### PR TITLE
datapath: Do not SNAT replies to outside

### LINKED ISSUE #12544: BPF-masq unexpectedly SNATs replies to outside
Follow up from https://github.com/cilium/cilium/pull/12482.

See https://github.com/cilium/cilium/pull/12482#discussion_r454691162.

### PR DESCRIPTION
**Pull request by brb**
See commit msgs.

Fix: #12544

### CODE REVIEW

**Comment by brb** [comment]
test-net-next

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-1.19-5.4

**Comment by brb** [comment]
test-1.20-4.19

**Comment by brb** [comment]
test-1.20-4.19

**Comment by brb** [comment]
4.19 is hitting the complexity issue :eyes:

**Comment by brb** [comment]
test-1.20-4.19

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Review by nebril — APPROVED** [review]

File: bpf/lib/conntrack.h [hunk 1]
```diff
@@ -602,6 +703,11 @@ static __always_inline int ct_lookup4(const void *map,
 	else
 		return DROP_CT_INVALID_HDR;
 
+	/*
+	err = ct_extract_ports4(ctx, off, dir,
+				tuple, &action, &tcp_flags, &has_l4_header);
+	*/
```
Comment (pchaigno) [inline bpf/lib/conntrack.h]: This should get inlined, no? Is there any difference between the function above and the code below? That is, do you know why it might result in a complexity issue?

If we're not going ahead with `ct_extract_ports4`, I think we should remove it rather than keep dead code in the hope we'll be able to uncomment some day. It doesn't look too hard to implement if we want to reconsider later on.

**Review by pchaigno — APPROVED** [review]

File: bpf/lib/conntrack.h (hunk 1 above)
Comment (kkourt) [reply bpf/lib/conntrack.h]: An argument for keeping it is that it explains why the various arguments that are not used in the current caller (`action`, `tcp_flags`, and `has_l4_header`) are there.

File: bpf/lib/conntrack.h [hunk 2]
```diff
@@ -575,6 +575,107 @@ static __always_inline void ct4_cilium_dbg_tuple(struct __ctx_buff *ctx, __u8 ty
...
+				break;
+
+			case ICMP_ECHOREPLY:
+				tuple->sport = identifier;
+				break;
+			case ICMP_ECHO:
+				tuple->dport = identifier;
+				/* fall through */
+			default:
+				*action = ACTION_CREATE;
```
Comment (kkourt) [inline bpf/lib/conntrack.h]: In the current use of the function, `action` is not used. But I'm curious, why do we set `ACTION_CREATE` which I guess means create a new conntrack entry for types which are not `ICMP_ECHO`.

**Review by kkourt — APPROVED** [review]
LGTM!

File: bpf/lib/conntrack.h (hunk 1 above)
Comment (pchaigno) [reply bpf/lib/conntrack.h]: :+1: to add a comment that explains that :slightly_smiling_face:

**Review by borkmann — APPROVED** [review]
modulo dead code, lgtm

File: bpf/lib/conntrack.h (hunk 1 above)
Comment (brb) [reply bpf/lib/conntrack.h]: > This should get inlined, no?

Yep, it was inlined.

> Is there any difference between the function above and the code below? That is, do you know why it might result in a complexity issue?

If think the error checking could have made a difference. However, it was not always reproducible :confused: 

> If we're not going ahead with ct_extract_ports4, I think we should remove it rather than keep dead code in the hope we'll be able to uncomment some day.

Are you referring to the commented out `ct_extract_port4` function invocation or the `ct_extract_port4` function itself?

@kkourt @pchaigno I'm going to remove the commented block, and also remove unused params in the `ct_extract_port4` function. Do we all ACK on this?

Comment (pchaigno) [reply bpf/lib/conntrack.h]: > I'm going to remove the commented block, and also remove unused params in the ct_extract_port4 function. Do we all ACK on this?

:+1:

Comment (kkourt) [reply bpf/lib/conntrack.h]: ACK!

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-net-next

**Comment by christarazi** [comment]
CI has passed and we have reviewer approval, marking ready to merge.
