### PR TITLE
fix panic in linuxNodeHandler.NodeDelete

### LINKED ISSUE #25543: Panic in linuxNodeHandler.NodeDelete
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We have a cluster of 474 nodes with cilium 1.12.9. Yesterday all cilium agents containers restarted simultaneously which caused traffic outage. All agents have the same stack trace in logs which is attached below. The issue happened at the same time as some nodes were recreated (deleted and added to the cluster by CAPI controller). Stack trace mentions node deletion logic so I guess this could trigger the problem.

### Cilium Version

1.12.9

### Kernel Version

5.4.0-146-generic

### Kubernetes Version

v1.21.14

### Sysdump

_No response_

### Relevant log output

```shell
{"error":"unable to lookup route for node \u003cnil\u003e: numerical result out of range","level":"warning","msg":"Unable to install direct node route {Ifindex: 0 Dst: 10.80.189.64/26 Src: \u003cnil\u003e Gw: \u003cnil\u003e Flags: [] Table: 0 Realm: 0}","subsys":"linux-datapath"}
{"level":"info","msg":"Iptables rules installed","subsys":"iptables"}
{"level":"info","msg":"Adding new proxy port rules for cilium-dns-egress:37503","proxy port name":"cilium-dns-egress","subsys":"proxy"}
{"level":"info","msg":"Iptables proxy rules installed","subsys":"iptables"}
{"level":"info","msg":"Serving cilium node monitor v1.2 API at unix:///var/run/cilium/monitor1_2.sock","subsys":"monitor-agent"}
{"level":"info","msg":"Validating configured node address ranges","subsys":"daemon"}
{"level":"info","msg":"Starting connection tracking garbage collector","subsys":"daemon"}
{"level":"info","msg":"Starting IP identity watcher","subsys":"ipcache"}
{"level":"info","msg":"Trace[817455089]: \"Reflector ListAndWatch\" name:github.com/cilium/cilium/pkg/k8s/watchers/cilium_endpoint.go:98 (18-May-2023 18:08:45.108) (total time: 41951ms):","subsys":"klog"}
{"level":"info","msg":"Trace[817455089]: ---\"Objects listed\" error:\u003cnil\u003e 41940ms (18:09:27.048)","subsys":"klog"}
{"level":"info","msg":"Trace[817455089]: [41.951798598s] [41.951798598s] END","subsys":"klog"}
{"deleteRatio":0.9,"level":"info","msg":"Conntrack garbage collector interval recalculated","newInterval":30000000000,"subsys":"map-ct"}
{"level":"info","msg":"Datapath signal listener running","subsys":"signal"}
{"level":"info","msg":"Initial scan of connection tracking completed","subsys":"ct-gc"}
Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
goroutine 304 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x2d719e0?, 0xc00b3c8960})
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x1?})
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
panic({0x2d719e0, 0xc00b3c8960})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/cilium/cilium/pkg/datapath/linux.(*linuxNodeHandler).deallocateIDForNode(0xc003e871f0?, 0xc003e87108?)
	/go/src/github.com/cilium/cilium/pkg/datapath/linux/node_ids.go:110 +0x335
github.com/cilium/cilium/pkg/datapath/linux.(*linuxNodeHandler).nodeDelete(0xc00056c420, 0xc003b1f8c0)
	/go/src/github.com/cilium/cilium/pkg/datapath/linux/node.go:1205 +0x291
github.com/cilium/cilium/pkg/datapath/linux.(*linuxNodeHandler).NodeDelete(_, {{0xc01294f470, 0x21}, {0xc000834bd0, 0x7}, {0x0, 0x0, 0x0}, 0xc00de68de8, {0x0, ...}, ...})
	/go/src/github.com/cilium/cilium/pkg/datapath/linux/node.go:1157 +0x19e
github.com/cilium/cilium/pkg/node/manager.(*Manager).NodeDeleted.func1({0x34f3048?, 0xc00056c420?})
	/go/src/github.com/cilium/cilium/pkg/node/manager/manager.go:653 +0x79
github.com/cilium/cilium/pkg/node/manager.(*Manager).Iter(0xc000a3f930?, 0xc0133a76e0)
	/go/src/github.com/cilium/cilium/pkg/node/manager/manager.go:186 +0xe6
github.com/cilium/cilium/pkg/node/manager.(*Manager).NodeDeleted(_, {{0xc01294f470, 0x21}, {0xc000834bd0, 0x7}, {0x0, 0x0, 0x0}, 0xc00de68de8, {0x0, ...}, ...})
	/go/src/github.com/cilium/cilium/pkg/node/manager/manager.go:652 +0x7c5
github.com/cilium/cilium/pkg/nodediscovery.(*NodeDiscovery).NodeDeleted(_, {{0xc01294f470, 0x21}, {0xc000834bd0, 0x7}, {0x0, 0x0, 0x0}, 0xc00de68de8, {0x0, ...}, ...})
	/go/src/github.com/cilium/cilium/pkg/nodediscovery/nodediscovery.go:218 +0x59
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).ciliumNodeInit.func3({0x2f10740?, 0xc009452e00?})
	/go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_node.go:114 +0x215
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:246
github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1({0x2aa76c0?, 0xc011372330?})
	/go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:129 +0x216
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc003463970, 0xc0066ec3c0)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:598 +0x566
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc003bdad80)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:184 +0x36
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x40d67f?)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x127e605?, {0x34b4560, 0xc0066f67b0}, 0x1, 0xc005a834a0)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc003bdade8?, 0x3b9aca00, 0x0, 0x0?, 0x7fd053a44de8?)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:92
k8s.io/client-go/tools/cache.(*controller).Run(0xc003bdad80, 0xc005a834a0)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:155 +0x2c5
created by github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).ciliumNodeInit
	/go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_node.go:134 +0x62a
{"level":"error","msg":"Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)","subsys":"klog"}
{"level":"error","msg":"goroutine 304 [running]:","subsys":"klog"}
{"level":"error","msg":"k8s.io/apimachinery/pkg/util/runtime.logPanic({0x2d719e0?, 0xc00b3c8960})","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99","subsys":"klog"}
{"level":"error","msg":"k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x1?})","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75","subsys":"klog"}
{"level":"error","msg":"panic({0x2d719e0, 0xc00b3c8960})","subsys":"klog"}
{"level":"error","msg":"\t/usr/local/go/src/runtime/panic.go:838 +0x207","subsys":"klog"}
{"level":"error","msg":"github.com/cilium/cilium/pkg/datapath/linux.(*linuxNodeHandler).deallocateIDForNode(0xc003e871f0?, 0xc003e87108?)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/pkg/datapath/linux/node_ids.go:110 +0x335","subsys":"klog"}
{"level":"error","msg":"github.com/cilium/cilium/pkg/datapath/linux.(*linuxNodeHandler).nodeDelete(0xc00056c420, 0xc003b1f8c0)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/pkg/datapath/linux/node.go:1205 +0x291","subsys":"klog"}
{"level":"error","msg":"github.com/cilium/cilium/pkg/datapath/linux.(*linuxNodeHandler).NodeDelete(_, {{0xc01294f470, 0x21}, {0xc000834bd0, 0x7}, {0x0, 0x0, 0x0}, 0xc00de68de8, {0x0, ...}, ...})","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/pkg/datapath/linux/node.go:1157 +0x19e","subsys":"klog"}
{"level":"error","msg":"github.com/cilium/cilium/pkg/node/manager.(*Manager).NodeDeleted.func1({0x34f3048?, 0xc00056c420?})","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/pkg/node/manager/manager.go:653 +0x79","subsys":"klog"}
{"level":"error","msg":"github.com/cilium/cilium/pkg/node/manager.(*Manager).Iter(0xc000a3f930?, 0xc0133a76e0)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/pkg/node/manager/manager.go:186 +0xe6","subsys":"klog"}
{"level":"error","msg":"github.com/cilium/cilium/pkg/node/manager.(*Manager).NodeDeleted(_, {{0xc01294f470, 0x21}, {0xc000834bd0, 0x7}, {0x0, 0x0, 0x0}, 0xc00de68de8, {0x0, ...}, ...})","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/pkg/node/manager/manager.go:652 +0x7c5","subsys":"klog"}
{"level":"error","msg":"github.com/cilium/cilium/pkg/nodediscovery.(*NodeDiscovery).NodeDeleted(_, {{0xc01294f470, 0x21}, {0xc000834bd0, 0x7}, {0x0, 0x0, 0x0}, 0xc00de68de8, {0x0, ...}, ...})","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/pkg/nodediscovery/nodediscovery.go:218 +0x59","subsys":"klog"}
{"level":"error","msg":"github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).ciliumNodeInit.func3({0x2f10740?, 0xc009452e00?})","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_node.go:114 +0x215","subsys":"klog"}
{"level":"error","msg":"k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:246","subsys":"klog"}
{"level":"error","msg":"github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1({0x2aa76c0?, 0xc011372330?})","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:129 +0x216","subsys":"klog"}
{"level":"error","msg":"k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc003463970, 0xc0066ec3c0)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:598 +0x566","subsys":"klog"}
{"level":"error","msg":"k8s.io/client-go/tools/cache.(*controller).processLoop(0xc003bdad80)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:184 +0x36","subsys":"klog"}
{"level":"error","msg":"k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x40d67f?)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157 +0x3e","subsys":"klog"}
{"level":"error","msg":"k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x127e605?, {0x34b4560, 0xc0066f67b0}, 0x1, 0xc005a834a0)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158 +0xb6","subsys":"klog"}
{"level":"error","msg":"k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc003bdade8?, 0x3b9aca00, 0x0, 0x0?, 0x7fd053a44de8?)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:135 +0x89","subsys":"klog"}
{"level":"error","msg":"k8s.io/apimachinery/pkg/util/wait.Until(...)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:92","subsys":"klog"}
{"level":"error","msg":"k8s.io/client-go/tools/cache.(*controller).Run(0xc003bdad80, 0xc005a834a0)","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:155 +0x2c5","subsys":"klog"}
{"level":"error","msg":"created by github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).ciliumNodeInit","subsys":"klog"}
{"level":"error","msg":"\t/go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_node.go:134 +0x62a","subsys":"klog"}
{"level":"fatal","msg":"Panic in Kubernetes runtime handler","subsys":"k8s"}
{"level":"info","msg":"Regenerating restored endpoints","numRestored":7,"subsys":"daemon"}
```

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by cyclinder**
Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: https://github.com/cilium/cilium/issues/25543
```release-note
Fix crash of cilium-agent happening when a remote node without node IP addresses is removed.
```

### CODE REVIEW

File: pkg/datapath/linux/node_ids.go [hunk 1]
```diff
@@ -126,6 +126,10 @@ func (n *linuxNodeHandler) allocateIDForNode(node *nodeTypes.Node) uint16 {
 
 // deallocateIDForNode deallocates the node ID for the given node, if it was allocated.
 func (n *linuxNodeHandler) deallocateIDForNode(oldNode *nodeTypes.Node) {
+	if len(oldNode.IPAddresses) == 0 {
+		return
+	}
+
 	nodeID := n.nodeIDsByIPs[oldNode.IPAddresses[0].IP.String()]
```
Comment (bimmlerd) [inline pkg/datapath/linux/node_ids.go]: Wouldn't the following be a cleaner fix? In symmetry with `allocateIDForNode` above,  `getNodeIDForNode` has a fallback ID of zero if there are no IPs.

```suggestion
	nodeID := n.getNodeIDForNode(oldNode)
```

Comment (cyclinder) [reply pkg/datapath/linux/node_ids.go]: sorry, I didn't notice it, now updated.

Comment (pchaigno) [reply pkg/datapath/linux/node_ids.go]: That function was introduced just yesterday so that might be why you didn't notice when preparing the patch :smile:

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
Can you provide details on how this causes a panic? Do you have a stacktrace for the panic and could you include it in the commit description?

**Comment by bimmlerd** [comment]
> Can you provide details on how this causes a panic? Do you have a stacktrace for the panic and could you include it in the commit description?

See https://github.com/cilium/cilium/issues/25543 for details on the panic. The commit msg could use a link too, though :)

**Comment by cyclinder** [comment]
hi @pchaigno, I have updated the commit message, Please tell me if you feel this is good.

**Comment by pchaigno** [comment]
> hi @pchaigno, I have updated the commit message, Please tell me if you feel this is good.

I think the formatting is broken as there are no newlines. You will also need to squash your two commits in one.

**Comment by cyclinder** [comment]
It seems `git rebase` was broken, Now cilium use main or master? 🤔

**Comment by pchaigno** [comment]
Cilium uses main and your commit now looks good to me.

Do you know under what conditions the panic happens? I'd like to write a release note and that requires understanding why our CI didn't catch this. Is there something special about your deployment? Why don't nodes have IP addresses? :thinking:

**Comment by cyclinder** [comment]
sorry, I can't explain the root cause, but according to https://github.com/cilium/cilium/issues/25543's description, this happens in the case of node rebuilding (deleted and created), and the node loses its IP, maybe ask @egsysoev for more details if needed.

**Comment by egsysoev** [comment]
I am the reporter of [#25543](https://github.com/cilium/cilium/issues/25543). I can't reproduce the issue, but it happened two times during the abnormal shutdown of node:
1) esxi hypervisor failed and rebooted.
2) VMs with attached GPU device could not be migrated to another hypervisor.
3) Cluster API operator deleted the failed VMs: drain, delete node from k8s, remove VM from esxi.
4) Cluster API operator created new VMs.

**Comment by pchaigno** [comment]
Thanks for the additional context @egsysoev!

> Cluster API operator deleted the failed VMs: drain, delete node from k8s, remove VM from esxi.

So the VM wasn't fully provisioned yet when it was deleted? If so, that could explain how the deleted node doesn't have IP addresses.

**Review by ldelossa — APPROVED** [review]

**Comment by cyclinder** [comment]
@pchaigno Hi, It's time to merge this PR?

**Review by jrajahalme — APPROVED** [review]

**Comment by cyclinder** [comment]
I see, thanks for the clarification @pchaigno

**Comment by ti-mo** [comment]
@cyclinder Sorry to pull you in the other direction; would you be able to rebase to pick up the recent changes to CI? (Jenkins is no longer)

**Review by ti-mo — APPROVED** [review]

**Comment by gandro** [comment]
ci-gingo failed with `ssh: connect to host localhost port 2222: Connection refused` - restarting affected jobs
