### PR TITLE
deflake endpointmanager tests

### LINKED ISSUE #26630: CI: integration-test: Test/EndpointManagerSuite/TestmarkAndSweep - obtained 4, expected 5
## CI failure

```
 INTEGRATION_TESTS=true CGO_ENABLED=0 go test  -mod=vendor -tags=osusergo -ldflags "-X github.com/cilium/cilium/pkg/datapath.DatapathSHA256=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" ./... -timeout 600s  -json -covermode=count -coverprofile=coverage.out | tparse
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃   FAIL  package: github.com/cilium/cilium/pkg/endpointmanager   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

--- FAIL: Test (0.12s)
--- FAIL: Test/EndpointManagerSuite (0.12s)
--- FAIL: Test/EndpointManagerSuite/TestmarkAndSweep (0.00s)

level=info msg="New endpoint" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="New endpoint" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="New endpoint" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=7 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="New endpoint" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2 ipv4= ipv6= k8sPodName=/ subsys=endpoint
    gc_test.go:43: 
        ... obtained int = 4
        ... expected int = 5
```

- [Failed run](https://github.com/cilium/cilium/actions/runs/5455927968/jobs/9928035989)
- [Impacted PR](https://github.com/cilium/cilium/pull/26629)
- No artifact

### LINKED ISSUE #27837: CI: integration-test: Test/EndpointManagerSuite/TestLookupIPv4
## CI failure

```
INTEGRATION_TESTS=true CGO_ENABLED=0 go test  -mod=vendor -tags=osusergo -ldflags "-X github.com/cilium/cilium/pkg/datapath.DatapathSHA256=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" ./... -timeout 600s  -json -covermode=count -coverprofile=coverage.out | tparse
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃   FAIL  package: github.com/cilium/cilium/pkg/endpointmanager   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

--- FAIL: Test (0.16s)
--- FAIL: Test/EndpointManagerSuite (0.16s)
--- FAIL: Test/EndpointManagerSuite/TestLookupIPv4 (0.01s)

    manager_test.go:590: 
        ... obtained *endpoint.Endpoint = (*endpoint.Endpoint)(nil) (<nil>)
        ... expected *endpoint.Endpoint = &endpoint.Endpoint{owner:(*endpointmanager.EndpointManagerSuite)(0xc0008565f0), ...
        +}
        
        

make: *** [Makefile:130: integration-tests] Error 1
```

- [Failed run](https://github.com/cilium/cilium/issues/26630)
- [Impacted PR](https://github.com/cilium/cilium/pull/27815)
- No artifact
- [Very similar issue](https://github.com/cilium/cilium/issues/26630)

### LINKED ISSUE #28878: CI: Travis: Test/EndpointManagerSuite/TestLookup fails due to unexpected endpoint
Failure:
https://app.travis-ci.com/github/cilium/cilium/builds/266927007

The `endpointmanager` has a test at the start of `TestLookup` which ensures that endpoint 1234 doesn't exist. It's the first test in the set of lookup tests. It appears to be flaky, sometimes failing since it actually finds an endpoint unexpectedly.

Unclear whether this is newly introduced by recent endpointmanager changes, or simply a rare case of leftover state from running another test.

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃   FAIL  package: github.com/cilium/cilium/pkg/endpointmanager   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
--- FAIL: Test (0.11s)
--- FAIL: Test/EndpointManagerSuite (0.11s)
--- FAIL: Test/EndpointManagerSuite/TestLookup (0.00s)
level=info msg="New endpoint" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1234 ipv4= ipv6= k8sPodName=/ subsys=endpoint
    manager_test.go:439: 
        ... value *endpoint.Endpoint = &endpoint.Endpoint{owner:(*endpointmanager.EndpointManagerSuite)(0x400011d1b0), policyGetter:(*endpointmanager.EndpointManagerSuite)(0x400011d1b0), namedPortsGetter:(*testipcache.MockIPCache)(0x3ab01e0), ID:0x4d2, createdAt:time.Time{wall:0xc1481d374e0726c5, ext:29863870, loc:(*time.Location)(0x3a79920)}, mutex:lock.RWMutex{internalRWMutex:lock.internalRWMutex{RWMutex:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:atomic.Int32{_:atomic.noCopy{}, v:0}, readerWait:atomic.Int32{_:atomic.noCopy{}, v:0}}}}, containerName:atomic.Pointer[string]{_:[0]*string{}, _:atomic.noCopy{}, v:(unsafe.Pointer)(nil)}, containerID:atomic.Pointer[string]{_:[0]*string{}, _:atomic.noCopy{}, v:(unsafe.Pointer)(nil)}, dockerNetworkID:"", dockerEndpointID:"", ifName:"", ifIndex:0, containerIfName:"", disableLegacyIdentifiers:false, OpLabels:labels.OpLabels{Custom:labels.Labels{}, OrchestrationIdentity:labels.Labels{}, Disabled:labels.Labels{}, OrchestrationInfo:labels.Labels{}}, identityRevision:0, bps:0x0, mac:mac.MAC(nil), IPv6:netip.Addr{addr:netip.uint128{hi:0x0, lo:0x0}, z:(*intern.Value)(nil)}, IPv6IPAMPool:"", IPv4:netip.Addr{addr:netip.uint128{hi:0x0, lo:0x0}, z:(*intern.Value)(nil)}, IPv4IPAMPool:"", nodeMAC:mac.MAC(nil), SecurityIdentity:(*identity.Identity)(nil), hasSidecarProxy:false, policyMap:(*policymap.PolicyMap)(nil), PolicyMapPressureUpdater:(*endpointmanager.policyMapPressure)(0x4000400318), Options:(*option.IntOptions)(0x40000e59b0), status:(*endpoint.EndpointStatus)(0x40000d4240), DNSRules:restore.DNSRules(nil), DNSHistory:(*fqdn.DNSCache)(0x40005f1e00), DNSZombies:(*fqdn.DNSZombieMappings)(0x40000d4200), dnsHistoryTrigger:(*trigger.Trigger)(0x400029e1e0), state:"", bpfHeaderfileHash:"", K8sPodName:"", K8sNamespace:"", pod:atomic.Pointer[github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1.Pod]{_:[0]*v1.Pod{}, _:atomic.noCopy{}, v:(unsafe.Pointer)(nil)}, k8sPorts:atomic.Pointer[github.com/cilium/cilium/pkg/types.NamedPortMap]{_:[0]*types.NamedPortMap{}, _:atomic.noCopy{}, v:(unsafe.Pointer)(nil)}, logLimiter:logging.Limiter{bucket:(*rate.Limiter)(0x40005f4050)}, policyRevision:0x0, policyRevisionSignals:map[*endpoint.policySignal]bool(nil), proxyPolicyRevision:0x0, proxyStatisticsMutex:lock.RWMutex{internalRWMutex:lock.internalRWMutex{RWMutex:sync.RWMutex{w:sync.Mutex{state:0, sema:0x0}, writerSem:0x0, readerSem:0x0, readerCount:atomic.Int32{_:atomic.noCopy{}, v:0}, readerWait:atomic.Int32{_:atomic.noCopy{}, v:0}}}}, proxy:(*endpoint.FakeEndpointProxy)(0x3ab01e0), proxyStatistics:map[string]*models.ProxyStatistics(nil), nextPolicyRevision:0x0, forcePolicyCompute:false, buildMutex:lock.Mutex{internalMutex:lock.internalMutex{Mutex:sync.Mutex{state:0, sema:0x0}}}, logger:atomic.Pointer[github.com/sirupsen/logrus.Entry]{_:[0]*logrus.Entry{}, _:atomic.noCopy{}, v:(unsafe.Pointer)(0x400054c1c0)}, policyLogger:atomic.Pointer[github.com/sirupsen/logrus.Entry]{_:[0]*logrus.Entry{}, _:atomic.noCopy{}, v:(unsafe.Pointer)(nil)}, controllers:(*controller.Manager)(0x40005988c0), realizedRedirects:map[string]uint16(nil), ctCleaned:false, hasBPFProgram:(chan struct {})(0x4000103140), selectorPolicy:policy.SelectorPolicy(nil), desiredPolicy:(*policy.EndpointPolicy)(0x40005f4000), realizedPolicy:(*policy.EndpointPolicy)(0x40005f4000), visibilityPolicy:(*policy.VisibilityPolicy)(nil), eventQueue:(*eventqueue.EventQueue)(0x40001e5440), skippedRegenerationLevel:0, DatapathConfiguration:models.EndpointDatapathConfiguration{DisableSipVerification:false, ExternalIpam:false, InstallEndpointRoute:false, RequireArpPassthrough:false, RequireEgressProg:false, RequireRouting:(*bool)(nil)}, aliveCtx:(*context.cancelCtx)(0x40005f40a0), aliveCancel:(context.CancelFunc)(0x17b280), regenFailedChan:(chan struct {})(0x40001031a0), allocator:(*testidentity.MockIdentityAllocator)(0x40000e5620), isIngress:false, isHost:false, noTrackPort:0x0, ciliumEndpointUID:"", reporterScope:cell.Scope(nil), closeHealthReporter:(func())(nil)} ("{\n  \"ID\": 1234,\n  \"ContainerName\": \"\",\n  \"DockerNetworkID\": \"\",\n  \"DockerEndpointID\": \"\",\n  \"IfName\": \"\",\n  \"IfIndex\": 0,\n  \"ContainerIfName\": \"\",\n  \"DisableLegacyIdentifiers\": false,\n  \"OpLabels\": {\n    \"Custom\": {},\n    \"OrchestrationIdentity\": {},\n    \"Disabled\": {},\n    \"OrchestrationInfo\": {}\n  },\n  \"LXCMAC\": \"\",\n  \"IPv6\": \"\",\n  \"IPv6IPAMPool\": \"\",\n  \"IPv4\": \"\",\n  \"IPv4IPAMPool\": \"\",\n  \"NodeMAC\": \"\",\n  \"SecLabel\": null,\n  \"Options\": {\n    \"map\": {\n      \"ConntrackAccounting\": 0,\n      \"ConntrackLocal\": 0,\n      \"Debug\": 0,\n      \"DebugLB\": 0,\n      \"DebugPolicy\": 0,\n      \"DropNotification\": 0,\n      \"MonitorAggregationLevel\": 0,\n      \"PolicyAuditMode\": 0,\n      \"PolicyVerdictNotification\": 0,\n      \"SourceIPVerification\": 0,\n      \"TraceNotification\": 0\n    }\n  },\n  \"DNSRules\": null,\n  \"DNSHistory\": [],\n  \"DNSZombies\": {},\n  \"K8sPodName\": \"\",\n  \"K8sNamespace\": \"\",\n  \"DatapathConfiguration\": {},\n  \"CiliumEndpointUID\": \"\"\n}")
        ... Test Name: endpoint does not exist
```

### PR DESCRIPTION
**Pull request by bimmlerd**
This series of patches deflakes the endpoint manager tests. Four different flakes were observed when running just the `endpointmanager` pkg test in a loop, after this PR I achieved `31m55s: 46344 runs so far, 0 failures` which implies a high likelihood that any potentially remaining flakes are highly unlikely to occur.

There was a trivial data race in the pressure metrics _test_, fixed by using an atomic value.

This PR refactors the endpointmanager EP identifier allocation logic away from using a single, global identity pool, as that inherently causes flakes in tests sharing that pool. Specifically, there was a call to `mgr.expose` which did not check the error - the error was that in the global pool, one of the identities `[1, 3, 5, 7]` had already been allocated, and hence the exposing failed. Fixed by creating a new allocation pool for each new manager.

Further tests also didn't check `expose` errors, but these were inconsequential once the global ID pool was removed. Fixed the checks anyway, for good measure.

In addition, `TestLookup` would fail iff the EP allocated would by chance get ID `1234`.

The commits attempt to be somewhat readable in sequence, but the whole change isn't massive either.

Fixes: #26630
Fixes: #28878
Fixes: #27837

### CODE REVIEW

File: pkg/endpointmanager/idallocator/allocator_test.go [hunk 1]
```diff
@@ -6,100 +6,93 @@ package idallocator
...
 
 	for i := minID; i <= maxID; i++ {
 		id := Allocate()
-		c.Assert(id, Not(Equals), uint16(0))
+		assert.NotZero(t, id)
 
 		// check if same ID is returned more than once
 		_, ok := idsReturned[id]
-		c.Assert(ok, Equals, false)
+		assert.False(t, ok)
```
Comment (giorio94) [inline pkg/endpointmanager/idallocator/allocator_test.go]: Nit. `assert.NotContains` is probably a bit more idiomatic.

File: pkg/endpointmanager/idallocator/allocator_test.go [hunk 2]
```diff
@@ -6,100 +6,93 @@ package idallocator
...
 
 	for i := minID; i <= maxID-2; i++ {
 		id := Allocate()
-		c.Assert(id, Not(Equals), uint16(0))
+		assert.NotZero(t, id)
 
 		// check if same ID is returned more than once
 		_, ok := idsReturned[id]
-		c.Assert(ok, Equals, false)
+		assert.False(t, ok)
```
Comment (giorio94) [inline pkg/endpointmanager/idallocator/allocator_test.go]: Same here.

**Review by giorio94 — APPROVED** [review]
Thanks!

**Comment by chancez** [comment]
While we're in there, would it be possible to fix the spelling of `fakeGague`? Not sure if that's gonna make for painful merge conflicts or not, so feel free to ignore if it's gonna make it harder to merge.

**Review by chancez — APPROVED** [review]

File: pkg/endpointmanager/allocator.go [hunk 3]
```diff
@@ -14,21 +15,27 @@ const (
...
+	return &epIDAllocator{
+		pool: idpool.NewIDPool(minID, maxID),
+	}
+}
 
-// ReallocatePool starts over with a new pool. This function is only used for
+// reallocatePool starts over with a new pool. This function is only used for
 // tests and its implementation is not optimized for production.
-func ReallocatePool() {
+func (a *epIDAllocator) reallocatePool(t testing.TB) {
```
Comment (tklauser) [inline pkg/endpointmanager/allocator.go]: `t` looks unused in the method. Importing `testing` in non `*_test.go` files is kind of unfortunate, so maybe we could avoid that?

Comment (bimmlerd) [reply pkg/endpointmanager/allocator.go]: The idea was to ensure that we don't use this method outside of the test context; but it is used (via `RemoveAll`) from other package's tests, so putting it in `_test` wasn't an option. Is there some other way we can mark this as test-only code?

Comment (tklauser) [reply pkg/endpointmanager/allocator.go]: Ah right. I didn't consider that this is transitively also used in other package's tests. In that case I don't think there's any other way than exposing the method in non-test code :disappointed: I know people seldomly read godoc comments and we want to prevent use of the method outside of test code, but having `testing` imports in non-test code is a bit of a code smell as well. At least having a comment on both `reallocatePool` and `RemoveAll` about the purpose of the `t` parameter would be nice.

Comment (tklauser) [reply pkg/endpointmanager/allocator.go:30]: Ah right. I didn't consider that this is transitively also used in other package's tests. In that case I don't think there's any other way than exposing the method in non-test code :disappointed: I know people seldomly read godoc comments and we want to prevent use of the method outside of test code, but having `testing` imports in non-test code is a bit of a code smell as well. At least having a comment on both `reallocatePool` and `RemoveAll` about the purpose of the `t` parameter would be nice.

**Comment by bimmlerd** [comment]
CI triage:

- ci-integration hit https://github.com/cilium/cilium/issues/31466 in https://github.com/cilium/cilium/actions/runs/8374987537/job/22931388760#step:10:632. Repro'd locally with `-race`, posted race details to issue for Tom to look into the fix.
- ci-eks failed setting up the cluster (prior to installing cilium). infra issue, it happens.
- ci-e2e failed in `outside-to-ingress-service/outside-to-ingress-service/curl-ingress-service-0: cilium-test/host-netns-non-cilium-4rm4f (172.18.0.3) -> /cilium-ingress-ingress-service (cilium-ingress-ingress-service.:80)` with exit code 7 (`Failed to connect to host`)
` which appears to be https://github.com/cilium/cilium/issues/30717, which is in the process of being fixed :heart_eyes_cat: 
- ci-ipsec-upgrade failed in `client-egress-l7-named-port/pod-to-world/http-to-one.one.one.one-1:` [here](https://github.com/cilium/cilium/actions/runs/8374987775/job/22931395171#step:19:620) with `curl: (28) Resolving timed out after 2003 milliseconds\n` which sounds like a DNS issue. Possibly https://github.com/cilium/cilium/issues/22217.

File: pkg/endpointmanager/allocator.go (hunk 3 above)
Comment (tklauser) [reply pkg/endpointmanager/allocator.go]: Another option would be to `panic` on [`testing.Testing()`](https://pkg.go.dev/testing#Testing) being `true` in `RemoveAll`. That way we'd not have to pass down the `*testing.TB` (which someone could potentially still provide in production code :ninja:).

Comment (bimmlerd) [reply pkg/endpointmanager/allocator.go]: I've figured out a solution which allows us to just remove `RemoveAll` from non-package-local testing code, and hence I moved it to _test.go :)

**Review by tklauser — APPROVED** [review]

**Review by dylandreimerink — APPROVED** [review]
Datapath owned files look good to me!
