### PR TITLE
Fix bug with `toServices` policy where service backend churn left stale CIDR identities

### LINKED ISSUE #20477: Deleting service selected by ToServices policy rules can cause policy denies until agent restart
When two services have the same backends and a same label selected in `toServices` rule in a network policy, the internal storage of the policy structure in the form of "generated CIDRs" are removed from the datapath when one of the services is deleted. This can happen even though the other service should still be allowed by policy. As a result, traffic can be dropped for the remaining service.

Likely affects versions v1.8.x onwards.

### PR DESCRIPTION
**Pull request by christarazi**
- k8s: Plumb old Endpoints object through handlers
- k8s: Fix toServices rule translation cleanup
- k8s: Add test for RuleTranslator.Translate()
- k8s: Remove unnecessary AllocatePrefixes from RuleTranslator

Fixes: #20477

---

Main commit "k8s: Fix toServices rule translation cleanup" will be pasted below for ease of review:
> Previously, toServices-based rules did not properly cleanup CIDR
identities. When service backends were removed or changed, the deletion
logic acted on the new object rather than on the old object, thus
the entries that were supposed to be deleted were simply added back in
generateToCidrFromEndpoint().
>
> Fix this by passing the deletion logic the old endpoint object state
and performing a diff between the old and new states.

### CODE REVIEW

**Comment by christarazi** [comment]
cc @squeed @joestringer for opening https://github.com/cilium/cilium/issues/20477

File: operator/watchers/k8s_service_sync.go [hunk 1]
```diff
@@ -229,7 +229,7 @@ func endpointsInit(slimClient slimclientset.Interface, swgEps *lock.StoppableWai
 						if oldk8sEP.DeepEqual(newk8sEP) {
 							return
 						}
-						K8sSvcCache.UpdateEndpoints(newk8sEP, swgEps)
+						K8sSvcCache.UpdateEndpoints(oldk8sEP, newk8sEP, swgEps)
```
Comment (giorio94) [inline operator/watchers/k8s_service_sync.go]: Directly passing the old object will become problematic once starting to use `Resource[Endpoints]` (https://github.com/cilium/cilium/pull/23977), as no longer available as part of the event. Would it be possible to retrieve the old endpoints from the already existing `ServiceCache.endpoints[<service-name>]` map (https://github.com/cilium/cilium/blob/pr%2Fchristarazi%2Fto-services-fixups/pkg/k8s/service_cache.go#L88)?

Comment (joamaki) [reply operator/watchers/k8s_service_sync.go]: Yep, once https://github.com/cilium/cilium/pull/23977/ is merged you don't have the old object anymore so this approach won't work. The right approach is for `ServiceCache` to keep the previous endpoint. I'd wait until #23977 is merged before refactoring as it changes a lot of the code in this PR (all the different endpoint variants will be gone)

**Review by joamaki — CHANGES_REQUESTED** [review]

File: operator/watchers/k8s_service_sync.go (hunk 1 above)
Comment (christarazi) [reply operator/watchers/k8s_service_sync.go]: Thanks. PR should be updated now!

File: pkg/k8s/service_cache.go [hunk 2]
```diff
@@ -291,17 +295,25 @@ func (s *ServiceCache) UpdateEndpoints(newEndpoints *Endpoints, swg *lock.Stoppa
 
 	eps.Upsert(esID.EndpointSliceName, newEndpoints)
 
+	oldEPs, _ := cache[key]
+	// cache is optional as it's only needed for Agents (not for Operator). If
+	// it's nil, then we don't expect to use oldEPs anyway.
+	if cache != nil {
+		cache[key] = newEndpoints
+	}
```
Comment (giorio94) [inline pkg/k8s/service_cache.go]: Why is this external cache necessary? I think it should be possible to retrieve the oldEPs from `eps.epSlices[esID.EndpointSliceName]`, which is already kept in sync.

Comment (christarazi) [reply pkg/k8s/service_cache.go]: Good point, removed!

**Review by joamaki — APPROVED** [review]

File: pkg/k8s/watchers/watcher.go [hunk 3]
```diff
@@ -637,7 +642,11 @@ func (k *K8sWatcher) k8sServiceHandler() {
 				return
 			}
 
-			translator := k8s.NewK8sTranslator(event.ID, *event.Endpoints, true, svc.Labels, true)
+			var oldEP k8s.Endpoints
+			if event.OldEndpoints != nil {
+				oldEP = *event.OldEndpoints
+			}
```
Comment (giorio94) [inline pkg/k8s/watchers/watcher.go]: It seems to me that `OldEndpoints` is never set when the event type is `DeleteService`. IIUC the logic here should be adapted to use `*event.Endpoints` as the list of old endpoints.

File: pkg/k8s/service_cache.go [hunk 4]
```diff
@@ -297,11 +302,12 @@ func (s *ServiceCache) UpdateEndpoints(newEndpoints *Endpoints, swg *lock.Stoppa
...
-			Action:    UpdateService,
-			ID:        esID.ServiceID,
-			Service:   svc,
-			Endpoints: endpoints,
-			SWG:       swg,
+			Action:       UpdateService,
+			ID:           esID.ServiceID,
+			Service:      svc,
+			Endpoints:    endpoints,
+			OldEndpoints: oldEPs,
```
Comment (giorio94) [inline pkg/k8s/service_cache.go:311]: Should `OldEndpoints` be set also in the other cases in which an `UpdateService` event is emitted? IMO it is mainly necessary in the `DeleteEndpoints` method below.

**Review by giorio94 — COMMENTED** [review]
A couple of comments/questions about the OldEndpoints propagation, while the rest of the changes looks good to me.

File: pkg/k8s/watchers/watcher.go (hunk 3 above)
Comment (christarazi) [reply pkg/k8s/watchers/watcher.go]: There's no notion of "old" in other event types like "delete", there's only the "current" object. Only the "update" event type has "old" and "new", so we don't need to set `OldEndpoints` for any other event type besides `UpdateService`.

File: pkg/k8s/service_cache.go (hunk 4 above)
Comment (christarazi) [reply pkg/k8s/service_cache.go:311]: Given https://github.com/cilium/cilium/pull/25687#discussion_r1223262168, can you elaborate why it's necessary?

File: pkg/k8s/watchers/watcher.go (hunk 3 above)
Comment (giorio94) [reply pkg/k8s/watchers/watcher.go]: I mean, I agree that in case of deletes all the endpoints that are part of the event are the old ones (and it is not necessary to to set `OldEndpoints`). What seems strange to me is that they are passed as `newEPs` to `k8s.NewK8sTranslator()`, and that AFAIU that wil result in `result.PrefixesToRelease` being always empty.

File: pkg/k8s/service_cache.go (hunk 4 above)
Comment (giorio94) [reply pkg/k8s/service_cache.go:311]: I'm referring in particular to the event generated [here](https://github.com/cilium/cilium/blob/pr%2Fchristarazi%2Fto-services-fixups/pkg/k8s/service_cache.go#L331-L340). Essentially, that happens when one endpointslice gets deleted, triggering an update event with the remaining endpoints for that service. Since `OldEndpoints` is not propagated, the corresponding `PrefixesToRelease` rules will not be eventually generated by the `K8sTranslator`.

Comment (giorio94) [reply pkg/k8s/service_cache.go:311]: There's also another aspect that I didn't realize earlier, `OldEndpoints` will contain the previous list of endpoints from a given endpointslice, while `Endpoints` the ones merged from all endpointslices. It seems to me that it should not create problems though.

File: pkg/k8s/watchers/watcher.go (hunk 3 above)
Comment (christarazi) [reply pkg/k8s/watchers/watcher.go]: Ah now I understand what you're referring to. 

So notice the 4th parameter to `NewK8sTranslator()` -- `revert bool`. This means it will take the "new endpoints" and do the inverse operation, as in it will release them instead of add them.

Given that, I should simply remove the highlighted code here to avoid confusion and just pass an empty `Endpoints` object so it's clearer. Good catch. I probably just added this snippet of code to be consistent with the `UpdateService` case, but then later realized that the delete path does not need the "old" object and forgot to cleanup this code.

File: pkg/k8s/service_cache.go (hunk 4 above)
Comment (christarazi) [reply pkg/k8s/service_cache.go:311]: In the end, I've set the `OldEndpoints` for all `UpdateService` events. Please take another look. Thanks for double checking!

File: pkg/k8s/watchers/watcher.go (hunk 3 above)
Comment (giorio94) [reply pkg/k8s/watchers/watcher.go]: Right, I completely missed the revert parameter. Thanks for the clarification.

I still think there's an issue though (due to the subsequent modifications). The only place where revert seems to be used is [here](https://github.com/cilium/cilium/blob/pr%2Fchristarazi%2Fto-services-fixups/pkg/k8s/rule_translate.go#L48-L53), where it guards the population of the egress rules (which is obviously correct). But with the new changes `depopulateEgress` [operates on the `OldEndpoint` object](https://github.com/cilium/cilium/blob/pr%2Fchristarazi%2Fto-services-fixups/pkg/k8s/rule_translate.go#L83). And given that it is always empty nothing will happen. I feel that the revert parameter could be dropped, swapping the parameters in case of deletions:

```go
translator := k8s.NewK8sTranslator(event.ID, *event.Endpoints, k8s.Endpoints{}, svc.Labels)
```

File: pkg/k8s/service_cache.go (hunk 4 above)
Comment (giorio94) [reply pkg/k8s/service_cache.go:311]: Makes sense to me, thanks! Another possibility might be to just use `correlateEndpoints` to obtain the full list of old endpoints before updating the current one, but as mentioned above it shouldn't matter much.

Comment (giorio94) [reply pkg/k8s/service_cache.go:311]: 🤔 I see that `OldEndpoints` and `Endpoints` are always the same for updates from remote service backends. Shouldn't they be different? (I'm not 100% sure about how this feature should play with global services)

Comment (christarazi) [reply pkg/k8s/service_cache.go:311]: `toServices` (currently) only supports backends that are outside of the cluster (world), and not pod-based backends.

File: pkg/k8s/watchers/watcher.go (hunk 3 above)
Comment (christarazi) [reply pkg/k8s/watchers/watcher.go]: Thanks! 

I opted to keep the revert boolean for now (followup on removing `revert` tracked [here](https://github.com/cilium/cilium/issues/26094)) and just go for the quickest change, which is that the old and new object are set to the same object with `revert=true`.

File: pkg/k8s/service_cache.go (hunk 4 above)
Comment (giorio94) [reply pkg/k8s/service_cache.go:311]: The same logic is also used in the external workloads case, and IIUC in that case the backends processed through that function might be outside of the cluster. Still that is most likely an extremely rare condition.

**Review by giorio94 — APPROVED** [review]
/lgtm

**Review by youngnick — APPROVED** [review]

File: pkg/k8s/service_cache.go (hunk 4 above)
Comment (christarazi) [reply pkg/k8s/service_cache.go:311]: @giorio94 Could you file a followup issue so that we don't forget this?

**Comment by christarazi** [comment]
Thanks for the very thorough review @giorio94!

File: pkg/k8s/service_cache.go (hunk 4 above)
Comment (giorio94) [reply pkg/k8s/service_cache.go:311]: https://github.com/cilium/cilium/issues/26176
