### PR TITLE
eni: fix new node not triggering creation of ENI with fix deadlock

### LINKED ISSUE #20678: ENI: new node not does not immediately trigger the creation of Eni
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. New node add to cluster, it not immediately trigger the creation of Eni.  Until resync period is triggered, eni be created in new node. so agent in waiting eni create max duration is 1min. 
2. It happend in aws and alibabacloud and azure.
3. it also find log in issue https://github.com/cilium/cilium/issues/18239#issuecomment-992927403 https://github.com/cilium/cilium/issues/14028 https://github.com/cilium/cilium/issues/11560#issuecomment-902693365
```
Instance not found! Please delete corresponding ciliumnode if instance has already been deleted
``` 
4.  `instance does not exist` in azure
5. Because it not update `instanceManger.instances` when new node find. So in `ops.ResyncInterfacesAndIPs` return error in aws and alibabacloud.
https://github.com/cilium/cilium/blob/94ea7fc93e0af5bf3ddab5b67508003ca47678cd/pkg/aws/eni/node.go#L509-L542
https://github.com/cilium/cilium/blob/94ea7fc93e0af5bf3ddab5b67508003ca47678cd/pkg/aws/eni/instances.go#L216-L230
https://github.com/cilium/cilium/blob/94ea7fc93e0af5bf3ddab5b67508003ca47678cd/pkg/ipam/types/types.go#L433-L449

### Cilium Version

master https://github.com/cilium/cilium/tree/94ea7fc93e0af5bf3ddab5b67508003ca47678cd

### Kernel Version

none

### Kubernetes Version

none

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

I think need add new method `UpdateInstance(ctx context.Context, obj *v2.CiliumNode) error` for `instanceManager` that call cloud api to get instance for this node and update `instanceManager.instances` .  do update instances logic in `n.ops.UpdatedNode(resource)`
https://github.com/cilium/cilium/blob/94ea7fc93e0af5bf3ddab5b67508003ca47678cd/pkg/ipam/node.go#L355-L377

``` go
// UpdatedNode is called when an update to the CiliumNode is received.
func (n *Node) UpdatedNode(obj *v2.CiliumNode) {
	n.mutex.Lock()
	n.k8sObj = obj
        n.mutex.Unlock()
        err := n.manager.UpdateInstance(context.Todo(), obj)
        ..........
}
```
other ideas is  add new method  `UpdateInstance(ctx context.Context, obj *v2.CiliumNode) error`   for  `AllocationImplementation` interface and do logic `node.UpdatedResource`
``` go
func (n *Node) UpdatedResource(resource *v2.CiliumNode) bool {
	// Deep copy the resource before storing it. This way we are not
	// dependent on caller not using the resource after this call.
	resource = resource.DeepCopy()

	n.ops.UpdatedNode(resource)
        err := n.manager.instancesAPI.UpdateInstance(context.Todo(), obj)
        if err != nil {
           return false
         }

	n.mutex.Lock()
	// Any modification to the custom resource is seen as a sign that the
	// instance is alive
	n.instanceRunning = true
	n.resource = resource
	n.mutex.Unlock()

	n.recalculate()
	allocationNeeded := n.allocationNeeded()
	if allocationNeeded {
		n.requirePoolMaintenance()
		n.poolMaintainer.Trigger()
	}

	return allocationNeeded
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by wu0407**
1. Sync the instances network interface information from instances api when a new node is created but not in `instanceManager.instances`. This is fix errors
 in `ResyncInterfacesAndIPs` "Instance not found! Please delete corresponding
ciliumnode if instance has already been deleted" when new node created in cloud provider then add to cluster and before resync triggered.

2. Delete instance from `instanceManager.instances` on node deleted. This will cause `NodeManager.Update()` to invoke `instancesAPIResync` if this instance rejoins the cluster. This ensures that `Node.recalculate()` does not use stale data for instances which rejoin the cluster after their EC2 configuration has changed.

3. Fixes daedlock that report in #21477

Fixes: #20678

Signed-off-by: xiaoqing <xiaoqingnb@gmail.com>

### CODE REVIEW

**Comment by gandro** [comment]
@wu0407 Thanks! I do have two questions that I think need to be discussed and maybe resolved:

- If the instances API is not yet stable, I don't think we should issue the resyncs.
- I'm a bit worried that if the EC2 API is unstable (which is something we've observed recently), that issuing a resync for each updated node will make the situation worse, i.e. adding even more load to the already overloaded API. I think we should mark the API as unstable if `Resync` returns an error and not try to resync while the API is unstable.

I think both cases can be handled by reading/writing to `n.stableInstancesAPI`.  This should be safe, since we already hold the NodeManager lock.

**Review by gandro — CHANGES_REQUESTED** [review]
(see comment above)

**Comment by wu0407** [comment]
> (see comment above)

done

File: pkg/ipam/node_manager.go [hunk 1]
```diff
@@ -288,6 +294,16 @@ func (n *NodeManager) Update(resource *v2.CiliumNode) (nodeSynced bool) {
...
+				node.logger().Warning("Failed to resync the instances from the API after new node was found")
+				n.stableInstancesAPI = false
+			} else {
+				n.stableInstancesAPI = true
+			}
+		}
+
 		node.ops = n.instancesAPI.CreateNode(resource, node)
 
 		ctx, cancel := context.WithCancel(context.Background())
```
Comment (gandro) [inline pkg/ipam/node_manager.go]: One last request: Do you mind moving this up and pass `ctx` it into `n.instancesAPI.Resync`? It doesn't affect correctness (since the context won't be cancelled till later), but if we ever change the behavior of `Resync` to spawn any go routines, it will ensure that those are cancelled when the node is removed.

Comment (wu0407) [reply pkg/ipam/node_manager.go]: > One last request: Do you mind moving this up and pass `ctx` it into `n.instancesAPI.Resync`? It doesn't affect correctness (since the context won't be cancelled till later), but if we ever change the behavior of `Resync` to spawn any go routines, it will ensure that those are cancelled when the node is removed.

ok

**Review by gandro — APPROVED** [review]

File: operator/cmd/cilium_node.go [hunk 2]
```diff
@@ -269,8 +274,18 @@ func syncHandlerConstructor(notFoundHandler func(name string), foundHandler func
...
-			log.Errorf("Object stored in store is not *cilium_v2.CiliumNode but %T", obj)
-			return err
+			tombstone, ok := obj.(cache.DeletedFinalStateUnknown)
+			if !ok {
+				return fmt.Errorf("couldn't get object from tombstone %#v", obj)
+			}
+			cn, ok = tombstone.Obj.(*cilium_v2.CiliumNode)
+			if !ok {
+				return fmt.Errorf("tombstone contained object that is not a *cilium_v2.CiliumNode %#v", obj)
+			}
```
Comment (christarazi) [inline operator/cmd/cilium_node.go]: I don't think we should be splatting the obj into the error msg. We only care about the type, right?

```suggestion
				return fmt.Errorf("couldn't get object from tombstone %T", obj)
			}
			cn, ok = tombstone.Obj.(*cilium_v2.CiliumNode)
			if !ok {
				return fmt.Errorf("tombstone contained object that is not a *cilium_v2.CiliumNode %T", obj)
			}
```

**Review by christarazi — CHANGES_REQUESTED** [review]
LGTM besides one comment.

File: pkg/azure/ipam/instances.go [hunk 3]
```diff
@@ -46,6 +46,14 @@ func (m *InstancesManager) CreateNode(obj *v2.CiliumNode, n *ipam.Node) ipam.Nod
 	return &Node{manager: m, node: n}
 }
 
+// HasInstance returns whether the instance is in instances
+func (m *InstancesManager) HasInstance(instanceID string) bool {
+	m.mutex.RLock()
+	instanceExist := m.instances.Exists(instanceID)
```
Comment (tommyp1ckles) [inline pkg/azure/ipam/instances.go]: nit: might be a bit cleaner to just return the result of .Exists() and defer the RUnlock()

**Review by tommyp1ckles — APPROVED** [review]
Azure changes LGTM

**Comment by wu0407** [comment]
> LGTM besides one comment.

done

**Review by christarazi — APPROVED** [review]

**Comment by gandro** [comment]
@wu0407 Could you rebase your branch on master? The various test failures do seem unrelated (crashes in the init containers, which should be unrelated to this PR), but I'd like to test again on a more recent branch.

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-kernel-4.9/3003/
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.23-kernel-5.4/539/
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.24-kernel-4.19/718/
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.25-kernel-net-next/588/

**Comment by wu0407** [comment]
> @wu0407 Could you rebase your branch on master? The various test failures do seem unrelated (crashes in the init containers, which should be unrelated to this PR), but I'd like to test again on a more recent branch.
> 
> https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-kernel-4.9/3003/ https://jenkins.cilium.io/job/Cilium-PR-K8s-1.23-kernel-5.4/539/ https://jenkins.cilium.io/job/Cilium-PR-K8s-1.24-kernel-4.19/718/ https://jenkins.cilium.io/job/Cilium-PR-K8s-1.25-kernel-net-next/588/

ok

**Comment by gandro** [comment]
This unfortunately needs another rebase due to a merge conflict.

**Comment by gandro** [comment]
- https://jenkins.cilium.io/job/Cilium-PR-K8s-1.23-kernel-5.4/604/ hit unrelated flake #21735 
- https://jenkins.cilium.io/job/Cilium-PR-K8s-1.25-kernel-net-next/652/ hit new (but seems unrelated, there is no IPAM code involved) flake #22056
- https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/3889/ failed with `bpf_test.go:56: -bpf-test-path is a required flag`which is unrelated too

**Comment by gandro** [comment]
/test-1.23-5.4

**Comment by gandro** [comment]
/test-1.25-net-next

**Comment by gandro** [comment]
- https://jenkins.cilium.io/job/Cilium-PR-K8s-1.23-kernel-5.4/611/ keeps hitting known flake https://github.com/cilium/cilium/issues/21735
 - Runtime, as mentioned above, was broken as well, so not rerunning.

Marking ready to merge.
