### PR TITLE
fix: add annotate-k8s-node flag to daemon

### LINKED ISSUE #7976: Add --annotate-k8s-node flag to allow disabling node annotation
Add a flag to make the following code conditional. The default should remain enabled.

``` go 
        // Annotation of the k8s node must happen after discovery of the
        // PodCIDR range and allocation of the health IPs.
        if k8s.IsEnabled() {
                bootstrapStats.k8sInit.Start()
                log.WithFields(logrus.Fields{
                        logfields.V4Prefix:       node.GetIPv4AllocRange(),
                        logfields.V6Prefix:       node.GetIPv6NodeRange(),
                        logfields.V4HealthIP:     d.nodeDiscovery.LocalNode.IPv4HealthIP,
                        logfields.V6HealthIP:     d.nodeDiscovery.LocalNode.IPv6HealthIP,
                        logfields.V4CiliumHostIP: node.GetInternalIPv4(),
                        logfields.V6CiliumHostIP: node.GetIPv6Router(),
                }).Info("Annotating k8s node")

                err := k8s.Client().AnnotateNode(node.GetName(),
                        node.GetIPv4AllocRange(), node.GetIPv6NodeRange(),
                        d.nodeDiscovery.LocalNode.IPv4HealthIP, d.nodeDiscovery.LocalNode.IPv6HealthIP,
                        node.GetInternalIPv4(), node.GetIPv6Router())
                if err != nil {
                        log.WithError(err).Warning("Cannot annotate k8s node with CIDR range")
                }
                bootstrapStats.k8sInit.End(true)
        }
```

### PR DESCRIPTION
**Pull request by fristonio**
* Add a new flag for daemon to optionally annotate kubernetes node
* By default daemon will annotate the kubernetes node
* This can be optinally disabled by --annotate-k8s-node flag
* Fixes #7976

Fixes: #7976

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8109)

### CODE REVIEW

**Comment by fristonio** [comment]
test-me-please

File: daemon/daemon_main.go [hunk 1]
```diff
@@ -366,6 +366,9 @@ func init() {
 	flags.Bool(option.BlacklistConflictingRoutes, defaults.BlacklistConflictingRoutes, "Don't blacklist IP allocations conflicting with local non-cilium routes")
 	option.BindEnv(option.BlacklistConflictingRoutes)
 
+	flags.Bool(option.AnnotateK8sNode, defaults.AnnotateK8sNode, "Annotate Kubernetes nodes")
```
Comment (aanm) [inline daemon/daemon_main.go]: Small nit, can you put this in line 359 just to be in alphabetical order?

**Review by aanm — CHANGES_REQUESTED** [review]
Looks good, only a small nit and if you can drop the merge commit and rebase with origin/master that would be good.

File: daemon/daemon_main.go (hunk 1 above)
Comment (fristonio) [reply daemon/daemon_main.go]: Done.

**Review by nebril — APPROVED** [review]

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-docs-please

**Comment by tgraf** [comment]
@fristonio Needs a bit of fixing up in order to pass `gofmt`

```
00:01:06.960  contrib/scripts/check-fmt.sh
00:01:07.448  Unformatted Go source code:
00:01:07.448  ./pkg/defaults/defaults.go
00:01:07.448  diff -u ./pkg/defaults/defaults.go.orig ./pkg/defaults/defaults.go
00:01:07.448  --- ./pkg/defaults/defaults.go.orig	2019-05-24 09:54:58.167132489 +0000
00:01:07.448  +++ ./pkg/defaults/defaults.go	2019-05-24 09:54:58.167132489 +0000
00:01:07.448  @@ -217,7 +217,7 @@
00:01:07.448   	// provide backwards compatibility, it can be disabled via an option
00:01:07.448   	ForceLocalPolicyEvalAtSource = true
00:01:07.448   
00:01:07.448  -	// AnnotateK8sNode is the default value for option.AnnotateK8sNode. It is 
00:01:07.448  +	// AnnotateK8sNode is the default value for option.AnnotateK8sNode. It is
00:01:07.448   	// enabled by default to annotate kubernetes node and can be disabled using
00:01:07.448   	// the provided option.
00:01:07.448   	AnnotateK8sNode = true
0
```

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
@fristonio Almost there. The automatically generated help text needs to be updated and a rebase against master is needed.

```
00:09:09.965      runtime: make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/Documentation'
00:09:09.965      runtime: diff -x '*.rst' -r ./Documentation/cmdref/cilium-agent.md /tmp/tmp.oXRgTFj80z/cilium-agent.md
00:09:09.965      runtime: 21c21
00:09:09.965      runtime: <       --annotate-k8s-node                          Annotate Kubernetes nodes (default true)
00:09:09.965      runtime: ---
00:09:09.965      runtime: >       --annotate-k8s-node                          Annotate Kubernetes node (default true)
00:09:09.965      runtime: Detected a difference in the cmdref directory
00:09:09.965      runtime: diff -r: diff -r ./Documentation/cmdref/cilium-agent.md /tmp/tmp.oXRgTFj80z/cilium-agent.md
00:09:09.965      runtime: 21c21
00:09:09.965      runtime: <       --annotate-k8s-node                          Annotate Kubernetes nodes (default true)
00:09:09.965      runtime: ---
00:09:09.965      runtime: >       --annotate-k8s-node                          Annotate Kubernetes node (default true)
00:09:09.965      runtime: Only in ./Documentation/cmdref: cli_index.rst
00:09:09.965      runtime: Only in ./Documentation/cmdref: index.rst
00:09:09.965      runtime: Only in ./Documentation/cmdref: kvstore.rst
00:09:09.965      runtime: Please rerun 'make -C Documentation cmdref' and commit your changes
```

**Review by aanm — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]
