### PR TITLE
CFP: read-only filesystem support

### LINKED ISSUE #30059: CFP: Check if sysctl values need to be updated before write instead of blatant sysctl write to potentially read-only filesystem
## Cilium Feature Proposal
        
Thanks for taking time to make a feature proposal for Cilium! If you have usage questions, please try the [slack channel](http://slack.cilium.io/) and see the [FAQ](https://github.com/cilium/cilium/issues?utf8=%E2%9C%93&q=is:issue+label:kind/question+) first.

**Is your proposed feature related to a problem?**

Ability to have hardened read-only proc filesystem is not allowed due to [enableIPForwarding](https://github.com/cilium/cilium/blob/2daca4c3935a43dac72044c7ca3e17ac57af2617/pkg/datapath/iptables/sysctl_linux.go#L10) always assuming that filesystem is readable / modifiable. When using read-only proc filesystem with load-balancing enabled ensures cilium-agent node crash, even if values have been set previously.

**Describe the feature you'd like**

Add work-around for read-only procfs or when sysctl writes are not allowed.

**(Optional) Describe your proposed solution**

Modify usage of [writeSysctl](https://github.com/cilium/cilium/blob/2daca4c3935a43dac72044c7ca3e17ac57af2617/pkg/sysctl/sysctl.go#L91) to read parameter path file if exists and checks if read value is set to `value` passed in writeSysctl fn.

Once the CFP is close to being finalized, please add it as a PR to the [design-cfps](https://github.com/cilium/design-cfps) repo for final approval.

### PR DESCRIPTION
**Pull request by chaunceyjiang**
Check sysctl values before writes to avoid errors on potentially read-only filesystem

Fixes: #30059

```release-note
Check sysctl values before writes to avoid errors on potentially read-only filesystem
```

### CODE REVIEW

File: pkg/sysctl/sysctl.go [hunk 1]
```diff
@@ -93,6 +93,15 @@ func writeSysctl(name string, value string) error {
 	if err != nil {
 		return err
 	}
+	// Check if the value is already set to the desired value.
+	val, err := os.ReadFile(path)
+	if err != nil {
+		return fmt.Errorf("failed to read %s: %s", path, err)
```
Comment (aspsk) [inline pkg/sysctl/sysctl.go]: Could you please change the error message to the same form as other error messages in this function, smth like
```
fmt.Errorf("could not read the sysctl file %s: %s", path, err)
```

Comment (chaunceyjiang) [reply pkg/sysctl/sysctl.go]: Done.

**Review by aspsk — APPROVED** [review]
Thanks, lgtm
