### PR TITLE
bpf: Fix Geneve-DSR inconsistency with host-routing off

### LINKED ISSUE #32189: Geneve DSR is broken when running w/o BPF masquerade
Encountered on the latest `main` (stable branches might be affected too):

```
12:39:59.287274 IP 172.18.0.2.30851 > 172.18.0.1.44148: Flags [S.], seq 736152428, ack 72597045, win 32950, options [mss 1330,sackOK,TS val 1289060956 ecr 1762384254,nop,wscale 7], length 0
12:39:59.287471 IP 172.18.0.3.80 > 172.18.0.1.44148: Flags [.], ack 72597124, win 257, options [nop,nop,TS val 1289060956 ecr 1762384254], length 0
12:39:59.287486 IP 172.18.0.1.44148 > 172.18.0.3.80: Flags [R], seq 72597124, win 0, length 0
12:39:59.494078 IP 172.18.0.2.30851 > 172.18.0.1.44148: Flags [R], seq 736152429, win 0, length 01
```

The second reply gets wrong src port (should be 30851 instead of 80). Enabling BPF masq fixes the issue.

### PR DESCRIPTION
**Pull request by yushoyamaguchi**
This commit fixes an inconsistency in how Geneve-DSR packets are processed when host-routing is disabled.
In the current behavior, only DSR reply packets are seen by the host-stack, while incoming packets are redirected by BPF and skip the host-stack.
This causes conntrack entries to be incomplete.

As a result, when BPF-masquerade is disabled, reply packets are unintentionally masqueraded by iptables, which break DSR functionality.
See: https://github.com/cilium/cilium/issues/32189.
Note: When BPF-masquerade is disabled, host-routing is also automatically disabled.
https://github.com/cilium/cilium/blob/55aecc0f4706b5f8a70fc38ed2817cc2e15b0f60/Documentation/operations/performance/tuning.rst?plain=1#L168

To resolve this, cil_from_overlay() now delivers incoming Geneve-DSR packets to the host-stack, if host-routing is disabled.
This ensures conntrack entries are created properly and prevents incorrect masquerading.

### CODE REVIEW

File: bpf/bpf_overlay.c [hunk 1]
```diff
@@ -458,6 +480,26 @@ static __always_inline int handle_ipv4(struct __ctx_buff *ctx,
...
+		 * However, there is no problem because purpose of this procedure
+		 * is to insert conntrack entry of this flow.
+		 */
+		if (ret > 0 && gopt.hdr.type == DSR_GENEVE_OPT_TYPE)
+			is_geneve_dsr_packet = 1;
+	}
+	if (is_geneve_dsr_packet)
+		return ipv4_handle_geneve_dsr(ctx, ip4);
+#endif
+
```
Comment (ysksuzuki) [inline bpf/bpf_overlay.c]: I think we should integrate it into `ipv4_local_delivery()` by adding a parameter `deliver_via_stack` for example.

File: bpf/bpf_overlay.c [hunk 2]
```diff
@@ -458,6 +480,26 @@ static __always_inline int handle_ipv4(struct __ctx_buff *ctx,
...
+	 */
+	if (!is_defined(ENABLE_MASQUERADE_IPV4)) {
+		ret = ctx_get_tunnel_opt(ctx, &gopt, sizeof(gopt));
+		/* Mark only Geneve DSR packets.
+		 * In TCP, only SYN packets have DSR_GENEVE_OPT_TYPE.
+		 * However, there is no problem because purpose of this procedure
+		 * is to insert conntrack entry of this flow.
+		 */
+		if (ret > 0 && gopt.hdr.type == DSR_GENEVE_OPT_TYPE)
+			is_geneve_dsr_packet = 1;
```
Comment (ysksuzuki) [inline bpf/bpf_overlay.c]: It's weird. The kernel only sees the SYN packet and other packets are delivered via BPF?

I'm not sure whether we need to catch the DSR GENEVE packet here. In native routing mode, only DSR packets should go through this path.

File: bpf/bpf_overlay.c [hunk 3]
```diff
@@ -207,6 +207,24 @@ static __always_inline int ipv4_host_delivery(struct __ctx_buff *ctx, struct iph
...
+		ret = ipv4_l3(ctx, ETH_HLEN, (__u8 *)&router_mac.addr,
+			      (__u8 *)&geneve_mac.addr, ip4);
+		if (ret != CTX_ACT_OK)
+			return ret;
+		ctx_change_type(ctx, PACKET_HOST);
+		return CTX_ACT_OK;
+	}
+}
+#endif /* ENABLE_DSR && IS_BPF_OVERLAY && DSR_ENCAP_MODE == DSR_ENCAP_GENEVE */
+
```
Comment (ysksuzuki) [inline bpf/bpf_overlay.c]: We can let `ipv4_local_delivery()` handle this.

**Review by ysksuzuki — CHANGES_REQUESTED** [review]
Thank you for the PR.

The issue occurs because bpf_overlay delivers packets to the local endpoint without passing through the kernel stack, even in legacy routing mode. This results in asymmetric communication. I believe we can address this by passing DSR GENEVE packets to the kernel from bpf_overlay. However, I'm not certain if this approach covers all scenarios, so further discussion is needed. Additionally, we need to add tests for this.

File: bpf/bpf_overlay.c (hunk 2 above)
Comment (yushoyamaguchi) [reply bpf/bpf_overlay.c]: I'm sorry, this procedure is for tunneling-mode with Geneve.
In tunnel mode, if cil_from_overlay() pass all packets to the kernel, it will increase overhead and unnecessarily expand conntrack entries.
With this implementation, both inter-node communication and communication with external clusters seem to be working well.

Could we use Geneve-DSR with native-routing-mode? I didn't know that.
Just in case, I’ll confirm the behavior when using native-routing-mode.

Comment (ysksuzuki) [reply bpf/bpf_overlay.c]: I understand that we should avoid passing in-cluster traffic into the kernel in tunneling mode here, but I'm not sure if we should treat only SYN packets specially in DSR GENEVE traffic. If we do so, that means packets other than SYN in DSR GENEVE traffic would remain asymmetric, right?

Comment (yushoyamaguchi) [reply bpf/bpf_overlay.c]: I've understood your concern.
As you said,  packets other than SYN in DSR GENEVE traffic would remain asymmetric, in current code.

If it is not appropriate, I will introduce a new type of metadata applied to both SYN and non-SYN packets  in these part.(instead of `DSR_GENEVE_OPT_TYPE`)

https://github.com/cilium/cilium/blob/7b7edc148225e6cb20644705cf0e33cd192144f6/bpf/lib/nodeport.h#L1634-L1646
https://github.com/cilium/cilium/blob/7b7edc148225e6cb20644705cf0e33cd192144f6/bpf/lib/encap.h#L220-L229


Should I do so?
More discussion is required?

Comment (ysksuzuki) [reply bpf/bpf_overlay.c]: The disadvantage of that approach is that it adds MTU overhead, right? I’d like to dig into the root cause of this issue, identify possible solutions, evaluate the pros and cons of each, and then make a decision. I don't think we have enough information to make a decision yet.

File: bpf/bpf_overlay.c (hunk 1 above)
Comment (yushoyamaguchi) [reply bpf/bpf_overlay.c]: fixed.

File: bpf/bpf_overlay.c (hunk 2 above)
Comment (ysksuzuki) [reply bpf/bpf_overlay.c]: I also think we need to dive deeper into the impact of the change that passes packets from bpf_overlay to the kernel. We need to consider whether it could break existing assumptions, such as the host routing path and the application of NetworkPolicy.

**Comment by ysksuzuki** [comment]
Let me convert this PR to draft since the more discussion is needed

File: bpf/bpf_overlay.c [hunk 4]
```diff
@@ -204,6 +206,17 @@ static __always_inline int ipv4_host_delivery(struct __ctx_buff *ctx, struct iph
...
+		union macaddr geneve_mac = CILIUM_OVERLAY_MAC;
+		union macaddr router_mac = THIS_INTERFACE_MAC;
+		int ret;
+
+		ret = ipv4_l3(ctx, ETH_HLEN, (__u8 *)&router_mac.addr,
+			      (__u8 *)&geneve_mac.addr, ip4);
+		if (ret != CTX_ACT_OK)
+			return ret;
+		ctx_change_type(ctx, PACKET_HOST);
+		return CTX_ACT_OK;
```
Comment (ysksuzuki) [inline bpf/bpf_overlay.c]: Why do we need this MAC address handling? I think currently, we just call `ctx_change_type(ctx, PACKET_HOST)` and `return CTX_ACT_OK` after the `ipv4_l3` call when passing packets into the kernel.
https://github.com/cilium/cilium/blob/c662625ffa1c92a22ebf08c925897eadd8a8222b/bpf/lib/l3.h#L107-L110

Comment (yushoyamaguchi) [reply bpf/bpf_overlay.c]: Thank you for pointing out.
This should be deleted.
I added this part when I didn't understand the cause of `SKB_DROP_REASON_OTHERHOST` correctly.

I've fixed.

File: bpf/bpf_overlay.c [hunk 5]
```diff
@@ -458,23 +468,43 @@ static __always_inline int handle_ipv4(struct __ctx_buff *ctx,
...
+	if (!is_defined(ENABLE_MASQUERADE_IPV4)) {
+		ret = ctx_get_tunnel_opt(ctx, &gopt, sizeof(gopt));
+		/* Mark only Geneve DSR packets.
+		 * In TCP, only SYN packets have DSR_GENEVE_OPT_TYPE.
+		 * However, there is no problem because purpose of this procedure
+		 * is to insert conntrack entry of this flow.
+		 */
+		if (ret > 0 && gopt.hdr.type == DSR_GENEVE_OPT_TYPE)
+			is_delivered_via_stack = 1;
+	}
```
Comment (julianwiedmann) [inline bpf/bpf_overlay.c]: Can we use the `is_dsr` indication we get from `nodeport_lb4()` instead?

File: bpf/bpf_overlay.c [hunk 6]
```diff
@@ -458,23 +468,43 @@ static __always_inline int handle_ipv4(struct __ctx_buff *ctx,
...
-	if (ep && !(ep->flags & ENDPOINT_MASK_HOST_DELIVERY))
-		return ipv4_local_delivery(ctx, ETH_HLEN, *identity, MARK_MAGIC_IDENTITY,
-					   ip4, ep, METRIC_INGRESS, false, true, 0);
+#if defined(ENABLE_DSR) && defined(IS_BPF_OVERLAY) && (DSR_ENCAP_MODE == DSR_ENCAP_GENEVE)
+	/* Pass packets which will be returned using Geneve DSR
+	 * to host-stack for conntrack entry insertion.
+	 * This is needed because the packet will be masqueraded
+	 * by iptables if the conntrack entry isn't exist.
+	 */
+	if (!is_defined(ENABLE_MASQUERADE_IPV4)) {
```
Comment (julianwiedmann) [inline bpf/bpf_overlay.c]: To clarify - what we want is netfilter symmetry between the forward and reply path, correct? In the reply path, netfilter will observe the traffic unless `ENABLE_HOST_ROUTING` is set. I would have expected us to match this behavior in the forward path (rather than checking for `ENABLE_MASQUERADE_IPV4`), same as we do [here](https://github.com/cilium/cilium/blob/eaecc8e9bf04389f8f328750762d7c6fe2b3b721/bpf/bpf_host.c#L742) for DSR traffic with IP-option.

**Review by julianwiedmann — COMMENTED** [review]
Thank you! I added some comments below.

Have you thought about how we can test this behavior? Maybe a BPF test with the problematic configuration?

File: bpf/bpf_overlay.c (hunk 5 above)
Comment (yushoyamaguchi) [reply bpf/bpf_overlay.c]: I'm sorry, I couldn't understand how to use `is_dsr` indication.

**Comment by yushoyamaguchi** [comment]
@julianwiedmann 

Thank you for reviewing.

I didn't think about test but I think BPF test will be fit.

In addition, as @ysksuzuki said,
https://github.com/cilium/cilium/pull/37937#discussion_r1976551611
should we test if this commit break current assumptions ?

To confirm this, a BPF test would not be sufficient, right?

**Comment by ysksuzuki** [comment]
To clarify, we currently pass packets into the stack from bpf_overlay if `defined(USE_BPF_PROG_FOR_INGRESS_POLICY)` which means that endpoint route is enables and `cil_to_container` is attached to apply the ingress policy. I wanted to make sure that it's safe to do so regardless of the the endpoint route. I guess that in that case, packets are routed to cilium-host and tail calls handle_policy to apply the ingress policy. But I haven't check it yet.
https://github.com/cilium/cilium/blob/main/bpf/lib/l3.h#L107-L110

File: bpf/bpf_overlay.c (hunk 5 above)
Comment (ysksuzuki) [reply bpf/bpf_overlay.c]: We are checking  whether the packet is part of the DSR flow  in `nodeport_extract_dsr_v4`. This is to update the world identity to the appropriate CIDR identity.
https://github.com/cilium/cilium/blob/main/bpf/bpf_overlay.c#L319-L320
https://github.com/cilium/cilium/blob/bf862fe70ec213233dc4d36ab7ea598e5877221b/bpf/lib/nodeport.h#L1742-L1744

I think we can use it

Comment (yushoyamaguchi) [reply bpf/bpf_overlay.c]: I may understand what you said.

You mean that 
- TCP packets other than SYN can be identified whether they are DSR-processed, based on whether the CT entry has a DSR mark.
- `cil_from_overlay()` should decide if it pass packets to host-stack with this judgment criteria, for TCP packets other than SYN.

Is it right ?

https://github.com/cilium/cilium/blob/bf862fe70ec213233dc4d36ab7ea598e5877221b/bpf/lib/nodeport.h#L1759

Comment (julianwiedmann) [reply bpf/bpf_overlay.c]: Yes. Instead of manually looking at `ctx_get_tunnel_opt()` to identify DSR traffic, just use the `is_dsr` that's returned by the nodeport code. This will cover *all* traffic for a DSR connection, even if the specific packet doesn't carry a DSR option (the non-SYN TCP case).

Comment (yushoyamaguchi) [reply bpf/bpf_overlay.c]: Thank you for explaining it to me so carefully.
I've fixed.

**Comment by yushoyamaguchi** [comment]
@ysksuzuki 

Are you concerned that, while the code I added pass packets to the host-stack even when Endpoint-Routes are disable, this might prevent the application of ingress-policy by the tail-called BPF program from `cil_overlay()`? (I'm sorry if I've misread.)

As you said, this might be a defect of my commit...
https://github.com/cilium/cilium/commit/3d2ceaf3b24d8f9dcbb96ee00b077c0226069ba4
According to this commit message, when Endpoint-Routes are disable, policy will be applied at the tail-called BPF program from `cil_overlay()` .

Is there any other ways to apply policies?

File: bpf/bpf_overlay.c [hunk 7]
```diff
@@ -458,23 +465,36 @@ static __always_inline int handle_ipv4(struct __ctx_buff *ctx,
 	}
 #endif /* ENABLE_EGRESS_GATEWAY_COMMON */
 
-	/* Deliver to local (non-host) endpoint: */
-	ep = lookup_ip4_endpoint(ip4);
-	if (ep && !(ep->flags & ENDPOINT_MASK_HOST_DELIVERY))
-		return ipv4_local_delivery(ctx, ETH_HLEN, *identity, MARK_MAGIC_IDENTITY,
-					   ip4, ep, METRIC_INGRESS, false, true, 0);
+#if defined(ENABLE_DSR) && defined(IS_BPF_OVERLAY) && (DSR_ENCAP_MODE == DSR_ENCAP_GENEVE)
```
Comment (julianwiedmann) [inline bpf/bpf_overlay.c]:
```suggestion
#if defined(ENABLE_DSR) && (DSR_ENCAP_MODE == DSR_ENCAP_GENEVE)
```

We're in `bpf_overlay`, no need to check further :).

I suspect you could even completely remove these guards, and rely on `is_dsr` being optimized out when DSR is not enabled. But that's just a hunch.

File: bpf/bpf_overlay.c [hunk 8]
```diff
@@ -289,6 +295,7 @@ static __always_inline int handle_ipv4(struct __ctx_buff *ctx,
 	bool decrypted;
 	bool __maybe_unused is_dsr = false;
 	int ret;
+	int is_delivered_via_stack = 0;
```
Comment (julianwiedmann) [inline bpf/bpf_overlay.c]:
```suggestion
	bool is_delivered_via_stack = false;
```

Let's be explicit about this being a boolean value (also in other parts of the patch).

File: bpf/bpf_overlay.c [hunk 9]
```diff
@@ -458,23 +465,36 @@ static __always_inline int handle_ipv4(struct __ctx_buff *ctx,
...
+		ret = overlay_ingress_policy_hook(ctx, ip4, *identity, ext_err);
+		if (ret != CTX_ACT_OK)
+			return ret;
+
+		/* A packet entering the node from the tunnel and not going to a local
+		 * endpoint has to be going to the local host.
+		 */
 
-	set_identity_mark(ctx, *identity, MARK_MAGIC_IDENTITY);
+		set_identity_mark(ctx, *identity, MARK_MAGIC_IDENTITY);
```
Comment (julianwiedmann) [inline bpf/bpf_overlay.c]: Let's also set this mark in the `is_delivered_via_stack` case, so that the source identity doesn't need to be resolved again?

File: bpf/bpf_overlay.c [hunk 10]
```diff
@@ -190,9 +190,11 @@ int tail_handle_ipv6(struct __ctx_buff *ctx)
 #endif /* ENABLE_IPV6 */
 
 #ifdef ENABLE_IPV4
-static __always_inline int ipv4_host_delivery(struct __ctx_buff *ctx, struct iphdr *ip4)
+static __always_inline int ipv4_host_delivery(struct __ctx_buff *ctx,
+							struct iphdr *ip4,
+							int deliver_via_stack)
 {
-	if (1) {
+	if (!deliver_via_stack) {
```
Comment (julianwiedmann) [inline bpf/bpf_overlay.c]:
```suggestion
	if (deliver_via_stack) {
	        /* Deliver to the host-stack */
		ctx_change_type(ctx, PACKET_HOST);
		return CTX_ACT_OK;
	}
	
	if (1) {
	      ....
	}
```

Maybe it's just personal preference, but this reads easier to me.

**Review by julianwiedmann — COMMENTED** [review]
Just a few remarks inline, this looks pretty close already!

So what we'd still need is
1. the corresponding IPv6 path
2. some BPF-level testing that demonstrates the scenario we're concerned about
3. a final conclusion on the "how is this traffic then delivered to the endpoint", considering the various config options (ep-routing yes/no, ...?). Mostly so that we can write this up in the patch description.

File: bpf/bpf_overlay.c (hunk 9 above)
Comment (yushoyamaguchi) [reply bpf/bpf_overlay.c]: I modified it so that this mark is also applied when `is_delivered_via_stack`.
However, honestly, I don't understand what the procedure is, I'm sorry.
Is my new code okay?

**Comment by yushoyamaguchi** [comment]
@julianwiedmann @ysksuzuki 

In my local environment, 
- Geneve-DSR with Native-Routing-Mode in IPv6 stand alone cluster cannot be generated with this error. (https://github.com/cilium/cilium/blob/f906a301515472b0dfeb8560721dafd03d786557/daemon/cmd/kube_proxy_replacement.go#L166)
- Geneve-DSR with Geneve-Tunnel-Mode in IPv6 stand alone cluster cannot be generated with this error. (https://github.com/cilium/cilium/blob/f906a301515472b0dfeb8560721dafd03d786557/pkg/node/address.go#L300)

Can we use Geneve-DSR in IPv6 stand alone cluster?

**Comment by yushoyamaguchi** [comment]
@julianwiedmann @ysksuzuki 
I've added BPF-unit-test for checking the datapath modification of this commit.
Please check if it is okay.

**Comment by yushoyamaguchi** [comment]
@julianwiedmann @ysksuzuki 

In my environment, Geneve DSR don't work in IPv6 cluster.
I made an issue. https://github.com/cilium/cilium/issues/38640

**Comment by julianwiedmann** [comment]
> @julianwiedmann @ysksuzuki I've added a BPF-unit-test for checking the datapath modification of this commit. Please check if it is okay.

sorry, too much other stuff & travel going on. I've added the PR back to my queue.

File: bpf/tests/tc_geneve_dsr_no_bpf_masq.c [hunk 11]
```diff
@@ -0,0 +1,126 @@
...
+
+#include "common.h"
+
+#include <bpf/ctx/skb.h>
+#include "pktgen.h"
+
+/* Enable code paths under test */
+#define ENABLE_IPV4
+
+#define ENABLE_HOST_ROUTING 0
```
Comment (julianwiedmann) [inline bpf/tests/tc_geneve_dsr_no_bpf_masq.c]: This is a bit dangerous - there are spots that will merely check `#ifdef ENABLE_HOST_ROUTING` (and then include the relevant code), while others will check `is_defined()` and behave as you'd expect.

So the safest is actually to omit this line, and consistently use `#define ENABLE_* 1` for everything else.

File: bpf/bpf_overlay.c (hunk 9 above)
Comment (julianwiedmann) [reply bpf/bpf_overlay.c]: yep looks good now! We first set the `skb->mark` to carry the source identity, and then forward the packet into the stack. The expectation is that the packet will later arrive at `to-container` with `skb->mark` still set.

File: bpf/tests/tc_geneve_dsr_no_bpf_masq.c [hunk 12]
```diff
@@ -0,0 +1,126 @@
...
+
+    data = (void *)(long)ctx_data(ctx);
+    data_end = (void *)(long)ctx->data_end;
+
+    if (data + sizeof(__u32) > data_end)
+        test_fatal("status code out of bounds");
+
+    status_code = data;
+	// The packet should be passed to kernel-stack
+    assert(*status_code == CTX_ACT_OK);
```
Comment (julianwiedmann) [inline bpf/tests/tc_geneve_dsr_no_bpf_masq.c]: I see that the test currently fails. Are you able to run the BPF tests locally (using `make run_bpf_tests`), and reproduce? My suspicion is that something with the mocks doesn't work, I vaguely remember having similar issues for these particular helpers.

**Review by julianwiedmann — COMMENTED** [review]
looks good to me! There's a few linter errors relating to coding style that need addressing, besides it's just a question of understanding why the BPF test doesn't work as expected :(

File: bpf/tests/tc_geneve_dsr_no_bpf_masq.c (hunk 12 above)
Comment (yushoyamaguchi) [reply bpf/tests/tc_geneve_dsr_no_bpf_masq.c]: In my local env, `make run_bpf_tests` is always finished well.
In GitHub CI, this test is sometimes failed.

File: bpf/tests/tc_geneve_dsr_no_bpf_masq.c (hunk 11 above)
Comment (yushoyamaguchi) [reply bpf/tests/tc_geneve_dsr_no_bpf_masq.c]: ~I've delete this line and the test is successful.~
~However, I couldn't understand how `ENABLE_HOST_ROUTING` is related to this data-path change, I'm sorry.~

~(Honestly, I didn't understand why this is reasonable. [https://github.com/cilium/cilium/pull/37937#discussion_r1978734808])~

~In above code of new logic, it seems that packets are passed to kernel-stack when only `ENABLE_HOST_ROUTING` is disabled.~

Why can we delete
`#define ENABLE_HOST_ROUTING 0`
from this BPF-test code?

Comment (yushoyamaguchi) [reply bpf/tests/tc_geneve_dsr_no_bpf_masq.c]: @julianwiedmann 

I'm sorry, I didn't know this requirement.
https://docs.cilium.io/en/latest/operations/performance/tuning/#ebpf-host-routing

When bpf-masquerade is disabled, `ENABLE_HOST_ROUTING` become 0!


However, still I couldn't understand Why we can delete
`#define ENABLE_HOST_ROUTING 0`
from this BPF-test code...

**Comment by yushoyamaguchi** [comment]
@julianwiedmann 

I've added corresponding IPv6 data-path and BPF tests for both v4 and v6 data-path.
About BPF-test, I implemented it heuristically, so please review it.
About network policy application by BPF, @ysksuzuki  said policies looks applied when using my patch, in last APAC-dev-MTG.

After reviewing BPF tests, could I make new PR of this commit?

P.S.
As @YutaroHayakawa  said in  last APAC-dev-MTG, I added the procedure to check if the correct ct_entry exists in each BPF test.
Is my implementation okay?

**Comment by yushoyamaguchi** [comment]
@ysksuzuki 

As you said in the APAC dev mtg, I've add the logic of checking nat_table entry which is created in `nodeport_dsr_ingress_ipv4()`.

I think remaining fix point for merging is only BPF-unit-test refactoring .
Please review.

cc @julianwiedmann

File: bpf/lib/local_delivery.h [hunk 13]
```diff
@@ -202,18 +208,25 @@ static __always_inline int ipv4_local_delivery(struct __ctx_buff *ctx, int l3_of
...
+
 	cilium_dbg(ctx, DBG_LOCAL_DELIVERY, ep->lxc_id, seclabel);
 
 	ret = ipv4_l3(ctx, l3_off, (__u8 *)&router_mac, (__u8 *)&lxc_mac, ip4);
 	if (ret != CTX_ACT_OK)
 		return ret;
 
 	return local_delivery(ctx, seclabel, magic, ep, direction, from_host,
-			      from_tunnel, cluster_id);
+				 from_tunnel, cluster_id);
```
Comment (julianwiedmann) [inline bpf/lib/local_delivery.h]: unnecessary change?

File: bpf/lib/local_delivery.h [hunk 14]
```diff
@@ -202,18 +208,25 @@ static __always_inline int ipv4_local_delivery(struct __ctx_buff *ctx, int l3_of
 					       struct iphdr *ip4,
 					       const struct endpoint_info *ep,
 					       __u8 direction, bool from_host,
-					       bool from_tunnel, __u32 cluster_id)
+					       bool from_tunnel, __u32 cluster_id,
+						   bool deliver_via_stack)
```
Comment (julianwiedmann) [inline bpf/lib/local_delivery.h]: Please align the indentation with the lines above.

File: bpf/lib/local_delivery.h [hunk 15]
```diff
@@ -175,12 +175,18 @@ static __always_inline int ipv6_local_delivery(struct __ctx_buff *ctx, int l3_of
...
 	mac_t router_mac = ep->node_mac;
 	mac_t lxc_mac = ep->mac;
 	int ret;
 
+	if (deliver_via_stack) {
+		/* Deliver to the host-stack */
+		ctx_change_type(ctx, PACKET_HOST);
+		return CTX_ACT_OK;
+	}
+
```
Comment (julianwiedmann) [inline bpf/lib/local_delivery.h]: As a follow-on PR, I think we can explore whether to push this part even further down into `local_delivery()`. But works just fine for now :).

**Review by julianwiedmann — COMMENTED** [review]
looks good to me! Some nitpicks below, but happy to approve once the PR is no longer in `draft` state :).

Please take a moment to refresh the PR & patch description, to reflect the current state.

File: bpf/lib/local_delivery.h (hunk 15 above)
Comment (yushoyamaguchi) [reply bpf/lib/local_delivery.h]: I see.
We need to consider whether packets should be passed to the host-stack after the following processing.

https://github.com/cilium/cilium/blob/fb82bb0afaea538b9b2b6f58d6c903692ec45463/bpf/lib/local_delivery.h#L211-L215
https://github.com/cilium/cilium/blob/fb82bb0afaea538b9b2b6f58d6c903692ec45463/bpf/lib/local_delivery.h#L184-L188

Should this be included in this PR, or would it be better to handle it in a separate one?

Comment (yushoyamaguchi) [reply bpf/lib/local_delivery.h]: It seems that the purpose of `ipv4_l3()` and `ipv6_l3()` is rewriting mac-addr correctly.
However, this packet will be processed by `cilium_geneve` device after passed to host-stack.
Geneve virtual device is L3-device so I think rewriting mac-addr may be not required.
How do you think ?

Comment (yushoyamaguchi) [reply bpf/lib/local_delivery.h]: However, by moving the `CTX_OK` return logic into `local_delivery()`,  we reduced repetition and made the code-base cleaner.

https://github.com/yushoyamaguchi/cilium/commit/f8bf5f02c151449532d5fea29ac446929a8e2669
Using the updated code with this change, I confirmed that the bpf-unit-test passes and that DSR works correctly in my local kind cluster.

Should I apply this change to the PR by `git rebase`?

@julianwiedmann

Comment (julianwiedmann) [reply bpf/lib/local_delivery.h]: My suggestion would be to fine-tune this piece in a separate PR.

File: bpf/bpf_overlay.c [hunk 16]
```diff
@@ -194,11 +195,21 @@ static __always_inline int handle_ipv6(struct __ctx_buff *ctx,
...
+#if defined(ENABLE_DSR) && (DSR_ENCAP_MODE == DSR_ENCAP_GENEVE)
+	/* Pass packets which will be returned using Geneve DSR
+	 * to host-stack for conntrack entry insertion.
+	 * This is needed because the packet will be masqueraded
+	 * by iptables if the conntrack entry isn't exist.
+	 */
+	if (!is_defined(ENABLE_HOST_ROUTING) && is_dsr)
+		is_delivered_via_stack = true;
+#endif
+
```
Comment (julianwiedmann) [inline bpf/bpf_overlay.c]: I had another look at how this scenario is [handled](https://github.com/cilium/cilium/blob/e87e9e21d3c243c823e8852cecc56f7efc92e8b6/bpf/bpf_host.c#L724) when DSR traffic arrives in `from-netdev` (with `dispatch-mode=opt`). And there we exit *before* looking up the local endpoint, or calling into `ipv*_local_delivery()`. Which means the equivalent change here would be as seen below.

I think that's preferable - it reduces the amount of code locations we need to touch (no additional parameter needed for `ipv*_local_delivery()`), and ensures we have symmetric behavior with the other DSR mode.


```suggestion
#if defined(ENABLE_DSR) && (DSR_ENCAP_MODE == DSR_ENCAP_GENEVE)
	/* Pass packets which will be returned using Geneve DSR
	 * to host-stack for conntrack entry insertion.
	 * This is needed because the packet will be masqueraded
	 * by iptables if the conntrack entry doesn't exist.
	 */
	if (!is_defined(ENABLE_HOST_ROUTING) && is_dsr)
		return CTX_ACT_OK;
#endif
```

Comment (yushoyamaguchi) [reply bpf/bpf_overlay.c]: I've fixed and confirmed that BPF unit tests and Geneve-DSR test workload in local-kind-cluster work well.

**Review by julianwiedmann — APPROVED** [review]

**Comment by julianwiedmann** [comment]
@ysksuzuki just needs your approval now :)

**Review by ysksuzuki — APPROVED** [review]
Thank you for your contribution!
