### PR TITLE
gateway-api: guard HTTP redirect with X-Forwarded-Proto

### LINKED ISSUE #34539: Gateway API - RequestRedirect loops indefinately scheme change from http to https
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

A copy of #28796 as this is still an persisting issue. I've also tried the slack channel, but I have gotten zero replies. I genuinely have no idea why this is happening, other than I don't specify a `tls` section.

Existing issues/references:
- https://github.com/kubernetes-sigs/gateway-api/issues/1185
- https://github.com/kubernetes-sigs/gateway-api/issues/2455
- https://github.com/kubernetes-sigs/gateway-api/issues/2809
- https://github.com/cilium/cilium/issues/25357
- https://github.com/cilium/cilium/issues/27493
- https://github.com/cilium/cilium/issues/28796
- https://www.reddit.com/r/kubernetes/comments/196w65h/gateway_api_and_redirect_loops/

1. Not using experimental Gateway CRDs, although I've tried with the both standard and experimental CRDs.
2. Gateway also does not have the `tls` section, because my cert is a public ACM one, so I can't add the `tls` section.
3. The Gateway HTTP section I copied from [this reddit post](https://www.reddit.com/r/kubernetes/comments/196w65h/gateway_api_and_redirect_loops/), in hopes that it actually did something.
4. Adding `hostnames` to any of the relevant sections doesn't make a difference.
5. I'm trying to use external-dns annotations to not use my internet-facing ELB, but ELB or service DNS endpoint doesn't make a difference.

Relevant yamls:

Gateway:

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: external
  namespace: kube-system
spec:
  gatewayClassName: cilium
  listeners:
    - name: shared-http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              https-upgrade: "true"
    - name: shared-https
      port: 443
      protocol: HTTPS
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: All
```

Service created from Gateway:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "<string list of my domains>"
    service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true
    service.beta.kubernetes.io/aws-load-balancer-name: iac-test-k8s-cilium-external
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "<my public acm cert>"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  labels:
    gateway.networking.k8s.io/gateway-name: external
    io.cilium.gateway/owning-gateway: external
  name: cilium-gateway-external
  namespace: kube-system
  ownerReferences:
  - apiVersion: gateway.networking.k8s.io/v1
    controller: true
    kind: Gateway
    name: external
```

HTTPRoute request redirect:

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: https-upgrade
  namespace: https-upgrade
  labels:
    https-upgrade: "true"
spec:
  parentRefs:
    - name: external
      namespace: kube-system
      sectionName: shared-http  # this doesn't seem to matter at all
      kind: Gateway
  hostnames:
    - "<my internet-facing elb>"
  rules:
    - filters:
      - type: RequestRedirect
        requestRedirect:
          scheme: https
```

HTTPRoute 443 to my service:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    app: api-gateway
  name: api-gateway
  namespace: default
spec:
  hostnames:
  - "<my internet-facing elb>"
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: external
    namespace: kube-system
    sectionName: shared-https  # this doesn't seem to matter at all
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: api-gateway
      namespace: default
      port: 9000
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
```

### How can we reproduce the issue?

I also have the AWS Load Balancer controller installed in my cluster to provision an NLB instead of Classic, but both types of LBs produce the same result.

1. Provision a public AWS ACM cert
2. Create a gateway like above
  - no tls section since the cert is handling that
  - with or without hostnames property will produce the same results
3. Annotate the Service created by the Gateway with `service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <cert arn>`, and make it a internet-facing LB (Classic or NLB both produce the same results)
4. Create HTTPRoute with RequestRedirect filter like above.
5. Create separate Service with an endpoint, like the echo example.
6. Create HTTPRoute with `backendRef` like above for the second created Service.
7. Hit HTTP AWS ELB endpoint, view network logs in dev tools to see infinite redirect loop

### Cilium Version

v1.16.1

### Kernel Version

Linux ip-10-3-3-27.us-east-2.compute.internal 5.10.219-208.866.amzn2.x86_64 #1 SMP Tue Jun 18 14:00:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.31.0
Server Version: v1.30.2-eks-db838b0

### Regression

_No response_

### Sysdump

Can't due to my environment.

### Relevant log output

_No response_

### Anything else?

Screenshot of what the network log looks like. You can see the first one is a HTTP, then the second one is HTTPS, but then continues HTTPS redirecting to HTTPS:

image

Logs were obfuscated to hide my IP and any info regarding my cluster, elb, etc...

[Explore-logs-2024-08-22 17_19_05.json](https://github.com/user-attachments/files/16719275/Explore-logs-2024-08-22.17_19_05.json)
[Explore-logs-2024-08-22 16_40_55.txt](https://github.com/user-attachments/files/16719276/Explore-logs-2024-08-22.16_40_55.txt)

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by arybolovlev**
### Description

Add a guard around the HTTP redirect logic using the X-Forwarded-Proto header. The redirect is only performed if the header value does not match the scheme defined in the HTTPRoute resource.

This prevents infinite redirect loops in scenarios where a front proxy or load balancer terminates TLS and passes unencrypted traffic to Envoy. By checking this header, Envoy can distinguish between redirected traffic and traffic that originally started as a secure connection.

The `--gateway-api-xff-num-trusted-hops` flag must be set to the desired number of trusted hops in order for Envoy to rely on the X-Forwarded-Proto header.

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Write a short paragraph that states whether you used machine learning models
      (including LLMs and other generative AI), and indicate the rating using
      [AI Influence Level](https://danielmiessler.com/blog/ai-influence-level-ail).
      Example: "This PR was prepared with AIL:3. I personally reviewed each line
      of the submission prior to opening this PR."
- [ ] Thanks for contributing!

Fixes: #34539

```release-note
Fix infinite HTTP redirect loops by honoring the X-Forwarded-Proto header to detect TLS termination at external load balancers.
```

### CODE REVIEW

File: operator/pkg/model/model.go [hunk 1]
```diff
@@ -383,6 +383,12 @@ func (r *HTTPRoute) GetMatchKey() string {
 		sb.WriteString("|")
 	}
 
+	if r.RequestRedirect != nil && r.RequestRedirect.Scheme != nil {
```
Comment (arybolovlev) [inline operator/pkg/model/model.go:386]: The motivation behind this change is to ensure that in cases where there are two similar matches with different actions (redirect and backend), it produces two respective routes where the redirect one is guarded and, thus, should not cause any logical route issues.

File: operator/pkg/model/translation/envoy_virtual_host.go [hunk 2]
```diff
@@ -502,6 +505,20 @@ func getRouteRedirect(redirect *model.HTTPRequestRedirectFilter, listenerPort ui
 	}
 }
 
+func getRouteRedirectMatch(match string) *envoy_config_route_v3.HeaderMatcher {
+	return &envoy_config_route_v3.HeaderMatcher{
+		Name: "X-Forwarded-Proto",
+		HeaderMatchSpecifier: &envoy_config_route_v3.HeaderMatcher_StringMatch{
+			StringMatch: &envoy_type_matcher_v3.StringMatcher{
```
Comment (mhofstetter) [inline operator/pkg/model/translation/envoy_virtual_host.go:512]: add `IgnoreCase: true` to be on the safe side? :sweat_smile:

**Review by mhofstetter — COMMENTED** [review]
Thanks for the contribution @arybolovlev . Looks good to me so far. only one nit.

File: operator/pkg/model/translation/envoy_virtual_host.go (hunk 2 above)
Comment (arybolovlev) [reply operator/pkg/model/translation/envoy_virtual_host.go:512]: This is a very good catch, thank you!

Comment (mhofstetter) [reply operator/pkg/model/translation/envoy_virtual_host.go:512]: thanks for adding it! let's squash the extra-commit before merging. but let's wait for the first test-run.

**Review by youngnick — APPROVED** [review]
LGTM, nice work.

**Comment by mhofstetter** [comment]
@arybolovlev `ci-integration` failures are related to the PR changes. please take a look

**Review by mhofstetter — APPROVED** [review]
Thanks!
