### PR TITLE
Attach to-wireguard to the tc egress of cilium_wg0

### LINKED ISSUE #32899: Broken connectivity of pod to remote nodeport when Wireguard is used with L7 ingress policy + native routing + KPR
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 1. Create kind cilium cluster

```
make kind-down
export IMAGE=kindest/node:v1.29.4@sha256:3abb816a5b1061fb15c6e9e60856ec40d56b7b52bcea5f5f1350bc6e2320b6f8
./contrib/scripts/kind.sh --xdp --secondary-network "" 3 "" "" iptables dual 0.0.0.0 6443
 kubectl patch node kind-worker3 --type=json -p='[{"op":"add","path":"/metadata/labels/cilium.io~1no-schedule","value":"true"}]'

git checkout 8cd748de7f4011d4ab9fc04338fa69c194205e6a # https://github.com/cilium/cilium/commit/8cd748de7f4011d4ab9fc04338fa69c194205e6a
make kind-image
kind load --name kind docker-image localhost:5000/cilium/cilium-dev:local
 kind load --name kind docker-image localhost:5000/cilium/operator-generic:local
 ./cilium-cli install --wait     --chart-directory=./install/kubernetes/cilium     --helm-set=debug.enabled=true     --helm-set=debug.verbose=envoy     --helm-set=hubble.eventBufferCapacity=65535     --helm-set=bpf.monitorAggregation=none     --helm-set=cluster.name=default     --helm-set=authentication.mutual.spire.enabled=false     --nodes-without-cilium     --helm-set-string=kubeProxyReplacement=true     --set='' --helm-set-string=routingMode=native --helm-set-string=autoDirectNodeRoutes=true --helm-set-string=ipv4NativeRoutingCIDR=10.244.0.0/16 --helm-set-string=ipv6NativeRoutingCIDR=fd00:10:244::/56 --helm-set=devices='{eth0,eth1}' --helm-set-string=loadBalancer.mode=snat  --helm-set=ipv6.enabled=true --helm-set=bpf.masquerade=true --helm-set=egressGateway.enabled=true --helm-set=encryption.enabled=true --helm-set=encryption.type=wireguard --helm-set=encryption.nodeEncryption=true --helm-set=encryption.ipsec.encryptedOverlay=false   --helm-set=ingressController.enabled=true --helm-set=ingressController.service.type=NodePort --helm-set=image.repository=localhost:5000/cilium/cilium-dev   --helm-set=image.useDigest=false   --helm-set=image.tag=local   --helm-set=operator.image.repository=localhost:5000/cilium/operator      --helm-set=operator.image.tag=local --helm-set operator.image.suffix=   --helm-set=operator.image.useDigest=false  --helm-set=image.pullPolicy=IfNotPresent --helm-set=operator.image.pullPolicy=IfNotPresent  --helm-set=debug.verbose=datapath
./cilium-cli status --wait
./cilium-cli connectivity test --include-unsafe-tests  --flush-ct --test "skipall"  -v  -p
```

### 2.  Check pod to remote nodeport connectivity

```
# kubectl -ncilium-test get po -owide | grep client2
client2-ccd7b8bdf-dtdng              1/1     Running   0          32m   10.244.3.159   kind-worker2         <none>           <none>

# kubectl -nkube-system get po -owide | grep cilium | grep kind-worker
cilium-2lwb2                                 1/1     Running   0          34m   172.19.0.5     kind-worker2         <none>           <none>
cilium-9bn77                                 1/1     Running   0          34m   172.19.0.4     kind-worker          <none>           <none>
cilium-envoy-6s69m                           1/1     Running   0          34m   172.19.0.5     kind-worker2         <none>           <none>
cilium-envoy-wjhfh                           1/1     Running   0          34m   172.19.0.4     kind-worker          <none>           <none>
cilium-operator-7b87f5b697-w88vj             1/1     Running   0          34m   172.19.0.4     kind-worker   

# client2 pod is on kind-worker2, so we choose a remote nodeport on kind-worker
# kubectl -nkube-system exec cilium-9bn77 -- cilium service list  | grep -i hostport
17   172.19.0.4:4000           HostPort       1 => 10.244.2.175:8080 (active)            
18   [fc00:c111::4]:4000       HostPort       1 => [fd00:10:244:2::fc99]:8080 (active)   
19   0.0.0.0:4000              HostPort       1 => 10.244.2.175:8080 (active)   
20   [::]:4000                 HostPort       1 => [fd00:10:244:2::fc99]:8080 (active) 

# kubectl -ncilium-test exec client2-ccd7b8bdf-dtdng  -- curl 172.19.0.4:4000 -I
HTTP/1.1 200 OK
X-Powered-By: Express
Vary: Origin, Accept-Encoding
Access-Control-Allow-Credentials: true
Accept-Ranges: bytes
Cache-Control: public, max-age=0
Last-Modified: Tue, 09 Jan 2024 12:57:12 GMT
ETag: W/"809-18cee4c6040"
Content-Type: text/html; charset=UTF-8
Content-Length: 2057
Date: Wed, 05 Jun 2024 03:38:14 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

### 3. Apply an L7 ingress policy and check connectivity again

```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-8080-ingress
spec:
  endpointSelector:
    matchLabels:
      kind: echo
  ingress:
  - fromEntities:
    - all
    toPorts:
    - ports:
      - port: "8080"
        protocol: TCP
      rules:
        http:
        - method: "GET"
          path: "/$"
```
```
kubectl -ncilium-test apply -f allow-8080-ingress.yaml
```
Then pod to remote nodeport can't be connected:
```
$ kubectl -ncilium-test exec client2-ccd7b8bdf-dtdng  -- curl 172.19.0.4:4000 -I -v
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 172.19.0.4:4000...
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0^C
```

### Cilium Version

```
Client: 1.16.0-dev 8cd748de7f 2024-05-20T11:00:02+09:00 go version go1.22.3 linux/amd64
Daemon: 1.16.0-dev 8cd748de7f 2024-05-20T11:00:02+09:00 go version go1.22.3 linux/amd64
```

### Kernel Version

Linux liangzc-l-PF4RDLEQ 6.5.0-1023-oem #24-Ubuntu SMP PREEMPT_DYNAMIC Tue May 7 14:26:31 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

This bug is similar to https://github.com/cilium/cilium/issues/32897, caused by missing revDNAT for proxy's reply.

TLDR, the proxy's reply (tcp syn-ack, on behalf of dst pod) will be wireguard-encrypted ahead of revDNAT at to-netdev@eth0, then revDNAT code can't process the encrypted packet. The reply will finally be routed back to source pod, with the wrong src IP, ending up with SKB_DROP_REASON_NO_SOCKET.

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jschwinger233**
This is to handle rev-DNAT when L7 ingress proxy is enabled with wireguard, nodeport, native routing, and KPR.

Consider a pod-to-remote-nodeport connection via L7 ingress proxy, the reply packet will pass: from_lxc@veth -> redirected to L7 proxy -> from_host@cilium_host -> to_host@cilium_net -> to_netdev@eth0 -> redirected to cilium_wg0. This patch ensures the new attached to-wireguard@cilium_wg0 can do the necessary rev-DNAT in this case.

Fixes: https://github.com/cilium/cilium/issues/32899

```release-note
Fixes a missing rev-DNAT issue when wireguard, nodeport, KPR, and L7 proxy are enabled together.
```

### CODE REVIEW

File: bpf/lib/nodeport.h [hunk 1]
```diff
@@ -3063,17 +3063,23 @@ nodeport_rev_dnat_fwd_ipv4(struct __ctx_buff *ctx, bool *snat_done,
...
+# if defined(ENABLE_WIREGUARD)
+	if (ctx_get_ifindex(ctx) != WG_IFINDEX) {
+# endif /* ENABLE_WIREGUARD */
+		/* Perform FIB lookup with post-RevDNAT src IP, and redirect
+		 * packet to the correct egress interface:
+		 */
+		fib_params.l.family = AF_INET;
+		fib_params.l.ifindex = ctx_get_ifindex(ctx);
+		fib_params.l.ipv4_src = nat_info->address;
+		fib_params.l.ipv4_dst = tuple.daddr;
```
Comment (julianwiedmann) [inline bpf/lib/nodeport.h]: Have you considered adding a new `bpf_wireguard.c` file, so that the program can identify itself as `IS_BPF_WIREGUARD` instead?

Comment (jschwinger233) [reply bpf/lib/nodeport.h]: Yeah definitely, I was just not sure which one is better. Currently busy with debugging broken NS connectivity :fearful:

Comment (jschwinger233) [reply bpf/lib/nodeport.h]: It turns out the skbs are entering tail_handle_snat_fwd_ipv4 tailcall from tail_handle_nat_fwd_ipv4 after failing rev DNAT. For now I added an early return after rev dnat:

```c
static __always_inline int
__handle_nat_fwd_ipv6(struct __ctx_buff *ctx, struct trace_ctx *trace,
		      __s8 *ext_err)
{
	bool snat_done = false;
	int ret;

	ret = nodeport_rev_dnat_fwd_ipv6(ctx, &snat_done, trace, ext_err);
	if (ret != CTX_ACT_OK)
		return ret;

+ #if defined(ENABLE_WIREGUARD)
+ 	if (ctx_get_ifindex(ctx) == WG_IFINDEX) {
+		return CTX_ACT_OK;
+	}
+ #endif /* ENABLE_WIREGUARD */
```

If CI is happy with this, I'll then move the whole thing into a `bpf_wg.c` with specific macros.

**Comment by jschwinger233** [comment]
Can't believe adding these trivial code leads to `BPF program is too large` :fearful: 
```
2024-07-01T08:54:07.534681504Z time="2024-07-01T08:54:07Z" level=error msg="endpoint regeneration failed" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=2725 error="loading eBPF collection into the kernel: program cil_to_netdev: load program: argument list too long: BPF program is too large. Processed 1000001 insn (1900 line(s) omitted)" identity=1 ipv4= ipv6= k8sPodName=/ subsys=endpoint
```

File: pkg/datapath/loader/base.go [hunk 2]
```diff
@@ -277,6 +277,38 @@ func (l *loader) reinitializeOverlay(ctx context.Context, tunnelConfig tunnel.Co
...
+		"-DENABLE_WIREGUARD=1",
+		"-DENABLE_NODEPORT=1",
+	}
+	if option.Config.EnableIPv4 {
+		opts = append(opts, "-DENABLE_IPV4")
+	}
+	if option.Config.EnableIPv6 {
+		opts = append(opts, "-DENABLE_IPV6")
+	}
+
```
Comment (julianwiedmann) [inline pkg/datapath/loader/base.go]: These should all come via `node_config.h`, no?

File: bpf/lib/nodeport.h [hunk 3]
```diff
@@ -3087,7 +3089,7 @@ nodeport_rev_dnat_fwd_ipv4(struct __ctx_buff *ctx, bool *snat_done,
 	if (!nat_info)
 		return CTX_ACT_OK;
 
-#if defined(IS_BPF_HOST) && !defined(ENABLE_SKIP_FIB)
+#if defined(IS_BPF_HOST) && !defined(ENABLE_SKIP_FIB) && !defined(IS_BPF_WIREGUARD)
```
Comment (julianwiedmann) [inline bpf/lib/nodeport.h]: Do we really still need to check for both `IS_BPF_HOST` *and* `IS_BPF_WIREGUARD` ?

**Review by dylandreimerink — APPROVED** [review]
Loader bits look good to me

File: bpf/bpf_wireguard.c [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+#include "lib/eth.h"
+#include "lib/dbg.h"
+#include "lib/trace.h"
+#include "lib/l3.h"
+#include "lib/drop.h"
+#include "lib/identity.h"
+#include "lib/nodeport.h"
+#include "lib/clustermesh.h"
+#include "lib/egress_gateway.h"
+
```
Comment (julianwiedmann) [inline bpf/bpf_wireguard.c]: I bet we can slim this down quite a bit :grin:

File: bpf/bpf_wireguard.c [hunk 5]
```diff
@@ -0,0 +1,48 @@
...
+	__s8 ext_err = 0;
+
+	struct trace_ctx trace = {
+		.reason = TRACE_REASON_UNKNOWN,
+		.monitor = 0,
+	};
+
+	if (validate_ethertype(ctx, &proto))
+		return handle_nat_fwd(ctx, 0, proto, &trace, &ext_err);
+
```
Comment (julianwiedmann) [inline bpf/bpf_wireguard.c]: Let's just use `ctx_get_protocol()` here, since we know it's a L3 device?

I think we also need to handle returned errors, and raise a drop notification for them.

File: bpf/bpf_wireguard.c [hunk 6]
```diff
@@ -0,0 +1,48 @@
...
+int cil_to_wireguard(struct __ctx_buff *ctx)
+{
+	__u16 proto;
+	__s8 ext_err = 0;
+
+	struct trace_ctx trace = {
+		.reason = TRACE_REASON_UNKNOWN,
+		.monitor = 0,
+	};
+
```
Comment (julianwiedmann) [inline bpf/bpf_wireguard.c:31]: Mind adding a `bpf_clear_meta(ctx)` here, for robustness?

**Review by julianwiedmann — CHANGES_REQUESTED** [review]
Thank you! Took a first swing at the BPF parts, only minor things so far.

File: pkg/datapath/loader/base.go (hunk 2 above)
Comment (jschwinger233) [reply pkg/datapath/loader/base.go]: Thank you! No wonder `reinitializeOverlay()` doesn't specify `-DENABLE_IPVX` at all.

File: bpf/lib/nodeport.h (hunk 3 above)
Comment (jschwinger233) [reply bpf/lib/nodeport.h]: Maybe I don't have to check `IS_BPF_WG` here, instead I can set `ENABLE_SKIP_FIB=1` for bpf_wireguard compiling?

File: bpf/bpf_wireguard.c (hunk 4 above)
Comment (jschwinger233) [reply bpf/bpf_wireguard.c]: Will do

File: bpf/lib/nodeport.h (hunk 3 above)
Comment (julianwiedmann) [reply bpf/lib/nodeport.h]: `IS_BPF_HOST` is *only* defined in `bpf_host.c`. If we're compiling any other file, this code should be excluded already.

File: pkg/datapath/loader/base.go (hunk 2 above)
Comment (dylandreimerink) [reply pkg/datapath/loader/base.go]: Yes, you are right, good catch. At least `DENABLE_IPV4` and `DENABLE_IPV6` are. The `opts := []string` part is also present in the reinitializeOverlay so we might need those still.

Comment (julianwiedmann) [reply pkg/datapath/loader/base.go]: ack, `SECLABEL` and `THIS_INTERFACE_MAC` is needed (and the `CALLS_MAP` ofc).

I'm unsure what the appropriate value for `SECLABEL` would be in WG context. So let's stick with `WORLD_ID` for now :+1:.

File: bpf/bpf_wireguard.c [hunk 7]
```diff
@@ -0,0 +1,48 @@
...
+#include "lib/drop.h"
+#include "lib/identity.h"
+#include "lib/nodeport.h"
+#include "lib/clustermesh.h"
+#include "lib/egress_gateway.h"
+
+/* to-wireguard is attached as a tc egress filter to the cilium_wg0 device.
+ */
+__section_entry
+int cil_to_wireguard(struct __ctx_buff *ctx)
```
Comment (julianwiedmann) [inline bpf/bpf_wireguard.c:20]: Maybe we also want to add the new program to `classifyProgramTypes()` ?

**Comment by julianwiedmann** [comment]
just noting down a few follow-up steps we'd want to sort out:
* CODEOWNERS for bpf_wireguard.c should probable also pull in sig/wireguard
* bpf/Makefile enhancements to build-test the program (can probably re-use the same configs as for bpf_host)
* bpf/complexity-tests enhancements (same as for bpf/Makefile)

File: bpf/bpf_wireguard.c (hunk 6 above)
Comment (jschwinger233) [reply bpf/bpf_wireguard.c:31]: I added `__u32 src_sec_identity = ctx_load_and_clear_meta(ctx, CB_SRC_LABEL)`. In the meantime, I called `ctx_store_meta(ctx, CB_SRC_LABEL, src->sec_identity)` before bpf_redirect(wg_ifindex) in `bpf/lib/wireguard.h`.

Comment (julianwiedmann) [reply bpf/bpf_wireguard.c:31]: hm I don't think that will work / is robust. We have to assume that the kernel stack uses `skb->cb` while processing the packet (before delivering it to the wireguard interface). Hence we typically share such cross-interface context via skb->mark. So I think you would need to use `set_identity_mark()` here.

File: pkg/datapath/loader/base.go [hunk 8]
```diff
@@ -277,6 +277,35 @@ func (l *loader) reinitializeOverlay(ctx context.Context, tunnelConfig tunnel.Co
...
+		return fmt.Errorf("failed to retrieve link for interface %s: %w", wgTypes.IfaceName, err)
+	}
+
+	opts := []string{
+		fmt.Sprintf("-DSECLABEL=%d", identity.ReservedIdentityWorld),
+		fmt.Sprintf("-DTHIS_INTERFACE_MAC={.addr=%s}", mac.CArrayString(link.Attrs().HardwareAddr)),
+		fmt.Sprintf("-DCALLS_MAP=cilium_calls_wireguard_%d", identity.ReservedIdentityWorld),
+
+		"-DENABLE_NODEPORT=1",
+	}
```
Comment (julianwiedmann) [inline pkg/datapath/loader/base.go]: This should also come via the [node_config.h](https://github.com/cilium/cilium/blob/99adddceccdc120ad75e6e63c79c9929fa813a59/pkg/datapath/linux/config/config.go#L426), I believe.

**Review by bimmlerd — APPROVED** [review]
CODEOWNERS lgtm

**Review by aanm — APPROVED** [review]

**Review by brb — APPROVED** [review]
Thanks!

File: bpf/bpf_wireguard.c [hunk 9]
```diff
@@ -0,0 +1,45 @@
+// SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause)
+/* Copyright Authors of Cilium */
+
+#define ETH_HLEN 0
+#define IS_BPF_WIREGUARD 1
+#define ENABLE_WIREGUARD 1
```
Comment (julianwiedmann) [inline bpf/bpf_wireguard.c]: Do we need the `ENABLE_WIREGUARD` ? It should be part of the `node_config.h`, no?

File: bpf/complexity-tests/510/bpf_wireguard/1.txt [hunk 10]
```diff
@@ -0,0 +1,37 @@
...
+-DENABLE_HOST_ROUTING=1
+-DENABLE_BANDWIDTH_MANAGER=1
+-DETH_HLEN=0
+-DENCAP_IFINDEX=1
+-DTUNNEL_MODE=1
+-DENABLE_EGRESS_GATEWAY=1
+-DENABLE_VTEP=1
+-DENABLE_SCTP=1
+-DENABLE_WIREGUARD=1
+-DIS_BPF_WIREGUARD=1
```
Comment (julianwiedmann) [inline bpf/complexity-tests/510/bpf_wireguard/1.txt]: Note that IS_BPF_WIREGUARD shouldn't be needed here - it already gets defined by the program itself.

(the other complexity configs don't specify their `IS_BPF_*` value)

**Review by julianwiedmann — APPROVED** [review]
Looks good, thank you!

Just two smaller nits in case you need to rebase once more. Otherwise we can clean those up later.

**Comment by brb** [comment]
BTW, with this PR merged, we can easily tackle:
> Create and load from-wireguard instead of from-netdev (https://github.com/cilium/cilium/pull/19401#discussion_r1066070869).

From https://github.com/cilium/cilium/issues/23032. It will give us a few CPU cycles back :sunglasses:
