### PR TITLE
resource: Fix flaky test due to missing Done call

### LINKED ISSUE #24696: CI: TestResource_WithFakeClient panic
## CI failure

https://app.travis-ci.com/github/cilium/cilium/builds/261984304

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━���━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃   PANIC  package: github.com/cilium/cilium/pkg/k8s/resource • TestResource_WithFakeClient   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
panic: runtime error: invalid memory address or nil pointer dereference [recovered]            
	panic: runtime error: invalid memory address or nil pointer dereference                        
[signal SIGSEGV: segmentation violation code=0x1 addr=0x188 pc=0x158bad0]                      
                                                                                               
goroutine 14 [running]:                                                                        
testing.tRunner.func1.2({0x17bd7c0, 0x2d1ae00})                                                
	/home/travis/.gimme/versions/go1.20.1.linux.arm64/src/testing/testing.go:1526 +0x1c8           
testing.tRunner.func1()                                                                        
	/home/travis/.gimme/versions/go1.20.1.linux.arm64/src/testing/testing.go:1529 +0x364           
panic({0x17bd7c0, 0x2d1ae00})                                                                  
	/home/travis/.gimme/versions/go1.20.1.linux.arm64/src/runtime/panic.go:884 +0x1f4              
github.com/cilium/cilium/pkg/k8s/resource_test.TestResource_WithFakeClient(0x4000425a00)       
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/k8s/resource/resource_test.go:167 +0xa70  
testing.tRunner(0x4000425a00, 0x1b812d0)                                                       
	/home/travis/.gimme/versions/go1.20.1.linux.arm64/src/testing/testing.go:1576 +0x104           
created by testing.(*T).Run                                                                    
	/home/travis/.gimme/versions/go1.20.1.linux.arm64/src/testing/testing.go:1629 +0x370           
FAIL	github.com/cilium/cilium/pkg/k8s/resource	60.044s   
```

### PR DESCRIPTION
**Pull request by joamaki**
The workaround in 5fa2ac4be5 was faulty as it did not call ev.Done on the received event leading to further events not being received and thus eventually causing the context to time out. The problem was reproduced reliably locally by adding short time.Sleep calls to the pushUpdate and the initial listing to trigger the race causing the double updates.

To remedy this, add the missing ev.Done call, handle timeout gracefully and make assertions FailNow immediately to not mask problems due to e.g. nil deref.

FIxes: #24696
Fixes: 5fa2ac4be5 ("resource: Work around a rare race in initial sync")

### CODE REVIEW

File: pkg/k8s/resource/resource_test.go [hunk 1]
```diff
@@ -125,7 +139,8 @@ func TestResource_WithFakeClient(t *testing.T) {
 	}
 
 	// First event should be the node (initial set)
-	ev := <-events
+	ev, ok := <-events
+	assert.True(t, ok)
```
Comment (lmb) [inline pkg/k8s/resource/resource_test.go]: Why not use require? https://pkg.go.dev/github.com/stretchr/testify/require

Comment (joamaki) [reply pkg/k8s/resource/resource_test.go]: Doh! Didn't know it existed. Fixing :)

**Review by lmb — APPROVED** [review]

File: pkg/k8s/resource/resource_test.go [hunk 2]
```diff
@@ -40,7 +41,7 @@ func TestMain(m *testing.M) {
 	goleak.VerifyTestMain(m, goleak.Cleanup(cleanup))
 }
 
-func testStore(t *testing.T, node *corev1.Node, store resource.Store[*corev1.Node]) {
+func testStore(t testing.TB, node *corev1.Node, store resource.Store[*corev1.Node]) {
```
Comment (lmb) [inline pkg/k8s/resource/resource_test.go]: Nit: the change is probably not required anymore? Conventionally this should be `tb` now which would lead to a lot of churn.

Comment (joamaki) [reply pkg/k8s/resource/resource_test.go]: Reverted this hunk.

**Comment by joamaki** [comment]
Relevant test is the `pkg/k8s/resource` unit test  (run as part of `Travis CI`) and since there's no functional changes we don't need the full CI run.

**Review by youngnick — APPROVED** [review]
