### PR TITLE
test: Fix the flake for TestRestoredPort

### LINKED ISSUE #37091: CI: Integration Test - TestRestoredPort
## CI failure

Link: https://github.com/cilium/cilium/actions/runs/12867119980/job/35871110616

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃   FAIL  package: github.com/cilium/cilium/pkg/proxy/proxyports   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

--- FAIL: TestRestoredPort (0.01s)

time="2025-01-20T11:47:21.003558766Z" level=info msg="Adding new proxy port rules for cilium-http-egress:17266" id=cilium-http-egress subsys=proxy
    proxyports_test.go:282: 
        	Error Trace:	/home/runner/work/cilium/cilium/pkg/proxy/proxyports/proxyports_test.go:282
        	Error:      	Should be zero, but was 17266
        	Test:       	TestRestoredPort
```

### PR DESCRIPTION
**Pull request by sayboras**
Testing was done locally as per below

```
➜  cilium git:(main) ✗ go test -count=1000 ./pkg/proxy/proxyports/... -test.run TestRestoredPort
ok      github.com/cilium/cilium/pkg/proxy/proxyports   4.666s
```

Fixes: #37091

### CODE REVIEW

File: pkg/proxy/proxyports/proxyports_test.go [hunk 1]
```diff
@@ -278,8 +279,8 @@ func TestRestoredPort(t *testing.T) {
 	require.Zero(t, pp.nRedirects)
 
 	// wait for port reuse wait to pass
-	time.Sleep(time.Millisecond)
```
Comment (joestringer) [inline pkg/proxy/proxyports/proxyports_test.go:281]: I'd like to know why this slipped through review; `time.Sleep()` is notorious for causing this kind of problem and I personally think we should have a near zero tolerance for it during review.

**Review by joestringer — APPROVED** [review]

File: pkg/proxy/proxyports/proxyports_test.go (hunk 1 above)
Comment (joestringer) [reply pkg/proxy/proxyports/proxyports_test.go:281]: Ref https://github.com/cilium/cilium/pull/36953 , something to consider for future @jrajahalme @aanm @sayboras .

**Comment by joestringer** [comment]
Marked the labels to match https://github.com/cilium/cilium/pull/36953 .

File: pkg/proxy/proxyports/proxyports_test.go (hunk 1 above)
Comment (sayboras) [reply pkg/proxy/proxyports/proxyports_test.go:281]: hope that the coming syntest in go 1.24 can help in this case, we can enable linter to disallow time.Sleep, the author can bypass if required.

**Review by jrajahalme — APPROVED** [review]
Thanks for the fix!
