### PR TITLE
cilium-cli: fix connectivity tests for IPv6-only clusters

### LINKED ISSUE #35553: Add support for Cilium connectivity test on IPv6-only clusters
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

When running `cilium connectivity test` there is the assumption that the user can reach `1.1.1.1` which isn't the case in IPv6-only deployments, and as it is an IP, even with NAT64.

I did also try `cilium connectivity test --external-ip "2606:4700:4700::1111" --external-other-ip "2606:4700:4700::1001" --external-cidr "2606:4700:4700::/48"`, but it parses the last segment of IPv6 address to ports (putting them in square brackets straight up crashes it, and specifying a port like `2606:4700:4700::1111:443` after seems to work-ish but is surprising and non-obvious, and seems to still cause the tests to fail).

### How can we reproduce the issue?

- Install with IPv6 connectivity only.
- Run `cilium connectivity test`

### Cilium Version

1.16.2

### Kernel Version

6.8.0-47-generic

### Kubernetes Version

v1.30.5+k3s1

### Regression

_No response_

### Sysdump

N/a

### Relevant log output

N/a

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by wedaly**
Handle external CIDR and IP addresses uses IPv6.

Command used to test:
```
  cilium connectivity test \
    --external-ip "2606:4700:4700::1111" \
    --external-other-ip "2606:4700:4700::1001" \
    --external-cidr "2606:4700:4700::/48"
 ```
 
 I used this script to create an IPv6-only cluster with Cilium in kind (adapted from delegated IPAM dual-stack E2E tests): https://gist.github.com/wedaly/26123c19baeaf62f092cdc52cf8c3c4e
 
 This fixes all of the test failures except for `to-fqdns` which fails trying to curl cilium.io, which doesn't currently have any IPv6 addresses.

Fixes: #35553

```release-note
Fix cilium CLI connectivity tests in IPv6-only clusters.
```

### CODE REVIEW

File: cilium-cli/connectivity/builder/manifests/template/template.go [hunk 1]
```diff
@@ -6,13 +6,22 @@ package template
...
 func Render(temp string, data any) (string, error) {
 	fns := template.FuncMap{
 		"trimSuffix": func(in, suffix string) string { return strings.TrimSuffix(in, suffix) },
+		"ipToCIDR": func(ipString string) string {
+			ip := net.ParseIP(ipString)
+			if ip != nil && ip.To4() == nil {
+				return ipString + "/128" // ipv6 address
+			} else {
+				return ipString + "/32" // otherwise assume IPv4
+			}
```
Comment (tklauser) [inline cilium-cli/connectivity/builder/manifests/template/template.go]: Let's use the more modern `net/netip` package here (cf. https://github.com/cilium/cilium/issues/24246):

```suggestion
			ip, err := netip.ParseAdd(ipString)
			if err == nil && ip.Is6() {
				return ipString + "/128"
			} else {
				return ipString + "/32" // otherwise assume IPv4
			}
```

File: cilium-cli/connectivity/tests/to-cidr.go [hunk 2]
```diff
@@ -51,3 +52,16 @@ func (s *podToCIDR) Run(ctx context.Context, t *check.Test) {
...
+func ipToName(ip string) string {
+	ipWithoutSep := strings.ReplaceAll(ip, ".", "")          // IPv4 separator
+	ipWithoutSep = strings.ReplaceAll(ipWithoutSep, ":", "") // IPv6 separator
+	return fmt.Sprintf("external-%s", ipWithoutSep)
+}
+
+func ipToURL(ipString string) string {
+	if ip := net.ParseIP(ipString); ip != nil && ip.To4() == nil {
+		ipString = fmt.Sprintf("[%s]", ipString) // Avoid parsing IPv6 last ":" as port
+	}
```
Comment (tklauser) [inline cilium-cli/connectivity/tests/to-cidr.go]: Same here, let's use `net/netip`:

```suggestion
	if ip, err := netip.ParseAddr(ipString); err == nil && ip.Is6() {
		ipString = fmt.Sprintf("[%s]", ipString) // Avoid parsing IPv6 last ":" as port
	}
```

**Comment by wedaly** [comment]
thanks, updated to use `net/netip` package

**Review by doniacld — APPROVED** [review]

**Comment by wedaly** [comment]
Rebased to try to fix CI failures
```
+ docker run --network host -v /home/runner/.kube/config:/root/.kube/config -v /home/runner/work/cilium/cilium:/root/app -v /home/runner/.aws:/root/.aws -v /home/runner/.azure:/root/.azure -v /home/runner/.config/gcloud:/root/.config/gcloud quay.io/cilium/cilium-cli-ci:2a9e656b33c09645b9f8a533a7cb02bfdc84265e cilium features status -o markdown --output-file=feature-status.md
unknown command "features" for "cilium"
```

Suspect my branch was out-of-date, since features CLI command got added recently

**Review by tklauser — APPROVED** [review]

**Review by brlbil — APPROVED** [review]
