### PR TITLE
fix(gateway-api): add retry with backoff for CRD discovery on transient errors

### LINKED ISSUE #43130: Gateway API TLS termination fails permanently if API server is temporarily unreachable during operator startup
# Gateway API TLS termination fails permanently if API server is temporarily unreachable during operator startup

## Is there an existing issue for this?

- [x] I have searched the existing issues

**Related issue**: #32596 (closed as stale without resolution)

## What happened?

When Cilium operator starts and the Kubernetes API server is temporarily unreachable (even for a few seconds), the Gateway API controller fails to initialize and **never recovers**. This results in:

1. TLS secrets not being synchronized to `cilium-secrets` namespace
2. Envoy proxy starting with 0 TLS secrets
3. All HTTPS traffic through Gateway API failing with "Connection reset by peer" during TLS handshake
4. HTTP traffic continues to work (redirects to HTTPS)
5. Gateway resources show `Programmed: True` even though TLS termination is broken

**Expected behavior**: Cilium operator should retry Gateway API initialization or use a watch-based approach that recovers when API server becomes available.

**Actual behavior**: Gateway API controller initialization fails once and is never retried. The operator continues running but Gateway API secret sync is permanently broken until operator pod is manually restarted.

## How can we reproduce the issue?

1. Set up a Kubernetes cluster with Cilium and Gateway API enabled
2. Create a Gateway with TLS termination using cert-manager certificates
3. Verify HTTPS works correctly
4. Simulate API server unavailability during operator restart:
   - Either restart operator while API server is under load/briefly unavailable
   - Or in a single-node cluster, reboot the node (race condition between components starting)
5. After operator starts, check:
   - `kubectl get secrets -n cilium-secrets` - will be empty
   - `kubectl logs -n kube-system deployment/cilium-operator | grep -i gateway` - will show the error
   - HTTPS requests to Gateway will fail with TLS handshake errors

## Evidence from logs

**Cilium operator logs showing the failure:**
```
level=info msg="Checking for required and optional GatewayAPI resources" requiredGVK="[gateway.networking.k8s.io/v1, Kind=gatewayclasses ...]"
level=error msg="Required GatewayAPI resources are not found, please refer to docs for installation instructions" error="Get \"https://172.16.101.101:6443/apis/apiextensions.k8s.io/v1/customresourcedefinitions/gatewayclasses.gateway.networking.k8s.io\": dial tcp 172.16.101.101:6443: connect: no route to host"
level=info msg=Invoked duration=21.507194468s function="gateway-api.initGatewayAPIController"
```

**Secret sync registration missing Gateway (compare with working state):**
```
# Broken state - Gateway missing from registrations:
level=info msg="Setting up Secret synchronization" registrations="[*v2.CiliumClusterwideNetworkPolicy -> \"cilium-secrets\" *v2.CiliumNetworkPolicy -> \"cilium-secrets\"]"

# Working state (from issue #32596 comment by @ivucica):
level=info msg="Setting up Secret synchronization" registrations="[*v1.Ingress -> \"cilium-secrets\" *v2.CiliumNetworkPolicy -> \"cilium-secrets\" *v2.CiliumClusterwideNetworkPolicy -> \"cilium-secrets\" *v1.Gateway -> \"cilium-secrets\"]"
```

**Cilium agent logs showing Envoy failing to get secrets:**
```
level=info msg="[loading 0 static secret(s)" subsys=envoy-config
level=info msg="[gRPC config: initial fetch timed out for type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret" subsys=envoy-config
level=info msg="[gRPC config: initial fetch timed out for type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret" subsys=envoy-config
level=info msg="[gRPC config: initial fetch timed out for type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret" subsys=envoy-config
```

**Gateway shows healthy but TLS is broken:**
```
$ kubectl get gateway -A
NAMESPACE     NAME                      CLASS    ADDRESS          PROGRAMMED
kube-system   cilium-gateway-internal   cilium   172.16.100.250   True

$ curl -v https://myapp.home.example.com/
* TLS handshake, Client hello
* Recv failure: Connection reset by peer
curl: (35) Recv failure: Connection reset by peer
```

## Root Cause Analysis

Looking at the code flow:
1. `initGatewayAPIController` in `pkg/gateway-api/cell.go` checks for Gateway API CRDs at startup
2. If API server is unreachable, this check fails with network error
3. The error is logged but the function returns, and Gateway API controller is never initialized
4. Secret sync for Gateway resources is never registered
5. There is no retry mechanism or recovery path

## Suggested Fix

Options to consider:
1. **Retry loop**: Add retry with exponential backoff for Gateway API CRD discovery
2. **Watch-based initialization**: Use informers/watches that automatically handle reconnection
3. **Deferred initialization**: Initialize Gateway API controller lazily when first Gateway resource is seen
4. **Health check integration**: Report degraded status when Gateway API initialization fails, allowing orchestrators to restart the pod

## Cilium Version

```
Client: 1.18.4 afda2aa9 2025-11-12T10:14:04+00:00 go version go1.24.10 linux/arm64
Daemon: 1.18.4 afda2aa9 2025-11-12T10:14:04+00:00 go version go1.24.10 linux/arm64
```

## Kernel Version

```
6.17.0-1004-raspi (Ubuntu 25.10, Raspberry Pi ARM64)
```

## Kubernetes Version

```
Client Version: v1.34.2
Server Version: v1.34.1+k3s1
```

## Regression

Unknown. This behavior appears to exist in at least:
- v1.15.4, v1.15.5, v1.16.0-pre.2 (from issue #32596)
- v1.18.4 (this report)
- v1.19.0-pre.2 (from @ivucica comment on #32596)

## Environment

- Platform: K3s on Raspberry Pi 4 (ARM64)
- Gateway API version: v1.3.0
- TLS certificates managed by cert-manager
- Control plane HA via keepalived VIP (172.16.101.101)

## Workaround

Manually restart cilium-operator deployment after ensuring API server is fully available:
```bash
kubectl rollout restart deployment/cilium-operator -n kube-system
```

## Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

## Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by lexfrei**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer's Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

## Description

When cilium-operator starts and the Kubernetes API server is temporarily unreachable, Gateway API CRD discovery fails and never recovers. This results in permanent TLS termination failure because TLS secrets are not synchronized to the `cilium-secrets` namespace.

This PR adds retry with exponential backoff for Gateway API CRD discovery:

- **Error classification**: Distinguishes transient errors (network issues, API server overload) from permanent errors (CRDs not installed)
- **Retry loop**: Exponential backoff (1s-2min) for transient errors only
- **Health reporting**: Reports controller status via `cell.Health` for observability
- **Graceful degradation**: Permanent errors (missing CRDs) exit immediately without infinite retries

Fixes: #43130

```release-note
gateway-api: Add retry with exponential backoff for CRD discovery when API server is temporarily unreachable during operator startup
```

### CODE REVIEW

File: operator/pkg/gateway-api/cell.go [hunk 1]
```diff
@@ -127,10 +132,51 @@ func initGatewayAPIController(params gatewayAPIParams) error {
 		logfields.RequiredGVK, requiredGVKs,
 		logfields.OptionalGVK, optionalGVKs,
 	)
-	installedKinds, err := checkCRDs(context.Background(), params.K8sClient, params.Logger, requiredGVKs, optionalGVKs)
-	if err != nil {
-		params.Logger.Error("Required GatewayAPI resources are not found, please refer to docs for installation instructions", logfields.Error, err)
-		return nil
+
+	// Configure exponential backoff for CRD discovery.
```
Comment (mhofstetter) [inline operator/pkg/gateway-api/cell.go:124]: i think it would be worth to extract all checks whether Gateway API reconciliation logic should be enabled into its own [privately provided hive component](https://docs.cilium.io/en/stable/contributing/development/hive/#the-hive-api) (`cell.ProvidePrivate`)

* gateway api enabled in config
* kubeproxyreplacement enabled
* external traffic policy enabled
* gateway api crds installed in k8s api server (incl. the new retry logic)

It would provide installed kinds (GVKS) and the info whether Gateway API reconciliation logic is enabled.

Then we could depend on this component from `initGatewayAPIController` and `registerSecretSync`.

File: operator/pkg/gateway-api/cell.go [hunk 2]
```diff
@@ -193,8 +239,10 @@ func initGatewayAPIController(params gatewayAPIParams) error {
 // registerSecretSync registers the Gateway API for secret synchronization based on TLS secrets referenced
 // by a Cilium Gateway resource.
 func registerSecretSync(params gatewayAPIParams) secretsync.SecretSyncRegistrationOut {
-	// In this case, we don't care about optional CRDs, so we ignore the second parameter.
+	// Note: This check happens during cell startup, so we can't block with retry here.
```
Comment (mhofstetter) [inline operator/pkg/gateway-api/cell.go]: Both, `registerSecretSync` & `initGatewayAPIController` are executed in the Hive config phase at Cilium Operator startup. I don't see a reason why we should handle it differently for the `registerSecretSync` case. Not doing it the same way could result in inconsistent behavior (e.g. gateway api logic enabled but secret sync not registered - if we have a transient error when checking in `registerSecretSync`)

-> Another reason to extract and provide the information whether Gateway API preconditions are fulfilled (incl. CRDs are present) into its own privately provided hive cell

File: operator/pkg/gateway-api/cell.go [hunk 3]
```diff
@@ -127,10 +132,51 @@ func initGatewayAPIController(params gatewayAPIParams) error {
...
-	if err != nil {
-		params.Logger.Error("Required GatewayAPI resources are not found, please refer to docs for installation instructions", logfields.Error, err)
-		return nil
+
+	// Configure exponential backoff for CRD discovery.
+	// This allows the operator to recover if API server is temporarily unavailable at startup.
+	bo := backoff.Exponential{
+		Logger: params.Logger,
+		Min:    1 * time.Second,
+		Max:    2 * time.Minute,
```
Comment (mhofstetter) [inline operator/pkg/gateway-api/cell.go]: IMO 2 minutes are quite some time to check for these transient k8s api server issues -  think 30s would be ok as default value. we could also make this configurable via config - what do you think?

**Review by mhofstetter — CHANGES_REQUESTED** [review]
Thanks a lot for the contribution!

I left some suggestions inline - my main concern is that we don't handle `initGatewayAPIController` & `registerSecretSync` the same. Please let me know what you think.

File: operator/pkg/gateway-api/cell.go (hunk 3 above)
Comment (lexfrei) [reply operator/pkg/gateway-api/cell.go]: Done

File: operator/pkg/gateway-api/cell.go (hunk 2 above)
Comment (lexfrei) [reply operator/pkg/gateway-api/cell.go]: Done

File: operator/pkg/gateway-api/cell.go (hunk 1 above)
Comment (lexfrei) [reply operator/pkg/gateway-api/cell.go:124]: Done

File: operator/pkg/gateway-api/cell.go [hunk 4]
```diff
@@ -236,17 +276,26 @@ func initGatewayAPIController(params gatewayAPIParams) error {
...
+
 // registerSecretSync registers the Gateway API for secret synchronization based on TLS secrets referenced
 // by a Cilium Gateway resource.
-func registerSecretSync(params gatewayAPIParams) secretsync.SecretSyncRegistrationOut {
-	// Note: This check happens during cell startup, so we can't block with retry here.
-	// The main controller (initGatewayAPIController) will handle retry with backoff.
-	if _, err := checkCRDs(context.Background(), params.K8sClient, params.Logger, requiredGVKs, optionalGVKs); err != nil {
-		params.Logger.Debug("Gateway API secret sync disabled - CRDs not available", logfields.Error, err)
+func registerSecretSync(params secretSyncParams) secretsync.SecretSyncRegistrationOut {
+	if params.Preconditions == nil || !params.Preconditions.Enabled {
```
Comment (mhofstetter) [inline operator/pkg/gateway-api/cell.go]: We typically don't nil-check injected dependencies - except they are optional. These would be developer errors.

File: operator/pkg/gateway-api/cell.go [hunk 5]
```diff
@@ -151,33 +139,85 @@ func initGatewayAPIController(params gatewayAPIParams) error {
...
 		params.Health.Degraded("Gateway API initialization pending - API server unreachable", err)
 
 		if err := bo.Wait(ctx); err != nil {
-			// Context cancelled (operator shutdown)
-			return err
+			return nil, err
 		}
 	}
+
+	return &gatewayAPIPreconditions{
```
Comment (mhofstetter) [inline operator/pkg/gateway-api/cell.go]: nit: please remove above `break` statement and additional variables with a return statement if the CRDs are discovered (and remove the return after the for loop)

```
		installedKinds, err := checkCRDs(ctx, params.K8sClient, params.Logger, requiredGVKs, optionalGVKs)
		if err == nil {
			params.Health.OK("Gateway API CRDs discovered")
			return &gatewayAPIPreconditions{
				Enabled:        true,
				InstalledKinds: installedKinds,
			}, nil
		}
```

File: operator/pkg/gateway-api/cell.go (hunk 3 above)
Comment (mhofstetter) [reply operator/pkg/gateway-api/cell.go]: Thanks. But i realized that this is only the max backoff.

But the in case of transient errors we actually never terminate that loop. we also need to introduce  a timeout on the context.Context. Let's timeout the cancel after 30s and use a `Min/Max` of 200ms/5s in the `back.Exponential` instead.

Note: this is the part that is not so nice about introducing this retry in the hive config phase instead of the lifecycle phase (that would provide a context). But as long this is only for transient errors it should be fine.

File: operator/pkg/gateway-api/cell.go (hunk 1 above)
Comment (mhofstetter) [reply operator/pkg/gateway-api/cell.go:124]: thanks, looking good

**Review by mhofstetter — CHANGES_REQUESTED** [review]
Thanks for the extraction of the preconditions. We still have to set a timeout for the context that is used in the retry.

File: operator/pkg/gateway-api/cell.go (hunk 5 above)
Comment (lexfrei) [reply operator/pkg/gateway-api/cell.go]: Done

File: operator/pkg/gateway-api/cell.go (hunk 4 above)
Comment (lexfrei) [reply operator/pkg/gateway-api/cell.go]: Done

File: operator/pkg/gateway-api/cell.go (hunk 3 above)
Comment (lexfrei) [reply operator/pkg/gateway-api/cell.go]: Done

**Review by mhofstetter — APPROVED** [review]
LGTM - thanks again!
