### PR TITLE
kpr: Enable/fix Cilium socket based load balancing in different environments

### LINKED ISSUE #15137: Cilium attaching to the wrong cgroup
## Bug report

**General Information**

*Version*
```
Client: 1.9.4 07b62884c 2021-02-03T11:45:44-08:00 go version go1.15.7 linux/amd64
Daemon: 1.9.4 07b62884c 2021-02-03T11:45:44-08:00 go version go1.15.7 linux/amd64
```

*Kervel Version*
```
Linux broker1 5.10.18 #1-NixOS SMP Tue Feb 23 14:53:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

*Orchestration version (kubernetes)*
```
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-rc.0", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-rc.0", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Setup**

I am using NixOS (system state version `20.09`) with `unstable` nixpkgs.
Kubernetes has been deployed using the provided config options, refer to the [wiki](https://nixos.wiki/wiki/Kubernetes). Changes have been made to said configuration, but those changes do not affect the setup.
The important parts of the rendered `service` files are:

```
ExecStart=/nix/store/m17a776xbvs4d1f91hcka0s3289hr8a7-kubernetes-1.19.5/bin/kubelet \
            [...snip...] \
            --cgroup-driver=systemd --anonymous-auth=false --cloud-provider=external
Slice=kubernetes.slice
```

Cilium was installed using helm with the following options (custom nix, but straight-forward):

```nix
{
    ctf.platform.node.config.kubernetes.helm.cilium = {
      repo = "https://helm.cilium.io/";

      charts = [{
        path = "cilium";
        name = "cilium";
        version = "1.9.4";
        namespace = ciliumNamespace;

        values = {
          # CNI config
          cni = {
            install = false;
            configMap = configMapName;
            customConf = true;
          };

          # Rollout on config changes
          rollOutCiliumPods = true;

          # Enable sockops acceleration
          sockops.enabled = true;

          # Have k8s manage ip addresses
          ipam.mode = "kubernetes";

          # Replace kube-proxy
          kubeProxyReplacement = "strict";
          k8sServiceHost = platform.getRoleDns "master";
          k8sServicePort = platform.cfg.kubernetes.apiPort;

          # Have services be reachable by the host
          hostServices.enabled = true;
        };
      }];
    };
}
```

(The `cni.install=false` setting is not of importance here, as cilium will be installed into the correct path by NixOS (required due to `nixos-rebuild switch` re-symlinking the directory))

Now I would expect cilium to attach to the root cgroup and everything to work, but it didn't. Symptoms included: routing between nodes and pods functioning (due to the kernel routing the `PodCIDR` to the `cilium_host` interface, thus applying the bpf), but service ips not being routed properly (exiting via `bond0` in my case)

After hours of debugging it turned out, that cilium attached to the pod-internal cgroups, meaning that bpf was working properly, just _inside_ of the pod.

```
$ nix run nixpkgs.bpftool --command bpftool cgroup tree
[...snip...]
/sys/fs/cgroup/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod2ca50d7d_4376_42f7_b95e_f6cfed8082b4.slice/docker-a305231644dfdac2d21ec70d7884c6ab8b9b24b298225b7c4b5b4eb1ba15e310.scope
    3179     ingress         multi
    3178     egress          multi
    3177     device          multi
    3180     device          multi
/sys/fs/cgroup/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod2ca50d7d_4376_42f7_b95e_f6cfed8082b4.slice/docker-6da42fbcf7aa862441877a5ca52f169247c39b73174b449253ddd00386316eca.scope
    3189     ingress         multi
    3188     egress          multi
    3619     sock_ops                        bpf_sockmap
    3190     device          multi
    3639     connect4
    3634     connect6
    3641     post_bind4
    3636     post_bind6
    3642     sendmsg4
    3637     sendmsg6
    3643     recvmsg4
    3638     recvmsg6
    3640     getpeername4
    3635     getpeername6
/sys/fs/cgroup/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod1e5fa539_4583_4147_bd6f_a2633dff45b4.slice
    1964     ingress         multi
    1963     egress          multi
/sys/fs/cgroup/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod1e5fa539_4583_4147_bd6f_a2633dff45b4.slice/docker-4e9678a09c7519bc612169ef5549dd521ef0e4c9ce1c2914adf6fa730509c9ea.scope
    2089     ingress         multi
    2088     egress          multi
    1279     device          multi
    2087     device          multi
/sys/fs/cgroup/kubepods.slice/kubepods-b
[...snip...]
```

Looking through the code [here](https://github.com/cilium/cilium/blob/07b62884ce906a97a6922f9ee35a35efd6cccd55/pkg/cgroups/cgroups.go#L51) this is happening, because cilium mounts the cgroups itself from withtin the container, thus getting their own - namespaced - view.

```go
	if err := unix.Mount("none", cgroupRoot, "cgroup2", 0, ""); err != nil {
		return fmt.Errorf("failed to mount %s: %s", cgroupRoot, err)
	}
```

**Fix**

The fix turned out to be a simple one - I just needed to mount the _proper_ cgroups myself using (nix syntax again)

```nix
{
  # [...snip...]
  charts = [{
    path = "cilium";
    name = "cilium";
    version = "1.9.4";
    namespace = ciliumNamespace;

    values = {
      # [...snip...]
      extraConfig = {
        cgroup-root = "/var/run/host-cgroup";
      };

      extraHostPathMounts = [{
        name = "host-cgroup";
        type = "DirectoryOrCreate";
        hostPath = "/sys/fs/cgroup";
        mountPath = "/var/run/host-cgroup";
      }];
      # [...snip...]
    };
  }];
  # [...snip...]
}
```

After mounting the proper cgroups everything works as expected.

```
$ nix run nixpkgs.bpftool --command bpftool cgroup tree
[...snip...]
CgroupPath
ID       AttachType      AttachFlags     Name
/sys/fs/cgroup
4263     ingress         multi
4262     egress          multi
3007     sock_ops                        bpf_sockmap
3027     connect4
3022     connect6
3029     post_bind4
3024     post_bind6
3030     sendmsg4
3025     sendmsg6
3031     recvmsg4
3026     recvmsg6
3028     getpeername4
3023     getpeername6
/sys/fs/cgroup/kubernetes.slice
    4217     ingress         multi
    4216     egress          multi
[...snip...]
```

### LINKED ISSUE #15769: socket-lb is broken on minikube in Docker mode
When running minikube in the [Docker mode](https://minikube.sigs.k8s.io/docs/drivers/docker/) (aka k8s docker-in-docker), ClusterIP services cannot be reached with socket-lb enabled (aka host-reachable svc; enabled by default on newer kernels due to the `--kube-proxy-replacement` defaulting to probe). This is due to the same reason as documented in https://github.com/cilium/cilium/pull/14951.

- [x] In the GSG minikube disable socket-lb or ask users to chose another minikube mode (release blocker).
- [ ] Fix socket-lb for minikube in the Docker mode (requires host to run in cgroup v2).

### LINKED ISSUE #16078: Kind with socket-lb doesn't work in dev VM + update kind docs
Context : https://github.com/cilium/cilium/pull/15999#issuecomment-836254349 and https://github.com/cilium/cilium/pull/15999#issuecomment-837747885.

The instructions given in the Kind getting started guide to enable kube-proxy-replacement need to be updated to accommodate different kernels/container runtimes.

### PR DESCRIPTION
**Pull request by aditighag**
This PR aims to revisit some of the assumptions made around cgroup hierarchies in Cilium in order to enable socket-lb in different environments.

## Context 

Cilium attaches `BPF_CGROUP_*` type programs to provide socket based load-balancing. The default cgroup root in the agent is set to a custom location (`/var/run/cilium/cgroupv2`), where the agent tries to mount cgroup filesystem. The cgroup root is then passed to `init.sh` in order to attach the `BPF_CGROUP_*` programs at relevant hook points. While we have some extended logic in place to accommodate environments like `kind`, the overall logic breaks in certain scenarios. While the following list is not an exhaustive list, it helps in identifying general patterns.

## Scenarios where current logic breaks

- Virtualized cgroup root in the cgroup namespace mode (#15137)
If container runtimes are run with cgroup v2, Cilium agent pod would be deployed in a separate cgroup namespace. For example, Docker container runtime with cgroupv2 support switched to [private](https://docs.docker.com/config/containers/runmetrics/#running-docker-on-cgroup-v2) cgroup namespace mode as the default. Due to [cgroup namespaces](https://man7.org/linux/man-pages/man7/cgroup_namespaces.7.html), the cgroup fs mounted by the Cilium pod points to a virtualized cgroup hierarchy instead of the host cgroup root. As a result, BPF programs are attached to the nested cgroup root, and socket-lb isn't effective for other pods. 
**Resolution:** 
Mount cgroup fs on the host from init containers. We need to specify cgroup as the [enterable namespace](https://man7.org/linux/man-pages/man1/nsenter.1.html) in the nsenter command. Cilium agent will auto mount cgroup2 fs on the underlying host if not already mounted. This requires mounting host's `/proc` inside an init container temporarily. As an alternative, users can disable auto mount, and specify a mount point on the host where cgroup2 fs is already mounted. Cgroup2 fs mount point is platform dependent. Hence, we introduce a new helm option for the host cgroup2 fs mount point. See this note in [cgroup man page](https://man7.org/linux/man-pages/man7/cgroups.7.html)  -
Note that on many modern systems, systemd(1) automatically mounts
the cgroup2 filesystem at /sys/fs/cgroup/unified during the boot
process.

- Commit 866969e3 hard-coded `kubelet` string which may not work in some platforms. Depending on the value of kubelet config `--cgroup-root`, this string may or may not be present. Moreover, the logic to get cgroup root is specific to `kind` environments only so that it won't take effect for minikube clusters.
**Resolution:** 
The kind cgroup root detection logic can be removed as kind nodes and cilium agent pod are deployed in the same cgroup ns (if they don't, the above init container fix should be sufficient).

- Deploying a kind cluster alongside "other" BPF cgroup programs (#16078)
I ran into this issue while deploying a kind cluster on the dev VM. Cilium pod inside the kind cluster fails to come up with this warning message `failed to attach program`, and is stuck in a "CrashLoopback" state. We can have `cilium/ebpf` loader print better error messages/hints in such cases (I'll file an issue). 
I traced the error return code `255` (aka operation not permitted) from to this check [1] in the kernel source that disallows attach in the presence of programs (no override/multi) in the parent cgroup. After I removed the BPF programs attached in the dev VM cgroup root, I was able to create a kind cluster with socket-lb successfully.
[1] https://elixir.bootlin.com/linux/latest/source/kernel/bpf/cgroup.c#L457
**Resolution:** 
We document this case along with potential steps to resolve the issue. 

## Testing
Tested the changes on kind, GKE and bare metal k8s cluster by verifying that BPF programs are correctly attached, and socket-lb works as expected.

Deferred to follow-ups - 
 - Move BPF fs to an init container in the cilium ds
 - Remove the agent code that mounts cgroup v2 fs if not mounted : This is done in order to not break installation with cilium cli. Cilium CLI crafts its own DS, and doesn't use the OSS DS. Once we've released a new version of the CLI (https://github.com/cilium/cilium-cli/issues/256) with similar fixes as this PR, we can safely remove this.
 - CI/dev env #16528
 - Extend bugtool to collect output of attached cgroup programs

Fixes: #16078 
Fixes: #15769 
Fixes: 866969e3e43931c5d45b9b1a4e601f5bdf7895d4
Fixes: https://github.com/cilium/cilium/issues/15137
(Reported-by : @kkourt) 

**Release note**
```release-note
Fixes connectivity issues when kube-proxy replacement is enabled, caused by 
ineffective socket based load balancing (aka host reachable services) in the private 
cgroup namespace mode of container runtimes (e.g., docker cgroupv2 configuration). 
```

### CODE REVIEW

File: pkg/cgroups/cgroups.go [hunk 1]
```diff
@@ -92,8 +92,15 @@ func getCgroupRootForKind() (string, error) {
...
+		// line := "0::/system.slice/docker-$(SOME_NODE_ID).scope/kubelet/kubepods/burstable/pod-$(SOME_POD_ID)"
+		// line := "0::/kubelet/kubepods/burstable/pod95f45c87-c016-4b1a-9692-73ae901ea461/de0c46065bb736b5e0b8b85e8fec48b3cdee83351418552e9af300fd64ed4cbe"
+		// line := "0::/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod6745a7f5_63fd_46ff_8ce6_e312ac764642.slice/docker-0c2c12c9762dbe9f3e5c3bc43224347b828d19bd1834ed6a6d87fbd3d7bbb4e4.scope"
+		//
+		// Why kubepods or kubepods.slice?
+		// cgroupfs vs systemd cgroup driver -- Reference : https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/cgroup_manager_linux.go#L86
 		if strings.HasPrefix(line, "0::") { // cgroup v2 starts with "0::"
-			re := regexp.MustCompile(`^.*kubelet`)
+			re := regexp.MustCompile(`^.*(kubepods|kubepods.slice)/`)
 			p := path.Join(cgroupRoot, strings.Split(line, "::")[1])
```
Comment (kkourt) [inline pkg/cgroups/cgroups.go:104]: Thanks for the patch and digging into kubelet code! :)

How about we leave detection logic outside of the cilium agent, and just pass a proper argument to `--cgroup-root` in the agent? We can even pass two options, one for the root and one for where to attach the bpf programs, if we care about this distinction. We already had a special case for Kind, now we are going to add another one, and I think we should keep this complexity out of the agent.

**Review by kkourt — COMMENTED** [review]
Thanks for the patch!

The patch at its current state does not seem to work for me [1]. it's probably because cilium tries to mount in `/var/run/cilium` and it uses this directory (which is not the global one). Passing a `--cgroup-root` also does not seem to work because then the detection will not run. 

I'm confident that we can get the patch to work, but I would like to propose to  leave the detection logic outside of the cilium agent, and just pass a proper argument with --cgroup-root. We can even pass two options, one for the root and one for where to attach the bpf programs, if we care about this distinction. We already had a special case for Kind, now we are going to add another one, and I think we should keep this complexity out of the agent.

[1] This is the logs:

```
level=info msg="Mounted cgroupv2 filesystem at /var/run/cilium/cgroupv2" subsys=cgroups
level=warning msg="Failed to determine cgroup v2 hierarchy for Kind node. Socket-based LB (--enable-host-reachable-services) will not work." error="cannot find \"kubelet\" in cgroup v2 path: \"/var/run/cilium/cgroupv2\"" subsys=cgroups
```

**Comment by brb** [comment]
> Cilium only needs to be able to attach the BPF cgroup programs to a cgroup root that's common for all pods (and not necessarily to the host cgroup root).

Unfortunately we need to include host itself, as otherwise an application running on a host won't be able to access a ClusterIP service via bpf_sock. So, finding a common root for all pods won't work.

**Comment by aditighag** [comment]
> > Cilium only needs to be able to attach the BPF cgroup programs to a cgroup root that's common for all pods (and not necessarily to the host cgroup root).
> 
> Unfortunately we need to include host itself, as otherwise an application running on a host won't be able to access a ClusterIP service via bpf_sock. So, finding a common root for all pods won't work.

Yeah, it was at the back of my mind, but I wasn't really sure how it fits into the 2nd scenario above (Virtualized cgroup root). 🤔  I also would like to keep the detection logic to only the specific cases that I've called out above, and leave out the default as-is. 

@borkmann Do you have any explanation for the https://github.com/cilium/cilium/issues/15137 like environments where (cgroup root as seen by Cilium) != (host cgroup root)? We weren't quite able to figure that out in the slack thread.

**Comment by aditighag** [comment]
>Do you have any explanation for the #15137 like environments where (cgroup root as seen by Cilium) != (host cgroup root)because of cgroup namespaces? 

Ah! I wonder if this unlocks the mystery of the 2nd scenario - https://docs.docker.com/config/containers/runmetrics/#running-docker-on-cgroup-v2.

>Note that the cgroup v2 mode behaves slightly different from the cgroup v1 mode:
The default cgroup driver (dockerd --exec-opt native.cgroupdriver) is “systemd” on v2, “cgroupfs” on v1.
**The default cgroup namespace mode (docker run --cgroupns) is “private” on v2, “host” on v1.**
The docker run flags --oom-kill-disable and --kernel-memory are discarded on v2.

>--cgroupns | &nbsp; | API 1.41+Cgroup namespace to use (host\|private) 'host': Run the container in the Docker host's cgroup namespace 'private': Run the container in its own private cgroup namespace '': Use the cgroup namespace as configured by the default-cgroupns-mode option on the daemon (default)

**Comment by brb** [comment]
>  wonder if this unlocks the mystery of the 2nd scenario

@aditighag Aha, good find! I'm using Docker with the systemd cgroup driver (=cgroup v2), and I have completely disabled cgroupv1 on my host.

```
> docker run --cgroupns=host --name foobar --privileged -td alpine sleep 3600
cd33c0d2dfa48d976100a1fd7ceffa0d5588148f65b58ec5b2904c6ad8c3d37b
> docker exec -ti foobar /bin/sh
/ # mkdir /foo
/ # mount -t cgroup2 none /foo
/ # cd /foo/
/foo # cat cgroup.procs  | wc -l
153

> docker run --cgroupns=private --name foobar --privileged -td alpine sleep 3600
4a834a698271c9b1d9284e26a64873f0ca2203d73837aae205a04cbb5562fa51
> docker exec -ti foobar /bin/sh
/ # mkdir /foo
/ # mount -t cgroup2 none /foo
/ # cd /foo/
/foo # cat cgroup.procs  | wc -l
4
```

**Comment by aditighag** [comment]
Discussed the overall issue in the sig-datapath meeting (05/27), the suggestion was to [mount](https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/templates/cilium-nodeinit-daemonset.yaml#L142) the host cgroupv2 fs (prior to cilium agent running) from the init script. This is similar to how we mount the BPF fs.

**Comment by brb** [comment]
Some relevant examples:
```
> cat /proc/$(docker inspect kind-control-plane -f '{{.State.Pid}}')/cgroup
0::/system.slice/docker-8b5a44de9a72711ff1d0ad827a8612ff87e7c06acd81b60c31d690973b0ac392.scope/init.scope

> sudo cat /proc/$(pidof cilium-agent)/cgroup
0::/system.slice/docker-8b5a44de9a72711ff1d0ad827a8612ff87e7c06acd81b60c31d690973b0ac392.scope/kubelet/kubepods/burstable/podaf2cded2-e493-43e4-9199-dc870ac556a5/ca7fb7b008460fb77187247f772afbe9079674692513b14eaecfdaf327562a5a

> docker exec -ti kind-control-plane /bin/bash
root@kind-control-plane:/# cat /proc/self/cgroup
0::/init.scope

root@kind-control-plane:/# cat /proc/$(pidof cilium-agent)/cgroup
0::/kubelet/kubepods/burstable/podaf2cded2-e493-43e4-9199-dc870ac556a5/ca7fb7b008460fb77187247f772afbe9079674692513b14eaecfdaf327562a5a

> ks exec -ti cilium-x8c7m /bin/bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Defaulted container "cilium-agent" out of: cilium-agent, wait-for-node-init (init), clean-cilium-state (init)
root@kind-control-plane:/home/cilium# cat /proc/self/cgroup
0::/kubelet/kubepods/burstable/podaf2cded2-e493-43e4-9199-dc870ac556a5/ca7fb7b008460fb77187247f772afbe9079674692513b14eaecfdaf327562a5a
```

As you can see, the `kind-control-plane` Docker container and the cilium-agent pod running in it has a different cgroup parent, so mounting the cgroupfs from node-init won't work in the namespaced cgroup mode.

**Comment by aditighag** [comment]
@brb I don't follow your comment. I mounted cgroup fs as part of an init container, disabled kind detection logic, and socket lb worked fine. See details about cgroup paths - https://github.com/cilium/cilium/issues/16078#issuecomment-843810317. 

Can you elaborate more?

**Comment by brb** [comment]
> The cgroup hierarchies are relative to the top level cgroup root. As long as we attach the BPF programs at every kind node's cgroup root, it should work, no?

With cgroup namespaces on, the node-init container will mount `/system.slice/docker-foobar.scope/init.scope` as the cgroup root, while cilium-agent (or any other pod) will run in the `/system.slice/docker-foobar.scope/kubelet/kubepods/burstable/pod-foo/bar` cgroup. The bpf_sock will be attached to `/system.slice/docker-foobar.scope/init.scope` which will render them useless for pods, as the common ancestor is `/system.slice/docker-foobar.scope/` which doesn't have bpf_sock attached.

With cgroup namespaces off, the node-init container will mount the host's cgroup root. So we still would need to find an appropriate hierarchy when running on Kind for each cilium-agent.

**Comment by brb** [comment]
I think you can ignore what I wrote above, as it is no longer relevant. The latest findings are that even with cgroup NS on, on Kind we gonna run the cilium-agent pod in the same cgroup NS as the node container. Meaning that if we mount cgroupfs from the node-init and then propagate the mount via DaemonSet into the cilium-agent pod, then cilium-agent will attach the bpf_sock to the right cgroup root :tada: 

Next step is to check in what cgroup the node-init is running.

**Comment by brb** [comment]
> Next step is to check in what cgroup NS the node-init is running.

I've tried running the following Pod which should have the same privileges and configuration as the node-init:
```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    imagePullPolicy: Always
    name: busybox
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
    securityContext:
      privileged: true
  hostPID: true
  hostNetwork: true
```
Unfortunately, it's running in a different cgroup NS than the host :disappointed: 
```
> sudo ls -al /proc/$(pidof sleep)/ns/cgroup
lrwxrwxrwx 1 root root 0 May 28 18:29 /proc/837276/ns/cgroup -> 'cgroup:[4026533221]'
> sudo ls -al /proc/self/ns/cgroup
lrwxrwxrwx 1 root root 0 May 28 18:38 /proc/self/ns/cgroup -> 'cgroup:[4026531835]'
```

**Comment by aditighag** [comment]
> Unfortunately, it's running in a different cgroup NS than the host 😞

That's expected since you are only running in the network and pid namespaces of the host. 

In the [node-init container](https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/templates/cilium-nodeinit-daemonset.yaml#L132), we use `nsenter` to enter in the host namespace. I'll push the changes shortly. However, I noticed that the node-int container is run only when the `nodeinit` config option is enabled. That's not the case with the cilium-cli [logic](https://github.com/cilium/cilium-cli/blob/master/install/install.go#L690) though. Planning to bring this up in the community meeting to get more context.

**Comment by brb** [comment]
> we use nsenter to enter in the host namespace

But that's only for net and mount ns? I think the nodeinit will still run in a container's cgroup ns.

**Comment by aditighag** [comment]
We need to specify `cgroup` as the [enterable namespace](https://man7.org/linux/man-pages/man1/nsenter.1.html) in the `nsenter` command. I tried this in the dev VM (didn't want to mess up the `/sys/fs/cgroup` so I used a test dir) - 

```
vagrant@k8s1:/sys/fs/cgroup$ cd /var/run/cilium/test-cgroupv2/
vagrant@k8s1:/var/run/cilium/test-cgroupv2$ ls
root@k8s1:/home/cilium# nsenter -t 1 -m -C -- mount -t cgroup2 none /var/run/cilium/test-cgroupv2
$ cat /sys/fs/cgroup/cgroup.procs  | wc -l
112
vagrant@k8s1:/var/run/cilium/test-cgroupv2$ cat cgroup.procs | wc -l
112
```

We can confirm that node-init can run in the same cgroup ns as the host (with `hostPID` set to true) - 

```
root@k8s1:/home/cilium# nsenter -t 1 -C -- sleep 5000 &
[1] 12108
vagrant@k8s1:~/go/src/github.com/cilium/cilium$ sudo ls -al /proc/12108/ns/cgroup
lrwxrwxrwx 1 root root 0 Jun  1 05:06 /proc/12108/ns/cgroup -> 'cgroup:[4026531835]'
vagrant@k8s1:~/go/src/github.com/cilium/cilium$ sudo ls -al /proc/self/ns/cgroup
lrwxrwxrwx 1 root root 0 Jun  1 05:06 /proc/self/ns/cgroup -> 'cgroup:[4026531835]'
```

**Comment by aditighag** [comment]
Documentation changes are underway.

**Comment by aditighag** [comment]
test-me-please

File: install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml [hunk 2]
```diff
@@ -370,6 +372,16 @@ spec:
 {{- end }}
       hostNetwork: true
       initContainers:
+        {{/* Required to mount cgroup v2 filesystem on the underlying Kubernetes node.*/}}
```
Comment (qmonnet) [inline install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml]: If using a template comment, please [add spaces](https://helm.sh/docs/chart_best_practices/templates/#formatting-templates) after `{{` and before `}}`.
```suggestion
      {{ /* Required to mount cgroup v2 filesystem on the underlying Kubernetes node */ }}
```

But should this just be a [YAML comment instead](https://helm.sh/docs/chart_best_practices/templates/#comments-yaml-comments-vs-template-comments)? It doesn't document something specific to the template?

File: install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml [hunk 3]
```diff
@@ -427,6 +439,10 @@ spec:
 {{- /* Required for wait-bpf-mount to work */}}
           mountPropagation: HostToContainer
 {{- end }}
+{{/*Required to mount cgroup filesystem from the host to cilium agent pod*/}}
```
Comment (qmonnet) [inline install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml]: Same here.

File: Documentation/gettingstarted/kind.rst [hunk 4]
```diff
@@ -81,6 +81,24 @@ and no longer routing api-server requests to the current ``kind-control-plane``
...
+Check if Cilium agent pods are crashing with following logs. This may indicate
+that you are deploying a kind cluster in an environment where Cilium is already
+running (for example, in the Cilium development VM). This can also happen if you
+have other overlapping BPF ``cgroup`` type programs attached to the parent ``cgroup``
+hierarchy of the kind container nodes. In such cases, either tear down Cilium, or manually
+detach the overlapping BPF ``cgroup`` programs running in the parent ``cgroup`` hierarchy
+by following the `bpftool documentation <https://manpages.ubuntu.com/manpages/focal/man8/bpftool-cgroup.8.html>`_.
+For more information, see the `Pull Request <https://github.com/cilium/cilium/pull/16259>`__.
+
+.. parsed-literal::
```
Comment (qmonnet) [inline Documentation/gettingstarted/kind.rst]:
```suggestion
::
```

Nothing to be parsed in this literal block.

File: Documentation/gettingstarted/kubeproxy-free.rst [hunk 5]
```diff
@@ -1205,6 +1205,43 @@ As per `k8s Service <https://kubernetes.io/docs/concepts/services-networking/ser
...
+check if the programs are attached to the host ``cgroup root``. The default ``cgroup``
+root is set to ``/var/run/cilium/cgroupv2``. Run the following commands from a
+Cilium agent pod as well as the underlying kubernetes node where the pod is running.
+If the container runtime in your cluster is running in the cgroup namespace mode,
+Cilium agent pod can attach BPF ``cgroup`` programs to the ``virtualized cgroup root``.
+In such cases, Cilium kube-proxy replacement based load-balancing may not be
+effective leading to connectivity issues.
+For more information, ensure that you have the fix `Pull Request <https://github.com/cilium/cilium/pull/16259>`__.
+
+.. parsed-literal::
```
Comment (qmonnet) [inline Documentation/gettingstarted/kubeproxy-free.rst]:
```suggestion
.. code-block:: shell-session
```

**Review by qmonnet — CHANGES_REQUESTED** [review]
PR looks good to me, but I have a few nits on formatting.

**Comment by aditighag** [comment]
test-me-please

**Review by qmonnet — APPROVED** [review]
All good from my side, thank you!

File: install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml [hunk 6]
```diff
@@ -458,6 +479,16 @@ spec:
           type: DirectoryOrCreate
         name: bpf-maps
 {{- end }}
+      # To mount cgroup filesystem on the host
+      - hostPath:
+          path: /proc
+          type: DirectoryOrCreate
+        name: host-proc
```
Comment (aanm) [inline install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml]: We shouldn't mount host's `/proc` into Cilium's DaemonSet.

File: install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml [hunk 7]
```diff
@@ -370,6 +374,19 @@ spec:
...
+          - name: CGROUP_ROOT
+            value: {{ .Values.cgroupRoot }}
+        command: ['nsenter', '--cgroup=/hostproc/1/ns/cgroup', '--mount=/hostproc/1/ns/mnt', "--",
+                  'sh', '-c',  'mount | grep "$CGROUP_ROOT type cgroup2" || { echo "Mounting cgroup filesystem..."; mount -t cgroup2 none $CGROUP_ROOT; }']
+        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}{{ if .Values.image.useDigest }}@{{ .Values.image.digest }}{{ end }}"
+        volumeMounts:
+          - mountPath: /hostproc
+            name: host-proc
+        securityContext:
+          privileged: true
```
Comment (aanm) [inline install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml]: This is a really nasty hack.

**Review by aanm — CHANGES_REQUESTED** [review]
Did you check an alternative to the hack using [Bidirectional](https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation) mount propagation as proposed in the weekly meeting?

File: install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml (hunk 7 above)
Comment (brb) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml]: IMHO saying that this is _a really nasty hack_ doesn't provide much helpful information. Mind elaborating instead?

File: install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml (hunk 6 above)
Comment (brb) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml]: A bit similar as above, this is missing _why_.

File: install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml (hunk 7 above)
Comment (aditighag) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml]: >Bidirectional mount propagation as proposed in the weekly meeting?

@aanm Can you explain how the propagation mount will solve the cgroup namespace problem? Also, cgroup v2 fs is not guaranteed to be mounted on the host at `/sys/fs/cgroup` path. 
Example on GKE - 
```
$ mount | grep cgroup2
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime)
```

Comment (kkourt) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml]: One thing to note is that if we know _where_ the cgroupv2 host fs is mounted in the host, the mount propagation allows us to expose the host cgroupfs inside the agent's container without having to expose /proc [1]. Couldn't we have a configurable helm variable for this location (default /sys/fs/cgroup/) that can be set to a proper value for each platform that deviates (e.g., GKE).

E.g., something like:

```
- hostPath:
       path: {{ .Values.hostCgroupFS }} # /sys/fs/cgroup by default
        type: DirectoryOrCreate
   name: cilium-cgroup
```

and:
```
- mountPath: /var/run/cilium/cgroupv2
   name: cilium-cgroup
```


[1] I've just tested this. I think the way it works is by  doing a bind mount inside the root fs of the container.

Comment (aditighag) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml]: I think this is may be a fair middle ground. Having said that, I may have a preference for mounting cgroupfs at a cilium specified custom path - 
As far as possible, we should try to keep the internal details as transparent to the end user as possible. It can be error prone to have too many knobs. See this note in the [cgroup manpage](https://man7.org/linux/man-pages/man7/cgroups.7.html) - 

>Note that on many modern systems, systemd(1) automatically mounts
       the cgroup2 filesystem at /sys/fs/cgroup/unified during the boot
       process.

So the cgroupfs mount location may differ across cgroup v1/v2, systemd or not, etc. The default` /sys/fs/cgroup` path for cgroupfs 2 doesn't necessarily cover a large number of environments.

**Comment by aditighag** [comment]
> 4.19 failure is related to nfs.mount, the issue is tracked - https://cilium.slack.com/archives/C7PE7V806/p1623352955165200.

Same for other tests that failed. I'll rebase my PR, and resume tests.

File: install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml (hunk 7 above)
Comment (aanm) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml]: > IMHO saying that this is _a really nasty hack_ doesn't provide much helpful information. Mind elaborating instead?

@brb As mentioned in the review description, bidirectional mounts offered by Kubernetes should help having the behavior that we want without having the mount the entire `/proc`, increasing attack surface, into Cilium's container.

Sure there are environments where the cgroup directory is not the default one but we can hard-code the value of `--cgroup-root` for the environments that we know of. We already have dedicated options for cloud providers so I don't see how much difference it would be having dedicated value for the `--cgroup-root` depending on the cloud provider. We can even mount `/sys/fs`, instead of `/sys/fs/bpf`, inside the cilium-agent container and we could detect if the cgroup is mounted in ` /sys/fs/cgroup/unified` or in ` /sys/fs/cgroup`.

For the more specific environments where users might change the cgroup directory intentionally then we just need to add documentation regarding this in the kube-proxy GSG.

Comment (aditighag) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml]: >without having the mount the entire /proc, increasing attack surface, into Cilium's container.

We are only mounting `/proc` inside the init container that's short-lived (not inside the agent container). Cilium CLI already [mounts](https://github.com/cilium/cilium-cli/blob/master/install/install.go#L685) `/proc` in order to mount `/sys/fs/bpf`.

Comment (aanm) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml]: > > without having the mount the entire /proc, increasing attack surface, into Cilium's container.
> 
> We are only mounting `/proc` inside the init container that's short-lived (not inside the agent container). Cilium CLI already [mounts](https://github.com/cilium/cilium-cli/blob/master/install/install.go#L685) `/proc` in order to mount `/sys/fs/bpf`.

Cilium CLI is still in beta stage, the reason it is mounting proc was to make it easier to deploy Cilium across all environments but that does not mean it's the safest way of mounting bpf fs. We should replace Cilium cli with bidirectional mounting instead of mounting `/proc` in Cilium repo.

Comment (brb) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml]: To reduce the attack surface, wouldn't it be enough to mount `/proc/1/ns/cgroup` and `/proc/1/ns/mnt` instead of `/proc`?

Comment (aditighag) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml]: Yeah, we could do selective `/proc/*` mounts.

Comment (aditighag) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml]: `/proc/1/ns/cgrou`p and `/proc/1/ns/cgroup` are symlinks. I've made the change to mount `/proc/1/ns` instead.

**Comment by aditighag** [comment]
test-me-please

**Comment by aditighag** [comment]
I've dropped the vagrant related changes to override kubelet cgroup drive to systemd for now. I've opened an issue (#16528) to tackle the overall changes.

**Comment by aditighag** [comment]
test-me-please

File: Documentation/gettingstarted/kubeproxy-free.rst [hunk 8]
```diff
@@ -1201,6 +1201,44 @@ As per `k8s Service <https://kubernetes.io/docs/concepts/services-networking/ser
 Cilium's eBPF kube-proxy replacement by default disallows access to a ClusterIP service from outside the cluster.
 This can be allowed by setting ``bpf.lbExternalClusterIP=true``.
 
+
+Troubleshooting
```
Comment (aditighag) [inline Documentation/gettingstarted/kubeproxy-free.rst:1220]: @brb I think we also need to add a note about incompatibility between cgroup v1 and v2 to the installation step in this guide?
Edit: Checked with Daniel offline, this won't be an issue when this PR is merged since we'll be attaching programs to the cgroup root. We already have a note in `kind` gsg.

**Comment by aditighag** [comment]
test-me-please

**Comment by aditighag** [comment]
I've fixed the helm-docs test failure locally. Will wait for reviews before pushing more updates.

File: install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml [hunk 9]
```diff
@@ -370,6 +374,21 @@ spec:
...
       hostNetwork: true
       initContainers:
+{{- if .Values.cgroupAutoMount.enabled }}
+      # Required to mount cgroup v2 filesystem on the underlying Kubernetes node
+      - name: mount-cgroup
+        env:
+          - name: CGROUP_ROOT
+            value: {{ .Values.cgroupRoot }}
+        command: ['nsenter', '--cgroup=/hostpid1ns/cgroup', '--mount=/hostpid1ns/mnt', "--",
+                  'sh', '-c',  'mount | grep "$CGROUP_ROOT type cgroup2" || { echo "Mounting cgroup filesystem..."; mount -t cgroup2 none $CGROUP_ROOT; }']
```
Comment (aanm) [inline install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml]: nit, can we have this in a multiline?

File: install/kubernetes/cilium/values.yaml [hunk 10]
```diff
@@ -1643,3 +1643,10 @@ clustermesh:
 externalWorkloads:
   # -- Enable support for external workloads, such as VMs (false by default).
   enabled: false
+
+# -- Configure cgroup root where cgroup v2 filesystem is mounted
+cgroupRoot: /run/cilium/cgroupv2
+
+# -- Enable auto mount of cgroup v2 filesystem
+cgroupAutoMount:
+  enabled: true
```
Comment (aanm) [inline install/kubernetes/cilium/values.yaml]: Why not have the options like:
```
cgroup:
  autoMount:
    enabled: true
  root: /run/cilium/cgroupv2
```

File: install/kubernetes/cilium/values.yaml [hunk 11]
```diff
@@ -1643,3 +1643,10 @@ clustermesh:
 externalWorkloads:
   # -- Enable support for external workloads, such as VMs (false by default).
   enabled: false
+
+# -- Configure cgroup root where cgroup v2 filesystem is mounted
+cgroupRoot: /run/cilium/cgroupv2
```
Comment (aanm) [inline install/kubernetes/cilium/values.yaml]: I don't understand this one. With the current version of the `master` branch, the cgroupv2 are already available in this directory. Why do we need to specify it as an helm flag?

File: install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml [hunk 12]
```diff
@@ -426,6 +445,12 @@ spec:
           name: bpf-maps
 {{- /* Required for wait-bpf-mount to work */}}
           mountPropagation: HostToContainer
+{{- end }}
+        # Required to mount cgroup filesystem from the host to cilium agent pod
+{{- if .Values.cgroupAutoMount }}
```
Comment (aanm) [inline install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml]: The comment should be inside the if statement

File: install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml [hunk 13]
```diff
@@ -457,6 +486,24 @@ spec:
           path: /sys/fs/bpf
           type: DirectoryOrCreate
         name: bpf-maps
+{{- end }}
+{{- if .Values.cgroupAutoMount.enabled }}
+      # To mount cgroup filesystem on the host
+      - hostPath:
+          path: /proc/1/ns
```
Comment (brb) [inline install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml:502]: Could we limit the mount scope even more? I.e. to mount only `/proc/1/ns/cgroup` and `/proc/1/ns/mnt`?

**Review by aanm — CHANGES_REQUESTED** [review]

File: install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml (hunk 13 above)
Comment (aditighag) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml:502]: Those are just symlinks.

File: install/kubernetes/cilium/values.yaml (hunk 11 above)
Comment (aditighag) [reply install/kubernetes/cilium/values.yaml]: This helm value corresponds to the Cilium agent config option (`cgroup-root`) that allows users to specify a different path than the default.

File: Documentation/helm-values.rst [hunk 14]
```diff
@@ -90,6 +90,18 @@
      - Seconds after which the completed job pod will be deleted
      - int
      - ``1800``
+   * - cgroup
+     - Configure cgroup related configuration
+     - object
+     - ``{"autoMount":{"enabled":true},"root":"/run/cilium/cgroupv2"}``
```
Comment (kkourt) [inline Documentation/helm-values.rst]: Is this a different option than `cgroup.root`? If yes, do we need both of them?

File: Documentation/helm-values.rst [hunk 15]
```diff
@@ -90,6 +90,18 @@
...
+   * - cgroup.autoMount.enabled
+     - Enable auto mount of cgroup v2 filesystem
+     - bool
+     - ``true``
+   * - cgroup.root
+     - Configure cgroup root where cgroup v2 filesystem is mounted
```
Comment (kkourt) [inline Documentation/helm-values.rst]: The above line seems a bit confusing to me. How about: "Location where the cgroup v2 filesystem is mounted inside the cilium agent container"?

File: install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml [hunk 16]
```diff
@@ -276,6 +276,10 @@ spec:
         - mountPath: /sys/fs/bpf
           name: bpf-maps
 {{- end }}
+{{- if not (contains "/run/cilium/cgroupv2" .Values.cgroup.root) }}
+        - mountPath: {{ .Values.cgroup.root }}
```
Comment (kkourt) [inline install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml]: If I'm reading this correctly, `cgroup.root` is used to refer to locations (mountpoints) that, depending on its value, are in the host or in the agent's container. I think that's confusing.

**Review by kkourt — COMMENTED** [review]
Thanks Aditi!

Maybe I'm missing something, but the helm options seem confusing to me.

IMHO, we should have two different configuration options:
* one configuration variable that points to the location of the cgroup dir on the host, to be used  when autoMount is disabled.
* one configuration variable for the cgroup root inside the container, which is what directory that the agent will use.

File: install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml (hunk 16 above)
Comment (aditighag) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml]: (I'm replying to @kkourt 's comment here so that we can have the discussion in a single thread.)

Chatted with Kornilios offline. Looks like there was some confusion around the PR.

If auto-mount is enabled, then cgroup2 fs will be mounted at `cgroupRoot` on both the host and the agent pod. Else,  cgroup2 fs mounted at `cgroupHostRoot` is mounted inside the agent pod at `cgroupRoot`. I can clarify this a bit further.

>one configuration variable that points to the location of the cgroup dir on the host, to be used when autoMount is disabled.

This is the `cgroupHostRoot` that the PR has introduced. 

>one configuration variable for the cgroup root inside the container, which is what directory that the agent will use.

If this config only points to the directory inside the agent pod, why do we need to expose that as an helm option to users?

Alternatively, we can drop the additional option `cgroupHostRoot`. We hand-waived over some of these details in the datapath meeting.

option 1
- cgroup.autoMount : Enable/disable
- cgroup.root : If `autoMount` is enabled, then agent will mount cgroup2 fs at that path. Else, it'll mount that directory on the host inside the agent pod. In both the cases, we allow users to override the path. However, we'll need to have different defaults in auto-mount enable (`/run/cilium/cgroupv2`) and disable (`/sys/fs/cgroup`) cases. 

option 2
- cgroup.autoMount : Enable/disable
If `autoMount` is enabled, then agent will mount cgroup2 fs at a custom (hard-coded) location `/run/cilium/cgroupv2`.  Users won't be able to override this. 
- cgroup.root : This will be used when users disable auto-mount, and agent will then mount host's `cgroup.root` inside the agent pod. The default will be `/sys/fs/cgroup`.

I think option 2 is simpler.

Comment (joestringer) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml]: > If this config only points to the directory inside the agent pod, why do we need to expose that as an helm option to users?

:heavy_plus_sign: 

Option 2 sounds simpler and more consistent to me. If `cgroup.autoMount=false`, would we mount `cgroup.root` to `/run/cilium/cgroupv2` inside the container?

Comment (kkourt) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml]: @aditighag, thanks for the clarification! Indeed I misunderstood the PR.

Both options are fine by me. The only comment I would make is that `cgroup.root` seems somewhat similar to the agent option `-cgroup-root` so I would suggest we use a different name to avoid confusion. `cgroup.hostRoot` maybe?

Comment (aditighag) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml]: > If cgroup.autoMount=false, would we mount cgroup.root to /run/cilium/cgroupv2 inside the container?

This is exactly why I introduced a new option (`cgroupHostRoot`) in the current commits. If we go with option 2, we'll need to have `/run/cilium/cgroupv2` hard-coded in the agent DS, or have the same mount path as the host. Unless folks have some other ideas?

Comment (joestringer) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml]: If you don't specify it anywhere, then the default agent value is `""` which it then replaces with `DefaultCgroupRoot = "/var/run/cilium/cgroupv2"`. That seems fine to me.

Comment (aditighag) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml]: I was referring to the agent daemonset yaml file changes when auto-mount is enabled. 
I'm getting conflicting comments on the PR. 😕 

Where do we want to mount cgroup2 fs inside the cilium agent pod when `auto.mount` is - 
- enabled
- disabled 

If it's going to be `/run/cilium/cgroupv2` in both the cases, then we can have the path hard-coded, and remove the `cgroup-root` agent configmap option. If we want it to be `/run/cilium/cgroupv2` in the 1st case, but same as the host cgroup root for the latter case, then don't we have the same confusion if we rename the current option to `cgroupHostRoot`? 

IMO, we are overly complicating this. Let's just call it `cgroupRoot`, and have it better documented.

Comment (joestringer) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml]: One thing that made it more complicated is it's the same actual directory in the cilium container:

```
# ls -lh /var/run
lrwxrwxrwx 1 root root 4 Apr 16 05:11 /var/run -> /run
```

I think we should stick with `/var/run/cilium/cgroupv2` so we're consistent with the defaults in the daemon, in case for whatever reason these directories diverge at some point in the future.

Then in the DaemonSet, if `cgroup.automount` is enabled, we do the nsenter trick to mount it to this path. If `cgroup.automount` is disabled, then we specify a cgroup hostPath under `volumes` as the configured argument `cgroup.root` or whatever we call it. Only in the latter case we need a `volumeMount` to mount the path to `/var/run/cilium/cgroupv2` (which will then be automatically used by the daemon defaults without having to specify it anywhere in configmap or DS commandline args).

I'm fine with `cgroup.root` or `cgroup.hostRoot` in the helm config, either way I agree that documenting that it's about the host path is the important piece. I don't think many users care how it looks inside the container.

Comment (joestringer) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml]: Oh, I think I glossed over some of the detail in the automount side which makes the above comment miss some of the nuance.

For automount I think the goal is to mount at a known Cilium path on the host, then mount that to the consistent internal path. I _think_ if `cgroup.automount=true` it's fine to automount the cgroupfs to either `/var/run/cilium/cgroupv2` or `cgroup.root` on the host, I don't know if makes a big difference.  Then in that case we also need to specify the `volumes` / `volumeMount`, based on wherever we decide the cgroup FS should be automounted. Maybe I'm finally coming around to why this is complicated :sweat_smile:

Comment (joestringer) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml]: ^^ Probably makes sense to have some default for `cgroup.root` and always use that as the host path, either that we try to mount cgroupfs there in the case that `cgroup.automount=true`, or we use that (expected pre-mounted) path to mount into the container in the case that `cgroup.automount=false`. Then we can decide whatever the default for `cgroup.root` should be.

**Comment by aditighag** [comment]
As discussed, I've simplified the helm options, and enhanced the documentation further.

**Comment by aditighag** [comment]
test-me-please

**Comment by aditighag** [comment]
test-me-please

File: Documentation/helm-values.rst [hunk 17]
```diff
@@ -90,6 +90,18 @@
...
+   * - cgroup
+     - Configure cgroup related configuration
+     - object
+     - ``{"autoMount":{"enabled":true},"root":"/run/cilium/cgroupv2"}``
+   * - cgroup.autoMount.enabled
+     - Enable auto mount of cgroup v2 filesystem. When cgroup.autoMount is enabled, cgroup v2 filesystem is mounted at cgroup.root path on the underlying host and inside the cilium agent pod. If users disable cgroup.autoMount, it's expected that users have mounted cgroup v2 filesystem at the specified cgroup.root, and it'll then be volume mounted inside the cilium agent pod at the same path.
+     - bool
+     - ``true``
+   * - cgroup.root
+     - Configure cgroup root where cgroup v2 filesystem is mounted
```
Comment (kkourt) [inline Documentation/helm-values.rst]:
```suggestion
     - Configure cgroup root where cgroup v2 filesystem is mounted on the host (see also: `cgroup.autoMount`)
```

**Review by kkourt — CHANGES_REQUESTED** [review]
As I mentioned elsewhere, I think the helm option `cgroup.root` is too close to the agent option `-cgroup-root`. @aditighag I believe you suggested `cgroup.hostRoot` somewhere. Can we go with that?

Thanks.

File: install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml (hunk 13 above)
Comment (brb) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml:502]: From namespaces(7):
>        Bind mounting (see mount(2)) one of the files in this directory
>       to somewhere else in the filesystem keeps the corresponding
>       namespace of the process specified by pid alive even if all
>       processes currently in the namespace terminate.
To my understanding, mounting only those files should work.

Comment (aditighag) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml:502]: @brb I'm not sure that's supposed to work. I'm unable to mount `/proc/1/ns/mnt`. It may be because of the circular dependency. This might be related- https://stackoverflow.com/questions/34783391/why-i-couldnt-use-mount-bind-proc-pid-ns-mnt-to-another-file-in-ubuntu

`  Warning  Failed     20s                kubelet            Error: failed to start container "mount-cgroup": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/proc/1/ns/mnt\\\" to rootfs \\\"/var/lib/docker/overlay2/7b5659481002373db731ac03d0563a9cad37be0027d77bf755a8332a32c080e4/merged\\\" at \\\"/var/lib/docker/overlay2/7b5659481002373db731ac03d0563a9cad37be0027d77bf755a8332a32c080e4/merged/hostpid1mntns\\\" caused \\\"invalid argument\\\"\"": unknown`

**Comment by aditighag** [comment]
@kkourt Sure, renamed the helm option. PTAL.

> As I mentioned elsewhere, I think the helm option `cgroup.root` is too close to the agent option `-cgroup-root`. @aditighag I believe you suggested `cgroup.hostRoot` somewhere. Can we go with that?
> 
> Thanks.

File: install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml (hunk 13 above)
Comment (aanm) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml:502]: @aditighag try changing the type from `DirectoryOrCreate` to `Directory`

File: install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml [hunk 18]
```diff
@@ -458,6 +487,16 @@ spec:
...
+      # To mount cgroup2 filesystem on the host
+      - hostPath:
+          path: /proc/1/ns
+          type: DirectoryOrCreate
+        name: host-proc-ns
+      # To keep state between restarts / upgrades for cgroup2 filesystem
+      - hostPath:
+          path: {{ .Values.cgroup.hostRoot}}
+          type: DirectoryOrCreate
+        name: cilium-cgroup
```
Comment (aanm) [inline install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml:510]: Is this really necessary? I thought the cgroup2 state would be kept even if it was not mounted in the host. I might be wrong but that was my impression.

File: install/kubernetes/cilium/values.yaml [hunk 19]
```diff
@@ -1643,3 +1643,8 @@ clustermesh:
 externalWorkloads:
   # -- Enable support for external workloads, such as VMs (false by default).
   enabled: false
+
+# -- Configure cgroup related configuration
+cgroup:
+  # -- Configure cgroup root where cgroup2 filesystem is mounted on the host (see also: `cgroup.autoMount`)
+  hostRoot: /run/cilium/cgroupv2
```
Comment (aanm) [inline install/kubernetes/cilium/values.yaml:1658]: shouldn't this be by default `/sys/fs/cgroup`? The comment is a little confusing. Looking at the helm chart (install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml line 281) it looks that this is used to define the path where cgroup-root is mounted inside the container.

edit since I was reviewing the PR per commit basis: It also seems that with `cgroup.autoMount=false` Cilium will not mount the cgroup v2 correctly under `/sys/fs/cgroup` as there is no reference of it anywhere.

File: Documentation/gettingstarted/kubeproxy-free.rst [hunk 20]
```diff
@@ -92,6 +92,15 @@ configuration.
         --set k8sServiceHost=REPLACE_WITH_API_SERVER_IP \\
         --set k8sServicePort=REPLACE_WITH_API_SERVER_PORT
 
+.. note::
+
+    Cilium will automatically mount cgroup v2 filesystem required to attach BPF
+    cgroup programs by default at the path ``run/cilium/cgroupv2``. In order to
```
Comment (aanm) [inline Documentation/gettingstarted/kubeproxy-free.rst]: `run`->`/run`

File: daemon/cmd/daemon_main.go [hunk 21]
```diff
@@ -1180,6 +1181,7 @@ func initEnv(cmd *cobra.Command) {
 	// useful if the daemon is being round inside a namespace and the
 	// BPF filesystem is mapped into the slave namespace.
 	bpf.CheckOrMountFS(option.Config.BPFRoot, k8s.IsEnabled())
+	cgroups.CheckOrMountCgrpFS(option.Config.CGroupRoot)
```
Comment (aanm) [inline daemon/cmd/daemon_main.go:1184]: any reason why can't this be on line 584 of daemon/cmd/daemon.go?

File: pkg/cgroups/cgroups.go [hunk 22]
```diff
@@ -131,17 +56,6 @@ func CheckOrMountCgrpFS(mapRoot string, runsOnKind bool) {
 		// Failed cgroup2 mount is not a fatal error, sockmap will be disabled however
 		if err == nil {
```
Comment (aanm) [inline pkg/cgroups/cgroups.go:57]: Can you add a log message for the error condition? :pray:

**Review by aanm — CHANGES_REQUESTED** [review]

File: pkg/cgroups/cgroups.go (hunk 22 above)
Comment (aditighag) [reply pkg/cgroups/cgroups.go:57]: This is fixed in the PR - https://github.com/cilium/cilium/pull/15999.

File: install/kubernetes/cilium/values.yaml (hunk 19 above)
Comment (aditighag) [reply install/kubernetes/cilium/values.yaml:1658]: See this thread - https://github.com/cilium/cilium/pull/16259#discussion_r656486823.  😄 

@kkourt suggested to rename the option. This makes sense since it is user-facing. Users shouldn't care where we mount the fs inside the agent pod.

>It also seems that with cgroup.autoMount=false Cilium will not mount the cgroup v2 correctly under /sys/fs/cgroup

See this comment - 

```
# If users disable `autoMount`, it's expected that users have mounted
# cgroup2 filesystem at the specified `cgroup.hostRoot` 
```

File: daemon/cmd/daemon_main.go (hunk 21 above)
Comment (aditighag) [reply daemon/cmd/daemon_main.go:1184]: This is part of a revert commit.

File: install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml (hunk 13 above)
Comment (aditighag) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml:502]: @aanm I'm not sure which line you were pointing to. Anyway I meant to fix the type for `/proc/1/ns mount`. The DS shouldn't try to create that directory. 😅 ✅

File: install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml (hunk 18 above)
Comment (aditighag) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml:510]: >cgroup2 state would be kept even if it was not mounted in the host

Not sure I understand. Where would the state be kept?

**Review by aditighag — COMMENTED** [review]
@aanm I've addressed some of your comments. Replied inline to other comments. Thanks!

File: Documentation/helm-values.rst [hunk 23]
```diff
@@ -90,6 +90,14 @@
      - Seconds after which the completed job pod will be deleted
      - int
      - ``1800``
+   * - cgroup
+     - Configure cgroup related configuration
+     - object
+     - ``{"hostRoot":"/run/cilium/cgroupv2"}``
+   * - cgroup.hostRoot
+     - Configure cgroup root where cgroup2 filesystem is mounted on the host (see also: `cgroup.autoMount`)
```
Comment (kkourt) [inline Documentation/helm-values.rst]: nit: if going patch-by-patch, the:

> (see also: `cgroup.autoMount`)

is added in a prior patch than the autoMount option.

Not blocking on my side.

**Review by kkourt — APPROVED** [review]
LGTM, thanks!

File: install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml (hunk 13 above)
Comment (aanm) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml:502]: >Could we limit the mount scope even more? I.e. to mount only /proc/1/ns/cgroup and /proc/1/ns/mnt?

To limiting the scope as Martynas mentioned above I would suggest trying to set `type: File` as it was previously set with `DirectoryOrCreate`.

File: install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml (hunk 18 above)
Comment (aanm) [reply install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml:510]: oh this is the hostRoot ok, nevermind.

File: install/kubernetes/cilium/values.yaml (hunk 19 above)
Comment (aanm) [reply install/kubernetes/cilium/values.yaml:1658]: > See this thread - [#16259 (comment)](https://github.com/cilium/cilium/pull/16259#discussion_r656486823). 
> 
> @kkourt suggested to rename the option. This makes sense since it is user-facing. Users shouldn't care where we mount the fs inside the agent pod.
> 
> > It also seems that with cgroup.autoMount=false Cilium will not mount the cgroup v2 correctly under /sys/fs/cgroup
> 
> See this comment -
> 
> ```
> # If users disable `autoMount`, it's expected that users have mounted
> # cgroup2 filesystem at the specified `cgroup.hostRoot` 
> ```

But why isn't the default `/sys/fs/cgroup` and `/sys/fs/cgroup/unified` for gke? This would work as fine regardless if `autoMount` is true or false. However if we have `/run/cilium/cgroupv2` set as default, this will not work by default for users running with `autoMount` as false, which we can avoid it by setting the default to `/sys/fs/cgroup` for `/sys/fs/cgroup/unified` for gke.

**Review by aanm — CHANGES_REQUESTED** [review]

File: install/kubernetes/cilium/values.yaml (hunk 19 above)
Comment (joestringer) [reply install/kubernetes/cilium/values.yaml:1658]: Defaulting to mounting the cgroupfs to `/sys/fs/cgroup` on the host sounds fine to me, I doubt that there's much problem there - it's the canonical path so it's not like we'd get some other filesystem mounted there. If it's already mounted, we can detect that and avoid mounting it. If it's not yet mounted, then I don't think anyone would complain if we mounted it. Every mount of the cgroupv2 FS points to the same underlying cgroupfs implementation so there's nothing special about us mounting it there vs any other software mounting it there, so from that reasoning I don't think there's a compatibility issue or anything.

Comment (aanm) [reply install/kubernetes/cilium/values.yaml:1658]: @aditighag, while I was discussing this topic with Joe we are a little bit confused about one thing: We thought the whole point of `autoMount=true` was to auto detect the cgroup root mount point, so why are we using `/run/cilium/cgroupv2` in `autoMount=true`? Or is a misunderstanding from our part?

Comment (aditighag) [reply install/kubernetes/cilium/values.yaml:1658]: @joestringer To be clear, I haven't changed the default path. You explained the reasoning in the sig-datapath meeting why we chose to mount cgroup2 fs at a custom location. 

@aanm It's auto mount, where the init-container will automatically **mount** cgroup2 fs.

Comment (aanm) [reply install/kubernetes/cilium/values.yaml:1658]: >@aanm It's auto mount, where the daemonset will automatically mount cgroup2 fs.

oh and that is because the init container will mount the cgroup2 fs in that directory and then cilium container can use it?

Comment (joestringer) [reply install/kubernetes/cilium/values.yaml:1658]: Evidently past me was thinking about this more deeply than current me :sweat_smile: (Looking at the notes, I don't think we captured this nuance) . I think I recall the reasoning, it was something along the lines of, if the host isn't already mounting cgroupfs by itself then maybe /sys/fs/cgroup doesn't exist as a directory to mount to (because otherwise the OS would mount the FS there right?) and then maybe it's not our role to create that directory. Then it's better to just mount on `/var/run/cilium/cgroupv2` where we know that Cilium controls the directory and no-one should interfere with it.

OK, then I think this default is fine as-is.

File: Documentation/gettingstarted/kubeproxy-free.rst [hunk 24]
```diff
@@ -92,6 +92,15 @@ configuration.
...
         --set k8sServicePort=REPLACE_WITH_API_SERVER_PORT
 
+.. note::
+
+    Cilium will automatically mount cgroup v2 filesystem required to attach BPF
+    cgroup programs by default at the path ``/run/cilium/cgroupv2``. In order to
+    do that, it needs to mount the host ``/proc`` inside an init container
+    launched by the daemonset temporarily. If you need to disable the auto-mount,
+    specify ``--set cgroup.autoMount.enabled=false``, and set the host mount point
+    where cgroup v2 filesystem is already mounted by using ``--set cgroup.hostRoot``.
```
Comment (aanm) [inline Documentation/gettingstarted/kubeproxy-free.rst:102]: Can we have an example on how to mount cgroup2 for this case?

**Review by aanm — CHANGES_REQUESTED** [review]

**Comment by aditighag** [comment]
test-me-please

**Review by aanm — APPROVED** [review]
:tada:

**Comment by aditighag** [comment]
ci-gke

**Comment by aditighag** [comment]
All the relevant tests for this PR have passed. The PR primarily changes the agent daemonset, and the only relevant tests are net-next (kpr enabled).

k8s-1.21-kernel-4.9 failures are not related - 

```
Expected command: kubectl exec -n default app2-58757b7dd5-nrwln -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 --retry 5 http://vagrant-cache.ci.cilium.io -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Err: exit status 28
Stdout:
 	 time-> DNS: '0.000019()', Connect: '0.000000',Transfer '0.000000', total '5.002315'
Stderr:
 	 command terminated with exit code 28
```

ci-awscni (not required) are partially failing but not related as well. Additionally, ci-* tests use their own daemonsets so the PR changes are not picked up. I've filed a separate issue for the CLI changes - https://github.com/cilium/cilium-cli/issues/256.

```
Error: Connectivity test failed: 1 tests failed
📋 Test Report
❌ 1/9 tests failed (1/81 actions), 0 warnings, 0 tests skipped, 0 scenarios skipped:
Test [no-policies]:
  ❌ no-policies/pod-to-remote-nodeport/curl-2: cilium-test/client-6998dc6449-lpdzk (192.168.144.24) -> cilium-test/echo-other-node (echo-other-node:8080)
Error: Process completed with exit code 1.
```

**Comment by joestringer** [comment]
All of the CI 3.0 jobs are failing, would you mind triaging those before we merge this?

For context we just merged in the usage of cilium-cli v0.8.2; I don't know if that's related to these failures yet or not.

**Comment by aditighag** [comment]
@joestringer Not sure if you saw my comment - https://github.com/cilium/cilium/pull/16259#issuecomment-868681380. I did triage all of them, but I didn't call them all out because the failures weren't related.

**Comment by joestringer** [comment]
Sorry, yeah I did a very brief scan over the comment and thought it was looking only at Jenkins. More :coffee: required I guess.

As far as the CI 3.0 jobs, we've merged https://github.com/cilium/cilium/pull/16650 now so presumably all of the issues should be fixed right? For the overall project I'm hoping we can get to a stricter process of addressing CI 3.0 issues in this tree as well as cilium-cli, so I'd be very interested to find out, if you rebase against master do you still see CI 3.0 issues?

For jenkins jobs, it'd be good to at least find & reference or file issues for each of the failures so we're tracking them and can coordinate with other PRs. I was looking at some failures yesterday also on k8s1.21/kernel 4.9 and I'm not sure quite how stable that job is overall right now but I have a sense that it's maybe not super stable. If that's the case, I'd like to see what we can do to slowly make progress on that.

(None of the above is relevant to the PR changes themselves, so from that sense I'm OK with this code and merging it. At the same time I'd like to apply a bit of pressure to ensure that we as a core team are all thinking about how do we improve the status quo on CI flakiness, even if it's just incremental progress on individual PRs, stuff like tracking the common issues and picking at least one thing to drive forward).

**Comment by aditighag** [comment]
I've filed - https://github.com/cilium/cilium/issues/16659.

> k8s-1.21-kernel-4.9 failures are not related -
> 
> ```
> Expected command: kubectl exec -n default app2-58757b7dd5-nrwln -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 --retry 5 http://vagrant-cache.ci.cilium.io -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
> To succeed, but it failed:
> Exitcode: 28 
> Err: exit status 28
> Stdout:
>  	 time-> DNS: '0.000019()', Connect: '0.000000',Transfer '0.000000', total '5.002315'
> Stderr:
>  	 command terminated with exit code 28
> ```

File: pkg/defaults/defaults.go [hunk 25]
```diff
@@ -98,7 +98,7 @@ const (
 	DefaultMapRoot = "/sys/fs/bpf"
 
 	// DefaultCgroupRoot is the default path where cilium cgroup2 should be mounted
-	DefaultCgroupRoot = "/var/run/cilium/cgroupv2"
+	DefaultCgroupRoot = "/run/cilium/cgroupv2"
```
Comment (joestringer) [inline pkg/defaults/defaults.go:101]: Any time that we change default options, we have the potential to impact upgrade, and the consequences are not always immediately clear. Not sure if there was any discussion on this particular change, but I've thought it through a bit below.

In practice this should not have any impact, unless there's the unusual combination of:
* Cilium is _not_ run in a container.
* The underlying distribution does _not_ link `/var/run` to `/run`.

Maybe in the above case, upgrading Cilium to this version with a new default could leave an extra mount of the cgroupfs behind which would never be unmounted. The user could of course unmount it.

This is all to say basically, I think the change is probably fine, but in future I'd suggest avoiding changes to defaults like this unless there's a clear reason for it and it's accompanied with upgrade impact analysis.

Comment (aditighag) [reply pkg/defaults/defaults.go:101]: @joestringer FWIW, I did consider upgrade/downgrade implications before making the change. 

>upgrading Cilium to this version with a new default could leave an extra mount of the cgroupfs behind which would never be unmounted.

How would that happen? 🤔  `/var/run` is a symlink to `/run` on most platforms.

**Comment by aditighag** [comment]
I ended up taking care of both the backports since it there were lot many conflicts.

File: pkg/defaults/defaults.go (hunk 25 above)
Comment (joestringer) [reply pkg/defaults/defaults.go:101]: It's good to know that you had considered upgrade/downgrade implications. It can be a bit hard to gauge whether different developers are considering this on their PRs and whether we all have a shared understanding of the impacts. As someone trying to assess whether we should be including particular PRs in upcoming releases, my goal is basically to minimize the risk of the changes. If I see something that appears risky through some fuzzy logic (glancing at the changes, looking at what CI is saying) then I tend to look into what I can do to reduce that risk. The above comment was the output of that process with basically an assessment (low risk) and a suggestion (maybe in future we can avoid making changes to pkg/defaults).

One of the reasons I raised the comment above is that I see any change to `pkg/defaults` in a backport patch as a red flag. In general our upgrade model tends to assume that agent defaults do not change, with the notion in mind that users can end up using their existing DS YAMLs and just doing an image tag bump and they will not adopt new changes to existing settings. On the contrary if we want _new_ users to adopt some setting, then we tend to set the new value in the helm configuration and avoid making the change in the daemon. I'm not sure if we've ever formally encoded this knowledge somewhere or whether it's been effectively passed around the core team. (If we have passed this on successfully, then bear with me explaining it again :sweat_smile: )

The reason for this approach is that there's a certain class of upgrade bugs that can be caused by changing agent defaults. On one hand, banning changes to `pkg/defaults` in bugfix PRs isn't going to get rid of upgrade breakages. On the other hand, if it's possible to avoid changing default settings then I think we should avoid making those changes, so we don't have to consider this class of upgrade bugs.

File: install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml [hunk 26]
```diff
@@ -370,6 +375,28 @@ spec:
...
+            value: {{ .Values.cgroup.hostRoot }}
+        command:
+          - nsenter
+          - --cgroup=/hostpid1ns/cgroup
+          - --mount=/hostpid1ns/mnt
+          - --
+          - sh
+          - -c
+          - 'mount | grep "$CGROUP_ROOT type cgroup2" || { echo "Mounting cgroup filesystem..."; mount -t cgroup2 none $CGROUP_ROOT; }'
+        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}{{ if .Values.image.useDigest }}@{{ .Values.image.digest }}{{ end }}"
```
Comment (joestringer) [inline install/kubernetes/cilium/templates/cilium-agent-daemonset.yaml:393]: @aditighag btw just while looking back over this implementation I noticed that this container is missing `imagePullPolicy`. We shuold probably set it the same way as the other init container below.
