### PR TITLE
iptables, loader: add rules for multi-node NodePort traffic on EKS

### LINKED ISSUE #12098: pod-to-b-multi-node-nodeport connectivity test failing on EKS with 1.8.0-rc3
When following the EKS GSG instructions to validate Cilium 1.8.0-rc3 for #11903 (including the fix for #12078), the connectivity check for `pod-to-b-multi-node-nodeport` is failing:

```
% kubectl get po
NAME                                                     READY   STATUS    RESTARTS   AGE
echo-a-58dd59998d-fcfsc                                  1/1     Running   0          133m
echo-b-865969889d-7qgfg                                  1/1     Running   0          133m
echo-b-host-659c674bb6-tvzxm                             1/1     Running   0          133m
host-to-b-multi-node-clusterip-6fb94d9df6-v25v4          1/1     Running   0          133m
host-to-b-multi-node-headless-7c4ff79cd-2dgct            1/1     Running   0          133m
pod-to-a-5c8dcf69f7-zq2zj                                1/1     Running   0          133m
pod-to-a-allowed-cnp-75684d58cc-tb5jm                    1/1     Running   0          133m
pod-to-a-external-1111-669ccfb85f-8l2p2                  1/1     Running   0          133m
pod-to-a-l3-denied-cnp-7b8bfcb66c-qg2wc                  1/1     Running   0          133m
pod-to-b-intra-node-74997967f8-c88x9                     1/1     Running   0          133m
pod-to-b-intra-node-nodeport-775f967f47-t426f            1/1     Running   0          133m
pod-to-b-multi-node-clusterip-587678cbc4-xskt6           1/1     Running   0          133m
pod-to-b-multi-node-headless-574d9f5894-xd2jq            1/1     Running   0          133m
pod-to-b-multi-node-nodeport-7944d9f9fc-qpv5r            0/1     Running   0          133m
pod-to-external-fqdn-allow-google-cnp-6dd57bc859-bqhhq   1/1     Running   0          133m

% kubectl get svc
NAME                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
echo-a                 ClusterIP   10.100.133.146   <none>        80/TCP         136m
echo-b                 NodePort    10.100.21.112    <none>        80:31313/TCP   136m
echo-b-headless        ClusterIP   None             <none>        80/TCP         136m
echo-b-host-headless   ClusterIP   None             <none>        <none>         136m
kubernetes             ClusterIP   10.100.0.1       <none>        443/TCP        147m

% kubectl get ep 
NAME                   ENDPOINTS                               AGE
echo-a                 192.168.108.20:80                       136m
echo-b                 192.168.98.169:80                       136m
echo-b-headless        192.168.98.169:80                       136m
echo-b-host-headless   192.168.16.155                          136m
kubernetes             192.168.148.188:443,192.168.97.61:443   147m
```

Follow-up for #12078 

/cc @brb

### PR DESCRIPTION
**Pull request by qmonnet**
## Description

Multi-node NodePort traffic for EKS needs a set of specific rules that are usually set by the aws daemonset:

    # sysctl -w net.ipv4.conf.eth0.rp_filter=2
    # iptables -t mangle -A PREROUTING -i eth0 -m comment --comment "AWS, primary ENI" -m addrtype --dst-type LOCAL --limit-iface-in -j CONNMARK --set-xmark 0x80/0x80
    # iptables -t mangle -A PREROUTING -i eni+ -m comment --comment "AWS, primary ENI" -j CONNMARK --restore-mark --nfmask 0x80 --ctmask 0x80
    # ip rule add fwmark 0x80/0x80 lookup main

These rules mark packets coming from another node through eth0, and restore the mark on the return path to force a lookup into the main routing table. Without them, the `ip rules` set by the cilium-cni plugin tell the host to lookup into the table related to the VPC for which the CIDR used by the endpoint has been configured.

We want to reproduce equivalent rules to ensure correct routing, or multi-node NodePort traffic will not be routed correctly. This could be observed with the `pod-to-b-multi-node-nodeport` pod from connectivity check never getting ready.

This commit makes the loader and iptables module create the relevant rules when IPAM is ENI and egress masquerading is in use. The rules are nearly identical to those from the aws daemonset (different comments, different interface prefix for conntrack return path, explicit preference for ip rule):

    # sysctl -w net.ipv4.conf.<egressMasqueradeInterfaces>.rp_filter=2
    # iptables -t mangle -A PREROUTING -i <egressMasqueradeInterfaces> -m comment --comment "cilium: primary ENI" -m addrtype --dst-type LOCAL --limit-iface-in -j CONNMARK --set-xmark 0x80/0x80
    # iptables -t mangle -A PREROUTING -i lxc+ -m comment --comment "cilium: primary ENI" -j CONNMARK --restore-mark --nfmask 0x80 --ctmask 0x80
    # ip rule add fwmark 0x80/0x80 lookup main pref 109

## Steps for verification

Apply the patch, build and push the Docker image:

```
$ DOCKER_DEV_ACCOUNT=qmonnet make dev-docker-image
$ docker push qmonnet/cilium-dev:latest
```

Follow the instructions to [install Cilium on AWS EKS](https://docs.cilium.io/en/v1.8/gettingstarted/k8s-install-eks/). When deploying Cilium with Helm, do not forget to pass the location of the custom image for the agent:

```
$ helm install cilium [...] --set agent.image=docker.io/qmonnet/cilium-dev
```

Deploy the connectivity check. Pick the version from Cilium v1.8 (latest version does not have `pod-to-b-multi-node-nodeport`):

```
$ kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/v1.8/examples/kubernetes/connectivity-check/connectivity-check.yaml
```

Wait a few seconds. On a cilium pod, the newly-added rules should be visible:

```
# sysctl net.ipv4.conf.eth0.rp_filter
net.ipv4.conf.eth0.rp_filter = 2
# iptables-save|grep -w 0x80
-A CILIUM_PRE_mangle -i eth0 -m comment --comment "cilium: primary ENI" -m addrtype --dst-type LOCAL --limit-iface-in -j CONNMARK --set-xmark 0x80/0x80
-A CILIUM_PRE_mangle -i lxc+ -m comment --comment "cilium: primary ENI" -j CONNMARK --restore-mark --nfmask 0x80 --ctmask 0x80
# ip rule|grep -w 0x80
109:    from all fwmark 0x80/0x80 lookup main 
```

All pods from the connectivity-check should be marked as ready, in particular the `pod-to-b-multi-node-nodeport`:

```
$ kubectl get pods
NAME                                                     READY   STATUS    RESTARTS   AGE
echo-a-58dd59998d-ct49w                                  1/1     Running   0          3m8s
echo-b-865969889d-xlb2v                                  1/1     Running   0          3m8s
echo-b-host-659c674bb6-895qn                             1/1     Running   2          3m8s
host-to-b-multi-node-clusterip-6fb94d9df6-7lk9s          1/1     Running   1          3m8s
host-to-b-multi-node-headless-7c4ff79cd-9zk4c            1/1     Running   1          3m8s
pod-to-a-5c8dcf69f7-5jnmh                                1/1     Running   0          3m8s
pod-to-a-allowed-cnp-75684d58cc-flpb9                    1/1     Running   0          3m8s
pod-to-a-external-1111-669ccfb85f-mljxd                  1/1     Running   0          3m7s
pod-to-a-l3-denied-cnp-7b8bfcb66c-tnqqf                  1/1     Running   0          3m8s
pod-to-b-intra-node-74997967f8-phb8v                     1/1     Running   0          3m8s
pod-to-b-intra-node-nodeport-775f967f47-8tjkq            1/1     Running   1          3m8s
pod-to-b-multi-node-clusterip-587678cbc4-4kzpg           1/1     Running   0          3m7s
pod-to-b-multi-node-headless-574d9f5894-vsbjt            1/1     Running   1          3m7s
pod-to-b-multi-node-nodeport-7944d9f9fc-wn4j2            1/1     Running   1          3m7s
pod-to-external-fqdn-allow-google-cnp-6dd57bc859-4h4pj   1/1     Running   0          3m7s
```

## Discussion

I am not entirely sure of my implementation. In particular, reviewers might want to consider:

- Is this the best location to add the rules? I initially considered the AWS-related code for the cilium-cni but I don't think this is used to manage the node itself.
- Should the rules depend on masquerading being used? I was under the impression we always use it for EKS, and that the interface we use for egress masquerading is the one to target with the rules. But I may be wrong.
- I picked a preference for the `ip rule` (`linux_defaults.RulePriorityEgress - 1`) so it gets looked up just before the rule we want to avoid, but maybe I should create a new constant in `linux_defaults` for that? Not sure if this is worth.
- Style: The processing of interface names for the `ip rule` addition feels a bit cumbersome (with this `+` prefix to process). I'm not sure we have a helper for this somewhere, I could not find one (other `lxc+`-style names are passed directly to iptables from what I could see). We do have a helper somewhere for setting `rp_filter` but it is not used in `Reinitialize()` from the `loader`, so I just stuck to local code and appended to `sysSettings`.

## Tests

None in this PR. Ready-state can be tested with connectivity check from Cilium v1.8 (I didn't realise [it was gone](https://github.com/cilium/cilium/commit/8a03d54da11a1c15302f4f90de8bf1e539252784) until writing this description).

Follow-up: Re-introduce `pod-to-b-multi-node-nodeport` or equivalent in connectivity checks.

Fixes: #12098

```release-note
Fix bug in ENI environments where connections to NodePort would fail due to asymmetric routing
```

### CODE REVIEW

**Comment by qmonnet** [comment]
test-me-please

**Comment by qmonnet** [comment]
Sidenote: Discussing with @joestringer on Slack, it appears that the removal of `pod-to-b-multi-node-nodeport` from the connectivity checks was unintentional. I'll work on restoring it, but this may be for a follow-up PR and should not be blocking this one.

File: pkg/datapath/iptables/iptables.go [hunk 1]
```diff
@@ -1036,6 +1036,17 @@ func (m *IptablesManager) InstallRules(ifName string) error {
 		}
 	}
 
+	// EKS expects the aws daemonset to set up specific rules for marking
+	// packets It marks packets coming from another node and restores the
```
Comment (tklauser) [inline pkg/datapath/iptables/iptables.go]: Nit:
```suggestion
	// packets. It marks packets coming from another node and restores the
```

File: pkg/datapath/iptables/iptables.go [hunk 2]
```diff
@@ -1036,6 +1036,17 @@ func (m *IptablesManager) InstallRules(ifName string) error {
...
+	// mark on the return path to force a lookup into the main routing
+	// table. We want to reproduce something similar. Please see note in
+	// Reanitialize() in package "loader" for more details.
```
Comment (tklauser) [inline pkg/datapath/iptables/iptables.go]: Nit:
```suggestion
	// Reinitialize() in pkg/datapath/loader for more details.
```

File: pkg/datapath/loader/base.go [hunk 3]
```diff
@@ -107,6 +110,42 @@ func writePreFilterHeader(preFilter *prefilter.PreFilter, dir string) error {
...
+	if *egMasqIfOpt == "" {
+		for _, l := range links {
+			ifaces = append(ifaces, l.Attrs().Name)
+		}
+	} else {
+		for _, l := range links {
+			if strings.HasPrefix(l.Attrs().Name, (*egMasqIfOpt)[:len(*egMasqIfOpt)-1]) {
+				ifaces = append(ifaces, l.Attrs().Name)
+			}
+		}
```
Comment (tklauser) [inline pkg/datapath/loader/base.go]: With the above change of the declaration of `egMasqIfOpt`:

```suggestion
		egMasqIfOpt := strings.TrimSuffix(egMasqIfOpt, "+")
		for _, l := range links {
			if strings.HasPrefix(l.Attrs().Name, egMasqIfOpt) {
				ifaces = append(ifaces, l.Attrs().Name)
			}
		}
```

IMO this makes it easier to follow that the `+` is stripped.

**Review by tklauser — APPROVED** [review]
Thanks a lot for the detailed descriptions and the verification steps in the PR description! Using these steps I was able to verify that this PR indeed fixes the `pod-to-b-multi-node-nodeport` connectivity check on EKS.

Some small nits inline regarding coding style and some typos. Other than that LGTM.

I'm not sure (or not knowledgeable enough) to judge on the first 3 discussion bullet points in the PR description. I'd be glad if the other reviewers could comment on these.

Regarding the fourth bullet point (_Style_) I think it's fine as is for now and could be refactored in a follow-up PR if needed. I don't think we have an existing helper for this (or at least I couldn't find one with my `grep` skills).

File: pkg/datapath/iptables/iptables.go (hunk 1 above)
Comment (christarazi) [inline pkg/datapath/iptables/iptables.go]: Nit: missing a period?

```suggestion
	// EKS expects the aws daemonset to set up specific rules for marking
	// packets. It marks packets coming from another node and restores the
```

File: pkg/datapath/loader/base.go [hunk 4]
```diff
@@ -293,6 +332,41 @@ func (l *Loader) Reinitialize(ctx context.Context, o datapath.BaseProgramOwner,
...
+		ifaces, err := getEgressMasqueradeInterfaces()
+		if err != nil {
+			return fmt.Errorf("failed to set rp_filter for interfaces with egress masquerading for ENI multi-node NodePort: %w", err)
+		}
+		for _, iface := range ifaces {
+			sysSettings = append(sysSettings,
+				setting{"net.ipv4.conf." + iface + ".rp_filter", "2", false})
+		}
+		if err := route.ReplaceRule(route.Rule{
+			Priority: linux_defaults.RulePriorityEgress - 1,
```
Comment (christarazi) [inline pkg/datapath/loader/base.go]: Regarding point (3), I think it would be valuable to create this as a const. It's better to codify a value that we depend on, so that it is discoverable when debugging, understanding docs, etc.

Comment (christarazi) [reply pkg/datapath/loader/base.go]: (Seeing the marks and masks down below are also not consts, but maybe that's something we've always done with marks and masks? Either way, I think defining the rule priority still makes sense as there's precedent.)

**Review by christarazi — COMMENTED** [review]
Thanks for the thorough explanations. Just a few minor points to address.

File: pkg/datapath/loader/base.go (hunk 4 above)
Comment (joestringer) [reply pkg/datapath/loader/base.go]: Yes, collecting these in canonical locations with all relevant references (+ comments on how they were chosen) would be useful for maintenance.

File: pkg/datapath/iptables/iptables.go [hunk 5]
```diff
@@ -1036,6 +1036,17 @@ func (m *IptablesManager) InstallRules(ifName string) error {
...
+	if option.Config.Masquerade && option.Config.IPAM == ipamOption.IPAMENI {
```
Comment (joestringer) [inline pkg/datapath/iptables/iptables.go]: Starting a thread for the point from the PR description:

> Should the rules depend on masquerading being used? I was under the impression we always use it for EKS, and that the interface we use for egress masquerading is the one to target with the rules. But I may be wrong.

Can you reproduce if masquerade is disabled?

I see the core of this issue as 'multi-homing' in that traffic coming in on the primary ENI must have the responses routed via the primary ENI. If I follow right, the priority/pref selected below is specifically to take precedence over the default routing which would route traffic from a pod via the associated (non-primary) ENI.

I'm not sure I follow the masquerade link here (not saying it's not there, I'm just curious to see the explanation).

File: pkg/datapath/loader/base.go [hunk 6]
```diff
@@ -293,6 +332,41 @@ func (l *Loader) Reinitialize(ctx context.Context, o datapath.BaseProgramOwner,
...
+	//
+	// It marks packets coming from another node through eth0, and restores
+	// the mark on the return path to force a lookup into the main routing
+	// table. Without these rules, the "ip rules" set by the cilium-cni
+	// plugin tell the host to lookup into the table related to the VPC for
+	// which the CIDR used by the endpoint has been configured.
+	//
+	// We want to reproduce equivalent rules to ensure correct routing.
+	// See also iptables.addCiliumENIRules().
+	if option.Config.Masquerade && option.Config.IPAM == ipamOption.IPAMENI {
```
Comment (joestringer) [inline pkg/datapath/loader/base.go]: nit: If there's some common set of configurations across multiple packages, it might be worth introducing a dedicated option function to encapsulate the common checks, maybe something like `option.Config.MultiDevice()` or `MultiHoming()` or similar?

File: pkg/datapath/iptables/iptables.go [hunk 7]
```diff
@@ -1140,3 +1151,25 @@ func (m *IptablesManager) addCiliumNoTrackXfrmRules() error {
 	}
 	return nil
 }
+
+func (m *IptablesManager) addCiliumENIRules() error {
```
Comment (joestringer) [inline pkg/datapath/iptables/iptables.go:1154]: My next question is, what's our plan for a non-iptables version of this functionality? :-)

File: pkg/datapath/iptables/iptables.go [hunk 8]
```diff
@@ -1140,3 +1151,25 @@ func (m *IptablesManager) addCiliumNoTrackXfrmRules() error {
...
+	if err := runProg("iptables", append(
+		m.waitArgs,
+		"-t", "mangle",
+		"-A", ciliumPreMangleChain,
+		"-i", option.Config.EgressMasqueradeInterfaces,
+		"-m", "comment", "--comment", "cilium: primary ENI",
+		"-m", "addrtype", "--dst-type", "LOCAL", "--limit-iface-in",
+		"-j", "CONNMARK", "--set-xmark", "0x80/0x80"),
```
Comment (joestringer) [inline pkg/datapath/iptables/iptables.go]: Do we have a Golang representation of the common marks we use or do we just set them via strings like this everywhere? If the former, let's make this the same as the other code. If the latter, let's file an issue to follow up & collect these so we can more easily reason about them.

File: pkg/datapath/loader/base.go [hunk 9]
```diff
@@ -107,6 +110,42 @@ func writePreFilterHeader(preFilter *prefilter.PreFilter, dir string) error {
 	return fw.Flush()
 }
 
+// Return the list of interfaces with egress masquerading.
+// - If option.Config.Masquerade is disabled, return an empty slice.
+// - If option.Config.EgressMasqueradeInterfaces is set to a simple interface
+//   name, return its value.
+// - If it is empty, return the list of all interfaces.
+// - If it has a '+' suffix, return the names of all matching interfaces.
+func getEgressMasqueradeInterfaces() ([]string, error) {
```
Comment (joestringer) [inline pkg/datapath/loader/base.go]: > Style: The processing of interface names for the ip rule addition feels a bit cumbersome (with this + prefix to process). I'm not sure we have a helper for this somewhere, I could not find one (other lxc+-style names are passed directly to iptables from what I could see). We do have a helper somewhere for setting rp_filter but it is not used in Reinitialize() from the loader, so I just stuck to local code and appended to sysSettings.

I doubt we have another place where we actually process these. For most cases it has been sufficient to just pass the argument directly to `iptables`.

But this highlights a point, if we're going to have it here, seems reasonable to add a small unit test to check that the devices are being properly selected by this function. (Even if it's abstracted so we're not directly interacting with the kernel, just matching the string names properly).

File: pkg/datapath/loader/base.go [hunk 10]
```diff
@@ -293,6 +332,41 @@ func (l *Loader) Reinitialize(ctx context.Context, o datapath.BaseProgramOwner,
 	log.Infof("Setting up base BPF datapath (BPF %s instruction set, %s clock source)",
 		args[initBPFCPU], clockSource[option.Config.ClockSource])
 
+	// EKS expects the aws daemonset to set up the following rules that
```
Comment (joestringer) [inline pkg/datapath/loader/base.go]: > Is this the best location to add the rules? I initially considered the AWS-related code for the cilium-cni but I don't think this is used to manage the node itself.

I think it's spread over multiple places likely including `bpf/init.sh` right now, so I'm not sure there's a "wrong" answer. At some point we should converge them, but that's a longer-term objective.

**Review by joestringer — CHANGES_REQUESTED** [review]
Looks reasonable, couple of comments below on your discussion points. Please also address the feedback from other reviewers.

File: pkg/datapath/iptables/iptables.go (hunk 5 above)
Comment (qmonnet) [reply pkg/datapath/iptables/iptables.go]: I looked at it again, and making it depend on masquerading seems wrong.

If masquerade is disabled here, there is no visible impact on most of the connectivity checks (in particular, the one we focus on is still working). Only the ones related to external connectivity fail to get ready. I think my initial idea was “we always need masquerading with EKS to have external connectivity, so I can rely on it to pin down the « EKS » case”, but on second thought this seems dubious. And there are probably no particular reason why I should apply the rules on the masqueraded interfaces either.

So there are two things that I need to sort out here:
- Should I restrict those rules to EKS only, and if so, how can I do it? At least it's easy to restrict to AWS. Ideally we _should_ restrict further to EKS (as far as I know, this fix is not required for regular AWS), but do we have an easy way to do so (and is it worth it)?
- How should I determine the interface on which the rules should be applied? For the GSG it's easy, it's just `eth0` but I can't really go with that in the code. So I need a way to get the list of interfaces through which the node is susceptible to receive traffic from other nodes from the cluster, do we have a way to retrieve that? Other iptables/ip rules I found were only on `lxc*`, `cilium_*` interfaces.

File: pkg/datapath/loader/base.go (hunk 6 above)
Comment (qmonnet) [reply pkg/datapath/loader/base.go]: Good idea, let's sort out the exact conditions we need first.

File: pkg/datapath/iptables/iptables.go (hunk 7 above)
Comment (qmonnet) [reply pkg/datapath/iptables/iptables.go:1154]: No plan at the moment. I'm mostly focusing on getting a fix so NodePort works as expected on EKS, I don't know if we want or need a non-iptables version. It's only two rules per interface used between the nodes, so shouldn't be adding to much overhead, but maybe finding an alternative is desirable... What is your opinion on the topic?

File: pkg/datapath/iptables/iptables.go (hunk 8 above)
Comment (qmonnet) [reply pkg/datapath/iptables/iptables.go]: It seems we have a representation for the other _marks_ (e.g. `markAsFromHost`), I have updated my code accordingly.

I suppose long-term we might also want to wrap the recurrent arguments a bit to avoid appending so many strings? Would you like me to open an issue for that?

File: pkg/datapath/loader/base.go (hunk 9 above)
Comment (qmonnet) [reply pkg/datapath/loader/base.go]: Right, a unit test is a good idea. I'll add one if we keep the relevant code, let's figure out how to get the interfaces on which we should load the rules first.

File: pkg/datapath/iptables/iptables.go (hunk 8 above)
Comment (qmonnet) [reply pkg/datapath/iptables/iptables.go]: By the way most of those representations take the form
```go
markAsFromHost := fmt.Sprintf("%#08x/%#08x", linux_defaults.MagicMarkHost, linux_defaults.MagicMarkHostMask)
```
We could maybe at least add a wrapper to have 
```go
markAsFromHost := makeXmark(linux_defaults.MagicMarkHost, linux_defaults.MagicMarkHostMask)
```
instead.

**Comment by qmonnet** [comment]
Thanks a lot Tobias, Chris and Joe for the verification and the reviews! It's been really helpful and much appreciated.

I addressed the comments from Tobias and Chris, there are some points that I still need to sort out regarding Joe's feedback (see inline answers).
<details><summary>Incremental diff</summary>

``` diff
diff --git a/pkg/datapath/iptables/iptables.go b/pkg/datapath/iptables/iptables.go
index c59a76f5399a..b6f424ca646d 100644
--- a/pkg/datapath/iptables/iptables.go
+++ b/pkg/datapath/iptables/iptables.go
@@ -1037,10 +1037,10 @@ func (m *IptablesManager) InstallRules(ifName string) error {
 	}
 
 	// EKS expects the aws daemonset to set up specific rules for marking
-	// packets It marks packets coming from another node and restores the
+	// packets. It marks packets coming from another node and restores the
 	// mark on the return path to force a lookup into the main routing
 	// table. We want to reproduce something similar. Please see note in
-	// Reanitialize() in package "loader" for more details.
+	// Reanitialize() in pkg/datapath/loader for more details.
 	if option.Config.Masquerade && option.Config.IPAM == ipamOption.IPAMENI {
 		if err := m.addCiliumENIRules(); err != nil {
 			return fmt.Errorf("cannot install rules for ENI multi-node NodePort: %w", err)
@@ -1153,6 +1153,8 @@ func (m *IptablesManager) addCiliumNoTrackXfrmRules() error {
 }
 
 func (m *IptablesManager) addCiliumENIRules() error {
+	nfmask := fmt.Sprintf("%#08x", linux_defaults.MarkMultinodeNodeport)
+	ctmask := fmt.Sprintf("%#08x", linux_defaults.MaskMultinodeNodeport)
 	if err := runProg("iptables", append(
 		m.waitArgs,
 		"-t", "mangle",
@@ -1160,7 +1162,7 @@ func (m *IptablesManager) addCiliumENIRules() error {
 		"-i", option.Config.EgressMasqueradeInterfaces,
 		"-m", "comment", "--comment", "cilium: primary ENI",
 		"-m", "addrtype", "--dst-type", "LOCAL", "--limit-iface-in",
-		"-j", "CONNMARK", "--set-xmark", "0x80/0x80"),
+		"-j", "CONNMARK", "--set-xmark", nfmask+"/"+ctmask),
 		false); err != nil {
 		return err
 	}
@@ -1170,6 +1172,6 @@ func (m *IptablesManager) addCiliumENIRules() error {
 		"-A", ciliumPreMangleChain,
 		"-i", getDeliveryInterface(""),
 		"-m", "comment", "--comment", "cilium: primary ENI",
-		"-j", "CONNMARK", "--restore-mark", "--nfmask", "0x80", "--ctmask", "0x80"),
+		"-j", "CONNMARK", "--restore-mark", "--nfmask", nfmask, "--ctmask", ctmask),
 		false)
 }
diff --git a/pkg/datapath/linux/linux_defaults/linux_defaults.go b/pkg/datapath/linux/linux_defaults/linux_defaults.go
index 8d9dda86755b..33040aa7324c 100644
--- a/pkg/datapath/linux/linux_defaults/linux_defaults.go
+++ b/pkg/datapath/linux/linux_defaults/linux_defaults.go
@@ -34,6 +34,15 @@ const (
 	// RouteMarkMask is the mask required for the route mark value
 	RouteMarkMask = 0xF00
 
+	// MarkMultinodeNodeport is used on AWS EKS to mark traffic from another
+	// node, so that it gets routed back through the relevant interface.
+	MarkMultinodeNodeport = 0x80
+
+	// MaskMultinodeNodeport is the mask associated with the
+	// RouterMarkNodePort for NodePort traffic from remote nodes on AWS
+	// EKS.
+	MaskMultinodeNodeport = 0x80
+
 	// IPSecProtocolID IP protocol ID for IPSec defined in RFC4303
 	RouteProtocolIPSec = 50
 
@@ -46,6 +55,13 @@ const (
 	// of endpoints. This priority is after the local table priority.
 	RulePriorityEgress = 110
 
+	// RulePriorityNodeport is the priority of the rule used on AWS EKS, to
+	// make sure that lookups for multi-node NodePort traffic are NOT done
+	// from the table for the VPC to which the endpoint's CIDR is
+	// associated, but from the main routing table instead.
+	// This priority is before the egress priority.
+	RulePriorityNodeport = RulePriorityEgress - 1
+
 	// TunnelDeviceName the default name of the tunnel device when using vxlan
 	TunnelDeviceName = "cilium_vxlan"
 
diff --git a/pkg/datapath/loader/base.go b/pkg/datapath/loader/base.go
index 629cebf118ee..75ef8197fb53 100644
--- a/pkg/datapath/loader/base.go
+++ b/pkg/datapath/loader/base.go
@@ -137,8 +137,9 @@ func getEgressMasqueradeInterfaces() ([]string, error) {
 			ifaces = append(ifaces, l.Attrs().Name)
 		}
 	} else {
+		ifPrefix := strings.TrimSuffix(*egMasqIfOpt, "+")
 		for _, l := range links {
-			if strings.HasPrefix(l.Attrs().Name, (*egMasqIfOpt)[:len(*egMasqIfOpt)-1]) {
+			if strings.HasPrefix(l.Attrs().Name, ifPrefix) {
 				ifaces = append(ifaces, l.Attrs().Name)
 			}
 		}
@@ -358,9 +359,9 @@ func (l *Loader) Reinitialize(ctx context.Context, o datapath.BaseProgramOwner,
 				setting{"net.ipv4.conf." + iface + ".rp_filter", "2", false})
 		}
 		if err := route.ReplaceRule(route.Rule{
-			Priority: linux_defaults.RulePriorityEgress - 1,
-			Mark:     0x80,
-			Mask:     0x80,
+			Priority: linux_defaults.RulePriorityNodeport,
+			Mark:     linux_defaults.MarkMultinodeNodeport,
+			Mask:     linux_defaults.MaskMultinodeNodeport,
 			Table:    route.MainTable,
 		}); err != nil {
 			return fmt.Errorf("unable to install ip rule for ENI multi-node NodePort: %w", err)
```
</details>

File: pkg/datapath/iptables/iptables.go (hunk 7 above)
Comment (joestringer) [reply pkg/datapath/iptables/iptables.go:1154]: We're aiming to provide an entirely iptables-free implementation, so that's where my question comes from. I think it's very reasonable to have this PR to solve the functional question first, then we can address the non-iptables question later. This is mostly fishing for thoughts :-)

File: pkg/datapath/iptables/iptables.go (hunk 8 above)
Comment (joestringer) [reply pkg/datapath/iptables/iptables.go]: > I suppose long-term we might also want to wrap the recurrent arguments a bit to avoid appending so many strings? Would you like me to open an issue for that?

Long-term we want to drop the rules entirely ;) But mid-term, yeah seems like a reasonable aim to avoid extra appends.  Not a huge deal for relatively static generation of rules so I see it maybe more from the angle that it could improve readability.

File: pkg/datapath/iptables/iptables.go (hunk 5 above)
Comment (joestringer) [reply pkg/datapath/iptables/iptables.go]: > Should I restrict those rules to EKS only, and if so, how can I do it? At least it's easy to restrict to AWS. Ideally we should restrict further to EKS (as far as I know, this fix is not required for regular AWS), but do we have an easy way to do so (and is it worth it)?

I think that restricting using `IPAMENI` is very reasonable and handles the case we want. Strictly speaking you might interpret that as handling only IPAM via ENI (rather than routing/devices), but in practice these two are tied together. If we're in an environment where we're handling direct IPAM via ENI, then there are potentially multiple ENI devices that we need to manage, and that's the case where this comes up.

> How should I determine the interface on which the rules should be applied? For the GSG it's easy, it's just eth0 but I can't really go with that in the code. So I need a way to get the list of interfaces through which the node is susceptible to receive traffic from other nodes from the cluster, do we have a way to retrieve that? Other iptables/ip rules I found were only on lxc*, cilium_* interfaces.

On latest code, does `--devices` provide what you need? That's where we detect devices with access outside the cluster AFAIK (including on v1.8.x). @pchaigno / @brb can keep me honest here. But then we'll still need to figure it out for older releases as well. On older release there was `--device` but I don't know whether ENI users will be guaranteed to configure it. May be worth cross-referencing with the EKS guide.

Comment (brb) [reply pkg/datapath/iptables/iptables.go]: > How should I determine the interface on which the rules should be applied?

If the device is used to communicate between k8s nodes, then you can use `DirectRoutingDevice`.

Comment (brb) [reply pkg/datapath/iptables/iptables.go]: > Is this the best location to add the rules?

Just thinking loud but we have another PR which adds custom iptables rules for GKE to nodeinit: https://github.com/cilium/cilium/pull/11782/files. Perhaps we should not spread cloud provider specific rules across multiple places, and have a dedicated package for it?

**Review by tklauser — APPROVED** [review]
:+1: for my requested changes

File: pkg/datapath/iptables/iptables.go (hunk 5 above)
Comment (tgraf) [reply pkg/datapath/iptables/iptables.go]: The GKE bits are likely to be removed again fairly soon given the native integration.

**Comment by joestringer** [comment]
From discussion on Slack, while this is important to fix and it would be great to include in a release shortly, it should not block other important fixes from being released. Removed the corresponding label.

**Review by tgraf — APPROVED** [review]

File: pkg/datapath/loader/base.go [hunk 11]
```diff
@@ -107,6 +110,43 @@ func writePreFilterHeader(preFilter *prefilter.PreFilter, dir string) error {
...
+// Return the list of interfaces with egress masquerading.
+// - If option.Config.Masquerade is disabled, return an empty slice.
+// - If option.Config.EgressMasqueradeInterfaces is set to a simple interface
+//   name, return its value.
+// - If it is empty, return the list of all interfaces.
+// - If it has a '+' suffix, return the names of all matching interfaces.
+func getEgressMasqueradeInterfaces() ([]string, error) {
+	var ifaces []string
+	if !option.Config.Masquerade {
+		return ifaces, nil
```
Comment (tgraf) [inline pkg/datapath/loader/base.go]: I think we should just return "eth0" in this case.

**Review by tgraf — CHANGES_REQUESTED** [review]

**Review by tgraf — APPROVED** [review]

File: pkg/datapath/loader/base.go (hunk 11 above)
Comment (tgraf) [reply pkg/datapath/loader/base.go]: Fixed up

File: pkg/datapath/loader/base.go (hunk 6 above)
Comment (qmonnet) [reply pkg/datapath/loader/base.go]: Turns out we don't want checks on masquerading, so we end up with a simple condition already. Marking as resolved.

File: pkg/datapath/loader/base.go (hunk 9 above)
Comment (qmonnet) [reply pkg/datapath/loader/base.go]: Function is gone. Marking as resolved.

**Comment by qmonnet** [comment]
test-me-please

File: pkg/datapath/iptables/iptables.go (hunk 5 above)
Comment (qmonnet) [reply pkg/datapath/iptables/iptables.go]: Main topic of the discussion addressed in the sense that the added rules do not depend on masquerading anymore.

The other PR has been merged already and according to Thomas, it may not stay long in the code, so I won't address the suggestion from Martynas on creating a dedicated package for the rules. Could be done as a follow-up, if desired and relevant.

File: pkg/datapath/iptables/iptables.go (hunk 8 above)
Comment (qmonnet) [reply pkg/datapath/iptables/iptables.go]: Will do the mid-term change as a follow-up.

**Review by joestringer — APPROVED** [review]

File: pkg/datapath/loader/base.go [hunk 12]
```diff
@@ -293,6 +296,35 @@ func (l *Loader) Reinitialize(ctx context.Context, o datapath.BaseProgramOwner,
...
+	//
+	// It marks packets coming from another node through eth0, and restores
+	// the mark on the return path to force a lookup into the main routing
+	// table. Without these rules, the "ip rules" set by the cilium-cni
+	// plugin tell the host to lookup into the table related to the VPC for
+	// which the CIDR used by the endpoint has been configured.
+	//
+	// We want to reproduce equivalent rules to ensure correct routing.
+	if option.Config.IPAM == ipamOption.IPAMENI {
+		sysSettings = append(sysSettings, setting{"net.ipv4.conf.eth0.rp_filter", "2", false})
```
Comment (joestringer) [inline pkg/datapath/loader/base.go:317]: wait, we're hardcoding `eth0` in here now? Is this applicable on AWS nodes?

**Comment by qmonnet** [comment]
Discussion on Slack ([link](https://cilium.slack.com/archives/CDD1S4BHC/p1598283890000800) and link):

The fix in this PR solves the basic case but is not the perfect solution and will likely need follow-ups.

The ideal fix should add the rules for all interfaces, but the list of interfaces that can be used for traffic between nodes is not trivial to obtain. Thomas has worked on a more comprehensive fix, with:

- Extended IPAM to store full IPAM result so we get MACs of all ENIs
- Set up marks on ingress with `0x80000000 | ifindex` to have unique marks for each ENI
- Set up iptables rules via pkg/datapath/loader on initial build
- Move sysctl setting to that hook as well

As of the Slack discussion, there was at least the following item remaning:

- Change ip rules to lookup the table of the ENI instead of the main table

Long term, it may be worth to look at a pure eBPF implementation as well.

File: pkg/datapath/loader/base.go (hunk 12 above)
Comment (joestringer) [reply pkg/datapath/loader/base.go:317]: Per Slack discussion: @qmonnet pointed out that the default instructions do in fact specify `eth0` and this is the standard in EKS, which is the only case we're trying to address in this PR. So there's no need to directly follow up on this.

https://docs.cilium.io/en/v1.8/gettingstarted/k8s-install-eks/

**Comment by joestringer** [comment]
4.9 run hit known issue #12993 which randomly affects some PRs and causes significant numbers of failures. Given that the 4.19 tests all passed, I take that to mean that these are flakes and there is no reliable failure here. Waiting to hear back on net-next CI run.

**Comment by qmonnet** [comment]
Please also give me a bit more time to validate it on EKS. Although I don't expect any surprise, I haven't had time to run the latest version yet.

**Comment by joestringer** [comment]
The test `K8sPolicyTest Multi-node policy test validates ingress CIDR-dependent L4 connectivity is restored after importing ingress policy` failed with an inaccurate count where we expect a specific number of packets but the number is off-by-two. I see a similar failure in the quarantined "host" variation of this test (from https://datastudio.google.com/s/n3goM_hIP4Y), and generally it seems similar to previous monitor tests where we test for specific packet counts and end up being off by a couple of packets sometimes due to test infrastructure not being able to track all packets.

Given that the code in this PR depends on IPAMENI mode which is not enabled in any of the test cases, this is clearly a flake so we can safely ignore to merge.

File: pkg/datapath/iptables/iptables.go (hunk 7 above)
Comment (n0rad) [reply pkg/datapath/iptables/iptables.go:1154]: Just got bitten by this, thankfully after 2h of research I landed here :crying_cat_face: 

I have multi interfaces nodes and wanted to be full cilium, replacing kube-proxy, kube-router and metallb.

Is there any tracking ticket to support it out of kube-proxy? should it be added as a warning on kube-proxy replacement doc page in the meantime?

Comment (pchaigno) [reply pkg/datapath/iptables/iptables.go:1154]: @n0rad Please open a bug report. This discussion is about getting rid of iptables, but it seems you are looking at getting this to work with our kube-proxy replacement, which is a different thing.
