### PR TITLE
datapath/linux: protect against concurrent access in NodeValidateImplementation

### LINKED ISSUE #12460: agent: fatal error: concurrent map writes
## Bug report

Scaling out the amount of nodes of a kubernetes cluster, some of the cilium agent (~18%) failed on the first run with the following error : `fatal error: concurrent map writes`. They all seemed to be working fine after the very next automated restart of the agent process.

at first sight, the error seems quite similar to https://github.com/cilium/cilium/issues/8278

**General Information**

- Cilium version: **1.8.1**
- Kernel version: **5.4.0-1015-aws**
- Orchestration system version in use: **EKS/1.16.8 (eks.1)**
- Link to relevant artifacts: [previous logs of a failed cilium agent pod](https://github.com/cilium/cilium/files/4892180/trace.log)

I am happy to provide the sysdump if necessary as it won't fit on this GitHub issue (>10MB).

**How to reproduce the issue**

I am very uncertain about which environment specifics may be in cause, all I can tell for now is that it never happened until today as I attempted to scale from 5 nodes to 75. All t3a.xlarge in a single AZ. Scaled out via the cluster-autoscaler after increasing the amount of replicas of an `httpbin` deployment.

### PR DESCRIPTION
**Pull request by tklauser**
The `linuxNodeHandler.neighByNode` map is also protected by
`linuxNodeHandler.mutex` in all other code paths. Protect access to it in
`(*linuxNodeHandler).NodeValidateImplementation as well.

Fixes #12460

Fixes: 6c06c51926bc ("node: Remove permanent ARP entry when remote node is deleted")

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

File: pkg/datapath/linux/node.go [hunk 1]
```diff
@@ -1150,6 +1150,9 @@ func (n *linuxNodeHandler) NodeConfigurationChanged(newConfig datapath.LocalNode
 // NodeValidateImplementation is called to validate the implementation of the
 // node in the datapath
 func (n *linuxNodeHandler) NodeValidateImplementation(nodeToValidate nodeTypes.Node) error {
+	n.mutex.Lock()
+	defer n.mutex.Unlock()
+
 	return n.nodeUpdate(nil, &nodeToValidate, false)
```
Comment (sayboras) [inline pkg/datapath/linux/node.go:1156]: nits: I saw in the codebase that normally we add a note on method with some details like `must be called with Lock() held`, do you think it will add any values if we do the same for _nodeUpdate_ as well as _nodeDelete_ ?

Comment (tklauser) [reply pkg/datapath/linux/node.go:1156]: Good point. Given that the CI already passed and in case there are no other requested change, I think this could be addressed in a follow-up PR. It will also make backporting this PR easier.

**Review by brb — APPROVED** [review]
Thanks! I assume you have checked all other paths where nodeUpdate() is called?

**Comment by tklauser** [comment]
> Thanks! I assume you have checked all other paths where nodeUpdate() is called?

Yes, all other code paths calling `nodeUpdate` already hold the mutex.
