### PR TITLE
Use identity labels for selector matching for Egress NAT Gateway

### LINKED ISSUE #17669: Egress Gateway doesn't work with CiliumEndpointSlices
## Proposal / RFE

**Retrieve endpoint labels from numerical id within egressPolicyManager instead of relying on watched obj**

Currently when CiliumEndpointSlices is enabled, egress gateway feature would break. The egress policy updater relies on `endpoint.Identity.labels` to match endpoint to egress policy selector (https://github.com/cilium/cilium/blob/master/pkg/egresspolicy/manager.go#L242) but by design `CES` won't carry pod labels in its `CoreCEP` struct. So egress policy won't match in this case and egress map is always empty.

We discussed this issue with @MasterZ40 offline, the fix is to use `Identity.id` as a middle groud. `CoreCEP` carries the numerical id of an endpoint's security identity, and agent is already watching for all `ciliumidentities` (https://github.com/cilium/cilium/blob/master/pkg/k8s/identitybackend/identity.go#L272), so egress policy manager could just grab the numerical security id from the endpoint, then look up the full identity in the cache, then retrieve the labels.

@MasterZ40 @anfernee @aanm @krishgobinath

### PR DESCRIPTION
**Pull request by blzhao-0**
With the introduction of cilium endpoint slices (CES), pod labels are no
longer in the cilium endpoint struct, breaking the matching logic for
egress NAT gateway. This change fetches the labels from the identify
cache and use identity labels to do the same matching. It makes Egress
NAT Gateway compatible with CES.

Signed-off-by: Bolun Zhao <blzhao@google.com>

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #17669

This is tested manually to verify that

- The egress NAT functionality remains unchanged
- The policy manager correctly fetched the Identity labels for matching
- Egress NAT is compatible with CES enablement

Unit Test Results:
```
=== RUN   Test
START: manager_privileged_test.go:87: EgressGatewayTestSuite.SetUpSuite
level=info msg="Detected mounted BPF filesystem at /sys/fs/bpf" subsys=bpf
PASS: manager_privileged_test.go:87: EgressGatewayTestSuite.SetUpSuite  0.145s

START: manager_privileged_test.go:97: EgressGatewayTestSuite.TestEgressGatewayManager
level=info msg="Added CiliumEgressNATPolicy" ciliumEgressNATPolicyName=policy-1 subsys=egressgateway
Allocated ID:  {1000 k8s:test-key=test-value-1 {0 {0 0}}  []  1}
level=info msg="Egress gateway policy applied" destinationCIDR="{1.1.1.0 ffffff00}" egressIP=192.168.101.1 gatewayIP=192.168.101.1 sourceIP=10.0.0.1 subsys=egressgateway
Released old ID:  {1000 k8s:test-key=test-value-1 {0 {0 0}}  []  1}
Allocated new ID:  {1001  {0 {0 0}}  []  1}
level=info msg="Egress gateway policy removed" destinationCIDR=1.1.1.0/24 sourceIP=10.0.0.1 subsys=egressgateway
Released old ID:  {1001  {0 {0 0}}  []  1}
Allocated new ID:  {1002 k8s:test-key=test-value-1 {0 {0 0}}  []  1}
level=info msg="Egress gateway policy applied" destinationCIDR="{1.1.1.0 ffffff00}" egressIP=192.168.101.1 gatewayIP=192.168.101.1 sourceIP=10.0.0.1 subsys=egressgateway
level=info msg="Added CiliumEgressNATPolicy" ciliumEgressNATPolicyName=policy-2 subsys=egressgateway
Allocated ID:  {1003 k8s:test-key=test-value-2 {0 {0 0}}  []  1}
level=info msg="Egress gateway policy applied" destinationCIDR="{1.1.1.0 ffffff00}" egressIP=192.168.102.1 gatewayIP=192.168.102.1 sourceIP=10.0.0.2 subsys=egressgateway
Released old ID:  {1002 k8s:test-key=test-value-1 {0 {0 0}}  []  1}
Allocated new ID:  {1004  {0 {0 0}}  []  1}
level=info msg="Egress gateway policy removed" destinationCIDR=1.1.1.0/24 sourceIP=10.0.0.1 subsys=egressgateway
PASS: manager_privileged_test.go:97: EgressGatewayTestSuite.TestEgressGatewayManager    0.000s

level=info msg="Egress gateway policy applied" destinationCIDR="{1.1.1.0 ffffff00}" egressIP=192.168.102.1 gatewayIP=192.168.102.1 sourceIP=10.0.0.2 subsys=egressgateway
OK: 1 passed
--- PASS: Test (0.15s)
PASS
```

### CODE REVIEW

File: daemon/cmd/daemon.go [hunk 1]
```diff
@@ -506,7 +506,7 @@ func NewDaemon(ctx context.Context, cancel context.CancelFunc, epMgr *endpointma
 	}
 
 	if option.Config.EnableIPv4EgressGateway {
-		d.egressGatewayManager = egressgateway.NewEgressGatewayManager(&d)
+		d.egressGatewayManager = egressgateway.NewEgressGatewayManager(&d, d.identityAllocator)
```
Comment (Weil0ng) [inline daemon/cmd/daemon.go:577]: A bit curious, is this identityAllocator local to the node? Or does it also store labels for identities created on remote nodes?

Comment (blzhao-0) [reply daemon/cmd/daemon.go:577]: It's a caching allocator that has both global and local identities. Details:
https://github.com/cilium/cilium/blob/master/pkg/identity/cache/allocator.go#L69
When looking up, it prefers the local cache.

Comment (Weil0ng) [reply daemon/cmd/daemon.go:577]: it says it is from the kvstore: https://github.com/cilium/cilium/blob/master/pkg/identity/cache/allocator.go#L71 which got me thinking is the "global" cache used when kvstore is CRD mode?

Comment (blzhao-0) [reply daemon/cmd/daemon.go:577]: Yes i think it uses both global and local cache. For example when looking by ID, here it looks through the local identities first: https://github.com/cilium/cilium/blob/82c742f2e9fb65fb3fc392c7dcb3b4e22b69c650/pkg/identity/cache/cache.go#L281

Comment (Weil0ng) [reply daemon/cmd/daemon.go:577]: I see, makes sense, thanks for the pointers!

**Review by Weil0ng — APPROVED** [review]

File: pkg/egressgateway/manager.go [hunk 2]
```diff
@@ -39,21 +45,40 @@ type Manager struct {
 
 	// epDataStore stores endpointId to endpoint metadata mapping
 	epDataStore map[endpointID]*endpointMetadata
+
+	identityAllocator identityCache.IdentityAllocator
```
Comment (jibi) [inline pkg/egressgateway/manager.go:50]: Could you add a comment documenting the field please?

File: pkg/egressgateway/manager.go [hunk 3]
```diff
@@ -39,21 +45,40 @@ type Manager struct {
...
 
 	return manager
 }
 
+// getIdentityLabels waits for the global identities to be populated to the cache,
+// then looks up identity by ID from the cached identity allocator and return its labels.
+func (manager *Manager) getIdentityLabels(securityIdentity uint32) (labels.Labels, error) {
+	identityCtx, cancel := context.WithTimeout(context.Background(), option.Config.KVstoreConnectivityTimeout)
+	defer cancel()
+	if err := manager.identityAllocator.WaitForInitialGlobalIdentities(identityCtx); err != nil {
```
Comment (jibi) [inline pkg/egressgateway/manager.go:72]: This looks like an initialization step, should it be moved in `NewEressGatewayManager()`?

File: pkg/egressgateway/manager_privileged_test.go [hunk 4]
```diff
@@ -180,18 +191,22 @@ func newEgressPolicyConfig(policyName string, labels map[string]string, destinat
 	}
 }
 
-func newEndpoint(name, ip string, labels map[string]string) k8sTypes.CiliumEndpoint {
+func newEndpoint(name, ip string, eplb map[string]string) k8sTypes.CiliumEndpoint {
```
Comment (jibi) [inline pkg/egressgateway/manager_privileged_test.go]:
```suggestion
func newEndpoint(name, ip string, epLabels map[string]string) k8sTypes.CiliumEndpoint {
```

File: pkg/egressgateway/manager_privileged_test.go [hunk 5]
```diff
@@ -180,18 +191,22 @@ func newEgressPolicyConfig(policyName string, labels map[string]string, destinat
...
 	epLabels := []string{}
-	for k, v := range labels {
+	for k, v := range eplb {
+		//epLabels = append(epLabels, fmt.Sprintf("k8s:%s=%s", k, v))
+		// Not sure about this, probably not need the "k8s:"" prefix
 		epLabels = append(epLabels, fmt.Sprintf("k8s:%s=%s", k, v))
 	}
 
+	id, _, _ := identityAllocator.AllocateIdentity(context.Background(), labels.Map2Labels(eplb, "k8s"), true)
```
Comment (jibi) [inline pkg/egressgateway/manager_privileged_test.go]:
```suggestion
	id, _, _ := identityAllocator.AllocateIdentity(context.Background(), labels.Map2Labels(epLabels, labels.LabelSourceK8s), true)
```

File: pkg/egressgateway/manager_privileged_test.go [hunk 6]
```diff
@@ -180,18 +191,22 @@ func newEgressPolicyConfig(policyName string, labels map[string]string, destinat
 	}
 }
 
-func newEndpoint(name, ip string, labels map[string]string) k8sTypes.CiliumEndpoint {
+func newEndpoint(name, ip string, eplb map[string]string) k8sTypes.CiliumEndpoint {
 	epLabels := []string{}
-	for k, v := range labels {
+	for k, v := range eplb {
+		//epLabels = append(epLabels, fmt.Sprintf("k8s:%s=%s", k, v))
+		// Not sure about this, probably not need the "k8s:"" prefix
```
Comment (jibi) [inline pkg/egressgateway/manager_privileged_test.go]: I think it's fine to keep the prefix and then use it in `Map2Labels()`

**Review by jibi — COMMENTED** [review]
Thanks for the fix! I did a first pass and it looks good (mostly nits) but unit tests are failing :thinking: 
```
➜  egressgateway git:(ade8a23571) sudo go test . -count=1 -tags=privileged_tests
level=info msg="Detected mounted BPF filesystem at /sys/fs/bpf" subsys=bpf
level=info msg="Added CiliumEgressNATPolicy" ciliumEgressNATPolicyName=policy-1 subsys=egressgateway
level=info msg="Egress gateway policy applied" destinationCIDR="{1.1.1.0 ffffff00}" egressIP=192.168.101.1 gatewayIP=192.168.101.1 sourceIP=10.0.0.1 subsys=egressgateway
level=info msg="Egress gateway policy removed" destinationCIDR=1.1.1.0/24 sourceIP=10.0.0.1 subsys=egressgateway

----------------------------------------------------------------------
FAIL: manager_privileged_test.go:95: EgressGatewayTestSuite.TestEgressGatewayManager

manager_privileged_test.go:135:
    assertEgressRules(c, []egressRule{
        {ep1IP, destCIDR, egressIP1, egressIP1},
    })
manager_privileged_test.go:258:
    c.Assert(err, IsNil)
... value *fmt.wrapError = &fmt.wrapError{msg:"lookup: key does not exist", err:(*sys.syscallError)(0xc00000e8d0)} ("lookup: key does not exist")

OOPS: 0 passed, 1 FAILED
--- FAIL: Test (0.16s)
FAIL
FAIL	github.com/cilium/cilium/pkg/egressgateway	0.183s
FAIL
```

**Comment by jibi** [comment]
I think this https://github.com/cilium/cilium/blob/8b790625a4c035e59b0e47c182612464cbdd4250/test/k8s/egress.go#L90-L93 should also be removed

File: pkg/egressgateway/manager.go (hunk 3 above)
Comment (anfernee) [reply pkg/egressgateway/manager.go:72]: As Gilberto suggested, or use `atomic.once`. Make sure it's not called every time `getIdentityLabels` is called.

File: pkg/egressgateway/manager.go (hunk 2 above)
Comment (blzhao-0) [reply pkg/egressgateway/manager.go:50]: Done.

File: pkg/egressgateway/manager.go (hunk 3 above)
Comment (blzhao-0) [reply pkg/egressgateway/manager.go:72]: @jibi this is called in the EndpointUpdate callback, so no good place to relocate the wait. It only needs to be done for the very first time. So I wrapped it in a sync.once.

File: pkg/egressgateway/manager_privileged_test.go (hunk 4 above)
Comment (blzhao-0) [reply pkg/egressgateway/manager_privileged_test.go]: Done.

File: pkg/egressgateway/manager_privileged_test.go (hunk 5 above)
Comment (blzhao-0) [reply pkg/egressgateway/manager_privileged_test.go]: Done.

File: pkg/egressgateway/manager_privileged_test.go (hunk 6 above)
Comment (blzhao-0) [reply pkg/egressgateway/manager_privileged_test.go]: Cool. This part of the code is refactored. Thx.

**Comment by blzhao-0** [comment]
> Thanks for the fix! I did a first pass and it looks good (mostly nits) but unit tests are failing 🤔
> 
> ```
> ➜  egressgateway git:(ade8a23571) sudo go test . -count=1 -tags=privileged_tests
> level=info msg="Detected mounted BPF filesystem at /sys/fs/bpf" subsys=bpf
> level=info msg="Added CiliumEgressNATPolicy" ciliumEgressNATPolicyName=policy-1 subsys=egressgateway
> level=info msg="Egress gateway policy applied" destinationCIDR="{1.1.1.0 ffffff00}" egressIP=192.168.101.1 gatewayIP=192.168.101.1 sourceIP=10.0.0.1 subsys=egressgateway
> level=info msg="Egress gateway policy removed" destinationCIDR=1.1.1.0/24 sourceIP=10.0.0.1 subsys=egressgateway
> 
> ----------------------------------------------------------------------
> FAIL: manager_privileged_test.go:95: EgressGatewayTestSuite.TestEgressGatewayManager
> 
> manager_privileged_test.go:135:
>     assertEgressRules(c, []egressRule{
>         {ep1IP, destCIDR, egressIP1, egressIP1},
>     })
> manager_privileged_test.go:258:
>     c.Assert(err, IsNil)
> ... value *fmt.wrapError = &fmt.wrapError{msg:"lookup: key does not exist", err:(*sys.syscallError)(0xc00000e8d0)} ("lookup: key does not exist")
> 
> OOPS: 0 passed, 1 FAILED
> --- FAIL: Test (0.16s)
> FAIL
> FAIL	github.com/cilium/cilium/pkg/egressgateway	0.183s
> FAIL
> ```

This is broken because we switched to the ID to look for labels, therefore the old "edit-in-place" for endpoint update is not working anymore. I fixed it by writing a mock for endpoint and ID creation/update to keep them in sync in the test.

Also updated the test results in the description.

**Comment by blzhao-0** [comment]
> I think this
> 
> https://github.com/cilium/cilium/blob/8b790625a4c035e59b0e47c182612464cbdd4250/test/k8s/egress.go#L90-L93
> 
> should also be removed

This is Done. Thanks.

File: test/k8s/egress.go [hunk 7]
```diff
@@ -88,8 +88,6 @@ var _ = SkipDescribeIf(func() bool {
 		// different configurations for the tests.
 		ciliumFilename = helpers.TimestampFilename("cilium.yaml")
 		DeployCiliumOptionsAndDNS(kubectl, ciliumFilename,
```
Comment (jibi) [inline test/k8s/egress.go]:
```suggestion
		DeployCiliumAndDNS(kubectl, ciliumFilename)
```

(i.e. we should stop setting `enableCiliumEndpointSlice=false` in the configmap)

File: pkg/egressgateway/manager_privileged_test.go [hunk 8]
```diff
@@ -199,7 +202,19 @@ func newEndpoint(name, ip string, labels map[string]string) k8sTypes.CiliumEndpo
...
-	}
+	}, id
+}
+
+// Mock the update of endpoint and its corresponding identity, with new labels. Returns new ID.
+func updateEndpointAndIdentity(endpoint *k8sTypes.CiliumEndpoint, oldID *identity.Identity, newEpLabels map[string]string) *identity.Identity {
+	ctx := context.Background()
+
+	identityAllocator.Release(ctx, oldID, true)
+	fmt.Printf("Released old ID:  %v\n", *oldID)
```
Comment (jibi) [inline pkg/egressgateway/manager_privileged_test.go]: Leftovers?

File: pkg/egressgateway/manager_privileged_test.go [hunk 9]
```diff
@@ -199,7 +202,19 @@ func newEndpoint(name, ip string, labels map[string]string) k8sTypes.CiliumEndpo
...
+	newID, _, _ := identityAllocator.AllocateIdentity(ctx, labels.Map2Labels(newEpLabels, labels.LabelSourceK8s), true)
+	fmt.Printf("Allocated new ID:  %v\n", *newID)
```
Comment (jibi) [inline pkg/egressgateway/manager_privileged_test.go]: (ditto)

File: pkg/egressgateway/manager.go [hunk 10]
```diff
@@ -39,21 +46,45 @@ type Manager struct {
...
 	return manager
 }
 
+// getIdentityLabels waits for the global identities to be populated to the cache,
+// then looks up identity by ID from the cached identity allocator and return its labels.
+func (manager *Manager) getIdentityLabels(securityIdentity uint32) (labels.Labels, error) {
+	identityCtx, cancel := context.WithTimeout(context.Background(), option.Config.KVstoreConnectivityTimeout)
+	defer cancel()
+
+	var once sync.Once
```
Comment (jibi) [inline pkg/egressgateway/manager.go]: I think the `once` variable should be declared outside of the function, otherwise we are going to execute the callback passed to `once.Do()` every time anyone (while at it we could also rename it to `InitGlobalIdentitiesOnce` or something like that)

File: test/k8s/egress.go (hunk 7 above)
Comment (blzhao-0) [reply test/k8s/egress.go]: Fixed. Thx~

File: pkg/egressgateway/manager_privileged_test.go (hunk 8 above)
Comment (blzhao-0) [reply pkg/egressgateway/manager_privileged_test.go]: Removed.

File: pkg/egressgateway/manager_privileged_test.go (hunk 9 above)
Comment (blzhao-0) [reply pkg/egressgateway/manager_privileged_test.go]: Removed.

File: pkg/egressgateway/manager.go (hunk 10 above)
Comment (blzhao-0) [reply pkg/egressgateway/manager.go]: My bad.. This is fixed.

**Comment by jibi** [comment]
/test-1.23-net-next

**Comment by blzhao-0** [comment]
@jibi @Weil0ng I saw some testing failures (gke-stable (test-gke)) related to this PR, could u confirm if this is due to CES being enabled or infra?
```
03:52:42  [Fail] K8sFQDNTest [BeforeEach] Restart Cilium validate that FQDN is still working 
03:52:42  /home/jenkins/workspace/Cilium-PR-K8s-GKE@3/src/github.com/cilium/cilium/test/k8s/fqdn.go:78
03:52:42  
03:52:42  [Fail] K8sFQDNTest [BeforeEach] Validate that multiple specs are working correctly 
03:52:42  /home/jenkins/workspace/Cilium-PR-K8s-GKE@3/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:647
03:52:42  
03:52:42  [Fail] K8sFQDNTest [BeforeEach] Validate that FQDN policy continues to work after being updated 
03:52:42  /home/jenkins/workspace/Cilium-PR-K8s-GKE@3/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:647
03:52:42  
03:52:42  Ran 42 of 375 Specs in 5019.583 seconds
03:52:42  FAIL! -- 39 Passed | 3 Failed | 0 Pending | 333 Skipped
```

**Comment by jibi** [comment]
> could u confirm if this is due to CES being enabled or infra?

The failure looks unrelated/like a flake, I restarted the test

File: pkg/egressgateway/manager.go [hunk 11]
```diff
@@ -39,21 +48,44 @@ type Manager struct {
...
 
+// getIdentityLabels waits for the global identities to be populated to the cache,
+// then looks up identity by ID from the cached identity allocator and return its labels.
+func (manager *Manager) getIdentityLabels(securityIdentity uint32) (labels.Labels, error) {
+	identityCtx, cancel := context.WithTimeout(context.Background(), option.Config.KVstoreConnectivityTimeout)
+	defer cancel()
+
+	waitForIdentityCacheOnce.Do(func() {
+		if err := manager.identityAllocator.WaitForInitialGlobalIdentities(identityCtx); err != nil {
+			log.WithError(err).Error("Failed to wait for initial global identities.")
```
Comment (jibi) [inline pkg/egressgateway/manager.go]: Unfortunately with this approach we are going to ignore any error returned by `WaitForInitialGlobalIdentities()` :disappointed: 

I checked internally and in the end it's fine to keep calling `WaitForInitialGlobalIdentities()` each time, so we should go back to the original approach and just get rid of the `waitForIdentityCacheOnce.Do()` (apologies for the back and forth on this change :pray:)

**Comment by jibi** [comment]
/test-1.23-net-next

**Comment by jibi** [comment]
/test-1.23-net-next

File: pkg/egressgateway/manager.go (hunk 3 above)
Comment (blzhao-0) [reply pkg/egressgateway/manager.go:72]: This can remain as is. Resolving.

File: pkg/egressgateway/manager.go (hunk 11 above)
Comment (blzhao-0) [reply pkg/egressgateway/manager.go]: Yeah I see what you meant.
NP, this is reverted back to 1st version.

File: pkg/egressgateway/manager.go [hunk 12]
```diff
@@ -4,20 +4,29 @@
...
 	"github.com/cilium/cilium/pkg/logging"
 	"github.com/cilium/cilium/pkg/logging/logfields"
 	"github.com/cilium/cilium/pkg/maps/egressmap"
+	"github.com/cilium/cilium/pkg/option"
 )
 
 var (
 	log = logging.DefaultLogger.WithField(logfields.LogSubsys, "egressgateway")
+
+	waitForIdentityCacheOnce sync.Once
```
Comment (jibi) [inline pkg/egressgateway/manager.go]: This should also be removed

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
/test-1.23-net-next

**Comment by jibi** [comment]
/test-1.23-net-next

File: pkg/egressgateway/manager.go (hunk 12 above)
Comment (blzhao-0) [reply pkg/egressgateway/manager.go]: my bad. removed.

**Comment by pchaigno** [comment]
All tests (including [net-next](https://jenkins.cilium.io/view/PR/job/Cilium-PR-K8s-1.23-kernel-net-next/1043/)) were passing before [the small push](https://github.com/cilium/cilium/compare/64ca212771b3cdb855deca1e04d6ab823f03d9d4..43ce1429e70e5b433fd3ff473c134fbc90475f34) to address @jibi's feedback, so I think we're good to merge once @jibi approves.

**Review by jibi — APPROVED** [review]
