### PR TITLE
CLI: set json output as default for cilium get endpoint

### LINKED ISSUE #29247: cilium get endpoint fails with "Failed to decode nested JSON"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Running `cilium get endpoint <id>` results in:
```
Error: Failed to decode nested JSON: invalid character 'M' looking for beginning of object key string (
{MatchLabels:map[string]string{k8s.foo: bar,k8s.io.kubernetes.pod.namespace: default,},MatchExpressions:[]LabelSelectorRequirement{},}
)
```

If using `yaml` output, it's fine.

### Cilium Version

Client: 1.14.4 87dd2b64 2023-11-09T15:02:52-05:00 go version go1.20.11 linux/amd64
Daemon: 1.14.4 87dd2b64 2023-11-09T15:02:52-05:00 go version go1.20.11 linux/amd64

### Kernel Version

5.15.0-1049-aws #54~20.04.1-Ubuntu SMP Fri Oct 6 22:04:33 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.24.17-eks-4f4795d

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by saiaunghlyanhtet**
Set json output as default for cilium get endpoint

Fixes: #29247 

```release-note
Set json output as default for `cilium-dbg endpoint get`
```

### CODE REVIEW

File: cilium-dbg/cmd/endpoint_get.go [hunk 1]
```diff
@@ -55,21 +52,13 @@ var endpointGetCmd = &cobra.Command{
 				os.Exit(1)
 			}
 			return
+		} else {
```
Comment (joestringer) [inline cilium-dbg/cmd/endpoint_get.go]: Probably we can remove the `command.OutputOption` conditional check as well since both cases are running the same code.

Comment (saiaunghlyanhtet) [reply cilium-dbg/cmd/endpoint_get.go]: Made changes as requested.

**Review by joestringer — APPROVED** [review]

**Comment by saiaunghlyanhtet** [comment]
@joestringer, do I need to rebase for some failing CI checks?

**Comment by joestringer** [comment]
@saiaunghlyanhtet At a glance, the failures do not look related to this change. I've retriggered the failed jobs.

File: cilium-dbg/cmd/endpoint_get.go [hunk 2]
```diff
@@ -50,26 +47,10 @@ var endpointGetCmd = &cobra.Command{
 			endpointInst = append(endpointInst, result)
 		}
 
-		if command.OutputOption() {
```
Comment (tommyp1ckles) [inline cilium-dbg/cmd/endpoint_get.go:53]: Why do we need to remove plaintext output?  Isn't this still useful for debugging to have the human readable format?

**Review by tommyp1ckles — CHANGES_REQUESTED** [review]

**Review by tommyp1ckles — APPROVED** [review]

**Comment by tommyp1ckles** [comment]
ignore my previous comment, misunderstood the commit.  Change looks good 😄

**Comment by joestringer** [comment]
@tommyp1ckles FWIW if we decide to create an actual text format for this, that would be an alternative. But since the default output currently is just trying to create a single flattened JSON object (but failing on the way), I figured it's easier to just reduce the scope to always generate JSON for now.

**Comment by julianwiedmann** [comment]
I'm seeing CI failures that have been resolved in latest `main`. Rebasing.

**Comment by julianwiedmann** [comment]
@saiaunghlyanhtet [this CI failure](https://github.com/cilium/cilium/actions/runs/12714070955/job/35445140715#step:19:809) is robust, and looks genuine. Maybe something in the ginkgo tests is parsing the output, and observes changed behavior?

**Comment by saiaunghlyanhtet** [comment]
> @saiaunghlyanhtet [this CI failure](https://github.com/cilium/cilium/actions/runs/12714070955/job/35445140715#step:19:809) is robust, and looks genuine. Maybe something in the ginkgo tests is parsing the output, and observes changed behavior?

I found the problem. I think that the ginko tests are not parsing any output. The problem is like the following:

First, we call CiliumEndpointIPv6 here (https://github.com/cilium/cilium/blob/f2c7fe00938c93d0b554abfffdb1b9157c2b3ae1/test/k8s/datapath_configuration.go#L430), which use "cilium-dbg endpoint get" command with -o jsonpath= (https://github.com/cilium/cilium/blob/f2c7fe00938c93d0b554abfffdb1b9157c2b3ae1/test/helpers/kubectl.go#L2827). But, the current fix to setting JSON output as default for cilium-dbg endpoint does not work with -o jsonpath. So, it returns a long json instead of endpoint IPv6s. So, in that way, the test failed.

File: cilium-dbg/cmd/endpoint_get.go (hunk 2 above)
Comment (joestringer) [inline cilium-dbg/cmd/endpoint_get.go]: Is this deleted code what is supporting `-o jsonpath`? Maybe you could try not deleting this conditional statement (+ contents) and then test that `-o jsonpath` works like in the test case.

Comment (saiaunghlyanhtet) [reply cilium-dbg/cmd/endpoint_get.go]: I changed the code to the situation in which if there is an output option, the response will be in that output option, but if there is no output option, we will get the JSON output as default.

**Comment by joestringer** [comment]
I closed and re-opened the PR because some image builds failed when you uploaded, most likely due to infrastructure issues. I'll retrigger the test that was failing to confirm whether you have fixed the issue.

**Comment by saiaunghlyanhtet** [comment]
3 still failing but as far as I checked, they are not related to the changes in this PR.

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
Nominating for v1.17 backport to address problems where users can't get cilium endpoints via local CLI.
