### PR TITLE
cilium: hostport service map fixes

### LINKED ISSUE #12116: Cilium native hostport only listens on a internal IP, unlike CNI portmap
## Bug report

Cilium v1.8 release candidates include a native bpf hostport feature to replace CNI [portmap](https://github.com/containernetworking/plugins/tree/master/plugins/meta/portmap) chaining ([#10359](https://github.com/cilium/cilium/issues/10359)) implemented in https://github.com/cilium/cilium/pull/10592. In testing, it seems this feature is a partial implementation of CNI portmap.

When CNI portmap is used in a CNI conflist (with any CNI provider, not just Cilium), Kubernetes Pods that set a hostPort proxy any traffic on that host port to the container.

```
          ports:
            - name: http
              containerPort: 80
              hostPort: 80
```

For example, a PodSpec above would allow the web app to be accessed via multiple host IPs - hostPort maps multiple interface addresses (unless a single hostIP is set https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#containerport-v1-core).

```
curl 127.0.0.1:80  (works)
curl 10.135.173.170:80 (works)
curl publicipv4:80 (works)
curl [someipv6]:80 (depends)
```

In Cilium v1.8.0-rc3 the hostport feature works as described in docs, but its always picking the node's own internal IP, which doesn't satisfy the use cases CNI portmap had.

```
curl 127.0.0.1:80  (no)
curl 10.135.173.170:80 (works)
curl publicipv4:80 (no)
curl [someipv6]:80 (no)
```

```
cilium service list
...
13   10.135.173.170:80      HostPort       1 => 10.2.0.214:80
```

So its not a bug per-se, more that the implementation isn't a drop-in for CNI portmap yet, unless the node's internal IP is the only address you are interested in. (imo) Most uses of CNI portmap to support containers with hostPort are using it to listen on any of the available host addresses.

* node with a private IP (kubelet internal IP, tunnels) and public IP (interfacing with LBs)
* health checks may expect the hostPort to be available on 127.0.0.1 or ::1 as well
* node with multiple addresses for other reasons

For myself, I have to fallback to certain pods that could use hostPort to just using full hostNetwork.

**General Information**

- Cilium version: 1.8.0-rc3
- Kernel version: 5.6.11
- Orchestration system version: Kubernetes v1.18.3

### PR DESCRIPTION
**Pull request by borkmann**
See commit msg; targeted for 1.8.2.

Fixes: #12116

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-focus K8sService*

**Comment by borkmann** [comment]
test-focus K8sService*

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
(all tested & working as expected, ready for review)

**Comment by borkmann** [comment]
retest-4.9

**Comment by borkmann** [comment]
retest-runtime

**Comment by borkmann** [comment]
retest-4.19

**Comment by borkmann** [comment]
retest-net-next

**Comment by borkmann** [comment]
test-me-please

File: bpf/bpf_sock.c [hunk 1]
```diff
@@ -268,6 +271,12 @@ static __always_inline int __sock4_xlate_fwd(struct bpf_sock_addr *ctx,
 		svc = sock4_wildcard_lookup(&key, true, false, in_hostns);
 		if (svc && !lb4_svc_is_nodeport(svc))
 			svc = NULL;
+		if (!svc) {
+			svc = sock4_wildcard_lookup(&key, false, true,
+						    in_hostns);
+			if (svc && !lb4_svc_is_hostport(svc))
+				svc = NULL;
+		}
```
Comment (pchaigno) [inline bpf/bpf_sock.c]: Maybe worth refactoring code a bit here by introducing a function for the two lookups? Same for the two cases in IPv6 case.

File: bpf/lib/lb.h [hunk 2]
```diff
@@ -215,37 +215,33 @@ bool lb6_svc_is_affinity(const struct lb6_service *svc)
...
 {
-	return svc->flags & svc_is_routable_mask();
+	return (svc->flags & svc_is_routable_mask()) > SVC_FLAG_ROUTABLE;
 }
 
 static __always_inline
 bool lb6_svc_is_routable(const struct lb6_service *svc)
 {
-	return svc->flags & svc_is_routable_mask();
+	return (svc->flags & svc_is_routable_mask()) > SVC_FLAG_ROUTABLE;
```
Comment (pchaigno) [inline bpf/lib/lb.h]: Why do we even need to distinguish between IPv4 and IPv6 here? Couldn't we pass `svc->flags` or `svc` to `svc_is_routable_mask()` and used that for both cases?

File: pkg/k8s/watchers/pod.go [hunk 3]
```diff
@@ -314,32 +314,32 @@ func (k *K8sWatcher) deleteK8sPodV1(pod *slim_corev1.Pod) error {
...
 				continue
 			}
-			feIP := net.ParseIP(p.HostIP)
-			if feIP == nil {
-				feIP = net.ParseIP(pod.Status.HostIP)
+
+			if int(p.HostPort) >= option.Config.NodePortMin &&
+				int(p.HostPort) <= option.Config.NodePortMax {
+				logger.Warningf("The requested hostPort %d is colliding with the configured NodePort range [%d, %d]. Ignoring.",
+					p.HostPort, option.Config.NodePortMin, option.Config.NodePortMax)
```
Comment (pchaigno) [inline pkg/k8s/watchers/pod.go:331]: This is a new constraint, right? Do we need a note in upgrade guide for this?

File: pkg/k8s/watchers/pod.go [hunk 4]
```diff
@@ -350,18 +350,98 @@ func genServiceMappings(pod *slim_corev1.Pod, podIPs []string) []loadbalancer.SV
 						},
 					},
 				}
-				bes = append(bes, be)
+				if be.L3n4Addr.IP.To4() != nil {
+					bes4 = append(bes4, be)
+				} else {
+					bes6 = append(bes6, be)
```
Comment (pchaigno) [inline pkg/k8s/watchers/pod.go:356]: I don't understand why `bes` and `fes` need to be broken into IPv4 and IPv6 cases.
Is that to be able to return only IPv4 service mappings if IPv4 is enabled (resp. IPv6)? If that's it, maybe a single slice for both cases would be enough and you could only append to it if IPv4 is enabled (resp. IPv6); you check the address type here anyway.

**Review by pchaigno — APPROVED** [review]
Mostly refactoring nits on my side. LGTM otherwise, but I'm not very familiar with this code and even less with the Kubernetes implication.

File: pkg/k8s/watchers/pod.go (hunk 3 above)
Comment (borkmann) [reply pkg/k8s/watchers/pod.go:331]: I've added it to the kube-proxy free GSG doc as limitation in the PR. I don't think that anyone would add a hostport in the nodeport range since this is rather broken given k8s would allocate ports for NodePort services in there and then the two would interfere with each other.

File: pkg/k8s/watchers/pod.go (hunk 4 above)
Comment (borkmann) [reply pkg/k8s/watchers/pod.go:356]: I didn't have it before when it was wip and what happened was basically that I've been adding v6 frontends with v4 backends. We're not there yet until we have nat64 service support.

File: bpf/lib/lb.h (hunk 2 above)
Comment (borkmann) [reply bpf/lib/lb.h]: There is no need to distinguish, I can add a inline helper `lb_svc_is_routable()` where both pass in `svc->flags`, not sure if it's really worth it but at least the logic would be in a single location.

File: bpf/bpf_sock.c (hunk 1 above)
Comment (borkmann) [reply bpf/bpf_sock.c]: Makes sense, I'll check if we can do something reasonable wrt refactoring.

**Comment by borkmann** [comment]
(all checks green)

File: bpf/bpf_sock.c (hunk 1 above)
Comment (borkmann) [reply bpf/bpf_sock.c]: Pushed, I think look much better now.

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
(ignoring checkpatch in this case since line goes over ~85 chars)

File: pkg/k8s/watchers/pod.go [hunk 5]
```diff
@@ -314,32 +314,32 @@ func (k *K8sWatcher) deleteK8sPodV1(pod *slim_corev1.Pod) error {
...
-						Protocol: proto,
-						Port:     uint16(p.HostPort),
-					},
-				},
-				ID: loadbalancer.ID(0),
-			}
-			bes := make([]loadbalancer.Backend, 0, len(podIPs))
+
+			bes4 := make([]loadbalancer.Backend, 0, len(podIPs))
+			bes6 := make([]loadbalancer.Backend, 0, len(podIPs))
```
Comment (aanm) [inline pkg/k8s/watchers/pod.go:341]: We are unnecessarily allocating more memory than we really need here. `bes6` won't have `len(podIPs)` if all backends are a v4 for example.

File: pkg/k8s/watchers/pod.go [hunk 6]
```diff
@@ -350,18 +350,98 @@ func genServiceMappings(pod *slim_corev1.Pod, podIPs []string) []loadbalancer.SV
...
+			if option.Config.EnableIPv6 && len(bes6) > 0 {
+				for _, fe6 := range fes6 {
+					svcs = append(svcs,
+						loadbalancer.SVC{
+							Frontend:      fe6,
+							Backends:      bes6,
+							Type:          loadbalancer.SVCTypeHostPort,
+							TrafficPolicy: loadbalancer.SVCTrafficPolicyCluster,
+						})
+				}
```
Comment (aanm) [inline pkg/k8s/watchers/pod.go:443]: This can been simplified as:
```
			// When HostIP is explicitly set, then we need to expose *only*
			// on this address but not via other addresses. When it's not set,
			// then expose via all local addresses. Same when the user provides
			// an unspecified address (0.0.0.0 / [::]).
			feIP := net.ParseIP(p.HostIP)
			var nodeAddrAll [][]net.IP
			if feIP != nil && !feIP.IsUnspecified() {
				// Migrate the loopback address into a 0.0.0.0 / [::]
				// surrogate, thus internal datapath handling can be
				// streamlined. It's not exposed for traffic from outside.
				if feIP.IsLoopback() {
					if feIP.To4() != nil {
						feIP = net.IPv4zero
					} else {
						feIP = net.IPv6zero
					}
				}
				nodeAddrAll = [][]net.IP{
					{feIP},
				}
			} else {
				nodeAddrAll = [][]net.IP{
					k.K8sSvcCache.GetNodeAddressing().IPv4().LoadBalancerNodeAddresses(),
					k.K8sSvcCache.GetNodeAddressing().IPv6().LoadBalancerNodeAddresses(),
				}
			}
			for _, addrs := range nodeAddrAll {
				for _, ip := range addrs {
					fe := loadbalancer.L3n4AddrID{
						L3n4Addr: loadbalancer.L3n4Addr{
							IP: ip,
							L4Addr: loadbalancer.L4Addr{
								Protocol: proto,
								Port:     uint16(p.HostPort),
							},
							Scope: loadbalancer.ScopeExternal,
						},
						ID: loadbalancer.ID(0),
					}

					// We don't have the node name available here, but in any
					// case in the BPF data path we drop any potential non-local
					// backends anyway (which should never exist in the first
					// place), hence we can just leave it at Cluster policy.
					if fe.L3n4Addr.IP.To4() != nil {
						if option.Config.EnableIPv4 && len(bes4) > 0 {
							svcs = append(svcs,
								loadbalancer.SVC{
									Frontend:      fe,
									Backends:      bes4,
									Type:          loadbalancer.SVCTypeHostPort,
									TrafficPolicy: loadbalancer.SVCTrafficPolicyCluster,
								})
						}
					} else {
						if option.Config.EnableIPv6 && len(bes6) > 0 {
							svcs = append(svcs,
								loadbalancer.SVC{
									Frontend:      fe,
									Backends:      bes6,
									Type:          loadbalancer.SVCTypeHostPort,
									TrafficPolicy: loadbalancer.SVCTrafficPolicyCluster,
								})
						}
					}
				}
			}
```
