### PR TITLE
ipcache: fix flapping labels in SelectorCache when reserved:host identity has multiple IPs

### LINKED ISSUE #28259: "kube-apiserver" policy entity is broken on dual-stack clusters
### What happened?

A bug happened!

The mechanism that applies the `kube-apiserver` label can cause flaps when the IP in question belongs to the local node. This only applies to clusters where nodes have ipv6 addresses. (Note that whether or not Cilium is in dual-stack mode is irrelevant).

The root cause is somewhat complicated due to the number of special cases:

1. the ipcache "back-propagates" labels up to a global value only for the local identity.
2. the `default/kubernetes` service is always single-stack, even for dual-stack clusters
3. the node-manager doesn't understand the kube-apsierver identity; it is applied purely to IPs in the ipcache metadata layer.

So when there are multiple IPs for the `reserved:node` identity, but their set of labels is not uniform, it is last-write-wins. Whichever IP is most recently triggered will have those labels applied to the `reserved:node` identity.

### Cilium Version

v1.14 at least, perhaps older.

Edit: See https://github.com/cilium/cilium/issues/28259#issuecomment-1746489439.

### PR DESCRIPTION
**Pull request by squeed**
The `reserved:host` identity is special: the numeric identity is fixed and the set of labels is mutable. (The datapath requires this.) So, we need to determine all prefixes that have the `reserved:host` label and capture their labels. Then, we must aggregate *all* labels from all IPs and insert them as the `reserved:host` identity labels.

However, the code as written has a race condition whenever the local node has more than one IP address. This can happen when, for example vxlan or ipv6 is enabled. The basic sequence is this:

1. Insert IP A as `reserved:host` in to the ipcache. ID 1 now has labels `reserved:host`
2. Insert IP A as `reserved:kube-apiserver` in to the ipcache. ID 1 is updated with labels labels `reserved:host, reserved:kube-apsierver`
3. Insert IP B as `reserved:host` in to the ipcache. ID 1 is updated with labels `reserved:host`
And now policies are broken.

Likewise, we need to always update the SelectorCache; we cannot short-circuit if the ipcache already has that identity. Again, this is needed because the identity is mutable. So this bug can take another form:

1. Insert IP A as `reserved:host` in to the ipcache. Because IP A is not known to the ipcache, treat ID 1 as a new identity and update the selector cache
2. Insert IP A as `reserved:kube-apiserver`. Mutate the labels of ID 1. But, because IP A already has ID 1, short-circuit the update to the selector cache (if the Source is the same, which it _may_ be).
3. Now the selector cache has incorrect labels for ID 1.

Without this, when there are multiple IPs with the host label, the identity may flap and the SelectorCache may be missing updates.

Fixes: #28259
Fixes: b099ba614
Fixes: f5d95325c

### CODE REVIEW

**Comment by nathanjsweet** [comment]
Additional CI for "pod-to-node-policycidr" test: https://github.com/cilium/cilium/pull/28334.

**Comment by christarazi** [comment]
> Without this, when there are multiple IPs with the host label, the identity may flap and the SelectorCache may be missing updates.

I'm having trouble understanding this and without understanding, it's difficult to review the PR. Could you go into more detail and also provide an example?

**Comment by nathanjsweet** [comment]
[This test](https://github.com/cilium/cilium/actions/runs/6353246315/job/17322728953) keeps failing, but when I run it locally, it passes. I'm going to rerun it a few more times, because the error is simply one of the test pods not coming up.

File: pkg/ipcache/metadata.go [hunk 1]
```diff
@@ -81,12 +81,21 @@ type metadata struct {
 	// generate updates into the ipcache, policy engine and datapath.
 	queuedChangesMU lock.Mutex
 	queuedPrefixes  map[netip.Prefix]struct{}
+
+	// reservedHostLock protects the localHostLabels map
```
Comment (schlosna) [inline pkg/ipcache/metadata.go]:
```suggestion
	// reservedHostLock protects the reservedHostLabels map
```

File: pkg/ipcache/metadata.go [hunk 2]
```diff
@@ -511,6 +538,33 @@ func (ipc *IPCache) resolveIdentity(ctx context.Context, prefix netip.Prefix, in
...
+		ipc.metadata.reservedHostLabels[prefix] = lbls
+	}
+
+	// aggregate all labels and update static identity
+	newLabels := labels.Labels{}
+	for _, l := range ipc.metadata.reservedHostLabels {
+		newLabels.MergeLabels(l)
+	}
+
+	log.WithField(logfields.Labels, newLabels).Debug("Merged labels for reserved:host identity")
```
Comment (schlosna) [inline pkg/ipcache/metadata.go]: Should this be pulled out to a separate function to allow releasing the lock to reduce critical section and possible contention before adding and looking up identity?

File: pkg/ipcache/metadata.go [hunk 3]
```diff
@@ -511,6 +538,33 @@ func (ipc *IPCache) resolveIdentity(ctx context.Context, prefix netip.Prefix, in
...
+
+	identity.AddReservedIdentityWithLabels(identity.ReservedIdentityHost, newLabels)
+	return identity.LookupReservedIdentity(identity.ReservedIdentityHost)
+}
```
Comment (schlosna) [inline pkg/ipcache/metadata.go]: more specifically, I was wondering if something like the following might be beneficial to avoid lock contention on both the `IPCache.metadata.reservedHostLock` and also update `AddReservedIdentityWithLabels` to return the identity added to the cache to avoid an additional cache read lock and access.

```suggestion
func (ipc *IPCache) updateReservedHostLabels(prefix netip.Prefix, lbls labels.Labels) *identity.Identity {
	newLabels := ipc.mergeReservedHostLabels(prefix, lbls)
	log.WithField(logfields.Labels, newLabels).Debug("Merged labels for reserved:host identity")
	return identity.AddReservedIdentityWithLabels(identity.ReservedIdentityHost, newLabels)
}

func (ipc *IPCache) mergeReservedHostLabels(prefix netip.Prefix, lbls labels.Labels) labels.Labels {
	ipc.metadata.reservedHostLock.Lock()
	defer ipc.metadata.reservedHostLock.Unlock()
	if lbls == nil {
		delete(ipc.metadata.reservedHostLabels, prefix)
	} else {
		ipc.metadata.reservedHostLabels[prefix] = lbls
	}

	// aggregate all labels and update static identity
	newLabels := labels.Labels{}
	for _, l := range ipc.metadata.reservedHostLabels {
		newLabels.MergeLabels(l)
	}

	return newLabels
}
```

`pkg/identity/reserved.go`:
```
func AddReservedIdentityWithLabels(ni NumericIdentity, lbls labels.Labels) *Identity {
	identity := NewIdentity(ni, lbls)
	cacheMU.Lock()
	reservedIdentityCache[ni] = identity
	cacheMU.Unlock()
	return identity
}

func init() {
	iterateReservedIdentityLabels(func(ni NumericIdentity, lbls labels.Labels) {
		AddReservedIdentityWithLabels(ni, lbls)
	})
}
```

**Review by joestringer — APPROVED** [review]
Core change LGTM from a high level, I walked through the logic along with @christarazi . He may have some other minor feedback.

File: pkg/ipcache/metadata.go (hunk 3 above)
Comment (squeed) [reply pkg/ipcache/metadata.go:566]: I'd considered doing just that (but hadn't to keep the PR small). But yes, I think it's a good idea.

Comment (squeed) [reply pkg/ipcache/metadata.go]: Yeah, I had considered something like this as well, but left it out to make a small PR. But you've convinced me it's worth it. I'll remove the extra lock.

Comment (squeed) [reply pkg/ipcache/metadata.go]: However, we can't drop `reservedHostLock` until after we update the identity store -- otherwise we might have an A-B-A problem when there are parallel updates. (both InjectLabels and AllocateCIDRs call this code, and they only have a read lock on the metadata cache).

**Comment by squeed** [comment]
@schlosna updated based on feedback; PTAL.

File: pkg/ipcache/metadata.go (hunk 2 above)
Comment (squeed) [reply pkg/ipcache/metadata.go]: It shouldn't; see below. (resolving this thread)

**Review by schlosna — APPROVED** [review]
Thanks for addressing my comments, this looks good to me.

The commit check is unhappy with a duplicated word `labels` in the commit message and references to commits b099ba614 & f5d95325c that were part of https://github.com/cilium/cilium/pull/19765

> {[1/1] ipcache: aggregate labels from all IPs with local host identity}
>   Running on ae661971b3e961b64b9f7fc28a6e162eb72ed58e
>   Warning: WARNING:REPEATED_WORD: Possible repeated word: 'labels'
>   #[20](https://github.com/cilium/cilium/actions/runs/6404376766/job/17384819951?pr=28332#step:3:37): 
>     with labels labels `reserved:host, reserved:kube-apsierver`
>   
>   Warning: WARNING:UNKNOWN_COMMIT_ID: Unknown commit id 'b099ba614', maybe rebased or not pulled?
>   #[41](https://github.com/cilium/cilium/actions/runs/6404376766/job/17384819951?pr=28332#step:3:42): 
>   Fixes: b099ba614
>   
>   Warning: WARNING:UNKNOWN_COMMIT_ID: Unknown commit id 'f5d95325c', maybe rebased or not pulled?
>   #[42](https://github.com/cilium/cilium/actions/runs/6404376766/job/17384819951?pr=28332#step:3:43): 
>   Fixes: f5d95325c

File: pkg/identity/reserved.go [hunk 4]
```diff
@@ -18,20 +18,22 @@ var (
...
 	cacheMU.Lock()
 	reservedIdentityCache[ni] = identity
 	cacheMU.Unlock()
+	return identity
 }
 
 // AddReservedIdentityWithLabels is the same as AddReservedIdentity but accepts
 // multiple labels.
-func AddReservedIdentityWithLabels(ni NumericIdentity, lbls labels.Labels) {
+func AddReservedIdentityWithLabels(ni NumericIdentity, lbls labels.Labels) *Identity {
```
Comment (christarazi) [inline pkg/identity/reserved.go]: Let's update the godocs to mention that the added identity is now returned and more importantly, should **not** be modified as it's a live reference.

File: pkg/ipcache/metadata.go [hunk 5]
```diff
@@ -511,6 +538,32 @@ func (ipc *IPCache) resolveIdentity(ctx context.Context, prefix netip.Prefix, in
 	return id, isNew, err
 }
 
+// updateReservedHostLabels adds or removes labels that apply to the local host.
+// The `reserved:host` identity is special: the numeric identity is fixed
+// and the set of labels is mutable. (The datapath requires this.) So,
+// we need to determine all prefixes that have the `reserved:host` label and
+// capture their labels. Then, we must aggregate *all* labels from all IPs and
+// insert them as the `reserved:host` identity labels.
```
Comment (christarazi) [inline pkg/ipcache/metadata.go]: Just clarifying a bit more.

```suggestion
// capture their labels. Then, we must aggregate *all* labels from all prefixes and
// update the labels that correspond to the `reserved:host` identity.
```

Comment (christarazi) [reply pkg/ipcache/metadata.go]: Additionally, I think it would be useful to call out is that this function is doing another merging of metadata of which there are two now: one in this function and the other is the main ipcache metadata consolidator. The main difference from the latter is that we have to consider other prefixes, whereas the latter is per prefix.

File: pkg/ipcache/metadata.go [hunk 6]
```diff
@@ -511,6 +538,32 @@ func (ipc *IPCache) resolveIdentity(ctx context.Context, prefix netip.Prefix, in
...
+	ipc.metadata.reservedHostLock.Lock()
+	defer ipc.metadata.reservedHostLock.Unlock()
+	if lbls == nil {
+		delete(ipc.metadata.reservedHostLabels, prefix)
+	} else {
+		ipc.metadata.reservedHostLabels[prefix] = lbls
+	}
+
+	// aggregate all labels and update static identity
+	newLabels := labels.Labels{}
```
Comment (christarazi) [inline pkg/ipcache/metadata.go]: Nit: Can this be

```suggestion
	newLabels := labels.NewFrom(labels.LabelHost)
```

?

File: pkg/ipcache/metadata_test.go [hunk 7]
```diff
@@ -236,6 +236,63 @@ func TestInjectLabels(t *testing.T) {
...
+	bothLabels := labels.Labels{}
+	bothLabels.MergeLabels(labels.LabelHost)
+	bothLabels.MergeLabels(labels.LabelKubeAPIServer)
+
+	selectorCacheHas := func(lbls labels.Labels) {
+		t.Helper()
+		id := PolicyHandler.identities[hostid]
+		assert.NotNil(t, id)
+
+		assert.True(t, id.Equals(lbls.LabelArray()), "labels should equal: %v -- %v", id, lbls.LabelArray())
```
Comment (christarazi) [inline pkg/ipcache/metadata_test.go]: When running this test locally, I struggled to understand which value that's outputted is expected vs obtained. When I modified this to 

```suggestion
		assert.Equal(t, lbls.LabelArray(), id, "labels should equal")
```

it was much easier to read.

File: pkg/ipcache/metadata_test.go [hunk 8]
```diff
@@ -236,6 +236,63 @@ func TestInjectLabels(t *testing.T) {
...
+	// Mark .4 as local host
+	IPIdentityCache.metadata.upsertLocked(inClusterPrefix, source.Local, "node-uid", labels.LabelHost)
+	remaining, err := IPIdentityCache.InjectLabels(ctx, []netip.Prefix{inClusterPrefix})
+	assert.NoError(t, err)
+	assert.Len(t, remaining, 0)
+	assert.Equal(t, IPIdentityCache.ipToIdentityCache["10.0.0.4/32"].ID, hostid)
+	selectorCacheHas(labels.LabelHost)
+
+	// Mark .4 as kube-apiserver
+	IPIdentityCache.metadata.upsertLocked(inClusterPrefix, source.Local, "kube-uid", labels.LabelKubeAPIServer)
```
Comment (christarazi) [inline pkg/ipcache/metadata_test.go:280]: This should actually be

```suggestion
	IPIdentityCache.metadata.upsertLocked(inClusterPrefix, source.KubeAPIServer, "kube-uid", labels.LabelKubeAPIServer)
```

but I don't think there's a functional impact here.

File: pkg/ipcache/metadata_test.go [hunk 9]
```diff
@@ -236,6 +236,63 @@ func TestInjectLabels(t *testing.T) {
...
+	assert.Equal(t, IPIdentityCache.ipToIdentityCache["10.0.0.5/32"].ID, hostid)
+	selectorCacheHas(bothLabels)
+
+	// remove kube-apiserver
+	IPIdentityCache.metadata.remove(inClusterPrefix, "kube-uid", overrideIdentity(false), labels.LabelKubeAPIServer)
+	remaining, err = IPIdentityCache.InjectLabels(ctx, []netip.Prefix{inClusterPrefix})
+	assert.NoError(t, err)
+	assert.Len(t, remaining, 0)
+	assert.Equal(t, IPIdentityCache.ipToIdentityCache["10.0.0.4/32"].ID, hostid)
+
```
Comment (christarazi) [inline pkg/ipcache/metadata_test.go:315]: Nit: extra newline?

File: pkg/ipcache/metadata.go [hunk 10]
```diff
@@ -81,12 +81,21 @@ type metadata struct {
 	// generate updates into the ipcache, policy engine and datapath.
 	queuedChangesMU lock.Mutex
 	queuedPrefixes  map[netip.Prefix]struct{}
+
+	// reservedHostLock protects the localHostLabels map
+	reservedHostLock lock.Mutex
```
Comment (christarazi) [inline pkg/ipcache/metadata.go]: I think it's worth calling out here that we require this lock to be taken only within the `metadata` **read** lock.

File: pkg/ipcache/metadata.go [hunk 11]
```diff
@@ -211,6 +220,14 @@ func (ipc *IPCache) InjectLabels(ctx context.Context, modifiedPrefixes []netip.P
...
 				continue
 			} // else continue below to remove the old entry
+
+			// Special case: if we are removing an IP from the reserved:host identity,
+			// we need to remove this prefix's labels from the local identity and
+			// force an update to the selector cache.
+			if oldID.ID == identity.ReservedIdentityHost {
+				i := ipc.updateReservedHostLabels(prefix, nil)
+				idsToAdd[i.ID] = i.Labels.LabelArray()
+			}
```
Comment (christarazi) [inline pkg/ipcache/metadata.go]: I'm wondering if it's easier on the reader to have all of the cases for "deletion" under the `releaseIdentity` section on line 292. That way when the reader is considering all of the deletion cases, there's just one part of the function to look at, instead of overhead of scrolling up and down to evaluate different conditions, etc.

File: pkg/ipcache/metadata.go [hunk 12]
```diff
@@ -239,6 +256,12 @@ func (ipc *IPCache) InjectLabels(ctx context.Context, modifiedPrefixes []netip.P
 				break
 			}
 
+			// Special case: the host identity is mutable; we need to always update the SelectorCache.
+			// If the labels are unchanged, the SelectorCache will short-circuit.
+			if newID.ID == identity.ReservedIdentityHost {
+				idsToAdd[newID.ID] = newID.Labels.LabelArray()
+			}
+
```
Comment (christarazi) [inline pkg/ipcache/metadata.go]: Similar sentiment as my previous comment, but a bit further. Same spirit as keeping the loop core logic more readable. 

This line here is updating the **selectorcache**. The logic inside `resolveIdentity` is updating the **host identity labels**. I propose we keep that general structure.

However, it seems this check highlighted here was added presumably before the condition that could trigger jumping to `releaseIdentity`. To me this suggests there could be a helper function that returns bools based on whether the selectorcache should be updated or if we need to `releaseIdentity`.

That would involve refactoring the few lines of code below starting with `if oldID.ID == newID.ID && prefixInfo.Source() == oldID.Source &&` into a separate function and folding in `if newID.ID == identity.ReservedIdentityHost {` somewhere in that function.

I've took a stab at this below so feel free to apply and amend if needed. Naming could be improved as per usual :), unit tests are still passing for me so I think I've got it right:

<details><summary>Diff</summary>
<p>

```diff
diff --git a/pkg/ipcache/metadata.go b/pkg/ipcache/metadata.go
index 6874be5951..43955fc7f1 100644
--- a/pkg/ipcache/metadata.go
+++ b/pkg/ipcache/metadata.go
@@ -232,8 +232,8 @@ func (ipc *IPCache) InjectLabels(ctx context.Context, modifiedPrefixes []netip.P
 			var newID *identity.Identity
 
 			// Insert to propagate the updated set of labels after removal.
-			newID, _, err = ipc.resolveIdentity(ctx, prefix, prefixInfo, identity.InvalidIdentity)
-			if err != nil {
+			newID, isNew, err2 := ipc.resolveIdentity(ctx, prefix, prefixInfo, identity.InvalidIdentity)
+			if err2 != nil {
 				// NOTE: This may fail during a 2nd or later
 				// iteration of the loop. To handle this, break
 				// the loop here and continue executing the set
@@ -252,26 +252,18 @@ func (ipc *IPCache) InjectLabels(ctx context.Context, modifiedPrefixes []netip.P
 					"Failed to allocate new identity while handling change in labels associated with a prefix.",
 				)
 				remainingPrefixes = modifiedPrefixes[i:]
-				err = fmt.Errorf("failed to allocate new identity during label injection: %w", err)
+				err = fmt.Errorf("failed to allocate new identity during label injection: %w", err2)
 				break
 			}
 
-			// Special case: the host identity is mutable; we need to always update the SelectorCache.
-			// If the labels are unchanged, the SelectorCache will short-circuit.
-			if newID.ID == identity.ReservedIdentityHost {
+			selectorCacheUpdate, releaseID := determineIdentityUpdate(oldID, newID, isNew, prefixInfo, oldTunnelIP, oldEncryptionKey)
+			if selectorCacheUpdate {
 				idsToAdd[newID.ID] = newID.Labels.LabelArray()
 			}
-
-			// We can safely skip the ipcache upsert if the entry matches with
-			// the entry in the metadata cache exactly.
-			// Note that checking ID alone is insufficient, see GH-24502.
-			if oldID.ID == newID.ID && prefixInfo.Source() == oldID.Source &&
-				oldTunnelIP.Equal(prefixInfo.TunnelPeer().IP()) &&
-				oldEncryptionKey == prefixInfo.EncryptKey().Uint8() {
+			if releaseID {
 				goto releaseIdentity
 			}
 
-			idsToAdd[newID.ID] = newID.Labels.LabelArray()
 			entriesToReplace[prefix] = ipcacheEntry{
 				identity: Identity{
 					ID:                  newID.ID,
@@ -288,6 +280,7 @@ func (ipc *IPCache) InjectLabels(ctx context.Context, modifiedPrefixes []netip.P
 				// identity and replace it with this new identity.
 				force: entryExists && prefixInfo.Source() != oldID.Source && oldID.ID != newID.ID,
 			}
+
 		}
 	releaseIdentity:
 		if entryExists {
@@ -406,6 +399,37 @@ func (ipc *IPCache) InjectLabels(ctx context.Context, modifiedPrefixes []netip.P
 	return remainingPrefixes, err
 }
 
+func determineIdentityUpdate(
+	oldID Identity, newID *identity.Identity,
+	isNewID bool,
+	prefixInfo PrefixInfo,
+	oldTunnelIP net.IP,
+	oldEncryptionKey uint8,
+) (selectorCacheUpdate, releaseIdentity bool) {
+	// Always update the SelectorCache if the identity is new.
+	selectorCacheUpdate = isNewID
+
+	// Special case: the host identity is mutable; we need to always update the
+	// SelectorCache, even though isNewID might be false.
+	//
+	// If the labels are unchanged, the SelectorCache will short-circuit
+	// anyway.
+	if newID.ID == identity.ReservedIdentityHost {
+		selectorCacheUpdate = true
+	}
+
+	// We can safely skip the ipcache upsert if the entry matches with
+	// the entry in the metadata cache exactly.
+	// Note that checking ID alone is insufficient, see GH-24502.
+	if oldID.ID == newID.ID && prefixInfo.Source() == oldID.Source &&
+		oldTunnelIP.Equal(prefixInfo.TunnelPeer().IP()) &&
+		oldEncryptionKey == prefixInfo.EncryptKey().Uint8() {
+		releaseIdentity = true
+	}
+
+	return
+}
+
 // UpdatePolicyMaps pushes updates for the specified identities into the policy
 // engine and ensures that they are propagated into the underlying datapaths.
 func (ipc *IPCache) UpdatePolicyMaps(ctx context.Context, addedIdentities, deletedIdentities map[identity.NumericIdentity]labels.LabelArray) {
```

</p>
</details>

**Review by christarazi — COMMENTED** [review]
The core logic LGTM and I have some suggestions that IMO improve the code readability and hopefully maintainability. See the comments below.

Stepping back, initially I was a bit confused as it looked to me that this PR was needed to fix https://github.com/cilium/cilium/pull/27464, but the [linked issue](https://github.com/cilium/cilium/issues/28259) was something different. In the end, what it looks like is that this PR is needed to fix both cases, https://github.com/cilium/cilium/pull/27464 and the [linked issue](https://github.com/cilium/cilium/issues/28259), but this was not clear to me.

To understand the root cause of https://github.com/cilium/cilium/issues/28259, I git bisected down to https://github.com/cilium/cilium/pull/19765/commits/b099ba614e7090ea6a19e8dbadfe0db07eb83298 and https://github.com/cilium/cilium/pull/19765/commits/f5d95325c10762d3cd563be4a71a87bbdfd701ee, which shows a regression going back to v1.13.0-rc1. https://github.com/cilium/cilium/issues/28259 stated that the issue exists on main as well as v1.14, but it looks like this fix will need to be backported to v1.13 as well. Additionally, it turns out that there's no CI coverage for this case, so it's great you found & fixed it (:tada:) and we'll need to fill this gap in coverage. From an offline sync, @nathanjsweet offered to put up a PR for that.

The summary of my root cause analysis is in the regression we had removed the special handling of the host identity labels, and this PR basically adds that back. 

Policy, identity, ipcache, etc, are all code areas with logic that can sometimes be extremely subtle. A one line change could cause a significant regression, so understanding the full root cause is crucial in evaluating a change. For future changes, understanding which change introduced the regression is important context to provide in commit msgs / descriptions so we can determine which versions are affected. Additionally, it will greatly ease code reviews of particularly curly areas of Cilium like ipcache & policy-related code.

File: pkg/ipcache/metadata.go (hunk 6 above)
Comment (squeed) [reply pkg/ipcache/metadata.go]: I have to check the mutation rules, but probably, yes.

File: pkg/ipcache/metadata_test.go (hunk 8 above)
Comment (squeed) [reply pkg/ipcache/metadata_test.go:280]: Keeping the sources the same makes the bug much more likely. So it is a good test-case for the specific bug, even if it doesn't mirror current usage exactly.

File: pkg/ipcache/metadata.go (hunk 11 above)
Comment (squeed) [reply pkg/ipcache/metadata.go]: I'll see if the blocks can be correctly joined without affecting logic.

File: pkg/ipcache/metadata.go (hunk 12 above)
Comment (squeed) [reply pkg/ipcache/metadata.go]: it's not just SelectorCacheUpdate; we elide the entire ipcache update when the comparison is true.

Given how far this needs to be backported, I'd prefer a minimal diff.

File: pkg/ipcache/metadata.go (hunk 11 above)
Comment (squeed) [reply pkg/ipcache/metadata.go]: While thinking through this, I realized there was a potential bug when an IP lost reserved:node status. So the logic needed to be refactored to the "bottom" anyways.

File: pkg/ipcache/metadata.go (hunk 12 above)
Comment (christarazi) [reply pkg/ipcache/metadata.go]: > it's not just SelectorCacheUpdate; we elide the entire ipcache update when the comparison is true.

Do you mean the `if oldID.ID == newID.ID && prefixInfo.Source() == oldID.Source &&` comparisons? AFAICT, if `releaseIdentity` is true, then it will also skip the ipcache update, and the selectorcache update always happens if it needs to.

> Given how far this needs to be backported, I'd prefer a minimal diff.

Fair enough. I'm not opposed to keeping this minimal and submitting the refactor in a future `main` PR.

File: pkg/ipcache/metadata_test.go (hunk 7 above)
Comment (squeed) [reply pkg/ipcache/metadata_test.go]: Somehow I thought that label arrays didn't have ordering guarantees, but that was wrong, and we can use `assert.Equal`

File: pkg/ipcache/metadata.go (hunk 6 above)
Comment (squeed) [reply pkg/ipcache/metadata.go]: It could, though that just does a MergeLabels under the hood.

File: pkg/ipcache/metadata.go (hunk 11 above)
Comment (squeed) [reply pkg/ipcache/metadata.go]: OK, check out the latest revision.

File: pkg/ipcache/metadata.go (hunk 5 above)
Comment (squeed) [reply pkg/ipcache/metadata.go]: OK, I added some wording to that effect.

File: pkg/ipcache/metadata_test.go (hunk 8 above)
Comment (christarazi) [reply pkg/ipcache/metadata_test.go:280]: > Keeping the sources the same makes the bug much more likely

The only cases of labels attaching to the host identity is either kube-apiserver or CIDR labels in the case of node CIDR policy. AFAICT in node CIDR policy case, CIDR labels upserted as metadata into the ipcache from the nodemanager with the same `Local` source because the node being handled in the local node.

In this test case, we are testing the association of the kube-apiserver label which always comes with the `KubeAPIServer` source. If we were testing the association of CIDR labels, I'd agree with keeping `Local`. It's technically incorrect to use `Local` with kube-apiserver. Because `source` only plays a factor for the _actual_ ipcache entry itself, not the identity, it has no functional impact in this test, so in theory it does not make the bug more likely, AFAIU. The unit test is deterministic.

Anyway, I think this is a very minor thing because there's no functional impact. I was more calling it out from the perspective of a future reader potentially getting confused and thinking there's a bug in the test.

**Review by christarazi — APPROVED** [review]

File: pkg/ipcache/metadata.go (hunk 11 above)
Comment (christarazi) [reply pkg/ipcache/metadata.go]: Out of curiosity, how did you discover the potential bug?

Comment (squeed) [reply pkg/ipcache/metadata.go]: > Out of curiosity, how did you discover the potential bug?

I was thinking about more possible transitions (after our in-person conversation) and I realized I had missed a case. I also added this to the unit test.

As a hobby project, it would be fun to try and fuzz the ipcache in general. I'm thinking of a way to invent a sequence of operations and invariants.

File: pkg/ipcache/metadata_test.go (hunk 8 above)
Comment (squeed) [reply pkg/ipcache/metadata_test.go:280]: Added a comment to this effect -- that the source is normally different, but it's the same in the test case to maximize the chance of triggering the bug.

**Comment by squeed** [comment]
FYI @joestringer I was chatting with @christarazi, then I realized a few hours later that I had missed a case (albeit unlikely): if an IP loses `reserved:host` but keeps, say, `reserved:kube-apiserver` or `cidr:xxxx`

File: pkg/ipcache/metadata.go (hunk 11 above)
Comment (christarazi) [reply pkg/ipcache/metadata.go]: Sounds like a potentially nice-to-have item that could go in https://github.com/cilium/cilium/issues/21142.
