### PR TITLE
policy: Fixed  CIDRGroupRef breaking the sanitization

### LINKED ISSUE #34066: [1.16.0] CIDRGroupRef is breaking sanitization and not applying correctly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0 and lower than v1.17.0

### What happened?

We are utilizing `CiliumCIDRGroup`s.
When we create a CNP or CCNP (it happens for both), the status changes to an error message
```yaml
status:
  conditions:
  - lastTransitionTime: "2024-07-26T13:24:29Z"
    message: 'Unable to parse CIDRRule "": netip.ParsePrefix(""): no ''/'''
    status: "False"
    type: Valid
```

I searched the code and found out that `sanitize` is the problem here and I think that the `cidrGroupRef` is not translated correctly into a list of IPs before it is sanitized.
This should be tested somewhere IMO, but this is a different topic.

`cilium-dbg policy get` is showing the correctly translated IPs for any C(C)NP though. I would expect that the agent also applies the correct policy if it knows about the translated list of IPs, but this seems to not be the case. It seems to not apply the policy at all.

Setting the default deny rule to allow all ingress traffic by default (rendering the CCNP effectively useless) works as it should, even though the `status` still shows the CCNP to be invalid.

Can you give us a short explanation, what we could be doing wrong, if you think this is on us? Or please investigate in the code, how to fix this problem.

Remark: It is not just an appearance problem, but the firewall is not applied as it should be.

### How can we reproduce the issue?

1. Apply the following in a cluster:
```yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumCIDRGroup
metadata:
  name: test-cidrgroup
spec:
  externalCIDRs:
  - 12.3.4.5/32
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: test-fw
spec:
  nodeSelector: {}
  ingress:
  - fromCIDRSet:
    - cidrGroupRef: test-cidrgroup
```
2. Check the status of the `test-fw` CCNP -> It is marked as invalid.
3. Check the cilium-dbg output -> It correctly translates the CCG to a list of IPs.
4. Check the firewall access via telnet for example -> It is not applying correctly.
5. If you set the spec of the CCNP to the following:
```yaml
spec:
  ingress:
  - fromCIDRSet:
    - cidr: 12.3.4.5/32
```
it applies and the status is correctly set.

### Cilium Version

Client: 1.16.0 82999990 2024-07-23T22:22:14-07:00 go version go1.22.5 linux/amd64
Daemon: 1.16.0 82999990 2024-07-23T22:22:14-07:00 go version go1.22.5 linux/amd64

### Kernel Version

Linux $node 6.5.0-45-generic #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 15 16:40:02 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.30.3

### Regression

It worked on 1.15.6.

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by chaunceyjiang**
Fixes: #34066

```release-note
policy:  Fixed  CIDRGroupRef breaking the sanitization
```

### CODE REVIEW

File: pkg/policy/api/rule_validation.go [hunk 1]
```diff
@@ -528,6 +528,10 @@ func (c CIDR) sanitize() error {
 // valid, and ensuring that all of the exception CIDR prefixes are contained
 // within the allowed CIDR prefix.
 func (c *CIDRRule) sanitize() error {
+	if c.CIDRGroupRef != "" {
+		// When a CIDRGroupRef is set, we don't need to validate the CIDR
+		return nil
```
Comment (chaunceyjiang) [inline pkg/policy/api/rule_validation.go:533]: https://github.com/cilium/cilium/blob/17882e96de339905ecf46c0146e2dc6bda9f6158/pkg/policy/api/cidr.go#L195-L201


CIDRGroupRef already has some validation rules, so I didn't perform any validation on CIDRGroupRef here.

**Comment by jonasbadstuebner** [comment]
Shouldn't there still be validation that the prefix is included and everything? Or is this part of a CIDRGroup-Validation (I don't know if this exists and didn't look)?

**Comment by jonasbadstuebner** [comment]
And wouldn't it be possible to have `cidr` and `cidrGroupRef` at the same time - IMO the validation should not just be disabled? :eyes:

**Comment by jonasbadstuebner** [comment]
If disabling the validation is the best approach (for now, maybe), it would make more sense to skip it if there is no `cidr` set. Since the `cidrGroupRef` being set should not automatically mean any set `cidr` should not be validated.
The problem we are having is that _only_ having `cidrGroupRef` is currently an invalid state for sanitization to be performed.

**Comment by jonasbadstuebner** [comment]
And just for me, since I am unsure if my issue was understood correctly: Would fixing the validation - one way or another - also fix the apply of the firewall? So, is the broken validation the reason the firewall also does not apply as it should? Even though the `cilium-dbg` command shows the correctly translated IPs for the CCNP already?

**Comment by chaunceyjiang** [comment]
> And wouldn't it be possible to have cidr and cidrGroupRef at the same time - IMO the validation should not just be disabled? 👀

No. cidr and cidrGroupRef can only be chosen between the two. 👀

**Comment by chaunceyjiang** [comment]
> Since the cidrGroupRef being set should not automatically mean any set cidr should not be validated.

Since cidrGroupRef and cidr can only be chosen between the two, when setting cidrGroupRef, it simply skips the cidr at the same level as it, while other cidr will continue to be validated. 👀

**Comment by jonasbadstuebner** [comment]
You can have `cidr` and `cidrGroupRef` together.

**Comment by jonasbadstuebner** [comment]
Oh you mean for every entry in the `fromCIDRSet` only one key is allowed?

**Comment by jonasbadstuebner** [comment]
Ah, I understand the workaround now, thank you for the explanation.

**Comment by chaunceyjiang** [comment]
> You can have cidr and cidrGroupRef together.

Oh? Could you share your CiliumClusterwideNetworkPolicy with me?

**Comment by jonasbadstuebner** [comment]
```yaml
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: test-fw
spec:
  nodeSelector: {}
  ingress:
  - fromCIDRSet:
    - cidr: 12.3.4.56/32
    - cidrGroupRef: test-cidrgroup
```
This is valid.

```yaml
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: test-fw
spec:
  nodeSelector: {}
  ingress:
  - fromCIDRSet:
    - cidr: 12.3.4.56/32
      cidrGroupRef: test-cidrgroup
```
This is not valid.

So if the code sanitizes each enty in `fromCIDRSet` separately, this workaround will work.
I thought you meant you could not have `cidr` and `cidrGroupRef` entries in the same `fromCIDRSet` (and similar) sections.

**Comment by jonasbadstuebner** [comment]
But each CIDRRule can only have one, this is true. So the workaround would work, I think.

Still I have to double check, if the firewall applies as before - because as I wrote in the issue, this seems to not be the case.
That's why I was asking (I had trouble navigating the code efficiently): Could the sanitization stop the firewall from being applied "agent-side"?

**Comment by chaunceyjiang** [comment]
@jonasbadstuebner Not sure if it can solve your problem. Can you help test it?  ❤️

**Review by nathanjsweet — APPROVED** [review]

**Comment by jonasbadstuebner** [comment]
Why is this not included in 1.16.1? :/

**Comment by chancez** [comment]
Seems like this should be backported to v1.16, so I've marked it to be backported

**Comment by sebastiangaiser** [comment]
Found it in the actions: `pushing manifest for quay.io/cilium/operator-generic-ci:bb8897a753f859df3035147d0fc7fb10b2c6eef5@sha256:4a103859b8f807569acdad8e2eb9147cdf7c88ddb853457ae857d6cf2582a8bc 0.6s done`

**Comment by sebastiangaiser** [comment]
The fix worked but unfortunately we have a second problem, will continue in the original issue which is now reopened...
