### PR TITLE
daemon: Ignore cilium_* interfaces when deriving NodePort device

### LINKED ISSUE #16019: Cilium kube-proxy-replacement sometimes binds to cilium_host, breaking NodePort
## Bug report

**General Information**

- Cilium version (run `cilium version`): 1.9.5 and 1.9.6
- Kernel version (run `uname -a`): `5.11.11-200.fc33.x86_64`
- Orchestration system version in use (e.g. `kubectl version`, ...): Kubernetes 1.20.5
- Link to relevant artifacts (policies, deployments scripts, ...):
- Generate and upload a system zip:
  - 1.9.5 sysdump with one node (`usden1storage01`) in problem state (KPR bound only to cilium_host): [cilium-sysdump-20210503-144026.zip](https://github.com/cilium/cilium/files/6424447/cilium-sysdump-20210503-144026.zip)
  - 1.9.5 bugtool from affected node: [cilium-bugtool-20210503-203727.157+0000-UTC-382197453.tar.gz](https://github.com/cilium/cilium/files/6424456/cilium-bugtool-20210503-203727.157%2B0000-UTC-382197453.tar.gz)
  - 1.9.6 sysdump with *all* nodes in problem state (KPR bound to default route interface & cilium_host): [cilium-sysdump-20210503-154752.zip](https://github.com/cilium/cilium/files/6424457/cilium-sysdump-20210503-154752.zip)

**Environment details**
- Kubernetes 1.20.5 installed with kubeadm; Cilium 1.9.5 and 1.9.6. Cluster-pool IPAM.
- Dual-stack, with IPv6 preferred (node IPs are IPv6; v6 is the "first" pod and service CIDR, etc)
- Control plane nodes are L2-adjacent VMs running on Proxmox; upstream interface is `ens18`
- Worker nodes are L2-adjacent bare metal on a different subnet from the control-plane notes; upstream interface is `bond0`
- Tunnel and masquerade are disabled. BGP (FRRouting) is used to announce pod IPs for direct routing. Due to heterogeneous nodes, I can't hardcode an external interface (direct routing / nodeport) so this is set to auto-detect.

**Description of issue**
This is a follow-up from the Slack conversation [here](https://cilium.slack.com/archives/C53TG4J4R/p1620072235442800).

When all nodes are first booted, kube-proxy-replacement correctly auto-detects the external interface (`ens18` on control-plane VMs; `bond0` on worker bare-metal nodes).

Sometime later (unknown exactly how long it takes, or what the trigger is), I consistently find that one of two things has occurred:
- KPR is bound to _both_ the correct interface and `cilium_host` (with `cilium_host` selected as the Direct Routing interface), OR
- KPR is bound to _only_ `cilium_host`.

In both cases, all NodePort-related services on the host are broken (including MetalLB LoadBalancer services, which rely on NodePort).

In order to get out of this state, I have to reboot the node. No amount of restarting the Cilium pod restores the node to the correct state.

As discussed on Slack, I have an unproven suspicion that this _may_ have something to do with how `cilium_host` is addressed in a V6 or dual-stack environment:
- For the IPv4 address family, `cilium_host` is assigned an address out of the node's pod CIDR.
- For the IPv6 address family, `cilium_host` is assigned the same IP as on the external interface. Unclear of the logic here (are we cloning the node IP onto `cilium_host`?)

I'll do a bit of code spelunking once this is filed, as I'd like to understand both how the `cilium_host` V6 address is assigned, and the logic by which the interface auto-detection works (and if that could be contributing to this "mis-detection" of `cilium_host` as a valid interface).

I've attached a sysdump+bugtool from 1.9.5 when one node (`usden1storage01`) was in the bad state. Upgrading to 1.9.6 (and restarting cilium pods to do so, hitting the trigger noted below) immediately put _all_ the nodes into the "dual bind" state, so I've attached a sysdump from that state as well.

**How to reproduce the issue**

This seems at least partially correlated to restarts of the Cilium pod on a given node. In order to get into the state where KPR is bound to _both_ `cilium_host` and the correct external interface, restart the Cilium pod on a "good" node and it will come back up in this state.

I have not found a definitive way to trigger the state where KPR is bound to _only_ `cilium_host` - I'll update this if/when I shake out a trigger for that.

In any case, as @pchaigno noted in our Slack conversation, KPR probably shouldn't be allowed to bind to `cilium_host` - since in the vast majority of cases I assume it'd be impossible for that to have any useful outcome.

### PR DESCRIPTION
**Pull request by eyanulis**
Any Cilium-created interface (`cilium_host`, etc) will never be a valid
interface for kube-proxy-replacement NodePort (or direct routing). In
certain cases, it is possible for the NodePort auto-derivation code to
select one of these interfaces. This notably happens when the k8s node
IP is an IPv6 address: the node IP is cloned to `cilium_host`, and the IP
(sans netmask) is used as a map key - so `cilium_host` may be viewed as
the only interface with an address matching the node IP. 

Add a check bypassing any interface whose name is prefixed with
`cilium_` during NodePort device detection.

Add a test mimicking the IPv6 `cilium_host` case: node IP assigned to a
"real" interface and a `cilium_foo` interface, we should ignore
`cilium_foo`.

Fixes: #16019

Please ensure your pull request adheres to the following guidelines:

- [X] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [X] All code is covered by unit and/or runtime tests where feasible.
- [X] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [X] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [X] Provide a title or release-note blurb suitable for the release notes.
- [X] Thanks for contributing!

### CODE REVIEW

**Review by borkmann — APPROVED** [review]

File: daemon/cmd/kube_proxy_replacement.go [hunk 1]
```diff
@@ -626,7 +626,20 @@ func detectDevices(detectNodePortDevs, detectDirectRoutingDev bool) error {
 			"Cannot retrieve host IP addrs for BPF NodePort device detection")
 	} else {
 		for _, a := range addrs {
-			ifidxByAddr[a.IP.String()] = a.LinkIndex
+			// Any cilium_* interface will never be a valid NodePort or Direct Routing
+			// interface. Skip interface if we cannot resolve it from Netlink via its
+			// ifIndex or if its name begins with cilium_.
+			if link, err := netlink.LinkByIndex(a.LinkIndex); err != nil {
+				log.WithError(err).WithField(logfields.LinkIndex, a.LinkIndex).Warn(
+					"Unable to resolve link from ifIndex, skipping interface")
```
Comment (brb) [inline daemon/cmd/kube_proxy_replacement.go]: Nit: s/skipping interface/skipping interface for device detection/.

File: daemon/cmd/kube_proxy_replacement.go [hunk 2]
```diff
@@ -626,7 +626,20 @@ func detectDevices(detectNodePortDevs, detectDirectRoutingDev bool) error {
...
+				continue
+			} else if strings.HasPrefix(link.Attrs().Name, "cilium_") {
+				log.WithField(logfields.Device, link.Attrs().Name).Debug(
+					"Skipping Cilium-generated interface in NodePort device detection")
```
Comment (brb) [inline daemon/cmd/kube_proxy_replacement.go]: Nit: s/NodePort device/device/ (it's not only used for NodePort).

**Review by brb — CHANGES_REQUESTED** [review]
Thanks for the contribution! Looks good, just two nits.

File: daemon/cmd/kube_proxy_replacement.go [hunk 3]
```diff
@@ -626,7 +626,20 @@ func detectDevices(detectNodePortDevs, detectDirectRoutingDev bool) error {
...
 	} else {
 		for _, a := range addrs {
-			ifidxByAddr[a.IP.String()] = a.LinkIndex
+			// Any cilium_* interface will never be a valid NodePort or Direct Routing
+			// interface. Skip interface if we cannot resolve it from Netlink via its
+			// ifIndex or if its name begins with cilium_.
+			if link, err := netlink.LinkByIndex(a.LinkIndex); err != nil {
+				log.WithError(err).WithField(logfields.LinkIndex, a.LinkIndex).Warn(
+					"Unable to resolve link from ifIndex, skipping interface")
+				continue
```
Comment (jibi) [inline daemon/cmd/kube_proxy_replacement.go]: nit: no need for these `continue`s

Comment (eyanulis) [reply daemon/cmd/kube_proxy_replacement.go]: Thanks for catching that, I've removed them. I had gone back and forth between having an "implicit" and "explicit" `else` condition and the `continue`s would have been required for the implicit condition, but I forgot to remove them after settling on an explicit `else`.

File: daemon/cmd/kube_proxy_replacement.go (hunk 2 above)
Comment (eyanulis) [reply daemon/cmd/kube_proxy_replacement.go]: Updated, thanks. Also s/in/for/ for consistency with the various messages around it.

File: daemon/cmd/kube_proxy_replacement.go (hunk 1 above)
Comment (eyanulis) [reply daemon/cmd/kube_proxy_replacement.go]: Updated, thanks.

File: daemon/cmd/kube_proxy_replacement.go (hunk 2 above)
Comment (eyanulis) [reply daemon/cmd/kube_proxy_replacement.go]: Updated, thanks. Also s/in/for/ to be consistent with various messages around it.

**Comment by eyanulis** [comment]
@brb @jibi Thank you both for the review. Most recent force-push addresses the comments.

**Review by brb — APPROVED** [review]
Thanks!

**Review by jibi — APPROVED** [review]

**Comment by jibi** [comment]
test-me-please

**Comment by eyanulis** [comment]
It looks like most(/all?) of the failing tests are Github flakes from the first run (HTTP 500 during checkout, etc).

Is there any way to rerun them? I'm not terribly familiar with how this repo is wired up to Github Actions but it doesn't seem like they re-ran after the `test-me-please` comment above from @jibi.

**Comment by jibi** [comment]
> It looks like most(/all?) of the failing tests are Github flakes from the first run (HTTP 500 during checkout, etc).
> 
> Is there any way to rerun them? I'm not terribly familiar with how this repo is wired up to Github Actions but it doesn't seem like they re-ran after the `test-me-please` comment above from @jibi.

I think GH was having some issues yesterday with actions. Closing and reopening the PR should have restarted them

**Review by joamaki — APPROVED** [review]

**Comment by joamaki** [comment]
test-1.16-netnext

**Comment by joamaki** [comment]
The tests relevant to this PR are passing, so marking this ready for merge.
