### PR TITLE
ipam/aws: fixed a bug causing the operator to hang indefinitely when the ENI limits for an instance type could not be determined

### LINKED ISSUE #14802: ipam/aws/eni: IP allocation silently failing when using "unsupported" instance types
## Bug report

As I attempted to get CIlium to run onto arm64 EC2 instances of the `t4g` family with IPAM/ENI mode, I encountered an issue where the agent is waiting for the operator to allocate new addresses indefinitely.

agent logs on the `t4g.large` instance:

```json
{"level":"info","msg":"Successfully synchronized CiliumNode custom resource","name":"ip-10-6-29-165.eu-west-1.compute.internal","subsys":"ipam"}
{"available":0,"helpMessage":"Check if cilium-operator pod is running and does not have any warnings or error messages.","level":"info","msg":"Waiting for IPs to become available in CRD-backed allocation pool","name":"ip-10-6-29-165.eu-west-1.compute.internal","required":10,"subsys":"ipam"}
```

operator logs:

```json
{"level":"info","msg":"Discovered new CiliumNode custom resource","name":"ip-10-6-29-165.eu-west-1.compute.internal","subsys":"ipam"}
```

I tried to scale out existing autoscaling groups of a knowingly working instance type: `m5.large` (amd64), and surprisingly got into the same issue.

After removing the `t4g.large` from the cluster and it's associated CiliumNode resource, the operator managed to allocate ip addresses over the `m5.large` successfully.

I then looked at the following file: https://github.com/cilium/cilium/blob/8531ff82215943beb12650b784d2255bfae313db/pkg/aws/eni/limits/limits.go#L40

I tried to add another `arm64` instance type which was referenced into it: `m6g.large`. And this time it worked perfectly.

What is surprising is:
1. The lack of errors and/or warnings showing up on the operator's logs.
2. The fact that it seems to completely break the IP allocation for whole cluster

I haven't gone any further for now but I will follow up on this with more details next week! We briefly talked about it on Slack with @joestringer https://cilium.slack.com/archives/C53TG4J4R/p1611607263013800

**General Information**

- Cilium version: `v1.9.3`
- Kernel version: `5.4.0-1037-aws`
- Orchestration system version in use: `EKS v1.18.9`

**How to reproduce the issue**

1. Register an EC2 instance of the `t4g` family
2. Validate that no errors is showing up from the cilium-controller yet no IP allocation is occurring anymore

### PR DESCRIPTION
**Pull request by mvisonneau**
Fixes: #14802

With the current implementation, there is a race condition which causes the operator to completely hang if one of the EC2 instance of the cluster has a type for which the operator cannot determine the limits. This PR sorts this situation by removing the attempt for getting a readlock over the node mutex which already has a readwrite lock at this time.

Here is the pprof trace of the hanging goroutine:
```
1 @ 0x43a4a5 0x44afc5 0x44afae 0x46c0e7 0x25c769a 0x25c75e2 0x2649a7b 0x264da08 0x25c7302 0x25c7a6c 0x25c7758 0x25ce2bc 0x25cc525 0x25cc375 0x2660af1 0x19ec99a 0x1b1b61f 0x19dece2 0x19dc3a2 0x1116ebf 0x1115ced 0x1115c18 0x19dc105 0x19dc0a6 0x46fe81
#	0x46c0e6	sync.runtime_SemacquireMutex+0x46						/usr/local/go/src/runtime/sema.go:71
#	0x25c7699	sync.(*RWMutex).RLock+0xd9							/usr/local/go/src/sync/rwmutex.go:50
#	0x25c75e1	github.com/cilium/cilium/pkg/ipam.(*Node).InstanceID+0x21			/go/src/github.com/cilium/cilium/pkg/ipam/node.go:311
#	0x2649a7a	github.com/cilium/cilium/pkg/aws/eni.(*Node).loggerLocked+0x7a			/go/src/github.com/cilium/cilium/pkg/aws/eni/node.go:76
#	0x264da07	github.com/cilium/cilium/pkg/aws/eni.(*Node).GetMaximumAllocatableIPv4+0x67	/go/src/github.com/cilium/cilium/pkg/aws/eni/node.go:503
#	0x25c7301	github.com/cilium/cilium/pkg/ipam.(*Node).getMaxAllocate+0x41			/go/src/github.com/cilium/cilium/pkg/ipam/node.go:222
#	0x25c7a6b	github.com/cilium/cilium/pkg/ipam.(*Node).recalculate+0x18b			/go/src/github.com/cilium/cilium/pkg/ipam/node.go:378
#	0x25c7757	github.com/cilium/cilium/pkg/ipam.(*Node).UpdatedResource+0x97			/go/src/github.com/cilium/cilium/pkg/ipam/node.go:337
#	0x25ce2bb	github.com/cilium/cilium/pkg/ipam.(*NodeManager).Update.func1+0x5b		/go/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:263
#	0x25cc524	github.com/cilium/cilium/pkg/ipam.(*NodeManager).Update+0x184			/go/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:321
#	0x25cc374	github.com/cilium/cilium/pkg/ipam.(*NodeManager).Create+0x34			/go/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:251
#	0x2660af0	main.startSynchronizingCiliumNodes.func1+0x70					/go/src/github.com/cilium/cilium/operator/cilium_node.go:59
#	0x19ec999	k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd+0x59		/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:231
#	0x1b1b61e	github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1+0x25e	/go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:119
```

As we discussed with @christarazi in the releated issue, I also took this opportunity to improve the associated logging!

```release-note
ipam/aws: fixed a bug causing the operator to hang indefinitely when the ENI limits for an instance type could not be determined
```

### CODE REVIEW

File: pkg/aws/eni/node.go [hunk 1]
```diff
@@ -174,7 +174,7 @@ func (n *Node) ReleaseIPs(ctx context.Context, r *ipam.ReleaseAction) error {
 func (n *Node) PrepareIPAllocation(scopedLog *logrus.Entry) (a *ipam.AllocationAction, err error) {
 	limits, limitsAvailable := n.getLimits()
 	if !limitsAvailable {
-		return nil, fmt.Errorf("Unable to determine limits")
+		return nil, fmt.Errorf(errUnableToDetermineLimits)
```
Comment (christarazi) [inline pkg/aws/eni/node.go]: I think moving to sentinel error values is fine, but no need to `fmt.Errorf()` again

File: pkg/aws/eni/node.go [hunk 2]
```diff
@@ -322,12 +322,13 @@ func (n *Node) findNextIndex(index int32) int32 {
...
-	errUnableToDetermineLimits    = "unable to determine limits"
-	errUnableToGetSecurityGroups  = "unable to get security groups"
-	errUnableToCreateENI          = "unable to create ENI"
-	errUnableToAttachENI          = "unable to attach ENI"
-	errUnableToMarkENIForDeletion = "unable to mark ENI for deletion"
-	errUnableToFindSubnet         = "unable to find matching subnet"
+	errUnableToAttachENI                    = "unable to attach ENI"
+	errUnableToCreateENI                    = "unable to create ENI"
+	errUnableToDetermineFirstInterfaceIndex = "unable to determine first interface index"
+	errUnableToDetermineLimits              = "unable to determine limits, consider setting --update-ec2-adapter-limit-via-api=true"
```
Comment (christarazi) [inline pkg/aws/eni/node.go]: I think we should keep recommendations / mitigations to log msgs instead of error msgs. Errors should describe succinctly the cause of a problem, but it should not recommend any course of action. I believe it is cleaner if the caller of the function which errored to recommend a course of action / provide a mitigation instead.  This way the caller has the full context of the issue and can decide if it makes sense to log at that point in the code path.

File: pkg/aws/eni/node.go [hunk 3]
```diff
@@ -494,9 +495,9 @@ func (n *Node) ResyncInterfacesAndIPs(ctx context.Context, scopedLog *logrus.Ent
 
 // GetMaximumAllocatableIPv4 returns the maximum amount of IPv4 addresses
 // that can be allocated to the instance
-func (n *Node) GetMaximumAllocatableIPv4() int {
+func (n *Node) GetMaximumAllocatableIPv4(scopedLog *logrus.Entry) int {
 	if n == nil {
-		log.Warningf("Could not determine first interface index, %s", getMaximumAllocatableIPv4FailureWarningStr)
+		log.Warningf("%s: %s", errUnableToDetermineFirstInterfaceIndex, getMaximumAllocatableIPv4FailureWarningStr)
```
Comment (christarazi) [inline pkg/aws/eni/node.go]: This seems unnecessary to me. I think we should keep the log msgs how they were, as log msgs and error msgs should not be used interchangeably.

File: pkg/aws/eni/node.go [hunk 4]
```diff
@@ -494,9 +495,9 @@ func (n *Node) ResyncInterfacesAndIPs(ctx context.Context, scopedLog *logrus.Ent
 
 // GetMaximumAllocatableIPv4 returns the maximum amount of IPv4 addresses
 // that can be allocated to the instance
-func (n *Node) GetMaximumAllocatableIPv4() int {
+func (n *Node) GetMaximumAllocatableIPv4(scopedLog *logrus.Entry) int {
```
Comment (christarazi) [inline pkg/aws/eni/node.go]: Why was this needed? It seems to me that we can already access the logger via `n.loggerLocked()`

Comment (christarazi) [reply pkg/aws/eni/node.go]: Plus this modifies the interface to the functions for no concrete benefit

File: pkg/ipam/node.go [hunk 5]
```diff
@@ -828,7 +831,7 @@ func (n *Node) update(origNode, node *v2.CiliumNode, attempts int, status bool)
 //
 // For now, this function is only needed in ENI IPAM mode. In the future, this
 // may also be needed for Azure IPAM as well.
-func adjustPreAllocateIfNeeded(node *v2.CiliumNode) {
+func adjustPreAllocateIfNeeded(node *v2.CiliumNode) (err error) {
```
Comment (christarazi) [inline pkg/ipam/node.go]: Nit: no need to name return values; we only have one

File: pkg/ipam/node.go [hunk 6]
```diff
@@ -837,13 +840,22 @@ func adjustPreAllocateIfNeeded(node *v2.CiliumNode) {
...
-		max := lim.Adapters * lim.IPv4
-		if node.Spec.IPAM.PreAllocate > max {
-			node.Spec.IPAM.PreAllocate = max
+	lim, ok := limits.Get(node.Spec.ENI.InstanceType)
+	if !ok {
+		return fmt.Errorf(
+			`unable to find the limits for this instance type '%s',
+			consider setting --update-ec2-adapter-limit-via-api=true`,
+			node.Spec.ENI.InstanceType,
+		)
```
Comment (christarazi) [inline pkg/ipam/node.go]: At this point in the code, this error can be triggered many times because the caller of this function will retry. Given that, it would be nicer if we used a `sync.Once` to log this only once, as to not pollute the logs. We can also provide the recommendation of setting the specific flag, rather than embedding the mitigation in the error msg. The error returned should simply be `errLimitsNotFound` or whatever the sentinel error variable is called.

We should also consider whether it makes more sense for the caller to log once or whether to do it in this function itself.

**Review by christarazi — CHANGES_REQUESTED** [review]
Thanks for the PR! I think the core idea of the PR seems good to me. I have comments on how it's implemented however. 

Also, the commit msg seems to be better suited as a release note. The commit msg should briefly describe the code change, to conform to https://docs.cilium.io/en/v1.9/contributing/development/contributing_guide/#submitting-a-pull-request. Concretely, the commit msg can be:

```
ipam/aws: Provide mitigation if ENI limits not found
```

Elaborating that it fixed a bug would be good to move to the commit msg context instead.

Feel free to add / modify it as you see fit as well.

File: pkg/aws/eni/node.go (hunk 4 above)
Comment (mvisonneau) [reply pkg/aws/eni/node.go]: So this is exactly where the whole situation resides. By calling `n.loggerLocked()` within this scope, the function gets blocked as it returns `n.node.InstanceID()` which requires a read-lock over the node mutex which is already rw locked

https://github.com/cilium/cilium/blob/e2676483a51b7b089cd6a476b83038b9a1ec6169/pkg/aws/eni/node.go#L76

https://github.com/cilium/cilium/blob/e2676483a51b7b089cd6a476b83038b9a1ec6169/pkg/ipam/node.go#L311

https://github.com/cilium/cilium/blob/e2676483a51b7b089cd6a476b83038b9a1ec6169/pkg/ipam/node.go#L364

do you know if there is a better way to workaround this issue?

File: pkg/aws/eni/node.go (hunk 1 above)
Comment (mvisonneau) [reply pkg/aws/eni/node.go]: sounds good, what should I use then as `errUnableToDetermineLimits` is a string? 🤔

File: pkg/aws/eni/node.go (hunk 3 above)
Comment (mvisonneau) [reply pkg/aws/eni/node.go]: sounds good I will revert these then 👍

File: pkg/aws/eni/node.go (hunk 2 above)
Comment (mvisonneau) [reply pkg/aws/eni/node.go]: sounds good, I will revert this change then 👍, where exactly do you reckon we should be putting the advice?

File: pkg/ipam/node.go (hunk 6 above)
Comment (mvisonneau) [reply pkg/ipam/node.go]: absolutely, I wasn't too sure about this part anyway. I believe it is out of scope for the PR so I will revert it for now.

**Review by mvisonneau — COMMENTED** [review]
thanks for the 👀 feedback @christarazi ! Can you please doublecheck a couple of my subsequent comments? 🙇

File: pkg/aws/eni/node.go (hunk 1 above)
Comment (christarazi) [reply pkg/aws/eni/node.go]: Yeah you can do:

```
var errUnableToDetermineLimits = errors.New("...")
```

Then 
```suggestion
		return nil, errUnableToDetermineLimits
```

File: pkg/aws/eni/node.go (hunk 4 above)
Comment (christarazi) [reply pkg/aws/eni/node.go]: Are you saying that you found a deadlock in the code prior and this change fixes it? Because the prior code is still using `loggerLocked()`

File: pkg/aws/eni/node.go (hunk 2 above)
Comment (christarazi) [reply pkg/aws/eni/node.go]: I think the first place that the user will encounter this error is in `pkg/nodediscovery.determineFirstInterfaceIndex()` so it would make sense to put it there to warn as early as possible

File: pkg/aws/eni/node.go (hunk 4 above)
Comment (mvisonneau) [reply pkg/aws/eni/node.go]: yes, absolutely!

Comment (christarazi) [reply pkg/aws/eni/node.go]: Ah, I see! I didn't notice that the driver behind this PR is this deadlock. Nice catch!

However, I still think we can do better here than to pollute the interface with a logger; that shouldn't need to be passed around and the fact that we do rely on that to avoid a deadlock is a very strong indicator that we need to rethink the flow and dependencies of this code.

Here's my proposal:

Let's add `instanceID string` as a field to the `pkg/aws/eni.Node` struct. This would allow us to avoid depending on `n.node.InstanceID()` which was done previously (which evidently cannot be called when `n.node` is already locked).

We can initialize the field when we call [`CreateNode`](https://github.com/mvisonneau/cilium/blob/e2676483a51b7b089cd6a476b83038b9a1ec6169/pkg/aws/eni/instances.go#L68), and we can rely on this to be set because the instance ID is [always set when the resource is created](https://github.com/mvisonneau/cilium/blob/e2676483a51b7b089cd6a476b83038b9a1ec6169/pkg/nodediscovery/nodediscovery.go#L469).

Something like:

```
func (m *InstancesManager) CreateNode(obj *v2.CiliumNode, n *ipam.Node) ipam.NodeOperations {
	return &Node{k8sObj: obj, manager: m, node: n, instanceID: n.InstanceID()}
}
```

or feel free to create a constructor for `Node`. 

If you think this is a good idea, then please implement in a separate commit. WDYT?

File: pkg/aws/eni/node.go (hunk 2 above)
Comment (mvisonneau) [reply pkg/aws/eni/node.go]: sounds great, I added the warning at this place 👍

File: pkg/aws/eni/node.go (hunk 1 above)
Comment (mvisonneau) [reply pkg/aws/eni/node.go]: I reverted those changes as they are not related to this change anyway!

File: pkg/aws/eni/node.go (hunk 3 above)
Comment (mvisonneau) [reply pkg/aws/eni/node.go]: done 👍

File: pkg/aws/eni/node.go (hunk 4 above)
Comment (mvisonneau) [reply pkg/aws/eni/node.go]: indeed, this is much cleaner and future proof, thanks for the guidance on this @christarazi 🙇 !

File: pkg/ipam/node.go (hunk 5 above)
Comment (mvisonneau) [reply pkg/ipam/node.go]: I reverted this change as well 👍

File: pkg/ipam/node.go (hunk 6 above)
Comment (mvisonneau) [reply pkg/ipam/node.go]: done 👍

File: pkg/nodediscovery/nodediscovery.go [hunk 7]
```diff
@@ -525,6 +525,8 @@ func determineFirstInterfaceIndex(instanceType string) *int {
 		if defaults.IPAMPreAllocation > max {
 			idx = 0 // Include eth0
 		}
+	} else {
+		log.Warningf("Unable to find limits for instance type '%s', consider setting --update-ec2-adapter-limit-via-api=true", instanceType)
```
Comment (christarazi) [inline pkg/nodediscovery/nodediscovery.go]: Rather than using dynamic string formatting, let's use structured logging instead:

```
log.WithField("instance-type", instanceType).Warning(...)
```

Comment (christarazi) [reply pkg/nodediscovery/nodediscovery.go]: Actually, we might need string formatting to include the name of the option:

```
Warningf("Unable to find limits for instance type, consider setting --%s=true", option.UpdateEC2AdapterLimitViaAPI)
```

**Review by christarazi — CHANGES_REQUESTED** [review]
Looks much better! Could you separate out the `instanceID` change into a separate commit? The log msg should be in it's own commit. This way we have clear logical commits implementing independent behavior.

File: pkg/nodediscovery/nodediscovery.go (hunk 7 above)
Comment (mvisonneau) [reply pkg/nodediscovery/nodediscovery.go]: absolutely, I splitted the change in 2 commits and updated accordingly 👌

File: pkg/nodediscovery/nodediscovery.go [hunk 8]
```diff
@@ -525,6 +526,13 @@ func determineFirstInterfaceIndex(instanceType string) *int {
 		if defaults.IPAMPreAllocation > max {
 			idx = 0 // Include eth0
 		}
+	} else {
+		log.WithFields(logrus.Fields{
+			"instance-type": instanceType,
+		}).Warningf(
+			"Unable to find limits for instance type, consider setting --%s=true",
+			operatorOption.UpdateEC2AdapterLimitViaAPI,
+		)
```
Comment (christarazi) [inline pkg/nodediscovery/nodediscovery.go]: I didn't realize that the flag is only for the operator...

Maybe we should clarify that in the log msg. Something like:

> "Unable to find limits for instance type, consider setting --%s=true on the Operator"

**Review by christarazi — COMMENTED** [review]
Awesome! I have 2 more pieces of feedback:

- Minor fixup to the log msg
- Could you update the commit msg of the second commit to elaborate a bit more on the deadlock issue? Maybe describe that in a particular function (I forgot the name of it), a write-lock was obtained and while it was locked, calling `n.loggerLocked()` would call `n.node.InstanceID()` which then attempts to read-lock to extract out the `instanceID`.

File: pkg/nodediscovery/nodediscovery.go (hunk 8 above)
Comment (mvisonneau) [reply pkg/nodediscovery/nodediscovery.go]: sounds good, updated the log message and the commit message 👍

File: pkg/nodediscovery/nodediscovery.go [hunk 9]
```diff
@@ -525,6 +526,13 @@ func determineFirstInterfaceIndex(instanceType string) *int {
 		if defaults.IPAMPreAllocation > max {
 			idx = 0 // Include eth0
 		}
+	} else {
+		log.WithFields(logrus.Fields{
+			"instance-type": instanceType,
+		}).Warningf(
+			"Unable to find limits for instance type, consider setting --%s=true on the operator",
```
Comment (christarazi) [inline pkg/nodediscovery/nodediscovery.go]: Capitalize "operator"

**Review by christarazi — COMMENTED** [review]
:tada: 

LGTM, thanks for the PR! Minor feedback:

- Minor nit below
- In the 2nd commit msg, I'd avoid referencing exact line numbers as they'll get out-of-date quickly. Referencing the function is good enough like you have already done. :)

File: pkg/nodediscovery/nodediscovery.go (hunk 9 above)
Comment (mvisonneau) [reply pkg/nodediscovery/nodediscovery.go]: great, sorted! thanks for the very constructive review 🙇 !

**Review by christarazi — APPROVED** [review]
:rocket:

**Comment by aanm** [comment]
test-me-please

**Comment by joestringer** [comment]
Only one failure, the k8s-1.20-kernel-4.9 job which failed on a test that doesn't make sense to fail given the changes. It must be a flake, so I filed https://github.com/cilium/cilium/issues/15103 to follow up. No need to block this PR on flaky CI.
