### PR TITLE
oper/bgp: Disable PeerConfigStatusReconciler with empty bgp-secrets-namespace

### LINKED ISSUE #42408: Cilium Operator crashes when bgp-secrets-namespace not set
https://github.com/cilium/cilium/blob/10b55acc994369fde7c95de751d8de1492472910/operator/pkg/bgpv2/peer.go#L85

When `bgp-secrets-namespace` is not set, the operator enters into a continuous crash loop. The highlighted line is the culprit.

Must `bgp-secrets-namespace` be set? The docs don't state that. And also if there's no authentication between BGP peers i don't see why it has to be set

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x2aa907d]

goroutine 356 [running]:
github.com/cilium/cilium/operator/pkg/bgpv2.(*peerConfigStatusReconciler).reconcileStatus(0xc001792d20, {0x447c978, 0xc000620ae0}, {0xc0017ffd78?, 0x4b37b3?})
	/go/src/github.com/cilium/cilium/operator/pkg/bgpv2/peer.go:85 +0x3d
github.com/cilium/hive/job.(*jobOneShot).start(0xc001792d80, {0x447c978, 0xc000620ae0}, 0x3a00327463656a?, {0x4484880, 0xc001313c20}, {{{0xc0007d0b40, 0x1, 0x1}}, 0xc00097efe0, ...})
	/go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/job/oneshot.go:138 +0x4fd
created by github.com/cilium/hive/job.(*queuedJob).Start.func1 in goroutine 273
	/go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/job/job.go:126 +0x16f
```

### PR DESCRIPTION
**Pull request by rastislavs**
The sole purpose of the `peer-config-status-reconciler` job ATM is to set `MissingAuthSecret` condition when BGP secrets are used. When `BGPSecretsNamespace` is not set and `Resource[*Secret]` is nil, we should not run the `peer-config-status-reconciler` job (otherwise it crashes ATM). We should however still run the `cleanup-peer-config-status job`.

Fixes: #42408

```release-note
Fix BGP operator crash when bgp-secrets-namespace not set.
```

### CODE REVIEW

File: operator/pkg/bgpv2/peer.go [hunk 1]
```diff
@@ -75,10 +75,14 @@ func registerPeerConfigStatusReconciler(in peerConfigStatusReconcilerIn) {
 		return
 	}
 
-	in.JobGroup.Add(job.OneShot(
-		"peer-config-status-reconciler",
-		u.reconcileStatus,
-	))
+	if in.SecretResource != nil {
```
Comment (harsimran-pabla) [inline operator/pkg/bgpv2/peer.go:78]: Should we not set the status field if secret namespace is not configured? 

For eg, if user creates a BGP peer resource with secret ( namespace A, secret X ). Currently, we are checking if secret X exists in namespace A. And this sets MissingAuthSecret condition. 

I would guess this condition should also be set if namespace A was not configured.

Comment (rastislavs) [reply operator/pkg/bgpv2/peer.go:78]: I would not complicate this reconciler with that. In most of the use-cases, the secret namespace is set (it is defaulted in the Helm chart), so this is an edge scenario when the BGP CP is enabled via CLI. Instead, we should consolidate the config options in BGP CP to use Hive config, and apply same defaulting as in the Helm chart.

**Review by harsimran-pabla — APPROVED** [review]
