### PR TITLE
node-neigh: Wait instead of sleeping in unit tests

### LINKED ISSUE #17034: CI: RuntimePrivilegedUnitTests Run Tests
### Test Name
```test-name
RuntimePrivilegedUnitTests Run Tests
```

### Failure Output
```failure-output
FAIL: Failed to run privileged unit tests
```

### Stacktrace
<details><summary>Click to show.</summary>

```stack-trace
/home/jenkins/workspace/Cilium-PR-Runtime-4.9/runtime-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:518
Failed to run privileged unit tests
Expected command: sudo make -C /home/vagrant/go/src/github.com/cilium/cilium/ tests-privileged 
To succeed, but it failed:
Exitcode: 2 
Err: Process exited with status 2
Stdout:
 	 make: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium'
	 # cilium-map-migrate is a dependency of some unit tests.
	 make  -C bpf cilium-map-migrate
	 make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/bpf'
	 make[1]: 'cilium-map-migrate' is up to date.
	 make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/bpf'
	 make init-coverage
	 make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium'
	 echo "mode: count" > coverage-all-tmp.out
	 echo "mode: count" > coverage.out
	 make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium'
	 for pkg in github.com/cilium/cilium/daemon/cmd github.com/cilium/cilium/pkg/bpf github.com/cilium/cilium/pkg/datapath/link github.com/cilium/cilium/pkg/datapath/linux github.com/cilium/cilium/pkg/datapath/linux/config github.com/cilium/cilium/pkg/datapath/linux/ipsec github.com/cilium/cilium/pkg/datapath/linux/probes github.com/cilium/cilium/pkg/datapath/linux/route github.com/cilium/cilium/pkg/datapath/linux/routing github.com/cilium/cilium/pkg/datapath/loader github.com/cilium/cilium/pkg/fqdn/dnsproxy github.com/cilium/cilium/pkg/maps/ctmap github.com/cilium/cilium/pkg/maps/eppolicymap github.com/cilium/cilium/pkg/maps/lbmap github.com/cilium/cilium/pkg/maps/policymap github.com/cilium/cilium/pkg/modules github.com/cilium/cilium/pkg/mountinfo github.com/cilium/cilium/pkg/mtu github.com/cilium/cilium/pkg/redirectpolicy github.com/cilium/cilium/pkg/sysctl; do \
	 	PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/go/src/github.com/cilium/cilium/bpf go test  -mod=vendor -tags=osusergo,privileged_tests -ldflags "-X github.com/cilium/cilium/pkg/kvstore.consulDummyAddress=https://consul:8443 -X github.com/cilium/cilium/pkg/kvstore.etcdDummyAddress=http://etcd:4002 -X github.com/cilium/cilium/pkg/testutils.CiliumRootDir=/home/vagrant/go/src/github.com/cilium/cilium -X github.com/cilium/cilium/pkg/datapath.DatapathSHA256=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" $pkg -test.v -timeout 360s -check.vv  -covermode=count -coverprofile=coverage.out -coverpkg ./... \
	 	|| exit 1; \
	 	tail -n +2 coverage.out >> coverage-all-tmp.out; \
	 done
	 === RUN   Test
	 START: kube_proxy_replacement_test.go:44: KubeProxySuite.SetUpSuite
	 PASS: kube_proxy_replacement_test.go:44: KubeProxySuite.SetUpSuite	0.000s
	 
	 START: kube_proxy_replacement_test.go:65: KubeProxySuite.TestDetectDevices
	 level=warning msg="Cannot determine a device from k8s Node IP addr for BPF NodePort device detection" error="K8s Node IP is not set" subsys=daemon
	 level=warning msg="Cannot determine a device from k8s Node IP addr for BPF NodePort device detection" error="Cannot find device with 192.168.34.1 addr" subsys=daemon
	 level=info msg="Auto Detecting IPv6 Mcast device" subsys=daemon
	 level=info msg="Detected ipv6-mcast-device: dummy3" subsys=daemon
	 START: kube_proxy_replacement_test.go:57: KubeProxySuite.TearDownTest
	 PASS: kube_proxy_replacement_test.go:57: KubeProxySuite.TearDownTest	0.000s
	 
	 PASS: kube_proxy_replacement_test.go:65: KubeProxySuite.TestDetectDevices	0.533s
	 
	 START: kube_proxy_replacement_test.go:118: KubeProxySuite.TestExpandDevices
	 START: kube_proxy_replacement_test.go:57: KubeProxySuite.TearDownTest
	 PASS: kube_proxy_replacement_test.go:57: KubeProxySuite.TearDownTest	0.000s
	 
	 PASS: kube_proxy_replacement_test.go:118: KubeProxySuite.TestExpandDevices	0.002s
	 
	 START: nodeport_linux_test.go:51: NodePortSuite.TestCheckNodePortAndEphemeralPortRanges
	 START: nodeport_linux_test.go:35: NodePortSuite.SetUpTest
	 PASS: nodeport_linux_test.go:35: NodePortSuite.SetUpTest	0.000s
	 
	 START: nodeport_linux_test.go:44: NodePortSuite.TearDownTest
	 PASS: nodeport_linux_test.go:44: NodePortSuite.TearDownTest	0.001s
	 
	 PASS: nodeport_linux_test.go:51: NodePortSuite.TestCheckNodePortAndEphemeralPortRanges	0.003s
	 
	 START: sysctl_linux_test.go:34: DaemonPrivilegedSuite.TestEnableIPForwarding
	 PASS: sysctl_linux_test.go:34: DaemonPrivilegedSuite.TestEnableIPForwarding	0.000s
	 
	 OK: 4 passed
	 --- PASS: Test (0.54s)
	 PASS
	 coverage: 1.9% of statements in ./...
	 ok  	github.com/cilium/cilium/daemon/cmd	0.684s	coverage: 1.9% of statements in ./...
	 level=info msg="Detected mounted BPF filesystem at /sys/fs/bpf" subsys=bpf
	 === RUN   Test
	 START: map_linux_test.go:251: BPFPrivilegedTestSuite.TestBasicManipulation
	 PASS: map_linux_test.go:251: BPFPrivilegedTestSuite.TestBasicManipulation	0.003s
	 
	 START: map_linux_test.go:538: BPFPrivilegedTestSuite.TestCheckAndUpgrade
	 MapTypeHash: no prealloc to prealloc upgrade
	 level=warning msg="Flags mismatch for BPF map" file-path=/sys/fs/bpf/tc/globals/cilium_test_upgrade new=0 old=1 subsys=bpf
	 level=warning msg="Removing map to allow for property upgrade (expect map data loss)" file-path=/sys/fs/bpf/tc/globals/cilium_test_upgrade subsys=bpf
	 MapTypeLRUHash on 4.9 kernel: no prealloc to no prealloc upgrade
	 PASS: map_linux_test.go:538: BPFPrivilegedTestSuite.TestCheckAndUpgrade	0.000s
	 
	 START: map_linux_test.go:699: BPFPrivilegedTestSuite.TestCreateUnpinned
	 PASS: map_linux_test.go:699: BPFPrivilegedTestSuite.TestCreateUnpinned	0.000s
	 
	 START: map_linux_test.go:498: BPFPrivilegedTestSuite.TestDeleteAll
	 PASS: map_linux_test.go:498: BPFPrivilegedTestSuite.TestDeleteAll	0.000s
	 
	 START: map_linux_test.go:338: BPFPrivilegedTestSuite.TestDump
	 PASS: map_linux_test.go:338: BPFPrivilegedTestSuite.TestDump	0.000s
	 
	 START: map_linux_test.go:409: BPFPrivilegedTestSuite.TestDumpReliablyWithCallback
	 PASS: map_linux_test.go:409: BPFPrivilegedTestSuite.TestDumpReliablyWithCallback	0.126s
	 
	 START: map_linux_test.go:100: BPFPrivilegedTestSuite.TestGetMapInfo
	 PASS: map_linux_test.go:100: BPFPrivilegedTestSuite.TestGetMapInfo	0.000s
	 
	 START: map_linux_test.go:533: BPFPrivilegedTestSuite.TestGetModel
	 PASS: map_linux_test.go:533: BPFPrivilegedTestSuite.TestGetModel	0.000s
	 
	 START: map_linux_test.go:114: BPFPrivilegedTestSuite.TestOpen
	 PASS: map_linux_test.go:114: BPFPrivilegedTestSuite.TestOpen	0.000s
	 
	 START: map_linux_test.go:141: BPFPrivilegedTestSuite.TestOpenMap
	 PASS: map_linux_test.go:141: BPFPrivilegedTestSuite.TestOpenMap	0.000s
	 
	 START: map_linux_test.go:160: BPFPrivilegedTestSuite.TestOpenOrCreate
	 level=warning msg="Flags mismatch for BPF map" file-path=/sys/fs/bpf/tc/globals/cilium_test new=0 old=1 subsys=bpf
	 level=warning msg="Removing map to allow for property upgrade (expect map data loss)" file-path=/sys/fs/bpf/tc/globals/cilium_test subsys=bpf
	 PASS: map_linux_test.go:160: BPFPrivilegedTestSuite.TestOpenOrCreate	0.000s
	 
	 START: map_linux_test.go:200: BPFPrivilegedTestSuite.TestOpenParallel
	 PASS: map_linux_test.go:200: BPFPrivilegedTestSuite.TestOpenParallel	0.000s
	 
	 START: map_linux_test.go:658: BPFPrivilegedTestSuite.TestUnpin
	 PASS: map_linux_test.go:658: BPFPrivilegedTestSuite.TestUnpin	0.000s
	 
	 OK: 13 passed
	 --- PASS: Test (0.13s)
	 PASS
	 coverage: 6.9% of statements in ./...
	 ok  	github.com/cilium/cilium/pkg/bpf	2.245s	coverage: 6.9% of statements in ./...
	 === RUN   Test
	 START: link_test.go:34: LinkSuite.TestDeleteByName
	 PASS: link_test.go:34: LinkSuite.TestDeleteByName	0.022s
	 
	 START: link_test.go:72: LinkSuite.TestRename
	 PASS: link_test.go:72: LinkSuite.TestRename	0.040s
	 
	 OK: 2 passed
	 --- PASS: Test (0.06s)
	 PASS
	 coverage: 18.1% of statements in ./...
	 ok  	github.com/cilium/cilium/pkg/datapath/link	0.067s	coverage: 18.1% of statements in ./...
	 === RUN   Test
	 START: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestAgentRestartOptionChanges
	 START: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest
	 level=warning msg="Flags mismatch for BPF map" file-path=/sys/fs/bpf/tc/globals/cilium_tunnel_map new=1 old=0 subsys=bpf
	 level=warning msg="Removing map to allow for property upgrade (expect map data loss)" file-path=/sys/fs/bpf/tc/globals/cilium_tunnel_map subsys=bpf
	 PASS: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest	3.083s
	 
	 START: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest	0.076s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestAgentRestartOptionChanges	0.001s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestAuxiliaryPrefixes
	 START: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest	0.049s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestAuxiliaryPrefixes	0.001s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestNodeUpdateDirectRouting
	 START: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest	0.056s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestNodeUpdateDirectRouting	0.066s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestNodeUpdateEncapsulation
	 START: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest	0.052s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestNodeUpdateEncapsulation	0.002s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestNodeValidationDirectRouting
	 START: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest	0.058s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestNodeValidationDirectRouting	0.001s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestSingleClusterPrefix
	 START: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest	0.059s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestSingleClusterPrefix	0.107s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestUpdateNodeRoute
	 START: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest	0.053s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestUpdateNodeRoute	0.001s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestAgentRestartOptionChanges
	 START: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest	0.053s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestAgentRestartOptionChanges	0.001s
	 
	 START: node_linux_test.go:956: linuxPrivilegedIPv4OnlyTestSuite.TestArpPingHandling
	 START: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest	0.001s
	 
	 node_linux_test.go:1433:
	     c.Assert(found, check.Equals, true)
	 ... obtained bool = false
	 ... expected bool = true
	 
	 START: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest	0.052s
	 
	 FAIL: node_linux_test.go:956: linuxPrivilegedIPv4OnlyTestSuite.TestArpPingHandling
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestAuxiliaryPrefixes
	 START: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest	0.058s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestAuxiliaryPrefixes	0.001s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestNodeUpdateDirectRouting
	 START: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest	0.055s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestNodeUpdateDirectRouting	0.050s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestNodeUpdateEncapsulation
	 START: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest	0.054s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestNodeUpdateEncapsulation	0.001s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestNodeValidationDirectRouting
	 START: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest	0.050s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestNodeValidationDirectRouting	0.001s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestSingleClusterPrefix
	 START: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest	0.046s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestSingleClusterPrefix	0.002s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestUpdateNodeRoute
	 START: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest	0.002s
	 
	 START: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest	0.052s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestUpdateNodeRoute	0.001s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestAgentRestartOptionChanges
	 START: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest
	 PASS: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest
	 PASS: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest	0.041s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestAgentRestartOptionChanges	0.001s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestAuxiliaryPrefixes
	 START: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest
	 PASS: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest
	 PASS: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest	0.057s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestAuxiliaryPrefixes	0.002s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestNodeUpdateDirectRouting
	 START: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest
	 PASS: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest
	 PASS: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest	0.056s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestNodeUpdateDirectRouting	0.050s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestNodeUpdateEncapsulation
	 START: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest
	 PASS: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest
	 PASS: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest	0.045s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestNodeUpdateEncapsulation	0.003s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestNodeValidationDirectRouting
	 START: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest
	 PASS: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest
	 PASS: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest	0.053s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestNodeValidationDirectRouting	0.003s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestSingleClusterPrefix
	 START: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest
	 PASS: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest
	 PASS: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest	0.037s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestSingleClusterPrefix	0.002s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestUpdateNodeRoute
	 START: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest
	 PASS: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest
	 PASS: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest	0.042s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestUpdateNodeRoute	0.001s
	 
	 OOPS: 21 passed, 1 FAILED
	 --- FAIL: Test (6.64s)
	 FAIL
	 coverage: 4.3% of statements in ./...
	 FAIL	github.com/cilium/cilium/pkg/datapath/linux	7.212s
	 FAIL
	 Makefile:141: recipe for target 'tests-privileged' failed
	 make: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium'
	 
Stderr:
 	 make: *** [tests-privileged] Error 1
	 

/home/jenkins/workspace/Cilium-PR-Runtime-4.9/runtime-gopath/src/github.com/cilium/cilium/test/runtime/privileged_tests.go:57
```
</details>

### Standard Output
<details><summary>Click to show.</summary>

```stack-output


```
</details>

### Standard Error
<details><summary>Click to show.</summary>

```stack-error
17:25:00 STEP: Running BeforeAll block for EntireTestsuite RuntimePrivilegedUnitTests
FAIL: Failed to run privileged unit tests
Expected command: sudo make -C /home/vagrant/go/src/github.com/cilium/cilium/ tests-privileged 
To succeed, but it failed:
Exitcode: 2 
Err: Process exited with status 2
Stdout:
 	 make: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium'
	 # cilium-map-migrate is a dependency of some unit tests.
	 make  -C bpf cilium-map-migrate
	 make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium/bpf'
	 make[1]: 'cilium-map-migrate' is up to date.
	 make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium/bpf'
	 make init-coverage
	 make[1]: Entering directory '/home/vagrant/go/src/github.com/cilium/cilium'
	 echo "mode: count" > coverage-all-tmp.out
	 echo "mode: count" > coverage.out
	 make[1]: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium'
	 for pkg in github.com/cilium/cilium/daemon/cmd github.com/cilium/cilium/pkg/bpf github.com/cilium/cilium/pkg/datapath/link github.com/cilium/cilium/pkg/datapath/linux github.com/cilium/cilium/pkg/datapath/linux/config github.com/cilium/cilium/pkg/datapath/linux/ipsec github.com/cilium/cilium/pkg/datapath/linux/probes github.com/cilium/cilium/pkg/datapath/linux/route github.com/cilium/cilium/pkg/datapath/linux/routing github.com/cilium/cilium/pkg/datapath/loader github.com/cilium/cilium/pkg/fqdn/dnsproxy github.com/cilium/cilium/pkg/maps/ctmap github.com/cilium/cilium/pkg/maps/eppolicymap github.com/cilium/cilium/pkg/maps/lbmap github.com/cilium/cilium/pkg/maps/policymap github.com/cilium/cilium/pkg/modules github.com/cilium/cilium/pkg/mountinfo github.com/cilium/cilium/pkg/mtu github.com/cilium/cilium/pkg/redirectpolicy github.com/cilium/cilium/pkg/sysctl; do \
	 	PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/go/src/github.com/cilium/cilium/bpf go test  -mod=vendor -tags=osusergo,privileged_tests -ldflags "-X github.com/cilium/cilium/pkg/kvstore.consulDummyAddress=https://consul:8443 -X github.com/cilium/cilium/pkg/kvstore.etcdDummyAddress=http://etcd:4002 -X github.com/cilium/cilium/pkg/testutils.CiliumRootDir=/home/vagrant/go/src/github.com/cilium/cilium -X github.com/cilium/cilium/pkg/datapath.DatapathSHA256=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" $pkg -test.v -timeout 360s -check.vv  -covermode=count -coverprofile=coverage.out -coverpkg ./... \
	 	|| exit 1; \
	 	tail -n +2 coverage.out >> coverage-all-tmp.out; \
	 done
	 === RUN   Test
	 START: kube_proxy_replacement_test.go:44: KubeProxySuite.SetUpSuite
	 PASS: kube_proxy_replacement_test.go:44: KubeProxySuite.SetUpSuite	0.000s
	 
	 START: kube_proxy_replacement_test.go:65: KubeProxySuite.TestDetectDevices
	 level=warning msg="Cannot determine a device from k8s Node IP addr for BPF NodePort device detection" error="K8s Node IP is not set" subsys=daemon
	 level=warning msg="Cannot determine a device from k8s Node IP addr for BPF NodePort device detection" error="Cannot find device with 192.168.34.1 addr" subsys=daemon
	 level=info msg="Auto Detecting IPv6 Mcast device" subsys=daemon
	 level=info msg="Detected ipv6-mcast-device: dummy3" subsys=daemon
	 START: kube_proxy_replacement_test.go:57: KubeProxySuite.TearDownTest
	 PASS: kube_proxy_replacement_test.go:57: KubeProxySuite.TearDownTest	0.000s
	 
	 PASS: kube_proxy_replacement_test.go:65: KubeProxySuite.TestDetectDevices	0.533s
	 
	 START: kube_proxy_replacement_test.go:118: KubeProxySuite.TestExpandDevices
	 START: kube_proxy_replacement_test.go:57: KubeProxySuite.TearDownTest
	 PASS: kube_proxy_replacement_test.go:57: KubeProxySuite.TearDownTest	0.000s
	 
	 PASS: kube_proxy_replacement_test.go:118: KubeProxySuite.TestExpandDevices	0.002s
	 
	 START: nodeport_linux_test.go:51: NodePortSuite.TestCheckNodePortAndEphemeralPortRanges
	 START: nodeport_linux_test.go:35: NodePortSuite.SetUpTest
	 PASS: nodeport_linux_test.go:35: NodePortSuite.SetUpTest	0.000s
	 
	 START: nodeport_linux_test.go:44: NodePortSuite.TearDownTest
	 PASS: nodeport_linux_test.go:44: NodePortSuite.TearDownTest	0.001s
	 
	 PASS: nodeport_linux_test.go:51: NodePortSuite.TestCheckNodePortAndEphemeralPortRanges	0.003s
	 
	 START: sysctl_linux_test.go:34: DaemonPrivilegedSuite.TestEnableIPForwarding
	 PASS: sysctl_linux_test.go:34: DaemonPrivilegedSuite.TestEnableIPForwarding	0.000s
	 
	 OK: 4 passed
	 --- PASS: Test (0.54s)
	 PASS
	 coverage: 1.9% of statements in ./...
	 ok  	github.com/cilium/cilium/daemon/cmd	0.684s	coverage: 1.9% of statements in ./...
	 level=info msg="Detected mounted BPF filesystem at /sys/fs/bpf" subsys=bpf
	 === RUN   Test
	 START: map_linux_test.go:251: BPFPrivilegedTestSuite.TestBasicManipulation
	 PASS: map_linux_test.go:251: BPFPrivilegedTestSuite.TestBasicManipulation	0.003s
	 
	 START: map_linux_test.go:538: BPFPrivilegedTestSuite.TestCheckAndUpgrade
	 MapTypeHash: no prealloc to prealloc upgrade
	 level=warning msg="Flags mismatch for BPF map" file-path=/sys/fs/bpf/tc/globals/cilium_test_upgrade new=0 old=1 subsys=bpf
	 level=warning msg="Removing map to allow for property upgrade (expect map data loss)" file-path=/sys/fs/bpf/tc/globals/cilium_test_upgrade subsys=bpf
	 MapTypeLRUHash on 4.9 kernel: no prealloc to no prealloc upgrade
	 PASS: map_linux_test.go:538: BPFPrivilegedTestSuite.TestCheckAndUpgrade	0.000s
	 
	 START: map_linux_test.go:699: BPFPrivilegedTestSuite.TestCreateUnpinned
	 PASS: map_linux_test.go:699: BPFPrivilegedTestSuite.TestCreateUnpinned	0.000s
	 
	 START: map_linux_test.go:498: BPFPrivilegedTestSuite.TestDeleteAll
	 PASS: map_linux_test.go:498: BPFPrivilegedTestSuite.TestDeleteAll	0.000s
	 
	 START: map_linux_test.go:338: BPFPrivilegedTestSuite.TestDump
	 PASS: map_linux_test.go:338: BPFPrivilegedTestSuite.TestDump	0.000s
	 
	 START: map_linux_test.go:409: BPFPrivilegedTestSuite.TestDumpReliablyWithCallback
	 PASS: map_linux_test.go:409: BPFPrivilegedTestSuite.TestDumpReliablyWithCallback	0.126s
	 
	 START: map_linux_test.go:100: BPFPrivilegedTestSuite.TestGetMapInfo
	 PASS: map_linux_test.go:100: BPFPrivilegedTestSuite.TestGetMapInfo	0.000s
	 
	 START: map_linux_test.go:533: BPFPrivilegedTestSuite.TestGetModel
	 PASS: map_linux_test.go:533: BPFPrivilegedTestSuite.TestGetModel	0.000s
	 
	 START: map_linux_test.go:114: BPFPrivilegedTestSuite.TestOpen
	 PASS: map_linux_test.go:114: BPFPrivilegedTestSuite.TestOpen	0.000s
	 
	 START: map_linux_test.go:141: BPFPrivilegedTestSuite.TestOpenMap
	 PASS: map_linux_test.go:141: BPFPrivilegedTestSuite.TestOpenMap	0.000s
	 
	 START: map_linux_test.go:160: BPFPrivilegedTestSuite.TestOpenOrCreate
	 level=warning msg="Flags mismatch for BPF map" file-path=/sys/fs/bpf/tc/globals/cilium_test new=0 old=1 subsys=bpf
	 level=warning msg="Removing map to allow for property upgrade (expect map data loss)" file-path=/sys/fs/bpf/tc/globals/cilium_test subsys=bpf
	 PASS: map_linux_test.go:160: BPFPrivilegedTestSuite.TestOpenOrCreate	0.000s
	 
	 START: map_linux_test.go:200: BPFPrivilegedTestSuite.TestOpenParallel
	 PASS: map_linux_test.go:200: BPFPrivilegedTestSuite.TestOpenParallel	0.000s
	 
	 START: map_linux_test.go:658: BPFPrivilegedTestSuite.TestUnpin
	 PASS: map_linux_test.go:658: BPFPrivilegedTestSuite.TestUnpin	0.000s
	 
	 OK: 13 passed
	 --- PASS: Test (0.13s)
	 PASS
	 coverage: 6.9% of statements in ./...
	 ok  	github.com/cilium/cilium/pkg/bpf	2.245s	coverage: 6.9% of statements in ./...
	 === RUN   Test
	 START: link_test.go:34: LinkSuite.TestDeleteByName
	 PASS: link_test.go:34: LinkSuite.TestDeleteByName	0.022s
	 
	 START: link_test.go:72: LinkSuite.TestRename
	 PASS: link_test.go:72: LinkSuite.TestRename	0.040s
	 
	 OK: 2 passed
	 --- PASS: Test (0.06s)
	 PASS
	 coverage: 18.1% of statements in ./...
	 ok  	github.com/cilium/cilium/pkg/datapath/link	0.067s	coverage: 18.1% of statements in ./...
	 === RUN   Test
	 START: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestAgentRestartOptionChanges
	 START: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest
	 level=warning msg="Flags mismatch for BPF map" file-path=/sys/fs/bpf/tc/globals/cilium_tunnel_map new=1 old=0 subsys=bpf
	 level=warning msg="Removing map to allow for property upgrade (expect map data loss)" file-path=/sys/fs/bpf/tc/globals/cilium_tunnel_map subsys=bpf
	 PASS: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest	3.083s
	 
	 START: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest	0.076s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestAgentRestartOptionChanges	0.001s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestAuxiliaryPrefixes
	 START: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest	0.049s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestAuxiliaryPrefixes	0.001s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestNodeUpdateDirectRouting
	 START: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest	0.056s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestNodeUpdateDirectRouting	0.066s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestNodeUpdateEncapsulation
	 START: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest	0.052s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestNodeUpdateEncapsulation	0.002s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestNodeValidationDirectRouting
	 START: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest	0.058s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestNodeValidationDirectRouting	0.001s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestSingleClusterPrefix
	 START: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest	0.059s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestSingleClusterPrefix	0.107s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestUpdateNodeRoute
	 START: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:112: linuxPrivilegedIPv6OnlyTestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:134: linuxPrivilegedIPv6OnlyTestSuite.TearDownTest	0.053s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv6OnlyTestSuite.TestUpdateNodeRoute	0.001s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestAgentRestartOptionChanges
	 START: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest	0.053s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestAgentRestartOptionChanges	0.001s
	 
	 START: node_linux_test.go:956: linuxPrivilegedIPv4OnlyTestSuite.TestArpPingHandling
	 START: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest	0.001s
	 
	 node_linux_test.go:1433:
	     c.Assert(found, check.Equals, true)
	 ... obtained bool = false
	 ... expected bool = true
	 
	 START: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest	0.052s
	 
	 FAIL: node_linux_test.go:956: linuxPrivilegedIPv4OnlyTestSuite.TestArpPingHandling
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestAuxiliaryPrefixes
	 START: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest	0.058s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestAuxiliaryPrefixes	0.001s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestNodeUpdateDirectRouting
	 START: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest	0.055s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestNodeUpdateDirectRouting	0.050s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestNodeUpdateEncapsulation
	 START: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest	0.054s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestNodeUpdateEncapsulation	0.001s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestNodeValidationDirectRouting
	 START: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest	0.050s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestNodeValidationDirectRouting	0.001s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestSingleClusterPrefix
	 START: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest	0.046s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestSingleClusterPrefix	0.002s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestUpdateNodeRoute
	 START: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest	0.002s
	 
	 START: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest
	 PASS: node_linux_test.go:138: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest	0.052s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4OnlyTestSuite.TestUpdateNodeRoute	0.001s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestAgentRestartOptionChanges
	 START: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest
	 PASS: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest
	 PASS: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest	0.041s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestAgentRestartOptionChanges	0.001s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestAuxiliaryPrefixes
	 START: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest
	 PASS: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest
	 PASS: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest	0.057s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestAuxiliaryPrefixes	0.002s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestNodeUpdateDirectRouting
	 START: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest
	 PASS: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest
	 PASS: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest	0.056s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestNodeUpdateDirectRouting	0.050s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestNodeUpdateEncapsulation
	 START: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest
	 PASS: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest
	 PASS: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest	0.045s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestNodeUpdateEncapsulation	0.003s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestNodeValidationDirectRouting
	 START: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest
	 PASS: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest
	 PASS: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest	0.053s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestNodeValidationDirectRouting	0.003s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestSingleClusterPrefix
	 START: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest
	 PASS: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest
	 PASS: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest	0.037s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestSingleClusterPrefix	0.002s
	 
	 START: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestUpdateNodeRoute
	 START: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest
	 PASS: node_linux_test.go:122: linuxPrivilegedIPv4AndIPv6TestSuite.SetUpTest	0.001s
	 
	 START: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest
	 PASS: node_linux_test.go:142: linuxPrivilegedIPv4AndIPv6TestSuite.TearDownTest	0.042s
	 
	 PASS: <autogenerated>:1: linuxPrivilegedIPv4AndIPv6TestSuite.TestUpdateNodeRoute	0.001s
	 
	 OOPS: 21 passed, 1 FAILED
	 --- FAIL: Test (6.64s)
	 FAIL
	 coverage: 4.3% of statements in ./...
	 FAIL	github.com/cilium/cilium/pkg/datapath/linux	7.212s
	 FAIL
	 Makefile:141: recipe for target 'tests-privileged' failed
	 make: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium'
	 
Stderr:
 	 make: *** [tests-privileged] Error 1
	 

=== Test Finished at 2021-07-28T17:27:29Z====
17:27:29 STEP: Running AfterEach for block EntireTestsuite

[[ATTACHMENT|78b249a1_RuntimePrivilegedUnitTests_Run_Tests.zip]]
17:27:29 STEP: Running AfterAll block for EntireTestsuite RuntimePrivilegedUnitTests
17:27:29 STEP: Restarting Cilium


```
</details>

ZIP Links: 
<details><summary>Click to show.</summary>

 https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/5423/artifact/78b249a1_RuntimePrivilegedUnitTests_Run_Tests.zip/78b249a1_RuntimePrivilegedUnitTests_Run_Tests.zip
  https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/5423/artifact/test_results_Cilium-PR-Runtime-4.9_5423_BDD-Test-PR.zip/test_results_Cilium-PR-Runtime-4.9_5423_BDD-Test-PR.zip
 
</details>

Jenkins URL: https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/5423/

If this is a duplicate of an existing flake, comment 'Duplicate of #\<issue-number>' and close this issue.

### PR DESCRIPTION
**Pull request by aanm**
We can inspect the neighLastPingByNextHop map to check
when insertNeighbor() or deleteNeighbor() was called.

Fixes: e68848b98004 ("remove ARP entries left from previous Cilium run")
Signed-off-by: André Martins <andre@cilium.io>

Fixes https://github.com/cilium/cilium/issues/17034

### CODE REVIEW

**Comment by aanm** [comment]
test-runtime

File: pkg/datapath/linux/node_linux_test.go [hunk 1]
```diff
@@ -1405,7 +1405,7 @@ func (s *linuxPrivilegedIPv4OnlyTestSuite) TestArpPingHandling(c *check.C) {
 	c.Assert(found, check.Equals, false)
 
 	c.Assert(linuxNodeHandler.NodeAdd(nodev3), check.IsNil)
-	time.Sleep(100 * time.Millisecond) // insertNeighbor is invoked async
+	wait(nodev3.Identity(), nil, false)
```
Comment (brb) [inline pkg/datapath/linux/node_linux_test.go]: Either you need to pass the `now` value or make the function `wait` to accept `before = nil`.

**Review by brb — CHANGES_REQUESTED** [review]

**Comment by brb** [comment]
I'm wondering why all of sudden we started to hit the TestArp flakes again. Another issue: https://github.com/cilium/cilium/issues/17020.

File: pkg/datapath/linux/node_linux_test.go [hunk 2]
```diff
@@ -1422,7 +1423,9 @@ func (s *linuxPrivilegedIPv4OnlyTestSuite) TestArpPingHandling(c *check.C) {
 	c.Assert(found, check.Equals, true)
 
 	// We have stored the devices in NodeConfigurationChanged
+	now = time.Now()
 	linuxNodeHandler.NodeCleanNeighbors()
+	wait(nodev3.Identity(), &now, true)
```
Comment (brb) [inline pkg/datapath/linux/node_linux_test.go]: `now` is not needed for the deletion.

**Comment by aanm** [comment]
test-runtime

**Review by brb — APPROVED** [review]
:rocket: :moon:

**Comment by aanm** [comment]
test-runtime

**Comment by aanm** [comment]
test-runtime
