### PR TITLE
Fix various bugs related to restart of StatefulSet pods that may result in connectivity issues

### LINKED ISSUE #30409: Cilium-agent incorrectly handles rollouts of statefulsets
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There are multiple issues with how we handle the recreation of statefulset pods **on the same node**. This is specific to statefulsets as after the rolling upgrade of them, they have the same namespace and name.

1. Informer lagging case

In case of informer lagging, it might contain an old pod object in store, which we use for assigning ownerReference.
Here we get pod information for ownerReference: https://github.com/cilium/cilium/blob/bacf2e8718e603b6b74bd599711d73f3f7bfcddb/pkg/endpointmanager/endpointsynchronizer.go#L172
which comes from `fetchK8sMetadataForEndpoint`: https://github.com/cilium/cilium/blob/63e2676ccbe992af3243253725dab2bfc7981a9d/daemon/cmd/endpoint.go#L443
and only in HighScaleIPCache case it's fetched from k8s control plane, in most of the cases it's fetched from local store: 
https://github.com/cilium/cilium/blob/e43b759bab69c9f978fd893a75ae7c3f03d184b0/daemon/cmd/state.go#L193-L199

This can be easily reproduced by adding artificial `time.Sleep` in Add/Update/Delete handlers in the pod informer. When ownerReference is set to the old pod then kube-controller-manager GCes CiliumEndpoint and `sync-to-k8s-ciliumendpoint` controller never recreates CiliumEndpoint as it stores local copy and doesn't react to this delete event thinking that there is correct CEP: https://github.com/cilium/cilium/blob/bacf2e8718e603b6b74bd599711d73f3f7bfcddb/pkg/endpointmanager/endpointsynchronizer.go#L138

Potential solutions:
- During CNI Add verify that UID of the pod is the same as the pod in informer's store
- Make sync-to-k8s-ciliumendpoint controller react to changes to CiliumEndpoint.

This is more likely to occur in 1.13 as we don't use Resource[T] for informer updates, but still can happen in 1.14/1.15 under high pod churn on the node.

2. Delayed Delete pod event

CNI ADD/CNI DEL are independent from pod informer updates. In case statefulset pod is recreated on the same node, we might trigger a Delete event after recreating statefulset pod. As it has the same namespace/name it can cause some issues, for example, LocalRedirectPolicy depends only on namespace/name of the pod:
- trigger of deletion - https://github.com/cilium/cilium/blob/fbebd4062d96e330d82f0e976145af4711f0f4f2/pkg/k8s/watchers/pod.go#L542-L544
- id of policy entries consists only of namespace/name: https://github.com/cilium/cilium/blob/825b91d17489b8e7f4d82ce92b402a2b2581e97d/pkg/redirectpolicy/manager.go#L316-L319

Potential solution:
We should definitely review this case and also take into account UID of pod when receiving delete event (I only did initial review where I found issue with LocalRedirectPolicy).

3. Missed Delete/Add event

In some very rare cases, informer may skip the Delete/Add event and trigger the Update event instead with references to a new and old pod (because they have the same namespace/name). For example, this can happen when watch requests to k8s control plane gets terminated and the informer performs a relist. 

Update trigger: https://github.com/cilium/cilium/blob/fbebd4062d96e330d82f0e976145af4711f0f4f2/pkg/k8s/watchers/pod.go#L140-L149

This can potentially cause for example not detecting pod label's change. Scenario:
- Pod A with label X=Y
- Pod A gets deleted and recreated as Pod A' on the same node but without label X=Y (Pod A' has the same namespace/name)
- Pod A' gets patched with label X=Y
If the informer skips Delete/Add/Update events and triggers an update between Pod A with labels -> Pod A' with labels, we might fail to detect a patch of labels in the last step as we would be comparing Pod A and Pod A': https://github.com/cilium/cilium/blob/fbebd4062d96e330d82f0e976145af4711f0f4f2/pkg/k8s/watchers/pod.go#L361

Potential solution:
- Take into account UID of the pod when handling an update event. 

### Cilium Version

1.13-1.15 affected

### Kernel Version

N/A

### Kubernetes Version

N/A

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by christarazi**
- **k8s/watcher: Remove outdated comments about K8sEventHandover**
- **daemon, endpoint: Consolidate K8s metadata into struct**
- **watchers: Detect Pod UID changes**
- **daemon,endpoint,cni: Pass pod UID through CNI ADD**
- **k8s/watchers: Fix pod IP modified check**

--- 

Fixes: https://github.com/cilium/cilium/issues/30409

### CODE REVIEW

File: pkg/identity/identity.go [hunk 1]
```diff
@@ -64,6 +64,7 @@ type IPIdentityPair struct {
 	Metadata     string          `json:"Metadata"`
 	K8sNamespace string          `json:"K8sNamespace,omitempty"`
 	K8sPodName   string          `json:"K8sPodName,omitempty"`
+	K8sUID       string          `json:"K8sUID,omitempty"`
```
Comment (christarazi) [inline pkg/identity/identity.go]: This is a change to the API model of the kvstore interaction. However, given that it's an additive change, it should be fully JSON backwards/forwards compat.

**Comment by tklauser** [comment]
Is this fix something we want to backport to 1.15? From the linked issue it seems all currently supported stable versions are affected.

File: pkg/endpoint/endpoint.go [hunk 2]
```diff
@@ -292,6 +292,10 @@ type Endpoint struct {
 	// Immutable after Endpoint creation.
 	K8sNamespace string
 
+	// K8sUID is the Kubernetes UID of the pod. Passed directly from the CNI.
+	// Immutable after Endpoint creation.
+	K8sUID string
```
Comment (tklauser) [inline pkg/endpoint/endpoint.go:296]: Given this is immutable after endpoint creation, should this be unexported?

File: pkg/endpoint/api.go [hunk 3]
```diff
@@ -76,6 +76,7 @@ func NewEndpointFromChangeModel(ctx context.Context, owner regeneration.Owner, p
 	ep.dockerEndpointID = base.DockerEndpointID
 	ep.K8sPodName = base.K8sPodName
 	ep.K8sNamespace = base.K8sNamespace
+	ep.K8sUID = base.K8sUID
```
Comment (tklauser) [inline pkg/endpoint/api.go:82]: Do we need to consider this field during endpoint restore serialization/deserialization in endpoint (i.e. `(*Endpoint).toSerializedEndpoint` and `(*Endpoint).ep.fromSerializedEndpoint`) as well?

**Review by tklauser — APPROVED** [review]
Thanks for the descriptive commit messages!

LGTM with some non-blocking questions inline.

File: pkg/k8s/watchers/pod.go [hunk 4]
```diff
@@ -400,7 +405,9 @@ func (k *K8sWatcher) updateK8sPodV1(oldK8sPod, newK8sPod *slim_corev1.Pod) error
 	}
 
 	for _, podEP := range podEPs {
-		if labelsChanged {
+		if labelsChanged || uidChanged {
+			// Consider a UID change the same as a label change in case the pod's
+			// identity needs to be updated, see GH-30409.
```
Comment (aanm) [inline pkg/k8s/watchers/pod.go]: Please leave comments on why it's not necessary to do the same for when the annotations change.

File: daemon/cmd/endpoint.go [hunk 5]
```diff
@@ -453,6 +455,13 @@ func (d *Daemon) createEndpoint(ctx context.Context, owner regeneration.Owner, e
 		pod, k8sMetadata, err := d.fetchK8sMetadataForEndpoint(ep.K8sNamespace, ep.K8sPodName)
 		if err != nil {
 			ep.Logger("api").WithError(err).Warning("Unable to fetch kubernetes labels")
+		} else if types.UID(ep.K8sUID) != pod.GetUID() {
+			log.WithFields(logrus.Fields{
+				logfields.K8sPodName: ep.K8sNamespace + "/" + ep.K8sPodName,
+				logfields.K8sUID:     ep.K8sUID,
+			}).Warn("Detected outdated Pod UID during Endpoint creation. " +
+				"The Endpoint may be created with outdated identity due to delay in Kubernetes event updates, i.e. until Pod event is processed by Cilium. " +
+				"If the Endpoint persists with an outdated identity for an extended period of time, please report an issue.")
```
Comment (aanm) [inline daemon/cmd/endpoint.go]: I'm not sure if we should Warn in here, this is a transient error and we will recover afterwards.

File: pkg/endpoint/api.go (hunk 3 above)
Comment (aanm) [reply pkg/endpoint/api.go:82]: Yes!

File: pkg/k8s/watchers/pod.go [hunk 6]
```diff
@@ -539,14 +539,29 @@ func (k *K8sWatcher) deleteK8sPodV1(pod *slim_corev1.Pod) error {
...
+	// CNI ADD/DELETE's, it's necessary to check whether this pod event is
+	// outdated. StatefulSets do not have a unique namespace/name, so therefore
+	// we rely on UIDs instead for the check.
+	//
+	// Ensure that any downstream subscriber disambiguates pods as
+	// namespace/name as an index is not sufficient.
+	//
+	// This specific scenario is to guard against a delayed delete event. See
+	// GH-30409.
+
```
Comment (aanm) [inline pkg/k8s/watchers/pod.go]: I'm lost, you left this comment here but don't we need some code as well? :confused:

File: clustermesh-apiserver/clustermesh/root.go [hunk 7]
```diff
@@ -277,6 +277,11 @@ func (es *endpointSynchronizer) upsert(ctx context.Context, key resource.Key, ob
 					entry.Key = uint8(endpoint.Encryption.Key)
 				}
 
+				if len(endpoint.OwnerReferences) > 0 {
+					// Assume the first ownerRef is the pod.
+					entry.K8sUID = string(endpoint.OwnerReferences[0].UID)
+				}
+
```
Comment (aanm) [inline clustermesh-apiserver/clustermesh/root.go]: No, we should check the ownerreference type.

**Review by aanm — CHANGES_REQUESTED** [review]

File: pkg/endpoint/api.go (hunk 3 above)
Comment (christarazi) [reply pkg/endpoint/api.go:82]: Thanks, good catch!

File: pkg/endpoint/endpoint.go (hunk 2 above)
Comment (christarazi) [reply pkg/endpoint/endpoint.go:296]: Don't we need to exported for marshaling purposes? As in `json.{Unm,M}arshal` requires fields to be exported for them to get detected.

File: pkg/k8s/watchers/pod.go (hunk 4 above)
Comment (christarazi) [reply pkg/k8s/watchers/pod.go]: I'll update the comment. The short story is that annotations don't affect identities, so we don't need to trigger the logic for updating labels if the annotations changed.

File: daemon/cmd/endpoint.go (hunk 5 above)
Comment (christarazi) [reply daemon/cmd/endpoint.go]: Wouldn't it be useful to know that the bugs we've hit with statefulsets were detected and Cilium is warning the user that there might be a period of time where the identity is out of date? It seems useful to me.

File: pkg/k8s/watchers/pod.go (hunk 6 above)
Comment (christarazi) [reply pkg/k8s/watchers/pod.go]: I've clarified the comment to be a note to readers/developers who might add new code below this comment in the future to keep this case in mind.

**Comment by christarazi** [comment]
@aanm @tklauser Here's the [diff](https://github.com/cilium/cilium/compare/13d3ac71eb2ba1d4018d6d7307880428a652dd7a..3eeb5d3bfe85570e296fb661631c1e31c74a0047) for implementing your feedback.

File: pkg/endpoint/endpoint.go (hunk 2 above)
Comment (tklauser) [reply pkg/endpoint/endpoint.go:296]: Yeah, good point. I wasn't considering this struct is marshalled.

**Review by tklauser — APPROVED** [review]
> @aanm @tklauser Here's the [diff](https://github.com/cilium/cilium/compare/13d3ac71eb2ba1d4018d6d7307880428a652dd7a..3eeb5d3bfe85570e296fb661631c1e31c74a0047) for implementing your feedback.

LGTM, thank you Chris!

**Review by marseel — COMMENTED** [review]
Clustermesh changes look good, but I will take a look at the whole PR if you don't mind Chris, before approving :)

File: pkg/endpoint/endpoint.go [hunk 8]
```diff
@@ -1308,6 +1312,14 @@ func (e *Endpoint) GetK8sNamespace() string {
 	return ns
 }
 
+// GetK8sUID returns the UID of the pod if the endpoint represents a Kubernetes
+// pod.
+func (e *Endpoint) GetK8sUID() string {
```
Comment (marseel) [inline pkg/endpoint/endpoint.go:1273]: nit: this is not used anywhere, right? I would probably remove it.

File: pkg/endpoint/api.go (hunk 3 above)
Comment (marseel) [reply pkg/endpoint/api.go:82]: ~From what I see we currently don't use UID after endpoint restoration, right? Just wanted to confirm my understanding that currently in this PR we only use UID during endpoint creation AFAIK?~

File: pkg/k8s/watchers/cilium_endpoint.go [hunk 9]
```diff
@@ -116,13 +116,13 @@ func (k *K8sWatcher) endpointUpdated(oldEndpoint, endpoint *types.CiliumEndpoint
 					}
 				}
 				if !v4Added {
-					portsChanged := k.ipcache.DeleteOnMetadataMatch(oldPair.IPV4, source.CustomResource, endpoint.Namespace, endpoint.Name)
+					portsChanged := k.ipcache.DeleteOnMetadataMatch(oldPair.IPV4, source.CustomResource, endpoint.Namespace, endpoint.Name, string(endpoint.UID))
```
Comment (marseel) [inline pkg/k8s/watchers/cilium_endpoint.go]: This is incorrect UID, right?
Seems to me like it's CiliumEndpoint UID and not pod UID/ ownerReference UID.

File: pkg/ipcache/ipcache.go [hunk 10]
```diff
@@ -759,11 +761,11 @@ func (ipc *IPCache) GetNamedPorts() (npm types.NamedPortMultiMap) {
 
 // DeleteOnMetadataMatch removes the provided IP to security identity mapping from the IPCache
 // if the metadata cache holds the same "owner" metadata as the triggering pod event.
-func (ipc *IPCache) DeleteOnMetadataMatch(IP string, source source.Source, namespace, name string) (namedPortsChanged bool) {
+func (ipc *IPCache) DeleteOnMetadataMatch(IP string, source source.Source, namespace, name, uid string) (namedPortsChanged bool) {
 	ipc.mutex.Lock()
 	defer ipc.mutex.Unlock()
 	k8sMeta := ipc.getK8sMetadata(IP)
-	if k8sMeta != nil && k8sMeta.Namespace == namespace && k8sMeta.PodName == name {
+	if k8sMeta != nil && k8sMeta.Namespace == namespace && k8sMeta.PodName == name && k8sMeta.UID == uid {
```
Comment (marseel) [inline pkg/ipcache/ipcache.go]: Isn't `k8sMeta.UID` going to be always empty for restored endpoints after upgrade :thinking: ?

File: pkg/ipcache/ipcache.go [hunk 11]
```diff
@@ -759,11 +761,11 @@ func (ipc *IPCache) GetNamedPorts() (npm types.NamedPortMultiMap) {
 
 // DeleteOnMetadataMatch removes the provided IP to security identity mapping from the IPCache
 // if the metadata cache holds the same "owner" metadata as the triggering pod event.
-func (ipc *IPCache) DeleteOnMetadataMatch(IP string, source source.Source, namespace, name string) (namedPortsChanged bool) {
+func (ipc *IPCache) DeleteOnMetadataMatch(IP string, source source.Source, namespace, name, uid string) (namedPortsChanged bool) {
```
Comment (marseel) [inline pkg/ipcache/ipcache.go]: Commenting on random like, this refers to line 304:
We probably want to add UID to `scopedLog`:
```
			scopedLog = scopedLog.WithFields(logrus.Fields{
				logfields.K8sPodName:   k8sMeta.PodName,
				logfields.K8sNamespace: k8sMeta.Namespace,
				logfields.NamedPorts:   k8sMeta.NamedPorts,
			})
```

**Review by marseel — CHANGES_REQUESTED** [review]
Huge thanks @christarazi for working on this, looks good overall.

I am a bit worried about the upgrade path though, so I left a few comments.

File: pkg/k8s/watchers/cilium_endpoint.go (hunk 9 above)
Comment (christarazi) [reply pkg/k8s/watchers/cilium_endpoint.go]: Good point, I'll fix this up.

File: pkg/ipcache/ipcache.go (hunk 10 above)
Comment (christarazi) [reply pkg/ipcache/ipcache.go]: It will be and so this check will be true, so it shouldn't be an issue. When a new pod is created while running the new code, then the UID will be non-empty. Either the UID is set or it's empty, in other words, there shouldn't be a situation where it's mixed. So I don't see an issue, do you have something in mind?

File: pkg/k8s/watchers/cilium_endpoint.go (hunk 9 above)
Comment (christarazi) [reply pkg/k8s/watchers/cilium_endpoint.go]: <details><summary>Diff</summary>
<p>

```diff
commit b6be38f8e5de748c852376f87a2737d09a83855d
Author: Chris Tarazi <chris@isovalent.com>
Date:   Tue Apr 9 14:02:34 2024 -0700

    fixup! ipcache,watchers,identity: Pass pod UID into ipcache metadata
    
    Signed-off-by: Chris Tarazi <chris@isovalent.com>

diff --git a/api/v1/models/ip_list_entry_metadata.go b/api/v1/models/ip_list_entry_metadata.go
index 75a0099252..6efafe32e9 100644
--- a/api/v1/models/ip_list_entry_metadata.go
+++ b/api/v1/models/ip_list_entry_metadata.go
@@ -29,6 +29,9 @@ type IPListEntryMetadata struct {
 	// Source of the IP entry and its metadata
 	// Example: k8s
 	Source string `json:"source,omitempty"`
+
+	// UID of the backing resource to the IP (e.g. Kubernetes pod UID)
+	UID string `json:"uid,omitempty"`
 }
 
 // Validate validates this IP list entry metadata
diff --git a/api/v1/openapi.yaml b/api/v1/openapi.yaml
index 3a773d5ceb..ca93a92e1b 100644
--- a/api/v1/openapi.yaml
+++ b/api/v1/openapi.yaml
@@ -3787,6 +3787,9 @@ definitions:
       name:
         description: Name assigned to the IP (e.g. Kubernetes pod name)
         type: string
+      uid:
+        description: UID of the backing resource to the IP (e.g. Kubernetes pod UID)
+        type: string
   NamedPorts:
     description: |-
       List of named Layer 4 port and protocol pairs which will be used in Network
diff --git a/api/v1/server/embedded_spec.go b/api/v1/server/embedded_spec.go
index 7314db4792..37e3b02204 100644
--- a/api/v1/server/embedded_spec.go
+++ b/api/v1/server/embedded_spec.go
@@ -3573,6 +3573,10 @@ func init() {
           "description": "Source of the IP entry and its metadata",
           "type": "string",
           "example": "k8s"
+        },
+        "uid": {
+          "description": "UID of the backing resource to the IP (e.g. Kubernetes pod UID)",
+          "type": "string"
         }
       }
     },
@@ -9423,6 +9427,10 @@ func init() {
           "description": "Source of the IP entry and its metadata",
           "type": "string",
           "example": "k8s"
+        },
+        "uid": {
+          "description": "UID of the backing resource to the IP (e.g. Kubernetes pod UID)",
+          "type": "string"
         }
       }
     },
diff --git a/daemon/cmd/ipcache.go b/daemon/cmd/ipcache.go
index 31d85eac9a..9fdf84792a 100644
--- a/daemon/cmd/ipcache.go
+++ b/daemon/cmd/ipcache.go
@@ -86,6 +86,7 @@ func (ipc *ipCacheDumpListener) OnIPIdentityCacheChange(modType ipcache.CacheMod
 			Source:    string(newID.Source),
 			Namespace: k8sMeta.Namespace,
 			Name:      k8sMeta.PodName,
+			UID:       k8sMeta.UID,
 			// TODO (jrajahalme): Consider if named ports should be
 			//                    made visible in the model.
 		}
diff --git a/pkg/k8s/factory_functions.go b/pkg/k8s/factory_functions.go
index 46eec43c94..42ef3a411f 100644
--- a/pkg/k8s/factory_functions.go
+++ b/pkg/k8s/factory_functions.go
@@ -457,8 +457,9 @@ func TransformToCiliumEndpoint(obj interface{}) (interface{}, error) {
 				ResourceVersion: concreteObj.ObjectMeta.ResourceVersion,
 				// We don't need to store labels nor annotations because
 				// they are not used by the CEP handlers.
-				Labels:      nil,
-				Annotations: nil,
+				Labels:          nil,
+				Annotations:     nil,
+				OwnerReferences: slim_metav1.SlimOwnerReferences(concreteObj.OwnerReferences),
 			},
 			Encryption: func() *cilium_v2.EncryptionSpec {
 				enc := concreteObj.Status.Encryption
@@ -492,8 +493,9 @@ func TransformToCiliumEndpoint(obj interface{}) (interface{}, error) {
 					ResourceVersion: ciliumEndpoint.ObjectMeta.ResourceVersion,
 					// We don't need to store labels nor annotations because
 					// they are not used by the CEP handlers.
-					Labels:      nil,
-					Annotations: nil,
+					Labels:          nil,
+					Annotations:     nil,
+					OwnerReferences: slim_metav1.SlimOwnerReferences(ciliumEndpoint.ObjectMeta.OwnerReferences),
 				},
 				Encryption: func() *cilium_v2.EncryptionSpec {
 					enc := ciliumEndpoint.Status.Encryption
diff --git a/pkg/k8s/watchers/cilium_endpoint.go b/pkg/k8s/watchers/cilium_endpoint.go
index 5e62d3273e..7cc44c1288 100644
--- a/pkg/k8s/watchers/cilium_endpoint.go
+++ b/pkg/k8s/watchers/cilium_endpoint.go
@@ -167,10 +167,11 @@ func (k *K8sWatcher) endpointUpdated(oldEndpoint, endpoint *types.CiliumEndpoint
 		return
 	}
 
+	podUID := k.fetchPodUIDForCEP(endpoint)
 	k8sMeta := &ipcache.K8sMetadata{
 		Namespace:  endpoint.Namespace,
 		PodName:    endpoint.Name,
-		UID:        string(endpoint.UID),
+		UID:        podUID,
 		NamedPorts: make(ciliumTypes.NamedPortMap, len(endpoint.NamedPorts)),
 	}
 	for _, port := range endpoint.NamedPorts {
@@ -206,18 +207,19 @@ func (k *K8sWatcher) endpointUpdated(oldEndpoint, endpoint *types.CiliumEndpoint
 }
 
 func (k *K8sWatcher) endpointDeleted(endpoint *types.CiliumEndpoint) {
+	podUID := k.fetchPodUIDForCEP(endpoint)
 	if endpoint.Networking != nil {
 		namedPortsChanged := false
 		for _, pair := range endpoint.Networking.Addressing {
 			if pair.IPV4 != "" {
-				portsChanged := k.ipcache.DeleteOnMetadataMatch(pair.IPV4, source.CustomResource, endpoint.Namespace, endpoint.Name, string(endpoint.UID))
+				portsChanged := k.ipcache.DeleteOnMetadataMatch(pair.IPV4, source.CustomResource, endpoint.Namespace, endpoint.Name, podUID)
 				if portsChanged {
 					namedPortsChanged = true
 				}
 			}
 
 			if pair.IPV6 != "" {
-				portsChanged := k.ipcache.DeleteOnMetadataMatch(pair.IPV6, source.CustomResource, endpoint.Namespace, endpoint.Name, string(endpoint.UID))
+				portsChanged := k.ipcache.DeleteOnMetadataMatch(pair.IPV6, source.CustomResource, endpoint.Namespace, endpoint.Name, podUID)
 				if portsChanged {
 					namedPortsChanged = true
 				}
@@ -228,3 +230,20 @@ func (k *K8sWatcher) endpointDeleted(endpoint *types.CiliumEndpoint) {
 		}
 	}
 }
+
+func (k *K8sWatcher) fetchPodUIDForCEP(endpoint *types.CiliumEndpoint) string {
+	// Fetch the Pod UID from the internal Endpoint object if it exists,
+	// otherwise check the ownerRef of the CEP object.
+	var podUID string
+	ep := k.endpointManager.LookupCEPName(endpoint.Namespace + "/" + endpoint.Name)
+	if ep != nil {
+		// If the endpoint is local to this node, then this should suffice.
+		podUID = ep.GetK8sUID()
+	}
+	if podUID == "" {
+		if len(endpoint.OwnerReferences) > 0 && endpoint.OwnerReferences[0].Kind == "Pod" {
+			podUID = string(endpoint.OwnerReferences[0].UID)
+		}
+	}
+	return podUID
+}
```

</p>
</details>

File: pkg/endpoint/endpoint.go (hunk 8 above)
Comment (christarazi) [reply pkg/endpoint/endpoint.go:1273]: Now it's used in the below fixup commit

File: pkg/k8s/watchers/cilium_endpoint.go [hunk 12]
```diff
@@ -227,3 +230,20 @@ func (k *K8sWatcher) endpointDeleted(endpoint *types.CiliumEndpoint) {
 		}
 	}
 }
+
+func (k *K8sWatcher) fetchPodUIDForCEP(endpoint *types.CiliumEndpoint) string {
+	// Fetch the Pod UID from the internal Endpoint object if it exists,
```
Comment (marseel) [inline pkg/k8s/watchers/cilium_endpoint.go]: I find it a bit counter-intuitive that we are mixing object information received from k8s control plane and locally cached endpointManager. 

I would probably reverse order and first try ownerReference as a more reasonable/reliable source of truth, which will work for every CEP as long as it's managed by Cilium

File: pkg/k8s/watchers/cilium_endpoint.go (hunk 9 above)
Comment (marseel) [reply pkg/k8s/watchers/cilium_endpoint.go]: You've updated it in endpointDelete, but endpointUpdate is still having incorrect endpoint.uid, right?

File: pkg/ipcache/ipcache.go (hunk 10 above)
Comment (marseel) [reply pkg/ipcache/ipcache.go]: okay, I was thinking about deletion of pod that was previously created with versions that didn't support UID:
- Pod is running with the previous version of Cilium that doesn't handle UID - so when we restore endpoint k8s it won't have UID
- We upgrade it to version from this PR that now handles UID
- new cilium-agent restores the endpoint without UID in k8sMeta
- I guess we receive endpoint update event during the initialization and update k8s metadata? This is open question, I haven't checked code in depth, but looking at https://github.com/cilium/cilium/blob/dbb579ada86ebcde8bf41b10a55b23528099d4f8/pkg/ipcache/ipcache.go#L332 we might not be updating k8sMeta if identity did not change?
- endpoint is deleted and call to `DeleteOnMetadataMatch` has uid in it, so we need to make sure k8sMeta.UID is set after upgrade (previous point that I haven't fully checked). If it isn't then we would not trigger delete in ipcache even though we should.

File: daemon/cmd/endpoint.go (hunk 5 above)
Comment (marseel) [reply daemon/cmd/endpoint.go]: +1 from me for warning, I think it's useful. 

Another way to prevent that would be to fail CNI ADD when we don't have a pod in the informer store and let Kubelet retry later on, but this has lots of other consequences. Or wait for a fixed amount of time for store to get updated pod and if it doesn't happen then fail CNI ADD. But this is probably quite a lot of work and outside of this PR's scope.

Comment (marseel) [reply daemon/cmd/endpoint.go]: Another place similar to this is metadataResolver https://github.com/cilium/cilium/blob/1518818397ac98be01573bb0c52cd0ece122f3f7/pkg/endpoint/endpoint.go#L1776
where we could get a "random" pod instead of the correct one in case the store is lagging.

How about an alternative approach:
- we try to get the pod from the store
- if it's not there or has incorrect UID we fetch it from k8s control plane directly like in high-scale case. Not ideal, but in most cases, it should not be triggered and it would ensure we have the correct pod information always.

**Review by marseel — CHANGES_REQUESTED** [review]

File: pkg/k8s/watchers/cilium_endpoint.go (hunk 9 above)
Comment (christarazi) [reply pkg/k8s/watchers/cilium_endpoint.go]: I'm not sure I understand what else `endpointUpdate` needs? It's already been fixed to use the pod UID.

File: pkg/ipcache/ipcache.go (hunk 10 above)
Comment (christarazi) [reply pkg/ipcache/ipcache.go]: One approach we can take here is to update the endpointsynchronizer `sync-to-k8s-ciliumendpoint` controller to also set the pod UID in the `Endpoint` object similar to what's being done already for CEP UID. However, there's no guarantee that this controller runs before [the ipache code above](https://github.com/cilium/cilium/blob/dbb579ada86ebcde8bf41b10a55b23528099d4f8/pkg/ipcache/ipcache.go#L332) is invoked. I'm not sure of another way around this than to skip the UID check if the UID is empty in [that ipcache code](https://github.com/cilium/cilium/blob/dbb579ada86ebcde8bf41b10a55b23528099d4f8/pkg/ipcache/ipcache.go#L332). What do you think?

File: pkg/k8s/watchers/cilium_endpoint.go (hunk 12 above)
Comment (christarazi) [reply pkg/k8s/watchers/cilium_endpoint.go]: Fair enough, I can switch it to just the ownerReference.

File: daemon/cmd/endpoint.go (hunk 5 above)
Comment (christarazi) [reply daemon/cmd/endpoint.go]: While you are correct, I don't see any negative consequences for having an out-of-date pod object reference in the `Endpoint`. In fact, we don't even update the reference on pod update events, so they are pretty much always stale after `metadataResolver` runs. This is because we don't use the metadata for anything else besides initially fetching the labels for identity purposes. Label changes are detected in the pod update events, but the reference to the object is never updated.

To be clear, the only "negative consequence" is that it will have the same behavior that the warning log msg mentions: the endpoint's identity will be outdated until a pod update event comes in.

Is there something else I'm missing?

Comment (marseel) [reply daemon/cmd/endpoint.go]: > I don't see any negative consequences for having an out-of-date pod object reference

If we have reference to previous pod with incorrect UID then in endpoint synchronizer we will set ownerReference to incorrect pod that no longer exists:
https://github.com/cilium/cilium/blob/02d04b34005c45d955a6850d3faf561d9eae8f78/pkg/endpointmanager/endpointsynchronizer.go#L115
which means, kube-controller-manager will GC that CEP immediately.

File: pkg/ipcache/ipcache.go (hunk 10 above)
Comment (marseel) [reply pkg/ipcache/ipcache.go]: > I'm not sure of another way around this than to skip the UID check if the UID is empty

yea, I was thinking we could do something like that and then in 1.17 we could assume that UID is always non-empty. That would be probably the safest approach.

File: pkg/k8s/watchers/cilium_endpoint.go (hunk 9 above)
Comment (christarazi) [reply pkg/k8s/watchers/cilium_endpoint.go]: I've updated the `defer` function to replace the remaining reference to `endpoint.UID`.

File: daemon/cmd/endpoint.go [hunk 13]
```diff
@@ -455,6 +457,13 @@ func (d *Daemon) createEndpoint(ctx context.Context, owner regeneration.Owner, e
...
```
Comment (learnitall) [inline daemon/cmd/endpoint.go]: [This question is related to https://github.com/cilium/cilium/pull/31605/commits/7dd6b4c697cb253634bdc4847c209c6c4d419f8f#r1550314914 but I'm starting it in another thread as to not interrupt the conversation surrounding handling the case of outdated pod UID]

I think the log message is a bit ambiguous in a couple of ways, so I have some clarifying questions:

1. What is "an extended period of time"? One minute? Five minutes?
2. Would users have to keep in mind the identity change grace period when determining how long it took for an Endpoint's identity to update after seeing this message?
3. Is the delay in Kubernetes event updates normal or expected? I feel this log message could be a great indicator when an API server is backed up with events and needs some attention, but the message tells users to only take action based off of the endpoint identity update delay.

File: pkg/redirectpolicy/manager_test.go [hunk 14]
```diff
@@ -182,9 +182,11 @@ var (
...
 		},
 	}
-	pod1ID = k8s.ServiceID{
-		Name:      pod1.Name,
-		Namespace: pod1.Namespace,
+	pod1ID = podID{
+		ServiceID: k8s.ServiceID{
+			Name:      pod1.Name,
+			Namespace: pod1.Namespace,
+		},
```
Comment (learnitall) [inline pkg/redirectpolicy/manager_test.go]: Can we add a test here to check for a regression in the behavior that this commit fixes?

File: clustermesh-apiserver/clustermesh/root.go [hunk 15]
```diff
@@ -277,6 +277,10 @@ func (es *endpointSynchronizer) upsert(ctx context.Context, key resource.Key, ob
 					entry.Key = uint8(endpoint.Encryption.Key)
 				}
 
+				if len(endpoint.OwnerReferences) > 0 && endpoint.OwnerReferences[0].Kind == "Pod" {
```
Comment (learnitall) [inline clustermesh-apiserver/clustermesh/root.go]: Why do we only check the first owner reference and not iterate through the slice to look for a Pod owner?

**Review by learnitall — COMMENTED** [review]
Thank you for the helpful commit descriptions and comments! I have a couple of clarifying questions. My main concern here is that the PR doesn't include any tests which look for regressions in this behavior. It would be awesome if new go-based tests could be added to check for each of the scenarios laid out in #30409.

File: clustermesh-apiserver/clustermesh/root.go (hunk 15 above)
Comment (christarazi) [reply clustermesh-apiserver/clustermesh/root.go]: The ownerRef on a CEP is only expected to be a Pod. There aren't multiple ownerRefs.

File: pkg/redirectpolicy/manager_test.go (hunk 14 above)
Comment (christarazi) [reply pkg/redirectpolicy/manager_test.go]: While I'm not opposed to adding tests, I'm afraid that in order to fully test out the scenarios within https://github.com/cilium/cilium/issues/30409, it would not suffice in a single package unit test nor would it be easy to write an e2e test for it, which requires figuring out a set of steps to repro the conditions. The alternative is to write a controlplane test, but I'm also afraid that that framework is not quite up to spec to support the testing needed, i.e. creating endpoints, simulating delays in k8s events, etc. and would be non-trivial to do so. I'm hesitant to block the PR on this. I also understand that it's not ideal to have a PR without tests either. :/

On the plus side, the changes are relatively easy to understand especially regarding the LRP code, which essentially is updated to query an internal map with a more unique key, instead.

File: daemon/cmd/endpoint.go (hunk 5 above)
Comment (christarazi) [reply daemon/cmd/endpoint.go]: I've changed the code to fetch the latest pod object in the case that the UID is mismatching during endpoint creation.

**Comment by christarazi** [comment]
@marseel I've pushed some temp commits for ease of review. See the last 4 commits. They will get squashed into the original commits once they're good to go.

**Review by joamaki — APPROVED** [review]

File: daemon/cmd/endpoint.go (hunk 5 above)
Comment (squeed) [reply daemon/cmd/endpoint.go]: How will the user know that a pod has been successfully updated? Should we log a message indicating that a pod was stale for XXX minutes?

Also, error messages "aren't real", only alerts are. There should be a metric for whether or not an endpoint has a correct pod.

File: pkg/redirectpolicy/manager.go [hunk 16]
```diff
@@ -46,8 +47,12 @@ type svcCache interface {
 	GetServiceFrontendIP(svcID k8s.ServiceID, svcType lb.SVCType) net.IP
 }
 
-// podID is pod name and namespace
-type podID = k8s.ServiceID
+// podID is a unique identifier for pods.
+type podID = struct {
+	k8s.ServiceID
+
+	uid types.UID
```
Comment (squeed) [inline pkg/redirectpolicy/manager.go]: Careful here. If a pod is deleted and added with the same name, it is possible for the shared informer to coalesce this in to a single update.

As a general rule, unless we really need to associate with the specific "version" of a pod, we should ignore UIDs.

File: pkg/identity/identity.go (hunk 1 above)
Comment (squeed) [inline pkg/identity/identity.go]: Why do we need to persist the pod UID in the kvstore? What cases does it disambiguate?

File: pkg/ipcache/ipcache.go [hunk 17]
```diff
@@ -759,11 +762,11 @@ func (ipc *IPCache) GetNamedPorts() (npm types.NamedPortMultiMap) {
...
```
Comment (squeed) [inline pkg/ipcache/ipcache.go]: In what cases do we need UID? I'm having a bit of trouble thinking through all the cases.

Separately, I'm concerned that there are valid state transitions that this might break. e.g., if we restart a watch, and a CEP had transitioned from pod A to pod A'. We would never see the delete of A and the add of A', just the update. Would stale ipcache entries then be left behind?

**Comment by squeed** [comment]
There is, sadly, another case that I *painfully* experienced while working on another CNI: a stale CNI ADD.

It is possible on heavily loaded systems to get a CNI ADD for UID 1, but that pod has already been deleted and re-created with UID 2 in the apiserver. Thus, the k8s watcher will "never" catch up with UID 1, since it's already on 2+. How does this PR handle this situation?

The solution we decided on -- which was extremely awkward and painful -- was to block the CNI ADD until the requested UID was observed. In the event of a stale CNI ADD, it failed, but that's OK, as the pod in question is going away. This was really frustrating for latency, but it prevented correctness issues.

So, think about how we might handle that case. Remember that we don't need to worry about stale local endpoints (for the most part), as containerd will *eventually* issue us a CNI DEL. Plus, CNI GC will also eventually perform cleanup, when I get that merged.

File: pkg/redirectpolicy/manager_test.go (hunk 14 above)
Comment (learnitall) [reply pkg/redirectpolicy/manager_test.go]: My worry is that if we let the PR through without tests they will never be added. I feel that a separate TODO item for adding tests would go stale or become de-prioritized and never get done. I agree that the changes are relatively easy to understand, and delaying the PR isn't great, but I think it's a better alternative to merging these changes without the associated regression tests. This is a great opportunity to expand on the controlplane test framework to support testing these kinds of changes.

File: clustermesh-apiserver/clustermesh/root.go [hunk 18]
```diff
@@ -277,6 +277,10 @@ func (es *endpointSynchronizer) upsert(ctx context.Context, key resource.Key, ob
...
+					entry.K8sUID = string(endpoint.OwnerReferences[0].UID)
+				}
+
```
Comment (aanm) [inline clustermesh-apiserver/clustermesh/root.go]: What I meant here was that we should find the first occurrence of the "Pod". The pod can be on index 2 for example.

File: pkg/endpointmanager/endpointsynchronizer.go [hunk 19]
```diff
@@ -202,6 +205,8 @@ func (epSync *EndpointSynchronizer) RunK8sCiliumEndpointSync(e *endpoint.Endpoin
 
 						scopedLog.WithField(logfields.CEPUID, localCEP.UID).Debug("storing CEP UID after create")
 						e.SetCiliumEndpointUID(localCEP.UID)
+						// TODO: Set here as well
```
Comment (aanm) [inline pkg/endpointmanager/endpointsynchronizer.go]: What's the TODO?

File: pkg/endpointmanager/endpointsynchronizer.go [hunk 20]
```diff
@@ -161,13 +161,16 @@ func (epSync *EndpointSynchronizer) RunK8sCiliumEndpointSync(e *endpoint.Endpoin
...
+						// Backfill the Pod and CEP UID as we need to do if the CEP was
 						// created on an agent version that did not yet store the
 						// UID at CEP create time.
 						if err := updateCEPUID(scopedLog, e, localCEP); err != nil {
 							scopedLog.WithError(err).Warn("could not take ownership of existing ciliumendpoint")
 							return err
 						}
+						if err := updatePodUID(scopedLog, e, localCEP.GetUID()); err != nil {
+							return err
+						}
```
Comment (aanm) [inline pkg/endpointmanager/endpointsynchronizer.go]: Wait a second, why are we updating the pod UID with the endpoint's UID?

File: pkg/endpointmanager/endpointsynchronizer.go [hunk 21]
```diff
@@ -202,6 +205,8 @@ func (epSync *EndpointSynchronizer) RunK8sCiliumEndpointSync(e *endpoint.Endpoin
 
 						scopedLog.WithField(logfields.CEPUID, localCEP.UID).Debug("storing CEP UID after create")
 						e.SetCiliumEndpointUID(localCEP.UID)
+						// TODO: Set here as well
+						e.K8sUID = string(localCEP.UID)
```
Comment (aanm) [inline pkg/endpointmanager/endpointsynchronizer.go]: Wait a second, why are we updating the pod UID with the endpoint's UID?

File: pkg/endpointmanager/endpointsynchronizer.go [hunk 22]
```diff
@@ -228,14 +233,16 @@ func (epSync *EndpointSynchronizer) RunK8sCiliumEndpointSync(e *endpoint.Endpoin
...
-						// Backfill the CEP UID as we need to do if the CEP was
+						// Backfill the Pod and CEP UID as we need to do if the CEP was
 						// created on an agent version that did not yet store the
 						// UID at CEP create time.
 						if err := updateCEPUID(scopedLog, e, localCEP); err != nil {
 							scopedLog.WithError(err).Warn("could not take ownership of existing ciliumendpoint")
 							return err
 						}
-
+						if err := updatePodUID(scopedLog, e, localCEP.GetUID()); err != nil {
```
Comment (aanm) [inline pkg/endpointmanager/endpointsynchronizer.go]: Wait a second, why are we updating the pod UID with the endpoint's UID?

File: pkg/ipcache/ipcache.go [hunk 23]
```diff
@@ -74,6 +74,8 @@ type K8sMetadata struct {
 	Namespace string
 	// PodName is the Kubernetes pod name behind the IP
 	PodName string
+	// UID is the Kubernetes UID of the pod
+	UID string
```
Comment (aanm) [inline pkg/ipcache/ipcache.go]: Let's make the variable more obvious and change it to `PodUID`

File: pkg/ipcache/ipcache.go [hunk 24]
```diff
@@ -759,11 +762,17 @@ func (ipc *IPCache) GetNamedPorts() (npm types.NamedPortMultiMap) {
 
 // DeleteOnMetadataMatch removes the provided IP to security identity mapping from the IPCache
 // if the metadata cache holds the same "owner" metadata as the triggering pod event.
-func (ipc *IPCache) DeleteOnMetadataMatch(IP string, source source.Source, namespace, name string) (namedPortsChanged bool) {
+func (ipc *IPCache) DeleteOnMetadataMatch(IP string, source source.Source, namespace, name, uid string) (namedPortsChanged bool) {
```
Comment (aanm) [inline pkg/ipcache/ipcache.go]: Can we change the varilable name to be podUID?

File: pkg/ipcache/kvstore.go [hunk 25]
```diff
@@ -97,7 +97,7 @@ func newKVReferenceCounter(s store) *kvReferenceCounter {
 // UpsertIPToKVStore updates / inserts the provided IP->Identity mapping into the
 // kvstore, which will subsequently trigger an event in NewIPIdentityWatcher().
 func UpsertIPToKVStore(ctx context.Context, IP, hostIP netip.Addr, ID identity.NumericIdentity, key uint8,
-	metadata, k8sNamespace, k8sPodName string, npm types.NamedPortMap) error {
+	metadata, k8sNamespace, k8sPodName, k8sUID string, npm types.NamedPortMap) error {
```
Comment (aanm) [inline pkg/ipcache/kvstore.go]: same here with `k8sPodUID`

File: pkg/ipcache/kvstore.go [hunk 26]
```diff
@@ -120,6 +120,7 @@ func UpsertIPToKVStore(ctx context.Context, IP, hostIP netip.Addr, ID identity.N
 		Key:          key,
 		K8sNamespace: k8sNamespace,
 		K8sPodName:   k8sPodName,
+		K8sUID:       k8sUID,
```
Comment (aanm) [inline pkg/ipcache/kvstore.go]: same here with `k8sPodUID`

File: pkg/k8s/watchers/cilium_endpoint.go [hunk 27]
```diff
@@ -227,3 +230,12 @@ func (k *K8sWatcher) endpointDeleted(endpoint *types.CiliumEndpoint) {
 		}
 	}
 }
+
+func (k *K8sWatcher) fetchPodUIDForCEP(endpoint *types.CiliumEndpoint) string {
```
Comment (aanm) [inline pkg/k8s/watchers/cilium_endpoint.go]: This doesn't need to be a method of  `(k *K8sWatcher)`, it can be a normal function.

File: pkg/k8s/watchers/cilium_endpoint.go [hunk 28]
```diff
@@ -227,3 +230,12 @@ func (k *K8sWatcher) endpointDeleted(endpoint *types.CiliumEndpoint) {
...
+	// Fetch the Pod UID from the internal Endpoint object if it exists,
+	// otherwise check the ownerRef of the CEP object.
+	if len(endpoint.OwnerReferences) > 0 && endpoint.OwnerReferences[0].Kind == "Pod" {
+		return string(endpoint.OwnerReferences[0].UID)
+	}
```
Comment (aanm) [inline pkg/k8s/watchers/cilium_endpoint.go]: The same comment I left with regarding the pod not being in the index 0 should be applied here as well.

File: pkg/redirectpolicy/manager.go (hunk 16 above)
Comment (aanm) [inline pkg/redirectpolicy/manager.go]: same rename from `uid` to `podUID`

**Review by aanm — DISMISSED** [review]

File: pkg/endpointmanager/endpointsynchronizer.go (hunk 20 above)
Comment (christarazi) [reply pkg/endpointmanager/endpointsynchronizer.go]: Yeah, this is a mistake. I'll update.

File: pkg/k8s/watchers/pod.go [hunk 29]
```diff
@@ -352,12 +352,17 @@ func (k *K8sWatcher) updateK8sPodV1(oldK8sPod, newK8sPod *slim_corev1.Pod) error
...
 	newPodLabels := newK8sPodLabels.K8sStringMap()
 	labelsChanged := !maps.Equal(oldPodLabels, newPodLabels)
+	uidChanged := oldK8sPod.UID != newK8sPod.UID
 
 	lrpNeedsReassign := false
 	// The relevant updates are : podIPs and label updates.
 	oldPodIPLen := len(oldK8sPod.Status.PodIP)
 	newPodIPLen := len(newK8sPod.Status.PodIP)
 	switch {
+	case uidChanged:
```
Comment (squeed) [inline pkg/k8s/watchers/pod.go]: This seems wrong; pod IPs and labels can change, even when a pod isn't deleted and recreated.

I see below that the pod IP equality check is wrong; that needs to be fixed as part of this PR.

File: pkg/k8s/watchers/pod.go [hunk 30]
```diff
@@ -397,7 +402,10 @@ func (k *K8sWatcher) updateK8sPodV1(oldK8sPod, newK8sPod *slim_corev1.Pod) error
 	}
 
 	for _, podEP := range podEPs {
-		if labelsChanged {
+		if labelsChanged || uidChanged {
```
Comment (squeed) [inline pkg/k8s/watchers/pod.go:385]: What case does this catch? That the CEP's labels are different from the Pod's labels?

If so, we should fix that regardless of the UID.

Comment (christarazi) [reply pkg/k8s/watchers/pod.go:385]: This catches scenario 3 from the linked issue in the PR description.

**Comment by christarazi** [comment]
The latest push simplifies the PR quite a bit as discussed offline with Marcel and Casey. The solution we decided on is to block the CNI ADD (for up to 30s) until the requested UID is observed by the K8s pod informer. See the last commit for more details. This means we no longer need to pass the pod UID to many other places in the code as the previous revision had. Basically, we are trading off availability for correctness at a high level.

File: pkg/ipcache/ipcache.go (hunk 17 above)
Comment (christarazi) [reply pkg/ipcache/ipcache.go]: https://github.com/cilium/cilium/pull/31605#issuecomment-2097483504

File: pkg/identity/identity.go (hunk 1 above)
Comment (christarazi) [reply pkg/identity/identity.go]: https://github.com/cilium/cilium/pull/31605#issuecomment-2097483504

File: pkg/redirectpolicy/manager.go (hunk 16 above)
Comment (christarazi) [reply pkg/redirectpolicy/manager.go]: https://github.com/cilium/cilium/pull/31605#issuecomment-2097483504

File: pkg/redirectpolicy/manager_test.go (hunk 14 above)
Comment (christarazi) [reply pkg/redirectpolicy/manager_test.go]: I've greatly simplified the PR as per https://github.com/cilium/cilium/pull/31605#issuecomment-2097483504, so this code highlighted here no longer exists.

File: daemon/cmd/endpoint.go (hunk 13 above)
Comment (christarazi) [reply daemon/cmd/endpoint.go]: See https://github.com/cilium/cilium/pull/31605#issuecomment-2097483504

File: pkg/ipcache/ipcache.go (hunk 10 above)
Comment (christarazi) [reply pkg/ipcache/ipcache.go]: https://github.com/cilium/cilium/pull/31605#issuecomment-2097483504

File: pkg/k8s/watchers/pod.go [hunk 31]
```diff
@@ -347,12 +344,17 @@ func (k *K8sWatcher) updateK8sPodV1(oldK8sPod, newK8sPod *slim_corev1.Pod) error
 	newK8sPodLabels, _ := labelsfilter.Filter(labels.Map2Labels(strippedNewLabels, labels.LabelSourceK8s))
 	newPodLabels := newK8sPodLabels.K8sStringMap()
 	labelsChanged := !maps.Equal(oldPodLabels, newPodLabels)
+	uidChanged := oldK8sPod.UID != newK8sPod.UID
 
 	lrpNeedsReassign := false
```
Comment (squeed) [inline pkg/k8s/watchers/pod.go]:
```suggestion
	lrpNeedsReassign := !maps.Equal(oldPodLabels, newPodLabels) || !k8sTypes.IPSlice(oldPodIPs).DeepEqual(newPodIPs)
	// delete switch statement.
```

Everything that can change **with** a uid change, can change **without** one too :-(

Comment (christarazi) [reply pkg/k8s/watchers/pod.go]: IIUC, this essentially means `lrpNeedsReassign := true`, right? I'm not sure I understand why each pod event means we have to trigger the LRP logic if there could be no label or IP change. The current logic already detects if the labels or IPs have changed.

Given that the modification I made just adds UID to list of conditions, it isn't making any fundmental changes to the logic. If the suggestion here is to fix that core logic, I'd opt to have that be in another PR so we can get this one merged for fixing statefulset handling.

Comment (squeed) [reply pkg/k8s/watchers/pod.go]: Sorry, I made a typo. Corrected the comment.

Comment (squeed) [reply pkg/k8s/watchers/pod.go]: The problem is that we don't catch IP address changes; the code as-written just checks to see if the length changes. Which is silly; pods can change IPs at will. If we correctly catch IP and label changes, then there's no need to check UIDs.

Comment (christarazi) [reply pkg/k8s/watchers/pod.go]: Gotcha, I can implement this suggestion as a separate commit. I'll leave in the UID check as another OR as per scenario 3 in https://github.com/cilium/cilium/issues/30409.

File: daemon/cmd/endpoint.go [hunk 32]
```diff
@@ -421,37 +436,68 @@ func (d *Daemon) createEndpoint(ctx context.Context, owner regeneration.Owner, e
...
+		pod, k8sMetadata, err := d.fetchK8sMetadataForEndpoint(ep.K8sNamespace, ep.K8sPodName)
+		if pod != nil && ep.K8sUID != string(pod.GetUID()) {
+			log.WithFields(logrus.Fields{
+				logfields.K8sPodName: ep.K8sNamespace + "/" + ep.K8sPodName,
+				logfields.K8sUID:     ep.K8sUID,
+			}).Warn("Detected outdated Pod UID during Endpoint creation. Endpoint creation cannot proceed with an outdated Pod store. Creation will be retried.")
+
+			t, ok := d.endpointCreations.requests[d.endpointCreations.getKey(ep)]
+			if !ok || time.Now().Sub(t.started) < 30*time.Second {
+				return ep, 0, fmt.Errorf("pod store out-of-date")
```
Comment (squeed) [inline daemon/cmd/endpoint.go]: So we return failure here, and wait for kubelet -> containerd -> cni -> agent to retry? Am I reading this right?

Does it make sense to pause for a few seconds first to let the informer catch up? That would save some unnecessary system load.

**Review by marseel — APPROVED** [review]
Thanks, looks good from my point of view.
I would probably add retry with a few seconds delay that Casey suggested.

File: daemon/cmd/endpoint.go (hunk 32 above)
Comment (christarazi) [reply daemon/cmd/endpoint.go]: Ok, I've pushed this suggestion, PTAL.

File: daemon/cmd/endpoint.go [hunk 33]
```diff
@@ -559,6 +590,33 @@ func (d *Daemon) createEndpoint(ctx context.Context, owner regeneration.Owner, e
...
+func (d *Daemon) handleOutdatedPodInformer(
+	ctx context.Context,
+	ep *endpoint.Endpoint,
+) (pod *slim_corev1.Pod, k8sMetadata *endpoint.K8sMetadata, err error) {
+	var once sync.Once
+
+	// Average attempt every 10ms.
+	err = resiliency.Retry(ctx, 2*time.Second, 12, func(_ context.Context, _ int) (bool, error) {
+		pod, k8sMetadata, err = d.fetchK8sMetadataForEndpoint(ep.K8sNamespace, ep.K8sPodName)
+		if pod != nil && ep.K8sUID != string(pod.GetUID()) {
```
Comment (squeed) [inline daemon/cmd/endpoint.go:609]: One minor suggestion: handle the case where the CNI-supplied uid is missing. Just in case.

otherwise LGTM.

**Review by squeed — APPROVED** [review]
One minor suggestion, then LGTM

File: pkg/k8s/watchers/pod.go (hunk 29 above)
Comment (christarazi) [reply pkg/k8s/watchers/pod.go]: Fixed in recent revisions

File: daemon/cmd/endpoint.go (hunk 5 above)
Comment (christarazi) [reply daemon/cmd/endpoint.go]: There will be log msgs indicating what Cilium is doing when the outdated UID case is hit. We suspect this case to be very rare anyway.

**Review by learnitall — APPROVED** [review]
API changes LGTM!

File: pkg/redirectpolicy/manager_test.go (hunk 14 above)
Comment (christarazi) [reply pkg/redirectpolicy/manager_test.go]: After syncing offline, given the multi month effort investment required to allow the controlplane framework to have the ability to test this kind of behavior, I am resolving this thread to proceed with the PR as it resolves problematic behavior for users today.

**Comment by primeroz** [comment]
Is this being backported to 1.14 ? :pray:

**Comment by primeroz** [comment]
@christarazi sorry for the ping , i just wanted to check if there is any plan of porting this fix to 1.14 ? 

thanks :pray:

**Comment by christarazi** [comment]
@primeroz Right now only v1.15 backport was considered due to the nature of the changes being non-trivial. The risk of backporting to older stable versions is that we introduce a regression in very stable versions of Cilium.

**Comment by primeroz** [comment]
@christarazi i understand and we will check internally if is worth for us to upgrade to 1.15 

Just to confirm though the issue is present in 1.14 as well right ? ( we think we did hit it )
