### PR TITLE
Agent: Include Cilium version in output of 'cilium status --verbose'

### LINKED ISSUE #14154: Agent: Include Cilium version in output of cilium status --verbose
## Bug report

**General Information**

When using ``cilium status --verbose`` to introspect Cilium installations, it would be helpful if the output included the Cilium version running.

### PR DESCRIPTION
**Pull request by romanspb80**
The status output doesn't contain the version of the Daemon agent and shows double 'OK' for state:
      $ cilium status --verbose
      ...
      Cilium:                 Ok        OK
      ...
This commit fix double 'OK' and add the version to output:
      ...
      Cilium:                 Ok        Ver: 1.9.90   Rev: 6d3143fd0
      ...
    
Fixes: #14154
    
Signed-off-by: Roman Ptitcyn romanspb@yahoo.com

### CODE REVIEW

File: daemon/cmd/status.go [hunk 1]
```diff
@@ -599,16 +600,22 @@ func (d *Daemon) getStatus(brief bool) models.StatusResponse {
...
+	Ver := v.GetCiliumVersion()
+	ciliumVer := fmt.Sprintf("    Ver: %s  Rev: %s", Ver.Version, Ver.Revision)
+
 	switch {
 	case len(sr.Stale) > 0:
+		msg := "Stale status data"
 		sr.Cilium = &models.Status{
 			State: models.StatusStateWarning,
-			Msg:   "Stale status data",
+			Msg:   msg + ciliumVer,
```
Comment (sayboras) [inline daemon/cmd/status.go]: while string concatenation is faster, it's hard to read and error prone (e.g. ciliumVer _must_ have space prefix, msg should be ending with dot or comma, etc). I would prefer to go with fmt.Sprintf() in general.

**Review by sayboras — COMMENTED** [review]
Thanks for PR. 

Based on my understanding, version will be printed in case of any failed check. This could be 
 redudant in some cases. What do you think about always printing version details at the beginning ?

File: daemon/cmd/status.go (hunk 1 above)
Comment (romanspb80) [reply daemon/cmd/status.go]: > Thanks for PR.
> 
> Based on my understanding, version will be printed in case of any failed check. This could be
> redudant in some cases. What do you think about always printing version details at the beginning ?

Thanks Tam for the suggestion! Printing version details at the beginning is a good idea. But there are some entities which printing status at the beginning. For example:
$ cilium status
KVStore:                Ok   etcd: 1/1 connected, lease-ID=29c6767063b65989, lock lease-ID=29c6767063b6598b, has-quorum=true: https://192.168.33.11:2379 - 3.4.13 (Leader)
Kubernetes:             Ok   1.20+ (v1.20.0-rc.0) [linux/amd64]
Cilium:                 Ok            Ver: 1.9.90  Rev: 25d8615be
Cilium health daemon:   Ok   
BandwidthManager:       Disabled
Host Routing:           Legacy
Proxy Status:           OK, ip 10.11.0.128, 0 redirects active on ports 10000-20000
Hubble:                 Ok              Current/Max Flows: 471/4095 (11.50%), Flows/s: 11.86   Metrics: Disabled

Maybe we will return to this idea, but a little later, after feedback? Because perhaps it would be more correct to make the output uniform for all entities.

Comment (romanspb80) [reply daemon/cmd/status.go]: > while string concatenation is faster, it's hard to read and error prone (e.g. ciliumVer _must_ have space prefix, msg should be ending with dot or comma, etc). I would prefer to go with fmt.Sprintf() in general.

OK. I've implemented fmt.Sprintf() in the next commit. And regarding the question about the order of output I swapped msg and ciliumVer. Could you please check:
$ cilium status
Cilium:                 Failure   [Ver: 1.9.90  Rev: 25d8615be]    Kvstore service is not ready

**Review by aanm — CHANGES_REQUESTED** [review]
The changes look good overall but there are a couple things I don't understand:
1) Why are 4 spaces between `ciliumVer` and `msg`?
2) What's the reasoning to always print the cilium version in a failure scenario instead of only printing the Cilium versions int the Cilium-specific line?

**Comment by romanspb80** [comment]
> The changes look good overall but there are a couple things I don't understand:
> 
> 1. Why are 4 spaces between `ciliumVer` and `msg`?
> 2. What's the reasoning to always print the cilium version in a failure scenario instead of only printing the Cilium versions int the Cilium-specific line?

Thanks for the questions.
1. The 4 spaces is the prefix to devide msg from ciliumVer for easy reading.
2. The version will be printed in all cases, not just in case of an failure scenario. And I think it should be same as for Kubernetes entity: "Kubernetes: Ok 1.20+ (v1.20.0-rc.0)". In my opinion no additional entity is needed in the output of the "cilium status".

**Comment by aanm** [comment]
Thanks for the answers, please see inline replies.

> > The changes look good overall but there are a couple things I don't understand:
> > 
> > 1. Why are 4 spaces between `ciliumVer` and `msg`?
> > 2. What's the reasoning to always print the cilium version in a failure scenario instead of only printing the Cilium versions int the Cilium-specific line?
> 
> Thanks for the questions.
> 
> 1. The 4 spaces is the prefix to devide msg from ciliumVer for easy reading.

With the current changes the output is the following:
```
KVStore:                Ok   etcd: 1/1 connected, lease-ID=29c676a8be0e14c8, lock lease-ID=29c676a8be0e14ca, has-quorum=true: https://192.168.33.11:2379 - 3.4.13 (Leader)
Kubernetes:             Ok   1.20+ (v1.20.0-rc.0) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumNetworkPolicy", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1beta1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Partial   
Cilium:                 Ok        [Ver: 1.9.90  Rev: 7ce4c3609]
```

The space between the `Ok` and the `[Ver: 1.9.90  Rev: 7ce4c3609]` seems unnecessary. Also, to make it consistent maybe we should make it between parenthesis, similar to what is done for Kubernetes, and not square brackets.

> 2. The version will be printed in all cases, not just in case of an failure scenario. And I think it should be same as for Kubernetes entity: "Kubernetes: Ok 1.20+ (v1.20.0-rc.0)". In my opinion no additional entity is needed in the output of the "cilium status".

File: daemon/cmd/status.go [hunk 2]
```diff
@@ -599,16 +600,22 @@ func (d *Daemon) getStatus(brief bool) models.StatusResponse {
 
 	sr.Stale = stale
 
+	//CiliumVersion definition
+	Ver := v.GetCiliumVersion()
```
Comment (christarazi) [inline daemon/cmd/status.go]:
```suggestion
	ver := v.GetCiliumVersion()
```

File: daemon/cmd/status.go [hunk 3]
```diff
@@ -46,6 +46,7 @@ import (
 	"github.com/cilium/cilium/pkg/option"
 	"github.com/cilium/cilium/pkg/rand"
 	"github.com/cilium/cilium/pkg/status"
+	v "github.com/cilium/cilium/pkg/version"
```
Comment (christarazi) [inline daemon/cmd/status.go]: Nit: is there a reason to do a named import here? Why not just use the package name as long as there's no conflicts already, which there shouldn't be.

**Review by christarazi — CHANGES_REQUESTED** [review]
A few nits below. LGTM besides what others have suggested. Also, please squash all the commits into one when you think it's ready to merge.

**Comment by romanspb80** [comment]
> The space between the `Ok` and the `[Ver: 1.9.90 Rev: 7ce4c3609]` seems unnecessary. Also, to make it consistent maybe we should make it between parenthesis, similar to what is done for Kubernetes, and not square brackets.

Done:

KVStore:                Ok   etcd: 1/1 connected, lease-ID=29c6767063bb912e, lock lease-ID=29c6767063bb9132, has-quorum=true: https://192.168.33.11:2379 - 3.4.13 (Leader)
Kubernetes:             Ok   1.20+ (v1.20.0-rc.0) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumNetworkPolicy", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1beta1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Partial   
Cilium:                 Ok   1.9.90 (v.1.9.90-r.d3428c13e)

File: daemon/cmd/status.go [hunk 4]
```diff
@@ -599,16 +600,22 @@ func (d *Daemon) getStatus(brief bool) models.StatusResponse {
...
+	ver := version.GetCiliumVersion()
+	ciliumVer := fmt.Sprintf("%s (v.%s-r.%s)", ver.Version, ver.Version, ver.Revision)
+
 	switch {
 	case len(sr.Stale) > 0:
+		msg := "Stale status data"
 		sr.Cilium = &models.Status{
 			State: models.StatusStateWarning,
-			Msg:   "Stale status data",
+			Msg:   fmt.Sprintf("%s    %s", ciliumVer, msg),
```
Comment (aanm) [inline daemon/cmd/status.go:612]: it seems the space was not removed? As well as in the remaining lines.

**Review by aanm — CHANGES_REQUESTED** [review]

File: daemon/cmd/status.go (hunk 4 above)
Comment (romanspb80) [reply daemon/cmd/status.go:612]: > it seems the space was not removed? As well as in the remaining lines.

Yes, it is. This is OK. You only mentioned the space between State and Version: 

> The space between the Ok and the [Ver: 1.9.90 Rev: 7ce4c3609] seems unnecessary. Also, to make it consistent maybe we should make it between parenthesis, similar to what is done for Kubernetes, and not square brackets.

And this is a fix in accordance with your remark:
`
pkg/client/client.go

	if sr.Cilium != nil {
		-fmt.Fprintf(w, "Cilium:\t%s\t%s\n", sr.Cilium.State, sr.Cilium.Msg)
		+fmt.Fprintf(w, "Cilium:\t%s   %s\n", sr.Cilium.State, sr.Cilium.Msg)
	}
`

But the space between Version and Msg is needed as a delimeter. Please, see comment from [sayboras](https://github.com/sayboras):

> while string concatenation is faster, it's hard to read and error prone (e.g. ciliumVer must have space prefix, msg should be ending with dot or comma, etc). I would prefer to go with fmt.Sprintf() in general.

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

File: daemon/cmd/status.go (hunk 3 above)
Comment (romanspb80) [reply daemon/cmd/status.go]: > Nit: is there a reason to do a named import here? Why not just use the package name as long as there's no conflicts already, which there shouldn't be.

Thanks for the remark.
Done. Please check

**Review by christarazi — APPROVED** [review]

**Comment by aanm** [comment]
retest-net-netxt

**Comment by aanm** [comment]
retest-net-next

**Review by sayboras — APPROVED** [review]
LGTM 💯

**Comment by romanspb80** [comment]
Thanks a lot guys!

**Review by fristonio — APPROVED** [review]
LGTM :rocket:

**Review by jibi — APPROVED** [review]
Looks good :+1:

**Comment by jibi** [comment]
retest-net-next

**Comment by jibi** [comment]
retest-runtime

**Comment by aanm** [comment]
marked for backport to fix https://github.com/cilium/cilium/issues/15815
