### PR TITLE
ctmap/gc: continue interval time on partial GC pass.

### LINKED ISSUE #40820: ct6_global bpf table not cleared
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.18.0 and lower than v1.19.0

### What happened?

`ct6_global` and `ct_any6_global` bpf pressure is increasing steadily up to 100% over a time period of approximately 7 days and not cleared automatically.

Once map is almost full no new pods can be deployed and Cilium hangs / get's very slow / high CPU usage (probably expected).

We do not observe the same behavior with IPv4 and IPv4 traffic is much more than IPv6.

See below log output. `fd85:ee78:d8a6:8607::1:fe5:8000` is a traefik pod accepting HTTP requests on port 8000. I'm not exactly sure what the "expires=26644226" mean and what unit it is (timestamp, seconds etc.). Would be good if someone could clarify.

Restarting cilium pod temporarily fixes this (although initial startup is very slow) but starts filling up again within 7 days. Interestingly on some nodes after restarting unrelated pods the ct map usage drops to close to 0% after a few minutes, although the pods do not use IPv6 themselves.

This behavior is observed on all nodes.

Image

Interestingly there is a clear pattern when IPv6 Conntrack TCP metric jumps but I couldn't figure out yet what triggers it. There are no pod restarts or cron jobs at the steep increase. Also no entries are ever deleted.

Image

### How can we reproduce the issue?

Not sure.
Cilium installed via Helm with following config:

```yaml
data:
  agent-health-port: "9879"
  api-rate-limit: '{"endpoint-create": "rate-limit:20/s,rate-burst:30,parallel-requests:15,auto-adjust:true",
    "endpoint-delete": "rate-limit:20/s,rate-burst:30,parallel-requests:15,auto-adjust:true",
    "endpoint-get": "rate-limit:200/s,rate-burst:200,parallel-requests:200,auto-adjust:true",
    "endpoint-list": "rate-limit:200/s,rate-burst:200,parallel-requests:200,auto-adjust:true",
    "endpoint-patch": "rate-limit:20/s,rate-burst:30,parallel-requests:15,auto-adjust:true"}'
  auto-direct-node-routes: "True"
  bpf-ct-timeout-regular-tcp-fin: 5s
  bpf-ct-timeout-regular-tcp-syn: 15s
  bpf-distributed-lru: "True"
  bpf-lb-mode: snat
  bpf-map-dynamic-size-ratio: "0.08"
  cgroup-root: /run/cilium/cgroupv2
  clean-cilium-bpf-state: "false"
  clean-cilium-state: "false"
  cluster-name: default
  cluster-pool-ipv4-cidr: 10.10.0.0/15
  cluster-pool-ipv4-mask-size: "22"
  cluster-pool-ipv6-cidr: fd85:ee78:d8a6:8607::1:0000/112
  cluster-pool-ipv6-mask-size: "118"
  cni-exclusive: "False"
  cni-log-file: /var/run/cilium/cilium-cni.log
  custom-cni-conf: "false"
  datapath-mode: netkit
  debug: "False"
  disable-cnp-status-updates: "True"
  egress-gateway-policy-map-max: "163840"
  enable-bgp-control-plane: "False"
  enable-bpf-clock-probe: "True"
  enable-bpf-masquerade: "True"
  enable-host-firewall: "False"
  enable-host-legacy-routing: "False"
  enable-hubble: "false"
  enable-ip-masq-agent: "False"
  enable-ipv4: "True"
  enable-ipv4-big-tcp: "True"
  enable-ipv4-egress-gateway: "False"
  enable-ipv4-masquerade: "True"
  enable-ipv6: "True"
  enable-ipv6-big-tcp: "True"
  enable-ipv6-masquerade: "True"
  enable-l2-announcements: "True"
  enable-l7-proxy: "False"
  enable-local-redirect-policy: "True"
  enable-metrics: "true"
  enable-remote-node-identity: "True"
  enable-well-known-identities: "False"
  identity-allocation-mode: crd
  ipam: cluster-pool
  ipv4-native-routing-cidr: 10.10.0.0/15
  ipv6-native-routing-cidr: fd85:ee78:d8a6:8607::1:0000/112
  kube-proxy-replacement: "true"
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  node-port-range: 8192,9215
  operator-api-serve-addr: 127.0.0.1:9234
  operator-prometheus-serve-addr: :9963
  policy-audit-mode: "False"
  preallocate-bpf-maps: "True"
  prometheus-serve-addr: :9962
  routing-mode: native
  sidecar-istio-proxy-image: cilium/istio_proxy
  write-cni-conf-when-ready: /host/etc/cni/net.d/05-cilium.conflist
```

### Cilium Version

v1.18.0-rc.1
v1.17.6

### Kernel Version

6.11.5+bpo-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.11.5-1~bpo12+1 (2024-11-11) x86_64 GNU/Linux

### Kubernetes Version

v1.31.4

### Regression

not sure

### Sysdump

_No response_

### Relevant log output

```shell
TCP OUT 2a02:c7c:8c7:7900:43:2c21:4148:83f7:47090 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26620539 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26620535 TxFlagsSeen=0x1b LastTxReport=26620535 Flags=0x0033 [ RxClosing TxClosing SeenNonSyn NodePort ] RevNAT=218 SourceSecurityID=10 BackendID=0
TCP IN 2601:58b:1100:1a60:ed0e:2d04:f505:dda8:35620 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26589693 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26589689 TxFlagsSeen=0x1b LastTxReport=26589689 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=10 BackendID=0
TCP SVC 2a00:23c7:8d50:2a01:8ce7:20da:67fe:13bd:35874 -> 2a03:3f40:88:1::24:80 expires=26771663 Packets=0 Bytes=0 RxFlagsSeen=0x00 LastRxReport=0 TxFlagsSeen=0x1b LastTxReport=26771659 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=218 SourceSecurityID=0 BackendID=98
TCP OUT 2a00:23c7:7130:9801:4ab4:23ff:fe82:ccaa:51222 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26634555 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26634551 TxFlagsSeen=0x1b LastTxReport=26634551 Flags=0x0033 [ RxClosing TxClosing SeenNonSyn NodePort ] RevNAT=218 SourceSecurityID=10 BackendID=0
TCP IN 2a00:23c8:bcb:5101:cce4:dbf7:957:33a4:47224 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26562518 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26562514 TxFlagsSeen=0x1b LastTxReport=26562514 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=10 BackendID=0
TCP SVC 2603:8080:c0f0:d2e0:99f2:9195:c043:304f:44564 -> 2a03:3f40:88:1::24:80 expires=26806933 Packets=0 Bytes=0 RxFlagsSeen=0x00 LastRxReport=0 TxFlagsSeen=0x1b LastTxReport=26806929 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=218 SourceSecurityID=0 BackendID=98
TCP IN 2601:647:8500:fb60:6c05:5abe:2e2e:8184:57218 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26623966 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26623962 TxFlagsSeen=0x1b LastTxReport=26623962 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=10 BackendID=0
TCP SVC 2606:8ac0:200:13ce:5408:2ccb:5dec:957:45750 -> 2a03:3f40:88:1::24:80 expires=26671440 Packets=0 Bytes=0 RxFlagsSeen=0x00 LastRxReport=0 TxFlagsSeen=0x1b LastTxReport=26671436 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=218 SourceSecurityID=0 BackendID=98
TCP OUT 2a00:23c8:2425:b801:a91:15ff:fe2a:51c4:58786 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26627216 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26627212 TxFlagsSeen=0x1b LastTxReport=26627212 Flags=0x0033 [ RxClosing TxClosing SeenNonSyn NodePort ] RevNAT=218 SourceSecurityID=10 BackendID=0
TCP OUT 2a00:23c8:a898:3e01:9cae:5a57:26a6:ae47:33292 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26705742 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26705738 TxFlagsSeen=0x1b LastTxReport=26705738 Flags=0x0033 [ RxClosing TxClosing SeenNonSyn NodePort ] RevNAT=218 SourceSecurityID=10 BackendID=0
TCP OUT 2405:201:c025:80c4:114:3ed7:7bb9:fc65:58516 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26687540 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26687536 TxFlagsSeen=0x1b LastTxReport=26687536 Flags=0x0033 [ RxClosing TxClosing SeenNonSyn NodePort ] RevNAT=218 SourceSecurityID=10 BackendID=0
TCP OUT 2a0a:ef40:d35:3901:9c51:6ee1:57fe:f34a:38520 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26674980 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26674976 TxFlagsSeen=0x1b LastTxReport=26674976 Flags=0x0033 [ RxClosing TxClosing SeenNonSyn NodePort ] RevNAT=218 SourceSecurityID=10 BackendID=0
TCP IN 2a02:c7c:d904:2000:14d0:702:9731:1dc3:35732 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26600307 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26600303 TxFlagsSeen=0x1b LastTxReport=26600303 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=10 BackendID=0
TCP IN 2a00:23c8:8914:e401:57d:ff36:186e:f693:40914 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26572199 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26572195 TxFlagsSeen=0x1b LastTxReport=26572195 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=10 BackendID=0
TCP IN 2a00:23c6:7e2c:3c01:18c9:5808:555:eb09:36388 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26632789 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26632785 TxFlagsSeen=0x1b LastTxReport=26632785 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=10 BackendID=0
TCP OUT 2600:8803:2b11:6d00:ed45:16c7:b1e5:38c:44458 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26560668 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26560664 TxFlagsSeen=0x1b LastTxReport=26560664 Flags=0x0033 [ RxClosing TxClosing SeenNonSyn NodePort ] RevNAT=218 SourceSecurityID=10 BackendID=0
TCP SVC 2a0e:1d47:8d84:6400:3106:e840:7266:965d:46826 -> 2a03:3f40:88:1::24:80 expires=26776083 Packets=0 Bytes=0 RxFlagsSeen=0x00 LastRxReport=0 TxFlagsSeen=0x1b LastTxReport=26776079 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=218 SourceSecurityID=0 BackendID=98
TCP OUT 2600:1700:e24f:8200:9c4c:73fe:df52:831:59026 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26632784 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26632780 TxFlagsSeen=0x1b LastTxReport=26632780 Flags=0x0033 [ RxClosing TxClosing SeenNonSyn NodePort ] RevNAT=218 SourceSecurityID=10 BackendID=0
TCP OUT 2a00:1f:6500:5101:5502:4a52:5394:91d6:38966 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26829678 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26829674 TxFlagsSeen=0x1b LastTxReport=26829674 Flags=0x0033 [ RxClosing TxClosing SeenNonSyn NodePort ] RevNAT=218 SourceSecurityID=10 BackendID=0
TCP IN 2001:14f7:1a:a01:7d93:c8ab:30a5:26f8:58112 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26669701 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26669697 TxFlagsSeen=0x1b LastTxReport=26669697 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=10 BackendID=0
TCP OUT 2607:fb91:3193:d242:843c:52b2:43cf:a266:33958 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26638029 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26638025 TxFlagsSeen=0x1b LastTxReport=26638025 Flags=0x0033 [ RxClosing TxClosing SeenNonSyn NodePort ] RevNAT=218 SourceSecurityID=10 BackendID=0
TCP SVC 2a02:c7c:31c8:e300:31d3:ec2d:450f:d2a9:44016 -> 2a03:3f40:88:1::24:80 expires=26667119 Packets=0 Bytes=0 RxFlagsSeen=0x00 LastRxReport=0 TxFlagsSeen=0x1b LastTxReport=26667115 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=218 SourceSecurityID=0 BackendID=98
TCP SVC 2a02:6b6f:f726:7100:7da0:1395:74bb:1075:50616 -> 2a03:3f40:88:1::24:80 expires=26812102 Packets=0 Bytes=0 RxFlagsSeen=0x00 LastRxReport=0 TxFlagsSeen=0x1b LastTxReport=26812098 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=218 SourceSecurityID=0 BackendID=98
TCP IN 2600:8801:2f9a:ca00:960e:a237:94e2:7cea:41096 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26633667 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26633663 TxFlagsSeen=0x1b LastTxReport=26633662 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=10 BackendID=0
TCP IN 2a02:c7c:c9da:3b00:1c98:bbc5:6c8b:28ba:39726 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26512374 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26512370 TxFlagsSeen=0x1b LastTxReport=26512370 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=10 BackendID=0
TCP IN 2600:6c54:4d40:385:ad74:e233:2dbf:3ee0:60136 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26539605 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26539601 TxFlagsSeen=0x1b LastTxReport=26539601 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=10 BackendID=0
TCP OUT 2601:2c4:4300:3e80:5041:7b47:23bb:8498:36162 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26523739 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26523735 TxFlagsSeen=0x1b LastTxReport=26523735 Flags=0x0033 [ RxClosing TxClosing SeenNonSyn NodePort ] RevNAT=218 SourceSecurityID=10 BackendID=0
TCP SVC 2a02:c7c:408d:9500:11de:10bb:5ceb:c37a:53044 -> 2a03:3f40:88:1::24:80 expires=26863307 Packets=0 Bytes=0 RxFlagsSeen=0x00 LastRxReport=0 TxFlagsSeen=0x1b LastTxReport=26863303 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=218 SourceSecurityID=0 BackendID=98
TCP IN 2600:4040:5696:7e00:9973:e9b5:b419:2ff1:46148 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26489466 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26489462 TxFlagsSeen=0x1b LastTxReport=26489462 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=10 BackendID=0
TCP IN 2a00:23c7:8adf:6901:b56b:31ac:8987:3b93:53116 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26562518 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26562514 TxFlagsSeen=0x1b LastTxReport=26562513 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=10 BackendID=0
TCP IN 2a00:23c7:b33e:ab01:e084:4db9:9b5f:dfc9:40916 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26604678 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26604674 TxFlagsSeen=0x1b LastTxReport=26604674 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=10 BackendID=0
TCP IN 2603:6011:5100:a7d:88a3:7f6f:b460:3b9d:40672 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26558036 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26558032 TxFlagsSeen=0x1b LastTxReport=26558031 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=10 BackendID=0
TCP IN 2a00:23c7:2994:bc01:2fc:8bff:fe62:da9e:49380 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26660040 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26660036 TxFlagsSeen=0x1b LastTxReport=26660036 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=10 BackendID=0
TCP SVC 2a04:241e:700:7f00:8afe:3d33:4873:32df:55460 -> 2a03:3f40:88:1::24:80 expires=26478186 Packets=0 Bytes=0 RxFlagsSeen=0x00 LastRxReport=0 TxFlagsSeen=0x1b LastTxReport=26478182 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=218 SourceSecurityID=0 BackendID=98
TCP OUT 2a0e:1d47:d20a:1600:50fc:8d46:bd8f:a019:47936 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26761149 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26761145 TxFlagsSeen=0x1b LastTxReport=26761145 Flags=0x0033 [ RxClosing TxClosing SeenNonSyn NodePort ] RevNAT=218 SourceSecurityID=10 BackendID=0
TCP IN 2a02:c7c:c66c:6100:4ba4:c0c3:b80a:fe1a:60802 -> fd85:ee78:d8a6:8607::1:fe5:8000 expires=26729513 Packets=0 Bytes=0 RxFlagsSeen=0x1b LastRxReport=26729509 TxFlagsSeen=0x1b LastTxReport=26729509 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=10 BackendID=0
```

### Anything else?

_No response_

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by tommyp1ckles**
When {ipv4,ipv6} specific signals are sent from the datapath to indicate conditions such as high ctmap or snat pressure we may invoke a ipv4 or ipv6 *only* gc pass.
Currently this will also reset the gc interval by recomputing the next interval.

Under a situation where a lot of ipv4/ipv6 specific signals are being sent this may a starvation condition such that the other family never has a chance to be run since before the interval time can finish the loop is woken up by another signal.

To prevent this, if the GC was a "partial" pass (i.e. not including all *enabled* ip families), then we will continue waiting from where the previous timer left off.  Following a full GC pass we will just recompute the interval as normal (doesn't matter if the full pass was caused by the timer or a signal).

Addresses: #40820

### CODE REVIEW

File: pkg/maps/ctmap/gc/gc.go [hunk 1]
```diff
@@ -110,8 +110,23 @@ func New(params parameters) *GC {
 	return gc
 }
 
+func (gc *GC) isFullGC(ipv4, ipv6 bool) bool {
+	// A full GC pass is when we perform GC on any and all
+	// enabled IP families.
+	// Partial passes can happen as a result of datapath
+	// signals on particular families (i.e. ct or nat).
+	return ipv4 == gc.ipv4 && ipv6 == gc.ipv6
```
Comment (aditighag) [inline pkg/maps/ctmap/gc/gc.go:118]: Umm... This is valid only for dual clusters, no?

Comment (tommyp1ckles) [reply pkg/maps/ctmap/gc/gc.go:118]: Say `gc.ipv4` is true, and `gc.ipv6` (indicating the cluster is not dualstack), then the passed ipv4/ipv6 will be true,false so this will return true (which is expected... as this is a "Full GC" pass in the case of a single-stack cluster).

**Review by borkmann — APPROVED** [review]

**Review by aspsk — APPROVED** [review]

File: pkg/maps/ctmap/gc/gc.go (hunk 1 above)
Comment (tommyp1ckles) [reply pkg/maps/ctmap/gc/gc.go:118]: Just as a note, this clause was copied from below.  I wanted to put it into a separate function to improve readability.

File: pkg/maps/ctmap/gc/gc.go [hunk 2]
```diff
@@ -178,14 +195,38 @@ func (gc *GC) Enable() {
...
+				forceInterval := time.Until(forceFullGCTTL)
+				if forceInterval < 0 {
+					forceInterval = 0
+				}
+				if forceInterval >= 0 && forceInterval < interval {
+					interval = forceInterval
+				} else {
+					// partial pass, but the new interval is less than any leftover ttl so
+					// we cache this as well.
+					cachedGCInterval = interval
```
Comment (aditighag) [inline pkg/maps/ctmap/gc/gc.go]: This can be simplified - 

```
forceInterval := max(0, time.Until(forceFullGCTTL))
if forceInterval < interval {
    interval = forceInterval
} else {
    cachedGCInterval = interval
}
```

File: pkg/maps/ctmap/gc/gc.go [hunk 3]
```diff
@@ -251,13 +292,15 @@ func (gc *GC) Enable() {
...
 	}()
 
-	// Wait until after initial scan is complete prior to starting ctmap metrics controller.
-	go func() {
-		<-initialScanComplete
-		gc.logger.Info("Initial scan of connection tracking completed, starting ctmap pressure metrics controller")
-		// Not supporting BPF map pressure for local CT maps as of yet.
-		ctmap.CalculateCTMapPressure(gc.controllerManager, gc.metricsRegistry, ctmap.GlobalMaps(gc.ipv4, gc.ipv6)...)
-	}()
+	if runMapPressureDaemon {
```
Comment (aditighag) [inline pkg/maps/ctmap/gc/gc.go:291]: How's this change related to the issues this PR is trying to fix?

File: pkg/maps/ctmap/gc/gc_test.go [hunk 4]
```diff
@@ -0,0 +1,109 @@
...
+	"github.com/cilium/cilium/pkg/endpoint"
+	"github.com/cilium/cilium/pkg/fqdn"
+	"github.com/cilium/cilium/pkg/maps/ctmap"
+	"github.com/cilium/cilium/pkg/option"
+	"github.com/cilium/cilium/pkg/signal"
+)
+
+// TestGCEnable tests the overall *flow* of ctmap GC scheduling
+// while abstracting out the underlying garbage collection logic.
+func TestGCEnable(t *testing.T) {
```
Comment (aditighag) [inline pkg/maps/ctmap/gc/gc_test.go]: It would be great to cover a couple of more tests cases as we've had many regressions in this code path:

- Receive both IPv4 and IPv6 signals
- The current test case is only testing low delete ratio (higher interval). It'll be good to also test a higher delete ratio (short interval).
- Receive IPv6 signals only (optional)

**Review by aditighag — CHANGES_REQUESTED** [review]
The `runGC` function is getting overloaded in terms of functionalities, and as a result, carrying a lot of bookkeeping state. But I understand that the general refactoring is out of scope of this PR as we would want to backport this fix. 
Left comments around code simplification and a couple of more test cases.

File: pkg/maps/ctmap/gc/gc.go (hunk 2 above)
Comment (tommyp1ckles) [reply pkg/maps/ctmap/gc/gc.go]: Oh! missed the memo on there finally being built in min/max funcs in Go.

File: pkg/maps/ctmap/gc/gc.go (hunk 3 above)
Comment (tommyp1ckles) [reply pkg/maps/ctmap/gc/gc.go:291]: Motivation: With this change, I wanted to add some real test coverage on the highLevel enable function, without having to worry about creating/mocking all the underlying map infrastructure.   This was specifically for the reasons we discussed - i.e. the control for for the GC loop getting too complicated so I wanted to be able to write some tests that _just_ check that logic.

So, before this would run a controller to do ctmap pressure iterate/counting, to avoid having to make all that mockable or create the maps I decided to just have it be optional when calling from the internal `gc.enable(...)` function and enabled by default for the exported `gc.Enable(...)` (i.e. similar to how I allow for passing a custom `doGC` to `enable`.

File: pkg/maps/ctmap/gc/gc_test.go (hunk 4 above)
Comment (tommyp1ckles) [reply pkg/maps/ctmap/gc/gc_test.go]: yup, good call, ill add extra coverage.

File: pkg/maps/ctmap/gc/gc.go (hunk 3 above)
Comment (tommyp1ckles) [reply pkg/maps/ctmap/gc/gc.go:291]: I'll put the testing refactors in a seperate commit however.

Comment (tommyp1ckles) [reply pkg/maps/ctmap/gc/gc.go:291]: @aditighag I broke this commit into 3:

1) Do the Enable/enable refactor to prep for our unit test changes.
2) Implement the fix
3) Add unit test

File: pkg/maps/ctmap/gc/gc_test.go (hunk 4 above)
Comment (tommyp1ckles) [reply pkg/maps/ctmap/gc/gc_test.go]: > The current test case is only testing low delete ratio (higher interval). It'll be good to also test a higher delete ratio (short interval).

note: I wanted to avoid adding this case, as testing relative "long vs short" durations would be more difficult to do than just checking if event "X" has happened within some reasonable timeout.

Comment (tommyp1ckles) [reply pkg/maps/ctmap/gc/gc_test.go]: I think those test cases would be better covered by the GetInerval tests in package ctmap (although, imo this should probably be moved to package gc, alongside with its tests).

Basically, we probably don't want to actually have to wait in the test to see if it waited longer, but rather just check that GetDuration computes those times as we would expect.

Comment (aditighag) [reply pkg/maps/ctmap/gc/gc_test.go]: >I think those test cases would be better covered by the GetInerval tests in package ctmap

I would like us to get more confidence on the changes in `runGC`. Higher delete ration => shorter interval
Not a blocking comment, but since we are early in the dev cycle, we don't have too much time pressure to ship the fix so it'll be good to work on the test coverage.

File: pkg/maps/ctmap/gc/gc.go [hunk 5]
```diff
@@ -191,12 +200,31 @@ func (gc *GC) enable(
 
 			// Mark the CT GC as over in each EP DNSZombies instance, if we did a *full* GC run
```
Comment (pchaigno) [inline pkg/maps/ctmap/gc/gc.go]: Nitpick: This comment probably needs to be moved 3 lines down.

**Review by pchaigno — COMMENTED** [review]
Thanks for tackling this and for the neat commit history!

In a scenario where there's a lot more traffic for one family than the other, won't this cause us to run GC more often? Was the CPU impact measured?

**Comment by tommyp1ckles** [comment]
@pchaigno 

> In a scenario where there's a lot more traffic for one family than the other, won't this cause us to run GC more often? Was the CPU impact measured?

It would, but only in so much that the we're running the family that did not get GC'd due to a "partial" signal (i.e. ipv4 only) from the datapath.  For example, if a full pass was to run in 2 minutes but was interrupted by a ipv4 signal, we would still run a full pass at most within 2 minutes to avoid starvation.

The main thing to affect CPU would likely be high signals, which would indicate CT/NAT pressure, the extra full passes should be negligible in that scenario.

File: pkg/maps/ctmap/gc/gc_test.go (hunk 4 above)
Comment (tommyp1ckles) [reply pkg/maps/ctmap/gc/gc_test.go]: @aditighag Added a test for the interval "ratchet" behavior: https://github.com/cilium/cilium/pull/41258/commits
This test is really showing the difficulty of this code, definitely think we need to look at refactoring this but this should provide some assurances in not having regressions here before/after the changes.

Note: This runs successfully before and after the gc.Enable changes.

**Review by pchaigno — APPROVED** [review]

**Review by aditighag — APPROVED** [review]
Thanks for the revisions, LGTM!
