### PR TITLE
bpf: service loopback for ipv6

### LINKED ISSUE #26733: pod can't access itself via service (IPv6 loopback)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In a dual-stack cluster, I create a pod and an ipv6 service, this pod is the only endpoint for this service. and I found that the service cannot be accessed in the pod. 

```
root@cyclinder3:~/cyclinder# kubectl  get po -o wide
NAME                        READY   STATUS    RESTARTS   AGE     IP              NODE                      NOMINATED NODE   READINESS GATES
test1-6dd8dc96c6-nfv92      1/1     Running   0          29m     10.244.65.80    ty-spider-control-plane   <none>           <none>
```

```
root@cyclinder3:~:/home/cilium# cilium endpoint list | grep test1
199        Disabled           Disabled          38058      k8s:app=test1                                                                  fd00:10:244::1e0   10.244.65.80    ready
```

I used `cilium monitor` and found that only SYN packets were sent and no ACK packets were responded.

```shell
root@cyclinder3:/home/cilium# cilium service list | grep fd00:10:244::1e0
14   [fd00:10:233::6d5]:80   ClusterIP      1 => [fd00:10:244::1e0]:80 (active)
```

```shell
root@test1-6dd8dc96c6-nfv92:/# curl -g [fd00:10:233::6d5]:80
curl: (28) Failed to connect to fd00:10:233::e5f port 80 after 131032 ms: Connection timed out

# another screen
root@ty-spider-control-plane:/home/cilium# cilium monitor --from 199
Listening for events on 16 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
level=info msg="Initializing dissection cache..." subsys=monitor
-> endpoint 199 flow 0x878a41da , identity 38058->38058 state new ifindex lxc6b1e61147d85 orig-ip fd00:10:244::1e0: [fd00:10:244::1e0]:45382 -> [fd00:10:244::1e0]:80 tcp SYN
-> endpoint 199 flow 0xd58912ba , identity 38058->38058 state established ifindex lxc6b1e61147d85 orig-ip fd00:10:244::1e0: [fd00:10:244::1e0]:45382 -> [fd00:10:244::1e0]:80 tcp SYN
-> endpoint 199 flow 0x42998434 , identity 38058->38058 state established ifindex lxc6b1e61147d85 orig-ip fd00:10:244::1e0: [fd00:10:244::1e0]:45382 -> [fd00:10:244::1e0]:80 tcp SYN
-> endpoint 199 flow 0x8f5076ac , identity 38058->38058 state established ifindex lxc6b1e61147d85 orig-ip fd00:10:244::1e0: [fd00:10:244::1e0]:45382 -> [fd00:10:244::1e0]:80 tcp SYN
-> endpoint 199 flow 0xa0c922ba , identity 38058->38058 state established ifindex lxc6b1e61147d85 orig-ip fd00:10:244::1e0: [fd00:10:244::1e0]:45382 -> [fd00:10:244::1e0]:80 tcp SYN
```

### Cilium Version

```
root@ty-spider-control-plane:/home/cilium# cilium version
Client: 1.13.4 4061cdfc 2023-06-14T03:37:39+00:00 go version go1.19.10 linux/amd64
Daemon: 1.13.4 4061cdfc 2023-06-14T03:37:39+00:00 go version go1.19.10 linux/amd64
```

### Kernel Version

```
root@ty-spider-control-plane:~# uname -a
Linux ty-spider-control-plane 5.15.0-75-generic #82-Ubuntu SMP Tue Jun 6 23:10:23 UTC 2023 x86_64 GNU/Linux
```

### Kubernetes Version

```
root@ty-spider-control-plane:~# kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-05-12T19:03:40Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-05-12T19:03:40Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
```

### Sysdump

v1.13.4: [cilium-sysdump-20230710-111806.zip](https://github.com/cilium/cilium/files/12001311/cilium-sysdump-20230710-111806.zip)

v1.12.5: [cilium-sysdump-20230711-105810.zip](https://github.com/cilium/cilium/files/12013940/cilium-sysdump-20230711-105810.zip)

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by saiaunghlyanhtet**
Service Loopback IPv6

Fixes: #26733 

```release-note
IPv6 support for pods connecting to themselves via a k8s service ("service loopback").
```

### CODE REVIEW

File: bpf/lib/lb.h [hunk 1]
```diff
@@ -1122,12 +1157,41 @@ static __always_inline int lb6_local(const void *map, struct __ctx_buff *ctx,
...
+			if (netns_cookie > 0 && lb6_svc_is_localredirect(svc) &&
+		    	lb6_skip_xlate_from_ctx_to_svc(netns_cookie, tuple->saddr, tuple->sport))
+				return CTX_ACT_OK;
+		#endif
+
+		#if defined(USE_LOOPBACK_LB)
+			union v6addr loopback_addr = IPV6_LOOPBACK;
+			ipv6_addr_copy(&new_saddr, &loopback_addr);
+			state->loopback = 1;
+		#endif
```
Comment (julianwiedmann) [inline bpf/lib/lb.h]: I don't think this will pass the compiler. Note that you can extend `bpf/tests/tc_nodeport_test.c` as needed to iterate faster.

File: bpf/lib/lb.h [hunk 2]
```diff
@@ -1122,12 +1157,41 @@ static __always_inline int lb6_local(const void *map, struct __ctx_buff *ctx,
...
+	    saddr.addr[6] == backend->address.addr[6] &&
+	    saddr.addr[7] == backend->address.addr[7] &&
+	    saddr.addr[8] == backend->address.addr[8] &&
+	    saddr.addr[9] == backend->address.addr[9] &&
+	    saddr.addr[10] == backend->address.addr[10] &&
+	    saddr.addr[11] == backend->address.addr[11] &&
+	    saddr.addr[12] == backend->address.addr[12] &&
+	    saddr.addr[13] == backend->address.addr[13] &&
+	    saddr.addr[14] == backend->address.addr[14] &&
+	    saddr.addr[15] == backend->address.addr[15]) {
```
Comment (julianwiedmann) [inline bpf/lib/lb.h]: Ideally this would be `ipv6_addr_equals()`.

File: pkg/node/local_node_store.go [hunk 3]
```diff
@@ -39,6 +39,7 @@ type LocalNode struct {
 	// v6 CIDR in which pod IPs are routable
 	IPv6NativeRoutingCIDR *cidr.CIDR
 	IPv4Loopback          net.IP
+	IPv6Loopback          net.IP
```
Comment (julianwiedmann) [inline pkg/node/local_node_store.go]: Have you already looked at how this ends up in the datapath? You can follow how `router_ipv6` is plumbed in via `bpf/include/bpf/config/node.h` and used as `CONFIG()` in the datapath.

Comment (saiaunghlyanhtet) [reply pkg/node/local_node_store.go]: @julianwiedmann 
Can I integrate IPv6Loopback like router_ipv6 via node.h? And if so, do I need to follow this docs https://github.com/cilium/cilium/blob/main/Documentation/contributing/development/datapath_config.rst , and run this command (make -C bpf -j$(nproc)) to auto-generate GO code in config?

Comment (julianwiedmann) [reply pkg/node/local_node_store.go]: yep that looks like a great guide to follow! Please shout on Slack if anything in there is not clear, this part of the loader infrastructure is fairly recent.

Comment (saiaunghlyanhtet) [reply pkg/node/local_node_store.go]: Can you have a look at the current condition of the PR if you have time? Anything else needs to be done apart from tc_nodeport_test.c?

Comment (julianwiedmann) [reply pkg/node/local_node_store.go]: Thank you! I can't do detailed pre-review of PRs, sorry. More than enough on my plate :).

I'd suggest splitting the changes into two patches (one that introduces `IPV6_LOOPBACK` in the controlplane, and a second patch that then adds all the datapath parts). And ideally we'd have both a connectivity test and a BPF-level for this specific behavior in the service translation, to confirm that your changes work as expected.

Note that https://github.com/cilium/cilium/pull/38818 is making similar changes for IPv4, maybe you can cross-check whether that matches up and check with @jrife for review :).

File: bpf/include/bpf/config/node.h [hunk 4]
```diff
@@ -16,3 +16,4 @@
 #include <node_config.h>
 
 NODE_CONFIG(union v6addr, router_ipv6, "Internal IPv6 router address assigned to the cilium_host interface")
+NODE_CONFIG(union v6addr, ipv6_loopback, "IPv6 loopback address")
```
Comment (jrife) [inline bpf/include/bpf/config/node.h]: It looks like we ended up settling on `service_loopback_ipv4` in https://github.com/cilium/cilium/pull/38818. Rename this and follow the [same patterns](https://github.com/cilium/cilium/pull/38818/commits/3d057129899afe3b6e0e75743116f0cd4c0183da).

Comment (saiaunghlyanhtet) [reply bpf/include/bpf/config/node.h]: Changed to service_loopback_ipv6.

**Comment by saiaunghlyanhtet** [comment]
@jrife I have changed to serivce_loopback_ipv6. If you have free time, can you have a look at it?. Currently, I am stuck at the condition in which source ip is not translated back to the service cluster IP. I think that the reverse NAT for the reply path is not being applied correctly. But, I have no idea which is going wrong.

The logs show multiple SYN packets from [fd00:10:244:1::dc8e]:53060 to [fd00:10:96::cd54]:80, indicating that the client is retransmitting SYN packets, likely because it is not receiving properly formatted replies.

$ k exec -ti -n kube-system cilium-qz7tt -- cilium-dbg monitor --related-to 542

Listening for events on 8 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
time=2025-06-08T07:43:34.15455902Z level=info msg="Initializing dissection cache..."
<- endpoint 542 flow 0x70e2ab0d , identity 20084->unknown state unknown ifindex 0 orig-ip 0.0.0.0: [fd00:10:244:1::dc8e]:53060 -> [fd00:10:96::cd54]:80 tcp SYN
-> endpoint 542 flow 0x70e2ab0d , identity 20084->20084 state new ifindex lxc14f4f090a3e0 orig-ip fd00::1: [fd00::1]:53060 -> [fd00:10:244:1::dc8e]:80 tcp SYN
<- endpoint 542 flow 0xcfd94455 , identity 20084->unknown state unknown ifindex 0 orig-ip 0.0.0.0: [fd00:10:244:1::dc8e]:80 -> [fd00::1]:53060 tcp SYN, ACK
-> endpoint 542 flow 0xcfd94455 , identity 20084->20084 state reply ifindex lxc14f4f090a3e0 orig-ip fd00:10:244:1::dc8e: [fd00:10:244:1::dc8e]:80 -> [fd00::1]:53060 tcp SYN, ACK
<- endpoint 542 flow 0xc34aebbb , identity 20084->unknown state unknown ifindex 0 orig-ip 0.0.0.0: [fd00:10:244:1::dc8e]:53060 -> [fd00:10:96::cd54]:80 tcp SYN
-> endpoint 542 flow 0xc34aebbb , identity 20084->20084 state established ifindex lxc14f4f090a3e0 orig-ip fd00::1: [fd00::1]:53060 -> [fd00:10:244:1::dc8e]:80 tcp SYN
<- endpoint 542 flow 0x8c902078 , identity 20084->unknown state unknown ifindex 0 orig-ip 0.0.0.0: [fd00:10:244:1::dc8e]:80 -> [fd00::1]:53060 tcp SYN, ACK
-> endpoint 542 flow 0x8c902078 , identity 20084->20084 state reply ifindex lxc14f4f090a3e0 orig-ip fd00:10:244:1::dc8e: [fd00:10:244:1::dc8e]:80 -> [fd00::1]:53060 tcp SYN, ACK
<- endpoint 542 flow 0x15fde42f , identity 20084->unknown state unknown ifindex 0 orig-ip 0.0.0.0: [fd00:10:244:1::dc8e]:80 -> [fd00::1]:53060 tcp SYN, ACK
-> endpoint 542 flow 0x15fde42f , identity 20084->20084 state reply ifindex lxc14f4f090a3e0 orig-ip fd00:10:244:1::dc8e: [fd00:10:244:1::dc8e]:80 -> [fd00::1]:53060 tcp SYN, ACK
<- endpoint 542 flow 0xfb86fd56 , identity 20084->unknown state unknown ifindex 0 orig-ip 0.0.0.0: [fd00:10:244:1::dc8e]:53060 -> [fd00:10:96::cd54]:80 tcp SYN
-> endpoint 542 flow 0xfb86fd56 , identity 20084->20084 state established ifindex lxc14f4f090a3e0 orig-ip fd00::1: [fd00::1]:53060 -> [fd00:10:244:1::dc8e]:80 tcp SYN
<- endpoint 542 flow 0xf6a6963b , identity 20084->unknown state unknown ifindex 0 orig-ip 0.0.0.0: [fd00:10:244:1::dc8e]:80 -> [fd00::1]:53060 tcp SYN, ACK
-> endpoint 542 flow 0xf6a6963b , identity 20084->20084 state reply ifindex lxc14f4f090a3e0 orig-ip fd00:10:244:1::dc8e: [fd00:10:244:1::dc8e]:80 -> [fd00::1]:53060 tcp SYN, ACK
<- endpoint 542 flow 0x3f4fed5 , identity 20084->unknown state unknown ifindex 0 orig-ip 0.0.0.0: [fd00:10:244:1::dc8e]:53060 -> [fd00:10:96::cd54]:80 tcp SYN
-> endpoint 542 flow 0x3f4fed5 , identity 20084->20084 state established ifindex lxc14f4f090a3e0 orig-ip fd00::1: [fd00::1]:53060 -> [fd00:10:244:1::dc8e]:80 tcp SYN
<- endpoint 542 flow 0xce35e2bf , identity 20084->unknown state unknown ifindex 0 orig-ip 0.0.0.0: [fd00:10:244:1::dc8e]:80 -> [fd00::1]:53060 tcp SYN, ACK
-> endpoint 542 flow 0xce35e2bf , identity 20084->20084 state reply ifindex lxc14f4f090a3e0 orig-ip fd00:10:244:1::dc8e: [fd00:10:244:1::dc8e]:80 -> [fd00::1]:53060 tcp SYN, ACK
<- endpoint 542 flow 0x72c6a27e , identity 20084->unknown state unknown ifindex 0 orig-ip 0.0.0.0: [fd00:10:244:1::dc8e]:80 -> [fd00::1]:53060 tcp SYN, ACK
-> endpoint 542 flow 0x72c6a27e , identity 20084->20084 state reply ifindex lxc14f4f090a3e0 orig-ip fd00:10:244:1::dc8e: [fd00:10:244:1::dc8e]:80 -> [fd00::1]:53060 tcp SYN, ACK
<- endpoint 542 flow 0x0 , identity 20084->unknown state unknown ifindex 0 orig-ip 0.0.0.0: fe80::8034:dfff:fe01:1dbf -> fd00:10:244:1::6ec8 icmp NeighborSolicitation

File: Documentation/cmdref/cilium-agent.md [hunk 5]
```diff
@@ -278,6 +278,7 @@ cilium-agent [flags]
       --ipv6-node string                                          IPv6 address of node (default "auto")
       --ipv6-pod-subnets strings                                  List of IPv6 pod subnets to preconfigure for encryption
       --ipv6-range string                                         Per-node IPv6 endpoint prefix, e.g. fd02:1:1::/96 (default "auto")
+      --ipv6-service-loopback-address string                      IPv6 address for service loopback SNAT when a Pod talks to itself over a Service. (default "fd00::1")
```
Comment (jrife) [inline Documentation/cmdref/cilium-agent.md]: nit: The language here slightly differs from `ipv4-service-loopback-address`. Keep them consistent.

#### Current
```
--ipv4-service-loopback-address string                      IPv4 source address to use for SNAT when a Pod talks to itself over a Service. (default "169.254.42.1")
...
--ipv6-service-loopback-address string                      IPv6 address for service loopback SNAT when a Pod talks to itself over a Service. (default "fd00::1")
...
```

#### Should Be
```
--ipv4-service-loopback-address string                      IPv4 source address to use for SNAT when a Pod talks to itself over a Service. (default "169.254.42.1")
...
--ipv6-service-loopback-address string                      IPv6 source address to use for SNAT when a Pod talks to itself over a Service. (default "fd00::1")
...
```

File: bpf/bpf_lxc.c [hunk 6]
```diff
@@ -543,6 +544,9 @@ static __always_inline int handle_ipv6_from_lxc(struct __ctx_buff *ctx, __u32 *d
 		}
 #endif /* ENABLE_L7_LB */
 
+		if (hairpin_flow)
```
Comment (jrife) [inline bpf/bpf_lxc.c:563]: Can we add a comment here similar to the one in `handle_ipv4_from_lxc`?

File: bpf/bpf_lxc.c [hunk 7]
```diff
@@ -690,13 +696,23 @@ static __always_inline int handle_ipv6_from_lxc(struct __ctx_buff *ctx, __u32 *d
 	if (is_defined(ENABLE_ROUTING) || is_defined(ENABLE_HOST_ROUTING)) {
```
Comment (jrife) [inline bpf/bpf_lxc.c]: I think this condition needs an additional `|| hairpin_flow` condition similar to the IPv4 logic. Have you tested with endpoint routes?

File: bpf/bpf_lxc.c [hunk 8]
```diff
@@ -690,13 +696,23 @@ static __always_inline int handle_ipv6_from_lxc(struct __ctx_buff *ctx, __u32 *d
...
-		 *    host itself.
+		/* Loopback replies are addressed to config service_loopback_ipv6, so
+		 * an endpoint lookup with ip6->daddr won't work.
+		 *
+		 * But as it is loopback traffic, the clientIP and backendIP
+		 * are identical and we can just use the packet's saddr
+		 * for the destination endpoint lookup.
 		 */
-		ep = lookup_ip6_endpoint(ip6);
+		if (ct_status == CT_REPLY && hairpin_flow)
```
Comment (jrife) [inline bpf/bpf_lxc.c:728]: nit: I would slightly prefer if we could keep the structure similar to the IPv4 version. In particular, by declaring `union v6addr daddr = ip6->daddr` in this scope and reassigning its value to `saddr` so that there's only one place `__lookup_ip6_endpoint` is called.

File: bpf/lib/lb.h [hunk 9]
```diff
@@ -570,9 +587,11 @@ lb6_lookup_rev_nat_entry(struct __ctx_buff *ctx __maybe_unused, __u16 index)
  * @arg ctx		packet
  * @arg l4_off		offset to L4
  * @arg index		reverse NAT index
+ * @arg loopback    loopback connection
  * @arg tuple		tuple
  */
 static __always_inline int lb6_rev_nat(struct __ctx_buff *ctx, int l4_off, __u16 index,
+					   bool loopback,
```
Comment (jrife) [inline bpf/lib/lb.h]: nit: Indention looks weird here. This doesn't look aligned.

File: bpf/lib/lb.h [hunk 10]
```diff
@@ -1123,13 +1155,30 @@ static __always_inline int lb6_local(const void *map, struct __ctx_buff *ctx,
...
+	if (ipv6_addr_equals(&saddr, &backend->address)) {
+	#if defined(ENABLE_LOCAL_REDIRECT_POLICY)
+		if (netns_cookie > 0 && unlikely(lb6_svc_is_localredirect(svc)) &&
+		    lb6_skip_xlate_from_ctx_to_svc(netns_cookie, tuple->daddr, tuple->sport))
+			return CTX_ACT_OK;
+	#endif
+	}
+
+	if (ipv6_addr_equals(&saddr, &backend->address)) {
+	#ifdef USE_LOOPBACK_LB
```
Comment (jrife) [inline bpf/lib/lb.h:1167]: This can just be moved into the if block above instead of doing `if (ipv6_addr_equals(&saddr, &backend->address))` again. This would be more consistent with `lb4_local` as well.

File: bpf/lib/lb.h [hunk 11]
```diff
@@ -1123,13 +1155,30 @@ static __always_inline int lb6_local(const void *map, struct __ctx_buff *ctx,
...
+			state->loopback = 1;
+	#endif
+	}
 #endif /* ENABLE_LOCAL_REDIRECT_POLICY */
 
-	ipv6_addr_copy(&tuple->daddr, &backend->address);
+#ifdef USE_LOOPBACK_LB
+	if (!state->loopback)
+#endif
+
```
Comment (jrife) [inline bpf/lib/lb.h]: nit: get rid of the empty line.

File: bpf/tests/tc_nodeport_test.c [hunk 12]
```diff
@@ -545,3 +551,425 @@ int tc_drop_no_backend_check(const struct __ctx_buff *ctx)
...
+	struct pktgen builder;
+	volatile const __u8 *src = mac_one;
+	volatile const __u8 *dst = mac_two;
+	struct tcphdr *l4;
+	void *data;
+
+	pktgen__init(&builder, ctx);
+
+	l4 = pktgen__push_ipv6_tcp_packet(&builder,
+									  (__u8 *)src, (__u8 *)dst,
```
Comment (jrife) [inline bpf/tests/tc_nodeport_test.c]: fix indention

File: bpf/tests/tc_nodeport_test.c [hunk 13]
```diff
@@ -545,3 +551,425 @@ int tc_drop_no_backend_check(const struct __ctx_buff *ctx)
...
```
Comment (jrife) [inline bpf/tests/tc_nodeport_test.c]: fix indention.

File: bpf/tests/tc_nodeport_test.c [hunk 14]
```diff
@@ -545,3 +551,425 @@ int tc_drop_no_backend_check(const struct __ctx_buff *ctx)
...
```
Comment (jrife) [inline bpf/tests/tc_nodeport_test.c]: fix indention.

File: pkg/datapath/loader/config.go [hunk 15]
```diff
@@ -19,5 +19,9 @@ func nodeConfig(lnc *datapath.LocalNodeConfiguration) config.Node {
 		node.RouterIPv6 = ([16]byte)(lnc.CiliumInternalIPv6.To16())
 	}
 
+	if lnc.ServiceLoopbackIPv6 != nil {
```
Comment (jrife) [inline pkg/datapath/loader/config.go]: Group this together with 

```
if lnc.ServiceLoopbackIPv4 != nil {
		node.ServiceLoopbackIPv4 = [4]byte(lnc.ServiceLoopbackIPv4.To4())
	}
```

**Comment by jrife** [comment]
> Currently, I am stuck at the condition in which source ip is not translated back to the service cluster IP. I think that the reverse NAT for the reply path is not being applied correctly. But, I have no idea which is going wrong.

Off the top of my head, I'm not sure. I may have some time later this week to look at it in a bit more detail. In the meantime, I left a few comments. I'd recommend fixing whatever unit tests and checkpatch checks are failing and try testing again. The checkpatch stuff is likely similar to some of the formatting stuff I commented on.

File: bpf/bpf_lxc.c (hunk 7 above)
Comment (saiaunghlyanhtet) [reply bpf/bpf_lxc.c]: Thank you for pointing that out.

**Comment by saiaunghlyanhtet** [comment]
I fixed the problem related to the reverse nat reply path and tested the service loopback for ipv6 in my local cluster. The service loopback works properly, so marked this pr ready for review.

File: bpf/lib/lb.h [hunk 16]
```diff
@@ -847,24 +866,35 @@ lb6_select_backend_id(struct __ctx_buff *ctx __maybe_unused,
...
-		__be32 sum = csum_diff(key->address.addr, 16, new_dst->addr,
-				       16, 0);
+	sum = csum_diff(key->address.addr, 16, new_dst->addr, 16, 0);
+#ifdef USE_LOOPBACK_LB
+	if (new_saddr && (new_saddr->d1 || new_saddr->d2)) {
+		cilium_dbg_lb(ctx, DBG_LB6_LOOPBACK_SNAT, old_saddr->p4, new_saddr->p4);
 
+		if (ipv6_store_saddr(ctx, (void *)new_saddr->addr, l3_off) < 0)
+			return DROP_WRITE_ERROR;
+		sum = csum_diff(old_saddr->addr, 16, new_saddr->addr, 16, 0);
```
Comment (andreaterzolo) [inline bpf/lib/lb.h]: I believe we need to provide the previous `sum` to have a correct computation of the final checksum
```suggestion
		sum = csum_diff(old_saddr->addr, 16, new_saddr->addr, 16, sum);
```

Comment (andreaterzolo) [reply bpf/lib/lb.h]: A slightly more performant version could be
```c
{
	const union v6addr *new_dst = &backend->address;
	struct csum_offset csum_off = {};
	__be32 sum = 0;

	if (has_l4_header)
		csum_l4_offset_and_flags(nexthdr, &csum_off);

	if (ipv6_store_daddr(ctx, new_dst->addr, l3_off) < 0)
		return DROP_WRITE_ERROR;
#ifdef USE_LOOPBACK_LB
	if (new_saddr && (new_saddr->d1 || new_saddr->d2)) {
		cilium_dbg_lb(ctx, DBG_LB6_LOOPBACK_SNAT, old_saddr->p4, new_saddr->p4);

		if (ipv6_store_saddr(ctx, (void *)new_saddr->addr, l3_off) < 0)
			return DROP_WRITE_ERROR;
		sum = csum_diff(old_saddr->addr, 16, new_saddr->addr, 16, 0);
	}
#endif /* USE_LOOPBACK_LB */
	if (csum_off.offset) {
		sum = csum_diff(key->address.addr, 16, new_dst->addr, 16, sum);

		if (csum_l4_replace(ctx, l4_off, &csum_off, 0, sum,
				    BPF_F_PSEUDO_HDR) < 0)
			return DROP_CSUM_L4;
	}

	if (!has_l4_header)
		return CTX_ACT_OK;

	return lb_l4_xlate(ctx, nexthdr, l4_off, &csum_off, key->dport,
			   backend->port);
}
```

in this way we compute `sum = csum_diff(key->address.addr, 16, new_dst->addr, 16, sum);` only when we really need to rewrite the l4 checksum. WDYT?

File: bpf/tests/tc_nodeport_test.c [hunk 17]
```diff
@@ -545,3 +551,428 @@ int tc_drop_no_backend_check(const struct __ctx_buff *ctx)
...
+
+    if ((void *)l4 + sizeof(struct tcphdr) > data_end)
+	test_fatal("l4 out of bounds");
+
+    if (l4->source != tcp_src_one)
+	test_fatal("src TCP port was changed");
+
+    if (l4->dest != tcp_dst_one)
+	test_fatal("dst TCP port incorrect");
+
```
Comment (andreaterzolo) [inline bpf/tests/tc_nodeport_test.c:640]: maybe we could assert against the l4 checksum here `if (l4->check != bpf_htons(...))` like in the ipv4 tests

File: bpf/tests/tc_nodeport_test.c [hunk 18]
```diff
@@ -545,3 +551,428 @@ int tc_drop_no_backend_check(const struct __ctx_buff *ctx)
...
+    tuple.sport = tcp_src_one;
+    memcpy(&tuple.daddr, (const void *)SERVICE_IPV6, sizeof(tuple.daddr));
+    tuple.dport = tcp_svc_one;
+
+    ipv6_ct_tuple_swap_ports(&tuple);
+
+    ct_entry = map_lookup_elem(get_ct_map6(&tuple), &tuple);
+    if (!ct_entry)
+	test_fatal("no CT_SERVICE entry found");
+
```
Comment (andreaterzolo) [inline bpf/tests/tc_nodeport_test.c:659]: We could also assert against the second conntrack entry created (`tuple.flags = TUPLE_F_OUT`), see the IPv4 corresponding test

File: bpf/tests/tc_nodeport_test.c (hunk 17 above)
Comment (andreaterzolo) [reply bpf/tests/tc_nodeport_test.c:640]: Same in all other tests below

File: bpf/lib/lb.h [hunk 19]
```diff
@@ -542,6 +543,22 @@ static __always_inline int __lb6_rev_nat(struct __ctx_buff *ctx, int l4_off,
...
 	ipv6_addr_copy(&tuple->saddr, &nat->address);
 
+#ifdef USE_LOOPBACK_LB
+	if (loopback) {
+		union v6addr old_daddr;
+
+		ipv6_addr_copy(&old_daddr, &tuple->daddr);
+		cilium_dbg_lb(ctx, DBG_LB6_LOOPBACK_SNAT_REV, old_daddr.p4, old_saddr.p4);
+
+		ret = ipv6_store_daddr(ctx, old_saddr.addr, ETH_HLEN);
```
Comment (andreaterzolo) [inline bpf/lib/lb.h:523]: Shouldn't we call something like `csum_diff` to take the source address rewriting into consideration for the final L4_checksum update?

**Review by Andreagit97 — COMMENTED** [review]
Hi! I'm not a maintainer or reviewer of this repo, but I was looking at this casually and noticed a few things. I've left some questions/comments about the L4 checksum computation. Hope they might be helpful!

File: bpf/include/bpf/config/node.h [hunk 20]
```diff
@@ -15,6 +15,7 @@
 /* Legacy node config rendered at agent runtime. */
 #include <node_config.h>
 
+NODE_CONFIG(union v6addr, service_loopback_ipv6, "IPv6 source address used for SNAT when a Pod talks to itself over a Service")
```
Comment (jrife) [inline bpf/include/bpf/config/node.h]: small nit: I feel like it makes more sense to have `service_loopback_ipv4` above `service_loopback_ipv6` here.

File: bpf/bpf_lxc.c [hunk 21]
```diff
@@ -697,16 +709,28 @@ static __always_inline int handle_ipv6_from_lxc(struct __ctx_buff *ctx, __u32 *d
...
+		 * are identical and we can just use the packet's saddr
+		 * for the destination endpoint lookup.
+		 */
+		if (ct_status == CT_REPLY && hairpin_flow)
+			ipv6_addr_copy(&daddr, (union v6addr *)&ip6->saddr);
 		/* Lookup IPv6 address, this will return a match if:
-		 *  - The destination IP address belongs to a local endpoint managed by
-		 *    cilium
-		 *  - The destination IP address is an IP address associated with the
-		 *    host itself.
```
Comment (jrife) [inline bpf/bpf_lxc.c:710]: nit: Remove these extra spaces that were introduced to make the diff cleaner.

File: bpf/bpf_lxc.c [hunk 22]
```diff
@@ -1639,6 +1665,19 @@ ipv6_policy(struct __ctx_buff *ctx, struct ipv6hdr *ip6, __u32 src_label,
 		if (tc_index_from_ingress_proxy(ctx))
 			break;
 
+#if defined(ENABLE_PER_PACKET_LB)
+		loopback_addr = CONFIG(service_loopback_ipv6);
```
Comment (jrife) [inline bpf/bpf_lxc.c:1661]: Is `loopback_addr` necessary here? Can we just pass `&CONFIG(service_loopback_ipv6` directly to `ipv6_addr_equals`?

File: bpf/lib/lb.h [hunk 23]
```diff
@@ -542,6 +543,22 @@ static __always_inline int __lb6_rev_nat(struct __ctx_buff *ctx, int l4_off,
...
+		if (IS_ERR(ret))
+			return DROP_WRITE_ERROR;
+
+		/* Update the tuple address which is representing the destination address */
+		ipv6_addr_copy(&tuple->saddr, &old_saddr);
+    }
```
Comment (jrife) [inline bpf/lib/lb.h]: nit: this brace doesn't look aligned with the if statement above.

File: bpf/lib/lb.h [hunk 24]
```diff
@@ -579,9 +596,11 @@ lb6_lookup_rev_nat_entry(struct __ctx_buff *ctx __maybe_unused, __u16 index)
  * @arg ctx		packet
  * @arg l4_off		offset to L4
  * @arg index		reverse NAT index
+ * @arg loopback    loopback connection
```
Comment (jrife) [inline bpf/lib/lb.h]: nit: alignment with other args.

File: bpf/bpf_lxc.c (hunk 22 above)
Comment (saiaunghlyanhtet) [reply bpf/bpf_lxc.c:1661]: I have already tried it. But, it leads to incompatible pointer type error.

File: bpf/tests/tc_nodeport_test.c (hunk 17 above)
Comment (saiaunghlyanhtet) [reply bpf/tests/tc_nodeport_test.c:640]: Thanks for pointing that out. I forgot to add check for checksum.

File: bpf/lib/lb.h (hunk 16 above)
Comment (saiaunghlyanhtet) [reply bpf/lib/lb.h]: I think your suggestion looks better. But, we may need to be consistent with `lb4_xlate`. I'd love to get other reviewers' opinions on this.

File: bpf/lib/lb.h (hunk 19 above)
Comment (saiaunghlyanhtet) [reply bpf/lib/lb.h:523]: I think we don't need to do that for IPv6 as we have already done L4 checksum update via `ipv6_l4_csum_update`.

File: bpf/lib/lb.h (hunk 16 above)
Comment (jrife) [reply bpf/lib/lb.h]: > But, we may need to be consistent with lb4_xlate

IMO we should keep things consistent with the v4 stuff until this is merged. Then, if there's an optimization to be made, it could be done in another PR that targets both v4 and v6 at the same time.

File: bpf/lib/lb.h (hunk 19 above)
Comment (andreaterzolo) [reply bpf/lib/lb.h:523]: uhm, in the current code, we are recomputing the checksum only on the saddr change, but in the hairpin flow, we also change the daddr so we need to take it into account when we recompute the L4 checksum.

We can probably check it with the `hairpin_flow_4_reverse_ingress_v6` test.

I see you used this checksum `(l4->check != bpf_htons(0xdfd0))`, but if I put the packet generated after the SETUP phase into Wireshark 
```
00000000  13 37 13 37 13 37 de ad  be ef de ef 86 dd 60 00
00000010  00 00 00 28 06 40 fd 05  00 00 00 00 00 00 00 00
00000020  00 00 00 00 00 03 fd 04  00 00 00 00 00 00 00 00
00000030  00 00 00 00 00 01 00 50  57 3a 40 e2 01 00 00 00
00000040  00 00 50 12 ff ff df d0  00 00 53 68 6f 75 6c 64
00000050  20 6e 6f 74 20 63 68 61  6e 67 65 21 21 00
```
I see a validation error on the L4 checksum

```
Checksum: 0xdfd0 incorrect, should be 0xdfd1
```

This means that there is probably something wrong in the checksum computation, and I believe it is the fact that we are not recomputing it when we change the daddr

Comment (saiaunghlyanhtet) [reply bpf/lib/lb.h:523]: Thanks. Fixed.

**Comment by asauber** [comment]
Are you able to see the output of the checkpatch workflow? You have some lines >100 chars which is causing it to fail.

**Comment by saiaunghlyanhtet** [comment]
> Are you able to see the output of the checkpatch workflow? You have some lines >100 chars which is causing it to fail.

I have fixed some warnings. But, I think the warning in node.h cannot be solved.

**Comment by asauber** [comment]
This edit would make checkpatch happy

```patch
diff --git a/bpf/include/bpf/config/node.h b/bpf/include/bpf/config/node.h
index 8f4d647cbe..048fde6229 100644
--- a/bpf/include/bpf/config/node.h
+++ b/bpf/include/bpf/config/node.h
@@ -15,10 +15,16 @@
 /* Legacy node config rendered at agent runtime. */
 #include <node_config.h>

-NODE_CONFIG(union v4addr, service_loopback_ipv4, "IPv4 source address used for SNAT when a Pod talks to itself over a Service")
-NODE_CONFIG(union v6addr, router_ipv6, "Internal IPv6 router address assigned to the cilium_host interface")
+NODE_CONFIG(union v4addr, service_loopback_ipv4,
+           "IPv4 source address used for SNAT when a Pod talks to itself over a Service")
+NODE_CONFIG(union v6addr, service_loopback_ipv6,
+           "IPv6 source address used for SNAT when a Pod talks to itself over a Service")
+NODE_CONFIG(union v6addr, router_ipv6,
+           "Internal IPv6 router address assigned to the cilium_host interface")

-NODE_CONFIG(__u32, trace_payload_len, "Length of payload to capture when tracing native packets.")
+NODE_CONFIG(__u32, trace_payload_len,
+           "Length of payload to capture when tracing native packets.")
 #define TRACE_PAYLOAD_LEN CONFIG(trace_payload_len) /* Backwards compatibility */

-NODE_CONFIG(__u32, trace_payload_len_overlay, "Length of payload to capture when tracing overlay packets.")
+NODE_CONFIG(__u32, trace_payload_len_overlay,
+           "Length of payload to capture when tracing overlay packets.")
```

**Review by thorn3r — APPROVED** [review]
Approving for the agent-related work, it looks good :+1:  I think a more detailed commit message, and even splitting the datapath and agent changes into separate commits, would be nice

File: bpf/include/bpf/config/node.h [hunk 25]
```diff
@@ -15,12 +15,19 @@
 /* Legacy node config rendered at agent runtime. */
 #include <node_config.h>
 
-NODE_CONFIG(union v4addr, service_loopback_ipv4, "IPv4 source address used for SNAT when a Pod talks to itself over a Service")
-NODE_CONFIG(union v6addr, router_ipv6, "Internal IPv6 router address assigned to the cilium_host interface")
-
-NODE_CONFIG(__u32, trace_payload_len, "Length of payload to capture when tracing native packets.")
+NODE_CONFIG(union v4addr, service_loopback_ipv4,
+	    "IPv4 source address used for SNAT when a Pod talks to itself over a Service")
+NODE_CONFIG(union v6addr, service_loopback_ipv6,
```
Comment (jrife) [inline bpf/include/bpf/config/node.h:19]: nit: checkpatch would probably be happy if you just made this adjustment to the lines you added. My preference would be to only change what you need for this PR and leave reformatting the other lines for another patch, but not a blocker.

File: pkg/option/config.go [hunk 26]
```diff
@@ -773,6 +773,9 @@ const (
 	// ServiceLoopbackIPv4 is the address to use for service loopback SNAT
 	ServiceLoopbackIPv4 = "ipv4-service-loopback-address"
 
+	// ServiceLoopbackIPv6 is the address to use for service loopback SNAT
+	ServiceLoopbackIPv6 = "ipv6-service-loopback-address"
```
Comment (asauber) [inline pkg/option/config.go:747]: Sorry for the delay on this comment. We prefer that all new config options are added to a hive cell, to begin the process of modularizing the related feature. If you take a look at the [history on this file](https://github.com/cilium/cilium/commits/main/pkg/option/config.go), you will see some recent example of refactors into cells. The initial refactor can be purely for the sake of config, with other modularlization coming later. Could you look into making this change?

Comment (saiaunghlyanhtet) [reply pkg/option/config.go:747]: To make it clear, I would like to confirm the cell file to which I need to move the current config. Is it ok to move to datapath/loader/cell.go? Or other file?

Comment (asauber) [reply pkg/option/config.go:747]: Logically, pkg/ipam/cell/cell.go seems like the right place, but given the breadth of changes that are required in this PR, that might not be feasible on the dependency graph. Could you give that a try and see if you run into any issues?

@joamaki is there a good way to visualize the dependency graph in order to make this type of decision, or any other advice that you would provide here?

Comment (joamaki) [reply pkg/option/config.go:747]: Since we already have `ServiceLoopbackIPv4` here I'd be OK with adding it here for now and then moving them both into a saner place in another PR. It'd probably make sense to do that as part of a bigger refactoring that moves `daemon/cmd/ipam.go` into `pkg/ipam`. @cilium/sig-ipam any opinion?

**Review by asauber — APPROVED** [review]
Approving for config. Given the above discussion, it seems like a separate refactor would be the place to move the flag.

File: bpf/include/bpf/config/node.h (hunk 25 above)
Comment (saiaunghlyanhtet) [reply bpf/include/bpf/config/node.h:19]: Fixed it. I think that the current checkpatch failed because of unknown manifest issue related t checkpatch image.

Comment (pchaigno) [reply bpf/include/bpf/config/node.h:19]: Yes, it's unrelated to your changes. It will fix itself next time you rebase.

File: pkg/defaults/defaults.go [hunk 27]
```diff
@@ -310,6 +310,9 @@ const (
 	// ServiceLoopbackIPv4 is the default address for service loopback
 	ServiceLoopbackIPv4 = "169.254.42.1"
 
+	// ServiceLoopbackIPv6 is the default address for service loopback
+	ServiceLoopbackIPv6 = "fd00::1"
```
Comment (pchaigno) [inline pkg/defaults/defaults.go]: How was this selected? Wouldn't an IP address within the range reserved for link-local addresses (fe80::/64) be more appropriate?

File: bpf/tests/tc_nodeport_test.c [hunk 28]
```diff
@@ -537,3 +543,456 @@ int tc_drop_no_backend_check(const struct __ctx_buff *ctx)
...
+    struct ipv6hdr *l3;
+    struct tcphdr *l4;
+
+    test_init();
+
+    data = (void *)(long)ctx->data;
+    data_end = (void *)(long)ctx->data_end;
+
+    if (data + sizeof(__u32) > data_end)
+	test_fatal("status code out of bounds");
```
Comment (pchaigno) [inline bpf/tests/tc_nodeport_test.c]: There seem to be an indentation issue on all the `if` statements in this function.

File: bpf/tests/tc_nodeport_test.c [hunk 29]
```diff
@@ -11,6 +11,7 @@
 
 /* Enable code paths under test*/
 #define ENABLE_IPV4
+#define ENABLE_IPV6
```
Comment (pchaigno) [inline bpf/tests/tc_nodeport_test.c:14]: Could you move the new tests into their own commit?

Optionally: Probably even better if you can introduce them each in their own commit and describe in the commit descriptions what scenario is covered.

**Review by pchaigno — COMMENTED** [review]
Thanks a lot for working on this! I looks really good :)

I only have minor comments below. IMO, it should be good to merge soon.

File: pkg/defaults/defaults.go (hunk 27 above)
Comment (saiaunghlyanhtet) [reply pkg/defaults/defaults.go]: Just chose it because I think it is just private and routable within the cluster and interface-agnostic.

File: bpf/tests/tc_nodeport_test.c (hunk 29 above)
Comment (saiaunghlyanhtet) [reply bpf/tests/tc_nodeport_test.c:14]: I have moved the new tests into a single commit in which each test is properly described about what scenario is covered.

File: bpf/tests/tc_nodeport_test.c (hunk 28 above)
Comment (saiaunghlyanhtet) [reply bpf/tests/tc_nodeport_test.c]: Fixed the indentation issue.

File: pkg/defaults/defaults.go (hunk 27 above)
Comment (pchaigno) [reply pkg/defaults/defaults.go]: Let's switch to a reserved link-local address then. Less chances of conflicts.

Comment (saiaunghlyanhtet) [reply pkg/defaults/defaults.go:314]: Can I use any address I want for LLA or any address you would like to recommend for consistency?

Comment (saiaunghlyanhtet) [reply pkg/defaults/defaults.go]: Switched to LLA address.

**Review by pchaigno — APPROVED** [review]

File: bpf/bpf_lxc.c [hunk 30]
```diff
@@ -1583,6 +1607,7 @@ ipv6_policy(struct __ctx_buff *ctx, struct ipv6hdr *ip6, __u32 src_label,
 	__u8 policy_match_type = POLICY_MATCH_NONE;
 	__u8 audited = 0;
 	__u8 auth_type = 0;
+	union v6addr loopback_addr;
```
Comment (pchaigno) [inline bpf/bpf_lxc.c]: This variable can be unused so should be marked as `__maybe_unused`. This is why the CI is currently failing (or at least one reason).

**Review by joamaki — APPROVED** [review]

File: bpf/bpf_lxc.c (hunk 30 above)
Comment (saiaunghlyanhtet) [reply bpf/bpf_lxc.c]: Thanks for pointing that out. Fixed it.

File: pkg/monitor/datapath_debug.go [hunk 31]
```diff
@@ -66,6 +66,8 @@ const (
 	DbgLb6LookupBackendFail
 	DbgLb6ReverseNatLookup
 	DbgLb6ReverseNat
+	DbgLb6LoopbackSnat
+	DbgLb6LoopbackSnatRev
```
Comment (pchaigno) [inline pkg/monitor/datapath_debug.go]: The integration tests are failing as a consequence of this change. You'll need to also update the list in `api/v1/flow/flow.proto` and regenerate the protobuf files, with `make generate-hubble-api`.

Ideally, I'd move the two new constants into their own commit and would note the command used to generate the files (i.e., `make generate-hubble-api`). Then, the new constants can be used in subsequent commits.

Comment (pchaigno) [reply pkg/monitor/datapath_debug.go]: Since you'll need to push, please rebase on latest `main` at the same time. That should help reduce the number of CI issues on the branch. I think we're close to being able to merge :slightly_smiling_face:

Comment (saiaunghlyanhtet) [reply pkg/monitor/datapath_debug.go]: Regenerated the flow.pb.go and rebased on the latest main.

File: api/v1/flow/flow.proto [hunk 32]
```diff
@@ -948,4 +948,6 @@ enum DebugEventType {
     DBG_SK_ASSIGN = 64;
     DBG_L7_LB = 65;
     DBG_SKIP_POLICY = 66;
+    DBG_LB6_LOOPBACK_SNAT = 67;
+    DBG_LB6_LOOPBACK_SNAT_REV = 68;
```
Comment (pchaigno) [inline api/v1/flow/flow.proto:952]: This list needs to be in the same order as the list in `datapath_debug.go`, otherwise the constants won't get assigned the same values.

Comment (saiaunghlyanhtet) [reply api/v1/flow/flow.proto:952]: I am sorry that I was rushing. Fixed it.

Comment (pchaigno) [reply api/v1/flow/flow.proto:952]: No worries. Thanks for the quick replies :)

**Review by jrife — APPROVED** [review]

**Review by ti-mo — APPROVED** [review]
Thanks!

File: bpf/lib/dbg.h [hunk 33]
```diff
@@ -35,6 +35,8 @@ enum {
 	DBG_LB6_LOOKUP_BACKEND_FAIL,
 	DBG_LB6_REVERSE_NAT_LOOKUP,
 	DBG_LB6_REVERSE_NAT,
+	DBG_LB6_LOOPBACK_SNAT,
+	DBG_LB6_LOOPBACK_SNAT_REV,
```
Comment (gandro) [inline bpf/lib/dbg.h]: This is a bit of an unfortunate situation - but because we pull in these definitions in Hubble, they are considered stable. You have to move them to the end of this enum, to avoid re-numbering the existing enum variants. Otherwise older Hubble clients will now report the wrong trace type when decoding debug events (due to the changed integer-to-name mapping).

Long-term we probably have to find another solution, since I'm not sure it was a good idea to have this internal enum be part of the stable API. But I think that's something we can address separately later, independent of this PR. For this PR, I think it's easiest if we add this to the bottom of this enum (and accordingly for the Go and Hubble definitions).

**Review by gandro — CHANGES_REQUESTED** [review]
Thanks for the PR. Unfortunately I think there are some minor changes needed

File: bpf/lib/dbg.h (hunk 33 above)
Comment (pchaigno) [reply bpf/lib/dbg.h]: While at it, could you move the BPF definitions of the these two constants to the first commit, with the Go side? I think that will be a bit less confusing when reviewing :)

Comment (saiaunghlyanhtet) [reply bpf/lib/dbg.h]: @gandro Moved to the end of the enum.
@pchaigno Moved the dbg.h to the first commit.

**Review by gandro — APPROVED** [review]
Thanks!

**Comment by julianwiedmann** [comment]
great stuff @saiaunghlyanhtet, glad to see this finally land! :rocket:

I added a `release-note` stanza to the PR description, so that this shows up properly in the releases notes for `v1.19`. Feel free to polish the wording as you see fit :).

**Comment by pchaigno** [comment]
Congrats on getting this in @saiaunghlyanhtet! Your swift iterations on reviews made a big difference, especially for the details at the end :slightly_smiling_face: Don't hesitate to reach out if you need help on anything else!
