### PR TITLE
cilium-cli: re-fix GITHUB_WORKFLOW_REF parsing

### LINKED ISSUE #37705: CI: Cilium Cluster Mesh upgrade (ci-clustermesh): `(*ConnectivityTest).LogOwners` panic
## CI failure

test output:
```
📋 Test Report [cilium-test-1]
❌ 1/9 tests failed (1/187 actions), 105 tests skipped, 2 scenarios skipped:
Test [check-log-errors]:
  ❌ check-log-errors/no-errors-in-logs/kind-cluster2/kube-system/cilium-p8hhp (cilium-agent)
panic: runtime error: slice bounds out of range [2:1]

goroutine 1 [running]:
github.com/cilium/cilium/cilium-cli/connectivity/check.(*ConnectivityTest).LogOwners(0xc0008bf208, {0x7fed317c3a80, 0xc001270000})
	/go/src/github.com/cilium/cilium/cilium-cli/connectivity/check/logging.go:133 +0x67b
github.com/cilium/cilium/cilium-cli/connectivity/check.(*ConnectivityTest).report(0xc0008bf208)
	/go/src/github.com/cilium/cilium/cilium-cli/connectivity/check/context.go:514 +0xdb9
github.com/cilium/cilium/cilium-cli/connectivity/check.(*ConnectivityTest).PrintReport(0xc0010c27c8?, {0x62060b8?, 0xc000cf2200?})
	/go/src/github.com/cilium/cilium/cilium-cli/connectivity/check/context.go:469 +0x11b
github.com/cilium/cilium/cilium-cli/connectivity.Run({0x62060b8, 0xc000cf2200}, {0xc00012a340, 0x1, 0x1}, {0x7fed3182f7c0, 0x9583d20})
	/go/src/github.com/cilium/cilium/cilium-cli/connectivity/suite.go:46 +0x4ce
github.com/cilium/cilium/cilium-cli/cli.newCmdConnectivityTest.RunE.func1(0xc00035e908, {0x4502695?, 0x4?, 0x4502551?})
	/go/src/github.com/cilium/cilium/cilium-cli/cli/connectivity.go:106 +0x7b2
github.com/spf13/cobra.(*Command).execute(0xc00035e908, {0xc000791380, 0x1a, 0x1a})
	/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:985 +0xaaa
github.com/spf13/cobra.(*Command).ExecuteC(0xc000b8d508)
	/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0x62161f0?)
	/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:1041 +0x13
main.main()
	/go/src/github.com/cilium/cilium/cilium-cli/cmd/cilium/main.go:22 +0xc5
``` 

https://github.com/cilium/cilium/actions/runs/13386077184/job/37383087410

### PR DESCRIPTION
**Pull request by kaworu**
af9ac194453338217af6bde1b52dc81e0aad93fd introduced an issue where the cilium-cli connectivity check could panic when `GITHUB_WORKFLOW_REF` was not set as expected.

This commit changes the `GITHUB_WORKFLOW_REF` parsing logic using a regexp capture to extract the workflow name from `GITHUB_WORKFLOW_REF` and check whether the match was successful.

Fix https://github.com/cilium/cilium/issues/37705

### CODE REVIEW

File: cilium-cli/connectivity/check/logging.go [hunk 1]
```diff
@@ -126,11 +128,15 @@ func (ct *ConnectivityTest) LogOwners(scenario ownedScenario) {
...
-	ghWorkflow := os.Getenv("GITHUB_WORKFLOW_REF")
-	ghWorkflow, _, _ = strings.Cut(ghWorkflow, "@")
-	segments := strings.Split(ghWorkflow, "/")
-	ghWorkflow = strings.Join(segments[2:], "/")
+	ghWorkflowRef := os.Getenv("GITHUB_WORKFLOW_REF")
+	matches := ghWorkflowRegexp.FindStringSubmatch(ghWorkflowRef)
+	// here matches should either be nil (no match) or a slice with two values:
+	// the full match and the capture.
+	if len(matches) == 2 {
+		ghWorkflow = matches[1]
```
Comment (joestringer) [inline cilium-cli/connectivity/check/logging.go:138]: Naive question, how do you tell that the capture omits the initial `org/repo/` match?

**Review by joestringer — APPROVED** [review]
Thanks for the fix. Works as expected.

File: cilium-cli/connectivity/check/logging.go (hunk 1 above)
Comment (kaworu) [reply cilium-cli/connectivity/check/logging.go:138]: in `^(?:.+?)/(?:.+?)/(.+?)@.*$`:
* `^` start of line anchor
* `(?:.+?)/(?:.+?)/` is the `org/repo/` part and it is using the non-capturing group syntax `(?:...)`
* `(.+?)` is a non-eager group, so we'll stop before the first `@`. this is what we're interested in, i.e. `ghWorkflow`, so it's a capture group.
* `@.*$` matches the rest of the line, at least `cilium/cilium/.github/workflows/conformance-kind-proxy-embedded.yaml@` will still match (i.e. nothing after `@`) but I think it's ok.

So when we have a match, `matches[0]` will always be the full `os.Getenv("GITHUB_WORKFLOW_REF")` because our regexp is anchored both at start and EOL, and `matches[1]` will be our only regexp capture group. Something like `foo/bar/mou/ha/ha/ha@` will match and result in `ghWorkflow="mou/ha/ha/ha"`, see https://regex101.com/r/I2fYmk/1.

**Review by viktor-kurchenko — APPROVED** [review]

File: cilium-cli/connectivity/check/logging.go (hunk 1 above)
Comment (joestringer) [reply cilium-cli/connectivity/check/logging.go:138]: Looks like the answer lies in the use of `(?:...)` syntax, which matches but does not capture that submatch :+1:

Comment (joestringer) [reply cilium-cli/connectivity/check/logging.go:138]: Ah thank you for the detailed explanation!

**Comment by joestringer** [comment]
We're even lucky enough to get a random failure in ci-clustermesh that demonstrates that this fixes the issue that was reported, as in the case where GITHUB_WORKFLOW_REF is unspecified it just ignores the workflow attribution rather than crashing: https://github.com/cilium/cilium/actions/runs/13392927898/job/37404692001#step:54:463 :tada:

**Comment by kaworu** [comment]
Hit https://github.com/cilium/cilium/issues/37718
