### PR TITLE
metrics: fix ts_events API timestamp and scope label cardinality

### LINKED ISSUE #20967: High label cardinality in `cilium_event_ts` metric
Screen Shot 2022-08-17 at 8 54 16 PM

The problem is in this code since we are using `req.URL.Path` to be defined as the "scope". 
https://github.com/cilium/cilium/blob/e4d68f84a7c957bc9c6b6fea3bfda3151f830629/pkg/metrics/middleware.go#L56-L58

The "scope" should be an enum of a handful of different values. These are some good usages of this collector's metric here:
https://github.com/cilium/cilium/blob/c7b14878ce56b2b841f949d0f888b56864a611dc/pkg/k8s/watchers/watcher.go#L923
https://github.com/cilium/cilium/blob/a0fa1a8f74aebc430c48efc981b35a8f6e581fee/operator/watchers/k8s_service_sync.go#L56-L58
https://github.com/cilium/cilium/blob/a0fa1a8f74aebc430c48efc981b35a8f6e581fee/operator/cmd/ccnp_event.go#L26-L28

This is a regression introduced in https://github.com/cilium/cilium/commit/41d77e168f6bd6b5045775a5c043a5d7457b4e9c

### PR DESCRIPTION
**Pull request by tommyp1ckles**
Regression caused ts_events gauge to be scoped with url path including url parameter causing high cardinality metrics.
This fixes that to follow the same scoping as the API metrics middleware histogram metrics.

As well fixes API type ts_events metrics only ever being reported as 0 due to not setting the metric timestamp upon emit.

Also adds unit test for metrics middleware.

Fixes: #20967

Signed-off-by: Tom Hadlaw <tom.hadlaw@isovalent.com>

```release-note
metrics: fix ts_events API timestamp only emitting zero and unbounded scope label cardinality issue. 
```

### CODE REVIEW

File: pkg/metrics/middleware.go [hunk 1]
```diff
@@ -53,15 +53,17 @@ func getShortPath(s string) string {
...
 		path := getShortPath(req.URL.Path)
-		took := float64(duration.End(true).Total().Seconds())
-		m.Histogram.WithLabelValues(path, req.Method, strconv.Itoa(rw.code)).Observe(took)
+		// Only emit metrics on non-404 results, avoids metrics
+		// on arbitrary non existent paths.
+		if rw.code != http.StatusNotFound {
+			m.TSGauge.WithLabelValues(LabelEventSourceAPI, path, req.Method).Set(float64(duration.StartTime().Unix()))
+			took := float64(duration.End(true).Total().Seconds())
+			m.Histogram.WithLabelValues(path, req.Method, strconv.Itoa(rw.code)).Observe(took)
+		}
```
Comment (aanm) [inline pkg/metrics/middleware.go]: @tommyp1ckles I might be changing my mind on this because a) the API is only accessible by a privileged client and b) there might be other http response codes that can be caused by arbitrary non existing paths, like 5xx for example. So the arbitrary non existent paths might not be a problem that we need to solve here.

**Review by aanm — CHANGES_REQUESTED** [review]

File: pkg/metrics/middleware.go (hunk 1 above)
Comment (tommyp1ckles) [reply pkg/metrics/middleware.go]: Yeah makes sense. I'll make the change.

Comment (tommyp1ckles) [reply pkg/metrics/middleware.go]: fixed

**Comment by tommyp1ckles** [comment]
Keeping the spanstat test fix as separate commit despite reverting pkg/spanstat changes since its worth fixing

**Review by aanm — APPROVED** [review]

**Review by sayboras — APPROVED** [review]
LGTM :100:

**Comment by aditighag** [comment]
@tommyp1ckles In future, please add a note when you added a ready-to-merge label without running the full e2e tests suite.
