### PR TITLE
Prevent CiliumEndpoint removal by non-owning agent

### LINKED ISSUE #17047: CiliumEndpoint missing for a pod
cilium version: 1.9.4
kubelet: 1.20

After upgrade of a cluster, we notice ciliumendpoint is missing for a running pod. We dig into it and think it may be a bug in the way cilium manages cilium endpoint. Here is the timeline:

1. An existing statefulset pod alertmanager-0 running on a node
2. cluster is going with an upgrade. both cilium-agent and alertmanager-0 are getting upgraded
3. kubelet fails to remove the old container for alertmanager-0 because cilium-agent is being rebooted at the same time (so cni is missing)
```
Aug 03 04:08:11 bmut-dozrr9-0803-024754-871f3-acp2 kubelet[48398]: E0803 04:08:11.853703   48398 pod_workers.go:191] Error syncing pod 3f7c5201-edc9-4b83-a6a2-470289ae89ac ("alertmanager-0_kube-system(3f7c5201-edc9-4b83-a6a2-470289ae89ac)"), skipping: error killing pod: failed to "KillPodSandbox" for "3f7c5201-edc9-4b83-a6a2-470289ae89ac" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to destroy network for sandbox \"a580c1ab31c3b1c66cbc5d542f9eb340bd0494449c2d832c1bda6e27636ed949\": failed to find plugin \"cilium-cni\" in path [/opt/cni/bin]"
```

4. cilium-agent is rebooted and starts to restore existing endpoints
```
2021-08-03T04:08:34.378283278Z level=info msg="New endpoint" containerID=a580c1ab31 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=277 identity=60609 ipv4=192.168.1.165 ipv6= k8sPodName=kube-system/alertmanager-0 subsys=endpoint
```
5. Almost at the same time, kubelet creates a new container for the pod:
```
2021-08-03T04:08:34.737428463Z level=info msg="Create endpoint request" addressing="&{192.168.1.85 78bda739-f410-11eb-92f1-42010a800063  }" containerID=f4a2e88f66aabf348196605c0b4d430bf6f3b4f660224f984bd16053b07b6b23 datapathConfiguration="<nil>" interface=lxc368fadda4150 k8sPodName=kube-system/alertmanager-0 labels="[]" subsys=daemon sync-build=true
```

Note that the container ID is not the same, so it's kubelet creating a new container for the same pod

6. after ~ 30seconds, kubelet tries to remove the old container of the pod
```
2021-08-03T04:09:00.533694827Z level=info msg="Delete endpoint request" id="container-id:a580c1ab31c3b1c66cbc5d542f9eb340bd0494449c2d832c1bda6e27636ed949" subsys=daemon
2021-08-03T04:09:00.534015683Z level=info msg="Releasing key" key="[k8s:app=alertmanager k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=alertmanager k8s:io.kubernetes.pod.namespace=kube-system k8s:statefulset.kubernetes.io/pod-name=alertmanager-0]" subsys=allocator
2021-08-03T04:09:00.539698529Z level=info msg="Removed endpoint" containerID=a580c1ab31 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=277 identity=60609 ipv4=192.168.1.165 ipv6= k8sPodName=kube-system/alertmanager-0 subsys=endpoint
```

Note the container id in the request is the old one.

7. cilium-agent removes the ciliumendpoint but still the pod is running.

After all of these steps, we end up with alertmanager-0 running fine but doesn't have a cilium endpoint. I guess the issue is that when we process delete endpoint rpc request, we didn't check the container id matches the one in the cilium_endpoint so if kubelet is removing an stale container, ciliumendpoint for a pod is removed. Shall we add this check?

### PR DESCRIPTION
**Pull request by timoreimann**
CEPs are creating as well as updated based on informer store data local to an agent's node but (necessarily) deleted globally from the API server. This can currently lead to situations where an agent that does not own a CEP deletes an unrelated CEP.

Avoid this problem by having agents maintain the CEP UID and using it as a precondition when deleting CEPs. This guarantees that only the owning agents can delete "their" CEPs.

Fixes #17047

**Note:** I am not yet sure if/how to best extend any automated testing: most of the files I updated seem to have many tests, so I'm a bit uncertain if initial tests need to be built out first or if coverage is maintained through other flavors of tests. I know Cilium has e2e tests as well, but I couldn't spot the corresponding tests for the change in question either. Appreciate any pointers in this regard.

See also the related Slack convo [here](https://cilium.slack.com/archives/C53TG4J4R/p1644882661331769).

/cc @aanm 

```release-note
Fix issue where StatefulSet pod restarts could trigger persistent connectivity issues for the pods due to overzealous CiliumEndpoint resource removal by cilium-agent instances
```

### CODE REVIEW

File: pkg/k8s/slim/k8s/api/core/v1/types.go [hunk 1]
```diff
@@ -252,6 +252,11 @@ type PodSpec struct {
 	// More info: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
 	// +optional
 	ServiceAccountName string `json:"serviceAccountName,omitempty" protobuf:"bytes,8,opt,name=serviceAccountName"`
+	// NodeName is a request to schedule this pod onto a specific node. If it is non-empty,
+	// the scheduler simply schedules this pod onto that node, assuming that it fits resource
+	// requirements.
+	// +optional
+	NodeName string `json:"nodeName,omitempty" protobuf:"bytes,10,opt,name=nodeName"`
```
Comment (christarazi) [inline pkg/k8s/slim/k8s/api/core/v1/types.go:259]: There's no need for this field actually because we know that any Pod object that enters the K8s watchers is a local pod due to https://github.com/cilium/cilium/blob/82c742f2e9fb65fb3fc392c7dcb3b4e22b69c650/pkg/k8s/watchers/pod.go#L122.

File: pkg/k8s/watchers/endpointsynchronizer.go [hunk 2]
```diff
@@ -281,6 +297,21 @@ func (epSync *EndpointSynchronizer) RunK8sCiliumEndpointSync(e *endpoint.Endpoin
 		})
 }
 
+// updateCEPUIDIfNeeded updates the endpoint's CEP UID from the local CEP if the
+// node name from the pod matches the agent's node name and the CEP UID is
+// different (i.e., has never been set on the endpoint or has changed).
+func updateCEPUIDIfNeeded(scopedLog *logrus.Entry, pod *slim_corev1.Pod, e *endpoint.Endpoint, localCEP *cilium_v2.CiliumEndpoint) {
```
Comment (christarazi) [inline pkg/k8s/watchers/endpointsynchronizer.go]: Do we need to think about whether we need to lock the `Endpoint` object? We are unconditionally writing into it.

File: pkg/k8s/watchers/endpointsynchronizer.go [hunk 3]
```diff
@@ -323,8 +354,31 @@ func deleteCEP(ctx context.Context, scopedLog *logrus.Entry, ciliumClient v2.Cil
...
+	// scheduled onto a different node while the agent on the original node was
+	// down, which would cause the CEP to be deleted once the original agent came
+	// back up. (This holds for StatefulSets in particular that come with stable
+	// pod identifiers and thus do not guard against such accidental deletes
+	// through unique pod names.) Storing the CEP UID at CEP create/fetch time
+	// and using it as a precondition for deletion ensures that agents may only
+	// delete CEPs they own.
+	// It is possible for the CEP UID to not be populated when an agent tries to
+	// clean up a CEP. In that case, skip deletion and rely on cilium operator
+	// garbage collection to clean up eventually.
```
Comment (christarazi) [inline pkg/k8s/watchers/endpointsynchronizer.go:367]: This makes sense to me. I took a look at our CEP GC code and it's not quite as "observable" as I'd like if we now more explicitly rely on the GC to get the cluster into a good state. Specifically, we only have a debug level log, which I'd argue should stay that way but we need to augment it.

Could you add a new commit which exposes a metric for how many times we GC a CEP? The code should be around here: https://github.com/cilium/cilium/blob/d783aca9aa277397d60361de0af96da5a4bcf4f0/operator/k8s_cep_gc.go#L149

File: pkg/k8s/watchers/endpointsynchronizer.go [hunk 4]
```diff
@@ -176,12 +184,14 @@ func (epSync *EndpointSynchronizer) RunK8sCiliumEndpointSync(e *endpoint.Endpoin
 							return err
 						}
 
+						scopedLog.WithField("cep_uid", localCEP.UID).Debug("storing CEP UID after create")
```
Comment (christarazi) [inline pkg/k8s/watchers/endpointsynchronizer.go]: Let's define `cepGUID` (nit on underscores just to conform to existing camel-case) as a logfield inside the logfields package and use it throughout. It seems useful enough now

File: pkg/k8s/watchers/endpointsynchronizer.go [hunk 5]
```diff
@@ -281,6 +297,21 @@ func (epSync *EndpointSynchronizer) RunK8sCiliumEndpointSync(e *endpoint.Endpoin
...
+// updateCEPUIDIfNeeded updates the endpoint's CEP UID from the local CEP if the
+// node name from the pod matches the agent's node name and the CEP UID is
+// different (i.e., has never been set on the endpoint or has changed).
+func updateCEPUIDIfNeeded(scopedLog *logrus.Entry, pod *slim_corev1.Pod, e *endpoint.Endpoint, localCEP *cilium_v2.CiliumEndpoint) {
+	if pod != nil && pod.Spec.NodeName == types.GetName() && e.CiliumEndpointUID != localCEP.UID {
+		scopedLog.WithFields(logrus.Fields{
+			"agent_node_name": types.GetName(),
+			"pod_node_name":   pod.Spec.NodeName,
+			"old_cep_uid":     e.CiliumEndpointUID,
+			"new_cep_uid":     localCEP.UID,
```
Comment (christarazi) [inline pkg/k8s/watchers/endpointsynchronizer.go]:
```
			logfields.Node: types.GetName(),
			"pod_node_name":   pod.Spec.NodeName,  // <- no need as per above comment
			"old"+logfields.CEPGUID:     e.CiliumEndpointUID,
			logfield.CEPGUID:     localCEP.UID,
```

**Review by christarazi — CHANGES_REQUESTED** [review]
Thanks for the PR! :rocket: 

A couple of comments below. Also, please squash the second commit if it's meant to change the same files as the first commit.

File: pkg/k8s/slim/k8s/api/core/v1/types.go (hunk 1 above)
Comment (timoreimann) [reply pkg/k8s/slim/k8s/api/core/v1/types.go:259]: The addition was based on a suggestion from @aanm in a discussion we had on Slack (with the relevant portion starting around [here](https://cilium.slack.com/archives/C53TG4J4R/p1645045322460259?thread_ts=1644882661.331769&cid=C53TG4J4R)). The idea was to play it safe since some code paths to get the pod seem to rely on [`GetCachedPod()`](https://github.com/cilium/cilium/blob/fcbeb6402b2ce63be373e27a216c4b6806188def/pkg/k8s/watchers/pod.go#L852), which comes with a comment saying that a `K8sEventHandover` determines whether the backing store is populated from local or cluster-wide pods. So the concern was that we could be seeing cluster-wide pods if the Cilium configuration was set accordingly.

With this additional context, can you confirm that omitting the `NodeName` addition (and consumption) is still the right thing to do?

File: pkg/k8s/watchers/endpointsynchronizer.go (hunk 2 above)
Comment (timoreimann) [reply pkg/k8s/watchers/endpointsynchronizer.go]: I found it hard enough to judge if we needed to synchronize access or not, so I went ahead and added a getter/setter pair.

File: pkg/k8s/watchers/endpointsynchronizer.go (hunk 3 above)
Comment (timoreimann) [reply pkg/k8s/watchers/endpointsynchronizer.go:367]: Took a stab at this. Let me know what you think.

File: pkg/k8s/watchers/endpointsynchronizer.go (hunk 5 above)
Comment (timoreimann) [reply pkg/k8s/watchers/endpointsynchronizer.go]: Done. Left the pod's node name in for now until we have resolved the other conversation.

**Comment by timoreimann** [comment]
>Please squash the second commit if it's meant to change the same files as the first commit.

Squashed. I left the new changes as separate commits for now to ease reviewing (as good contributor citizens should do :) ). Happy to squash all but the main and metrics commits once we complete the review (or earlier if you prefer).

**Comment by timoreimann** [comment]
Thanks for the initial review @christarazi. I updated the PR, it should be ready for another round.

File: pkg/k8s/watchers/endpointsynchronizer.go (hunk 2 above)
Comment (christarazi) [reply pkg/k8s/watchers/endpointsynchronizer.go]: Yes, it can be hard to ascertain just from reading the code. If we take a step back and think about how this code is executing by following the callers / callees of the relevant functions, we can notice that it's called from async points (driven by K8s events) which is enough to tell us that it's possible to have a race, and hence need a lock. Thanks for adding it.

File: operator/k8s_cep_gc.go [hunk 6]
```diff
@@ -58,17 +60,38 @@ func enableCiliumEndpointSyncGC(once bool) {
 	}
 	<-k8sCiliumNodesCacheSynced
 
+	cegc := CiliumEndpointGC{}
+	if operatorOption.Config.EnableMetrics {
+		cegc.objectsMetric = metrics.EndpointGCObjects
+	}
```
Comment (christarazi) [inline operator/k8s_cep_gc.go]: What's the need to do this?

File: pkg/k8s/slim/k8s/api/core/v1/types.go (hunk 1 above)
Comment (christarazi) [reply pkg/k8s/slim/k8s/api/core/v1/types.go:259]: As discussed in Slack, we'll keep the nodeName addition for a future PR to fix an endpoint restoration bug (sep. from this issue). That issue is tracked in https://github.com/cilium/cilium/issues/18923.

File: operator/k8s_cep_gc.go (hunk 6 above)
Comment (timoreimann) [reply operator/k8s_cep_gc.go]: It is meant to encapsulate the logic that determines if metrics should be tracked or not based on the `EnableMetrics` flag: if the flag is enabled, `cegc.objectsMetric` will be populated and otherwise left nil. The convenience methods defined on the struct check `cegc.objectsMetric` before recording a successful/failure metric event.

The larger intention of mine was to not sprinkle `if` checks for whether metrics are enabled across the core business logic and instead scope it to the struct. This should also make it easier to test the logic as it does not rely on globals (though I haven't added tests yet).

Let me know if you think there's a different/better way to do it.

**Comment by timoreimann** [comment]
Split out the node name addition into a separate commit and removed its usage in this PR.

Also squashed all commits related to the core logic of this PR and left metrics as well as node name addition as separate ones.

File: operator/k8s_cep_gc.go (hunk 6 above)
Comment (christarazi) [reply operator/k8s_cep_gc.go]: Ah I see, I think this can be simpler. I don't think we need a struct, but rather just change the helper functions to do the following

```go
func (cegc *CiliumEndpointGC) successfulObjectGC() {
	if metricsEnabled {
		metrics.EndpointGCObjects.WithLabelValues(metrics.LabelValueOutcomeSuccess).Inc()
	}
}
```

This does what you were intending, right? I don't think it's a deal breaker to have the if-statements checking the option, so we might as well simplify and remove the struct.

**Comment by christarazi** [comment]
Could you add a reference to like `GH-18923` to the last commit?

File: operator/k8s_cep_gc.go (hunk 6 above)
Comment (timoreimann) [reply operator/k8s_cep_gc.go]: Okay, done.

**Comment by timoreimann** [comment]
@christarazi left a reference to the endpoint restore Github issue in the corresponding comment, and updated the PR to address your GC comment.

**Review by christarazi — APPROVED** [review]
Thanks!

**Review by nebril — APPROVED** [review]

**Comment by joestringer** [comment]
I've just kicked of the test job, so we can gather some info from existing testsuites. We can triage the results to see whether there is likely to be anything related to this PR or if any failures correlate with existing issues reported with label `area/ci`.

As for reviews, there is only @cilium/cli remaining but that's for a trivial log field update so this should be good to merge as long as CI doesn't flag any relevant test failures.

**Comment by joestringer** [comment]
Triaging the failures here since I noticed one of them was similar to something I observed:

[gke-stable job failed](https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/7757/testReport/junit/Suite-k8s-1/20/K8sServicesTest_Checks_E_W_loadbalancing__ClusterIP__NodePort_from_inside_cluster__etc__Checks_in_cluster_KPR_Tests_NodePort/) several of the `K8sServicesTest Checks E/W loadbalancing` tests. The failures are that before the test even starts, one of the pods required for the test did not become ready:

```
	 default             testds-9kfcn                                             1/2     Running   0          5m51s   10.20.2.1     gke-cilium-ci-13-cilium-ci-13-a2a46331-lgnx   <none>           <none>
```

There are artifacts at the top of the tree to try to dig a little further, but it's not obvious to me how this PR could be related. Looking at the artifacts for that test, the 9kfcn ciliumendpoint is in k8s. There's some possibility that this is just a one-off flake, or it's caused by churn in the master tree (where the tests are pulled from) vs. the base version of this branch. If the latter is the cause, a rebase should address the issue.

The [runtime job failed](https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/1440/) also with a timeout issue in the privileged unit tests. I saw this also in my own PR, so I'll create a new CI flake issue for this. I presume it affects the master branch.

**Comment by joestringer** [comment]
Filed #19124 for the runtime test failure. Doesn't seem related at all to this PR. The rest of the CI jobs passed, reviews are in, good to merge.

**Comment by joestringer** [comment]
@timoreimann [reported on Slack](https://cilium.slack.com/archives/C53TG4J4R/p1646946953366239?thread_ts=1644882661.331769&cid=C53TG4J4R) that a backport of this PR has been running in production for hundreds of clusters for the past couple of weeks, so we have pretty high confidence that this will solve a real issue for users on v1.9.x and later, and is unlikely to trigger regressions. Nominated for backports to all supported branches.

I also updated the release note in the PR description to be a bit clearer for users to understand the implications.
