### PR TITLE
daemon: fix issue where IPAM options in custom CNI confs was ignored

### LINKED ISSUE #26731: Custom IPAM section in CNI config is ignored
@joamaki stumbled upon the fact that NetConf isn't set anymore in the daemon: https://github.com/cilium/cilium/blob/main/daemon/cmd/daemon.go#L405. This is passed down to NodeDiscovery which then pulls some IPAM related things out of it.

This breaks the ability to configure IPAM parameters such as e.g. the ones used for ENI [documented here](https://docs.cilium.io/en/stable/network/concepts/ipam/eni/#custom-eni-configuration). Since this is a critical ability for many ENI users, this is a release-blocking bug that we need to address. The IPAM parameters need to be present in the CiliumNode CRD when it is created, otherwise the operator will take meaningful decisions (e.g. attaching network interface from the wrong subnet) based on absent configuration.

In addition, we should probably also add some CI testing around this, for example by using custom subnets in the CI-EKS workflow.

### PR DESCRIPTION
**Pull request by squeed**
As part of a CNI refactor, a bug was introduced where node-specific IPAM overrides were no longer being loaded. Specifically, the parsed network configuration wasn't properly being passed down to the NodeDiscovery manager.

Fixes: #26731
Fixes: 1254bf403f

### CODE REVIEW

**Comment by squeed** [comment]
tentatively setting this as release-note misc, since we will (hopefully) ship no releases with this label!

**Review by joamaki — APPROVED** [review]

File: daemon/cmd/cni/config.go [hunk 1]
```diff
@@ -67,6 +67,22 @@ func (c *cniConfigManager) GetChainingMode() string {
 	return c.config.CNIChainingMode
 }
 
+// GetCustomNetConf returns the parsed custom CNI configuration, if provided
+// (In other words, the value to --read-cni-conf).
+// Otherwise, returns nil.
+func (c *cniConfigManager) GetCustomNetConf() *cnitypes.NetConf {
```
Comment (gentoo-root) [inline daemon/cmd/cni/config.go:65]: GetMTU can reuse this new function, the code is almost the same.

File: daemon/cmd/daemon.go [hunk 2]
```diff
@@ -414,11 +407,6 @@ func newDaemon(ctx context.Context, cleaner *daemonCleanup, params *daemonParams
 		return nil, nil, fmt.Errorf("CRD Identity allocation mode requires k8s to be configured")
 	}
 
-	if mtu := params.CNIConfigManager.GetMTU(); mtu > 0 {
```
Comment (gentoo-root) [inline daemon/cmd/daemon.go:417]: If GetMTU returned 0, configuredMTU used to be set to option.Config.MTU, but not anymore after this patch. Is it intentional?

Comment (squeed) [reply daemon/cmd/daemon.go:417]: no, that's a bug. Oops

Comment (squeed) [reply daemon/cmd/daemon.go:417]: Trying to be too clever, I'll back out the MTU changes.

**Comment by squeed** [comment]
Thanks for the review; fixed.

**Review by gentoo-root — APPROVED** [review]

**Comment by squeed** [comment]
All green, merging
