### PR TITLE
datapath/loader: always set all args to bpf/init.sh

### LINKED ISSUE #10228: bpf: command execution failed for bpf/init.sh
Seen in `cilium.log` on a failed CI test run for #10204, looks unrelated to that PR:

```
Feb 17 22:37:01 runtime cilium-agent[15047]: level=error msg="Error while initializing daemon" error="Command execution failed for [/var/lib/cilium/bpf/init.sh /var/lib/cilium/bpf /var/run/cilium/state 10.15.185.178 fc00::10ca:1 vxlan    1500 false false  false false /var/run/cilium/cgroupv2 /sys/fs/bpf ]: context canceled" subsys=daemon
Feb 17 22:37:01 runtime cilium-agent[15047]: level=fatal msg="Error while creating daemon" error="Command execution failed for [/var/lib/cilium/bpf/init.sh /var/lib/cilium/bpf /var/run/cilium/state 10.15.185.178 fc00::10ca:1 vxlan    1500 false false  false false /var/run/cilium/cgroupv2 /sys/fs/bpf ]: context canceled" subsys=daemon
```

when running said command line locally I get

```
$ sudo /var/lib/cilium/bpf/init.sh /var/lib/cilium/bpf /var/run/cilium/state 10.15.185.178 fc00::10ca:1 vxlan 1500 false false false false /var/run/cilium/cgroupv2 /sys/fs/bpf
[...]
+ ip link set cilium_host mtu false
Error: argument "false" is wrong: Invalid "mtu" value
```

It seems like the number of arguments passed to `bpf/init.sh` is not 17 (`pkg/datapath/loader.initArgMax`) in all cases, while the script assumes them to always be:

https://github.com/cilium/cilium/blob/b6f2e75d5b98bc200817da41f96c6522866cdd4a/bpf/init.sh#L17-L34

It looks like the unused arguments are passed as empty string rather than some placeholder value.

/cc @cilium/bpf @cilium/bpf-loader

### PR DESCRIPTION
**Pull request by tklauser**
Passing empty strings to `bpf/init.sh` will lead to arguments being
misinterpreted as their index is no longer correct. This can e.g. lead
to the MTU not being set in `vxlan` mode as seen in #10228. Thus, always
set all 17 (current value `initArgMax`) arguments top non-empty values.
Use `<nil>` as a default empty value if the arg is not used by
`bpf/init.sh`.

Fixes #10228

Signed-off-by: Tobias Klauser <tklauser@distanz.ch>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10230)

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-me-please

**Review by pchaigno — APPROVED** [review]

**Comment by tklauser** [comment]
test-me-please

File: pkg/datapath/loader/base.go [hunk 1]
```diff
@@ -259,6 +267,12 @@ func (l *Loader) Reinitialize(ctx context.Context, o datapath.BaseProgramOwner,
 		}
 	}
 
+	for i, arg := range args {
+		if arg == "" {
+			log.Warningf("empty argument passed to bpf/init.sh at position %d", i)
```
Comment (aanm) [inline pkg/datapath/loader/base.go:272]: The user won't be able to perform any action if this happen. Shouldn't we return an error instead? On the other hand, I assume this should only happen because of some bug on our side? Perhaps we can leave the warning but add it to this list so we can detect it in our CI: https://github.com/cilium/cilium/blob/25ee77eb9c3e524ff6001d79cd2b566e30d2d124/test/helpers/cons.go#L256-L265

**Review by aanm — CHANGES_REQUESTED** [review]

File: pkg/datapath/loader/base.go (hunk 1 above)
Comment (tklauser) [reply pkg/datapath/loader/base.go:272]: Good point. This should only show up in case of a bug on our side. Maybe we should just `log.Fatal` instead?

Comment (pchaigno) [reply pkg/datapath/loader/base.go:272]: If only the last arguments are empty, there won't be any user impact, right? In that case, if we return an error, we will block an otherwise fine setup.

Comment (tklauser) [reply pkg/datapath/loader/base.go:272]: True. So I'll leave the `log.Warning` and add them to `badLogMessages` like @aam suggested.

**Comment by tklauser** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by tklauser** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by tklauser** [comment]
test-me-please

**Review by vadorovsky — APPROVED** [review]

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-me-please
