### PR TITLE
fix to forbid IPAM ENI with TUNNEL routing and segfault with also IPSec

### LINKED ISSUE #15883: cilium: encryption, subnet IPSec mode configuration may segfault on init
If not all of our preconditions are met, e.g. IP allocation fails or IP lookup fails its possible for enableSubnetIPSec,

```
func (n *linuxNodeHandler) enableSubnetIPsec(v4CIDR, v6CIDR []*net.IPNet)
```

to segfault. For example in an EKS environment where I misconfigured node pools I got this,

```
level=debug msg="IPsec enable succeeded" local-ip=0.0.0.0/0 reason="CNI Out IPv4" remote-ip=192.168.0.0/16 spi=3 subsys=linux-datapath
level=error msg="IPsec enable failed" error="Link not found" local-ip=0.0.0.0/0 reason="getV4LinkLocalIP failed" remote-ip=192.168.0.0/16 spi=3 subsys=linux-datapath
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2009397]

goroutine 1 [running]:
github.com/cilium/cilium/pkg/datapath/linux/ipsec.UpsertIPsecEndpoint(0x0, 0xc000f9a0c0, 0xc000c8bb90, 0x299e187, 0x8, 0xc000c8bb01, 0x275f903, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/datapath/linux/ipsec/ipsec_linux.go:334 +0x37
github.com/cilium/cilium/pkg/datapath/linux.(*linuxNodeHandler).enableSubnetIPsec(0xc0009ae000, 0xc000baada0, 0x2, 0x2, 0x46308e8, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/datapath/linux/node.go:534 +0x2d4
github.com/cilium/cilium/pkg/datapath/linux.(*linuxNodeHandler).nodeUpdate(0xc0009ae000, 0x0, 0xc000c5a540, 0x1, 0x2, 0xc000baada0)
        /go/src/github.com/cilium/cilium/pkg/datapath/linux/node.go:922 +0x21b
github.com/cilium/cilium/pkg/datapath/linux.(*linuxNodeHandler).NodeConfigurationChanged(0xc0009ae000, 0x2329, 0x22aa, 0x22dc, 0x22f7, 0x100, 0x46308e8, 0x0, 0x0, 0x1000000000001, ...)
        /go/src/github.com/cilium/cilium/pkg/datapath/linux/node.go:1398 +0x487
```

The system wasn't going to come up anyways so it would have failed and crash looped regardless, but still issuing a splat because we don't handle errors nicely is not user friendly. Offending code here,

```
                        linkAddr, err := getV4LinkLocalIp()
                        if err != nil {
                                upsertIPsecLog(err, "getV4LinkLocalIP failed", ipsecIPv4Wildcard, cidr, spi)
                        }
                        spi, err := ipsec.UpsertIPsecEndpoint(linkAddr, ipsecIPv4Wildcard, cidr, ipsec.IPSecDirIn, zeroMark)
                        upsertIPsecLog(err, "CNI In IPv4", linkAddr, ipsecIPv4Wildcard, spi)
```
Notice we just ignore the error and try to upsert anyways with linkAddr == null. Clearly not going to work. Above was caused by user error but like noted above we should be a bit friendlier with our errors.

### PR DESCRIPTION
**Pull request by smagnani96**
This PR includes two commits to fix the segfault caused by the combination IPAM ENI and TUNNEL routing with IPSEC.
IPAM ENI is not expected to work with TUNNEL routing, but only with NATIVE/DIRECT, at least from my understanding.

The final result is as follows:
1. fixed indexing of empty slice -> no more segfault
2. prevent agent startup and return a fatal if IPAM ENI and TUNNEL routing are both enabled.

Let me know in case I missed something :smiley: 

Fix: #15883

```release-note
Fix parameter check to forbid IPAM ENI with TUNNEL routing, and prevent agent segfault when also IPSec is enabled.
```

### CODE REVIEW

File: daemon/cmd/daemon_main.go [hunk 1]
```diff
@@ -1420,6 +1420,10 @@ func initEnv(vp *viper.Viper) {
 		}
 	}
 
+	if option.Config.EnableIPSec && option.Config.TunnelingEnabled() && option.Config.IPAM == ipamOption.IPAMENI {
+		log.Fatalf("IPAM ENI with IPSEC require routingMode=%s (--routing-mode=%s)", option.RoutingModeNative, option.RoutingModeNative)
+	}
```
Comment (pchaigno) [inline daemon/cmd/daemon_main.go]: This isn't actually specific to IPsec. ENI IPAM mode doesn't make sense with tunneling routing mode, regardless of other features.

(You can read about those different modes in https://docs.cilium.io/en/stable/network/concepts/routing/#aws-eni-datapath. In particular, notice the pod IPs in ENI IPAM mode are directly routable on the AWS VPC and how the implementation via Linux rules & routes assumes traffic flows through the ENI devices and not some overlay.)

**Review by pchaigno — CHANGES_REQUESTED** [review]
First commit is perfect. Second commit needs a change :slightly_smiling_face:

**Comment by pchaigno** [comment]
Beware when you remove the pull request and issue templates. In this case, you should keep the `release-note` block and complete it because it's a bugfix. What you write in there will end up in release notes for the bugfix section, so be sure to clarify the user-visible impact (typically of the form `Fix bug that caused ... when ...`).

**Comment by smagnani96** [comment]
As follow-up for https://github.com/cilium/cilium/pull/34651#pullrequestreview-2276056672, after a brief discussion it seems that there's no strong reason to support overlay with IPAM ENI, at least at the moment. Running such a config allows pod-to-pod, node-to-node and node-to-world communications, while not supporting pod-to-world ones. Enabling IPSec would cause also pod-to-pod to be disrupted, and before the 1st commit of this PR it would also lead to segfault.

Waiting to gather more feedbacks before proceeding, does it make sense at this point to check and block this config (2nd commit)?

File: daemon/cmd/daemon_main.go (hunk 1 above)
Comment (smagnani96) [reply daemon/cmd/daemon_main.go]: As follow-up for https://github.com/cilium/cilium/pull/34651#pullrequestreview-2276056672, after a brief discussion it seems that there's no strong reason to support overlay with IPAM ENI, at least at the moment. Running such a config allows pod-to-pod, node-to-node and node-to-world communications, while not supporting pod-to-world ones. Enabling IPSec would cause also pod-to-pod to be disrupted, and before the 1st commit of this PR it would also lead to segfault.

Waiting to gather more feedbacks before proceeding, does it make sense at this point to check and block this config (2nd commit)?

**Review by pchaigno — APPROVED** [review]

**Review by ldelossa — APPROVED** [review]
Change looks good.
