### PR TITLE
distinguish between FIN and RST on datapath

### LINKED ISSUE #11742: Connection tracking issue in connections with a single RST.
## Bug report

**General Information**

- Cilium version (run `cilium version`)
```
Client: 1.7.3 952090308 2020-04-29T15:29:53-07:00 go version go1.13.10 linux/amd64
Daemon: 1.7.3 952090308 2020-04-29T15:29:53-07:00 go version go1.13.10 linux/amd64
```

- Kernel version (run `uname -a`)
```
# uname -a
Linux xyz 4.9.0-0.bpo.12-amd64 #1 SMP Debian 4.9.210-1~deb8u1 (2020-02-21) x86_64 x86_64 x86_64 GNU/Linux
```

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
```
Kubernetes
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.9", GitCommit:"e09f5c40b55c91f681a46ee17f9bc447eeacee57", GitTreeState:"clean", BuildDate:"2019-05-27T15:58:45Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

```

- Configuration
Cilium integration with flannel through CNI chaining. Using managed etcd as the kvstore. NodeAffinity is used to control on which nodes Cilium agents are scheduled.

**How to reproduce the issue**
These three cases are tested between two pods in Kubernetes on different nodes, one node has Cilium agent running on it and the other one doesn't have. These tests can be done using `nc(1)` or by crafting packets using [Scapy](https://scapy.net/).

1) [This is a working example, so you may want to jump to (2) or (3)] A TCP Connection was established properly between two pods, then it was terminated with a FIN. In this case everything works as expected.

The conn-track entry immediately after the connection was established: 
```
(1) TCP IN 172.16.42.108:33284 -> 172.16.106.7:7777 expires=705338 RxPackets=12 RxBytes=822 RxFlagsSeen=0x1b LastRxReport=705328 TxPackets=6 TxBytes=408 TxFlagsSeen=0x1b LastTxReport=705328 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=3
```
This CT entry is removed after a few seconds (>20s, which is our `ct-gc-interval`). 

2) The sender tries to open a TCP connection to port `7777` on the receiver. The receiver (where we're observing) didn't have the port open and sends a RST.

These are captured traces for (2):
```
2)
-> endpoint 973 flow 0x274d2956 identity 3->279988 state new ifindex veth9866e6c1 orig-ip 172.16.42.108: 172.16.42.108:52456 -> 172.16.106.7:7777 tcp SYN
-> stack flow 0x274d2956 identity 279988->3 state reply ifindex 0 orig-ip 0.0.0.0: 172.16.106.7:7777 -> 172.16.42.108:52456 tcp ACK, RST
```

This CT entry is created for (2):
```
(2) TCP IN 172.16.42.108:52456 -> 172.16.106.7:7777 expires=727187 RxPackets=2 RxBytes=148 RxFlagsSeen=0x02 LastRxReport=705587 TxPackets=1 TxBytes=54 TxFlagsSeen=0x14 LastTxReport=705587 Flags=0x0012 [ TxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=3
```
The record has `expires=727187` which is in about `21600s` from `now`. This is the maximum TCP connection lifetime in [here](https://github.com/cilium/cilium/blob/1.7.3/bpf/node_config.h#L56).

3) The sender (where we're observing) tries to establish a new TCP connection to port `7777` on the receiver. It sends a packet to the port that is closed and receives a RST.

These are captured traces for (3):
```
3)
-> stack flow 0x58208063 identity 279988->3 state new ifindex 0 orig-ip 0.0.0.0: 172.16.106.7:33462 -> 172.16.42.108:7777 tcp SYN
-> endpoint 973 flow 0xf8720d19 identity 3->279988 state reply ifindex veth9866e6c1 orig-ip 172.16.42.108: 172.16.42.108:7777 -> 172.16.106.7:33462 tcp ACK, RST
-> endpoint 973 flow 0xf8720d19 identity 3->279988 state reply ifindex 0 orig-ip 172.16.42.108: 172.16.42.108:7777 -> 172.16.106.7:33462 tcp ACK, RST
```

This CT entry is created for (3):
```
(3) TCP OUT 172.16.106.7:33462 -> 172.16.42.108:7777 expires=727434 RxPackets=2 RxBytes=108 RxFlagsSeen=0x14 LastRxReport=705834 TxPackets=1 TxBytes=74 TxFlagsSeen=0x02 LastTxReport=705834 Flags=0x0011 [ RxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=279988
```
This entry will also expire in about `21600s`. Same as case (2).

This results in connections accumulating in the Cilium CT map and expiring after a long time (6 hours). It should be noted that, reducing `conntrack-gc-interval` won't help because these entries are not eligible to be removed. Also, increasing `bpf-ct-global-tcp-max` significantly will just postpone the problem for a few hours depending on the volume and type of traffic in a cluster. Eventually this results in `CT: Map insertion failed` and dropped packets.

Apparently, a single RST doesn't trigger a shortened timeout and there is an issue in the detection of non-SYN state (Thanks to @tgraf for the hint).

### PR DESCRIPTION
**Pull request by kkourt**
Consider a pod trying to connect to another pod (valid IP) in a port that no app listens to.

```    
client -> server: SYN
server->client: ACK,RST
```
    
This exchange will result in the following CT entry:
    
```
TCP OUT 10.11.0.34:55510 -> 10.11.1.136:6767 expires=335419 (in 21591 sec(s) from now) RxPackets=1 RxBytes=54 RxFlagsSeen=0x04 LastRxReport=313819 TxPackets=1 TxBytes=74 TxFlagsSeen=0x02 LastTxReport=313819 Flags=0x0011 [ RxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=12121 IfIndex=0
```
   
That is, even though we get an RST flag on the return path, the CT verdict is a reply and the entry is updated with a lifetime of 21600s. This PR distinguishes between FIN and RST TCP and in the case of an RST on the return path it sets the timeout to CT_CLOSE_TIMEOUT (10s).

There are also some additional helper patches so please review them individually.

Update: use BPF_PROG_TEST_RUN tests.

Fixes: #11742

### CODE REVIEW

**Comment by kkourt** [comment]
test-me-please

**Comment by kkourt** [comment]
Re checkpatch warnings: My preference would be to keep the code as it is. If we want to be strict, I can of course change it.

**Comment by kkourt** [comment]
test-me-please

File: bpf/lib/conntrack.h [hunk 1]
```diff
@@ -254,14 +255,15 @@ static __always_inline __u8 __ct_lookup(const void *map, struct __ctx_buff *ctx,
...
+		case ACTION_RESET:
 			/* RST or similar, immediately delete ct entry */
 			if (dir == CT_INGRESS)
 				entry->rx_closing = 1;
 			else
 				entry->tx_closing = 1;
 
 			*monitor = TRACE_PAYLOAD_LEN;
-			if (ct_entry_alive(entry))
+			if (ct_entry_alive(entry) && action != ACTION_RESET)
```
Comment (joestringer) [inline bpf/lib/conntrack.h]: I briefly played with the idea of whether this would be clearer with something like the following instead:

```
static __always_inline void ct_entry_terminate(const struct ct_entry *entry)
{
        entry->rx_closing = entry->tx_closing = 1;
}
```

then above,

```
case ACTION_RESET:
    ct_entry_terminate(entry);
    /* fallthrough */
case ACTION_CLOSE:
```

Then, no change to this line.

Possible implications:
1. This would actually update the fields in the entry that imply closing, so if any other subsequent logic wanted to switch logic based off that (eBPF or userspace by dumping the entry), then connections being reset would be considered also closed. 
1. Could affect code generation

I think point (1) is a bit of a wash, I don't see any such logic so other than a mild preference for readability, I don't think it's much of a motivation to change it. Point (2) is more interesting, I could see some potential for complexity reduction since this branch would have one less condition to check, but I haven't sat down & tried out the two approaches to see if there's a real difference. It could also turn out that the compiler optimizes any differences away.

So I guess in summary, if you're interested in digging a little deeper, this might be a path to learn a bit more but it's a bit orthogonal to the goal you have for this PR.

File: bpf/lib/conntrack.h [hunk 2]
```diff
@@ -254,14 +255,15 @@ static __always_inline __u8 __ct_lookup(const void *map, struct __ctx_buff *ctx,
 			}
 			break;
 		case ACTION_CLOSE:
+		case ACTION_RESET:
```
Comment (joestringer) [inline bpf/lib/conntrack.h]: nit: Please add `/* fallthrough */` to document that the cases here are intentional:

```
case ACTION_CLOSE:
    /* fallthrough */
case ACTION_RESET:
```

File: bpf/lib/conntrack.h [hunk 3]
```diff
@@ -406,10 +408,13 @@ static __always_inline int ct_lookup6(const void *map,
...
 
-			if (unlikely(tcp_flags.value & (TCP_FLAG_RST|TCP_FLAG_FIN)))
+			if (unlikely(tcp_flags.value & TCP_FLAG_RST)) {
+				action = ACTION_RESET;
+			} else if (unlikely(tcp_flags.value & TCP_FLAG_FIN)) {
 				action = ACTION_CLOSE;
-			else
+			} else {
 				action = ACTION_CREATE;
+			}
```
Comment (joestringer) [inline bpf/lib/conntrack.h]: As the script pointed out, we use kernel style in the BPF datapath code, so no braces unless necessary. For consistency, please switch over to the approach suggested byt he checkpatch script.

File: test/k8sT/CT.go [hunk 4]
```diff
@@ -0,0 +1,84 @@
...
+	var (
+		kubectl        *helpers.Kubectl
+		ciliumFilename string
+	)
+
+	BeforeAll(func() {
+		kubectl = helpers.CreateKubectl(helpers.K8s1VMName(), logger)
+		ciliumFilename = helpers.TimestampFilename("cilium.yaml")
+		DeployCiliumOptionsAndDNS(kubectl, ciliumFilename, map[string]string{
+			"bpf.monitorAggregation": "none",
```
Comment (joestringer) [inline test/k8sT/CT.go]: Do you need `monitorAggregation: none` to validate this functionality? Surely the "new" "RST" flag should always trigger a monitor notification, even if monitor aggregation is set to medium (default) ?

File: test/k8sT/CT.go [hunk 5]
```diff
@@ -0,0 +1,84 @@
...
+	})
+
+	Context("CT Timeouts", func() {
+		It("Checks timeout of TCP connection attempts in ports that none listens to", func() {
+
+			port := 12346
+			ciliumPodK8s1, err := kubectl.GetCiliumPodOnNode(helpers.K8s1)
+			ExpectWithOffset(2, err).Should(BeNil(), "Cannot get cilium pod on k8s1")
+			// ciliumPodK8s2, err := kubectl.GetCiliumPodOnNode(helpers.K8s2)
+			// ExpectWithOffset(2, err).Should(BeNil(), "Cannot get cilium pod on k8s2")
```
Comment (joestringer) [inline test/k8sT/CT.go]: Leftover code to be removed?

File: test/k8sT/manifests/testpods.yaml [hunk 6]
```diff
@@ -0,0 +1,36 @@
+---
```
Comment (joestringer) [inline test/k8sT/manifests/testpods.yaml]: Is there something unique / different about these pods vs. some of the other sample apps we have? I would prefer to minimize the number of new different manifests we use if possible, so that if we need to debug the test, we don't have to spend as much time understanding what the manifest does compared with the deployments we use in other tests. Of course, feel free to disregard this point if there's some obvious difference in this manifest that I'm missing.

File: test/k8sT/CT.go [hunk 7]
```diff
@@ -0,0 +1,84 @@
...
+	"strconv"
+	"strings"
+
+	. "github.com/onsi/gomega"
+
+	. "github.com/cilium/cilium/test/ginkgo-ext"
+	"github.com/cilium/cilium/test/helpers"
+)
+
+var _ = Describe("K8sConnectionTracking", func() {
```
Comment (joestringer) [inline test/k8sT/CT.go]: I wonder, can we achieve the same testing through `bpf/tests/conntrack_test.h` `test___ct_lookup()` instead? If we're just trying to validate timeout behaviour, that's one of the few things we actually have unit test infrastructure that we can use to validate.

It should take fractions of a second to validate the change in functionality, not seconds or minutes worth of configuring the cluster, creating apps, running commands to generate traffic, just to check a timeout.

If the goal of this is to put some infrastructure in place to be able to build out more comprehensive testing, or if there's unusual application behaviour that requires integration testing to properly simulate, then I can see arguments to have additional tests like this. Otherwise I wonder if we can gain the same validation in a more lightweight manner.

File: test/k8sT/Services.go [hunk 8]
```diff
@@ -779,7 +779,7 @@ var _ = Describe("K8sServicesTest", func() {
 			// packets.
 
 			// Field #7 is "RxPackets=<n>"
-			cmdIn := "cilium bpf ct list global | awk '/%s/ { sub(\".*=\",\"\", $7); print $7 }'"
+			cmdIn := "cilium bpf ct list global | perl -ne 'print $1 if /%s.*RxPackets=(\\d+).*/'"
```
Comment (joestringer) [inline test/k8sT/Services.go]: These changes appear to be made in the commit which introduces a new `--time-diff` flag, but these commands aren't using the new flag. Is the default behaviour changing? Should this change be in a different commit?

Also, I would be reluctant to start adding `perl` usage into the codebase simply to minimize the number of different languages we use. I'm happy to be overruled if we think perl knowledge is more common across the Cilium contributor community than awk (they're both a bit foreign to me), but I'll at least raise it as a point here since this seems like this would be the first perl expression.

**Review by joestringer — CHANGES_REQUESTED** [review]
I didn't look closely at the --time-diff command but it looks super useful. I'll let other reviewers look closer at that area.

A few minor points on the datapath and testing side. In particular, it seems like integration testing is a heavy hammer to use for validating functionality that should be able to be unit-tested. More detail below.

File: cilium/cmd/bpf_ct_list.go [hunk 9]
```diff
@@ -57,6 +63,36 @@ func getMaps(eID string) []*ctmap.Map {
 	return ctmap.LocalMaps(&dummyEndpoint{ID: id}, true, true)
 }
 
+func doDumpEntries(m ctmap.CtMap) {
+	var out string
+	var err error
+
+	if timeDiff {
+		params := daemon.NewGetHealthzParamsWithTimeout(5 * time.Second)
```
Comment (aanm) [inline cilium/cmd/bpf_ct_list.go]: Usually the `cilium bpf` commands don't require connection to the agent. Can't the developer pass a flag with the clock type as a fallback?

File: pkg/maps/ctmap/ctmap.go [hunk 10]
```diff
@@ -283,6 +284,54 @@ func (m *Map) DumpEntries() (string, error) {
...
+		if err != nil {
+			return "", err
+		}
+		now = now / 1000000000
+		toRemSecs = func(t uint32) string {
+			diff := int64(t) - int64(now)
+			return fmt.Sprintf("remaining: %d sec(s)", diff)
+		}
+
+	case "jiffies":
```
Comment (aanm) [inline pkg/maps/ctmap/ctmap.go]: `case models.ClockSourceModeJiffies:`

File: pkg/maps/ctmap/ctmap.go [hunk 11]
```diff
@@ -283,6 +284,54 @@ func (m *Map) DumpEntries() (string, error) {
 	return DoDumpEntries(m)
 }
 
+func DumpEntriesWithTimeDiff(m CtMap, clockSource models.ClockSource) (string, error) {
+	var toRemSecs func(uint32) string
+	switch clockSource.Mode {
+	case "ktime":
```
Comment (aanm) [inline pkg/maps/ctmap/ctmap.go]: `case models.ClockSourceModeKtime:`

File: pkg/maps/ctmap/ctmap.go [hunk 12]
```diff
@@ -283,6 +284,54 @@ func (m *Map) DumpEntries() (string, error) {
...
+		key := k.(CtKey)
+		if !key.ToHost().Dump(&sb, true) {
+			return
+		}
+		value := v.(*CtEntry)
+		sb.WriteString(value.TimeDiffString(toRemSecs))
+	}
+	// DumpWithCallback() must be called before sb.String().
+	err := m.DumpWithCallback(cb)
+	return sb.String(), err
```
Comment (aanm) [inline pkg/maps/ctmap/ctmap.go:316]: if there's an error, do we still need to do `sb.String`?, i.e.:
```
err := m.DumpWithCallback(cb)
if err != nil {
    return "", err
}
return sb.String(), nil
```

File: test/k8sT/Services.go (hunk 8 above)
Comment (aanm) [reply test/k8sT/Services.go]: +1

**Review by aanm — CHANGES_REQUESTED** [review]

File: test/k8sT/CT.go (hunk 4 above)
Comment (kkourt) [reply test/k8sT/CT.go]: nope, it's a leftover. I'll remove it.

File: test/k8sT/manifests/testpods.yaml (hunk 6 above)
Comment (kkourt) [reply test/k8sT/manifests/testpods.yaml]: I could not find any, but maybe I missed it? The distinguish characteristic is that these are pods (i.e., not deployments) and they use the netperf container (technically, netcat but we typically use the netperf container for that). 

The closest one I found was `test-cli.yaml` but this one has the pods running on the same node instead of different nodes which was what I wanted. (it probably does not make a difference, but since we are getting two nodes up anyway, I felt it's safer to test with packets going over the wire.)

File: test/k8sT/CT.go (hunk 7 above)
Comment (kkourt) [reply test/k8sT/CT.go]: I agree that it is too much overhead for this simple use-case. I also think that the unit tests will not have the same coverage as the current test, since AFAIU we do not process actual packets in the latter.

I think there is a (mostly) happy middle ground where we:  create a tap device, load parts (e.g., the CT code with some minimal initial processing) of the datapath, send constructed packets to the interface, and check the state from the BPF maps. I think that this would generally very useful to have, and I cannot think of a reason why it wouldn't work. I want to try and hack something up and see if I can make it work.

File: test/k8sT/Services.go (hunk 8 above)
Comment (kkourt) [reply test/k8sT/Services.go]: > These changes appear to be made in the commit which introduces a new --time-diff flag, but these commands aren't using the new flag. Is the default behaviour changing? Should this change be in a different commit?

Makes sense.

> Also, I would be reluctant to start adding perl usage into the codebase simply to minimize the number of different languages we use. I'm happy to be overruled if we think perl knowledge is more common across the Cilium contributor community than awk (they're both a bit foreign to me), but I'll at least raise it as a point here since this seems like this would be the first perl expression.

I thnk the perl one liner above is more easy to understand than the awk above because it is just a single regular expression. Even if you don't understand all the details, I think you get an idea of what it does. That's my personal opinion colored by my personal bias though :-)

File: cilium/cmd/bpf_ct_list.go (hunk 9 above)
Comment (kkourt) [reply cilium/cmd/bpf_ct_list.go]: I thought about this option, but I decided that it would not be very ergonomic to do so and opted to make their (and our) lives easier. Especially because users would have to use the same first-level command (`cilium`) to do this:
```
cilium status --verbose
cilium bpf ct list --time-diff --clock-source xxx
```

I believe connecting the agent _only_ if a specific flag is give is a good tradeoff because the tool will continue to work on its basic form (as before) without depending on the agent.

File: bpf/lib/conntrack.h (hunk 1 above)
Comment (kkourt) [reply bpf/lib/conntrack.h]: I thought about this as well.

The reason I opted not to do so is that the sender end has not seen the `RST` yet so it is technically not closing yet. I think this is similar to 1. in that it does not currently seem to matter but that might change in the future.

IMHO, we should optimize for readability rather than complexity in this case. Not because complexity does not matter, but because I think the difference is very small and can change with the surrounding code and the compiler version. That is, if complexity is lower now there is a high chance that a couple of code additions and/or compiler versions this might change.

That being said, I don't mind trying this out.

File: cilium/cmd/bpf_ct_list.go (hunk 9 above)
Comment (aanm) [reply cilium/cmd/bpf_ct_list.go]: > I thought about this option, but I decided that it would not be very ergonomic to do so and opted to make their (and our) lives easier. Especially because users would have to use the same first-level command (`cilium`) to do this:
> 
> ```
> cilium status --verbose
> cilium bpf ct list --time-diff --clock-source xxx
> ```
> 
> I believe connecting the agent _only_ if a specific flag is give is a good tradeoff because the tool will continue to work on its basic form (as before) without depending on the agent.

What I'm suggesting is to have a flag that allows someone to pass the `time-diff` as a value of its own, this is useful even if the agent is not available. I'm not saying to replace the `params := daemon.NewGetHealthzParamsWithTimeout(5 * time.Second)` with the flag.

Comment (kkourt) [reply cilium/cmd/bpf_ct_list.go]: I see, so

```
cilium bpf ct list --time-diff
```

contacts the server, and:


```
cilium bpf ct list --time-diff --time-diff-clocksource=jiffies|ktime
```

does not contact the server.

Makes sense!

File: cilium/cmd/bpf_ct_list.go [hunk 13]
```diff
@@ -57,6 +63,36 @@ func getMaps(eID string) []*ctmap.Map {
 	return ctmap.LocalMaps(&dummyEndpoint{ID: id}, true, true)
 }
 
+func doDumpEntries(m ctmap.CtMap) {
+	var out string
+	var err error
```
Comment (christarazi) [inline cilium/cmd/bpf_ct_list.go]: Nit:

```
var (
 out string
 err  error
)
```

File: test/k8sT/CT.go (hunk 7 above)
Comment (joestringer) [reply test/k8sT/CT.go]: There's also I believe the option to load a program, then simulate running a packet through using the `BPF_PROG_TEST_RUN` command to the `bpf()` syscall.

File: bpf/lib/conntrack.h (hunk 1 above)
Comment (tgraf) [inline bpf/lib/conntrack.h]: Doesn't this allow for anybody to spam a ton of RSTs (with invalid sequence numbers) in one direction without requiring the victim to have a chance to react and cause all lifetimes of the conntrack table to be reset to 10s to trigger the expiration of connections that could still be alive?

**Review by tgraf — CHANGES_REQUESTED** [review]

File: bpf/lib/conntrack.h (hunk 1 above)
Comment (kkourt) [reply bpf/lib/conntrack.h]: The packets would have to be mapped to the same CT entry, so AFAIU they would need to have the same 4-tuple.

When we originally discussed this approach on the datapath meeting, I believe that @joestringer mentioned that we do not allow pods to send packets that do not match their IP. So the spurious packets will have to come from the same pod as the alive connections, which under normal operation should not happen since the port should already be binded if an active connection exists.

Comment (kkourt) [reply bpf/lib/conntrack.h]: If I'm missing something, one way to amortize the problem would be to only set `ACTION_RESET` for CT entries that have not seen both `SYN`s, since from a quick look we are already tracking this. In this case, the issue would happen only during the 3-way handshake.

Comment (tgraf) [reply bpf/lib/conntrack.h]: > When we originally discussed this approach on the datapath meeting, I believe that @joestringer mentioned that we do not allow pods to send packets that do not match their IP. So the spurious packets will have to come from the same pod as the alive connections, which under normal operation should not happen since the port should already be binded if an active connection exists.

Agreed but I don't think that is protection enough to assume that we are fully OK with anybody with access to schedule a host networking pod with raw socket access can terminate connections of other pods at will.

> If I'm missing something, one way to amortize the problem would be to only set ACTION_RESET for CT entries that have not seen both SYNs, since from a quick look we are already tracking this. In this case, the issue would happen only during the 3-way handshake.

Yes, that is a good protection mechanism. The handshake makes it reasonable to expect packets delivered in both directions so even if the lifetime is adjusted incorrectly by a malicious packet, it would get reset when the SYN-ACK arrives. The main concern is that the lifetime can be reduced on connections which are iding.

File: bpf/lib/conntrack.h (hunk 3 above)
Comment (kkourt) [reply bpf/lib/conntrack.h]: Addressed.

File: test/k8sT/CT.go (hunk 7 above)
Comment (kkourt) [reply test/k8sT/CT.go]: Pushed a new version that uses such a test.

File: test/k8sT/Services.go (hunk 8 above)
Comment (kkourt) [reply test/k8sT/Services.go]: Change removed.

File: cilium/cmd/bpf_ct_list.go (hunk 9 above)
Comment (kkourt) [reply cilium/cmd/bpf_ct_list.go]: Updated version includes this change.

**Comment by kkourt** [comment]
test-me-please

**Comment by kkourt** [comment]
test-me-please

**Comment by kkourt** [comment]
There seem to be verification errors, so I need to have a closer look at this. It might even make sense to take invidual patches and do them as separate PRs. I'll convert it to draft for now, until I'll figure a way to move forward.

**Comment by kkourt** [comment]
retest-net-next

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go [hunk 14]
```diff
@@ -0,0 +1,476 @@
...
+	}
+
+	if err := iter.Err(); err != nil {
+		return ret, fmt.Errorf("Error iterating map: %v", err)
+	}
+
+	return ret, nil
+}
+
+func MapDeleteAll(m *ebpf.Map) error {
```
Comment (ti-mo) [inline bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: Exported function, but doesn't seem to be used outside this package.

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go [hunk 15]
```diff
@@ -0,0 +1,476 @@
+package main
```
Comment (ti-mo) [inline bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: Why not make this a testable Go package? (e.g. renaming to `bpf/tests/prog_test.go`)

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go [hunk 16]
```diff
@@ -0,0 +1,476 @@
...
+	"github.com/cilium/ebpf"
+	"github.com/cilium/ebpf/perf"
+
+	"github.com/google/gopacket"
+	"github.com/google/gopacket/layers"
+	log "github.com/sirupsen/logrus"
+	"golang.org/x/sys/unix"
+)
+
+type Ct4GlobalMap map[ctmap.CtKey4Global]ctmap.CtEntry
```
Comment (ti-mo) [inline bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: Exported symbol only used in this package.

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go [hunk 17]
```diff
@@ -0,0 +1,476 @@
...
+
+func Ct4TcpMapFromBPF(ebpfMap *ebpf.Map) (Ct4GlobalMap, error) {
```
Comment (ti-mo) [inline bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: Exported function only used in this package.

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 15 above)
Comment (kkourt) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: That would require two .go files, right? I was just opting for keeping things simple...

**Comment by kkourt** [comment]
test-me-please

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 15 above)
Comment (joestringer) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: Nope, not required:

```
$ ls
foo_test.go
$ go test -v ./...
=== RUN   TestIntMinBasic
--- PASS: TestIntMinBasic (0.00s)
=== RUN   TestIntMinTableDriven
=== RUN   TestIntMinTableDriven/0,1
=== RUN   TestIntMinTableDriven/1,0
=== RUN   TestIntMinTableDriven/2,-2
=== RUN   TestIntMinTableDriven/0,-1
=== RUN   TestIntMinTableDriven/-1,0
--- PASS: TestIntMinTableDriven (0.00s)
    --- PASS: TestIntMinTableDriven/0,1 (0.00s)
    --- PASS: TestIntMinTableDriven/1,0 (0.00s)
    --- PASS: TestIntMinTableDriven/2,-2 (0.00s)
    --- PASS: TestIntMinTableDriven/0,-1 (0.00s)
    --- PASS: TestIntMinTableDriven/-1,0 (0.00s)
PASS
ok      _/home/joe/playground/test      0.003s
```

foo_test.go is a direct copy of the code from https://gobyexample.com/testing .

**Comment by kkourt** [comment]
retest-net-next

**Comment by kkourt** [comment]
retest-4.19

**Comment by kkourt** [comment]
Failures seemed unrelated: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-net-next/1466/, https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Kernel/4054/

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 15 above)
Comment (kkourt) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: Ah OK, now I understand. @ti-mo 's point was to invoke this as a testing package using `go test`. I think that makes sense.

**Comment by kkourt** [comment]
Again failures (https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Kernel/4060/) are of the "DNS did not become ready" kind, which seems to be a separate issue: https://github.com/cilium/cilium/issues/13774

**Comment by kkourt** [comment]
retest-4.19

**Comment by kkourt** [comment]
I'm moving this PR out of draft and re-requesting reviews. (The verification error was just an error caused by a new file not being ignored by the testing script.)

Thanks everyone for the comments -- I believe all major  issues have been addressed.

The only remaining issues  is @ti-mo 's suggestion to make the test a testable go package. I'd like to address this in a followup PR that also adds the test program into CI.

File: bpf/lib/conntrack.h (hunk 1 above)
Comment (kkourt) [reply bpf/lib/conntrack.h]: Updated version does what is described above, i.e., only reduces the timeout for connections where not both SYNs have been seen.

**Comment by kkourt** [comment]
Again, tests fail with "FAIL: Kubernetes DNS did not become ready in time" (https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Kernel/4062/testReport/junit/Suite-k8s-1/18/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan_With_host_policy_Tests_NodePort/) 

I'll try to run the test locally and see what happens.

**Comment by pchaigno** [comment]
> Again, tests fail with "FAIL: Kubernetes DNS did not become ready in time" (https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Kernel/4062/testReport/junit/Suite-k8s-1/18/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan_With_host_policy_Tests_NodePort/)
> 
> I'll try to run the test locally and see what happens.

Before resorting to that, did you check the Cilium logs?

**Comment by kkourt** [comment]
> Before resorting to that, did you check the Cilium logs?

I did.

Maybe I'm missing something, so here what I saw in the logs.

Let's take `pod-kube-system-cilium-9wfxm-cilium-agent.log` for example.

There is this:
```
2020-12-03T09:14:41.298960017Z level=warning msg="3006: (7b) *(u64 *)(r10 -136) = r1" subsys=datapath-loader
2020-12-03T09:14:41.298963445Z level=warning msg="BPF program is too large. Processed 131073 insn" subsys=datapath-loader
2020-12-03T09:14:41.298967102Z level=warning subsys=datapath-loader
2020-12-03T09:14:41.298970172Z level=warning msg="Error filling program arrays!" subsys=datapath-loader
2020-12-03T09:14:41.298973604Z level=warning msg="Unable to load program" subsys=datapath-loader
2020-12-03T09:14:41.309253634Z level=warning msg="JoinEP: Failed to load program for host endpoint (to-host)" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=2249 error="Failed to load tc filter: exit status 1" file-path=2249_next/bpf_host.o identity=1 ipv4= ipv6= k8sPodName=/ subsys=datapath-loader veth=cilium_host
2020-12-03T09:14:41.309276191Z level=error msg="Error while rewriting endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=2249 error="Failed to load tc filter: exit status 1" identity=1 ipv4= ipv6= k8sPodName=/ subsys=endpoint
```

Which seems suspicious, but looking later at the log there is:

```
2020-12-03T09:18:46.457386420Z level=debug msg="Finished writing ELF" error="<nil>" new-elf-path=2249_next/bpf_netdev_enp0s3.o subsys=elf template-path=2249_next/bpf_host.o
2020-12-03T09:18:46.457544204Z level=debug msg="netlink: Replacing qdisc for cilium_host succeeded" subsys=datapath-loader
2020-12-03T09:18:47.859847965Z level=debug msg="Load 1-min: 0.59 5-min: 1.45 15min: 1.43" subsys=loadinfo type=background
2020-12-03T09:18:47.859874531Z level=debug msg="Memory: Total: 7974 Used: 817 (10.25%) Free: 3691 Buffers: 148 Cached: 3316" subsys=loadinfo type=background
2020-12-03T09:18:47.859957152Z level=debug msg="Swap: Total: 0 Used: 0 (0.00%) Free: 0" subsys=loadinfo type=background
2020-12-03T09:18:47.860358021Z level=debug msg="NAME tc STATUS R PID 719 CPU: 47.90% MEM: 0.04% CMDLINE: tc filter replace dev cilium_host ingress prio 1 handle 1 bpf da obj 2249_next/bpf_host.o sec to-host MEM-EXT: RSS: 3 VMS: 6 Data: 0 Stack: 0 Locked: 0 Swap: 0" subsys=loadinfo type=background
2020-12-03T09:18:48.299914729Z level=debug msg="Skipping CiliumEndpoint update because it has not changed" containerID= controller="sync-to-k8s-ciliumendpoint (438)" datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=438 identity=7697 ipv4= ipv6= k8sPodName=/ subsys=endpointsynchronizer
2020-12-03T09:18:48.299940321Z level=debug msg="Controller func execution time: 120.886µs" name="sync-to-k8s-ciliumendpoint (438)" subsys=controller uuid=fd7f5649-3547-11eb-82bc-080027d34594
```

AFAICT, this means that the bpf_host.o was actually loaded. The endpointID seems to be the same. So my assumption is that cilium actually succeeded in inserting `bpf_host.o` and everything was OK after that from the cilium side.

**Comment by kkourt** [comment]
> > Before resorting to that, did you check the Cilium logs?
> 
> I did.
> AFAICT, this means that the bpf_host.o was actually loaded. The endpointID seems to be the same (2249). So my assumption is that cilium actually succeeded in inserting `bpf_host.o` and everything was OK after that from the cilium side.

Having a second look at this looks that my assumption is wrong. I guess the success is just for compiling the program rather than loading it.

**Comment by pchaigno** [comment]
> > > Before resorting to that, did you check the Cilium logs?
> > 
> > 
> > I did.
> > AFAICT, this means that the bpf_host.o was actually loaded. The endpointID seems to be the same (2249). So my assumption is that cilium actually succeeded in inserting `bpf_host.o` and everything was OK after that from the cilium side.
> 
> Having a second look at this looks that my assumption is wrong. I guess the success is just for compiling the program rather than loading it.

The success is for a different endpoint. The one failing is the host endpoint (`identity=1` or `HOST_ID`) whereas the one succeeding has `identity=43267`.

The `BPF program is too large. Processed 131073 insn` error indicates a complexity issue. Given this happen in a host firewall test, I would say you have a complexity regression when combining your new code with the host firewall :cry:

**Comment by kkourt** [comment]
Refactored the code to avoid verification problems.

**Comment by kkourt** [comment]
test-me-please

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go [hunk 18]
```diff
@@ -0,0 +1,473 @@
+package main
```
Comment (aanm) [inline bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: needs copyright header.

**Review by aanm — APPROVED** [review]
Minot nit that needs to be addressed but doesn't require my 2nd review.

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 18 above)
Comment (kkourt) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: Thanks!

**Comment by kkourt** [comment]
test-me-please

**Comment by kkourt** [comment]
test-me-please

**Comment by kkourt** [comment]
GKE seemd to have failed with early timeout error: https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/3538/. Retesting.

test-gke

**Comment by kkourt** [comment]
test-gke

File: bpf/lib/conntrack.h [hunk 19]
```diff
@@ -253,12 +261,20 @@ static __always_inline __u8 __ct_lookup(const void *map, struct __ctx_buff *ctx,
...
+			if (!ct_entry_seen_both_syns(entry) &&
+			    (seen_flags.value & TCP_FLAG_RST)) {
 				entry->rx_closing = 1;
-			else
 				entry->tx_closing = 1;
+			} else if (dir == CT_INGRESS) {
+				entry->rx_closing = 1;
+			} else {
+				entry->tx_closing = 1;
+			}
```
Comment (borkmann) [inline bpf/lib/conntrack.h:280]: This should only be done for dir != CT_SERVICE since for the latter we may not see both directions.

**Review by tgraf — APPROVED** [review]
My concern has been addressed so LGTM.

File: bpf/lib/conntrack.h (hunk 19 above)
Comment (kkourt) [reply bpf/lib/conntrack.h:280]: Do you mean that the last `else` should be `else if (dir == CT_EGRESS)` like so:

```
	/* If we got an RST and have not seen both SYNs,
	 * terminate the connection
	 */
	if (!ct_entry_seen_both_syns(entry) &&
	    (seen_flags.value & TCP_FLAG_RST)) {
		entry->rx_closing = 1;
		entry->tx_closing = 1;
	} else if (dir == CT_INGRESS) {
		entry->rx_closing = 1;
	} else if (dir == CT_EGRESS) {
		entry->tx_closing = 1;
	}
```

File: pkg/maps/ctmap/ctmap.go [hunk 20]
```diff
@@ -286,6 +290,54 @@ func (m *Map) DumpEntries() (string, error) {
 	return DoDumpEntries(m)
 }
 
+func DumpEntriesWithTimeDiff(m CtMap, clockSource models.ClockSource) (string, error) {
```
Comment (brb) [inline pkg/maps/ctmap/ctmap.go]: Have you considered making the `DoDumpEntries(..)` function to accept an option parameter which could contain `bool` to indicate whether time-diff is required and if so, then another field which contains the clock source? That would eliminate a bit of boilerplate code.

File: pkg/maps/ctmap/types.go [hunk 21]
```diff
@@ -588,3 +588,22 @@ func (c *CtEntry) String() string {
 		c.SourceSecurityID,
 		c.IfIndex)
 }
+
+func (c *CtEntry) TimeDiffString(toRemSecs func(uint32) string) string {
```
Comment (brb) [inline pkg/maps/ctmap/types.go]: Maybe we could change `(c *CtEntry) String(..)` to `StringWithOpt(..)`, then make `String(..)` to invoke `StringWithOpt(..)`, so that we could DRY?

File: pkg/maps/ctmap/ctmap.go (hunk 12 above)
Comment (pchaigno) [reply pkg/maps/ctmap/ctmap.go:316]: @kkourt I think you forgot to push the change to address :point_up:

File: bpf/Makefile [hunk 22]
```diff
@@ -8,6 +8,7 @@ include ../Makefile.defs
 SUBDIRS = sockops
```
Comment (pchaigno) [inline bpf/Makefile:8]: Commit `bpf: add BPF_PROG_RUN_TEST tests` has a typo on `It is intentended for a subsequent patch.` Probably not worth re-spinning just for that.

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 15 above)
Comment (pchaigno) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: Were there any changes made to address this? What's the `go test` command we should use?

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go [hunk 23]
```diff
@@ -0,0 +1,487 @@
...
+		return errors.New("unexpected data modification")
+	}
+
+	return nil
+}
+
+func testMap(spec *ebpf.Collection) error {
+	prog := spec.Programs["test_map"]
+	if prog == nil {
+		return errors.New("did not find test_nop program")
```
Comment (pchaigno) [inline bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]:
```suggestion
		return errors.New("did not find test_map program")
```

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go [hunk 24]
```diff
@@ -0,0 +1,487 @@
...
+	}
+
+	bpfCtMap := spec.Maps["test_cilium_ct_tcp4_65535"]
```
Comment (pchaigno) [inline bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: Isn't a nil check needed here or in `ct4TcpMapFromBPF`?

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go [hunk 25]
```diff
@@ -0,0 +1,487 @@
...
+
+	packetIn := gopacket.NewSerializeBuffer()
+	opts := gopacket.SerializeOptions{}
+	gopacket.SerializeLayers(packetIn, opts,
+		&layers.Ethernet{
+			SrcMAC:       net.HardwareAddr{1, 0, 0, 3, 0, 10},
+			DstMAC:       net.HardwareAddr{1, 0, 0, 3, 0, 20},
+			EthernetType: layers.EthernetTypeIPv4,
+		},
+	)
```
Comment (pchaigno) [inline bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: Given the same packet is defined several times, maybe worth declaring it as a variable of the package, not of each test function?

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go [hunk 26]
```diff
@@ -0,0 +1,487 @@
...
+		}).Fatal("test failed")
+	}
+
+	err = testCt4Rst(coll)
+	if err != nil {
+		log.WithFields(log.Fields{
+			"test":  "map",
+			"error": err,
+		}).Fatal("test failed")
+	}
```
Comment (pchaigno) [inline bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: I think you can use a function slice for `testNop`, `testMap`, and `testCt4Rst`.

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go [hunk 27]
```diff
@@ -0,0 +1,487 @@
...
+
+	if !reflect.DeepEqual(mapAfter, mapExpected) {
+		return errors.New("resulting BPF CT map is not equal to expected")
+	}
+
+	mapDeleteAll(bpfCtMap)
+	return nil
+}
+
+func patchElf(fname string, fnameOut string) error {
```
Comment (pchaigno) [inline bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: As far as I understand, this patching function is only necessary because we use the map definition convention of iproute2. If we switch to use cilium/ebpf as our loader, it will likely not be necessary anymore (not sure of libbpf's convention if that's what we end up using). Given this patching is kind of a hack, maybe it would be worth clarifying the intent and purpose in a comment?

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go [hunk 28]
```diff
@@ -0,0 +1,487 @@
...
+		dm := monitor.DebugMsg{}
+		reader := bytes.NewReader(record.RawSample)
+		if err := binary.Read(reader, byteorder.Native, &dm); err != nil {
+			return fmt.Errorf("Error while parsing debug message: %v\n", err)
+		}
+
+		// special record values set from our bpf programs to mark their termination
+		if dm.SubType == monitor.DbgUnspec && dm.Arg1 == 0xe3d && dm.Arg2 == 0xe3d {
+			break
+		}
```
Comment (pchaigno) [inline bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: Couldn't you run `dumpDebugMessages` as a goroutine then use a channel to signal the end of `BPF_PROG_TEST_RUN`? it would avoid this hack where we use debug logs to signal the end. We won't be able to use this hack if we later want to extend those `BPF_PROG_TEST_RUN` tests to our existing object files.

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go [hunk 29]
```diff
@@ -0,0 +1,487 @@
...
+			Protocol: layers.IPProtocolTCP,
+			IHL:      5,
+		},
+		&layers.TCP{
+			SrcPort:    3010,
+			DstPort:    3020,
+			DataOffset: 5,
+			SYN:        true,
+		},
+		gopacket.Payload([]byte{'p', 'i', 'z', 'z', 'a', '!', ' ', ':', '-', ')'}),
```
Comment (pchaigno) [inline bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: :smile:

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go [hunk 30]
```diff
@@ -0,0 +1,487 @@
...
+			Protocol: layers.IPProtocolTCP,
+			IHL:      5,
+		},
+		&layers.TCP{
+			DstPort:    3010,
+			SrcPort:    3020,
+			DataOffset: 5,
+			RST:        true,
+		},
+		gopacket.Payload([]byte{'p', 'i', 'z', 'z', 'a', '!', ' ', ':', '-', ')'}),
```
Comment (pchaigno) [inline bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: Maybe best to make a copy of the first packet and change the only two fields that differ? It took me a while to spot the difference (before I read the variable's name).

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go [hunk 31]
```diff
@@ -0,0 +1,487 @@
...
+	)
+
+	bpfCtMap := spec.Maps["test_cilium_ct_tcp4_65535"]
+
+	// First Packet: SYN
+	prog1 := spec.Programs["test_ct4_rst1"]
+	if prog1 == nil {
```
Comment (pchaigno) [inline bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: I think the Go way of writing that would be, but maybe worth double checking:
```suggestion
	if prog1 := spec.Programs["test_ct4_rst1"]; prog1 == nil {
```
Also works for most other checks in this file.

File: bpf/tests/bpf_ct_tests.c [hunk 32]
```diff
@@ -0,0 +1,163 @@
+// SPDX-License-Identifier: GPL-2.0
+/* Copyright (C) 2016-2020 Authors of Cilium */
+
+#include <bpf/ctx/skb.h>
+#include <bpf/api.h>
+
+/* most values taken from node_config.h */
```
Comment (pchaigno) [inline bpf/tests/bpf_ct_tests.c:7]: Probably naive question: can't we just import `node_config.h`?

File: bpf/lib/conntrack.h (hunk 19 above)
Comment (brb) [reply bpf/lib/conntrack.h:280]:
```
if (!ct_entry_seen_both_syns(entry) && (seen_flags.value & TCP_FLAG_RST) && (dir != CT_SERVICE) {
    entry->rx_closing = 1;
    entry->tx_closing = 1;
} else if ...
```

Otherwise, we would prematurely mark the `CT_SERVICE` entry for removal. In the case of `CT_SERVICE`, we see packets only in one direction (to a service).

File: bpf/tests/bpf_ct_tests.c [hunk 33]
```diff
@@ -0,0 +1,163 @@
...
+		.flags = 0,
+	};
+
+	struct ct_entry ct_val = (struct ct_entry){
+		.rx_packets = 1000,
+		.tx_packets = 1000,
+	};
+	struct bpf_elf_map *ctmap = &CT_MAP_TCP4;
+
+	(void)ctx;
```
Comment (pchaigno) [inline bpf/tests/bpf_ct_tests.c]: Our convention for unused arguments is to use `__maybe_unused` which is defined in `include/bpf/compiler.h` and looks safe to pull in here.

**Review by brb — COMMENTED** [review]
Thanks, some comments.

This BPF_PROG_TEST_RUN based testing is :rocket:. If you could convert it to _test.go (as suggested by others), and make it a part of CI, it would be :100: :rocket:.

File: bpf/lib/conntrack.h [hunk 34]
```diff
@@ -223,6 +223,7 @@ static __always_inline __u8 __ct_lookup(const void *map, struct __ctx_buff *ctx,
 			ct_state->ifindex = entry->ifindex;
 			ct_state->dsr = entry->dsr;
 			ct_state->proxy_redirect = entry->proxy_redirect;
+			/* See the ct_create4 comments re the rx_bytes hack */
 			if (dir == CT_SERVICE)
```
Comment (pchaigno) [inline bpf/lib/conntrack.h:235]: @brb I just became aware of this hack. Would it be worth writing a small Coccinelle script to check that all assignments of `x != entry->rx_bytes` to `ct_state->backend_id` are guarded by a check that `dir == z; z != CT_SERVICE`? Happy to write it given it's fairly trivial. It would guarantee we have a test failing if the assumption behind this hack ever becomes false.

**Review by pchaigno — COMMENTED** [review]
Hopefully my review comments don't conflict too much with Martynas's :worried: 

The new `BPF_PROG_TEST_RUN` program looks awesome! And it's simpler than I expected :tada: 
Probably worth adding it to the CI or it will become stale very quickly.

I think long term it would be worth to extend this test to be able to apply such checks to our unmodified object files. We would probably also benefit from having a slightly higher-level way of describing input parameters and expected outputs. Maybe best to move that discussion to a dedicated issue.

File: bpf/lib/conntrack.h (hunk 34 above)
Comment (brb) [reply bpf/lib/conntrack.h:235]: Yeah, makes sense. Thanks!

File: bpf/lib/conntrack.h (hunk 19 above)
Comment (kkourt) [reply bpf/lib/conntrack.h:280]: Got it! Thanks. Should be fixed on the latest version.

File: pkg/maps/ctmap/ctmap.go (hunk 20 above)
Comment (kkourt) [reply pkg/maps/ctmap/ctmap.go]: I've reworked the code to avoid the boilerplate.

File: pkg/maps/ctmap/types.go (hunk 21 above)
Comment (kkourt) [reply pkg/maps/ctmap/types.go]: Used `StringWithTimeDiff` on latest patch to do so.

File: bpf/Makefile (hunk 22 above)
Comment (kkourt) [reply bpf/Makefile:8]: Did a respin anyway, so it should be fixed now.

File: pkg/maps/ctmap/ctmap.go (hunk 12 above)
Comment (kkourt) [reply pkg/maps/ctmap/ctmap.go:316]: Indeed. I changed one of them but not both. Should be fixed now.

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 15 above)
Comment (kkourt) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: Fixed this (see last patch). 

There is now a `make go_prog_test` target that builds the object file and runs the test. It runs `sudo go test ./tests/prog_test`

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 23 above)
Comment (kkourt) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: Fixed! Thanks!

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 25 above)
Comment (kkourt) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: ~It's not the same packet -- it's source/destination addresses/ports are reversed.~

I don't think it offers much at this point. Once we add more tests, I think we use build packet builder functions, but it's probably out of scope for this PR.

(edited)

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 30 above)
Comment (kkourt) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: It's not the same packet -- its source/destination addresses/ports are reversed.

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 26 above)
Comment (kkourt) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: Hmm, if I understand you mean I could do something like:

```
for fn := range  testFns {
    fn(...)
}
```

I'd rather not, since we might want to pass different arguments to the test functions eventually.

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 27 above)
Comment (kkourt) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: Definitely is, thanks! Added a comment.

> If we switch to use cilium/ebpf as our loader, it will likely not be necessary anymore

I thought that this (i.e., not processing al the fields of `bpf_elf_map`) was something that should be fixed on cilium/ebpf. For the current tests, it does not matter because we  don't care about these fields but for the loader I think we do. Nothing to do with this PR, just thought I'd mention it.

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 28 above)
Comment (kkourt) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: Yap, Agreed.

I've seen code that already does this somewhere in our tree. I think the main issue is that we do not want to follow this approach when we integrate this test to CI tests, because we don't want to block forever (or wait for the CI timeout).

I would like to add a subsequent PR that adds some more CT tests and integrates this into the CI, so I plan to address it there.

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 25 above)
Comment (pchaigno) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: > I don't think it offers much

It shortens the code and makes it easier to read. Definitely not a blocker.

**Review by pchaigno — COMMENTED** [review]
I'm super happy for the introduction of this new `BPF_PROG_TEST_RUN`-based tests, but why couldn't this be tested in `test___ct_lookup`? For this particular use case, it seems a lot simpler...

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go [hunk 35]
```diff
@@ -0,0 +1,494 @@
...
+}
+
+func testMap(spec *ebpf.Collection) error {
+	prog := spec.Programs["test_map"]
+	if prog == nil {
+		return errors.New("did not find test_nop program")
+	}
+
+	bpfCtMap := spec.Maps["test_cilium_ct_tcp4_65535"]
+	if prog == nil {
```
Comment (pchaigno) [inline bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]:
```suggestion
	if bpfCtMap == nil {
```

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 31 above)
Comment (kkourt) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: `golint` does not complain about it, but  I've seen it complain it when using this syntax in some cases (although don't remember which and it is entirely possible that I'm misremembering) so I tend not to use it.

File: bpf/tests/bpf_ct_tests.c (hunk 32 above)
Comment (kkourt) [reply bpf/tests/bpf_ct_tests.c:7]: We could, and that's what I did for an initial version but this way we get more freedom in defining only the definitions we want. 

E.g., if I remember correctly, if we include `node_config.h` we cannot directly define `CONNTRACK`, we need to define either `ENABLE_NODEPORT` or `ENABLE_HOST_FIREWALL`. I prefer just defining `CONNTRACK`.

File: bpf/tests/bpf_ct_tests.c (hunk 33 above)
Comment (kkourt) [reply bpf/tests/bpf_ct_tests.c]: fixed!

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 24 above)
Comment (kkourt) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: Yap! Added the check!

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 31 above)
Comment (pchaigno) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: Didn't say it was incorrect Go lint :slightly_smiling_face:
I find it makes the code a bit easier to read, especially when its a successions a checks :wink: 
And we're using it a lot in our code base:
```
$ git grep -P "; \w+ != nil" -- "*.go" | grep -v "^vendor\/" | wc -l
2579
```

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 35 above)
Comment (kkourt) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: :man_facepalming: 

Thanks for catching this :)

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 30 above)
Comment (pchaigno) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: One more argument to copy the packet IMO, because it's very much not obvious that the ports are reversed currently.

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 35 above)
Comment (kkourt) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: It should be fixed now.

**Comment by kkourt** [comment]
> I'm super happy for the introduction of this new `BPF_PROG_TEST_RUN`-based tests, but why couldn't this be tested in `test___ct_lookup`? For this particular use case, it seems a lot simpler...

This was also brought up by @joestringer here: https://github.com/cilium/cilium/pull/14097#discussion_r527304368

We could test this using `test___ct_lookup` or probably `test___ct_timeout` but it it would be a different level of coverage. These tests do not actually process packets, they just check function calls. You might say that for this particular patch it does not matter that much, but (personally) I wouldn't feel safe with only such a test and would have  to do an end-to-end test (manually or in the CI) if I wanted to change something to ensure that it works as expected. Now, I don't feel I have to. And if something ends up being broken, I can easily add a packet exchange to replicate the problem and add another test.

At the same time, I think having a simple test that uses BPF_PROG_RUN is a good investment for better testing on the datapath.

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 31 above)
Comment (kkourt) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: I personally don't find it more readable but it's probably an acquired taste. I'll change it and repush.

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 30 above)
Comment (kkourt) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: Not sure what you mean by copying the packet. Do you mean copy the packet and change the fields by finding their respective offsets? If you could provide an example of what is that you are suggesting, I'd be happy to change the code to match it.

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 31 above)
Comment (pchaigno) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: It could be worth raising in e.g. our #golang channel to see how folks are usually using it.

File: bpf/Makefile [hunk 36]
```diff
@@ -213,6 +213,10 @@ tests/bpf_ct_tests.o: tests/bpf_ct_tests.ll
 	@$(ECHO_CC)
 	$(QUIET) ${LLC} ${LLC_FLAGS} -filetype=obj -o $@ $(patsubst %.o,%.ll,$@)
 
+.PHONY: go_prog_test
+go_prog_test: $(BPF_TEST)
+	sudo go test ./tests/prog_test
```
Comment (pchaigno) [inline bpf/Makefile]: From the development VM:
```
vagrant@k8s1:~/go/src/github.com/cilium/cilium/bpf$ sudo go test ./tests/prog_test
package github.com/cilium/cilium/bpf/tests/prog_test: build constraints exclude all Go files in /home/vagrant/go/src/github.com/cilium/cilium/bpf/tests/prog_test
```
Same error if I run `make -C bpf go_prog_test` from the root of the Cilium sources.

File: bpf/lib/conntrack.h [hunk 37]
```diff
@@ -39,6 +39,14 @@ static __always_inline bool conn_is_dns(__u16 dport)
 	return dport == bpf_htons(53);
```
Comment (pchaigno) [inline bpf/lib/conntrack.h:39]: FYI, the commit `datapath/ct: terminate connections that were reset` triggers a checkpatch warning because it has two signed-off-by.

Comment (kkourt) [reply bpf/lib/conntrack.h:39]: yap, thanks! I've already fixed this into my local tree. I'll push it when I have all fixes ready.

File: bpf/Makefile (hunk 36 above)
Comment (kkourt) [reply bpf/Makefile]: Thanks for testing this! I'll convert the PR to draft until I figure out how to deal with this. (I believe this is due to the build contrain I added). (edited.)

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 31 above)
Comment (kkourt) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: Pushed a new version with the above syntax. It was not trivial to rebase, so added a new patch on top.

**Comment by kkourt** [comment]
test-me-please

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 30 above)
Comment (pchaigno) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: Discussed this offline a bit: there's no good way to modify the packet after creating it with gopacket :disappointed: So it looks like the code duplication is the best we can do for now without big changes.

**Comment by kkourt** [comment]
Runtime failure seems to be due to https://github.com/cilium/cilium/pull/14335

**Comment by kkourt** [comment]
retest-runtime

**Review by pchaigno — APPROVED** [review]

**Review by brb — APPROVED** [review]
Thanks!

**Review by joestringer — APPROVED** [review]

File: pkg/maps/ctmap/ctmap.go [hunk 38]
```diff
@@ -261,25 +262,67 @@ type GCFilter struct {
...
 
-// DoDumpEntries iterates through Map m and writes the values of the ct entries
-// in m to a string.
-func DoDumpEntries(m CtMap) (string, error) {
-	var sb strings.Builder
+// DumpEntriesWithTimeDiff iterates through Map m and writes the values of the
+// ct entries in m to a string. If clockSource is not nil, it uses it to
+// compute the time difference of each entry from now and prints that too.
+func DumpEntriesWithTimeDiff(m CtMap, clockSource *models.ClockSource) (string, error) {
+
```
Comment (christarazi) [inline pkg/maps/ctmap/ctmap.go]: Nit: extra line here not needed

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go [hunk 39]
```diff
@@ -0,0 +1,494 @@
...
+			break
+		}
+		dm.Dump("")
+	}
+
+	return nil
+}
+
+func testCt4Rst(spec *ebpf.Collection) error {
+
```
Comment (christarazi) [inline bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: Nit: extra line

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go [hunk 40]
```diff
@@ -0,0 +1,494 @@
...
+			Protocol: layers.IPProtocolTCP,
+			IHL:      5,
+		},
+		&layers.TCP{
+			DstPort:    3010,
+			SrcPort:    3020,
+			DataOffset: 5,
+			RST:        true,
+		},
+		gopacket.Payload([]byte{'p', 'i', 'z', 'z', 'a', '!', ' ', ':', '-', ')'}),
```
Comment (christarazi) [inline bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: Not a big deal, but was wondering why not just make a string "pizza! :-)" and then cast to `[]byte`?

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go [hunk 41]
```diff
@@ -0,0 +1,494 @@
...
+	}
+	val := bpfCt[key]
+	expires := (val.Lifetime - uint32(now/1000000000))
+	fmt.Printf("Entry expires in %ds\n", expires)
+
+	return nil
+}
+
+func main() {
+
```
Comment (christarazi) [inline bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: Nit: extra lina

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go [hunk 42]
```diff
@@ -0,0 +1,494 @@
...
+	lim := unix.Rlimit{
+		Cur: unix.RLIM_INFINITY,
+		Max: unix.RLIM_INFINITY,
+	}
+	err := unix.Setrlimit(unix.RLIMIT_MEMLOCK, &lim)
+	if err != nil {
+		log.Fatalf("setrlimit: %v", err)
+	}
```
Comment (christarazi) [inline bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: Why is this needed?

File: bpf/Makefile [hunk 43]
```diff
@@ -8,7 +8,7 @@ include ../Makefile.defs
 SUBDIRS = sockops
 
 BPF_SIMPLE = bpf_network.o bpf_alignchecker.o
```
Comment (christarazi) [inline bpf/Makefile:10]: Typo in commit `invovekd` :)

File: bpf/tests/prog_test/prog_test.go [hunk 44]
```diff
@@ -446,52 +451,52 @@ func testCt4Rst(spec *ebpf.Collection) error {
...
 
-	lim := unix.Rlimit{
-		Cur: unix.RLIM_INFINITY,
-		Max: unix.RLIM_INFINITY,
-	}
-	err := unix.Setrlimit(unix.RLIMIT_MEMLOCK, &lim)
+	objDir := ".."
+	fname := path.Join(objDir, "bpf_ct_tests.o")
+	fnamePatched := path.Join(objDir, "bpf_ct_tests_patched.o")
+	err := patchElf(fname, fnamePatched)
```
Comment (christarazi) [inline bpf/tests/prog_test/prog_test.go]: I see that this commit is changing a previous commit. Why not just squash these two commits together?

File: bpf/tests/prog_test/prog_test.go [hunk 45]
```diff
@@ -75,8 +75,7 @@ func mapDeleteAll(m *ebpf.Map) error {
 			break
 		}
 
-		err = m.Delete(key)
-		if err != nil {
+		if err := m.Delete(key); err != nil {
```
Comment (christarazi) [inline bpf/tests/prog_test/prog_test.go:78]: Same here re: squashing commits

**Review by christarazi — CHANGES_REQUESTED** [review]
LGTM overall. Mostly minor nits and some commit squashing comments.

File: cilium/cmd/bpf_ct_list.go (hunk 13 above)
Comment (kkourt) [reply cilium/cmd/bpf_ct_list.go]: fixed

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 39 above)
Comment (kkourt) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: fixed

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 40 above)
Comment (kkourt) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: fixed

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 41 above)
Comment (kkourt) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: fixed by squashing

File: bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go (hunk 42 above)
Comment (kkourt) [reply bpf/tests/bpf-prog-test-run/bpf-prog-test-run.go]: It's needed to run the bpf programs.

File: bpf/Makefile (hunk 43 above)
Comment (kkourt) [reply bpf/Makefile:10]: fixed.

File: bpf/tests/prog_test/prog_test.go (hunk 44 above)
Comment (kkourt) [reply bpf/tests/prog_test/prog_test.go]: squashed

File: bpf/tests/prog_test/prog_test.go (hunk 45 above)
Comment (kkourt) [reply bpf/tests/prog_test/prog_test.go:78]: fixed

**Comment by kkourt** [comment]
test-me-please

**Review by christarazi — APPROVED** [review]

**Comment by kkourt** [comment]
retest-4.19

**Comment by kkourt** [comment]
The checkpatch failures are about commit messages, so this should be good to merge.
