### PR TITLE
l4: Fix l7rules ordering test failure

### LINKED ISSUE #1902: Build failure: ordering of JSON output failed unit tests
Build link: https://jenkins.cilium.io/job/cilium/job/cilium/job/master/784/execution/node/28/log/

Output:
```
18:07:58 ==> cilium-master-build-master-784: FAIL: l4_test.go:124: PolicyTestSuite.TestJSONMarshal
18:07:58 ==> cilium-master-build-master-784: 
18:07:58 ==> cilium-master-build-master-784: l4_test.go:228:
18:07:58 ==> cilium-master-build-master-784:     c.Assert(pretty.Sprintf("%+ v", result), comparator.DeepEquals, expected)
18:07:58 ==> cilium-master-build-master-784: ... obtained string = "" +
18:07:58 ==> cilium-master-build-master-784: ...     "[{\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "  \"port\": 80,\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "  \"protocol\": \"TCP\",\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "  \"l7-rules\": [\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "    {\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "      \"any.foo=\": {\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "        \"http\": [\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "          {\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "            \"path\": \"/\",\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "            \"method\": \"GET\"\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "          }\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "        ]\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "      }\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "    }\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "  ]\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "} {\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "  \"port\": 8080,\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "  \"protocol\": \"TCP\",\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "  \"l7-rules\": [\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "    {\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "      \"\\u003cnone\\u003e\": {\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "        \"http\": [\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "          {\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "            \"path\": \"/\",\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "            \"method\": \"GET\"\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "          }\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "        ]\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "      }\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "    },\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "    {\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "      \"any.foo=\": {\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "        \"http\": [\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "          {\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "            \"path\": \"/\",\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "            \"method\": \"GET\"\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "          },\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "          {\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "            \"path\": \"/bar\",\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "            \"method\": \"GET\"\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "          }\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "        ]\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "      }\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "    }\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "  ]\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "}]"
18:07:58 ==> cilium-master-build-master-784: ... expected string = "" +
18:07:58 ==> cilium-master-build-master-784: ...     "[{\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "  \"port\": 80,\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "  \"protocol\": \"TCP\",\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "  \"l7-rules\": [\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "    {\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "      \"any.foo=\": {\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "        \"http\": [\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "          {\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "            \"path\": \"/\",\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "            \"method\": \"GET\"\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "          }\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "        ]\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "      }\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "    }\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "  ]\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "} {\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "  \"port\": 8080,\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "  \"protocol\": \"TCP\",\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "  \"l7-rules\": [\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "    {\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "      \"any.foo=\": {\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "        \"http\": [\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "          {\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "            \"path\": \"/\",\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "            \"method\": \"GET\"\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "          },\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "          {\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "            \"path\": \"/bar\",\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "            \"method\": \"GET\"\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "          }\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "        ]\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "      }\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "    },\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "    {\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "      \"\\u003cnone\\u003e\": {\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "        \"http\": [\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "          {\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "            \"path\": \"/\",\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "            \"method\": \"GET\"\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "          }\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "        ]\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "      }\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "    }\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "  ]\n" +
18:07:58 ==> cilium-master-build-master-784: ...     "}]"
18:07:58 ==> cilium-master-build-master-784: ... Unified diff:
18:07:58 ==> cilium-master-build-master-784: --- expected
18:07:58 ==> cilium-master-build-master-784: +++ obtained
18:07:58 ==> cilium-master-build-master-784: @@ -1,45 +1,45 @@
18:07:58 ==> cilium-master-build-master-784:  [{
18:07:58 ==> cilium-master-build-master-784:    "port": 80,
18:07:58 ==> cilium-master-build-master-784:    "protocol": "TCP",
18:07:58 ==> cilium-master-build-master-784:    "l7-rules": [
18:07:58 ==> cilium-master-build-master-784:      {
18:07:58 ==> cilium-master-build-master-784:        "any.foo=": {
18:07:58 ==> cilium-master-build-master-784:          "http": [
18:07:58 ==> cilium-master-build-master-784:            {
18:07:58 ==> cilium-master-build-master-784:              "path": "/",
18:07:58 ==> cilium-master-build-master-784:              "method": "GET"
18:07:58 ==> cilium-master-build-master-784:            }
18:07:58 ==> cilium-master-build-master-784:          ]
18:07:58 ==> cilium-master-build-master-784:        }
18:07:58 ==> cilium-master-build-master-784:      }
18:07:58 ==> cilium-master-build-master-784:    ]
18:07:58 ==> cilium-master-build-master-784:  } {
18:07:58 ==> cilium-master-build-master-784:    "port": 8080,
18:07:58 ==> cilium-master-build-master-784:    "protocol": "TCP",
18:07:58 ==> cilium-master-build-master-784:    "l7-rules": [
18:07:58 ==> cilium-master-build-master-784:      {
18:07:58 ==> cilium-master-build-master-784: +      "\u003cnone\u003e": {
18:07:58 ==> cilium-master-build-master-784: +        "http": [
18:07:58 ==> cilium-master-build-master-784: +          {
18:07:58 ==> cilium-master-build-master-784: +            "path": "/",
18:07:58 ==> cilium-master-build-master-784: +            "method": "GET"
18:07:58 ==> cilium-master-build-master-784: +          }
18:07:58 ==> cilium-master-build-master-784: +        ]
18:07:58 ==> cilium-master-build-master-784: +      }
18:07:58 ==> cilium-master-build-master-784: +    },
18:07:58 ==> cilium-master-build-master-784: +    {
18:07:58 ==> cilium-master-build-master-784:        "any.foo=": {
18:07:58 ==> cilium-master-build-master-784:          "http": [
18:07:58 ==> cilium-master-build-master-784:            {
18:07:58 ==> cilium-master-build-master-784:              "path": "/",
18:07:58 ==> cilium-master-build-master-784:              "method": "GET"
18:07:58 ==> cilium-master-build-master-784:            },
18:07:58 ==> cilium-master-build-master-784:            {
18:07:58 ==> cilium-master-build-master-784:              "path": "/bar",
18:07:58 ==> cilium-master-build-master-784:              "method": "GET"
18:07:58 ==> cilium-master-build-master-784:            }
18:07:58 ==> cilium-master-build-master-784:          ]
18:07:58 ==> cilium-master-build-master-784:        }
18:07:58 ==> cilium-master-build-master-784: -    },
18:07:58 ==> cilium-master-build-master-784: -    {
18:07:58 ==> cilium-master-build-master-784: -      "\u003cnone\u003e": {
18:07:58 ==> cilium-master-build-master-784: -        "http": [
18:07:58 ==> cilium-master-build-master-784: -          {
18:07:58 ==> cilium-master-build-master-784: -            "path": "/",
18:07:58 ==> cilium-master-build-master-784: -            "method": "GET"
18:07:58 ==> cilium-master-build-master-784: -          }
18:07:58 ==> cilium-master-build-master-784: -        ]
18:07:58 ==> cilium-master-build-master-784: -      }
18:07:58 ==> cilium-master-build-master-784:      }
18:07:58 ==> cilium-master-build-master-784:    ]
18:07:58 ==> cilium-master-build-master-784:  }]
18:07:58 ==> cilium-master-build-master-784: 
18:07:58 ==> cilium-master-build-master-784: ----------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by joestringer**
This patch fixes issue #1902 reported on GitHub where the ordering of
l7rules formatted to JSON is unreliable. We don't serialize the
L7DataMap to JSON very frequently, so solve this by sorting the
endpointselectors before assembling the JSON.

Fixes: #1902 
Reported-by: Ian Vernon <ian@cilium.io>
Signed-off-by: Joe Stringer <joe@covalent.io>

### CODE REVIEW

**Review by ianvernon — APPROVED** [review]
LGTM, thanks for taking care of this so quickly!

File: pkg/policy/l4.go [hunk 1]
```diff
@@ -39,13 +40,25 @@ func (l7 L7DataMap) MarshalJSON() ([]byte, error) {
...
-	for k, v := range l7 {
+	for _, es := range selectors {
+		if _, ok := l7[es]; !ok {
+			continue
+		}
 		buffer.WriteString("\n  {    \n    \"")
-		buffer.WriteString(k.LabelSelectorString())
+		buffer.WriteString(es.LabelSelectorString())
 		buffer.WriteString("\": ")
-		b, err := json.MarshalIndent(v, "    ", "  ")
```
Comment (aanm) [inline pkg/policy/l4.go]: This line is unnecessary, as well all the `\n` and spaces since this function is `MarshalJSON`, not `MarshalIndent`

https://golang.org/pkg/encoding/json/#MarshalIndent

**Review by aanm — DISMISSED** [review]

File: pkg/policy/l4.go (hunk 1 above)
Comment (joestringer) [reply pkg/policy/l4.go]: Fixed.

File: pkg/policy/l4.go [hunk 2]
```diff
@@ -39,24 +40,36 @@ func (l7 L7DataMap) MarshalJSON() ([]byte, error) {
 		return []byte("[]"), nil
 	}
 
+	/* First, create a sorted slice of the selectors so we can get
+	 * consistent JSON output */
+	selectors := make(api.EndpointSelectorSlice, len(l7))
```
Comment (rlenglet) [inline pkg/policy/l4.go]: Here you create a slice of *length* `len(l7)`. You should create an empty slice of *capacity* `len(l7)`:
```
selectors := make(api.EndpointSelectorSlice, 0, len(l7))
```

I'm surprised that the tests are passing...

File: pkg/policy/l4.go [hunk 3]
```diff
@@ -39,24 +40,36 @@ func (l7 L7DataMap) MarshalJSON() ([]byte, error) {
...
+	/* Now we can iterate the slice and generate JSON entries. */
 	var err error
 	buffer := bytes.NewBufferString("[")
-	for k, v := range l7 {
-		buffer.WriteString("\n  {    \n    \"")
-		buffer.WriteString(k.LabelSelectorString())
-		buffer.WriteString("\": ")
-		b, err := json.MarshalIndent(v, "    ", "  ")
+	for _, es := range selectors {
+		if _, ok := l7[es]; !ok {
```
Comment (rlenglet) [inline pkg/policy/l4.go]: Alright, this is why the tests are passing, you're ignoring the `len(l7)` `nil` selectors that are always at the beginning of your slice. You should be able to remove this after you fix the slice creation above?

**Review by rlenglet — CHANGES_REQUESTED** [review]

File: pkg/policy/l4.go (hunk 3 above)
Comment (joestringer) [reply pkg/policy/l4.go]: Nice catch, yup! I'll fix this up.

**Comment by joestringer** [comment]
Fixed current feedback, thanks for the reviews.

**Review by rlenglet — APPROVED** [review]
