### PR TITLE
Fix typo in UpdateEC2AdapterLimitViaAPI command line flag

### LINKED ISSUE #12396: Typo in UpdateEC2AdapterLimitViaAPI command line flag
Currently the `cilium-operator-aws` command line flag is named [`update-ec2-apdater-limit-via-api`](https://github.com/cilium/cilium/blob/76df1345ad49afb48ce5a3e14ee70e99e73113f4/operator/option/config.go#L147-L149) which has a typo in `apdater` (should be `adapter`).

I suspect we should deprecate the old typo'ed flag and introduce a new one. I am not sure what is the official Cilium policy on flag deprecations (@tgraf, @aanm mind sharing some insight here?).

### PR DESCRIPTION
**Pull request by soumynathan**
This PR fixes the typo in UpdateEC2AdapterLimitViaAPI command line
flag by introducing a new command line flag and deprecating the
old command line flag.

Fixes: #12396
Signed-off-by: Swaminathan Vasudevan <svasudevan@suse.com>

### CODE REVIEW

File: operator/provider_aws_flags.go [hunk 1]
```diff
@@ -45,6 +45,9 @@ func init() {
 
 	flags.Bool(operatorOption.UpdateEC2AdapterLimitViaAPI, false, "Use the EC2 API to update the instance type to adapter limits")
 	option.BindEnv(operatorOption.UpdateEC2AdapterLimitViaAPI)
+	flags.MarkDeprecated(operatorOption.UpdateEC2AdapterLimitViaAPI, "This option has been deprecated and will be removed in v2.0")
```
Comment (tgraf) [inline operator/provider_aws_flags.go]: It's very unlikely that we will release 2.0 next ;-) Let's assume it will be 1.10.

**Review by tgraf — CHANGES_REQUESTED** [review]

File: Documentation/concepts/networking/ipam/eni.rst [hunk 2]
```diff
@@ -387,6 +387,9 @@ the cilium-operator. This allows the user to supply a custom limit.
 Additionally the limits can be updated via the EC2 API
 by passing the ``--update-ec2-apdater-limit-via-api`` CLI flag. This will require an additional EC2 IAM permission:
 
+Additionally the limits can be updated via the EC2 API v2
+by passing the ``--update-ec2-adapter-limit-via-api`` CLI flag. This will require an additional EC2 IAM permission:
+
```
Comment (tklauser) [inline Documentation/concepts/networking/ipam/eni.rst]: This is duplicating the paragraph above. I think we should change the parameter name in the "old" paragraph instead.

**Review by tklauser — CHANGES_REQUESTED** [review]

File: operator/option/config.go [hunk 3]
```diff
@@ -322,6 +330,7 @@ func (c *OperatorConfig) Populate() {
 
 	c.AWSReleaseExcessIPs = viper.GetBool(AWSReleaseExcessIPs)
 	c.UpdateEC2AdapterLimitViaAPI = viper.GetBool(UpdateEC2AdapterLimitViaAPI)
+	c.UpdateEC2AdapterLimitViaAPIv2 = viper.GetBool(UpdateEC2AdapterLimitViaAPIv2)
```
Comment (tklauser) [inline operator/option/config.go]: No need to introduce a new option `OperatorConfig.UpdateEC2AdapterLimitViaAPIv2` for this. Just assign the existing `OperatorConfig.UpdateEC2AdapterLimitViaAPI` and make the new option flag override the deprecated one in the unlikely case that both are specified.

**Review by tklauser — CHANGES_REQUESTED** [review]

File: operator/provider_aws_flags.go (hunk 1 above)
Comment (soumynathan) [reply operator/provider_aws_flags.go]: Ok, I will change it to 1.10.

File: Documentation/concepts/networking/ipam/eni.rst (hunk 2 above)
Comment (soumynathan) [reply Documentation/concepts/networking/ipam/eni.rst]: > This is duplicating the paragraph above. I think we should change the parameter name in the "old" paragraph instead.

I am not sure what you meant by 'parameter name' change.
In the new paragraph I mentioned it as 'EC2 API v2' and also the command line flag 'update-ec2-adapter-limit-via-api' is different from 'update-ec2-apdater-limit-via-api'.

What else do you think we should be able to change here. Since both denotes the same functionality other than the typo, I am not sure what else make sense here.

File: operator/option/config.go (hunk 3 above)
Comment (soumynathan) [reply operator/option/config.go]: Ok makes sense, will do.

Comment (soumynathan) [reply operator/option/config.go]: Done.

File: Documentation/concepts/networking/ipam/eni.rst (hunk 2 above)
Comment (soumynathan) [reply Documentation/concepts/networking/ipam/eni.rst]: I have made some tweaks, let me know if that would work and make sense.

File: operator/provider_aws_flags.go (hunk 1 above)
Comment (soumynathan) [reply operator/provider_aws_flags.go]: Done

File: Documentation/concepts/networking/ipam/eni.rst [hunk 4]
```diff
@@ -384,8 +384,9 @@ hardcoded in the Cilium codebase for easy out-of-the box deployment and usage.
 The limits can be modified via the ``--aws-instance-limit-mapping`` CLI flag on
 the cilium-operator. This allows the user to supply a custom limit.
 
-Additionally the limits can be updated via the EC2 API
-by passing the ``--update-ec2-apdater-limit-via-api`` CLI flag. This will require an additional EC2 IAM permission:
+Additionally the limits can be updated via the EC2 API by passing the
+``--update-ec2-apdater-limit-via-api`` or ``--update-ec2-adapter-limit-via-api`` CLI flag.
```
Comment (pchaigno) [inline Documentation/concepts/networking/ipam/eni.rst]: Do we need to document the flag with the typo?

File: operator/provider_aws_flags.go [hunk 5]
```diff
@@ -45,6 +45,9 @@ func init() {
 
 	flags.Bool(operatorOption.UpdateEC2AdapterLimitViaAPI, false, "Use the EC2 API to update the instance type to adapter limits")
 	option.BindEnv(operatorOption.UpdateEC2AdapterLimitViaAPI)
+	flags.MarkDeprecated(operatorOption.UpdateEC2AdapterLimitViaAPI, "This option has been deprecated and will be removed in v1.10")
```
Comment (pchaigno) [inline operator/provider_aws_flags.go]: It's best to point to the new flag when warning about a deprecated flag.

Comment (soumynathan) [reply operator/provider_aws_flags.go]: Sure will add a reference to the new flag.

File: Documentation/concepts/networking/ipam/eni.rst (hunk 4 above)
Comment (soumynathan) [reply Documentation/concepts/networking/ipam/eni.rst]: I thought it would be good to retain the old one, until we remove it. What do you think.

Comment (pchaigno) [reply Documentation/concepts/networking/ipam/eni.rst]: Given users shouldn't be using the old flag, I don't see a need to document it.

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
test-me-please

File: operator/option/config.go [hunk 6]
```diff
@@ -322,6 +326,7 @@ func (c *OperatorConfig) Populate() {
 
 	c.AWSReleaseExcessIPs = viper.GetBool(AWSReleaseExcessIPs)
 	c.UpdateEC2AdapterLimitViaAPI = viper.GetBool(UpdateEC2AdapterLimitViaAPI)
+	c.UpdateEC2AdapterLimitViaAPI = viper.GetBool(UpdateEC2AdapterLimitViaAPIv2)
```
Comment (aanm) [inline operator/option/config.go]: This will ignore the value set by `UpdateEC2AdapterLimitViaAPI`, in the end we want to know the value of any of both flags. Something like this:

`c.UpdateEC2AdapterLimitViaAPI = viper.GetBool(UpdateEC2AdapterLimitViaAPI) || viper.GetBool(UpdateEC2AdapterLimitViaAPIv2)`

**Review by aanm — CHANGES_REQUESTED** [review]

**Comment by qmonnet** [comment]
@soumynathan, did you have a chance to address the feedback from André and to rebase this PR? Looks like there's not much left to do to put this to a good shape?

**Comment by soumynathan** [comment]
> @soumynathan, did you have a chance to address the feedback from André and to rebase this PR? Looks like there's not much left to do to put this to a good shape?

Sure will rebase and address the review comments.

**Comment by soumynathan** [comment]
Addressed review comments.

File: operator/option/config.go [hunk 7]
```diff
@@ -132,6 +132,10 @@ const (
 	// API to fill out the instancetype to adapter limit mapping.
 	UpdateEC2AdapterLimitViaAPI = "update-ec2-apdater-limit-via-api"
 
+	// UpdateEC2AdapterLimitViaAPIv2 configures the operator to use the EC2
+	// API to fill out the instancetype to adapter limit mapping.
+	UpdateEC2AdapterLimitViaAPIv2 = "update-ec2-adapter-limit-via-api"
+
```
Comment (tklauser) [inline operator/option/config.go]: I'd rename this const and re-use the name for the "new option" to better reflect that the misspelled option is deprecated and so we don't forget to remove it in 1.10:
```suggestion
	UpdateEC2AdapterLimitViaAPIDeprecated = "update-ec2-apdater-limit-via-api"

	// UpdateEC2AdapterLimitViaAPI configures the operator to use the EC2
	// API to fill out the instancetype to adapter limit mapping.
	UpdateEC2AdapterLimitViaAPI = "update-ec2-adapter-limit-via-api"

```

File: operator/option/config.go [hunk 8]
```diff
@@ -335,7 +339,8 @@ func (c *OperatorConfig) Populate() {
 	// AWS options
 
 	c.AWSReleaseExcessIPs = viper.GetBool(AWSReleaseExcessIPs)
-	c.UpdateEC2AdapterLimitViaAPI = viper.GetBool(UpdateEC2AdapterLimitViaAPI)
+	c.UpdateEC2AdapterLimitViaAPI = viper.GetBool(UpdateEC2AdapterLimitViaAPI) ||
+		viper.GetBool(UpdateEC2AdapterLimitViaAPIv2)
```
Comment (tklauser) [inline operator/option/config.go]: Given the above change, this would then be:
```suggestion
	c.UpdateEC2AdapterLimitViaAPI = viper.GetBool(UpdateEC2AdapterLimitViaAPIDeprecated) ||
		viper.GetBool(UpdateEC2AdapterLimitViaAPI)
```

File: operator/provider_aws_flags.go [hunk 9]
```diff
@@ -43,8 +45,11 @@ func init() {
 		operatorOption.ENITags, "ENI tags in the form of k1=v1 (multiple k/v pairs can be passed by repeating the CLI flag)")
 	option.BindEnv(operatorOption.ENITags)
 
-	flags.Bool(operatorOption.UpdateEC2AdapterLimitViaAPI, false, "Use the EC2 API to update the instance type to adapter limits")
+	flags.Bool(operatorOption.UpdateEC2AdapterLimitViaAPI, false, fmt.Sprintf("Use the EC2 API to update the instance type to adapter limits. Deprecated in favor of %s", operatorOption.UpdateEC2AdapterLimitViaAPIv2))
 	option.BindEnv(operatorOption.UpdateEC2AdapterLimitViaAPI)
+	flags.MarkDeprecated(operatorOption.UpdateEC2AdapterLimitViaAPI, "This option will be removed in v1.10")
+	flags.Bool(operatorOption.UpdateEC2AdapterLimitViaAPIv2, false, "Use the EC2 API to update the instance type to adapter limits")
+	option.BindEnv(operatorOption.UpdateEC2AdapterLimitViaAPIv2)
```
Comment (tklauser) [inline operator/provider_aws_flags.go]: And here:
```suggestion
	flags.Bool(operatorOption.UpdateEC2AdapterLimitViaAPIDeprecated, false, fmt.Sprintf("Use the EC2 API to update the instance type to adapter limits. Deprecated in favor of %s", operatorOption.UpdateEC2AdapterLimitViaAPI))
	option.BindEnv(operatorOption.UpdateEC2AdapterLimitViaAPIDeprecated)
	flags.MarkDeprecated(operatorOption.UpdateEC2AdapterLimitViaAPIDeprecated, "This option will be removed in v1.10")
	flags.Bool(operatorOption.UpdateEC2AdapterLimitViaAPI, false, "Use the EC2 API to update the instance type to adapter limits")
	option.BindEnv(operatorOption.UpdateEC2AdapterLimitViaAPI)
```

**Review by tklauser — APPROVED** [review]
One suggestion regarding `const` naming, otherwise LGTM.

**Review by aanm — APPROVED** [review]
LGTM besides what Tobias mentioned

**Review by joestringer — CHANGES_REQUESTED** [review]
I see outstanding feedback that is requested, but it's unclear that it should be addressed because the Github UI does not reflect that changes were requested. Marking request changes to address the above feedback, once it's addressed feel free to re-request my (or other) reviewers' feedback to move this forward.

File: operator/option/config.go (hunk 6 above)
Comment (soumynathan) [reply operator/option/config.go]: Let me push a new version.

File: operator/provider_aws_flags.go (hunk 9 above)
Comment (soumynathan) [reply operator/provider_aws_flags.go]: Will address your review comments.

Comment (soumynathan) [reply operator/provider_aws_flags.go]: Addressed review comments.

**Comment by soumynathan** [comment]
> I see outstanding feedback that is requested, but it's unclear that it should be addressed because the Github UI does not reflect that changes were requested. Marking request changes to address the above feedback, once it's addressed feel free to re-request my (or other) reviewers' feedback to move this forward.

Addressed review comments.

**Comment by tklauser** [comment]
retest-net-next

**Comment by tklauser** [comment]
retest-4.19

**Review by tklauser — APPROVED** [review]
