### PR TITLE
pkg/k8s: Synchronize heartbeat goroutine

### LINKED ISSUE #39428: CI: Test_clientMultipleAPIServers failure
```
--- FAIL: Test_clientMultipleAPIServers (0.02s)

    logger.go:256: time=2025-05-08T09:29:25.742Z level=INFO source=/home/runner/work/cilium/cilium/pkg/k8s/client/restConfig_provider.go:274 msg="Rotated api server" module=k8s-client url=http://127.0.0.1:33993/
    logger.go:256: time=2025-05-08T09:29:25.746Z level=INFO source=/home/runner/work/cilium/cilium/vendor/github.com/cilium/hive/hive.go:357 msg="Starting hive"
    logger.go:256: time=2025-05-08T09:29:25.746Z level=INFO source=/home/runner/work/cilium/cilium/pkg/k8s/client/cell.go:317 msg="Establishing connection to apiserver" module=k8s-client ipAddr=http://127.0.0.1:33993/
    logger.go:256: time=2025-05-08T09:29:25.748Z level=INFO source=/home/runner/work/cilium/cilium/pkg/k8s/client/cell.go:344 msg="Connected to apiserver" module=k8s-client
    logger.go:256: time=2025-05-08T09:29:25.749Z level=INFO source=/home/runner/work/cilium/cilium/vendor/github.com/cilium/hive/hive.go:361 msg="Started hive" duration=3.055708ms
    logger.go:256: time=2025-05-08T09:29:25.756Z level=WARN source=/home/runner/work/cilium/cilium/pkg/k8s/client/cell.go:399 msg="Heartbeat timed out, restarting client connections" module=k8s-client
    logger.go:256: time=2025-05-08T09:29:25.760Z level=INFO source=/home/runner/work/cilium/cilium/pkg/k8s/client/restConfig_provider.go:274 msg="Rotated api server" module=k8s-client url=http://127.0.0.1:40725/
    client_test.go:337: 
        	Error Trace:	/home/runner/work/cilium/cilium/pkg/k8s/client/client_test.go:337
        	Error:      	Received unexpected error:
        	            	Get "http://127.0.0.1:40725/api/v1/namespaces/test/pods/slim-pod": dial tcp 127.0.0.1:40725: connect: connection refused
        	Test:       	Test_clientMultipleAPIServers
```

https://github.com/cilium/cilium/actions/runs/14903032174/job/41859123372

Seen on https://github.com/cilium/cilium/pull/39426

/cc @cilium/sig-k8s @aditighag

### PR DESCRIPTION
**Pull request by aditighag**
When the heartbeat timeout is set to a low value (e.g., in tests), there's a risk that the goroutine responsible for sending heartbeat probes may not start before the timeout expires. To address this, introduce a channel to synchronize goroutine startup.

A WaitGroup could also be used, but it risks blocking the controller indefinitely if the goroutine fails to start or blocks on I/O.

Fixes: https://github.com/cilium/cilium/issues/39428

### CODE REVIEW

**Comment by aditighag** [comment]
Ran all the tests in the file 100 times locally without any issue.

File: pkg/k8s/client/cell.go [hunk 1]
```diff
@@ -367,10 +367,15 @@ func runHeartbeat(logger *slog.Logger, heartBeat func(context.Context) error, ti
...
+		ctx    context.Context
+		cancel context.CancelFunc
+	)
+	start := make(chan struct{})
 	done := make(chan error)
-	ctx, cancel := context.WithTimeout(context.Background(), timeout)
-	defer cancel()
 	go func() {
+		ctx, cancel = context.WithTimeout(context.Background(), timeout)
+		start <- struct{}{}
```
Comment (marseel) [inline pkg/k8s/client/cell.go]: As far as I can see, `K8sHeartbeatTimeout` is set to `5ms` in that test. 
This also controls how often heartbeat is executed here: https://github.com/cilium/cilium/blob/afcb0c986df5b45d0037cc768c7da4f5ecc367ab/pkg/k8s/client/cell.go#L306
Client-go rate-limits number of requests to external server, be default we have 10 qps / 20 burst. 
I've checked that with:
```
	t.Log(clientset.Config().K8sClientQPS)
	t.Log(clientset.Config().K8sClientBurst)
```
in the test.
That means, if test runs for ~200-300 ms, we saturate limit from heartbeat and all consecutive calls are throttled, resulting in timeouts in heartbeat. 
This can be easily simulated by adding `time.Sleep(10 * time.Second)` after `hive.Start` here: https://github.com/cilium/cilium/blob/2b754de5808a29fee75d93a8ac7d5a5e97c34141/pkg/k8s/client/client_test.go#L323 and the test fails reliably.

I would propose to change `K8sHeartbeatTimeout` in the test from `5ms` to `150ms` instead (so 10 QPS can be sustained), or just increase client-go rate limits :)

**Review by marseel — CHANGES_REQUESTED** [review]

**Comment by marseel** [comment]
> Ran all the tests in the file 100 times locally without any issue.

FYI, I ran your patch with that sleep(10s) in the test and it also failed.

File: pkg/k8s/client/cell.go (hunk 1 above)
Comment (aditighag) [reply pkg/k8s/client/cell.go]: >This can be easily simulated by adding time.Sleep(10 * time.Second) after hive.Start here:

Well spotted! 
~I noticed that this particular test has a bunch of different values set for heart beat timeout, and as a result corresponding asserts. 
I'm hoping we can transition to synctest once it's available as a follow-up.~

Edit: <errnocoffee> Nvm, I mixed this up with the other test case. 

For now, I'll increase the QPS as the test case is supposed to exercise mainly time aspect of the heartbeat testing logic.

Comment (aditighag) [reply pkg/k8s/client/cell.go]: Done! Added an artificial delay of 10s, and wasn't able to reproduce the issue caused due to throttling.

Comment (marseel) [reply pkg/k8s/client/cell.go]: Two more nits:
I see you've added `flags.Set(option.K8sHeartbeatTimeout, "150ms")` in one test, which contradicts
`For now, I'll increase the QPS as the test case is supposed to exercise mainly time aspect of the heartbeat testing logic.`. Just want to make sure this is what you wanted :) I'm fine with that change either way. 

I do not think that your previous change helps though, I would remove it - groutine was most likely starting, it was just waiting on response. `start <- struct{}{}` can preempt go-routine anyway as it's blocking operation and channel is non-buffered - depending on execution order of inner and outer goroutines. It doesn't break anything either, but it just makes code a bit harder to read/understand.

**Review by marseel — APPROVED** [review]

**Comment by joestringer** [comment]
Added the `dont-merge/discussion` label due to the ongoing discussion. Feel free to drop the label once that is resolved.

File: pkg/k8s/client/cell.go (hunk 1 above)
Comment (aditighag) [reply pkg/k8s/client/cell.go]: Oh! I had edited the previous note after pushing the last revision of changes, but somehow I don't see the edits. 😕 
Anyway, yes, I decided to bump up the heart beat timeout as well to prevent any further flakes. 
I had also commented saying that I would keep the first commit as the main thread *should* block on the goroutine sending heart beat probes. Also, notice that earlier the context timeout was started outside of the goroutine. I don't have a strong preference about the channel based synchronization, but I think we should at least start the timeout when the goroutine runs. We could also make the channel buffered with capacity 1 to avoid getting the goroutine preempted by the schedular. 

Edit: I thought more about this -- we can merge the 2nd commit bumping up QPS and heartbeat timeout and see how that plays out, and drop the 1st commit. It's less likely that go routine scheduler delay would cause such failures in production environments.

Comment (marseel) [reply pkg/k8s/client/cell.go]: > Edit: I thought more about this -- we can merge the 2nd commit bumping up QPS and heartbeat timeout and see how that plays out, and drop the 1st commit. It's less likely that go routine scheduler delay would cause such failures in production environments.

yea, fully agree. if scheduler takes more than couple of ms then there are probably other problems already, but still it wouldn't affect production due to higher timeout. 
I guess you might want to increase heartbeat timeout for `Test_client` test as well?
