### PR TITLE
Fix agent deadlock caused by frequent kube-apiserver IP recycling

### LINKED ISSUE #21596: Agent stops responding
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Periodically agents stop responding until restarted. Pod sandboxes cannot be created, endpoint regeneration stops, etc.

Sometimes after being restarted, it gets restarted _again_ by the liveness probe. The last lines in the log before liveness restart:
```
level=info msg="regenerating all endpoints" reason= subsys=endpoint-manager
level=info msg="Exiting due to signal" signal=terminated subsys=daemon
level=error msg="Failed to start the udp DNS proxy on [::]:41491" error="read udp [::]:41491: use of closed network connection" subsys=fqdn/dnsproxy
level=error msg="Failed to start the tcp DNS proxy on [::]:41491" error="accept tcp [::]:41491: use of closed network connection" subsys=fqdn/dnsproxy
level=info msg="Waiting for all endpoints' go routines to be stopped." subsys=daemon
level=info msg="All endpoints' goroutines stopped." subsys=daemon
```

`cilium status` works, but commands like `cilium endpoint list` result in `Cilium API client timeout exceeded` too

### Cilium Version

`Daemon: 1.12.2 c7516b9 2022-09-14T15:25:06+02:00 go version go1.18.6 linux/amd64`

### Kernel Version

`Linux ip-10-199-23-150 5.15.0-1019-aws #23~20.04.1-Ubuntu SMP Thu Aug 18 03:20:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

`Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.13-eks-15b7512", GitCommit:"94138dfbea757d7aaf3b205419578ef186dd5efb", GitTreeState:"clean", BuildDate:"2022-08-31T19:15:48Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}`

### Sysdump

[cilium-stack-2022-10-05.tar.gz](https://github.com/cilium/cilium/files/9717902/cilium-stack-2022-10-05.tar.gz)

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by joestringer**
A user reports the following deadlock in with lock chain[^1] and
lock chain[^2].

Lock chain 2 is at a high level trying to implement the new network
policy for an endpoint. As part of this step, it calculates a new
policy, then attempts to switch the policy pointer over to the new
policy, and then garbage collect references & objects in the old policy.
When garbage collecting the old policy objects, it is going into the
selectorcache and identifying that certain identities are no longer used
by the selector and cleaning up those identities. Hence we end up in the
ReleaseCIDRIdentitiesByID() call and attempting to grab the ipcache
lock.

Commit 40e13ea attempted to mitigate a bug where interleaved ordering of
identity reference counting and ipcache updates could lead to
inconsistent internal state (=> packet drops), but the core idea there
was that these two operations (identity refcount update + ipcache
update) must happen together in the same critical section, but the exact
timing when these two operations occur is not particularly important. I
think they should happen in a canonical order, but when that order is
iterated is not critical. Given that overall agent state is eventually
consistent, cleanup of these ipcache entries can happen at any
subsequent time. The sooner the better for sure, but I don't think that
there are any hard constraints on this.

If lock chain 2 was not holding the endpoint lock while releasing these
resources, then this deadlock would not occur. So, this commit proposes
to add a new queue + GC goroutine in the ipcache that handles the
release of these CIDR identities out-of-band so that they can be cleaned
up while not holding the endpoint lock. Then, from the endpoint policy
generation perspective it can continue with the remaining endpoint
policy calculation / datapath updates, return, and then that will allow
lock chain 1 to proceed since it's waiting for all endpoints to
regenerate their policies, then once that completes & unlocks the lock,
this new dedicated goroutine can do this cleanup.

[1]: Lock chain 1: ipc.Lock() -> e.lockAlive()
     When removeLabelsFromIPs is triggered through an EP change, it performs
     ipc.Lock() first, then collects information about added/deleted
     identities in a loop and then calls ipc.UpdatePolicyMaps(...), which
     then calls UpdatePolicyMaps(...) from the EndpointManager. The call
     stack of this is:

    ```
    goroutine 237 [semacquire, 417 minutes]:
    sync.runtime_Semacquire(0xc00038d880?)
            /usr/local/go/src/runtime/sema.go:56 +0x25
    sync.(*WaitGroup).Wait(0xc000398700?)
            /usr/local/go/src/sync/waitgroup.go:136 +0x52
    github.com/cilium/cilium/pkg/ipcache.(*IPCache).UpdatePolicyMaps(0xc00083c980, {0x3461140, 0xc000128008}, 0xc?, 0xc0024410e0)
            /go/src/github.com/cilium/cilium/pkg/ipcache/metadata.go:235 +0xc7
    github.com/cilium/cilium/pkg/ipcache.(*IPCache).removeLabelsFromIPs(0xc00083c980, 0xc0013d5778?, {0x2f2a9f6, 0xf})
            /go/src/github.com/cilium/cilium/pkg/ipcache/metadata.go:414 +0x7c5
    github.com/cilium/cilium/pkg/ipcache.(*IPCache).RemoveLabelsExcluded(0xc00083c980, 0xc0000d5c50, 0xc000bf41d8?, {0x2f2a9f6, 0xf})
            /go/src/github.com/cilium/cilium/pkg/ipcache/metadata.go:328 +0x1ab
    github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).handleKubeAPIServerServiceEPChanges(0xc000a91d40, 0xc001a739b0?)
            /go/src/github.com/cilium/cilium/pkg/k8s/watchers/endpoint.go:135 +0x5b
    github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).addKubeAPIServerServiceEPSliceV1(0x1861426?, 0xc0020f2c30)
            /go/src/github.com/cilium/cilium/pkg/k8s/watchers/endpoint_slice.go:205 +0x452
    github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).updateK8sEndpointSliceV1(0xc000a91d40, 0xc0020f2c30?, 0xc0020f2c30?)
            /go/src/github.com/cilium/cilium/pkg/k8s/watchers/endpoint_slice.go:178 +0x69
    github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).endpointSlicesInit.func2({0x2ebcec0?, 0xc0020f3a00?}, {0x2ebcec0, 0xc0020f2c30})
            /go/src/github.com/cilium/cilium/pkg/k8s/watchers/endpoint_slice.go:71 +0x125
    k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
            /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:239
    github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1({0x2a48d00?, 0xc000a9b5f0?})
            /go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:103 +0x2fe
    k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc000c5a960, 0xc00013b240)
            /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:554 +0x566
    k8s.io/client-go/tools/cache.(*controller).processLoop(0xc000eff710)
            /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:184 +0x36
    k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x40d645?)
            /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x3e
    k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x102fe25?, {0x3436f20, 0xc000b54b10}, 0x1, 0xc0005e06c0)
            /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
    k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000eff778?, 0x3b9aca00, 0x0, 0x40?, 0x7f72ce949c00?)
            /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
    k8s.io/apimachinery/pkg/util/wait.Until(...)
            /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
    k8s.io/client-go/tools/cache.(*controller).Run(0xc000eff710, 0xc0005e06c0)
            /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:155 +0x2c5
    created by github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).endpointSlicesInit
            /go/src/github.com/cilium/cilium/pkg/k8s/watchers/endpoint_slice.go:156 +0x759
    UpdatePolicyMaps will then start a goroutine for each EP and just return a WaitGroup, so that the caller can wait on it. The goroutines then end up in calling locking the EP lock via lockAlive().
    ```

[2]: Lock chain 2: e.lockAlive() -> ipc.Lock()
     If at the same time a EndpointRegenerationEvent is handled, it
     might end up locking the Endpoint locks first and then (through
     a quite deep stack) end up calling ipc.Lock() in
     IPCache.releaseCIDRIdentities(), which will then cause a
     deadlock. The stack trace looks like this:

    ```
    goroutine 455 [select, 417 minutes]:
    golang.org/x/sync/semaphore.(*Weighted).Acquire(0xc000842050, {0x3461140, 0xc000128000}, 0x40000000)
            /go/src/github.com/cilium/cilium/vendor/golang.org/x/sync/semaphore/semaphore.go:60 +0x345
    github.com/cilium/cilium/pkg/lock.(*SemaphoredMutex).Lock(...)
            /go/src/github.com/cilium/cilium/pkg/lock/semaphored_mutex.go:30
    github.com/cilium/cilium/pkg/ipcache.(*IPCache).Lock(...)
            /go/src/github.com/cilium/cilium/pkg/ipcache/ipcache.go:121
    github.com/cilium/cilium/pkg/ipcache.(*IPCache).releaseCIDRIdentities(0xc00083c980, {0x3461178, 0xc000445680}, 0x0?)
            /go/src/github.com/cilium/cilium/pkg/ipcache/cidr.go:203 +0x85
    github.com/cilium/cilium/pkg/ipcache.(*IPCache).ReleaseCIDRIdentitiesByID(0xc00083c980, {0x3461178, 0xc000445680}, {0x0, 0x0, 0x1bf08eb000?})
            /go/src/github.com/cilium/cilium/pkg/ipcache/cidr.go:265 +0x497
    github.com/cilium/cilium/daemon/cmd.cachingIdentityAllocator.ReleaseCIDRIdentitiesByID(...)
            /go/src/github.com/cilium/cilium/daemon/cmd/identity.go:118
    github.com/cilium/cilium/pkg/policy.(*SelectorCache).releaseIdentityMappings(0xc000398700, {0x0, 0x0, 0x0})
            /go/src/github.com/cilium/cilium/pkg/policy/selectorcache.go:556 +0x9d
    github.com/cilium/cilium/pkg/policy.(*SelectorCache).RemoveSelectors(0xc000398700, {0xc001a00210, 0x1, 0x0?}, {0x3429f40, 0xc003d42600})
            /go/src/github.com/cilium/cilium/pkg/policy/selectorcache.go:961 +0xc5
    github.com/cilium/cilium/pkg/policy.(*L4Filter).removeSelectors(0xc003d42600, 0xc001c02518?)
            /go/src/github.com/cilium/cilium/pkg/policy/l4.go:627 +0x185
    github.com/cilium/cilium/pkg/policy.(*L4Filter).detach(0xb?, 0x0?)
            /go/src/github.com/cilium/cilium/pkg/policy/l4.go:634 +0x1e
    github.com/cilium/cilium/pkg/policy.L4PolicyMap.Detach(...)
            /go/src/github.com/cilium/cilium/pkg/policy/l4.go:804
    github.com/cilium/cilium/pkg/policy.(*L4Policy).Detach(0xc0048b0180, 0x1?)
            /go/src/github.com/cilium/cilium/pkg/policy/l4.go:1013 +0x7b
    github.com/cilium/cilium/pkg/policy.(*selectorPolicy).Detach(...)
            /go/src/github.com/cilium/cilium/pkg/policy/resolve.go:104
    github.com/cilium/cilium/pkg/policy.(*cachedSelectorPolicy).setPolicy(0xc000398770?, 0xc000c275c0?)
            /go/src/github.com/cilium/cilium/pkg/policy/distillery.go:188 +0x3b
    github.com/cilium/cilium/pkg/policy.(*PolicyCache).updateSelectorPolicy(0xc00098a090, 0xc000c275c0)
            /go/src/github.com/cilium/cilium/pkg/policy/distillery.go:124 +0x195
    github.com/cilium/cilium/pkg/policy.(*PolicyCache).UpdatePolicy(...)
            /go/src/github.com/cilium/cilium/pkg/policy/distillery.go:153
    github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regeneratePolicy(0xc000e47c00)
            /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:230 +0x22b
    github.com/cilium/cilium/pkg/endpoint.(*Endpoint).runPreCompilationSteps(0xc000e47c00, 0xc0015cf400)
            /go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:809 +0x2c5
    github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF(0xc000e47c00, 0xc0015cf400)
            /go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:579 +0x189
    github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc000e47c00, 0xc0015cf400)
            /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:398 +0x7a5
    github.com/cilium/cilium/pkg/endpoint.(*EndpointRegenerationEvent).Handle(0xc005584d10, 0xc0003dae80?)
            /go/src/github.com/cilium/cilium/pkg/endpoint/events.go:53 +0x325
    github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).run.func1()
            /go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:245 +0x13b
    sync.(*Once).doSlow(0x1?, 0x442205?)
            /usr/local/go/src/sync/once.go:68 +0xc2
    sync.(*Once).Do(...)
            /usr/local/go/src/sync/once.go:59
    github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).run(0x0?)
            /go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:233 +0x45
    created by github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Run
            /go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:229 +0x76
    ```

Thanks to John Watson (@dctrwatson), Alexander Block (@codablock), and Chris Tarazi (@christarazi) for their
reports and assistance in digging to the bottom of this issue.

Fixes: 40e13ea2a5a9 ("ipcache: Fix race in identity/ipcache release")
Fixes: #20721
Fixes: #21596

### CODE REVIEW

File: pkg/ipcache/gc.go [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+				option.Config.KVstoreConnectivityTimeout)
+			defer cancel()
+			result.run(ctx, parent, reasons...)
+		},
+	})
+
+	return result
+}
+
+func (pr *asyncPrefixReleaser) add(reason string, prefixes []netip.Prefix) {
```
Comment (christarazi) [inline pkg/ipcache/gc.go]: Nit: When reading the calling code, it wasn't obvious to me at first that this was the actual trigger. Maybe rename to `trigger`? I don't feel strongly about this however.

Comment (christarazi) [reply pkg/ipcache/gc.go]: Also another nit, if you decide the rename make sense, then I think re-ordering the parameters with the `reason` coming last makes more sense as it aligns with other trigger calls throughout the code base like `TriggerPolicyUpdates` for example. Again, don't feel strongly.

**Review by christarazi — APPROVED** [review]

File: pkg/ipcache/gc.go (hunk 1 above)
Comment (joestringer) [reply pkg/ipcache/gc.go]: :+1: maybe `enqueue` and `dequeue` makes sense. There's already a trigger underneath so I think it'll be confusing to call two different things `trigger`.

**Comment by joestringer** [comment]
All tests passed except for the [multicluster test](https://github.com/cilium/cilium/actions/runs/3207508785) which is known unreliable and not marked as required.
