### PR TITLE
envoy: Fix too many open Unix sockets

### LINKED ISSUE #33542: Cilium 1.15 too many open unix sockets
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium agent and envoy use so many open unix sockets and it increases overtime. It is because of envoy as restarting envoy fix it. It is visible on both containers because of privileged mode probably.

```
wc -l /proc/net/* | sort -h
...
...
...
    173 /proc/net/tcp
   1246 /proc/net/nf_conntrack
  12144 /proc/net/unix
```

And different cluster incl. screenshot
```
    199 /proc/net/tcp
    738 /proc/net/unix
   1573 /proc/net/nf_conntrack
```
Snímek obrazovky 2024-07-02 v 22 24 55

### Cilium Version

1.15.5
1.15.4

### Kernel Version

Linux app-worker-dev-d556f601-qfnnq 5.14.0-427.18.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Tue May 28 06:27:02 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.28.10+rke2r1

### Regression

I don't know

### Sysdump

File size too big. Please let me know how should I proceed.

### Relevant log output

```shell
Haven't found anything interesting  in logs
```

### Anything else?
A lot of the unix sockets are `/var/run/cilium/envoy/sockets/admin.sock`

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by chaunceyjiang**
Fixes: #33542

```release-note
Fix too many open Unix sockets
```

### CODE REVIEW

File: pkg/envoy/envoyadminclient.go [hunk 1]
```diff
@@ -33,16 +33,22 @@ func NewEnvoyAdminClientForSocket(envoySocketDir string) *EnvoyAdminClient {
...
+	var err error
 	client := &http.Client{
 		Transport: &http.Transport{
-			DialContext: func(_ context.Context, _, _ string) (net.Conn, error) { return net.Dial("unix", a.unixPath) },
+			DialContext: func(_ context.Context, _, _ string) (net.Conn, error) {
+				conn, err = net.Dial("unix", a.unixPath)
+				return conn, err
+			},
 		},
 	}
```
Comment (aanm) [inline pkg/envoy/envoyadminclient.go:46]: Shouldn't we do the `defer conn.Close()` here so that it's also closed in case of error on line 49?

File: pkg/envoy/envoyadminclient.go [hunk 2]
```diff
@@ -78,16 +84,22 @@ func (a *EnvoyAdminClient) quit() error {
...
 
 	resp, err := client.Get(fmt.Sprintf("%s%s", a.adminURL, "server_info"))
```
Comment (aanm) [inline pkg/envoy/envoyadminclient.go:98]: same question for here.

**Review by aanm — CHANGES_REQUESTED** [review]

File: pkg/envoy/envoyadminclient.go (hunk 1 above)
Comment (chaunceyjiang) [reply pkg/envoy/envoyadminclient.go:46]: No, because at this point `conn` has not been initialized yet. Only after calling Post/Get will `conn` have a value.

**Comment by chaunceyjiang** [comment]
``` shell
# while true; do cat /proc/net/unix |grep admin|wc -l; date; sleep 5; done
....
27
Thu Jul  4 02:49:44 UTC 2024
27
Thu Jul  4 02:49:49 UTC 2024
27
Thu Jul  4 02:49:54 UTC 2024
27
Thu Jul  4 02:49:59 UTC 2024
27
Thu Jul  4 02:50:04 UTC 2024
27
Thu Jul  4 02:50:09 UTC 2024
27
Thu Jul  4 02:50:14 UTC 2024
27
Thu Jul  4 02:50:19 UTC 2024
27
Thu Jul  4 02:50:24 UTC 2024
27
Thu Jul  4 02:50:29 UTC 2024
27
Thu Jul  4 02:50:34 UTC 2024
27
Thu Jul  4 02:50:39 UTC 2024
27
Thu Jul  4 02:50:44 UTC 2024
27
Thu Jul  4 02:50:49 UTC 2024
27
Thu Jul  4 02:50:54 UTC 2024
27
Thu Jul  4 02:50:59 UTC 2024
27
Thu Jul  4 02:51:04 UTC 2024
27
Thu Jul  4 02:51:09 UTC 2024
27
Thu Jul  4 02:51:14 UTC 2024
27
Thu Jul  4 02:51:19 UTC 2024
27
Thu Jul  4 02:51:24 UTC 2024
27
Thu Jul  4 02:51:29 UTC 2024
27
Thu Jul  4 02:51:34 UTC 2024

```


After running stably in my local environment for 10 hours, the number of connections to `admin.sock` remains stable and does not continue to increase.

**Review by aanm — APPROVED** [review]

**Review by sayboras — APPROVED** [review]
Thanks a ton :1st_place_medal:
