### PR TITLE
hubble/relay: fix warning about missing config file

### LINKED ISSUE #13104: Warning while installing hubble-relay
```
./hubble-relay completion bash > hubble-relay_bash_completion
level=warning msg="Failed to read config from file '/etc/hubble-relay/config.yaml'" error="open /etc/hubble-relay/config.yaml: no such file or directory" subsys=hubble-relay
install -m 0644 -T hubble-relay_bash_completion /etc/bash_completion.d/hubble-relay
```

### PR DESCRIPTION
**Pull request by kaworu**
Before this patch, hubble-relay would complain when its config file was missing. This patch make it so the error message is only shown at the debug level.

Before this patch:
```
% ./hubble-relay version
level=warning msg="Failed to read config from file '/etc/hubble-relay/config.yaml'" error="open /etc/hubble-relay/config.yaml: no such file or directory" subsys=hubble-relay
Hubble-relay: 1.8.90 b13dcfb3f 2020-08-21T15:53:46+05:30 go version go1.15 linux/amd64
```
After this patch:
```
% ./hubble-relay version
Hubble-relay: 1.8.90 6c4963ab6 2020-09-07T19:07:01+02:00 go version go1.15 linux/amd64
```
and
```
% ./hubble-relay version --debug
level=debug msg="os.Hostname() returned" nodeName=shelob subsys=node
level=debug msg="Failed to read config from file '/etc/hubble-relay/config.yaml'" error="open /etc/hubble-relay/config.yaml: no such file or directory" subsys=hubble-relay
Hubble-relay: 1.8.90 6c4963ab6 2020-09-07T19:07:01+02:00 go version go1.15 linux/amd64
% RELAY_DEBUG=true ./hubble-relay version
level=debug msg="Failed to read config from file '/etc/hubble-relay/config.yaml'" error="open /etc/hubble-relay/config.yaml: no such file or directory" subsys=hubble-relay
Hubble-relay: 1.8.90 6c4963ab6 2020-09-07T19:07:01+02:00 go version go1.15 linux/amd64
```

Fixes #13104

### CODE REVIEW

**Review by aanm — APPROVED** [review]
Thanks! The `ReadInConfig` should be done similarly to what is done for Cilium / Cilium operator, i.e., mount each config map option as files inside the pod. https://github.com/cilium/cilium/pull/12900#pullrequestreview-482920057

**Review by sayboras — APPROVED** [review]

**Review by kkourt — APPROVED** [review]

**Comment by kAworu** [comment]
Updated: One strange thing with this patch was that setting the `debug` flag from the config file would not affect the logging level (because we check this before `ReadInConfig()`). I don't see a better way than checking for `viper.GetBool("debug")` a second time and setting the log level accordingly.

**Comment by gandro** [comment]
> Thanks! The `ReadInConfig` should be done similarly to what is done for Cilium / Cilium operator, i.e., mount each config map option as files inside the pod. [#12900 (review)](https://github.com/cilium/cilium/pull/12900#pullrequestreview-482920057)

Since #12900 we are actually reading in the configmap as a file:

https://github.com/cilium/cilium/blob/6f7fb6cd349d18bf86300c923dda49d2f263c8d5/install/kubernetes/cilium/charts/hubble-relay/templates/deployment.yaml#L59-L61

Is there anything else you had in mind?

File: hubble-relay/cmd/root.go [hunk 1]
```diff
@@ -40,9 +41,27 @@ func New() *cobra.Command {
...
+
+	// We need to check for the debug environment variable or CLI flag before
+	// loading the configuration file since on configuration file read failure
+	// we will emit a debug log entry.
+	if vp.GetBool("debug") {
+		logging.SetLogLevel(logrus.DebugLevel)
+	}
 	if err := vp.ReadInConfig(); err != nil {
-		logger.WithError(err).Warnf("Failed to read config from file '%s'", configFilePath)
+		logger.WithError(err).Debugf("Failed to read config from file '%s'", configFilePath)
```
Comment (gandro) [inline hubble-relay/cmd/root.go:55]: I would prefer at least `Info` level. Because in a real deployment done using our Helm charts, the config file should always be present. So if the config file is absent, this likely indicates a deployment problem and the user should be able to see this message without enabling debug.

**Review by aanm — APPROVED** [review]

File: hubble-relay/cmd/root.go (hunk 1 above)
Comment (kaworu) [reply hubble-relay/cmd/root.go:55]: That's fair. The issue is that then we're back to square one where any `./hubble-relay version` or `hubble-relay completion bash` will display this log entry right?

Comment (gandro) [reply hubble-relay/cmd/root.go:55]: Ah, I did not realize that complication. I guess we could check if `vp.ConfigFileUsed()` existed in `runServe`, but that would still not catch all possible errors (such as permission problems). Let's keep this PR as is then!

**Review by gandro — APPROVED** [review]

**Comment by kAworu** [comment]
test-me-please
