### PR TITLE
bpf: adding a special case for service loopback IPv6 during icmp routing

### LINKED ISSUE #42460: Service loopback fails because of ip used for service loopback (fe80::1)
### Version

equal or higher than v1.18.3 and lower than v1.19.0

### What happened?

Service loopback support for IPv6 was introduced by this [pr](https://github.com/cilium/cilium/pull/39594), in which service loopback address is set to fe80::1. 

Unfortunately, while I was working on the follow-up pr for connectivity tests for service loopback, I found neighbor discovery issues for fe80::1 (IMO, fe80::1 has limited scope and routing capabilities). See the logs below.

When I change the service loopback address to ULA (e.g fd00::1), the service loopback works properly. So, I think fe80::1 is the problem.

### Possible Solutions
1. Change the address to ULA or change it to routable LLA for neighbor discovery. I have confirmed this by changing to ULA as mentioned above.

2. If we keep using fe80::1, ensure it's properly configured on the node's routing interface and neighbor discovery is working. I think this can be done in `ipam_infra_ip_allocation.go`. (But, I am not sure about this).

### How can we reproduce the issue?

1. Create a pod and ipv6 service and test. Check flow logs.

### Cilium Version

dev version (compiled from source)

### Kernel Version

6.17.5-arch1-1

### Kubernetes Version

1.34.1

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell
k exec -ti -n kube-system cilium-lqmb6 -- cilium monitor --related-to 287
Listening for events on 8 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
time=2025-10-29T06:13:08.518438799Z level=info msg="Initializing dissection cache..."
<- endpoint 287 flow 0x9011f821 , identity 48569->unknown state unknown ifindex 0 orig-ip ::: [fd00:10:244:1::7bcf]:53478 -> [fd00:10:96::112f]:80 tcp SYN
-> endpoint 287 flow 0x9011f821 , identity 48569->48569 state new ifindex lxc7b070451d820 orig-ip fe80::1: [fe80::1]:53478 -> [fd00:10:244:1::7bcf]:80 tcp SYN
<- endpoint 287 flow 0x0 , identity 48569->unknown state unknown ifindex 0 orig-ip ::: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
xx drop (Unknown L3 target address) flow 0x0 to endpoint 0, ifindex 15, file icmp6.h:395, , identity unknown->unknown: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
<- endpoint 287 flow 0x198dee5 , identity 48569->unknown state unknown ifindex 0 orig-ip ::: [fd00:10:244:1::7bcf]:53478 -> [fd00:10:96::112f]:80 tcp SYN
-> endpoint 287 flow 0x198dee5 , identity 48569->48569 state established ifindex lxc7b070451d820 orig-ip fe80::1: [fe80::1]:53478 -> [fd00:10:244:1::7bcf]:80 tcp SYN
<- endpoint 287 flow 0x0 , identity 48569->unknown state unknown ifindex 0 orig-ip ::: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
xx drop (Unknown L3 target address) flow 0x0 to endpoint 0, ifindex 15, file icmp6.h:395, , identity unknown->unknown: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
<- endpoint 287 flow 0x0 , identity 48569->unknown state unknown ifindex 0 orig-ip ::: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
xx drop (Unknown L3 target address) flow 0x0 to endpoint 0, ifindex 15, file icmp6.h:395, , identity unknown->unknown: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
<- endpoint 287 flow 0x46b3e75c , identity 48569->unknown state unknown ifindex 0 orig-ip ::: [fd00:10:244:1::7bcf]:53478 -> [fd00:10:96::112f]:80 tcp SYN
-> endpoint 287 flow 0x46b3e75c , identity 48569->48569 state established ifindex lxc7b070451d820 orig-ip fe80::1: [fe80::1]:53478 -> [fd00:10:244:1::7bcf]:80 tcp SYN
<- endpoint 287 flow 0xf79d516a , identity 48569->unknown state unknown ifindex 0 orig-ip ::: [fd00:10:244:1::7bcf]:53478 -> [fd00:10:96::112f]:80 tcp SYN
-> endpoint 287 flow 0xf79d516a , identity 48569->48569 state established ifindex lxc7b070451d820 orig-ip fe80::1: [fe80::1]:53478 -> [fd00:10:244:1::7bcf]:80 tcp SYN
<- endpoint 287 flow 0x0 , identity 48569->unknown state unknown ifindex 0 orig-ip ::: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
xx drop (Unknown L3 target address) flow 0x0 to endpoint 0, ifindex 15, file icmp6.h:395, , identity unknown->unknown: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
<- endpoint 287 flow 0x0 , identity 48569->unknown state unknown ifindex 0 orig-ip ::: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
xx drop (Unknown L3 target address) flow 0x0 to endpoint 0, ifindex 15, file icmp6.h:395, , identity unknown->unknown: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
<- endpoint 287 flow 0xfa1f2fad , identity 48569->unknown state unknown ifindex 0 orig-ip ::: [fd00:10:244:1::7bcf]:53478 -> [fd00:10:96::112f]:80 tcp SYN
-> endpoint 287 flow 0xfa1f2fad , identity 48569->48569 state established ifindex lxc7b070451d820 orig-ip fe80::1: [fe80::1]:53478 -> [fd00:10:244:1::7bcf]:80 tcp SYN
<- endpoint 287 flow 0x4e771d96 , identity 48569->unknown state unknown ifindex 0 orig-ip ::: [fd00:10:244:1::7bcf]:53478 -> [fd00:10:96::112f]:80 tcp SYN
-> endpoint 287 flow 0x4e771d96 , identity 48569->48569 state established ifindex lxc7b070451d820 orig-ip fe80::1: [fe80::1]:53478 -> [fd00:10:244:1::7bcf]:80 tcp SYN
<- endpoint 287 flow 0x0 , identity 48569->unknown state unknown ifindex 0 orig-ip ::: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
xx drop (Unknown L3 target address) flow 0x0 to endpoint 0, ifindex 15, file icmp6.h:395, , identity unknown->unknown: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
<- endpoint 287 flow 0x0 , identity 48569->unknown state unknown ifindex 0 orig-ip ::: fe80::d40b:abff:fec3:22f -> fd00:10:244:1::f18f icmp NeighborSolicitation
<- endpoint 287 flow 0x0 , identity 48569->unknown state unknown ifindex 0 orig-ip ::: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
xx drop (Unknown L3 target address) flow 0x0 to endpoint 0, ifindex 15, file icmp6.h:395, , identity unknown->unknown: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
<- endpoint 287 flow 0xe5ae5999 , identity 48569->unknown state unknown ifindex 0 orig-ip ::: [fd00:10:244:1::7bcf]:53478 -> [fd00:10:96::112f]:80 tcp SYN
-> endpoint 287 flow 0xe5ae5999 , identity 48569->48569 state established ifindex lxc7b070451d820 orig-ip fe80::1: [fe80::1]:53478 -> [fd00:10:244:1::7bcf]:80 tcp SYN
<- endpoint 287 flow 0x0 , identity 48569->unknown state unknown ifindex 0 orig-ip ::: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
xx drop (Unknown L3 target address) flow 0x0 to endpoint 0, ifindex 15, file icmp6.h:395, , identity unknown->unknown: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
<- endpoint 287 flow 0x0 , identity 48569->unknown state unknown ifindex 0 orig-ip ::: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
xx drop (Unknown L3 target address) flow 0x0 to endpoint 0, ifindex 15, file icmp6.h:395, , identity unknown->unknown: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
<- endpoint 287 flow 0x0 , identity 48569->unknown state unknown ifindex 0 orig-ip ::: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
xx drop (Unknown L3 target address) flow 0x0 to endpoint 0, ifindex 15, file icmp6.h:395, , identity unknown->unknown: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
<- endpoint 287 flow 0x0 , identity 48569->unknown state unknown ifindex 0 orig-ip ::: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
xx drop (Unknown L3 target address) flow 0x0 to endpoint 0, ifindex 15, file icmp6.h:395, , identity unknown->unknown: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
<- endpoint 287 flow 0x0 , identity 48569->unknown state unknown ifindex 0 orig-ip ::: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
xx drop (Unknown L3 target address) flow 0x0 to endpoint 0, ifindex 15, file icmp6.h:395, , identity unknown->unknown: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
<- endpoint 287 flow 0x0 , identity 48569->unknown state unknown ifindex 0 orig-ip ::: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
xx drop (Unknown L3 target address) flow 0x0 to endpoint 0, ifindex 15, file icmp6.h:395, , identity unknown->unknown: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
<- endpoint 287 flow 0x0 , identity 48569->unknown state unknown ifindex 0 orig-ip ::: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
xx drop (Unknown L3 target address) flow 0x0 to endpoint 0, ifindex 15, file icmp6.h:395, , identity unknown->unknown: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
<- endpoint 287 flow 0x0 , identity 48569->unknown state unknown ifindex 0 orig-ip ::: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
xx drop (Unknown L3 target address) flow 0x0 to endpoint 0, ifindex 15, file icmp6.h:395, , identity unknown->unknown: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
<- endpoint 287 flow 0x0 , identity 48569->unknown state unknown ifindex 0 orig-ip ::: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
xx drop (Unknown L3 target address) flow 0x0 to endpoint 0, ifindex 15, file icmp6.h:395, , identity unknown->unknown: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
<- endpoint 287 flow 0x0 , identity 48569->unknown state unknown ifindex 0 orig-ip ::: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
xx drop (Unknown L3 target address) flow 0x0 to endpoint 0, ifindex 15, file icmp6.h:395, , identity unknown->unknown: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
<- endpoint 287 flow 0x0 , identity 48569->unknown state unknown ifindex 0 orig-ip ::: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
xx drop (Unknown L3 target address) flow 0x0 to endpoint 0, ifindex 15, file icmp6.h:395, , identity unknown->unknown: fd00:10:244:1::7bcf -> ff02::1:ff00:1 icmp NeighborSolicitation
```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by saiaunghlyanhtet**
[Previously,](https://github.com/cilium/cilium/pull/39594) the service loopback address for IPv6 is not recognized during icmp routing. So, a special case is needed to handle for it (Suggested by @pchaigno).

Fixes: #42460 

```release-note
bpf: adding a speical case for service loopback IPv6 during icmp routing 
```

### CODE REVIEW

**Review by bimmlerd — COMMENTED** [review]
cc @harsimran-pabla for visibility as you were involved in the mentioned issue

@saiaunghlyanhtet I lack some context on the change, but from what I understand this was in a released version of cilium - does this have upgrade impact? As in, could users observe breakage due to the default changing?

**Comment by saiaunghlyanhtet** [comment]
> @saiaunghlyanhtet does this have upgrade impact? As in, could users observe breakage due to the default changing?

I don't think so. Service loopback support for IPv6 was only included in v1.19.0-pre release but not backported to other previous versions yet.

**Review by bimmlerd — APPROVED** [review]
Oh yeah, you're right - somehow assumed this made it into 1.18. LGTM then!

File: bpf/lib/icmp6.h [hunk 1]
```diff
@@ -359,6 +359,13 @@ static __always_inline int __icmp6_handle_ns(struct __ctx_buff *ctx, int nh_off)
 		return icmp6_send_ndisc_adv(ctx, nh_off, &router_mac, true);
 	}
 
+#ifdef USE_LOOPBACK_LB
+	union v6addr service_loopback = CONFIG(service_loopback_ipv6);
+
+	if (ipv6_addr_equals(&target, &service_loopback))
+		return icmp6_send_ndisc_adv(ctx, nh_off, &router_mac, false);
```
Comment (pchaigno) [inline bpf/lib/icmp6.h]: Shouldn't we reply with the L2 address of the source pod here instead?

File: bpf/lib/icmp6.h [hunk 2]
```diff
@@ -359,6 +359,13 @@ static __always_inline int __icmp6_handle_ns(struct __ctx_buff *ctx, int nh_off)
 		return icmp6_send_ndisc_adv(ctx, nh_off, &router_mac, true);
```
Comment (pchaigno) [inline bpf/lib/icmp6.h:359]: *(On commit description)*

Could you include a bit more information on what's happening here? Maybe with the `cilium monitor` trace from the issue as an illustration? I think it would also be good to have a `Fixes:` tag referring to your previous commit (see the commit logs for examples of the format).

Nit: There's a typo on `special` in the title.

**Comment by pchaigno** [comment]
Given there is no user-visible impact, it should be `release-note/misc`.

**Review by pchaigno — COMMENTED** [review]
Thanks for sending the fix!

File: bpf/lib/icmp6.h (hunk 1 above)
Comment (saiaunghlyanhtet) [reply bpf/lib/icmp6.h]: Fixed it.

File: bpf/lib/icmp6.h (hunk 2 above)
Comment (saiaunghlyanhtet) [reply bpf/lib/icmp6.h:359]: I added some info.

Comment (pchaigno) [reply bpf/lib/icmp6.h:359]: The typo is still in the commit title :slightly_smiling_face: Could you also refer to the commit on `main` you are fixing instead of the pull request?

Comment (saiaunghlyanhtet) [reply bpf/lib/icmp6.h:359]: Sorry. Didn't see it.

**Review by pchaigno — APPROVED** [review]

**Review by jrife — APPROVED** [review]
