### PR TITLE
bpf: nodeport: handle DSR at from-netdev / to-netdev

### LINKED ISSUE #10789: DSR does not work for service endpoints in host netns
The NodePort DSR feature does not work for service endpoints which run in the host netns (`hostNetwork: true`). The problem is that parsing the IP options, populating the BPF map with service IP addr + port for the rev-DNAT xlation, etc is implemented in bpf_lxc, which, obviously, is not attached to such endpoints.

### PR DESCRIPTION
**Pull request by julianwiedmann**
(see partner PR https://github.com/cilium/cilium/pull/22756)

Replies by DSR service backends currently get their revDNAT processing in
[from-container](https://github.com/cilium/cilium/blob/2d1a82f49f241045f778d44bb537a1e150341e57/bpf/bpf_lxc.c#L907). There's two problems with that:

1. we have cases where the packet doesn't reach this part of the
    from-container program (ie. redirect to host proxy), and
2. we're not handling replies by hostns backends at all.

This PR tackles the problem as follows:
1. Add support for RevDNAT of DSR connections in the `to-netdev` path.
2. extract the DSR information (from IPv4 Options / IPv6 Extension Header) in the nodeport entry path, and not in [to-container](https://github.com/cilium/cilium/blob/2d1a82f49f241045f778d44bb537a1e150341e57/bpf/bpf_lxc.c#L1810). Build a nodeport-level CT entry for connections that have DSR info (similar as for the `local-backend` case). Use the DSR info to build a SNAT entry for RevDNAT of the backend replies.
3. reduce the DSR support in bpf_lxc to only cover old connections. The nodeport path can't easily create a CT entry for these connections (as for TCP we won't see another SYN with DSR info). There's possibilities how to move this into `to-netdev` as well, but let's try that in a follow-on PR.

```release-note
When using KPR Nodeport with DSR, support backends in hostNetwork or with L7 policies.
```

Updated nodeport ingress diagram:

```mermaid
flowchart TD
    A[from-netdev] -->|CILIUM_CALL_IPV4_FROM_NETDEV| B{"bpf_skip_nodeport()?"}
    B --> |No| C["nodeport_lb4()"]
    B --> |Yes| B1["// further packet process"]
    C --> D["lb4_lookup_service()"]
    D --> E{"dst is svc ?"}
    E --> |No| F{"has DSR info / CT entry with .dsr set?"}
    E --> |Yes| F1["lb4_local()"]
    F --> |Yes| F2[" "]
    F2 --> |CILIUM_CALL_IPV4_NODEPORT_DSR_INGRESS| X["tail_nodeport_dsr_ingress_ipv4()"]
    X --> X1["create / update CT entry and SNAT entry"]
    X1 --> X2["bpf_skip_nodeport_set()"]
    X2 --> |CILIUM_CALL_IPV4_FROM_NETDEV| B
    F1 --> G1{"backend local?"}
    G1 --> |Yes| H1["CTX_ACT_OK"]
    G1 --> |No| H2[" "]
    H2 --> |CILIUM_CALL_IPV4_NODEPORT_NAT_EGRESS| G2["tail_nodeport_nat_egress_ipv4()"]
    G2 --> J2["snat_v4_nat()"]
    J2 --> K2{"found new SNAT mapping?"}
    K2 --> |No| L2["CTX_ACT_DROP"]
    K2 --> |Yes| M2["// Do SNAT"]
    M2 --> N2["ctx_redirect()"]
    F --> |No| F3[" "]
    F3 --> |CILIUM_CALL_IPV4_NODEPORT_NAT_INGRESS| G["tail_nodeport_nat_ingress_ipv4()"]
    G --> H["snat_v4_rev_nat()"]
    H --> J{"Reverse mapping exist?"}
    J --> |No| K["bpf_skip_nodeport_set()"]
    K --> |CILIUM_CALL_IPV4_FROM_NETDEV| B
    J --> |"Yes\n(This can be rev-SNAT for outside2pod)"| L["tail_rev_nodeport_lb4()"]
    L --> M["rev_nodeport_lb4()"]
    M --> N["ct_lb_lookup4()"]
    N --> O{"NodePort CT reply?"}
    O --> |Yes| P["// do rev-DNAT"]
    P --> R["ctx_redirect()"]
    O --> |No| Q["bpf_skip_nodeport_set()"]
    Q --> |CILIUM_CALL_IPV4_FROM_NETDEV| B
```

### CODE REVIEW

**Comment by julianwiedmann** [comment]
Some ideas for reviewers to double-check:
- is there any change in behaviour for old connections (where bpf_lxc has already created the SNAT entry and flagged its CT entry as `.dsr = true`)
- in `from-container,` is there anything in the code path *after* the call to `xlate_dsr_v4()` that might be surprised by now seeing replies that haven't been RevDNATed yet
- does all the CT logic in `tail_nodeport_dsr_ingress_ipv4()` check out?

**Comment by julianwiedmann** [comment]
/test-1.26-net-next

**Comment by julianwiedmann** [comment]
/test-1.25-4.19

**Comment by julianwiedmann** [comment]
@ysksuzuki would appreciate review/feedback from your side too :)

File: bpf/lib/conntrack.h [hunk 1]
```diff
@@ -1043,6 +1043,23 @@ ct_has_nodeport_egress_entry4(const void *map,
...
+	ingress_tuple->flags = prev_flags;
+
+	if (entry)
+		return entry->node_port || entry->dsr;
+
+	return 0;
+}
+
 static __always_inline bool
 ct_has_nodeport_egress_entry6(const void *map,
```
Comment (sahid) [inline bpf/lib/conntrack.h:1047]: Why not to replace it with the new one that you have introduced where it is used and removing it completely? (same for ipv4)

File: bpf/lib/nodeport.h [hunk 2]
```diff
@@ -1019,24 +1019,35 @@ nodeport_rev_dnat_fwd_ipv6(struct __ctx_buff *ctx, struct trace_ctx *trace)
...
 
-		ctx_snat_done_set(ctx);
+			csum_l4_offset_and_flags(tuple.nexthdr, &csum_off);
+
+			ret = lb6_rev_nat(ctx, l4_off, &csum_off, ct_state.rev_nat_index,
+					  &tuple, REV_NAT_F_TUPLE_SADDR);
+			if (IS_ERR(ret))
+				return ret;
+
+			ctx_snat_done_set(ctx);
```
Comment (sahid) [inline bpf/lib/nodeport.h:1023]: You can perhaps put this one line 1050, and remove the one line 1048?

**Review by dylandreimerink — APPROVED** [review]
I am not familiar enough with the CT/DSR code to give a valued opinion about it, would like someone else from sig-datapath approve it as well.

Having that said, I really appreciate the work on the tests, looks like a great addition!

**Comment by ysksuzuki** [comment]
I'm trying the nodeport-hostns-dsr branch and checking CT. It seems that the nodeport-hostns-dsr version creates TCP IN and TCP OUT, and TCP OUT remains half closed and stays for a while. Is this an expected behavior?

```
# nodeport-hostns-dsr
$ kubectl -n kube-system exec cilium-rqfcm -- cilium bpf ct list global
TCP IN 10.72.3.2:39170 -> 10.64.0.35:8000 expires=8256 RxPackets=6 RxBytes=486 RxFlagsSeen=0x1b LastRxReport=8246 TxPackets=4 TxBytes=393 TxFlagsSeen=0x1b LastTxReport=8246 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=2 IfIndex=0
TCP OUT 10.72.3.2:39170 -> 10.64.0.35:8000 expires=29846 RxPackets=4 RxBytes=393 RxFlagsSeen=0x1b LastRxReport=8246 TxPackets=1 TxBytes=82 TxFlagsSeen=0x02 LastTxReport=8246 Flags=0x0091 [ RxClosing SeenNonSyn DSR ] RevNAT=0 SourceSecurityID=2 IfIndex=3
ICMP IN 10.72.3.2:0 -> 10.64.0.35:0 related expires=8306 RxPackets=1 RxBytes=82 RxFlagsSeen=0x02 LastRxReport=8246 TxPackets=0 TxBytes=0 TxFlagsSeen=0x00 LastTxReport=0 Flags=0x0010 [ SeenNonSyn ] RevNAT=0 SourceSecurityID=2 IfIndex=0

# v1.12.4
$ kubectl -n kube-system exec cilium-m7vwq -- cilium bpf ct list global
TCP IN 10.72.3.2:33108 -> 10.64.0.35:8000 expires=6741 RxPackets=6 RxBytes=486 RxFlagsSeen=0x1b LastRxReport=6731 TxPackets=4 TxBytes=393 TxFlagsSeen=0x1b LastTxReport=6731 Flags=0x0093 [ RxClosing TxClosing SeenNonSyn DSR ] RevNAT=0 SourceSecurityID=2 IfIndex=0
ICMP IN 10.72.3.2:0 -> 10.64.0.35:0 related expires=6791 RxPackets=1 RxBytes=82 RxFlagsSeen=0x02 LastRxReport=6731 TxPackets=0 TxBytes=0 TxFlagsSeen=0x00 LastTxReport=0 Flags=0x0090 [ SeenNonSyn DSR ] RevNAT=0 SourceSecurityID=2 IfIndex=0

$ kubectl -n dctest get svc
NAME               TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
suzuki-test        LoadBalancer   10.68.158.113   10.72.32.1    80:32202/TCP   59m
$ kubectl -n dctest get po -o wide
NAME                                READY   STATUS    RESTARTS   AGE     IP            NODE          NOMINATED NODE   READINESS GATES
suzuki-test-d7f66dc7d-hqlx8         1/1     Running   0          48m     10.64.0.35    10.69.0.4     <none>           <none>
```

**Comment by julianwiedmann** [comment]
> I'm trying the nodeport-hostns-dsr branch and checking CT. It seems that the nodeport-hostns-dsr version creates TCP IN and TCP OUT, and TCP OUT remains half closed and stays for a while. Is this an expected behavior?
> 

Yeah probably a side-effect of us tracking just one leg of the connection. Once the TCP-SYN is through, the inbound nodeport code doesn't do any CT lookups for subsequent packets of the connection (as we can't easily tell that they belong to a DSR connection).

I didn't want to add that right away. But we probably need a `ct_has_dsr_egress_entry4()` check, and branch off into the DSR_INGRESS path accordingly to update the CT entry.

**Comment by ysksuzuki** [comment]
> Yeah probably a side-effect of us tracking just one leg of the connection. Once the TCP-SYN is through, the inbound nodeport code doesn't do any CT lookups for subsequent packets of the connection (as we can't easily tell that they belong to a DSR connection).

I see. the inbound FIN packet never hit this line https://github.com/cilium/cilium/blob/0d45e32c372dc0cacd0124fba8ef0def60de65b5/bpf/lib/nodeport.h#L2012, and the CT entry remains half closed.

I was worried about an issue like https://github.com/cilium/cilium/issues/23126, in which a client hit a stale CT and Cilium skips to create or update the SNAT mapping. But it seems like that tail_nodeport_dsr_ingress_ipv4 code covers this scenario. If the CT lookup result is CT_REOPENED or CT_ESTABLISHED, this code update CT entry and SNAT mapping accordingly. This PR also fixes https://github.com/cilium/cilium/issues/18632, perhaps. Excellent work!

> But we probably need a ct_has_dsr_egress_entry4() check, and branch off into the DSR_INGRESS path accordingly to update the CT entry.

Yeah, it's probably good to have.

**Comment by ysksuzuki** [comment]
It would be helpful to show flow logs for the Load balancer with host network endpoints when users debug communication with it. `hubble observe` shows flow logs for the services with `hostNetwork: false` endpoints as follows, but it doesn't for the Load balancer with host network endpoints. 

```
$ hubble observe --follow --server hubble-relay.kube-system.svc:443 --tls --tls-allow-insecure --namespace dctest

Feb  1 11:05:27.865: 10.72.3.2:43898 (world) -> dctest/suzuki-test-5bb565759-mnrvc:8000 (ID:11305) to-endpoint FORWARDED (TCP Flags: SYN)
Feb  1 11:05:27.865: 10.72.3.2:43898 (world) <- dctest/suzuki-test-5bb565759-mnrvc:8000 (ID:11305) to-network FORWARDED (TCP Flags: SYN, ACK)
Feb  1 11:05:27.865: 10.72.3.2:43898 (world) -> dctest/suzuki-test-5bb565759-mnrvc:8000 (ID:11305) to-endpoint FORWARDED (TCP Flags: ACK)
Feb  1 11:05:27.866: 10.72.3.2:43898 (world) -> dctest/suzuki-test-5bb565759-mnrvc:8000 (ID:11305) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
Feb  1 11:05:27.866: 10.72.3.2:43898 (world) <- dctest/suzuki-test-5bb565759-mnrvc:8000 (ID:11305) to-network FORWARDED (TCP Flags: ACK, PSH)
Feb  1 11:05:27.866: 10.72.3.2:43898 (world) -> dctest/suzuki-test-5bb565759-mnrvc:8000 (ID:11305) to-endpoint FORWARDED (TCP Flags: ACK, FIN)
Feb  1 11:05:27.866: 10.72.3.2:43898 (world) <- dctest/suzuki-test-5bb565759-mnrvc:8000 (ID:11305) to-network FORWARDED (TCP Flags: ACK, FIN)
Feb  1 11:05:27.866: 10.72.3.2:43898 (world) -> dctest/suzuki-test-5bb565759-mnrvc:8000 (ID:11305) to-endpoint FORWARDED (TCP Flags: ACK)
```

File: bpf/bpf_lxc.c [hunk 3]
```diff
@@ -878,6 +878,7 @@ static __always_inline int handle_ipv4_from_lxc(struct __ctx_buff *ctx, __u32 *d
 
 #ifdef ENABLE_NODEPORT
 # ifdef ENABLE_DSR
+		/* only for old connections: */
```
Comment (ysksuzuki) [inline bpf/bpf_lxc.c]: After upgrading Cilium v1.12 to v1.13, this code ensures that ongoing active connections will be handled appropriately. Cilium doesn't have a chance to update DSR states until clients shut down old connections and restart new connections (only the SYN packet has a clue). So this code is left here as is. Is my understanding correct?

**Comment by ysksuzuki** [comment]
That's all from my side. Awesome work! I'm looking forward to implementing DSR with Geneve on top of this new DSR implementation!

File: bpf/bpf_lxc.c (hunk 3 above)
Comment (julianwiedmann) [reply bpf/bpf_lxc.c]: Ack - that's point 3 in the cover letter:

> reduce the DSR support in bpf_lxc to only cover old connections. The nodeport path can't easily create a CT entry for these connections (as for TCP we won't see another SYN with DSR info). There's possibilities how to move this into to-netdev as well, but let's try that in a follow-on PR.

We might be able to identify such old connections in the RevDNAT code @ `to-netdev`, but I'm a bit hesitant to change this for existing connections. It would be very confusing to any observer that sits "in between" `from-container` and `to-netdev` - suddenly the replies of an established flow are no longer revDNATed from their perspective.

**Comment by julianwiedmann** [comment]
> It would be helpful to show flow logs for the Load balancer with host network endpoints when users debug communication with it. `hubble observe` shows flow logs for the services with `hostNetwork: false` endpoints as follows, but it doesn't for the Load balancer with host network endpoints.

Agree, sounds like a good observability improvement!

**Comment by julianwiedmann** [comment]
> > Yeah probably a side-effect of us tracking just one leg of the connection. Once the TCP-SYN is through, the inbound nodeport code doesn't do any CT lookups for subsequent packets of the connection (as we can't easily tell that they belong to a DSR connection).
> 
> I see. the inbound FIN packet never hit this line
> 
> https://github.com/cilium/cilium/blob/0d45e32c372dc0cacd0124fba8ef0def60de65b5/bpf/lib/nodeport.h#L2012
> , and the CT entry remains half closed.
> 
> I was worried about an issue like #23126, in which a client hit a stale CT and Cilium skips to create or update the SNAT mapping. But it seems like that tail_nodeport_dsr_ingress_ipv4 code covers this scenario. If the CT lookup result is CT_REOPENED or CT_ESTABLISHED, this code update CT entry and SNAT mapping accordingly. This PR also fixes #18632, perhaps. Excellent work!
> 

Ah, I wasn't aware of that issue. Yes, I can see where that would come from... don't think it's fixed in this version yet, but the next push should hopefully take care of it. Thanks!

> > But we probably need a ct_has_dsr_egress_entry4() check, and branch off into the DSR_INGRESS path accordingly to update the CT entry.
> 
> Yeah, it's probably good to have.

I started hacking on it ... tricky stuff. Should have something shortly.

File: bpf/bpf_lxc.c (hunk 3 above)
Comment (ysksuzuki) [reply bpf/bpf_lxc.c]: Agree. It's very confusing, and I think it would be a bit risky to touch the state of existing long connections.

File: bpf/lib/conntrack.h (hunk 1 above)
Comment (julianwiedmann) [reply bpf/lib/conntrack.h:1047]: One function looks for entries where `.nodeport` is set, the other looks for entries with `.nodeport` and/or `.dsr` set. Different functionality, different usage. I don't understand how one would replace the other, can you elaborate a bit more?

File: bpf/lib/nodeport.h (hunk 2 above)
Comment (julianwiedmann) [reply bpf/lib/nodeport.h:1023]: Not sure I understand - you mean moving this into the general `if (ret == CT_REPLY)` case? That would mean potentially flagging a packet as SNAT-done even if we didn't do any SNAT processing, no?

**Comment by julianwiedmann** [comment]
Added a patch to track the whole inbound leg of the TCP DSR connection (not just the SYN packet that contains the DSR info). This of course caused `nodeport_lb4()` to blow up in the verifier, so all the earlier LB cleanups are back to shave off some instructions.

**Comment by julianwiedmann** [comment]
I pulled the CT refactoring into a separate PR (https://github.com/cilium/cilium/pull/22936). It's fairly self-contained, and this should hopefully make review easier.

**Comment by julianwiedmann** [comment]
> I pulled the CT refactoring into a separate PR (#22936). It's fairly self-contained, and this should hopefully make review easier.

This is merged now, so opening it up for review of the DSR changes again.

File: bpf/lib/conntrack.h (hunk 1 above)
Comment (gentoo-root) [reply bpf/lib/conntrack.h:1047]: E.g., like this:

```
static __always_inline bool
ct_has_nodeport_egress_entry6(const void *map,
			      struct ipv6_ct_tuple *ingress_tuple,
			      bool or_dsr)
{
	__u8 prev_flags = ingress_tuple->flags;
	struct ct_entry *entry;
	ingress_tuple->flags = TUPLE_F_OUT;
	entry = map_lookup_elem(map, ingress_tuple);
	ingress_tuple->flags = prev_flags;
	if (entry)
		return entry->node_port || (entry->dsr && or_dsr);
	return 0;
}
```

Hoping that clang will optimize out the new logical operation, given that or_dsr is known at compile time.

File: bpf/lib/nodeport.h [hunk 4]
```diff
@@ -1012,24 +1012,35 @@ nodeport_rev_dnat_fwd_ipv6(struct __ctx_buff *ctx, struct trace_ctx *trace)
...
+#ifdef ENABLE_DSR
+		} else if (ct_state.dsr) {
+			ret = xlate_dsr_v6(ctx, &tuple, l4_off);
+			if (IS_ERR(ret))
+				return ret;
+
+			ctx_snat_done_set(ctx);
```
Comment (pchaigno) [inline bpf/lib/nodeport.h]: `xlate_dsr_v6` already calls `ctx_snat_done_set`. Same for IPv4 I expect.

File: bpf/bpf_lxc.c [hunk 5]
```diff
@@ -86,7 +86,7 @@ static __always_inline int __per_packet_lb_svc_xlate_4(void *ctx, struct iphdr *
```
Comment (pchaigno) [inline bpf/bpf_lxc.c:86]: *(Commenting on random line just to have a thread.)*

Shouldn't the PR be renamed to `bpf: nodeport: handle DSR at to-netdev`? It looks like it currently describes the first commit only, but this pull request actually moves most of the DSR logic to to-netdev, no?

File: bpf/bpf_lxc.c [hunk 6]
```diff
@@ -923,6 +923,7 @@ static __always_inline int handle_ipv4_from_lxc(struct __ctx_buff *ctx, __u32 *d
 
 #ifdef ENABLE_NODEPORT
 # ifdef ENABLE_DSR
+		/* only for old connections: */
```
Comment (pchaigno) [inline bpf/bpf_lxc.c]: Could you expand a bit on this comment? I understand it, but I think it will just be very confusing to someone who stumbles upon it while reading bpf_lxc :-/

Do we need a similar comment or reference to IPv4 comment in the IPv6 code?

File: bpf/bpf_lxc.c [hunk 7]
```diff
@@ -1436,22 +1437,11 @@ ipv6_policy(struct __ctx_buff *ctx, int ifindex, __u32 src_label,
...
-		if (ret2 != 0)
-			return ret2;
-
-		ct_state_new.dsr = dsr;
-		if (ret == CT_REOPENED && ct_state->dsr != dsr)
-			ct_update_dsr(get_ct_map6(tuple), tuple, dsr);
+		if (ret == CT_REOPENED && ct_state->dsr)
+			ct_update_dsr(get_ct_map6(tuple), tuple, false);
 # endif /* ENABLE_DSR */
-		if (!dsr) {
```
Comment (pchaigno) [inline bpf/bpf_lxc.c:1457]: Why is the below NodePort logic always executed now when it was only conditionally executed before? What's the consequence of running it even for DSR traffic now?

File: bpf/bpf_lxc.c [hunk 8]
```diff
@@ -1436,22 +1437,11 @@ ipv6_policy(struct __ctx_buff *ctx, int ifindex, __u32 src_label,
...
 #ifdef ENABLE_NODEPORT
 	if (ret == CT_NEW || ret == CT_REOPENED) {
-		bool dsr = false;
 # ifdef ENABLE_DSR
-		int ret2;
-
-		if (!revalidate_data(ctx, &data, &data_end, &ip6))
-			return DROP_INVALID;
-
-		ret2 = handle_dsr_v6(ctx, ip6, &dsr);
```
Comment (pchaigno) [inline bpf/bpf_lxc.c:1449]: Looks like this was the only call to `handle_dsr_v{4,6}`.

File: bpf/lib/nodeport.h [hunk 9]
```diff
@@ -911,8 +987,28 @@ static __always_inline int nodeport_lb6(struct __ctx_buff *ctx,
 #endif
 		ctx_set_xfer(ctx, XFER_PKT_NO_SVC);
 
-		if (nodeport_uses_dsr6(&tuple))
+#ifdef ENABLE_DSR
+		if (nodeport_uses_dsr6(&tuple)) {
+			bool dsr = false;
+
+			ret = nodeport_extract_dsr_v6(ctx, ip6, &key.address,
+						      &key.dport, &dsr);
```
Comment (pchaigno) [inline bpf/lib/nodeport.h]: Do we even need `nodeport_extract_dsr_v6` now? It looks like `find_dsr_v6` could write directly into `key.address` and `key.dport`.

File: bpf/lib/nodeport.h [hunk 10]
```diff
@@ -832,6 +833,81 @@ int tail_nodeport_nat_egress_ipv6(struct __ctx_buff *ctx)
...
+
+	ret = ct_lb_lookup6(get_ct_map6(&tuple), &tuple, ctx, l4_off,
+			    CT_EGRESS, &ct_state, &monitor);
+	switch (ret) {
+	case CT_NEW:
+	case CT_REOPENED:
+create_ct:
+		ct_state_new.src_sec_id = WORLD_ID;
+		ct_state_new.dsr = 1;
+		ct_state_new.ifindex = (__u16)NATIVE_DEV_IFINDEX;
```
Comment (pchaigno) [inline bpf/lib/nodeport.h:769]: AFAIU, this code comes to replace the code you've removed from bpf_lxc, right? In bpf_lxc, we didn't set `ct_state_new.ifindex` AFAICS. Why do we need to set it here?

File: bpf/lib/nodeport.h [hunk 11]
```diff
@@ -832,6 +833,81 @@ int tail_nodeport_nat_egress_ipv6(struct __ctx_buff *ctx)
...
+		ipv6_ct_tuple_reverse(&tuple);
+		goto create_ct;
+	default:
+		ret = DROP_UNKNOWN_CT;
+		goto drop_err;
+	}
+
+	ret = neigh_record_ip6(ctx);
+	if (ret < 0)
+		goto drop_err;
```
Comment (pchaigno) [inline bpf/lib/nodeport.h:792]: Why is this needed?

File: bpf/lib/nodeport.h [hunk 12]
```diff
@@ -832,6 +833,81 @@ int tail_nodeport_nat_egress_ipv6(struct __ctx_buff *ctx)
...
+
+	ctx_skip_nodeport_set(ctx);
+	ep_tail_call(ctx, CILIUM_CALL_IPV6_FROM_NETDEV);
+	ret = DROP_MISSED_TAIL_CALL;
```
Comment (pchaigno) [inline bpf/lib/nodeport.h:796]: `nodeport_lb6` used to perform a tail call to `CILIUM_CALL_IPV6_NODEPORT_NAT_INGRESS` after calling `nodeport_uses_dsr6`. Why is this changed to go to `CILIUM_CALL_IPV6_FROM_NETDEV` instead?

File: bpf/lib/nodeport.h [hunk 13]
```diff
@@ -327,20 +327,41 @@ static __always_inline int find_dsr_v6(struct __ctx_buff *ctx, __u8 nexthdr,
...
+			return DROP_CT_INVALID_HDR;
+
+		ipv6_ct_tuple_reverse(&tmp);
+
+		if (!(tcp_flags.value & TCP_FLAG_SYN)) {
+			*dsr = ct_has_dsr_egress_entry6(get_ct_map6(&tmp), &tmp);
+			*port = 0;
+			return 0;
+		}
+	}
```
Comment (pchaigno) [inline bpf/lib/nodeport.h:324]: Could we have a comment for this whole block, to explain why it's needed? IMO, what you have in the commit description should be good enough.

File: bpf/lib/nodeport.h [hunk 14]
```diff
@@ -327,20 +327,41 @@ static __always_inline int find_dsr_v6(struct __ctx_buff *ctx, __u8 nexthdr,
...
 		return ret;
 
 	if (*dsr) {
 		*addr = opt.addr;
 		*port = opt.port;
+		return 0;
 	}
 
+	if (tuple->nexthdr == IPPROTO_TCP)
+		ct_update_dsr(get_ct_map6(&tmp), &tmp, false);
```
Comment (pchaigno) [inline bpf/lib/nodeport.h:337]: Why is this needed? Isn't the DSR flag set to false already in the CT entry? I thought that's what we just read `*dsr` from.

File: bpf/lib/nodeport.h [hunk 15]
```diff
@@ -873,6 +894,11 @@ int tail_nodeport_dsr_ingress_ipv6(struct __ctx_buff *ctx)
 	case CT_NEW:
 	case CT_REOPENED:
 create_ct:
+		if (port == 0) {
+			ret = DROP_INVALID;
+			goto drop_err;
+		}
```
Comment (pchaigno) [inline bpf/lib/nodeport.h:765]: Couldn't we check for this case and drop the packet sooner, when we read the port before the tail call?

File: bpf/lib/lb.h [hunk 16]
```diff
@@ -510,8 +510,8 @@ lb6_fill_key(struct lb6_key *key, struct ipv6_ct_tuple *tuple)
  *   - Negative error code
  */
 static __always_inline int
-lb6_extract_tuple(struct __ctx_buff *ctx, struct ipv6hdr *ip6, int *l4_off,
-		  struct ipv6_ct_tuple *tuple)
```
Comment (pchaigno) [inline bpf/lib/lb.h:514]: The function comment above needs an update. It would also be good to mention there that `l4_off` is only for unit tests. Some people have been know to remove those seemingly-unused `l4_off` arguments in the past :innocent:

File: bpf/lib/lb.h [hunk 17]
```diff
@@ -1151,7 +1151,7 @@ lb4_fill_key(struct lb4_key *key, struct ipv4_ct_tuple *tuple)
  *   - Negative error code
  */
 static __always_inline int
-lb4_extract_tuple(struct __ctx_buff *ctx, struct iphdr *ip4, int *l4_off,
```
Comment (pchaigno) [inline bpf/lib/lb.h:1154]: Ditto.

File: bpf/tests/pktgen.h [hunk 18]
```diff
@@ -207,24 +211,24 @@ struct iphdr *pktgen__push_iphdr(struct pktgen *builder)
...
+	builder->cur_off += length;
 
 	return layer;
 }
 
-/* Push a IPv4 header with sane defaults onto the packet */
+/* Push a IPv4 header with sane defaults and options onto the packet */
 static __always_inline
 __attribute__((warn_unused_result))
-struct iphdr *pktgen__push_default_iphdr(struct pktgen *builder)
```
Comment (pchaigno) [inline bpf/tests/pktgen.h:218]: Could we have a `pktgen__push_default_iphdr_with_opt` and let `pktgen__push_default_iphdr` call it with a 0 second argument, such that we wouldn't need to change all call sites of `pktgen__push_default_iphdr`?

**Review by pchaigno — CHANGES_REQUESTED** [review]
Mostly questions from me. This is tricky code and I'm not always sure I'm following the changes. There are a couple I would really like to understand before approving (e.g., change in tail call target, impact of some condition on NodePort logic).

File: bpf/lib/conntrack.h (hunk 1 above)
Comment (pchaigno) [reply bpf/lib/conntrack.h:1047]: Maxim's proposal makes sense to me, especially given there are three such functions in the end (node_port, dsr, node_port or dsr).

File: bpf/lib/nodeport.h [hunk 19]
```diff
@@ -1012,24 +1012,35 @@ nodeport_rev_dnat_fwd_ipv6(struct __ctx_buff *ctx, struct trace_ctx *trace)
...
+			csum_l4_offset_and_flags(tuple.nexthdr, &csum_off);
+
+			ret = lb6_rev_nat(ctx, l4_off, &csum_off, ct_state.rev_nat_index,
+					  &tuple, REV_NAT_F_TUPLE_SADDR);
+			if (IS_ERR(ret))
+				return ret;
+
+			ctx_snat_done_set(ctx);
+#ifdef ENABLE_DSR
+		} else if (ct_state.dsr) {
```
Comment (brb) [inline bpf/lib/nodeport.h:1025]: Nit: I think it would make sense to rename `ct_state.nodeport` to `ct_state.nodeport_snat`, and `ct_state.dsr` to `ct_state.nodeport_dsr` (both are mutually exclusive).

File: bpf/bpf_lxc.c (hunk 5 above)
Comment (julianwiedmann) [reply bpf/bpf_lxc.c:86]: ack - it kind of grew bigger and bigger :smile:. Updated to `bpf: nodeport: handle DSR at from-netdev / to-netdev`

File: bpf/lib/nodeport.h (hunk 12 above)
Comment (julianwiedmann) [reply bpf/lib/nodeport.h:796]: The code in NAT_INGRESS is only needed if we're dealing with some sort of reply traffic - revSNAT, potentially revDNAT, EgressGW reply .... But if the packet has embedded DSR info or matches a DSR CT entry, we already know it's not reply traffic. So we could circle through NAT_INGRESS as well, but at the moment it's just not necessary.

File: bpf/lib/nodeport.h (hunk 4 above)
Comment (julianwiedmann) [reply bpf/lib/nodeport.h]: Oh indeed. And I even know who added it there :smile:. Will remove - maybe we can shift it around once `bpf_lxc` doesn't care about DSR RevDNAT any longer. Thanks!

File: bpf/lib/conntrack.h (hunk 1 above)
Comment (julianwiedmann) [reply bpf/lib/conntrack.h:1047]: So my first thought was that it doesn't make much difference. But this would actually allow us to pass `or_dsr := is_defined(ENABLE_DSR)`, and that's a nice little improvement :+1:.

File: bpf/lib/nodeport.h (hunk 12 above)
Comment (pchaigno) [reply bpf/lib/nodeport.h:796]: Got it. Thanks for the explanation!

Might be worst a note in the commit description, though maybe it's evident to LB folks.

File: bpf/tests/pktgen.h (hunk 18 above)
Comment (julianwiedmann) [reply bpf/tests/pktgen.h:218]: Yes, I'll change that :+1:. Needing to adjust for every new unit-test that gets added during this PR's lifetime has started to get silly ... :)

File: bpf/lib/lb.h (hunk 16 above)
Comment (julianwiedmann) [reply bpf/lib/lb.h:514]: FWIW, I expect that we'll end up using the l3_off parameter in other areas too (eg. see https://github.com/cilium/cilium/pull/18414#discussion_r1106777228). So think we won't need that comment - the unit tests will complain loud enough if they fail to compile :).

File: bpf/bpf_lxc.c (hunk 8 above)
Comment (julianwiedmann) [reply bpf/bpf_lxc.c:1449]: Yup, and those functions have been renamed to `nodeport_extract_dsr_*()` now.

File: bpf/bpf_lxc.c (hunk 7 above)
Comment (julianwiedmann) [reply bpf/bpf_lxc.c:1457]: In old code we were able to say "if it's DSR, it's certainly not local-backend".

Now that we no longer look at the connection's DSR state (note that we only flush out any stale `.dsr` flags in the pod-level CT entry, but don't call `ct_has_dsr_egress_entry4()`), *all* connections are potentially for a local-backend.

If this is traffic for a new DSR connection, then the pod-level CT entry has its stale `.node_port` flag cleared.

File: bpf/lib/nodeport.h (hunk 9 above)
Comment (julianwiedmann) [reply bpf/lib/nodeport.h]: If you look at the final result of the PR, there's quite a bit of surrounding logic in `nodeport_extract_dsr_v6()` that deals with TCP-SYN etc.

File: bpf/lib/nodeport.h (hunk 10 above)
Comment (julianwiedmann) [reply bpf/lib/nodeport.h:769]: Right now it's essentially prep-work, to keep the CT entry on par with that we build for a local backend.

My gut feeling is that with multiple external interfaces, we'll end up needing an additional FIB-lookup **after** the RevDNAT in `to-netdev` happened. So let's make sure that we already create CT entries that have all the needed information for that case. Alternatively we clean it up consistently for both DSR and local-backend sometime in the future.

File: bpf/lib/nodeport.h (hunk 11 above)
Comment (julianwiedmann) [reply bpf/lib/nodeport.h:792]: see [above](https://github.com/cilium/cilium/pull/22978#discussion_r1119880115)

File: bpf/lib/nodeport.h (hunk 15 above)
Comment (julianwiedmann) [reply bpf/lib/nodeport.h:765]: See the comment in `tail_nodeport_dsr_ingress_ipv4()` - this isn't about the TCP-SYN containing bad DSR info, but about a subsequent TCP packet that expects a matching CT entry but doesn't find it (even though we checked earlier that it exists). It's arguably the most hacky/tricky part of the PR :/.

**Review by brb — COMMENTED** [review]
Did my first round of a review. Amazing PR! Will do a second round once you have added the `to-netdev` diagram.

File: bpf/lib/nodeport.h (hunk 13 above)
Comment (julianwiedmann) [reply bpf/lib/nodeport.h:324]: Is the comment in `nodeport_extract_dsr_v4()` sufficient, or are you looking for more details?

File: bpf/lib/nodeport.h (hunk 14 above)
Comment (julianwiedmann) [reply bpf/lib/nodeport.h:337]: See `nodeport_extract_dsr_v4()` - we just processed a TCP-SYN (because all non-SYN TCP traffic already got handled earlier) without DSR info, so we need to flush the `.dsr` flag from a potentially existing CT entry. Otherwise all subsequent TCP packets on this new connection get misdirected down the DSR path (based on that stale `.dsr` flag).

**Comment by julianwiedmann** [comment]
> Did my first round of a review. Amazing PR! Will do a second round once you have added the `to-netdev` diagram.

It's actually pretty straight-forward:

```mermaid
flowchart TD
    A[to-netdev] --> |...| B{"ctx_snat_done()?"}
    B --> |No| C["handle_nat_fwd()"]
    B --> |Yes| B1["// further packet process"]
    C --> |...| D["__handle_nat_fwd_ipv4()"]
    D --> |...| E["nodeport_rev_dnat_fwd_ipv4()"]
    E --> F{"apply RevDNAT for \nreply by local / DSR backend?"}
    F --> |Yes| G["ctx_snat_done_set()"]
    F --> |No| H
    G --> H{"ctx_snat_done()?"}
    H --> |No\n\nCILIUM_CALL_IPV4_NODEPORT_SNAT_FWD| I["tail_handle_snat_fwd_ipv4()"]
    H --> |Yes| B1
    I --> |...| J["snat_v4_nat()"] --> B1
```

File: bpf/bpf_lxc.c (hunk 7 above)
Comment (pchaigno) [reply bpf/bpf_lxc.c:1457]: Thanks for the explanation!

File: bpf/lib/nodeport.h (hunk 9 above)
Comment (pchaigno) [reply bpf/lib/nodeport.h]: Oh, right!

File: bpf/lib/nodeport.h (hunk 10 above)
Comment (pchaigno) [reply bpf/lib/nodeport.h:769]: Got it! Not necessary today, but added for consistency :+1:

File: bpf/lib/nodeport.h (hunk 13 above)
Comment (pchaigno) [reply bpf/lib/nodeport.h:324]: I would add a bit of details to help the reader go from `TCP connections have the DSR Option only in their SYN packet` to "we need to parse the TCP packets". Right now, *why* that means we need this parsing block isn't super obvious.

File: bpf/lib/nodeport.h (hunk 14 above)
Comment (pchaigno) [reply bpf/lib/nodeport.h:337]: Oh, I had not realized the `.dsr` flag was only kept for the TCP SYN packet of each connection and removed afterward. That's new with those changes, right?

File: bpf/lib/nodeport.h (hunk 15 above)
Comment (pchaigno) [reply bpf/lib/nodeport.h:765]: OK. I think I get it.

File: bpf/lib/lb.h (hunk 16 above)
Comment (pchaigno) [reply bpf/lib/lb.h:514]: Fair enough.

File: bpf/lib/nodeport.h [hunk 20]
```diff
@@ -1965,10 +2221,34 @@ static __always_inline int nodeport_lb4(struct __ctx_buff *ctx,
 		 */
 		ctx_set_xfer(ctx, XFER_PKT_NO_SVC);
 
+#ifdef ENABLE_DSR
+		if (nodeport_uses_dsr4(&tuple)) {
```
Comment (brb) [inline bpf/lib/nodeport.h:1996]: I think we need here a comment saying that this is handling a packet to a service which was forwarded by a remote node to us, and that packet has a DSR metadata set.

File: bpf/lib/nodeport.h [hunk 21]
```diff
@@ -1464,8 +1597,32 @@ static __always_inline int dsr_set_opt4(struct __ctx_buff *ctx,
...
+	if (tuple->nexthdr == IPPROTO_TCP) {
+		union tcp_flags tcp_flags = {};
+
+		if (l4_load_tcp_flags(ctx, l4_off, &tcp_flags) < 0)
+			return DROP_CT_INVALID_HDR;
+
+		ipv4_ct_tuple_reverse(&tmp);
+
+		if (!(tcp_flags.value & TCP_FLAG_SYN)) {
+			/* Packet belongs to a tracked DSR connection, so
```
Comment (brb) [inline bpf/lib/nodeport.h]: I'm a bit puzzled how you decide that a `packet belongs to a tracked DSR connection`?  I think this branch can be hit not only by LB traffic, thus the comment might need to be changed.

File: bpf/lib/nodeport.h [hunk 22]
```diff
@@ -1005,31 +1128,41 @@ nodeport_rev_dnat_fwd_ipv6(struct __ctx_buff *ctx, struct trace_ctx *trace)
...
 
-		ctx_snat_done_set(ctx);
+			csum_l4_offset_and_flags(tuple.nexthdr, &csum_off);
+
+			ret = lb6_rev_nat(ctx, l4_off, &csum_off, ct_state.rev_nat_index,
+					  &tuple, REV_NAT_F_TUPLE_SADDR);
+			if (IS_ERR(ret))
+				return ret;
+
+			ctx_snat_done_set(ctx);
```
Comment (brb) [inline bpf/lib/nodeport.h:1023]: Nit for a follow up PR - I think s/ctx_snat_done_set/ctx_snat_not_needed/ would be better naming. In the case of DSR we don't do any SNAT (we  do rev-DNAT).

**Comment by brb** [comment]
Thanks for the diagrams. These we very helpful when doing the review. One more thing which could help with the reviews is to show example CT and SNAT entries for DSR before your changes and after (and maybe where they got created). We could place this info into one of your commit messages.

File: bpf/lib/nodeport.h (hunk 21 above)
Comment (julianwiedmann) [reply bpf/lib/nodeport.h]: The `ct_has_dsr_egress_entry4()` lookup below tells us if a preceding SYN for this TCP connection created a DSR CT entry. So maybe the comment would be better phrased as

> If the packet belongs to a tracked DSR connection, trigger a CT update:

?

File: bpf/lib/nodeport.h (hunk 19 above)
Comment (julianwiedmann) [reply bpf/lib/nodeport.h:1025]: Heh, I'm actually thinking we could combine them into a single flag at some point (and then differentiate based on whether the `.rev_nat_index` is set).

File: bpf/lib/nodeport.h (hunk 14 above)
Comment (julianwiedmann) [reply bpf/lib/nodeport.h:337]: Ah no, let me elaborate a bit more.

For TCP traffic, `nodeport_extract_dsr_v4()` does three things:
1. for non-SYNs, check if they belong to a DSR connection (== match a DSR CT entry). If so, send the packet towards the DSR_INGRESS code (without DSR info).
2. for SYNs, extract DSR info from the IP option. If the info exists, send the packet towards the DSR_INGRESS code (with DSR info).
3. that leaves us with SYNs which don't have embedded DSR info. So effectively a fresh, non-DSR connection. But the same Client->BackendIP connection might have been **previously** established as DSR connection, and still have a dangling DSR CT entry. If we don't clean up that CT entry now, all subsequent non-SYN packets of this fresh (non-DSR!) connection will end up matching that stale CT entry (step 1) and believe they belong to a DSR connection.

File: bpf/lib/nodeport.h (hunk 20 above)
Comment (julianwiedmann) [reply bpf/lib/nodeport.h:1996]: Ah we don't know that yet?

At this point it's merely a packet that **qualifies** for DSR (ie. its L4 protocol has the right type). And we're not just interested in packets that have embedded DSR info, but also non-SYN TCP packets that **match** a DSR connection.

File: bpf/lib/nodeport.h (hunk 22 above)
Comment (julianwiedmann) [reply bpf/lib/nodeport.h:1023]: Yep, that's a good follow-on cleanup :+1:. It's not obvious that we've been overloading the flag with other semantics.

File: bpf/lib/nodeport.h (hunk 20 above)
Comment (brb) [reply bpf/lib/nodeport.h:1996]: > Ah we don't know that yet?

Yep, you are right. Then a comment that a packet **might** have DSR md.

File: bpf/lib/nodeport.h (hunk 14 above)
Comment (pchaigno) [reply bpf/lib/nodeport.h:337]: Got it! Thanks for the explanation!

I don't know if it's new or if I missed it before, but the current comment in `nodeport_extract_dsr_v4` for that code looks good enough to me.

File: bpf/lib/nodeport.h (hunk 21 above)
Comment (brb) [reply bpf/lib/nodeport.h]: Yep, the suggestion :+1:

File: bpf/lib/nodeport.h (hunk 12 above)
Comment (julianwiedmann) [reply bpf/lib/nodeport.h:796]: added
>If a packet belongs to a DSR connection (ie gets handled by
tail_nodeport_dsr_ingress\_\*()), we know it's not reply traffic. Thus
we don't need to jump through CILIUM_CALL\_\*\_NODEPORT_NAT_INGRESS
afterwards, and can circle straight back to CILIUM_CALL\_\*\_FROM_NETDEV.

File: bpf/lib/nodeport.h (hunk 20 above)
Comment (julianwiedmann) [reply bpf/lib/nodeport.h:1996]: Added

> /\* Check if packet has embedded DSR info, or belongs to
>  \* an established DSR connection:
>  \*/

File: bpf/lib/nodeport.h (hunk 21 above)
Comment (julianwiedmann) [reply bpf/lib/nodeport.h]: adjusted

**Comment by julianwiedmann** [comment]
> Thanks for the diagrams. These were very helpful when doing the review. One more thing which could help with the reviews is to show example CT and SNAT entries for DSR before your changes and after (and maybe where they got created). We could place this info into one of your commit messages.

Dumped the following into the commit description for `bpf: nodeport: move DSR handling from bpf_lxc into from/to-netdev`:


> On a CT / SNAT entry level, this change means that:
> 
> - on old code, bpf_lxc would create a CT_INGRESS CT entry and a SNAT entry
>   for a new DSR connection.
> 
>   The CT entry has .dsr set, and is created for the following tuple
>      .daddr = CLIENT_ADDR,
>      .saddr = BACKEND_ADDR,
>      .dport = BACKEND_PORT,
>      .sport = CLIENT_PORT,
>      .flags = TUPLE_F_IN,
> 
>   The SNAT entry contains the DSR info (svc_addr / svc_port), and
>   is created for the following tuple
>      .daddr = CLIENT_ADDR,
>      .saddr = BACKEND_ADDR,
>      .dport = CLIENT_PORT,
>      .sport = BACKEND_PORT,
>      .flags = TUPLE_F_OUT,
> 
> - on new code, lib/nodeport.h creates a CT_EGRESS CT entry and a SNAT entry
>   for a new DSR connection as follows:
> 
>   The CT entry has .dsr set, and is created for the following tuple
>      .daddr = CLIENT_ADDR,
>      .saddr = BACKEND_ADDR,
>      .dport = BACKEND_PORT,
>      .sport = CLIENT_PORT,
>      .flags = TUPLE_F_OUT,    (<-- opposite direction as in bpf_lxc!)
> 
>   The SNAT entry is created exactly as before.
> 
>   bpf_lxc still creates its CT_INGRESS entry as before, but no longer sets
>   the .dsr flag.

File: bpf/lib/nodeport.h (hunk 13 above)
Comment (julianwiedmann) [reply bpf/lib/nodeport.h:324]: Expanded the comment in `nodeport_extract_dsr_v4()`.

**Comment by julianwiedmann** [comment]
Some changes to comments & commit descriptions. Then rebase to pick up d6c423c616.

**Comment by ysksuzuki** [comment]
Tested the latest branch and confirmed that TCP OUT has been fully closed. Awesome!
https://github.com/cilium/cilium/pull/22978#issuecomment-1410184665

```
TCP OUT 10.72.3.2:54493 -> 10.64.0.97:8000 expires=273805 RxPackets=4 RxBytes=393 RxFlagsSeen=0x1b LastRxReport=273795 TxPackets=6 TxBytes=486 TxFlagsSeen=0x1b LastTxReport=273795 Flags=0x0093 [ RxClosing TxClosing SeenNonSyn DSR ] RevNAT=0 SourceSecurityID=2 IfIndex=3
TCP IN 10.72.3.2:54493 -> 10.64.0.97:8000 expires=273805 RxPackets=6 RxBytes=486 RxFlagsSeen=0x1b LastRxReport=273795 TxPackets=4 TxBytes=393 TxFlagsSeen=0x1b LastTxReport=273795 Flags=0x0013 [ RxClosing TxClosing SeenNonSyn ] RevNAT=0 SourceSecurityID=2 IfIndex=0
```

File: pkg/maps/ctmap/ctmap.go [hunk 23]
```diff
@@ -618,9 +619,12 @@ func PurgeOrphanNATEntries(ctMapTCP, ctMapAny *Map) *NatGCStats {
 		} else if natKey.GetFlags()&tuple.TUPLE_F_OUT == tuple.TUPLE_F_OUT {
 			ingressCTKey := ingressCTKeyFromEgressNatKey(natKey)
 			egressCTKey := egressCTKeyFromEgressNatKey(natKey)
+			dsrCTKey := dsrCTKeyFromEgressNatKey(natKey)
 
-			if !ctEntryExist(ctMap, ingressCTKey) && !ctEntryExist(ctMap, egressCTKey) {
-				// No ingress and egress CT entries were found, delete the orphan egress NAT entry
+			if !ctEntryExist(ctMap, ingressCTKey) &&
```
Comment (brb) [inline pkg/maps/ctmap/ctmap.go:624]: Q: once we get are fine to assume that DSR flows created by bpf_lxc no longer exist (probably in v1.15), should remove the `!ctEntryExist(ctMap, ingressCTKey)` condition? If yes, then maybe let's add a TODO code comment.

**Review by brb — APPROVED** [review]
:rocket:

File: pkg/maps/ctmap/ctmap.go (hunk 23 above)
Comment (julianwiedmann) [reply pkg/maps/ctmap/ctmap.go:624]: Yep, let's add that as TODO step in the to-be-opened issue for deprecating the bpf_lxc-level DSR code :+1:

**Review by pchaigno — APPROVED** [review]

**Comment by julianwiedmann** [comment]
Travis flaked in

> ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                                                                                                                                                                                           
> 
> ┃   PANIC  package: github.com/cilium/cilium/operator/pkg/lbipam • TestNonMatchingLBClass   ┃                                                                                                                                                                                           
> 
> ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛                                                                                                                                                                                           
> 
> panic: *resource.resource[*github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1.Service].Events() called from /home/travis/gopath/src/github.com/cilium/cilium/operator/pkg/lbipam/lbipam.go:192 has a broken event handler that did not call Done() before event was garbage collected

which is already WIP (see https://github.com/cilium/cilium/issues/24087 / https://github.com/cilium/cilium/pull/23297).

**Review by gentoo-root — APPROVED** [review]
Looks good to me, as far as I can tell after going though the code and comments.

It would be cool if you could walk me through the diagrams ([from-netdev](https://github.com/cilium/cilium/pull/22978#issue-1525306119) and [to-netdev](https://github.com/cilium/cilium/pull/22978#issuecomment-1448178940)), as there are things I don't fully understand there (especially on the first one :D).

File: pkg/maps/ctmap/ctmap.go (hunk 23 above)
Comment (julianwiedmann) [reply pkg/maps/ctmap/ctmap.go:624]: -> https://github.com/cilium/cilium/issues/24207
