### PR TITLE
CNI: keep cni config on shutdown; taint instead, queue deletions

### LINKED ISSUE #22067: CNI plugin should tolerate a down agent.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

While uninstalling Cilium, deletion of existing pods fails since the agent is down. It fails with the message

` failed to destroy network for sandbox \"\": plugin type=\"cilium-cni\" failed (delete): unable to connect to Cilium daemon: failed to create cilium agent client after 30.000000 seconds timeout: Get \"http:///var/run/cilium/cilium.sock/v1/config\": dial unix /var/run/cilium/cilium.sock: connect: no such file or directory\nIs the agent running?" `

The CNI specification says that, on delete, CNI plugins should be as error-tolerant as possible. So, if at all possible, the CNI binary should be able to handle a deletion without the agent running.

### Cilium Version

v1.13.0-rc2

### Kernel Version

n/a

### Kubernetes Version

n/a

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

Related: https://github.com/cilium/cilium/issues/20723

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by squeed**
This change is made up of several commits, which build on each other. It fixes a wart with how CNI, Containerd, and Dockershim interact, and prevents some possible outage scenarios.

Ultimately, I'd like to make much of this less necessary with an improved CNI STATUS verb, but that will take some time to roll out across the ecosystem.

### Asynchronous CNI delete
The CNI plugin now queues DEL for later submission, rather than failing. It tries to connect to the agent socket, and if that fails, it will write a file in `/run/cilium` with the pod's details. When the agent starts up, it will read that queue and process all pending deletes.

This fixes #22067, where an end-user found themselves with an unrecoverable cluster.  Cilium got descheduled but their node was at its pod limit. They couldn't start any pods, and they couldn't delete any pods without Cilium running. Not good.

### Taint the node when Cilium is shut down

On nodes where Cilium is scheduled, if it is not running, taint the node with NoSchedule. This will prevent new pods from being scheduled there. This has two goals:
1. Minimize ignorable errors from pods failing to start because Cilium can't handle a CNI ADD
2. Minimize pods being started with a non-Cilium network provider

### Preserve CNI configuration 

Lastly, we no longer delete the CNI configuration file when stopping the agent. This has several important effects:
- the node no longer goes NotReady, so it won't be removed from cloud LB backends just because cilium is being upgraded. This prevents unneeded churn.
- CNI DEL will still succeed, so pods can always be cleaned up
- No chance of pods being started with a different CNI provider

```release-note
The Cilium operator now taints nodes where Cilium is scheduled to run but is not running. 
This prevents pods from being scheduled on nodes without Cilium.
The CNI configuration file is no longer removed on agent shutdown. 
This means that pod deletion will always succeed; previously it would fail if Cilium was down for an upgrade.
This should help prevent nodes accidentally entering an unmanageable state.
It also means that nodes are not removed from cloud LoadBalancer backends during Cilium upgrades.
```

Fixes: #22067.

### CODE REVIEW

**Comment by squeed** [comment]
Test failures are either known flakes, or unlikely to be caused by this:
- l4lb XDP doesn't use CNI at all
- TestGetIdentity/Duplicated_identity is a known flake
- MonitorAggregation didn't get all ICMP events. Again, not something this could do.

So, rebasing and retrying to see if that helms.

File: pkg/lock/lockfile/lockfile_linux.go [hunk 1]
```diff
@@ -0,0 +1,118 @@
+// SPDX-License-Identifier: Apache-2.0
```
Comment (christarazi) [inline pkg/lock/lockfile/lockfile_linux.go:1]: We'll need to update the CODEOWNERS for this new file. Not sure what is appropriate? `cilium/sig-agent`?

File: plugins/cilium-cni/main.go [hunk 2]
```diff
@@ -695,7 +688,7 @@ func cmdDel(args *skel.CmdArgs) error {
 		log.WithError(err).Warning("Errors encountered while deleting endpoint")
 	}
 
-	if conf.IpamMode == ipamOption.IPAMDelegatedPlugin {
+	if n.IPAM.Type != "" {
```
Comment (christarazi) [inline plugins/cilium-cni/main.go:692]: I'm not sure I understand why this change is necessary?

File: operator/watchers/node_taint_test.go [hunk 3]
```diff
@@ -420,6 +427,7 @@ func (n *NodeTaintSuite) TestNodeConditionIfCiliumAndNodeAreReady(c *check.C) {
 	mno = markNodeOptions{
 		RemoveNodeTaint:        true,
 		SetCiliumIsUpCondition: true,
+		SetNodeTaint:           false, // too annoying to test this with the same reactor
```
Comment (christarazi) [inline operator/watchers/node_taint_test.go]: I'm not sure what this comment is trying to say

File: Documentation/installation/taints.rst [hunk 4]
```diff
@@ -44,6 +44,9 @@ node. The mechanism works as follows:
 3. From this point on, pods will start being scheduled and running on the node,
    having their networking managed by Cilium.
 
+4. If Cilium is temporarily removed from the node, the operator will re-apply
```
Comment (christarazi) [inline Documentation/installation/taints.rst]: Nit: `operator` -> `Operator`

**Review by christarazi — CHANGES_REQUESTED** [review]
Looks mostly good to me, a few minor comments to address.

If I may share an opinion: I appreciate the PR description because it made reviewing the code much easier, however I'd hate to lose all that context because it isn't somewhere in the commit msg. What do you think of putting it somewhere in the commit(s)? The reason is because when bisecting, it's much easier to read all the context related to a change from the commit msg, rather than think "hmm, I wonder if there's more to this" and have to locate the PR behind it. 

What I've seen people do (and what I try to do as well) is paste the "important" commit msgs in the PR description as well, so people sort of have a cover letter to read before diving in, as you did in your PR, while also preserving the history in the commit(s) themselves.

On another note, for the release note: I'd suggest stripping the extra newlines as it's not going to format quite as nicely in the end. Something like this would be easier to read:

```
This is sentence 1 of the release note.
This is sentence 2 of the same release note.
And so on...
```

File: plugins/cilium-cni/main.go (hunk 2 above)
Comment (squeed) [reply plugins/cilium-cni/main.go:692]: `conf` is retrieved from the agent's API, but we need to be able to proceed even if its down. Good question.

File: operator/watchers/node_taint_test.go (hunk 3 above)
Comment (squeed) [reply operator/watchers/node_taint_test.go]: Mostly explaining why this particular test isn't, well, testing everything. I'll clarify.

File: pkg/lock/lockfile/lockfile_linux.go (hunk 1 above)
Comment (squeed) [reply pkg/lock/lockfile/lockfile_linux.go:1]: Do we? `pkg/lock` is already in CODEOWNERS, wouldn't that cover it?

Comment (christarazi) [reply pkg/lock/lockfile/lockfile_linux.go:1]: Ah, yes. My eyes just glazed over the `pkg/lock` part and thought I saw `pkg/lockfile`. :+1:

File: plugins/cilium-cni/main.go (hunk 2 above)
Comment (christarazi) [reply plugins/cilium-cni/main.go:692]: That makes sense. But my main question was about the previous logic checking against `ipamOption.IPAMDelegatedPlugin` and now we aren't. How come?

File: pkg/defaults/defaults.go [hunk 5]
```diff
@@ -106,6 +106,11 @@ const (
 	// PidFilePath is the path to the pid file for the agent.
 	PidFilePath = RuntimePath + "/cilium.pid"
 
+	// XXX doc
```
Comment (qmonnet) [inline pkg/defaults/defaults.go]: Please update (same for `DeleteQueueLockfile`).

The rest of the PR looks good to me, but I only took a very brief look at the Go code.

File: pkg/lock/lockfile/lockfile_linux.go [hunk 6]
```diff
@@ -0,0 +1,118 @@
...
+func NewLockfile(path string) (*Lockfile, error) {
+	fp, err := os.OpenFile(path, os.O_RDWR|os.O_CREATE, 0644)
+	if err != nil {
+		return nil, fmt.Errorf("failed to create lockfile %s: %w", path, err)
+	}
+
+	return &Lockfile{
+		fp: fp,
+	}, nil
+
```
Comment (qmonnet) [inline pkg/lock/lockfile/lockfile_linux.go]: Nit: blank line

File: plugins/cilium-cni/main.go (hunk 2 above)
Comment (christarazi) [reply plugins/cilium-cni/main.go:692]: @squeed ^

**Review by christarazi — APPROVED** [review]

**Review by sayboras — APPROVED** [review]
This PR is not only interesting but alsoo fun to read, love the comment in code :+1:.

LGTM :heavy_check_mark:

**Comment by squeed** [comment]
Setting this as blocked; I want to merge https://github.com/cilium/cilium/pull/24009 first. Then I'll rebase on that.

File: plugins/cilium-cni/main.go (hunk 2 above)
Comment (christarazi) [reply plugins/cilium-cni/main.go:692]: Any updates here?

**Comment by squeed** [comment]
OK, the PR I was waiting for has merged. This has been rebased and is ready for review (no behavior or code has changed).

File: plugins/cilium-cni/main.go (hunk 2 above)
Comment (squeed) [reply plugins/cilium-cni/main.go:692]: So, there are two separate configuration "knobs" here: whether or not there is a delegated IPAM plugin provided in the CNI configuration file, and whether or not the daemon is in delegated-ipam mode.

For CNI ADD, we check both: there needs to be user-added configuration in the IPAM section of the CNI configuration file, as well as the daemon configured for delegated ipam mode.

For DEL, we don't have the ability to query the daemon. So, we check only for a user-supplied IPAM plugin in the CNI configuration, and always use that.

This is actually safe. On the off chance that the user has supplied an IPAM plugin, but the daemon is not configured to use delegated IPAM, we will _still do the IPAM cleanup_ in the agent, by the very nature of the EndpointDelete API call. And the delegated IPAM plugin will get a DEL for which it doesn't have an ADD, which, according to the CNI spec, it must ignore.

File: pkg/defaults/defaults.go (hunk 5 above)
Comment (squeed) [reply pkg/defaults/defaults.go]: ouch. good point.

File: plugins/cilium-cni/main.go (hunk 2 above)
Comment (squeed) [reply plugins/cilium-cni/main.go:692]: @christarazi make sense?

**Comment by squeed** [comment]
(rebased to pick up test changes)

File: plugins/cilium-cni/main.go (hunk 2 above)
Comment (christarazi) [reply plugins/cilium-cni/main.go:692]: :+1:

File: plugins/cilium-cni/lib/deletion_queue.go [hunk 7]
```diff
@@ -0,0 +1,133 @@
...
+		return fmt.Errorf("failed to acquire lock: %w", err)
+	}
+	dc.lockfile = lf
+	return nil
+}
+
+// EndpointDelete deletes an endpoint given by an endpoint id, either
+// by directly accessing the API or dropping in a queued-deletion file.
+// endpoint-id is a qualified endpoint reference, e.g. "container-id:XXXXXXX"
+func (dc *DeletionFallbackClient) EndpointDelete(id string) error {
```
Comment (chancez) [inline plugins/cilium-cni/lib/deletion_queue.go:112]: Should there be a cap on how many queued deletes we allow? Just in case it grows indefinitely?

Comment (squeed) [reply plugins/cilium-cni/lib/deletion_queue.go:112]: That's a good idea for a few reasons
- protect against some kind of kubelet total insanity
- prevent against a downgrade where the agent is no longer processing deletions

I'll add it.

Comment (squeed) [reply plugins/cilium-cni/lib/deletion_queue.go:112]: Done!

Comment (christarazi) [reply plugins/cilium-cni/lib/deletion_queue.go:112]: I agree this is a nice change. I wonder if it would also be useful if we had some sort of preemptive warning as a log msg as we approach the hard limit (maybe at 75%, 90%, 95%?). Given the CNI binary has no way to export metrics AFAIK, we don't really have visibility as to what's happening with this queue. Also open to other ideas that could give us visibility. Ideally, this is a metric and we ship an alert with it as well.

In general, one of the major goals for Cilium moving forward is better supportability and that includes visibility. One quick way to do that is to enumerate the hard limits in Cilium and ensure Cilium doesn't just all of a sudden stop to a grinding halt when it reaches them.

**Review by qmonnet — APPROVED** [review]
Nice!

File: plugins/cilium-cni/lib/deletion_queue.go (hunk 7 above)
Comment (squeed) [reply plugins/cilium-cni/lib/deletion_queue.go:112]: That's a fair observation, and I also dislike systems that have surprises. In this case, it's difficult to export this as a metric because it's only in play when the agent is down :-).

The potential failure mode here - the queue filling up - is equivalent to the behavior before this PR: CNI deletion fails explicitly and is retried by the kubelet. Very different semantics than, say, bpf map exhaustion. Given that there is a clean fallback, I'd say it's OK not to add complicated guard-rails or alerting here.

File: daemon/cmd/deletion_queue.go [hunk 8]
```diff
@@ -0,0 +1,86 @@
...
+//
+// Returns a done function that drops the lock. It should be called
+// after the server is running.
+func (d *Daemon) processQueuedDeletes() func() {
+	if err := os.MkdirAll(defaults.DeleteQueueDir, 0755); err != nil {
+		log.WithError(err).WithField("path", defaults.DeleteQueueDir).Error("Failed to ensure deletion queue directory exists")
+		return func() {}
+	}
+
+	log.Infof("Processing queued endpoint deletions")
```
Comment (christarazi) [inline daemon/cmd/deletion_queue.go]: Nit: no need for `Infof`

File: daemon/cmd/deletion_queue.go [hunk 9]
```diff
@@ -0,0 +1,86 @@
...
+			lf.Unlock()
+		}
+		if lf != nil {
+			lf.Close()
+		}
+	}
+
+	lf, err := lockfile.NewLockfile(defaults.DeleteQueueLockfile)
+	if err != nil {
+		log.WithError(err).WithField("filename", defaults.DeleteQueueLockfile).Error("Failed to create ")
```
Comment (christarazi) [inline daemon/cmd/deletion_queue.go]: Nit: we already have a logfield for file paths, we should prefer this one for the sake of consistency especially in structured logging. Please also apply for each occurrence.

```suggestion
		log.WithError(err).WithField(logfields.Path, defaults.DeleteQueueLockfile).Error("Failed to create ")
```

Comment (christarazi) [reply daemon/cmd/deletion_queue.go]: This one feels more like a warning because Cilium is still proceeding anyway. 

```suggestion
		log.WithError(err).WithField("filename", defaults.DeleteQueueLockfile).Warn("Failed to create CNI delete directory queue lockfile. Proceeding with deletion anyway")
```

File: daemon/cmd/deletion_queue.go [hunk 10]
```diff
@@ -0,0 +1,86 @@
...
+		return unlock
+	}
+
+	ctx, cancel := context.WithTimeout(d.ctx, 10*time.Second)
+	defer cancel()
+	err = lf.Lock(ctx, true)
+	if err != nil {
+		log.WithError(err).Error("Failed to lock deletion directory, proceeding anyways")
```
Comment (christarazi) [inline daemon/cmd/deletion_queue.go]:
```suggestion
		log.WithError(err).Warn("Failed to lock CNI deletion directory, proceeding anyways")
```

What are the consequences of this failure? What should the user know?

File: daemon/cmd/deletion_queue.go [hunk 11]
```diff
@@ -0,0 +1,86 @@
...
+		locked = true
+	}
+
+	// OK, we have the lock; process the deletes
+	files, err := filepath.Glob(defaults.DeleteQueueDir + "/*.delete")
+	if err != nil {
+		log.WithError(err).Error("Failed to list deletion files")
+	}
+
+	log.Infof("processing %d queued deletion requests", len(files))
```
Comment (christarazi) [inline daemon/cmd/deletion_queue.go]:
```suggestion
	files, err := filepath.Glob(defaults.DeleteQueueDir + "/*.delete")
	if err != nil {
		log.WithError(err).Error("Failed to list deletion files. Unable to process CNI deletion queue. Endpoint queued for deletion will not be deleted")
	} else { 
	  log.Infof("processing %d queued deletion requests", len(files))
	  }
```

File: daemon/cmd/deletion_queue.go [hunk 12]
```diff
@@ -0,0 +1,86 @@
...
+	for _, file := range files {
+		// get the container id
+		epID, err := os.ReadFile(file)
+		if err != nil {
+			log.WithError(err).WithField("filename", file).Error("failed to read deletion file")
```
Comment (christarazi) [inline daemon/cmd/deletion_queue.go]:
```suggestion
			log.WithError(err).WithField("filename", file).Error("Failed to read deletion file; endpoint will not be deleted")
```

File: daemon/cmd/deletion_queue.go [hunk 13]
```diff
@@ -0,0 +1,86 @@
...
+		} else {
+			_, _ = d.DeleteEndpoint(string(epID)) // this will log errors elsewhere
+		}
+
+		if err := os.Remove(file); err != nil {
+			log.WithError(err).WithField("filename", file).Error("failed to remove processed deletion file")
```
Comment (christarazi) [inline daemon/cmd/deletion_queue.go]:
```suggestion
			log.WithError(err).WithField("filename", file).Warn("failed to remove processed deletion file, however the endpoint was deleted")
```

**Review by christarazi — COMMENTED** [review]
Apologies for extending this PR, but upon a second read, I noticed that the error logs are quite terse. I think we'd benefit from providing more context when there are warnings / errors, because we don't want the user to then think, "OK well I've got this error, but what should I do / what is Cilium going to do about it?".

Minor comments below.

File: plugins/cilium-cni/lib/deletion_queue.go (hunk 7 above)
Comment (christarazi) [reply plugins/cilium-cni/lib/deletion_queue.go:112]: Fair enough. A note in the code where we fallback would be good to call out as a comment so that future readers know that that was an explicit design decision. We can also revisit it in the future if this theoretical problem actually turns up in the wild and at least we will have documented our assumptions of it in the code.

File: daemon/cmd/deletion_queue.go (hunk 10 above)
Comment (squeed) [reply daemon/cmd/deletion_queue.go]: I've been thinking about this. On the one hand, it means we might miss an endpoint deletion in the worst possible case. On the other hand, I really **really** don't want to ever block agent startup for something non-critical. Plus, we might as well proceed with cleanup regardless.

One possible error message would be "Failed to lock CNI deletion directory, proceeding anyways. This may cause CNI deletions to be missed" which sounds drastic but is technically correct.

Thoughts?

Comment (christarazi) [reply daemon/cmd/deletion_queue.go]: I think it's fair enough.

**Comment by squeed** [comment]
@christarazi updated the logging based on your suggestions, thanks for the review.

**Review by christarazi — APPROVED** [review]

**Comment by squeed** [comment]
[jenkins job failure](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.26-kernel-net-next/1412/testReport/junit/Suite-k8s-1/26/K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master/) is because of a missed tail call!? This PR has nothing to do with BPF...

```
time="2023-03-21T21:17:36Z" level=debug msg="running local command: kubectl exec -n kube-system cilium-dj8v9 -- cilium metrics list -o json | jq '.[] | select( .name == \"cilium_drop_count_total\" and .labels.reason == \"Missed tail call\" ).value'"
cmd: "kubectl exec -n kube-system cilium-dj8v9 -- cilium metrics list -o json | jq '.[] | select( .name == \"cilium_drop_count_total\" and .labels.reason == \"Missed tail call\" ).value'" exitCode: 0 duration: 168.910676ms stdout:
1
```

**Comment by squeed** [comment]
/test-1.26-net-next

**Review by chancez — APPROVED** [review]

**Comment by aojea** [comment]
it is sad we don't have a better defined processs for the Pod lifecycle in k8s so we don't have to implement these things :(

**Comment by robbie-demuth** [comment]
Forgive me if there's an obvious answer to this question, but, out of curiosity, why a `NoSchedule` taint as opposed to a `NoExecute` taint? If Cilium isn't running, pods already scheduled to the node will presumably run into issues. Why not apply a `NoExecute` taint so that they're evicted and rescheduled elsewhere? A `NoExecute` taint presumably shouldn't evict Cilium itself since it's a daemon set pod

**Comment by squeed** [comment]
That is a fine idea. I initially did NoExecute as well to catch pods that were scheduled but not yet picked up by the Kubelet, but I agree that it's too drastic an effect.

**Comment by bmendoza820** [comment]
> That is a fine idea. I initially did NoExecute as well to catch pods that were scheduled but not yet picked up by the Kubelet, but I agree that it's too drastic an effect.

What are your thoughts on updating the behavior to actually apply a NoExecute? Or could this be parameterized similar to how we are able to set the `agent-not-ready-taint-key`?

**Comment by squeed** [comment]
Actually, I got this backwards; I set a NoSchedule taint and avoided a NoExecute taint. The reason is that running pods do not need to be evicted when Cilium goes down, as they are running and should not be disrupted.

**Comment by bmendoza820** [comment]
> Actually, I got this backwards; I set a NoSchedule taint and avoided a NoExecute taint. The reason is that running pods do not need to be evicted when Cilium goes down, as they are running and should not be disrupted.

When Cilium goes down, the running pods lose connectivity. Shouldn't they be evicted so that they can be rescheduled onto other nodes where Cilium is running? We encountered this scenario recently and experienced some service outages because the pods were not rescheduled elsehwere.

**Comment by squeed** [comment]
> When Cilium goes down, the running pods lose connectivity. 

Generally, that shouldn't happen, with the exception of flows being sent through the userspace L7 proxy. Do you suspect a Cilium bug?

**Comment by bmendoza820** [comment]
> > When Cilium goes down, the running pods lose connectivity.
> 
> Generally, that shouldn't happen, with the exception of flows being sent through the userspace L7 proxies. Do you suspect a Cilium bug?

Oh, this is not what we observed (or perhaps what we observed were failed network calls sent through the userspace L7 proxies). We saw several reported failed connection attempts for the duration that the nodes had the `NoSchedule` taint applied. This lasted for several hours until our autoscaler conducted node consolidation.
