### PR TITLE
node: Install individual per node routes

### LINKED ISSUE #1846: Cilium agent drops all DNS requests host is trying to make
"I've been having a couple issues and was hoping to get a push in the right direction if possible. I'm attempting to switch one of our beta kubernetes clusters to cilium, in the hopes that we get comfortable enough to use it in production. The problem I am having is that the cilium agent is dropping all dns requests the host is trying to make. This is making it so that the cilium container never reaches a ready state (as api comunication is not working)."
Environment information:
```
OS: CoreOS 1409.7.0
Kubernetes version: 1.6.4
Cilium version: latest stable
Pod CIDR: 10.2.0.0/24
Node CIDR: 10.8.0.0/24
Monitor output:
Error: xx drop (No tunnel/encapsulation endpoint), to endpoint 0, identity 0->0: <host ip>:45040 -> <ip from resolv.conf>:53 udp
```

### PR DESCRIPTION
**Pull request by tgraf**
The route pointing packets from the host to IPs managed by other nodes
has been covered by a single cluster wide route prefix which covered all
nodes. This did not allow to have any non Cilium IPs unless the IPs were
associated to the local host.

 * Merge node and nodeaddress package together as they depend on each
   other.

 * Move route and address addition from the init.sh script to golang
   native code in pkg/node to allow tiggering route additions based
   on events.

 * Add a per node route for each node discovered in the cluster

Fixes: #1846

Signed-off-by: Thomas Graf <thomas@cilium.io>

### CODE REVIEW

File: pkg/node/logfields.go [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+// Unless required by applicable law or agreed to in writing, software
+// distributed under the License is distributed on an "AS IS" BASIS,
+// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+// See the License for the specific language governing permissions and
+// limitations under the License.
+
+package node
+
+const (
+	fieldRoute = "route"
```
Comment (aanm) [inline pkg/node/logfields.go]: So, which package will have its logfields defined? CC @raybejjani

File: pkg/node/manager.go [hunk 2]
```diff
@@ -64,12 +67,195 @@ func deleteNodeCIDR(ip *net.IPNet) {
...
+		}
+
+		scopedLog.Info("Added L2 nexthop route")
+	}
+
+	return nil
+}
+
+func replaceNodeRoute(ip *net.IPNet) {
+	link, err := netlink.LinkByName("cilium_host")
```
Comment (aanm) [inline pkg/node/manager.go]: Use a const for `cilium_host`

File: pkg/node/manager.go [hunk 3]
```diff
@@ -64,12 +67,195 @@ func deleteNodeCIDR(ip *net.IPNet) {
...
+	scopedLog := log.WithField(fieldRoute, route)
+
+	if err := netlink.RouteDel(&route); err != nil {
+		scopedLog.WithError(err).Debug("Old node route does not exist")
+	}
+
+	if err := netlink.RouteAdd(&route); err != nil {
+		scopedLog.WithError(err).Error("Unable to add node route")
+	} else {
+		scopedLog.Info("Installed node route")
```
Comment (aanm) [inline pkg/node/manager.go]: If I was a user, I wouldn't understand which node route is this. Can you add the specific route that was installed?

File: pkg/node/manager.go [hunk 4]
```diff
@@ -64,12 +67,195 @@ func deleteNodeCIDR(ip *net.IPNet) {
...
+			return fmt.Errorf("unable to add L2 nexthop route")
+		}
+
+		scopedLog.Info("Added L2 nexthop route")
+	}
+
+	return nil
+}
+
+func replaceNodeRoute(ip *net.IPNet) {
```
Comment (aanm) [inline pkg/node/manager.go]: Can you add a description to that function of what it does?

**Review by aanm — CHANGES_REQUESTED** [review]

File: bpf/init.sh [hunk 5]
```diff
@@ -16,18 +16,13 @@
...
 RUNDIR=$2
-IP6_ROUTER=$3
-IP4_HOST=$4
-IP6_HOST=$5
-IP4_RANGE=$6
-IP6_RANGE=$7
-IP4_SVC_RANGE=$8
-IP6_SVC_RANGE=$9
-MODE=${10}
+IP4_HOST=$3
```
Comment (raybejjani) [inline bpf/init.sh:19]: Not too relevant, but we could use `shift` to avoid renumbering args on refactor. This doesn't happen too often, though.

File: daemon/daemon.go [hunk 6]
```diff
@@ -946,30 +935,27 @@ func NewDaemon(c *Config) (*Daemon, error) {
...
 	}
 
 	if v6ServicePrefix != AutoCIDR {
-		_, _, err := net.ParseCIDR(v6ServicePrefix)
+		_, ipnet, err := net.ParseCIDR(v6ServicePrefix)
 		if err != nil {
 			log.WithError(err).WithField(logfields.V6Prefix, v6ServicePrefix).Fatal("Invalid IPv6 service prefix")
 		}
+
+		node.AddAuxPrefix(ipnet)
```
Comment (raybejjani) [inline daemon/daemon.go:949]: This should be the else case for if `err != nil` since we don't exit/return on error.

File: daemon/daemon.go [hunk 7]
```diff
@@ -920,24 +907,26 @@ func NewDaemon(c *Config) (*Daemon, error) {
...
 	}
 
 	if v4ServicePrefix != AutoCIDR {
-		_, _, err := net.ParseCIDR(v4ServicePrefix)
+		_, ipnet, err := net.ParseCIDR(v4ServicePrefix)
 		if err != nil {
 			log.WithError(err).WithField(logfields.V4Prefix, v4ServicePrefix).Fatal("Invalid IPv4 service prefix")
 		}
+
+		node.AddAuxPrefix(ipnet)
```
Comment (raybejjani) [inline daemon/daemon.go:929]: This should be the else case for if err != nil since we don't exit/return on error.

File: pkg/node/logfields.go (hunk 1 above)
Comment (tgraf) [reply pkg/node/logfields.go]: log fields which are specific to a package don't need to be global but I'm open to a discussion

File: pkg/node/manager.go (hunk 3 above)
Comment (tgraf) [reply pkg/node/manager.go]: The `scopedLog` contains the full route description as field.

File: pkg/k8s/init.go [hunk 8]
```diff
@@ -34,22 +34,21 @@ func Init() error {
...
+		node.SetName(nodeName)
 
 		k8sNode, err := GetNode(Client(), nodeName)
 		if err != nil {
 			return fmt.Errorf("unable to retrieve k8s node information: %s", err)
 		}
 
-		node := ParseNode(k8sNode)
+		n := ParseNode(k8sNode)
+		log.Infof("Retrieved node's %s information from kubernetes", n.Name)
```
Comment (raybejjani) [inline pkg/k8s/init.go]: `log.WithField(logfields.NodeName, n.Name).Info("Retrieved node information from kubernetes")` to be consistent with our logrus usage.

File: pkg/node/logfields.go (hunk 1 above)
Comment (raybejjani) [reply pkg/node/logfields.go]: Good question. `fieldRoute` is used in an Error message, and it is likely to be common in logs. I'd vote to put it in logfields.

File: pkg/node/manager.go (hunk 2 above)
Comment (tgraf) [reply pkg/node/manager.go]: fixed

File: pkg/node/manager.go (hunk 4 above)
Comment (tgraf) [reply pkg/node/manager.go]: fixed

File: pkg/node/manager.go [hunk 9]
```diff
@@ -41,8 +41,11 @@ const (
 )
 
 var (
-	mutex lock.RWMutex
-	nodes = map[Identity]*Node{}
+	mutex                 lock.RWMutex
+	nodes                 = map[Identity]*Node{}
+	ciliumHostInitialized = false
+	usePerNodeRoutes      = false
+	auxPrefixes           = []*net.IPNet{}
```
Comment (raybejjani) [inline pkg/node/manager.go]: Since these are package variables (which is probably unintentional) and file variables, could you comment what/when/how they're to be used. In particular, what is mutex protecting?

File: pkg/node/manager.go (hunk 3 above)
Comment (raybejjani) [reply pkg/node/manager.go]: The scopedLog already has route in it so it should be reported in both the Error and Info.

File: pkg/node/manager.go [hunk 10]
```diff
@@ -64,12 +67,195 @@ func deleteNodeCIDR(ip *net.IPNet) {
...
+		routerIP = nil
+		routerNet = &net.IPNet{IP: via, Mask: net.CIDRMask(128, 128)}
+		local = GetIPv6()
+	}
+
+	if err := replaceNexthopRoute(link, routerIP, routerNet); err != nil {
+		log.WithError(err).Error("Unable to add nexthop route")
+	}
+
+	route := netlink.Route{LinkIndex: link.Attrs().Index, Dst: ip, Gw: via, Src: local}
```
Comment (raybejjani) [inline pkg/node/manager.go:219]: We delete then add the same route object. Does this work because netlink.RouteDel matches only on some of the fields?

File: pkg/node/manager.go [hunk 11]
```diff
@@ -64,12 +67,195 @@ func deleteNodeCIDR(ip *net.IPNet) {
...
+		scopedLog.WithError(err).Error("Unable to add node route")
+	} else {
+		scopedLog.Info("Installed node route")
+	}
+}
+
+func installHostRoutes() {
+	if !ciliumHostInitialized {
+		return
+	}
```
Comment (raybejjani) [inline pkg/node/manager.go]: Since we went to all the effort to guard this (in InstallHostRoutes and here in installHostRoutes) we should log something here, or return an error that can be logged at the callers.

**Review by raybejjani — CHANGES_REQUESTED** [review]

**Review by aanm — APPROVED** [review]

File: daemon/daemon.go (hunk 7 above)
Comment (raybejjani) [reply daemon/daemon.go:929]: oh, nevermind, it's a fatal

File: daemon/daemon.go (hunk 6 above)
Comment (raybejjani) [reply daemon/daemon.go:949]: oh, nevermind, it's a fatal

File: bpf/init.sh (hunk 5 above)
Comment (tgraf) [reply bpf/init.sh:19]: @scanf is working on removing `init.sh` entirely in favor of a golang native implementation.

File: pkg/k8s/init.go (hunk 8 above)
Comment (tgraf) [reply pkg/k8s/init.go]: fixed

File: pkg/node/logfields.go (hunk 1 above)
Comment (tgraf) [reply pkg/node/logfields.go]: Moved to `logfields`

File: pkg/node/manager.go (hunk 9 above)
Comment (tgraf) [reply pkg/node/manager.go]: fixed

File: pkg/node/manager.go (hunk 10 above)
Comment (tgraf) [reply pkg/node/manager.go:219]: I was worried that `RouteReplace` does not have the correct semantics. I double checked and it does so I will be replacing this with a single `netlink.RouteReplace()` call

File: pkg/node/manager.go (hunk 11 above)
Comment (tgraf) [reply pkg/node/manager.go]: The case where we might hit this is if the Kubernetes watcher is installed before we put the `cilium_host` device in place in which case we will start collecting node information without being able to install the routes. They will be installed when we add the device. I'll add a debug statement to indicate that installation was deferred.

**Review by raybejjani — APPROVED** [review]

**Review by aalemayhu — APPROVED** [review]

**Review by manalibhutiyani — APPROVED** [review]
Looks good.
