### PR TITLE
bpf:nat: restore a NAT entry if its REV NAT is not found

### LINKED ISSUE #34833: NAT LRU Eviction due to Full Capacity
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.14.13 

### What happened?

This issue is intended to track a branch of the BPF SNAT improvements issue #31643, where we see LRU eviction due to full capacity.  As we discussed in the community meeting,   we might have a longer term goal and some short term enhancement we can look into.

Long term Goals:
1. The fundamental problem is that we store the NAT entries in pairs, but the LRU eviction is not aware of this context.  The connection will be interrupted if one of the entries is evicted.  So if we can combine the out-going entry with its response entry into a single one, we can permanently solve this problem.  AFAIU, this is still in idea phase,  and might have further impact beyond solving the eviction problem itself.
2. Kernel side eviction behavior improvement?

Short term Enhancements:

We may just restore the response entry whenever we do a out-going entry lookup.  However,  it comes with some cons:
1.  Since we are already at capacity,  this is likely to have domino effects on other connections. Maybe we can run reproduction or load test to see if this patch mitigate the issue. 
3. This is also relying on the outbound packet to re-establish SNAT, which might not be available all the time.

 

### How can we reproduce the issue?

Repro in #29305 applies here, but I will update with further repro steps once I starts to work on the PR mentioned above. 

### Cilium Version

v1.14+ 

### Kernel Version

5.10+

### Kubernetes Version

1.24+

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sugangli**
NAT Map LRU behavior could evict any entry in the MAP. This change restore a reverse NAT entry when it is expected but not found.  Previously, we were only relying on existence of forwarding NAT to determine if the NAT pair exists or not.  

This fix is verified by using the same repro steps in  #34833.  After the fix, we saw much less timeout from the client, but the case like eviction happens between TCP SYN and TCP SYN ACK will still drop the returning packets.

Fixes: #34833

### CODE REVIEW

File: bpf/lib/nat.h [hunk 1]
```diff
@@ -312,8 +313,10 @@ snat_v4_nat_handle_mapping(struct __ctx_buff *ctx,
 	if (*state) {
 		int ret;
 		struct ipv4_ct_tuple rtuple = {};
-
-		if (target->addr == (*state)->to_saddr &&
+		set_v4_rtuple(tuple, *state, &rtuple);
+		rstate = __snat_lookup(map, &rtuple);
+		if (rstate &&
```
Comment (sypakine) [inline bpf/lib/nat.h]: Add a comment explaining that we want to ensure there is a reverse entry.

**Comment by sugangli** [comment]
Hi @joestringer, let me know if I need to add anything else to this PR.

File: bpf/lib/nat.h [hunk 2]
```diff
@@ -312,24 +313,25 @@ snat_v4_nat_handle_mapping(struct __ctx_buff *ctx,
...
-
-		if (target->addr == (*state)->to_saddr &&
+		/* reverse SNAT entries could be missing due to LRU eviction */
+		set_v4_rtuple(tuple, *state, &rtuple);
+		rstate = __snat_lookup(map, &rtuple);
+		if (rstate &&
+		    target->addr == (*state)->to_saddr &&
 		    needs_ct == (*state)->common.needs_ct) {
 			barrier_data(*state);
 			return 0;
```
Comment (sypakine) [inline bpf/lib/nat.h:340]: Aside: should this be replaced with `CTX_ACT_OK`?

File: bpf/lib/nat.h [hunk 3]
```diff
@@ -312,24 +313,25 @@ snat_v4_nat_handle_mapping(struct __ctx_buff *ctx,
 	if (*state) {
 		int ret;
 		struct ipv4_ct_tuple rtuple = {};
-
-		if (target->addr == (*state)->to_saddr &&
+		/* reverse SNAT entries could be missing due to LRU eviction */
```
Comment (sypakine) [inline bpf/lib/nat.h]: nit: this comment could be clearer:

```
Check for the reverse SNAT entry. If it is missing (e.g. due to LRU eviction), it must be restored before returning.
```

File: bpf/lib/nat.h [hunk 4]
```diff
@@ -312,24 +313,25 @@ snat_v4_nat_handle_mapping(struct __ctx_buff *ctx,
...
+		    target->addr == (*state)->to_saddr &&
 		    needs_ct == (*state)->common.needs_ct) {
 			barrier_data(*state);
 			return 0;
 		}
 
-		/* Recreate the SNAT and RevSNAT entries if the source IP is stale.
-		 * Otherwise, the packet will be erroneously SNATed with the stale
-		 * source IP.
+		/* Recreate the SNAT and RevSNAT entries if the source IP is stale,
```
Comment (sypakine) [inline bpf/lib/nat.h]: consider: when there are multiple cases, it reads better as a list and allows items to be added without touching other comment lines unnecessarily:

```
Recreate the SNAT and RevSNAT entries if any of:
- Source IP is stale
- RevSNAT entry is missing

Otherwise, the packet will be erroneously SNATed with the stale source IP or dropped.
```

**Review by sypakine — APPROVED** [review]

File: bpf/lib/nat.h (hunk 2 above)
Comment (sugangli) [reply bpf/lib/nat.h:340]: This is not the final stage of the packet. Returning CTX_ACT_OK may be too early?

File: bpf/lib/nat.h (hunk 4 above)
Comment (sugangli) [reply bpf/lib/nat.h]: Done.

File: bpf/lib/nat.h (hunk 3 above)
Comment (sugangli) [reply bpf/lib/nat.h]: Done.

File: bpf/lib/nat.h (hunk 2 above)
Comment (sypakine) [reply bpf/lib/nat.h:340]: `CTX_ACT_OK` is just an alias for `0`

Don't worry about this though, marked it as an aside (i.e. a follow-up for anyone).

Comment (sugangli) [reply bpf/lib/nat.h:340]: Yup.  I was checking  the convention of  using `CTX_ACT_OK`,  other places seem to be the final stages.

**Comment by joestringer** [comment]
@gentoo-root Do you have intentions to review this PR or can you find someone else from @cilium/sig-datapath ?

File: bpf/lib/nat.h [hunk 5]
```diff
@@ -312,24 +313,28 @@ snat_v4_nat_handle_mapping(struct __ctx_buff *ctx,
 	if (*state) {
 		int ret;
 		struct ipv4_ct_tuple rtuple = {};
-
-		if (target->addr == (*state)->to_saddr &&
+		/* Check for the reverse SNAT entry. If it is missing (e.g. due to LRU
```
Comment (tommyp1ckles) [inline bpf/lib/nat.h]: Changes seem reasonable, I'm a little bit concerned with any possible regressions here resulting in unnecessary/unnoticed recreations of nat mappings.

Perhaps it would make sense to make sure there's some coverage of this particular scenario over in bpf/tests/bpf_nat_tests.c?

Comment (sugangli) [reply bpf/lib/nat.h]: @tommyp1ckles Thanks for the comment.  I was thinking what could be an unnoticed recreation? I am assuming fwd tuple and rev tuple should always co-exist. The only case is when they become orphaned, we don't need to recreate them and it is OK to stay broken. But this path won't touch the orphaned entries.

**Review by julianwiedmann — CHANGES_REQUESTED** [review]
Could you please also add the IPv6 part of the fix?

Agree with Tom that this needs tests. I could see a `bpf_host` test under `bpf/tests/` that walks through the desired packet flow, and reproduces the whole scenario you're fixing:

1. transmit a packet, have it SNATed
2. receive a reply for that connection, check that it gets revSNATed
3. manually delete the revSNAT entry
4. receive a second reply, check that it no longer gets revSNATed 
5. transmit a second packet, validate that it re-creates the missing state
6. receive a third reply, check that it gets revSNATed again

File: bpf/lib/nat.h (hunk 5 above)
Comment (sugangli) [reply bpf/lib/nat.h]: Added the tests.

**Comment by sugangli** [comment]
> Could you please also add the IPv6 part of the fix?
> 
> Agree with Tom that this needs tests. I could see a `bpf_host` test under `bpf/tests/` that walks through the desired packet flow, and reproduces the whole scenario you're fixing:
> 
> 1. transmit a packet, have it SNATed
> 2. receive a reply for that connection, check that it gets revSNATed
> 3. manually delete the revSNAT entry
> 4. receive a second reply, check that it no longer gets revSNATed
> 5. transmit a second packet, validate that it re-creates the missing state
> 6. receive a third reply, check that it gets revSNATed again

@julianwiedmann There are existing flows for 1 and 2.  Adding following tests to cover 3 to 6.

File: bpf/tests/tc_nodeport_lb4_nat_lb.c [hunk 6]
```diff
@@ -914,3 +914,212 @@ int nodeport_nat_fwd_reply_no_fib_check(__maybe_unused const struct __ctx_buff *
 {
 	return check_reply(ctx);
 }
+
+/* The following three tests are checking the scenario where a Rev NAT entry gets
+ * deleleted:
```
Comment (tommyp1ckles) [inline bpf/tests/tc_nodeport_lb4_nat_lb.c]: typo: deleleted

File: bpf/lib/nat.h [hunk 7]
```diff
@@ -1220,9 +1231,7 @@ snat_v6_nat_handle_mapping(struct __ctx_buff *ctx,
 		if (IS_ERR(ret))
 			return ret;
 
-		set_v6_rtuple(tuple, *state, &rtuple);
-		*state = snat_v6_lookup(&rtuple);
-		if (*state)
+		if (rstate)
```
Comment (julianwiedmann) [inline bpf/lib/nat.h]: (commenting here as the diff is cleaner)

to clarify - when the RevSNAT entry is missing, we
1. delete the SNAT entry
2. let `snat_v6_new_mapping()` create a new SNAT / RevSNAT pair of entries.

In a busy node, won't `snat_v6_new_mapping()` then end up selecting a different source port for this connection? Won't this result in disrupted connectivity?

I would have expected that we preserve the SNAT entry, and merely re-create the RevSNAT entry from the available information. Why is that not possible?

File: bpf/tests/tc_nodeport_lb4_nat_lb.c [hunk 8]
```diff
@@ -914,3 +914,212 @@ int nodeport_nat_fwd_reply_no_fib_check(__maybe_unused const struct __ctx_buff *
...
+ *
+ *
+ * Test that the LB fails to RevDNAT and RevSNAT a reply from the
+ * NAT remote backend when its Rev NAT entry gets deleted
+ */
+PKTGEN("tc", "tc_nodeport_nat_fwd_reply_punt")
+int nodeport_nat_fwd_reply_punt_pktgen(struct __ctx_buff *ctx)
+{
+	return build_reply(ctx);
+}
```
Comment (julianwiedmann) [inline bpf/tests/tc_nodeport_lb4_nat_lb.c:950]: Thank you, the test looks good!

File: bpf/lib/nat.h (hunk 7 above)
Comment (sugangli) [reply bpf/lib/nat.h]: Good point. Updated!

File: bpf/lib/nat.h [hunk 9]
```diff
@@ -313,8 +313,24 @@ snat_v4_nat_handle_mapping(struct __ctx_buff *ctx,
...
+			struct ipv4_nat_entry *lookup_result;
+
+			lookup_result = __snat_lookup(map, &rtuple);
+			if (!lookup_result) {
+				memset(&rstate, 0, sizeof(rstate));
+				rstate.to_daddr = tuple->saddr;
+				rstate.to_dport = tuple->sport;
+				rstate.common.needs_ct = needs_ct;
+				rstate.common.created = bpf_mono_now();
+				return __snat_create(map, &rtuple, &rstate);
```
Comment (julianwiedmann) [inline bpf/lib/nat.h]: Please align this with how we handle errors from `__snat_create()` in other places (setting `ext_err`, and returning a proper DROP reason)

File: bpf/lib/nat.h [hunk 10]
```diff
@@ -327,8 +343,6 @@ snat_v4_nat_handle_mapping(struct __ctx_buff *ctx,
 		if (IS_ERR(ret))
 			return ret;
 
-		set_v4_rtuple(tuple, *state, &rtuple);
-		*state = __snat_lookup(map, &rtuple);
```
Comment (julianwiedmann) [inline bpf/lib/nat.h:331]: Can you explain why this lookup is no longer needed :pray: ? It's not obvious to me.

**Review by julianwiedmann — CHANGES_REQUESTED** [review]

File: bpf/lib/nat.h (hunk 9 above)
Comment (sugangli) [reply bpf/lib/nat.h]: Done.

File: bpf/lib/nat.h (hunk 10 above)
Comment (sugangli) [reply bpf/lib/nat.h:331]: I was just reading the comment below that it was OK to fail a deletion? If that's the case, maybe we can always try to delete RevSNAT if the SNAT exists.  But I am not sure about the penalty of deletion failure. Adding it back.

File: bpf/tests/tc_nodeport_lb4_nat_lb.c (hunk 6 above)
Comment (sugangli) [reply bpf/tests/tc_nodeport_lb4_nat_lb.c]: Done.

**Comment by tommyp1ckles** [comment]
Thanks, these changes all look good to me.

@julianwiedmann do you mind taking another look as well?

**Review by julianwiedmann — APPROVED** [review]
lgtm, thank you! I still feel this is a bit hack-ish, and hope we can find a solution to this issue that covers the whole problem space.
