### PR TITLE
datapath: Create sysctl `rp_filter` overwrite config on agent init

### LINKED ISSUE #10645: systemd 245 breaks cilium pod to out-of-node traffic
## Bug report

**General Information**
Updating systemd 244.2-2 on Arch to systemd 245.2-1 and 245-3 break pod to out-of-node ipv4 traffic. Reverting to 244.2-2 and rebooting fixes the problem. (ipv6 keeps working on all versions)

I did a sysctl -a diff with 244 vs 245 with cilium running (ready):
```
< net.ipv4.conf.all.promote_secondaries = 1
> net.ipv4.conf.all.promote_secondaries = 0
< net.ipv4.conf.cilium_host.accept_source_route = 1
> net.ipv4.conf.cilium_host.accept_source_route = 0
< net.ipv4.conf.cilium_host.promote_secondaries = 0
> net.ipv4.conf.cilium_host.promote_secondaries = 1
< net.ipv4.conf.cilium_host.rp_filter = 0
> net.ipv4.conf.cilium_host.rp_filter = 2
< net.ipv4.conf.cilium_net.accept_source_route = 1
> net.ipv4.conf.cilium_net.accept_source_route = 0
< net.ipv4.conf.cilium_net.promote_secondaries = 0
> net.ipv4.conf.cilium_net.promote_secondaries = 1
< net.ipv4.conf.default.accept_source_route = 1
> net.ipv4.conf.default.accept_source_route = 0
< net.ipv4.conf.default.promote_secondaries = 0
> net.ipv4.conf.default.promote_secondaries = 1
< net.ipv4.conf.default.rp_filter = 0
> net.ipv4.conf.default.rp_filter = 2
< net.ipv4.conf.ens192.accept_source_route = 1
> net.ipv4.conf.ens192.accept_source_route = 0
< net.ipv4.conf.ens192.promote_secondaries = 0
> net.ipv4.conf.ens192.promote_secondaries = 1
< net.ipv4.conf.ens192.rp_filter = 0
> net.ipv4.conf.ens192.rp_filter = 2
< net.ipv4.conf.lo.accept_source_route = 1
> net.ipv4.conf.lo.accept_source_route = 0
< net.ipv4.conf.lo.promote_secondaries = 0
> net.ipv4.conf.lo.promote_secondaries = 1
< net.ipv4.conf.lo.rp_filter = 0
> net.ipv4.conf.lo.rp_filter = 2
```

- Cilium version (run `cilium version`)
1.7.1
- Kernel version (run `uname -a`)
Linux k8s22 5.5.10-arch1-1 #1 SMP PREEMPT Wed, 18 Mar 2020 08:40:35 +0000 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
Kubernetes 1.17.4
- Upload a system dump (run `curl -sLO
https://github.com/cilium/cilium-sysdump/releases/latest/download/cilium-sysdump.zip &&
python cilium-sysdump.zip` and then attach the generated zip file)

[cilium-sysdump-20200319-221054.zip](https://github.com/cilium/cilium/files/4356947/cilium-sysdump-20200319-221054.zip)

### LINKED ISSUE #14658: Cilium without kube-proxy and systemd 247 is broken on Debian Bullseye
## Bug report

Installing cilium on a fresh kubernetes installation without kube-proxy on debian bullseye with systemd 247 doesn't work: coredns won't come up because the API server is not reachable. It keeps saying "still waiting on kubernetes". Everything comes up except coredns.

It's related to kube-proxy: it works with kube-proxy enabled.

**General Information**

- Linux: debian 10 with bullseye repos enabled
- Cilium version (run `cilium version`): 1.9.1
- Kernel version (run `uname -a`): 5.10.0-1-amd64
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...): kubectl: 1.20.2
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip: 
[cilium-sysdump-20210119-220818.zip](https://github.com/cilium/cilium/files/5838610/cilium-sysdump-20210119-220818.zip)

**How to reproduce the issue**

1. obtain a VM with debian bullseye
2. update the whole system (`apt-get update` and `apt-get dist-upgrade`)
2. install kubeadm
3. follow the [cilium guide](https://docs.cilium.io/en/v1.9/gettingstarted/kubeproxy-free/#kubeproxy-free)
4. untaint master `kubectl taint nodes "${master_node}" node-role.kubernetes.io/master:NoSchedule-`

**More Details**

We updated our system, with that systemd from 246 to 247. We were able to update the whole system with systemd on hold on 246 and it worked. Updating then systemd alone breaks it.

"Breaks it": a service requested the API server, uses the IP directly of the server and runs into a timeout repeatedly. I suspect that's also what coredns is meaning when it says "still waiting for kubernetes".

The logs in the cilium operator or in the agent don't say anything suspicious.

[10645](https://github.com/cilium/cilium/issues/10645) is not helping. `rp_filter` is 0 everywhere (i.e. when doing `sysctl -a | grep \\.rp_filter`) and the mentioned option `--enable-endpoint-routes` is not helping either. Plus, we ran with systemd 246 before without issues.

### LINKED ISSUE #19761: Connectivity to kubernetes service endpoints broken after k8s version upgrade
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In an environment with 3 control-plane (master) nodes and 3 worker nodes, the communication from pods running on the master nodes to the kubernetes service endpoints is broken after upgrading k8s version from 1.23.5 to 1.23.6 (or from 1.22.2 to 1.22.3). The connectivity still works from the worker (non-master) nodes. The issue can be recovered by restarting the cilium pods running on the master nodes. 

Nodes setup:
```
$ kubectl get nodes -o wide
NAME                                           STATUS   ROLES                  AGE   VERSION   INTERNAL-IP      EXTERNAL-IP      OS-IMAGE             KERNEL-VERSION    CONTAINER-RUNTIME
ip-172-31-141-179.eu-west-3.compute.internal   Ready    control-plane,master   91m   v1.23.6   172.31.141.179   <redacted>       Ubuntu 20.04.4 LTS   5.13.0-1022-aws   containerd://1.4.13
ip-172-31-141-32.eu-west-3.compute.internal    Ready    <none>                 84m   v1.23.5   172.31.141.32    <redacted>       Ubuntu 20.04.4 LTS   5.13.0-1022-aws   containerd://1.4.13
ip-172-31-142-157.eu-west-3.compute.internal   Ready    control-plane,master   90m   v1.23.6   172.31.142.157   <redacted>       Ubuntu 20.04.4 LTS   5.13.0-1022-aws   containerd://1.4.13
ip-172-31-142-232.eu-west-3.compute.internal   Ready    <none>                 84m   v1.23.5   172.31.142.232   <redacted>       Ubuntu 20.04.4 LTS   5.13.0-1022-aws   containerd://1.4.13
ip-172-31-143-187.eu-west-3.compute.internal   Ready    control-plane,master   89m   v1.23.6   172.31.143.187   <redacted>       Ubuntu 20.04.4 LTS   5.13.0-1022-aws   containerd://1.4.13
ip-172-31-143-91.eu-west-3.compute.internal    Ready    <none>                 84m   v1.23.5   172.31.143.91    <redacted>       Ubuntu 20.04.4 LTS   5.13.0-1022-aws   containerd://1.4.13
```

kubernetes service endpoints:
```
$ kubectl get endpoints kubernetes                                                                                                                                                                                  
NAME         ENDPOINTS                                                     AGE
kubernetes   172.31.141.179:6443,172.31.142.157:6443,172.31.143.187:6443   101m
```

apiservers are running in the host namespace of the master nodes:
```
NAMESPACE     NAME                                                                   READY   STATUS             RESTARTS         AGE
kube-system   kube-apiserver-ip-172-31-141-179.eu-west-3.compute.internal            1/1     Running            0                93m    172.31.141.179   ip-172-31-141-179.eu-west-3.compute.internal   <none>           <none>
kube-system   kube-apiserver-ip-172-31-142-157.eu-west-3.compute.internal            1/1     Running            0                88m    172.31.142.157   ip-172-31-142-157.eu-west-3.compute.internal   <none>           <none>
kube-system   kube-apiserver-ip-172-31-143-187.eu-west-3.compute.internal            1/1     Running            0                72m    172.31.143.187   ip-172-31-143-187.eu-west-3.compute.internal   <none>           <none>
``` 

Pods running on the master nodes cannot connect to the kubernetes service after kubernetes version upgrade.
```
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   109m
```

```
curl --connect-timeout 5 --insecure https://10.96.0.1:443
curl: (28) Connection timeout after 5001 ms
```

Connecting directly to the endpoint IPs does not work either (none of them):
```
curl --connect-timeout 5 --insecure https://172.31.141.179:6443
curl: (28) Connection timeout after 5001 ms
```

Connectivity to other pods and services works fine from the same pod.

Pods running on worker nodes can connect to the kubernetes service (and its endpoints) successfully:
```
curl --connect-timeout 5 --insecure https://10.96.0.1:443
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}#

curl --connect-timeout 5 --insecure https://172.31.141.179:6443
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}#
```

After restart of the cilium pod on the affected master node, the issue recovers and broken pods can communicate with the kubernetes service successfully.

### Cilium Version

v1.11.1

### Kernel Version

Linux ip-172-31-141-179 5.13.0-1022-aws #24~20.04.1-Ubuntu SMP Thu Apr 7 22:10:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.23.6

### Sysdump

[cilium-sysdump-20220510-154929.zip](https://github.com/cilium/cilium/files/8662162/cilium-sysdump-20220510-154929.zip)

### Relevant log output

_No response_

### Anything else?

`cilium monitor --type drop` does not show anything on affected node.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #19909: CFP: make cilium-agent freak out if rp_filter config is wrong
## Cilium Feature Proposal

When upgrading our Kubernetes workers from Ubuntu 20.04 -> 22.04 we encountered the issue described in #10645, since Ubuntu 22.04 ships with systemd 249.

The workaround is described in the [System Requirements](https://docs.cilium.io/en/stable/operations/system_requirements/#linux-distribution-compatibility-matrix) page, but I only managed to find it there because I was looking for it (I ran into this issue a few weeks ago trying to run Cilium on my local Arch workstation).

Given that the failure mode is really weird (host networking pods work fine, networked pods work fine when talking to same node), perhaps it would be worth checking the sysctl setting during cilium-agent startup, and fail to boot if it's not correctly set?

With Ubuntu 22.04.1 (the "real" LTS release, as everybody knows) around the corner, I suspect that many Cilium users are going to encounter this issue in the short term. Adding a check could save them (and folks responsible for Cilium issue triage!) a lot of time :)

### PR DESCRIPTION
**Pull request by dylandreimerink**
SystemD versions greater than 245 will create sysctl config which sets
the `rp_filter` value for all network interfaces to 1. This conflicts
with cilium which requires `rp_filter` to be 0 on interfaces it uses.

This commit adds a small utility/tool: `sysctlfix` which will insert
a config file into the `/etc/sysctl.d` dir with the highest priority
containing directives to disable `rp_filter` and perhaps to contain
other sysctl config in future.

This utility is called as an init container before the cilium agent
starts. Because the sysctl config is in place before the agent starts,
all interfaces created by the agent and matching the patten in the
config file will have `rp_filter` disabled, even when SystemD >=245 is
installed.

Fixes: #10645
Fixes: #19909

```release-note
Fixed SystemD >=245 sysctl(`rp_filter`) config incompatibility
```

### CODE REVIEW

File: tools/sysctlfix/main.go [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+	"os"
+	"path"
+	"strings"
+)
+
+// This tool attempts to write a sysctl config file to the sysctl config directory with the highest precedence so
+// we can overwrite any other config and ensure correct sysctl options for Cilium to function.
+
+const (
+	sysctlD = "/etc/sysctl.d/"
```
Comment (aanm) [inline tools/sysctlfix/main.go]: Is this directory always the same? Should we make it user-configurable by passing it as a flag?

**Review by aanm — APPROVED** [review]

File: tools/sysctlfix/main.go (hunk 1 above)
Comment (dylandreimerink) [reply tools/sysctlfix/main.go]: There are multiple paths defined which overwrite each other in a set order. So as far as I can tell these directories are always the same and the `/etc/sysctl.d` overwrites all others.

From https://man7.org/linux/man-pages/man5/sysctl.d.5.html
```
       Configuration files are read from directories in /etc/, /run/,
       /usr/local/lib/, and /usr/lib/, in order of precedence, as listed
       in the SYNOPSIS section above. Files must have the ".conf"
       extension. Files in /etc/ override files with the same name in
       /run/, /usr/local/lib/, and /usr/lib/. Files in /run/ override
       files with the same name under /usr/.

       All configuration files are sorted by their filename in
       lexicographic order, regardless of which of the directories they
       reside in. If multiple files specify the same option, the entry
       in the file with the lexicographically latest name will take
       precedence. Thus, the configuration in a certain file may either
       be replaced completely (by placing a file with the same name in a
       directory with higher priority), or individual settings might be
       changed (by specifying additional settings in a file with a
       different name that is ordered later).
```

**Review by sayboras — APPROVED** [review]
LGTM :100:

**Comment by sayboras** [comment]
Below is from my local minikube, do we need to do something with `net.ipv4.conf.all.rp_filter=1` ? 

```
docker@minikube:/etc/sysctl.d$ grep -Ris "rp_filter" * 
10-network-security.conf:net.ipv4.conf.default.rp_filter=1
10-network-security.conf:net.ipv4.conf.all.rp_filter=1
99-sysctl.conf:#net.ipv4.conf.default.rp_filter=1
99-sysctl.conf:#net.ipv4.conf.all.rp_filter=1
99-zzz-override_cilium.conf:# Disable rp_filter on Cilium interfaces since it may cause mangled packets to be dropped
99-zzz-override_cilium.conf:net.ipv4.conf.lxc*.rp_filter = 0
99-zzz-override_cilium.conf:net.ipv4.conf.cilium_*.rp_filter = 0
```

**Comment by rastislavs** [comment]
> Below is from my local minikube, do we need to do something with `net.ipv4.conf.all|default.rp_filter=1` ?

yeah, in our case from https://github.com/cilium/cilium/issues/19761, the proposed change is not enough to resolve the issue  and `net.ipv4.conf.all.rp_filter` would solve it.

**Comment by dylandreimerink** [comment]
@sayboras @rastislavs is the goal of adding `net.ipv4.conf.all|default.rp_filter=1|0` to change this setting for all interfaces? Asking because I am looking into it atm.  Setting it seems to only actually change `net.ipv4.conf.all.rp_filter` for me
```
$ sysctl -a | grep rp_filter
net.ipv4.conf.all.arp_filter = 0
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.cilium_host.arp_filter = 0
net.ipv4.conf.cilium_host.rp_filter = 2
net.ipv4.conf.cilium_net.arp_filter = 0
net.ipv4.conf.cilium_net.rp_filter = 2
net.ipv4.conf.cilium_vxlan.arp_filter = 0
net.ipv4.conf.cilium_vxlan.rp_filter = 2
net.ipv4.conf.default.arp_filter = 0
net.ipv4.conf.default.rp_filter = 2
net.ipv4.conf.docker0.arp_filter = 0
net.ipv4.conf.docker0.rp_filter = 2
net.ipv4.conf.enp0s3.arp_filter = 0
net.ipv4.conf.enp0s3.rp_filter = 2
net.ipv4.conf.enp0s8.arp_filter = 0
net.ipv4.conf.enp0s8.rp_filter = 2
net.ipv4.conf.lo.arp_filter = 0
net.ipv4.conf.lo.rp_filter = 2
net.ipv4.conf.lxc_health.arp_filter = 0
net.ipv4.conf.lxc_health.rp_filter = 2
net.ipv4.conf.veth5086343.arp_filter = 0
net.ipv4.conf.veth5086343.rp_filter = 2
net.ipv4.conf.veth8e6cce6.arp_filter = 0
net.ipv4.conf.veth8e6cce6.rp_filter = 2
net.ipv4.conf.vetha39077f.arp_filter = 0
net.ipv4.conf.vetha39077f.rp_filter = 2
``` 

I have to add `net.ipv4.conf.*.rp_filter` to get it to change all interfaces.
```
$ sudo systemctl restart systemd-sysctl.service`
$ sysctl -a | grep rp_filter
net.ipv4.conf.all.arp_filter = 0
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.cilium_host.arp_filter = 0
net.ipv4.conf.cilium_host.rp_filter = 0
net.ipv4.conf.cilium_net.arp_filter = 0
net.ipv4.conf.cilium_net.rp_filter = 0
net.ipv4.conf.cilium_vxlan.arp_filter = 0
net.ipv4.conf.cilium_vxlan.rp_filter = 0
net.ipv4.conf.default.arp_filter = 0
net.ipv4.conf.default.rp_filter = 2
net.ipv4.conf.docker0.arp_filter = 0
net.ipv4.conf.docker0.rp_filter = 0
net.ipv4.conf.enp0s3.arp_filter = 0
net.ipv4.conf.enp0s3.rp_filter = 0
net.ipv4.conf.enp0s8.arp_filter = 0
net.ipv4.conf.enp0s8.rp_filter = 0
net.ipv4.conf.lo.arp_filter = 0
net.ipv4.conf.lo.rp_filter = 0
net.ipv4.conf.lxc_health.arp_filter = 0
net.ipv4.conf.lxc_health.rp_filter = 0
net.ipv4.conf.veth5086343.arp_filter = 0
net.ipv4.conf.veth5086343.rp_filter = 0
net.ipv4.conf.veth8e6cce6.arp_filter = 0
net.ipv4.conf.veth8e6cce6.rp_filter = 0
net.ipv4.conf.vetha39077f.arp_filter = 0
net.ipv4.conf.vetha39077f.rp_filter = 0
```

**Comment by dylandreimerink** [comment]
@ungureanuvladvictor that is something to look into. I just occurred to me that this might also affect Cilium in 'standalone LB' mode (@brb, @borkmann ?), setting this up via an init container might not be the way to go. Perhaps we should move this into the agent/daemon itself.

**Comment by joestringer** [comment]
CNI plugin is an interesting option, the awkward thing there is that the CNI binary is run semi-frequently and each time is an independent execution of the binary. So it'd just need to be idempotent. The nice thing about running in CNI plugin context is that it's running as an application directly on the host with privileges, so we shouldn't need to worry about the security context at all.

Thinking about the option to move it into the agent, this becomes more tricky because then we're further expanding the set of things that the cilium-agent container can access at runtime, and we're trying to avoid granting blanket access to lots of the system at all times from the cilium-agent. Cilium needs to be pretty powerful already, but do we really need access to reconfigure random `/etc/sysctl.d` settings in addition to all the other stuff? At least if it's an init container, this access is relatively short-lived.

**Review by aditighag — APPROVED** [review]
🚀

File: tools/sysctlfix/main.go [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+	// The 99-zzz prefix ensures our config file gets precedence over most if not all other files.
+	ciliumOverwrites = "99-zzz-override_cilium.conf"
+)
+
+var sysctlConfig = strings.Join([]string{
+	"# Disable rp_filter on Cilium interfaces since it may cause mangled packets to be dropped",
+	"net.ipv4.conf.lxc*.rp_filter = 0",
```
Comment (aditighag) [inline tools/sysctlfix/main.go]: I overlooked that we are completely disabling the filter. What about setting it to the `Loose` mode? That's all we should need to pass the packets with asymmetric routing. Details - https://github.com/cilium/cilium/issues/13130. That's the value we are currently setting as well.

**Review by aditighag — CHANGES_REQUESTED** [review]

**Comment by dylandreimerink** [comment]
> Thinking about the option to move it into the agent, this becomes more tricky because then we're further expanding the set of things that the cilium-agent container can access at runtime

That is a good point, hadn't considered that. Running the tool should be a one time thing, so we can make it part of the installation process/guide for the standalone LB if it ever becomes an issue.

>  So it'd just need to be idempotent.

Updating the config file frequently doesn't do any harm. But we should only trigger a reload of the systemd unit when it has actually changed, will take this into account when updating the tool, so we can move this logic to the CNI plugin if we wish.

File: tools/sysctlfix/main.go (hunk 2 above)
Comment (dylandreimerink) [reply tools/sysctlfix/main.go]: I set it to disabled since that seemed to be the suggested fix in #10645. According too @aanm, [this](https://github.com/systemd/systemd/commit/230450d4e4f1f5fc9fa4295ed9185eea5b6ea16e) commit in SystemD is the source of the issue. In the commit the `rp_filter` is changed from 1(Strict) to 2(Loose). In #10645 [this](https://github.com/systemd/systemd/commit/5d4fc0e665a3639f92ac880896c56f9533441307#diff-7816eed8ca6324f23a690cc5f58e6bf7) commit is mentioned as the culprit (also a change to 2(Loose))

The description of 'Loose' mode is:
> Loose mode as defined in RFC3704 Loose Reverse Path
        Each incoming packet's source address is also tested against the FIB
        and if the source address is not reachable via any interface
        the packet check will fail.
        
I am not sure if there are common use cases in Cilium where we handle packets for source addresses which don't appear in the FIB, but it wouldn't surprise me if there are.

File: tools/sysctlfix/main.go (hunk 1 above)
Comment (dylandreimerink) [reply tools/sysctlfix/main.go]: I made flags for all of the constants anyway, none of them are required, so we use default values if no flags are passed. It doesn't hurt and might be useful to have it in the binary in case we ever need it in a production environment for some reason.

**Comment by brb** [comment]
> just occurred to me that this might also affect Cilium in 'standalone LB' mode (@brb, @borkmann ?), setting this up via an init container might not be the way to go.

The answer depends on what iface's rp_filter we are concerned about. If it's Cilium's lxc, then this is not a problem for the stadalone L4LB (`--datapath-mode=lb-only`), as in this mode Cilium is not acting as CNI, so it doesn't create / attach to lxc's. Another thing is that in the stadalone L4LB mode it's very likely that a user might deploy Cilium as a standalone binary, i.e., without running in a k8s pod.

File: tools/sysctlfix/main.go [hunk 3]
```diff
@@ -0,0 +1,142 @@
...
+	sysctlUnit = flagSet.String(
+		"systemd-sysctl-unit",
+		"systemd-sysctl.service",
+		"Name of the systemd sysctl unit to reload",
+	)
+)
+
+var sysctlConfig = strings.Join([]string{
+	"# Disable rp_filter on Cilium interfaces since it may cause mangled packets to be dropped",
+	"net.ipv4.conf.all.rp_filter = 0",
```
Comment (brb) [inline tools/sysctlfix/main.go]: Aren't we changing the rp_filter setting of other non-Cilium ifaces? If yes, then this might be undesirable behavior by users who are concerned about the packet spoofing.

Comment (dylandreimerink) [reply tools/sysctlfix/main.go]: Yes, it does. According to @rastislavs this is required to fix #19761. Perhaps we can find a middle ground between disabling on all interfaces and just the Cilium interfaces? 

If `rp_filter` on host interfaces really does create connectivity problems, perhaps we should disable it and fast-track spoofing detection in Cilium, so we can guarantee it is compatible?

**Comment by dylandreimerink** [comment]
> Anyway, for now I wouldn't be too concerned about the standalone L4LB mode

Alright, in that case I think it makes most sense to move the logic to the CNI plugin instead of using a privileged container at startup.

File: tools/sysctlfix/main.go (hunk 3 above)
Comment (brb) [reply tools/sysctlfix/main.go]: > According to @rastislavs this is required to fix

I think it makes sense to first understand which packet path was broken due to rp_filter=2 in that case.

Comment (dylandreimerink) [reply tools/sysctlfix/main.go]: That seems fair, I will revert this PR to only setting `rp_filter` for Cilium interfaces so we can get this PR merged for the other issues. Then we will do a followup PR once we have more details regarding #19761.

Comment (rastislavs) [reply tools/sysctlfix/main.go]: But isn't Cilium already setting `net.ipv4.conf.all.rp_filter` to `0` upon its startup ([here](https://github.com/cilium/cilium/blob/v1.11.5/pkg/datapath/loader/base.go#L245))? At least this is a log message that I can see in Cilium logs when it starts:
```
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.ipv4.conf.all.rp_filter sysParamValue=0
```
So why should this be any different to that logic?

File: tools/sysctlfix/main.go (hunk 2 above)
Comment (aditighag) [reply tools/sysctlfix/main.go]: Cilium isn't the only entity that could be running on a host. The issues you've linked above indicate that systemd overwrites `rp_filter` settings set by Cilium. Regardless, I would like for us to understand why we would need to disable source address checks altogether in case of Cilium.

File: tools/sysctlfix/main.go (hunk 3 above)
Comment (aditighag) [reply tools/sysctlfix/main.go]: We set the config to the `Loose` mode while installing ENI rules on EKS clusters - http://github.com/cilium/cilium/blob/master/pkg/datapath/loader/base.go#L146-L146. We should ideally have a consistent way of setting the config. I would suggest investigating this further. You may refer to this issue https://github.com/cilium/cilium/issues/13130 to get pointers for debugging.

Comment (dylandreimerink) [reply tools/sysctlfix/main.go]: > But isn't Cilium already setting net.ipv4.conf.all.rp_filter to 0 upon its startup

Yes, but this only changes the runtime option, if systemd is triggered for any reason it can just change the runtime setting to match the config. By setting the desired sysctl parameter in systemd config, we ensure that the value stays even after systemd config reloads

Edit: nevermind, you are hinting at the part where we set the setting for all interfaces, disregard my comment above.

Comment (rastislavs) [reply tools/sysctlfix/main.go]: Please see my latest comment on https://github.com/cilium/cilium/issues/19761#issuecomment-1150751732

**Review by brb — APPROVED** [review]
Reviewed only two lines (`...lxc*.rp_filter = 0` and `...cilium_*.rp_filter = 0`), LGTM!

File: tools/sysctlfix/main.go [hunk 4]
```diff
@@ -0,0 +1,139 @@
...
+	)
+	// Name of the systemd-sysctl unit to restart after making changes
+	sysctlUnit = flagSet.String(
+		"systemd-sysctl-unit",
+		"systemd-sysctl.service",
+		"Name of the systemd sysctl unit to reload",
+	)
+)
+
+var sysctlConfig = strings.Join([]string{
```
Comment (tklauser) [inline tools/sysctlfix/main.go]: Nit: given this is a constant string, I think this could be defined as a const multi-line string to avoid `strings.Join` altogether.

File: tools/sysctlfix/main.go [hunk 5]
```diff
@@ -0,0 +1,139 @@
...
+		return
+	}
+
+	if string(currentContents) == sysctlConfig {
+		fmt.Println("sysctl config up-to-date, nothing to do")
+		return
+	}
+
+	// Move offset into the file to the beginning
+	_, err = f.Seek(0, 0)
```
Comment (tklauser) [inline tools/sysctlfix/main.go]: Let's use a named constant for `whence` which should also make the comment superfluous:

```suggestion
	_, err = f.Seek(0, io.SeekStart)
```

File: tools/sysctlfix/main.go [hunk 6]
```diff
@@ -0,0 +1,139 @@
...
+
+	_, err = fmt.Fprint(f, sysctlConfig)
+	if err != nil {
+		fmt.Printf("error while writing to sysctl config: %s\n", err)
+		return
+	}
+
+	fmt.Println("sysctl config created/updated")
+
+	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Minute)
```
Comment (tklauser) [inline tools/sysctlfix/main.go]: 1 minute seems like a rather long timeout. How was this determined?

**Review by tklauser — COMMENTED** [review]
Some non-blocking nits inline.

File: tools/sysctlfix/main.go (hunk 5 above)
Comment (dylandreimerink) [reply tools/sysctlfix/main.go]: That is neat, didn't know about those constants

File: tools/sysctlfix/main.go (hunk 6 above)
Comment (dylandreimerink) [reply tools/sysctlfix/main.go]: You are probably right. Didn't put much thought into the actual value, 1 minutes does seem like a bit on the long side for a startup program. I will change it to 15 secondes or so. That feels like a more reasonable for timeout SystemD to reload the unit. In my experience this is normally a sub-second thing.

File: tools/sysctlfix/main.go (hunk 4 above)
Comment (dylandreimerink) [reply tools/sysctlfix/main.go]: This style initially made sense to interleave go comments and configuration. But that is not required due to recent changes, and we can put any comments in the file itself anyway like done new. So agreed!

**Review by tklauser — APPROVED** [review]
Thanks

File: install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml [hunk 7]
```diff
@@ -454,6 +455,49 @@ spec:
...
+        - -ec
+        # The statically linked Go program binary is invoked to avoid any
+        # dependency on utilities like sh that can be missing on certain
+        # distros installed on the underlying host. Copy the binary to the
+        # same directory where we install cilium cni plugin so that exec permissions
+        # are available.
+        - |
+          cp /usr/bin/cilium-sysctlfix /hostbin/cilium-sysctlfix;
+          nsenter --mount=/hostproc/1/ns/mnt "${BIN_PATH}/cilium-sysctlfix";
+          rm /hostbin/cilium-sysctlfix
```
Comment (christarazi) [inline install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml:475]: Does there need to be a semi-colon at the end of these lines?

**Review by christarazi — COMMENTED** [review]
Code LGTM at a glance. I didn't do a deep review. 

1. Minor nit comment below
2. Could you update the commits and PR desc. to now reference the CNI approach rather than init container? Could you also add the background around the lb-only flag and only disabling `rp_filter` for `cilium*` and `lxc*` interfaces, rather than `all`, etc?
3. This might be a dumb question, but I don't see how this is getting invoked each time the CNI plugin is invoked. Could you point it out?

File: tools/sysctlfix/main.go [hunk 8]
```diff
@@ -0,0 +1,136 @@
...
+		fmt.Printf("error while writing to sysctl config: %s\n", err)
+		return
+	}
+
+	fmt.Println("sysctl config created/updated")
+
+	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
+	defer cancel()
+
+	conn, err := dbus.NewSystemdConnectionContext(ctx)
```
Comment (aditighag) [inline tools/sysctlfix/main.go:112]: Ah! Nice to see the API being exposed via dbus.

**Review by aditighag — COMMENTED** [review]
Mainly looked at changes in `tools/sysctlfix/main.go`. LGTM!
Do we still need changes related to setting `rp_filter` configs - https://github.com/cilium/cilium/blob/master/bpf/init.sh#L63?

File: install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml (hunk 7 above)
Comment (dylandreimerink) [reply install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml:475]: Not sure to be honest :sweat_smile:, I copied this part from the `cilium-mount` container at line 429, I haven't tried it without to see how it gets interpreted

**Comment by dylandreimerink** [comment]
@christarazi 

> 2. Could you update the commits and PR desc. to now reference the CNI approach rather than init container.

Due to the long back and forth about the scope of the `rp_filter` setting I decided to leave the PR as is to avoid dragging things out even longer.

> 3. This might be a dumb question, but I don't see how this is getting invoked each time the CNI plugin is invoked. Could you point it out?

Not dumb at all, you are not seeing it because it isn't there, still using init containers at the moment.

**Comment by dylandreimerink** [comment]
@aditighag 

> Do we still need changes related to setting rp_filter configs

Yes, this tool only works if SystemD is installed, since we can't guarantee this, we still need to change the runtime settings.

**Review by aditighag — APPROVED** [review]

**Comment by dylandreimerink** [comment]
After a short discussion with @aanm and after having checked out https://github.com/cilium/cilium/issues/19761#issuecomment-1150751732, I must conclude that the `net.ipv4.conf.all.rp_filter` must also be set to 0 since it otherwise overwrites the per-dev config.

As far as I can tell rp_filter enforcement happens [here](https://elixir.bootlin.com/linux/v5.18.3/source/net/ipv4/fib_frontend.c#L425) based on the value of [IN_DEV_RPFILTER](https://elixir.bootlin.com/linux/v5.18.3/source/include/linux/inetdevice.h#L101) which resolves the setting with [IN_DEV_MAXCONF](https://elixir.bootlin.com/linux/v5.18.3/source/include/linux/inetdevice.h#L94). The code for which is:
```
#define IN_DEV_MAXCONF(in_dev, attr) \
	(max(IPV4_DEVCONF_ALL(dev_net(in_dev->dev), attr), \
	     IN_DEV_CONF_GET((in_dev), attr)))
```
So it seems that the `.all.` setting will always overwrite the per-dev setting if not set to `0`. I have updated the PR to add this as well. Side effect is that, if the user is relying on this behavior instead of explicitly setting the `rp_filter` value per device than we disable return path filtering. So perhaps we should recommend users whom want to use `rp_filter` on non-cilium interfaces to explicitly configure the setting per device

File: tools/sysctlfix/main.go [hunk 9]
```diff
@@ -0,0 +1,59 @@
...
+	"strings"
+)
+
+// This tool attempts to write a sysctl config file to the sysctl config directory with the highest precedence so
+// we can overwrite any other config and ensure correct sysctl options for Cilium to function.
+
+const (
+	sysctlD = "/etc/sysctl.d/"
+	// The 99-zzz prefix ensures our config file gets precedence over most if not all other files.
+	ciliumOverwrites = "99-zzz-override_cilium.conf"
```
Comment (ldelossa) [inline tools/sysctlfix/main.go]: Do we have a strategy to detect if another "99-zzz" file is located on the system? It's most likely not necessary but at least dropping a log in the init container would be valuable for customers debugging.

**Review by ldelossa — APPROVED** [review]
LGTM

**Review by sayboras — APPROVED** [review]
LGTM :100:

File: tools/sysctlfix/main.go (hunk 3 above)
Comment (sayboras) [reply tools/sysctlfix/main.go]: https://github.com/cilium/cilium/pull/20072#issuecomment-1156495539

**Comment by dylandreimerink** [comment]
The `k8s-1.16-kernel-4.9 (test-1.16-4.9)` and `k8s-1.23-kernel-net-next (test-1.23-net-next)` failures seem to be a flake effecting multiple PRs at the moment: #20217 

As for the `gke-stable` test, it seems to fail when installing cilium. It looks very similar to other failed test runs, so I think this is a flake and not something specific to this PR.
