### PR TITLE
pkg/health: Fix IPv6 URL format in HTTP probe

### LINKED ISSUE #7804: cilium-health reports failure to reach agent in ipv6-only mode
Cilium master in v1.6 cycle.

Steps:
1. Enable IPv6 and disable IPv4
1. Run Cilium
1. Observe that `cilium-health` complains about connectivity to the agent via IPv6.
1. Observe that the server is in fact responding to IPv6 requests.

```
$ kubectl -n kube-system get configmap cilium-config -o yaml | grep ipv
  enable-ipv4: "false"
  enable-ipv6: "true"
$ kubectl exec -n kube-system $(get_cilium_pod) -- cilium-health status
Probe time:   2019-04-22T05:12:49Z
Nodes:
  allosaurus (localhost):
    Host connectivity to fc00::10ca:1:
      ICMP to stack:   OK, RTT=483.482µs
      HTTP to agent:   Connection timed out
    Endpoint connectivity to f00d::a84:0:0:24d3:
      ICMP to stack:   OK, RTT=386.242µs
      HTTP to agent:   Connection timed out
$ kubectl -n kube-system exec $(get_cilium_pod) -- cilium-health ping
OK
```

Seems like the server is reachable and the API is responding to the ping, but `cilium-health status` reports it as failing?

Reported by Roelf Wichertjes on Slack.

### PR DESCRIPTION
**Pull request by iffyio**
The current URL address formatting for HTTP probes does not support
IPv6 literal addresses very well. Since an IPv6 address itself
contains ':' it should be enclosed within '[' and ']' to be able to
properly parse the port from the address.

E.g for an endpoint `f00d::a10:0:0:a26e`, we will make an HTTP request:
`http://f00d::a10:0:0:a26e:4240/v1beta/hello` which throws an error:
`Get http://f00d::a10:0:0:a26e:4240/v1beta/hello: invalid URL port ":a10:0:0:a26e:4240"`.

Instead, the request could be something like:
`http://[f00d::a10:0:0:a26e]:4240/v1beta/hello`

* Enclose health endpoint addresses within brackets during HTTP probe.
  This doesn't affect the behavior for IPv4 literal addresses.
* In case of an error, set the probe result `status` to the error
  message instead of the generic 'Connection timed out' message.
  If there aren't already reasons for having the generic message, then
  it might help the user debug probe issues.

Fixes #7804

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7869)

### CODE REVIEW

**Review by joestringer — APPROVED** [review]
Thanks for the fix!

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Can't tell what the Travis failure is due to #7867 , likely a flake so I'll try to kick it.

**Comment by iffyio** [comment]
Hmmn, could the `context deadline exceeded` be due to a timeout if `cilium/health.sock` isn't available?

**Comment by joestringer** [comment]
@iffyio taking the error message from the CI:

```
Cilium is not ready yet: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-24crp': Exitcode: 255 
Stdout:
 	 
Stderr:
 	 Error: Cannot get status/probe: Put http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe: context deadline exceeded
```

I tried grepping around the codebase for some of these error strings and found this:

https://github.com/cilium/cilium/blob/9e81aff817bf7a29c7a4782ddbdedc33bc3bace2/test/helpers/kubectl.go#L1973-L1978

I think this is suggesting that the `cilium-health status -o json --probe` command itself is actually failing for some reason, for instance because it can't reach all of the remote IPs?

I would suggest either attempting to dig through the sysdump attached to the ci build here:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11932/testReport/junit/Suite-k8s-1/14/K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master/

..or attempting to reproduce locally via the instructions here (Perhaps even just spin up the k8s VMs and play around in the environment to ascertain what the agents are doing?):
http://docs.cilium.io/en/latest/contributing/#running-end-to-end-tests

I note also that the CI is only failing for the multi-node k8s tests, and not for the single-node runtime tests. Perhaps there is some other difference in those environments. Does IPv6 routing between the test VMs work, for instance? Perhaps the test environment never provided proper IPv6 connectivity on the underlay and we're only noticing in this PR because of the error representation change. You might consider splitting this PR into two PRs, one to fix the IPv6 addressing bug and one to fix up the error, this may also reveal some information.

**Comment by iffyio** [comment]
ah, I'll set up the e2e tests locally and look around. Thanks for the heads up!

File: pkg/health/server/prober.go [hunk 1]
```diff
@@ -229,7 +229,7 @@ func (p *prober) setNodes(nodes nodeMap) {
 func (p *prober) httpProbe(node string, ip string, port int) *models.ConnectivityStatus {
 	result := &models.ConnectivityStatus{}
 
-	host := fmt.Sprintf("http://%s:%d", ip, port)
+	host := fmt.Sprintf("http://[%s]:%d", ip, port)
```
Comment (aanm) [inline pkg/health/server/prober.go]: please replace with `host := "http://" + net.JoinHostPort(ip, strconv.Itoa(port))`

**Review by aanm — CHANGES_REQUESTED** [review]

File: pkg/health/server/prober.go (hunk 1 above)
Comment (iffyio) [reply pkg/health/server/prober.go]: Will do!

**Comment by iffyio** [comment]
@joestringer It looks like while nodes are reachable via IPv6 primary-addresses (on `fd04::` network), it's not the case for the IPv6 health endpoint addresses (on `f00d::`).
I figured updating the Vagrantfile to add each machine to a `f00d::a0a:0:0:0/80` private network should provide connectivity for all node subnetworks since the tests always use `10.10.0.0/16`.
The result was that both primary and health endpoint addresses got picked from the `f00d::a0a:0:0:0/80` (the former wasn't necessarily intentional) but what I found strange was that IPv6 connectivity now only partially works in one direction (k8s1=>k8s2) and it only works for the health endpoint addresses and not the primary addresses even though they should technically belong to the same network. The routing tables looked sane enough to allow connectivity both ways afaict.

I suspected this wasn't a viable approach to begin with though :) I guess my question would be what approach could be taken to fixing the actual issue of IPv6 routing? I can't yet tell if it's just a setup issue or if cilium itself is involved.

**Comment by joestringer** [comment]
> @joestringer It looks like while nodes are reachable via IPv6 primary-addresses (on fd04:: network), it's not the case for the IPv6 health endpoint addresses (on f00d::).

@iffyio Hmm. In the IPv4 equivalent, that would be expected. We don't route the endpoint IPv4 addresses on the "underlay" (between the VMs), we just route the node IPs and for all other (eg endpoint) traffic use the tunnels between the nodes. For a cilium-health server instance on a node to connect to a health endpoint on another node, there is a route on the local node for the remote node's endpoint prefix which points to the tunnel so the traffic will be encapsulated and sent through via the underlay addresses.

In the IPv6 case, I haven't actually paid close attention. We do the same `TUNNEL_MAP` lookup in BPF to fetch the remote node address for a given remote IP, but it's unclear to me whether the traffic is then encapsulated in an IPv4 tunnel like the IPv4 traffic is, or an IPv6-based tunnel, or just directly routed.

> I figured updating the Vagrantfile to add each machine to a f00d::a0a:0:0:0/80 private network should provide connectivity for all node subnetworks since the tests always use 10.10.0.0/16.
The result was that both primary and health endpoint addresses got picked from the f00d::a0a:0:0:0/80 (the former wasn't necessarily intentional) but what I found strange was that IPv6 connectivity now only partially works in one direction (k8s1=>k8s2) and it only works for the health endpoint addresses and not the primary addresses even though they should technically belong to the same network. The routing tables looked sane enough to allow connectivity both ways afaict.

Having these in the same network may end up confusing things a bit particularly if we're running in tunnel mode, because these networks are typically distinct and not directly connected. Might be worth comparing with the IPv4 examples, and trying `ip route`, `cilium monitor` as well as `tcpdump` (on the interface in each VM facing the network) then executing both IPv4 and IPv6 pings for each address space, then try to understand how the traffic flows for each path in IPv4, and what's happening with IPv6 as well.

**Comment by iffyio** [comment]
@joestringer I can see ipv4/6 health traffic coming into a node via `cilium_health` but also the `cilium_vxlan` interface. It's not yet clear to me how both interfaces tie together but `cilium_vxlan` seems to drop ipv6 packets (e.g no echo replies for ping requests). Could this be an issue? Comparing the paths ipv4 and ipv6 traffic take, both seem to be setup similarly AFAICT but this is one difference I've found so far.

**Comment by joestringer** [comment]
@iffyio That's interesting.. 

(I really ought to write this first bit up as a proper documentation update..)

The cilium-health daemon runs effectively directly on a node. In the runtime CI, it really is on the node, spawned as a subprocess from the Cilium daemon. In the k8s case, all of Cilium is in a host-networking pod with privileges, and in that case again it spawns the cilium-health daemon. So from that perspective, it is a local process. This is the agent that is responsible for pinging other agents, both the daemon running directly on each other node in the cluster, as well as the passive `cilium-health` agent that is run in a network namespace and joined to Cilium like a pod. 

Per this diagram:
http://docs.cilium.io/en/latest/_static/cilium_bpf_egress.svg

I would expect that on the source node, the `cilium-health` daemon is operating as a local process, in the same spot that the "Userspace Proxy" occupies. It sends traffic towards the iptables OUTPUT chain, through the routing table, then POSTROUTING, then to the `cilium_host` device where TC is run (the box directly underneath `POSTROUTING`). From there, the BPF program determines that the destination is on another node, so it sends it towards NIC (Access to world) which would be the `cilium_vxlan` device. From there, the overlay mode is enabled so it will go through the purple box, become encapsulated, and go through the host device that provides access from the VM down to the hypervisor (probably something like `eth0`, `en0` or `enp0s0` though the numbers may be different).

Conversely, at the destination on ingress (again, following roughly left-to-right path): 
http://docs.cilium.io/en/latest/_static/cilium_bpf_ingress.svg

The initial request should come from the NIC/device that faces the hypervisor, go through the purple box for decapsulation then the "NIC (Access to World)" (again, representing `cilium_vxlan`), which triggers the TC/BPF logic to deliver to the `cilium_health` (in this diagram, "Endpoint" green box), then the health endpoint will receive the traffic.

To follow the response, we can go back to the egress prog diagram above and this time it will just follow the left-to-right path across the bottom, from `Endpoint (lxc)` through `TC @ Endpoint` , `TC @ cilium_host`, `NIC (Access to world)`, encapsulation/routing, and out of the remote node. The ingress path to get back to the original daemon on the original source node isn't really described in the ingress diagram because these diagrams are designed for pod-pod traffic, but basically it would come in towards the `TC @ NIC` point and then the BPF program would determine that the traffic is actually for the local host, and pass it up towards PREROUTING iptables hook, then it would be routed, go through INPUT iptables hook, and up to the application (sitting where the userspace proxy box is).

---

Why do I explain this? Hopefully to provide an overview of why traffic from one cilium-health daemon towards a cilium-health endpoint goes from the source node through `cilium_host` -> `cilium_vxlan` -> `eth0`, then across the underlying fabric (in this case, the virtualbox-provided network linking the VMs), then into `eth0` -> `cilium_vxlan` -> `cilium-health`.... then back again for response traffic. If we can pinpoint which of these boxes we lose the traffic, that can hint at the problem. Furthermore, each box in the diagrams (and also the point that doesn't have a box before POSTROUTING / after PREROUTING, ie the linux routing table) can potentially provide additional introspection points to query to follow the traffic. For the TC points, that's where we attach BPF programs and that's where we can observe traffic using `cilium monitor`.

Touching back on my previous question, it's possible that the encapsulation that occurs when transmitting into the `cilium_vxlan` device (and decapsulation when receiving on the `cilium_vxlan` device on the other node) hides IPv6 traffic in one or both cases, because underneath everything the IPv6 traffic is inside the IPv4+VXLAN tunnel. By attaching tcpdump/wireshark to each device along this path, perhaps we can identify where the packets disappear?

**Comment by iffyio** [comment]
Thanks a lot for the overview! :smile:  I could identify echo request packets received on the destination `cilium_vxlan` and `cilium_health` interfaces and while `cilium_health` routes back a response, the destination `cilium_vxlan` does not. That was why I suspected that `cilium_vxlan` was dropping traffic, at least in the response direction - so the case `cilium_health` -> `cilium_host` -> `cilium_vxlan` ... -> source.

For example, with a ping to destination health endpoint (2604) `f00d::a0a:0:0:3ba2`, I get the following output running `cilium monitor --related-to 2604` on the destination:

```
-> endpoint 2604 flow 0x656d30f7 identity 1->4 state new ifindex cilium_health: fd04::12 -> f00d::a0a:0:0:3ba2 EchoRequest
<- endpoint 2604 flow 0xa47896a1 identity 4->0 state new ifindex 0: f00d::a0a:0:0:3ba2 -> fd04::12 EchoReply
-> stack flow 0xa47896a1 identity 4->2 state reply ifindex 0: f00d::a0a:0:0:3ba2 -> fd04::12 EchoReply
-> 0: f00d::a0a:0:0:3ba2 -> fd04::12 EchoReply
```

Would this suggest that `cilium_vxlan` does eventually receive response packets on the destination to transmit back to the source node? (I can't really tell the significance of identities 0 and 2) Also, `cilium monitor` on the source only shows `EchoRequest`s and I don't see any response traffic coming back into it otherwise.

**Comment by joestringer** [comment]
> `-> endpoint 2604 flow 0x656d30f7 identity 1->4 state new ifindex cilium_health: fd04::12 -> f00d::a0a:0:0:3ba2 EchoRequest`

OK, so the echo request is sent "to the endpoint" (`-> endpoint`).. identity 1 is `host`, 4 is `cilium-health`

> `<- endpoint 2604 flow 0xa47896a1 identity 4->0 state new ifindex 0: f00d::a0a:0:0:3ba2 -> fd04::12 EchoReply`

Echo response comes back "from the endpoint" (`<- endpoint`), great.. (identity `0` is unknown, because it's coming from the endpoint and the destination identity is not determined just yet..)

`-> stack flow 0xa47896a1 identity 4->2 state reply ifindex 0: f00d::a0a:0:0:3ba2 -> fd04::12 EchoReply`

That same packet (same `flow` value) is now passed up to the stack. This seems to suggest that it's going back to the local node's `cilium-health` server.

-> 0: f00d::a0a:0:0:3ba2 -> fd04::12 EchoReply

I'm a little surprised to see something like this, seems like it's the same packet as the two immediately previous monitor lines but this line isn't really telling us any additional information.

As far as I can tell from these monitor lines, this is a valid and successful ICMP probe from the local `cilium-health` server to the local `cilium-health` endpoint.

Seems like the local node IP here is fd04::12, can you identify the other node's IPv6 address and the corresponding monitor traffic? (if `cilium monitor --related-to ...` is not showing any, the traffic might not be making its way to that node at all)

**Comment by iffyio** [comment]
In the example, src was k8s2 `fd04::12` (`f00d::a0a:100:0:59b4` endpoint 2604) and dst was k8s1 `fd04::11` (health `f00d::a0a:0:0:3ba2` endpoint 2390)
The previous `cilium monitor --related-to 2604` command was run on k8s1.
Running `cilium monitor --related-to 2390` on k8s2 comes up empty. Though I can see the request packet with grep

```
root@k8s2:~# cilium monitor | grep -i echo
level=info msg="Initializing dissection cache..." subsys=monitor
<- host flow 0x53c3bd9e identity 2->0 state new ifindex 0: fd04::12 -> f00d::a0a:0:0:3ba2 EchoRequest
-> overlay flow 0x53c3bd9e identity 1->0 state new ifindex cilium_vxlan: fd04::12 -> f00d::a0a:0:0:3ba2 EchoRequest

```

**Comment by joestringer** [comment]
@iffyio ah, then looks like I misinterpreted. In that case, we don't know how to deliver the traffic from BPF (because the dst IP of the packet is an underlay address), so we pass the response up the stack to Linux to perform the routing. Next stop would be the routing table:

```
ip route get fd04::12
```

Then start to follow how the response goes back. Maybe this routes it back out the network-facing device, then the question is: Can we see the response on the network-facing devices, first on the destination VM, then at the source VM?

**Comment by iffyio** [comment]
@joestringer ipv6 packet forwarding seems culprit :open_mouth:  `sysctl net.ipv6.conf.all.forwarding` showed it was disabled, turning it on, I'm able to ping between both hosts and pods.

`ip route get fd04::12` on the destination returned:
```
fd04::12 from :: dev enp0s8 proto kernel src fd04::11 metric 256 pref medium
```

And initially I wasn't able to observe any response with tcpdump on `enp0s8` on any host but I could on both after enabling forwarding.

**Comment by joestringer** [comment]
@iffyio that's great!

I see this is configured in the dev VM:
```
contrib/vagrant/start.sh:sysctl -w net.ipv6.conf.all.forwarding=1
```

A similar line likely just needs to be added to `tests/k8s/Vagrantfile`.

**Comment by iffyio** [comment]
Thanks @joestringer! I'll create a separate PR for this change

File: pkg/health/server/prober.go (hunk 1 above)
Comment (iffyio) [reply pkg/health/server/prober.go]: Fixed!

**Comment by joestringer** [comment]
This looks like it depends on #8160 so will need to merge that first. I've updated the labels and run the CI there to try to push that forward.

**Comment by iffyio** [comment]
Rebased onto master with #8160 merged. I think it should be ok for a CI run

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please
