### PR TITLE
ipsec: Clean up stale XFRM policies and states

### LINKED ISSUE #24780: Cross-nodes connectivity issues with IPsec on upgrades
When upgrading to 1.11.15, 1.12.8, or 1.13.1 with IPsec enabled, cross-node connectivity fails completely. New cluster installations on those versions are okay. This issue happens because stale Linux XFRM states and policies are left behind and they conflict with the new states and policies we install on those versions.

### Mitigation

The best is obviously to wait for the fix before upgrading. If that is not possible or if the migration already happened, there are three solutions:
1. Restart or replace the nodes such that new nodes with a clean state are used.
2. Manually clean the XFRM states and policies on all nodes with `ip x s flush && ip x p flush` from Cilium agent pods.
3. Disable IPsec.

### PR DESCRIPTION
**Pull request by pchaigno**
First commit is a bit of refactoring. Second implements a proper function to update XFRM states. Third adds a catch-all default-drop policy to avoid leaking plain-text traffic during the cleanup. Fourth commit implements the cleanup itself.
See commit descriptions for details.

Fixes: https://github.com/cilium/cilium/pull/24030.
Fixes: https://github.com/cilium/cilium/issues/24780.
Updates: https://github.com/cilium/cilium/issues/24010.

```
Fix IPsec bug that causes connectivity issues across nodes when upgrading from a previous version of Cilium.
```

### CODE REVIEW

File: pkg/datapath/linux/ipsec/ipsec_linux.go [hunk 1]
```diff
@@ -149,6 +149,96 @@ func ipSecJoinState(state *netlink.XfrmState, keys *ipSecKey) {
...
+}
+
+// Attempt to remove any XFRM state that conflicts with the state we just tried
+// to add. To find those conflicting states, we need to use the same logic that
+// the kernel used to reject our check with EEXIST. That logic is upstream in
+// __xfrm_state_lookup.
+func xfrmDeleteConflictingState(states []netlink.XfrmState, new *netlink.XfrmState) (bool, error) {
+	deletedSomething := false
+	for _, s := range states {
+		if new.Spi == s.Spi && new.Mark == s.Mark &&
```
Comment (jschwinger233) [inline pkg/datapath/linux/ipsec/ipsec_linux.go]: `xfrmState.Mark` is of type `*XfrmMark`, so `new.Mark == s.Mark` is true only if `new.Mark == s.Mark == nil`, or they point to the same object, but the latter one can't be true, am I right?

Comment (pchaigno) [reply pkg/datapath/linux/ipsec/ipsec_linux.go]: That's correct. I've changed it to check both variables against `nil`.

**Review by michi-covalent — APPROVED** [review]
lgtm for cli team files

**Comment by michi-covalent** [comment]
oh i guess it already is, i see the corresponding issue has release-blocker labels: https://github.com/cilium/cilium/issues/24780

**Review by jschwinger233 — APPROVED** [review]

File: pkg/datapath/linux/ipsec/ipsec_linux.go [hunk 2]
```diff
@@ -83,6 +83,17 @@ var (
 	// replaced with a newer one, allowing to reclaim old keys only after
 	// enough time has passed since their replacement
 	ipSecKeysRemovalTime = make(map[uint8]time.Time)
+
+	wildcardIPv4   = net.ParseIP("0.0.0.0")
+	wildcardCIDRv4 = &net.IPNet{
+		IP:   wildcardIPv4,
+		Mask: net.IPv4Mask(0, 0, 0, 0),
+	}
+	wildcardIPv6   = net.ParseIP("0::0")
```
Comment (YutaroHayakawa) [inline pkg/datapath/linux/ipsec/ipsec_linux.go:93]: Nit: This can be `::`.

File: pkg/datapath/linux/ipsec/ipsec_linux.go [hunk 3]
```diff
@@ -372,14 +377,104 @@ func IpSecReplacePolicyFwd(dst *net.IPNet, tmplDst net.IP) error {
...
+				logfields.DestinationCIDR: p.Dst,
+			}).Error("Failed to remove stale XFRM policy")
+		}
+	}
+}
+
+func removeStaleStates(family int) {
+	states, err := netlink.XfrmStateList(family)
+	if err != nil {
+		log.WithError(err).Error("Cannot get XFRM states")
```
Comment (YutaroHayakawa) [inline pkg/datapath/linux/ipsec/ipsec_linux.go:449]: Don't we need return here?

File: pkg/datapath/linux/ipsec/ipsec_linux.go [hunk 4]
```diff
@@ -372,14 +377,104 @@ func IpSecReplacePolicyFwd(dst *net.IPNet, tmplDst net.IP) error {
...
+	removeStaleXFRMOnce.Do(func() {
+		removeStalePolicies(family)
+		removeStaleStates(family)
+	})
+}
+
+func removeStalePolicies(family int) {
+	policies, err := netlink.XfrmPolicyList(family)
+	if err != nil {
+		log.WithError(err).Error("Cannot get XFRM policies")
```
Comment (YutaroHayakawa) [inline pkg/datapath/linux/ipsec/ipsec_linux.go:416]: Don't we need return here?

**Review by YutaroHayakawa — APPROVED** [review]
LGTM with non-blocking nits.

**Review by asauber — APPROVED** [review]
`cli` owned files (the logger) LGTM. I'll defer to others for now on the state replacement correctness.

**Review by asauber — CHANGES_REQUESTED** [review]

**Review by asauber — APPROVED** [review]

File: pkg/datapath/linux/ipsec/ipsec_linux.go (hunk 4 above)
Comment (pchaigno) [reply pkg/datapath/linux/ipsec/ipsec_linux.go:416]: Yep, good point. I'll do that as a follow up, with a bunch of other IPsec code improvements, in the interest of merging this quickly and unblocking backports.

I've checked [the source](https://github.com/vishvananda/netlink/blob/v1.1.0/xfrm_policy_linux.go#L127) for `XfrmPolicyList` and, if there is an error, an empty slice is always return, so the subsequent for loop will just be a noop.
