### PR TITLE
cni: Avoid returning error in DEL command

### LINKED ISSUE #8313: Avoid CNI DEL to fail
containerd will never retry a failed CNI DEL call so it is better to clean up as much as possible and never return an error. Failing will prevent from CNI plugins further in the chain to not be invoked which will lead to more leaks.

Leaking of resource on CNI DEL is fine in most cases, the main reason for failure is the agent being down, once it comes back up, it will delete all resources which have been left over or cannot be associated with a running workload.

### PR DESCRIPTION
**Pull request by vadorovsky**
CNI DEL operations might be never retried by the container runtime, so
it's better to clean up as much as possible and make sure that Cilium
agent is going to clean up everything after start.

Fixes: #8313

Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8335)

### CODE REVIEW

File: plugins/cilium-cni/cilium-cni.go [hunk 1]
```diff
@@ -544,7 +544,9 @@ func cmdDel(args *skel.CmdArgs) error {
 		)
 
 		if chainAction.ImplementsDelete() {
-			return chainAction.Delete(context.TODO(), ctx)
```
Comment (vadorovsky) [inline plugins/cilium-cni/cilium-cni.go]: @tgraf Why is CNI plugin returning here immediately? We don't want to perform cleanups below (like removing an endpoint) after running chained plugin(s)? Is there something which I'm missing?

I'm wondering whether I should `return` here or not. So far I removed the `return` and I'm just logging an error.

**Comment by mrostecki** [comment]
test-me-please

File: plugins/cilium-cni/cilium-cni.go (hunk 1 above)
Comment (tgraf) [reply plugins/cilium-cni/cilium-cni.go]: If the chaining implements delete then it will release all resources in that delete command.

File: plugins/cilium-cni/cilium-cni.go [hunk 2]
```diff
@@ -529,7 +529,7 @@ func cmdDel(args *skel.CmdArgs) error {
 	c, err := client.NewDefaultClientWithTimeout(defaults.ClientConnectTimeout)
 	if err != nil {
 		// this error can be recovered from
-		return fmt.Errorf("unable to connect to Cilium daemon: %s", err)
+		logger.WithError(err).Warningf("unable to connect to Cilium daemon")
```
Comment (tgraf) [inline plugins/cilium-cni/cilium-cni.go]: I don't think we can continue here as `c` will be nil.

File: plugins/cilium-cni/cilium-cni.go [hunk 3]
```diff
@@ -562,11 +564,6 @@ func cmdDel(args *skel.CmdArgs) error {
 		//              Recoverable() will return true if error can be
 		//              retried
 		log.WithError(err).Warning("Errors encountered while deleting endpoint")
-		if clientError, ok := err.(client.ClientError); ok {
-			if clientError.Recoverable() {
```
Comment (tgraf) [inline plugins/cilium-cni/cilium-cni.go:566]: Is something still using `Recoverable()`?

**Review by tgraf — CHANGES_REQUESTED** [review]

File: plugins/cilium-cni/cilium-cni.go (hunk 3 above)
Comment (vadorovsky) [reply plugins/cilium-cni/cilium-cni.go:566]: Yes, the chained veth plugin is using it.

https://github.com/cilium/cilium/blob/master/plugins/cilium-cni/chaining/generic-veth/generic-veth.go#L215

Should I remove it there as well? Maybe we should avoid returning errors in chained plugins as well.

Comment (vadorovsky) [reply plugins/cilium-cni/cilium-cni.go:566]: For now I removed it. Let me know if you think that it should remain.

**Comment by mrostecki** [comment]
test-me-please

**Comment by mrostecki** [comment]
test-me-please

**Comment by mrostecki** [comment]
test-missing-k8s

**Comment by mrostecki** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]
