### PR TITLE
cilium: Improve user experience of policy trace with regard to port a…

### LINKED ISSUE #15387: Improve user experience of policy trace with regard to port and protocol
## Bug report

**General Information**

- Cilium version (run `cilium version`): 1.9.5
- Kernel version (run `uname -a`): Linux aks-stand16-26081535-vmss000014 5.4.0-1036-azure #38~18.04.1-Ubuntu SMP Wed Jan 6 18:26:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...): AKS 1.18.14
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

We have a namespace with these two policies.

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka-cluster-network-policy-kafka
  namespace: kafka
spec:
  ingress:
  - from:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          strimzi.io/kind: cluster-operator
    - podSelector:
        matchLabels:
          strimzi.io/name: kafka-cluster-kafka
    - podSelector:
        matchLabels:
          strimzi.io/name: kafka-cluster-entity-operator
    - podSelector:
        matchLabels:
          strimzi.io/name: kafka-cluster-kafka-exporter
    - podSelector:
        matchLabels:
          strimzi.io/name: kafka-cluster-cruise-control
    ports:
    - port: 9091
      protocol: TCP
  - ports:
    - port: 9092
      protocol: TCP
  - ports:
    - port: 9093
      protocol: TCP
  - ports:
    - port: 9404
      protocol: TCP
  podSelector:
    matchLabels:
      strimzi.io/name: kafka-cluster-kafka
  policyTypes:
  - Ingress
```

```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: kafka-cluster-all
  namespace: kafka
spec:
  endpointSelector:
    matchLabels:
      app: kafka-cluster
  ingress:
  - fromEndpoints:
    - {}
```

Together, these policies allow traffic from other namespaces to ports 9092, 9093 and 9404.

However, using `cilium policy trace` to verify this shows `Final verdict: DENIED`. I'm assuming that the NetworkPolicy is not taken into account here.

```
root@aks-fdbts-26081535-vmss00001I:/home/cilium# cilium policy trace --src-identity 43182 --dst-identity 58080
----------------------------------------------------------------
Tracing From: [k8s:app=context-api-entity-matcher-worker, k8s:app.kubernetes.io/managed-by=spinnaker, k8s:app.kubernetes.io/name=context-api, k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/managed-by=spinnaker, k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/name=cluster-config, k8s:io.cilium.k8s.namespace.labels.name=context, k8s:io.cilium.k8s.namespace.labels.team=contextualization, k8s:io.cilium.k8s.policy.cluster=default, k8s:io.cilium.k8s.policy.serviceaccount=default, k8s:io.kubernetes.pod.namespace=context, k8s:team=contextualization] => To: [k8s:app=kafka-cluster, k8s:app.kubernetes.io/instance=kafka-cluster, k8s:app.kubernetes.io/managed-by=strimzi-cluster-operator, k8s:app.kubernetes.io/name=kafka, k8s:app.kubernetes.io/part-of=strimzi-kafka-cluster, k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/managed-by=spinnaker, k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/name=cluster-config, k8s:io.cilium.k8s.namespace.labels.name=kafka, k8s:io.cilium.k8s.policy.cluster=default, k8s:io.cilium.k8s.policy.serviceaccount=kafka-cluster-kafka, k8s:io.kubernetes.pod.namespace=kafka, k8s:statefulset.kubernetes.io/pod-name=kafka-cluster-kafka-1, k8s:strimzi.io/cluster=kafka-cluster, k8s:strimzi.io/kind=Kafka, k8s:strimzi.io/name=kafka-cluster-kafka] Ports: [0/ANY]
Resolving ingress policy for [k8s:app=kafka-cluster k8s:app.kubernetes.io/instance=kafka-cluster k8s:app.kubernetes.io/managed-by=strimzi-cluster-operator k8s:app.kubernetes.io/name=kafka k8s:app.kubernetes.io/part-of=strimzi-kafka-cluster k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/managed-by=spinnaker k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/name=cluster-config k8s:io.cilium.k8s.namespace.labels.name=kafka k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=kafka-cluster-kafka k8s:io.kubernetes.pod.namespace=kafka k8s:statefulset.kubernetes.io/pod-name=kafka-cluster-kafka-1 k8s:strimzi.io/cluster=kafka-cluster k8s:strimzi.io/kind=Kafka k8s:strimzi.io/name=kafka-cluster-kafka]
* Rule {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"kafka","k8s:strimzi.io/name":"kafka-cluster-kafka"}}: selected
    Enforcing requirements [{Key:k8s.io.kubernetes.pod.namespace Operator:Exists Values:[]}]
    Allows from labels {"matchLabels":{"k8s:strimzi.io/kind":"cluster-operator"},"matchExpressions":[{"key":"k8s:io.kubernetes.pod.namespace","operator":"Exists"}]}
      No label match for [k8s:app=context-api-entity-matcher-worker k8s:app.kubernetes.io/managed-by=spinnaker k8s:app.kubernetes.io/name=context-api k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/managed-by=spinnaker k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/name=cluster-config k8s:io.cilium.k8s.namespace.labels.name=context k8s:io.cilium.k8s.namespace.labels.team=contextualization k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=context k8s:team=contextualization]
    Allows from labels {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"kafka","k8s:strimzi.io/name":"kafka-cluster-kafka"}}
      No label match for [k8s:app=context-api-entity-matcher-worker k8s:app.kubernetes.io/managed-by=spinnaker k8s:app.kubernetes.io/name=context-api k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/managed-by=spinnaker k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/name=cluster-config k8s:io.cilium.k8s.namespace.labels.name=context k8s:io.cilium.k8s.namespace.labels.team=contextualization k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=context k8s:team=contextualization]
    Allows from labels {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"kafka","k8s:strimzi.io/name":"kafka-cluster-entity-operator"}}
      No label match for [k8s:app=context-api-entity-matcher-worker k8s:app.kubernetes.io/managed-by=spinnaker k8s:app.kubernetes.io/name=context-api k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/managed-by=spinnaker k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/name=cluster-config k8s:io.cilium.k8s.namespace.labels.name=context k8s:io.cilium.k8s.namespace.labels.team=contextualization k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=context k8s:team=contextualization]
    Allows from labels {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"kafka","k8s:strimzi.io/name":"kafka-cluster-kafka-exporter"}}
      No label match for [k8s:app=context-api-entity-matcher-worker k8s:app.kubernetes.io/managed-by=spinnaker k8s:app.kubernetes.io/name=context-api k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/managed-by=spinnaker k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/name=cluster-config k8s:io.cilium.k8s.namespace.labels.name=context k8s:io.cilium.k8s.namespace.labels.team=contextualization k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=context k8s:team=contextualization]
    Allows from labels {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"kafka","k8s:strimzi.io/name":"kafka-cluster-cruise-control"}}
      No label match for [k8s:app=context-api-entity-matcher-worker k8s:app.kubernetes.io/managed-by=spinnaker k8s:app.kubernetes.io/name=context-api k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/managed-by=spinnaker k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/name=cluster-config k8s:io.cilium.k8s.namespace.labels.name=context k8s:io.cilium.k8s.namespace.labels.team=contextualization k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=context k8s:team=contextualization]
      Found all required labels
      Allows port [{9092 TCP}]
        No port match found
      Found all required labels
      Allows port [{9093 TCP}]
        No port match found
      Found all required labels
      Allows port [{9404 TCP}]
        No port match found
* Rule {"matchLabels":{"any:app":"kafka-cluster","k8s:io.kubernetes.pod.namespace":"kafka"}}: selected
    Allows from labels {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"kafka"}}
      No label match for [k8s:app=context-api-entity-matcher-worker k8s:app.kubernetes.io/managed-by=spinnaker k8s:app.kubernetes.io/name=context-api k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/managed-by=spinnaker k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/name=cluster-config k8s:io.cilium.k8s.namespace.labels.name=context k8s:io.cilium.k8s.namespace.labels.team=contextualization k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=context k8s:team=contextualization]
2/59 rules selected
Found no allow rule
Found no deny rule
Ingress verdict: denied
Final verdict: DENIED
```

The identities were collected from `hubble observe`:

```
{"time":"2021-03-18T13:13:12.991348254Z","verdict":"FORWARDED","ethernet":{"source":"62:4f:11:75:33:f5","destination":"26:05:d1:cc:81:6e"},"IP":{"source":"10.240.29.7","destination":"10.240.27.183","ipVersion":"IPv4"},"l4":{"TCP":{"source_port":57264,"destination_port":9092,"flags":{"PSH":true,"ACK":true}}},"source":{"identity":43182,"namespace":"context","labels":["k8s:app.kubernetes.io/managed-by=spinnaker","k8s:app.kubernetes.io/name=context-api","k8s:app=context-api-entity-matcher-worker","k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/managed-by=spinnaker","k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/name=cluster-config","k8s:io.cilium.k8s.namespace.labels.name=context","k8s:io.cilium.k8s.namespace.labels.team=contextualization","k8s:io.cilium.k8s.policy.cluster=default","k8s:io.cilium.k8s.policy.serviceaccount=default","k8s:io.kubernetes.pod.namespace=context","k8s:team=contextualization"],"pod_name":"context-api-entity-matcher-worker-75c9f8cb7d-bfxjz"},"destination":{"ID":1278,"identity":58080,"namespace":"kafka","labels":["k8s:app.kubernetes.io/instance=kafka-cluster","k8s:app.kubernetes.io/managed-by=strimzi-cluster-operator","k8s:app.kubernetes.io/name=kafka","k8s:app.kubernetes.io/part-of=strimzi-kafka-cluster","k8s:app=kafka-cluster","k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/managed-by=spinnaker","k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/name=cluster-config","k8s:io.cilium.k8s.namespace.labels.name=kafka","k8s:io.cilium.k8s.policy.cluster=default","k8s:io.cilium.k8s.policy.serviceaccount=kafka-cluster-kafka","k8s:io.kubernetes.pod.namespace=kafka","k8s:statefulset.kubernetes.io/pod-name=kafka-cluster-kafka-1","k8s:strimzi.io/cluster=kafka-cluster","k8s:strimzi.io/kind=Kafka","k8s:strimzi.io/name=kafka-cluster-kafka"],"pod_name":"kafka-cluster-kafka-1"},"Type":"L3_L4","node_name":"aks-stand16-26081535-vmss000018","event_type":{"type":4},"traffic_direction":"INGRESS","trace_observation_point":"TO_ENDPOINT","Summary":"TCP Flags: ACK, PSH"}
```

### PR DESCRIPTION
**Pull request by Maddy007-maha**
cilium: Improve user experience of policy trace related to port/protocol

Description: As part of 'cilium policy trace' command, dport was an optional paramter due to which it takes port and protocol
as 0 and ANY respectively due to which it causing undefined behaviors.
Root Cause: --dport parameter is an optional argument under 'cilium policy trace'
Fix: We made this --dport parameter as mandatory argument under 'cilium policy trace'

Fixes: #15387

Signed-off-by: Maddy007-maha <mahadev.panchal@accuknox.com>

```
--dport flag is a mandatory argument in cilium policy trace command with port and protocol
```

### CODE REVIEW

File: cilium/cmd/policy_trace.go [hunk 1]
```diff
@@ -46,7 +46,7 @@ var srcEndpoint, dstEndpoint, srcK8sPod, dstK8sPod, srcK8sYaml, dstK8sYaml strin
 
 // policyTraceCmd represents the policy_trace command
 var policyTraceCmd = &cobra.Command{
-	Use:   "trace ( -s <label context> | --src-identity <security identity> | --src-endpoint <endpoint ID> | --src-k8s-pod <namespace:pod-name> | --src-k8s-yaml <path to YAML file> ) ( -d <label context> | --dst-identity <security identity> | --dst-endpoint <endpoint ID> | --dst-k8s-pod <namespace:pod-name> | --dst-k8s-yaml <path to YAML file>) [--dport <port>[/<protocol>]",
+	Use:   "trace ( -s <label context> | --src-identity <security identity> | --src-endpoint <endpoint ID> | --src-k8s-pod <namespace:pod-name> | --src-k8s-yaml <path to YAML file> ) ( -d <label context> | --dst-identity <security identity> | --dst-endpoint <endpoint ID> | --dst-k8s-pod <namespace:pod-name> | --dst-k8s-yaml <path to YAML file>) --dport <port>[/<protocol>]",
```
Comment (twpayne) [inline cilium/cmd/policy_trace.go:49]: The closing `]` is still present, leaving the parentheses unbalanced.

**Review by twpayne — CHANGES_REQUESTED** [review]
Please also fill in the PR template, specifically the release notes. The release notes should probably something like "Require --dport flag in cilium policy trace command".

File: cilium/cmd/policy_trace.go (hunk 1 above)
Comment (Maddy007-maha) [reply cilium/cmd/policy_trace.go:49]: Thanks for the comments,

Undoubtedly it seems to be an unbalanced parentheses ` ]` by reviewing the changes But it was unbalanced parentheses earlier and it got fixed by removing the optional parentheses.

**Review by twpayne — CHANGES_REQUESTED** [review]
Thanks for the updates. The author of the commit is currently `vagrant@vagrant.vm` which does not match the Signed-Off-By line in the commit message. Please could you change this.

**Comment by Maddy007-maha** [comment]
> Thanks for the updates. The author of the commit is currently `vagrant@vagrant.vm` which does not match the Signed-Off-By line in the commit message. Please could you change this.



> Thanks for the updates. The author of the commit is currently `vagrant@vagrant.vm` which does not match the Signed-Off-By line in the commit message. Please could you change this.

Yeah I have changed accordingly

-Thank you

**Review by twpayne — APPROVED** [review]
Thank you!

**Comment by twpayne** [comment]
test-me-please

**Comment by Maddy007-maha** [comment]
> test-me-please

Hi @twpayne,

Looks like some test suites are failed and after inspecting those failed logs => It looks like it's due to the change of command (--dport is a mandatory option now).

Do we need to rewrite the test cases according to this fix?
Please guide me on this.

-Thanks

**Comment by twpayne** [comment]
Yes, the test cases need to be updated for the code change.

**Review by nbusseneau — APPROVED** [review]
LGTM, thanks :)

**Review by nbusseneau — CHANGES_REQUESTED** [review]
Actually, no... Sorry I posted on the wrong PR 😅
I think the test cases should be updated to work with the now mandatory option, not removed ;)

**Comment by Maddy007-maha** [comment]
> Actually, no... Sorry I posted on the wrong PR 😅
> 
> I think the test cases should be updated to work with the now mandatory option, not removed ;)

Yeah I have updated the test cases as well

Kindly review it

-Thanks

**Comment by nbusseneau** [comment]
@Maddy007-maha Can you double-check that you did push the updates? In the current set of changes, I only see test removals, not updates. Am I missing something?

**Comment by Maddy007-maha** [comment]
> @Maddy007-maha Can you double-check that you did push the updates? In the current set of changes, I only see test removals, not updates. Am I missing something?

If you see the test cases, we have 2 categories as follows
1. with `--dport `argument test cases
2. without `--dport `argument test cases

As we made `--dport ` as a mandatory argument, so we removed the rest of the void (unused `--dport` option) test cases.
And we are already taking care of `--dport` argument test cases.

File: test/k8sT/Policies.go [hunk 2]
```diff
@@ -263,11 +263,6 @@ var _ = SkipDescribeIf(func() bool {
 				namespaceForTest, appPods[helpers.App2], namespaceForTest, appPods[helpers.App1]))
 			trace.ExpectContains("Final verdict: ALLOWED", "Policy trace output mismatch")
 
-			trace = kubectl.CiliumExecMustSucceed(context.TODO(), ciliumPod, fmt.Sprintf(
-				"cilium policy trace --src-k8s-pod %s:%s --dst-k8s-pod %s:%s",
-				namespaceForTest, appPods[helpers.App3], namespaceForTest, appPods[helpers.App1]))
-			trace.ExpectContains("Final verdict: DENIED", "Policy trace output mismatch")
-
```
Comment (nbusseneau) [inline test/k8sT/Policies.go:293]: > If you see the test cases, we have 2 categories as follows
> 
> 1. with `--dport `argument test cases
> 2. without `--dport `argument test cases
> 
> As we made `--dport ` as a mandatory argument, so we removed the rest of the void (unused `--dport` option) test cases.
> And we are already taking care of `--dport` argument test cases so no need for any changes

@Maddy007-maha Thanks for your answer. I agree with the fact that we could have removed the tests without `--dport` if they were duplicated with the `--dport` tests, but this does not seem to be the case to me.

Let's take a look at this example. We have two tests:

1. With `--dport`, using `helpers.App2`, expecting `ALLOWED`:

```go
trace := kubectl.CiliumExecMustSucceed(context.TODO(), ciliumPod, fmt.Sprintf(
		"cilium policy trace --src-k8s-pod %s:%s --dst-k8s-pod %s:%s --dport 80/TCP",
	namespaceForTest, appPods[helpers.App2], namespaceForTest, appPods[helpers.App1]))
trace.ExpectContains("Final verdict: ALLOWED", "Policy trace output mismatch")
```

2. Without `--dport`, using `helpers.App3`, expecting `DENIED`:

```go
trace = kubectl.CiliumExecMustSucceed(context.TODO(), ciliumPod, fmt.Sprintf(
	"cilium policy trace --src-k8s-pod %s:%s --dst-k8s-pod %s:%s",
	namespaceForTest, appPods[helpers.App3], namespaceForTest, appPods[helpers.App1]))
trace.ExpectContains("Final verdict: DENIED", "Policy trace output mismatch")
```

They look similar, but are not duplicates: my understanding is that they work hand-in-hand, and both are required to cover what we want to test. Thus we can't simply remove them: they should be updated to use `--dport` instead :)

**Review by nbusseneau — CHANGES_REQUESTED** [review]
@Maddy007-maha I re-read #15387 in more details, and actually what we want is not to require `--dport`, but rather than when `--dport` is used, always require both ports and protocol to be provided.

**Comment by Maddy007-maha** [comment]
> @Maddy007-maha I re-read #15387 in more details, and actually what we want is not to require `--dport`, but rather than when `--dport` is used, always require both ports and protocol to be provided.

Thanks for the clarification @nbusseneau 

But I have some queries,

The reason we made these current changes for the mandatory option of `--dport` is because without **dport** option we observed a wrong policy trace info from this description https://github.com/cilium/cilium/issues/15387#issue-835002035
 
If we observe the below errors and analyze it,  **"No port match found"** because of no port and protocol info provided to the `cilium policy trace` command due to which the policy trace verdict got DENIED.

Query1: Is it possible to use `policy trace` without **dport** argument.
              If yes, we can only enable `port/protocol` as a must arguments to the `--dport` option

Query2: What if there is port info is not provided NP?
              How can we handle it
Answer(likely/unlikely): Do they use `policy trace` command without `--dport` option?

Issue: From the below errors, without the dport option => port info does not match and as a result policy trace verdict got DENIED. is this the correct behavior or the user have to issue the right command with appropriate options (i.e `dport`)

```
Found all required labels
      Allows port [{9092 TCP}]
        No port match found
      Found all required labels
      Allows port [{9093 TCP}]
        No port match found
      Found all required labels
      Allows port [{9404 TCP}]
        No port match found
 Rule {"matchLabels":{"any:app":"kafka-cluster","k8s:io.kubernetes.pod.namespace":"kafka"}}: selected
    Allows from labels {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"kafka"}}
      No label match for [k8s:app=context-api-entity-matcher-worker k8s:app.kubernetes.io/managed-by=spinnaker k8s:app.kubernetes.io/name=context-api k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/managed-by=spinnaker k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/name=cluster-config k8s:io.cilium.k8s.namespace.labels.name=context k8s:io.cilium.k8s.namespace.labels.team=contextualization k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=context k8s:team=contextualization]
2/59 rules selected
Found no allow rule
Found no deny rule
Ingress verdict: denied
Final verdict: DENIED
```
Kindly clarify on above queries So that we are all in the same context.

**Comment by nbusseneau** [comment]
> Hi @nbusseneau,
> If we refer to this comment [#15387 (comment)](https://github.com/cilium/cilium/issues/15387#issuecomment-802191452)
> which clearly explains the port and protocol are required as an argument.
> 
> If we do skip the `dport `option it takes wildcard {0/ANY} values which wont match with any policies and as a result it shows invalid results.
> 
> For Eg please refer [#15387 (comment)](https://github.com/cilium/cilium/issues/15387#issue-835002035)
> As it gives invalid results with wild card values, we have made changes for the `dport` option as a mandatory argument.

@Maddy007-maha Yes, I did see Thomas' comment, and while I agree on first read it might look like an argument for having `--dport` as required, on a second read and with the whole issue context, it is not: I double confirm that what we we want is that when `--dport` is used, we should require both ports and protocol to be provided. But `--dport` itself should stay optional.

**Comment by nbusseneau** [comment]
@Maddy007-maha Following clarification on Slack, and contrary to my previous comments, you are indeed right and we do want to mark `--dport` as required. Apologies for the confusion 👐🏻 

Can you please re-review my comment [here](https://github.com/cilium/cilium/pull/15929#discussion_r627630015) about how we can move forward to fix the tests?

**Comment by nbusseneau** [comment]
test-me-please

**Comment by nbusseneau** [comment]
test-runtime

**Comment by nbusseneau** [comment]
test-gke

**Comment by nbusseneau** [comment]
test-1.19-5.4

**Comment by nbusseneau** [comment]
ci-aks

**Comment by nbusseneau** [comment]
test-gke

**Comment by nbusseneau** [comment]
test-1.19-5.4

**Review by nbusseneau — APPROVED** [review]
Thanks, all tests have passed, I think this should be OK from a CI perspective.

**Review by twpayne — APPROVED** [review]

**Review by nbusseneau — APPROVED** [review]
Seems like you rebased and re-requested a review, right? I see no changes, so still LGTM.

**Comment by nbusseneau** [comment]
test-me-please

**Comment by nbusseneau** [comment]
ci-aks)

**Comment by nbusseneau** [comment]
test-1.20-4.19

**Comment by nbusseneau** [comment]
test-1.21-4.9

**Comment by nbusseneau** [comment]
test-runtime

**Comment by nbusseneau** [comment]
1.16 on netnext failed on `Suite-k8s-1.16.K8sDatapathConfig Encapsulation Check vxlan connectivity with per-endpoint routes` with:
```
/home/jenkins/workspace/Cilium-PR-K8s-1.16-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:518
Connectivity test between nodes failed
Expected
    <bool>: false
to be true
/home/jenkins/workspace/Cilium-PR-K8s-1.16-net-next/src/github.com/cilium/cilium/test/k8sT/DatapathConfiguration.go:257
```
I think this is a flake that hasn't been filed yet.
I am retriggering the job just in case, but am 90% sure.
