### PR TITLE
pkg/datapath: fix arp ping handling

### LINKED ISSUE #14125: CI: RuntimePrivilegedUnitTests: arping failed in TestArpPingHandling
https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/2657/testReport/junit/(root)/Suite-runtime/RuntimePrivilegedUnitTests_Run_Tests/
[372c1e59_RuntimePrivilegedUnitTests_Run_Tests.zip](https://github.com/cilium/cilium/files/5582285/372c1e59_RuntimePrivilegedUnitTests_Run_Tests.zip)

```
level=error msg="arping failed" error=timeout interface=veth0 ipAddr=9.9.9.250 subsys=linux-datapath
node_linux_test.go:1038:
 c.Assert(found, check.Equals, true)
... obtained bool = false
... expected bool = true

START: node_linux_test.go:133: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest
PASS: node_linux_test.go:133: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest	0.052s

FAIL: node_linux_test.go:950: linuxPrivilegedIPv4OnlyTestSuite.TestArpPingHandling
```

### PR DESCRIPTION
**Pull request by aanm**
Due some underlying concurrency issues, the ARP requests were dropped by
the kernel ("arp_error_report") as the neighbor lookup fails. This
caused the unit test to fail while waiting for an ARP reply, for which a
ARP request was never sent. To avoid this issue, a time.Sleep of 1
second is added in the unit test.

Fixes: c5ed9aeb217e ("node: Add unit test for node arpinging")
Signed-off-by: André Martins <andre@cilium.io>

Fixes https://github.com/cilium/cilium/issues/14125

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
retest-4.9

File: pkg/datapath/linux/node_linux_test.go [hunk 1]
```diff
@@ -1022,6 +1023,9 @@ func (s *linuxPrivilegedIPv4OnlyTestSuite) TestArpPingHandling(c *check.C) {
 		Name:        "node1",
 		IPAddresses: []nodeTypes.Address{{nodeaddressing.NodeInternalIP, ip1}},
 	}
+	// wait 1 second to give the OS time to setup the routes for the veth pairs
```
Comment (brb) [inline pkg/datapath/linux/node_linux_test.go:1026]: Does the route setup happen async in the kernel? /cc @borkmann @jrfastab

**Review by brb — APPROVED** [review]
Nice! This matches with what I saw when debugging #14125 (`From it I saw that the request which fails with the "i/o timeout" error is even not sent.`). The long term fix is to retry arpings (I'm going to create a separate issue for it).

**Comment by brb** [comment]
@aanm Why we didn't backport this to 1.8 and 1.9?

**Comment by aanm** [comment]
> @aanm Why we didn't backport this to 1.8 and 1.9?

@brb that's a good question :thinking:
