### PR TITLE
Fix k8s external IPs implementation

### LINKED ISSUE #5293: Support for ExternalIPs in Kubernetes Service
```
        // externalIPs is a list of IP addresses for which nodes in the cluster
        // will also accept traffic for this service.  These IPs are not managed by
        // Kubernetes.  The user is responsible for ensuring that traffic arrives
        // at a node with this IP.  A common example is external load-balancers
        // that are not part of the Kubernetes system.
        // +optional
        ExternalIPs []string `json:"externalIPs,omitempty" protobuf:"bytes,5,rep,name=externalIPs"`
```

cc @kbaegis

### LINKED ISSUE #9546: Simplify k8s external IPs control plane implementation
Follow up on https://github.com/cilium/cilium/pull/9092#discussion_r342141502

Already simplified in PR 9092

### PR DESCRIPTION
**Pull request by aanm**
```release-note
Fix implementation of k8s external IPs as described in kubernetes documentation
```

Fix: https://github.com/cilium/cilium/issues/9546
Fix: https://github.com/cilium/cilium/issues/5293

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9092)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

File: bpf/lib/nodeport.h [hunk 1]
```diff
@@ -646,6 +634,30 @@ static inline int nodeport_lb4(struct __sk_buff *skb, __u32 src_identity)
 		return TC_ACT_OK;
 	}
 
+        cilium_dbg_lb(skb, DBG_GENERIC, 1, 2);
+        cilium_dbg_lb(skb, DBG_GENERIC, svc->reserved, svc->is_k8s_external_ip);
```
Comment (jrajahalme) [inline bpf/lib/nodeport.h]: Left-over debugging?

File: bpf/lib/nodeport.h [hunk 2]
```diff
@@ -646,6 +634,30 @@ static inline int nodeport_lb4(struct __sk_buff *skb, __u32 src_identity)
...
+
+	if (!svc->is_k8s_external_ip) {
+                cilium_dbg_lb(skb, DBG_GENERIC, 7, 7);
+                cilium_dbg_lb(skb, DBG_GENERIC, 0x79, 0x80);
```
Comment (jrajahalme) [inline bpf/lib/nodeport.h]: Left-over debugging?

File: bpf/lib/nodeport.h [hunk 3]
```diff
@@ -733,6 +745,9 @@ static inline int rev_nodeport_lb4(struct __sk_buff *skb, int *ifindex,
 	ret = ct_lookup4(get_ct_map4(&tuple), &tuple, skb, l4_off, CT_INGRESS, &ct_state,
 			 &monitor);
 
+        cilium_dbg_lb(skb, DBG_LB4_LOOKUP_MASTER, ip4->daddr, ip4->protocol);
+        cilium_dbg_lb(skb, DBG_LB4_LOOKUP_MASTER, ip4->saddr, ip4->protocol);
```
Comment (jrajahalme) [inline bpf/lib/nodeport.h]: Left-over debugging?

**Review by jrajahalme — APPROVED** [review]
Small nits about likely left-over debugging messages.

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

File: bpf/lib/common.h [hunk 4]
```diff
@@ -553,7 +553,9 @@ struct lb6_service_v2 {
 	__u16 count;
 	__u16 rev_nat_index;
 	__u16 weight;
-	__u16 pad;
+	__u8 is_k8s_external_ip:1, /* K8s External IPs */
```
Comment (brb) [inline bpf/lib/common.h]: `s/is_k8s_external_ip/external/`?

File: bpf/bpf_sock.c [hunk 5]
```diff
@@ -204,12 +211,20 @@ int sock4_xlate(struct bpf_sock_addr *ctx)
 	struct lb4_service_v2 *svc;
 	struct lb4_key_v2 key = {
 		.dport		= ctx_get_port(ctx),
+		.address        = ctx_get_ip4(ctx),
```
Comment (brb) [inline bpf/bpf_sock.c]: Setting `key.address` will make `127.0.0.1:$NODE_PORT` unavailable from a Pod.

File: bpf/bpf_sock.c [hunk 6]
```diff
@@ -204,12 +211,20 @@ int sock4_xlate(struct bpf_sock_addr *ctx)
...
 	};
 	struct lb4_service_v2 *slave_svc;
 
 	if (!sock_proto_enabled(ctx))
 		return CONNECT_PROCEED;
 
+	svc = __lb4_lookup_service_v2(&key);
+	if (svc) {
+		if (unlikely(svc->is_k8s_external_ip)) {
```
Comment (brb) [inline bpf/bpf_sock.c]: I think a comment why we exclude ExternalIP SVC here might be useful for a reader.

File: bpf/lib/nodeport.h [hunk 7]
```diff
@@ -646,6 +631,23 @@ static inline int nodeport_lb4(struct __sk_buff *skb, __u32 src_identity)
 		return TC_ACT_OK;
 	}
 
+	if (!svc->is_k8s_external_ip) {
```
Comment (brb) [inline bpf/lib/nodeport.h]: I think you don't want to skip here and you need to modify the if-statement, as this handles a remote backend reply, which means that the reverse SNAT translation should be done.

File: cilium/cmd/service_list.go [hunk 8]
```diff
@@ -113,19 +115,19 @@ func printServiceList(w *tabwriter.Writer, list []*models.Service) {
 		var str string
 
 		if len(service.BackendAddresses) == 0 {
-			str = fmt.Sprintf("%d\t%s\t\t",
-				service.ID, service.FrontendAddress)
+			str = fmt.Sprintf("%d\t%s\t%t\t\t",
+				service.ID, service.FrontendAddress, service.ExternalIP)
```
Comment (brb) [inline cilium/cmd/service_list.go]: Does k8s allocate a ClusterIP for ExternalIP SVC? If not, then printing `FrontendAddress` for such service is not needed.

**Review by brb — CHANGES_REQUESTED** [review]
I did the first-round of reviewing the code.

One additional suggestion: we should add an info log statement when a user runs with `--enable-node-port=false` saying that `Using kube-proxy implementation of ExternalIP Service`.

File: bpf/bpf_sock.c (hunk 5 above)
Comment (aanm) [reply bpf/bpf_sock.c]: The `sock4_handle_node_port` will correctly populate `key.address`

File: cilium/cmd/bpf_lb_list.go [hunk 9]
```diff
@@ -69,22 +69,23 @@ func dumpSVC(serviceList map[string][]string) {
...
 		backendID := svcVal.GetBackendID()
+		flags := svcVal.GetFlags()
 
 		if backendID == 0 {
 			ip := "0.0.0.0"
 			if svcKey.IsIPv6() {
 				ip = "[::]"
 			}
-			entry = fmt.Sprintf("%s:%d (%d)", ip, 0, revNATID)
+			entry = fmt.Sprintf("%s:%d (%d) [FLAGS: 0x%x]", ip, 0, revNATID, flags)
```
Comment (borkmann) [inline cilium/cmd/bpf_lb_list.go]: I would prefer if we add actual human readable names instead of hex dump, eases debugging, also for the other places.

File: bpf/bpf_sock.c [hunk 10]
```diff
@@ -204,12 +211,20 @@ int sock4_xlate(struct bpf_sock_addr *ctx)
...
 	struct lb4_key_v2 key = {
 		.dport		= ctx_get_port(ctx),
+		.address        = ctx_get_ip4(ctx),
 	};
 	struct lb4_service_v2 *slave_svc;
 
 	if (!sock_proto_enabled(ctx))
 		return CONNECT_PROCEED;
 
+	svc = __lb4_lookup_service_v2(&key);
```
Comment (borkmann) [inline bpf/bpf_sock.c]: Should have a compile flag `ENABLE_EXTERNAL_SERVICES` so we don't pay the cost of looking up service twice here in fast-path if not used.

File: bpf/lib/nodeport.h (hunk 7 above)
Comment (borkmann) [inline bpf/lib/nodeport.h]: How does this set handle the case where you SNAT the external request to the remote backend and at the same time an app from the node itself directly connects to the same backend where kernel picks same source port. In other words I'm not seeing how you SNAT all other connections to avoid clashing tuples.

**Review by borkmann — CHANGES_REQUESTED** [review]

**Comment by borkmann** [comment]
Two more things that come to mind:
1) Does the case work on go orchestration side where we add two _identical_ service IPs, one as _external_ services, the other one as _non-external_ or would the daemon bail out or even override the other entry where each of the two cases would be wrong since _both_ would have to be supported simultaneously?
2) Would be great for testing to add `--external` flag support to `cilium service update` for manual testing.

**Comment by borkmann** [comment]
> 1. Does the case work on go orchestration side where we add two _identical_ service IPs, one as _external_ services, the other one as _non-external_ or would the daemon bail out or even override the other entry where each of the two cases would be wrong since _both_ would have to be supported simultaneously?

For this, the `external` bit would need to be part of the `struct lb4_key_v2` key so they can be exactly the same wrt IP/port. There's a `pad` field that could be reused.

**Comment by ianvernon** [comment]
@aanm can we remove this as a release blocker since https://github.com/cilium/cilium/pull/9125 is going to be merged?

**Comment by haoyixin** [comment]
How is progress?

**Comment by haoyixin** [comment]
How is progress?

**Comment by haoyixin** [comment]
How is the progress?

**Comment by aanm** [comment]
> How is the progress?

@haoyixin there are some datapath changes that need to be performed first before completing this PR. It will be made available with the 1.7 release.

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

File: Documentation/gettingstarted/external-ips.rst [hunk 11]
```diff
@@ -0,0 +1,82 @@
...
+
+.. note::
+
+    This is a beta feature. Please provide feedback and file a GitHub issue if
+    you experience any problems.
+
+.. note::
+
+   ExternalIPs services depend on the :ref:`host-services` feature, therefore
+   a v4.19.57, v5.1.16, v5.2.0 or more recent Linux kernel is required.
```
Comment (joestringer) [inline Documentation/gettingstarted/external-ips.rst]: It might be worth mentioning as well that v5.0 is not supported.

File: pkg/maps/lbmap/ipv4.go [hunk 12]
```diff
@@ -222,6 +223,8 @@ func (s *Service4Value) GetCount() int        { return int(s.Count) }
 func (s *Service4Value) SetRevNat(id int)     { s.RevNat = uint16(id) }
 func (s *Service4Value) GetRevNat() int       { return int(s.RevNat) }
 func (s *Service4Value) RevNatKey() RevNatKey { return &RevNat4Key{s.RevNat} }
+func (s *Service4Value) SetFlags(flags uint8) { s.Flags = flags }
+func (s *Service4Value) GetFlags() uint8      { return s.Flags }
```
Comment (joestringer) [inline pkg/maps/lbmap/ipv4.go:227]: Could this return a `type ServiceFlags uint8` which implements `Stringer` to get human-readable flags?

**Review by joestringer — COMMENTED** [review]
Minor nits on docs/cli side. Can review again if you'd like another pair of eyes on the main logic.

File: bpf/lib/common.h (hunk 4 above)
Comment (aanm) [reply bpf/lib/common.h]: Changed to `k8s_external` to distinguish to with possible external IPs (from a different cluster)

File: cilium/cmd/service_list.go (hunk 8 above)
Comment (aanm) [reply cilium/cmd/service_list.go]: Yes it does.

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

File: bpf/lib/common.h [hunk 13]
```diff
@@ -561,7 +561,9 @@ struct lb6_service {
 	__u32 backend_id;
 	__u16 count;
 	__u16 rev_nat_index;
-	__u32 pad;
+	__u8 k8s_external:1, /* K8s External IPs */
```
Comment (brb) [inline bpf/lib/common.h:564]: Maybe s/k8s_external/external_ip/ ? Let's keep the datapath free from `k8s`.

File: bpf/bpf_sock.c [hunk 14]
```diff
@@ -214,6 +214,12 @@ int sock4_xlate(struct bpf_sock_addr *ctx)
 
 	svc = __lb4_lookup_service(&key);
 	if (svc) {
+		// Do not perform service translation for external IPs because
+		// we don't want a k8s service to easily do MITM attacks for
+		// a public IP address.
+		if (svc->k8s_external) {
+			return CONNECT_PROCEED;
+		}
```
Comment (borkmann) [inline bpf/bpf_sock.c:251]: No extra `{` `}` needed above. The UDP bits are missing below in `sock4_xlate_snd()`.

Is there a case where the externalIP service is overlapping with a nodeport service on that host? Afaik, it potentially could, so here we would hit the nodeport wildcard entry which seems fine. One thing that is a bit less clear to me is that depending on the order of insertion into the services map, we either override the IP:nodeport entry for the nodeport service with the external IP one or vice versa? Is this prevented from orchestration side somehow?

File: bpf/lib/common.h [hunk 15]
```diff
@@ -561,7 +561,9 @@ struct lb6_service {
...
+	     reserved:7;
+	__u8 pad[3];
```
Comment (borkmann) [inline bpf/lib/common.h:566]: Should be part of the v6 patch?

File: bpf/lib/nodeport.h [hunk 16]
```diff
@@ -631,26 +631,26 @@ static inline int nodeport_lb4(struct __sk_buff *skb, __u32 src_identity)
...
-	service_port = bpf_ntohs(key.dport);
-	if (service_port < NODEPORT_PORT_MIN ||
-	    service_port > NODEPORT_PORT_MAX) {
-		skb->cb[CB_NAT] = NAT_DIR_INGRESS;
-		skb->cb[CB_SRC_IDENTITY] = src_identity;
-		ep_tail_call(skb, CILIUM_CALL_IPV4_NODEPORT_NAT);
-		return DROP_MISSED_TAIL_CALL;
-	}
-
-	ct_state_new.orig_dport = key.dport;
```
Comment (borkmann) [inline bpf/lib/nodeport.h]: I tried to find where we use orig_dport in our code, but looks like the last remains on policy side where removed soe time ago, so we can actually get rid of ct_state's orig_dport in general.

File: bpf/lib/nodeport.h [hunk 17]
```diff
@@ -631,26 +631,26 @@ static inline int nodeport_lb4(struct __sk_buff *skb, __u32 src_identity)
...
 	if ((svc = lb4_lookup_service(skb, &key)) != NULL) {
 		ret = lb4_local(get_ct_map4(&tuple), skb, l3_off, l4_off, &csum_off,
 				&key, &tuple, svc, &ct_state_new, ip4->saddr);
 		if (IS_ERR(ret))
 			return ret;
-	} else {
-		return TC_ACT_OK;
 	}
 
+	if ((svc == NULL) || (!svc->k8s_external)) {
```
Comment (borkmann) [inline bpf/lib/nodeport.h]: Small nit: no extra `(` `)` for both needed.

Comment (borkmann) [reply bpf/lib/nodeport.h]: What happens if this is overlapping with nodeport service, we'd never do the reverse NAT?

File: Documentation/cmdref/cilium_service_update.md [hunk 18]
```diff
@@ -19,6 +19,7 @@ cilium service update [flags]
       --frontend string    Frontend address
   -h, --help               help for update
       --id uint            Identifier
+      --k8s-external       Set service as an external IP
```
Comment (brb) [inline Documentation/cmdref/cilium_service_update.md]: `--external-ip`?

File: Documentation/gettingstarted/external-ips.rst [hunk 19]
```diff
@@ -0,0 +1,83 @@
+.. only:: not (epub or latex or html)
+
+    WARNING: You are looking at unreleased Cilium documentation.
+    Please use the official rendered version released here:
+    http://docs.cilium.io
+
+.. _external-ips:
+
+*****************************
+Kubernetes externalIPs (beta)
```
Comment (brb) [inline Documentation/gettingstarted/external-ips.rst]: Wouldn't it make sense to merge this doc with the NodePort GSG? Many parts seem to be identical between those two, so I'd create a section for the ExternalIP in the NodePort GSG.

File: cilium/cmd/service_list.go [hunk 20]
```diff
@@ -60,10 +60,11 @@ func listServices(cmd *cobra.Command, args []string) {
 }
 
 func printServiceList(w *tabwriter.Writer, list []*models.Service) {
-	fmt.Fprintln(w, "ID\tFrontend\tBackend\t")
+	fmt.Fprintln(w, "ID\tFrontend\tExternal IP\tBackend\t")
```
Comment (brb) [inline cilium/cmd/service_list.go]: s/External IP/Service Type/, and then print a service type?

File: pkg/k8s/service.go [hunk 21]
```diff
@@ -142,13 +143,52 @@ func ParseService(svc *types.Service) (ServiceID, *Service) {
 		}
 	}
 
-	return svcID, svcInfo
+	var svcInfoExternal []*Service
```
Comment (brb) [inline pkg/k8s/service.go]: Why can't you just extend the `Service` struct by adding a field to store external IPs? Then in the `pkg/k8s/watchers/service.go` create the ExternalIP services in similar way as we currently do for NodePort? This would allow us to get rid of a lot of new code below.

**Review by brb — CHANGES_REQUESTED** [review]

File: bpf/lib/common.h (hunk 13 above)
Comment (aanm) [reply bpf/lib/common.h:564]: Discussed offline, keeping with k8s_external to distinguish between a "real" possible external IP nomenclature in the future.

File: pkg/k8s/service.go (hunk 21 above)
Comment (aanm) [reply pkg/k8s/service.go]: Sorry @brb I know we have briefly discuss this offline but I don't see a good way to do it properly since an externalIP is in the end a frontend. I'll be happy to discuss this again and address it before 1.7 is released

**Review by aanm — COMMENTED** [review]
comment

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]
Overall I'm okay with merging as-is, but I do have a few minor comments that would be great to do as a follow-up cleanup. Will comment separately.

File: bpf/bpf_sock.c [hunk 22]
```diff
@@ -210,10 +210,47 @@ int sock4_xlate(struct bpf_sock_addr *ctx)
 	if (!sock_proto_enabled(ctx))
 		return CONNECT_PROCEED;
 
+#ifdef ENABLE_K8S_EXTERNAL_IP  /* ENABLE_K8S_EXTERNAL_IP */
```
Comment (borkmann) [inline bpf/bpf_sock.c:213]: Is there a way in the daemon where I'd have a --enable-external-ip flag to switch it on/off?

If required for nodeport, it could be enabled transparently, but it would at least give an option to opt-out if the additional overhead would not be needed and a way to debug potential nodeport/external IP separately.

Lets also add that flag to the doc then.

File: Documentation/cmdref/cilium_service_update.md [hunk 23]
```diff
@@ -19,6 +19,7 @@ cilium service update [flags]
       --frontend string    Frontend address
   -h, --help               help for update
       --id uint            Identifier
+      --k8s-external       Set service as a k8s external IP
```
Comment (borkmann) [inline Documentation/cmdref/cilium_service_update.md:22]: I don't think this nor the daemon flag should have any k8s mention in it, so lets do just `--external-ip`. Neither struct members in the BPF datapath since the concept itself is generic and could potentially be used outside of k8s w/o any problem. So I think it's better to remove all the k8s mentions in the datapath and agent/cli flags. We have this similarly with nodeport etc.

File: bpf/bpf_sock.c (hunk 22 above)
Comment (aanm) [reply bpf/bpf_sock.c:213]: Good point, will do this.

File: Documentation/cmdref/cilium_service_update.md (hunk 23 above)
Comment (aanm) [reply Documentation/cmdref/cilium_service_update.md:22]: @borkmann I've mentioned this in the previous comments, the mention of k8s is on purpose to distinguish from potential future work that involves a type of IP that is external to the cluster. Although the concept itself is generic the functionality is tightly couple to a k8s feature.

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

File: Documentation/cmdref/cilium_service_update.md (hunk 23 above)
Comment (borkmann) [reply Documentation/cmdref/cilium_service_update.md:22]: Ok, is there anything coming up from k8s you're aware of that would have this potential naming clash?

Comment (aanm) [reply Documentation/cmdref/cilium_service_update.md:22]: Discussed offline
