### PR TITLE
cilium-cli: Fix CNI config file collection in sysdump

### LINKED ISSUE #41833: CLI reports "failed to copy CNI config file" when pulling sysdump
Example failure in CI: https://github.com/cilium/cilium/actions/runs/17863574255/job/50800531398#step:28:498

```
🔍 Collecting sysdump with cilium-cli version: 9ba2179b, args: [connectivity test --include-unsafe-tests --conn-disrupt-test-restarts-path ./cilium-conn-disrupt-restarts --conn-disrupt-test-xfrm-errors-path ./cilium-conn-disrupt-xfrm-errors --flush-ct --sysdump-hubble-flows-count=1000000 --sysdump-hubble-flows-timeout=5m --sysdump-output-filename cilium-sysdump-conn-disrupt-test-cilium-upgrade-ipsec-2-concurrent-<ts> --junit-file cilium-junits/conn-disrupt-test-cilium-upgrade-ipsec-2-concurrent.xml --collect-sysdump-on-failure --log-code-owners --code-owners=CODEOWNERS --exclude-code-owners=@cilium/github-sec --external-target=bing.com. --external-cidr=8.0.0.0/8 --external-ip=8.8.4.4 --external-other-ip=8.8.8.8 --hubble=true --flow-validation=disabled --external-target=fake.external.service.cilium --external-other-target=fake.external.service.other.cilium --external-cidr=172.20.1.0/24 --external-cidrv6=fc00:c111::ffff:0/112 --external-ip=172.20.1.100 --external-ipv6=fc00:c111::ffff:ec --external-other-ip=172.20.1.101 --external-other-ipv6=fc00:c111::ffff:ee --external-target-ca-namespace=external-target-secrets --external-target-ca-name=custom-ca --external-target-ipv6-capable --junit-property github_job_step=Run conn disrupt tests (cilium-upgrade-ipsec-2-concurrent) --test !seq-.* --test-concurrency=5 --expected-xfrm-errors +inbound_no_state]
🔮 Detected Cilium installation in namespace: "kube-system"
🔮 Detected Cilium operator in namespace: "kube-system"
ℹ️ Using default Cilium Helm release name: "cilium"
ℹ️ Using default Tetragon Helm release name: "tetragon"
ℹ️ Failed to detect Cilium SPIRE installation - using Cilium namespace as Cilium SPIRE namespace: "kube-system"
🔍 Collecting Kubernetes nodes
🔮 Detected Cilium features: map[bpf-lb-external-clusterip:Disabled cidr-match-nodes:Disabled clustermesh-enable-endpoint-sync:Disabled cni-chaining:Disabled:none enable-bgp-control-plane:Disabled enable-egress-gateway:Disabled enable-encryption-strict-mode:Disabled enable-envoy-config:Disabled enable-gateway-api:Disabled enable-ipsec:Enabled enable-local-redirect-policy:Disabled enable-policy-secrets-sync:Enabled endpoint-routes:Disabled ingress-controller:Disabled ipam:Disabled:kubernetes ipv4:Enabled ipv6:Enabled loadbalancer-l7:Disabled multicast-enabled:Disabled mutual-auth-spiffe:Disabled policy-default-local-cluster:Enabled policy-secrets-only-from-secrets-namespace:Enabled tunnel:Disabled:vxlan tunnel-port:Disabled:8472 wireguard-encapsulate:Disabled]
🔍 Collecting profiling data from Cilium pods
🔍 Collecting profiling data from Cilium pods
⚠️ The following tasks failed, the sysdump may be incomplete:
```
...
```
⚠️ cniconflist-cilium-4qbq7: failed to copy CNI config file "" from directory "/etc/cni/net.d/": command failed (pod=kube-system/cilium-4qbq7, container=cilium-agent): command terminated with exit code 1: "/usr/bin/cat: /etc/cni/net.d: Is a directory\n"
⚠️ cniconflist-cilium-bfrtr: failed to copy CNI config file "" from directory "/etc/cni/net.d/": command failed (pod=kube-system/cilium-bfrtr, container=cilium-agent): command terminated with exit code 1: "/usr/bin/cat: /etc/cni/net.d: Is a directory\n"
⚠️ cniconflist-cilium-ldkhf: failed to copy CNI config file "" from directory "/etc/cni/net.d/": command failed (pod=kube-system/cilium-ldkhf, container=cilium-agent): command terminated with exit code 1: "/usr/bin/cat: /etc/cni/net.d: Is a directory\n"
```

Something seems to be wrong with the file listing for determining which CNI configuration files to pull, as it's generating empty strings for the filepath which subsequently results in the commands failing.

### PR DESCRIPTION
**Pull request by pillai-ashwin**
The `SubmitCniConflistSubtask` function was failing when listing CNI config files because strings.SplitSeq can yield empty strings from trailing newlines in the 'ls' command output. When an empty filename is passed to path.Join with the directory path, it returns just the directory path, and attempting to 'cat' a directory results in an error:

  failed to copy CNI config file "" from directory "/etc/cni/net.d/":
  command terminated with exit code 1: "/usr/bin/cat: /etc/cni/net.d: Is a directory"

This fix adds a check to skip empty filenames before attempting to copy CNI config files, preventing the error while still collecting all valid CNI configuration files.

Fixes: #41833

### CODE REVIEW

File: cilium-cli/sysdump/sysdump.go [hunk 1]
```diff
@@ -2575,6 +2575,10 @@ func (c *Collector) SubmitCniConflistSubtask(pods []*corev1.Pod, containerName s
 				return err
 			}
 			for cniFileName := range strings.SplitSeq(strings.TrimSpace(outputStr.String()), "\n") {
```
Comment (tklauser) [inline cilium-cli/sysdump/sysdump.go:2578]: Not directly related to this fix, but if the CNI config directory contains more than one file, with the current `ls` command we wouldn't get one file per line, so the above split wouldn't work:

```
$ kubectl -n kube-system exec -it cilium-hxg7n -- /usr/bin/ls /etc/cni/net.d
05-cilium.conflist  06-foo.conflist
```

I think we want to use `ls -1` in `ExecInPod` above in addition:

```
$ kubectl -n kube-system exec -it cilium-hxg7n -- /usr/bin/ls -1 /etc/cni/net.d
05-cilium.conflist
06-foo.conflist
```

Comment (pillai-ashwin) [reply cilium-cli/sysdump/sysdump.go:2578]: Good catch! I've added `ls -1` to ensure one file per line output. Tested with multiple CNI config files and confirmed all files are collected correctly.

**Review by tklauser — APPROVED** [review]
Thanks!
