### PR TITLE
Fix data race during Hubble setup

### LINKED ISSUE #28291: Race condition in (*Daemon).getHubbleStatus()
With the source code from f73e1c535d704989b3ea24eb68487aa23f6ba52b
```
Read at 0x00c00170c288 by goroutine 6803:
  github.com/cilium/cilium/daemon/cmd.(*Daemon).getHubbleStatus()
      /go/src/github.com/cilium/cilium/daemon/cmd/hubble.go:56 +0xa6
  github.com/cilium/cilium/daemon/cmd.(*Daemon).startStatusCollector.func22()
      /go/src/github.com/cilium/cilium/daemon/cmd/status.go:982 +0x3e
  github.com/cilium/cilium/pkg/status.(*Collector).runProbe.func1()
      /go/src/github.com/cilium/cilium/pkg/status/status.go:180 +0x83

Previous write at 0x00c00170c288 by goroutine 6769:
  github.com/cilium/cilium/daemon/cmd.(*Daemon).launchHubble()
      /go/src/github.com/cilium/cilium/daemon/cmd/hubble.go:193 +0x2687
  github.com/cilium/cilium/daemon/cmd.startDaemon.func6()
      /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1907 +0x33

Goroutine 6803 (running) created at:
  github.com/cilium/cilium/pkg/status.(*Collector).runProbe()
      /go/src/github.com/cilium/cilium/pkg/status/status.go:179 +0x44a
  github.com/cilium/cilium/pkg/status.(*Collector).spawnProbe.func1()
      /go/src/github.com/cilium/cilium/pkg/status/status.go:145 +0x11b

Goroutine 6769 (running) created at:
  github.com/cilium/cilium/daemon/cmd.startDaemon()
      /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1907 +0x20ec
  github.com/cilium/cilium/daemon/cmd.newDaemonPromise.func1()
      /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1694 +0x295
  github.com/cilium/cilium/pkg/datapath/loader.(*Loader).replaceOverlayDatapath()
      /go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:480 +0x309
  github.com/cilium/cilium/pkg/datapath/loader.(*Loader).reinitializeOverlay()
      /go/src/github.com/cilium/cilium/pkg/datapath/loader/base.go:230 +0xa5a
  github.com/cilium/cilium/pkg/datapath/loader.(*Loader).Reinitialize()
      /go/src/github.com/cilium/cilium/pkg/datapath/loader/base.go:429 +0x2dd1
  fmt.(*ss).doScanf()
      /usr/local/go/src/fmt/scan.go:1230 +0x3ee
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xdc
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x6c4
  github.com/cilium/cilium/pkg/bpf.iproute2Compat()
      /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:90 +0x5c7
  fmt.(*ss).doScanf()
      /usr/local/go/src/fmt/scan.go:1230 +0x3ee
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xdc
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x6c4
  github.com/cilium/cilium/pkg/bpf.iproute2Compat()
      /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:90 +0x5c7
  fmt.(*ss).doScanf()
      /usr/local/go/src/fmt/scan.go:1230 +0x3ee
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xdc
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x6c4
  github.com/cilium/cilium/pkg/bpf.iproute2Compat()
      /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:90 +0x5c7
  fmt.(*ss).doScanf()
      /usr/local/go/src/fmt/scan.go:1230 +0x3ee
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xdc
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x6c4
  github.com/cilium/cilium/pkg/bpf.iproute2Compat()
      /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:90 +0x5c7
  fmt.(*ss).doScanf()
      /usr/local/go/src/fmt/scan.go:1230 +0x3ee
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xdc
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x6c4
  github.com/cilium/cilium/pkg/bpf.iproute2Compat()
      /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:90 +0x5c7
  fmt.(*ss).doScanf()
      /usr/local/go/src/fmt/scan.go:1230 +0x3ee
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xdc
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x6c4
  github.com/cilium/cilium/pkg/bpf.iproute2Compat()
      /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:90 +0x5c7
  fmt.(*ss).doScanf()
      /usr/local/go/src/fmt/scan.go:1230 +0x3ee
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xdc
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x6c4
  github.com/cilium/cilium/pkg/bpf.iproute2Compat()
      /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:90 +0x5c7
  fmt.(*ss).doScanf()
      /usr/local/go/src/fmt/scan.go:1230 +0x3ee
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xdc
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x6c4
  github.com/cilium/cilium/pkg/bpf.iproute2Compat()
      /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:90 +0x5c7
  fmt.(*ss).doScanf()
      /usr/local/go/src/fmt/scan.go:1230 +0x3ee
  fmt.Fscanf()
      /usr/local/go/src/fmt/scan.go:143 +0xdc
  fmt.Sscanf()
      /usr/local/go/src/fmt/scan.go:114 +0x6c4
  github.com/cilium/cilium/pkg/bpf.iproute2Compat()
      /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:90 +0x5c7
  github.com/cilium/cilium/pkg/bpf.LoadCollectionSpec()
      /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:33 +0x64
  github.com/cilium/cilium/pkg/socketlb.Enable()
      /go/src/github.com/cilium/cilium/pkg/socketlb/socketlb.go:64 +0x1a4
  github.com/cilium/cilium/pkg/datapath/loader.(*Loader).Reinitialize()
      /go/src/github.com/cilium/cilium/pkg/datapath/loader/base.go:391 +0x2569
  github.com/cilium/cilium/daemon/cmd.(*Daemon).init()
      /go/src/github.com/cilium/cilium/daemon/cmd/daemon.go:289 +0x8aa
  github.com/cilium/cilium/daemon/cmd.newDaemon()
      /go/src/github.com/cilium/cilium/daemon/cmd/daemon.go:1153 +0xba89
  github.com/cilium/cilium/daemon/cmd.newDaemonPromise.func1()
      /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1687 +0xa4
  github.com/cilium/cilium/pkg/hive.Hook.Start()
      /go/src/github.com/cilium/cilium/pkg/hive/lifecycle.go:34 +0x70
  github.com/cilium/cilium/pkg/hive.(*Hook).Start()
      <autogenerated>:1 +0x1f
  github.com/cilium/cilium/pkg/hive.(*DefaultLifecycle).Start()
      /go/src/github.com/cilium/cilium/pkg/hive/lifecycle.go:103 +0x3f1
  github.com/cilium/cilium/pkg/hive.(*Hive).Start()
      /go/src/github.com/cilium/cilium/pkg/hive/hive.go:291 +0x152
  github.com/cilium/cilium/pkg/hive.(*Hive).Run()
      /go/src/github.com/cilium/cilium/pkg/hive/hive.go:191 +0xc4
  github.com/cilium/cilium/daemon/cmd.NewAgentCmd.func1()
      /go/src/github.com/cilium/cilium/daemon/cmd/root.go:39 +0x264
  github.com/spf13/cobra.(*Command).execute()
      /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:944 +0xcb8
  github.com/spf13/cobra.(*Command).ExecuteC()
      /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:1068 +0x5c4
  github.com/spf13/cobra.(*Command).Execute()
      /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:992 +0x2e
  github.com/cilium/cilium/daemon/cmd.Execute()
      /go/src/github.com/cilium/cilium/daemon/cmd/root.go:79 +0x2f
  main.main()
      /go/src/github.com/cilium/cilium/daemon/main.go:14 +0xa9
```

From a quick glance the issue is basically that we are reading this variable:
https://github.com/cilium/cilium/blob/8ef62c7a30a243ade2ab9c1b0761c58aadf03dea/daemon/cmd/hubble.go#L56-L61

and writing it here:
https://github.com/cilium/cilium/blob/8ef62c7a30a243ade2ab9c1b0761c58aadf03dea/daemon/cmd/hubble.go#L193-L202

We need to protect the variable with a mutex or some other method.

### PR DESCRIPTION
**Pull request by glrf**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.

This commit fixes a data race where the hubbleObserver is being initialized in a new goroutine while the StatusCollector already tries to check Hubble's status.

We fix the data race by switching to an atomic pointer to access the `hubbleObserver` in the Daemon struct.

Fixing the data race by simply waiting to start the status collector until hubble is initialized does not work, as `launchHubble` could take up to 30s to return while waiting for a TLS certificate and we don't want to block agent startup for this.

Fixes: #28291

### CODE REVIEW

File: daemon/cmd/hubble.go [hunk 1]
```diff
@@ -322,6 +323,8 @@ func (d *Daemon) launchHubble() {
 			}
 		}()
 	}
+
+	d.hubbleObserver.Store(hubbleObserver)
```
Comment (giorio94) [inline daemon/cmd/hubble.go:327]: One functional difference here is that now we are setting the observer only if all the previous operations succeeded, while it was always configured in the previous implementation. I'd defer the final call on whether this is acceptable to Alexandre though, as I don't know the details of the hubble initialization logic.

**Review by giorio94 — APPROVED** [review]
Overall looks good to me. Just one comment inline about a behavioral difference introduced in the refactoring.

File: daemon/cmd/hubble.go (hunk 1 above)
Comment (glrf) [reply daemon/cmd/hubble.go:327]: Good point, thanks. I suspect that doesn't really make a difference in practice. But let's see what alex thinks about it

Comment (kaworu) [reply daemon/cmd/hubble.go:327]: From the commit message:

> Fixing the data race by simply waiting to start the status collector until hubble is initialized does not work, as launchHubble could take up to 30s to return while waiting for a TLS certificate and we don't want to block agent startup for this.

Actually `lauchHubble` can block indefinitely waiting on the TLS cert, the 30s timeout is only used to log the "Waiting on TLS cert" message. See

https://github.com/cilium/cilium/blob/39dce8574d453b6957a85923ec768ded07b4ff42/daemon/cmd/hubble.go#L285-L294

While we wait on the TLS cert, Hubble is in a "half initialized state" where metrics and the local UNIX domain socket Hubble server are fully initialized, but the TCP server isn't.

At that point, before this patch we would report `models.StatusStateOk` (because `d.hubbleObserver` is set before waiting on the TLS cert) and after this patch we report `models.HubbleStatusStateWarning` "Server not initialized".

Personally speaking, "Server not initialized" make sense when Hubble is configured to listen on TCP but doesn't yet, so this change LGTM. cc @rolinh @gandro thoughts?

Comment (rolinh) [reply daemon/cmd/hubble.go:327]: > At that point, before this patch we would report models.StatusStateOk (because d.hubbleObserver is set before waiting on the TLS cert) and after this patch we report models.HubbleStatusStateWarning "Server not initialized".
>
> Personally speaking, "Server not initialized" make sense when Hubble is configured to listen on TCP but doesn't yet, so this change LGTM.

That's a good point. I think the change is actually for the better.

**Review by kaworu — APPROVED** [review]

**Review by gandro — APPROVED** [review]

**Review by rolinh — APPROVED** [review]
