### PR TITLE
datapath: Pull skb data in to-netdev path

### LINKED ISSUE #11802: Unable to ping node
## Bug report

**General Information**

- Cilium version: `Daemon: 1.7.4 c7ee6d62b 2020-05-15T16:07:35+02:00 go version go1.13.10 linux/amd64`
- Kernel version `5.4.0-33-generic #37-Ubuntu SMP`
- Orchestration system version in use: Kubernetes 1.18.3

**How to reproduce the issue**

1. Install cilium in Kubeproxy-free deployment following [this guide](https://docs.cilium.io/en/stable/gettingstarted/kubeproxy-free)
2. Try to ping kubernetes nodes, ping fails

If I set `kube-proxy-replacement: disabled` in the cilium-config then the nodes ping again, but pod to pod traffic is dropped since cube-proxy isn't running in the cluster. 

[Slack thread](https://cilium.slack.com/archives/C1MATJ5U5/p1591027432067800) with initial troubleshooting

Attached is a pcap during ping attempts
[ping.pcap.zip](https://github.com/cilium/cilium/files/4713291/ping.pcap.zip)

### LINKED ISSUE #12854: Cilium is droping ICMP packets (Invalid packet)
## Bug report

When I deploy cilium, ICMP is stoping working on any cluster node, If I running `cilium monitor -t drop` I see that it is dropping EchoReply packets:

```
xx drop (Invalid packet) flow 0x318a7847 to endpoint 0, identity 4294967162->0: 10.28.0.1 -> 10.28.36.174 EchoReply
```

I've tried to deploy with default settings from quick start guide and with `kubeProxyReplacement=strict`.

ICMP is working fine only if I setting `global.kubeProxyReplacement=disabled` option.

**General Information**

- Cilium version (run `cilium version`):
  ```
  Client: 1.8.2 aa42034f0 2020-07-23T15:02:39-07:00 go version go1.14.6 linux/amd64
  Daemon: 1.8.2 aa42034f0 2020-07-23T15:02:39-07:00 go version go1.14.6 linux/amd64
  ```
- Kernel version (run `uname -a`)
  ```
  Linux m1c31 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
  ```
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...):
  ```
  Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Link to relevant artifacts (policies, deployments scripts, ...)
  - Discussion on slack https://cilium.slack.com/archives/C1MATJ5U5/p1597152404202800
  - Packets dump: [1.zip](https://github.com/cilium/cilium/files/5062239/1.zip)
- Generate and upload a system zip:
  - [cilium-sysdump-latest.zip](https://github.com/cilium/cilium/files/5062223/cilium-sysdump-latest.zip)

**How to reproduce the issue**

1. I'm trying cilium on pxe bootable server farm ([`kubefarm` ](https://github.com/kvaps/kubefarm)) the image is [based](https://github.com/kvaps/kubefarm/blob/master/build/ltsp/Dockerfile) on Ubuntu 20.04 and its standard kernel.
1. install cilium:
    ```
    helm upgrade cilium cilium/cilium --version 1.8.2 \
      --namespace kube-system \
      --set global.kubeProxyReplacement=strict \
      --set global.k8sServiceHost=cluster1-kubernetes-apiserver --set global.k8sServicePort=6443 
    ```
1. go to any node and try to ping anything

I also tried to collect some debug with `--debug-verbose=datapath` and `cilium monitor -v`:

<details>
<summary>debug log</summary>
<pre>
CPU 07: MARK 0xde444e0f FROM 2373 DEBUG: Successfully mapped addr=10.28.36.20 to identity=0
CPU 07: MARK 0xde444e0f FROM 2373 DEBUG: Successfully mapped addr=10.28.36.20 to identity=0
CPU 04: MARK 0xd829242c FROM 2373 DEBUG: Successfully mapped addr=10.28.20.107 to identity=0
CPU 04: MARK 0xd829242c FROM 2373 DEBUG: Successfully mapped addr=10.28.20.107 to identity=0
CPU 07: MARK 0xde444e0f FROM 2373 DEBUG: Successfully mapped addr=10.28.36.20 to identity=0
CPU 07: MARK 0xde444e0f FROM 2373 DEBUG: Successfully mapped addr=10.28.36.20 to identity=0
CPU 04: MARK 0xd829242c FROM 2373 DEBUG: Successfully mapped addr=10.28.20.107 to identity=0
CPU 04: MARK 0xd829242c FROM 2373 DEBUG: Successfully mapped addr=10.28.20.107 to identity=0
CPU 07: MARK 0xde444e0f FROM 2373 DEBUG: Successfully mapped addr=10.28.36.20 to identity=0
CPU 07: MARK 0xde444e0f FROM 2373 DEBUG: Successfully mapped addr=10.28.36.20 to identity=0
CPU 04: MARK 0xd829242c FROM 2373 DEBUG: Successfully mapped addr=10.28.20.107 to identity=0
CPU 04: MARK 0xd829242c FROM 2373 DEBUG: Successfully mapped addr=10.28.20.107 to identity=0
CPU 07: MARK 0xde444e0f FROM 2373 DEBUG: Successfully mapped addr=10.28.36.20 to identity=0
CPU 07: MARK 0xde444e0f FROM 2373 DEBUG: Successfully mapped addr=10.28.36.20 to identity=0
CPU 04: MARK 0xd829242c FROM 2373 DEBUG: Successfully mapped addr=10.28.20.107 to identity=0
CPU 04: MARK 0xd829242c FROM 2373 DEBUG: Successfully mapped addr=10.28.20.107 to identity=0
CPU 07: MARK 0xde444e0f FROM 2373 DEBUG: Successfully mapped addr=10.28.36.20 to identity=0
CPU 07: MARK 0xde444e0f FROM 2373 DEBUG: Successfully mapped addr=10.28.36.20 to identity=0
CPU 04: MARK 0xd829242c FROM 2373 DEBUG: Successfully mapped addr=10.28.20.107 to identity=0
CPU 02: MARK 0x6592b0b7 FROM 1489 DEBUG: Conntrack lookup 1/2: src=10.0.0.115:4240 dst=10.0.4.32:44320
CPU 02: MARK 0x6592b0b7 FROM 1489 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=1
CPU 02: MARK 0x6592b0b7 FROM 1489 DEBUG: CT entry found lifetime=22460, revnat=0
CPU 02: MARK 0x6592b0b7 FROM 1489 DEBUG: CT verdict: Reply, revnat=0
CPU 02: MARK 0x6592b0b7 FROM 1489 DEBUG: Successfully mapped addr=10.0.4.32 to identity=6
CPU 02: MARK 0x6592b0b7 FROM 1489 DEBUG: Encapsulating to node 169616560 (0xa1c24b0) from seclabel 4
-> overlay flow 0x6592b0b7 identity 4->0 state new ifindex cilium_vxlan orig-ip 0.0.0.0: 10.0.0.115:4240 -> 10.0.4.32:44320 tcp ACK
CPU 02: MARK 0x6592b0b7 FROM 2373 DEBUG: Conntrack lookup 1/2: src=10.28.36.174:56273 dst=10.28.36.176:8472
CPU 02: MARK 0x6592b0b7 FROM 2373 DEBUG: Conntrack lookup 2/2: nexthdr=17 flags=1
CPU 02: MARK 0x6592b0b7 FROM 2373 DEBUG: CT entry found lifetime=920, revnat=0
CPU 02: MARK 0x6592b0b7 FROM 2373 DEBUG: CT verdict: Established, revnat=0
CPU 02: MARK 0xc24a7312 FROM 2373 DEBUG: Successfully mapped addr=10.28.36.176 to identity=0
CPU 05: MARK 0x6c1c79d FROM 2373 DEBUG: Successfully mapped addr=10.28.36.176 to identity=0
CPU 05: MARK 0x6c1c79d FROM 0 DEBUG: Tunnel decap: id=6 flowlabel=0
CPU 05: MARK 0x6c1c79d FROM 0 DEBUG: Attempting local delivery for container id 1489 from seclabel 6
CPU 05: MARK 0x6c1c79d FROM 1489 DEBUG: Conntrack lookup 1/2: src=10.0.4.32:44320 dst=10.0.0.115:4240
CPU 05: MARK 0x6c1c79d FROM 1489 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 05: MARK 0x6c1c79d FROM 1489 DEBUG: CT entry found lifetime=22475, revnat=0
CPU 05: MARK 0x6c1c79d FROM 1489 DEBUG: CT verdict: Established, revnat=0
-> endpoint 1489 flow 0x6c1c79d identity 6->4 state established ifindex lxc_health orig-ip 10.0.4.32: 10.0.4.32:44320 -> 10.0.0.115:4240 tcp ACK
CPU 04: MARK 0xd829242c FROM 2373 DEBUG: Successfully mapped addr=10.28.20.107 to identity=0
CPU 04: MARK 0xd829242c FROM 2373 DEBUG: Successfully mapped addr=10.28.20.107 to identity=0
CPU 07: MARK 0xde444e0f FROM 2373 DEBUG: Successfully mapped addr=10.28.36.20 to identity=0
CPU 07: MARK 0xde444e0f FROM 2373 DEBUG: Successfully mapped addr=10.28.36.20 to identity=0
CPU 04: MARK 0xd829242c FROM 2373 DEBUG: Successfully mapped addr=10.28.20.107 to identity=0
CPU 07: MARK 0xde444e0f FROM 2373 DEBUG: Successfully mapped addr=10.28.36.20 to identity=0
CPU 04: MARK 0xd829242c FROM 2373 DEBUG: Successfully mapped addr=10.28.20.107 to identity=0
CPU 04: MARK 0xd829242c FROM 2373 DEBUG: Successfully mapped addr=10.28.20.107 to identity=0
CPU 07: MARK 0xde444e0f FROM 2373 DEBUG: Successfully mapped addr=10.28.36.20 to identity=0
CPU 07: MARK 0xde444e0f FROM 2373 DEBUG: Successfully mapped addr=10.28.36.20 to identity=0
CPU 07: MARK 0xde444e0f FROM 2373 DEBUG: Successfully mapped addr=10.28.36.20 to identity=0
CPU 04: MARK 0xd829242c FROM 2373 DEBUG: Successfully mapped addr=10.28.20.107 to identity=0
CPU 04: MARK 0xd829242c FROM 2373 DEBUG: Successfully mapped addr=10.28.20.107 to identity=0
xx drop (Invalid packet) flow 0xd2e687fb to endpoint 0, identity 4294967162->0: 10.28.0.1 -> 10.28.36.174 EchoReply
CPU 03: MARK 0x55e677e4 FROM 2373 DEBUG: Conntrack lookup 1/2: src=10.28.36.174:40554 dst=10.28.36.70:6443
CPU 03: MARK 0x55e677e4 FROM 2373 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=1
CPU 03: MARK 0x55e677e4 FROM 2373 DEBUG: CT entry found lifetime=22471, revnat=0
CPU 03: MARK 0x55e677e4 FROM 2373 DEBUG: CT verdict: Established, revnat=0
CPU 03: MARK 0x55e677e4 FROM 2373 DEBUG: Conntrack lookup 1/2: src=10.28.36.174:40554 dst=10.28.36.70:6443
CPU 03: MARK 0x55e677e4 FROM 2373 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=1
CPU 03: MARK 0x55e677e4 FROM 2373 DEBUG: CT entry found lifetime=22477, revnat=0
CPU 03: MARK 0x55e677e4 FROM 2373 DEBUG: CT verdict: Established, revnat=0
CPU 03: MARK 0x55e677e4 FROM 2373 DEBUG: Conntrack lookup 1/2: src=10.28.36.174:40554 dst=10.28.36.70:6443
CPU 03: MARK 0x55e677e4 FROM 2373 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=1
CPU 03: MARK 0x55e677e4 FROM 2373 DEBUG: CT entry found lifetime=22477, revnat=0
CPU 03: MARK 0x55e677e4 FROM 2373 DEBUG: CT verdict: Established, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Successfully mapped addr=10.28.36.70 to identity=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 1/2: src=10.28.36.70:6443 dst=10.28.36.174:40554
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT entry found lifetime=22477, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT verdict: Reply, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 1/2: src=10.28.36.70:6443 dst=10.28.36.174:40554
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT entry found lifetime=22477, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT verdict: Reply, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Successfully mapped addr=10.28.36.70 to identity=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 1/2: src=10.28.36.70:6443 dst=10.28.36.174:40554
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT entry found lifetime=22477, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT verdict: Reply, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 1/2: src=10.28.36.70:6443 dst=10.28.36.174:40554
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT entry found lifetime=22477, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT verdict: Reply, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Successfully mapped addr=10.28.36.70 to identity=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 1/2: src=10.28.36.70:6443 dst=10.28.36.174:40554
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT entry found lifetime=22477, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT verdict: Reply, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 1/2: src=10.28.36.70:6443 dst=10.28.36.174:40554
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT entry found lifetime=22477, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT verdict: Reply, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Successfully mapped addr=10.28.36.70 to identity=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 1/2: src=10.28.36.70:6443 dst=10.28.36.174:40554
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT entry found lifetime=22477, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT verdict: Reply, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 1/2: src=10.28.36.70:6443 dst=10.28.36.174:40554
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT entry found lifetime=22477, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT verdict: Reply, revnat=0
CPU 06: MARK 0x55e677e4 FROM 2373 DEBUG: Conntrack lookup 1/2: src=10.28.36.174:40554 dst=10.28.36.70:6443
CPU 06: MARK 0x55e677e4 FROM 2373 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=1
CPU 06: MARK 0x55e677e4 FROM 2373 DEBUG: CT entry found lifetime=22477, revnat=0
CPU 06: MARK 0x55e677e4 FROM 2373 DEBUG: CT verdict: Established, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Successfully mapped addr=10.28.36.70 to identity=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 1/2: src=10.28.36.70:6443 dst=10.28.36.174:40554
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT entry found lifetime=22477, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT verdict: Reply, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 1/2: src=10.28.36.70:6443 dst=10.28.36.174:40554
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT entry found lifetime=22477, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT verdict: Reply, revnat=0
CPU 06: MARK 0x55e677e4 FROM 2373 DEBUG: Conntrack lookup 1/2: src=10.28.36.174:40554 dst=10.28.36.70:6443
CPU 06: MARK 0x55e677e4 FROM 2373 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=1
CPU 06: MARK 0x55e677e4 FROM 2373 DEBUG: CT entry found lifetime=22477, revnat=0
CPU 06: MARK 0x55e677e4 FROM 2373 DEBUG: CT verdict: Established, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Successfully mapped addr=10.28.36.70 to identity=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 1/2: src=10.28.36.70:6443 dst=10.28.36.174:40554
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT entry found lifetime=22477, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT verdict: Reply, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 1/2: src=10.28.36.70:6443 dst=10.28.36.174:40554
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT entry found lifetime=22477, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT verdict: Reply, revnat=0
CPU 06: MARK 0x55e677e4 FROM 2373 DEBUG: Conntrack lookup 1/2: src=10.28.36.174:40554 dst=10.28.36.70:6443
CPU 06: MARK 0x55e677e4 FROM 2373 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=1
CPU 06: MARK 0x55e677e4 FROM 2373 DEBUG: CT entry found lifetime=22477, revnat=0
CPU 06: MARK 0x55e677e4 FROM 2373 DEBUG: CT verdict: Established, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Successfully mapped addr=10.28.36.70 to identity=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 1/2: src=10.28.36.70:6443 dst=10.28.36.174:40554
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT entry found lifetime=22477, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT verdict: Reply, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 1/2: src=10.28.36.70:6443 dst=10.28.36.174:40554
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT entry found lifetime=22477, revnat=0
CPU 06: MARK 0x59425406 FROM 2373 DEBUG: CT verdict: Reply, revnat=0
CPU 06: MARK 0x55e677e4 FROM 2373 DEBUG: Conntrack lookup 1/2: src=10.28.36.174:40554 dst=10.28.36.70:6443
CPU 06: MARK 0x55e677e4 FROM 2373 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=1
CPU 06: MARK 0x55e677e4 FROM 2373 DEBUG: CT entry found lifetime=22477, revnat=0
CPU 06: MARK 0x55e677e4 FROM 2373 DEBUG: CT verdict: Established, revnat=0
CPU 07: MARK 0xde444e0f FROM 2373 DEBUG: Successfully mapped addr=10.28.36.20 to identity=0
CPU 07: MARK 0xde444e0f FROM 2373 DEBUG: Successfully mapped addr=10.28.36.20 to identity=0
CPU 04: MARK 0xd829242c FROM 2373 DEBUG: Successfully mapped addr=10.28.20.107 to identity=0
CPU 04: MARK 0xd829242c FROM 2373 DEBUG: Successfully mapped addr=10.28.20.107 to identity=0
xx drop (Invalid packet) flow 0xd2e687fb to endpoint 0, identity 4294967162->0: 10.28.0.1 -> 10.28.36.174 EchoReply
CPU 07: MARK 0xde444e0f FROM 2373 DEBUG: Successfully mapped addr=10.28.36.20 to identity=0
CPU 07: MARK 0xde444e0f FROM 2373 DEBUG: Successfully mapped addr=10.28.36.20 to identity=0
CPU 04: MARK 0xd829242c FROM 2373 DEBUG: Successfully mapped addr=10.28.20.107 to identity=0
CPU 04: MARK 0xd829242c FROM 2373 DEBUG: Successfully mapped addr=10.28.20.107 to identity=0
CPU 01: MARK 0x17ece03b FROM 2373 DEBUG: Inheriting identity=1 from stack
CPU 01: MARK 0x17ece03b FROM 2373 DEBUG: Successfully mapped addr=10.0.0.207 to identity=1
CPU 01: MARK 0x17ece03b FROM 2373 DEBUG: Attempting local delivery for container id 2470 from seclabel 1
CPU 01: MARK 0x17ece03b FROM 2470 DEBUG: Conntrack lookup 1/2: src=10.0.0.207:49708 dst=10.0.0.58:8181
CPU 01: MARK 0x17ece03b FROM 2470 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 01: MARK 0x17ece03b FROM 2470 DEBUG: CT verdict: New, revnat=0
CPU 01: MARK 0x17ece03b FROM 2470 DEBUG: Conntrack create: proxy-port=0 revnat=0 src-identity=1 lb=0.0.0.0
-> endpoint 2470 flow 0x17ece03b identity 1->5843 state new ifindex lxcb20428011962 orig-ip 10.0.0.207: 10.0.0.207:49708 -> 10.0.0.58:8181 tcp SYN
CPU 01: MARK 0x8179cafa FROM 2470 DEBUG: Conntrack lookup 1/2: src=10.0.0.58:8181 dst=10.0.0.207:49708
CPU 01: MARK 0x8179cafa FROM 2470 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=1
CPU 01: MARK 0x8179cafa FROM 2470 DEBUG: CT entry found lifetime=939, revnat=0
CPU 01: MARK 0x8179cafa FROM 2470 DEBUG: CT verdict: Reply, revnat=0
CPU 01: MARK 0x8179cafa FROM 2470 DEBUG: Successfully mapped addr=10.0.0.207 to identity=1
-> stack flow 0x8179cafa identity 5843->1 state reply ifindex 0 orig-ip 0.0.0.0: 10.0.0.58:8181 -> 10.0.0.207:49708 tcp SYN, ACK
-> 0: 10.0.0.58:8181 -> 10.0.0.207:49708 tcp SYN, ACK
CPU 01: MARK 0x17ece03b FROM 2373 DEBUG: Inheriting identity=1 from stack
CPU 01: MARK 0x17ece03b FROM 2373 DEBUG: Successfully mapped addr=10.0.0.207 to identity=1
CPU 01: MARK 0x17ece03b FROM 2373 DEBUG: Attempting local delivery for container id 2470 from seclabel 1
CPU 01: MARK 0x17ece03b FROM 2470 DEBUG: Conntrack lookup 1/2: src=10.0.0.207:49708 dst=10.0.0.58:8181
CPU 01: MARK 0x17ece03b FROM 2470 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 01: MARK 0x17ece03b FROM 2470 DEBUG: CT entry found lifetime=939, revnat=0
CPU 01: MARK 0x17ece03b FROM 2470 DEBUG: CT verdict: Established, revnat=0
-> endpoint 2470 flow 0x17ece03b identity 1->5843 state established ifindex lxcb20428011962 orig-ip 10.0.0.207: 10.0.0.207:49708 -> 10.0.0.58:8181 tcp ACK
CPU 01: MARK 0x17ece03b FROM 2373 DEBUG: Inheriting identity=1 from stack
CPU 01: MARK 0x17ece03b FROM 2373 DEBUG: Successfully mapped addr=10.0.0.207 to identity=1
CPU 01: MARK 0x17ece03b FROM 2373 DEBUG: Attempting local delivery for container id 2470 from seclabel 1
CPU 01: MARK 0x17ece03b FROM 2470 DEBUG: Conntrack lookup 1/2: src=10.0.0.207:49708 dst=10.0.0.58:8181
CPU 01: MARK 0x17ece03b FROM 2470 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 01: MARK 0x17ece03b FROM 2470 DEBUG: CT entry found lifetime=22479, revnat=0
CPU 01: MARK 0x17ece03b FROM 2470 DEBUG: CT verdict: Established, revnat=0
-> endpoint 2470 flow 0x17ece03b identity 1->5843 state established ifindex lxcb20428011962 orig-ip 10.0.0.207: 10.0.0.207:49708 -> 10.0.0.58:8181 tcp ACK
CPU 01: MARK 0x8179cafa FROM 2470 DEBUG: Conntrack lookup 1/2: src=10.0.0.58:8181 dst=10.0.0.207:49708
CPU 01: MARK 0x8179cafa FROM 2470 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=1
CPU 01: MARK 0x8179cafa FROM 2470 DEBUG: CT entry found lifetime=22479, revnat=0
CPU 01: MARK 0x8179cafa FROM 2470 DEBUG: CT verdict: Reply, revnat=0
CPU 01: MARK 0x8179cafa FROM 2470 DEBUG: Successfully mapped addr=10.0.0.207 to identity=1
-> 0: 10.0.0.58:8181 -> 10.0.0.207:49708 tcp ACK
CPU 04: MARK 0x8179cafa FROM 2470 DEBUG: Conntrack lookup 1/2: src=10.0.0.58:8181 dst=10.0.0.207:49708
CPU 04: MARK 0x8179cafa FROM 2470 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=1
CPU 04: MARK 0x8179cafa FROM 2470 DEBUG: CT entry found lifetime=22479, revnat=0
CPU 04: MARK 0x8179cafa FROM 2470 DEBUG: CT verdict: Reply, revnat=0
CPU 04: MARK 0x8179cafa FROM 2470 DEBUG: Successfully mapped addr=10.0.0.207 to identity=1
-> stack flow 0x8179cafa identity 5843->1 state reply ifindex 0 orig-ip 0.0.0.0: 10.0.0.58:8181 -> 10.0.0.207:49708 tcp ACK
-> 0: 10.0.0.58:8181 -> 10.0.0.207:49708 tcp ACK
CPU 01: MARK 0x17ece03b FROM 2373 DEBUG: Inheriting identity=1 from stack
CPU 01: MARK 0x17ece03b FROM 2373 DEBUG: Successfully mapped addr=10.0.0.207 to identity=1
CPU 01: MARK 0x17ece03b FROM 2373 DEBUG: Attempting local delivery for container id 2470 from seclabel 1
CPU 04: MARK 0x8179cafa FROM 2470 DEBUG: Conntrack lookup 1/2: src=10.0.0.58:8181 dst=10.0.0.207:49708
CPU 04: MARK 0x8179cafa FROM 2470 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=1
CPU 04: MARK 0x8179cafa FROM 2470 DEBUG: CT entry found lifetime=22479, revnat=0
CPU 04: MARK 0x8179cafa FROM 2470 DEBUG: CT verdict: Reply, revnat=0
CPU 04: MARK 0x8179cafa FROM 2470 DEBUG: Successfully mapped addr=10.0.0.207 to identity=1
-> stack flow 0x8179cafa identity 5843->1 state reply ifindex 0 orig-ip 0.0.0.0: 10.0.0.58:8181 -> 10.0.0.207:49708 tcp ACK, FIN
-> 0: 10.0.0.58:8181 -> 10.0.0.207:49708 tcp ACK, FIN
CPU 01: MARK 0x17ece03b FROM 2470 DEBUG: Conntrack lookup 1/2: src=10.0.0.207:49708 dst=10.0.0.58:8181
CPU 01: MARK 0x17ece03b FROM 2470 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 01: MARK 0x17ece03b FROM 2470 DEBUG: CT entry found lifetime=22479, revnat=0
CPU 01: MARK 0x17ece03b FROM 2470 DEBUG: CT verdict: Established, revnat=0
CPU 02: MARK 0x17ece03b FROM 2373 DEBUG: Inheriting identity=1 from stack
CPU 02: MARK 0x17ece03b FROM 2373 DEBUG: Successfully mapped addr=10.0.0.207 to identity=1
CPU 02: MARK 0x17ece03b FROM 2373 DEBUG: Attempting local delivery for container id 2470 from seclabel 1
CPU 02: MARK 0x17ece03b FROM 2470 DEBUG: Conntrack lookup 1/2: src=10.0.0.207:49708 dst=10.0.0.58:8181
CPU 02: MARK 0x17ece03b FROM 2470 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 02: MARK 0x17ece03b FROM 2470 DEBUG: CT entry found lifetime=22479, revnat=0
CPU 02: MARK 0x17ece03b FROM 2470 DEBUG: CT verdict: Established, revnat=0
-> endpoint 2470 flow 0x17ece03b identity 1->5843 state established ifindex lxcb20428011962 orig-ip 10.0.0.207: 10.0.0.207:49708 -> 10.0.0.58:8181 tcp ACK, FIN
CPU 02: MARK 0x8179cafa FROM 2470 DEBUG: Conntrack lookup 1/2: src=10.0.0.58:8181 dst=10.0.0.207:49708
CPU 02: MARK 0x8179cafa FROM 2470 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=1
CPU 02: MARK 0x8179cafa FROM 2470 DEBUG: CT entry found lifetime=889, revnat=0
CPU 02: MARK 0x8179cafa FROM 2470 DEBUG: CT verdict: Reply, revnat=0
CPU 02: MARK 0x8179cafa FROM 2470 DEBUG: Successfully mapped addr=10.0.0.207 to identity=1
-> 0: 10.0.0.58:8181 -> 10.0.0.207:49708 tcp ACK
CPU 07: MARK 0xde444e0f FROM 2373 DEBUG: Successfully mapped addr=10.28.36.20 to identity=0
CPU 07: MARK 0xde444e0f FROM 2373 DEBUG: Successfully mapped addr=10.28.36.20 to identity=0
CPU 04: MARK 0xd829242c FROM 2373 DEBUG: Successfully mapped addr=10.28.20.107 to identity=0
CPU 04: MARK 0xd829242c FROM 2373 DEBUG: Successfully mapped addr=10.28.20.107 to identity=0
</pre>
</details>

### PR DESCRIPTION
**Pull request by brb**
It has been reported \[1\]\[2\] that ICMP packets are being dropped by a
receiving node due to `DROP_INVALID` when bpf_host was attached to the
receiving iface. Further look into the issue revealed that the drops
were happening because IP headers were not in the skb linear data
(unsuccessful `revalidate_data()` caused the `DROP_INVALID` return).

Fix this by making sure that the first invocation of `revalidate_data()`
in the `to-netdev` path will always do `skb_data_pull()` before deciding
that the packet is invalid.

Manually tested by the user who reported \[2\]: https://github.com/cilium/cilium/issues/12854#issuecomment-675569188.

\[1\]: https://github.com/cilium/cilium/issues/11802
\[2\]: https://github.com/cilium/cilium/issues/12854

Fix #11802 
Fix #12854 

Reported-by: Andrei Kvapil (@kvaps)

### CODE REVIEW

File: bpf/lib/common.h [hunk 1]
```diff
@@ -147,6 +147,12 @@ __revalidate_data(struct __ctx_buff *ctx, void **data_, void **data_end_,
 #define revalidate_data_first(ctx, data, data_end, ip)			\
 	__revalidate_data(ctx, data, data_end, (void **)ip, sizeof(**ip), true)
 
+/* revalidate_data_with_pull() does the same as revalidate_data_first(), except
+ * that the skb pulling is controlled with the "pull" parameter.
+ */
+#define revalidate_data_with_pull(ctx, data, data_end, ip, pull)	\
```
Comment (brb) [inline bpf/lib/common.h]: Happy to change the function name with a better one.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
The checkpatch.pl action reported a false positive:
```
CHECK:MACRO_ARG_REUSE: Macro argument reuse 'ip' - possible side-effects?
#69: FILE: bpf/lib/common.h:153:
+#define revalidate_data_with_pull(ctx, data, data_end, ip, pull)	\
+	__revalidate_data(ctx, data, data_end, (void **)ip, sizeof(**ip), pull)
```

File: bpf/lib/common.h (hunk 1 above)
Comment (borkmann) [reply bpf/lib/common.h]: Yeah agree, the `revalidate_data_first()` vs `revalidate_data_with_pull()` is a bit hard to differ based on name.
Maybe rename `revalidate_data_first()` into `revalidate_data_pull()` which internally calls `__revalidate_data_pull(..., true)` such that the two occurences with `!from_host` as param use `__revalidate_data_pull(..., !from_host)`. Other than that lgtm, nice!

**Review by borkmann — APPROVED** [review]

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
retest-kernel-4.19

**Comment by brb** [comment]
retest-4.19
