### PR TITLE
pkg/bpf: Use the other directory when /sys/fs/bpf is not BPFFS

### LINKED ISSUE #3717: Cilium unable to mount BPF fs
Nirmoy reported:
```
level=info msg=" ___|_| |_|_ _ _____"                                                                                                                                                                   
level=info msg="|  _| | | | | |     |"
level=info msg="|___|_|_|_|___|_|_|_|"
level=info msg="Cilium 1.0.0-rc10  go version go1.9.4 linux/amd64"
level=info msg="Envoy version check disabled"
level=info msg="clang (6.0.0) and kernel (4.12.14) versions: OK!"
level=info msg="linking environment: OK!"
level=info msg="bpf_requirements check: OK!"
level=warning msg="BPF root is not a BPF filesystem (0x62656572 != 0xcafe4a11)" file-path=/sys/fs/bpf
level=info msg="Mounted BPF filesystem /sys/fs/bpf"
level=info msg="Waiting for etcd client to be ready"
level=info msg="Valid label prefix configuration:"
level=info msg=" - :io.kubernetes.pod.namespace"
level=info msg=" - :io.cilium.k8s.namespace.labels"
level=info msg=" - !:io.kubernetes"
level=info msg=" - !:.*kubernetes.io"
level=info msg=" - !:pod-template-generation"
level=info msg=" - !:pod-template-hash"
level=info msg=" - !:controller-revision-hash"
level=info msg=" - !:annotation.cilium.io/"
level=info msg=" - !:annotation.cilium-identity"
level=info msg=" - !:annotation.sidecar.istio.io"
level=info msg="Container runtimes being used: \"docker\" on endpoint \"unix:///var/run/docker.sock\""
level=info msg="Waiting for k8s api-server to be ready..." subsys=k8s
[...]
level=info msg="  IPv6 router address: f00d::ac1c:400:0:81d6"
level=error msg="bpf: Unable to update in tunnel endpoint map" error="Unable to get object /sys/fs/bpf/tc/globals/tunnel_endpoint_map: no such file or directory" ipAddr=172.16.xxx.xxx/23
level=error msg="bpf: Unable to update in tunnel endpoint map" error="Unable to get object /sys/fs/bpf/tc/globals/tunnel_endpoint_map: no such file or directory" ipAddr="f00d::ac1c:400:0:0/112"
level=info msg="Loopback IPv4: 172.16.xxx.xxx"
```

Whereas worked on `cilium/stable`.

BPF fs was not mounted by Cilium:
```
caasp-master-0:~ # mount | grep bpf
caasp-master-0:~ # find /sys/fs/bpf/
/sys/fs/bpf/
```
Manually mounting and restarting resolved the issue (kubectl delete -f cilium.yaml then recreate).
```
caasp-master-0:~ # mount | grep bpf
bpf on /sys/fs/bpf type bpf (rw,relatime)
```

On top of: https://github.com/cilium/cilium/commit/42b330c4a14358a7100b70c82e39169ad7bcdd7f

Potentially bug in mountFS() where `mountpoint` could have failed for some reason where daemon instead assumed it was mounted but in reality it wasn't. 0x62656572 is the sysfs superblock magic, so mounting BPF fs should have been fine here.

### PR DESCRIPTION
**Pull request by vadorovsky**
When Cilium is running inside container, it has /sys/fs/bpf
directory mounted from the host. However, if BPPFS is not mounted
on the host, then containerized Cilium should be aware of that and
try to mount BPPFS in the other directory - /run/cilium/bpffs.

Fixes #3717

Signed-off-by: Michal Rostecki <mrostecki@suse.com>

```release-note
Remount /sys/fs/bpf if its filesystem is not BPFFS
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/3786)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by vadorovsky** [comment]
test-me-please

**Comment by vadorovsky** [comment]
test-me-please

**Comment by vadorovsky** [comment]
@tgraf @aanm @joestringer It's ready for review. It works both on Vagrant (as a systemd servise running on host, which uses `/sys/fs/bpf` mount) and on minikube (where `/sys/fs/bpf/` is an empty mount and Cilium fallbacks successfully to `/run/cilium/bpffs` and makes the mount by itself).

Logs from Vagrant:
https://paste.opensuse.org/19728735

Logs from minikube:
https://paste.opensuse.org/60298312

**Comment by vadorovsky** [comment]
test-me-please

**Review by borkmann — COMMENTED** [review]
@mrostecki Did you test that `/run/cilium/bpffs` gets populated by tc? tc has an option to pass the mount point via env, but it also is able to auto-detect a BPF fs mount from /proc/mounts; just making sure the latter works fine in this setting. What happens if you have, say, another BPF fs instance in some different location like /tmp/foo. Are the maps/progs still populated at the right location under /run/cilium/bpffs when /tmp/foo is listed first or last?

**Comment by mrostecki** [comment]
>tc has an option to pass the mount point via env, but it also is able to auto-detect a BPF fs mount from /proc/mounts; just making sure the latter works fine in this setting. What happens if you have, say, another BPF fs instance in some different location like /tmp/foo. Are the maps/progs still populated at the right location under /run/cilium/bpffs when /tmp/foo is listed first or last?

That's a good question, I didn't check that. But I think that any autodetection mechanism which exists outside of `pkg/bpf/bpffs.go` file can be harmful and every map should rely on `mapRoot` variable.

I will try to dig into tc code. But if you already know better how it works, can you point me to the code which autodetects BPFFS mount for tc? Thanks a lot!

**Comment by vadorovsky** [comment]
@borkmann That's a good question, but I think to ensure that everything will be working well, I will just pass the proper `mapRoot` via env variable to tc.

**Comment by vadorovsky** [comment]
@borkmann I added the `BPF_ENV_MNT` variable for `init.sh` and `join_ep.sh` scripts. I skipped the `run_probes.sh` script, because it's executed before BPFFS mount. I also skipped scripts from `test/` directory.

**Comment by vadorovsky** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by vadorovsky** [comment]
test-me-please

**Comment by vadorovsky** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

File: pkg/bpf/bpffs.go [hunk 1]
```diff
@@ -104,100 +118,275 @@ func OpenAfterMount(m *Map) error {
...
+func RemoveAfterMount(name string) {
+	mountMutex.Lock()
+	defer mountMutex.Unlock()
+
+	if mounted {
+		removeMap(name)
+	}
+
+	log.WithField(logfields.BPFMapName, name).Debug("bpffs is not mounted yet; adding to list of maps to remove once it is mounted")
+	delayedRemoves = append(delayedRemoves, name)
```
Comment (aanm) [inline pkg/bpf/bpffs.go]: What's is the `delayedRemoves`?

File: pkg/bpf/bpffs.go [hunk 2]
```diff
@@ -104,100 +118,275 @@ func OpenAfterMount(m *Map) error {
...
-		// Execute the following command to find multiple bpffs mount points
-		// % mount | grep "<mapRoot> " | wc -l | cut -f1 -d' '
-		newmapRoot := mapRoot + " " // Append space to ignore /sys/fs/bpf/xdp and /sys/fs/bpf/ip mountpoints.
-		cmds := []*exec.Cmd{
-			exec.Command("mount"),
-			exec.Command("grep", newmapRoot),
-			exec.Command("wc", "-l"),
-			exec.Command("cut", "-f1", "-d "),
+		if os.IsNotExist(err) {
+			os.MkdirAll(mapRoot, 0644)
```
Comment (aanm) [inline pkg/bpf/bpffs.go]: If `mapRoot` is a directory it should have the execution permission bits set.

File: pkg/bpf/bpffs.go [hunk 3]
```diff
@@ -104,100 +118,275 @@ func OpenAfterMount(m *Map) error {
...
+		} else {
+			return fmt.Errorf("failed to stat the mount path %s: %v", mapRoot, err)
```
Comment (aanm) [inline pkg/bpf/bpffs.go]: `%s: %v", mapRoot, err)` to `%s: %s", mapRoot, err)`

File: pkg/bpf/bpffs.go [hunk 4]
```diff
@@ -104,100 +118,275 @@ func OpenAfterMount(m *Map) error {
...
 		}
+	}
 
-		output, stderr, err := pipeexec.CommandPipe(cmds)
-		if len(stderr) > 0 || err != nil {
-			return fmt.Errorf("command execution failed: %s", stderr)
-		}
+	if !mapRootStat.IsDir() {
+		return fmt.Errorf("%s is a file which is not a directory: %v", mapRoot, err)
```
Comment (aanm) [inline pkg/bpf/bpffs.go]: err is nil at this point you can remove it from the `fmt.Errorf`

File: pkg/bpf/bpffs.go [hunk 5]
```diff
@@ -104,100 +118,275 @@ func OpenAfterMount(m *Map) error {
...
+	}
 
-		// Strip the newline character at the end.
-		parts := strings.Split(string(output), "\n")
+	if err := syscall.Mount(mapRoot, mapRoot, "bpf", 0, ""); err != nil {
+		return fmt.Errorf("failed to mount %s: %v", mapRoot, err)
```
Comment (aanm) [inline pkg/bpf/bpffs.go]: `%s: %v", mapRoot, err)` to `%s: %s", mapRoot, err)`

File: pkg/bpf/bpffs.go [hunk 6]
```diff
@@ -104,100 +118,275 @@ func OpenAfterMount(m *Map) error {
...
+}
+
+func (ms *mountsScanner) Text() string {
+	return ms.scanner.Text()
+}
+
+func newMountsScanner() (*mountsScanner, error) {
+	fMounts, err := os.Open("/proc/mounts")
+	if err != nil {
+		return nil, fmt.Errorf("failed to open /proc/mounts: %v", err)
```
Comment (aanm) [inline pkg/bpf/bpffs.go]: `s: %v", err)` to `s: %s", err)`

File: pkg/bpf/bpffs.go [hunk 7]
```diff
@@ -104,100 +118,275 @@ func OpenAfterMount(m *Map) error {
...
+
+func (ms *mountsScanner) Scan() bool {
+	return ms.scanner.Scan()
+}
+
+func (ms *mountsScanner) Text() string {
+	return ms.scanner.Text()
+}
+
+func newMountsScanner() (*mountsScanner, error) {
```
Comment (aanm) [inline pkg/bpf/bpffs.go]: Can you pass the filename as an argument to this function so you can add a unit test?

```
// search and replace newMountsScanner() with mountScanner()
func mountsScanner() (*mountsScanner, error) {
   return newMountsScanner("/proc/mounts")
}

// unit test this function
func newMountsScanner(path string) (*mountsScanner, error) {
....
}
```

File: pkg/bpf/bpffs.go [hunk 8]
```diff
@@ -104,100 +118,275 @@ func OpenAfterMount(m *Map) error {
...
 
-		if num > 1 {
-			return fmt.Errorf("multiple mount points detected at %s", mapRoot)
+	return num > 1, nil
+}
+
+// isBPFFS checks whether the current mapRoot:
+// - has any mount
+// - if yes, it checks whether the filesystem of that mount is BPFFS
+func isBPFFS() (bool, bool, error) {
```
Comment (aanm) [inline pkg/bpf/bpffs.go]: in the function description, write what are the returned values

File: pkg/bpf/bpffs.go [hunk 9]
```diff
@@ -104,100 +118,275 @@ func OpenAfterMount(m *Map) error {
...
+// - /run/cilium/bpffs
+// There is a procedure of determining which directory is going to be used:
+// 1. Checking whether BPFFS filesystem is mounted in /sys/fs/bpf.
+// 2. If there is no mount, then mount BPFFS in /sys/fs/bpf and finish there.
+// 3. If there is a BPFFS mount, finish there.
+// 4. If there is a mount, but with the other filesystem, then it means that most
+//    probably Cilium is running inside container which has mounted /sys/fs/bpf
+//    from host, but host doesn't have proper BPFFS mount, so that mount is just
+//    the empty directory. In that case, mount BPFFS under /run/cilium/bpffs.
+func checkOrMountDefaultLocations() error {
```
Comment (aanm) [inline pkg/bpf/bpffs.go:272]: The function description is not the same as the function's name

File: pkg/bpf/bpffs.go [hunk 10]
```diff
@@ -104,100 +118,275 @@ func OpenAfterMount(m *Map) error {
...
+		// We should mount BPFFS in /run/cilium/bpffs automatically.
+		// This will allow operation of Cilium but will result in unmounting of
+		// the filesystem when the pod is restarted. This in turn will cause resources
+		// such as the connection tracking table of the BPF programs to be released
+		// which will cause all connections into local containers to be dropped.
+		// User is going to be warned about that.
+		log.Warnf("BPF filesystem is going to be mounted automatically in %s. However, it probably "+
+			"means that Cilium is running inside container and BPFFS is not mounted on "+
+			"the host. We recommend to do that: "+
+			"https://cilium.readthedocs.io/en/latest/kubernetes/install/?highlight=bpffs#mounting-the-bpf-fs-optional",
```
Comment (aanm) [inline pkg/bpf/bpffs.go]: This probably needs a short URL similar the one with have for the kvstore error cc @tgraf

File: pkg/bpf/bpffs.go [hunk 11]
```diff
@@ -104,100 +118,275 @@ func OpenAfterMount(m *Map) error {
...
+		if err := checkOrMountDefaultLocations(); err != nil {
+			return err
+		}
+	} else {
+		if err := checkOrMountCustomLocation(bpfRoot); err != nil {
+			return err
+		}
+	}
+
+	multipleMounts, err := hasMultipleMounts()
```
Comment (aanm) [inline pkg/bpf/bpffs.go:328]: If you ware checking if the filepath has multiple mounts **after** mounting, doesn't this means cilium will keep failing afterwards?

**Review by aanm — CHANGES_REQUESTED** [review]

File: pkg/bpf/bpffs.go (hunk 11 above)
Comment (vadorovsky) [reply pkg/bpf/bpffs.go:328]: No. After mounting Cilium should have only one mount (`hasMultipleMounts` returns true if number of mounts is greater than 1).

File: pkg/bpf/bpffs.go (hunk 1 above)
Comment (vadorovsky) [reply pkg/bpf/bpffs.go]: Delayed removes is the list of deprecated BPF maps which are going to be removed after BPFFS is mounted. I made it specially for https://github.com/cilium/cilium/blob/master/pkg/maps/tunnel/tunnel.go#L62-L63

Comment (vadorovsky) [reply pkg/bpf/bpffs.go]: TBH, I'm almost sure that the `os.Remove` call which is currently used in master is ineffective, because when `init` functions are executed when Cilium is started, BPFFS is not mounted yet. So it's de facto an another small bugfix. ;)

File: pkg/bpf/bpffs.go (hunk 9 above)
Comment (vadorovsky) [reply pkg/bpf/bpffs.go:272]: done

File: pkg/bpf/bpffs.go (hunk 10 above)
Comment (vadorovsky) [reply pkg/bpf/bpffs.go]: What kind of short URL do you expect? `git grep "http\:\/\/" pkg/kvstore/` gave me only:

```
pkg/kvstore/allocator/allocator.go://     http://www.apache.org/licenses/LICENSE-2.0
pkg/kvstore/allocator/allocator_test.go://     http://www.apache.org/licenses/LICENSE-2.0
pkg/kvstore/allocator/doc.go://     http://www.apache.org/licenses/LICENSE-2.0
pkg/kvstore/allocator/localkeys.go://     http://www.apache.org/licenses/LICENSE-2.0
pkg/kvstore/allocator/localkeys_test.go://     http://www.apache.org/licenses/LICENSE-2.0
pkg/kvstore/allocator/logfields.go://     http://www.apache.org/licenses/LICENSE-2.0
pkg/kvstore/backend.go://     http://www.apache.org/licenses/LICENSE-2.0
pkg/kvstore/backwards_compat.go://     http://www.apache.org/licenses/LICENSE-2.0
pkg/kvstore/base_test.go://     http://www.apache.org/licenses/LICENSE-2.0
pkg/kvstore/client.go://     http://www.apache.org/licenses/LICENSE-2.0
pkg/kvstore/config.go://     http://www.apache.org/licenses/LICENSE-2.0
pkg/kvstore/consul.go://     http://www.apache.org/licenses/LICENSE-2.0
pkg/kvstore/consul_test.go://     http://www.apache.org/licenses/LICENSE-2.0
pkg/kvstore/doc.go://     http://www.apache.org/licenses/LICENSE-2.0
pkg/kvstore/dummy.go://     http://www.apache.org/licenses/LICENSE-2.0
pkg/kvstore/etcd.go://     http://www.apache.org/licenses/LICENSE-2.0
pkg/kvstore/etcd.go:    etcdDummyAddress = "http://127.0.0.1:4002"
pkg/kvstore/etcd_test.go://     http://www.apache.org/licenses/LICENSE-2.0
pkg/kvstore/etcd_test.go:                       case "http://127.0.0.1:4004":
pkg/kvstore/etcd_test.go:       v, err := getEPVersion(mm, "http://127.0.0.1:4003", time.Second)
pkg/kvstore/etcd_test.go:       v, err = getEPVersion(mm, "http://127.0.0.1:4004", time.Second)
pkg/kvstore/etcd_test.go:       cfg.Endpoints = []string{"http://127.0.0.1:4003", "http://127.0.0.1:4005"}
pkg/kvstore/etcd_test.go:       cfg.Endpoints = []string{"http://127.0.0.1:4003", "http://127.0.0.1:4004", "http://127.0.0.1:4005"}
pkg/kvstore/events.go://     http://www.apache.org/licenses/LICENSE-2.0
pkg/kvstore/keepalive.go://     http://www.apache.org/licenses/LICENSE-2.0
pkg/kvstore/kvstore.go://     http://www.apache.org/licenses/LICENSE-2.0
pkg/kvstore/kvstore_test.go://     http://www.apache.org/licenses/LICENSE-2.0
pkg/kvstore/lock.go://     http://www.apache.org/licenses/LICENSE-2.0
pkg/kvstore/logfields.go://     http://www.apache.org/licenses/LICENSE-2.0
pkg/kvstore/store/doc.go://     http://www.apache.org/licenses/LICENSE-2.0
pkg/kvstore/store/store.go://     http://www.apache.org/licenses/LICENSE-2.0
pkg/kvstore/store/store_test.go://     http://www.apache.org/licenses/LICENSE-2.0
pkg/kvstore/trace.go://     http://www.apache.org/licenses/LICENSE-2.0
pkg/kvstore/watcher_cache.go://     http://www.apache.org/licenses/LICENSE-2.0
```

**Comment by vadorovsky** [comment]
test-me-please

**Comment by mrostecki** [comment]
test-me-please

**Comment by vadorovsky** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cilium/cilium/3786)*
