### PR TITLE
cni: Wait for cilium-agent availability

### LINKED ISSUE #6556: CNI plugin doesn't wait for agent to come up
It's not super serious but it causes unnecessary failures in the pod event log:

```
  Warning  FailedCreatePodSandBox  6m3s                  kubelet, k8s2      Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "ed0135d1743810e0c0f57cc3fd9abf986544185a62cf5543a29cd70b56703ee7" network for pod "etcd-operator-5cf67779fd-gzt59": NetworkPlugin cni failed to set up pod "etcd-operator-5cf67779fd-gzt59_kube-system" network: unable to retrieve configuration from cilium-agent: Get http:///var/run/cilium/cilium.sock/v1/config: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
```

The CNI plugin should upon ADD and DEL wait for the agent to come up for 30 seconds in a loop and then error out.

### PR DESCRIPTION
**Pull request by vadorovsky**
Sometimes Kubernetes schedules pods and executes CNI plugin before
cilium-agent is available. It causes unnecessary failures in pods' event
logs, especially when Cilium was just deployed on the cluster.

Fixes #6556

Signed-off-by: Michal Rostecki <mrostecki@suse.de>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6583)

### CODE REVIEW

**Comment by vadorovsky** [comment]
test-me-please

**Comment by vadorovsky** [comment]
Seems unrelated

```
16:17:59 • Failure [9.848 seconds]
16:17:59 RuntimePolicyValidationTests
16:17:59 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:351
16:17:59   Validates Example Policies [It]
16:17:59   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:383
16:17:59 
16:17:59   Unable to validate policy /home/vagrant/go/src/github.com/cilium/cilium/examples/policies/l7/dns/dns-visibility.json
16:17:59   Expected command: sudo cilium policy validate /home/vagrant/go/src/github.com/cilium/cilium/examples/policies/l7/dns/dns-visibility.json 
16:17:59   To succeed, but it failed:
16:17:59   Exitcode: 1 
16:17:59   Stdout:
16:17:59    	 
16:17:59   Stderr:
16:17:59    	 Error: Validation of policy has failed: Invalid characters in MatchName: "*". Only 0-9, a-z, A-Z and . and - characters are allowed
16:17:59   	 
16:17:59   	 
16:17:59   
16:17:59 
16:17:59   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/runtime/examples.go:103
```

**Comment by vadorovsky** [comment]
test-me-please

**Comment by tgraf** [comment]
Fixed by #6584. You need to rebase.

**Comment by vadorovsky** [comment]
test-me-please

**Comment by vadorovsky** [comment]
test-me-please

File: pkg/client/client.go [hunk 1]
```diff
@@ -76,6 +81,28 @@ func NewDefaultClient() (*Client, error) {
...
+// NewDefaultClientWithTimeout creates a client with default parameters connecting to UNIX
+// domain socket and waits for cilium-agent availability at most 30 seconds.
+func NewDefaultClientWithTimeout() (*Client, error) {
+	timeout := time.After(ciliumAgentTimeout)
+	var c *Client
+	var err error
+	for {
+		select {
+		case <-timeout:
+			return c, err
```
Comment (tgraf) [inline pkg/client/client.go]: Please return a more descriptive error, otherwise we'll online see `context deadline exceeded`. Let's use

> timeout while connecting to cilium agent. Is the cilium agent running?

File: pkg/client/client.go [hunk 2]
```diff
@@ -35,6 +35,11 @@ import (
 	"github.com/go-openapi/strfmt"
 )
 
+var (
+	// ciliumAgentTimeout is a timeout for cilium-agent readiness.
+	ciliumAgentTimeout = 30 * time.Second
```
Comment (tgraf) [inline pkg/client/client.go]: Call this `DefaultConnectTimeout`, make it a const and then use it from the CNI code as an argument to `NewDefaultClientWithTimeout()`

**Review by tgraf — CHANGES_REQUESTED** [review]
Looks great! Some style changes

File: pkg/client/client.go (hunk 1 above)
Comment (mrostecki) [reply pkg/client/client.go]: I agree. Although the `context deadline exceeded` is not the only type of error which might be returned there. Maybe I should include the `timeout while connecting...` message only if `err` is an instance of `DeadlineExceeded` from golang.org/x/net?

Otherwise we may receive errors like:

> Timeout while connecting to cilium agent. Is the cilium agent running? invalid host format

Comment (mrostecki) [reply pkg/client/client.go]: Or even better - we should probably even timeout only when `err` is an instance of `DeadlineExceeded`. Otherwise error should be returned immediately.

Comment (tgraf) [reply pkg/client/client.go]: Good point. Including the original error is fine as well if we provide the additional context that is relates to a connect timeout

File: pkg/client/client.go (hunk 2 above)
Comment (vadorovsky) [reply pkg/client/client.go]: Disregard my comments which you probably got on email - I forgot that with DefaultClient there is no possibility of getting errors due to parsing and every error should be related to connectivity.

**Review by tgraf — APPROVED** [review]

**Comment by vadorovsky** [comment]
test-me-please

**Comment by vadorovsky** [comment]
test-me-please
