### PR TITLE
Full CES Reconciliation in the Operator

### LINKED ISSUE #24581: Cilium Operator doesn't fully reconcile CiliumEndpointSlices on startup
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cluster with Cilium Endpoint Slices enabled with identity based batching.
Label on namespace was changed. It led to change of identities for Cilium Endpoints in this namespace - Cilium Endpoints were updated with new identity.
Operator moved the endpoints from one slice to another.

First operator queued the insert of the cep to the new ces.
Then, delayed, operator queued the removed of the old cep from the old ces.
Operator crashed after inserting, before removing.

The old cep was never removed from the old ces.

In general there is no reconciliation of Cilium Endpoint Slices. If for some reason the state becomes bad it stays that way. In this particular case it should be enough to have full reconciliation during startup. 

### Cilium Version

all

### Kernel Version

all

### Kubernetes Version

all

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by alan-kut**
Implement full CES reconciliation logic in the Cilium Operator.

Refactor and unify CEPs and CESs watchers in the operator.
Refactor CES Controller:
- Limit the functionality of the Manager to maintain mapping between CEPs and CESs.
- Implement reconciliation in the Reconcilar based on the mapping from the Manager and CEPs and CESs from the watchers stores.
- React to the CESs events in addition to the CEPs events.

This PR should fix all the problems related to CESs out of sync.
If there is a broken state (stale, duplicated, missing CESs) the operator should always fully reconcile it on startup and maintain good state.
If different client breaks CES operator would fix it back.

Fixes: #24581

```release-note
Implement full CES reconciliation logic in the operator
```

### CODE REVIEW

**Comment by dlapcevic** [comment]
cc @dlapcevic @aojea

File: operator/pkg/ciliumendpointslice/ceptocesmap.go [hunk 1]
```diff
@@ -8,104 +8,136 @@ import "github.com/cilium/cilium/pkg/lock"
...
+	delete(c.cesNameToCEPNameSet[c.cepNameToCESName[cepName]], cepName)
+	delete(c.cepNameToCESName, cepName)
 }
 
-func (c *CESToCEPMapping) getCESName(cepName string) (string, bool) {
-	c.cesMutex.RLock()
-	defer c.cesMutex.RUnlock()
-	name, ok := c.cepNametoCESName[CEPName(cepName)]
-	return string(name), ok
+// Return CES to which the given CEP is amm
```
Comment (dlapcevic) [inline operator/pkg/ciliumendpointslice/ceptocesmap.go]: typo: CEP is assigned

File: operator/pkg/ciliumendpointslice/ceptocesmap.go [hunk 2]
```diff
@@ -8,104 +8,136 @@ import "github.com/cilium/cilium/pkg/lock"
...
-	var cess []*cesTracker
-	for _, ces := range c.desiredCESs {
-		cess = append(cess, ces)
-	}
-	return cess
+// Remove mapping structure for CES
+func (c *CESToCEPMapping) deleteCES(cesName CESName) {
+	c.mutex.Lock()
+	defer c.mutex.Unlock()
+	delete(c.cesNameToCEPNameSet, cesName)
```
Comment (dlapcevic) [inline operator/pkg/ciliumendpointslice/ceptocesmap.go:113]: Should it also be removed from `c.cesData`?

File: operator/pkg/ciliumendpointslice/manager_test.go [hunk 3]
```diff
@@ -6,241 +6,108 @@ package ciliumendpointslice
...
-
-	// Insert CEPs in Cache and count total number of CES and CEP
-	t.Run("Test Inserting CEPs in cache and count number of CEPs and CESs", func(*testing.T) {
-		m := newCESManagerFcfs(newQueue(), 2)
-		m.InsertCEPInCache(cep1, "kube-system")
-		m.InsertCEPInCache(cep2, "kube-system")
-		m.InsertCEPInCache(cep3, "kube-system")
-		assert.Equal(t, m.getCESCount(), 2, "Total number of CESs allocated is 2")
-		assert.Equal(t, m.getTotalCEPCount(), 3, "Total number of CEPs inserted is 3")
+func TestFCFSManager(t *testing.T) {
```
Comment (dlapcevic) [inline operator/pkg/ciliumendpointslice/manager_test.go:21]: Consider adding a test with different namespaces, to verify that each CES can only take CEPs from a single namespace.
`UpdateCEPMapping(getCEP("c1", 0), "ns-a")`
`UpdateCEPMapping(getCEP("c2", 0), "ns-b")`

Same for `TestIdentityManager()` below.

File: operator/pkg/ciliumendpointslice/endpointslice.go [hunk 4]
```diff
@@ -53,11 +52,14 @@ const (
 	// Default CES Synctime, multiple consecutive syncs with k8s-apiserver are
 	// batched and synced together after a short delay.
 	DefaultCESSyncTime = 500 * time.Millisecond
+	UpdateEvent        = 1
```
Comment (dlapcevic) [inline operator/pkg/ciliumendpointslice/endpointslice.go]: nit: Should it be exported (capital first letter)?
Anyway maybe it's better to make it like this:
```
type EventType int

const (
	AddEvent EventType = iota
	UpdateEvent
	DeleteEvent
)
```

And then update EndpointEvent.event to be EventType.

File: operator/pkg/ciliumendpointslice/endpointslice.go [hunk 5]
```diff
@@ -102,24 +104,47 @@ func GetCEPNameFromCCEP(cep *capi_v2a1.CoreCiliumEndpoint, namespace string) str
...
+		slicingMode:                    slicingMode,
+		workerLoopPeriod:               1 * time.Second,
+		enqueuedAt:                     make(map[string]time.Time),
+		preInitEnqueuedEndpointsEvents: make([]EndpointEvent, 0),
+		endpointsMappingInitialized:    false,
+	}
+
+	cepWatcher.AddOnUpdateHandler(controller.onEndpointUpdate)
+	cepWatcher.AddOnDeleteHandler(controller.onEndpointDelete)
+	cesWatcher.AddOnDeleteHandler(controller.onSliceUpdate)
```
Comment (dlapcevic) [inline operator/pkg/ciliumendpointslice/endpointslice.go]: typo: Should be `AddOnUpdateHandler`

File: operator/pkg/ciliumendpointslice/manager.go [hunk 6]
```diff
@@ -214,396 +99,100 @@ func uniqueCESliceName(desiredCESs *CESToCEPMapping) string {
 //     with an empty name, it generates a random unique name and assign it to the CES.
 //  2. During operator warm boot [after crash or software upgrade], slicing manager
 //     creates a CES, by passing unique name.
-func (c *cesMgr) createCES(name string) *cesTracker {
-	var cesName string = name
+func (c *cesMgr) createCES(name, ns string) CESName {
+	var cesName = name
```
Comment (dlapcevic) [inline operator/pkg/ciliumendpointslice/manager.go]: nit: `cesName := name`

File: operator/pkg/ciliumendpointslice/manager.go [hunk 7]
```diff
@@ -214,396 +99,100 @@ func uniqueCESliceName(desiredCESs *CESToCEPMapping) string {
...
+			logfields.CEPName: cepName,
+			logfields.CESName: cesName,
+		}).Debug("CEP already mapped to CES")
+		return []CESName{cesName}
 	}
 
 	// If given cep object isn't packed in any of the CES. find a new ces
 	// to pack this cep.
-	cb, cesName := func() (*cesTracker, string) {
+	for {
```
Comment (dlapcevic) [inline operator/pkg/ciliumendpointslice/manager.go]: Is the loop needed because `getLargestAvailableCESForNamespace()` can return a `cesName` that can get full before locking the cache, even though the function returns the name of the largest non-full CES?

File: operator/pkg/ciliumendpointslice/manager.go [hunk 8]
```diff
@@ -214,396 +99,100 @@ func uniqueCESliceName(desiredCESs *CESToCEPMapping) string {
...
-		logfields.CEPCount: len(ces.ces.Endpoints),
-	}).Debug("Removed CEP from CES")
-
-	// Increment the cepRemove counter
-	ces.cepRemoved += 1
-	c.insertCESInWorkQueue(ces, baseDelay)
+	return ""
 }
 
 // getLargestAvailableCESForNamespace returns the largest CES from cache for the
```
Comment (dlapcevic) [inline operator/pkg/ciliumendpointslice/manager.go:162]: Update the comment that it returns the name of the largest, and that it doesn't guarantee that the CESs is not full by the time it's read from cache by name.

File: operator/pkg/ciliumendpointslice/manager.go [hunk 9]
```diff
@@ -612,133 +201,109 @@ func (c *cesManagerIdentity) InsertCEPInCache(cep *cilium_v2.CoreCiliumEndpoint,
...
-func (c *cesMgr) getCESQueueDelayInSeconds(cesName string) (diff float64) {
-	ces, exists := c.desiredCESs.getCESTracker(cesName)
-	if !exists {
-		return
+func (c *cesManagerIdentity) removeCESToIdentity(id int64, cesName CESName) {
+	c.identityLock.Lock()
+	cesSlice := c.identityToCES[id]
+	for i, ces := range cesSlice {
+		if ces == cesName {
+			cesSlice[i] = cesSlice[len(cesSlice)-1]
```
Comment (dlapcevic) [inline operator/pkg/ciliumendpointslice/manager.go:277]: I don't understand this. How is cesSlice ever reducing the number of elements?

File: operator/pkg/ciliumendpointslice/reconciler.go [hunk 10]
```diff
@@ -29,71 +35,174 @@ func newReconciler(client clientset.CiliumV2alpha1Interface, cesMgr operations)
...
-	if ces, err = r.cesManager.getCESCopyFromCache(cesToUpdate); err != nil {
-		return
+	// Iterate through existing CEPs in the CES
+	// remove stale ones
+	// update outdated
+	// Iterate through expected CEPs in the CES
+	// insert missing
+	ceps := r.cesManager.getCEPinCES(cesName)
+	desiredEndpoints := make([]cilium_v2a1.CoreCiliumEndpoint, 0, len(ceps))
+	desiredObjects := make(map[CEPName]*cilium_v2a1.CoreCiliumEndpoint)
```
Comment (dlapcevic) [inline operator/pkg/ciliumendpointslice/reconciler.go]: It's a little difficult to follow `desiredEndpoints` and `desiredObjects`.
Consider renaming `desiredEndpoints` to `updatedEndpoints`, and `desiredObjects` to `desiredEndpoints`.

File: operator/watchers/ciliumendpoint/utils.go [hunk 11]
```diff
@@ -0,0 +1,39 @@
...
+		return false
+	}
+	ces, _ := CiliumEndpointStore.IndexKeys(identityIndex, identity)
+
+	return len(ces) != 0
+}
+
+// HasCE returns true or false if the Cilium Endpoint store has the endpoint
+// with the given name.
+func HasCE(ns, name string) (*ciliumApiV2.CiliumEndpoint, bool, error) {
```
Comment (dlapcevic) [inline operator/watchers/ciliumendpoint/utils.go]: The function name and description isn't matching. It should be `GetCE`.

**Comment by pippolo84** [comment]
Thanks for the PR!

Currently, there is an ongoing effort to modularize each component of the operator, in order to improve the readability and the testability of the codebase. To do that we introduced the [Hive](https://docs.cilium.io/en/latest/contributing/development/hive/#id1) package and we started to organize each component into a separate cell.
As an example, that kind of modularization has already been done in the operator for the [CiliumIdentity GC](https://github.com/cilium/cilium/pull/22892).
There is also a [Work-In-Progress PR](https://github.com/cilium/cilium/pull/27037) for the CiliumEndpoint GC.

Would you be willing to follow the same approach for the CES controller? I think that the linked PR for the CiliumEndpoint GC should be a good example to follow, since it shows how to handle events for k8s resources through the `Resource[T]`-based providers. Besides, it is strictly related to the CES controller code.

I'm more than happy to help if you need any kind of clarifications and/or further examples.

**Comment by alan-kut** [comment]
I was occupied by other things but I plan to fix the current issues with the current version soon and then I will upgrade the code to follow the same modularization apprach for the CES controller

**Comment by pippolo84** [comment]
> I was occupied by other things but I plan to fix the current issues with the current version soon and then I will upgrade the code to follow the same modularization apprach for the CES controller

That's great, thanks! :rocket:

File: operator/pkg/ciliumendpointslice/ceptocesmap.go (hunk 1 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/ceptocesmap.go]: Fixed

File: operator/pkg/ciliumendpointslice/ceptocesmap.go (hunk 2 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/ceptocesmap.go:113]: Yes, fixed.

File: operator/pkg/ciliumendpointslice/manager_test.go (hunk 3 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/manager_test.go:21]: Added

File: operator/pkg/ciliumendpointslice/endpointslice.go (hunk 4 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/endpointslice.go]: Done

File: operator/pkg/ciliumendpointslice/endpointslice.go (hunk 5 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/endpointslice.go]: Fixed.

File: operator/pkg/ciliumendpointslice/manager.go (hunk 7 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/manager.go]: Yes, that's the reason

Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/manager.go]: Locked sooner so the loop is not needed here.

File: operator/pkg/ciliumendpointslice/manager.go (hunk 8 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/manager.go:162]: I think it should be clear that if this only returns a name of CES the state may change in the meantime.

File: operator/pkg/ciliumendpointslice/manager.go (hunk 9 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/manager.go:277]: CES is deleted when all the elements inside are deleted.

File: operator/pkg/ciliumendpointslice/reconciler.go (hunk 10 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/reconciler.go]: Simplified a code a little bit. It may reshuffle the CEPs on update now but it's much easier to track

File: operator/watchers/ciliumendpoint/utils.go (hunk 11 above)
Comment (alan-kut) [reply operator/watchers/ciliumendpoint/utils.go]: Done

File: operator/pkg/ciliumendpointslice/manager.go (hunk 9 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/manager.go:277]: Fixed the code:
- removed second mutex (everything is now on one mutex)
- added deleting CES from the local operator cache

**Comment by alan-kut** [comment]
Resolved comments and fixed checks.

Next step: upgrade the code to follow the same modularization apprach for the CES controller

**Review by dlapcevic — APPROVED** [review]
/lgtm

I'll review the changes for "Next step: upgrade the code to follow the same modularization apprach for the CES controller" when it's ready.
Please make it a separate commit.

**Comment by alan-kut** [comment]
@pippolo84 Please take a look. I'm not sure yet that everything is fully correct and passes the tests but at least hive part is done.

**Comment by pippolo84** [comment]
> @pippolo84 Please take a look. I'm not sure yet that everything is fully correct and passes the tests but at least hive part is done.

Thanks for all the modularization work @alan-kut !
Right now I'm on PTO, but I'm happy to review this as soon as I'll be back at the end of August.

File: operator/cmd/root.go [hunk 12]
```diff
@@ -153,6 +153,8 @@ var (
 			// setup operations. This is a hacky workaround until the kvstore is
 			// refactored into a proper cell.
 			identitygc.Cell,
+
+			ciliumendpointslice.Cell,
```
Comment (joamaki) [inline operator/cmd/root.go:174]: Add a short one or two line comment here describing the functionality of this cell. It helps getting an overview of what each top-level cell is doing and how they relate to each other.

File: operator/pkg/ciliumendpointslice/cell.go [hunk 13]
```diff
@@ -0,0 +1,57 @@
...
+	// requests to the kube-apiserver.
+	CESWriteQPSLimit = "ces-write-qps-limit"
+
+	// CESWriteQPSBurst is the burst rate per second used with CESWriteQPSLimit
+	// for the CES work queue to process CES events that result in CES write
+	// (Create, Update, Delete) requests to the kube-apiserver.
+	CESWriteQPSBurst = "ces-write-qps-burst"
+)
+
+var Cell = cell.Module(
```
Comment (joamaki) [inline operator/pkg/ciliumendpointslice/cell.go:34]: Add descriptive comment here describing what this cell does. E.g. think of the `var Cell` definition as something someone new to the codebase would be hovering over in the `root.go` file and trying to piece together what's going on. Having clear description here about what this implements makes the codebase easier to understand and navigate.

(Incidentally have an issue to "document how to document" hive cells :smile:)

File: operator/pkg/ciliumendpointslice/controller.go [hunk 14]
```diff
@@ -0,0 +1,111 @@
...
+
+	Logger    logrus.FieldLogger
+	Lifecycle hive.Lifecycle
+
+	Clientset           k8sClient.Clientset
+	CiliumEndpoint      resource.Resource[*v2.CiliumEndpoint]
+	CiliumEndpointSlice resource.Resource[*v2alpha1.CiliumEndpointSlice]
+
+	Cfg Config
+	//daemonCfg *option.DaemonConfig
```
Comment (joamaki) [inline operator/pkg/ciliumendpointslice/controller.go]: Drop this?

File: operator/pkg/ciliumendpointslice/controller.go [hunk 15]
```diff
@@ -0,0 +1,111 @@
...
+}
+
+// registerController creates and initializes the CES controller
+func registerController(p params) {
+	if !p.Clientset.IsEnabled() && option.Config.EnableCiliumEndpointSlice {
+		return
+	}
+
+	cesController := &Controller{
+		logger:                         p.Logger.WithField(logfields.LogSubsys, "ces-controller"),
```
Comment (joamaki) [inline operator/pkg/ciliumendpointslice/controller.go]: The `p.Logger` already has `LogSubsys` set to `k8s-ces-controller` via `cell.Module`, so no need to set it again.

File: operator/pkg/ciliumendpointslice/controller.go [hunk 16]
```diff
@@ -0,0 +1,111 @@
...
+		writeQPSBurst:                  p.Cfg.CESWriteQPSBurst,
+		workerLoopPeriod:               1 * time.Second,
+		enqueuedAt:                     make(map[CESName]time.Time),
+		preInitEnqueuedEndpointsEvents: make([]EndpointEvent, 0),
+		endpointsMappingInitialized:    false,
+	}
+
+	p.Lifecycle.Append(hive.Hook{
+		OnStart: func(context hive.HookContext) error {
+			return cesController.Start(context)
```
Comment (joamaki) [inline operator/pkg/ciliumendpointslice/controller.go]: It would be preferable to do `p.Lifecycle.Append(cesController)` as then the `cilium-agent hive` output that shows the start and stop hooks would have nice function names rather than anonymous functions.

`Append` takes a `HookInterface` containing the `Start` and `Stop` methods. `Hook` is an alternative way of implementing the hooks, but it's usually preferably to have an object implement the `HookInterface` directly.

File: operator/pkg/ciliumendpointslice/reconciler.go [hunk 17]
```diff
@@ -7,93 +7,209 @@ import (
...
 	cesManager operations
+	cepStore   resource.Store[*cilium_v2.CiliumEndpoint]
+	cesStore   resource.Store[*cilium_v2a1.CiliumEndpointSlice]
 }
 
 // newReconciler creates and initializes a new reconciler.
-func newReconciler(client clientset.CiliumV2alpha1Interface, cesMgr operations) *reconciler {
+func newReconciler(client clientset.CiliumV2alpha1Interface, cesMgr operations,
+	logger logrus.FieldLogger, ciliumEndpoint resource.Resource[*cilium_v2.CiliumEndpoint], ciliumEndpointSlice resource.Resource[*cilium_v2a1.CiliumEndpointSlice]) *reconciler {
+	cepStore, _ := ciliumEndpoint.Store(context.Background())
```
Comment (joamaki) [inline operator/pkg/ciliumendpointslice/reconciler.go]: Do not call blocking (Store blocks until resource has synchronized) or side-effectful methods from a constructor as this is also called when inspecting hive (e.g. `go run ./operator hive`). Instead call these from a `Start` hook and use the start context to allow aborting the start.

https://docs.cilium.io/en/latest/contributing/development/hive/#guidelines

File: operator/watchers/ciliumendpoint/cilium_endpoint.go [hunk 18]
```diff
@@ -0,0 +1,153 @@
...
+	"github.com/cilium/cilium/pkg/logging"
+	"github.com/cilium/cilium/pkg/logging/logfields"
+)
+
+const identityIndex = "identity"
+
+type cepHanlderFunc func(cep *ciliumApiV2.CiliumEndpoint)
+
+var (
+	log      = logging.DefaultLogger.WithField(logfields.LogSubsys, "watchers")
```
Comment (joamaki) [inline operator/watchers/ciliumendpoint/cilium_endpoint.go]: s/watchers/ciliumendpoint/

File: operator/watchers/ciliumendpoint/cilium_endpoint.go [hunk 19]
```diff
@@ -0,0 +1,153 @@
...
+	once = sync.Once{}
+	CiliumEndpointsSynced = make(chan struct{})
+	CiliumEndpointsInit(ctx, wg, clientset)
+}
+
+// CiliumEndpointsInit starts a CiliumEndpointWatcher
+func CiliumEndpointsInit(ctx context.Context, wg *sync.WaitGroup, clientset k8sClient.Clientset) {
+	once.Do(func() {
+		CiliumEndpointStore = cache.NewIndexer(cache.DeletionHandlingMetaNamespaceKeyFunc, indexers)
+		ciliumEndpointInformer := informer.NewInformerWithStore(
```
Comment (joamaki) [inline operator/watchers/ciliumendpoint/cilium_endpoint.go]: We should not have two informers for the same object kind. Is this still needed after adding `Resource[*CiliumEndpoint]`? Would it be hard to convert the remaining uses? If it is consider converting this internally to use `Resource[*CiliumEndpoint]` as an intermediate step towards removing it. https://github.com/cilium/cilium/blob/main/pkg/k8s/watchers/pod.go#L124

File: operator/watchers/ciliumendpointslice/cilium_endpoint_slice.go [hunk 20]
```diff
@@ -0,0 +1,119 @@
...
+func CiliumEndpointSliceReinitialize(ctx context.Context, wg *sync.WaitGroup, clientset k8sClient.Clientset) {
+	once = sync.Once{}
+	CiliumEndpointSlicesSynced = make(chan struct{})
+	CiliumEndpointSliceInit(ctx, wg, clientset)
+}
+
+func CiliumEndpointSliceInit(ctx context.Context, wg *sync.WaitGroup, clientset k8sClient.Clientset) {
+	once.Do(func() {
+		var ciliumEndpointSliceInformer cache.Controller
+		CiliumEndpointSliceStore, ciliumEndpointSliceInformer = informer.NewInformer(
```
Comment (joamaki) [inline operator/watchers/ciliumendpointslice/cilium_endpoint_slice.go]: Same here, we really don't want duplicate informers.

**Review by joamaki — CHANGES_REQUESTED** [review]
Hey, this is looking great!

Any feedback on `pkg/hive` and `pkg/k8s/resource`? Did you find anything confusing or documentation lacking?

**Comment by alan-kut** [comment]
> Any feedback on pkg/hive and pkg/k8s/resource? Did you find anything confusing or documentation lacking?
https://docs.cilium.io/en/latest/contributing/development/hive/ is very good and I managed to learn how to use hive quite quickly.

I can think about two problems - please treat it as 
I had problems with testing - it was hard for me to provide resources and fake client - I ended up using hive to provide those for test.

It wasn't also clear how to wait for syncing resource cache.
I needed to go through the code to make sure I'll not get any event before getting cache sync event.
Then I learned that I can block on cache sync by getting the store.

File: operator/cmd/root.go (hunk 12 above)
Comment (alan-kut) [reply operator/cmd/root.go:174]: Done

File: operator/pkg/ciliumendpointslice/controller.go (hunk 14 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/controller.go]: Fixed. I wasn't sure how to propagate option.Config.EnableCiliumEndpointSlice to CES Controller but at the end I used it directly so at the end it's not needed and I forgot to remove it.

File: operator/pkg/ciliumendpointslice/controller.go (hunk 15 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/controller.go]: Fixed

File: operator/pkg/ciliumendpointslice/controller.go (hunk 16 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/controller.go]: Fixed, thanks. It makes sense.

File: operator/pkg/ciliumendpointslice/reconciler.go (hunk 17 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/reconciler.go]: This is called on Start - CES Controller creates reconciler (using newReconciler).
I moved this to Start just because of this.

I see that newReconciler may be confusing. I don't have much better idea as it doesn't do anything else except for getting those stores, logger and client.

File: operator/watchers/ciliumendpoint/cilium_endpoint.go (hunk 18 above)
Comment (alan-kut) [reply operator/watchers/ciliumendpoint/cilium_endpoint.go]: Done

File: operator/watchers/ciliumendpoint/cilium_endpoint.go (hunk 19 above)
Comment (alan-kut) [reply operator/watchers/ciliumendpoint/cilium_endpoint.go]: When I started working on the Full CES Reconciliation I was unaware of the hive.
I started by fixing the watchers, implemented full reconciliation and then I learned about the hive and I moved CES Controller to hive.

If I knew about the hive I wouldn't refactor legacy watchers. I can revert this refactoring if needed.
I'll try to revert this refactoring.
This won't help with the main issue - there are still use cases on legacy watchers.

I talked to @pippolo84 about this problem and it's tricky one. It may be hard to move everything out of legacy watchers at once. He agreed that we may have some period of time in which we would have two informers.

I'm trying to move other use case to hive in the #27458
I could work on all remaining use cases but there is already some work done by @pippolo84 so I'm not sure whether it's ok to hijack it.

File: operator/pkg/ciliumendpointslice/cell.go (hunk 13 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/cell.go:34]: Added

**Comment by alan-kut** [comment]
@joamaki Thank you for the review.

I replied to all the comments.

I also:
- reverted the refactoring on the watchers - should've done this when I moved CES Controller to hive
- due to this I needed to move Identity GC to CES resource so I decided to combine the other PR with this one
- I fixed the leaks from hive.Stop() and added such test for the CES Controller as well

**Comment by alan-kut** [comment]
I will be out till Wednesday

File: operator/pkg/ciliumendpointslice/reconciler.go (hunk 17 above)
Comment (joamaki) [reply operator/pkg/ciliumendpointslice/reconciler.go]: Ah sorry, I missed that it was called from a start hook. In that case I don't have any problem with this. I think the naming etc. is fine here. I should've checked how it was used and not assume.

File: operator/identitygc/crd_gc_test.go [hunk 21]
```diff
@@ -0,0 +1,88 @@
...
+)
+
+func TestUsedIdentitiesInCESs(t *testing.T) {
+	wait := make(chan struct{})
+	var fakeClient k8sClient.FakeClientset
+	var ciliumEndpointSlice resource.Resource[*cilium_v2a1.CiliumEndpointSlice]
+	hive := hive.New(
+		k8sClient.FakeClientCell,
+		k8s.ResourcesCell,
+		cell.Invoke(func(c *k8sClient.FakeClientset, cep resource.Resource[*cilium_v2.CiliumEndpoint], ces resource.Resource[*cilium_v2a1.CiliumEndpointSlice]) error {
```
Comment (pippolo84) [inline operator/identitygc/crd_gc_test.go]: `cep` parameter is unused, it can be removed

File: operator/identitygc/crd_gc_test.go [hunk 22]
```diff
@@ -0,0 +1,88 @@
...
+			fakeClient = *c
+			ciliumEndpointSlice = ces
+			close(wait)
+			return nil
+		}),
+	)
+	hive.Start(context.Background())
+	<-wait
```
Comment (pippolo84) [inline operator/identitygc/crd_gc_test.go]: `Invoke` calls are executed synchronously before `Start` returns, so there's no need to wait here (but I suggest to add a check for the error returned by `hive.Start`).

File: operator/identitygc/crd_gc_test.go [hunk 23]
```diff
@@ -0,0 +1,88 @@
...
+	time.Sleep(50 * time.Millisecond)
+	wantIdentities["10"] = true
+	wantIdentities["20"] = true
+	wantIdentities["30"] = true
+	wantIdentities["40"] = true
+	wantIdentities["50"] = true
+	gotIdentities = usedIdentitiesInCESs(cesStore)
+	assertEqualIDs(t, wantIdentities, gotIdentities)
+
+	hive.Stop(context.Background())
```
Comment (pippolo84) [inline operator/identitygc/crd_gc_test.go]: Same here, better to check for the error returned by `hive.Stop`

File: operator/identitygc/crd_gc_test.go [hunk 24]
```diff
@@ -0,0 +1,88 @@
...
+
+	// Empty store.
+	gotIdentities := usedIdentitiesInCESs(cesStore)
+	wantIdentities := make(map[string]bool)
+	assertEqualIDs(t, wantIdentities, gotIdentities)
+
+	// 5 IDs in the store.
+	cesA := createCESWithIDs("cesA", []int64{1, 2, 3, 4, 5})
+	fakeClient.CiliumV2alpha1().CiliumEndpointSlices().Create(context.Background(), cesA, meta_v1.CreateOptions{})
+	time.Sleep(50 * time.Millisecond)
```
Comment (pippolo84) [inline operator/identitygc/crd_gc_test.go]: One-shot `time.Sleep`s with fixed duration don't play nice with the unpredictability of the CI environment. To avoid introducing flakiness, I suggest to use `testutils.WaitUntil` or `testutils.WaitUntilWithSleep` with a very large timeout.

File: operator/identitygc/crd_gc_test.go [hunk 25]
```diff
@@ -0,0 +1,88 @@
...
+	wantIdentities["3"] = true
+	wantIdentities["4"] = true
+	wantIdentities["5"] = true
+	gotIdentities = usedIdentitiesInCESs(cesStore)
+	assertEqualIDs(t, wantIdentities, gotIdentities)
+
+	// 10 IDs in the store.
+	cesB := createCESWithIDs("cesB", []int64{10, 20, 30, 40, 50})
+	fakeClient.CiliumV2alpha1().CiliumEndpointSlices().Create(context.Background(), cesB, meta_v1.CreateOptions{})
+	time.Sleep(50 * time.Millisecond)
```
Comment (pippolo84) [inline operator/identitygc/crd_gc_test.go]: Same here, use `testutils.WaitUntil` or `testutils.WaitUntilWithSleep`

File: operator/pkg/ciliumendpointslice/ceptocesmap.go [hunk 26]
```diff
@@ -8,104 +8,137 @@ import "github.com/cilium/cilium/pkg/lock"
...
+	c.mutex.RLock()
+	defer c.mutex.RUnlock()
+	return len(c.cesNameToCEPNameSet)
+}
+
+// Return names of all CESs.
+func (c *CESToCEPMapping) getAllCESs() []CESName {
+	c.mutex.RLock()
+	defer c.mutex.RUnlock()
+	var cess []CESName
```
Comment (pippolo84) [inline operator/pkg/ciliumendpointslice/ceptocesmap.go]: Nit: `cess := make([]CESName, 0, len(c.cesNameToCEPNameSet))`

File: operator/pkg/ciliumendpointslice/ceptocesmap.go [hunk 27]
```diff
@@ -8,104 +8,137 @@ import "github.com/cilium/cilium/pkg/lock"
...
-// Remove the CES tracker from map
-func (c *CESToCEPMapping) deleteCES(cesName string) {
-	c.cesMutex.Lock()
-	defer c.cesMutex.Unlock()
-	delete(c.desiredCESs, CESName(cesName))
+// Return CEP Names mapped to the given CES
+func (c *CESToCEPMapping) getCEPsInCES(ces CESName) []CEPName {
+	c.mutex.RLock()
+	defer c.mutex.RUnlock()
+	ceps := []CEPName{}
```
Comment (pippolo84) [inline operator/pkg/ciliumendpointslice/ceptocesmap.go]: Nit: `ceps := make([]CEPName, 0, len(c.cesNameToCEPNameSet[ces]))`

File: operator/pkg/ciliumendpointslice/controller.go [hunk 28]
```diff
@@ -0,0 +1,97 @@
...
+	enqueuedAt                     map[CESName]time.Time
+	preInitEnqueuedEndpointsEvents []EndpointEvent
+	endpointsMappingInitialized    bool
+
+	wp *workerpool.WorkerPool
+}
+
+// registerController creates and initializes the CES controller
+func registerController(p params) {
+	if !p.Clientset.IsEnabled() && option.Config.EnableCiliumEndpointSlice {
```
Comment (pippolo84) [inline operator/pkg/ciliumendpointslice/controller.go]: Shouldn't this be `if !p.Clientset.IsEnabled() || !option.Config.EnableCiliumEndpointSlice {` ?

File: operator/pkg/ciliumendpointslice/endpointslice_test.go [hunk 29]
```diff
@@ -51,115 +52,137 @@ func createStoreEndpointSlice(name string, namespace string, endpoints []capi_v2
...
+		cell.Invoke(func(c *k8sClient.FakeClientset, cep resource.Resource[*cilium_v2.CiliumEndpoint], ces resource.Resource[*cilium_v2a1.CiliumEndpointSlice]) error {
+			fakeClient = *c
+			ciliumEndpoint = cep
+			ciliumEndpointSlice = ces
+			close(wait)
+			return nil
+		}),
+	)
+	hive.Start(context.Background())
+	<-wait
```
Comment (pippolo84) [inline operator/pkg/ciliumendpointslice/endpointslice_test.go]: No need to wait here.

File: operator/pkg/ciliumendpointslice/endpointslice_test.go [hunk 30]
```diff
@@ -51,115 +52,137 @@ func createStoreEndpointSlice(name string, namespace string, endpoints []capi_v2
...
```
Comment (pippolo84) [inline operator/pkg/ciliumendpointslice/endpointslice_test.go]: No need to wait here.

**Review by pippolo84 — CHANGES_REQUESTED** [review]
Thanks for the PR and for the additional effort to refactor the identitygc.
I did a first pass and left some suggestions inline, I'm planning to do another pass focusing on the CES controller inner workings tomorrow.

File: operator/pkg/ciliumendpointslice/endpointslice.go [hunk 31]
```diff
@@ -48,263 +48,237 @@ const (
...
+// start the worker thread, reconciles the modified CESs with api-server
+func (c *Controller) Start(ctx hive.HookContext) error {
+	c.logger.Info("Bootstrap ces controller")
+	defer utilruntime.HandleCrash()
+	if c.slicingMode == cesIdentityBasedSlicing {
+		c.manager = newCESManagerIdentity(c.maxCEPsInCES, c.logger)
+	} else {
+		c.manager = newCESManagerFcfs(c.maxCEPsInCES, c.logger)
+	}
+	c.reconciler = newReconciler(c.clientset.CiliumV2alpha1(), c.manager, c.logger, c.ciliumEndpoint, c.ciliumEndpointSlice)
```
Comment (pippolo84) [inline operator/pkg/ciliumendpointslice/endpointslice.go]: We should pass down the `hive.HookContext` here in order to use it when Creating/Updating/Deleting CESs in place of `context.TODO()`.

File: operator/pkg/ciliumendpointslice/reconciler.go [hunk 32]
```diff
@@ -7,93 +7,214 @@ import (
...
+		}
 	}
 
 	// Call the client API, to Create CES
-	if retCES, err = r.client.CiliumEndpointSlices().Create(
-		context.TODO(), ces, metav1.CreateOptions{}); err != nil {
-		log.WithError(err).WithFields(logrus.Fields{
-			logfields.CESName: cesToCreate,
+	if _, err = r.client.CiliumEndpointSlices().Create(
+		context.TODO(), newCES, meta_v1.CreateOptions{}); err != nil {
```
Comment (pippolo84) [inline operator/pkg/ciliumendpointslice/reconciler.go]: Following the above comment, we should use the context from the upper level and extend the check as `err != nil && !errors.Is(err, context.Canceled)`.
Same for the update and deletion.

File: operator/pkg/ciliumendpointslice/endpointslice_test.go [hunk 33]
```diff
@@ -54,240 +52,137 @@ func createStoreEndpointSlice(name string, namespace string, endpoints []capi_v2
...
+	cesN, _ = mapping.getCESName(NewCEPName("cep3", "ns"))
+	assert.Equal(t, cesN, NewCESName("ces1"))
+	cesN, _ = mapping.getCESName(NewCEPName("cep4", "ns"))
+	assert.Equal(t, cesN, NewCESName("ces1"))
+	cesN, _ = mapping.getCESName(NewCEPName("cep5", "ns"))
+	assert.Equal(t, cesN, NewCESName("ces2"))
+	cesN, _ = mapping.getCESName(NewCEPName("cep6", "ns"))
+	assert.Equal(t, cesN, NewCESName("ces2"))
+	cesN, _ = mapping.getCESName(NewCEPName("cep7", "ns"))
+	assert.Equal(t, cesN, NewCESName("ces2"))
```
Comment (pippolo84) [inline operator/pkg/ciliumendpointslice/endpointslice_test.go:116]: The call to hive.Stop is missing, this test will leak goroutines.

File: operator/pkg/ciliumendpointslice/endpointslice_test.go [hunk 34]
```diff
@@ -54,240 +52,137 @@ func createStoreEndpointSlice(name string, namespace string, endpoints []capi_v2
...
+	assert.Equal(t, 0, cesController.queue.Len())
+	assert.Equal(t, 4, len(cesController.preInitEnqueuedEndpointsEvents))
+	assert.Equal(t, false, cesController.endpointsMappingInitialized)
+
+	cesController.syncCESsInLocalCache(context.Background())
+	assert.Equal(t, true, cesController.endpointsMappingInitialized)
+
+	cesController.processEnqueuedPreInitEndpoints()
+	time.Sleep(DefaultCESSyncTime * 2) // elements are added to the queue with a default delay
+	assert.Equal(t, 2, cesController.queue.Len())
```
Comment (pippolo84) [inline operator/pkg/ciliumendpointslice/endpointslice_test.go]: Missing call to hive.Stop

File: operator/pkg/ciliumendpointslice/reconciler_test.go [hunk 35]
```diff
@@ -4,217 +4,226 @@
...
+	m.mapping.insertCEP(NewCEPName("cep2", "ns"), NewCESName("ces1"))
+	m.mapping.insertCEP(NewCEPName("cep3", "ns"), NewCESName("ces2"))
+	r.reconcileCES(NewCESName("ces1"))
+
+	assert.Equal(t, "ces1", createdSlice.Name)
+	assert.Equal(t, 2, len(createdSlice.Endpoints))
+	assert.Equal(t, "ns", createdSlice.Namespace)
+	eps := []string{createdSlice.Endpoints[0].Name, createdSlice.Endpoints[1].Name}
+	assert.Contains(t, eps, "cep1")
+	assert.Contains(t, eps, "cep2")
```
Comment (pippolo84) [inline operator/pkg/ciliumendpointslice/reconciler_test.go:73]: Missing call to hive.Stop

File: operator/pkg/ciliumendpointslice/reconciler_test.go [hunk 36]
```diff
@@ -4,217 +4,226 @@
...
+	// ces1 contains cep1 and cep3, but it's mapped to cep1 and cep2
+	// so it's expected that after update it would contain cep1 and cep2
+	r.reconcileCES(NewCESName("ces1"))
+
+	assert.Equal(t, "ces1", updatedSlice.Name)
+	assert.Equal(t, 2, len(updatedSlice.Endpoints))
+	assert.Equal(t, "ns", updatedSlice.Namespace)
+	eps := []string{updatedSlice.Endpoints[0].Name, updatedSlice.Endpoints[1].Name}
+	assert.Contains(t, eps, "cep1")
+	assert.Contains(t, eps, "cep2")
```
Comment (pippolo84) [inline operator/pkg/ciliumendpointslice/reconciler_test.go:128]: Missing call to hive.Stop

File: operator/pkg/ciliumendpointslice/reconciler_test.go [hunk 37]
```diff
@@ -4,217 +4,226 @@
...
+	cesStore.CacheStore().Add(ces1)
+	m.mapping.insertCES(NewCESName("ces1"), "ns")
+	m.mapping.insertCES(NewCESName("ces2"), "ns")
+	m.mapping.insertCEP(NewCEPName("cep1", "ns"), NewCESName("ces2"))
+	m.mapping.insertCEP(NewCEPName("cep2", "ns"), NewCESName("ces2"))
+	m.mapping.insertCEP(NewCEPName("cep3", "ns"), NewCESName("ces2"))
+	// ces1 contains cep1 and cep3, but it's mapped to nothing so it should be deleted
+	r.reconcileCES(NewCESName("ces1"))
+
+	assert.Equal(t, "ces1", deletedSlice)
```
Comment (pippolo84) [inline operator/pkg/ciliumendpointslice/reconciler_test.go:177]: Missing call to hive.Stop

File: operator/pkg/ciliumendpointslice/reconciler_test.go [hunk 38]
```diff
@@ -4,217 +4,226 @@
...
+	cepStore.CacheStore().Add(cep3)
+	m.mapping.insertCES(NewCESName("ces1"), "ns")
+	m.mapping.insertCES(NewCESName("ces2"), "ns")
+	m.mapping.insertCEP(NewCEPName("cep1", "ns"), NewCESName("ces2"))
+	m.mapping.insertCEP(NewCEPName("cep2", "ns"), NewCESName("ces2"))
+	m.mapping.insertCEP(NewCEPName("cep3", "ns"), NewCESName("ces2"))
+	// ces1 contains cep1 and cep3, but it's mapped to nothing so it should be deleted
+	r.reconcileCES(NewCESName("ces1"))
+
+	assert.Equal(t, true, noRequest)
```
Comment (pippolo84) [inline operator/pkg/ciliumendpointslice/reconciler_test.go:222]: Missing call to hive.Stop

File: operator/pkg/ciliumendpointslice/controller.go [hunk 39]
```diff
@@ -0,0 +1,97 @@
...
+	Lifecycle hive.Lifecycle
+
+	Clientset           k8sClient.Clientset
+	CiliumEndpoint      resource.Resource[*v2.CiliumEndpoint]
+	CiliumEndpointSlice resource.Resource[*v2alpha1.CiliumEndpointSlice]
+
+	Cfg Config
+}
+
+type EndpointEvent struct {
```
Comment (pippolo84) [inline operator/pkg/ciliumendpointslice/controller.go]: No need to export this type.

File: operator/pkg/ciliumendpointslice/endpointslice.go [hunk 40]
```diff
@@ -48,263 +48,237 @@ const (
...
-		// Create new CES locally, with the given cesName
-		manager.createCES(ces.GetName())
-
-		// Deep copy the ces, we got from api-server to local datastore.
-		manager.updateCESInCache(ces, true)
-
+func (c *Controller) processEnqueuedPreInitEndpoints() {
+	for _, e := range c.preInitEnqueuedEndpointsEvents {
+		if e.event == updateEvent {
+			c.onEndpointUpdate(e.cep)
```
Comment (pippolo84) [inline operator/pkg/ciliumendpointslice/endpointslice.go]: I suggest to add a Debug log here too, as already done in `runCiliumEndpointsUpdater`, it might be convenient. Same for the deletion.

File: operator/identitygc/crd_gc_test.go (hunk 21 above)
Comment (alan-kut) [reply operator/identitygc/crd_gc_test.go]: Fixed

File: operator/identitygc/crd_gc_test.go (hunk 22 above)
Comment (alan-kut) [reply operator/identitygc/crd_gc_test.go]: Fixed. I think I had problems with it at some point but it works now. Removed

File: operator/identitygc/crd_gc_test.go (hunk 23 above)
Comment (alan-kut) [reply operator/identitygc/crd_gc_test.go]: Fixed

File: operator/identitygc/crd_gc_test.go (hunk 24 above)
Comment (alan-kut) [reply operator/identitygc/crd_gc_test.go]: Glad I could learn something new. Fixed.

File: operator/identitygc/crd_gc_test.go (hunk 25 above)
Comment (alan-kut) [reply operator/identitygc/crd_gc_test.go]: Fixed

File: operator/pkg/ciliumendpointslice/ceptocesmap.go (hunk 26 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/ceptocesmap.go]: Fixed

File: operator/pkg/ciliumendpointslice/ceptocesmap.go (hunk 27 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/ceptocesmap.go]: Fixed

File: operator/pkg/ciliumendpointslice/controller.go (hunk 28 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/controller.go]: You are right. Fixed. Moved the EnableCiliumEndpointSlice to shared config and added test to verify it is used correctly.

File: operator/pkg/ciliumendpointslice/endpointslice_test.go (hunk 29 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/endpointslice_test.go]: Fixed here and in the other places in the CES controller tests

File: operator/pkg/ciliumendpointslice/endpointslice_test.go (hunk 30 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/endpointslice_test.go]: fixed

File: operator/pkg/ciliumendpointslice/endpointslice_test.go [hunk 41]
```diff
@@ -54,240 +52,131 @@ func createStoreEndpointSlice(name string, namespace string, endpoints []capi_v2
...
+	cesN, _ = mapping.getCESName(NewCEPName("cep3", "ns"))
+	assert.Equal(t, cesN, NewCESName("ces1"))
+	cesN, _ = mapping.getCESName(NewCEPName("cep4", "ns"))
+	assert.Equal(t, cesN, NewCESName("ces1"))
+	cesN, _ = mapping.getCESName(NewCEPName("cep5", "ns"))
+	assert.Equal(t, cesN, NewCESName("ces2"))
+	cesN, _ = mapping.getCESName(NewCEPName("cep6", "ns"))
+	assert.Equal(t, cesN, NewCESName("ces2"))
+	cesN, _ = mapping.getCESName(NewCEPName("cep7", "ns"))
+	assert.Equal(t, cesN, NewCESName("ces2"))
```
Comment (pippolo84) [inline operator/pkg/ciliumendpointslice/endpointslice_test.go:116]: Also, before stopping the hive, you need to call `cesController.queue.ShutDown()` to stop the internal client-go goroutine managing the delaying queue. That is because you are manually managing (outside of the hive lifecycle) the CES controller (and so controller `Stop` is not called).
After doing that, you can get rid of the goleak.IgnoreCurrent, since there will be no other goroutine leak (ultimately making the test better in finding possible leaks).

File: operator/pkg/ciliumendpointslice/endpointslice_test.go [hunk 42]
```diff
@@ -54,240 +52,131 @@ func createStoreEndpointSlice(name string, namespace string, endpoints []capi_v2
...
+	assert.Equal(t, 0, cesController.queue.Len())
+	assert.Equal(t, 4, len(cesController.preInitEnqueuedEndpointsEvents))
+	assert.Equal(t, false, cesController.endpointsMappingInitialized)
+
+	cesController.syncCESsInLocalCache(context.Background())
+	assert.Equal(t, true, cesController.endpointsMappingInitialized)
+
+	cesController.processEnqueuedPreInitEndpoints()
+	time.Sleep(DefaultCESSyncTime * 2) // elements are added to the queue with a default delay
+	assert.Equal(t, 2, cesController.queue.Len())
```
Comment (pippolo84) [inline operator/pkg/ciliumendpointslice/endpointslice_test.go]: Same here, we need to call `cesController.queue.ShutDown()`before stopping the hive.

File: operator/pkg/ciliumendpointslice/utils.go [hunk 43]
```diff
@@ -0,0 +1,31 @@
...
+// of a CES name is similar to pod k8s naming convention "ces-123456789-abcde".
+// First 3 letters indicates ces resource, followed by random letters.
+func uniqueCESliceName(mapping *CESToCEPMapping) string {
+	var cesName string
+	for {
+		cesName = fmt.Sprintf("%s-%s-%s", cesNamePrefix, randomName(9), randomName(5))
+		if !mapping.hasCESName(NewCESName(cesName)) {
+			return cesName
+		}
+	}
```
Comment (pippolo84) [inline operator/pkg/ciliumendpointslice/utils.go]: Not sure if this truly qualifies as a "hot path", but I suggest to avoid the usage of `fmt.Sprintf` in favor of `strings.Builder` (it is also possible to preallocate the underlying buffer with the right size):
```
	var sb strings.Builder
	for {
		rn1, rn2 := randomName(9), randomName(5)

		sb.Reset()
		sb.Grow(len(cesNamePrefix) + 1 + len(rn1) + 1 + len(rn2))
		sb.WriteString(cesNamePrefix)
		sb.WriteRune('-')
		sb.WriteString(rn1)
		sb.WriteRune('-')
		sb.WriteString(rn2)
		cesName := sb.String()

		if !mapping.hasCESName(NewCESName(cesName)) {
			return cesName
		}
	}
```

See https://github.com/cilium/cilium/issues/19571

File: operator/pkg/ciliumendpointslice/manager.go [hunk 44]
```diff
@@ -211,394 +97,99 @@ func uniqueCESliceName(desiredCESs *CESToCEPMapping) string {
...
+			logfields.CEPName: cepName.string(),
+			logfields.CESName: cesName.string(),
+		}).Debug("Removing CEP from CES")
+		c.mapping.deleteCEP(cepName)
+		if c.mapping.countCEPsInCES(cesName) == 0 {
+			c.mutex.Lock()
+			defer c.mutex.Unlock()
+			if c.mapping.countCEPsInCES(cesName) == 0 {
+				c.mapping.deleteCES(cesName)
+			}
```
Comment (pippolo84) [inline operator/pkg/ciliumendpointslice/manager.go]: I suggest to add a brief comment to explain that we're doing the first check with the read lock to avoid the performance penalty of acquiring the write lock every time. The double check might be confusing for a casual reader.

File: operator/pkg/ciliumendpointslice/manager.go [hunk 45]
```diff
@@ -607,133 +198,125 @@ func (c *cesManagerIdentity) InsertCEPInCache(cep *cilium_v2.CoreCiliumEndpoint,
...
-	if ces.cesInsertedAt.IsZero() {
-		ces.cesInsertedAt = time.Now()
+func (c *cesManagerIdentity) removeCESToIdentity(id int64, cesName CESName) {
+	cesSlice := c.identityToCES[id]
+	for i, ces := range cesSlice {
+		if ces == cesName {
+			cesSlice[i] = cesSlice[len(cesSlice)-1]
+		}
 	}
+	c.identityToCES[id] = cesSlice
```
Comment (pippolo84) [inline operator/pkg/ciliumendpointslice/manager.go]: Shouldn't we keep track of how many elements we've overwritten in cesSlice at line 291 and then assign here `cesSlice[:len(cesSlice)-removed]`? Otherwise the slices in the `c.identityToCES` won't never shrink.

**Review by pippolo84 — CHANGES_REQUESTED** [review]
I've completed a second round of review.
Overall LGTM, my suggestions are mainly related to the tests. Thanks again!

File: operator/pkg/ciliumendpointslice/endpointslice.go (hunk 31 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/endpointslice.go]: Fixed

File: operator/pkg/ciliumendpointslice/reconciler.go (hunk 32 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/reconciler.go]: Fixed

File: operator/pkg/ciliumendpointslice/endpointslice_test.go (hunk 33 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/endpointslice_test.go:116]: Fixed

File: operator/pkg/ciliumendpointslice/endpointslice_test.go (hunk 34 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/endpointslice_test.go]: Fixed

File: operator/pkg/ciliumendpointslice/reconciler_test.go (hunk 35 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/reconciler_test.go:73]: Fixed

File: operator/pkg/ciliumendpointslice/reconciler_test.go (hunk 36 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/reconciler_test.go:128]: Fixed

File: operator/pkg/ciliumendpointslice/reconciler_test.go (hunk 37 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/reconciler_test.go:177]: Fixed

File: operator/pkg/ciliumendpointslice/reconciler_test.go (hunk 38 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/reconciler_test.go:222]: Fixed

File: operator/pkg/ciliumendpointslice/controller.go (hunk 39 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/controller.go]: Fixed

File: operator/pkg/ciliumendpointslice/endpointslice.go (hunk 40 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/endpointslice.go]: Added

File: operator/pkg/ciliumendpointslice/endpointslice_test.go (hunk 41 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/endpointslice_test.go:116]: Fixed stopping the queue.

Regarding IgnoreCurrent - Shouldn't we always use it?
Otherwise it's easy to add a test for A (e.g. some CES controller test leaking) and change some other part B (e.g. Identity GC) that does have such test and the test for B would start failing even though the problem is totally outside of B.

File: operator/pkg/ciliumendpointslice/endpointslice_test.go (hunk 42 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/endpointslice_test.go]: Fixed

File: operator/pkg/ciliumendpointslice/utils.go (hunk 43 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/utils.go]: I just moved this code but there is no harm in changing it now do string builder.

File: operator/pkg/ciliumendpointslice/manager.go (hunk 44 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/manager.go]: Added, you are right, it may  be confusing

File: operator/pkg/ciliumendpointslice/manager.go (hunk 45 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/manager.go]: Fixed. Good catch.

File: operator/pkg/ciliumendpointslice/endpointslice_test.go (hunk 41 above)
Comment (pippolo84) [reply operator/pkg/ciliumendpointslice/endpointslice_test.go:116]: That's true but, if we keep that, it's easier to add a new test that might leak a goroutine, and let the leak go unnoticed. I find this to be even worse, although you're right that having a failure in another test is not ideal.
The hive based tests are like integration tests for multiple cells even if they are written as unit. I suggest to first add goleak to each hive based test (like the ones in `endpointslice_test.go` and in `reconciler_test.go`) and then check that we are not leaking anything (except for anything that is due to a dependency like client-go). If so, I still suggest to avoid `IgnoreCurrent` for now.

Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/endpointslice_test.go:116]: Also - those test would fail if some other test fail and doesn't clean up everything.
```
hive.Start()

err := checkSth()
if err != nil {
  t.Fatalf("failed")
}

hive.Stop()
```

Removed IgnoreCurrent for now.

It would be good to have some kind of a leak test at the end if all other test passed, maybe?

**Comment by alan-kut** [comment]
I think I responded to all the comments. If some test/check fails I'll fix it on Monday

File: operator/pkg/ciliumendpointslice/endpointslice_test.go (hunk 41 above)
Comment (pippolo84) [reply operator/pkg/ciliumendpointslice/endpointslice_test.go:116]: > Also - those test would fail if some other test fail and doesn't clean up everything.

That's true but that is less harmful, since it'll be clear that the root cause is the first test failure.

> It would be good to have some kind of a leak test at the end if all other test passed, maybe?

I think that right now is not necessary, since we can check every single hive-based test with goleak, excluding what we already know is leaking (and out of our control), like `k8s.io/client-go/util/workqueue.(*Type).updateUnfinishedWorkLoop`.

**Comment by alan-kut** [comment]
Thanks, fixed it.

I read that start context should be used for all potentially long running operations during start but I thought that it would harm to use it later after I got your comment.

> This came up after a round of manual testing in a kind cluster
Did you test this PR specifically or are there some kind of other tests not shown here?

I have prepared a manual test for identities so I would've caught it as well before merging.
I'll run my test as well once we are close to accepting the PR.

**Comment by pippolo84** [comment]
> Did you test this PR specifically or are there some kind of other tests not shown here?

Yep, I've played a bit with this branch.

> I have prepared a manual test for identities so I would've caught it as well before merging.
> I'll run my test as well once we are close to accepting the PR.

Sounds good, thanks.

File: operator/pkg/ciliumendpointslice/controller_test.go [hunk 46]
```diff
@@ -0,0 +1,135 @@
...
+		}),
+	)
+	if err := hive.Start(context.Background()); err != nil {
+		t.Fatalf("failed to start: %s", err)
+	}
+	cesCreated, err := createCEPandVerifyCESCreated(fakeClient, ciliumEndpoint, ciliumEndpointSlice)
+	if err != nil {
+		t.Fatalf("Couldn't verify if CES is created: %s", err)
+	}
+	// Verify CES is created when CES features is disabled
```
Comment (pippolo84) [inline operator/pkg/ciliumendpointslice/controller_test.go]: Typo: `disabled` -> `enabled`

File: operator/pkg/ciliumendpointslice/endpointslice.go [hunk 47]
```diff
@@ -48,263 +48,244 @@ const (
...
-		logfields.CESSliceMode: c.slicingMode,
-	}).Info("Starting CES controller reconciler.")
+func (c *Controller) enqueueCESReconciliation(cess []CESName) {
+	for _, ces := range cess {
+		c.logger.WithFields(logrus.Fields{
+			logfields.CESName: ces.string(),
+		}).Debug("Enqueueing CES (if not empty name)")
+		if ces.Name != "" {
+			if c.enqueuedAt[ces].IsZero() {
+				c.enqueuedAt[ces] = time.Now()
```
Comment (pippolo84) [inline operator/pkg/ciliumendpointslice/endpointslice.go:109]: I think `enqueuedAt` needs to be protected from concurrent writes. It is written here (from the workerpool `cilium-endpoint-slices-updater` goroutine) and from the `worker` goroutine in `getAndResetCESProcessingDelay`.

**Review by rolinh — CHANGES_REQUESTED** [review]
I just did a review of the vendor changes. Please, see suggestion below.

File: operator/pkg/ciliumendpointslice/controller_test.go [hunk 48]
```diff
@@ -0,0 +1,135 @@
...
+}
+
+func createCEPandVerifyCESCreated(fakeClient k8sClient.FakeClientset, ciliumEndpoint resource.Resource[*cilium_v2.CiliumEndpoint], ciliumEndpointSlice resource.Resource[*cilium_v2a1.CiliumEndpointSlice]) (bool, error) {
+	cep := createStoreEndpoint("cep1", "ns", 1)
+	fakeClient.CiliumV2().CiliumEndpoints("ns").Create(context.Background(), cep, meta_v1.CreateOptions{})
+	cepStore, _ := ciliumEndpoint.Store(context.Background())
+	if err := testutils.WaitUntil(func() bool {
+		return len(cepStore.List()) > 0
+	}, time.Second); err != nil {
+		return false, errors.Errorf("failed to get CEP: %s", err)
```
Comment (rolinh) [inline operator/pkg/ciliumendpointslice/controller_test.go]: I don't see a good argument for having `github.com/pkg/errors` as a new direct dependency. 
```suggestion
		return false, fmt.Errorf("failed to get CEP: %s", err)
```

**Review by rolinh — CHANGES_REQUESTED** [review]

File: operator/pkg/ciliumendpointslice/manager.go [hunk 49]
```diff
@@ -23,75 +18,31 @@ var (
...
 	// as well as CEPName to CESName.
-	desiredCESs *CESToCEPMapping
+	mapping *CESToCEPMapping
 
-	// workqueue is used to sync CESs with the api-server. this will rate-limit the
-	// CES requests going to api-server, ensures a single CES will not be proccessed
-	// multiple times concurrently, and if CES is added multiple times before it
-	// can be processed, this will only be processed only once.
-	queue workqueue.RateLimitingInterface
+	mutex lock.Mutex
```
Comment (pippolo84) [inline operator/pkg/ciliumendpointslice/manager.go]: This lock can be avoided since `mapping` is assigned once at the manager startup and then every ops on it is protected by its internal lock. Same for `maxCEPsInCES`, it is assigned at startup and then only read.

File: operator/pkg/ciliumendpointslice/controller.go [hunk 50]
```diff
@@ -0,0 +1,100 @@
...
+	// multiple times concurrently, and if CES is added multiple times before it
+	// can be processed, this will only be processed only once.
+	queue           workqueue.RateLimitingInterface
+	queueTerminated chan struct{}
+	writeQPSLimit   float64
+	writeQPSBurst   int
+
+	enqueuedAt                     map[CESName]time.Time
+	preInitEnqueuedEndpointsEvents []endpointEvent
+	endpointsMappingInitialized    bool
```
Comment (pippolo84) [inline operator/pkg/ciliumendpointslice/controller.go]: I think the access to `endpointsMappingInitialized` needs to be synchronized (for example using an `atomic.Bool`). That's because it is written by the goroutine that executes `syncCESsInLocalCache` and it is read by the goroutine that executes `onEndpointUpdate` and `onEndpointDelete` (that is, the goroutine `cilium-endpoints-updater` from the workerpool).
IOW, the second goroutine is doing a busy wait on that boolean, and doing that without synchronization is incorrect, as reported [here](https://go.dev/ref/mem) (look for the relevant example regarding "busy waiting").

**Review by pippolo84 — CHANGES_REQUESTED** [review]
Thanks for addressing all the comments! I've focused this last round of review on the usage of locks. I think there is something that needs to be addressed.
Apart from that, I think now the PR is starting to looking great! :+1:

File: operator/pkg/ciliumendpointslice/controller_test.go (hunk 48 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/controller_test.go]: Fixed, thanks

File: operator/pkg/ciliumendpointslice/controller_test.go (hunk 46 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/controller_test.go]: Fixed

File: operator/pkg/ciliumendpointslice/manager.go (hunk 49 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/manager.go]: It is used in the following cases:

Get largest not full CES and create new one if there is none. Without lock there may be too many CEPs in CES or too many CESs (all gets the same CES and fill it above capacity or all create new one when one would be enough)
```go
cesName = c.getLargestAvailableCESForNamespace(ns)
if cesName.Name == "" {
	cesName = c.createCES("", ns)
}
c.mapping.insertCEP(cepName, cesName)
```

Check if CES can be deleted. Without this check new CEP may be added to the CES and CES then deleted.
```go
c.mutex.Lock()
defer c.mutex.Unlock()
if c.mapping.countCEPsInCES(cesName) == 0 {
	c.mapping.deleteCES(cesName)
}
```

The same, a little bit more complicated, for identity.

I think I could rewrite this code without this lock. The mapping could do the checks and then return error. But it means the code would need to be changed to the loop.

File: operator/pkg/ciliumendpointslice/controller.go (hunk 50 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/controller.go]: I don't think it's busy waiting.

```go
func (c *Controller) onEndpointEvent(cep *cilium_api_v2.CiliumEndpoint) {
  if c.endpointsMappingInitialized {
    process
  } else {
    add to queue
}
```
Nothing else read it. It's changed to true later.

I agree we need synchronization to avoid situation in which we miss an event - check for c.endpointsMappingInitialized return false but the queue is started being processed before new element is added.

I think we need synchronization on the preInitEnqueuedEndpointsEvents even more. If two threads change it at the same time (it's not possible right now I think as we have 1 thread processing the events) then we will miss some events.

It's too bad we will have quite complicated code here just for short period of time.
I'll try to remove it all together. I think we can start processing the events only after the initial mapping is initialized.

Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/controller.go]: Done it. It is quite simple with the hive as we can start processing event when we want to.

File: operator/pkg/ciliumendpointslice/manager.go (hunk 49 above)
Comment (pippolo84) [reply operator/pkg/ciliumendpointslice/manager.go]: > It is used in the following cases:
> 
> Get largest not full CES and create new one if there is none. Without lock there may be too many CEPs in CES or too many CESs (all gets the same CES and fill it above capacity or all create new one when one would be enough)
> 

But the only operations that can insert or remove a CEP are:
- `UpdateCEPMapping` and `RemoveCEPMapping`, but these are serialized by the channel returned by `Events` in `runCiliumEndpointsUpdater` (IOW it's not possible to handle multiple CiliumEndpoint related events at the same time)
- `initializeMappingCEPtoCES` that is called only before initial sync is completed

So, it should not be possible to have multiple goroutines concurrently reading the CEPs in CES counter and trying to  insert or remove a CEP in a CES. Or am I missing something?

File: operator/pkg/ciliumendpointslice/endpointslice.go (hunk 47 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/endpointslice.go:109]:
```go
func enqueueCES(ces CESName) {
  if c.enqueuedAt[ces].IsZero() {
    c.enqueuedAt[ces] = time.Now()
  }
}

func getAndReset(ces CESName) {
  enqueued, exists := c.enqueuedAt[ces]
  if exists && !enqueued.IsZero() {
    c.enqueuedAt[ces] = time.Time{}
    return time.Since(enqueued).Seconds()
  }
}
```

So when we enqueue a CES and there is no timestamp we set it to current time. When we process the CES and there is a timestamp we reset it and report time.

The conflict and race may happen if we try to enqueue and process a CES in the same time but the result doesn't matter.

Case I: enqueueAt[ces] was not zero before the race.
In this case the result reported from getAndReset will be correct delay.
At the end enqueueAt[ces] may be zero (if getAndReset finished later than enqueue) or time.Now() otherwise. The same can happen if either enqueue happens fully before or after getAndReset so synchronization doesn't change anything.

Case II: enqueueAt[ces] was zero.
In this case race may happen that enqueue first sees it's zero, changes it to time.now() and then getAndReset sees it's not zero, reports the delay and reset it. The same can happen if enqueueAt happens fully before getAndReset.

I don't see a case in which the result without synchronization cannot be achieved with synchronization. I'd rather not add a lock here just to protect queue delay metric.

That said this may be wrong. The code should always show the time really spent in the queue. I'm not sure how to fix it. It would be great to add new field to the queue. However this would break the behavior of not processing the same items multiple times as all entries would be unique now.
We can't also just prepare a queue of enqueued at as not all add will add element to the queue.

I will keep thinking about it.

File: operator/pkg/ciliumendpointslice/controller.go (hunk 50 above)
Comment (pippolo84) [reply operator/pkg/ciliumendpointslice/controller.go]: > I'll try to remove it all together. I think we can start processing the events only after the initial mapping is initialized.

Yep, this sounds better from a readability perspective too. :+1:

File: operator/pkg/ciliumendpointslice/manager.go (hunk 49 above)
Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/manager.go]: Yes. As long as we are sure we cannot process multiple events from the CEP at the same time we are good here. I'm removing those locks for now.

I thought that the CES controller worker also changes mapping but it's not the case, it's:

CEP event => update mapping => enqueue CES => worker processing CESs from the queue
CES event => enqueue CES => the same worker as above processing CESs from the queu

I'll remove the locks.

Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/manager.go]: Removed

**Review by rolinh — APPROVED** [review]
No more vendor changes so the PR lgtm in that respect. Thanks for your contribution!

File: operator/pkg/ciliumendpointslice/endpointslice.go (hunk 47 above)
Comment (pippolo84) [reply operator/pkg/ciliumendpointslice/endpointslice.go:109]: > I don't see a case in which the result without synchronization cannot be achieved with synchronization. I'd rather not add a lock here just to protect queue delay metric.

The write operations themselves (`c.enqueuedAt[ces] = time.Now()` and `c.enqueuedAt[ces] = time.Time{}`) are not atomic. So we can end up with a value in `c.enqueuedAt[ces]` that is neither `time.Now()` nor `time.Time{}`.
That's because `time.Time` is defined as a struct:

```
type Time struct {
	wall uint64
	ext  int64

	loc *Location
}
```

And if that happens, `getAndReset` might return a totally bogus time interval when doing `time.Since(enqueued).Seconds()` the next time is called for the same CES.

Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/endpointslice.go:109]: Added a lock

File: operator/pkg/ciliumendpointslice/endpointslice.go [hunk 51]
```diff
@@ -48,263 +41,223 @@ const (
...
+		}
+	}
+}
+
+func (c *Controller) getAndResetCESProcessingDelay(ces CESName) float64 {
+	enqueued, exists := c.enqueuedAt[ces]
+	if !exists {
+		return 0
+	}
+	c.enqueuedAtLock.Lock()
```
Comment (pippolo84) [inline operator/pkg/ciliumendpointslice/endpointslice.go]: I think we should take the lock before checking the key existence, too. That's because it is possible to have a concurrent write to the `c.enqueuedAt` map at line 109 and that can potentially reallocate the map internal buckets (e.g: think about when the map grows) giving us incorrect results.

Comment (alan-kut) [reply operator/pkg/ciliumendpointslice/endpointslice.go]: Done

**Review by pippolo84 — APPROVED** [review]
Awesome, thanks! :rocket:

**Comment by alan-kut** [comment]
Can we merge it now?

I see two tests are failing now but I don't see how this change can cause it especially when all the tests were passing just moments ago before small review changes.

**Comment by pippolo84** [comment]
ci-ginkgo hit a known [flake](https://github.com/cilium/cilium/issues/13071#issuecomment-1711671271), rerunning.

**Comment by pippolo84** [comment]
> Can we merge it now?
> 
> I see two tests are failing now but I don't see how this change can cause it especially when all the tests were passing just moments ago before small review changes.

Let's wait for the other assigned reviewers to give their feedback. Once the PR has all the approvals and all the tests marked as "Required" have been passed, a repository owner will merge it.
No need to change anything in the meantime.

**Review by asauber — APPROVED** [review]
Config-related changes LGTM. 

A great reference for Hive considerations as well.

**Review by joamaki — APPROVED** [review]
