### PR TITLE
cilium: distributed lru map sizing roundup fixes

### LINKED ISSUE #39009: Node becomes unavailable when enabling bpf-distributed-lru: true on Cilium 1.17.2/1.17.3
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.2 and lower than v1.18.0

### What happened?

When enabling the bpf-distributed-lru: true setting via CiliumNodeConfig, the affected node becomes completely unavailable (kubelet unresponsive, pods inaccessible). This issue is reproducible on Cilium 1.17.2 and 1.17.3, but does not occur on 1.17.1, where the node remains fully functional.

### How can we reproduce the issue?

1. Install Cilium via Helm with the following relevant values:
```yaml
loadBalancer:
  algorithm: maglev
  mode: snat
ipam:
  mode: "kubernetes"
k8s:
  requireIPv4PodCIDR: true
autoDirectNodeRoutes: true
ipv4NativeRoutingCIDR: 10.244.0.0/16
routingMode: native
bandwidthManager:
  enabled: true
  bbr: true 
bpf:
  datapathMode: netkit
  masquerade: true
  hostLegacyRouting: false
  tproxy: true
kubeProxyReplacement: true
```

2. Apply the following CiliumNodeConfig on a single node in the cluster:
```yaml
apiVersion: cilium.io/v2
kind: CiliumNodeConfig
metadata:
  name: new-config
  namespace: kube-system
spec:
  defaults:
    bpf-distributed-lru: "true"
  nodeSelector:
    matchLabels:
      cilium.dats.services/config: new
```
3. Add a new node to the cluster, apply the label that matches the node selector, and reboot the node to ensure that Cilium starts from scratch with the updated configuration. 

4.  Once the node reboots and joins the cluster, it becomes unreachable:

- kubectl times out when accessing pods on that node
- Cilium and kubelet logs stop streaming
- Node shows as “NotReady”
- Removing bpf-distributed-lru: true and restarting the node resolves the issue

### Cilium Version

1.17.2, 1.17.3

### Kernel Version

6.12.18

### Kubernetes Version

1.32.3

### Regression

1.17.1

### Sysdump

_No response_

### Relevant log output

```shell
time="2025-04-17T12:55:11.930877622Z" level=error msg="endpoint regeneration failed" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=8 endpointID=2887 error="attaching cilium_host: loading eBPF collection into the kernel: map cilium_snat_v4_external: map create: cannot allocate memory" identity=1 ipv4= ipv6= k8sPodName=/ subsys=endpoint

time="2025-04-17T12:55:28.582665938Z" level=warning msg="Detected unexpected endpoint BPF program removal. Consider investigating whether other software running on this machine is removing Cilium's endpoint BPF programs. If endpoint BPF programs are removed, the associated pods will lose connectivity and only reinstating the programs will restore connectivity." count=6 subsys=daemon
```
This is the latest lines of log before node gone down

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by borkmann**
(see commit msg)

Closes: https://github.com/cilium/cilium/issues/39009

```release-note
Fix map recreation loop when distributed lru setting is enabled
```

### CODE REVIEW

File: pkg/option/config.go [hunk 1]
```diff
@@ -3655,13 +3660,26 @@ func (c *DaemonConfig) calculateDynamicBPFMapSizes(vp *viper.Viper, totalMemory
...
+	}
+	roundDown := func(x, multiple int) int {
+		return int(x - (x % multiple))
+	}
 	getEntries := func(entriesDefault, min, max int) int {
 		entries := (entriesDefault * memoryAvailableForMaps) / totalMapMemoryDefault
+		entries = roundUp(entries, possibleCPUs)
 		if entries < min {
-			entries = min
+			entries = roundUp(min, possibleCPUs)
```
Comment (tommyp1ckles) [inline pkg/option/config.go]: maybe lets add a note on why we need this rounding logic (i.e. https://elixir.bootlin.com/linux/v6.13.7/source/kernel/bpf/hashtab.c#L496-L506)

File: pkg/option/config.go [hunk 2]
```diff
@@ -45,6 +45,8 @@ import (
 	"github.com/cilium/cilium/pkg/mac"
 	"github.com/cilium/cilium/pkg/time"
 	"github.com/cilium/cilium/pkg/version"
+
+	"github.com/cilium/ebpf"
```
Comment (tklauser) [inline pkg/option/config.go]: nit: I think this import clause should be part of the 2nd import group (external non-stdlib dependencies) above. We generally try to stick to 3 import groups:

1. Go stdlib
2. External non-stdlib dependencies
3. Own module (github.com/cilium/cilium)

File: pkg/option/config_test.go [hunk 3]
```diff
@@ -21,6 +21,8 @@ import (
 	"github.com/cilium/cilium/pkg/cidr"
 	"github.com/cilium/cilium/pkg/defaults"
 	ipamOption "github.com/cilium/cilium/pkg/ipam/option"
+
+	"github.com/cilium/ebpf"
```
Comment (tklauser) [inline pkg/option/config_test.go]: Same here, this should be part of the 2nd import group.

File: pkg/option/config.go (hunk 2 above)
Comment (borkmann) [reply pkg/option/config.go]: thanks, fixed now!

**Review by tklauser — APPROVED** [review]

**Review by ghost — APPROVED** [review]
docs good

**Review by ti-mo — APPROVED** [review]
Thanks! As a minor nit, I'd just make roundUp/Down plain functions so they don't need to be redeclared in tests.

**Review by doniacld — APPROVED** [review]

**Review by tommyp1ckles — APPROVED** [review]

**Review by aditighag — APPROVED** [review]
Nice find! Looks good for my CODEOWNERS.
