### PR TITLE
Address ipcache startup perfomance regression

### LINKED ISSUE #24987: Extremely slow agent startup
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. Rolling upgrade to v1.12.9
2. each cilium agent pod is not ready for 2-3m

### Cilium Version

`1.12.9 e0bb30a 2023-04-17T23:54:19+02:00 go version go1.18.10 linux/amd64`

### Kernel Version

`Linux ip-10-200-14-243 5.15.0-1033-aws #37~20.04.1-Ubuntu SMP Fri Mar 17 11:39:30 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

`v1.22.17-eks-48e63af`

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

When startup is slow, it correlates with cluster size (some clusters don't have this issue)

For the time until cilium starts, all I get is:
```
# cilium status
Get "http:///var/run/cilium/cilium.sock/v1/healthz": dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
Is the agent running?
```

I do see a bunch of `clang` and `tc` commands running in the background during this time.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bimmlerd**
The commit messages should be descriptive, here's the summary line for each.

1. ipcache: add benchmark for Upsert (`regression.txt` below)
2. ipcache: make NamedPortMultiMap an interface (`interface.txt` below)
3. ipcache: switch named ports to reference counting (`fix.txt` below)
4. ipcache: simplify the named ports update code (`cleanup.txt` below)

The following is a comparison of running the benchmark added in commit 1 over the course of the four commits.

```
goos: linux
goarch: arm64
pkg: github.com/cilium/cilium/pkg/ipcache
                      │ regression.txt │             interface.txt             │               fix.txt               │             cleanup.txt             │
                      │     sec/op     │     sec/op      vs base               │   sec/op     vs base                │   sec/op     vs base                │
IPCacheUpsert10-10        97.10µ ±  3%     94.58µ ±  3%       ~ (p=0.052 n=10)   48.84µ ± 5%  -49.70% (p=0.000 n=10)   47.59µ ± 5%  -50.98% (p=0.000 n=10)
IPCacheUpsert100-10      2672.3µ ±  5%    2718.4µ ±  8%       ~ (p=0.481 n=10)   508.3µ ± 5%  -80.98% (p=0.000 n=10)   485.0µ ± 2%  -81.85% (p=0.000 n=10)
IPCacheUpsert1000-10     69.543m ± 13%    66.515m ± 17%       ~ (p=0.481 n=10)   5.282m ± 5%  -92.40% (p=0.000 n=10)   5.056m ± 2%  -92.73% (p=0.000 n=10)
IPCacheUpsert10000-10   4166.59m ±  1%   4299.95m ±  2%  +3.20% (p=0.000 n=10)   48.63m ± 5%  -98.83% (p=0.000 n=10)   44.87m ± 5%  -98.92% (p=0.000 n=10)
geomean                   16.56m           16.47m        -0.55%                  1.589m       -90.40%                  1.513m       -90.86%
```

The last commit, `cleanup.txt` removes some now redundant work, and hence gets a mild speedup. If preferred, it can be squashed into the third commit, but like this the algorithmic changes are easier to understand.

```
goos: linux
goarch: arm64
pkg: github.com/cilium/cilium/pkg/ipcache
                      │   fix.txt   │            cleanup.txt             │
                      │   sec/op    │   sec/op     vs base               │
IPCacheUpsert10-10      48.84µ ± 5%   47.59µ ± 5%       ~ (p=0.165 n=10)
IPCacheUpsert100-10     508.3µ ± 5%   485.0µ ± 2%  -4.58% (p=0.005 n=10)
IPCacheUpsert1000-10    5.282m ± 5%   5.056m ± 2%  -4.28% (p=0.011 n=10)
IPCacheUpsert10000-10   48.63m ± 5%   44.87m ± 5%  -7.74% (p=0.009 n=10)
geomean                 1.589m        1.513m       -4.81%
```

Note that simply reverting 93cd67f2994a618865fbcdb0294bcd9b4d44036a is not actually a fix, as the quadratic behaviour still lurks. This can be observed by forcefully setting `ipcache.needNamedPorts = true` when benchmarking:

```
                      │ main-head.txt  │    revert-with-neednamedports.txt     │ 
                      │     sec/op     │     sec/op      vs base               │  
IPCacheUpsert10-10        95.00µ ±  5%     92.12µ ±  3%  -3.04% (p=0.000 n=10)   
IPCacheUpsert100-10      2729.7µ ±  4%    2617.5µ ± 12%       ~ (p=0.165 n=10)   
IPCacheUpsert1000-10     70.192m ± 11%    68.974m ± 10%       ~ (p=0.579 n=10)   
IPCacheUpsert10000-10   4247.52m ±  3%   4233.62m ±  1%       ~ (p=0.853 n=10)   
geomean                   16.68m           16.29m        -2.31%                 
```

Fixes: #24987 

```release-note
Address cilium-agent startup performance regression.
```

### CODE REVIEW

File: pkg/ipcache/ipcache_test.go [hunk 1]
```diff
@@ -553,6 +556,83 @@ func (s *IPCacheTestSuite) TestIPCacheNamedPorts(c *C) {
...
+
+func BenchmarkIPCacheUpsert1000(b *testing.B) {
+	benchmarkIPCacheUpsert(1000, b)
+}
+
+func BenchmarkIPCacheUpsert10000(b *testing.B) {
+	benchmarkIPCacheUpsert(10000, b)
+}
+
+func benchmarkIPCacheUpsert(num int, b *testing.B) {
```
Comment (christarazi) [inline pkg/ipcache/ipcache_test.go]: Nit: Maybe `b` should be the first argument in case we need to adjust this in the future, it makes more sense to have `b` be first and the rest of the params follow

File: pkg/ipcache/ipcache_test.go [hunk 2]
```diff
@@ -553,6 +556,83 @@ func (s *IPCacheTestSuite) TestIPCacheNamedPorts(c *C) {
...
+		ctx, cancel = context.WithCancel(context.Background())
+		allocator := testidentity.NewMockIdentityAllocator(nil)
+		ipcache = NewIPCache(&Configuration{
+			Context:           ctx,
+			IdentityAllocator: allocator,
+			PolicyHandler:     &mockUpdater{},
+			DatapathHandler:   &mockTriggerer{},
+			NodeHandler:       &mockNodeHandler{},
+		})
+		b.StartTimer()
```
Comment (christarazi) [inline pkg/ipcache/ipcache_test.go]: Nit: Why not put the `StartTimer` at the start of the for loop iteration and keep the `StopTimer` where it is? Seems a bit strange to put the start at the bottom of the loop iteration, even though the iteration will start back up again when the loop reaches the end.

File: pkg/types/portmap.go [hunk 3]
```diff
@@ -31,7 +33,7 @@ type PortProto struct {
 type NamedPortMap map[string]PortProto
 
 // PortProtoSet is a set of unique PortProto values.
-type PortProtoSet map[PortProto]struct{}
+type PortProtoSet counter.Counter[PortProto]
```
Comment (christarazi) [inline pkg/types/portmap.go:36]: What's the plan for the backport as this uses generics?

**Review by christarazi — COMMENTED** [review]
Thanks for the fix, nice work! The fix looks good to me, I have a few minor questions below. 

Just a nit on the commit msg: technically the namedport map is not the only lock being held while it's locked; the ipcache lock is always held before the namedport map lock is taken. Actually, it seems like we should "promote" this relationship to say that the ipcache lock must be taken before the namedport map.

File: pkg/types/portmap.go (hunk 3 above)
Comment (bimmlerd) [reply pkg/types/portmap.go:36]: I was thinking we can use something akin to https://github.com/cilium/cilium/blob/v1.12/pkg/counter/string.go. It'll be yet another custom-ish backport, but I think it's worth having the nicer version on main.

Comment (christarazi) [reply pkg/types/portmap.go:36]: I've marked the PR with `backport/author` for you to take care of the backport due to the above.

**Comment by bimmlerd** [comment]
> technically the namedport map is not the only lock being held while it's locked; the ipcache lock is always held before the namedport map lock is taken. Actually, it seems like we should "promote" this relationship to say that the ipcache lock must be taken before the namedport map.

What I was trying to express in the commit message was that we don't _acquire_ a new lock while holding the namedport mutex (M), and hence don't establish any relations of the form M > X, for any X. I think that's correct. But yes, we do hold the ipcache mutex while acquiring the namedport mutex, and establish IPCache > M. This is precisely why it's crucial to not acquire any other mutex while also holding M.

Tests were green before pushing to clarify the commitmsg and fix a cosmetic issue in the benchmark, but more reruns can't hurt.

**Comment by bimmlerd** [comment]
/test-1.25-5.4

File: pkg/ipcache/ipcache.go [hunk 4]
```diff
@@ -244,44 +244,6 @@ func (ipc *IPCache) getK8sMetadata(ip string) *K8sMetadata {
...
-		ipc.namedPorts.Store(&npm)
-	}
-
-	// Set namedPortsChanged to false if they have not (yet) been requested.
-	// This avoids triggering policy updates if named ports changed, but no
-	// policy actually needs them. We still pre-compute the namedPorts map,
-	// so we don't have to acquire the IPCache lock in GetNamedPorts
-	if !ipc.needNamedPorts.Load() {
-		namedPortsChanged = false
-	}
```
Comment (gandro) [inline pkg/ipcache/ipcache.go:281]: This has been removed, where as the corresponding `Store` is still there in `GetNamedPorts` which is now dead code.

I'm a bit torn on how to tackle this (should we remove the boolean? should we keep it?). The comment here is still valid, i.e. by keeping this boolean we avoid re-triggering policies after namedPort changes if no policy ever used namedPorts. 

But as I understand now, even before this PR we were potentially triggering unnecessary policy updates if a namedPorts policy was added and then later removed (since this is never set back to false). This makes me wonder how necessary this flag here is in the first place, i.e. how expensive is it to trigger policy updates if no policy is using named ports?

File: pkg/ipcache/ipcache_test.go [hunk 5]
```diff
@@ -604,9 +621,10 @@ func benchmarkIPCacheUpsert(b *testing.B, num int) {
 			DatapathHandler:   &mockTriggerer{},
 			NodeHandler:       &mockNodeHandler{},
 		})
+
+		b.StartTimer()
+		// We only want to measure the call to upsert.
```
Comment (gandro) [inline pkg/ipcache/ipcache_test.go]: Why this change?

File: pkg/types/portmap.go [hunk 6]
```diff
@@ -47,21 +49,82 @@ func (pps PortProtoSet) Equal(other PortProtoSet) bool {
...
+func NewNamedPortMultiMapUpdater() NamedPortMultiMapUpdater {
+	return &namedPortMultiMap{
+		m: make(map[string]PortProtoSet),
 	}
-	for name, ports := range npm {
-		if otherPorts, exists := other[name]; !exists || !ports.Equal(otherPorts) {
-			return false
+}
+
+func (npm *namedPortMultiMap) Get(name string) (PortProtoSet, bool) {
```
Comment (gandro) [inline pkg/types/portmap.go]: This looks off. We're handing out a reference to `PortProtoSet` here, which I think allows consumers of this function to read (or even write) to the `PortProtoSet` without holding `npm.RWMutex`, which would be racy.

The good news is that I don't see any usage of this function, so we probably can just remove it?

**Review by gandro — CHANGES_REQUESTED** [review]
Awesome work, thanks for taking care of this! :pray: 

There is one issue around `ipc.needNamedPorts` and the externally visible behavior that I'm not sure how to address, see inline comment.

File: pkg/ipcache/ipcache_test.go (hunk 5 above)
Comment (gandro) [reply pkg/ipcache/ipcache_test.go]: Ah, I just noticed https://github.com/cilium/cilium/pull/25007#discussion_r1172817804

Might be worth moving this change into the first commit.

File: pkg/types/portmap.go (hunk 6 above)
Comment (bimmlerd) [reply pkg/types/portmap.go]: Yeah - I realised the problem with it as well, and removed it form the interface but forgot to remove the implementation :facepalm: Fixing.

File: pkg/ipcache/ipcache.go (hunk 4 above)
Comment (bimmlerd) [reply pkg/ipcache/ipcache.go:281]: I've pushed a fixup 56a943c93b1d7a55a212eaa4e5024fb7fb25ef14 which shows the changes needed to keep the boolean, I think it's probably worth it as it doesn't increase the code complexity much and may save some computation.

But yes, we've never set this back to false, so it might not be the most effective of optimisations.

File: pkg/ipcache/ipcache.go [hunk 7]
```diff
@@ -419,8 +419,10 @@ func (ipc *IPCache) upsertLocked(
 			ipc.ipToK8sMetadata[ip] = *k8sMeta
 		}
 
-		// Check whether named ports have changed.
+		// Update the named ports reference counting, but don't cause policy recomputation of no
+		// policy uses the named ports feature.
 		namedPortsChanged = ipc.namedPorts.Update(oldK8sMeta.NamedPorts, newNamedPorts)
+		namedPortsChanged = namedPortsChanged && ipc.needNamedPorts.Load()
```
Comment (gandro) [inline pkg/ipcache/ipcache.go:426]: I think `deleteLocked` needs the same `ipc.needNamedPorts.Load` here as well? Otherwise we would trigger policy whenever a named port is deleted.

File: pkg/ipcache/ipcache.go (hunk 4 above)
Comment (gandro) [reply pkg/ipcache/ipcache.go:281]: > I think it's probably worth it as it doesn't increase the code complexity much and may save some computation.

Agreed. Let's keep it to avoid further changing behavior on stable branches, especially since we backport this. I've left one comment on the fixup commit.

File: pkg/ipcache/ipcache.go (hunk 7 above)
Comment (bimmlerd) [reply pkg/ipcache/ipcache.go:426]: Very true. fixed and squashed.

File: pkg/types/portmap.go [hunk 8]
```diff
@@ -47,21 +49,75 @@ func (pps PortProtoSet) Equal(other PortProtoSet) bool {
...
+			c = make(PortProtoSet)
+			npm.m[name] = c
+		}
+		if c.Add(port) {
+			namedPortsChanged = true
 		}
 	}
-	return true
+	for name, port := range old {
+		if PortProtoSet(npm.m[name]).Delete(port) {
```
Comment (gandro) [inline pkg/types/portmap.go]: nit: The `PortProtoSet()` type conversion here is a no-op.

File: pkg/types/portmap.go [hunk 9]
```diff
@@ -47,21 +49,75 @@ func (pps PortProtoSet) Equal(other PortProtoSet) bool {
...
+			delete(npm.m, name)
```
Comment (gandro) [inline pkg/types/portmap.go]: I don't think this is right. Even if we deleted a port, there might be other (non-conflicting) ports with the same name. We only should do a `delete(npm.m, name)` if `len(npm.m) == 0`.

Here's a unit test to demonstrate what I mean:

It fails at the end, because `http=8080:UDP` is no longer present, even though it has not been deleted.
```go

func (ds *PortsTestSuite) TestPolicyNamedPortMultiMapUpdate(c *C) {
	npm := NewNamedPortMultiMapUpdater()

	pod1PortsOld := map[string]PortProto{}
	pod1PortsNew := map[string]PortProto{
		"http": {80, uint8(u8proto.TCP)},
	}

	// Insert http=80/TCP from pod1
	changed := npm.Update(pod1PortsOld, pod1PortsNew)
	c.Assert(changed, Equals, true)

	// No changes
	changed = npm.Update(pod1PortsNew, pod1PortsNew)
	c.Assert(changed, Equals, false)

	// Assert http=80/TCP
	port, err := npm.GetNamedPort("http", uint8(u8proto.TCP))
	c.Assert(err, IsNil)
	c.Assert(port, Equals, uint16(80))

	pod2PortsOld := map[string]PortProto{}
	pod2PortsNew := map[string]PortProto{
		"http": {8080, uint8(u8proto.UDP)},
	}

	// Insert http=8080/UDP from pod2, retain http=80/TCP from pod1
	changed = npm.Update(pod2PortsOld, pod2PortsNew)
	c.Assert(changed, Equals, true)

	port, err = npm.GetNamedPort("http", uint8(u8proto.TCP))
	c.Assert(err, IsNil)
	c.Assert(port, Equals, uint16(80))
	port, err = npm.GetNamedPort("http", uint8(u8proto.UDP))
	c.Assert(err, IsNil)
	c.Assert(port, Equals, uint16(8080))

	// Delete http=80/TCP from pod1, retain http=8080/UDP from pod2
	pod1PortsOld = pod1PortsNew
	pod1PortsNew = map[string]PortProto{}

	// Delete http=80/TCP from pod1
	changed = npm.Update(pod1PortsOld, pod1PortsNew)
	c.Assert(changed, Equals, true)

	port, err = npm.GetNamedPort("http", uint8(u8proto.UDP))
	c.Assert(err, IsNil)
	c.Assert(port, Equals, uint16(8080))
}
```

**Review by gandro — CHANGES_REQUESTED** [review]
Thanks! Starting to look good overall. I found one bug that I think does not match the expected semantics I think

**Review by joestringer — COMMENTED** [review]
I perused this PR for a while, but I had a bit of trouble pinpointing the key algorithm changes in the code given that the main commit here contains a fair bit of refactoring as well as the logic change. It seems like you and @gandro have a handle on it, so I'm inclined to leave it be, but if it's at all possible to split refactoring and key changes into separate commits, that would help subsequent review and debugging if we ever have to go back and `git bisect` this change. I briefly tried to do this, but I could only identify that the `pkg/ipcache/ipcache_test.go` changes could be isolated into a dedicated commit, and that didn't really help with understanding the code. I'll put this down for now but shout if you think this needs more close attention.

**Comment by bimmlerd** [comment]
> but if it's at all possible to split refactoring and key changes into separate commits, that would help subsequent review and debugging if we ever have to go back and `git bisect` this change.

@joestringer It took a bit of doing, but I've split the changes up into four commits, see the edited PR description or the commit messages. I hope the changes are a bit clearer now, thanks for the suggestion. PTAL.

File: pkg/types/portmap.go (hunk 9 above)
Comment (bimmlerd) [reply pkg/types/portmap.go]: Nice catch. Added the testcase, fixed the problem - PTAL.

**Comment by bimmlerd** [comment]
Previous CI failures triage:
- Cilium-PR-K8s-1.25-kernel-5.4 failed with https://github.com/cilium/cilium/issues/24966
- Cilium-PR-K8s-1.27-kernel-net-next failed with something I haven't seen before - creating an issue.

File: pkg/types/portmap.go [hunk 10]
```diff
@@ -49,21 +49,38 @@ func (pps PortProtoSet) Equal(other PortProtoSet) bool {
...
+	return make(namedPortMultiMap)
+}
+
+type namedPortMultiMap map[string]PortProtoSet
 
 // Equal returns true if the NamedPortMultiMaps are equal.
-func (npm NamedPortMultiMap) Equal(other NamedPortMultiMap) bool {
-	if len(npm) != len(other) {
+func (npm namedPortMultiMap) Equal(other NamedPortMultiMap) bool {
+	o, ok := other.(namedPortMultiMap)
```
Comment (ldelossa) [inline pkg/types/portmap.go]: This strikes me as a bit odd. 

You take an interface in, but you pretty much force the interface to be a concrete type for comparison. 

Is this desired? If expose a way to obtain the {name, port} tuples in a generic way, then you can avoid the forcing the a type within the interface method implementation.

File: pkg/types/portmap.go [hunk 11]
```diff
@@ -47,38 +49,75 @@ func (pps PortProtoSet) Equal(other PortProtoSet) bool {
...
 	GetNamedPort(name string, proto uint8) (uint16, error)
 	// Len returns the number of Name->PortProtoSet mappings known.
 	Len() int
-	Equal(other NamedPortMultiMap) bool
 }
 
-func NewNamedPortMultiMap() namedPortMultiMap {
-	return make(namedPortMultiMap)
+// NamedPortMultiMapUpdater allows for mutation of the NamedPortMultiMap, and is
+// intended for ipcache internal usage.
```
Comment (ldelossa) [inline pkg/types/portmap.go]: `intended for ipcache internal usage` makes me wonder why this is not in `ipcache` package and why its exported?

**Review by ldelossa — APPROVED** [review]
Overall code looks good. Just a few things that made me scratch my head while reading. Don't think either are worth blocking the PR on.

File: pkg/types/portmap.go (hunk 10 above)
Comment (joestringer) [reply pkg/types/portmap.go]: Yeah, slightly odd but it looks like this is an intermediate state in the PR which is useful for transitioning to a subsequent implementation, and it's deleted by the end. There should be no risk of falsely asserting the wrong type :+1:

File: pkg/ipcache/ipcache.go
Comment (joestringer) [inline pkg/ipcache/ipcache.go:1]: nit, commit message:

`Fixes: 93cd67f2994a618865fbcdb0294bcd9b4d44036a`

It's typically more common to use this format to give more context while still disambiguating longer hashes:

```
$ git log --oneline --pretty='Fixes: %h ("%s")' -1 93cd67f2994a618865fbcdb0294bcd9b4d44036a
Fixes: 93cd67f2994a ("ipcache: fix potential deadlock in GetNamedPorts")
```

(Personally I just put this in a special alias in my `.gitconfig`  `[pretty]` section to format this)

**Review by joestringer — APPROVED** [review]
Thanks, I didn't quite understand the role of the last patch until you split it up here. LGTM :+1:

File: pkg/ipcache/ipcache.go
Comment (christarazi) [reply pkg/ipcache/ipcache.go:1]: (Oh nice tip! I'll steal that :slightly_smiling_face:)

File: pkg/types/portmap.go (hunk 10 above)
Comment (ldelossa) [reply pkg/types/portmap.go]: Yup, reviewed this per commit, so this is even marked as outdated. Resolving

File: pkg/types/portmap.go [hunk 12]
```diff
@@ -47,38 +49,75 @@ func (pps PortProtoSet) Equal(other PortProtoSet) bool {
...
+		}
+		if c.Add(port) {
+			namedPortsChanged = true
+		}
 	}
-	for name, ports := range npm {
-		if otherPorts, exists := o[name]; !exists || !ports.Equal(otherPorts) {
-			return false
+	for name, port := range old {
+		namedPortsChanged = npm.m[name].Delete(port) || namedPortsChanged
```
Comment (gandro) [inline pkg/types/portmap.go]: tiny nit: I _think_ we only need to check the len if `npm.m[name].Delete(port)` returned true. I don't think there is any other condition when it would be zero.

```go
	if npm.m[name].Delete(port) {
		namedPortsChanged = true
		if len(npm.m[name]) == 0 {
			delete(npm.m, name)
		}
	}
```

(As a bonus point, it would bring back the aestethic symmetry with Add, which uses an `if`-statement instead of `||` to set `namedPortsChanged`)

**Review by gandro — APPROVED** [review]
Awesome! One tiny optional nit, besides the things already pointed out by the other reviewers

**Comment by gandro** [comment]
Removing the ready-to-merge label till David had time to look at the optional feedback. Feel free to re-add it you don't plan further changes.

File: pkg/ipcache/ipcache.go
Comment (bimmlerd) [reply pkg/ipcache/ipcache.go:1]: Good to know - fixed and +1 on the alias :)

File: pkg/types/portmap.go (hunk 12 above)
Comment (bimmlerd) [reply pkg/types/portmap.go]: I agree, looks better and passes tests, changed. Thanks!

File: pkg/types/portmap.go (hunk 11 above)
Comment (bimmlerd) [reply pkg/types/portmap.go]: Good point, fixed.

**Review by gandro — APPROVED** [review]

**Comment by bimmlerd** [comment]
/test-1.24-5.4

**Comment by bimmlerd** [comment]
/test-1.25-4.19

**Comment by bimmlerd** [comment]
/test-1.24-5.4

**Comment by bimmlerd** [comment]
/test-1.26-net-next

**Comment by bimmlerd** [comment]
CI triage:
- k8s-1.26-kernel-net-next (test-1.26-net-next) failed with https://github.com/cilium/cilium/issues/24687 (we don't have the fix commit 0691784961b76be4cc93f3d7489ec55166a60ebe)

I'll gamble one rerun and otherwise rebase and run it all again

**Comment by bimmlerd** [comment]
/test-1.26-net-next
