### PR TITLE
Fix Endpoint delete request processing during agent startup

### LINKED ISSUE #39370: Endpoint restoration/regeneration of completed job stuck in infinite loop (error="retrieving device lxc*: Link not found")
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.3 and lower than v1.18.0

### What happened?

Hit in a CI run: https://github.com/cilium/cilium/actions/runs/14863456177/job/41734848140

Essentially, one of the Cilium agents is stuck attempting to restore the endpoint of a job that most likely completed right before or while the Cilium agent on the hosting node got restarted, and fails because the corresponding link no longer exists.

```
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                                    IPv6                  IPv4           STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                                                      
1362       Disabled           Disabled          16756690   k8s:batch.kubernetes.io/job-name=clustermesh-apiserver-generate-certs          fd00:10:244:2::917d   10.244.2.44    not-ready   
                                                           k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system                                                      
                                                           k8s:io.cilium.k8s.policy.cluster=cluster2-with-long-name-01234567                                                               
                                                           k8s:io.cilium.k8s.policy.serviceaccount=clustermesh-apiserver-generate-certs                                                    
                                                           k8s:io.kubernetes.pod.namespace=kube-system                                                                                     
                                                           k8s:job-name=clustermesh-apiserver-generate-certs                                                                               
                                                           k8s:k8s-app=clustermesh-apiserver-generate-certs                                                                                
```

```
2025-05-06T15:36:41.438279873Z level=error source=/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:610 msg="Error while reloading endpoint BPF program" ipv4=10.244.2.44 containerInterface=eth0 k8sPodName=kube-system/clustermesh-apiserver-generate-certs-4kgkm containerID=5072ef6b95 desiredPolicyRevision=1 endpointID=1362 datapathPolicyRevision=0 ipv6=fd00:10:244:2::917d ciliumEndpointName=kube-system/clustermesh-apiserver-generate-certs-4kgkm identity=16756690 subsys=endpoint error="retrieving device lxc863c5237af4c: Link not found"
2025-05-06T15:36:41.438747716Z level=warn source=/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:607 msg="Regeneration of endpoint failed" ipv4=10.244.2.44 containerInterface=eth0 k8sPodName=kube-system/clustermesh-apiserver-generate-certs-4kgkm containerID=5072ef6b95 desiredPolicyRevision=1 endpointID=1362 datapathPolicyRevision=0 ipv6=fd00:10:244:2::917d ciliumEndpointName=kube-system/clustermesh-apiserver-generate-certs-4kgkm identity=16756690 subsys=endpoint reason="syncing state to host" waitingForPolicyRepository=361ns prepareBuild=28.113µs total=12.088630966s waitingForLock=4.809098796s proxyConfiguration=0s proxyPolicyCalculation=980.03µs mapSync=0s bpfCompilation=6.854898416s bpfWaitForELF=6.870777505s waitingForCTClean=391ns selectorPolicyCalculation=0s endpointPolicyCalculation=0s proxyWaitForAck=0s policyCalculation=413.032µs bpfLoadProg=405.58053ms bpfCompilation=6.854898416s bpfWaitForELF=6.870777505s bpfLoadProg=405.58053ms error="retrieving device lxc863c5237af4c: Link not found"
2025-05-06T15:36:41.439164485Z level=error source=/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:803 msg="endpoint regeneration failed" ipv4=10.244.2.44 containerInterface=eth0 k8sPodName=kube-system/clustermesh-apiserver-generate-certs-4kgkm containerID=5072ef6b95 desiredPolicyRevision=1 endpointID=1362 datapathPolicyRevision=0 ipv6=fd00:10:244:2::917d ciliumEndpointName=kube-system/clustermesh-apiserver-generate-certs-4kgkm identity=16756690 subsys=endpoint error="retrieving device lxc863c5237af4c: Link not found"
2025-05-06T15:37:10.223490385Z level=warning msg="Unable to assert if endpoint BPF programs need to be reloaded" source="/go/src/github.com/cilium/cilium/daemon/cmd/watchdogs.go:115" ciliumEndpointName=kube-system/clustermesh-apiserver-generate-certs-4kgkm endpoint=lxc863c5237af4c endpointID=1362 error="retrieving device lxc863c5237af4c: Link not found" subsys=daemon
```

### How can we reproduce the issue?

Haven't attempted reproducing locally yet, but I assume restating the Cilium agent while a job completes should trigger it.

### Cilium Version

Hit on tip of main, unsure whether this affects any stable version as well.

### Sysdump

[cilium-sysdump-context2-final-2-disabled-dual-wireguard-none-clustermesh-cronJob-migration-migration-511-disabled.zip](https://github.com/user-attachments/files/20066941/cilium-sysdump-context2-final-2-disabled-dual-wireguard-none-clustermesh-cronJob-migration-migration-511-disabled.zip)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by fristonio**
This PR fixes an issue in the Endpoint API's delete request
processing during cilium-agent startup.
Currently, when cilium-agent boots up, the API server is started first
which allows CNI to interact with the endpoint subsystem. This exposes
endpoint APIs like `Put`, `Delete` to CNI plugin without waiting for
initial state restore to complete.
This leads to a stituation where CNI plugin can request Delete for an
endpoint that is not yet restored and exposed to EndpointManager. In
such cases cilium-agent will respond with `NotFound` error to CNI.
Currently, the CNI plugin ignores all errors in the delete path and
continues to clean up corresponding resources for the endpoint(eg.Link),
reporting success back to kubelet. When eventually endpoint restore
finishes regeneration fails for these endpoints, because the underlying
resources(eg. Link) no longer exist.

This patch fixes the issue by coordinating endpoint restore handling
with API requests processing for endpoint subsystem. With this patch,
the API server responds with a special 503(Service Unavailble) http
error for requests when the state restore is in progress. CNI
appropriately handles this error code by persisting the delete request
on the disk before cleaning up the associated resources. Once the state
restore is complete, this persisted deletion requests are replayed and
all pending deletes are processed.

With this patch the end-to-end flow for interaction between CNI plugin
and agent during startup behaves as follows:

* Agent is down:
  * Connection to API server fails. CNI plugin persists DELs on disk.
* Agent is up; API server is started:
  * Server responds with 503 for endpoint API requests.
  * CNI processes and persists DELs on disk; ADDs are rejected.
* Agent is up; API Server is up; Bootstrap in progress
  * Endpoint state is restored from the disk and exposed to EndpointManager.
* Agent is up; API Server is up; Bootstrap completed:
  * API accepts DELs but still rejects ADDs
  * Deletion Queue handler processes persisted DELs from disk.
* Agent is up; API Server is up; Bootstrap completed; DeletionQueue drained:
  * API is fully functional
* Regeneration is triggered for all alive restored endpoints.

Fixes: #39370

```release-note
Fix a bug where cilium-agent would report "Link not found" for an endpoint deleted during state restore after cilium-agent restart.
```

### CODE REVIEW

File: plugins/cilium-cni/lib/deletion_queue.go [hunk 1]
```diff
@@ -138,7 +141,18 @@ func (dc *DeletionFallbackClient) EndpointDelete(id string) error {
...
+		if !ok || !status.IsCode(http.StatusServiceUnavailable) {
+			return err
+		}
+
+		// Fallback to queuing endpoint delete if cilium Endpoint service is unavailable.
+		// Once ready, cilium-agent will process all the pending deletes in this queue.
+		dc.logger.Warn(
+			"Received ServiceUnavailable response from server, queuing delete request to be processed later",
+			logfields.Request, req,
+		)
```
Comment (marseel) [inline plugins/cilium-cni/lib/deletion_queue.go]: I'm not 100% sure it will work. 
Based on:
https://github.com/cilium/cilium/blob/a5952a8867b470cbd7a689977e6c32399ee36b71/plugins/cilium-cni/lib/deletion_queue.go#L44
it seems to me that `lockfile` below will be always nil in this case. 
So if we get connection working, but request returns 503, lockfile will be empty and we will never queue deletion?

Comment (fristonio) [reply plugins/cilium-cni/lib/deletion_queue.go]: Ah yes, thats right. Seems like I missed re-acquiring the lock before exiting the `if`. I am working on adding tests for the changes, will fix this behavior.

**Comment by joestringer** [comment]
Would it make sense to clarify the release note to make it more obvious to users what the change in behavior is? Below is a suggestion from my current understanding of the impact:

```
Fix a bug where cilium-agent would report "Link not found" for a Pod that has been deleted during cilium-agent restart
```

File: daemon/cmd/state.go [hunk 2]
```diff
@@ -304,57 +300,36 @@ func (d *Daemon) regenerateRestoredEndpoints(state *endpointRestoreState, endpoi
...
-			// The host endpoint was handled above.
-			continue
-		}
-		d.logger.Info(
-			"Successfully restored endpoint. Scheduling regeneration",
-			logfields.EndpointID, ep.ID,
-		)
-		go func(ep *endpoint.Endpoint, epRegenerated chan<- bool) {
+			// To support v1.18 VinE upgrades, we need to restore the host
+			// endpoint before any other endpoint, to ensure a drop-less upgrade.
```
Comment (joestringer) [inline daemon/cmd/state.go:308]: How is the host endpoint restored before the other endpoints?

**Comment by fristonio** [comment]
> ```
> Fix a bug where cilium-agent would report "Link not found" for a Pod that has been deleted during cilium-agent restart
> ```

Yeah, this sounds good. Fixed the release note with a minor update to attribute the issue to `cilium-agent state restore after restart` instead of just restart.

File: daemon/cmd/state.go [hunk 3]
```diff
@@ -375,35 +350,59 @@ func (d *Daemon) regenerateRestoredEndpoints(state *endpointRestoreState, endpoi
...
-				if buildSuccess {
-					regenerated++
-				}
-				total++
-				if total >= len(state.restored) {
-					break
-				}
-			}
+	// Trigger regeneration for relevant restored endopints in a separate goroutine.
+	go d.handleRestoredEndpointsRegeneration(endpointsToRegenerate, endpointsRegenerator)
```
Comment (joestringer) [inline daemon/cmd/state.go]: Would you mind splitting the refactoring out into a separate commit? This would help to make the review a bit easier. I struggled a bit to understand which parts of the commit were related to the bugfix and which parts were innocently shuffling code to improve style/reuse.

For instance for this case, I understand that the tail end of this function is being modified to do extra work before closing the 'restore complete' channel, but since there's a new function being introduced it makes this hunk quite big. If instead there was first a commit that created this `d.handleRestoredEndpointsRegeneration()` function with the current implementation, and then subsequently a separate commit just changed the logic, there would be fewer details to track.

File: api/v1/openapi.yaml
Comment (joestringer) [inline api/v1/openapi.yaml:1]: Incidentally I think it would also help to split all of the API-related changes into their own commit, to ease review. We can introduce the API first, then subsequently use that new API.

File: daemon/cmd/state.go [hunk 4]
```diff
@@ -375,35 +350,59 @@ func (d *Daemon) regenerateRestoredEndpoints(state *endpointRestoreState, endpoi
...
+}
+
+// This method is called during daemon start to asynchronously handle regeneration for restored
+// endpoints. We assume that all the endpoints for which regeneration is requested are
+// already exposed to EndpointManager.
+// This method is responsible for listening/waiting on relevant signals from other subsystems
+// and only performing regeneration for alive endpoints.
```
Comment (joestringer) [inline daemon/cmd/state.go]: I like the part about the declared assumptions, that context is helpful for readers.

nit: I find the mention of "relevant signals" a bit vague and obscures one of the most important aspects of the function. I'd suggest either deciding this is not relevant in the comment and omitting this sentence, or make it more clear to readers. Suggested alternative below.

One more minor nit to declare the other critical aspect of the operation of this function.

```suggestion
//
// This method assumes that all the endpoints for which regeneration is requested are
// already exposed to EndpointManager. It waits until the Endpoint DeletionQueue is
// drained before regenerating all remaining live endpoints.
//
// Once complete, this method closes the daemon 'endpointRestoreComplete' channel.
```

File: daemon/cmd/state.go [hunk 5]
```diff
@@ -375,35 +350,59 @@ func (d *Daemon) regenerateRestoredEndpoints(state *endpointRestoreState, endpoi
...
-				total++
-				if total >= len(state.restored) {
-					break
-				}
-			}
+	// Trigger regeneration for relevant restored endopints in a separate goroutine.
+	go d.handleRestoredEndpointsRegeneration(endpointsToRegenerate, endpointsRegenerator)
+}
+
+// This method is called during daemon start to asynchronously handle regeneration for restored
```
Comment (joestringer) [inline daemon/cmd/state.go]: nit: Function comments should describe the function itself, not the caller. The caller can always change, and that often happens without updating the function comments. This can make the comments misleading and confusing, which is often worse than having no comments.

```suggestion
// Trigger asynchronous regeneration of restored endpoints.
```

**Review by joestringer — DISMISSED** [review]
I did a very rough initial review pass but I didn't think deeply about the solution in this review. There's a few comments below of things that stood out.

File: daemon/cmd/state.go (hunk 2 above)
Comment (fristonio) [reply daemon/cmd/state.go:308]: My understanding is that we only want to synchronously regenerate the host endpoint if IPSec is enabled. We do this within this if cond.
`ep.RegenerateAfterRestore(endpointsRegenerator, d.endpointMetadata.FetchK8sMetadataForEndpoint)`.

When IPsec is disabled host endpoint regeneration happens in the same path as other local endpoints. So the behavior is identical to what we had before.

File: daemon/cmd/state.go (hunk 3 above)
Comment (fristonio) [reply daemon/cmd/state.go]: Yeah, thats a good point. I will refactor the changes in this PR to smaller, reviewable chunks.

File: daemon/cmd/state.go (hunk 2 above)
Comment (joestringer) [reply daemon/cmd/state.go:308]: Ah right, I just got a bit lost in the way the logic was shifted around. It's clearer opening up in an editor than in the diff. :+1:

**Comment by squeed** [comment]
Lets document the exact timing here somewhere in a README.md, so we can make it more explicit.

Here's how it's supposed to work, back in #23486:

0. Agent goes down
1. CNI plugin fails to connect to gRPC socket. It takes a lockfile and writes a queued deletion
2. Agent comes back up. It takes an exclusive lock on the lockfile and replays the deletion queue
4. Agent starts the REST server
5. Agent drops the lock
6. Any blocked CNI plugin processes obtain the lock and retry the REST request, on the off chance the agent was starting up

To be consistent, we need to hold the delete queue lock while we transition from unavailable -> available, and the plugin needs to retry. So the ordering is something like

0. The REST API starts up, but rejects all endpoint requests
1. Agent takes the lock and replays all queued deletions
2. Endpoint API transitions to available
3. Agent drops the lock


Likewise, the CNI plugin needs to:

0. Connect and try the Delete request. If that fails...
1. Take the lock
2. Re-try connecting and the delete request
3. Fall back to queued delete.

File: plugins/cilium-cni/lib/deletion_queue.go [hunk 6]
```diff
@@ -138,7 +141,32 @@ func (dc *DeletionFallbackClient) EndpointDelete(id string) error {
...
+		err := dc.cli.EndpointDeleteMany(req)
+		status, ok := err.(runtime.ClientResponseStatus)
+		if !ok || !status.IsCode(http.StatusServiceUnavailable) {
+			return err
+		}
+
+		// If we don't already have lock on the local endpoint deletion queue, try acquire it.
+		if dc.lockfile == nil {
+			dc.logger.Debug("Deletion Queue lock not already held, reprocessing delete request with locked queue")
+			if err = dc.tryQueueLock(); err != nil || dc.lockfile == nil {
```
Comment (squeed) [inline plugins/cilium-cni/lib/deletion_queue.go]: I'm not sure this is right. The sequence needs to be:

1. Connect and Delete(). If that fails:
2. Lock
3. Connect and Delete(). If that fails
4. Write to queue
5. Unlock

So code needs a "connect-and-delete" method that is Unavailable-aware.

File: daemon/cmd/state.go (hunk 3 above)
Comment (fristonio) [reply daemon/cmd/state.go]: I have refactored the changes and split the PR to multiple commits.

File: plugins/cilium-cni/lib/deletion_queue.go (hunk 6 above)
Comment (fristonio) [reply plugins/cilium-cni/lib/deletion_queue.go]: It is no? We don't need to connect twice. The current flow is:
* Connect to server
* Attempt endpoint Delete; If that fails
* Lock
* Attempt endpoint Delete again; If that fails
* Write to Queue
* Unlock

Some logs from testing indicating the scenarios and corresponding transitions:
```
# Scenario: Cilium-Agent down
time=2025-07-28T23:19:56.797Z level=DEBUG msg="Processing CNI DEL request" subsys=cilium-cni eventID=398325a3-7db7-488c-9194-4c4fdfbabb25 containerID=9677d37a7fdce6bab07a8c9d1db920b75b85f20d3d9233cb7004512126658000 netNSName=/var/run/netns/cni-e4a0cdda-2833-3fd3-0f82-04f5500c36c1 interface=eth0 args="K8S_POD_INFRA_CONTAINER_ID=9677d37a7fdce6bab07a8c9d1db920b75b85f20d3d9233cb7004512126658000;K8S_POD_UID=24bd6a70-0289-4b1a-a653-d44dc991942f;IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=netshoot" file-path=/opt/cni/bin netConf="&{NetConf:{CNIVersion:0.3.1 Name:cilium Type:cilium-cni Capabilities:map[] IPAM:{Type:} DNS:{Nameservers:[] Domain: Search:[] Options:[]} RawPrevResult:map[] PrevResult:<nil> ValidAttachments:[]} MTU:0 Args:{} EnableRouteMTU:false ENI:{InstanceID: InstanceType: MinAllocate:0 PreAllocate:0 MaxAboveWatermark:0 FirstInterfaceIndex:<nil> SecurityGroups:[] SecurityGroupTags:map[] SubnetIDs:[] SubnetTags:map[] NodeSubnetID: VpcID: AvailabilityZone: ExcludeInterfaceTags:map[] DeleteOnTermination:<nil> UsePrimaryAddress:<nil> DisablePrefixDelegation:<nil>} Azure:{InterfaceName:} IPAM:{IPAM:{Type:} IPAMSpec:{Pool:map[] IPv6Pool:map[] Pools:{Requested:[] Allocated:[]} PodCIDRs:[] MinAllocate:0 MaxAllocate:0 PreAllocate:0 MaxAboveWatermark:0 StaticIPTags:map[]}} AlibabaCloud:{InstanceType: AvailabilityZone: VPCID: CIDRBlock: VSwitches:[] VSwitchTags:map[] SecurityGroups:[] SecurityGroupTags:map[]} EnableDebug:true LogFormat: LogFile:/var/run/cilium/cilium-cni.log ChainingMode:}"
time=2025-07-28T23:20:06.829Z level=WARN msg="Failed to connect to agent socket" subsys=cilium-cni eventID=398325a3-7db7-488c-9194-4c4fdfbabb25 containerID=9677d37a7fdce6bab07a8c9d1db920b75b85f20d3d9233cb7004512126658000 netNSName=/var/run/netns/cni-e4a0cdda-2833-3fd3-0f82-04f5500c36c1 interface=eth0 args="K8S_POD_INFRA_CONTAINER_ID=9677d37a7fdce6bab07a8c9d1db920b75b85f20d3d9233cb7004512126658000;K8S_POD_UID=24bd6a70-0289-4b1a-a653-d44dc991942f;IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=netshoot" file-path=/opt/cni/bin k8sNamespace=default k8sPodName=netshoot error="failed to create cilium agent client after 10.000000 seconds timeout: Get \"http://localhost/v1/config\": dial unix /var/run/cilium/cilium.sock: connect: no such file or directory" socket=unix:///var/run/cilium/cilium.sock
time=2025-07-28T23:20:06.829Z level=DEBUG msg="Attempting to acquire deletion queue lock" subsys=cilium-cni eventID=398325a3-7db7-488c-9194-4c4fdfbabb25 containerID=9677d37a7fdce6bab07a8c9d1db920b75b85f20d3d9233cb7004512126658000 netNSName=/var/run/netns/cni-e4a0cdda-2833-3fd3-0f82-04f5500c36c1 interface=eth0 args="K8S_POD_INFRA_CONTAINER_ID=9677d37a7fdce6bab07a8c9d1db920b75b85f20d3d9233cb7004512126658000;K8S_POD_UID=24bd6a70-0289-4b1a-a653-d44dc991942f;IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=netshoot" file-path=/opt/cni/bin k8sNamespace=default k8sPodName=netshoot file-path=/var/run/cilium/deleteQueue/lockfile
time=2025-07-28T23:20:06.830Z level=DEBUG msg="Deletion Queue lock acquired" subsys=cilium-cni eventID=398325a3-7db7-488c-9194-4c4fdfbabb25 containerID=9677d37a7fdce6bab07a8c9d1db920b75b85f20d3d9233cb7004512126658000 netNSName=/var/run/netns/cni-e4a0cdda-2833-3fd3-0f82-04f5500c36c1 interface=eth0 args="K8S_POD_INFRA_CONTAINER_ID=9677d37a7fdce6bab07a8c9d1db920b75b85f20d3d9233cb7004512126658000;K8S_POD_UID=24bd6a70-0289-4b1a-a653-d44dc991942f;IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=netshoot" file-path=/opt/cni/bin k8sNamespace=default k8sPodName=netshoot file-path=/var/run/cilium/deleteQueue/lockfile duration=486.376µs
time=2025-07-28T23:20:16.863Z level=INFO msg="Agent is down, falling back to deletion queue directory" subsys=cilium-cni eventID=398325a3-7db7-488c-9194-4c4fdfbabb25 containerID=9677d37a7fdce6bab07a8c9d1db920b75b85f20d3d9233cb7004512126658000 netNSName=/var/run/netns/cni-e4a0cdda-2833-3fd3-0f82-04f5500c36c1 interface=eth0 args="K8S_POD_INFRA_CONTAINER_ID=9677d37a7fdce6bab07a8c9d1db920b75b85f20d3d9233cb7004512126658000;K8S_POD_UID=24bd6a70-0289-4b1a-a653-d44dc991942f;IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=netshoot" file-path=/opt/cni/bin k8sNamespace=default k8sPodName=netshoot
time=2025-07-28T23:20:16.863Z level=INFO msg="Queueing endpoint batch deletion request" subsys=cilium-cni eventID=398325a3-7db7-488c-9194-4c4fdfbabb25 containerID=9677d37a7fdce6bab07a8c9d1db920b75b85f20d3d9233cb7004512126658000 netNSName=/var/run/netns/cni-e4a0cdda-2833-3fd3-0f82-04f5500c36c1 interface=eth0 args="K8S_POD_INFRA_CONTAINER_ID=9677d37a7fdce6bab07a8c9d1db920b75b85f20d3d9233cb7004512126658000;K8S_POD_UID=24bd6a70-0289-4b1a-a653-d44dc991942f;IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=netshoot" file-path=/opt/cni/bin k8sNamespace=default k8sPodName=netshoot req=&{ContainerID:9677d37a7fdce6bab07a8c9d1db920b75b85f20d3d9233cb7004512126658000}
time=2025-07-28T23:20:16.864Z level=INFO msg="Wrote queued deletion file" subsys=cilium-cni eventID=398325a3-7db7-488c-9194-4c4fdfbabb25 containerID=9677d37a7fdce6bab07a8c9d1db920b75b85f20d3d9233cb7004512126658000 netNSName=/var/run/netns/cni-e4a0cdda-2833-3fd3-0f82-04f5500c36c1 interface=eth0 args="K8S_POD_INFRA_CONTAINER_ID=9677d37a7fdce6bab07a8c9d1db920b75b85f20d3d9233cb7004512126658000;K8S_POD_UID=24bd6a70-0289-4b1a-a653-d44dc991942f;IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=netshoot" file-path=/opt/cni/bin k8sNamespace=default k8sPodName=netshoot file-path=/var/run/cilium/deleteQueue/f078c648eb722794235ee51ebf8cbb956e18b5a5c07781d74951dc81fa1ab623.delete
time=2025-07-28T23:20:16.867Z level=DEBUG msg="CNI DEL processing complete" subsys=cilium-cni eventID=398325a3-7db7-488c-9194-4c4fdfbabb25 containerID=9677d37a7fdce6bab07a8c9d1db920b75b85f20d3d9233cb7004512126658000 netNSName=/var/run/netns/cni-e4a0cdda-2833-3fd3-0f82-04f5500c36c1 interface=eth0 args="K8S_POD_INFRA_CONTAINER_ID=9677d37a7fdce6bab07a8c9d1db920b75b85f20d3d9233cb7004512126658000;K8S_POD_UID=24bd6a70-0289-4b1a-a653-d44dc991942f;IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=netshoot" file-path=/opt/cni/bin k8sNamespace=default k8sPodName=netshoot

# Scenario: ServiceUnavailable -> DeletionQueue Lock -> Service Available
time=2025-07-28T23:16:04.423Z level=DEBUG msg="Processing CNI DEL request" subsys=cilium-cni eventID=78986dce-b813-4abb-bf1e-84601a4f65e4 containerID=d158a6af9487327ed24cb568ef2291c7cf39379240ed86957ae4a3b02f1274f0 netNSName=/var/run/netns/cni-608f55cd-c414-c188-6566-78d4dd72738d interface=eth0 args="K8S_POD_NAME=netshoot;K8S_POD_INFRA_CONTAINER_ID=d158a6af9487327ed24cb568ef2291c7cf39379240ed86957ae4a3b02f1274f0;K8S_POD_UID=e9aad29a-2e89-4018-ad72-0fefbb169665;IgnoreUnknown=1;K8S_POD_NAMESPACE=default" file-path=/opt/cni/bin netConf="&{NetConf:{CNIVersion:0.3.1 Name:cilium Type:cilium-cni Capabilities:map[] IPAM:{Type:} DNS:{Nameservers:[] Domain: Search:[] Options:[]} RawPrevResult:map[] PrevResult:<nil> ValidAttachments:[]} MTU:0 Args:{} EnableRouteMTU:false ENI:{InstanceID: InstanceType: MinAllocate:0 PreAllocate:0 MaxAboveWatermark:0 FirstInterfaceIndex:<nil> SecurityGroups:[] SecurityGroupTags:map[] SubnetIDs:[] SubnetTags:map[] NodeSubnetID: VpcID: AvailabilityZone: ExcludeInterfaceTags:map[] DeleteOnTermination:<nil> UsePrimaryAddress:<nil> DisablePrefixDelegation:<nil>} Azure:{InterfaceName:} IPAM:{IPAM:{Type:} IPAMSpec:{Pool:map[] IPv6Pool:map[] Pools:{Requested:[] Allocated:[]} PodCIDRs:[] MinAllocate:0 MaxAllocate:0 PreAllocate:0 MaxAboveWatermark:0 StaticIPTags:map[]}} AlibabaCloud:{InstanceType: AvailabilityZone: VPCID: CIDRBlock: VSwitches:[] VSwitchTags:map[] SecurityGroups:[] SecurityGroupTags:map[]} EnableDebug:true LogFormat: LogFile:/var/run/cilium/cilium-cni.log ChainingMode:}"
time=2025-07-28T23:16:04.425Z level=WARN msg="Received ServiceUnavailable response from server for batch Endpoint Delete request" subsys=cilium-cni eventID=78986dce-b813-4abb-bf1e-84601a4f65e4 containerID=d158a6af9487327ed24cb568ef2291c7cf39379240ed86957ae4a3b02f1274f0 netNSName=/var/run/netns/cni-608f55cd-c414-c188-6566-78d4dd72738d interface=eth0 args="K8S_POD_NAME=netshoot;K8S_POD_INFRA_CONTAINER_ID=d158a6af9487327ed24cb568ef2291c7cf39379240ed86957ae4a3b02f1274f0;K8S_POD_UID=e9aad29a-2e89-4018-ad72-0fefbb169665;IgnoreUnknown=1;K8S_POD_NAMESPACE=default" file-path=/opt/cni/bin k8sNamespace=default k8sPodName=netshoot req=&{ContainerID:d158a6af9487327ed24cb568ef2291c7cf39379240ed86957ae4a3b02f1274f0}
time=2025-07-28T23:16:04.425Z level=DEBUG msg="Deletion Queue lock not already held, reprocessing delete request with locked queue" subsys=cilium-cni eventID=78986dce-b813-4abb-bf1e-84601a4f65e4 containerID=d158a6af9487327ed24cb568ef2291c7cf39379240ed86957ae4a3b02f1274f0 netNSName=/var/run/netns/cni-608f55cd-c414-c188-6566-78d4dd72738d interface=eth0 args="K8S_POD_NAME=netshoot;K8S_POD_INFRA_CONTAINER_ID=d158a6af9487327ed24cb568ef2291c7cf39379240ed86957ae4a3b02f1274f0;K8S_POD_UID=e9aad29a-2e89-4018-ad72-0fefbb169665;IgnoreUnknown=1;K8S_POD_NAMESPACE=default" file-path=/opt/cni/bin k8sNamespace=default k8sPodName=netshoot
time=2025-07-28T23:16:04.425Z level=DEBUG msg="Attempting to acquire deletion queue lock" subsys=cilium-cni eventID=78986dce-b813-4abb-bf1e-84601a4f65e4 containerID=d158a6af9487327ed24cb568ef2291c7cf39379240ed86957ae4a3b02f1274f0 netNSName=/var/run/netns/cni-608f55cd-c414-c188-6566-78d4dd72738d interface=eth0 args="K8S_POD_NAME=netshoot;K8S_POD_INFRA_CONTAINER_ID=d158a6af9487327ed24cb568ef2291c7cf39379240ed86957ae4a3b02f1274f0;K8S_POD_UID=e9aad29a-2e89-4018-ad72-0fefbb169665;IgnoreUnknown=1;K8S_POD_NAMESPACE=default" file-path=/opt/cni/bin k8sNamespace=default k8sPodName=netshoot file-path=/var/run/cilium/deleteQueue/lockfile
time=2025-07-28T23:16:04.425Z level=DEBUG msg="Deletion Queue lock acquired" subsys=cilium-cni eventID=78986dce-b813-4abb-bf1e-84601a4f65e4 containerID=d158a6af9487327ed24cb568ef2291c7cf39379240ed86957ae4a3b02f1274f0 netNSName=/var/run/netns/cni-608f55cd-c414-c188-6566-78d4dd72738d interface=eth0 args="K8S_POD_NAME=netshoot;K8S_POD_INFRA_CONTAINER_ID=d158a6af9487327ed24cb568ef2291c7cf39379240ed86957ae4a3b02f1274f0;K8S_POD_UID=e9aad29a-2e89-4018-ad72-0fefbb169665;IgnoreUnknown=1;K8S_POD_NAMESPACE=default" file-path=/opt/cni/bin k8sNamespace=default k8sPodName=netshoot file-path=/var/run/cilium/deleteQueue/lockfile duration=63.666µs
time=2025-07-28T23:16:04.425Z level=DEBUG msg="Endpoint delete request successful" subsys=cilium-cni eventID=78986dce-b813-4abb-bf1e-84601a4f65e4 containerID=d158a6af9487327ed24cb568ef2291c7cf39379240ed86957ae4a3b02f1274f0 netNSName=/var/run/netns/cni-608f55cd-c414-c188-6566-78d4dd72738d interface=eth0 args="K8S_POD_NAME=netshoot;K8S_POD_INFRA_CONTAINER_ID=d158a6af9487327ed24cb568ef2291c7cf39379240ed86957ae4a3b02f1274f0;K8S_POD_UID=e9aad29a-2e89-4018-ad72-0fefbb169665;IgnoreUnknown=1;K8S_POD_NAMESPACE=default" file-path=/opt/cni/bin k8sNamespace=default k8sPodName=netshoot req=&{ContainerID:d158a6af9487327ed24cb568ef2291c7cf39379240ed86957ae4a3b02f1274f0} duration=166ns
time=2025-07-28T23:16:04.439Z level=DEBUG msg="CNI DEL processing complete" subsys=cilium-cni eventID=78986dce-b813-4abb-bf1e-84601a4f65e4 containerID=d158a6af9487327ed24cb568ef2291c7cf39379240ed86957ae4a3b02f1274f0 netNSName=/var/run/netns/cni-608f55cd-c414-c188-6566-78d4dd72738d interface=eth0 args="K8S_POD_NAME=netshoot;K8S_POD_INFRA_CONTAINER_ID=d158a6af9487327ed24cb568ef2291c7cf39379240ed86957ae4a3b02f1274f0;K8S_POD_UID=e9aad29a-2e89-4018-ad72-0fefbb169665;IgnoreUnknown=1;K8S_POD_NAMESPACE=default" file-path=/opt/cni/bin k8sNamespace=default k8sPodName=netshoot

# Scenario: ServiceUnavailable -> DeletionQueue Lock -> Service Unvailable -> Persist to DeletionQueue
time=2025-07-28T23:23:21.973Z level=DEBUG msg="Processing CNI DEL request" subsys=cilium-cni eventID=c675e003-87ea-4d93-b35f-74d846398fde containerID=2afdcf40187740a4a9bcf97dc9715fe7deec01962e2acf4c64666e7e2991f663 netNSName=/var/run/netns/cni-59ff0698-552b-f3fe-72e6-611d2ef351e8 interface=eth0 args="IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=netshoot;K8S_POD_INFRA_CONTAINER_ID=2afdcf40187740a4a9bcf97dc9715fe7deec01962e2acf4c64666e7e2991f663;K8S_POD_UID=cefb4251-438f-436a-8ebb-1ec9f8c1ba14" file-path=/opt/cni/bin netConf="&{NetConf:{CNIVersion:0.3.1 Name:cilium Type:cilium-cni Capabilities:map[] IPAM:{Type:} DNS:{Nameservers:[] Domain: Search:[] Options:[]} RawPrevResult:map[] PrevResult:<nil> ValidAttachments:[]} MTU:0 Args:{} EnableRouteMTU:false ENI:{InstanceID: InstanceType: MinAllocate:0 PreAllocate:0 MaxAboveWatermark:0 FirstInterfaceIndex:<nil> SecurityGroups:[] SecurityGroupTags:map[] SubnetIDs:[] SubnetTags:map[] NodeSubnetID: VpcID: AvailabilityZone: ExcludeInterfaceTags:map[] DeleteOnTermination:<nil> UsePrimaryAddress:<nil> DisablePrefixDelegation:<nil>} Azure:{InterfaceName:} IPAM:{IPAM:{Type:} IPAMSpec:{Pool:map[] IPv6Pool:map[] Pools:{Requested:[] Allocated:[]} PodCIDRs:[] MinAllocate:0 MaxAllocate:0 PreAllocate:0 MaxAboveWatermark:0 StaticIPTags:map[]}} AlibabaCloud:{InstanceType: AvailabilityZone: VPCID: CIDRBlock: VSwitches:[] VSwitchTags:map[] SecurityGroups:[] SecurityGroupTags:map[]} EnableDebug:true LogFormat: LogFile:/var/run/cilium/cilium-cni.log ChainingMode:}"
time=2025-07-28T23:23:21.975Z level=WARN msg="Received ServiceUnavailable response from server for batch Endpoint Delete request" subsys=cilium-cni eventID=c675e003-87ea-4d93-b35f-74d846398fde containerID=2afdcf40187740a4a9bcf97dc9715fe7deec01962e2acf4c64666e7e2991f663 netNSName=/var/run/netns/cni-59ff0698-552b-f3fe-72e6-611d2ef351e8 interface=eth0 args="IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=netshoot;K8S_POD_INFRA_CONTAINER_ID=2afdcf40187740a4a9bcf97dc9715fe7deec01962e2acf4c64666e7e2991f663;K8S_POD_UID=cefb4251-438f-436a-8ebb-1ec9f8c1ba14" file-path=/opt/cni/bin k8sNamespace=default k8sPodName=netshoot req=&{ContainerID:2afdcf40187740a4a9bcf97dc9715fe7deec01962e2acf4c64666e7e2991f663}
time=2025-07-28T23:23:21.975Z level=DEBUG msg="Deletion Queue lock not already held, reprocessing delete request with locked queue" subsys=cilium-cni eventID=c675e003-87ea-4d93-b35f-74d846398fde containerID=2afdcf40187740a4a9bcf97dc9715fe7deec01962e2acf4c64666e7e2991f663 netNSName=/var/run/netns/cni-59ff0698-552b-f3fe-72e6-611d2ef351e8 interface=eth0 args="IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=netshoot;K8S_POD_INFRA_CONTAINER_ID=2afdcf40187740a4a9bcf97dc9715fe7deec01962e2acf4c64666e7e2991f663;K8S_POD_UID=cefb4251-438f-436a-8ebb-1ec9f8c1ba14" file-path=/opt/cni/bin k8sNamespace=default k8sPodName=netshoot
time=2025-07-28T23:23:21.975Z level=DEBUG msg="Attempting to acquire deletion queue lock" subsys=cilium-cni eventID=c675e003-87ea-4d93-b35f-74d846398fde containerID=2afdcf40187740a4a9bcf97dc9715fe7deec01962e2acf4c64666e7e2991f663 netNSName=/var/run/netns/cni-59ff0698-552b-f3fe-72e6-611d2ef351e8 interface=eth0 args="IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=netshoot;K8S_POD_INFRA_CONTAINER_ID=2afdcf40187740a4a9bcf97dc9715fe7deec01962e2acf4c64666e7e2991f663;K8S_POD_UID=cefb4251-438f-436a-8ebb-1ec9f8c1ba14" file-path=/opt/cni/bin k8sNamespace=default k8sPodName=netshoot file-path=/var/run/cilium/deleteQueue/lockfile
time=2025-07-28T23:23:21.975Z level=DEBUG msg="Deletion Queue lock acquired" subsys=cilium-cni eventID=c675e003-87ea-4d93-b35f-74d846398fde containerID=2afdcf40187740a4a9bcf97dc9715fe7deec01962e2acf4c64666e7e2991f663 netNSName=/var/run/netns/cni-59ff0698-552b-f3fe-72e6-611d2ef351e8 interface=eth0 args="IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=netshoot;K8S_POD_INFRA_CONTAINER_ID=2afdcf40187740a4a9bcf97dc9715fe7deec01962e2acf4c64666e7e2991f663;K8S_POD_UID=cefb4251-438f-436a-8ebb-1ec9f8c1ba14" file-path=/opt/cni/bin k8sNamespace=default k8sPodName=netshoot file-path=/var/run/cilium/deleteQueue/lockfile duration=59µs
time=2025-07-28T23:23:21.975Z level=WARN msg="Received ServiceUnavailable response from server for batch Endpoint Delete request" subsys=cilium-cni eventID=c675e003-87ea-4d93-b35f-74d846398fde containerID=2afdcf40187740a4a9bcf97dc9715fe7deec01962e2acf4c64666e7e2991f663 netNSName=/var/run/netns/cni-59ff0698-552b-f3fe-72e6-611d2ef351e8 interface=eth0 args="IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=netshoot;K8S_POD_INFRA_CONTAINER_ID=2afdcf40187740a4a9bcf97dc9715fe7deec01962e2acf4c64666e7e2991f663;K8S_POD_UID=cefb4251-438f-436a-8ebb-1ec9f8c1ba14" file-path=/opt/cni/bin k8sNamespace=default k8sPodName=netshoot req=&{ContainerID:2afdcf40187740a4a9bcf97dc9715fe7deec01962e2acf4c64666e7e2991f663}
time=2025-07-28T23:23:21.975Z level=INFO msg="Queueing endpoint batch deletion request" subsys=cilium-cni eventID=c675e003-87ea-4d93-b35f-74d846398fde containerID=2afdcf40187740a4a9bcf97dc9715fe7deec01962e2acf4c64666e7e2991f663 netNSName=/var/run/netns/cni-59ff0698-552b-f3fe-72e6-611d2ef351e8 interface=eth0 args="IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=netshoot;K8S_POD_INFRA_CONTAINER_ID=2afdcf40187740a4a9bcf97dc9715fe7deec01962e2acf4c64666e7e2991f663;K8S_POD_UID=cefb4251-438f-436a-8ebb-1ec9f8c1ba14" file-path=/opt/cni/bin k8sNamespace=default k8sPodName=netshoot req=&{ContainerID:2afdcf40187740a4a9bcf97dc9715fe7deec01962e2acf4c64666e7e2991f663}
time=2025-07-28T23:23:21.975Z level=INFO msg="Wrote queued deletion file" subsys=cilium-cni eventID=c675e003-87ea-4d93-b35f-74d846398fde containerID=2afdcf40187740a4a9bcf97dc9715fe7deec01962e2acf4c64666e7e2991f663 netNSName=/var/run/netns/cni-59ff0698-552b-f3fe-72e6-611d2ef351e8 interface=eth0 args="IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=netshoot;K8S_POD_INFRA_CONTAINER_ID=2afdcf40187740a4a9bcf97dc9715fe7deec01962e2acf4c64666e7e2991f663;K8S_POD_UID=cefb4251-438f-436a-8ebb-1ec9f8c1ba14" file-path=/opt/cni/bin k8sNamespace=default k8sPodName=netshoot file-path=/var/run/cilium/deleteQueue/7080ffcc30c5eadcd16021171fbe24b55ed4a3780f677250c393a54d20aed932.delete
time=2025-07-28T23:23:21.999Z level=DEBUG msg="CNI DEL processing complete" subsys=cilium-cni eventID=c675e003-87ea-4d93-b35f-74d846398fde containerID=2afdcf40187740a4a9bcf97dc9715fe7deec01962e2acf4c64666e7e2991f663 netNSName=/var/run/netns/cni-59ff0698-552b-f3fe-72e6-611d2ef351e8 interface=eth0 args="IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=netshoot;K8S_POD_INFRA_CONTAINER_ID=2afdcf40187740a4a9bcf97dc9715fe7deec01962e2acf4c64666e7e2991f663;K8S_POD_UID=cefb4251-438f-436a-8ebb-1ec9f8c1ba14" file-path=/opt/cni/bin k8sNamespace=default k8sPodName=netshoot

```

**Comment by fristonio** [comment]
```mermaid
sequenceDiagram
    participant Kubelet
    participant CNI as cilium-cni
    participant Agent as cilium-agent
    participant Disk as Disk (Persisted State)

    rect grey
    par Request
        Kubelet-->>+CNI: CNI Request [ADD/DEL]
        CNI->>-Agent: Endpoint API Request
    end
    end

    Note over Agent: Agent Down
    Kubelet-->>Agent: Request
    alt DEL
        Agent->>+CNI: Connection Failed
        CNI->>Disk: Persist to DeletionQueue
        Disk->>CNI:
        CNI-->>-Kubelet: OK
    else ADD
        Agent->>+CNI: Connection Failed
        CNI-->>-Kubelet: ERROR
    end

    Note over Agent: API Server Up
    Kubelet-->>Agent: Request
    alt DEL
        Agent->>+CNI: Service Unavailable (503)
        CNI->>Disk: Persist to DeletionQueue
        Disk->>CNI:
        CNI->>-Kubelet: OK
    else ADD
        Agent->>+CNI: Service Unavailable (503)
        CNI-->>-Kubelet: ERROR
    end

    critical Restore EndpointState
        Agent->>Disk:
        Disk->>Agent:
    end

    Note over Agent: EndpointState Restore Complete
    Kubelet-->>Agent: Request
    alt DEL
        Agent->>+CNI: DeleteEndpoint OK
        CNI->>-Kubelet: OK
    else ADD
        Agent->>+CNI: Service Unavailable (503)
        CNI-->>-Kubelet: ERROR
    end

    critical Process offline DeletionQueue
        Agent->>Disk:
        Disk->>Agent:
    end

    Note over Agent: Endpoint API Fence Unblocked
    Kubelet-->>Agent: Request
    alt DEL
        Agent->>+CNI: DeleteEndpoint OK
        CNI->>-Kubelet: OK
    else ADD
        Agent->>+CNI: PutEndpoint OK
        CNI-->>-Kubelet: OK
    end

    Note over Agent: API Fully Functional
```

@squeed does something like this makes sense for the flow?

File: plugins/cilium-cni/lib/deletion_queue.go (hunk 6 above)
Comment (squeed) [reply plugins/cilium-cni/lib/deletion_queue.go]: I'm pretty sure there's still a possible transition that could result in an entry written to the deletion queue after the agent comes up. This is because `tryConnect()` drops the lock once successfully connected. The flow is something like

1. plugin connect fails
2. plugin obtains lock file -- succeeds
3. plugin connect succeeds. drop lock file
4. agent acquires lock file
5. plugin delete request gets Unavailable
6. agent replays queue and drops lock
7. plugin acquires lock file and writes entry

The entry written in step 7 will be lost.

**Comment by fristonio** [comment]
/test
Edit: Retrying failed jobs
ci-eks: API failure to allocate eni ip address(400)
ci-gateway-api: Github api failure(429)

File: plugins/cilium-cni/lib/deletion_queue.go (hunk 6 above)
Comment (fristonio) [reply plugins/cilium-cni/lib/deletion_queue.go]: In step 7 we first acquire the lock and then **retry Endpoint Delete with lock held**. If CNI was able to acquire the lock after agent has processed the deletion queue then the subsequent DeleteEndpoint call won't fail with 503, so we won't write to DeletionQueue.

https://github.com/fristonio/cilium/blob/b37cb432134c7e6e04ba4572cb71a0225e1a5245/plugins/cilium-cni/lib/deletion_queue.go#L160-L163

Comment (squeed) [reply plugins/cilium-cni/lib/deletion_queue.go]: sure, but it's still too many steps. We should treat "connect-and-send-request" as a single logical step. That way we only have one lock acquisition, and the whole flow is easier to reason about.

Comment (fristonio) [reply plugins/cilium-cni/lib/deletion_queue.go]: Ah ok, yeah I think simplifying the transition makes sense. This is not a hotpath case, so should be ok to have multiple connects to API server. Let me update the PR.

Comment (fristonio) [reply plugins/cilium-cni/lib/deletion_queue.go]: Looking at the code, it seems like the client handling in general can be simplified a lot in the cni-plugin. Since the suggestion in this comment will also be a cosmetic change, would it make sense to holistically do this in a separate PR?
Ideally I would want to keep the entire cni-plugin client handling separate, so we can hide the implementation. But the change is outside the scope of the fix in this PR. I have some preliminary changes here - https://github.com/fristonio/cilium/commit/445f6a9932bb31bcd720f7dd208d42a81575e768

We can do scoped cleanup in this PR as well(I don't have a strong opinion either way), let me know what you think.
cc/ @joestringer for inputs.

Comment (joestringer) [reply plugins/cilium-cni/lib/deletion_queue.go]: I'd rather keep the fix as minimal as we can so we can potentially backport this to `v1.18` with fewer changes, then do subsequent refactor/cleanup in `main` as we deem necessary.

Comment (fristonio) [reply plugins/cilium-cni/lib/deletion_queue.go]: Yeah, I think that makes sense, will create a separate PR for cleanup.

**Review by dylandreimerink — APPROVED** [review]

**Review by Nikhil77Sharma — APPROVED** [review]

File: pkg/client/client.go [hunk 7]
```diff
@@ -190,14 +190,14 @@ func Hint(err error) error {
 	}
 
 	if errors.Is(err, context.DeadlineExceeded) {
-		return fmt.Errorf("Cilium API client timeout exceeded")
+		return fmt.Errorf("cilium API client timeout exceeded")
```
Comment (joestringer) [inline pkg/client/client.go]: nit: Please avoid unrelated changes in a functional patch. If necessary, these can be deferred to a separate cleanup patch. In this case given that Cilium is a proper noun, I don't really see a need to apply these changes - it's just churn for the codebase.

File: pkg/client/client.go [hunk 8]
```diff
@@ -190,14 +190,14 @@ func Hint(err error) error {
...
 	}
 
 	e, _ := url.PathUnescape(err.Error())
 	if strings.Contains(err.Error(), defaults.SockPath) {
 		return fmt.Errorf("%s\nIs the agent running?", e)
 	}
-	return fmt.Errorf("%s", e)
+	return err
```
Comment (joestringer) [inline pkg/client/client.go:200]: Cleanup change makes sense, but this also seems like it should be submitted in a separate commit.

File: plugins/cilium-cni/cmd/cmd.go [hunk 9]
```diff
@@ -930,6 +930,7 @@ func (cmd *Cmd) Del(args *skel.CmdArgs) error {
 		// We are not returning an error as this is very unlikely to be recoverable
 	}
 
+	scopedLogger.Debug("CNI DEL processing complete")
```
Comment (joestringer) [inline plugins/cilium-cni/cmd/cmd.go:956]: There's a few similar logging changes for CNI in this commit which should be split into a dedicated commit to improve debuggability of the CNI.

File: plugins/cilium-cni/lib/deletion_queue.go [hunk 10]
```diff
@@ -110,35 +114,54 @@ func (dc *DeletionFallbackClient) tryQueueLock() error {
...
+		logfields.Path, defaults.DeleteQueueLockfile,
+		logfields.Duration, time.Since(startTime))
 	dc.lockfile = lf
 	return nil
 }
 
-// EndpointDelete deletes an endpoint given by an endpoint id, either
-// by directly accessing the API or dropping in a queued-deletion file.
-// endpoint-id is a qualified endpoint reference, e.g. "container-id:XXXXXXX"
-func (dc *DeletionFallbackClient) EndpointDelete(id string) error {
```
Comment (joestringer) [inline plugins/cilium-cni/lib/deletion_queue.go:121]: Was this function unused? I don't see any corresponding calls to `EndpointDelete` being removed. If this change is non-functional, I would suggest also splitting the deletion of this method into a dedicated commit. This will clearly communicate that this was dead code that is being eliminated and that it is not necessary for that reason. That will help to focus this specific commit's changes on just updating the CNI to handle the newly introduced 503s; and if we ever have to bisect an issue down to this commit, the job will be much easier given that there aren't these other unrelated changes in the commit.

File: plugins/cilium-cni/lib/deletion_queue.go [hunk 11]
```diff
@@ -110,35 +114,54 @@ func (dc *DeletionFallbackClient) tryQueueLock() error {
...
+
+		status, ok := err.(runtime.ClientResponseStatus)
+		if !ok || !status.IsCode(http.StatusServiceUnavailable) {
+			// Propagate unhandled Endpoint delete errors.
+			return err
+		}
+
+		// Fallback to queuing endpoint delete if cilium Endpoint service is unavailable.
+		// Once ready, cilium-agent will process all the pending deletes in this queue.
+		dc.logger.Warn(
```
Comment (joestringer) [inline plugins/cilium-cni/lib/deletion_queue.go]: If this is an expected condition that the user can't do anything about, I would suggest either Debug or at most, Info.

```suggestion
		dc.logger.Debug(
```

As a separate note, we could decide to always emit an Info level log message when queueing deletion for easier tracing of the CNI flow.

File: plugins/cilium-cni/lib/deletion_queue.go [hunk 12]
```diff
@@ -110,35 +114,54 @@ func (dc *DeletionFallbackClient) tryQueueLock() error {
...
+			"Received ServiceUnavailable response from server for batch Endpoint Delete request",
+			logfields.Request, req,
+		)
+
+		// If we don't already have lock on the local endpoint deletion queue, try acquire it.
+		if dc.lockfile == nil {
```
Comment (joestringer) [inline plugins/cilium-cni/lib/deletion_queue.go]: Starting a separate thread, but it's related to this line vs. 155 (where there's another thread which is far deeper).

There is a `dc.lockfile == nil` check here and then another check two lines later. If `dc.lockfile` is protected by a lock, then this line should not do an unsynchronized check of its state. If this value not protected by a lock, then I don't understand why the value would be checked again two lines down.

File: plugins/cilium-cni/lib/deletion_queue.go (hunk 6 above)
Comment (joestringer) [reply plugins/cilium-cni/lib/deletion_queue.go]: Looking back over this thread, I think that @squeed was pointing out a logic error that must be addressed, then @fristonio was asking about cosmetic changes. Just to clarify, in this PR I would prioritize addressing the logic changes and then just omit cosmetic changes where possible.

File: pkg/endpoint/api/cell.go [hunk 13]
```diff
@@ -44,6 +47,9 @@ var Cell = cell.Module(
 	// has started and the deletion queue has been drained to unlock the
 	// delete queue and thus allow CNI plugin to proceed.
 	cell.Invoke(unlockAfterAPIServer),
+
+	// Fence for Endpoint API.
```
Comment (joestringer) [inline pkg/endpoint/api/cell.go]: nit: Endpoint API context is useful but I think this still a bit terse. Probably one of these makes the intent clearer?
```suggestion
	// Fence unblocks once the Endpoint deletion queue has been processed.
```

or 

```suggestion
	// Fence blocks until this package is ready to process Endpoint API requests.
```

File: pkg/endpoint/api/endpoint_deletion_queue.go [hunk 14]
```diff
@@ -23,6 +23,9 @@ import (
 	"github.com/cilium/cilium/pkg/promise"
 )
 
+// DeletionQueue manages the processing of persisted CNI delete requests.
+// This state is populated by CNI when the API is unrechable(eg. during agent restart),
```
Comment (joestringer) [inline pkg/endpoint/api/endpoint_deletion_queue.go]: nit:
```suggestion
// This state is populated by CNI when the API is unreachable (agent restart),
```

File: pkg/endpoint/api/endpoint_deletion_queue.go [hunk 15]
```diff
@@ -163,14 +177,9 @@ func (dq *DeletionQueue) processQueuedDeletes(ctx context.Context) error {
...
-		select {
-		case <-ctx.Done():
-			// continue and unlock
-		case <-dq.processed:
-			// continue and unlock
-		}
+		_ = dq.Wait(ctx)
 
+		// Continue and release the lock on offline queue.
 		if dq.lf != nil {
```
Comment (joestringer) [inline pkg/endpoint/api/endpoint_deletion_queue.go:183]: I realize this PR doesn't introduce the locking pattern here, but seeing a goroutine do a nil check for whether it has the lock or not looks like a red flag to me.

File: daemon/cmd/state.go [hunk 16]
```diff
@@ -375,35 +351,67 @@ func (d *Daemon) regenerateRestoredEndpoints(state *endpointRestoreState, endpoi
...
+}
+
+// Trigger asynchronous regeneration of restored endpoints.
+//
+// This method assumes that all the endpoints for which regeneration is requested are
+// already exposed to EndpointManager. It waits until the Endpoint API fence is unblocked
+// before regenerating all remaining live endpoints.
+//
+// Once complete, this method closes the daemon 'endpointRestoreComplete' channel.
+func (d *Daemon) handleRestoredEndpointsRegeneration(endpoints []*endpoint.Endpoint, endpointsRegenerator *endpoint.Regenerator) {
```
Comment (joestringer) [inline daemon/cmd/state.go:368]: This last commit makes a lot of subtle ordering changes and does not describe those subtleties. This makes it a bit hard to validate whether there are other unintentional ordering changes occurring in this commit. For a commit named "daemon: wait for endpoint api fence before restored endpoint regeneration" I expected that the code change would plumb the fence through and do a `fence.Wait()`. That code is definitely here, but then the flow of `regenerateRestoredEndpoints()` is also significantly altered to combine the upper two loops, as well as deferring the asynchronous regeneration until after the other asynchronous routines for endpoint deletion, policy computation complete are triggered. I'd suggest further breaking down these individual steps into dedicated commits so that each individual change is very clear and we can review the ordering changes for any potential pitfalls independently.

**Review by joestringer — CHANGES_REQUESTED** [review]

File: plugins/cilium-cni/lib/deletion_queue.go (hunk 12 above)
Comment (joestringer) [reply plugins/cilium-cni/lib/deletion_queue.go]: Digging a bit deeper it seems like `tryQueueLock()` should probably just either (a) get the lock and then it's non-nil or (b) fail with an  error. Then the conditional check below doesn't need to double-check `dc.lockfile`.

Comment (joestringer) [reply plugins/cilium-cni/lib/deletion_queue.go]: ^ Above appears to be the case already, so the resulting suggestion for this PR is just to drop the `|| dc.lockfile == nil ` check below.

Comment (joestringer) [reply plugins/cilium-cni/lib/deletion_queue.go]: While inspecting I found this other likely innocuous bug: https://github.com/cilium/cilium/pull/40958

Comment (fristonio) [reply plugins/cilium-cni/lib/deletion_queue.go]: Yeah, the check two lines below is not necessarily required. Given we are recursively calling this function if we acquired the lock, I added that check to make sure that we won't end up in an infinite loop.
I will remove the check and just rely on `tryQueueLock` err to ensure lockfile is populated as expected.

File: plugins/cilium-cni/lib/deletion_queue.go (hunk 10 above)
Comment (fristonio) [reply plugins/cilium-cni/lib/deletion_queue.go:121]: Yes this was dead code. Makes sense, will split to a separate commit.

File: plugins/cilium-cni/lib/deletion_queue.go (hunk 11 above)
Comment (fristonio) [reply plugins/cilium-cni/lib/deletion_queue.go]: We do have an info log as part of `enqueueDeletionRequestLocked` method.

File: pkg/endpoint/api/endpoint_deletion_queue.go (hunk 15 above)
Comment (joestringer) [reply pkg/endpoint/api/endpoint_deletion_queue.go:183]: I strongly suspect we could just move the content of this function into the end of `dq.Process()` to make the locking pattern more sane, but we can follow up on that separately from this PR.

File: pkg/client/client.go (hunk 8 above)
Comment (fristonio) [reply pkg/client/client.go:200]: This is required for endpoint delete api request handling in cni lib where we convert it to Runtime ResponseStatus to get http status code. I will keep it with that commit.

File: pkg/endpoint/api/endpoint_deletion_queue.go (hunk 15 above)
Comment (joestringer) [reply pkg/endpoint/api/endpoint_deletion_queue.go:183]: Asking about it here: https://github.com/cilium/cilium/pull/39014#discussion_r2255343572 .

File: plugins/cilium-cni/lib/deletion_queue.go (hunk 12 above)
Comment (joestringer) [reply plugins/cilium-cni/lib/deletion_queue.go]: I see a comment in the code a few lines down "Lockfile nil check to make sure we don't end up in an infinite loop", but the infinite loop case isn't apparent to me. Maybe I'm missing some context?

File: plugins/cilium-cni/lib/deletion_queue.go [hunk 17]
```diff
@@ -110,35 +114,54 @@ func (dc *DeletionFallbackClient) tryQueueLock() error {
...
+			dc.logger.Debug("Deletion Queue lock not already held, reprocessing delete request with locked queue")
+			if err = dc.tryQueueLock(); err != nil || dc.lockfile == nil {
+				// LockFile nil check to make sure we don't end up in an inifinite loop.
+				return fmt.Errorf("failed to acquire deletion queue lock: %w", err)
+			}
+
+			// Once we have the lock reprocess the Endpoint delete request. This is to make sure
+			// we don't race with an already proccessed cilium-agent endpoint deletion queue while
+			// we waited to acquire the lock.
+			return dc.EndpointDeleteMany(req)
```
Comment (joestringer) [inline plugins/cilium-cni/lib/deletion_queue.go]: Can you explain the race further here? In the logic I trace:
1. A connection was established to cilium-agent
2. cilium-agent is emitting 503s
3. cilium-agent finishes processing its existing deletion queue and unlocks the lockfile
4. This goroutine grabs the lock on the lockfile
5. Now there is a recursive call

This seems like it should just `dc.cli.EndpointDeleteMany(req)` instead?

File: plugins/cilium-cni/lib/deletion_queue.go (hunk 6 above)
Comment (joestringer) [reply plugins/cilium-cni/lib/deletion_queue.go]: Looking back over this thread I think we should sync on exactly what the form of the changes should look like. I've spent a bit of time thinking through the cases that were highlighted above and I agree with @squeed that this logic is too subtle which will likely mean we introduce other weirder cases. The idea of simplifying this logic down to follow the original flow that @squeed proposed at the start of this thread seems like it will be the simplest, most robust fix both for main and stable backport.

Comment (joestringer) [reply plugins/cilium-cni/lib/deletion_queue.go]: @fristonio and I synced out-of-band and we think there should be a relatively minimal way to take some of the connection logic out of the constructor and move that logic into this function, to then align it more closely with the simpler approach discussed at the top of this thread.

File: plugins/cilium-cni/lib/deletion_queue.go (hunk 17 above)
Comment (joestringer) [reply plugins/cilium-cni/lib/deletion_queue.go]: Discussed out-of-band, the recursive call would allow the first couple of calls to be shared, and I guess the eventual fallback could have fell through to the enqueueing logic, but given that it's harder to reason about the terminating condition of the recursive call, it is probably simpler to avoid the recursive call altogether. Then for the error conditions we just need to consider in which cases we want the logic to fall through to enqueuing the CNI DEL operation.

File: daemon/cmd/state.go (hunk 16 above)
Comment (fristonio) [reply daemon/cmd/state.go:368]: I have split this change to 3 commits. I think it should be simpler to reason about the change now. Let me know what you think.

File: plugins/cilium-cni/cmd/cmd.go (hunk 9 above)
Comment (fristonio) [reply plugins/cilium-cni/cmd/cmd.go:956]: Done

File: plugins/cilium-cni/lib/deletion_queue.go [hunk 18]
```diff
@@ -110,56 +117,89 @@ func (dc *DeletionFallbackClient) tryQueueLock() error {
...
-
-	return errors.New("attempt to delete with no valid connection")
 }
 
 // EndpointDeleteMany deletes multiple endpoints based on the endpoint deletion request,
 // either by directly accessing the API or dropping in a queued-deletion file.
 func (dc *DeletionFallbackClient) EndpointDeleteMany(req *models.EndpointBatchDeleteRequest) error {
-	if dc.cli != nil {
-		return dc.cli.EndpointDeleteMany(req)
+	err := dc.deleteEndpointsBatch(req)
```
Comment (marseel) [inline plugins/cilium-cni/lib/deletion_queue.go]: I would really love to see some unit test for this function as it became way more complicated than before to reason about.
There are at least two different entry points here:
- `dc.cli` not set and `lock` acquired
- `dc.cli` set and `lock` not acquired

and on top of that, we have a quite number of different cases here.

Comment (marseel) [reply plugins/cilium-cni/lib/deletion_queue.go]: In my opinion it has very unintuitive flow for case when lock was already acquired. How it works right now:
- `deleteEndpointsBatch` fails with `errServiceUnavailable` as client is not set.
- Then we don't acquire lock as we already have it. 
- And then we check error type and issue `enqueueDeletionRequestLocked`.
I would like to propose alternative implementation, that in my opinion is much simpler to reason about:
https://github.com/cilium/cilium/commit/569d956d6697691d3ccf9e3a0ae941525ac43265

Comment (fristonio) [reply plugins/cilium-cni/lib/deletion_queue.go]: This flow makes a lot of sense <3. I have incorporated the change to the PR. 
I am deferring testing and a more complete refactor to a separate PR. Does that make sense?

Comment (marseel) [reply plugins/cilium-cni/lib/deletion_queue.go]: > I am deferring testing and a more complete refactor to a separate PR. Does that make sense?

In my personal opinion, I would be fine with merging it to main if you plan to refactor it and extend testing later on as we have plenty of time till next release.
However, in this case, as you plan to backport it to 1.18, I would prefer to have test coverage before as I don't think any of the current test covers this logic. Also, some parts of lifecycle, bootstrap etc might diverge over time on main vs v1.18 branch.

File: pkg/client/client.go (hunk 8 above)
Comment (joestringer) [reply pkg/client/client.go:200]: Retrospectively I'm a bit surprised to see `Hint()` being called and I even wonder whether the lines immediately above about reformatting the output string to emit `Is the agent running?` is misaligned with the logic you're talking about. Probably the CNI plugin should be directly calling `api/v1/client/endpoint` functions to perform the API calls instead of the `pkg/client` wrappers which interfere with the underlying errors. Or `Hint()` could be updated to wrap the underlying errors instead of overwriting them.

But this is again more of an aside, I think that the call you made here is the right call for this specific PR. We can always further tidy the code after this PR.

File: daemon/cmd/state.go [hunk 19]
```diff
@@ -381,29 +356,57 @@ func (d *Daemon) regenerateRestoredEndpoints(state *endpointRestoreState, endpoi
...
+					"Error regenerating endpoint during restore",
+					logfields.Error, err,
+					logfields.EndpointID, ep.ID,
+				)
+			}
+		}(ep, regenWg)
+	}
+
+	regenWg.Wait()
+	d.logger.Info("Finished regenerating restored endpoints")
```
Comment (joestringer) [inline daemon/cmd/state.go]: The previous iteration of this log message printed some super useful statistics for sanity checking: The number of restored endpoints and the total number of endpoints that were requested to restore. If there's some issue and we find the numbers mismatch, this is interesting as it may indicate an endpoint was deleted while Cilium was down. If somehow the numbers are zero, then maybe we completely lost the restore state somehow. Can we keep those statistics?

File: daemon/cmd/state.go [hunk 20]
```diff
@@ -304,59 +301,37 @@ func (d *Daemon) regenerateRestoredEndpoints(state *endpointRestoreState, endpoi
...
-			epRegenerated <- true
-		}(ep, epRegenerated)
+			continue
+		}
+
+		endpointsToRegenerate = append(endpointsToRegenerate, ep)
 	}
 
+	// Trigger regeneration for relevant restored endpoints in a separate goroutine.
+	go d.handleRestoredEndpointsRegeneration(endpointsToRegenerate, endpointsRegenerator)
```
Comment (joestringer) [inline daemon/cmd/state.go]: There's a subtle reordering of logic here in the ~last~ patch 2555ad4409d2e761b982ab263070df87e6f4377e that I'm not sure I understand the repercussions for: Previously, the current goroutine would wait until all endpoints were removed before beginning the goroutine that waits for full policy computation to complete. This meant that `d.endpointInitialPolicyCompute` would only be closed once all restoration is complete, including both policy calculation for live endpoints as well as the removal of endpoints that were selected for cleanup/removal.

Is this change intentional? Is it safe? If in doubt, I would avoid changing the order (or do so as a separate change, maybe even not part of this bugfix. We could introduce it on `main` branch and let it bake without backporting to see if any issues arise).

EDIT: I pointed to the wrong patch, sorry :facepalm:

File: pkg/endpoint/endpoint.go [hunk 21]
```diff
@@ -2533,6 +2533,10 @@ func (e *Endpoint) Delete(conf DeleteConfig) []error {
 	}
 	e.setState(StateDisconnecting, "Deleting endpoint")
 
+	// Close initial policy computation channel to ensure consumers don't
+	// wait indefinitely.
+	e.InitialPolicyComputedLocked()
```
Comment (joestringer) [inline pkg/endpoint/endpoint.go]: I'm somewhat inclined to argue that the consumers should be checking that the endpoint has been deleted, even if indirectly via `lockAlive()` rather than changing the semantics of this other channel to mean that it's "policy was computed OR the endpoint disappeared while computing policy".

Comment (joestringer) [reply pkg/endpoint/endpoint.go]: Given that this function can do a `close()` and double-close *must* not happen, I would feel more comfortable not introducing another different path that might close the channel. This feels like it's taking channel ownership in the wrong direction.

Comment (joestringer) [reply pkg/endpoint/endpoint.go]: Looking at the users of `e.InitialEnvoyPolicyComputed`, there seems to be only:
1. A non-blocking call from `EndpointRegenerationEvent.Handle()`, which subsequently calls `Endpoint.rlockAlive()` to confirm the Endpoint has not been deleted, or
2. The call being made here.

Therefore I don't understand why this change is necessary at all.

**Review by joestringer — CHANGES_REQUESTED** [review]
The issue from [this thread](https://github.com/cilium/cilium/pull/40568#discussion_r2225572843) is still present in this latest version. However, given the simplifications going on in the recent iterations I think this actually provides a straightforward path to then address that concern as well. You could apply this additional patch on top of this tree and it would resolve the issue, while also simplifying the code to align with the discussion in that thread (I'd suggest just creating a new commit with this content as it'd be clearer to keep separate from the existing commits):

```
diff --git a/plugins/cilium-cni/cmd/cmd.go b/plugins/cilium-cni/cmd/cmd.go
index d402c8371120..dac56284c981 100644
--- a/plugins/cilium-cni/cmd/cmd.go
+++ b/plugins/cilium-cni/cmd/cmd.go
@@ -864,10 +864,7 @@ func (cmd *Cmd) Del(args *skel.CmdArgs) error {
        }
        scopedLogger = buildLogAttrsWithCNIArgs(scopedLogger, cniArgs)
 
-       c, err := lib.NewDeletionFallbackClient(scopedLogger)
-       if err != nil {
-               return fmt.Errorf("unable to connect to Cilium agent: %w", err)
-       }
+       c := lib.NewDeletionFallbackClient(scopedLogger)
 
        // If this is a chained plugin, then "delegate" to the special chaining mode and be done.
        // Note: DEL always has PrevResult set, so that doesn't tell us if we're chained. Given
diff --git a/plugins/cilium-cni/lib/deletion_queue.go b/plugins/cilium-cni/lib/deletion_queue.go
index d211ffa3f456..f80cebec4dc2 100644
--- a/plugins/cilium-cni/lib/deletion_queue.go
+++ b/plugins/cilium-cni/lib/deletion_queue.go
@@ -44,43 +44,10 @@ var (
 // NewDeletionFallbackClient creates a client that will either issue an EndpointDelete
 // request via the api, *or* queue one in a temporary directory.
 // To prevent race conditions, the logic is:
-// 1. Try and connect to the socket. if that succeeds, done
-// 2. Otherwise, take a shared lock on the delete queue directory
-// 3. Once we get the lock, check to see if the socket now exists
-// 4. If it exists, drop the lock and use the api
-func NewDeletionFallbackClient(logger *slog.Logger) (*DeletionFallbackClient, error) {
-       dc := &DeletionFallbackClient{
+func NewDeletionFallbackClient(logger *slog.Logger) *DeletionFallbackClient {
+       return &DeletionFallbackClient{
                logger: logger,
        }
-
-       // Try and connect (the usual case)
-       err := dc.tryConnect()
-       if err == nil {
-               return dc, nil
-       }
-       dc.logger.Warn(
-               "Failed to connect to agent socket",
-               logfields.Error, err,
-               logfields.Socket, client.DefaultSockPath(),
-       )
-
-       // We failed to connect: get the queue lock
-       if err := dc.tryQueueLock(); err != nil {
-               return nil, fmt.Errorf("failed to acquire deletion queue: %w", err)
-       }
-
-       // We have the queue lock; try and connect again
-       // just in case the agent finished starting up while we were waiting
-       if err := dc.tryConnect(); err == nil {
-               dc.logger.Info("Successfully connected to API on second try.")
-               // hey, it's back up!
-               dc.unlockQueue()
-               return dc, nil
-       }
-
-       // We have the lockfile, but no valid client
-       dc.logger.Info("Agent is down, falling back to deletion queue directory")
-       return dc, nil
 }
 
 func (dc *DeletionFallbackClient) tryConnect() error {
@@ -134,12 +101,10 @@ func (dc *DeletionFallbackClient) unlockQueue() {
 
 // EndpointDeleteMany deletes multiple endpoints based on the endpoint deletion request,
 // either by directly accessing the API or dropping in a queued-deletion file.
+//
+// The receiver is not expected to be connected to the cilium-agent API yet,
+// and this function will attempt to establish that connection.
 func (dc *DeletionFallbackClient) EndpointDeleteMany(req *models.EndpointBatchDeleteRequest) error {
-       if dc.lockfile != nil {
-               return dc.enqueueDeletionRequestLocked(req)
-       }
-
-       // If lock was not acquired, we have a valid client.
        err := dc.deleteEndpointsBatch(req)
        if err == nil || !errors.Is(err, errServiceUnavailable) {
                // Propagate the error if its not related to service unavailability.
@@ -171,6 +136,15 @@ func (dc *DeletionFallbackClient) EndpointDeleteMany(req *models.EndpointBatchDe
 }
 
 func (dc *DeletionFallbackClient) deleteEndpointsBatch(req *models.EndpointBatchDeleteRequest) error {
+       if err := dc.tryConnect(); err != nil {
+               dc.logger.Warn(
+                       "Failed to connect to agent socket",
+                       logfields.Error, err,
+                       logfields.Socket, client.DefaultSockPath(),
+               )
+               return err
+       }
+
        err := dc.cli.EndpointDeleteMany(req)
        if err != nil {
                status, ok := err.(runtime.ClientResponseStatus)
```

File: plugins/cilium-cni/lib/deletion_queue.go (hunk 18 above)
Comment (fristonio) [reply plugins/cilium-cni/lib/deletion_queue.go]: I have added the tests. It needed some additional refactoring in deletion queue lib code. Let me know what you think.

File: daemon/cmd/state.go (hunk 19 above)
Comment (fristonio) [reply daemon/cmd/state.go]: We do have logging for each restored endpoints regeneration so we can correlate from logs if we want this info. Given its one time handling it should be ok to keep the regen statistics at the cost of little bit complexity. I will make the changes.

File: pkg/client/client.go (hunk 8 above)
Comment (fristonio) [reply pkg/client/client.go:200]: Yeah, I think wrapping the errors instead of overwriting them makes more sense here. If we rely on directly using api client methods, eventually we would end up building the similar client implementation in cni plugin code. I think it would make more sense to adapt `pkg/client` to cni lib requirements.

File: daemon/cmd/state.go (hunk 20 above)
Comment (fristonio) [reply daemon/cmd/state.go]: While the reordering here is not intentional I don't think it impacts the overall restore logic. We propagate regen status through `endpointRestoreComplete` channel which was anyways async before.

> d.endpointInitialPolicyCompute would only be closed once all restoration is complete, including both policy calculation for live endpoints as well as the removal of endpoints that were selected for cleanup/removal.

This behavior doesn't change. Cleanup and this wait are not reordered and endpoints will close their own channel only when the regeneration completes.

File: pkg/endpoint/endpoint.go (hunk 21 above)
Comment (fristonio) [reply pkg/endpoint/endpoint.go]: When restoring the state with this patch, we might end up not regenerating an endpoint if it was deleted from offline queue. This change makes sure that this channel is closed if the endpoint is deleted. This helps simplify the code to not have dependency between endpoint regeneration and initial policy computation goroutines in `daemon/state.go`. Also, in general I think it makes sense to close all channels owned by the endpoint that are consumed externally during `Delete` so we don't leave something blocking on these channels.
I think we can refactor this more generally by introducing a function in endpoint object to wait for `InitialPolicyComputation` rather than using the channel directly. That way we can ensure waiting on channel doesn't block for an endpoint being deleted.

> Given that this function can do a close() and double-close must not happen, I would feel more comfortable not introducing another different path that might close the channel. This feels like it's taking channel ownership in the wrong direction.

That should not happen given we only close the channel if not already closed.

```go
func (e *Endpoint) InitialPolicyComputedLocked() {
	select {
	case <-e.InitialEnvoyPolicyComputed:
	default:
		close(e.InitialEnvoyPolicyComputed)
	}
}
```

**Comment by marseel** [comment]
> The issue from https://github.com/cilium/cilium/pull/40568#discussion_r2225572843 is still present in this latest version. However, given the simplifications going on in the recent iterations I think this actually provides a straightforward path to then address that concern as well. You could apply this additional patch on top of this tree and it would resolve the issue, while also simplifying the code to align with the discussion in that thread (I'd suggest just creating a new commit with this content as it'd be clearer to keep separate from the existing commits):

I'm fairly sure that proposed patch is incorrect. Let's consider case when `tryConnect` fails with timeout. It will not match error `if err == nil || !errors.Is(err, errServiceUnavailable) {` below line `err := dc.deleteEndpointsBatch(req)` and we will fail CNI DEL immediately when agent is down.

File: plugins/cilium-cni/lib/deletion_queue.go [hunk 22]
```diff
@@ -34,22 +52,43 @@ const timeoutSeconds = 10
...
+		newCiliumClientFn: newCiliumClient,
 	}
 
+	err := dc.initialize()
+	if err != nil {
+		return nil, err
+	}
+
+	// We have the lockfile, but no valid client
+	dc.logger.Info("Agent is down, falling back to deletion queue directory")
```
Comment (marseel) [inline plugins/cilium-cni/lib/deletion_queue.go]: nit: this is some leftover, right? Should be moved to end of initialize()

File: plugins/cilium-cni/lib/deletion_queue_test.go [hunk 23]
```diff
@@ -0,0 +1,223 @@
...
+	}
+	deletionClientErrorAlways := errorMock{
+		errorCase: errorCaseAlways,
+		err:       deletionClientErr,
+	}
+
+	tt := []struct {
+		newClientCreator    fakeCiliumClientCreator
+		initFail            bool
+		deletionFail        bool
```
Comment (marseel) [inline plugins/cilium-cni/lib/deletion_queue_test.go]: nit: initFail and deletionFail unused

File: plugins/cilium-cni/lib/deletion_queue.go (hunk 18 above)
Comment (marseel) [reply plugins/cilium-cni/lib/deletion_queue.go]: Thanks! I think it makes sense and looks good from my point of view.

File: plugins/cilium-cni/lib/deletion_queue.go [hunk 24]
```diff
@@ -34,22 +52,43 @@ const timeoutSeconds = 10
...
 	dc := &DeletionFallbackClient{
 		logger: logger,
+
+		deleteQueueDir:      defaults.DeleteQueueDir,
+		deleteQueueLockfile: defaults.DeleteQueueLockfile,
+
+		newCiliumClientFn: newCiliumClient,
 	}
 
+	err := dc.initialize()
```
Comment (marseel) [inline plugins/cilium-cni/lib/deletion_queue.go]: nit: at this point, we can just move `dc.initialize()` to `EndpointDeleteMany`. It will simplify testing as well.

**Review by marseel — APPROVED** [review]
lgtm for cni parts. 
I understand that:
> the issue from https://github.com/cilium/cilium/pull/40568#discussion_r2225572843 is still present in this latest version.

is still in the code, i. e. too many steps, could be simplified.

However, in my opinion, handling one special error (and usually infrequent one) from API as extension from previous implementation sounds like lower risk change than changing whole flow and potentially introducing other regressions - for example as mentioned above with incorrect error handling for proposed patch.

File: pkg/endpoint/endpoint.go (hunk 21 above)
Comment (joestringer) [reply pkg/endpoint/endpoint.go]: How would an endpoint get deleted from an offline queue?

Comment (joestringer) [reply pkg/endpoint/endpoint.go]: > I think it makes sense to close all channels owned by the endpoint that are consumed externally during `Delete`

I agree with the argument that the channel should be closed when the Endpoint is deleted, but I think that it's an anti-pattern to write code like this which checks if the channel is closed then closed it. This indicates that the actual goroutine that owns this channel is not taking full responsibility. I see it almost as a feature if `Delete` does not close this channel, because that indicates there is a bug elsewhere in the code which owns the channel. If that other code hangs, then that code needs to properly coordinate on the Endpoint deletion (which is currently done via the aliveLock), and ensure it actually closes the channel.

File: daemon/cmd/state.go (hunk 20 above)
Comment (joestringer) [reply daemon/cmd/state.go]: I suspect I may have added some unnecessary confusion to the thread sorry, let me walk through the steps I am seeing to contrast the behavior:

Before:

1. go ... `ep.RegenerateAfterRestore()` (for all endpoints)
2. `endpointCleanupCompleted.Wait()`
3. go ... `close(d.RestoreComplete)`

After:
1. `ep.RegenerateAfterRestore()` (host endpoint only)
2. `go d.handleRestoredEndpointsRegeneration(endpointsToRegenerate, endpointsRegenerator)`
   - `close(d.endpointRestoreComplete)`
3. `endpointCleanupCompleted.Wait()`

EDIT: Typo'd the channel

Comment (joestringer) [reply daemon/cmd/state.go]: My question then is, is it crucial for `d.endpointRestoreComplete` to wait for `endpointCleanupCompleted` or not? From a high level I wouldn't think endpoint restore operations overall are complete if the endpoint restore detected some cleanup needs to happen and that cleanup has not completed.

File: pkg/endpoint/endpoint.go (hunk 21 above)
Comment (joestringer) [reply pkg/endpoint/endpoint.go]: > simplify the code to not have dependency between endpoint regeneration and initial policy computation goroutines in daemon/state.go

I'm trying to understand this statement. Initial policy computation happens as part of endpoint regeneration, meaning you can guarantee that policy computation occurred if you wait until after endpoint regerenation. That dependency is baked into the current architecture. IIRC Chris might have been looking into changing this logic a bit, but I'm not sure that's relevant for the discussion here.

Comment (joestringer) [reply pkg/endpoint/endpoint.go]: I think I understand your perspective now, let me see if this is on the right track:

Looking at the latest version of this PR, at the end of `regenerateRestoredEndpoints()` there is this code:

```
       go func() {                                                                                                                                                                                                                                            
                for _, ep := range state.restored {                                                                                                                                                                                                            
                        <-ep.InitialEnvoyPolicyComputed                                                                                                                                                                                                        
                }                                                                                                                                                                                                                                              
                close(d.endpointInitialPolicyComplete)                                                                                                                                                                                                         
        }()
```

This assumes that for each endpoint that this function decides to restore, we *must* fully compute policy before proceeding, and there is no accounting for concurrent delete.

It seems to me that these endpoints were not concurrently deleted before. Maybe it was just unlikely due to when this code runs vs. cilium-agent grabbing the endpoint deletion queue lock?

However it sounds like what you're asserting is that there are two possible outcomes for the "restored" endpoints here: The endpoint might be restored, or the endpoint may be deleted. From the perspective of `regenerateRestoredEndpoints` closing the `d.endpointInitialPolicyComplete` channel, it doesn't matter which one of these events occur, as this goroutine is just signalling to the rest of the agent that all the necessary policy computation steps have been completed. Therefore it's simpler for this logic to not have to consider both cases. That's fair, and yeah I agree that exposing a method on the Endpoint object to deal with that complexity would allow the `daemon/cmd` logic to be ambivalent to this detail while still accounting for both cases in `pkg/endpoint`.

File: daemon/cmd/state.go (hunk 19 above)
Comment (joestringer) [reply daemon/cmd/state.go]: I should have mentioned this is a nit, but yeah I think this is a worthwhile improvement. I do think though if there ended up being some bug, it will be far more obvious to spot `msg="Finished regenerating restored endpoints" total=0 restored=0` than to see `msg="Finished regenerating restored endpoints"` with no other logs.

File: daemon/cmd/state.go (hunk 20 above)
Comment (fristonio) [reply daemon/cmd/state.go]: Ah ok, yeah you are right. We should keep the old order of dependencies between endpoint cleanup and restore complete channel close. Should just need reordering, will make the fix.

File: plugins/cilium-cni/lib/deletion_queue.go (hunk 24 above)
Comment (fristonio) [reply plugins/cilium-cni/lib/deletion_queue.go]: I think in the context of this PR I would keep it separate. Currently in CNI delete processing if initialization fails(both connect and lockfile acquire fails) then we return error from CNI so kubelet can retry. Coalescing initialize and endpoint delete will change this behavior as with the suggested change, chaining action delete can still complete even if init fails.

```go
	c, err := lib.NewDeletionFallbackClient(scopedLogger)
	if err != nil {
		return fmt.Errorf("unable to connect to Cilium agent: %w", err)
	}

	// If this is a chained plugin, then "delegate" to the special chaining mode and be done.
	// Note: DEL always has PrevResult set, so that doesn't tell us if we're chained. Given
	// that a CNI ADD could not have succeeded with an invalid chained mode, we should always
	// find a valid chained mode
	if chainAction, err := getChainedAction(n, scopedLogger); chainAction != nil {
		var (
			ctx = chainingapi.PluginContext{
				Logger:  scopedLogger,
				Args:    args,
				CniArgs: cniArgs,
				NetConf: n,
			}
		)

		return chainAction.Delete(context.TODO(), ctx, c)
	} else if err != nil {
		scopedLogger.Error(
			"Invalid chaining mode",
			logfields.Error, err,
		)
		return err
	}

	req := &models.EndpointBatchDeleteRequest{ContainerID: args.ContainerID}
	if err := c.EndpointDeleteMany(req); err != nil {
		// EndpointDeleteMany returns an error in the following scenarios:
		// DeleteEndpointInvalid: Invalid delete parameters, no need to retry
		// DeleteEndpointNotFound: No need to retry
		// DeleteEndpointErrors: Errors encountered while deleting,
		//                       the endpoint is always deleted though, no
		//                       need to retry
		scopedLogger.Warn("Errors encountered while deleting endpoint", logfields.Error, err)
	}
```

This is also the reason I am inclined to avoid changing the behavior of the constructor for this fix as @joestringer suggested. Might be something to carry forward to a separate change.

**Comment by joestringer** [comment]
> However, in my opinion, handling one special error (and usually infrequent one) from API as extension from previous implementation sounds like lower risk change than changing whole flow and potentially introducing other regressions - for example as mentioned above with incorrect error handling for proposed patch.

The concern I have is that the more complicated code is adding a race condition in the following path:

1. CNI `tryConnect()` fails, cilium-agent is down
2. CNI `tryQueueLock()` succeeds, obtains lock
3. cilium-agent starts up, restores endpoints and starts the API
4. cilium-agent begins `dq.Process()`. Blocks on deletion queue lock.
5. CNI `tryConnect()` succeeds, cilium-agent is up.
6. CNI `NewDeletionFallbackClient()` releases CNI lock
7. cilium-agent obtains lock, begins processing deletion queue
8. CI moves through to `EndpointDeleteMany()`, lock is not held and attempts deletion. Delete fails with 503.
9. CNI attempts `tryQueueLock()`. 
10. cilium-agent completes processing of deletion queue, releases lock
11. CNI is able to grab the lock, adds an endpoint delete to a queue but cilium-agent will not process it.

Looks like CNI `tryQueueLock()` and `tryConnect()` use a 10s timeout. ~That means that for this condition to occur, Cilium should execute step (3) in under 10s in order for step (5) to succeed; not sure how likely that is.~ Then the likelihood of hitting this condition overall depends on how many deletions are queued for step (7) to process and the host scheduling for threads handling CNI vs. Cilium API vs. Cilium deletion queue processing.

My gut feeling is that this is a relatively rare circumstance, but I think that means that this PR swaps out the behavior "Cilium might complain when it tries to delete an endpoint it already deleted" over to "Cilium might not delete an endpoint". 

I agree that the patch I proposed above isn't right in its timeout handling, the timeout case and the explicit "service unavailable" case should be treated the same IMO.

I'm not sure I agree that it's less risk to add an additional critical section along with more nuanced logic in the CNI that relies on specific steps occurring in cilium-agent. That said, I understand that the patch I proposed makes some logical leaps to realign the logic with a "connect and delete" approach along the lines of Casey's proposal, and those logical leaps are harder to reason about. Even if I think that's probably where we want to get to, maybe there is a middle ground where we keep the logic closer to the current approach but with simpler lock handling.

EDIT: Crossed out a logical step that was incorrect. All that needs to happen for this case is that Cilium agent is starting up/restoring endpoints and happens to start the API after step (2) and before/during step (5) (prior to the timeout).

File: plugins/cilium-cni/lib/deletion_queue.go (hunk 24 above)
Comment (joestringer) [reply plugins/cilium-cni/lib/deletion_queue.go]: I agree with this. This is pretty much the idea I was exploring when I was proposing the patch above, but I think that the patch I proposed above takes some additional logic jumps that are not super obvious. I think it would be a valuable step forward to move this logic into `EndpointDeleteMany()` at least, then all the logic is concentrated. (I didn't consider exactly how unit testing would work for this though)

Comment (joestringer) [reply plugins/cilium-cni/lib/deletion_queue.go]: My post above was prepared before I saw the response from @fristonio . Let me consider this.

As far as I can tell, the chained action just uses CNI lib code to delegate the deletion to any other chained plugins, then also for the Cilium specific path it just calls `c.EndpointDeleteMany()`: https://github.com/cilium/cilium/blob/b46ebf8c77ba1a436606346837506579affdc755/plugins/cilium-cni/chaining/generic-veth/generic-veth.go#L268-L277

Hence moving this logic out of the constructor should be logically OK. I'm also assuming all other chaining variations in `plugins/cilium-cni` are based on top of generic-veth. I don't see any other calls to `EndpointDeleteMany`, so I think there's nothing else to worry about.

I sympathize with the notion that the constructor should initialize everything inside the object, and that leaving the client uninitialized afterwards is a bit odd. On the other hand given how the connection step needs to be tightly integrated into the other logic in the delete function, I don't think that the constructor should really be doing blocking network calls. If there's some client object initialization we can do in the constructor that doesn't do a connect, I think it'd be reasonable to keep that logic there, then it'd be OK to move the connect out to `EndpointDeleteMany()`. At a glance the client initialization functions seem to be directly tied to client creation. 

Fortunately this code is pretty self-contained, so it's really just this path from `Cmd.Del()` we need to worry about.

TL;DR I agree with @marseel .

Comment (fristonio) [reply plugins/cilium-cni/lib/deletion_queue.go]: I have updated the PR to adapt to this review. There is one custom handling we have to add to `EndpointDeleteMany` call in cni delete processing to make sure that if the Delete was not processed by cilium(connect failed + delete lock/delete queue failed), we propagate the error to kubelet to retry. This matches the behavior we had before.
The flow now looks more clear to me, let me know what you think.

File: pkg/endpoint/endpoint.go (hunk 21 above)
Comment (fristonio) [reply pkg/endpoint/endpoint.go]: Should we make this change in this PR or can we defer it as a followup?

Comment (joestringer) [reply pkg/endpoint/endpoint.go]: I think it'd be OK to make the change here, that way we don't introduce this code then revert it again. Should be <10 lines change unless I'm missing something?

File: daemon/cmd/state.go (hunk 20 above)
Comment (joestringer) [reply daemon/cmd/state.go]: Thanks, LGTM.

File: pkg/endpoint/endpoint.go (hunk 21 above)
Comment (fristonio) [reply pkg/endpoint/endpoint.go]: Yeah shouldn't be too big of a change.

Looking at the code for this change, we will still need to ensure that channel is closed during Delete. Since Delete can be called async on the endpoint, we cannot just rely on checking endpoint state before waiting on the channel.
So for example in the below sequence, we will block:
1. daemon.WaitForInitialPolicy()
2. Endpoint Not Disconnecting
3. wait for `InitialEnvoyPolicyComputed` channel to close
4. Delete Endpoint(no regneration). Policy awaiter is orphaned.

I see two options:
1. Keep the current code to close `InitialEnvoyPolicyComputed` during endpoint delete so the Wait call doesn't block indefinitely.
2. Endpoint `Delete` closes a generic shutdown channel(needs to be introduced) that initial policy computation awaiter can select on along with `InitialPolicyComputation`.

Thoughts?

**Comment by joestringer** [comment]
Minor nit but for commit 7991dafddbc7 ("cni: refactor deletion queue lib for unit testing") I think that the title and commit description should highlight the functional changes being made there, to make it clear to future readers (including reviewers) that the logical changes are intentional. IMHO the `tryQueueLock()` changes there don't need to be part of the same change as they seem to be more about cleaning up the code to avoid storing a lock into an object (which is a change I agree with, it's just that logically it's a separate change and hence it's better to separate into a different commit). Otherwise as far as I could read, this is in line with what I had in mind in the threads above. Only other question I would have is whether the API timeout case that Marcel pointed out above is handled properly.

**Comment by fristonio** [comment]
> The concern I have is that the more complicated code is adding a race condition in the following path:
> 
> 1. CNI `tryConnect()` fails, cilium-agent is down
> 2. CNI `tryQueueLock()` succeeds, obtains lock
> 3. cilium-agent starts up, restores endpoints and starts the API
> 4. cilium-agent begins `dq.Process()`. Blocks on deletion queue lock.
> 5. CNI `tryConnect()` succeeds, cilium-agent is up.
> 6. CNI `NewDeletionFallbackClient()` releases CNI lock
> 7. cilium-agent obtains lock, begins processing deletion queue
> 8. CI moves through to `EndpointDeleteMany()`, lock is not held and attempts deletion. Delete fails with 503.
> 9. CNI attempts `tryQueueLock()`.
> 10. cilium-agent completes processing of deletion queue, releases lock
> 11. CNI is able to grab the lock, adds an endpoint delete to a queue but cilium-agent will not process it.

This is not a valid case no? Between 10 and 11,  once CNI grabs the lock, we will reattempt the `EndpointDeleteMany()` call which will succeed since cilium agent has processed the deletion queue.

**Comment by joestringer** [comment]
> This is not a valid case no? Between 10 and 11, once CNI grabs the lock, we will reattempt the EndpointDeleteMany() call which will succeed since cilium agent has processed the deletion queue.

Ah you're right, I made a mistake in step (11) as I didn't take into account the subsequent attempt to delete the endpoint while holding the lock. :dizzy_face:

**Comment by fristonio** [comment]
> Minor nit but for commit https://github.com/cilium/cilium/commit/7991dafddbc7245f6d878023aebdf42165f94e8f ("cni: refactor deletion queue lib for unit testing") I think that the title and commit description should highlight the functional changes being made there, to make it clear to future readers (including reviewers) that the logical changes are intentional. IMHO the tryQueueLock() changes there don't need to be part of the same change as they seem to be more about cleaning up the code to avoid storing a lock into an object (which is a change I agree with, it's just that logically it's a separate change and hence it's better to separate into a different commit).

Yeah, that makes sense. I will clean up the commits and do one final round of e2e testing.

> Only other question I would have is whether the API timeout case that Marcel pointed out above is handled properly.

Sorry, the thread has become too long, not able to find the comment in context. Which API timeout case? 😅

**Comment by joestringer** [comment]
>  Which API timeout case?

https://github.com/cilium/cilium/pull/40568#issuecomment-3163137234

I think the new `wrapClientFailure()` wrapper looks like it is supposed to help with that, but I'm also having some trouble getting my head around the wrapper as it's adding additional context only to some specific error paths. Overall I think it'd be easier if the underlying client library just emits either the standard timeout error or a standard 503 error, and the paths that check the errors for both of these to determine that cilium-agent is unavailable => execute the fallback behavior. The extra wrapper and custom error means we have to understand exactly which cases the error is wrapped or not rather than understanding the underlying error case.

**Comment by fristonio** [comment]
`wrapClientFailure` wraps all client specific errors to a known error type which is used:
1. Internally in the client lib to execute fallback logic
2. Externally by the caller to early return an error to kubelet indicating that the error is non-recoverable

The error types wrapped are:
1. cilium socket connection failure
2. Endpoint Delete failure with 503
3. Offline deletion queue related failures(lock fails, enqueue fails)

The main usecase is for external call(from `cmd.go`) to check when failure is unrecoverable. While handling error types explicitly with `lib` makes more sense, i think we should not spill this complexity over to the caller. Caller should only care about 3 cases: Success, EndpointDelete errors, Client errors(unrecoverable).

I have updated the code to use more scoped errors to better reason about the flow.

**Comment by fristonio** [comment]
To summarize the changes and discussion so far. The endpoint delete flow with fallback client now looks something like this:

```mermaid
flowchart TD
    A[DeletionFallbackClient] -->|EndpointDeleteMany| B[Get Or Connect Cilium API]
    B -->|Success| D[Request Endpoint Delete]
    B -->|Failure| E{DeletionQueue Lock}
    D -->|Success| OK{Return OK}
    D -->|Failure| E
    E -->|Acquired| F[Persist Deletion Request]
    E -->|NotAcquired| L[AcquireLock]
    L -->|Success| B
    L -->|Failed| NotOK
    F -->|Success| OK{Return OK}
    F -->|Failed| NotOK{Return Error}
```

**Comment by fristonio** [comment]
/test
Edit:
Clustermesh upgrade CI failure with `Link not found` errors, this change is fixing. The failure happens with `Cilium 1.18.0 2cd9057b` cilium-agent which is expected.

File: pkg/endpoint/endpoint.go (hunk 21 above)
Comment (joestringer) [reply pkg/endpoint/endpoint.go]: Another option is the endpoint's `aliveCtx` which is cancelled when the endpoint is stopped/deleted :thinking: . I'm not a huge fan of (1) but maybe that's the best short term fix while we re-familiarize ourselves with this code and decide which direction we want to take it.

Comment (fristonio) [reply pkg/endpoint/endpoint.go]: Oh, I missed that we already have an alive context for the endpoint. I think that is probably the more cleaner way to wait for initial policy no?
https://github.com/cilium/cilium/pull/40568/commits/eb4e6f24a19335b07e0f3ad72ee9130652d2207c

File: plugins/cilium-cni/lib/deletion_queue.go [hunk 25]
```diff
@@ -109,92 +110,128 @@ func (dc *DeletionFallbackClient) tryQueueLock() error {
...
+// To prevent race conditions, the logic is:
+// 1. Try and connect to the socket and request deletion. if that succeeds, done.
+// 2. Otherwise, take a shared lock on the delete queue directory.
+// 3. Once we have the lock, check again to see if the deletion request succeeds.
+// 4. Persist the request to offline queue in case of failure.
+func (dc *DeletionFallbackClient) EndpointDeleteMany(req *models.EndpointBatchDeleteRequest) error {
+	err := dc.deleteEndpointsBatch(req)
+	if err == nil || !dc.isServiceError(err) {
+		// Propagate the error if its not related to API service.
+		return err
```
Comment (joestringer) [inline plugins/cilium-cni/lib/deletion_queue.go:131]: I'm a bit confused around the error wrapping or lack of error wrapping for different cases to integrate `ErrClientFailure` into the error when propagating it up the stack. The usage seems a bit inconsistent to me - this line for instance doesn't wrap the error, and neither does `deleteEndpointsBatch()`, but there are two other error return cases that do wrap the error. Since this is then triggering different behavior up at the `Cmd.Del()` level with how the error is handled, it makes the logic at that layer hard to reason about without having a deep understanding of the full tree of error cases.

File: plugins/cilium-cni/cmd/cmd.go [hunk 26]
```diff
@@ -894,6 +891,11 @@ func (cmd *Cmd) Del(args *skel.CmdArgs) error {
 
 	req := &models.EndpointBatchDeleteRequest{ContainerID: args.ContainerID}
 	if err := c.EndpointDeleteMany(req); err != nil {
+		if errors.Is(err, lib.ErrClientFailure) {
+			scopedLogger.Error("Failed to delete endpoint", logfields.Error, err)
+			return err
+		}
```
Comment (joestringer) [inline plugins/cilium-cni/cmd/cmd.go:897]: If you make changes at this layer for error handling, then the same changes should be made for other callers of `c.EndpointDeleteMany()`, ie the generic-veth code.

Comment (joestringer) [reply plugins/cilium-cni/cmd/cmd.go:897]: When I read this code, I struggle to understand what the error cases are, and I think that the wrapper used in `EndpointDeleteMany` makes this even more confusing because only some error cases are wrapped and others are not. I don't know how intentional those cases are.

I have two potential directions I would suggest for this:
1. If we are going to do special logic for specific error conditions, I think it is better to open code a `switch` statement that clearly identifies the underlying errors like the timeout error or 503 and handle those specifically, then if we need a fallback for other error conditions, have a default case. Ideally those errors should be exported from the underlying library code and be pretty generic errors. This way, hopefully at this layer we can just read this code and have a pretty direct understanding of the error deep down the call stack without having to read through and understand the nuances of all of the code layers.
2. Until now, we have accepted that it's better to absorb all errors in the CNI and only print them to the logfile, then return success. Do you need to change that behavior to achieve the goal of this PR? If yes, let's have that discussion. If no and this is more of a cleanup because it feels odd to hide an error from the callers, then I would strongly recommend deferring that change to a different PR. I know Casey has some experience with how kubelet reacts to errors being passed back, and he could probably speak to what the best approach would be for how we handle these errors, but he's OOO at the moment and I think that may be a deeper discussion. This PR is complicated enough as it is, so if we don't need to take on this problem as well then I'd like to reduce the scope of this PR to get it into the tree sooner than later.

File: plugins/cilium-cni/lib/deletion_queue.go [hunk 27]
```diff
@@ -34,73 +46,62 @@ const timeoutSeconds = 10
...
-	if err := dc.tryConnect(); err == nil {
-		dc.logger.Info("Successfully connected to API on second try.")
-		// hey, it's back up!
-		dc.lockfile.Unlock()
-		dc.lockfile = nil
-		return dc, nil
-	}
+func wrapClientFailure(err error) error {
+	return fmt.Errorf("%w: %w", ErrClientFailure, err)
+}
```
Comment (joestringer) [inline plugins/cilium-cni/lib/deletion_queue.go]: nit: For an error wrapping case like this where the semantics of the name are not that different from the semantics of the underlying function (`Errorf() creates an error type, so does `wrapClientFailure()`), I think it's best to avoid one-liner functions like this because it obscures the important details of how the error is handled, and forces the reader to open this function to understand how the errors are being manipulated. This is not a hard rule, in some cases a wrapper can simplify the caller's logic, but for this case I think it does not simplify the caller.

File: plugins/cilium-cni/lib/deletion_queue.go [hunk 28]
```diff
@@ -34,73 +46,62 @@ const timeoutSeconds = 10
...
-	if err == nil {
-		return dc, nil
-	}
-	dc.logger.Warn(
-		"Failed to connect to agent socket",
-		logfields.Error, err,
-		logfields.Socket, client.DefaultSockPath(),
-	)
+	errClientConnectionFailed = errors.New("client connection failed")
+	errServiceUnavailable     = errors.New("service unavailable")
```
Comment (joestringer) [inline plugins/cilium-cni/lib/deletion_queue.go]: I think these errors are fine for this bugfix.

As a follow up, IMO `pkg/client` should be declaring and exporting the underlying errors so that all clients can use them, rather than declaring these errors in this library which uses `pkg/client`. There's nothing in these errors that is specific to logic in this package, so this package shouldn't need to declare its own error cases.

The way I'm thinking about this is that as a reviewer / maintainer of the Cilium codebase, if we have 100 really good common errors across the tree that we consistently use, which have clear semantics for the conditions those errors can occur in, that is easier to reason about than having 1000 errors with each package having its own special version of an error case.

File: plugins/cilium-cni/lib/deletion_queue.go [hunk 29]
```diff
@@ -34,73 +46,62 @@ const timeoutSeconds = 10
...
+)
 
-	// We failed to connect: get the queue lock
-	if err := dc.tryQueueLock(); err != nil {
-		return nil, fmt.Errorf("failed to acquire deletion queue: %w", err)
-	}
+func newCiliumClient(timeout time.Duration) (ciliumClient, error) {
+	return client.NewDefaultClientWithTimeout(timeout)
+}
```
Comment (joestringer) [inline plugins/cilium-cni/lib/deletion_queue.go:56]: This function has no value. The caller of this function can just directly call the function that's being called here.
```suggestion
```

File: daemon/cmd/state.go [hunk 30]
```diff
@@ -375,35 +347,88 @@ func (d *Daemon) regenerateRestoredEndpoints(state *endpointRestoreState, endpoi
...
+	for _, ep := range endpoints {
+		// Check if the endpoint still exists in EndpointManager.
+		epFromLookup := d.endpointManager.LookupCiliumID(ep.ID)
+		if epFromLookup == nil {
+			d.logger.Debug(
+				"Endpoint missing in EndpointManager, assuming already deleted",
+				logfields.EndpointID, ep.ID,
+			)
+			continue
+		}
```
Comment (joestringer) [inline daemon/cmd/state.go:391]: nit: This solves a significant portion of the problem, but there is a race condition remaining. Maybe something to think about beyond this PR.

I think this overall means that any queued deletions will have completed, so for instance if Cilium was down for several minutes and endpoints were deleted, then those deletions will be processed and Cilium won't attempt regeneration for those endpoints. That's already a huge improvement.

As far as I understand there's another race condition here where this call checks whether the endpoint is present in the endpoint manager, then immediately after the cilium-agent processes an Endpoint Delete API call for that endpoint, and this code will attempt a regeneration for that endpoint. That should be a much rarer case but still possible. Might be something to consider for a follow up.

File: plugins/cilium-cni/lib/deletion_queue.go [hunk 31]
```diff
@@ -34,73 +46,62 @@ const timeoutSeconds = 10
...
 func (dc *DeletionFallbackClient) tryConnect() error {
-	c, err := client.NewDefaultClientWithTimeout(timeoutSeconds * time.Second)
+	if dc.cli != nil {
+		return nil
+	}
+
+	c, err := dc.newCiliumClientFn(timeoutSeconds * time.Second)
 	if err != nil {
-		return err
+		return fmt.Errorf("%w: %w", errClientConnectionFailed, err)
```
Comment (joestringer) [inline plugins/cilium-cni/lib/deletion_queue.go]: As far as I understand, this is what's ensuring that a timeout error during connect will be handled the same as a service unavailable error in the caller. Solves the concern Marcel was concerned about :+1: 

I dug around in the internals of the client function for a while to try to understand which conditions should or should not be treated like service unavailable, and it was a bit tricky to come to a conclusive understanding about the range of error conditions that might occur as part of the client creation. Maybe this is good enough, and if it turns out that some specific error shouldn't be handled as service unavailable, we can address the issue as it comes up.

**Review by joestringer — COMMENTED** [review]
I think I'm fine with the logic flow for almost everything in this PR :+1: 

There's one new change in this latest revision where sometimes errors are being returned to Kubelet. I didn't see that before and unless we really need to I think we should avoid that and defer that discussion to a subsequent PR. That's the one blocking feedback I would give on the PR at this point. 

Most of the remaining feedback below were either minor nits or just non-actionable comments, for instance recognizing a change you made. I pointed out a couple of cases where (IMHO) some extra wrapper functions were unnecessary.

**Comment by joestringer** [comment]
Oh one more thing, you'll want to include a revert for commit 62c81afeea82 in this PR too.

File: pkg/endpoint/endpoint.go (hunk 21 above)
Comment (joestringer) [reply pkg/endpoint/endpoint.go]: Sorry missed your comment. Yeah I think `aliveCtx` should work.

File: plugins/cilium-cni/lib/deletion_queue.go (hunk 25 above)
Comment (fristonio) [reply plugins/cilium-cni/lib/deletion_queue.go:131]: Yeah, this error handling was a little bit unintuitive. I have removed all internal error types and `deleteEndpointsBatch` now returns an indication if the caller should try fallback. This is easy to reason about. Let me know what you think.

File: plugins/cilium-cni/cmd/cmd.go (hunk 26 above)
Comment (fristonio) [reply plugins/cilium-cni/cmd/cmd.go:897]: > Until now, we have accepted that it's better to absorb all errors in the CNI and only print them to the logfile, then return success.

This is not true for all errors. Currently we propagate the error to kubelet if we failed to fallback(locking the deletion queue file fails), this was handled as part of the constructor. This error handling preserves this behavior, which is required because if we failed to fall back(rare case) then we do want kubelet to retry the DEL later.

`EndpointDeleteMany` can return two types of errors with this change:
1. errors propagated from cilium-agent during endpoint deletion processing(eg. NotFound, Invalid etc).
2. Non recoverable error: DeletionFallbackClient failed to process the request due to error in fallback logic(eg. failed to get deletion queue lock). This indicates the caller to retry at a later time. This will be a very rare case.

I have added a comment to the method to make errors returned more clear. The error handling should be a little bit more cleaner now. Let me know if you have any other ideas.

File: plugins/cilium-cni/lib/deletion_queue.go (hunk 28 above)
Comment (fristonio) [reply plugins/cilium-cni/lib/deletion_queue.go]: I have cleaned up these errors. I think a simpler way is for the `deleteEndpointsBatch` method to directly return an indication if fallback should be attempted.

File: plugins/cilium-cni/lib/deletion_queue.go (hunk 29 above)
Comment (fristonio) [reply plugins/cilium-cni/lib/deletion_queue.go:56]: This is a required method. To be able to unit test the logic, we need to plug-in custom mock cilium api client. This method returns the default cilium client which can then be overridden by other mock methods during testing.
I am not sure if there is a better way to test such usecases. Let me know if you have any other ideas.

File: daemon/cmd/state.go (hunk 30 above)
Comment (fristonio) [reply daemon/cmd/state.go:391]: Yeah this behavior is possible, but I won't call it a race condition. Since endpoint regeneration and deletion are handled by two asynchronous channels, it is always possible for them to race. But this is handled correctly within Endpoint objects state machine and the eventual state of endpoint will reflect the deletion.

**Review by YutaroHayakawa — APPROVED** [review]

File: plugins/cilium-cni/cmd/cmd.go (hunk 26 above)
Comment (joestringer) [reply plugins/cilium-cni/cmd/cmd.go:897]: Ah right, I didn't correlate the failures in the constructor. I guess if there's no way to persist the delete to disk then yeah I don't see an alternative to returning the error back to kubelet. :+1:

File: plugins/cilium-cni/lib/deletion_queue.go (hunk 29 above)
Comment (joestringer) [reply plugins/cilium-cni/lib/deletion_queue.go:56]: I should have tried this out locally first before giving the feedback, sorry. The mocking bothers me a bit, but I don't have strictly better alternatives given the intent to return an interface type.

I played around a bit with generics to see if there's a solution there and I think there likely is, but frankly the incremental benefit of pursuing that is pretty low. Let's stick with this for now.

File: daemon/cmd/state.go (hunk 30 above)
Comment (joestringer) [reply daemon/cmd/state.go:391]: I think where I was taking this idea is the following: If the endpoint regeneration on the other side of the channel has to deal with the case where endpoints were deleted, then do we need this optimization to look up the endpoints before triggering? We could presumably delete this code and the other side should receive the event, find that the endpoint has been deleted, and early-cancel. 

This code gives me the impression that it is trying to prevent enqueueing regenerations for endpoints that were deleted, but we know that it cannot catch all such cases. If the other side of the regeneration trigger must handle these cases anyway, then could we just delete this code and rely on the fallback logic?

Comment (joestringer) [reply daemon/cmd/state.go:391]: An answer to this is we can save spinning up a few goroutines, controllers etc by keeping the current implementation. One variation on this idea is to place a simple `aliveCtx` / `lockAlive()` check in the start of `RegenerateAfterRestore()` just as an optimization in case the endpoint was deleted first. I guess it depends where we think it's best for this logic to live. Not sure if there are obvious tradeoffs here.

File: plugins/cilium-cni/lib/deletion_queue_test.go [hunk 32]
```diff
@@ -0,0 +1,264 @@
...
+		deleteQueueLockfile := path.Join(testDir, "lockfile")
+		return DeletionFallbackClient{
+			logger: logger,
+
+			deleteQueueDir:      testDir,
+			deleteQueueLockfile: deleteQueueLockfile,
+
+			newCiliumClientFn: newClientFn,
+		}
+	}
```
Comment (joestringer) [inline plugins/cilium-cni/lib/deletion_queue_test.go:100]: nit: I think this is a sign that the constructor is not well abstracted - if the constructor had parameters for each field, or used some kind of builder pattern, you could imagine reusing the constructor directly in the test below rather than open-coding another constructor for the underlying object.

But again, stuff we could improve but no need to block this PR on it.

**Review by joestringer — APPROVED** [review]
LGTM, thanks for bearing with all my questions :pray: 

Feel free to resolve all of the threads I have open, none of them are important to address at this time.

**Comment by joestringer** [comment]
The last commit needs a sign-off-by from you; BPF-checks is failing for this reason.

File: plugins/cilium-cni/lib/deletion_queue_test.go (hunk 32 above)
Comment (fristonio) [reply plugins/cilium-cni/lib/deletion_queue_test.go:100]: Yeah, I think builder pattern would have made more sense here. Will keep this as part of the follow up to unblock the PR.

File: daemon/cmd/state.go (hunk 30 above)
Comment (fristonio) [reply daemon/cmd/state.go:391]: > This code gives me the impression that it is trying to prevent enqueueing regenerations for endpoints that were deleted, but we know that it cannot catch all such cases. If the other side of the regeneration trigger must handle these cases anyway, then could we just delete this code and rely on the fallback logic?

Yeah that is right to some extent, the main reason for the wait however is to fix the CI and avoid logging any recoverable errors. Without waiting on endpoint deletion queue draining, we will try to regenerate the endpoint and might log errors.
During restore this check lets us wait for internal state to be consistent with that of the node, so I think its reasonable to have this special case after restart.

> One variation on this idea is to place a simple aliveCtx / lockAlive() check in the start of RegenerateAfterRestore() just as an optimization in case the endpoint was deleted first.

We already have this check as part of `RegenerateAfterRestore` when we attempt to restore the identity. 
image

**Comment by fristonio** [comment]
/test
K8s NetworkPolicy E2E tests - https://github.com/cilium/cilium/issues/39968

**Comment by joestringer** [comment]
Thanks again for all your work on this @fristonio :pray: Merging now.
