### PR TITLE
ipam: Fix invalid PodCIDR in CiliumNode in ENI/Azure/MultiPool mode

### LINKED ISSUE #9409: ENI: Do not fill ciliumnodes with allocated podCIDRs in ENI mode
In ENI mode, `spec.ipam.podCIDRs` of `ciliumnodes` is filled with CIDR allocated by cilium and it's never used. Remove `spec.ipam.podCIDRs` to avoid confusion with ENI IP addresses allocated by operator.

### PR DESCRIPTION
**Pull request by gandro**
This commit fixes an issue where Cilium-Agent would announce its internal auto-generated IPv4/IPv6AllocRange by writing it into the local CiliumNode resource.

Cilium-Agents IPv4/IPv6AllocRange is Cilium's internal representation of the local node's PodCIDR. The concept of a single allocation CIDR however is outdated, since in many IPAM modes (ENI, Azure, AlibabaCloud, MultiPool) there either is no PodCIDR to begin with (and pod IPs are allocated using a different scheme), or there are multiple PodCIDRs (in the case of MultiPool).

Before this commit, cilium-agent used to copy its internal PodCIDR into the CiliumNode resource, but this behavior is only correct in Kubernetes IPAM mode. In Kubernetes IPAM mode, the IPv4/IPv6AllocRange is taken from the Kubernetes Node resource, and thus it makes sense to announce it to other cilium-agent instances via the CiliumNode resource. This field then is for example used by `auto-direct-node-routes` to install routes for direct routing mode.

However, in all other IPAM modes that we have, copying the internal PodCIDR into the the CiliumNode resource does not make sense:

 - In ClusterPool mode, the CiliumNode PodCIDR field is populated by cilium-operator. Therefore, we should try to overwrite it ourselves. This behavior is unchanged by this commit.
 - In all other current IPAM modes, the CiliumNode PodCIDR field is not used. Instead we use fields specific to those IPAM modes (c.f. CiliumNode.Spec.IPAM). In those modes, the previous code therefore wrote a auto-generated but otherwise IPv4/IPv6AllocRange into the field. That auto-generated PodCIDR is not used for pod IP allocation in those modes, so it does not make sense to announce it either.

The announced auto-generated PodCIDR is causing issues in IPAM MultiPool mode. With this commit, we will no longer install invalid routes for the auto-generated PodCIDR. This was mostly harmless (since the auto-generated PodCIDR rarely overlapped with the real ones), but still a potential cause for confusion and bugs.

In addition, ENI-mode users have reported that they are confused by the this "fake" PodCIDR, which is understandable, since that PodCIDR is meaningless in ENI mode (#9409).

Long term, we want to remove the concept of the IPv4/IPv6AllocCIDR completely (and remove the auto-generation code), but this is a first incremental step towards that goal.

Fixes: #9409

```release-note
Fix potential cross-node connectivity issue when IPsec is enabled with ENI or Azure IPAM modes.
```

### CODE REVIEW

**Review by doniacld — APPROVED** [review]

**Comment by gandro** [comment]
- [CI Multicluster](https://github.com/cilium/cilium/actions/runs/5474058352) failed with #26513 - restarting
- [CI AKS](https://github.com/cilium/cilium/actions/runs/5474058322) failed due to quota (reported to infra team)
- [CI EKS](https://github.com/cilium/cilium/actions/runs/5474058443/jobs/9968346055) seems to have hit a new issue? I've created https://github.com/cilium/cilium/issues/26665 Unlikely that it is related, but I'll investigate in the issue and restart

**Review by thorn3r — APPROVED** [review]
thanks for the detailed commit msg, looks great :+1:

**Comment by gandro** [comment]
The IPSec failures seem legitimate. It seems we do not setup IPSec if the node does not have a podCIDR, even in ENI mode:

https://github.com/cilium/cilium/blob/9c78f2a3c5c50d8d37619af8be4e8f225d791d28/pkg/datapath/linux/node.go#L1006

**Comment by mathpl** [comment]
Does this relate to https://github.com/cilium/cilium/issues/22273 @gandro?

**Comment by gandro** [comment]
> Does this relate to #22273 @gandro?

Yes, that issue too (we have to many issues caused by the invalid PodCIDRs :disappointed: )

**Comment by gandro** [comment]
This is currently in draft because it affects the IPSec code base, which is currently also undergoing a refactor. Paul asked me to hold off with this change until the IPSec refactor dust has settled.

**Comment by gandro** [comment]
> This is currently in draft because it affects the IPSec code base, which is currently also undergoing a refactor. Paul asked me to hold off with this change until the IPSec refactor dust has settled.

@pchaigno Are more changes to this part of the IPSec code base planned or is now a good time to try to get the changes in this PR merged?

In particular, if I recall correctly, you said the changes themselves were fine, but we need to also consider the upgrade/downgrade path. I see we now also have new IPSec pipelines. Do they test upgrade/downgrade or do I need to di manual testing still for this?

**Comment by pchaigno** [comment]
> @pchaigno Are more changes to this part of the IPSec code base planned or is now a good time to try to get the changes in this PR merged?
> 
> In particular, if I recall correctly, you said the changes themselves were fine, but we need to also consider the upgrade/downgrade path. I see we now also have new IPSec pipelines. Do they test upgrade/downgrade or do I need to di manual testing still for this?

Nice timing! I was planning to ping you today :) Gray's PR to cover IPsec key rotation was merged this morning, so I thought now is probably as good a time as ever to merge this. We have some up/downgrade coverage (minus patch versions, minus error logs) and good key rotation coverage. We also extended the BPF and Golang unit tests. I think this doesn't need additional manual testing (the IPsec team will perform some before releases anyway). I'm also happy to review once it's ready for reviews!

**Comment by gandro** [comment]
Image build failed due to an infra error:

```
 ERROR: failed to solve: failed to compute cache key: failed to copy: httpReadSeeker: failed open: unexpected status code https://quay.io/v2/cilium/cilium-runtime/blobs/sha256:3975c531ca1b6c65f021a92957af42ca1f01a690d3864fdeef48dbbe0da9d380: 502 Bad Gateway
Error: buildx failed with: ERROR: failed to solve: failed to compute cache key: failed to copy: httpReadSeeker: failed open: unexpected status code https://quay.io/v2/cilium/cilium-runtime/blobs/sha256:3975c531ca1b6c65f021a92957af42ca1f01a690d3864fdeef48dbbe0da9d380: 502 Bad Gateway
```

Restarting.

File: pkg/nodediscovery/nodediscovery.go [hunk 1]
```diff
@@ -507,17 +507,16 @@ func (n *NodeDiscovery) mutateNodeResource(nodeResource *ciliumv2.CiliumNode) er
 		}
```
Comment (pchaigno) [inline pkg/nodediscovery/nodediscovery.go:507]: *(On commit description)*

(Not sure if it's worth repushing just for that.)

> In ClusterPool mode, the CiliumNode PodCIDR field is populated by cilium-operator. Therefore, we should try to overwrite it ourselves.

Did you mean "we shouldn't"?

> the previous code therefore wrote a auto-generated but otherwise IPv4/IPv6AllocRange into the field

I think there's a word missing here.

File: pkg/datapath/linux/node.go [hunk 2]
```diff
@@ -1081,26 +1081,29 @@ func (n *linuxNodeHandler) enableIPsecIPv4(newNode *nodeTypes.Node, nodeID uint1
...
 
-	new4Net := newNode.IPv4AllocCIDR.IPNet
 	wildcardIP := net.ParseIP(wildcardIPv4)
 	wildcardCIDR := &net.IPNet{IP: wildcardIP, Mask: net.IPv4Mask(0, 0, 0, 0)}
 
 	err := ipsec.IPsecDefaultDropPolicy(false)
 	errs = errors.Join(errs, upsertIPsecLog(err, "default-drop IPv4", wildcardCIDR, wildcardCIDR, spi))
 
 	if newNode.IsLocal() {
-		errs = errors.Join(errs, n.replaceNodeIPSecInRoute(new4Net))
```
Comment (pchaigno) [inline pkg/datapath/linux/node.go:1096]: IIUC, on EKS & AKS, we would install a route using the internal auto-generated IPv4/IPv6AllocRange. Do we have an idea of the potential consequences of that? The second commit suggests that the auto-generated CIDR could clash with real CIDR, although unlikely.

**Review by pchaigno — APPROVED** [review]
Thanks a lot for delaying this until we can have enough confidence into the IPsec CI and changes :pray: I know it's a pain to have to postpone PRs like that.

I have one comment below to try to understand the potential impact of the IPsec change. But regardless of that, I see the PR is marked as release-note/bug, but doesn't have a release note or a backport label. Outside of the IPsec part, is there any user-visible impact?

File: pkg/nodediscovery/nodediscovery.go (hunk 1 above)
Comment (gandro) [reply pkg/nodediscovery/nodediscovery.go:507]: > Did you mean "we shouldn't"?

> I think there's a word missing here.

Yes, good catches! Will fix, thanks!

File: pkg/datapath/linux/node.go (hunk 2 above)
Comment (gandro) [reply pkg/datapath/linux/node.go:1096]: So yes, before this PR installed a route for the auto-generated pod CIDR. It used an auto-generated pod CIDR, because that's Cilium's ancient fall-back if no pod CIDR is configured. That auto-generated pod CIDR is not used anywhere (see also https://github.com/cilium/cilium/issues/27018) and we're planning to eventually remove it, since it causes confusion for both engineers and users.

Particularly in EKS and AKS, IPs are not allocated from any pod CIDR (be it auto-generated or manually configured), and so using a node's pod CIDR in AKS or EKS is making assumptions about the IP range that does not hold true. By installing a route for each node's (auto-generated) pod CIDR (as we did before the PR), we routed all traffic belonging to those auto-generated CIDRs to the encrypt device.  

I'm not sure, what the consequence of this were. We have not received bug reports about this, I think mostly because the auto-generated CIDR is by design unlikely to clash with a real CIDR. Since the encrypt device is probably also the default egress device, the route might also not have affected any issues for CIDRs that were routable on the default egress device anyway.

In any case, my primary motivation for this PR is the clean up unconditional uses of "pod CIDR" in the agent code, because such code will not be compatible with pod-CIDR-less IPAM modes such as EKS/AKS or Multi-Pool. IPSec already has "subnet encryption" as a pod CIDR replacement, but for some reason it still unconditionally used the pod CIDR, which this PR attempts to fix.

**Comment by gandro** [comment]
- ci-ipsec-e2e https://github.com/cilium/cilium/actions/runs/6010063414/job/16300738637 failed with `one.one.one.one:443` - I suspect this is a infra flake, though I'll investigate
- https://github.com/cilium/cilium/actions/runs/6010063515/job/16300786495 hit https://github.com/cilium/cilium/issues/27688, restarting

**Comment by gandro** [comment]
I did a quick triage of the IPSec failiures. I don't see anything wrong, but if anything stands out @pchaigno let me know.

Sympton: The DNS lookup fails as follows:
```
[.] Action [no-policies/pod-to-world/http-to-one.one.one.one-0: cilium-test/client2-646b88fb9b-n948t (10.244.2.191) -> one.one.one.one-http (one.one.one.one:80)]
Tue, 29 Aug 2023 09:16:46 GMT   [.] Action [no-policies/pod-to-world/https-to-one.one.one.one-0: cilium-test/client2-646b88fb9b-n948t (10.244.2.191) -> one.one.one.one-https (one.one.one.one:443)]
Tue, 29 Aug 2023 09:16:46 GMT   ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --output /dev/null --connect-timeout 2 --max-time 10 --retry 3 --retry-all-errors --retry-delay 3 [https://one.one.one.one:443](https://one.one.one.one/)" failed: command failed: curl: (28) Resolving timed out after 2000 milliseconds
```

It is a bit suspicious that it's not the connection to 1.1.1.1 that fails, but the DNS lookup. In Hubble, I don't see any dropped UDP port 53 traffic.

I also checked the routes in routing table 200 (the one affected by this PR) and it looks like it should on all three nodes, one route per remote node:

```
10.244.0.0/24 dev cilium_host proto kernel mtu 1450 
local 10.244.1.0/24 dev cilium_vxlan proto kernel scope host 
10.244.3.0/24 dev cilium_host proto kernel mtu 1450 
```

So I suspect this is just a flake where DNS somehow timed out, we've seen apparently similar flakes before: https://github.com/cilium/cilium/issues/26321

File: pkg/datapath/linux/node.go (hunk 2 above)
Comment (pchaigno) [reply pkg/datapath/linux/node.go:1096]: I did a quick test on EKS to simulate the impact of a clash between the auto-generated CIDR and the pod subnet. Pod subnet was 192.168.0.0/16 and I manually installed a route like the one removed in this PR but with CIDR 192.168.128.0/17.

That caused some existing connections to be interrupted and prevented me from running the connectivity tests. I didn't debug further. There were no drops reported by Cilium or XFRM errors.

I have no idea how unlikely it is for the CIDRs to clash, but maybe we need to add a release note (something like below or can we make the "potential" more precise?) and backport to just v1.14?
```
Fix potential cross-node connectivity issue when IPsec is enabled with ENI or Azure IPAM modes.
```

**Comment by pchaigno** [comment]
> So I suspect this is just a flake where DNS somehow timed out, we've seen apparently similar flakes before: #26321

I agree it's unlikely caused by this PR. Nevertheless, the fact that it happens in both cases in the key rotation section which we've just added makes me wonder if it's not a new flake caused by the key rotation changes. Might be worth opening a flake issue, just so we can track it.

File: pkg/datapath/linux/node.go (hunk 2 above)
Comment (gandro) [reply pkg/datapath/linux/node.go:1096]: Awesome, thanks for that test :rocket: 

> I have no idea how unlikely it is for the CIDRs to clash, but maybe we need to add a release note (something like below or can we make the "potential" more precise?) and backport to just v1.14?

In the end, it depends on user configuration. [The auto-generated CIDR](https://github.com/cilium/cilium/blob/a8d80e25ca2d26affe4f7f7a8350bb537ddbe388/pkg/node/address.go#L123) is of the form "10.x.0.0/16" where x is derived from the node's IP. So I think clashes can happen - but I'm not aware of any bug reports, probably because most users are using IPs in the range of "10.0.0.0/16".

I think we can absolutely backport this to v1.14. I removed the backport label because there have not been bug reports and this has likely been present for years, but given the risk should be low, it does fit our backporting policy.

**Comment by gandro** [comment]
> > So I suspect this is just a flake where DNS somehow timed out, we've seen apparently similar flakes before: #26321
> 
> I agree it's unlikely caused by this PR. Nevertheless, the fact that it happens in both cases in the key rotation section which we've just added makes me wonder if it's not a new flake caused by the key rotation changes. Might be worth opening a flake issue, just so we can track it.

I've created an issue. Pretty sure it's unrelated since I also found scheduled runs with the same error. https://github.com/cilium/cilium/issues/27799

---

Triage of new failures:

[Setup & Test (1, 4.19-20230810.091425, iptables, false, vxlan, ipsec, false)](https://github.com/cilium/cilium/actions/runs/6011556981/job/16305158986#logs)

```
   [.] Action [echo-ingress-knp/pod-to-pod/curl-ipv6-3: cilium-test/client2-646b88fb9b-g945g (fd00:10:244:3::9397) -> cilium-test/echo-same-node-59dc776cf5-qhn8t (fd00:10:244:3::7973:8080)]
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --output /dev/null --connect-timeout 2 --max-time 10 http://[fd00:10:244:3::7973]:8080" failed: command terminated with exit code 28
```

There are some weird RSTs coming `from-host` with the host identity. This is weird:

```
Aug 29 11:49:03.669: cilium-test/client2-646b88fb9b-g945g:49480 (ID:4992) <> cilium-test/echo-same-node-59dc776cf5-qhn8t:8080 (ID:41938) from-endpoint FORWARDED (TCP Flags: SYN)
Aug 29 11:49:03.669: cilium-test/client2-646b88fb9b-g945g:49480 (ID:4992) -> cilium-test/echo-same-node-59dc776cf5-qhn8t:8080 (ID:41938) policy-verdict:L3-Only INGRESS ALLOWED (TCP Flags: SYN)
Aug 29 11:49:03.669: cilium-test/client2-646b88fb9b-g945g:49480 (ID:4992) -> cilium-test/echo-same-node-59dc776cf5-qhn8t:8080 (ID:41938) to-endpoint FORWARDED (TCP Flags: SYN)
Aug 29 11:49:03.669: cilium-test/echo-same-node-59dc776cf5-qhn8t:8080 (ID:41938) <> cilium-test/client2-646b88fb9b-g945g:49480 (ID:4992) from-endpoint FORWARDED (TCP Flags: SYN, ACK)
Aug 29 11:49:03.669: cilium-test/client2-646b88fb9b-g945g:49480 (host) <> cilium-test/echo-same-node-59dc776cf5-qhn8t:8080 (ID:41938) from-host FORWARDED (TCP Flags: RST)
Aug 29 11:49:03.669: cilium-test/client2-646b88fb9b-g945g:49480 (ID:4992) -> cilium-test/echo-same-node-59dc776cf5-qhn8t:8080 (ID:41938) to-endpoint FORWARDED (TCP Flags: RST)
```

---

[Setup & Test (2, 5.4-20230810.091425, iptables, false, disabled, ipsec, false)](https://github.com/cilium/cilium/actions/runs/6011556981/job/16305159139#logs)

```
[.] Action [echo-ingress-mutual-auth-spiffe/pod-to-pod/curl-ipv4-2: cilium-test/client2-646b88fb9b-vgmc9 (10.244.2.188) -> cilium-test/echo-other-node-f884df9df-cf7mg (10.244.1.142:8080)]
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --output /dev/null --connect-timeout 2 --max-time 10 http://10.244.1.142:8080/" failed: command terminated with exit code 28
```

There are no RSTs in this trace (at least not related to IP `10.244.2.188`), but I see that the the connection eventually succeeds, so I'm not sure why the test failed:

```
Aug 29 11:35:27.757: cilium-test/client2-646b88fb9b-vgmc9:33116 (ID:22938) <> cilium-test/echo-other-node-f884df9df-cf7mg:8080 (ID:10042) to-host FORWARDED (TCP Flags: SYN)
Aug 29 11:35:27.757: cilium-test/client2-646b88fb9b-vgmc9:33116 (ID:9) <> cilium-test/echo-other-node-f884df9df-cf7mg:8080 (ID:10042) from-host FORWARDED (TCP Flags: SYN)
Aug 29 11:35:27.757: cilium-test/client2-646b88fb9b-vgmc9:33116 (ID:22938) <> cilium-test/echo-other-node-f884df9df-cf7mg:8080 (ID:10042) policy-verdict:L3-L4 INGRESS DENIED (TCP Flags: SYN; Auth: SPIRE)
Aug 29 11:35:27.757: cilium-test/client2-646b88fb9b-vgmc9:33116 (ID:22938) <> cilium-test/echo-other-node-f884df9df-cf7mg:8080 (ID:10042) Authentication required DROPPED (TCP Flags: SYN)
Aug 29 11:35:28.784: cilium-test/client2-646b88fb9b-vgmc9:33116 (ID:22938) <> cilium-test/echo-other-node-f884df9df-cf7mg:8080 (ID:10042) from-stack FORWARDED (TCP Flags: SYN)
Aug 29 11:35:28.784: cilium-test/client2-646b88fb9b-vgmc9:33116 (ID:22938) <> cilium-test/echo-other-node-f884df9df-cf7mg:8080 (ID:10042) to-host FORWARDED (TCP Flags: SYN)
Aug 29 11:35:28.784: cilium-test/client2-646b88fb9b-vgmc9:33116 (ID:9) <> cilium-test/echo-other-node-f884df9df-cf7mg:8080 (ID:10042) from-host FORWARDED (TCP Flags: SYN)
Aug 29 11:35:28.784: cilium-test/client2-646b88fb9b-vgmc9:33116 (ID:22938) -> cilium-test/echo-other-node-f884df9df-cf7mg:8080 (ID:10042) to-endpoint FORWARDED (TCP Flags: SYN)
Aug 29 11:35:28.784: cilium-test/echo-other-node-f884df9df-cf7mg:8080 (ID:10042) <> cilium-test/client2-646b88fb9b-vgmc9:33116 (ID:22938) from-endpoint FORWARDED (TCP Flags: SYN, ACK)
Aug 29 11:35:28.784: cilium-test/client2-646b88fb9b-vgmc9:33116 (ID:22938) <- cilium-test/echo-other-node-f884df9df-cf7mg:8080 (ID:10042) to-stack FORWARDED (TCP Flags: SYN, ACK)
```

**Comment by gandro** [comment]
Given that I don't see anything wrong with the routes, and both symptoms have been observed before (see links), I'll restart again. I don't know how to otherwise troubleshoot those failures further
