### PR TITLE
pkg/k8s: use a controller manager in K8sClient

### LINKED ISSUE #17103: Cilium does not remove taint on already running nodes
## Bug report

Cilium does not remove the node taint `node.cilium.io/agent-not-ready` if the taint is set on existing node (after cilium agent started). We observe this on our AWS EKS clusters. After upgrading to Cilium `1.10.3` we added the taint to all EKS NodeGroups and EKS immediately applied the taint not only to newly started nodes but also to all already existing nodes. 

---

### Expected behaviour

Cilium should remove the taint (if cilium is ready) even if the taint is set (later) after startup. Cilium should be resilient and insistently remove the taint whenever it is added again.

### Observed behaviour 

Cilium only removes the taint if it was already set on startup. If the taint is added later to an already running node, it is not removed unless the cilium agent on that node is restarted. 

### Workaround

Manually restarting the cilium agent (` kubectl rollout restart -n kube-system daemonset/cilium`) resolved the problem. 

However, that workaround is cumbersome as it needs manual intervention, which breaks our GitOps flow and can lead to severe downtime as all nodes are not eligible for scheduling of workloads. 

---

**General Information**

- Cilium version `1.10.3`
- Kernel version `5.4.117-58.216.amzn2.x86_64`
- Orchestration system version in use `v1.19.13-eks-8df270`

**How to reproduce the issue**

1. Upgrade to or install Cilium 1.10.3 on AWS EKS cluster
2. Add node taint `node.cilium.io/agent-not-ready` to EKS NodeGroup
3. The taint is not removed until the cilium agent is restarted

### PR DESCRIPTION
**Pull request by aanm**
Since "controller.NewManager()" returns a new Manager, triggering a
controller from this newly returned manager does not work because the
manager does not have any controller set in it. In order to be able
to re-trigger controllers, a single instance of this manager is set in
the K8sClient struct.

Fixes: bd34b95a7939 ("pkg/k8s: remove node.cilium.io/agent-not-ready taint from nodes")
Signed-off-by: André Martins <andre@cilium.io>

Fixes: https://github.com/cilium/cilium/issues/17103

```release-note
Remove `node.cilium.io/agent-not-ready` node taints if they are re-added after Cilium has started
```

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by gandro — APPROVED** [review]

File: pkg/controller/controller.go [hunk 1]
```diff
@@ -282,6 +282,7 @@ func (c *Controller) runController() {
 
 		case <-runTimer.After(interval):
```
Comment (joamaki) [inline pkg/controller/controller.go:283]: Is it on purpose that we do nothing after the timer elapses? Go doesn't do case fallthrough.

Comment (joamaki) [reply pkg/controller/controller.go:283]: Indentation seems to be a bit off as well :-)

Comment (aanm) [reply pkg/controller/controller.go:283]: > Is it on purpose that we do nothing after the timer elapses? Go doesn't do case fallthrough.

We do "something". Once that timer elapses we run the function in 
https://github.com/cilium/cilium/blob/a8e3fa283cf40b330035265bf83d63800b296bcf/pkg/controller/controller.go#L206

> Indentation seems to be a bit off as well :-)

The indentation is correct, otherwise gofmt would have complained.

**Review by nathanjsweet — APPROVED** [review]

File: pkg/controller/controller.go (hunk 1 above)
Comment (joamaki) [reply pkg/controller/controller.go:283]: Ah now I get the logic. And I guess it's just github not showing it properly.

**Review by joamaki — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-gke

**Comment by aanm** [comment]
test-1.20-4.19

**Comment by aanm** [comment]
ci-gke
