### PR TITLE
policy/k8s: Fix deadlock in ToServices implementation

### LINKED ISSUE #33675: Cilium agents fall into an infinite restarts loop after update
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When update Cilium to vr 1.16.0-rc.1 in EKS cluster with up to 150+ nodes Cilium agents fall into an infinite restarts loop with error:  `error="timed out after 3m0s since receiving last event for resource \"core/v1::Service\`. The API endpoint is different every time, usually I can catche: `Service`, `CiliumCIDRGroup` or `CiliumNetworkPolicy`. Same installation works fine in EKS cluster with ~30 nodes.

### Cilium Version

1.16.0-rc.1

### Kernel Version

EKS 1.26

### Kubernetes Version

Client Version: v1.27.12
Kustomize Version: v5.0.1
Server Version: v1.26.15-eks-3af477

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell
EnableDefaultDeny:{Ingress:0xc0062a1fdc Egress:0xc0062a1fdb} Description:}]" policyAddRequest=4f3d96ae-3db6-427b-807d-5351a2f2cea4 subsys=daemon
time="2024-07-09T11:35:18Z" level=info msg="Policy imported via API, recalculating..." policyAddRequest=4f3d96ae-3db6-427b-807d-5351a2f2cea4 policyRevision=12 subsys=daemon
time="2024-07-09T11:35:18Z" level=info msg="Imported CiliumNetworkPolicy" ciliumNetworkPolicyName=sip k8sApiVersion=cilium.io/v2 k8sNamespace=sip subsys=policy-k8s-watcher
time="2024-07-09T11:35:38Z" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=1
time="2024-07-09T11:35:39Z" level=info msg="starting xDS stream processing" subsys=xds xdsStreamID=2
time="2024-07-09T11:38:18Z" level=fatal msg="Timed out waiting for pre-existing resources to be received; exiting" error="timed out after 3m0s since receiving last event for resource \"core/v1::Service\"" subsys=k8s-watcher
```

### Anything else?

_No response_

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by gandro**
This commit fixes a deadlock between the `k8s.ServiceCache` and `policyWatcher`. The interaction between the two components is as follows:

1. `ServiceCache` observes a service change event, this is forwarded to `policyWatcher` in a buffered channel (default capacity 128).
2. `policyWatcher` receives the service event, determines if any CNPs are affected by this service event, and then calls back into the `ServiceCache` via `ForEachService` to determine the endpoints for each service.

This unfortunately can lead to a deadlock when the notifications channel fills up: `ServiceCache` will attempt to send the next notification with its mutex held, while `policyWatcher` attempts concurrently call into `ForEachService`, which attempts to acquire the `ServiceCache` mutex, thereby causing a deadlock.

This commit works around this issue by queueing received notifications in an unbounded queue. This way, the `ServiceCache` sender is never blocked, as it will always be able to enqueue a notification.

This is not a very elegant solution, but it solves the issue without restructuring the code too much. The proper long-term solution is to likely use per-CIDR labels to implement `ToServices` in policy, similar to cilium/cilium#33441. This would not only simplify the `policyWatcher` logic and decouple it from the `ServiceCache`, it would also reduce the number of policy maps updated whenever the endpoints of a selected service change.

Fixes: #33675

### CODE REVIEW

**Review by aanm — APPROVED** [review]

File: pkg/policy/k8s/service_test.go [hunk 1]
```diff
@@ -732,3 +735,40 @@ func Test_hasMatchingToServices(t *testing.T) {
...
+	require.Equal(t, k8s.ServiceNotification{ID: k8s.ServiceID{Name: "svc2"}}, <-downstream)
+	require.Equal(t, k8s.ServiceNotification{ID: k8s.ServiceID{Name: "svc3"}}, <-downstream)
+	require.Empty(t, downstream)
+
+	// Test that Go routine exits on empty upstream if ctx is cancelled
+	cancel()
+	_, ok := <-downstream
+	require.False(t, ok, "service notification channel was not closed on cancellation")
+
+	// Test that Go routine exits on upstream close
```
Comment (derailed) [inline pkg/policy/k8s/service_test.go:762]: This may warrant a separate test(s) to test channel closure and gor exist?

File: pkg/policy/k8s/service_test.go [hunk 2]
```diff
@@ -732,3 +735,40 @@ func Test_hasMatchingToServices(t *testing.T) {
...
+
+func Test_serviceNotificationsQueue(t *testing.T) {
+	ctx, cancel := context.WithCancel(context.Background())
+	defer cancel()
+
+	upstream := make(chan k8s.ServiceNotification)
+	downstream := serviceNotificationsQueue(ctx, stream.FromChannel(upstream))
+
+	// Test that sending events in upstream does not block on unbuffered channel
+	upstream <- k8s.ServiceNotification{ID: k8s.ServiceID{Name: "svc1"}}
```
Comment (derailed) [inline pkg/policy/k8s/service_test.go:747]: We could dry this up a bit by declaring svc1,2,3 vars and use on enqueue/dequeue.

**Review by derailed — APPROVED** [review]
@gandro Nice work! Hopefully we'll revisit soon...

File: pkg/policy/k8s/service_test.go (hunk 2 above)
Comment (gandro) [reply pkg/policy/k8s/service_test.go:747]: Thanks for the suggestion! I wanted to make sure we do an e2e test, rather than testing enqueue/dequeue. The important behavior to assert is that it doesn't block the producer, thereby solving the deadlock
