### PR TITLE
endpoint: Write headerfile under full regeneration

### LINKED ISSUE #12005: cilium endpoint regenerate broken
```
root@apoc:~/go/src/github.com/cilium/cilium# ./cilium/cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])   IPv6               IPv4            STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                   
84         Disabled           Disabled          7008       no labels                     2001:db8:5::4817   10.29.71.199    ready   
1038       Disabled           Disabled          7008       no labels                     2001:db8:5::60a9   10.29.218.124   ready   
1184       Disabled           Disabled          4          reserved:health               2001:db8:5::f395   10.29.52.34     ready   
2817       Disabled           Disabled          1          reserved:host                                                    ready  

root@apoc:~/go/src/github.com/cilium/cilium# ./cilium/cilium endpoint regenerate 84
Endpoint 84 successfully regenerated
```
Agent log, looks like it's trying to generate a per-EP CT map:
```
level=error msg="Failed to compile bpf_lxc.o: exit status 1" compiler-pid=20856 linker-pid=20857 subsys=datapath-loader
level=warning msg="In file included from /var/lib/cilium/bpf/bpf_lxc.c:8:" subsys=datapath-loader
level=warning msg="/var/run/cilium/state/globals/node_config.h:22:9: error: 'CT_MAP_TCP4' macro redefined [-Werror,-Wmacro-redefined]" subsys=datapath-loader
level=warning msg="#define CT_MAP_TCP4 cilium_ct4_global" subsys=datapath-loader
level=warning msg="        ^" subsys=datapath-loader
level=warning msg="/var/lib/cilium/bpf/ep_config.h:39:9: note: previous definition is here" subsys=datapath-loader
level=warning msg="#define CT_MAP_TCP4 test_cilium_ct_tcp4_65535" subsys=datapath-loader
level=warning msg="        ^" subsys=datapath-loader
level=warning msg="In file included from /var/lib/cilium/bpf/bpf_lxc.c:8:" subsys=datapath-loader
level=warning msg="/var/run/cilium/state/globals/node_config.h:23:9: error: 'CT_MAP_ANY4' macro redefined [-Werror,-Wmacro-redefined]" subsys=datapath-loader
level=warning msg="#define CT_MAP_ANY4 cilium_ct_any4_global" subsys=datapath-loader
level=warning msg="        ^" subsys=datapath-loader
level=warning msg="/var/lib/cilium/bpf/ep_config.h:40:9: note: previous definition is here" subsys=datapath-loader
level=warning msg="#define CT_MAP_ANY4 test_cilium_ct_any4_65535" subsys=datapath-loader
level=warning msg="        ^" subsys=datapath-loader
level=warning msg="In file included from /var/lib/cilium/bpf/bpf_lxc.c:8:" subsys=datapath-loader
level=warning msg="/var/run/cilium/state/globals/node_config.h:24:9: error: 'CT_MAP_TCP6' macro redefined [-Werror,-Wmacro-redefined]" subsys=datapath-loader
level=warning msg="#define CT_MAP_TCP6 cilium_ct6_global" subsys=datapath-loader
level=warning msg="        ^" subsys=datapath-loader
level=warning msg="/var/lib/cilium/bpf/ep_config.h:37:9: note: previous definition is here" subsys=datapath-loader
level=warning msg="#define CT_MAP_TCP6 test_cilium_ct_tcp6_65535" subsys=datapath-loader
level=warning msg="        ^" subsys=datapath-loader
level=warning msg="In file included from /var/lib/cilium/bpf/bpf_lxc.c:8:" subsys=datapath-loader
level=warning msg="/var/run/cilium/state/globals/node_config.h:25:9: error: 'CT_MAP_ANY6' macro redefined [-Werror,-Wmacro-redefined]" subsys=datapath-loader
level=warning msg="#define CT_MAP_ANY6 cilium_ct_any6_global" subsys=datapath-loader
level=warning msg="        ^" subsys=datapath-loader
level=warning msg="/var/lib/cilium/bpf/ep_config.h:38:9: note: previous definition is here" subsys=datapath-loader
level=warning msg="#define CT_MAP_ANY6 test_cilium_ct_any6_65535" subsys=datapath-loader
level=warning msg="        ^" subsys=datapath-loader
level=warning msg="In file included from /var/lib/cilium/bpf/bpf_lxc.c:8:" subsys=datapath-loader
level=warning msg="/var/run/cilium/state/globals/node_config.h:26:9: error: 'CT_MAP_SIZE_TCP' macro redefined [-Werror,-Wmacro-redefined]" subsys=datapath-loader
level=warning msg="#define CT_MAP_SIZE_TCP 524288" subsys=datapath-loader
level=warning msg="        ^" subsys=datapath-loader
level=warning msg="/var/lib/cilium/bpf/ep_config.h:41:9: note: previous definition is here" subsys=datapath-loader
level=warning msg="#define CT_MAP_SIZE_TCP 4096" subsys=datapath-loader
level=warning msg="        ^" subsys=datapath-loader
level=warning msg="In file included from /var/lib/cilium/bpf/bpf_lxc.c:8:" subsys=datapath-loader
level=warning msg="/var/run/cilium/state/globals/node_config.h:27:9: error: 'CT_MAP_SIZE_ANY' macro redefined [-Werror,-Wmacro-redefined]" subsys=datapath-loader
level=warning msg="#define CT_MAP_SIZE_ANY 262144" subsys=datapath-loader
level=warning msg="        ^" subsys=datapath-loader
level=warning msg="/var/lib/cilium/bpf/ep_config.h:42:9: note: previous definition is here" subsys=datapath-loader
level=warning msg="#define CT_MAP_SIZE_ANY 4096" subsys=datapath-loader
level=warning msg="        ^" subsys=datapath-loader
level=warning msg="In file included from /var/lib/cilium/bpf/bpf_lxc.c:22:" subsys=datapath-loader
level=warning msg="/var/lib/cilium/bpf/lib/icmp6.h:33:29: error: use of undeclared identifier 'NODE_MAC'" subsys=datapath-loader
level=warning msg="        union macaddr smac, dmac = NODE_MAC;" subsys=datapath-loader
level=warning msg="                                   ^" subsys=datapath-loader
level=warning msg="/var/lib/cilium/bpf/lib/icmp6.h:342:30: error: use of undeclared identifier 'NODE_MAC'" subsys=datapath-loader
level=warning msg="                union macaddr router_mac = NODE_MAC;" subsys=datapath-loader
level=warning msg="                                           ^" subsys=datapath-loader
level=warning msg="In file included from /var/lib/cilium/bpf/bpf_lxc.c:26:" subsys=datapath-loader
level=warning msg="/var/lib/cilium/bpf/lib/lxc.h:67:29: error: use of undeclared identifier 'NODE_MAC'" subsys=datapath-loader
level=warning msg="        union macaddr router_mac = NODE_MAC;" subsys=datapath-loader
level=warning msg="                                   ^" subsys=datapath-loader
level=warning msg="9 errors generated." subsys=datapath-loader
level=warning msg="JoinEP: Failed to compile" containerID=f93fd3aa58 datapathPolicyRevision=1 debug=false desiredPolicyRevision=1 endpointID=84 error="Failed to compile bpf_lxc.o: exit status 1" identity=7008 ipv4=10.29.71.199 ipv6="2001:db8:5::4817" k8sPodName=/ params="&{Source:bpf_lxc.c Output:bpf_lxc.o OutputType:obj}" subsys=datapath-loader
level=info msg="Regenerated endpoint BPF program" containerID=f93fd3aa58 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=84 error="Failed to compile bpf_lxc.o: exit status 1" identity=7008 ipv4=10.29.71.199 ipv6="2001:db8:5::4817" k8sPodName=/ subsys=endpoint
level=warning msg="generating BPF for endpoint failed, keeping stale directory." containerID=f93fd3aa58 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=84 file-path=84_next_fail identity=7008 ipv4=10.29.71.199 ipv6="2001:db8:5::4817" k8sPodName=/ subsys=endpoint
level=warning msg="Regeneration of endpoint failed" bpfCompilation=92.742911ms bpfLoadProg=0s bpfWaitForELF=0s bpfWriteELF=0s buildDuration=93.000511ms containerID=f93fd3aa58 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=84 error="Failed to compile bpf_lxc.o: exit status 1" identity=7008 ipv4=10.29.71.199 ipv6="2001:db8:5::4817" k8sPodName=/ mapSync=806ns policyCalculation="2.993µs" prepareBuild="72.888µs" proxyConfiguration="5.486µs" proxyPolicyCalculation="81.856µs" proxyWaitForAck=0s reason="endpoint was manually regenerated via API" subsys=endpoint waitingForCTClean=203ns waitingForLock="11.691µs"
level=error msg="endpoint regeneration failed" containerID=f93fd3aa58 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=84 error="Failed to compile bpf_lxc.o: exit status 1" identity=7008 ipv4=10.29.71.199 ipv6="2001:db8:5::4817" k8sPodName=/ subsys=endpoint
level=info msg="Rewrote endpoint BPF program" containerID=f93fd3aa58 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=84 identity=7008 ipv4=10.29.71.199 ipv6="2001:db8:5::4817" k8sPodName=/ subsys=endpoint
```
Despite ConntrackLocal being disabled:
```
# ./cilium/cilium config
Conntrack                Enabled
ConntrackAccounting      Enabled
ConntrackLocal           Disabled
Debug                    Disabled
DebugLB                  Disabled
DropNotification         Enabled
MonitorAggregationLevel  None
PolicyAuditMode          Disabled
PolicyTracing            Disabled
PolicyVerdictNotification Enabled
TraceNotification        Enabled
k8s-configuration        
k8s-endpoint             
PolicyEnforcement        default

# ./cilium/cilium endpoint config  84
Conntrack                Enabled
ConntrackAccounting      Enabled
ConntrackLocal           Disabled
Debug                    Disabled
DebugLB                  Disabled
DropNotification         Enabled
MonitorAggregationLevel  None
NAT46                    Disabled
PolicyAuditMode          Disabled
PolicyVerdictNotification Enabled
TraceNotification        Enabled
```

### PR DESCRIPTION
**Pull request by christarazi**
Previously, regenerating an endpoint manually via CLI resulted in
compilation errors as seen below. These errors occurred because the
endpoint headerfile (ep_config.h or lxc_config.h) was not written to the
`<endpoint ID>_next` directory (will be reffered to as "next"), where
the BPF compilation takes place.

The reason the headerfile was not written to the "next" directory was
because Cilium only wrote the headerfile if it was changed (via hash).
However, a manual regeneration triggered through the API, sets the
regeneration level to "compile+load" (a full regeneration), where Cilium
expects all relevant files, including the headerfile, to be present in
the "next" directory (`<endpoint ID>_next`). Hence, the compilation
errors.

This commit fixes this issue by checking whether there has been a
request for a full regeneration, in which case, we write the headerfile
to the "next" directory.

```
root@k8s2:/var/run/cilium/state# clang -emit-llvm -O2 -target bpf -std=gnu89 -nostdinc -D__NR_CPUS__=2 -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-s
ized-type-not-at-end -Wdeclaration-after-statement -I/var/run/cilium/state/globals -I1285_next -I/var/lib/cilium/bpf -I/var/lib/cilium/bpf/include -c /var/lib/cilium/bpf/bpf_lxc.c -o /tmp/c
In file included from /var/lib/cilium/bpf/bpf_lxc.c:22:
/var/lib/cilium/bpf/lib/icmp6.h:50:29: error: use of undeclared identifier 'NODE_MAC'
        union macaddr smac, dmac = NODE_MAC;
                                   ^
/var/lib/cilium/bpf/lib/icmp6.h:359:30: error: use of undeclared identifier 'NODE_MAC'
                union macaddr router_mac = NODE_MAC;
                                           ^
In file included from /var/lib/cilium/bpf/bpf_lxc.c:26:
/var/lib/cilium/bpf/lib/lxc.h:67:29: error: use of undeclared identifier 'NODE_MAC'
        union macaddr router_mac = NODE_MAC;
                                   ^
/var/lib/cilium/bpf/bpf_lxc.c:159:10: error: implicit declaration of function 'lookup_ip6_remote_endpoint' [-Werror,-Wimplicit-function-declaration]
                info = lookup_ip6_remote_endpoint(&orig_dip);
                       ^
/var/lib/cilium/bpf/bpf_lxc.c:159:10: note: did you mean 'lookup_ip6_endpoint'?
/var/lib/cilium/bpf/lib/eps.h:13:1: note: 'lookup_ip6_endpoint' declared here
lookup_ip6_endpoint(struct ipv6hdr *ip6)
^
/var/lib/cilium/bpf/bpf_lxc.c:159:8: error: incompatible integer to pointer conversion assigning to 'struct remote_endpoint_info *' from 'int' [-Werror,-Wint-conversion]
                info = lookup_ip6_remote_endpoint(&orig_dip);
                     ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/cilium/bpf/bpf_lxc.c:529:10: error: implicit declaration of function 'lookup_ip4_remote_endpoint' [-Werror,-Wimplicit-function-declaration]
                info = lookup_ip4_remote_endpoint(orig_dip);
                       ^
/var/lib/cilium/bpf/bpf_lxc.c:529:10: note: did you mean 'lookup_ip4_endpoint'?
/var/lib/cilium/bpf/lib/eps.h:35:1: note: 'lookup_ip4_endpoint' declared here
lookup_ip4_endpoint(const struct iphdr *ip4)
^
/var/lib/cilium/bpf/bpf_lxc.c:529:8: error: incompatible integer to pointer conversion assigning to 'struct remote_endpoint_info *' from 'int' [-Werror,-Wint-conversion]
                info = lookup_ip4_remote_endpoint(orig_dip);
                     ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/cilium/bpf/bpf_lxc.c:1027:10: error: implicit declaration of function 'lookup_ip6_remote_endpoint' [-Werror,-Wimplicit-function-declaration]
                info = lookup_ip6_remote_endpoint(src);
                       ^
/var/lib/cilium/bpf/bpf_lxc.c:1027:8: error: incompatible integer to pointer conversion assigning to 'struct remote_endpoint_info *' from 'int' [-Werror,-Wint-conversion]
                info = lookup_ip6_remote_endpoint(src);
                     ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/cilium/bpf/bpf_lxc.c:1256:10: error: implicit declaration of function 'lookup_ip4_remote_endpoint' [-Werror,-Wimplicit-function-declaration]
                info = lookup_ip4_remote_endpoint(ip4->saddr);
                       ^
/var/lib/cilium/bpf/bpf_lxc.c:1256:8: error: incompatible integer to pointer conversion assigning to 'struct remote_endpoint_info *' from 'int' [-Werror,-Wint-conversion]
                info = lookup_ip4_remote_endpoint(ip4->saddr);
                     ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11 errors generated.
```

Fixes https://github.com/cilium/cilium/pull/10630
Fixes https://github.com/cilium/cilium/issues/12005

```release-note
Fix manual endpoint regeneration via command line
```

### CODE REVIEW

**Comment by christarazi** [comment]
I ran into this bug while debugging https://github.com/cilium/cilium/pull/12482 and looked into it. I'm not 100% sure on the implementation of this, but it does seem reasonable to me. I'd like to get feedback from those who have more context in the regenerating endpoints. 

@joestringer The code touches recently changed parts by you. It'd be great to have your feedback.

**Comment by christarazi** [comment]
test-me-please

File: pkg/endpoint/bpf.go [hunk 1]
```diff
@@ -870,6 +870,11 @@ func (e *Endpoint) runPreCompilationSteps(regenContext *regenerationContext) (he
 		if err = e.writeHeaderfile(nextDir); err != nil {
 			return false, fmt.Errorf("unable to write header file: %s", err)
 		}
+	} else if datapathRegenCtxt.regenerationLevel == regeneration.RegenerateWithDatapathRebuild {
```
Comment (joestringer) [inline pkg/endpoint/bpf.go]: We could probably tweak this to avoid duplicating the `writeHeaderfile()` call by instead having the `headerfileChanged` check above only set the `regenerationLevel` then have this check do the following instead:

```suggestion
	if datapathRegenCtxt.regenerationLevel >= regeneration.RegenerateWithDatapathRewrite {
```

Then I'm not sure whether the comment below provides any additional context; basically if either a rewrite or rebuild is required, we'll be sure to write the headerfile again.

**Review by joestringer — CHANGES_REQUESTED** [review]
Minor nit, I think we can have this be a little more concise but the change LGTM.

**Comment by joestringer** [comment]
May be worth considering whether we should backport this. In an ideal circumstance we should never need this, but even for development purposes for backports and so on it may turn out to be useful. I note that the referred PR that this marks as "Fixes" was also attempting to fix a broader version of this bug and was backported to v1.6; hopefully this will bring the saga to a close :-)

**Comment by christarazi** [comment]
> May be worth considering whether we should backport this. In an ideal circumstance we should never need this, but even for development purposes for backports and so on it may turn out to be useful. I note that the referred PR that this marks as "Fixes" was also attempting to fix a broader version of this bug and was backported to v1.6; hopefully this will bring the saga to a close :-)

I was thinking that as well. It's not a crucial bug, but the backports should be trivial as the change is small and code paths are consistent in all relevant trees.

File: pkg/endpoint/bpf.go (hunk 1 above)
Comment (christarazi) [reply pkg/endpoint/bpf.go]: Done

**Review by joestringer — APPROVED** [review]

**Comment by pchaigno** [comment]
@christarazi Did you check if this fix also works for the host endpoint? I can have a look as a follow up if not.

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
test-me-please

**Review by qmonnet — APPROVED** [review]

**Review by borkmann — APPROVED** [review]
lgtm as far as I can see
