### PR TITLE
ipcache: Fix deadlock when ipcache GC results in datapath reload

### LINKED ISSUE #11690: v1.8: CI: K8sDatapathConfig Etcd Check connectivity
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Kernel/1645/testReport/Suite-k8s-1/17/K8sDatapathConfig_Etcd_Check_connectivity/

According to the dashboard, this test has been flaky since it was added on May 15.
One Cilium pod is reported unhealthy with one of the following:
```
Error: Cannot get status/probe: Put "http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe": dial unix /var/run/cilium/health.sock: connect: no such file or directory
Error: Cannot get status/probe: Put "http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe": context deadline exceeded
```
but the logs and other commands (e.g., `cilium status` or `cilium endpoint list`) show that everything is okay.

## Stacktrace
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Kernel/k8s-1.17-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:471
cilium pre-flight checks failed
Expected
    <*errors.errorString | 0xc000291a30>: {
        s: "Cilium validation failed: 4m0s timeout expired: Last polled error: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-dfkrf': Exitcode: 255 \nStdout:\n \t \nStderr:\n \t Error: Cannot get status/probe: Put \"http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe\": context deadline exceeded\n\t \n\t command terminated with exit code 255\n\t \n",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Kernel/k8s-1.17-gopath/src/github.com/cilium/cilium/test/helpers/manifest.go:297
```

## Standard output
```
⚠️  Number of "context deadline exceeded" in logs: 20
Number of "level=error" in logs: 0
⚠️  Number of "level=warning" in logs: 30
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
Top 5 errors/warnings:
Mutation detector is enabled, this will result in memory leakage.
BPF system config check: NOT OK.
BPF NodePort's external facing device could not be determined. Use --device to specify. Disabling BPF NodePort feature.
sessionAffinity for host reachable services needs kernel 5.7.0 or newer. Disabling sessionAffinity for cases when a service is accessed from a cluster.
Hubble server will be exposing its API insecurely on this address
Cilium pods: [cilium-dfkrf cilium-nhkx8]
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
Pod                        Ingress   Egress
coredns-767d4c6dd7-4wcvd             
Cilium agent 'cilium-dfkrf': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 30 Failed 0
Cilium agent 'cilium-nhkx8': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 24 Failed 0
```

## Standard error
<details><summary>Show standard error</summary>
<p>

```
16:41:54 STEP: Deploying etcd-deployment.yaml in namespace kube-system
16:41:54 STEP: Waiting for 4m0s for 1 pods of deployment etcd-deployment.yaml to become ready
16:41:54 STEP: WaitforNPods(namespace="kube-system", filter="")
16:41:54 STEP: WaitforNPods(namespace="kube-system", filter="") => <nil>
16:41:54 STEP: Installing Cilium
16:41:54 STEP: Waiting for Cilium to become ready
16:41:54 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
16:41:59 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
16:42:04 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
16:42:09 STEP: Cilium DaemonSet not ready yet: only 1 of 2 desired pods are ready
16:42:14 STEP: Cilium DaemonSet not ready yet: only 1 of 2 desired pods are ready
16:42:19 STEP: Cilium DaemonSet not ready yet: only 1 of 2 desired pods are ready
16:42:24 STEP: Number of ready Cilium pods: 2
16:42:24 STEP: Installing DNS Deployment
16:42:24 STEP: Restarting DNS Pods
16:42:39 STEP: Validating Cilium Installation
16:42:39 STEP: Performing Cilium status preflight check
16:42:39 STEP: Performing Cilium health check
16:42:39 STEP: Performing Cilium controllers preflight check
16:42:47 STEP: Performing Cilium service preflight check
16:42:47 STEP: Performing K8s service preflight check
16:42:47 STEP: Cilium is not ready yet: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-dfkrf': Exitcode: 255 
Stdout:
 	 
Stderr:
 	 Error: Cannot get status/probe: Put "http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe": dial unix /var/run/cilium/health.sock: connect: no such file or directory
	 
	 command terminated with exit code 255
	 

16:42:47 STEP: Performing Cilium status preflight check
16:42:47 STEP: Performing Cilium controllers preflight check
16:42:47 STEP: Performing Cilium health check
16:42:55 STEP: Performing Cilium service preflight check
16:42:55 STEP: Performing K8s service preflight check
16:43:19 STEP: Cilium is not ready yet: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-dfkrf': Exitcode: 255 
Stdout:
 	 
Stderr:
 	 Error: Cannot get status/probe: Put "http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe": context deadline exceeded
	 
	 command terminated with exit code 255
	 

16:43:19 STEP: Performing Cilium controllers preflight check
16:43:19 STEP: Performing Cilium status preflight check
16:43:19 STEP: Performing Cilium health check
16:43:24 STEP: Performing Cilium service preflight check
16:43:24 STEP: Performing K8s service preflight check
16:43:51 STEP: Performing Cilium status preflight check
16:43:51 STEP: Performing Cilium health check
16:43:51 STEP: Performing Cilium controllers preflight check
16:43:59 STEP: Performing Cilium service preflight check
16:43:59 STEP: Performing K8s service preflight check
16:44:22 STEP: Performing Cilium status preflight check
16:44:22 STEP: Performing Cilium health check
16:44:22 STEP: Performing Cilium controllers preflight check
16:44:31 STEP: Performing Cilium service preflight check
16:44:31 STEP: Performing K8s service preflight check
16:44:54 STEP: Performing Cilium status preflight check
16:44:54 STEP: Performing Cilium controllers preflight check
16:44:54 STEP: Performing Cilium health check
16:45:02 STEP: Performing Cilium service preflight check
16:45:02 STEP: Performing K8s service preflight check
16:45:25 STEP: Performing Cilium status preflight check
16:45:25 STEP: Performing Cilium health check
16:45:25 STEP: Performing Cilium controllers preflight check
16:45:31 STEP: Performing Cilium service preflight check
16:45:31 STEP: Performing K8s service preflight check
16:45:57 STEP: Performing Cilium status preflight check
16:45:57 STEP: Performing Cilium controllers preflight check
16:45:57 STEP: Performing Cilium health check
16:46:04 STEP: Performing Cilium service preflight check
16:46:04 STEP: Performing K8s service preflight check
16:46:29 STEP: Cilium is not ready yet: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-dfkrf': Exitcode: 255 
Stdout:
 	 
Stderr:
 	 Error: Cannot get status/probe: Put "http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe": context deadline exceeded
	 
	 command terminated with exit code 255
	 

16:46:29 STEP: Performing Cilium status preflight check
16:46:29 STEP: Performing Cilium controllers preflight check
16:46:29 STEP: Performing Cilium health check
16:46:37 STEP: Performing Cilium service preflight check
16:46:37 STEP: Performing K8s service preflight check
FAIL: cilium pre-flight checks failed
Expected
    <*errors.errorString | 0xc000291a30>: {
        s: "Cilium validation failed: 4m0s timeout expired: Last polled error: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-dfkrf': Exitcode: 255 \nStdout:\n \t \nStderr:\n \t Error: Cannot get status/probe: Put \"http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe\": context deadline exceeded\n\t \n\t command terminated with exit code 255\n\t \n",
    }
to be nil
=== Test Finished at 2020-05-21T16:46:39Z====
16:46:39 STEP: Running JustAfterEach block for K8sDatapathConfig
===================== TEST FAILED =====================
16:46:39 STEP: Running AfterFailed block for K8sDatapathConfig
16:46:39 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium")
16:46:39 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium") => <nil>
16:46:42 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium")
16:46:42 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium") => <nil>
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE     NAME                               READY   STATUS    RESTARTS   AGE     IP              NODE   NOMINATED NODE   READINESS GATES
	 kube-system   cilium-dfkrf                       1/1     Running   0          4m49s   192.168.36.12   k8s2   <none>           <none>
	 kube-system   cilium-nhkx8                       1/1     Running   0          4m49s   192.168.36.11   k8s1   <none>           <none>
	 kube-system   cilium-operator-5b7944dcc8-lhjdc   1/1     Running   0          4m49s   192.168.36.12   k8s2   <none>           <none>
	 kube-system   coredns-767d4c6dd7-4wcvd           1/1     Running   0          4m19s   10.0.1.212      k8s2   <none>           <none>
	 kube-system   etcd-k8s1                          1/1     Running   0          66m     192.168.36.11   k8s1   <none>           <none>
	 kube-system   kube-apiserver-k8s1                1/1     Running   0          66m     192.168.36.11   k8s1   <none>           <none>
	 kube-system   kube-controller-manager-k8s1       1/1     Running   0          66m     192.168.36.11   k8s1   <none>           <none>
	 kube-system   kube-proxy-khm7w                   1/1     Running   0          64m     192.168.36.12   k8s2   <none>           <none>
	 kube-system   kube-proxy-p6vvj                   1/1     Running   0          66m     192.168.36.11   k8s1   <none>           <none>
	 kube-system   kube-scheduler-k8s1                1/1     Running   0          66m     192.168.36.11   k8s1   <none>           <none>
	 kube-system   log-gatherer-hvfr2                 1/1     Running   0          64m     192.168.36.12   k8s2   <none>           <none>
	 kube-system   log-gatherer-mlt9z                 1/1     Running   0          64m     192.168.36.11   k8s1   <none>           <none>
	 kube-system   registry-adder-4q8s8               1/1     Running   0          64m     192.168.36.12   k8s2   <none>           <none>
	 kube-system   registry-adder-84kvl               1/1     Running   0          64m     192.168.36.11   k8s1   <none>           <none>
	 kube-system   stateless-etcd-7b9bfffcbd-lvcz7    1/1     Running   0          4m49s   192.168.36.12   k8s2   <none>           <none>
	 
Stderr:
 	 

Fetching command output from pods [cilium-dfkrf cilium-nhkx8]
16:46:45 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium")
16:46:45 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium") => <nil>
16:46:47 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium")
16:46:47 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium") => <nil>
16:46:49 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium")
16:46:49 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium") => <nil>
16:46:51 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium")
16:46:51 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium") => <nil>
16:46:52 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium")
16:46:53 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium") => <nil>
16:46:56 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium")
16:46:56 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium") => <nil>
16:46:58 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium")
16:46:59 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium") => <nil>
16:47:21 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs")
16:47:21 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs") => <nil>
16:47:23 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs")
16:47:23 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs") => <nil>
16:47:26 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs")
16:47:26 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs") => <nil>
cmd: kubectl exec -n kube-system cilium-dfkrf -- cilium status
Exitcode: 0 
Stdout:
 	 KVStore:                Ok   etcd: 1/1 connected, lease-ID=7c0272381d05963a, lock lease-ID=7c0272381d05963c, has-quorum=true: http://10.101.171.39:2379 - 3.4.7 (Leader)
	 Kubernetes:             Ok   1.17 (v1.17.5) [linux/amd64]
	 Kubernetes APIs:        ["CustomResourceDefinition", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumNetworkPolicy", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1beta1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
	 KubeProxyReplacement:   Probe   ()   [HostReachableServices (TCP, UDP)]
	 Cilium:                 Ok      OK
	 NodeMonitor:            Listening for events on 3 CPUs with 64x4096 of shared memory
	 Cilium health daemon:   Ok   
	 IPAM:                   IPv4: 3/255 allocated from 10.0.1.0/24, IPv6: 3/255 allocated from fd00::100/120
	 Controller Status:      30/30 healthy
	 Proxy Status:           OK, ip 10.0.1.223, 0 redirects active on ports 10000-20000
	 Hubble:                 Ok              Current/Max Flows: 4096/4096 (100.00%), Flows/s: 18.54   Metrics: Disabled
	 Cluster health:         1/2 reachable   (2020-05-21T16:46:00Z)
	   Name                  IP              Reachable   Endpoints reachable
	   k8s1                  192.168.36.11   true        false
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-dfkrf -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                       IPv6        IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                             
	 2485       Disabled           Disabled          44021      k8s:io.cilium.k8s.policy.cluster=default          fd00::1be   10.0.1.212   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=coredns                                    
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                        
	                                                            k8s:k8s-app=kube-dns                                                               
	 2986       Disabled           Disabled          4          reserved:health                                   fd00::1ca   10.0.1.49    ready   
	 4045       Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s2                                                 ready   
	                                                            reserved:host                                                                      
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-nhkx8 -- cilium status
Exitcode: 0 
Stdout:
 	 KVStore:                Ok   etcd: 1/1 connected, lease-ID=7c0272381d059605, lock lease-ID=7c0272381d059607, has-quorum=true: http://10.101.171.39:2379 - 3.4.7 (Leader)
	 Kubernetes:             Ok   1.17 (v1.17.5) [linux/amd64]
	 Kubernetes APIs:        ["CustomResourceDefinition", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumNetworkPolicy", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1beta1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
	 KubeProxyReplacement:   Probe   ()   [HostReachableServices (TCP, UDP)]
	 Cilium:                 Ok      OK
	 NodeMonitor:            Listening for events on 3 CPUs with 64x4096 of shared memory
	 Cilium health daemon:   Ok   
	 IPAM:                   IPv4: 2/255 allocated from 10.0.0.0/24, IPv6: 2/255 allocated from fd00::/120
	 Controller Status:      24/24 healthy
	 Proxy Status:           OK, ip 10.0.0.39, 0 redirects active on ports 10000-20000
	 Hubble:                 Ok              Current/Max Flows: 3821/4096 (93.29%), Flows/s: 13.87   Metrics: Disabled
	 Cluster health:         2/2 reachable   (2020-05-21T16:45:36Z)
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-nhkx8 -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])          IPv6       IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                               
	 253        Disabled           Disabled          4          reserved:health                      fd00::b7   10.0.0.247   ready   
	 1323       Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s1                                   ready   
	                                                            k8s:node-role.kubernetes.io/master                                   
	                                                            reserved:host                                                        
	 
Stderr:
```
</p>
</details>

[68ee983f_K8sDatapathConfig_Etcd_Check_connectivity.zip](https://github.com/cilium/cilium/files/4681812/68ee983f_K8sDatapathConfig_Etcd_Check_connectivity.zip)

### LINKED ISSUE #11946: Deadlock between ipcache GC and endpoint regeneration injecting ipcache entry via FQDN
### Routine 1:

The following go routine holds the ipcache mutex while garbage collecting:

```
goroutine 779 [semacquire, 48 minutes]:
sync.runtime_SemacquireMutex(0xc0008f4f68, 0xc007663600, 0x0)
        /usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*RWMutex).Lock(0xc0008f4f60)
        /usr/local/go/src/sync/rwmutex.go:103 +0x88
github.com/cilium/cilium/pkg/datapath/loader.(*Loader).Reinitialize(0xc0003d70a0, 0x2759d20, 0xc000468bc0, 0x2771e60, 0xc000515680, 0x2329, 0x7f87768eac80, 0xc00022ff10, 0x26faf60, 0xc0004a18b0, ...)
        /go/src/github.com/cilium/cilium/pkg/datapath/loader/base.go:124 +0xcd
main.(*Daemon).TriggerReloadWithoutCompile(0xc000515680, 0x2332316, 0x10, 0x12, 0xc008f75060, 0x16)
        /go/src/github.com/cilium/cilium/daemon/daemon.go:588 +0x202
github.com/cilium/cilium/pkg/datapath/ipcache.(*BPFListener).garbageCollect(0xc0006f8960, 0x2759d20, 0xc003748000, 0x0, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/datapath/ipcache/listener.go:306 +0xadc
github.com/cilium/cilium/pkg/datapath/ipcache.(*BPFListener).OnIPIdentityCacheGC.func1(0x2759d20, 0xc003748000, 0x3a5bf00, 0x2)
        /go/src/github.com/cilium/cilium/pkg/datapath/ipcache/listener.go:340 +0x3e
github.com/cilium/cilium/pkg/controller.(*Controller).runController(0xc001e1e000)
        /go/src/github.com/cilium/cilium/pkg/controller/controller.go:205 +0xa2a
created by github.com/cilium/cilium/pkg/controller.(*Manager).updateController
        /go/src/github.com/cilium/cilium/pkg/controller/manager.go:120 +0xb09

```

As part of this, `Reinitialize()` is called which will require the compilation mutex to be acquired.

### Routine 2

The following ongoing endpoint regeneration is holding the compilation lock and thus blocks Routine 1 from completing. It is itself blocked on the FQDN NameManager mutex.

```
goroutine 7227352 [semacquire, 48 minutes]:
sync.runtime_SemacquireMutex(0xc0005c3744, 0xc009bf4c00, 0x1)
        /usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0005c3740)
        /usr/local/go/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:81
github.com/cilium/cilium/pkg/fqdn.(*NameManager).Lock(0xc0005c3740)
        /go/src/github.com/cilium/cilium/pkg/fqdn/name_manager.go:93 +0x47
github.com/cilium/cilium/pkg/policy.(*SelectorCache).AddFQDNSelector(0xc0004691c0, 0x26faf00, 0xc00acd6e70, 0x0, 0x0, 0xc004106590, 0xb, 0x0, 0x0, 0x40ca00)
        /go/src/github.com/cilium/cilium/pkg/policy/selectorcache.go:580 +0x13f
github.com/cilium/cilium/pkg/policy.(*L4Filter).cacheFQDNSelector(...)
        /go/src/github.com/cilium/cilium/pkg/policy/l4.go:392
github.com/cilium/cilium/pkg/policy.(*L4Filter).cacheFQDNSelectors(0xc00acd6e70, 0xc008c7d100, 0x38, 0x38, 0xc0004691c0)
        /go/src/github.com/cilium/cilium/pkg/policy/l4.go:387 +0xad
github.com/cilium/cilium/pkg/policy.createL4Filter(0x2739660, 0xc001c49680, 0xc006beab60, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cilium/cilium/pkg/policy/l4.go:489 +0x7ce
github.com/cilium/cilium/pkg/policy.createL4EgressFilter(...)
        /go/src/github.com/cilium/cilium/pkg/policy/l4.go:599
github.com/cilium/cilium/pkg/policy.mergeEgressPortProto(0x2739660, 0xc001c49680, 0xc0052087d0, 0xc006beab60, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cilium/cilium/pkg/policy/rule.go:637 +0x187
github.com/cilium/cilium/pkg/policy.mergeEgress(0x2739660, 0xc001c49680, 0xc0052087d0, 0xc006beab60, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc00b91f2c0, ...)
        /go/src/github.com/cilium/cilium/pkg/policy/rule.go:572 +0xdbd
github.com/cilium/cilium/pkg/policy.(*rule).resolveEgressPolicy(0xc0079a0400, 0x2739660, 0xc001c49680, 0xc0052087d0, 0xc005208418, 0xc0090738f0, 0x0, 0x0, 0x0, 0xc0090738f0, ...)
        /go/src/github.com/cilium/cilium/pkg/policy/rule.go:675 +0x265
github.com/cilium/cilium/pkg/policy.ruleSlice.resolveL4EgressPolicy(0xc008d0a9c0, 0x5, 0x8, 0x2739660, 0xc001c49680, 0xc0052087d0, 0xc008d6c300, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/policy/rules.go:106 +0x70b
github.com/cilium/cilium/pkg/policy.(*Repository).resolvePolicyLocked(0xc000246460, 0xc0059fe820, 0xc0000066c3, 0xc0030b0960, 0xc006176201)
        /go/src/github.com/cilium/cilium/pkg/policy/repository.go:665 +0x3f9
github.com/cilium/cilium/pkg/policy.(*PolicyCache).updateSelectorPolicy(0xc000342b20, 0xc0059fe820, 0x3a5bf00, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/policy/distillery.go:135 +0x148
github.com/cilium/cilium/pkg/policy.(*PolicyCache).UpdatePolicy(...)
        /go/src/github.com/cilium/cilium/pkg/policy/distillery.go:170
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regeneratePolicy(0xc001427080, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:175 +0x255
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).runPreCompilationSteps(0xc001427080, 0xc005d3a500, 0xc008d0a800, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:736 +0x96a
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF(0xc001427080, 0xc005d3a500, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:508 +0x1e0
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc001427080, 0xc005d3a500, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:349 +0x841
github.com/cilium/cilium/pkg/endpoint.(*EndpointRegenerationEvent).Handle(0xc003530210, 0xc0068115c0)
        /go/src/github.com/cilium/cilium/pkg/endpoint/events.go:58 +0x459
github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Run.func1()
        /go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:260 +0x187
sync.(*Once).doSlow(0xc005f60e58, 0xc009bbb330)
        /usr/local/go/src/sync/once.go:66 +0xe3
sync.(*Once).Do(0xc005f60e58, 0xc009bbb330)
        /usr/local/go/src/sync/once.go:57 +0x45
created by github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Run
        /go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:248 +0xa9
```

### Routine 3

This third routine is holding the FQDN NameManager mutex while itself waiting on the ipcache mutex which is held by routine 1.

```
goroutine 7229843 [select, 48 minutes]:
golang.org/x/sync/semaphore.(*Weighted).Acquire(0xc000464230, 0x2759d60, 0xc000058018, 0x40000000, 0xc0008f9740, 0x0)
        /go/src/github.com/cilium/cilium/vendor/golang.org/x/sync/semaphore/semaphore.go:60 +0x28e
github.com/cilium/cilium/pkg/lock.(*SemaphoredMutex).Lock(...)
        /go/src/github.com/cilium/cilium/pkg/lock/semaphored_mutex.go:41
github.com/cilium/cilium/pkg/ipcache.(*IPCache).Upsert(0xc000464280, 0xc008858dd0, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1000596, 0x231acf1, ...)
        /go/src/github.com/cilium/cilium/pkg/ipcache/ipcache.go:184 +0x93
github.com/cilium/cilium/pkg/ipcache.allocateCIDRs(0xc004bb2a00, 0x98, 0x98, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/ipcache/cidr.go:97 +0x7aa
github.com/cilium/cilium/pkg/ipcache.AllocateCIDRsForIPs(0xc0046a2000, 0x98, 0x200, 0x1, 0x1, 0x0, 0x1f4a440, 0xc00a768900)
        /go/src/github.com/cilium/cilium/pkg/ipcache/cidr.go:52 +0x65
main.identitiesForFQDNSelectorIPs(0xc00a7687e0, 0xc0008f9740, 0x0, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/daemon/fqdn.go:87 +0x38e
main.(*Daemon).updateSelectors(0xc000515680, 0x2759da0, 0xc000e09a40, 0xc00a7687e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/daemon/fqdn.go:320 +0x40
github.com/cilium/cilium/pkg/fqdn.(*NameManager).UpdateGenerateDNS(0xc0005c3740, 0x2759da0, 0xc000e09a40, 0xbfae6eb0118dc6cd, 0x131b26c90d12, 0x3a5bf00, 0xc004cf9910, 0x0, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/fqdn/name_manager.go:225 +0x48f
main.(*Daemon).notifyOnDNSMsg(0xc000515680, 0xbfae6eb0118dc6cd, 0x131b26c90d12, 0x3a5bf00, 0xc001427080, 0xc00a2bdec0, 0x11, 0xc00ae52340, 0x10, 0xc003564f30, ...)
        /go/src/github.com/cilium/cilium/daemon/fqdn.go:584 +0x12cd
github.com/cilium/cilium/pkg/fqdn/dnsproxy.(*DNSProxy).ServeDNS(0xc0008c8e80, 0x27818e0, 0xc00302e1e0, 0xc0072a4f30)
        /go/src/github.com/cilium/cilium/pkg/fqdn/dnsproxy/proxy.go:475 +0x238c
github.com/miekg/dns.(*Server).serveDNS(0xc000563a40, 0xc001f8be00, 0x6b, 0x200, 0xc00302e1e0)
        /go/src/github.com/cilium/cilium/vendor/github.com/miekg/dns/server.go:597 +0x20b
github.com/miekg/dns.(*Server).serveUDPPacket(0xc000563a40, 0xc00047d060, 0xc001f8be00, 0x6b, 0x200, 0xc000df0380, 0xc0092cf2b0)
        /go/src/github.com/cilium/cilium/vendor/github.com/miekg/dns/server.go:552 +0xb2
github.com/miekg/dns.(*Server).serveUDP.func2(0xc000563a40, 0xc00047d060, 0xc001f8be00, 0x6b, 0x200, 0xc000df0380, 0xc0092cf2b0)
        /go/src/github.com/cilium/cilium/vendor/github.com/miekg/dns/server.go:478 +0x67
created by github.com/miekg/dns.(*Server).serveUDP
        /go/src/github.com/cilium/cilium/vendor/github.com/miekg/dns/server.go:477 +0x272
```

### PR DESCRIPTION
**Pull request by tgraf**
The following deadlock can occur when the ipcache GC relies on map
renames and datapath reloads to delete entries in combination with
endpoint regenrations triggered by the FQDN proxy which perform ipcache
upserts as part of regenerations:

Routine 1:
The following go routine holds the ipcache mutex while garbage collecting:

```
goroutine 779 [semacquire, 48 minutes]:
sync.runtime_SemacquireMutex(0xc0008f4f68, 0xc007663600, 0x0)
        /usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*RWMutex).Lock(0xc0008f4f60)
        /usr/local/go/src/sync/rwmutex.go:103 +0x88
github.com/cilium/cilium/pkg/datapath/loader.(*Loader).Reinitialize(0xc0003d70a0, 0x2759d20, 0xc000468bc0, 0x2771e60, 0xc000515680, 0x2329, 0x7f87768eac80, 0xc00022ff10, 0x26faf60, 0xc0004a18b0, ...)
        /go/src/github.com/cilium/cilium/pkg/datapath/loader/base.go:124 +0xcd
main.(*Daemon).TriggerReloadWithoutCompile(0xc000515680, 0x2332316, 0x10, 0x12, 0xc008f75060, 0x16)
        /go/src/github.com/cilium/cilium/daemon/daemon.go:588 +0x202
github.com/cilium/cilium/pkg/datapath/ipcache.(*BPFListener).garbageCollect(0xc0006f8960, 0x2759d20, 0xc003748000, 0x0, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/datapath/ipcache/listener.go:306 +0xadc
github.com/cilium/cilium/pkg/datapath/ipcache.(*BPFListener).OnIPIdentityCacheGC.func1(0x2759d20, 0xc003748000, 0x3a5bf00, 0x2)
        /go/src/github.com/cilium/cilium/pkg/datapath/ipcache/listener.go:340 +0x3e
github.com/cilium/cilium/pkg/controller.(*Controller).runController(0xc001e1e000)
        /go/src/github.com/cilium/cilium/pkg/controller/controller.go:205 +0xa2a
created by github.com/cilium/cilium/pkg/controller.(*Manager).updateController
        /go/src/github.com/cilium/cilium/pkg/controller/manager.go:120 +0xb09
```

As part of this, Reinitialize() is called which will require the compilation mutex to be acquired.

Routine 2
The following ongoing endpoint regeneration is holding the compilation lock and thus blocks Routine 1 from completing. It is itself blocked on the FQDN NameManager mutex.

```
goroutine 7227352 [semacquire, 48 minutes]:
sync.runtime_SemacquireMutex(0xc0005c3744, 0xc009bf4c00, 0x1)
        /usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0005c3740)
        /usr/local/go/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:81
github.com/cilium/cilium/pkg/fqdn.(*NameManager).Lock(0xc0005c3740)
        /go/src/github.com/cilium/cilium/pkg/fqdn/name_manager.go:93 +0x47
github.com/cilium/cilium/pkg/policy.(*SelectorCache).AddFQDNSelector(0xc0004691c0, 0x26faf00, 0xc00acd6e70, 0x0, 0x0, 0xc004106590, 0xb, 0x0, 0x0, 0x40ca00)
        /go/src/github.com/cilium/cilium/pkg/policy/selectorcache.go:580 +0x13f
github.com/cilium/cilium/pkg/policy.(*L4Filter).cacheFQDNSelector(...)
        /go/src/github.com/cilium/cilium/pkg/policy/l4.go:392
github.com/cilium/cilium/pkg/policy.(*L4Filter).cacheFQDNSelectors(0xc00acd6e70, 0xc008c7d100, 0x38, 0x38, 0xc0004691c0)
        /go/src/github.com/cilium/cilium/pkg/policy/l4.go:387 +0xad
github.com/cilium/cilium/pkg/policy.createL4Filter(0x2739660, 0xc001c49680, 0xc006beab60, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cilium/cilium/pkg/policy/l4.go:489 +0x7ce
github.com/cilium/cilium/pkg/policy.createL4EgressFilter(...)
        /go/src/github.com/cilium/cilium/pkg/policy/l4.go:599
github.com/cilium/cilium/pkg/policy.mergeEgressPortProto(0x2739660, 0xc001c49680, 0xc0052087d0, 0xc006beab60, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cilium/cilium/pkg/policy/rule.go:637 +0x187
github.com/cilium/cilium/pkg/policy.mergeEgress(0x2739660, 0xc001c49680, 0xc0052087d0, 0xc006beab60, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc00b91f2c0, ...)
        /go/src/github.com/cilium/cilium/pkg/policy/rule.go:572 +0xdbd
github.com/cilium/cilium/pkg/policy.(*rule).resolveEgressPolicy(0xc0079a0400, 0x2739660, 0xc001c49680, 0xc0052087d0, 0xc005208418, 0xc0090738f0, 0x0, 0x0, 0x0, 0xc0090738f0, ...)
        /go/src/github.com/cilium/cilium/pkg/policy/rule.go:675 +0x265
github.com/cilium/cilium/pkg/policy.ruleSlice.resolveL4EgressPolicy(0xc008d0a9c0, 0x5, 0x8, 0x2739660, 0xc001c49680, 0xc0052087d0, 0xc008d6c300, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/policy/rules.go:106 +0x70b
github.com/cilium/cilium/pkg/policy.(*Repository).resolvePolicyLocked(0xc000246460, 0xc0059fe820, 0xc0000066c3, 0xc0030b0960, 0xc006176201)
        /go/src/github.com/cilium/cilium/pkg/policy/repository.go:665 +0x3f9
github.com/cilium/cilium/pkg/policy.(*PolicyCache).updateSelectorPolicy(0xc000342b20, 0xc0059fe820, 0x3a5bf00, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/policy/distillery.go:135 +0x148
github.com/cilium/cilium/pkg/policy.(*PolicyCache).UpdatePolicy(...)
        /go/src/github.com/cilium/cilium/pkg/policy/distillery.go:170
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regeneratePolicy(0xc001427080, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:175 +0x255
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).runPreCompilationSteps(0xc001427080, 0xc005d3a500, 0xc008d0a800, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:736 +0x96a
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF(0xc001427080, 0xc005d3a500, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:508 +0x1e0
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc001427080, 0xc005d3a500, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:349 +0x841
github.com/cilium/cilium/pkg/endpoint.(*EndpointRegenerationEvent).Handle(0xc003530210, 0xc0068115c0)
        /go/src/github.com/cilium/cilium/pkg/endpoint/events.go:58 +0x459
github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Run.func1()
        /go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:260 +0x187
sync.(*Once).doSlow(0xc005f60e58, 0xc009bbb330)
        /usr/local/go/src/sync/once.go:66 +0xe3
sync.(*Once).Do(0xc005f60e58, 0xc009bbb330)
        /usr/local/go/src/sync/once.go:57 +0x45
created by github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Run
        /go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:248 +0xa9
```

Routine 3

This third routine is holding the FQDN NameManager mutex while itself waiting on the ipcache mutex which is held by routine 1.

```
goroutine 7229843 [select, 48 minutes]:
golang.org/x/sync/semaphore.(*Weighted).Acquire(0xc000464230, 0x2759d60, 0xc000058018, 0x40000000, 0xc0008f9740, 0x0)
        /go/src/github.com/cilium/cilium/vendor/golang.org/x/sync/semaphore/semaphore.go:60 +0x28e
github.com/cilium/cilium/pkg/lock.(*SemaphoredMutex).Lock(...)
        /go/src/github.com/cilium/cilium/pkg/lock/semaphored_mutex.go:41
github.com/cilium/cilium/pkg/ipcache.(*IPCache).Upsert(0xc000464280, 0xc008858dd0, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1000596, 0x231acf1, ...)
        /go/src/github.com/cilium/cilium/pkg/ipcache/ipcache.go:184 +0x93
github.com/cilium/cilium/pkg/ipcache.allocateCIDRs(0xc004bb2a00, 0x98, 0x98, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/ipcache/cidr.go:97 +0x7aa
github.com/cilium/cilium/pkg/ipcache.AllocateCIDRsForIPs(0xc0046a2000, 0x98, 0x200, 0x1, 0x1, 0x0, 0x1f4a440, 0xc00a768900)
        /go/src/github.com/cilium/cilium/pkg/ipcache/cidr.go:52 +0x65
main.identitiesForFQDNSelectorIPs(0xc00a7687e0, 0xc0008f9740, 0x0, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/daemon/fqdn.go:87 +0x38e
main.(*Daemon).updateSelectors(0xc000515680, 0x2759da0, 0xc000e09a40, 0xc00a7687e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/daemon/fqdn.go:320 +0x40
github.com/cilium/cilium/pkg/fqdn.(*NameManager).UpdateGenerateDNS(0xc0005c3740, 0x2759da0, 0xc000e09a40, 0xbfae6eb0118dc6cd, 0x131b26c90d12, 0x3a5bf00, 0xc004cf9910, 0x0, 0x0, 0x0)
        /go/src/github.com/cilium/cilium/pkg/fqdn/name_manager.go:225 +0x48f
main.(*Daemon).notifyOnDNSMsg(0xc000515680, 0xbfae6eb0118dc6cd, 0x131b26c90d12, 0x3a5bf00, 0xc001427080, 0xc00a2bdec0, 0x11, 0xc00ae52340, 0x10, 0xc003564f30, ...)
        /go/src/github.com/cilium/cilium/daemon/fqdn.go:584 +0x12cd
github.com/cilium/cilium/pkg/fqdn/dnsproxy.(*DNSProxy).ServeDNS(0xc0008c8e80, 0x27818e0, 0xc00302e1e0, 0xc0072a4f30)
        /go/src/github.com/cilium/cilium/pkg/fqdn/dnsproxy/proxy.go:475 +0x238c
github.com/miekg/dns.(*Server).serveDNS(0xc000563a40, 0xc001f8be00, 0x6b, 0x200, 0xc00302e1e0)
        /go/src/github.com/cilium/cilium/vendor/github.com/miekg/dns/server.go:597 +0x20b
github.com/miekg/dns.(*Server).serveUDPPacket(0xc000563a40, 0xc00047d060, 0xc001f8be00, 0x6b, 0x200, 0xc000df0380, 0xc0092cf2b0)
        /go/src/github.com/cilium/cilium/vendor/github.com/miekg/dns/server.go:552 +0xb2
github.com/miekg/dns.(*Server).serveUDP.func2(0xc000563a40, 0xc00047d060, 0xc001f8be00, 0x6b, 0x200, 0xc000df0380, 0xc0092cf2b0)
        /go/src/github.com/cilium/cilium/vendor/github.com/miekg/dns/server.go:478 +0x67
created by github.com/miekg/dns.(*Server).serveUDP
        /go/src/github.com/cilium/cilium/vendor/github.com/miekg/dns/server.go:477 +0x272
```

Fixes: #11946
Fixes: #11690

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tklauser** [comment]
Should be backport this for 1.6 as well?

**Comment by tgraf** [comment]
> Should be backport this for 1.6 as well?

We have not observed this with 1.6 so far. We can backport it as the ipcache GC is subject to the same logic.

**Review by tklauser — APPROVED** [review]
LGTM as far as my reading of the code and understanding of the interactions between ipcache and the datapath goes.

**Comment by errordeveloper** [comment]
> Routine 1: The following go routine holds the ipcache mutex while garbage collecting

This looks like https://github.com/cilium/cilium/issues/11690#issuecomment-637413664. If that's the case, this PR should fix #11680.

**Review by jrajahalme — APPROVED** [review]

File: pkg/datapath/ipcache/listener.go [hunk 1]
```diff
@@ -300,24 +306,35 @@ func (l *BPFListener) garbageCollect(ctx context.Context) (*sync.WaitGroup, erro
...
+		if err != nil {
+			// We can't really undo the map rename again as ipcache
+			// operations had already been permitted so the backup
+			// map is potentially outdated. Fail hard to restart
+			// the agent so we reconstruct the ipcache from
+			// scratch.
+			log.WithError(err).Fatal("Endpoint datapath reload triggered by ipcache GC failed. Inconsistent state.")
 		}
+
+		_ = os.RemoveAll(bpf.MapPath(backupMapName))
```
Comment (jrajahalme) [inline pkg/datapath/ipcache/listener.go:337]: Are we leaking the backup map if we take the Fatal above? It seems to me that `shuffleMaps()` fails if the backup already exists? If so, maybe `shuffleMaps()` should remove the old backup as the first step?

**Comment by tgraf** [comment]
> This looks like [#11690 (comment)](https://github.com/cilium/cilium/issues/11690#issuecomment-637413664). If that's the case, this PR should fix #11690.

Good find!

File: pkg/datapath/ipcache/listener.go (hunk 1 above)
Comment (jrajahalme) [reply pkg/datapath/ipcache/listener.go:337]: `os.Rename()` replaces existing files, so this is not a concern.
```
Rename renames (moves) oldpath to newpath. If newpath already exists and is not a directory, Rename replaces it. 
```

**Comment by pchaigno** [comment]
@errordeveloper Does that mean it fixes #11820?

**Comment by errordeveloper** [comment]
> @errordeveloper Does that mean it fixes #11820?

It may do :)

File: pkg/datapath/ipcache/listener.go (hunk 1 above)
Comment (joestringer) [inline pkg/datapath/ipcache/listener.go:337]: Should we do this before the compile (or at least in the error case) to ensure that in the unlikely event that we `Fatal()` out above, the old map is removed from the filesystem?

Comment (joestringer) [reply pkg/datapath/ipcache/listener.go:337]: The concern of causing a subsequent failure due to the backup map being on the filesystem shouldn't be a problem.

However if we don't clean up the old map then it will continue to consume kernel resources. I think we still need to handle this in the `Fatal()` case. There's no benefit in leaving it on the filesesystem, since we can't introspect the map anyway given the kernel versions triggering this path.

Comment (joestringer) [reply pkg/datapath/ipcache/listener.go:337]: I guess that assuming the new run of the daemon executes through this path successfully, it will remove the old map 5 minutes after startup.

**Review by joestringer — APPROVED** [review]

File: pkg/datapath/ipcache/listener.go (hunk 1 above)
Comment (joestringer) [reply pkg/datapath/ipcache/listener.go:337]: Given the `Rename()` behaviour described below + the periodic deletion / recreate, I don't think this is blocking.

https://github.com/cilium/cilium/pull/11950#discussion_r436813198

Comment (tgraf) [reply pkg/datapath/ipcache/listener.go:337]: I've discussed this with Jarno as well. I've left it there on purpose that in the event that the Fatal occurs, the map is left behind so we can potentially troubleshoot it.

The next GC run will remove it as the agent restarts so it will only persist if the system remains in an inconsistent state.

Comment (jrajahalme) [reply pkg/datapath/ipcache/listener.go:337]: I asked the same question. Turns our that `os.Rename()` will replace the old file if it exists, and there is value of having the old file left behind in case you get to debug the error case.
