### PR TITLE
Gracefully terminate service endpoints

### LINKED ISSUE #14844: LB service (pod) backend deletion breaks existing connections
Consolidate discussion/proposals for 

[ ] https://github.com/cilium/cilium/issues/12859 (forceful termination of existing connections)
[ ] https://github.com/cilium/cilium/issues/10217 (graceful handling of existing connections)

### Desired goal 
Upon removal of a service backend, drain all the existing connections to the backend, and ensure that the backend is not selected for new connections. 

### Current behavior
What happens when a service backend is deleted, and we immediately remove it from the `lb` maps?

- Socket-based load balancing 

TCP (Connected UDP) : 

(Broken) 
Backend is selected at the time of the socket `Connect` call via a lookup in the `lb` map. As a result, existing connections are likely to trigger re-transmissions, and eventually give up.  The onus is on applications to recover from the failure (e.g., keep-alives).

(Ok) 
The deleted backend won't be selected for new connections.
If the backend pod hangs around for the duration of `terminationGracePeriod`, then connections could terminate gracefully.

UDP: 

(Broken) 
Backend selection happens on per packet in the sendmsg call (similar to per packet load balancing). Daniel mentioned that socket cookie could help pick the same backend, but if the backend is deleted, then a new backend will be selected.
This logic also breaks when the number of service backends change (either increase/decrease). 

(Ok) 
The deleted backend won't be selected for new connections.

-  Per packet load balancing  

TCP/ Connected UDP/ UDP:

(Broken) 
Backend is selected on a per packet basis. For the first packet in a flow, a new CT entry is created, which also stores the selected backend id. The backend selection involves `lb` services map lookup. For subsequent packets, a lookup is issued to the `ct` map to retrieve the selected backend id. This is followed by a lookup to the `lb` backend map to get the backend metadata. When a backend is deleted, we end up selecting a wrong backend, and the existing connections are likely to receive a `RST`. 

(Ok) 
The deleted backend won't be selected for new connections.
RSTs could enable fast recovery for active connections. 

### Potential solutions :

- Graceful termination

  * Modified backend ref counting (selected)
Backend selection is done using `lb service` map lookups, and backend info retrieval via `lb backend` maps. Could we remove a backend entry from the former, but not the latter until a configured graceful termination timeout? Backend ref counting logic would need to be updated. 
	
  * Weights based backend selection
Keep entry in both the maps. Use weights in the backend selection logic. When a backend is being deleted, its weight will be set to `0` by cilium agent, and such backends won't be selected by the datapath. How do we handle the case where this backend is selected for new connections? Re-do the process?

- Abrupt termination 
A backend can disappear without honoring the graceful termination timeout configured by Kubernetes. In such scenarios, there is no way to gracefully terminate existing connections to the backend. We can, however, facilitate faster recovery from failures by sending `RST`s. For active connections, create a `SOCKMAP`, and use `bpf_sk_assign` to redirect packets to a terminator socket?
How do we handle inactive connections???
What about socket-based load balancing???

### Optimizations:

- Keep a backend entry in the lb backend map only when the backend has existing connections. Conntrack could be one place to get this information from.

 
### Open questions :
- ~Does Kubernetes expose `terminationGracePeriod` for an Endpoint?~
No, the configuration is only available in the `pod Spec`. Use the terminating state introduced in Kubernetes v1.20 by the [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1672-tracking-terminating-endpoints).
- ~Clean up of CT entries~
It's not needed for now as LRU will clean up such entries. 
- How does the Linux stack handle an incoming packet destined to a socket that doesn't exist?
- Test environment to reproduce the issue

Discussed during the sig-datapath meeting on 02/03 - https://docs.google.com/document/d/1IZZ-FTM_U3zN06-M_mDOgep_DcDM0Oe3YOFVM1BTIt8/edit#heading=h.b4c02eltf70i

### PR DESCRIPTION
**Pull request by aditighag**
Objective:
Upon removal of a service backend, drain all the existing connections to the backend, and ensure that the backend is
not selected for new connections.

Implementation:
Backend selection in the datapath is done using `lb service` map lookups, and backend information is retrieved via `lb backend` maps. Earlier, we removed the backend entry from the maps as soon as it was deleted. This can break existing active connections to the backend for per-packet based load-balancing, or unconnected UDP, wherein backend information retrieval lookups fail, and connections are redirected to other backends.

Kubernetes allows users to specify `terminationGracefulPeriod` in the pod spec in order to allow server pods to gracefully terminate active connections. In k8s v1.20, a new endpoint condition called as `Terminating` [1] was added. When we receive an update for a terminating backend, we skip adding it to the service map so that the backends isn't selected for new connections. But we keep the entry in the backend and affinity maps so that active connections continue are not disrupted. Once the endpoint deletion event is received, the backend state is fully removed.

See commit description for more details.

[1] https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/#terminating

Fixes : #14844 

**Release note**
```release-note
Support graceful termination for service load-balancing such that active connections don't break when endpoints are deleted. 
```

### CODE REVIEW

File: pkg/service/service.go [hunk 1]
```diff
@@ -787,7 +787,10 @@ func (s *Service) upsertServiceIntoLBMaps(svc *svcInfo, onlyLocalBackends bool,
 	// Upsert service entries into BPF maps
 	backends := make(map[string]lb.BackendID, len(svc.backends))
 	for _, b := range svc.backends {
-		backends[b.String()] = b.ID
+		// The terminating backend won't be selected to serve new requests.
+		if !b.Terminating {
+			backends[b.String()] = b.ID
+		}
```
Comment (borkmann) [inline pkg/service/service.go:801]: Does the above also work for Maglev LB map?

Comment (aditighag) [reply pkg/service/service.go:801]: Discussed offline - deferred to follow-ups.

File: install/kubernetes/cilium/templates/cilium-configmap.yaml [hunk 2]
```diff
@@ -771,6 +771,10 @@ data:
   vlan-bpf-bypass: {{ .Values.bpf.vlanBypass | join " " | quote }}
 {{- end }}
 
+{{- if hasKey .Values "enable-k8s-terminating-endpoint" }}
+  enable-k8s-terminating-endpoint: {{ .Values.enableTerminatingEndpoint | quote }}
```
Comment (borkmann) [inline install/kubernetes/cilium/templates/cilium-configmap.yaml]: I think this one needs a  bit of rework, e.g. above should check `hasKey .Values "enableTerminatingEndpoint"` at min. We should probably also add the entry description to values.yaml. Cc @joestringer

File: pkg/service/service.go [hunk 3]
```diff
@@ -787,7 +787,11 @@ func (s *Service) upsertServiceIntoLBMaps(svc *svcInfo, onlyLocalBackends bool,
 	// Upsert service entries into BPF maps
 	backends := make(map[string]lb.BackendID, len(svc.backends))
 	for _, b := range svc.backends {
-		backends[b.String()] = b.ID
+		// Skip adding the terminating backend to the service map as it
+		// won't be selected to serve new requests.
```
Comment (borkmann) [inline pkg/service/service.go]: Could you also extend the comment a bit in that the backend will still be present in the backends map etc, and the refcounting will take care of the final cleanup once graceful period is over? Bit more verbosity of the mechanics would help for future context.

File: Documentation/gettingstarted/kubeproxy-free.rst [hunk 4]
```diff
@@ -1158,6 +1158,14 @@ The current Cilium kube-proxy replacement mode can also be introspected through
     $ kubectl exec -it -n kube-system cilium-xxxxx -- cilium status | grep KubeProxyReplacement
     KubeProxyReplacement:   Strict	[eth0 (DR)]
 
+Graceful Termination
+*********************
```
Comment (borkmann) [inline Documentation/gettingstarted/kubeproxy-free.rst]: tiny nit: I think one '*' too much, not sure if it still keeps rendering docs then.

File: Documentation/gettingstarted/kubeproxy-free.rst [hunk 5]
```diff
@@ -1158,6 +1158,14 @@ The current Cilium kube-proxy replacement mode can also be introspected through
...
+
+Cilium's eBPF kube-proxy replacement supports graceful termination of service
+endpoints deletion. The feature requires at least Kubernetes version 1.20, and
+the feature gate ``EndpointSliceTerminatingCondition`` needs to be enabled. The
+feature can be disabled with the configuration option ``enable-k8s-terminating-endpoint``.
```
Comment (borkmann) [inline Documentation/gettingstarted/kubeproxy-free.rst]: Could you add more verbosity in here? I think that would help users with the setup, e.g. what's the default time for the grace period? Also description on what happens in datapath during that period wrt terminating backend. Maybe also link to K8s docs, etc would help.

File: test/k8sT/Services.go [hunk 6]
```diff
@@ -1548,6 +1549,133 @@ Secondary Interface %s :: IPv4: (%s, %s), IPv6: (%s, %s)`, helpers.DualStackSupp
...
+			for _, pod := range pods {
+				// Repeat the command as Kubernetes events propagation may have delays
+				Eventually(func() bool {
+					res = kubectl.ExecPodCmd(
+						helpers.DefaultNamespace, pod,
+						helpers.CurlFail("graceful-term-svc.default.svc.cluster.local.:8081"))
+					return !res.WasSuccessful()
+				}, 2*time.Minute, time.Second).Should(BeTrue(), "%q can connect when it should not work \n", pod)
+			}
+			wg.Wait()
```
Comment (borkmann) [inline test/k8sT/Services.go]: Could we also assert whether the backend gets eventually removed as expected after graceful period? Meaning, to ensure that agent internal refcounting etc is all still working as expected?

File: install/kubernetes/cilium/templates/cilium-configmap.yaml [hunk 7]
```diff
@@ -771,6 +771,10 @@ data:
   vlan-bpf-bypass: {{ .Values.bpf.vlanBypass | join " " | quote }}
 {{- end }}
 
+{{- if hasKey .Values "enable-k8s-terminating-endpoint" }}
```
Comment (errordeveloper) [inline install/kubernetes/cilium/templates/cilium-configmap.yaml]:
```suggestion
{{- if hasKey .Values "enableTerminatingEndpoint" }}
```

File: test/k8sT/Services.go (hunk 6 above)
Comment (aditighag) [reply test/k8sT/Services.go]: That's validated in unit tests as that's the rightful place for map clean-up assertions.

File: install/kubernetes/cilium/templates/cilium-configmap.yaml (hunk 2 above)
Comment (aditighag) [reply install/kubernetes/cilium/templates/cilium-configmap.yaml]: Yes, you are right. I forgot to add that file with my changes to the git commit.

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.Checks graceful termination of service endpoints " --k8s_version=1.21 --kernel_version="419"

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.Checks graceful termination of service endpoints" --k8s_version=1.21 --kernel_version="49"

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.Checks graceful termination of service endpoints" --k8s_version=1.21 --kernel_version="49"

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.Checks graceful termination of service endpoints" --k8s_version=1.20 --kernel_version="49"

**Comment by aditighag** [comment]
I've fixed the helm documentation lint issue in the generated files. Will push an update once the Jenkins infrastructure related issue is resolved - 

```
Error when executing always post condition:
org.jenkinsci.plugins.workflow.steps.MissingContextVariableException: Required context class hudson.FilePath is missing
Perhaps you forgot to surround the code with a step that provides this, such as: node
	at org.jenkinsci.plugins.workflow.steps.StepDescriptor.checkContextAvailability(StepDescriptor.java:266)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:260)
```

**Review by borkmann — APPROVED** [review]

File: Documentation/gettingstarted/kubeproxy-free.rst [hunk 8]
```diff
@@ -1158,6 +1158,20 @@ The current Cilium kube-proxy replacement mode can also be introspected through
     $ kubectl exec -it -n kube-system cilium-xxxxx -- cilium status | grep KubeProxyReplacement
     KubeProxyReplacement:   Strict	[eth0 (DR)]
 
+Graceful Termination
+********************
+
+Cilium's eBPF kube-proxy replacement supports graceful termination of service
+endpoints deletion. The feature requires at least Kubernetes version 1.20, and
+the feature gate ``EndpointSliceTerminatingCondition`` needs to be enabled. The
+feature can be disabled with the configuration option ``enable-k8s-terminating-endpoint``.
```
Comment (borkmann) [inline Documentation/gettingstarted/kubeproxy-free.rst]: nit, I would make a slight amendment here, for example:

[...] needs to be enabled. By default, the Cilium agent then detects such terminating Pod state. If desired, the feature can also be disabled with the configuration option ``--enable-k8s-terminating-endpoint=false``.

**Comment by borkmann** [comment]
Please also add an explicit follow-up issue that Maglev needs to be investigated wrt graceful termination. Ideally, we get that still into the .0 release, or .1 worst case.

File: pkg/k8s/endpoints.go [hunk 9]
```diff
@@ -164,7 +165,16 @@ func ParseEndpointSliceV1Beta1(ep *slim_discovery_v1beta1.EndpointSlice) (Endpoi
...
 		// More info: vendor/k8s.io/api/discovery/v1beta1/types.go
 		if sub.Conditions.Ready != nil && !*sub.Conditions.Ready {
-			continue
+			if option.Config.EnableK8sTerminatingEndpoint {
+				// Terminating indicates that the endpoint is getting terminated.
+				// Ready is never true when an endpoint is terminating.
+				// Propagate the terminating endpoint state so that we can gracefully
+				// remove those endpoints.
+				// More details : vendor/k8s.io/api/discovery/v1beta1/types.go
+				if sub.Conditions.Terminating != nil && !*sub.Conditions.Terminating {
```
Comment (brb) [inline pkg/k8s/endpoints.go]: Aren't we adding non-ready endpoint if it is in non-terminating state?

File: test/k8sT/manifests/graceful-termination.yaml [hunk 10]
```diff
@@ -0,0 +1,47 @@
...
+---
+apiVersion: v1
+kind: Pod
+metadata:
+  name: graceful-term-server
+  labels:
+    app: graceful-term-server
+spec:
+  containers:
+    - name: server
```
Comment (brb) [inline test/k8sT/manifests/graceful-termination.yaml:19]: Do we actually need new pods to test the graceful termination? Maybe the existing testDS pods are enough? If not, then could you move the images into the cilium repo/org?

File: test/k8sT/Services.go [hunk 11]
```diff
@@ -1548,6 +1549,132 @@ Secondary Interface %s :: IPv4: (%s, %s), IPv6: (%s, %s)`, helpers.DualStackSupp
...
+		)
+		var (
+			gracefulTermYAML string
+			clientPod        string
+			serverPod        string
+			testPodYAML      string
+		)
+
+		BeforeAll(func() {
+			if helpers.SkipK8sVersions("<1.20") {
```
Comment (brb) [inline test/k8sT/Services.go]: Could we move this to the SkipContextIf condition?

File: test/k8sT/manifests/demo-graceful-term.yaml [hunk 12]
```diff
@@ -0,0 +1,21 @@
+apiVersion: apps/v1
+kind: DaemonSet
+metadata:
+  name: testclient
```
Comment (brb) [inline test/k8sT/manifests/demo-graceful-term.yaml]: Don't we have multiple similar pods already available?

File: test/k8sT/Services.go [hunk 13]
```diff
@@ -1548,6 +1549,132 @@ Secondary Interface %s :: IPv4: (%s, %s), IPv6: (%s, %s)`, helpers.DualStackSupp
...
+				Skip(fmt.Sprintln("Graceful termination support requires at least K8s version 1.20"))
+			}
+			DeployCiliumOptionsAndDNS(kubectl, ciliumFilename, map[string]string{
+				"kubeProxyReplacement": "disabled",
+			})
+
+			testPodYAML = helpers.ManifestGet(kubectl.BasePath(), "demo-graceful-term.yaml")
```
Comment (brb) [inline test/k8sT/Services.go]: Shouldn't this be in a separate It() block?

**Review by brb — CHANGES_REQUESTED** [review]

File: pkg/k8s/endpoints.go (hunk 9 above)
Comment (aditighag) [reply pkg/k8s/endpoints.go]: No, we are not. There is a `continue` on the next line.

File: test/k8sT/manifests/demo-graceful-term.yaml (hunk 12 above)
Comment (aditighag) [reply test/k8sT/manifests/demo-graceful-term.yaml]: Nope, they are replicated in every e2e test that need the demo pods. Anyway I'm going to fold this into the graceful-test yaml file.

File: test/k8sT/manifests/graceful-termination.yaml (hunk 10 above)
Comment (aditighag) [reply test/k8sT/manifests/graceful-termination.yaml:19]: Yes, we do - 1) Test phases are organized based on logged events by server/client 2) The server pod performs actions based on `SIGTERM` signal.
Yes, I've moved the image. Was waiting until Jenkins test infra issue was resolved.

File: test/k8sT/Services.go (hunk 13 above)
Comment (aditighag) [reply test/k8sT/Services.go]: I presume you meant that the actual test logic `Checking if terminating service endpoint doesn't serve new connections` should be moved to a separate It() block? Deployment of test pods will still happen in the `BeforeAll` block, no? Yes, we can do that.

**Comment by aditighag** [comment]
Travis CI failure is legit - I've updated the `endpoint_test.go` with the terminating state related changes.

File: pkg/k8s/endpoints.go (hunk 9 above)
Comment (brb) [reply pkg/k8s/endpoints.go]: - We won't invoke `continue` if `--enable-k8s-terminating-endpoints=false` for non-ready endpoints. Is it OK?
- We won't invoke `continue` for non-ready terminating endpoints. Same question.

Comment (aditighag) [reply pkg/k8s/endpoints.go]: >We won't invoke continue if --enable-k8s-terminating-endpoints=false for non-ready endpoints. Is it OK?

Ah, yes! Need to fix the case where user explicitly disables the feature flag. 

>We won't invoke continue for non-ready terminating endpoints. Same question.

Yes, as the comment indicates, we want to propagate the terminating state.

Edit : Refactored the code a bit, and also added unit tests.

File: test/k8sT/Services.go (hunk 11 above)
Comment (aditighag) [reply test/k8sT/Services.go]: I decided to keep it looking at other references in the code - it's useful to have the context why the test is being skipped.

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.Checks graceful termination of service endpoints" --k8s_version=1.20 --kernel_version="49"

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.Checks graceful termination of service endpoints" --k8s_version=1.20 --kernel_version="49"

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.Checks graceful termination of service endpoints" --k8s_version=1.20 --kernel_version="419"

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.Checks graceful termination of service endpoints" --k8s_version=1.20 --kernel_version="419"

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.Checks graceful termination of service endpoints" --k8s_version=1.20 --kernel_version="419"

**Comment by borkmann** [comment]
(Looks like Travis CI currently trips into a related test case issue.)

**Comment by aditighag** [comment]
> (Looks like Travis CI currently trips into a related test case issue.)

Yup, debugging it. :) There is some logic related to book-keeping of previous backend count that's used to delete obsolete backends from the services map that didn't come up until now.

**Comment by aditighag** [comment]
@brb I've pushed a temporary commit to fix the issue in the clean-up code flagged by Travis - https://github.com/cilium/cilium/pull/17716/commits/c2987122776a3648b0d2add37745bbc3436a5307. The unit tests pass in my local environment. Re-run of the CI test also passed in a local environment. 
But before I formalize these changes, I would like to check if my understanding about the code logic is correct.

File: pkg/service/service_test.go [hunk 14]
```diff
@@ -710,3 +714,93 @@ func (m *ManagerTestSuite) TestLocalRedirectServiceOverride(c *C) {
...
+	c.Assert(created, Equals, false)
+	c.Assert(id1, Equals, lb.ID(1))
+	c.Assert(len(m.lbmap.ServiceByID[uint16(id1)].Backends), Equals, 0)
+	c.Assert(len(m.lbmap.BackendByID), Equals, 0)
+	c.Assert(m.svc.svcByID[id1].svcName, Equals, "svc1")
+	c.Assert(m.svc.svcByID[id1].svcNamespace, Equals, "ns1")
+	c.Assert(len(m.lbmap.AffinityMatch[uint16(id1)]), Equals, 0)
+}
+
+// Tests terminating backend entries are removed after service restore.
```
Comment (brb) [inline pkg/service/service_test.go:768]: We need to test whether terminating backend IDs have been restored after the restart. Otherwise, we are risking to allocate already used IDs.

File: pkg/service/service_test.go [hunk 15]
```diff
@@ -710,3 +714,93 @@ func (m *ManagerTestSuite) TestLocalRedirectServiceOverride(c *C) {
...
+	// Simulate agent restart.
+	lbmap := m.svc.lbmap.(*mockmaps.LBMockMap)
+	m.svc = NewService(nil)
+	m.svc.lbmap = lbmap
+
+	// Restore services from lbmap
+	err = m.svc.RestoreServices()
+	c.Assert(err, IsNil)
+
+	// (Non-terminating) Backends have been restored
```
Comment (brb) [inline pkg/service/service_test.go]: Why don't we restore the terminating backends?

File: test/helpers/kubectl.go [hunk 16]
```diff
@@ -1195,6 +1195,21 @@ func (kub *Kubectl) Logs(namespace string, pod string) *CmdRes {
 		fmt.Sprintf("%s -n %s logs %s", KubectlCmd, namespace, pod))
 }
 
+// LogsWithLabel returns a CmdRes with command output from the
+// execution of `kubectl logs --previous -l <label string> -n <namespace>`.
+func (kub *Kubectl) LogsWithLabel(namespace string, labelStr string) *CmdRes {
```
Comment (brb) [inline test/helpers/kubectl.go]: Nit: maybe let's add "previous" to the method name to avoid any possible confusion.

File: test/k8sT/Services.go [hunk 17]
```diff
@@ -1548,6 +1549,155 @@ Secondary Interface %s :: IPv4: (%s, %s), IPv6: (%s, %s)`, helpers.DualStackSupp
...
+			Expect(res.WaitUntilMatch("terminating")).To(BeNil(),
+				"%s is not in the output after timeout", res.GetStdOut())
+			defer func() {
+				cancel()
+				res.WaitUntilFinish()
+			}()
+		}
+
+		BeforeAll(func() {
+			if helpers.SkipK8sVersions("<1.20.0") {
```
Comment (brb) [inline test/k8sT/Services.go]: (GH doesn't allow me to comment in my previous comment) I'd still move it to the ctx skip condition. You can add the comment there saying why we skip the test. Otherwise, it makes it more difficult already overbloated and poorly structured suite file (I'm talking about the whole `K8sService` suite).

File: test/k8sT/manifests/graceful-termination.yaml [hunk 18]
```diff
@@ -0,0 +1,69 @@
...
+spec:
+  restartPolicy: OnFailure
+  terminationGracePeriodSeconds: 0
+  containers:
+    - name: client
+      image: docker.io/cilium/graceful-termination-test-apps:latest
+      imagePullPolicy: IfNotPresent
+      command: [ "/client", "graceful-term-svc.default.svc.cluster.local.:8081" ]
+---
+apiVersion: apps/v1
```
Comment (brb) [inline test/k8sT/manifests/graceful-termination.yaml:53]: This is a duplicate of the `test/k8sT/manifests/demo_ds.yaml`.

File: test/k8sT/Services.go [hunk 19]
```diff
@@ -1548,6 +1549,155 @@ Secondary Interface %s :: IPv4: (%s, %s), IPv6: (%s, %s)`, helpers.DualStackSupp
...
+			testPodLabel   = "zgroup=testDSClient"
+		)
+		var (
+			gracefulTermYAML string
+			clientPod        string
+			serverPod        string
+			wg               sync.WaitGroup
+		)
+
+		waitForServer := func() {
```
Comment (brb) [inline test/k8sT/Services.go]: Could you move the helper functions to `service_helpers.go`, so that the file size can be reduced for the sake of readability? Also, you could make it more generic so that it can be reused.

File: test/k8sT/manifests/graceful-termination.yaml [hunk 20]
```diff
@@ -0,0 +1,69 @@
...
+kind: Service
+metadata:
+  name: graceful-term-svc
+spec:
+  ports:
+    - port: 8081
+  selector:
+    app: graceful-term-server
+---
+apiVersion: v1
```
Comment (brb) [inline test/k8sT/manifests/graceful-termination.yaml:11]: It would make reviewing easier if you could write a few comments saying what the server and the client does, and what output/behavior is used for testing. Otherwise, a reviewer needs to dive into the implementations of both.

File: test/k8sT/Services.go [hunk 21]
```diff
@@ -1548,6 +1549,155 @@ Secondary Interface %s :: IPv4: (%s, %s), IPv6: (%s, %s)`, helpers.DualStackSupp
...
+			ExpectWithOffset(1, len(podIPs)).To(Equal(1), "Unexpected number of service backends")
+			for _, ip := range podIPs {
+				err = kubectl.WaitForServiceBackend(helpers.K8s1, ip)
+				ExpectWithOffset(1, err).Should(BeNil(), "Failed waiting for %s backend entry on k8s1", ip)
+				err = kubectl.WaitForServiceBackend(helpers.K8s2, ip)
+				ExpectWithOffset(1, err).Should(BeNil(), "Failed waiting for %s backend entry on k8s2", ip)
+			}
+		}
+
+		terminateServiceEndpoint := func() {
```
Comment (brb) [inline test/k8sT/Services.go]: Ditto.

File: test/k8sT/Services.go [hunk 22]
```diff
@@ -1548,6 +1549,155 @@ Secondary Interface %s :: IPv4: (%s, %s), IPv6: (%s, %s)`, helpers.DualStackSupp
...
+				cancel()
+				res.WaitUntilFinish()
+			}()
+		}
+
+		BeforeAll(func() {
+			if helpers.SkipK8sVersions("<1.20.0") {
+				Skip(fmt.Sprintln("Graceful termination feature requires at least K8s version 1.20"))
+			}
+			DeployCiliumOptionsAndDNS(kubectl, ciliumFilename, map[string]string{
```
Comment (brb) [inline test/k8sT/Services.go:1592]: To reduce the suite runtime, have you considered moving the test case in the beginning where we test per-packet LB? Then the redeploying with KPR off is not needed.

**Review by brb — CHANGES_REQUESTED** [review]

**Comment by brb** [comment]
I'd prefer to have the Maglev resolved in this PR. Otherwise, we risk to have partially implemented feature for a long time.

File: test/k8sT/manifests/graceful-termination.yaml (hunk 18 above)
Comment (aditighag) [reply test/k8sT/manifests/graceful-termination.yaml:53]: No, it's not. It contains a bunch of other test apps. :( See my previous comment - https://github.com/cilium/cilium/pull/17716#discussion_r745769554.

File: test/k8sT/manifests/graceful-termination.yaml (hunk 20 above)
Comment (aditighag) [reply test/k8sT/manifests/graceful-termination.yaml:11]: There is a detailed description of the test apps in the commit description, and also in the e2e test inline. I don't see any description in other test yamls. I'll see what I can do more.

File: test/k8sT/Services.go (hunk 22 above)
Comment (aditighag) [reply test/k8sT/Services.go:1592]: Nice suggestion! Will look into that. Thanks!

File: pkg/service/service_test.go (hunk 14 above)
Comment (aditighag) [reply pkg/service/service_test.go:768]: Discussed offline, I'll revisit the code path along with the unit test case.

File: test/k8sT/manifests/graceful-termination.yaml (hunk 18 above)
Comment (brb) [reply test/k8sT/manifests/graceful-termination.yaml:53]: I meant this particular object is defined in both files.

File: test/k8sT/Services.go (hunk 22 above)
Comment (aditighag) [reply test/k8sT/Services.go:1592]: > have you considered moving the test case in the beginning where we test per-packet LB? Then the redeploying with KPR off is not needed.

Well, we don't enable kpr later on. We set kpr to `strict` on 4.19 and later. Per-packet LB tests are skipped on these kernels.

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.Checks graceful termination of service endpoints" --k8s_version=1.20 --kernel_version="419"

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.Checks graceful termination of service endpoints" --k8s_version=1.20 --kernel_version="419"

**Comment by aditighag** [comment]
\test

**Comment by aditighag** [comment]
ci-eks

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.Checks graceful termination of service endpoints" --k8s_version=1.20 --kernel_version="419"

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.Checks graceful termination of service endpoints" --k8s_version=1.22 --kernel_version="49"

**Review by brb — APPROVED** [review]
:rocket:

**Comment by aditighag** [comment]
CI test failures are unrelated - 

4.9 - https://github.com/cilium/cilium/issues/13011
gke - https://github.com/cilium/cilium/issues/17867

File: pkg/k8s/endpoints.go [hunk 23]
```diff
@@ -213,17 +235,33 @@ func parseEndpointPortV1Beta1(port slim_discovery_v1beta1.EndpointPort) (string,
...
 		// indicates an unknown state. In most cases consumers should interpret this
 		// unknown state as ready.
-		// More info: vendor/k8s.io/api/discovery/v1/types.go:117
+		// More info: vendor/k8s.io/api/discovery/v1/types.go
 		if sub.Conditions.Ready != nil && !*sub.Conditions.Ready {
+			skipEndpoint = true
+			if option.Config.EnableK8sTerminatingEndpoint {
+				// Terminating indicates that the endpoint is getting terminated. A
+				// nil values indicates an unknown state. Ready is never true when
+				// an endpoint is terminating. Propagate the terminating endpoint
```
Comment (aojea) [inline pkg/k8s/endpoints.go:256]: Kubernetes default behaviors allows graceful terminating, it never breaks established connections, doesn't matter the endpoints state.

This feature is meant to be used to allow sending NEW traffic to Terminating endpoints, "if there is no ready endpoint, then use the ones that are terminating AND SERVING"
```
	// serving is identical to ready except that it is set regardless of the
	// terminating state of endpoints. This condition should be set to true for
	// a ready endpoint that is terminating. If nil, consumers should defer to
	// the ready condition.
	// +optional
	Serving *bool
```

you should skip the endpoint is is terminating and not service

/cc @thockin
