### PR TITLE
EKS: improve rules for asymmetric routing (multi-node NodePort)

### LINKED ISSUE #13143: Breaking error around "open /proc/sys/net/ipv4/conf/eth0/rp_filter: no such file or directory" in 1.8.3
Originally discussed in https://github.com/cilium/cilium/issues/10645#issuecomment-688446819, @joestringer advised to open a separate issue for this behaviour/bug which seems to be a regression.

## Bug report

After attempting a `1.8.2` -> `1.8.3` upgrade on **Ubuntu 20.04 / 5.4.0-1021-aws**, agent pods end up crashing with the following logs. Rolling back to 1.8.2, pods are healthy and do not contain those errors. 🤷

```
{"error":"Failed to sysctl -w net.ipv4.conf.eth0.rp_filter=2: could not open the sysctl file /proc/sys/net/ipv4/conf/eth0/rp_filter: open /proc/sys/net/ipv4/conf/eth0/rp_filter: no such file or directory","level":"error","msg":"Error while initializing daemon","subsys":"daemon"}
{"error":"Failed to sysctl -w net.ipv4.conf.eth0.rp_filter=2: could not open the sysctl file /proc/sys/net/ipv4/conf/eth0/rp_filter: open /proc/sys/net/ipv4/conf/eth0/rp_filter: no such file or directory","level":"fatal","msg":"Error while creating daemon","subsys":"daemon"}
{"error":"Operation cannot be fulfilled on ciliumnodes.cilium.io \"ip-10-6-11-13.eu-west-1.compute.internal\": the object has been modified; please apply your changes to the latest version and try again","level":"warning","msg":"Unable to update CiliumNode custom resource","subsys":"ipam"}
{"level":"info","msg":"regenerating all endpoints","reason":"one or more identities created or deleted","subsys":"endpoint-manager"}
{"level":"info","msg":"regenerating all endpoints","reason":"one or more identities created or deleted","subsys":"endpoint-manager"}
```
**General Information**

- Cilium version: `1.8.3`
- Kernel version: `5.4.0-1021-aws`
- Orchestration system version: `EKS : v1.17.9-eks-4c6976`

**How to reproduce the issue**

1. [TO BE CONFIRMED] -> run an EKS cluster with [AWS Nitro](https://aws.amazon.com/ec2/nitro/) instances, [presumably](https://github.com/cilium/cilium/issues/10645#issuecomment-689025791) the issue is around the lack of `eth0` interface 
2. It should work with 1.8.2 but upgrading to 1.8.3 would cause the Cilium agent to crash after a few seconds

### PR DESCRIPTION
**Pull request by qmonnet**
Multi-node NodePort traffic on EKS needs specific rules regarding asymmetric routing. This PR improves the way those rules are implemented.

The most important change is related to the interface for which the rules are used. So far we have been creating them for the `eth0` interface (namely), because this is what EKS uses... With the default Amazon Linux 2 distribution. But EKS can also run with Ubuntu for example, and the name of the interface is not the same in that case. Instead of `eth0`, use the interface with the default route. I checked that this selects the same interfaces as the default AWS deamonset for the two AMIs Amazon Linux 2 (`eth0`) and Ubuntu 18.04 (`ens5`), and that `pod-to-b-multi-node-nodeport` from connectivity tests gets ready in both cases.

Other changes are minor, please refer to individual commits for details.

Fixes: #12770
Fixes: #13143

### CODE REVIEW

**Comment by qmonnet** [comment]
test-me-please

File: pkg/datapath/loader/base.go [hunk 1]
```diff
@@ -110,6 +110,43 @@ func writePreFilterHeader(preFilter *prefilter.PreFilter, dir string) error {
 	return fw.Flush()
 }
 
+type setting struct {
+	name      string
+	val       string
+	ignoreErr bool
+}
+
+func addENIRules(sysSettings *[]setting) error {
```
Comment (christarazi) [inline pkg/datapath/loader/base.go]: Nit: While passing the slice "by reference" gets the job done, instead the pattern in Golang is to return the updated slice. Slices under-the-hood are just a pointer to an array, so there aren't copies of the data being made when passed by value. Only the slice header is copied, hence why we return the slice because it updates the header.

> To understand how slices work, it helps to understand how they are implemented. There is a little data structure, the slice header, that is the item associated with the slice variable, and that header describes a section of a separately allocated array. When we pass slice values around, the header gets copied but the array it points to is always shared.

Source: https://blog.golang.org/slices#Conclusion

**Review by christarazi — COMMENTED** [review]
LGTM! Just a minor nit below.

**Review by joestringer — CHANGES_REQUESTED** [review]
Looks good overall, but I think it makes sense to fix up @christarazi's feedback.

File: pkg/datapath/loader/base.go (hunk 1 above)
Comment (qmonnet) [reply pkg/datapath/loader/base.go]: Thanks for the review, and for the feedback + link! I did have a doubt at some point, I guess I went C-style and just used a pointer... But that's fixed now. Interesting read!

**Comment by qmonnet** [comment]
> Looks good overall, but I think it makes sense to fix up @christarazi's feedback.

Of course it does :) Done now.

<details><summary>Incremental diff</summary>

``` diff
diff --git a/pkg/datapath/loader/base.go b/pkg/datapath/loader/base.go
index 0703bcc6e34f..042d013176a4 100644
--- a/pkg/datapath/loader/base.go
+++ b/pkg/datapath/loader/base.go
@@ -116,7 +116,7 @@ type setting struct {
 	ignoreErr bool
 }
 
-func addENIRules(sysSettings *[]setting) error {
+func addENIRules(sysSettings []setting) ([]setting, error) {
 	// AWS ENI mode requires symmetric routing, see
 	// iptables.addCiliumENIRules().
 	// The default AWS daemonset installs the following rules that are used
@@ -135,15 +135,15 @@ func addENIRules(sysSettings *[]setting) error {
 	//
 	// We want to reproduce equivalent rules to ensure correct routing.
 	if !option.Config.EnableIPv4 {
-		return nil
+		return nil, nil
 	}
 
 	iface, err := route.NodeDeviceWithDefaultRoute(option.Config.EnableIPv4, option.Config.EnableIPv6)
 	if err != nil {
-		return fmt.Errorf("failed to find interface with default route: %w", err)
+		return nil, fmt.Errorf("failed to find interface with default route: %w", err)
 	}
 
-	*sysSettings = append(*sysSettings, setting{
+	retSettings := append(sysSettings, setting{
 		fmt.Sprintf("net.ipv4.conf.%s.rp_filter", iface.Attrs().Name),
 		"2",
 		false,
@@ -154,10 +154,10 @@ func addENIRules(sysSettings *[]setting) error {
 		Mask:     linux_defaults.MaskMultinodeNodeport,
 		Table:    route.MainTable,
 	}); err != nil {
-		return fmt.Errorf("unable to install ip rule for ENI multi-node NodePort: %w", err)
+		return nil, fmt.Errorf("unable to install ip rule for ENI multi-node NodePort: %w", err)
 	}
 
-	return nil
+	return retSettings, nil
 }
 
 // Reinitialize (re-)configures the base datapath configuration including global
@@ -344,7 +344,8 @@ func (l *Loader) Reinitialize(ctx context.Context, o datapath.BaseProgramOwner,
 	}).Info("Setting up BPF datapath")
 
 	if option.Config.IPAM == ipamOption.IPAMENI {
-		if err := addENIRules(&sysSettings); err != nil {
+		var err error
+		if sysSettings, err = addENIRules(sysSettings); err != nil {
 			return fmt.Errorf("unable to install ip rule for ENI multi-node NodePort: %w", err)
 		}
 	}
```
</details>

**Comment by qmonnet** [comment]
test-me-please

File: pkg/datapath/loader/base.go [hunk 2]
```diff
@@ -110,6 +110,56 @@ func writePreFilterHeader(preFilter *prefilter.PreFilter, dir string) error {
...
+	//
+	// It marks packets coming from another node through eth0, and restores
+	// the mark on the return path to force a lookup into the main routing
+	// table. Without these rules, the "ip rules" set by the cilium-cni
+	// plugin tell the host to lookup into the table related to the VPC for
+	// which the CIDR used by the endpoint has been configured.
+	//
+	// We want to reproduce equivalent rules to ensure correct routing.
+	if !option.Config.EnableIPv4 {
+		return nil, nil
```
Comment (tklauser) [inline pkg/datapath/loader/base.go]: I think we should return `sysSettings` here in order to keep the existing ones.
```suggestion
		return sysSettings, nil
```

**Review by tklauser — CHANGES_REQUESTED** [review]

File: pkg/datapath/loader/base.go (hunk 2 above)
Comment (qmonnet) [reply pkg/datapath/loader/base.go]: Correct, thanks for catching this!

**Comment by qmonnet** [comment]
test-me-please

**Review by tklauser — APPROVED** [review]

**Review by vadorovsky — APPROVED** [review]

**Review by christarazi — APPROVED** [review]
