### PR TITLE
Fix EndpointSlice support

### LINKED ISSUE #11587: Endpoints disappear from ServiceInfo cache
## Bug report

Couldn't find a better title sorry!

**General Information**

- Cilium version (run `cilium version`)
```
Client: 1.7.3 952090308 2020-04-29T15:29:53-07:00 go version go1.13.10 linux/amd64
Daemon: 1.7.3 952090308 2020-04-29T15:29:53-07:00 go version go1.13.10 linux/amd64
```
- Kernel version (run `uname -a`)
```
5.3.0-51-generic #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
```
Kubernetes
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cilium config:
```
  auto-direct-node-routes: "false"
  bpf-ct-global-any-max: "262144"
  bpf-ct-global-tcp-max: "524288"
  cluster-name: default
  cni-chaining-mode: portmap
  container-runtime: none
  debug: "false"
  enable-ipv4: "true"
  enable-ipv6: "false"
  enable-node-port: "false"
  enable-remote-node-identity: "true"
  enable-well-known-identities: "false"
  identity-allocation-mode: crd
  install-iptables-rules: "true"
  kube-proxy-replacement: probe
  masquerade: "true"
  monitor-aggregation: medium
  preallocate-bpf-maps: "false"
  sidecar-istio-proxy-image: cilium/istio_proxy
  tofqdns-enable-poller: "false"
  tunnel: vxlan
  wait-bpf-mount: "false"
```

**How to reproduce the issue**

1. Looks like it happens after some time
2. Run `dig kubernetes.default.svc.cluster.local` inside a pod:
```
;; reply from unexpected source: 100.64.1.197#53, expected 10.32.0.10#53
```
```
$ tcpdump -i any 'port 53'
18:01:58.976876 IP 100.64.1.107.49805 > 10.32.0.10.domain: 49725+ [1au] A? kubernetes.default.svc.cluster.local. (77)
18:01:58.976980 IP 100.64.1.107.49805 > 100.64.1.197.domain: 49725+ [1au] A? kubernetes.default.svc.cluster.local. (77)
18:01:58.977420 IP 100.64.1.197.domain > 100.64.1.107.49805: 49725*- 1/0/1 A 10.32.0.1 (129)
18:01:58.977468 IP 100.64.1.197.domain > 100.64.1.107.49805: 49725*- 1/0/1 A 10.32.0.1 (129)
```
`100.64.1.107` is the pod IP
`10.32.0.10` is coredns service IP
`100.64.1.197` is coredns pod IP

on a working cluster : 
```
18:00:45.324371 IP 100.64.0.86.35473 > 100.64.0.246.domain: 25350+ [1au] A? kubernetes.default.svc.cluster.local. (77)
18:00:45.324444 IP 100.64.0.86.35473 > 100.64.0.246.domain: 25350+ [1au] A? kubernetes.default.svc.cluster.local. (77)
18:00:45.324790 IP 100.64.0.246.domain > 100.64.0.86.35473: 25350*- 1/0/1 A 10.32.0.1 (129)
18:00:45.324813 IP 100.64.0.246.domain > 100.64.0.86.35473: 25350*- 1/0/1 A 10.32.0.1 (129)
```

A restart of the cilium pod solves the issue.

### LINKED ISSUE #11921: Kubernetes service is not reachable from same host
## Bug report

**General Information**

- Cilium version: 1.7.3
- Kernel version: 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux
- Orchestration system version in use: Kubernetes v1.18.2
- Upload a system dump: I have one, but due to company restrictions I can't upload it to a public place. 

I have a service that has one endpoint in kubernetes and somehow pods on the same node are not able to connect to this service anymore. Pods from other nodes can still connect. A direct connection to the pod behind the service still works. 

Running  `cilium service list` also does not show the service on any node. Deleting the node behind the service seems to solve the problem.

If specific parts of a systemdump can help I will post them here. I should also be able to arrange that I can send the full dump to specific persons.

**How to reproduce the issue**
I can't reproduce the issue, but it appeared on 2 different kubernetes cluster in the last days.

Config options over configmap:
  auto-direct-node-routes: "false"
  bpf-ct-global-any-max: "262144"
  bpf-ct-global-tcp-max: "524288"
  cluster-name: default
  container-runtime: none
  debug: "false"
  enable-ipv4: "true"
  enable-ipv6: "false"
  enable-node-port: "false"
  identity-allocation-mode: crd
  install-iptables-rules: "true"
  masquerade: "true"
  monitor-aggregation: medium
  preallocate-bpf-maps: "false"
  prometheus-serve-addr: :9090
  sidecar-istio-proxy-image: <redacted>
  tofqdns-enable-poller: "false"
  tunnel: vxlan
  wait-bpf-mount: "false"

### PR DESCRIPTION
**Pull request by aanm**
The endpoint slice implementation did not account that a service could
map to multiple endpoint slices. Wrongly assuming that only a single
endpoint slice existed for a single service can cause Cilium to fail
the translation of a service to a backend in case 2 or more endpoint
slices existed. In some rare occurrences where a single endpoint slice
was deleted and another one was recreated, for the same service, it
could cause Cilium stop doing service translation entirely.

The unit test added easily replicates the issue as we can see the test
fails in the current master where the 2nd endpoint slice added overwrote
the 1st endpoint slice:

```
c.Assert(endpoints.String(), check.Equals, "2.2.2.2:8080/TCP,2.2.2.3:8080/TCP")
Expected :string = "2.2.2.2:8080/TCP,2.2.2.3:8080/TCP"
Actual   :string = "2.2.2.3:8080/TCP"
```

pkg/k8s: wait for EndpointSlice to be ready before initializing Cilium

Similar to the v1.Endpoints, in case Cilium is running with
EndpointSlice enabled, it should wait for the k8s watchers watching
those resources before it starts.

Fixes: c3b5ca6fdc40 ("add support for k8s endpoint slice")
Signed-off-by: André Martins <andre@cilium.io>

```release-note
Fix issue when Cilium randomly stops doing service translation in k8s 1.18
```

Fixes https://github.com/cilium/cilium/issues/11587
Fixes https://github.com/cilium/cilium/issues/11921

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-missed-k8s

**Review by nebril — APPROVED** [review]

File: pkg/k8s/endpoints.go [hunk 1]
```diff
@@ -172,15 +171,18 @@ func ParseEndpoints(ep *slim_corev1.Endpoints) (ServiceID, *Endpoints) {
 
 // ParseEndpointSliceID parses a Kubernetes endpoints slice and returns the
 // ServiceID
```
Comment (brb) [inline pkg/k8s/endpoints.go]: Nit: returns EndpointSliceID.

**Review by christarazi — APPROVED** [review]

File: pkg/k8s/endpoints.go [hunk 2]
```diff
@@ -239,6 +241,54 @@ func parseEndpointPort(port slim_discover_v1beta1.EndpointPort) (string, *loadba
 	return name, lbPort
 }
 
+// endpointSlices is the collection of all endpoint slices in the cluster.
+// The map key is the name of the endpoint slice.
+type endpointSlices struct {
+	epSlices map[string]*Endpoints
+}
+
+// newEndpointsSlices returns a new endpointSlices
```
Comment (brb) [inline pkg/k8s/endpoints.go:253]: Nit: IMHO redundant comment for the private type.

File: pkg/k8s/watchers/watcher.go [hunk 3]
```diff
@@ -370,6 +370,7 @@ func (k *K8sWatcher) InitK8sSubsystem() <-chan struct{} {
 			// To perform the service translation and have the BPF LB datapath
 			// with the right service -> backend (k8s endpoints) translation.
 			K8sAPIGroupEndpointV1Core,
+			K8sAPIGroupEndpointSliceV1Beta1Discovery,
```
Comment (brb) [inline pkg/k8s/watchers/watcher.go:373]: What will happen, if k8s runs w/o endpoint slice support?

File: pkg/k8s/endpoints.go [hunk 4]
```diff
@@ -239,6 +241,54 @@ func parseEndpointPort(port slim_discover_v1beta1.EndpointPort) (string, *loadba
 	return name, lbPort
 }
 
+// endpointSlices is the collection of all endpoint slices in the cluster.
+// The map key is the name of the endpoint slice.
+type endpointSlices struct {
+	epSlices map[string]*Endpoints
```
Comment (brb) [inline pkg/k8s/endpoints.go:250]: Shouldn't the key be namespace + endpoint slice name? Otherwise I find "the collection of all endpoint slices in the cluster" misleading.

File: pkg/k8s/endpoints.go [hunk 5]
```diff
@@ -239,6 +241,54 @@ func parseEndpointPort(port slim_discover_v1beta1.EndpointPort) (string, *loadba
...
+	}
+	return allEps
+}
+
+// Upsert maps the 'esname' to 'e'.
+// - 'esname': Name of the Endpoint Slice
+// - 'e': Endpoints to store in the map
+func (es *endpointSlices) Upsert(esname string, e *Endpoints) {
+	if es == nil {
+		panic("nil map")
```
Comment (brb) [inline pkg/k8s/endpoints.go]: Do we really want to panic here? Maybe return an error instead, so that the top layer can decide what to do?

File: pkg/k8s/endpoints.go [hunk 6]
```diff
@@ -239,6 +241,54 @@ func parseEndpointPort(port slim_discover_v1beta1.EndpointPort) (string, *loadba
...
+			allEps.Backends[backend] = ep
+		}
+	}
+	return allEps
+}
+
+// Upsert maps the 'esname' to 'e'.
+// - 'esname': Name of the Endpoint Slice
+// - 'e': Endpoints to store in the map
+func (es *endpointSlices) Upsert(esname string, e *Endpoints) {
```
Comment (brb) [inline pkg/k8s/endpoints.go]: Nit: s/esname/esName/ ?

File: pkg/k8s/service_cache.go [hunk 7]
```diff
@@ -81,9 +81,12 @@ type ServiceCache struct {
 
 	// mutex protects the maps below including the concurrent access of each
 	// value.
-	mutex     lock.RWMutex
-	services  map[ServiceID]*Service
-	endpoints map[ServiceID]*Endpoints
+	mutex    lock.RWMutex
+	services map[ServiceID]*Service
+	// endpoints maps a service to a map of endpointSlices. In case the cluster
```
Comment (brb) [inline pkg/k8s/service_cache.go:86]: Is it allowed by k8s to create an endpoint slice with an empty name?

**Review by brb — COMMENTED** [review]
From the first glance LGTM - mostly nits and comments. I will do another round of the review once they have been addressed.

File: pkg/k8s/endpoints.go (hunk 4 above)
Comment (aanm) [reply pkg/k8s/endpoints.go:250]: `s/cluster/service`

File: pkg/k8s/service_cache.go (hunk 7 above)
Comment (aanm) [reply pkg/k8s/service_cache.go:86]: No, I've changed this to make it clear.

File: pkg/k8s/endpoints.go (hunk 5 above)
Comment (aanm) [reply pkg/k8s/endpoints.go]: IMO, yes, if this happens it is a programmer error.

**Review by aanm — COMMENTED** [review]
@brb PTAL

File: pkg/k8s/watchers/watcher.go (hunk 3 above)
Comment (aanm) [reply pkg/k8s/watchers/watcher.go:373]: Nothing, `WaitForCacheSync` only waits for the groups of the resources marked to be synchronized.

File: pkg/k8s/endpoints.go (hunk 5 above)
Comment (brb) [reply pkg/k8s/endpoints.go]: Then maybe we could change the panic msg to "BUG: endpointSlices is nil"?

**Review by brb — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please
