### PR TITLE
fix(hubble): use strconv.Itoa for kafka.ErrorCode + add unit tests

### LINKED ISSUE #35749: [hubble] hubble_kafka_requests_total error_code contains undefined unicode character �
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.15.7 and lower than v1.16.0

### What happened?

I’m testing Hubble Kafka metrics in a BYO CNI AKS cluster and observed that the hubble_kafka_requests_total metric displays an undefined Unicode character for the error code:

Image

Upon reviewing the code, I found that Hubble uses `string()` to convert `kafka.ErrorCode`:

Image

Is this the intended behavior? Would it be more appropriate to use `strconv.Itoa` instead?

### How can we reproduce the issue?

Installed Cilium with this command
```
cilium install --version 1.15.10 --set azure.resourceGroup="${AZURE_RESOURCE_GROUP}" --set envoy.enabled=true --set prometheus.enabled=true --set hubble.enabled=true --set hubble.metrics.enabled="{flow:sourceEgressContext=pod;destinationIngressContext=pod,flows-to-world:sourceEgressContext=pod;destinationIngressContext=pod,httpV2:sourceEgressContext=pod;destinationIngressContext=pod,kafka:sourceEgressContext=pod;destinationIngressContext=pod}"
```

### Cilium Version

v1.15.10

### Kernel Version

5.15.0-1073-azure

### Kubernetes Version

v1.30.5

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by nddq**
Fixes: #35749
```release-note
Use `strconv.Itoa` instead of `string()` for the correct behavior when converting `kafka.ErrorCode` from `int32` to `string`. Add relevant unit tests for Kafka plugin and handler.
```

Verified that `hubble_kafka_requests_total` is working with the fix
image
image

### CODE REVIEW

**Review by chancez — APPROVED** [review]

**Comment by nddq** [comment]
oops didn't realize clicking `Update Branch` on the Github UI will do that 🥲

**Comment by nddq** [comment]
@joestringer looks like it is failing the conformance test for some reason. Also, I'm curious about the process of backport a bug fix to previous Cilium's versions. Do I need to open a different PR for that?

**Comment by joestringer** [comment]
The failure looks unrelated, I filed https://github.com/cilium/cilium/issues/35872 for it and will re-run the test. For backport we can mark it for v1.16.

File: pkg/hubble/metrics/kafka/plugin_test.go [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+ destinationContext        ::= identifier , { "|", identifier }
+ sourceEgressContext       ::= identifier , { "|", identifier }
+ sourceIngressContext      ::= identifier , { "|", identifier }
+ destinationEgressContext  ::= identifier , { "|", identifier }
+ destinationIngressContext ::= identifier , { "|", identifier }
+ labels                    ::= label , { ",", label }
+ identifier                ::= identity | namespace | pod | pod-name | dns | ip | reserved-identity | workload | workload-name | app
+ label                     ::= source_ip | source_pod | source_namespace | source_workload | source_workload_kind | source_app | destination_ip | destination_pod | destination_namespace | destination_workload | destination_workload_kind | destination_app | traffic_direction
+`
+	assert.Equal(t, expected, plugin.HelpText())
```
Comment (joestringer) [inline pkg/hubble/metrics/kafka/plugin_test.go:32]: Why is it helpful to have a test that checks the kafka plugin help text?

Comment (nddq) [reply pkg/hubble/metrics/kafka/plugin_test.go:32]: I was following what we currently have for the http metrics handler but looks like this is not implemented for other handlers. I can remove this if this is not helpful beside increasing code coverage 🙂

**Review by rolinh — APPROVED** [review]
Thanks, patch lgtm

File: pkg/hubble/metrics/kafka/plugin_test.go (hunk 1 above)
Comment (joestringer) [reply pkg/hubble/metrics/kafka/plugin_test.go:32]: OK. I guess it's trying to make sure that all of the relevant labels are exported.
