### PR TITLE
pkg: add port name to address-based lrp

### LINKED ISSUE #41589: lrp not using the right port number
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

latest from main

### What happened?

With the new LRP control plane with the current bug fix. I still found that we don't have the right backend created for multiple frontend ports.

For example,

```
apiVersion: "cilium.io/v2"
kind: CiliumLocalRedirectPolicy
metadata:
  name: "lrp-addr"
spec:
  redirectFrontend:
    addressMatcher:
      ip: "169.254.169.254"
      toPorts:
        - port: "8080"
          name: "test"
          protocol: TCP
        - port: "8081"
          name: "test1"
          protocol: TCP
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        app: proxy
    toPorts:
      - port: "80"
        name: "test"
        protocol: TCP
      - port: "81"
        name: "test1"
        protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: lrp-pod
  labels:
    app: proxy
spec:
  containers:
    - name: lrp-pod
      image: nginx
      ports:
        - containerPort: 80
          name: test
          protocol: TCP
        - containerPort: 81
          name: test1
          protocol: TCP

```

we will get
```
6    169.254.169.254:8080/TCP   LocalRedirect   1 => 10.244.1.75:80/TCP (active)
                                                2 => 10.244.1.75:81/TCP (active)
7    169.254.169.254:8081/TCP   LocalRedirect   1 => 10.244.1.75:80/TCP (active)
                                                2 => 10.244.1.75:81/TCP (active)
```

In 1.17, we will get
```
6    169.254.169.254:8080/TCP   LocalRedirect   1 => 10.244.2.184:80/TCP (active)
7    169.254.169.254:8081/TCP   LocalRedirect   1 => 10.244.2.184:81/TCP (active)
```

I'm on Cilium 1.19.0-dev 9ea94fec85

### How can we reproduce the issue?

just build and install cilium from the latest main and use the following LRP config

### Cilium Version

1.19.0-dev 9ea94fec85

### Kernel Version

na

### Kubernetes Version

na

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by liyihuang**
see the commit msg

Fixes: #41589

```release-note
add the port name for address based LRP so frontend can pick the right backend
```

### CODE REVIEW

**Comment by liyihuang** [comment]
ok, we are allowing front and backend not match in the connectiviy test in LRP. I will push another fix from lrp controller to resolve this.

**Review by aditighag — COMMENTED** [review]
Thanks for the fix. I've pushed this commit adding unit test cases - https://github.com/cilium/cilium/pull/41608/commits/ebecab86e77f6f219fd4518163933d01fa86c252 to your PR.

File: pkg/loadbalancer/redirectpolicy/controller.go [hunk 1]
```diff
@@ -322,13 +322,18 @@ func (c *lrpController) updateRedirects(wtxn writer.WriteTxn, ws *statedb.WatchS
 					}
 					continue
 				}
+				//if we only have one frontend mapping, we dont need the frontend port name so it will not check the port name in the backend ports
+				if len(lrp.FrontendMappings) == 1 {
+					feM.fePort = lb.FEPortName("")
+				}
```
Comment (aditighag) [inline pkg/loadbalancer/redirectpolicy/controller.go]: Why is this required?

Comment (liyihuang) [reply pkg/loadbalancer/redirectpolicy/controller.go]: I found this is required because we have the test for this.

https://github.com/cilium/cilium/blob/main/cilium-cli/connectivity/builder/manifests/local-redirect-policy.yaml#L11-L19. Maybe the question is why we have such test where the frontend name is different from backend. If we already allow this in the past, I dont know if we need to keep it in case there is the surprise when people upgrade to 1.18? I can also change the test.

Comment (aditighag) [reply pkg/loadbalancer/redirectpolicy/controller.go]: Good spotting! Let's fix the test -- I don't remember any particular reason for the mismatched port names.

File: pkg/loadbalancer/redirectpolicy/controller.go [hunk 2]
```diff
@@ -322,13 +322,18 @@ func (c *lrpController) updateRedirects(wtxn writer.WriteTxn, ws *statedb.WatchS
...
 				_, err := c.p.Writer.UpsertFrontend(
 					wtxn,
 					lb.FrontendParams{
 						Address:     feM.feAddr,
 						Type:        lb.SVCTypeLocalRedirect,
 						ServiceName: lrpServiceName,
 						ServicePort: feM.feAddr.Port(),
+						PortName:    feM.fePort,
```
Comment (aditighag) [inline pkg/loadbalancer/redirectpolicy/controller.go]: Can we do this instead of overwriting the `feM.fePort `

```
PortName: func() string {
					if len(lrp.FrontendMappings) > 1 {
						return feM.fePort
					}
					return lb.FEPortName("")
				}(),
```

File: pkg/loadbalancer/redirectpolicy/controller.go (hunk 1 above)
Comment (liyihuang) [reply pkg/loadbalancer/redirectpolicy/controller.go:328]: hope this is not a feature that we offered to the users before.

File: pkg/loadbalancer/redirectpolicy/controller.go (hunk 2 above)
Comment (liyihuang) [reply pkg/loadbalancer/redirectpolicy/controller.go]: I can definitely change this but I have questions/concerns.

Do we want to offer the users that the frontend not need to match the backend user experience when there is only one frontend?

If so, I think we can just keep the test this way https://github.com/cilium/cilium/blob/main/cilium-cli/connectivity/builder/manifests/local-redirect-policy.yaml#L11-L19 since that's kind of check from connectivity test perspective.

If we want users to keep the frontend/backend port the same even there is one frontend, we dont have to write the function at all, since it will just pass the frontend port name. Then in the writer, it will check the if that's correct.

Comment (aditighag) [reply pkg/loadbalancer/redirectpolicy/controller.go]: Ack -- The docs suggest that we only use port names for matching when there are multiple ports, so there is a bit of an ambiguity there as we simply ignored port name in the earlier implementation. Let's be consistent.

**Review by aditighag — APPROVED** [review]

**Comment by joamaki** [comment]
I'm seeing a test flake when running `pkg/loadbalancer/stress.sh`:
```
        scripttest.go:273: FAIL: testdata/address-matcher-named-ports.txtar:46: db/cmp backends backends-single.table: table mismatch:
              Address             Instances
            - 10.244.2.1:50/TCP   test/lrp-addr-single:local-redirect (test)
            + 10.244.2.1:50/TCP   test/lrp-addr-single:local-redirect
```

Fairly rare: `22s: 500 runs total, 4 failures (0.80%)`

EDIT: Figured it out. `pod.yaml` and `pod-single.yaml` used the same name and because the controller was only checking if the backend address changed it sometimes processed using the older `pod.yaml` in the test and didn't reprocess `pod-single.yaml`. Doing a PR to fix.
