### PR TITLE
policy: Support l4 any port policy

### LINKED ISSUE #21184: NetworkPolicy: should enforce ingress policy allowing any port traffic to a server on a specific protocol
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Create a NetworkPolicy allow any port traffic，but it doesn't work，cilium will deny.
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-by-proto
  namespace: cilium-test
spec:
  ingress:
  - ports:
    - protocol: TCP
  podSelector:
    matchLabels:
      kind: echo
  policyTypes:
  - Ingress
```
```bash
$ cilium policy get
[
  {
    "endpointSelector": {
      "matchLabels": {
        "k8s:io.kubernetes.pod.namespace": "cilium-test",
        "k8s:kind": "echo"
      }
    },
    "ingress": [
      {
        "fromEndpoints": [
          {}
        ],
        "toPorts": [
          {
            "ports": [
              {
                "port": "0",
                "protocol": "TCP"
              }
            ]
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "io.cilium.k8s.policy.derived-from",
        "value": "NetworkPolicy",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.name",
        "value": "allow-ingress-by-proto",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.namespace",
        "value": "cilium-test",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.uid",
        "value": "5367ac00-1d2e-402f-9054-6910d1f1e7d4",
        "source": "k8s"
      }
    ]
  }
]
Revision: 310
```
```bash
$ cilium monitor --to 490 -v
Press Ctrl-C to quit
level=info msg="Initializing dissection cache..." subsys=monitor
Policy verdict log: flow 0xc20b6886 local EP ID 490, remote ID 3403, proto 6, ingress, action deny, match none, 192.168.1.20:60714 -> 192.168.1.44:8080 tcp SYN
xx drop (Policy denied) flow 0xc20b6886 to endpoint 490, file bpf_lxc.c line 1979, , identity 3403->28673: 192.168.1.20:60714 -> 192.168.1.44:8080 tcp SYN
```

### Cilium Version

1.12.0

### Kernel Version

5.4.119

### Kubernetes Version

1.22.5

### Sysdump

_No response_

### Relevant log output

```shell
level=info msg="Policy Add Request" ciliumNetworkPolicy="[&{EndpointSelector:{\"matchLabels\":{\"k8s:io.kubernetes.pod.namespace\":\"cilium-test\",\"k8s:kind\":\"echo\"}} NodeSelector:{} Ingress:[{IngressCommonRule:{FromEndpoints:[{}] FromRequires:[] FromCIDR: FromCIDRSet:[] FromEntities:[] aggregatedSelectors:[]} ToPorts:[{Ports:[{Port:0 Protocol:TCP}] TerminatingTLS:<nil> OriginatingTLS:<nil> Rules:<nil>}] ICMPs:[]}] IngressDeny:[] Egress:[] EgressDeny:[] Labels:[k8s:io.cilium.k8s.policy.derived-from=NetworkPolicy k8s:io.cilium.k8s.policy.name=allow-ingress-by-proto k8s:io.cilium.k8s.policy.namespace=cilium-test k8s:io.cilium.k8s.policy.uid=03d66abd-7bee-408c-9538-fb3dc7968a83] Description:}]" policyAddRequest=7743e9b9-a7cd-48fc-a9bb-de0fe13817e4 subsys=daemon
level=debug msg="Policy imported via API, found CIDR prefixes..." policyAddRequest=7743e9b9-a7cd-48fc-a9bb-de0fe13817e4 prefixes="[]" subsys=daemon
level=info msg="Policy imported via API, recalculating..." policyAddRequest=7743e9b9-a7cd-48fc-a9bb-de0fe13817e4 policyRevision=10 subsys=daemon
level=info msg="NetworkPolicy successfully added" k8sApiVersion= k8sNetworkPolicyName=allow-ingress-by-proto subsys=k8s-watcher
level=debug msg="EventQueue event processing statistics" eventConsumeOffQueueWaitTime="7.043µs" eventEnqueueWaitTime="5.871µs" eventHandlingDuration="166.281µs" eventType="*cmd.PolicyAddEvent" name=repository-change-queue subsys=eventqueue
level=debug msg="Triggering endpoint regeneration due to policy rules added" code=OK containerID=1487649442 datapathPolicyRevision=9 desiredPolicyRevision=9 endpointID=490 endpointState=waiting-to-regenerate identity=28673 ipv4=192.168.1.44 ipv6="fe80::f849:b6ff:fe16:be0c" k8sPodName=cilium-test/echo-same-node-bbb6b5ddb-jjfb7 policyRevision=9 subsys=endpoint type=0
level=debug msg="Dequeued endpoint from build queue" containerID=1487649442 datapathPolicyRevision=9 desiredPolicyRevision=9 endpointID=490 identity=28673 ipv4=192.168.1.44 ipv6="fe80::f849:b6ff:fe16:be0c" k8sPodName=cilium-test/echo-same-node-bbb6b5ddb-jjfb7 subsys=endpoint
level=debug msg="EventQueue event processing statistics" eventConsumeOffQueueWaitTime="6.863µs" eventEnqueueWaitTime="5.72µs" eventHandlingDuration="9.367µs" eventType="*endpoint.EndpointRevisionBumpEvent" name=endpoint-2727 subsys=eventqueue
level=debug msg="EventQueue event processing statistics" eventConsumeOffQueueWaitTime="8.827µs" eventEnqueueWaitTime="7.855µs" eventHandlingDuration="11.131µs" eventType="*endpoint.EndpointRevisionBumpEvent" name=endpoint-2933 subsys=eventqueue
level=debug msg="Regenerating endpoint" containerID=1487649442 datapathPolicyRevision=9 desiredPolicyRevision=9 endpointID=490 identity=28673 ipv4=192.168.1.44 ipv6="fe80::f849:b6ff:fe16:be0c" k8sPodName=cilium-test/echo-same-node-bbb6b5ddb-jjfb7 reason="policy rules added" startTime="2022-09-01 09:26:53.278984294 +0000 UTC m=+1334.726869889" subsys=endpoint
level=debug msg="EventQueue event processing statistics" eventConsumeOffQueueWaitTime="5.459µs" eventEnqueueWaitTime="4.487µs" eventHandlingDuration="6.412µs" eventType="*endpoint.EndpointRevisionBumpEvent" name=endpoint-374 subsys=eventqueue
level=debug msg="Regenerating endpoint: policy rules added" code=OK containerID=1487649442 datapathPolicyRevision=9 desiredPolicyRevision=9 endpointID=490 endpointState=regenerating identity=28673 ipv4=192.168.1.44 ipv6="fe80::f849:b6ff:fe16:be0c" k8sPodName=cilium-test/echo-same-node-bbb6b5ddb-jjfb7 policyRevision=9 subsys=endpoint type=0
level=debug msg="removing directory" containerID=1487649442 datapathPolicyRevision=9 desiredPolicyRevision=9 directory=490_next endpointID=490 identity=28673 ipv4=192.168.1.44 ipv6="fe80::f849:b6ff:fe16:be0c" k8sPodName=cilium-test/echo-same-node-bbb6b5ddb-jjfb7 subsys=endpoint
level=debug msg="Starting policy recalculation..." containerID=1487649442 datapathPolicyRevision=9 desiredPolicyRevision=9 endpointID=490 identity=28673 ipv4=192.168.1.44 ipv6="fe80::f849:b6ff:fe16:be0c" k8sPodName=cilium-test/echo-same-node-bbb6b5ddb-jjfb7 subsys=endpoint
level=debug msg="ToMapState: allow all" EndpointSelector="&LabelSelector{MatchLabels:map[string]string{},MatchExpressions:[]LabelSelectorRequirement{},}" port=0 portName= protocol=6 subsys=policy trafficDirection=Ingress
level=debug msg="Completed endpoint policy recalculation" containerID=1487649442 datapathPolicyRevision=9 desiredPolicyRevision=10 endpointID=490 forcedRegeneration=false identity=28673 ipv4=192.168.1.44 ipv6="fe80::f849:b6ff:fe16:be0c" k8sPodName=cilium-test/echo-same-node-bbb6b5ddb-jjfb7 policyCalculation="&{{{{{0 0} 0 0 0 0}}} {0 0 <nil>} 87274 0}" subsys=endpoint waitingForIdentityCache="&{{{{{0 0} 0 0 0 0}}} {0 0 <nil>} 0 0}" waitingForPolicyRepository="&{{{{{0 0} 0 0 0 0}}} {0 0 <nil>} 351 0}"
level=debug msg="BPF header file hashed (was: \"8f1e0a7a0896ae28efc455df6309e62b9d2a0e61d64713bfef9381784c31f7bf\")" bpfHeaderfileHash=9a9e99e27a8ae6e0f42d9ec3bb3a68c526c39f30d52086286cdc7e2a6bfa4f16 containerID=1487649442 datapathPolicyRevision=9 desiredPolicyRevision=10 endpointID=490 identity=28673 ipv4=192.168.1.44 ipv6="fe80::f849:b6ff:fe16:be0c" k8sPodName=cilium-test/echo-same-node-bbb6b5ddb-jjfb7 subsys=endpoint
level=debug msg="writing header file" containerID=1487649442 datapathPolicyRevision=9 desiredPolicyRevision=10 endpointID=490 file-path=490_next/ep_config.h identity=28673 ipv4=192.168.1.44 ipv6="fe80::f849:b6ff:fe16:be0c" k8sPodName=cilium-test/echo-same-node-bbb6b5ddb-jjfb7 subsys=endpoint
level=debug msg="EventQueue event processing statistics" eventConsumeOffQueueWaitTime="20.308µs" eventEnqueueWaitTime=671ns eventHandlingDuration="613.308µs" eventType="*cmd.PolicyReactionEvent" name=repository-reaction-queue subsys=eventqueue
level=debug msg="EventQueue event processing statistics" eventConsumeOffQueueWaitTime="33.082µs" eventEnqueueWaitTime="12.514µs" eventHandlingDuration="7.324µs" eventType="*endpoint.EndpointRevisionBumpEvent" name=endpoint-2151 subsys=eventqueue
level=debug msg="Preparing to compile BPF" containerID=1487649442 datapathPolicyRevision=9 desiredPolicyRevision=10 endpointID=490 identity=28673 ipv4=192.168.1.44 ipv6="fe80::f849:b6ff:fe16:be0c" k8sPodName=cilium-test/echo-same-node-bbb6b5ddb-jjfb7 regeneration-level=rewrite+load subsys=endpoint
level=debug msg="Skipping " subsys=elf
level=debug msg="Skipping " subsys=elf
level=debug msg="Skipping " subsys=elf
level=debug msg="Skipping " subsys=elf
level=debug msg="Skipping " subsys=elf
level=debug msg="Skipping " subsys=elf
level=debug msg="Skipping " subsys=elf
level=debug msg="Skipping " subsys=elf
level=debug msg="Skipping " subsys=elf
level=debug msg="Found variable with offset 65324" subsys=elf symbol=LXC_ID
level=debug msg="Found variable with offset 65320" subsys=elf symbol=LXC_IPV4
level=debug msg="Found variable with offset 65304" subsys=elf symbol=LXC_IP_1
level=debug msg="Found variable with offset 65308" subsys=elf symbol=LXC_IP_2
level=debug msg="Found variable with offset 65312" subsys=elf symbol=LXC_IP_3
level=debug msg="Found variable with offset 65316" subsys=elf symbol=LXC_IP_4
level=debug msg="Found variable with offset 65328" subsys=elf symbol=NODE_MAC_1
level=debug msg="Found variable with offset 65332" subsys=elf symbol=NODE_MAC_2
level=debug msg="Found variable with offset 65344" subsys=elf symbol=POLICY_VERDICT_LOG_FILTER
level=debug msg="Found variable with offset 65336" subsys=elf symbol=SECLABEL
level=debug msg="Found variable with offset 65340" subsys=elf symbol=SECLABEL_NB
level=debug msg="Found symbol referring to unknown section id 24" subsys=elf symbol=____license
level=debug msg="Skipping __send_drop_notify" subsys=elf
level=debug msg="Found symbol with offset 532080" subsys=elf symbol=cilium_call_policy
level=debug msg="Found symbol with offset 535089" subsys=elf symbol=cilium_calls_65535
level=debug msg="Found symbol with offset 532468" subsys=elf symbol=cilium_ct4_global
level=debug msg="Found symbol with offset 532446" subsys=elf symbol=cilium_ct_any4_global
level=debug msg="Found symbol with offset 532524" subsys=elf symbol=cilium_encrypt_state
level=debug msg="Found symbol with offset 532213" subsys=elf symbol=cilium_events
level=debug msg="Found symbol with offset 532590" subsys=elf symbol=cilium_ipcache
level=debug msg="Found symbol with offset 532288" subsys=elf symbol=cilium_ipv4_frag_datagrams
level=debug msg="Found symbol with offset 532041" subsys=elf symbol=cilium_lb4_affinity
level=debug msg="Found symbol with offset 536438" subsys=elf symbol=cilium_lb4_backends_v2
level=debug msg="Found symbol with offset 532190" subsys=elf symbol=cilium_lb4_reverse_nat
level=debug msg="Found symbol with offset 536415" subsys=elf symbol=cilium_lb4_services_v2
level=debug msg="Found symbol with offset 532486" subsys=elf symbol=cilium_lb_affinity_match
level=debug msg="Found symbol with offset 532605" subsys=elf symbol=cilium_lxc
level=debug msg="Found symbol with offset 532348" subsys=elf symbol=cilium_metrics
level=debug msg="Found symbol with offset 535069" subsys=elf symbol=cilium_policy_65535
level=debug msg="Found symbol with offset 532315" subsys=elf symbol=cilium_signals
level=debug msg="Found symbol with offset 535301" subsys=elf symbol=cilium_tail_call_buffer4
level=debug msg="Skipping handle_policy" subsys=elf
level=debug msg="Skipping handle_to_container" subsys=elf
level=debug msg="Skipping handle_xgress" subsys=elf
level=debug msg="Skipping tail_handle_ipv4" subsys=elf
level=debug msg="Skipping tail_handle_ipv4_cont" subsys=elf
level=debug msg="Skipping tail_ipv4_ct_egress" subsys=elf
level=debug msg="Skipping tail_ipv4_ct_ingress" subsys=elf
level=debug msg="Skipping tail_ipv4_to_endpoint" subsys=elf
level=debug msg="Found section with offset 532137" subsys=elf symbol=.BTF.ext
level=debug msg="Found section with offset 532334" subsys=elf symbol=.debug_ranges
level=debug msg="Found section with offset 532398" subsys=elf symbol=to-container
level=debug msg="Found section with offset 532415" subsys=elf symbol=from-container
level=debug msg="Found section with offset 532434" subsys=elf symbol=.debug_info
level=debug msg="Found section with offset 532515" subsys=elf symbol=1/0xffff
level=debug msg="Found section with offset 532561" subsys=elf symbol=.debug_line
level=debug msg="Found section with offset 532577" subsys=elf symbol=.debug_frame
level=debug msg="Found section with offset 532620" subsys=elf symbol=.debug_loc
level=debug msg="Found section with offset 532702" subsys=elf symbol=.BTF
level=debug msg="Found section with offset 533076" subsys=elf symbol=2/29
level=debug msg="Found section with offset 534049" subsys=elf symbol=2/27
level=debug msg="Found section with offset 534163" subsys=elf symbol=2/7
level=debug msg="Found section with offset 535182" subsys=elf symbol=2/25
level=debug msg="Found section with offset 536365" subsys=elf symbol=2/13
level=debug msg="Found section with offset 537460" subsys=elf symbol=2/1
level=debug msg="Finished writing ELF" error="<nil>" new-elf-path=490_next/bpf_lxc.o subsys=elf template-path=/var/run/cilium/state/templates/dbc0bc50119f71b31273c12c0c37cb5876b0ed229894962dd714575cd8ee4488/bpf_lxc.o
level=debug msg="netlink: Replacing qdisc for eni01401b8d8c6 succeeded" subsys=datapath-loader
level=debug msg="tc filter using priority 1 for interface eni01401b8d8c6" subsys=datapath-loader
level=debug msg="netlink: Replacing qdisc for eni01401b8d8c6 succeeded" subsys=datapath-loader
level=debug msg="tc filter using priority 1 for interface eni01401b8d8c6" subsys=datapath-loader
level=debug msg="Finalizing bpffs map migration" device=eni01401b8d8c6 objPath=490_next/bpf_lxc.o subsys=datapath-loader
level=debug msg="Finalizing bpffs map migration" device=eni01401b8d8c6 objPath=490_next/bpf_lxc.o subsys=datapath-loader
level=info msg="Rewrote endpoint BPF program" containerID=1487649442 datapathPolicyRevision=9 desiredPolicyRevision=10 endpointID=490 identity=28673 ipv4=192.168.1.44 ipv6="fe80::f849:b6ff:fe16:be0c" k8sPodName=cilium-test/echo-same-node-bbb6b5ddb-jjfb7 subsys=endpoint
level=debug msg="Waiting for proxy updates to complete..." containerID=1487649442 datapathPolicyRevision=9 desiredPolicyRevision=10 endpointID=490 identity=28673 ipv4=192.168.1.44 ipv6="fe80::f849:b6ff:fe16:be0c" k8sPodName=cilium-test/echo-same-node-bbb6b5ddb-jjfb7 subsys=endpoint
level=debug msg="Wait time for proxy updates: 15.749µs" containerID=1487649442 datapathPolicyRevision=9 desiredPolicyRevision=10 endpointID=490 identity=28673 ipv4=192.168.1.44 ipv6="fe80::f849:b6ff:fe16:be0c" k8sPodName=cilium-test/echo-same-node-bbb6b5ddb-jjfb7 subsys=endpoint
level=debug msg="Finalizing successful endpoint regeneration" containerID=1487649442 datapathPolicyRevision=9 desiredPolicyRevision=10 endpointID=490 identity=28673 ipv4=192.168.1.44 ipv6="fe80::f849:b6ff:fe16:be0c" k8sPodName=cilium-test/echo-same-node-bbb6b5ddb-jjfb7 subsys=endpoint
level=debug msg="synchronizing directories" containerID=1487649442 datapathPolicyRevision=9 desiredPolicyRevision=10 endpointID=490 identity=28673 ipv4=192.168.1.44 ipv6="fe80::f849:b6ff:fe16:be0c" k8sPodName=cilium-test/echo-same-node-bbb6b5ddb-jjfb7 subsys=endpoint
level=debug msg="endpoint directory exists; backing it up" containerID=1487649442 datapathPolicyRevision=9 desiredPolicyRevision=10 endpointID=490 identity=28673 ipv4=192.168.1.44 ipv6="fe80::f849:b6ff:fe16:be0c" k8sPodName=cilium-test/echo-same-node-bbb6b5ddb-jjfb7 subsys=endpoint
level=debug msg="removing directory" containerID=1487649442 datapathPolicyRevision=9 desiredPolicyRevision=10 directory=490_stale endpointID=490 identity=28673 ipv4=192.168.1.44 ipv6="fe80::f849:b6ff:fe16:be0c" k8sPodName=cilium-test/echo-same-node-bbb6b5ddb-jjfb7 subsys=endpoint
level=debug msg="moving current directory to backup location" backupDirectory=490_stale containerID=1487649442 datapathPolicyRevision=9 desiredPolicyRevision=10 endpointID=490 identity=28673 ipv4=192.168.1.44 ipv6="fe80::f849:b6ff:fe16:be0c" k8sPodName=cilium-test/echo-same-node-bbb6b5ddb-jjfb7 originalDirectory=/var/run/cilium/state/490 subsys=endpoint
level=debug msg="removing directory" containerID=1487649442 datapathPolicyRevision=9 desiredPolicyRevision=10 directory=490_next_fail endpointID=490 identity=28673 ipv4=192.168.1.44 ipv6="fe80::f849:b6ff:fe16:be0c" k8sPodName=cilium-test/echo-same-node-bbb6b5ddb-jjfb7 subsys=endpoint
level=debug msg="removing directory" containerID=1487649442 datapathPolicyRevision=9 desiredPolicyRevision=10 directory=490_stale endpointID=490 identity=28673 ipv4=192.168.1.44 ipv6="fe80::f849:b6ff:fe16:be0c" k8sPodName=cilium-test/echo-same-node-bbb6b5ddb-jjfb7 subsys=endpoint
level=debug msg="Updating existing controller" name=sync-policymap-490 subsys=controller uuid=aace148c-4ce8-4139-8455-bea92d075051
level=debug msg="Controller update time: 25.999µs" name=sync-policymap-490 subsys=controller uuid=aace148c-4ce8-4139-8455-bea92d075051
level=debug msg="removing directory" containerID=1487649442 datapathPolicyRevision=10 desiredPolicyRevision=10 directory=490_next endpointID=490 identity=28673 ipv4=192.168.1.44 ipv6="fe80::f849:b6ff:fe16:be0c" k8sPodName=cilium-test/echo-same-node-bbb6b5ddb-jjfb7 subsys=endpoint
level=debug msg="Completed endpoint regeneration with no pending regeneration requests" code=OK containerID=1487649442 datapathPolicyRevision=10 desiredPolicyRevision=10 endpointID=490 endpointState=ready identity=28673 ipv4=192.168.1.44 ipv6="fe80::f849:b6ff:fe16:be0c" k8sPodName=cilium-test/echo-same-node-bbb6b5ddb-jjfb7 policyRevision=10 subsys=endpoint type=0
level=debug msg="Completed endpoint regeneration" bpfCompilation=0s bpfLoadProg=147.303554ms bpfWaitForELF="4.188µs" bpfWriteELF="366.025µs" containerID=1487649442 datapathPolicyRevision=10 desiredPolicyRevision=10 endpointID=490 identity=28673 ipv4=192.168.1.44 ipv6="fe80::f849:b6ff:fe16:be0c" k8sPodName=cilium-test/echo-same-node-bbb6b5ddb-jjfb7 mapSync="126.165µs" policyCalculation="142.026µs" prepareBuild="400.761µs" proxyConfiguration="6.572µs" proxyPolicyCalculation=251ns proxyWaitForAck="35.356µs" reason="policy rules added" subsys=endpoint total=149.794458ms waitingForCTClean=240ns waitingForLock="1.723µs"
level=debug msg="Controller func execution time: 164.479µs" name=sync-policymap-490 subsys=controller uuid=aace148c-4ce8-4139-8455-bea92d075051
level=debug msg="Successfully regenerated endpoint program (Reason: policy rules added)" code=OK containerID=1487649442 datapathPolicyRevision=10 desiredPolicyRevision=10 endpointID=490 endpointState=ready identity=28673 ipv4=192.168.1.44 ipv6="fe80::f849:b6ff:fe16:be0c" k8sPodName=cilium-test/echo-same-node-bbb6b5ddb-jjfb7 policyRevision=10 subsys=endpoint type=200
level=debug msg="EventQueue event processing statistics" eventConsumeOffQueueWaitTime="14.397µs" eventEnqueueWaitTime=761ns eventHandlingDuration=150.098659ms eventType="*endpoint.EndpointRegenerationEvent" name=endpoint-490 subsys=eventqueue
```

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by liuxu623**
Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #21184 

```release-note
Support L4 any port policy.
```

### CODE REVIEW

**Comment by julianwiedmann** [comment]
Hi, thanks for digging into this! Currently we intentionally exclude this test for Cilium. I just [fixed up](https://github.com/cilium/cilium/pull/21203) the corresponding documentation to make the reasoning easier to follow.

**Comment by joestringer** [comment]
@julianwiedmann I think that the reason it's excluded is because it's not supported, but if this patch adds support then we should be able to remove the exclusion?

Overall I think there's a few relevant questions to look into here, some from the Cilium side and some from the contributor side:
- Do we have any concerns around adding this additional check (eg perf impact) - @cilium/sig-datapath 
- If this is part of a standard k8s network policy conformance test, should that then override any concerns we have given that this is about complying to the standard implementation? If we're still concerned, do we want to implement some mitigations on the performance impact (eg conditionally enabling this based on whether this type of policy is set up) - @cilium/sig-datapath / @cilium/sig-agent 
- How is this PR being tested? - @liuxu623 , how should it be tested - @cilium/sig-datapath

**Comment by liuxu623** [comment]
> * How is this PR being tested? - @liuxu623 , how should it be tested
Yes, I have tested, we can use kubernetes e2e test, like
```
./_output/bin/e2e.test --ginkgo.focus='should enforce ingress policy allowing any port traffic to a server on a specific protocol' -disable-log-dump --provider=skeleton --kubeconfig=xxx
```

**Comment by julianwiedmann** [comment]
> @julianwiedmann I think that the reason it's excluded is because it's not supported, but if this patch adds support then we should be able to remove the exclusion?
> 

ack - haven't had time to fully digest https://github.com/cilium/cilium/issues/9207 yet, and why we didn't consider a fix such as this before.

**Comment by joestringer** [comment]
@liuxu623 I see, that makes sense. In that case, can you update `test/kubernetes-test.sh` to enable this test? Then we can validate in CI that this fixes the issue (and doesn't regress again).

**Comment by pchaigno** [comment]
> > @julianwiedmann I think that the reason it's excluded is because it's not supported, but if this patch adds support then we should be able to remove the exclusion?
> 
> ack - haven't had time to fully digest #9207 yet, and why we didn't consider a fix such as this before.

AFAIU, this pull request doesn't fix #9207.

**Comment by liuxu623** [comment]
I don't understand  what's related with `should enforce ingress policy allowing any port traffic to a server on a specific protocol` and #9207，I think it doesn't depend #9207.

File: test/kubernetes-test.sh [hunk 1]
```diff
@@ -103,12 +103,9 @@ ${HOME}/go/bin/kubetest --provider=local --test \
 #   - TL;DR Cilium does not allow to specify pod CIDRs as part of the policy
 #     because it conflicts with the pod's security identity.
 #   - More info at https://github.com/cilium/cilium/issues/9209
-# - should enforce ingress policy allowing any port traffic to a server on a specific protocol
-#   - Cilium does not distinguish between UDP and TCP
-#   - More info at https://github.com/cilium/cilium/issues/9207
```
Comment (pchaigno) [inline test/kubernetes-test.sh:108]: It seems this comment was incorrectly mentioning #9207. The test was skipped first in https://github.com/cilium/cilium/commit/d846652fdb59b168914f7e57d889a1edaa0b00a0#diff-5b7396a53a4522682b55bc3b4bd7433ac49313b38e8398547dc2c66fdf9e2a3f (by @aanm) and the link was later added in https://github.com/cilium/cilium/blame/master/test/kubernetes-test.sh#L106 (by @joestringer). As far as I understand, both the sentence and the link are incorrect as we're here talking about not being able to match on e.g. TCP without a port, whereas the issue is about not being able to differentiate between TCP and UDP in service resolution.

Hence, it looks fine to just remove the comment.

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
> Do we have any concerns around adding this additional check (eg perf impact) - @cilium/sig-datapath

My main concern is that it will increase complexity too much before it adds more path in our core logic. The end-to-end tests should cover that well enough.

File: test/kubernetes-test.sh (hunk 1 above)
Comment (aanm) [reply test/kubernetes-test.sh:108]: Yes that's a good point. I noticed that I've been mixing both issues with each other.

**Comment by julianwiedmann** [comment]
So while the test-case is only about ingress, this also changes the egress path. Do we need to keep `policy_sk_egress()` in sync?

**Comment by liuxu623** [comment]
> So while the test-case is only about ingress, this also changes the egress path. Do we need to keep `policy_sk_egress()` in sync?

It's a good idea, we also need to support egress any port policy.

File: bpf/lib/policy.h [hunk 2]
```diff
@@ -186,6 +186,17 @@ __policy_can_access(const void *map, struct __ctx_buff *ctx, __u32 local_id,
...
+		/* Check L4 any port policy */
+		key.dport = 0;
+		policy = map_lookup_elem(map, &key);
+		if (likely(policy)) {
+			account(ctx, policy);
+			*match_type = POLICY_MATCH_L4_ONLY;
+			if (unlikely(policy->deny))
+				return DROP_POLICY_DENY;
+			return CTX_ACT_OK;
+		}
```
Comment (pchaigno) [inline bpf/lib/policy.h:209]: This code will affect both ingress and egress, so the commit title is incorrect. The other, egress-specific code is for the sockops feature.

I think it's fine to squash both commits.

Comment (liuxu623) [reply bpf/lib/policy.h:209]: Thank you for your suggestion.

File: test/kubernetes-test.sh (hunk 1 above)
Comment (joestringer) [reply test/kubernetes-test.sh:108]: :thinking: The test looks to me like it configures a TCP-only service then ensures that UDP connectivity fails:

https://github.com/kubernetes/kubernetes/blob/2b203348fbe7d05dec9e913e0fb50045a2474425/test/e2e/network/netpol/network_policy.go#L883-L899

Comment (pchaigno) [reply test/kubernetes-test.sh:108]: To me it looks like it's creating a TCP-only *policy*; I don't see any mention of services.

**Comment by pchaigno** [comment]
@liuxu623 Did you push a change or just rebase? It's usually not necessary to rebase unless you're also pushing a change. After every rebase, we'll need to rerun the full end-to-end tests.

**Comment by liuxu623** [comment]
> @liuxu623 Did you push a change or just rebase? It's usually not necessary to rebase unless you're also pushing a change. After every rebase, we'll need to rerun the full end-to-end tests.

ok, I just rebase latest master branch.

**Review by nbusseneau — APPROVED** [review]

File: bpf/lib/policy.h [hunk 3]
```diff
@@ -186,6 +196,17 @@ __policy_can_access(const void *map, struct __ctx_buff *ctx, __u32 local_id,
...
+
+		/* Check L4 any port policy */
+		key.dport = 0;
+		policy = map_lookup_elem(map, &key);
+		if (likely(policy)) {
+			account(ctx, policy);
+			*match_type = POLICY_MATCH_L4_ONLY;
+			if (unlikely(policy->deny))
+				return DROP_POLICY_DENY;
+			return CTX_ACT_OK;
```
Comment (julianwiedmann) [inline bpf/lib/policy.h:208]: I'm still fuzzy on the L7 integration myself. But as this is a L4 policy, don't we need to handle that it's combined with a L7 policy and return `policy->proxy_port` here?

Comment (pchaigno) [reply bpf/lib/policy.h:208]: Ah, yes, that's a good point. Do we want to allow redirecting all TCP traffic to the proxy though?

**Review by pchaigno — CHANGES_REQUESTED** [review]
Blocking on Julian's comment above.

File: bpf/lib/policy.h (hunk 3 above)
Comment (liuxu623) [reply bpf/lib/policy.h:208]: `policy->proxy_port` is `0`, should return `d.port` here ?

Comment (pchaigno) [reply bpf/lib/policy.h:208]: Do you mean it's always 0? How did you check that?

Comment (liuxu623) [reply bpf/lib/policy.h:208]: I know why `policy->proxy_port` is always 0, because when use k8s NetworkPolicy, l7 rules is empty.
When use CiliumNetworkPolicy and port is 0 (it means all ports) we couldn't use l7 rules too.
https://github.com/cilium/cilium/blob/v1.12.1/pkg/policy/api/rule_validation.go#L390
So, in this case, we needn't consider l7 rules.

Comment (liuxu623) [reply bpf/lib/policy.h:208]:
```yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "rule1"
  namespace: "cilium-test"
spec:
  endpointSelector:
    matchLabels:
      kind: echo
  ingress:
  - toPorts:
    - ports:
      - port: "0"
        protocol: TCP
      rules:
        http:
        - method: "GET"
          path: "/"
```
level=warning msg="Unable to add CiliumNetworkPolicy" ciliumNetworkPolicyName=rule1 error="Invalid CiliumNetworkPolicy spec: L7 rules can not be used when a port is 0" k8sApiVersion= k8sNamespace=cilium-test subsys=k8s-watcher

Comment (pchaigno) [reply bpf/lib/policy.h:208]: Ok. Makes sense! Thanks for double checking!

**Review by pchaigno — APPROVED** [review]

**Review by julianwiedmann — APPROVED** [review]
