### PR TITLE
bpf/maps: cleanup deprecated cilium_policy_v1

### LINKED ISSUE #39115: stale records in endpoints that links to v1 cilium_policy
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.9 and lower than v1.17.0

### What happened?

After upgrading to 1.17 there are multiple stale records in endpoints that links to v1 cilium_policy

```
$ cilium bpf policy list
Endpoint ID: 11
Path: /sys/fs/bpf/tc/globals/cilium_policy_00011

Was impossible to retrieve label ID 590153: [GET /identity/{id}][404] getIdentityIdNotFound
Was impossible to retrieve label ID 590278: [GET /identity/{id}][404] getIdentityIdNotFound
Was impossible to retrieve label ID 590395: [GET /identity/{id}][404] getIdentityIdNotFound

...

Endpoint ID: 45
Path: /sys/fs/bpf/tc/globals/cilium_policy_v2_00045

POLICY   DIRECTION   LABELS (source:key[=value])                                                  PORT/PROTO   PROXY PORT   AUTH TYPE   BYTES         PACKETS    PREFIX
Deny     Egress      cidr:64:ff9b::/96                                                            ANY          NONE         disabled    0             0          0
                     reserved:world
```

v2 introduced in https://github.com/cilium/cilium/commit/a9ff8a7b0792ef466f3fb20d1b1bde34d34b245e

[Slack thread](https://cilium.slack.com/archives/C1MATJ5U5/p1744368563286239?thread_ts=1744368087.160049&cid=C1MATJ5U5)

### How can we reproduce the issue?

1. Install 1.16
2. Do upgrade to 1.17

### Cilium Version

1.17.x

### Kernel Version

6.6.37

### Kubernetes Version

v1.30.11

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by pasteley**
Fixes: #39115
Related PRs: #36361

```release-note
Added cleanup of deprecated cilium_policy_v1 maps
```

### CODE REVIEW

**Review by jrajahalme — APPROVED** [review]
LGTM :-)

File: pkg/datapath/maps/map_test.go [hunk 1]
```diff
@@ -199,3 +205,27 @@ func TestCollectStaleMapGarbage(t *testing.T) {
...
+		depricatedMaps := []string{
+			"cilium_proxy4",
+			"cilium_proxy6",
+			"cilium_policy_01234",
+		}
+		bwManager := newTestBWManager()
+		sweeper := NewMapSweeper(hivetest.Logger(t), testEPManager, bwManager, loadbalancer.DefaultConfig)
+
+		sweeper.RemoveDisabledMaps()
+		require.Equal(t, depricatedMaps, testEPManager.removedPaths)
```
Comment (jrajahalme) [inline pkg/datapath/maps/map_test.go:231]: This expectation is failing due to `testEPManager.removedPaths` having full paths:
```
    map_test.go:229: 
        	Error Trace:	/home/runner/work/cilium/cilium/pkg/datapath/maps/map_test.go:229
        	Error:      	Not equal: 
        	            	expected: []string{"cilium_proxy4", "cilium_proxy6", "cilium_policy_01234"}
        	            	actual  : []string{"/sys/fs/bpf/tc/globals/cilium_proxy4", "/sys/fs/bpf/tc/globals/cilium_proxy6", "/sys/fs/bpf/tc/globals/cilium_policy_01234"}
```

**Review by jrajahalme — CHANGES_REQUESTED** [review]

File: pkg/datapath/maps/map_test.go (hunk 1 above)
Comment (pasteley) [reply pkg/datapath/maps/map_test.go:231]: fxd: https://github.com/cilium/cilium/pull/39400/commits/7f86543e926a9f543ecf1fed4a93975d7a7e0406

**Comment by joestringer** [comment]
The BPF checks workflow is failing due to multiple sign offs. I would suggest when you rebase and squash the commits together, ensure that the entire commit message follows a standard form. An example is shown in step 5 of the contributor guide: https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request .

I'll trigger the testsuite.

**Review by jrajahalme — APPROVED** [review]
Thanks!

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
Thanks for the contribution @pasteley !
