### PR TITLE
rate: fix TestStressRateLimiter when run with race detector

### LINKED ISSUE #13508: api-limiter: TestAutoAdjust unit test fails consistently
Running `make unit-tests` in the standard Vagrant VM on my local machine consistently fails with the following test failing:

```
FAIL: api_limiter_test.go:96: ControllerSuite.TestAutoAdjust

api_limiter_test.go:128:
    // burst should not adjust this quickly
    c.Assert(a.limiter.Burst(), check.Equals, initialRateBurst)
... obtained int = 1
... expected int = 2
```

The failing test is at [this line](https://github.com/cilium/cilium/blob/master/pkg/rate/api_limiter_test.go#L128).

The test here looks potentially a little racy (there are a few `time.Sleep`s), and the code being tested looks to be both new and quite subtle.

@tgraf and @aanm it looks like you're currently working on this area of the codebase. Would you like me to investigate further? Do you need any further information?

### PR DESCRIPTION
**Pull request by tklauser**
This test is currently failing consistently when run under the race
detector. Similar to TestAllocateID in pkg/idpool, decrease the number
of parallel goroutines when running the test under the race detector.

Fixes #13508

### CODE REVIEW

File: pkg/rate/api_limiter_norace_test.go [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+	}, nil)
+
+	var (
+		sem                = semaphore.NewWeighted(100)
+		completed, retries int32
+	)
+
+	go func() {
+		for i := 0; i < 1000; i++ {
+			sem.Acquire(context.Background(), 1)
```
Comment (aanm) [inline pkg/rate/api_limiter_norace_test.go]: The reason I think it fails is because the number of parallel go routines with we running. There was a similar issue with `AllocatedID`: https://github.com/cilium/cilium/blob/060901444c152cd293744a4af6a5b393299dd05d/pkg/idpool/idpool_race_test.go#L23-L30

https://github.com/cilium/cilium/blob/060901444c152cd293744a4af6a5b393299dd05d/pkg/idpool/idpool_norace_test.go#L23-L25

Comment (tklauser) [reply pkg/rate/api_limiter_norace_test.go]: Thanks for the hint. I'll try adjusting the test accordingly and see if it helps.

**Comment by tklauser** [comment]
It seems we don't run the unit tests with race detector on PRs by default:

https://github.com/cilium/cilium/blob/2a27fdba92cb9589afcdf54de0ca926b7c092a98/.travis.yml#L14-L16

I've pushed a temporary commit enabling Travis CI race builds (a05525097a37ee25f3f3f5a94bdecdbf8c879f2e) and will drop it again once the build passed.

**Review by twpayne — APPROVED** [review]

**Comment by tklauser** [comment]
Travis CI race build failed due to different issues. I've verified this PR locally now using `go test -race -check.f StressRateLimiter -count 1000` and it passed. Dropped the temporary change to `.travis.yml`.

**Review by aanm — APPROVED** [review]

**Comment by tklauser** [comment]
Reviews are in, GH actions and Travis CI passed. Respective race unit tests have been verified locally. Marking as ready to merge.
