### PR TITLE
[CI] Don't overwrite minRequired in WaitforNPods

### LINKED ISSUE #7995: K8sServicesTest fail due to timeout
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/2865/

### PR DESCRIPTION
**Pull request by nebril**
If `minRequired` was set to 0, it was overwritten on the first pass of
`body` function (since it's in this function's closure) and if some pods
were being deleted during the test startup time, it could cause
`minRequired` to be higher than possible with test pods number.

Fixes: #7995

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8002)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Review by brb — COMMENTED** [review]
Maybe I'm missing something, but isn't the intention of `minRequired=0` is to determine the count during the first run? If yes, then this PR defeats its intention.

File: test/helpers/kubectl.go [hunk 1]
```diff
@@ -556,11 +556,15 @@ func (kub *Kubectl) WaitforNPods(namespace string, filter string, minRequired in
 			return false
 		}
 
+		var required int
```
Comment (raybejjani) [inline test/helpers/kubectl.go:560]: Could you update the function comment above?

**Review by raybejjani — CHANGES_REQUESTED** [review]
LGTM except for a comment change

**Comment by nebril** [comment]
@brb the first couple of runs can contain leftover pods being deleted from previous tests. This causes `minRequired` to be set to higher pod count than the test can provide.

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]

**Comment by nebril** [comment]
test-me-please

**Comment by raybejjani** [comment]
@brb One reason I'm preferring this PR over https://github.com/cilium/cilium/pull/7993/files is that it eventually accounts for deleted/deleting pods but also handles new pods showing up. It's not clear to me that this way of determining the pod count is correct to begin with. Ian's suggestion in https://github.com/cilium/cilium/pull/7993/files#r283611833 is probably the correct way to go, with variants for deployments, replicasets and (maybe) even parsing a pod manifest directly (although, really, we should just not be so lazy and put numbers in).

**Review by aanm — APPROVED** [review]

**Comment by tgraf** [comment]
I think it's fine to merge this right now but I agree that we should follow @ianvernon's approach as described in https://github.com/cilium/cilium/pull/7993/files#r283611833

**Comment by aanm** [comment]
marking this as backported needed since it is happening in 1.4
