### PR TITLE
policy: Make selectorcache callbacks lock-free

### LINKED ISSUE #16236: Unable to update ipcache map entry on pod add causing DNS resolving failure in the pods.
## Bug report

**General Information**

- Cilium version: 1.10.0.rc1
- Kernel version: `Linux ip-172-18-46-124 5.4.0-1045-aws #47-Ubuntu SMP Tue Apr 13 07:02:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use: Using EKS, with `Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`
- Generate and upload a system zip:
Too large to upload to github so created a google drive share. 

https://drive.google.com/file/d/1vL8W7cg6-CSmCmFZtWk3PDLc6og4skfQ/view?usp=sharing

**How to reproduce the issue**

Hey Guys, I am running cilium 1.10.0.rc1 with eks 1.18 with aws eni mode (withous chaining mode)

I am having this weird issue that both of the two pods below cannot resolve any dns / talk to coredns in the cluster. It keeps getting timeout somehow. This is the log in the cilium pod
```
level=warning msg="Unable to update ipcache map entry on pod add" error="ipcache entry for podIP 172.18.46.215: unable to overwrite source \"custom-resource\" with source \"k8s\"" hostIP=172.18.46.215 k8sNamespace=pelican k8sPodName=pelican-bf8c54f86-4zfgp podIP=172.18.46.215 podIPs="[{172.18.46.215}]" subsys=k8s-watcher
level=warning msg="Unable to update ipcache map entry on pod add" error="ipcache entry for podIP 172.18.59.200: unable to overwrite source \"custom-resource\" with source \"k8s\"" hostIP=172.18.59.200 k8sNamespace=sentry k8sPodName=sentry-sentry-redis-slave-0 podIP=172.18.59.200 podIPs="[{172.18.59.200}]" subsys=k8s-watcher
```

From what I can see that this cilium pod somehow has issue that the garbage collector hasn't been running for a day. When I checked the log above it's already 05/19 UTC time

```
2021-05-18T14:54:15.211318802Z level=info msg="FQDN garbage collector work deleted 6 name entries: sentry-kafka-2.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-0.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-1.sentry-kafka-headless.sentry.svc.cluster.local.,sts.amazonaws.com.,db-pelican.mysql.service.ap-southeast-2.consul.,sentry-sentry-redis-master-0.sentry-sentry-redis-headless.sentry.svc.cluster.local." controller=dns-garbage-collector-job subsys=daemon
2021-05-18T14:55:15.211917883Z level=info msg="FQDN garbage collector work deleted 6 name entries: sentry-kafka-0.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-1.sentry-kafka-headless.sentry.svc.cluster.local.,sts.amazonaws.com.,db-pelican.mysql.service.ap-southeast-2.consul.,sentry-sentry-redis-master-0.sentry-sentry-redis-headless.sentry.svc.cluster.local.,sentry-kafka-2.sentry-kafka-headless.sentry.svc.cluster.local." controller=dns-garbage-collector-job subsys=daemon
2021-05-18T14:56:15.213160212Z level=info msg="FQDN garbage collector work deleted 6 name entries: sts.amazonaws.com.,db-pelican.mysql.service.ap-southeast-2.consul.,sentry-sentry-redis-master-0.sentry-sentry-redis-headless.sentry.svc.cluster.local.,sentry-kafka-2.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-1.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-0.sentry-kafka-headless.sentry.svc.cluster.local." controller=dns-garbage-collector-job subsys=daemon
2021-05-18T14:57:15.214740217Z level=info msg="FQDN garbage collector work deleted 6 name entries: sentry-kafka-2.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-0.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-1.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-sentry-redis-master-0.sentry-sentry-redis-headless.sentry.svc.cluster.local.,sts.amazonaws.com.,db-pelican.mysql.service.ap-southeast-2.consul." controller=dns-garbage-collector-job subsys=daemon
2021-05-18T14:58:01.388798338Z level=warning msg="UpdateIdentities: Skipping Delete of a non-existing identity" identity=16777255 subsys=policy
2021-05-18T14:58:01.388819817Z level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
2021-05-18T14:58:01.393484089Z level=warning msg="UpdateIdentities: Skipping Delete of a non-existing identity" identity=16777228 subsys=policy
2021-05-18T14:58:02.389790661Z level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
2021-05-18T14:58:15.216149319Z level=info msg="FQDN garbage collector work deleted 7 name entries: sentry-kafka-2.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-0.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-1.sentry-kafka-headless.sentry.svc.cluster.local.,qlb.syd1.fln-dev.net.,sentry-sentry-redis-master-0.sentry-sentry-redis-headless.sentry.svc.cluster.local.,sts.amazonaws.com.,db-pelican.mysql.service.ap-southeast-2.consul." controller=dns-garbage-collector-job subsys=daemon
2021-05-18T14:59:15.216945537Z level=info msg="FQDN garbage collector work deleted 6 name entries: sentry-kafka-2.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-0.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-1.sentry-kafka-headless.sentry.svc.cluster.local.,sts.amazonaws.com.,db-pelican.mysql.service.ap-southeast-2.consul.,sentry-sentry-redis-master-0.sentry-sentry-redis-headless.sentry.svc.cluster.local." controller=dns-garbage-collector-job subsys=daemon
2021-05-18T15:00:15.218293017Z level=info msg="FQDN garbage collector work deleted 6 name entries: sts.amazonaws.com.,db-pelican.mysql.service.ap-southeast-2.consul.,sentry-sentry-redis-master-0.sentry-sentry-redis-headless.sentry.svc.cluster.local.,sentry-kafka-2.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-0.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-1.sentry-kafka-headless.sentry.svc.cluster.local." controller=dns-garbage-collector-job subsys=daemon
2021-05-18T15:01:15.219695212Z level=info msg="FQDN garbage collector work deleted 6 name entries: sentry-kafka-0.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-1.sentry-kafka-headless.sentry.svc.cluster.local.,sts.amazonaws.com.,db-pelican.mysql.service.ap-southeast-2.consul.,sentry-sentry-redis-master-0.sentry-sentry-redis-headless.sentry.svc.cluster.local.,sentry-kafka-2.sentry-kafka-headless.sentry.svc.cluster.local." controller=dns-garbage-collector-job subsys=daemon
2021-05-18T15:02:15.221210254Z level=info msg="FQDN garbage collector work deleted 6 name entries: sts.amazonaws.com.,db-pelican.mysql.service.ap-southeast-2.consul.,sentry-sentry-redis-master-0.sentry-sentry-redis-headless.sentry.svc.cluster.local.,sentry-kafka-2.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-0.sentry-kafka-headless.sentry.svc.cluster.local.,sentry-kafka-1.sentry-kafka-headless.sentry.svc.cluster.local." controller=dns-garbage-collector-job subsys=daemon
```

Cilium itself seems to be healthy on this node
```
$ kubectl exec -it cilium-lx849 -n kube-system -- cilium status
Defaulted container "cilium-agent" out of: cilium-agent, wait-for-node-init (init), clean-cilium-state (init)
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.18+ (v1.18.9-eks-d1db3c) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1beta1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Strict   [ens5 172.18.46.124 (Direct Routing)]
Cilium:                 Ok   1.10.0-rc1 (v1.10.0-rc1-efc15cd)
NodeMonitor:            Listening for events on 4 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok
IPAM:                   IPv4: 24/32 allocated,
BandwidthManager:       EDT with BPF   [ens5]
Host Routing:           Legacy
Masquerading:           Disabled
Controller Status:      109/109 healthy
Proxy Status:           OK, ip 172.18.46.202, 16 redirects active on ports 10000-20000
Hubble:                 Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 215.86   Metrics: Ok
Encryption:             Disabled
Cluster health:         10/10 reachable   (2021-05-19T04:14:37Z)

```

But I can see every time I do a dns lookup the cilium pod fails talking to coredns
172.18.55.216 is the coredns pod ip
```
$ kubectl exec -it cilium-lx849 -n kube-system -- cilium monitor | grep 172.18.46.215
Policy verdict log: flow 0xe5effeec local EP ID 1574, remote ID 38547, proto 17, egress, action redirect, match L3-L4, 172.18.46.215:57991 -> 172.18.55.216:53 udp
-> proxy flow 0xe5effeec identity 7374->unknown state new ifindex 0 orig-ip 0.0.0.0: 172.18.46.215:57991 -> 172.18.55.216:53 udp
-> proxy flow 0xe5effeec identity 7374->unknown state established ifindex 0 orig-ip 0.0.0.0: 172.18.46.215:57991 -> 172.18.55.216:53 udp
-> proxy flow 0xe5effeec identity 7374->unknown state established ifindex 0 orig-ip 0.0.0.0: 172.18.46.215:57991 -> 172.18.55.216:53 udp
-> proxy flow 0xe5effeec identity 7374->unknown state established ifindex 0 orig-ip 0.0.0.0: 172.18.46.215:57991 -> 172.18.55.216:53 udp
```
If I delete this cilium pod on this node, a new one spun up by the daemonset and everything seems to be working again, but this issue happens occasionally every couple of hours

### PR DESCRIPTION
**Pull request by jrajahalme**
Make IdentitySelectionUpdated() callbacks lock-free by queueing them
while still holding selectorcache lock (to keep FIFO order) and
calling from a goroutine not holding any locks. This prevents
deadlocks caused by the implementation of IdentitySelectionUpdated()
taking locks such as endpoint or selectorcache locks.

```release-note
Potential deadlock in pod identity updates has been fixed.
```

Fixes https://github.com/cilium/cilium/issues/16236

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Review by twpayne — COMMENTED** [review]
Is there a good reason to use a `sync.Cond` and a `sync.Mutex` instead of channels here? It's generally easier to reason about code using channels.

**Comment by jrajahalme** [comment]
> Is there a good reason to use a `sync.Cond` and a `sync.Mutex` instead of channels here? It's generally easier to reason about code using channels.

Did consider using channels, but they seem unsuitable for the task. Channel can block (when full) which would effectively transfer the held locks from one goroutine to another, and this is what we want to avoid here. We use channels with "large" buffers to avoid this somewhere else in the code base (event queue I recall), but if those channels ever become full there be deadlocks.

In essence if a buffered channel "fixes" a locking problem (e.g. deadlock) then it still can happen when buffer becomes full. IMO we should try to make all buffered channels of length 1 and see what happens. Or even unbuffered to make this even more apparent?

**Comment by jrajahalme** [comment]
test-me-please

File: pkg/policy/selectorcache.go [hunk 1]
```diff
@@ -197,6 +209,10 @@ type SelectorCache struct {
 	selectors map[string]identitySelector
 
 	localIdentityNotifier identityNotifier
+
+	userCond  *sync.Cond
+	userMutex lock.Mutex
+	userNotes []userNotification
```
Comment (aanm) [inline pkg/policy/selectorcache.go]: It would be nice to have some comments about these fields.

File: pkg/policy/selectorcache.go [hunk 2]
```diff
@@ -223,12 +239,46 @@ func (sc *SelectorCache) GetModel() models.SelectorCache {
 	return selCacheMdl
 }
 
+func (sc *SelectorCache) handleUserNotifications() {
+	for {
+		sc.userMutex.Lock()
+		for len(sc.userNotes) == 0 {
+			sc.userCond.Wait()
```
Comment (aanm) [inline pkg/policy/selectorcache.go:250]: How come this doesn't deadlock? We are effectively holding `sc.userMutex.Lock()` so `queueUserNotification` would never be able to handle notifications because it won't be able to get a lock of `sc.userMutex`. I assume this could be fixed by [1]

File: pkg/policy/selectorcache.go [hunk 3]
```diff
@@ -223,12 +239,46 @@ func (sc *SelectorCache) GetModel() models.SelectorCache {
...
+		sc.userMutex.Unlock()
+
+		for _, n := range notifications {
+			n.user.IdentitySelectionUpdated(n.selector, n.added, n.deleted)
+		}
+	}
+}
+
+func (sc *SelectorCache) queueUserNotification(user CachedSelectionUser, selector CachedSelector, added, deleted []identity.NumericIdentity) {
+	sc.userMutex.Lock()
```
Comment (aanm) [inline pkg/policy/selectorcache.go:265]: [1] Replace the mutex with a 2-slot semaphore. Then call `sc.userCond.Signal()` until we are able to acquire `sc.semaphore.Acquire(2)` in this line, which means that `handleUserNotifications` will only re-acquire the semaphore until this function has released it because `handleUserNotifications` will only do a `sc.semaphore.Acquire(1)`.

**Review by aanm — CHANGES_REQUESTED** [review]

File: pkg/policy/selectorcache.go (hunk 2 above)
Comment (jrajahalme) [reply pkg/policy/selectorcache.go:250]: From the docs:

> Wait atomically unlocks c.L and suspends execution of the calling goroutine. After later resuming execution, Wait locks c.L before returning. Unlike in other systems, Wait cannot return unless awoken by Broadcast or Signal.

Because c.L is not locked when Wait first resumes, the caller typically cannot assume that the condition is true when Wait returns. Instead, the caller should Wait in a loop:

`userCond` is initialized as:
```
	sc.userCond = sync.NewCond(&sc.userMutex)
```
so `Wait()` will unlock `userMutex` and locks it again before returning. `userMutex` must be held to read `userNotes`.

File: pkg/policy/selectorcache.go (hunk 3 above)
Comment (jrajahalme) [reply pkg/policy/selectorcache.go:265]: IMO this is not necessary and would be more complex.

File: pkg/policy/selectorcache.go (hunk 1 above)
Comment (jrajahalme) [reply pkg/policy/selectorcache.go]: Added :-)

**Comment by jrajahalme** [comment]
test-me-please

File: pkg/policy/selectorcache.go (hunk 2 above)
Comment (aanm) [reply pkg/policy/selectorcache.go:250]: ahh I forgot about that minor detail, see how comments are nice? :smile: 
>// userMutex protects userNotes and is linked to userCond

**Review by aanm — APPROVED** [review]

**Comment by joestringer** [comment]
#16769 reverts this change, so I am removing the needs-backport/1.8 label. To address the original issue on v1.8, we would need a fresh PR proposal.
