### PR TITLE
hubble: Never fail with ErrInvalidRead

### LINKED ISSUE #17036: hubble observe fails with "requested data has been overwritten and is no longer available"
cilium version: v1.10.3

i'm hitting this error fairly consistently on nodes with moderate traffic:
```
% kubectl exec -it -n kube-system ds/cilium -- hubble observe --all
requested data has been overwritten and is no longer available
command terminated with exit code 1
```
ref: there is a draft PR to re-implement the ring buffer: https://github.com/cilium/cilium/pull/14304

### PR DESCRIPTION
**Pull request by michi-covalent**
Currently GetFlows() fails with the following error when a position in
the ring buffer being read by Ring.read() has been overwritten:

    requested data has been overwritten and is no longer available

This turned out to be impractical as it makes it difficult to read all
the flows in the ring buffer (e.g.. hubble observe --all). GetFlows()
would fail if Hubble observes a single flow between the reader rewinding
to the oldest position and retrieving the entry.

This patch modifies Ring.read() so that GetFlows() returns LostEvent
instead of stopping with an error. The caller of GetFlows() can then
decide how to handle LostEvent.

Note that this makes the behavior of Ring.read() consistent with that
of Ring.readFrom() used in the follow mode. It generates LostEvent and
continues following instead of failing with ErrInvalidRead.

Fixes: #17036

Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>

### CODE REVIEW

**Comment by michi-covalent** [comment]
in addition to unit tests, manually validated the fix with `hubble observe --all --debug`:
```
# hubble observe --all --debug | head
time="2021-08-03T23:49:59Z" level=debug msg="Sending GetFlows request" request="number:18446744073709551615"
unknown response type: &{LostEvents:source:HUBBLE_RING_BUFFER  num_events_lost:1}
Aug  3 23:47:12.074: default/pod-to-a-9dc6d768c-rc7nc:49527 <- kube-system/kube-dns-6c7b8dc9f9-x962b:53 to-endpoint FORWARDED (UDP)
Aug  3 23:47:12.074: default/pod-to-a-9dc6d768c-rc7nc:34082 -> default/echo-a-56f9849b6b-jlbpr:8080 to-stack FORWARDED (TCP Flags: SYN)
Aug  3 23:47:12.074: default/pod-to-a-9dc6d768c-rc7nc:34082 -> default/echo-a-56f9849b6b-jlbpr:8080 to-endpoint FORWARDED (TCP Flags: SYN)
Aug  3 23:47:12.074: default/pod-to-a-9dc6d768c-rc7nc:34082 <- default/echo-a-56f9849b6b-jlbpr:8080 to-stack FORWARDED (TCP Flags: SYN, ACK)
Aug  3 23:47:12.074: default/pod-to-a-9dc6d768c-rc7nc:34082 <- default/echo-a-56f9849b6b-jlbpr:8080 to-endpoint FORWARDED (TCP Flags: SYN, ACK)
Aug  3 23:47:12.074: default/pod-to-a-9dc6d768c-rc7nc:34082 -> default/echo-a-56f9849b6b-jlbpr:8080 to-stack FORWARDED (TCP Flags: ACK)
Aug  3 23:47:12.074: default/pod-to-a-9dc6d768c-rc7nc:34082 -> default/echo-a-56f9849b6b-jlbpr:8080 to-endpoint FORWARDED (TCP Flags: ACK)
Aug  3 23:47:12.074: default/pod-to-a-9dc6d768c-rc7nc:34082 -> default/echo-a-56f9849b6b-jlbpr:8080 to-stack FORWARDED (TCP Flags: ACK, PSH)
Aug  3 23:47:12.074: default/pod-to-a-9dc6d768c-rc7nc:34082 -> default/echo-a-56f9849b6b-jlbpr:8080 to-endpoint FORWARDED (TCP Flags: ACK, PSH)
```

File: pkg/hubble/observer/local_observer.go [hunk 1]
```diff
@@ -606,7 +602,7 @@ func newRingReader(ring *container.Ring, req genericRequest, whitelist, blacklis
 	// correct index, then create a new reader that starts from there
 	for i := ring.Len(); i > 0; i, idx = i-1, idx-1 {
 		e, err := reader.Previous()
-		if errors.Is(err, container.ErrInvalidRead) {
```
Comment (gandro) [inline pkg/hubble/observer/local_observer.go:609]: I think this is not correct: Invalid reads are only one source of lost events - the ring buffer will contain lost events for other reasons too [1], in which case we have _not_ reached the end of the ring buffer and need to continue rewinding.

We need to check for  `LostEventSource_HUBBLE_RING_BUFFER` here if we are relying on LostEvents to detect the end of the buffer. Or, alternatively, we could keep `ErrInvalidRead` and just translate replace `errors.New("requested data has been overwritten and is no longer available")` into a `LostEvent`.

[1] e.g. `PERF_EVENT_RING_BUFFER`, which means we dropped events in the kernel perf buffer before the reached Hubble. These events not very common, but they are stored in the ring buffer to indicate "some data is missing here due to userspace not keeping up with the kernel". If we observe them, we still want to continue rewinding.

**Review by gandro — CHANGES_REQUESTED** [review]
Thanks for doing this! I left an inline comment

File: pkg/hubble/observer/local_observer.go (hunk 1 above)
Comment (michi-covalent) [reply pkg/hubble/observer/local_observer.go:609]: fixed!

**Review by gandro — APPROVED** [review]
Nice work! Should we mark this for backport too?

**Review by glibsm — APPROVED** [review]

**Comment by michi-covalent** [comment]
test-me-please

**Comment by michi-covalent** [comment]
restarting these 2:

aks: https://github.com/cilium/cilium/actions/runs/1101961941
eks: https://github.com/cilium/cilium/actions/runs/1101961955
```
Error : .github#L1
An unexpected error has occurred and we've been automatically notified. Errors are sometimes temporary, so please try again.
```

**Comment by michi-covalent** [comment]
ci-aks

**Comment by michi-covalent** [comment]
ci-eks

**Comment by michi-covalent** [comment]
https://github.com/cilium/cilium/actions/runs/1102872491

legitimate failures 😐 
```
Error: Connectivity test failed: 2 tests failed
📋 Test Report
❌ 2/9 tests failed (2/81 actions), 0 tests skipped, 0 scenarios skipped:
Test [client-ingress]:
  ❌ client-ingress/client-to-client/ping-1: cilium-test/client2-666976c95b-fpfxz (10.240.0.42) -> cilium-test/client2-666976c95b-fpfxz (10.240.0.42:0)
Test [client-egress]:
  ❌ client-egress/pod-to-pod/curl-0: cilium-test/client2-666976c95b-fpfxz (10.240.0.42) -> cilium-test/echo-other-node-697d5d69b7-jk4kp (10.240.0.49:8080)
```

**Comment by gandro** [comment]
Looking at the failure, it is not related to the PR, it's a connectivity problem, not a problem with flow visibility (i.e. Hubble). Given that more and more users are hitting the error that this PR is addressing, I'll mark this ready-to-merge.
