### PR TITLE
fix: fallback to ipv6 node address usage for endpoint kvstore sync

### LINKED ISSUE #37791: cilium-agent cannot map IP to identity if node has no IPv4 address
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.1 and lower than v1.18.0

### What happened?

When running in an IPv6 environment, using native routing, cilium-agent still requires a Node to have an IPv4 address on its manifest, even though this does not appear to be necessary.

### How can we reproduce the issue?

1.  Deploy Helm with routing=native, ipv4.enabled=false
2. Create a Node with an IPv6 address(es) but no IPv4 address:

```
apiVersion: v1
kind: Node
...
status:
  addresses:
  - address: "2001:0db8:85a3:0000:0000:8a2e:0370:7334"
    type: InternalIP
```

3. Start a Pod. Cilium will fail to create it
4. Add a dud IPv4 address to the Node:

```
apiVersion: v1
kind: Node
...
status:
  addresses:
  - address: "2001:0db8:85a3:0000:0000:8a2e:0370:7334"
    type: InternalIP
  - address: "203.0.113.23"
    type: InternalIP
```

5. Pod will now be able to be scheduled (NB: Due to a separate issue, #37790, cilium-agent needs to be restarted after step 4)

When in native routing mode, this IPv4 address does not appear to actually be used anywhere, it just needs to exist. In our cluster, we tested this theory by adding the exact same IPv4 address to every Node manifest. This was an IPv4 address that was not actually assigned to any ports in the host net, and wasn't routable. Despite this, cilium is able to route pod-to-pod, pod-to-service, outside-to-service, and correctly enforce NetworkPolicies.

It seems that, in the case that native routing is being used at least, it would be acceptable to drop this requirement?

The relevant code is here: https://github.com/cilium/cilium/blob/ff7d6771e95fcb62a866c814741aa8e8be8915ec/pkg/endpoint/policy.go#L983C3-L983C5

### Cilium Version

1.17.1

### Kernel Version

6.6.2

### Kubernetes Version

v1.29.8

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by pasteley**
This PR addresses root cause of #37791
Cilium-agent endpoint synchronization with kvstore fails in IPv6-only environments when nodes don't have IPv4 addresses. The `runIPIdentitySync()` function was hardcoded to use `node.GetIPv4()` for the host IP regardless of the endpoint's address family or node configuration. Now we call `runIPIdentitySync()` per enabled address family and checking node IP before creating sync controller.

Fixes: #37791

```release-note
Ensure that kvstore synchronisation can work in IPv6-only environments.
```

### CODE REVIEW

**Comment by bimmlerd** [comment]
> Fixes: https://github.com/cilium/cilium/issues/37791

That issue has been closed with a different PR; can you elaborate why this would be necessary in addition?

**Comment by pasteley** [comment]
> > Fixes: https://github.com/cilium/cilium/issues/37791

> That issue has been closed with a different PR; can you elaborate why this would be necessary in addition?

@bimmlerd 
PR #38938 addressed the deadlock issue specifically, this one make endpoint sync work properly in IPv6-only cilium deployment with kvstore enabled, which was the underlying cause of the original problem. Would you like me to open a separate issue for this, which would be duplicate the original one?

File: pkg/node/address.go [hunk 1]
```diff
@@ -226,13 +226,18 @@ func GetInternalIPv6(logger *slog.Logger) net.IP {
 	return clone(n.GetNodeInternalIPv6())
 }
 
+// GetNodeIP returns node IP, prioritizing IPv4 if enabled in config
```
Comment (bimmlerd) [inline pkg/node/address.go]: Eh, let's not add more to `pkg/node`. The package global methods are all sort of deprecated, but obviously still in massive use. But let's not add more, I think you can get away with just using `GetCiliumEndpointNodeIP` (this is semantically the right thing anyway; the KVstore entries are CEP equivalents) and then parsing the IP.

**Review by bimmlerd — CHANGES_REQUESTED** [review]
Direction seems sane - if you fix the implementation note we can get this green

Thrown in an inital release note, just so we have something - feel free to improve.

File: pkg/node/address.go (hunk 1 above)
Comment (pasteley) [reply pkg/node/address.go]: `GetCiliumEndpointNodeIP()` returns String representation of `net.IP`
We would need to make redundant parsing back to `net.IP` with `net.ParseIP()` for each address family of each endpoint.
Or do you see another way to do this?

**Comment by pasteley** [comment]
@bimmlerd  
I suppose, since it's definitely a bug, we would need to backport it to 1.17?

Also, do You think we should create a separate issue to add a test pipeline for the mentioned IPv6-only network + KVStore setup?

File: pkg/node/address.go (hunk 1 above)
Comment (bimmlerd) [reply pkg/node/address.go]: `net.IP` to `netip.Addr` is also a conversion 🤷
I know it's a bit inefficient but we can work this out once we're getting rid of the `pkg/node` globals.

**Comment by bimmlerd** [comment]
> I suppose, since it's definitely a bug, we would need to backport it to 1.17?

Basically if it wasn't a bug it couldn't go in at the moment since we're in feature freeze for 1.18; but yeah I think we can mark this for backport to 1.17 still.

**Comment by bimmlerd** [comment]
> separate issue to add a test pipeline for the mentioned IPv6-only network + KVStore

I don't think creating an issue is necessary - but feel free to create a PR to improve the testing, sure!

**Comment by pasteley** [comment]
@bimmlerd Can we merge it?

**Comment by bimmlerd** [comment]
> @bimmlerd Can we merge it?

No - neither I nor @tommyp1ckles have given an approval, both are needed to merge.

File: pkg/endpoint/policy.go [hunk 2]
```diff
@@ -1014,6 +1015,15 @@ func (e *Endpoint) runIPIdentitySync(endpointIP netip.Addr) {
 		addressFamily = "IPv6"
 	}
 
+	logger := e.getLogger()
+
+	// Don't create controller if we can't get node IP
+	hostIP, ok := netipx.FromStdIP(net.ParseIP(node.GetCiliumEndpointNodeIP(logger)))
```
Comment (bimmlerd) [inline pkg/endpoint/policy.go]: Please use https://pkg.go.dev/net/netip#ParseAddr directly instead of parsing into a `net.IP` and then converting it into an `netip.Addr`.

Comment (pasteley) [reply pkg/endpoint/policy.go]: Oh, right, missed that part, thank you

**Review by bimmlerd — APPROVED** [review]

**Comment by joestringer** [comment]
Could you rebase the PR against `main`? We triaged this PR during the community meeting and it looks like the failures are because the PR is not up-to-date against the `main` branch testing code.

File: pkg/endpoint/policy.go [hunk 3]
```diff
@@ -1010,6 +1009,15 @@ func (e *Endpoint) runIPIdentitySync(endpointIP netip.Addr) {
 		addressFamily = "IPv6"
 	}
 
+	logger := e.getLogger()
+
+	// Don't create controller if we can't get node IP
+	hostIP, err := netip.ParseAddr(node.GetCiliumEndpointNodeIP(logger))
```
Comment (joestringer) [inline pkg/endpoint/policy.go]: The other consequence of this change is that it means the IP is declared once on the stack and used for the lifetime of the agent. Is it possible for this IP to change at some point later? If yes this could cause a staleness bug where for this specific controller the agent doesn't properly adapt to changes in the node IP.

I think if the goal here is fallback to IPv6, then the code change should probably switch the existing change in the existing location to this line and not move the check outside the controller.

Comment (pasteley) [reply pkg/endpoint/policy.go]: Can't argue with that, fixed

**Review by joestringer — APPROVED** [review]
LGTM

**Comment by joestringer** [comment]
@cilium/endpoint still looking for your review ( cc @tommyp1ckles I dropped you as there was no response for some time, hoping GitHub would rebalance into the codeowner but GitHub didn't rebalance :sweat_smile: )

**Review by tklauser — APPROVED** [review]
Thanks!
