### PR TITLE
policy: Fix selectorcache locking issue

### LINKED ISSUE #9292: deadlock can occur if AllocatorEventChan buffer is full and attempts to allocate local CIDR identities are in flight
A user reported that `cilium endpoint list` fails with a context deadline exceeded.

When looking into the agent logs, there are a few instances of:

```
cilium.io/agent: "endpoint regeneration failed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1037 error="context canceled" identity=4 ipv4=10.0.124.181 ipv6= k8sPodName=/ subsys=endpoint
```

From the gops stack traces:

```
 goroutine 658 [chan receive, 15 minutes]:
main.(*Daemon).regenerateRestoredEndpoints.func1(0xc00000c3c0, 0xc000176780, 0xc002d0dce0)
    /go/src/github.com/cilium/cilium/daemon/state.go:365 +0x5b9
created by main.(*Daemon).regenerateRestoredEndpoints
    /go/src/github.com/cilium/cilium/daemon/state.go:261 +0x61f

[...]

goroutine 843 [semacquire, 15 minutes]:
sync.runtime_SemacquireMutex(0xc0001e5198, 0x7ffff80000000000)
    /usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc0001e5194)
    /usr/local/go/src/sync/mutex.go:134 +0x109
sync.(*RWMutex).Lock(0xc0001e5194)
    /usr/local/go/src/sync/rwmutex.go:93 +0x2d
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).LockAlive(0xc0001e5180, 0x0, 0x0)
    /go/src/github.com/cilium/cilium/pkg/endpoint/lock.go:21 +0x3a
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).RegenerateIfAlive(0xc0001e5180, 0xc0021b0c60, 0xc002b3bc20)
    /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:419 +0x43
github.com/cilium/cilium/pkg/endpointmanager.RegenerateAllEndpoints.func1(0xc0021b0c60, 0xc002b24630, 0xc0001e5180)
    /go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:434 +0x35
created by github.com/cilium/cilium/pkg/endpointmanager.RegenerateAllEndpoints
    /go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:433 +0x207
```

From the cilium-agent logs I can see that the user has imported a few network policies (with FQDN) which could have triggered the latter regeneration.

Worth noting that a previous instance of the cilium-agent has been killed by OOM killer most likely due to the FQDN cache size increase.

Cilium: v1.6.1 + some custom patches.

### PR DESCRIPTION
**Pull request by joestringer**
When adding a new FQDN selector to the selector cache, the selector
cache lock would be held while registering into the DNS subsystem for
identity updates. This could then trigger allocation of CIDR identities,
leading to a call to UpdateIdentities() to notify all other selectors in
the cache about the new identity. This would then attempt to lock the
selector cache lock which was held at the beginning of this process,
leading to deadlock.

Fix the issue by releasing the selectorcache lock for the duration of
registering (and potentially triggering allocations), then after that
process is done, lock again and see if another goroutine has
successfully created the FQDN. If so, we can unregister from the proxy
again and use the existing selector; otherwise we can go ahead and
configure the selector in the selector cache and return it.

Thanks to Ian Vernon and Thomas Graf for their assistance digging to the
bottom of this issue.

Fixes: #9292

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9296)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Hit #9297. I suspect it's a flake, since there's no policy; the test is related to services with BPF nodeport; and only one variation of the test failed (DR, not vxlan).

**Comment by joestringer** [comment]
test-me-please

File: pkg/policy/selectorcache.go [hunk 1]
```diff
@@ -590,9 +595,27 @@ func (sc *SelectorCache) AddFQDNSelector(user CachedSelectionUser, fqdnSelec api
...
+
+	sc.mutex.Lock()
+	defer sc.mutex.Unlock()
+
+	// Check whether the selectorCache was updated while 'newFQDNSel' was
+	// being registered without the 'sc.mutex'. If so, use it. Otherwise
+	// we can use the one we just created/configured above.
+	if sel := sc.lookupSelectorLocked(key); sel != nil {
+		// Unregister, discard our local copy.
+		newFQDNSel.dnsProxy.UnregisterForIdentityUpdates(newFQDNSel.selector)
```
Comment (ianvernon) [inline pkg/policy/selectorcache.go]: Remove this line - we should only unregister if there are no more users, and if there is an entry in the `SelectorCache` for this FQDNSelector, it will have users.

Comment (joestringer) [reply pkg/policy/selectorcache.go]: Thanks for the review, the `RegisterForIdentityUpdates()` function has a different set of side-effects than I thought and this forced some rethinking of the way we patch this up. I've fixed this up in the latest version.

**Comment by joestringer** [comment]
test-me-please

File: pkg/policy/selectorcache.go [hunk 2]
```diff
@@ -548,15 +548,20 @@ func (sc *SelectorCache) updateFQDNSelector(fqdnSelec api.FQDNSelector, identiti
...
 	key := fqdnSelec.String()
+
+	// If the selector already exists, use it.
+	sc.mutex.Lock()
 	fqdnSel, exists := sc.selectors[key]
 	if exists {
+		sc.mutex.Unlock()
 		return fqdnSel, fqdnSel.addUser(user)
 	}
+	sc.mutex.Unlock()
```
Comment (jrajahalme) [inline pkg/policy/selectorcache.go:561]: I would move the `Unlock` to happen right before `if` rather than doing it on two different code paths.

File: pkg/policy/selectorcache.go [hunk 3]
```diff
@@ -567,15 +572,18 @@ func (sc *SelectorCache) AddFQDNSelector(user CachedSelectionUser, fqdnSelec api
 		dnsProxy: sc.localIdentityNotifier,
 	}
 
-	// Add the initial user
-	newFQDNSel.users[user] = struct{}{}
-
-	// Make the FQDN subsystem aware of this selector.
+	// Make the FQDN subsystem aware of this selector and fetch identities
+	// that the FQDN subsystem are aware of.
```
Comment (jrajahalme) [inline pkg/policy/selectorcache.go]: "is aware of"

**Review by jrajahalme — APPROVED** [review]
Small nits only, good work :-)

File: pkg/policy/selectorcache.go [hunk 4]
```diff
@@ -548,15 +548,20 @@ func (sc *SelectorCache) updateFQDNSelector(fqdnSelec api.FQDNSelector, identiti
...
-	sc.mutex.Lock()
-	defer sc.mutex.Unlock()
-
 	key := fqdnSelec.String()
+
+	// If the selector already exists, use it.
+	sc.mutex.Lock()
 	fqdnSel, exists := sc.selectors[key]
 	if exists {
+		sc.mutex.Unlock()
```
Comment (ianvernon) [inline pkg/policy/selectorcache.go:558]: Hm, should the `Unlock` be deferred here? Otherwise if multiple calls to `addUser` occur for the same `fqdnSel` at the same time, there would be concurrent access of the `users` map.

**Review by ianvernon — COMMENTED** [review]
One final comment - everything else looks good.

File: pkg/policy/selectorcache.go (hunk 4 above)
Comment (joestringer) [reply pkg/policy/selectorcache.go:558]: Hmm yeah, looks like the selector users are also managed by the same selectorcache lock. I'll need to fix that up.

I'm not a big fan of the defer, because we will unlock then lock again, but this concern can be easily resolved one way or another.

File: pkg/policy/selectorcache.go (hunk 2 above)
Comment (joestringer) [reply pkg/policy/selectorcache.go:561]: I ended up leaving this in place since the `addUser()` should likely occur while still holding the lock.

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]
🚀
