### PR TITLE
policy: Fix transient policy deny during agent restart

### LINKED ISSUE #15878: Drop happening during Cilium-agent restart
## Bug report

We are experiencing cilium_drop packet while restarting cilium-agent on the node, if we do not restart it no drop appears. 

## Config setup 

Cilium version: 1.9.5 (version 1.7.4 was also generating drop metric and increase in latency)
Kernel: 5.4.0-1037-aws #39~18.04.1-Ubuntu SMP Fri Jan 15 02:48:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Os: Ubuntu
CNI: aws-cni 1.7.9
Kubernetes: v1.12.10
Instance type: m5.4xlarge

## Cilium config: 

Using dedicated etcd cluster + AWS cni chaining + proxy layer 7 disabled + kube-proxy-replacement:  "disabled" 

```
---
# Source: cilium/templates/cilium-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-config
  namespace: $namespace
data:
$kvstoreConfig

  # This etcd-config contains the etcd endpoints of your cluster. If you use
  # TLS please make sure you follow the tutorial in https://cilium.link/etcd-config
$etcdConfig # Using dedicated etcd cluster

  # Identity allocation mode selects how identities are shared between cilium
  # nodes by setting how they are stored. The options are "crd" or "kvstore".
  # - "crd" stores identities in kubernetes as CRDs (custom resource definition).
  #   These can be queried with:
  #     kubectl get ciliumid
  # - "kvstore" stores identities in a kvstore, etcd or consul, that is
  #   configured below. Cilium versions before 1.6 supported only the kvstore
  #   backend. Upgrades from these older cilium versions should continue using
  #   the kvstore by commenting out the identity-allocation-mode below, or
  #   setting it to "kvstore".
  identity-allocation-mode: ${identityAllocationMode}
  cilium-endpoint-gc-interval: "5m0s"

  # If you want to run cilium in debug mode change this value to true
  debug: "false"
  # The agent can be put into the following three policy enforcement modes
  # default, always and never.
  # https://docs.cilium.io/en/latest/policy/intro/#policy-enforcement-modes
  enable-policy: "default"
  # If you want metrics enabled in all of your Cilium agents, set the port for
  # which the Cilium agents will have their metrics exposed.
  # This option deprecates the "prometheus-serve-addr" in the
  # "cilium-metrics-config" ConfigMap
  # NOTE that this will open the port on ALL nodes where Cilium pods are
  # scheduled.
  prometheus-serve-addr: ":9091"
  # Port to expose Envoy metrics (e.g. "9095"). Envoy metrics listener will be disabled if this
  # field is not set.
  proxy-prometheus-port: "9094"
  # If you want metrics enabled in cilium-operator, set the port for
  # which the Cilium Operator will have their metrics exposed.
  # NOTE that this will open the port on the nodes where Cilium operator pod
  # is scheduled.
  operator-prometheus-serve-addr: ":9092"
  enable-metrics: "true"

  # Enable IPv4 addressing. If enabled, all endpoints are allocated an IPv4
  # address.
  enable-ipv4: "true"

  # Enable IPv6 addressing. If enabled, all endpoints are allocated an IPv6
  # address.
  enable-ipv6: "false"
  # Users who wish to specify their own custom CNI configuration file must set
  # custom-cni-conf to "true", otherwise Cilium may overwrite the configuration.
  custom-cni-conf: "false"
  enable-bpf-clock-probe: "true"
  # If you want cilium monitor to aggregate tracing for packets, set this level
  # to "low", "medium", or "maximum". The higher the level, the less packets
  # that will be seen in monitor output.
  monitor-aggregation: medium

  # The monitor aggregation interval governs the typical time between monitor
  # notification events for each allowed connection.
  #
  # Only effective when monitor aggregation is set to "medium" or higher.
  monitor-aggregation-interval: 5s

  # The monitor aggregation flags determine which TCP flags which, upon the
  # first observation, cause monitor notifications to be generated.
  #
  # Only effective when monitor aggregation is set to "medium" or higher.
  monitor-aggregation-flags: all
  # Specifies the ratio (0.0-1.0) of total system memory to use for dynamic
  # sizing of the TCP CT, non-TCP CT, NAT and policy BPF maps.
  bpf-map-dynamic-size-ratio: "0.0025"
  # bpf-policy-map-max specifies the maximum number of entries in endpoint
  # policy map (per endpoint)
  bpf-policy-map-max: "16384"
  # bpf-lb-map-max specifies the maximum number of entries in bpf lb service,
  # backend and affinity maps.
  bpf-lb-map-max: "65536"
  # Pre-allocation of map entries allows per-packet latency to be reduced, at
  # the expense of up-front memory allocation for the entries in the maps. The
  # default value below will minimize memory usage in the default installation;
  # users who are sensitive to latency may consider setting this to "true".
  #
  # This option was introduced in Cilium 1.4. Cilium 1.3 and earlier ignore
  # this option and behave as though it is set to "true".
  #
  # If this value is modified, then during the next Cilium startup the restore
  # of existing endpoints and tracking of ongoing connections may be disrupted.
  # As a result, reply packets may be dropped and the load-balancing decisions
  # for established connections may change.
  #
  # If this option is set to "false" during an upgrade from 1.3 or earlier to
  # 1.4 or later, then it may cause one-time disruptions during the upgrade.
  preallocate-bpf-maps: "false"

  # Regular expression matching compatible Istio sidecar istio-proxy
  # container image names
  sidecar-istio-proxy-image: "cilium/istio_proxy"

  # Name of the cluster. Only relevant when building a mesh of clusters.
  cluster-name: $region.$environment
  # Unique ID of the cluster. Must be unique across all conneted clusters and
  # in the range of 1 and 255. Only relevant when building a mesh of clusters.
  cluster-id: ""

  # Encapsulation mode for communication between nodes
  # Possible values:
  #   - disabled
  #   - vxlan (default)
  #   - geneve
  tunnel: disabled
  # Enables L7 proxy for L7 policy enforcement and visibility
  enable-l7-proxy: "false"

  # wait-bpf-mount makes init container wait until bpf filesystem is mounted
  wait-bpf-mount: "false"
  # Enable chaining with another CNI plugin
  #
  # Supported modes:
  #  - none
  #  - aws-cni
  #  - flannel
  #  - portmap (Enables HostPort support for Cilium)
  cni-chaining-mode: aws-cni
  # Disable the PodCIDR route to the cilium_host interface as it is not
  # required. While chaining, it is the responsibility of the underlying plugin
  # to enable routing.
  enable-local-node-route: "false"

  masquerade: "false"
  enable-bpf-masquerade: "false"

  enable-xt-socket-fallback: "true"
  install-iptables-rules: "true"

  auto-direct-node-routes: "false"
  enable-bandwidth-manager: "false"
  enable-local-redirect-policy: "false"
  enable-host-firewall: "true"
  # List of devices used to attach bpf_host.o (implements BPF NodePort,
  # host-firewall and BPF masquerading)
  devices: "ens5"
  kube-proxy-replacement:  "disabled"
  enable-health-check-nodeport: "true"
  node-port-bind-protection: "true"
  enable-auto-protect-node-port-range: "true"
  enable-session-affinity: "false"
  # Disable health checking, when chaining mode is not set to portmap or none
  enable-endpoint-health-checking: "false"
  enable-health-checking: "true"
  enable-well-known-identities: "false"
  enable-remote-node-identity: "true"
  labels: "!app.kubernetes.io !io.cilium.k8s.namespace.labels k8s:io.cilium.k8s.namespace.labels.team k8s:io.cilium.k8s.namespace.labels.network-policy/namespace-prefix k8s:io.cilium.k8s.policy.cluster"
  operator-api-serve-addr: "127.0.0.1:9234"
  # Enable Hubble gRPC service.
  enable-hubble: "true"
  # UNIX domain socket for Hubble server to listen to.
  hubble-socket-path:  "/var/run/cilium/hubble.sock"
  # Address to expose Hubble metrics (e.g. ":7070"). Metrics server will be disabled if this
  # field is not set.
  hubble-metrics-server: ":9093"
  # A space separated list of metrics to enable. See [0] for available metrics.
  #
  # https://github.com/cilium/hubble/blob/master/Documentation/metrics.md
  hubble-metrics:
    dns:sourceContext=namespace;destinationContext=namespace
    drop:sourceContext=namespace;destinationContext=namespace
    flow:sourceContext=namespace;destinationContext=namespace
    http:sourceContext=namespace;destinationContext=namespace
    icmp:sourceContext=namespace;destinationContext=namespace
    tcp:sourceContext=namespace;destinationContext=namespace
  # An additional address for Hubble server to listen to (e.g. ":4244").
  hubble-listen-address: ":4244"
  hubble-disable-tls: "false"
  hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
  hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
  hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
  ipam: "cluster-pool"
  cluster-pool-ipv4-cidr: "192.168.96.0/19"
  cluster-pool-ipv4-mask-size: "30"
  disable-cnp-status-updates: "true"
  native-routing-cidr: "192.168.96.0/19"
```

## Test setup 

A single load injector (gatling) in the "source-namespace" sends requests to service IP(cluster ip) reaching 6 replicas in the "target-namespace" (golang echo server). 
Another 600 namespaces are created with pause container to create 600 identities as cilium is configured to create identity via namespace label only. 
Load is generated for 10 min with 1000 TPS.
 
Cilium Network policies are applied on both namespaces (source and target).

```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cilium-stubbed-nft-network-policy
spec:
   # allows everything (endpoints, nodes, host) to
  endpointSelector: {}
  egress:
    - toEntities:
        - cluster
    - toCIDRSet:
        - cidr: 0.0.0.0/0
          except:
            - 172.21.20.0/22
```
The test deletes the oldest cilium-agent every 2 min.  Deleting the cilium-agent running on the load-injector or target nodes causes packet drops, with egress/ingress denied reason as shown in the grafana dashboards below.
We expected there to be no drops during a cilium agent restart.
If we do not restart cilium-agent we do not see any drops.
The injector latency increases but requests are not failing most likely due to TCP retries.

## Run with cilium-agent restart only 

Screenshot 2021-04-26 at 15 48 34

```
 kubectl --context $context -n cilium-agent-traffic-target-stubbed-nft-0 get pods -o wide
NAME                    READY   STATUS    RESTARTS   AGE    IP               NODE                                          NOMINATED NODE
echo-56b6b6d545-86wmw   1/1     Running   0          4m1s   100.69.39.2      ip-10-50-104-67.eu-west-1.compute.internal    <none>
echo-56b6b6d545-d55pn   1/1     Running   0          4m1s   100.67.7.130     ip-10-50-99-211.eu-west-1.compute.internal    <none>
echo-56b6b6d545-lb5r9   1/1     Running   0          4m1s   100.69.135.175   ip-10-50-104-95.eu-west-1.compute.internal    <none>
echo-56b6b6d545-qcn6b   1/1     Running   0          4m1s   100.68.204.169   ip-10-50-103-97.eu-west-1.compute.internal    <none>
echo-56b6b6d545-shfmz   1/1     Running   0          4m1s   100.67.82.117    ip-10-50-96-125.eu-west-1.compute.internal    <none>
echo-56b6b6d545-zm7vm   1/1     Running   0          4m1s   100.68.247.195   ip-10-50-103-117.eu-west-1.compute.internal   <none>
```

## Run without cilium-agent restart 

Screenshot 2021-04-26 at 16 38 57

### PR DESCRIPTION
**Pull request by jaffcheng**
Please see commit msg

Fixes: #15878

```release-note
Fix transient policy deny during agent restart
```

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]
Thanks for the fixes!

How did you find and validate this? Was it enough to restart Cilium with chatty pods and policies in place? If so, why did we miss those issues in CI?

**Comment by pchaigno** [comment]
test-me-please

**Comment by jaffcheng** [comment]
> How did you find and validate this? Was it enough to restart Cilium with chatty pods and policies in place? If so, why did we miss those issues in CI?

Hi @pchaigno, my test setup to reproduce is like the following: enforce ingress policy (that allows access from clientpod) on serverpod on `node1`, and create a chatty clientpod (`nc -zw1 $serverip $port` every 5ms) on another node, then restart cilium-agent on `node1`.
With the above setup, the policy flush issue should be easy to reproduce, and the probability to reproduce the ipcache missing issue might depend on the number of entries in ipcache map(over 55000 in the above setup). I haven't read the CI code, but I guess it might depend on the scale of CI setup and how chatty the client is, hope this helps.

**Comment by pchaigno** [comment]
ci-awscni

**Comment by pchaigno** [comment]
ci-aks

**Comment by pchaigno** [comment]
ci-eks

**Comment by pchaigno** [comment]
ci-gke

**Review by christarazi — APPROVED** [review]
:rocket:

**Comment by pchaigno** [comment]
The only failing test is on EKS with IPsec and L7 policies; it therefore corresponds to https://github.com/cilium/cilium/issues/17139, a known broken test. Review requests are covered. I'm marking ready to merge.

File: pkg/endpoint/bpf.go [hunk 1]
```diff
@@ -813,16 +813,11 @@ func (e *Endpoint) runPreCompilationSteps(regenContext *regenerationContext) (he
...
-		if err != nil {
-			return false, err
-		}
 
-		// Also reset the in-memory state of the realized state as the
-		// BPF map content is guaranteed to be empty right now.
+		// Reset the in-memory state of the realized state, the realized
+		// state and BPF map entries will be filled with desired policy in
+		// the following e.syncPolicyMap, and stale entries in BPF map will
+		// be removed by the subsequent syncPolicyMapController.
```
Comment (joestringer) [inline pkg/endpoint/bpf.go]: I agree that flushing the policymap like we did previously here doesn't sound like the right approach since it can cause transient policy drops.

That said I don't think it's a good idea to rely on `syncPolicyMapController` to implement the policy correctly. It only runs once a minute, and in an ideal world it would never exist at all. We have talked about changing logic like the `syncPolicyMapController` to warn any time that it makes a change to the policy, because this implies that the core policy logic is not properly implementing the policy in the first place. Note that any discrepancy between the desired policy state and the current map entries represents a potential gap in enforcement (either denying traffic that should be allowed, or worse, allowing traffic that should no longer be allowed). If the policy is changed while Cilium is restarting, then we cannot immediately respond to those changes. But we would like to minimize that timeframe.

Skipping the delete and then reinitializing the in-memory view of the current contents of the BPF map (and reinitializing pressure metrics) just puts this logic out-of-sync with the actual current state in the datapath. The whole point of "realizedState" is that it is tightly bound to the current state of the active BPF map, but without having to do expensive syscall operations to perform lookups and checks.

Here's an alternative proposal: Set some flag like `e.ForcePolicyMapSync` so that when the next `e.syncPolicyMap()` runs, it will sweep the map and delete all entries that do not have corresponding entries in the `desiredPolicyMap`. We can't do this step here, because the policy didn't get calculated yet; it's calculated in `e.regeneratePolicy()` below. But the actual `e.syncPolicyMap()` occurs even later. We could do it there, and then the  core policymap sync logic would be correct.

File: pkg/endpoint/restore.go [hunk 2]
```diff
@@ -298,10 +298,13 @@ func (e *Endpoint) restoreIdentity() error {
 			return ErrNotAlive
 		case <-gotInitialGlobalIdentities:
 		}
+	}
```
Comment (joestringer) [inline pkg/endpoint/restore.go:301]: Second patch LGTM.

I'm curious, do you have an easy way to reproduce these connectivity issues during agent restart? We have some tests like the Upgrade tests that attempt to do this, but it sounds like your testing is able to more reliably pick up on issues like this. If we can integrate such tests into the Cilium CI, we can hopefully catch these bugs in future before they get merged into the tree.

**Review by joestringer — CHANGES_REQUESTED** [review]
Nice find, thanks for the submission!

I've got some concerns about the first patch. I have proposed an alternative solution that I think should be able to achieve the goal of fixing the transient policy deny during agent restart but without deferring the policy synchronization too late.

File: pkg/endpoint/restore.go (hunk 2 above)
Comment (joestringer) [reply pkg/endpoint/restore.go:301]: I see there was already discussion on this above in the PR, I missed that initially :)

We do not need to resolve this testing question to merge the fix, but it would be a nice follow-up to prevent future regressions.

File: pkg/endpoint/bpf.go (hunk 1 above)
Comment (joestringer) [reply pkg/endpoint/bpf.go]: Thinking a bit more about this... Another way to look at it is that upon restore, the 'realizedState' of the policymap for the endpoint is out-of-sync with the datapath, because it is encoded in process memory, and the process just started up again. So a different way to ensure that the policymap synchronization occurs correctly would be from this code to read the BPF policymap and populate the 'realizedState' with the current state of the BPF map. Then the 'realized' state will be accurate and be bound closely with the BPF implementation.

Then we don't need any additional flag, next time the `e.syncPolicyMap()` runs, it will automatically deal with the discrepancies between the 'desired' and 'realized' state, and flush out any entries that don't match the latest policy.

**Review by joestringer — APPROVED** [review]
Looks good, thanks.

**Comment by joestringer** [comment]
test-me-please

**Comment by rewiko** [comment]
https://github.com/cilium/cilium/issues/15878#issuecomment-897444123  @yorg1st @chaosbox  should be able to do it next week. 
But ideally, cilium pipeline should have a regression test :smiley:

**Comment by joestringer** [comment]
I did some (very brief) triage of the failing tests. If we click through the "Details" links and scan through, we find:

Kind: 
* https://github.com/cilium/cilium/runs/3309030987?check_suite_focus=true
  * :x: to-entities-world/pod-to-world/http-to-jenkins-cilium-1: cilium-test/client2-666976c95b-t5lgs (10.244.1.107) -> jenkins-cilium-io-http (jenkins.cilium.io:80)

AKS:
* https://github.com/cilium/cilium/runs/3313537647?check_suite_focus=true
  * :x: to-entities-world/pod-to-world/http-to-cilium-io-0: cilium-test/client2-666976c95b-fltfr (10.240.0.51) -> cilium-io-http (cilium.io:80)

EKS:
* https://github.com/cilium/cilium/runs/3313559788?check_suite_focus=true
  * :x: client-egress-l7/pod-to-pod/curl-3: cilium-test/client2-666976c95b-lbhg4 (192.168.172.63) -> cilium-test/echo-same-node-7967996674-lcjpz (192.168.63.2:8080)
  :x: echo-ingress-l7/pod-to-pod/curl-3: cilium-test/client2-666976c95b-lbhg4 (192.168.172.63) -> cilium-test/echo-same-node-7967996674-lcjpz (192.168.63.2:8080)

However, I would not expect this PR to have an effect on the tests. This PR adjusts the "endpoint restore" logic which is run when Cilium restarts with active workloads. As far as I know, the tests never restart Cilium and will only start pods after Cilium started and stop them before it shuts down. So I don't think they're related to the code being changed.

I have opened a thread in Slack #testing channel to see whether anyone knows anything about such failures.

I didn't yet search the GitHub issues to see whether there are similar reports; that would be another good next step, try to correlate with other reports and see whether there was a regression introduced into the tree recently.

**Comment by jaffcheng** [comment]
Thanks for the investigation! Rebased

**Comment by pchaigno** [comment]
test-me-please

**Comment by jaffcheng** [comment]
> test-me-please
> 
> Job 'Cilium-PR-K8s-1.16-net-next' failed and has not been observed before, so may be related to your PR:
> 
> Click to show.
> ### Test Name
> ```
> K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with direct routing Tests LoadBalancer Connectivity to endpoint via LB
> ```
> 
> ### Failure Output
> ```
> FAIL: Can not connect to service "http://192.168.1.146" from outside cluster (1/10)
> ```
> 
> If it is a flake, comment `/mlh new-flake Cilium-PR-K8s-1.16-net-next` so I can create a new GitHub issue to track it.

I guess this is https://github.com/cilium/cilium/issues/16399 ?

**Comment by pchaigno** [comment]
> I guess this is #16399 ?

Yes. So only failing test is a known flake and review requests are covered. Marking ready to merge.

**Comment by rewiko** [comment]
Nice :sun_with_face: , will it be backported to 1.9 or only 1.10 ?

**Comment by pchaigno** [comment]
We'll backport to both.

**Comment by aditighag** [comment]
1.9 backport for this commit isn't straightforward, see this thread - https://github.com/cilium/cilium/pull/17328#discussion_r703175928.

**Comment by rewiko** [comment]
That's what @yorg1st told me when he was trying to deploy on our cluster with the fix. 

Up to you but it's probably safer to backport only for 1.10.
