### PR TITLE
Fix GetResources function in xds.Cache

### LINKED ISSUE #36553: xds cache returns all resources ignoring input urlType
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.4 and lower than v1.17.0

### What happened?

xds cache has method `GetResources` takes urlType, and resourceNames as an input. When resourcesNames list is empty the function returns all resources in the cache ignoring input urlType. The function should return all resources with given urlType instead.

### How can we reproduce the issue?

Can be reproduced in unit test. 

### Cilium Version

all versions

### Kernel Version

N/A

### Kubernetes Version

all versions

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kl52752**
xds cache has method GetResources takes urlType, and resourceNames as an input. 
When resourcesNames list is empty the function returns all resources in the cache 
ignoring input urlType. The function should return all resources with given urlType instead.

Fixes: #36553

### CODE REVIEW

**Comment by bowei** [comment]
LGTM -- can you wrap the commit comment text to 80 columns?

File: pkg/envoy/xds/cache.go [hunk 1]
```diff
@@ -208,16 +208,19 @@ func (c *Cache) GetResources(typeURL string, lastVersion uint64, nodeIP string,
...
+	// Return all resources of given typeURL.
 	// TODO: return nil if no changes since the last version?
 	if len(resourceNames) == 0 {
 		res.ResourceNames = make([]string, 0, len(c.resources))
 		res.Resources = make([]proto.Message, 0, len(c.resources))
-		cacheLog.Debugf("no resource names requested, returning all %d resources", len(c.resources))
 		for k, v := range c.resources {
+			if k.typeURL != typeURL {
+				continue
+			}
```
Comment (pchaigno) [inline pkg/envoy/xds/cache.go:219]: What's the user impact of this bug if any? We'll need to understand that to set the proper `release-note` label and write the release note text (in the PR template).

Comment (kl52752) [reply pkg/envoy/xds/cache.go:219]: returned result of the function will change. Previously the function returned all resources in the cache. After the fix it will return only resources of given typeURL.

Comment (pchaigno) [reply pkg/envoy/xds/cache.go:219]: I understand that aspect, but users don't see the return values of functions, they see changes in behavior. So how will the behavior of Cilium change for users? Or maybe it won't? Basically, how would you describe the impact of this fix to a cluster operator?

Comment (kl52752) [reply pkg/envoy/xds/cache.go:219]: I see. This PR change the way xDS Server is handling DiscoveryRequest in ADS.  

When  [DiscoveryRequests](https://github.com/envoyproxy/envoy/blob/b87da3fa9f008d87ab02df53840c5246f1ba6209/api/envoy/service/discovery/v3/discovery.proto#L47) is send wit ADS and  [ResourceName](https://github.com/envoyproxy/envoy/blob/b87da3fa9f008d87ab02df53840c5246f1ba6209/api/envoy/service/discovery/v3/discovery.proto#L68)  list in the request  is empty  then the Server will return all resources of type set in [TypeURL](https://github.com/envoyproxy/envoy/blob/b87da3fa9f008d87ab02df53840c5246f1ba6209/api/envoy/service/discovery/v3/discovery.proto#L83) field. Before the fix the xDS Server returned all resources.

Comment (pchaigno) [reply pkg/envoy/xds/cache.go:219]: Hm. Cilium users don't managed any of those resources directly, do they? Is there maybe an impact on Cilium's L7 policies or on the L7 load balancing (Ingress or GatewayAPI)?

Comment (kl52752) [reply pkg/envoy/xds/cache.go:219]: In NetworkPolicies this function is used only in ``GetNetworkPolicies` which is marked as test only. And all tests passed

Comment (pchaigno) [reply pkg/envoy/xds/cache.go:219]: Ok, so sounds like there's no user-visible impact :+1:

**Review by jrajahalme — APPROVED** [review]

**Comment by jrajahalme** [comment]
@kl52752 rebase needed to pick up a fix for the Envoy version check failures in CI upgrade tests.

**Comment by kl52752** [comment]
> @kl52752 rebase needed to pick up a fix for the Envoy version check failures in CI upgrade tests.

done
