### PR TITLE
While recovering services, don't skip if one of the service recovery fails.

### LINKED ISSUE #18371: service: Improve restoration of services from lbmap
Currently, the service restoration from lbmap (the entrypoint is `(pkg/service/service.go.*Service) RestoreServices(...)`) bails immediately upon hitting an error. Instead of bailing, we should log those errors and continue to restore next entries.

This could help to reduce a number of connections which would be interrupted due to svc/backend ID changes which happens when the restoration fails.

### PR DESCRIPTION
**Pull request by chowmean**
While recovering a service doesn't return an error instead try to recover the remaining service. 
Fixes: [#18371](https://github.com/cilium/cilium/issues/18371)

```release-note
In the case of recovering the services, cilium will not fail directly on the first service recovery error but will try to recover other services. 
```

### CODE REVIEW

**Comment by chowmean** [comment]
@pchaigno please have a look at this PR. Have to close the earlier one due to wrong commits.

**Review by kkourt — CHANGES_REQUESTED** [review]
Hi, thanks for the patch!

Can you please add some additional details in the commit message? Rewording or even copy-pasting the text from the issue would be fine. The goal here would be to have a brief description of what the problem that this patch tries to solve is and how it manages it.

Thanks again!

**Comment by chowmean** [comment]
Added. Please have a look.

File: pkg/service/service.go [hunk 1]
```diff
@@ -851,8 +851,10 @@ func (s *Service) restoreBackendsLocked() error {
 			logfields.L3n4Addr:  b.L3n4Addr.String(),
 		}).Debug("Restoring backend")
 		if err := RestoreBackendID(b.L3n4Addr, b.ID); err != nil {
-			return fmt.Errorf("Unable to restore backend ID %d for %q: %s",
-				b.ID, b.L3n4Addr, err)
+			log.WithError(err).WithField(logfields.BackendID, b.ID).
+				Warnf("Unable to restore backend ID %d for %q: %s",
+					b.ID, b.L3n4Addr, err)
+			continue
```
Comment (kkourt) [inline pkg/service/service.go:860]: How about putting all arguments as fields and removing them from the message?

```
log.WithFields(logrus.Fields{
                logfields.BackendID: b.ID,
		logfields.L3n4Addr: b.L3n4Addr,
	}).Warn("Unable to restore backend")
```

File: pkg/service/service.go [hunk 2]
```diff
@@ -935,7 +937,8 @@ func (s *Service) restoreServicesLocked() error {
 				backends[b.String()] = b.ID
 			}
 			if err := s.lbmap.UpsertMaglevLookupTable(uint16(newSVC.frontend.ID), backends, ipv6); err != nil {
-				return err
+				scopedLog.WithError(err).Warning("Unable to Inserts into the Maglev BPF map.")
```
Comment (kkourt) [inline pkg/service/service.go]: How about:

> scopedLog.WithError(err).Warning("Unable to upsert into the Maglev BPF map.")

?

**Review by kkourt — APPROVED** [review]
Thanks! some more nits from my side, but otherwise LGTM.

**Review by brb — CHANGES_REQUESTED** [review]
My comments are the same as what @kkourt said. Also, it would be good to log a count for how many backends failed to be restored (same it is done for the services).

File: pkg/service/service.go (hunk 2 above)
Comment (chowmean) [reply pkg/service/service.go]: Changed it to this

File: pkg/service/service.go (hunk 1 above)
Comment (chowmean) [reply pkg/service/service.go:860]: done

**Comment by chowmean** [comment]
Added changes to log the information about restored and failed backends just like services. @brb @kkourt Please take a look. Thanks!

**Comment by kkourt** [comment]
> Added changes to log the information about restored and failed backends just like services. @brb @kkourt Please take a look. Thanks!

Great! Many thanks! Can you please squash the two commits into one?

**Comment by chowmean** [comment]
Squashed the commits

**Review by kkourt — APPROVED** [review]

File: pkg/service/service.go [hunk 3]
```diff
@@ -851,14 +852,23 @@ func (s *Service) restoreBackendsLocked() error {
 			logfields.L3n4Addr:  b.L3n4Addr.String(),
 		}).Debug("Restoring backend")
 		if err := RestoreBackendID(b.L3n4Addr, b.ID); err != nil {
-			return fmt.Errorf("Unable to restore backend ID %d for %q: %s",
-				b.ID, b.L3n4Addr, err)
+			log.WithFields(logrus.Fields{
+				logfields.BackendID: b.ID,
+				logfields.L3n4Addr:  b.L3n4Addr,
+			}).Warn("Unable to restore backend")
```
Comment (brb) [inline pkg/service/service.go]: The error needs to be logged.

**Review by brb — CHANGES_REQUESTED** [review]

File: pkg/service/service.go (hunk 3 above)
Comment (chowmean) [reply pkg/service/service.go]: Made the change. Please have a look.

**Comment by chowmean** [comment]
@brb please have a look at the changes. Thanks!

File: pkg/service/service.go [hunk 4]
```diff
@@ -851,14 +852,23 @@ func (s *Service) restoreBackendsLocked() error {
 			logfields.L3n4Addr:  b.L3n4Addr.String(),
 		}).Debug("Restoring backend")
 		if err := RestoreBackendID(b.L3n4Addr, b.ID); err != nil {
-			return fmt.Errorf("Unable to restore backend ID %d for %q: %s",
-				b.ID, b.L3n4Addr, err)
+			log.WithFields(logrus.Fields{
+				logfields.BackendID: b.ID,
+				logfields.L3n4Addr:  b.L3n4Addr,
+			}).Error("Unable to restore backend: %s", err)
```
Comment (brb) [inline pkg/service/service.go]: Please use `WithError()` instead.

File: pkg/service/service.go [hunk 5]
```diff
@@ -851,14 +852,23 @@ func (s *Service) restoreBackendsLocked() error {
...
+			continue
 		}
-
+		restored++
 		hash := b.L3n4Addr.Hash()
 		s.backendByHash[hash] = b
 	}
 
+	log.WithFields(logrus.Fields{
+		"restored": restored,
```
Comment (brb) [inline pkg/service/service.go]: Please use `pkg/logging/logfields/` for `"restored"` and `"failed"`. If there is no suitable logfield, then you can introduce it.

**Review by brb — CHANGES_REQUESTED** [review]

File: pkg/service/service.go (hunk 5 above)
Comment (chowmean) [reply pkg/service/service.go]: Added the new variable please take look.

File: pkg/service/service.go (hunk 4 above)
Comment (chowmean) [reply pkg/service/service.go]: made the changes.

**Review by brb — CHANGES_REQUESTED** [review]
Thanks! One more nit before we can merge it - could you squash both commits into one?

**Comment by chowmean** [comment]
@brb squashed the commits please take a look.

**Comment by brb** [comment]
@chowmean The commit msg needs to be fixed, see https://github.com/cilium/cilium/runs/4880993387?check_suite_focus=true. See https://cbea.ms/git-commit/#limit-50 and https://cbea.ms/git-commit/#wrap-72.

**Comment by chowmean** [comment]
@brb made the changes. Sorry for so many iterations.

**Comment by brb** [comment]
Thanks. Could you make the commit message lines no longer than 72 chars?

**Comment by chowmean** [comment]
Done

File: pkg/service/service.go [hunk 6]
```diff
@@ -851,14 +852,23 @@ func (s *Service) restoreBackendsLocked() error {
 			logfields.L3n4Addr:  b.L3n4Addr.String(),
 		}).Debug("Restoring backend")
 		if err := RestoreBackendID(b.L3n4Addr, b.ID); err != nil {
-			return fmt.Errorf("Unable to restore backend ID %d for %q: %s",
-				b.ID, b.L3n4Addr, err)
+			log.WithError(err).WithFields(logrus.Fields{
+				logfields.BackendID: b.ID,
+				logfields.L3n4Addr:  b.L3n4Addr,
+			}).Error("Unable to restore backend")
```
Comment (brb) [inline pkg/service/service.go]: The last nit: let's use `Warning` instead of `Error` here.

Comment (chowmean) [reply pkg/service/service.go]: Made the change

**Review by nathanjsweet — APPROVED** [review]

**Comment by chowmean** [comment]
@brb please have a look into this. Thanks!

**Review by brb — APPROVED** [review]
Thanks!

**Comment by chowmean** [comment]
hi @brb do I need to make any other changes here. What will be the next steps?

**Comment by brb** [comment]
The CI failure seems to be unrelated. Marking as ready-to-merge.

**Comment by aditighag** [comment]
Nominating this PR for backports to older branches as it can alleviate backend leaks. @jaredlevina has created this backport PR on 1.11 - https://github.com/cilium/cilium/pull/23922.
