### PR TITLE
loadbalancer: Flatten the backend representation

### LINKED ISSUE #44310: Cilium v1.19.0 excessive memory usage
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.19.0 and lower than v1.20.0

### What happened?

After upgrading from v1.18.6 to v1.19.0 we noticed Cilium-agent was using an excessive amount of memory, sometimes so much that kubelet would be OOMkilled - killing the node's ability to recover. 

Datadog metrics from Cilium:

Image

Reverting back to v1.18.6 resolved the memory pressure.

I followed the guide here to investigate and took some pprof snapshots: https://docs.cilium.io/en/latest/contributing/development/debugging/#cpu-profiling-and-memory-leaks

Here is the pprof output after I ran `kubectl exec -it -n kube-system cilium-tvtg5 -- cilium-bugtool --get-pprof --pprof-trace-seconds 10`

[cilium-bugtool-20260211-221005.093+0000-UTC-4259347162.zip](https://github.com/user-attachments/files/25246070/cilium-bugtool-20260211-221005.093%2B0000-UTC-4259347162.zip)

### How can we reproduce the issue?

Cilium helm values:
```
cilium:
  socketLB:
    hostNamespaceOnly: true
  extraEnv:
    - name: MALLOC_ARENA_MAX
      value: "1"
  k8sServicePort: 443
  localRedirectPolicy: true
  enableIPv4Masquerade: true
  egressMasqueradeInterfaces: "eth0 primary"
  extraArgs:
    - "--api-rate-limit"
    - "endpoint-create=rate-limit:5/s,rate-burst:40,parallel-requests:40,log:true,endpoint-delete=rate-burst:40,parallel-requests:40,log:true" # 10x base rate limits, see https://docs.cilium.io/en/stable/configuration/api-rate-limiting/
    - "--enable-stale-cilium-endpoint-cleanup=false" # Disable Stale Cilium Endpoint Cleanup to solve pods with missing IPs or CiliumEndpoints after cilium restarts
  resources:
    requests:
      cpu: 250m
      memory: 128Mi
  tls:
    # Disable secretsNamespace & secretSync
    readSecretsOnlyFromSecretsNamespace: false
    secretsNamespace:
      create: false
    secretSync:
      enabled: false

  scheduling:
    mode: kube-scheduler

  cni:
    # Defaults to true.  Setting to false avoids removal of CNI configuration
    # files during upgrades in order to ensure nodes do not go unmanageable.
    uninstall: false

  logOptions:
    format: json-ts

  operator:
    nodeSelector:
      role.node.kubernetes.io/critical-addon: "true"
    tolerations:
      - operator: Exists
    priorityClassName: system-cluster-critical
    podDisruptionBudget:
      enabled: true
    prometheus:
      enabled: true

  kubeProxyReplacement: true

# enable metrics
  prometheus:
    enabled: true

  # workaround for cilium mem leak in l2 neighbor discovery error handling in 1.16.0-1.16.1+
  l2NeighDiscovery:
    enabled: false

# perf settings for high pod-churn clusters
  ipam:
    ciliumNodeUpdateRate: 5s # Ref https://github.com/cilium/cilium/pull/23017
    operator:
      externalAPILimitBurstSize: 100
      externalAPILimitQPS: 10.0
  k8sClientRateLimit:
    burst: 100
    qps: 20
  ciliumEndpointSlice:
    enabled: true

  bpf:
    policyMapMax: 65536 # limited to 16 bits https://github.com/cilium/cilium/issues/27866
    mapDynamicSizeRatio: 0.005 # Ref https://docs.cilium.io/en/stable/network/ebpf/maps/

  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%

  envoy:
    enabled: true
    resources:
      requests:
        cpu: 250m
        memory: 128Mi
  loadBalancer:
    l7:
      backend: envoy

### Cilium Version

v1.19.0

### Kernel Version

`6.12.58-82.121.amzn2023.x86_64` (AWS AL2023)

### Kubernetes Version

`v1.34.2-eks-ecaa3a6`

### Regression

v1.18.6

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by joamaki**
This flattens the `loadbalancer.Backend` by storing "backend instance" per row in the backend table instead of having a map of `BackendParams` inside the `Backend` object.

Before:
```
pkg/loadbalancer/writer/ > go test . -bench . -benchmem
goos: linux
goarch: arm64
pkg: github.com/cilium/cilium/pkg/loadbalancer/writer
Benchmark_UpsertServiceAndFrontends_100-6                   3687            311606 ns/op            320918 objects/sec    326431 B/op       4639 allocs/op
Benchmark_UpsertServiceAndFrontends_100_Unchanged-6        14514             81891 ns/op           1221133 objects/sec     50012 B/op       1151 allocs/op
Benchmark_UpsertServiceAndFrontends_1-6                   141879              8088 ns/op            123640 objects/sec     13087 B/op         89 allocs/op
BenchmarkInsertBackend-6                                    3007            387712 ns/op            257923 objects/sec    511640 B/op       6785 allocs/op
BenchmarkReplaceBackend-6                                3216202               377.9 ns/op         2646089 objects/sec       448 B/op          9 allocs/op
BenchmarkReplaceService-6                                2284094               524.4 ns/op         1906815 objects/sec       464 B/op         10 allocs/op
Benchmark_UpsertBackends_SharedBackendManyServices-6           1        3182529066 ns/op        962720856 B/op  16146352 allocs/op
PASS
ok      github.com/cilium/cilium/pkg/loadbalancer/writer        10.315s
```

After:
```
pkg/loadbalancer/writer/ > stg push
> loadbalancer-flatten-backend
pkg/loadbalancer/writer/ > go test . -bench . -benchmem
goos: linux
goarch: arm64
pkg: github.com/cilium/cilium/pkg/loadbalancer/writer
Benchmark_UpsertServiceAndFrontends_100-6                   3796            314436 ns/op            318030 objects/sec    328109 B/op       4840 allocs/op
Benchmark_UpsertServiceAndFrontends_100_Unchanged-6        14769             80686 ns/op           1239372 objects/sec     50012 B/op       1151 allocs/op
Benchmark_UpsertServiceAndFrontends_1-6                   144716              7964 ns/op            125565 objects/sec     13103 B/op         91 allocs/op
BenchmarkInsertBackend-6                                    3433            338560 ns/op            295369 objects/sec    439490 B/op       5285 allocs/op
BenchmarkReplaceBackend-6                                4402164               272.7 ns/op         3667044 objects/sec       226 B/op          6 allocs/op
BenchmarkReplaceService-6                                2189962               535.3 ns/op         1868165 objects/sec       464 B/op         10 allocs/op
Benchmark_UpsertBackends_SharedBackendManyServices-6        1480            756108 ns/op          552204 B/op      14062 allocs/op
PASS
ok      github.com/cilium/cilium/pkg/loadbalancer/writer        8.681s
```

The "Benchmark_UpsertBackends_SharedBackendManyServices" inserts a backend that is shared by 2000 services.
By storing the backends flat in the table this is now 4000x faster and consumes ~500kB instead of 1GB
of memory.

The downside of this is that now it is harder to get the set of backend IP addresses and we need
to dedup on the consuming side. The backend table by default is also now sorted first by
service name.

Fixes: https://github.com/cilium/cilium/issues/44310

```release-note
The internal representation of load-balancing backends has been refactored to efficiently support thousands of services referencing a shared backend.
```

### CODE REVIEW

**Review by rastislavs — APPROVED** [review]
Looks good for my codeowners

File: pkg/loadbalancer/writer/writer.go [hunk 1]
```diff
@@ -248,24 +243,31 @@ func (w *Writer) DeleteFrontend(txn WriteTxn, addr loadbalancer.L3n4Addr) {
 }
 
 func (w *Writer) UpdateBackendHealth(txn WriteTxn, serviceName loadbalancer.ServiceName, backend loadbalancer.L3n4Addr, healthy bool) (bool, error) {
-	be, _, ok := w.bes.Get(txn, loadbalancer.BackendByAddress(backend))
-	if !ok {
-		return false, loadbalancer.ErrServiceNotFound
+	var (
+		target *loadbalancer.Backend
+	)
+	bes, _ := loadbalancer.ListBackendsByServiceName(txn, w.bes, serviceName)
```
Comment (joamaki) [inline pkg/loadbalancer/writer/writer.go]: Maybe search here with `<name>\0<addr>\0`

**Review by jrajahalme — APPROVED** [review]

**Review by dylandreimerink — APPROVED** [review]

**Comment by jasonaliyetti** [comment]
Is there any chance this can be backported to 1.18 and 1.19?

My team tried to upgrade from 1.17 to 1.18 and hit the underlying issue around many services referencing shared backends.  We are trying to assess how to upgrade especially since jumping minor versions isn't technically supported.

**Comment by joamaki** [comment]
> Is there any chance this can be backported to 1.18 and 1.19?
> 
> My team tried to upgrade from 1.17 to 1.18 and hit the underlying issue around many services referencing shared backends. We are trying to assess how to upgrade especially since jumping minor versions isn't technically supported.

Will look into whether it's feasible to backport this!

**Comment by joestringer** [comment]
:wave: the scalability improvement here seems like something we might want to include in the release announcement for v1.20, so I bumped this up to `release-note/major`.
