### PR TITLE
Fix the initialization of host endpoint labels

### LINKED ISSUE #13676: Host Firewall: Attaching a label to a node before deploying Cilium breaks the host firewall
## Bug report

When trying to deploy the host firewall, attaching a label to the node _before_ deploying Cilium makes the agent unable to pick up the label and deploy the host policy correctly.

While the issue was observed with the host firewall, the fact that the label is not displayed in `cilium endpoint list` may not be specific to this feature.

**General Information**

- Cilium version: v1.9.0-rc2
- Kernel version: 4.19.112
- Orchestration system version in use: GKE, K8s v1.15.12-gke.20

**How to reproduce the issue**

1. Create a GKE cluster (see <https://docs.cilium.io/en/latest/gettingstarted/k8s-install-gke/>).
2. Attach the `node-access=ssh` label to a node, see the GSG at <https://docs.cilium.io/en/v1.9.0-rc2/gettingstarted/host-firewall/>:
   ```
   $ kubectl label node $NODE_NAME node-access=ssh
   ```
3. Deploy Cilium with the host firewall enabled (don't forget to disable per-endpoint routing, currently incompatible with the host firewall):
   ```
   $ kubectl create namespace cilium
   $ helm install cilium ./cilium \
     --namespace cilium \
     --set nodeinit.enabled=true \
     --set nodeinit.reconfigureKubelet=true \
     --set nodeinit.removeCbrBridge=true \
     --set cni.binPath=/home/kubernetes/bin \
     --set ipam.mode=kubernetes \
     --set nativeRoutingCIDR=$NATIVE_CIDR \
     --set hostFirewall=true \
     --set devices=eth0 \
     --set endpointRoutes.enabled=false \
     --set tunnel=disabled
   ```
   Note: the exact steps I ran were: a) Deploy Cilium, b) Attach the label, c) Uninstall then redeploy CIlium.
4. To follow the GSG, enable the audit mode, then apply a policy:
   ```
   $ CILIUM_NAMESPACE=cilium
   $ CILIUM_POD_NAME=$(kubectl -n $CILIUM_NAMESPACE get pods -o json | jq -r '.items[] | select( .metadata.labels."k8s-app" == "cilium" and .spec.nodeName == env.NODE_NAME ).metadata.name')
   $ HOST_EP_ID=$(kubectl -n $CILIUM_NAMESPACE exec $CILIUM_POD_NAME -- cilium endpoint list -o jsonpath='{[?(@.status.identity.id==1)].id}')
   $ kubectl -n $CILIUM_NAMESPACE exec $CILIUM_POD_NAME -- cilium endpoint config $HOST_EP_ID PolicyAuditMode=Enabled
   Endpoint 293 configuration updated successfully
   $ kubectl -n $CILIUM_NAMESPACE exec $CILIUM_POD_NAME -- cilium endpoint config $HOST_EP_ID | grep PolicyAuditMode
   PolicyAuditMode          Enabled
   $ kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.9.0-rc2/examples/policies/host/demo-host-policy.yaml
   ciliumclusterwidenetworkpolicy.cilium.io/demo-host-policy created
   ```

The `node-access=ssh` for the host should then appear in the list of endpoints. The ingress policy enforcement should also be marked as `Disabled (Audit)`. What happens instead is that neither the label nor the policy are being reported:

```
$ kubectl -n $CILIUM_NAMESPACE exec $CILIUM_POD_NAME -- cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                      IPv6   IPv4          STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                        
293        Disabled           Disabled          1          k8s:cloud.google.com/gke-nodepool=default-pool                        ready   
                                                           k8s:cloud.google.com/gke-os-distribution=cos                                  
                                                           reserved:host                                                                 
1867       Disabled           Disabled          4          reserved:health                                         10.60.3.167   ready
```

However, Kubernetes _is_ aware of the label:

```
$ kubectl get nodes $NODE_NAME --show-labels
NAME                                         STATUS   ROLES    AGE   VERSION           LABELS
gke-test-cluster-default-pool-fa00e972-xziz   Ready    <none>   1d   v1.15.12-gke.20   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/fluentd-ds-ready=true,beta.kubernetes.io/instance-type=n1-standard-4,beta.kubernetes.io/os=linux,cloud.google.com/gke-nodepool=default-pool,cloud.google.com/gke-os-distribution=cos,failure-domain.beta.kubernetes.io/region=europe-west2,failure-domain.beta.kubernetes.io/zone=europe-west2-a,kubernetes.io/arch=amd64,kubernetes.io/hostname=gke-test-cluster-default-pool-fa00e972-xziz,kubernetes.io/os=linux,node-access=ssh
```

Attempting to display the policy verdicts for the host with `cilium monitor` prints nothing.

The issue can be solved by removing and re-creating the label (or possibly by simply overwriting it, I have not tried):

```
$ kubectl label node $NODE_NAME node-access-
$ kubectl label node $NODE_NAME node-access=ssh
```

After that, everything works as expected.

A note is being added to the GSG to make sure users attach the label first, in https://github.com/cilium/cilium/pull/13673.

### PR DESCRIPTION
**Pull request by pchaigno**
To properly initialize the host endpoint with labels added before the agent starts, we need to watch for k8s Node ADD events and use the new set of labels to update the restored host endpoint. See commits for details.

I tested this patch set in https://github.com/cilium/cilium/pull/15714, with an extension to the tests. That extension to the test can't be backported so I'll submit it in a separate PR to ease backporting of the present fix.

Fixes: https://github.com/cilium/cilium/issues/13676.

### CODE REVIEW

**Comment by pchaigno** [comment]
test-me-please

File: pkg/k8s/watchers/node.go [hunk 1]
```diff
@@ -37,11 +38,13 @@ func (k *K8sWatcher) nodesInit(k8sClient kubernetes.Interface) {
...
+				var valid bool
 				if node := k8s.ObjToV1Node(obj); node != nil {
-					if option.Config.BGPAnnounceLBIP {
-						k.bgpSpeakerManager.OnUpdateNode(node) // Need to seed the BGP speaker
-					}
+					valid = true
+					err := k.updateK8sNodeV1(nil, node)
+					k.K8sEventProcessed(metricNode, metricUpdate, err == nil)
 				}
+				k.K8sEventReceived(metricNode, metricUpdate, valid, false)
```
Comment (aanm) [inline pkg/k8s/watchers/node.go]: this should be metricCreate

Comment (aanm) [inline pkg/k8s/watchers/node.go]: this should be metricCreate

File: pkg/k8s/watchers/node.go [hunk 2]
```diff
@@ -70,12 +73,16 @@ func (k *K8sWatcher) nodesInit(k8sClient kubernetes.Interface) {
...
+	if oldK8sNode != nil {
+		oldNodeLabels = oldK8sNode.GetLabels()
+	}
 	newNodeLabels := newK8sNode.GetLabels()
 
 	nodeEP := k.endpointManager.GetHostEndpoint()
 	if nodeEP == nil {
-		log.Error("Host endpoint not found")
+		log.Debug("Host endpoint not found, updating node labels")
+		node.UpdateLabels(oldNodeLabels, newNodeLabels)
```
Comment (aanm) [inline pkg/k8s/watchers/node.go]: Why not simply pass the newNodeLabels with the `node.SetLabels(newNodeLabels)`?

**Review by aanm — CHANGES_REQUESTED** [review]

File: pkg/k8s/watchers/node.go [hunk 3]
```diff
@@ -37,11 +38,13 @@ func (k *K8sWatcher) nodesInit(k8sClient kubernetes.Interface) {
 		0,
 		cache.ResourceEventHandlerFuncs{
 			AddFunc: func(obj interface{}) {
+				var valid bool
 				if node := k8s.ObjToV1Node(obj); node != nil {
-					if option.Config.BGPAnnounceLBIP {
-						k.bgpSpeakerManager.OnUpdateNode(node) // Need to seed the BGP speaker
-					}
```
Comment (christarazi) [inline pkg/k8s/watchers/node.go:43]: Why was this removed? It is still needed to seed the BGP subsystem. You can add it to the end of `updateK8sNodeV1`

**Review by christarazi — CHANGES_REQUESTED** [review]
One more comment on top of Andre's review

File: pkg/k8s/watchers/node.go (hunk 3 above)
Comment (pchaigno) [reply pkg/k8s/watchers/node.go:43]: It's already called in `updateK8sNodeV1`. Is something different needed?

File: pkg/k8s/watchers/node.go (hunk 2 above)
Comment (pchaigno) [reply pkg/k8s/watchers/node.go]: :facepalm: I think I started implementing `UpdateLabels` thinking something different was needed and completely forgot about `SetLabels` afterward.

File: pkg/k8s/watchers/node.go (hunk 3 above)
Comment (christarazi) [reply pkg/k8s/watchers/node.go:43]: Oh, right! I missed that. Nevermind :sweat_smile:

**Review by christarazi — APPROVED** [review]

**Comment by pchaigno** [comment]
test-me-please

File: pkg/k8s/watchers/watcher.go [hunk 4]
```diff
@@ -342,6 +342,9 @@ func (k *K8sWatcher) InitK8sSubsystem(ctx context.Context) <-chan struct{} {
 			// We need to know about active local redirect policy services
 			// before BPF LB datapath is synced.
 			k8sAPIGroupCiliumLocalRedirectPolicyV2,
+			// We need to know the node labels to populate the host endpoint
+			// labels.
+			k8sAPIGroupNodeV1Core,
```
Comment (brb) [inline pkg/k8s/watchers/watcher.go:347]: @aanm Won't this cause scalability issues? IIRC you moved this away to cilium-operator, as  cilium-agent was not able to keep up with Node events. Or is it just one-off subscribe?

Comment (pchaigno) [reply pkg/k8s/watchers/watcher.go:347]: In case it matters: we're only watching for Node events for the local node.

Comment (aanm) [reply pkg/k8s/watchers/watcher.go:347]: Yeah it's like Paul said, it's ok because we are only watching for 1 node.

**Review by aanm — APPROVED** [review]

**Comment by pchaigno** [comment]
test-only --focus="K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with direct routing Tests LoadBalancer Connectivity to endpoint via LB" --k8s_version=1.16 --kernel_version=netnext

**Review by jibi — APPROVED** [review]

**Comment by pchaigno** [comment]
All team reviews are covered and the test-only for the test that failed in k8s-1.16-kernel-netnext passed. Merging.
