### PR TITLE
ipcache: Fix IPcache leak of remote-node IP addresses

### LINKED ISSUE #21844: Remote node IP addresses kept in ipcaches when the node is removed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When the cluster is resized and a node is removed, its IP addresses are kept in the ipcache maps of other nodes. Those IP addresses are then overwritten when they are reallocated.

```
$ gcloud container clusters create paul-cluster --num-nodes 3 --machine-type n1-standard-4 --zone europe-west4-a --node-taints node.cilium.io/agent-not-ready=true:NoSchedule
$ cilium install
# Assuming cilium-lkbnc is on the removed node:
$ kubectl -n kube-system -c cilium-agent exec cilium-lkbnc -- ip a show dev cilium_host
    inet 10.68.0.82/32 scope link cilium_host
$ kubectl -n kube-system -c cilium-agent exec cilium-lkbnc -- ip a show dev eth0
    inet 10.164.0.29/32 scope global dynamic eth0
$ gcloud container clusters resize paul-cluster --num-nodes 2 --region europe-west4-a
# Assuming cilium-8btml is on one of the remaining nodes:
$ kubectl -n kube-system -c cilium-agent exec cilium-8btml -- cilium bpf ipcache get 10.68.0.82
10.68.0.82 maps to identity identity=6 encryptkey=3 tunnelendpoint=10.164.0.29
$ kubectl -n kube-system -c cilium-agent exec cilium-8btml -- cilium bpf ipcache get 10.164.0.29
10.164.0.29 maps to identity identity=6 encryptkey=0 tunnelendpoint=10.164.0.29
```

### Cilium Version

latest (4bafe1750f)

### Kernel Version

5.10.133 (Google COS)

### Kubernetes Version

v1.22.12-gke.2300

### Sysdump

[cilium-sysdump-20221021-165641.zip](https://github.com/cilium/cilium/files/9840184/cilium-sysdump-20221021-165641.zip)

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by pchaigno**
The first commit refactors the code a bit to avoid any refactoring changes in the second commit. The second commit fixes the IPcache leak for remote-node IP addresses. The third commit increases the log level on the error from debug to error to ensure we don't miss such bugs in the future. See commits for details.

cc @joestringer, as the author of https://github.com/cilium/cilium/pull/19765:
Note I fixed the bug by changing the deletion logic to follow the `a.b.c.d/32` format, but maybe I should have changed the insert logic to follow the format `a.b.c.d` instead.

As far as I can see, this bug wasn't released anywhere, hence the `release-note/misc` label.

Fixes: https://github.com/cilium/cilium/pull/19765
Fixes: https://github.com/cilium/cilium/pull/4810
Fixes: https://github.com/cilium/cilium/issues/21844

### CODE REVIEW

File: pkg/ipcache/ipcache.go [hunk 1]
```diff
@@ -511,7 +511,7 @@ func (ipc *IPCache) deleteLocked(ip string, source source.Source) (namedPortsCha
 
 	cachedIdentity, found := ipc.ipToIdentityCache[ip]
 	if !found {
-		scopedLog.Debug("Attempt to remove non-existing IP from ipcache layer")
+		scopedLog.Error("Attempt to remove non-existing IP from ipcache layer")
```
Comment (joestringer) [inline pkg/ipcache/ipcache.go]: I'm a little concerned that this will cause noisy logs in some scenario, but I'm OK to try this out and see what reports come through up until 1.13 final.

**Review by joestringer — APPROVED** [review]
Thanks for the fix. This matches the insertion side, so LGTM.

File: pkg/ipcache/ipcache.go (hunk 1 above)
Comment (pchaigno) [reply pkg/ipcache/ipcache.go]: I have the same concern, but we fail on any error in CI, so hopefully we should catch at least the most obvious scenarios.

**Comment by joestringer** [comment]
Issue https://github.com/cilium/cilium/issues/21142 is trying to slowly move away from having this interface be defined by strings so we can avoid this whole class of bugs across the codebase, but it's a bit slow going. In the mean time I think that squashing these bugs is about as good as we can do. :pray:

File: pkg/ipcache/ipcache.go (hunk 1 above)
Comment (pchaigno) [reply pkg/ipcache/ipcache.go]: Well, CI is currently failing because of that error log. See, it's working :sweat_smile:

**Comment by pchaigno** [comment]
/test-1.23-5.4

**Comment by pchaigno** [comment]
/test-1.26-net-next

**Comment by pchaigno** [comment]
ConformanceAKS failed with known flake https://github.com/cilium/cilium/issues/22162. k8s-1.16-kernel-4.9 failed with reoccuring flake https://github.com/cilium/cilium/issues/22404. Both are unrelated to the changes in this PR. Merging.

File: pkg/ipcache/ipcache.go [hunk 2]
```diff
@@ -507,7 +507,7 @@ func (ipc *IPCache) deleteLocked(ip string, source source.Source) (namedPortsCha
 
 	cachedIdentity, found := ipc.ipToIdentityCache[ip]
 	if !found {
-		scopedLog.Debug("Attempt to remove non-existing IP from ipcache layer")
```
Comment (julianwiedmann) [inline pkg/ipcache/ipcache.go:510]: FYI - caught this in an (unrelated) [draft PR](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.26-kernel-net-next/138/testReport/junit/Suite-k8s-1/26/K8sDatapathConfig_AutoDirectNodeRoutes_Check_direct_connectivity_with_per_endpoint_routes/).

File: pkg/ipcache/ipcache.go [hunk 3]
```diff
@@ -507,7 +507,7 @@ func (ipc *IPCache) deleteLocked(ip string, source source.Source) (namedPortsCha
...
+		scopedLog.Warn("Attempt to remove non-existing IP from ipcache layer")
```
Comment (julianwiedmann) [inline pkg/ipcache/ipcache.go:510]: FYI - caught this in an (unrelated) [draft PR](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.26-kernel-net-next/138/testReport/junit/Suite-k8s-1/26/K8sDatapathConfig_AutoDirectNodeRoutes_Check_direct_connectivity_with_per_endpoint_routes/).
