### PR TITLE
DNS proxy: reuse TCP connection

### LINKED ISSUE #31197: Cilium fqdn/dnsproxy fails with FQDN dns policy when DNS respons is truncated
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?
https://github.com/cilium/cilium/pull/29239 introduced a new default which causes issues in certain setup

An egress.toFQDNs policy does not work under certain conditions when the DNS response is truncated and the host has IPv6 enabled in a IPv4-only environment. 

The dns proxy in cilium seems to be unable to connect to upstream coredns, but I don't think this is the real issue:
```
cilium-agent level=error msg="Cannot forward proxied DNS lookup" DNSRequestID=36304 dnsName=aoai-digital-pippen.openai.azure.com. endpointID=523 error="failed to dial connection to 10.254.61.105:53: dial tcp 10.254.93.208:55534->10.254.61.105:53: connect: cannot assign requested address" identity=41536 ipAddr="10.254.93.208:55534" subsys=fqdn/dnsproxy
```

Setting dnsproxy-enable-transparent-mode to false corrects the issue.

There seem to be a related issue (https://github.com/cilium/cilium/issues/30669) where this change has caused issues as well.

I'm not sure what's specific to our networking layout that would cause this new default to create issues. I do note however that this specific comment seem to match our issue:
https://github.com/cilium/cilium/pull/28928#issuecomment-1788951996
```dnsproxy gets timeouts waiting for response from the dns server when curl is issuing both IPv4 (A) and IPv6 (AAAA) queries at the same time. Works flawlessly if limiting to IPv4 only (curl -4 ...).```

The issue seems to occur only if the DNS response has the DNS TC flag set.

This occurs only for this specific DNS query, any other queries pass through the proxy without issue or error msg. Here is the applied NetworkPolicy for the affected pod:

```yaml
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: test
spec:
  endpointSelector:
    matchLabels:
      test: "true"
  egress:
    - toFQDNs:
        - matchName: aoai-digital-pippen.openai.azure.com.
```   

With this policy present, I'm expecting that traffic to this endpoint is allowed:
```
# getent hosts aoai-digital-pippen.openai.azure.com.
20.61.99.32     api0df69e61b7d2469bb25a53be6441fcf3pcvso5kj6wdvbahismwbl.westeurope.cloudapp.azure.com aoai-digital-pippen.openai.azure.com westeurope.api.cognitive.microsoft.com cognitiveweprod.trafficmanager.net cognitiveweprod.azure-api.net apimgmttmdjylckcx6clmh2isu2wr38uqzm63s8n4ub2y3e6xs.trafficmanager.net cognitiveweprod-westeurope-01.regional.azure-api.net
/# curl -v aoai-digital-pippen.openai.azure.com.
* Could not resolve host: aoai-digital-pippen.openai.azure.com.
* Closing connection 0
curl: (6) Could not resolve host: aoai-digital-pippen.openai.azure.com.
```

Putting cilium in debug mode, I was able to grab what fqdn/dnsproxy is logging related to this:
```
level=debug msg="Waited for endpoints to regenerate due to a DNS response" duration="70.817µs" endpointID=2638 qname=aoai-digital-pippen.openai.azure.com. subsys=daemon
level=debug msg="Responding to original DNS query" DNSRequestID=54559 dnsName=aoai-digital-pippen.openai.azure.com. endpointID=2638 identity=29739 ipAddr="10.254.150.167:37343" subsys=fqdn/dnsproxy
level=debug msg="Received DNS response to proxied lookup" DNSRequestID=43037 dnsName=aoai-digital-pippen.openai.azure.com. endpointID=2638 identity=29739 ipAddr="10.254.150.167:37343" resp=";; opcode: QUERY, status: NOERROR, id: 49148\n;; flags: qr tc rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;aoai-digital-pippen.openai.azure.com.\tIN\t AAAA\n\n;; ANSWER SECTION:\naoai-digital-pippen.openai.azure.com.\t5\tIN\tCNAME\twesteurope.api.cognitive.microsoft.com.\nwesteurope.api.cognitive.microsoft.com.\t5\tIN\tCNAME\tcognitiveweprod.trafficmanager.net.\ncognitiveweprod.trafficmanager.net.\t5\tIN\tCNAME\tcognitiveweprod.azure-api.net.\ncognitiveweprod.azure-api.net.\t5\tIN\tCNAME\tapimgmttmdjylckcx6clmh2isu2wr38uqzm63s8n4ub2y3e6xs.trafficmanager.net.\napimgmttmdjylckcx6clmh2isu2wr38uqzm63s8n4ub2y3e6xs.trafficmanager.net.\t5\tIN\tCNAME\tcognitiveweprod-westeurope-01.regional.azure-api.net.\n" subsys=fqdn/dnsproxy
level=debug msg="Notifying with DNS response to original DNS query" DNSRequestID=43037 dnsName=aoai-digital-pippen.openai.azure.com. endpointID=2638 identity=29739 ipAddr="10.254.150.167:37343" subsys=fqdn/dnsproxy
level=debug msg="Responding to original DNS query" DNSRequestID=43037 dnsName=aoai-digital-pippen.openai.azure.com. endpointID=2638 identity=29739 ipAddr="10.254.150.167:37343" subsys=fqdn/dnsproxy
level=debug msg="Handling DNS query from endpoint" DNSRequestID=54559 dnsName=aoai-digital-pippen.openai.azure.com. ipAddr="10.254.150.167:57560" subsys=fqdn/dnsproxy
level=debug msg="Found target server to of DNS request secID {ID:10023 Source:custom-resource _:[] shadowed:false createdFromMetadata:false}" DNSRequestID=54559 dnsName=aoai-digital-pippen.openai.azure.com. endpointID=2638 identity=29739 ipAddr="10.254.150.167:57560" server="10.254.87.63:53" subsys=fqdn/dnsproxy
level=debug msg="Forwarding DNS request for a name that is allowed" DNSRequestID=54559 dnsName=aoai-digital-pippen.openai.azure.com. endpointID=2638 identity=29739 ipAddr="10.254.150.167:57560" subsys=fqdn/dnsproxy
level=debug msg="Received DNS response to proxied lookup" DNSRequestID=54559 dnsName=aoai-digital-pippen.openai.azure.com. endpointID=2638 identity=29739 ipAddr="10.254.150.167:57560" resp=";; opcode: QUERY, status: NOERROR, id: 44857\n;; flags: qr aa rd ra; QUERY: 1, ANSWER: 7, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;aoai-digital-pippen.openai.azure.com.\tIN\t A\n\n;; ANSWER SECTION:\naoai-digital-pippen.openai.azure.com.\t2\tIN\tCNAME\twesteurope.api.cognitive.microsoft.com.\nwesteurope.api.cognitive.microsoft.com.\t2\tIN\tCNAME\tcognitiveweprod.trafficmanager.net.\ncognitiveweprod.trafficmanager.net.\t2\tIN\tCNAME\tcognitiveweprod.azure-api.net.\ncognitiveweprod.azure-api.net.\t2\tIN\tCNAME\tapimgmttmdjylckcx6clmh2isu2wr38uqzm63s8n4ub2y3e6xs.trafficmanager.net.\napimgmttmdjylckcx6clmh2isu2wr38uqzm63s8n4ub2y3e6xs.trafficmanager.net.\t2\tIN\tCNAME\tcognitiveweprod-westeurope-01.regional.azure-api.net.\ncognitiveweprod-westeurope-01.regional.azure-api.net.\t2\tIN\tCNAME\tapi0df69e61b7d2469bb25a53be6441fcf3pcvso5kj6wdvbahismwbl.westeurope.cloudapp.azure.com.\napi0df69e61b7d2469bb25a53be6441fcf3pcvso5kj6wdvbahismwbl.westeurope.cloudapp.azure.com.\t2\tIN\tA\t20.61.99.32\n" subsys=fqdn/dnsproxy
level=debug msg="Notifying with DNS response to original DNS query" DNSRequestID=54559 dnsName=aoai-digital-pippen.openai.azure.com. endpointID=2638 identity=29739 ipAddr="10.254.150.167:57560" subsys=fqdn/dnsproxy
level=debug msg="Updating DNS name in cache from response to query" ips="[20.61.99.32]" qname=aoai-digital-pippen.openai.azure.com. subsys=daemon
level=debug msg="FQDN: IPs didn't change for DNS name" dnsName=aoai-digital-pippen.openai.azure.com. lookupIPs="&{2 [20.61.99.32]}" subsys=fqdn
level=debug msg="Waited for endpoints to regenerate due to a DNS response" duration="53.699µs" endpointID=2638 qname=aoai-digital-pippen.openai.azure.com. subsys=daemon
level=debug msg="Responding to original DNS query" DNSRequestID=54559 dnsName=aoai-digital-pippen.openai.azure.com. endpointID=2638 identity=29739 ipAddr="10.254.150.167:57560" subsys=fqdn/dnsproxy
level=debug msg="Handling DNS query from endpoint" DNSRequestID=43037 dnsName=aoai-digital-pippen.openai.azure.com. ipAddr="10.254.150.167:57560" subsys=fqdn/dnsproxy
level=debug msg="Found target server to of DNS request secID {ID:10023 Source:custom-resource _:[] shadowed:false createdFromMetadata:false}" DNSRequestID=43037 dnsName=aoai-digital-pippen.openai.azure.com. endpointID=2638 identity=29739 ipAddr="10.254.150.167:57560" server="10.254.87.63:53" subsys=fqdn/dnsproxy
level=debug msg="Forwarding DNS request for a name that is allowed" DNSRequestID=43037 dnsName=aoai-digital-pippen.openai.azure.com. endpointID=2638 identity=29739 ipAddr="10.254.150.167:57560" subsys=fqdn/dnsproxy
level=error msg="Cannot forward proxied DNS lookup" DNSRequestID=43037 dnsName=aoai-digital-pippen.openai.azure.com. endpointID=2638 error="failed to dial connection to 10.254.87.63:53: dial tcp 10.254.150.167:57560->10.254.87.63:53: connect: cannot assign requested address" identity=29739 ipAddr="10.254.150.167:57560" subsys=fqdn/dnsproxy
```

Notice that the _first_ DNS query returns an incomplete response (see `ANSWER: 5, `), but with the `tc` flag set, so the response is in-complete as it does not fit into the UDP packet. It then re-queries over TCP, (see `ANSWER: 7, `), and the complete query is returned.

For reference, this is the answer payload I saw locally when testing this:
```shell
;; ANSWER SECTION:
aoai-digital-pippen.openai.azure.com. 900 IN CNAME westeurope.api.cognitive.microsoft.com.
westeurope.api.cognitive.microsoft.com.	3600 IN	CNAME cognitiveweprod.trafficmanager.net.
cognitiveweprod.trafficmanager.net. 30 IN CNAME	cognitiveweprod.azure-api.net.
cognitiveweprod.azure-api.net. 900 IN	CNAME	apimgmttmdjylckcx6clmh2isu2wr38uqzm63s8n4ub2y3e6xs.trafficmanager.net.
apimgmttmdjylckcx6clmh2isu2wr38uqzm63s8n4ub2y3e6xs.trafficmanager.net. 300 IN CNAME cognitiveweprod-westeurope-01.regional.azure-api.net.
cognitiveweprod-westeurope-01.regional.azure-api.net. 900 IN CNAME api0df69e61b7d2469bb25a53be6441fcf3pcvso5kj6wdvbahismwbl.westeurope.cloudapp.azure.com.
api0df69e61b7d2469bb25a53be6441fcf3pcvso5kj6wdvbahismwbl.westeurope.cloudapp.azure.com.	10 IN A	20.61.99.32
```

Within the affected pod, DNS query works as expected:
```shell
# getent hosts aoai-digital-pippen.openai.azure.com.
20.61.99.32     api0df69e61b7d2469bb25a53be6441fcf3pcvso5kj6wdvbahismwbl.westeurope.cloudapp.azure.com aoai-digital-pippen.openai.azure.com westeurope.api.cognitive.microsoft.com cognitiveweprod.trafficmanager.net cognitiveweprod.azure-api.net apimgmttmdjylckcx6clmh2isu2wr38uqzm63s8n4ub2y3e6xs.trafficmanager.net cognitiveweprod-westeurope-01.regional.azure-api.net
/# cat /etc/resolv.conf 
search redact.svc.cluster.local svc.cluster.local cluster.local eu-north-1.compute.internal
nameserver 10.255.0.10
options ndots:5
```

While doing the lookup, the following Hubble flow is observed:
```yaml
redact:41566 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) policy-verdict:L3-L4 EGRESS ALLOWED (UDP)
redact:41566 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-proxy FORWARDED (UDP)
redact:41566 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) dns-request proxy FORWARDED (DNS Query aoai-digital-pippen.openai.azure.com. AAAA)
redact:41566 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) policy-verdict:L3-L4 INGRESS ALLOWED (UDP)
redact:41566 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-endpoint FORWARDED (UDP)
redact:39642 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) policy-verdict:L3-L4 EGRESS ALLOWED (TCP Flags: SYN)
redact:39642 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-proxy FORWARDED (TCP Flags: SYN)
redact:39642 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-proxy FORWARDED (TCP Flags: ACK)
redact:39642 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-proxy FORWARDED (TCP Flags: ACK, PSH)
redact:39642 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) dns-request proxy FORWARDED (DNS Query aoai-digital-pippen.openai.azure.com. AAAA)
redact:39642 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) policy-verdict:L3-L4 INGRESS ALLOWED (TCP Flags: SYN)
redact:39642 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-endpoint FORWARDED (TCP Flags: SYN)
redact:39642 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-endpoint FORWARDED (TCP Flags: ACK)
redact:39642 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
redact:39642 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-endpoint FORWARDED (TCP Flags: ACK, FIN)
redact:39642 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-proxy FORWARDED (TCP Flags: ACK, FIN)
redact:39642 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-endpoint FORWARDED (TCP Flags: ACK)
redact:39642 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-proxy FORWARDED (TCP Flags: ACK)
redact:51481 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) policy-verdict:L3-L4 EGRESS ALLOWED (UDP)
redact:51481 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-proxy FORWARDED (UDP)
redact:51481 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) dns-request proxy FORWARDED (DNS Query aoai-digital-pippen.openai.azure.com. A)
redact:51481 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) policy-verdict:L3-L4 INGRESS ALLOWED (UDP)
redact:51481 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-endpoint FORWARDED (UDP)
redact:54074 (ID:41536) -> kube-system/coredns-7f6fdfd5c-p5tph:53 (ID:10023) policy-verdict:L3-L4 EGRESS ALLOWED (TCP Flags: SYN)
redact:54074 (ID:41536) -> kube-system/coredns-7f6fdfd5c-p5tph:53 (ID:10023) to-proxy FORWARDED (TCP Flags: SYN)
redact:54074 (ID:41536) -> kube-system/coredns-7f6fdfd5c-p5tph:53 (ID:10023) to-proxy FORWARDED (TCP Flags: ACK)
redact:54074 (ID:41536) -> kube-system/coredns-7f6fdfd5c-p5tph:53 (ID:10023) to-proxy FORWARDED (TCP Flags: ACK, PSH)
redact:54074 (ID:41536) -> kube-system/coredns-7f6fdfd5c-p5tph:53 (ID:10023) dns-request proxy FORWARDED (DNS Query aoai-digital-pippen.openai.azure.com. A)
redact:54074 (ID:41536) -> kube-system/coredns-7f6fdfd5c-p5tph:53 (ID:10023) to-proxy FORWARDED (TCP Flags: ACK, FIN)
redact:54074 (ID:41536) -> kube-system/coredns-7f6fdfd5c-p5tph:53 (ID:10023) to-proxy FORWARDED (TCP Flags: ACK)
```

On the other hand, curl will fail even though the policy should allow the traffic:
```shell
# curl aoai-digital-pippen.openai.azure.com. -v
* Could not resolve host: aoai-digital-pippen.openai.azure.com.
* Closing connection 0
curl: (6) Could not resolve host: aoai-digital-pippen.openai.azure.com.
```

This is when cilium will log the following error:
```
level=error msg="Cannot forward proxied DNS lookup" DNSRequestID=52940 dnsName=aoai-digital-pippen.openai.azure.com. endpointID=523 error="failed to dial connection to 10.254.61.105:53: dial tcp 10.254.93.208:59448->10.254.61.105:53: connect: cannot assign requested address" identity=41536 ipAddr="10.254.93.208:59448" subsys=fqdn/dnsproxy 
```

I doubt this is an issue with enough local ports, as the error is only generated for that specific query in our environment.

Hubble flows for this curl command shows an PROXY ERROR for the AAAA record, bot no error for the A record:
```redact:34083 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) policy-verdict:L3-L4 EGRESS ALLOWED (UDP)
redact:34083 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-proxy FORWARDED (UDP)
redact:34083 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) dns-request proxy FORWARDED (DNS Query aoai-digital-pippen.openai.azure.com. AAAA)
redact:34083 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) dns-request proxy FORWARDED (DNS Query aoai-digital-pippen.openai.azure.com. A)
redact:34083 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) policy-verdict:L3-L4 INGRESS ALLOWED (UDP)
redact:34083 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-endpoint FORWARDED (UDP)
redact:59448 (ID:41536) -> kube-system/coredns-7f6fdfd5c-p5tph:53 (ID:10023) policy-verdict:L3-L4 EGRESS ALLOWED (TCP Flags: SYN)
redact:59448 (ID:41536) -> kube-system/coredns-7f6fdfd5c-p5tph:53 (ID:10023) to-proxy FORWARDED (TCP Flags: SYN)
redact:59448 (ID:41536) -> kube-system/coredns-7f6fdfd5c-p5tph:53 (ID:10023) to-proxy FORWARDED (TCP Flags: ACK)
redact:59448 (ID:41536) -> kube-system/coredns-7f6fdfd5c-p5tph:53 (ID:10023) to-proxy FORWARDED (TCP Flags: ACK, PSH)
redact:59448 (ID:41536) -> kube-system/coredns-7f6fdfd5c-p5tph:53 (ID:10023) dns-request proxy FORWARDED (DNS Query aoai-digital-pippen.openai.azure.com. A)
redact:59448 (ID:41536) -> kube-system/coredns-7f6fdfd5c-p5tph:53 (ID:10023) dns-request proxy FORWARDED (DNS Query aoai-digital-pippen.openai.azure.com. AAAA)
redact:59448 (ID:41536) -> kube-system/coredns-7f6fdfd5c-p5tph:53 (ID:10023) dns-request proxy ERROR (DNS Query aoai-digital-pippen.openai.azure.com. AAAA)
redact:59448 (ID:41536) -> kube-system/coredns-7f6fdfd5c-p5tph:53 (ID:10023) to-proxy FORWARDED (TCP Flags: ACK, FIN)
```

For some reason, the curl command will work if one specify it with `-4` (This option tells curl to use IPv4 addresses only when resolving hostnames, and not for example try IPv6.):
```
# curl -4 aoai-digital-pippen.openai.azure.com. -I  --silent 
HTTP/1.1 400 Bad Request
Content-Length: 334
Content-Type: text/html; charset=us-ascii
Date: Wed, 06 Mar 2024 11:42:01 GMT
Connection: close
```

Cilium agent does not report any errors, and Hubble flow shows no error, but also no AAAA queries:
```
redact:46155 (ID:41536) -> kube-system/coredns-7f6fdfd5c-p5tph:53 (ID:10023) policy-verdict:L3-L4 EGRESS ALLOWED (UDP)
redact:46155 (ID:41536) -> kube-system/coredns-7f6fdfd5c-p5tph:53 (ID:10023) to-proxy FORWARDED (UDP)
redact:46155 (ID:41536) -> kube-system/coredns-7f6fdfd5c-p5tph:53 (ID:10023) dns-request proxy FORWARDED (DNS Query aoai-digital-pippen.openai.azure.com. A)
redact:54172 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) policy-verdict:L3-L4 EGRESS ALLOWED (TCP Flags: SYN)
redact:54172 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-proxy FORWARDED (TCP Flags: SYN)
redact:54172 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-proxy FORWARDED (TCP Flags: ACK)
redact:54172 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-proxy FORWARDED (TCP Flags: ACK, PSH)
redact:54172 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) dns-request proxy FORWARDED (DNS Query aoai-digital-pippen.openai.azure.com. A)
redact:54172 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) policy-verdict:L3-L4 INGRESS ALLOWED (TCP Flags: SYN)
redact:54172 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-endpoint FORWARDED (TCP Flags: SYN)
redact:54172 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-endpoint FORWARDED (TCP Flags: ACK)
redact:54172 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
redact:54172 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-endpoint FORWARDED (TCP Flags: ACK, FIN)
redact:54172 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-proxy FORWARDED (TCP Flags: ACK, FIN)
redact:54172 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-proxy FORWARDED (TCP Flags: ACK)
redact:54172 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-endpoint FORWARDED (TCP Flags: ACK)
redact:48856 (ID:41536) -> aoai-digital-pippen.openai.azure.com:80 (ID:16778731) policy-verdict:L3-L4 EGRESS ALLOWED (TCP Flags: SYN)
redact:48856 (ID:41536) -> aoai-digital-pippen.openai.azure.com:80 (ID:16778731) to-network FORWARDED (TCP Flags: SYN)
redact:48856 (ID:41536) -> aoai-digital-pippen.openai.azure.com:80 (ID:16778731) to-network FORWARDED (TCP Flags: ACK)
redact:48856 (ID:41536) -> aoai-digital-pippen.openai.azure.com:80 (ID:16778731) to-network FORWARDED (TCP Flags: ACK, PSH)
redact:48856 (ID:41536) -> aoai-digital-pippen.openai.azure.com:80 (ID:16778731) to-network FORWARDED (TCP Flags: ACK, FIN)
```

I'm not sure what's wrong here. If I update resolv.conf to include the [no-aaaa](https://man7.org/linux/man-pages/man5/resolv.conf.5.html) option, the problem goes away. But I find it strange and not expected that a failed AAAA query should deny traffic in this fashion.
```
resolv.conf :  this works
search redact.svc.cluster.local svc.cluster.local cluster.local eu-north-1.compute.internal.cluster.local cluster.local eu-north-1.compute.internal
nameserver 10.255.0.10
options ndots:5 no-aaaa

# curl aoai-digital-pippen.openai.azure.com.
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid Hostname</h2>
<hr><p>HTTP Error 400. The request hostname is invalid.</p>
</BODY></HTML>

redact:40135 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) policy-verdict:L3-L4 EGRESS ALLOWED (UDP)
redact:40135 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-proxy FORWARDED (UDP)
redact:40135 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) dns-request proxy FORWARDED (DNS Query aoai-digital-pippen.openai.azure.com. A)
redact:40135 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) policy-verdict:L3-L4 INGRESS ALLOWED (UDP)
redact:40135 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-endpoint FORWARDED (UDP)
redact:53652 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) policy-verdict:L3-L4 EGRESS ALLOWED (TCP Flags: SYN)
redact:53652 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-proxy FORWARDED (TCP Flags: SYN)
redact:53652 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-proxy FORWARDED (TCP Flags: ACK)
redact:53652 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-proxy FORWARDED (TCP Flags: ACK, PSH)
redact:53652 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) dns-request proxy FORWARDED (DNS Query aoai-digital-pippen.openai.azure.com. A)
redact:53652 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) policy-verdict:L3-L4 INGRESS ALLOWED (TCP Flags: SYN)
redact:53652 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-endpoint FORWARDED (TCP Flags: SYN)
redact:53652 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-endpoint FORWARDED (TCP Flags: ACK)
redact:53652 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
redact:53652 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-endpoint FORWARDED (TCP Flags: ACK, FIN)
redact:53652 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-proxy FORWARDED (TCP Flags: ACK, FIN)
redact:53652 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-proxy FORWARDED (TCP Flags: ACK)
redact:53652 (ID:41536) -> kube-system/coredns-7f6fdfd5c-fccrw:53 (ID:10023) to-endpoint FORWARDED (TCP Flags: ACK)
redact:40056 (ID:41536) -> aoai-digital-pippen.openai.azure.com:80 (ID:16778909) policy-verdict:L3-L4 EGRESS ALLOWED (TCP Flags: SYN)
redact:40056 (ID:41536) -> aoai-digital-pippen.openai.azure.com:80 (ID:16778909) to-network FORWARDED (TCP Flags: SYN)
redact:40056 (ID:41536) -> aoai-digital-pippen.openai.azure.com:80 (ID:16778909) to-network FORWARDED (TCP Flags: ACK)
redact:40056 (ID:41536) -> aoai-digital-pippen.openai.azure.com:80 (ID:16778909) to-network FORWARDED (TCP Flags: ACK, PSH)
redact:40056 (ID:41536) -> aoai-digital-pippen.openai.azure.com:80 (ID:16778909) to-network FORWARDED (TCP Flags: ACK, FIN)
```

I have a hunch that if there is something wrong with the fqdn/proxy component. Does it handle an incomplete query response for AAAA records properly ? As `aoai-digital-pippen.openai.azure.com.` for AAAA is just a CNAME chain that does not result in something:
```
 dig AAAA aoai-digital-pippen.openai.azure.com @8.8.8.8

; <<>> DiG 9.10.6 <<>> AAAA aoai-digital-pippen.openai.azure.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40269
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;aoai-digital-pippen.openai.azure.com. IN AAAA

;; ANSWER SECTION:
aoai-digital-pippen.openai.azure.com. 900 IN CNAME westeurope.api.cognitive.microsoft.com.
westeurope.api.cognitive.microsoft.com.	1134 IN	CNAME cognitiveweprod.trafficmanager.net.
cognitiveweprod.trafficmanager.net. 15 IN CNAME	cognitiveweprod.azure-api.net.
cognitiveweprod.azure-api.net. 855 IN	CNAME	apimgmttmdjylckcx6clmh2isu2wr38uqzm63s8n4ub2y3e6xs.trafficmanager.net.
apimgmttmdjylckcx6clmh2isu2wr38uqzm63s8n4ub2y3e6xs.trafficmanager.net. 300 IN CNAME cognitiveweprod-westeurope-01.regional.azure-api.net.
cognitiveweprod-westeurope-01.regional.azure-api.net. 713 IN CNAME api0df69e61b7d2469bb25a53be6441fcf3pcvso5kj6wdvbahismwbl.westeurope.cloudapp.azure.com.

;; AUTHORITY SECTION:
westeurope.cloudapp.azure.com. 60 IN	SOA	ns1-201.azure-dns.com. msnhst.microsoft.com. 10001 900 300 604800 60

;; Query time: 133 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Mar 06 13:56:40 CET 2024
;; MSG SIZE  rcvd: 472
```

I've briefly looked at the [proxy code](https://github.com/cilium/cilium/blob/f92b528abc30a5c66ba80d5922d4e58c48cfe7e1/pkg/fqdn/dnsproxy/proxy.go#L1135) that relates to CNAMES and AAAA, but I'm not able to identify if something special happens when a AAAA query returns a set of CNAMES that does not resolve to anything.

IPv6 is not disabled in the kernel.

### Cilium Version

# cilium version
Client: 1.15.1 a368c8f0 2024-02-14T22:16:57+00:00 go version go1.21.6 linux/amd64
Daemon: 1.15.1 a368c8f0 2024-02-14T22:16:57+00:00 go version go1.21.6 linux/amd64

### Kernel Version

# uname -a
Linux ip-10-209-136-25.eu-north-1.compute.internal 5.10.209-198.858.amzn2.x86_64 #1 SMP Tue Feb 13 18:46:41 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: v1.28.5-eks-5e0fdde

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell
apiVersion: v1
data:
  agent-not-ready-taint-key: node.cilium.io/agent-not-ready
  arping-refresh-period: 30s
  auto-create-cilium-node-resource: "true"
  auto-direct-node-routes: "false"
  aws-enable-prefix-delegation: "true"
  bpf-lb-acceleration: disabled
  bpf-lb-external-clusterip: "false"
  bpf-lb-map-max: "65536"
  bpf-lb-sock: "false"
  bpf-map-dynamic-size-ratio: "0.0025"
  bpf-policy-map-max: "16384"
  bpf-root: /sys/fs/bpf
  cgroup-root: /run/cilium/cgroupv2
  cilium-endpoint-gc-interval: 5m0s
  cluster-id: "0"
  cluster-name: default
  cni-exclusive: "true"
  cni-log-file: /var/run/cilium/cilium-cni.log
  controller-group-metrics: write-cni-file sync-host-ips sync-lb-maps-with-k8s-services
  custom-cni-conf: "false"
  debug: "false"
  debug-verbose: ""
  devices: eth0
  dnsproxy-enable-transparent-mode: "true"
  ec2-api-endpoint: ""
  egress-gateway-reconciliation-trigger-interval: 1s
  enable-auto-protect-node-port-range: "true"
  enable-bgp-control-plane: "false"
  enable-bpf-clock-probe: "false"
  enable-bpf-masquerade: "true"
  enable-endpoint-health-checking: "true"
  enable-endpoint-routes: "true"
  enable-health-check-loadbalancer-ip: "false"
  enable-health-check-nodeport: "true"
  enable-health-checking: "true"
  enable-hubble: "true"
  enable-hubble-open-metrics: "false"
  enable-ip-masq-agent: "true"
  enable-ipv4: "true"
  enable-ipv4-big-tcp: "false"
  enable-ipv4-masquerade: "true"
  enable-ipv6: "false"
  enable-ipv6-big-tcp: "false"
  enable-ipv6-masquerade: "true"
  enable-k8s-networkpolicy: "true"
  enable-k8s-terminating-endpoint: "true"
  enable-l2-neigh-discovery: "true"
  enable-l7-proxy: "true"
  enable-local-redirect-policy: "false"
  enable-masquerade-to-route-source: "false"
  enable-metrics: "true"
  enable-policy: default
  enable-remote-node-identity: "true"
  enable-runtime-device-detection: "true"
  enable-sctp: "false"
  enable-svc-source-range-check: "true"
  enable-vtep: "false"
  enable-well-known-identities: "false"
  enable-xt-socket-fallback: "true"
  eni-tags: '{}'
  external-envoy-proxy: "false"
  hubble-disable-tls: "false"
  hubble-export-file-max-backups: "5"
  hubble-export-file-max-size-mb: "10"
  hubble-listen-address: :4244
  hubble-metrics: dns:query;ignoreAAAA drop:sourceContext=workload-name|pod-name|ip;destinationContext=workload-name|pod-name|dns|ip;labelsContext=source_namespace,destination_namespace
    tcp flow:sourceContext=workload-name|pod-name|ip;destinationContext=workload-name|pod-name|dns|ip;labelsContext=source_namespace,destination_namespace
    icmp http
  hubble-metrics-server: :9965
  hubble-socket-path: /var/run/cilium/hubble.sock
  hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
  hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
  hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
  identity-allocation-mode: crd
  identity-gc-interval: 15m0s
  identity-heartbeat-timeout: 30m0s
  install-no-conntrack-iptables-rules: "false"
  instance-tags-filter: kubernetes.io/cluster/ip-eks-stage=owned
  ipam: eni
  ipam-cilium-node-update-rate: 15s
  k8s-client-burst: "20"
  k8s-client-qps: "10"
  kube-proxy-replacement: "true"
  kube-proxy-replacement-healthz-bind-address: ""
  max-connected-clusters: "255"
  mesh-auth-enabled: "true"
  mesh-auth-gc-interval: 5m0s
  mesh-auth-queue-size: "1024"
  mesh-auth-rotated-identities-queue-size: "1024"
  monitor-aggregation: medium
  monitor-aggregation-flags: all
  monitor-aggregation-interval: 5s
  node-port-bind-protection: "true"
  nodes-gc-interval: 5m0s
  operator-api-serve-addr: 127.0.0.1:9234
  operator-prometheus-serve-addr: :9963
  policy-audit-mode: "false"
  policy-cidr-match-mode: ""
  preallocate-bpf-maps: "false"
  procfs: /host/proc
  prometheus-serve-addr: :9962
  proxy-connect-timeout: "2"
  proxy-max-connection-duration-seconds: "0"
  proxy-max-requests-per-connection: "0"
  proxy-prometheus-port: "9964"
  remove-cilium-node-taints: "true"
  routing-mode: native
  service-no-backend-response: reject
  set-cilium-is-up-condition: "true"
  set-cilium-node-taints: "true"
  sidecar-istio-proxy-image: cilium/istio_proxy
  skip-cnp-status-startup-clean: "false"
  subnet-ids-filter: subnet-0b1aa525788de8a9c subnet-0449b556e3d2e0689 subnet-09b9e3a77f7db3b32
  synchronize-k8s-nodes: "true"
  tofqdns-dns-reject-response-code: refused
  tofqdns-enable-dns-compression: "true"
  tofqdns-endpoint-max-ip-per-hostname: "50"
  tofqdns-idle-connection-grace-period: 0s
  tofqdns-max-deferred-connection-deletes: "10000"
  tofqdns-proxy-response-max-delay: 100ms
  unmanaged-pod-watcher-interval: "15"
  update-ec2-adapter-limit-via-api: "true"
  vtep-cidr: ""
  vtep-endpoint: ""
  vtep-mac: ""
  vtep-mask: ""
  write-cni-conf-when-ready: /host/etc/cni/net.d/05-cilium.conflist
```

### Anything else?

_No response_

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #33672: DNS Proxy opens multiple upstream TCP connections for a single downstream connection
# Motivation

As part of investigating https://github.com/cilium/cilium/issues/31197, @gandro and I realized that the TCP proxying of DNS queries opens multiple TCP connections to the upstream server, one for each query by the downstream client.

[In transparent mode](https://github.com/cilium/cilium/pull/28928), this breaks in interesting ways, as trying to open multiple TCP connections using the same source port is not really a well-supported use case. (Wireshark will flag TCP traffic for reusing the local port; we've seem to have found a kernel bug related to this, ...)

Even without transparent mode, creating multiple TCP connections to upstream is inefficient. [The relevant RFC](https://datatracker.ietf.org/doc/html/rfc7766) recommends reusing connections.

## Head-of-line Blocking

While investigating the existing TCP handling loop, it became clear that the current code was suffering from head-of-line blocking. The TCP server loops reads a query from the client and synchronously executes the handler callback. In our case, this meant establishing the upstream connection, exchanging query/response, tearing it down and only then reading the next query - leading to severly degraded performance.

# Goals

- Instead of opening multiple upstream TCP connections, the DNS proxy should tie the lifecycle of it's upstream/server connection to the lifecycle of the downstream/client connection.
- Avoid Head-of-line blocking by pipelining

## Non-goals

- Change the flow of UDP DNS traffic. DNS over TCP is expected to be vastly less often used than UDP, and there's little reason to change the UDP flow. 

# Design

Currently, the DNS handling code (mostly) abstracts over whether the incoming query has reached the proxy via UDP or TCP. The code uses the DNS server provided by the `cilium/dns` (our fork of `miekg/dns`), which is structured similar to `net/http` - we only have to provde a handler, implementing `ServeDNS(w ResponseWriter, m *Msg)`. This query/response orientation leads to simple implementations in most cases, but it does not easily allow for our plans - differentiating between UDP and TCP, as well as getting the open/close signals of the TCP connection are possible (by wrapping the listeners and providing custom readers), but cumbersome.

We've thought of the following three approaches to achieve the stated goals:

1. (Least effort, most tech debt) Solve the head-of-line blocking problem by replacing the serve loop of the TCP server. The underlying code assumes to be called concurrently anyway, so in theory this should just work. The remaining problem is tying the lifecycle of the shared client to the TCP connection, which replacing the serve loop also helps with since we trivially have access to the underlying connection. Altering the shared client to only perform ref-counting for UDP seems doable, though inelegant. Threading through the close signal would muddle the request/reply abstraction somewhat. Given those two flaws, I'd argue this approach is adding tech debt. The shared client code is complex as is, differentiating between TCP/UDP (which it is supposed to abstract over) seems suboptimal.
2. (Medium effort, architecturally somewhat inelegant) Separate the control flow for TCP and UDP, by moving away from a request/reply model in the TCP case and instead act more like a TCP proxy with some added business logic. A typical TCP proxy is represented by two goroutines, writing from downstream to upstream and the reverse. In our case, we'd have these same two goroutines, and a bit of shared state (`lock.Map[DNSReqID, RequestContext]`), but the goroutines would not only copy bytes, but also handle the policy logic of the DNS proxy. The drawback is that we have to split up outgoing and incoming policy logic, which arguably makes understanding it harder. The benefit is that both problems identified are easily solved.
3. (Most effort/difficulty) Think hard and figure out a new abstraction which solves the identified issues while keeping the request/reply model in-place. It's unclear to me at the moment whether I'll succeed in finding a way to unify the differences between TCP&UDP in a way which does not give rise to new bugs, but the pay-off would be that the policy logic is not muddled.

I'm leaning towards 2, with the argument that the business logic split for outgoing/incoming traffic is a natural one, whereas the downsides of 1 and the difficulty of 3 deter me from these approaches.

### PR DESCRIPTION
**Pull request by bimmlerd**
This is a slightly involved one, please review commit by commit and read the commit messages for details.

Fixes: #31197 

```release-note
Fixes DNS proxy "connect: cannot assign requested address" errors in transparent mode, which were due to opening multiple TCP connections to the upstream DNS server.
```

### CODE REVIEW

File: pkg/fqdn/dnsproxy/shared_client.go [hunk 1]
```diff
@@ -41,6 +46,35 @@ func (s *SharedClients) ExchangeContext(ctx context.Context, key string, conf *d
...
+	client := s.clients[key]
+	if client == nil {
+		return
+	}
+	s.lock.Unlock()
+
+	client.Lock()
+	defer client.Unlock()
+	client.refcount--
+	if client.refcount == 0 {
```
Comment (tamilmani1989) [inline pkg/fqdn/dnsproxy/shared_client.go:63]: what's the use of refCount and when refCount will be incremented or decremented?

File: pkg/fqdn/dnsproxy/shared_client.go [hunk 2]
```diff
@@ -0,0 +1,357 @@
...
+				return
+			}
+			start := time.Now()
+
+			// Check if we already have a request with the same id
+			// Due to birthday paradox and the fact that ID is uint16
+			// it's likely to happen with small number (~200) of concurrent requests
+			// which would result in goroutine leak as we would never close req.ch
+			if _, duplicate := waitingResponses[req.msg.Id]; duplicate {
+				for n := 0; n < 5; n++ {
```
Comment (tamilmani1989) [inline pkg/fqdn/dnsproxy/shared_client.go:279]: is 5 randomly chosen?

File: pkg/fqdn/dnsproxy/shared_client.go [hunk 3]
```diff
@@ -0,0 +1,357 @@
...
+			}
+
+			// send error response to cancel all current requests.
+			responses <- sharedClientResponse{nil, 0, err}
+
+			// wait for a trigger from the handler after any errors. Re-reading in
+			// this condition could busy loop, e.g., if a read timeout occurred.
+			// receiverTrigger is buffered so that we catch the trigger that may
+			// have been sent while we sent the error response above.
+			_, ok := <-receiverTrigger
```
Comment (tamilmani1989) [inline pkg/fqdn/dnsproxy/shared_client.go:236]: why don't this be moved to top of for loop and remove the one outside for loop?

File: pkg/fqdn/dnsproxy/shared_client.go (hunk 1 above)
Comment (bimmlerd) [reply pkg/fqdn/dnsproxy/shared_client.go:63]: The `refCount` (reference count) is increased on acquiring the shared client. In the case of UDP: whenever a query arrives, the `key` is derived from the five-tuple. If a shared client with that key is known, a reference to it is acquired (increasing the `refCount`), otherwise a new client is allocated. Once the query has a response, the shared client reference is released (and `refCount` decreases). 
For TCP, after this change, the reference count is not strictly needed, as we lifecycle the client together with the downstream connection - if a downstream connection (from an EP) comes in, we open a corresponding upstream conn, once it is closed, we close the upstream conn.

We need to be careful to do this reference counting primarily for the transparent mode, to avoid attempting to allocate sockets with IP pairs we already have a socket for, since linux will throw an error otherwise.

Note that the method you commented on is specific to TCP. For why this specialisation was necessary, please read the second commit message.

File: pkg/fqdn/dnsproxy/shared_client.go (hunk 2 above)
Comment (bimmlerd) [reply pkg/fqdn/dnsproxy/shared_client.go:279]: I've chosen to change `shared_client.go` as little as possible from the code in `cilium/dns` that's in use today, since minimal changes are encouraged. Hence please see https://github.com/cilium/dns/pull/13 for details on this code.

File: pkg/fqdn/dnsproxy/shared_client.go (hunk 3 above)
Comment (bimmlerd) [reply pkg/fqdn/dnsproxy/shared_client.go:236]: That would not be equivalent: we'd block on `receiverTrigger` in every loop iteration, whereas we currently can hit the `continue` case which does not involve the `receiverTrigger`

File: pkg/fqdn/dnsproxy/shared_client.go (hunk 1 above)
Comment (tamilmani1989) [reply pkg/fqdn/dnsproxy/shared_client.go:63]: Thanks for the detailed explanation. So in case of udp, if multiple queries from same client comes in parallel, then refcount is incremented and same upstream connection is used but if query comes one after other, then new upstream connection is spawned every time as previous connection would be closed. 
A naive question: if downstream is UDP, then upstream should be UDP and there wont be mix like downstream udp and upstream tcp?

File: pkg/fqdn/dnsproxy/shared_client.go (hunk 3 above)
Comment (tamilmani1989) [reply pkg/fqdn/dnsproxy/shared_client.go:236]: yep, sorry my bad. didn't see continue case

File: pkg/fqdn/dnsproxy/shared_client.go (hunk 1 above)
Comment (bimmlerd) [reply pkg/fqdn/dnsproxy/shared_client.go:63]: > So in case of udp, if multiple queries from same client comes in parallel, then refcount is incremented and same upstream connection is used but if query comes one after other, then new upstream connection is spawned every time as previous connection would be closed.

Yes, pretty much. Queries will typically come in in rapid succession due to DNS clients often querying for A and AAAA records immediately. Also, in the case of UDP, it's mildly misleading to speak of "connections" since UDP doesn't have that concept - de facto we mean the socket towards upstream which is bound to the EP source address/port (!) in transparent mode. 

> if downstream is UDP, then upstream should be UDP and there wont be mix like downstream udp and upstream tcp?

Yes. The proxy will forward the query to upstream using the same protocol as the client used.

File: pkg/fqdn/dnsproxy/shared_client.go [hunk 4]
```diff
@@ -0,0 +1,357 @@
...
+			close(waiter.ch)
+		}
+	}()
+
+	for {
+		select {
+		case req, ok := <-requests:
+			if !ok {
+				// 'requests' is closed when SharedClient is recycled, which happens
+				// responeses (or errors) have been received and there are no more
```
Comment (doniacld) [inline pkg/fqdn/dnsproxy/shared_client.go]: nit: responses

File: pkg/fqdn/dnsproxy/shared_client.go [hunk 5]
```diff
@@ -0,0 +1,357 @@
...
+	close(c.requests)
+	c.wg.Wait()
+	c.conn = nil
+}
+
+// Return the appropriate timeout for a specific request
+func getTimeoutForRequest(c *dns.Client) time.Duration {
+	wtimeout := c.WriteTimeout
+	if wtimeout == 0 {
+		wtimeout = time.Second * 2
```
Comment (doniacld) [inline pkg/fqdn/dnsproxy/shared_client.go:380]: Why did you choose 2 seconds here?

**Review by doniacld — APPROVED** [review]
Only 2 comment/question! Great job!

File: pkg/fqdn/dnsproxy/shared_client.go (hunk 5 above)
Comment (bimmlerd) [reply pkg/fqdn/dnsproxy/shared_client.go:380]: I didn't, this was the default in miekg/dns 🙃  Added a comment to that effect.

**Comment by bimmlerd** [comment]
Marking this for 1.16 backport since it's a bug, but I wouldn't call it a major bugfix (since DNS over TCP isn't incredibly common).

**Comment by bimmlerd** [comment]
The bugfix PR is merged, and hence this should be backported together.
