### PR TITLE
test: Fix fragment tracking test on GKE

### LINKED ISSUE #14652: CI: K8sServicesTest Checks service across nodes Supports IPv4 fragments failing with endpoint routes enabled
The fragment tracking test is currently failing on GKE, with zero fragments received at the destination. The issue can be easily reproduced by enabling test [`Supports IPv4 fragments`](https://github.com/cilium/cilium/blob/6e3ca8f84e643200203aec24b4310ec71c403942/test/k8sT/Services.go#L2594) on GKE.

Related: https://github.com/cilium/cilium/pull/14639

### PR DESCRIPTION
**Pull request by pchaigno**
The fragment tracking test was disabled on GKE because [it is incompatible with endpoint routes](https://github.com/cilium/cilium/issues/15958). Until that incompatibility is fixed, we can disable endpoint routes when running on GKE.

Fixes: https://github.com/cilium/cilium/issues/14652.

### CODE REVIEW

**Comment by pchaigno** [comment]
test-gke

**Review by qmonnet — APPROVED** [review]
Looks good, thanks!

**Review by nbusseneau — APPROVED** [review]

File: test/k8sT/Services.go [hunk 1]
```diff
@@ -2909,9 +2909,16 @@ Secondary Interface %s :: IPv4: (%s, %s), IPv6: (%s, %s)`, helpers.DualStackSupp
 		// Run on net-next and 4.19 but not on old versions, because of
 		// LRU requirement.
 		SkipItIf(func() bool {
-			return helpers.DoesNotRunOn419OrLaterKernel() || helpers.RunsOnGKE()
+			return helpers.DoesNotRunOn419OrLaterKernel()
 		}, "Supports IPv4 fragments", func() {
-			DeployCiliumAndDNS(kubectl, ciliumFilename)
+			options := map[string]string{}
+			// On GKE we need to disable endpoint routes as fragment tracking
```
Comment (aditighag) [inline test/k8sT/Services.go:2915]: Why don't we deploy Cilium with the following options instead? No preference either way, I'm just trying to understand if there is more to it than setting the `endpointroutes` option.
	
```
options := map[string]string{
				"endpointRoutes.enabled": "false",
			}
```

Comment (pchaigno) [reply test/k8sT/Services.go:2915]: Good question. That's what I tried first, the first time I disabled endpoint routes on GKE, but it just gets overwritten by `gke.enabled`. So we have to instead disable `gke.enable` to let `endpointRoutes.enabled` take its default value (false).

**Comment by pchaigno** [comment]
GKE is passing and team reviews are covered. Marking as ready to merge.

File: test/k8sT/Services.go (hunk 1 above)
Comment (aditighag) [reply test/k8sT/Services.go:2915]: Thanks, it might be worth mentioning this in the code.

**Review by aditighag — APPROVED** [review]
