### PR TITLE
bpf: Fix proxy redirection for egress programs

### LINKED ISSUE #9429: Bootstrapping on AKS fails
I already touched on this issue with @aanm:

When we bootstrap an AKS cluster according to [the installation guide](https://docs.cilium.io/en/latest/gettingstarted/k8s-install-aks/) the connectivity test fails because the containers on one node cannot reach containers on other nodes which causes the readiness check to fail:

```
Events:
  Type     Reason     Age                From                                        Message
  ----     ------     ----               ----                                        -------
  Normal   Scheduled  93s                default-scheduler                           Successfully assigned default/probe-7df8579c88-q95px to aks-nodepool1-42326083-vmss000000
  Normal   Pulling    91s                kubelet, aks-nodepool1-42326083-vmss000000  Pulling image "docker.io/cilium/json-mock"
  Normal   Pulled     80s                kubelet, aks-nodepool1-42326083-vmss000000  Successfully pulled image "docker.io/cilium/json-mock"
  Normal   Created    79s                kubelet, aks-nodepool1-42326083-vmss000000  Created container probe-container
  Normal   Started    78s                kubelet, aks-nodepool1-42326083-vmss000000  Started container probe-container
  Warning  Unhealthy  16s (x2 over 48s)  kubelet, aks-nodepool1-42326083-vmss000000  Liveness probe failed: curl: (6) Could not resolve host: echo.default.svc.cluster.local
```
and this is the corresponding pod list:
```
NAME                     READY   STATUS    RESTARTS   AGE   IP            NODE                                NOMINATED NODE   READINESS GATES                                                                                              echo-6459757d96-8jrj2    1/1     Running   0          79s   10.240.0.22   aks-nodepool1-42326083-vmss000000   <none>           <none>                                                                                                       echo-6459757d96-cxmdf    1/1     Running   0          79s   10.240.0.38   aks-nodepool1-42326083-vmss000001   <none>           <none>                                                                                                       echo-6459757d96-hbrq7    1/1     Running   0          79s   10.240.0.39   aks-nodepool1-42326083-vmss000001   <none>           <none>                                                                                                       echo-6459757d96-pds47    1/1     Running   0          79s   10.240.0.31   aks-nodepool1-42326083-vmss000000   <none>           <none>                                                                                                       echo-6459757d96-qlwj6    1/1     Running   0          79s   10.240.0.18   aks-nodepool1-42326083-vmss000000   <none>           <none>                                                                                                       probe-7df8579c88-2w9xf   1/1     Running   0          79s   10.240.0.16   aks-nodepool1-42326083-vmss000000   <none>           <none>                                                                                                       probe-7df8579c88-bdw9t   0/1     Running   0          79s   10.240.0.47   aks-nodepool1-42326083-vmss000001   <none>           <none>                                                                                                       probe-7df8579c88-d58sp   1/1     Running   0          79s   10.240.0.63   aks-nodepool1-42326083-vmss000001   <none>           <none>                                                                                                       probe-7df8579c88-k5c9d   1/1     Running   0          79s   10.240.0.37   aks-nodepool1-42326083-vmss000001   <none>           <none>                                                                                                       probe-7df8579c88-q95px   0/1     Running   0          79s   10.240.0.26   aks-nodepool1-42326083-vmss000000   <none>           <none>
```
I deployed the 1.6.3 version!
Do you guys have any further information on this issue, a workaround or something else that could help me?

### LINKED ISSUE #9794: DNS proxy denies traffic with "L3 Denied" on AKS with CNI chaining
Community report from Slack:

Environment: AKS with CNI chaining
Cilium: v1.6.5

### Summary

When applying an L4 policy, the traffic is allowed. However when adding an L7 allow-all policy, the traffic is then denied with `Policy denied (L3)`.

### More detail

Policy applied in default namespace:

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "enable-dns-egress"
spec:
  endpointSelector:
    matchLabels: {}
  egress:
  - toEndpoints:
    - matchLabels:
       "k8s:io.kubernetes.pod.namespace": kube-system
       "k8s:k8s-app": kube-dns
    toPorts:
      - ports:
         - port: '53'
           protocol: ANY
        rules:
          dns:
            - matchPattern: "*"
```

> After applying policy dns resolution doesn't work and with cilium monitor I can see dropped packages.

```
xx drop (Policy denied (L3)) flow 0x8e9cdc7a to endpoint 0, identity 63754->55258: 172.23.85.46 -> 172.23.85.24 DestinationUnreachable(Port)
xx drop (Policy denied (L3)) flow 0x8e9cdc7a to endpoint 0, identity 63754->55258: 172.23.85.46 -> 172.23.85.24 DestinationUnreachable(Port)
xx drop (Policy denied (L3)) flow 0x8e9cdc7a to endpoint 0, identity 63754->55258: 172.23.85.46 -> 172.23.85.24 DestinationUnreachable(Port)
```

Identity 63754 is my probe pod, 55258 is the core-dns pod.

If I remove L7 rule, then DNS resolution works, but L3 DNS based doesn't:

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "enable-dns-egress"
spec:
  endpointSelector:
    matchLabels: {}
  egress:
  - toEndpoints:
    - matchLabels:
       "k8s:io.kubernetes.pod.namespace": kube-system
       "k8s:k8s-app": kube-dns
    toPorts:
      - ports:
         - port: '53'
           protocol: ANY
```

### LINKED ISSUE #10105: Egress proxy redirection broken with EndpointRoutes enabled
How to reproduce:
1. Follow ENI installation guide
2. Run https://github.com/cilium/cilium/pull/10104
3. `pod-to-a-fqdn-allow-google-cnp` will fail

## Analysis of code:
1. In EndpointRoutes mode, `handle_to_container` section is called at egress of `lxc+` veth pair. This hook is passed after any potential iptables chain.
2. `ipv4_policy()` is called to handle ingress policy and proxy redirection needs of the pod.
3. The conntrack table is consulted to see if the connection was subject to egress proxy redirection:
   ```
        // Check it this is return traffic to an egress proxy.
        // Do not redirect again if the packet is coming from the egress proxy.
        if ((ret == CT_REPLY || ret == CT_RELATED) && ct_state.proxy_redirect &&
            !tc_index_skip_egress_proxy(skb)) {
                // Stack will do a socket match and deliver locally
                return skb_redirect_to_proxy(skb, 0);
        }
   ```
4. This returns `TC_ACT_OK` after changing the type to `PACKET_HOST` as `HOST_REDIRECT_TO_INGRESS` is only enabled for the flannel integration:
   ```
       static inline int __inline__
        skb_redirect_to_proxy(struct __sk_buff *skb, __be16 proxy_port)
        {
                skb->mark = MARK_MAGIC_TO_PROXY | proxy_port << 16;

        #ifdef HOST_REDIRECT_TO_INGRESS
                cilium_dbg_capture(skb, DBG_CAPTURE_PROXY_PRE, proxy_port);
                /* In this case, the DBG_CAPTURE_PROXY_POST will be sent from the
                 * programm attached to HOST_IFINDEX. */
                return redirect(HOST_IFINDEX, BPF_F_INGRESS);
        #else
                cilium_dbg_capture(skb, DBG_CAPTURE_PROXY_POST, proxy_port);
                skb_change_type(skb, PACKET_HOST); // Required for ingress packets from overlay
                return TC_ACT_OK;
        #endif
        }
   ```
5. This will have skipped service reverse-translation and proxy redirection for reply packets and will result in ICMP port unreachable messages to be emitted to due non-matching 5-tuple.

### PR DESCRIPTION
**Pull request by tgraf**
The `to-conatiner` section of bpf_lxc included a broken proxy redirection logic
which lead to an ineffective proxy redirection when EnableEndpointRoutes was
set.

The required hairpin redirection logic already existed but was only applied for
ingress rules and not for reply traffic of an egress rule.

Fixes: #10105
Fixes: #9794
FIxes: #9429

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10113)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
Rebased

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
Known flake `Suite-k8s-1.17.K8sPolicyTest Basic Test TLS policy` failed. All other tests passed.

File: bpf/lib/common.h [hunk 1]
```diff
@@ -287,6 +287,9 @@ enum {
  */
 #define IPSEC_ENDPOINT TC_ACT_OK
 
+/* Indicates that proxy redirection is required */
+#define TC_ACT_PROXY_REDIRECT (1 << 16)
```
Comment (joestringer) [inline bpf/lib/common.h]: `TC_ACT_*` suggests that this is an action that TC understands. This is not a TC command.

```suggestion
#define POLICY_ACT_PROXY_REDIRECT (1 << 16)
```

**Review by joestringer — CHANGES_REQUESTED** [review]
This would be a lot easier to understand with refactoring and functional changes in separate commits.

If I follow correctly, the functional changes are:
* `tail_ipv6_to_endpoint()` previously used the standard `skb_redirect_to_proxy()` but now uses `skb_redirect_to_proxy_hairpin()`. This likely fixes IPv6 connectivity with proxy.
* `ipv4_policy()` previously used to unconditionally return TC_ACT_OK rather than using the common `skb_redirect_to_proxy()` logic (broken in 25a80dfdd5e2232a6c0feb2ac048ad60c1f08714). This means that in `HOST_REDIRECT_TO_INGRESS` mode it was not redirecting correctly, and in regular mode the skb would not be set to `PACKET_HOST`. Should not affect endpoint routes mode at all.

I don't see any other changes. Is this what you expect? Did I miss something?

Minor nit below, it's misleading to call this intermediate return code as `TC_*` as TC has no knowledge of this value.

File: bpf/bpf_lxc.c [hunk 2]
```diff
@@ -1023,8 +1030,9 @@ ipv4_policy(struct __sk_buff *skb, int ifindex, __u32 src_label, __u8 *reason, _
 	// Do not redirect again if the packet is coming from the egress proxy.
 	if ((ret == CT_REPLY || ret == CT_RELATED) && ct_state.proxy_redirect &&
 	    !tc_index_skip_egress_proxy(skb)) {
-		// Stack will do a socket match and deliver locally
-		return skb_redirect_to_proxy(skb, 0);
+		send_trace_notify(skb, TRACE_TO_PROXY, src_label, SECLABEL,
+				  0, ifindex, *reason, monitor);
+		return TC_ACT_PROXY_REDIRECT;
```
Comment (joestringer) [inline bpf/bpf_lxc.c]: The implicit set of `*proxy_port` to zero here is a little surprising, IMO that should be explicitly called out somehow.

File: bpf/bpf_lxc.c [hunk 3]
```diff
@@ -835,8 +835,7 @@ ipv6_policy(struct __sk_buff *skb, int ifindex, __u32 src_label, __u8 *reason)
 	// Do not redirect again if the packet is coming from the egress proxy.
 	if ((ret == CT_REPLY || ret == CT_RELATED) && ct_state.proxy_redirect &&
 	    !tc_index_skip_egress_proxy(skb)) {
-		// Stack will do a socket match and deliver locally
-		return skb_redirect_to_proxy(skb, 0);
+		return TC_ACT_PROXY_REDIRECT;
```
Comment (joestringer) [inline bpf/bpf_lxc.c]: We should make this the same as the IPv4:
* Same trace message
* It's also redirecting with `*proxy_port` set as 0, which should be called out either in code or in comment

**Review by joestringer — CHANGES_REQUESTED** [review]
Couple of other minor nits. I still didn't see the primary proxy change here outside IPv6.

**Comment by tgraf** [comment]
> This would be a lot easier to understand with refactoring and functional changes in separate commits.

There are no intentional refactorings in this commit.

> * `tail_ipv6_to_endpoint()` previously used the standard `skb_redirect_to_proxy()` but now uses `skb_redirect_to_proxy_hairpin()`. This likely fixes IPv6 connectivity with proxy.

Correct and the proxy redirect for the egress case was missing entirely.

> ipv4_policy() previously used to unconditionally return TC_ACT_OK rather than using the common skb_redirect_to_proxy() logic (broken in 25a80df). This means that in HOST_REDIRECT_TO_INGRESS mode it was not redirecting correctly, and in regular mode the skb would not be set to PACKET_HOST. Should not affect endpoint routes mode at all.

 25a80df correctly introduced the hairpin by moving he proxy redirect into the caller of `ipv4_policy()` so a different action could be taken for egress and ingress. 830adba1c0 broke EndpointRoutes by returning TC_ACT_OK the egress program case without setting proxy_port, assuming that a BPF program is always followed by a PREROUTING chain which is not the case for egress. This resulted in packets that were supposed to be redirected to the proxy to be passed straight into the pod, bypassing policy and service lookup.

I'll fix up the commit message to make this clear.

File: bpf/bpf_lxc.c (hunk 2 above)
Comment (tgraf) [reply bpf/bpf_lxc.c]: I don't quite follow this comment. Are you talking about the trace message or the caller of `ipv4_policy()` still redirecting?

Comment (joestringer) [reply bpf/bpf_lxc.c]: I was looking at the previous equivalent code, `skb_redirect_to_proxy(..., 0)` where the port is set to zero because the stack already knows that it needs to receive packets for this tuple and hence we don't need to embed the port into the `skb->mark` (which would otherwise match the tproxy rules and then zero the port portion of the mark).

This kind of detail where this path relies upon passing the port back as zero seems really easy to miss if we subsequently refactor.

**Comment by joestringer** [comment]
Thanks for the explanation, makes sense.

**Comment by tgraf** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
Rebased

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
Waiting for runtime tests to pass before rebasing again
