### PR TITLE
bpf: Check native-routing-cidr in BPF masquerade

### LINKED ISSUE #11464: Use native-routing-cidr in BPF masq
Currently, the BPF masq depends on ipcache when making a decision whether a packet has to be SNAT'd. However, the ipcache might take time to update which leads to unexpected SNAT when sending to a pod running on a remote node.

We should add a check to datapath for `native-routing-cidr` which would solve the problem above.

### PR DESCRIPTION
**Pull request by brb**
This commit extends the BPF masquerade by adding a check for whether a dst IPv4 addr is in `native-routing-cidr`.

The check fixes a problem when a node hasn't received an ipcache update for a pod running on a remote node, and thus a packet sent from a local pod to that pod is SNAT'd (this happens because the dst is considered as `WORLD_ID` until the update has been received).

Fix #11464.

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
4.9 CI hit https://github.com/cilium/cilium/issues/11457.

**Comment by brb** [comment]
retest-4.9

File: bpf/lib/nodeport.h [hunk 1]
```diff
@@ -763,6 +763,13 @@ static __always_inline bool nodeport_nat_ipv4_needed(struct __ctx_buff *ctx,
 			struct remote_endpoint_info *info;
 			*from_endpoint = true;
 
+#ifdef IPV4_NATIVE_ROUTING_CIDR
+			if (ipv4_is_in_subnet(ip4->daddr,
+					      IPV4_NATIVE_ROUTING_CIDR,
+					      IPV4_NATIVE_ROUTING_CIDR_LEN))
+				return false;
+#endif
```
Comment (borkmann) [inline bpf/lib/nodeport.h]: Can't we save the cycles of the map lookup and do this before `__lookup_ip4_endpoint()`?

Comment (brb) [reply bpf/lib/nodeport.h]: `__lookup_ip4_endpoint()` is for detecting whether src is a local pod, while the added native-routing-cidr check is for detecting whether dst is a pod in a cluster (local or remote).

**Review by tgraf — APPROVED** [review]

**Comment by brb** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]

**Comment by brb** [comment]
retest-runtime

**Comment by brb** [comment]
retest-4.19

**Comment by brb** [comment]
retest-runtime

**Comment by brb** [comment]
retest-4.19
