### PR TITLE
daemon: log errors from bpf.TestDummyProg()

### LINKED ISSUE #15448: Log errors from bpf.TestDummyProg
We currently rely on our function `bpf.TestDummyProg` to probe kernel support for some BPF hooks:
https://github.com/cilium/cilium/blob/08d0af46e46d460f87b506933c3701704ec52d8f/daemon/cmd/kube_proxy_replacement.go#L231-L250

When this function fails, we should log the returned error with `log.WithError(err)`.

### PR DESCRIPTION
**Pull request by rgo3**
Previously we just checked if bpf.TestDummyProg() returns an error.

Now the error is logged so it is easier to debug what actually happened
if bpf.TestDummyProg() fails.

Fixes: #15448

Signed-off-by: Robin Gögge <r.goegge@outlook.com>

### CODE REVIEW

File: daemon/cmd/kube_proxy_replacement.go [hunk 1]
```diff
@@ -228,33 +228,71 @@ func initKubeProxyReplacementOptions() (strict bool) {
...
-			if strict {
-				log.Fatal(msg)
-			} else {
-				option.Config.EnableHostServicesTCP = false
-				log.Warn(msg + " Disabling the feature.")
+		if option.Config.EnableHostServicesTCP {
+			var disableHostServicesTCP bool
+			if option.Config.EnableIPv4 {
+				if err := bpf.TestDummyProg(bpf.ProgTypeCgroupSockAddr, bpf.BPF_CGROUP_INET4_CONNECT); err != nil {
+					log.WithError(err)
```
Comment (pchaigno) [inline daemon/cmd/kube_proxy_replacement.go]: You need to assign this (typically `scopedLog`) or it won't take effect for when you issue the fatal/warning.

File: daemon/cmd/kube_proxy_replacement.go [hunk 2]
```diff
@@ -228,33 +228,71 @@ func initKubeProxyReplacementOptions() (strict bool) {
...
+
+			if disableHostServicesTCP {
+				msg := "BPF host reachable services for TCP needs kernel 4.17.0 or newer."
+				if strict {
+					log.Fatal(msg)
+				} else {
+					option.Config.EnableHostServicesTCP = false
+					log.Warn(msg + " Disabling the feature.")
+				}
 			}
```
Comment (pchaigno) [inline daemon/cmd/kube_proxy_replacement.go]: Maybe this could be refactored to use a function such as `probeCgroupSupport(tcp, ipv6 bool)`. We should then only call:
```go
if option.Config.EnableHostServicesTCP && option.Config.EnableIPv4 {
    probeCgroupSupport(true, false)
}
if option.Config.EnableHostServicesTCP && option.Config.EnableIPv6 {
    probeCgroupSupport(true, true)
}
if option.Config.EnableHostServicesUDP && option.Config.EnableIPv4 {
    probeCgroupSupport(false, false)
}
if option.Config.EnableHostServicesUDP && option.Config.EnableIPv6 {
    probeCgroupSupport(false, true)
}
```
The logic would also be the same as the original code as we would fatal as soon as we find something missing.

**Review by pchaigno — CHANGES_REQUESTED** [review]
Thanks for the pull request!

A couple of changes required below.

File: daemon/cmd/kube_proxy_replacement.go (hunk 2 above)
Comment (rgo3) [reply daemon/cmd/kube_proxy_replacement.go]: I was worried that the code had blown up a bit. I actually added two functions for refactoring now to avoid even more `if {} else {}` statements. Hope thats fine. The logic should be the same as the original code now too.

File: daemon/cmd/kube_proxy_replacement.go [hunk 3]
```diff
@@ -347,6 +345,59 @@ func initKubeProxyReplacementOptions() (strict bool) {
...
+
+	if ipv4 {
+		if err := bpf.TestDummyProg(bpf.ProgTypeCgroupSockAddr, bpf.BPF_CGROUP_INET4_CONNECT); err != nil {
+			scopedLog = log.WithError(err)
+			disableHostServicesTCP = true
+		}
+	} else {
+		if err := bpf.TestDummyProg(bpf.ProgTypeCgroupSockAddr, bpf.BPF_CGROUP_INET6_CONNECT); err != nil {
+			scopedLog = log.WithError(err)
+			disableHostServicesTCP = true
```
Comment (pchaigno) [inline daemon/cmd/kube_proxy_replacement.go]: These two lines can be moved out of the if/else block for IPv4/IPv6 and merged with the following code, such that we don't need `disableHostServicesTCP` anymore.

File: daemon/cmd/kube_proxy_replacement.go [hunk 4]
```diff
@@ -347,6 +345,59 @@ func initKubeProxyReplacementOptions() (strict bool) {
...
+
+	if ipv4 {
+		if err := bpf.TestDummyProg(bpf.ProgTypeCgroupSockAddr, bpf.BPF_CGROUP_UDP4_RECVMSG); err != nil {
+			scopedLog = log.WithError(err)
+			disableHostServicesUDP = true
+		}
+	} else {
+		if err := bpf.TestDummyProg(bpf.ProgTypeCgroupSockAddr, bpf.BPF_CGROUP_UDP6_RECVMSG); err != nil {
+			scopedLog = log.WithError(err)
+			disableHostServicesUDP = true
```
Comment (pchaigno) [inline daemon/cmd/kube_proxy_replacement.go]: Ditto.

**Review by pchaigno — COMMENTED** [review]
One minor comment below. Looks good to me otherwise.

**Comment by rgo3** [comment]
I keep force-pushing, do you prefer adding new commits to address comments and squashing them later?
In any case, addressed the comments and rebased the commit.

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
> I keep force-pushing, do you prefer adding new commits to address comments and squashing them later?

Probably best to avoid having to do a final squash as we'd then need to retrigger the end-to-end tests :-/

**Comment by rgo3** [comment]
Are the failing tests caused by what I did or are those flaky? I think I saw similar ones on other PRs too but I am too unfamiliar with the repo/CI to be able to tell.

**Comment by pchaigno** [comment]
test-1.13-netnext

**Review by christarazi — APPROVED** [review]

**Comment by pchaigno** [comment]
k8s-1.19-kernel-4.19 failed with known flake https://github.com/cilium/cilium/issues/15455; k8s-1.20-kernel-4.9 with https://github.com/cilium/cilium/pull/15487. Other CI jobs are green and team reviews are in. Marking as ready to merge.
