### PR TITLE
endpointsynchronizer: suppress context.Canceled errors

### LINKED ISSUE #12636: endpointsynchronizer logs Cannot create CEP when ep context was canceled
## Bug report
See also https://cilium.slack.com/archives/C1MATJ5U5/p1595511711300300

**General Information**

- Cilium version (run `cilium version`)
```
Client: 1.8.1 5ce2bc7b3 2020-07-02T20:04:47+02:00 go version go1.14.4 linux/amd64
Daemon: 1.8.1 5ce2bc7b3 2020-07-02T20:04:47+02:00 go version go1.14.4 linux/amd64
```
- Kernel version (run `uname -a`)
```
Linux e1-k8s-alsu120 5.7.7-1.el7.elrepo.x86_64 #1 SMP Wed Jul 1 11:53:16 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
````
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Link to relevant artifacts (policies, deployments scripts, ...)
x
- Generate and upload a system zip:
x

In one of our larger clusters we regularly see log messages from cilium similar to this one:

```
level=error msg="Cannot update CEP" containerID= controller="sync-to-k8s-ciliumendpoint (360)" datapathPolicyRevision=4920 desiredPolicyRevision=4920 endpointID=360 error="context canceled" identity=27179 ipv4= ipv6= k8sPodName=/ subsys=endpointsynchronizer
level=error msg="Cannot create CEP" containerID= controller="sync-to-k8s-ciliumendpoint (1756)" datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=1756 error="context canceled" ipv4= ipv6= k8sPodName=/ subsys=endpointsynchronizer
````
from: https://github.com/cilium/cilium/blob/a2e2fed26a6e39ca0eb395dadc3f8341d7b69d38/pkg/k8s/watchers/endpointsynchronizer.go#L164-L168
and:
https://github.com/cilium/cilium/blob/a2e2fed26a6e39ca0eb395dadc3f8341d7b69d38/pkg/k8s/watchers/endpointsynchronizer.go#L261-L264

As tgraf said in slack and as far as I can see the `context canceled` error only appears when an Endpoint backing the Pod was terminated before the CEP could be created/updated. This error should be hidden as it is not really an error, will have a look at it now and send a PR to address this.

### PR DESCRIPTION
**Pull request by ghouscht**
Fixes: #12636 

```release-note
endpointsynchronizer: suppress logging context.Canceled errors on CEP creation/update
```

Not sure about possible side effects of those two small changes, waiting for someone to provide feedback. The other approach would be to wrap the log statement within another `if err != context.Canceled` and still return the error. As far as I can see this should work, but I'm not familiar with ciliums code at all...

### CODE REVIEW

File: pkg/k8s/watchers/endpointsynchronizer.go [hunk 1]
```diff
@@ -162,7 +162,8 @@ func (epSync *EndpointSynchronizer) RunK8sCiliumEndpointSync(e *endpoint.Endpoin
 							},
 						}
 						localCEP, err = ciliumClient.CiliumEndpoints(namespace).Create(ctx, cep, meta_v1.CreateOptions{})
-						if err != nil {
+						// suppress error if ep backing the pod was terminated before CEP could be created
+						if err != nil && err != context.Canceled {
```
Comment (aanm) [inline pkg/k8s/watchers/endpointsynchronizer.go]: small nit `if err != nil && !errors.Is(err, context.Canceled) {`

File: pkg/k8s/watchers/endpointsynchronizer.go [hunk 2]
```diff
@@ -258,7 +259,7 @@ func (epSync *EndpointSynchronizer) RunK8sCiliumEndpointSync(e *endpoint.Endpoin
 
 				// Ensure we re-init when we see a generic error. This will recrate the
 				// CEP.
-				case err != nil:
+				case err != nil && err != context.Canceled:
```
Comment (aanm) [inline pkg/k8s/watchers/endpointsynchronizer.go]: small nit `if err != nil && !errors.Is(err, context.Canceled) {`

**Review by aanm — CHANGES_REQUESTED** [review]

File: pkg/k8s/watchers/endpointsynchronizer.go [hunk 3]
```diff
@@ -162,7 +163,8 @@ func (epSync *EndpointSynchronizer) RunK8sCiliumEndpointSync(e *endpoint.Endpoin
 							},
 						}
 						localCEP, err = ciliumClient.CiliumEndpoints(namespace).Create(ctx, cep, meta_v1.CreateOptions{})
-						if err != nil {
+						// suppress error if ep backing the pod was terminated before CEP could be created
+						if err != nil && !errors.Is(err, context.Canceled) {
 							scopedLog.WithError(err).Error("Cannot create CEP")
 							return err
 						}
```
Comment (aanm) [inline pkg/k8s/watchers/endpointsynchronizer.go]: Sorry, I forgot one important thing in my initial review. This means if the context is canceled that we won't return on line 169.

I assume the intention is only to suppress the verbosity of the errors, so ideally this should be:
```golang
if err != nil {
	if !errors.Is(err, context.Canceled) {
		scopedLog.WithError(err).Error("Cannot create CEP")
	}
	return err
}
```

File: pkg/k8s/watchers/endpointsynchronizer.go [hunk 4]
```diff
@@ -258,7 +260,7 @@ func (epSync *EndpointSynchronizer) RunK8sCiliumEndpointSync(e *endpoint.Endpoin
 
 				// Ensure we re-init when we see a generic error. This will recrate the
 				// CEP.
-				case err != nil:
+				case err != nil && !errors.Is(err, context.Canceled):
```
Comment (aanm) [inline pkg/k8s/watchers/endpointsynchronizer.go]: Similar here, should be:
```golang
if err != nil {
	if !errors.Is(err, context.Canceled) {
		scopedLog.WithError(err).Error("Cannot create CEP")
	}
        needInit = true
	return err
}
```

**Review by aanm — CHANGES_REQUESTED** [review]

**Review by christarazi — APPROVED** [review]
LGTM assuming Andre's latest comments are addressed

File: pkg/k8s/watchers/endpointsynchronizer.go [hunk 5]
```diff
@@ -162,7 +163,8 @@ func (epSync *EndpointSynchronizer) RunK8sCiliumEndpointSync(e *endpoint.Endpoin
 							},
 						}
 						localCEP, err = ciliumClient.CiliumEndpoints(namespace).Create(ctx, cep, meta_v1.CreateOptions{})
-						if err != nil {
+						// suppress error if ep backing the pod was terminated before CEP could be created
```
Comment (christarazi) [inline pkg/k8s/watchers/endpointsynchronizer.go]: Nit for style: Can you modify the formatting of this comment to be similar to the one on line 261?

File: pkg/k8s/watchers/endpointsynchronizer.go (hunk 3 above)
Comment (ghouscht) [reply pkg/k8s/watchers/endpointsynchronizer.go]: Whoops, good catch 👍

File: pkg/k8s/watchers/endpointsynchronizer.go (hunk 5 above)
Comment (ghouscht) [reply pkg/k8s/watchers/endpointsynchronizer.go]: Slightly changed the comment, not sure if this is what you wanted.

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
marked for 1.8 backport given it's a small change and the warning message might be annoying for users.

File: pkg/k8s/watchers/endpointsynchronizer.go [hunk 6]
```diff
@@ -163,7 +164,11 @@ func (epSync *EndpointSynchronizer) RunK8sCiliumEndpointSync(e *endpoint.Endpoin
 						}
 						localCEP, err = ciliumClient.CiliumEndpoints(namespace).Create(ctx, cep, meta_v1.CreateOptions{})
 						if err != nil {
-							scopedLog.WithError(err).Error("Cannot create CEP")
+							// Suppress logging an error if ep backing the pod was terminated
+							// before CEP could be created.
+							if !errors.Is(err, context.Canceled) {
+								scopedLog.WithError(err).Error("Cannot create CEP")
```
Comment (tgraf) [inline pkg/k8s/watchers/endpointsynchronizer.go]: Given that `context.Canceled` means that the controller is being shut down, we should just return `nil` instead of `err` as to not account for a controller failure which didn't really happen.

**Review by tgraf — CHANGES_REQUESTED** [review]

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by ghouscht** [comment]
mhh clicking `UpdateBranch` was a bad idea... now things are messed up, trying to fix...

**Review by tklauser — APPROVED** [review]

**Comment by tklauser** [comment]
test-me-please

**Comment by ghouscht** [comment]
test-me-please

**Comment by christarazi** [comment]
@ghouscht Looks like the only failure is GKE, which is expected at this time, as we are trying to improve that area. By the way, only members with commit rights can trigger CI, with `test-me-please`. :)

**Review by fristonio — APPROVED** [review]
:100:
