### PR TITLE
hubble: deflake TestLocalObserverServer_NodeLabels

### LINKED ISSUE #33273: CI: ci-integration: TestLocalObserverServer_NodeLabels
## CI failure

```
--- FAIL: TestLocalObserverServer_NodeLabels (0.00s)

    local_observer_test.go:699: 
        	Error Trace:	/home/runner/work/cilium/cilium/pkg/hubble/observer/local_observer_test.go:699
        	            				/home/runner/work/cilium/cilium/pkg/hubble/testutils/fake.go:43
        	            				/home/runner/work/cilium/cilium/pkg/hubble/observer/local_observer.go:369
        	            				/home/runner/work/cilium/cilium/pkg/hubble/observer/local_observer_test.go:737
        	Error:      	Not equal: 
        	            	expected: []string{"kubernetes.io/arch=amd64", "kubernetes.io/hostname=ip-1-2-3-4.us-west-2.compute.internal", "kubernetes.io/os=linux", "topology.kubernetes.io/region=us-west-2", "topology.kubernetes.io/zone=us-west-2d"}
        	            	actual  : []string(nil)
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,8 +1,2 @@
        	            	-([]string) (len=5) {
        	            	- (string) (len=24) "kubernetes.io/arch=amd64",
        	            	- (string) (len=60) "kubernetes.io/hostname=ip-1-2-3-4.us-west-2.compute.internal",
        	            	- (string) (len=22) "kubernetes.io/os=linux",
        	            	- (string) (len=39) "topology.kubernetes.io/region=us-west-2",
        	            	- (string) (len=38) "topology.kubernetes.io/zone=us-west-2d"
        	            	-}
        	            	+([]string) <nil>
        	            	 
        	Test:       	TestLocalObserverServer_NodeLabels
```

- Observed in https://github.com/cilium/cilium/pull/33237
- CI run: https://github.com/cilium/cilium/actions/runs/9594579558/job/26457473354
- Likely cause https://github.com/cilium/cilium/pull/32851

### PR DESCRIPTION
**Pull request by kaworu**
Before this patch, `TestLocalObserverServer_NodeLabels` was flaky because it didn't wait on the `localNodeWatcher` to have been updated at least once before using it.

This commit makes `NewLocalNodeWatcher` retrieve the local node info so that the returned `LocalNodeWatcher` is usable right away. This means that the Hubble startup will block until the `LocalNodeStore` is ready with local node info, which in practice should not be an issue.

fix #33273

### CODE REVIEW

File: pkg/hubble/observer/local_node_watcher.go [hunk 1]
```diff
@@ -17,21 +17,25 @@ import (
...
 
 // NewLocalNodeWatcher return a new LocalNodeWatcher. The given context control
 // whether the LocalNodeWatcher gets updated by the localNodeStream. It is safe
 // to use the returned LocalNodeWatcher once the context is cancelled, but its
 // information might be out-of-date.
 func NewLocalNodeWatcher(ctx context.Context, localNodeStream stream.Observable[node.LocalNode]) *LocalNodeWatcher {
-	watcher := LocalNodeWatcher{}
+	watcher := LocalNodeWatcher{
+		init: make(chan struct{}),
+	}
```
Comment (gandro) [inline pkg/hubble/observer/local_node_watcher.go:36]: I wonder if it would be possible to call `LocalNodeStore.Get()` here to block the creation of the this wrapper until the local node information is available. That way the callers could assume that the information is always here.

It would block Hubble until local node information is available, but I think that's fine

**Review by gandro — APPROVED** [review]
Looks good to me, though there might be an alternative approach

File: pkg/hubble/observer/local_node_watcher.go (hunk 1 above)
Comment (kaworu) [reply pkg/hubble/observer/local_node_watcher.go:36]: Yes I thought about it and decided that the feature wasn't important enough to block the Hubble startup. My thinking was also that it shouldn't be designed around tests.

On the other hand in the current implementation it's easy to misuse the `LocalNodeWatcher`, so let's change it.

**Comment by kaworu** [comment]
@gandro updated the PR with your suggestion, please take another look :pray:

**Review by gandro — APPROVED** [review]

**Comment by gandro** [comment]
> Yes I thought about it and decided that the feature wasn't important enough to block the Hubble startup. My thinking was also that it shouldn't be designed around tests.

I haven't tested it, but looking at the code I expect the local node store to be ready once `launchHubble` is called. So it probably doesn't make a difference
