### PR TITLE
If source address is remote node then we should treat it as ouside traffic.

### LINKED ISSUE #28492: Broken connectivity with wireguard and DSR
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When using virtual IPs and DSR packets are filtered in certain scenarios.

Requirements: DSR, external virtual ip (balancer will send packets to nodes with dst = virtual ip, suited for dsr).

This bug is related to: https://github.com/cilium/cilium/issues/28187

If pod will try to connect to external service, which in turn in reality is service inside the same kubernetes cluster and the connection is established to virtual ip (external ip), connection from pod will be masqueraded. Node ip will be used for masquerading such connection. In such case service will receive packet on external ip address and src will be equal to node address. Such packets will be treated as internal and will be processed via wireguard interface:

https://github.com/cilium/cilium/blob/3de85a10f040fc83ddbf598656d1a244123feaa6/bpf/lib/wireguard.h#L102

But packets will be dropped on wireguard side, cause such ip address is not listed in allowed-ips for wireguard interface.  And connectivity will be broken as a result.

We've added following lines in order to fix the problem (hacked way):

```
	if (!src || identity_is_remote_node(src->sec_identity))
		goto out;
```

### Cilium Version

1.14.2

### Kernel Version

Any, tested on 6.5.5

### Kubernetes Version

Any, tested on 1.28.2

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kvaster**
If source address is remote node then we should treat it as ouside traffic. In other way traffic will be dropped by wireguard. And such traffic may exist in case some pod will connect to load balancer's external address with DSR enabled.

Fixes: #28492

### CODE REVIEW

**Comment by squeed** [comment]
ping @markpash

**Review by markpash — APPROVED** [review]

**Review by gandro — APPROVED** [review]

File: bpf/lib/wireguard.h [hunk 1]
```diff
@@ -133,6 +133,12 @@ wg_maybe_redirect_to_encrypt(struct __ctx_buff *ctx)
 	if (!src || !identity_is_cluster(src->sec_identity))
 		goto out;
 
+	/* If source is remote node we should treat it like outside traffic.
+	 * This is possible when connection is done from pod to load balancer with DSR enabled.
+	 */
+	if (identity_is_remote_node(src->sec_identity))
```
Comment (gandro) [inline bpf/lib/wireguard.h:139]: I'm assuming this is fine with node-to-node encryption too. Since the remote node IP is only in the `allowedIPs` list of the peer representing the remote node, we cannot forward such packets as they will have the wrong source IP. Is that correct?

Comment (kvaster) [reply bpf/lib/wireguard.h:139]: Yes. It's correct.
