### PR TITLE
fix: Panic during endpoint restore due to nil logger

### LINKED ISSUE #42213: SIGSEGV panic in 1.18 Agent DNSZombieMappings
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.18.2 and lower than v1.19.0

### What happened?

When upgrading our clusters from 1.17 to 1.18 multiple nodes had the Agent crashing on startup with the following error:
```
{"time":"2025-10-15T22:01:51.347740156Z","level":"info","msg":"Restoring checkpointed local identities","module":"agent.controlplane.identity.identity","file-path":"/var/run/cilium/state/local_allocator_state.json","count":15}
{"time":"2025-10-15T22:01:51.347871996Z","level":"info","msg":"Processing identity update","module":"agent.controlplane.policy","policyID.Added":[16777593,16777652,16777222,16777224,16777218,16777223,16777663,16777227,16777228,16777665,16777233,16777659,16777221,16777230,16777231],"policyID.Deleted":null}
{"time":"2025-10-15T22:01:51.348159482Z","level":"info","msg":"Removed map pin, recreating and re-pinning map","bpfMapPath":"cilium_ipcache_v2","bpfMapName":"cilium_ipcache_v2"}
{"time":"2025-10-15T22:01:51.348935006Z","level":"info","msg":"Reading old endpoints...","module":"agent.controlplane.daemon"}
{"time":"2025-10-15T22:01:51.350165182Z","level":"info","msg":"Incremental policy update: waiting for endpoint notifications to complete","module":"agent.controlplane.policy","count":1}
{"time":"2025-10-15T22:01:51.350217697Z","level":"info","msg":"Incremental policy update: triggering UpdatePolicyMaps for all endpoints","module":"agent.controlplane.policy"}
{"time":"2025-10-15T22:01:51.372703852Z","level":"info","msg":"restored DNS history from endpoint","module":"agent.controlplane.fqdn.namemanager","endpointID":3519,"count":13,"numAddresses":478}
{"time":"2025-10-15T22:01:51.375396725Z","level":"info","msg":"restored DNS history from endpoint","module":"agent.controlplane.fqdn.namemanager","endpointID":3162,"count":6,"numAddresses":242}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55c3d0]

goroutine 1 [running]:
log/slog.(*Logger).Handler(...)
	/usr/local/go/src/log/slog/logger.go:121
log/slog.(*Logger).Enabled(0x0?, {0x4e3cd70?, 0x815a8e0?}, 0xfa612c47c688?)
	/usr/local/go/src/log/slog/logger.go:168 +0x20
log/slog.(*Logger).log(0x0, {0x4e3cd70, 0x815a8e0}, 0x4, {0x40024b6680, 0xca}, {0x0, 0x0, 0x0})
	/usr/local/go/src/log/slog/logger.go:241 +0x48
log/slog.(*Logger).Warn(...)
	/usr/local/go/src/log/slog/logger.go:219
github.com/cilium/cilium/pkg/fqdn.(*DNSZombieMappings).GC(0x4003e789c0)
	/go/src/github.com/cilium/cilium/pkg/fqdn/cache.go:1036 +0x644
github.com/cilium/cilium/pkg/fqdn/namemanager.(*manager).RestoreCache(0x4001248600, 0x400131c930)
	/go/src/github.com/cilium/cilium/pkg/fqdn/namemanager/gc.go:218 +0x33c
github.com/cilium/cilium/daemon/cmd.newDaemon({0x4e3cfd0, 0x4002506500}, 0x4001060a70, 0x40008cc008)
	/go/src/github.com/cilium/cilium/daemon/cmd/daemon.go:463 +0xd88
github.com/cilium/cilium/daemon/cmd.newDaemonPromise.func1({0x4002e99748?, 0xa059d8?})
	/go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1438 +0xa0
github.com/cilium/hive/cell.Hook.Start(...)
	/go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/cell/lifecycle.go:43
github.com/cilium/hive/cell.(*DefaultLifecycle).Start(0x40002d9770, 0x4000522cf0, {0x4e3d040?, 0x400053c000?})
	/go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/cell/lifecycle.go:128 +0x2a0
github.com/cilium/hive.(*Hive).Start(0x4000d10e10, 0x4000522cf0, {0x4e3d040, 0x400053c000})
	/go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/hive.go:359 +0xe0
github.com/cilium/hive.(*Hive).Run(0x4000d10e10, 0x4000522cf0)
	/go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/hive.go:231 +0x70
github.com/cilium/cilium/daemon/cmd.NewAgentCmd.func1(0x4000a62c08, {0x47156ca?, 0x4?, 0x471556a?})
	/go/src/github.com/cilium/cilium/daemon/cmd/root.go:52 +0x1d4
github.com/spf13/cobra.(*Command).execute(0x4000a62c08, {0x40000b4190, 0x17, 0x17})
	/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:1019 +0x82c
github.com/spf13/cobra.(*Command).ExecuteC(0x4000a62c08)
	/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:1148 +0x384
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:1071
github.com/cilium/cilium/daemon/cmd.Execute(0x4978060?)
	/go/src/github.com/cilium/cilium/daemon/cmd/root.go:90 +0x1c
main.main()
	/go/src/github.com/cilium/cilium/daemon/main.go:15 +0x28
```

I believe this is caused by `ep.getLogger()` returning `nil` here when the endpoint is being restored:
https://github.com/cilium/cilium/blob/586a7c5fbded51f0c96c0dbe7239934a4ecae6a8/pkg/endpoint/restore.go#L563
So `DNSZombieMappings` ends up with a `nil` logger. 

The problem can be clearly seen here, first `ep.UnmarshalJSON()` is called: 
https://github.com/cilium/cilium/blob/586a7c5fbded51f0c96c0dbe7239934a4ecae6a8/pkg/endpoint/endpoint.go#L955 
and only afterwards the logger is actually initialized:
https://github.com/cilium/cilium/blob/586a7c5fbded51f0c96c0dbe7239934a4ecae6a8/pkg/endpoint/endpoint.go#L997

### How can we reproduce the issue?

-

### Cilium Version

```
Daemon: 1.18.2 e359538840 2025-09-25T14:38:13+02:00 go version go1.24.7 X:boringcrypto linux/arm64
```

### Kernel Version

-

### Kubernetes Version

-

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by pinaki-08**
Ensure DNSZombieMappings cannot hold a nil *slog.Logger when created during endpoint restore. The endpoint's logger is not initialized at Unmarshal/restore time which caused a nil-pointer dereference in DNSZombieMappings.GC.
Adding the existing endpoint Logger that has the nil check for the logger.

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

Fixes: #42213

```release-note
fix: Panic during endpoint restore due to nil logger
```

### CODE REVIEW

**Comment by HadrienPatte** [comment]
FYI your commit is authored and signed-off with a `@gamil.com` email, if that's a typo for `@gmail.com` you might want to update your git config to fix it and amend your commit on this PR to use the right email domain ;)

**Comment by pinaki-08** [comment]
@HadrienPatte Thanks for catching that ! I updated it.

File: pkg/endpoint/restore.go [hunk 1]
```diff
@@ -560,7 +560,7 @@ func (ep *Endpoint) UnmarshalJSON(raw []byte) error {
 		Labels:     labels.NewOpLabels(),
 		Options:    option.NewIntOptions(&EndpointMutableOptionLibrary),
 		DNSHistory: fqdn.NewDNSCacheWithLimit(option.Config.ToFQDNsMinTTL, option.Config.ToFQDNsMaxIPsPerHost),
-		DNSZombies: fqdn.NewDNSZombieMappings(ep.getLogger(), option.Config.ToFQDNsMaxDeferredConnectionDeletes, option.Config.ToFQDNsMaxIPsPerHost),
+		DNSZombies: fqdn.NewDNSZombieMappings(ep.Logger(subsystem), option.Config.ToFQDNsMaxDeferredConnectionDeletes, option.Config.ToFQDNsMaxIPsPerHost),
```
Comment (fristonio) [inline pkg/endpoint/restore.go:563]: It seems like the logger we are passing to DNSZombieMappings doesn't have endpoint attributes. I guess its not an issue given the logging usage is very minimal(only 2 warn logs). But it would be nice to get endpoint context in the logger.

Sample log: `2025-03-07T16:42:30.243220389Z time="2025-03-07T16:42:30Z" level=warning msg="Evicting expired DNS cache entries that may be in-use due to per-host limits. This may cause recently created connections to be disconnected. Raise tofqdns-endpoint-max-ip-per-hostname to mitigate this." subsys=fqdn`

**Review by fristonio — APPROVED** [review]
Thanks!
One minor suggestion, but not a blocker for the PR.

File: pkg/endpoint/restore.go (hunk 1 above)
Comment (pinaki-08) [reply pkg/endpoint/restore.go:563]: Yes, I thought about that. We could add a `setLogger` for `DNSZombieMappings` after setting the endpoint logger. However, since there are only two warning logs, it might be an overdo. We can still add it if you think it’s worthwhile.

Comment (pinaki-08) [reply pkg/endpoint/restore.go:563]: Let me check if there's a better way than `setLogger` though and create a separate PR.

Comment (fristonio) [reply pkg/endpoint/restore.go:563]: Yes, I would keep it separate to this fix.

**Comment by joestringer** [comment]
@fristonio @viktor-kurchenko did you check if the fix is relevant for older branches? We only started using slog relatively recently so I'm not sure this even makes sense to backport that far.

**Comment by HadrienPatte** [comment]
We only observed #42213 in 1.18 (first release to use slog), I don't see any instances of that panic in our clusters running 1.16 or 1.17, which could make sense as those don't use slog.

**Comment by fristonio** [comment]
> @fristonio @viktor-kurchenko did you check if the fix is relevant for older branches? We only started using slog relatively recently so I'm not sure this even makes sense to backport that far.

Ah, thats right. We don't pass a logger instance to zombie mapping object pre 1.18. So backport is only applicable to 1.18.
Removed the tags and removed the reference from v1.16 backport PR. cc/ @viktor-kurchenko.

**Comment by viktor-kurchenko** [comment]
> Ah, thats right. We don't pass a logger instance to zombie mapping object pre 1.18. So backport is only applicable to 1.18. Removed the tags and removed the reference from v1.16 backport PR. cc/ @viktor-kurchenko.

Thanks!
