### PR TITLE
Three fixes for deadlocks

### LINKED ISSUE #20915: Scale-down event of EKS kube-apiserver causes network outage
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

AWS EKS scales its kube-apiserver(s) out and in. I notice that whenever a kube-apiserver is removed, the cilium-agent and -operator continue to make API requests to this now decommissioned kube-apiserver. What's annoying is that this kube-apiserver does not seem to close existing connections. Instead, it now returns a 401 Unauthorized as a response to all requests. This could also be considered an EKS bug. The result is that cilium can no longer create endpoints, allocate ENIs or IPs and that the CiliumLocalRedirectPolicy and DNS proxy seem to stop functioning; potentially causing a cluster-wide network outage until cilium connects to a working kube-apiserver

I know that it is caused by a kube-apiserver being removed because I am monitoring the endpoints in `kubectl -n default get endpoints kubernetes`. Whenever an endpoint is removed, the problems start.

Restarting the agent and the operator restores functionality. Without a restart it takes about 5 minutes before cilium connects to a working endpoint.

From the operator:
```
cilium-operator-78d4dc7dbb-lv8q2 cilium-operator error retrieving resource lock kube-system/cilium-operator-resource-lock: Unauthorized
cilium-operator-78d4dc7dbb-lv8q2 cilium-operator level=error msg="error retrieving resource lock kube-system/cilium-operator-resource-lock: Unauthorized" subsys=klo
```

I don't know exactly how to reproduce this. What I do know is that new EKS clusters see the most scaling events of the kube-apiserver. I reproduce it myself by creating a new cluster and then scheduling a lot of pods. This often leads to scaling events.

Our cilium is installed with the following helm values:

```
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
        - key: kubernetes.io/arch
          operator: In
          values:
          - amd64
        - key: eks.amazonaws.com/compute-type
          operator: NotIn
          values:
          - fargate
bpf:
  hostRouting: false
  masquerade: true
  tproxy: true
cni:
  chainingMode: none
  configMap: cni-configuration
  customConf: true
devices: eth0
enableCiliumEndpointSlice: true
endpointHealthChecking:
  enabled: false
eni:
  awsEnablePrefixDelegation: true
  ec2APIEndpoint: ec2.eu-west-1.amazonaws.com
  enabled: true
  instanceTagsFilter: aws:eks:cluster-name=ci-eks-4qrg9g
  updateEC2AdapterLimitViaAPI: true
healthChecking: false
hubble:
  enabled: true
  eventBufferCapacity: "8191"
  metrics:
    enabled: null
    serviceMonitor:
      enabled: true
  relay:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: k8s-app
              operator: In
              values:
              - hubble-relay
          topologyKey: kubernetes.io/hostname
    enabled: true
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1
    replicas: 3
    rollOutPods: true
  ui:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: k8s-app
              operator: In
              values:
              - hubble-ui
          topologyKey: kubernetes.io/hostname
    enabled: true
    ingress:
      annotations: {}
      enabled: true
      hosts:
      - hubble.example.com
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1
    replicas: 3
    rollOutPods: true
ipam:
  mode: eni
k8sServiceHost: C0F975EE951307D359FFC679CA1FDD1F.sk1.eu-west-1.eks.amazonaws.com
k8sServicePort: 443
kubeProxyReplacement: strict
l7Proxy: true
loadBalancer:
  serviceTopology: true
localRedirectPolicy: true
operator:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: io.cilium/app
            operator: In
            values:
            - operator
          - key: name
            operator: In
            values:
            - cilium-operator
        topologyKey: kubernetes.io/hostname
  extraArgs:
  - --unmanaged-pod-watcher-interval=0
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1
  priorityClassName: system-cluster-critical
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  replicas: 3
  rollOutPods: true
  tolerations:
  - key: node.cilium.io/agent-not-ready
    operator: Exists
  - key: node.kubernetes.io/not-ready
    operator: Exists
priorityClassName: system-node-critical
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
svcSourceRangeCheck: "false"
tunnel: disabled
updateStrategy:
  type: OnDelete
```

### Cilium Version

```
❯ cilium version
cilium-cli: 0.12.1 compiled with go1.18.5 on linux/amd64
cilium image (default): v1.12.0
cilium image (stable): v1.12.0
cilium image (running): v1.12.0
```

### Kernel Version

Several:
```
5.15.54-25.126.amzn2.x86_64
5.4.204-113.362.amzn2.x86_64
```

### Kubernetes Version

```
Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.22.11-eks-18ef993
```

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bimmlerd**
This PR collects three commits with deadlock fixes:
1. Fixes a deadlock involving `writeHeaderFile`. See #24582 for details
2. Removes the lock ordering constraint of DNSProxy > IPCache by hoisting IPCache access out of the DNSProxy critical section in `GetRules`
3. Resolves a potential deadlock involving IPCache and Endpoint by avoiding to hold the IPCache mutex in `GetNamedPorts`. `IPCache.InjectLabels` holds the ipcache mutex while calling into `endpointManager.UpdatePolicyMaps`, which holds each EP lock in turn. On the other hand, `GetNamedPorts` holds an EP lock and calls into IPCache.

Please review commit by commit, and carefully - all changes are subtle.

Could use some help in word-smithing the release note.

[Marking this as backport/author, `atomic.Bool` and friends aren't available in Go 1.18 for v1.12]

- v1.13 backport is #24814
- v1.12 backport is #24669

Fixes: #23836
Ref: #20915

```release-note
Solve control-plane deadlock issues leading to outages. A typical log line indicative of this issue is `probe=l7-proxy msg="No response from probe within 15 seconds"`
```

cc @gandro @joestringer @christarazi

### CODE REVIEW

File: pkg/ipcache/ipcache.go [hunk 1]
```diff
@@ -103,18 +104,17 @@ type IPCache struct {
...
+	// 'namedPorts' map when it is known not to be needed.
+	needNamedPorts atomic.Bool
 
 	// namedPorts is a collection of all named ports in the cluster. This is needed
 	// only if an egress policy refers to a port by name.
 	// This map is returned to users so all updates must be made into a fresh map that
-	// is then swapped in place while 'mutex' is being held.
-	namedPorts types.NamedPortMultiMap
+	// is then swapped in place atomically.
+	namedPorts atomic.Pointer[types.NamedPortMultiMap]
```
Comment (jrajahalme) [inline pkg/ipcache/ipcache.go:117]: This is using `atomic.Pointer[]` though?

**Review by jrajahalme — APPROVED** [review]
Nice work! 

nit: It seems `atomic.Pointer` is used after all

File: pkg/ipcache/ipcache.go (hunk 1 above)
Comment (bimmlerd) [reply pkg/ipcache/ipcache.go:117]: It is on master, where we have an up to date Go version - I'll use `atomic.Value` in the backports.

File: pkg/endpoint/bpf.go [hunk 2]
```diff
@@ -156,12 +156,10 @@ func (e *Endpoint) writeHeaderfile(prefix string) error {
 	}
 	defer f.Cleanup()
 
-	// Update DNSRules if any. This is needed because DNSRules also encode allowed destination IPs
-	// and those can change anytime we have identity updates in the cluster. If there are no
-	// DNSRules (== nil) we don't need to update here, as in that case there are no allowed
-	// destinations either.
 	if e.DNSRules != nil {
-		e.OnDNSPolicyUpdateLocked(e.owner.GetDNSRules(e.ID))
+		// Note: e.DNSRules is updated by syncEndpointHeaderFile and regenerateBPF
```
Comment (joestringer) [inline pkg/endpoint/bpf.go:155]: nit: The `regenerateBPF()` path is now a bit odd, because the callpath is:

`regenerateBPF()` -> `runPreCompilationSteps()` -> `writeHeaderfile()`, then
`GetDNSRules()`, `OnDNSPolicyUpdateLocked()`

whereas for the `syncEndpointHeaderFile()`, it's:
`syncEndpointHeaderFile()` -> `GetDNSRules()`, `OnDNSPolicyUpdateLocked()` then `writeHeaderfile()`

Not really introduced by your PR, but worth noting since we're changing this now to be inconsistent. The other existing path in `regenerateBPF()` is only updating the DNS rules to be put into the headerfile _after_ writing the headerfile, so that would take effect next time around rather than this time around.

File: pkg/endpoint/regeneration/owner.go [hunk 3]
```diff
@@ -35,6 +35,7 @@ type Owner interface {
 
 	// GetDNSRules creates a fresh copy of DNS rules that can be used when
 	// endpoint is restored on a restart.
+	// No endpoint lock must be held while calling this function.
```
Comment (joestringer) [inline pkg/endpoint/regeneration/owner.go]: nit, the current wording suggests that it's not required to hold the lock, but it's stronger than that. In RFC2119 parlance, we would use "must not" to communicate this clearly.

```suggestion
	// The endpoint lock must not be held while calling this function.
```

File: pkg/endpoint/endpoint.go [hunk 4]
```diff
@@ -2101,12 +2101,23 @@ func (e *Endpoint) syncEndpointHeaderFile(reasons []string) {
 	e.buildMutex.Lock()
 	defer e.buildMutex.Unlock()
 
+	// The following GetDNSRules call will acquire a read-lock on the IPCache.
+	// Because IPCache itself will potentially acquire endpoint locks in its
+	// critical section, it is important to _not_ hold any endpoint lock
+	// while calling GetDNSRules, to avoid a deadlock between IPCache and the
+	// endpoint.
```
Comment (joestringer) [inline pkg/endpoint/endpoint.go]: The comment here is a little bit misleading given the buildMutex being grabbed above ("any endpoint lock"). 

I looked closer and it doesn't look like any paths outside endpoint acquire this mutex, so I don't think it's required to move this step to the top of the function. The other callpath down into `writeHeaderfile()` isn't making that call outside the buildMutex critical section either.

File: pkg/ipcache/ipcache.go [hunk 5]
```diff
@@ -680,15 +684,18 @@ func (ipc *IPCache) deleteLocked(ip string, source source.Source) (namedPortsCha
 
 // GetNamedPorts returns a copy of the named ports map. May return nil.
 func (ipc *IPCache) GetNamedPorts() (npm types.NamedPortMultiMap) {
-	ipc.mutex.Lock()
-	if !ipc.needNamedPorts {
-		ipc.needNamedPorts = true
-		ipc.updateNamedPorts()
+	ipc.mutex.RLock()
+	defer ipc.mutex.RUnlock()
```
Comment (joestringer) [inline pkg/ipcache/ipcache.go]: What's the purpose of the Read lock here?

Comment (joestringer) [reply pkg/ipcache/ipcache.go]: Oh, it looks like this is because `updateNamedPortsRLocked()` needs to access `ipc.ipToK8sMetadata` to read & prepare the new map to atomically update. We could probably shift that locking into the child function since I'm not seeing anything inside this function that relies on the readlock usage.

Comment (joestringer) [reply pkg/ipcache/ipcache.go]: ^ But if we moved it into the child function, we'd also need to provide a "don't lock" variant for `deleteLocked()` and friends. So probably this is reasonable enough to leave here, it's just that putting the locking at the start of the function implies additional locking protections than just the need for stable read access for the child call. 🤷 it works, I just want to make sure we don't make assumptions about multiple threads inside this function because that *can* be the case. Based on the usage of atomics etc. here I think the behaviour is correct.

File: pkg/endpoint/bpf.go (hunk 2 above)
Comment (joestringer) [reply pkg/endpoint/bpf.go:155]: I don't think this has a particularly meaningful impact given that the headerfile will be synced soon enough anyway, but it would be a nice followup to fix the ordering. Non-blocking.

**Review by joestringer — CHANGES_REQUESTED** [review]
Nice work tracking these down. Looks good to me other than some minor discrepancies in comments and one inconsequential ordering issue that was introduced by the prior commit in this area. It'd be good to take a fresh look at the comments since they don't account for buildMutex, but practically I think there's just minor wording tweaks to make there. Functionally the PR looks good.

File: pkg/endpoint/bpf.go (hunk 2 above)
Comment (christarazi) [reply pkg/endpoint/bpf.go:155]: After investigating the code paths (to familiarize myself more with this code), it should be as simple as applying the following, which pulls the `writeHeaderfile()` out of `runPreCompilationSteps()`:

```diff
diff --git a/pkg/endpoint/bpf.go b/pkg/endpoint/bpf.go
index a06349f5e8..63cf59605f 100644
--- a/pkg/endpoint/bpf.go
+++ b/pkg/endpoint/bpf.go
@@ -618,6 +618,11 @@ func (e *Endpoint) regenerateBPF(regenContext *regenerationContext) (revnum uint
 		return 0, compilationExecuted, err
 	}
 	e.OnDNSPolicyUpdateLocked(rules)
+	if headerfileChanged {
+		if err := e.writeHeaderfile(datapathRegenCtxt.nextDir); err != nil {
+			return 0, compilationExecuted, fmt.Errorf("unable to write header file: %w", err)
+		}
+	}
 	e.unlock()
 
 	// Keep track of the side-effects of the regeneration that need to be
@@ -935,11 +940,6 @@ func (e *Endpoint) runPreCompilationSteps(regenContext *regenerationContext) (he
 	if headerfileChanged {
 		datapathRegenCtxt.regenerationLevel = regeneration.RegenerateWithDatapathRewrite
 	}
-	if datapathRegenCtxt.regenerationLevel >= regeneration.RegenerateWithDatapathRewrite {
-		if err := e.writeHeaderfile(nextDir); err != nil {
-			return false, fmt.Errorf("unable to write header file: %s", err)
-		}
-	}
 
 	// Cache endpoint information so that we can release the endpoint lock.
 	if datapathRegenCtxt.regenerationLevel >= regeneration.RegenerateWithDatapathRewrite {
```

This should make the `regenerateBPF()` path equivalent to `syncEndpointHeaderFile()`.

File: pkg/endpoint/regeneration/owner.go (hunk 3 above)
Comment (christarazi) [reply pkg/endpoint/regeneration/owner.go]: And to be clear, there are more than one endpoint locks (i.e. `buildMutex`) as Joe mentioned above.

File: pkg/fqdn/dnsproxy/proxy.go [hunk 6]
```diff
@@ -221,47 +221,73 @@ func (p *DNSProxy) checkRestored(endpointID uint64, destPort uint16, destIP stri
 // GetRules creates a fresh copy of EP's DNS rules to be stored
 // for later restoration.
 func (p *DNSProxy) GetRules(endpointID uint16) (restore.DNSRules, error) {
+	// Lock Ordering Note: Acquiring the IPCache look (as LookupIPsBySecID does)
```
Comment (christarazi) [inline pkg/fqdn/dnsproxy/proxy.go]: I'm wondering if we'd feel more confident if we had unit tests validating this function, in case this change subtly introduced a regression.

File: pkg/ipcache/ipcache.go [hunk 7]
```diff
@@ -244,13 +244,21 @@ func (ipc *IPCache) getK8sMetadata(ip string) *K8sMetadata {
 	return nil
 }
 
-// updateNamedPorts accumulates named ports from all K8sMetadata entries to a single map
-func (ipc *IPCache) updateNamedPorts() (namedPortsChanged bool) {
-	if !ipc.needNamedPorts {
+// updateNamedPortsRLocked accumulates named ports from all K8sMetadata entries to a single map
```
Comment (christarazi) [inline pkg/ipcache/ipcache.go]: This should probably explicitly call out that it requires at least a read-lock? Yes the name of the function is clear, but given that the usage of the function is not always called with only the read-lock, then explaining that this call should only be done with _at least_ a read-lock and thus, is safe to be done with a write-lock as well.

File: pkg/ipcache/ipcache.go (hunk 5 above)
Comment (christarazi) [reply pkg/ipcache/ipcache.go]: Once we land the [ipcache refactor](https://github.com/cilium/cilium/issues/21142), hopefully this will clean up this code path.

**Review by christarazi — COMMENTED** [review]
Great work! A few comments on top of Joe's review.

File: pkg/endpoint/bpf.go (hunk 2 above)
Comment (gandro) [reply pkg/endpoint/bpf.go:155]: Pushed a variant of this: https://github.com/cilium/cilium/compare/054b7f6fa2c02162de5441ddc3afee4c379bb2d4..133a02cf2ccf7c336bcd7a16aaccfc0929fd01dd

I am a bit unsure though if it really is save to release `e.lock()` between `runPreCompilationSteps()` and `writeHeaderfile()` - could it allow for any significant changes to the endpoint that would cause the headerfile to look different?

File: pkg/fqdn/dnsproxy/proxy.go (hunk 6 above)
Comment (bimmlerd) [reply pkg/fqdn/dnsproxy/proxy.go]: Current tests actually found such a regression, see https://github.com/cilium/cilium/compare/62f094858c38ac1d14e117a1d54736196198f24c..054b7f6fa2c02162de5441ddc3afee4c379bb2d4 where I had missed adding the regex in the wildcard case. It's covered by the privileged proxy test cases in `DNSProxyTestSuite.TestFullPathDependence`

File: pkg/endpoint/endpoint.go (hunk 4 above)
Comment (bimmlerd) [reply pkg/endpoint/endpoint.go]: Updated the comment, PTAL.

File: pkg/endpoint/regeneration/owner.go (hunk 3 above)
Comment (bimmlerd) [reply pkg/endpoint/regeneration/owner.go]: Done. I've tried calling it `endpoint.mutex` to be as clear as possible, does that work?

File: pkg/ipcache/ipcache.go (hunk 5 above)
Comment (bimmlerd) [reply pkg/ipcache/ipcache.go]: added a comment to clarify - but yeah, a cleanup would be nice.

**Review by bimmlerd — COMMENTED** [review]
Wordsmithing. Diff in https://github.com/cilium/cilium/compare/133a02cf2ccf7c336bcd7a16aaccfc0929fd01dd..770dbf1c9f19eb8b9caf78324e958baf08d8f949

File: pkg/ipcache/ipcache.go (hunk 5 above)
Comment (gandro) [reply pkg/ipcache/ipcache.go]: @joestringer @christarazi We just determined that this RLock here will still cause a deadlock:

We have `EndpointRLocked -> IPCacheRLocked` (for `GetNamedPorts`) and `IPCacheWLocked -> EndpointWLocked` (for `InjectLabels`), which will deadlock if the two paths are taken by to go routines in parallel.

I will investigate if it's possible to refactor the `GetNamedPorts` to not hold the RLock here. Otherwise, I think we need to introduce the additional [IPCache update lock](https://github.com/cilium/cilium/compare/v1.12...gandro:cilium:pr/gandro/v1.12-ipcache-deadlock-attempt-v5?expand=1) that allows for the IPCache RLock to be taken during InjectLabels.

Comment (gandro) [reply pkg/ipcache/ipcache.go]: I've pushed a commit that just always computes the `NamedPorts` eagerly, regardless if it's used by a policy or not. I'm not sure how expensive that will be: https://github.com/cilium/cilium/pull/24672/commits/3a5e8d9fa06a31aa3929f437fde9d5d33d77327c

File: pkg/endpoint/bpf.go (hunk 2 above)
Comment (christarazi) [reply pkg/endpoint/bpf.go:155]: Hm, you're right. Then I think to resolve Joe's original comment, we should move `writeHeaderfile()` back to it's original spot and then move the following block _before_ `runPreCompilationSteps()`:

```
	rules := e.owner.GetDNSRules(uint16(e.ID))
	if err := e.lockAlive(); err != nil {
		return 0, compilationExecuted, err
	}
	e.OnDNSPolicyUpdateLocked(rules)
	e.unlock()
```

Comment (christarazi) [reply pkg/endpoint/bpf.go:155]: ^ We can even go a step further (after the above is applied) and allow the DNS rules to be passed into `runPreCompilationSteps()` and then perform the `OnDNSPolicyUpdateLocked()` while the endpoint is locked. Then we remove that whole extra block above which is too messy already with the extra locking.

This makes the ordering and locking much more sane and predictable in behavior, even though I don't think it would've caused actual problems in a cluster. Just easier to reason about when reading the code.

File: pkg/ipcache/ipcache.go (hunk 5 above)
Comment (gandro) [reply pkg/ipcache/ipcache.go]: Folded the above change into the last commit (`ipcache: fix potential deadlock in GetNamedPorts`). In contrast to earlier versions, the `needNamedPorts` boolean is kept to avoid unnecessary policy updates if `GetNamedPorts` was never called.

The current version of the `GetNamedPorts` should not any externally visible behavior, all the commit does is drop an optimization that would delay the construction of the NamedPorts map until it was requested for the first time.

File: pkg/ipcache/ipcache.go [hunk 8]
```diff
@@ -259,15 +265,20 @@ func (ipc *IPCache) updateNamedPorts() (namedPortsChanged bool) {
...
+		ipc.namedPorts.Store(&npm)
 	}
+
+	// Set namedPortsChanged to false if they have not (yet) been requested.
+	// This avoids triggering policy updates if named ports changed, but no
+	// policy actually needs them. We still pre-compute the namedPorts map,
+	// so we don't have to acquire the IPCache lock in GetNamedPorts
+	if !ipc.needNamedPorts.Load() {
+		namedPortsChanged = false
+	}
```
Comment (joestringer) [inline pkg/ipcache/ipcache.go]: If we don't trigger policy updates due to the named port changes, then how does the policy evaluation occur in order to set the need for named ports?

Comment (joestringer) [reply pkg/ipcache/ipcache.go]: This _feels_ like it may introduce a behaviour where someone changes a named port on a Pod, and it doesn't take effect until later on when policy evaluation is triggered for some other unrelated reason.

**Comment by joestringer** [comment]
(GitHub/Azure looks like it's having a bad day, maybe I'll try close+reopen)

**Comment by bimmlerd** [comment]
IntergrationTests / integratio-test failure is https://github.com/cilium/cilium/issues/24653, rebasing on master to get https://github.com/cilium/cilium/pull/24652

File: pkg/ipcache/ipcache.go (hunk 8 above)
Comment (gandro) [reply pkg/ipcache/ipcache.go]: Yeah, I also had that thought. But note that the old code also has the behavior (this if statement here just used to be the first statement of this function, the only difference now is that we're always computing the namedPorts map now).

I'll investigate.

File: pkg/fqdn/dnsproxy/proxy.go [hunk 9]
```diff
@@ -221,47 +221,73 @@ func (p *DNSProxy) checkRestored(endpointID uint64, destPort uint16, destIP stri
...
+			count := 0
+			nids := selRegex.cs.GetSelections()
+		Loop:
+			for _, nid := range nids {
+				nidIPs := p.LookupIPsBySecID(nid)
+				for _, ip := range nidIPs {
+					// Skip IPs that are allowed but have never been used,
+					// but only if at least one server has been used so far.
+					if len(p.usedServers) > 0 {
+						if _, used := p.usedServers[ip]; !used {
```
Comment (bimmlerd) [inline pkg/fqdn/dnsproxy/proxy.go]: this map access is now racy and will panic - there's a fixed variant in the v1.12 backport (take the rlock and release it again after), but we're looking into fixing it in a better way for master.

File: pkg/fqdn/dnsproxy/proxy.go [hunk 10]
```diff
@@ -221,47 +221,73 @@ func (p *DNSProxy) checkRestored(endpointID uint64, destPort uint16, destIP stri
...
+							continue
 						}
 					}
+					ips[ip] = struct{}{}
+					count++
+					if count > p.maxIPsPerRestoredDNSRule {
```
Comment (bimmlerd) [inline pkg/fqdn/dnsproxy/proxy.go:284]: accesses to maxIPsPerRestoredDNSRule are also racy, though somewhat inconsequential as it's essentially constant. will fix by pulling out of the loop into a local var read while in critical section.

**Review by bimmlerd — COMMENTED** [review]
commit 2 introduced two dataraces, will need to be fixed before merging

File: pkg/endpoint/bpf.go (hunk 2 above)
Comment (gandro) [reply pkg/endpoint/bpf.go:155]: I considered a similar approach before as well. My understanding is that `runPreCompilationSteps` can actually change the DNS rules. So if we extract them before the call, they will be stale. 

Maybe we should get rid of the call to DNS rules here and rely on the sync routine, as proposed earlier: https://github.com/cilium/cilium/pull/23836#discussion_r1109687019

**Comment by gandro** [comment]
Pushed a fix for the data race.

File: pkg/endpoint/bpf.go (hunk 2 above)
Comment (gandro) [reply pkg/endpoint/bpf.go:155]: Implemented your suggestion for now. I don't think there is a way to obtain fresh DNSRules _and_ hold on to the endpoint mutex, since that order of events is the reason we have a deadlock. 

So we either need to unlock endpoint, obtain fresh DNSRules, and lock it again for `writeHeaderfile` - or work with potentially stale DNS rules that we obtain before calling into `runPreCompilationSteps`. Since the DNSRules are periodically updated by `syncEndpointHeaderFile`, I think it's fine to write potentially stale DNSRules during regeneration.

File: pkg/ipcache/ipcache.go (hunk 8 above)
Comment (gandro) [reply pkg/ipcache/ipcache.go]: I've investigated:

> If we don't trigger policy updates due to the named port changes, then how does the policy evaluation occur in order to set the need for named ports?

So the way this seems to work is that `ipc.needNamedPorts` is false as long as there is no policy referencing named ports. So it's safe to not trigger policy updates, because at that point no policy was using them. Once a policy has named ports, the policy engine will call "GetNamedPorts", and thereby causing any subsequent `IPCache.{Upsert,Delete}` calls to return 'namedPortsChanged=true', enabling callers to trigger policy updates when needed.

I've left a source code comment indicating that as well. Note that this behavior was already present before this PR. This PR does not change any externally visible behavior of IPCache around named ports (besides the fact that internally it no longer acquires a mutex for `GetNamedPorts`).

**Comment by gandro** [comment]
@joestringer @christarazi Please re-review. I think we addressed all the feedback and 

There are a few oddities with the current approach, but I think the current patch is a close as possible to the existing behavior in our stables branches as it can get. Given the limitation that we cannot acquire a readlock on IPCache during certain operations (i.e. GetDNSRules or GetNamedPorts) I think any future improvements should be done on separate PRs to ensure minimal risks for backports.

Ideally this lands in the next v1.12/v1.13 patch scheduled for end of next week.

File: pkg/endpoint/bpf.go (hunk 2 above)
Comment (christarazi) [reply pkg/endpoint/bpf.go:155]: Agreed with the above.

File: pkg/endpoint/bpf.go [hunk 11]
```diff
@@ -608,18 +607,11 @@ func (e *Endpoint) regenerateBPF(regenContext *regenerationContext) (revnum uint
 	datapathRegenCtxt.prepareForProxyUpdates(regenContext.parentContext)
 	defer datapathRegenCtxt.completionCancel()
 
-	headerfileChanged, err = e.runPreCompilationSteps(regenContext)
 	// The following DNS rules code was previously inside the critical section
 	// above (runPreCompilationSteps()), but this caused a deadlock with the
```
Comment (christarazi) [inline pkg/endpoint/bpf.go]: "above" -> "below"

File: pkg/fqdn/dnsproxy/proxy.go [hunk 12]
```diff
@@ -218,50 +218,87 @@ func (p *DNSProxy) checkRestored(endpointID uint64, destPort uint16, destIP stri
...
+				continue
+			}
+			ips := make(map[string]struct{})
+			count := 0
+			nids := selRegex.cs.GetSelections()
+		Loop:
+			for _, nid := range nids {
+				nidIPs := p.LookupIPsBySecID(nid)
+				for _, ip := range nidIPs {
+					if p.skipIPInRestoration(ip) {
```
Comment (christarazi) [inline pkg/fqdn/dnsproxy/proxy.go]: Does it make sense to acquire the proxy read-lock here in a loop like this or should we move the lock outside of the lock and make `skipIPInRestoration()` -> `skipIPInRestorationRLocked()`?

**Comment by christarazi** [comment]
Just a minor nit: I think the PR description is slightly stale.

File: pkg/fqdn/dnsproxy/proxy.go [hunk 13]
```diff
@@ -218,50 +218,87 @@ func (p *DNSProxy) checkRestored(endpointID uint64, destPort uint16, destIP stri
...
+			if selRegex.cs.IsWildcard() {
+				ipRules = append(ipRules, asIPRule(selRegex.re, nil))
+				continue
+			}
+			ips := make(map[string]struct{})
+			count := 0
+			nids := selRegex.cs.GetSelections()
+		Loop:
+			for _, nid := range nids {
+				nidIPs := p.LookupIPsBySecID(nid)
```
Comment (joestringer) [inline pkg/fqdn/dnsproxy/proxy.go:276]: It occurs to me that it's this callback mechanism that's injected in the `StartDNSProxy()` function that never really stated any sort of locking constraints... probably we should at least document if not rework the way that lookup occurs at some point to make it less error-prone. Maybe a target for future `pkg/statedb` work.

This raises an interesting question though because `LookupIPsBySecIDFunc` is just one of three callbacks there that we may want to investigate if we haven't already, and confirm the locking behaviours for each of them.

File: pkg/fqdn/dnsproxy/proxy.go [hunk 14]
```diff
@@ -218,50 +218,87 @@ func (p *DNSProxy) checkRestored(endpointID uint64, destPort uint16, destIP stri
 	return false
 }
 
+// skipIPInRestoration skips IPs that are allowed but have never been used,
+// but only if at least one server has been used so far.
+func (p *DNSProxy) skipIPInRestoration(ip string) bool {
+	p.RLock()
+	defer p.RUnlock()
```
Comment (joestringer) [inline pkg/fqdn/dnsproxy/proxy.go]: nit: Depending on how frequently Cilium hits `GetRules()`, we could amortize locking costs by assembling the IPs in a separate loop then grabbing the lock again later on. But I'm fine with this solution unless we get specific indicators that it will be a performance problem :+1:

**Review by joestringer — APPROVED** [review]

**Review by thorn3r — APPROVED** [review]
this LGTM. nice sleuthing :heavy_plus_sign:

File: pkg/endpoint/bpf.go (hunk 11 above)
Comment (gandro) [reply pkg/endpoint/bpf.go]: Thanks, fixed!

File: pkg/fqdn/dnsproxy/proxy.go (hunk 12 above)
Comment (gandro) [reply pkg/fqdn/dnsproxy/proxy.go]: Good call! I moved it out of the `for _, ip` loop. Moving it out of the `for _, nid` loop is a bit more tricky, so I'll leave this as is for now.

File: pkg/fqdn/dnsproxy/proxy.go (hunk 13 above)
Comment (gandro) [reply pkg/fqdn/dnsproxy/proxy.go:276]: Yes, I did check the other callbacks and did not find anything. They mostly seem to be called when a DNS request is handled, which does not either not hold the EP or DNSProxy lock, or only for a short, isolated time.

Having said that, there is always the danger that we missed something. My IDE support and grep foo is limited in ensuring that there really are no other calls to those functions.

File: pkg/fqdn/dnsproxy/proxy.go (hunk 14 above)
Comment (gandro) [reply pkg/fqdn/dnsproxy/proxy.go]: I did hoist the RLock one loop up, c.f. https://github.com/cilium/cilium/pull/24672#discussion_r1159482992

The outer loop could probably be fixed as well via your suggestion, but I'll leave that as a follow-up item for now.

**Comment by gandro** [comment]
Addressed the feedback, thanks! Here's the diff:

<details>

```diff
diff --git a/pkg/endpoint/bpf.go b/pkg/endpoint/bpf.go
index c86f137de2ff..a815866a6a86 100644
--- a/pkg/endpoint/bpf.go
+++ b/pkg/endpoint/bpf.go
@@ -608,7 +608,7 @@ func (e *Endpoint) regenerateBPF(regenContext *regenerationContext) (revnum uint
 	defer datapathRegenCtxt.completionCancel()
 
 	// The following DNS rules code was previously inside the critical section
-	// above (runPreCompilationSteps()), but this caused a deadlock with the
+	// below (runPreCompilationSteps()), but this caused a deadlock with the
 	// IPCache. Therefore, we obtain the DNSRules outside the critical section.
 	rules := e.owner.GetDNSRules(e.ID)
 	headerfileChanged, err = e.runPreCompilationSteps(regenContext, rules)
diff --git a/pkg/fqdn/dnsproxy/proxy.go b/pkg/fqdn/dnsproxy/proxy.go
index cdbb90474b40..766633d903b3 100644
--- a/pkg/fqdn/dnsproxy/proxy.go
+++ b/pkg/fqdn/dnsproxy/proxy.go
@@ -218,11 +218,10 @@ func (p *DNSProxy) checkRestored(endpointID uint64, destPort uint16, destIP stri
 	return false
 }
 
-// skipIPInRestoration skips IPs that are allowed but have never been used,
+// skipIPInRestorationRLocked skips IPs that are allowed but have never been used,
 // but only if at least one server has been used so far.
-func (p *DNSProxy) skipIPInRestoration(ip string) bool {
-	p.RLock()
-	defer p.RUnlock()
+// Requires the RLock to be held.
+func (p *DNSProxy) skipIPInRestorationRLocked(ip string) bool {
 	if len(p.usedServers) > 0 {
 		if _, used := p.usedServers[ip]; !used {
 			return true
@@ -256,8 +255,6 @@ func (p *DNSProxy) GetRules(endpointID uint16) (restore.DNSRules, error) {
 		portToSelRegex[port] = nidRules
 	}
 
-	maxIPsPerRestoredDNSRule := p.maxIPsPerRestoredDNSRule
-
 	// We've read what we need from the proxy. The following IPCache lookups _must_ occur outside of
 	// the critical section.
 	p.RUnlock()
@@ -275,24 +272,28 @@ func (p *DNSProxy) GetRules(endpointID uint16) (restore.DNSRules, error) {
 			nids := selRegex.cs.GetSelections()
 		Loop:
 			for _, nid := range nids {
+				// Note: p.RLock must not be held during this call to IPCache
 				nidIPs := p.LookupIPsBySecID(nid)
+				p.RLock()
 				for _, ip := range nidIPs {
-					if p.skipIPInRestoration(ip) {
+					if p.skipIPInRestorationRLocked(ip) {
 						continue
 					}
 					ips[ip] = struct{}{}
 					count++
-					if count > maxIPsPerRestoredDNSRule {
+					if count > p.maxIPsPerRestoredDNSRule {
 						log.WithFields(logrus.Fields{
 							logfields.EndpointID:            endpointID,
 							logfields.Port:                  port,
 							logfields.EndpointLabelSelector: selRegex.cs,
-							logfields.Limit:                 maxIPsPerRestoredDNSRule,
+							logfields.Limit:                 p.maxIPsPerRestoredDNSRule,
 							logfields.Count:                 len(nidIPs),
 						}).Warning("Too many IPs for a DNS rule, skipping the rest")
+						p.RUnlock()
 						break Loop
 					}
 				}
+				p.RUnlock()
 			}
 			ipRules = append(ipRules, asIPRule(selRegex.re, ips))
 		}
```

</details>

@christarazi 
> Just a minor nit: I think the PR description is slightly stale.

Anything particular that stands out to you? I did some minor edits just now, but it should be up to date as far as I can tell.

**Comment by joestringer** [comment]
👍 latest diff LGTM

**Comment by christarazi** [comment]
LGTM as well :+1:

**Review by christarazi — APPROVED** [review]

**Comment by gandro** [comment]
Previous CI was green except [ci-datapath](url) and [EKS](https://github.com/cilium/cilium/actions/runs/4665767495), the latter due to a known issue on master which just got fixed. Rebased again to pull in those cahnges.

Restarting the tests again.

**Comment by gandro** [comment]
This is ready to merge.
