### PR TITLE
CNI: improve plugin chaining

### LINKED ISSUE #22286: Cilium kubernetes IPAM shows duplicated addresses when in chaining mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I want to run Cilium CNI to partially replace kube-proxy. I run a live GKE cluster that does not have Data Plane v2. The GKE native CNI uses veth, so I tried to use the [Generic Veth Chaining](https://docs.cilium.io/en/stable/gettingstarted/cni-chaining-generic-veth/) approach. I could not use the static CNI config solution proposed by the tutorial, because GKE uses host-local Pod IPAM, which means the CNI config is different per node, for example:
```
$ sudo cat /etc/cni/net.d/10-gke-ptp.conflist | jq
{
  "name": "gke-pod-network",
  "cniVersion": "0.3.1",
  "plugins": [
    {
      "type": "gke",
      "mtu": 1460,
      "ipam": {
        "type": "host-local",
        "ranges": [
          [
            {
              "subnet": "10.16.3.0/25"
            }
          ]
        ],
        "routes": [
          {
            "dst": "0.0.0.0/0"
          }
        ]
      }
    },
    {
      "type": "portmap",
      "capabilities": {
        "portMappings": true
      }
    },
    {
      "type": "bandwidth",
      "capabilities": {
        "bandwidth": true
      }
    }
  ]
}
```

I worked around this problem by creating a DaemonSet that basically append the cilium-cni entry to the CNI plugin list on every node. The DaemonSet would execute:
```
ROOT_MOUNT_DIR="/node_root"
CNI_CONFIG_FILE="/etc/cni/net.d/10-gke-ptp.conflist"

echo "Current CNI config:"
cat "${ROOT_MOUNT_DIR}/${CNI_CONFIG_FILE}"

# This check ensures `cilium-cni' plugin is defined once.
found=$(grep "cilium-cni" "${ROOT_MOUNT_DIR}/${CNI_CONFIG_FILE}")
if [[ ! -z "${found}" ]]; then
  echo "cilium-cni is already appended. Done."
  exit 0
fi

echo "Updating CNI config file."
BEFORE='} ] }'
AFTER='},{"type": "cilium-cni"} ] }'
chroot "${ROOT_MOUNT_DIR}" sed -i s/"${BEFORE}"/"${AFTER}"/g "${CNI_CONFIG_FILE}"

echo "New CNI config:"
cat "${ROOT_MOUNT_DIR}/${CNI_CONFIG_FILE}"

echo "Done."
```

After creating this DaemonSet, I install Cilium by applying
```
helm template cilium cilium/cilium --version 1.12.3 \
--namespace kube-system \
--set cni.chainingMode=generic-veth \
--set cni.customConf=true \
--set cni.binPath=/home/kubernetes/bin \
--set enableIPv4Masquerade=false \
--set enableIPv6Masquerade=false \
--set tunnel=disabled \
--set kubeProxyReplacement=partial \
--set socketLB.enabled=true \
--set socketLB.hostNamespaceOnly=true \
--set nodePort.enabled=false \
--set nodePort.enableHealthCheck=false \
--set externalIPs.enabled=true \
--set hostPort.enabled=true \
--set policyEnforcementMode=never \
--set rollOutCiliumPods=true \
--set hubble.enabled=false \
--set operator.rollOutPods=true \
--set l7Proxy=false \
--set waitForKubeProxy=true \
--set ipam.mode=kubernetes \
--set nodeinit.enabled=true \
> install.yaml
```

```
$ kubectl -n kube-system exec ds/cilium -- cilium status --verbose
KubeProxyReplacement Details:
  Status:                 Partial
  ...
  Services:
  - ClusterIP:      Enabled
  - NodePort:       Disabled
  - LoadBalancer:   Disabled
  - externalIPs:    Disabled
  - HostPort:       Disabled
```

Then I noticed the my CoreDNS pods (serving my cluster kube-dns) were all stuck in `ContainerCreating` because of error like `Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "1ff7a4ac2f30398726374aecbb8d9bb8bea1a8fac1cf0befc57173f0d8180809": invalid CIDR address: <nil>`.

```
$ kubectl get ciliumnodes.cilium.io gke-gke-us-central1--auto-pool-22-gke-ea27f07a-dmtz -o yaml
...
spec:
  addresses:
  - ip: 10.31.120.92
    type: InternalIP
  - ip: 10.16.10.203
    type: CiliumInternalIP
  alibaba-cloud: {}
  azure: {}
  encryption: {}
  eni: {}
  health: {}
  ingress: {}
  ipam:
    podCIDRs:
    - 10.16.10.128/25

$ kubectl get node gke-gke-us-central1--auto-pool-22-gke-ea27f07a-dmtz -o yaml
...
spec:
  podCIDR: 10.16.10.128/25
  podCIDRs:
  - 10.16.10.128/25

$ kubectl describe no gke-gke-us-central1--auto-pool-22-gke-ea27f07a-dmtz | grep cilium
  kube-system                     cilium-node-init-7wk8r                                             100m (0%)     0 (0%)      100Mi (0%)       0 (0%)         74m
  kube-system                     cilium-zmmtx                                                       100m (0%)     0 (0%)      100Mi (0%)       0 (0%)         69m
  kube-system                     gke-cni-chaining-cilium-lxwg4                                      100m (0%)     100m (0%)   100Mi (0%)       100Mi (0%)     135m
  
$ kubectl logs cilium-zmmtx -n kube-system
...
level=info msg="Initializing kubernetes IPAM" subsys=ipam v4Prefix=10.16.10.128/25 v6Prefix="<nil>"
level=info msg="Restoring endpoints..." subsys=daemon
level=info msg="Endpoints restored" failed=0 restored=1 subsys=daemon
level=info msg="Addressing information:" subsys=daemon
level=info msg="  Cluster-Name: default" subsys=daemon
level=info msg="  Cluster-ID: 0" subsys=daemon
level=info msg="  Local node-name: gke-gke-us-central1--auto-pool-22-gke-ea27f07a-dmtz" subsys=daemon
level=info msg="  Node-IPv6: <nil>" subsys=daemon
level=info msg="  External-Node IPv4: 10.31.120.92" subsys=daemon
level=info msg="  Internal-Node IPv4: 10.16.10.203" subsys=daemon
level=info msg="  IPv4 allocation prefix: 10.16.10.128/25" subsys=daemon
level=info msg="  Loopback IPv4: 169.254.42.1" subsys=daemon
level=info msg="  Local IPv4 addresses:" subsys=daemon
level=info msg="  - 10.31.120.92" subsys=daemon
level=info msg="  - 10.16.10.129" subsys=daemon
level=info msg="  - 10.16.10.129" subsys=daemon
level=info msg="  - 10.16.10.129" subsys=daemon
level=info msg="  - 10.16.10.129" subsys=daemon
level=info msg="  - 10.16.10.129" subsys=daemon
level=info msg="  - 10.16.10.129" subsys=daemon
level=info msg="  - 10.16.10.129" subsys=daemon
level=info msg="  - 10.16.10.129" subsys=daemon
level=info msg="  - 10.16.10.129" subsys=daemon
level=info msg="  - 10.16.10.129" subsys=daemon
level=info msg="  - 10.16.10.129" subsys=daemon
level=info msg="  - 10.16.10.129" subsys=daemon
level=info msg="  - 10.16.10.129" subsys=daemon
level=info msg="  - 10.16.10.129" subsys=daemon
level=info msg="  - 10.16.10.129" subsys=daemon
level=info msg="  - 10.16.10.129" subsys=daemon
level=info msg="  - 10.16.10.129" subsys=daemon
level=info msg="  - 10.16.10.129" subsys=daemon
level=info msg="  - 10.16.10.129" subsys=daemon
level=info msg="  - 10.16.10.129" subsys=daemon
level=info msg="  - 10.16.10.129" subsys=daemon
level=info msg="  - 10.16.10.129" subsys=daemon
level=info msg="  - 10.16.10.129" subsys=daemon
level=info msg="  - 10.16.10.203" subsys=daemon
```

As you can see, there are lots of duplicated IPs. Restarting CoreDNS DaemonSet and Cilium DaemonSet made no difference. Traffic to a Kubernetes Service using ClusterIP + Host header actually works (kube-dns backed by CoreDNS was down, so I could not use hostname to test).

My questions for you:
1. Why would Cilium want to manage IPAM when in CNI chaining mode? How do I delegate Pod IPAM to the GKE native CNI and just use Cilium for load balancing and policy enforcement?
2. It seems to be a bug that Cilium agent reports reserving duplicated IPs. How to fix/workaround this?
3. How do I observe Cilium CNI binary behavior? The helm option `cni.logFile` defaults to `/var/run/cilium/cilium-cni.log`, but I don't see this log file under `/var/run/cilium/` on the node.

### Cilium Version

v1.12.3

### Kernel Version

```
Linux gke-gke-us-central1--auto-pool-22-gke-ea27f07a-dmtz 5.4.0-1072-gke #77-Ubuntu SMP Thu May 19 07:50:39 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
$ kubectl version                                                                                                                                                            ─╯
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:36:43Z", GoVersion:"go1.19", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.12-gke.2300", GitCommit:"e55564cf3a1384026a54920174977659c8c56a50", GitTreeState:"clean", BuildDate:"2022-08-16T09:24:51Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.22) exceeds the supported minor version skew of +/-1
```

### Sysdump

[cilium-sysdump-20221120-234817.zip](https://github.com/cilium/cilium/files/10054452/cilium-sysdump-20221120-234817.zip)

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by squeed**
The Cilium agent already supports a mode where it waits for a certain CNI network to exist, then injects itself as a chained plugin, and writes a new file. However, this was only only supported for AWS. Instead, let's make this functionality generic.

This PR makes these changes:
- plugins/cni: improve logic around chaining mode. Previously, we would use the **cni network name** to decide what chaining mode to use. This makes it impossible to chain off of arbitrary networks. So, make the chaining mode an optional explicit parameter
- Add an explicit chaining-target parameter, and generalize the aws-cni injection code to support arbitrary networks
- wire this all up in Helm

The end result is a cleaner setup for end-users who would like to chain Cilium.

Fixes: #22286
Inspired-by: #22358

```release-note
Cilium now supports chaining with arbitrary CNI plugins. To use, set the Helm value cni.chainingTarget.
```

### CODE REVIEW

**Comment by squeed** [comment]
fyi @sofat1989, do you want to see if this covers your use case?

**Review by asauber — APPROVED** [review]
CLI related changed LGTM. I'll read through to see if I have any other comments, and leave reviews of other portions to the related codeowners.

File: daemon/cmd/cni/cell.go [hunk 1]
```diff
@@ -62,6 +64,14 @@ func enableConfigManager(lc hive.Lifecycle, log logrus.FieldLogger, cfg Config,
 }
 
 func newConfigManager(log logrus.FieldLogger, cfg Config, debug bool) *cniConfigManager {
+	if cfg.CNIChainingMode == "aws-cni" {
```
Comment (asauber) [inline daemon/cmd/cni/cell.go]: How about `if cfg.CNIChainingMode == "aws-cni" && cfg.CNIChainingTarget == ""` ? This gives us some flexibility in case the name is changed.

That being said it looks vanishingly unlikely https://github.com/aws/amazon-vpc-cni-k8s/blob/f3859a56cffa22cff07c541b1c95ec8d32c9bb18/misc/10-aws.conflist

**Review by rolinh — APPROVED** [review]
vendor changes lgtm

File: daemon/cmd/cni/cell.go (hunk 1 above)
Comment (squeed) [reply daemon/cmd/cni/cell.go]: nevertheless, good point. :+1:

**Review by kaworu — APPROVED** [review]
Helm changes LGTM

File: daemon/cmd/cni/cell.go [hunk 2]
```diff
@@ -52,6 +53,7 @@ func (cfg Config) Flags(flags *pflag.FlagSet) {
 	flags.String(option.ReadCNIConfiguration, defaultConfig.ReadCNIConf, fmt.Sprintf("CNI configuration file to use as a source for --%s. If not supplied, a suitable one will be generated.", option.WriteCNIConfigurationWhenReady))
 	flags.String(option.CNIChainingMode, defaultConfig.CNIChainingMode, "Enable CNI chaining with the specified plugin")
 	flags.String(option.CNILogFile, defaultConfig.CNILogFile, "Path where the CNI plugin should write logs")
+	flags.String(option.CNIChainingTarget, defaultConfig.CNIChainingTarget, "CNI network name in to which we should insert the Cilium chained configuration. Use '*' to select any network.")
```
Comment (zacharysarah) [inline daemon/cmd/cni/cell.go]: typo, clarity
```suggestion
	flags.String(option.CNIChainingTarget, defaultConfig.CNIChainingTarget, "CNI network name into which to insert the Cilium chained configuration. Use '*' to select any network.")
```

**Review by zacharysarah — APPROVED** [review]
Nits for typos and clarity, otherwise LGTM :+1: 

Approved preemptively with the understanding that changes must happen prior to merge.

**Review by qmonnet — APPROVED** [review]

File: daemon/cmd/cni/config.go [hunk 3]
```diff
@@ -301,45 +302,52 @@ func (c *cniConfigManager) renderCNIConf() (cniConfig []byte, err error) {
...
 
-// mergeExistingAWSCNIConfig looks for an existing AWS cni configuration file
+// mergeExistingCNIConfig looks for an existing AWS cni configuration file
 // and modifies it to include Cilium. This is because they do something
 // "special" for v6-only clusters.
 //
 // cniDir is the directory in the container to look for AWS CNI config, and
 // pluginConfig is the raw json to insert
 //
 // See PR #18522 for details.
```
Comment (youngnick) [inline daemon/cmd/cni/config.go]: Nit: Feels like this could do with an update?

File: daemon/cmd/cni/config.go [hunk 4]
```diff
@@ -301,45 +302,52 @@ func (c *cniConfigManager) renderCNIConf() (cniConfig []byte, err error) {
...
-		return nil, fmt.Errorf("failed to modify existing AWS CNI config at %s: %w", found, err)
+		return nil, fmt.Errorf("failed to modify existing CNI config: %w", err)
 	}
-	c.log.Infof("Inserting cilium in to CNI configuration file at %s", found)
+	c.log.Infof("Generated chained cilium CNI configuration from %s", c.config.CNIChainingTarget)
 	return out, nil
 }
 
 // renderCNITemplate applies any cni template replacements
 // right now, just sets .Debug and Logfile
```
Comment (youngnick) [inline daemon/cmd/cni/config.go]: Nit: Sets ChainingMode now too.

**Review by youngnick — APPROVED** [review]
LGTM with a couple of nits.

File: daemon/cmd/cni/config.go (hunk 3 above)
Comment (squeed) [reply daemon/cmd/cni/config.go]: argh yes, very good catch.
