### PR TITLE
pkg/client/client.go: Set EnabledProtocols when pointer is nil

### LINKED ISSUE #15617: EnabledProtocols is nil when using an cilium-agent which is not aware of the field definition
The commit [14ced84](https://github.com/cilium/cilium/commit/14ced84f7ef847350de8606b9e3159151a365531) have introduced two new flags `enable-ipv6-masquerade` and `enable-ipv4-masquerade` with default values (true). However, if someone makes a mistake mixing the versions of cilium-agent and cilium (cli), e.g. by applying  

```kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.9/install/kubernetes/quick-install.yaml``` 

right after build the current master - v1.10 (from git), the running cilium-agent (v1.9) will not be aware of Masquerading.EnabledProtocols. So this field will have the default value for the type (nil).

https://github.com/cilium/cilium/blob/c603c5e378b2ecdfbc0367d85f18fe7bf1ff4fe2/api/v1/models/masquerading.go#L31

As a consequence, we can have an invalid memory access on client.go.

https://github.com/cilium/cilium/blob/c603c5e378b2ecdfbc0367d85f18fe7bf1ff4fe2/pkg/client/client.go#L408

```
cilium status
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xaebe23]
goroutine 1 [running]:
github.com/cilium/cilium/pkg/client.FormatStatusResponse(0x25db460, 0xc00057d600, 0xc0000dd130, 0x0)
	/home/vagrant/go/src/github.com/cilium/cilium/pkg/client/client.go:408 +0x7a3
github.com/cilium/cilium/cilium/cmd.statusDaemon()
	/home/vagrant/go/src/github.com/cilium/cilium/cilium/cmd/status.go:102 +0x33e
github.com/cilium/cilium/cilium/cmd.glob..func73(0x36033a0, 0x3b8c978, 0x0, 0x0)
	/home/vagrant/go/src/github.com/cilium/cilium/cilium/cmd/status.go:37 +0x25
github.com/spf13/cobra.(*Command).execute(0x36033a0, 0x3b8c978, 0x0, 0x0, 0x36033a0, 0x3b8c978)
	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x3601ea0, 0x3633800, 0x0, 0xc00006e778)
	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/vagrant/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:895
github.com/cilium/cilium/cilium/cmd.Execute()
	/home/vagrant/go/src/github.com/cilium/cilium/cilium/cmd/root.go:47 +0x31
main.main()
	/home/vagrant/go/src/github.com/cilium/cilium/cilium/main.go:22 +0x25
```

The fix seems to be as simple as checking the pointer before using, or just ensure it is initialized after some previous initialization.

### PR DESCRIPTION
**Pull request by chkhalt**
When running cilium-agent <= v1.9.5, a request to /healthz returns a json which does not have the field masquerading.enabledProtocols. But if the same machine has a version of cilium (cli) > v1.9.5, after GET /healthz, it will create a StatusResponse without set the pointer Masquerading.EnabledProtocols.

In this case, ~~we allocate a new struct and fill IPV4 and IPV6 with the value from~~ set `status` based on Masquerading.Enabled. 

Fixes: #15617

Signed-off-by: Joao Victorino <joao@accuknox.com>

### CODE REVIEW

File: pkg/client/client.go [hunk 1]
```diff
@@ -405,6 +405,13 @@ func FormatStatusResponse(w io.Writer, sr *models.StatusResponse, sd StatusDetai
...
+		if sr.Masquerading.EnabledProtocols == nil {
+			sr.Masquerading.EnabledProtocols = &models.MasqueradingEnabledProtocols{
+				IPV4: sr.Masquerading.Enabled,
+				IPV6: sr.Masquerading.Enabled,
+			}
+		}
+
 		if !sr.Masquerading.EnabledProtocols.IPV4 && !sr.Masquerading.EnabledProtocols.IPV6 {
 			status = enabled(false)
 		} else {
```
Comment (aanm) [inline pkg/client/client.go]: Shouldn't the fix be this? :thinking: 
```suggestion
		if sr.Masquerading.EnabledProtocols == nil {
			status = enabled(false)
		} else if !sr.Masquerading.EnabledProtocols.IPV4 && !sr.Masquerading.EnabledProtocols.IPV6 {
			status = enabled(false)
		} else {
```

Comment (chkhalt) [reply pkg/client/client.go]: Yeah, it really makes more sense. I will fix that. Thanks @aanm!

Comment (chkhalt) [reply pkg/client/client.go]: Actually, the pointer can be nil even when masquerading is enabled. My first code was able to catch this point. Does it make sense?

Comment (chkhalt) [reply pkg/client/client.go]: IMHO, the pointer be nil is just a hint that the running agente is not able to inform which protocols masquerading is enabled for. Because it just has a global flag (--masquerading) to enable/disable.

Comment (chkhalt) [reply pkg/client/client.go]: @aanm ... what you think about ```status = enabled(sr.Masquerading.Enabled)```? Inside the check you've suggested.

Comment (aanm) [reply pkg/client/client.go]: ah, that makes sense yes!

Comment (chkhalt) [reply pkg/client/client.go]: @aanm Done!

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Review by nathanjsweet — APPROVED** [review]

**Comment by aanm** [comment]
dropping backport label as explained here https://github.com/cilium/cilium/pull/15830#issuecomment-824995949
