### PR TITLE
bandwidth: fix FQ qdisc setup on bond devices

### LINKED ISSUE #45283: Packets only enter a single FQ qdisc when bandwidth manager is enabled on bond device.
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.19.2 and lower than v1.20.0

### What happened?

The `tc -s qdisc show dev bond` command shows that only one FQ qdisc is sending packets.

Bond devices use the TX 0 queue by default. a single FQ qdisc can easily cause increased latency. 
```
static u16 bond_select_queue(struct net_device *dev, struct sk_buff *skb,
			     struct net_device *sb_dev)
{
	/* This helper function exists to help dev_pick_tx get the correct
	 * destination queue.  Using a helper function skips a call to
	 * skb_tx_hash and will put the skbs in the queue we expect on their
	 * way down to the bonding driver.
	 */
	u16 txq = skb_rx_queue_recorded(skb) ? skb_get_rx_queue(skb) : 0;

	/* Save the original txq to restore before passing to the driver */
	qdisc_skb_cb(skb)->slave_dev_queue_mapping = skb_get_queue_mapping(skb);

	if (unlikely(txq >= dev->real_num_tx_queues)) {
		do {
			txq -= dev->real_num_tx_queues;
		} while (txq >= dev->real_num_tx_queues);
	}
	return txq;
}
```
https://github.com/torvalds/linux/blob/master/drivers/net/bonding/bond_main.c#L5384-L5403

I'd like to know if the FQ qdisc should be created on the bond slave device instead of the bond master device, or do we have any better suggestions?

### How can we reproduce the issue?

1.  config linux bond
2. enable bandwidth manager on bond device
3. check the FQ qdisc statistics on bond device

### Cilium Version

1.12（new version also seems to have this problem）

### Kernel Version

5.15

### Kubernetes Version

1.28

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ssam18**
When the bandwidth manager runs on a bond device, all outgoing traffic ends up in a single FQ qdisc because bond_select_queue always returns TX queue 0. This happens because the EDT code resets queue_mapping to 0 after reading the endpoint ID, which makes the multi-queue setup on the bond master pointless.

The fix installs FQ qdiscs on the bond slave devices instead, where physical NIC drivers do proper hash-based queue selection across multiple queues. The skb->tstamp departure time set by the TC BPF program survives through the bond's internal transmission path to the slave, so EDT pacing continues to work correctly.

Fixes: #45283.

### CODE REVIEW

File: pkg/datapath/linux/bandwidth/ops.go [hunk 1]
```diff
@@ -51,6 +51,76 @@ func (ops *ops) Update(ctx context.Context, txn statedb.ReadTxn, _ statedb.Revis
...
+	for _, slave := range slaves {
+		if err := ops.setupFQOnLink(slave, q); err != nil {
+			return fmt.Errorf("bond slave %s: %w", slave.Attrs().Name, err)
+		}
+	}
+	return nil
+}
+
+func (ops *ops) bondSlaves(bond netlink.Link) ([]netlink.Link, error) {
+	allLinks, err := safenetlink.LinkList()
```
Comment (joamaki) [inline pkg/datapath/linux/bandwidth/ops.go]: As we already pull link/route/addr data from the kernel into internal StateDB tables it would be slightly better to query the `Table[*Device]` instead of doing a LinkList. This can be done by wiring in `*statedb.DB` and `statedb.Table[*tables.Device]` into `ops` and using the `txn` passed to `Update` to query against the device table (`for dev := range ops.devices.All(txn) { ... }`). I think it should have the necessary fields (https://github.com/cilium/cilium/blob/main/pkg/datapath/tables/device.go#L106).

File: pkg/datapath/linux/bandwidth/ops.go [hunk 2]
```diff
@@ -51,6 +51,76 @@ func (ops *ops) Update(ctx context.Context, txn statedb.ReadTxn, _ statedb.Revis
...
+	return ops.setupFQOnLink(link, q)
+}
+
+func (ops *ops) updateBondDevice(bond netlink.Link, q *tables.BandwidthQDisc) error {
+	slaves, err := ops.bondSlaves(bond)
+	if err != nil {
+		return err
+	}
+
+	if len(slaves) == 0 {
```
Comment (joamaki) [inline pkg/datapath/linux/bandwidth/ops.go:66]: Would it make sense to just do nothing (or ensure "noqueue") instead of doing this?

**Review by joamaki — CHANGES_REQUESTED** [review]
Thanks!

**Review by joamaki — APPROVED** [review]
Thanks looks great now! The commit messages just need to be fixed. The subject must be below 75 characters to pass "Check Patch". Would also be nice if you could squash these commits into one and add `Fixes: 450a5418493 ("bandwidth: Reconciler for qdisc setup")` to the message.

**Review by pchaigno — CHANGES_REQUESTED** [review]
Thanks for the fix!

Could you add more context to the commit descriptions? The context in the pull request description is good but should be in the commit descriptions as well. Each description should answer *Why* the commit is needed.

**Comment by pchaigno** [comment]
cc @borkmann

**Review by pchaigno — APPROVED** [review]
Thanks!
