### PR TITLE
Fix regression to avoid freeing alive IPs

### LINKED ISSUE #10065: Alive IP can be released if CNI DELETE is called with stale result
It has been observed that kubelet calls `CNI DELETE` multiple times with potentially stale CNI result information. This can lead to a race condition where the initial CNI DELETE properly releases the IP in use which then gets reused by a different pod. Any subsequent CNI DELETE with the stale IP will then cause the IP of the live pod to be released. While the pod will continue to function, the next scheduled pod will attempt to use that IP and continuously fail to be scheduled due to a `IP in use` error.

This is a regression of commit ab61853ca324711582f1af64018315e8499dc28e which introduced the ability for CNI DELETE to release an IP even if the endpoint deletion fails which is required to fix the race condition when the CNI binary gets killed in between allocating an IP and creating the endpoint.

### PR DESCRIPTION
**Pull request by tgraf**
This is a replacement fix for ab61853ca3 which turned out to be racy, leading
to alive PodIPs to be freed. Instead of attempting to reconstruct the context
for potential release in CNI DEL for any failure scenarios, introduce an
expiration timer that is enabled when any IP is allocated via the CNI plugin.
The expiration timer must be explicitly stopped by the endpoint creation
following the allocation to avoid releasing the IP again after a timeout. This
ensures that IPs are always either used or released without requiring any
cleanup from the CNI plugin itself.

In the event that an IP is released due to expiration but then the endpoint
still succeeds to be created, the endpoint creation will fail, triggering a
re-creation of the endpoint.

Fixes: #10065

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10207)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

File: pkg/ipam/allocator.go [hunk 1]
```diff
@@ -277,3 +313,72 @@ func (ipam *IPAM) Dump() (allocv4 map[string]string, allocv6 map[string]string,
...
+		ipam.allocatorMutex.Lock()
+		defer ipam.allocatorMutex.Unlock()
+
+		if currentUUID, ok := ipam.expirationTimers[ipString]; ok {
+			if currentUUID == allocationUUID {
+				scopedLog := log.WithFields(logrus.Fields{"ip": ipString, "uuid": allocationUUID})
+				if err := ipam.releaseIPLocked(ip); err != nil {
+					scopedLog.WithError(err).Warning("Unable to release IP after expiration")
+				}
+				scopedLog.Warning("Released IP after expiration")
```
Comment (aanm) [inline pkg/ipam/allocator.go]: line 352 should be in an else, otherwise both Warning messages will be confusing

File: pkg/ipam/allocator.go [hunk 2]
```diff
@@ -182,10 +184,36 @@ func (ipam *IPAM) AllocateNext(family, owner string) (ipv4Result, ipv6Result *Al
...
+
+	if timeout != time.Duration(0) {
+		for _, result := range []*AllocationResult{ipv4Result, ipv6Result} {
+			if result != nil {
+				defer func(result *AllocationResult) {
+					if err != nil {
+						ipam.ReleaseIP(result.IP)
+					}
+				}(result)
+
```
Comment (aanm) [inline pkg/ipam/allocator.go]: This defer is confusing because it's not really needed since we are early returning on line 207.

Also, what happens if `ipam.StartExpirationTimer(result.IP, timeout)` fails for the `ipv4result`? When will `ipv6Result` be released?

**Comment by tgraf** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by mrostecki** [comment]
I'm trying to backport this one, but I think we need also #8016, since it depends on the `Allocator` interface.

**Comment by mrostecki** [comment]
Probably also needs:

#8146
#9102

**Comment by joestringer** [comment]
Due to the complexity of backporting, I nominate dropping the 1.5 backport for this PR.

Users that are affected by this issue can update to a recent v1.6.x or v1.7.x release to address this issue.
