### PR TITLE
datapath/linux: return errors when unable to setup encrypt interface

### LINKED ISSUE #13555: Enabling encryption crashes the Cilium operator on Azure with native IPAM (1.9.0-rc1)
## Bug report

All Cilium agents crash on startup when transparent encryption is enabled on Azure (aks) using native IPAM.

**General Information**

- Cilium version
```
Client: 1.9.0-rc1 9ab7bfc94 2020-10-12T16:22:19-07:00 go version go1.15.2 linux/amd64
Daemon: 1.9.0-rc1 9ab7bfc94 2020-10-12T16:22:19-07:00 go version go1.15.2 linux/amd64
```

- Kernel version
```
Linux aks-nodepool1-28902834-vmss000000 4.15.0-1096-azure #106~16.04.1-Ubuntu SMP Thu Sep 10 18:51:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

- Kubernetes version
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:18:16Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"3a3612132641768edd7f7e73d07772225817f630", GitTreeState:"clean", BuildDate:"2020-09-02T06:46:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**How to reproduce the issue**

1. Install Cilium on Azure using native IPAM: https://docs.cilium.io/en/latest/gettingstarted/k8s-install-azure/
2. Enable transparent encryption: https://docs.cilium.io/en/latest/gettingstarted/encryption/

Expected result:
Cilum runs with transparent encryption enabled.

Observed result:
The Cilium agents are unable to start. The cilium-sysdump tool leaks at least one secret (the Azure client secret is an environment variable in the pod, which seems like a bad idea and is dumped as part of the pod yaml) so I won't be including that. Here's the log for one of the agents:

```
level=info msg="Skipped reading configuration file" reason="Config File \"ciliumd\" Not Found in \"[/root]\"" subsys=config
level=info msg="Memory available for map entries (0.003% of 7284367360B): 18210918B" subsys=config
level=info msg="option bpf-ct-global-tcp-max set by dynamic sizing to 131072" subsys=config
level=info msg="option bpf-ct-global-any-max set by dynamic sizing to 65536" subsys=config
level=info msg="option bpf-nat-global-max set by dynamic sizing to 131072" subsys=config
level=info msg="option bpf-neigh-global-max set by dynamic sizing to 131072" subsys=config
level=info msg="option bpf-sock-rev-map-max set by dynamic sizing to 65536" subsys=config
level=info msg="  --agent-health-port='9876'" subsys=daemon
level=info msg="  --agent-labels=''" subsys=daemon
level=info msg="  --allow-icmp-frag-needed='true'" subsys=daemon
level=info msg="  --allow-localhost='auto'" subsys=daemon
level=info msg="  --annotate-k8s-node='true'" subsys=daemon
level=info msg="  --api-rate-limit='map[]'" subsys=daemon
level=info msg="  --auto-create-cilium-node-resource='true'" subsys=daemon
level=info msg="  --auto-direct-node-routes='false'" subsys=daemon
level=info msg="  --blacklist-conflicting-routes='false'" subsys=daemon
level=info msg="  --bpf-compile-debug='false'" subsys=daemon
level=info msg="  --bpf-ct-global-any-max='262144'" subsys=daemon
level=info msg="  --bpf-ct-global-tcp-max='524288'" subsys=daemon
level=info msg="  --bpf-ct-timeout-regular-any='1m0s'" subsys=daemon
level=info msg="  --bpf-ct-timeout-regular-tcp='6h0m0s'" subsys=daemon
level=info msg="  --bpf-ct-timeout-regular-tcp-fin='10s'" subsys=daemon
level=info msg="  --bpf-ct-timeout-regular-tcp-syn='1m0s'" subsys=daemon
level=info msg="  --bpf-ct-timeout-service-any='1m0s'" subsys=daemon
level=info msg="  --bpf-ct-timeout-service-tcp='6h0m0s'" subsys=daemon
level=info msg="  --bpf-fragments-map-max='8192'" subsys=daemon
level=info msg="  --bpf-lb-maglev-hash-seed='FYJf2hrSynYxcZrkMWTGYA=='" subsys=daemon
level=info msg="  --bpf-lb-maglev-table-size='16381'" subsys=daemon
level=info msg="  --bpf-lb-map-max='65536'" subsys=daemon
level=info msg="  --bpf-map-dynamic-size-ratio='0.0025'" subsys=daemon
level=info msg="  --bpf-nat-global-max='524288'" subsys=daemon
level=info msg="  --bpf-neigh-global-max='524288'" subsys=daemon
level=info msg="  --bpf-policy-map-max='16384'" subsys=daemon
level=info msg="  --bpf-root=''" subsys=daemon
level=info msg="  --bpf-sock-rev-map-max='262144'" subsys=daemon
level=info msg="  --certificates-directory='/var/run/cilium/certs'" subsys=daemon
level=info msg="  --cgroup-root=''" subsys=daemon
level=info msg="  --cluster-id='0'" subsys=daemon
level=info msg="  --cluster-name='default'" subsys=daemon
level=info msg="  --clustermesh-config='/var/lib/cilium/clustermesh/'" subsys=daemon
level=info msg="  --cmdref=''" subsys=daemon
level=info msg="  --config=''" subsys=daemon
level=info msg="  --config-dir='/tmp/cilium/config-map'" subsys=daemon
level=info msg="  --conntrack-gc-interval='0s'" subsys=daemon
level=info msg="  --datapath-mode='veth'" subsys=daemon
level=info msg="  --debug='false'" subsys=daemon
level=info msg="  --debug-verbose=''" subsys=daemon
level=info msg="  --device=''" subsys=daemon
level=info msg="  --devices=''" subsys=daemon
level=info msg="  --direct-routing-device=''" subsys=daemon
level=info msg="  --disable-cnp-status-updates='true'" subsys=daemon
level=info msg="  --disable-conntrack='false'" subsys=daemon
level=info msg="  --disable-endpoint-crd='false'" subsys=daemon
level=info msg="  --disable-envoy-version-check='false'" subsys=daemon
level=info msg="  --disable-iptables-feeder-rules=''" subsys=daemon
level=info msg="  --disable-k8s-services='false'" subsys=daemon
level=info msg="  --egress-masquerade-interfaces=''" subsys=daemon
level=info msg="  --enable-auto-protect-node-port-range='true'" subsys=daemon
level=info msg="  --enable-bandwidth-manager='true'" subsys=daemon
level=info msg="  --enable-bpf-clock-probe='true'" subsys=daemon
level=info msg="  --enable-bpf-masquerade='true'" subsys=daemon
level=info msg="  --enable-bpf-tproxy='true'" subsys=daemon
level=info msg="  --enable-endpoint-health-checking='true'" subsys=daemon
level=info msg="  --enable-endpoint-routes='true'" subsys=daemon
level=info msg="  --enable-external-ips='true'" subsys=daemon
level=info msg="  --enable-health-check-nodeport='true'" subsys=daemon
level=info msg="  --enable-health-checking='true'" subsys=daemon
level=info msg="  --enable-host-firewall='false'" subsys=daemon
level=info msg="  --enable-host-legacy-routing='false'" subsys=daemon
level=info msg="  --enable-host-port='true'" subsys=daemon
level=info msg="  --enable-host-reachable-services='false'" subsys=daemon
level=info msg="  --enable-hubble='true'" subsys=daemon
level=info msg="  --enable-identity-mark='true'" subsys=daemon
level=info msg="  --enable-ip-masq-agent='false'" subsys=daemon
level=info msg="  --enable-ipsec='true'" subsys=daemon
level=info msg="  --enable-ipv4='true'" subsys=daemon
level=info msg="  --enable-ipv4-fragment-tracking='true'" subsys=daemon
level=info msg="  --enable-ipv6='false'" subsys=daemon
level=info msg="  --enable-ipv6-ndp='false'" subsys=daemon
level=info msg="  --enable-k8s-api-discovery='false'" subsys=daemon
level=info msg="  --enable-k8s-endpoint-slice='true'" subsys=daemon
level=info msg="  --enable-k8s-event-handover='false'" subsys=daemon
level=info msg="  --enable-l7-proxy='true'" subsys=daemon
level=info msg="  --enable-local-node-route='false'" subsys=daemon
level=info msg="  --enable-monitor='true'" subsys=daemon
level=info msg="  --enable-node-port='false'" subsys=daemon
level=info msg="  --enable-policy='default'" subsys=daemon
level=info msg="  --enable-remote-node-identity='true'" subsys=daemon
level=info msg="  --enable-selective-regeneration='true'" subsys=daemon
level=info msg="  --enable-session-affinity='true'" subsys=daemon
level=info msg="  --enable-svc-source-range-check='true'" subsys=daemon
level=info msg="  --enable-tracing='false'" subsys=daemon
level=info msg="  --enable-well-known-identities='false'" subsys=daemon
level=info msg="  --enable-xt-socket-fallback='true'" subsys=daemon
level=info msg="  --encrypt-interface='eth0'" subsys=daemon
level=info msg="  --encrypt-node='false'" subsys=daemon
level=info msg="  --endpoint-interface-name-prefix='lxc+'" subsys=daemon
level=info msg="  --endpoint-queue-size='25'" subsys=daemon
level=info msg="  --endpoint-status=''" subsys=daemon
level=info msg="  --envoy-log=''" subsys=daemon
level=info msg="  --exclude-local-address=''" subsys=daemon
level=info msg="  --fixed-identity-mapping='map[]'" subsys=daemon
level=info msg="  --flannel-master-device=''" subsys=daemon
level=info msg="  --flannel-uninstall-on-exit='false'" subsys=daemon
level=info msg="  --force-local-policy-eval-at-source='true'" subsys=daemon
level=info msg="  --host-reachable-services-protos='tcp,udp'" subsys=daemon
level=info msg="  --http-403-msg=''" subsys=daemon
level=info msg="  --http-idle-timeout='0'" subsys=daemon
level=info msg="  --http-max-grpc-timeout='0'" subsys=daemon
level=info msg="  --http-request-timeout='3600'" subsys=daemon
level=info msg="  --http-retry-count='3'" subsys=daemon
level=info msg="  --http-retry-timeout='0'" subsys=daemon
level=info msg="  --hubble-disable-tls='false'" subsys=daemon
level=info msg="  --hubble-event-queue-size='0'" subsys=daemon
level=info msg="  --hubble-flow-buffer-size='4095'" subsys=daemon
level=info msg="  --hubble-listen-address=':4244'" subsys=daemon
level=info msg="  --hubble-metrics='dns,drop,tcp,flow,port-distribution,icmp,http'" subsys=daemon
level=info msg="  --hubble-metrics-server=':9091'" subsys=daemon
level=info msg="  --hubble-socket-path='/var/run/cilium/hubble.sock'" subsys=daemon
level=info msg="  --hubble-tls-cert-file='/var/lib/cilium/tls/hubble/server.crt'" subsys=daemon
level=info msg="  --hubble-tls-client-ca-files='/var/lib/cilium/tls/hubble/client-ca.crt'" subsys=daemon
level=info msg="  --hubble-tls-key-file='/var/lib/cilium/tls/hubble/server.key'" subsys=daemon
level=info msg="  --identity-allocation-mode='crd'" subsys=daemon
level=info msg="  --identity-change-grace-period='5s'" subsys=daemon
level=info msg="  --install-iptables-rules='true'" subsys=daemon
level=info msg="  --ip-allocation-timeout='2m0s'" subsys=daemon
level=info msg="  --ip-masq-agent-config-path='/etc/config/ip-masq-agent'" subsys=daemon
level=info msg="  --ipam='azure'" subsys=daemon
level=info msg="  --ipsec-key-file='/etc/ipsec/keys'" subsys=daemon
level=info msg="  --iptables-lock-timeout='5s'" subsys=daemon
level=info msg="  --ipv4-node='auto'" subsys=daemon
level=info msg="  --ipv4-pod-subnets=''" subsys=daemon
level=info msg="  --ipv4-range='auto'" subsys=daemon
level=info msg="  --ipv4-service-loopback-address='169.254.42.1'" subsys=daemon
level=info msg="  --ipv4-service-range='auto'" subsys=daemon
level=info msg="  --ipv6-cluster-alloc-cidr='f00d::/64'" subsys=daemon
level=info msg="  --ipv6-mcast-device=''" subsys=daemon
level=info msg="  --ipv6-node='auto'" subsys=daemon
level=info msg="  --ipv6-pod-subnets=''" subsys=daemon
level=info msg="  --ipv6-range='auto'" subsys=daemon
level=info msg="  --ipv6-service-range='auto'" subsys=daemon
level=info msg="  --ipvlan-master-device='undefined'" subsys=daemon
level=info msg="  --join-cluster='false'" subsys=daemon
level=info msg="  --k8s-api-server=''" subsys=daemon
level=info msg="  --k8s-force-json-patch='false'" subsys=daemon
level=info msg="  --k8s-heartbeat-timeout='30s'" subsys=daemon
level=info msg="  --k8s-kubeconfig-path=''" subsys=daemon
level=info msg="  --k8s-namespace='kube-system'" subsys=daemon
level=info msg="  --k8s-require-ipv4-pod-cidr='false'" subsys=daemon
level=info msg="  --k8s-require-ipv6-pod-cidr='false'" subsys=daemon
level=info msg="  --k8s-service-cache-size='128'" subsys=daemon
level=info msg="  --k8s-service-proxy-name=''" subsys=daemon
level=info msg="  --k8s-sync-timeout='3m0s'" subsys=daemon
level=info msg="  --k8s-watcher-endpoint-selector='metadata.name!=kube-scheduler,metadata.name!=kube-controller-manager,metadata.name!=etcd-operator,metadata.name!=gcp-controller-manager'" subsys=daemon
level=info msg="  --k8s-watcher-queue-size='1024'" subsys=daemon
level=info msg="  --keep-config='false'" subsys=daemon
level=info msg="  --kube-proxy-replacement='probe'" subsys=daemon
level=info msg="  --kvstore=''" subsys=daemon
level=info msg="  --kvstore-connectivity-timeout='2m0s'" subsys=daemon
level=info msg="  --kvstore-lease-ttl='15m0s'" subsys=daemon
level=info msg="  --kvstore-opt='map[]'" subsys=daemon
level=info msg="  --kvstore-periodic-sync='5m0s'" subsys=daemon
level=info msg="  --label-prefix-file=''" subsys=daemon
level=info msg="  --labels=''" subsys=daemon
level=info msg="  --lib-dir='/var/lib/cilium'" subsys=daemon
level=info msg="  --log-driver=''" subsys=daemon
level=info msg="  --log-opt='map[]'" subsys=daemon
level=info msg="  --log-system-load='false'" subsys=daemon
level=info msg="  --masquerade='false'" subsys=daemon
level=info msg="  --max-controller-interval='0'" subsys=daemon
level=info msg="  --metrics=''" subsys=daemon
level=info msg="  --monitor-aggregation='medium'" subsys=daemon
level=info msg="  --monitor-aggregation-flags='all'" subsys=daemon
level=info msg="  --monitor-aggregation-interval='5s'" subsys=daemon
level=info msg="  --monitor-queue-size='0'" subsys=daemon
level=info msg="  --mtu='0'" subsys=daemon
level=info msg="  --nat46-range='0:0:0:0:0:FFFF::/96'" subsys=daemon
level=info msg="  --native-routing-cidr=''" subsys=daemon
level=info msg="  --node-port-acceleration='disabled'" subsys=daemon
level=info msg="  --node-port-algorithm='random'" subsys=daemon
level=info msg="  --node-port-bind-protection='true'" subsys=daemon
level=info msg="  --node-port-mode='snat'" subsys=daemon
level=info msg="  --node-port-range='30000,32767'" subsys=daemon
level=info msg="  --policy-audit-mode='false'" subsys=daemon
level=info msg="  --policy-queue-size='100'" subsys=daemon
level=info msg="  --policy-trigger-interval='1s'" subsys=daemon
level=info msg="  --pprof='false'" subsys=daemon
level=info msg="  --preallocate-bpf-maps='false'" subsys=daemon
level=info msg="  --prefilter-device='undefined'" subsys=daemon
level=info msg="  --prefilter-mode='native'" subsys=daemon
level=info msg="  --prepend-iptables-chains='true'" subsys=daemon
level=info msg="  --prometheus-serve-addr=''" subsys=daemon
level=info msg="  --proxy-connect-timeout='1'" subsys=daemon
level=info msg="  --proxy-prometheus-port='0'" subsys=daemon
level=info msg="  --read-cni-conf=''" subsys=daemon
level=info msg="  --restore='true'" subsys=daemon
level=info msg="  --sidecar-istio-proxy-image='cilium/istio_proxy'" subsys=daemon
level=info msg="  --single-cluster-route='false'" subsys=daemon
level=info msg="  --skip-crd-creation='false'" subsys=daemon
level=info msg="  --socket-path='/var/run/cilium/cilium.sock'" subsys=daemon
level=info msg="  --sockops-enable='false'" subsys=daemon
level=info msg="  --state-dir='/var/run/cilium'" subsys=daemon
level=info msg="  --tofqdns-dns-reject-response-code='refused'" subsys=daemon
level=info msg="  --tofqdns-enable-dns-compression='true'" subsys=daemon
level=info msg="  --tofqdns-endpoint-max-ip-per-hostname='50'" subsys=daemon
level=info msg="  --tofqdns-max-deferred-connection-deletes='10000'" subsys=daemon
level=info msg="  --tofqdns-min-ttl='0'" subsys=daemon
level=info msg="  --tofqdns-pre-cache=''" subsys=daemon
level=info msg="  --tofqdns-proxy-port='0'" subsys=daemon
level=info msg="  --tofqdns-proxy-response-max-delay='100ms'" subsys=daemon
level=info msg="  --trace-payloadlen='128'" subsys=daemon
level=info msg="  --tunnel='disabled'" subsys=daemon
level=info msg="  --version='false'" subsys=daemon
level=info msg="  --write-cni-conf-when-ready=''" subsys=daemon
level=info msg="     _ _ _" subsys=daemon
level=info msg=" ___|_| |_|_ _ _____" subsys=daemon
level=info msg="|  _| | | | | |     |" subsys=daemon
level=info msg="|___|_|_|_|___|_|_|_|" subsys=daemon
level=info msg="Cilium 1.9.0-rc1 9ab7bfc94 2020-10-12T16:22:19-07:00 go version go1.15.2 linux/amd64" subsys=daemon
level=info msg="cilium-envoy  version: 1177896bebde79915fe5f9092409bf0254084b4e/1.14.5/Modified/RELEASE/BoringSSL" subsys=daemon
level=info msg="clang (10.0.0) and kernel (4.15.0) versions: OK!" subsys=linux-datapath
level=info msg="linking environment: OK!" subsys=linux-datapath
level=info msg="BPF system config check: NOT OK." error="Kernel Config file not found" subsys=linux-datapath
level=info msg="Detected mounted BPF filesystem at /sys/fs/bpf" subsys=bpf
level=info msg="Valid label prefix configuration:" subsys=labels-filter
level=info msg=" - :io.kubernetes.pod.namespace" subsys=labels-filter
level=info msg=" - :io.cilium.k8s.namespace.labels" subsys=labels-filter
level=info msg=" - :app.kubernetes.io" subsys=labels-filter
level=info msg=" - !:io.kubernetes" subsys=labels-filter
level=info msg=" - !:kubernetes.io" subsys=labels-filter
level=info msg=" - !:.*beta.kubernetes.io" subsys=labels-filter
level=info msg=" - !:k8s.io" subsys=labels-filter
level=info msg=" - !:pod-template-generation" subsys=labels-filter
level=info msg=" - !:pod-template-hash" subsys=labels-filter
level=info msg=" - !:controller-revision-hash" subsys=labels-filter
level=info msg=" - !:annotation.*" subsys=labels-filter
level=info msg=" - !:etcd_node" subsys=labels-filter
level=warning msg="The bandwidth manager cannot be used with IPSec. Disabling the bandwidth manager." subsys=daemon
level=info msg="Using autogenerated IPv4 allocation range" subsys=node v4Prefix=10.35.0.0/16
level=info msg="Disabled support for BPF TProxy due to missing kernel support for socket assign (Linux 5.7 or later)" subsys=daemon
level=info msg="Initializing daemon" subsys=daemon
level=info msg="Establishing connection to apiserver" host="https://eyvind-ist-eyvind-test-531564-86e62833.hcp.northeurope.azmk8s.io:443" subsys=k8s
level=info msg="Connected to apiserver" subsys=k8s
level=info msg="Unable to retrieve EndpointSlices for default/kubernetes. Disabling EndpointSlices" error="endpointslices.discovery.k8s.io \"kubernetes\" not found" subsys=k8s
level=info msg="Inheriting MTU from external network interface" device=azure0 ipAddr=10.240.0.35 mtu=1500 subsys=mtu
level=info msg="Trying to auto-enable \"enable-node-port\", \"enable-external-ips\", \"enable-host-reachable-services\", \"enable-host-port\", \"enable-session-affinity\" features" subsys=daemon
level=warning msg="IPSec cannot be used with BPF NodePort. Disabling BPF NodePort feature." subsys=daemon
level=warning msg="BPF host reachable services for TCP needs kernel 4.17.0 or newer. Disabling the feature." subsys=daemon
level=warning msg="BPF host reachable services for UDP needs kernel 4.19.57, 5.1.16, 5.2.0 or newer. If you run an older kernel and only need TCP, then specify: --host-reachable-services-protos=tcp and --kube-proxy-replacement=partial Disabling the feature." subsys=daemon
level=info msg="Restored services from maps" failed=0 restored=8 subsys=service
level=info msg="Reading old endpoints..." subsys=daemon
level=info msg="Envoy: Starting xDS gRPC server listening on /var/run/cilium/xds.sock" subsys=envoy-manager
level=info msg="Reusing previous DNS proxy port: 41073" subsys=daemon
level=info msg="Retrieved node information from kubernetes node" nodeName=aks-nodepool1-28902834-vmss000001 subsys=k8s
level=info msg="Received own node information from API server" ipAddr.ipv4=10.240.0.35 ipAddr.ipv6="<nil>" k8sNodeIP=10.240.0.35 labels="map[agentpool:nodepool1 beta.kubernetes.io/arch:amd64 beta.kubernetes.io/instance-type:Standard_DS2_v2 beta.kubernetes.io/os:linux failure-domain.beta.kubernetes.io/region:northeurope failure-domain.beta.kubernetes.io/zone:0 kubernetes.azure.com/cluster:MC_eyvind-test_eyvind-istio-test_northeurope kubernetes.azure.com/mode:system kubernetes.azure.com/node-image-version:AKSUbuntu-1604-2020.09.30 kubernetes.azure.com/role:agent kubernetes.io/arch:amd64 kubernetes.io/hostname:aks-nodepool1-28902834-vmss000001 kubernetes.io/os:linux kubernetes.io/role:agent node-role.kubernetes.io/agent: node.kubernetes.io/instance-type:Standard_DS2_v2 storageprofile:managed storagetier:Premium_LRS topology.kubernetes.io/region:northeurope topology.kubernetes.io/zone:0]" nodeName=aks-nodepool1-28902834-vmss000001 subsys=k8s v4Prefix=10.35.0.0/16 v6Prefix="<nil>"
level=info msg="k8s mode: Allowing localhost to reach local endpoints" subsys=daemon
level=info msg="Enabling k8s event listener" subsys=k8s-watcher
level=info msg="Removing stale endpoint interfaces" subsys=daemon
level=info msg="Initializing node addressing" subsys=daemon
level=info msg="Restored router address from device" device=cilium_host ipv4=10.240.0.50 ipv6="<nil>" subsys=node
level=info msg="Initializing CRD-based IPAM" subsys=ipam
level=info msg="Subscribed to CiliumNode custom resource" name=aks-nodepool1-28902834-vmss000001 subsys=ipam
level=info msg="Creating or updating CiliumNode resource" node=aks-nodepool1-28902834-vmss000001 subsys=nodediscovery
level=info msg="Waiting until all pre-existing resources related to policy have been received" subsys=k8s-watcher
level=info msg="Policy Add Request" ciliumNetworkPolicy="[&{EndpointSelector:{\"matchLabels\":{\"k8s:component\":\"tunnel\",\"k8s:io.kubernetes.pod.namespace\":\"kube-system\"}} NodeSelector:{} Ingress:[] IngressDeny:[] Egress:[{EgressCommonRule:{ToEndpoints:[{}] ToRequires:[] ToCIDR: ToCIDRSet:[] ToEntities:[] ToServices:[] ToGroups:[] AggregatedSelectors:[]} ToPorts:[] ToFQDNs:[]}] EgressDeny:[] Labels:[k8s:io.cilium.k8s.policy.derived-from=NetworkPolicy k8s:io.cilium.k8s.policy.name=tunnelfront k8s:io.cilium.k8s.policy.namespace=kube-system k8s:io.cilium.k8s.policy.uid=76c6d3f4-9f3f-48fa-80d5-2f2311d44b70] Description:}]" policyAddRequest=342374e2-0dfc-11eb-a744-000d3ad803f2 subsys=daemon
level=info msg="Policy imported via API, recalculating..." policyAddRequest=342374e2-0dfc-11eb-a744-000d3ad803f2 policyRevision=2 subsys=daemon
level=warning msg="Failed to send policy update as monitor notification" policyAddRequest=342374e2-0dfc-11eb-a744-000d3ad803f2 policyRevision=2 subsys=daemon
level=info msg="NetworkPolicy successfully added" k8sApiVersion= k8sNetworkPolicyName=tunnelfront subsys=k8s-watcher
level=info msg="Waiting for CiliumNode custom resource to become available..." name=aks-nodepool1-28902834-vmss000001 subsys=ipam
level=info msg="All pre-existing resources related to policy have been received; continuing" subsys=k8s-watcher
level=info msg="Successfully synchronized CiliumNode custom resource" name=aks-nodepool1-28902834-vmss000001 subsys=ipam
level=info msg="All required IPs are available in CRD-backed allocation pool" available=31 name=aks-nodepool1-28902834-vmss000001 required=8 subsys=ipam
level=info msg="Restoring endpoints..." subsys=daemon
level=error msg="Unable to enqueue endpoint policy visibility event" containerID=19fb21b8ff datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=745 error="unable to Enqueue event" identity=13259 ipv4=10.240.0.36 ipv6= k8sPodName=kube-system/coredns-869cb84759-h6jzx subsys=endpoint
level=error msg="Unable to enqueue endpoint policy bandwidth event" containerID=19fb21b8ff datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=745 error="unable to Enqueue event" identity=13259 ipv4=10.240.0.36 ipv6= k8sPodName=kube-system/coredns-869cb84759-h6jzx subsys=endpoint
level=error msg="Unable to enqueue endpoint policy visibility event" containerID=4c74986233 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2127 error="unable to Enqueue event" identity=51696 ipv4=10.240.0.44 ipv6= k8sPodName=kube-system/hubble-relay-5bfd4567f4-gkmlc subsys=endpoint
level=error msg="Unable to enqueue endpoint policy bandwidth event" containerID=4c74986233 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2127 error="unable to Enqueue event" identity=51696 ipv4=10.240.0.44 ipv6= k8sPodName=kube-system/hubble-relay-5bfd4567f4-gkmlc subsys=endpoint
level=info msg="Endpoints restored" failed=0 restored=3 subsys=daemon
level=info msg="Addressing information:" subsys=daemon
level=info msg="  Cluster-Name: default" subsys=daemon
level=info msg="  Cluster-ID: 0" subsys=daemon
level=info msg="  Local node-name: aks-nodepool1-28902834-vmss000001" subsys=daemon
level=info msg="  Node-IPv6: <nil>" subsys=daemon
level=info msg="  External-Node IPv4: 10.240.0.35" subsys=daemon
level=info msg="  Internal-Node IPv4: 10.240.0.50" subsys=daemon
level=info msg="  IPv4 allocation prefix: 10.35.0.0/16" subsys=daemon
level=info msg="  Loopback IPv4: 169.254.42.1" subsys=daemon
level=info msg="  Local IPv4 addresses:" subsys=daemon
level=info msg="  - 10.240.0.35" subsys=daemon
level=info msg="  - 10.240.0.50" subsys=daemon
level=info msg="Annotating k8s node" subsys=daemon v4CiliumHostIP.IPv4=10.240.0.50 v4Prefix=10.35.0.0/16 v4healthIP.IPv4=10.240.0.52 v6CiliumHostIP.IPv6="<nil>" v6Prefix="<nil>" v6healthIP.IPv6="<nil>"
level=info msg="Skipping kvstore configuration" subsys=daemon
level=info msg="Creating or updating CiliumNode resource" node=aks-nodepool1-28902834-vmss000001 subsys=nodediscovery
level=info msg="Adding local node to cluster" node="{aks-nodepool1-28902834-vmss000001 default [{InternalIP 10.240.0.35} {CiliumInternalIP 10.240.0.50}] 10.35.0.0/16 <nil> 10.240.0.52 <nil> 0 local 3 map[agentpool:nodepool1 beta.kubernetes.io/arch:amd64 beta.kubernetes.io/instance-type:Standard_DS2_v2 beta.kubernetes.io/os:linux failure-domain.beta.kubernetes.io/region:northeurope failure-domain.beta.kubernetes.io/zone:0 kubernetes.azure.com/cluster:MC_eyvind-test_eyvind-istio-test_northeurope kubernetes.azure.com/mode:system kubernetes.azure.com/node-image-version:AKSUbuntu-1604-2020.09.30 kubernetes.azure.com/role:agent kubernetes.io/arch:amd64 kubernetes.io/hostname:aks-nodepool1-28902834-vmss000001 kubernetes.io/os:linux kubernetes.io/role:agent node-role.kubernetes.io/agent: node.kubernetes.io/instance-type:Standard_DS2_v2 storageprofile:managed storagetier:Premium_LRS topology.kubernetes.io/region:northeurope topology.kubernetes.io/zone:0] 0}" subsys=nodediscovery
level=info msg="Initializing identity allocator" subsys=identity-cache
level=info msg="Cluster-ID is not specified, skipping ClusterMesh initialization" subsys=daemon
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/cilium/cilium/pkg/datapath/linux/config.(*HeaderfileWriter).WriteNodeConfig(0x3fe5bb0, 0x29366c0, 0xc00000f450, 0xc000a769a8, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/pkg/datapath/linux/config/config.go:366 +0x726c
github.com/cilium/cilium/daemon/cmd.(*Daemon).createNodeConfigHeaderfile(0xc00000a1e0, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/daemon/cmd/datapath.go:71 +0x3e7
github.com/cilium/cilium/daemon/cmd.(*Daemon).init(0xc00000a1e0, 0x3a8a9a0, 0x3a7a720)
	/go/src/github.com/cilium/cilium/daemon/cmd/daemon.go:212 +0x6a6
github.com/cilium/cilium/daemon/cmd.NewDaemon(0x2993920, 0xc0000b2c00, 0xc0008fc2c0, 0x29c80a0, 0xc0008af030, 0xc000362d80, 0x29c80a0, 0xc0008af030, 0xc0001f7740)
	/go/src/github.com/cilium/cilium/daemon/cmd/daemon.go:645 +0x1ddd
github.com/cilium/cilium/daemon/cmd.runDaemon()
	/go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1335 +0x51a
github.com/cilium/cilium/daemon/cmd.glob..func1(0x3a66a00, 0xc00044b6d0, 0x0, 0x1)
	/go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:124 +0x12f
github.com/spf13/cobra.(*Command).execute(0x3a66a00, 0xc0000b6010, 0x1, 0x1, 0x3a66a00, 0xc0000b6010)
	/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x3a66a00, 0xc0009fa900, 0x4472aa, 0x39b9f00)
	/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:887
github.com/cilium/cilium/daemon/cmd.Execute()
	/go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:149 +0x5f
main.main()
	/go/src/github.com/cilium/cilium/daemon/main.go:22 +0x25
```

### PR DESCRIPTION
**Pull request by aanm**
When unable to setup the encryption interface we should error out
prematurely so the user will be aware of the possible errors with the
encryption interface set.

Signed-off-by: André Martins <andre@cilium.io>
Fixes https://github.com/cilium/cilium/issues/13555
```release-note
Fixes panic when setting up encryption with azure IPAM
```

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

File: pkg/datapath/linux/config/config.go [hunk 1]
```diff
@@ -356,13 +356,19 @@ func (h *HeaderfileWriter) WriteNodeConfig(w io.Writer, cfg *datapath.LocalNodeC
...
+		link, err := netlink.LinkByName(iface)
 		if err == nil {
 			cDefinesMap["ENCRYPT_IFACE"] = fmt.Sprintf("%d", link.Attrs().Index)
 
 			addr, err := netlink.AddrList(link, netlink.FAMILY_V4)
+			if err != nil {
+				return err
+			}
 			if err == nil {
+				if len(addr) == 0 {
```
Comment (christarazi) [inline pkg/datapath/linux/config/config.go]:
```suggestion
			} else if len(addr) == 0 /* && if err == nil */ {
```

**Review by christarazi — APPROVED** [review]
LGTM. One small nit.

File: pkg/datapath/linux/config/config.go [hunk 2]
```diff
@@ -356,13 +356,19 @@ func (h *HeaderfileWriter) WriteNodeConfig(w io.Writer, cfg *datapath.LocalNodeC
 		cDefinesMap["ENABLE_HOST_FIREWALL"] = "1"
 	}
 
-	if option.Config.EncryptInterface != "" {
-		link, err := netlink.LinkByName(option.Config.EncryptInterface)
+	if iface := option.Config.EncryptInterface; iface != "" {
+		link, err := netlink.LinkByName(iface)
```
Comment (jrfastab) [inline pkg/datapath/linux/config/config.go:360]: I was tempted to say we should throw an error here, but it I think its OK to try defaults if the link specified doesn't exist. At least we've been doing it this way so probably best to leave it.

**Review by jrfastab — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

File: pkg/datapath/linux/config/config.go (hunk 2 above)
Comment (kkourt) [reply pkg/datapath/linux/config/config.go:360]: I know it's merged already, but to me it feels counter-intuitive to silently ignore the iface that the user suggested. Maybe add a warning if the link does not exist?
