### PR TITLE
ctmap: add support for GC of DSR orphaned entries

### LINKED ISSUE #21346: Ephemeral ports of an egress ip may be exhausted in NAT mapping table
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We observed drop SYN packet in cilium pod of **egress gateway**, and reason was "**No mapping for NAT masquerade**".
After received the error message, we show the **nat mapping** table by filtering a egress ip, specific target and target port.

>Cilium nat table information likes below
> cilium bpf nat list | grep '[target ip]:[target port]' | grep 'XLATE_SRC' | sort -k7
> TCP OUT xxx.xxxx.xxx.xxx:32768 -> [target ip]:[target port] XLATE_SRC [egress ip]:**32768** Created=2719514sec HostLocal=0
>.
>.
>.
>TCP OUT xxx.xxxx.xxx.xxx:32768 -> [target ip]:[target port] XLATE_SRC [egress ip]:**60999** Created=2719514sec HostLocal=0

Thus, we guess the ephemeral ports of a specific egress ip are exhausted, and source ports of egress ip would not be recycled/deleted in nat mapping table after a period of time.
Is there maybe a bug or garbage collect is not working?

### Cilium Version

1.11.8

### Kernel Version

5.13.0-40-generic

### Kubernetes Version

v1.21.14

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

Scenario:
image

**How to reproduce?**

1. Create a web service in cluster outside.
2. Deploy a pod which can use curl command and apply CiliumEgressNATPolicy through egress ip to web service.
3. Execute bash command in the pod.
    Repeat curl web service until total of running times exceed **_28231_**.
   (Hint: ephemeral port range: net.ipv4.ip_local_port_range = 32768    60999)
   `for i in {1..5000}; do [[ $(( $i % 1000 )) -eq 0 ]] && echo $i; curl -sI target ip]:[target port] > /dev/null; done &`

4. In cilium pod of egress gateway, you can observe nat mapping variation.
>cilium bpf nat list | grep '[target ip]:[target port]' | grep 'XLATE_SRC' | sort -k7
>TCP OUT xxx.xxxx.xxx.xxx:32768 -> [target ip]:[target port] XLATE_SRC [egress ip]:32768 Created=2719514sec HostLocal=0
>.
>.
>.
>TCP OUT xxx.xxxx.xxx.xxx:32768 -> [target ip]:[target port] XLATE_SRC [egress ip]:60999 Created=2719514sec HostLocal=0`

5. Create another pod and also curl same target and destination port,
We would receive error msg: "reason No mapping for NAT masquerade" from cilium pod of egress gateway node.
(e.g. cilium monitor -t drop -vv)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jibi**
Let's start from some context: normally, when traffic on a node needs to
get SNAT-ed by the datapath, the following map entries get created:

CT table:

  | Dir | Source      | Destination |
  | --- | ----------- | ----------- |
  | OUT | src IP/port | dst IP/port |

NAT table:

  | Dir | Source      | Destination | Xlate target          |
  | --- | ----------- | ----------- | --------------------- |
  | OUT | src IP/port | dst IP/port | XLATE_SRC nat IP/port |
  | IN  | dst IP/port | nat IP/port | XLATE_DST src IP/port |

Given this, the current algorithm to clear orphan NAT entries (i.e.
entries that are not backed anymore by a related CT one) can be
described as follow:

for each ingress NAT entry:
  - derive the related egress CT key:

        source      = ingress NAT entry xlate target
        destination = ingress NAT entry source

  - if there's no entry for the egress CT key
    - derive the related egress NAT entry (aka original tuple/ingress
      reverse tuple):

          source       = ingress NAT entry xlate targe
          destination  = ingress NAT entry source
          xlate target = ingress NAT entry destination

    - delete both ingress and egress NAT entries

This commit is about adding support for collecting orphaned NAT entries
created by the DSR loadbalancer mode.

In DSR mode, when a client connects to a NodePort service, the traffic
flow will be something like:

- client connects to a second node where the NodePort service is running
- this second node selects a backend and (unless the backend is running
  locally) forwards the traffic to a third node where the backend is
  running, while:
  - keeping the original client source IP
  - encoding the original destination in an IP option
  - rewriting the destination to the backend IP
- in the third node, the original destination is extracted from the IP
  option and the following bpf entries are created:

CT table:

  | Dir | Source      | Destination | Flags |
  | --- | ----------- | ----------- | ----- |
  | IN  | src IP/port | dst IP/port | DSR   |

NAT:

  | Dir | Source      | Destination | Xlate target     |
  | --- | ----------- | ----------- | ---------------- |
  | OUT | dst IP/port | src IP/port | XLATE_SRC nat IP |

  where:

  - src IP is the IP of the client
  - dst IP is the IP of the backend running on the node
  - nat IP is the IP of the nodeport node (second node), which was
    encoded by the node itself in an IP option before forwarding traffic
    to the third node.
    This is used to implement DSR as the reply traffic leaving the
    current node is forwarded back to the original client with this IP
    as source

Considering the entries that get created by the regular (i.e. non DSR)
NAT operations, to implement GC of the DSR SNAT entries we can extend
the algorithm as follows:

for each egress NAT entry:
  - derive the related ingress CT key:

        source      = ingress NAT entry destination
        destination = ingress NAT entry source

  - derive the related egress CT key:

        source      = ingress NAT entry source
        destination = ingress NAT entry destination

  - if both the ingress and egress CT keys don't have a corresponding
    entry:
    - delete the egress NAT entry

If both ingress and egress CT keys for a given NAT entry don't exist we
can assume the entry is orphan, as the lack of the ingress key will
cover the DSR case while the lack of the egress key will cover the
"regular" one.

There's one last catch: to simplify this writing, we discussed the
_logical_ content of the CT keys, but in practice every key has the
source and destination addresses swapped because of the way the datapath
creates these entries.

Fixes: https://github.com/cilium/cilium/issues/21346

### CODE REVIEW

**Comment by jibi** [comment]
/test-1.16-4.9

**Comment by jibi** [comment]
/test-1.23-5.4

File: pkg/maps/ctmap/ctmap.go [hunk 1]
```diff
@@ -627,6 +620,21 @@ func PurgeOrphanNATEntries(ctMapTCP, ctMapAny *Map) *NatGCStats {
 				}
 			} else {
 				stats.IngressAlive += 1
+				stats.EgressAlive += 1
```
Comment (julianwiedmann) [inline pkg/maps/ctmap/ctmap.go]: This is because we assume that such ingress NAT entry always has a related egress NAT entry, correct? Why can't we handle this in the case below, once we visit that egress NAT entry?

File: pkg/maps/ctmap/ctmap.go [hunk 2]
```diff
@@ -627,6 +620,21 @@ func PurgeOrphanNATEntries(ctMapTCP, ctMapAny *Map) *NatGCStats {
...
+			}
+		} else if natKey.GetFlags()&tuple.TUPLE_F_OUT == tuple.TUPLE_F_OUT {
+			ingressNatKey := ingressNatKeyFromEgressNatKeyVal(natKey, natVal)
```
Comment (julianwiedmann) [inline pkg/maps/ctmap/ctmap.go]: For my understanding - instead of checking for "no Ingress CT entry AND no Ingress NAT entry", we could also check for "no Ingress CT entry AND no Egress CT entry". Correct?

Should we raise some warning if we find an Ingress CT entry, but the entry doesn't have the DSR flag?

**Review by julianwiedmann — COMMENTED** [review]
Thanks @jibi! This all sounds sane, but some questions to make sure my understanding is correct ...

File: pkg/maps/ctmap/ctmap.go (hunk 1 above)
Comment (jibi) [reply pkg/maps/ctmap/ctmap.go]: Right, we are already accounting for this in the case below, I should remove it :+1:

File: pkg/maps/ctmap/ctmap.go (hunk 2 above)
Comment (jibi) [reply pkg/maps/ctmap/ctmap.go]: >For my understanding - instead of checking for "no Ingress CT entry AND no Ingress NAT entry", we could also check for "no Ingress CT entry AND no Egress CT entry". Correct?

Yep, that is correct also to my understanding :+1: 

I decided to go for the CT and NAT entries check to make it more explicit (i.e. it's a DSR SNAT entry and it doesn't have a related NAT entry), but perhaps once we are happy with this we can evaluate the incress/egress CT check and maybe unify the 2 cases (just food for thoughts)

> Should we raise some warning if we find an Ingress CT entry, but the entry doesn't have the DSR flag?

I'm not sure here, I would imagine it's possible to have ingress CT entries without NAT being involved

Comment (julianwiedmann) [reply pkg/maps/ctmap/ctmap.go]: > > For my understanding - instead of checking for "no Ingress CT entry AND no Ingress NAT entry", we could also check for "no Ingress CT entry AND no Egress CT entry". Correct?
> 
> Yep, that is correct also to my understanding +1
> 
> I decided to go for the CT and NAT entries check to make it more explicit (i.e. it's a DSR SNAT entry and it doesn't have a related NAT entry), 

yeah, that's what I figured :). I understand where you're coming from (focusing it exactly on how the situation looks like for DSR). But I feel the reasoning "if there's no ingress CT and no egress CT, then obviously this NAT entry is stale" is more straight-forward, and requires less understanding of how NAT/CT works for DSR in detail. Maybe that tips the balance, both approaches being equal? Either way is alright.


> > Should we raise some warning if we find an Ingress CT entry, but the entry doesn't have the DSR flag?
> 
> I'm not sure here, I would imagine it's possible to have ingress CT entries without NAT being involved

Ah sorry. I specifically meant for the "we are dealing with a DSR entry" path. Here it would be nice to know if we unexpectedly match something that's **not** DSR.

Comment (jibi) [reply pkg/maps/ctmap/ctmap.go]: > I feel the reasoning "if there's no ingress CT and no egress CT, then obviously this NAT entry is stale" is more straight-forward, and requires less understanding of how NAT/CT works for DSR in detail

Fair enough, my initial aim was to narrow down the changes to the DSR case in order to avoid introducing regressions in the logic already in place, but now that we have a clearer picture of what's going on with these entries I'm mostly convinced that approach should be fine as well, so I'll give it a try :+1: 

> Ah sorry. I specifically meant for the "we are dealing with a DSR entry" path. Here it would be nice to know if we unexpectedly match something that's not DSR.

Got it (but switching to checking only CT entries means we can't detect this case anymore)

**Comment by jibi** [comment]
/test-1.16-4.9

File: pkg/maps/ctmap/ctmap.go [hunk 3]
```diff
@@ -628,6 +621,19 @@ func PurgeOrphanNATEntries(ctMapTCP, ctMapAny *Map) *NatGCStats {
...
+		} else if natKey.GetFlags()&tuple.TUPLE_F_OUT == tuple.TUPLE_F_OUT {
+			ingressCTKey := ingressCTKeyFromEgressNatKey(natKey)
+			egressCTKey := egressCTKeyFromEgressNatKey(natKey)
+			if _, err := ctMap.Lookup(ingressCTKey); errors.Is(err, unix.ENOENT) {
+				if _, err := ctMap.Lookup(egressCTKey); errors.Is(err, unix.ENOENT) {
+					// No ingress and egress CT entries were found, delete the egress NAT entry
+					if deleted, _ := natMap.Delete(natKey); deleted {
+						stats.EgressDeleted += 1
+					}
+				}
```
Comment (julianwiedmann) [inline pkg/maps/ctmap/ctmap.go:626]: For the inner `if` condition we're missing an
```
} else {
	stats.EgressAlive += 1
}
```

But this is fixed up by the last patch in the series. Might still want to get it right here, so that we can revert without regression.

**Review by julianwiedmann — APPROVED** [review]
Thanks! Good call on doing the refactor at the end :+1:.

Just one minor thing that's worth addressing imho. But either way lgtm.

File: pkg/maps/ctmap/ctmap.go (hunk 3 above)
Comment (jibi) [reply pkg/maps/ctmap/ctmap.go:626]: Good shout, updated :+1:

**Comment by jibi** [comment]
CI was green, just fixed an intermediate commit which got overwritten by the refactoring in the last one (net result is no changes to the tree https://github.com/cilium/cilium/compare/dd7bcee3f55265f61125e03278d772d932d17861..97b3698c549332973bcbf0cbe686c2ff3d5d0c9c)

Marking as ready to merge
