### PR TITLE
Make LRP restore test logic robust and optimized

### LINKED ISSUE #16154: CI: K8sServicesTest Checks local redirect policy LRP restores service when removed
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.20-kernel-4.19/407/testReport/junit/Suite-k8s-1/20/K8sServicesTest_Checks_local_redirect_policy_LRP_restores_service_when_removed/
[27d7cbf5_K8sServicesTest_Checks_local_redirect_policy_LRP_restores_service_when_removed.zip](https://github.com/cilium/cilium/files/6479597/27d7cbf5_K8sServicesTest_Checks_local_redirect_policy_LRP_restores_service_when_removed.zip)

### Stacktrace
```
/home/jenkins/workspace/Cilium-PR-K8s-1.20-kernel-4.19/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:518
Timed out after 30.000s.
assertion fails for test case: {id=app1 curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 tftp://10.108.37.217:69/hello }
Expected
    <bool>: false
to be true
/home/jenkins/workspace/Cilium-PR-K8s-1.20-kernel-4.19/src/github.com/cilium/cilium/test/k8sT/Services.go:836
```
### Standard Output
```
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Cilium pods: [cilium-8g2gr cilium-h8k8c]
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
Pod                           Ingress   Egress
grafana-d69c97b9b-5pvf9                 
prometheus-655fb888d7-jsz7f             
k8s1-backend                            
k8s1-client                             
k8s2-backend                            
k8s2-client                             
coredns-867bf6789f-7zrs4                
Cilium agent 'cilium-8g2gr': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 39 Failed 0
Cilium agent 'cilium-h8k8c': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 33 Failed 0
```
### Standard Error
<details></summary>Click to show.</summary>

```
21:49:08 STEP: Checking traffic goes to both backends
FAIL: Timed out after 30.000s.
assertion fails for test case: {id=app1 curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 tftp://10.108.37.217:69/hello }
Expected
    <bool>: false
to be true
FAIL: Timed out after 30.000s.
assertion fails for test case: {id=app1 curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 tftp://10.108.37.217:69/hello }
Expected
    <bool>: false
to be true
=== Test Finished at 2021-05-12T21:49:38Z====
21:49:38 STEP: Running JustAfterEach block for EntireTestsuite K8sServicesTest
===================== TEST FAILED =====================
21:49:38 STEP: Running AfterFailed block for EntireTestsuite K8sServicesTest
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE           NAME                              READY   STATUS    RESTARTS   AGE     IP              NODE   NOMINATED NODE   READINESS GATES
	 cilium-monitoring   grafana-d69c97b9b-5pvf9           1/1     Running   0          44m     10.0.0.143      k8s1   <none>           <none>
	 cilium-monitoring   prometheus-655fb888d7-jsz7f       1/1     Running   0          44m     10.0.0.66       k8s1   <none>           <none>
	 default             k8s1-backend                      2/2     Running   0          78s     10.0.0.175      k8s1   <none>           <none>
	 default             k8s1-client                       1/1     Running   0          78s     10.0.0.42       k8s1   <none>           <none>
	 default             k8s2-backend                      2/2     Running   0          78s     10.0.1.93       k8s2   <none>           <none>
	 default             k8s2-client                       1/1     Running   0          78s     10.0.1.151      k8s2   <none>           <none>
	 kube-system         cilium-8g2gr                      1/1     Running   0          2m20s   192.168.36.11   k8s1   <none>           <none>
	 kube-system         cilium-h8k8c                      1/1     Running   0          2m20s   192.168.36.12   k8s2   <none>           <none>
	 kube-system         cilium-operator-99bf8596f-fdxwx   1/1     Running   0          2m20s   192.168.36.11   k8s1   <none>           <none>
	 kube-system         cilium-operator-99bf8596f-z4q2m   1/1     Running   0          2m20s   192.168.36.12   k8s2   <none>           <none>
	 kube-system         coredns-867bf6789f-7zrs4          1/1     Running   0          43m     10.0.1.105      k8s2   <none>           <none>
	 kube-system         etcd-k8s1                         1/1     Running   0          47m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-apiserver-k8s1               1/1     Running   0          47m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-controller-manager-k8s1      1/1     Running   0          47m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-proxy-48s8f                  1/1     Running   0          46m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-proxy-4qnkq                  1/1     Running   0          45m     192.168.36.12   k8s2   <none>           <none>
	 kube-system         kube-scheduler-k8s1               1/1     Running   0          47m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         log-gatherer-cwkpv                1/1     Running   0          44m     192.168.36.12   k8s2   <none>           <none>
	 kube-system         log-gatherer-lmq5m                1/1     Running   0          44m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         registry-adder-btk8l              1/1     Running   0          45m     192.168.36.12   k8s2   <none>           <none>
	 kube-system         registry-adder-wl5nv              1/1     Running   0          45m     192.168.36.11   k8s1   <none>           <none>
	 
Stderr:
 	 

Fetching command output from pods [cilium-8g2gr cilium-h8k8c]
cmd: kubectl exec -n kube-system cilium-8g2gr -- cilium service list
Exitcode: 0 
Stdout:
 	 ID   Frontend            Service Type   Backend                   
	 1    10.96.0.1:443       ClusterIP      1 => 192.168.36.11:6443   
	 2    10.96.0.10:53       ClusterIP      1 => 10.0.1.105:53        
	 3    10.96.0.10:9153     ClusterIP      1 => 10.0.1.105:9153      
	 4    10.96.116.64:3000   ClusterIP      1 => 10.0.0.143:3000      
	 5    10.101.9.143:9090   ClusterIP      1 => 10.0.0.66:9090       
	 10   10.108.37.217:69    ClusterIP      1 => 10.0.0.175:69        
	                                         2 => 10.0.1.93:69         
	 11   10.108.37.217:80    ClusterIP      1 => 10.0.0.175:80        
	                                         2 => 10.0.1.93:80         
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-8g2gr -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                              IPv6       IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                   
	 79         Disabled           Disabled          13603      k8s:app=grafana                                          fd02::1d   10.0.0.143   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                 
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                          
	                                                            k8s:io.kubernetes.pod.namespace=cilium-monitoring                                        
	 888        Disabled           Disabled          38169      k8s:id=app1                                              fd02::56   10.0.0.42    ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                 
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                          
	                                                            k8s:io.kubernetes.pod.namespace=default                                                  
	                                                            k8s:role=frontend                                                                        
	 1170       Disabled           Disabled          12525      k8s:id=be1                                               fd02::a9   10.0.0.175   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                 
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                          
	                                                            k8s:io.kubernetes.pod.namespace=default                                                  
	                                                            k8s:role=backend                                                                         
	 1279       Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s1                                                       ready   
	                                                            k8s:node-role.kubernetes.io/control-plane                                                
	                                                            k8s:node-role.kubernetes.io/master                                                       
	                                                            reserved:host                                                                            
	 1404       Disabled           Disabled          4          reserved:health                                          fd02::a7   10.0.0.35    ready   
	 3162       Disabled           Disabled          50465      k8s:app=prometheus                                       fd02::3b   10.0.0.66    ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                 
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=prometheus-k8s                                   
	                                                            k8s:io.kubernetes.pod.namespace=cilium-monitoring                                        
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-h8k8c -- cilium service list
Exitcode: 0 
Stdout:
 	 ID   Frontend            Service Type   Backend                   
	 1    10.96.0.1:443       ClusterIP      1 => 192.168.36.11:6443   
	 2    10.96.0.10:53       ClusterIP      1 => 10.0.1.105:53        
	 3    10.96.0.10:9153     ClusterIP      1 => 10.0.1.105:9153      
	 4    10.96.116.64:3000   ClusterIP      1 => 10.0.0.143:3000      
	 5    10.101.9.143:9090   ClusterIP      1 => 10.0.0.66:9090       
	 10   10.108.37.217:80    ClusterIP      1 => 10.0.1.93:80         
	                                         2 => 10.0.0.175:80        
	 11   10.108.37.217:69    ClusterIP      1 => 10.0.1.93:69         
	                                         2 => 10.0.0.175:69        
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-h8k8c -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                       IPv6        IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                             
	 414        Disabled           Disabled          14501      k8s:io.cilium.k8s.policy.cluster=default          fd02::1ab   10.0.1.105   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=coredns                                    
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                        
	                                                            k8s:k8s-app=kube-dns                                                               
	 422        Disabled           Disabled          11844      k8s:id=app2                                       fd02::15f   10.0.1.151   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                           
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                    
	                                                            k8s:io.kubernetes.pod.namespace=default                                            
	                                                            k8s:role=frontend                                                                  
	 877        Disabled           Disabled          40435      k8s:id=be2                                        fd02::17c   10.0.1.93    ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                           
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                    
	                                                            k8s:io.kubernetes.pod.namespace=default                                            
	                                                            k8s:role=backend                                                                   
	 1239       Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s2                                                 ready   
	                                                            reserved:host                                                                      
	 2143       Disabled           Disabled          4          reserved:health                                   fd02::185   10.0.1.251   ready   
	 
Stderr:
 	 

===================== Exiting AfterFailed =====================
21:49:59 STEP: Running AfterEach for block EntireTestsuite K8sServicesTest
21:49:59 STEP: Running AfterEach for block EntireTestsuite
```
</details>

### PR DESCRIPTION
**Pull request by aditighag**
The goal of the test is to check if `curl` to a clusterIP svc endpoint is redirected to both the backends when the original svc entry is restored upon LRP removal. The current test logic expects the same backend should be selected for all the pod clients simultaneously, and this can lengthen test duration. This doesn't seem right since backend selection is not exactly deterministic. More importantly, we only need both backends to be selected at least once for all the client pods.

Flip the order in which we loop over backends and client pods.  Loop over client pods first, and then making curl calls to until we hit both the backends on each of the client pods. Also, keep state about which backends have been successfully tested in order to avoid making some of the duplicate `curl` calls, and make the test logic deterministic.

More details - https://github.com/cilium/cilium/issues/16154#issuecomment-842688720.

Deferred to a follow-up PR - Looking at the LRP [test case](https://github.com/cilium/cilium/blob/master/test/k8sT/Services.go#L773) where we check if traffic only goes to the local backend, it doesn't seem reliable since it's possible that the curl request that the test made wasn't redirected to the remote backend by chance. I think the reliable way to validate the correctness is to check for a `LocalRedirect` service entry and its corresponding backends in the `cilium service list `.

Fixes: #16154

### CODE REVIEW

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.* LRP" --kernel_version="net-next"

**Comment by aditighag** [comment]
LRP focused tests [passed](https://jenkins.cilium.io/job/Cilium-PR-Tests-Kernel-Focus/216/testReport/Suite-k8s-1/20/). Marking it as ready for review. /cc @Weil0ng

**Comment by aanm** [comment]
marking for backport as it failed in one backport PR https://github.com/cilium/cilium/pull/16210

File: test/k8sT/Services.go [hunk 1]
```diff
@@ -816,25 +816,25 @@ var _ = SkipDescribeIf(helpers.RunsOn54Kernel, "K8sServicesTest", func() {
...
 
 			var wg sync.WaitGroup
-			wg.Add(len(testCases) * 2)
-			for _, testCase := range testCases {
-				for _, name := range []string{be1Name, be2Name} {
-					go func(tc lrpTestCase, want string) {
+			for _, tc := range testCases {
+				pods, err := kubectl.GetPodNames(helpers.DefaultNamespace, tc.selector)
+				Expect(len(pods)).Should(BeNumerically(">", 0), "no pod exists by filter %q", tc.selector)
+				Expect(err).Should(BeNil(), "cannot retrieve pod names by filter %q", tc.selector)
```
Comment (joamaki) [inline test/k8sT/Services.go:821]: might be better to check err first to get slightly more useful output on failure, or was there a specific reason the order changed?

File: test/k8sT/Services.go [hunk 2]
```diff
@@ -816,25 +816,25 @@ var _ = SkipDescribeIf(helpers.RunsOn54Kernel, "K8sServicesTest", func() {
...
 						defer wg.Done()
 						Eventually(func() bool {
-							pods, err := kubectl.GetPodNames(helpers.DefaultNamespace, tc.selector)
-							Expect(err).Should(BeNil(), "cannot retrieve pod names by filter %q", tc.selector)
-							Expect(len(pods)).Should(BeNumerically(">", 0), "no pod exists by filter %q", tc.selector)
 							ret := true
-							for _, pod := range pods {
+							for _, want := range []string{be1Name, be2Name} {
 								res := kubectl.ExecPodCmd(helpers.DefaultNamespace, pod, tc.cmd)
 								Expect(err).To(BeNil(), "%s failed in %s pod", tc.cmd, pod)
```
Comment (joamaki) [inline test/k8sT/Services.go]: should `err` be `res`?

File: test/k8sT/Services.go [hunk 3]
```diff
@@ -816,25 +816,25 @@ var _ = SkipDescribeIf(helpers.RunsOn54Kernel, "K8sServicesTest", func() {
...
 								ret = ret && strings.Contains(res.Stdout(), want)
 							}
 							return ret
```
Comment (joamaki) [inline test/k8sT/Services.go]: does this return value go anywhere since we're inside `go` and `Eventually`?

**Review by joamaki — CHANGES_REQUESTED** [review]

**Review by Weil0ng — APPROVED** [review]
LGTM! Thanks for the fix, I think this is the correct test logic as you described.

**Review by nbusseneau — APPROVED** [review]
As discussed in the community meeting, rationale looks sensible to me. Thanks!

File: test/k8sT/Services.go (hunk 2 above)
Comment (aditighag) [reply test/k8sT/Services.go]: I didn't touch this code. But, yeah, the error check doesn't seem right. Good catch!

File: test/k8sT/Services.go (hunk 3 above)
Comment (aditighag) [reply test/k8sT/Services.go]: It's consumed by `Eventually` - https://pkg.go.dev/github.com/onsi/gomega#Eventually.

**Review by aditighag — COMMENTED** [review]
@joamaki  Thanks for the review, PTAL.

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.* LRP" --kernel_version="net-next"

**Review by joamaki — APPROVED** [review]

**Comment by pchaigno** [comment]
test-1.16-netnext

**Comment by pchaigno** [comment]
test-1.20-4.19

**Comment by pchaigno** [comment]
test-gke

**Comment by aditighag** [comment]
Test failures -

1.16-netnext : https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/576/console

>Setting status of 07392becc9d9752966c6bbf97d50391be02efea3 to FAILURE with url https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/576/ and message: 'Build finished. '
Using context: k8s-1.16-kernel-netnext (test-1.16-netnext)
Global Slack Notifier try posting to slack. However some error occurred
TeamDomain :cilium
Channel :#testing
Message :

java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)

1.20-net-next failure looks legit. Marking the PR as draft for now.

**Comment by aditighag** [comment]
Focused test runs passed - https://jenkins.cilium.io/job/Cilium-PR-Tests-Kernel-Focus/219/testReport/Suite-k8s-1/20/.

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.* LRP" --kernel_version="net-next"

**Comment by aditighag** [comment]
test-1.20-4.19

**Comment by aditighag** [comment]
test-gke

**Comment by aditighag** [comment]
I've made the test logic deterministic all the way. 3 successful runs of the LRP test - focused, test-1.20-4.19 and test-gke. Marking the PR as ready for review again.

**Review by joamaki — APPROVED** [review]

File: test/k8sT/Services.go [hunk 4]
```diff
@@ -757,8 +757,8 @@ var _ = SkipDescribeIf(helpers.RunsOn54Kernel, "K8sServicesTest", func() {
 			}
 
 			var wg sync.WaitGroup
-			wg.Add(len(testCases))
```
Comment (pchaigno) [inline test/k8sT/Services.go:760]: In this commit's description, f4c769 doesn't correspond to any commit on master.

**Comment by pchaigno** [comment]
test-1.16-netnext

**Review by Weil0ng — APPROVED** [review]

**Review by nbusseneau — APPROVED** [review]
LGTM, new version is easier to read as well, nice :)

**Comment by aditighag** [comment]
> I've made the test logic deterministic all the way. 3 successful runs of the LRP test - focused, test-1.20-4.19 and test-gke. Marking the PR as ready for review again.

Reviews are in.
4 successful test runs. 1.16-net-next failures are unrelated - LRP tests have [passed](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/607/testReport/Suite-k8s-1/16/)

I'll push a new commit to address Paul's [comment](https://github.com/cilium/cilium/pull/16194#discussion_r639518205) about incorrect "Fixes" commit SHA mentioned in the 1st commit.

**Review by michi-covalent — APPROVED** [review]

**Comment by pchaigno** [comment]
> I'll push a new commit to address Paul's comment about incorrect "Fixes" commit SHA mentioned in the 1st commit.

According to [the logs](https://github.com/cilium/cilium/compare/33e66585511bafbdaa660f0d5a9caa78fb5db7fd..4eb5dae1fb96565393ce8cdee0fb9814d091fd5e), you also rebased, so let's retrigger the e2e tests :disappointed:

**Comment by pchaigno** [comment]
test-gke

**Comment by pchaigno** [comment]
test-1.20-4.19

**Comment by pchaigno** [comment]
test-1.16-netnext

**Review by pchaigno — APPROVED** [review]

**Comment by aditighag** [comment]
> > I'll push a new commit to address Paul's comment about incorrect "Fixes" commit SHA mentioned in the 1st commit.
> 
> 
> 
> According to [the logs](https://github.com/cilium/cilium/compare/33e66585511bafbdaa660f0d5a9caa78fb5db7fd..4eb5dae1fb96565393ce8cdee0fb9814d091fd5e), you also rebased, so let's retrigger the e2e tests :disappointed: 


Why do we need to trigger the e2e tests? The changes are localized to only LRP test cases.

**Comment by pchaigno** [comment]
Because other changes included in the rebase could cause the test to fail (e.g., changes to the agent). The only case where we can merge without restarting tests is when [the diff](https://github.com/cilium/cilium/compare/33e66585511bafbdaa660f0d5a9caa78fb5db7fd..4eb5dae1fb96565393ce8cdee0fb9814d091fd5e) doesn't include any changes that is tested (e.g., only code comment or commit description changes). That's not the case with a rebase.

**Comment by aditighag** [comment]
Relevant tests have passed. Marking it as ready for merge again.
