### PR TITLE
endpoint: Fix goroutine leak when EP is deleted

### LINKED ISSUE #13680: Goroutine leak when waiting on endpoint's metadata resolver to terminate
When an endpoint is created, Cilium will kick off an async controller to fetch the pod labels. If Cilium is never able to fetch the pods labels, the controller will continue retrying forever, _even_ after the endpoint was deleted. This is because the following goroutine is stuck waiting on the `done` channel, which is never closed due to a persistently failing controller.

```go
func (e *Endpoint) RunMetadataResolver(resolveMetadata MetadataResolverCB) {
	done := make(chan struct{})
	controllerName := fmt.Sprintf("resolve-labels-%s", e.GetK8sNamespaceAndPodName())
	go func() {
		<-done
		e.controllers.RemoveController(controllerName)
	}()

	e.controllers.UpdateController(controllerName,
		controller.ControllerParams{
			DoFunc: func(ctx context.Context) error {
				ns, podName := e.GetK8sNamespace(), e.GetK8sPodName()
				pod, cp, identityLabels, info, _, err := resolveMetadata(ns, podName+"noway")
				if err != nil {
					e.Logger(controllerName).WithError(err).Warning("Unable to fetch kubernetes labels")
					return err
				}
				...
				e.UpdateLabels(ctx, identityLabels, info, true)
				close(done)
				return nil
			},
			RunInterval: 30 * time.Second,
			Context:     e.aliveCtx,
		},
	)
}
```

This can leave stack traces like:

```
goroutine 1244259 [chan receive, 1434 minutes]:
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).RunMetadataResolver.func1(0xc0055d2a20, 0xc0049ff600, 0xc0055d2ae0, 0x5d)
	/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:1531 +0x34
created by github.com/cilium/cilium/pkg/endpoint.(*Endpoint).RunMetadataResolver
	/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:1530 +0x11e
```

This goroutines can pile up and potentially could cause the Cilium process to exceed its expected memory usage.

### PR DESCRIPTION
**Pull request by christarazi**
The metadata resolver controller can be put in a scenario where it can
never succeed if the Cilium K8s pod cache is out-of-sync with the
current view of pods in the cluster. The cache can be out-of-sync if
there's heavy load on the cluster and especially on the apiserver. This
leaves the Cilium pod cache starved. When the pod cache is starved,
Cilium may never have an up-to-date view of the pods running in the
cluster, and therefore may never be able to resolve labels for pods
because the fetch will return "pod not found".

Eventually, kubelet (or maybe even the user) will give up on the pod and
remove it, thereby Cilium begins removing the endpoint. The controller
is stopped, but the goroutine waiting on the `done` channel will never
receive, hence the leak.

This commit fixes the goroutine leak when the controller never succeeds
and therefore, never closes the `done` channel. The fix is to add a
`select` statement to also watch the endpoint's `aliveCtx` which is
cancelled (and the context's `Done` channel is closed) when the endpoint
is deleted.

This commit was validated by forcing the metadata resolver to never find
a pod (manually hardcode the wrong pod name), and ensuring that the 
`gops stack` output does not contain an entry like:

```
goroutine 1244259 [chan receive, 1434 minutes]:
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).RunMetadataResolver.func1(0xc0055d2a20, 0xc0049ff600, 0xc0055d2ae0, 0x5d)
	/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:1531 +0x34
created by github.com/cilium/cilium/pkg/endpoint.(*Endpoint).RunMetadataResolver
	/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:1530 +0x11e
```

Fixes: https://github.com/cilium/cilium/issues/13680

```release-note
Fix bug where Cilium leaks a goroutine when an endpoint is deleted. This leak, if left running in a high pod churn environment, can cause Cilium to exceed its memory usage and get OOM killed.
```

### CODE REVIEW

**Comment by christarazi** [comment]
test-me-please

File: pkg/endpoint/endpoint.go [hunk 1]
```diff
@@ -1642,7 +1642,11 @@ func (e *Endpoint) RunMetadataResolver(resolveMetadata MetadataResolverCB) {
 	done := make(chan struct{})
 	controllerName := fmt.Sprintf("resolve-labels-%s", e.GetK8sNamespaceAndPodName())
 	go func() {
-		<-done
+		select {
+		case <-done:
+		case <-e.aliveCtx.Done():
+			return
```
Comment (joestringer) [inline pkg/endpoint/endpoint.go:1648]: I suspect that another option would be to add a `StopFunc` to the controller below to close `done`, though that said I don't think there should be a functional difference so I'm happy with this solution.

**Review by joestringer — APPROVED** [review]
LGTM. :shipit:

**Review by aanm — APPROVED** [review]

**Comment by christarazi** [comment]
test-gke

File: pkg/endpoint/endpoint.go (hunk 1 above)
Comment (christarazi) [reply pkg/endpoint/endpoint.go:1648]: Just for posterity, we could add a `StopFunc` to also close the `done` channel, but wouldn't work for the way we've set up this controller. Essentially, the configured run interval at 30s seems like it's there to provide a buffer for the initial run. Once it runs and succeeds, the controller closes `done` and returns, _and_ this would normally run again after 30s, but the goroutine is waiting for the `done` channel to be closed and removes the controller, thereby stopping it.

So having the close on `done` be inside `StopFunc` wouldn't work because we want to stop this controller as soon as it succeeds. 

I've prepared a commit to remove the interval because it is actually unnecessary. Waiting for CI to finish its run.

**Comment by christarazi** [comment]
test-me-please

**Comment by tklauser** [comment]
Not backporting this to 1.6 after out-of-band discussion with @christarazi. The build of backport PR #13870 currently fails. and 1.6 will become unsupported with the release of 1.9.
