### PR TITLE
cilium, ipsec: Do revalidate_data_pull() early in do_decrypt() case

### LINKED ISSUE #13528: CI: K8sDatapathConfig Transparent encryption DirectRouting Check connectivity with transparent encryption and direct routing
I've seen this in multiple PRs so definitely a flake. Note this appear to be different from #13430.

### Stacktrace
```
/home/jenkins/workspace/Cilium-PR-K8s-1.19-kernel-4.9/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
cilium pre-flight checks failed
Expected
    <*errors.errorString | 0xc00030c240>: {
        s: "Cilium validation failed: 4m0s timeout expired: Last polled error: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-28czp': Exitcode: 255 \nErr: exit status 255\nStdout:\n \t \nStderr:\n \t Error: Cannot get status/probe: Put \"http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe\": context deadline exceeded\n\t \n\t command terminated with exit code 255\n\t \n",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-K8s-1.19-kernel-4.9/src/github.com/cilium/cilium/test/helpers/manifest.go:316
```
### Standard Output
```
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
⚠️  Number of "level=warning" in logs: 7
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
Top 1 errors/warnings:
Mutation detector is enabled, this will result in memory leakage.
⚠️  Number of "context deadline exceeded" in logs: 24
⚠️  Number of "level=error" in logs: 17
⚠️  Number of "level=warning" in logs: 37
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
Top 5 errors/warnings:
Mutation detector is enabled, this will result in memory leakage.
insertNeighbor failed
Unable to enqueue endpoint policy visibility event
Unable to enqueue endpoint policy bandwidth event
SessionAffinity feature requires BPF LRU maps. Disabling the feature.
Cilium pods: [cilium-28czp cilium-qwq4q]
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
Pod                           Ingress   Egress
grafana-d69c97b9b-fw4ck                 
prometheus-655fb888d7-ks8f8             
coredns-867bf6789f-pw5f8                
Cilium agent 'cilium-28czp': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 27 Failed 0
Cilium agent 'cilium-qwq4q': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 22 Failed 0
```

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-4.9/752/testReport/junit/Suite-k8s-1/19/K8sDatapathConfig_Transparent_encryption_DirectRouting_Check_connectivity_with_transparent_encryption_and_direct_routing/
[6adc05ad_K8sDatapathConfig_Transparent_encryption_DirectRouting_Check_connectivity_with_transparent_encryption_and_direct_routing.zip](https://github.com/cilium/cilium/files/5369848/6adc05ad_K8sDatapathConfig_Transparent_encryption_DirectRouting_Check_connectivity_with_transparent_encryption_and_direct_routing.zip)
https://datastudio.google.com/s/tKc_PRLPvDs

### PR DESCRIPTION
**Pull request by jrfastab**
When we created a lib for encryption the pull_data call was pulled
into the per protocol cases versus being called regardless of if
its been decrypted already or not.

Lets pull it back to the previous location.

Next we returned a drop code DROP_INVALID incorrectly as well
so lets make that an accept return code. We shouldn't be dropping
packets from here, lets let the stack or upper layer Cilium code do
that if it needs to.

Finally for same reason above lets allow all non esp packets to
go up the stack. The will still hit a Cilium policy program later
so let that code work as expected.

Fixes #13528

Signed-off-by: John Fastabend <john.fastabend@gmail.com>

---

@nebril bisected an encryption failure back to this patch 7ba0e83acc458 and this corrects the difference between the old code and the new lib based code. However it seems that the pull should be unnecessary to me unless we have a miss in the cilium_host codebase as well?

### CODE REVIEW

**Comment by jrfastab** [comment]
retest-4.9

**Comment by jrfastab** [comment]
K8s-1.19-kernel-4.9 passed lets try again.

**Comment by jrfastab** [comment]
retest-4.9

**Comment by jrfastab** [comment]
tbd patch needs a fixes tag.

**Comment by jrfastab** [comment]
2/2 try again.

**Comment by jrfastab** [comment]
retest-4.9

**Comment by jrfastab** [comment]
3/3, try entire set now.

**Comment by jrfastab** [comment]
test-me-please

**Comment by nebril** [comment]
test-missed-k8s

**Comment by jrfastab** [comment]
test-missed-k8s

**Comment by jrfastab** [comment]
So test-missed-k8s failed on encryption tests lets try leaving the code refactor in place, but revert the host changes.

**Comment by jrfastab** [comment]
test-missed-k8s

**Comment by jrfastab** [comment]
test-missed-k8s

**Comment by jrfastab** [comment]
test-missed-k8s

**Comment by jrfastab** [comment]
test-missed-k8s

**Comment by jrfastab** [comment]
test-missed-k8s

**Comment by jrfastab** [comment]
test-missed-k8s

**Comment by jrfastab** [comment]
OK trying to revert most everything except translating existing bpf_network code to use a lib ./bpf/lib/encrypt.h I did see one difference which I resolved here between old and new code. Namely, when the pull_data fails we return DROP_INVALID which is not a real return code but lets do it here as well and see what we get.

**Comment by jrfastab** [comment]
test-missed-k8s

**Comment by jrfastab** [comment]
tested and have working version in local and gke.

**Comment by jrfastab** [comment]
test-missed-k8s

**Comment by jrfastab** [comment]
The failures are no longer encryption related lets run the larger suite.

**Comment by jrfastab** [comment]
test-me-please

File: bpf/lib/encrypt.h [hunk 1]
```diff
@@ -16,56 +16,62 @@
...
+	switch (proto) {
 #ifdef ENABLE_IPV6
-		case bpf_htons(ETH_P_IPV6):
-			if (!revalidate_data_pull(ctx, &data, &data_end, &ip6))
-				break;
-			protocol = ip6->nexthdr;
-			break;
+	case bpf_htons(ETH_P_IPV6):
+		if (!revalidate_data_pull(ctx, &data, &data_end, &ip6))
+			return CTX_ACT_OK;
```
Comment (joestringer) [inline bpf/lib/encrypt.h:36]: Do we need to clear `ctx->mark` in these cases?

**Review by joestringer — APPROVED** [review]
Minor query on ctx->mark handling in case where pulling fails, plus it would be nice to have the PR description text in the commit message as well just for git log background.

Oh and CI looks like it needs a look.

File: bpf/lib/encrypt.h (hunk 1 above)
Comment (jrfastab) [reply bpf/lib/encrypt.h:36]: Probably a nice touch to clear the mark so we don't try to decrypt a decrypted packet if the data_pull fails after encryption.

**Comment by jrfastab** [comment]
@joestringer wrt CI, none of those tests should even have encryption enabled.

**Comment by jrfastab** [comment]
Suite-k8s-1.13.K8sDatapathConfig Encapsulation Check vxlan connectivity with per-endpoint routes; https://datastudio.google.com/s/n0v8X8zXamo

**Comment by jrfastab** [comment]
K8sDatapathConfig Encapsulation Check iptables masquerading with random-fully: https://datastudio.google.com/s/poztQoaWOL8

Only a couple failures on this one, but seems unrelated to this PR.

**Comment by joestringer** [comment]
`K8sDatapathConfig Encapsulation Check iptables masquerading with random-fully` is pretty new so we won't have a lot of data on its reliability. /cc @pchaigno

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
test-me-please

**Comment by jrfastab** [comment]
k8s-1.12-kernel-netnext failure: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-net-next/900/ (Suite-k8s-1.12.K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with direct routing and DSR)

**Comment by jrfastab** [comment]
retest-net-next

**Comment by jrfastab** [comment]
Runtime-4.9 failure: https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/2227/ (Suite-runtime.RuntimePolicies Tests Egress To World)

**Comment by jrfastab** [comment]
retest-runtime

**Comment by jrfastab** [comment]
retest-runtime
