### PR TITLE
Don't enable host firewall bypass unless host firewall is enabled

### LINKED ISSUE #40682: CI: check-log-errors/ - subsys=resolve-labels pod.core "[...]" not found when --enable-k8s-host-firewall-bypass=true
## CI failure

Example run: https://github.com/cilium/cilium/actions/runs/16462113248/job/46531465538
Error log:
```
check-log-errors/no-errors-in-logs:pkg/endpoint:kind-kind/kube-system/cilium-xv6d2 (cilium-agent): Found 1 logs in kind-kind/kube-system/cilium-xv6d2 (cilium-agent) matching list of errors that must be investigated:
time=2025-07-23T05:16:47.521601164Z level=warn source=/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:1785 
msg="Unable to fetch kubernetes labels" 
datapathPolicyRevision=0 desiredPolicyRevision=1 k8sPodName=local-path-storage/local-path-provisioner-59f7658548-ldmdf ciliumEndpointName=local-path-storage/local-path-provisioner-59f7658548-ldmdf containerInterface="" containerID=fe097f7430 ipv4=10.244.0.232 endpointID=246 ipv6=fd00:10:244::7365 identity=5 subsys=resolve-labels 
error="pod.core \"local-path-provisioner-59f7658548-ldmdf\" not found" (12 occurrences)
```

[cilium-sysdump-ipsec-2.zip](https://github.com/user-attachments/files/21410869/cilium-sysdump-ipsec-2.zip)

This seems to be a widespread issue affecting multiple tests:
`Conformance IPsec E2E (ci-ipsec-e2e):`
https://github.com/cilium/cilium/actions/runs/16462113248 
`Conformance Cluster Mesh (ci-clustermesh):`
https://github.com/cilium/cilium/actions/runs/16461700567
`Conformance EKS (ci-eks):`
https://github.com/cilium/cilium/actions/runs/16402220714

First occurance that I was able to find: 
Jul 19, 2025 @ 03:31:22.000
https://github.com/cilium/cilium/actions/runs/16383474555
Unfortunately I wasn't able to pinpoint failure to any PRs around that time.

It seems that since then, it failed ~27 times on scheduled runs.

As a result of this warning - new pods that are being run on a node get `init` identity, which means policy is not correctly enforced for them for some time.

### PR DESCRIPTION
**Pull request by atykhyy**
An [analysis](https://github.com/cilium/cilium/issues/40682#issuecomment-3146426530) of e2e conformance test failures reported in #40682 and attributed to #40346 (k8s host firewall bypass) being enabled by default showed that these failures appear in test jobs where IPSec is enabled. However, IPSec cannot be used with the host firewall, whereas the whole host (node) FQDN-based egress rules feature, which creates the need for a bypass, only makes sense _with_ the host firewall. This PR ensures that the bypass is not enabled unless the host firewall is enabled.

Fixes: #40682
Related: #40346

### CODE REVIEW

**Comment by atykhyy** [comment]
For what it's worth, the failure in `ci-clustermesh` test is the same as in a dozen other unrelated runs today. `ci-gateway-api` is less flaky but I found several runs with similar errors and [one](https://github.com/cilium/cilium/actions/runs/16746753798/job/47407033297) with the same error (albeit in a different job), so it does not look to be caused by changes in this PR either.

**Review by joamaki — APPROVED** [review]

**Comment by joestringer** [comment]
FWIW for future reference it's easier for committers to understand the status of the PR if CI results are reported with issue links (related: [CI Failure Triage Docs](https://docs.cilium.io/en/stable/contributing/testing/ci/#ci-failure-triage)).

Example:
* [ci-clustermesh](https://github.com/cilium/cilium/actions/runs/16757424340) run hit known issue https://github.com/cilium/cilium/issues/39370 (now fixed on `main`, fix for v1.18 upgrade is pending)
* [ci-gateway-api](https://github.com/cilium/cilium/actions/runs/16757422979) run hit known issue https://github.com/cilium/cilium/issues/40243

Given these issues have been reported by others, I think it's fair to say this PR is not introducing these failures.

File: pkg/k8s/hostfirewallbypass/cell.go [hunk 1]
```diff
@@ -14,17 +16,24 @@ var Cell = cell.Module(
 	"k8s-host-firewall-bypaass",
 	"Kubernetes host firewall bypass",
 
-	cell.Config(Params{
-		EnableK8sHostFirewallBypass: false,
+	cell.Config(config{
+		EnableK8sHostFirewallBypass: true,
```
Comment (joestringer) [inline pkg/k8s/hostfirewallbypass/cell.go:20]: Is this also setting the default value to true when host firewall is enabled?

Looking back at prior discussion [here](https://github.com/cilium/cilium/pull/40346#issuecomment-3058567264) I guess we set it default false out of caution, but perhaps your thinking on this has developed since then.

If I understand correctly, this option affects applications running on the host who set SO_MARK option on their sockets. Per the socket(7) man pages, this appears to require `CAP_NET_ADMIN` or `CAP_NET_RAW` privileges which are considered elevated, so the host firewall bypass is only opened up to users who already have considerable privileges. Arguably if a user only grants `CAP_NET_RAW` to an untrusted application, this could plausibly lead to policy bypass if not otherwise mitigated. Not sure the best way to inform users about this. We might consider docs or even just a log message wrapped in a `sync.Once` in `pkg/k8s/hostfirewallbypass/bypass.go` that reports at "info" level a message like `Host firewall bypass enabled for sockets with SO_MARK ____. Applications in host network with CAP_NET_ADMIN or CAP_NET_RAW may bypass host firewall`.

Thoughts?

Comment (atykhyy) [reply pkg/k8s/hostfirewallbypass/cell.go:20]: > Is this also setting the default value to true when host firewall is enabled?

Yes. However, I did not add the bypass to the k8s clientset module. The daemon and `cilium-dbg build-config` hives include the bypass cell explicitly.

> If I understand correctly, this option affects applications running on the host who set SO_MARK option on their sockets.

That's not the case. Unlike the `-j MARK` iptables target, `SO_MARK` is a per socket option. The bypass option thus affects only sockets created by the k8s clientset dialer instantiated by the same hive the bypass cell is added to. It does not affect anything else, not even other sockets created by the daemon process, much less sockets in other processes. However, _any_ process running on the host that has the required capabilities and knowledge can set the same `SO_MARK` option on _its_ sockets and bypass Cilium host network policies (that's what I did when I investigated if the bypass would work). So far as I can tell, this has always been the case; my changes do not affect the situation one way or another. To check this, in a 1.18 (or earlier) Cilium cluster with host firewall enabled, create a host network policy forbidding access to `1.1.1.1:80`, then exec into the agent pod, start perl (there being no python available), and run the following with and without the commented line:
```perl
use Socket;
use constant SO_MARK => 36;
socket(my $sock, PF_INET, SOCK_STREAM, getprotobyname("tcp")) || die "socket: $!";
#setsockopt($sock, SOL_SOCKET, SO_MARK, 0x0b00) || die "setsockopt: $!";
connect($sock, sockaddr_in(80, inet_aton("1.1.1.1"))) || die "connect: $!";
syswrite($sock,"GET / HTTP/1.1\r\nHost: one.one.one.one\r\n\r\n") || die "syswrite: $!";
sysread($sock, my $buf, 4096) || die "sysread: $!";
print $buf;
close($sock);
```
For what it's worth, I don't think this is a security issue by itself. Processes running on the host with `CAP_NET_ADMIN` can do many other nasty things, not just bypass host firewall.

Comment (atykhyy) [reply pkg/k8s/hostfirewallbypass/cell.go:20]: PS: I don't think this is a security issue by itself. Processes running on the host with `CAP_NET_ADMIN` can do many other nasty things, not just bypass host firewall.

Comment (joestringer) [reply pkg/k8s/hostfirewallbypass/cell.go:20]: > However, any process running on the host that has the required capabilities and knowledge can set the same `SO_MARK` option on its sockets and bypass Cilium host network policies

Yeah this was the case I was thinking about. 

> So far as I can tell, this has always been the case; my changes do not affect the situation one way or another. 

Right true, I mixed up the datapath implementation of how Cilium already handles packets with these marks vs. the functionality enabled with this feature which only affects the sockets which integrate a dependency on this bypass Dialer configuration :+1: 

> PS: I don't think this is a security issue by itself. Processes running on the host with CAP_NET_ADMIN can do many other nasty things, not just bypass host firewall.

I agree, especially for `CAP_NET_ADMIN`. I think people might expect a little more from `CAP_NET_RAW`, but we can consider whether to improve the threat model docs on this independently of this PR. :+1:

**Comment by joestringer** [comment]
This seems ready to merge. Thanks for your patience.
