### PR TITLE
cilium: change default error message when checking agent status

### LINKED ISSUE #1522: Improve error message if UDS does not exist
```
$ cilium status
Error: Error while retrieving configuration: Get http://%2Fvar%2Frun%2Fcilium%2Fcilium.sock/v1beta/config: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
```

### PR DESCRIPTION
**Pull request by aalemayhu**
cilium: change default client error messages
    
When the agent is down the new output looks something like this
    
            Cannot connect to the Cilium Agent at unix:///var/run/cilium/cilium.sock. Is the agent running?
    
It might differ a little depending on what the prefix is. Also the error
strings are now unescaped so output with `%` should not show up.
    
Closes: #1522 (Improve error message if UDS does not exist)
Signed-off-by: Alexander Alemayhu <alexander@alemayhu.com>

### CODE REVIEW

**Review by aanm — COMMENTED** [review]
Won't this omit errors like `connect: no such file or directory` or `connect: permission denied`?

**Comment by aalemayhu** [comment]
@aanm I don't think so, since it should match on the string (UDS path). Tried locally by creating a temporary user and the below is what I get. Or maybe  I am missing something?

```
bash-4.4$ cilium status
Cannot connect to the Cilium Agent at unix:///var/run/cilium/cilium.sock. Is the agent running?
bash-4.4$ cilium endpoint list
Error: cannot get endpoint list: Get http://%2Fvar%2Frun%2Fcilium%2Fcilium.sock/v1beta/endpoint: dial unix /var/run/cilium/cilium.sock: connect: permission denied

bash-4.4$ ^C /var/run/cilium/cilium.sock
bash-4.4$ # in different terminal removing /var/run/cilium/cilium.sock
bash-4.4$ ls /var/run/cilium/cilium.sock
ls: cannot access '/var/run/cilium/cilium.sock': No such file or directory
bash-4.4$ cilium status
Cannot connect to the Cilium Agent at unix:///var/run/cilium/cilium.sock. Is the agent running?
bash-4.4$ cilium endpoint list
Error: cannot get endpoint list: Get http://%2Fvar%2Frun%2Fcilium%2Fcilium.sock/v1beta/endpoint: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
```

**Comment by aanm** [comment]
Why does the `cilium status` and `cilium endpoint list` have different outputs? I thought this PR would show all non-successful attempts of reaching out cilium agent would be printed as `Cannot connect to the Cilium Agent at unix:///var/run/cilium/cilium.sock. Is the agent running?`

Can you change all error message to show `http:///var/run/cilium/cilium.sock` instead of `http://%2Fvar%2Frun%2Fcilium%2Fcilium.sock`?

**Comment by aalemayhu** [comment]
The output differs because the change was made where the error checking for the status is. I agree that it should be consistent and a better place would be in pkg/client so it's transparent to the caller. Can make the changes in a moment.

File: pkg/client/client.go [hunk 1]
```diff
@@ -89,3 +89,14 @@ func NewClient(host string) (*Client, error) {
 		clientapi.DefaultSchemes, httpClient)
 	return &Client{*clientapi.New(clientTrans, strfmt.Default)}, nil
 }
+
+func improve(err error) error {
+	if err == nil {
+		return err
+	}
+	if strings.Contains(err.Error(), defaults.SockPath) {
+		return fmt.Errorf("Cannot connect to the Cilium Agent at unix://%s. Is the agent running?", defaults.SockPath)
```
Comment (tgraf) [inline pkg/client/client.go]: While I like the hint with regard to what could be wrong, we should continue to print the real error returned from the client as well. It could be permissions denied, no such file or directory, ...

**Review by tgraf — CHANGES_REQUESTED** [review]

File: pkg/client/client.go [hunk 2]
```diff
@@ -89,3 +89,15 @@ func NewClient(host string) (*Client, error) {
...
 }
+
+// Hint tries to improve the error message displayed to the user.
+func Hint(err error) error {
+	if err == nil {
+		return err
+	}
+	e, _ := url.PathUnescape(err.Error())
+	if strings.Contains(err.Error(), defaults.SockPath) {
+		return fmt.Errorf("%s\nIs the agent running?\n", e)
```
Comment (tgraf) [inline pkg/client/client.go]: I think the trailing `\n` should be removed

File: pkg/client/client.go [hunk 3]
```diff
@@ -89,3 +89,15 @@ func NewClient(host string) (*Client, error) {
...
 	return &Client{*clientapi.New(clientTrans, strfmt.Default)}, nil
 }
+
+// Hint tries to improve the error message displayed to the user.
+func Hint(err error) error {
+	if err == nil {
+		return err
+	}
+	e, _ := url.PathUnescape(err.Error())
+	if strings.Contains(err.Error(), defaults.SockPath) {
```
Comment (tgraf) [inline pkg/client/client.go:99]: 👍

**Review by tgraf — CHANGES_REQUESTED** [review]

**Review by tgraf — APPROVED** [review]
