### PR TITLE
cilium: fix up all --help sections properly

### LINKED ISSUE #10944: cilium: fix up all --help sections properly
Reminder for 1.8 release (hence release blocker) to go over all --help sections of cilium agent together and fix them up properly. E.g. to pick one, the kube-proxy free knobs are randomly spread all over the place right now which must be fixed before 1.8 goes out, same likely for other areas.

### PR DESCRIPTION
**Pull request by soumynathan**
This patch will try to fix up all the --help sections properly based
on the feature requirements.

Fixes: #10944
Signed-off-by: Swaminathan Vasudevan <svasudevan@suse.com>

### CODE REVIEW

**Comment by soumynathan** [comment]
I have went in and added the help section for 'kubeproxy'.
Please feel free to let me know the additional sections and I can collect the config options for it and can group it.

**Comment by aanm** [comment]
test-me-please

File: pkg/option/config.go [hunk 1]
```diff
@@ -1109,6 +1100,20 @@ var HelpFlagSections = []FlagsSection{
...
+			InstallIptRules,
+			EnableExternalIPs,
+			EnableHostReachableServices,
+			EnableNodePort,
+			HostReachableServicesProtos,
+			LoopbackIPv4,
+			IPv4ServiceRange,
+			IPv6ServiceRange,
+		},
+	},
```
Comment (borkmann) [inline pkg/option/config.go:1039]: @soumynathan @joestringer  My main worry is three-fold:

1. Developers add new agent flags and then forget to add them to one of the `HelpFlagSections` areas. Given we know all the flags and know the content of `HelpFlagSections`, we really need to fail the build in one way or another.

2. Some of the above options are still in too many random places. Examples: `EnableAutoProtectNodePortRange` is only relevant to kube-proxy-free. `NodePortMode` and `NodePortRange` is kube-proxy free. Then `DisableK8sServices` is related to kube-proxy free but also to k8s. How do we handle overlap?

3. I think this needs further split up otherwise it is way too confusing. For example for the CT, some options are under `BPF flags` and some under `Networking flags` like `ConntrackGCInterval`. I think we can only get order in there if we split even more fine-grained and have it pedantically organized by topic. Even if there are just two flags in such group, etc. Otherwise the user experience won't be great.

Comment (joestringer) [reply pkg/option/config.go:1039]: (1) Agree. If developers aren't provided an explicit choice about where to put it, they will ignore it and just default to the "other" section. Forcing build failure via `make check` if they don't make this choice is a way to address this.

(2) Is it possible (and reasonable) to duplicate the entry across multiple sections?

Both (2) and (3) I partly see as there's uneven spread of information. For instance there's a bunch of flags that I think you're concerned about @borkmann, but you have several years of Cilium background to say what makes sense where. @soumynathan who's newer to the project doesn't have that background so it's hard to go back-and-forth on it to get it right.

From a practical perspective, I think it's worth narrowing down which items are worthwhile for @soumynathan to tackle here and which ones we can put into a review step prior to release that the maintainers can go through.

Comment (soumynathan) [reply pkg/option/config.go:1039]: I agree. If @borkmann can provide a template we can organize it in a cleaner way, but still I do expect there might be some overlaps if we are grouping related to features.

**Comment by tklauser** [comment]
@soumynathan this PR needs a rebase

File: pkg/option/config.go [hunk 2]
```diff
@@ -798,6 +798,9 @@ var HelpFlagSections = []FlagsSection{
 			PreAllocateMapsName,
 			BPFCompileDebugName,
 			FragmentsMapEntriesName,
+			EnableBPFClockProbe,
+			EnableBPFMasquerade,
+			EnableIPMasqAgent,
```
Comment (joestringer) [inline pkg/option/config.go]: Although IPMasqAgent is implemented in BPF, I don't really consider it a BPF tweak. @brb any opinion on this?

File: pkg/option/config.go [hunk 3]
```diff
@@ -1011,6 +1012,34 @@ var HelpFlagSections = []FlagsSection{
...
+	{
+		Name: "KubeProxy free flags",
+		Flags: []string{
+			KubeProxyReplacement,
+			EnableNodePort,
+			EnableHostReachableServices,
+			EnableExternalIPs,
+			HostReachableServicesProtos,
+			NodePortMode,
+			EnableAutoDirectRoutingName,
```
Comment (joestringer) [inline pkg/option/config.go]: I don't think  AutoDirectRouting is related to kube-proxy free. Its existing listing under Route flags is fine.

File: pkg/option/config.go [hunk 4]
```diff
@@ -957,7 +961,7 @@ var HelpFlagSections = []FlagsSection{
 			IdentityAllocationMode,
 			IdentityChangeGracePeriod,
 			FixedIdentityMapping,
-			CertsDirectory,
```
Comment (joestringer) [inline pkg/option/config.go:960]: CertsDirectory is specifically for Certificates used in L7 policy enforcement, so I think it makes sense for this to remain under policy.

**Review by joestringer — CHANGES_REQUESTED** [review]
I pointed out some individual items here that probably make sense to move elsewhere / not change / etc, hopefully that helps.

File: pkg/option/config.go (hunk 3 above)
Comment (soumynathan) [reply pkg/option/config.go]: The document says for advanced kube-proxy that is required.
```
helm install cilium cilium/cilium --version 1.7.4 \
    --namespace kube-system \
    --set global.tunnel=disabled \
    --set global.autoDirectNodeRoutes=true \
    --set global.kubeProxyReplacement=strict \
    --set global.nodePort.mode=dsr \
    --set global.k8sServiceHost=API_SERVER_IP \
    --set global.k8sServicePort=API_SERVER_PORT

File: pkg/option/config.go (hunk 4 above)
Comment (soumynathan) [reply pkg/option/config.go:960]: Ok, I can move it back, since I was grouping all path related info together, I moved it.

File: pkg/option/config.go (hunk 2 above)
Comment (soumynathan) [reply pkg/option/config.go]: Ok, I can move it back in that case.

File: pkg/option/config.go (hunk 4 above)
Comment (soumynathan) [reply pkg/option/config.go:960]: Done.

File: pkg/option/config.go (hunk 2 above)
Comment (soumynathan) [reply pkg/option/config.go]: For now I will move it to others.

File: pkg/option/config.go (hunk 3 above)
Comment (soumynathan) [reply pkg/option/config.go]: Yes I moved it back.

File: pkg/option/config.go (hunk 4 above)
Comment (soumynathan) [reply pkg/option/config.go:960]: Done.

**Comment by mrostecki** [comment]
test-me-please

File: pkg/option/config.go [hunk 5]
```diff
@@ -890,6 +891,8 @@ var HelpFlagSections = []FlagsSection{
 			EnableHealthChecking,
 			TracePayloadlen,
 			PProf,
+			Restore,
+			KeepConfig,
```
Comment (joestringer) [inline pkg/option/config.go]: These aren't to do with debug / logging / trace, what's the motivation for moving these here?

**Review by joestringer — CHANGES_REQUESTED** [review]
One more nit below.

File: pkg/option/config.go (hunk 5 above)
Comment (soumynathan) [reply pkg/option/config.go]: Will fix it.

Comment (soumynathan) [reply pkg/option/config.go]: Done.

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
Discussed with @borkmann , we'll merge as-is then he can follow up with any remaining items that need rearranging.

**Comment by soumynathan** [comment]
> Discussed with @borkmann , we'll merge as-is then he can follow up with any remaining items that need rearranging.

Sounds good.
