### PR TITLE
probe: fix kernel config probe log

### LINKED ISSUE #20858: Cilium fails to start with "RTNETLINK answers: Operation not supported"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Architecture: x86_64

I installed cilium via helm chart into our k3s cluster.

helm values:

```yaml
containerRuntime:
  integration: containerd
  socketPath: /var/run/k3s/containerd/containerd.sock

hubble:
  tls:
    enabled: false
  relay:
    enabled: true
  ui:
    enabled: true

ipam:
  mode: "kubernetes"

operator:
  replicas: 1

kubeProxyReplacement: disabled
```

Unfortunatly cilium want start and fail with following logs:

```bash
level=warning msg="+ tc qdisc replace dev cilium_vxlan clsact" subsys=datapath-loader
level=warning msg="RTNETLINK answers: Operation not supported" subsys=datapath-loader
level=warning msg="+ true" subsys=datapath-loader
level=warning msg="++ grep -v 'pref 1 bpf chain 0 $\\|pref 1 bpf chain 0 handle 0x1'" subsys=datapath-loader
level=warning msg="++ tc filter show dev cilium_vxlan ingress" subsys=datapath-loader
level=warning msg="RTNETLINK answers: Operation not supported" subsys=datapath-loader
level=warning msg="Dump terminated" subsys=datapath-loader
level=warning msg="+ '[' -z '' ']'" subsys=datapath-loader
level=warning msg="+ cilium bpf migrate-maps -s bpf_overlay.o" subsys=datapath-loader
level=warning msg="+ tc filter replace dev cilium_vxlan ingress prio 1 handle 1 bpf da obj bpf_overlay.o sec from-overlay" subsys=datapath-loader
level=warning msg="RTNETLINK answers: Operation not supported" subsys=datapath-loader
level=warning msg="We have an error talking to the kernel" subsys=datapath-loader
level=warning msg="+ cilium bpf migrate-maps -e bpf_overlay.o -r 1" subsys=datapath-loader
level=warning msg="+ return 1" subsys=datapath-loader
level=fatal msg="Error while creating daemon" error="error while initializing daemon: failed while reinitializing datapath: exit status 1" subsys=daemon
```

### Cilium Version

1.12.0

### Kernel Version

5.15.0-1013-kvm #16-Ubuntu SMP Fri Jul 1 21:19:48 UTC 2022

### Kubernetes Version

v1.24.3+k3s1

### Sysdump

_No response_

### Relevant log output

```shell
see above
```

### Anything else?

When I upgrade the kernel (by hand) to version: 5.18.0-051800-generic, everything is working fine again.

Unfortunatly, we are using the jammy cloud image and we don't want to update the kernel by ourself.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by vincentmli**
In https://github.com/cilium/cilium/issues/20858 and my lab,
I tested kernel with

    1 missing kernel config file /boot/config-xxx and /proc/config.gz
    2 missing required kernel config option CONFIG_NET_CLS_ACT
    
    when both condition 1 and 2 are met, the cilium agent does not log
    missing kernel config file, and missing required kernel config option.
    
    The reason is when missing kernel config file, SystemConfigProbes()
    returns ErrKernelConfigNotFound, but SystemConfigProbes() caller
    only logs error when SystemConfigProbes() detect missing required
    kernel config option which would never happen because SystemConfigProbes()
    returned already and kernel config option check is skipped.
    
      Warn missing kernel config file if cilium agent fail to start
    
    After the fix:
    
    level=info msg="clang (10.0.0) and kernel (5.18.0) versions: OK!" subsys=linux-datapath
    level=info msg="linking environment: OK!" subsys=linux-datapath
    level=warning msg="Kernel Config file not found: Check required kernel config parameter \
            if cilium agent fail to start!" subsys=probes
    …SNIP…
    level=warning msg="+ tc qdisc replace dev cilium_vxlan clsact" subsys=datapath-loader
    level=warning msg="Error: Cannot find ingress queue for specified device." subsys=datapath-loader

Fix: #20858

Signed-off-by: Vincent Li <v.li@f5.com>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #20858
```release-note
fix kernel config file and config option probe log
```

### CODE REVIEW

**Review by dylandreimerink — CHANGES_REQUESTED** [review]
Warning on missing kernel configs were removed in a previous [commit](https://github.com/dylandreimerink/cilium/commit/d93177132d8e1b260424d851ce995a5eec1537ac) hence [this](https://github.com/vincentmli/cilium/blob/399a03ee2427ba4ece35362e147dcf45d8bf03ef/pkg/datapath/linux/requirements.go#L148) comment. Seems like we should first check that #14314 has been resolved before adding a log back in.

Second thing, `ErrKernelConfigNotFound` was exclusively used for this check. So please remove it and the if statement in [requirements.go](https://github.com/vincentmli/cilium/blob/vli-kconfig/pkg/datapath/linux/requirements.go#L149) and [probes_test.go](https://github.com/vincentmli/cilium/blob/vli-kconfig/pkg/datapath/linux/probes/probes_test.go#L247) as well.

**Comment by vincentmli** [comment]
> Warning on missing kernel configs were removed in a previous [commit](https://github.com/dylandreimerink/cilium/commit/d93177132d8e1b260424d851ce995a5eec1537ac) hence [this](https://github.com/vincentmli/cilium/blob/399a03ee2427ba4ece35362e147dcf45d8bf03ef/pkg/datapath/linux/requirements.go#L148) comment. Seems like we should first check that #14314 has been resolved before adding a log back in.
> 

I see, instead of warning level log, maybe log as info level log? I think it is helpful for customer to know they are missing kernel config file. https://github.com/cilium/cilium/issues/14314 seems to be resolved by using cilium/ebpf Go API to probe feature in https://github.com/cilium/cilium/issues/20701,  this is minor log bug I think we can address it early

> Second thing, `ErrKernelConfigNotFound` was exclusively used for this check. So please remove it and the if statement in [requirements.go](https://github.com/vincentmli/cilium/blob/vli-kconfig/pkg/datapath/linux/requirements.go#L149) and [probes_test.go](https://github.com/vincentmli/cilium/blob/vli-kconfig/pkg/datapath/linux/probes/probes_test.go#L247) as well.

ok I can remove `ErrKernelConfigNotFound`

**Comment by vincentmli** [comment]
I actually compiled kernel 5.18.0 without `/proc/config.gz` but with all required kernel config option, with the current PR, I get log:

```
level=info msg="Kernel Config file /proc/config.gz not found: BUT OK." subsys=probes
level=warning msg="BPF system config check: NOT OK." error="CONFIG_BPF_JIT kernel parameter is required (needed for: Essential eBPF infrastructure)" subsys=linux-datapath
```
cilium agent runs fine, but obviously the warning log is mis-leading, `CONFIG_BPF_JIT` is actually enabled, but bpftool reports not enabled, we can see from bpftool feature probe:

```
  "system_config": {
    "unprivileged_bpf_disabled": 1,
    "bpf_jit_enable": 1,
    "bpf_jit_harden": 0,
    "bpf_jit_kallsyms": 1,
    "bpf_jit_limit": 264241152,
    "CONFIG_BPF": null,
    "CONFIG_BPF_SYSCALL": null,
    "CONFIG_HAVE_EBPF_JIT": null,
    "CONFIG_BPF_JIT": null, <=====
``` 
so it looks to me `bpftool feature probe` also read from `/proc/config.gz`, if `/proc/config.gz` is missing, bpftool can't probe the correct kernel config option. so hiding the kernel config warning log kind of making sense, but hiding the warning log is not helpful when `/proc/config.gz` is missing and required kernel config option is disabled, will have to think about again how to make the logging meaningful for:
1 `/proc/config.gz` is missing, required kernel config option is enabled
2 `/proc/config.gz` is missing, required kernel config option is disabled

**Comment by vincentmli** [comment]
pushed the new changes and here is the manual test result:

1, Missing kernel config file, required kernel config parameter enabled
```
level=info msg="clang (10.0.0) and kernel (5.18.0) versions: OK!" subsys=linux-datapath
level=info msg="linking environment: OK!" subsys=linux-datapath
level=warning msg="Kernel Config file not found: Check if required kernel config parameter enabled if cilium agent fail to start!" subsys=probes
```
2, Missing kernel config file, required kernel config parameter disabled
```
level=info msg="clang (10.0.0) and kernel (5.18.0) versions: OK!" subsys=linux-datapath
level=info msg="linking environment: OK!" subsys=linux-datapath
level=warning msg="Kernel Config file not found: Check kernel config parameter if cilium agent fail to start!" subsys=probes
…SNIP…
level=warning msg="+ tc qdisc replace dev cilium_vxlan clsact" subsys=datapath-loader
level=warning msg="Error: Cannot find ingress queue for specified device." subsys=datapath-loader
```

3, Kernel config file available, required kernel config enabled
```
level=info msg="clang (10.0.0) and kernel (5.18.0) versions: OK!" subsys=linux-datapath
level=info msg="linking environment: OK!" subsys=linux-datapath
level=warning msg="CONFIG_LWTUNNEL_BPF optional kernel parameter is not in kernel (needed for: Lightweight Tunnel hook for IP-in-IP encapsulation)" subsys=probes
```
4, Kernel config file available, required kernel config disabled
```
level=info msg="clang (10.0.0) and kernel (5.18.0) versions: OK!" subsys=linux-datapath
level=info msg="linking environment: OK!" subsys=linux-datapath
level=warning msg="BPF system config check: NOT OK." error="CONFIG_NET_CLS_ACT kernel parameter is required (needed for: Essential eBPF infrastructure)" subsys=linux-datapath
…SNIP…
level=warning msg="+ tc qdisc replace dev cilium_vxlan clsact" subsys=datapath-loader
level=warning msg="Error: Cannot find ingress queue for specified device." subsys=datapath-loader
```

**Comment by pchaigno** [comment]
@vincentmli I switch to draft but this is actually ready for reviews, no? If so, could you mark ready and re-request a review from Dylan?

**Comment by vincentmli** [comment]
> @vincentmli I switch to draft but this is actually ready for reviews, no? If so, could you mark ready and re-request a review from Dylan?

yes it is ready for review for @dylandreimerink I have no strong opinion on this PR though

**Review by dylandreimerink — APPROVED** [review]
Thank you for the changes, I think all concerns has been addressed. I suspect #20701 will indeed  improve the situation, but I don't think we have to wait, approved!

Apologies for the non-response from my part, but we got there in the end :)

**Comment by vincentmli** [comment]
rebase

File: pkg/datapath/linux/probes/probes.go [hunk 1]
```diff
@@ -204,13 +199,19 @@ func (p *ProbeManager) SystemKernelHz() (int, error) {
...
+//
+// When kernel config file is not found, bpftool can't probe kernel configuration
+// parameter real setting, so only return error log when kernel config file exists
+// and kernel configuration parameter setting is disabled
 func (p *ProbeManager) SystemConfigProbes() error {
+	var notFound bool
 	if !p.KernelConfigAvailable() {
-		return ErrKernelConfigNotFound
+		notFound = true
+		log.Warn("Kernel Config file not found: If agent fail to start, Please check kernel requirements https://docs.cilium.io/en/stable/operations/system_requirements")
```
Comment (joestringer) [inline pkg/datapath/linux/probes/probes.go:211]: Can we achieve the same logic as this PR by *only* adding this warning message?

I found a few things to be confusing in this PR:
- `notFound` then gets checked as `!notFound` below, so then it's confusing to think about what "not not found" double negative means. At the very least this can be `found = false`.
- But then, if all of the checks below are being skipped in the `found == false` case , this could just return `nil`.
- If this line returned `nil` though, it's a bit strange because this function *is* actually having an error condition, it's just that the callers may not want to treat that as a fatal error, they can tolerate the error and continue. This is the case already today.

In the end, it seems like the core difference that this PR proposes is just to avoid logging the message as `BPF system config check: NOT OK.`, this instead logs a more friendly warning. If that's the case, then we don't need to make the logic checks more complicated here, the complete PR could be just to add this one log warning message.

**Review by joestringer — CHANGES_REQUESTED** [review]

File: pkg/datapath/linux/probes/probes.go (hunk 1 above)
Comment (vincentmli) [reply pkg/datapath/linux/probes/probes.go:211]: If I recall correct, in https://github.com/cilium/cilium/issues/20858#issuecomment-1213342951, in my reproduction, without this PR, the original code does not log anything, not even `BPF system config check: NOT OK`.  I could make this PR just as simple as below, I will have to double check and test again. 

```
diff --git a/pkg/datapath/linux/requirements.go b/pkg/datapath/linux/requirements.go
index 199c135716..b12452550c 100644
--- a/pkg/datapath/linux/requirements.go
+++ b/pkg/datapath/linux/requirements.go
@@ -146,7 +146,7 @@ func CheckMinRequirements() {
                if err := probeManager.SystemConfigProbes(); err != nil {
                        errMsg := "BPF system config check: NOT OK."
                        // TODO(brb) warn after GH#14314 has been resolved
-                       if !errors.Is(err, probes.ErrKernelConfigNotFound) {
+                       if errors.Is(err, probes.ErrKernelConfigNotFound) {
                                log.WithError(err).Warn(errMsg)
                        }
                }
```

Comment (vincentmli) [reply pkg/datapath/linux/probes/probes.go:211]: I just tested above simple change, if I do not have required kernel BPF config, but I have kernel config file found, there will be no any log, just like original issue reported in https://github.com/cilium/cilium/issues/20858, agent crashes, but no early log clue on maybe required kernel BPF config might be missing. I admit the logic code in this PR is kind of confusing, but it does give user useful log clue. see the 4 test scenario with this PR https://github.com/cilium/cilium/pull/20889#issuecomment-1214179412

Comment (vincentmli) [reply pkg/datapath/linux/probes/probes.go:211]: to make the code bit clear, I could rename `notFound` to `found`, that seems less confusing

Comment (vincentmli) [reply pkg/datapath/linux/probes/probes.go:211]: I made the change, I think the logic is clear now :)

Comment (vincentmli) [reply pkg/datapath/linux/probes/probes.go:211]: the  following two `if !kernelOption.Enabled && found` check is to only log when required/optional kernel config not enabled and kernel config file is found, because bpftool probe kernel features based on kernel config file either in `/proc/config.gz` or `/boot/`, if none of these kernel config file exists, bpftool can't probe kernel feature, so bpftool don't really know if required/optional kernel config is enabled or not, log the message without kernel config file found is not correct.

Comment (joestringer) [reply pkg/datapath/linux/probes/probes.go:211]: > I just tested above simple change, if I do not have required kernel BPF config, but I have kernel config file found, there will be no any log ...

The changes in this function only make a difference in the case `if !p.KernelConfigAvailable()`. I don't understand how you could observe a difference in the case where the kernel config is found.

Comment (joestringer) [reply pkg/datapath/linux/probes/probes.go:211]:
```
diff --git a/pkg/datapath/linux/requirements.go b/pkg/datapath/linux/requirements.go
index 199c135716..b12452550c 100644
--- a/pkg/datapath/linux/requirements.go
+++ b/pkg/datapath/linux/requirements.go
@@ -146,7 +146,7 @@ func CheckMinRequirements() {
                if err := probeManager.SystemConfigProbes(); err != nil {
                        errMsg := "BPF system config check: NOT OK."
                        // TODO(brb) warn after GH#14314 has been resolved
-                       if !errors.Is(err, probes.ErrKernelConfigNotFound) {
+                       if errors.Is(err, probes.ErrKernelConfigNotFound) {
                                log.WithError(err).Warn(errMsg)
                        }
                }
```

This change is wrong, because it hides all of the other errors. If you were to do an approach like this, it would need to add new lines something like this:

```
                if err := probeManager.SystemConfigProbes(); err != nil {
                        errMsg := "BPF system config check: NOT OK."
                        // TODO(brb) warn after GH#14314 has been resolved
                        if !errors.Is(err, probes.ErrKernelConfigNotFound) {

                                log.WithError(err).Warn(errMsg)
+                       } else {                        
+                               log.WithError(err).Warn("If cilium-agent fails to start, Please check kernel requirements https://docs.cilium.io/en/stable/operations/system_requirements")}
                }
```

File: pkg/datapath/linux/probes/probes.go [hunk 2]
```diff
@@ -204,13 +200,19 @@ func (p *ProbeManager) SystemKernelHz() (int, error) {
...
+//
+// When kernel config file is not found, bpftool can't probe kernel configuration
+// parameter real setting, so only return error log when kernel config file exists
+// and kernel configuration parameter setting is disabled
 func (p *ProbeManager) SystemConfigProbes() error {
+	found := true
 	if !p.KernelConfigAvailable() {
-		return ErrKernelConfigNotFound
+		found = false
+		log.Warn("Kernel Config file not found: If agent fail to start, Please check kernel requirements https://docs.cilium.io/en/stable/operations/system_requirements")
```
Comment (joestringer) [inline pkg/datapath/linux/probes/probes.go:211]: grammar nit:
```suggestion
		log.Warn("Kernel Config file not found: If cilium-agent fails to start, Please check kernel requirements https://docs.cilium.io/en/stable/operations/system_requirements")
```

File: pkg/datapath/linux/requirements.go [hunk 3]
```diff
@@ -139,10 +139,9 @@ func CheckMinRequirements() {
 		}
 		if err := probeManager.SystemConfigProbes(); err != nil {
 			errMsg := "BPF system config check: NOT OK."
-			// TODO(brb) warn after GH#14314 has been resolved
-			if !errors.Is(err, probes.ErrKernelConfigNotFound) {
-				log.WithError(err).Warn(errMsg)
-			}
+			// TODO(vincentmli): revisit log when GH#14314 has been resolved
+			// Warn missing required kernel config option
```
Comment (joestringer) [inline pkg/datapath/linux/requirements.go:143]: This todo was specifically about ignoring the error, so I don't think it's necessary any more?

File: pkg/datapath/linux/probes/probes.go (hunk 1 above)
Comment (vincentmli) [reply pkg/datapath/linux/probes/probes.go:211]: Went to original PR route, but keep this in mind in case original PR is flawed (unlikely) :)

**Review by joestringer — APPROVED** [review]
I still suspect there's a simpler way, but it's not a big deal. This looks pretty clean anyway :+1: Thanks!

**Comment by vincentmli** [comment]
not sure why so many test errors in https://jenkins.cilium.io/job/Cilium-PR-K8s-1.25-kernel-net-next/421/, does not seem to related to this PR

**Comment by joestringer** [comment]
@vincentmli have you rebased the PR recently? It's possible there's some mismatch between the tests that run vs. the code here. I haven't observed such failures recently on other PRs.

**Comment by vincentmli** [comment]
@joestringer I did not do rebase, the last change is just addressing your review. should I do rebase?

**Comment by vincentmli** [comment]
retried the zip https://jenkins.cilium.io/job/Cilium-PR-K8s-1.25-kernel-net-next/421/testReport/junit/Suite-k8s-1/25/K8sDatapathServicesTest_Checks_N_S_loadbalancing_Tests_with_XDP__vxlan_tunnel__SNAT_and_Random/attachments/b5394d32_K8sDatapathServicesTest_Checks_N-S_loadbalancing_Tests_with_XDP%2C_vxlan_tunnel%2C_SNAT_and_Random.zip
the agent log has :

2022-10-08T13:31:39.470454155Z level=error msg="unable to initialize Kube proxy replacement options" error="Cannot use NodePort acceleration with tunneling. Either run cilium-agent with --node-port-acceleration=disabled or --tunnel=disabled" subsys=daemon
2022-10-08T13:31:39.470535185Z level=fatal msg="daemon creation failed: unable to initialize Kube proxy replacement options: Cannot use NodePort acceleration with tunneling. Either run cilium-agent with --node-port-acceleration=disabled or --tunnel=disabled" subsys=daemon

not related to this PR, maybe I should do rebase and see if it fails again?

**Comment by vincentmli** [comment]
just did a rebase

**Comment by vincentmli** [comment]
> just did a rebase

seems rebase made the test fail worse :)

**Comment by joestringer** [comment]
@vincentmli it looks like there is something wrong with the rebase, the failures are pointing at code related to probes.

**Comment by vincentmli** [comment]
> @vincentmli it looks like there is something wrong with the rebase, the failures are pointing at code related to probes.

ah, my PR had this below, so other places in probes.go reference `errors`  result in undefined errors use 

```
diff --git a/pkg/datapath/linux/probes/probes.go b/pkg/datapath/linux/probes/probes.go
index 933fe51d58..b6908a1471 100644
--- a/pkg/datapath/linux/probes/probes.go
+++ b/pkg/datapath/linux/probes/probes.go
@@ -7,7 +7,6 @@ import (
        "bufio"
        "bytes"
        "encoding/json"
-       "errors"
        "fmt"
        "io"
        "os"
@@ -34,10 +33,6 @@ var (
        probeManager *ProbeManager
 )
 
-// ErrKernelConfigNotFound is the error returned if the kernel config is unavailable
-// to the cilium agent.
-var ErrKernelConfigNotFound = errors.New("Kernel Config file not found")
-
```

**Comment by joestringer** [comment]
Travis hit known flake https://github.com/cilium/cilium/issues/21730 .

**Comment by vincentmli** [comment]
given this PR  only changes logging behavior when cilium agent startup, all the most recent test failures shows cilium agent is up and running, so don't think the test failures are related to this PR.

**Comment by aanm** [comment]
@vincentmli I agree. I've just rebased the PR and re-trigger the tests, let's see how it goes by now.

**Comment by vincentmli** [comment]
only mulitcluster and travis ci failed, but unrelated to this PR since multicluster cilium agent is up running fine.
