### PR TITLE
L7 Visibility Annotations for proxylib parsers

### LINKED ISSUE #14072: L7 visibility annotations do not work with proxylib parsers (including Kafka)
[Layer 7 Protocol Visibility](https://docs.cilium.io/en/stable/policy/visibility/) annotations only work for DNS and HTTP at the moment.

If you're interested in having this work for other L7 parsers, please :+1: or post below.

### PR DESCRIPTION
**Pull request by trvll**
Translating VisibilityPolicy into PortNetworkPolicy to enable L7 visibility for pod annotations.

Creates an allow-all policy that has a PortNetworkPolicyRule derived from VisibilityPolicy.

Signed-off-by: Thales Paiva <thales@accuknox.com>

Fixes: #14072
```release-note
Pod visibility annotations are now supported for Kafka and other policies implemented via Cilium Go extensions for Envoy.
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
@trvll Please note that no PortNetworkPolicy is needed for the visibility annotations to work. The reason why the visibility annotations do not currently work with Network Policies is *not* the lack of translation from visibility annotation to PortNetworkPolicy (which is not needed), but the missing interplay with L3/L4 allow/deny policy processing for the BPF policy map entries.

There is a work-in-progress PR that adds the missing pieces: https://github.com/cilium/cilium/pull/16258

While the solution in the linked PR is correct, it is still missing unit testing making it fragile towards future regressions. I'll be working on that shortly.

**Comment by jrajahalme** [comment]
Here's the code on the cilium-envoy side making the policy exception to support Istio sidecars, this same exception also allows visibility annotations to work without PortNetworkPolicies:

https://github.com/cilium/proxy/blob/master/cilium/network_policy.cc#L555-L560

**Comment by jrajahalme** [comment]
Corresponding code on the proxylib side is somewhat unfinished, maybe you try make it behave similarly to the C++ side linked above and test how it works out?

https://github.com/cilium/cilium/blob/master/proxylib/proxylib/policymap.go#L235-L245

**Comment by trvll** [comment]
@jrajahalme thank you for this kind discussion. 

>@trvll Please note that no PortNetworkPolicy is needed for the visibility annotations to work. 

AFAIU for annotations a PortNetworkPolicy will be used but it is an allow-all policy since there is no policy enforced:

https://github.com/cilium/cilium/blob/eb11c1467a2c535054e5c64d644d2ea442bf1270/pkg/envoy/server.go#L1239-L1242

>EDIT: I did not consider proxylib parsers yet. It may be possible to make the proxylib network policy code behave like the Envoy side so that a missing port network policy is interpreted as an allow-all policy. For normal (non-annotation) policies we never redirect to the proxy unless a PortNetworkPolicy is successfully configured. So the only configuration where traffic is redirected without a PortNetworkPolicy is for visibility only (via the visibility annotations).

In  case of proxylib parsers, when receiving a new connection, the proxy will create a new instancy from proxylib and needs the protocol name information to do that. This information on  Envoy side is retrieved from PortNetworkPolicyRule which comes to be empty because we are using an allow-all policy. 

https://github.com/cilium/proxy/blob/e83275091139101e7ff29284ef35c56f4cd6bfc3/cilium/network_filter.cc#L124-L127

So my approach here was to create an allow-all policy that has a PortNetworkPolicyRule derived from VisibilityPolicy. This make sense to you?

**Comment by jrajahalme** [comment]
@trvll Right, I forgot that proxylib parser selection requires the l7 parser name in the PortNetworkPolicyRule :-)

This PR looks good to me to fix this for the current master and is fully orthogonal with #16258. Some CI testing would be needed though. Would it be possible to augment the existing proxylib and/or Kafka tests with visibility annotations to verify this works?

Additional work will be needed to fuse the visibility annotation with an actual policy when policy is enforced, though. #16258 does this for the bpf policy map rules, but fails to address this for proxylib parsers. IMO this can be left for a follow-up PR.

**Comment by jrajahalme** [comment]
test-me-please

**Comment by trvll** [comment]
@jrajahalme thanks for your review. Yes! I can go through the tests right now as the proposed solution is considered satisfactory.

I also agree with the additional work statement. Thank you so much!

**Comment by jrajahalme** [comment]
@trvll Do you still plan working on some test coverage? This has no test coverage as of now. At a minimum, some unit tests for the additional functionality of `getNetworkPolicy()` in `pkg/envoy/server_test.go` should be added.

**Comment by trvll** [comment]
@jrajahalme yes, I'll code the tests ASAP considering your suggestion for sure. Tks.

**Comment by trvll** [comment]
Hi @jrajahalme I've added a unit test for the added functionality. I used kafka as example which I think is enough to test the mechanism. Please  let me know you opinion. Tks.

**Comment by jrajahalme** [comment]
test-me-please

**Review by jrajahalme — APPROVED** [review]
LGTM, thanks for adding the test :-)

**Comment by trvll** [comment]
@jrajahalme seems that the the failing tests are not related. Should we run the tests again?

File: pkg/envoy/server.go [hunk 1]
```diff
@@ -1334,8 +1335,61 @@ func getNetworkPolicy(ep logger.EndpointUpdater, name string, policy *policy.L4P
...
+					//TODO: Supports TCP only
+					if visMeta.Proto != u8proto.TCP {
+						PerPortPolicies = allowAllPortNetworkPolicy
+					} else {
+						protocol := envoy_config_core.SocketAddress_TCP
+
+						PerPortPolicies = append(PerPortPolicies, &cilium.PortNetworkPolicy{
+							Port:     uint32(visMeta.Port),
+							Protocol: protocol,
+							//Rules:    SortPortNetworkPolicyRules(rules),
```
Comment (nathanjsweet) [inline pkg/envoy/server.go]: Is this comment still necessary?

File: pkg/envoy/server.go [hunk 2]
```diff
@@ -1334,8 +1335,61 @@ func getNetworkPolicy(ep logger.EndpointUpdater, name string, policy *policy.L4P
...
```
Comment (nathanjsweet) [inline pkg/envoy/server.go]: ditto.

**Review by nathanjsweet — CHANGES_REQUESTED** [review]
nits. Otherwise, looks good. Your update should kickoff the tests again.

File: pkg/envoy/server.go (hunk 1 above)
Comment (trvll) [reply pkg/envoy/server.go]: not really. I'm going to remove it. Tks

**Review by nathanjsweet — APPROVED** [review]

**Comment by aanm** [comment]
test-1.16-netnext

**Comment by aanm** [comment]
test-1.21-4.9

**Comment by aanm** [comment]
ci-awscni

**Comment by aanm** [comment]
ci-aks

**Comment by aanm** [comment]
ci-eks

**Comment by aanm** [comment]
ci-gke

**Comment by aanm** [comment]
@trvll it looks these changes is breaking CI. Can you to take a look at them?

**Comment by trvll** [comment]
@aanm for sure.  I'm going to look on that. thx

**Comment by trvll** [comment]
I've patched the offending code. Basically we should create the PortNetworkPolicyRule with L7Proto set only for proxylib parsers.
I added a statement to avoid this setup for HTTP and DNS annotations.

**Comment by jrajahalme** [comment]
All the CI fails are unrelated, labeling ready-to-merge.

**Review by jrajahalme — APPROVED** [review]

**Review by nathanjsweet — APPROVED** [review]
