### PR TITLE
operator: Wait for informers to shut down when stopping

### LINKED ISSUE #22748: CI: panic in test/controlplane
### Test Name

```shell
Suite-runtime.RuntimeDatapathPrivilegedUnitTests Run Tests
```

### Failure Output

```shell
[20:52:09] level=info msg="Reading old endpoints..." subsys=daemon
	 [20:52:09] level=info msg="No old endpoints found." subsys=daemon
	 [20:52:09] panic: close of closed channel
	 [20:52:09] 
	 [20:52:09] goroutine 697 [running]:
	 [20:52:09] github.com/cilium/cilium/operator/watchers.UnmanagedKubeDNSPodsInit({0x3ad76a8?, 0xc00083ed40?})
	 [20:52:09] 	/home/vagrant/go/src/github.com/cilium/cilium/operator/watchers/pod.go:140 +0x268
	 [20:52:09] github.com/cilium/cilium/operator/cmd.enableUnmanagedKubeDNSController({0x3ad76a8?, 0xc00083ed40})
	 [20:52:09] 	/home/vagrant/go/src/github.com/cilium/cilium/operator/cmd/k8s_pod_controller.go:35 +0x59
	 [20:52:09] created by github.com/cilium/cilium/operator/cmd.(*legacyOnLeader).onStart
	 [20:52:09] 	/home/vagrant/go/src/github.com/cilium/cilium/operator/cmd/root.go:432 +0x435
	 [20:52:09] FAIL	github.com/cilium/cilium/test/controlplane	0.489s
	 [20:52:13] OK: 1 passed
```

and 

```
	 [20:54:42] ?   	github.com/cilium/cilium/tools/spdxconv	[no test files]
	 [20:54:42] ?   	github.com/cilium/cilium/tools/sysctlfix	[no test files]
	 [20:54:42] �[38;5;103m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓�[0m  
	 [20:54:42] �[38;5;103m┃�[0m   �[91m�[91mPANIC�[0m�[0m  package: github.com/cilium/cilium/test/controlplane • TestControlPlane/IdentityGC   �[38;5;103m┃�[0m  
	 [20:54:42] �[38;5;103m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛�[0m  
	 [20:54:42] panic: close of closed channel                                                                    
	 [20:54:42]                                                                                                   
	 [20:54:42] goroutine 697 [running]:                                                                          
	 [20:54:42] github.com/cilium/cilium/operator/watchers.UnmanagedKubeDNSPodsInit({0x3ad76a8?, 0xc00083ed40?})  
	 [20:54:42] 	/home/vagrant/go/src/github.com/cilium/cilium/operator/watchers/pod.go:140 +0x268                 
	 [20:54:42] github.com/cilium/cilium/operator/cmd.enableUnmanagedKubeDNSController({0x3ad76a8?, 0xc00083ed40})
	 [20:54:42] 	/home/vagrant/go/src/github.com/cilium/cilium/operator/cmd/k8s_pod_controller.go:35 +0x59         
	 [20:54:42] created by github.com/cilium/cilium/operator/cmd.(*legacyOnLeader).onStart                        
	 [20:54:42] 	/home/vagrant/go/src/github.com/cilium/cilium/operator/cmd/root.go:432 +0x435                     
	 [20:54:42] FAIL	github.com/cilium/cilium/test/controlplane	0.489s         
```
```


### Stack Trace

```shell
See above.
```

### Standard Output

```shell
See above.
```

### Standard Error

```shell
See above.
```

### Resources

- Jenkins URL: https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/4316/
- ZIP file(s): 
[af82d25c_RuntimeDatapathPrivilegedUnitTests_Run_Tests.zip](https://github.com/cilium/cilium/files/10235406/af82d25c_RuntimeDatapathPrivilegedUnitTests_Run_Tests.zip)

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by joamaki**
Now that the control-plane tests are running multiple test cases against
the operator we're seeing more flakes due to global variables that
left behind goroutines from previous test cases. For example:

```
  panic: close of closed channel

  goroutine 697 [running]:
    github.com/cilium/cilium/operator/watchers.UnmanagedKubeDNSPodsInit({0x3ad76a8?, 0xc00083ed40?})
        /home/vagrant/go/src/github.com/cilium/cilium/operator/watchers/pod.go:140 +0x268
```

The proper fix would be to refactor the operator to not use global variables
and implement it as cells with their own Start and Stop hooks that don't leave goroutines behind,

Since that refactoring will take significant time, we can apply band aid to the flaky test
problem by propagating a Context and WaitGroup to the places where goroutines are left behind
(as indicated by goleak check).

This commit does not apply this to every feature in operator due to gaps in test coverage
(e.g. operator/pkg/ingress was not modified).

Fixes: #22748

### CODE REVIEW

File: operator/watchers/pod.go [hunk 1]
```diff
@@ -24,18 +26,11 @@ var (
...
-	// PodStoreSynced is closed once the PodStore is synced with k8s.
-	PodStoreSynced = make(chan struct{})
-
 	// UnmanagedKubeDNSPodStore has a minimal copy of the unmanaged kube-dns pods running
 	// in the cluster.
 	// Warning: The pods stored in the cache are not intended to be used for Update
 	// operations in k8s as some of its fields are not populated.
 	UnmanagedKubeDNSPodStore cache.Store
-
-	// UnmanagedPodStoreSynced is closed once the UnmanagedKubeDNSPodStore is synced
```
Comment (joamaki) [inline operator/watchers/pod.go:36]: Heh, this channel was the cause of the original flaky test and it wasn't even used anywhere (same for PodStoreSynced). The changes in this PR still make sense since there's still e.g. `slimNodeStoreSynced` and after these changes we'll clean up a lot of the goroutines left by the operator during `test/controlplane` tests, which leads to lower memory usage as we add more tests.

**Comment by joamaki** [comment]
codeql hitting a known timeout issue. GKE seems flaky, so kicking it.

**Comment by joamaki** [comment]
ci-gke failing everywhere. temporary fix seems to be to downgrade it to 1.24.5: https://github.com/cilium/cilium/pull/22798.

**Review by dylandreimerink — APPROVED** [review]
Looks good to me

File: operator/watchers/k8s_service_sync.go [hunk 2]
```diff
@@ -186,15 +185,17 @@ func StartSynchronizingServices(ctx context.Context, clientset k8sClient.Clients
...
+			endpointController.Run(ctx.Done())
+		}()
 	}
 
+	wg.Add(1)
 	go func() {
-		<-k8sSvcCacheSynced
-		cache.WaitForCacheSync(wait.NeverStop, endpointController.HasSynced)
-	}()
+		defer wg.Done()
```
Comment (joestringer) [inline operator/watchers/k8s_service_sync.go:197]: What's going on in this hunk? It seems like the previous version waited for the cache to be synced, while the new one doesn't delay at all. As far as I could follow, the rest of the WaitGroup handling was set up to ensure that all cleanup completes before the next test runs, which doesn't seem related to removing the cache sync logic here.

File: operator/watchers/k8s_service_sync.go [hunk 3]
```diff
@@ -99,7 +98,7 @@ type ServiceSyncConfiguration interface {
 // 'shared' specifies whether only shared services are synchronized. If 'false' then all services
 // will be synchronized. For clustermesh we only need to synchronize shared services, while for
 // VM support we need to sync all the services.
-func StartSynchronizingServices(ctx context.Context, clientset k8sClient.Clientset, services resource.Resource[*slim_corev1.Service], shared bool, cfg ServiceSyncConfiguration) {
+func StartSynchronizingServices(ctx context.Context, wg *sync.WaitGroup, clientset k8sClient.Clientset, services resource.Resource[*slim_corev1.Service], shared bool, cfg ServiceSyncConfiguration) {
```
Comment (joestringer) [inline operator/watchers/k8s_service_sync.go:101]: nit: It'd be nice to have a comment about the purpose of the waitgroup here. As far as I follow, it's about signalling to the caller when all cleanup has completed and the service handling has stopped. Until we address the longer term planned changes, this could be a bit confusing to follow without some more indications of the purpose like this.

File: operator/watchers/k8s_service_sync.go (hunk 2 above)
Comment (joamaki) [reply operator/watchers/k8s_service_sync.go:197]: This was some left-over from earlier and it wasn't doing anything after waiting for sync, hence I removed it.

File: operator/cmd/root.go [hunk 4]
```diff
@@ -620,10 +641,10 @@ func (legacy *legacyOnLeader) onStart(_ hive.HookContext) error {
 			log.Fatal("CRD Identity allocation mode requires k8s to be configured.")
 		}
 
-		startManagingK8sIdentities(legacy.clientset)
+		startManagingK8sIdentities(legacy.ctx, &legacy.wg, legacy.clientset)
 
 		if operatorOption.Config.IdentityGCInterval != 0 {
-			go startCRDIdentityGC(legacy.clientset)
+			go startCRDIdentityGC(legacy.ctx, &legacy.wg, legacy.clientset)
```
Comment (pippolo84) [inline operator/cmd/root.go:647]: Not strictly related to the PR purpose, but here I think we can get rid of the `go` statement: it is unneeded to run the setup of the GC controller asynchronously.

**Review by pippolo84 — APPROVED** [review]
Late to the party, but LGTM, thanks! :100: 
I've left a comment about a possible minor improvement to be done in a follow up PR.
