### PR TITLE
Fix creation and deletion of host port maps that would occasionally leave pods without them

### LINKED ISSUE #32805: Cilium sporadically loses track of HostPort associated with daemonset pods
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium sporadically loses track of HostPort associated with daemonset pods. We have observed rollouts (kubectl rollout restart) or new deploys of daemonsets that have hostports configured in their pod definitions may stop being accessible and no longer show up in `cilium service list`. 

Clients attempting to connect to the host ports affected have their connections refused:
```
curl "http://${HOST_IP}:29472/info/healthcheck"
curl: (7) Failed to connect to 10.115.200.102 port 29472 after 0 ms: Connection refused
```

Restarting affected cilium pods causes cilium to correctly regenerate the hostport and connections  start working.

### Cilium Version

Cilium 1.15.3

### Kernel Version

5.10.216-204.855.amzn2.x86_64

### Kubernetes Version

v1.27.12-eks-ae9a62a

### Regression

_No response_

### Sysdump

I have a sysdump, but it's 1.2GB. I can provide if given a means to upload, or send individual dirs in the sysdump.

### Relevant log output

_No response_

### Anything else?

I was able to reproduce this in one of our qa clusters, and `rhonedelta-jjr85` was an affected pod. I used `kubectl rollout restart daemonsets -n rad`. The rhonedelta daemonset has a hostport on 29472 (spec included). Attached is the cilium-agent logs from the node, `ip-10-115-197-60.us-east-2.compute.internal`, the describe output of the node, the output of `cilium service list` from the cilium pod on that node, `cilium-6cg8l` and the cilium endpoint spec for `rhonedelta-jjr85` yaml.

The logs for the cilium agent show `rhonedelta-jjr85`'s endpoint was set up, but `cilium service list` shows no such hostport, and connections the hostport fail.

Deleting the cilium pod `cilium-6cg8l` resulted in the host port being generated as expected by the replacement cilium pod and connections started succeeding.

[cilium-6cg8l.log](https://github.com/cilium/cilium/files/15503708/cilium-6cg8l.log)
[cilium-6cg8l-cilium-service-list.txt](https://github.com/cilium/cilium/files/15503709/cilium-6cg8l-cilium-service-list.txt)
[ip-10-115-197-60.us-east-2.compute.internal.txt](https://github.com/cilium/cilium/files/15503710/ip-10-115-197-60.us-east-2.compute.internal.txt)
[rhonedelta-jjr85-cilium-endpoint.yaml.txt](https://github.com/cilium/cilium/files/15503730/rhonedelta-jjr85-cilium-endpoint.yaml.txt)
[rhonedelta.yaml.txt](https://github.com/cilium/cilium/files/15503731/rhonedelta.yaml.txt)

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by javanthropus**
Fixes: #32805

### CODE REVIEW

File: pkg/loadbalancer/loadbalancer.go [hunk 1]
```diff
@@ -458,6 +459,14 @@ type ServiceName struct {
 	Cluster   string
 }
 
+func NewServiceName(pod *slim_corev1.Pod, port uint16, cluster string) *ServiceName {
```
Comment (joamaki) [inline pkg/loadbalancer/loadbalancer.go]: This should not be called `NewServiceName` but rather something like `NewHostPortServiceName` and no need to heap allocate this, nor do we need to deal with `Cluster`.

**Review by joamaki — CHANGES_REQUESTED** [review]

File: pkg/loadbalancer/loadbalancer.go (hunk 1 above)
Comment (javanthropus) [reply pkg/loadbalancer/loadbalancer.go]: I'm not very familiar with golang, but I thought that a constructor function name should be of the form `New` + struct name.

Comment (joamaki) [reply pkg/loadbalancer/loadbalancer.go]: but that constructor is not for the general use but rather for the very niche case of making a synthetic service for HostPort. even better would be to put this to `watchers/pod.go` as that's the only place where we care about this. e.g. just add `func hostPortServiceName(pod *Pod, port int32) loadbalancer.ServiceName` there.

**Comment by joamaki** [comment]
Hey, could you add descriptions to the commits that describe what the problem was and how exactly this fixes the issue? It is not clear to me what including the pod UID does here to improve things.

**Comment by javanthropus** [comment]
> Hey, could you add descriptions to the commits that describe what the problem was and how exactly this fixes the issue? It is not clear to me what including the pod UID does here to improve things.

Done.

> Do you also have an example scenario of where the problem occurs? Is it in context of stateful sets or is it when the HostPort is handed over from one pod to another?

I included a manifest and instructions for reproducing the issue in #32805.  In short, this can happen any time the HostPort is handed from one pod to another.  In my example, it affects pods of a Deployment, but we also saw it affect DaemonSet pods.  I chose to use the pod UID in this PR because it could just as easily affect StatefulSet pods where the pod names don't necessarily change.  Hopefully the descriptions in the commits help clarify things.

**Comment by joamaki** [comment]
> > Hey, could you add descriptions to the commits that describe what the problem was and how exactly this fixes the issue? It is not clear to me what including the pod UID does here to improve things.
> 
> Done.
> 
> > Do you also have an example scenario of where the problem occurs? Is it in context of stateful sets or is it when the HostPort is handed over from one pod to another?
> 
> I included a manifest and instructions for reproducing the issue in #32805. In short, this can happen any time the HostPort is handed from one pod to another. In my example, it affects pods of a Deployment, but we also saw it affect DaemonSet pods. I chose to use the pod UID in this PR because it could just as easily affect StatefulSet pods where the pod names don't necessarily change. Hopefully the descriptions in the commits help clarify things.

Thanks! This clarifies it. I don't think including the pod UID will do anything since pods are indexed by name everywhere, e.g. it is not possible to have two copies of a pod with the same name in the system.

I'll take a look at reproducing this issue and implement the fix&test for the upcoming control-plane. Will think about if there's a point in including the pod UID and will get back on that...

**Comment by joamaki** [comment]
> > I don't think including the pod UID will do anything since pods are indexed by name everywhere, e.g. it is not possible to have two copies of a pod with the same name in the system.
> 
> That's true, but the events associated with pod state changes are asynchronous and could arrive or be processed out of order. Via debug logs, I saw this happen and cause the removal of the host port map _after_ a new pod was started to replace an old pod. I added the pod identity check in the first commit to guard against this case. When doing so, it seemed prudent to guard against the case of the old and new pods having the same name as well, such as for StatefulSet managed pods. I'm not aware of any better solution than the pod UID to do that.

The name/namespace is how pods are indexed in Kubernetes. It is not possible to have two instances of the pod with the same name and different UID at the same time and since the events will arrive in order for a resource with a specific name, Cilium will not see things out of order, e.g. it will see the pod terminating, being deleted and then recreated. What can happen is that the deletion and recreation gets coalesced and cilium-agent will only see an "update" to the pod where the UID changes. And that is something that needs to be handled correctly (for example in the endpoint sub-system). However that is not going to affect HostPort handling. Adding the UID in the service name for HostPort doesn't really do anything except make the service name longer. However, I don't really have anything against this and I can see it being useful in debugging scenarios, so let's go for it.

The fix seems to be correct, however it's quite subtle and relies on the fact that a pod being updated to phase=Completed is considered a deletion.

> Maybe what I should have done though is _replace_ the pod name in the Name field of the ServiceName struct with the pod UID rather than _add_ it. The pod name is redundant the vast majority of the time since the UID is guaranteed to be unique.

Let's keep the name as well since it's very informative.

**Review by joamaki — APPROVED** [review]

File: pkg/k8s/watchers/pod.go [hunk 2]
```diff
@@ -155,6 +155,14 @@ type K8sPodWatcher struct {
 	controllersStarted chan struct{}
 }
 
+func hostPortServiceName(pod *slim_corev1.Pod, port uint16, cluster string) *loadbalancer.ServiceName {
+	return &loadbalancer.ServiceName{
+		Name:      fmt.Sprintf("%s/pod-id/%s/host-port/%d", pod.ObjectMeta.Name, pod.ObjectMeta.UID, port),
```
Comment (christarazi) [inline pkg/k8s/watchers/pod.go]: Let's use string concat directly here to avoid `Sprintf` in the hotpath code.

Comment (javanthropus) [reply pkg/k8s/watchers/pod.go]: I'm not expert enough in golang to make the suggested change on my own such that there's an actual performance improvement.  I think you're asking for something like this:
```go
pod.ObjectMeta.Name + "/pod-id/" + pod.ObjectMeta.UID + "/host-port/" + strconv.Itoa(port)
```
If that's not right, can you provide an example of what you want done here?

Comment (javanthropus) [reply pkg/k8s/watchers/pod.go]: @christarazi, can you please get back to me soon?

Comment (christarazi) [reply pkg/k8s/watchers/pod.go]: Yes, that's correct. Thanks!

Comment (javanthropus) [reply pkg/k8s/watchers/pod.go]: The changes are in, but they were a little more complicated than my suggestion as it turns out.  Please check again and see if they're sufficient.

**Review by christarazi — APPROVED** [review]

**Comment by javanthropus** [comment]
@joamaki, I think I jammed this by requesting a re-review from you after pushing my last set of updates.  Can you approve this again?

How much longer before this is merged?

**Review by joamaki — APPROVED** [review]

**Comment by javanthropus** [comment]
I can't tell if the failing tests are a result of my changes, but I don't think they are.
