### PR TITLE
spire: Fix unreliable test

### LINKED ISSUE #40130: CI: TestSpireDelegateClient_GetCertificateForIdentity/get_certificate_for_numeric_identity
```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃   FAIL  package: github.com/cilium/cilium/pkg/auth/spire   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

--- FAIL: TestSpireDelegateClient_GetCertificateForIdentity (0.02s)
--- FAIL: TestSpireDelegateClient_GetCertificateForIdentity/get_certificate_for_numeric_identity (0.00s)

    certificate_provider_test.go:393: SpireDelegateClient.GetCertificateForIdentity() = &{[[48 130 1 221 48 130 1 70 160 3 2 1 2 2 1 1 48 13 6 9 42 134 72 134 247 13 1 1 11 5 0 48 0 48 32 24 15 48 48 48 49 48 49 48 49 48 48 48 48 48 48 90 23 13 50 53 48 54 49 57 49 51 48 57 48 51 90 48 0 48 129 159 48 13 6 9 42 134 72 134 247 13 1 1 1 5 0 3 129 141 0 48 129 137 2 129 129 0 203 198 50 36 248 151 4 0 9 245 142 231 166 87 93 52 98 227 182 149 113 221 128 246 99 60 178 41 147 146 224 12 14 140 114 8 39 30 87 33 195 49 171 11 136 110 176 124 58 210 236 48 96 246 219 2 10 82 8 80 88 100 22 94 90 152 56 234 37 107 209 35 0 49 248 43 27 146 163 1 166 134 222 61 99 55 13 191 196 131 16 172 134 128 238 100 162 21 132 156 109 39 52 8 93 126 28 162 132 193 85 95 193 139 219 57 181 123 192 228 147 119 28 87 213 184 37 207 2 3 1 0 1 163 101 48 99 48 14 6 3 85 29 15 1 1 255 4 4 3 2 7 128 48 29 6 3 85 29 37 4 22 48 20 6 8 43 6 1 5 5 7 3 1 6 8 43 6 1 5 5 7 3 2 48 50 6 3 85 29 17 1 1 255 4 40 48 38 134 36 115 112 105 102 102 101 58 47 47 115 112 105 102 102 101 46 99 105 108 105 117 109 47 105 100 101 110 116 105 116 121 47 49 50 51 52 48 13 6 9 42 134 72 134 247 13 1 1 11 5 0 3 129 129 0 139 2 249 196 117 104 184 249 113 142 249 185 22 184 171 66 246 230 83 52 151 35 215 193 98 18 251 50 157 150 76 168 9 7 100 231 51 25 37 187 176 35 129 74 118 176 62 223 158 88 12 35 239 0 127 250 244 107 161 125 100 213 144 18 167 6 196 152 128 112 42 227 32 107 214 101 57 191 79 165 244 137 123 242 171 50 101 169 222 75 206 225 4 22 63 204 169 85 52 102 157 61 17 163 183 135 72 154 66 131 207 87 236 140 108 226 1 210 154 215 64 192 143 243 117 141 45 218]] 0x40003b5ab0 [] [] [] 0x40003fac08}, want &{[[48 130 1 221 48 130 1 70 160 3 2 1 2 2 1 1 48 13 6 9 42 134 72 134 247 13 1 1 11 5 0 48 0 48 32 24 15 48 48 48 49 48 49 48 49 48 48 48 48 48 48 90 23 13 50 53 48 54 49 57 49 51 48 57 48 51 90 48 0 48 129 159 48 13 6 9 42 134 72 134 247 13 1 1 1 5 0 3 129 141 0 48 129 137 2 129 129 0 203 198 50 36 248 151 4 0 9 245 142 231 166 87 93 52 98 227 182 149 113 221 128 246 99 60 178 41 147 146 224 12 14 140 114 8 39 30 87 33 195 49 171 11 136 110 176 124 58 210 236 48 96 246 219 2 10 82 8 80 88 100 22 94 90 152 56 234 37 107 209 35 0 49 248 43 27 146 163 1 166 134 222 61 99 55 13 191 196 131 16 172 134 128 238 100 162 21 132 156 109 39 52 8 93 126 28 162 132 193 85 95 193 139 219 57 181 123 192 228 147 119 28 87 213 184 37 207 2 3 1 0 1 163 101 48 99 48 14 6 3 85 29 15 1 1 255 4 4 3 2 7 128 48 29 6 3 85 29 37 4 22 48 20 6 8 43 6 1 5 5 7 3 1 6 8 43 6 1 5 5 7 3 2 48 50 6 3 85 29 17 1 1 255 4 40 48 38 134 36 115 112 105 102 102 101 58 47 47 115 112 105 102 102 101 46 99 105 108 105 117 109 47 105 100 101 110 116 105 116 121 47 49 50 51 52 48 13 6 9 42 134 72 134 247 13 1 1 11 5 0 3 129 129 0 139 2 249 196 117 104 184 249 113 142 249 185 22 184 171 66 246 230 83 52 151 35 215 193 98 18 251 50 157 150 76 168 9 7 100 231 51 25 37 187 176 35 129 74 118 176 62 223 158 88 12 35 239 0 127 250 244 107 161 125 100 213 144 18 167 6 196 152 128 112 42 227 32 107 214 101 57 191 79 165 244 137 123 242 171 50 101 169 222 75 206 225 4 22 63 204 169 85 52 102 157 61 17 163 183 135 72 154 66 131 207 87 236 140 108 226 1 210 154 215 64 192 143 243 117 141 45 218]] 0x40003b5960 [] [] [] 0x40003fa608}
```

Full logs: https://github.com/cilium/cilium/actions/runs/15757273749/job/44415390343

Seen on #40023

/cc @cilium/sig-servicemesh

### PR DESCRIPTION
**Pull request by joestringer**
Since the introduction of private FIPS fields in core library RSA
key fields, the Certificate.PrivateKey fields can differ when generated
from the same key, as observed by `reflect.DeepEqual`. If you use the native
type's `.Equal()` function, it reports the fields are the same.

This difference only appears when running this test frequently or many
times in a row, such as by using `go test -count=1000 -failfast ...`

Expand out the checks for the Certificate's child fields to validate
the Certificate, PrivateKey and Leaf independently. While we're at it,
switch to `assert.Equal` so that there's a higher chance that the output
can be interpreted by developers when the test fails.

Fixes: https://github.com/cilium/cilium/issues/40130

### CODE REVIEW

**Comment by joestringer** [comment]
Nominated for backport back to 1.16 or later because they all use Go 1.24 so each branch could see unreliable failures for this test due to the behavior of the standard library.

File: pkg/auth/spire/certificate_provider_test.go [hunk 1]
```diff
@@ -389,8 +390,24 @@ func TestSpireDelegateClient_GetCertificateForIdentity(t *testing.T) {
...
-			if !reflect.DeepEqual(got, tt.want) {
-				t.Errorf("SpireDelegateClient.GetCertificateForIdentity() = %v, want %v", got, tt.want)
+			if tt.want != nil {
+				if !assert.Equal(t, tt.want.Certificate, got.Certificate) {
+					t.Errorf("SpireDelegateClient.GetCertificateForIdentity().Certificate = %v, want %v", got.Certificate, tt.want.Certificate)
+				}
+				wantKey := tt.want.PrivateKey.(*rsa.PrivateKey)
+				gotKey := got.PrivateKey.(*rsa.PrivateKey)
+				if !wantKey.Equal(gotKey) {
+					if !assert.Equal(t, tt.want.PrivateKey, got.PrivateKey) {
```
Comment (mhofstetter) [inline pkg/auth/spire/certificate_provider_test.go]: you can add a message to the assert functions instead of checking their result and emitting an additional error.

```
assert.Equal(t, tt.want.PrivateKey, got.PrivateKey, "SpireDelegateClient.GetCertificateForIdentity().PrivateKey = %v, want %v", got.PrivateKey, tt.want.PrivateKey)
```

File: pkg/auth/spire/certificate_provider_test.go [hunk 2]
```diff
@@ -389,8 +390,24 @@ func TestSpireDelegateClient_GetCertificateForIdentity(t *testing.T) {
...
+						t.Errorf("SpireDelegateClient.GetCertificateForIdentity().PrivateKey = %v, want %v", got.PrivateKey, tt.want.PrivateKey)
+					}
+				}
+				if !assert.Equal(t, tt.want.Leaf, got.Leaf) {
+					t.Errorf("SpireDelegateClient.GetCertificateForIdentity().Leaf = %v, want %v", got.Leaf, tt.want.Leaf)
+				}
+			} else {
+				if !assert.Equal(t, tt.want, got) {
```
Comment (mhofstetter) [inline pkg/auth/spire/certificate_provider_test.go]: -> `assert.Nil(t, got, "SpireDelegateClient.GetCertificateForIdentity() = %v, should be nil")` ?

File: pkg/auth/spire/certificate_provider_test.go [hunk 3]
```diff
@@ -389,8 +390,24 @@ func TestSpireDelegateClient_GetCertificateForIdentity(t *testing.T) {
...
 			}
-			if !reflect.DeepEqual(got, tt.want) {
-				t.Errorf("SpireDelegateClient.GetCertificateForIdentity() = %v, want %v", got, tt.want)
+			if tt.want != nil {
+				if !assert.Equal(t, tt.want.Certificate, got.Certificate) {
+					t.Errorf("SpireDelegateClient.GetCertificateForIdentity().Certificate = %v, want %v", got.Certificate, tt.want.Certificate)
+				}
+				wantKey := tt.want.PrivateKey.(*rsa.PrivateKey)
+				gotKey := got.PrivateKey.(*rsa.PrivateKey)
+				if !wantKey.Equal(gotKey) {
```
Comment (mhofstetter) [inline pkg/auth/spire/certificate_provider_test.go]: is it really necessary to have this additional equality check on the type itself - even though we have the following equals assertion?

IMO if one of them isn't reliable we should simply not use it for assertion at all.

File: pkg/auth/spire/certificate_provider_test.go [hunk 4]
```diff
@@ -389,8 +390,24 @@ func TestSpireDelegateClient_GetCertificateForIdentity(t *testing.T) {
 				t.Errorf("SpireDelegateClient.GetCertificateForIdentity() error = %v, wantErr %v", err, tt.wantErr)
```
Comment (mhofstetter) [inline pkg/auth/spire/certificate_provider_test.go]: maybe worth to refactor this to use testify too - while we're at it.

```
assert.Equal(t, tt.wantErr, err != nil, "SpireDelegateClient.GetCertificateForIdentity() error = %v, wantErr %v", err, tt.wantErr)

```

**Review by mhofstetter — COMMENTED** [review]
Thanks Joe! I left some comments that might help to make the test more readable.

edit: maybe it would be worth to add a small comment in the code why we're comparing like this.

File: pkg/auth/spire/certificate_provider_test.go (hunk 3 above)
Comment (joestringer) [reply pkg/auth/spire/certificate_provider_test.go]: Yeah it's necessary unfortunately. Upstream core libraries have private fields that differ, but they provide an `.Equal()` function to determine equality. That's the underlying reason for the unreliability of the test.

Similar to your other feedback on this PR, we can tidy up the logic here to simplify the test logic. It looks like there's a few test files that have similar poor patterns for use of `testify.assert`, will take note that could do with some follow up.

File: pkg/auth/spire/certificate_provider_test.go (hunk 1 above)
Comment (joestringer) [reply pkg/auth/spire/certificate_provider_test.go]: Yeah that can be helpful in general. For many of these cases, `assert.Equal` will already emit the relevant information for us in a standardized form. Where this PR uses `assert.Equal`, I'll just drop the message entirely.

File: pkg/auth/spire/certificate_provider_test.go (hunk 4 above)
Comment (joestringer) [reply pkg/auth/spire/certificate_provider_test.go]: Yeah makes sense. I'll apply similar changes to the rest of the file.

**Comment by joestringer** [comment]
Thanks for the review @mhofstetter, that tidies up / simplifies the code a fair bit:

```
@@ -386,35 +368,25 @@ func TestSpireDelegateClient_GetCertificateForIdentity(t *testing.T) {
                                svidStore: svidStore,
                        }
                        got, err := s.GetCertificateForIdentity(tt.args.id)
-                       if (err != nil) != tt.wantErr {
-                               t.Errorf("SpireDelegateClient.GetCertificateForIdentity() error = %v, wantErr %v", err, tt.wantErr)
+                       assert.Equal(t, tt.wantErr, err != nil)
+                       if tt.want == nil {
+                               assert.Nil(t, got)
                                return
                        }
-                       if tt.want != nil {
-                               if !assert.Equal(t, tt.want.Certificate, got.Certificate) {
-                                       t.Errorf("SpireDelegateClient.GetCertificateForIdentity().Certificate = %v, want %v", got.Certificate, tt.want.Certificate)
-                               }
-                               wantKey := tt.want.PrivateKey.(*rsa.PrivateKey)
-                               gotKey := got.PrivateKey.(*rsa.PrivateKey)
-                               if !wantKey.Equal(gotKey) {
-                                       if !assert.Equal(t, tt.want.PrivateKey, got.PrivateKey) {
-                                               t.Errorf("SpireDelegateClient.GetCertificateForIdentity().PrivateKey = %v, want %v", got.PrivateKey, tt.want.PrivateKey)
-                                       }
-                               }
-                               if !assert.Equal(t, tt.want.Leaf, got.Leaf) {
-                                       t.Errorf("SpireDelegateClient.GetCertificateForIdentity().Leaf = %v, want %v", got.Leaf, tt.want.Leaf)
-                               }
-                       } else {
-                               if !assert.Equal(t, tt.want, got) {
-                                       t.Errorf("SpireDelegateClient.GetCertificateForIdentity() = %v, want %v", got, tt.want)
-                               }
-                       }
+                       assert.Equal(t, tt.want.Certificate, got.Certificate)
+                       // Standard library hides private fields in the
+                       // PrivateKey for FIPS compliance, which causes
+                       // "assert.Equal()" to report inconsistent results,
+                       // leading to unreliable failures of the test. Since
+                       // we know the types here we can cast and use the type
+                       // specific Equals.
+                       wantKey := tt.want.PrivateKey.(*rsa.PrivateKey)
+                       gotKey := got.PrivateKey.(*rsa.PrivateKey)
+                       assert.True(t, wantKey.Equal(gotKey),
+                               "SpireDelegateClient.GetCertificateForIdentity().PrivateKey: %v\nwant: %v",
+                               got.PrivateKey, tt.want.PrivateKey,
+                       )
+                       assert.Equal(t, tt.want.Leaf, got.Leaf)
                })
        }
 }
```

I'll tidy up the other test assertions in the same file and re-push.

**Comment by joestringer** [comment]
sigstore appears to be having one of those days. Will retry CI.

**Review by mhofstetter — APPROVED** [review]
Thanks!
