### PR TITLE
fix staticchecker warnings

### LINKED ISSUE #7920: Resolve staticchecker warnings
1. Install staticcheck (https://github.com/dominikh/go-tools#installation)
2. Run `staticcheck` against a package

    ```
    staticcheck github.com/cilium/cilium/pkg/idpool
    pkg/idpool/idpool_test.go:346:2: should use for range instead of for { select {} } (S1000)
    ```
3. Fix the warnings. Maintain at least one commit per package. Split it up if a package contains a lot of warnings.
4. Paste the output of staticcheck of all fixed warnings in the commit
5. Submit PR
6. Brag on Slack

### PR DESCRIPTION
**Pull request by darshanime**
Fix static checker warnings
Fixes: #7920

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7973)

### CODE REVIEW

File: pkg/alignchecker/alignchecker.go [hunk 1]
```diff
@@ -113,7 +113,7 @@ func check(name string, toCheck []reflect.Type, structs map[string]structInfo) e
 	for _, g := range toCheck {
 		c, found := structs[name]
 		if !found {
-			return fmt.Errorf("C struct %s not found", name)
+			return fmt.Errorf("not found C struct %s", name)
```
Comment (joestringer) [inline pkg/alignchecker/alignchecker.go]: The previous error actually makes sense, while this new one doesn't really make sense to me. Is the staticchecker complaining that variable strings are in the middle of an error? Or starting with a capital letter?

File: pkg/alignchecker/alignchecker_test.go [hunk 2]
```diff
@@ -34,27 +34,15 @@ func Test(t *testing.T) {
 const path = "testdata/bpf_foo.o"
 
 type foo struct {
-	ipv6 [4]uint32 `align:"$union0"`
```
Comment (joestringer) [inline pkg/alignchecker/alignchecker_test.go]: This kind of change is surprising to me, do you have the staticchecker warning for it?

/cc @brb I would imagine these fields are here for testing purposes.

File: pkg/bpf/map.go [hunk 3]
```diff
@@ -120,10 +120,7 @@ func (t MapType) String() string {
 }
 
 func (t MapType) allowsPreallocation() bool {
-	if t == MapTypeLPMTrie {
-		return false
-	}
-	return true
+	return t == MapTypeLPMTrie
```
Comment (joestringer) [inline pkg/bpf/map.go]: This logic has been exactly reversed, please make it consistent with the previous logic.

File: pkg/elf/symbols.go [hunk 4]
```diff
@@ -26,18 +26,8 @@ import (
...
-	endpointMapPrefix = "1/0x"     // CILIUM_MAP_POLICY ## / ## LXC_ID
-	endpointRelPrefix = ".rel1/0x" // .rel ## endpointMapPrefix
-
-	// nMapRelocations is an approximation of the number of offsets in an
-	// ELF relating to map names that need to be adjusted. It's used for
-	// map initialization within 'Symbols'.
-	//
-	// $ readelf -a bpf/bpf_lxc.o | grep "cilium_.*_" | grep "^0000" | wc -l
-	// 51
-	nMapRelocations = 64
```
Comment (joestringer) [inline pkg/elf/symbols.go]: This was intended for use in `extractFrom()` for `stringOffsets` map initialization, but was dropped at some point. Would you mind using it there?

https://github.com/cilium/cilium/blob/64ec2d12ea7616b32e419a25a2e755a6eee59614/pkg/elf/symbols.go#L154-L158

File: pkg/metrics/status.go [hunk 5]
```diff
@@ -15,19 +15,13 @@
...
-
 	clientPkg "github.com/cilium/cilium/pkg/client"
 	healthClientPkg "github.com/cilium/cilium/pkg/health/client"
 
 	"github.com/prometheus/client_golang/prometheus"
 	log "github.com/sirupsen/logrus"
 )
 
-const (
-	updateLatencyMetricsInterval = 30 * time.Second
```
Comment (joestringer) [inline pkg/metrics/status.go]: @mrostecki did you intend to use this for something? git log points to a commit where you introduced this.

File: pkg/policy/l4_test.go [hunk 6]
```diff
@@ -28,35 +28,6 @@ import (
 	. "gopkg.in/check.v1"
 )
 
-func (s *PolicyTestSuite) testDPortCoverage(c *C, policy L4Policy,
```
Comment (joestringer) [inline pkg/policy/l4_test.go:31]: Why is this test being removed?

File: pkg/policy/rule_test.go [hunk 7]
```diff
@@ -30,8 +30,8 @@ import (
 	"github.com/cilium/cilium/pkg/labels"
 	"github.com/cilium/cilium/pkg/option"
 	"github.com/cilium/cilium/pkg/policy/api"
+	logging "github.com/op/go-logging"
```
Comment (joestringer) [inline pkg/policy/rule_test.go]: This change is inconsistent with the style we use (group go runtime, then group cilium, then group external dependencies), what's the staticchecker warning for this?

File: pkg/policy/rule_test.go [hunk 8]
```diff
@@ -324,7 +324,7 @@ func (ds *PolicyTestSuite) TestL4Policy(c *C) {
 	c.Assert(err, IsNil)
 	c.Assert(res, IsNil)
 
-	res2, err = rule2.resolveEgressPolicy(fromFoo, &egressState, NewL4Policy(), nil)
+	_, err = rule2.resolveEgressPolicy(fromFoo, &egressState, NewL4Policy(), nil)
```
Comment (joestringer) [inline pkg/policy/rule_test.go]: This looks like a typo where two lines down it should be checking `res2` instead?

File: pkg/policy/rules.go [hunk 9]
```diff
@@ -19,8 +19,7 @@ import (
 	"strconv"
 
 	"github.com/cilium/cilium/pkg/policy/api"
-
-	"k8s.io/apimachinery/pkg/apis/meta/v1"
+	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
```
Comment (joestringer) [inline pkg/policy/rules.go:23]: Again, inconsistent with style. `v1` change is OK but external dependencies typically should be separated from cilium dependencies by a newline.

**Review by joestringer — CHANGES_REQUESTED** [review]
Thanks for working through these, I've added some feedback below.

I also noticed that several of the commits are missing signoff. You should be able to fix these using something like `git rebase origin/master --exec "git commit --amend -s"` to rebase and add the signoff to each commit (assuming your git config has your email/name configured).

File: pkg/alignchecker/alignchecker.go (hunk 1 above)
Comment (darshanime) [reply pkg/alignchecker/alignchecker.go]: starting with a capital letter.
how about `could not find C struct %s`?

File: pkg/alignchecker/alignchecker_test.go (hunk 2 above)
Comment (joestringer) [reply pkg/alignchecker/alignchecker_test.go]: Actually, Travis already complains about this, these deletions are breaking unit tests.

Comment (darshanime) [reply pkg/alignchecker/alignchecker_test.go]: yeah, `pkg/alignchecker/alignchecker_test.go:37:2: field ipv6 is unused (U1000)`. 
I figured, I'd just look at the tests on CI and revert if turns out to be a false positive from the staticchecker.

File: pkg/policy/rule_test.go (hunk 7 above)
Comment (darshanime) [reply pkg/policy/rule_test.go]: ah, that's just my editor acting up. will revert.

File: pkg/alignchecker/alignchecker_test.go (hunk 2 above)
Comment (tgraf) [reply pkg/alignchecker/alignchecker_test.go]: I think the staticchecker can't possibly know that these fields are used as there is no golang usage.

Comment (tgraf) [reply pkg/alignchecker/alignchecker_test.go]: Does staticchecker allow to annotate fields so it ignores the warning?

File: pkg/bpf/map.go [hunk 10]
```diff
@@ -120,10 +120,7 @@ func (t MapType) String() string {
 }
 
 func (t MapType) allowsPreallocation() bool {
```
Comment (aanm) [inline pkg/bpf/map.go:122]: commit missing sign off

File: pkg/buildqueue/buildqueue.go [hunk 11]
```diff
@@ -122,7 +122,7 @@ func NewBuildQueue(name string) *BuildQueue {
 		name:             name,
 		buildStatus:      buildStatusMap{},
 		workerBuildQueue: make(chan Builder, buildQueueSize),
-		stopWorker:       make(chan struct{}, 0),
+		stopWorker:       make(chan struct{}),
```
Comment (aanm) [inline pkg/buildqueue/buildqueue.go]: commit missing sign-off

Comment (aanm) [reply pkg/buildqueue/buildqueue.go]: this code does not exist on master you will need to drop this commit and rebase against master

File: pkg/command/output.go [hunk 12]
```diff
@@ -57,7 +57,7 @@ func PrintOutputWithType(data interface{}, outputType string) error {
 		return dumpJSON(data, re.ReplaceAllString(outputType, "$1"))
 	}
 
-	return fmt.Errorf("Couldn't found output printer")
+	return fmt.Errorf("couldn't found output printer")
```
Comment (aanm) [inline pkg/command/output.go:60]: missing sign off

**Review by aanm — CHANGES_REQUESTED** [review]

**Comment by tgraf** [comment]
@darshanime This looks fantastic overall. Let us know once the comments are addressed so we can re-review.

**Comment by joestringer** [comment]
test-me-please

File: pkg/alignchecker/alignchecker_test.go (hunk 2 above)
Comment (aanm) [reply pkg/alignchecker/alignchecker_test.go]: cc @brb

File: pkg/elf/symbols.go (hunk 4 above)
Comment (aanm) [reply pkg/elf/symbols.go]: Was this addressed? @darshanime

File: pkg/ipcache/ipcache.go [hunk 13]
```diff
@@ -306,7 +306,7 @@ func (ipc *IPCache) Upsert(ip string, hostIP net.IP, hostKey uint8, newIdentity
 			cidrStr := cidr.String()
 			if cidrIdentity, cidrFound := ipc.ipToIdentityCache[cidrStr]; cidrFound {
 				oldHostIP, _ = ipc.getHostIPCache(cidrStr)
-				if cidrIdentity.ID != newIdentity.ID || bytes.Compare(oldHostIP, hostIP) != 0 {
+				if cidrIdentity.ID != newIdentity.ID || bytes.Equal(oldHostIP, hostIP) {
```
Comment (aanm) [inline pkg/ipcache/ipcache.go]: BUG: should be `!bytes.Equal(oldHostIP, hostIP)`

File: pkg/policy/distillery_test.go [hunk 14]
```diff
@@ -29,8 +29,8 @@ import (
 	"github.com/cilium/cilium/pkg/policy/api"
 	"github.com/cilium/cilium/pkg/policy/trafficdirection"
 	"github.com/cilium/cilium/pkg/testutils"
+	logging "github.com/op/go-logging"
```
Comment (aanm) [inline pkg/policy/distillery_test.go]: leave it on line 33

File: pkg/policy/l4_test.go (hunk 6 above)
Comment (aanm) [reply pkg/policy/l4_test.go:31]: @darshanime Is this solved?

File: pkg/nodediscovery/nodediscovery.go [hunk 15]
```diff
@@ -51,11 +51,7 @@ type NodeDiscovery struct {
 }
 
 func enableLocalNodeRoute() bool {
-	if option.Config.IsFlannelMasterDeviceSet() {
-		return false
-	}
-
-	return true
+	return option.Config.IsFlannelMasterDeviceSet()
```
Comment (aanm) [inline pkg/nodediscovery/nodediscovery.go]: BUG: should be `return !option.Config.IsFlannelMasterDeviceSet()`

File: pkg/bpf/map.go [hunk 16]
```diff
@@ -120,7 +121,7 @@ func (t MapType) String() string {
...
-	return t == MapTypeLPMTrie
```
Comment (aanm) [inline pkg/bpf/map.go]: BUG? What's happening here?

File: pkg/metrics/status.go [hunk 17]
```diff
@@ -1,161 +0,0 @@
-// Copyright 2018 Authors of Cilium
```
Comment (aanm) [inline pkg/metrics/status.go]: Why is this code being removed?

File: pkg/monitor/dissect.go [hunk 18]
```diff
@@ -23,9 +23,10 @@ import (
 	"github.com/cilium/cilium/pkg/logging"
 	"github.com/cilium/cilium/pkg/logging/logfields"
 
+	"strconv"
```
Comment (aanm) [inline pkg/monitor/dissect.go]: should be between lines 18 and 20

File: pkg/policy/l4_filter_test.go [hunk 19]
```diff
@@ -24,8 +24,8 @@ import (
 	"github.com/cilium/cilium/pkg/labels"
 	"github.com/cilium/cilium/pkg/option"
 	"github.com/cilium/cilium/pkg/policy/api"
+	logging "github.com/op/go-logging"
```
Comment (aanm) [inline pkg/policy/l4_filter_test.go]: should be on line 28

**Review by aanm — CHANGES_REQUESTED** [review]

**Comment by joestringer** [comment]
test-me-please

File: pkg/policy/rule_test.go (hunk 8 above)
Comment (joestringer) [reply pkg/policy/rule_test.go]: @darshanime looks like the check on line 253 (now 246) needs to actually use the result of this function instead of this change.

File: pkg/policy/l4_test.go (hunk 6 above)
Comment (darshanime) [reply pkg/policy/l4_test.go:31]: yes, added. it again

File: pkg/alignchecker/alignchecker_test.go (hunk 2 above)
Comment (darshanime) [reply pkg/alignchecker/alignchecker_test.go]: hmm, yes it does have that. ` //lint:ignore Check1[,Check2,...,CheckN] reason`
should I put it everywhere there are false positives?

File: pkg/elf/symbols.go (hunk 4 above)
Comment (darshanime) [reply pkg/elf/symbols.go]: @joestringer I am not sure how you wanted to use the constants to initialize the map, can you elaborate please?

File: pkg/alignchecker/alignchecker_test.go (hunk 2 above)
Comment (darshanime) [reply pkg/alignchecker/alignchecker_test.go]: that might get unwieldy as there are many such places.  https://gist.github.com/darshanime/1e4da42ec3c2da5024037c42f30b33ad

File: pkg/elf/symbols.go (hunk 4 above)
Comment (joestringer) [reply pkg/elf/symbols.go]: @darshanime You can pass it to the `make` call for `stringOffsets` map to set the size of the map.

**Comment by aanm** [comment]
test-me-please

File: pkg/policy/l4_filter_test.go [hunk 20]
```diff
@@ -47,14 +47,12 @@ var (
 	bazSelector = api.NewESFromLabels(labels.ParseSelectLabel("baz"))
 
 	cachedFooSelector, _ = testSelectorCache.AddIdentitySelector(dummySelectorCacheUser, fooSelector)
-	cachedBarSelector, _ = testSelectorCache.AddIdentitySelector(dummySelectorCacheUser, barSelector)
```
Comment (aanm) [inline pkg/policy/l4_filter_test.go:50]: How come the  test doesn't need this line?

**Review by aanm — COMMENTED** [review]
Only one comment left that can be addressed after the PR is merged

File: pkg/policy/l4_filter_test.go (hunk 20 above)
Comment (aanm) [reply pkg/policy/l4_filter_test.go:50]: cc @ianvernon

**Review by aanm — APPROVED** [review]

**Comment by darshanime** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
CI failed for a know bug #8234

File: pkg/policy/l4_filter_test.go (hunk 20 above)
Comment (ianvernon) [reply pkg/policy/l4_filter_test.go:50]: Looks like it was added but never used by @jrajahalme . I don't see this as a big concern, it was probably left over after the tests were reworked after initially being written.
