### PR TITLE
allocator: Fix kvstore identity leak

### LINKED ISSUE #35451: kvstore implementation leaks cilium identities during identity churn
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

We have discovered that when churning (creating and deleting) identities by starting and stopping pods, some identities are never properly cleaned up by the identity GC. We have tracked this down to a race between the [syncLocalKeys](https://github.com/cilium/cilium/blob/b3a3108696fd1716de256a17998375356411d2d4/pkg/allocator/allocator.go#L952-L970) function running in the background on an interval, and the release of the node usage of identities.

We correlate this with ["Re-created missing slave key"](https://github.com/cilium/cilium/blob/b3a3108696fd1716de256a17998375356411d2d4/pkg/kvstore/allocator/allocator.go#L303) logline, and see that the keys mentioned in these loglines are the ones leaked. 

We see this happen once in a while, but with long lived hosts, this can result in a lot of leaked identities in large clusters.

### How can we reproduce the issue?

Install cilium with kvstore / etcd mode in eg. kind. Set the `kvstore-periodic-sync` to a low value to reproduce easier. eg. to `10ms`.

Then create and delete some pods with unique labels in a loop eg. like;
```bash
counter=0
while true; do
  kubectl run --rm -it -n default --image alpine testing-${counter} -- sleep 1
  counter=$((counter+1))
  sleep .1
done
```
Then check the logs of the agent(s) the pods run on;
```bash
$ logs -n kube-system -l k8s-app=cilium  -f | grep "slave"
time="2024-10-21T07:35:49.925108545Z" level=warning msg="Re-created missing slave key" key="cilium/state/identities/v1/value/k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default;k8s:io.cilium.k8s.policy.cluster=default;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=default;k8s:run=testing-0;/172.18.0.2" subsys=kvstorebackend
time="2024-10-21T07:35:51.674576796Z" level=warning msg="Re-created missing slave key" key="cilium/state/identities/v1/value/k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default;k8s:io.cilium.k8s.policy.cluster=default;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=default;k8s:run=testing-1;/172.18.0.2" subsys=kvstorebackend
time="2024-10-21T07:35:57.025689132Z" level=warning msg="Re-created missing slave key" key="cilium/state/identities/v1/value/k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default;k8s:io.cilium.k8s.policy.cluster=default;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=default;k8s:run=testing-2;/172.18.0.2" subsys=kvstorebackend
```

Then check if any identity node values / slave keys are leaked, even when all the pods are deleted;

```bash
$ kubectl exec -n kube-system daemonset/cilium -- cilium kvstore get --recursive "cilium/state/identities/v1/value/" 2>&1 | grep testing-1
cilium/state/identities/v1/value/k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default;k8s:io.cilium.k8s.policy.cluster=default;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=default;k8s:run=testing-1;/172.18.0.2 => 36729
cilium/state/identities/v1/value/k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default;k8s:io.cilium.k8s.policy.cluster=default;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=default;k8s:run=testing-16;/172.18.0.2 => 7225
cilium/state/identities/v1/value/k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default;k8s:io.cilium.k8s.policy.cluster=default;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=default;k8s:run=testing-12;/172.18.0.2 => 4687
[...]
```

This means these identities won't be GCed by the cilium-operator, since there are still references to them. The keys are written with the node lease, so even tho. they are no longer "updated", the lease will keep them alive.

The only mitigation so far is either cleaning up manually in etcd, or restarting the cilium-agent to make it get a new lease - and then wait for the initial lease to be cleaned up when it expires.

### Cilium Version

Seems to affect all. We are seeing this in both v1.13 and latest master. Latest reproduced on is https://github.com/cilium/cilium/commit/1ede9d906524893135084cbf71fa54ad6197d446, so all versions seem expected.

### Kernel Version

n/a

### Kubernetes Version

n/a

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by odinuge**
This fixes an identity leak in the kvstore implementation that has been here since the beginning. If the kvstore-refresh sync dumps the loadKeys immediately before a key is released, it will try to update that key. In large clusters with a lot of identity and pod churn, we see this
happening multiple times an hour. It can be investigated by looking at
the "Re-created missing slave key" logline. This often leads to multiple
thousand extra identities in the clusters, that are unused and not
cleaned up.

This can also be easily mitigated by always grabbing the `slaveKeysMutex` - but that is most likely going to cause a lot of slowness to identity allocation on the agents, so that is probably not a good idea.

The term `slave` and `master` key is also a bit confusing, and sometimes its explained as `ID` and `reference` (eg. via acquire reference) - so getting a consistent and better naming scheme would be useful for the readability of the code. We can probably save that for another PR. 

See the commits for a more detailed explanation.

---

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: https://github.com/cilium/cilium/issues/35451

```release-note
Fix identity leak for kvstore identity mode
```

### CODE REVIEW

File: pkg/kvstore/etcd.go [hunk 1]
```diff
@@ -1152,6 +1152,34 @@ func (e *etcdClient) GetIfLocked(ctx context.Context, key string, lock KVLocker)
 	return getR.Kvs[0].Value, nil
 }
 
+// GetWithLeaseInfo returns value of key, together with a boolean indicating if the lease associated
+// with the key is held by this client.
+func (e *etcdClient) GetWithLeaseInfo(ctx context.Context, key string) (bv []byte, hasLease bool, err error) {
```
Comment (odinuge) [inline pkg/kvstore/etcd.go]: Struggling a bit on how to keep the lease abstraction to the kvstore implementation. The lease manager is only accessible, so returning the actual lease value here would be confusing and painful. Open for other suggestions on how to solve this.

Main thing is that we expect this to "always" be `hasLease == true` - and the case `hasLease == false` or `bv == nil` requires some extra "expensive" synchronization before updating the key.

File: pkg/allocator/allocator.go [hunk 2]
```diff
@@ -241,6 +241,18 @@ type Backend interface {
...
+	// When reliablyMissing is set it will also recreate missing master key.
+	UpdateMasterKey(ctx context.Context, id idpool.ID, key AllocatorKey, reliablyMissing bool) error
+
+	// ValidateSlaveKey validates that the slave part of the record that this node is using this key -> id
+	// mapping is up-to-date. If it returns true, it means that no action is needed.
+	ValidateSlaveKey(ctx context.Context, id idpool.ID, key AllocatorKey) (bool, error)
+
+	// UpdateSlaveKey refreshes the slave part of the record that this node is using this key -> id
+	// mapping. When reliablyMissing is set it will also recreate missing slave key.
+	UpdateSlaveKey(ctx context.Context, id idpool.ID, key AllocatorKey, reliablyMissing bool) error
```
Comment (odinuge) [inline pkg/allocator/allocator.go]: Trying to keep the existing lingua around these. In a follow-up PR we might want to change these to `upsertX` instead, as that is in practice what the implementation does (at lease kvstore), and then only use `reliablyMissing` for the initial operation.

File: pkg/kvstore/allocator/allocator.go [hunk 3]
```diff
@@ -274,17 +275,24 @@ func (k *kvstoreBackend) GetByID(ctx context.Context, id idpool.ID) (allocator.A
...
-		recreated  bool
 		keyPath    = path.Join(k.idPrefix, id.String())
 		keyEncoded = []byte(k.backend.Encode([]byte(key.GetKey())))
 		valueKey   = path.Join(k.valuePrefix, k.backend.Encode([]byte(key.GetKey())), k.suffix)
 	)
+	if !reliablyMissing {
+		// If we expect the key to be present, and it has the expected value, exit early as it's already correct
+		// in the kvstore. If there is an error, we skip to the CreateOnly part.
+		val, err := k.backend.Get(ctx, keyPath)
+		if err == nil && val != nil && bytes.Equal(val, keyEncoded) {
```
Comment (odinuge) [inline pkg/kvstore/allocator/allocator.go]: We can split this into a separate PR as well, since its not strictly required. (also reminds me that it deserves a separate commit maybe).

Main reason we want this is that we expect it to be present and up to date, and that is the case in 99.9% of the cases. A `Get` call here results in a single read-only `Range` request for a single key, while opening a transaction will always write the transaction to the WAL log and require an fsync on the etcd servers.

**Comment by odinuge** [comment]
Ahh. I'll rebase this and fix the conflict as well as remove the extra code in https://github.com/cilium/cilium/pull/34893#discussion_r1761128192 tomorrow morning.

**Comment by odinuge** [comment]
Got stuck with other work, but did the rebase now. Will read through on Monday and then remove the `draft` mark.

File: pkg/allocator/allocator.go [hunk 4]
```diff
@@ -952,18 +964,47 @@ func (a *Allocator) DeleteAllKeys() {
...
+		} else if slaveKeyOk {
+			continue
 		}
+
+		func() {
+			// We ensure we hold the slaveKeysMutex while checking if the localKey is still in use, and while we are
+			// doing the create/update operation. We do this to avoid re-creating a newly deleted slave key, that can
+			// potentially result in leaking it - as the identity gc in the operator won't delete slave keys.
+			a.slaveKeysMutex.Lock()
+			defer a.slaveKeysMutex.Unlock()
```
Comment (odinuge) [inline pkg/allocator/allocator.go]: I think its not 100% required to grab this lock in all cases, but I think its clearer to understand the flow and avoid regressions if we hold it. That ensures we don't do slave key/node key creations while the allocator is allocating that exact identity.

I don't think the overhead or lock congestion matter much here either, since we hit this code path very rarely - and only when this code happens concurrently with allocation or deallocation of local keys.

File: pkg/kvstore/allocator/doublewrite/backend.go [hunk 5]
```diff
@@ -175,6 +175,55 @@ func (d *doubleWriteBackend) UpdateKey(ctx context.Context, id idpool.ID, key al
 	return crdErr
 }
 
+func (d *doubleWriteBackend) UpdateMasterKey(ctx context.Context, id idpool.ID, key allocator.AllocatorKey, reliablyMissing bool) error {
```
Comment (odinuge) [inline pkg/kvstore/allocator/doublewrite/backend.go]: I've mostly just copied the logic from `UpdateKey` to keep the existing behavior.

File: pkg/kvstore/allocator/allocator.go (hunk 3 above)
Comment (odinuge) [reply pkg/kvstore/allocator/allocator.go]: We tested this internally, and the etcd load went down significantly.

File: pkg/kvstore/allocator/allocator.go [hunk 6]
```diff
@@ -287,10 +287,31 @@ func (k *kvstoreBackend) UpdateKey(ctx context.Context, id idpool.ID, key alloca
 	case success:
 		log.WithField(logfields.Key, keyPath).Warning("Re-created missing master key")
 	}
+	return nil
+}
+
+// UpdateKey refreshes the record that this node is using this key -> id
+// mapping. When reliablyMissing is set it will also recreate missing master or
+// slave keys.
```
Comment (youngnick) [inline pkg/kvstore/allocator/allocator.go]: Ideally we would avoid using master/slave words here. Is there a better option?

Comment (odinuge) [reply pkg/kvstore/allocator/allocator.go]: Agree. I already added a section in the PR description about this, and that we should probably come up with a more consistent and better naming. I think I would prefer doing that in a separate PR to differentiate between phrasing and logic, but if you think we should do it here, I'm happy to! I can do that when we agree on the overall idea here, and when we have a better phrasing.

I'm not 100% convinced what the best alternative phrasing is either, so very open to suggestions.
- `identity` and `node reference`?
- `leader` and `follower`?
- `primary` and `secondary`?

File: pkg/kvstore/etcd.go (hunk 1 above)
Comment (giorio94) [inline pkg/kvstore/etcd.go]: Nit. This method looks practically a copy of `Get`, with only minor differences in the return values. I definitely see the reason for creating a separate one to avoid having to change all callers, but I'd just implement `Get` based on this one, discarding the extra parameter, to remove the code duplication.

Comment (giorio94) [reply pkg/kvstore/etcd.go]: Your approach sounds reasonable to me. I'd probably just rename `hasLease` to `ownsLease` or something like that, as that boolean may be false even if the key is actually attached to a lease.

File: pkg/allocator/allocator.go [hunk 7]
```diff
@@ -964,18 +964,47 @@ func (a *Allocator) DeleteAllKeys() {
...
+		}
+
+		func() {
+			// We ensure we hold the slaveKeysMutex while checking if the localKey is still in use, and while we are
+			// doing the create/update operation. We do this to avoid re-creating a newly deleted slave key, that can
+			// potentially result in leaking it - as the identity gc in the operator won't delete slave keys.
+			a.slaveKeysMutex.Lock()
+			defer a.slaveKeysMutex.Unlock()
+			if key := a.localKeys.lookupID(id); key != nil && key.GetKey() == value.GetKey() {
+				if err := a.backend.UpdateSlaveKey(ctx, id, value, true); err != nil {
```
Comment (giorio94) [inline pkg/allocator/allocator.go]: The last parameter should be false, right? Otherwise it leads to a different behavior compared to before (i.e., not updating the key when out of sync).

File: pkg/allocator/allocator.go [hunk 8]
```diff
@@ -964,18 +964,47 @@ func (a *Allocator) DeleteAllKeys() {
...
+	// disappear while we perform the sync. For master keys this is fine as
+	// the garbage collector will remove it again. However, for slave keys, they
+	// will continue to exist until the kvstore lease expires after the agent is restarted.
+	// To ensure slave keys are not leaked we do an extra check before recreating a slave key.
 	ids := a.localKeys.getVerifiedIDs()
+	ctx := context.TODO()
 
 	for id, value := range ids {
-		if err := a.backend.UpdateKey(context.TODO(), id, value, false); err != nil {
+		if err := a.backend.UpdateMasterKey(ctx, id, value, false); err != nil {
```
Comment (giorio94) [inline pkg/allocator/allocator.go]: Nit. Technically the same race condition may occur in [`cache.onDeleteLocked`](https://github.com/cilium/cilium/blob/main/pkg/allocator/cache.go#L183) as well, although that is arguably way rarer, both because it is not expected to be called in normal conditions, and because the presence of the key is double-checked right before calling `UpdateKey`.

File: pkg/kvstore/allocator/allocator.go [hunk 9]
```diff
@@ -287,10 +287,31 @@ func (k *kvstoreBackend) UpdateKey(ctx context.Context, id idpool.ID, key alloca
...
+func (k *kvstoreBackend) UpdateKey(ctx context.Context, id idpool.ID, key allocator.AllocatorKey, reliablyMissing bool) error {
```
Comment (giorio94) [inline pkg/kvstore/allocator/allocator.go]: I wonder whether it would be possible to reduce the amount of changes here by passing an extra function as parameter to UpdateKey (instead of splitting it), to essentially allow running the locked part after checking that the key is actually still there. And the other backend implementations would simply ignore it, with no further changes. As a bonus, it would allow avoiding to have to find alternative names for master/slave.

Essentially the pseudocode (names are far from great) would be something like:

```go
func UpdateKey(...., ifLocalKeyStillExistsLocked func(func()) error {
    // Update master key
 
    // Validate slave key
    if ok {
        return
    }

    ifLocalKeyStillExistsLocked(func() {
        // Update slave key
    })
}

func ifLocalKeyStillExistsLocked(fn func()) {
   a.slaveKeysMutex.Lock()
   defer a.slaveKeysMutex.Unlock()

   if key := a.localKeys.lookupID(id); key != nil && key.GetKey() == value.GetKey() {
      fn()
   }
}
```

WDYT?

**Review by giorio94 — COMMENTED** [review]
Thanks for discovering this issue and proposing a fix. Your patch overall looks great to me -- I've just left a few minor comments inline.

File: pkg/allocator/allocator.go (hunk 7 above)
Comment (odinuge) [reply pkg/allocator/allocator.go]: I was explicitly setting `reliablyMissing: true` here to jump directly to a `CreateOnly` etcd call and avoid the extra `Get`.

Tho. I kinda agree with you that keeping it `false` makes sense to keep the existing behavior and not fail if it for some reason exists again here. Given we hit this code path _very very rarely_, saving a single etcd Get seems like a an optimization that we don't strictly need. 

I'll change this to `false`.

Comment (giorio94) [reply pkg/allocator/allocator.go]: Sounds good. Another case would be if say either the lease or the value are different, as with `reliablyMissing: true` the update would be always a no-op.

File: pkg/kvstore/allocator/allocator.go (hunk 9 above)
Comment (odinuge) [reply pkg/kvstore/allocator/allocator.go]: Hmm. I thought about this initially but struggled with making it work well without leaking too much of the abstraction into the allocator, but yeah, I agree this looks nice. I'll try to do this and see how it works out when I fix the other comments on Monday morning.

Thanks for the suggestion!

Comment (odinuge) [reply pkg/kvstore/allocator/allocator.go]: Implemented that here; https://github.com/cilium/cilium/pull/35617. Still very unsure about that approach, since its handing off a callback that grabs a lock - and if that goes wrong deadlocks are close.. Any thoughts?

Comment (giorio94) [reply pkg/kvstore/allocator/allocator.go]: Yeah, I personally feel both approaches to be fairly complex. The original one is probably a bit more involved in terms of changes that are required, and leaks part of the kvstore implementation details into the Backend interface. The new one on the other hand is a bit more obscure due to the need of handing the callback (with the additional complexity that it needs to grab the lock, although the risks should be the same at the end of the day).

I'm starting to wonder whether a simpler approach could be preferable, even though it would still allow for a race condition window (although way shorter compared to before the patch).

My understanding is that currently the race condition is triggered fairly often in high churn environments because the snapshot of keys is retrieved at the beginning of the loop, which then updates all keys. Given that etcd operations are potentially slow (especially with the default rate limiting settings), the whole operation can easily take in the order of multiple seconds in case of a significant number of identities on the given node, hence increasing the probability that the last ones that are processed are stale at that point.

This race condition window could be significantly reduced by checking before each loop iteration whether the current key still exists, but without holding the lock during the subsequent update. That requires accepting that it could still be released in the meanwhile, potentially causing a leak until the agent is restarted. 

As a potential extra check to remove that possibility, one could additionally bubble up whether the key got recreated from UpdateKey and in that case (which should be arguably only happen in a minority of cases), check once more whether the key is still allocated locally at that point, and if not calling `backend.Release` once more to delete the now stale entry (while holding the lock during the whole process to prevent concurrent operations).

That should require very little changes to the existing code base. WDYT?

Comment (odinuge) [reply pkg/kvstore/allocator/allocator.go]: Hmm, yeah, I kinda agree. The complexity here has grown a bit more than I would like.

This seems to pass the test I wrote as well. A bit convoluted but pretty small patch.
```diff
diff --git a/pkg/allocator/allocator.go b/pkg/allocator/allocator.go
index 709bcb2686..1ee33bd7e7 100644
--- a/pkg/allocator/allocator.go
+++ b/pkg/allocator/allocator.go
@@ -952,18 +952,45 @@ func (a *Allocator) DeleteAllKeys() {
 func (a *Allocator) syncLocalKeys() error {
        // Create a local copy of all local allocations to not require to hold
        // any locks while performing kvstore operations. Local use can
-       // disappear while we perform the sync but that is fine as worst case,
-       // a master key is created for a slave key that no longer exists. The
-       // garbage collector will remove it again.
+       // disappear while we perform the sync. For master keys this is fine as
+       // the garbage collector will remove it again. However, for slave keys, they
+       // will continue to exist until the kvstore lease expires after the agent is restarted.
+       // To ensure slave keys are not leaked we do an extra check before recreating a slave key.
        ids := a.localKeys.getVerifiedIDs()
+       ctx := context.TODO()

        for id, value := range ids {
-               if err := a.backend.UpdateKey(context.TODO(), id, value, false); err != nil {
-                       log.WithError(err).WithFields(logrus.Fields{
-                               fieldKey: value,
-                               fieldID:  id,
-                       }).Warning("Unable to sync key")
-               }
+               func() {
+                       if key := a.localKeys.lookupID(id); key == nil || key.GetKey() != value.GetKey() {
+                               // If key is not in use exit early
+                               return
+                       }
+                       err := a.backend.UpdateKey(ctx, id, value, false)
+                       if err != nil {
+                               log.WithError(err).WithFields(logrus.Fields{
+                                       fieldKey: value,
+                                       fieldID:  id,
+                               }).Warning("Error updating key")
+                       }
+                       if newKey := a.localKeys.lookupID(id); newKey != nil && newKey.GetKey() == value.GetKey() {
+                               // If key is still in use after we updated it, exit
+                               return
+                       }
+                       // If key has been deleted, grab the slaveKeysMutex and check again before releasing it
+                       a.slaveKeysMutex.Lock()
+                       defer a.slaveKeysMutex.Unlock()
+                       if newKey := a.localKeys.lookupID(id); newKey != nil && newKey.GetKey() == value.GetKey() {
+                               return
+                       }
+                       err = a.backend.Release(ctx, id, value)
+                       if err != nil {
+                               log.WithError(err).WithFields(logrus.Fields{
+                                       fieldKey: value,
+                                       fieldID:  id,
+                               }).Warning("Error releasing unused key")
+                       }
+               }()
+
        }

        return nil
```

I also did some thinking about the mutex itself, and we can also potentially do this to limit complexity even more. It does come and the cost of grabbing the mutex for every identity, but given it just grabs it via `RLock` any identity allocation/release will grab using `Lock` and get priority when the existing readers have finished.

```diff
--- a/pkg/allocator/allocator.go
+++ b/pkg/allocator/allocator.go
@@ -118,7 +118,7 @@ type Allocator struct {

        // slaveKeysMutex protects the concurrent access of the slave key by this
        // agent.
-       slaveKeysMutex lock.Mutex
+       slaveKeysMutex lock.RWMutex

        // mainCache is the main cache, representing the allocator contents of
        // the primary kvstore connection
@@ -952,18 +952,29 @@ func (a *Allocator) DeleteAllKeys() {
 func (a *Allocator) syncLocalKeys() error {
        // Create a local copy of all local allocations to not require to hold
        // any locks while performing kvstore operations. Local use can
-       // disappear while we perform the sync but that is fine as worst case,
-       // a master key is created for a slave key that no longer exists. The
-       // garbage collector will remove it again.
+       // disappear while we perform the sync. For master keys this is fine as
+       // the garbage collector will remove it again. However, for slave keys, they
+       // will continue to exist until the kvstore lease expires after the agent is restarted.
+       // To ensure slave keys are not leaked we do an extra check before recreating a slave key.
        ids := a.localKeys.getVerifiedIDs()
+       ctx := context.TODO()

        for id, value := range ids {
-               if err := a.backend.UpdateKey(context.TODO(), id, value, false); err != nil {
-                       log.WithError(err).WithFields(logrus.Fields{
-                               fieldKey: value,
-                               fieldID:  id,
-                       }).Warning("Unable to sync key")
-               }
+               func() {
+                       a.slaveKeysMutex.RLock()
+                       defer a.slaveKeysMutex.RUnlock()
+                       if key := a.localKeys.lookupID(id); key == nil || key.GetKey() != value.GetKey() {
+                               return
+                       }
+                       err := a.backend.UpdateKey(ctx, id, value, false)
+                       if err != nil {
+                               log.WithError(err).WithFields(logrus.Fields{
+                                       fieldKey: value,
+                                       fieldID:  id,
+                               }).Warning("Error updating key")
+                       }
+               }()
+
        }

        return nil
```

Both of these pass my synthetic test but I'll also test with my repro locally to ensure they are both sound.

Comment (odinuge) [reply pkg/kvstore/allocator/allocator.go]: Okay, so this seems to work pretty nice;
```diff
diff --git a/pkg/allocator/allocator.go b/pkg/allocator/allocator.go
index 709bcb2686..8edb930744 100644
--- a/pkg/allocator/allocator.go
+++ b/pkg/allocator/allocator.go
@@ -952,21 +952,56 @@ func (a *Allocator) DeleteAllKeys() {
 func (a *Allocator) syncLocalKeys() error {
        // Create a local copy of all local allocations to not require to hold
        // any locks while performing kvstore operations. Local use can
-       // disappear while we perform the sync but that is fine as worst case,
-       // a master key is created for a slave key that no longer exists. The
-       // garbage collector will remove it again.
+       // disappear while we perform the sync. For master keys this is fine as
+       // the garbage collector will remove it again. However, for slave keys, they
+       // will continue to exist until the kvstore lease expires after the agent is restarted.
+       // To ensure slave keys are not leaked we do an extra check before recreating a slave key.
        ids := a.localKeys.getVerifiedIDs()
+       ctx := context.TODO()

-       for id, value := range ids {
-               if err := a.backend.UpdateKey(context.TODO(), id, value, false); err != nil {
+       for id, key := range ids {
+               a.syncLocalKey(ctx, id, key)
+       }
+
+       return nil
+}
+
+func (a *Allocator) syncLocalKey(ctx context.Context, id idpool.ID, key AllocatorKey) {
+       ctx, cancel := context.WithTimeout(ctx, backendOpTimeout)
+       defer cancel()
+
+       encodedKey := key.GetKey()
+       if newId := a.localKeys.lookupKey(encodedKey); newId != id {
+               return
+       }
+       err := a.backend.UpdateKey(ctx, id, key, false)
+       if err != nil {
+               log.WithError(err).WithFields(logrus.Fields{
+                       fieldKey: key,
+                       fieldID:  id,
+               }).Warning("Error updating key")
+       }
+
+       if newId := a.localKeys.lookupKey(encodedKey); newId != idpool.NoID {
+               return
+       }
+
+       a.slaveKeysMutex.Lock()
+       defer a.slaveKeysMutex.Unlock()
+
+       if newId := a.localKeys.lookupKey(encodedKey); newId == idpool.NoID {
+               log.WithFields(logrus.Fields{
+                       fieldKey: key,
+                       fieldID:  id,
+               }).Warning("Releasing now unused key that was re-recreated")
+               err = a.backend.Release(ctx, id, key)
+               if err != nil {
                        log.WithError(err).WithFields(logrus.Fields{
-                               fieldKey: value,
+                               fieldKey: key,
                                fieldID:  id,
-                       }).Warning("Unable to sync key")
+                       }).Warning("Error releasing unused key")
                }
        }
-
-       return nil
 }

 func (a *Allocator) startLocalKeySync() {
 ```
 
 Tested a bunch today, and no leaks 🙌 
 
 With a short kvsync period I see a decent amount of these, but they are all cleared up, and no deadlocks;
 
 ```
 time="2024-10-31T15:44:15.689831095Z" level=info msg="Released last local use of key, invoking global release" key="[k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=default k8s:run=fix-2604]" subsys=kvstorebackend
time="2024-10-31T15:44:15.803218137Z" level=info msg="Removed endpoint" ciliumEndpointName=default/fix-2604 containerID=0059925165 containerInterface= datapathPolicyRevision=3 desiredPolicyRevision=3 endpointID=444 identity=5521 ipv4=10.244.1.84 ipv6= k8sPodName=default/fix-2604 subsys=endpoint
time="2024-10-31T15:44:16.003678137Z" level=warning msg="Re-created missing slave key" key="cilium/state/identities/v1/value/k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default;k8s:io.cilium.k8s.policy.cluster=default;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=default;k8s:run=fix-2604;/172.18.0.3" subsys=kvstorebackend
time="2024-10-31T15:44:16.003729803Z" level=warning msg="Releasing now unused key that was re-recreated" id=5521 key="[k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=default k8s:run=fix-2604]" subsys=allocator
time="2024-10-31T15:44:16.003761095Z" level=info msg="Released last local use of key, invoking global release" key="[k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=default k8s:run=fix-2604]" subsys=kvstorebackend
```

will push tomorrow morning!

**Comment by odinuge** [comment]
Thanks for looking at this @giorio94! Pushed a new version now.

Been running in a loop locally and seems to work as expected!

Running locally I see some of these (with a tiny kvstore-sync value);
```
$ kubectl logs -n kube-system -l k8s-app=cilium  -f |grep "Re-created" -A 2 -B 2
time="2024-11-01T16:25:24.806888127Z" level=info msg="Released last local use of key, invoking global release" key="[k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=default k8s:run=fix-101]" subsys=kvstorebackend
time="2024-11-01T16:25:24.925191043Z" level=info msg="Removed endpoint" ciliumEndpointName=default/fix-101 containerID=d42039ca5d containerInterface= datapathPolicyRevision=3 desiredPolicyRevision=3 endpointID=127 identity=17055 ipv4=10.244.1.118 ipv6= k8sPodName=default/fix-101 subsys=endpoint
time="2024-11-01T16:25:25.17641821Z" level=warning msg="Re-created missing slave key" key="cilium/state/identities/v1/value/k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default;k8s:io.cilium.k8s.policy.cluster=default;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=default;k8s:run=fix-101;/172.18.0.3" subsys=kvstorebackend
time="2024-11-01T16:25:25.176465627Z" level=warning msg="Releasing now unused key that was re-recreated" id=17055 key="[k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=default k8s:run=fix-101]" subsys=allocator
time="2024-11-01T16:25:25.17650171Z" level=info msg="Released last local use of key, invoking global release" key="[k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=default k8s:run=fix-101]" subsys=kvstorebackend
```

so it all seems to work as intended; and after all pods are gone, all the "slave keys" are released correctly and we have no leaks.

File: pkg/kvstore/allocator/allocator.go (hunk 6 above)
Comment (youngnick) [reply pkg/kvstore/allocator/allocator.go]: I think that in this case, `identity` and `node reference` are probably the _most_ correct, if a bit long.

File: pkg/allocator/allocator.go [hunk 10]
```diff
@@ -952,21 +952,60 @@ func (a *Allocator) DeleteAllKeys() {
...
+	}
+	err := a.backend.UpdateKey(contextWithTimeout, id, key, false)
+	if err != nil {
+		log.WithError(err).WithFields(logrus.Fields{
+			fieldKey: key,
+			fieldID:  id,
+		}).Warning("Error updating key")
+	}
+
+	if newId := a.localKeys.lookupKey(encodedKey); newId != idpool.NoID {
```
Comment (giorio94) [inline pkg/allocator/allocator.go:987]: Nit. I'd suggest adding a comment explaining why this check is performed again, just to prevent confusion in the future. Especially to clarify why this prevents the possibilities of race conditions, as it is not immediately obvious.

File: pkg/allocator/allocator.go [hunk 11]
```diff
@@ -952,21 +952,60 @@ func (a *Allocator) DeleteAllKeys() {
...
+		return
+	}
+
+	a.slaveKeysMutex.Lock()
+	defer a.slaveKeysMutex.Unlock()
+
+	if newId := a.localKeys.lookupKey(encodedKey); newId == idpool.NoID {
```
Comment (giorio94) [inline pkg/allocator/allocator.go:998]: Same here about adding a small comment to clarify the purpose of this logic.

File: pkg/allocator/allocator.go [hunk 12]
```diff
@@ -952,21 +952,60 @@ func (a *Allocator) DeleteAllKeys() {
...
+
+func (a *Allocator) syncLocalKey(ctx context.Context, id idpool.ID, key AllocatorKey) {
+	contextWithTimeout, cancel := context.WithTimeout(ctx, backendOpTimeout)
+	defer cancel()
+
+	encodedKey := key.GetKey()
+	if newId := a.localKeys.lookupKey(encodedKey); newId != id {
+		return
+	}
+	err := a.backend.UpdateKey(contextWithTimeout, id, key, false)
```
Comment (giorio94) [inline pkg/allocator/allocator.go]: I wonder whether it could make sense to keep the plain `ctx` here, to not modify the current behavior. I see the reasons for adding a timeout, but maybe that's better suited for a follow-up which doesn't get backported to stable branches. WDYT?

**Review by giorio94 — APPROVED** [review]
Thanks, looks great to me :rocket: Just a couple of nits inline.

File: pkg/allocator/allocator.go (hunk 12 above)
Comment (odinuge) [reply pkg/allocator/allocator.go]: I think my main concern is grabbing the `slaveKeyMutex` without a timeout seems a bit scary, but if you think its fine without we can probably skip it.

Or do you want no timeout here and only a timeout for the `release`?

Comment (giorio94) [reply pkg/allocator/allocator.go]: Yeah, I was thinking about having the timeout only for release, given that it is grabbing a lock. But I'm also totally fine with the current approach.

Comment (odinuge) [reply pkg/allocator/allocator.go]: Sounds good. I only added it to the `Release` now! Also added some extra comments

**Review by giorio94 — APPROVED** [review]
Thanks!

File: pkg/kvstore/allocator/allocator.go (hunk 6 above)
Comment (giorio94) [reply pkg/kvstore/allocator/allocator.go]: Marking as resolved, given that this part has been dropped in the latest version.

Comment (odinuge) [reply pkg/kvstore/allocator/allocator.go]: Thanks.

Lets follow up on the naming convention here in a follow up PR! :)

**Review by youngnick — APPROVED** [review]
