### PR TITLE
test: Fix pod cleanup after various tests

### LINKED ISSUE #18447: CI: Any test: terminating containers are not deleted after timeout
### Test Name

```shell
K8sUpdates Tests upgrade and downgrade from a Cilium stable image to master
```

### Failure Output

```shell
terminating containers are not deleted after timeout
```

### Stack Trace

```shell
/home/jenkins/workspace/Cilium-PR-K8s-1.22-kernel-4.19/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:465
terminating containers are not deleted after timeout
Expected
    <*errors.errorString | 0xc00024a0b0>: {
        s: "Pods are still not deleted after a timeout: 4m0s timeout expired",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-K8s-1.22-kernel-4.19/src/github.com/cilium/cilium/test/k8sT/Updates.go:79
```

### Standard Output

```shell
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Cilium pods: []
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
Pod   Ingress   Egress
```

### Standard Error

```shell
21:03:16 STEP: Running BeforeAll block for EntireTestsuite K8sUpdates
21:03:16 STEP: Ensuring the namespace kube-system exists
21:03:16 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs")
21:03:16 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs") => <nil>
21:03:16 STEP: Deleting pods [k8s1-client,k8s2-client] in namespace default
21:03:16 STEP: Waiting for 2 deletes to return (k8s1-client,k8s2-client)
21:03:16 STEP: Deleting cep [k8s1-client,k8s2-client] in namespace default
21:03:16 STEP: Waiting for 2 deletes to return (k8s1-client,k8s2-client)
21:03:26 STEP: Unable to delete pods k8s2-client with 'kubectl -n default delete pods k8s2-client': Exitcode: -1 
Err: signal: killed
Stdout:
 	 pod "k8s2-client" deleted
	 
Stderr:
 	 

21:03:26 STEP: Unable to delete pods k8s1-client with 'kubectl -n default delete pods k8s1-client': Exitcode: -1 
Err: signal: killed
Stdout:
 	 pod "k8s1-client" deleted
	 
Stderr:
 	 

21:07:26 STEP: Waiting for pods to be terminated
FAIL: terminating containers are not deleted after timeout
Expected
    <*errors.errorString | 0xc00024a0b0>: {
        s: "Pods are still not deleted after a timeout: 4m0s timeout expired",
    }
to be nil
21:11:26 STEP: Running JustAfterEach block for EntireTestsuite K8sUpdates
===================== TEST FAILED =====================
21:11:27 STEP: Running AfterFailed block for EntireTestsuite K8sUpdates
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE           NAME                           READY   STATUS        RESTARTS   AGE     IP              NODE   NOMINATED NODE   READINESS GATES
	 cilium-monitoring   grafana-5747bcc8f9-7llnk       1/1     Running       0          41m     10.0.0.203      k8s1   <none>           <none>
	 cilium-monitoring   prometheus-655fb888d7-z9g9l    1/1     Running       0          41m     10.0.0.114      k8s1   <none>           <none>
	 default             k8s1-client                    0/1     Terminating   0          8m52s   10.0.0.72       k8s1   <none>           <none>
	 default             k8s2-client                    0/1     Terminating   0          8m52s   10.0.1.191      k8s2   <none>           <none>
	 kube-system         coredns-69b675786c-6hbf7       1/1     Running       0          9m8s    10.0.0.3        k8s1   <none>           <none>
	 kube-system         etcd-k8s1                      1/1     Running       0          44m     192.168.56.11   k8s1   <none>           <none>
	 kube-system         kube-apiserver-k8s1            1/1     Running       0          44m     192.168.56.11   k8s1   <none>           <none>
	 kube-system         kube-controller-manager-k8s1   1/1     Running       0          44m     192.168.56.11   k8s1   <none>           <none>
	 kube-system         kube-proxy-8dkk6               1/1     Running       0          44m     192.168.56.11   k8s1   <none>           <none>
	 kube-system         kube-proxy-pkvz6               1/1     Running       0          42m     192.168.56.12   k8s2   <none>           <none>
	 kube-system         kube-scheduler-k8s1            1/1     Running       0          44m     192.168.56.11   k8s1   <none>           <none>
	 kube-system         log-gatherer-pv9h7             1/1     Running       0          41m     192.168.56.11   k8s1   <none>           <none>
	 kube-system         log-gatherer-wr4rf             1/1     Running       0          41m     192.168.56.12   k8s2   <none>           <none>
	 kube-system         registry-adder-4kg7l           1/1     Running       0          42m     192.168.56.12   k8s2   <none>           <none>
	 kube-system         registry-adder-ff8gh           1/1     Running       0          42m     192.168.56.11   k8s1   <none>           <none>
	 
Stderr:
 	 

Fetching command output from pods []
===================== Exiting AfterFailed =====================
21:11:30 STEP: Running AfterEach for block EntireTestsuite K8sUpdates
FAIL: terminating containers are not deleted after timeout
Expected
    <*errors.errorString | 0xc000c17af0>: {
        s: "Pods are still not deleted after a timeout: 4m0s timeout expired",
    }
to be nil
21:15:30 STEP: Running AfterEach for block EntireTestsuite

[[ATTACHMENT|0bb96475_K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master.zip]]
21:15:30 STEP: Running AfterAll block for EntireTestsuite K8sUpdates
21:15:30 STEP: Cleaning up Cilium components
FAIL: terminating containers are not deleted after timeout
Expected
    <*errors.errorString | 0xc000aff2d0>: {
        s: "Pods are still not deleted after a timeout: 4m0s timeout expired",
    }
to be nil
```

### Resources

- Jenkins URL: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.22-kernel-4.19/248/testReport/junit/Suite-k8s-1/22/K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master/
- ZIP file(s): 
[0bb96475_K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master.zip](https://github.com/cilium/cilium/files/7850280/0bb96475_K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master.zip)

### Anything else?

This may in theory happen at the beginning of any test, due to improper cleanup from the previous test. Basically what happens is:
* Deploy Cilium
* Deploy pods
* Remove Cilium
* Remove pods, which hangs in `Terminating` state because Cilium is no longer present, so CNI DEL fails.

### LINKED ISSUE #18566: CI: K8sUpdates Tests upgrade and downgrade from a Cilium stable image to master
### Test Name
```test-name
K8sUpdates Tests upgrade and downgrade from a Cilium stable image to master
```

### Failure Output
```failure-output
FAIL: terminating containers are not deleted after timeout
```

### Stacktrace
<details><summary>Click to show.</summary>

```stack-trace
/home/jenkins/workspace/Cilium-PR-K8s-1.23-kernel-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:465
terminating containers are not deleted after timeout
Expected
    <*errors.errorString | 0xc0015d4260>: {
        s: "Pods are still not deleted after a timeout: 4m0s timeout expired",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-K8s-1.23-kernel-net-next/src/github.com/cilium/cilium/test/k8sT/Updates.go:79
```
</details>

### Standard Output
<details><summary>Click to show.</summary>

```stack-output
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Cilium pods: []
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
Pod                           Ingress   Egress
grafana-6c7d4c9fd8-bcvcf                
prometheus-55777f54d9-qgl9n             
coredns-6874cd75d4-7hs5c                


```
</details>

### Standard Error
<details><summary>Click to show.</summary>

```stack-error
04:08:32 STEP: Running BeforeAll block for EntireTestsuite K8sUpdates
04:08:32 STEP: Ensuring the namespace kube-system exists
04:08:32 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs")
04:08:32 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs") => <nil>
04:08:32 STEP: Deleting cep [k8s1-client,k8s2-client] in namespace default
04:08:32 STEP: Waiting for 2 deletes to return (k8s1-client,k8s2-client)
04:08:32 STEP: Deleting pods [k8s1-client,k8s2-client] in namespace default
04:08:32 STEP: Waiting for 2 deletes to return (k8s1-client,k8s2-client)
04:08:42 STEP: Unable to delete pods k8s1-client with 'kubectl -n default delete pods k8s1-client': Exitcode: -1 
Err: signal: killed
Stdout:
 	 pod "k8s1-client" deleted
	 
Stderr:
 	 

04:08:42 STEP: Unable to delete pods k8s2-client with 'kubectl -n default delete pods k8s2-client': Exitcode: -1 
Err: signal: killed
Stdout:
 	 pod "k8s2-client" deleted
	 
Stderr:
 	 

04:12:42 STEP: Waiting for pods to be terminated
FAIL: terminating containers are not deleted after timeout
Expected
    <*errors.errorString | 0xc0015d4260>: {
        s: "Pods are still not deleted after a timeout: 4m0s timeout expired",
    }
to be nil
04:16:42 STEP: Running JustAfterEach block for EntireTestsuite K8sUpdates
===================== TEST FAILED =====================
04:16:43 STEP: Running AfterFailed block for EntireTestsuite K8sUpdates
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE           NAME                           READY   STATUS        RESTARTS   AGE     IP              NODE   NOMINATED NODE   READINESS GATES
	 cilium-monitoring   grafana-6c7d4c9fd8-bcvcf       1/1     Running       0          67m     10.0.0.104      k8s1   <none>           <none>
	 cilium-monitoring   prometheus-55777f54d9-qgl9n    1/1     Running       0          67m     10.0.0.251      k8s1   <none>           <none>
	 default             k8s1-client                    0/1     Terminating   0          8m52s   10.0.0.41       k8s1   <none>           <none>
	 default             k8s2-client                    0/1     Terminating   0          8m52s   10.0.1.53       k8s2   <none>           <none>
	 kube-system         coredns-6874cd75d4-7hs5c       1/1     Running       0          9m12s   10.0.0.219      k8s1   <none>           <none>
	 kube-system         etcd-k8s1                      1/1     Running       0          71m     192.168.56.11   k8s1   <none>           <none>
	 kube-system         kube-apiserver-k8s1            1/1     Running       0          71m     192.168.56.11   k8s1   <none>           <none>
	 kube-system         kube-controller-manager-k8s1   1/1     Running       0          71m     192.168.56.11   k8s1   <none>           <none>
	 kube-system         kube-scheduler-k8s1            1/1     Running       0          71m     192.168.56.11   k8s1   <none>           <none>
	 kube-system         log-gatherer-vmgrl             1/1     Running       0          67m     192.168.56.11   k8s1   <none>           <none>
	 kube-system         log-gatherer-wqphw             1/1     Running       0          67m     192.168.56.12   k8s2   <none>           <none>
	 kube-system         log-gatherer-xltg8             1/1     Running       0          67m     192.168.56.13   k8s3   <none>           <none>
	 kube-system         registry-adder-c4x9d           1/1     Running       0          68m     192.168.56.11   k8s1   <none>           <none>
	 kube-system         registry-adder-k58k7           1/1     Running       0          68m     192.168.56.13   k8s3   <none>           <none>
	 kube-system         registry-adder-vdqjp           1/1     Running       0          68m     192.168.56.12   k8s2   <none>           <none>
	 
Stderr:
 	 

Fetching command output from pods []
===================== Exiting AfterFailed =====================
04:16:46 STEP: Running AfterEach for block EntireTestsuite K8sUpdates
FAIL: terminating containers are not deleted after timeout
Expected
    <*errors.errorString | 0xc00007ec60>: {
        s: "Pods are still not deleted after a timeout: 4m0s timeout expired",
    }
to be nil
04:20:46 STEP: Running AfterEach for block EntireTestsuite

[[ATTACHMENT|1f648a50_K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master.zip]]
04:20:47 STEP: Running AfterAll block for EntireTestsuite K8sUpdates
04:20:47 STEP: Cleaning up Cilium components
FAIL: terminating containers are not deleted after timeout
Expected
    <*errors.errorString | 0xc00203ae20>: {
        s: "Pods are still not deleted after a timeout: 4m0s timeout expired",
    }
to be nil


```
</details>

ZIP Links: 
<details><summary>Click to show.</summary>

 https://jenkins.cilium.io/job/Cilium-PR-K8s-1.23-kernel-net-next//273/artifact/1f648a50_K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master.zip
  https://jenkins.cilium.io/job/Cilium-PR-K8s-1.23-kernel-net-next//273/artifact/test_results_Cilium-PR-K8s-1.23-kernel-net-next_273_BDD-Test-PR.zip
 
</details>

Jenkins URL: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.23-kernel-net-next/273/

If this is a duplicate of an existing flake, comment 'Duplicate of #\<issue-number>' and close this issue.

### PR DESCRIPTION
**Pull request by joestringer**
See individual commits for more details.

According to the [Cilium Ginkgo e2e test docs](https://docs.cilium.io/en/latest/contributing/testing/e2e/#example-test-layout), All `AfterEach` statements are executed before all `AfterAll` statements.

Previously, some of this code was assuming that `AfterAll` inside a context would run first (to delete pods) and then the `AfterEach` would run outside the context (to wait for the pods to terminate), then `AfterAll` outside the context to finally clean up the Cilium pods. The result was that in issue #18447, the next test to run could hit a race condition where pods were deleted but did not fully terminate before Cilium was removed. Cilium ends up getting deleted before all the pods, which means that there is no longer any way to execute the `CNI DEL` operation for those pods, so they get stuck in `Terminating` state.

Other parts of the code seemed to just omit the check for whether the pods were correctly terminated or not.

Fix these isseus by moving checks that the test pods are fully terminated into the statements where the pods are deleted.

Fixes: 412e299df74f ("test: Move LRP tests to a separate suite")
Fixes: #18447
Fixes: #18566

Note, I initially marked this for backport to v1.10 based on the first LRP test refactor commit, but left it like this since it seems like it should make the testsuite a bit more robust in general. I don't know if each of the changes will successfully backport to v1.10 or not. If not, we can maybe just drop those changes from the commit. Or we could just decide to avoid backporting the PR to v1.10 altogether.

### CODE REVIEW

**Comment by joestringer** [comment]
:joy: of course this PR hits the exact same problem, but from a different test:

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.22-kernel-4.19/251/testReport/junit/Suite-k8s-1/22/K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master/
```
16:20:27  K8sDatapathConfig
16:20:27  /home/jenkins/workspace/Cilium-PR-K8s-1.22-kernel-4.19/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:473
16:20:27    Iptables
16:20:27    /home/jenkins/workspace/Cilium-PR-K8s-1.22-kernel-4.19/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:473
16:20:27      Skip conntrack for pod traffic
16:20:27      /home/jenkins/workspace/Cilium-PR-K8s-1.22-kernel-4.19/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:527
```

Am I approaching this the wrong way? Should we be making sure all of the tests clean up after themselves properly or should we just make sure that the first test in each test group gets the environment back into a good state?

**Review by nbusseneau — APPROVED** [review]
Well spotted!

**Comment by nbusseneau** [comment]
> Am I approaching this the wrong way? Should we be making sure all of the tests clean up after themselves properly or should we just make sure that the first test in each test group gets the environment back into a good state?

(Thanks GH for not refreshing the PR comments when I'm reviewing)

To be honest I kinda assumed that every test was already supposed to clean up after itself, unless a test suite is specifically designed with environment being kept around for several tests in a row (in which case the suite should clean up). So I was convinced your approach would be right...

**Comment by joestringer** [comment]
> To be honest I kinda assumed that every test was already supposed to clean up after itself, unless a test suite is specifically designed with environment being kept around for several tests in a row (in which case the suite should clean up). So I was convinced your approach would be right...

I think this is basically a decision we have to make :-) Note that this approach can be right, but the same class of bug is present elsewhere in the testsuite. The failure that happened here is not the exact same test or conditions as the one I reported in #18447, since the previous test was in `K8sDatapathConfig`, not `K8sLRPTests`.

The likelihood of this failure is based on (1) removing and redeploying Cilium, (2) race conditions between deleting app pods and starting the next test, and (3) how many different test files there are (because if a bug like this is caused by incorrect ordering between `AfterEach()` at the top level of the file and `AfterAll()` inside a context, then the bug only triggers wherever the `AfterEach()` happens at the wrong time, so based on the specific files and the probability of running a particular file after a test that doesn't clean up after itself correctly.

Maybe we just need to apply the same fix to K8sDatapathConfig and then we're done. I guess I'll just look over the other test files and look for a similar pattern.

File: test/helpers/manifest.go [hunk 1]
```diff
@@ -280,6 +280,8 @@ func (m *DeploymentManager) DeleteAll() {
 // DeployCilium()
 func (m *DeploymentManager) DeleteCilium() {
 	if m.ciliumDeployed {
+		/* Ensure any Cilium-managed pods are terminated first */
```
Comment (gandro) [inline test/helpers/manifest.go]: tiny nit:
```suggestion
		// Ensure any Cilium-managed pods are terminated first
```

**Review by gandro — APPROVED** [review]
Thanks a ton for this!

**Comment by nbusseneau** [comment]
GitHub shenanigans -- CI image builds did not trigger. Closing and re-opening to force retrigger all actions.

**Review by aditighag — APPROVED** [review]
Good find! Thanks!

**Review by brb — APPROVED** [review]
Nice find and thanks for the fix!

**Review by nbusseneau — APPROVED** [review]
Changes LGTM.

**Comment by joestringer** [comment]
Hit the same sort of problem again in `K8sUpdates`: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.22-kernel-4.19/313/testReport/Suite-k8s-1/22/K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master/

The reason here is that in commit c18cfc874620163769f0f66863b1c15962d25e1f , we tried to re-deploy DNS pods after we reconfigure endpointRoutes mode in Cilium, however depending on a race condition in the testsuite (whether Cilium actually shuts down first or the DNS pods do), we may end up waiting forever for the coredns pods to terminate, but Cilium is no longer running and therefore can't handle the cleanup. 

I think the solution may be to just scale the number of DNS pods down to 0, then uninstall Cilium, then scale it up during the `K8sDatapathConfig` and `K8sCustomCalls` suites' `Afterall()` functions.

=====

Hit a different problem with K8sVerifier failing, but this also looks like a test leakage issue this time from `K8sBandwidthTest` leaving netperf client pods lying around after completing. I've filed #18540 to track that one.

Also hit https://github.com/cilium/cilium/pull/17182.

**Comment by joestringer** [comment]
/test-1.22-4.19

**Comment by joestringer** [comment]
I don't yet know whether this PR is making the first problem I mentioned in the above comment more likely, or it's already present and this PR doesn't affect it. I guess we'll get at least one more round of feedback on that. Then we can either try to deal with the first issue above in this PR or in a subsequent separate PR. Seems like it will likely need backporting the same as https://github.com/cilium/cilium/commit/c18cfc874620163769f0f66863b1c15962d25e1f, so that probably motivates doing a dedicated separate PR for that one to separate it from the rest of the changes in this PR.

**Comment by joestringer** [comment]
Seems like there's still potentially some issue specifically with this PR and the cleanup *after* K8sVerifier. I'll investigate.

**Comment by joestringer** [comment]
Didn't yet figure out why the verifier test is failing on `Cilium-PR-K8s-1.22-kernel-4.19`, but I suspect it's because `K8sDatapathConfig` is not properly cleaning up after itself. Unfortunately the helpers in the tree aren't providing detail about which pods are still terminating, so I've just added an extra commit on top to improve the debug output when the current failure occurs. Will kick off the same test again to try to get more info.

**Comment by joestringer** [comment]
/test-1.22-4.19

**Comment by joestringer** [comment]
/test-1.22-4.19

**Comment by joestringer** [comment]
[k8s-1.16-kernel-4.9](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-kernel-4.9/630/) hit #18060, which blocked the whole run.

[test-runtime](https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/1085/) Hit two peculiar problems:

(1) [RuntimePolicies TestsEgressToHost Tests egress with CIDR+L4 policy to external https service](https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/1085/testReport/junit/(root)/Suite-runtime/RuntimePolicies_TestsEgressToHost_Tests_egress_with_CIDR_L4_policy_to_external_https_service/) failed to contact 1.1.1.1. Looking into the `monitor.log` file in the test artifacts, Cilium hands the echo requests to the stack, and the stack has a default route pointing out of the node. So Cilium seems to be doing the right thing, it just doesn't receive any response from Cloudflare. This PR doesn't change any related code, and I see no other reports in the issues of similar behaviour. Infra issue? :shrug: 

(2) [RuntimePrivilegedUnitTests Run Tests](https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/1085/testReport/junit/(root)/Suite-runtime/RuntimePrivilegedUnitTests_Run_Tests/)  hit this:

```
	 flag provided but not defined: -check.vv
	 Usage of /tmp/go-build534159421/b001/prog_test.test:
	   -test.bench regexp
	     	run only benchmarks matching regexp
	   -test.benchmem
	     	print memory allocations for benchmarks
	   -test.benchtime d
	     	run each benchmark for duration d (default 1s)
	   -test.blockprofile file
	     	write a goroutine blocking profile to file
	   -test.blockprofilerate rate
	     	set blocking profile rate (see runtime.SetBlockProfileRate) (default 1)
	   -test.count n
	     	run tests and benchmarks n times (default 1)
	   -test.coverprofile file
	     	write a coverage profile to file
	   -test.cpu list
	     	comma-separated list of cpu counts to run each test with
	   -test.cpuprofile file
	     	write a cpu profile to file
	   -test.failfast
	     	do not start new tests after the first test failure
	   -test.list regexp
	     	list tests, examples, and benchmarks matching regexp then exit
	   -test.memprofile file
	     	write an allocation profile to file
	   -test.memprofilerate rate
	     	set memory allocation profiling rate (see runtime.MemProfileRate)
	   -test.mutexprofile string
	     	write a mutex contention profile to the named file after execution
	   -test.mutexprofilefraction int
	     	if >= 0, calls runtime.SetMutexProfileFraction() (default 1)
	   -test.outputdir dir
	     	write profiles to dir
	   -test.paniconexit0
	     	panic on call to os.Exit(0)
	   -test.parallel n
	     	run at most n tests in parallel (default 4)
	   -test.run regexp
	     	run only tests and examples matching regexp
	   -test.short
	     	run smaller test suite to save time
	   -test.shuffle string
	     	randomize the execution order of tests and benchmarks (default "off")
	   -test.testlogfile file
	     	write test action log to file (for use only by cmd/go)
	   -test.timeout d
	     	panic test binary after duration d (default 0, timeout disabled)
	   -test.trace file
	     	write an execution trace to file
	   -test.v
	     	verbose: print additional output
	 FAIL	github.com/cilium/cilium/test/test_results/RuntimePolicies_TestsEgressToHost_Tests_egress_with_CIDR+L4_policy_to_external_https_service/run/cilium/bpf/tests/prog_test	0.016s
	 FAIL
	 make: Leaving directory '/home/vagrant/go/src/github.com/cilium/cilium'
	 
Stderr:
 	 make: *** [Makefile:138: tests-privileged] Error 1
```

I don't understand why this would occur on this PR and not elsewhere ([master seems green](https://jenkins.cilium.io/job/cilium-master-runtime-kernel-net-next/)). The Makefile line is the line where we iterate through all of the test packages where there are privileged tests. The `check.vv` parameter is a flag to gocheck, so plausibly if we removed gocheck from some test recently then this could explain it, but I see no such evidence in git logs.  It's also odd that the directory for running these unit tests is under the directory for the previous failing test, could the previous failing test somehow have inadvertently triggered this failure by triggering the privileged tests from the wrong directory? :shrug: 

All other tests passed, despite previous failures :thinking: . I guess I'll just re-trigger CI again to go fishing for more failures.

**Comment by joestringer** [comment]
:shrug: Hit a bug earlier on, introduced debugging code, now the whole testsuite passes:
https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/7414/
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-kernel-4.9/633/
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-5.4/321/
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.22-kernel-4.19/340/
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.23-kernel-net-next/270/
https://jenkins.cilium.io/job/Cilium-PR-Runtime-net-next/1088/

I don't think the bug I observed ealier has anything specifically to do with this PR, but I'd like to catch it in the wild before merging this PR if I can. I'll give it another one or two shots and if I can't repro then I'll just mark this ready for another round of review / merging.

**Comment by joestringer** [comment]
[net-next job](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.23-kernel-net-next/272/): Seems to have raced against the build/tag of the images so the whole run failed:

```
18:07:08  + curl --silent -f -lSL https://quay.io/api/v1/repository/cilium/cilium-ci/tag/e8e6c17a30f9932d7f6d96c99f4f7e28448ea456/images
18:07:08  curl: (22) The requested URL returned error: 404 
```

[test-1.22-4.19 job](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.22-kernel-4.19/342/) seems to have failed in a beforeall in one of the K8sServicesTests where Cilium was stuck in terminating state:

[First failed test](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.22-kernel-4.19/342/testReport/junit/Suite-k8s-1/22/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan_Tests_NodePort_with_Maglev_Tests_NodePort/). Pulling the sysdump, we can't get logs from the "terminating" container because of a lack of route available to the k8s2 node..?

```
Error from server: Get "https://192.168.56.12:10250/containerLogs/kube-system/cilium-hzhqt/cilium-agent?timestamps=true": dial tcp 192.168.56.12:10250: connect: no route to host
```

Previous test was `K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with vxlan with L7 policy Tests NodePort with L7 Policy`, which seemed to pass successfully without anything unusual going on. I've filed #18604 in case this shows up again, but right now it just seems like weird spontaneous loss of k8s2 VM in CI environment.

**Comment by joestringer** [comment]
/test-1.22-4.19

**Comment by joestringer** [comment]
test-1.23-net-next

**Comment by joestringer** [comment]
/test-1.23-net-next

**Comment by joestringer** [comment]
I picked out a few problems from the most recent [two](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.22-kernel-4.19/374/) [failures](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.23-kernel-net-next/301/flowGraphTable/):

* K8sBandwidth, K8sCustomCalls were skipping the Context rather than Describe, so some of the test prep code could run, which seemed unnecessary
* K8sCustomCalls test could fail to completely clean up DNS after itself
* The debug code I added earlier in this patch to find out which pods aren't cleaned up would just print timestamps instead of pod names.

The latest push of the PR addresses the above with the following diff on top of the prior version (Mostly addressed by the new patches on the top of the branch):

```
diff --git a/test/helpers/kubectl.go b/test/helpers/kubectl.go
index e94be73c6527..549a12ad4346 100644
--- a/test/helpers/kubectl.go
+++ b/test/helpers/kubectl.go
@@ -310,6 +310,10 @@ type Kubectl struct {
 	// ciliumOptions is a cache of the most recent configuration options
 	// used to install Cilium via CiliumInstall().
 	ciliumOptions map[string]string
+
+	// nDNSReplicas is the number of replicas for DNS pods in the cluster.
+	// Stored via kub.ScaleDownDNS(), used by kub.ScaleUpDNS().
+	nDNSReplicas int
 }
 
 // CreateKubectl initializes a Kubectl helper with the provided vmName and log
@@ -2047,11 +2051,62 @@ iteratePods:
 	}
 }
 
-// RedeployDNS deletes the kube-dns pods and does not wait for the deletion
-// to complete. Useful to ensure that the pods are recreated after datapath
-// configuration changes.
-func (kub *Kubectl) RedeployDNS() *CmdRes {
-	return kub.DeleteResource("pod", "-n "+KubeSystemNamespace+" -l "+kubeDNSLabel)
+func (kub *Kubectl) setDNSReplicas(nReplicas int) *CmdRes {
+	res := kub.ExecShort(fmt.Sprintf("%s get deploy -n %s -l %s -o jsonpath='{.items[*].metadata.name}'", KubectlCmd, KubeSystemNamespace, kubeDNSLabel))
+	if !res.WasSuccessful() {
+		return res
+	}
+
+	// kubectl -n kube-system patch deploy coredns --patch '{"spec": { "replicas":1}}'
+	name := res.Stdout()
+	spec := fmt.Sprintf("{\"spec\": { \"replicas\":%d}}", nReplicas)
+	return kub.ExecShort(fmt.Sprintf("%s patch deploy -n %s %s '%s'", KubectlCmd, KubeSystemNamespace, name, spec))
+}
+
+// ScaleDownDNS reduces the number of pods in the cluster performing kube-dns
+// duties down to zero. May be reverted by calling ScaleUpDNS().
+func (kub *Kubectl) ScaleDownDNS() *CmdRes {
+	cmd := fmt.Sprintf("%s get deploy -n %s -l %s -o jsonpath='{.items[*].status.replicas}'", KubectlCmd, KubeSystemNamespace, kubeDNSLabel)
+	res := kub.ExecShort(cmd)
+	if !res.WasSuccessful() {
+		ginkgoext.Failf("Unable to retrieve DNS pods to scale down, command '%s': %s", res.GetCmd(), res.OutputPrettyPrint())
+		return res
+	}
+
+	n, err := strconv.Atoi(res.Stdout())
+	if err != nil {
+		ginkgoext.Failf("Failed to retrieve DNS replicas via '%s': %s", res.GetCmd(), err)
+		res.success = false
+		res.err = err
+		return res
+	}
+	kub.nDNSReplicas = n
+
+	res = kub.setDNSReplicas(0)
+	if !res.WasSuccessful() {
+		ginkgoext.Failf("Unable to scale down DNS pods, command '%s': %s", res.GetCmd(), res.OutputPrettyPrint())
+	}
+	return res
+}
+
+// ScaleUpDNS restores the number of replicas for kube-dns to the number
+// prior to calling ScaleDownDNS(). Must be called after ScaleDownDNS().
+func (kub *Kubectl) ScaleUpDNS() *CmdRes {
+	res := kub.setDNSReplicas(kub.nDNSReplicas)
+	if !res.WasSuccessful() {
+		ginkgoext.Failf("Unable to scale down DNS pods, command '%s': %s", res.GetCmd(), res.OutputPrettyPrint())
+	}
+	return res
+}
+
+// redeployDNS deletes the kube-dns pods and does not wait for the deletion
+// to complete.
+func (kub *Kubectl) redeployDNS() *CmdRes {
+	if res := kub.ScaleDownDNS(); !res.WasSuccessful() {
+		return res
+	}
+
+	return kub.ScaleUpDNS()
 }
 
 // RedeployKubernetesDnsIfNecessary validates if the Kubernetes DNS is
@@ -2070,7 +2125,7 @@ func (kub *Kubectl) RedeployKubernetesDnsIfNecessary(force bool) {
 	}
 
 	ginkgoext.By("Restarting Kubernetes DNS (-l %s)", kubeDNSLabel)
-	res := kub.RedeployDNS()
+	res := kub.redeployDNS()
 	if !res.WasSuccessful() {
 		ginkgoext.Failf("Unable to delete DNS pods: %s", res.OutputPrettyPrint())
 	}
@@ -2208,7 +2263,7 @@ func (kub *Kubectl) WaitTerminatingPodsInNsWithFilter(ns, filter string, timeout
 			where = "-n " + where
 		}
 		res := kub.ExecShort(fmt.Sprintf(
-			"%s get pods %s %s -o jsonpath='{.items[*].metadata.deletionTimestamp}'",
+			"%s get pods %s %s -o jsonpath='{.items[?(.metadata.deletionTimestamp!=\"\")].metadata.name}'",
 			KubectlCmd, filter, where))
 		if !res.WasSuccessful() {
 			innerErr = fmt.Errorf("Failed to connect to apiserver: %w", res.GetError())
@@ -2224,7 +2279,7 @@ func (kub *Kubectl) WaitTerminatingPodsInNsWithFilter(ns, filter string, timeout
 		nTerminating := len(podsTerminating)
 		kub.Logger().WithField("Terminating pods", nTerminating).Info("List of pods terminating")
 		if nTerminating > 0 {
-			innerErr = fmt.Errorf("Pods are still terminating:\n%s", podsTerminating)
+			innerErr = fmt.Errorf("Pods are still terminating: %s", podsTerminating)
 			return false
 		}
 		return true
diff --git a/test/k8sT/Bandwidth.go b/test/k8sT/Bandwidth.go
index 57ea882dafea..8ef8a02492ff 100644
--- a/test/k8sT/Bandwidth.go
+++ b/test/k8sT/Bandwidth.go
@@ -12,7 +12,7 @@ import (
 	"github.com/cilium/cilium/test/helpers"
 )
 
-var _ = Describe("K8sBandwidthTest", func() {
+var _ = SkipDescribeIf(helpers.DoesNotRunOnNetNextKernel, "K8sBandwidthTest", func() {
 	var (
 		kubectl        *helpers.Kubectl
 		ciliumFilename string
@@ -39,7 +39,7 @@ var _ = Describe("K8sBandwidthTest", func() {
 		kubectl.CloseSSHClient()
 	})
 
-	SkipContextIf(helpers.DoesNotRunOnNetNextKernel, "Checks Bandwidth Rate-Limiting", func() {
+	Context("Checks Bandwidth Rate-Limiting", func() {
 		const (
 			testDS10       = "run=netperf-10"
 			testDS25       = "run=netperf-25"
diff --git a/test/k8sT/CustomCalls.go b/test/k8sT/CustomCalls.go
index bc3530a74651..4f48ea942160 100644
--- a/test/k8sT/CustomCalls.go
+++ b/test/k8sT/CustomCalls.go
@@ -17,7 +17,22 @@ import (
 	"github.com/cilium/cilium/test/helpers"
 )
 
-var _ = Describe("K8sCustomCalls", func() {
+var _ = SkipDescribeIf(func() bool {
+	// Believe it or not, bpftool internally attempts to retrieve
+	// map info before updating a map, but BPF_OBJ_GET_INFO_BY_FD
+	// is not supported on kernel 4.9 (it was introduced in Linux
+	// 4.13). Skip on 4.9 kernels.
+	//
+	// This leaves us with 4.19 and net-next. Coverage should be
+	// identical on the two versions, so just run on net-next.
+	//
+	// Also skip on GKE because we do not have the source of the
+	// custom program available on a node, for the compiler pod to
+	// pick up (although technically, skipping 4.19 kernels already
+	// skips GKE).
+	return helpers.DoesNotRunOnNetNextKernel() ||
+		helpers.RunsOnGKE()
+}, "K8sCustomCalls", func() {
 
 	var (
 		kubectl *helpers.Kubectl
@@ -54,22 +69,7 @@ var _ = Describe("K8sCustomCalls", func() {
 		kubectl.ValidateNoErrorsInLogs(duration)
 	})
 
-	SkipContextIf(func() bool {
-		// Believe it or not, bpftool internally attempts to retrieve
-		// map info before updating a map, but BPF_OBJ_GET_INFO_BY_FD
-		// is not supported on kernel 4.9 (it was introduced in Linux
-		// 4.13). Skip on 4.9 kernels.
-		//
-		// This leaves us with 4.19 and net-next. Coverage should be
-		// identical on the two versions, so just run on net-next.
-		//
-		// Also skip on GKE because we do not have the source of the
-		// custom program available on a node, for the compiler pod to
-		// pick up (although technically, skipping 4.19 kernels already
-		// skips GKE).
-		return helpers.DoesNotRunOnNetNextKernel() ||
-			helpers.RunsOnGKE()
-	}, "Basic test with byte-counter", func() {
+	Context("Basic test with byte-counter", func() {
 
 		var (
 			yaml string
@@ -101,9 +101,11 @@ var _ = Describe("K8sCustomCalls", func() {
 		})
 
 		AfterAll(func() {
-			deploymentManager.DeleteCilium()
 			deploymentManager.DeleteAll()
-			kubectl.RedeployDNS()
+			kubectl.ScaleDownDNS()
+			ExpectAllPodsTerminated(kubectl)
+			deploymentManager.DeleteCilium()
+			kubectl.ScaleUpDNS()
 		})
 
 		installPods := func() {
diff --git a/test/k8sT/DatapathConfiguration.go b/test/k8sT/DatapathConfiguration.go
index 1d537103f560..d01c609d66db 100644
--- a/test/k8sT/DatapathConfiguration.go
+++ b/test/k8sT/DatapathConfiguration.go
@@ -44,8 +44,10 @@ var _ = Describe("K8sDatapathConfig", func() {
 	})
 
 	AfterAll(func() {
+		kubectl.ScaleDownDNS()
+		ExpectAllPodsTerminated(kubectl)
 		deploymentManager.DeleteCilium()
-		kubectl.RedeployDNS()
+		kubectl.ScaleUpDNS()
 		kubectl.CloseSSHClient()
 	})
 
````

**Comment by joestringer** [comment]
/test-1.22-4.19

**Comment by joestringer** [comment]
/test-1.23-net-next

**Comment by joestringer** [comment]
/test-1.22-4.19

**Comment by joestringer** [comment]
/test-1.22-4.19

**Comment by joestringer** [comment]
/test-1.23-net-next

**Comment by joestringer** [comment]
/test-1.22-4.19

**Comment by joestringer** [comment]
/test-1.23-net-next

**Comment by nbusseneau** [comment]
/test-1.22-4.19

**Comment by nbusseneau** [comment]
/test-1.23-net-next

**Comment by nbusseneau** [comment]
4.19 hit #18634 again => maybe we are introducing this in the PR?

**Comment by joestringer** [comment]
> 4.19 hit #18634 again => maybe we are introducing this in the PR?

The relevant code changes would be that this PR is removing the "AfterEach" for the overall services test (because of bad ordering of cleanup events), then this PR adds an "AfterAll" in the context where this test fails. The test that fails is the second test in the group. 

I can try changing that particular cleanup change for the graceful termination tests to use AfterEach (inside the context, so it runs first).

Looks like this failed in about 2/11 runs above.

**Comment by joestringer** [comment]
I'm hoping that commit https://github.com/cilium/cilium/commit/d4739ad757d8d84dd65302e0e85e985b51198d69 will fix the above issue.

**Review by aditighag — COMMENTED** [review]
Reviewed d4739ad757d8d84dd65302e0e85e985b51198d69. The change looks correct to me.

Thanks! 🙏 

While at it, we should remove this duplicate code that deploys the yaml - https://github.com/cilium/cilium/blob/master/test/k8sT/Services.go#L1639-L1641. I can fix this in a separate PR if you don't want to do it in this PR. 

>The next commit will then shift the cleanup logic
out of a Describe level AfterEach and into the individual Contexts.

Can you confirm the commit? Might as well double check that too.

**Comment by joestringer** [comment]
> While at it, we should remove this duplicate code that deploys the yaml - https://github.com/cilium/cilium/blob/master/test/k8sT/Services.go#L1639-L1641. I can fix this in a separate PR if you don't want to do it in this PR.

Please do, I'm hoping that this PR is now in a good state to merge & stabilize the tree.

> Can you confirm the commit? Might as well double check that too. 

The commit is https://github.com/cilium/cilium/pull/18448/commits/30a6d9091d3c224a34bdea2a27e263a6f029020d . I can't confirm it in the commit message unfortunately because github will rewrite the commit shas. Hence I just rearranged the commits to be in order so that this statement would be correct for the next commit. (The only reason for these gymnastics is to prevent introducing the failure into the tree then removing it again, so I moved the commit earlier in the ordering in this branch).

**Comment by joestringer** [comment]
Travis hit pull ratelimit issue, ignoring (prior versions passed successfully and this PR is focused on ginkgo test code which isn't tested by Travis). Everything else passed, the PR has been reviewed, and this fixes a common CI flake on master. Merging.
