### PR TITLE
CountUniqueIPsecKeys function fixed.

### LINKED ISSUE #29181: IPSec key count for AES-CBC algorithm
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

`cilium encrypt status` command always return `Keys in use: 0` for the `AES-CBC Cipher Algorithm`.
cilium images: v1.12 - v1.15

### Cilium Version

cilium-cli: v0.15.7 compiled with go1.21.0

### Kernel Version

Linux 5.15.136-flatcar x86_64

### Kubernetes Version

EKS 1.23

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by viktor-kurchenko**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #issue-number

```release-note
Handle non-AEAD IPsec keys in `cilium encrypt status`.
```

### CODE REVIEW

File: pkg/common/ipsec/utils_test.go [hunk 1]
```diff
@@ -5,31 +5,44 @@ package ipsec
...
+			ICVLen: 64,
+		}
+	case "rfc4106(gcm(aes))":
+		state.Aead = &netlink.XfrmStateAlgo{
+			Name:   "rfc4106(gcm(aes))",
+			Key:    k,
+			ICVLen: 64,
+		}
+	default:
+		log.Fatalf("Unsupported algorithm: %s", algoName)
```
Comment (pchaigno) [inline pkg/common/ipsec/utils_test.go]: We should fail the test via the `testing` or `require` primitives in this case, not fatal via `log`.

File: pkg/common/ipsec/utils.go [hunk 2]
```diff
@@ -18,10 +18,12 @@ const (
...
 	keys := make(map[string]bool)
 	for _, s := range states {
-		if s.Aead == nil {
-			continue
+		if s.Aead != nil {
+			keys[string(s.Aead.Key)] = true
+		}
+		if s.Crypt != nil {
+			keys[string(s.Crypt.Key)] = true
 		}
```
Comment (pchaigno) [inline pkg/common/ipsec/utils.go:34]: Shoudn't we be handling the authentication key as well?

**Review by pchaigno — CHANGES_REQUESTED** [review]
Nice work!

File: pkg/common/ipsec/utils.go (hunk 2 above)
Comment (viktor-kurchenko) [reply pkg/common/ipsec/utils.go:34]: As I understood in case of CBC we have both:
```
Crypt name: cbc(aes), key: Q���3��90x��, str: {Name: cbc(aes), Key: 0x0151a41da39e3310d4f58b3930788dc4}
Auth name: hmac(sha512), key: �M�������MQ�s�������~M��8��1">�, str: {Name: hmac(sha512), Key: 0x8b4d92bf9396e7febb4d51e..., Truncate length: 256}
```
Do you mean that it should count unique pair of Crypt and Auth?

Comment (pchaigno) [reply pkg/common/ipsec/utils.go:34]: Yes. One way to achieve that would be to concatenate them with a separator before using that as the key in the set.

Comment (pchaigno) [reply pkg/common/ipsec/utils.go:34]: (It needs a comment if that's the way you achieve this given it won't be obvious what/why we're doing from reading the code.)

Comment (viktor-kurchenko) [reply pkg/common/ipsec/utils.go:34]: Gotcha, tnx! Do you think it might be possible to have `s.Auth != nil && s.Crypt == nil` (or vice versa)?

File: pkg/common/ipsec/utils_test.go (hunk 1 above)
Comment (viktor-kurchenko) [reply pkg/common/ipsec/utils_test.go]: Fixed.

File: pkg/common/ipsec/utils.go (hunk 2 above)
Comment (pchaigno) [reply pkg/common/ipsec/utils.go:34]: I don't know. The best solution might be to error on such cases to avoid reporting incorrect results.

Comment (viktor-kurchenko) [reply pkg/common/ipsec/utils.go:34]: Done.

File: pkg/common/ipsec/utils.go [hunk 3]
```diff
@@ -15,18 +17,24 @@ const (
...
 		if s.Aead != nil {
 			keys[string(s.Aead.Key)] = true
+			continue
 		}
-		if s.Crypt != nil {
-			keys[string(s.Crypt.Key)] = true
+		if s.Auth == nil && s.Crypt == nil {
+			continue
 		}
+		if (s.Auth != nil && s.Crypt == nil) || (s.Auth == nil && s.Crypt != nil) {
```
Comment (pchaigno) [inline pkg/common/ipsec/utils.go]: This can be simplified to:
```
// We don't support XFRM states with only one of auth or crypt set.
if s.Auth == nil || s.Crypt == nil {
```

File: pkg/common/ipsec/utils.go [hunk 4]
```diff
@@ -15,18 +17,24 @@ const (
...
+			return 0, fmt.Errorf("invalid XfrmState found [Auth != nil -> %t] [Crypt != nil -> %t]", s.Auth != nil, s.Crypt != nil)
```
Comment (pchaigno) [inline pkg/common/ipsec/utils.go]: This is a bit cryptic for an end-user. I think it would be good enough to say that "an unsupported key with only Auth or Crypt set has been found".

File: pkg/common/ipsec/utils.go [hunk 5]
```diff
@@ -15,18 +17,24 @@ const (
...
+		}
+		// if AES-CBC Cipher algorithm enabled both Auth and Crypt keys will be present and used to make a unique key
```
Comment (pchaigno) [inline pkg/common/ipsec/utils.go]: (This isn't specific to AES-CBC.)

I think it would be best to explain the intent here (why) rather than when it happens. So you could simply say that "we want to count the number of unique (Auth; Crypt) tuples".

**Review by pchaigno — COMMENTED** [review]
Minor comments around error message and readability.

**Review by chancez — APPROVED** [review]
I got pulled in via the metrics group but do not see any metrics changes. IPSEC isn't in my area of expertise so I'll defer to others.

File: pkg/common/ipsec/utils.go (hunk 5 above)
Comment (viktor-kurchenko) [reply pkg/common/ipsec/utils.go]: Fixed.

File: pkg/common/ipsec/utils.go (hunk 4 above)
Comment (viktor-kurchenko) [reply pkg/common/ipsec/utils.go]: Done, thanks!

File: pkg/common/ipsec/utils.go (hunk 3 above)
Comment (viktor-kurchenko) [reply pkg/common/ipsec/utils.go]: Simplified, thanks!

File: pkg/common/ipsec/utils.go [hunk 6]
```diff
@@ -15,16 +17,25 @@ const (
...
+			keys[string(s.Aead.Key)] = true
+			continue
+		}
+		if s.Auth == nil && s.Crypt == nil {
 			continue
 		}
-		keys[string(s.Aead.Key)] = true
+		// We don't support XFRM states with only one of auth or crypt set.
+		if s.Auth == nil || s.Crypt == nil {
+			return 0, fmt.Errorf("an unsupported key with only Auth or Crypt set has been found")
```
Comment (gentoo-root) [inline pkg/common/ipsec/utils.go]: Should we really error out when we find an invalid entry, or rather just skip in and log the error?

If the former, I guess, we should also error out on `s.Aead != nil && (s.Auth != nil || s.Crypt != nil)`. If we restructure the code as follows, we should catch all invalid cases (including 3 nils):

```
if (s.Aead != nil) {
    ...
    continue
}
if (s.Auth != nil && s.Crypt != nil) {
    ...
    continue
}
return 0, fmt.Errorf(...)
```

Comment (viktor-kurchenko) [reply pkg/common/ipsec/utils.go]: Yeah, looks like you are right `3 nils` is another invalid situation.

Comment (viktor-kurchenko) [reply pkg/common/ipsec/utils.go]: I've refactored `CountUniqueIPsecKeys` with your suggestion, thanks!

Regarding error, I've checked that it won't impact `cilium metrics list` if IPSec is not enabled.
I don't have a strong opinion here but I think error will make it more visible, isn't it?

**Comment by viktor-kurchenko** [comment]
> Could you add some description of what's being fixed to the commit message? `Fixes: #29181` would work best as the last line, after a proper title and a short description.

Done. I also squashed and renamed other commits (hope it looks better now).

File: pkg/common/ipsec/utils.go (hunk 6 above)
Comment (gentoo-root) [reply pkg/common/ipsec/utils.go]: On second thought, my suggestion is not completely correct, it still misses `s.Aead != nil && (s.Auth != nil || s.Crypt != nil)`. This one should work better and catch all invalid combinations (by explicitly allowing only valid ones):

```
if (s.Aead != nil && s.Auth == nil && s.Crypt == nil) {
    ...
    continue
}
if (s.Aead == nil && s.Auth != nil && s.Crypt != nil) {
    ...
    continue
}
return 0, fmt.Errorf(...)
```

> I think error will make it more visible, isn't it?

Yeah, let's keep the error as long as it doesn't break anything. Let's just make this text `"an unsupported key with only Auth or Crypt set has been found"` more generic, it could be other invalid combinations.

Comment (viktor-kurchenko) [reply pkg/common/ipsec/utils.go]: Fixed.

**Review by jschwinger233 — COMMENTED** [review]
I noted this PR causes regression for https://github.com/cilium/cilium/pull/27996. For instance, after running `ip x s a src 1.1.1.1 dst 1.1.1.2 proto esp spi 0x3 reqid 1 mode tunnel enc aes 0xf0e1d2c3b4a5f60708090a0b0c0d0e0f` on kind-worker, `cilium encrypt status` at kind-worker failed with "Error: Cannot count unique IPSec keys: an unsupported key with only Auth or Crypt set has been found".
Is this what we want? In some cases users would install xfrm states out of cilium's management, do we expect cilium CLI to continue working?

File: cilium-dbg/cmd/encrypt_status.go [hunk 7]
```diff
@@ -164,7 +164,10 @@ func dumpIPsecStatus() {
 	if err != nil {
 		Fatalf("Cannot get xfrm state: %s", err)
 	}
-	keys := ipsec.CountUniqueIPsecKeys(xfrmStates)
+	keys, err := ipsec.CountUniqueIPsecKeys(xfrmStates)
+	if err != nil {
+		Fatalf("Cannot count unique IPSec keys: %s", err)
```
Comment (gentoo-root) [inline cilium-dbg/cmd/encrypt_status.go]: Nit: the right spelling is "IPsec" with small "s" (also in other new messages).

File: pkg/common/ipsec/utils.go [hunk 8]
```diff
@@ -15,16 +17,22 @@ const (
...
+			continue
+		}
+		if s.Aead == nil && s.Auth != nil && s.Crypt != nil {
+			// we want to count the number of unique (Auth, Crypt) tuples
+			key := fmt.Sprintf("%s:%s", string(s.Auth.Key), string(s.Crypt.Key))
+			keys[key] = true
 			continue
 		}
-		keys[string(s.Aead.Key)] = true
+		return 0, fmt.Errorf("an unsupported XfrmStateAlgo combination has been found")
```
Comment (gentoo-root) [inline pkg/common/ipsec/utils.go]: > In some cases users would install xfrm states out of cilium's management, do we expect cilium CLI to continue working?

Looks like we better make this error non-fatal...

File: cilium-dbg/cmd/encrypt_status.go (hunk 7 above)
Comment (viktor-kurchenko) [reply cilium-dbg/cmd/encrypt_status.go]: Fixed.

File: pkg/common/ipsec/utils.go (hunk 8 above)
Comment (viktor-kurchenko) [reply pkg/common/ipsec/utils.go]: Fixed.

Comment (gentoo-root) [reply pkg/common/ipsec/utils.go]: I think we shouldn't even interrupt this loop when encountering this error, so that we count all valid keys. Otherwise we just return 0 if any custom state with an unsupported algorithm is installed.

Comment (viktor-kurchenko) [reply pkg/common/ipsec/utils.go]: Then I don't think it makes sense to return the error at all.
What do you think if I revert it to the initial function signature and just print to StdErr in the loop in case of an invalid combination?

Comment (gentoo-root) [reply pkg/common/ipsec/utils.go]: Yes, that's what I mean, let's print it right here.

Comment (viktor-kurchenko) [reply pkg/common/ipsec/utils.go]: Done.
Does it make sense to squash the commits for this PR? It looks pretty small.
CC: @pchaigno

Comment (gentoo-root) [reply pkg/common/ipsec/utils.go]: > Does it make sense to squash the commits for this PR?

Yes please.

File: pkg/common/ipsec/utils.go [hunk 9]
```diff
@@ -30,9 +31,9 @@ func CountUniqueIPsecKeys(states []netlink.XfrmState) (int, error) {
 			keys[key] = true
 			continue
 		}
-		return 0, fmt.Errorf("an unsupported XfrmStateAlgo combination has been found")
+		_, _ = fmt.Fprintf(os.Stderr, "an unsupported XfrmStateAlgo combination has been found\n")
```
Comment (gentoo-root) [inline pkg/common/ipsec/utils.go]: Nit: it seems that `_, _ =` is not really needed, at least all the other occurrences of Fprintf don't need it.

It's also a good idea to print it only once, because now it will output a line per an unsupported xfrm state.

File: pkg/common/ipsec/utils.go (hunk 8 above)
Comment (viktor-kurchenko) [reply pkg/common/ipsec/utils.go]: Done.

File: pkg/common/ipsec/utils.go (hunk 9 above)
Comment (viktor-kurchenko) [reply pkg/common/ipsec/utils.go]: Good catch about duplicated outputs, fixed.

Regarding `_, _ =`, it is usually a good practice to ignore errors explicitly (e.g.: my IDE complains about it) but its not required. Removed.

**Review by gentoo-root — APPROVED** [review]

File: pkg/common/ipsec/utils.go [hunk 10]
```diff
@@ -4,6 +4,9 @@
 package ipsec
```
Comment (pchaigno) [inline pkg/common/ipsec/utils.go:4]: The commit title is too long and that's why checkpatch is complaining. It should also be a title instead of a sentence and it's good practice to prepend it with the part of the code base that's affected (ex. `cmd:`, `bpf:`). Run `git log` in the directory you're making changes in to see examples.

**Review by pchaigno — COMMENTED** [review]
Apart from the commit title, everything looks good to me!

**Comment by pchaigno** [comment]
> I noted this PR causes regression for #27996. For instance, after running `ip x s a src 1.1.1.1 dst 1.1.1.2 proto esp spi 0x3 reqid 1 mode tunnel enc aes 0xf0e1d2c3b4a5f60708090a0b0c0d0e0f` on kind-worker, `cilium encrypt status` at kind-worker failed with "Error: Cannot count unique IPSec keys: an unsupported key with only Auth or Crypt set has been found". Is this what we want? In some cases users would install xfrm states out of cilium's management, do we expect cilium CLI to continue working?

@jschwinger233 Thanks for checking! I didn't even know you could set `Crypt` without `Auth`, but I guess it makes sense. I believe your concern should be addressed by the last version of the PR, right? It will print an error but otherwise behave correctly.

**Review by jschwinger233 — APPROVED** [review]
Paul: right! 
Viktor: Thanks!

File: pkg/common/ipsec/utils.go (hunk 10 above)
Comment (viktor-kurchenko) [reply pkg/common/ipsec/utils.go:4]: Gotcha! Is it better now?
Thanks!

Comment (pchaigno) [reply pkg/common/ipsec/utils.go:4]: It's better but "bug" isn't a code base area :wink:  You could also be a bit more specific in what is fixed. For example, `cmd: Handle non-AEAD IPsec keys in encrypt status`.

Comment (viktor-kurchenko) [reply pkg/common/ipsec/utils.go:4]: Fixed.

**Review by pchaigno — APPROVED** [review]
Thanks!

I've updated the release note.

File: pkg/common/ipsec/utils.go [hunk 11]
```diff
@@ -17,13 +20,23 @@ const (
...
+			// we want to count the number of unique (Auth, Crypt) tuples
+			key := fmt.Sprintf("%s:%s", string(s.Auth.Key), string(s.Crypt.Key))
+			keys[key] = true
 			continue
 		}
-		keys[string(s.Aead.Key)] = true
+		invalidStateFound = true
+	}
+	if invalidStateFound {
+		fmt.Fprintf(os.Stderr, "an unsupported XfrmStateAlgo combination has been found\n")
```
Comment (asauber) [inline pkg/common/ipsec/utils.go]: Since we know that this is an invalid state, why not also return an error in this case?

**Review by asauber — CHANGES_REQUESTED** [review]

File: pkg/common/ipsec/utils.go (hunk 11 above)
Comment (viktor-kurchenko) [reply pkg/common/ipsec/utils.go]: That was the initial idea but it causes regression: https://github.com/cilium/cilium/pull/29182#pullrequestreview-1741248733

Comment (asauber) [reply pkg/common/ipsec/utils.go]: Is there a way for us to mark XFRM states as being owned by Cilium?

Comment (viktor-kurchenko) [reply pkg/common/ipsec/utils.go]: I have no idea... (((

Comment (pchaigno) [reply pkg/common/ipsec/utils.go]: Not really, no, and it feels fairly out-of-scope for this PR anyway.

Comment (asauber) [reply pkg/common/ipsec/utils.go]: Error handling here would help to prevent related bugs in the future.

Comment (pchaigno) [reply pkg/common/ipsec/utils.go]: Feel free to send a PR or CFP with a proposed approach. The goal of this PR is to add support for non-AEAD keys, not to deal with concurrent software using XFRM.

Comment (asauber) [reply pkg/common/ipsec/utils.go]: External factors are one reason to add error handling, another is giving the agent the ability to detect and recover in such instances (including unintentional corruption by the agent itself).

With regards to the above introduced test failure, I wouldn't suggest that we change the existing logic to exit on an error condition, rather add an error return value and ignore it in all cases where it is currently ignored. This gives, at least, future consumers of this function the opportunity to implement error handling.

Comment (derailed) [reply pkg/common/ipsec/utils.go]: I would agree with @asauber here. This is an exported util function and the call site won't be able to assert the validity of the returned count should one or mode invalid entries are found in the slice. 
Not to mention, we are assuming we are on the console which seems odd from a convenience call perspective??

**Review by asauber — APPROVED** [review]
The logic and tests appear to be correct, so I'll approve.

Adding error handling here will be important for catching similar issues in the future. It can be done with a first pass that doesn't impact the existing logic.

File: pkg/common/ipsec/utils.go (hunk 11 above)
Comment (viktor-kurchenko) [reply pkg/common/ipsec/utils.go]: @asauber @derailed I'm going to add error to the function signature.
Are you okay if the function returns the IPsec key count even if an error was detected? or it should return 0?
Thanks!

Comment (asauber) [reply pkg/common/ipsec/utils.go]: Non-zero for other parameters is definitely fine

Comment (viktor-kurchenko) [reply pkg/common/ipsec/utils.go]: Done.

**Review by derailed — APPROVED** [review]
@viktor-kurchenko Nice work! Thanks for the updates Viktor.
