### PR TITLE
test: Support singleton manifests

### LINKED ISSUE #11311: CI: Suite-k8s-1.18.K8sConformance Portmap Chaining Check connectivity-check compliance with portmap chaining
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/4661/testReport/

```
/home/jenkins/workspace/cilium-ginkgo_cilium_master/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:431
connectivity-check pods are not ready after timeout
Expected
    <*errors.errorString | 0xc000439440>: {
        s: "timed out waiting for pods with filter  to be ready: 4m0s timeout expired",
    }
to be nil
/usr/local/go/src/reflect/value.go:460

Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
⚠️  Number of "level=warning" in logs: 32
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
Top 5 errors/warnings:
Mutation detector is enabled, this will result in memory leakage.
BPF host reachable services for UDP needs kernel 4.19.57, 5.1.16, 5.2.0 or newer. If you run an older kernel and only need TCP, then specify: --host-reachable-services-protos=tcp Disabling the feature.
SessionAffinity feature requires BPF LRU maps. Disabling the feature.
Key allocation attempt failed
BPF system config check: NOT OK.
Cilium pods: [cilium-6dvmt cilium-92vp5]
Netpols loaded: 
CiliumNetworkPolicies loaded: default::pod-to-a-allowed-cnp default::pod-to-a-l3-denied-cnp default::pod-to-external-fqdn-allow-google-cnp 
Endpoint Policy Enforcement:
Pod                                                      Ingress   Egress
pod-to-b-multi-node-clusterip-75f5c78f68-jt47x                     
pod-to-external-fqdn-allow-google-cnp-74466b4c6f-98vwn             
pod-to-a-l3-denied-cnp-74b9566cc7-kztsh                            
pod-to-b-intra-node-hostport-6c55bf8459-dtwpv                      
coredns-7964865f77-f99vr                                           
pod-to-b-intra-node-77b485d996-469f4                               
pod-to-b-multi-node-hostport-d7c8d659f-7cqjq                       
pod-to-a-external-1111-5779fb7cb9-7cq6b                            
pod-to-b-multi-node-nodeport-55b9769455-2bllq                      
echo-b-659766fb56-tqtpc                                            
pod-to-a-allowed-cnp-5898f7d8c9-qc8sd                              
pod-to-b-intra-node-nodeport-56975db6c7-vpzf7                      
pod-to-b-multi-node-headless-5df88f9bd4-z9fgl                      
echo-a-5f555bbc8b-7mfxc                                            
pod-to-a-6cf58894b7-9ll5d                                          
Cilium agent 'cilium-6dvmt': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 60 Failed 0
Cilium agent 'cilium-92vp5': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 32 Failed 0

Standard Error
STEP: Installing Cilium
STEP: Installing DNS Deployment
STEP: Restarting DNS Pods
STEP: Performing Cilium preflight check
STEP: Performing Cilium status preflight check
STEP: Performing Cilium controllers preflight check
STEP: Performing Cilium health check
STEP: Performing Cilium service preflight check
STEP: Performing K8s service preflight check
STEP: Waiting for cilium-operator to be ready
STEP: Waiting for kube-dns to be ready
STEP: Running kube-dns preflight check
STEP: Performing K8s service preflight check
STEP: Making sure all endpoints are in ready state
=== Test Finished at 2020-05-01T19:35:58Z====
===================== TEST FAILED =====================
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE     NAME                                                     READY   STATUS             RESTARTS   AGE     IP              NODE   NOMINATED NODE   READINESS GATES
	 default       echo-a-5f555bbc8b-7mfxc                                  1/1     Running            0          4m2s    10.10.1.180     k8s2   <none>           <none>
	 default       echo-b-659766fb56-tqtpc                                  1/1     Running            0          4m2s    10.10.1.254     k8s2   <none>           <none>
	 default       echo-b-host-65d7db76d8-2v66n                             0/1     CrashLoopBackOff   5          4m2s    192.168.36.12   k8s2   <none>           <none>
	 default       host-to-b-multi-node-clusterip-c7557d4f8-b7plg           1/1     Running            0          4m2s    192.168.36.11   k8s1   <none>           <none>
	 default       host-to-b-multi-node-headless-5dfcdf9b76-jccng           1/1     Running            0          4m2s    192.168.36.11   k8s1   <none>           <none>
	 default       pod-to-a-6cf58894b7-9ll5d                                1/1     Running            0          4m1s    10.10.1.171     k8s2   <none>           <none>
	 default       pod-to-a-allowed-cnp-5898f7d8c9-qc8sd                    1/1     Running            0          4m2s    10.10.1.168     k8s2   <none>           <none>
	 default       pod-to-a-external-1111-5779fb7cb9-7cq6b                  1/1     Running            0          4m      10.10.1.207     k8s2   <none>           <none>
	 default       pod-to-a-l3-denied-cnp-74b9566cc7-kztsh                  1/1     Running            0          4m1s    10.10.1.28      k8s2   <none>           <none>
	 default       pod-to-b-intra-node-77b485d996-469f4                     1/1     Running            0          4m1s    10.10.1.240     k8s2   <none>           <none>
	 default       pod-to-b-intra-node-hostport-6c55bf8459-dtwpv            0/1     Running            4          4m1s    10.10.1.210     k8s2   <none>           <none>
	 default       pod-to-b-intra-node-nodeport-56975db6c7-vpzf7            0/1     Running            3          4m1s    10.10.1.85      k8s2   <none>           <none>
	 default       pod-to-b-multi-node-clusterip-75f5c78f68-jt47x           1/1     Running            0          4m1s    10.10.0.150     k8s1   <none>           <none>
	 default       pod-to-b-multi-node-headless-5df88f9bd4-z9fgl            1/1     Running            0          4m      10.10.0.148     k8s1   <none>           <none>
	 default       pod-to-b-multi-node-hostport-d7c8d659f-7cqjq             0/1     Running            3          4m      10.10.0.132     k8s1   <none>           <none>
	 default       pod-to-b-multi-node-nodeport-55b9769455-2bllq            0/1     Running            4          4m      10.10.0.228     k8s1   <none>           <none>
	 default       pod-to-external-fqdn-allow-google-cnp-74466b4c6f-98vwn   1/1     Running            0          4m      10.10.1.73      k8s2   <none>           <none>
	 kube-system   cilium-6dvmt                                             1/1     Running            0          4m28s   192.168.36.12   k8s2   <none>           <none>
	 kube-system   cilium-92vp5                                             1/1     Running            0          4m28s   192.168.36.11   k8s1   <none>           <none>
	 kube-system   cilium-operator-5895969ff9-fcwv8                         1/1     Running            0          4m28s   192.168.36.12   k8s2   <none>           <none>
	 kube-system   coredns-7964865f77-f99vr                                 1/1     Running            0          4m23s   10.10.1.80      k8s2   <none>           <none>
	 kube-system   etcd-k8s1                                                1/1     Running            0          56m     192.168.36.11   k8s1   <none>           <none>
	 kube-system   kube-apiserver-k8s1                                      1/1     Running            0          56m     192.168.36.11   k8s1   <none>           <none>
	 kube-system   kube-controller-manager-k8s1                             1/1     Running            0          56m     192.168.36.11   k8s1   <none>           <none>
	 kube-system   kube-proxy-95nbb                                         1/1     Running            0          55m     192.168.36.12   k8s2   <none>           <none>
	 kube-system   kube-proxy-fhkf6                                         1/1     Running            0          56m     192.168.36.11   k8s1   <none>           <none>
	 kube-system   kube-scheduler-k8s1                                      1/1     Running            0          56m     192.168.36.11   k8s1   <none>           <none>
	 kube-system   log-gatherer-84w6x                                       1/1     Running            0          52m     192.168.36.11   k8s1   <none>           <none>
	 kube-system   log-gatherer-x5whx                                       1/1     Running            0          52m     192.168.36.12   k8s2   <none>           <none>
	 kube-system   registry-adder-s2rfb                                     1/1     Running            0          55m     192.168.36.12   k8s2   <none>           <none>
	 kube-system   registry-adder-w5zsw                                     1/1     Running            0          55m     192.168.36.11   k8s1   <none>           <none>
	 
Stderr:
 	 

Fetching command output from pods [cilium-6dvmt cilium-92vp5]
cmd: kubectl exec -n kube-system cilium-6dvmt -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                       IPv6                   IPv4          STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                         
	 186        Disabled           Disabled          63100      k8s:io.cilium.k8s.policy.cluster=default          f00d::a0a:100:0:c7dd   10.10.1.80    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=coredns                                                
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                    
	                                                            k8s:k8s-app=kube-dns                                                                           
	 310        Disabled           Disabled          4          reserved:health                                   f00d::a0a:100:0:fbe4   10.10.1.232   ready   
	 621        Disabled           Disabled          3697       k8s:io.cilium.k8s.policy.cluster=default          f00d::a0a:100:0:340e   10.10.1.85    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                
	                                                            k8s:io.kubernetes.pod.namespace=default                                                        
	                                                            k8s:name=pod-to-b-intra-node-nodeport                                                          
	 1135       Disabled           Enabled           3204       k8s:io.cilium.k8s.policy.cluster=default          f00d::a0a:100:0:cea3   10.10.1.73    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                
	                                                            k8s:io.kubernetes.pod.namespace=default                                                        
	                                                            k8s:name=pod-to-external-fqdn-allow-google-cnp                                                 
	 1181       Disabled           Enabled           4481       k8s:io.cilium.k8s.policy.cluster=default          f00d::a0a:100:0:7aa2   10.10.1.28    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                
	                                                            k8s:io.kubernetes.pod.namespace=default                                                        
	                                                            k8s:name=pod-to-a-l3-denied-cnp                                                                
	 1283       Disabled           Disabled          2698       k8s:io.cilium.k8s.policy.cluster=default          f00d::a0a:100:0:f8f5   10.10.1.207   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                
	                                                            k8s:io.kubernetes.pod.namespace=default                                                        
	                                                            k8s:name=pod-to-a-external-1111                                                                
	 1396       Disabled           Disabled          40831      k8s:io.cilium.k8s.policy.cluster=default          f00d::a0a:100:0:a837   10.10.1.254   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                
	                                                            k8s:io.kubernetes.pod.namespace=default                                                        
	                                                            k8s:name=echo-b                                                                                
	 1598       Disabled           Disabled          24705      k8s:io.cilium.k8s.policy.cluster=default          f00d::a0a:100:0:2410   10.10.1.171   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                
	                                                            k8s:io.kubernetes.pod.namespace=default                                                        
	                                                            k8s:name=pod-to-a                                                                              
	 1721       Disabled           Enabled           28825      k8s:io.cilium.k8s.policy.cluster=default          f00d::a0a:100:0:1adf   10.10.1.168   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                
	                                                            k8s:io.kubernetes.pod.namespace=default                                                        
	                                                            k8s:name=pod-to-a-allowed-cnp                                                                  
	 2564       Disabled           Disabled          22785      k8s:io.cilium.k8s.policy.cluster=default          f00d::a0a:100:0:bb78   10.10.1.210   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                
	                                                            k8s:io.kubernetes.pod.namespace=default                                                        
	                                                            k8s:name=pod-to-b-intra-node-hostport                                                          
	 3070       Disabled           Disabled          1776       k8s:io.cilium.k8s.policy.cluster=default          f00d::a0a:100:0:ad8d   10.10.1.240   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                
	                                                            k8s:io.kubernetes.pod.namespace=default                                                        
	                                                            k8s:name=pod-to-b-intra-node                                                                   
	 3381       Disabled           Disabled          18097      k8s:io.cilium.k8s.policy.cluster=default          f00d::a0a:100:0:a424   10.10.1.180   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                
	                                                            k8s:io.kubernetes.pod.namespace=default                                                        
	                                                            k8s:name=echo-a                                                                                
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-92vp5 -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                       IPv6                 IPv4          STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                       
	 339        Disabled           Disabled          37384      k8s:io.cilium.k8s.policy.cluster=default          f00d::a0a:0:0:411c   10.10.0.132   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                              
	                                                            k8s:io.kubernetes.pod.namespace=default                                                      
	                                                            k8s:name=pod-to-b-multi-node-hostport                                                        
	 689        Disabled           Disabled          4          reserved:health                                   f00d::a0a:0:0:4193   10.10.0.56    ready   
	 889        Disabled           Disabled          10516      k8s:io.cilium.k8s.policy.cluster=default          f00d::a0a:0:0:dd9f   10.10.0.228   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                              
	                                                            k8s:io.kubernetes.pod.namespace=default                                                      
	                                                            k8s:name=pod-to-b-multi-node-nodeport                                                        
	 3569       Disabled           Disabled          26723      k8s:io.cilium.k8s.policy.cluster=default          f00d::a0a:0:0:d07d   10.10.0.150   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                              
	                                                            k8s:io.kubernetes.pod.namespace=default                                                      
	                                                            k8s:name=pod-to-b-multi-node-clusterip                                                       
	 3582       Disabled           Disabled          29252      k8s:io.cilium.k8s.policy.cluster=default          f00d::a0a:0:0:6264   10.10.0.148   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                              
	                                                            k8s:io.kubernetes.pod.namespace=default                                                      
	                                                            k8s:name=pod-to-b-multi-node-headless                                                        
	 
Stderr:
 	 

===================== Exiting AfterFailed =====================

[[ATTACHMENT|dc899a59_K8sConformance_Portmap_Chaining_Check_connectivity-check_compliance_with_portmap_chaining.zip]]
STEP: Installing Cilium
STEP: Installing DNS Deployment
STEP: Restarting DNS Pods
STEP: Performing Cilium preflight check
STEP: Performing Cilium status preflight check
STEP: Performing Cilium controllers preflight check
STEP: Performing Cilium health check
STEP: Performing Cilium service preflight check
STEP: Performing K8s service preflight check
STEP: Waiting for cilium-operator to be ready
STEP: Waiting for kube-dns to be ready
STEP: Running kube-dns preflight check
STEP: Performing K8s service preflight check
```

[dc899a59_K8sConformance_Portmap_Chaining_Check_connectivity-check_compliance_with_portmap_chaining (1).zip](https://github.com/cilium/cilium/files/4575533/dc899a59_K8sConformance_Portmap_Chaining_Check_connectivity-check_compliance_with_portmap_chaining.1.zip)

### PR DESCRIPTION
**Pull request by tgraf**
Some manifests contain hostports or other definitions which are only
available once on a particular node. Combined with a node selector,
these can create scheduling conflicts and result in deployments
remaining in pending state.

Support marking such manifests as singleton and delete any conflicting
leftover deployment in any other namespace.

Fixes: #11311

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-gke

**Comment by tgraf** [comment]
test-gke

**Comment by tgraf** [comment]
test-me-please

File: test/k8sT/manifests.go [hunk 1]
```diff
@@ -22,9 +22,11 @@ var (
 	deploymentManager = helpers.NewDeploymentManager()
 
 	DemoDaemonSet = helpers.Manifest{
-		Filename:     "demo_ds.yaml",
-		NumDaemonSet: 2,
-		NumPods:      1,
+		Filename:        "demo_ds.yaml",
+		DaemonSetNames:  []string{"testds", "testclient"},
```
Comment (nebril) [inline test/k8sT/manifests.go:26]: would be nice to have a helper which reads the file and fills `DaemonSetNames` and `DeploymentNames` automatically so we don't need to keep these in sync. I think it's a good candidate for a follow-up PR though.

**Review by nebril — APPROVED** [review]

**Comment by joestringer** [comment]
I marked this as needing backport to v1.7 since we observed the flake on that branch as well in #13292 . If the backport is painful, then it may not be worth actually backporting but I will nominate it just in case it's a smooth fix for a known flake.

**Comment by joestringer** [comment]
There's a fairly big conflict that is mostly just the new code added by this PR. At a glance I would guess it's not a huge effort to backport, but I've avoided doing so in #13335 to avoid blocking important bugfixes & the next v1.7 release.

**Comment by qmonnet** [comment]
I'm working on a backport for 1.7.

**Comment by qmonnet** [comment]
Seeing that this one looks complex to backport to v1.7, for what looks to be a moderate gain, I'll unmark it to ease the backport process. Can be re-marked for backport if priorities change in the future.
