### PR TITLE
daemon: Implement route-based device detection

### LINKED ISSUE #15960: cilium agent device auto-detection issue
## Bug report

As part of the `v1.10.0-rc1` upgrade, I discovered that "a lot" of kernel warnings were being generated (approx rate: 10 every 5s):

```shell
~$ dmesg
[..]
[4551032.527084] ens6 selects TX queue 2135, but real number of TX queues is 4
[4551032.564637] ens6 selects TX queue 2135, but real number of TX queues is 4
[4551032.655046] ens6 selects TX queue 1925, but real number of TX queues is 4
[4551032.655136] ens6 selects TX queue 1925, but real number of TX queues is 4
[4551032.655330] ens6 selects TX queue 1925, but real number of TX queues is 4
[4551032.655658] ens6 selects TX queue 1925, but real number of TX queues is 4
[4551032.656205] ens6 selects TX queue 1925, but real number of TX queues is 4
[4551032.656311] ens6 selects TX queue 1925, but real number of TX queues is 4
[4551032.656873] ens6 selects TX queue 1925, but real number of TX queues is 4
[4551032.656957] ens6 selects TX queue 1925, but real number of TX queues is 4
[4551034.763793] lxc_health: Caught tx_queue_len zero misconfig
```

Doing some researches I ended up onto https://github.com/cilium/cilium/issues/13869, looking at the diff with of my former installation (v1.9.4), I figured that [bandwidth manager](https://docs.cilium.io/en/v1.9/gettingstarted/bandwidth-manager/) was now enabled by default.

https://github.com/cilium/cilium/blob/44099a46016360278381f9fd181853a88f695d99/install/kubernetes/cilium/values.yaml#L217

Even though I do not believe any pods were actually configured to enforce limits, by disabling it I managed to sort this issue out.

**General Information**

- Cilium version: `v1.10.0-rc1`
- Kernel version: `5.4.0-1038-aws`
- Orchestration system version in use: `v1.19.6-eks-49a6c0`

### PR DESCRIPTION
**Pull request by joamaki**
This reimplements the device detection logic to use the route
information rather than detecting devices based on k8s nodeIP and
the device with the default route.

The devices are discovered by finding all devices mentioned in global
unicast routes and filtering out cilium-managed devices by prefix.

Motivation for this change is to handle cases like #15960 more reliably
and not have the user specify devices manually. This also prepares for
later work to detect devices at runtime to allow e.g. use of KPR with ENI,
which adds devices dynamically.

The reason for introducing DeviceManager is to later add support for
dynamically reconfiguring the datapath for devices added at runtime.
Also the detected devices are now also used for host firewall and
bandwidth manager so makes sense for this logic to be moved out.

Fixes: #15960

```release-note
Detect devices from global unicast routes in addition to only
looking for the device with the Kubernetes Node IP and the one with
default route.  This expands the set of devices used for kube-proxy
replacement, host firewall and bandwidth manager and should reduce
the need to specify devices manually.
```

### CODE REVIEW

File: daemon/cmd/devices.go [hunk 1]
```diff
@@ -0,0 +1,257 @@
...
+			Warn("Ignoring L3 device; >= 5.8 kernel is required.")
+		return false
+	}
+
+	return true
+}
+
+// updateDevicesFromRoutes processes a batch of routes and updates the set of
+// devices. Returns true if devices changed.
+func (dm *DeviceManager) updateDevicesFromRoutes(routes []netlink.Route) bool {
```
Comment (joamaki) [inline daemon/cmd/devices.go]: A follow-up PR will reuse this logic to detect devices at runtime and reload the datapath.

File: daemon/cmd/devices.go [hunk 2]
```diff
@@ -0,0 +1,257 @@
...
+		}
+	}
+
+	option.Config.Devices = dm.getDevices()
+	log.WithField(logfields.Devices, option.Config.Devices).Info("Detected devices")
+
+	return nil
+}
+
+func (dm *DeviceManager) GetDevices() []string {
```
Comment (joamaki) [inline daemon/cmd/devices.go:152]: In a follow-up with runtime detection of devices the plan is to stop using `option.Config.Devices` throughout and rather call into device manager to ask for the list of devices as it may mutate over time. Hence I already have the state for the devices and this function here. 

See https://github.com/cilium/cilium/pull/17187 for the work in progress for the runtime detection and reasoning behind the structure of this file.

File: daemon/cmd/daemon.go [hunk 3]
```diff
@@ -112,6 +112,8 @@ type Daemon struct {
 	monitorAgent *monitoragent.Agent
 	ciliumHealth *health.CiliumHealth
 
+	deviceManager *DeviceManager
```
Comment (joamaki) [inline daemon/cmd/daemon.go:115]: A more suitable place for `DeviceManager` might be in `pkg/datapath`, but I'd like to leave it here for now.

File: daemon/cmd/devices.go [hunk 4]
```diff
@@ -0,0 +1,257 @@
...
+	if option.Config.DirectRoutingDevice != "" {
+		dm.devices[option.Config.DirectRoutingDevice] = true
+	}
+
+	if option.Config.IPv6MCastDevice != "" {
+		dm.devices[option.Config.IPv6MCastDevice] = true
+	}
+
+	detectDirectRoutingDev := option.Config.EnableNodePort && option.Config.DirectRoutingDevice == ""
+	detectIPv6MCastDev := option.Config.EnableIPv6NDP && len(option.Config.IPv6MCastDevice) == 0
```
Comment (joamaki) [inline daemon/cmd/devices.go]:
```suggestion
	detectIPv6MCastDev := option.Config.EnableIPv6NDP && option.Config.IPv6MCastDevice == ""
```

**Review by borkmann — APPROVED** [review]

**Comment by joamaki** [comment]
test-me-please

File: daemon/cmd/devices.go [hunk 5]
```diff
@@ -0,0 +1,257 @@
...
+				link, err := netlink.LinkByName(dev)
+				if err != nil {
+					return fmt.Errorf("Cannot find device '%s': %w", dev, err)
+				}
+
+				// Check if any of the addresses assigned to this device is the k8s node IP and if so
+				// use it for direct routing and IPv6 multicast.
+				if addrs, err := netlink.AddrList(link, netlink.FAMILY_ALL); err == nil {
+					for _, a := range addrs {
+						if a.IP.Equal(nodeIP) {
```
Comment (borkmann) [inline daemon/cmd/devices.go]: Could we add the dev to the list of devs in any case if it matches k8s node ip (given here we know the intent for sure)?

Comment (joamaki) [reply daemon/cmd/devices.go]: Done.

**Comment by joamaki** [comment]
test-me-please

File: daemon/cmd/devices.go [hunk 6]
```diff
@@ -0,0 +1,292 @@
...
+
+	if err := expandDevices(); err != nil {
+		log.WithError(err).Warnf("Failed to expand device wildcards")
+	}
+
+	l3DevOK := false
+	if option.Config.EnableNodePort {
+		// Probe whether fast redirect is supported for L3 devices. This will
+		// invoke bpftool and requires root privileges.
+		l3DevOK = supportL3Dev()
```
Comment (joamaki) [inline daemon/cmd/devices.go:71]: Had to put the probing behind the EnableNodePort check as otherwise integration tests "Fatal()" when bpftool is missing (or if not run as root). Alternatively could make the probing not fatal on bpftool invocation failure and just return empty set of features, but not sure if that's any nicer.

**Comment by joamaki** [comment]
test-me-please

**Comment by joamaki** [comment]
test-runtime

**Comment by joamaki** [comment]
test-gke

**Comment by joamaki** [comment]
test-runtime

**Comment by joamaki** [comment]
test-me-please

**Comment by joamaki** [comment]
ci-gke

File: daemon/cmd/daemon.go [hunk 7]
```diff
@@ -603,7 +606,13 @@ func NewDaemon(ctx context.Context, cancel context.CancelFunc, epMgr *endpointma
 	// This is because the device detection requires self (Cilium)Node object,
 	// and the k8s service watcher depends on option.Config.EnableNodePort flag
 	// which can be modified after the device detection.
-	handleNativeDevices(isKubeProxyReplacementStrict)
+	if err := d.deviceManager.Detect(); err != nil {
+		if isKubeProxyReplacementStrict {
```
Comment (brb) [inline daemon/cmd/daemon.go]: @pchaigno We could extend this condition by appending `|| option.Config.EnableHostFirewall`?

File: daemon/cmd/devices.go [hunk 8]
```diff
@@ -0,0 +1,296 @@
...
+		"cilium_",
+		"lo",
+		"lxc",
+		"cni",
+		"docker",
+	}
+)
+
+type DeviceManager struct {
+	mu      lock.Mutex
```
Comment (brb) [inline daemon/cmd/devices.go]: Q: can you embed the lock.Mutex instead of creating `mu`?

File: daemon/cmd/devices.go [hunk 9]
```diff
@@ -0,0 +1,296 @@
...
+	devices map[string]bool
```
Comment (brb) [inline daemon/cmd/devices.go]: It's not clear what bool stands for. Maybe you could add the comment `// key meaning => val meaning`?

File: daemon/cmd/devices.go [hunk 10]
```diff
@@ -0,0 +1,296 @@
...
+}
+
+func NewDeviceManager() *DeviceManager {
+	return &DeviceManager{
+		devices: make(map[string]bool),
+	}
+}
+
+func (dm *DeviceManager) Close() {
```
Comment (brb) [inline daemon/cmd/devices.go]: What is supposed to be in the `Close` method?

File: daemon/cmd/devices.go [hunk 11]
```diff
@@ -0,0 +1,296 @@
...
+}
+
+// Detect tries to detect devices which are to be used for:
+// NodePort BPF, direct routing in NodePort BPF, IPsec and Bandwidth Manager.
```
Comment (brb) [inline daemon/cmd/devices.go]: I think you can merge `NodePort BPF` with `direct routing in NodePort BPF`. It's just an implementation detail.

File: daemon/cmd/devices.go (hunk 6 above)
Comment (brb) [reply daemon/cmd/devices.go:71]: The test is marked to be run as privileged. Should we just install bpftool in the env which runs the test suite?

File: daemon/cmd/devices.go [hunk 12]
```diff
@@ -0,0 +1,296 @@
...
+	for _, p := range excludedDevicePrefixes {
+		if strings.HasPrefix(name, p) {
+			log.WithField(logfields.Device, name).Debugf("Skipping device as it has excluded prefix '%s'", p)
+			return false
+		}
+	}
+
+	// Skip slave devices.
+	if link.Attrs().RawFlags&unix.IFF_SLAVE != 0 {
+		log.WithField(logfields.Device, name).Debugf("Skipping slave device")
```
Comment (brb) [inline daemon/cmd/devices.go]: Nit on terminology: s/slave/secondary device/?

**Review by brb — COMMENTED** [review]
LGTM, just a few nits.

File: daemon/cmd/daemon.go (hunk 7 above)
Comment (pchaigno) [reply daemon/cmd/daemon.go]: IIUC, we should extend this condition with all features that require devices to be set, so host firewall and bandwidth manager. IPsec as well if/once it uses this set of devices.

File: daemon/cmd/devices.go (hunk 11 above)
Comment (pchaigno) [reply daemon/cmd/devices.go]: Host firewall is missing from the list. I wonder if we should just have a method `areDevicesRequired`, use it above, and refer to it here.

File: daemon/cmd/devices.go [hunk 13]
```diff
@@ -0,0 +1,296 @@
...
+
+	l3DevOK := false
+	if option.Config.EnableNodePort {
+		// Probe whether fast redirect is supported for L3 devices. This will
+		// invoke bpftool and requires root privileges.
+		l3DevOK = supportL3Dev()
+	}
+
+	detectDevices := len(option.Config.Devices) == 0 &&
+		(option.Config.EnableNodePort || option.Config.EnableHostFirewall || option.Config.EnableBandwidthManager)
```
Comment (pchaigno) [inline daemon/cmd/devices.go]: Plus `|| option.Config.EnableIPsec`?

File: daemon/cmd/devices.go [hunk 14]
```diff
@@ -0,0 +1,296 @@
...
+		// e.g. skip loopback, multicast and link local routes.
+		if route.Dst != nil && !route.Dst.IP.IsGlobalUnicast() {
+			continue
+		}
+
+		linkIndices[route.LinkIndex] = struct{}{}
+	}
+
+	changed := false
+links:
```
Comment (pchaigno) [inline daemon/cmd/devices.go]: What is this label used for? I thought the typical use case was nested loops.

File: daemon/cmd/devices.go [hunk 15]
```diff
@@ -0,0 +1,296 @@
...
+func (dm *DeviceManager) updateDevicesFromRoutes(l3DevOK bool, routes []netlink.Route) bool {
+	linkIndices := make(map[int]struct{})
+
+	// Collect all link indices mentioned in the route update batch
+	for _, route := range routes {
+		// Only consider devices that have global unicast routes,
+		// e.g. skip loopback, multicast and link local routes.
+		if route.Dst != nil && !route.Dst.IP.IsGlobalUnicast() {
+			continue
+		}
```
Comment (pchaigno) [inline daemon/cmd/devices.go:224]: This skip condition could be moved inside the second loop to avoid the `linkIndices` allocation and one iteration through routes.

File: daemon/cmd/devices.go [hunk 16]
```diff
@@ -0,0 +1,296 @@
...
+
+		linkIndices[route.LinkIndex] = struct{}{}
+	}
+
+	changed := false
+links:
+	for linkIndex := range linkIndices {
+		link, err := netlink.LinkByIndex(linkIndex)
+		if err != nil {
+			log.WithError(err).Warnf("Failed to get link by index %d", linkIndex)
```
Comment (pchaigno) [inline daemon/cmd/devices.go]:
```suggestion
			log.WithError(err).WithField(logfields.LinkIndex, linkIndex).Warn("Failed to get link by index")
```

File: daemon/cmd/devices.go (hunk 9 above)
Comment (joamaki) [reply daemon/cmd/devices.go]: It's the suggested way of making a set in go: https://golang.org/doc/effective_go#maps. The boolean just marks existence.
I've seen "struct{}" being used elsewhere. Is there a reason to prefer that (I find it much uglier)?

File: daemon/cmd/devices.go (hunk 10 above)
Comment (joamaki) [reply daemon/cmd/devices.go]: This work was split off from PR #17187  and I wanted to get this part in first and with the basic structure in place already.
I can remove this if you want and add it later.

Eventually `Close()` will have something like this: https://github.com/cilium/cilium/pull/17187/files#diff-b7bf7344c04110932f57b676c0dce948271b6e2bb4a1587135e1cf5336958a5eR256.

File: daemon/cmd/devices.go (hunk 12 above)
Comment (pchaigno) [reply daemon/cmd/devices.go]: I think secondary as a different meaning in Linux terminology. I would also prefer to avoid this term here, but I'm not sure what to replace it with given it's specific to Linux. I ended up using it elsewhere in the codebase recently :disappointed:

Comment (joamaki) [reply daemon/cmd/devices.go]: I've not heard of "secondary device". We're testing whether the SLAVE flag is set, so we should talk about using the right terms? Or if we need to avoid that particular word we could use "lower" or "nested" device instead?

File: daemon/cmd/devices.go (hunk 6 above)
Comment (joamaki) [reply daemon/cmd/devices.go:71]: Having bpftool installed is probably better. Will take a look at adding it.

File: daemon/cmd/devices.go [hunk 17]
```diff
@@ -0,0 +1,296 @@
...
+
+	detectIPv6MCastDev := option.Config.EnableIPv6NDP
+	if option.Config.IPv6MCastDevice != "" {
+		dm.devices[option.Config.IPv6MCastDevice] = true
+		detectIPv6MCastDev = false
+	}
+
+	k8sNodeDev := ""
+	k8sNodeLink, err := findK8SNodeIPLink()
+	if err == nil {
```
Comment (pchaigno) [inline daemon/cmd/devices.go]: Shouldn't we log the error if it is not nil?

File: daemon/cmd/devices.go [hunk 18]
```diff
@@ -0,0 +1,296 @@
...
+	}
+
+	if detectDirectRoutingDev {
+		// If only one device found, use that one. Otherwise use the device with k8s node IP.
+		if len(dm.devices) == 1 {
+			for dev := range dm.devices {
+				option.Config.DirectRoutingDevice = dev
+				break
+			}
+		} else if k8sNodeLink != nil {
```
Comment (pchaigno) [inline daemon/cmd/devices.go]: Maybe safer to do:
```suggestion
		} else if k8sNodeDev != "" {
```

File: daemon/cmd/devices.go [hunk 19]
```diff
@@ -0,0 +1,296 @@
...
+			option.Config.DirectRoutingDevice = k8sNodeDev
+		} else {
+			return fmt.Errorf("Unable to determine direct routing device. Use --%s to specify them",
```
Comment (pchaigno) [inline daemon/cmd/devices.go]:
```suggestion
			return fmt.Errorf("Unable to determine direct routing device. Use --%s to specify it",
```

File: daemon/cmd/devices.go [hunk 20]
```diff
@@ -0,0 +1,296 @@
...
+			option.Config.IPv6MCastDevice = k8sNodeDev
+			log.Infof("Detected %s=%s", option.IPv6MCastDevice, option.Config.IPv6MCastDevice)
+		} else {
+			return fmt.Errorf("Unable to determine Multicast device. Use --%s to specify them",
+				option.IPv6MCastDevice)
+		}
+	}
+
+	// TODO(JM): Remove mutation of option.Config.Devices as it is unsafe. A follow up will add support
+	// for runtime detection of new devices and will switch cilium agent to use GetDevices() instead.
```
Comment (pchaigno) [inline daemon/cmd/devices.go]: Nit: Maybe best to make a note of this in the issue used to track progress on runtime detection instead. It's the sort of comments we forget and tend to leave behind :grimacing:

File: daemon/cmd/devices.go [hunk 21]
```diff
@@ -0,0 +1,296 @@
...
+	}
+
+	l3DevOK := false
+	if option.Config.EnableNodePort {
+		// Probe whether fast redirect is supported for L3 devices. This will
+		// invoke bpftool and requires root privileges.
+		l3DevOK = supportL3Dev()
+	}
+
+	detectDevices := len(option.Config.Devices) == 0 &&
```
Comment (pchaigno) [inline daemon/cmd/devices.go]: If the device name expansion fails to find any matching devices, we will kick off the detection logic. Is that what we want? It may be a bit surprising for users if they make a mistake in the device pattern (not matching anything) and everything proceeds with unexpected devices (from detection).

File: test/runtime/kafka.go [hunk 22]
```diff
@@ -134,11 +137,12 @@ var _ = Describe("RuntimeKafka", func() {
 	})
 
 	JustBeforeEach(func() {
+		testStartTime = time.Now()
 		monitorRes, monitorStop = vm.MonitorStart("--type l7")
 	})
 
 	JustAfterEach(func() {
-		vm.ValidateNoErrorsInLogs(CurrentGinkgoTestDescription().Duration)
+		vm.ValidateNoErrorsInLogs(time.Since(testStartTime))
```
Comment (pchaigno) [inline test/runtime/kafka.go]: Could you send this fix as a separate pull request so we can backport it? :pray:

**Review by pchaigno — CHANGES_REQUESTED** [review]
LGTM overall, mostly nits below.

File: daemon/cmd/devices.go (hunk 9 above)
Comment (pchaigno) [reply daemon/cmd/devices.go]: I personally like `map[string]void` but I don't think we have a precedent in the codebase. Regardless of what we use, could you add a comment explaining it's a set. It's not immediately obvious otherwise.

File: daemon/cmd/devices.go (hunk 6 above)
Comment (joamaki) [reply daemon/cmd/devices.go:71]: Yep I think I meant the privileged unit tests. daemon_test.go I think was stumbling on this.

Comment (pchaigno) [reply daemon/cmd/devices.go:71]: AFAIK, `bpftool` should already be installed in all environments we use for integration tests. Did you mean unit tests maybe?

File: daemon/cmd/devices.go (hunk 9 above)
Comment (joamaki) [reply daemon/cmd/devices.go]: Will add, thanks!

File: daemon/cmd/devices.go (hunk 14 above)
Comment (joamaki) [reply daemon/cmd/devices.go]: Ah heh, looks like refactoring at some point removed the nested loop, but I forgot this. I'll remove the label :)

File: daemon/cmd/devices.go (hunk 10 above)
Comment (pchaigno) [reply daemon/cmd/devices.go]: Nit: I'd prefer if it was removed until used. You never know what will happen with the second pull request; this method may not be needed anymore by the time it gets merged.

File: daemon/cmd/devices.go (hunk 20 above)
Comment (joamaki) [reply daemon/cmd/devices.go]: Added TODO to roadmap issue and dropped the comment. I won't forget this one since it's one of the main blockers on #17187 :)

File: daemon/cmd/devices.go (hunk 21 above)
Comment (joamaki) [reply daemon/cmd/devices.go]: Good catch. I think it's best to fail if expansion fails completely. I'll add that check. We do still want to allow expansion to partially not match so users can provide alternatives.

File: test/runtime/kafka.go (hunk 22 above)
Comment (joamaki) [reply test/runtime/kafka.go]: Yes will do!

File: daemon/cmd/devices.go (hunk 17 above)
Comment (joamaki) [reply daemon/cmd/devices.go]: No since k8s may not actually be always available in all use-cases. Though may be it should be here?

File: daemon/cmd/devices.go (hunk 15 above)
Comment (joamaki) [reply daemon/cmd/devices.go:224]: Hmm I don't quite follow. We want to ignore all uninteresting routes here and not consider the links that don't have interesting routes.

File: daemon/cmd/devices.go (hunk 13 above)
Comment (joamaki) [reply daemon/cmd/devices.go]: Added.

File: daemon/cmd/devices.go (hunk 6 above)
Comment (joamaki) [reply daemon/cmd/devices.go:71]: I think the solution as is is fine. The failing tests prior to moving call to supportL3Dev() here was the daemon_test.go which was non-privileged, so we wouldn't be able to query this with bpftool even if it was available.

File: daemon/cmd/devices.go (hunk 11 above)
Comment (joamaki) [reply daemon/cmd/devices.go]: Good idea, added.

File: daemon/cmd/devices.go (hunk 10 above)
Comment (joamaki) [reply daemon/cmd/devices.go]: Yep cleaner. Removed.

File: daemon/cmd/devices.go (hunk 9 above)
Comment (joamaki) [reply daemon/cmd/devices.go]: I'll switch this to `struct{}` as that's the normal pattern.

File: daemon/cmd/daemon.go (hunk 7 above)
Comment (joamaki) [reply daemon/cmd/daemon.go]: Done.

File: daemon/cmd/devices.go (hunk 15 above)
Comment (pchaigno) [reply daemon/cmd/devices.go:224]: Yes, I'm not proposing to change that. But these four lines could be moved inside the second loop and it would achieve the same while avoiding the need for `linkIndices`, no?

File: daemon/cmd/devices.go (hunk 17 above)
Comment (pchaigno) [reply daemon/cmd/devices.go]: Do you mean there's one error case that's expected? If that's the case, we should ignore that specific error and log the rest I think.

File: daemon/cmd/devices.go (hunk 15 above)
Comment (joamaki) [reply daemon/cmd/devices.go:224]: I'm still not following how that would work. We may have hundreds of routes from which we want to create a set of interesting links to look at. The second loop doesn't deal with routes anymore so this check doesn't work there. Also please check the final code as the second commit modified this.

File: daemon/cmd/devices.go (hunk 17 above)
Comment (joamaki) [reply daemon/cmd/devices.go]: Well, it can fail in two ways: either the Node IP is not set (k8s not enabled, or something else horrible wrong), or the device can not be found that has the Node IP. Right now we only care about it failing to find the device if we need that information for the direct routing device or mcast device detection. 

I guess I see the point of failing more eagerly here. I'll think about what would be more exact thing to do here.

File: daemon/cmd/devices.go (hunk 15 above)
Comment (pchaigno) [reply daemon/cmd/devices.go:224]: > Also please check the final code as the second commit modified this.

Ah, forgot that. What I had in mind won't work with `linkInfo.hasDefaultRoute` :+1:

File: daemon/cmd/devices.go (hunk 9 above)
Comment (brb) [reply daemon/cmd/devices.go]: > I've seen "struct{}" being used elsewhere

AFAIK `struct{}` should not allocate any mem for val, while `bool` does.

File: daemon/cmd/devices.go (hunk 17 above)
Comment (pchaigno) [reply daemon/cmd/devices.go]: If we're just worried about environment where K8s is not installed, we could simply check `k8s.IsEnabled()` before looking up `k8sNodeLink`.

File: test/runtime/kafka.go (hunk 22 above)
Comment (joamaki) [reply test/runtime/kafka.go]: https://github.com/cilium/cilium/pull/17351

**Review by nbusseneau — APPROVED** [review]
Code changes LGTM.

Q: regarding CI status => I see Travis CI failing with
```
--- FAIL: Test (2.48s)
FAIL coverage: 3.8% of statements in ./...
FAIL	github.com/cilium/cilium/pkg/aws/eni	2.560s
FAIL make: *** [Makefile:205: integration-tests] Error 1
The command "./.travis/build.sh" exited with 2.
```
Did we investigate if this was related to the PR? It looks like #9604 at a first glance but just to be sure...

**Comment by joamaki** [comment]
> Code changes LGTM.
> 
> Q: regarding CI status => I see Travis CI failing with
> 
> ```
> --- FAIL: Test (2.48s)
> FAIL coverage: 3.8% of statements in ./...
> FAIL	github.com/cilium/cilium/pkg/aws/eni	2.560s
> FAIL make: *** [Makefile:205: integration-tests] Error 1
> The command "./.travis/build.sh" exited with 2.
> ```
> 
> Did we investigate if this was related to the PR? It looks like #9604 at a first glance but just to be sure...

First time it's failing there in the course of this PR and the recent changes were mostly cosmetic, so quite likely it's #9604.

**Comment by joamaki** [comment]
test-me-please

File: daemon/cmd/devices.go (hunk 12 above)
Comment (joamaki) [reply daemon/cmd/devices.go]: This is now "bonded device"

**Comment by joamaki** [comment]
test-me-please

**Comment by joamaki** [comment]
@pchaigno PTAL

**Comment by joamaki** [comment]
Test failures:
ci-aks:
```
Connectivity test failed: timeout reached waiting lookup for kubernetes.default from pod cilium-test/client-6488dcf5d4-x97t6 to succeed
```
ci-eks:
```
command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null http://echo-same-node:8080" failed: command terminated with exit code 6
  ℹ️  curl output:
  curl: (6) Could not resolve host: echo-same-node
:0 -> :0 = 000
```
ci-gke:
```
command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null http://one.one.one.one:80" failed: command terminated with exit code 22
  ℹ️  curl output:
  curl: (22) The requested URL returned error: 403
10.84.1.73:40722 -> 1.0.0.1:80 = 403
```

None of these appear to be related to this PR since it's more of an all-or-nothing with the device detection. Logs show that "eth0" was detected properly in all cases.

**Comment by jrajahalme** [comment]
I see no proxy related changes so maybe those have disappeared in force pushes? I have 0% familiarity with the touched code, so I will not be reviewing this :-)

**Comment by joamaki** [comment]
test-me-please

**Comment by nbusseneau** [comment]
Tried to do some quick triage...

### GKE

https://github.com/cilium/cilium/actions/runs/1233482831 hit multiple issues when testing with IPsec encryption enabled:
```
   [.] Action [allow-all/pod-to-world/https-to-one-one-one-one-0: cilium-test/client-6488dcf5d4-fr2sp (10.36.1.60) -> one-one-one-one-https (one.one.one.one:443)]
  📄 Following flows...
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null https://one.one.one.one:443" failed: command terminated with exit code 28
  ℹ️  curl output:
  curl: (28) Resolving timed out after 5000 milliseconds
:0 -> :0 = 000
...
Test [allow-all]:
  ❌ allow-all/pod-to-world/https-to-one-one-one-one-0: cilium-test/client2-65f446d77c-vvtj8 (10.36.0.212) -> one-one-one-one-https (one.one.one.one:443)
```
This one is https://github.com/cilium/cilium-cli/issues/367.

```
   [.] Action [client-egress-l7/pod-to-pod/curl-3: cilium-test/client2-65f446d77c-vvtj8 (10.36.0.212) -> cilium-test/echo-same-node-7967996674-tr7sb (10.36.1.102:8080)]
  📄 Following flows...
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null http://10.36.1.102:8080" failed: command terminated with exit code 22
  ℹ️  curl output:
  curl: (22) The requested URL returned error: 503
10.36.0.212:38336 -> 10.36.1.102:8080 = 503
...
Test [client-egress-l7]:
  ❌ client-egress-l7/pod-to-pod/curl-3: cilium-test/client2-65f446d77c-vvtj8 (10.36.0.212) -> cilium-test/echo-same-node-7967996674-tr7sb (10.36.1.102:8080)
```
```
   [.] Action [echo-ingress-l7/pod-to-pod/curl-3: cilium-test/client2-65f446d77c-vvtj8 (10.36.0.212) -> cilium-test/echo-same-node-7967996674-tr7sb (10.36.1.102:8080)]
  📄 Following flows...
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null http://10.36.1.102:8080" failed: command terminated with exit code 52
  ℹ️  curl output:
  curl: (52) Empty reply from server
10.36.0.212:38450 -> 10.36.1.102:8080 = 000
...
 Test [echo-ingress-l7]:
  ❌ echo-ingress-l7/pod-to-pod/curl-3: cilium-test/client2-65f446d77c-vvtj8 (10.36.0.212) -> cilium-test/echo-same-node-7967996674-tr7sb (10.36.1.102:8080)
```
Both of these look extremely similar to #17139. These did not seem to be not happening on GKE beforehand, and they also appeared in a previous `ci-gke` run from this PR (https://github.com/cilium/cilium/actions/runs/1221422154), so I would be inclined to say this might be coming from the PR changes or recently merged changes.

### AKS

https://github.com/cilium/cilium/actions/runs/1233482770 hit a startup issue with encryption enabled:

```
🔥 [cilium-cilium-1233482770] Deleting connectivity check deployments...
✨ [cilium-cilium-1233482770] Creating namespace for connectivity check...
✨ [cilium-cilium-1233482770] Deploying echo-same-node service...
✨ [cilium-cilium-1233482770] Deploying same-node deployment...
✨ [cilium-cilium-1233482770] Deploying client deployment...
✨ [cilium-cilium-1233482770] Deploying client2 deployment...
✨ [cilium-cilium-1233482770] Deploying echo-other-node service...
✨ [cilium-cilium-1233482770] Deploying other-node deployment...
⌛ [cilium-cilium-1233482770] Waiting for deployments [client client2 echo-same-node] to become ready...
⌛ [cilium-cilium-1233482770] Waiting for deployments [echo-other-node] to become ready...
⌛ [cilium-cilium-1233482770] Waiting for CiliumEndpoint for pod cilium-test/client-6488dcf5d4-s7j8l to appear...
⌛ [cilium-cilium-1233482770] Waiting for CiliumEndpoint for pod cilium-test/client2-65f446d77c-cpdjs to appear...
⌛ [cilium-cilium-1233482770] Waiting for CiliumEndpoint for pod cilium-test/echo-other-node-697d5d69b7-jmbqh to appear...
⌛ [cilium-cilium-1233482770] Waiting for CiliumEndpoint for pod cilium-test/echo-same-node-7967996674-8597x to appear...
⌛ [cilium-cilium-1233482770] Waiting for Service cilium-test/echo-other-node to become ready...
⌛ [cilium-cilium-1233482770] Waiting for Service cilium-test/echo-same-node to become ready...
⌛ [cilium-cilium-1233482770] Waiting for NodePort 10.240.0.35:30259 (cilium-test/echo-other-node) to become ready...
⌛ [cilium-cilium-1233482770] Waiting for NodePort 10.240.0.35:30083 (cilium-test/echo-same-node) to become ready...
⌛ [cilium-cilium-1233482770] Waiting for NodePort 10.240.0.66:30259 (cilium-test/echo-other-node) to become ready...
⌛ [cilium-cilium-1233482770] Waiting for NodePort 10.240.0.66:30083 (cilium-test/echo-same-node) to become ready...
ℹ️  Skipping IPCache check
⌛ [cilium-cilium-1233482770] Waiting for pod cilium-test/client-6488dcf5d4-s7j8l to reach default/kubernetes service...
⌛ [cilium-cilium-1233482770] Waiting for pod cilium-test/client2-65f446d77c-cpdjs to reach default/kubernetes service...
Connectivity test failed: timeout reached waiting lookup for kubernetes.default from pod cilium-test/client2-65f446d77c-cpdjs to succeed
```
This looks new, I have never seen it before and can't find a similar report. It also happened identically in a previous `ci-aks` run from this PR (https://github.com/cilium/cilium/actions/runs/1229138644), so I would be inclined to say this might be coming from the PR changes or recently merged changes.

### Multi-cluster

Same as the 2 "new" GKE failures:

```
[.] Action [client-egress/pod-to-pod/curl-0: cilium-test/client-6488dcf5d4-rxmxc (10.104.1.18) -> cilium-test/echo-other-node-697d5d69b7-sbvjf (10.4.0.139:8080)]
  📄 Following flows...
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null http://10.4.0.139:8080" failed: command terminated with exit code 28
  ℹ️  curl output:
  curl: (28) Connection timeout after 5001 ms
:0 -> :0 = 000
...
❌ client-egress/pod-to-pod/curl-0: cilium-test/client2-65f446d77c-6fb74 (10.104.1.52) -> cilium-test/echo-other-node-697d5d69b7-sbvjf (10.4.0.139:8080)
```
```
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null http://10.4.0.139:8080" failed: command terminated with exit code 28
  ℹ️  curl output:
  curl: (28) Connection timeout after 5000 ms
:0 -> :0 = 000
...
❌ client-egress/pod-to-pod/curl-3: cilium-test/client2-65f446d77c-6fb74 (10.104.1.52) -> cilium-test/echo-other-node-697d5d69b7-sbvjf (10.4.0.139:8080)
```

File: daemon/cmd/devices.go (hunk 17 above)
Comment (joamaki) [reply daemon/cmd/devices.go]: Added the check and returning a better error now.

File: daemon/cmd/devices.go (hunk 13 above)
Comment (joamaki) [reply daemon/cmd/devices.go]: Oops, only added it to areDevicesRequired(), but forgot to call it here. Fixed.

**Comment by joamaki** [comment]
Thanks @nbusseneau for having a look. I found one behavior change to earlier in that it added the k8s node IP device to devices. I think this might've caused something unexpected down the line. Fixed that now and will kick off the tests again.

**Comment by joamaki** [comment]
ci-gke

**Comment by joamaki** [comment]
ci-aks

**Comment by joamaki** [comment]
test-me-please

**Comment by joamaki** [comment]
ci-aks

**Comment by joamaki** [comment]
ci-aks

**Comment by joamaki** [comment]
well, `ci-aks` now passes if I don't go detect devices when `enableIPsec` is on. Looks like something somewhere is acting on the contents of `option.Config.Devices`, even though node-port=false, bandwidth-manager=false and host-firewall=false. 

I'd suggest getting this in without probing with IPsec and then I'll follow up with the runtime device detection PR and will try to then switch IPsec code to use detected devices there (need the runtime detection bit to keep IPsec working with ENI).

@pchaigno you're ok with this?

**Comment by joamaki** [comment]
test-me-please

**Comment by joamaki** [comment]
test-me-please

**Comment by joamaki** [comment]
test-me-please

**Comment by joamaki** [comment]
test-me-please

**Comment by joamaki** [comment]
ci-gke

**Comment by joamaki** [comment]
ci-l4lb

File: daemon/cmd/devices.go [hunk 23]
```diff
@@ -185,13 +186,33 @@ func (dm *DeviceManager) isViableDevice(l3DevOK bool, link netlink.Link) bool {
 		return false
 	}
 
+	// Skip veth devices that don't have a default route.
+	// This is a workaround for kubernetes-in-docker. We want to avoid
+	// veth devices in general as they may be leftovers from another CNI.
+	if !hasDefaultRoute {
+		virtual, err := ethtool.IsVirtualDriver(name)
```
Comment (brb) [inline daemon/cmd/devices.go]: I'm wondering whether we really need to invoke the ethtool. AFAIK the netlink.Link should already embed the link type, so `_, virtual := netlink.(*Veth)` could do the job.

File: daemon/cmd/devices.go [hunk 24]
```diff
@@ -255,22 +251,29 @@ links:
...
 			}
 		} else {
-			expandedDevices[iface] = true
+			expandedDevices[iface] = struct{}{}
 		}
 	}
+	if len(option.Config.Devices) > 0 && len(expandedDevices) == 0 {
+		// User defined devices, but expansion yielded no devices. Fail here to not
+		// surprise with auto-detection.
+		return fmt.Errorf("Device wildcard expansion failed to detect devices. Please verify --%s option.",
```
Comment (brb) [inline daemon/cmd/devices.go:281]: I think we are changing the previous behavior (i.e., do the dev detection if the expansion has failed), which is fine, just that we need to add a note to the upgrade guide.

File: daemon/cmd/devices.go [hunk 25]
```diff
@@ -100,36 +98,40 @@ func (dm *DeviceManager) Detect() error {
...
-		k8sNodeDev = k8sNodeLink.Attrs().Name
-		dm.devices[k8sNodeDev] = struct{}{}
-	}
+	if detectDirectRoutingDev || detectIPv6MCastDev {
+		k8sNodeDev := ""
+		k8sNodeLink, err := findK8SNodeIPLink()
+		if err == nil {
+			k8sNodeDev = k8sNodeLink.Attrs().Name
+			dm.devices[k8sNodeDev] = struct{}{}
+		} else if k8s.IsEnabled() {
```
Comment (brb) [inline daemon/cmd/devices.go:113]: It might make sense to move the `k8s.IsEnabled()` check above the `detectDirectRoutingDev || detectIPv6MCastDev` check.

File: daemon/cmd/devices.go [hunk 26]
```diff
@@ -100,36 +98,40 @@ func (dm *DeviceManager) Detect() error {
...
+			} else {
+				return fmt.Errorf("Unable to determine direct routing device. Use --%s to specify it",
+					option.DirectRoutingDevice)
 			}
-		} else if k8sNodeDev != "" {
-			option.Config.DirectRoutingDevice = k8sNodeDev
-		} else {
-			return fmt.Errorf("Unable to determine direct routing device. Use --%s to specify it",
-				option.DirectRoutingDevice)
+			log.Infof("Detected %s=%s", option.DirectRoutingDevice, option.Config.DirectRoutingDevice)
```
Comment (brb) [inline daemon/cmd/devices.go]: While you are here, maybe you could fix the msg, so that we respect the structured logging?

File: daemon/cmd/devices.go [hunk 27]
```diff
@@ -100,36 +98,40 @@ func (dm *DeviceManager) Detect() error {
...
-		if k8sNodeLink != nil && k8sNodeLink.Attrs().Flags&net.FlagMulticast != 0 {
-			option.Config.IPv6MCastDevice = k8sNodeDev
-			log.Infof("Detected %s=%s", option.IPv6MCastDevice, option.Config.IPv6MCastDevice)
-		} else {
-			return fmt.Errorf("Unable to determine Multicast device. Use --%s to specify it",
-				option.IPv6MCastDevice)
+		if detectIPv6MCastDev {
+			if k8sNodeLink != nil && k8sNodeLink.Attrs().Flags&net.FlagMulticast != 0 {
+				option.Config.IPv6MCastDevice = k8sNodeDev
+				log.Infof("Detected %s=%s", option.IPv6MCastDevice, option.Config.IPv6MCastDevice)
```
Comment (brb) [inline daemon/cmd/devices.go]: Ditto.

**Review by brb — CHANGES_REQUESTED** [review]
Cool, a few more comments, and we are getting ready to this PR to be merged.

BTW, regarding disabling the dev detection for the IPSec in the last commit - any clue why it's needed? /cc @pchaigno @jrfastab

**Comment by joamaki** [comment]
> Cool, a few more comments, and we are getting ready to this PR to be merged.
> 
> BTW, regarding disabling the dev detection for the IPSec in the last commit - any clue why it's needed? /cc @pchaigno @jrfastab

Not yet. I'll start debugging that soon though.

**Review by pchaigno — CHANGES_REQUESTED** [review]
Could you break commit `daemon: Address review comments on device detection` and merge it in the respective commits it fixes/improves? Having it in a separate commit hinders reviewing and doesn't make sense once merged.

File: daemon/cmd/devices.go (hunk 25 above)
Comment (joamaki) [reply daemon/cmd/devices.go:113]: We only require k8s when direct routing device or ipv6 mcast device detection is necessary, so it doesn't make sense to move it there as then device detection won't work without k8s. Though do we ever need device detection without k8s? I'm not sure. If not, then we can just make this fail early when k8s is not enabled.

File: daemon/cmd/devices.go (hunk 26 above)
Comment (joamaki) [reply daemon/cmd/devices.go]: Sure, good catch.

**Comment by joamaki** [comment]
> Could you break commit `daemon: Address review comments on device detection` and merge it in the respective commits it fixes/improves? Having it in a separate commit hinders reviewing and doesn't make sense once merged.

Ah I was just trying to make reviewing easier. I'll squash.

File: daemon/cmd/devices.go (hunk 27 above)
Comment (joamaki) [reply daemon/cmd/devices.go]: :+1:

File: daemon/cmd/devices.go (hunk 23 above)
Comment (joamaki) [reply daemon/cmd/devices.go]: Thanks, that works nicely.

File: daemon/cmd/devices.go (hunk 24 above)
Comment (joamaki) [reply daemon/cmd/devices.go:281]: Added a note about that, plus about the change in device detection logic.

File: daemon/cmd/devices_test.go [hunk 28]
```diff
@@ -7,7 +7,6 @@
 package cmd
 
 import (
-	"fmt"
```
Comment (qmonnet) [inline daemon/cmd/devices_test.go]: Nit: this should be moved to the previous commit

**Review by qmonnet — APPROVED** [review]

File: daemon/cmd/devices_test.go (hunk 28 above)
Comment (joamaki) [reply daemon/cmd/devices_test.go]: Done.

**Comment by joamaki** [comment]
test-me-please

**Comment by joamaki** [comment]
test-1.16-netnext

File: daemon/cmd/devices.go (hunk 25 above)
Comment (brb) [reply daemon/cmd/devices.go:113]: > Though do we ever need device detection without k8s?

Yes. In the `lb-only` mode when user specifies multiple devices, but doesn't specify the direct routing device. We should definitely keep the case `|devices| == 1 => dr_device = devices[0]` regardless of k8s presence.

**Review by brb — APPROVED** [review]

**Comment by joamaki** [comment]
@pchaigno PTAL

File: daemon/cmd/daemon.go [hunk 29]
```diff
@@ -607,7 +610,14 @@ func NewDaemon(ctx context.Context, cancel context.CancelFunc, epMgr *endpointma
 	// This is because the device detection requires self (Cilium)Node object,
 	// and the k8s service watcher depends on option.Config.EnableNodePort flag
 	// which can be modified after the device detection.
-	handleNativeDevices(isKubeProxyReplacementStrict)
+	if err := d.deviceManager.Detect(); err != nil {
+		if isKubeProxyReplacementStrict || areDevicesRequired() {
```
Comment (pchaigno) [inline daemon/cmd/daemon.go]: If `isKubeProxyReplacementStrict` is true, then `areDevicesRequired()` will always return true. So can we simplify this condition?

File: daemon/cmd/devices.go [hunk 30]
```diff
@@ -0,0 +1,337 @@
...
+	dm.Lock()
+	defer dm.Unlock()
+	dm.devices = make(map[string]struct{})
+
+	if err := expandDevices(); err != nil {
+		return err
+	}
+
+	l3DevOK := false
+	if option.Config.EnableNodePort {
```
Comment (pchaigno) [inline daemon/cmd/devices.go]: Why `EnableNodePort`? From the comment below, I understood that we only need to restrict ourselves to L3 devices if fast redirect is used. So maybe we should check for the fast redirect config instead of the BPF NodePort one?

File: daemon/cmd/devices.go [hunk 31]
```diff
@@ -0,0 +1,337 @@
...
+func (dm *DeviceManager) Detect() error {
+	dm.Lock()
+	defer dm.Unlock()
+	dm.devices = make(map[string]struct{})
+
+	if err := expandDevices(); err != nil {
+		return err
+	}
+
+	l3DevOK := false
```
Comment (pchaigno) [inline daemon/cmd/devices.go]: Shouldn't this be initialized to true by default to allow such devices unless a feature forces us to exclude them?

File: daemon/cmd/devices.go [hunk 32]
```diff
@@ -0,0 +1,337 @@
...
+					option.DirectRoutingDevice)
+			}
+			log.WithField(option.DirectRoutingDevice, option.Config.DirectRoutingDevice).
+				Info("Direct routing device detected")
+		}
+
+		if detectIPv6MCastDev {
+			if k8sNodeLink != nil && k8sNodeLink.Attrs().Flags&net.FlagMulticast != 0 {
+				option.Config.IPv6MCastDevice = k8sNodeDev
+				log.WithField(option.IPv6MCastDevice, option.Config.IPv6MCastDevice).Infof("IPv6 multicast device detected")
```
Comment (pchaigno) [inline daemon/cmd/devices.go]: Nit:
```suggestion
				log.WithField(option.IPv6MCastDevice, option.Config.IPv6MCastDevice).Info("IPv6 multicast device detected")
```

File: daemon/cmd/devices.go [hunk 33]
```diff
@@ -0,0 +1,337 @@
...
+	// Do not consider any of the excluded devices.
+	for _, p := range excludedDevicePrefixes {
+		if strings.HasPrefix(name, p) {
+			log.WithField(logfields.Device, name).
+				Warnf("Skipping device as it has excluded prefix '%s'", p)
+			return false
+		}
+	}
+
+	// Skip bonding slave devices.
```
Comment (pchaigno) [inline daemon/cmd/devices.go]:
```suggestion
	// Skip lower bond devices.
```

File: daemon/cmd/devices.go [hunk 34]
```diff
@@ -0,0 +1,337 @@
...
+// isViableDevice returns true if the given link is usable and Cilium should attach
+// programs to it.
+func (dm *DeviceManager) isViableDevice(l3DevOK, hasDefaultRoute bool, link netlink.Link) bool {
+	name := link.Attrs().Name
+
+	// Do not consider any of the excluded devices.
+	for _, p := range excludedDevicePrefixes {
+		if strings.HasPrefix(name, p) {
+			log.WithField(logfields.Device, name).
+				Warnf("Skipping device as it has excluded prefix '%s'", p)
```
Comment (pchaigno) [inline daemon/cmd/devices.go]: Do we need to print a warning in this case? If I understand correctly, this means we'll print a warning per excluded device (if they are in routes, but most usually are) on each Cilium agent restart :grimacing: 

I think Debug would be good enough here.

File: daemon/cmd/devices.go [hunk 35]
```diff
@@ -0,0 +1,337 @@
...
+			return false
+		}
+	}
+
+	// Skip bonding slave devices.
+	if link.Attrs().RawFlags&unix.IFF_SLAVE != 0 {
+		log.WithField(logfields.Device, name).Warn("Skipping bonded device")
```
Comment (pchaigno) [inline daemon/cmd/devices.go]: Here I think Debug or Info would be enough.

File: daemon/cmd/devices.go [hunk 36]
```diff
@@ -0,0 +1,337 @@
...
+	}
+
+	// Skip veth devices that don't have a default route.
+	// This is a workaround for kubernetes-in-docker. We want to avoid
+	// veth devices in general as they may be leftovers from another CNI.
+	if !hasDefaultRoute {
+		_, virtual := link.(*netlink.Veth)
+		if virtual {
+			log.WithField(logfields.Device, name).
+				Warn("Ignoring veth device as it has no default route")
```
Comment (pchaigno) [inline daemon/cmd/devices.go]: I think Debug would be enough here (it should be fairly obvious to users why we avoid veth devices).

File: daemon/cmd/devices.go [hunk 37]
```diff
@@ -0,0 +1,337 @@
...
+	// Skip bonding slave devices.
+	if link.Attrs().RawFlags&unix.IFF_SLAVE != 0 {
+		log.WithField(logfields.Device, name).Warn("Skipping bonded device")
+		return false
+	}
+
+	// Ignore L3 devices if we cannot support them.
+	if !l3DevOK && !mac.LinkHasMacAddr(link) {
+		log.WithField(logfields.Device, name).
+			Warn("Ignoring L3 device; >= 5.8 kernel is required.")
```
Comment (pchaigno) [inline daemon/cmd/devices.go]: Info would be enough here I think (users might expect L3 devices to be detected, but it's not as if it necessarily needs immediate attention).

File: daemon/cmd/devices.go [hunk 38]
```diff
@@ -0,0 +1,337 @@
...
+	option.Config.Devices = make([]string, 0, len(expandedDevices))
+	for dev := range expandedDevices {
+		option.Config.Devices = append(option.Config.Devices, dev)
+	}
+	sort.Strings(option.Config.Devices)
+	return nil
+}
+
+func areDevicesRequired() bool {
+	return len(option.Config.Devices) == 0 &&
```
Comment (pchaigno) [inline daemon/cmd/devices.go]: This part of the condition feels a bit unexpected to me given the function's name. Whether devices are preconfigured or not shouldn't impact whether they are required. I would just remove it.

**Review by pchaigno — CHANGES_REQUESTED** [review]
> > Could you break commit `daemon: Address review comments on device detection` and merge it in the respective commits it fixes/improves? Having it in a separate commit hinders reviewing and doesn't make sense once merged.
> 
> Ah I was just trying to make reviewing easier. I'll squash.

I didn't mean you should squash everything; that doesn't make reviews any easier ;-) 

If you're looking for guidance on how to split commits in pull requests, maybe a good starting point is https://kernelnewbies.org/PatchPhilosophy#How_to_break_up_changes. For this specific pull request, a good example is the code you moved from `daemon/cmd/kube_proxy_replacement{,_test}.go` to a new file; that move should be in its own commit, before the rest. It would help reviewers because we wouldn't have to re-review existing code that was just moved around.

**Comment by joamaki** [comment]
test-me-please

**Review by pchaigno — APPROVED** [review]

**Comment by joamaki** [comment]
test-1.16-netnext

**Comment by pchaigno** [comment]
I think the two tests failing in k8s-1.16-kernel-netnext are new, so likely a case of https://github.com/cilium/cilium/issues/15474. You can confirm by checking you don't have related changes (the changes those tests test) in your branch. Happy to help on Slack.

If that's confirmed, then I think we're good to go. The remaining cilium/agent review is for changes under `daemon/` but I'm familiar with the specific code you touched and I approved already.

**Comment by joamaki** [comment]
> I think the two tests failing in k8s-1.16-kernel-netnext are new, so likely a case of #15474. You can confirm by checking you don't have the related changes (the changes those tests test) in your branch. Happy to help on Slack.
> 
> If that's confirmed, then I think we're good to go. The remaining cilium/agent review is for changes under `daemon/` but I'm familiar with the specific code you touched and I approved already.

```
cilium % git diff upstream/master -- test/k8sT/Services.go|grep "Checks conn"
-       }, "Checks connectivity when skipping socket lb in pod ns", func() {
```

Yep, it's a new test.

**Comment by pchaigno** [comment]
> Yep, it's a new test.

Yep, but are the changes added with that test included in your branch?
