### PR TITLE
Ensure endpoint validation occurs before initial regeneration

### LINKED ISSUE #10278: CI: RuntimeKVStoreTest Consul KVStore: Found a "JoinEP: " in Cilium Logs
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/4097/testReport/junit/(root)/Suite-runtime/RuntimeKVStoreTest_Consul_KVStore/

Likely also seen in other test failures.

## Stacktrace
```
/home/jenkins/workspace/cilium-ginkgo_cilium_master/runtime-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:357
Found a "JoinEP: " in Cilium Logs
/home/jenkins/workspace/cilium-ginkgo_cilium_master/runtime-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:546
```
## Standard Output
```
⚠️  Found a "JoinEP: " in logs
⚠️  Found a "JoinEP: " in logs
⚠️  Found a "JoinEP: " in logs
Number of "context deadline exceeded" in logs: 0
⚠️  Number of "level=error" in logs: 6
⚠️  Number of "level=warning" in logs: 16
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 4
Top 5 errors/warnings:
Unable to release endpoint ID
Error while rewriting endpoint BPF program
endpoint regeneration failed
JoinEP: Failed to load program
generating BPF for endpoint failed, keeping stale directory.
```
## Standard Error
```
STEP: Starting Cilium with consul as kvstore
STEP: Restarting cilium-docker service
=== Test Finished at 2020-02-20T16:24:14Z====
===================== TEST FAILED =====================
cmd: sudo cilium endpoint list
Exitcode: 1 
Stdout:
 	 
Stderr:
 	 Error: cannot get endpoint list: Get http:///var/run/cilium/cilium.sock/v1/endpoint: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
	 Is the agent running?
	 
	 

cmd: sudo cilium status
Exitcode: 1 
Stdout:
 	 
Stderr:
 	 Get http:///var/run/cilium/cilium.sock/v1/healthz: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
	 Is the agent running?
	 

===================== Exiting AfterFailed =====================
STEP: Restarting Cilium


```

### LINKED ISSUE #10667: K8sDatapathConfig DirectRouting Check connectivity with automatic direct nodes routes
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/4319/testReport/Suite-k8s-1/11/K8sDatapathConfig_DirectRouting_Check_connectivity_with_automatic_direct_nodes_routes/

### LINKED ISSUE #10856: CI: K8sDatapathConfig MonitorAggregation Checks that monitor aggregation restricts notifications
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/18496/testReport/Suite-k8s-1/11/K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_restricts_notifications/

Cilium logs contain the following messages for coredns that seem related:
```
2020-04-03T14:27:49.939971063Z level=warning msg="JoinEP: Failed to load program" containerID=83dd70756c datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=957 error="Failed to replace Qdisc for lxceb5f17118667: Link not found" file-path=957_next/bpf_lxc.o identity=3583 ipv4=10.10.1.222 ipv6="f00d::a0c:0:0:5ad" k8sPodName=kube-system/coredns-687db6485c-65fst subsys=datapath-loader veth=lxceb5f17118667
2020-04-03T14:27:49.940044547Z level=error msg="Error while rewriting endpoint BPF program" containerID=83dd70756c datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=957 error="Failed to replace Qdisc for lxceb5f17118667: Link not found" identity=3583 ipv4=10.10.1.222 ipv6="f00d::a0c:0:0:5ad" k8sPodName=kube-system/coredns-687db6485c-65fst subsys=endpoint
```

## Stacktrace
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430
Failure while waiting for all cilium endpoints to reach ready state
Expected
    <*helpers.SSHMetaError | 0xc0001552e0>: Error: context deadline exceeded
Extended info: 	Cilium Pod: cilium-dctmj 	Endpoint: 381 	Identity: 3583	 State: ready
	Cilium Pod: cilium-dctmj 	Endpoint: 957 	Identity: 3583	 State: not-ready
	Cilium Pod: cilium-dctmj 	Endpoint: 1035 	Identity: 38794	 State: ready
	Cilium Pod: cilium-dctmj 	Endpoint: 2113 	Identity: 44755	 State: ready
	Cilium Pod: cilium-dctmj 	Endpoint: 2236 	Identity: 9564	 State: ready
	Cilium Pod: cilium-dctmj 	Endpoint: 2865 	Identity: 4	 State: ready
	Cilium Pod: cilium-jvkg9 	Endpoint: 187 	Identity: 38794	 State: ready
	Cilium Pod: cilium-jvkg9 	Endpoint: 331 	Identity: 44755	 State: ready
	Cilium Pod: cilium-jvkg9 	Endpoint: 745 	Identity: 4	 State: ready


to be nil
```

## Standard output
```
⚠️  Found a "JoinEP: " in logs
⚠️  Found a "JoinEP: " in logs
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 4
⚠️  Number of "level=warning" in logs: 24
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
Top 5 errors/warnings:
Unable to release endpoint ID
Unable to restore endpoint, ignoring
Error while rewriting endpoint BPF program
endpoint regeneration failed
Disabling NodePort's \
Cilium pods: [cilium-dctmj cilium-jvkg9]
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
Pod                          Ingress   Egress
test-k8s2-848b6f7864-8vb4j             
testds-rw59d                           
app2-dc85b4585-fmdq8                   
app1-798d4f944d-9fjxd                  
app3-68fb594d47-lfcg8                  
coredns-687db6485c-579m5               
coredns-687db6485c-65fst               
testclient-v7cm2                       
testclient-vz9jk                       
testds-6plh5                           
Cilium agent 'cilium-dctmj': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 31 Failed 0
Cilium agent 'cilium-jvkg9': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 21 Failed 0
```

## Standard error
<details><summary>Show standard error</summary>
<p>

```
STEP: Installing Cilium
STEP: Installing DNS Deployment
STEP: Restarting DNS Pods
STEP: Performing Cilium preflight check
STEP: Performing Cilium status preflight check
STEP: Performing Cilium controllers preflight check
STEP: Performing Cilium health check
Cilium is not ready yet: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-jvkg9': Exitcode: 255 
Stdout:
 	 
Stderr:
 	 Error: Cannot get status/probe: Put "http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe": dial unix /var/run/cilium/health.sock: connect: no such file or directory
	 
	 command terminated with exit code 255
	 

STEP: Performing Cilium status preflight check
STEP: Performing Cilium controllers preflight check
STEP: Performing Cilium health check
STEP: Performing Cilium status preflight check
STEP: Performing Cilium controllers preflight check
STEP: Performing Cilium health check
STEP: Performing Cilium status preflight check
STEP: Performing Cilium controllers preflight check
STEP: Performing Cilium health check
STEP: Performing Cilium service preflight check
STEP: Performing K8s service preflight check
STEP: Waiting for cilium-operator to be ready
STEP: Waiting for kube-dns to be ready
STEP: Running kube-dns preflight check
STEP: Performing K8s service preflight check
STEP: Making sure all endpoints are in ready state
=== Test Finished at 2020-04-03T14:32:21Z====
===================== TEST FAILED =====================
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE           NAME                               READY   STATUS    RESTARTS   AGE   IP              NODE   NOMINATED NODE
	 default             test-k8s2-848b6f7864-8vb4j         2/2     Running   0          5m    10.10.1.214     k8s2   <none>
	 default             testclient-v7cm2                   1/1     Running   0          5m    10.10.0.201     k8s1   <none>
	 default             testclient-vz9jk                   1/1     Running   0          5m    10.10.1.167     k8s2   <none>
	 default             testds-6plh5                       2/2     Running   0          5m    10.10.1.239     k8s2   <none>
	 default             testds-rw59d                       2/2     Running   0          5m    10.10.0.165     k8s1   <none>
	 external-ips-test   app1-798d4f944d-9fjxd              2/2     Running   0          55m   10.10.0.238     k8s1   <none>
	 external-ips-test   app2-dc85b4585-fmdq8               1/2     Running   0          55m   10.10.0.18      k8s1   <none>
	 external-ips-test   app3-68fb594d47-lfcg8              1/2     Running   0          55m   10.10.1.158     k8s2   <none>
	 external-ips-test   host-client-hw7q8                  1/1     Running   0          55m   192.168.36.12   k8s2   <none>
	 external-ips-test   host-client-k8z6r                  1/1     Running   0          55m   192.168.36.11   k8s1   <none>
	 external-ips-test   host-server-1-56c9467d4b-fwlvr     2/2     Running   0          55m   192.168.36.11   k8s1   <none>
	 external-ips-test   host-server-2-b8d89c58c-jrtmg      2/2     Running   0          55m   192.168.36.11   k8s1   <none>
	 kube-system         cilium-dctmj                       1/1     Running   1          5m    192.168.36.12   k8s2   <none>
	 kube-system         cilium-jvkg9                       1/1     Running   0          5m    192.168.36.11   k8s1   <none>
	 kube-system         cilium-operator-8677f5c767-tpcwk   1/1     Running   0          5m    192.168.36.12   k8s2   <none>
	 kube-system         coredns-687db6485c-579m5           1/1     Running   0          5m    10.10.1.98      k8s2   <none>
	 kube-system         etcd-k8s1                          1/1     Running   0          1h    192.168.36.11   k8s1   <none>
	 kube-system         kube-apiserver-k8s1                1/1     Running   0          1h    192.168.36.11   k8s1   <none>
	 kube-system         kube-controller-manager-k8s1       1/1     Running   0          1h    192.168.36.11   k8s1   <none>
	 kube-system         kube-scheduler-k8s1                1/1     Running   0          1h    192.168.36.11   k8s1   <none>
	 kube-system         log-gatherer-97wzg                 1/1     Running   0          1h    192.168.36.11   k8s1   <none>
	 kube-system         log-gatherer-kml6f                 1/1     Running   0          1h    192.168.36.12   k8s2   <none>
	 kube-system         log-gatherer-nl9k9                 1/1     Running   0          1h    192.168.36.13   k8s3   <none>
	 kube-system         registry-adder-7f6nb               1/1     Running   0          1h    192.168.36.13   k8s3   <none>
	 kube-system         registry-adder-cbrmj               1/1     Running   0          1h    192.168.36.12   k8s2   <none>
	 kube-system         registry-adder-sns97               1/1     Running   0          1h    192.168.36.11   k8s1   <none>
	 
Stderr:
 	 

Fetching command output from pods [cilium-dctmj cilium-jvkg9]
cmd: kubectl exec -n kube-system cilium-dctmj -- cilium bpf tunnel list
Exitcode: 0 
Stdout:
 	 TUNNEL              VALUE             
	 f00d::a0b:0:0:0:0   192.168.36.11:0   
	 10.10.0.0:0         192.168.36.11:0   
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-dctmj -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                       IPv6                 IPv4          STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                       
	 381        Disabled           Disabled          3583       k8s:io.cilium.k8s.policy.cluster=default          f00d::a0c:0:0:b5d2   10.10.1.98    ready       
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=coredns                                                  
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                      
	                                                            k8s:k8s-app=kube-dns                                                                             
	 957        Disabled           Disabled          3583       k8s:io.cilium.k8s.policy.cluster=default          f00d::a0c:0:0:5ad    10.10.1.222   not-ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=coredns                                                  
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                      
	                                                            k8s:k8s-app=kube-dns                                                                             
	 1035       Disabled           Disabled          38794      k8s:io.cilium.k8s.policy.cluster=default          f00d::a0c:0:0:c76b   10.10.1.167   ready       
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                  
	                                                            k8s:io.kubernetes.pod.namespace=default                                                          
	                                                            k8s:zgroup=testDSClient                                                                          
	 2113       Disabled           Disabled          44755      k8s:io.cilium.k8s.policy.cluster=default          f00d::a0c:0:0:bfd7   10.10.1.239   ready       
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                  
	                                                            k8s:io.kubernetes.pod.namespace=default                                                          
	                                                            k8s:zgroup=testDS                                                                                
	 2236       Disabled           Disabled          9564       k8s:io.cilium.k8s.policy.cluster=default          f00d::a0c:0:0:5486   10.10.1.214   ready       
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                  
	                                                            k8s:io.kubernetes.pod.namespace=default                                                          
	                                                            k8s:zgroup=test-k8s2                                                                             
	 2865       Disabled           Disabled          4          reserved:health                                   f00d::a0c:0:0:cdb6   10.10.1.9     ready       
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-jvkg9 -- cilium bpf tunnel list
Exitcode: 0 
Stdout:
 	 TUNNEL              VALUE             
	 10.10.1.0:0         192.168.36.12:0   
	 f00d::a0c:0:0:0:0   192.168.36.12:0   
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-jvkg9 -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                       IPv6                 IPv4          STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                       
	 187        Disabled           Disabled          38794      k8s:io.cilium.k8s.policy.cluster=default          f00d::a0b:0:0:bb7    10.10.0.201   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                              
	                                                            k8s:io.kubernetes.pod.namespace=default                                                      
	                                                            k8s:zgroup=testDSClient                                                                      
	 331        Disabled           Disabled          44755      k8s:io.cilium.k8s.policy.cluster=default          f00d::a0b:0:0:9a7a   10.10.0.165   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                              
	                                                            k8s:io.kubernetes.pod.namespace=default                                                      
	                                                            k8s:zgroup=testDS                                                                            
	 745        Disabled           Disabled          4          reserved:health                                   f00d::a0b:0:0:9531   10.10.0.61    ready   
	 
Stderr:
```
</p>
</details>

[f9f3b3b1_K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_restricts_notifications.zip](https://github.com/cilium/cilium/files/4436900/f9f3b3b1_K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_restricts_notifications.zip)

### LINKED ISSUE #11076: regeneration recovery failed due to Failed to replace Qdisc for lxc8a3af5d3166d
In a CI run, the managed etcd test failed:
```
/home/jenkins/workspace/Cilium-PR-K8s-GKE/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:357
Found a "JoinEP: " in Cilium Logs
```

This by itself is not very exceptional, but the following is concerning:
```
	   endpoint-4058-regeneration-recovery         never          3s ago       2       regeneration recovery failed   

```

This indicates that the endpoint was never built successfully.

The underlying error is:
```
cilium-test.log:2020-04-21T00:22:08.745442775Z level=warning msg="JoinEP: Failed to load program" containerID=50d8dc2cf0 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=4058 error="Failed to replace Qdisc for lxc8a3af5d3166d: Link not found" file-path=/var/run/cilium/state/4058/bpf_lxc.o identity=104 ipv4=10.52.224.159 ipv6= k8sPodName=kube-system/coredns-cc45bff6b-nn9x9 subsys=datapath-loader veth=lxc8a3af5d3166d
```
[test_results_Cilium-PR-K8s-GKE_465_BDD-Test-PR.zip](https://github.com/cilium/cilium/files/4508802/test_results_Cilium-PR-K8s-GKE_465_BDD-Test-PR.zip)

### LINKED ISSUE #11645: CI: K8sIdentity Identity expiration Expiration of CiliumIdentity: Unable to restore endpoint (interface lxc... could not be found)
## Suite-k8s-1.18.K8sIdentity Identity expiration Expiration of CiliumIdentity

Initial triage suggests that this is a test pollution issue from Bookinfo tests, and is likely to affect other tests depending on test ordering.

https://jenkins.cilium.io/job/Cilium-PR-K8s-newest-kernel-4.9/318/testReport/junit/Suite-k8s-1/18/K8sIdentity_Identity_expiration_Expiration_of_CiliumIdentity/
[test_results_Cilium-PR-K8s-newest-kernel-4.9_318_BDD-Test-PR.zip](https://github.com/cilium/cilium/files/4664454/test_results_Cilium-PR-K8s-newest-kernel-4.9_318_BDD-Test-PR.zip)

### Stacktrace
```
/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:387
Found 1 Cilium logs matching list of errors that must be investigated
/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:385
```
### Standard Output
```
⚠️  Found a "JoinEP: " in logs
Number of "context deadline exceeded" in logs: 0
⚠️  Number of "level=error" in logs: 6
⚠️  Number of "level=warning" in logs: 50
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
Top 5 errors/warnings:
removing identity not added to the identity manager!
Error while rewriting endpoint BPF program
before filtering labels during regenerating restored endpoint
endpoint regeneration failed
Mutation detector is enabled, this will result in memory leakage.
Cilium pods: [cilium-lmkhb cilium-rpnbj]
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
Pod                             Ingress   Egress
hubble-cli-j5n24                          
hubble-cli-tw429                          
hubble-relay-58c8798f47-xhsgn             
coredns-7964865f77-wxxxc                  
Cilium agent 'cilium-lmkhb': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 26 Failed 0
Cilium agent 'cilium-rpnbj': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 19 Failed 0
```
### Standard Error
```
08:37:41 STEP: Running BeforeAll block for K8sIdentity
08:37:41 STEP: Ensuring the namespace kube-system exists
08:37:41 STEP: Deleting cep [details-v1-55cf6d74d-k98wn,reviews-v1-6948677f85-mnb8v,reviews-v2-77c4d85c6c-8kzqk] in namespace default
08:37:41 STEP: Waiting for 3 deletes to return (details-v1-55cf6d74d-k98wn,reviews-v1-6948677f85-mnb8v,reviews-v2-77c4d85c6c-8kzqk)
08:37:41 STEP: Unable to delete cep details-v1-55cf6d74d-k98wn with 'kubectl -n default delete cep details-v1-55cf6d74d-k98wn': Exitcode: 1 
Stdout:
 	 
Stderr:
 	 Error from server (NotFound): ciliumendpoints.cilium.io "details-v1-55cf6d74d-k98wn" not found
	 

08:37:41 STEP: Installing Cilium
08:37:42 STEP: Waiting for Cilium to become ready
08:37:42 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
08:37:47 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
08:37:52 STEP: Cilium DaemonSet not ready yet: only 1 of 2 desired pods are ready
08:37:57 STEP: Cilium DaemonSet not ready yet: only 1 of 2 desired pods are ready
08:38:02 STEP: Number of ready Cilium pods: 2
08:38:02 STEP: Installing DNS Deployment
08:38:02 STEP: Restarting DNS Pods
08:38:09 STEP: Validating Cilium Installation
08:38:09 STEP: Performing Cilium controllers preflight check
08:38:09 STEP: Performing Cilium status preflight check
08:38:09 STEP: Performing Cilium health check
08:38:12 STEP: Performing Cilium service preflight check
08:38:12 STEP: Performing K8s service preflight check
08:38:12 STEP: Waiting for cilium-operator to be ready
08:38:12 STEP: Waiting for kube-dns to be ready
08:38:12 STEP: Running kube-dns preflight check
08:38:15 STEP: Performing K8s service preflight check
08:38:16 STEP: Making sure all endpoints are in ready state
08:38:17 STEP: Creating unused CiliumIdentity
08:38:17 STEP: Waiting for CiliumIdentity to be garbage collected
=== Test Finished at 2020-05-21T08:38:22Z====
08:38:22 STEP: Running JustAfterEach block for K8sIdentity
FAIL: Found 1 Cilium logs matching list of errors that must be investigated
===================== TEST FAILED =====================
08:38:22 STEP: Running AfterFailed block for K8sIdentity
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE     NAME                               READY   STATUS             RESTARTS   AGE   IP              NODE   NOMINATED NODE   READINESS GATES
	 kube-system   cilium-lmkhb                       1/1     Running            0          41s   192.168.36.12   k8s2   <none>           <none>
	 kube-system   cilium-operator-6c758b54bf-68sbw   1/1     Running            0          41s   192.168.36.12   k8s2   <none>           <none>
	 kube-system   cilium-rpnbj                       1/1     Running            0          41s   192.168.36.11   k8s1   <none>           <none>
	 kube-system   coredns-7964865f77-wxxxc           1/1     Running            0          21s   10.0.0.10       k8s2   <none>           <none>
	 kube-system   etcd-k8s1                          1/1     Running            0          17m   192.168.36.11   k8s1   <none>           <none>
	 kube-system   hubble-cli-j5n24                   0/1     CrashLoopBackOff   5          13m   10.0.1.131      k8s1   <none>           <none>
	 kube-system   hubble-cli-tw429                   0/1     CrashLoopBackOff   5          13m   10.0.0.131      k8s2   <none>           <none>
	 kube-system   hubble-relay-58c8798f47-xhsgn      1/1     Running            0          13m   10.0.0.229      k8s2   <none>           <none>
	 kube-system   kube-apiserver-k8s1                1/1     Running            0          17m   192.168.36.11   k8s1   <none>           <none>
	 kube-system   kube-controller-manager-k8s1       1/1     Running            0          17m   192.168.36.11   k8s1   <none>           <none>
	 kube-system   kube-proxy-mbkzb                   1/1     Running            0          17m   192.168.36.11   k8s1   <none>           <none>
	 kube-system   kube-proxy-szqxv                   1/1     Running            0          16m   192.168.36.12   k8s2   <none>           <none>
	 kube-system   kube-scheduler-k8s1                1/1     Running            0          17m   192.168.36.11   k8s1   <none>           <none>
	 kube-system   log-gatherer-69z26                 1/1     Running            0          15m   192.168.36.12   k8s2   <none>           <none>
	 kube-system   log-gatherer-wbfqv                 1/1     Running            0          15m   192.168.36.11   k8s1   <none>           <none>
	 kube-system   registry-adder-9jr2j               1/1     Running            0          15m   192.168.36.11   k8s1   <none>           <none>
	 kube-system   registry-adder-ps2ql               1/1     Running            0          15m   192.168.36.12   k8s2   <none>           <none>
	 
Stderr:
 	 

Fetching command output from pods [cilium-lmkhb cilium-rpnbj]
cmd: kubectl exec -n kube-system cilium-lmkhb -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                       IPv6       IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                            
	 2          Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s2                                                ready   
	                                                            reserved:host                                                                     
	 177        Disabled           Disabled          4          reserved:health                                   fd00::98   10.0.0.197   ready   
	 1017       Disabled           Disabled          1797       k8s:io.cilium.k8s.policy.cluster=default          fd00::b    10.0.0.10    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=coredns                                   
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                       
	                                                            k8s:k8s-app=kube-dns                                                              
	 1623       Disabled           Disabled          2044       k8s:io.cilium.k8s.policy.cluster=default          fd00::7c   10.0.0.131   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                   
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                       
	                                                            k8s:k8s-app=hubble-cli                                                            
	 3562       Disabled           Disabled          56769      k8s:io.cilium.k8s.policy.cluster=default          fd00::82   10.0.0.229   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                   
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                       
	                                                            k8s:k8s-app=hubble-relay                                                          
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-rpnbj -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                       IPv6        IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                             
	 269        Disabled           Disabled          2044       k8s:io.cilium.k8s.policy.cluster=default          fd00::172   10.0.1.131   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                    
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                        
	                                                            k8s:k8s-app=hubble-cli                                                             
	 1342       Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s1                                                 ready   
	                                                            k8s:node-role.kubernetes.io/master                                                 
	                                                            reserved:host                                                                      
	 4048       Disabled           Disabled          4          reserved:health                                   fd00::16b   10.0.1.52    ready   
	 
Stderr:
 	 

===================== Exiting AfterFailed =====================
08:39:13 STEP: Running AfterEach for block EntireTestsuite

08:39:13 STEP: Running AfterAll block for K8sIdentity
```

### PR DESCRIPTION
**Pull request by tgraf**
Due to a performance optimization, validateEndpoint() was changed to use
the pod store instad of contacting the apiserver directly. This required
to make the validation async to wait until the pod cache is available.

This change however caused the endpoint to be exposed and regenerated
before the endpoint was fully validated. This in turn caused the
validation to occur while the regeneration was being performed. When the
validation then failed, the endpoint was deleted while the endpoint was
being regenerated, causing the endpoint to fail with a "JoinEP" message
in the logs.

This commit requires the endpoint to be validated before exposure and
initial regeneration.

This problem only exists in master. No need to backport.

Fixes: #11645
Fixes: #11076
Fixes: #10856
Fixes: #10667
Fixes: #10278
Fixes: 9975bba1637 ("pkg/endpoint: fetch pod and namespace labels from local stores")

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by tgraf** [comment]
restart-1.11

File: daemon/cmd/daemon.go [hunk 1]
```diff
@@ -395,6 +387,20 @@ func NewDaemon(ctx context.Context, dp datapath.Datapath) (*Daemon, *endpointRes
 	treatRemoteNodeAsHost := option.Config.AlwaysAllowLocalhost() && !option.Config.EnableRemoteNodeIdentity
 	policyApi.InitEntities(option.Config.ClusterName, treatRemoteNodeAsHost)
 
+	d.k8sCachesSynced = d.k8sWatcher.InitK8sSubsystem()
```
Comment (christarazi) [inline daemon/cmd/daemon.go:399]: Not sure if I'm missing something here, but shouldn't we guard this statement by checking if K8s is enabled? What would happen if K8s is disabled?

**Review by christarazi — COMMENTED** [review]
The code looks good to me, besides one question that I have.

File: daemon/cmd/daemon.go (hunk 1 above)
Comment (tgraf) [reply daemon/cmd/daemon.go:399]: It was not protected before which is why I've kept it this way. The check is embedded in `EnableK8sWatcher()`.

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please
