### PR TITLE
Fix issue where --enable-remote-node-identity=false causes policy drops

### LINKED ISSUE #10702: Enabling remote-node-identity then disabling doesn't properly disable it
Cilium: v1.7.1
Kernel: Ubuntu 4.15 AWS

We observed in a community report that if Cilium was deployed with the remote node identity option enabled, then redeployed to disable the option, traffic would continue to be classified as remote-node in cilium monitor:

```
xx drop (Policy denied) flow 0x4ca54ca5 to endpoint 4017, identity 6->28806: 192.168.138.220:36473 -> 192.168.128.41:53 udp
```

Interestingly, the source identity shows up as "host" in the userspace view of the ipcache:

```
$ cilium map get cilium_ipcache
...
192.168.138.220/32   1 0 0.0.0.0             sync
```

Debuginfo reported from cilium agent:
```
"enable-remote-node-identity:false"
```

On this kernel, we cannot fetch ipcache directly from the kernel:

```
> Error while running 'cilium bpf ipcache list':  exit status 1                 
                                                                                                                                                                              
error dumping contents of map: Unable to get next key from map with file descriptor 5: errno 524
```

However the identity comes from somewhere, either through a tunnel from the source node or from ipcache.

### PR DESCRIPTION
**Pull request by joestringer**
This PR fixes #10702 by reworking the `--enable-remote-node-identity=false` behaviour to ensure that it injects BPF policymap entries that allow traffic from the remote-node identity if the policy generation would otherwise generate BPF policymap entries that allow traffic from the Host identity. 

In other words:
* If `--enable-remote-node-identity=false`, then remote identity traffic will be allowed by default, like in v1.6.
* If `--enable-remote-node-identity=true`, then remote identity traffic will be dropped by default, like in existing v1.7 releases.

Consider reviewing commit-by-commit. It is structured as follows:
* Patch 1 refactors some L7 wildcard handling to make it more generic for host and remote node identity wildcarding.
* Patch 2 is the core policy generation logic change. It's pretty simple but builds on the existing policy generation logic to handle the allow of the remoteNode identity both for the automatic allow from host case, and also when explicit from-host policy is injected.
* Patches 3-5 refactor and extend the testsuite to validate that patch 2 fixes the issue. Note that these tests fail on master.
* Patch 6 attempts to incrementally improve the upgrade / policy docs to make this behaviour more clear.

Patch 2 description for reference:

    policy: Treat remote-node as host in resolution

    In the --enable-remote-node-identity=false mode, the policy behaviour is
    intended to be identical to Cilium v1.6 or earlier, which is to say that
    if a remote node sends traffic towards a pod on the local node, then
    that traffic should be allowed.

    Since commit 28dc941544f1 ("bpf: Map HOST_ID to REMOTE_NODE_ID when
    encapsulating"), we have propagated the source identity from remote
    nodes as the remote node identity rather than the host, which breaks the
    above policy expectations because policy is looked up using this new
    remote-node identity.

    We could entirely disable the remote-node identity, but we want to
    provide a path whereby eventually all users are able to apply separate
    policy for whether they allow traffic from the localhost (where the
    typical use can is to handle kubelet health checks) vs. other nodes
    (where the typical case is hostNetworking pods on other nodes). This may
    allow some users to tighten their security posture.

    With this approach, the policy handling on the datapath will allow
    traffic from remote nodes if the relevant daemon options are configured,
    but in visibility tools like cilium monitor or Hubble, the actual
    identity used will be propagated. For users to migrate from
    `--enable-remote-node-identity=false` to setting this option to true,
    they can first deploy with it set to false, then monitor their traffic,
    craft their policies, and subsequently perform a migration step to turn
    this flag on. This can be iterated in a loop separately from the concern
    of upgrading their Cilium version.

Supersedes: https://github.com/cilium/cilium/pull/10951
Fixes: https://github.com/cilium/cilium/issues/10702

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-focus "Multi-node policy"

File: pkg/policy/l4_test.go [hunk 1]
```diff
@@ -48,8 +49,9 @@ func (s *PolicyTestSuite) TestCreateL4Filter(c *C) {
 		// Regardless of ingress/egress, we should end up with
 		// a single L7 rule whether the selector is wildcarded
 		// or if it is based on specific labels.
-		filter, err := createL4IngressFilter(testPolicyContext, eps, false, portrule, tuple, tuple.Protocol, nil)
+		filter, err := createL4IngressFilter(testPolicyContext, eps, nil, portrule, tuple, tuple.Protocol, nil)
 		c.Assert(err, IsNil)
+		c.Logf("JOE: %+v", option.Config.EnableRemoteNodeIdentity)
```
Comment (joestringer) [inline pkg/policy/l4_test.go]:
```suggestion
```

File: pkg/policy/l4_test.go [hunk 2]
```diff
@@ -22,6 +22,7 @@ import (
 	"github.com/cilium/cilium/api/v1/models"
 	"github.com/cilium/cilium/pkg/checker"
 	"github.com/cilium/cilium/pkg/labels"
+	"github.com/cilium/cilium/pkg/option"
```
Comment (joestringer) [inline pkg/policy/l4_test.go]:
```suggestion
```

**Comment by joestringer** [comment]
test-me-please

File: pkg/policy/rule.go [hunk 3]
```diff
@@ -327,7 +327,10 @@ func mergeIngress(policyCtx PolicyContext, ctx *SearchContext, fromEndpoints api
 	// restrictions on these endpoints into L7 allow-all so that the
 	// traffic is always allowed, but is also always redirected through the
 	// proxy
-	hostWildcardL7 := option.Config.AlwaysAllowLocalhost()
+	hostWildcardL7 := make([]string, 0, 2)
```
Comment (aanm) [inline pkg/policy/rule.go:330]: why 2? :thinking:

Comment (aanm) [reply pkg/policy/rule.go:330]: ah in this commit makes sense.

**Review by aanm — APPROVED** [review]

File: pkg/policy/rule.go (hunk 3 above)
Comment (joestringer) [reply pkg/policy/rule.go:330]: Yeah strictly speaking this would set to 1 first in the initial refactor patch then 2 in the patch that adds the second entry, I just didn't bother making the two changes since it doesn't make a big difference.

File: pkg/policy/l4.go [hunk 4]
```diff
@@ -576,11 +576,13 @@ func createL4IngressFilter(policyCtx PolicyContext, fromEndpoints api.EndpointSe
...
 	// then wildcard Host at L7.
-	if !rule.Rules.IsEmpty() && hostWildcardL7 {
+	if !rule.Rules.IsEmpty() && len(hostWildcardL7) > 0 {
 		for cs := range filter.L7RulesPerSelector {
-			if cs.Selects(identity.ReservedIdentityHost) {
-				hostSelector := api.ReservedEndpointSelectors[labels.IDNameHost]
-				filter.cacheIdentitySelector(hostSelector, policyCtx.GetSelectorCache())
+			for _, name := range hostWildcardL7 {
+				if cs.Selects(identity.ReservedIdentityHost) {
+					selector := api.ReservedEndpointSelectors[name]
```
Comment (jrajahalme) [inline pkg/policy/l4.go:583]: The name range could be inside the `cs.Selects()` as it does not depend on the name?

File: test/k8sT/Policies.go [hunk 5]
```diff
@@ -961,6 +963,133 @@ var _ = Describe("K8sPolicyTest", func() {
...
+				cnpFromEntitiesHost = helpers.ManifestGet(kubectl.BasePath(), "cnp-from-entities-host.yaml")
+				cnpFromEntitiesRemoteNode = helpers.ManifestGet(kubectl.BasePath(), "cnp-from-entities-remote-node.yaml")
+				k8s1Name, _ = kubectl.GetNodeInfo(helpers.K8s1)
+				k8s2Name, _ = kubectl.GetNodeInfo(helpers.K8s2)
+				_, k8s1PodIP = kubectl.GetPodOnNodeWithOffset(k8s1Name, testDS, 0)
+				_, k8s2PodIP = kubectl.GetPodOnNodeWithOffset(k8s2Name, testDS, 0)
+			})
+
+			validateNodeConnectivity := func(expectHostSuccess, expectRemoteNodeSuccess bool) {
+				By("Checking connectivity from k8s1 to local pod")
```
Comment (jrajahalme) [inline test/k8sT/Policies.go]: -> "Checking connectivity from local host to k8s1"

File: test/k8sT/Policies.go [hunk 6]
```diff
@@ -961,6 +963,133 @@ var _ = Describe("K8sPolicyTest", func() {
...
+				res, err := kubectl.ExecInHostNetNS(context.TODO(), k8s1Name,
+					helpers.CurlFail(k8s1PodIP))
+				Expect(err).To(BeNil(), "Cannot run curl in host netns")
+				ExpectWithOffset(1, res).To(getMatcher(expectHostSuccess),
+					"HTTP ingress connectivity to pod %q from local host", k8s1PodIP)
+
+				By("Checking connectivity from k8s1 to k8s2 pod")
+				res, err = kubectl.ExecInHostNetNS(context.TODO(), k8s1Name,
```
Comment (jrajahalme) [inline test/k8sT/Policies.go:1040]: -> "Checking connectivity from remote node to k8s2"

File: test/k8sT/Policies.go [hunk 7]
```diff
@@ -961,6 +963,133 @@ var _ = Describe("K8sPolicyTest", func() {
...
+					helpers.CurlFail(k8s2PodIP))
+				Expect(err).To(BeNil(), "Cannot run curl in host netns")
+				ExpectWithOffset(1, res).To(getMatcher(expectRemoteNodeSuccess),
+					"HTTP ingress connectivity to pod %q from remote node", k8s1PodIP)
+			}
```
Comment (jrajahalme) [inline test/k8sT/Policies.go:1045]: -> k8s2PodIP

File: test/k8sT/Policies.go [hunk 8]
```diff
@@ -961,6 +963,133 @@ var _ = Describe("K8sPolicyTest", func() {
...
+				ExpectWithOffset(1, err).Should(BeNil(),
+					"policy %s cannot be applied in %q namespace", file, testNamespace)
+			}
+
+			Context("with remote-node identity disabled", func() {
+				BeforeAll(func() {
+					By("Reconfiguring Cilium to disable remote-node identity")
+					newCfg := map[string]string{
+						"global.remoteNodeIdentity": "false",
+					}
```
Comment (jrajahalme) [inline test/k8sT/Policies.go:1059]: So this is enabled by default in demonCfg?

File: test/k8sT/Policies.go [hunk 9]
```diff
@@ -961,6 +963,133 @@ var _ = Describe("K8sPolicyTest", func() {
...
+					for k, v := range daemonCfg {
+						newCfg[k] = v
+					}
```
Comment (jrajahalme) [inline test/k8sT/Policies.go:1062]: This relies on `global.remoteNodeIdentity` not being set in `demonCfg`?

**Review by jrajahalme — APPROVED** [review]
Only small nits ;-)

File: test/k8sT/Policies.go (hunk 5 above)
Comment (joestringer) [reply test/k8sT/Policies.go]: I would interpret this to mean that you're connecting to the k8s1 node, but that's not what we're doing. We're testing ingress from k8s1 node into a local pod.

Comment (joestringer) [reply test/k8sT/Policies.go]: I guess `"Checking connectivity from local host to k8s1 pod"` might be a bit more clear, but is the current description unclear in some way?

Comment (joestringer) [reply test/k8sT/Policies.go]: oh, I see... `ExecInHostNetNS` doesn't actually declare which host it runs on. I can fix this up.

File: test/k8sT/Policies.go (hunk 8 above)
Comment (joestringer) [reply test/k8sT/Policies.go:1059]: Yeah. If we decided to change this default we'd need to update these tests. I guess we could add similar beforeall/afterall logic to the other test as well to make sure that it's configured in the way that the test expects. That's an easy fix.

File: test/k8sT/Policies.go (hunk 5 above)
Comment (joestringer) [reply test/k8sT/Policies.go]: Never mind, we explicitly pass `k8s1` as the host to run on in the `ExecInHostNetNS()` call. So it is guaranteed to call from k8s1 to k8s1pod. So I think it's accurate and should not be confusing?

**Comment by joestringer** [comment]
Existing CI runs were all green. Here's my incremental diff, I will run the CI once more.

```
diff --git a/test/k8sT/Policies.go b/test/k8sT/Policies.go
index 21c8b2847a7e..bb22d5aae6dd 100644
--- a/test/k8sT/Policies.go
+++ b/test/k8sT/Policies.go
@@ -1023,20 +1023,25 @@ var _ = Describe("K8sPolicyTest", func() {
                                _, k8s2PodIP = kubectl.GetPodOnNodeWithOffset(k8s2Name, testDS, 0)
                        })

+                       AfterAll(func() {
+                               By("Redeploying Cilium with default configuration")
+                               RedeployCilium(kubectl, ciliumFilename, daemonCfg)
+                       })
+
                        validateNodeConnectivity := func(expectHostSuccess, expectRemoteNodeSuccess bool) {
-                               By("Checking connectivity from k8s1 to local pod")
+                               By("Checking ingress connectivity from k8s1 node to k8s1 pod (host)")
                                res, err := kubectl.ExecInHostNetNS(context.TODO(), k8s1Name,
                                        helpers.CurlFail(k8s1PodIP))
                                Expect(err).To(BeNil(), "Cannot run curl in host netns")
                                ExpectWithOffset(1, res).To(getMatcher(expectHostSuccess),
                                        "HTTP ingress connectivity to pod %q from local host", k8s1PodIP)

-                               By("Checking connectivity from k8s1 to k8s2 pod")
+                               By("Checking ingress connectivity from k8s1 node to k8s2 pod (remote-node)")
                                res, err = kubectl.ExecInHostNetNS(context.TODO(), k8s1Name,
                                        helpers.CurlFail(k8s2PodIP))
                                Expect(err).To(BeNil(), "Cannot run curl in host netns")
                                ExpectWithOffset(1, res).To(getMatcher(expectRemoteNodeSuccess),
-                                       "HTTP ingress connectivity to pod %q from remote node", k8s1PodIP)
+                                       "HTTP ingress connectivity to pod %q from remote node", k8s2PodIP)
                        }

                        importPolicy := func(file, name string) {
@@ -1058,11 +1063,6 @@ var _ = Describe("K8sPolicyTest", func() {
                                        RedeployCilium(kubectl, ciliumFilename, newCfg)
:...skipping...
diff --git a/pkg/policy/l4.go b/pkg/policy/l4.go
index 070fc902e0e6..b9a919389d0a 100644
--- a/pkg/policy/l4.go
+++ b/pkg/policy/l4.go
@@ -578,8 +578,8 @@ func createL4IngressFilter(policyCtx PolicyContext, fromEndpoints api.EndpointSe
        // then wildcard Host at L7.
        if !rule.Rules.IsEmpty() && len(hostWildcardL7) > 0 {
                for cs := range filter.L7RulesPerSelector {
-                       for _, name := range hostWildcardL7 {
-                               if cs.Selects(identity.ReservedIdentityHost) {
+                       if cs.Selects(identity.ReservedIdentityHost) {
+                               for _, name := range hostWildcardL7 {
                                        selector := api.ReservedEndpointSelectors[name]
                                        filter.cacheIdentitySelector(selector, policyCtx.GetSelectorCache())
                                }
diff --git a/test/k8sT/Policies.go b/test/k8sT/Policies.go
index 21c8b2847a7e..bb22d5aae6dd 100644
--- a/test/k8sT/Policies.go
+++ b/test/k8sT/Policies.go
@@ -1023,20 +1023,25 @@ var _ = Describe("K8sPolicyTest", func() {
                                _, k8s2PodIP = kubectl.GetPodOnNodeWithOffset(k8s2Name, testDS, 0)
                        })

+                       AfterAll(func() {
+                               By("Redeploying Cilium with default configuration")
+                               RedeployCilium(kubectl, ciliumFilename, daemonCfg)
+                       })
+
                        validateNodeConnectivity := func(expectHostSuccess, expectRemoteNodeSuccess bool) {
-                               By("Checking connectivity from k8s1 to local pod")
+                               By("Checking ingress connectivity from k8s1 node to k8s1 pod (host)")
                                res, err := kubectl.ExecInHostNetNS(context.TODO(), k8s1Name,
                                        helpers.CurlFail(k8s1PodIP))
                                Expect(err).To(BeNil(), "Cannot run curl in host netns")
                                ExpectWithOffset(1, res).To(getMatcher(expectHostSuccess),
                                        "HTTP ingress connectivity to pod %q from local host", k8s1PodIP)

-                               By("Checking connectivity from k8s1 to k8s2 pod")
+                               By("Checking ingress connectivity from k8s1 node to k8s2 pod (remote-node)")
                                res, err = kubectl.ExecInHostNetNS(context.TODO(), k8s1Name,
                                        helpers.CurlFail(k8s2PodIP))
                                Expect(err).To(BeNil(), "Cannot run curl in host netns")
                                ExpectWithOffset(1, res).To(getMatcher(expectRemoteNodeSuccess),
-                                       "HTTP ingress connectivity to pod %q from remote node", k8s1PodIP)
+                                       "HTTP ingress connectivity to pod %q from remote node", k8s2PodIP)
                        }

                        importPolicy := func(file, name string) {
@@ -1058,11 +1063,6 @@ var _ = Describe("K8sPolicyTest", func() {
                                        RedeployCilium(kubectl, ciliumFilename, newCfg)
                                })

-                               AfterAll(func() {
-                                       By("Reconfiguring Cilium to enable remote-node identity")
-                                       RedeployCilium(kubectl, ciliumFilename, daemonCfg)
-                               })
-
                                It("Allows from all hosts with cnp fromEntities host policy", func() {
                                        By("Installing fromEntities host policy")
                                        importPolicy(cnpFromEntitiesHost, "from-entities-host")
@@ -1073,6 +1073,17 @@ var _ = Describe("K8sPolicyTest", func() {
                        })

                        Context("with remote-node identity enabled", func() {
+                               BeforeAll(func() {
+                                       By("Reconfiguring Cilium to enable remote-node identity")
+                                       newCfg := map[string]string{
+                                               "global.remoteNodeIdentity": "true",
+                                       }
+                                       for k, v := range daemonCfg {
+                                               newCfg[k] = v
+                                       }
+                                       RedeployCilium(kubectl, ciliumFilename, newCfg)
+                               })
+
                                It("Validates fromEntities remote-node policy", func() {
                                        By("Installing default-deny ingress policy")
                                        importPolicy(cnpDenyIngress, "default-deny-ingress")
```

**Comment by joestringer** [comment]
test-me-please

**Comment by danwent** [comment]
docs look good, chatted with joe about this in slack.

File: pkg/policy/api/entity.go [hunk 10]
```diff
@@ -101,12 +101,19 @@ func (s EntitySlice) GetAsEndpointSelectors() EndpointSelectorSlice {
...
 		endpointSelectorHost,
 		endpointSelectorRemoteNode,
 		endpointSelectorInit,
 		endpointSelectorUnmanaged,
 		NewESFromLabels(labels.NewLabel(k8sapi.PolicyLabelCluster, clusterName, labels.LabelSourceK8s)),
 	}
+
+	hostSelectors := make(EndpointSelectorSlice, 0, 2)
+	hostSelectors = append(hostSelectors, endpointSelectorHost)
+	if treatRemoteNodeAsHost {
```
Comment (tgraf) [inline pkg/policy/api/entity.go:115]: Very nicely solved.

**Review by tgraf — APPROVED** [review]
Awesome fix!

There is one additional aspect that we need to look at in this context. bbfabcfdafca0ffe0d130eff01f096835409c229 has done the following:

```
@@ -289,19 +289,12 @@ func (m *Manager) NodeUpdated(n node.Node) {
        }

        for _, address := range n.IPAddresses {
-               // Map the Cilium internal IP to the reachable node IP so it
-               // can be routed via the overlay. Routing via overlay is always
-               // done via public v4 address hence n.GetNodeIP(false).
-               if address.Type == addressing.NodeCiliumInternalIP {
-                       nodeIP = n.GetNodeIP(false)
-                       if address.IP.To4() != nil {
-                               nodeIP4 = nodeIP
-                       }
-               } else {
-                       continue
+               var tunnelIP net.IP
+               if address.Type == addressing.NodeCiliumInternalIP || option.Config.EncryptNode {
+                       tunnelIP = nodeIP
                }

-               isOwning := ipcache.IPIdentityCache.Upsert(address.IP.String(), nodeIP, n.EncryptionKey, nil, ipcache.Identity{
+               isOwning := ipcache.IPIdentityCache.Upsert(address.IP.String(), tunnelIP, n.EncryptionKey, nil, ipcache.Identity{
```

This is technically correct but it does lead to a change in what IPs are being considered host or remote-node. The implication of this is that while a node IP may have been considered world before, with CIDR rules coming into play, they are now being treated as host/remote-node identity and CIDR rules are no longer respected.

If the remote-node identity is disabled, they are treated as host and thus allowed. It means that we are actually more permissive. One could argue it is more consistent but it's also a change.

With remote node identities enabled, nodes *have* to be whitelisted using remote-node identity now. This is also more consistent and it is definitely easier to do so via the identity compared to CIDR blocks.

**Comment by joestringer** [comment]
Hit https://github.com/cilium/cilium/issues/11024 , but I don't see how it can be related to the incremental changes I did since the last run. Also only affects net-next runs.

**Comment by joestringer** [comment]
test-focus K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with XDP

**Comment by joestringer** [comment]
> If the remote-node identity is disabled, they are treated as host and thus allowed. It means that we are actually more permissive. One could argue it is more consistent but it's also a change.

This is a valid concern, let's follow up on this separately. I think one big aspect is how we want things to work longer-term so we can reduce operational complexity, and the other big aspect is that assuming we stay with the current behaviour, how we ensure a smooth transition for existing users.
