### PR TITLE
gateway-api: fixed RequestRedirect picks wrong port with multiple listeners

### LINKED ISSUE #29099: Gateway API RequestRedirect picks wrong port with multiple listeners
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When setting a `RequestRedirect` filter in an HTTPRoute the response sends back the port of the 1st listener defined in the gateway no matter what port or protocol was used. This causes redirects to be incorrectly forwarded eg. from HTTPS on 443 to HTTPS on port 80 as this was the first listener set.

### Cilium Version

v1.15.0-pre.1

### Kernel Version

6.1.0-rpi4-rpi-v8

### Kubernetes Version

v1.26.10

### Sysdump

_No response_

### Relevant log output
Config:

```yaml
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: go2rtc
spec:
  gatewayClassName: cilium
  listeners:
  - name: http
    protocol: HTTP
    port: 80
  - name: https
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate 
      certificateRefs:
      - kind: Secret
        group: ""
        name: go2rtc-tls
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: go2rtc-public
spec:
  parentRefs:
  - name: go2rtc
  hostnames:
  - "blinken.rpi.maartje.dev"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    filters:
      - type: RequestRedirect
        requestRedirect:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /home
  - matches:
    - path:
        type: PathPrefix
        value: /home
      method: GET
    backendRefs:
    - name: go2rtc-home
      port: 80

```
Curl output:
```
maartje@maartje-XPS-9315 ~ [SIGINT]> curl https://blinken.rpi.maartje.dev -v
> GET / HTTP/1.1
> Host: blinken.rpi.maartje.dev
> User-Agent: curl/7.81.0
> Accept: */*
> 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< location: https://blinken.rpi.maartje.dev:80/home
< date: Fri, 10 Nov 2023 10:12:31 GMT
< server: envoy
< content-length: 0
< 
* Connection #0 to host blinken.rpi.maartje.dev left intact
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by chaunceyjiang**
Fixes: #29099

If RequestRedirect does not specify a port. The port of the listener is used by default.

```release-note
gateway-api: fixed RequestRedirect picks wrong port with multiple listeners
```

### CODE REVIEW

File: operator/pkg/model/ingestion/gateway.go [hunk 1]
```diff
@@ -480,11 +480,18 @@ func toHTTPRequestRedirectFilter(redirect *gatewayv1.HTTPRequestRedirectFilter)
 			pathModifier.Prefix = *redirect.Path.ReplacePrefixMatch
 		}
 	}
+	// If the redirectPort is not specified, use the listener's port
+	var redirectPort *int32
+	if redirect.Port == nil {
+		redirectPort = model.AddressOf(int32(listener.Port))
+	} else {
+		redirectPort = (*int32)(redirect.Port)
+	}
```
Comment (chaunceyjiang) [inline operator/pkg/model/ingestion/gateway.go:493]: The `root cause`  of the issue is here .

https://github.com/cilium/cilium/blob/7c7ae03aa95620c4b022dd1defcf2b7d424f296a/operator/pkg/model/translation/cec_translator.go#L287

If a gateway has multiple listeners, then there will be multiple `m.HTT`P here, while the current code always uses the first `m.HTTP`.


In ingress, `m.HTTP`, there should always be only one.




The reason I didn't modify `L287` is because I think my current approach may be more elegant.

The core idea of this PR is to leverage the following code:

https://github.com/cilium/cilium/blob/7c7ae03aa95620c4b022dd1defcf2b7d424f296a/operator/pkg/model/translation/envoy_virtual_host.go#L410-L422

**Comment by chaunceyjiang** [comment]
Before:
https://github.com/cilium/cilium/issues/29099#issuecomment-1831885873

After:
image

File: operator/pkg/model/ingestion/gateway.go (hunk 1 above)
Comment (sayboras) [reply operator/pkg/model/ingestion/gateway.go:493]: Awesome finding :+1:

Comment (sayboras) [reply operator/pkg/model/ingestion/gateway.go:493]: Will take a closer look later today or tmr

Comment (chaunceyjiang) [reply operator/pkg/model/ingestion/gateway.go:493]: Reference  https://github.com/kubernetes-sigs/gateway-api/blob/35fe25d1384a41c9b89dd5af7ae3214c431f008c/apis/v1/httproute_types.go#L1040-L1041

**Review by sayboras — APPROVED** [review]
I probably have missed the default port details from upstream spec. Thanks and lgtm.

**Comment by gandro** [comment]
@sayboras @chaunceyjiang I've attempted to backport this to v1.15, but the unit test is failing and I lack the domain knowledge to fix it. Marking as "backport/author", i.e. asking one of you to backport this to v1.15 yourselves (or removing the "needs backport" label.

**Comment by sayboras** [comment]
sure, thanks for the ping. I have a few more lined up related to Gateway API backport, will bundle all of them together in on backport PR.
