### PR TITLE
modules_linux: Add support for builtin kernel modules

### LINKED ISSUE #23863: Cilium doesn't recognize built-in kernel modules, causing IPv6 to fail on Talos Linux
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've encountered this in Talos Linux which does not have any loadable kernel modules, rather, most modules are linked statically
When trying to enable IPv6 support:

```yaml
ipv6:
  enabled: true

securityContext:
  privileged: true

ipam:
  mode: kubernetes

kubeProxyReplacement: "strict"
k8sServiceHost: "192.168.13.37"
k8sServicePort: "6443"

```

(this also happens with kube-proxy enabled)

Then the agent fails (see below for logs)

The issue seems to be with https://github.com/cilium/cilium/blob/66e5ec75ed8bbb96c4129634a75f01662cc439b3/pkg/modules/modules_linux.go 

It tries to read `/proc/modules` which is empty, so it then tries to dynamically load the modules, e.g by doing
`modprobe ip6_tables` which fails on Talos Linux:

```shell
root@cwwk-box:/home/cilium# modprobe ip6_tables -n
modprobe: FATAL: Module ip6_tables not found in directory /lib/modules/6.1.7-talos
```

I think a better solution would be to check the built in modules first:

```shell
root@cwwk-box:/home/cilium# cat /lib/modules/6.1.7-talos/modules.builtin | grep -E '(ip6table|ip_tables|xt_socket)'
kernel/net/netfilter/xt_socket.ko
kernel/net/ipv4/netfilter/ip_tables.ko
kernel/net/ipv6/netfilter/ip6table_filter.ko
kernel/net/ipv6/netfilter/ip6table_mangle.ko
kernel/net/ipv6/netfilter/ip6table_raw.ko
kernel/net/ipv6/netfilter/ip6table_security.ko
kernel/net/ipv6/netfilter/ip6table_nat.ko
```

When I patched cilium to skip the module check, it seems to work fine 

### Cilium Version

v1.13.0

### Kernel Version

`6.1.7-talos`

also encountered on talos `v1.3.4` which uses `5.15`

### Kubernetes Version

Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.26.1

### Sysdump

_No response_

### Relevant log output

```shell
cilium-agent level=fatal msg="IPv6 is enabled and ip6tables modules could not be initialized (try disabling IPv6 in Cilium or loading ip6_tables, ip6table_mangle, ip6table_raw and ip6table_filter kernel modules)" error="could not load module ip6_tables: exit status 1" subsys=iptables
```

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by TheAifam5**
Previously, kernel modules names were read from the `/proc/modules` only which prevented k8s linux distribution with kernel modules builtin into the kernel to pass the validation of required kernel modules by Cilium.

This patch adds support for systems with builtin modules by trying to read the kernel module names from following files additionally:
- `/lib/modules/<kernel-version>/modules.builtin`
- `/usr/lib/modules/<kernel-version>/modules.builtin`
- `/usr/lib/debug/lib/modules/<kernel-version>/modules.builtin`

Fixes: #23863

```release-note
Add support for builtin kernel modules
```

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible
   **Unable to test on my current machine**
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

### CODE REVIEW

**Comment by TheAifam5** [comment]
I mistakenly made it as draft. Please publish the PR. :)

File: pkg/modules/modules_linux.go [hunk 1]
```diff
@@ -45,15 +63,94 @@ func parseModulesFile(r io.Reader) ([]string, error) {
...
+		fModulePath := fmt.Sprintf(location, release)
+
+		fModules, err := os.Open(fModulePath)
+		if errors.Is(err, os.ErrNotExist) {
+			continue
+		}
+
+		if err != nil {
+			return nil, fmt.Errorf(
+				"failed to open builtin modules information at %s: %s",
```
Comment (uhthomas) [inline pkg/modules/modules_linux.go]:
```suggestion
				"failed to open builtin modules information at %s: %w",
```

File: pkg/modules/modules_linux.go [hunk 2]
```diff
@@ -45,15 +63,94 @@ func parseModulesFile(r io.Reader) ([]string, error) {
...
+
+	return result, nil
+}
+
+// listModules returns the list of loaded kernel modules names parsed from
+// /proc/modules and from /lib/modules/<version>/modules.builtin.
+func listModules() ([]string, error) {
+	loadedModules, err := listLoadedModules()
+	if err != nil {
+		return nil, fmt.Errorf("failed to retrieve loaded modules names: %s", err)
```
Comment (uhthomas) [inline pkg/modules/modules_linux.go]:
```suggestion
		return nil, fmt.Errorf("failed to retrieve loaded modules names: %w", err)
```

File: pkg/modules/modules_linux.go (hunk 1 above)
Comment (TheAifam5) [reply pkg/modules/modules_linux.go]: Thank you for spotting it out. I have applied this change on points which you suggested and also in lines above.

**Comment by pchaigno** [comment]
> Should I rebase? The one of the pipelines is failing (perhaps due to 0.6 gateway api upgrade).

Yes, please. The ConformanceGatewayAPI failure doesn't look like a flake and seems fixed on master.

File: pkg/modules/modules_linux.go [hunk 3]
```diff
@@ -45,15 +63,94 @@ func parseModulesFile(r io.Reader) ([]string, error) {
...
+		}
+
+		defer fModules.Close()
+
+		modules, err := parseBuiltinModulesFile(fModules)
+		if err != nil {
+			return nil, err
+		}
+
+		result = append(result, modules...)
```
Comment (TheAifam5) [inline pkg/modules/modules_linux.go]: This will load all available `modules.builtin`, which I think (now came to my mind) it should do not and break the execution on first successful read, same as in `vendor/github.com/cilium/ebpf/btf/btf.go#findVMLinux`. Am I right on this?

Comment (TheAifam5) [reply pkg/modules/modules_linux.go]: I have prepared the change for this. Please let me know if that should be a desired behaviour, then I will push it.

Comment (NikAleksandrov) [reply pkg/modules/modules_linux.go]: I agree, it should use the first one found.

**Review by NikAleksandrov — CHANGES_REQUESTED** [review]

**Comment by TheAifam5** [comment]
@gentoo-root
> IMO, it's more reliable to query subdirectories of /sys/module

I thought that also. The problem with /sys/module is that [only appears when at least has a version or at least one parameter](https://www.kernel.org/doc/Documentation/ABI/stable/sysfs-module) and it is not reliable source due to `The conditions of creation in the built-in case are not by design and may be removed in the future.`

Since the /lib/modules is getting already mounted due to cilium's btf (findVMLinux function) - I see no problem here.

File: pkg/modules/modules_linux.go (hunk 3 above)
Comment (TheAifam5) [reply pkg/modules/modules_linux.go]: Done, also moved the linux-specific tests to the different file. Please resolve this conversation if you are satisfied with the result.

**Comment by NikAleksandrov** [comment]
@TheAifam5 could you please squash the last commit into the first? Since it's not merged yet we can just have the
correct code in the original commit.

**Comment by TheAifam5** [comment]
@NikAleksandrov Understood. I will do it today, around 19-23:00 GMT+1.

**Review by NikAleksandrov — APPROVED** [review]
Looks good to me, but it needs to be rebased on top of latest master.

**Comment by TheAifam5** [comment]
Should I rebase it again?

**Comment by pchaigno** [comment]
> Should I rebase it again?

No. In general it's best not to rebase unless 1) you're going to push a change anyway, or 2) there is a merge conflict, or 3) a maintainer asks you to. When rebasing all tests need to be restarted.

I'll triage CI results now and will rerun or mark ready to merge accordingly.

**Comment by pchaigno** [comment]
Thanks for fixing this @TheAifam5!

**Comment by pchaigno** [comment]
This will be released in v1.14.0. I've added the backport label given that it fits the backporting criteria and shouldn't cause backport conflicts (that code is rarely touched). So unless the backporter hits issues, it should also be in the next v1.13 release.

**Comment by dedene** [comment]
Awesome, thanks!

**Comment by dedene** [comment]
Any idea when there will be another 1.13 release or the 1.14 release?
