### PR TITLE
bpf: create and open maps using `cilium/ebpf`

### LINKED ISSUE #25272: CI: Travis: Times out from no output received in the last 10m0s
## CI failure

https://app.travis-ci.com/github/cilium/cilium/builds/262657655
```
$ travis_export_go 1.20.3 github.com/cilium/cilium
0.01s
Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
21.49s$ travis_setup_go
go version go1.20.3 linux/arm64
$ export GOPATH="/home/travis/gopath"
$ export PATH="/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.20.3.linux.arm64/bin:/home/travis/bin:/home/travis/bin:/home/travis/.local/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v10.16.0/bin:/home/travis/.kiex/elixirs/elixir-1.7.4/bin:/home/travis/.kiex/bin:/home/travis/.rvm/gems/ruby-2.7.1/bin:/home/travis/.rvm/gems/ruby-2.7.1@global/bin:/home/travis/.rvm/rubies/ruby-2.7.1/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.arm64/bin:/usr/local/maven-3.6.3/bin:/usr/local/cmake-3.16.8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin"
$ export GO111MODULE="auto"
$ gimme version
v1.5.4
$ go version
go version go1.20.3 linux/arm64
go.env
$ go env
before_install
65.53s$ ./.travis/prepare.sh
install
0.00s$ travis_install_go_dependencies 1.20.3 -v
before_script.1
0.00s$ export DOCKER_BUILD_FLAGS=--quiet
before_script.2
0.00s$ export PATH=/usr/local/clang/bin:$PATH
before_script.3
0.00s$ export V=0
$ ./.travis/build.sh
docker: 'buildx' is not a docker command.
See 'docker --help'
  CHECK   Installed Go version 1.20 matches required version 1.20
  CHECK   contrib/scripts/check-logging-subsys-field.sh
  CHECK   pkg/datapath/loader/check-sources.sh
  GO     proxylib/libcilium.so
  SKIP  envoy/
cilium-envoy has been moved to github.com/cilium/proxy
  CC     bpf/bpf_network.ll
  CC     bpf/bpf_alignchecker.ll
  CC     bpf/custom/bytecount.ll
  CC     bpf/custom/bytecount.o
  CC     bpf/bpf_lxc.ll
  CC     bpf/bpf_overlay.ll
  CC     bpf/bpf_sock.ll
  CC     bpf/bpf_host.ll
  CC     bpf/bpf_xdp.ll
  CC     bpf/bpf_network.o
  CC     bpf/bpf_alignchecker.o
  CC     bpf/bpf_lxc.o
  CC     bpf/bpf_overlay.o
  CC     bpf/bpf_sock.o
  CC     bpf/bpf_host.o
  CC     bpf/bpf_xdp.o
  GO     cilium/cilium
  GO     daemon/cilium-agent
  GO     cilium-health/cilium-health
  GO     cilium-health/responder/cilium-health-responder
  GO     bugtool/cilium-bugtool
  GO     tools/mount/cilium-mount
  GO     tools/sysctlfix/cilium-sysctlfix
  GO     operator/cilium-operator
  GO     plugins/cilium-docker/cilium-docker
  GO     plugins/cilium-cni/cilium-cni
  GO     tools/alignchecker/cilium-align-checker
  GO     tools/mount/cilium-mount
  GO     hubble-relay/hubble-relay
  CHECK   contrib/scripts/check-fmt.sh
  CHECK   contrib/scripts/check-log-newlines.sh
  CHECK   contrib/scripts/check-test-tags.sh
  CHECK   contrib/scripts/check-assert-deep-equals.sh
  CHECK   contrib/scripts/lock-check.sh
  CHECK   contrib/scripts/check-viper.sh
  CHECK   contrib/scripts/custom-vet-check.sh
  GO     operator/cilium-operator-generic
  GO     operator/cilium-operator-aws
  GO     operator/cilium-operator-azure
  GO     operator/cilium-operator-alibabacloud
  DOCKER Documentation builder-image
3.7.9-alpine3.13: Pulling from library/python
Status: Downloaded newer image for python:3.7.9-alpine3.13
docker.io/library/python:3.7.9-alpine3.13
sha256:e8db498c6737ec3f104982897441e2e11cde539c3317d0bbfec446796e8b805f
SKIP_BUILD set, assuming all build artifacts are already present.
Unable to find image 'quay.io/cilium/helm-toolbox:v1.0.1@sha256:a1483fc036b15c290326ba7ed36b8f0b714e185913b72a6074c04225d74e034c' locally
sha256:a1483fc036b15c290326ba7ed36b8f0b714e185913b72a6074c04225d74e034c: Pulling from cilium/helm-toolbox
42d620ca9c84: Pulling fs layer
c4166f4e5818: Pulling fs layer
4d704a88b82e: Pulling fs layer
e2cebd955edf: Pulling fs layer
f021891ab9ce: Pulling fs layer
a93dffc060fc: Pulling fs layer
051dcd00ae06: Pulling fs layer
ed307f0dcaa7: Pulling fs layer
e2cebd955edf: Waiting
f021891ab9ce: Waiting
a93dffc060fc: Waiting
051dcd00ae06: Waiting
ed307f0dcaa7: Waiting
4d704a88b82e: Verifying Checksum
4d704a88b82e: Download complete
42d620ca9c84: Verifying Checksum
42d620ca9c84: Download complete
f021891ab9ce: Verifying Checksum
f021891ab9ce: Download complete
c4166f4e5818: Verifying Checksum
c4166f4e5818: Download complete
a93dffc060fc: Verifying Checksum
a93dffc060fc: Download complete
e2cebd955edf: Verifying Checksum
e2cebd955edf: Download complete
051dcd00ae06: Verifying Checksum
051dcd00ae06: Download complete
42d620ca9c84: Pull complete
ed307f0dcaa7: Verifying Checksum
ed307f0dcaa7: Download complete
c4166f4e5818: Pull complete
4d704a88b82e: Pull complete
e2cebd955edf: Pull complete
f021891ab9ce: Pull complete
a93dffc060fc: Pull complete
051dcd00ae06: Pull complete
ed307f0dcaa7: Pull complete
Digest: sha256:a1483fc036b15c290326ba7ed36b8f0b714e185913b72a6074c04225d74e034c
Status: Downloaded newer image for quay.io/cilium/helm-toolbox@sha256:a1483fc036b15c290326ba7ed36b8f0b714e185913b72a6074c04225d74e034c
time="2023-04-28T06:13:49Z" level=info msg="Found Chart directories [cilium]"
time="2023-04-28T06:13:50Z" level=info msg="Generating README Documentation for chart /src/install/kubernetes/cilium"
  GEN    Documentation/cmdref
level=info msg="Memory available for map entries (0.003% of 8129646592B): 20324116B" subsys=config
level=info msg="option bpf-ct-global-tcp-max set by dynamic sizing to 131072" subsys=config
level=info msg="option bpf-ct-global-any-max set by dynamic sizing to 65536" subsys=config
level=info msg="option bpf-nat-global-max set by dynamic sizing to 131072" subsys=config
level=info msg="option bpf-neigh-global-max set by dynamic sizing to 131072" subsys=config
level=info msg="option bpf-sock-rev-map-max set by dynamic sizing to 65536" subsys=config
level=warning msg="Running Cilium with \"kvstore\"=\"\" requires identity allocation via CRDs. Changing identity-allocation-mode to \"crd\"" subsys=config
  CHECK  Documentation cmdref
  CHECK  Documentation helm-values.rst
  CHECK  Documentation examples
  CHECK  Documentation codeowners.rst
  CHECK   contrib/scripts/rand-check.sh
Build finished.
docker: 'buildx' is not a docker command.
See 'docker --help'
Starting key-value store containers...
Unable to find image 'quay.io/coreos/etcd:v3.3.20-arm64' locally
v3.3.20-arm64: Pulling from coreos/etcd
Status: Downloaded newer image for quay.io/coreos/etcd:v3.3.20-arm64
ad2be58ff834df359a13063d552b9494f78f14dc67e945bfbe80be71c228cc19
Unable to find image 'consul:1.7.2' locally
1.7.2: Pulling from library/consul
Status: Downloaded newer image for consul:1.7.2
39a3c9f50367e056beab6b77ae1fdc621f1d869ad7cd233f13d9e84943dcdbba
  CC     test/bpf/elf-demo.o
  CC     test/bpf/unit-test
  CHECK  test/bpf
  CHECK  test/bpf unit-test
docker: 'buildx' is not a docker command.
See 'docker --help'
  CHECK   vetting all packages...
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
```

I can't quite tell, is this because _vetting_ is taking >10m, or because vetting completes and Cilium moves on to the next step which then doesn't output anything for 10m?

### PR DESCRIPTION
**Pull request by ti-mo**
This PR puts `cilium/ebpf.Map` at the core of Cilium's `bpf.Map` type, see #22513 for more context. Best reviewed per commit given its size. If you've been tagged for review and don't feel comfortable, please let me know so we can reassign. Don't hesitate to ping me offline for discussion or more context.

Part of: #22513.

```release-note
Perform map creation and opening using cilium/ebpf API
```

### CODE REVIEW

**Comment by tommyp1ckles** [comment]
@ti-mo Sorry never got around to reviewing this,  are you planning to reopen?

**Comment by ti-mo** [comment]
> @ti-mo Sorry never got around to reviewing this,  are you planning to reopen?

No worries, it's a draft. :) Will pick this up again in a few weeks.

**Comment by ti-mo** [comment]
@YutaroHayakawa I've had to make some changes to the way per-cluster CT maps are loaded from a pin, PTAL.

I think pinning inner maps there is not strictly necessary and creates quite some accidental complexity around managing pins. Also, 4 * 256 syscalls to attempt opening all possible pins on every single GC cycle. Map-in-map reads need RCU, but surely a few BPF_MAP_GET_NEXT_KEY calls on the outer map aren't that problematic? At least the latter would just block instead of hammering BPF_OBJ_GETs, leading to lower CPU usage?

**Review by YutaroHayakawa — APPROVED** [review]
Sorry for the late response 🙇 

Thanks for taking care of the per-cluster maps. The changes looks good. Wrt the pinned maps, I totally agree that it introduces the complexity, but the time takes to iterate over the outer maps is significantly longer when we don't pin the inner map. For example, measurement in my local machine shows 5s for iterating single per-cluster map without pin and 600us with pin. Thus, with pin, 20s per GC.

I'm worrying about the scenario that users have clusters with very high CT fill-up rate and want to reduce the GC rate, this latency becomes the problem. However, I don't know how short do people setup the CT GC practically. The default GC interval is 5m, so in default scenario (ignoring the auto interval adjustment), indeed, it doesn't become a big problem.

**Comment by ti-mo** [comment]
> Wrt the pinned maps, I totally agree that it introduces the complexity, but the time takes to iterate over the outer maps is significantly longer when we don't pin the inner map. For example, measurement in my local machine shows 5s for iterating single per-cluster map without pin and 600us with pin. Thus, with pin, 20s per GC.

Thanks for taking a look! Did you run a profile to check what these 5s were being spent on? Since this is an ARRAY_OF_MAPS, a lot of unnecessary work will be done to scan all keys. (4 * 256 syscalls) Have you considered making this a HASH_OF_MAPS instead? That would only result in entries + 1 syscalls for a full iteration.

**Comment by ti-mo** [comment]
/test-1.26-net-next

**Review by dylandreimerink — APPROVED** [review]
LGTM. Thanks for the clean history and small commits, makes it easy to review :rocket:

File: pkg/bpf/bpf_linux.go [hunk 1]
```diff
@@ -460,82 +354,60 @@ func objCheck(fd int, path string, mapType MapType, keySize, valueSize, maxEntri
...
+		log.WithField(logfields.Path, path.Join(pinDir, spec.Name)).
+			WithFields(logrus.Fields{
+				"old": fmt.Sprintf("Type:%s KeySize:%d ValueSize:%d MaxEntries:%d, Flags:%d",
+					info.Type, info.KeySize, info.ValueSize, info.MaxEntries, info.Flags),
+				"new": fmt.Sprintf("Type:%s KeySize:%d ValueSize:%d MaxEntries:%d, Flags:%d",
+					spec.Type, spec.KeySize, spec.ValueSize, spec.MaxEntries, spec.Flags),
+			}).Info("Unpinning map with incompatible properties")
+
+		// Found pinned map incompatible with spec. Remove it and recreate the map.
+		if err := os.RemoveAll(path.Join(pinDir, spec.Name)); err != nil {
```
Comment (lmb) [inline pkg/bpf/bpf_linux.go]: Nit: why not `m.Unpin()`?

File: pkg/maps/cidrmap/cidrmap.go [hunk 2]
```diff
@@ -140,50 +142,49 @@ func (cm *CIDRMap) Close() error {
...
-		bpf.BPF_F_NO_PREALLOC, 0, true,
-	)
+	m, err := bpf.OpenOrCreateMap(&ebpf.MapSpec{
+		Name:       path.Base(pinPath),
+		Type:       mapType,
+		KeySize:    uint32(unsafe.Sizeof(uint32(0)) + uintptr(bytes)),
+		ValueSize:  uint32(LPM_MAP_VALUE_SIZE),
+		MaxEntries: maxelem,
+		Flags:      bpf.BPF_F_NO_PREALLOC,
+		Pinning:    1,
```
Comment (lmb) [inline pkg/maps/cidrmap/cidrmap.go]: Nit: use the named constant?

File: pkg/bpf/map_linux.go [hunk 3]
```diff
@@ -71,7 +71,6 @@ type MapInfo struct {
 	MaxEntries    uint32
 	Flags         uint32
 	InnerSpec     *ebpf.MapSpec
-	OwnerProgType ProgType
```
Comment (lmb) [inline pkg/bpf/map_linux.go:73]: I guess this was unused?

File: pkg/bpf/map_linux.go [hunk 4]
```diff
@@ -402,38 +397,32 @@ func GetMapInfo(pid int, fd int) (*MapInfo, error) {
...
 	m := &Map{
-		MapInfo: *info,
-		fd:      fd,
-		name:    path.Base(name),
-		path:    name,
+		MapInfo: MapInfo{
+			MapType:       MapType(em.Type()),
+			KeySize:       em.KeySize(),
+			ValueSize:     em.ValueSize(),
+			ReadValueSize: em.ValueSize(),
```
Comment (lmb) [inline pkg/bpf/map_linux.go:400]: Not sure whether this is actually used in the code base, but this value is going to be wrong for per CPU maps, no?

File: pkg/maps/tunnel/tunnel.go [hunk 5]
```diff
@@ -60,7 +60,7 @@ func NewTunnelMap(mapName string) *Map {
 		MaxEntries,
 		0,
 		bpf.ConvertKeyValue,
-	).WithCache().WithPressureMetric().WithNonPersistent().
+	).WithCache().WithPressureMetric().
```
Comment (lmb) [inline pkg/maps/tunnel/tunnel.go:63]: So where is the matching `Recreate` call?

File: pkg/bpf/bpf_linux.go [hunk 6]
```diff
@@ -42,6 +42,33 @@ func createMap(spec *ebpf.MapSpec, opts *ebpf.MapOptions) (*ebpf.Map, error) {
...
+
+		info, err2 := m.Info()
+		if err2 != nil {
+			return nil, fmt.Errorf("get info of incompatible map: %w", err)
+		}
+
+		return nil, fmt.Errorf(
+			"incompatible map at path %s: old: (Type:%s KeySize:%d ValueSize:%d MaxEntries:%d, Flags:%d), "+
+				"new: (Type:%s KeySize:%d ValueSize:%d MaxEntries:%d, Flags:%d): %w", path,
+			info.Type, info.KeySize, info.ValueSize, info.MaxEntries, info.Flags,
```
Comment (lmb) [inline pkg/bpf/bpf_linux.go]: Doesn't `m.Type()` etc. should give you what you need?

File: pkg/bpf/bpf_linux.go [hunk 7]
```diff
@@ -42,6 +42,33 @@ func createMap(spec *ebpf.MapSpec, opts *ebpf.MapOptions) (*ebpf.Map, error) {
...
+			return nil, fmt.Errorf("open pin of incompatible map: %w", err)
+		}
+		defer m.Close()
+
+		info, err2 := m.Info()
+		if err2 != nil {
+			return nil, fmt.Errorf("get info of incompatible map: %w", err)
+		}
+
+		return nil, fmt.Errorf(
```
Comment (lmb) [inline pkg/bpf/bpf_linux.go]: FWIW we could extend the library to return an more useful error. Or create a dedicated error type which contains the info needed.

File: pkg/maps/policymap/policymap.go [hunk 8]
```diff
@@ -453,7 +455,15 @@ func newMap(path string) *PolicyMap {
 // protected by this map.
 func OpenOrCreate(path string) (*PolicyMap, error) {
 	m := newMap(path)
+
 	err := m.OpenOrCreate()
+	if errors.Is(err, ebpf.ErrMapIncompatible) {
+		err = m.Recreate()
```
Comment (lmb) [inline pkg/maps/policymap/policymap.go]: Shouldn't this be part of the previous commit?

**Review by lmb — COMMENTED** [review]
Thanks a lot for breaking this down into individual commits, it really helps with review!

**Review by nebril — APPROVED** [review]
ci-structure bit LGTM

File: pkg/bpf/bpf_linux.go (hunk 7 above)
Comment (ti-mo) [reply pkg/bpf/bpf_linux.go]: Yes, that might be better. Would like to merge this PR in the short term, though, so we can keep this here for now. Tracking this in https://github.com/cilium/ebpf/issues/1034.

File: pkg/bpf/bpf_linux.go (hunk 6 above)
Comment (ti-mo) [reply pkg/bpf/bpf_linux.go]: Thanks, forgot those existed!

File: pkg/maps/policymap/policymap.go (hunk 8 above)
Comment (ti-mo) [reply pkg/maps/policymap/policymap.go]: This commit has been removed, but the goal was to split off the change to the building block from the change to the consumer, as it might be easier to review that way. In hindsight, probably better to put them together to avoid mistakes.

File: pkg/bpf/bpf_linux.go (hunk 1 above)
Comment (ti-mo) [reply pkg/bpf/bpf_linux.go]: Of course, thanks!

File: pkg/bpf/map_linux.go (hunk 3 above)
Comment (ti-mo) [reply pkg/bpf/map_linux.go:73]: Yep, wasn't used.

File: pkg/bpf/map_linux.go (hunk 4 above)
Comment (ti-mo) [reply pkg/bpf/map_linux.go:400]: Hmm, good catch. We used to have [`NewPerCPUHashMap`](https://github.com/cilium/cilium/commit/60eef6f60ce74b659ac493a593f24f7fe8b3a15d), but this has since been removed. I replicated `GetMapInfo()` behaviour here, which also populates ReadValueSize with the `value_size:%d` value found in a map's fdinfo.

As far as I can see, `METRICS_MAP` is still in use and is a per-cpu hash map. I assume fdinfo echoes the full value with across all CPUs, otherwise dumping metrics (e.g. using `cilium metrics list` from within the container) would currently be broken if the metrics map was opened from a pin. I'll need to double-check on Monday.

Comment (ti-mo) [reply pkg/bpf/map_linux.go:400]: Nope, fdinfo of percpu hashes shows the value size given during creation, not the total over all CPUs. Turns out `pkg/maps/metricsmap.metricsMap` used by `cilium bpf metrics list` is already implemented on top of `pkg/ebpf` using ebpf-go.

Given the code here replaces `GetMapInfo` behaviour 1:1, this is not going to break anything. When we implement `Map.DumpWithCallback` and friends on top of `Map.Iterate()`, we'll add support for per-cpu maps again. I've left a warning in the method godoc to remind us.

File: pkg/maps/tunnel/tunnel.go (hunk 5 above)
Comment (ti-mo) [reply pkg/maps/tunnel/tunnel.go:63]: See `tunnel.TunnelMap().Recreate()` and `vtep.VtepMap().Recreate()` in `daemon/cmd/datapath.go` for both 'NonPersistent' maps.

**Comment by YutaroHayakawa** [comment]
> Have you considered making this a HASH_OF_MAPS instead? That would only result in entries + 1 syscalls for a full iteration.

No. That sounds like a good solution. I blindly used ARRAY_OF_MAPS because the max entries are 256 so far, and it gives a maximum lookup/update performance to datapath, but given the cost of map iteration, it's worth considering that. I'll put this into the task list.

**Comment by ti-mo** [comment]
/test-1.24-5.4

**Review by lmb — APPROVED** [review]

File: pkg/bpf/bpf_linux.go [hunk 9]
```diff
@@ -460,82 +354,55 @@ func objCheck(fd int, path string, mapType MapType, keySize, valueSize, maxEntri
...
+	if spec.Pinning != 0 {
+		if pinDir == "" {
+			return nil, errors.New("cannot pin map to empty pinDir")
+		}
+		if spec.Name == "" {
+			return nil, errors.New("cannot load unnamed map from pin")
+		}
+
+		if err := os.MkdirAll(pinDir, 0755); err != nil {
+			return nil, fmt.Errorf("creating map base pinning directory: %w", err)
```
Comment (tommyp1ckles) [inline pkg/bpf/bpf_linux.go:329]: nit: can we add the pinDir to the error message to aid in debugging.

File: pkg/bpf/bpf_linux.go [hunk 10]
```diff
@@ -460,82 +354,55 @@ func objCheck(fd int, path string, mapType MapType, keySize, valueSize, maxEntri
...
-		if pin {
-			err = ObjPin(fd, path)
-			if err != nil {
-				return 0, err
-			}
+		defer m.Close()
+
+		log.WithField(logfields.Path, path.Join(pinDir, spec.Name)).
+			WithFields(logrus.Fields{
+				"old": fmt.Sprintf("Type:%s KeySize:%d ValueSize:%d MaxEntries:%d, Flags:%d",
```
Comment (tommyp1ckles) [inline pkg/bpf/bpf_linux.go]: question - why not just use the logrus kv API?

File: pkg/bpf/map_linux.go [hunk 11]
```diff
@@ -155,35 +159,36 @@ func NewMap(name string, mapType MapType, mapKey MapKey, keySize int,
...
-// NewPerCPUHashMap creates a new Map type of "per CPU hash" - object representing a BPF map
-// The number of cpus is used to have the size representation of a value when
-// a lookup is made on this map types.
-func NewPerCPUHashMap(name string, mapKey MapKey, keySize int, mapValue MapValue, valueSize, cpus, maxEntries int, flags uint32, innerID uint32, dumpParser DumpParser) *Map {
-	m := &Map{
+// NewMap creates a new Map instance - object representing a BPF map
+func NewMapWithInnerSpec(name string, mapType MapType, mapKey MapKey, mapValue MapValue, maxEntries int, flags uint32,
+	innerSpec *ebpf.MapSpec, dumpParser DumpParser) *Map {
+
+	keySize := reflect.TypeOf(mapKey).Elem().Size()
```
Comment (tommyp1ckles) [inline pkg/bpf/map_linux.go:161]: note: Calls to `Elem()` can panic, such as if mapKey is not a pointer type.

File: pkg/bpf/bpf_linux.go (hunk 9 above)
Comment (ti-mo) [reply pkg/bpf/bpf_linux.go:329]: That's on purpose, errors returned from os.Mkdir and friends already include the path: https://go.dev/play/p/RZbMjf2Q55z.

```go
func main() {
	fmt.Println(os.MkdirAll("/proc/foo", 0777))
}

mkdir /proc/foo: operation not permitted
```

File: pkg/bpf/bpf_linux.go (hunk 10 above)
Comment (ti-mo) [reply pkg/bpf/bpf_linux.go]: This may be personal preference, but I find the kv approach harder to visually diff: https://go.dev/play/p/xlpzqnxCIig.

```
time="2009-11-10T23:00:00Z" level=info msg="Unpinning map with incompatible properties" new="Type:Array KeySize:4 ValueSize:4 MaxEntries:1024 Flags:0" old="Type:Hash KeySize:4 ValueSize:4 MaxEntries:1024 Flags:0"
```
vs
```
time="2009-11-10T23:00:00Z" level=info msg="Unpinning map with incompatible properties" new_flags=0 new_keysize=4 new_maxentries=4 new_type=Array new_valuesize=4 old_flags=0 old_keysize=4 old_maxentries=4 old_type=Hash old_valuesize=4
```

- Lots of repetition (old_ and new_ prefixes)
- Longer
- Fields get sorted alphabetically
- The convention is to lowercase keys, which sort of breaks the correspondence to the keys in the MapSpec

File: pkg/bpf/map_linux.go (hunk 11 above)
Comment (ti-mo) [reply pkg/bpf/map_linux.go:161]: Ah, good observation, didn't realize. It's already been in use in NewMap for years, so we can live with this for now. The goal is to make bpf.Map generic in the short term, e.g. `Map[K MapKey, V MapValue]` so sizing can be done at compile time.

File: pkg/bpf/bpf_linux.go (hunk 10 above)
Comment (tommyp1ckles) [reply pkg/bpf/bpf_linux.go]: I see what you mean, the main advantage of the standard way is that it might hook better into existing log aggregation services.

**Review by tommyp1ckles — APPROVED** [review]

**Comment by ti-mo** [comment]
Runtime tests for `pkg/bgpv1/test` failing due to https://github.com/cilium/cilium/pull/25625.

**Comment by ti-mo** [comment]
/test-1.26-net-next

**Comment by ti-mo** [comment]
net-next is hitting https://github.com/cilium/cilium/issues/25524

**Comment by joestringer** [comment]
Broadly I think the direction that this PR is pushing the codebase is the right path, reducing Cilium-specific syscall related code and relying more on the cilium/ebpf library :tada:

From a quick glance, the `OpenOrCreate()` replacement seems to retain the semantics we want, and I welcome the improvement on `OpenParallel()` to more accurately reflect the reality of what it does.

**Comment by ti-mo** [comment]
Marked ready-to-merge as Travis' arm64 job is stalling on `go vet` (maybe due to many files touched, missing cache?) and net-next is currently kernel panicking. Nothing changed here that would cause a failure on net-next only. Not much point in re-running, this PR would otherwise remain blocked and in perpetual rebase hell.

**Review by squeed — APPROVED** [review]
approved the tophat-relevant files.
