### PR TITLE
clustermesh: fix race condition in TestClusterMeshMultipleAddRemove

### LINKED ISSUE #41984: CI: ci-integration: failing TestClusterMeshMultipleAddRemove
## CI failure

Hit this in https://github.com/cilium/cilium/actions/runs/18178424149/job/51749303598

```
    logger.go:256: time=2025-10-01T23:36:43.955Z level=INFO source=/home/runner/work/cilium/cilium/pkg/clustermesh/common/remote_cluster.go:179 msg="Connection to remote cluster established" clusterName=cluster2 etcdClusterID=7e2aa5c77baae76b
    logger.go:256: time=2025-10-01T23:36:43.956Z level=INFO source=/home/runner/work/cilium/cilium/pkg/clustermesh/common/remote_cluster.go:211 msg="Found remote cluster configuration" clusterName=cluster2
    logger.go:256: time=2025-10-01T23:36:43.956Z level=INFO source=/home/runner/work/cilium/cilium/pkg/clustermesh/common/remote_cluster.go:211 msg="Found remote cluster configuration" clusterName=cluster3
    logger.go:256: time=2025-10-01T23:36:43.956Z level=INFO source=/home/runner/work/cilium/cilium/pkg/clustermesh/common/clustermesh.go:187 msg="Delaying configuration of remote cluster, which is still being removed" clusterName=cluster3
    logger.go:256: time=2025-10-01T23:36:43.957Z level=INFO source=/home/runner/work/cilium/cilium/pkg/clustermesh/common/clustermesh.go:187 msg="Delaying configuration of remote cluster, which is still being removed" clusterName=cluster3
    clustermesh_test.go:282: 
        	Error Trace:	/home/runner/work/cilium/cilium/pkg/clustermesh/common/clustermesh_test.go:282
        	Error:      	Should be false
        	Test:       	TestClusterMeshMultipleAddRemove
        	Messages:   	Cluster3 is ready, although it shouldn't
```

Also this issue is closely related but not the same error: https://github.com/cilium/cilium/issues/33915

### PR DESCRIPTION
**Pull request by MrFreezeex**
See the commit for more details

Fixes: #41984

### CODE REVIEW

**Comment by MrFreezeex** [comment]
While it seems to me that the explanation above about the goroutine and the lock looks legit, I haven't hoped into a debugger/tried to trace the test to be fully fully sure that this is what happens.

I have run this test like 100K times locally and it doesn't seems to fail anymore though!

**Comment by MrFreezeex** [comment]
Sorry for those multiples pushes/notification... I have the tendency of spotting mistakes more easily in the github webui and realized multiple small typo that I did here :man_facepalming: , should be good now though!

File: pkg/clustermesh/common/clustermesh_test.go [hunk 1]
```diff
@@ -256,9 +261,13 @@ func TestClusterMeshMultipleAddRemove(t *testing.T) {
 	block, _ := blockRemoval.Load("cluster1")
 	close(block)
 
-	// Multiple removals and additions, ending with an addition should lead to a ready cluster
+	// A blocked removal following by multiple removals and additions, should lead to a not ready cluster
```
Comment (giorio94) [inline pkg/clustermesh/common/clustermesh_test.go]: The original comment is actually correct, if you consider the entire set of operations until:

```
require.EventuallyWithT(t, func(c *assert.CollectT) { assert.True(c, isReady("cluster2")) }, timeout, tick, "Cluster2 is not ready")
```

And similarly for the one below.

**Review by giorio94 — CHANGES_REQUESTED** [review]
Thanks @MrFreezeex identifying and looking into this flake!

```
The `remove` function lock and unlock to then call a goroutine which will take
the lock and block itself on purpose. Between the time we unlock and start the
goroutine, the `add` function might run and take the lock which was not
expected in this test.
```

I don't think this is true, and if it were, it would be a bug in the logic rather than in the test itself. The reason why it is not true is that, when `remove` is called, it synchronously creates a tombstone (while holding the lock) for the cluster that is being removed. In turn, that tombstone would delay the addition of a cluster with the same name, regardless of whether the deletion goroutine has already started or not. And that goroutine also doesn't hold the lock when calling `cluster.OnRemove` on purpose, as it would otherwise block additions/removals for other clusters.

The cause of flakiness is actually the following line:

```go
hivetest.Lifecycle(t).Append(gcm)
```

Which should not be there at all. Under the hood, that starts the fsnotify watcher, which would eventually cause `add` to be called for all clusters. However, that breaks the expectations of the test and, depending on ordering of operations, it can cause the flake. Indeed, the following comment also suggests that we don't want to rely on the watcher to have a more deterministic behavior:

```go
// Directly call the add/remove methods, rather than creating/removing the
// to prevent race conditions due to the interplay with the watcher.
```

Removing that, I've got ~100K successful runs in a row, while before I could reproduce the flake practically immediately (with the extra change mentioned below):

```
$ stress ./common.test --test.run 'TestClusterMeshMultipleAddRemove'
...
7m0s: 98870 runs so far, 0 failures
7m5s: 100059 runs so far, 0 failures
...
```

While you are here, it would be also nice to remove the dependency on a real etcd instance, which also speeds up the test quite a bit (and makes flakes easier to spot). For instance, that could be done with the following patch:

```diff
diff --git a/pkg/clustermesh/common/clustermesh_test.go b/pkg/clustermesh/common/clustermesh_test.go
index 38e20f48344a..b73e7311d8ac 100644
--- a/pkg/clustermesh/common/clustermesh_test.go
+++ b/pkg/clustermesh/common/clustermesh_test.go
@@ -7,11 +7,13 @@ import (
 	"context"
 	"errors"
 	"fmt"
+	"log/slog"
 	"os"
 	"path/filepath"
 	"testing"
 
 	"github.com/cilium/hive/hivetest"
+	"github.com/cilium/statedb"
 	"github.com/stretchr/testify/assert"
 	"github.com/stretchr/testify/require"
 
@@ -192,8 +194,14 @@ func TestClusterMesh(t *testing.T) {
 }
 
 func TestClusterMeshMultipleAddRemove(t *testing.T) {
-	testutils.IntegrationTest(t)
-	client := kvstore.SetupDummy(t, "etcd")
+	var (
+		client  = kvstore.NewInMemoryClient(statedb.New(), "__all__")
+		factory = func(context.Context, *slog.Logger, string, kvstore.ExtraOptions) (kvstore.BackendOperations, chan error) {
+			errch := make(chan error)
+			close(errch)
+			return client, errch
+		}
+	)
 
 	baseDir := t.TempDir()
 	path := func(name string) string { return filepath.Join(baseDir, name) }
@@ -220,7 +228,7 @@ func TestClusterMeshMultipleAddRemove(t *testing.T) {
 		Logger:              hivetest.Logger(t),
 		Config:              Config{ClusterMeshConfig: baseDir},
 		ClusterInfo:         types.ClusterInfo{ID: 255, Name: "local"},
-		RemoteClientFactory: DefaultRemoteClientFactory(kvstore.Config{}),
+		RemoteClientFactory: factory,
 		NewRemoteCluster: func(name string, _ StatusFunc) RemoteCluster {
 			return &fakeRemoteCluster{
 				onRun: func(context.Context) { ready.Store(name, true) },
```

File: pkg/clustermesh/common/clustermesh_test.go (hunk 1 above)
Comment (MrFreezeex) [reply pkg/clustermesh/common/clustermesh_test.go]: Indeed I didn't meant to say the the original comment was wrong but wanted to clarify a bit the flow of the test. But yes this isn't clear now for the entire set of operation now... I ended up keeping the original comment and added an additional one to try to have the best of both world

**Review by giorio94 — APPROVED** [review]
Thanks! You seem to need changing the commit message to please the linter though.

**Comment by MrFreezeex** [comment]
> The reason why it is not true is that, when remove is called, it synchronously creates a tombstone (while holding the lock) for the cluster that is being removed.

Ahh yes it was the only thing that made sense to me when I looked at it, but indeed that can't be true!

> [...] Under the hood, that starts the fsnotify watcher, [...]

Ohhh indeed that's a very very nice find, thanks a lot!

> While you are here, it would be also nice to remove the dependency on a real etcd instance, which also speeds up the test quite a bit (and makes flakes easier to spot). For instance, that could be done with the following patch:

TIL that we can do this, that's quite a nice change :D
