### PR TITLE
bpf: fix iptables masquerading for node -> remote pod traffic

### LINKED ISSUE #12205: Remote endpoints' identities resolved to WORLD when devices are set and tunneling disabled
@jrajahalme reported that, when `--devices` is configured on GKE, all remote endpoints' security identities are resolved to `WORLD` (2):
```
$ kubectl exec -it cilium-zv68c -n cilium -- cilium monitor | grep -e "10\.52\.14\.148"
Policy verdict log: flow 0x0 local EP ID 905, remote ID 2, dst port 80, proto 6, ingress true, action deny, match none, 10.52.14.148:45346 -> 10.52.15.206:80 tcp SYN
xx drop (Policy denied) flow 0x0 to endpoint 905, identity 2->41663: 10.52.14.148:45346 -> 10.52.15.206:80 tcp SYN
Policy verdict log: flow 0x0 local EP ID 905, remote ID 2, dst port 80, proto 6, ingress true, action deny, match none, 10.52.14.148:45346 -> 10.52.15.206:80 tcp SYN
xx drop (Policy denied) flow 0x0 to endpoint 905, identity 2->41663: 10.52.14.148:45346 -> 10.52.15.206:80 tcp SYN
Policy verdict log: flow 0x0 local EP ID 905, remote ID 2, dst port 80, proto 6, ingress true, action deny, match none, 10.52.14.148:45346 -> 10.52.15.206:80 tcp SYN
xx drop (Policy denied) flow 0x0 to endpoint 905, identity 2->41663: 10.52.14.148:45346 -> 10.52.15.206:80 tcp SYN
Policy verdict log: flow 0x0 local EP ID 905, remote ID 2, dst port 80, proto 6, ingress true, action deny, match none, 10.52.14.148:45346 -> 10.52.15.206:80 tcp SYN
xx drop (Policy denied) flow 0x0 to endpoint 905, identity 2->41663: 10.52.14.148:45346 -> 10.52.15.206:80 tcp SYN
Policy verdict log: flow 0x0 local EP ID 905, remote ID 2, dst port 80, proto 6, ingress true, action deny, match none, 10.52.14.148:45346 -> 10.52.15.206:80 tcp SYN
xx drop (Policy denied) flow 0x0 to endpoint 905, identity 2->41663: 10.52.14.148:45346 -> 10.52.15.206:80 tcp SYN
Policy verdict log: flow 0x0 local EP ID 905, remote ID 2, dst port 80, proto 6, ingress true, action deny, match none, 10.52.14.148:45346 -> 10.52.15.206:80 tcp SYN
xx drop (Policy denied) flow 0x0 to endpoint 905, identity 2->41663: 10.52.14.148:45346 -> 10.52.15.206:80 tcp SYN
^C
$ kubectl exec -it cilium-zv68c -n cilium -- cilium bpf policy get 905
DIRECTION   LABELS (source:key[=value])                       PORT/PROTO   PROXY PORT   BYTES   PACKETS   
Ingress     reserved:host                                     ANY          NONE         0       0         
Ingress     k8s:class=spaceship                               80/TCP       18510        0       0         
            k8s:io.cilium.k8s.policy.cluster=default                                                           
            k8s:io.cilium.k8s.policy.serviceaccount=default                                                    
            k8s:io.kubernetes.pod.namespace=default                                                            
            k8s:org=empire                                                                                     
Ingress     k8s:class=spaceship                               80/TCP       18510        0       0         
            k8s:io.cilium.k8s.policy.cluster=default                                                           
            k8s:io.cilium.k8s.policy.serviceaccount=default                                                    
            k8s:io.kubernetes.pod.namespace=default                                                            
            k8s:org=alliance                                                                                   
Egress      reserved:unknown                                  ANY          NONE         0       0 
```

The following dump has some incorrectly auto-detected devices. We already established that the bug still happens when devices are properly detected.
[gke-star-wars-demo.zip](https://github.com/cilium/cilium/files/4804739/gke-star-wars-demo.zip)

/cc @brb

### LINKED ISSUE #14859: Connection RST on pod -> remote pod with host firewall and kube-proxy in native routing mode
Running on Linux 4.9 (thus using kube-proxy), with native routing and the host firewall enabled, connections between pods across nodes are failing due to some masquerading issue:

Command run:
```
k8s1$ curl http://10.0.1.8:4240/hello
```
On k8s1:
```
-> network flow 0xf231cb6 identity host->unknown state new ifindex 0 orig-ip 0.0.0.0: 192.168.36.11:40298 -> 10.0.1.8:4240 tcp SYN
<- network flow 0x0 identity unknown->unknown state new ifindex enp0s8 orig-ip 0.0.0.0: 10.0.1.8:4240 -> 192.168.36.11:40298 tcp SYN, ACK
-> network flow 0xf231cb6 identity host->unknown state new ifindex 0 orig-ip 0.0.0.0: 192.168.36.11:40298 -> 10.0.1.8:4240 tcp ACK
-> network flow 0xf231cb6 identity host->unknown state new ifindex 0 orig-ip 0.0.0.0: 192.168.36.11:40298 -> 10.0.1.8:4240 tcp ACK
<- network flow 0x0 identity unknown->unknown state new ifindex enp0s8 orig-ip 0.0.0.0: 192.168.36.12:4240 -> 192.168.36.11:40298 tcp ACK
-> network flow 0x0 identity host->unknown state new ifindex 0 orig-ip 0.0.0.0: 192.168.36.11:40298 -> 192.168.36.12:4240 tcp RST
```
On k8s2:
```
-> network flow 0xe436ad37 identity unknown->unknown state new ifindex 0 orig-ip 0.0.0.0: [fd04::12]:59446 -> [fd02::7c]:4240 tcp SYN
-> network flow 0x1412a947 identity unknown->unknown state new ifindex 0 orig-ip 0.0.0.0: [fd04::12]:59446 -> [fd02::7c]:4240 tcp SYN
<- network flow 0x0 identity unknown->unknown state new ifindex enp0s8 orig-ip 0.0.0.0: 192.168.36.11:40298 -> 10.0.1.8:4240 tcp SYN
-> endpoint 1188 flow 0x0 identity world->health state new ifindex lxc_health orig-ip 192.168.36.11: 192.168.36.11:40298 -> 10.0.1.8:4240 tcp SYN
<- endpoint 1188 flow 0xc14d6817 identity health->unknown state new ifindex 0 orig-ip 0.0.0.0: 10.0.1.8:4240 -> 192.168.36.11:40298 tcp SYN, ACK
-> stack flow 0xc14d6817 identity health->remote-node state reply ifindex 0 orig-ip 0.0.0.0: 10.0.1.8:4240 -> 192.168.36.11:40298 tcp SYN, ACK
-> network flow 0xc14d6817 identity health->unknown state new ifindex 0 orig-ip 0.0.0.0: 10.0.1.8:4240 -> 192.168.36.11:40298 tcp SYN, ACK
<- network flow 0x0 identity unknown->unknown state new ifindex enp0s8 orig-ip 0.0.0.0: 192.168.36.11:40298 -> 10.0.1.8:4240 tcp ACK
-> endpoint 1188 flow 0x0 identity world->health state established ifindex lxc_health orig-ip 192.168.36.11: 192.168.36.11:40298 -> 10.0.1.8:4240 tcp ACK
<- network flow 0x0 identity unknown->unknown state new ifindex enp0s8 orig-ip 0.0.0.0: 192.168.36.11:40298 -> 10.0.1.8:4240 tcp ACK
-> endpoint 1188 flow 0x0 identity world->health state established ifindex lxc_health orig-ip 192.168.36.11: 192.168.36.11:40298 -> 10.0.1.8:4240 tcp ACK
<- endpoint 1188 flow 0xc14d6817 identity health->unknown state new ifindex 0 orig-ip 0.0.0.0: 10.0.1.8:4240 -> 192.168.36.11:40298 tcp ACK
-> stack flow 0xc14d6817 identity health->remote-node state reply ifindex 0 orig-ip 0.0.0.0: 10.0.1.8:4240 -> 192.168.36.11:40298 tcp ACK
-> network flow 0xc14d6817 identity unknown->unknown state new ifindex 0 orig-ip 0.0.0.0: 192.168.36.12:4240 -> 192.168.36.11:40298 tcp ACK
<- network flow 0x0 identity unknown->unknown state new ifindex enp0s8 orig-ip 0.0.0.0: 192.168.36.11:40298 -> 192.168.36.12:4240 tcp RST
```

The part I don't understand yet is: why is the ACK packet from 10.0.1.8 to 192.168.36.11 SNATed if the previous SYN+ACK with same origin/dest. wasn't SNATed??

### PR DESCRIPTION
**Pull request by jibi**
When Cilium runs with KPR, host-firewall or bandwidth manager, it will
try to auto-derive one or more devices to which the bpf_host program is
attached.

This program will, among other things, redirect ingress traffic destined
to a pod to the pod's lxc device using `bpf_redirect()`.

This causes the traffic to bypass the nf_conntrack table, leading to a
situation where traffic leaving the pod after the connection's been
established will be (incorrectly) masqueraded in case Iptables
masquerading is enabled, since the connection is not tracked by
netfilter.

This commit fixes this by skipping `bpf_redirect()` when we detect this
case (i.e. traffic is flowing through bpf_host attached to a physical
device and Cilium has installed Iptables rules which require conntrack).

Fixes: https://github.com/cilium/cilium/issues/14859.
Fixes: https://github.com/cilium/cilium/issues/12205.

### CODE REVIEW

**Comment by jibi** [comment]
test-me-please

**Comment by jibi** [comment]
test-me-please

**Comment by jibi** [comment]
retest-4.9

**Comment by jibi** [comment]
test-me-please

**Comment by jibi** [comment]
retest-4.9

**Comment by jibi** [comment]
retest-netnext

**Comment by jibi** [comment]
retest-4.9

File: bpf/bpf_host.c [hunk 1]
```diff
@@ -526,6 +526,23 @@ handle_ipv4(struct __ctx_buff *ctx, __u32 secctx,
 			return DROP_INVALID;
 	}
 
+#if defined(NO_REDIRECT) && !defined(ENABLE_REDIRECT_FAST)
```
Comment (pchaigno) [inline bpf/bpf_host.c]: Isn't this only an issue if BPF masquerading is disabled? Does it also happen when KPR is enabled but not BPF masquerading?

I also think the proper place to fix this would be in https://github.com/cilium/cilium/blob/master/bpf/bpf_lxc.c#L1451-L1465.

**Review by pchaigno — CHANGES_REQUESTED** [review]
Isn't the same fix required for the IPv6 path?

File: bpf/bpf_host.c (hunk 1 above)
Comment (jibi) [reply bpf/bpf_host.c]: > Isn't this only an issue if BPF masquerading is disabled? Does it also happen when KPR is enabled but not BPF masquerading?

The issue is only there when both BPF masquerading and KPR are disabled (i.e. not an issue with BPF masquerading disabled and KPR enabled). Does it mean the guard above is incorrect?

> I also think the proper place to fix this would be in https://github.com/cilium/cilium/blob/master/bpf/bpf_lxc.c#L1451-L1465.

What's the advantage of skipping redirect in `bpf_lxc`? That we would do:
```
bpf_host [netdev] -> bpf_lxc -> stack
```

rather than:
```
bpf_host [netdev] -> stack -> bpf_host [cilum_host] -> bpf_lxc
```
skipping the `bpf_host` program attached to `cilium_host`?

**Comment by jibi** [comment]
> Isn't the same fix required for the IPv6 path?

Right, I forgot about that since in direct routing mode pods can only have v4 IPs assigned to (as `native-routing-cidr` is a v4 CIDR), but yeah, let's fix that path as well since we are on it

File: bpf/bpf_host.c (hunk 1 above)
Comment (pchaigno) [reply bpf/bpf_host.c]: > The issue is only there when both BPF masquerading and KPR are disabled (i.e. not an issue with BPF masquerading disabled and KPR enabled). Does it mean the guard above is incorrect?

I think so. At least it does not encode "BPF masquerading and KPR are disabled". For that you would need to check `ENABLE_MASQUERADING` and `ENABLE_NODEPORT` I believe.

> What's the advantage of skipping redirect in `bpf_lxc`?

Not bypassing ingress policy enforcement when endpoint routes are disabled :wink: 

`ipv4_local_delivery` will tail call to the destination pod's BPF program and enforce ingress policy. If endpoint routes are disabled, that's the only place where we enforce ingress policies.

Comment (jibi) [reply bpf/bpf_host.c]: > I think so. At least it does not encode "BPF masquerading and KPR are disabled". For that you would need to check `ENABLE_MASQUERADING` and `ENABLE_NODEPORT` I believe.

ack, will look into that

> Not bypassing ingress policy enforcement when endpoint routes are disabled wink
> 
> `ipv4_local_delivery` will tail call to the destination pod's BPF program and enforce ingress policy. If endpoint routes are disabled, that's the only place where we enforce ingress policies.

I'm not sure I'm following: if endpoint routes are disabled it means that endpoint traffic should go through `cilium_host` (which will not skip redirect as `from_host` will be `true` in this context), which in turn should tail call to the destination pod's BPF program and enforce ingress policy. Am I missing something?

Comment (pchaigno) [reply bpf/bpf_host.c]: > if endpoint routes are disabled it means that endpoint traffic should go through `cilium_host` (which will not skip redirect as `from_host` will be `true` in this context), which in turn should tail call to the destination pod's BPF program and enforce ingress policy. Am I missing something?

Ah, right :+1: It should work then...

Comment (brb) [reply bpf/bpf_host.c]: Maybe we should just make the `#if defined(ENCAP_IFINDEX) || defined(NO_REDIRECT)` check at the line 479 in your PR independent from `#ifdef ENABLE_NODEPORT`?

**Comment by brb** [comment]
> since in direct routing mode pods can only have v4 IPs assigned to (as native-routing-cidr is a v4 CIDR)
In the IPv6 case the following used for the MASQ exclusion - https://github.com/cilium/cilium/blob/master/pkg/datapath/config.go#L141.

Anyway, it's getting more difficult to wrap my head around `NO_REDIRECT` usage and implications. I've created the issue for that https://github.com/cilium/cilium/issues/16166. I guess we need to fix your particular case anyway before doing my suggested change.

File: bpf/bpf_host.c (hunk 1 above)
Comment (jibi) [reply bpf/bpf_host.c]: I run a few tests to confirm when all these macros are defined:

* `--kube-proxy-replacement disabled`:
```
root@k8s1:~# cilium status | egrep 'Masquerading|KubeProxyReplacement'
KubeProxyReplacement:   Disabled
Masquerading:           IPTables [IPv4: Enabled, IPv6: Enabled]
root@k8s1:~# egrep 'ENABLE_NODEPORT |ENABLE_MASQUERADE |NO_REDIRECT ' /var/run/cilium/state/globals/node_config.h
#define NO_REDIRECT 1
```

* `--kube-proxy-replacement strict`:
```
root@k8s1:~# cilium status | egrep 'Masquerading|KubeProxyReplacement'
KubeProxyReplacement:   Strict   [enp0s8 192.168.33.11 fd01::b (Direct Routing)]
Masquerading:           IPTables [IPv4: Enabled, IPv6: Enabled]
root@k8s1:~# egrep 'ENABLE_NODEPORT |ENABLE_MASQUERADE |NO_REDIRECT ' /var/run/cilium/state/globals/node_config.h
#define ENABLE_NODEPORT 1
#define NO_REDIRECT 1
```

*` --kube-proxy-replacement strict --enable-bpf-masquerade`:
```
root@k8s1:~# cilium status | egrep 'Masquerading|KubeProxyReplacement'
KubeProxyReplacement:   Strict   [enp0s8 192.168.33.11 fd01::b (Direct Routing)]
Masquerading:           BPF   [enp0s8]   10.11.0.0/16 [IPv4: Enabled, IPv6: Enabled]
root@k8s1:~# egrep 'ENABLE_NODEPORT |ENABLE_MASQUERADE |NO_REDIRECT ' /var/run/cilium/state/globals/node_config.h
#define ENABLE_MASQUERADE 1
#define ENABLE_NODEPORT 1
#define NO_REDIRECT 1
```

to my understanding this means we should assert both that `NO_REDIRECT` is defined as well as `ENABLE_NODEPORT` is _not_ defined, otherwise we'll skip redirect even in the second and third case (which is not optimal as we are redirecting packets back to the stack when we could avoid that)

**Comment by jibi** [comment]
> > since in direct routing mode pods can only have v4 IPs assigned to (as native-routing-cidr is a v4 CIDR)
> 
> In the IPv6 case the following used for the MASQ exclusion - https://github.com/cilium/cilium/blob/master/pkg/datapath/config.go#L141.
> 
> > it will try to auto-derive a device to which the bpf_host program is attached.
> 
> Nit: It can derive more than one devices.
> 
> Anyway, it's getting more difficult to wrap my head around `NO_REDIRECT` usage and implications. I've created the issue for that #16166. I guess we need to fix your particular case anyway before doing my suggested change.

I think ideally we should move most of this conditional logic to userspace, and have `NO_REDIRECT` being a single source of truth for when we actually need to skip redirect (without the need to check for encap vs direct routing or nodeport being enabled in the datapath)

**Comment by jibi** [comment]
test-me-please

File: bpf/bpf_host.c (hunk 1 above)
Comment (borkmann) [reply bpf/bpf_host.c]: So shouldn't this patch rather be: `bool skip_redirect = !is_defined(ENABLE_NODEPORT)` instead of `bool skip_redirect = false;` ? We already have `skip_redirect` taking care of this. Why it cannot be reused?

Also, what about v6, seems missing?

**Comment by jibi** [comment]
retest-gke

**Comment by brb** [comment]
> I think ideally we should move most of this conditional logic to userspace, and have NO_REDIRECT being a single source of truth for when we actually need to skip redirect (without the need to check for encap vs direct routing or nodeport being enabled in the datapath)

@jibi :+1: :+1: :+1:

**Comment by jibi** [comment]
retest-runtime

File: bpf/bpf_host.c [hunk 2]
```diff
@@ -249,6 +249,12 @@ handle_ipv6(struct __ctx_buff *ctx, __u32 secctx, const bool from_host)
 			return DROP_INVALID;
 	}
 
+#if !defined(ENABLE_NODEPORT) && defined(NO_REDIRECT) && !defined(ENABLE_REDIRECT_FAST)
+	/* See comment in handle_ipv4() */
+	if (!from_host)
+		return CTX_ACT_OK;
```
Comment (borkmann) [inline bpf/bpf_host.c]: What about the `skip_redirect` suggestion from https://github.com/cilium/cilium/pull/16136#discussion_r633339972 ?

File: bpf/bpf_host.c (hunk 1 above)
Comment (jibi) [reply bpf/bpf_host.c]: >So shouldn't this patch rather be: bool skip_redirect = !is_defined(ENABLE_NODEPORT) instead of bool skip_redirect = false; ? We already have skip_redirect taking care of this. Why it cannot be reused?

If we do like that, we would skip redirect just if `ENABLE_NODEPORT` is not defined (without checking also that `NO_REDIRECT` is set)

> Also, what about v6, seems missing?

(I think I pushed the changes for v6 right before you commented on the PR)

**Comment by jibi** [comment]
retest-4.9

**Comment by jibi** [comment]
retest-runtime

**Comment by jibi** [comment]
retest-4.9

**Comment by brb** [comment]
> I think ideally we should move most of this conditional logic to userspace, and have NO_REDIRECT being a single source of truth for when we actually need to skip redirect (without the need to check for encap vs direct routing or nodeport being enabled in the datapath)

@jibi Are you planning to implement it in this PR?

**Comment by jibi** [comment]
> > I think ideally we should move most of this conditional logic to userspace, and have NO_REDIRECT being a single source of truth for when we actually need to skip redirect (without the need to check for encap vs direct routing or nodeport being enabled in the datapath)
> 
> @jibi Are you planning to implement it in this PR?

No, I wanted to first get the issue sorted, and after that start looking into cleaning up the ifdefs logic

File: bpf/bpf_host.c (hunk 2 above)
Comment (brb) [reply bpf/bpf_host.c]: @jibi Does this comment need to be addressed?

Comment (jibi) [reply bpf/bpf_host.c]: @brb to my understanding [the same conclusion for the v4 logic](https://github.com/cilium/cilium/pull/16136#discussion_r633477903) would apply here as well (i.e. following that suggestion we would skip redirect only if `ENABLE_NODEPORT` is not defined, ignoring the `NO_REDIRECT` macro, which is not what we want)

**Review by nebril — APPROVED** [review]

File: bpf/bpf_host.c [hunk 3]
```diff
@@ -526,6 +532,23 @@ handle_ipv4(struct __ctx_buff *ctx, __u32 secctx,
 			return DROP_INVALID;
 	}
 
+#if !defined(ENABLE_NODEPORT) && defined(NO_REDIRECT) && !defined(ENABLE_REDIRECT_FAST)
```
Comment (brb) [inline bpf/bpf_host.c]: OK, I think we should ignore whether `ENABLE_NODEPORT` is set or not. In the end we are interested only whether `bpf_host` is attached to a native device (i.e. `!from_host`). The following patch (untested; IPv4-only) should do the job:
```
diff --git a/bpf/bpf_host.c b/bpf/bpf_host.c
index 2feaa7053..88a2b9e95 100644
--- a/bpf/bpf_host.c
+++ b/bpf/bpf_host.c
@@ -478,6 +478,12 @@ handle_ipv4(struct __ctx_buff *ctx, __u32 secctx,
                        if (ret < 0)
                                return ret;
                }
+               /* Verifier workaround: modified ctx access. */
+               if (!revalidate_data(ctx, &data, &data_end, &ip4))
+                       return DROP_INVALID;
+       }
+#endif /* ENABLE_NODEPORT */
+
 #if defined(NO_REDIRECT) && !defined(ENABLE_REDIRECT_FAST)
                /* Without bpf_redirect_neigh() helper, we cannot redirect a
                 * packet to a local endpoint in the direct routing mode, as
@@ -488,13 +494,9 @@ handle_ipv4(struct __ctx_buff *ctx, __u32 secctx,
                 * we bypass request and reply path in the host namespace and
                 * do not run into this issue.
                 */
-               skip_redirect = true;
+               if (!from_host)
+                       skip_redirect = true;
 #endif /* NO_REDIRECT && !ENABLE_REDIRECT_FAST */
-               /* Verifier workaround: modified ctx access. */
-               if (!revalidate_data(ctx, &data, &data_end, &ip4))
-                       return DROP_INVALID;
-       }
-#endif /* ENABLE_NODEPORT */

 #ifdef ENABLE_HOST_FIREWALL
        if (from_host) {
```

**Review by brb — CHANGES_REQUESTED** [review]
I had a second thought on this.

**Comment by jibi** [comment]
test-me-please

**Comment by jibi** [comment]
test-me-please

**Comment by jibi** [comment]
retest-gke

**Comment by jibi** [comment]
retest-4.9

**Review by brb — APPROVED** [review]
LGTM, thanks!

Would be good to get a review from @borkmann and @pchaigno too.

**Review by borkmann — APPROVED** [review]
LGTM, and also addresses https://github.com/cilium/cilium/pull/16136#discussion_r633434944 . Thanks!

**Review by pchaigno — APPROVED** [review]
LGTM! Thanks @jibi! One step closer to making the hostfw stable with kube-proxy :tada:
