### PR TITLE
pkg/logging: add a logfield to embed help messages when logging

### LINKED ISSUE #12918: Provide better UX for info messages in Cilium agent
Currently the Cilium agent can provide messages such as:
```
Waiting for IPs to become available in CRD-backed allocation pool
```
or 
```
Err: quorum check failed 9 times in a row: 4m51.157975074s since last heartbeat update has been received
```

This is not helpful for users as they can't know how to solve the issue. Instead, those messages should also tell the users to verify the logs from the Cilium operator pods. Something amount these lines:

```
Waiting for IPs [...]. Tip: Check if cilium-operator pod is running and does not have any warnings or error messages.
```
```
Err: quorum check failed 9 times [...]. Tip: cilium-agent depends on the availability of a cilium-operator, check if cilium-operator pod is running and does not have any warnings or error messages.
```

### PR DESCRIPTION
**Pull request by fristonio**
Fixes #12918

### CODE REVIEW

File: pkg/ipam/crd.go [hunk 1]
```diff
@@ -185,7 +186,9 @@ func newNodeStore(nodeName string, conf Configuration, owner Owner, k8sEventReg
 			break
 		}
 
-		log.WithFields(logFields).Info("Waiting for IPs to become available in CRD-backed allocation pool")
+		log.WithFields(logFields).WithFields(logrus.Fields{
```
Comment (sayboras) [inline pkg/ipam/crd.go]: nit: there is WithField as well if you want to use

**Review by sayboras — APPROVED** [review]
LGTM

File: pkg/ipam/crd.go (hunk 1 above)
Comment (fristonio) [reply pkg/ipam/crd.go]: Good Catch.

File: daemon/cmd/status.go [hunk 2]
```diff
@@ -834,5 +835,18 @@ func (d *Daemon) startStatusCollector() {
...
+	// Set up a signal handler function which prints out logs related to daemon status.
+	cleaner.cleanupFuncs.Add(func() {
+		// If the KVstore state is not OK, print help for user.
+		if d.statusResponse.Kvstore != nil &&
+			d.statusResponse.Kvstore.State != models.StatusStateOk {
+			helpMsg := "cilium-agent depends on the availability of cilium-operator/etcd-cluster. " +
+				"Check if the cilium-operator pod and etcd-cluster are running and do not have any " +
+				"warnings or error messages."
+			log.WithField(logfields.HelpMessage, helpMsg).
+				Errorf("KVStore state not OK: %v", d.statusResponse.Kvstore.Msg)
```
Comment (joestringer) [inline daemon/cmd/status.go]: Did you consider putting the `d.statusResponse.Kvstore.Msg` into a separate field for 'status' or similar?

In general we try to avoid the foof() variety of log messages just to ensure that the messages are consistent in log systems that understand structured logging. If `Msg` doesn't contain variable information (eg if it's only one directly-defined string or another) then this is probably fine. But if `Msg` changes depending on variable state like IPs or anything else then it'd be better to place `Msg` into a dedicated field.

Comment (fristonio) [reply daemon/cmd/status.go]: Yeah, I think it makes sense to have it in a separate field as the message is subject to change. I have updated the pull request.

**Review by aanm — APPROVED** [review]
:100:

**Comment by aanm** [comment]
test-me-please

**Comment by fristonio** [comment]
Known flake - #13062
