### PR TITLE
fix(datapath): ignore link-local IPv6 addresses for NodePort binding

### LINKED ISSUE #44436: From 1.18.4 upgrade to 1.19 breaks nodeport ipv6 functionality
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.19.0 and lower than v1.20.0

### What happened?

After upgrading to 1.19 nodeport service are not accesible over ipv6 anymore. Tcpdump on the node reveals Reset packets sent back to client. 

### How can we reproduce the issue?

1. install cilium
```
helm install cilium cilium/cilium \
  --version 1.19.1 \
  --namespace kube-system \
  --set ipam.mode=kubernetes \
  --set routingMode=native \
  --set enableIPv4Masquerade=true \
  --set enableIPv6Masquerade=true \
  --set kubeProxyReplacement=true \
  --set autoDirectNodeRoutes=true \
  --set bpf.masquerade=true \
  --set bpf.hostLegacyRouting=false \
  --set ipv4NativeRoutingCIDR=172.25.0.0/16 \
  --set ipv6NativeRoutingCIDR=fdc8:56d5:bf9c::/48 \
  --set requireIPv4PodCIDR=false \
  --set requireIPv6PodCIDR=false \
  --set l7Proxy=true \
  --set ipv6.enabled=true \
  --set envoy.enabled=true \
  --set hubble.enabled=true \
  --set hubble.relay.enabled=true \
  --set operator.identityHeartbeatTimeout=5m \
  --set prometheus.enabled=true \
  --set localRedirectPolicies.enabled=true 
```
2. create a pod and a nodeport service
```
  kubectl create service nodeport http-echo --tcp=5678:5678
  kubectl patch service http-echo --type=merge -p '{ "spec": { "ipFamilyPolicy": "PreferDualStack", "ipFamilies": [ "IPv4", "IPv6" ] } }'
  kubectl  run -l 'app=http-echo' --restart=Never --image hashicorp/http-echo:alpine http-echo -- -text="here I am"

```
4. curl the nodeport of the service  over ipv6.
```
curl -siv -m 2 -6 http://[ipv6]:31546
* Failed to connect to <ipv6> port 31546 after 35 ms: Error
```
while it's working as expected over ipv4

### Cilium Version

1.19.1

### Kernel Version

Linux node-c97577568-fhmb6 6.8.0-100-generic #100-Ubuntu SMP PREEMPT_DYNAMIC Tue Jan 13 16:40:06 UTC 2026 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.34.3

### Regression

1.18.4

### Sysdump

[cilium-sysdump-20260219-124651.zip](https://github.com/user-attachments/files/25415536/cilium-sysdump-20260219-124651.zip)

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Bigdelle**
Currently, in environments with dual-stack or IPv6 enabled, NodePorts can fail to route traffic because the agent incorrectly binds the IPv6 frontend to the node's unroutable link-local address (e.g., fe80::) instead of the global IPv6 address.

When dumping the eBPF load balancer maps (cilium-dbg bpf lb list), the NodePort incorrectly points to the link-local address:
```
[fe80::4001:aff:fe0b:102]:30884/TCP (0)   [::]:0 (16) (0) [NodePort]
```

In `pkg/datapath/tables/node_address.go` (getAddressesFromDevice), the agent evaluates the device's IPv6 addresses. Because a link-local IP isn't considered "public", the agent tags it as a valid "private" IP.

Later in the function, the fallback logic states: "Pick the NodePort addresses. Prefer private addresses if possible." Because of this, the unroutable link-local address wins the election and steals the NodePort binding from the actual global IPv6 address.

This fix should also be backported to 1.19

Fixes: #44436

### CODE REVIEW

File: pkg/datapath/tables/node_address.go [hunk 1]
```diff
@@ -514,25 +514,27 @@ func (n *nodeAddressController) getAddressesFromDevice(dev *Device, k8sIPv4, k8s
...
 		if addr.Addr.Is6() {
-			if addr.Addr == k8sIPv6 {
-				// Address matches the K8s Node IP. Prioritize it within its
-				// category (public or private) for NodePort address selection.
-				// We don't force it to both categories, as that would break
-				// the "prefer public over private" logic for Primary address
-				// selection used by BPF masquerading.
-				// See: https://github.com/cilium/cilium/issues/41866
-				if isPublic {
+			if !addr.Addr.IsLinkLocalUnicast() {
```
Comment (jingyuanliang) [inline pkg/datapath/tables/node_address.go]: Maybe && to the if above?

Comment (Bigdelle) [reply pkg/datapath/tables/node_address.go]: done

**Review by jrife — APPROVED** [review]

**Comment by julianwiedmann** [comment]
@Bigdelle thank you! Curious, were you able to pin-point whether this was a regression from https://github.com/cilium/cilium/pull/43996 ?

**Comment by Bigdelle** [comment]
> @Bigdelle thank you! Curious, were you able to pin-point whether this was a regression from #43996 ?

I didn't identify the specific commit that led to this regression, but AFAIK it was the commit that migrated from this heuristic and architecture fix (https://github.com/cilium/cilium/pull/37839) which fixes to the same issue that this code does (https://github.com/cilium/cilium/issues/36752)

**Comment by julianwiedmann** [comment]
> > @Bigdelle thank you! Curious, were you able to pin-point whether this was a regression from #43996 ?
> 
> I didn't identify the specific commit that led to this regression, but AFAIK it was the commit that migrated from this heuristic and architecture fix (#37839) which fixes to the same issue that this code does (#36752)

Ok I believe the regression from `v1.18` to `v1.19` is caused by https://github.com/cilium/cilium/pull/41778. Which messes with the skip condition [here](https://github.com/cilium/cilium/blob/e91fe6e0f329415ce626388b3afee959f3270cc5/pkg/datapath/tables/node_address.go#L481), and causes us to consider the link-local address as candidate for the NodePort address on the device.

@Bigdelle does that make sense? I think your fix is still the right move (even for older releases) - even if someone intentionally changes the scope for address discovery, they still don't want to use a link-local address for NodePort (or BPF masq) purposes.
