### PR TITLE
Fixes: #24185 Cilium-operator crash on empty azure node pools

### LINKED ISSUE #24185: cilium-operator crashes when there are node pools with 0 nodes on azure
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When cilium is deployed on azure cluster which has node pools with 0 nodes it crashes with following message:
```
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumEndpoint/v2 subsys=k8s                                                                                                                                                                                               level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumNode/v2 subsys=k8s                                                                                                                                                                                                   
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumClusterwideNetworkPolicy/v2 subsys=k8s                                                                                                                                                                               level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumNetworkPolicy/v2 subsys=k8s                                                                                                                                                                                          level=info msg="attempting to acquire leader lease kube-system/cilium-operator-resource-lock..." subsys=klog                                                                                                                                                                                                
level=info msg="Leader re-election complete" newLeader=aks-agentpool000-35274810-vmss000000-XqbLJIioEB operatorID=aks-agentpool001-35274810-vmss000001-SQiVhnkbXf subsys=cilium-operator-azure                                                                                                              level=info msg="successfully acquired lease kube-system/cilium-operator-resource-lock" subsys=klog                                                                                                                                                                                                          level=info msg="Leading the operator HA deployment" subsys=cilium-operator-azure                                                                                                                                                                                                                            
level=info msg="Initializing IPAM" mode=azure subsys=cilium-operator-azure                                                                                                                                                                                                                                  level=info msg="Starting Azure IP allocator..." subsys=ipam-allocator-azure                                                                                                                                                                                                                                 level=info msg="Restarting unmanaged kube-dns pod, started 2h2m56.606047676s ago" k8sPodName=kube-system/coredns-59b6bf8b4f-sgbwf subsys=cilium-operator-azure                                                                                                                                              
level=warning msg="Unable to synchronize Azure instances list" error="network.InterfacesClient#ListVirtualMachineScaleSetNetworkInterfaces: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"NotFound\" Message=\"Resource /subscriptions/[REDACTED]/resourceGroups/[REDACTED]/providers/Microsoft.Compute/virtualMachineScaleSets/aks-agentpool003-35274810-vmss not found.\" Details=[]" subsys=azure                                               level=fatal msg="Unable to start azure allocator" error="Initial synchronization with instances API failed" subsys=cilium-operator-azure  
```
Because of that cilium agent pods can't connect to cilium-operator and the whole cluster is unusable because of connectivity issues

### Cilium Version

1.12.6

### Kernel Version

Linux aks-agentpool001-35274810-vmss000002 5.4.0-1103-azure #109~18.04.1-Ubuntu SMP Wed Jan 25 20:53:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.24.9

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by forgems**
Empty VirtualMachineScaleSets returns 404 on ListVirtualMachineScaleSetNetworkInterfaces if there are no nodes in it. Continue with next VirtualMachineScaleSet in that case.

Please ensure your pull request adheres to the following guidelines:

- [X] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [] All code is covered by unit and/or runtime tests where feasible.
- [X] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [X] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [X] Provide a title or release-note blurb suitable for the release notes.
- [X] Thanks for contributing!

Azure allows for empty user node pools. In that case ListVirtualMachineScaleSetNetworkInterfaces will return 404 when trying to get interfaces associated with given node pool. With this change it will continue with next VirtualMachineScaleSet if this is NotFound error.

Fixes: #24185
```release-note
Fix Cilium Operator from crashing when encountering empty node pools on Azure
```

### CODE REVIEW

**Comment by forgems** [comment]
I've tested it manually on azure cluster with k8s 1.24.9

**Comment by forgems** [comment]
@tommyp1ckles Any ETA for the review of this?

**Comment by tommyp1ckles** [comment]
@forgems sorry for the delay - I'll take a look.

File: pkg/azure/api/api.go [hunk 1]
```diff
@@ -189,6 +190,10 @@ func (c *Client) vmssNetworkInterfaces(ctx context.Context) ([]network.Interface
 		result2, err2 := c.interfaces.ListVirtualMachineScaleSetNetworkInterfacesComplete(ctx, c.resourceGroup, *scaleset.Name)
 		c.metricsAPI.ObserveAPICall("Interfaces.ListVirtualMachineScaleSetNetworkInterfacesComplete", deriveStatus(err2), sinceStart.Seconds())
 		if err2 != nil {
+			// For scale set without any instances API will return not found. Then it can be skipped.
+			if v, ok := err2.(autorest.DetailedError); ok && v.StatusCode == http.StatusNotFound {
```
Comment (tommyp1ckles) [inline pkg/azure/api/api.go:194]: Makes sense, I did a bit more digging. Strangely, it seems like the Azure API only returns NotFound when the vmss was created as part of a AKS node-group, otherwise it returns a 200 with any empty list.

Could we document this idiosyncrasy in the comment for the next person looking at this.

**Review by tommyp1ckles — APPROVED** [review]

File: pkg/azure/api/api.go (hunk 1 above)
Comment (forgems) [reply pkg/azure/api/api.go:194]: sure

Comment (forgems) [reply pkg/azure/api/api.go:194]: Done

**Review by christarazi — APPROVED** [review]
