### PR TITLE
Avoid tunnel map sync controller errors

### LINKED ISSUE #16488: cilium-health test fails. bpf-map-sync-cilium_tunnel_map map sync errors
## Bug report

**General Information**

- Cilium version  - 1.10
- Kernel version - Linux ip-10-108-51-55.us-west-2.compute.internal 5.4.95-42.163.amzn2.x86_64 #1 SMP Thu Feb 4 12:50:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Kubernetes 1.19

**How to reproduce the issue**

1. Installed cilium 1.10 (latest version) to eks
2. ran ./k8s-cilium-exec.sh cilium status
3. Error 
```
  bpf-map-sync-cilium_tunnel_map   never          48s ago      49      1 map sync errors
Proxy Status:     OK, ip 100.64.46.25, 0 redirects active on ports 10000-20000
Hubble:           Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 64.68   Metrics: Ok
Encryption:       Disabled
Cluster health:         Warning   cilium-health daemon unreachable
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.19+ (v1.19.8-eks-96780e) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1beta1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Disabled
Cilium:                 Ok   1.10.0 (v1.10.0-952d9d3)
NodeMonitor:            Listening for events on 8 CPUs with 64x4096 of shared memory
IPAM:                   IPv4: 5/13 allocated,
BandwidthManager:       EDT with BPF   [eth0]
Host Routing:           Legacy
Masquerading:           IPTables [IPv4: Enabled, IPv6: Disabled]
Controller Status:      34/35 healthy
  Name                             Last success   Last error   Count   Message
  bpf-map-sync-cilium_tunnel_map   never          8s ago       45      1 map sync errors
Proxy Status:     OK, ip 100.64.91.71, 0 redirects active on ports 10000-20000
Hubble:           Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 22.71   Metrics: Ok
Encryption:       Disabled
Cluster health:         Warning   cilium-health daemon unreachable
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.19+ (v1.19.8-eks-96780e) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1beta1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Disabled
Cilium:                 Ok   1.10.0 (v1.10.0-952d9d3)
NodeMonitor:            Listening for events on 15 CPUs with 64x4096 of shared memory
IPAM:                   IPv4: 20/28 allocated,
BandwidthManager:       EDT with BPF   [eth0]
Host Routing:           Legacy
Masquerading:           IPTables [IPv4: Enabled, IPv6: Disabled]
Controller Status:      109/110 healthy
  Name                             Last success   Last error   Count   Message
  bpf-map-sync-cilium_tunnel_map   never          38s ago      45      1 map sync errors
Proxy Status:     OK, ip 100.64.12.195, 0 redirects active on ports 10000-20000
Hubble:           Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 193.80   Metrics: Ok
Encryption:       Disabled
Cluster health:         Warning   cilium-health daemon unreachable

```

See controller status.

There is no errors in the log

### PR DESCRIPTION
**Pull request by tklauser**
Several users [reported issues](https://github.com/cilium/cilium/issues/16488) with `bpf-map-sync-cilium_tunnel_map` controller in an error state even though tunneling is disabled in their setup.

While the exact condition causing these error states could not be reproduced, there are several counter-measures that can be taken to avoid these issues: most importantly disabling the `bpf-map-sync-cilium_tunnel_map` altogether in case tunneling (or the egress gateway, which also makes use of the tunnel map) is not enabled.

See commit messages for more details on the individual changes.

Fixes: #16488

```release-note
Fix an issue where the tunnel map sync controller causes errors even though tunneling is disabled.
```

### CODE REVIEW

File: pkg/datapath/linux/node.go [hunk 1]
```diff
@@ -156,14 +156,20 @@ func deleteTunnelMapping(oldCIDR *cidr.CIDR, quietMode bool) {
...
-	if err := tunnel.TunnelMap.DeleteTunnelEndpoint(oldCIDR.IP); err != nil {
-		if !quietMode {
+	if !quietMode {
+		if err := tunnel.TunnelMap.DeleteTunnelEndpoint(oldCIDR.IP); err != nil {
 			log.WithError(err).WithFields(logrus.Fields{
 				"allocCIDR": oldCIDR,
 			}).Error("Unable to delete in tunnel endpoint map")
 		}
+	} else {
+		_ = tunnel.TunnelMap.SilentDeleteTunnelEndpoint(oldCIDR.IP)
```
Comment (jibi) [inline pkg/datapath/linux/node.go:171]: Should we be a bit extra defensive and only ignore the `ENOENT` error here?

**Review by jibi — APPROVED** [review]

File: pkg/datapath/linux/node.go (hunk 1 above)
Comment (tklauser) [reply pkg/datapath/linux/node.go:171]: I think we won't ever see `ENOENT` or any other error here due to the following in `pkg/bpf.(*Map).deleteMapEntry`:

https://github.com/cilium/cilium/blob/67a3618d4775f0f52146a4c72693d0c2012f904a/pkg/bpf/map_linux.go#L977-L986

`SilentDeleteTunnelEndpoint` will call `TunnelMap.SilentDelete` which then calls `(*Map).deleteMapEntry` with `ignoreMissing = true`, meaning that we'll always get a `nil` error.

**Review by michi-covalent — APPROVED** [review]
:ship:
