### PR TITLE
operator: explicit controller-runtime controller names to avoid naming conflicts

### LINKED ISSUE #37582: cilium-operator fails to start after upgrading to v1.17.0
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.0 and lower than v1.18.0

### What happened?

After upgrading the Cilium Helm Chart from `v1.16.6` to `v1.17.0`, `cilium-operator` fails to start. There is only a single instance, and killing the Pod did not resolve the issue.

Log:

```plain
cilium-operator-68884cdb7c-m2tk9 time="2025-02-12T14:44:55.561717262Z" level=info msg="Cilium Operator 1.17.0 c2bbf787 2025-01-31T15:05:59+01:00 go version go1.23.5 linux/amd64" subsys=cilium-operator-generic
cilium-operator-68884cdb7c-m2tk9 time=2025-02-12T14:44:55Z level=info msg="Setting up Secret synchronization" module=operator.operator-controlplane.leader-lifecycle.secret-sync registrations="[*v2.CiliumNetworkPolicy -> \"cilium-secrets\" *v2.CiliumClusterwideNetworkPolicy -> \"cilium-secrets\"]"
cilium-operator-68884cdb7c-m2tk9 time=2025-02-12T14:44:55Z level=info msg=Invoked duration=175.415058ms function="secretsync.initSecretSyncReconciliation (pkg/secretsync/cell.go:54)"
cilium-operator-68884cdb7c-m2tk9 time=2025-02-12T14:44:55Z level=info msg="Register Envoy load balancer reconciler" module=operator.operator-controlplane.leader-lifecycle.ciliumenvoyconfig
cilium-operator-68884cdb7c-m2tk9 time=2025-02-12T14:44:55Z level=error msg="Invoke failed" error="failed to setup Envoy load balancer reconciler: controller with name service already exists. Controller names must be unique to avoid multiple controllers reporting to the same metric" function="ciliumenvoyconfig.registerL7LoadBalancingController (pkg/ciliumenvoyconfig/cell.go:60)"
cilium-operator-68884cdb7c-m2tk9 time=2025-02-12T14:44:55Z level=info msg=Stopping
cilium-operator-68884cdb7c-m2tk9 time="2025-02-12T14:44:55.757321531Z" level=fatal msg="failed to start: failed to setup Envoy load balancer reconciler: controller with name service already exists. Controller names must be unique to avoid multiple controllers reporting to the same metric" subsys=cilium-operator-generic
```

Digging through the code, the error seems to be triggered [here](https://github.com/kubernetes-sigs/controller-runtime/blob/894df3a7e664eb08c0ae0e0154a1e4204fd6729e/pkg/controller/name.go#L29-L43) by [this line](https://github.com/cilium/cilium/blob/v1.17.0/operator/pkg/ciliumenvoyconfig/cell.go#L78). The `controller-runtime` check for duplicate names runs locally, and does refer to any Kubernetes object for verification. It might therefore be a bug in the controller.

### How can we reproduce the issue?

1. Install cilium Helm Chart `v1.17.0`
2. Set `loadBalancer.l7.backend` to `envoy` (setting to `disabled` allows to controller to start)

### Cilium Version

```plain
Client: 1.17.0 c2bbf787 2025-01-31T15:05:59+01:00 go version go1.23.5 linux/amd64
Daemon: 1.17.0 c2bbf787 2025-01-31T15:05:59+01:00 go version go1.23.5 linux/amd64
```

### Kernel Version

```plain
Linux dev01 5.15.0-124-generic #134-Ubuntu SMP Fri Sep 27 20:20:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

`v1.31.5`

### Regression

`v1.16.6`

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mhofstetter**
The library `controller-runtime` introduced a validation for unique controller names with [v0.19.0](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.19.0).

> Breaking Changes
> ...
> controller: Validate controller names are unique & add SkipNameValidation option

If no name is explicitly configured, controllers are named using the lowercase version of their kind. (defined in `For(...)` builder function). This might lead to validation issues that prevent the operator from starting.

Therefore this PR sets explicit names when registering the controllers for the same kind (K8s Service) to the controller-runtime manager.

Note: There's also the option to completely disable this validation in controller-runtime. But this also leads to overlapping metrics names which was the reason why this check was introduced in the first place. (We need to have an extra eye on this when new controller-runtime based controllers are added to the Cilium Operator - but this shouldn't be that big of a deal as most k8s kinds are only owned by one controller)

Fixes: https://github.com/cilium/cilium/issues/37582

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
Thanks, we have done similar thing in https://github.com/cilium/cilium/pull/34575

File: operator/pkg/lbipam/cell.go [hunk 1]
```diff
@@ -118,8 +118,8 @@ func newLBIPAMCell(params lbipamCellParams) *LBIPAM {
 }
 
 const (
-	DefaultLBClassLBIPAM   = "lbipam"
-	DefaulLBClasstNodeIPAM = "nodeipam"
+	DefaultLBClassLBIPAM    = "lbipam"
+	DefaultLBClasstNodeIPAM = "nodeipam"
```
Comment (dlapcevic) [inline operator/pkg/lbipam/cell.go]: nit: Since we're fixing typos, is it supposed to have that "t" in between "Class" and "Node"?

**Review by dlapcevic — APPROVED** [review]

File: operator/pkg/lbipam/cell.go (hunk 1 above)
Comment (mhofstetter) [reply operator/pkg/lbipam/cell.go]: Thanks, fixed

**Review by julianwiedmann — APPROVED** [review]
