### PR TITLE
l2responder: fix BPF map entry deletion caused by pointer reuse

### LINKED ISSUE #45068: L2 responder reconciler repeatedly tries to delete non-existent BPF map entries, causing intermittent ARP failures
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.19.2 and lower than v1.20.0

### What happened?

LoadBalancer services using Cilium L2 Announcements intermittently become unreachable from outside the cluster with `No route to host`. The root cause is that the L2 responder BPF map loses entries for announced IPs, so the elected leader node stops responding to ARP requests.
 
The Cilium agent logs show the L2 responder reconciler repeatedly attempting to **delete** entries from the BPF map that don't exist, cycling every 5 minutes:
 
```
level=error msg="Error(s) while full reconciling l2 responder map" module=agent.datapath.l2-responder error="delete 192.168.1.250@2: delete: key does not exist"
level=error msg="Error(s) while full reconciling l2 responder map" module=agent.datapath.l2-responder error="delete 192.168.1.230@2: delete: key does not exist"
```
 
This happens even though:
- The node **is** the lease holder (leader) for these IPs
- The L2 announcer and leader election jobs report `[OK]`
- The services are valid, healthy, and have backends in `cilium-dbg service list`
- `arping` sometimes gets responses, sometimes doesn't — confirming intermittent ARP failures
 
Restarting the Cilium agent pod temporarily fixes the issue by forcing a clean BPF map rebuild, but the errors return within minutes and connectivity eventually degrades again.
 
### Environment
 
- 2-node bare-metal cluster (KVM VMs on a single host)
- Worker node interface: `enp1s0` (index 2) — matches the L2 policy regex
- Tunnel mode: VXLAN
- Two Ingress controllers: ingress-nginx and Cilium Ingress, both using Cilium LB-IPAM + L2 Announcements
 
### L2AnnouncementPolicy
 
```yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: metallb-migration-l2policy
spec:
  interfaces:
  - ^enp[0-9]+s[0-9]+
  loadBalancerIPs: true
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
```
 
### CiliumLoadBalancerIPPool
 
```yaml
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: metallb-migration-pool
spec:
  blocks:
  - start: 192.168.1.230
    stop: 192.168.1.250
```
 
### Affected services
 
```
$ kubectl get svc -A | grep -E "192.168.1.230|192.168.1.250"
ingress-nginx   ingress-nginx-controller   LoadBalancer   10.108.176.71   192.168.1.230   80:32575/TCP,443:30600/TCP   374d
kube-system     cilium-ingress             LoadBalancer   10.97.54.165    192.168.1.250   80/TCP,443/TCP               41d
```
 
### Lease status (leader is the worker for both)
 
```
$ kubectl get leases -n kube-system | grep -E "cilium-ingress|ingress-nginx"
cilium-l2announce-ingress-nginx-ingress-nginx-controller   k8s-cluster-worker-1   10d
cilium-l2announce-kube-system-cilium-ingress               k8s-cluster-worker-1   43d
```
 
### Cilium service list confirms backends exist
 
```
$ kubectl -n kube-system exec cilium-worker-pod -- cilium-dbg service list | grep 192.168.1.250
139   192.168.1.250:80/TCP       LoadBalancer
140   192.168.1.250:443/TCP      LoadBalancer
```
 
### Cilium status verbose — L2 subsystems report OK
 
```
l2-announcer
│   ├── job-l2-announcer-run                            [OK] Running (39h, x1)
│   ├── leader-election
│   │   ├── job-leader-election-kube-system-cilium-ingress  [OK] Running (39h, x1)
│   │   ├── job-leader-election-ingress-nginx-ingress-nginx-controller  [OK] Running (39h, x1)
 
l2-responder
│   └── job-l2-responder-reconciler                     [OK] Running (39h, x1)
```
 
### Error pattern in agent logs (worker node)
 
The errors alternate every 5 minutes, cycling through affected IPs:
 
```
time=2026-03-31T02:08:16Z level=error msg="Error(s) while full reconciling l2 responder map" error="delete 192.168.1.234@2: delete: key does not exist"
time=2026-03-31T02:13:16Z level=error msg="Error(s) while full reconciling l2 responder map" error="delete 192.168.1.250@2: delete: key does not exist"
time=2026-03-31T02:18:16Z level=error msg="Error(s) while full reconciling l2 responder map" error="delete 192.168.1.234@2: delete: key does not exist"
time=2026-03-31T02:23:16Z level=error msg="Error(s) while full reconciling l2 responder map" error="delete 192.168.1.250@2: delete: key does not exist"
time=2026-03-31T02:28:16Z level=error msg="Error(s) while full reconciling l2 responder map" error="delete 192.168.1.234@2: delete: key does not exist"
time=2026-03-31T02:33:16Z level=error msg="Error(s) while full reconciling l2 responder map" error="delete 192.168.1.250@2: delete: key does not exist"
```
 
Note: 192.168.1.234 was a stale LoadBalancer service (`kubernetes-dashboard-kong-proxy`) that was no longer in use. After deleting that service, the errors for .234 stopped, but errors for .230 and .250 persist.
 
After the pod restart, errors shifted to also include multiple delete attempts for the same IP in a single reconciliation pass:
 
```
time=2026-03-31T03:13:06Z level=error msg="Error(s) while full reconciling l2 responder map" error="delete 192.168.1.230@2: delete: key does not exist\ndelete 192.168.1.230@2: delete: key does not exist\ndelete 192.168.1.230@2: delete: key does not exist\ndelete 192.168.1.230@2: delete: key does not exist\ndelete 192.168.1.230@2: delete: key does not exist\ndelete 192.168.1.230@2: delete: key does not exist\ndelete 192.168.1.230@2: delete: key does not exist"
```
 
### Symptom observed from outside the cluster
 
```
$ curl -vk https://apicurio.cluster.local/apis/ccompat/v7/config
*   Trying 192.168.1.250:443...
* connect to 192.168.1.250 port 443 from 192.168.1.133 port 57964 failed: No route to host
curl: (7) Failed to connect to apicurio.cluster.local port 443 after 3053 ms: Couldn't connect to server
```
 
tcpdump confirms ARP requests going unanswered after the BPF map entry is lost:
 
```
04:54:16.902825 ARP, Request who-has 192.168.1.250 tell 192.168.1.133, length 28
04:54:17.926826 ARP, Request who-has 192.168.1.250 tell 192.168.1.133, length 28
04:54:18.946841 ARP, Request who-has 192.168.1.250 tell 192.168.1.133, length 28
(no replies)
```
 
### Connectivity test — 10/10 failures before pod restart
 
```
$ for i in $(seq 1 10); do
  curl -sk --connect-timeout 3 -o /dev/null -w "Attempt $i: HTTP %{http_code} - %{time_total}s\n" \
    https://apicurio.cluster.local/apis/ccompat/v7/config
  sleep 2
done
Attempt 1: HTTP 000 - 3.002356s (FAILED)
Attempt 2: HTTP 000 - 3.002026s (FAILED)
...
Attempt 10: HTTP 000 - 3.001399s (FAILED)
```
 
### After restarting the Cilium pod on the worker — immediate fix
 
```
$ kubectl -n kube-system delete pod cilium-p8lbl
 
$ for i in $(seq 1 5); do
  curl -sk --connect-timeout 3 -o /dev/null -w "Attempt $i: HTTP %{http_code} - %{time_total}s\n" \
    https://apicurio.cluster.local/apis/ccompat/v7/config
  sleep 2
done
Attempt 1: HTTP 200 - 0.120037s
Attempt 2: HTTP 200 - 0.023374s
Attempt 3: HTTP 200 - 0.016211s
Attempt 4: HTTP 200 - 0.015856s
Attempt 5: HTTP 200 - 0.016479s
```
 
However, the reconciler errors return within minutes after the restart.

### How can we reproduce the issue?

1. Set up a 2-node bare-metal cluster with Cilium v1.19.2 using VXLAN tunnel mode
2. Configure `CiliumLoadBalancerIPPool` and `CiliumL2AnnouncementPolicy`
3. Deploy multiple LoadBalancer services (we have 12 using the pool)
4. Wait for the L2 responder reconciler to run (every 5 minutes)
5. Observe errors in the Cilium agent logs on the leader node
6. Eventually, ARP responses stop for affected IPs, causing `No route to host` from external hosts

### Cilium Version

Client: 1.19.2 3977f6a1 2026-03-17T13:15:59+00:00 go version go1.25.8 linux/amd64
Daemon: 1.19.2 3977f6a1 2026-03-17T13:15:59+00:00 go version go1.25.8 linux/amd64

### Kernel Version

# Host KVM
Linux k8s-node-01 6.18.20 #5 SMP PREEMPT_DYNAMIC Wed Mar 25 12:34:13 CET 2026 x86_64 x86_64 x86_64 GNU/Linux

# Control plane & workers
Linux k8s-cluster-master-1 6.17.0-19-generic #19~24.04.2-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar  6 23:08:46 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.35.3
Kustomize Version: v5.7.1
Server Version: v1.35.3

### Regression

Unknown — this is the first version where we've used L2 Announcements with this number of services. The setup was migrated from MetalLB.

### Sysdump

Can provide on request.

### Relevant log output

```shell

```

### Anything else?

The fact that deleting a stale LoadBalancer service (kubernetes-dashboard-kong-proxy with IP 192.168.1.234) immediately stopped the reconciler errors for that specific IP suggests the reconciler is computing stale desired-state entries. The same pattern continues for active services (.230, .250), which indicates the reconciler's diff logic may have a bug where it marks entries for deletion on the leader node when they should be preserved.
 
The L2 announcer subsystem (leases, leader election) works correctly — the issue is isolated to the L2 responder BPF map reconciler.

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Krishnachaitanyakc**
## Summary

Fix the L2 responder reconciler incorrectly deleting desired BPF map
entries during full reconciliation, which causes intermittent ARP
failures for LoadBalancer services using L2 announcements.

**Root cause:** `ebpf.Map.IterateWithCallback` reuses the same key
pointer across iterations. The `fullReconciliation` method stored
these pointers directly in the `toDelete` slice, so all entries ended
up pointing to the last iterated key. This caused the reconciler to
delete desired entries instead of rogue ones.

**Changes:**

- Copy key values (`*key`) instead of storing pointers (`key`) when
  building the `toDelete` / `toDelete6` slices during BPF map iteration
- Tolerate `ErrKeyNotExist` errors during deletion in both partial and
  full reconciliation, since entries may be removed between iteration
  and the delete loop
- Add regression tests with a `pointerReusingFakeMap` that mimics real
  BPF map iteration behavior

```release-note
Fixed intermittent ARP failures for LoadBalancer services caused by pointer reuse during BPF map iteration in the L2 responder reconciler.
```

Fixes: #45068
Signed-off-by: Kc Balusu <krishnabkc15@gmail.com>

## Test plan

- [x] Added `TestFullReconciliationPointerReuse` — verifies desired
  entry survives and rogue entry is deleted with pointer-reusing
  iteration
- [x] Added `TestFullReconciliationMultipleRoguePointerReuse` — same
  with multiple rogue entries
- [x] Cross-compiled for Linux (`GOOS=linux go build` / `go test -c`)
- [x] `gofmt`, `go vet`, `golangci-lint` all pass with 0 issues
- [x] Existing tests continue to pass

### CODE REVIEW

**Comment by Krishnachaitanyakc** [comment]
I've added a `release-note` block to the PR description. Could a maintainer please add the `release-note/bug` label? This fixes a user-facing bug where BPF map pointer reuse causes intermittent ARP failures for LoadBalancer services.

**Comment by Krishnachaitanyakc** [comment]
@rolinh @aspsk @MikeZappa87 @rastislavs @joestringer can you please review this?

File: pkg/datapath/l2responder/l2responder.go [hunk 1]
```diff
@@ -286,37 +286,40 @@ func (p *l2ResponderReconciler) fullReconciliation(txn statedb.ReadTxn) (err err
...
+			toDelete6 = append(toDelete6, *key)
 			return
 		}
 		e.satisfied = true
 		desiredMap6[*key] = e
 	})
 
-	// Delete all unwanted map values
+	// Delete all unwanted map values. Ignore "key does not exist" errors
+	// since the entry may have been removed between iteration and deletion.
```
Comment (joestringer) [inline pkg/datapath/l2responder/l2responder.go:315]: How do the entries get deleted? I don't see any datapath code corresponding to this assertion. This seems like it's a map that is purely managed from userspace and is expected to be completely owned by the cilium-agent. Feel free to point out if I missed something.

The main reason I ask is in the unlikely case in future there's a regression that causes malformed keys (=> leak) or there's external system tampering with the map, then the error in the logs could help to pinpoint such an issue.

**Review by joestringer — COMMENTED** [review]
Nice find and fix, thanks!

@Krishnachaitanyakc we don't take in merge commits, please rebase against tip of `main` if you want to pull in the latest code. I will see if I can just click the rebase button from the UI to take care of that this time to drop the merge commit. With that I'll trigger the full testsuite run.

@cilium/sig-datapath this looks mostly fine to merge as-is to me, but four things we might want to look into:
1. Similar patterns (I can see some CLI commands making the same mistake)
2. Improving the function documentation for `IterateWithCallback` to highlight to developers that they should watch out for this pattern
3. Linting for this pattern to catch it at review time
4. Potential refactor to DRY up the fake map definition introduced in the testsuite here

File: pkg/datapath/l2responder/l2responder.go (hunk 1 above)
Comment (Krishnachaitanyakc) [reply pkg/datapath/l2responder/l2responder.go]: That's a good point actually, this map is purely userspace and managed by cilium agent, so ErrKeyNotExist during deletion would be unexpected and worth investigating. So, I updated the code to log a warning with the IP and ifindex when this occurs and still allowing reconciliation to continue. This way any regression or external tampering will be visible in the logs.

I also rebased onto main to eliminate the merge commit.

Comment (joestringer) [reply pkg/datapath/l2responder/l2responder.go]: I see yep. Given that the errors are being collected already in `errs` I don't think there needs to be a dedicated warn message just for this condition; as long as this code doesn't filter the error out, it should bubble up automatically. It's probably simpler to drop the last patch and drop the conditional checks that the first patch added.

File: pkg/datapath/l2responder/l2responder.go [hunk 2]
```diff
@@ -159,7 +159,7 @@ func (p *l2ResponderReconciler) cycle(
 
 		if deleted {
 			err = arMap.Delete(e.IP, uint32(idx))
-			if err != nil {
+			if err != nil && !errors.Is(err, ebpf.ErrKeyNotExist) {
```
Comment (joestringer) [inline pkg/datapath/l2responder/l2responder.go]: This case also still has the no exist error, does the same logic apply for this one too?
```suggestion
			if err != nil {
```

Comment (Krishnachaitanyakc) [reply pkg/datapath/l2responder/l2responder.go]: Yes, removed here too.

File: pkg/datapath/l2responder/l2responder.go (hunk 1 above)
Comment (Krishnachaitanyakc) [reply pkg/datapath/l2responder/l2responder.go]: Makes sense, dropped the last patch and removed the ErrKeyNotExist filtering.

File: pkg/datapath/l2responder/l2responder_test.go [hunk 3]
```diff
@@ -526,6 +528,165 @@ func TestIpv6McasMAC(t *testing.T) {
...
+	// matching real BPF map behavior in ebpf.Map.IterateWithCallback.
+	var key l2respondermap.L2ResponderKey
+	var val l2respondermap.L2ResponderStats
+	for k, v := range fm.entries {
+		key = k
+		val = v
+		cb(&key, &val)
+	}
+	return nil
+}
```
Comment (smagnani96) [inline pkg/datapath/l2responder/l2responder_test.go:586]: I believe we can reuse `l2respondermap.NewFakeMap()` without adding a second test implementation

```suggestion
```

File: pkg/datapath/l2responder/l2responder_test.go [hunk 4]
```diff
@@ -526,6 +528,165 @@ func TestIpv6McasMAC(t *testing.T) {
...
+// TestFullReconciliationPointerReuse verifies that fullReconciliation correctly
+// handles BPF map iteration where the same key pointer is reused across iterations.
+// This is a regression test for https://github.com/cilium/cilium/issues/45068
+// where storing pointers (instead of copies) from the iterator caused the
+// reconciler to delete wrong entries from the BPF map.
+func TestFullReconciliationPointerReuse(t *testing.T) {
+	fix := newFixture(t)
+
+	// Use the pointer-reusing fake map instead of the default fake map
+	ptrReuseMap := newPointerReusingFakeMap()
```
Comment (smagnani96) [inline pkg/datapath/l2responder/l2responder_test.go:597]:
```suggestion
	ptrReuseMap := l2respondermap.NewFakeMap()
```

Can also reduce verbosity in comments.

File: pkg/datapath/l2responder/l2responder_test.go [hunk 5]
```diff
@@ -526,6 +528,165 @@ func TestIpv6McasMAC(t *testing.T) {
...
+	assert.NoError(t, err)
+	assert.Nil(t, stats, "rogue entry ip3 was not deleted from BPF map")
+}
+
+// TestFullReconciliationMultipleRoguePointerReuse verifies correct behavior
+// when multiple rogue entries need to be deleted with pointer-reusing iteration.
+func TestFullReconciliationMultipleRoguePointerReuse(t *testing.T) {
+	fix := newFixture(t)
+
+	ptrReuseMap := newPointerReusingFakeMap()
```
Comment (smagnani96) [inline pkg/datapath/l2responder/l2responder_test.go:643]:
```suggestion
	ptrReuseMap := l2respondermap.NewFakeMap()
```

Can also reduce verbosity in comments.

**Review by smagnani96 — CHANGES_REQUESTED** [review]
Thanks for the contrib! The fix itself LGTM, I've some doubts for the tests.

> @cilium/sig-datapath this looks mostly fine to merge as-is to me, but four things we might want to look into:

@joestringer Agree this can be improved (I would've done the same mistake probably). We can track in a separate issue.

I'm not 100% convinced of the test though: I see the utility, but should we then test all BPF (and fake) maps in Go? I'd opt for a linter (similar as coccinelle script) to warn this out and block.

**Comment by Krishnachaitanyakc** [comment]
@smagnani96 addressed your comments, mind reviewing again?

**Comment by Krishnachaitanyakc** [comment]
CI failures are transient, not related to my changes.

File: pkg/datapath/l2responder/l2responder_test.go [hunk 6]
```diff
@@ -526,6 +526,87 @@ func TestIpv6McasMAC(t *testing.T) {
...
+
+	stats, err = fix.respondermap.Lookup(ip2, ifidx1)
+	assert.NoError(t, err)
+	assert.Nil(t, stats, "rogue entry ip2 was not deleted from BPF map")
+
+	stats, err = fix.respondermap.Lookup(ip3, ifidx1)
+	assert.NoError(t, err)
+	assert.Nil(t, stats, "rogue entry ip3 was not deleted from BPF map")
+}
+
```
Comment (smagnani96) [inline pkg/datapath/l2responder/l2responder_test.go]: So in the previous `TestFullReconciliationPointerReuse`, we verify that:

1. Desired entries in StateDB are 1: `A`
2. BPF Map entries are 2: `A,B`
3. Rogue entries to delete is 1: `B`

This tests simply changes (2) and (3), which does add little value (can be done directly in `TestFullReconciliationPointerReuse` imho if we still want to make sure to catch the >=2 entries diff case)

What I'd write here is a test where:

1. Desired entries in StateDB are >=2: `A, B`
2. BPF Map entries are 3: `A, B, C`
3. Rogue entries to delete is `: `C`

wdyt?

**Review by smagnani96 — CHANGES_REQUESTED** [review]
Fix looks good, I've a proposal to enhance the introduced tests! (see comment)
Other than this, please make sure to address reviewer's feedback in the same original commit. We want to make sure to keep a clean git history, so it improves readability and bisect in case of problems. Splitting multiple commits make sense to divide huge changes or logically different changes/fix in the codebase. In this case we're changing our own implementation added in the 1st commit, so not useful 🙏🏼

File: pkg/datapath/l2responder/l2responder_test.go (hunk 6 above)
Comment (Krishnachaitanyakc) [reply pkg/datapath/l2responder/l2responder_test.go]: Good suggestion, I've updated the tests.

File: pkg/datapath/l2responder/l2responder_test.go [hunk 7]
```diff
@@ -526,6 +527,144 @@ func TestIpv6McasMAC(t *testing.T) {
...
+	stats, err = fix.respondermap6.Lookup(ipv6_2, ifidx1)
+	assert.NoError(t, err)
+	assert.Nil(t, stats, "rogue entry ipv6_2 was not deleted from BPF map")
+
+	stats, err = fix.respondermap6.Lookup(ipv6_3, ifidx1)
+	assert.NoError(t, err)
+	assert.Nil(t, stats, "rogue entry ipv6_3 was not deleted from BPF map")
+}
+
```
Comment (smagnani96) [inline pkg/datapath/l2responder/l2responder_test.go:646]: Hey Krishna, I think we're now missing the IPv6 counterpart of `TestFullReconciliationMultipleDesiredPointerReuse`. And given we're adding so many "similar" tests, wdyt if we'd go for (a) table-driven tests and (b) tests both the two condition (1 vs 2+ desired states) in the same test? See below patch.

```suggestion
// Regression test for https://github.com/cilium/cilium/issues/45068
func TestFullReconciliationPointerReuse(t *testing.T) {
	type mapOps struct {
		create func(ip netip.Addr, ifIndex uint32) error
		lookup func(ip netip.Addr, ifIndex uint32) (any, error)
	}

	for _, tt := range []struct {
		name     string
		ips      [3]netip.Addr
		ipLabels [3]string
		mapOpsFn func(fix *fixture) mapOps
	}{
		{
			name:     "v4",
			ips:      [3]netip.Addr{ip1, ip2, ip3},
			ipLabels: [3]string{"ip1", "ip2", "ip3"},
			mapOpsFn: func(fix *fixture) mapOps {
				return mapOps{
					create: fix.respondermap.Create,
					lookup: func(ip netip.Addr, ifIndex uint32) (any, error) {
						return fix.respondermap.Lookup(ip, ifIndex)
					},
				}
			},
		},
		{
			name:     "v6",
			ips:      [3]netip.Addr{ipv6_1, ipv6_2, ipv6_3},
			ipLabels: [3]string{"ipv6_1", "ipv6_2", "ipv6_3"},
			mapOpsFn: func(fix *fixture) mapOps {
				return mapOps{
					create: fix.respondermap6.Create,
					lookup: func(ip netip.Addr, ifIndex uint32) (any, error) {
						return fix.respondermap6.Lookup(ip, ifIndex)
					},
				}
			},
		},
	} {
		t.Run(tt.name, func(t *testing.T) {
			fix := newFixture(t)
			ops := tt.mapOpsFn(fix)

			fix.mockNetlink.LinkByNameFn = func(name string) (netlink.Link, error) {
				return &mockLink{
					attr: netlink.LinkAttrs{Index: ifidx1},
				}, nil
			}

			// Add IP1 only as desired entry in state DB. Therefore, IP2 and IP3
			//  are rouge entries that should be removed from the BPF map.
			txn := fix.stateDB.WriteTxn(fix.proxyNeighborTable)
			_, _, err := fix.proxyNeighborTable.Insert(txn, &tables.L2AnnounceEntry{
				L2AnnounceKey: tables.L2AnnounceKey{
					IP:               tt.ips[0],
					NetworkInterface: if1,
				},
				Origins: []resource.Key{origin1},
			})
			assert.NoError(t, err)
			txn.Commit()

			for _, ip := range tt.ips {
				assert.NoError(t, ops.create(ip, ifidx1))
			}

			err = fix.reconciler.fullReconciliation(fix.stateDB.ReadTxn())
			assert.NoError(t, err)

			stats, err := ops.lookup(tt.ips[0], ifidx1)
			assert.NoError(t, err)
			assert.NotNil(t, stats, "desired entry %s was wrongly deleted from BPF map", tt.ipLabels[0])

			stats, err = ops.lookup(tt.ips[1], ifidx1)
			assert.NoError(t, err)
			assert.Nil(t, stats, "rogue entry %s was not deleted from BPF map", tt.ipLabels[1])

			stats, err = ops.lookup(tt.ips[2], ifidx1)
			assert.NoError(t, err)
			assert.Nil(t, stats, "rogue entry %s was not deleted from BPF map", tt.ipLabels[2])

			// Now add also IP2 as desired entry in state DB. Therefore, IP3 is
			// the only rouge entry that should be removed from the BPF map.
			txn = fix.stateDB.WriteTxn(fix.proxyNeighborTable)
			_, _, err = fix.proxyNeighborTable.Insert(txn, &tables.L2AnnounceEntry{
				L2AnnounceKey: tables.L2AnnounceKey{
					IP:               tt.ips[1],
					NetworkInterface: if1,
				},
				Origins: []resource.Key{origin1},
			})
			assert.NoError(t, err)
			txn.Commit()

			for _, ip := range tt.ips {
				assert.NoError(t, ops.create(ip, ifidx1))
			}

			err = fix.reconciler.fullReconciliation(fix.stateDB.ReadTxn())
			assert.NoError(t, err)

			stats, err = ops.lookup(tt.ips[0], ifidx1)
			assert.NoError(t, err)
			assert.NotNil(t, stats, "desired entry %s was wrongly deleted from BPF map", tt.ipLabels[0])

			stats, err = ops.lookup(tt.ips[1], ifidx1)
			assert.NoError(t, err)
			assert.NotNil(t, stats, "desired entry %s was wrongly deleted from BPF map", tt.ipLabels[1])

			stats, err = ops.lookup(tt.ips[2], ifidx1)
			assert.NoError(t, err)
			assert.Nil(t, stats, "rogue entry %s was not deleted from BPF map", tt.ipLabels[2])
		})
	}
}
```

**Review by smagnani96 — CHANGES_REQUESTED** [review]

**Review by smagnani96 — CHANGES_REQUESTED** [review]
LGTM! Please move changes all in 1 commit, don't address review feedback in a separate one (in this case, we would have 1 commit in the history with an incomplete test suite that is immediately changing the commit after).

**Review by smagnani96 — APPROVED** [review]
LGTM now, thanks again for the contrib 🚀
