### PR TITLE
Validate "ownership" of hostPort service being deleted

### LINKED ISSUE #22460: Pod hostPort not reachable after node restart when GracefulNodeShutdown kublet config set
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We found an issue where the pod hostPort connection is refused, following a node restart, after the old pod is deleted.

Here are the steps to reproduce:
Prerequisite:
1. Ensure that the pods for a deployment are scheduled on the same node. Couple ways to achieve this is by having a node pool with only a single worker node or by using a `nodeSelector` on the single pod deployment. (This issue seems to only be reproduced when the new pod is scheduled on the same node as the old one.)
2. Add the GracefulNodeShutdown in the kubelet config on all nodes by modifying the configuration in `/var/lib/kubelet/config.yaml`
```
 featureGates:
   GracefulNodeShutdown: true
 shutdownGracePeriod: 30s
 shutdownGracePeriodCriticalPods: 10s
```
3. Run `sudo systemctl restart kubelet` on each node to apply the kubelet config change.

Reproduce:

1. Deploy the nginx web server with hostPort set as 8081
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        kubernetes.io/hostname: <node-name>
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          hostPort: 8081
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 20
          httpGet:
            path: /
            port: 80
```
2. ***Important:*** Run `systemctl reboot` on the worker node to restart the machine.
3. After reboot spot the old pod in `Completed` state, while the new pod is `Running`.
```
# k get pods
NAME                                READY   STATUS      RESTARTS   AGE
nginx-deployment-645797c867-8p2hp   0/1     Completed   0          13m
nginx-deployment-645797c867-dx2m8   1/1     Running     0          4m2s
```
4. curl the `nodeIP:hostPort` successfully get the result.
5. Manually deleted the old pod which is in `Completed` state.
6. Redo the curl `nodeIP:hostPort`, but this time the connection refused.

### Cilium Version

v1.12, also on master.

### Kernel Version

 5.4.0-42-generic #46-Ubuntu SMP

### Kubernetes Version

v1.25.4

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by yasz24**
This addresses a bug where deleting a completed pod deletes the service map entry for the corresponding running pod on the same node. This is due to the hostPort mapping keys being the 
same for both old and new pods.

Ideally we should validate whether the (completed) pod being deleted  
"owns" the host port service - to prevent breaking host port 
connectivity for any running pods with the same service as frontend.

This PR adds such a validation.

Testing-
Automated (Control Plane):
This fix is captured by a control plane test case that does the
following:
1. Create a hostport pod, and terminate it's running containers to mark
   it as "Completed".
2. Create another hostport pod using the same port as the "Completed" pod.
3. Delete the "Completed" pod, and verify that the hostport service has
   not been deleted in the Datapath.

Manual Testing -
1. Add the GracefulNodeShutdown in the kubelet config on all nodes by
   modifying the configuration in `/var/lib/kubelet/config.yaml`
   ```
    featureGates:
      GracefulNodeShutdown: true
    shutdownGracePeriod: 30s
    shutdownGracePeriodCriticalPods: 10s
   ```
2. Run `sudo systemctl restart kubelet` on each node to apply the kubelet
   config change
3. Deploy an nginx web server with hostPort set, as well as a
   nodeSelector, so pods get scheduled on the same node after node
   restarts.
   ```
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: nginx-deployment
   spec:
     selector:
       matchLabels:
         app: nginx
    replicas: 1
    template:
      metadata:
        labels:
          app: nginx
      spec:
        nodeSelector:
	  kubernetes.io/hostname: <node-name>
	containers:
	- name: nginx
          image: nginx:1.14.2
          ports:
          - containerPort: 80
            hostPort: 8081
   ```
4. Run `systemctl reboot` on the worker node to restart the machine.
5. After reboot spot the old pod in `Completed state`, while the new pod
   is `Running`.
   ```
   $ kubectl get pods
   NAME                                READY   STATUS      RESTARTS    AGE
   nginx-deployment-645797c867-8p2hp   0/1     Completed   0           13m
   nginx-deployment-645797c867-dx2m8   1/1     Running     0           4m2s
   ```
6. `curl nodeIP:hostPort` successfully get the result.
7. Manually deleted the old pod which is in Completed state.
   ```
   $ kubectl delete pod/nginx-deployment-645797c867-8p2hp
   ```
8. Redo the `curl nodeIP:hostPort`, and successfully get the result again.    // hostPort service has been preserved.

Fixes: #22460

Signed-off-by: Yash Shetty [yashshetty@google.com](mailto:yashshetty@google.com)

### CODE REVIEW

**Review by aanm — CHANGES_REQUESTED** [review]
Thank you for the PR. What happens in case there is only one pod running on the node and that pod is removed? IF we are skipping the generation of service mappings will the entries in the bpf maps be deleted?

File: pkg/k8s/watchers/pod.go [hunk 1]
```diff
@@ -503,6 +503,9 @@ func (k *K8sWatcher) genServiceMappings(pod *slim_corev1.Pod, podIPs []string, l
 		svcs       []loadbalancer.SVC
 		containers []slim_corev1.Container
 	)
+	if !k8sUtils.IsPodRunning(pod.Status) {
+		return svcs
+	}
```
Comment (aditighag) [inline pkg/k8s/watchers/pod.go]: This logic is common to add/update/delete watcher callbacks, so this will leak an entry (<host-ip, host-port>) on a cluster. See http://github.com/cilium/cilium/blob/master/pkg/k8s/watchers/pod.go#L271-L271.

@aanm Why do we need to [call](http://github.com/cilium/cilium/blob/master/pkg/k8s/watchers/pod.go#L220-L220) `deleteK8sPodV1` for non-running pods from the **add** watcher callback? We need to clean up previously saved state only when there is an update for pod state, no?

Screen Shot 2022-12-06 at 4 03 16 PM

**Review by aditighag — CHANGES_REQUESTED** [review]
👋 The fix doesn't look right to me, see the inline comment.

File: pkg/k8s/watchers/pod.go (hunk 1 above)
Comment (yasz24) [reply pkg/k8s/watchers/pod.go]: I see your point about the leaks. The problem essentially boils down to distinguishing between hostPort pods in `completed` status that have a corresponding `running` status pod, versus `completed` pods that don't have a `running` pod.  I think one way to accomplish this could be to add a guard clause when DeleteService is called ([here](https://github.com/cilium/cilium/blob/master/pkg/k8s/watchers/pod.go#L722), and maybe [here](https://github.com/cilium/cilium/blob/master/pkg/k8s/watchers/pod.go#L665) too?), to check the backends IPs for the service being deleted, and validate that it does in fact contain the IP for the completed pod as one of the backends. That way we know that the service being deleted "belongs" to the `completed` pod, and we won't mistakenly break hostPort connectivity for the corresponding `running` pod on the same node, by deleting the service whose "ownership" has since transferred to the `running` pod. The question is whether there is an easy way to get the service's map entries (current backends) in `pkg/k8s/watchers/pod.go` to perform this check? I'm not super familiar with this code, so any thoughts would be appreciated!

Comment (aditighag) [reply pkg/k8s/watchers/pod.go]: >The problem essentially boils down to distinguishing between hostPort pods in completed status that have a corresponding running status pod, versus completed pods that don't have a running.

Given that k8s allows only 1 unique <host ip, host port> pod to be deployed at a time, don't we expect that the cilium agent will first receive an event for the completed pod followed by an event for the running pod?

**Comment by squeed** [comment]
One possible option - though it's a pretty significant refactor - is to manage HostPort mappings via CNI capability arguments rather than via pod objects. This would then serialize hostport mappings via the kubelet.

**Comment by squeed** [comment]
I also wonder if we can elide the pod deletion entirely if the pod is newly "Completed" when we first see it?

File: pkg/k8s/watchers/pod.go (hunk 1 above)
Comment (aanm) [reply pkg/k8s/watchers/pod.go]: > > The problem essentially boils down to distinguishing between hostPort pods in completed status that have a corresponding running status pod, versus completed pods that don't have a running.
> 
> Given that k8s allows only 1 unique <host ip, host port> pod to be deployed at a time, don't we expect that the cilium agent will first receive an event for the completed pod followed by an event for the running pod?

@aditighag no, they can be random.

**Comment by yasz24** [comment]
> One possible option - though it's a pretty significant refactor - is to manage HostPort mappings via CNI capability arguments rather than via pod objects. This would then serialize hostport mappings via the kubelet.

@squeed  IIUC, the issue isn't really caused by a race condition, so serializing the hostport mappings wouldn't help us I believe. I think what we really need is a way to know if the hostPort mappings "belong" to the  "completed" pod being deleted or not. One way to do that would be to inspect the hostPort mappings for the service in question, and verifying that the IP for the "completed" pod is one of the backends. But I wasn't able to find any APIs to do a simple lookup for a service's hostPort mappings to verify this (`GetService` or similar on the [svcManager](https://github.com/cilium/cilium/blob/master/pkg/k8s/watchers/watcher.go#L142) could help accomplish this)

**Comment by yasz24** [comment]
Hi, @squeed, @aditighag, @aanm. Update PR with an alternative fix, that checks the "ownership" of the hostPort service before deleting it. PTAL whenever you have the chance. Thanks!

File: pkg/k8s/watchers/pod.go [hunk 2]
```diff
@@ -719,6 +719,11 @@ func (k *K8sWatcher) deleteHostPortMapping(pod *slim_corev1.Pod, podIPs []string
 	}
 
 	for _, dpSvc := range svcs {
+		svcs := k.svcManager.GetDeepCopyServices()
+		svc := findServiceByL3n4Addr(dpSvc.Frontend.L3n4Addr, svcs)
+		if svc != nil && !deepEqualBackends(svc.Backends, dpSvc.Backends) {
```
Comment (squeed) [inline pkg/k8s/watchers/pod.go]: makes sense; can you add a comment for what this does?

**Comment by squeed** [comment]
Nice and simple; I like it.

Can you think of any way to test this? The integration tests (in `/test/k8s`) are allowed to arbitrarily disrupt the cluster, so there's no need to be a "good citizen".

**Comment by squeed** [comment]
(p.s. can you rebase to make CI slightly happier)?

**Comment by aditighag** [comment]
@yasz24 Can you check if this [PR: Endpoint/CEP Ownership Fix](https://github.com/cilium/cilium/pull/21768) resolves this issue, or something that you can extend?  /cc @tommyp1ckles

File: pkg/k8s/watchers/pod.go [hunk 3]
```diff
@@ -719,6 +719,11 @@ func (k *K8sWatcher) deleteHostPortMapping(pod *slim_corev1.Pod, podIPs []string
 	}
 
 	for _, dpSvc := range svcs {
+		svcs := k.svcManager.GetDeepCopyServices()
```
Comment (tommyp1ckles) [inline pkg/k8s/watchers/pod.go]: Copying all of these, in each loop iteration, seems like it might be a bit heavy?

**Comment by tommyp1ckles** [comment]
> @yasz24 Can you check if the [PR: Endpoint/CEP Ownership Fix](https://github.com/cilium/cilium/pull/21768) resolves this issue, or something that you can extend? /cc @tommyp1ckles

I don't think so, similar class of issues though. That one dealt with ownership of Endpoints -> CiliumEndpoints. This one appears to deal with Pod ownership of Service entries.

File: pkg/k8s/watchers/pod.go (hunk 2 above)
Comment (yasz24) [reply pkg/k8s/watchers/pod.go]: will do

File: pkg/k8s/watchers/pod.go (hunk 3 above)
Comment (yasz24) [reply pkg/k8s/watchers/pod.go]: Good catch! Yes, there is definitely no need for the service copies to be retrieved in each iteration, and the operation can definitely be moved outside the for-loop. Will go ahead and do so 👍

File: pkg/k8s/watchers/pod.go [hunk 4]
```diff
@@ -719,6 +719,11 @@ func (k *K8sWatcher) deleteHostPortMapping(pod *slim_corev1.Pod, podIPs []string
...
+		svc := findServiceByL3n4Addr(dpSvc.Frontend.L3n4Addr, svcs)
```
Comment (squeed) [inline pkg/k8s/watchers/pod.go]: You can skip all this looping (and the full deepcopy above) by adding this method to the ServiceManager:

```go
func (s *Service) GetDeepCopyServiceByFrontend(frontend lb.L3n4Addr) (*lb.SVC, bool) {
	s.Lock()
	defer s.Unlock()

	if svc, found := s.svcByHash[frontend.Hash()]; found {
		return svc.deepCopyToLBSVC(), true
	}

	return nil, false
}
```

Then you won't need `findServiceByL3nL4Addr` or the full `GetDeepCopyServices`. Saves a lot of allocs and looping.

**Review by squeed — CHANGES_REQUESTED** [review]

File: pkg/k8s/watchers/pod.go (hunk 3 above)
Comment (squeed) [reply pkg/k8s/watchers/pod.go]: commented below; we can simplify this even more :-)

**Review by aditighag — COMMENTED** [review]
Logic looks good to me. Please incorporate Casey's suggestion in the implementation. Thanks! How did you test the fix, and I was wondering if you had any thoughts on adding tests? See - https://github.com/cilium/cilium/tree/master/test/controlplane.

File: pkg/k8s/watchers/pod.go (hunk 3 above)
Comment (aditighag) [inline pkg/k8s/watchers/pod.go]: The ownership check also warrant a code comment explaining the motivation.

File: pkg/k8s/watchers/pod.go [hunk 5]
```diff
@@ -728,6 +733,28 @@ func (k *K8sWatcher) deleteHostPortMapping(pod *slim_corev1.Pod, podIPs []string
...
+		}
+	}
+	return nil
+}
+
+func deepEqualBackends(backends1 []*loadbalancer.Backend, backends2 []*loadbalancer.Backend) bool {
+	if len(backends1) != len(backends2) {
+		return false
+	}
+	for idx, backend1 := range backends1 {
```
Comment (tommyp1ckles) [inline pkg/k8s/watchers/pod.go]: are we sure these will always be in the same order?

File: pkg/k8s/watchers/pod.go (hunk 3 above)
Comment (yasz24) [reply pkg/k8s/watchers/pod.go]: done

File: pkg/k8s/watchers/pod.go (hunk 4 above)
Comment (yasz24) [reply pkg/k8s/watchers/pod.go]: Done!

File: pkg/k8s/watchers/pod.go (hunk 3 above)
Comment (yasz24) [reply pkg/k8s/watchers/pod.go]: Done!

File: pkg/k8s/watchers/pod.go (hunk 5 above)
Comment (yasz24) [reply pkg/k8s/watchers/pod.go]: Good point, i'm not sure if we can assume they will be in the same order. Updated the deepEquals logic to be order agnostic. PTAL

File: pkg/k8s/watchers/pod.go [hunk 6]
```diff
@@ -731,6 +742,37 @@ func (k *K8sWatcher) deleteHostPortMapping(pod *slim_corev1.Pod, podIPs []string
 	return nil
 }
 
+func findServiceByL3n4Addr(l3n4Addr loadbalancer.L3n4Addr, svcs []*loadbalancer.SVC) *loadbalancer.SVC {
```
Comment (squeed) [inline pkg/k8s/watchers/pod.go]: You can delete this function now :-)

File: pkg/k8s/watchers/watcher.go [hunk 7]
```diff
@@ -141,6 +141,8 @@ type policyRepository interface {
 
 type svcManager interface {
 	DeleteService(frontend loadbalancer.L3n4Addr) (bool, error)
+	GetDeepCopyServices() []*loadbalancer.SVC
```
Comment (squeed) [inline pkg/k8s/watchers/watcher.go]: We can remove this from the interface now, right?

File: pkg/k8s/watchers/pod.go [hunk 8]
```diff
@@ -731,6 +742,37 @@ func (k *K8sWatcher) deleteHostPortMapping(pod *slim_corev1.Pod, podIPs []string
...
+
+	l3n4AddrMap := make(map[string]*loadbalancer.Backend)
+
+	for _, backend1 := range backends1 {
+		l3n4AddrMap[backend1.L3n4Addr.AddrCluster.String()] = backend1
+	}
+
+	for _, backend2 := range backends2 {
+		backend1 := l3n4AddrMap[backend2.L3n4Addr.AddrCluster.String()]
+		if backend1.L3n4Addr.DeepEqual(&backend2.L3n4Addr) {
```
Comment (squeed) [inline pkg/k8s/watchers/pod.go]: need to add a nil check here too

Comment (squeed) [reply pkg/k8s/watchers/pod.go]: (backend1 could be nil)

**Comment by squeed** [comment]
two small things then this will be good from my side.

File: pkg/k8s/watchers/pod.go [hunk 9]
```diff
@@ -731,6 +742,37 @@ func (k *K8sWatcher) deleteHostPortMapping(pod *slim_corev1.Pod, podIPs []string
...
+	}
+	return nil
+}
+
+func deepEqualBackends(backends1 []*loadbalancer.Backend, backends2 []*loadbalancer.Backend) bool {
+	if len(backends1) != len(backends2) {
+		return false
+	}
+
+	l3n4AddrMap := make(map[string]*loadbalancer.Backend)
```
Comment (aditighag) [inline pkg/k8s/watchers/pod.go]: The slice length is known, so might as well use it?

Edit: Didn't realize that you were creating a map, nvm.

File: pkg/k8s/watchers/pod.go [hunk 10]
```diff
@@ -731,6 +742,37 @@ func (k *K8sWatcher) deleteHostPortMapping(pod *slim_corev1.Pod, podIPs []string
...
+
+	for _, backend1 := range backends1 {
+		l3n4AddrMap[backend1.L3n4Addr.AddrCluster.String()] = backend1
+	}
+
+	for _, backend2 := range backends2 {
+		backend1 := l3n4AddrMap[backend2.L3n4Addr.AddrCluster.String()]
```
Comment (aditighag) [inline pkg/k8s/watchers/pod.go]:
```suggestion
		if backend1, ok := l3n4AddrMap[backend2.L3n4Addr.AddrCluster.String()]; ok {
		:
		}
```

**Review by aditighag — CHANGES_REQUESTED** [review]

File: pkg/k8s/watchers/pod.go (hunk 6 above)
Comment (yasz24) [reply pkg/k8s/watchers/pod.go]: yes :)

File: pkg/k8s/watchers/watcher.go (hunk 7 above)
Comment (yasz24) [reply pkg/k8s/watchers/watcher.go]: removed!

File: pkg/k8s/watchers/pod.go (hunk 8 above)
Comment (yasz24) [reply pkg/k8s/watchers/pod.go]: Added!

File: pkg/k8s/watchers/pod.go (hunk 9 above)
Comment (yasz24) [reply pkg/k8s/watchers/pod.go]: Not sure which slice you're referring to?

File: pkg/k8s/watchers/pod.go (hunk 10 above)
Comment (yasz24) [reply pkg/k8s/watchers/pod.go]: Done!

**Comment by yasz24** [comment]
Thank you for all the great feedback! I've addressed most of the code related comments, PTAL again whenever you have the chance! 

As far as testing is concerned, I added details about how I manually tested the fix in the PR description, and the commit message. I was looking into how I might add an integration test, and it seemed a bit complex, since I'd have to basically recreate the manual test in an automated way. This would entail ssh'ing into the worker node on which the pod is deployed, editing the kublet config, restarting kubelet, followed by restarting the entire node itself. 

I couldn't find any examples of ssh'ing into the node in /test/k8s. Not sure how easy it would be to do that. Let me know if you guys have any thoughts or if you think the manual test would be sufficient here. Thanks!

File: pkg/k8s/watchers/pod.go [hunk 11]
```diff
@@ -731,6 +742,27 @@ func (k *K8sWatcher) deleteHostPortMapping(pod *slim_corev1.Pod, podIPs []string
...
+	}
+
+	l3n4AddrMap := make(map[string]*loadbalancer.Backend)
+
+	for _, backend1 := range backends1 {
+		l3n4AddrMap[backend1.L3n4Addr.AddrCluster.String()] = backend1
+	}
+
+	for _, backend2 := range backends2 {
+		if backend1, ok := l3n4AddrMap[backend2.L3n4Addr.AddrCluster.String()]; ok && backend1.L3n4Addr.DeepEqual(&backend2.L3n4Addr) {
```
Comment (aditighag) [inline pkg/k8s/watchers/pod.go]: Why call the `DeepEqual` method if there was a look up done based on the `L3nL4Addr` string?

Comment (yasz24) [reply pkg/k8s/watchers/pod.go]: Good point. Could the `L4Addr`  or `Scope` in the `L3n4Addr` differ for two backends with the same IP? If not, i think we could definitely get rid of the `DeepEqual` check 👍

**Comment by aditighag** [comment]
> Thank you for all the great feedback! I've addressed most of the code related comments, PTAL again whenever you have the chance!
> 
> As far as testing is concerned, I added details about how I manually tested the fix in the PR description, and the commit message. I was looking into how I might add an integration test, and it seemed a bit complex, since I'd have to basically recreate the manual test in an automated way. This would entail ssh'ing into the worker node on which the pod is deployed, editing the kublet config, restarting kubelet, followed by restarting the entire node itself.
> 
> I found examples of exec'ing into the pod, but couldn't find any examples of ssh'ing into the node in `/test/k8s`. Not sure how easy it would be to do that. Let me know if you guys have any thoughts or if you think the manual test would be sufficient here. Thanks!

I would've expected to also reproduce the issue by stopping the cilium agent when a host port pod switches state, and another one with overlapping port comes up. We have runtime tests to induce such scenarios, but it's probably ok to rely on the manual testing/code comments for now.

File: pkg/k8s/watchers/pod.go (hunk 11 above)
Comment (yasz24) [reply pkg/k8s/watchers/pod.go]: Actually, now that I think of it, I think we could just use the `backend2.String()` as the map key, instead of using the `backend2.L3n4Addr.AddrCluster.String()`. Then we don't need the `DeepEqual` check. Will update 👍

Comment (yasz24) [reply pkg/k8s/watchers/pod.go]: Done!

File: pkg/k8s/watchers/pod.go [hunk 12]
```diff
@@ -733,6 +744,27 @@ func (k *K8sWatcher) deleteHostPortMapping(pod *slim_corev1.Pod, podIPs []string
...
 
+func deepEqualBackends(backends1 []*loadbalancer.Backend, backends2 []*loadbalancer.Backend) bool {
+	if len(backends1) != len(backends2) {
+		return false
+	}
+
+	l3n4AddrMap := make(map[string]*loadbalancer.Backend)
+
+	for _, backend1 := range backends1 {
+		l3n4AddrMap[backend1.String()] = backend1
```
Comment (aditighag) [inline pkg/k8s/watchers/pod.go]: Why not use `backend1.L3n4Addr.String()` for comparing backends? The backend structure has different attributes besides the L3nL4 address, and while the `String()` method currently returns only the L3nL4 address in the string format, it's better to not rely on that being the case (especially since we don't have any tests covering this logic).

Comment (yasz24) [reply pkg/k8s/watchers/pod.go]: Makes sense. Agreed that it's probably better to be explicit. Updated!

**Review by aditighag — APPROVED** [review]

**Comment by yasz24** [comment]
Hi @squeed @aanm, PTAL again whenever you have the chance, and let me know if this looks good for your approval!

**Review by squeed — APPROVED** [review]

**Comment by aditighag** [comment]
@yasz24 Can you rebase the PR? It'll resolve the Travis failure. We can trigger the e2e tests once you've rebased.

**Comment by yasz24** [comment]
@aditighag, rebased!

File: pkg/service/service.go [hunk 13]
```diff
@@ -944,6 +944,18 @@ func (s *Service) GetDeepCopyServicesByName(name, namespace string) (svcs []*lb.
 	return svcs
 }
 
+// GetDeepCopyServiceByFrontend returns a deep-copy of the service that matches the Frontend address.
+func (s *Service) GetDeepCopyServiceByFrontend(frontend lb.L3n4Addr) (*lb.SVC, bool) {
+	s.Lock()
+	defer s.Unlock()
```
Comment (aanm) [inline pkg/service/service.go]:
```suggestion
	s.RLock()
	defer s.RUnlock()
```

**Review by aanm — CHANGES_REQUESTED** [review]
Just some small nits from my side. @aditighag where can we add some tests covering this?

File: pkg/k8s/watchers/pod.go [hunk 14]
```diff
@@ -736,6 +747,27 @@ func (k *K8sWatcher) deleteHostPortMapping(pod *slim_corev1.Pod, podIPs []string
...
+	}
+
+	l3n4AddrMap := make(map[string]*loadbalancer.Backend)
+
+	for _, backend1 := range backends1 {
+		l3n4AddrMap[backend1.L3n4Addr.String()] = backend1
+	}
+
+	for _, backend2 := range backends2 {
+		if _, ok := l3n4AddrMap[backend2.L3n4Addr.String()]; ok {
```
Comment (aanm) [inline pkg/k8s/watchers/pod.go]:
```suggestion
	l3n4AddrMap := make(map[loadbalancer.L3n4Addr]struct{})

	for _, backend1 := range backends1 {
		l3n4AddrMap[backend1.L3n4Addr] = struct{}{}
	}

	for _, backend2 := range backends2 {
		if _, ok := l3n4AddrMap[backend2.L3n4Addr]; ok {
```

**Review by aanm — CHANGES_REQUESTED** [review]
This should have been part of the previous review

**Comment by aditighag** [comment]
> @aditighag where can we add some tests covering this?

@aanm Here is my previous comment - https://github.com/cilium/cilium/pull/22587#pullrequestreview-1253905966. 

@yasz24 The control plane tests lie somewhere between an e2e integration test and package specific unit tests. I think we can use the infrastructure to validate this fix (and any regressions in future) without having to rely on manual tests. I would imagine that you can write a new test that creates following events to simplify some of the manual steps like node reboot, agent restart, etc:

- Watcher event that leads to host port service entry being created
- Watcher update event for the pod in `completed` state, and new pod with overlapping host port
- Check service entries 
- Delete the `complete`d pod
- Check service entries

/cc @joamaki can give pointers. Feel free to reach out on the #development slack channel.

**Review by tommyp1ckles — APPROVED** [review]

**Comment by yasz24** [comment]
Ack. will work on writing the tests soon

**Comment by joestringer** [comment]
Thanks for your contribution. I have marked the PR as draft while the feedback is addressed. Once you're ready for further review, click the "Ready for review" button at the bottom of the page.

File: test/controlplane/pod/hostport/hostport.go [hunk 15]
```diff
@@ -0,0 +1,58 @@
...
+	k8sVersions := controlplane.K8sVersions()
+	// We only need to test the last k8s version
+	test := suite.NewControlPlaneTest(t, "pod-hostport-control-plane", k8sVersions[len(k8sVersions)-1])
+	defer test.StopAgent()
+
+	// Feed in initial state and start the agent.
+	test.
+		UpdateObjectsFromFile(abs("init.yaml")).
+		SetupEnvironment(modConfig).
+		StartAgent().
```
Comment (aojea) [inline test/controlplane/pod/hostport/hostport.go:42]: @joamaki we are stuck with the test, it hangs at this point and it never move forward, we compared with the other tests and we can't see anything obvious, can you help us to understand what is missing?

It seems that it is waiting for a local node initialization
```
oroutine 118 [chan receive, 9 minutes]:
github.com/cilium/cilium/daemon/cmd.(*localNodeInitializer).getK8sLocalNode(0xc000e9c6f0, {0x3ed7ef8?, 0xc000527b80?})
        /usr/local/google/home/aojea/src/cilium/daemon/cmd/local_node_init.go:87 +0xec
github.com/cilium/cilium/daemon/cmd.(*localNodeInitializer).initFromK8s(0xc000e9c6f0, {0x3ed7ef8?, 0xc000527b80?}, 0xc0001ea178)
        /usr/local/google/home/aojea/src/cilium/daemon/cmd/local_node_init.go:101 +0x5b
github.com/cilium/cilium/daemon/cmd.(*localNodeInitializer).InitLocalNode(0x4b1886?, {0x3ed7ef8, 0xc000527b80}, 0xc0001ea178)
        /usr/local/google/home/aojea/src/cilium/daemon/cmd/local_node_init.go:48 +0x9e
github.com/cilium/cilium/pkg/node.NewLocalNodeStore.func1({0x7f30000e7d00?, 0xc000527b80})
        /usr/local/google/home/aojea/src/cilium/pkg/node/local_node_store.go:81 +0x187
github.com/cilium/cilium/pkg/hive.Hook.Start(...)
        /usr/local/google/home/aojea/src/cilium/pkg/hive/lifecycle.go:35
github.com/cilium/cilium/pkg/hive.(*DefaultLifecycle).Start(0xc00123e420, {0x3ed7f30?, 0xc000226008?})
        /usr/local/google/home/aojea/src/cilium/pkg/hive/lifecycle.go:104 +0x2ee
github.com/cilium/cilium/pkg/hive.(*Hive).Start(0xc00127cb40, {0x3ed7f30, 0xc000226008})
        /usr/local/google/home/aojea/src/cilium/pkg/hive/hive.go:295 +0x105
github.com/cilium/cilium/test/controlplane/suite.startCiliumAgent(0xc000303ba0, {0x3f17488?, 0xc0012291c0}, {0x3ec03d0?, 0x63b9620})
        /usr/local/google/home/aojea/src/cilium/test/controlplane/suite/agent.go:105 +0x785
github.com/cilium/cilium/test/controlplane/suite.(*ControlPlaneTest).StartAgent(0xc001261770, {0x0, 0x0, 0x0})
        /usr/local/google/home/aojea/src/cilium/test/controlplane/suite/testcase.go:141 +0xe5
github.com/cilium/cilium/test/controlplane/services/hostport.testHostPort(0xc000303ba0)
        /usr/local/google/home/aojea/src/cilium/test/controlplane/services/hostport/hostport.go:42 +0x1f2
testing.tRunner(0xc000303ba0, 0x3ae3388)
        /usr/local/google/home/aojea/sdk/go1.20.4/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
        /usr/local/google/home/aojea/sdk/go1.20.4/src/testing/testing.go:1629 +0x3ea
```

File: test/controlplane/pod/hostport/hostport.go [hunk 16]
```diff
@@ -0,0 +1,58 @@
...
+		t.Fatal(err)
+	}
+
+	abs := func(f string) string { return path.Join(cwd, "pod", "hostport", f) }
+
+	modConfig := func(daemonCfg *agentOption.DaemonConfig, _ *operatorOption.OperatorConfig) {}
+
+	k8sVersions := controlplane.K8sVersions()
+	// We only need to test the last k8s version
+	test := suite.NewControlPlaneTest(t, "pod-hostport-control-plane", k8sVersions[len(k8sVersions)-1])
```
Comment (aojea) [inline test/controlplane/pod/hostport/hostport.go]:
```suggestion
	test := suite.NewControlPlaneTest(t, "hostport-control-plane", k8sVersions[len(k8sVersions)-1])
```

this has to match teh name of the control plane node on the init.yaml file, otherwise it does not start waiting for the local node

File: test/controlplane/pod/hostport/hostport.go (hunk 15 above)
Comment (aojea) [reply test/controlplane/pod/hostport/hostport.go:42]: found the problem https://github.com/cilium/cilium/pull/22587/files#r1244016712

File: test/controlplane/pod/hostport/generate.sh [hunk 17]
```diff
@@ -0,0 +1,60 @@
...
+
+: Preloading images
+kind load --name hostport docker-image "${cilium_container_repo}/${cilium_container_image}:${cilium_version}" || true
+kind load --name hostport docker-image "${cilium_container_repo}/${cilium_operator_container_image}:${cilium_version}" || true || true
+
+: Install cilium
+cilium install --wait
+
+: Dump the initial state
+kubectl get nodes,pods -o yaml > "${dir}/init.yaml"
```
Comment (aojea) [inline test/controlplane/pod/hostport/generate.sh:30]:
```suggestion
kubectl get nodes,ciliumnodes,pods -o yaml > "${dir}/init.yaml"
```

with your PR it fails in one endpoint to me, I regenerated and also added this , but I'm not sure this makes a difference

File: test/controlplane/pod/hostport/hostport.go (hunk 16 above)
Comment (yasz24) [reply test/controlplane/pod/hostport/hostport.go]: done!

File: test/controlplane/pod/hostport/generate.sh (hunk 17 above)
Comment (yasz24) [reply test/controlplane/pod/hostport/generate.sh:30]: I don't think this is necessary (getting ciliumnodes). Passes for me as is.

**Comment by yasz24** [comment]
@aanm @aditighag @squeed I have added the control-plane test as requested. PTAL

cc @aojea

File: test/controlplane/pod/hostport/manifests/hostport-2.yaml [hunk 18]
```diff
@@ -0,0 +1,19 @@
...
+    image: nginx:1.14.2
+    ports:
+    - containerPort: 80
+      hostPort: 8081
+    readinessProbe:
+      initialDelaySeconds: 30
+      periodSeconds: 20
+      httpGet:
+        path: /
+        port: 80
```
Comment (aojea) [inline test/controlplane/pod/hostport/manifests/hostport-2.yaml]: end of line

File: test/controlplane/pod/hostport/manifests/hostport-1.yaml [hunk 19]
```diff
@@ -0,0 +1,19 @@
...
+    image: nginx:1.14.2
+    ports:
+    - containerPort: 80
+      hostPort: 8081
+    readinessProbe:
+      initialDelaySeconds: 30
+      periodSeconds: 20
+      httpGet:
+        path: /
+        port: 80
```
Comment (aojea) [inline test/controlplane/pod/hostport/manifests/hostport-1.yaml]: add end of line

**Comment by aojea** [comment]
lgtm, two nits only about the the empty line in the end of two files

File: test/controlplane/pod/hostport/manifests/hostport-2.yaml (hunk 18 above)
Comment (yasz24) [reply test/controlplane/pod/hostport/manifests/hostport-2.yaml]: done

File: test/controlplane/pod/hostport/manifests/hostport-1.yaml (hunk 19 above)
Comment (yasz24) [reply test/controlplane/pod/hostport/manifests/hostport-1.yaml]: done

**Review by squeed — APPROVED** [review]
nice work!

File: pkg/k8s/watchers/pod.go [hunk 20]
```diff
@@ -782,6 +793,27 @@ func (k *K8sWatcher) deleteHostPortMapping(pod *slim_corev1.Pod, podIPs []string
 	return nil
 }
 
+func deepEqualBackends(backends1 []*loadbalancer.Backend, backends2 []*loadbalancer.Backend) bool {
```
Comment (nebril) [inline pkg/k8s/watchers/pod.go]: Would be nice to get a unit test for this function.

Comment (nebril) [inline pkg/k8s/watchers/pod.go]: AFAIU this function doesn't care about backend order in provided slices, can you add a comment about that?

**Review by nebril — COMMENTED** [review]
Thanks for the PR! LGTM overall, please add the missing unit test, otherwise it's good to go!

File: pkg/k8s/watchers/pod.go (hunk 20 above)
Comment (yasz24) [reply pkg/k8s/watchers/pod.go]: Done!

Comment (yasz24) [reply pkg/k8s/watchers/pod.go]: Done!

**Review by nebril — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by borkmann** [comment]
@yasz24 looks like the PR broke Go code precheck test on master, could you take a look and fix? Thanks

https://github.com/cilium/cilium/actions/runs/5483316043/jobs/9989522587
```
[...]
contrib/scripts/lock-check.sh
contrib/scripts/check-viper.sh
contrib/scripts/custom-vet-check.sh
-: # github.com/cilium/cilium/test/controlplane/pod/hostport
Error: test/controlplane/pod/hostport/hostport.go:39:2: not enough arguments in call to test.UpdateObjectsFromFile(abs("init.yaml")).SetupEnvironment(modConfig).StartAgent
	have ()
	want (func(*"github.com/cilium/cilium/pkg/option".DaemonConfig), ...cell.Cell)
Error: test/controlplane/pod/hostport/hostport.go:41:20: too many arguments in call to test.UpdateObjectsFromFile(abs("init.yaml")).SetupEnvironment
	have (func(daemonCfg *"github.com/cilium/cilium/pkg/option".DaemonConfig, _ *"github.com/cilium/cilium/operator/option".OperatorConfig))
	want ()
Error: /home/runner/work/cilium/cilium/src/github.com/cilium/cilium/test/controlplane/pod/hostport/hostport.go:41:20: too many arguments in call to test.UpdateObjectsFromFile(abs("init.yaml")).SetupEnvironment
	have (func(daemonCfg *"github.com/cilium/cilium/pkg/option".DaemonConfig, _ *"github.com/cilium/cilium/operator/option".OperatorConfig))
	want ()
Error: /home/runner/work/cilium/cilium/src/github.com/cilium/cilium/test/controlplane/pod/hostport/hostport.go:42:[14](https://github.com/cilium/cilium/actions/runs/5483316043/jobs/9989522587#step:4:15): not enough arguments in call to test.UpdateObjectsFromFile(abs("init.yaml")).SetupEnvironment(modConfig).StartAgent
	have ()
	want (func(*"github.com/cilium/cilium/pkg/option".DaemonConfig), ...cell.Cell)
customvet: 3 errors during loading
exit status 1
make: *** [Makefile:653: precheck] Error 1
Error: Process completed with exit code 2.
```

**Comment by pippolo84** [comment]
> @yasz24 looks like the PR broke Go code precheck test on master, could you take a look and fix? Thanks
> 

Fix is very simple, [here](https://github.com/cilium/cilium/pull/26685) the PR.
