### PR TITLE
bpf: exclude pod's reply traffic from egress gateway logic

### LINKED ISSUE #17866: Reply traffic from pods matching a policy is incorrectly being SNAT'ed
In [bpf_lxc](https://github.com/cilium/cilium/blob/701cfb62549173027fcc3ab497cb9dea8ec38da2/bpf/bpf_lxc.c#L797-L811) the logic to forward traffic to an egress gateway does not check if the traffic is actually originating from the pod.

This means that if an external client connects to a pod which is selected by an egress policy (and the source IP of the client matches the destinationCIDR of the policy), the reply traffic will be incorrectly forwarded to an egress gateway and SNAT'ed, disrupting the connection.

To prevent this, before forwarding a packet to an egress gateway we should make sure that said packet is not a reply, similarly to what we are already doing in [nodeport.h](https://github.com/cilium/cilium/blob/701cfb62549173027fcc3ab497cb9dea8ec38da2/bpf/lib/nodeport.h#L1183-L1191).

### PR DESCRIPTION
**Pull request by jibi**
Currently all pod traffic matching source IP and destination CIDR of an
egress policy will be forwarded to an egress gateway.

This means we will incorrectly forward to an egress gateway also all
reply traffic from connections destined to a pod, breaking said
connections.

This commit fixes this by adding an additional check to make sure reply
traffic (i.e. connections not originating from a pod) is excluded from
the egress gateway logic.

Fixes: #17866
Signed-off-by: Gilberto Bertin <gilberto@isovalent.com>

### CODE REVIEW

**Comment by brb** [comment]
I think we might want to have a CI test for it.

**Review by kkourt — APPROVED** [review]

File: bpf/bpf_lxc.c [hunk 1]
```diff
@@ -803,6 +804,15 @@ static __always_inline int handle_ipv4_from_lxc(struct __ctx_buff *ctx,
 		if (!info)
 			goto skip_egress_gateway;
 
+		/* If the packet is a reply, it means that outside has initiated
+		 * the connection, and so we should skip egress gateway, since
+		 * an egress policy is only matching connections originating
+		 * from a pod.
+		 */
+		if (!ct_is_reply4(get_ct_map4(&tuple), ctx, ETH_HLEN + ipv4_hdrlen(ip4), &tuple,
+				  &is_reply) && is_reply)
```
Comment (pchaigno) [inline bpf/bpf_lxc.c]: Can't we use `ret != CT_REPLY` instead of doing a new map lookup here?

File: bpf/lib/nodeport.h [hunk 2]
```diff
@@ -1167,29 +1182,27 @@ static __always_inline bool snat_v4_needed(struct __ctx_buff *ctx, __be32 *addr,
...
-				*addr = einfo->egress_ip;
-				*from_endpoint = true;
-				return true;
+				/* If the packet is a reply it means that the
+				 * connection did not originate from a pod,
+				 * and so we should skip SNAT (similar to how we
+				 * skipped forwarding the packet over the tunnel
+				 * to the egress gateway in bpf_lxc)
+				 */
+				if (!ct_is_reply) {
```
Comment (pchaigno) [inline bpf/lib/nodeport.h]: Shouldn't we check *before* the egress map lookup, to avoid an unnecessary lookup?

Comment (pchaigno) [inline bpf/lib/nodeport.h]: If `ep` is NULL, `ct_is_reply` will always be false, even if it is actually reply traffic, because we will never execute `ct_is_reply4` above. Or am I missing something?

File: test/k8sT/Egress.go [hunk 3]
```diff
@@ -149,6 +154,37 @@ var _ = SkipDescribeIf(func() bool {
 		// DNS query should work (pod-to-pod connectivity)
 		res = kubectl.ExecPodCmd(randomNamespace, srcPod, "dig kubernetes +time=2")
 		res.ExpectSuccess()
+
+		if ciliumOpts["tunnel"] == "disabled" {
```
Comment (pchaigno) [inline test/k8sT/Egress.go:177]: Why this check? Does the bug not affect tunneling mode?

File: test/k8sT/Egress.go [hunk 4]
```diff
@@ -149,6 +154,37 @@ var _ = SkipDescribeIf(func() bool {
...
+			targetPodHostIP, err := targetPodJSON.Filter("{.status.hostIP}")
+			Expect(err).Should(BeNil(), "Cannot get target pod host IP")
+
+			targetPodIP, err := targetPodJSON.Filter("{.status.podIP}")
+			Expect(err).Should(BeNil(), "Cannot get target pod IP")
+
+			outsideNodeName, outsideNodeIP := kubectl.GetNodeInfo(helpers.GetNodeWithoutCilium())
+
+			// Add a route for the target pod's IP on the node running without Cilium to
+			// allow reaching it from outside the cluster
```
Comment (pchaigno) [inline test/k8sT/Egress.go:196]: Can't we expose the pod via a NodePort service instead? I'm guessing it's because we use a direct route that we can't run this in tunneling mode?

**Review by pchaigno — CHANGES_REQUESTED** [review]

File: bpf/bpf_lxc.c (hunk 1 above)
Comment (jibi) [reply bpf/bpf_lxc.c]: Ah, I think we can :+1: 

I got fooled by the `CT_EGRESS` param passed to the `ct_lookup4()` call above, but I just noticed that this will set `tuple->flags` to `TUPLE_F_IN` and so we'll end up with the same key set by `ct_is_reply4()`

File: bpf/lib/nodeport.h (hunk 2 above)
Comment (jibi) [reply bpf/lib/nodeport.h]: We want to skip SNAT only if traffic is both coming from a local endpoint/pod and is reply traffic, so if the first condition is false (`ep == NULL`) we don't really care if it's reply traffic or not

File: test/k8sT/Egress.go (hunk 4 above)
Comment (jibi) [reply test/k8sT/Egress.go:196]: > Can't we expose the pod via a NodePort service instead?

That's what I initially tried (https://github.com/cilium/cilium/commit/61eecd0123e548832348d27ec2ef801e0c6c893f) but that test was succeeding even without the reply traffic checks, since to my understanding:
* if the target pod is running on the same node to which we connect to, once we get a reply from the pod we will jump to a different program before even looking up the egress gw policy: https://github.com/cilium/cilium/blob/master/bpf/bpf_lxc.c#L710-L714
* if the target pod is running on a different node, the node to which we connected to is going to SNAT the traffic with its own IP before forwarding it to the second node, and so even in this case the egress gw logic will be skipped since the reply traffic is destined to a remote node (https://github.com/cilium/cilium/blob/master/bpf/bpf_lxc.c#L799)

> I'm guessing it's because we use a direct route that we can't run this in tunneling mode?

Yep, since we can't use a nodeport I run this test only in direct routing. This actually works even in tunneling mode (since `bpf_host` is attached anyway to the physical device), I'm just not sure it's worth having that test :thinking:

File: bpf/lib/nodeport.h (hunk 2 above)
Comment (pchaigno) [reply bpf/lib/nodeport.h]: Ah, I get it. If it's coming from a remote node (i.e., `ep == NULL`), it can't be reply traffic anyway. I think the comment should clarify this as it's probably not going to be obvious to anyone who's not deeply familiar with the egress gateway.

File: test/k8sT/Egress.go (hunk 4 above)
Comment (pchaigno) [reply test/k8sT/Egress.go:196]: Thanks for the explanation! It makes sense to me.

AFAICS, that means the additional check in the datapath is only necessary for native routing mode today. I'm tempted to limit the check to native routing, but... :point_down: 

> if the target pod is running on the same node to which we connect to, once we get a reply from the pod we will jump to a different program before even looking up the egress gw policy: https://github.com/cilium/cilium/blob/master/bpf/bpf_lxc.c#L710-L714

This one relies on the assumption that we're using BPF to perform service resolution. If we ever enable the egress gateway to work with kube-proxy instead of KPR and we're relying on this assumption (e.g., we limited the check to only native routing mode), then the egress gateway may silently break. So probably best not to rely on that assumption.

Considering this, do you think it would be worth testing both pod-to-service in addition to direct pod-to-pod?

Comment (pchaigno) [reply test/k8sT/Egress.go:196]: (Whatever you decide, I think it would be worth a comment on the `ciliumOpts["tunnel"] == "disabled"` check to clarify the assumptions made here.)

Comment (jibi) [reply test/k8sT/Egress.go:196]: > Considering this, do you think it would be worth testing both pod-to-service in addition to direct pod-to-pod?

Yep, I guess it doesn't hurt to have an additional test for `external node -> nodeport service` since it can detect regressions on this front, so I'll add it back both for direct routing and tunneling :+1:

File: bpf/bpf_lxc.c [hunk 5]
```diff
@@ -803,6 +803,14 @@ static __always_inline int handle_ipv4_from_lxc(struct __ctx_buff *ctx,
 		if (!info)
 			goto skip_egress_gateway;
 
+		/* If the packet is a reply, it means that outside has initiated
```
Comment (brb) [inline bpf/bpf_lxc.c]: Nit: maybe mention in the comment that we exclude related packets as well.

File: bpf/lib/nodeport.h [hunk 6]
```diff
@@ -1144,7 +1145,28 @@ static __always_inline bool snat_v4_needed(struct __ctx_buff *ctx, __be32 *addr,
...
+			bool is_reply = false;
+			struct ipv4_ct_tuple tuple = {
+				.nexthdr = ip4->protocol,
+				.daddr = ip4->daddr,
+				.saddr = ip4->saddr
+			};
+
+			if (!ct_is_reply4(get_ct_map4(&tuple), ctx, ETH_HLEN + ipv4_hdrlen(ip4),
+					  &tuple, &is_reply) && is_reply)
+				ct_is_reply = true;
```
Comment (brb) [inline bpf/lib/nodeport.h]: Why can't we just `return false` here instead? This would eliminate the `if(!ct_is_reply)` below.

Comment (jibi) [reply bpf/lib/nodeport.h]: No strong reason here, I just thought avoiding this early return would make the code below a bit more explicit

**Comment by jibi** [comment]
(Just updated a comment ^, CI was green before beside a GKE flake)

**Review by kkourt — APPROVED** [review]
🚀

File: bpf/lib/nodeport.h (hunk 6 above)
Comment (brb) [reply bpf/lib/nodeport.h]: I think it's in opposite - the early return improves the code readability (no need to keep the context in head until the end of the function), and reduces the instr count.

File: bpf/bpf_lxc.c [hunk 7]
```diff
@@ -605,7 +605,7 @@ static __always_inline int handle_ipv4_from_lxc(struct __ctx_buff *ctx,
 	if (ret < 0)
 		return ret;
 
-	reason = ret;
+	ct_ret = ret;
```
Comment (brb) [inline bpf/bpf_lxc.c]: I feel nit-picky today, but why can't we use `ct_ret` directly a few lines above, i.e., `ct_ret = ct_lookup4(...)`?

**Review by brb — APPROVED** [review]
One non-blocking nit. Besides that :rocket: :moon:

File: bpf/bpf_lxc.c (hunk 7 above)
Comment (jibi) [reply bpf/bpf_lxc.c]: Yep, no reason for not doing that :+1:

File: bpf/bpf_lxc.c [hunk 8]
```diff
@@ -525,7 +525,7 @@ static __always_inline int handle_ipv4_from_lxc(struct __ctx_buff *ctx,
 	__u32 __maybe_unused tunnel_endpoint = 0;
 	__u8 __maybe_unused encrypt_key = 0;
 	__u32 monitor = 0;
-	__u8 reason;
+	__u8 ct_ret;
```
Comment (pchaigno) [inline bpf/bpf_lxc.c:528]: Should we also rename in other functions (IPv6, bpf_host, etc.) for consistency?

I'm also wondering if this change should be in its own PR to *not* backport it as it may cause a lot of conflicts.

**Review by pchaigno — APPROVED** [review]

File: bpf/bpf_lxc.c (hunk 8 above)
Comment (jibi) [reply bpf/bpf_lxc.c:528]: > Should we also rename in other functions (IPv6, bpf_host, etc.) for consistency?

Yes, I was thinking about doing it in a separate PR as it's a bit out of scope with the changes proposed here

> I'm also wondering if this change should be in its own PR to not backport it as it may cause a lot of conflicts.

I'll probably take care of backporting this PR anyway since there are conflicts also in the first commit, so I think it's fine

**Comment by jibi** [comment]
One last change: moved the

```
	if (ct_ret == CT_REPLY || ct_ret == CT_RELATED)
			goto skip_egress_gateway;
```

check in `bpf_lxc` before the policy lookup (to possibly avoid a non necessary map lookup)

**Comment by jibi** [comment]
/test-4.19
