### PR TITLE
KVStoreMesh: only sync identities ID

### LINKED ISSUE #36425: KVStoreMesh: only sync identities ID
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.15.11 and lower than v1.16.0

### What happened?

We run cilium with KVStoreMesh and KVstore identity mode and sync data from remote kubernetes clusters in etcd. We observed that when syncing data from a cluster with around 1k identities, there are about 2k keys synced from the `cilium/state/identities/v1` path in the source cluster. This is because both the identities `id` and `value` keys are getting synced (`cilium/state/identities/v1/id` and `cilium/state/identities/v1/value`). 

The `value` keys are used to track which node uses which identity which seems to only be used for garbage collection, which only happens on the source cluster, since synced clusters rely on a TTL based garbage collection. Hence syncing those `value` keys does not appear to be necessary.

We ran some tests with a patched version of the kvstoremesh API that only syncs `id` identity keys and got the following results:

Before applying the patch:

* Source cluster `cluster-a`:
```sh
root@cilium-agent-cluster-a:/home/cilium# cilium kvstore get --recursive cilium/state/identities/v1 2>/dev/null | wc -l
2789
root@cilium-agent-cluster-a:/home/cilium# cilium kvstore get --recursive cilium/state/identities/v1/id 2>/dev/null | wc -l
1097
root@cilium-agent-cluster-a:/home/cilium# cilium kvstore get --recursive cilium/state/identities/v1/value 2>/dev/null | wc -l
1694
```

* Target cluster `cluster-b`:
```sh
root@cilium-agent-cluster-b:/home/cilium# cilium kvstore get --recursive cilium/cache/identities/v1/cluster-a 2>/dev/null | wc -l
2788
root@cilium-agent-cluster-b:/home/cilium# cilium kvstore get --recursive cilium/cache/identities/v1/cluster-a/id 2>/dev/null | wc -l
1097
root@cilium-agent-cluster-b:/home/cilium# cilium kvstore get --recursive cilium/cache/identities/v1/cluster-a/value 2>/dev/null | wc -l
1690
```
After deploying the patch to only sync `id` identity keys:
* Source cluster `cluster-a`:
```sh
root@cilium-agent-cluster-a:/home/cilium# cilium kvstore get --recursive cilium/state/identities/v1 2>/dev/null | wc -l
2787
root@cilium-agent-cluster-a:/home/cilium# cilium kvstore get --recursive cilium/state/identities/v1/id 2>/dev/null | wc -l
1097
root@cilium-agent-cluster-a:/home/cilium# cilium kvstore get --recursive cilium/state/identities/v1/value 2>/dev/null | wc -l
1690
```
* Target cluster `cluster-b`:
```sh
root@cilium-agent-cluster-b:/home/cilium# cilium kvstore get --recursive cilium/cache/identities/v1/cluster-a 2>/dev/null | wc -l
1097
root@cilium-agent-cluster-b:/home/cilium# cilium kvstore get --recursive cilium/cache/identities/v1/cluster-a/id 2>/dev/null | wc -l
1097
root@cilium-agent-cluster-b:/home/cilium# cilium kvstore get --recursive cilium/cache/identities/v1/cluster-a/value 2>/dev/null | wc -l
0
```

The following graph shows the `cilium_kvstoremesh_kvstore_sync_queue_size` metric for the `identities/v1` scope with two spikes, the first one without the patch with a max queue size spike of about 2500, and the second one after applying the patch with a max queue size spike of about 800.

Image

This patch reduces the number of keys synced from a source cluster to a target cluster by about 50% which can add up to a significant number in large meshes with many clusters as all clusters sync their identities with every other cluster in the mesh. This leads to reduced load on the etcd and reduced sync queue size.

### How can we reproduce the issue?

See section above.

### Cilium Version

```
# cilium version
Client: 1.15.10 7aff1a4d87 2024-07-30T13:05:24+00:00 go version go1.22.8 linux/amd64
Daemon: 1.15.10 7aff1a4d87 2024-07-30T13:05:24+00:00 go version go1.22.8 linux/amd64
```

### Kernel Version

```
# uname -a
Linux 6.8.0-1019-aws #21~22.04.1-Ubuntu SMP Thu Nov  7 17:33:30 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
$ kubectl version
Client Version: v1.31.3
Kustomize Version: v5.4.2
Server Version: v1.31.2
```

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by HadrienPatte**
This PR implements the patch described in #36425

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

Fixes: #36425

```release-note
KVStoreMesh: Optimize cross-cluster state distribution by only synchronizing identities keyed by ID, not by value
```

### CODE REVIEW

File: pkg/clustermesh/kvstoremesh/remote_cluster.go [hunk 1]
```diff
@@ -314,8 +316,12 @@ func (o *syncer) OnSync(ctx context.Context) {
 
 func newReflector(local kvstore.BackendOperations, cluster, prefix string, factory store.Factory, synced *resources) reflector {
 	prefix = kvstore.StateToCachePrefix(prefix)
+	var syncStorePrefix = path.Join(prefix, cluster)
+	if strings.Contains(prefix, "identities") {
```
Comment (marseel) [inline pkg/clustermesh/kvstoremesh/remote_cluster.go]: Can we move this special handling outside of `newReflector`?
My proposal would be to have additional "suffix" paramter and just do here:
```
var syncStorePrefix = path.Join(prefix, cluster, suffix)
```

File: pkg/clustermesh/kvstoremesh/kvstoremesh_test.go [hunk 2]
```diff
@@ -262,10 +262,10 @@ func TestRemoteClusterRun(t *testing.T) {
 			}, timeout, tick, "Failed to retrieve the cluster config")
 
 			expectedReflected := map[string]string{
-				"cilium/cache/nodes/v1/foo/bar":      "qux1",
-				"cilium/cache/services/v1/foo/bar":   "qux2",
-				"cilium/cache/identities/v1/foo/bar": "qux4",
-				"cilium/cache/ip/v1/foo/bar":         "qux5",
+				"cilium/cache/nodes/v1/foo/bar":         "qux1",
+				"cilium/cache/services/v1/foo/bar":      "qux2",
+				"cilium/cache/identities/v1/foo/id/bar": "qux4",
```
Comment (marseel) [inline pkg/clustermesh/kvstoremesh/kvstoremesh_test.go:271]: Let's add additional case to verify that `cilium/cache/identities/v1/foo/value` is not propagated so we won't accidentally break it in the future :)

**Review by marseel — COMMENTED** [review]
Overall change makes sense, thanks for contribution!

I see @joestringer you edited release-notes. I am on the fence if this PR should have any release notes as it's related to https://github.com/cilium/cilium/pull/36216 and running KVStoreMesh with dedicated Etcd, which is not officially supported yet. This patch does not apply to "regular" Clustermesh deployments.

**Comment by joestringer** [comment]
Is it a big lift to apply this to the regular kvstoremesh case as well? Seems like that would be beneficial to reduce divergence between different modes.

File: pkg/clustermesh/kvstoremesh/remote_cluster.go (hunk 1 above)
Comment (HadrienPatte) [reply pkg/clustermesh/kvstoremesh/remote_cluster.go]: Updated in 28c0467e82452468dfb957defa9d27ab8b409369

File: pkg/clustermesh/kvstoremesh/kvstoremesh_test.go (hunk 2 above)
Comment (HadrienPatte) [reply pkg/clustermesh/kvstoremesh/kvstoremesh_test.go:271]: Updated in 28c0467e82452468dfb957defa9d27ab8b409369

**Comment by HadrienPatte** [comment]
> it's related to https://github.com/cilium/cilium/pull/36216 and running KVStoreMesh with dedicated Etcd, which is not officially supported yet. This patch does not apply to "regular" Clustermesh deployments.

As far as I understand it, this codepath should be used both when using a dedicated etcd or the sidecar one.

> Is it a big lift to apply this to the regular kvstoremesh case as well? Seems like that would be beneficial to reduce divergence between different modes.

Similarly, I think this patch should already cover regular kvstoremesh mode.

File: pkg/clustermesh/kvstoremesh/kvstoremesh_test.go [hunk 3]
```diff
@@ -279,6 +283,18 @@ func TestRemoteClusterRun(t *testing.T) {
...
+				"cilium/cache/identities/v1/foo/value/bar": "qux5",
+			}
+			// Assert that the keys have not been reflected
+			for key, value := range expectedNotReflected {
+				require.EventuallyWithTf(t, func(c *assert.CollectT) {
+					v, err := kvstore.Client().Get(ctx, key)
+					assert.NoError(c, err)
+					assert.NotEqual(c, value, string(v))
+				}, timeout, tick, "Key %q is not expected to be synced, got a match on value %q", key, value)
+			}
```
Comment (marseel) [inline pkg/clustermesh/kvstoremesh/kvstoremesh_test.go]: Let's switch this test to:
```
			// Assert that other keys have not been reflected
			values, err := kvstore.Client().ListPrefix(ctx, "cilium/cache/identities/v1/")
			require.Len(t, values, 1)
```
Checking if something doesn't exists with "eventually" probably doesn't make sense here. 
Instead, we can just check if anything else was not propagated in that specific prefix, including "value" keys.

**Review by marseel — APPROVED** [review]
> As far as I understand it, this codepath should be used both when using a dedicated etcd or the sidecar one.

For sidecar one, we synchronize from CiliumIdentities to identities in sidecard Etcd and clustermesh-apiserver is managing these. So there are no "/value" keys in sidecar Etcd at all as we don't need to keep track of which identities are used by which nodes, as that is already being handled through CiliumIdentity CRD itself. 

Anyway, codewise looks good, thanks for contribution :) 
Only one small nit with the test to make it a bit more robust.

File: pkg/clustermesh/kvstoremesh/kvstoremesh_test.go (hunk 3 above)
Comment (HadrienPatte) [reply pkg/clustermesh/kvstoremesh/kvstoremesh_test.go]: Thanks for the suggestion, updated in 53b6fc2a9d

**Comment by HadrienPatte** [comment]
@marseel Are we good to merge this now or do we need to wait for the 1.17 release? (also happy to rebase before merging if necessary), thanks

**Comment by marseel** [comment]
CI complains about long commit message:
```
Error: ERROR:CUSTOM: Please avoid long commit subjects (max: 75, found: 113)
```

Release branch for 1.17 was created, so no need to wait on 1.17 release :)

**Comment by HadrienPatte** [comment]
Ah sorry about that, I missed that CI warning, updated the commit message, should be all good now
