### PR TITLE
service/test: Fix waiting in testSessionAffinity and regroup affinity match map updates

### LINKED ISSUE #11296: CI: SessionAffinity tests take 8 minutes to run
## BPF Tests with direct routing Tests NodePort with sessionAffinity

Example from PR run:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/19395/execution/node/187/log/?consoleFull

This test takes over eight minutes to complete, which is significantly increasing CI run times:

```
13:17:52  K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with direct routing 
13:17:52    Tests NodePort with sessionAffinity
13:17:52    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:431
13:17:52  STEP: Making 10 HTTP requests from testclient-bqrw9 to "http://192.168.36.11:32016" (sessionAffinity)
13:22:06  STEP: Making 10 HTTP requests from k8s3 to "http://192.168.36.11:32016" (sessionAffinity)
13:26:05  === Test Finished at 2020-05-01T20:26:00Z====
13:26:05  <Checks>
13:26:05  Number of "context deadline exceeded" in logs: 0
13:26:05  Number of "level=error" in logs: 0
13:26:05  Number of "level=warning" in logs: 0
13:26:05  Number of "Cilium API handler panicked" in logs: 0
13:26:05  Number of "Goroutine took lock for more than" in logs: 0
13:26:05  No errors/warnings found in logs
13:26:05  
13:26:05  </Checks>
13:26:05  
13:26:05  
13:26:05  • [SLOW TEST:488.542 seconds]
13:26:05  K8sServicesTest
13:26:05  /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:396
13:26:05    Checks service across nodes
13:26:05    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:396
13:26:05      Tests NodePort BPF
13:26:05      /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:396
13:26:05        Tests with direct routing
13:26:05        /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:396
13:26:05          Tests NodePort with sessionAffinity
13:26:05          /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:431
```

The run is successful, but should not take this long.

### PR DESCRIPTION
**Pull request by brb**
See commit msgs.

Fix #11296
Partially_fix #11442

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

File: test/k8sT/Services.go [hunk 1]
```diff
@@ -832,14 +832,16 @@ var _ = Describe("K8sServicesTest", func() {
...
-			// Wait until the pod has been removed from the cilium endpoints list.
-			// Otherwise, the requests below might fail as the non-existing endpoint
-			// will be chosen.
-			kubectl.WaitForCiliumEndpointDeleted(nodes[dstPod], helpers.DefaultNamespace, dstPod)
+
+			// Wait until the replacement pod has been provisioned + 1 second. This
+			// should give enough time for cilium-agents to remove the deleted pod
+			// from the BPF LB maps, so that the next request won't choose the deleted pod.
+			waitPodsDs()
+			time.Sleep(1 * time.Second)
```
Comment (joestringer) [inline test/k8sT/Services.go]: Do you think that waiting 1 second is reliable?

I've often seen `kubectl delete` commands hang for some time, more than one second. I don't have a direct comparison with this as I didn't dig into what `waitPodsDs()` does here though.

**Comment by brb** [comment]
test-focus K8sService*

**Comment by brb** [comment]
test-focus .*sessionAffinity.*

**Comment by brb** [comment]
test-focus K8sService*

File: test/k8sT/Services.go (hunk 1 above)
Comment (brb) [reply test/k8sT/Services.go]: Apparently not. Did more troubleshooting and found out that ipcache entry is missing for the new backend after the removal which resulted in the request being dropped.

**Comment by brb** [comment]
test-focus K8sService*

**Comment by brb** [comment]
test-me-please

**Review by qmonnet — COMMENTED** [review]
[Ignore this comment - I forgot to add inline comment before submitting the review, sorry for the noise]

File: test/k8sT/Services.go [hunk 2]
```diff
@@ -830,14 +830,28 @@ var _ = Describe("K8sServicesTest", func() {
...
+			//
+			// The second wait is needed to make sure that an IPCache entry of the
+			// new pod appears on the k8s1 node. Otherwise, if the new pod runs
+			// on k8s2 and a request below selects it, the request will be dropped
+			// in the vxlan mode (the tailcall IPV4_NODEPORT_NAT body won't pass
+			// the request to the encap routines, and instead it will be dropped
+			// due to failing fib_lookup).
+			waitPodsDs()
+			if fromOutside && vxlan {
+				time.Sleep(5 * time.Second)
```
Comment (qmonnet) [inline test/k8sT/Services.go]: Would it make sense to create a new helper to wait for the specific ipcache entry, so that we are sure that it has been added before going on? Maybe overkill, I'm not strongly opposed to the 5s wait.

**Review by qmonnet — COMMENTED** [review]
Looks good, and nice catch! One question.

File: test/k8sT/Services.go (hunk 2 above)
Comment (brb) [reply test/k8sT/Services.go]: It's a bit an overkill, but on the other hand we are risking to introduce flakes with sleep. Going to add it in this PR.

**Comment by brb** [comment]
test-focus K8sService*

**Review by qmonnet — APPROVED** [review]
Thanks for the change, looks all good to me now.
