### PR TITLE
watchers: Support hostPort for init containers

### LINKED ISSUE #16191: HostPort doesn't work for initContainers
Trough code auditing it's obvious that we don't handle initContainer hostports:

https://github.com/cilium/cilium/blob/465cac1b740bdd370326607cdcedef1059df9e12/pkg/k8s/watchers/pod.go#L473-L475

cc @borkmann

### PR DESCRIPTION
**Pull request by pchaigno**
The K8s watcher for HostPort services was only watching for containers and not init containers. This commit fixes it such that HostPorts assigned to init containers generate the proper service mapping in the datapath.

Fixes: https://github.com/cilium/cilium/issues/16191.

```release-note
Fix support of BPF-based HostPort on init containers.
```

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Comment by pchaigno** [comment]
In gke-stable, two tests failed with known flake https://github.com/cilium/cilium/issues/17307. They were testing session affinity and not hostport so not affected by this change. The team review request is covered by André's review. Marking ready to merge.

File: pkg/k8s/watchers/pod.go [hunk 1]
```diff
@@ -461,7 +461,8 @@ func (k *K8sWatcher) deleteK8sPodV1(pod *slim_corev1.Pod) error {
 
 func (k *K8sWatcher) genServiceMappings(pod *slim_corev1.Pod, podIPs []string, logger *logrus.Entry) []loadbalancer.SVC {
 	var svcs []loadbalancer.SVC
-	for _, c := range pod.Spec.Containers {
+	containers := append(pod.Spec.InitContainers, pod.Spec.Containers...)
+	for _, c := range containers {
```
Comment (aanm) [inline pkg/k8s/watchers/pod.go]: Actually let's do it like this, just to be safe:
```golang
nContainers := len(pod.Spec.InitContainers) + len(pod.Spec.Containers)
var c slim_corev1.Container
for i := 0; i < nContainers; i++ {
   if i<len(pod.Spec.InitContainers){
     c = pod.Spec.InitContainers[i]
   }else{
    c =pod.Spec.Containers[i-len(pod.Spec.InitContainers)]
   }
....
```

**Review by aanm — CHANGES_REQUESTED** [review]

File: pkg/k8s/watchers/pod.go (hunk 1 above)
Comment (pchaigno) [reply pkg/k8s/watchers/pod.go]: Why? My newbie Golang :eyes: see only more convoluted code :smile_cat:

Comment (aanm) [reply pkg/k8s/watchers/pod.go]: https://go.dev/play/p/_C5VYvaJ0i1

**Review by borkmann — APPROVED** [review]
Nice, thanks a lot for looking at this! Ack (modulo @aanm's suggestion and mentioned readiness probe doc update).

File: pkg/k8s/watchers/pod.go (hunk 1 above)
Comment (pchaigno) [reply pkg/k8s/watchers/pod.go]: :exploding_head: 

What about the following?
```go
var containers []Container
containers = append(containers, pod.Spec.InitContainers...)
containers = append(containers, pod.Spec.Containers...)
for _, c := range containers {
```
Seems easier to parse.

Comment (aanm) [reply pkg/k8s/watchers/pod.go]: yep, that also works although we are kind of unnecessarily allocating memory

**Comment by pchaigno** [comment]
> Ack (modulo @aanm's suggestion and mentioned readiness probe doc update).

I don't think a readiness probe doc update is needed since existing readiness probes should still work the same. AFAIU, the readiness probes would need to be updated if we changed the HostPort provisioning to only happen once the pod is in Ready status.

**Review by aanm — APPROVED** [review]
