### PR TITLE
kvstore: add tests for etcd ratelimiter implementation

### LINKED ISSUE #11916: Verify correctness of KVStore rate limiter
It seems in some occasions the KVStore rate limiter was not working, verify its behavior with a unit test against etcd should be enough.

https://github.com/cilium/cilium/blob/3430980860e68dbb92d7f0faa79a49d09b6e6786/pkg/kvstore/etcd.go#L160-L166

### PR DESCRIPTION
**Pull request by fristonio**
Increase unit tests coverage for `pkg/kvstore`.
This Pull Request adds tests to cover rate limiter functionality for etcd kvstore backend.
Fixes #11916

### CODE REVIEW

File: pkg/kvstore/dummy.go [hunk 1]
```diff
@@ -18,14 +18,28 @@ import "context"
...
+		err := module.setConfig(opts)
+		if err != nil {
+			log.WithError(err).Panic("Unable to set config options for kvstore backend module")
+		}
+	}
+
 	if err := initClient(context.TODO(), module, nil); err != nil {
 		log.WithError(err).Panic("Unable to initialize kvstore client")
 	}
+
```
Comment (tklauser) [inline pkg/kvstore/dummy.go]: Nit: unnecessary newline added

File: pkg/kvstore/etcd_test.go [hunk 2]
```diff
@@ -1664,3 +1665,183 @@ func TestShuffleEndpoints(t *testing.T) {
...
+		key := e.getKey(prefix, i)
+
+		_, err := e.etcdClient.Delete(context.Background(), key)
+		c.Assert(err, IsNil)
+	}
+}
+
+func (e *EtcdRateLimiterSuite) TestRateLimiterGetOps(c *C) {
+	randomPath := c.MkDir()
+	txnCount := 15
```
Comment (aanm) [inline pkg/kvstore/etcd_test.go]: We don't need to make it 15, it can be `e.maxQPS+2`. That should return the same results as well.

**Review by aanm — CHANGES_REQUESTED** [review]
Just a small note, everything else looks great!

File: pkg/kvstore/etcd_test.go [hunk 3]
```diff
@@ -1664,3 +1665,183 @@ func TestShuffleEndpoints(t *testing.T) {
...
+		wg := sync.WaitGroup{}
+		for i := 0; i < txnCount; i++ {
+			wg.Add(1)
+			go func(wg *sync.WaitGroup, i int) {
+				defer wg.Done()
+				op.fn(c, key, i, kvlocker)
+			}(&wg, i)
+		}
+		wg.Wait()
+		c.Assert(time.Now().Sub(start) < minTime, Equals, true)
```
Comment (tklauser) [inline pkg/kvstore/etcd_test.go]:
```suggestion
		c.Assert(time.Since(start) < minTime, Equals, true)
```

File: pkg/kvstore/etcd_test.go [hunk 4]
```diff
@@ -1664,3 +1665,183 @@ func TestShuffleEndpoints(t *testing.T) {
...
+		wg = sync.WaitGroup{}
+		for i := 0; i < txnCount; i++ {
+			wg.Add(1)
+			go func(wg *sync.WaitGroup, i int) {
+				defer wg.Done()
+				op.fn(c, key, i, kvlocker)
+			}(&wg, i)
+		}
+		wg.Wait()
+		c.Assert(time.Now().Sub(start) > minTime, Equals, true)
```
Comment (tklauser) [inline pkg/kvstore/etcd_test.go]:
```suggestion
		c.Assert(time.Since(start) > minTime, Equals, true)
```

**Review by tklauser — COMMENTED** [review]
LGTM apart from a few small nits

File: pkg/kvstore/etcd_test.go (hunk 2 above)
Comment (fristonio) [reply pkg/kvstore/etcd_test.go]: We will at least need this to be `e.maxQPS * 2 + 2`.
If we use e.maxQPS + 2 the operation can be performed in less than a second because the rate limiter comes with a granularity of a second and the tokens in the rate limiter are regenerated every second.

**Comment by fristonio** [comment]
test-me-please

**Review by tklauser — APPROVED** [review]
🚀

**Comment by fristonio** [comment]
Hitting #13071 for net-next run.

**Review by aanm — APPROVED** [review]
