### PR TITLE
Fix IPAM IP release racing condition when IP reassigned back to ENI

### LINKED ISSUE #39981: AWS ENI IP addresses can get stuck released status, preventing allocation to pods
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.4 and lower than v1.18.0

### What happened?

We've identified a bug in Cilium's IPAM with AWS ENI where an IP address that was marked for release and then reassigned back to the ENI can become stuck in a state where it's both in CiliumNode's `spec.ipam.pool` and in `status.ipam.release-IPs` with status "released". This prevents the IP from being assigned to new pods, leading to pods stuck in ContainerCreating state with "No more IPs available" errors. 

#### Environment
Cilium version: `1.17.2`
Kubernetes: EKS `1.31`
IPAM mode: AWS ENI

Here is what I believe where the issue occurs, in the IP release handshake process when the following sequence happens:
1. An IP is marked for release and goes through the handshake process to "released" state
2. The IP is removed from `spec.ipam.pool` as part of the release process
3. Before the agent can complete the handshake by removing the IP from `status.ipam.ReleaseIPs`, the same IP is reassigned to the ENI (e.g., due to PreAllocate or new pods needing IP addresses)
4. The IP is added back to `spec.ipam.pool`
5. When the agent tries to clean up, its logic checks https://github.com/cilium/cilium/blob/79e9a78f01111baf7221cf337aa955a1fd1159bd/pkg/ipam/crd.go#L450-L454
Since the IP is now in the pool, the agent doesn't remove it from status.ipam.ReleaseIPs
6. The IP remains in both `spec.ipam.pool` AND `status.ipam.ReleaseIPs` with status "released"
7. When checking for available IPs, [`isIPInReleaseHandshake()`](https://github.com/cilium/cilium/blob/79e9a78f01111baf7221cf337aa955a1fd1159bd/pkg/ipam/crd.go#L611-L622) returns true for this IP, making it unavailable for allocation

Restarting the Cilium operator temporarily resolves the issue as it resets the internal tracking state.

### How can we reproduce the issue?

Because this issue requires tricky timing, it's not very easy to reproduce. But we've seen it a few times in a few high churning clusters. 

### Cilium Version

`1.17.2`

### Kernel Version

`6.8.0-1029-aws #31~22.04.1-Ubuntu`

### Kubernetes Version

`1.31`

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by victorcq**
This fixes the racing condition during IPAM IP release process:
where an IP address that was marked for release and then reassigned back to the ENI can become stuck in a state where it's both in CiliumNode's `spec.ipam.pool` and in `status.ipam.release-IPs` with status "released". This prevents the IP from being assigned to new pods, leading to pods stuck in ContainerCreating state with "No more IPs available" errors.

Fixes: #39981

### CODE REVIEW

**Comment by victorcq** [comment]
There were failed integration tests, but I'm not sure if they are really related to my change. Just rebased from main branch.

**Comment by joestringer** [comment]
Fair enough, thanks for contributing. If it happens again could you also link to the build and highlight the failure symptom(s)? This can help others to review the output of those tests and either correlate with other issues others are facing or help to identify that the build is unrelated. You can also search the symptom in the "Issues" tab to see if someone else experiences the same problem. 

As I see that you updated the PR several times, I'll also note that we do not require all PRs to be up-to-date with `main` before merging. It's not viable to rebase all the PRs with the rate of contribution we receive. Generally it's good for the PR to be up-to-date within the last week or so. Rebasing more frequently requires intervention to trigger the tests, while rebasing less frequently might start to create conflicts with the `main` branch.

I'll retrigger the tests.

**Comment by victorcq** [comment]
Thanks @joestringer ! Looks like all checks passed.

File: pkg/ipam/node_manager_test.go [hunk 1]
```diff
@@ -589,6 +590,121 @@ func TestNodeManagerAbortRelease(t *testing.T) {
...
+	require.Equal(t, 4, node.Stats().IPv4.AvailableIPs)
+	require.Equal(t, 2, node.Stats().IPv4.UsedIPs)
+
+	node.instanceSync.Trigger()
+
+	// This is the key IP that will be released and later reassigned
+	var releasedIP string
+	wg.Add(1)
+
+	time.AfterFunc(3*time.Second, func() {
```
Comment (pippolo84) [inline pkg/ipam/node_manager_test.go]: I guess we are waiting 3 seconds here to be sure that the `instanceSync` is run. I suggest to rely on `assert.Eventually` or `assert.EventuallyWithT` and use an explicit condition instead, to avoid flakiness when running the test in the (unpredictable) CI environment.

Same for all the other `time.Sleep` occurrences later.

**Review by pippolo84 — CHANGES_REQUESTED** [review]
Thanks for the fix!

The fix makes sense to me, but I'd left a feedback inline about the usage of `time` functions in the test.

File: pkg/ipam/node_manager_test.go (hunk 1 above)
Comment (victorcq) [reply pkg/ipam/node_manager_test.go]: Hi @pippolo84 I'm new to the codebase, so I was purely following the same style from existing test cases to make sure I do not introduce something new, like https://github.com/cilium/cilium/blob/main/pkg/ipam/node_manager_test.go#L519 and https://github.com/cilium/cilium/blob/main/pkg/ipam/node_manager_test.go#L602, where they used `time.AfterFunc` and `time.Sleep`. 

If `Eventually` is expected here, I can certainly do that.

Comment (joestringer) [reply pkg/ipam/node_manager_test.go]: Using `time.Sleep` in tests is a poor pattern, those existing usages should also be fixed up at some point. In this case it would be better to follow best practices than to follow the existing examples in the tree.

Comment (victorcq) [reply pkg/ipam/node_manager_test.go]: Cool, all good. I've updated my test to use `require.Eventually`

File: pkg/ipam/node_manager_test.go [hunk 2]
```diff
@@ -589,6 +590,141 @@ func TestNodeManagerAbortRelease(t *testing.T) {
...
+	require.Equal(t, 4, node.Stats().IPv4.AvailableIPs)
+	require.Equal(t, 2, node.Stats().IPv4.UsedIPs)
+
+	node.instanceSync.Trigger()
+
+	// This is the key IP that will be released and later reassigned
+	var releasedIP string
+	wg.Add(1)
+
+	go func() {
```
Comment (pippolo84) [inline pkg/ipam/node_manager_test.go]: There's no need to spawn a separate goroutine (note that the main one is just blocked waiting for this one to finish, hinting that there's no real concurrent work to be done). Eventually spawns its own goroutine to periodically test the condition.

File: pkg/ipam/node_manager_test.go [hunk 3]
```diff
@@ -589,6 +590,141 @@ func TestNodeManagerAbortRelease(t *testing.T) {
...
+			}
+
+			for _, ts := range node.ipv4Alloc.ipsMarkedForRelease {
+				if ts.Add(time.Duration(operatorOption.Config.ExcessIPReleaseDelay) * time.Second).Before(time.Now()) {
+					return true
+				}
+			}
+
+			return false
+		}, 5*time.Second, time.Second)
```
Comment (pippolo84) [inline pkg/ipam/node_manager_test.go]: I suggest to use a larger timeout, at least 10 seconds. This prevents flakes in the CI where the condition might be tested fewer times than expected due to the unpredictable latency introduced in such environments. Note that this should not slow down the test in more stable environments (that is, in a local environment), since the test goes ahead as soon as the condition is true for the first time.

File: pkg/ipam/node_manager_test.go [hunk 4]
```diff
@@ -589,6 +590,141 @@ func TestNodeManagerAbortRelease(t *testing.T) {
...
+
+	// This is the key IP that will be released and later reassigned
+	var releasedIP string
+	wg.Add(1)
+
+	go func() {
+		defer wg.Done()
+		// Wait for the IP to be marked as excess for longer than the ExcessIPReleaseDelay
+		require.Eventually(t, func() bool {
+			if len(node.ipv4Alloc.ipsMarkedForRelease) == 0 {
```
Comment (pippolo84) [inline pkg/ipam/node_manager_test.go]: There's a race here between the test goroutine accessing `ipsMarkedForRelease` and the trigger goroutine run by the NodeManager (you can see that running the test with the race detector). It can be solved taking a read lock on the node at the start of the condition:

```go
	require.Eventually(t, func() bool {
		node.mutex.RLock()
		defer node.mutex.RUnlock()

		if len(node.ipv4Alloc.ipsMarkedForRelease) == 0 {
```

File: pkg/ipam/node_manager_test.go [hunk 5]
```diff
@@ -589,6 +590,141 @@ func TestNodeManagerAbortRelease(t *testing.T) {
...
+		// Resync one more time to process acknowledgements.
+		node.instanceSync.Trigger()
+
+		require.Eventually(t, func() bool {
+			status, exists := node.resource.Status.IPAM.ReleaseIPs[releasedIP]
+			return exists && string(status) == ipamOption.IPAMReadyForRelease
+		}, 5*time.Second, time.Second)
+
+		// Now simulate the operator releasing the IP and marking it as released
+		delete(node.resource.Spec.IPAM.Pool, releasedIP)
```
Comment (pippolo84) [inline pkg/ipam/node_manager_test.go]: Similar race here between the test and the NodeManager. Can be solved by taking the lock on the node:

```go
		node.mutex.Lock()
		delete(node.resource.Spec.IPAM.Pool, releasedIP)
		node.resource.Status.IPAM.ReleaseIPs[releasedIP] = ipamOption.IPAMReleased
		node.mutex.Unlock()
```

**Review by pippolo84 — CHANGES_REQUESTED** [review]
Thanks for the second iteration!

Some final advice about the test and I think we can merge this! :100:

File: pkg/ipam/node_manager_test.go (hunk 2 above)
Comment (victorcq) [reply pkg/ipam/node_manager_test.go]: Thanks @pippolo84 makes sense, I've made changes as suggested, also checked using `-race` 👍

File: pkg/ipam/node_manager_test.go (hunk 3 above)
Comment (victorcq) [reply pkg/ipam/node_manager_test.go]: Updated as suggested

File: pkg/ipam/node_manager_test.go (hunk 5 above)
Comment (victorcq) [reply pkg/ipam/node_manager_test.go]: Updated as suggested

File: pkg/ipam/node_manager_test.go (hunk 4 above)
Comment (victorcq) [reply pkg/ipam/node_manager_test.go]: Updated as suggested.

**Comment by pippolo84** [comment]
@victorcq changes LGTM, nice! Could you please squash the three commits into a single one? Thanks in advance! :pray:

**Comment by victorcq** [comment]
> @victorcq changes LGTM, nice! Could you please squash the three commits into a single one? Thanks in advance! 🙏

👍 Done. Btw, I see this PR is tagged as `needs-backport` and we do need it in `1.17`, do I need to do anything to make this happen?

**Review by pippolo84 — APPROVED** [review]
Thanks! :white_check_mark:

**Comment by pippolo84** [comment]
> 👍 Done. Btw, I see this PR is tagged as `needs-backport` and we do need it in `1.17`, do I need to do anything to make this happen?

No need to do the backporting yourself, a backporter will take care of doing that (see https://docs.cilium.io/en/stable/contributing/development/reviewers_committers/duties/#backporters).

**Comment by victorcq** [comment]
@pippolo84 can you help to trigger those failed checks again? They don't really relate to my change. 🤞

**Comment by aanm** [comment]
@victorcq This change is making the PR https://github.com/cilium/cilium/pull/41434 to fail. Do you mind taking a look?

**Comment by aanm** [comment]
> @victorcq This change is making the PR #41434 to fail. Do you mind taking a look?

I've pushed a fix into #41434
