### PR TITLE
Sanitize endpoint security identity upon restore

### LINKED ISSUE #7358: CI: Tests upgrade and downgrade from a Cilium stable image to master (Expect a 403 from app1-service)
## k8s-1.8.K8sUpdates Tests upgrade and downgrade from a Cilium stable image to master

Etcd appears unhealthy during upgrade which causes traffic to pass when it should be denied.

### Stacktrace
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:409
Expect a 403 from app1-service
Expected command: kubectl exec -n default app2-cd69fd9f6-nlgs2 -- curl -s -D /dev/stderr --fail --connect-timeout 5 --max-time 8 http://app1-service/private -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'"
To have failed, but it was successful:
Exitcode: 0 
Stdout:
 	 { 'val': 'this is private' }
	 time-> DNS: '0.004221(10.97.31.250)', Connect: '0.004305',Transfer '0.004970', total '0.004992'
Stderr:
 	 HTTP/1.1 200 OK
	 Date: Fri, 08 Mar 2019 11:42:49 GMT
	 Server: Apache/2.4.25 (Unix)
	 Last-Modified: Mon, 27 Mar 2017 15:58:16 GMT
	 ETag: "1d-54bb86948d600"
	 Accept-Ranges: bytes
	 Content-Length: 29


/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Updates.go:272
```

```
Standard Error
STEP: Installing a cleaning state of Cilium
STEP: Installing kube-dns
STEP: Deploying etcd-operator
STEP: Cilium "v1.4" is installed and running
STEP: Performing Cilium preflight check
Cilium is not ready yet: status is unhealthy: cilium-agent 'cilium-vrg4b' is unhealthy: Exitcode: 1 
Stdout:
 	 KVStore:                Failure   Err: Not able to connect to any etcd endpoints
	 ContainerRuntime:       Ok        docker daemon: OK
	 Kubernetes:             Ok        1.8 (v1.8.14) [linux/amd64]
	 Kubernetes APIs:        ["CustomResourceDefinition", "cilium/v2::CiliumNetworkPolicy", "core/v1::Endpoint", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
	 Cilium:                 Failure   Kvstore service is not ready
	 NodeMonitor:            Disabled
	 Cilium health daemon:   Warning   Get http:///var/run/cilium/health.sock/v1beta/hello: dial unix /var/run/cilium/health.sock: connect: no such file or directory
	 IPv4 address pool:      5/255 allocated from 10.10.1.0/24
	 IPv6 address pool:      4/65535 allocated from f00d::a0a:100:0:0/112
	 Controller Status:      25/25 healthy
	 Proxy Status:           OK, ip 10.10.1.1, port-range 10000-20000
	 
Stderr:
 	 command terminated with exit code 1
```

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/10628/testReport/junit/k8s-1/8/K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master/

[843076e7_K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master.zip](https://github.com/cilium/cilium/files/2947378/843076e7_K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master.zip)

### PR DESCRIPTION
**Pull request by joestringer**
Supersedes #7672.

Previously, we would deserialize endpoints from json, then add these
partially unvalidated objects into the endpointmanager, exposing them to
other subsystems, then only after some time change the identity of the
endpoint and ensure that the security identity is correct.

As a result, the `pkg/endpoint` code could not rely upon the
`e.SecurityIdentity` being fully initialized (specifically, with the
`LabelArray` of the security identity being non-nil). This leads to
calculation of `L4Policy` using security labels `[]`.

This PR ensures that during restore, the endpoint's SecurityIdentity is
properly restored by sanitizing the `e.SecurityIdentity` to ensure that its
corresponding `LabelArray` is populated with labels that reflect the identity.

Additionally, this PR prevents identity updates triggering regeneration for
 endpoints that are currently being restored or waiting to regenerate. This
should avoid the entire situation in future where endpoints that are exposed
via the endpointmanager (to provide visibility to users) are regenerated prior
to the restore logic completely finishing.

A side effect of the change to how regeneration is triggered is that if the
identity of an endpoint is changed during Cilium startup, that endpoint will
now appear as `Restoring` for about 20 seconds during Cilium startup. I
believe that this is a more accurate reflection of how Cilium is handling this
endpoint for that period, so this is an improvement above the current setup
where the endpoint is represented as `ready`, even though the newly
launched Cilium hasn't yet regenerated that endpoint, so it is only applying
whatever policy was determined during a previous Cilium run.

```release-note
Fix issue where if there are many identities changing during Cilium restart, some endpoints may enforce policy only using policy that selects all labels, rather than the policy that selects that endpoint's labels.
```

Fixes: #7358

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7682)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

File: pkg/endpoint/endpoint.go [hunk 1]
```diff
@@ -1065,6 +1065,7 @@ func ParseEndpoint(strEp string) (*Endpoint, error) {
 	}
 
 	ep.UpdateLogger(nil)
+	ep.SecurityIdentity.Sanitize()
```
Comment (ianvernon) [inline pkg/endpoint/endpoint.go]: Any possibility that the endpoint's identity is nil here?

Comment (joestringer) [reply pkg/endpoint/endpoint.go]: probably, we're reading stuff off the filesystem.

Comment (joestringer) [reply pkg/endpoint/endpoint.go]: I think in the common case there's a value here. If someone goes and messes with the FS state, they could snip this out, and I presume that would lead `parseBase64ToEndpoint()` to set the `SecurityIdentity` to nil. So then what do we do? Set it with the `reserved:init` identity?

Comment (tgraf) [reply pkg/endpoint/endpoint.go]: Yes

**Comment by joestringer** [comment]
Green build. If the only outstanding feedback is defaulting to init identity when it's not provided in the serialized object, then I'll just roll that in and re-push.

File: daemon/state.go [hunk 2]
```diff
@@ -281,7 +281,7 @@ func (d *Daemon) regenerateRestoredEndpoints(state *endpointRestoreState) (resto
 				return
 			}
 
-			ep.LogStatusOKLocked(endpoint.Other, "Synchronizing endpoint labels with KVStore")
+			ep.SetStateLocked(endpoint.StateRestoring, "Synchronizing endpoint labels with KVStore")
```
Comment (joestringer) [inline daemon/state.go:284]: I thought about setting this as `endpoint.StateWaitingForIdentity()`, but that would require thinking through a few more state machine transitions so this seemed like a safer alternative.

**Review by tgraf — APPROVED** [review]

File: pkg/endpoint/endpoint.go (hunk 1 above)
Comment (joestringer) [reply pkg/endpoint/endpoint.go]: Resolved in the latest version by setting identity to `reserved:init`.

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]
