### PR TITLE
datapath: link-local unicast addresses can be "host"

### LINKED ISSUE #16308: Cilium non-deterministically classifies CIDR policy matches for range with node IPs
## Bug report

**General Information**

- Cilium version: cilium 1.9.4
- Kernel version: Linux ip-10-29-109-25 5.4.0-1045-aws #47-Ubuntu SMP Tue Apr 13 07:02:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use: kubernetes v1.20.6

**How to reproduce the issue**

Run `node-local-dns --setupiptables=false` and `kubelet --cluster-dns=169.254.20.10`

Add a CNP that looks like this:
```
spec:
  egress:
  - toCIDR:
    - 169.254.20.10/32
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
  endpointSelector: {}
```

On first cilium run, cilium will deny traffic to node-local-dns. If the pod is deleted, the second cilium run will accept traffic.

*First cilium run*

`cilium ip list`:
```
169.254.20.10/32    host
```

`cilium monitor -t policy-verdict`:
```
Policy verdict log: flow 0xaaa04ad local EP ID 1762, remote ID 1, proto 17, egress, action deny, match none, 100.71.181.66:53076 -> 169.254.20.10:53 udp
Policy verdict log: flow 0xaaa04ad local EP ID 1762, remote ID 1, proto 17, egress, action deny, match none, 100.71.181.66:53076 -> 169.254.20.10:53 udp
Policy verdict log: flow 0x0 local EP ID 481, remote ID 17956, proto 6, ingress, action deny, match none, 100.71.139.54:45062 -> 100.71.181.177:6943 tcp SYN
Policy verdict log: flow 0xaaa04ad local EP ID 1762, remote ID 1, proto 17, egress, action deny, match none, 100.71.181.66:53076 -> 169.254.20.10:53 udp
Policy verdict log: flow 0xaaa04ad local EP ID 1762, remote ID 1, proto 17, egress, action deny, match none, 100.71.181.66:53076 -> 169.254.20.10:53 udp
Policy verdict log: flow 0x897b78c4 local EP ID 1762, remote ID 1, proto 17, egress, action deny, match none, 100.71.181.66:56843 -> 169.254.20.10:53 udp
Policy verdict log: flow 0x897b78c4 local EP ID 1762, remote ID 1, proto 17, egress, action deny, match none, 100.71.181.66:56843 -> 169.254.20.10:53 udp
```

*Second cilium run*

```
169.254.20.10/32     cidr:169.254.0.0/16                                                                                       
                     cidr:169.254.0.0/19                                                                                       
                     cidr:169.254.20.10/31                                                                                     
                     cidr:168.0.0.0/5                                                                                          
                     cidr:168.0.0.0/7                                                                                          
                     cidr:169.254.0.0/17                                                                                       
                     cidr:169.254.20.0/23                                                                                      
                     reserved:world                                                                                            
                     cidr:169.254.20.0/22                                                                                      
                     cidr:169.254.20.10/32                                                                                     
                     cidr:169.254.20.0/25                                                                                      
                     cidr:169.254.20.0/27                                                                                      
                     cidr:169.0.0.0/8                                                                                          
                     cidr:169.128.0.0/9                                                                                        
                     cidr:169.254.0.0/15                                                                                       
                     cidr:169.224.0.0/11                                                                                       
                     cidr:168.0.0.0/6                                                                                          
                     cidr:169.254.20.0/26                                                                                      
                     cidr:160.0.0.0/3                                                                                          
                     cidr:169.254.16.0/20                                                                                      
                     cidr:0.0.0.0/0                                                                                            
                     cidr:169.254.16.0/21                                                                                      
                     cidr:128.0.0.0/2                                                                                          
                     cidr:169.248.0.0/13                                                                                       
                     cidr:169.192.0.0/10                                                                                       
                     cidr:169.254.20.8/30                                                                                      
                     cidr:169.254.0.0/18                                                                                       
                     cidr:160.0.0.0/4                                                                                          
                     cidr:169.254.20.0/28                                                                                      
                     cidr:169.254.20.8/29                                                                                      
                     cidr:169.240.0.0/12                                                                                       
                     cidr:169.252.0.0/14                                                                                       
                     cidr:169.254.20.0/24                                                                                      
                     cidr:128.0.0.0/1  
```

`cilium monitor -t policy-verdict`:
```
Policy verdict log: flow 0x5f42acab local EP ID 1109, remote ID 16777221, proto 17, egress, action allow, match L3-L4, 100.71.139.123:38685 -> 169.254.20.10:53 udp
Policy verdict log: flow 0xbe339248 local EP ID 1109, remote ID 16777221, proto 17, egress, action allow, match L3-L4, 100.71.139.123:54033 -> 169.254.20.10:53 udp
Policy verdict log: flow 0x3a516849 local EP ID 1109, remote ID 16777221, proto 17, egress, action allow, match L3-L4, 100.71.139.123:40686 -> 169.254.20.10:53 udp
Policy verdict log: flow 0x656356b6 local EP ID 1109, remote ID 16777221, proto 17, egress, action allow, match L3-L4, 100.71.139.123:41152 -> 169.254.20.10:53 udp
Policy verdict log: flow 0x978580ec local EP ID 1109, remote ID 16777221, proto 17, egress, action allow, match L3-L4, 100.71.139.123:53109 -> 169.254.20.10:53 udp
Policy verdict log: flow 0x45c1e6c1 local EP ID 1109, remote ID 16777221, proto 17, egress, action allow, match L3-L4, 100.71.139.123:50593 -> 169.254.20.10:53 udp
Policy verdict log: flow 0x9cd850d5 local EP ID 1109, remote ID 16777221, proto 17, egress, action allow, match L3-L4, 100.71.139.123:37507 -> 169.254.20.10:53 udp
```

Slack thread https://cilium.slack.com/archives/C1MATJ5U5/p1621963201289500

### LINKED ISSUE #20055: `cilium connectivity test` fails when nodelocaldns is running in cluster
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi,

In our environment, `pod-to-a-allowed-cnp` and `pod-to-external-fqdn-allow-google-cnp` tests are failing when cilium runs with nodelocaldns. We used [these](https://github.com/cilium/cilium/blob/master/examples/kubernetes/connectivity-check/connectivity-check.yaml) resources to find out what pods are failing. Also, some tests are failing for some reason in `cilium connectivity test` command.

So, we have noticed that packages are being dropped because of the policies. Here is one example output from Hubble UI

```
Flow Details
Timestamp
2022-06-02T12:06:10.175Z
Verdict
dropped
Drop reason
Policy denied
Traffic direction
egress
Source pod
pod-to-a-allowed-cnp-bbc844c6f-2zrdf
Source identity
45495
Source labels
io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=test-alani
io.cilium.k8s.policy.cluster=default
io.cilium.k8s.policy.serviceaccount=default
namespace=test-alani
name=pod-to-a-allowed-cnp
Source IP
some-ip
Destination identity
2
Destination labels
reserved:world
Destination IP
169.254.25.10
Destination port
53
```

nodelocadns settings:

```yaml
  Containers:
   node-cache:
    Image:       k8s.gcr.io/dns/k8s-dns-node-cache:1.21.1
    Ports:       53/UDP, 53/TCP, 9253/TCP
    Host Ports:  53/UDP, 53/TCP, 9253/TCP
    Args:
      -localip
      169.254.25.10
      -conf
      /etc/coredns/Corefile
      -upstreamsvc
      coredns
    Limits:
      memory:  170Mi
```

```yaml
Corefile:
----
poc-cilium-test:53 {
    errors
    cache {
        success 9984 30
        denial 9984 5
    }
    reload
    loop
    bind 169.254.25.10
    forward . coredns-ip {
        force_tcp
    }
    prometheus :9253
    health 169.254.25.10:9254
}
in-addr.arpa:53 {
    errors
    cache 30
    reload
    loop
    bind 169.254.25.10
    forward . coredns-ip {
        force_tcp
    }
    prometheus :9253
}
ip6.arpa:53 {
    errors
    cache 30
    reload
    loop
    bind 169.254.25.10
    forward . coredns-ip {
        force_tcp
    }
    prometheus :9253
}
.:53 {
    errors
    cache 30
    reload
    loop
    bind 169.254.25.10
    forward . /etc/resolv.conf
    prometheus :9253
}
```

Any idea what could be happening here or are we hitting a bug?

cc @necatican 

### Cilium Version

cilium version
cilium-cli: v0.9.3 compiled with go1.17.3 on darwin/amd64
cilium image (default): v1.10.5
cilium image (stable): v1.11.5
cilium image (running): v1.11.2

### Kernel Version

uname -a
Linux poc-cilium-test-1 5.13.0-39-generic #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

cilium connectivity test outpu

```bash
cilium connectivity test 
ℹ️  Monitor aggregation detected, will skip some flow validation steps
✨ [poc-cilium-test] Creating namespace for connectivity check...
✨ [poc-cilium-test] Deploying echo-same-node service...
✨ [poc-cilium-test] Deploying same-node deployment...
✨ [poc-cilium-test] Deploying client deployment...
✨ [poc-cilium-test] Deploying client2 deployment...
✨ [poc-cilium-test] Deploying echo-other-node service...
✨ [poc-cilium-test] Deploying other-node deployment...
⌛ [poc-cilium-test] Waiting for deployments [client client2 echo-same-node] to become ready...
⌛ [poc-cilium-test] Waiting for deployments [echo-other-node] to become ready...
⌛ [poc-cilium-test] Waiting for CiliumEndpoint for pod cilium-test/client-7568bc7f86-9hjkp to appear...
⌛ [poc-cilium-test] Waiting for CiliumEndpoint for pod cilium-test/client2-686d5f784b-xvplx to appear...
⌛ [poc-cilium-test] Waiting for CiliumEndpoint for pod cilium-test/echo-other-node-59d779959c-gj5rp to appear...
⌛ [poc-cilium-test] Waiting for CiliumEndpoint for pod cilium-test/echo-same-node-5767b7b99d-qchrk to appear...
⌛ [poc-cilium-test] Waiting for Service cilium-test/echo-other-node to become ready...
⌛ [poc-cilium-test] Waiting for Service cilium-test/echo-same-node to become ready...
⌛ [poc-cilium-test] Waiting for NodePort some-ip:32452 (cilium-test/echo-same-node) to become ready...
⌛ [poc-cilium-test] Waiting for NodePort some-ip:30389 (cilium-test/echo-other-node) to become ready...
⌛ [poc-cilium-test] Waiting for NodePort some-ip:30389 (cilium-test/echo-other-node) to become ready...
⌛ [poc-cilium-test] Waiting for NodePort some-ip:32452 (cilium-test/echo-same-node) to become ready...
⌛ [poc-cilium-test] Waiting for NodePort some-ip:30389 (cilium-test/echo-other-node) to become ready...
⌛ [poc-cilium-test] Waiting for NodePort some-ip:32452 (cilium-test/echo-same-node) to become ready...
⌛ [poc-cilium-test] Waiting for NodePort some-ip:30389 (cilium-test/echo-other-node) to become ready...
⌛ [poc-cilium-test] Waiting for NodePort some-ip:32452 (cilium-test/echo-same-node) to become ready...
ℹ️  Skipping IPCache check
⌛ [poc-cilium-test] Waiting for pod cilium-test/client-7568bc7f86-9hjkp to reach default/kubernetes service...
⌛ [poc-cilium-test] Waiting for pod cilium-test/client2-686d5f784b-xvplx to reach default/kubernetes service...
🔭 Enabling Hubble telescope...
⚠️  Unable to contact Hubble Relay, disabling Hubble telescope and flow validation: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp [::1]:4245: connect: connection refused"
ℹ️  Expose Relay locally with:
   cilium hubble enable
   cilium status --wait
   cilium hubble port-forward&
🏃 Running tests...

[=] Test [no-policies]
........................................
[=] Test [allow-all]
....................................
[=] Test [client-ingress]
..
[=] Test [echo-ingress]
....
[=] Test [client-egress]
....
[=] Test [to-entities-world]
.
  ℹ️  📜 Applying CiliumNetworkPolicy 'client-egress-to-entities-world' to namespace 'cilium-test'..
  [-] Scenario [to-entities-world/pod-to-world]
  [.] Action [to-entities-world/pod-to-world/http-to-one-one-one-one-0: cilium-test/client-7568bc7f86-9hjkp (some-ip) -> one-one-one-one-http (one.one.one.one:80)]
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null http://one.one.one.one:80" failed: command terminated with exit code 28
  ℹ️  curl output:
  curl: (28) Resolving timed out after 5000 milliseconds
:0 -> :0 = 000
  
  📄 No flows recorded during action http-to-one-one-one-one-0
  📄 No flows recorded during action http-to-one-one-one-one-0
  [.] Action [to-entities-world/pod-to-world/https-to-one-one-one-one-0: cilium-test/client-7568bc7f86-9hjkp (10.233.65.69) -> one-one-one-one-https (one.one.one.one:443)]
  [.] Action [to-entities-world/pod-to-world/https-to-one-one-one-one-index-0: cilium-test/client-7568bc7f86-9hjkp (10.233.65.69) -> one-one-one-one-https-index (one.one.one.one:443)]
  [.] Action [to-entities-world/pod-to-world/http-to-one-one-one-one-1: cilium-test/client2-686d5f784b-xvplx (10.233.65.123) -> one-one-one-one-http (one.one.one.one:80)]
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null http://one.one.one.one:80" failed: command terminated with exit code 28
  ℹ️  curl output:
  curl: (28) Resolving timed out after 5000 milliseconds
:0 -> :0 = 000
  
  📄 No flows recorded during action http-to-one-one-one-one-1
  📄 No flows recorded during action http-to-one-one-one-one-1
  [.] Action [to-entities-world/pod-to-world/https-to-one-one-one-one-1: cilium-test/client2-686d5f784b-xvplx (10.233.65.123) -> one-one-one-one-https (one.one.one.one:443)]
  [.] Action [to-entities-world/pod-to-world/https-to-one-one-one-one-index-1: cilium-test/client2-686d5f784b-xvplx (10.233.65.123) -> one-one-one-one-https-index (one.one.one.one:443)]
  ℹ️  📜 Deleting CiliumNetworkPolicy 'client-egress-to-entities-world' from namespace 'cilium-test'..

[=] Test [to-cidr-1111]
....
[=] Test [echo-ingress-l7]
....
[=] Test [client-egress-l7]
........
  ℹ️  📜 Applying CiliumNetworkPolicy 'client-egress-only-dns' to namespace 'cilium-test'..
  ℹ️  📜 Applying CiliumNetworkPolicy 'client-egress-l7-http' to namespace 'cilium-test'..
  [-] Scenario [client-egress-l7/pod-to-pod]
  [.] Action [client-egress-l7/pod-to-pod/curl-0: cilium-test/client-7568bc7f86-9hjkp (10.233.65.69) -> cilium-test/echo-other-node-59d779959c-gj5rp (10.233.64.161:8080)]
  [.] Action [client-egress-l7/pod-to-pod/curl-1: cilium-test/client-7568bc7f86-9hjkp (10.233.65.69) -> cilium-test/echo-same-node-5767b7b99d-qchrk (10.233.65.57:8080)]
  [.] Action [client-egress-l7/pod-to-pod/curl-2: cilium-test/client2-686d5f784b-xvplx (10.233.65.123) -> cilium-test/echo-other-node-59d779959c-gj5rp (10.233.64.161:8080)]
  [.] Action [client-egress-l7/pod-to-pod/curl-3: cilium-test/client2-686d5f784b-xvplx (10.233.65.123) -> cilium-test/echo-same-node-5767b7b99d-qchrk (10.233.65.57:8080)]
  [-] Scenario [client-egress-l7/pod-to-world]
  [.] Action [client-egress-l7/pod-to-world/http-to-one-one-one-one-0: cilium-test/client-7568bc7f86-9hjkp (10.233.65.69) -> one-one-one-one-http (one.one.one.one:80)]
  [.] Action [client-egress-l7/pod-to-world/https-to-one-one-one-one-0: cilium-test/client-7568bc7f86-9hjkp (10.233.65.69) -> one-one-one-one-https (one.one.one.one:443)]
  [.] Action [client-egress-l7/pod-to-world/https-to-one-one-one-one-index-0: cilium-test/client-7568bc7f86-9hjkp (10.233.65.69) -> one-one-one-one-https-index (one.one.one.one:443)]
  [.] Action [client-egress-l7/pod-to-world/http-to-one-one-one-one-1: cilium-test/client2-686d5f784b-xvplx (10.233.65.123) -> one-one-one-one-http (one.one.one.one:80)]
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null http://one.one.one.one:80" failed: command terminated with exit code 28
  ℹ️  curl output:
  curl: (28) Resolving timed out after 5000 milliseconds
:0 -> :0 = 000
  
  📄 No flows recorded during action http-to-one-one-one-one-1
  📄 No flows recorded during action http-to-one-one-one-one-1
  [.] Action [client-egress-l7/pod-to-world/https-to-one-one-one-one-1: cilium-test/client2-686d5f784b-xvplx (10.233.65.123) -> one-one-one-one-https (one.one.one.one:443)]
  [.] Action [client-egress-l7/pod-to-world/https-to-one-one-one-one-index-1: cilium-test/client2-686d5f784b-xvplx (10.233.65.123) -> one-one-one-one-https-index (one.one.one.one:443)]
  ℹ️  📜 Deleting CiliumNetworkPolicy 'client-egress-only-dns' from namespace 'cilium-test'..
  ℹ️  📜 Deleting CiliumNetworkPolicy 'client-egress-l7-http' from namespace 'cilium-test'..

[=] Test [dns-only]
..........
[=] Test [to-fqdns]
.
  ℹ️  📜 Applying CiliumNetworkPolicy 'client-egress-to-fqdns-one-one-one-one' to namespace 'cilium-test'..
  [-] Scenario [to-fqdns/pod-to-world]
  [.] Action [to-fqdns/pod-to-world/http-to-one-one-one-one-0: cilium-test/client2-686d5f784b-xvplx (10.233.65.123) -> one-one-one-one-http (one.one.one.one:80)]
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null http://one.one.one.one:80" failed: command terminated with exit code 28
  ℹ️  curl output:
  curl: (28) Resolving timed out after 5000 milliseconds
:0 -> :0 = 000
  
  📄 No flows recorded during action http-to-one-one-one-one-0
  📄 No flows recorded during action http-to-one-one-one-one-0
  [.] Action [to-fqdns/pod-to-world/https-to-one-one-one-one-0: cilium-test/client2-686d5f784b-xvplx (some-ip) -> one-one-one-one-https (one.one.one.one:443)]
  [.] Action [to-fqdns/pod-to-world/https-to-one-one-one-one-index-0: cilium-test/client2-686d5f784b-xvplx (10.233.65.123) -> one-one-one-one-https-index (one.one.one.one:443)]
  [.] Action [to-fqdns/pod-to-world/http-to-one-one-one-one-1: cilium-test/client-7568bc7f86-9hjkp (some-ip) -> one-one-one-one-http (one.one.one.one:80)]
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --connect-timeout 5 --output /dev/null http://one.one.one.one:80" failed: command terminated with exit code 28
  ℹ️  curl output:
  curl: (28) Resolving timed out after 5000 milliseconds
:0 -> :0 = 000
  
  📄 No flows recorded during action http-to-one-one-one-one-1
  📄 No flows recorded during action http-to-one-one-one-one-1
  [.] Action [to-fqdns/pod-to-world/https-to-one-one-one-one-1: cilium-test/client-7568bc7f86-9hjkp (some-ip) -> one-one-one-one-https (one.one.one.one:443)]
  [.] Action [to-fqdns/pod-to-world/https-to-one-one-one-one-index-1: cilium-test/client-7568bc7f86-9hjkp (some-ip) -> one-one-one-one-https-index (one.one.one.one:443)]
  ℹ️  📜 Deleting CiliumNetworkPolicy 'client-egress-to-fqdns-one-one-one-one' from namespace 'cilium-test'..

📋 Test Report
❌ 3/11 tests failed (5/126 actions), 0 tests skipped, 0 scenarios skipped:
Test [to-entities-world]:
  ❌ to-entities-world/pod-to-world/http-to-one-one-one-one-0: cilium-test/client-7568bc7f86-9hjkp (some-ip) -> one-one-one-one-http (one.one.one.one:80)
  ❌ to-entities-world/pod-to-world/http-to-one-one-one-one-1: cilium-test/client2-686d5f784b-xvplx (some-ip) -> one-one-one-one-http (one.one.one.one:80)
Test [client-egress-l7]:
  ❌ client-egress-l7/pod-to-world/http-to-one-one-one-one-1: cilium-test/client2-686d5f784b-xvplx (some-ip) -> one-one-one-one-http (one.one.one.one:80)
Test [to-fqdns]:
  ❌ to-fqdns/pod-to-world/http-to-one-one-one-one-0: cilium-test/client2-686d5f784b-xvplx (some-ip) -> one-one-one-one-http (one.one.one.one:80)
  ❌ to-fqdns/pod-to-world/http-to-one-one-one-one-1: cilium-test/client-7568bc7f86-9hjkp (some-ip) -> one-one-one-one-http (one.one.one.one:80)
Connectivity test failed: 3 tests failed
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #23910: datapath: Per endpoint routes broken for IPv6 traffic between (remote) node to pod when netpol is applied
The ICMPv6 neighbor resolution is striking us again (#23852). When sending a request from a remote node / a local node to the `echo` pod, the ICMPv6 NS is using the `echo`'s pod veth iface in the host netns IPv6 addr:
```
7: lxc75bc3f9009e7    inet6 fe80::ec8b:fdff:fe18:6632/64 scope link
```

And of course, it's not recognized by the `to-container` @ `lxc75bc3f9009e7`:

```
CPU 07: MARK 0x0 FROM 1192 DEBUG: Inheriting identity=1 from stack
<- stack flow 0x0 , identity host->unknown state unknown ifindex 0 orig-ip 0.0.0.0: fe80::ec8b:fdff:fe18:6632 -> ff02::1:ff00:3816 NeighborSolicitation
CPU 07: MARK 0x0 FROM 1192 DEBUG: Conntrack lookup 1/2: src=[::fe18:6632]:0 dst=[::ff00:3816]:0
CPU 07: MARK 0x0 FROM 1192 DEBUG: Conntrack lookup 2/2: nexthdr=58 flags=0
CPU 07: MARK 0x0 FROM 1192 DEBUG: CT verdict: New, revnat=0
CPU 07: MARK 0x0 FROM 1192 DEBUG: Successfully mapped addr.p4=[::fe18:6632] to identity=2
CPU 07: MARK 0x0 FROM 1192 DEBUG: Attempting local delivery for container id 1192 from seclabel 44107
CPU 07: MARK 0x0 FROM 1192 DEBUG: Policy evaluation would deny packet from 2 to 44107
Policy verdict log: flow 0x0 local EP ID 1192, remote ID world, proto 58, ingress, action deny, match none, fe80::ec8b:fdff:fe18:6632 -> ff02::1:ff00:3816 NeighborSolicitation
xx drop (Policy denied) flow 0x0 to endpoint 1192, ifindex 7, file 2:1604, , identity world->44107: fe80::ec8b:fdff:fe18:6632 -> ff02::1:ff00:3816 NeighborSolicitation
```

A few possible fixes:
- Add the IPv6 local scope addr of a pod into the IPCache, so that the non-world sec ID is used.
- Respect the `HOST_ID` skb mark in the `to-container` section.

### LINKED ISSUE #25242: Azure LB health probe failing (IPv6 link-local address)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When Azure LB is deployed to expose Kubernetes service, it will never become healthy and load balance traffic as health probes are failing.

Probes are reaching nodes properly but it seems that probes are dropped/denied by Cilium and thus load balancer is not receiving responds to probes.

LB probes have source address from IPv6 link-local address space, in my case `fe80::1234:5678:9abc`.

tcpdump at node:
```
tcpdump -nei any ip6 and port 30460
tcpdump: data link type LINUX_SLL2
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on any, link-type LINUX_SLL2 (Linux cooked v2), snapshot length 262144 bytes
12:52:51.558487 enP47348s1 In  ifindex 3 12:34:56:78:9a:bc ethertype IPv6 (0x86dd), length 92: fe80::1234:5678:9abc.65168 > fddc:bbc4:705:2::a.30460: Flags [SEW], seq 1547269981, win 64800, options [mss 1440,nop,wscale 8,nop,nop,sackOK], length 0
12:52:51.558487 eth0  In  ifindex 2 12:34:56:78:9a:bc ethertype IPv6 (0x86dd), length 92: fe80::1234:5678:9abc.65168 > fddc:bbc4:705:2::a.30460: Flags [SEW], seq 1547269981, win 64800, options [mss 1440,nop,wscale 8,nop,nop,sackOK], length 0
12:52:52.573384 enP47348s1 In  ifindex 3 12:34:56:78:9a:bc ethertype IPv6 (0x86dd), length 92: fe80::1234:5678:9abc.65168 > fddc:bbc4:705:2::a.30460: Flags [SEW], seq 1547269981, win 64800, options [mss 1440,nop,wscale 8,nop,nop,sackOK], length 0
12:52:52.573384 eth0  In  ifindex 2 12:34:56:78:9a:bc ethertype IPv6 (0x86dd), length 92: fe80::1234:5678:9abc.65168 > fddc:bbc4:705:2::a.30460: Flags [SEW], seq 1547269981, win 64800, options [mss 1440,nop,wscale 8,nop,nop,sackOK], length 0
12:52:54.579086 enP47348s1 In  ifindex 3 12:34:56:78:9a:bc ethertype IPv6 (0x86dd), length 92: fe80::1234:5678:9abc.65168 > fddc:bbc4:705:2::a.30460: Flags [S], seq 1547269981, win 64800, options [mss 1440,nop,wscale 8,nop,nop,sackOK], length 0
12:52:54.579086 eth0  In  ifindex 2 12:34:56:78:9a:bc ethertype IPv6 (0x86dd), length 92: fe80::1234:5678:9abc.65168 > fddc:bbc4:705:2::a.30460: Flags [S], seq 1547269981, win 64800, options [mss 1440,nop,wscale 8,nop,nop,sackOK], length 0
12:52:57.574024 enP47348s1 In  ifindex 3 12:34:56:78:9a:bc ethertype IPv6 (0x86dd), length 92: fe80::1234:5678:9abc.65330 > fddc:bbc4:705:2::a.30460: Flags [SEW], seq 3203281907, win 64800, options [mss 1440,nop,wscale 8,nop,nop,sackOK], length 0
12:52:57.574024 eth0  In  ifindex 2 12:34:56:78:9a:bc ethertype IPv6 (0x86dd), length 92: fe80::1234:5678:9abc.65330 > fddc:bbc4:705:2::a.30460: Flags [SEW], seq 3203281907, win 64800, options [mss 1440,nop,wscale 8,nop,nop,sackOK], length 0
12:52:58.587394 enP47348s1 In  ifindex 3 12:34:56:78:9a:bc ethertype IPv6 (0x86dd), length 92: fe80::1234:5678:9abc.65330 > fddc:bbc4:705:2::a.30460: Flags [SEW], seq 3203281907, win 64800, options [mss 1440,nop,wscale 8,nop,nop,sackOK], length 0
12:52:58.587394 eth0  In  ifindex 2 12:34:56:78:9a:bc ethertype IPv6 (0x86dd), length 92: fe80::1234:5678:9abc.65330 > fddc:bbc4:705:2::a.30460: Flags [SEW], seq 3203281907, win 64800, options [mss 1440,nop,wscale 8,nop,nop,sackOK], length 0
12:53:00.601813 enP47348s1 In  ifindex 3 12:34:56:78:9a:bc ethertype IPv6 (0x86dd), length 92: fe80::1234:5678:9abc.65330 > fddc:bbc4:705:2::a.30460: Flags [S], seq 3203281907, win 64800, options [mss 1440,nop,wscale 8,nop,nop,sackOK], length 0
12:53:00.601813 eth0  In  ifindex 2 12:34:56:78:9a:bc ethertype IPv6 (0x86dd), length 92: fe80::1234:5678:9abc.65330 > fddc:bbc4:705:2::a.30460: Flags [S], seq 3203281907, win 64800, options [mss 1440,nop,wscale 8,nop,nop,sackOK], length 0
```

I managed to capture logs from hubble and cilium monitor. Both contains drop verdict, but I captured such drop verdicts just once and not again later.

Issue is reproducible either by using Azure cloud provider to expose Kubernetes service automatically or by creating NodePort Kubernetes service and deploying load balancer manually in Azure.

### Cilium Version

v1.12.4
v1.13.2

### Kernel Version

5.15.0-1036-azure #43-Ubuntu SMP Wed Mar 29 16:11:05 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.25.4

### Sysdump

_No response_

### Relevant log output

```shell
hubble observe -f --verdict DROPPED
Apr 26 11:12:23.171: [fddc:bbc4:705:2::4]:30460 (host) <> [fe80::1234:5678:9abc]:54675 (world) Stale or unroutable IP DROPPED (TCP Flags: SYN, ACK)
Apr 26 11:12:23.395: [fddc:bbc4:705:2::4]:30460 (host) <> [fe80::1234:5678:9abc]:54503 (world) Stale or unroutable IP DROPPED (TCP Flags: SYN, ACK)
Apr 26 11:12:24.155: [fddc:bbc4:705:2::4]:30460 (host) <> [fe80::1234:5678:9abc]:54769 (world) Stale or unroutable IP DROPPED (TCP Flags: SYN, ACK)
Apr 26 11:12:25.154: [fddc:bbc4:705:2::4]:30460 (host) <> [fe80::1234:5678:9abc]:54769 (world) Stale or unroutable IP DROPPED (TCP Flags: SYN, ACK)


cilium monitor -t drop
Listening for events on 8 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
level=info msg="Initializing dissection cache..." subsys=monitor
xx drop (Stale or unroutable IP) flow 0x2885480f to endpoint 0, file bpf_host.c line 351, , identity host->unknown: [fddc:bbc4:705:2::4]:30460 -> [fe80::1234:5678:9abc]:56055 tcp SYN, ACK
xx drop (Stale or unroutable IP) flow 0xa247e0c9 to endpoint 0, file bpf_host.c line 351, , identity host->unknown: [fddc:bbc4:705:2::4]:30460 -> [fe80::1234:5678:9abc]:56055 tcp SYN, ACK
xx drop (Stale or unroutable IP) flow 0x6aa6b80e to endpoint 0, file bpf_host.c line 351, , identity host->unknown: [fddc:bbc4:705:2::4]:30460 -> [fe80::1234:5678:9abc]:55938 tcp SYN, ACK
xx drop (Stale or unroutable IP) flow 0x84d4eaf1 to endpoint 0, file bpf_host.c line 351, , identity host->unknown: [fddc:bbc4:705:2::4]:30460 -> [fe80::1234:5678:9abc]:55564 tcp SYN, ACK
xx drop (Stale or unroutable IP) flow 0x33bb69e7 to endpoint 0, file bpf_host.c line 351, , identity host->unknown: [fddc:bbc4:705:2::4]:30460 -> [fe80::1234:5678:9abc]:56055 tcp SYN, ACK
```

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by asauber**
### Background

This is a fix for a regression in the local addresses logic, introduced in 080857bdedca as part of the implementation for AddressScopeMax. Addresses with the form of a link-local unicast address began to be filtered out of the local address aggregation, causing them to labeled with the "world" identity for the sake of policy enforcement. Examples of such addresses include:

169.254.10.10
fe80::1234

This caused issues for a variety of users, whose policies allowing "host" traffic would no longer allow traffic to these addresses, forcing the use of workarounds involving CIDR policies, which is not the intended behavior for this type of address. This was a regression as of Cilium 1.12.0-rc2. One reason for this regression was that logic prior to the change looked at the address scope, whereas logic after the change looked at the address bytes, and it was found that many users had assigned addresses of the forms above but with scope global, causing them to again be filtered out unconditionally.

### Implementation

This patch factors out the local address filtering logic into a function, removes the skip over IsLinkLocalUnicast(), and adds a variety of unit tests for that function.

### Important Note

This change has no effect on link-local services such as the AWS Metadata service which operates on `169.254.169.254/32` because that address is not assigned to any interface of the local host and thus is not enumerated by rnetlink. The address is still labeled with the "world" identity as usual. This has been tested on EKS and kind.

### Fixes

fixes: https://github.com/cilium/cilium/issues/25242
fixes: https://github.com/cilium/cilium/issues/23910
fixes: https://github.com/cilium/cilium/issues/16308
fixes: https://github.com/cilium/cilium/issues/20055

```release-note
Fix a regression in which link-local addresses were not treated with the "host" identity in some circumstances.
```

### CODE REVIEW

File: pkg/datapath/linux/node_addressing.go [hunk 1]
```diff
@@ -28,20 +28,11 @@ func listLocalAddresses(family int) ([]net.IP, error) {
...
-		}
-
-		addresses = append(addresses, addr.IP)
-	}
+	filteredIPs := filterLocalAddresses(addrs, ipsToExclude, option.Config.AddressScopeMax)
+	addresses = append(addresses, filteredIPs...)
 
+	// If AddressScopeMax is a scope more broad (numerically less than) than SCOPE_LINK then include
+	// all addresses at SCOPE_LINK which are assigned to the Cilium host device.
 	if option.Config.AddressScopeMax < int(netlink.SCOPE_LINK) {
```
Comment (asauber) [inline pkg/datapath/linux/node_addressing.go:36]: @borkmann Should this be "`<=`" rather than "`<`"? If our max scope is `SCOPE_LINK`, then I think we should include these addresses.

File: pkg/datapath/linux/node_addressing.go [hunk 2]
```diff
@@ -59,6 +50,28 @@ func listLocalAddresses(family int) ([]net.IP, error) {
...
 
+func filterLocalAddresses(addrs []netlink.Addr, ipsToExclude []net.IP, addrScopeMax int) []net.IP {
+	var filteredIPs []net.IP
+	for _, addr := range addrs {
+		// This address is at a scope which is more narrow (numerically greater than) the configured
+		// max address scope. For example, if this addr is SCOPE_NOWHERE, and our addrScopeMax is
+		// SCOPE_LINK, then we do NOT treat the address as a local address. Similarly, if this addr
+		// is SCOPE_HOST, and our addrScopeMax is SCOPE_LINK, we do NOT treat the address as a local
+		// address.
+		if addr.Scope > addrScopeMax {
```
Comment (asauber) [inline pkg/datapath/linux/node_addressing.go:61]: @borkmann Should this be "`<`"? Is this max supposed to be the "most narrowly scoped" address that we will treat as local or the "most universally scoped" address that we will treat as local?

Comment (asauber) [reply pkg/datapath/linux/node_addressing.go:61]: I suppose it's obvious from 080857bdedca that the max is intended to be the "most narrowly scoped" address.

File: pkg/datapath/linux/node_addressing.go (hunk 1 above)
Comment (gentoo-root) [reply pkg/datapath/linux/node_addressing.go:36]: I think `<` is correct. It matches the `addr.Scope > option.Config.AddressScopeMax` above, i.e. SCOPE_LINK will be included either here or there.

**Review by gentoo-root — APPROVED** [review]

File: pkg/datapath/linux/node_addressing.go (hunk 1 above)
Comment (asauber) [reply pkg/datapath/linux/node_addressing.go:36]: Right, makes sense. If we haven't included them above because our Max is too low, then include them here.

**Comment by asauber** [comment]
/test-1.26-net-next
