### PR TITLE
node: Fix race condition on labels' getter/setter

### LINKED ISSUE #16180: [Race Detector] Race between `pkg/nodediscovery.(*NodeDiscovery).StartDiscovery` and `pkg/node.SetLabels()`
Observed https://jenkins.cilium.io/view/Race%20Detection/job/Ginkgo-CI-Tests-4.19-Pipeline-Race-Detection/136/

```
2021-05-16T01:49:01.893157891Z ==================
2021-05-16T01:49:01.893174123Z WARNING: DATA RACE
2021-05-16T01:49:01.893177901Z Read at 0x0000056c4b58 by main goroutine:
2021-05-16T01:49:01.893180968Z   github.com/cilium/cilium/pkg/nodediscovery.(*NodeDiscovery).StartDiscovery()
2021-05-16T01:49:01.893183999Z       /go/src/github.com/cilium/cilium/pkg/nodediscovery/nodediscovery.go:182 +0x3ab
2021-05-16T01:49:01.893187013Z   github.com/cilium/cilium/daemon/cmd.NewDaemon()
2021-05-16T01:49:01.893190028Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon.go:727 +0x346b
2021-05-16T01:49:01.893193068Z   github.com/cilium/cilium/daemon/cmd.runDaemon()
2021-05-16T01:49:01.893196056Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1567 +0xb8b
2021-05-16T01:49:01.893199188Z   github.com/cilium/cilium/daemon/cmd.glob..func1()
2021-05-16T01:49:01.893202295Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:136 +0x3a4
2021-05-16T01:49:01.893205265Z   github.com/spf13/cobra.(*Command).execute()
2021-05-16T01:49:01.893208229Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:854 +0x8cb
2021-05-16T01:49:01.893211562Z   github.com/spf13/cobra.(*Command).ExecuteC()
2021-05-16T01:49:01.893214416Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:958 +0x4b2
2021-05-16T01:49:01.893217513Z   github.com/spf13/cobra.(*Command).Execute()
2021-05-16T01:49:01.893220638Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:895 +0x88
2021-05-16T01:49:01.893223716Z   github.com/cilium/cilium/daemon/cmd.Execute()
2021-05-16T01:49:01.893226680Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:161 +0x69
2021-05-16T01:49:01.893229948Z   main.main()
2021-05-16T01:49:01.893233266Z       /go/src/github.com/cilium/cilium/daemon/main.go:22 +0x2f
2021-05-16T01:49:01.893236611Z   runtime.main()
2021-05-16T01:49:01.893239810Z       /usr/local/go/src/runtime/proc.go:225 +0x255
2021-05-16T01:49:01.893242970Z   github.com/cilium/ebpf.init()
2021-05-16T01:49:01.893245882Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/syscalls.go:437 +0x58b
2021-05-16T01:49:01.893249173Z   github.com/cilium/ebpf.init()
2021-05-16T01:49:01.893262697Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/prog.go:453 +0x518
2021-05-16T01:49:01.893266628Z   github.com/cilium/ebpf.init()
2021-05-16T01:49:01.893270035Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/syscalls.go:419 +0x4ab
2021-05-16T01:49:01.893273358Z   github.com/cilium/ebpf.init()
2021-05-16T01:49:01.893276608Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/syscalls.go:235 +0x439
2021-05-16T01:49:01.893279781Z   github.com/cilium/ebpf.init()
2021-05-16T01:49:01.893282678Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/syscalls.go:217 +0x3cc
2021-05-16T01:49:01.893285899Z   runtime.doInit()
2021-05-16T01:49:01.893288698Z       /usr/local/go/src/runtime/proc.go:6309 +0xeb
2021-05-16T01:49:01.893291719Z   github.com/cilium/ebpf/internal/btf.init()
2021-05-16T01:49:01.893295636Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/internal/btf/btf.go:728 +0x1cc
2021-05-16T01:49:01.893299005Z 
2021-05-16T01:49:01.893302051Z Previous write at 0x0000056c4b58 by goroutine 52:
2021-05-16T01:49:01.893305233Z   github.com/cilium/cilium/pkg/node.SetLabels()
2021-05-16T01:49:01.893308171Z       /go/src/github.com/cilium/cilium/pkg/node/host_endpoint.go:33 +0x229
2021-05-16T01:49:01.893311311Z   github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).updateK8sNodeV1()
2021-05-16T01:49:01.893314368Z       /go/src/github.com/cilium/cilium/pkg/k8s/watchers/node.go:85 +0x219
2021-05-16T01:49:01.893317358Z   github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).nodesInit.func1()
2021-05-16T01:49:01.893320458Z       /go/src/github.com/cilium/cilium/pkg/k8s/watchers/node.go:44 +0xd1
2021-05-16T01:49:01.893323648Z   k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd()
2021-05-16T01:49:01.893326739Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:231 +0x8f
2021-05-16T01:49:01.893329915Z   k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnAdd()
2021-05-16T01:49:01.893332900Z       <autogenerated>:1 +0x2a
2021-05-16T01:49:01.893336272Z   github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1()
2021-05-16T01:49:01.893339333Z       /go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:119 +0x297
2021-05-16T01:49:01.893342324Z   k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop()
2021-05-16T01:49:01.893345177Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:544 +0x50d
2021-05-16T01:49:01.893348882Z   k8s.io/client-go/tools/cache.(*controller).processLoop()
2021-05-16T01:49:01.893351805Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:183 +0x83
2021-05-16T01:49:01.893354882Z   k8s.io/client-go/tools/cache.(*controller).processLoop-fm()
2021-05-16T01:49:01.893362595Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:181 +0x4a
2021-05-16T01:49:01.893366126Z   k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1()
2021-05-16T01:49:01.893369152Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x75
2021-05-16T01:49:01.893372247Z   k8s.io/apimachinery/pkg/util/wait.BackoffUntil()
2021-05-16T01:49:01.893375304Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xba
2021-05-16T01:49:01.893378408Z   k8s.io/apimachinery/pkg/util/wait.JitterUntil()
2021-05-16T01:49:01.893381400Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x114
2021-05-16T01:49:01.893384591Z   k8s.io/apimachinery/pkg/util/wait.Until()
2021-05-16T01:49:01.893387520Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x507
2021-05-16T01:49:01.893391209Z   k8s.io/client-go/tools/cache.(*controller).Run()
2021-05-16T01:49:01.893394334Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:154 +0x4a9
2021-05-16T01:49:01.893397160Z 
2021-05-16T01:49:01.893400524Z Goroutine 52 (running) created at:
2021-05-16T01:49:01.893416130Z   github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).nodesInit()
2021-05-16T01:49:01.893419216Z       /go/src/github.com/cilium/cilium/pkg/k8s/watchers/node.go:71 +0x4cb
2021-05-16T01:49:01.893422544Z   github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).EnableK8sWatcher()
2021-05-16T01:49:01.893425601Z       /go/src/github.com/cilium/cilium/pkg/k8s/watchers/watcher.go:449 +0x5c4
2021-05-16T01:49:01.893428739Z   github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).InitK8sSubsystem()
2021-05-16T01:49:01.893431890Z       /go/src/github.com/cilium/cilium/pkg/k8s/watchers/watcher.go:302 +0x92
2021-05-16T01:49:01.893435072Z   github.com/cilium/cilium/daemon/cmd.NewDaemon()
2021-05-16T01:49:01.893438211Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon.go:591 +0x8904
2021-05-16T01:49:01.893441346Z   github.com/cilium/cilium/daemon/cmd.runDaemon()
2021-05-16T01:49:01.893444351Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1567 +0xb8b
2021-05-16T01:49:01.893447502Z   github.com/cilium/cilium/daemon/cmd.glob..func1()
2021-05-16T01:49:01.893450596Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:136 +0x3a4
2021-05-16T01:49:01.893453790Z   github.com/spf13/cobra.(*Command).execute()
2021-05-16T01:49:01.893456479Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:854 +0x8cb
2021-05-16T01:49:01.893459454Z   github.com/spf13/cobra.(*Command).ExecuteC()
2021-05-16T01:49:01.893462570Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:958 +0x4b2
2021-05-16T01:49:01.893465890Z   github.com/spf13/cobra.(*Command).Execute()
2021-05-16T01:49:01.893472964Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:895 +0x88
2021-05-16T01:49:01.893476184Z   github.com/cilium/cilium/daemon/cmd.Execute()
2021-05-16T01:49:01.893479079Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:161 +0x69
2021-05-16T01:49:01.893482047Z   main.main()
2021-05-16T01:49:01.893485130Z       /go/src/github.com/cilium/cilium/daemon/main.go:22 +0x2f
2021-05-16T01:49:01.893488534Z   runtime.main()
2021-05-16T01:49:01.893491702Z       /usr/local/go/src/runtime/proc.go:225 +0x255
2021-05-16T01:49:01.893495114Z   github.com/cilium/ebpf.init()
2021-05-16T01:49:01.893498009Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/syscalls.go:437 +0x58b
2021-05-16T01:49:01.893501322Z   github.com/cilium/ebpf.init()
2021-05-16T01:49:01.893504505Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/prog.go:453 +0x518
2021-05-16T01:49:01.893507682Z   github.com/cilium/ebpf.init()
2021-05-16T01:49:01.893511560Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/syscalls.go:419 +0x4ab
2021-05-16T01:49:01.893514755Z   github.com/cilium/ebpf.init()
2021-05-16T01:49:01.893530431Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/syscalls.go:235 +0x439
2021-05-16T01:49:01.893533505Z   github.com/cilium/ebpf.init()
2021-05-16T01:49:01.893536468Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/syscalls.go:217 +0x3cc
2021-05-16T01:49:01.893554298Z   runtime.doInit()
2021-05-16T01:49:01.893558840Z       /usr/local/go/src/runtime/proc.go:6309 +0xeb
2021-05-16T01:49:01.893561783Z   github.com/cilium/ebpf/internal/btf.init()
2021-05-16T01:49:01.893564343Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/internal/btf/btf.go:728 +0x1cc
2021-05-16T01:49:01.893567254Z ==================
20
```

Commit 81f0626a9ec9eca7cf4baa741a7257a8b693bde0 is the likely culprit

/cc @pchaigno

### PR DESCRIPTION
**Pull request by pchaigno**
Our race detection pipeline detected a race condition between the setter and getter for the local node's labels:

    WARNING: DATA RACE
    Write at 0x000005882150 by goroutine 154:
      github.com/cilium/cilium/pkg/node.SetLabels()
          /go/src/github.com/cilium/cilium/pkg/node/host_endpoint.go:33 +0x1dc
      github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).updateK8sNodeV1()
          /go/src/github.com/cilium/cilium/pkg/k8s/watchers/node.go:89 +0x1cc
      github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).nodesInit.func1()
          /go/src/github.com/cilium/cilium/pkg/k8s/watchers/node.go:44 +0xd1
      k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd()
          /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:231 +0x8f
      k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnAdd()
          <autogenerated>:1 +0x2a
      github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1()
          /go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:119 +0x297
      k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop()
          /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:544 +0x50d
      k8s.io/client-go/tools/cache.(*controller).processLoop()
          /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:183 +0x83
      k8s.io/client-go/tools/cache.(*controller).processLoop-fm()
          /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:181 +0x4a
      k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1()
          /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x75
      k8s.io/apimachinery/pkg/util/wait.BackoffUntil()
          /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xba
      k8s.io/apimachinery/pkg/util/wait.JitterUntil()
          /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x114
      k8s.io/apimachinery/pkg/util/wait.Until()
          /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x507
      k8s.io/client-go/tools/cache.(*controller).Run()
          /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:154 +0x4a9

    Previous read at 0x000005882150 by main goroutine:
      github.com/cilium/cilium/pkg/nodediscovery.(*NodeDiscovery).StartDiscovery()
          /go/src/github.com/cilium/cilium/pkg/nodediscovery/nodediscovery.go:182 +0x3ab
      github.com/cilium/cilium/daemon/cmd.NewDaemon()
          /go/src/github.com/cilium/cilium/daemon/cmd/daemon.go:762 +0x34d6
      github.com/cilium/cilium/daemon/cmd.runDaemon()
          /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1558 +0xb8b
      github.com/cilium/cilium/daemon/cmd.glob..func1()
          /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:137 +0x3a4
      github.com/spf13/cobra.(*Command).execute()
          /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:854 +0x8cb
      github.com/spf13/cobra.(*Command).ExecuteC()
          /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:958 +0x4b2
      github.com/spf13/cobra.(*Command).Execute()
          /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:895 +0x88
      github.com/cilium/cilium/daemon/cmd.Execute()
          /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:162 +0x69
      main.main()
          /go/src/github.com/cilium/cilium/daemon/main.go:22 +0x2f
      runtime.main()
          /usr/local/go/src/runtime/proc.go:225 +0x255
      github.com/cilium/ebpf.init()
          /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/syscalls.go:437 +0x58b
      github.com/cilium/ebpf.init()
          /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/prog.go:453 +0x518
      github.com/cilium/ebpf.init()
          /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/syscalls.go:419 +0x4ab
      github.com/cilium/ebpf.init()
          /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/syscalls.go:235 +0x439
      github.com/cilium/ebpf.init()
          /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/syscalls.go:217 +0x3cc
      runtime.doInit()
          /usr/local/go/src/runtime/proc.go:6309 +0xeb
      github.com/cilium/ebpf/internal/btf.init()
          /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/internal/btf/btf.go:728 +0x1cc

This commit fixes it.

Fixes: https://github.com/cilium/cilium/pull/15217.
Fixes: https://github.com/cilium/cilium/issues/16180.

### CODE REVIEW

**Comment by pchaigno** [comment]
test-me-please

File: pkg/node/host_endpoint.go [hunk 1]
```diff
@@ -3,22 +3,31 @@
...
+	"github.com/cilium/cilium/pkg/lock"
+)
+
 const (
 	templateHostEndpointID = uint64(0xffff)
 )
 
 var (
 	labels     map[string]string
+	labelsMu   lock.Mutex
```
Comment (aanm) [inline pkg/node/host_endpoint.go]: could be  RWMutex

File: pkg/node/host_endpoint.go [hunk 2]
```diff
@@ -3,22 +3,31 @@
...
 	endpointID = templateHostEndpointID
 )
 
 // GetLabels returns the labels of this node.
 func GetLabels() map[string]string {
+	labelsMu.Lock()
```
Comment (aanm) [inline pkg/node/host_endpoint.go]: here would be  RLock

File: pkg/node/host_endpoint.go [hunk 3]
```diff
@@ -3,22 +3,31 @@
...
+	defer labelsMu.Unlock()
 	return labels
 }
 
 // SetLabels sets the labels of this node.
 func SetLabels(l map[string]string) {
+	labelsMu.Lock()
+	defer labelsMu.Unlock()
 	labels = l
 }
```
Comment (aanm) [inline pkg/node/host_endpoint.go:33]: While you are at it, can you fix the comment on line 39? :pray:

Comment (pchaigno) [reply pkg/node/host_endpoint.go:33]: Sure! Nice catch!

**Review by aanm — APPROVED** [review]

**Comment by pchaigno** [comment]
test-me-please

**Review by tklauser — APPROVED** [review]

**Review by borkmann — APPROVED** [review]

**Comment by pchaigno** [comment]
test-me-please
