### PR TITLE
pkg/azure/ipam: fix data race in (*Node).PopulateStatusFields

### LINKED ISSUE #13580: [RACE detector] data race in pkg/azure/ipam.(*Node).PopulateStatusFields()
```
WARNING: DATA RACE
Write at 0x00c000358270 by goroutine 57:
  github.com/cilium/cilium/pkg/azure/ipam.(*InstancesManager).Resync()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/azure/ipam/instances.go:98 +0x933
  github.com/cilium/cilium/pkg/ipam.(*NodeManager).instancesAPIResync()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:186 +0x8b
  github.com/cilium/cilium/pkg/ipam.NewNodeManager.func1()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:168 +0x8f
  github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:206 +0x5cf

Previous read at 0x00c000358270 by goroutine 250:
  github.com/cilium/cilium/pkg/azure/ipam.(*Node).PopulateStatusFields()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/azure/ipam/node.go:51 +0x11a
  github.com/cilium/cilium/pkg/ipam.(*Node).syncToAPIServer()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/ipam/node.go:716 +0x232
  github.com/cilium/cilium/pkg/ipam.(*NodeManager).Update.func4()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:305 +0x75
  github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:206 +0x5cf

Goroutine 57 (running) created at:
  github.com/cilium/cilium/pkg/trigger.NewTrigger()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:129 +0x2c4
  github.com/cilium/cilium/pkg/ipam.NewNodeManager()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:163 +0x356
  github.com/cilium/cilium/pkg/azure/ipam.(*IPAMSuite).TestIpamManyNodes()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/azure/ipam/ipam_test.go:319 +0x52e
  runtime.call32()
      /home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/asm_amd64.s:540 +0x3d
  reflect.Value.Call()
      /home/travis/.gimme/versions/go1.15.2.linux.amd64/src/reflect/value.go:336 +0xd8
  gopkg.in/check%2ev1.(*suiteRunner).forkTest.func1()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:781 +0xabb
  gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:675 +0xe1

Goroutine 250 (running) created at:
  github.com/cilium/cilium/pkg/trigger.NewTrigger()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:129 +0x2c4
  github.com/cilium/cilium/pkg/ipam.(*NodeManager).Update()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:300 +0xfe5
  github.com/cilium/cilium/pkg/azure/ipam.(*IPAMSuite).TestIpamManyNodes()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/azure/ipam/ipam_test.go:345 +0xbcd
  runtime.call32()
      /home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/asm_amd64.s:540 +0x3d
  reflect.Value.Call()
      /home/travis/.gimme/versions/go1.15.2.linux.amd64/src/reflect/value.go:336 +0xd8
  gopkg.in/check%2ev1.(*suiteRunner).forkTest.func1()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:781 +0xabb
  gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:675 +0xe1
```

### PR DESCRIPTION
**Pull request by tklauser**
Fixes the following data race:

```
WARNING: DATA RACE
Write at 0x00c000358270 by goroutine 57:
  github.com/cilium/cilium/pkg/azure/ipam.(*InstancesManager).Resync()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/azure/ipam/instances.go:98 +0x933
  github.com/cilium/cilium/pkg/ipam.(*NodeManager).instancesAPIResync()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:186 +0x8b
  github.com/cilium/cilium/pkg/ipam.NewNodeManager.func1()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:168 +0x8f
  github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:206 +0x5cf

Previous read at 0x00c000358270 by goroutine 250:
  github.com/cilium/cilium/pkg/azure/ipam.(*Node).PopulateStatusFields()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/azure/ipam/node.go:51 +0x11a
  github.com/cilium/cilium/pkg/ipam.(*Node).syncToAPIServer()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/ipam/node.go:716 +0x232
  github.com/cilium/cilium/pkg/ipam.(*NodeManager).Update.func4()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:305 +0x75
  github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:206 +0x5cf

Goroutine 57 (running) created at:
  github.com/cilium/cilium/pkg/trigger.NewTrigger()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:129 +0x2c4
  github.com/cilium/cilium/pkg/ipam.NewNodeManager()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:163 +0x356
  github.com/cilium/cilium/pkg/azure/ipam.(*IPAMSuite).TestIpamManyNodes()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/azure/ipam/ipam_test.go:319 +0x52e
  runtime.call32()
      /home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/asm_amd64.s:540 +0x3d
  reflect.Value.Call()
      /home/travis/.gimme/versions/go1.15.2.linux.amd64/src/reflect/value.go:336 +0xd8
  gopkg.in/check%2ev1.(*suiteRunner).forkTest.func1()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:781 +0xabb
  gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:675 +0xe1

Goroutine 250 (running) created at:
  github.com/cilium/cilium/pkg/trigger.NewTrigger()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/trigger/trigger.go:129 +0x2c4
  github.com/cilium/cilium/pkg/ipam.(*NodeManager).Update()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:300 +0xfe5
  github.com/cilium/cilium/pkg/azure/ipam.(*IPAMSuite).TestIpamManyNodes()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/azure/ipam/ipam_test.go:345 +0xbcd
  runtime.call32()
      /home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/asm_amd64.s:540 +0x3d
  reflect.Value.Call()
      /home/travis/.gimme/versions/go1.15.2.linux.amd64/src/reflect/value.go:336 +0xd8
  gopkg.in/check%2ev1.(*suiteRunner).forkTest.func1()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:781 +0xabb
  gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:675 +0xe1
```

Closes #13580

Fixes: b89979a697be ("ipam: Move instance ID retrieval into generic code")

### CODE REVIEW

File: pkg/azure/ipam/node.go [hunk 1]
```diff
@@ -48,6 +48,9 @@ func (n *Node) UpdatedNode(obj *v2.CiliumNode) {
 // resource with Azure specific information
 func (n *Node) PopulateStatusFields(k8sObj *v2.CiliumNode) {
 	k8sObj.Status.Azure.Interfaces = []types.AzureInterface{}
+
+	n.manager.mutex.Lock()
```
Comment (tklauser) [inline pkg/azure/ipam/node.go]: This should be an `RLock()`, but then we get another data race:

```
==================
WARNING: DATA RACE
Read at 0x00c00042ee38 by goroutine 62:
  github.com/cilium/cilium/pkg/azure/types.(*AzureInterface).GetVMScaleSetName()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/azure/types/types.go:178 +0xd2
  github.com/cilium/cilium/pkg/azure/ipam.(*Node).AllocateIPs()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/azure/ipam/node.go:146 +0x9c
  github.com/cilium/cilium/pkg/ipam.(*Node).maintainIPPool()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/ipam/node.go:620 +0xa1a
  github.com/cilium/cilium/pkg/ipam.(*Node).MaintainIPPool()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/ipam/node.go:678 +0xd0
  github.com/cilium/cilium/pkg/ipam.(*NodeManager).Update.func2()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:279 +0xab
  github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/trigger/trigger.go:206 +0x4fa

Previous write at 0x00c00042ee38 by goroutine 49:
  github.com/cilium/cilium/pkg/azure/types.(*AzureInterface).extractIDs()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/azure/types/types.go:153 +0x1f1
  github.com/cilium/cilium/pkg/azure/types.(*AzureInterface).GetVMID()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/azure/types/types.go:187 +0x6ad
  github.com/cilium/cilium/pkg/azure/api/mock.(*API).AssignPrivateIpAddressesVMSS.func1()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/azure/api/mock/mock.go:203 +0xcb
  github.com/cilium/cilium/pkg/ipam/types.foreachInterface()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/ipam/types/types.go:364 +0x1b1
  github.com/cilium/cilium/pkg/ipam/types.(*InstanceMap).ForeachInterface()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/ipam/types/types.go:391 +0x2fb
  github.com/cilium/cilium/pkg/azure/api/mock.(*API).AssignPrivateIpAddressesVMSS()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/azure/api/mock/mock.go:197 +0x267
  github.com/cilium/cilium/pkg/azure/ipam.(*Node).AllocateIPs()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/azure/ipam/node.go:149 +0x371
  github.com/cilium/cilium/pkg/ipam.(*Node).maintainIPPool()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/ipam/node.go:620 +0xa1a
  github.com/cilium/cilium/pkg/ipam.(*Node).MaintainIPPool()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/ipam/node.go:678 +0xd0
  github.com/cilium/cilium/pkg/ipam.(*NodeManager).Update.func2()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:279 +0xab
  github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/trigger/trigger.go:206 +0x4fa

Goroutine 62 (running) created at:
  github.com/cilium/cilium/pkg/trigger.NewTrigger()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/trigger/trigger.go:129 +0x264
  github.com/cilium/cilium/pkg/ipam.(*NodeManager).Update()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:274 +0x645
  github.com/cilium/cilium/pkg/azure/ipam.(*IPAMSuite).TestIpamManyNodes()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/azure/ipam/ipam_test.go:345 +0xd45
  runtime.call32()
      /usr/local/go/src/runtime/asm_amd64.s:540 +0x3d
  reflect.Value.Call()
      /usr/local/go/src/reflect/value.go:336 +0xd8
  gopkg.in/check%2ev1.(*suiteRunner).forkTest.func1()
      /home/tklauser/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:781 +0xabb
  gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1()
      /home/tklauser/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:675 +0xe1

Goroutine 49 (running) created at:
  github.com/cilium/cilium/pkg/trigger.NewTrigger()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/trigger/trigger.go:129 +0x264
  github.com/cilium/cilium/pkg/ipam.(*NodeManager).Update()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:274 +0x645
  github.com/cilium/cilium/pkg/azure/ipam.(*IPAMSuite).TestIpamManyNodes()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/azure/ipam/ipam_test.go:345 +0xd45
  runtime.call32()
      /usr/local/go/src/runtime/asm_amd64.s:540 +0x3d
  reflect.Value.Call()
      /usr/local/go/src/reflect/value.go:336 +0xd8
  gopkg.in/check%2ev1.(*suiteRunner).forkTest.func1()
      /home/tklauser/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:781 +0xabb
  gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1()
      /home/tklauser/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:675 +0xe1
==================
==================
WARNING: DATA RACE
Read at 0x00c00042ee48 by goroutine 62:
  github.com/cilium/cilium/pkg/azure/types.(*AzureInterface).GetVMID()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/azure/types/types.go:186 +0x147
  github.com/cilium/cilium/pkg/azure/ipam.(*Node).AllocateIPs()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/azure/ipam/node.go:149 +0x1cc
  github.com/cilium/cilium/pkg/ipam.(*Node).maintainIPPool()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/ipam/node.go:620 +0xa1a
  github.com/cilium/cilium/pkg/ipam.(*Node).MaintainIPPool()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/ipam/node.go:678 +0xd0
  github.com/cilium/cilium/pkg/ipam.(*NodeManager).Update.func2()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:279 +0xab
  github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/trigger/trigger.go:206 +0x4fa

Previous write at 0x00c00042ee48 by goroutine 49:
  github.com/cilium/cilium/pkg/azure/types.(*AzureInterface).extractIDs()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/azure/types/types.go:156 +0x168
  github.com/cilium/cilium/pkg/azure/types.(*AzureInterface).GetVMID()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/azure/types/types.go:187 +0x6ad
  github.com/cilium/cilium/pkg/azure/api/mock.(*API).AssignPrivateIpAddressesVMSS.func1()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/azure/api/mock/mock.go:203 +0xcb
  github.com/cilium/cilium/pkg/ipam/types.foreachInterface()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/ipam/types/types.go:364 +0x1b1
  github.com/cilium/cilium/pkg/ipam/types.(*InstanceMap).ForeachInterface()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/ipam/types/types.go:391 +0x2fb
  github.com/cilium/cilium/pkg/azure/api/mock.(*API).AssignPrivateIpAddressesVMSS()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/azure/api/mock/mock.go:197 +0x267
  github.com/cilium/cilium/pkg/azure/ipam.(*Node).AllocateIPs()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/azure/ipam/node.go:149 +0x371
  github.com/cilium/cilium/pkg/ipam.(*Node).maintainIPPool()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/ipam/node.go:620 +0xa1a
  github.com/cilium/cilium/pkg/ipam.(*Node).MaintainIPPool()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/ipam/node.go:678 +0xd0
  github.com/cilium/cilium/pkg/ipam.(*NodeManager).Update.func2()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:279 +0xab
  github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/trigger/trigger.go:206 +0x4fa

Goroutine 62 (running) created at:
  github.com/cilium/cilium/pkg/trigger.NewTrigger()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/trigger/trigger.go:129 +0x264
  github.com/cilium/cilium/pkg/ipam.(*NodeManager).Update()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:274 +0x645
  github.com/cilium/cilium/pkg/azure/ipam.(*IPAMSuite).TestIpamManyNodes()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/azure/ipam/ipam_test.go:345 +0xd45
  runtime.call32()
      /usr/local/go/src/runtime/asm_amd64.s:540 +0x3d
  reflect.Value.Call()
      /usr/local/go/src/reflect/value.go:336 +0xd8
  gopkg.in/check%2ev1.(*suiteRunner).forkTest.func1()
      /home/tklauser/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:781 +0xabb
  gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1()
      /home/tklauser/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:675 +0xe1

Goroutine 49 (running) created at:
  github.com/cilium/cilium/pkg/trigger.NewTrigger()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/trigger/trigger.go:129 +0x264
  github.com/cilium/cilium/pkg/ipam.(*NodeManager).Update()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/ipam/node_manager.go:274 +0x645
  github.com/cilium/cilium/pkg/azure/ipam.(*IPAMSuite).TestIpamManyNodes()
      /home/tklauser/go/src/github.com/cilium/cilium/pkg/azure/ipam/ipam_test.go:345 +0xd45
  runtime.call32()
      /usr/local/go/src/runtime/asm_amd64.s:540 +0x3d
  reflect.Value.Call()
      /usr/local/go/src/reflect/value.go:336 +0xd8
  gopkg.in/check%2ev1.(*suiteRunner).forkTest.func1()
      /home/tklauser/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:781 +0xabb
  gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1()
      /home/tklauser/go/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:675 +0xe1
==================
```

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

File: pkg/azure/ipam/node.go [hunk 2]
```diff
@@ -48,6 +48,9 @@ func (n *Node) UpdatedNode(obj *v2.CiliumNode) {
 // resource with Azure specific information
 func (n *Node) PopulateStatusFields(k8sObj *v2.CiliumNode) {
 	k8sObj.Status.Azure.Interfaces = []types.AzureInterface{}
+
+	n.manager.mutex.RLock()
+	defer n.manager.mutex.RUnlock()
```
Comment (christarazi) [inline pkg/azure/ipam/node.go:53]: I think I attempted a fix like this before, and the deadlock detector ended up flagging this as "inconsistent locking" with another lock inside `ForeachInterface`. Maybe you don't run into it this time and it was another piece of code that looks very similar?

**Review by christarazi — APPROVED** [review]
LGTM. Just a heads up about a similar code change that I've attempted previously.

File: pkg/azure/ipam/node.go (hunk 2 above)
Comment (tklauser) [reply pkg/azure/ipam/node.go:53]: Thanks for the heads-up. I didn‘t see any such message in my local testing but will keep an eye on the CI tests.
