### PR TITLE
LRP: Fix node-local redirection exceptions

### LINKED ISSUE #15195: Cilium LRP failed to NAT when client side listen same port as endpoint
## Bug report

- Cilium version 
   -  Client: 1.9.4 07b62884c 2021-02-03T11:45:44-08:00 go version go1.15.7 linux/amd64
   -  Daemon: 1.9.4 07b62884c 2021-02-03T11:45:44-08:00 go version go1.15.7 linux/amd64
- Kernel version 5.4.0-65-generic

**How to reproduce the issue**

LRP works well when client  side not listen 80 port.

image

1.   deploy with yaml  https://gist.github.com/l1b0k/a1936da7e80c1f53c6fa966bf89c4a04
2.  client curl ,test LRP work well

```s
root@ins3:~# nsenter -t 1077188 -n bash
root@ins3:~# curl 10.100.200.200:8080
GET /
Host: 10.100.200.200:8080
ins3 server-mxgkg/default
Counter: 1
Accept: */*
User-Agent: curl/7.68.0
```

3. start a listen in client pod

```s
root@ins3:~# nc -lp 80
```

4. curl again

```s
root@ins3:~# curl 10.100.200.200:8080
^C
```

6. previous trace , i can see no DNAT is done and package is route out the vm

```s
time       NETWORK_NS   INTERFACE    DEST_MAC     PKT_INFO                                 TRACE_INFO
[15:54:26 ][4026532778] b'nil'       000000000000 T_SYN:10.0.2.126:35112->10.100.200.200:8080 ffff899c60df58e0.0:b'ip_output'
[15:54:26 ][4026532778] b'eth0'      000000000000 T_SYN:10.0.2.126:35112->10.100.200.200:8080 ffff899c60df58e0.0:b'ip_finish_output'
[15:54:26 ][4026532778] b'eth0'      000000000000 T_SYN:10.0.2.126:35112->10.100.200.200:8080 ffff899c60df58e0.0:b'__dev_queue_xmit'
[15:54:26 ][4026531992] b'lxc3410fd74de30' e23a36f7c133 T_SYN:10.0.2.126:35112->10.100.200.200:8080 ffff899c60df58e0.0:b'netif_rx'
[15:54:26 ][4026531992] b'lxc3410fd74de30' e23a36f7c133 T_SYN:10.0.2.126:35112->10.100.200.200:8080 ffff899c60df58e0.0:b'__netif_receive_skb'
[15:54:26 ][4026531992] b'lxc3410fd74de30' e23a36f7c133 T_SYN:10.0.2.126:35112->10.100.200.200:8080 ffff899c60df58e0.0:b'ip_rcv'
[15:54:26 ][4026531992] b'lxc3410fd74de30' e23a36f7c133 T_SYN:10.0.2.126:35112->10.100.200.200:8080 ffff899c60df58e0.0:b'ip_rcv_finish'
[15:54:26 ][4026531992] b'lxc3410fd74de30' e23a36f7c133 T_SYN:10.0.2.126:35112->10.100.200.200:8080 ffff899c60df58e0.0:b'ip_output'
[15:54:26 ][4026531992] b'eth0'      e23a36f7c133 T_SYN:10.0.2.126:35112->10.100.200.200:8080 ffff899c60df58e0.0:b'ip_finish_output'
[15:54:26 ][4026531992] b'eth0'      eeffffffffff T_SYN:10.0.2.126:35112->10.100.200.200:8080 ffff899c60df58e0.0:b'__dev_queue_xmit'
[15:54:27 ][4026532778] b'nil'       000000000000 T_SYN:10.0.2.126:35112->10.100.200.200:8080 ffff899c60df58e0.0:b'ip_output'
[15:54:27 ][4026532778] b'eth0'      000000000000 T_SYN:10.0.2.126:35112->10.100.200.200:8080 ffff899c60df58e0.0:b'ip_finish_output'
[15:54:27 ][4026532778] b'eth0'      000000000000 T_SYN:10.0.2.126:35112->10.100.200.200:8080 ffff899c60df58e0.0:b'__dev_queue_xmit'
```

@aditighag pls take a look

### LINKED ISSUE #20164: Node-Local dns with LocalRedirectPolicy not working on pods listening on port 53
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi, I'm just started running into an issue with node-local-dns and cilium local redirect policy. Everything was working fine previously on 20.04.

My previous nodes running
```
Linux n101 5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
worked just fine, however my new nodes are running ubuntu 22.04 with kernel
```
Linux n001 5.15.0-35-generic #36-Ubuntu SMP Sat May 21 02:24:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
does not seem to work properly for some pods, and does for others

I'm thinking it might be a kernel issue, because previously I was also using the same cilium version (1.11.4, then I tried again with cilium 1.11.5)
Currently i'm on:
kubernetes 1.24.1
cilium 1.11.5
ubuntu 22.04 up to date

### Cilium Version

```
Client: 1.11.5 b0d3140 2022-05-10T02:47:42+02:00 go version go1.17.9 linux/amd64
Daemon: 1.11.5 b0d3140 2022-05-10T02:47:42+02:00 go version go1.17.9 linux/amd64
```

### Kernel Version

```
Linux n002 5.15.0-35-generic #36-Ubuntu SMP Sat May 21 02:24:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:18:48Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
```

### Sysdump

[cilium-sysdump-20220616-083851.zip](https://github.com/cilium/cilium/files/8918870/cilium-sysdump-20220616-083851.zip)

### Relevant log output

```shell
#### WITH POLICY DISABLED

root@dnstest:/root# dig @10.3.0.10 web.site.svc.cluster.local

; <<>> DiG 9.16.27-Debian <<>> @10.3.0.10 web.site.svc.cluster.local
; (1 server found)
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52788
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: fe7eba1c9b7d2ba8 (echoed)
;; QUESTION SECTION:
;web.site.svc.cluster.local. IN A

;; ANSWER SECTION:
web.site.svc.cluster.local. 25 IN A 10.3.249.244

;; Query time: 0 msec
;; SERVER: 10.3.0.10#53(10.3.0.10)
;; WHEN: Tue Jun 07 02:12:13 UTC 2022
;; MSG SIZE  rcvd: 151
```

#### WITH POLICY ENABLED
```
root@dnstest:/root# dig @10.3.0.10 web.site.svc.cluster.local

; <<>> DiG 9.16.27-Debian <<>> @10.3.0.10 web.site.svc.cluster.local
; (1 server found)
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 2353
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: f3135a06af572481 (echoed)
;; QUESTION SECTION:
;web.site.svc.cluster.local. IN A

;; Query time: 999 msec
;; SERVER: 10.3.0.10#53(10.3.0.10)
;; WHEN: Tue Jun 07 02:13:08 UTC 2022
;; MSG SIZE  rcvd: 88
```
#### to node-local-dns pod in the same host
```
root@dnstest:/root# dig @10.2.3.72 web.site.svc.cluster.local

; <<>> DiG 9.16.27-Debian <<>> @10.2.3.72 web.site.svc.cluster.local
; (1 server found)
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64896
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: e6244d4c09352f06 (echoed)
;; QUESTION SECTION:
;web.site.svc.cluster.local. IN A

;; ANSWER SECTION:
web.site.svc.cluster.local. 6 IN A 10.3.249.244

;; Query time: 3 msec
;; SERVER: 10.2.3.72#53(10.2.3.72)
;; WHEN: Tue Jun 07 02:14:02 UTC 2022
;; MSG SIZE  rcvd: 151
```

tcpdump policy off, here it goes straight to the coredns pods in kube-dns correctly
```
02:47:44.076470 lxc700b5d19881b In  IP 10.2.3.143.53337 > 10.2.0.42.53: Flags [S], seq 2601814125, win 65535, options [mss 1460,sackOK,TS val 3298041818 ecr 0,nop,wscale 9], length 0
02:47:44.076536 eth0  Out IP 10.2.3.143.53337 > 10.2.0.42.53: Flags [S], seq 2601814125, win 65535, options [mss 1460,sackOK,TS val 3298041818 ecr 0,nop,wscale 9], length 0
02:47:44.076666 eth0  In  IP 10.2.0.42.53 > 10.2.3.143.53337: Flags [S.], seq 2145065476, ack 2601814126, win 65535, options [mss 1460,sackOK,TS val 833701055 ecr 3298041818,nop,wscale 9], length 0
02:47:44.076703 lxc700b5d19881b Out IP 10.2.0.42.53 > 10.2.3.143.53337: Flags [S.], seq 2145065476, ack 2601814126, win 65535, options [mss 1460,sackOK,TS val 833701055 ecr 3298041818,nop,wscale 9], length 0
02:47:44.076728 lxc700b5d19881b In  IP 10.2.3.143.53337 > 10.2.0.42.53: Flags [.], ack 1, win 128, options [nop,nop,TS val 3298041818 ecr 833701055], length 0
02:47:44.076747 eth0  Out IP 10.2.3.143.53337 > 10.2.0.42.53: Flags [.], ack 1, win 128, options [nop,nop,TS val 3298041818 ecr 833701055], length 0
02:47:44.076825 lxc700b5d19881b In  IP 10.2.3.143.53337 > 10.2.0.42.53: Flags [P.], seq 1:91, ack 1, win 128, options [nop,nop,TS val 3298041819 ecr 833701055], length 90 64571+ [1au] A? web.site.svc.cluster.local. (88)
02:47:44.076847 eth0  Out IP 10.2.3.143.53337 > 10.2.0.42.53: Flags [P.], seq 1:91, ack 1, win 128, options [nop,nop,TS val 3298041819 ecr 833701055], length 90 64571+ [1au] A? web.site.svc.cluster.local. (88)
02:47:44.076914 eth0  In  IP 10.2.0.42.53 > 10.2.3.143.53337: Flags [.], ack 91, win 128, options [nop,nop,TS val 833701055 ecr 3298041819], length 0
02:47:44.076928 lxc700b5d19881b Out IP 10.2.0.42.53 > 10.2.3.143.53337: Flags [.], ack 91, win 128, options [nop,nop,TS val 833701055 ecr 3298041819], length 0
02:47:44.077554 eth0  In  IP 10.2.0.42.53 > 10.2.3.143.53337: Flags [P.], seq 1:154, ack 91, win 128, options [nop,nop,TS val 833701056 ecr 3298041819], length 153 64571*- 1/0/1 A 10.3.249.244 (151)
02:47:44.077590 lxc700b5d19881b Out IP 10.2.0.42.53 > 10.2.3.143.53337: Flags [P.], seq 1:154, ack 91, win 128, options [nop,nop,TS val 833701056 ecr 3298041819], length 153 64571*- 1/0/1 A 10.3.249.244 (151)
02:47:44.077598 lxc700b5d19881b In  IP 10.2.3.143.53337 > 10.2.0.42.53: Flags [.], ack 154, win 131, options [nop,nop,TS val 3298041819 ecr 833701056], length 0
02:47:44.077617 eth0  Out IP 10.2.3.143.53337 > 10.2.0.42.53: Flags [.], ack 154, win 131, options [nop,nop,TS val 3298041819 ecr 833701056], length 0
02:47:44.078027 lxc700b5d19881b In  IP 10.2.3.143.53337 > 10.2.0.42.53: Flags [F.], seq 91, ack 154, win 131, options [nop,nop,TS val 3298041820 ecr 833701056], length 0
02:47:44.078061 eth0  Out IP 10.2.3.143.53337 > 10.2.0.42.53: Flags [F.], seq 91, ack 154, win 131, options [nop,nop,TS val 3298041820 ecr 833701056], length 0
02:47:44.078632 eth0  In  IP 10.2.0.42.53 > 10.2.3.143.53337: Flags [F.], seq 154, ack 92, win 128, options [nop,nop,TS val 833701057 ecr 3298041820], length 0
02:47:44.078713 lxc700b5d19881b Out IP 10.2.0.42.53 > 10.2.3.143.53337: Flags [F.], seq 154, ack 92, win 128, options [nop,nop,TS val 833701057 ecr 3298041820], length 0
02:47:44.078728 lxc700b5d19881b In  IP 10.2.3.143.53337 > 10.2.0.42.53: Flags [.], ack 155, win 131, options [nop,nop,TS val 3298041820 ecr 833701057], length 0
02:47:44.078758 eth0  Out IP 10.2.3.143.53337 > 10.2.0.42.53: Flags [.], ack 155, win 131, options [nop,nop,TS val 3298041820 ecr 833701057], length 0
```

tcpdump policy on, as noted it still tries to go to `10.3.0.10` instead of `10.2.3.72`
```
02:45:11.932993 lxc700b5d19881b In  IP 10.2.3.143.44363 > 10.3.0.10.53: Flags [S], seq 1070528412, win 65535, options [mss 1460,sackOK,TS val 2627356549 ecr 0,nop,wscale 9], length 0
02:45:11.935114 lxc700b5d19881b In  IP 10.2.3.143.42160 > 10.3.0.10.53: 2512+ NS? . (17)
02:45:12.949409 lxc700b5d19881b In  IP 10.2.3.143.44363 > 10.3.0.10.53: Flags [S], seq 1070528412, win 65535, options [mss 1460,sackOK,TS val 2627357565 ecr 0,nop,wscale 9], length 0
02:45:13.437332 lxc700b5d19881b In  IP 10.2.3.143.44013 > 10.3.0.10.53: 48493+ NS? . (17)
02:45:14.938081 lxc700b5d19881b In  IP 10.2.3.143.40206 > 10.3.0.10.53: 30742+ NS? . (17)
02:45:14.965460 lxc700b5d19881b In  IP 10.2.3.143.44363 > 10.3.0.10.53: Flags [S], seq 1070528412, win 65535, options [mss 1460,sackOK,TS val 2627359581 ecr 0,nop,wscale 9], length 0
02:45:16.438784 lxc700b5d19881b In  IP 10.2.3.143.45143 > 10.3.0.10.53: 31560+ NS? . (17)
02:45:17.939217 lxc700b5d19881b In  IP 10.2.3.143.55114 > 10.3.0.10.53: 53360+ NS? . (17)
02:45:19.125544 lxc700b5d19881b In  IP 10.2.3.143.44363 > 10.3.0.10.53: Flags [S], seq 1070528412, win 65535, options [mss 1460,sackOK,TS val 2627363741 ecr 0,nop,wscale 9], length 0
02:45:19.440629 lxc700b5d19881b In  IP 10.2.3.143.40681 > 10.3.0.10.53: 13073+ NS? . (17)
02:45:20.941308 lxc700b5d19881b In  IP 10.2.3.143.57037 > 10.3.0.10.53: 13942+ NS? . (17)
02:45:21.926173 lxc700b5d19881b In  IP 10.2.3.143.57207 > 10.3.0.10.53: Flags [S], seq 1423905828, win 65535, options [mss 1460,sackOK,TS val 2627366542 ecr 0,nop,wscale 9], length 0
02:45:22.443111 lxc700b5d19881b In  IP 10.2.3.143.40074 > 10.3.0.10.53: 29603+ NS? . (17)
02:45:22.933385 lxc700b5d19881b In  IP 10.2.3.143.57207 > 10.3.0.10.53: Flags [S], seq 1423905828, win 65535, options [mss 1460,sackOK,TS val 2627367549 ecr 0,nop,wscale 9], length 0
02:45:23.945404 lxc700b5d19881b In  IP 10.2.3.143.42131 > 10.3.0.10.53: 2748+ NS? . (17)
```

### Anything else?

I have already tried the sysctl fix + reboot mentioned in https://github.com/cilium/cilium/issues/19909.
```
net.ipv4.conf.cilium_host.rp_filter=0
net.ipv4.conf.cilium_net.rp_filter=0
net.ipv4.conf.lo.rp_filter=0
net.ipv4.conf.lxc*.rp_filter=0
```

Slack thread https://cilium.slack.com/archives/C53TG4J4R/p1654571691219659

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by aditighag**
This PR fixes cases with the local redirect policy datapath behavior with socket-LB where node-local redirection was being erroneously skipped.

### Summary

Extend the local redirect policy spec with a new flag called `skipRedirectFromBackend` that allow users to skip redirection of traffic from an LRP backend to itself via the LRP frontend for certain use cases. This replaces the previous default logic in the BPF socket-LB datapath involving local redirect services LB that led to unintended error cases. 
LRPs with the new flag are processed by the LRP manager, and translated into entries populated in newly introduced maps that enable socket-LB datapath to skip local redirect service translation from certain pods. 

### Highlights of PR commits

(Check commits description for more details.)

- [CRD] Extend LRP CRD spec with the new flag.
- [Plugin, openapi, pkg/endpoint] Preparatory commits to get endpoint netns cookies metadata.
- [pkg/maps] Define new BPF maps to store the translated LRP state with the new flag.
- [pkg/redirectpolicy] Update the LRP manager to process and plumb such user configured policies.
- [BPF] Revise BPF datapath to implement the desired LRP behavior for certain traffic 
- [BPF] Unit tests
- [Doc] Document the flag along with requirements.
Tested manually on a local cluster. An e2e test will be added in the cilium-cli connectivity suite as a follow-up once this dependency PR is merged.

Example LRP with the extended spec - 

lrp-skip-lb (1)

Fixes: https://github.com/cilium/cilium/issues/15195
Fixes: https://github.com/cilium/cilium/issues/20164

```release-note
Fix LRP error cases where node-local redirection was erroneously skipped. Extend LRP spec in order for users to explicitly skip node-local redirection from LRP selected backend pods.
```

### CODE REVIEW

**Comment by aditighag** [comment]
/test-1.26-net-next

**Comment by joestringer** [comment]
@aditighag I've dropped release-blocker from this PR, it seems significant enough that it needs thorough review, and a compressed timeline will not help to get that. Feature freeze was last friday, and even if we consider that maybe this is fixing a known limitation, it does not look like it's tracking to land in time for v1.14 branching next week. If we really think that this is worthwhile backporting to v1.14 at a later time, we can first get it into a form that we're happy with, merge into main, and then make the call whether a backport makes sense or not. Either way we can get this into an upcoming v1.15 monthly snapshot release.

File: plugins/cilium-cni/cmd/cmd.go [hunk 1]
```diff
@@ -618,6 +620,20 @@ func (cmd *Cmd) Add(args *skel.CmdArgs) (err error) {
...
+		var cookie uint64
+		if getNetnsCookie {
+			if err = ns.Do(func() error {
+				cookie, err = netns.GetNetNSCookie()
+				return err
+			}); err != nil {
+				if errors.Is(err, unix.ENOPROTOOPT) {
+					getNetnsCookie = false
+				}
+				log.WithError(err).Infof("unable to get netns cookie %s", args.ContainerID)
```
Comment (tommyp1ckles) [inline plugins/cilium-cni/cmd/cmd.go]: can we use the keyed WithField for the `ContainerID` value?

File: pkg/endpoint/api.go [hunk 2]
```diff
@@ -94,6 +95,18 @@ func NewEndpointFromChangeModel(ctx context.Context, owner regeneration.Owner, p
 		ep.nodeMAC = m
 	}
 
+	if base.NetnsCookie != "" {
+		cookie64, err := strconv.ParseInt(base.NetnsCookie, 10, 64)
+		if err != nil {
+			// Don't return on error (and block the endpoint creation) as this
+			// is an unusual case where data could have been malformed. Defer error
+			// logging to individual features depending on the metadata.
+			log.Errorf("unable to parse netns cookie [%s] for ep [%d]: %v", base.NetnsCookie, base.ID, err)
```
Comment (tommyp1ckles) [inline pkg/endpoint/api.go]: In general, I think it's better to use the WithFields() function on the logger to emit these to produce more structured and consistent logs.

File: pkg/endpoint/restore_test.go [hunk 3]
```diff
@@ -72,6 +72,8 @@ func (ds *EndpointSuite) endpointCreator(id uint16, secID identity.NumericIdenti
 	ep.nodeMAC = []byte{0x02, 0xff, 0xf2, 0x12, 0x0, 0x0}
 	ep.SecurityIdentity = identity
 	ep.OpLabels = labels.NewOpLabels()
+	// TODO (aditi-lrp
```
Comment (tommyp1ckles) [inline pkg/endpoint/restore_test.go]: Is this TODO still relevant?

Comment (dylandreimerink) [inline pkg/endpoint/restore_test.go]: nit: seems like a leftover comment?

File: bpf/bpf_sock.c [hunk 4]
```diff
@@ -256,31 +266,26 @@ sock4_wildcard_lookup_full(struct lb4_key *key __maybe_unused,
...
+#ifdef HAVE_NETNS_COOKIE
+	__net_cookie cookie = get_netns_cookie(ctx);
+	struct skip_lb4_key key;
+	__u8 *val = NULL;
+
+	memset(&key, 0, sizeof(key));
+	key.netns_cookie = cookie;
+	key.address = address;
+	key.port = port;
+	printk("bpf_sock-trace: netns %llu %u\n", key.netns_cookie, key.address);
```
Comment (dylandreimerink) [inline bpf/bpf_sock.c]: I assume this is leftover from debugging?

File: bpf/bpf_sock.c [hunk 5]
```diff
@@ -677,6 +690,35 @@ static __always_inline int sock6_update_revnat(struct bpf_sock_addr *ctx,
...
+#ifdef HAVE_NETNS_COOKIE
+	__net_cookie cookie = get_netns_cookie(ctx);
+	struct skip_lb6_key key;
+	__u8 *val = NULL;
+
+	memset(&key, 0, sizeof(key));
+	key.netns_cookie = cookie;
+	ctx_get_v6_address(ctx, &key.address);
+	key.port = port;
+	printk("bpf_sock-trace-v6: netns %llu\n", key.netns_cookie);
```
Comment (dylandreimerink) [inline bpf/bpf_sock.c]: Same here, leftover printk

**Review by dylandreimerink — APPROVED** [review]
Looks good overall. A few small things, nothing to block on, approving

File: bpf/node_config.h [hunk 6]
```diff
@@ -191,7 +191,7 @@ DEFINE_IPV6(HOST_IP, 0xbe, 0xef, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0xa, 0x
 #define CILIUM_LB_AFFINITY_MAP_MAX_ENTRIES	65536
 #define CILIUM_LB_REV_NAT_MAP_MAX_ENTRIES	65536
 #define CILIUM_LB_MAGLEV_MAP_MAX_ENTRIES	65536
-#define CILIUM_LB_SKIP_MAP_MAX_ENTRIES		65536
+#define CILIUM_LB_SKIP_MAP_MAX_ENTRIES		100
```
Comment (tommyp1ckles) [inline bpf/node_config.h:194]: One of the previous commits sets this to 64k then this is set to 100. Was this intentional?

File: bpf/bpf_sock.c [hunk 7]
```diff
@@ -256,31 +266,26 @@ sock4_wildcard_lookup_full(struct lb4_key *key __maybe_unused,
...
+	__net_cookie cookie = get_netns_cookie(ctx);
+	struct skip_lb4_key key;
+	__u8 *val = NULL;
+
+	memset(&key, 0, sizeof(key));
+	key.netns_cookie = cookie;
+	key.address = address;
+	key.port = port;
+	printk("bpf_sock-trace: netns %llu %u\n", key.netns_cookie, key.address);
+	val = map_lookup_elem(&LB4_SKIP_MAP, &key);
```
Comment (tommyp1ckles) [inline bpf/bpf_sock.c:281]: Q: Seems like we weren't doing any bpf map lookups in this code-path prior to this, is there any performance concerns here?

File: bpf/bpf_sock.c [hunk 8]
```diff
@@ -677,6 +690,35 @@ static __always_inline int sock6_update_revnat(struct bpf_sock_addr *ctx,
...
+				 const __be16 port __maybe_unused)
+{
+#ifdef HAVE_NETNS_COOKIE
+	__net_cookie cookie = get_netns_cookie(ctx);
+	struct skip_lb6_key key;
+	__u8 *val = NULL;
+
+	memset(&key, 0, sizeof(key));
+	key.netns_cookie = cookie;
+	ctx_get_v6_address(ctx, &key.address);
```
Comment (tommyp1ckles) [inline bpf/bpf_sock.c:708]: q: how come we pull the ip6 addr from the socket buffer here, whereas we use the passed ip4 address above?

File: bpf/bpf_sock.c (hunk 7 above)
Comment (aditighag) [reply bpf/bpf_sock.c:281]: The old logic was invoking `sk_lookup_` helper in the kernel, which looks up a socket in the kernel hash table. While the new logic works differently, the performance concerns are not significant as the lookup is done only once at the socket `connect` calls.

File: bpf/bpf_sock.c (hunk 8 above)
Comment (aditighag) [reply bpf/bpf_sock.c:708]: Ah! It's essentially the same address (the address is retrieved from the context and passed to this function), but the v6 address is stored in a different structure than v4. I updated the function definition as the passed `address` argument wasn't used. While we could retrieve address and port from the context again, since we already retrieve them in sock{4,6}_fwd function, I decided to just pass them to here. 
Thanks!

File: pkg/endpoint/api.go (hunk 2 above)
Comment (aditighag) [reply pkg/endpoint/api.go]: Agreed, I did use structured logging in other places. Missed some of these logs.

**Comment by aditighag** [comment]
@joamaki / @learnitall 👋 Waiting for your reviews. Trying to batch up updates so that I can rebase and resolve conflicts.

File: bpf/node_config.h (hunk 6 above)
Comment (aditighag) [reply bpf/node_config.h:194]: This is the right size as we expect smaller number of entries in the map. I'll make it consistent.

File: pkg/endpointmanager/cell.go [hunk 9]
```diff
@@ -79,6 +79,8 @@ type EndpointsLookup interface {
 
 	// IngressEndpointExists returns true if the ingress endpoint exists.
 	IngressEndpointExists() bool
+
```
Comment (learnitall) [inline pkg/endpointmanager/cell.go:82]: Nit: missing comment.

File: pkg/endpointmanager/manager.go [hunk 10]
```diff
@@ -778,3 +778,12 @@ func (mgr *endpointManager) CallbackForEndpointsAtPolicyRev(ctx context.Context,
 func (mgr *endpointManager) EndpointExists(id uint16) bool {
 	return mgr.LookupCiliumID(id) != nil
 }
+
```
Comment (learnitall) [inline pkg/endpointmanager/manager.go:798]: Nit: missing comment.

File: pkg/endpoint/identifiers.go [hunk 11]
```diff
@@ -161,3 +161,9 @@ func (e *Endpoint) SetCiliumEndpointUID(uid types.UID) {
 	e.ciliumEndpointUID = uid
 	e.unlock()
 }
+
```
Comment (learnitall) [inline pkg/endpoint/identifiers.go:164]: Nit: missing comment

File: pkg/maps/lbmap/skip_lb_map.go [hunk 12]
```diff
@@ -0,0 +1,312 @@
...
+	deleted := 0
+	errors := 0
+	deleteEntry := func(key *SkipLB4Key, _ SkipLB4Value) {
+		if key == nil {
+			return
+		}
+		if ip.To4().Equal(key.Address.IP()) && byteorder.NetworkToHost16(key.Port) == port {
+			if err := m.bpfMap4.Delete(key); err != nil {
+				errors++
+				log.Errorf("error deleting entry from skip_lb4 map %v", key)
```
Comment (learnitall) [inline pkg/maps/lbmap/skip_lb_map.go]: One long-term effort that is currently underway is replacing logrus with slog, which does not have any message formatting capabilities. To ease the transition, can we remove usages of any "f" log functions and instead log any dynamic values using `WithFields`?

File: daemon/cmd/endpoint.go [hunk 13]
```diff
@@ -825,6 +825,11 @@ func (d *Daemon) EndpointCreated(ep *endpoint.Endpoint) {
 	d.SendNotification(monitorAPI.EndpointCreateMessage(ep))
 }
 
+// EndpointRestored implements endpointmanager.Subscriber
```
Comment (learnitall) [inline daemon/cmd/endpoint.go]: Nit: missing period.

File: pkg/auth/authmap_gc.go [hunk 14]
```diff
@@ -429,6 +429,11 @@ func (r *authMapGarbageCollector) EndpointDeleted(ep *endpoint.Endpoint, conf en
 	}
 }
 
+// EndpointRestored implements endpointmanager.Subscriber
```
Comment (learnitall) [inline pkg/auth/authmap_gc.go]: Nit: missing period

File: pkg/datapath/garp/processor.go [hunk 15]
```diff
@@ -91,3 +91,8 @@ func (gp *processor) EndpointDeleted(ep *endpoint.Endpoint, conf endpoint.Delete
 
 	delete(gp.endpointIPs, ep.ID)
 }
+
+// EndpointRestored implements endpointmanager.Subscriber
```
Comment (learnitall) [inline pkg/datapath/garp/processor.go]: Nit: missing period

File: pkg/endpointmanager/cell.go [hunk 16]
```diff
@@ -170,6 +170,7 @@ type EndpointManager interface {
 	// each endpoint that reaches the desired revision calls 'done' independently.
 	// The provided callback should not block and generally be lightweight.
 	CallbackForEndpointsAtPolicyRev(ctx context.Context, rev uint64, done func(time.Time)) error
+	GetEndpointNetnsCookieByIP(ip netip.Addr) (uint64, error)
```
Comment (learnitall) [inline pkg/endpointmanager/cell.go:176]: Nit: missing comment

File: pkg/redirectpolicy/manager.go [hunk 17]
```diff
@@ -532,6 +668,43 @@ func (rpm *Manager) deleteService(svcID k8s.ServiceID) {
 	}
 }
 
+func (rpm *Manager) plumbSkipLBEntries(mapping *feMapping) error {
+	if rpm.skipLBMap == nil {
+		return fmt.Errorf("")
```
Comment (learnitall) [inline pkg/redirectpolicy/manager.go]: Is there a reason why you're using a blank error here? What's the difference between a blank error and `nil`? IMO, if the map is `nil`, then an error should be returned stating that the function was unable to continue because the map was not initialized.

File: pkg/redirectpolicy/manager.go [hunk 18]
```diff
@@ -532,6 +668,43 @@ func (rpm *Manager) deleteService(svcID k8s.ServiceID) {
...
+}
+
+func (rpm *Manager) upsertPolicyMapping(config *LRPConfig, feMapping *feMapping) {
+	if config.skipRedirectFromBackend {
+		if err := rpm.plumbSkipLBEntries(feMapping); err != nil {
+			log.WithFields(logrus.Fields{
+				logfields.LRPType:      config.lrpType,
+				logfields.K8sNamespace: config.id.Namespace,
+				logfields.LRPName:      config.id.Name,
+			}).Errorf("LRP not applied as skipRedirectFromBackend not supported: %v", err)
```
Comment (learnitall) [inline pkg/redirectpolicy/manager.go]: Nit: "not supported" implies that the Cilium configuration is invalid, but an error is returned from `plumbSkipLBEntries` for other reasons, such as failing to write to the map. Can we adjust the wording here to make it clear to users that the LRP was not applied due to an error that occurred while trying to apply it?

File: pkg/redirectpolicy/manager.go [hunk 19]
```diff
@@ -79,16 +96,30 @@ type Manager struct {
...
 }
 
-func NewRedirectPolicyManager(svc svcManager, lpr agentK8s.LocalPodResource) *Manager {
+func NewRedirectPolicyManager(svc svcManager, lpr agentK8s.LocalPodResource, epM endpointManager) *Manager {
+	skipLBMap, err := lbmap.NewSkipLBMap()
+	if err != nil {
+		log.Warnf("failed to init cilium_skip_lb maps: %v"+
+			"Check the local redirect policy documentation if you are using"+
+			"CiliumLocalRedirectPolicy where it's required to"+
+			"skip load-balancing in certain cases", err)
```
Comment (learnitall) [inline pkg/redirectpolicy/manager.go]: Would it be possible to change the signature of `NewRedirectPolicyManager` so it can return an error in this case? If we hit this block, the manager will continue with `skipRedirectFromBackend` functionality missing which may be hard to debug. We could return an error and have the caller of NewRedirectPolicyManager attempt a retry or cause the cilium-agent to restart. Users would have to restart the cilium-agent anyways to fix this kind of error, so I think having the agent fail because of this error is OK to do.

File: pkg/redirectpolicy/manager_test.go [hunk 20]
```diff
@@ -566,3 +644,144 @@ func (m *ManagerSuite) TestManager_OnAddandUpdatePod(c *C) {
...
+	}
+	m.rpm = NewRedirectPolicyManager(m.svc, fps, m.epM)
+	lbEvents = make(chan skipLBParams)
+	m.rpm.skipLBMap = &fakeSkipLBMap{lb4Events: lbEvents}
+
+	//// Pod selected by the policy added.
+	//m.rpm.OnAddPod(pod)
+	//
+	// Endpoint event for the policy selected pod created.
+	//m.rpm.EndpointCreated(ep)
```
Comment (learnitall) [inline pkg/redirectpolicy/manager_test.go]: Are these leftover comments?

File: Documentation/network/kubernetes/local-redirect-policy.rst [hunk 21]
```diff
@@ -480,11 +480,17 @@ security credentials for pods.
...
+However, for traffic originating from a node-local backend pod destined to the policy frontend, users may want to
+skip redirecting the traffic back to the node-local backend pod, and instead forward the traffic to the original frontend.
+This behavior can be enabled by setting the ``skipRedirectFromBackend`` flag to ``true`` in the local redirect policy spec.
+The configuration is only supported with socket-based load-balancing, and requires ``SO_NETNS_COOKIE`` feature
+available in Linux kernel version >= 5.8.
+
+.. note::
+
+    In order to enable this configuration starting Cilium version 1.16.0, previously applied local redirect policies
+    and policies selected backend pods need to be re-created.
```
Comment (learnitall) [inline Documentation/network/kubernetes/local-redirect-policy.rst]: Just to clarify, when you say "re-created" here, do you mean that the policy must be explicitly deleted and then created again? This wording used here could cause folks to believe that they could just `kubectl apply` their policies again and call it a day.

File: Documentation/operations/upgrade.rst [hunk 22]
```diff
@@ -309,7 +309,10 @@ Annotations:
 * Cilium Envoy DaemonSet is now enabled by default, and existing in-container installs
   will be changed to DaemonSet mode unless specifically opted out of. This can be done by
   disabling it manually by setting ``envoy.enabled=false`` accordingly.
-
+* Local Redirect Policy when enabled with socket-based load-balancing allows traffic going
+  from policy selected node-local backends destined to the policy frontend, and redirected back
+  to the backends, by default. In order to skip redirection from backends, create policies
+  with the ``skipRedirectFromBackend`` flag set to ``false``.
```
Comment (learnitall) [inline Documentation/operations/upgrade.rst]: Wording suggestion for clarity:

```suggestion
* Local Redirect Policy, when enabled with socket-based load-balancing, redirects traffic
  from policy-selected node-local backends destined to the policy's frontend, back to the
  backends listed in the policy. To override this behavior, which is enabled by default, create
  local redirect policies with the ``skipRedirectFromBackend`` flag set to ``false``.
```

**Review by learnitall — CHANGES_REQUESTED** [review]
Great work! I left some nits, comments and suggestions. Nothing major though. Thank you!

File: pkg/redirectpolicy/manager_test.go (hunk 20 above)
Comment (aditighag) [reply pkg/redirectpolicy/manager_test.go]: Yes, these are stale comments, don't exist in my local version.

File: pkg/redirectpolicy/manager.go (hunk 19 above)
Comment (aditighag) [reply pkg/redirectpolicy/manager.go]: I understand your point, but it seems like an overkill as not all users would want to use the spec flag. 
But I'll update the warning to make it more user friendly.

File: pkg/redirectpolicy/manager.go (hunk 17 above)
Comment (aditighag) [reply pkg/redirectpolicy/manager.go]: It's an oversight. 😕 Good catch!

File: pkg/redirectpolicy/manager.go (hunk 18 above)
Comment (aditighag) [reply pkg/redirectpolicy/manager.go]: We are currently logging the returned error, but I can reword the logged error message.

File: pkg/redirectpolicy/manager.go (hunk 19 above)
Comment (learnitall) [reply pkg/redirectpolicy/manager.go]: Where I'm coming from here is, if I'm a user who is relying on this field, I'd be compelled to check for this warning log every time I restart a Cilium Agent because there's no other indication given by Cilium that the field is working or not.

Comment (aditighag) [reply pkg/redirectpolicy/manager.go]: I ended up refactoring this a bit to lazy initialize the maps when policies are added. So if a policy that needs this functionality is not applied because of errors around the skip_lb maps, users can check the logs as expected.

**Comment by aditighag** [comment]
@tommyp1ckles @learnitall Thanks for the reviews. Addressed review comments, PTAL.

File: pkg/maps/lbmap/skip_lb_map.go (hunk 12 above)
Comment (learnitall) [reply pkg/maps/lbmap/skip_lb_map.go]: There are still a few uses of log formatting functions here that your PR introduces, do you mind addressing them?

```go
 git log 7670403..73eb4b5 -p | grep -E '^\+.*[EIDW].*f\(' | grep -vE 'fmt.*f'
+					log.Warnf("failed to init cilium_skip_lb maps: %v"+
+			log.Debugf("Track pod for endpoint metadata %v %v", addr, err)
+		log.Debugf("Pod endpoint netNsCookie %v %v", pod.Name, cookie)
+			log.Debugf("Endpoint event %v metadata [%v]", podID, ep.NetNsCookie)
+			}).Errorf("LRP not applied due to error in plumbing skip_lb map: %v", err)
+				log.Debugf("Track pod for endpoint metadata %v %v", addr, err)
+			log.Debugf("Pod endpoint netNsCookie %v %v", pod.Name, cookie)
+				}).Errorf("error deleting entry from map: %v", err)
+		log.Errorf("error iterating over skip_lb4 map: %v", errors)
+	scopedLog.Infof("DeleteLB4ByAddrPort deleted %d errors %d", deleted, errors)
+				}).Errorf("error deleting entry from map: %v", err)
+		log.Errorf("error iterating over skip_lb4 map: %v", errors)
+	scopedLog.Infof("DeleteLB4ByNetnsCookie deleted %d errors %d", deleted, errors)
+				}).Errorf("error deleting entry from map: %v", err)
+		log.Errorf("error iterating over skip_lb6 map: %v", errors)
+	scopedLog.Infof("DeleteLB6ByAddrPort deleted %d errors %d", deleted, errors)
+				}).Errorf("error deleting entry from map: %v", err)
+		log.Errorf("error iterating over skip_lb6 map: %v", errors)
+	scopedLog.Infof("DeleteLB6ByNetnsCookie deleted %d errors %d", deleted, errors)
+			}).Errorf("unable to parse netns cookie for ep:%v", err)
```

File: pkg/redirectpolicy/manager.go (hunk 18 above)
Comment (learnitall) [reply pkg/redirectpolicy/manager.go]: Looks great, thank you!

File: pkg/redirectpolicy/manager.go [hunk 23]
```diff
@@ -101,18 +119,48 @@ func (rpm *Manager) RegisterSvcCache(cache svcCache) {
...
+		}
+		if rpm.skipLBMap == nil {
+			err := fmt.Errorf("policy with skipRedirectFromBackend flag set not applied:" +
+				"requires cilium_skip_lb maps")
+			log.WithFields(logrus.Fields{
+				logfields.LRPType:      config.lrpType,
+				logfields.K8sNamespace: config.id.Namespace,
+				logfields.LRPName:      config.id.Name,
+			}).Error(err)
+			return false, nil
```
Comment (learnitall) [inline pkg/redirectpolicy/manager.go]: Does the error need to be returned here?
```suggestion
			return false, err
```

**Review by learnitall — CHANGES_REQUESTED** [review]
Changes look great, thank you! I think there are a couple of the formatting log methods that are still in the PR, and I think I found a typo, but otherwise LGTM!

File: pkg/redirectpolicy/manager.go (hunk 19 above)
Comment (learnitall) [reply pkg/redirectpolicy/manager.go]: That looks great thank you! This is super nice because every time a new policy is applied we'll retry creating the map if it failed previously.

**Comment by aditighag** [comment]
> Changes look great, thank you! I think there are a couple of the formatting log methods that are still in the PR, and I think I found a typo, but otherwise LGTM!

I think I got them all this time. Thanks!

File: pkg/endpointmanager/manager.go [hunk 24]
```diff
@@ -627,7 +627,17 @@ func (mgr *endpointManager) expose(ep *endpoint.Endpoint) error {
 // manager.
 func (mgr *endpointManager) RestoreEndpoint(ep *endpoint.Endpoint) error {
 	ep.SetDefaultConfiguration(true)
-	return mgr.expose(ep)
+	err := mgr.expose(ep)
+	if err != nil {
+		return err
+	}
+	mgr.mutex.RLock()
```
Comment (tommyp1ckles) [inline pkg/endpointmanager/manager.go:635]: Probably unlikely, but because all endpoint subscriber events are done in a separate critical section from expose/unexpose, could there be any issues if say a restore/delete event where emitted out of order?

(I think this is fine in your case since the other hooks appear to just be stubs)

**Review by tommyp1ckles — APPROVED** [review]
Endpoint changes lgtm

File: pkg/endpointmanager/manager.go (hunk 24 above)
Comment (joamaki) [reply pkg/endpointmanager/manager.go:635]: Seems dangerous to hold the RLock() and calling `EndpointRestored` here. At the very least it looks redirect policy manager is calling `localPods.Store()` which blocks until we've pulled the pods from api-server and that may delay endpoint restoration. 

It would be better to grab a copy of `subscribers` with RLock, then release it and call the subscribers. This does of course mean that a subscriber may get called after it has unsubscribed, but that seems like a lesser evil.

File: pkg/redirectpolicy/manager.go [hunk 25]
```diff
@@ -459,6 +591,15 @@ func (rpm *Manager) deletePolicyFrontend(config *LRPConfig, frontend *frontend)
 		log.WithError(err).Debugf("Local redirect service for policy %v not deleted",
 			config.id)
 	}
+	if config.skipRedirectFromBackend {
+		// Delete skip_lb map entries.
+		addr := frontend.AddrCluster
+		if addr.Is4() {
+			rpm.skipLBMap.DeleteLB4ByAddrPort(addr.AsNetIP(), frontend.Port)
```
Comment (joamaki) [inline pkg/redirectpolicy/manager.go:598]: We don't seem to handle BPF syscall errors from the skip map operations. At the very least we could use `WithCache()` and have a retry mechanism?

File: bpf/bpf_sock.c [hunk 26]
```diff
@@ -335,6 +339,12 @@ static __always_inline int __sock4_xlate_fwd(struct bpf_sock_addr *ctx,
 	if (sock4_skip_xlate(svc, orig_key.address))
 		return -EPERM;
 
+#ifdef ENABLE_LOCAL_REDIRECT_POLICY
+	if (lb4_svc_is_localredirect(svc) &&
```
Comment (joamaki) [inline bpf/bpf_sock.c:343]: Do we have an idea how costly this extra lookup is? We could consider making this code-path conditional on whether or not skip map entries exist?

**Review by mhofstetter — APPROVED** [review]

File: bpf/bpf_sock.c (hunk 26 above)
Comment (aditighag) [reply bpf/bpf_sock.c:343]: >whether or not skip map entries exist

Wouldn't that extra call be comparable to doing a look up in the map?

Anyway I don't think it's necessary, the lookup is only done for LRP services, and that too at the socket (`connect`) calls.

File: pkg/endpointmanager/manager.go (hunk 24 above)
Comment (aditighag) [reply pkg/endpointmanager/manager.go:635]: Maybe... AFAICS, `unsubscribe` is called in the tear down phase, so it may not race with the restore path.

File: pkg/redirectpolicy/manager.go (hunk 25 above)
Comment (aditighag) [reply pkg/redirectpolicy/manager.go:598]: I checked errors paths for other BPF maps (`git grep Map.Delete`) in the code base, and I'm not seeing any retries being done, only error being logged.

**Review by learnitall — APPROVED** [review]
Thank you!

File: pkg/endpointmanager/manager.go (hunk 24 above)
Comment (aditighag) [reply pkg/endpointmanager/manager.go:635]: Revised this logic in the latest revision.

**Comment by aditighag** [comment]
@joamaki PTAL

File: bpf/bpf_sock.c (hunk 26 above)
Comment (joamaki) [reply bpf/bpf_sock.c:343]: Oh right, yeah if it's part of `connect` then there's no point to optimize this away.

File: pkg/redirectpolicy/manager.go (hunk 25 above)
Comment (joamaki) [reply pkg/redirectpolicy/manager.go:598]: Yeah that's a general endemic problem in the codebase. We're missing critical error handling in way too many places. Looks like you're using `pkg/ebpf` and not `pkg/bpf` so there's no `WithCache()`. I guess this is less critical feature so it can live a short while without proper resilience? Alternatively you could switch the `ebpf.NewMap` to using `bpf.NewMap` and then you can chain it with `WithCache()` and have a controller that retries failed operations.

I'm working on tooling to manage BPF maps with resilience (StateDB, reconciler and https://github.com/cilium/cilium/pull/32123). I'll probably do a pass to switch simple maps over to this in coming months and can also do it for this map.

**Review by joamaki — APPROVED** [review]

File: pkg/redirectpolicy/manager.go (hunk 25 above)
Comment (aditighag) [reply pkg/redirectpolicy/manager.go:598]: I agree that having a controller to retry failed operations could make the maps operation code more resilient in general. However, I would be curious to know what failure scenarios could really benefit from such retries.
