### PR TITLE
test: Wait for kube-dns before starting test

### LINKED ISSUE #16409: CI: K8sFQDNTest Validate that multiple specs are working correctly
## CI failure

DNS requests are failing due to coredns not responding:
```
2021-06-02T16:20:41.702516076Z level=debug msg="DNS Proxy bound to address" address="[::]:35403" subsys=fqdn/dnsproxy
2021-06-02T16:21:10.903154120Z level=debug msg="Handling DNS query from endpoint" DNSRequestID=3383 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. ipAddr="10.0.1.17:50548" subsys=fqdn/dnsproxy
2021-06-02T16:21:10.903181784Z level=debug msg="Found target server to of DNS request secID {ID:19257 Source:custom-resource shadowed:false}" DNSRequestID=3383 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. endpointID=1613 ipAddr="10.0.1.17:50548" server="10.0.0.154:53" subsys=fqdn/dnsproxy
2021-06-02T16:21:10.903185726Z level=debug msg="Forwarding DNS request for a name that is allowed" DNSRequestID=3383 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. endpointID=1613 ipAddr="10.0.1.17:50548" subsys=fqdn/dnsproxy
2021-06-02T16:21:10.906064663Z level=debug msg="Handling DNS query from endpoint" DNSRequestID=36830 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. ipAddr="10.0.1.17:50548" subsys=fqdn/dnsproxy
2021-06-02T16:21:10.906219019Z level=debug msg="Found target server to of DNS request secID {ID:19257 Source:custom-resource shadowed:false}" DNSRequestID=36830 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. endpointID=1613 ipAddr="10.0.1.17:50548" server="10.0.0.154:53" subsys=fqdn/dnsproxy
2021-06-02T16:21:10.906229745Z level=debug msg="Forwarding DNS request for a name that is allowed" DNSRequestID=36830 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. endpointID=1613 ipAddr="10.0.1.17:50548" subsys=fqdn/dnsproxy
2021-06-02T16:21:13.407128424Z level=debug msg="Handling DNS query from endpoint" DNSRequestID=3383 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. ipAddr="10.0.1.17:50548" subsys=fqdn/dnsproxy
2021-06-02T16:21:13.407148809Z level=debug msg="Found target server to of DNS request secID {ID:19257 Source:custom-resource shadowed:false}" DNSRequestID=3383 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. endpointID=1613 ipAddr="10.0.1.17:50548" server="10.0.0.154:53" subsys=fqdn/dnsproxy
2021-06-02T16:21:13.407152418Z level=debug msg="Forwarding DNS request for a name that is allowed" DNSRequestID=3383 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. endpointID=1613 ipAddr="10.0.1.17:50548" subsys=fqdn/dnsproxy
2021-06-02T16:21:13.407832024Z level=debug msg="Handling DNS query from endpoint" DNSRequestID=36830 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. ipAddr="10.0.1.17:50548" subsys=fqdn/dnsproxy
2021-06-02T16:21:13.407843681Z level=debug msg="Found target server to of DNS request secID {ID:19257 Source:custom-resource shadowed:false}" DNSRequestID=36830 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. endpointID=1613 ipAddr="10.0.1.17:50548" server="10.0.0.154:53" subsys=fqdn/dnsproxy
2021-06-02T16:21:13.407847468Z level=debug msg="Forwarding DNS request for a name that is allowed" DNSRequestID=36830 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. endpointID=1613 ipAddr="10.0.1.17:50548" subsys=fqdn/dnsproxy
2021-06-02T16:21:16.912243430Z level=debug msg="Handling DNS query from endpoint" DNSRequestID=5974 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. ipAddr="10.0.1.17:34282" subsys=fqdn/dnsproxy
2021-06-02T16:21:16.912263754Z level=debug msg="Found target server to of DNS request secID {ID:19257 Source:custom-resource shadowed:false}" DNSRequestID=5974 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. endpointID=1613 ipAddr="10.0.1.17:34282" server="10.0.0.154:53" subsys=fqdn/dnsproxy
2021-06-02T16:21:16.912267474Z level=debug msg="Forwarding DNS request for a name that is allowed" DNSRequestID=5974 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. endpointID=1613 ipAddr="10.0.1.17:34282" subsys=fqdn/dnsproxy
2021-06-02T16:21:16.912275315Z level=debug msg="Handling DNS query from endpoint" DNSRequestID=5729 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. ipAddr="10.0.1.17:34282" subsys=fqdn/dnsproxy
2021-06-02T16:21:16.912277861Z level=debug msg="Found target server to of DNS request secID {ID:19257 Source:custom-resource shadowed:false}" DNSRequestID=5729 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. endpointID=1613 ipAddr="10.0.1.17:34282" server="10.0.0.154:53" subsys=fqdn/dnsproxy
2021-06-02T16:21:16.912280594Z level=debug msg="Forwarding DNS request for a name that is allowed" DNSRequestID=5729 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. endpointID=1613 ipAddr="10.0.1.17:34282" subsys=fqdn/dnsproxy
2021-06-02T16:21:19.414899563Z level=debug msg="Handling DNS query from endpoint" DNSRequestID=5729 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. ipAddr="10.0.1.17:34282" subsys=fqdn/dnsproxy
2021-06-02T16:21:19.414920948Z level=debug msg="Found target server to of DNS request secID {ID:19257 Source:custom-resource shadowed:false}" DNSRequestID=5729 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. endpointID=1613 ipAddr="10.0.1.17:34282" server="10.0.0.154:53" subsys=fqdn/dnsproxy
2021-06-02T16:21:19.414924725Z level=debug msg="Forwarding DNS request for a name that is allowed" DNSRequestID=5729 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. endpointID=1613 ipAddr="10.0.1.17:34282" subsys=fqdn/dnsproxy
2021-06-02T16:21:19.414932502Z level=debug msg="Handling DNS query from endpoint" DNSRequestID=5974 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. ipAddr="10.0.1.17:34282" subsys=fqdn/dnsproxy
2021-06-02T16:21:19.414953061Z level=debug msg="Found target server to of DNS request secID {ID:19257 Source:custom-resource shadowed:false}" DNSRequestID=5974 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. endpointID=1613 ipAddr="10.0.1.17:34282" server="10.0.0.154:53" subsys=fqdn/dnsproxy
2021-06-02T16:21:19.415060007Z level=debug msg="Forwarding DNS request for a name that is allowed" DNSRequestID=5974 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. endpointID=1613 ipAddr="10.0.1.17:34282" subsys=fqdn/dnsproxy
2021-06-02T16:21:20.905173339Z level=warning msg="Timeout waiting for response to forwarded proxied DNS lookup" DNSRequestID=3383 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. endpointID=1613 error="read udp 10.0.1.227:35886->10.0.0.154:53: i/o timeout" ipAddr="10.0.1.17:50548" subsys=fqdn/dnsproxy
2021-06-02T16:21:20.907376471Z level=warning msg="Timeout waiting for response to forwarded proxied DNS lookup" DNSRequestID=36830 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. endpointID=1613 error="read udp 10.0.1.227:34482->10.0.0.154:53: i/o timeout" ipAddr="10.0.1.17:50548" subsys=fqdn/dnsproxy
2021-06-02T16:21:23.409467910Z level=warning msg="Timeout waiting for response to forwarded proxied DNS lookup" DNSRequestID=36830 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. endpointID=1613 error="read udp 10.0.1.227:55132->10.0.0.154:53: i/o timeout" ipAddr="10.0.1.17:50548" subsys=fqdn/dnsproxy
2021-06-02T16:21:23.409587876Z level=warning msg="Timeout waiting for response to forwarded proxied DNS lookup" DNSRequestID=3383 dnsName=vagrant-cache.ci.cilium.io.default.svc.cluster.local. endpointID=1613 error="read udp 10.0.1.227:33239->10.0.0.154:53: i/o timeout" ipAddr="10.0.1.17:50548" subsys=fqdn/dnsproxy
```
CoreDNS logs do not reveal anything:
```
2021-06-02T16:18:49.087469113Z cilium.test.:53
2021-06-02T16:18:49.087507827Z .:53
2021-06-02T16:18:49.087811035Z [INFO] plugin/reload: Running configuration MD5 = 25c208da8218c8a2947c0192345d561e
2021-06-02T16:18:49.087823418Z CoreDNS-1.8.0
2021-06-02T16:18:49.087827554Z linux/amd64, go1.15.3, 054c9ae
2021-06-02T16:18:49.095027824Z [INFO] 127.0.0.1:50866 - 63344 "HINFO IN 6332896698001052037.783533555189006764. udp 56 false 512" NXDOMAIN qr,rd,ra 131 0.007472997s
2021-06-02T16:18:50.670404480Z [INFO] 10.0.2.15:15385 - 31320 "A IN kubernetes.default.svc.cluster.local. udp 77 false 4096" NOERROR qr,aa,rd 106 0.001115605s
2021-06-02T16:18:55.946854834Z [INFO] 10.0.2.15:55311 - 33294 "A IN kubernetes.default.svc.cluster.local. udp 77 false 4096" NOERROR qr,aa,rd 106 0.00010673s
2021-06-02T16:19:30.230588949Z [INFO] 10.0.0.7:60863 - 5387 "AAAA IN prometheus.cilium-monitoring.svc.cluster.local. udp 64 false 512" NOERROR qr,aa,rd 157 0.000167214s
2021-06-02T16:19:30.230679483Z [INFO] 10.0.0.7:34596 - 2659 "A IN prometheus.cilium-monitoring.svc.cluster.local. udp 64 false 512" NOERROR qr,aa,rd 126 0.000101328s
2021-06-02T16:20:47.465971785Z [INFO] 10.0.2.15:25621 - 41455 "A IN kubernetes.default.svc.cluster.local. udp 77 false 4096" NOERROR qr,aa,rd 106 0.003893244s
```
The failing request is for a nonexistent cluster service (`vagrant-cache.ci.cilium.io.default.svc.cluster.local`) that coredns should be able to respond to, not sure it the log indicates anything about coredns knowing the current cluster config or not.

Might be worthwhile to add a step where we validate that coredns can respond to some known cluster service (such as the apiserver) before starting any tests?

Failing test logs: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/587/testReport/junit/Suite-k8s-1/21/K8sFQDNTest_Validate_that_multiple_specs_are_working_correctly/

Test artifacts: [06c05254_K8sFQDNTest_Validate_that_multiple_specs_are_working_correctly.zip](https://github.com/cilium/cilium/files/6586869/06c05254_K8sFQDNTest_Validate_that_multiple_specs_are_working_correctly.zip)

### Stacktrace
```
/home/jenkins/workspace/Cilium-PR-K8s-1.21-kernel-4.9/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:518
Can't connect to to a valid target when it should work
Expected command: kubectl exec -n default app2-58757b7dd5-nrbhn -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 --retry 5 http://vagrant-cache.ci.cilium.io -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Err: exit status 28
Stdout:
 	 time-> DNS: '0.000000()', Connect: '0.000000',Transfer '0.000000', total '5.234394'
Stderr:
 	 command terminated with exit code 28
	 

/home/jenkins/workspace/Cilium-PR-K8s-1.21-kernel-4.9/src/github.com/cilium/cilium/test/k8sT/fqdn.go:283
Standard Output
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
⚠️  Number of "level=warning" in logs: 20
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
Top 1 errors/warnings:
Timeout waiting for response to forwarded proxied DNS lookup
Cilium pods: [cilium-b4rx6 cilium-zmxx4]
Netpols loaded: 
CiliumNetworkPolicies loaded: default::fqdn-proxy-policy.yaml 
Endpoint Policy Enforcement:
Pod                           Ingress   Egress
app1-6bf9bf9bd5-d57t5                   
app1-6bf9bf9bd5-wffvp                   
app2-58757b7dd5-nrbhn                   
app3-5d69599cdd-nmcb9                   
coredns-755cd654d4-ktrpj                
grafana-5747bcc8f9-nz5ck                
prometheus-655fb888d7-rdb6t             
Cilium agent 'cilium-b4rx6': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 36 Failed 0
Cilium agent 'cilium-zmxx4': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 37 Failed 0
```
### Standard Error
```
16:21:10 STEP: Validating APP2 policy connectivity
FAIL: Can't connect to to a valid target when it should work
Expected command: kubectl exec -n default app2-58757b7dd5-nrbhn -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 --retry 5 http://vagrant-cache.ci.cilium.io -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Err: exit status 28
Stdout:
 	 time-> DNS: '0.000000()', Connect: '0.000000',Transfer '0.000000', total '5.234394'
Stderr:
 	 command terminated with exit code 28
	 

=== Test Finished at 2021-06-02T16:22:12Z====
16:22:12 STEP: Running JustAfterEach block for EntireTestsuite K8sFQDNTest
===================== TEST FAILED =====================
16:22:12 STEP: Running AfterFailed block for EntireTestsuite K8sFQDNTest
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE           NAME                              READY   STATUS    RESTARTS   AGE     IP              NODE   NOMINATED NODE   READINESS GATES
	 cilium-monitoring   grafana-5747bcc8f9-nz5ck          1/1     Running   0          28m     10.0.0.7        k8s2   <none>           <none>
	 cilium-monitoring   prometheus-655fb888d7-rdb6t       1/1     Running   0          28m     10.0.0.158      k8s2   <none>           <none>
	 default             app1-6bf9bf9bd5-d57t5             2/2     Running   0          77s     10.0.1.220      k8s1   <none>           <none>
	 default             app1-6bf9bf9bd5-wffvp             2/2     Running   0          77s     10.0.1.245      k8s1   <none>           <none>
	 default             app2-58757b7dd5-nrbhn             1/1     Running   0          77s     10.0.1.17       k8s1   <none>           <none>
	 default             app3-5d69599cdd-nmcb9             1/1     Running   0          77s     10.0.1.1        k8s1   <none>           <none>
	 kube-system         cilium-b4rx6                      1/1     Running   0          98s     192.168.36.12   k8s2   <none>           <none>
	 kube-system         cilium-operator-8c9445bd4-jckk8   1/1     Running   0          98s     192.168.36.12   k8s2   <none>           <none>
	 kube-system         cilium-operator-8c9445bd4-nd7f2   1/1     Running   0          98s     192.168.36.11   k8s1   <none>           <none>
	 kube-system         cilium-zmxx4                      1/1     Running   0          98s     192.168.36.11   k8s1   <none>           <none>
	 kube-system         coredns-755cd654d4-ktrpj          1/1     Running   0          3m36s   10.0.0.154      k8s2   <none>           <none>
	 kube-system         etcd-k8s1                         1/1     Running   0          31m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-apiserver-k8s1               1/1     Running   0          31m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-controller-manager-k8s1      1/1     Running   0          31m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-proxy-2zhzp                  1/1     Running   0          31m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-proxy-kc5ts                  1/1     Running   0          29m     192.168.36.12   k8s2   <none>           <none>
	 kube-system         kube-scheduler-k8s1               1/1     Running   0          31m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         log-gatherer-7s2k8                1/1     Running   0          28m     192.168.36.12   k8s2   <none>           <none>
	 kube-system         log-gatherer-knrdm                1/1     Running   0          28m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         registry-adder-4nsdh              1/1     Running   0          29m     192.168.36.12   k8s2   <none>           <none>
	 kube-system         registry-adder-r27t7              1/1     Running   0          29m     192.168.36.11   k8s1   <none>           <none>
	 
Stderr:
 	 

Fetching command output from pods [cilium-b4rx6 cilium-zmxx4]
cmd: kubectl exec -n kube-system cilium-b4rx6 -- cilium service list
Exitcode: 0 
Stdout:
 	 ID   Frontend              Service Type   Backend                   
	 1    10.96.0.1:443         ClusterIP      1 => 192.168.36.11:6443   
	 2    10.96.0.10:53         ClusterIP      1 => 10.0.0.154:53        
	 3    10.96.0.10:9153       ClusterIP      1 => 10.0.0.154:9153      
	 4    10.105.196.217:3000   ClusterIP      1 => 10.0.0.7:3000        
	 5    10.106.128.91:9090    ClusterIP      1 => 10.0.0.158:9090      
	 6    10.105.44.123:80      ClusterIP      1 => 10.0.1.245:80        
	                                           2 => 10.0.1.220:80        
	 7    10.105.44.123:69      ClusterIP      1 => 10.0.1.245:69        
	                                           2 => 10.0.1.220:69        
	 
Stderr:
 	 Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
	 

cmd: kubectl exec -n kube-system cilium-b4rx6 -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                                        IPv6       IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                                             
	 314        Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s2                                                                                 ready   
	                                                            k8s:status=lockdown                                                                                                
	                                                            reserved:host                                                                                                      
	 919        Disabled           Disabled          21050      k8s:app=grafana                                                                    fd02::a3   10.0.0.7     ready   
	                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=cilium-monitoring                                   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                           
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                    
	                                                            k8s:io.kubernetes.pod.namespace=cilium-monitoring                                                                  
	 1062       Disabled           Disabled          32509      k8s:app=prometheus                                                                 fd02::bd   10.0.0.158   ready   
	                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=cilium-monitoring                                   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                           
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=prometheus-k8s                                                             
	                                                            k8s:io.kubernetes.pod.namespace=cilium-monitoring                                                                  
	 1526       Disabled           Disabled          4          reserved:health                                                                    fd02::93   10.0.0.157   ready   
	 1685       Disabled           Disabled          19257      k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system         fd02::63   10.0.0.154   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                           
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=coredns                                                                    
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                                        
	                                                            k8s:k8s-app=kube-dns                                                                                               
	 
Stderr:
 	 Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
	 

cmd: kubectl exec -n kube-system cilium-zmxx4 -- cilium service list
Exitcode: 0 
Stdout:
 	 ID   Frontend              Service Type   Backend                   
	 1    10.106.128.91:9090    ClusterIP      1 => 10.0.0.158:9090      
	 2    10.96.0.1:443         ClusterIP      1 => 192.168.36.11:6443   
	 3    10.96.0.10:53         ClusterIP      1 => 10.0.0.154:53        
	 4    10.96.0.10:9153       ClusterIP      1 => 10.0.0.154:9153      
	 5    10.105.196.217:3000   ClusterIP      1 => 10.0.0.7:3000        
	 6    10.105.44.123:80      ClusterIP      1 => 10.0.1.245:80        
	                                           2 => 10.0.1.220:80        
	 7    10.105.44.123:69      ClusterIP      1 => 10.0.1.245:69        
	                                           2 => 10.0.1.220:69        
	 
Stderr:
 	 Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
	 

cmd: kubectl exec -n kube-system cilium-zmxx4 -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                              IPv6        IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                                    
	 950        Disabled           Enabled           16993      k8s:id=app3                                                              fd02::185   10.0.1.1     ready   
	                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default                                    
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                  
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                           
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                   
	                                                            k8s:zgroup=testapp                                                                                        
	 1568       Disabled           Disabled          42564      k8s:id=app1                                                              fd02::1c1   10.0.1.245   ready   
	                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default                                    
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                  
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=app1-account                                                      
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                   
	                                                            k8s:zgroup=testapp                                                                                        
	 1613       Disabled           Enabled           34655      k8s:appSecond=true                                                       fd02::1e4   10.0.1.17    ready   
	                                                            k8s:id=app2                                                                                               
	                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default                                    
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                  
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=app2-account                                                      
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                   
	                                                            k8s:zgroup=testapp                                                                                        
	 2435       Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s1                                                                        ready   
	                                                            k8s:node-role.kubernetes.io/control-plane                                                                 
	                                                            k8s:node-role.kubernetes.io/master                                                                        
	                                                            k8s:node.kubernetes.io/exclude-from-external-load-balancers                                               
	                                                            reserved:host                                                                                             
	 2528       Disabled           Disabled          4          reserved:health                                                          fd02::1ba   10.0.1.72    ready   
	 3272       Disabled           Disabled          42564      k8s:id=app1                                                              fd02::11a   10.0.1.220   ready   
	                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default                                    
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                  
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=app1-account                                                      
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                   
	                                                            k8s:zgroup=testapp                                                                                        
	 
Stderr:
 	 Defaulted container "cilium-agent" out of: cilium-agent, clean-cilium-state (init)
```

### PR DESCRIPTION
**Pull request by jrajahalme**
Wait for kube-dns to become reachable from test pod before running test in fqdn.go.

Fixes: #16409

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-1.21-4.9

File: test/k8sT/fqdn.go [hunk 1]
```diff
@@ -85,6 +85,11 @@ var _ = SkipDescribeIf(helpers.RunsOn54Kernel, "K8sFQDNTest", func() {
 		err = kubectl.WaitforPods(helpers.DefaultNamespace, "-l zgroup=testapp", helpers.HelperTimeout)
 		Expect(err).Should(BeNil(), "Testapp is not ready after timeout")
 
+		// Validate that coredns is reachable from test pods
+		err = kubectl.NslookupInPod(helpers.DefaultNamespace, appPods[helpers.App2],
+			fmt.Sprintf("kube-dns.%s.svc.cluster.local", helpers.CiliumNamespace))
```
Comment (anfernee) [inline test/k8sT/fqdn.go]: I believe `kube-dns` always runs in `kube-system`, is it not true?

Comment (jrajahalme) [reply test/k8sT/fqdn.go]: You must be right, will fix :-)

**Comment by jrajahalme** [comment]
test-me-please

**Review by nebril — APPROVED** [review]

**Comment by jrajahalme** [comment]
test-1.20-4.19 had timed out

**Comment by jrajahalme** [comment]
test-1.20-4.19
run had failed in 7.5 seconds

**Comment by nebril** [comment]
test-1.20-4.19

**Comment by jrajahalme** [comment]
The two CI flakes are unrelated to this change, flagging as ready-to-merge.

**Comment by joestringer** [comment]
Should we be backporting this to v1.10 to help stabilize CI?

**Comment by aditighag** [comment]
@joestringer Yeah, I was just going to comment the same based on the comment I posted in #16671. You beat me to it. :)
