### PR TITLE
kubernetes: No CEP CRD for cilium-health EP

### LINKED ISSUE #4979: Cannot update CEP: StorageError: invalid object
Likely not a serious error so the work here may be to hide this error to not raise unnecessary concerns:

```
level=error msg="Cannot update CEP" containerID=cilium-loc controller="sync-to-k8s-ciliumendpoint (45702)" endpointID=45702 error="Operation cannot be fulfilled on ciliumendpoints.cilium.io \"cilium-health-ip-172-0-52-103.us-west-2.compute.internal\": StorageError: invalid object, Code: 4, Key: /registry/cilium.io/ciliumendpoints/kube-system/cilium-health-ip-172-0-52-103.us-west-2.compute.internal, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 9118baef-8e28-11e8-a7dc-029cdb62bcae, UID in object meta: " ipv4=10.2.1.195 ipv6="f00d::a02:100:0:b286" k8sPodName=":" policyRevision=0
```

### PR DESCRIPTION
**Pull request by raybejjani**
The cilium-health endpoint doesn't exist in kubernetes land, and we've
had random errors trying to maintain corresponding CEPs. Instead of
playing wack-a-mole with the errors, avoid creating the CEP to begin
with. Older, already created, cilium-health CEPs will be GCed.

Fixes #4979

```release-note/minor
cilium-agent no longer creates a CiliumEndpoint k8s CRD for internal cilium-health endpoints
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4981)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

File: pkg/endpoint/endpoint.go [hunk 1]
```diff
@@ -518,6 +514,12 @@ func (e *Endpoint) RunK8sCiliumEndpointSync() {
 		return
 	}
 
+	if isHealthEP := e.HasLabels(pkgLabels.LabelHealth); isHealthEP {
```
Comment (ianvernon) [inline pkg/endpoint/endpoint.go]: This will deadlock the agent.

The caller of `RunK8sCiliumEndpointSync` holds the endpoint's mutex:
https://github.com/cilium/cilium/blob/9639c30f14ea7428d182452a13a0d7ad6a5fbc24/pkg/endpointmanager/manager.go#L61-L70

And `endpoint.HasLabels` tries to `RLock()` that same lock:
https://github.com/cilium/cilium/blob/9639c30f14ea7428d182452a13a0d7ad6a5fbc24/pkg/endpoint/endpoint.go#L1660-L1681

**Review by ianvernon — CHANGES_REQUESTED** [review]
Please address the comment re: deadlock.

File: pkg/endpoint/endpoint.go (hunk 1 above)
Comment (ianvernon) [reply pkg/endpoint/endpoint.go]: Oops, the mutex I am looking at is the endpointmanager mutex in `Insert`...

Comment (raybejjani) [reply pkg/endpoint/endpoint.go]: but! there is a deadlock detected on `ep.Mutex`, so you have magic intuition.

Comment (ianvernon) [reply pkg/endpoint/endpoint.go]: https://stackoverflow.com/questions/30547916/goroutine-blocks-when-calling-rwmutex-rlock-twice-after-an-rwmutex-unlock `Insert` for an endpoint requires that the endpoint's mutex is read-locked. `HasLabels` calls `RLock` on the same mutex, within the same goroutine. However, this will cause deadlock in the code, because of the documentation for Golang's `RWMutex`:

> To ensure that the lock eventually becomes available, a blocked Lock call excludes new readers from acquiring the lock.

This effectively means that trying `RLock` twice within the same goroutine can result in a deadlock. 

Source: https://stackoverflow.com/questions/30547916/goroutine-blocks-when-calling-rwmutex-rlock-twice-after-an-rwmutex-unlock

**Comment by raybejjani** [comment]
I ended up suspending the controller to avoid the race. `RunK8sCiliumEndpointSync` doesn't directly lock the endpoint but it's callers do in various ways. Eventually, once we refactor those callsites a little bit, we can revisit this (the pkg/controllers function seemed like a lesser evil than a more major code reshuffle).

**Comment by raybejjani** [comment]
test-me-please

File: pkg/endpoint/endpoint.go [hunk 2]
```diff
@@ -535,29 +531,30 @@ func (e *Endpoint) RunK8sCiliumEndpointSync() {
...
-						scopedLog.Debug("Skipping CiliumEndpoint update because it has no k8s namespace")
-						return nil
-					}
+				// The health endpoint doesn't really exist in k8s and updates to it caused
+				// arbitrary errors. Disable the controller for these endpoints
+				// This is inside the controller to avoid deadlocking; calls to
+				// RunK8sCiliumEndpointSync hold ep.Mutex and that conflicts with
+				// HasLabels.
+				if isHealthEP := e.HasLabels(pkgLabels.LabelHealth); isHealthEP {
+					// use an error object so we can stop the controller. This is NOT an
```
Comment (ianvernon) [inline pkg/endpoint/endpoint.go]: Instead of starting the controller, why not create a private function, `hasLabelsRLocked` which assumes the RLock is held and then call it outside of the controller? You can use this function within `HasLabels`. This solves the potential deadlock. We are trying to induce behavior that indicates the controller shouldn't be ran; we should not run the controller and add the necessary code to avoid deadlock.

File: pkg/controller/controller.go [hunk 3]
```diff
@@ -32,13 +33,19 @@ type ControllerFunc func() error
...
+// Construct one with MakeExitReason("a reason")
 type ExitReason struct {
 	// This is constucted in this odd way because the type assertion in
 	// runController didn't work otherwise.
 	error
 }
 
+// MakeExitReason constructs an error object that, when returned by a DoFunc,
+// stops the controller from running further.
+func MakeExitReason(msg string) ExitReason {
```
Comment (ianvernon) [inline pkg/controller/controller.go]: Unit test this please, and plumb its usage wherever creation of an exit reason is called directly in the controller code.

**Review by ianvernon — CHANGES_REQUESTED** [review]
See comments.

File: pkg/endpoint/endpoint.go (hunk 2 above)
Comment (raybejjani) [reply pkg/endpoint/endpoint.go]: I had hoped to keep the controller create function free of the endpoint. At least, not have it hold a lock. As it turns out, we create this controller on `e.controllers` (it was once unattached to a local controller, only the global one).
With that in mind, what you're suggesting works far better. I've also labelled the function as needing the rlock.

**Review by raybejjani — COMMENTED** [review]
Ok, this should be less wonky now.

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by ianvernon** [comment]
@raybejjani all tests are failing with "Timeout reached: CEP not ready after timeout". My hypothesis is that you may need to update the logic which checks for CEPs in K8s; there might be an issue where we are waiting for a corresponding CEP for each endpoint that is running in each pod, and now, there is no health CEP, so the tests timeout.

**Comment by raybejjani** [comment]
Just as well, I suppose. I messed up the commits anyway and left a bogus comment. I'll debug and retest. Your hypothesis is likely correct (sadly :/)

**Comment by raybejjani** [comment]
@ianvernon I've put this PR into wip for now. I have https://github.com/cilium/cilium/pull/5068 which addressed the error in https://github.com/cilium/cilium/issues/4979 more directly (and, ideally, more simply).

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-upstream-k8s

**Comment by raybejjani** [comment]
test-missed-k8s

**Comment by raybejjani** [comment]
test-upstream-k8s

**Comment by raybejjani** [comment]
test-missed-k8s

**Comment by raybejjani** [comment]
test-me-please

**Review by eloycoto — APPROVED** [review]

**Comment by raybejjani** [comment]
@ianvernon I figured out how to make the test work without too much surgery. This PR isn't exclusive with https://github.com/cilium/cilium/pull/5068 but let's run with this one for now. sorry for the flip-flop.

**Review by tgraf — APPROVED** [review]

**Comment by raybejjani** [comment]
test-me-please
