### PR TITLE
hive/cell/health: don't warn when reporting on stopped reporter.

### LINKED ISSUE #31147: CI: Conformance Ginkgo: K8sDatapathLRPTests Checks local redirect policy LRP connectivity: error="reporter 10-datapath-regenerate has been stopped"
## CI failure

PR failure: https://github.com/cilium/cilium/actions/runs/8147153559/job/22269541305
[cilium-sysdumps (20).zip](https://github.com/cilium/cilium/files/14487987/cilium-sysdumps.20.zip)

```
K8sDatapathLRPTests Checks local redirect policy 
  LRP connectivity
  /home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:515
22:30:47 STEP: Running BeforeAll block for EntireTestsuite K8sDatapathLRPTests
22:30:48 STEP: Ensuring the namespace kube-system exists
22:30:48 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs")
22:30:48 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs") => <nil>
22:30:49 STEP: Running BeforeAll block for EntireTestsuite K8sDatapathLRPTests Checks local redirect policy
22:30:49 STEP: Installing Cilium
22:30:56 STEP: Waiting for Cilium to become ready
22:31:25 STEP: Validating if Kubernetes DNS is deployed
22:31:25 STEP: Checking if deployment is ready
22:31:26 STEP: Checking if kube-dns service is plumbed correctly
22:31:26 STEP: Checking if pods have identity
22:31:26 STEP: Checking if DNS can resolve
22:31:30 STEP: Kubernetes DNS is not ready: %!s(<nil>)
22:31:30 STEP: Restarting Kubernetes DNS (-l k8s-app=kube-dns)
22:31:31 STEP: Waiting for Kubernetes DNS to become operational
22:31:31 STEP: Checking if deployment is ready
22:31:32 STEP: Kubernetes DNS is not ready yet: only 0 of 2 replicas are available
22:31:32 STEP: Checking if deployment is ready
22:31:33 STEP: Kubernetes DNS is not ready yet: only 0 of 2 replicas are available
22:31:33 STEP: Checking if deployment is ready
22:31:34 STEP: Kubernetes DNS is not ready yet: only 0 of 2 replicas are available
22:31:34 STEP: Checking if deployment is ready
22:31:35 STEP: Kubernetes DNS is not ready yet: only 0 of 2 replicas are available
22:31:35 STEP: Checking if deployment is ready
22:31:36 STEP: Kubernetes DNS is not ready yet: only 0 of 2 replicas are available
22:31:36 STEP: Checking if deployment is ready
22:31:37 STEP: Kubernetes DNS is not ready yet: only 0 of 2 replicas are available
22:31:37 STEP: Checking if deployment is ready
22:31:38 STEP: Kubernetes DNS is not ready yet: only 0 of 2 replicas are available
22:31:38 STEP: Checking if deployment is ready
22:31:39 STEP: Kubernetes DNS is not ready yet: only 0 of 2 replicas are available
22:31:39 STEP: Checking if deployment is ready
22:31:40 STEP: Kubernetes DNS is not ready yet: only 1 of 2 replicas are available
22:31:40 STEP: Checking if deployment is ready
22:31:41 STEP: Checking if kube-dns service is plumbed correctly
22:31:41 STEP: Checking if pods have identity
22:31:41 STEP: Checking if DNS can resolve
22:31:42 STEP: Validating Cilium Installation
22:31:42 STEP: Performing Cilium controllers preflight check
22:31:42 STEP: Performing Cilium health check
22:31:42 STEP: Checking whether host EP regenerated
22:31:42 STEP: Performing Cilium status preflight check
22:31:44 STEP: Performing Cilium service preflight check
22:31:44 STEP: Performing K8s service preflight check
22:31:45 STEP: Waiting for cilium-operator to be ready
22:31:45 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator")
22:31:45 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator") => <nil>
22:31:46 STEP: WaitforPods(namespace="default", filter="-l role=frontend")
22:31:50 STEP: WaitforPods(namespace="default", filter="-l role=frontend") => <nil>
22:31:50 STEP: WaitforPods(namespace="default", filter="-l role=backend")
22:31:51 STEP: WaitforPods(namespace="default", filter="-l role=backend") => <nil>
22:31:51 STEP: WaitforPods(namespace="default", filter="-l role=lrpAddrBackend")
22:31:51 STEP: WaitforPods(namespace="default", filter="-l role=lrpAddrBackend") => <nil>
22:31:53 STEP: Checking traffic goes to local backend
Pod                           Ingress   Egress
grafana-6f4755f98c-vlfvn                
prometheus-67fdcf4796-z6d56             
k8s1-backend                            
k8s1-client                             
k8s2-backend                            
k8s2-client                             
coredns-76f75df574-8pvx8                
coredns-76f75df574-x8ls2                
Cilium agent 'cilium-64t8x': Status: Ok  Health: Ok Nodes "" ContainerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 29 Failed 0
Cilium agent 'cilium-kq54f': Status: Ok  Health: Ok Nodes "" ContainerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 51 Failed 0

</Checks>


• Failure in Spec Teardown (AfterEach) [136.897 seconds]
K8sDatapathLRPTests
/home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:461
  Checks local redirect policy
  /home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:461
    LRP connectivity [AfterEach]
    /home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:515

    Found 6 k8s-app=cilium logs matching list of errors that must be investigated:
    2024-03-04T22:31:37.194947916Z level=warning msg="Regeneration of endpoint failed" bpfCompilation=14.631117962s bpfLoadProg=515.994526ms bpfWaitForELF=14.631543195s bpfWriteELF=14.744104ms ciliumEndpointName=kube-system/coredns-76f75df574-85k62 containerID=24fea10bf3 containerInterface=eth0 datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3173 error="Error while configuring proxy redirects: context cancelled before waiting for proxy updates: context canceled" identity=686 ipv4=10.0.0.237 ipv6="fd02::d5" k8sPodName=kube-system/coredns-76f75df574-85k62 mapSync="121.004µs" policyCalculation=1.724529ms prepareBuild=10.524056ms proxyConfiguration="10.248µs" proxyPolicyCalculation="774.945µs" proxyWaitForAck="4.448µs" reason="syncing state to host" subsys=endpoint total=15.210727697s waitingForCTClean=552ns waitingForLock="45.164µs"
    2024-03-04T22:31:37.195980470Z level=error msg="endpoint regeneration failed" ciliumEndpointName=kube-system/coredns-76f75df574-85k62 containerID=24fea10bf3 containerInterface=eth0 datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3173 error="Error while configuring proxy redirects: context cancelled before waiting for proxy updates: context canceled" identity=686 ipv4=10.0.0.237 ipv6="fd02::d5" k8sPodName=kube-system/coredns-76f75df574-85k62 subsys=endpoint
    2024-03-04T22:31:37.196506781Z level=warning msg="could not set degraded status on subreporter \"9-datapath-regenerate\"" error="reporter 9-datapath-regenerate has been stopped" subsys=hive
    2024-03-04T22:31:37.381[298](https://github.com/cilium/cilium/actions/runs/8147153559/job/22269541305#step:16:300)791Z level=warning msg="Regeneration of endpoint failed" bpfCompilation=0s bpfLoadProg=704.95865ms bpfWaitForELF=14.621677359s bpfWriteELF=11.414126ms ciliumEndpointName=kube-system/coredns-76f75df574-qklfc containerID=907fa13179 containerInterface=eth0 datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=1037 error="Error while configuring proxy redirects: context cancelled before waiting for proxy updates: context canceled" identity=686 ipv4=10.0.0.58 ipv6="fd02::f7" k8sPodName=kube-system/coredns-76f75df574-qklfc mapSync="91.58µs" policyCalculation=2.392209ms prepareBuild=21.725394ms proxyConfiguration="9.698µs" proxyPolicyCalculation="496.[304](https://github.com/cilium/cilium/actions/runs/8147153559/job/22269541305#step:16:306)µs" proxyWaitForAck="5.731µs" reason="syncing state to host" subsys=endpoint total=15.39751845s waitingForCTClean=461ns waitingForLock="1.642µs"
    2024-03-04T22:31:37.381371136Z level=error msg="endpoint regeneration failed" ciliumEndpointName=kube-system/coredns-76f75df574-qklfc containerID=907fa1[317](https://github.com/cilium/cilium/actions/runs/8147153559/job/22269541305#step:16:319)9 containerInterface=eth0 datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=1037 error="Error while configuring proxy redirects: context cancelled before waiting for proxy updates: context canceled" identity=686 ipv4=10.0.0.58 ipv6="fd02::f7" k8sPodName=kube-system/coredns-76f75df574-qklfc subsys=endpoint
    2024-03-04T22:31:37.381373971Z level=warning msg="could not set degraded status on subreporter \"10-datapath-regenerate\"" error="reporter 10-datapath-regenerate has been stopped" subsys=hive

    /home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:413
```

Looks like there's a race condition where endpoint regeneration was canceled somewhere during the test and this generated error/warning logs.

### LINKED ISSUE #31238: HealthReporter should skip error logs if the reporter fails to set status, but it has already been stopped
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In CI, some jobs can fail with 

```
 FAIL: Found 2 k8s-app=cilium logs matching list of errors that must be investigated:
2024-03-07T20:41:06.648518164Z level=warning msg="could not set OK status on subreporter \"9-datapath-regenerate\"" error="reporter 9-datapath-regenerate has been stopped" subsys=hive
2024-03-07T20:41:06.699137665Z level=warning msg="could not set OK status on subreporter \"11-datapath-regenerate\"" error="reporter 11-datapath-regenerate has been stopped" subsys=hive
```

Digging into the error displayed, it looks like there was some kind of race between setting the health status on the reporter and stopping the reporter. My thinking is that if Cilium fails to set the health reporter status because the reporter is stopped/stopping, then it should not log an error for that specific case.

### Cilium Version

`main`

### Kernel Version

N/A

### Kubernetes Version

N/A

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

https://github.com/cilium/cilium/actions/runs/8194438762/job/22412008207#step:16:358

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by tommyp1ckles**
Currently in cases where reporters emit status on stopped reporters, a warning is logged. This causes failures in CI related to endpoints, as those close their reporters after endpoint is deleted.

This scenario is probably not a valuable log for users and generally such occurances should be harmless. This moves the log to debug level.

Fixes: #31147

### CODE REVIEW

**Review by dylandreimerink — APPROVED** [review]

**Review by jrajahalme — COMMENTED** [review]
This may not fully resolve #31147, as it also contains other error logs that are flaking CI tests:
```
    2024-03-04T22:31:37.195980470Z level=error msg="endpoint regeneration failed" ciliumEndpointName=kube-system/coredns-76f75df574-85k62 containerID=24fea10bf3 containerInterface=eth0 datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3173 error="Error while configuring proxy redirects: context cancelled before waiting for proxy updates: context canceled" identity=686 ipv4=10.0.0.237 ipv6="fd02::d5" k8sPodName=kube-system/coredns-76f75df574-85k62 subsys=endpoint
```

File: pkg/hive/cell/structured.go [hunk 1]
```diff
@@ -568,15 +568,15 @@ type subReporter struct {
 
 func (s *subReporter) OK(message string) {
 	if err := s.base.setStatus(s.id, StatusOK, message, nil); err != nil {
-		log.WithError(err).Warnf("could not set OK status on subreporter %q", s.id)
+		log.WithError(err).Debugf("could not set OK status on subreporter %q", s.id)
```
Comment (christarazi) [inline pkg/hive/cell/structured.go]: Why not check the error returned is indeed because the reporter is stopped, rather than blindly treating all errors as the same? i.e. https://github.com/cilium/cilium/issues/31238

Comment (tommyp1ckles) [reply pkg/hive/cell/structured.go]: @christarazi Makes sense, made the change, ptal.

File: pkg/hive/cell/structured.go [hunk 2]
```diff
@@ -568,15 +571,23 @@ type subReporter struct {
 
 func (s *subReporter) OK(message string) {
 	if err := s.base.setStatus(s.id, StatusOK, message, nil); err != nil {
-		log.WithError(err).Warnf("could not set OK status on subreporter %q", s.id)
+		if errors.Is(err, errReporterStopped) {
+			log.WithError(err).Debugf("could not set OK status on subreporter %q", s.id)
+		} else {
+			log.WithError(err).Warningf("could not set OK status on subreporter %q", s.id)
+		}
```
Comment (christarazi) [inline pkg/hive/cell/structured.go]: While we're at it, it would be good to use `logfields.ID` here instead of dynamic formatting.

**Review by christarazi — APPROVED** [review]

**Comment by christarazi** [comment]
I don't think this quite warrants a `minor` release note as this "bug" never really impacted the user behavior, unless they were monitoring the health status. Given that is relatively new, I don't think users have really been using it. I'd go with `misc`.

File: pkg/hive/cell/structured.go (hunk 2 above)
Comment (tommyp1ckles) [reply pkg/hive/cell/structured.go]: Sounds good, there doesn't appear to be a general logfields.ID field, so I just added a local const here since this is only for logging internal details regarding health.

**Comment by tommyp1ckles** [comment]
@jrajahalme added second commit that should address all CI failure logs
