### PR TITLE
Proxy: Do not release acknowledged proxy ports when endpoint regeneration fails

### LINKED ISSUE #36063: TPROXY iptables-rules for cilium-dns-egress redirect to the wrong port
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.3 and lower than v1.17.0

### What happened?

We are running kubernetes clusters on GKE. Sometimes the cluster-autoscaler backs out of a node scale down if a pod doesn't exit cleanly within the timeout. When this happens the node scaledown fails and the node is put back in to the pool.

Pods getting scheduled on these nodes can't do any DNS-lookups if there is a CNP with an L7 DNS rule for example:
```
spec:
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: kube-system
        k8s:k8s-app: kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: '*'
  endpointSelector:
    matchLabels: {}

```

I've tried tracking the issue down to the best of my abilities and here's what I've come up with:
The DNS-proxy is listening on a dynamically allocated port, in this case 35009:
```
root@gke-us1-us1-default-2022-08-223cced9-74qn:/home/cilium# ss -nltup | grep cilium-agent
udp   UNCONN 0      0           127.0.0.1:35009      0.0.0.0:*    users:(("cilium-agent",pid=1,fd=45))
tcp   LISTEN 0      1024        127.0.0.1:9890       0.0.0.0:*    users:(("cilium-agent",pid=1,fd=7))
tcp   LISTEN 0      1024        127.0.0.1:9878       0.0.0.0:*    users:(("cilium-agent",pid=1,fd=51))
tcp   LISTEN 0      1024        10.1.0.87:4240       0.0.0.0:*    users:(("cilium-agent",pid=1,fd=49))
tcp   LISTEN 0      1024        127.0.0.1:35009      0.0.0.0:*    users:(("cilium-agent",pid=1,fd=39))
tcp   LISTEN 0      1024                *:9091             *:*    users:(("cilium-agent",pid=1,fd=66))
tcp   LISTEN 0      1024                *:9990             *:*    users:(("cilium-agent",pid=1,fd=8))
tcp   LISTEN 0      1024                *:4244             *:*    users:(("cilium-agent",pid=1,fd=77))

```

However the iptables TPROXY-rule is pointing to another port:
```
root@gke-us1-us1-default-2022-08-223cced9-74qn:/home/cilium# iptables -t mangle -nvL | grep cilium-dns-egress
   64  3840 TPROXY     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0xa9330200 /* cilium: TPROXY to host cilium-dns-egress proxy */ TPROXY redirect 127.0.0.1:13225 mark 0x200/0xffffffff
90913 9181K TPROXY     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match 0xa9330200 /* cilium: TPROXY to host cilium-dns-egress proxy */ TPROXY redirect 127.0.0.1:13225 mark 0x200/0xffffffff

```

In the proxy_ports_state.json file we have the "iptables-port" listed:
```
root@gke-us1-us1-default-2022-08-223cced9-74qn:/home/cilium# cat /var/run/cilium/state/proxy_ports_state.json
{"cilium-dns-egress":{"type":"dns","ingress":false,"port":13225}}
```

There is some weird things going on in the logs that I can't quite understand:
`time="2024-11-13T06:10:58Z" level=info msg="Reusing previous DNS proxy port: 35009" subsys=daemon` This is presumably the port the dnsproxy ran on before the cilium pod got restarted.
`time="2024-11-13T06:11:00Z" level=info msg="Adding new proxy port rules for cilium-dns-egress:35009" id=cilium-dns-egress subsys=proxy` This feels normal to me.
However, a few seconds later we get this in the logs:
`time="2024-11-13T06:11:03Z" level=info msg="Adding new proxy port rules for cilium-dns-egress:0" id=cilium-dns-egress subsys=proxy`
And then:
`time="2024-11-13T06:11:03Z" level=info msg="Adding new proxy port rules for cilium-dns-egress:13225" id=cilium-dns-egress subsys=proxy`

I have done some digging into the code. (caveat, I'm not the worlds best programmer and I'm not entirely familiar with the cilium codebase, but here's what I gathered)
1. The log message "Adding new proxy port rules for..." Comes from `pkg/proxy/proxy.go` on line 247 in the function `*Proxy.ackProxyPort`. This function is only called from the exported function `*Proxy.AckProxyPort`
2. `*Proxy.AckProxyPort` is called from `daemon/cmd/fqdn.go` on line 179 in the function `*Daemon.updateDNSDatapathRules` (It's also called from the `ciliumenvoyconfig` package, but I think that is irrelevant in this case.
3. `*Daemon.updateDNSDatapathRules` is called from `daemon/cmd/daemon.go` on line 871 in the function `newDaemon`.
4. `newDaemon`  is called from `daemon/cmd/daemon_main.go` on line 1740 in the `newDaemonPromise` function
5. This is called(?) through the `cell.Provide` var in `daemon/cmd/daemon_main.go` on line 1633. But this is where it gets too hairy for me to follow due to my limited knowledge.

### How can we reproduce the issue?

We haven't been able to reproduce this ourselves, the only time we see it happening is when a node scale down fails and the node gets reinstated.

### Cilium Version

 miono@laima:~$ cilium -n flux version
cilium-cli: v0.16.20 compiled with go1.23.2 on linux/amd64
cilium image (default): v1.16.3
cilium image (stable): v1.16.3
cilium image (running): 1.16.3

### Kernel Version

Linux gke-us1-us1-default-2022-08-223cced9-74qn 6.1.100+ #1 SMP PREEMPT_DYNAMIC Sat Aug 24 16:19:44 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.30.6-dispatcher
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.5-gke.1014003

### Regression

We saw these issues appearing after upgrading kubernetes to 1.30 and cilium to 1.16. We had failed node scale downs previously too, without these problems occuring.

### Sysdump

This would leak quite a lot of internal information, please advise if there are some specific part(s) of the sysdump you would need and I can try to scrub the internal data from the files and provide them.

### Relevant log output

```shell
time="2024-11-13T06:10:58Z" level=info msg="Reusing previous DNS proxy port: 35009" subsys=daemon
time="2024-11-13T06:11:00Z" level=info msg="Adding new proxy port rules for cilium-dns-egress:35009" id=cilium-dns-egress subsys=proxy
time="2024-11-13T06:11:03Z" level=info msg="Adding new proxy port rules for cilium-dns-egress:0" id=cilium-dns-egress subsys=proxy
time="2024-11-13T06:11:03Z" level=info msg="Adding new proxy port rules for cilium-dns-egress:13225" id=cilium-dns-egress subsys=proxy
```

### Anything else?

_No response_

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jrajahalme**
Endpoint regeneration can fail for many reasons, only one of which is Envoy NACKing the listener configuration. Previously it was possible for a proxy port (e.g., DNS proxy port) to be released (and subsequently reallocated) if endpoint regeneration adding a new redirect (such as endpoint restore on agent restart) happened to fail for any reason. Handle proxy port ACK/NACK directly with an AddListener callback and only reset the proxy port if there are no redirects on the port and a NACK was received. Since envoy.AddListener is not used for DNS proxy redirects, it follows that DNS proxy port is now never reset. The AddListener callback allows to keep even newly configured redirects if the regeneration failure reason is not a NACK from Envoy. This helps reduce churn on Envoy listener configuration and the associated datapath proxy port redirection when endpoint regeneration fails for other reasons than Envoy Listener NACK.

To make the AddListener callback work we had to add a separate mutex for the proxy ports, so that a proxy mutex can be held without holding the proxy ports mutex while calling AddListener with a callback that then needs to take the proxy ports mutex. This also happens to solve a latent deadlock bug in CEC parser that also needs to take the mutex for acknowledging a proxy port. In this case we had different locking order for the `Proxy.mutex` and `xdsServer.mutex` in two different code paths:

- CEC parser via `upsertListener()`
  1. takes `xdsServer.mutex`
  2. takes `Proxy.mutex` in the callback via `AckProxyPort()`
- Endpoint redirect creation:
  1. takes `Proxy.mutex` to create a new redirect
  2. calls `AddListener()` which locks `xdsServer.mutex`

With the new `Proxy.proxyPorts.mutex` the above is modified so that `AckProxyPort()` no longer needs to take `Proxy.mutex` (but `Proxy.proxyPorts.mutex` instead), and on the latter path `AddListener()` is called without holding the new `Proxy.proxyPorts.mutex` which can then be taken in the callback function as needed.

Fixes: #36063

```release-note
DNS proxy port is no longer released when endpoint with a DNS policy fails to regenerate successfully.
A potential deadlock between CEC/CCEC parser and endpoint policy update is removed.
```

### CODE REVIEW

**Review by nebril — APPROVED** [review]

**Review by sayboras — APPROVED** [review]

**Comment by jrajahalme** [comment]
Split the last commit to highlight the new `pkg/proxy/proxyports` package.

**Review by tommyp1ckles — APPROVED** [review]
Approved for @cilium/cli

File: pkg/envoy/embedded_envoy.go [hunk 1]
```diff
@@ -124,7 +124,15 @@ func startEmbeddedEnvoy(config embeddedEnvoyConfig) (*EmbeddedEnvoy, error) {
...
 	}
 
-	bootstrapFilePath := filepath.Join(config.runDir, "envoy", "bootstrap.pb")
+	bootstrapDir := filepath.Join(config.runDir, "envoy")
+
+	// make sure envoy dir exists
+	os.Mkdir(bootstrapDir, 0777)
+
+	// Make sure sockets dir exists
+	os.Mkdir(GetSocketDir(config.runDir), 0777)
```
Comment (joestringer) [inline pkg/envoy/embedded_envoy.go:133]: @jrajahalme should this use `defaults.RuntimePathRights` instead (`0775`, ie avoid write access for every user on the node, given that this code runs in production environments)?

I briefly looked at proposing the change myself, but the commit seems to suggest that some magic is necessary in order to run the corresponding tests. Not sure how I would validate that this doesn't immediately break the test again.
