### PR TITLE
Misc test & debugging improvements

### LINKED ISSUE #2859: When BPF verification fails, the files should remain for debugging (if debug is enabled)
When we get into a state where the BPF code is generated but cannot be verified, it seems that the ${EPID}_next/ directory is cleaned up, so we don't have access to the binaries or preprocesed source to easily debug:

```
cilium-master cilium $ cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY        LABELS (source:key[=value])   IPv6                 IPv4           STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                         
29898      Enabled            Enabled           40305           reserved:health               f00d::a0f:0:0:74ca   10.11.242.54   ready                  
56326      Enabled            Enabled           <no label id>   no labels                     f00d::a0f:0:0:dc06   10.11.129.91   waiting-for-identity   
```
```
cilium-master cilium $ cilium endpoint log 56326
Timestamp              Status    State                  Message
2018-02-16T22:31:58Z   Failure   waiting-for-identity   Error regenerating endpoint: error: "exit status 1" command output: "Join EP id=/var/run/cilium/state/56326_next ifname=lxcce3f4\nkernel version:  Linux cilium-master 4.16.0-rc1+ #43 SMP Wed Feb 14 13:35:46 PST 2018 x86_64 x86_64 x86_64 GNU/Linux\nclang version:  clang version 3.8.1 (tags/RELEASE_381/final) Target: x86_64-unknown-linux-gnu Thread model: posix InstalledDir: /usr/local/clang/bin\n'probe' is not a recognized processor for this target (ignoring processor)\n'probe' is not a recognized processor for this target (ignoring processor)\n'probe' is not a recognized processor for this target (ignoring processor)\n'probe' is not a recognized processor for this target (ignoring processor)\n\nProg section '1/0xdc06' rejected: Invalid argument (22)!\n - Type:         3\n - Instructions: 2381 (0 over limit)\n - License:      GPL\n\nVerifier analysis:\n\nSkipped 775737 bytes, use 'verb' option for the full verbose log.\n[...]\nfrom 402 to 1563: R0=inv(id=0,umax_value=9223372036854775807,var_off=(0x0; 0x7fffffffffffffff)) R1=inv0 R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umin_value=14,umax_value=74,var_off=(0x2; 0x7c)) R8=inv0 R9=inv4294967159 R10=fp0,call_-1 fp-160=0 fp-168=0\n1563: (7b) *(u64 *)(r10 -296) = r7\n1564: (b7) r1 = 8\n1565: (6b) *(u16 *)(r10 -104) = r1\n1566: (b7) r1 = 0\n1567: (7b) *(u64 *)(r10 -248) = r1\n1568: (b7) r7 = 0\n1569: (b7) r1 = 0\n1570: (7b) *(u64 *)(r10 -288) = r1\n1571: (05) goto pc-1380\n192: (7b) *(u64 *)(r10 -272) = r7\n193: (69) r8 = *(u16 *)(r10 -104)\n194: (61) r1 = *(u32 *)(r10 -112)\n195: (7b) *(u64 *)(r10 -280) = r1\n196: (69) r9 = *(u16 *)(r10 -102)\n197: (61) r7 = *(u32 *)(r10 -108)\n198: (bf) r1 = r6\n199: (85) call bpf_get_hash_recalc#34\n200: (b7) r1 = 2\n201: (73) *(u8 *)(r10 -48) = r1\n202: (b7) r1 = 44\n203: (73) *(u8 *)(r10 -47) = r1\n204: (b7) r1 = 56326\n205: (6b) *(u16 *)(r10 -46) = r1\n206: (63) *(u32 *)(r10 -44) = r0\n207: (63) *(u32 *)(r10 -40) = r7\n208: (dc) r9 = be32 r9\n209: (18) r1 = 0xffff0000\n211: (5f) r9 &= r1\n212: (79) r1 = *(u64 *)(r10 -280)\n213: (63) *(u32 *)(r10 -36) = r1\n214: (dc) r8 = be16 r8\n215: (4f) r9 |= r8\n216: (63) *(u32 *)(r10 -32) = r9\n217: (bf) r4 = r10\n218: (07) r4 += -48\n219: (bf) r1 = r6\n220: (18) r2 = 0xffff8bf29add6800\n222: (18) r3 = 0xffffffff\n224: (b7) r5 = 20\n225: (85) call bpf_perf_event_output#25\n226: safe\n\nfrom 401 to 1036: R0=inv(id=0,umax_value=9223372036854775807,var_off=(0x0; 0x7fffffffffffffff)) R1=inv(id=0,umin_value=11,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umin_value=14,umax_value=74,var_off=(0x2; 0x7c)) R8=inv0 R9=inv4294967159 R10=fp0,call_-1 fp-160=0 fp-168=0\n1036: (7b) *(u64 *)(r10 -296) = r7\n1037: (07) r1 += -11\n1038: (25) if r1 > 0x1 goto pc+529\n R0=inv(id=0,umax_value=9223372036854775807,var_off=(0x0; 0x7fffffffffffffff)) R1=inv(id=0,umax_value=1,var_off=(0x0; 0x1)) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umin_value=14,umax_value=74,var_off=(0x2; 0x7c)) R8=inv0 R9=inv4294967159 R10=fp0,call_-1 fp-160=0 fp-168=0\n1039: safe\n\nfrom 1038 to 1568: safe\n\nfrom 398 to 1033: safe\n\nfrom 386 to 2095: safe\n\nfrom 154 to 357: R1=inv17 R2=inv(id=0,umax_value=60,var_off=(0x0; 0x3c)) R6=ctx(id=0,off=0,imm=0) R7=pkt(id=0,off=0,r=34,imm=0) R8=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R9=inv(id=0,umin_value=14,umax_value=74,var_off=(0x2; 0x7c)) R10=fp0,call_-1 fp-160=0 fp-168=0\n357: (7b) *(u64 *)(r10 -256) = r2\n358: (7b) *(u64 *)(r10 -264) = r8\n359: (b7) r8 = 0\n360: (73) *(u8 *)(r10 -99) = r8\n361: (bf) r3 = r10\n362: (07) r3 += -104\n363: (bf) r1 = r6\n364: (bf) r2 = r9\n365: (7b) *(u64 *)(r10 -296) = r9\n366: (b7) r4 = 4\n367: (85) call bpf_skb_load_bytes#26\n368: (b7) r1 = 1\n369: (7b) *(u64 *)(r10 -248) = r1\n370: (b7) r1 = 6\n371: (7b) *(u64 *)(r10 -288) = r1\n372: (b7) r7 = 32\n373: (18) r9 = 0xffffff79\n375: (67) r0 <<= 32\n376: (c7) r0 s>>= 32\n377: (6d) if r8 s> r0 goto pc+1717\n R0=inv(id=0,umax_value=9223372036854775807,var_off=(0x0; 0x7fffffffffffffff)) R1=inv6 R6=ctx(id=0,off=0,imm=0) R7=inv32 R8=inv0 R9=inv4294967161 R10=fp0,call_-1 fp-160=0 fp-168=0\n378: (05) goto pc-187\n192: (7b) *(u64 *)(r10 -272) = r7\n193: (69) r8 = *(u16 *)(r10 -104)\n194: (61) r1 = *(u32 *)(r10 -112)\n195: (7b) *(u64 *)(r10 -280) = r1\n196: (69) r9 = *(u16 *)(r10 -102)\n197: (61) r7 = *(u32 *)(r10 -108)\n198: (bf) r1 = r6\n199: (85) call bpf_get_hash_recalc#34\n200: (b7) r1 = 2\n201: (73) *(u8 *)(r10 -48) = r1\n202: (b7) r1 = 44\n203: (73) *(u8 *)(r10 -47) = r1\n204: (b7) r1 = 56326\n205: (6b) *(u16 *)(r10 -46) = r1\n206: (63) *(u32 *)(r10 -44) = r0\n207: (63) *(u32 *)(r10 -40) = r7\n208: (dc) r9 = be32 r9\n209: (18) r1 = 0xffff0000\n211: (5f) r9 &= r1\n212: (79) r1 = *(u64 *)(r10 -280)\n213: (63) *(u32 *)(r10 -36) = r1\n214: (dc) r8 = be16 r8\n215: (4f) r9 |= r8\n216: (63) *(u32 *)(r10 -32) = r9\n217: (bf) r4 = r10\n218: (07) r4 += -48\n219: (bf) r1 = r6\n220: (18) r2 = 0xffff8bf29add6800\n222: (18) r3 = 0xffffffff\n224: (b7) r5 = 20\n225: (85) call bpf_perf_event_output#25\n226: safe\n\nfrom 377 to 2095: safe\n\nfrom 148 to 352: safe\n\nfrom 110 to 2095: safe\nprocessed 13888 insns (limit 131072), stack depth 320\n\nError filling program arrays!\nNote: 8 bytes struct bpf_elf_map fixup performed due to size mismatch!\n"
2018-02-16T22:31:58Z   Warning   waiting-for-identity   Skipped invalid state transition to ready due to: Completed endpoint regeneration with no pending regeneration requests
2018-02-16T22:31:56Z   OK        waiting-for-identity   Update endpoint from API PATCH
```
```
cilium-master cilium $ ls /var/run/cilium/state/56326/
```
```
cilium-master cilium $ ls /var/run/cilium/state/56326_next
ls: cannot access '/var/run/cilium/state/56326_next': No such file or directory
```
```
cilium-master cilium $ cilium config
Conntrack                Enabled
ConntrackAccounting      Enabled
ConntrackLocal           Disabled
Debug                    Enabled
DropNotification         Enabled
PolicyTracing            Disabled
TraceNotification        Enabled
k8s-configuration        
k8s-endpoint             
PolicyEnforcement        always
MonitorNumPages          64
```
```
cilium-master cilium $ cilium endpoint config 56326
Conntrack                Enabled
ConntrackAccounting      Enabled
ConntrackLocal           Disabled
Debug                    Enabled
DropNotification         Enabled
EgressPolicy             Enabled
IngressPolicy            Enabled
NAT46                    Disabled
TraceNotification        Enabled
```

Also, should the state be `waiting-for-identity` if it managed to get to BPF code generation?
There doesn't appear to be any controller running for this endpoint either:

```
cilium-master cilium $ cilium status --all-controllers
KVStore:                Ok         Consul: 172.17.0.2:8300
ContainerRuntime:       Ok         
Kubernetes:             Disabled   
Cilium:                 Ok         OK
NodeMonitor:            Listening for events on 2 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok   
IPv4 address pool:      3/65535 allocated
IPv6 address pool:      2/65535 allocated
Controller Status:      3/3 healthy
  Name                               Last success   Last error   Count   Message
  kvstore-lease-keepalive            58s ago        never        0       no error   
  resolve-identity-29898             55s ago        never        0       no error   
  sync-identity-to-k8s-pod (29898)   55s ago        never        0       no error   
Cluster health:   1/1 reachable   (2018-02-16T14:41:33-08:00)
```

### PR DESCRIPTION
**Pull request by joestringer**
* Fix #2859, keep generated BPF programs that cannot be inserted around for debugging
* Add a 'make clean' target to `test/`
* Remove an unnecessary sprintf in `test/runtime/lb.go`

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

File: pkg/endpoint/policy.go [hunk 1]
```diff
@@ -718,7 +718,9 @@ func (e *Endpoint) regenerate(owner Owner, reason string) (retErr error) {
 
 	revision, err := e.regenerateBPF(owner, tmpDir, reason)
 	if err != nil {
-		os.RemoveAll(tmpDir)
+		failDir := tmpDir + "_fail"
+		os.RemoveAll(failDir)
+		os.Rename(tmpDir, failDir)
 		return err
 	}
```
Comment (joestringer) [inline pkg/endpoint/policy.go]: On success, we should probably remove these failed objects

Comment (joestringer) [reply pkg/endpoint/policy.go]: Done

**Comment by joestringer** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]
