### PR TITLE
bgpv1: Fix data race in bgppSelection

### LINKED ISSUE #33898: [DATA RACE]: github.com/cilium/cilium/pkg/bgpv1/agent.(*Controller).bgppSelection()
```
2024-07-18T14:43:44.508361985Z Read at 0x00c00034e0f0 by goroutine 3926:
2024-07-18T14:43:44.508366724Z   github.com/cilium/cilium/pkg/bgpv1/agent.(*Controller).bgppSelection()
2024-07-18T14:43:44.508371343Z       /go/src/github.com/cilium/cilium/pkg/bgpv1/agent/controller.go:335 +0xa8
2024-07-18T14:43:44.508375681Z   github.com/cilium/cilium/pkg/bgpv1/agent.(*Controller).Reconcile()
2024-07-18T14:43:44.508380009Z       /go/src/github.com/cilium/cilium/pkg/bgpv1/agent/controller.go:226 +0x51
2024-07-18T14:43:44.508384908Z   github.com/cilium/cilium/pkg/bgpv1/agent.(*Controller).Run()
2024-07-18T14:43:44.508389447Z       /go/src/github.com/cilium/cilium/pkg/bgpv1/agent/controller.go:201 +0x2d5
2024-07-18T14:43:44.508393815Z   github.com/cilium/cilium/pkg/bgpv1/agent.NewController.func3()
2024-07-18T14:43:44.508398203Z       /go/src/github.com/cilium/cilium/pkg/bgpv1/agent/controller.go:168 +0x1cd
2024-07-18T14:43:44.508402671Z   github.com/cilium/hive/job.(*jobOneShot).start()
2024-07-18T14:43:44.508407149Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/job/oneshot.go:136 +0x847
2024-07-18T14:43:44.508411498Z   github.com/cilium/hive/job.(*group).Start.func1.gowrap1()
2024-07-18T14:43:44.508415936Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/job/job.go:159 +0x131
2024-07-18T14:43:44.508419994Z 
2024-07-18T14:43:44.508424432Z Previous write at 0x00c00034e0f0 by goroutine 3925:
2024-07-18T14:43:44.508428860Z   github.com/cilium/cilium/pkg/bgpv1/agent.NewController.func2()
2024-07-18T14:43:44.508433509Z       /go/src/github.com/cilium/cilium/pkg/bgpv1/agent/controller.go:147 +0x171
2024-07-18T14:43:44.508482751Z   github.com/cilium/hive/job.(*jobOneShot).start()
2024-07-18T14:43:44.508489343Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/job/oneshot.go:136 +0x847
2024-07-18T14:43:44.508507006Z   github.com/cilium/hive/job.(*group).Start.func1.gowrap1()
2024-07-18T14:43:44.508511635Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/job/job.go:159 +0x131
2024-07-18T14:43:44.508515812Z 
2024-07-18T14:43:44.508520060Z Goroutine 3926 (running) created at:
2024-07-18T14:43:44.508524488Z   github.com/cilium/hive/job.(*group).Start.func1()
2024-07-18T14:43:44.508528896Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/job/job.go:159 +0x2c4
2024-07-18T14:43:44.508533476Z   runtime/pprof.Do()
2024-07-18T14:43:44.508538154Z       /usr/local/go/src/runtime/pprof/runtime.go:51 +0x117
2024-07-18T14:43:44.508542703Z   github.com/cilium/hive/job.(*group).Start()
2024-07-18T14:43:44.508547321Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/job/job.go:158 +0x353
2024-07-18T14:43:44.508551659Z   github.com/cilium/hive/cell.(*DefaultLifecycle).Start()
2024-07-18T14:43:44.508556708Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/cell/lifecycle.go:107 +0x46a
2024-07-18T14:43:44.508561157Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.508565616Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.508569883Z   fmt.Fscanf()
2024-07-18T14:43:44.508574312Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.508578650Z   fmt.Sscanf()
2024-07-18T14:43:44.508583037Z       /usr/local/go/src/fmt/scan.go:114 +0x355
2024-07-18T14:43:44.508587436Z   github.com/cilium/cilium/pkg/bpf.removeUnreachableTailcalls()
2024-07-18T14:43:44.508591634Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:72 +0x22c
2024-07-18T14:43:44.508596092Z   github.com/cilium/cilium/pkg/bpf.LoadCollectionSpec()
2024-07-18T14:43:44.508600481Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:36 +0x64
2024-07-18T14:43:44.508677003Z   github.com/cilium/cilium/pkg/datapath/loader.(*loader).replaceOverlayDatapath()
2024-07-18T14:43:44.508687032Z       /go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:540 +0x305
2024-07-18T14:43:44.508691841Z   github.com/cilium/cilium/pkg/datapath/loader.(*loader).reinitializeOverlay()
2024-07-18T14:43:44.508735783Z       /go/src/github.com/cilium/cilium/pkg/datapath/loader/base.go:304 +0xc10
2024-07-18T14:43:44.508741313Z   github.com/cilium/cilium/pkg/datapath/loader.(*loader).Reinitialize()
2024-07-18T14:43:44.508745451Z       /go/src/github.com/cilium/cilium/pkg/datapath/loader/base.go:520 +0x29b9
2024-07-18T14:43:44.508749689Z   fmt.Fscanf()
2024-07-18T14:43:44.508753867Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.508758185Z   fmt.Sscanf()
2024-07-18T14:43:44.508762523Z       /usr/local/go/src/fmt/scan.go:114 +0x355
2024-07-18T14:43:44.508767101Z   github.com/cilium/cilium/pkg/bpf.removeUnreachableTailcalls()
2024-07-18T14:43:44.508771450Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:72 +0x22c
2024-07-18T14:43:44.508775707Z   github.com/cilium/cilium/pkg/bpf.LoadCollectionSpec()
2024-07-18T14:43:44.508779905Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:36 +0x64
2024-07-18T14:43:44.508784224Z   github.com/cilium/cilium/pkg/datapath/loader.compileAndLoadXDPProg()
2024-07-18T14:43:44.508788661Z       /go/src/github.com/cilium/cilium/pkg/datapath/loader/xdp.go:160 +0x664
2024-07-18T14:43:44.508793210Z   github.com/cilium/cilium/pkg/datapath/loader.(*loader).reinitializeXDPLocked()
2024-07-18T14:43:44.508799943Z       /go/src/github.com/cilium/cilium/pkg/datapath/loader/base.go:352 +0x5c4
2024-07-18T14:43:44.508804501Z   github.com/cilium/cilium/pkg/bpf.LoadCollectionSpec()
2024-07-18T14:43:44.508816544Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:40 +0x77
2024-07-18T14:43:44.508820921Z   fmt.Fscanf()
2024-07-18T14:43:44.508825490Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.508830029Z   fmt.Sscanf()
2024-07-18T14:43:44.508834377Z       /usr/local/go/src/fmt/scan.go:114 +0x355
2024-07-18T14:43:44.514132616Z   github.com/cilium/cilium/pkg/bpf.removeUnreachableTailcalls()
2024-07-18T14:43:44.514146312Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:72 +0x22c
2024-07-18T14:43:44.514151862Z   github.com/cilium/cilium/pkg/bpf.LoadCollectionSpec()
2024-07-18T14:43:44.514157112Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:36 +0x64
2024-07-18T14:43:44.514161810Z   github.com/cilium/cilium/pkg/datapath/loader.compileAndLoadXDPProg()
2024-07-18T14:43:44.514167571Z       /go/src/github.com/cilium/cilium/pkg/datapath/loader/xdp.go:160 +0x664
2024-07-18T14:43:44.514173042Z   github.com/cilium/cilium/pkg/datapath/loader.(*loader).reinitializeXDPLocked()
2024-07-18T14:43:44.514178432Z       /go/src/github.com/cilium/cilium/pkg/datapath/loader/base.go:352 +0x5c4
2024-07-18T14:43:44.514182760Z   github.com/cilium/cilium/pkg/datapath/loader.(*loader).Reinitialize()
2024-07-18T14:43:44.514186777Z       /go/src/github.com/cilium/cilium/pkg/datapath/loader/base.go:497 +0x2084
2024-07-18T14:43:44.514191135Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.514196195Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.514201255Z   fmt.Fscanf()
2024-07-18T14:43:44.514206534Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.514211824Z   fmt.Sscanf()
2024-07-18T14:43:44.514217033Z       /usr/local/go/src/fmt/scan.go:114 +0x7c4
2024-07-18T14:43:44.514222464Z   github.com/cilium/cilium/pkg/bpf.iproute2Compat()
2024-07-18T14:43:44.514227353Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:220 +0x6a0
2024-07-18T14:43:44.514231832Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.514236681Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.514292815Z   fmt.Fscanf()
2024-07-18T14:43:44.514300890Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.514305810Z   fmt.Sscanf()
2024-07-18T14:43:44.514310378Z       /usr/local/go/src/fmt/scan.go:114 +0x7c4
2024-07-18T14:43:44.514314926Z   github.com/cilium/cilium/pkg/bpf.iproute2Compat()
2024-07-18T14:43:44.514319315Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:220 +0x6a0
2024-07-18T14:43:44.514323983Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.514328813Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.514333872Z   fmt.Fscanf()
2024-07-18T14:43:44.514339122Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.514343981Z   fmt.Sscanf()
2024-07-18T14:43:44.514349431Z       /usr/local/go/src/fmt/scan.go:114 +0x7c4
2024-07-18T14:43:44.514354621Z   github.com/cilium/cilium/pkg/bpf.iproute2Compat()
2024-07-18T14:43:44.514359831Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:220 +0x6a0
2024-07-18T14:43:44.514364619Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.514369318Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.514373886Z   fmt.Fscanf()
2024-07-18T14:43:44.514378305Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.514382903Z   fmt.Sscanf()
2024-07-18T14:43:44.514387422Z       /usr/local/go/src/fmt/scan.go:114 +0x7c4
2024-07-18T14:43:44.514392351Z   github.com/cilium/cilium/pkg/bpf.iproute2Compat()
2024-07-18T14:43:44.514396659Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:220 +0x6a0
2024-07-18T14:43:44.514401458Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.514419262Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.514424531Z   fmt.Fscanf()
2024-07-18T14:43:44.514429040Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.514433598Z   fmt.Sscanf()
2024-07-18T14:43:44.514438196Z       /usr/local/go/src/fmt/scan.go:114 +0x7c4
2024-07-18T14:43:44.514443216Z   github.com/cilium/cilium/pkg/bpf.iproute2Compat()
2024-07-18T14:43:44.514448305Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:220 +0x6a0
2024-07-18T14:43:44.514453545Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.514458875Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.514464095Z   fmt.Fscanf()
2024-07-18T14:43:44.514468684Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.514473071Z   fmt.Sscanf()
2024-07-18T14:43:44.514477620Z       /usr/local/go/src/fmt/scan.go:114 +0x7c4
2024-07-18T14:43:44.514487248Z   github.com/cilium/cilium/pkg/bpf.iproute2Compat()
2024-07-18T14:43:44.514491947Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:220 +0x6a0
2024-07-18T14:43:44.514496686Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.514501805Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.514507155Z   fmt.Fscanf()
2024-07-18T14:43:44.514512014Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.514517264Z   fmt.Sscanf()
2024-07-18T14:43:44.514522604Z       /usr/local/go/src/fmt/scan.go:114 +0x7c4
2024-07-18T14:43:44.514528074Z   github.com/cilium/cilium/pkg/bpf.iproute2Compat()
2024-07-18T14:43:44.514532874Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:220 +0x6a0
2024-07-18T14:43:44.514537382Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.514541850Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.514546980Z   fmt.Fscanf()
2024-07-18T14:43:44.514552299Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.514557529Z   fmt.Sscanf()
2024-07-18T14:43:44.514562338Z       /usr/local/go/src/fmt/scan.go:114 +0x7c4
2024-07-18T14:43:44.514567338Z   github.com/cilium/cilium/pkg/bpf.iproute2Compat()
2024-07-18T14:43:44.514572327Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:220 +0x6a0
2024-07-18T14:43:44.514577557Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.514582566Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.514587916Z   fmt.Fscanf()
2024-07-18T14:43:44.514593436Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.514598636Z   fmt.Sscanf()
2024-07-18T14:43:44.514604066Z       /usr/local/go/src/fmt/scan.go:114 +0x7c4
2024-07-18T14:43:44.514608925Z   github.com/cilium/cilium/pkg/bpf.iproute2Compat()
2024-07-18T14:43:44.514613814Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:220 +0x6a0
2024-07-18T14:43:44.514619044Z   github.com/cilium/cilium/pkg/bpf.LoadCollectionSpec()
2024-07-18T14:43:44.514624044Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:40 +0x77
2024-07-18T14:43:44.514629374Z   fmt.Fscanf()
2024-07-18T14:43:44.514634673Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.514640074Z   fmt.Sscanf()
2024-07-18T14:43:44.514671993Z       /usr/local/go/src/fmt/scan.go:114 +0x355
2024-07-18T14:43:44.514679197Z   github.com/cilium/cilium/pkg/bpf.removeUnreachableTailcalls()
2024-07-18T14:43:44.514684015Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:72 +0x22c
2024-07-18T14:43:44.514688895Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.514693744Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.514698182Z   fmt.Fscanf()
2024-07-18T14:43:44.514703041Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.514715684Z   fmt.Sscanf()
2024-07-18T14:43:44.514720303Z       /usr/local/go/src/fmt/scan.go:114 +0x355
2024-07-18T14:43:44.514725162Z   github.com/cilium/cilium/pkg/bpf.removeUnreachableTailcalls()
2024-07-18T14:43:44.514729811Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:72 +0x22c
2024-07-18T14:43:44.514734129Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.514738928Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.514743396Z   fmt.Fscanf()
2024-07-18T14:43:44.514747915Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.514752493Z   fmt.Sscanf()
2024-07-18T14:43:44.514756972Z       /usr/local/go/src/fmt/scan.go:114 +0x355
2024-07-18T14:43:44.514761520Z   github.com/cilium/cilium/pkg/bpf.removeUnreachableTailcalls()
2024-07-18T14:43:44.514766279Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:72 +0x22c
2024-07-18T14:43:44.514770607Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.514774544Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.514778602Z   fmt.Fscanf()
2024-07-18T14:43:44.514783290Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.514787448Z   fmt.Sscanf()
2024-07-18T14:43:44.514791927Z       /usr/local/go/src/fmt/scan.go:114 +0x355
2024-07-18T14:43:44.514871535Z   github.com/cilium/cilium/pkg/bpf.removeUnreachableTailcalls()
2024-07-18T14:43:44.514881053Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:72 +0x22c
2024-07-18T14:43:44.514886263Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.514890902Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.514895370Z   fmt.Fscanf()
2024-07-18T14:43:44.514900009Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.514904377Z   fmt.Sscanf()
2024-07-18T14:43:44.514909205Z       /usr/local/go/src/fmt/scan.go:114 +0x355
2024-07-18T14:43:44.514914035Z   github.com/cilium/cilium/pkg/bpf.removeUnreachableTailcalls()
2024-07-18T14:43:44.514919164Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:72 +0x22c
2024-07-18T14:43:44.514924103Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.514929233Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.514934152Z   fmt.Fscanf()
2024-07-18T14:43:44.514939432Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.514944862Z   fmt.Sscanf()
2024-07-18T14:43:44.514950062Z       /usr/local/go/src/fmt/scan.go:114 +0x355
2024-07-18T14:43:44.514954380Z   github.com/cilium/cilium/pkg/bpf.removeUnreachableTailcalls()
2024-07-18T14:43:44.514958798Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:72 +0x22c
2024-07-18T14:43:44.514963146Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.514967695Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.514972865Z   fmt.Fscanf()
2024-07-18T14:43:44.514977924Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.514982713Z   fmt.Sscanf()
2024-07-18T14:43:44.514987692Z       /usr/local/go/src/fmt/scan.go:114 +0x355
2024-07-18T14:43:44.514992572Z   github.com/cilium/cilium/pkg/bpf.removeUnreachableTailcalls()
2024-07-18T14:43:44.514997210Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:72 +0x22c
2024-07-18T14:43:44.515002150Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.515006988Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.515012438Z   fmt.Fscanf()
2024-07-18T14:43:44.515017588Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.515023109Z   fmt.Sscanf()
2024-07-18T14:43:44.515028288Z       /usr/local/go/src/fmt/scan.go:114 +0x355
2024-07-18T14:43:44.515033548Z   github.com/cilium/cilium/pkg/bpf.removeUnreachableTailcalls()
2024-07-18T14:43:44.515047314Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:72 +0x22c
2024-07-18T14:43:44.515052203Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.515057533Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.515062642Z   fmt.Fscanf()
2024-07-18T14:43:44.515068022Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.515072731Z   fmt.Sscanf()
2024-07-18T14:43:44.515077159Z       /usr/local/go/src/fmt/scan.go:114 +0x355
2024-07-18T14:43:44.515081928Z   github.com/cilium/cilium/pkg/bpf.removeUnreachableTailcalls()
2024-07-18T14:43:44.515088911Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:72 +0x22c
2024-07-18T14:43:44.515093490Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.515098329Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.515102947Z   fmt.Fscanf()
2024-07-18T14:43:44.515107877Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.515112375Z   fmt.Sscanf()
2024-07-18T14:43:44.515116753Z       /usr/local/go/src/fmt/scan.go:114 +0x355
2024-07-18T14:43:44.515121121Z   github.com/cilium/cilium/pkg/bpf.removeUnreachableTailcalls()
2024-07-18T14:43:44.515125790Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:72 +0x22c
2024-07-18T14:43:44.515130449Z   github.com/cilium/cilium/pkg/bpf.LoadCollectionSpec()
2024-07-18T14:43:44.515135047Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:36 +0x64
2024-07-18T14:43:44.515139716Z   github.com/cilium/cilium/pkg/socketlb.Enable()
2024-07-18T14:43:44.515144265Z       /go/src/github.com/cilium/cilium/pkg/socketlb/socketlb.go:64 +0x210
2024-07-18T14:43:44.515148883Z   github.com/cilium/cilium/pkg/datapath/loader.(*loader).Reinitialize()
2024-07-18T14:43:44.515153572Z       /go/src/github.com/cilium/cilium/pkg/datapath/loader/base.go:487 +0x1fad
2024-07-18T14:43:44.515158060Z   github.com/cilium/cilium/pkg/datapath/orchestrator.(*orchestrator).Reinitialize()
2024-07-18T14:43:44.515162438Z       /go/src/github.com/cilium/cilium/pkg/datapath/orchestrator/orchestrator.go:77 +0x857
2024-07-18T14:43:44.515167077Z   github.com/cilium/cilium/daemon/cmd.(*Daemon).init()
2024-07-18T14:43:44.515171145Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon.go:211 +0x870
2024-07-18T14:43:44.515175012Z   github.com/cilium/cilium/daemon/cmd.newDaemon()
2024-07-18T14:43:44.515178799Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon.go:848 +0x8264
2024-07-18T14:43:44.515224745Z   github.com/cilium/cilium/daemon/cmd.newDaemonPromise.func1()
2024-07-18T14:43:44.515231628Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1740 +0x1e9
2024-07-18T14:43:44.515236397Z   github.com/cilium/hive/cell.Hook.Start()
2024-07-18T14:43:44.515242858Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/cell/lifecycle.go:42 +0x70
2024-07-18T14:43:44.515247707Z   github.com/cilium/hive/cell.(*Hook).Start()
2024-07-18T14:43:44.515253448Z       <autogenerated>:1 +0x1f
2024-07-18T14:43:44.515258228Z   github.com/cilium/hive/cell.(*DefaultLifecycle).Start()
2024-07-18T14:43:44.515263126Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/cell/lifecycle.go:107 +0x46a
2024-07-18T14:43:44.515268046Z   github.com/cilium/hive.(*Hive).Start()
2024-07-18T14:43:44.515272975Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/hive.go:339 +0x192
2024-07-18T14:43:44.515278395Z   github.com/cilium/hive.(*Hive).Run()
2024-07-18T14:43:44.515283384Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/hive.go:229 +0xc9
2024-07-18T14:43:44.515288393Z   github.com/cilium/cilium/daemon/cmd.NewAgentCmd.func1()
2024-07-18T14:43:44.515302149Z       /go/src/github.com/cilium/cilium/daemon/cmd/root.go:40 +0x28f
2024-07-18T14:43:44.515307730Z   github.com/spf13/cobra.(*Command).execute()
2024-07-18T14:43:44.515312238Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:989 +0x1185
2024-07-18T14:43:44.515317027Z   github.com/spf13/cobra.(*Command).ExecuteC()
2024-07-18T14:43:44.515322367Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:1117 +0x657
2024-07-18T14:43:44.515331914Z   github.com/spf13/cobra.(*Command).Execute()
2024-07-18T14:43:44.515336854Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:1041 +0x2e
2024-07-18T14:43:44.515342484Z   github.com/cilium/cilium/daemon/cmd.Execute()
2024-07-18T14:43:44.515347274Z       /go/src/github.com/cilium/cilium/daemon/cmd/root.go:80 +0x12
2024-07-18T14:43:44.515351631Z   main.main()
2024-07-18T14:43:44.515356110Z       /go/src/github.com/cilium/cilium/daemon/main.go:14 +0xa9
2024-07-18T14:43:44.515360228Z 
2024-07-18T14:43:44.515364696Z Goroutine 3925 (running) created at:
2024-07-18T14:43:44.515369485Z   github.com/cilium/hive/job.(*group).Start.func1()
2024-07-18T14:43:44.515374063Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/job/job.go:159 +0x2c4
2024-07-18T14:43:44.515378813Z   runtime/pprof.Do()
2024-07-18T14:43:44.515384042Z       /usr/local/go/src/runtime/pprof/runtime.go:51 +0x117
2024-07-18T14:43:44.515389282Z   github.com/cilium/hive/job.(*group).Start()
2024-07-18T14:43:44.515394051Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/job/job.go:158 +0x353
2024-07-18T14:43:44.515399040Z   github.com/cilium/hive/cell.(*DefaultLifecycle).Start()
2024-07-18T14:43:44.515403939Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/cell/lifecycle.go:107 +0x46a
2024-07-18T14:43:44.515408938Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.515414268Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.515419228Z   fmt.Fscanf()
2024-07-18T14:43:44.515424508Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.515429457Z   fmt.Sscanf()
2024-07-18T14:43:44.515434647Z       /usr/local/go/src/fmt/scan.go:114 +0x355
2024-07-18T14:43:44.515439616Z   github.com/cilium/cilium/pkg/bpf.removeUnreachableTailcalls()
2024-07-18T14:43:44.515444305Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:72 +0x22c
2024-07-18T14:43:44.515449163Z   github.com/cilium/cilium/pkg/bpf.LoadCollectionSpec()
2024-07-18T14:43:44.515454123Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:36 +0x64
2024-07-18T14:43:44.515458812Z   github.com/cilium/cilium/pkg/datapath/loader.(*loader).replaceOverlayDatapath()
2024-07-18T14:43:44.515463240Z       /go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:540 +0x305
2024-07-18T14:43:44.515468510Z   github.com/cilium/cilium/pkg/datapath/loader.(*loader).reinitializeOverlay()
2024-07-18T14:43:44.515473559Z       /go/src/github.com/cilium/cilium/pkg/datapath/loader/base.go:304 +0xc10
2024-07-18T14:43:44.515479029Z   github.com/cilium/cilium/pkg/datapath/loader.(*loader).Reinitialize()
2024-07-18T14:43:44.515483929Z       /go/src/github.com/cilium/cilium/pkg/datapath/loader/base.go:520 +0x29b9
2024-07-18T14:43:44.515488427Z   fmt.Fscanf()
2024-07-18T14:43:44.515492574Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.515497073Z   fmt.Sscanf()
2024-07-18T14:43:44.515501291Z       /usr/local/go/src/fmt/scan.go:114 +0x355
2024-07-18T14:43:44.515505518Z   github.com/cilium/cilium/pkg/bpf.removeUnreachableTailcalls()
2024-07-18T14:43:44.515509627Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:72 +0x22c
2024-07-18T14:43:44.515520978Z   github.com/cilium/cilium/pkg/bpf.LoadCollectionSpec()
2024-07-18T14:43:44.515525046Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:36 +0x64
2024-07-18T14:43:44.515529223Z   github.com/cilium/cilium/pkg/datapath/loader.compileAndLoadXDPProg()
2024-07-18T14:43:44.515533110Z       /go/src/github.com/cilium/cilium/pkg/datapath/loader/xdp.go:160 +0x664
2024-07-18T14:43:44.515537910Z   github.com/cilium/cilium/pkg/datapath/loader.(*loader).reinitializeXDPLocked()
2024-07-18T14:43:44.515543370Z       /go/src/github.com/cilium/cilium/pkg/datapath/loader/base.go:352 +0x5c4
2024-07-18T14:43:44.515548459Z   github.com/cilium/cilium/pkg/bpf.LoadCollectionSpec()
2024-07-18T14:43:44.515554220Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:40 +0x77
2024-07-18T14:43:44.515559329Z   fmt.Fscanf()
2024-07-18T14:43:44.515564469Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.515569107Z   fmt.Sscanf()
2024-07-18T14:43:44.515573466Z       /usr/local/go/src/fmt/scan.go:114 +0x355
2024-07-18T14:43:44.515578365Z   github.com/cilium/cilium/pkg/bpf.removeUnreachableTailcalls()
2024-07-18T14:43:44.515583294Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:72 +0x22c
2024-07-18T14:43:44.515588103Z   github.com/cilium/cilium/pkg/bpf.LoadCollectionSpec()
2024-07-18T14:43:44.515592591Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:36 +0x64
2024-07-18T14:43:44.515596999Z   github.com/cilium/cilium/pkg/datapath/loader.compileAndLoadXDPProg()
2024-07-18T14:43:44.515601648Z       /go/src/github.com/cilium/cilium/pkg/datapath/loader/xdp.go:160 +0x664
2024-07-18T14:43:44.515606297Z   github.com/cilium/cilium/pkg/datapath/loader.(*loader).reinitializeXDPLocked()
2024-07-18T14:43:44.515610745Z       /go/src/github.com/cilium/cilium/pkg/datapath/loader/base.go:352 +0x5c4
2024-07-18T14:43:44.515615344Z   github.com/cilium/cilium/pkg/datapath/loader.(*loader).Reinitialize()
2024-07-18T14:43:44.515619952Z       /go/src/github.com/cilium/cilium/pkg/datapath/loader/base.go:497 +0x2084
2024-07-18T14:43:44.515624511Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.515629059Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.515633378Z   fmt.Fscanf()
2024-07-18T14:43:44.515637576Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.515675015Z   fmt.Sscanf()
2024-07-18T14:43:44.515682849Z       /usr/local/go/src/fmt/scan.go:114 +0x7c4
2024-07-18T14:43:44.515686777Z   github.com/cilium/cilium/pkg/bpf.iproute2Compat()
2024-07-18T14:43:44.515691105Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:220 +0x6a0
2024-07-18T14:43:44.515695323Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.515699812Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.515703989Z   fmt.Fscanf()
2024-07-18T14:43:44.515708548Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.515712756Z   fmt.Sscanf()
2024-07-18T14:43:44.515717424Z       /usr/local/go/src/fmt/scan.go:114 +0x7c4
2024-07-18T14:43:44.515722023Z   github.com/cilium/cilium/pkg/bpf.iproute2Compat()
2024-07-18T14:43:44.515730769Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:220 +0x6a0
2024-07-18T14:43:44.515736079Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.515740888Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.515745757Z   fmt.Fscanf()
2024-07-18T14:43:44.515750236Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.515754654Z   fmt.Sscanf()
2024-07-18T14:43:44.515759222Z       /usr/local/go/src/fmt/scan.go:114 +0x7c4
2024-07-18T14:43:44.515763590Z   github.com/cilium/cilium/pkg/bpf.iproute2Compat()
2024-07-18T14:43:44.515777105Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:220 +0x6a0
2024-07-18T14:43:44.515782486Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.515787845Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.515792425Z   fmt.Fscanf()
2024-07-18T14:43:44.515797283Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.515801682Z   fmt.Sscanf()
2024-07-18T14:43:44.515806079Z       /usr/local/go/src/fmt/scan.go:114 +0x7c4
2024-07-18T14:43:44.515810768Z   github.com/cilium/cilium/pkg/bpf.iproute2Compat()
2024-07-18T14:43:44.515815307Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:220 +0x6a0
2024-07-18T14:43:44.515820006Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.515825176Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.515830295Z   fmt.Fscanf()
2024-07-18T14:43:44.515835345Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.515840354Z   fmt.Sscanf()
2024-07-18T14:43:44.515845954Z       /usr/local/go/src/fmt/scan.go:114 +0x7c4
2024-07-18T14:43:44.515851074Z   github.com/cilium/cilium/pkg/bpf.iproute2Compat()
2024-07-18T14:43:44.515856203Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:220 +0x6a0
2024-07-18T14:43:44.515860692Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.515865030Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.515869478Z   fmt.Fscanf()
2024-07-18T14:43:44.515874538Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.515879948Z   fmt.Sscanf()
2024-07-18T14:43:44.515885037Z       /usr/local/go/src/fmt/scan.go:114 +0x7c4
2024-07-18T14:43:44.515889746Z   github.com/cilium/cilium/pkg/bpf.iproute2Compat()
2024-07-18T14:43:44.515894314Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:220 +0x6a0
2024-07-18T14:43:44.515899364Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.515904614Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.515909623Z   fmt.Fscanf()
2024-07-18T14:43:44.515914983Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.515920132Z   fmt.Sscanf()
2024-07-18T14:43:44.515925262Z       /usr/local/go/src/fmt/scan.go:114 +0x7c4
2024-07-18T14:43:44.515930572Z   github.com/cilium/cilium/pkg/bpf.iproute2Compat()
2024-07-18T14:43:44.515935151Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:220 +0x6a0
2024-07-18T14:43:44.515939759Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.515944508Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.515950148Z   fmt.Fscanf()
2024-07-18T14:43:44.515954898Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.515960017Z   fmt.Sscanf()
2024-07-18T14:43:44.515965117Z       /usr/local/go/src/fmt/scan.go:114 +0x7c4
2024-07-18T14:43:44.515970206Z   github.com/cilium/cilium/pkg/bpf.iproute2Compat()
2024-07-18T14:43:44.515975045Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:220 +0x6a0
2024-07-18T14:43:44.515979584Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.515984383Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.515988791Z   fmt.Fscanf()
2024-07-18T14:43:44.515993459Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.515997837Z   fmt.Sscanf()
2024-07-18T14:43:44.516002186Z       /usr/local/go/src/fmt/scan.go:114 +0x7c4
2024-07-18T14:43:44.516006314Z   github.com/cilium/cilium/pkg/bpf.iproute2Compat()
2024-07-18T14:43:44.516010341Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:220 +0x6a0
2024-07-18T14:43:44.516014298Z   github.com/cilium/cilium/pkg/bpf.LoadCollectionSpec()
2024-07-18T14:43:44.516018346Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:40 +0x77
2024-07-18T14:43:44.516029537Z   fmt.Fscanf()
2024-07-18T14:43:44.516033524Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.516037291Z   fmt.Sscanf()
2024-07-18T14:43:44.516041129Z       /usr/local/go/src/fmt/scan.go:114 +0x355
2024-07-18T14:43:44.516045306Z   github.com/cilium/cilium/pkg/bpf.removeUnreachableTailcalls()
2024-07-18T14:43:44.516049424Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:72 +0x22c
2024-07-18T14:43:44.516053312Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.516057720Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.516062409Z   fmt.Fscanf()
2024-07-18T14:43:44.516066606Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.516070664Z   fmt.Sscanf()
2024-07-18T14:43:44.516074792Z       /usr/local/go/src/fmt/scan.go:114 +0x355
2024-07-18T14:43:44.516078909Z   github.com/cilium/cilium/pkg/bpf.removeUnreachableTailcalls()
2024-07-18T14:43:44.516083157Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:72 +0x22c
2024-07-18T14:43:44.516087104Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.516091272Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.516095600Z   fmt.Fscanf()
2024-07-18T14:43:44.516099488Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.516103515Z   fmt.Sscanf()
2024-07-18T14:43:44.516107613Z       /usr/local/go/src/fmt/scan.go:114 +0x355
2024-07-18T14:43:44.516111660Z   github.com/cilium/cilium/pkg/bpf.removeUnreachableTailcalls()
2024-07-18T14:43:44.516115737Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:72 +0x22c
2024-07-18T14:43:44.516119665Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.516123693Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.516127740Z   fmt.Fscanf()
2024-07-18T14:43:44.516131998Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.516137809Z   fmt.Sscanf()
2024-07-18T14:43:44.516142037Z       /usr/local/go/src/fmt/scan.go:114 +0x355
2024-07-18T14:43:44.516146215Z   github.com/cilium/cilium/pkg/bpf.removeUnreachableTailcalls()
2024-07-18T14:43:44.516150402Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:72 +0x22c
2024-07-18T14:43:44.516154671Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.516158949Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.516163136Z   fmt.Fscanf()
2024-07-18T14:43:44.516193784Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.516198362Z   fmt.Sscanf()
2024-07-18T14:43:44.516202570Z       /usr/local/go/src/fmt/scan.go:114 +0x355
2024-07-18T14:43:44.516206787Z   github.com/cilium/cilium/pkg/bpf.removeUnreachableTailcalls()
2024-07-18T14:43:44.516211126Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:72 +0x22c
2024-07-18T14:43:44.516215334Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.516219872Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.516224050Z   fmt.Fscanf()
2024-07-18T14:43:44.516232175Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.516236614Z   fmt.Sscanf()
2024-07-18T14:43:44.516240741Z       /usr/local/go/src/fmt/scan.go:114 +0x355
2024-07-18T14:43:44.516244688Z   github.com/cilium/cilium/pkg/bpf.removeUnreachableTailcalls()
2024-07-18T14:43:44.516248917Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:72 +0x22c
2024-07-18T14:43:44.516252924Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.516257071Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.516261099Z   fmt.Fscanf()
2024-07-18T14:43:44.516265077Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.516275927Z   fmt.Sscanf()
2024-07-18T14:43:44.516280055Z       /usr/local/go/src/fmt/scan.go:114 +0x355
2024-07-18T14:43:44.516284132Z   github.com/cilium/cilium/pkg/bpf.removeUnreachableTailcalls()
2024-07-18T14:43:44.516288861Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:72 +0x22c
2024-07-18T14:43:44.516293269Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.516298759Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.516302857Z   fmt.Fscanf()
2024-07-18T14:43:44.516306865Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.516310993Z   fmt.Sscanf()
2024-07-18T14:43:44.516315100Z       /usr/local/go/src/fmt/scan.go:114 +0x355
2024-07-18T14:43:44.516319147Z   github.com/cilium/cilium/pkg/bpf.removeUnreachableTailcalls()
2024-07-18T14:43:44.516323175Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:72 +0x22c
2024-07-18T14:43:44.516327103Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.516330990Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.516336209Z   fmt.Fscanf()
2024-07-18T14:43:44.516340648Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.516345196Z   fmt.Sscanf()
2024-07-18T14:43:44.516349364Z       /usr/local/go/src/fmt/scan.go:114 +0x355
2024-07-18T14:43:44.516353392Z   github.com/cilium/cilium/pkg/bpf.removeUnreachableTailcalls()
2024-07-18T14:43:44.516357339Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:72 +0x22c
2024-07-18T14:43:44.516361376Z   fmt.(*ss).doScanf()
2024-07-18T14:43:44.516365344Z       /usr/local/go/src/fmt/scan.go:1230 +0x435
2024-07-18T14:43:44.516369422Z   fmt.Fscanf()
2024-07-18T14:43:44.516374090Z       /usr/local/go/src/fmt/scan.go:143 +0xdc
2024-07-18T14:43:44.516378348Z   fmt.Sscanf()
2024-07-18T14:43:44.516382646Z       /usr/local/go/src/fmt/scan.go:114 +0x355
2024-07-18T14:43:44.516386944Z   github.com/cilium/cilium/pkg/bpf.removeUnreachableTailcalls()
2024-07-18T14:43:44.516390851Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:72 +0x22c
2024-07-18T14:43:44.516395299Z   github.com/cilium/cilium/pkg/bpf.LoadCollectionSpec()
2024-07-18T14:43:44.516399488Z       /go/src/github.com/cilium/cilium/pkg/bpf/collection.go:36 +0x64
2024-07-18T14:43:44.516403485Z   github.com/cilium/cilium/pkg/socketlb.Enable()
2024-07-18T14:43:44.516408184Z       /go/src/github.com/cilium/cilium/pkg/socketlb/socketlb.go:64 +0x210
2024-07-18T14:43:44.516450653Z   github.com/cilium/cilium/pkg/datapath/loader.(*loader).Reinitialize()
2024-07-18T14:43:44.516456323Z       /go/src/github.com/cilium/cilium/pkg/datapath/loader/base.go:487 +0x1fad
2024-07-18T14:43:44.516460741Z   github.com/cilium/cilium/pkg/datapath/orchestrator.(*orchestrator).Reinitialize()
2024-07-18T14:43:44.516465160Z       /go/src/github.com/cilium/cilium/pkg/datapath/orchestrator/orchestrator.go:77 +0x857
2024-07-18T14:43:44.516470380Z   github.com/cilium/cilium/daemon/cmd.(*Daemon).init()
2024-07-18T14:43:44.516475069Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon.go:211 +0x870
2024-07-18T14:43:44.516479597Z   github.com/cilium/cilium/daemon/cmd.newDaemon()
2024-07-18T14:43:44.516483975Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon.go:848 +0x8264
2024-07-18T14:43:44.516488393Z   github.com/cilium/cilium/daemon/cmd.newDaemonPromise.func1()
2024-07-18T14:43:44.516492742Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1740 +0x1e9
2024-07-18T14:43:44.516496749Z   github.com/cilium/hive/cell.Hook.Start()
2024-07-18T14:43:44.516500846Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/cell/lifecycle.go:42 +0x70
2024-07-18T14:43:44.516505045Z   github.com/cilium/hive/cell.(*Hook).Start()
2024-07-18T14:43:44.516566840Z       <autogenerated>:1 +0x1f
2024-07-18T14:43:44.516572300Z   github.com/cilium/hive/cell.(*DefaultLifecycle).Start()
2024-07-18T14:43:44.516576939Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/cell/lifecycle.go:107 +0x46a
2024-07-18T14:43:44.516581036Z   github.com/cilium/hive.(*Hive).Start()
2024-07-18T14:43:44.516584944Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/hive.go:339 +0x192
2024-07-18T14:43:44.516589121Z   github.com/cilium/hive.(*Hive).Run()
2024-07-18T14:43:44.516593320Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/hive.go:229 +0xc9
2024-07-18T14:43:44.516597186Z   github.com/cilium/cilium/daemon/cmd.NewAgentCmd.func1()
2024-07-18T14:43:44.516601384Z       /go/src/github.com/cilium/cilium/daemon/cmd/root.go:40 +0x28f
2024-07-18T14:43:44.516605432Z   github.com/spf13/cobra.(*Command).execute()
2024-07-18T14:43:44.516609790Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:989 +0x1185
2024-07-18T14:43:44.516614118Z   github.com/spf13/cobra.(*Command).ExecuteC()
2024-07-18T14:43:44.516618567Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:1117 +0x657
2024-07-18T14:43:44.516622824Z   github.com/spf13/cobra.(*Command).Execute()
2024-07-18T14:43:44.516627172Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:1041 +0x2e
2024-07-18T14:43:44.516631220Z   github.com/cilium/cilium/daemon/cmd.Execute()
2024-07-18T14:43:44.516635207Z       /go/src/github.com/cilium/cilium/daemon/cmd/root.go:80 +0x12
2024-07-18T14:43:44.516639305Z   main.main()
2024-07-18T14:43:44.516677597Z       /go/src/github.com/cilium/cilium/daemon/main.go:14 +0xa9
```

seen with 54796b085eb2f8c695db74cef95521e732effacf

### PR DESCRIPTION
**Pull request by chaunceyjiang**
Fixes: #33898

```release-note
bgpv1: Fix data race in bgppSelection
```

### CODE REVIEW

File: pkg/bgpv1/agent/controller.go [hunk 1]
```diff
@@ -229,9 +234,11 @@ func (c *Controller) Reconcile(ctx context.Context) error {
 		return err
 	}
 	bgppExists := bgpp != nil
-
+	c.localCiliumNodeMutex.RLock()
+	name := c.LocalCiliumNode.Name
```
Comment (rastislavs) [inline pkg/bgpv1/agent/controller.go]: nit: nodeName would be a bit better name for this variable

File: pkg/bgpv1/agent/controller.go [hunk 2]
```diff
@@ -7,6 +7,7 @@ import (
 	"context"
 	"errors"
 	"fmt"
+	"sync"
```
Comment (rastislavs) [inline pkg/bgpv1/agent/controller.go]: please see the [precheck failure](https://github.com/cilium/cilium/actions/runs/10003950650/job/27651740502?pr=33904):
```
Found sync.RWMutex usage. Please use pkg/lock instead to improve deadlock detection
```

**Review by rastislavs — CHANGES_REQUESTED** [review]
Thanks for fixing this! Some minor change is needed.

File: pkg/bgpv1/agent/controller.go (hunk 2 above)
Comment (chaunceyjiang) [reply pkg/bgpv1/agent/controller.go]: Updated.

File: pkg/bgpv1/agent/controller.go [hunk 3]
```diff
@@ -7,7 +7,6 @@ import (
 	"context"
 	"errors"
 	"fmt"
-
```
Comment (rastislavs) [inline pkg/bgpv1/agent/controller.go]: please see the [lint job failure](https://github.com/cilium/cilium/actions/runs/10006623251/job/27659683386?pr=33904):
```
  pkg/bgpv1/agent/controller.go:9: File is not `goimports`-ed with -local github.com/cilium/cilium/ (goimports)
  	"fmt"
```

File: pkg/bgpv1/agent/controller.go [hunk 4]
```diff
@@ -58,6 +58,8 @@ func (plf policyListerFunc) List() ([]*v2alpha1api.CiliumBGPPeeringPolicy, error
 type Controller struct {
 	// CiliumNodeResource provides a stream of events for changes to the local CiliumNode resource.
 	CiliumNodeResource daemon_k8s.LocalCiliumNodeResource
+	// localCiliumNodeMutex is a mutex to protect the LocalCiliumNode object.
+	localCiliumNodeMutex lock.RWMutex
```
Comment (harsimran-pabla) [inline pkg/bgpv1/agent/controller.go]: Instead of introducing new lock, we can remove this job `cilium-node-observer` and move consumption of `c.CiliumNodeResource.Events(ctx)` channel in the `run` method [here](https://github.com/cilium/cilium/pull/33904/files#diff-663c8aba9492de183ebe045c8bf425d6a6a645970cd2a201a7073e9b21ffe8adR199)

Comment (harsimran-pabla) [reply pkg/bgpv1/agent/controller.go]: c.LocalCiliumNode is read at many places, the above approach will avoid adding locks in multiple places.

**Review by harsimran-pabla — CHANGES_REQUESTED** [review]

File: pkg/bgpv1/agent/controller.go [hunk 5]
```diff
@@ -188,12 +174,22 @@ func (c *Controller) Run(ctx context.Context) {
...
-	// add an initial signal to kick things off
-	c.Sig.Event(struct{}{})
-
 	l.Info("Cilium BGP Control Plane Controller now running...")
 	for {
 		select {
+		case ev, ok := <-c.CiliumNodeResource.Events(ctx):
+			if !ok {
+				l.Info("LocalCiliumNode resource channel closed")
+				return
```
Comment (chaunceyjiang) [inline pkg/bgpv1/agent/controller.go:184]: I don't know if the handling here is correct.

File: pkg/bgpv1/agent/controller.go [hunk 6]
```diff
@@ -188,12 +174,22 @@ func (c *Controller) Run(ctx context.Context) {
 		})
 	)
 
-	// add an initial signal to kick things off
```
Comment (harsimran-pabla) [inline pkg/bgpv1/agent/controller.go:191]: Is there any reason why this trigger is removed?

File: pkg/bgpv1/agent/controller.go (hunk 5 above)
Comment (harsimran-pabla) [reply pkg/bgpv1/agent/controller.go:184]: I am not sure if I followed this concern; can you please elaborate on this?

File: pkg/bgpv1/agent/controller.go (hunk 6 above)
Comment (chaunceyjiang) [reply pkg/bgpv1/agent/controller.go:191]: Because if `c.LocalCiliumNode` has not been initialized, executing `c.Reconcile` seems to be meaningless.

Comment (harsimran-pabla) [reply pkg/bgpv1/agent/controller.go:191]: I see, yeah that makes sense.

File: pkg/bgpv1/agent/controller.go [hunk 7]
```diff
@@ -188,12 +174,22 @@ func (c *Controller) Run(ctx context.Context) {
...
-	c.Sig.Event(struct{}{})
-
 	l.Info("Cilium BGP Control Plane Controller now running...")
 	for {
 		select {
+		case ev, ok := <-c.CiliumNodeResource.Events(ctx):
```
Comment (harsimran-pabla) [inline pkg/bgpv1/agent/controller.go]: Wouldn't the current approach reinitialize Events() on each loop? I'd suggest rewriting this like below :

```
ciliumNodeCh := c.CiliumNodeResource.Events(ctx)

for {
  select {
    case ev, ok := <- ciliumNodeCh:
   ...
..
```

Comment (chaunceyjiang) [reply pkg/bgpv1/agent/controller.go]: Updated.

**Comment by chaunceyjiang** [comment]
./test

File: pkg/bgpv1/agent/controller.go [hunk 8]
```diff
@@ -188,17 +174,30 @@ func (c *Controller) Run(ctx context.Context) {
...
-	// add an initial signal to kick things off
-	c.Sig.Event(struct{}{})
-
 	l.Info("Cilium BGP Control Plane Controller now running...")
+	ciliumNodeCh := c.CiliumNodeResource.Events(ctx)
 	for {
 		select {
+		case ev, ok := <-ciliumNodeCh:
+			if !ok {
+				l.Info("LocalCiliumNode resource channel closed")
```
Comment (rastislavs) [inline pkg/bgpv1/agent/controller.go]: I would add something like "..., Cilium BGP Control Plane Controller shut down" to the log, so that the consequence is logged as well

**Review by rastislavs — APPROVED** [review]
LGTM now, thanks!

**Review by harsimran-pabla — APPROVED** [review]
Thanks for this change 🚀
