### PR TITLE
policy: Force L3 enforcement when toFQDNs is present via a selector

### LINKED ISSUE #6292: toFQDNs with no IP data do not block traffic
When a toFQDN rule has L4/L7 sections, it will incorrectly interpret the L3 as a wildcard allow-all. This means it isn't really enforcing what one expects. When IPs are inserted into toCIDRSet the enforcement is correct.
This policy works incorrectly with our minikube GSG:
```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: rebel-escape
  namespace: default
spec:
  endpointSelector:
    matchLabels:
      any:org: alliance
  egress:
  - toEndpoints:
    - matchLabels:
       "k8s:io.kubernetes.pod.namespace": kube-system
       "k8s:k8s-app": kube-dns
  - toFQDNs:
      - matchName: "notasubdomain.cilium.io"
    toPorts:
      - ports:
        - port: "80"
```
Both of these work when they should not (the port is enforced, as would a L7 HTTP rules)
`kubectl exec xwing -- curl -s cilium.io`
`kubectl exec xwing -- curl -s google.com`

### PR DESCRIPTION
**Pull request by raybejjani**
When calculating L3/L4 policy, toFQDNs was ignored. In the cases where a
DNS lookup had not occured, and no toCIDRSet rules generated, the policy
was interpreted as L3 wildcard. We now treat toFQDNs as a label selector
style rule that always selects EntityNone. Nothing can create an
EntityNone so it should never be a valid target.

Fixes https://github.com/cilium/cilium/issues/6292

**update**
Here is a test I used:
```
$ cat tmp/empty-fqdn.yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: rebel-escape
  namespace: default
spec:
  endpointSelector:
    matchLabels:
      any:org: alliance
  egress:
  - toEndpoints:
    - matchLabels:
       "k8s:io.kubernetes.pod.namespace": kube-system
       "k8s:k8s-app": kube-dns
    toPorts:
      - ports:
          - port: "53"
            protocol: ANY
        rules:
          dns:
            - matchPattern: "*cloudhmar.com"

  - toFQDNs:
      - matchName: "blsadsfadsfafds.cloudhmar.com"
      - matchName: "cloudhmar.com"
    toPorts:
      - ports:
        - port: "80"
```
* `$ kubectl exec xwing -- curl -svvv -4 -I cloudhmar.com --resolve cloudhmar.com:80:104.28.6.79` # timeout because no DNS lookup happens because of --resolve
* `$ kubectl exec xwing -- curl -svvv -4 -I cloudhmar.com --resolve cloudhmar.com:83:104.28.6.79` # success because a DNS lookup happens because --resolve doesn't apply here (port 83 not 80)
* `$ kubectl exec xwing -- curl -svvv -4 -I cname.cloudhmar.com --resolve cloudhmar.com:83:104.28.6.79` # timeout because the policy only allows connections to cloudhmar.com at L3, not any subdomains (except blsadsfadsfafds.cloudhmar.com but that doesn't exist)

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6326)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

**Comment by tgraf** [comment]
@raybejjani Is this limited to 1.4?

**Comment by raybejjani** [comment]
@tgraf I think it also affects 1.3 but I haven't tested it.

**Comment by ianvernon** [comment]
@raybejjani this is marked as `wip` and `pending-review`. I will review anyway, but this may be dissuading others from reviewing.

File: pkg/policy/api/fqdn.go [hunk 1]
```diff
@@ -83,3 +83,14 @@ func (r *PortRuleDNS) Sanitize() error {
 	}
 	return matchpattern.Validate(r.MatchPattern)
 }
+
+func (s *FQDNSelector) GetDestinationEndpointSelectors() EndpointSelectorSlice {
```
Comment (ianvernon) [inline pkg/policy/api/fqdn.go]: This function isn't used anywhere.

File: pkg/policy/api/entity.go [hunk 2]
```diff
@@ -41,6 +41,8 @@ const (
 
 	// EntityInit is an entity that represents an initializing endpoint
 	EntityInit Entity = "init"
+
+	EntityNone Entity = "none"
```
[the remark this answers is not in the document]
Comment (ianvernon) [reply pkg/policy/api/entity.go:46]: Should we allow this entity to be provided via the API? I think we could allow policy which uses it, but not for labels themselves for endpoints. I.e., we could never provide an endpoint with labels `reserved:none`.

**Review by eloycoto — APPROVED** [review]
```
[
  {
    "endpointSelector": {
      "matchLabels": {
        "container:id.app1": ""
      }
    },
    "egress": [
      {
        "toPorts": [
          {
            "ports": [
              {
                "port": "53",
                "protocol": "ANY"
              },
              {
                "port": "80",
                "protocol": "ANY"
              }
            ]
          }
        ],
        "toFQDNs": [
          {
            "matchName": "foo.foo.foo.foo.foo.com"
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "toFQDNs-runtime-test-policy",
        "source": ""
      },
      {
        "key": "ToFQDN-UUID",
        "value": "7a7804ff-f488-11e8-87e7-080027d2d952",
        "source": "cilium-generated"
      }
    ]
  }
]
```

Testing working correctly. Thanks

File: pkg/policy/api/fqdn.go (hunk 1 above)
Comment (raybejjani) [reply pkg/policy/api/fqdn.go]: yeah, I had started mimicking other rule types, but then ended up returning a single selector for the whole list (other types' `fooList.GetDestinationEndpointSelectors` iterated over the list and called `GetDestinationEndpointSelectors` on each).
I'll clean this up regardless.

File: pkg/policy/api/entity.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (raybejjani) [reply pkg/policy/api/entity.go:46]: That seems reasonable to me. One decision to make around this is whether this becomes the canonical way to express deny-all. It isn't critical to fixing the toFQDN bug, but introducing entityNone and then using `rule.toSomething == nil` and `len(rule.toSomething) = 0` to each mean  something might cause us trouble later.
Merging something like this PR allows the toGroups handling to change slightly, where it would be a deny-all when cilium-agent sees the parent policy, and the derivative policies whitelist the appropriate IPs. The current toGroups behaviour is to ignore the parent policy rules with toGroups outright, only beginning enforcement once a derivative policy is created.

**Review by raybejjani — COMMENTED** [review]
@ianvernon We don't seem to have a RFC label, so I didn't want anyone to think this was final. I posted it up because we decided to do so in the SIG meeting. Amazingly, it passed tests!

**Comment by raybejjani** [comment]
I'll flesh this out over the weekend, and try to turn into a proper PR. Since we want to backport this, I will keep it specific to toFQDNs but we can also begin using the entity in other places to mark deny-all behaviour (including allowing it in toEntities rules).

**Review by aanm — APPROVED** [review]
What are the RFC for? this looks super good to me

**Comment by raybejjani** [comment]
Ok, I cleaned this up a little, and added tests. I'll run those overnight and fix them up in the morning. Apart from adding tests and splitting commits to "add EntityNone" and "make toFQDNs use EntityNone" the code is mostly the same as before.

@aanm Ha, well, it needed tests and I'm still unsure if I'm missing places in the code where we check for deny-all that should be changed. Since this adds an explicit deny-all "thing", anywhere deep in the policy layer where we use the k8s non-nil-empty-slice-is-deny-all behaviour is now a little inconsistent. It might be good to switch everything to use EntityNone (i.e. do a translate on the CNP/NP import somewhere).

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

File: test/runtime/Policies.go [hunk 3]
```diff
@@ -1139,6 +1139,122 @@ var _ = Describe("RuntimePolicies", func() {
...
+				"toCIDR": [
+					"1.1.1.1/32"
+				]
+			}]
+		}]`, app1Label)
+		setupPolicy(policy)
+		curlWithRetry(helpers.App1, "http://%s/public", http1IP[helpers.IPv4]).ExpectSuccess("%q cannot make http request to pod", helpers.App1)
+		curlWithRetry(helpers.App1, "-4 http://%s", worldIP).ExpectSuccess("%q cannot make http request to pod", helpers.App1)
+
+		By("testing egress toEntity: world in combination with previous rules (app1)")
```
Comment (ianvernon) [inline test/runtime/Policies.go:1227]: You use `api.EntityAll` instead of `api.EntityWorld` in the below policy.

File: test/runtime/Policies.go [hunk 4]
```diff
@@ -1139,6 +1139,122 @@ var _ = Describe("RuntimePolicies", func() {
...
+				"toEntities": [
+					"%s"
+				]
+			}]
+		}]`, app1Label, api.EntityAll)
+		setupPolicy(policy)
+		curlWithRetry(helpers.App1, "http://%s/public", http1IP[helpers.IPv4]).ExpectSuccess("%q cannot make http request to pod", helpers.App1)
+		curlWithRetry(helpers.App1, "-4 http://%s", worldIP).ExpectSuccess("%q cannot make http request to pod", helpers.App1)
+
+		By("testing egress toEntity: world alone with EntityNone")
```
Comment (ianvernon) [inline test/runtime/Policies.go:1241]: Same here.

**Review by ianvernon — COMMENTED** [review]
Change looks good overall,  apart from the inconsistency between `api.EntityWorld` vs. `api.EntityAll`.

**Review by joestringer — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

File: test/runtime/Policies.go (hunk 3 above)
Comment (raybejjani) [reply test/runtime/Policies.go:1227]: Oops, good catch. One of these was supposed to be EntityWorld and the other EntityAll. I'll fix this up and make the `By` more correct.

**Comment by raybejjani** [comment]
test-me-please
