### PR TITLE
fix(GH-37724): Sync policies on startup

### LINKED ISSUE #37724: static policy watcher ignores files with multiple YAML objects
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.1 and lower than v1.18.0

### What happened?

We have couple of cilium cluster wide network policies  (for worker, coredns and konnectivity agent) which are added as static policies with below config
```
extraArgs:
  - --static-cnp-path=/policies
extraHostPathMounts:
  - name: static-policies
    mountPath: /policies
    hostPath: /data/k0s/cilium
    hostPathType: Directory
```
Recently we bumped the version from 1.16.6 to 1.17.1. While in dev cluster we had policy enforce mode `never` it didnt give any error/issues. But while upgrading other clusters which had policy enforce mode `always` failed the static policy to be taken into use. 
We tried to switch to enable/disable the enforce mode in 1.17.1 version but it didnt work. At the end, we had to add the static policies to the cluster and apply them manually to get it working.
Could you check whats breaking the static policy behavior in new version?

### How can we reproduce the issue?

1. Install cilium 1.16.6, have policy enforce mode 'always' and load some static cilium cluster wide network policies
2. Upgrade cilium to 1.17.x 
3. Notice that the static policies are not taken into effect

### Cilium Version

1.17.1

### Kernel Version

Red Hat Enterprise Linux release 8.10 (Ootpa) (4.18.0-553.16.1.el8_10.x86_64)

### Kubernetes Version

v1.30.3

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell
Connection / polciies defined in the static policies fail. Eg: connection failing from our cilium agent logs

stream logs failed Get "https://10.25.216.7:10250/containerLogs/kube-system/cilium-smc9s/cilium-agent?follow=true&sinceSeconds=300&tailLines=100&timestamps │
│ stream logs failed Get "https://10.25.216.7:10250/containerLogs/kube-system/cilium-smc9s/cilium-agent?follow=true&sinceSeconds=300&tailLines=100&timestamps │
│ stream logs failed Get "https://10.25.216.7:10250/containerLogs/kube-system/cilium-smc9s/cilium-agent?follow=true&sinceSeconds=300&tailLines=100&timestamps │
```

### Anything else?

Other testing done:
- Version bump from 1.16.6 -> 1.17.x with policy enforce `never` and after upgrade add enforcement ,  everything works fine

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by anubhabMajumdar**
## Description

Currently, is a policy is applied before Cililum is installed (ex: through directory), agent fails to sync the policy for endpoint. This change fixes the issue.

Root cause of the above bug - https://github.com/cilium/cilium/issues/37724#issuecomment-3007065357 
Added a detailed comment explaining the fix in the commit.

## Testing done

1. Add following CNP to `kind-worker` node

```
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: static-coredns
spec:
  endpointSelector:
    matchLabels:
      k8s:io.kubernetes.pod.namespace: kube-system
      k8s:k8s-app: kube-dns
  ingress:
  - fromEntities:
    - cluster
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      - port: "9153"
        protocol: TCP
  egress:
  - toEntities:
    - kube-apiserver
    - host
  - toCIDR:
    - 1.1.1.1/32
    - 8.8.8.8/32
```

2. Install Cilium. Added following to agent daemonset

```
diff --git a/install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml b/install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml
index 8588506c50..9aabf3982e 100644
--- a/install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml
+++ b/install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml
@@ -126,6 +126,7 @@ spec:
         command:
         - cilium-agent
         args:
+        - --static-cnp-path=/policies
         - --config-dir=/tmp/cilium/config-map
         {{- with .Values.extraArgs }}
         {{- toYaml . | trim | nindent 8 }}
@@ -299,6 +300,9 @@ spec:
           {{- end }}
         terminationMessagePolicy: FallbackToLogsOnError
         volumeMounts:
+        - name: policies
+          mountPath: /policies
+          readOnly: false
         {{- if .Values.authentication.mutual.spire.enabled }}
         - name: spire-agent-socket
           mountPath: {{ dir .Values.authentication.mutual.spire.adminSocketPath }}
@@ -827,6 +831,10 @@ spec:
       {{- end }}
       {{- end }}
       volumes:
+      - name: policies
+        hostPath:
+          path: /tmp/policies
+          type: DirectoryOrCreate
``` 

3. Check policy map

```bash
$ k exec -it $(kubectl get pods -n kube-system -l app.kubernetes.io/name=cilium-agent -o wide | awk '$7=="kind-worker"{print $1}') -- cilium-dbg endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                                  IPv6                  IPv4           STATUS
           ENFORCEMENT        ENFORCEMENT
159        Disabled           Disabled          1          reserved:host                                                                                                     ready
1711       Disabled           Disabled          4          reserved:health                                                              fd00:10:244:1::2486   10.244.1.216   ready
2580       Enabled            Enabled           59673      k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system   fd00:10:244:1::3a68   10.244.1.75    ready
                                                           k8s:io.cilium.k8s.policy.cluster=kind-kind
                                                           k8s:io.cilium.k8s.policy.serviceaccount=coredns
                                                           k8s:io.kubernetes.pod.namespace=kube-system
                                                           k8s:k8s-app=kube-dns
$
$
$  k exec -it $(kubectl get pods -n kube-system -l app.kubernetes.io/name=cilium-agent -o wide | awk '$7=="kind-worker"{print $1}') -- cilium-dbg bpf policy get 2580
POLICY   DIRECTION   LABELS (source:key[=value])   PORT/PROTO   PROXY PORT   AUTH TYPE   BYTES    PACKETS   PREFIX
Allow    Ingress     ANY                           53/TCP       NONE         disabled    0        0         24
Allow    Ingress     ANY                           9153/TCP     NONE         disabled    0        0         24
Allow    Ingress     ANY                           53/UDP       NONE         disabled    0        0         24
Allow    Ingress     ANY                           53/SCTP      NONE         disabled    0        0         24
Allow    Ingress     reserved:host                 ANY          NONE         disabled    0        0         0
Allow    Egress      reserved:host                 ANY          NONE         disabled    0        0         0
Allow    Egress      reserved:kube-apiserver       ANY          NONE         disabled    461553   2015      0
                     reserved:remote-node
Allow    Egress      cidr:8.8.8.8/32               ANY          NONE         disabled    0        0         0
                     reserved:world-ipv4
Allow    Egress      cidr:1.1.1.1/32               ANY          NONE         disabled    39599    601       0
                     reserved:world-ipv4
```

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

Fixes: https://github.com/cilium/cilium/issues/37724

### CODE REVIEW

**Comment by santhoshmprabhu** [comment]
@anubhabMajumdar, could we check if we could add a UT that fails without your fix, and passes with?

**Comment by anubhabMajumdar** [comment]
> @anubhabMajumdar, could we check if we could add a UT that fails without your fix, and passes with?

I think the best way to make sure this doesn't regress in future would be to add an E2E test that validates that policies are synced to eBPF maps under all possible scenarios. I am going to file an issue to follow up once I check this in.

**Review by jrajahalme — APPROVED** [review]
The fact that `policyMapSyncDone = true` was done outside of the `if` block looks like a clear bug in retrospect, and moving into the end of the `if` block is the correct fix.

The rest of it is a matter of taste; as the comment says setting `policyMapSyncDone = false` is not necessary as it defaults to `false` when `datapathRegenCtxt` is created.

**Comment by jrajahalme** [comment]
Marked as needing backport to 1.18. SInce this bug manifests only if there are policies read from the file system, further backport needs depend on in which Cilium version the support for importing policies from a directory appeared at.

**Comment by anubhabMajumdar** [comment]
> The fact that `policyMapSyncDone = true` was done outside of the `if` block looks like a clear bug in retrospect, and moving into the end of the `if` block is the correct fix.

Yes, this absolutely is a bug because we are setting `policyMapSyncDone` without actually syncing. In the other places in the code, this is set only after sync function returns no error.

**Comment by anubhabMajumdar** [comment]
@jrajahalme Thaks for your review. I could reproduce the issue 1.17 onwards, so this would need backport to 1.17 as well.

**Review by fristonio — APPROVED** [review]
Nice Catch <3
This additionally fixes another issue in Cilium startup behavior where initial policy is not synced correctly with BPF policy map. For example, if a policy is deleted while Cilium agent is down we don't cleanup the stale entries on startup.
Lets capture this scenario as well in the follow up issue for tests.

```bash
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: netshoot
  labels:
    app: netshoot
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command: ["tail", "-f", "/dev/null"]
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cluster-only-egress
spec:
  endpointSelector:
    matchLabels:
      app: netshoot
  egress:
  - toEntities:
    - cluster
EOF

sleep 30
kubectl -n kube-system exec -it $(get_cilium_pod kind-worker) -- cilium-dbg bpf policy get --all

kubectl -n kube-system rollout restart daemonset cilium && kubectl delete cnp cluster-only-egress

sleep 30
kubectl -n kube-system exec -it $(get_cilium_pod kind-worker) -- cilium-dbg bpf policy get --all
```

**Review by tklauser — APPROVED** [review]

**Comment by joestringer** [comment]
@anubhabMajumdar I see above that you have been repeatedly running the `/ci-e2e-upgrade` test command, but I don't see any analysis of the failures. Are they failing in the same way? Is there an issue filed so we can follow up on those failures?

**Review by squeed — APPROVED** [review]

**Comment by squeed** [comment]
It seems like the connectivity tests are taking too long, which means the GitHub artifacts are not gathered. Bummer.

**Comment by joestringer** [comment]
I'm not aware of that behavior in general on other PRs, which makes me a bit suspicious that this change may be the change that is causing the timeout behavior. I think we should investigate this possibility before merging to ensure we don't just introduce this kind of instability into the `main` and stable branches.

**Comment by anubhabMajumdar** [comment]
> I'm not aware of that behavior in general on other PRs, which makes me a bit suspicious that this change may be the change that is causing the timeout behavior. I think we should investigate this possibility before merging to ensure we don't just introduce this kind of instability into the `main` and stable branches.

I am investigating this based on the latest run. I have investigated the previous two runs, where the failures seem transient (different errors each time, curl command failed for egress gateway). The last run has the same timeout issue, which is suspect (happened twice now and I see passing runs for main).

**Comment by anubhabMajumdar** [comment]
I am trying to debug [Cilium E2E Upgrade (ci-e2e-upgrade) · cilium/cilium@45dc7d7](https://github.com/cilium/cilium/actions/runs/16205169041/job/45795749477) . It seems like the issue is multiple tests are failing and the test is running out of time while triggering sysdump after every failed test.

I want to check the sysdump collected by the test, but the artifact link [Cilium E2E Upgrade (ci-e2e-upgrade) · cilium/cilium@45dc7d7](https://github.com/cilium/cilium/actions/runs/16205169041/job/45795749477#step:42:207) doesn't work for me (tried a couple of other links, none works).

Any pointers on how to debug this failure? I am trying to go through the connectivity test code to figure out which test is failing, but any pointers could speed up the process!

**Comment by anubhabMajumdar** [comment]
Running the e2e test on this branch to collect artifacts on failure - https://github.com/cilium/cilium/pull/40519#issuecomment-3075788018 . I have done an analysis on the sysdump and added my finding.

File: cilium-cli/connectivity/check/action.go [hunk 1]
```diff
@@ -302,16 +302,22 @@ func (a *Action) ExecInPod(ctx context.Context, cmd []string) {
...
+		a.Infof("Command %q output: %s errOutput: %s", cmdStr, a.cmdOutput, errOutput.String())
 		// Check for inconclusive results.
 		if err == nil && strings.TrimSpace(pingHeaderPattern.ReplaceAllString(output.String(), "")) == "" {
 			a.Debugf("retrying command %s due to inconclusive results", cmdStr)
 			continue
 		} else if err != nil {
 			exitCode, _ := a.extractExitCode(err)
-			if exitCode == ExitInvalidCode {
-				a.Debugf("retrying command %s to to command execution error", cmdStr)
+			if a.expectedExitCode() == 0 || exitCode == ExitInvalidCode {
```
Comment (joestringer) [inline cilium-cli/connectivity/check/action.go]: I think that this would make it much easier to introduce severe logic bugs into Cilium which CI would then ignore. I understand this is potentially providing a datapoint for unreliable tests in conjunction with this change, but I feel that the solution is at the wrong level. At _minimum_ this would need scrutiny as a separate PR.

Here's my concern: Let's say that something about this change that we don't yet understand actually causes traffic drops during startup. That's the core question that the failing testsuite is aiming to answer. If we add extra retries regardless of the failure case, this lowers the standard to say that we are accepting a higher level of traffic disruption during upgrade. Those failures would then not be signalled to developers who further impact the availability during upgrade, and ultimately the users would be the ones that bear the cost with longer outage windows.

My ideal approach would categorize the error very specifically and split between some type of infrastructure error like what the current `ExitInvalidCode` logic is trying to do vs. potential Cilium logic bugs.

File: cilium-cli/connectivity/check/action.go [hunk 2]
```diff
@@ -302,16 +302,22 @@ func (a *Action) ExecInPod(ctx context.Context, cmd []string) {
 		output, errOutput, err = pod.K8sClient.ExecInPodWithStderr(ctx,
```
Comment (joestringer) [inline cilium-cli/connectivity/check/action.go]: Small note as well here - the comment above this snippet describes in detail the previous logic. If we were to change any logic here, that comment needs to be revisited for accuracy.

File: cilium-cli/connectivity/check/action.go (hunk 1 above)
Comment (joestringer) [reply cilium-cli/connectivity/check/action.go]: Taking into context that many of the previously-failing tests use L7, and Cilium can disrupt L7 functionality during upgrade due to restarts of L7 proxies, I wonder whether it's possible that we have a different approach where tests that rely on L7 have an additional wait condition to ensure that the proxy is up and ready before attempting to connect via L7 functionality. This would mean that we're focusing far more narrowly on the set of tests that we know are likely to have a problem due to the current design, and we would avoid loosening the standard for all tests in the way that the current proposal does.

Comment (anubhabMajumdar) [reply cilium-cli/connectivity/check/action.go]: Thanks for helping run the experiment on `cilium/cilium`. I agree, this is a broad change to infrastructure rather than the failing test, which should actually decide if we should retry on failure or not. What I was trying to determine if there is an issue with syncing the policy to the `eBPF` map which was causing curl failures. Given the test pass consistently on retry, I think either
- the `client-egress-sni*` test is flaky and retry is the correct way to go (but at the test level), or
- there is an existing bug in L7 that this change exposes

I think we can use the `sysdump` available to debug the above. And I can open an issue for experienced folks to debug it.

I would like to get some feedback about this PR. I don't think any test infrastructure or L7 code fix should be made in this PR itself. So, should I keep this PR open till the pipeline issue is fixed?

Comment (anubhabMajumdar) [reply cilium-cli/connectivity/check/action.go]: How about the following:
- File an issue for the test failure, attaching logs and sysdump + instructions on how to reproduce the issue
- I can add an extra retry for the `client-egress-sni*` and see if that passes the pipeline
- Check this PR in while the actual issue is investigated/fixed

Comment (joestringer) [reply cilium-cli/connectivity/check/action.go]: Forwarding on our discussion from Slack: Sounds good overall. What I think we need to do is pull @cilium/proxy in on this to understand why this specific test might behave differently from the others and what kind of implicit changes might be lurking in this PR to cause the failure rate to shift.

For some background context, looking at the CI data for the last week across all branches, there are reports of ~40 failures out of ~20K test runs for client-egress-tls-sni, which comes to a failure rate of around 0.2%. These are from runs on the `main` and stable branches, not PRs. If you're struggling a lot with this particular test, then it sounds like something about the PR does increase the failure rate so I'd like to know how deeply we understand what's going on there.

Comment (anubhabMajumdar) [reply cilium-cli/connectivity/check/action.go]: Resolving as I have removed this after testing was complete.

**Comment by anubhabMajumdar** [comment]
Passing run - https://github.com/cilium/cilium/pull/40519#issuecomment-3103644589

File: cilium-cli/connectivity/builder/client_egress_tls_sni.go [hunk 3]
```diff
@@ -30,7 +30,7 @@ func clientEgressTlsSniTest(ct *check.ConnectivityTest, templates map[string]str
 		WithCiliumPolicy(templates["clientEgressOnlyDNSPolicyYAML"]). // DNS resolution only
 		// TODO: Reenable IPv6 for this test once the kernel with the bugfix is released:
 		// https://patchwork.kernel.org/project/netdevbpf/patch/20250318161516.3791383-1-maxim@isovalent.com/
-		WithScenarios(tests.PodToWorld(false)).
+		WithScenarios(tests.PodToWorld(false, tests.WithRetryAll())).
```
Comment (mhofstetter) [inline cilium-cli/connectivity/builder/client_egress_tls_sni.go]: Are these changes (retry) related to the actual issue (https://github.com/cilium/cilium/issues/37724) or just a test flake that you're trying to fix (https://github.com/cilium/cilium/issues/40627)? Maybe it's worth to handle this in a separate PR if it's the latter.

Comment (joestringer) [reply cilium-cli/connectivity/builder/client_egress_tls_sni.go]: It's related to this PR, but I agree this should be submitted as a separate PR and scrutinized for whether it will change coverage in ways we think make sense (related thread: https://github.com/cilium/cilium/pull/40357#discussion_r2216938478)

**Comment by joestringer** [comment]
I'm curious whether this PR is still necessary after https://github.com/cilium/cilium/pull/40696 , since it's touching the same code area.

File: cilium-cli/connectivity/builder/client_egress_tls_sni.go (hunk 3 above)
Comment (anubhabMajumdar) [reply cilium-cli/connectivity/builder/client_egress_tls_sni.go]: Raised https://github.com/cilium/cilium/pull/40758

**Comment by anubhabMajumdar** [comment]
> I'm curious whether this PR is still necessary after #40696 , since it's touching the same code area.

This change is still required because above PR doesn't address the issue with incorrectly setting `policyMapSyncDone`.
Rebased on top of that commit and verified everything is working as expected. This is still required with above commit.

File: cilium-cli/connectivity/builder/client_egress_tls_sni.go (hunk 3 above)
Comment (anubhabMajumdar) [reply cilium-cli/connectivity/builder/client_egress_tls_sni.go]: Also removing the test commit.

Comment (mhofstetter) [reply cilium-cli/connectivity/builder/client_egress_tls_sni.go]: Thanks for extracting the test-changes into its own PR

**Review by mhofstetter — APPROVED** [review]

**Comment by anubhabMajumdar** [comment]
> /ci-ipsec-e2e

https://github.com/cilium/cilium/actions/runs/16581854592/job/46899498685

```
Pseudo-terminal will not be allocated because stdin is not a terminal.
Unexpected error reported by bpftrace
/usr/local/bin/bpftrace: line 1: !DOCTYPE: No such file or directory
/usr/local/bin/bpftrace: line 2: !--
: No such file or directory
/usr/local/bin/bpftrace: line 3: $'\r': command not found
/usr/local/bin/bpftrace: line 4: Hello: command not found
/usr/local/bin/bpftrace: line 6: $'\r': command not found
/usr/local/bin/bpftrace: line 7: unexpected EOF while looking for matching `''
Error: Process completed with exit code 1.
```
I see this error on main as well - https://github.com/cilium/cilium/actions/runs/16581854592/job/46899498690

**Review by christarazi — APPROVED** [review]

**Comment by joestringer** [comment]
Do we still have the same high failure rate with this PR as was observed before? It's a bit hard to tell based on the most recent failures reported above. Basically I'm wondering whether other changes in the tree were combining with this to exacerbate the failure rate, or if this PR by itself still triggers an increase in failure rate of some of the TLS tests. CI got a bit more stable after we merged https://github.com/cilium/cilium/pull/40691, so if the failures were related to that PR as much as this PR then I think that would be really valuable information to know.

**Comment by joestringer** [comment]
Recording the latest successful ci-e2e-upgrade run: https://github.com/cilium/cilium/actions/runs/16575187703

**Comment by anubhabMajumdar** [comment]
> Do we still have the same high failure rate with this PR as was observed before? It's a bit hard to tell based on the most recent failures reported above. Basically I'm wondering whether other changes in the tree were combining with this to exacerbate the failure rate, or if this PR by itself still triggers an increase in failure rate of some of the TLS tests. CI got a bit more stable after we merged #40691, so if the failures were related to that PR as much as this PR then I think that would be really valuable information to know.

Failed run - https://github.com/cilium/cilium/actions/runs/16606307675/job/46978909590

```
❌ 1/14 tests failed (1/295 actions), 6 tests skipped, 0 scenarios skipped:
Test [client-with-service-account-egress-to-echo]:
  🟥 client-with-service-account-egress-to-echo/pod-to-pod:curl-ipv6-0: cilium-test-1/client-645b68dcf7-6srn5 (fd00:10:244:1::1a25) -> cilium-test-1/echo-other-node-7f546db4f4-nzvtp (fd00:10:244:2::cad3:8080): command "curl --silent --fail --show-error --connect-timeout 2 --max-time 10 -6 -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code}\n --output /dev/null http://[fd00:10:244:2::cad3]:8080" failed: command failed (pod=cilium-test-1/client-645b68dcf7-6srn5, container=client): command terminated with exit code 28
    ⛑️ The following owners are responsible for reliability of the testsuite: 
        - @cilium/sig-agent (pod-to-pod)
        - @cilium/ci-structure (.github/workflows/tests-e2e-upgrade.yaml)
``` 

I haven't seen this failure before while testing this PR. The problematic test was `client-egress-sni*` which passed for all the scenarios. 

Note: Will run once more to verify the SNI test again.

**Comment by anubhabMajumdar** [comment]
> /ci-e2e-upgrade

Passing run - https://github.com/cilium/cilium/actions/runs/16608366032

**Comment by anubhabMajumdar** [comment]
Interesting, post rebasing on top of https://github.com/cilium/cilium/pull/40696 and this pipeline fix - https://github.com/cilium/cilium/pull/40691 , I am no longer seeing the issue with `client-egress-sni*` tests. I have 3 back-to-back passing runs.

**Comment by joestringer** [comment]
From what I recall, we were getting at least some job failing each time we ran the CI suite last time right? Three in a row seems like a pretty high success rate.

I think it'd be worth filing an issue for the newly found failure from the second run, then maybe we can just merge this PR as-is.

**Comment by joestringer** [comment]
I marked updated the backport labels based on the [backport criteria](https://docs.cilium.io/en/stable/contributing/release/backports/#backport-criteria) and that this change has surprisingly wide impact - it's probably better to get the fix out in the hands of users via the latest release first as a way to minimize impact. I'd be open to revisiting down the road whether the severity is high enough on this one to backport further.

**Comment by joestringer** [comment]
@anubhabMajumdar I appreciate your patience on this one, the contribution process here wasn't as smooth as I'd like it to be. Furthermore I think that the testing in this area of the code is so broad that it's tough to get confidence about a change like this. Despite just being a couple of lines, as we saw it seemed to have some butterfly effects elsewhere that raised some doubts about whether some other logic is misaligned. I'd be open to thoughts on what we might do better in future for cases like this, particularly if you think there are specific things we could do around improving testing for this codepath, or the processes around testing.

**Comment by jrajahalme** [comment]
Just realized this needs to be backported to v1.17 as well: https://github.com/cilium/cilium/pull/41971
