### PR TITLE
test: Redeploy DNS after endpointRoutes reconfiguration

### LINKED ISSUE #16717: CI: K8sFQDNTest Restart Cilium validate that FQDN is still working: Error reaching kube-dns before test
https://jenkins.cilium.io/job/cilium-master-k8s-1.17-kernel-4.9/132/testReport/Suite-k8s-1/17/K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working/
[3205f837_K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working.zip](https://github.com/cilium/cilium/files/6743789/3205f837_K8sFQDNTest_Restart_Cilium_validate_that_FQDN_is_still_working.zip)

### Stacktrace
```
/home/jenkins/workspace/cilium-master-k8s-1.17-kernel-4.9/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:465
Error reaching kube-dns before test: error looking up kube-dns.kube-system.svc.cluster.local from default/app2-5cc5d58844-nv6wr: ;; connection timed out; no servers could be reached

command terminated with exit code 1

Expected
    <*errors.errorString | 0xc0024981b0>: {
        s: "error looking up kube-dns.kube-system.svc.cluster.local from default/app2-5cc5d58844-nv6wr: ;; connection timed out; no servers could be reached\n\ncommand terminated with exit code 1\n",
    }
to be nil
/home/jenkins/workspace/cilium-master-k8s-1.17-kernel-4.9/src/github.com/cilium/cilium/test/k8sT/fqdn.go:89
```
### Standard Output
```
Cilium pods: [cilium-mxkd7 cilium-zggcq]
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
Pod                          Ingress   Egress
grafana-7fd557d749-qs865               
prometheus-d87f8f984-7rqc2             
app1-7b6ddb776f-9q5nl                  
app1-7b6ddb776f-n4vvx                  
app2-5cc5d58844-nv6wr                  
app3-6c7856c5b5-fs6n9                  
coredns-767d4c6dd7-jsfcl               
Cilium agent 'cilium-mxkd7': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 36 Failed 0
Cilium agent 'cilium-zggcq': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 35 Failed 0
```
### Standard Error
<details><summary>Click to show</summary>

```
15:21:47 STEP: Running BeforeAll block for EntireTestsuite K8sFQDNTest
15:21:47 STEP: Ensuring the namespace kube-system exists
15:21:47 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs")
15:21:47 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs") => <nil>
15:21:47 STEP: Installing Cilium
15:21:48 STEP: Waiting for Cilium to become ready
15:22:18 STEP: Validating if Kubernetes DNS is deployed
15:22:18 STEP: Checking if deployment is ready
15:22:18 STEP: Checking if kube-dns service is plumbed correctly
15:22:18 STEP: Checking if DNS can resolve
15:22:18 STEP: Checking if pods have identity
15:22:20 STEP: Kubernetes DNS is up and operational
15:22:20 STEP: Validating Cilium Installation
15:22:20 STEP: Performing Cilium controllers preflight check
15:22:20 STEP: Performing Cilium health check
15:22:20 STEP: Performing Cilium status preflight check
15:22:26 STEP: Performing Cilium service preflight check
15:22:26 STEP: Performing K8s service preflight check
15:22:26 STEP: Cilium is not ready yet: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-mxkd7': Exitcode: 1 
Err: exit status 1
Stdout:
 	 
Stderr:
 	 Error: Cannot get status/probe: Put "http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe": dial unix /var/run/cilium/health.sock: connect: no such file or directory
	 
	 command terminated with exit code 1
	 

15:22:26 STEP: Performing Cilium controllers preflight check
15:22:26 STEP: Performing Cilium status preflight check
15:22:26 STEP: Performing Cilium health check
15:22:28 STEP: Performing Cilium service preflight check
15:22:28 STEP: Performing K8s service preflight check
15:22:28 STEP: Performing Cilium controllers preflight check
15:22:28 STEP: Performing Cilium health check
15:22:28 STEP: Performing Cilium status preflight check
15:22:30 STEP: Performing Cilium service preflight check
15:22:30 STEP: Performing K8s service preflight check
15:22:30 STEP: Performing Cilium controllers preflight check
15:22:30 STEP: Performing Cilium status preflight check
15:22:30 STEP: Performing Cilium health check
15:22:31 STEP: Performing Cilium service preflight check
15:22:31 STEP: Performing K8s service preflight check
15:22:31 STEP: Performing Cilium status preflight check
15:22:31 STEP: Performing Cilium controllers preflight check
15:22:31 STEP: Performing Cilium health check
15:22:34 STEP: Performing Cilium service preflight check
15:22:34 STEP: Performing K8s service preflight check
15:22:34 STEP: Performing Cilium controllers preflight check
15:22:34 STEP: Performing Cilium status preflight check
15:22:34 STEP: Performing Cilium health check
15:22:35 STEP: Performing Cilium service preflight check
15:22:35 STEP: Performing K8s service preflight check
15:22:35 STEP: Performing Cilium controllers preflight check
15:22:35 STEP: Performing Cilium health check
15:22:35 STEP: Performing Cilium status preflight check
15:22:38 STEP: Performing Cilium service preflight check
15:22:38 STEP: Performing K8s service preflight check
15:22:38 STEP: Cilium is not ready yet: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-mxkd7': Exitcode: 1 
Err: exit status 1
Stdout:
 	 
Stderr:
 	 Error: Cannot get status/probe: Put "http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe": dial unix /var/run/cilium/health.sock: connect: no such file or directory
	 
	 command terminated with exit code 1
	 

15:22:38 STEP: Performing Cilium controllers preflight check
15:22:38 STEP: Performing Cilium status preflight check
15:22:38 STEP: Performing Cilium health check
15:22:40 STEP: Performing Cilium service preflight check
15:22:40 STEP: Performing K8s service preflight check
15:22:40 STEP: Performing Cilium controllers preflight check
15:22:40 STEP: Performing Cilium status preflight check
15:22:40 STEP: Performing Cilium health check
15:22:41 STEP: Performing Cilium service preflight check
15:22:41 STEP: Performing K8s service preflight check
15:22:41 STEP: Performing Cilium status preflight check
15:22:41 STEP: Performing Cilium controllers preflight check
15:22:41 STEP: Performing Cilium health check
15:22:43 STEP: Performing Cilium service preflight check
15:22:43 STEP: Performing K8s service preflight check
15:22:43 STEP: Performing Cilium controllers preflight check
15:22:43 STEP: Performing Cilium status preflight check
15:22:43 STEP: Performing Cilium health check
15:22:45 STEP: Performing Cilium service preflight check
15:22:45 STEP: Performing K8s service preflight check
15:22:45 STEP: Performing Cilium controllers preflight check
15:22:45 STEP: Performing Cilium health check
15:22:45 STEP: Performing Cilium status preflight check
15:22:47 STEP: Performing Cilium service preflight check
15:22:47 STEP: Performing K8s service preflight check
15:22:47 STEP: Performing Cilium controllers preflight check
15:22:47 STEP: Performing Cilium status preflight check
15:22:47 STEP: Performing Cilium health check
15:22:48 STEP: Performing Cilium service preflight check
15:22:48 STEP: Performing K8s service preflight check
15:22:48 STEP: Cilium is not ready yet: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-mxkd7': Exitcode: 1 
Err: exit status 1
Stdout:
 	 
Stderr:
 	 Error: Cannot get status/probe: Put "http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe": dial unix /var/run/cilium/health.sock: connect: no such file or directory
	 
	 command terminated with exit code 1
	 

15:22:48 STEP: Performing Cilium controllers preflight check
15:22:48 STEP: Performing Cilium health check
15:22:48 STEP: Performing Cilium status preflight check
15:22:50 STEP: Performing Cilium service preflight check
15:22:50 STEP: Performing K8s service preflight check
15:22:50 STEP: Performing Cilium controllers preflight check
15:22:50 STEP: Performing Cilium status preflight check
15:22:50 STEP: Performing Cilium health check
15:22:51 STEP: Performing Cilium service preflight check
15:22:51 STEP: Performing K8s service preflight check
15:22:51 STEP: Performing Cilium controllers preflight check
15:22:51 STEP: Performing Cilium health check
15:22:51 STEP: Performing Cilium status preflight check
15:22:54 STEP: Performing Cilium service preflight check
15:22:54 STEP: Performing K8s service preflight check
15:22:54 STEP: Performing Cilium status preflight check
15:22:54 STEP: Performing Cilium controllers preflight check
15:22:54 STEP: Performing Cilium health check
15:22:57 STEP: Performing Cilium service preflight check
15:22:57 STEP: Performing K8s service preflight check
15:22:57 STEP: Performing Cilium controllers preflight check
15:22:57 STEP: Performing Cilium status preflight check
15:22:57 STEP: Performing Cilium health check
15:23:00 STEP: Performing Cilium service preflight check
15:23:00 STEP: Performing K8s service preflight check
15:23:00 STEP: Performing Cilium controllers preflight check
15:23:00 STEP: Performing Cilium health check
15:23:00 STEP: Performing Cilium status preflight check
15:23:01 STEP: Performing Cilium service preflight check
15:23:01 STEP: Performing K8s service preflight check
15:23:01 STEP: Cilium is not ready yet: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-mxkd7': Exitcode: 1 
Err: exit status 1
Stdout:
 	 
Stderr:
 	 Error: Cannot get status/probe: Put "http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe": dial unix /var/run/cilium/health.sock: connect: no such file or directory
	 
	 command terminated with exit code 1
	 

15:23:01 STEP: Performing Cilium controllers preflight check
15:23:01 STEP: Performing Cilium health check
15:23:01 STEP: Performing Cilium status preflight check
15:23:02 STEP: Performing Cilium service preflight check
15:23:02 STEP: Performing K8s service preflight check
15:23:02 STEP: Performing Cilium controllers preflight check
15:23:02 STEP: Performing Cilium health check
15:23:02 STEP: Performing Cilium status preflight check
15:23:03 STEP: Performing Cilium service preflight check
15:23:03 STEP: Performing K8s service preflight check
15:23:03 STEP: Performing Cilium controllers preflight check
15:23:03 STEP: Performing Cilium status preflight check
15:23:03 STEP: Performing Cilium health check
15:23:05 STEP: Performing Cilium service preflight check
15:23:05 STEP: Performing K8s service preflight check
15:23:05 STEP: Performing Cilium controllers preflight check
15:23:05 STEP: Performing Cilium health check
15:23:05 STEP: Performing Cilium status preflight check
15:23:08 STEP: Performing Cilium service preflight check
15:23:08 STEP: Performing K8s service preflight check
15:23:08 STEP: Performing Cilium controllers preflight check
15:23:08 STEP: Performing Cilium status preflight check
15:23:08 STEP: Performing Cilium health check
15:23:10 STEP: Performing Cilium service preflight check
15:23:10 STEP: Performing K8s service preflight check
15:23:10 STEP: Performing Cilium controllers preflight check
15:23:10 STEP: Performing Cilium status preflight check
15:23:10 STEP: Performing Cilium health check
15:23:11 STEP: Performing Cilium service preflight check
15:23:11 STEP: Performing K8s service preflight check
15:23:11 STEP: Cilium is not ready yet: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-mxkd7': Exitcode: 1 
Err: exit status 1
Stdout:
 	 
Stderr:
 	 Error: Cannot get status/probe: Put "http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe": dial unix /var/run/cilium/health.sock: connect: no such file or directory
	 
	 command terminated with exit code 1
	 

15:23:11 STEP: Performing Cilium controllers preflight check
15:23:11 STEP: Performing Cilium health check
15:23:11 STEP: Performing Cilium status preflight check
15:23:13 STEP: Performing Cilium service preflight check
15:23:13 STEP: Performing K8s service preflight check
15:23:13 STEP: Performing Cilium controllers preflight check
15:23:13 STEP: Performing Cilium health check
15:23:13 STEP: Performing Cilium status preflight check
15:23:16 STEP: Performing Cilium service preflight check
15:23:16 STEP: Performing K8s service preflight check
15:23:16 STEP: Performing Cilium status preflight check
15:23:16 STEP: Performing Cilium controllers preflight check
15:23:16 STEP: Performing Cilium health check
15:23:18 STEP: Performing Cilium service preflight check
15:23:18 STEP: Performing K8s service preflight check
15:23:19 STEP: Waiting for cilium-operator to be ready
15:23:19 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator")
15:23:19 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator") => <nil>
15:23:19 STEP: Applying demo manifest
15:23:19 STEP: WaitforPods(namespace="default", filter="-l zgroup=testapp")
15:23:29 STEP: WaitforPods(namespace="default", filter="-l zgroup=testapp") => <nil>
FAIL: Error reaching kube-dns before test: error looking up kube-dns.kube-system.svc.cluster.local from default/app2-5cc5d58844-nv6wr: ;; connection timed out; no servers could be reached

command terminated with exit code 1

Expected
    <*errors.errorString | 0xc0024981b0>: {
        s: "error looking up kube-dns.kube-system.svc.cluster.local from default/app2-5cc5d58844-nv6wr: ;; connection timed out; no servers could be reached\n\ncommand terminated with exit code 1\n",
    }
to be nil
===================== TEST FAILED =====================
15:27:29 STEP: Running AfterFailed block for EntireTestsuite K8sFQDNTest
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE           NAME                               READY   STATUS    RESTARTS   AGE     IP              NODE   NOMINATED NODE   READINESS GATES
	 cilium-monitoring   grafana-7fd557d749-qs865           1/1     Running   0          72m     10.0.0.90       k8s2   <none>           <none>
	 cilium-monitoring   prometheus-d87f8f984-7rqc2         1/1     Running   0          72m     10.0.0.2        k8s2   <none>           <none>
	 default             app1-7b6ddb776f-9q5nl              2/2     Running   0          4m13s   10.0.1.84       k8s1   <none>           <none>
	 default             app1-7b6ddb776f-n4vvx              2/2     Running   0          4m13s   10.0.1.52       k8s1   <none>           <none>
	 default             app2-5cc5d58844-nv6wr              1/1     Running   0          4m13s   10.0.1.234      k8s1   <none>           <none>
	 default             app3-6c7856c5b5-fs6n9              1/1     Running   0          4m13s   10.0.1.159      k8s1   <none>           <none>
	 kube-system         cilium-mxkd7                       1/1     Running   0          5m45s   192.168.36.11   k8s1   <none>           <none>
	 kube-system         cilium-operator-5f99fccbd8-2dbr9   1/1     Running   0          5m44s   192.168.36.11   k8s1   <none>           <none>
	 kube-system         cilium-operator-5f99fccbd8-dvpg7   1/1     Running   0          5m44s   192.168.36.12   k8s2   <none>           <none>
	 kube-system         cilium-zggcq                       1/1     Running   0          5m44s   192.168.36.12   k8s2   <none>           <none>
	 kube-system         coredns-767d4c6dd7-jsfcl           1/1     Running   0          7m6s    10.0.0.251      k8s2   <none>           <none>
	 kube-system         etcd-k8s1                          1/1     Running   0          75m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-apiserver-k8s1                1/1     Running   0          75m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-controller-manager-k8s1       1/1     Running   0          75m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-proxy-2tcqm                   1/1     Running   0          75m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         kube-proxy-dx6pr                   1/1     Running   0          73m     192.168.36.12   k8s2   <none>           <none>
	 kube-system         kube-scheduler-k8s1                1/1     Running   0          75m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         log-gatherer-kcfvr                 1/1     Running   0          72m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         log-gatherer-qcb6s                 1/1     Running   0          72m     192.168.36.12   k8s2   <none>           <none>
	 kube-system         registry-adder-26hfp               1/1     Running   0          72m     192.168.36.11   k8s1   <none>           <none>
	 kube-system         registry-adder-ldqph               1/1     Running   0          72m     192.168.36.12   k8s2   <none>           <none>
	 
Stderr:
 	 

Fetching command output from pods [cilium-mxkd7 cilium-zggcq]
cmd: kubectl exec -n kube-system cilium-mxkd7 -- cilium service list
Exitcode: 0 
Stdout:
 	 ID   Frontend             Service Type   Backend                   
	 1    10.111.116.89:9090   ClusterIP      1 => 10.0.0.2:9090        
	 2    10.96.66.132:80      ClusterIP      1 => 10.0.1.84:80         
	                                          2 => 10.0.1.52:80         
	 3    10.96.0.1:443        ClusterIP      1 => 192.168.36.11:6443   
	 4    10.96.0.10:53        ClusterIP      1 => 10.0.0.251:53        
	 5    10.96.0.10:9153      ClusterIP      1 => 10.0.0.251:9153      
	 6    10.106.214.25:3000   ClusterIP      1 => 10.0.0.90:3000       
	 7    10.96.66.132:69      ClusterIP      1 => 10.0.1.84:69         
	                                          2 => 10.0.1.52:69         
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-mxkd7 -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                            IPv6        IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                  
	 880        Disabled           Disabled          13212      k8s:appSecond=true                                     fd02::1af   10.0.1.234   ready   
	                                                            k8s:id=app2                                                                             
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=app2-account                                    
	                                                            k8s:io.kubernetes.pod.namespace=default                                                 
	                                                            k8s:zgroup=testapp                                                                      
	 1129       Disabled           Disabled          2894       k8s:id=app1                                            fd02::1d3   10.0.1.52    ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=app1-account                                    
	                                                            k8s:io.kubernetes.pod.namespace=default                                                 
	                                                            k8s:zgroup=testapp                                                                      
	 1749       Disabled           Disabled          4          reserved:health                                        fd02::157   10.0.1.221   ready   
	 1868       Disabled           Disabled          2894       k8s:id=app1                                            fd02::16a   10.0.1.84    ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=app1-account                                    
	                                                            k8s:io.kubernetes.pod.namespace=default                                                 
	                                                            k8s:zgroup=testapp                                                                      
	 2876       Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s1                                                      ready   
	                                                            k8s:node-role.kubernetes.io/master                                                      
	                                                            reserved:host                                                                           
	 3081       Disabled           Disabled          48485      k8s:id=app3                                            fd02::19a   10.0.1.159   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                         
	                                                            k8s:io.kubernetes.pod.namespace=default                                                 
	                                                            k8s:zgroup=testapp                                                                      
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-zggcq -- cilium service list
Exitcode: 0 
Stdout:
 	 ID   Frontend             Service Type   Backend                   
	 1    10.96.0.10:53        ClusterIP      1 => 10.0.0.251:53        
	 2    10.96.0.10:9153      ClusterIP      1 => 10.0.0.251:9153      
	 3    10.106.214.25:3000   ClusterIP      1 => 10.0.0.90:3000       
	 4    10.111.116.89:9090   ClusterIP      1 => 10.0.0.2:9090        
	 5    10.96.66.132:69      ClusterIP      1 => 10.0.1.84:69         
	                                          2 => 10.0.1.52:69         
	 6    10.96.0.1:443        ClusterIP      1 => 192.168.36.11:6443   
	 7    10.96.66.132:80      ClusterIP      1 => 10.0.1.84:80         
	                                          2 => 10.0.1.52:80         
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-zggcq -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                              IPv6       IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                   
	 27         Disabled           Disabled          2560       k8s:app=grafana                                          fd02::1    10.0.0.90    ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                 
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                          
	                                                            k8s:io.kubernetes.pod.namespace=cilium-monitoring                                        
	 112        Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s2                                                       ready   
	                                                            reserved:host                                                                            
	 2245       Disabled           Disabled          4          reserved:health                                          fd02::81   10.0.0.201   ready   
	 2411       Disabled           Disabled          471        k8s:app=prometheus                                       fd02::7a   10.0.0.2     ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                 
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=prometheus-k8s                                   
	                                                            k8s:io.kubernetes.pod.namespace=cilium-monitoring                                        
	 3246       Disabled           Disabled          28075      k8s:io.cilium.k8s.policy.cluster=default                 fd02::51   10.0.0.251   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=coredns                                          
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                              
	                                                            k8s:k8s-app=kube-dns                                                                     
	 
Stderr:
 	 

===================== Exiting AfterFailed =====================
15:27:50 STEP: Running AfterEach for block EntireTestsuite K8sFQDNTest
15:27:50 STEP: Running AfterEach for block EntireTestsuite
```
</details

### PR DESCRIPTION
**Pull request by joestringer**
In general up until now, Cilium has expected endpointRoutes mode to be
set to exactly one value upon deployment and for that value to stay the
same for the remainder of operation. Toggling it can lead to a mix of
endpoints in different datapath modes which is not well covered in CI.

In Github issue #16717 we observed that if the testsuite toggles this
setting then we can end up with kubedns pods remaining in endpoint
routes mode, even though the rest of the daemon (and other pods) are not
configured in this mode. This can lead to connectivity issues in DNS,
and a range of test failures in subsequent tests because DNS is broken.

Longer term to resolve this, we could improve on Cilium to ensure that
users can successfully toggle this setting on or off at runtime and
properly handle this case, or alternatively shift all logic over to
endpoint-routes mode by default and disable the other option.

Given that CI for the master branch is in a poor state due to this issue
today, and that part of the issue is CI reconfiguring the datapath state
of Cilium during the test setup in an unsupported manner, this commit
proposes to force DNS pod redeployment as part of setup any time a test
reconfigures the endpointRoutes mode. This should mitigate the testing
side issue while we mull over the right longer-term solution.

Fixes: #16717
Fixes: https://github.com/cilium/cilium/pull/16227
Related: #14955

### CODE REVIEW

**Review by nebril — APPROVED** [review]

**Review by jibi — APPROVED** [review]

File: test/k8sT/DatapathConfiguration.go [hunk 1]
```diff
@@ -318,10 +323,14 @@ var _ = Describe("K8sDatapathConfig", func() {
...
 				"endpointRoutes.enabled": "true",
-			}, DeployCiliumOptionsAndDNS)
+			}, RedeployCiliumAfterDatapathChange)
 
 			Expect(testPodConnectivityAcrossNodes(kubectl)).Should(BeTrue(), "Connectivity test between nodes failed")
 		})
+
+		// CAUTION: endpointRoutes mode was toggled. The next test
+		// MUST redeploy kubedns via RedeployCiliumAfterDatapathChange
+		// or potentially face GH-16717.
```
Comment (pchaigno) [inline test/k8sT/DatapathConfiguration.go]: Couldn't we have a variable in `kubectl` to remember the current state of endpoint routes and use that to detect when we should restart DNS pods?

**Review by pchaigno — APPROVED** [review]

File: test/k8sT/DatapathConfiguration.go (hunk 1 above)
Comment (joestringer) [reply test/k8sT/DatapathConfiguration.go]: I briefly thought about this but discounted it with some hand-waving about storing state across tests being bad. Coming fresh after the weekend, I think this would be a much cleaner approach, so I'll try this out.

**Comment by joestringer** [comment]
test-me-please

File: test/k8sT/DatapathConfiguration.go (hunk 1 above)
Comment (pchaigno) [reply test/k8sT/DatapathConfiguration.go]: > storing state across tests being bad

Yeah, I was concerned about that as well, but relying on people to call the correct code in the correct order is probably worse.

**Review by pchaigno — APPROVED** [review]
New version LGTM as well.

**Comment by joestringer** [comment]
On the fence about v1.9 backport, from out-of-band discussion with @pchaigno this flake is likely caused by https://github.com/cilium/cilium/pull/16227 which was backported to v1.9. I briefly looked through scheduled CI job runs for v1.9 and didn't observe the issue at all. We'll hold off for now. Now that we know how to detect this problem, if we see it on v1.9 it's easy to figure out if we see this particular issue and if so we can backport.

**Comment by joestringer** [comment]
Hit #16813, which seems at first glance like maybe #15459 resurfacing. Given that this is addressing one of the most common flakes in the tree today, bypassing the failing build to merge.

CI-3.0 not necessary to pass since this only changes ginkgo test code.

**Comment by nbusseneau** [comment]
Marking for backport to 1.9 following discussion here: https://github.com/cilium/cilium/pull/18031#issuecomment-991084995
