### PR TITLE
iptables: Remove '--nowildcard' from socket match

### LINKED ISSUE #8945: CI: K8sServiceTest Tests NodePort BPF
The test suite seems to be flaky. The example failure:

```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.10-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:420
Pod "testclient-6zb5g" can not connect to service "http://127.0.0.1:32174"
Expected command: kubectl exec -n default testclient-6zb5g -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 8 http://127.0.0.1:32174 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Stdout:
 	 time-> DNS: '0.000021()', Connect: '0.000000',Transfer '0.000000', total '5.000594'
Stderr:
 	 command terminated with exit code 28 
```

The following instances of the failure were observed:

- From pod curl to ClusterIP.
- From pod curl to 127.0.0.1:NodePort
- From pod curl to PublicIP:NodePort

The tunnel / direct routing mode setting does not matter, as the test failed in both modes. In all cases `bpf_sock.c` (aka host-reachable services) was involved.

* https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/14436/testReport/junit/Suite-k8s-1/10/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan/ : 
[de1ae283_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan.zip](https://github.com/cilium/cilium/files/3516090/de1ae283_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan.zip)

* https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/14440/testReport/junit/Suite-k8s-1/10/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan/ : 
[d2d95800_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan.zip](https://github.com/cilium/cilium/files/3515203/d2d95800_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan.zip)

/cc @borkmann

### LINKED ISSUE #10118: CI: K8sServicesTest Checks service across nodes with L7 policy Tests NodePort with L7 Policy: tftp connect via IPv6 failed
```

/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.17-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430
Pod "testclient-4h27j" can not connect to service "tftp://[::ffff:192.168.36.11]:31270/hello"
Expected command: kubectl exec -n default testclient-4h27j -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 8 tftp://[::ffff:192.168.36.11]:31270/hello -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Stdout:
 	 time-> DNS: '0.000037()', Connect: '0.000074',Transfer '0.000000', total '4.999814'
Stderr:
 	 command terminated with exit code 28
	 

/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.17-gopath/src/github.com/cilium/cilium/test/k8sT/Services.go:373
```

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/16973/testReport/junit/Suite-k8s-1/17/K8sServicesTest_Checks_service_across_nodes_with_L7_policy_Tests_NodePort_with_L7_Policy/

### LINKED ISSUE #10231: CI: K8sServicesTest Checks service across nodes Tests NodePort (kube-proxy)
## CI failure

```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.15-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430
Pod "testclient-6hhm2" can not connect to service "tftp://[::ffff:192.168.36.11]:30880/hello"
Expected command: kubectl exec -n default testclient-6hhm2 -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 8 tftp://[::ffff:192.168.36.11]:30880/hello -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Stdout:
 	 time-> DNS: '0.000018()', Connect: '0.000035',Transfer '0.000000', total '5.001616'
Stderr:
 	 command terminated with exit code 28
	 

/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.15-gopath/src/github.com/cilium/cilium/test/k8sT/Services.go:487

Standard Output

Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Cilium pods: [cilium-9kx2j cilium-xrglx]
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
Pod                          Ingress   Egress
coredns-86cd554449-49xpk     false     false
test-k8s2-5dc84ddf57-kzk6b   false     false
testclient-6hhm2             false     false
testclient-dmgkb             false     false
testds-hbx9n                 false     false
testds-lmmx9                 false     false
Cilium agent 'cilium-9kx2j': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 19 Failed 0
Cilium agent 'cilium-xrglx': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 26 Failed 0

```

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/2867/

[test_results_Cilium-PR-Ginkgo-Tests-K8s_2867_BDD-Test-k8s-1.15.zip](https://github.com/cilium/cilium/files/4219313/test_results_Cilium-PR-Ginkgo-Tests-K8s_2867_BDD-Test-k8s-1.15.zip)

### LINKED ISSUE #10669: CI: Suite-k8s-1.11.K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with direct routing Tests HostPort
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/18125/testReport/junit/Suite-k8s-1/11/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_HostPort/

Uploaded file:
[2ba30b89_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_HostPort.zip](https://github.com/cilium/cilium/files/4370682/2ba30b89_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_HostPort.zip)

```
Stacktrace
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430
k8s1 host can not connect to service "tftp://192.168.36.12:6969/hello"
Expected command: kubectl exec -n kube-system log-gatherer-xcwxq -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 8 tftp://192.168.36.12:6969/hello -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Stdout:
 	 time-> DNS: '0.000022()', Connect: '0.000038',Transfer '0.000000', total '5.001587'
Stderr:
 	 command terminated with exit code 28
	 

/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/k8sT/Services.go:657
Standard Output
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Cilium pods: [cilium-fpcp5 cilium-xxts6]
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
Pod                          Ingress   Egress
testds-bxn89                           
app1-798d4f944d-gt8pt                  
app3-68fb594d47-nxxmw                  
coredns-687db6485c-qcst5               
testclient-25l9t                       
testclient-tmrnh                       
app2-dc85b4585-mwtdc                   
test-k8s2-848b6f7864-8p5xm             
testds-2z4wc                           
Cilium agent 'cilium-fpcp5': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 23 Failed 0
Cilium agent 'cilium-xxts6': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 27 Failed 0

Standard Error
STEP: Making 10 curl requests from k8s2 to "http://192.168.36.12:8080"
STEP: Making 10 curl requests from k8s2 to "tftp://192.168.36.12:6969/hello"
STEP: Making 10 curl requests from k8s1 to "http://192.168.36.12:8080"
STEP: Making 10 curl requests from k8s1 to "tftp://192.168.36.12:6969/hello"
=== Test Finished at 2020-03-23T15:03:34Z====
===================== TEST FAILED =====================
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE           NAME                               READY   STATUS    RESTARTS   AGE   IP              NODE   NOMINATED NODE
	 default             test-k8s2-848b6f7864-8p5xm         2/2     Running   0          7m    10.10.1.82      k8s2   <none>
	 default             testclient-25l9t                   1/1     Running   0          7m    10.10.1.87      k8s2   <none>
	 default             testclient-tmrnh                   1/1     Running   0          7m    10.10.0.3       k8s1   <none>
	 default             testds-2z4wc                       2/2     Running   0          7m    10.10.1.50      k8s2   <none>
	 default             testds-bxn89                       2/2     Running   0          7m    10.10.0.39      k8s1   <none>
	 external-ips-test   app1-798d4f944d-gt8pt              2/2     Running   0          57m   10.10.0.174     k8s1   <none>
	 external-ips-test   app2-dc85b4585-mwtdc               2/2     Running   0          57m   10.10.0.150     k8s1   <none>
	 external-ips-test   app3-68fb594d47-nxxmw              2/2     Running   0          57m   10.10.1.179     k8s2   <none>
	 external-ips-test   host-client-f57qx                  1/1     Running   0          57m   192.168.36.11   k8s1   <none>
	 external-ips-test   host-client-pq5qn                  1/1     Running   0          57m   192.168.36.12   k8s2   <none>
	 external-ips-test   host-server-1-56c9467d4b-wkslh     2/2     Running   0          57m   192.168.36.11   k8s1   <none>
	 external-ips-test   host-server-2-b8d89c58c-2gtds      2/2     Running   0          57m   192.168.36.11   k8s1   <none>
	 kube-system         cilium-fpcp5                       1/1     Running   0          3m    192.168.36.11   k8s1   <none>
	 kube-system         cilium-operator-669595bd79-jl6pb   1/1     Running   0          3m    192.168.36.12   k8s2   <none>
	 kube-system         cilium-xxts6                       1/1     Running   0          3m    192.168.36.12   k8s2   <none>
	 kube-system         coredns-687db6485c-qcst5           1/1     Running   0          3m    10.10.1.70      k8s2   <none>
	 kube-system         etcd-k8s1                          1/1     Running   0          1h    192.168.36.11   k8s1   <none>
	 kube-system         kube-apiserver-k8s1                1/1     Running   0          1h    192.168.36.11   k8s1   <none>
	 kube-system         kube-controller-manager-k8s1       1/1     Running   0          1h    192.168.36.11   k8s1   <none>
	 kube-system         kube-scheduler-k8s1                1/1     Running   0          1h    192.168.36.11   k8s1   <none>
	 kube-system         log-gatherer-8pttx                 1/1     Running   0          1h    192.168.36.12   k8s2   <none>
	 kube-system         log-gatherer-b6xb7                 1/1     Running   0          1h    192.168.36.13   k8s3   <none>
	 kube-system         log-gatherer-xcwxq                 1/1     Running   0          1h    192.168.36.11   k8s1   <none>
	 kube-system         registry-adder-9nx46               1/1     Running   0          1h    192.168.36.12   k8s2   <none>
	 kube-system         registry-adder-nw2nh               1/1     Running   0          1h    192.168.36.13   k8s3   <none>
	 kube-system         registry-adder-qcxxv               1/1     Running   0          1h    192.168.36.11   k8s1   <none>
	 
Stderr:
 	 

Fetching command output from pods [cilium-fpcp5 cilium-xxts6]
cmd: kubectl exec -n kube-system cilium-fpcp5 -- cilium service list
Exitcode: 0 
Stdout:
 	 ID   Frontend               Service Type   Backend                    
	 1    10.96.0.10:53          ClusterIP      1 => 10.10.1.70:53         
	 2    10.96.0.1:443          ClusterIP      1 => 192.168.36.11:6443    
	 3    10.96.106.15:82        ClusterIP      1 => 10.10.0.174:80        
	 4    192.0.2.223:82         ExternalIPs    1 => 10.10.0.174:80        
	 5    172.28.128.3:82        ExternalIPs    1 => 10.10.0.174:80        
	 6    192.168.36.11:82       ExternalIPs    1 => 10.10.0.174:80        
	 7    10.111.205.107:30002   ClusterIP      1 => 10.10.0.174:80        
	 8    192.168.36.11:30002    ExternalIPs    1 => 10.10.0.174:80        
	 9    192.0.2.223:30002      ExternalIPs    1 => 10.10.0.174:80        
	 10   172.28.128.3:30002     ExternalIPs    1 => 10.10.0.174:80        
	 11   10.103.71.137:83       ClusterIP      1 => 10.10.0.150:80        
	 12   0.0.0.0:30003          NodePort       1 => 10.10.0.150:80        
	 13   192.168.36.11:30005    NodePort       1 => 192.168.36.11:30006   
	 14   10.10.0.72:30003       NodePort       1 => 10.10.0.150:80        
	 15   10.96.52.158:84        ClusterIP      1 => 192.168.36.11:20004   
	 16   10.10.0.72:30004       NodePort       1 => 192.168.36.11:20004   
	 17   0.0.0.0:30004          NodePort       1 => 192.168.36.11:20004   
	 18   192.168.36.11:30003    NodePort       1 => 10.10.0.150:80        
	 19   10.108.76.177:85       ClusterIP      1 => 192.168.36.11:30006   
	 20   0.0.0.0:30005          NodePort       1 => 192.168.36.11:30006   
	 21   192.168.36.11:30004    NodePort       1 => 192.168.36.11:20004   
	 22   10.10.0.72:30005       NodePort       1 => 192.168.36.11:30006   
	 39   10.102.193.208:80      ClusterIP      1 => 10.10.1.50:80         
	                                            2 => 10.10.0.39:80         
	 40   10.102.193.208:69      ClusterIP      1 => 10.10.1.50:69         
	                                            2 => 10.10.0.39:69         
	 41   10.111.98.12:10069     ClusterIP      1 => 10.10.1.50:69         
	                                            2 => 10.10.0.39:69         
	 42   10.111.98.12:10080     ClusterIP      1 => 10.10.1.50:80         
	                                            2 => 10.10.0.39:80         
	 43   0.0.0.0:30549          NodePort       1 => 10.10.1.50:80         
	                                            2 => 10.10.0.39:80         
	 44   192.168.36.11:30549    NodePort       1 => 10.10.1.50:80         
	                                            2 => 10.10.0.39:80         
	 45   10.104.143.106:2379    ClusterIP                                 
	 46   10.10.0.72:30549       NodePort       1 => 10.10.1.50:80         
	                                            2 => 10.10.0.39:80         
	 47   0.0.0.0:30467          NodePort       1 => 10.10.1.50:69         
	                                            2 => 10.10.0.39:69         
	 48   192.168.36.11:30467    NodePort       1 => 10.10.1.50:69         
	                                            2 => 10.10.0.39:69         
	 49   10.10.0.72:30467       NodePort       1 => 10.10.1.50:69         
	                                            2 => 10.10.0.39:69         
	 50   10.109.228.117:10069   ClusterIP      1 => 10.10.1.50:69         
	                                            2 => 10.10.0.39:69         
	 51   10.109.228.117:10080   ClusterIP      1 => 10.10.1.50:80         
	                                            2 => 10.10.0.39:80         
	 52   192.168.36.11:31146    NodePort       1 => 10.10.0.39:69         
	 53   10.10.0.72:31146       NodePort       1 => 10.10.0.39:69         
	 54   0.0.0.0:31146          NodePort       1 => 10.10.0.39:69         
	 55   0.0.0.0:30932          NodePort       1 => 10.10.0.39:80         
	 56   192.168.36.11:30932    NodePort       1 => 10.10.0.39:80         
	 57   10.10.0.72:30932       NodePort       1 => 10.10.0.39:80         
	 58   10.98.128.75:10069     ClusterIP      1 => 10.10.1.82:69         
	 59   10.98.128.75:10080     ClusterIP      1 => 10.10.1.82:80         
	 60   10.10.0.72:32205       NodePort                                  
	 61   0.0.0.0:32205          NodePort                                  
	 62   192.168.36.11:32205    NodePort                                  
	 63   0.0.0.0:31219          NodePort                                  
	 64   192.168.36.11:31219    NodePort                                  
	 65   10.10.0.72:31219       NodePort                                  
	 66   10.98.7.16:10080       ClusterIP      1 => 10.10.1.82:80         
	 67   10.98.7.16:10069       ClusterIP      1 => 10.10.1.82:69         
	 68   0.0.0.0:31912          NodePort       1 => 10.10.1.82:80         
	 69   192.168.36.11:31912    NodePort       1 => 10.10.1.82:80         
	 70   10.10.0.72:31912       NodePort       1 => 10.10.1.82:80         
	 71   0.0.0.0:30396          NodePort       1 => 10.10.1.82:69         
	 72   192.168.36.11:30396    NodePort       1 => 10.10.1.82:69         
	 73   10.10.0.72:30396       NodePort       1 => 10.10.1.82:69         
	 74   10.110.81.55:80        ClusterIP      1 => 10.10.1.50:80         
	                                            2 => 10.10.0.39:80         
	 75   0.0.0.0:30636          NodePort       1 => 10.10.1.50:80         
	                                            2 => 10.10.0.39:80         
	 76   192.168.36.11:30636    NodePort       1 => 10.10.1.50:80         
	                                            2 => 10.10.0.39:80         
	 77   10.10.0.72:30636       NodePort       1 => 10.10.1.50:80         
	                                            2 => 10.10.0.39:80         
	 78   10.106.94.198:80       ClusterIP      1 => 10.10.1.82:80         
	 79   192.168.36.11:30070    NodePort                                  
	 80   10.10.0.72:30070       NodePort                                  
	 81   0.0.0.0:30070          NodePort                                  
	 82   192.168.36.12:8080     HostPort       1 => 10.10.1.82:80         
	 83   192.168.36.12:6969     HostPort       1 => 10.10.1.82:69         
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-fpcp5 -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                         IPv6                 IPv4          STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                         
	 12         Disabled           Disabled          4089       k8s:id=app1                                         f00d::a0b:0:0:60eb   10.10.0.174   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                       
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                
	                                                            k8s:io.kubernetes.pod.namespace=external-ips-test                                              
	 163        Disabled           Disabled          18474      k8s:io.cilium.k8s.policy.cluster=default            f00d::a0b:0:0:9485   10.10.0.3     ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                
	                                                            k8s:io.kubernetes.pod.namespace=default                                                        
	                                                            k8s:zgroup=testDSClient                                                                        
	 449        Disabled           Disabled          12482      k8s:id=app2                                         f00d::a0b:0:0:a84f   10.10.0.150   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                       
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                
	                                                            k8s:io.kubernetes.pod.namespace=external-ips-test                                              
	 2850       Disabled           Disabled          27308      k8s:io.cilium.k8s.policy.cluster=default            f00d::a0b:0:0:b957   10.10.0.39    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                
	                                                            k8s:io.kubernetes.pod.namespace=default                                                        
	                                                            k8s:zgroup=testDS                                                                              
	 3568       Disabled           Disabled          4          reserved:health                                     f00d::a0b:0:0:4719   10.10.0.52    ready   
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-xxts6 -- cilium service list
Exitcode: 0 
Stdout:
 	 ID   Frontend               Service Type   Backend                    
	 1    10.96.0.1:443          ClusterIP      1 => 192.168.36.11:6443    
	 2    10.96.0.10:53          ClusterIP      1 => 10.10.1.70:53         
	 3    10.96.106.15:82        ClusterIP      1 => 10.10.0.174:80        
	 4    192.0.2.223:82         ExternalIPs    1 => 10.10.0.174:80        
	 5    172.28.128.3:82        ExternalIPs    1 => 10.10.0.174:80        
	 6    192.168.36.11:82       ExternalIPs    1 => 10.10.0.174:80        
	 7    10.111.205.107:30002   ClusterIP      1 => 10.10.0.174:80        
	 8    172.28.128.3:30002     ExternalIPs    1 => 10.10.0.174:80        
	 9    192.168.36.11:30002    ExternalIPs    1 => 10.10.0.174:80        
	 10   192.0.2.223:30002      ExternalIPs    1 => 10.10.0.174:80        
	 11   10.103.71.137:83       ClusterIP      1 => 10.10.0.150:80        
	 12   0.0.0.0:30003          NodePort       1 => 10.10.0.150:80        
	 13   192.168.36.12:30003    NodePort       1 => 10.10.0.150:80        
	 14   10.10.1.254:30003      NodePort       1 => 10.10.0.150:80        
	 15   10.96.52.158:84        ClusterIP      1 => 192.168.36.11:20004   
	 16   0.0.0.0:30004          NodePort       1 => 192.168.36.11:20004   
	 17   192.168.36.12:30004    NodePort       1 => 192.168.36.11:20004   
	 18   10.10.1.254:30004      NodePort       1 => 192.168.36.11:20004   
	 19   10.108.76.177:85       ClusterIP      1 => 192.168.36.11:30006   
	 20   0.0.0.0:30005          NodePort       1 => 192.168.36.11:30006   
	 21   192.168.36.12:30005    NodePort       1 => 192.168.36.11:30006   
	 22   10.10.1.254:30005      NodePort       1 => 192.168.36.11:30006   
	 39   10.102.193.208:80      ClusterIP      1 => 10.10.1.50:80         
	                                            2 => 10.10.0.39:80         
	 40   10.102.193.208:69      ClusterIP      1 => 10.10.1.50:69         
	                                            2 => 10.10.0.39:69         
	 41   10.111.98.12:10080     ClusterIP      1 => 10.10.1.50:80         
	                                            2 => 10.10.0.39:80         
	 42   10.111.98.12:10069     ClusterIP      1 => 10.10.1.50:69         
	                                            2 => 10.10.0.39:69         
	 43   0.0.0.0:30549          NodePort       1 => 10.10.1.50:80         
	                                            2 => 10.10.0.39:80         
	 44   192.168.36.12:30549    NodePort       1 => 10.10.1.50:80         
	                                            2 => 10.10.0.39:80         
	 45   10.104.143.106:2379    ClusterIP                                 
	 46   10.10.1.254:30549      NodePort       1 => 10.10.1.50:80         
	                                            2 => 10.10.0.39:80         
	 47   0.0.0.0:30467          NodePort       1 => 10.10.1.50:69         
	                                            2 => 10.10.0.39:69         
	 48   192.168.36.12:30467    NodePort       1 => 10.10.1.50:69         
	                                            2 => 10.10.0.39:69         
	 49   10.10.1.254:30467      NodePort       1 => 10.10.1.50:69         
	                                            2 => 10.10.0.39:69         
	 50   10.109.228.117:10069   ClusterIP      1 => 10.10.1.50:69         
	                                            2 => 10.10.0.39:69         
	 51   10.109.228.117:10080   ClusterIP      1 => 10.10.1.50:80         
	                                            2 => 10.10.0.39:80         
	 52   192.168.36.12:30932    NodePort       1 => 10.10.1.50:80         
	 53   10.10.1.254:30932      NodePort       1 => 10.10.1.50:80         
	 54   0.0.0.0:30932          NodePort       1 => 10.10.1.50:80         
	 55   0.0.0.0:31146          NodePort       1 => 10.10.1.50:69         
	 56   192.168.36.12:31146    NodePort       1 => 10.10.1.50:69         
	 57   10.10.1.254:31146      NodePort       1 => 10.10.1.50:69         
	 58   10.98.128.75:10080     ClusterIP      1 => 10.10.1.82:80         
	 59   10.98.128.75:10069     ClusterIP      1 => 10.10.1.82:69         
	 60   0.0.0.0:31219          NodePort       1 => 10.10.1.82:80         
	 61   192.168.36.12:31219    NodePort       1 => 10.10.1.82:80         
	 62   10.10.1.254:31219      NodePort       1 => 10.10.1.82:80         
	 63   0.0.0.0:32205          NodePort       1 => 10.10.1.82:69         
	 64   192.168.36.12:32205    NodePort       1 => 10.10.1.82:69         
	 65   10.10.1.254:32205      NodePort       1 => 10.10.1.82:69         
	 66   10.98.7.16:10080       ClusterIP      1 => 10.10.1.82:80         
	 67   10.98.7.16:10069       ClusterIP      1 => 10.10.1.82:69         
	 68   0.0.0.0:31912          NodePort       1 => 10.10.1.82:80         
	 69   192.168.36.12:31912    NodePort       1 => 10.10.1.82:80         
	 70   10.10.1.254:31912      NodePort       1 => 10.10.1.82:80         
	 71   0.0.0.0:30396          NodePort       1 => 10.10.1.82:69         
	 72   192.168.36.12:30396    NodePort       1 => 10.10.1.82:69         
	 73   10.10.1.254:30396      NodePort       1 => 10.10.1.82:69         
	 74   10.110.81.55:80        ClusterIP      1 => 10.10.1.50:80         
	                                            2 => 10.10.0.39:80         
	 75   0.0.0.0:30636          NodePort       1 => 10.10.1.50:80         
	                                            2 => 10.10.0.39:80         
	 76   192.168.36.12:30636    NodePort       1 => 10.10.1.50:80         
	                                            2 => 10.10.0.39:80         
	 77   10.10.1.254:30636      NodePort       1 => 10.10.1.50:80         
	                                            2 => 10.10.0.39:80         
	 78   10.106.94.198:80       ClusterIP      1 => 10.10.1.82:80         
	 79   0.0.0.0:30070          NodePort       1 => 10.10.1.82:80         
	 80   192.168.36.12:30070    NodePort       1 => 10.10.1.82:80         
	 81   10.10.1.254:30070      NodePort       1 => 10.10.1.82:80         
	 82   192.168.36.12:8080     HostPort       1 => 10.10.1.82:80         
	 83   192.168.36.12:6969     HostPort       1 => 10.10.1.82:69         
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-xxts6 -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                         IPv6                 IPv4          STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                         
	 83         Disabled           Disabled          55670      k8s:io.cilium.k8s.policy.cluster=default            f00d::a0c:0:0:4174   10.10.1.70    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=coredns                                                
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                    
	                                                            k8s:k8s-app=kube-dns                                                                           
	 503        Disabled           Disabled          27308      k8s:io.cilium.k8s.policy.cluster=default            f00d::a0c:0:0:79d0   10.10.1.50    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                
	                                                            k8s:io.kubernetes.pod.namespace=default                                                        
	                                                            k8s:zgroup=testDS                                                                              
	 686        Disabled           Disabled          10426      k8s:id=app3                                         f00d::a0c:0:0:6fb1   10.10.1.179   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                       
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                
	                                                            k8s:io.kubernetes.pod.namespace=external-ips-test                                              
	 1736       Disabled           Disabled          24008      k8s:io.cilium.k8s.policy.cluster=default            f00d::a0c:0:0:97f4   10.10.1.82    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                
	                                                            k8s:io.kubernetes.pod.namespace=default                                                        
	                                                            k8s:zgroup=test-k8s2                                                                           
	 2157       Disabled           Disabled          4          reserved:health                                     f00d::a0c:0:0:5623   10.10.1.2     ready   
	 2508       Disabled           Disabled          18474      k8s:io.cilium.k8s.policy.cluster=default            f00d::a0c:0:0:4907   10.10.1.87    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                
	                                                            k8s:io.kubernetes.pod.namespace=default                                                        
	                                                            k8s:zgroup=testDSClient                                                                        
	 
Stderr:
 	 

===================== Exiting AfterFailed =====================
```

### LINKED ISSUE #11313: CI: Suite-k8s-1.18.K8sServicesTest Checks service across nodes with L7 policy Tests NodePort with L7 Policy: Pod cannot connect to service via tftp (failed in request #/10)
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/4658/testReport/Suite-k8s-1/18/K8sServicesTest_Checks_service_across_nodes_with_L7_policy_Tests_NodePort_with_L7_Policy/

```
/home/jenkins/workspace/cilium-ginkgo_cilium_master/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:431
Pod "testclient-57gvr" can not connect to service "tftp://192.168.36.11:32377/hello" (failed in request 8/10)
Expected command: kubectl exec -n default testclient-57gvr -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 8 tftp://192.168.36.11:32377/hello -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Stdout:
 	 time-> DNS: '0.000018()', Connect: '0.000033',Transfer '0.000000', total '5.001023'
Stderr:
 	 command terminated with exit code 28
	 

/home/jenkins/workspace/cilium-ginkgo_cilium_master/k8s-1.18-gopath/src/github.com/cilium/cilium/test/k8sT/Services.go:611
```

[18927639_K8sServicesTest_Checks_service_across_nodes_with_L7_policy_Tests_NodePort_with_L7_Policy.zip](https://github.com/cilium/cilium/files/4575558/18927639_K8sServicesTest_Checks_service_across_nodes_with_L7_policy_Tests_NodePort_with_L7_Policy.zip)

### LINKED ISSUE #11867: CI: K8sServicesTest Checks service across nodes with L4 policy Tests NodePort with L4 Policy
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/1.14-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:512
Request from testclient-4wxwt pod to service tftp://[::ffff:192.168.36.11]:30747/hello failed
Expected command: kubectl exec -n default testclient-4wxwt -- /bin/sh -c 'set -e; for i in $(seq 1 10); do curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 tftp://[::ffff:192.168.36.11]:30747/hello; done' 
To succeed, but it failed:
Exitcode: 28 
Stdout:
	 Hostname: testds-xfkdm
	 
	 Request Information:
	 	client_address=10.10.0.106
	 	client_port=59279
	 	real path=/hello
	 	request_scheme=tftp
	 
	 
	 Hostname: testds-2zkmq
	 
	 Request Information:
	 	client_address=10.0.2.15
	 	client_port=51920
	 	real path=/hello
	 	request_scheme=tftp
	 
	 
	 Hostname: testds-2zkmq
	 
	 Request Information:
	 	client_address=10.0.2.15
	 	client_port=48402
	 	real path=/hello
	 	request_scheme=tftp
	 
	 
	 Hostname: testds-2zkmq
	 
	 Request Information:
	 	client_address=10.0.2.15
	 	client_port=38149
	 	real path=/hello
	 	request_scheme=tftp
	 
	 
	 Hostname: testds-2zkmq
	 
	 Request Information:
	 	client_address=10.0.2.15
	 	client_port=38765
	 	real path=/hello
	 	request_scheme=tftp
	 
	 
	 Hostname: testds-xfkdm
	 
	 Request Information:
	 	client_address=10.10.0.106
	 	client_port=58164
	 	real path=/hello
	 	request_scheme=tftp
	 
	 
	 Hostname: testds-2zkmq
	 
	 Request Information:
	 	client_address=10.0.2.15
	 	client_port=53457
	 	real path=/hello
	 	request_scheme=tftp
```

Assigning high priority because this was hit in the `test-missed-k8s` and those jobs are rarely executed so it might be a real bug and not a flake.
[3f7ee90a_K8sServicesTest_Checks_service_across_nodes_with_L4_policy_Tests_NodePort_with_L4_Policy.zip](https://github.com/cilium/cilium/files/4724777/3f7ee90a_K8sServicesTest_Checks_service_across_nodes_with_L4_policy_Tests_NodePort_with_L4_Policy.zip)

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/3151/testReport/junit/Suite-k8s-1/14/K8sServicesTest_Checks_service_across_nodes_with_L4_policy_Tests_NodePort_with_L4_Policy/

### LINKED ISSUE #12127: CI: K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with direct routing Tests with secondary NodePort device
Over the past 14 days, happened once in master and at least once in PRs:
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/5046/testReport/Suite-k8s-1/11/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_secondary_NodePort_device/
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Kernel/2145/testReport/Suite-k8s-1/17/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_secondary_NodePort_device/

Could be a duplicate of #8945?

### Stacktrace
```
/home/jenkins/workspace/cilium-ginkgo_cilium_master/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:512
Request from k8s1 to service tftp://[::ffff:127.0.0.1]:30151/hello failed
Expected command: kubectl exec -n kube-system log-gatherer-6c79s -- /bin/sh -c 'set -e; for i in $(seq 1 10); do curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 tftp://[::ffff:127.0.0.1]:30151/hello; done' 
To succeed, but it failed:
Exitcode: 28 
Stdout:
 	 
	 Hostname: testds-hz59j
	 
	 Request Information:
	 	client_address=192.168.36.11
	 	client_port=55510
	 	real path=/hello
	 	request_scheme=tftp
	 
	 
	 Hostname: testds-hz59j
	 
	 Request Information:
	 	client_address=192.168.36.11
	 	client_port=52738
	 	real path=/hello
	 	request_scheme=tftp
	 
	 
	 Hostname: testds-hz59j
	 
	 Request Information:
	 	client_address=192.168.36.11
	 	client_port=33402
	 	real path=/hello
	 	request_scheme=tftp
	 
	 
	 Hostname: testds-hz59j
	 
	 Request Information:
	 	client_address=192.168.36.11
	 	client_port=47691
	 	real path=/hello
	 	request_scheme=tftp
	 
	 
	 Hostname: testds-hz59j
	 
	 Request Information:
	 	client_address=192.168.36.11
	 	client_port=50861
	 	real path=/hello
	 	request_scheme=tftp
	 
	 
Stderr:
 	 command terminated with exit code 28
	 

/home/jenkins/workspace/cilium-ginkgo_cilium_master/k8s-1.11-gopath/src/github.com/cilium/cilium/test/k8sT/Services.go:676
```

### Standard Output
```
Number of "context deadline exceeded" in logs: 0
⚠️  Number of "level=error" in logs: 8
⚠️  Number of "level=warning" in logs: 54
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
Top 5 errors/warnings:
Deleting no longer present service
Mutation detector is enabled, this will result in memory leakage.
Unable to enqueue endpoint policy visibility event
Hubble server will be exposing its API insecurely on this address
BPF system config check: NOT OK.
Cilium pods: [cilium-8s7pc cilium-zfp98]
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
Pod                           Ingress   Egress
prometheus-556f8994ff-vjjsm             
test-k8s2-848b6f7864-wclfd              
testclient-jdxfl                        
testclient-pvq76                        
testds-ffr2t                            
testds-hz59j                            
coredns-687db6485c-fvvfj                
grafana-5968d99cc4-zr9qn                
Cilium agent 'cilium-8s7pc': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 28 Failed 0
Cilium agent 'cilium-zfp98': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 28 Failed 0
```

### Standard error
<details><summary>See standard error</summary>

```
21:49:30 STEP: Installing Cilium
21:49:31 STEP: Waiting for Cilium to become ready
21:49:31 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
21:49:36 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
21:49:41 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
21:49:46 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
21:49:51 STEP: Cilium DaemonSet not ready yet: only 1 of 2 desired pods are ready
21:49:56 STEP: Cilium DaemonSet not ready yet: only 1 of 2 desired pods are ready
21:50:01 STEP: Number of ready Cilium pods: 2
21:50:01 STEP: Validating if Kubernetes DNS is deployed
21:50:01 STEP: Checking if deployment is ready
21:50:01 STEP: Checking if kube-dns service is plumbed correctly
21:50:01 STEP: Checking if DNS can resolve
21:50:01 STEP: Checking if pods have identity
21:50:02 STEP: Kubernetes DNS is up and operational
21:50:02 STEP: Validating Cilium Installation
21:50:02 STEP: Performing Cilium controllers preflight check
21:50:02 STEP: Performing Cilium status preflight check
21:50:02 STEP: Performing Cilium health check
21:50:04 STEP: Performing Cilium service preflight check
21:50:04 STEP: Performing K8s service preflight check
21:50:05 STEP: Waiting for cilium-operator to be ready
21:50:05 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator")
21:50:05 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator") => <nil>
21:50:06 STEP: Making 10 curl requests from pod (host netns) k8s1 to "http://192.168.36.11:31686"
21:50:06 STEP: Making 10 curl requests from pod (host netns) k8s1 to "http://192.168.36.12:31686"
21:50:06 STEP: Making 10 curl requests from pod (host netns) k8s1 to "http://[::ffff:192.168.36.12]:31686"
21:50:06 STEP: Making 10 curl requests from pod (host netns) k8s1 to "tftp://192.168.36.11:30151/hello"
21:50:06 STEP: Making 10 curl requests from pod (host netns) k8s1 to "tftp://192.168.37.11:30151/hello"
21:50:06 STEP: Making 10 curl requests from pod (host netns) k8s1 to "tftp://[::ffff:192.168.36.11]:30151/hello"
21:50:06 STEP: Making 10 curl requests from pod (host netns) k8s1 to "http://[::ffff:192.168.36.11]:31686"
21:50:06 STEP: Making 10 curl requests from pod (host netns) k8s1 to "tftp://[::ffff:192.168.36.12]:30151/hello"
21:50:06 STEP: Making 10 curl requests from pod (host netns) k8s1 to "tftp://192.168.36.12:30151/hello"
21:50:06 STEP: Making 10 curl requests from pod (host netns) k8s1 to "http://192.168.37.11:31686"
21:50:06 STEP: Making 10 HTTP requests from outside cluster to "tftp://192.168.37.12:30151/hello"
21:50:06 STEP: Making 10 HTTP requests from outside cluster to "http://192.168.36.12:31686"
21:50:06 STEP: Making 10 curl requests from pod (host netns) k8s1 to "http://192.168.37.12:31686"
21:50:06 STEP: Making 10 curl requests from pod (host netns) k8s1 to "tftp://192.168.37.12:30151/hello"
21:50:06 STEP: Making 10 HTTP requests from outside cluster to "http://192.168.36.11:31686"
21:50:06 STEP: Making 10 HTTP requests from outside cluster to "tftp://192.168.36.11:30151/hello"
21:50:06 STEP: Making 10 HTTP requests from outside cluster to "http://192.168.37.11:31686"
21:50:06 STEP: Making 10 HTTP requests from outside cluster to "tftp://192.168.36.12:30151/hello"
21:50:06 STEP: Making 10 HTTP requests from outside cluster to "tftp://192.168.37.11:30151/hello"
21:50:06 STEP: Making 10 HTTP requests from outside cluster to "http://192.168.37.12:31686"
21:50:06 STEP: Making 10 curl requests from pod (host netns) k8s1 to "http://127.0.0.1:31686"
21:50:06 STEP: Making 10 curl requests from pod (host netns) k8s1 to "http://10.105.174.138:10080"
21:50:06 STEP: Making 10 curl requests from pod (host netns) k8s1 to "tftp://10.105.174.138:10069/hello"
21:50:06 STEP: Making 10 curl requests from pod (host netns) k8s1 to "http://[::ffff:127.0.0.1]:31686"
21:50:06 STEP: Making 10 curl requests from pod (host netns) k8s1 to "tftp://127.0.0.1:30151/hello"
21:50:06 STEP: Making 10 curl requests from pod (host netns) k8s1 to "tftp://[::ffff:127.0.0.1]:30151/hello"
21:50:07 STEP: Making 10 curl requests from testclient-jdxfl pod to service tftp://10.105.174.138:10069/hello
21:50:07 STEP: Making 10 curl requests from testclient-jdxfl pod to service http://10.105.174.138:10080
21:50:07 STEP: Making 10 curl requests from testclient-jdxfl pod to service http://192.168.36.11:31686
21:50:07 STEP: Making 10 curl requests from testclient-jdxfl pod to service tftp://192.168.36.11:30151/hello
21:50:07 STEP: Making 10 curl requests from testclient-jdxfl pod to service http://[::ffff:192.168.36.11]:31686
21:50:07 STEP: Making 10 curl requests from testclient-jdxfl pod to service tftp://[::ffff:192.168.36.11]:30151/hello
21:50:07 STEP: Making 10 curl requests from testclient-jdxfl pod to service http://192.168.36.12:31686
21:50:07 STEP: Making 10 curl requests from testclient-jdxfl pod to service tftp://192.168.36.12:30151/hello
21:50:07 STEP: Making 10 curl requests from testclient-jdxfl pod to service http://[::ffff:192.168.36.12]:31686
21:50:07 STEP: Making 10 curl requests from testclient-jdxfl pod to service tftp://[::ffff:192.168.36.12]:30151/hello
21:50:09 STEP: Making 10 curl requests from testclient-pvq76 pod to service http://10.105.174.138:10080
21:50:10 STEP: Making 10 curl requests from testclient-pvq76 pod to service http://192.168.36.11:31686
21:50:10 STEP: Making 10 curl requests from testclient-pvq76 pod to service tftp://192.168.36.11:30151/hello
21:50:10 STEP: Making 10 curl requests from testclient-pvq76 pod to service tftp://10.105.174.138:10069/hello
21:50:10 STEP: Making 10 curl requests from testclient-pvq76 pod to service http://[::ffff:192.168.36.12]:31686
21:50:11 STEP: Making 10 curl requests from testclient-pvq76 pod to service tftp://[::ffff:192.168.36.11]:30151/hello
21:50:11 STEP: Making 10 curl requests from testclient-pvq76 pod to service tftp://[::ffff:192.168.36.12]:30151/hello
21:50:11 STEP: Making 10 curl requests from testclient-pvq76 pod to service http://192.168.36.12:31686
21:50:11 STEP: Making 10 curl requests from testclient-pvq76 pod to service http://[::ffff:192.168.36.11]:31686
21:50:12 STEP: Making 10 curl requests from testclient-pvq76 pod to service tftp://192.168.36.12:30151/hello
FAIL: Request from k8s1 to service tftp://[::ffff:127.0.0.1]:30151/hello failed
Expected command: kubectl exec -n kube-system log-gatherer-6c79s -- /bin/sh -c 'set -e; for i in $(seq 1 10); do curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 tftp://[::ffff:127.0.0.1]:30151/hello; done' 
To succeed, but it failed:
Exitcode: 28 
Stdout:
 	 
	 Hostname: testds-hz59j
	 
	 Request Information:
	 	client_address=192.168.36.11
	 	client_port=55510
	 	real path=/hello
	 	request_scheme=tftp
	 
	 
	 Hostname: testds-hz59j
	 
	 Request Information:
	 	client_address=192.168.36.11
	 	client_port=52738
	 	real path=/hello
	 	request_scheme=tftp
	 
	 
	 Hostname: testds-hz59j
	 
	 Request Information:
	 	client_address=192.168.36.11
	 	client_port=33402
	 	real path=/hello
	 	request_scheme=tftp
	 
	 
	 Hostname: testds-hz59j
	 
	 Request Information:
	 	client_address=192.168.36.11
	 	client_port=47691
	 	real path=/hello
	 	request_scheme=tftp
	 
	 
	 Hostname: testds-hz59j
	 
	 Request Information:
	 	client_address=192.168.36.11
	 	client_port=50861
	 	real path=/hello
	 	request_scheme=tftp
	 
	 
Stderr:
 	 command terminated with exit code 28
	 

=== Test Finished at 2020-06-09T21:50:32Z====
21:50:32 STEP: Running JustAfterEach block for EntireTestsuite K8sServicesTest
===================== TEST FAILED =====================
21:50:38 STEP: Running AfterFailed block for EntireTestsuite K8sServicesTest
21:50:38 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium")
21:50:39 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium") => <nil>
21:50:39 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium")
21:50:40 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium") => <nil>
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE           NAME                               READY   STATUS    RESTARTS   AGE   IP              NODE   NOMINATED NODE
	 cilium-monitoring   grafana-5968d99cc4-zr9qn           1/1     Running   0          1h    10.0.1.218      k8s1   <none>
	 cilium-monitoring   prometheus-556f8994ff-vjjsm        1/1     Running   0          1h    10.0.1.191      k8s1   <none>
	 default             test-k8s2-848b6f7864-wclfd         2/2     Running   0          9m    10.0.0.26       k8s2   <none>
	 default             testclient-jdxfl                   1/1     Running   0          9m    10.0.1.206      k8s1   <none>
	 default             testclient-pvq76                   1/1     Running   0          9m    10.0.0.231      k8s2   <none>
	 default             testds-ffr2t                       2/2     Running   0          2m    10.0.1.81       k8s1   <none>
	 default             testds-hz59j                       2/2     Running   0          2m    10.0.0.96       k8s2   <none>
	 kube-system         cilium-8s7pc                       1/1     Running   0          1m    192.168.36.12   k8s2   <none>
	 kube-system         cilium-operator-5c59bd8f8c-46t6p   1/1     Running   0          1m    192.168.36.12   k8s2   <none>
	 kube-system         cilium-zfp98                       1/1     Running   0          1m    192.168.36.11   k8s1   <none>
	 kube-system         coredns-687db6485c-fvvfj           1/1     Running   0          1h    10.0.0.154      k8s2   <none>
	 kube-system         etcd-k8s1                          1/1     Running   0          1h    192.168.36.11   k8s1   <none>
	 kube-system         kube-apiserver-k8s1                1/1     Running   0          1h    192.168.36.11   k8s1   <none>
	 kube-system         kube-controller-manager-k8s1       1/1     Running   0          1h    192.168.36.11   k8s1   <none>
	 kube-system         kube-scheduler-k8s1                1/1     Running   0          1h    192.168.36.11   k8s1   <none>
	 kube-system         log-gatherer-6c79s                 1/1     Running   0          1h    192.168.36.11   k8s1   <none>
	 kube-system         log-gatherer-d28vk                 1/1     Running   0          1h    192.168.36.12   k8s2   <none>
	 kube-system         log-gatherer-qggqx                 1/1     Running   0          1h    192.168.36.13   k8s3   <none>
	 kube-system         registry-adder-4lfz9               1/1     Running   0          1h    192.168.36.13   k8s3   <none>
	 kube-system         registry-adder-dbsdh               1/1     Running   0          1h    192.168.36.12   k8s2   <none>
	 kube-system         registry-adder-lv2rf               1/1     Running   0          1h    192.168.36.11   k8s1   <none>
	 
Stderr:
 	 

Fetching command output from pods [cilium-8s7pc cilium-zfp98]
21:50:41 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium")
21:50:41 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium") => <nil>
21:50:41 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium")
21:50:41 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium") => <nil>
21:50:42 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium")
21:50:42 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium") => <nil>
21:50:43 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium")
21:50:43 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium") => <nil>
21:50:43 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium")
21:50:43 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium") => <nil>
21:50:44 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium")
21:50:44 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium") => <nil>
21:50:45 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium")
21:50:45 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium") => <nil>
21:50:45 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium")
21:50:45 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium") => <nil>
21:51:02 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs --field-selector='spec.nodeName!=k8s3'")
21:51:02 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs --field-selector='spec.nodeName!=k8s3'") => <nil>
21:51:02 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs --field-selector='spec.nodeName!=k8s3'")
21:51:02 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs --field-selector='spec.nodeName!=k8s3'") => <nil>
21:51:03 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs --field-selector='spec.nodeName!=k8s3'")
21:51:03 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs --field-selector='spec.nodeName!=k8s3'") => <nil>
cmd: kubectl exec -n kube-system cilium-8s7pc -- cilium service list
Exitcode: 0 
Stdout:
 	 ID   Frontend               Service Type   Backend                   
	 1    10.96.0.1:443          ClusterIP      1 => 192.168.36.11:6443   
	 2    10.96.0.10:53          ClusterIP      1 => 10.0.0.154:53        
	 3    10.103.46.88:3000      ClusterIP      1 => 10.0.1.218:3000      
	 4    10.104.46.46:9090      ClusterIP      1 => 10.0.1.191:9090      
	 5    192.168.36.11:20080    ExternalIPs    1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 6    192.168.36.11:20069    ExternalIPs    1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 7    192.168.37.12:30909    NodePort       1 => 10.0.0.96:80         
	 8    192.168.37.12:30811    NodePort       1 => 10.0.0.96:69         
	 9    10.99.47.23:80         ClusterIP      1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 10   10.99.47.23:69         ClusterIP      1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 11   10.105.174.138:10080   ClusterIP      1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 12   10.105.174.138:10069   ClusterIP      1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 13   192.168.36.12:31686    NodePort       1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 15   0.0.0.0:31686          NodePort       1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 16   0.0.0.0:30151          NodePort       1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 17   192.168.36.12:30151    NodePort       1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 19   10.104.207.11:10069    ClusterIP      1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 20   10.104.207.11:10080    ClusterIP      1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 22   192.168.36.12:31904    NodePort       1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 23   0.0.0.0:31904          NodePort       1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 24   0.0.0.0:30198          NodePort       1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 25   192.168.36.12:30198    NodePort       1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 27   10.100.168.224:10080   ClusterIP      1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 28   10.100.168.224:10069   ClusterIP      1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 30   192.168.36.12:30909    NodePort       1 => 10.0.0.96:80         
	 31   0.0.0.0:30909          NodePort       1 => 10.0.0.96:80         
	 32   192.168.36.12:30811    NodePort       1 => 10.0.0.96:69         
	 34   0.0.0.0:30811          NodePort       1 => 10.0.0.96:69         
	 35   10.99.147.49:10080     ClusterIP      1 => 10.0.0.26:80         
	 36   10.99.147.49:10069     ClusterIP      1 => 10.0.0.26:69         
	 37   192.168.36.12:31463    NodePort       1 => 10.0.0.26:80         
	 39   0.0.0.0:31463          NodePort       1 => 10.0.0.26:80         
	 40   192.168.36.12:31887    NodePort       1 => 10.0.0.26:69         
	 42   0.0.0.0:31887          NodePort       1 => 10.0.0.26:69         
	 43   10.98.104.36:10069     ClusterIP      1 => 10.0.0.26:69         
	 44   10.98.104.36:10080     ClusterIP      1 => 10.0.0.26:80         
	 45   192.168.36.12:31349    NodePort       1 => 10.0.0.26:69         
	 47   0.0.0.0:31349          NodePort       1 => 10.0.0.26:69         
	 48   192.168.36.12:31970    NodePort       1 => 10.0.0.26:80         
	 50   0.0.0.0:31970          NodePort       1 => 10.0.0.26:80         
	 51   10.108.221.123:80      ClusterIP      1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 53   0.0.0.0:30903          NodePort       1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 54   192.168.36.12:30903    NodePort       1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 55   10.101.43.190:80       ClusterIP      1 => 10.0.0.26:80         
	 56   192.168.36.12:31843    NodePort       1 => 10.0.0.26:80         
	 58   0.0.0.0:31843          NodePort       1 => 10.0.0.26:80         
	 59   10.98.120.47:20080     ClusterIP      1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 60   10.98.120.47:20069     ClusterIP      1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 61   192.0.2.233:20080      ExternalIPs    1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 62   192.0.2.233:20069      ExternalIPs    1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 64   0.0.0.0:32755          NodePort       1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 65   192.168.36.12:32755    NodePort       1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 66   192.168.36.12:31124    NodePort       1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 68   0.0.0.0:31124          NodePort       1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 69   192.168.36.12:8080     HostPort       1 => 10.0.0.26:80         
	 70   192.168.36.12:6969     HostPort       1 => 10.0.0.26:69         
	 71   192.168.37.12:30903    NodePort       1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 72   192.168.37.12:30198    NodePort       1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 73   192.168.37.12:31904    NodePort       1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 74   192.168.37.12:31887    NodePort       1 => 10.0.0.26:69         
	 75   192.168.37.12:31463    NodePort       1 => 10.0.0.26:80         
	 76   192.168.37.12:31970    NodePort       1 => 10.0.0.26:80         
	 77   192.168.37.12:31349    NodePort       1 => 10.0.0.26:69         
	 78   192.168.37.12:31843    NodePort       1 => 10.0.0.26:80         
	 79   192.168.37.12:31686    NodePort       1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 80   192.168.37.12:30151    NodePort       1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 81   192.168.37.12:32755    NodePort       1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 82   192.168.37.12:31124    NodePort       1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-8s7pc -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                       IPv6       IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                            
	 218        Disabled           Disabled          4          reserved:health                                   fd00::4b   10.0.0.137   ready   
	 1232       Disabled           Disabled          16555      k8s:io.cilium.k8s.policy.cluster=default          fd00::c8   10.0.0.154   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=coredns                                   
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                       
	                                                            k8s:k8s-app=kube-dns                                                              
	 2183       Disabled           Disabled          23024      k8s:io.cilium.k8s.policy.cluster=default          fd00::86   10.0.0.26    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                   
	                                                            k8s:io.kubernetes.pod.namespace=default                                           
	                                                            k8s:zgroup=test-k8s2                                                              
	 2474       Disabled           Disabled          5683       k8s:io.cilium.k8s.policy.cluster=default          fd00::cb   10.0.0.96    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                   
	                                                            k8s:io.kubernetes.pod.namespace=default                                           
	                                                            k8s:zgroup=testDS                                                                 
	 3093       Disabled           Disabled          1          reserved:host                                                             ready   
	 3254       Disabled           Disabled          10761      k8s:io.cilium.k8s.policy.cluster=default          fd00::33   10.0.0.231   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                   
	                                                            k8s:io.kubernetes.pod.namespace=default                                           
	                                                            k8s:zgroup=testDSClient                                                           
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-zfp98 -- cilium service list
Exitcode: 0 
Stdout:
 	 ID   Frontend               Service Type   Backend                   
	 1    10.104.46.46:9090      ClusterIP      1 => 10.0.1.191:9090      
	 2    10.96.0.1:443          ClusterIP      1 => 192.168.36.11:6443   
	 3    10.96.0.10:53          ClusterIP      1 => 10.0.0.154:53        
	 4    10.103.46.88:3000      ClusterIP      1 => 10.0.1.218:3000      
	 5    192.168.36.11:20080    ExternalIPs    1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 6    192.168.36.11:20069    ExternalIPs    1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 7    192.168.37.11:31843    NodePort                                 
	 8    192.168.37.11:31463    NodePort                                 
	 9    10.99.47.23:69         ClusterIP      1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 10   10.99.47.23:80         ClusterIP      1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 11   10.105.174.138:10080   ClusterIP      1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 12   10.105.174.138:10069   ClusterIP      1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 13   192.168.36.11:31686    NodePort       1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 15   0.0.0.0:31686          NodePort       1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 16   192.168.36.11:30151    NodePort       1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 18   0.0.0.0:30151          NodePort       1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 19   10.104.207.11:10069    ClusterIP      1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 20   10.104.207.11:10080    ClusterIP      1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 21   0.0.0.0:30198          NodePort       1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 22   192.168.36.11:30198    NodePort       1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 25   0.0.0.0:31904          NodePort       1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 26   192.168.36.11:31904    NodePort       1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 27   10.100.168.224:10080   ClusterIP      1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 28   10.100.168.224:10069   ClusterIP      1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 29   192.168.36.11:30909    NodePort       1 => 10.0.1.81:80         
	 31   0.0.0.0:30909          NodePort       1 => 10.0.1.81:80         
	 32   192.168.36.11:30811    NodePort       1 => 10.0.1.81:69         
	 34   0.0.0.0:30811          NodePort       1 => 10.0.1.81:69         
	 35   10.99.147.49:10080     ClusterIP      1 => 10.0.0.26:80         
	 36   10.99.147.49:10069     ClusterIP      1 => 10.0.0.26:69         
	 38   192.168.36.11:31463    NodePort                                 
	 39   0.0.0.0:31463          NodePort                                 
	 41   192.168.36.11:31887    NodePort                                 
	 42   0.0.0.0:31887          NodePort                                 
	 43   10.98.104.36:10080     ClusterIP      1 => 10.0.0.26:80         
	 44   10.98.104.36:10069     ClusterIP      1 => 10.0.0.26:69         
	 45   192.168.36.11:31970    NodePort       1 => 10.0.0.26:80         
	 47   0.0.0.0:31970          NodePort       1 => 10.0.0.26:80         
	 49   0.0.0.0:31349          NodePort       1 => 10.0.0.26:69         
	 50   192.168.36.11:31349    NodePort       1 => 10.0.0.26:69         
	 51   10.108.221.123:80      ClusterIP      1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 52   192.168.36.11:30903    NodePort       1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 54   0.0.0.0:30903          NodePort       1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 55   10.101.43.190:80       ClusterIP      1 => 10.0.0.26:80         
	 56   192.168.36.11:31843    NodePort                                 
	 58   0.0.0.0:31843          NodePort                                 
	 59   10.98.120.47:20080     ClusterIP      1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 60   10.98.120.47:20069     ClusterIP      1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 61   192.0.2.233:20080      ExternalIPs    1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 62   192.0.2.233:20069      ExternalIPs    1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 64   0.0.0.0:32755          NodePort       1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 65   192.168.36.11:32755    NodePort       1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 66   192.168.36.11:31124    NodePort       1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 68   0.0.0.0:31124          NodePort       1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 69   192.168.37.11:31887    NodePort                                 
	 70   192.168.37.11:30903    NodePort       1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 71   192.168.37.11:31686    NodePort       1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 72   192.168.37.11:30151    NodePort       1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 73   192.168.37.11:30909    NodePort       1 => 10.0.1.81:80         
	 74   192.168.37.11:30811    NodePort       1 => 10.0.1.81:69         
	 75   192.168.37.11:30198    NodePort       1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 76   192.168.37.11:31904    NodePort       1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 77   192.168.37.11:31970    NodePort       1 => 10.0.0.26:80         
	 78   192.168.37.11:31349    NodePort       1 => 10.0.0.26:69         
	 79   192.168.37.11:31124    NodePort       1 => 10.0.1.81:69         
	                                            2 => 10.0.0.96:69         
	 80   192.168.37.11:32755    NodePort       1 => 10.0.1.81:80         
	                                            2 => 10.0.0.96:80         
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-zfp98 -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                              IPv6        IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                    
	 168        Disabled           Disabled          10761      k8s:io.cilium.k8s.policy.cluster=default                 fd00::13a   10.0.1.206   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                           
	                                                            k8s:io.kubernetes.pod.namespace=default                                                   
	                                                            k8s:zgroup=testDSClient                                                                   
	 372        Disabled           Disabled          16453      k8s:app=prometheus                                       fd00::112   10.0.1.191   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                  
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=prometheus-k8s                                    
	                                                            k8s:io.kubernetes.pod.namespace=cilium-monitoring                                         
	 692        Disabled           Disabled          5683       k8s:io.cilium.k8s.policy.cluster=default                 fd00::17f   10.0.1.81    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                           
	                                                            k8s:io.kubernetes.pod.namespace=default                                                   
	                                                            k8s:zgroup=testDS                                                                         
	 1283       Disabled           Disabled          6100       k8s:app=grafana                                          fd00::1d9   10.0.1.218   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                  
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                           
	                                                            k8s:io.kubernetes.pod.namespace=cilium-monitoring                                         
	 1672       Disabled           Disabled          1          reserved:host                                                                     ready   
	 2514       Disabled           Disabled          4          reserved:health                                          fd00::136   10.0.1.125   ready   
	 
Stderr:
 	 

===================== Exiting AfterFailed =====================
21:51:03 STEP: Running AfterEach for block EntireTestsuite K8sServicesTest
21:51:03 STEP: Running AfterEach for block EntireTestsuite
```
</details>

[1dd77f1b_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_secondary_NodePort_device.zip](https://github.com/cilium/cilium/files/4790598/1dd77f1b_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_secondary_NodePort_device.zip)
[96a5b6da_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_secondary_NodePort_device.zip](https://github.com/cilium/cilium/files/4790604/96a5b6da_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_with_secondary_NodePort_device.zip)

### LINKED ISSUE #12241: DNS proxy intercepts TFTP response and send a DNS error response to TFTP server thousands of times
Found in logs of a failed CI test run (attached):
```
2020-06-15T21:12:19.262680843Z level=debug msg="Load 1-min: 0.24 5-min: 0.53 15min: 0.29" subsys=loadinfo type=background
2020-06-15T21:12:19.262705013Z level=debug msg="Memory: Total: 7974 Used: 868 (10.88%) Free: 4576 Buffers: 118 Cached: 2411" subsys=loadinfo type=background
2020-06-15T21:12:19.262709878Z level=debug msg="Swap: Total: 0 Used: 0 (0.00%) Free: 0" subsys=loadinfo type=background
2020-06-15T21:12:19.277248092Z level=debug msg="Handling request for /healthz" subsys=health-server
2020-06-15T21:12:20.335073725Z level=debug msg="Controller func execution time: 1.81µs" name=k8s-heartbeat subsys=controller uuid=690f6c74-af4c-11ea-aace-08002731e852
2020-06-15T21:12:20.435336539Z level=debug msg="Controller func execution time: 52.404µs" name=metricsmap-bpf-prom-sync subsys=controller uuid=69107f8b-af4c-11ea-aace-08002731e852
2020-06-15T21:12:20.460905785Z level=debug msg="GET /endpoint request" params="{HTTPRequest:0xc000c55900 Labels:[]}" subsys=daemon
2020-06-15T21:12:22.568019889Z level=debug msg="dnsproxy: Wrote DNS response (12/12 bytes) from 192.168.36.11:33241 to 192.168.36.12:31985" subsys=fqdn/dnsproxy
2020-06-15T21:12:22.575770403Z level=debug msg="dnsproxy: Wrote DNS response (12/12 bytes) from 192.168.36.11:33241 to 192.168.36.12:31985" subsys=fqdn/dnsproxy
2020-06-15T21:12:22.577000721Z level=debug msg="dnsproxy: Wrote DNS response (12/12 bytes) from 192.168.36.11:33241 to 192.168.36.12:31985" subsys=fqdn/dnsproxy
2020-06-15T21:12:22.577305779Z level=debug msg="dnsproxy: Wrote DNS response (12/12 bytes) from 192.168.36.11:33241 to 192.168.36.12:31985" subsys=fqdn/dnsproxy
...
2020-06-15T21:12:37.58690114Z level=debug msg="dnsproxy: Wrote DNS response (12/12 bytes) from 192.168.36.11:33241 to 192.168.36.12:31985" subsys=fqdn/dnsproxy
2020-06-15T21:12:37.586980691Z level=debug msg="dnsproxy: Wrote DNS response (12/12 bytes) from 192.168.36.11:33241 to 192.168.36.12:31985" subsys=fqdn/dnsproxy
2020-06-15T21:12:37.587170772Z level=debug msg="dnsproxy: Wrote DNS response (12/12 bytes) from 192.168.36.11:33241 to 192.168.36.12:31985" subsys=fqdn/dnsproxy
2020-06-15T21:12:37.58872813Z level=debug msg="dnsproxy: Wrote DNS response (12/12 bytes) from 192.168.36.11:33241 to 192.168.36.12:31985" subsys=fqdn/dnsproxy
2020-06-15T21:12:37.888053984Z level=debug msg="GET /config request" params="{HTTPRequest:0xc0015e4400}" subsys=daemon
2020-06-15T21:12:39.269112166Z level=debug msg="Load 1-min: 1.98 5-min: 0.90 15min: 0.42" subsys=loadinfo type=background
2020-06-15T21:12:39.269133362Z level=debug msg="Memory: Total: 7974 Used: 893 (11.21%) Free: 4546 Buffers: 118 Cached: 2415" subsys=loadinfo type=background
2020-06-15T21:12:39.269151279Z level=debug msg="Swap: Total: 0 Used: 0 (0.00%) Free: 0" subsys=loadinfo type=background
2020-06-15T21:12:39.269153706Z level=debug msg="NAME cilium-agent STATUS S PID 1 CPU: 5.52% MEM: 1.20% CMDLINE: cilium-agent --config-dir=/tmp/cilium/config-map MEM-EXT: RSS: 95 VMS: 751 Data: 0 Stack: 0 Locked: 0 Swap: 0" subsys=loadinfo type=background
2020-06-15T21:12:39.269156178Z level=debug msg="NAME cilium STATUS S PID 780 CPU: 21.58% MEM: 0.61% CMDLINE: cilium monitor -vv MEM-EXT: RSS: 48 VMS: 741 Data: 0 Stack: 0 Locked: 0 Swap: 0" subsys=loadinfo type=background
2020-06-15T21:12:39.300088612Z level=debug msg="Handling request for /healthz" subsys=health-server
```

The same message repeats 54339 times:
```
$ grep -c "dnsproxy: Wrote DNS response (12/12 bytes) from 192.168.36.11:33241 to 192.168.36.12:31985" pod-kube-system-cilium-gfpcl-cilium-agent.log
pod-kube-system-cilium-gfpcl-cilium-agent.log:54339
```

Ref: 
[4a93942f_K8sServicesTest_Checks_service_across_nodes_with_L4_policy_Tests_NodePort_with_L4_Policy.zip](https://github.com/cilium/cilium/files/4821056/4a93942f_K8sServicesTest_Checks_service_across_nodes_with_L4_policy_Tests_NodePort_with_L4_Policy.zip)

### LINKED ISSUE #12281: CI: K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with XDP, direct routing and Hybrid
Seen on net-next tests for #12254

```
/home/jenkins/workspace/Cilium-PR-K8s-oldest-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
Request from k8s1 to service tftp://192.168.36.12:31234/hello failed
Expected command: kubectl exec -n kube-system log-gatherer-smsnq -- /bin/bash -c 'fails=""; id=$RANDOM; for i in $(seq 1 10); do if curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 tftp://192.168.36.12:31234/hello -H "User-Agent: cilium-test-$id/$i"; then echo "Test round $id/$i exit code: $?"; else fails=$fails:$id/$i=$?; fi; done; if [ -n "$fails" ]; then echo "failed: $fails"; fi; cnt="${fails//[^:]}"; if [ ${#cnt} -gt 0 ]; then exit 42; fi' 
To succeed, but it failed:
Exitcode: 42 
Stdout:
 	 
	 Hostname: testds-znvgg
	 
	 Request Information:
	 	client_address=192.168.36.11
	 	client_port=57579
	 	real path=/hello
	 	request_scheme=tftp
	 
	 Test round 32157/1 exit code: 0
	 
	 Hostname: testds-ztdgk
	 
	 Request Information:
	 	client_address=10.10.0.49
	 	client_port=39444
	 	real path=/hello
	 	request_scheme=tftp
	 
	 Test round 32157/2 exit code: 0
	 
	 Hostname: testds-znvgg
	 
	 Request Information:
	 	client_address=192.168.36.11
	 	client_port=32773
	 	real path=/hello
	 	request_scheme=tftp
	 
	 Test round 32157/3 exit code: 0
	 
	 Hostname: testds-znvgg
	 
	 Request Information:
	 	client_address=192.168.36.11
	 	client_port=54477
	 	real path=/hello
	 	request_scheme=tftp
	 
	 Test round 32157/4 exit code: 0
	 
	 Hostname: testds-znvgg
	 
	 Request Information:
	 	client_address=192.168.36.11
	 	client_port=38194
	 	real path=/hello
	 	request_scheme=tftp
	 
	 Test round 32157/5 exit code: 0
	 
	 Hostname: testds-znvgg
	 
	 Request Information:
	 	client_address=192.168.36.11
	 	client_port=50590
	 	real path=/hello
	 	request_scheme=tftp
	 
	 Test round 32157/6 exit code: 0
	 
	 Hostname: testds-ztdgk
	 
	 Request Information:
	 	client_address=10.10.0.49
	 	client_port=51870
	 	real path=/hello
	 	request_scheme=tftp
	 
	 Test round 32157/8 exit code: 0
	 
	 Hostname: testds-znvgg
	 
	 Request Information:
	 	client_address=192.168.36.11
	 	client_port=33737
	 	real path=/hello
	 	request_scheme=tftp
	 
	 Test round 32157/9 exit code: 0
	 
	 Hostname: testds-ztdgk
	 
	 Request Information:
	 	client_address=10.10.0.49
	 	client_port=48269
	 	real path=/hello
	 	request_scheme=tftp
	 
	 Test round 32157/10 exit code: 0
	 failed: :32157/7=28
	 
Stderr:
 	 command terminated with exit code 42
	 

/home/jenkins/workspace/Cilium-PR-K8s-oldest-net-next/src/github.com/cilium/cilium/test/k8sT/Services.go:749
```

[3904f832_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_XDP,_direct_routing_and_Hybrid.zip](https://github.com/cilium/cilium/files/4829918/3904f832_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_XDP._direct_routing_and_Hybrid.zip)

https://jenkins.cilium.io/job/Cilium-PR-K8s-oldest-net-next/963

Possibly related to or a recurrence of #11029? /cc @borkmann @brb @joestringer

### PR DESCRIPTION
**Pull request by jrajahalme**
'--no-wildcard' allows the socket match to find zero-bound (listening)
sockets, which we do not want, as this may intercept traffic intended
for other nodes, for example, reply traffic when an ephemeral source
port number allocated in one node happens to be the same as the
allocated proxy port number in the node doing the iptables socket
match changed here.

Note to backporters: The test suite changes need not be backported
to older releases (e.g., 1.6) if these are non-trivial merge conflicts.

Fixes: #12281
Fixes: #12127
Fixes: #8945
Fixes: #10669
Fixes: #11867
Fixes: #10118
Fixes: #11313
Fixes: #12241
Fixes: #10231
Related: #8864
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
retest-net-next

**Comment by jrajahalme** [comment]
retest-net-next

**Comment by jrajahalme** [comment]
test-only --k8s_version=1.18 --focus="K8s.*AutoDirectNodeRoutes" --kernel_version=net-next

File: test/helpers/kubectl.go [hunk 1]
```diff
@@ -4073,3 +4073,22 @@ func logGathererSelector(allNodes bool) string {
...
+
+// GetDNSProxyPort returns the port the Cilium DNS proxy is listening on
+func (kub *Kubectl) GetDNSProxyPort(ciliumPod string) int {
+	const pickDNSProxyPort = `iptables-save | grep "udp.*TPROXY to host cilium-dns-egress" | sed 's/^.*--on-port \([1-9][0-9]*\).*$/\1/'`
+
+	// Find out the DNS proxy ports in use
+	res := kub.CiliumExecContext(context.TODO(), ciliumPod, pickDNSProxyPort)
+	if !res.WasSuccessful() {
+		ginkgoext.Failf("Cannot find DNS proxy port on %s", ciliumPod)
+		return 0
```
Comment (nebril) [inline test/helpers/kubectl.go]: nit: this line will never get executed

File: test/helpers/kubectl.go [hunk 2]
```diff
@@ -4073,3 +4073,22 @@ func logGathererSelector(allNodes bool) string {
...
+	}
+	portStr := res.GetStdOut().String()
+	gomega.Expect(portStr).ShouldNot(gomega.BeEmpty(), "No DNS proxy port found on %s", ciliumPod)
```
Comment (nebril) [inline test/helpers/kubectl.go]: Please use `ExpectWithOffset`, this will make test failure point to parent call instead of this line.

**Review by nebril — CHANGES_REQUESTED** [review]
LGTM overall, one small change request (ExpectWithOffset comment).

File: test/helpers/kubectl.go [hunk 3]
```diff
@@ -4073,3 +4073,22 @@ func logGathererSelector(allNodes bool) string {
 
 	return selector
 }
+
+// GetDNSProxyPort returns the port the Cilium DNS proxy is listening on
+func (kub *Kubectl) GetDNSProxyPort(ciliumPod string) int {
+	const pickDNSProxyPort = `iptables-save | grep "udp.*TPROXY to host cilium-dns-egress" | sed 's/^.*--on-port \([1-9][0-9]*\).*$/\1/'`
```
Comment (qmonnet) [inline test/helpers/kubectl.go]:
```suggestion
	const pickDNSProxyPort = `iptables-save | sed -n '/udp.*TPROXY to host cilium-dns-egress/ s/.*--on-port \([1-9][0-9]*\).*/\1/p'`
```

You could get rid of the `grep`, and of the `^`/`$` anchors in the pattern. If you know the name of the iptables table where the rule is located (and if it's constant), we could maybe pass `-t <name>` to `iptables-save`. We probably won't save much, but heh.

Comment (jrajahalme) [reply test/helpers/kubectl.go]: Nice, will do :-)

File: test/helpers/kubectl.go (hunk 2 above)
Comment (jrajahalme) [reply test/helpers/kubectl.go]: OK, so the offset value of 1 will point the failure to caller, 2 would point the failure to the caller's caller etc.?

File: test/helpers/kubectl.go (hunk 1 above)
Comment (jrajahalme) [reply test/helpers/kubectl.go]: Will remove.

**Comment by jrajahalme** [comment]
test-me-please

**Review by qmonnet — APPROVED** [review]
Looks good to me!

**Review by nebril — APPROVED** [review]

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-gke

**Comment by jrajahalme** [comment]
Fixed a white-space formatting error.

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
retest-net-next

File: test/k8sT/Services.go [hunk 4]
```diff
@@ -1113,7 +1113,73 @@ var _ = Describe("K8sServicesTest", func() {
...
+				ciliumPodK8s1 string
+				ciliumPodK8s2 string
+				DNSProxyPort1 int
+				DNSProxyPort2 int
+			)
+
+			BeforeAll(func() {
+				var err error
+				ciliumPodK8s1, err = kubectl.GetCiliumPodOnNodeWithLabel(helpers.CiliumNamespace, helpers.K8s1)
+				Expect(err).Should(BeNil(), fmt.Sprintf("Cannot get cilium pod on %s", helpers.K8s1))
```
Comment (vadorovsky) [inline test/k8sT/Services.go]: nit: you don't have to use `fmt.Sprintf`, the most of gomega functions (including `Should`) already support formatting.

```suggestion
				Expect(err).Should(BeNil(), "Cannot get cilium pod on %s", helpers.K8s1)
```

File: test/k8sT/Services.go [hunk 5]
```diff
@@ -1113,7 +1113,73 @@ var _ = Describe("K8sServicesTest", func() {
...
+				ciliumPodK8s2, err = kubectl.GetCiliumPodOnNodeWithLabel(helpers.CiliumNamespace, helpers.K8s2)
+				Expect(err).Should(BeNil(), fmt.Sprintf("Cannot get cilium pod on %s", helpers.K8s2))
```
Comment (vadorovsky) [inline test/k8sT/Services.go]: without `fmt.Sprintf`

**Review by vadorovsky — CHANGES_REQUESTED** [review]

File: test/k8sT/Services.go (hunk 4 above)
Comment (jrajahalme) [reply test/k8sT/Services.go]: Fixed

File: test/k8sT/Services.go (hunk 5 above)
Comment (jrajahalme) [reply test/k8sT/Services.go]: Fixed

**Comment by jrajahalme** [comment]
test-me-please

File: test/helpers/kubectl.go [hunk 6]
```diff
@@ -4077,3 +4077,21 @@ func logGathererSelector(allNodes bool) string {
...
+	if !res.WasSuccessful() {
+		ginkgoext.Failf("Cannot find DNS proxy port on %s", ciliumPod)
+	}
+	portStr := res.GetStdOut().String()
+	gomega.ExpectWithOffset(1, portStr).ShouldNot(gomega.BeEmpty(), "No DNS proxy port found on %s", ciliumPod)
+	port, err := strconv.Atoi(strings.TrimSpace(portStr))
+	if err != nil || port == 0 {
+		ginkgoext.Failf("Invalid DNS proxy port on %s: %s", ciliumPod, portStr)
+	}
+	return port
```
Comment (joestringer) [inline test/helpers/kubectl.go:4096]: Can we pull this from `cilium status` rather than the iptables rules? In future we won't rely on iptables so it'd be nice to have tests that don't rely on this implementation detail.

**Review by joestringer — APPROVED** [review]
Fix looks good, test looks good, just one comment on the helper which would help for future BPF TPROXY work.

File: test/helpers/kubectl.go (hunk 6 above)
Comment (jrajahalme) [reply test/helpers/kubectl.go:4096]: `cilium status` does not currently report the actual proxy ports, so this would be a clean-up for a later PR.

Comment (joestringer) [reply test/helpers/kubectl.go:4096]: Not true :-)

```
$ kubectl -n kube-system exec -ti pod/cilium-6nbc5 -- cilium status -o json | jq -r '.proxy.redirects[0]."proxy-port"'
11128
```

Comment (joestringer) [reply test/helpers/kubectl.go:4096]: (I'm fine to have this as an independent follow-up though)

Comment (jrajahalme) [reply test/helpers/kubectl.go:4096]: OK, I tried it without any policy imported (but DNS proxy still running) and in that case there are no redirects (`.proxy.redirects == null`), but the bug still exists as the DNS proxy is already listening.
