### PR TITLE
cli:connectivity: fix egress dev on aws-cni for pod-to-pod-encryption-v2

### LINKED ISSUE #37682: CI: AWS-CNI: pod-to-pod-encryption-v2/pod-to-pod-encryption-v2/curl-ipv4 : Expected to capture packets, but none found. This check might be broken.
## CI failure

Failure: https://github.com/cilium/cilium/actions/runs/13339169050/job/37260626000#step:21:275
Hit on PR https://github.com/cilium/cilium/pull/37620#issuecomment-2660451990 which only changes clustermesh things.

```
[=] [cilium-test-3] Test [pod-to-pod-encryption-v2] [18/36]
.  [-] Scenario [pod-to-pod-encryption-v2/pod-to-pod-encryption-v2]
  ℹ️  Encryption is disabled: test will fail if plain-text packets are not seen to validates pcap filters are correct
  [.] Action [pod-to-pod-encryption-v2/pod-to-pod-encryption-v2/curl-ipv4: cilium-test-3/client-7b7776c86b-d585x (192.168.110.108) -> cilium-test-3/echo-other-node-7c95b6845f-87sv5 (192.168.110.240:8080)]
  ❌ Expected to capture packets, but none found. This check might be broken.
```

...

```
📋 Test Report [cilium-test-3]
❌ 1/19 tests failed (1/125 actions), 17 tests skipped, 0 scenarios skipped:
Test [pod-to-pod-encryption-v2]:
  ❌ pod-to-pod-encryption-v2/pod-to-pod-encryption-v2/curl-ipv4: cilium-test-3/client-7b7776c86b-d585x (192.168.110.108) -> cilium-test-3/echo-other-node-7c95b6845f-87sv5 (192.168.110.240:8080)
🏃[cilium-test-1] Running 7 tests ...
```

### PR DESCRIPTION
**Pull request by smagnani96**
Partially fixes (only for v2): https://github.com/cilium/cilium/issues/37675

Fixes: https://github.com/cilium/cilium/issues/37682

```release-note
Fix egress device computation in cli connectivity pod-to-pod-encryption-v2 tests for AWS chaining mode.
```

### CODE REVIEW

**Comment by smagnani96** [comment]
Had to introduce one commit to enable `-d -v` in connectivity test.
I need this to make sure that, when running AWS tests, they score green for the case we're interested into.

Since we observed a different egress device being selected in our tests when `client -> echo-other-node` (and not in other combinations), I would like such verbose output and run multiple times `/ci-awscni`.

That said, this commit is just for test purpose and won't be merged.

File: cilium-cli/connectivity/tests/encryption_v2.go [hunk 1]
```diff
@@ -110,52 +110,138 @@ func (s *podToPodEncryptionV2) Name() string {
...
+
+		return "", fmt.Errorf("Failed to find egress device")
+	}
+
+	// tableIPRouteGet issues `ip route show table X` in provided host network
+	// namespace and extract device.
+	//
+	// example json output:
+	// [{"dst":"default","gateway":"192.168.128.1","dev":"ens6","flags":[]},{"dst":"192.168.128.1","dev":"ens6","scope":"link","flags":[]}]
+	tableIPRouteGet := func(table string) (string, error) {
```
Comment (ldelossa) [inline cilium-cli/connectivity/tests/encryption_v2.go]: This function is specifically looking for the 'device for the default route' but comments and function name don't really mention this.

**Review by ldelossa — APPROVED** [review]
Other then my comment, this looks good.

File: cilium-cli/connectivity/tests/encryption_v2.go (hunk 1 above)
Comment (smagnani96) [reply cilium-cli/connectivity/tests/encryption_v2.go]: You're absolutely right, didn't update comments in the code after changing the logic :sweat_smile: 
Just adjusted the comments, thanks!

**Comment by ldelossa** [comment]
latest `https://github.com/cilium/cilium/actions/runs/13396664630/job/37418038669` failure is not due to this change. Its an existing flake in the AWS-CNI test.

File: cilium-cli/connectivity/tests/encryption_v2.go [hunk 2]
```diff
@@ -114,52 +114,131 @@ func (s *podToPodEncryptionV2) Name() string {
 
 // resolveEgressDevice resolves the egress device used in the provided host
 // network namespace used to send traffic to dst.
-func (s *podToPodEncryptionV2) resolveEgressDevice(ctx context.Context, srcHostNS *check.Pod, dst *check.Pod) (string, error) {
+func (s *podToPodEncryptionV2) resolveEgressDevice(ctx context.Context, srcHostNS *check.Pod, src, dst *check.Pod) (string, error) {
+	// deviceFromIPRoute issues `ip route get` for destination in provided host network
```
Comment (pchaigno) [inline cilium-cli/connectivity/tests/encryption_v2.go]: Did you try using `ip route get ... from podIP`? AFAICT, that would remove the need for the two functions and for iterating over ip rules... or maybe I'm missing something?

**Review by pchaigno — COMMENTED** [review]
I'm really not confortable with the amount of logic introduced here to solve something that should be relatively trivial. Starting a discussion below :point_down: to see if there's any other way.

File: cilium-cli/connectivity/tests/encryption_v2.go (hunk 2 above)
Comment (ldelossa) [reply cilium-cli/connectivity/tests/encryption_v2.go]: @pchaigno so the `from` argument is news to me, TIL. 

I'm assuming you are saying do something like `ip rout get {dst} from {src_ip}` and `ip route get` will do the necessary ip rule and subsequent table lookup?

Comment (pchaigno) [reply cilium-cli/connectivity/tests/encryption_v2.go]: Yep, exactly.

Comment (smagnani96) [reply cilium-cli/connectivity/tests/encryption_v2.go]: Thanks @pchaigno for the point. With Louis, we verified your saying in an EKS cluster, and the command seems to need also an interface specified (can be whatever).
Going to change our logic to 1 single lookup `ip route get {dst} from {src_up} iif cilium_host` (cilium_host will always be present).

Comment (smagnani96) [reply cilium-cli/connectivity/tests/encryption_v2.go]: Just updated the commits.
Re-introduced commit 3 to re-run `/ci-awscni` with debug/verbose output + forcing `client3` during CLI tests. Won't be merged.

Comment (ldelossa) [reply cilium-cli/connectivity/tests/encryption_v2.go]: Just to add to that... 

`ip route get from ...` requires an `iif` (input interface) to return anything useful. 
ENI ip rules do not specify an `iif` specifically in the ip rule, therefore ANY interface works, as packets sourced from `src_ip` from ANY interface will result in the `ip rule` being triggered. 
Therefore, just provide `cilium_host` per what Simone mentions, its always there. 

Nice catch and suggestion Paul, that makes things way simpler :)

Comment (pchaigno) [reply cilium-cli/connectivity/tests/encryption_v2.go]: Uh, I didn't need to specify an interface when I checked locally :thinking: Anyway, if any interface works the same, I guess it doesn't matter.

**Comment by smagnani96** [comment]
Both actions https://github.com/cilium/cilium/actions/runs/13420355971/job/37491264387 and https://github.com/cilium/cilium/actions/runs/13420355971/job/37491264728 :green_circle: with `client3` being selected and `ens6` being correctly detected rather than `ens5`.

Running a new one to confirm.

**Comment by smagnani96** [comment]
Both actions are :green_circle:

* https://github.com/cilium/cilium/actions/runs/13420355971/job/37504755483 falls in the default case (`ens5` being selected for both client/server)
* https://github.com/cilium/cilium/actions/runs/13420355971/job/37504755680 falls in the other case (`ens5` for one, `ens6` for the other due to the source route)

Removing the 3rd commit and going through the process again.

File: cilium-cli/connectivity/tests/encryption_v2.go [hunk 3]
```diff
@@ -114,27 +114,35 @@ func (s *podToPodEncryptionV2) Name() string {
...
+	// but it is ignored if `ip rules` do not have an interface specified in the rule.
 	//
 	// example string output:
 	// "172.18.0.2 dev eth0 src 172.18.0.4 uid 0 \n    cache \n"
 	out, err := srcHostNS.K8sClient.ExecInPod(ctx,
 		srcHostNS.Pod.Namespace,
 		srcHostNS.Pod.Name,
 		"",
-		[]string{"ip", "route", "get", dstIP})
+		[]string{"ip", "-j", "route", "get", dstIP, "from", srcIP, "iif", "cilium_host"})
```
Comment (pchaigno) [inline cilium-cli/connectivity/tests/encryption_v2.go:145]: Nit: I believe the `-j` here is in the first commit when it should be in the second.

**Review by pchaigno — APPROVED** [review]
Way easier to review now :hand_over_mouth:

File: cilium-cli/connectivity/tests/encryption_v2.go (hunk 3 above)
Comment (smagnani96) [reply cilium-cli/connectivity/tests/encryption_v2.go:145]: You're right, nice catch, thanks :100:

File: cilium-cli/connectivity/tests/encryption_v2.go (hunk 2 above)
Comment (ldelossa) [reply cilium-cli/connectivity/tests/encryption_v2.go]: Yeah, without interface, we kept receiving errors that no route to network existed.
