### PR TITLE
k8s, node: Restore router IPs (cilium_host) from K8s resource 

### LINKED ISSUE #16279: Connectivity issues with IPsec after node reboot
## Bug report

We run flatcar-linux in our production clusters and since we updated to cilium 1.9 pods don't get connectivity after node reboots.
To fix it, we need to manually delete the cilium-agent pod on the corresponding node.
`cilium-health status` reports host connectivity to other nodes, but both ICMP to stack and HTTP to stack report timeouts.

Reproducible on both cilium 1.9.6 and 1.9.7, against recent Flatcar Linux stable versions (tested against 2765.2.3, 2765.4, 2765.2.5)
/cc: @johannwagner @Jasper-Ben

**General Information**

- Cilium version: 1.9.7
- Kernel version: 5.9.11, 5.9.16, 5.10.16, 5.10.25, 5.10.32, 5.10.37
- Orchestration system version: Kubernetes 1.20.7
- Link to relevant artifacts: To be followed, I'm working on building a reproducible deployment set.
- Generate and upload a system zip: (To be followed from reproducible deployment)

**How to reproduce the issue**

1. Setup Cilium 1.9.7 on a Cluster consisting of Flatcar Linux nodes
2. Reboot one node
3. See that the pods don't get connectivity on the rebooted node, until the cilium agent on this node is deleted and recreated

### PR DESCRIPTION
**Pull request by christarazi**
Previously, after a node reboot, Cilium would allocate a new router IP
and append it slice of node IPs. Since the node IPs have already been
synced to the K8s resource, meaning there are already IPs present (from
the previous Cilium instance), the router IP is appended to the slice.
In other parts of Cilium, it is assumed that the router IP is the first
node IP (first element of the slice). Since the new router IP has been
appended to the end, it is no longer where it is expected, aka no longer
the first element. This causes a mismatch of which router IP is to be
used. There should only ever be one router IP (one IPv4 or one IPv6).

In case of a node reboot, the router IPs cannot be restored because they
are wiped away due to the Cilium state dir being mounted as a tmpfs [1].
This commit fixes this to restore the router IPs from the K8s resource
(Node or CiliumNode) if they are present in the annotations. This
prevents the possibility of having more than one router IP, as described
above. Note that router IPs from the K8s resource are only restored if
no router IP was found on the filesystem, which is considered the source
of truth. In other words, the filesystem takes precedence over the K8s
resource. The user is warned in cases of a mismatch between the two
different sources. We also check that the IP to be restored is within
the pod / node CIDR range, otherwise we ignore it from restoration.

[1]: Linux distributions mount /run as tmpfs and Cilium's default state
	 directory is created under /run. (It's worth mentioning that it's
	 also common for /var/run to be symlinked to /run.)

Fixes: https://github.com/cilium/cilium/issues/16279

```release-note
Fix bug where Cilium allocates a new router (`cilium_host`) IP upon node reboot, breaking connectivity especially with IPsec
```

### CODE REVIEW

**Review by nathanjsweet — COMMENTED** [review]
I can't think of anything important offhand, but I guess there is the possibility that some kind of fast restart with a swapped NIC in a cloud provider could turn this into a race condition. However, that's a very edge case.

**Review by brb — COMMENTED** [review]
What's going to happen if podCIDR will change? Will it still try to restore potentially obsolete router IP?

**Comment by christarazi** [comment]
> What's going to happen if podCIDR will change? Will it still try to restore potentially obsolete router IP?

@brb Do we support pod CIDRs changing anyway?

Regardless of that, I'm thinking we need to determine the priority of the router IPs that we restore. I'm assuming that the local filesystem is the most up-to-date source of truth. An approach would be to load the router IPs from the K8s resource like this PR already does, then read the filesystem state. If the state contains a router IP as well, then compare it against the one from the K8s resource. If there's a mismatch, then we should warn loudly and we will probably want to switch over to it anyway. 

With a system like the above in-place, then we are not actually changing the behavior of Cilium by much. Only the case where the router IP doesn't exist on the filesystem, but does exist in the K8s resource, which occurs on a node reboot.

**Comment by christarazi** [comment]
User confirmed that this fixes their issue: https://github.com/cilium/cilium/issues/16279#issuecomment-849035211

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
test-me-please

File: pkg/k8s/init.go [hunk 1]
```diff
@@ -267,3 +269,22 @@ func WaitForNodeInformation() error {
 	// want to specify them manually
 	return nil
 }
+
+func restoreRouterHostIPs(n *nodeTypes.Node) {
+	if option.Config.EnableHostIPRestore {
```
Comment (aanm) [inline pkg/k8s/init.go]: nit: negate this to do an early return

**Review by aanm — CHANGES_REQUESTED** [review]
>> What's going to happen if podCIDR will change? Will it still try to restore potentially obsolete router IP?
>
> @brb Do we support pod CIDRs changing anyway?

Well, it's not up to Cilium as it will simply receive the podCIDR from Kubernetes.

There is at least one case where this patch might cause issues.

1. Stop kubelet
2. Delete node with `kubectl delete node <node-name>`
3. Restart kubelet
4. Kubernetes will assign a new podCIDR to that node
5. Cilium will wrongly restore an IP address that does not belong to the podCIDR.

**Comment by christarazi** [comment]
Synced with @aanm offline. The above feedback turned out to be more relevant for issue https://github.com/cilium/cilium/issues/6469, which we should tackle at another time. However, we also realized that we should validate the IP chosen for restoration to check whether it actually belongs to the pod CIDR of the node. If it does not, then we will discard it and not restore it.

**Comment by christarazi** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Review by michi-covalent — APPROVED** [review]

**Comment by christarazi** [comment]
Pushed a [small change](https://github.com/cilium/cilium/compare/c9af154fa064ed728cd179d3f37c47c70ebda076..68cae4c5f151a520ec3497ea92915e653b80bdee) that shouldn't require a re-run. CI has [passed](https://github.com/cilium/cilium/pull/16307#issuecomment-852442376).
