### PR TITLE
Fix k8s podCIDRs for vagrant deployment

### LINKED ISSUE #19594: [dev-VM] make CIDRs & IPs consistent (k8s vs Cilium)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The dev-VM environment doesn't configure the same CIDRs / IPs for `kubelet` and `cilium`. See eg. the PodCIDRs in the log output.

Harmonize these, so that users see consistent information and the different IPAM modes show the same behaviour.

### Cilium Version

Client: 1.11.90 6a97d2bace 2022-04-26T19:28:01+03:00 go version go1.18beta2 linux/amd64
Daemon: 1.11.90 6a97d2bace 2022-04-26T19:28:01+03:00 go version go1.18beta2 linux/amd64

### Kernel Version

Linux k8s1 5.17.0-rc2-g1127170d457e #1 SMP PREEMPT Thu Feb 10 21:30:01 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

_No response_

### Relevant log output

```shell
$ kubectl get ciliumnodes.cilium.io -o yaml
apiVersion: v1
items:
- apiVersion: cilium.io/v2
  kind: CiliumNode
  metadata:
  ...
    name: k8s1
  ...
  spec:
    addresses:
    - ip: 192.168.60.11
      type: InternalIP
    - ip: fd00::b
      type: InternalIP
    - ip: 10.11.0.188
      type: CiliumInternalIP
    - ip: fd04::c624
      type: CiliumInternalIP
    ...
    health:
      ipv4: 10.11.0.137
      ipv6: fd04::ddc6
    ipam:
      podCIDRs:
      - 10.11.0.0/24
      - fd04::/112


$ kubectl get nodes k8s1 -o yaml
apiVersion: v1
kind: Node
...
spec:
  podCIDR: 10.16.0.0/16
  podCIDRs:
  - 10.16.0.0/16
  - fd02::/96
status:
  addresses:
  - address: 192.168.60.11
    type: InternalIP
  - address: k8s1
    type: Hostname
```

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by romanspb80**
This patch makes podCIDRs of k8s Node and CiliumNode consistent: vagrant@k8s1:~/go/src/github.com/cilium/cilium$ kubectl get nodes k8s1 -o yaml apiVersion: v1
kind: Node
metadata:
...
spec:
  podCIDR: 10.11.0.0/24
  podCIDRs:
  - 10.11.0.0/24
  - fd04::/112 ...

vagrant@k8s1:~/go/src/github.com/cilium/cilium$ kubectl get ciliumnodes.cilium.io -o yaml apiVersion: v1
items:
- apiVersion: cilium.io/v2 kind: CiliumNode ... spec: ... ipam: podCIDRs: - 10.11.0.0/24 - fd04::/112 ...

Fixes: #19594

Signed-off-by: Roman Ptitcyn <romanspb@yahoo.com>

### CODE REVIEW

File: pkg/ip/ip_test.go [hunk 1]
```diff
@@ -664,7 +664,7 @@ func (s *IPTestSuite) TestPartitionCIDR(c *C) {
 	expectedRight := []*net.IPNet{createIPNet("10.128.0.0", 9, int(ipv4BitLen)),
 		createIPNet("10.64.0.0", 10, int(ipv4BitLen)),
 		createIPNet("10.32.0.0", 11, int(ipv4BitLen)),
-		createIPNet("10.16.0.0", 12, int(ipv4BitLen)),
+		createIPNet("10.11.0.0", 24, int(ipv4BitLen)),
```
Comment (christarazi) [inline pkg/ip/ip_test.go]: This seems like an unrelated change. This is test code and this delta is changing one of the test cases. Can you drop this change?

File: pkg/labels/cidr/cidr_test.go [hunk 2]
```diff
@@ -177,7 +177,7 @@ func (s *CIDRLabelsSuite) TestIPStringToLabel(c *C) {
 func BenchmarkGetCIDRLabels(b *testing.B) {
 	for _, cidr := range []netip.Prefix{
 		netip.MustParsePrefix("0.0.0.0/0"),
-		netip.MustParsePrefix("10.16.0.0/16"),
+		netip.MustParsePrefix("10.11.0.0/24"),
```
Comment (christarazi) [inline pkg/labels/cidr/cidr_test.go]: Same here

File: pkg/option/config.go [hunk 3]
```diff
@@ -175,7 +175,7 @@ const (
 	// which allows to use reserved label for fixed identities
 	FixedIdentityMapping = "fixed-identity-mapping"
 
-	// IPv4Range is the per-node IPv4 endpoint prefix, e.g. 10.16.0.0/16
+	// IPv4Range is the per-node IPv4 endpoint prefix, e.g. 10.11.0.0/24
```
Comment (christarazi) [inline pkg/option/config.go]: Same here

File: pkg/policy/cidr_test.go [hunk 4]
```diff
@@ -111,7 +111,7 @@ func (ds *PolicyTestSuite) TestGetCIDRPrefixes(c *C) {
 		"10.128.0.0/9",
 		"10.64.0.0/10",
 		"10.32.0.0/11",
-		"10.16.0.0/12",
+		"10.11.0.0/24",
```
Comment (christarazi) [inline pkg/policy/cidr_test.go]: Same here

**Review by christarazi — CHANGES_REQUESTED** [review]
Thanks for the PR. I think the changes need only be scoped to `contrib/vagrant`.

File: pkg/policy/cidr_test.go (hunk 4 above)
Comment (romanspb80) [reply pkg/policy/cidr_test.go]: Thanks Chris
Done

**Review by christarazi — APPROVED** [review]

File: contrib/vagrant/scripts/helpers.bash [hunk 5]
```diff
@@ -56,10 +56,10 @@ kubernetes_master="${controllers_ips[0]}"
 # Default values for IPv4 and IPv6
 #
 # CIDR Range for Pods in cluster.
-k8s_cluster_cidr=${K8S_CLUSTER_CIDR:-"10.16.0.0/12,FD02::/96"} # 10.16.0.1-10.31.255.255
+k8s_cluster_cidr=${K8S_CLUSTER_CIDR:-"10.11.0.0/24,FD04::/112"} # 10.11.0.1-10.11.0.255
 # Mask size for node cidr in cluster.
-k8s_node_cidr_v4_mask_size=${K8S_NODE_CIDR_MASK_SIZE:-"16"} # 1st Node: 10.16.0.1-10.16.255.254, 2nd Node: 10.17.0.1-10.17.255.254...
-k8s_node_cidr_v6_mask_size=${K8S_NODE_CIDR_V6_MASK_SIZE:-"112"} # 1st Node: 10.16.0.1-10.16.255.254, 2nd Node: 10.17.0.1-10.17.255.254...
+k8s_node_cidr_v4_mask_size=${K8S_NODE_CIDR_MASK_SIZE:-"24"} # 1st Node: 10.11.0.1-10.11.0.255, 2nd Node: 10.11.1.1-10.11.1.255...
+k8s_node_cidr_v6_mask_size=${K8S_NODE_CIDR_V6_MASK_SIZE:-"112"} # 1st Node: 10.11.0.1-10.11.0.255, 2nd Node: 10.11.1.1-10.11.1.255...
```
Comment (julianwiedmann) [inline contrib/vagrant/scripts/helpers.bash]: This doesn't seem correct - now each per-node Pod CIDR would have the same size as the cluster's total Pod CIDR.

Did the CIDR sizes actually need fixing?

Comment (romanspb80) [reply contrib/vagrant/scripts/helpers.bash]: > This doesn't seem correct - now each per-node Pod CIDR would have the same size as the cluster's total Pod CIDR.
> 
> Did the CIDR sizes actually need fixing?

Thanks for the review.
I have reduced the mask value "K8S_CLUSTER_CIDR" by 4 bits

**Comment by aditighag** [comment]
@julianwiedmann Could you re-review to check if your comments have been addressed? Thanks!

File: contrib/vagrant/scripts/helpers.bash [hunk 6]
```diff
@@ -56,10 +56,10 @@ kubernetes_master="${controllers_ips[0]}"
 # Default values for IPv4 and IPv6
 #
 # CIDR Range for Pods in cluster.
-k8s_cluster_cidr=${K8S_CLUSTER_CIDR:-"10.16.0.0/12,FD02::/96"} # 10.16.0.1-10.31.255.255
+k8s_cluster_cidr=${K8S_CLUSTER_CIDR:-"10.11.0.0/20,FD04::/112"} # 10.11.0.1-10.11.15.255
 # Mask size for node cidr in cluster.
-k8s_node_cidr_v4_mask_size=${K8S_NODE_CIDR_MASK_SIZE:-"16"} # 1st Node: 10.16.0.1-10.16.255.254, 2nd Node: 10.17.0.1-10.17.255.254...
-k8s_node_cidr_v6_mask_size=${K8S_NODE_CIDR_V6_MASK_SIZE:-"112"} # 1st Node: 10.16.0.1-10.16.255.254, 2nd Node: 10.17.0.1-10.17.255.254...
+k8s_node_cidr_v4_mask_size=${K8S_NODE_CIDR_MASK_SIZE:-"24"} # 1st Node: 10.11.0.1-10.11.0.255, 2nd Node: 10.11.1.1-10.11.1.255...
+k8s_node_cidr_v6_mask_size=${K8S_NODE_CIDR_V6_MASK_SIZE:-"112"} # 1st Node: 10.11.0.1-10.11.0.255, 2nd Node: 10.11.1.1-10.11.1.255...
```
Comment (julianwiedmann) [inline contrib/vagrant/scripts/helpers.bash]: This still looks odd - having a cluster-wide IPv6 CIDR of `FD04::/112`, the per-node CIDR mask can't be `112`.

**Review by julianwiedmann — CHANGES_REQUESTED** [review]
Hi @romanspb80 , thanks! Besides the IPv6 inconsistency in the change (as noted below), a more general remark - we want these CIDRs to end up looking identical to what gets passed to https://github.com/cilium/cilium/blob/80af06ee3c224f529961cd5ac546de27516ccb10/contrib/vagrant/start.sh#L332-L333

Right now the per-node CIDR size gets auto-sized there, but it can be configured with `--cluster-pool-ipv4-mask-size`.

File: contrib/vagrant/scripts/helpers.bash (hunk 6 above)
Comment (romanspb80) [reply contrib/vagrant/scripts/helpers.bash]: Hi @julianwiedmann . Thanks for the comments. I made corrections. Could you please check?

**Review by julianwiedmann — APPROVED** [review]
LGTM, thanks @romanspb80 !

**Comment by julianwiedmann** [comment]
Think we're good to go - this is devVM-only, so the CI won't do us any good.

**Review by pchaigno — APPROVED** [review]
I've tested this locally.

**Comment by romanspb80** [comment]
Thanks guys!
