### PR TITLE
bgp: Check the Condition.Ready field when adding ready endpoints

### LINKED ISSUE #19810: Rolling restart pods causes brief outage with externalTrafficPolicy=Local
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Some requests to Loadbalancer service with externalTrafficPolicy=Local failed due to `No route to host` during we updated its backend pods. The old pods remained in the terminating state for a while to handle the existing active connections and gracefully shut down. (We updated our Envoy pods.) It seems that the packets received by the nodes where the terminating pods were running were getting nowhere.

## How to reproduce the issue

- Install Cilium with kube-proxy replacement and bgp.announce.loadbalancerIP are enabled. (See values.yaml following)
- Apply the manifest. (The pods derived from the deployment will remain terminating state by the preStop hook when those stop.)
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: suzuki-test
  namespace: dctest
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: suzuki-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: suzuki-test
    spec:
      containers:
      - image: quay.io/ysksuzuki/testhttpd:0
        name: testhttpd
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "30"]
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: suzuki-test
  namespace: dctest
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/name: suzuki-test
```
- Run `kubectl -n dctest rollout restart deployment/suzuki-test`
- Access to the service

```
$ curl -v 10.72.32.1
*   Trying 10.72.32.1:80...
* TCP_NODELAY set
* connect to 10.72.32.1 port 80 failed: No route to host
* Failed to connect to 10.72.32.1 port 80: No route to host
* Closing connection 0
curl: (7) Failed to connect to 10.72.32.1 port 80: No route to host
```

vallues.yaml
```
bgp:
  announce:
    loadbalancerIP: true
  enabled: true
bpf:
  hostRouting: true
cni:
  chainingMode: "generic-veth"
  customConf: true
datapathMode: "veth"
devices: "eth+ eno1+ eno2+"
enableIPv4Masquerade: false
enableIdentityMark: false
externalIPs:
  enabled: true
hostPort:
  enabled: false
hostServices:
  enabled: true
  hostNamespaceOnly: true
hubble:
  relay:
    enabled: true
    tls:
      server:
        enabled: true
    rollOutPods: true
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
  tls:
    auto:
      method: "cronJob"
  metrics:
    enabled:
      - "dns"
      - "drop:destinationContext=pod|dns|ip;sourceContext=pod|dns|ip"
      - "tcp"
      - "flow:destinationContext=pod|dns|ip;sourceContext=pod|dns|ip"
      - "icmp"
      - "http"
k8sServiceHost: 127.0.0.1
k8sServicePort: 16443
kubeProxyReplacement: "partial"
loadBalancer:
  # We can't enable XDP Acceleration because of the issue https://github.com/cilium/cilium/issues/19453
  acceleration: disabled
  algorithm: maglev
  mode: dsr
maglev:
  hashSeed: 3HCx6JennjWtot2U
nodePort:
  directRoutingDevice: "e+"
  enabled: true
operator:
  rollOutPods: true
  prometheus:
    enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
policyAuditMode: false
policyEnforcementMode: "default"
prometheus:
  enabled: true
resources:
  requests:
    cpu: 100m
    memory: 400Mi
rollOutCiliumPods: true
tunnel: "disabled"
```

## What is happening?

When pods restart, Cilium detects the endpoint state is terminating and remove the service's backend from cilium_lb4_services_v2. 

```
$ kubectl -n kube-system exec cilium-6xm8g -- cilium bpf lb list
SERVICE ADDRESS       BACKEND ADDRESS
10.72.32.1:80         0.0.0.0:0 (26) [LoadBalancer, Local]
```

MetalLB is advertising the route to the LB until the pods are removed. So the node where the terminating pod is running still receives new connections to the LB, but Cilium can't handle the new connection because there's no backend for LB_LOOKUP_SCOPE_EXT scope value, and it won't forward them to the cluster-wide backends for externalTrafficPolicy=Local service.

```
# Pod is terminating
bird> show route 10.72.32.1/32
Table master4:
10.72.32.1/32        unicast [metallb 06:32:34.149 from 127.0.0.1] * (100/?) [AS64698?]
        via 10.69.1.193 on eth0

# Pod is removed. MetalLB withdraw the advertisement
bird> show route 10.72.32.1/32
Table master4:
10.72.32.1/32        unicast [tor1 07:40:56.715] * (100/?) [AS64698?]
        via 10.69.1.193 on eth0
                     unicast [tor2 07:40:56.715] (100/?) [AS64698?]
        via 10.69.2.1 on eth1
```

### Cilium Version

Client: 1.11.4 9d2546357e 2022-04-15T08:33:55-07:00 go version go1.17.9 linux/amd64
Daemon: 1.11.4 9d2546357e 2022-04-15T08:33:55-07:00 go version go1.17.9 linux/amd64

### Kernel Version

```
$ uname -a
Linux rack0-cs5 5.15.32-flatcar #1 SMP Tue Apr 5 17:17:31 -00 2022 x86_64 AMD EPYC 7413 24-Core Processor AuthenticAMD GNU/Linux
```

### Kubernetes Version

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"archive", BuildDate:"2022-03-23T08:04:34Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
```

### Sysdump

[cilium-sysdump-20220513-070444.zip](https://github.com/cilium/cilium/files/8685324/cilium-sysdump-20220513-070444.zip)

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ysksuzuki**
This PR fixes the issue that MetalLB doesn't withdraw the route advertisements to the node where any healthy local endpoint exists for the service with externalTrafficPolicy is Local when the backend pod is terminating. Cilium takes endpoint.Conditions.Ready field into account when it determines whether to announce the route.

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

Fixes: #19810

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
LGTM :100:

**Comment by ysksuzuki** [comment]
80 tests failed in k8s-1.16-kernel-4.9 (test-1.16-4.9). Run `K8S_VERSION=1.16 ginkgo --focus="K8s" --tags=integration_tests` locally, but it didn't reproduce. Something was wrong with the test environment, perhaps.
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-kernel-4.9/1897/

K8sPolicyTest Basic Test checks ICMP policies failed. Need to rebase according to [this](https://cilium.slack.com/archives/C7PE7V806/p1655309107740079)
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.24-kernel-net-next/41/

**Comment by ysksuzuki** [comment]
@sayboras Rebased the branch. Could you retrigger the CI?

**Comment by ysksuzuki** [comment]
gke-stable(tet-gke) is failed because of #20013. ALL other tests are green.

File: pkg/bgp/speaker/speaker.go [hunk 1]
```diff
@@ -423,36 +423,54 @@ func convertEndpointSliceV1(in *slim_discover_v1.EndpointSlice) *metallbspr.Endp
 	}
 	out := new(metallbspr.Endpoints)
 	for _, ep := range in.Endpoints {
-		for _, addr := range ep.Addresses {
-			out.Ready = append(out.Ready, metallbspr.Endpoint{
-				IP:       addr,
-				NodeName: ep.NodeName,
-			})
+		if isConditionReadyForSliceV1(ep.Conditions) {
```
Comment (jibi) [inline pkg/bgp/speaker/speaker.go:426]: nit: maybe invert the condition and save one level of indentation?

```suggestion
		if !isConditionReadyForSliceV1(ep.Conditions) {
		        continue
		}
```

File: pkg/bgp/speaker/speaker.go [hunk 2]
```diff
@@ -423,36 +423,54 @@ func convertEndpointSliceV1(in *slim_discover_v1.EndpointSlice) *metallbspr.Endp
...
+			}
 		}
 		// See above comment in convertEndpoints() for why we only append
 		// "ready" endpoints.
 	}
 	return out
 }
 
+func isConditionReadyForSliceV1Beta1(conditions slim_discover_v1beta1.EndpointConditions) bool {
+	if conditions.Ready == nil {
```
Comment (jibi) [inline pkg/bgp/speaker/speaker.go:468]: nit:
```suggestion
	return conditions.Ready == nil || *conditions.Ready
```

also it may be worth adding a comment as I'm not following why we consider the condition to be fulfilled when `condfitions.Ready` is `nil`

File: pkg/bgp/speaker/speaker.go [hunk 3]
```diff
@@ -423,36 +423,54 @@ func convertEndpointSliceV1(in *slim_discover_v1.EndpointSlice) *metallbspr.Endp
...
+				})
+			}
 		}
 		// See above comment in convertEndpoints() for why we only append
 		// "ready" endpoints.
 	}
 	return out
 }
 
+func isConditionReadyForSliceV1(conditions slim_discover_v1.EndpointConditions) bool {
```
Comment (jibi) [inline pkg/bgp/speaker/speaker.go:440]: I think naming could be made a bit more explicit here, for example what about `endpointIsReady()` (which would simply takes a `*slim_discover_v1.Endpoint` object)?

**Review by jibi — APPROVED** [review]
LGTM, just a few small nits

**Review by ldelossa — APPROVED** [review]
LGTM

File: pkg/bgp/speaker/speaker.go (hunk 2 above)
Comment (ysksuzuki) [reply pkg/bgp/speaker/speaker.go:468]: The following indicates nil ready means ready. Actually, I referenced the original MetalLB implementation. See https://github.com/metallb/metallb/pull/837#issuecomment-842917807

> A nil value indicates an unknown state. In most cases consumers should interpret this unknown state as ready.

https://github.com/kubernetes/api/blob/edebc6706ddef7e828b5b606fbd0c91c6843c2fa/discovery/v1/types.go#L119-L124
