### PR TITLE
bpf: nat: Fix short packet MTU path discovery

### LINKED ISSUE #33844: BUG: Cilium dropping ICMP DestinationUnreachable "FragmentationNeeded" packets while ebpf masquerading enabled
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

vv1.15.7 or higher

### What happened?

After moving from legacy host routing into native ebpf with ebpf masquerade enabled we started to experience hanging TCP connections to system located outside of kubernetes cluster. Running tcpdumps from both client pod and kubernetes worker node we can clearly see that ICMP DestinationUnreachable "FragmentationNeeded" packet is incoming to node interface, but never translated to client pod itself. This lead to client pod packet retransmission (with DF flag) again and again without getting ack, until server closing connection.

According to https://github.com/cilium/cilium/pull/18414 & https://docs.cilium.io/en/latest/network/concepts/masquerading/ Cilium should support translating ICMP DestinationUnreachable(FragmentationNeeded) packets to the targets while ebpf SNAT enabled, but it doesn't happens in our case.

Pod tcpdump:
image

Node tcpdump:
image

Running cilium monitor for dropped packets on worker node:
```
# cilium monitor -t drop
Listening for events on 8 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
time="2024-07-16T12:22:30Z" level=info msg="Initializing dissection cache..." subsys=monitor
xx drop (Error while correcting L4 checksum) flow 0x240c240c to endpoint 0, ifindex 2, file nodeport.h:2645, , identity unknown->unknown: 10.224.52.137 -> 10.232.48.139 DestinationUnreachable(FragmentationNeeded)
xx drop (Error while correcting L4 checksum) flow 0x240c240c to endpoint 0, ifindex 2, file nodeport.h:2645, , identity unknown->unknown: 10.224.52.137 -> 10.232.48.139 DestinationUnreachable(FragmentationNeeded)
xx drop (Error while correcting L4 checksum) flow 0x240c240c to endpoint 0, ifindex 2, file nodeport.h:2645, , identity unknown->unknown: 10.224.52.137 -> 10.232.48.139 DestinationUnreachable(FragmentationNeeded)
xx drop (Error while correcting L4 checksum) flow 0x240c240c to endpoint 0, ifindex 2, file nodeport.h:2645, , identity unknown->unknown: 10.224.52.137 -> 10.232.48.139 DestinationUnreachable(FragmentationNeeded)
xx drop (Error while correcting L4 checksum) flow 0x240c240c to endpoint 0, ifindex 2, file nodeport.h:2645, , identity unknown->unknown: 10.224.52.137 -> 10.232.48.139 DestinationUnreachable(FragmentationNeeded)
xx drop (Error while correcting L4 checksum) flow 0x240c240c to endpoint 0, ifindex 2, file nodeport.h:2645, , identity unknown->unknown: 10.224.52.137 -> 10.232.48.139 DestinationUnreachable(FragmentationNeeded)
xx drop (Error while correcting L4 checksum) flow 0x240c240c to endpoint 0, ifindex 2, file nodeport.h:2645, , identity unknown->unknown: 10.224.52.137 -> 10.232.48.139 DestinationUnreachable(FragmentationNeeded)
xx drop (Error while correcting L4 checksum) flow 0x240c240c to endpoint 0, ifindex 2, file nodeport.h:2645, , identity unknown->unknown: 10.224.52.137 -> 10.232.48.139 DestinationUnreachable(FragmentationNeeded)
^C
Received an interrupt, disconnecting from monitor...
```

suggesting that something is wrong with calculation of checksum, so attaching example of ICMP packet dropped in details:
image

Let me know if you need any additional information.

### How it happened?

Cilium v1.15.6 with helm values: 
```
bpf:
    masquerade: true
egressMasqueradeInterfaces: "
```

### Kernel Version

Linux 5.10.215-203.850.amzn2.x86_64

### Kubernetes Version

1.27+ (v1.27.13-eks-3af4770) [linux/amd64]

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell
# cilium monitor -t drop
Listening for events on 8 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
time="2024-07-16T12:22:30Z" level=info msg="Initializing dissection cache..." subsys=monitor
xx drop (Error while correcting L4 checksum) flow 0x240c240c to endpoint 0, ifindex 2, file nodeport.h:2645, , identity unknown->unknown: 10.224.52.137 -> 10.232.48.139 DestinationUnreachable(FragmentationNeeded)
xx drop (Error while correcting L4 checksum) flow 0x240c240c to endpoint 0, ifindex 2, file nodeport.h:2645, , identity unknown->unknown: 10.224.52.137 -> 10.232.48.139 DestinationUnreachable(FragmentationNeeded)
xx drop (Error while correcting L4 checksum) flow 0x240c240c to endpoint 0, ifindex 2, file nodeport.h:2645, , identity unknown->unknown: 10.224.52.137 -> 10.232.48.139 DestinationUnreachable(FragmentationNeeded)
xx drop (Error while correcting L4 checksum) flow 0x240c240c to endpoint 0, ifindex 2, file nodeport.h:2645, , identity unknown->unknown: 10.224.52.137 -> 10.232.48.139 DestinationUnreachable(FragmentationNeeded)
xx drop (Error while correcting L4 checksum) flow 0x240c240c to endpoint 0, ifindex 2, file nodeport.h:2645, , identity unknown->unknown: 10.224.52.137 -> 10.232.48.139 DestinationUnreachable(FragmentationNeeded)
xx drop (Error while correcting L4 checksum) flow 0x240c240c to endpoint 0, ifindex 2, file nodeport.h:2645, , identity unknown->unknown: 10.224.52.137 -> 10.232.48.139 DestinationUnreachable(FragmentationNeeded)
xx drop (Error while correcting L4 checksum) flow 0x240c240c to endpoint 0, ifindex 2, file nodeport.h:2645, , identity unknown->unknown: 10.224.52.137 -> 10.232.48.139 DestinationUnreachable(FragmentationNeeded)
xx drop (Error while correcting L4 checksum) flow 0x240c240c to endpoint 0, ifindex 2, file nodeport.h:2645, , identity unknown->unknown: 10.224.52.137 -> 10.232.48.139 DestinationUnreachable(FragmentationNeeded)
^C
Received an interrupt, disconnecting from monitor...
```

### Anything else?

_No response_

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by br4243**
Routers that send minimal RFC 1191 ICMP Error packets for MTU path discovery only include the first two 32-bit words of the original L4 header.  This is enough to include the L4 checksum for UDP, but not TCP; TCP needs an additional 3 32-bit words of the original datagram.  RFC 4884 provides a length field in octet 5 of the ICMP Error packet header to indicate there are additional words of the original datagram included.

This pays attention to the RFC 4884 length field and limits the L4 checksum update attempt to cases where there are enough bits of the original datagram included.

Signed-off-by:  Bill Reese <reesew@computer.org>

Fixes: #33844

```release-note
Fix "Error while correcting L4 checksum" dropped packets for ICMP destination unreachable error packets.
```

### CODE REVIEW

**Comment by br4243** [comment]
@pchaigno

Here is a candidate fix for issue #33844.
Thank you

**Comment by pchaigno** [comment]
@br4243 The `BPF Checks` and `Build Commits` workflows reported a few issues you'll need to fix. I'd recommend to also rebase at the same time (and whenever you push a new version in general).

**Comment by br4243** [comment]
@pchaigno I've rebased, fixed the compile warnings and made a first pass update for the test suite.  For the NAT test suite I changed the generation of the ICMP error packets to include the RFC 4884 extra length information, but I'd like to also add tests that generate truncated L4 content like that which causes the #33844 problem in the first place.

**Comment by pchaigno** [comment]
@br4243 I think you can make the pull request ready if you think it is. The last CI failures are likely flakes.

**Comment by br4243** [comment]
@pchaigno I added the additional tests, rebased and made the pull request ready.  Thank you!

**Comment by pchaigno** [comment]
Cc @ysksuzuki

File: bpf/lib/nat.h [hunk 1]
```diff
@@ -1031,8 +1050,19 @@ snat_v4_rev_nat_handle_icmp_error(struct __ctx_buff *ctx,
...
+	 * of the 1st 64 bits of the datagram following the IP header, but
+	 * TCP needs an additional 3 32-bit words to include the checksum.
+	 */
+	if (ctx_load_bytes(ctx, icmp_xlen_off, &icmp_xlen, sizeof(__u8)) < 0)
+		return DROP_INVALID;
+	icmp_has_full_l4_header = icmp_xlen >= ((tuple.nexthdr == IPPROTO_TCP) ? 3 : 0);
+
 	/* The embedded packet was SNATed on egress. Reverse it again: */
-	return snat_v4_rewrite_headers(ctx, tuple.nexthdr, (int)inner_l3_off, true, icmpoff,
+	return snat_v4_rewrite_headers(ctx, tuple.nexthdr, (int)inner_l3_off,
```
Comment (ysksuzuki) [inline bpf/lib/nat.h]: Wouldn't this mean that, for RFC 1191-compliant ICMP errors, if the original packet was TCP, the inner packet's port would not be modified? Wouldn't that be a problem?

**Review by ysksuzuki — COMMENTED** [review]
Thanks for the PR! Sorry for the late review. I’ve left one question.

File: bpf/lib/nat.h (hunk 1 above)
Comment (br4243) [reply bpf/lib/nat.h]: Yes, that's correct - for a short ICMP error packet the inner L4 ports won't be modified for TCP.  For path MTU discovery the kernel is [looking](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ipv4/tcp_ipv4.c#n494) at the outer L3/L4 header, which allows the MTU [fixup call](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ipv4/tcp_ipv4.c#n591) to succeed.

Comment (ysksuzuki) [reply bpf/lib/nat.h]: Thanks for the clarification. The original datagram data includes the source and destination ports, so rewriting them is possible, but since we can't update the checksum, we can't guarantee integrity. So does that mean there's no point in rewriting them?

That said, it makes me wonder, what's the point of including such incomplete data with no guarantee of integrity in the first place

Comment (br4243) [reply bpf/lib/nat.h]: My initial implementation of the fix left the call to snat_v4_rewrite_headers() intact with "true" for the inner L4 to go ahead and fix up the ports, but changed the check on its error return to ignore the error if there was not a complete header.  That way worked, too, and I can change it back to that if you'd rather see the port swap still happen.

Comment (joestringer) [reply bpf/lib/nat.h]: @ysksuzuki @br4243 does this need more discussion to resolve the conversation? It's a bit unclear to me what is the next step on this PR.

**Comment by joestringer** [comment]
Converting to draft while the threads above are resolved. When they're resolved, use the "Ready for Review" button at the bottom of the page to bring it back to the attention of the reviewers.

**Comment by br4243** [comment]
Since this is back to draft, I rebased on main and changed the implementation to retain the inner L4 header port NAT when the inner L4 header is short.  @ysksuzuki if you like this better can we resolve the discussion about the ports?

File: bpf/lib/nat.h (hunk 1 above)
Comment (pchaigno) [reply bpf/lib/nat.h]: @ysksuzuki Ping :slightly_smiling_face:

**Comment by ysksuzuki** [comment]
Hi @br4243, sorry for the late response and thank you for the clarification. Looks good to me.

**Review by ysksuzuki — APPROVED** [review]

**Comment by pchaigno** [comment]
@br4243 I think you'll need to rebase on latest `main` for CI to pass.

**Comment by br4243** [comment]
Thank you @pchaigno and @ysksuzuki - I've rebased the branch.

**Comment by br4243** [comment]
Oops - I rebased that from the wrong starting point, hence the bpf test failure.  It should be better, now.

**Comment by pchaigno** [comment]
You're branch is still 416 commits behind `main`. `git fetch origin && git rebase origin/main` should fix it assuming `upstream` is the cilium/cilium repository.

**Comment by pchaigno** [comment]
@br4243 I think this is ready to merge if you switch it to ready for reviews.

**Comment by br4243** [comment]
@pchaigno Thank you; I've so marked it.

**Comment by pchaigno** [comment]
Thanks again for the fix @br4243 and congrats on your first pull request in Cilium! :tada:

**Comment by yushoyamaguchi** [comment]
@br4243  @pchaigno 

I am currently working on this issue (https://github.com/cilium/cilium/issues/40827), but I implemented my patch without realizing the problem described here, that the inner TCP header may not be fully included. Now I want to add handling logic for this situation to my patch, so I have a few questions.

- ~~My understanding is that in `snat_v4_rewrite_headers()`, when the inner TCP header is not fully present, the L3 checksum/L4 checksum are not recalculated and the original values are kept because of the early-retrun. Is it correct? 
ref: https://github.com/cilium/cilium/blob/42f132a593f4e2b2dabef50bae1f421e13fc5e71/bpf/lib/nat.h#L513-L521~~
	- ~~I am writing logic to apply the inner packet's modifications(about addr/l3-csum/port/l4-csum) by `snat_v4_rewrite_headers()` to **the outer ICMP header**  ([ref](https://github.com/cilium/cilium/commit/cb797f6a6b52313fcd7da6f0238fa9bf7ff21b48) ), and I want to confirm this point.~~
- ~~Since recalculating the L3 checksum is not related to L4 header, wouldn’t it make more sense to move [this part](https://github.com/cilium/cilium/blob/42f132a593f4e2b2dabef50bae1f421e13fc5e71/bpf/lib/nat.h#L519-L521)  before the [has_l4_header conditional](https://github.com/cilium/cilium/blob/42f132a593f4e2b2dabef50bae1f421e13fc5e71/bpf/lib/nat.h#L476)?~~ 

<br>
I've made a PR. https://github.com/cilium/cilium/pull/41551.

**Comment by yushoyamaguchi** [comment]
- Is there a way to reproduce this situation (short ICMP error packets, which follow RFC1191) in a kind-cluster?
	- In my test environment, I use `iptables -A INPUT -p tcp --dport 55555  -j REJECT --reject-with icmp-port-unreachable` on LB's backend-pod to generate ICMP errors, but this produces long ICMP error packets.
	- BPF unit tests don’t work for verifying checksum, since they use arbitrary checksums.
