### PR TITLE
pkg/fswatcher: Rewrite without underlying use of fsnotify

### LINKED ISSUE #25666: CI: github.com/cilium/cilium/pkg/fswatcher timeout panic
### Test Name

```shell
github.com/cilium/cilium/pkg/fswatcher
```


### Failure Output

```shell
panic: test timed out after 10m0s                                                                  
running tests:                                                                                     
	Test (10m0s)                                                                                       
                                                                                                   
                      
FAIL	github.com/cilium/cilium/pkg/fswatcher	600.111s
```


### Stack Trace

```shell
goroutine 12 [running]:                                                                            
testing.(*M).startAlarm.func1()                                                                    
	/opt/hostedtoolcache/go/1.20.4/x64/src/testing/testing.go:2241 +0x3c5                              
created by time.goFunc                                                                             
	/opt/hostedtoolcache/go/1.20.4/x64/src/time/sleep.go:176 +0x32                                     
                                                                                                   
goroutine 1 [chan receive]:                                                                        
testing.(*T).Run(0xc000007d40, {0x6876dc?, 0x549885?}, 0x69a5c0)                                   
	/opt/hostedtoolcache/go/1.20.4/x64/src/testing/testing.go:1630 +0x405                              
testing.runTests.func1(0x8500a0?)                                                                  
	/opt/hostedtoolcache/go/1.20.4/x64/src/testing/testing.go:2036 +0x45                               
testing.tRunner(0xc000007d40, 0xc000070c80)                                                        
	/opt/hostedtoolcache/go/1.20.4/x64/src/testing/testing.go:1576 +0x10b                              
testing.runTests(0xc000100320?, {0x845520, 0x1, 0x1}, {0xc000108ce0?, 0x100c000108c20?, 0x84f6e0?})
	/opt/hostedtoolcache/go/1.20.4/x64/src/testing/testing.go:2034 +0x489                              
testing.(*M).Run(0xc000100320)                                                                     
	/opt/hostedtoolcache/go/1.20.4/x64/src/testing/testing.go:1906 +0x63a                              
main.main()                                                                                        
	_testmain.go:78 +0x1c5                                                                             
                                                                                                   
goroutine 6 [chan receive]:                                                                        
gopkg.in/check%2ev1.(*suiteRunner).runTest(...)                                                    
	/home/runner/work/cilium/cilium/vendor/gopkg.in/check.v1/check.go:813                              
gopkg.in/check%2ev1.(*suiteRunner).run(0xc000116100)                                               
	/home/runner/work/cilium/cilium/vendor/gopkg.in/check.v1/check.go:618 +0x1bd                       
gopkg.in/check%2ev1.Run({0x64d4e0?, 0x87d6d8?}, 0x8369a0?)                                         
	/home/runner/work/cilium/cilium/vendor/gopkg.in/check.v1/run.go:92 +0x2a                           
gopkg.in/check%2ev1.RunAll(0x8369a0?)                                                              
	/home/runner/work/cilium/cilium/vendor/gopkg.in/check.v1/run.go:84 +0x85                           
gopkg.in/check%2ev1.TestingT(0xc000124000)                                                         
	/home/runner/work/cilium/cilium/vendor/gopkg.in/check.v1/run.go:72 +0x27c                          
github.com/cilium/cilium/pkg/fswatcher.Test(0x0?)                                                  
	/home/runner/work/cilium/cilium/pkg/fswatcher/fswatcher_test.go:19 +0x19                           
testing.tRunner(0xc000124000, 0x69a5c0)                                                            
	/opt/hostedtoolcache/go/1.20.4/x64/src/testing/testing.go:1576 +0x10b                              
created by testing.(*T).Run                                                                        
	/opt/hostedtoolcache/go/1.20.4/x64/src/testing/testing.go:1629 +0x3ea                              
                                                                                                   
goroutine 7 [select]:                                                                              
gopkg.in/check%2ev1.(*resultTracker)._loopRoutine(0xc000128000)                                    
	/home/runner/work/cilium/cilium/vendor/gopkg.in/check.v1/check.go:464 +0x8d                        
created by gopkg.in/check%2ev1.(*resultTracker).start                                              
	/home/runner/work/cilium/cilium/vendor/gopkg.in/check.v1/check.go:444 +0x56                        
                                                                                                   
goroutine 8 [chan receive]:                                                                        
github.com/cilium/cilium/pkg/fswatcher.(*FsWatcherTestSuite).TestWatcher(0x0?, 0xc00012a000)       
	/home/runner/work/cilium/cilium/pkg/fswatcher/fswatcher_test.go:89 +0x9c9                          
reflect.Value.call({0x64d4e0?, 0x87d6d8?, 0x213?}, {0x687668, 0x4}, {0xc00006ff08, 0x1, 0x1?})     
	/opt/hostedtoolcache/go/1.20.4/x64/src/reflect/value.go:586 +0xb0b                                 
reflect.Value.Call({0x64d4e0?, 0x87d6d8?, 0xc00001e2a0?}, {0xc000042f08?, 0x0?, 0xc000042e96?})    
	/opt/hostedtoolcache/go/1.20.4/x64/src/reflect/value.go:370 +0xbc                                  
gopkg.in/check%2ev1.(*suiteRunner).forkTest.func1(0xc00012a000)                                    
	/home/runner/work/cilium/cilium/vendor/gopkg.in/check.v1/check.go:775 +0x632                       
gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1()                                                
	/home/runner/work/cilium/cilium/vendor/gopkg.in/check.v1/check.go:669 +0xa2                        
created by gopkg.in/check%2ev1.(*suiteRunner).forkCall                                             
	/home/runner/work/cilium/cilium/vendor/gopkg.in/check.v1/check.go:666 +0x285                       
                                                                                                   
goroutine 9 [IO wait]:                                                                             
internal/poll.runtime_pollWait(0x7fe2389e3158, 0x72)                                               
	/opt/hostedtoolcache/go/1.20.4/x64/src/runtime/netpoll.go:306 +0x89                                
internal/poll.(*pollDesc).wait(0xc0000685a0?, 0xc00018fed0?, 0x1)                                  
	/opt/hostedtoolcache/go/1.20.4/x64/src/internal/poll/fd_poll_runtime.go:84 +0x32                   
internal/poll.(*pollDesc).waitRead(...)                                                            
	/opt/hostedtoolcache/go/1.20.4/x64/src/internal/poll/fd_poll_runtime.go:89                         
internal/poll.(*FD).Read(0xc0000685a0, {0xc00018fed0, 0x10000, 0x10000})                           
	/opt/hostedtoolcache/go/1.20.4/x64/src/internal/poll/fd_unix.go:167 +0x299                         
os.(*File).read(...)                                                                               
	/opt/hostedtoolcache/go/1.20.4/x64/src/os/file_posix.go:31                                         
os.(*File).Read(0xc000012110, {0xc00018fed0?, 0x6d9ac8?, 0x1?})                                    
	/opt/hostedtoolcache/go/1.20.4/x64/src/os/file.go:118 +0x5e                                        
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc00006a280)                                   
	/home/runner/work/cilium/cilium/vendor/github.com/fsnotify/fsnotify/backend_inotify.go:356 +0xdf   
created by github.com/fsnotify/fsnotify.NewWatcher                                                 
	/home/runner/work/cilium/cilium/vendor/github.com/fsnotify/fsnotify/backend_inotify.go:150 +0x1b0  
                                                                                                   
goroutine 10 [select]:                                                                             
github.com/cilium/cilium/pkg/fswatcher.(*Watcher).loop(0xc000074db0)                               
	/home/runner/work/cilium/cilium/pkg/fswatcher/fswatcher.go:210 +0x109                              
created by github.com/cilium/cilium/pkg/fswatcher.New                                              
	/home/runner/work/cilium/cilium/pkg/fswatcher/fswatcher.go:98 +0x230                               
                                                                                                   
goroutine 11 [select]:                                                                             
github.com/cilium/cilium/pkg/fswatcher.(*FsWatcherTestSuite).TestWatcher.func1()                   
	/home/runner/work/cilium/cilium/pkg/fswatcher/fswatcher_test.go:46 +0xd8                           
created by github.com/cilium/cilium/pkg/fswatcher.(*FsWatcherTestSuite).TestWatcher                
	/home/runner/work/cilium/cilium/pkg/fswatcher/fswatcher_test.go:43 +0x5ec
```


### Standard Output

```shell
None
```


### Standard Error

```shell
None
```


### Resources

None

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by glibsm**
Remove reliance on fsnotify by replacing with a polling mechanism to check for modifications to tracked files.

There is a default interval that is configurable depending on the usage, and it is also significantly shortened when running tests.

Superseeds https://github.com/cilium/cilium/pull/37909
Fixes https://github.com/cilium/cilium/issues/25666

---

The original test cases were kept pretty much as-is, except they are now deterministic (at least so far on the mac)
```
❯ go test -count=100 -race ./pkg/fswatcher
ok      github.com/cilium/cilium/pkg/fswatcher  1.893s
```

### CODE REVIEW

File: pkg/fswatcher/fswatcher.go [hunk 1]
```diff
@@ -5,24 +5,54 @@ package fswatcher
...
-// Event currently wraps fsnotify.Event
-type Event fsnotify.Event
+// Has reports if this event has the given operation.
+func (e Event) Has(op Op) bool { return e.Op.Has(op) }
 
-// Watcher is a wrapper around fsnotify.Watcher which can track non-existing
+// Watcher implements a file polling mechanism which can track non-existing
 // files and emit creation events for them. All files which are supposed to be
 // tracked need to passed to the New constructor.
 //  1. If the file already exists, the watcher will emit write, chmod, remove
```
Comment (kaworu) [inline pkg/fswatcher/fswatcher.go]: This whole comment block should be rewritten as it still references fsnotify and (now) unsupported chmod events.

File: pkg/fswatcher/fswatcher.go [hunk 2]
```diff
@@ -64,37 +88,65 @@ type Watcher struct {
...
-	watcher, err := fsnotify.NewWatcher()
-	if err != nil {
-		return nil, err
+func New(trackedFiles []string, options ...Option) (*Watcher, error) {
+	// sane default that is configurable via WithInterval depending on the use case
+	defaultInterval := 5 * time.Second
+	if testing.Testing() {
+		// in a testing situation, refresh info much much faster to speed things up
+		defaultInterval = 10 * time.Millisecond
 	}
```
Comment (kaworu) [inline pkg/fswatcher/fswatcher.go]: nitpicking: Can we define a const for the default interval, and inject the testing one from the tests rather than in the constructor? It's counter-intuitive to me to change behavior like this, and I'd expect users of this package outside of the Cilium tree to overlook this. If we really want to keep it in then we should update the doc comment.

File: pkg/fswatcher/fswatcher.go [hunk 3]
```diff
@@ -64,37 +88,65 @@ type Watcher struct {
...
+	w.tracked = tracked
 
+	for _, option := range options {
+		option(w)
+	}
+
+	if w.interval != 0 {
+		w.ticker = time.Tick(w.interval)
+	}
```
Comment (kaworu) [inline pkg/fswatcher/fswatcher.go]: Shouldn't we return an error on `w.interval == 0`? If we don't `w.ticker` is `nil` and we will never attempt to read anything? If that is the intended behavior then we could remove the return `error` from `New`?

**EDIT**: ok after reading the tests it's clearer to me that it is intended: we setup `WithInterval(0)` to call `tick()` from the test in order to control exactly the fs state when the watcher take a look. No objection on the pattern, OTHO not a huge fan of exposing the behavior outside of the package (from the package test we have direct access to the `ticker` / channel).

File: pkg/fswatcher/fswatcher.go [hunk 4]
```diff
@@ -104,245 +156,117 @@ func (w *Watcher) Close() {
...
+		// some other type of error encountered while doing Lstat
+		if err != nil {
+			w.sendError(err)
+			continue
 		}
 
-		path = pathParent
-	}
-}
+		// symlinks are handled a little bit differntly
```
Comment (kaworu) [inline pkg/fswatcher/fswatcher.go]: typo
```suggestion
		// symlinks are handled a little bit differently
```

File: pkg/fswatcher/fswatcher_test.go [hunk 5]
```diff
@@ -22,113 +23,163 @@ func TestWatcher(t *testing.T) {
...
+				require.NoError(t, err)
+			},
+			want: []Event{
+				{Name: regularFile, Op: Create | Write},
+			},
+		},
+		{
+			name: "update file",
+			work: func() {
+				// create $tmp/file
```
Comment (kaworu) [inline pkg/fswatcher/fswatcher_test.go]: typo
```suggestion
				// update $tmp/file
```

File: pkg/fswatcher/fswatcher_test.go [hunk 6]
```diff
@@ -22,113 +23,163 @@ func TestWatcher(t *testing.T) {
...
+			name: "redirect symlink",
+			work: func() {
+				// redirect $tmp/symlink -> $tmp/file (this will not emit an event)
+				err := os.Remove(regularSymlink)
+				require.NoError(t, err)
+				err = os.Symlink(regularFile, regularSymlink)
+				require.NoError(t, err)
+			},
+			want: []Event{},
+		},
```
Comment (kaworu) [inline pkg/fswatcher/fswatcher_test.go]: AFAIU we're "watching" `regularSymlink` and this test case change it from `→ $tmp/target` to `→ $tmp/file` right? If correct, don't we need to emit something here?

File: pkg/fswatcher/fswatcher_test.go [hunk 7]
```diff
@@ -22,113 +23,163 @@ func TestWatcher(t *testing.T) {
...
+		{
+			name: "delete file",
```
Comment (kaworu) [inline pkg/fswatcher/fswatcher_test.go:122]: Can you add a symlink removal test case as well please?

**Review by kaworu — DISMISSED** [review]

File: pkg/fswatcher/fswatcher.go [hunk 8]
```diff
@@ -104,245 +156,117 @@ func (w *Watcher) Close() {
 	close(w.stop)
```
Comment (joamaki) [inline pkg/fswatcher/fswatcher.go:157]: Would it be possible to make this wait for the `loop` to exit? Perhaps also worth closing the channels. This way code using this that also uses `goleak` in tests wouldn't be flaky.

**Review by joamaki — APPROVED** [review]

**Review by ldelossa — APPROVED** [review]

File: pkg/fswatcher/fswatcher.go (hunk 3 above)
Comment (glibsm) [reply pkg/fswatcher/fswatcher.go]: I will try to find a neater pattern to do this only from the tests

File: pkg/fswatcher/fswatcher.go (hunk 1 above)
Comment (glibsm) [reply pkg/fswatcher/fswatcher.go]: I'm rewriting (as in mostly deleting) the godoc for the constructor.

Chmod can be added back if the need arises in the future.

File: pkg/fswatcher/fswatcher_test.go (hunk 6 above)
Comment (glibsm) [reply pkg/fswatcher/fswatcher_test.go]: That's a good question. I kept all the original test cases as is, so I didn't come up with this one.

File: pkg/fswatcher/fswatcher.go (hunk 2 above)
Comment (glibsm) [reply pkg/fswatcher/fswatcher.go]: Fixed, I think?

File: pkg/fswatcher/fswatcher_test.go (hunk 7 above)
Comment (glibsm) [reply pkg/fswatcher/fswatcher_test.go:122]: There was actually a bug, thanks for helping me uncover it. Should work properly now

File: pkg/fswatcher/fswatcher_test.go (hunk 6 above)
Comment (glibsm) [reply pkg/fswatcher/fswatcher_test.go]: After fixing a bug, this test was now updated with an event for the `regularSymlink: UPDATE`

File: pkg/fswatcher/fswatcher.go (hunk 8 above)
Comment (glibsm) [reply pkg/fswatcher/fswatcher.go:157]: Done, thanks for the suggestion.

**Review by gandro — COMMENTED** [review]
Looks good overall. Given there are still a few unknowns w.r.t. symlinks in the logic, have you tested this in a life K8s cluster and checked if it correctly detected updates to a ConfigMap/Secret mount?

File: pkg/fswatcher/fswatcher.go [hunk 9]
```diff
@@ -64,285 +89,209 @@ type Watcher struct {
...
+
+				// clear out old state from the map
+				w.tracked[oldState.path] = newState
+			}
 
-	for {
-		pathParent := filepath.Dir(path)
-		if pathParent == parent {
-			return true
+			// the path doesn't exist, and it didn't exist before -- ignore for now
```
Comment (kaworu) [inline pkg/fswatcher/fswatcher.go]: We're still going through this path when the file did exist before and was removed. As-is it's easy enough to understand because the block is small and granted it's not expected to grow so ok.

**Review by kaworu — COMMENTED** [review]
> have you tested this in a life K8s cluster and checked if it correctly detected updates to a ConfigMap/Secret mount?

IIRC you need to project the ConfigMap/Secret for k8s to do the weird symlink dance, like we do for e.g. [the Hubble server TLS cert](https://github.com/cilium/cilium/blob/595c0ac632d464def3bc7fc213e13b55f29fdd77/install/kubernetes/cilium/templates/cilium-agent/daemonset.yaml#L1004-L1029).

File: pkg/fswatcher/fswatcher.go (hunk 9 above)
Comment (glibsm) [reply pkg/fswatcher/fswatcher.go]: Yeah I think this comment is just incorrect as a result of a refactor at some point

**Comment by glibsm** [comment]
I did some local testing to see what happens when a secret is projected to filesystem and is then subsequently updated.

I deployed a basic pod which mounts a secret:
```
...
    spec:
      containers:
        - name: sleeper
          image: busybox
          command: ["sleep", "3600"]
          volumeMounts:
            - name: projected-secrets
              mountPath: "/tmp/projected-secrets"
              readOnly: true
      volumes:
        - name: projected-secrets
          projected:
            sources:
              - secret:
                  name: my-secret
```

And the resulting structure looks like this with the original key `apikey123`
```
$ /tmp/projected-secrets # ls -al
total 4
drwxrwxrwt    3 root     root           140 May  2 16:57 .
drwxrwxrwt    1 root     root          4096 May  2 16:57 ..
drwxr-xr-x    2 root     root           100 May  2 16:57 ..2025_05_02_16_57_16.1478340719
lrwxrwxrwx    1 root     root            32 May  2 16:57 ..data -> ..2025_05_02_16_57_16.1478340719
lrwxrwxrwx    1 root     root            14 May  2 16:57 api-key -> ..data/api-key
lrwxrwxrwx    1 root     root            15 May  2 16:57 password -> ..data/password
lrwxrwxrwx    1 root     root            15 May  2 16:57 username -> ..data/username
$ /tmp/projected-secrets # cat -n api-key
     1  apikey123
```

After I edit the key and a few seconds have passed
```
$ k edit secret
secret/my-secret edited
```

The directory structure looks as follows:
```
$ /tmp/projected-secrets # ls -al
total 4
drwxrwxrwt    3 root     root           140 May  2 17:02 .
drwxrwxrwt    1 root     root          4096 May  2 16:57 ..
drwxr-xr-x    2 root     root           100 May  2 17:02 ..2025_05_02_17_02_00.1481948809
lrwxrwxrwx    1 root     root            32 May  2 17:02 ..data -> ..2025_05_02_17_02_00.1481948809
lrwxrwxrwx    1 root     root            14 May  2 16:57 api-key -> ..data/api-key
lrwxrwxrwx    1 root     root            15 May  2 16:57 password -> ..data/password
lrwxrwxrwx    1 root     root            15 May  2 16:57 username -> ..data/username
$ /tmp/projected-secrets # cat -n api-key
     1  apikey456
```

To the best of my knowledge you can't edit symlinks, so it looks like when a new directory `..2025_05_02_17_02_00.1481948809` is created, the old symlink `..data` is deleted a new one created in it's place.

I will try to add exactly this test case into the `fswatcher_test` to see what we get. 

My gut tells me that new fswatcher should be able to handle this very well since we do `os.Stat` on the `api-key` and check the contents of the target (size and modtime) and should be able to detect the change very easily even though there are two symlinks in the way.

**Comment by glibsm** [comment]
Added a new test that mimics the kubernetes secret projection and a subsequent value update -- the fswatcher works for it without any additional changes 🥳

File: pkg/fswatcher/fswatcher_test.go [hunk 10]
```diff
@@ -7,128 +7,362 @@ import (
...
+				// new value for key1 -- should detect write
+				// config/..2025.456/key1 = key1value2
+				require.NoError(t,
+					os.WriteFile(
+						filepath.Join(dataUpdated, key1),
+						key1value2, 0777,
+					),
+				)
+
+				// same value for key2 -- no value change, but ModTime||Size shuold
```
Comment (gandro) [inline pkg/fswatcher/fswatcher_test.go]:
```suggestion
				// same value for key2 -- no value change, but ModTime||Size should
```

**Review by gandro — APPROVED** [review]
Thanks!

File: pkg/fswatcher/fswatcher.go [hunk 11]
```diff
@@ -4,41 +4,73 @@
...
-	"github.com/sirupsen/logrus"
+	"github.com/cilium/cilium/pkg/time"
+)
+
+const (
+	// how often tracked targets are checked for changes by default
+	defaultInterval = 5 * time.Second
+
+	// when fswatcher detects that it runs in a test, it will refresh things much faster
+	testInterval = 50 * time.Millisecond
```
Comment (gandro) [inline pkg/fswatcher/fswatcher.go]: Do we want to backport this PR to older versions of Cilium? If not, consider using [https://go.dev/blog/synctest instead](https://go.dev/blog/synctest#testing-time)

File: pkg/fswatcher/fswatcher.go [hunk 12]
```diff
@@ -64,285 +90,161 @@ type Watcher struct {
...
+		file, err := os.Open(path)
+		if err != nil {
+			w.sendError(err)
+			continue
 		}
 
-		// reached the root
-		if pathParent == path {
-			return false
+		h := sha256.New()
```
Comment (gandro) [inline pkg/fswatcher/fswatcher.go]: optional nit: We're probably i/o bound anyway, but consider using a fast non-cryptographic checksum like FNV https://pkg.go.dev/hash/fnv

It also gives you a uint64 which is faster to compare than a byte slice.

**Review by gandro — APPROVED** [review]
Very nice!

File: pkg/fswatcher/fswatcher.go (hunk 12 above)
Comment (glibsm) [reply pkg/fswatcher/fswatcher.go]: Thanks, I'll take a look didn't know about those.

File: pkg/fswatcher/fswatcher.go (hunk 11 above)
Comment (glibsm) [reply pkg/fswatcher/fswatcher.go]: It looks very tempting to try, but I'm a bit hesitant to use an experimental feature that's still behind a feature flag which would require a change in the build requirements. Maybe better to let it bake for another version :)

Comment (gandro) [reply pkg/fswatcher/fswatcher.go]: Ah, my bad - I thought we already did use synctest in Cilium and didn't realize it was still behind a feature flag.

File: pkg/fswatcher/fswatcher.go [hunk 13]
```diff
@@ -4,41 +4,72 @@
...
-	"github.com/fsnotify/fsnotify"
-	"github.com/sirupsen/logrus"
+	"github.com/cilium/cilium/pkg/time"
+)
+
+const (
+	// how often tracked targets are checked for changes by default
+	defaultInterval = 5 * time.Second
+
+	// when fswatcher detects that it runs in a test, it will refresh things much faster
```
Comment (kaworu) [inline pkg/fswatcher/fswatcher.go]: nit
```suggestion
	// when fswatcher detects that it runs in a test, it will poll the filesystem more frequently
```

File: pkg/fswatcher/fswatcher.go [hunk 14]
```diff
@@ -4,41 +4,72 @@
...
+
+	// File operation that triggered the event.
+	//
+	// This is a bitmask and some systems may send multiple operations at once.
+	// Use the Event.Has() method instead of comparing with ==.
+	Op Op
+}
+
+// Op describes a set of file operations.
+type Op uint32
```
Comment (kaworu) [inline pkg/fswatcher/fswatcher.go]: unless we have a good reason, let Go decide of the length
```suggestion
type Op uint
```

File: pkg/fswatcher/fswatcher.go [hunk 15]
```diff
@@ -4,41 +4,72 @@
...
+)
+
+// Event closely resembles what fsnotify.Event provided
+type Event struct {
+	// Path to the file or directory.
+	//
+	// Paths are relative to the input; for example with Add("dir") the Name
+	// will be set to "dir/file" if you create that file, but if you use
+	// Add("/path/to/dir") it will be "/path/to/dir/file".
+	Name string
```
Comment (kaworu) [inline pkg/fswatcher/fswatcher.go]: `Name` has to be a file after this patch correct? Or do we handle directory for `Create` / `Remove` events only? Also we don't use fsnotify `Add()` anymore, so this section is outdated.

File: pkg/fswatcher/fswatcher.go [hunk 16]
```diff
@@ -4,41 +4,72 @@
...
+	// The pathname was written to; this does *not* mean the write has finished,
+	// and a write can be followed by more writes.
+	Write
 
-	"github.com/cilium/cilium/pkg/counter"
-	"github.com/cilium/cilium/pkg/logging"
-	"github.com/cilium/cilium/pkg/logging/logfields"
+	// The path was removed; any watches on it will be removed. Some "remove"
+	// operations may trigger a Rename if the file is actually moved (for
+	// example "remove to trash" is often a rename).
```
Comment (kaworu) [inline pkg/fswatcher/fswatcher.go]: We do not support rename, so this section is confusing.

File: pkg/fswatcher/fswatcher.go [hunk 17]
```diff
@@ -49,12 +80,6 @@ type Event fsnotify.Event
 // itself does not emit an event. Only if the target of the symlink observes
 // an event is the symlink re-evaluated.
```
Comment (kaworu) [inline pkg/fswatcher/fswatcher.go]: I think this whole section needs to be updated too.

File: pkg/fswatcher/fswatcher.go [hunk 18]
```diff
@@ -64,285 +89,160 @@ type Watcher struct {
...
-}
+func (w *Watcher) tick() {
+	for _, oldState := range w.tracked {
+		var (
+			path     = oldState.path
+			oldInfo  = oldState.info
+			newState = state{path: oldState.path}
+		)
+
+		// os.Stat follows symlinks, os.Lstat doesn't
```
Comment (kaworu) [inline pkg/fswatcher/fswatcher.go:202]: is this still relevant now that the patch doesn't have a special symlink handling?

**Review by kaworu — CHANGES_REQUESTED** [review]
Thanks for the update Glib, patch LGTM but the comments need updating as well :pray:

File: pkg/fswatcher/fswatcher.go (hunk 18 above)
Comment (glibsm) [reply pkg/fswatcher/fswatcher.go:202]: It's relevant in the sense that we have to use `os.Stat` here else symlink tracking would break. Just preventing temptation of someone to write Lstat here instead I guess

File: pkg/fswatcher/fswatcher.go (hunk 15 above)
Comment (glibsm) [reply pkg/fswatcher/fswatcher.go]: Good point, added handling for directories as well because why not

**Comment by glibsm** [comment]
CI error seems like it could be related.

```
time=2025-05-19T21:17:42Z level=error source=/go/src/github.com/cilium/cilium/pkg/datapath/linux/ipsec/ipsec_linux.go:1186 msg="Failed to load IPsec keyfile" module=agent.datapath.ipsec-key-custodian error="invalid SPI: changing IPSec keys requires incrementing the key id" (1 occurrences)
```

That code is triggered via fswatcher notifications. Need to look at the test setup, maybe something about the new timing in tests is not working as expected.

**Review by kaworu — APPROVED** [review]

**Comment by gandro** [comment]
Should we backport this?

**Comment by glibsm** [comment]
> Should we backport this?

I think it's worth backporting, yeah. It should help CI health among other things. Backport may not be clean depending on the status of the slog migration PR which caused a rebase conflict halfway through this PR
