### PR TITLE
Fix source identity determination for DSR with Geneve-dispatch

### LINKED ISSUE #29153: Cilium Identity cannot be specified correctly when Geneve DSR is enabled
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When using Cilium with Geneve DSR, requests from outside the cluster are dropped by CiliumNetworkPolicy even though it’s permitted with `fromCIDR` like below.

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: ingress-allow
  namespace: test
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: dsr-geneve-test
  ingress:
  - fromCIDR:
    - 172.20.0.0/16  
```

Command

```console
# Send a request from outside the cluster via the Service(NodePort)
$ curl 172.20.0.3:32759
# No response and timeout
```

Kubernetes Resources

```console
$ kubectl get all -n test -o wide && kubectl get no -o wide
NAME                                   READY   STATUS    RESTARTS   AGE    IP            NODE           NOMINATED NODE   READINESS GATES
pod/dsr-geneve-test-67fb7f94bf-zf4nw   1/1     Running   0          2m4s   10.244.2.49   kind-worker2   <none>           <none>

NAME                      TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE    SELECTOR
service/dsr-geneve-test   NodePort   10.96.237.227   <none>        80:32759/TCP   2m4s   app.kubernetes.io/name=dsr-geneve-test

NAME                              READY   UP-TO-DATE   AVAILABLE   AGE    CONTAINERS   IMAGES                       SELECTOR
deployment.apps/dsr-geneve-test   1/1     1            1           2m4s   testhttpd    quay.io/cybozu/testhttpd:0   app.kubernetes.io/name=dsr-geneve-test

NAME                                         DESIRED   CURRENT   READY   AGE    CONTAINERS   IMAGES                       SELECTOR
replicaset.apps/dsr-geneve-test-67fb7f94bf   1         1         1       2m4s   testhttpd    quay.io/cybozu/testhttpd:0   app.kubernetes.io/name=dsr-geneve-test,pod-template-hash=67fb7f94bf
NAME                 STATUS     ROLES           AGE     VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION             CONTAINER-RUNTIME
kind-control-plane   Ready      control-plane   8m24s   v1.27.3   172.20.0.5    <none>        Debian GNU/Linux 11 (bullseye)   5.15.119-0515119-generic   containerd://1.7.1
kind-worker          Ready      <none>          8m1s    v1.27.3   172.20.0.3    <none>        Debian GNU/Linux 11 (bullseye)   5.15.119-0515119-generic   containerd://1.7.1
kind-worker2         Ready      <none>          8m1s    v1.27.3   172.20.0.2    <none>        Debian GNU/Linux 11 (bullseye)   5.15.119-0515119-generic   containerd://1.7.1
kind-worker3         NotReady   <none>          8m2s    v1.27.3   172.20.0.4    <none>        Debian GNU/Linux 11 (bullseye)   5.15.119-0515119-generic   containerd://1.7.1
```

`hubble observe` output 

```console
Nov 13 07:57:28.786: 172.20.0.1:44776 (ID:16777217) <> test/dsr-geneve-test-67fb7f94bf-zf4nw:8000 (ID:12730) from-overlay FORWARDED (TCP Flags: SYN)
Nov 13 07:57:28.786: 172.20.0.1:44776 (world) <> test/dsr-geneve-test-67fb7f94bf-zf4nw:8000 (ID:12730) policy-verdict:none INGRESS DENIED (TCP Flags: SYN)
Nov 13 07:57:28.786: 172.20.0.1:44776 (world) <> test/dsr-geneve-test-67fb7f94bf-zf4nw:8000 (ID:12730) Policy denied DROPPED (TCP Flags: SYN)
```

Other related manifests (e.g. Pod) are these↓

```yaml
kind: Namespace
apiVersion: v1
metadata:
  name: test
  labels:
    name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsr-geneve-test
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dsr-geneve-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dsr-geneve-test
    spec:
      containers:
      - image: quay.io/cybozu/testhttpd:0 # refs: https://github.com/cybozu/neco-containers/tree/main/testhttpd
        name: testhttpd
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "infinity"]
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: dsr-geneve-test
  namespace: test
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/name: dsr-geneve-test
```

 
Looking at hubble observe output, client’s identity is `world` when it’s dropped by the policy, although it’s specified as `16777217` in from-overlay.
It seems that client’s identity is not determined by its IP after `from-overlay` output. 

### Cilium Version

```
Client: 1.14.3 252a99efbc 2023-10-18T18:21:56+03:00 go version go1.20.10 linux/amd64
Daemon: 1.14.3 252a99efbc 2023-10-18T18:21:56+03:00 go version go1.20.10 linux/amd64
```

### Kernel Version

```
Linux kind-worker2 5.15.119-0515119-generic #202307080749 SMP Sat Jul 8 07:57:04 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-15T00:36:28Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
```

### Sysdump

_No response_

### Relevant log output

```shell
# cilium identity list and cilium bpf ipcache list 

$ cilium identity list
ID         LABELS
1          reserved:host
2          reserved:world
...
16777217   cidr:172.20.0.0/16
           reserved:world

$ cilium bpf ipcache list
IP PREFIX/ADDRESS               IDENTITY
172.20.0.3/32                   identity=6 encryptkey=0 tunnelendpoint=0.0.0.0
fd00:10:244:3::dd0e/128         identity=2865 encryptkey=0 tunnelendpoint=172.20.0.3
10.244.2.233/32                 identity=4 encryptkey=0 tunnelendpoint=0.0.0.0
10.244.3.51/32                  identity=4 encryptkey=0 tunnelendpoint=172.20.0.3
fe80::944c:b2ff:fe07:bafc/128   identity=1 encryptkey=0 tunnelendpoint=0.0.0.0
10.244.3.59/32                  identity=6 encryptkey=0 tunnelendpoint=172.20.0.3
172.20.0.2/32                   identity=1 encryptkey=0 tunnelendpoint=0.0.0.0
fd00:10:244::3617/128           identity=6 encryptkey=0 tunnelendpoint=172.20.0.5
fd00:10:244:2::7a4d/128         identity=12730 encryptkey=0 tunnelendpoint=0.0.0.0
fd00:10:244:3::1204/128         identity=53685 encryptkey=0 tunnelendpoint=172.20.0.3
fd00:10:244:3::929d/128         identity=4 encryptkey=0 tunnelendpoint=172.20.0.3
10.244.0.83/32                  identity=4 encryptkey=0 tunnelendpoint=172.20.0.5
10.244.3.210/32                 identity=53685 encryptkey=0 tunnelendpoint=172.20.0.3
172.20.0.5/32                   identity=7 encryptkey=0 tunnelendpoint=0.0.0.0
fc00:c111::3/128                identity=6 encryptkey=0 tunnelendpoint=0.0.0.0
fd00:10:244::8732/128           identity=4 encryptkey=0 tunnelendpoint=172.20.0.5
10.244.3.54/32                  identity=13908 encryptkey=0 tunnelendpoint=172.20.0.3
10.244.3.69/32                  identity=53685 encryptkey=0 tunnelendpoint=172.20.0.3
0.0.0.0/0                       identity=2 encryptkey=0 tunnelendpoint=0.0.0.0
fd00:10:244:3::9765/128         identity=53685 encryptkey=0 tunnelendpoint=172.20.0.3
fc00:c111::2/128                identity=1 encryptkey=0 tunnelendpoint=0.0.0.0
10.244.0.72/32                  identity=6 encryptkey=0 tunnelendpoint=172.20.0.5
10.244.2.49/32                  identity=12730 encryptkey=0 tunnelendpoint=0.0.0.0
fc00:c111::5/128                identity=6 encryptkey=0 tunnelendpoint=0.0.0.0
fd00:10:244:2::abe1/128         identity=4 encryptkey=0 tunnelendpoint=0.0.0.0
10.244.2.219/32                 identity=1 encryptkey=0 tunnelendpoint=0.0.0.0
172.20.0.0/16                   identity=16777217 encryptkey=0 tunnelendpoint=0.0.0.0
fd00:10:244:3::8bdf/128         identity=13908 encryptkey=0 tunnelendpoint=172.20.0.3
fd00:10:244:3::d7d4/128         identity=6 encryptkey=0 tunnelendpoint=172.20.0.3
::/0                            identity=2 encryptkey=0 tunnelendpoint=0.0.0.0
10.244.3.21/32                  identity=2865 encryptkey=0 tunnelendpoint=172.20.0.3
fd00:10:244:2::e49/128          identity=1 encryptkey=0 tunnelendpoint=0.0.0.0


# cilium config related DSR mode

$ cilium config view |grep dsr
bpf-lb-dsr-dispatch                               geneve
bpf-lb-mode                                       dsr
```

### Anything else?

My colleague @terassyi and I have been working on this issue and we’ve submitted a PR #29155  .

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by chez-shanpu**
When DSR with Geneve is enabled, Cilium identity is not determined by the client's IP address and requests from outside cluster are dropped even though they are permitted by CiliumNetworkPolicy using `fromCIDR`.

This PR inputs identity that is from the client IP address.

Fixes: #29153

```release-note
Fix source identity determination for DSR with Geneve-dispatch, by looking it up from the ipcache.
```

---
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

### CODE REVIEW

File: bpf/bpf_overlay.c [hunk 1]
```diff
@@ -355,6 +358,9 @@ static __always_inline int handle_ipv4(struct __ctx_buff *ctx,
 		/* See comment at equivalent code in handle_ipv6() */
 		if (info && identity_is_remote_node(*identity))
 			*identity = info->sec_identity;
+
+		if (info && identity_is_world_ipv4(*identity))
+			*identity = info->sec_identity;
```
Comment (YutaroHayakawa) [inline bpf/bpf_overlay.c]: Nit: How about doing like this?

```
		if (info && (identity_is_remote_node(*identity) || identity_is_world_ipv4(*identity)))
			*identity = info->sec_identity;
```

Comment (chez-shanpu) [reply bpf/bpf_overlay.c]: Thank you! I've fixed :) 
Also, I added some comments just before this block.

File: bpf/bpf_overlay.c [hunk 2]
```diff
@@ -353,7 +356,7 @@ static __always_inline int handle_ipv4(struct __ctx_buff *ctx,
 		}
 #endif
 		/* See comment at equivalent code in handle_ipv6() */
-		if (info && identity_is_remote_node(*identity))
+		if (info && (identity_is_remote_node(*identity) || identity_is_world_ipv4(*identity)))
```
Comment (ysksuzuki) [inline bpf/bpf_overlay.c]: With SNAT + tunneling, packets from LB SNATed with a remote node IP can be wrongly resolved as remote node identity?

See: https://github.com/cilium/cilium/blob/d93506e85f07aa42d650efc7f236a76601efc031/bpf/lib/nodeport.h#L2687-L2693

**Review by ysksuzuki — CHANGES_REQUESTED** [review]

File: bpf/bpf_overlay.c (hunk 2 above)
Comment (julianwiedmann) [reply bpf/bpf_overlay.c]: Agree, this is a bit too invasive right now I think and would conflict with SNATed LB connections.

Maybe just pass a `is_dsr` flag up from `nodeport_lb*()`? And use that in `from-overlay` to decide whether to resolve the identity from ipcache.

Comment (chez-shanpu) [reply bpf/bpf_overlay.c]: I see.
How about using `#ifdef`? 
I think we can use it like `#ifdef ENABLE_DSR` when DSR is enabled.

Comment (ysksuzuki) [reply bpf/bpf_overlay.c]: With `#ifdef`, in-cluster(pod to pod) communication over tunnel relies on ipcache too instead of the tunnel header when DSR is enabled, right? It would still be invasive, perhaps.

Comment (chez-shanpu) [reply bpf/bpf_overlay.c]: Oh that makes sense. Yes, we should decide whether to use ipcache per packet not config.

Comment (chez-shanpu) [reply bpf/bpf_overlay.c]: I pushed some changes adding `is_dsr` flag :)

File: bpf/bpf_overlay.c [hunk 3]
```diff
@@ -353,7 +359,8 @@ static __always_inline int handle_ipv4(struct __ctx_buff *ctx,
 		}
 #endif
 		/* See comment at equivalent code in handle_ipv6() */
-		if (info && identity_is_remote_node(*identity))
+		if (info && (identity_is_remote_node(*identity) ||
+			     (is_dsr && identity_is_world_ipv4(*identity))))
```
Comment (julianwiedmann) [inline bpf/bpf_overlay.c:363]: Looks good, ty! I wonder if we truly need the `identity_is_world_ipv4()` check, or should just always override the source identity. But that's not a blocking change.

Have you double-checked whether we now get the same behaviour as when using "IP opt/ext" DSR? It derives the identity via https://github.com/cilium/cilium/blob/8d7dd285d75a78ab32153fbc8812de5082f721f9/bpf/bpf_host.c#L474-L476, with `srcid_from_proxy == 0` and `from_host == false`.

Comment (chez-shanpu) [reply bpf/bpf_overlay.c:363]: > I wonder if we truly need the identity_is_world_ipv4() check, or should just always override the source identity.

I put `identity_is_world`, but as you wrote, I too think it will work well whether we check its identity or not if the packet has DSR info.
@ysksuzuki wdyt?

> Have you double-checked whether we now get the same behaviour as when using "IP opt/ext" DSR?

I've checked with my k8s, and it almost works well.
But the identity is still `reserved:world-ipv4/6` at from-overlay when the DSR with Geneve is enabled🤔
`hubble observe` outputs are these↓

**IP opt**
```console
Nov 20 04:32:48.556: 172.19.0.3:59036 (ID:16777220) <> test/dsr-geneve-test-67fb7f94bf-tcnm7:8000 (ID:58676) from-network FORWARDED (TCP Flags: SYN)
Nov 20 04:32:48.556: 172.19.0.3:59036 (ID:16777220) -> test/dsr-geneve-test-67fb7f94bf-tcnm7:8000 (ID:58676) policy-verdict:L3-Only INGRESS ALLOWED (TCP Flags: SYN)
Nov 20 04:32:48.556: 172.19.0.3:59036 (ID:16777220) -> test/dsr-geneve-test-67fb7f94bf-tcnm7:8000 (ID:58676) to-endpoint FORWARDED (TCP Flags: SYN)
Nov 20 04:32:48.556: 172.19.0.3:59036 (ID:16777220) <> test/dsr-geneve-test-67fb7f94bf-tcnm7:8000 (ID:58676) from-network FORWARDED (TCP Flags: ACK)
Nov 20 04:32:48.556: 172.19.0.3:59036 (ID:16777220) -> test/dsr-geneve-test-67fb7f94bf-tcnm7:8000 (ID:58676) to-endpoint FORWARDED (TCP Flags: ACK)
Nov 20 04:32:48.556: 172.19.0.3:59036 (ID:16777220) <> test/dsr-geneve-test-67fb7f94bf-tcnm7:8000 (ID:58676) from-network FORWARDED (TCP Flags: ACK, PSH)
Nov 20 04:32:48.556: 172.19.0.3:59036 (ID:16777220) -> test/dsr-geneve-test-67fb7f94bf-tcnm7:8000 (ID:58676) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
Nov 20 04:32:48.556: 172.19.0.3:59036 (ID:16777220) <> test/dsr-geneve-test-67fb7f94bf-tcnm7 (ID:58676) pre-xlate-rev TRACED (TCP)
Nov 20 04:32:48.556: 172.19.0.3:59036 (ID:16777220) <> test/dsr-geneve-test-67fb7f94bf-tcnm7 (ID:58676) pre-xlate-rev TRACED (TCP)
Nov 20 04:32:48.578: 172.19.0.3:59036 (ID:16777220) <> test/dsr-geneve-test-67fb7f94bf-tcnm7:8000 (ID:58676) from-network FORWARDED (TCP Flags: ACK)
Nov 20 04:32:48.578: 172.19.0.3:59036 (ID:16777220) -> test/dsr-geneve-test-67fb7f94bf-tcnm7:8000 (ID:58676) to-endpoint FORWARDED (TCP Flags: ACK)
Nov 20 04:32:48.578: 172.19.0.3:59036 (ID:16777220) <> test/dsr-geneve-test-67fb7f94bf-tcnm7:8000 (ID:58676) from-network FORWARDED (TCP Flags: ACK, FIN)
Nov 20 04:32:48.578: 172.19.0.3:59036 (ID:16777220) -> test/dsr-geneve-test-67fb7f94bf-tcnm7:8000 (ID:58676) to-endpoint FORWARDED (TCP Flags: ACK, FIN)
Nov 20 04:32:48.579: 172.19.0.3:59036 (ID:16777220) <> test/dsr-geneve-test-67fb7f94bf-tcnm7:8000 (ID:58676) from-network FORWARDED (TCP Flags: ACK)
Nov 20 04:32:48.579: 172.19.0.3:59036 (ID:16777220) -> test/dsr-geneve-test-67fb7f94bf-tcnm7:8000 (ID:58676) to-endpoint FORWARDED (TCP Flags: ACK)
```

**IP ext**
```console
Nov 20 04:30:48.839: fc00:c111::3 (ID:16777221) <> test/dsr-geneve-test-67fb7f94bf-r9snj (ID:58676) from-network FORWARDED (IPv6)
Nov 20 04:30:48.839: fc00:c111::3 (ID:16777221) -> test/dsr-geneve-test-67fb7f94bf-r9snj (ID:58676) policy-verdict:L3-Only INGRESS ALLOWED (IPv6)
Nov 20 04:30:48.839: fc00:c111::3 (ID:16777221) -> test/dsr-geneve-test-67fb7f94bf-r9snj (ID:58676) to-endpoint FORWARDED (IPv6)
Nov 20 04:30:48.839: [fc00:c111::3]:44532 (ID:16777221) <> test/dsr-geneve-test-67fb7f94bf-r9snj:8000 (ID:58676) from-network FORWARDED (TCP Flags: ACK)
Nov 20 04:30:48.839: [fc00:c111::3]:44532 (ID:16777221) -> test/dsr-geneve-test-67fb7f94bf-r9snj:8000 (ID:58676) to-endpoint FORWARDED (TCP Flags: ACK)
Nov 20 04:30:48.839: [fc00:c111::3]:44532 (ID:16777221) <> test/dsr-geneve-test-67fb7f94bf-r9snj:8000 (ID:58676) from-network FORWARDED (TCP Flags: ACK, PSH)
Nov 20 04:30:48.839: [fc00:c111::3]:44532 (ID:16777221) -> test/dsr-geneve-test-67fb7f94bf-r9snj:8000 (ID:58676) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
Nov 20 04:30:48.840: [fc00:c111::3]:44532 (ID:16777221) <> test/dsr-geneve-test-67fb7f94bf-r9snj (ID:58676) pre-xlate-rev TRACED (TCP)
Nov 20 04:30:48.866: [fc00:c111::3]:44532 (ID:16777221) <> test/dsr-geneve-test-67fb7f94bf-r9snj:8000 (ID:58676) from-network FORWARDED (TCP Flags: ACK)
Nov 20 04:30:48.866: [fc00:c111::3]:44532 (ID:16777221) -> test/dsr-geneve-test-67fb7f94bf-r9snj:8000 (ID:58676) to-endpoint FORWARDED (TCP Flags: ACK)
Nov 20 04:30:48.866: [fc00:c111::3]:44532 (ID:16777221) <> test/dsr-geneve-test-67fb7f94bf-r9snj:8000 (ID:58676) from-network FORWARDED (TCP Flags: ACK, FIN)
Nov 20 04:30:48.866: [fc00:c111::3]:44532 (ID:16777221) -> test/dsr-geneve-test-67fb7f94bf-r9snj:8000 (ID:58676) to-endpoint FORWARDED (TCP Flags: ACK, FIN)
Nov 20 04:30:48.869: [fc00:c111::3]:44532 (ID:16777221) <> test/dsr-geneve-test-67fb7f94bf-r9snj:8000 (ID:58676) from-network FORWARDED (TCP Flags: ACK)
Nov 20 04:30:48.869: [fc00:c111::3]:44532 (ID:16777221) -> test/dsr-geneve-test-67fb7f94bf-r9snj:8000 (ID:58676) to-endpoint FORWARDED (TCP Flags: ACK)
```

**geneve(ipv4)**
```console
Nov 20 07:22:07.986: 172.19.0.5:38448 (ID:9) <> test/dsr-geneve-test-67fb7f94bf-466f7:8000 (ID:8532) from-overlay FORWARDED (TCP Flags: SYN)
Nov 20 07:22:07.986: 172.19.0.5:38448 (ID:16777219) -> test/dsr-geneve-test-67fb7f94bf-466f7:8000 (ID:8532) policy-verdict:L3-Only INGRESS ALLOWED (TCP Flags: SYN)
Nov 20 07:22:07.986: 172.19.0.5:38448 (ID:16777219) -> test/dsr-geneve-test-67fb7f94bf-466f7:8000 (ID:8532) to-endpoint FORWARDED (TCP Flags: SYN)
Nov 20 07:22:07.987: 172.19.0.5:38448 (ID:9) <> test/dsr-geneve-test-67fb7f94bf-466f7:8000 (ID:8532) from-overlay FORWARDED (TCP Flags: ACK)
Nov 20 07:22:07.987: 172.19.0.5:38448 (ID:16777219) -> test/dsr-geneve-test-67fb7f94bf-466f7:8000 (ID:8532) to-endpoint FORWARDED (TCP Flags: ACK)
Nov 20 07:22:07.988: 172.19.0.5:38448 (ID:16777219) <> test/dsr-geneve-test-67fb7f94bf-466f7 (ID:8532) pre-xlate-rev TRACED (TCP)
Nov 20 07:22:07.988: 172.19.0.5:38448 (ID:16777219) <> test/dsr-geneve-test-67fb7f94bf-466f7 (ID:8532) pre-xlate-rev TRACED (TCP)
Nov 20 07:22:07.988: 172.19.0.5:38448 (ID:9) <> test/dsr-geneve-test-67fb7f94bf-466f7:8000 (ID:8532) from-overlay FORWARDED (TCP Flags: ACK, PSH)
Nov 20 07:22:07.988: 172.19.0.5:38448 (ID:16777219) -> test/dsr-geneve-test-67fb7f94bf-466f7:8000 (ID:8532) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
Nov 20 07:22:07.995: 172.19.0.5:38448 (ID:9) <> test/dsr-geneve-test-67fb7f94bf-466f7:8000 (ID:8532) from-overlay FORWARDED (TCP Flags: ACK)
Nov 20 07:22:07.995: 172.19.0.5:38448 (ID:16777219) -> test/dsr-geneve-test-67fb7f94bf-466f7:8000 (ID:8532) to-endpoint FORWARDED (TCP Flags: ACK)
Nov 20 07:22:07.995: 172.19.0.5:38448 (ID:9) <> test/dsr-geneve-test-67fb7f94bf-466f7:8000 (ID:8532) from-overlay FORWARDED (TCP Flags: ACK, FIN)
Nov 20 07:22:07.995: 172.19.0.5:38448 (ID:16777219) -> test/dsr-geneve-test-67fb7f94bf-466f7:8000 (ID:8532) to-endpoint FORWARDED (TCP Flags: ACK, FIN)
Nov 20 07:22:07.996: 172.19.0.5:38448 (ID:9) <> test/dsr-geneve-test-67fb7f94bf-466f7:8000 (ID:8532) from-overlay FORWARDED (TCP Flags: ACK)
Nov 20 07:22:07.996: 172.19.0.5:38448 (ID:16777219) -> test/dsr-geneve-test-67fb7f94bf-466f7:8000 (ID:8532) to-endpoint FORWARDED (TCP Flags: ACK)
```

**geneve(ipv6)**
```console
Nov 20 07:34:05.059: [fc00:c111::5]:40822 (ID:10) <> test/dsr-geneve-test-67fb7f94bf-dftzf:8000 (ID:8532) from-overlay FORWARDED (TCP Flags: SYN)
Nov 20 07:34:05.059: [fc00:c111::5]:40822 (ID:16777220) -> test/dsr-geneve-test-67fb7f94bf-dftzf:8000 (ID:8532) policy-verdict:L3-Only INGRESS ALLOWED (TCP Flags: SYN)
Nov 20 07:34:05.059: [fc00:c111::5]:40822 (ID:16777220) -> test/dsr-geneve-test-67fb7f94bf-dftzf:8000 (ID:8532) to-endpoint FORWARDED (TCP Flags: SYN)
Nov 20 07:34:05.060: [fc00:c111::5]:40822 (ID:10) <> test/dsr-geneve-test-67fb7f94bf-dftzf:8000 (ID:8532) from-overlay FORWARDED (TCP Flags: ACK)
Nov 20 07:34:05.060: [fc00:c111::5]:40822 (ID:16777220) -> test/dsr-geneve-test-67fb7f94bf-dftzf:8000 (ID:8532) to-endpoint FORWARDED (TCP Flags: ACK)
Nov 20 07:34:05.060: [fc00:c111::5]:40822 (ID:10) <> test/dsr-geneve-test-67fb7f94bf-dftzf:8000 (ID:8532) from-overlay FORWARDED (TCP Flags: ACK, PSH)
Nov 20 07:34:05.060: [fc00:c111::5]:40822 (ID:16777220) -> test/dsr-geneve-test-67fb7f94bf-dftzf:8000 (ID:8532) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
Nov 20 07:34:05.060: [fc00:c111::5]:40822 (ID:16777220) <> test/dsr-geneve-test-67fb7f94bf-dftzf (ID:8532) pre-xlate-rev TRACED (TCP)
Nov 20 07:34:05.064: [fc00:c111::5]:40822 (ID:10) <> test/dsr-geneve-test-67fb7f94bf-dftzf:8000 (ID:8532) from-overlay FORWARDED (TCP Flags: ACK, FIN)
Nov 20 07:34:05.064: [fc00:c111::5]:40822 (ID:16777220) -> test/dsr-geneve-test-67fb7f94bf-dftzf:8000 (ID:8532) to-endpoint FORWARDED (TCP Flags: ACK, FIN)
Nov 20 07:34:05.064: [fc00:c111::5]:40822 (ID:10) <> test/dsr-geneve-test-67fb7f94bf-dftzf:8000 (ID:8532) from-overlay FORWARDED (TCP Flags: ACK)
Nov 20 07:34:05.064: [fc00:c111::5]:40822 (ID:16777220) -> test/dsr-geneve-test-67fb7f94bf-dftzf:8000 (ID:8532) to-endpoint FORWARDED (TCP Flags: ACK)
Nov 20 07:34:05.066: [fc00:c111::5]:40822 (ID:10) <> test/dsr-geneve-test-67fb7f94bf-dftzf:8000 (ID:8532) from-overlay FORWARDED (TCP Flags: ACK)
Nov 20 07:34:05.066: [fc00:c111::5]:40822 (ID:16777220) -> test/dsr-geneve-test-67fb7f94bf-dftzf:8000 (ID:8532) to-endpoint FORWARDED (TCP Flags: ACK)

```

Comment (chez-shanpu) [reply bpf/bpf_overlay.c:363]: To fix this, we have to set identity here. https://github.com/cilium/cilium/blob/8e4c0a2fe66684bbd8082c4147aaef0f4e73b7a6/bpf/bpf_overlay.c#L616-L618

Comment (julianwiedmann) [reply bpf/bpf_overlay.c:363]: > To fix this, we have to set identity here.
> 
> https://github.com/cilium/cilium/blob/8e4c0a2fe66684bbd8082c4147aaef0f4e73b7a6/bpf/bpf_overlay.c#L616-L618

Ah true. Let's tackle that in a follow-up PR? :)

Comment (julianwiedmann) [reply bpf/bpf_overlay.c:363]: > > Have you double-checked whether we now get the same behaviour as when using "IP opt/ext" DSR?
> 
> I've checked with my k8s, and it almost works well.

I had a closer look at all the special handling in `resolve_srcid_ipv4()`, and think we're good without duplicating it.

Also realized that there is a "workaround" for this bug - enable per-EP routing, and disable BPF Host Routing. Then `to-container` will resolve the identity [on its own](https://github.com/cybozu-go/cilium/blob/d25d328955273c55814729548cb7dc32bce51c14/bpf/bpf_lxc.c#L2111).

**Review by julianwiedmann — APPROVED** [review]
Good from my side, ty!

(please add a release note!)

File: bpf/bpf_overlay.c (hunk 3 above)
Comment (chez-shanpu) [reply bpf/bpf_overlay.c:363]: > Let's tackle that in a follow-up PR? :)

Yes, let's do that :D

**Comment by chez-shanpu** [comment]
@julianwiedmann 

> Good from my side, ty!
> 
> (please add a release note!)

I added a release note to this PR description.
Could you check it?

**Comment by YutaroHayakawa** [comment]
Let me remove myself since there's enough 👀 from the people who are familiar with Geneve DSR.

**Comment by ysksuzuki** [comment]
The changes look good to me, but Conformance E2E is consistently failing. It seems that there's something wrong  with kube-apiserver.

https://github.com/cilium/cilium/actions/runs/6932811318/job/18884158732
```
Error: Unable to install Cilium: Get "https://127.0.0.1:35039/api/v1/namespaces/kube-system/services/hubble-peer": http2: client connection lost
Error: Process completed with exit code 1.
```

**Comment by julianwiedmann** [comment]
> @julianwiedmann
> 
> > Good from my side, ty!
> > (please add a release note!)
> 
> I added a release note to this PR description. Could you check it?

Thank you, looks good! I took the liberty to fine-tune it a tiny bit :).

**Comment by julianwiedmann** [comment]
> The changes look good to me, but Conformance E2E is consistently failing. It seems that there's something wrong with kube-apiserver.
> 
> https://github.com/cilium/cilium/actions/runs/6932811318/job/18884158732
> 
> ```
> Error: Unable to install Cilium: Get "https://127.0.0.1:35039/api/v1/namespaces/kube-system/services/hubble-peer": http2: client connection lost
> Error: Process completed with exit code 1.
> ```

when in doubt, a rebase might help :slightly_smiling_face:

**Review by ysksuzuki — APPROVED** [review]
LGTM. Thanks!

**Comment by ysksuzuki** [comment]
Is this because of this change?

```
cilium install --wait \
      --chart-directory=/home/yusuke/go/src/github.com/cilium/cilium/install/kubernetes/cilium \
      --helm-set=debug.enabled=true \
      --helm-set=debug.verbose=envoy \
      --helm-set=hubble.eventBufferCapacity=65535 \
      --helm-set=bpf.monitorAggregation=none \
      --helm-set=cluster.name=default \
      --helm-set=authentication.mutual.spire.enabled=true \
      --nodes-without-cilium=kind-worker3 \
      --helm-set-string=kubeProxyReplacement=true \
      --helm-set=image.repository=quay.io/cilium/cilium-ci \
      --helm-set=image.useDigest=false \
      --helm-set=image.tag=aaa9319e6362fa402192dee52f4d52bcb129bd0e \
      --helm-set=operator.image.repository=quay.io/cilium/operator \
      --helm-set=operator.image.suffix=-ci \
      --helm-set=operator.image.tag=aaa9319e6362fa402192dee52f4d52bcb129bd0e \
      --helm-set=operator.image.useDigest=false \
      --helm-set=hubble.relay.image.repository=quay.io/cilium/hubble-relay-ci \
      --helm-set=hubble.relay.image.tag=aaa9319e6362fa402192dee52f4d52bcb129bd0e \
      --helm-set=hubble.relay.image.useDigest=false \
      --helm-set-string=routingMode=native \
      --helm-set-string=autoDirectNodeRoutes=true \
      --helm-set-string=ipv4NativeRoutingCIDR=10.244.0.0/16 \
      --helm-set-string=ipv6NativeRoutingCIDR=fd00:10:244::/56 \
      --helm-set=devices='eth0' \
      --helm-set-string=loadBalancer.mode=dsr \
      --helm-set-string=endpointRoutes.enabled=true \
      --helm-set=ipv6.enabled=true \
      --helm-set=bpf.masquerade=true \
      --helm-set=egressGateway.enabled=true \
      --helm-set=encryption.enabled=true \
      --helm-set=encryption.type=wireguard \
      --helm-set=encryption.nodeEncryption=false   
🔮 Auto-detected Kubernetes kind: kind
✨ Running "kind" validation checks
✅ Detected kind version "0.20.0"
ℹ️  Using Cilium version 1.15.0
ℹ️  Using cluster name "default"
ℹ️  Detecting real Kubernetes API server addr and port on Kind
🔮 Auto-detected kube-proxy has not been installed
ℹ️  Cilium will fully replace all functionalities of kube-proxy

Error: Unable to install Cilium: Get "https://127.0.0.1:40123/api/v1/namespaces/kube-system/services/hubble-peer": http2: client connection lost

```

**Comment by ysksuzuki** [comment]
The problem happens with `--helm-set-string=loadBalancer.mode=dsr`. So it might be because of this change.

**Comment by ysksuzuki** [comment]
@chez-shanpu @terassyi Can you check `http2: client connection lost` error? It seems that the spire server can't start up when dsr is enabled.

**Comment by ysksuzuki** [comment]
The spire-agents are running eventually, but it takes longer than before when dsr is enabled.

```
k8s:kind-kind> kubectl -n cilium-spire logs spire-agent-w6l5c  -c init
Waiting for spire server to be reachable to start
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
Waiting for spire server to be reachable
SPIRE server is reachable

```

**Comment by chez-shanpu** [comment]
@ysksuzuki I still don't figure out why it failed, but after I rebased it to current main, `cilium install` succeeds in my k8s.
Could you trigger e2e? It might pass.

**Comment by ysksuzuki** [comment]
@chez-shanpu Still failing. https://github.com/cilium/cilium/actions/runs/7001542266/job/19043788477

**Comment by chez-shanpu** [comment]
@ysksuzuki Thank you. I'll check it 👀

**Comment by chez-shanpu** [comment]
It seems that the connection to the k8s api-server is lost when `authentication.mutual.spire.enabled` is true.

**Comment by ysksuzuki** [comment]
This Conformance Ginkgo failure is also relevant?
https://github.com/cilium/cilium/actions/runs/7001542415/job/19044349776

```
    2023-11-27T07:25:18.645895266Z level=error msg=k8sError error="github.com/cilium/cilium/pkg/k8s/resource/resource.go:725: Failed to watch *v1.Node: failed to list *v1.Node: Get \"https://172.18.0.2:6443/api/v1/nodes?fieldSelector=metadata.name%3Dkind-worker&resourceVersion=2762\": http2: client connection lost" subsys=k8s
    2023-11-27T07:25:18.646114114Z level=error msg=k8sError error="github.com/cilium/cilium/pkg/k8s/resource/resource.go:725: Failed to watch *v2.CiliumNode: failed to list *v2.CiliumNode: Get \"https://172.18.0.2:6443/apis/cilium.io/v2/ciliumnodes?fieldSelector=metadata.name%3Dkind-worker&resourceVersion=2731\": http2: client connection lost" subsys=k8s
    2023-11-27T07:25:18.646137357Z level=error msg=k8sError error="github.com/cilium/cilium/pkg/k8s/resource/resource.go:725: Failed to watch *v2.CiliumNetworkPolicy: failed to list *v2.CiliumNetworkPolicy: Get \"https://172.18.0.2:6443/apis/cilium.io/v2/ciliumnetworkpolicies?resourceVersion=2726\": http2: client connection lost" subsys=k8s
    2023-11-27T07:25:18.645379138Z level=error msg=k8sError error="github.com/cilium/cilium/pkg/k8s/resource/resource.go:725: Failed to watch *v2alpha1.CiliumCIDRGroup: failed to list *v2alpha1.CiliumCIDRGroup: Get \"https://172.18.0.2:6443/apis/cilium.io/v2alpha1/ciliumcidrgroups?resourceVersion=2720\": http2: client connection lost" subsys=k8s
```

**Review by ysksuzuki — CHANGES_REQUESTED** [review]
`dsr` should be `*dsr` here. I guess it causes an unexpected error and the packet drop (Invalid packet) 

https://github.com/cilium/cilium/pull/29155/files#diff-304969c111195cf4253b336fc67c9891f17b91d49738a0cc334333ac11e84b9eR1365

https://github.com/cilium/cilium/pull/29155/files#diff-304969c111195cf4253b336fc67c9891f17b91d49738a0cc334333ac11e84b9eR2852


On CP node, cilium monitor shows drop logs.

```
xx drop (Invalid packet) flow 0x3bc1dc4f to endpoint 0, ifindex 1430, file bpf_host.c:837, , identity remote-node->unknown: 192.168.16.3:41918 -> 192.168.16.5:6443 tcp ACK
xx drop (Invalid packet) flow 0x36882803 to endpoint 0, ifindex 1430, file bpf_host.c:837, , identity remote-node->unknown: 192.168.16.4:50738 -> 192.168.16.5:6443 tcp ACK
```

**Review by ysksuzuki — APPROVED** [review]
All tests are green

**Comment by julianwiedmann** [comment]
FYI - I just stumbled over https://github.com/cilium/cilium/blob/fa0037638534635471c8e45583d78f87ad78b3e1/bpf/lib/nodeport.h#L2315. That's probably just copy & pasted (I wouldn't know who uses it), but we are obviously not putting the right data there at the moment.

For the TC program it would be easy to fix (we already resolved the src-sec-identity). XDP and DSR-Geneve would need a bit more work. But maybe it's easiest to just remove that code :grin: .

**Comment by chez-shanpu** [comment]
@julianwiedmann 
> But maybe it's easiest to just remove that code 😁 .

Is it because the `src_sec_id` in CT  is not used?
