### PR TITLE
bpf: Fix broken remote-node identity classification

### LINKED ISSUE #18042: eBPF host routing breaks remote-node identity classification
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm running cilium on k3s with metallb. I have setup cilium with loadBalancer.mode=hybrid. I have UDP service and corresponding network policy to allow its traffic:
```
- apiVersion: v1         
  kind: Service
  metadata:
    labels:     
      app: oregon            
    annotations:
      metallb.universe.tf/allow-shared-ip: 'true'
    name: oregon  
    namespace: hass
  spec:                      
    ports:                                                                                                                                                                                     
    - name: oregon-udp
      port: 4360
      protocol: UDP
      targetPort: 4360
    selector:
      app: oregon
    loadBalancerIP: 172.17.2.230
    type: LoadBalancer
- apiVersion: cilium.io/v2
  kind: CiliumNetworkPolicy
  metadata:
    name: oregon-udp
    namespace: hass
  spec:
    endpointSelector:
      matchLabels:
        app: oregon
    ingress:
    - fromEntities:
      - remote-node
      toPorts:
        - ports:
            - port: '4360'
              protocol: UDP
    - fromCIDRSet:
        - cidr: 172.17.2.70/32
        - cidr: 172.17.2.71/32
      toPorts:
        - ports:
            - port: '4360'
              protocol: UDP
```
But packets gets dropped when loadbalanced to another node:
```
$ kubectl -n kube-system exec -ti cilium-f285n -- cilium monitor | grep 4360
Policy verdict log: flow 0x0 local EP ID 3521, remote ID world, proto 17, ingress, action deny, match none, 172.17.5.1:42644 -> 172.17.194.61:4360 udp
xx drop (Policy denied) flow 0x0 to endpoint 3521, identity world->17290: 172.17.5.1:42644 -> 172.17.194.61:4360 udp
```
```
$ kubectl get ciliumendpoints -A | grep oregon
hass             oregon-788c446575-2h5k6                        3521          17290                                                                        ready            172.17.194.61
```

For some reason `172.17.5.1/32` gets classified as `world`, but should be classified as `remote-node` (6):
```
$ kubectl -n kube-system exec -ti cilium-f285n -- cilium bpf ipcache list | grep ' 6 '
172.17.2.92/32      6 0 0.0.0.0
172.17.193.2/32     6 0 172.17.5.2
172.17.192.172/32   6 0 172.17.5.1
172.17.2.91/32      6 0 0.0.0.0
172.17.5.2/32       6 0 0.0.0.0
172.17.5.1/32       6 0 0.0.0.0
```

Cilium installed from chart with folowing configuration:
```
--set tunnel=disabled
--set autoDirectNodeRoutes=true
--set kubeProxyReplacement=strict
--set loadBalancer.mode=hybrid
--set k8sServiceHost=172.17.5.100
--set k8sServicePort=6443
--set hubble.enabled=false
--set ipam.operator.clusterPoolIPv4PodCIDR=172.17.192.0/18
--set nativeRoutingCIDR=172.17.192.0/18
```

### Cilium Version

1.10.5

### Kernel Version

5.11.0-16-generic

### Kubernetes Version

K3S

Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s2", GitCommit:"724ef700bab896ff252a75e2be996d5f4ff1b842", GitTreeState:"clean", BuildDate:"2021-10-05T19:59:14Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ysksuzuki**
When Cilium resolves a src ID from ipcache with a remote node IP, the resolved ID is ignored and returns the world ID. This is because the resolve_srcid_ipv[4,6] function checks if the resolved src ID is a reserved ID, which includes the remote node ID, and if it's true, then returns the world ID. This PR fixes this problem by removing !identity_is_reserved check.

This issue occurs if BPF host routing is in use because Cilium stores the src ID resolved by resolve_srcid_ipv[4,6] in ipv[4,6]_local_delivery and enforces the policy using the stored src id. 
https://github.com/cilium/cilium/blob/2c9c8c17aeebcd2e295ecd29fd99305000bc7790/bpf/lib/l3.h#L137

On the other hand, Cilium uses the src ID resolved in bpx_lxc tail_ipv4_to_endpoint if the legacy routing mode is enabled. There's no corresponding !identity_is_reserved check in bpf_lxc side. Therefore it works with the legacy routing mode.
https://github.com/cilium/cilium/blob/b3747c8a1bf0a0ee750385f23cc382bd92f0653c/bpf/bpf_lxc.c#L1942

According to #4874 #6703, this check was added when those introduced the fallback to use the ipcache data if the packet info does not contain any useful information. As far as I look it into those PR, there's no solid reason to keep the !identity_is_reserved check, because resolve_srcid_ipv[4,6] works as follows without the check which is the same as bpx_lxc tail_ipv4_to_endpoint side.

1. the packet info, ctx->mark, cotaints the identity, then return it (from host)
2. the packet info does not contain any useful information, then resolved from ipcache and return it (from netdev)
3. the identity is not resolved from both the packet info and ipcache then return the world ID

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

Fixes: #18042

### CODE REVIEW

**Comment by ysksuzuki** [comment]
@NikAleksandrov Would you be able to take a look at this PR? I would appreciate your input.

**Comment by NikAleksandrov** [comment]
> @NikAleksandrov Would you be able to take a look at this PR? I would appreciate your input.

I did, the change looks good to me and makes sense. I like the nice description!
I was waiting for all tests to pass.

**Review by NikAleksandrov — APPROVED** [review]
thanks again for the nice explanation, the change looks good to me

**Comment by ysksuzuki** [comment]
I think I need to rebase this branch as well.
https://github.com/cilium/cilium/pull/23210#issuecomment-1403612629

**Review by pchaigno — APPROVED** [review]
Thanks for the great commit description and for digging all the relevant information! :bow: 

I read the related PRs and have the same read as you, so I'd also assume this change to be safe (in addition to fixing the BPF Host Routing fix).

**Comment by ysksuzuki** [comment]
conformance-test-ipv6 failed
https://github.com/cilium/cilium/actions/runs/4011394707

The last two runs passed, but the third one is failing
https://github.com/cilium/cilium/actions/runs/3996135963
https://github.com/cilium/cilium/actions/runs/3912859135

**Comment by joestringer** [comment]
Heads up that this is a risky change - Any time you change the identity for some traffic, there's potential that someone has written a network policy to support the current behaviour, so when we change it, their policy breaks.

File: bpf/bpf_host.c [hunk 1]
```diff
@@ -448,8 +447,7 @@ resolve_srcid_ipv4(struct __ctx_buff *ctx, __u32 srcid_from_proxy,
 	/* If we could not derive the secctx from the packet itself but
 	 * from the ipcache instead, then use the ipcache identity.
 	 */
-	else if (identity_from_ipcache_ok() &&
-		 !identity_is_reserved(srcid_from_ipcache))
+	else if (identity_from_ipcache_ok())
 		src_id = srcid_from_ipcache;
```
Comment (joestringer) [inline bpf/bpf_host.c:451]: @cilium/sig-datapath the IPv4 vs. IPv6 cases here are divergent, seems like one checks for `WORLD_ID` and the other doesnt?

File: bpf/bpf_host.c [hunk 2]
```diff
@@ -170,8 +170,7 @@ resolve_srcid_ipv6(struct __ctx_buff *ctx, __u32 srcid_from_proxy,
 	if (from_host)
 		src_id = srcid_from_ipcache;
 	else if (src_id == WORLD_ID &&
-		 identity_from_ipcache_ok() &&
-		 !identity_is_reserved(srcid_from_ipcache))
+		 identity_from_ipcache_ok())
```
Comment (joestringer) [inline bpf/bpf_host.c:173]: Is it possible for NodePort traffic to hit this condition? If yes, and if the source is masqueraded, then the IP will look like a host IP, regardless of whether the traffic came from the host. That would be a security hole. I think that's the real reason why there's a reserved check here.

Comment (joestringer) [reply bpf/bpf_host.c:173]: cc @pchaigno , hopefully the above query is just noise but I would like to make sure given the implications of the change.

**Comment by joestringer** [comment]
I'll add `backport/author` just to hold up the automated backport of this for now while we resolve the above question. Once it's resolved, we can remove the label to backport this automatically to affected branches.

File: bpf/bpf_host.c (hunk 2 above)
Comment (pchaigno) [reply bpf/bpf_host.c:173]: Hm, I hesitated on blocking this on your review. Maybe I should have :smile: 

> Is it possible for NodePort traffic to hit this condition?

I had the same concern. My understanding however is that this is for traffic hitting tc-ingress of the native devices. So kube-proxy didn't have a chance to interfere yet. And KPR didn't run yet when we execute this bit of code (that happens after in `CILIUM_CALL_IPV{4,6}_FROM_NETDEV`).

File: bpf/bpf_host.c (hunk 1 above)
Comment (pchaigno) [reply bpf/bpf_host.c:451]: Yes, we have a special case for IPv6. See `derive_src_id`. The difference is:
- IPv4: No need to check the value of `src_id`. It was initialized with `WORLD_ID` and not modified before hitting this condition.
- IPv6: The `src_id` value may have been changed by `derive_src_id`.

File: bpf/bpf_host.c (hunk 2 above)
Comment (christarazi) [reply bpf/bpf_host.c:173]: > Is it possible for NodePort traffic to hit this condition? If yes, and if the source is masqueraded, then the IP will look like a host IP, regardless of whether the traffic came from the host. That would be a security hole. I think that's the real reason why there's a reserved check here.

On a related note, do we have a CI test which asserts future changes don't expose ourselves to this security hole?

Comment (joestringer) [reply bpf/bpf_host.c:173]: bpf_host is also attached to `cilium_host`:

```
# bpftool net
xdp:

tc:
cilium_net(2) clsact/ingress bpf_host_cilium_net.o:[to-host] id 1670
cilium_host(3) clsact/ingress bpf_host.o:[to-host] id 1656
cilium_host(3) clsact/egress bpf_host.o:[from-host] id 1663
...
```

Isn't it possible for a packet to arrive at some native device, Cilium passes it up the stack towards kube-proxy for nodeport handling, then after DNAT+SNAT the packet is routed towards `cilium_host` (endpoint-routes=false) -- then won't this code run?

Comment (joestringer) [reply bpf/bpf_host.c:173]: @christarazi good question... I think the tricky part here is that we would be configuring a nodeport, sending traffic from outside the node towards that nodeport, applying a security policy that drops the traffic, then the test would validate that the traffic is in fact dropped.

Comment (christarazi) [reply bpf/bpf_host.c:173]: At least in the Jenkins suite, we have the test where a 3rd node without Cilium exists that can be used to simulate this scenario. If we don't want Jenkins / Vagrant tests anymore, then it seems plausible that we could have a GH Actions job with a kind cluster and initiate these nodeport requests from outside of the cluster.

Or am I missing something obvious?

Comment (pchaigno) [reply bpf/bpf_host.c:173]: > bpf_host is also attached to `cilium_host`:

The above code is for the `!from_host` case.

> I think the tricky part here is that we would be configuring a nodeport, sending traffic from outside the node towards that nodeport, applying a security policy that drops the traffic, then the test would validate that the traffic is in fact dropped.

I think we already have at least one test covering that. See the `with L7 policy` test in the NodePort tests of services.go. That one is currently flaky but you get the idea. And it might not be the only NodePort test with policy enforcement.

Comment (pchaigno) [reply bpf/bpf_host.c:173]: > bpf_host is also attached to `cilium_host`:

The above code is for the `!from_host` case.

> I think the tricky part here is that we would be configuring a nodeport, sending traffic from outside the node towards that nodeport, applying a security policy that drops the traffic, then the test would validate that the traffic is in fact dropped.

I think we already have at least one test covering that. See the `with L7 policy` test in the NodePort tests of services.go. That one is currently flaky but you get the idea. And it might not be the only NodePort test with policy enforcement.

Comment (aditighag) [reply bpf/bpf_host.c:173]: >Isn't it possible for a packet to arrive at some native device, Cilium passes it up the stack towards kube-proxy for nodeport handling, then after DNAT+SNAT the packet is routed towards cilium_host (endpoint-routes=false) -- then won't this code run?

Hmm, it could... 🤔  We store the original source identity in ctx (see `nodeport_lb6`) when nodeport (kpr) is enabled. If we saved the identity unconditionally, it could help the cilium_host case. Although I'm not sure if the scratch pad is reset when packets are passed through stack, so we'll probably lose access to the encoded identity information. We only store identities in packet mark for local pods at the moment.

Comment (joestringer) [reply bpf/bpf_host.c:173]: > > bpf_host is also attached to cilium_host:
> 
> The above code is for the !from_host case.

:ok_hand: Awesome, then any time that iptables is involved then traffic is routed to cilium_host, it will not hit this line. Great.

One more case: XDP -> TC on receive into the node. I presume that we reliably either don't SNAT or we hand identity context between XDP->TC for native device?

Comment (joestringer) [reply bpf/bpf_host.c:173]: > Although I'm not sure if the scratch pad is reset when packets are passed through stack, so we'll probably lose access to the encoded identity information. 

Yeah this is a common difficulty while routing traffic through the stack. We may have more control over this in the "bpf host routing" case.

Comment (pchaigno) [reply bpf/bpf_host.c:173]: > One more case: XDP -> TC on receive into the node. I presume that we reliably either don't SNAT or we hand identity context between XDP->TC for native device?

That's reaching outside of my knowledge. You'd have to find someone familiar with that or dig the answer yourself.

Comment (joestringer) [reply bpf/bpf_host.c:173]: cc @borkmann / @cilium/sig-datapath  would you happen to know about the above question or be able to point towards someone with that context? I _think_ the first statement is true, not so sure about the second statement.
1. There is no path where Cilium XDP applies SNAT then forwards the packet up the stack, and
1. If forwarding up the stack, we ensure that XDP passes the source identity up the stack

If these both hold then I think we're good to proceed with this PR.

**Comment by ysksuzuki** [comment]
@joestringer Thank you for your comment!

> Heads up that this is a risky change - Any time you change the identity for some traffic, there's potential that someone has written a network policy to support the current behaviour, so when we change it, their policy breaks.

Yes, you are right.  This PR changes the identity for traffic from outside to LB with snat mode as follows. If users have written a networkpolicy that relies on this behavior, it breaks. This break change should be well documented if we proceed.

```
# Before
Jan 27 03:09:51.048: 10.69.1.132:44930 (world) -> dctest/suzuki-test-d7f66dc7d-rtnwj:8000 (ID:11696) to-endpoint FORWARDED (TCP Flags: SYN)
Jan 27 03:09:51.048: 10.69.1.132:44930 (kube-apiserver) <- dctest/suzuki-test-d7f66dc7d-rtnwj:8000 (ID:11696) to-network FORWARDED (TCP Flags: SYN, ACK)
Jan 27 03:09:51.049: 10.69.1.132:44930 (world) -> dctest/suzuki-test-d7f66dc7d-rtnwj:8000 (ID:11696) to-endpoint FORWARDED (TCP Flags: ACK)
Jan 27 03:09:51.049: 10.69.1.132:44930 (world) -> dctest/suzuki-test-d7f66dc7d-rtnwj:8000 (ID:11696) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
Jan 27 03:09:51.049: 10.69.1.132:44930 (kube-apiserver) <- dctest/suzuki-test-d7f66dc7d-rtnwj:8000 (ID:11696) to-network FORWARDED (TCP Flags: ACK, PSH)
Jan 27 03:09:51.049: 10.69.1.132:44930 (world) -> dctest/suzuki-test-d7f66dc7d-rtnwj:8000 (ID:11696) to-endpoint FORWARDED (TCP Flags: ACK, FIN)
Jan 27 03:09:51.049: 10.69.1.132:44930 (kube-apiserver) <- dctest/suzuki-test-d7f66dc7d-rtnwj:8000 (ID:11696) to-network FORWARDED (TCP Flags: ACK, FIN)
Jan 27 03:09:51.050: 10.69.1.132:44930 (world) -> dctest/suzuki-test-d7f66dc7d-rtnwj:8000 (ID:11696) to-endpoint FORWARDED (TCP Flags: ACK)

# After
Jan 27 03:08:51.392: 10.69.1.132:58564 (kube-apiserver) -> dctest/suzuki-test-d7f66dc7d-rtnwj:8000 (ID:11696) to-endpoint FORWARDED (TCP Flags: SYN)
Jan 27 03:08:51.392: 10.69.1.132:58564 (kube-apiserver) <- dctest/suzuki-test-d7f66dc7d-rtnwj:8000 (ID:11696) to-stack FORWARDED (TCP Flags: SYN, ACK)
Jan 27 03:08:51.393: 10.69.1.132:58564 (kube-apiserver) -> dctest/suzuki-test-d7f66dc7d-rtnwj:8000 (ID:11696) to-endpoint FORWARDED (TCP Flags: ACK)
Jan 27 03:08:51.393: 10.69.1.132:58564 (kube-apiserver) -> dctest/suzuki-test-d7f66dc7d-rtnwj:8000 (ID:11696) to-endpoint FORWARDED (TCP Flags: ACK, PSH)
Jan 27 03:08:51.394: 10.69.1.132:58564 (kube-apiserver) <- dctest/suzuki-test-d7f66dc7d-rtnwj:8000 (ID:11696) to-stack FORWARDED (TCP Flags: ACK, PSH)
Jan 27 03:08:51.394: 10.69.1.132:58564 (kube-apiserver) -> dctest/suzuki-test-d7f66dc7d-rtnwj:8000 (ID:11696) to-endpoint FORWARDED (TCP Flags: ACK, FIN)
Jan 27 03:08:51.394: 10.69.1.132:58564 (kube-apiserver) <- dctest/suzuki-test-d7f66dc7d-rtnwj:8000 (ID:11696) to-stack FORWARDED (TCP Flags: ACK, FIN)
Jan 27 03:08:51.394: 10.69.1.132:58564 (kube-apiserver) -> dctest/suzuki-test-d7f66dc7d-rtnwj:8000 (ID:11696) to-endpoint FORWARDED (TCP Flags: ACK)
```

File: bpf/bpf_host.c (hunk 2 above)
Comment (ysksuzuki) [reply bpf/bpf_host.c:173]: I'm digging the code and couldn't find a path where Cilium XDP applies SNAT then forwards the packet up the stack. But we should wait for the datapath team's comment.


In XDP Cilium calls nodeport_lb[4,6]

1. Lookup service and select a backend for the svc and do DNAT. https://github.com/cilium/cilium/blob/9f35b129dfb746f2f4a12d614cfefe99088acb2b/bpf/lib/nodeport.h#L892
2. If the backend is local, writes XFER_PKT_NO_SVC and return CTX_ACT_OK. https://github.com/cilium/cilium/blob/9f35b129dfb746f2f4a12d614cfefe99088acb2b/bpf/lib/nodeport.h#L962
   - If the backend is remote, then SNAT and redirect.(lb_mode = snat) Not move up to stack in this case. https://github.com/cilium/cilium/blob/9f35b129dfb746f2f4a12d614cfefe99088acb2b/bpf/lib/nodeport.h#L995
3. Move xfer to data_meta and up to stack
4. In TC, get xfer and set nodeport skip flag. https://github.com/cilium/cilium/blob/0670fd2ace1136a1143a384b39912f8153d7a063/bpf/bpf_host.c#L1056
5. Call resolve_srcid_ipv[4,6] and resolve an identity from ipcache. The source IP is a client IP at this point.

There's a special loopback case in which the origin endpoint has sent to a service which is being translated back to the source, and the source IP will be IPV4_LOOPBACK.
https://github.com/cilium/cilium/blob/ff05a619168d7c4b25cc135e612da1f740691e8c/bpf/lib/lb.h#L1705

But this case is nothing to do with N/S traffic. It's not the case.
https://github.com/cilium/cilium/blob/29479334c197748fa1ad1bcb990a8d1e8a7933c3/bpf/bpf_lxc.c#L1748

Comment (ysksuzuki) [reply bpf/bpf_host.c:173]: In XDP to TC punt case, Cilium does SNAT in XDP and moves up the stack, but it encaps and redirects in cil_from_netdev. So it doesn't call resolve_srcid_ipv[4,6]

https://github.com/cilium/cilium/blob/9f35b129dfb746f2f4a12d614cfefe99088acb2b/bpf/lib/nodeport.h#L827
https://github.com/cilium/cilium/blob/0670fd2ace1136a1143a384b39912f8153d7a063/bpf/bpf_host.c#L1065

Comment (pchaigno) [reply bpf/bpf_host.c:173]: > If these both hold then I think we're good to proceed with this PR.

If the first is true then why does the second matter? If the packet wasn't SNATed when it reaches the tc hook, then we can trust the ipcache anyway.

**Comment by m-yosefpor** [comment]
Will this fix be available in v1.13?

File: bpf/bpf_host.c (hunk 2 above)
Comment (ysksuzuki) [reply bpf/bpf_host.c:173]: @joestringer As far as I looked into the datapath code and tested it, Cilium doesn't apply SNAT for the inbound packets to local backends. So we can trust the ipcache here because the source is a client IP. What do you think?

**Comment by pchaigno** [comment]
Unblocking backports given the conclusion that was reached in the above discussion. I've however removed from v1.12 backports given v1.13.0 was now released.

File: bpf/bpf_host.c (hunk 2 above)
Comment (joestringer) [reply bpf/bpf_host.c:173]: > If the first is true then why does the second matter? If the packet wasn't SNATed when it reaches the tc hook, then we can trust the ipcache anyway.

Broadly my concern is when XDP "passes up the stack" and then some iptables rule munges the packets before the packet is delivered to TC-BPF for pod ingress processing, then we can incorrectly diagnose that the source identity is "host" and bypass all policy.

Comment (ysksuzuki) [reply bpf/bpf_host.c:173]: > when XDP "passes up the stack" and then some iptables rule munges the packets before the packet is delivered to TC-BPF for pod ingress processing

Is there any chance that iptables mangles the packets between XDP and TC? Did I miss something?

BTW, HOST_ID resolved from the ipcache is ignored for IPV4 case, but no corresponding check for IPv6. Is there any reason for that? We can assure avoiding the case that Cilium wrongly identifies as the host if we can add this check for IPv6.
https://github.com/cilium/cilium/blob/8ea979cfab6ac1005efc591a1f0378333bba6848/bpf/bpf_host.c#L408-L419

Comment (pchaigno) [reply bpf/bpf_host.c:173]: > > when XDP "passes up the stack" and then some iptables rule munges the packets before the packet is delivered to TC-BPF for pod ingress processing
> 
> Is there any chance that iptables mangles the packets between XDP and TC? Did I miss something?

If we're speaking about XDP and tc on the same device, then no, there are no netfilter hooks between XDP and tc-bpf ingress.

Comment (joestringer) [reply bpf/bpf_host.c:173]: I see, now we might bifurcate a bit..

One case I had in mind is with XDP at the native device and TC-BPF ingress at the veth device, which could be the case with endpoint-routes mode.

The latter case I'm not sure about would be endpoint-routes disabled, do we do TC-BPF on the native device for that case these days? Previously or perhaps on earlier kernels I was under the impression that would occur on another device post-routing, maybe cilium_host device.

**Comment by joestringer** [comment]
@sayboras I'm not sure we should be backporting this until we've resolved https://github.com/cilium/cilium/pull/23091#pullrequestreview-1271469166.

File: bpf/bpf_host.c (hunk 2 above)
Comment (joestringer) [reply bpf/bpf_host.c:173]: > BTW, HOST_ID resolved from the ipcache is ignored for IPV4 case, but no corresponding check for IPv6. Is there any reason for that? 

I think this is the same question as I asked in this thread?

https://github.com/cilium/cilium/pull/23091#discussion_r1088128446

**Comment by joestringer** [comment]
Just adding the backport/author label to remove it from automatic backports by the backporter tooling until we've resolved the conversations above. Once those are resolved, we can remove the label again.

**Comment by sayboras** [comment]
> Just adding the backport/author label to remove it from automatic backports by the backporter tooling until we've resolved the conversations above. Once those are resolved, we can remove the label again.

Thanks, I relied on start-backport script to create backport, and didn't check each PR again.

File: bpf/bpf_host.c (hunk 2 above)
Comment (ysksuzuki) [reply bpf/bpf_host.c:173]: > One case I had in mind is with XDP at the native device and TC-BPF ingress at the veth device, which could be the case with endpoint-routes mode.

The identity resolution will be handled on the bpf_lxc side in this case, and the HOST_ID resolved from ipcache will be ignored here. (Assuming that the endpoint route is handled by kernel stack and call TC-BPF ingress at the veth)

https://github.com/cilium/cilium/blob/master/bpf/bpf_lxc.c#L1581-L1592
https://github.com/cilium/cilium/blob/master/bpf/bpf_lxc.c#L1926-L1937

> The latter case I'm not sure about would be endpoint-routes disabled, do we do TC-BPF on the native device for that case these days? Previously or perhaps on earlier kernels I was under the impression that would occur on another device post-routing, maybe cilium_host device.

I assume that this case is under BPF HOST routing=false and Endpoint routing=false. This patch doesn't touch from_host path as Paul mentioned https://github.com/cilium/cilium/pull/23091/files#discussion_r1088422353

TC BPF ingress on netdev
 -> resolve_srcid_ipv[4,6](ctx, identity, from_host=false)
 -> pass to stack
 -> TC BPF ingress on cilium_host
 -> resolve_srcid_ipv[4,6](ctx, identity, from_host=true)
 -> ipv[4, 6]_local_delivery
 -> tail_call_dynamic
 -> redirect_peer
 -> Pod ns

Comment (ysksuzuki) [reply bpf/bpf_host.c:173]: Why don't we add the HOST_ID check to `resolve_srcid_ipv6` as well?

```
			if (*sec_label) {
				/* When SNAT is enabled on traffic ingressing
				 * into Cilium, all traffic from the world will
				 * have a source IP of the host. It will only
				 * actually be from the host if "srcid_from_proxy"
				 * (passed into this function) reports the src as
				 * the host. So we can ignore the ipcache if it
				 * reports the source as HOST_ID.
				 */
				if (*sec_label != HOST_ID)
					srcid_from_ipcache = *sec_label;
			}
```

Comment (borkmann) [reply bpf/bpf_host.c:173]: > The latter case I'm not sure about would be endpoint-routes disabled, do we do TC-BPF on the native device for that case these days? Previously or perhaps on earlier kernels I was under the impression that would occur on another device post-routing, maybe cilium_host device.

With endpoint-routes disabled, we attach tc BPF (bpf_host) to the native device.

Comment (joestringer) [reply bpf/bpf_host.c:173]: > The identity resolution will be handled on the bpf_lxc side in this case, and the HOST_ID resolved from ipcache will be ignored here.

:+1: makes sense, thanks for checking!

> With endpoint-routes disabled, we attach tc BPF (bpf_host) to the native device.

:+1: Right yep and there's no iptables hook between. That resolves my concerns.

Comment (joestringer) [reply bpf/bpf_host.c:173]: > Why don't we add the HOST_ID check to resolve_srcid_ipv6 as well? 

I think we should add that for the IPv6 case too.

Comment (joestringer) [reply bpf/bpf_host.c:173]: Revisiting one more time, Cilium v1.12.7, running inside the Cilium container:

```
# bpftool net
xdp:

tc:
cilium_net(2) clsact/ingress bpf_host_cilium_net.o:[to-host] id 11473
cilium_host(3) clsact/ingress bpf_host.o:[to-host] id 11457
cilium_host(3) clsact/egress bpf_host.o:[from-host] id 11465
cilium_vxlan(4) clsact/ingress bpf_overlay.o:[from-overlay] id 11442
cilium_vxlan(4) clsact/egress bpf_overlay.o:[to-overlay] id 11449
lxc76d5c04bf2ff(8) clsact/ingress bpf_lxc.o:[from-container] id 11541
lxc0443326c1546(10) clsact/ingress bpf_lxc.o:[from-container] id 11552
lxcd6a0dcb63216(12) clsact/ingress bpf_lxc.o:[from-container] id 11532
lxc2d9f8e8642ce(14) clsact/ingress bpf_lxc.o:[from-container] id 11535
lxc21b81bb5a3ab(16) clsact/ingress bpf_lxc.o:[from-container] id 11547
lxcd4cb3575c022(18) clsact/ingress bpf_lxc.o:[from-container] id 11546
lxcd398a5dcaa1d(22) clsact/ingress bpf_lxc.o:[from-container] id 11558
lxc4e2dc37164c3(26) clsact/ingress bpf_lxc.o:[from-container] id 11538
lxc_health(28) clsact/ingress bpf_lxc.o:[from-container] id 11587

flow_dissector:

```

So we see that the `cilium_host` device has the `bpf_host.o` program attached, both for `to-host` and `from-host`. I guess here we're more concerned about `from-host`. Tracing through the from-host section to `handle_netdev()` -> `do_netdev()` .... we may end up `inherit_identity_from_host()`, but then subsequently we follow through to `resolve_srcid_ipv4()` or `resolve_srcid_ipv6()`. So then yeah we need to make absolutely sure that if any traffic hit the stack and did SNAT to a host IP then was directed towards that device, we don't treat such traffic as "from the host".

I was under the impression that we avoided this with the `identity_is_reserved()` check that is changed in this PR, but that's not the case. Only in the IPv4 case we avoid this with the `if (*sec_label != HOST_ID)` check that @ysksuzuki highlighted above. So we've had the bug in the IPv6 path all along for a while.

This also means that this PR is innocent in this regard, it's not impacting this constraint. But yeah we need to follow up on the IPv6 side.

**Comment by joestringer** [comment]
We've resolved the concern I had with respect to this PR, it can be backported now. Sorry it took me this long to dig through and confirm :bow:

**Comment by thorn3r** [comment]
do we still want this to be backported into v1.12? I see the label was added and removed a couple times. Just checking before I remove it from the v1.12.11 project

**Comment by joestringer** [comment]
I think the 1.12 label was only proposed early on, but due to some bug in the project automation it gets carried forward. It should be safe to remove from the 1.12 projects now.
