### PR TITLE
node/manager: synthesize node deletion events

### LINKED ISSUE #29822: Cilium should reconcile missed node delete events
Cilium can miss `NodeDelete` events from Kubernetes, e.g when nodes get deleted during an upgrade while the cilium agent is down. This leads to leaking of resources (e.g. xfrm states/policies, node IDs) if a subsystem in cilium that subscribes to node events doesn't implement reconciliation/garbage collection. https://github.com/cilium/cilium/issues/26298#issuecomment-1832023965 offers a handful of steps to reproduce the bug.

Some subsystems already implement garbage collection to a certain degree for themselves, e.g. the [wireguard agent](https://github.com/cilium/cilium/blob/6ae935476e296986bd9e8ed7d3335748a3f3f727/pkg/wireguard/agent/agent.go#L293), however any feature depending on the `linuxNodeHandler` for cleanup suffers from the described issue.

This issue should track the design and development of a reconciler that ensures that the cilium agent knows about the same set of nodes that are currently in the Kubernetes cluster, triggering the cleanup of node-specific resources and unifying garbage collection functionality across all subsystems that subscribe to the `NodeManager`. 

An implementation approach could be based on the [Generic Reconciler](https://github.com/cilium/cilium/pull/29698) that was merged into the cilium code base for 1.16

### PR DESCRIPTION
**Pull request by bimmlerd**
When the cilium agent is down (due to a crash or an upgrade), it can miss node events. Upon startup, live nodes are upserted, but when deletions are missed, the agent fails to clean up node-related system state. Examples of such state includes bpf map entries, xfrm states or routes. In particular, the agent fails to clean up node IP to nodeID mappings in the nodeid bpf map. Since K8s will happily recycle such IPs, this can lead to breakage, as the agent associate the wrong nodeID with IPs.

To avoid leaking this state, the node manager now dumps its view of the current set of nodes to a file in the runtime state directory, which can be read on restart of an agent. This is similar to how we restore other state upon restart.

When reading this file, it's important to avoid resurrecting long-gone nodes (as we don't know for how long the agent was down) - instead, we merely take note of which nodes we knew of in the past, compare that to the nodes we consider live (once synced to k8s), and delete the ones which seem to have disappeared.

The motivation to build this reconciliation based on full state dumps to disk is that downstream code generally assumes to have access to a full node object in the deletion callbacks. This makes is infeasible to base the pruning on just the information available in bpf maps. In an alternative design, downstream subsystems are responsible for cleaning up their own state based on just a node identifier, but current code doesn't allow for this.

Fixes: #29822

```release-note
The cilium agent now cleans up stale nodeID mappings and other node-related state on startup
```

### CODE REVIEW

File: pkg/node/manager/manager.go [hunk 1]
```diff
@@ -296,6 +332,10 @@ func (m *manager) Stop(cell.HookContext) error {
 		}
 	}
 
+	if m.nodeCheckpointer != nil {
+		m.nodeCheckpointer.Shutdown()
```
Comment (gandro) [inline pkg/node/manager/manager.go:341]: Shutting down a trigger doesn't wait for the shutdown function to complete. We probably want to wait on a channel here to block the Stop hook until the snapshot has been performed

File: pkg/node/manager/manager.go [hunk 2]
```diff
@@ -794,11 +936,24 @@ func (m *manager) NodeDeleted(n nodeTypes.Node) {
...
+		entry         *nodeEntry
+		oldNodeExists bool
+	)
+
 	m.mutex.Lock()
-	entry, oldNodeExists := m.nodes[nodeIdentifier]
-	if !oldNodeExists {
-		m.mutex.Unlock()
-		return
+	// If the node is restored from disk, it doesn't exist in the bookkeeping,
```
Comment (gandro) [inline pkg/node/manager/manager.go:958]: Since IPCache is always created from scratch, we don't have to remove any stale entries there. We probably should investigate if we can skip the IPCache logic here and directly go to the `datapath.NodeHandlers` below

**Review by gandro — COMMENTED** [review]
Awesome work! Looks excellent to me. Two very minor things

File: pkg/node/manager/manager.go (hunk 1 above)
Comment (bimmlerd) [reply pkg/node/manager/manager.go:341]: good point, added

File: pkg/node/manager/manager.go (hunk 2 above)
Comment (bimmlerd) [reply pkg/node/manager/manager.go:958]: skipping `removeNodeFromIPCache` now - is that enough?

Comment (gandro) [reply pkg/node/manager/manager.go:958]: I see `removeNodeFromIPCache` also calls into the IPSetMgr. I think we already have a reconciler for IPSets which cleans up stale IPSet entries, so skipping `removeNodeFromIPCache` should be fine - but maybe not on stable branches (if we want to backport this). Something to keep in mind.

Other than that, this looks good to me, thanks!

**Review by gandro — APPROVED** [review]
Looks good to me now!

**Review by thorn3r — APPROVED** [review]
Nice work :+1:

File: pkg/node/manager/manager.go [hunk 3]
```diff
@@ -299,6 +335,15 @@ func (m *manager) Stop(cell.HookContext) error {
 	m.mutex.Lock()
 	defer m.mutex.Unlock()
 
+	if m.nodeCheckpointer != nil {
+		// Using the shutdown func of trigger to checkpoint would block shutdown
+		// for up to its MinInterval, which is too long.
+		m.nodeCheckpointer.Shutdown()
+		close(m.checkpointerDone)
+		_ = m.checkpoint() // Not much we can do on error.
```
Comment (nebril) [inline pkg/node/manager/manager.go]: Can we at least log the error?

**Review by nebril — APPROVED** [review]
LGTM, one minor comment left inline.

File: pkg/node/manager/manager.go (hunk 3 above)
Comment (bimmlerd) [reply pkg/node/manager/manager.go]: fair point, added.

**Comment by bimmlerd** [comment]
@ldelossa friendly ping for review

**Review by borkmann — APPROVED** [review]

**Comment by bimmlerd** [comment]
marking for backport to 1.16 as it's a bugfix
