### PR TITLE
multipool: Fix allocations when deleting or shrinking pools

### LINKED ISSUE #41986: Issue when extending `CiliumPodIPPool` with new CIDRs
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.7 and lower than v1.18.0

### What happened?

1. I have a cluster with 15 worker nodes, using a pod IP pool containing 9 CIDR blocks. They're announced to the border firewall using BGP.
2. I added a 16th worker node.
3. Few hours later, I noticed some pods lost their network connectivity (e.g. coreDNS could no longer connect to our internal DNS server).
4. During troubleshooting I noticed I had a couple of CIDRs advertised twice, but we're not doing ECMP so only one route was active.
5. While checking the `CiliumNode` I noticed several nodes had the same CIDR block assigned. This was confirmed by checking the IP address assigned to pods on those nodes.
6. I suspected I was running out of CIDR blocks in the pool, so I added a 10th block there, then bootstrapped a 17th worker node to see how it goes. Unfortunately, this new node also got assigned a CIDR block already in use. The node was cordoned to avoid new pods from being scheduled on it.
7. I restarted the Cilium operator, which fixed the duplicates by reassigning new (unused) CIDR blocks to the "broken" nodes. I had to restart pods on those nodes to ensure they get assigned an IP address from the CIDR block linked to the node. This concluded the issue.

### How can we reproduce the issue?

1. Install Cilium, using MP IPAM and create a default `CiliumPodIPPool`.
2. Schedule workloads on the cluster (maybe until the pod IP pool is fully used?).
3. Extend the pool by adding CIDRs to it - but DON'T restart the operator (I suspect this is the cause).
4. Add nodes to the cluster and check the CIDR blocks assigned.

### Cilium Version

v1.17.7

### Kernel Version

5.15.0-140-generic

### Kubernetes Version

v1.32.5

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell
# before operator restart
{"error":"an error on the server (\"[+]ping ok\\n[+]log ok\\n[-]etcd failed: reason withheld\\n[+]poststarthook/start-apiserver-admission-initializer ok\\n[+]poststarthook/generic-apiserver-start-informers ok\\n[+]poststarthook/priority-and-fairness-config-consumer ok\\n[+]poststarthook/priority-and-fairness-filter ok\\n[+]poststarthook/storage-object-count-tracker-hook ok\\n[+]poststarthook/start-apiextensions-informers ok\\n[+]poststarthook/start-apiextensions-controllers ok\\n[+]poststarthook/crd-informer-synced ok\\n[+]poststarthook/start-system-namespaces-controller ok\\n[+]poststarthook/start-cluster-authentication-info-controller ok\\n[+]poststarthook/start-kube-apiserver-identity-lease-controller ok\\n[+]poststarthook/start-kube-apiserver-identity-lease-garbage-collector ok\\n[+]poststarthook/start-legacy-token-tracking-controller ok\\n[+]poststarthook/start-service-ip-repair-controllers ok\\n[+]poststarthook/rbac/bootstrap-roles ok\\n[+]poststarthook/scheduling/bootstrap-system-priority-classes ok\\n[+]poststarthook/priority-and-fairness-config-producer ok\\n[+]poststarthook/bootstrap-controller ok\\n[+]poststarthook/aggregator-reload-proxy-client-cert ok\\n[+]poststarthook/start-kube-aggregator-informers ok\\n[+]poststarthook/apiservice-status-local-available-controller ok\\n[+]poststarthook/apiservice-status-remote-available-controller ok\\n[+]poststarthook/apiservice-registration-controller ok\\n[+]poststarthook/apiservice-discovery-controller ok\\n[+]poststarthook/kube-apiserver-autoregistration ok\\n[+]autoregister-completion ok\\n[+]poststarthook/apiservice-openapi-controller ok\\n[+]poststarthook/apiservice-openapiv3-controller ok\\nhealthz check failed\") has prevented the request from succeeding (get healthz.meta.k8s.io)","level":"warning","msg":"Network status error received, restarting client connections","subsys":"k8s-client-builder"}
{"error":"an error on the server (\"[+]ping ok\\n[+]log ok\\n[-]etcd failed: reason withheld\\n[+]poststarthook/start-apiserver-admission-initializer ok\\n[+]poststarthook/generic-apiserver-start-informers ok\\n[+]poststarthook/priority-and-fairness-config-consumer ok\\n[+]poststarthook/priority-and-fairness-filter ok\\n[+]poststarthook/storage-object-count-tracker-hook ok\\n[+]poststarthook/start-apiextensions-informers ok\\n[+]poststarthook/start-apiextensions-controllers ok\\n[+]poststarthook/crd-informer-synced ok\\n[+]poststarthook/start-system-namespaces-controller ok\\n[+]poststarthook/start-cluster-authentication-info-controller ok\\n[+]poststarthook/start-kube-apiserver-identity-lease-controller ok\\n[+]poststarthook/start-kube-apiserver-identity-lease-garbage-collector ok\\n[+]poststarthook/start-legacy-token-tracking-controller ok\\n[+]poststarthook/start-service-ip-repair-controllers ok\\n[+]poststarthook/rbac/bootstrap-roles ok\\n[+]poststarthook/scheduling/bootstrap-system-priority-classes ok\\n[+]poststarthook/priority-and-fairness-config-producer ok\\n[+]poststarthook/bootstrap-controller ok\\n[+]poststarthook/aggregator-reload-proxy-client-cert ok\\n[+]poststarthook/start-kube-aggregator-informers ok\\n[+]poststarthook/apiservice-status-local-available-controller ok\\n[+]poststarthook/apiservice-status-remote-available-controller ok\\n[+]poststarthook/apiservice-registration-controller ok\\n[+]poststarthook/apiservice-discovery-controller ok\\n[+]poststarthook/kube-apiserver-autoregistration ok\\n[+]autoregister-completion ok\\n[+]poststarthook/apiservice-openapi-controller ok\\n[+]poststarthook/apiservice-openapiv3-controller ok\\nhealthz check failed\") has prevented the request from succeeding (get healthz.meta.k8s.io)","level":"warning","msg":"Network status error received, restarting client connections","subsys":"k8s-client-builder"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
Failed to update lock optimistically: Put "https://10.11.12.58:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cilium-operator-resource-lock?timeout=5s": context deadline exceeded, falling back to slow path
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
{"error":"failed to allocate ipv4 address for node \"my-cluster-md-worker-default-jqzz7-hlldv\" from pool \"default\": pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-hlldv","subsys":"ipam-allocator-multi-pool"}
Failed to update lock optimistically: Put "https://10.11.12.58:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cilium-operator-resource-lock?timeout=5s": read tcp 10.11.12.176:53454->10.11.12.58:6443: read: connection reset by peer, falling back to slow path
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-kcp-d2t8l","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-md-infra-4gk7n-gk4nf","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-md-worker-datamesh-t6h7m-h5nvj","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-md-worker-default-jqzz7-xz5dk","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-md-worker-datamesh-t6h7m-cx8kl","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-md-worker-default-jqzz7-8g8pq","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-md-worker-default-jqzz7-bcbdb","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-md-worker-default-jqzz7-vtx9c","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-md-infra-4gk7n-4cdpk","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-md-worker-default-jqzz7-fzhw4","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-md-worker-default-jqzz7-jjn4x","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-md-worker-rabbitmq-c7twz-l2sml","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-md-worker-rabbitmq-c7twz-vbrs2","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-md-infra-4gk7n-grvdc","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-md-worker-default-jqzz7-6hcsv","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-md-worker-default-jqzz7-k58gz","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-md-worker-rabbitmq-c7twz-6kkmn","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-md-worker-default-jqzz7-5bt2v","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-md-worker-default-jqzz7-66q86","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-md-worker-default-jqzz7-69fzw","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-md-worker-default-jqzz7-cwwcx","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-md-worker-default-jqzz7-hlldv","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-kcp-mjqqc","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-md-worker-default-jqzz7-6bz52","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-md-worker-rabbitmq-c7twz-q6dns","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-kcp-8pdlt","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-md-worker-datamesh-t6h7m-d67zj","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-md-worker-default-jqzz7-p87sm","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-md-worker-rabbitmq-c7twz-xgc5k","pool":"default","subsys":"ipam-allocator-multi-pool"}
{"level":"warning","msg":"pool still in use by node","node":"my-cluster-md-worker-default-jqzz7-6hcsv","pool":"prod-databases","subsys":"ipam-allocator-multi-pool"}
{"error":"github.com/cilium/cilium/pkg/k8s/resource/resource.go:814: Failed to watch *v2alpha1.CiliumPodIPPool: the server could not find the requested resource (get ciliumpodippools.cilium.io)","level":"error","msg":"k8sError","subsys":"k8s"}
{"level":"warning","msg":"github.com/cilium/cilium/pkg/k8s/resource/resource.go:814: failed to list *v2alpha1.CiliumPodIPPool: the server could not find the requested resource (get ciliumpodippools.cilium.io)","subsys":"klog"}
{"error":"github.com/cilium/cilium/pkg/k8s/resource/resource.go:814: Failed to watch *v2alpha1.CiliumPodIPPool: failed to list *v2alpha1.CiliumPodIPPool: the server could not find the requested resource (get ciliumpodippools.cilium.io)","level":"error","msg":"k8sError","subsys":"k8s"}
{"level":"warning","msg":"github.com/cilium/cilium/pkg/k8s/resource/resource.go:814: failed to list *v2alpha1.CiliumPodIPPool: the server could not find the requested resource (get ciliumpodippools.cilium.io)","subsys":"klog"}
{"error":"github.com/cilium/cilium/pkg/k8s/resource/resource.go:814: Failed to watch *v2alpha1.CiliumPodIPPool: failed to list *v2alpha1.CiliumPodIPPool: the server could not find the requested resource (get ciliumpodippools.cilium.io)","level":"error","msg":"k8sError","subsys":"k8s"}
{"level":"warning","msg":"github.com/cilium/cilium/pkg/k8s/resource/resource.go:814: failed to list *v2alpha1.CiliumPodIPPool: the server could not find the requested resource (get ciliumpodippools.cilium.io)","subsys":"klog"}
{"error":"github.com/cilium/cilium/pkg/k8s/resource/resource.go:814: Failed to watch *v2alpha1.CiliumPodIPPool: failed to list *v2alpha1.CiliumPodIPPool: the server could not find the requested resource (get ciliumpodippools.cilium.io)","level":"error","msg":"k8sError","subsys":"k8s"}

# after operator restart
{"error":"unable to reuse from pool default: pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-rabbitmq-c7twz-xgc5k","subsys":"ipam-allocator-multi-pool"}
{"error":"unable to reuse from pool default: pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-nvmrd","subsys":"ipam-allocator-multi-pool"}
{"error":"unable to reuse from pool default: pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-rabbitmq-c7twz-l2sml","subsys":"ipam-allocator-multi-pool"}
{"error":"unable to reuse from pool default: pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-default-jqzz7-h4b7n","subsys":"ipam-allocator-multi-pool"}
{"error":"unable to reuse from pool default: pool empty","level":"warning","msg":"Failed to allocate PodCIDRs to node","nodeName":"my-cluster-md-worker-rabbitmq-c7twz-xgc5k","subsys":"ipam-allocator-multi-pool"}
```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by pippolo84**
When a CiliumPodIPPool is shrunk or deleted but its CIDRs are still in use by the nodes (i.e: there are some pods scheduled on those nodes with IPs from the removed CIDRs), we enter a status where the operator is not able to correctly account the allocated CIDRs anymore.
Specifically, it is possible to add again the deleted pool and end up with another node getting assigned the same CIDRs still in use by the initial node and ultimately having the same IPs assigned to multiple pods.

To avoid this scenario, beside emitting a warning when the operator detects that a CIDR still in use has been deleted, we introduce the concept of **orphan CIDRs**: CIDRs that do not have their parent pool anymore. The operator keeps track of those CIDRs specifically, in order to:

1) reconcile the internal allocation maps in case the original pool is restored
2) reject the insertion of new pools (i.e: pools with a different name) that contains the orphan CIDRs
3) release the orphan CIDRs if the node do not claim that anymore

This is done in order to allow fixing the orphan CIDRs scenario by either:

a) restore the CiliumPodIPPool that should not have been shrunk or deleted initially
b) delete all pods using an IP from a deleted pool

Please refer to the individual commit messages for more information.

Fixes: #41986

```release-note
Fix operator CIDR allocations in multi-pool IPAM mode after a CiliumPodIPPool update or re-insertion
```

### CODE REVIEW

File: pkg/ipam/allocator/multipool/pool_allocator.go [hunk 1]
```diff
@@ -96,18 +96,20 @@ func addrsInPrefix(p netip.Prefix) *big.Int {
...
-	logger *slog.Logger
-	mutex  lock.RWMutex
-	pools  map[string]cidrPool    // poolName -> pool
-	nodes  map[string]poolToCIDRs // nodeName -> pool -> cidrs
-	ready  bool
+	logger  *slog.Logger
+	mutex   lock.RWMutex
+	pools   map[string]cidrPool    // poolName -> pool
+	nodes   map[string]poolToCIDRs // nodeName -> pool -> cidrs
+	orphans map[string]cidrSets    // nodeName -> list of orphaned CIDRs (CIDRs allocated to nodes but missing their parent pool)
```
Comment (gandro) [inline pkg/ipam/allocator/multipool/pool_allocator.go]: This datastructure does not survive operator restart, right? So if the operator is restarted, we loose track of orphans and their CIDRs will be re-allocated without checking.

I think we also need to restore those. Unfortunately, it is a bit more tricky to do.

The ordering for restoration seems fine: `StartIPPoolAllocator` blocks until all pools have been received. So `NewNodeHandler` is called once all existing pools have been added to `pools` above. This means (I believe) we can declare something an orphan in the `PoolAllocator.occupyCIDR` if a node requests a CIDR from a pool that doesn't exist yet. I assume this is mostly fine, even if the pool never existed. It's a slight difference to the definition of an "orphan", because your current implementation only creates orphans for pools that actually at some point did exist. But since we loose all history on operator restart, we can't tell if a pools stopped existing or if a pool never existed in the first place.

~There is unfortunately one caveat with trusting nodes that they only request pools that existed at some point: We currently don't assert that a pod can only request IPs from a pool that exists. A malicious actor who can create pods could create a bunch of pods requesting IPs from pools that don't exist, thereby causing this `orphans` map to fill up with garbage. It's realistically speaking probably not that easy to trigger an OOM, but it's still a potential memory leak even for misconfigured clusters. We would have to check [here](https://github.com/cilium/cilium/blob/11fecab3f09c8634cc3e01722b21b475fc40d030/pkg/ipam/multipool.go#L717) or in `upsertPendingAllocation` that the there actually exists a CiliumPodIPPool for the requested pool~

Edit: Actually, the above is not a concern, since we can only orphan a CIDR that has been marked as allocated. A pod cannot cause a particular CIDR to be marked as allocated before a pool exists, so there's no attack vector there. So really I think the only thing that needs to be done is to mark orphans here:
https://github.com/cilium/cilium/blob/e69bd64a1c34f393d91a2337e697b335c793d975/pkg/ipam/allocator/multipool/pool_allocator.go#L517

**Review by gandro — COMMENTED** [review]
Awesome work! One thing around operator restart that we need to think about a bit

File: pkg/ipam/allocator/multipool/pool_allocator.go (hunk 1 above)
Comment (pippolo84) [reply pkg/ipam/allocator/multipool/pool_allocator.go]: > This datastructure does not survive operator restart, right? So if the operator is restarted, we loose track of orphans and their CIDRs will be re-allocated without checking.

I realized that few hours ago and was actually trying to fix it now :sweat: 

> This means (I believe) we can declare something an orphan in the PoolAllocator.occupyCIDR if a node requests a CIDR from a pool that doesn't exist yet.

I was trying to mark a CIDR as orphan in `AllocateToNode`, where we list the `allocatedSet` (in case the pool cannot be found) . It also requires to change `*PoolAllocator.AllocatedPools`, since now we want to keep the CIDRs from `p.orphan` as "allocated" across the restart. Consequently, a bunch of assertions have to be changed in the unit tests. TBH, I still have to fully understand the extent of that change in `AllocatedPools` (specifically, of always trusting the allocations reported by the CiliumNode resource) but I think it should be fine, apart from what you already pointed out.

> We would have to check [here](https://github.com/cilium/cilium/blob/11fecab3f09c8634cc3e01722b21b475fc40d030/pkg/ipam/multipool.go#L717) or in upsertPendingAllocation that the there actually exists a CiliumPodIPPool for the requested pool.

Seems resonable: we don't allow new allocations from non existent pools, but we trust the CiliumNode from the past. :+1:

File: pkg/ipam/allocator/multipool/pool_allocator.go [hunk 2]
```diff
@@ -389,7 +450,27 @@ func (p *PoolAllocator) AllocatedPools(targetNode string) (pools []types.IPAMPoo
...
+	// we have to aggregate CIDRs allocated from existing pools as well as orphan CIDRs
+	poolToCIDRs := poolToCIDRs{}
+	for _, poolName := range append(
+		slices.Collect(maps.Keys(p.nodes[targetNode])),
+		slices.Collect(maps.Keys(p.orphans[targetNode]))...,
+	) {
+		sets, found := poolToCIDRs[poolName]
+		if !found {
+			sets = cidrSets{v4: cidrSet{}, v6: cidrSet{}}
+		}
```
Comment (gandro) [inline pkg/ipam/allocator/multipool/pool_allocator.go]: I want to make sure I understand this logic correctly: We are iterating over pool names (where a pool name can occur twice, i.e. once from `nodes` and once from `orphans`), but when we collect the CIDRs below, we copy both them from both sources.

So if a poolName is already in `poolToCIDRs` and `found=true`, there is nothing we have to do, right? The second time we execute the loop body for a given poolName it is a no-op.

(I'm fine to keep in the current defensive programming style, I just wanted to make sure I understood the logic correctly)

File: pkg/ipam/allocator/multipool/pool_allocator.go [hunk 3]
```diff
@@ -366,9 +366,14 @@ func (p *PoolAllocator) AllocateToNode(cn *v2.CiliumNode) error {
...
-			occupyErr := p.occupyCIDR(cn.Name, allocatedPool.Pool, prefix)
-			if occupyErr != nil {
-				err = errors.Join(err, occupyErr)
+			if _, found := p.pools[allocatedPool.Pool]; found {
+				if occupyErr := p.occupyCIDR(cn.Name, allocatedPool.Pool, prefix); occupyErr != nil {
+					err = errors.Join(err, occupyErr)
+				}
+			} else {
+				// pool cannot be found: it must be a pool deleted before the operator restarted.
+				// Mark the CIDR as orphan to preserve node allocations.
```
Comment (gandro) [inline pkg/ipam/allocator/multipool/pool_allocator.go:369]: I think we still should report an error (as it is written into the node status) if the pool is not found.

**Review by gandro — COMMENTED** [review]
Neat, thanks! One minor piece of feedback

File: pkg/ipam/allocator/multipool/pool_allocator.go [hunk 4]
```diff
@@ -366,9 +366,14 @@ func (p *PoolAllocator) AllocateToNode(cn *v2.CiliumNode) error {
...
+				p.markOrphan(cn.Name, allocatedPool.Pool, prefix)
```
Comment (gandro) [inline pkg/ipam/allocator/multipool/pool_allocator.go:370]: Something I just realized: If an orphan is removed from the `Allocated` list (i.e. a node stopped claiming to have allocated a ophaned CIDR) - I think we also need to unorphan it below?

Otherwise the CIDR is associated with the node forever if the pool never is re-recreated.

File: pkg/ipam/allocator/multipool/pool_allocator.go (hunk 2 above)
Comment (pippolo84) [reply pkg/ipam/allocator/multipool/pool_allocator.go]: > So if a poolName is already in poolToCIDRs and found=true, there is nothing we have to do, right? The second time we execute the loop body for a given poolName it is a no-op.

That's correct. We need to address 3 cases:
1) a pool is only present in p.nodes
2) a pool is only present in p.orphans
3) a pool is present both in p.nodes and in p.orphans (this can happen if we shrink a pool and some CIDRs, but not all, become orphans)

File: pkg/ipam/allocator/multipool/pool_allocator.go (hunk 3 above)
Comment (pippolo84) [reply pkg/ipam/allocator/multipool/pool_allocator.go:369]: Yeah, makes sense, I'll change it.

File: pkg/ipam/allocator/multipool/pool_allocator.go (hunk 4 above)
Comment (pippolo84) [reply pkg/ipam/allocator/multipool/pool_allocator.go:370]: > I think we also need to unorphan it below?

That's right, good catch :+1: 

Related to this, I found another case that it's worth thinking about. Now that we tie the orphan CIDRs to the original "parent" pool name (see `p.orphans` type), and we also consider the information in `spec.IPAM.Pools.Allocated` in the CiliumNode as the source of truth, I think we should also return an error in case a new pool (i.e: a pool with a different name) that contains the orphan CIDRs is added. E.g:

- `10.0.1.0/24` is an orphan from deleted pool `test-pool`
- a node reports that CIDR as allocated in its CiliumNode:

```
Requested: {
	{
		Pool: "test-pool",
		Needed: ipamTypes.IPAMPoolDemand{
			IPv4Addrs: 10,
		},
	},
},
Allocated: {
	{
		Pool: "test-pool",
		CIDRs: []ipamTypes.IPAMPodCIDR{
			"10.0.1.0/24",
		},
	},
},
```
- `another-test-pool` with CIDR `10.0.0.0/16` is added 

In this case, we return an error at the insertion of the new pool. Otherwise we should handle the "orphan CIDR stealing" from the original pool to the new one and emit an update for the CiliumNode. For the sake of simplicity, I chose not to and also added a test to assert the error (coming with the next push-force).

WDYT? I'm open to discuss the addition of this "stealing" operation, but in case I think it'd be better to leave it as a later work.

Comment (gandro) [reply pkg/ipam/allocator/multipool/pool_allocator.go:370]: Interesting idea, but I strongly prefer no interactions between two pools, for the reason that I think we might want to support overlapping IP pools in the future. While we currently don't support overlapping pools in the datapath (or overlapping pod IPs for that matter), it is something I would want to have in the future in some form.

File: pkg/ipam/allocator/multipool/pool_allocator.go (hunk 2 above)
Comment (pippolo84) [reply pkg/ipam/allocator/multipool/pool_allocator.go]: Updated to use `continue` if the key is found in `poolToCIDRs`

File: pkg/ipam/allocator/multipool/pool_allocator.go (hunk 4 above)
Comment (pippolo84) [reply pkg/ipam/allocator/multipool/pool_allocator.go:370]: Sounds good, I avoided the "stealing" and also added a test to prove that it won't happen. What we are gonna do is simply to block the insertion of a new pool if it include orphan CIDRs. :+1:

**Comment by pippolo84** [comment]
@gandro I kept the release of the orphan CIDRs when they are not used by nodes anymore in a separate [commit](https://github.com/cilium/cilium/pull/42126/commits/2fc8c9934f7d7716ca2ac31c197ff4928619d4d0). Same for the test that assert that "stealing" orphan CIDRs is not possible (see [this commit](https://github.com/cilium/cilium/pull/42126/commits/8a0bf79582348f2890fec86f6191a2ed22a89959)). Hope that will ease the further round of review a bit.

Also, while working on the above I've discovered another bug and fixed it, see this [commit](https://github.com/cilium/cilium/pull/42126/commits/a7d61c759c226e0ce2f7e9a27b2b270d649c5bd4).

I understand the PR is becoming pretty convoluted, if you prefer I can try to split it, let me know.

**Comment by pippolo84** [comment]
ci-integration failure seems legit, marking this back to draft while I investigate.

**Review by gandro — APPROVED** [review]
Awesome work!

**Comment by pippolo84** [comment]
> ci-integration failure seems legit, marking this back to draft while I investigate.

It was just a matter of using the correct `c *assert.Collect` in the condition passed to `assert.EventuallyWithT`, fixed.

@gandro also added a very minor cleanup to DRY `updateCIDRSets` a bit, see https://github.com/cilium/cilium/pull/42126/commits/ca8bb6de4ec563ddadd9400e78bbe0683575d59c.

**Review by gandro — APPROVED** [review]
