### PR TITLE
pkg/ciliumidentity: Fix TestUpdateUsedCIDIsReverted test

### LINKED ISSUE #36996: CI: ciliumidentity: TestUpdateUsedCIDIsReverted failed: lbmap mismatch
## CI failure

Discovered in PR https://github.com/cilium/cilium/pull/36602, but that PR is unrelated to the change here.

https://github.com/cilium/cilium/actions/runs/12795392193/job/35672703492#step:17:14138

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃   FAIL  package: github.com/cilium/cilium/operator/pkg/ciliumidentity   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

--- FAIL: TestUpdateUsedCIDIsReverted (0.64s)

    logger.go:257: time=2025-01-15T19:31:37.424Z level=INFO source=/host/operator/pkg/ciliumidentity/controller.go:159 msg="CID controller resource work queue configuration" workQueueSyncBackOff=1s workQueueMaxSyncBackOff=1m40s
    logger.go:257: time=2025-01-15T19:31:37.424Z level=INFO source=/host/vendor/github.com/cilium/hive/hive.go:338 msg="Starting hive"
    logger.go:257: time=2025-01-15T19:31:37.424Z level=INFO source=/host/operator/pkg/ciliumidentity/controller.go:122 msg="Starting CID controller Operator"
    logger.go:257: time=2025-01-15T19:31:37.424Z level=INFO source=/host/vendor/github.com/cilium/hive/hive.go:342 msg=Started duration=61.234µs
    logger.go:257: time=2025-01-15T19:31:37.424Z level=INFO source=/host/operator/pkg/ciliumidentity/reconciler.go:67 msg="Creating CID controller Operator reconciler"
    logger.go:257: time=2025-01-15T19:31:38.046Z level=INFO source=/host/operator/pkg/ciliumidentity/controller.go:211 msg="Starting CID controller reconciler"
    logger.go:257: time=2025-01-15T19:31:38.047Z level=INFO source=/host/operator/pkg/ciliumidentity/reconciler.go:387 msg="Reconcile all pods in namespace" k8sNamespace=ns1
    logger.go:257: time=2025-01-15T19:31:38.047Z level=INFO source=/host/operator/pkg/ciliumidentity/controller.go:216 msg="Starting resource worker"
    logger.go:257: time=2025-01-15T19:31:38.047Z level=INFO source=/host/operator/pkg/ciliumidentity/reconciler.go:294 msg="CID allocated for pod" k8sPodName=ns1/pod1 ciliumIdentityName=30308 oldIdentity="" labels="map[io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name:ns1 io.cilium.k8s.policy.cluster: io.kubernetes.pod.namespace:ns1 key-c:val-3]"
    logger.go:257: time=2025-01-15T19:31:38.047Z level=INFO source=/host/operator/pkg/ciliumidentity/reconciler.go:187 msg="Creating CID" labels="map[k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name:ns1 k8s:io.cilium.k8s.policy.cluster: k8s:io.kubernetes.pod.namespace:ns1 k8s:key-c:val-3]" ciliumIdentityName=30308
    logger.go:257: time=2025-01-15T19:31:38.056Z level=INFO source=/host/operator/pkg/ciliumidentity/reconciler.go:202 msg="Updating CID" ciliumIdentityName=30308
    controller_test.go:426: expected labels map[k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name:ns1 k8s:io.cilium.k8s.policy.cluster: k8s:io.kubernetes.pod.namespace:ns1 k8s:key-b:val-2], got map[k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name:ns1 k8s:io.cilium.k8s.policy.cluster: k8s:io.kubernetes.pod.namespace:ns1 k8s:key-c:val-3]
    logger.go:257: time=2025-01-15T19:31:38.057Z level=INFO source=/host/vendor/github.com/cilium/hive/hive.go:354 msg=Stopping
    logger.go:257: time=2025-01-15T19:31:38.059Z level=INFO source=/host/operator/pkg/ciliumidentity/controller.go:227 msg="Stopping resource worker"
    logger.go:257: time=2025-01-15T19:31:38.059Z level=INFO source=/host/pkg/hive/health/provider.go:57 msg="health.job-module-status-metrics (rev=7)" module=health
    logger.go:257: time=2025-01-15T19:31:38.059Z level=INFO source=/host/pkg/hive/health/provider.go:57 msg="test.job-op-managing-resource-wq (rev=8)" module=health
    logger.go:257: time=2025-01-15T19:31:38.059Z level=INFO source=/host/pkg/hive/health/provider.go:57 msg="test.job-proc-ces-events (rev=9)" module=health
    logger.go:257: time=2025-01-15T19:31:38.059Z level=INFO source=/host/pkg/hive/health/provider.go:57 msg="test.job-proc-cid-events (rev=10)" module=health
    logger.go:257: time=2025-01-15T19:31:38.059Z level=INFO source=/host/pkg/hive/health/provider.go:57 msg="test.job-proc-ns-events (rev=12)" module=health
    logger.go:257: time=2025-01-15T19:31:38.059Z level=INFO source=/host/pkg/hive/health/provider.go:57 msg="test.job-proc-pod-events (rev=11)" module=health
```

```
    testcase.go:352: validation failed: lbmap mismatch:
        --- /host/test/controlplane/services/nodeport/v1.26/lbmap1_nodeport-worker.golden
        +++ <actual>
        @@ -1,28 +1,17 @@
        - - Services --------------------------------------------------------------------------------------
        -| ID |                                      Name |      Type |             Frontend | Backend IDs |
        -|----+-------------------------------------------+-----------+----------------------+-------------
        -|  0 |                        default/kubernetes | ClusterIP |    10.96.0.1:443/TCP |           1 |
        -|  1 |                                 test/echo | ClusterIP |  10.96.50.104:80/TCP |           0 |
        -|  2 |                           test/echo-local | ClusterIP |  10.96.155.18:80/TCP |           0 |
        -|  3 | test/echo-757d4cb97f-9gmf7/host-port/8080 |  HostPort |     0.0.0.0:8080/TCP |           0 |
        -|  4 | test/echo-757d4cb97f-9gmf7/host-port/8080 |  HostPort |    10.0.0.2:8080/TCP |           0 |
        -|  5 | test/echo-757d4cb97f-9gmf7/host-port/8080 |  HostPort |    10.0.0.3:8080/TCP |           0 |
        -|  6 |                                 test/echo |  NodePort |    0.0.0.0:30781/TCP |           0 |
        -|  7 |                                 test/echo |  NodePort |   10.0.0.2:30781/TCP |           0 |
        -|  8 |                                 test/echo |  NodePort |   10.0.0.3:30781/TCP |           0 |
        -|  9 |                           test/echo-local |  NodePort |    0.0.0.0:30867/TCP |           0 |
        -| 10 |                           test/echo-local |  NodePort |  0.0.0.0:30867/TCP/i |           0 |
        -| 11 |                           test/echo-local |  NodePort |   10.0.0.2:30867/TCP |           0 |
        -| 12 |                           test/echo-local |  NodePort | 10.0.0.2:30867/TCP/i |           0 |
        -| 13 |                           test/echo-local |  NodePort |   10.0.0.3:30867/TCP |           0 |
        -| 14 |                           test/echo-local |  NodePort | 10.0.0.3:30867/TCP/i |           0 |
        - -------------------------------------------------------------------------------------------------
        + - Services -----------------------------------------------------------------------------------
        +| ID |                                      Name |      Type |          Frontend | Backend IDs |
        +|----+-------------------------------------------+-----------+-------------------+-------------
        +|  0 |                        default/kubernetes | ClusterIP | 10.96.0.1:443/TCP |           1 |
        +|  1 | test/echo-757d4cb97f-9gmf7/host-port/8080 |  HostPort |  0.0.0.0:8080/TCP |           0 |
        +|  2 | test/echo-757d4cb97f-9gmf7/host-port/8080 |  HostPort | 10.0.0.2:8080/TCP |           0 |
        +|  3 | test/echo-757d4cb97f-9gmf7/host-port/8080 |  HostPort | 10.0.0.3:8080/TCP |           0 |
        + ----------------------------------------------------------------------------------------------
         
        - - Backends ------------------------------------------------------------------------
        -| ID |            L3n4Addr |  State |                               Linked Services |
        -|----+---------------------+--------+-----------------------------------------------
        -|  0 | 10.244.1.224:80/TCP | active | 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 |
        -|  1 | 172.18.0.4:6443/TCP | active |                                             0 |
        - -----------------------------------------------------------------------------------
        + - Backends ------------------------------------------
        +| ID |            L3n4Addr |  State | Linked Services |
        +|----+---------------------+--------+-----------------
        +|  0 | 10.244.1.224:80/TCP | active |         1, 2, 3 |
        +|  1 | 172.18.0.4:6443/TCP | active |               0 |
        + -----------------------------------------------------
```

### PR DESCRIPTION
**Pull request by ovidiutirla**
Fixes the TestUpdateUsedCIDIsReverted flakiness. Looks like `k8sClient.FakeClientset` is not properly synchronized and looks like is not properly propagating updating the store in a highly concurrent environment.
Instead of relying on .Events() order moved to only .List() with Eventually() to nicely wait for the re-generation.

```
3m15s: 42687 runs so far, 0 failures, 128 active
```

Fixes: https://github.com/cilium/cilium/issues/36996

### CODE REVIEW

File: operator/pkg/ciliumidentity/controller_test.go [hunk 1]
```diff
@@ -414,31 +405,24 @@ func TestUpdateUsedCIDIsReverted(t *testing.T) {
...
-	ev := <-events
-	if ev.Kind != resource.Upsert {
-		t.Fatalf("expected upsert event, got %v", ev.Kind)
-	}
-	if ev.Key.Name != toUpdate.Name {
-		t.Fatalf("expected upsert event for cid %s, got %v", toUpdate.Name, ev.Key.Name)
-	}
-	if !cmp.Equal(ev.Object.SecurityLabels, updated.SecurityLabels) {
-		t.Fatalf("expected labels %v, got %v", updated.SecurityLabels, ev.Object.SecurityLabels)
+	cid, err := fakeClient.CiliumV2().CiliumIdentities().Get(ctx, updated.Name, metav1.GetOptions{})
```
Comment (pippolo84) [inline operator/pkg/ciliumidentity/controller_test.go:408]: Let's add the check for the returned `err`

**Review by pippolo84 — COMMENTED** [review]
Thanks, just one minor thing to address. :pray: 

I'd be curious to understand why the FakeClientset sometimes fails to guarantee the correct events ordering, but for the problem at hand this approach is good enough.

File: operator/pkg/ciliumidentity/controller_test.go (hunk 1 above)
Comment (ovidiutirla) [reply operator/pkg/ciliumidentity/controller_test.go:408]: done

File: operator/pkg/ciliumidentity/controller_test.go [hunk 2]
```diff
@@ -414,31 +405,27 @@ func TestUpdateUsedCIDIsReverted(t *testing.T) {
...
 	}
 
-	// Wait for update event to propagate.
-	ev := <-events
-	if ev.Kind != resource.Upsert {
-		t.Fatalf("expected upsert event, got %v", ev.Kind)
-	}
-	if ev.Key.Name != toUpdate.Name {
-		t.Fatalf("expected upsert event for cid %s, got %v", toUpdate.Name, ev.Key.Name)
+	cid, err := fakeClient.CiliumV2().CiliumIdentities().Get(ctx, updated.Name, metav1.GetOptions{})
```
Comment (dlapcevic) [inline operator/pkg/ciliumidentity/controller_test.go:408]: Isn't it possible that CID controller would revert the CID before the test gets it here?

I assume you ran the stress test and it didn't fail.

**Review by dlapcevic — APPROVED** [review]

File: operator/pkg/ciliumidentity/controller_test.go (hunk 2 above)
Comment (ovidiutirla) [reply operator/pkg/ciliumidentity/controller_test.go:408]: The GET operation is probably much faster than the operator receiving the event .. processing etc.. And since we use the mock I would almost expect it to be atomical.

**Review by pippolo84 — APPROVED** [review]
Thanks!
