### PR TITLE
test: Block HubbleObserveFollow until ready

### LINKED ISSUE #22056: CI: K8sAgentPolicyTest Basic Test Traffic redirections to proxy Tests HTTP proxy visibility without policy
### Test Name
```test-name
K8sAgentPolicyTest Basic Test Traffic redirections to proxy Tests HTTP proxy visibility without policy
```

### Failure Output
```failure-output
FAIL: traffic was not redirected to the proxy when it should have been
```

### Stacktrace
<details><summary>Click to show.</summary>

```stack-trace
/home/jenkins/workspace/Cilium-PR-K8s-1.25-kernel-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:515
traffic was not redirected to the proxy when it should have been
Expected
    <*errors.errorString | 0xc001228df0>: {
        s: "Expected string \"202211081614k8sagentpolicytestbasictesttlspolicy RESPONSE http://10.0.0.184/public 200 GET\" is not in the filter output of \"{.destination.namespace} {.l7.type} {.l7.http.url} {.l7.http.code} {.l7.http.method}\": 10s timeout expired",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-K8s-1.25-kernel-net-next/src/github.com/cilium/cilium/test/k8s/net_policies.go:378
```
</details>

### Standard Output
<details><summary>Click to show.</summary>

```stack-output
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Cilium pods: [cilium-dkv4n cilium-dlg5x]
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
Pod                           Ingress   Egress
app2-6b6857744b-g2c4r         false     false
app3-79897dfc85-4bdhh         false     false
grafana-59957b9549-dt2wf      false     false
prometheus-7c8c9684bb-cx2hz   false     false
coredns-567b6dd84-95bkn       false     false
app1-84dcf689db-dk4tc         false     false
app1-84dcf689db-fqfpg         false     false
Cilium agent 'cilium-dkv4n': Status: Ok  Health: Ok Nodes "" ContainerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 49 Failed 0
Cilium agent 'cilium-dlg5x': Status: Ok  Health: Ok Nodes "" ContainerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 19 Failed 0


```
</details>

### Standard Error
<details><summary>Click to show.</summary>

```stack-error
16:14:45 STEP: Running BeforeEach block for EntireTestsuite K8sAgentPolicyTest Basic Test
16:14:46 STEP: WaitforPods(namespace="202211081614k8sagentpolicytestbasictesttlspolicy", filter="-l zgroup=testapp")
16:14:46 STEP: WaitforPods(namespace="202211081614k8sagentpolicytestbasictesttlspolicy", filter="-l zgroup=testapp") => <nil>
16:14:46 STEP: Running BeforeAll block for EntireTestsuite K8sAgentPolicyTest Basic Test Traffic redirections to proxy
16:14:47 STEP: WaitforPods(namespace="202211081614k8sagentpolicytestbasictesttlspolicy", filter="-l zgroup=testapp")
16:14:47 STEP: WaitforPods(namespace="202211081614k8sagentpolicytestbasictesttlspolicy", filter="-l zgroup=testapp") => <nil>
16:14:47 STEP: Starting hubble observe and generating traffic which should not  redirect to proxy
16:14:51 STEP: Checking that aforementioned traffic was not redirected to the proxy
16:15:01 STEP: Annotating app1-84dcf689db-dk4tc with <Ingress/80/TCP/HTTP>
16:15:02 STEP: Starting hubble observe and generating traffic which should  redirect to proxy
16:15:06 STEP: Checking that aforementioned traffic was redirected to the proxy
FAIL: traffic was not redirected to the proxy when it should have been
Expected
    <*errors.errorString | 0xc001228df0>: {
        s: "Expected string \"202211081614k8sagentpolicytestbasictesttlspolicy RESPONSE http://10.0.0.184/public 200 GET\" is not in the filter output of \"{.destination.namespace} {.l7.type} {.l7.http.url} {.l7.http.code} {.l7.http.method}\": 10s timeout expired",
    }
to be nil
=== Test Finished at 2022-11-08T16:15:16Z====
16:15:16 STEP: Running JustAfterEach block for EntireTestsuite K8sAgentPolicyTest
===================== TEST FAILED =====================
16:15:17 STEP: Running AfterFailed block for EntireTestsuite K8sAgentPolicyTest
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE                                          NAME                               READY   STATUS    RESTARTS   AGE   IP              NODE   NOMINATED NODE   READINESS GATES
	 202211081614k8sagentpolicytestbasictesttlspolicy   app1-84dcf689db-dk4tc              2/2     Running   0          39s   10.0.0.184      k8s1   <none>           <none>
	 202211081614k8sagentpolicytestbasictesttlspolicy   app1-84dcf689db-fqfpg              2/2     Running   0          39s   10.0.0.72       k8s1   <none>           <none>
	 202211081614k8sagentpolicytestbasictesttlspolicy   app2-6b6857744b-g2c4r              1/1     Running   0          39s   10.0.0.21       k8s1   <none>           <none>
	 202211081614k8sagentpolicytestbasictesttlspolicy   app3-79897dfc85-4bdhh              1/1     Running   0          39s   10.0.0.174      k8s1   <none>           <none>
	 cilium-monitoring                                  grafana-59957b9549-dt2wf           1/1     Running   0          42m   10.0.0.95       k8s1   <none>           <none>
	 cilium-monitoring                                  prometheus-7c8c9684bb-cx2hz        1/1     Running   0          42m   10.0.0.52       k8s1   <none>           <none>
	 kube-system                                        cilium-dkv4n                       1/1     Running   0          82s   192.168.56.11   k8s1   <none>           <none>
	 kube-system                                        cilium-dlg5x                       1/1     Running   0          82s   192.168.56.12   k8s2   <none>           <none>
	 kube-system                                        cilium-operator-55d66dfbd8-8j5nn   1/1     Running   0          82s   192.168.56.12   k8s2   <none>           <none>
	 kube-system                                        cilium-operator-55d66dfbd8-wlgbj   1/1     Running   0          82s   192.168.56.13   k8s3   <none>           <none>
	 kube-system                                        coredns-567b6dd84-95bkn            1/1     Running   0          60s   10.0.0.102      k8s1   <none>           <none>
	 kube-system                                        etcd-k8s1                          1/1     Running   0          50m   192.168.56.11   k8s1   <none>           <none>
	 kube-system                                        kube-apiserver-k8s1                1/1     Running   0          50m   192.168.56.11   k8s1   <none>           <none>
	 kube-system                                        kube-controller-manager-k8s1       1/1     Running   0          50m   192.168.56.11   k8s1   <none>           <none>
	 kube-system                                        kube-scheduler-k8s1                1/1     Running   0          50m   192.168.56.11   k8s1   <none>           <none>
	 kube-system                                        log-gatherer-25stp                 1/1     Running   0          42m   192.168.56.11   k8s1   <none>           <none>
	 kube-system                                        log-gatherer-5xlnl                 1/1     Running   0          42m   192.168.56.12   k8s2   <none>           <none>
	 kube-system                                        log-gatherer-8hbbw                 1/1     Running   0          42m   192.168.56.13   k8s3   <none>           <none>
	 kube-system                                        registry-adder-2fcng               1/1     Running   0          43m   192.168.56.13   k8s3   <none>           <none>
	 kube-system                                        registry-adder-7k7pl               1/1     Running   0          43m   192.168.56.11   k8s1   <none>           <none>
	 kube-system                                        registry-adder-h6mcs               1/1     Running   0          43m   192.168.56.12   k8s2   <none>           <none>
	 
Stderr:
 	 

Fetching command output from pods [cilium-dkv4n cilium-dlg5x]
cmd: kubectl exec -n kube-system cilium-dkv4n -c cilium-agent -- cilium service list
Exitcode: 0 
Stdout:
 	 ID   Frontend             Service Type   Backend                            
	 2    10.96.0.1:443        ClusterIP      1 => 192.168.56.11:6443 (active)   
	 3    10.96.0.10:53        ClusterIP      1 => 10.0.0.102:53 (active)        
	 4    10.96.0.10:9153      ClusterIP      1 => 10.0.0.102:9153 (active)      
	 5    10.97.162.80:3000    ClusterIP      1 => 10.0.0.95:3000 (active)       
	 6    10.111.217.95:9090   ClusterIP      1 => 10.0.0.52:9090 (active)       
	 7    10.110.194.203:443   ClusterIP      1 => 192.168.56.12:4244 (active)   
	                                          2 => 192.168.56.11:4244 (active)   
	 8    10.109.88.137:69     ClusterIP      1 => 10.0.0.72:69 (active)         
	                                          2 => 10.0.0.184:69 (active)        
	 9    10.109.88.137:80     ClusterIP      1 => 10.0.0.72:80 (active)         
	                                          2 => 10.0.0.184:80 (active)        
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-dkv4n -c cilium-agent -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                                                                       IPv6       IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                                                                            
	 77         Disabled           Disabled          37509      k8s:app=grafana                                                                                                   fd02::8e   10.0.0.95    ready   
	                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=cilium-monitoring                                                                  
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                                          
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                                                   
	                                                            k8s:io.kubernetes.pod.namespace=cilium-monitoring                                                                                                 
	 254        Disabled           Disabled          65472      k8s:id=app1                                                                                                       fd02::b3   10.0.0.184   ready   
	                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=202211081614k8sagentpolicytestbasictesttlspolicy                                   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                                          
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=app1-account                                                                                              
	                                                            k8s:io.kubernetes.pod.namespace=202211081614k8sagentpolicytestbasictesttlspolicy                                                                  
	                                                            k8s:zgroup=testapp                                                                                                                                
	 445        Disabled           Disabled          28056      k8s:id=app3                                                                                                       fd02::b6   10.0.0.174   ready   
	                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=202211081614k8sagentpolicytestbasictesttlspolicy                                   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                                          
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                                                   
	                                                            k8s:io.kubernetes.pod.namespace=202211081614k8sagentpolicytestbasictesttlspolicy                                                                  
	                                                            k8s:zgroup=testapp                                                                                                                                
	 813        Disabled           Disabled          9074       k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system                                        fd02::3b   10.0.0.102   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                                          
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=coredns                                                                                                   
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                                                                       
	                                                            k8s:k8s-app=kube-dns                                                                                                                              
	 1858       Disabled           Disabled          65472      k8s:id=app1                                                                                                       fd02::50   10.0.0.72    ready   
	                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=202211081614k8sagentpolicytestbasictesttlspolicy                                   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                                          
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=app1-account                                                                                              
	                                                            k8s:io.kubernetes.pod.namespace=202211081614k8sagentpolicytestbasictesttlspolicy                                                                  
	                                                            k8s:zgroup=testapp                                                                                                                                
	 2036       Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s1                                                                                                                ready   
	                                                            k8s:node-role.kubernetes.io/control-plane                                                                                                         
	                                                            k8s:node.kubernetes.io/exclude-from-external-load-balancers                                                                                       
	                                                            reserved:host                                                                                                                                     
	 2163       Disabled           Disabled          4          reserved:health                                                                                                   fd02::37   10.0.0.227   ready   
	 2180       Disabled           Disabled          28297      k8s:appSecond=true                                                                                                fd02::ca   10.0.0.21    ready   
	                                                            k8s:id=app2                                                                                                                                       
	                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=202211081614k8sagentpolicytestbasictesttlspolicy                                   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                                          
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=app2-account                                                                                              
	                                                            k8s:io.kubernetes.pod.namespace=202211081614k8sagentpolicytestbasictesttlspolicy                                                                  
	                                                            k8s:zgroup=testapp                                                                                                                                
	 2391       Disabled           Disabled          23239      k8s:app=prometheus                                                                                                fd02::60   10.0.0.52    ready   
	                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=cilium-monitoring                                                                  
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                                          
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=prometheus-k8s                                                                                            
	                                                            k8s:io.kubernetes.pod.namespace=cilium-monitoring                                                                                                 
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-dlg5x -c cilium-agent -- cilium service list
Exitcode: 0 
Stdout:
 	 ID   Frontend             Service Type   Backend                            
	 1    10.96.0.10:9153      ClusterIP      1 => 10.0.0.102:9153 (active)      
	 2    10.96.0.10:53        ClusterIP      1 => 10.0.0.102:53 (active)        
	 3    10.97.162.80:3000    ClusterIP      1 => 10.0.0.95:3000 (active)       
	 4    10.111.217.95:9090   ClusterIP      1 => 10.0.0.52:9090 (active)       
	 6    10.96.0.1:443        ClusterIP      1 => 192.168.56.11:6443 (active)   
	 7    10.110.194.203:443   ClusterIP      1 => 192.168.56.12:4244 (active)   
	                                          2 => 192.168.56.11:4244 (active)   
	 8    10.109.88.137:80     ClusterIP      1 => 10.0.0.72:80 (active)         
	                                          2 => 10.0.0.184:80 (active)        
	 9    10.109.88.137:69     ClusterIP      1 => 10.0.0.72:69 (active)         
	                                          2 => 10.0.0.184:69 (active)        
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-dlg5x -c cilium-agent -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])   IPv6        IPv4        STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                        
	 310        Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s2                            ready   
	                                                            reserved:host                                                 
	 510        Disabled           Disabled          4          reserved:health               fd02::1b5   10.0.1.76   ready   
	 
Stderr:
 	 

===================== Exiting AfterFailed =====================
16:15:29 STEP: Running AfterEach for block EntireTestsuite K8sAgentPolicyTest Basic Test Traffic redirections to proxy
16:15:29 STEP: Running AfterEach for block EntireTestsuite K8sAgentPolicyTest Basic Test
16:15:29 STEP: Running AfterEach for block EntireTestsuite

[[ATTACHMENT|786aa4b3_K8sAgentPolicyTest_Basic_Test_Traffic_redirections_to_proxy_Tests_HTTP_proxy_visibility_without_policy.zip]]


```
</details>

ZIP Links: 
<details><summary>Click to show.</summary>

 https://jenkins.cilium.io/job/Cilium-PR-K8s-1.25-kernel-net-next//652/artifact/786aa4b3_K8sAgentPolicyTest_Basic_Test_Traffic_redirections_to_proxy_Tests_HTTP_proxy_visibility_without_policy.zip
  https://jenkins.cilium.io/job/Cilium-PR-K8s-1.25-kernel-net-next//652/artifact/863c1002_K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master.zip
  https://jenkins.cilium.io/job/Cilium-PR-K8s-1.25-kernel-net-next//652/artifact/test_results_Cilium-PR-K8s-1.25-kernel-net-next_652_BDD-Test-PR.zip
 
</details>

Jenkins URL: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.25-kernel-net-next/652/

If this is a duplicate of an existing flake, comment 'Duplicate of #\<issue-number>' and close this issue.

### PR DESCRIPTION
**Pull request by pchaigno**
One of our flaky tests has been failing because we can't find the expected flow event in the `hubble observe` output. Looking at the logs revealed that the expected flow event was emitted before our `hubble observe` command running in the background was ready.

This happened because we start `hubble observe` in the background and directly make the test request without waiting [1]. This pull request changes that to ensure `HubbleObserveFollow` (which starts `hubble observe` in the background) waits for Hubble to be ready before returning.

To that end, debug mode is enabled. In that mode, `hubble observe` will the following debug message once connected to the server:

    time="2023-04-21T16:29:45Z" level=debug msg="Sending GetFlows request" request="follow:true whitelist:{event_type:{type:129}}"

We can wait until we see that message to exit from `HubbleObserveFollow`. After that we'll simply call `WaitUntilMatchFilterLineTimeout` as usual, but we'll be sure Hubble was ready when we made the test query.

This works because the debug message is sent over stderr, whereas `WaitUntilMatchFilterLineTimeout` reads from stdout. `WaitUntilMatchTimeout`, the helper function we use to block in `HubbleObserveFollow`, searches for a match in both stdout and stderr.

1 - In that particular flaky test, we were actually waiting 2s, but that wasn't always enough.
Fixes: https://github.com/cilium/cilium/pull/11232.
Fixes: https://github.com/cilium/cilium/issues/22056.

### CODE REVIEW

File: test/helpers/kubectl.go [hunk 1]
```diff
@@ -4328,8 +4328,18 @@ func (kub *Kubectl) HubbleObserve(pod string, args string) *CmdRes {
...
+func (kub *Kubectl) HubbleObserveFollow(ctx context.Context, pod string, args string) (*CmdRes, error) {
+	hubbleRes := kub.ExecPodCmdBackground(ctx, CiliumNamespace, pod, "cilium-agent",
+		fmt.Sprintf("hubble observe --debug --follow --output=jsonpb %s", args))
+	// Wait until we see the following debug log message. This is to ensure
+	// hubble observe is fully ready before returning from HubbleObserveFollow.
+	// We only need to wait for 10s because if the Hubble client can't connect
+	// to the server after 5s, it will error out anyway.
+	err := hubbleRes.WaitUntilMatchTimeout("Sending GetFlows request", 6*time.Second)
+	if err != nil {
+		return hubbleRes, fmt.Errorf("No flows received after timeout: %w", err)
```
Comment (viktor-kurchenko) [inline test/helpers/kubectl.go]: NIT: Usually error message starts in lowercase.

**Review by viktor-kurchenko — APPROVED** [review]
LGTM.

**Review by rolinh — APPROVED** [review]

File: test/helpers/kubectl.go [hunk 2]
```diff
@@ -4328,8 +4328,18 @@ func (kub *Kubectl) HubbleObserve(pod string, args string) *CmdRes {
...
 // HubbleObserveFollow runs `hubble observe --follow --output=jsonpb <args>` on
 // the Cilium pod 'ns/pod' in the background. The process is stopped when ctx is cancelled.
-func (kub *Kubectl) HubbleObserveFollow(ctx context.Context, pod string, args string) *CmdRes {
-	return kub.ExecPodCmdBackground(ctx, CiliumNamespace, pod, "cilium-agent", fmt.Sprintf("hubble observe --follow --output=jsonpb %s", args))
+func (kub *Kubectl) HubbleObserveFollow(ctx context.Context, pod string, args string) (*CmdRes, error) {
+	hubbleRes := kub.ExecPodCmdBackground(ctx, CiliumNamespace, pod, "cilium-agent",
+		fmt.Sprintf("hubble observe --debug --follow --output=jsonpb %s", args))
+	// Wait until we see the following debug log message. This is to ensure
+	// hubble observe is fully ready before returning from HubbleObserveFollow.
+	// We only need to wait for 10s because if the Hubble client can't connect
```
Comment (nebril) [inline test/helpers/kubectl.go]: Nit: 10s in comment, 6s in the code.

**Review by nebril — APPROVED** [review]

**Comment by pchaigno** [comment]
I fixed both nits without rebasing in [the last force push](https://github.com/cilium/cilium/compare/d34b99f3b3814b0af94fdedae2ae2ebc6007bec0..18ed9edd395d2384254ab6f4d6425829992facc3). The end-to-end ginkgo tests were green before that and I don't think we need to rerun them given I only touched an error string and a comment. Merging once linters are passing.
