### PR TITLE
k8s/watchers: Fix race condition in init functions

### LINKED ISSUE #23166: race: between `pkg/k8s/watchers.(*K8sWatcher).NodesInit.func1()` and `pkg/k8s/synced.(*Resources).BlockWaitGroupToSyncResources()`
Observed in:
- https://jenkins.cilium.io/view/Race%20Detection/job/cilium-master-k8s-1.16-kernel-4.9-race-detection/
- https://jenkins.cilium.io/view/Race%20Detection/job/cilium-master-k8s-1.25-kernel-4.19-race-detection/

It happens consistently on all runs, and the latest success we had on both pipelines is December 20. I strongly suspect we merged something around this time that started to cause the issue.

Artifacts example: [8e8573b5_K8sDatapathServicesTest_Checks_E-W_loadbalancing_(ClusterIP,_NodePort_from_inside_cluster,_etc)_Checks_service_on_same_node.zip](https://github.com/cilium/cilium/files/10448652/8e8573b5_K8sDatapathServicesTest_Checks_E-W_loadbalancing_.ClusterIP._NodePort_from_inside_cluster._etc._Checks_service_on_same_node.zip)

Trace:
```
2023-01-07T17:35:16.928043757Z WARNING: DATA RACE
2023-01-07T17:35:16.928045497Z Write at 0x00c0000fb3ff by goroutine 936:
2023-01-07T17:35:16.928047237Z   github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).serviceEventLoop()
2023-01-07T17:35:16.928048925Z       /go/src/github.com/cilium/cilium/pkg/k8s/watchers/service.go:49 +0x24c
2023-01-07T17:35:16.928050584Z   github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).servicesInit.func3()
2023-01-07T17:35:16.928052262Z       /go/src/github.com/cilium/cilium/pkg/k8s/watchers/service.go:27 +0x58
2023-01-07T17:35:16.928053948Z 
2023-01-07T17:35:16.928055665Z Previous read at 0x00c0000fb3ff by goroutine 935:
2023-01-07T17:35:16.928057338Z   github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).servicesInit.func1()
2023-01-07T17:35:16.928059012Z       /go/src/github.com/cilium/cilium/pkg/k8s/watchers/service.go:24 +0x30
2023-01-07T17:35:16.928060742Z   k8s.io/client-go/tools/cache.WaitForCacheSync.func1()
2023-01-07T17:35:16.928062389Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/shared_informer.go:291 +0x7a
2023-01-07T17:35:16.928064099Z   k8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1()
2023-01-07T17:35:16.928065768Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:222 +0x30
2023-01-07T17:35:16.928067475Z   k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext()
2023-01-07T17:35:16.928069229Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:235 +0x7b
2023-01-07T17:35:16.928070955Z   k8s.io/apimachinery/pkg/util/wait.poll()
2023-01-07T17:35:16.928072596Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:582 +0x57
2023-01-07T17:35:16.928074323Z   k8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext()
2023-01-07T17:35:16.928075988Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:547 +0x59
2023-01-07T17:35:16.928077679Z   k8s.io/apimachinery/pkg/util/wait.PollImmediateUntil()
2023-01-07T17:35:16.928079336Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:538 +0x9e
2023-01-07T17:35:16.928081027Z   k8s.io/client-go/tools/cache.WaitForCacheSync()
2023-01-07T17:35:16.928083193Z       /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/shared_informer.go:288 +0xb7
2023-01-07T17:35:16.928084986Z   github.com/cilium/cilium/pkg/k8s/synced.(*Resources).BlockWaitGroupToSyncResources.func1()
2023-01-07T17:35:16.928086681Z       /go/src/github.com/cilium/cilium/pkg/k8s/synced/resources.go:82 +0x22a
2023-01-07T17:35:16.928091346Z 
2023-01-07T17:35:16.928093206Z Goroutine 936 (running) created at:
2023-01-07T17:35:16.928094845Z   github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).servicesInit()
2023-01-07T17:35:16.928096512Z       /go/src/github.com/cilium/cilium/pkg/k8s/watchers/service.go:27 +0x344
2023-01-07T17:35:16.928098180Z   github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).enableK8sWatchers()
2023-01-07T17:35:16.928099994Z       /go/src/github.com/cilium/cilium/pkg/k8s/watchers/watcher.go:556 +0x6e4
2023-01-07T17:35:16.928101670Z   github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).InitK8sSubsystem()
2023-01-07T17:35:16.928103340Z       /go/src/github.com/cilium/cilium/pkg/k8s/watchers/watcher.go:491 +0x10e
2023-01-07T17:35:16.928105072Z   github.com/cilium/cilium/daemon/cmd.newDaemon()
2023-01-07T17:35:16.928106731Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon.go:1079 +0x9497
2023-01-07T17:35:16.928108406Z   github.com/cilium/cilium/daemon/cmd.newDaemonPromise.func1()
2023-01-07T17:35:16.928110075Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1670 +0x244
2023-01-07T17:35:16.928111761Z   github.com/cilium/cilium/pkg/hive.Hook.Start()
2023-01-07T17:35:16.928113459Z       /go/src/github.com/cilium/cilium/pkg/hive/lifecycle.go:35 +0x7a
2023-01-07T17:35:16.928115137Z   github.com/cilium/cilium/pkg/hive.(*Hook).Start()
2023-01-07T17:35:16.928116778Z       <autogenerated>:1 +0x29
2023-01-07T17:35:16.928118740Z   github.com/cilium/cilium/pkg/hive.(*DefaultLifecycle).Start()
2023-01-07T17:35:16.928121718Z       /go/src/github.com/cilium/cilium/pkg/hive/lifecycle.go:104 +0x405
2023-01-07T17:35:16.928123455Z   github.com/cilium/cilium/pkg/hive.(*Hive).Start()
2023-01-07T17:35:16.928125092Z       /go/src/github.com/cilium/cilium/pkg/hive/hive.go:239 +0xeb
2023-01-07T17:35:16.928126753Z   github.com/cilium/cilium/pkg/hive.(*Hive).Run()
2023-01-07T17:35:16.928128426Z       /go/src/github.com/cilium/cilium/pkg/hive/hive.go:167 +0xe9
2023-01-07T17:35:16.928130068Z   github.com/cilium/cilium/daemon/cmd.runApp()
2023-01-07T17:35:16.928131713Z       /go/src/github.com/cilium/cilium/daemon/cmd/root.go:87 +0x128
2023-01-07T17:35:16.928133441Z   github.com/spf13/cobra.(*Command).execute()
2023-01-07T17:35:16.928135077Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:920 +0xc6d
2023-01-07T17:35:16.928136789Z   github.com/spf13/cobra.(*Command).ExecuteC()
2023-01-07T17:35:16.928139020Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:1044 +0x5fa
2023-01-07T17:35:16.928140749Z   github.com/spf13/cobra.(*Command).Execute()
2023-01-07T17:35:16.928142437Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:968 +0xb5
2023-01-07T17:35:16.928144327Z   github.com/cilium/cilium/daemon/cmd.Execute()
2023-01-07T17:35:16.928147513Z       /go/src/github.com/cilium/cilium/daemon/cmd/root.go:99 +0x9e
2023-01-07T17:35:16.928149315Z   main.main()
2023-01-07T17:35:16.928150992Z       /go/src/github.com/cilium/cilium/daemon/main.go:15 +0x24
2023-01-07T17:35:16.928170986Z   runtime.main()
2023-01-07T17:35:16.928172871Z       /usr/local/go/src/runtime/proc.go:250 +0x211
2023-01-07T17:35:16.928174532Z   github.com/cilium/ebpf/btf.init.0()
2023-01-07T17:35:16.928176250Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/btf/marshal.go:24 +0x3c
2023-01-07T17:35:16.928177947Z 
2023-01-07T17:35:16.928179552Z Goroutine 935 (running) created at:
2023-01-07T17:35:16.928181172Z   github.com/cilium/cilium/pkg/k8s/synced.(*Resources).BlockWaitGroupToSyncResources()
2023-01-07T17:35:16.928182851Z       /go/src/github.com/cilium/cilium/pkg/k8s/synced/resources.go:79 +0x3fb
2023-01-07T17:35:16.928184510Z   github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).blockWaitGroupToSyncResources()
2023-01-07T17:35:16.928186198Z       /go/src/github.com/cilium/cilium/pkg/k8s/watchers/watcher.go:375 +0x24d
2023-01-07T17:35:16.928187863Z   github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).servicesInit()
2023-01-07T17:35:16.928189614Z       /go/src/github.com/cilium/cilium/pkg/k8s/watchers/service.go:21 +0x222
2023-01-07T17:35:16.928191250Z   github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).enableK8sWatchers()
2023-01-07T17:35:16.928192922Z       /go/src/github.com/cilium/cilium/pkg/k8s/watchers/watcher.go:556 +0x6e4
2023-01-07T17:35:16.928194589Z   github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).InitK8sSubsystem()
2023-01-07T17:35:16.928196251Z       /go/src/github.com/cilium/cilium/pkg/k8s/watchers/watcher.go:491 +0x10e
2023-01-07T17:35:16.928197914Z   github.com/cilium/cilium/daemon/cmd.newDaemon()
2023-01-07T17:35:16.928199545Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon.go:1079 +0x9497
2023-01-07T17:35:16.928201199Z   github.com/cilium/cilium/daemon/cmd.newDaemonPromise.func1()
2023-01-07T17:35:16.928202948Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1670 +0x244
2023-01-07T17:35:16.928204619Z   github.com/cilium/cilium/pkg/hive.Hook.Start()
2023-01-07T17:35:16.928206260Z       /go/src/github.com/cilium/cilium/pkg/hive/lifecycle.go:35 +0x7a
2023-01-07T17:35:16.928207936Z   github.com/cilium/cilium/pkg/hive.(*Hook).Start()
2023-01-07T17:35:16.928241900Z       <autogenerated>:1 +0x29
2023-01-07T17:35:16.928243946Z   github.com/cilium/cilium/pkg/hive.(*DefaultLifecycle).Start()
2023-01-07T17:35:16.928245605Z       /go/src/github.com/cilium/cilium/pkg/hive/lifecycle.go:104 +0x405
2023-01-07T17:35:16.928247295Z   github.com/cilium/cilium/pkg/hive.(*Hive).Start()
2023-01-07T17:35:16.928248972Z       /go/src/github.com/cilium/cilium/pkg/hive/hive.go:239 +0xeb
2023-01-07T17:35:16.928250629Z   github.com/cilium/cilium/pkg/hive.(*Hive).Run()
2023-01-07T17:35:16.928254445Z       /go/src/github.com/cilium/cilium/pkg/hive/hive.go:167 +0xe9
2023-01-07T17:35:16.928256624Z   github.com/cilium/cilium/daemon/cmd.runApp()
2023-01-07T17:35:16.928258354Z       /go/src/github.com/cilium/cilium/daemon/cmd/root.go:87 +0x128
2023-01-07T17:35:16.928260028Z   github.com/spf13/cobra.(*Command).execute()
2023-01-07T17:35:16.928261618Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:920 +0xc6d
2023-01-07T17:35:16.928263315Z   github.com/spf13/cobra.(*Command).ExecuteC()
2023-01-07T17:35:16.928264966Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:1044 +0x5fa
2023-01-07T17:35:16.928266643Z   github.com/spf13/cobra.(*Command).Execute()
2023-01-07T17:35:16.928268242Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:968 +0xb5
2023-01-07T17:35:16.928269921Z   github.com/cilium/cilium/daemon/cmd.Execute()
2023-01-07T17:35:16.928271570Z       /go/src/github.com/cilium/cilium/daemon/cmd/root.go:99 +0x9e
2023-01-07T17:35:16.928273220Z   main.main()
2023-01-07T17:35:16.928274844Z       /go/src/github.com/cilium/cilium/daemon/main.go:15 +0x24
2023-01-07T17:35:16.928276483Z   runtime.main()
2023-01-07T17:35:16.928278163Z       /usr/local/go/src/runtime/proc.go:250 +0x211
2023-01-07T17:35:16.928279785Z   github.com/cilium/ebpf/btf.init.0()
2023-01-07T17:35:16.928281371Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/btf/marshal.go:24 +0x3c
```

### PR DESCRIPTION
**Pull request by christarazi**
Use an atomic variable as the previous boolean was being passed around
to different goroutines without any synchronization mechanism.

Fixes: b4335eede37 ("k8s: Introduce shared resources")
Fixes: ee2ccdae7f0 ("k8s: Add shared resource for namespaces")
Fixes: https://github.com/cilium/cilium/issues/23166

Signed-off-by: Chris Tarazi <chris@isovalent.com>

### CODE REVIEW

**Comment by christarazi** [comment]
/test-race-1.16-4.9

**Comment by christarazi** [comment]
/test-4.19-race

**Comment by christarazi** [comment]
/test-4.9-race

**Comment by christarazi** [comment]
Found another instance of the same race condition issue, pushing new fix.

**Comment by christarazi** [comment]
/test-4.9-race

**Comment by christarazi** [comment]
/test-4.19-race

**Comment by christarazi** [comment]
CI triage:

* 5.4 hit https://github.com/cilium/cilium/issues/21519
* 4.9-race hit https://github.com/cilium/cilium/issues/15455

Previously, the race pipeline jobs would fail constantly, but now are passing which proves that the data race fix is working as intended.

**Review by joestringer — APPROVED** [review]

File: pkg/k8s/watchers/namespace.go [hunk 1]
```diff
@@ -24,12 +25,13 @@ import (
 func (k *K8sWatcher) namespacesInit() {
 	apiGroup := k8sAPIGroupNamespaceV1Core
 
-	synced := false
+	var synced atomic.Bool
+	synced.Store(false)
```
Comment (tommyp1ckles) [inline pkg/k8s/watchers/namespace.go:29]: this is probably redundant, zero value should be false

**Review by tommyp1ckles — APPROVED** [review]

**Comment by christarazi** [comment]
Marking ready to merge as we have approving reviews and CI passing except for known flakes.

File: pkg/k8s/watchers/namespace.go (hunk 1 above)
Comment (christarazi) [reply pkg/k8s/watchers/namespace.go:29]: Yeah, I opted for explicitness so that when someone fetches all references of the variable, they see an explicit "false" (next to an explicit "true"). It makes it slightly easier to tell how this variable is used.
