### PR TITLE
ipam: Wait for ENI netlink interface before configuring routes

### LINKED ISSUE #37948: CI: failed to configure router IP rules and routes: unable to find ifindex for interface MAC:
## CI failure

https://github.com/cilium/cilium/actions/runs/13589542930/job/37992134419 failed with

```
  ❌ Non-zero (1) restart count of cilium-cilium-13589542930-1.us-east-1.eksctl.io/kube-system/cilium-lkkcp (cilium-agent) must be investigated
```

The crashing agent was:
```
cilium-sysdump-final-1.31-us-east-1-true-true/logs-cilium-lkkcp-cilium-agent-20250228-142302-prev.log:2025-02-28T14:10:42.642691686Z time="2025-02-28T14:10:42.642619218Z" level=fatal msg="failed to start: daemon creation failed: failed to configure router IP rules and routes: unable to find ifindex for interface MAC: interface with MAC 0a:ff:c8:c8:f7:27 not found" subsys=daemon
```

## Sysdump

[cilium-sysdump-final-1.31-us-east-1-true-true.zip](https://github.com/user-attachments/files/19049006/cilium-sysdump-final-1.31-us-east-1-true-true.zip)

### PR DESCRIPTION
**Pull request by pippolo84**
In ENI IPAM mode, the ENIs are created by the operator. At the same
time, on each node, the agents configure the v4 and v6 rules and routes
for the Cilium router, after retrieving its IPs from either k8s or the
filesystem. In order to do so, each agent query netlink to get the
ifindex of the interface with the router IP, given its MAC address.
Unfortunately this behavior is racy, since the agent might query netlink
too soon, when the ENI is not yet up and running. This leads to the
following error from netlink:

"daemon creation failed: failed to configure router IP rules and routes:
unable to find ifindex for interface MAC: interface with MAC ... not
found"

that ultimately stops the daemon startup.

To address this, let's poll netlink and wait for the ENI netlink
interface to show up before going ahead with routes and rules
configuration.

Fixes: #37948

~Depends on https://github.com/cilium/cilium/pull/41783~

### CODE REVIEW

**Comment by pippolo84** [comment]
Completed [15 successful runs](https://github.com/cilium/cilium/actions/runs/18164340118) of `ci-eks` workflow. Opening for reviews.

File: daemon/cmd/ipam.go [hunk 1]
```diff
@@ -146,6 +149,28 @@ func reallocateDatapathIPs(logger *slog.Logger, alloc ipamAllocateIP, fromK8s, f
...
+func waitForENI(ctx context.Context, macAddr string) error {
+	bo := wait.Backoff{
+		Duration: 250 * time.Millisecond,
+		Factor:   2,
+		Jitter:   0.2,
+		Steps:    5,
+	}
+
+	findENIByMAC := func(ctx context.Context) (bool, error) {
+		macs, err := metadata.GetMACs(ctx)
```
Comment (gandro) [inline daemon/cmd/ipam.go]: So the commit message says that netlink might not have discovered the interface yet. But here we are querying the metdata service, which doesn't guarantee that the local kernel actually has attached the interface (i.e. loading the needed driver for the interface can take a few milliseconds, even if the hypervisor has attached it). 

While this makes the race far less likely, I do wonder if we should query netlink here instead and ensure that the expected mac address shows up in `netlink.LinkList()`.

**Review by gandro — COMMENTED** [review]
Thanks for the fix! One question/comment w.r.t. the approach

File: daemon/cmd/ipam.go (hunk 1 above)
Comment (liyihuang) [reply daemon/cmd/ipam.go]: Just put my 2 cents here, I found this implementation in AWS CNI. That's why I suggested this way. I guess the race conditions happened from AWS operations than kernel. I guess it's because ENI attachement happens async from operator and got the MAC address. Then agent picks it up from CR.

Comment (gandro) [reply daemon/cmd/ipam.go]: Right, thanks for the context. I'm also saying this because for non-router ENIs we actually check the netlink interfaces, not the metadata service before we try to allocate from it:

https://github.com/cilium/cilium/blob/de893e6330cc5b0d4b8fbc3d839a6b54a96c0733/pkg/ipam/crd_eni.go#L75-L92

Comment (gandro) [reply daemon/cmd/ipam.go]: Maybe we could also execute the above code not in the background, but always before we hand out IPs for a newly attached ENI. That way we wouldn't have to change `allocateDatapathIPs` and instead have the IPAM subsystem guarantee that whenever a we allocate an IP that the corresponding host interface is attached and ready.

Comment (pippolo84) [reply daemon/cmd/ipam.go]: Discussed this offline with @gandro . We decided to keep it simple for now and change `allocateDatapathIPs` to wait for the netlink interface to show up. I've updated the PR but kept the first commit since it was an useful improvement to the aws metadata client (though it is not needed for the fix anymore).

Comment (pippolo84) [reply daemon/cmd/ipam.go]: I'll also open an issue to keep track of the approach suggested by @gandro since it is a nicer solution in the long term.

**Review by gandro — APPROVED** [review]

**Comment by pippolo84** [comment]
@thorn3r Gentle ping for the review :pray:

**Comment by pippolo84** [comment]
Removed review request to Tim since sig-agent has been covered by Sebastian

**Comment by pippolo84** [comment]
- ci-e2e-upgrade failures tracked in https://github.com/cilium/cilium/issues/42100 and https://github.com/cilium/cilium/issues/42101
- ci-ipsec-e2e tracked in https://github.com/cilium/cilium/issues/41012
