### PR TITLE
Fix cilium-operator regressions

### LINKED ISSUE #9572: Potential master regression in cilium-operator with clustermesh
A user reported on Slack that the operator would not start up, logs like this:

https://cilium.slack.com/archives/C53TG4J4R/p1573085478010800

```
level=info msg="Cilium Operator 1.6.90 a5f496448 2019-10-30T12:31:14-04:00 go version go1.13.3 linux/amd64" subsys=cilium-operator
level=info msg="Establishing connection to apiserver" host="https://100.65.0.1:443" subsys=k8s
level=info msg="Starting apiserver on address :9234" subsys=cilium-operator
level=info msg="Connected to apiserver" subsys=k8s
level=info msg="Retrieved node information from kubernetes" nodeName=ip-10-100-1-228.ec2.internal subsys=k8s
level=info msg="Received own node information from API server" ipAddr.ipv4=10.100.1.228 ipAddr.ipv6="<nil>" nodeName=ip-10-100-1-228.ec2.internal subsys=k8s v4Prefix=100.64.4.0/24 v6Prefix="<nil>"
level=info msg="Starting to synchronize k8s services to kvstore..." subsys=cilium-operator
level=info msg="cilium-operator running with service synchronization: automatic etcd service translation enabled" address= kvstore=etcd subsys=cilium-operator
level=info msg="Waiting for all services to be synced with kubernetes before connecting to etcd" address= kvstore=etcd subsys=cilium-operator
level=fatal msg="Unable to start status api: http: Server closed" subsys=cilium-operator
```

I don't have timestamps for it.

When I suggested downgrading `operator` from `latest` to `1.6.3`, the operator started up fine.

### LINKED ISSUE #9819: cilium-operator startup hang syncing more than 128 services to kvstore
## Bug report

**General Information**

- Cilium version 1.6.5
- Kernel version 4.15.0-70-generic #79~16.04.1-Ubuntu SMP
- Orchestration system version in use Kubernetes v1.14.6
- Link to relevant artifacts (policies, deployments scripts, ...)
- Upload a system dump (run `curl -sLO
releases.cilium.io/tools/cluster-diagnosis.zip &&
python cluster-diagnosis.zip sysdump` and then attach the generated zip file)

**How to reproduce the issue**

1. Run cilium-operator on cluster with more than 128 services and with 

```
  kvstore: etcd
  kvstore-opt: '{"etcd.config": "/var/lib/etcd-config/etcd.config", "etcd.operator": "true"}'
```

cilium-operator logs 129 occurrences of `msg="Received service addition &Service{` and then logs nothing until it is killed by the failing liveness check.

Analysis:

`defaults.K8sServiceCacheSize`, which is used to size the channel `k8s.ServiceCache.Event` is 128. It seems likely that `k8s.ServiceCache.UpdateService()` is deadlocking sending to a full channel whose reader won't start until it finishes syncing the service cache.

### PR DESCRIPTION
**Pull request by aanm**
This PR fixes some regressions found in cilium-operator.

Fixes: #9819
Fixes: #9572

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10010)

```release-note
Fix cilium-operator deadlock for clusters with more than 128 services
```

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

File: pkg/k8s/service.go [hunk 1]
```diff
@@ -432,9 +432,9 @@ func CreateCustomDialer(b BackendIPGetter, log *logrus.Entry) func(s string, dur
 		if err == nil {
 			svc := ParseServiceIDFrom(u.Host)
 			if svc != nil {
-				backendIP := b.GetRandomBackendIP(*svc)
-				if backendIP != nil {
-					s = backendIP.String()
+				svcIP := b.GetServiceIP(*svc)
```
Comment (joestringer) [inline pkg/k8s/service.go:435]: 🤯

Do we need to fix up the comments above this outer function and the inner function here?

File: pkg/kvstore/etcd_test.go [hunk 2]
```diff
@@ -1564,3 +1565,57 @@ func (e *EtcdLockedSuite) TestListPrefixIfLocked(c *C) {
...
+				address: "http://foo.bar",
+			},
+			wantSvcName:   "foo",
+			wantNamespace: "bar",
+			wantErr:       false,
+		},
+		{
+			name: "test-3",
+			args: args{
+				address: "http://foo",
```
Comment (joestringer) [inline pkg/kvstore/etcd_test.go:1608]: What do we accept for `[optional]` at the end? ports, paths, ...? I guess in the end we just use `url.Parse()` so not a big deal to test, but it would provide examples in our tree if we had unit tests.

File: operator/k8s_service_sync.go [hunk 3]
```diff
@@ -205,12 +205,12 @@ func startSynchronizingServices() {
 	go func() {
 		cache.WaitForCacheSync(wait.NeverStop, svcController.HasSynced)
 		swgSvcs.Stop()
+		swgSvcs.Wait()
+		close(k8sSvcCacheSynced)
```
Comment (joestringer) [inline operator/k8s_service_sync.go:209]: So we don't have anywhere relying on this channel to guarantee that endpoints are now synced?

Comment (aanm) [reply operator/k8s_service_sync.go:209]: No, I've checked. I also did not change the name of the channel because it says "svc cache synced" not "svc and eps caches synced"

File: pkg/kvstore/etcd_test.go (hunk 2 above)
Comment (aanm) [reply pkg/kvstore/etcd_test.go:1608]: add unit tests

**Comment by aanm** [comment]
test-me-please

File: pkg/kvstore/etcd.go [hunk 4]
```diff
@@ -1343,6 +1343,23 @@ func (e *etcdClient) ListAndWatch(ctx context.Context, name, prefix string, chan
 	return w
 }
 
+// GetSvcNamespace returns the service name and namespace for the given address.
+// If the given address is not parseable or it is not the format
+// '<protocol://><name>.<namespace>[optional]', returns an error.
+func GetSvcNamespace(address string) (string, string, error) {
```
Comment (tgraf) [inline pkg/kvstore/etcd.go]: Call this `SplitK8sServiceURL` or similar to indicate that this is a string splitting function.

File: operator/k8s_service_sync.go [hunk 5]
```diff
@@ -369,3 +370,18 @@ func endpointSlicesInit(k8sClient kubernetes.Interface, serEps *serializer.Funct
 
 	return nil, false
 }
+
+// serviceGetter is used to hijack the main k8sCache until it is synchronized.
```
Comment (tgraf) [inline operator/k8s_service_sync.go]: I don't understand this comment.

File: operator/k8s_service_sync.go [hunk 6]
```diff
@@ -369,3 +370,18 @@ func endpointSlicesInit(k8sClient kubernetes.Interface, serEps *serializer.Funct
...
+type serviceGetter struct {
+	shortCutK8sCache k8s.ServiceIPGetter
+	k8sCache         k8s.ServiceIPGetter
+}
+
+func (s *serviceGetter) GetServiceIP(svcID k8s.ServiceID) *loadbalancer.L3n4Addr {
```
Comment (tgraf) [inline operator/k8s_service_sync.go:386]: Please add a comment describing the shortcut behavior

**Review by tgraf — CHANGES_REQUESTED** [review]
Looks good in general. Small changes needed to make sure we still understand this 6 months from now.

**Comment by aanm** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]

**Comment by johngmyers** [comment]
I hope this is being backported to 1.6. It is blocking our upgrade from 1.5.x.

**Comment by aanm** [comment]
@johngmyers Can you try out `v1.7.0-rc3`? Thanks

**Comment by johngmyers** [comment]
I tried upgrading a test cluster from v1.5.11 to v1.7.0-rc3.

cilium-operator no longer hangs. It continues to produce log output and is not restarting. I did see the following errors during the time between when I upgraded cilium-operator and when I upgraded the agent:

```
level=error msg=k8sError error="github.com/cilium/cilium/operator/ccnp_event.go:133: Failed to list *v2.CiliumClusterwideNetworkPolicy: the server could not find the requested resource (get ciliumclusterwidenetworkpolicies.cilium.io)" subsys=k8s
```

That appears unrelated to this PR and the error went away after upgrading the agent.

The agents all report a value of "1" for cilium_controllers_failing. I saw in their logs the message:

```
level=debug msg="Controller run failed" consecutiveErrors=47 error="error dumping ipcache BPF map: Unable to get next key from map with file descriptor 7: errno 524" name=ipcache-bpf-garbage-collection subsys=controller uuid=[REDACTED]
```

I have not have time to diagnose, but it also seems likely to be unrelated to this PR.

**Comment by aanm** [comment]
> I tried upgrading a test cluster from v1.5.11 to v1.7.0-rc3.
> 
> cilium-operator no longer hangs. It continues to produce log output and is not restarting. I did see the following errors during the time between when I upgraded cilium-operator and when I upgraded the agent:
> 
> ```
> level=error msg=k8sError error="github.com/cilium/cilium/operator/ccnp_event.go:133: Failed to list *v2.CiliumClusterwideNetworkPolicy: the server could not find the requested resource (get ciliumclusterwidenetworkpolicies.cilium.io)" subsys=k8s
> ```
> 
> That appears unrelated to this PR and the error went away after upgrading the agent.
> 
> The agents all report a value of "1" for cilium_controllers_failing. I saw in their logs the message:
> 
> ```
> level=debug msg="Controller run failed" consecutiveErrors=47 error="error dumping ipcache BPF map: Unable to get next key from map with file descriptor 7: errno 524" name=ipcache-bpf-garbage-collection subsys=controller uuid=[REDACTED]
> ```
> 
> I have not had time to diagnose, but it also seems likely to be unrelated to this PR.

@johngmyers thanks for giving it a shot. With regarding the operator, it is not enough to change the cilium image version as one also needs to update the associated RBAC for cilium and cilium-operator.

**Comment by johngmyers** [comment]
I believe I did update the associated RBAC.

From the RBAC it looks like it is cilium, not cilium-operator that installs the CRD. So in the time between when I updated cilium-operator and the time I updated cilium, cilium-operator was trying to list resources for which the CRD was not yet installed.

It seems a little odd to give a pod on each and every node on the cluster the rights to install new CRDs. I would think that function would be better put in the operator.

I also find it odd that the cilium agents are given the right to create and modify network policies.
