### PR TITLE
 Parses the IP addr passed as CIDR from the delegated IPAM and then use the IP addr from the parsed prefix.

### LINKED ISSUE #22917: Regression in latest cilium as it doesn't support IPAddress with CIDR notation from delegated ipam
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When using Cilium 1.13 with azure-ipam and CNS I ran into an issue with the ip addresses passed from the azure-ipam. The issue was originally tested on a dualstack cluster producing this error:

`Output when trying to run a dual stack AKS cluster
to setup network for sandbox "bba8210c502144b0ce2983a5ebedc7c18f63f3cceaaca5308b98b6b0715704f1": plugin type="cilium-cni" failed (add): unable to prepare IP addressing for 'fd12:1234::1f7/112': ParseAddr("fd12:1234::1f7/112"): unexpected character, want colon (at "/112")`

when tested and found on a single stack v4 cluster with the following error:

`Output when trying to run a dual stack AKS cluster
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "5604fb6b5175dd7135a21d3a8c2b8e9299f9f0b247a8eb6635103cd12d6f5e5d": plugin type="cilium-cni" failed (add): unable to prepare IP addressing for '192.168.3.31/16': ParseAddr("192.168.3.31/16"): unexpected character (at "/16")`

This issue is related to the addition of netip into Cilium and this specific issue is appearing from line 293 of plugins/cilium-cni/main.go in the following commit: https://github.com/cilium/cilium/commit/5755c583526a1d7364ce2921e281a0b8fb08ec4c#diff-87793c7d9c6d6a10f34d6a3efefed53dac8abd700cb05cfb2a77844ec990b744R293

### Cilium Version

1.13.90

### Kernel Version

5.4.0-1094-azure

### Kubernetes Version

1.25.2

### Sysdump

_No response_

### Relevant log output

```shell
Output when trying to run a dual stack AKS cluster
to setup network for sandbox "bba8210c502144b0ce2983a5ebedc7c18f63f3cceaaca5308b98b6b0715704f1": plugin type="cilium-cni" failed (add): unable to prepare IP addressing for 'fd12:1234::1f7/112': ParseAddr("fd12:1234::1f7/112"): unexpected character, want colon (at "/112")

Output when trying to run a dual stack AKS cluster
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "5604fb6b5175dd7135a21d3a8c2b8e9299f9f0b247a8eb6635103cd12d6f5e5d": plugin type="cilium-cni" failed (add): unable to prepare IP addressing for '192.168.3.31/16': ParseAddr("192.168.3.31/16"): unexpected character (at "/16")
```

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by vipul-21**
Fixes: #22917 
Parses the ipaddress passed as CIDR from the delegated Ipam. And then use the ipaddress from the parsed prefix.

---

Fixes: https://github.com/cilium/cilium/pull/21421

### CODE REVIEW

**Comment by christarazi** [comment]
@vipul-21 Could you move the "Fixes ..." out from the commit title and into the commit msg itself? This will resolve the checkpatch failure in the CI.

**Comment by christarazi** [comment]
CI is failing with 

```
  message: 'Failed to create pod sandbox: rpc error: code = Unknown desc = failed
    to setup network for sandbox "fa6a4caa47ec2fddf932d3a5302381c76201298b36ca73df188a98fcd4b20ad1":
    unable to prepare IP addressing for ''fd00:10:244:0:1::d616'': netip.ParsePrefix("fd00:10:244:0:1::d616"):
    no ''/'''
```

now

**Comment by vipul-21** [comment]
> ```
> Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "fa6a4caa47ec2fddf932d3a5302381c76201298b36ca73df188a98fcd4b20ad1": unable to prepare IP addressing for ''fd00:10:244:0:1::d616'': netip.ParsePrefix("fd00:10:244:0:1::d616"): no ''/''
> ```

Is there a way I can run these test locally ?

**Comment by christarazi** [comment]
I would suggest following https://docs.cilium.io/en/v1.12/gettingstarted/k8s-install-default/ as it seems like a general failure in creating any pod.

File: plugins/cilium-cni/main.go [hunk 1]
```diff
@@ -288,9 +288,16 @@ func prepareIP(ipAddr string, state *CmdState, mtu int) (*cniTypesV1.IPConfig, [
...
+		ip     netip.Addr
 	)
 
-	ip, err := netip.ParseAddr(ipAddr)
+	ipPrefix, err := netip.ParsePrefix(ipAddr)
+	if err != nil {
+		ip, err = netip.ParseAddr(ipAddr)
+	} else {
+		ip = ipPrefix.Addr()
+	}
```
Comment (christarazi) [inline plugins/cilium-cni/main.go:301]: Could you add a small code comment explaining why this is necessary?

File: plugins/cilium-cni/main.go [hunk 2]
```diff
@@ -547,7 +554,7 @@ func cmdAdd(args *skel.CmdArgs) (err error) {
 	}
 
 	if ipv4IsEnabled(ipam) {
-		ep.Addressing.IPV4 = ipam.Address.IPV4
+		ep.Addressing.IPV4 = ipam.IPV4.IP
```
Comment (christarazi) [inline plugins/cilium-cni/main.go]: Why is this change necessary?

Comment (vipul-21) [reply plugins/cilium-cni/main.go]: My bad this is not necessary. I was testing something. Let me remove this.

File: plugins/cilium-cni/main.go (hunk 1 above)
Comment (vipul-21) [reply plugins/cilium-cni/main.go:301]: Sure

Comment (vipul-21) [reply plugins/cilium-cni/main.go:301]: For context, I used the same logic as it was before: https://github.com/cilium/cilium/blob/c7516b9734a3c69db468dbacb34091347241cd47/pkg/addressing/ip.go#L102

**Comment by vipul-21** [comment]
> K8sDatapathConfig

Seems like the issue might be a flaky one. Can we retry this ? 
I'll try to replicate the issue locally.

**Comment by christarazi** [comment]
@vipul-21 No need to reproduce locally. It seems that the CI failures are flakes.

**Review by christarazi — APPROVED** [review]

**Review by nathanjsweet — APPROVED** [review]

**Comment by vipul-21** [comment]
@christarazi @nathanjsweet Thanks for the review and approval. Can we merge the PR ?

**Comment by joestringer** [comment]
I've marked this for backport since it seems to address a regression in 1.13.x in the delegated IPAM area.
