### PR TITLE
daemon: Fix detection of BPF/XDP NodePort, BPF masq and host-fw devices

### LINKED ISSUE #11789: Make Cilium list of devices clearly and consistently apply functionality across those devices
Per discussion from sig-datapath 2020-05-20:

Goal: User-friendly
* Easy to explain
* Easy to observe
* Out-of-the-box for common cloud options
  * Use default route,
  * K8s node IP

Feature enablement per-device:
  * Host fw
    * Always enable if CLI flag specified
  * XDP
    * Only select devices with native XDP support
    * User must specify flag to enable feature, autodetect device
    * How to override device?
  * Masquerade
    * Should be run on device with default route
    * Primary use: delivering when source is not routable
    * Currently relies on nodeport implementation. Desire to split out but not feasible for v1.8.
    * Autodetect based on default route
      * `--egress-masquerade-interfaces` to override
        * V1.8 known limitation: Will autoenable nodeport on this device. We can improve this in v1.9.
  * Nodeport
    * Should be run on devices where in-cluster communication is performed
    * Detect based on devices with k8s IPs in use, apply there. OR user specifies --devices=...

The above is copied from the meeting notes; @brb should have more context but if any of the above is ambiguous then let's discuss on-issue.

### PR DESCRIPTION
**Pull request by brb**
First, this PR extends the BPF NodePort device auto-detection mechanism by:

1. In addition to a device with a default route, it considers a device with k8s Node IP addr. The k8s Node IP addr is derived from the self Node object, and it's either `InternalIP` or `ExternalIP` or `nil` (the former is preferred).
2. BPF NodePort direct routing device can be automatically detected (previously, it was the first device among all BPF NodePort devices). If there is only one BPF NodePort device is set, then that device is used for the direct routing. Otherwise, the k8s Node IP device is used. Users can specify the device via `--direct-routing-device` (`global.nodePort.directRoutingDevice`).
3. Enables XDP on the direct routing device (see reasoning in the commit msg).

The detected devices by 1. are used for BPF masquerading and host-fw too.

Second, this PR introduces `--devices` flag and deprecated `--device`. If the latter is specified, its value is appended to the former.

Reviewable per commit.

One limitation which hasn't been resolved in this PR, is that if in the k8s dualstack mode InternalIPv4 and InternalIPv6 are assigned to two different devices, then only one will be considered. I'm going to address it in a separate PR (not a release blocker).

Once this PR is merged, I will move `initKubeProxyReplacement()` to `daemon/cmd/kube_proxy.go` (I didn't want to move in this PR to avoid complicating the reviewing).

Fix: https://github.com/cilium/cilium/issues/11789

### CODE REVIEW

**Comment by brb** [comment]
retest-net-next

**Comment by brb** [comment]
retest-net-next

**Comment by brb** [comment]
retest-net-next

**Comment by brb** [comment]
retest-net-next

**Comment by brb** [comment]
retest-net-next

**Comment by brb** [comment]
retest-net-next

**Comment by brb** [comment]
retest-net-next

**Comment by brb** [comment]
retest-net-next

File: pkg/node/types/node.go [hunk 1]
```diff
@@ -223,6 +223,26 @@ func (n *Node) getNodeIP(ipv6 bool) (net.IP, addressing.AddressType) {
...
+		} else if addr.Type == addressing.NodeExternalIP {
+			externalIP = addr.IP
+		}
+	}
+
+	if externalIP != nil {
+		return externalIP
+	}
+
+	return nil
```
Comment (aanm) [inline pkg/node/types/node.go]: can be `return externalIP`

File: pkg/option/config.go [hunk 2]
```diff
@@ -2146,7 +2154,24 @@ func (c *DaemonConfig) Populate() {
...
+				if d == device {
+					found = true
+					break
+				}
+			}
+			if !found {
+				c.Devices = append(c.Devices, device)
+			}
+		}
+	}
```
Comment (aanm) [inline pkg/option/config.go]: Please write this in a function

File: daemon/cmd/daemon_main.go [hunk 3]
```diff
@@ -253,9 +253,17 @@ func init() {
 	flags.StringSlice(option.DebugVerbose, []string{}, "List of enabled verbose debug groups")
 	option.BindEnv(option.DebugVerbose)
 
-	flags.StringSliceP(option.Device, "d", []string{}, "List of devices facing cluster/external network for attaching bpf_netdev (first device should be one used for direct routing if tunneling is disabled)")
+	flags.StringP(option.Device, "d", "",
+		fmt.Sprintf("Device facing cluster/external network for attaching bpf_host. Deprecated in favor of --%s", option.Devices))
+	flags.MarkHidden(option.Device)
```
Comment (aanm) [inline daemon/cmd/daemon_main.go]: also `flags.MarkDeprecated(option.Device, "This option is no longer supported and will be removed in v1.10")`

File: pkg/node/types/node.go (hunk 1 above)
Comment (brb) [reply pkg/node/types/node.go]: I wanted to make it more visible that `nil` can be returned as well.

File: daemon/cmd/daemon_main.go (hunk 3 above)
Comment (brb) [reply daemon/cmd/daemon_main.go]: It's supported, but it will be removed. Anyway, will add an description.

**Comment by brb** [comment]
test-me-please

File: daemon/cmd/kubeproxy_replacement_test.go [hunk 4]
```diff
@@ -0,0 +1,165 @@
...
+func (s *KubeProxySuite) SetUpSuite(c *C) {
+	var err error
+
+	s.prevConfigDevices = option.Config.Devices
+	s.prevConfigDirectRoutingDevice = option.Config.DirectRoutingDevice
+	s.prevConfigEnableIPv4 = option.Config.EnableIPv4
+	s.prevConfigEnableIPv6 = option.Config.EnableIPv6
+	s.prevK8sNodeIP = node.GetK8sNodeIP()
+
+	s.currentNetNS, err = netns.Get()
```
Comment (christarazi) [inline daemon/cmd/kubeproxy_replacement_test.go:54]: These operations likely need to be protected by locking the goroutine to the thread via `runtime.LockOSThread`. See [netns's docs](https://pkg.go.dev/github.com/vishvananda/netns?tab=doc) for more information. See fc7716622f5d1b11753e5815472fac15ee359d61 for an example.

Relevant snippet:

> Package netns allows ultra-simple network namespace handling. NsHandles can be retrieved and set. Note that the current namespace is thread local so actions that set and reset namespaces should use LockOSThread to make sure the namespace doesn't change due to a goroutine switch. It is best to close NsHandles when you are done with them. This can be accomplished via a `defer ns.Close()` on the handle. Changing namespaces requires elevated privileges, so in most cases this code needs to be run as root.

**Review by christarazi — CHANGES_REQUESTED** [review]
Looks good to me, I reviewed code I'm familiar with, so didn't get to all of it. Minor comment below

File: pkg/node/types/node.go (hunk 1 above)
Comment (joestringer) [reply pkg/node/types/node.go]: Doesn't the function comment already describe this? And the declaration of the stack implies potential lack of initialization? (I don't overly care)

File: pkg/node/address.go [hunk 5]
```diff
@@ -455,3 +451,13 @@ func SetIPsecKeyIdentity(id uint8) {
...
 }
+
+// GetK8sNodeIPs returns k8s Node IP addr.
+func GetK8sNodeIP() net.IP {
+	return k8sNodeIP
+}
+
+// SetK8sNodeIP sets k8s Node IP addr.
+func SetK8sNodeIP(ip net.IP) {
+	k8sNodeIP = ip
```
Comment (joestringer) [inline pkg/node/address.go:462]: Do we need some kind of synchronization here?

File: pkg/k8s/init.go [hunk 6]
```diff
@@ -196,6 +196,10 @@ func GetNodeSpec() error {
 		if option.Config.K8sRequireIPv4PodCIDR || option.Config.K8sRequireIPv6PodCIDR {
 			return fmt.Errorf("node name must be specified via environment variable '%s' to retrieve Kubernetes PodCIDR range", k8sConst.EnvNodeNameSpec)
 		}
+		if option.Config.KubeProxyReplacement != option.KubeProxyReplacementDisabled {
+			log.Info("K8s node name is empty. BPF NodePort might not be able to auto detect " +
+				"devices (if not specified)")
```
Comment (joestringer) [inline pkg/k8s/init.go]: Can we check `devices` to see if it's specified to clarify this info message further?

File: pkg/k8s/init.go [hunk 7]
```diff
@@ -228,6 +232,9 @@ func GetNodeSpec() error {
 		}
 
 		node.SetLabels(n.Labels)
+
+		// K8s Node IP is used by BPF NodePort devices auto-detection
+		node.SetK8sNodeIP(n.GetK8sNodeIP())
```
Comment (joestringer) [inline pkg/k8s/init.go]: What's the implication if we don't hit this case and instead fall through to the else below? 

I feel like the managed clouds were more likely to hit the `}else{` case below, but I'm not particularly familiar with this code.

File: install/kubernetes/cilium/charts/config/templates/configmap.yaml [hunk 8]
```diff
@@ -370,8 +370,14 @@ data:
 {{- if .Values.global.nodePort.range }}
   node-port-range: {{ .Values.global.nodePort.range | quote }}
 {{- end }}
+{{- if .Values.global.nodePort.devices }}
+  devices: {{ join " " .Values.global.nodePort.devices | quote }}
+{{- end }}
 {{- if .Values.global.nodePort.device }}
-  device: {{ join " " .Values.global.nodePort.device | quote }}
+  device: {{ .Values.global.nodePort.device | quote }}
```
Comment (joestringer) [inline install/kubernetes/cilium/charts/config/templates/configmap.yaml:380]: Should this just use `devices` since `--device` is deprecated?

File: daemon/cmd/daemon_test.go [hunk 9]
```diff
@@ -12,7 +12,7 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.
 
-// +build !privileged_tests
+// +build linux,privileged_tests
```
Comment (joestringer) [inline daemon/cmd/daemon_test.go]: IMO this is unfortunate, would be nice to mock out `bpftool` for this kind of testing if that's the constraining aspect here. I recognize that might not be a small task though.

**Review by joestringer — COMMENTED** [review]
First pass comments, I mainly looked at the logic outside of `daemon/` so far.

File: pkg/node/address.go (hunk 5 above)
Comment (joestringer) [reply pkg/node/address.go:462]: (Could/Should it be able to change over time?)

File: daemon/cmd/kubeproxy_replacement_test.go (hunk 4 above)
Comment (christarazi) [reply daemon/cmd/kubeproxy_replacement_test.go:54]: Ah, noticed that you already do this in the code. I suggest moving the locking to the setup before each test using `SetUpTest` and unlocking in `TearDownTest`. I recognize that there's only one test right now, but if someone later expands on this suite, there's a risk they may forget, so having the locking/unlocking in the setups/teardowns would mitigate this.

File: daemon/cmd/kubeproxy_replacement_test.go [hunk 10]
```diff
@@ -0,0 +1,165 @@
...
+	if err := netlink.AddrAdd(link, &netlink.Addr{IPNet: ipnet}); err != nil {
+		return err
+	}
+
+	if err := netlink.LinkSetUp(link); err != nil {
+		return err
+	}
+
+	return nil
+}
```
Comment (christarazi) [inline daemon/cmd/kubeproxy_replacement_test.go:147]: There's very similar code in `pkg/datapath/linux/routing` as well, and probably elsewhere too. If you have the time, it'd be nice to consolidate the implementation in the code. Non-blocking comment tho.

File: pkg/node/address.go [hunk 11]
```diff
@@ -44,6 +44,9 @@ var (
 	ipv4AllocRange      *cidr.CIDR
 	ipv6AllocRange      *cidr.CIDR
 
+	// k8s Node IP (either InternalIP or ExternalIP or nil; the former is prefered)
```
Comment (christarazi) [inline pkg/node/address.go:47]: Nit: could you update the copyright year? (Github UI doesn't let me select unchanged lines.)

File: pkg/option/config.go [hunk 12]
```diff
@@ -2450,6 +2460,26 @@ func (c *DaemonConfig) Populate() {
...
+			for _, d := range c.Devices {
+				if d == device {
+					found = true
+					break
+				}
+			}
+			if !found {
+				c.Devices = append(c.Devices, device)
+			}
+		}
```
Comment (christarazi) [inline pkg/option/config.go]: Nit: non-blocking comment--to keep the code less indented, you could return out of the `if` statement, and convert the `else` block to simply fallthrough

File: daemon/cmd/daemon_test.go (hunk 9 above)
Comment (brb) [reply daemon/cmd/daemon_test.go]: Totally agree. Actually found a way how to avoid marking the suite as privileged and without mocking bpftool: https://github.com/cilium/cilium/pull/11894/commits/d8571facd67a3735eb1117b52e9c173a96a03053.

File: pkg/node/address.go (hunk 5 above)
Comment (brb) [reply pkg/node/address.go:462]: For now noup, as getting the val happens after setting it.

File: install/kubernetes/cilium/charts/config/templates/configmap.yaml (hunk 8 above)
Comment (brb) [reply install/kubernetes/cilium/charts/config/templates/configmap.yaml:380]: I don't have any strong opinion on this, but we currently merge both vals in `populateDevices()` in the agent for the backward compatibility. WDYT?

File: pkg/k8s/init.go (hunk 7 above)
Comment (brb) [reply pkg/k8s/init.go]: Good concern. The `else` case will be hit, if it cannot retrieve (Cilium)Node object during the first request when both `--k8s-require-ipv{4,6}-pod-cidr` are disabled. I think it is possible only on a very busy clusters in which kube-apiserver is overloaded.

If it happens, then only a device with a default route will be able to be selected for BPF NodePort (behavior of the auto-detect in v1.6 and v1.7).

Anyway, I'm going to change `retrieveNodeInformation()` in a way that it keeps waiting for the node object if the auto-detection is required. Mainly, to avoid situations when bpf_host.o is attached to a k8s Node device only on some nodes in a busy cluster.

Comment (brb) [reply pkg/k8s/init.go]: Resolved in 8bf878063d6224f9382d5859e3e5bdb7872fb4a0.

File: daemon/cmd/kubeproxy_replacement_test.go (hunk 10 above)
Comment (brb) [reply daemon/cmd/kubeproxy_replacement_test.go:147]: Yeah, it makes sense to consolidate both suites. Once this PR is merged, I will create a good-first-issue for it.

File: daemon/cmd/kubeproxy_replacement_test.go (hunk 4 above)
Comment (brb) [reply daemon/cmd/kubeproxy_replacement_test.go:54]: Moving the locking to `SetUpTest` is IMHO error prone, as it's up to a testing framework to decide whether to run each test case in the same goroutine, and this might be not visible to a developer. If it end up running the test case in a different goroutine, then subtle bugs might be introduced, see https://www.weave.works/blog/linux-namespaces-golang-followup on this topic.

File: daemon/cmd/daemon.go [hunk 13]
```diff
@@ -413,6 +416,52 @@ func NewDaemon(ctx context.Context, dp datapath.Datapath) (*Daemon, *endpointRes
...
+	if option.Config.EnableIPMasqAgent {
+		if !option.Config.EnableIPv4 {
+			log.Fatalf("BPF ip-masq-agent requires IPv4 support (--%s=\"true\")", option.EnableIPv4Name)
+		}
+		if !probe.HaveFullLPM() {
+			log.Fatal("BPF ip-masq-agent needs kernel 4.16 or newer")
+		}
+	}
+	if option.Config.EnableHostFirewall && len(option.Config.Devices) == 0 {
+		device, err := linuxdatapath.NodeDeviceNameWithDefaultRoute()
```
Comment (brb) [inline daemon/cmd/daemon.go:461]: I left this to make the host-fw to work when BPF NodePort is disabled.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
net-next hit https://github.com/cilium/cilium/pull/11942.

**Comment by brb** [comment]
4.9 hit #10031 :-/

**Comment by brb** [comment]
retest-4.9

**Comment by brb** [comment]
retest-4.9

File: install/kubernetes/cilium/charts/config/templates/configmap.yaml [hunk 14]
```diff
@@ -370,8 +370,14 @@ data:
 {{- if .Values.global.nodePort.range }}
   node-port-range: {{ .Values.global.nodePort.range | quote }}
 {{- end }}
+{{- if .Values.global.nodePort.devices }}
+  devices: {{ join " " .Values.global.nodePort.devices | quote }}
+{{- end }}
```
Comment (pchaigno) [inline install/kubernetes/cilium/charts/config/templates/configmap.yaml]: Any reason `devices` is under `global.nodePort.` and not just `global.`? It isn't specific to NodePort as far as I understand.

File: install/kubernetes/cilium/charts/config/templates/configmap.yaml (hunk 8 above)
Comment (pchaigno) [reply install/kubernetes/cilium/charts/config/templates/configmap.yaml:380]: Shouldn't we just reject using both `devices` and `device` (in cilium-agent or in Helm)? It feels like currently we're introducing a new behavior for an option that will then be deprecated.

**Comment by brb** [comment]
test-me-please

File: bpf/lib/nodeport.h [hunk 15]
```diff
@@ -91,19 +91,6 @@ struct dsr_opt_v6 {
...
-#if defined(ENABLE_NODEPORT_ACCELERATION) && !defined(FROM_ENCAP_DEV) && \
-    __ctx_is == __ctx_skb
-	/* We already handled remote backends on XDP layer. Anything
-	 * landing here that is remote is a bug.
-	 */
-	return true;
-#else
-	return false;
-#endif
-}
```
Comment (pchaigno) [inline bpf/lib/nodeport.h:105]: Was this added to handle some specific potential bug? If we want to keep it, instead of returning `true`, we could return some static data set per device at load time, e.g., `IS_AFTER_XDP_PROG`. Not sure if it's worth it here.

**Comment by brb** [comment]
retest-runtime

**Review by pchaigno — CHANGES_REQUESTED** [review]

File: bpf/lib/nodeport.h (hunk 15 above)
Comment (brb) [reply bpf/lib/nodeport.h:105]: This was just a sanity check. When the XDP is loaded, the `!backend_local` case should have been handled by bpf_xdp. So, any handling of this case in bpf_host is considered as a bug (except for a case when a relevant svc has been added just after bpf_xdp finished handling a request).

File: install/kubernetes/cilium/charts/config/templates/configmap.yaml (hunk 8 above)
Comment (brb) [reply install/kubernetes/cilium/charts/config/templates/configmap.yaml:380]: > Shouldn't we just reject using both devices and device (in cilium-agent or in Helm)?

Yeah, makes sense. I will change it: keeping both `global.nodePort.device` and `global.devices`, but rejecting in agent if both are set.

File: install/kubernetes/cilium/charts/config/templates/configmap.yaml (hunk 14 above)
Comment (brb) [reply install/kubernetes/cilium/charts/config/templates/configmap.yaml]: Hmm, good point. BPF Nodeport doesn't depend on host-fw (and vice versa), so it makes sense to define devices via `global.devices` instead. I will change it.

As a side note, I was thinking about introducing more fine grained device selection in v1.9 for each feature, i.e. `global.nodePort.devices`, `global.hostFW.devices`, `global.masquerade.devices`. But in any case, the selection via `global.devices` makes sense.

Comment (brb) [reply install/kubernetes/cilium/charts/config/templates/configmap.yaml]: Resolved in: e361f6121a31140ba2fa9e77abcab6b852bf7014.

File: install/kubernetes/cilium/charts/config/templates/configmap.yaml (hunk 8 above)
Comment (brb) [reply install/kubernetes/cilium/charts/config/templates/configmap.yaml:380]: Resolved in: e361f6121a31140ba2fa9e77abcab6b852bf7014.

**Comment by brb** [comment]
test-me-please

**Review by pchaigno — APPROVED** [review]

**Comment by joestringer** [comment]
@brb the failures are likely all related to the unformatted Go code:

```
06:34:50  Unformatted Go source code:
06:34:50  ./test/k8sT/external_ips.go
06:34:50  diff -u ./test/k8sT/external_ips.go.orig ./test/k8sT/external_ips.go
06:34:50  --- ./test/k8sT/external_ips.go.orig	2020-06-08 13:34:50.367498284 +0000
06:34:50  +++ ./test/k8sT/external_ips.go	2020-06-08 13:34:50.367498284 +0000
06:34:50  @@ -244,7 +244,7 @@
06:34:50   				deployCilium(map[string]string{
06:34:50   					"global.tunnel":               "disabled",
06:34:50   					"global.autoDirectNodeRoutes": "true",
06:34:50  -					"global.devices":     external_ips.PublicInterfaceName,
06:34:50  +					"global.devices":              external_ips.PublicInterfaceName,
06:34:50   					"global.nodePort.enabled":     "true",
06:34:50   					"global.bpfMasquerade":        "false",
06:34:50   				})
06:34:50  @@ -289,7 +289,7 @@
06:34:50   			BeforeAll(func() {
06:34:50   				deployCilium(map[string]string{
06:34:50   					"global.tunnel":           "vxlan",
06:34:50  -					"global.devices": external_ips.PublicInterfaceName,
06:34:50  +					"global.devices":          external_ips.PublicInterfaceName,
06:34:50   					"global.nodePort.enabled": "true",
06:34:50   					"global.bpfMasquerade":    "false",
06:34:50   				})
...
```

**Comment by pchaigno** [comment]
> @brb the failures are likely all related to the unformatted Go code:

A good example of why we need to make Travis CI required to start e2e tests: the smoke test didn't catch this.

**Review by christarazi — APPROVED** [review]

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

File: pkg/k8s/init.go [hunk 16]
```diff
@@ -67,14 +67,21 @@ func waitForNodeInformation(ctx context.Context, nodeName string) *nodeTypes.Nod
 func retrieveNodeInformation(nodeName string) (*nodeTypes.Node, error) {
 	requireIPv4CIDR := option.Config.K8sRequireIPv4PodCIDR
 	requireIPv6CIDR := option.Config.K8sRequireIPv6PodCIDR
+	// At this point it's not clear whether the device auto-detection will
+	// happen, as initKubeProxyReplacementOptions() might disable BPF NodePort.
+	// Anyway, to be on the safe side, don't give up waiting for a (Cilium)Node
+	// self object.
+	mightAutoDetectDevices :=
+		option.Config.KubeProxyReplacement != option.KubeProxyReplacementDisabled &&
+			(len(option.Config.Devices) == 0 || option.Config.DirectRoutingDevice == "")
```
Comment (joestringer) [inline pkg/k8s/init.go]: nit: Given that `GetNodeSpec()` also needs this logic it seems appropriate for a separate function. I also wonder if it would be more suitable to live near other devices logic, eg in the `option` package.

File: daemon/cmd/kubeproxy_replacement_test.go [hunk 17]
```diff
@@ -0,0 +1,165 @@
...
+	sort.Strings(option.Config.Devices)
+	c.Assert(option.Config.Devices, checker.DeepEquals, []string{"dummy0", "dummy1"})
+	c.Assert(option.Config.DirectRoutingDevice, Equals, "dummy0")
+
+	// 5. Enable IPv6, dummy1 should not be detected, as no default route for
+	// ipv6 is found
+	option.Config.EnableIPv6 = true
+	c.Assert(detectDevices(true, true), IsNil)
+	c.Assert(option.Config.Devices, checker.DeepEquals, []string{"dummy0"})
+	c.Assert(option.Config.DirectRoutingDevice, Equals, "dummy0")
```
Comment (joestringer) [inline daemon/cmd/kubeproxy_replacement_test.go:107]: I don't fully follow case 5 here. I presume the state from case 4 (ie ipv4 default route) should remain, so now that we don't have a ipv6 default route we don't care about the device with the ipv4 default route? IPv4 and IPv6 must both have default routes and both route over the same device?

File: daemon/cmd/daemon.go [hunk 18]
```diff
@@ -419,6 +422,52 @@ func NewDaemon(ctx context.Context, dp datapath.Datapath) (*Daemon, *endpointRes
...
+	if option.Config.Masquerade && option.Config.EnableBPFMasquerade {
+		// TODO(brb) nodeport + ipvlan constraints will be lifted once the SNAT BPF code has been refactored
+		if !option.Config.EnableNodePort {
+			log.Fatalf("BPF masquerade requires NodePort (--%s=\"true\")", option.EnableNodePort)
+		}
+		if option.Config.DatapathMode == datapathOption.DatapathModeIpvlan {
+			log.Fatalf("BPF masquerade works only in veth mode (--%s=\"%s\"", option.DatapathMode, datapathOption.DatapathModeVeth)
+		}
+		if option.Config.EgressMasqueradeInterfaces != "" {
+			log.Fatalf("BPF masquerade does not allow to specify devices via --%s. Use --%s instead.", option.EgressMasqueradeInterfaces, option.Devices)
```
Comment (joestringer) [inline daemon/cmd/daemon.go:447]: Is this basically because `--egress-masquerade-interfaces` receives an iptables wildcard parameter which can specify either directly a device or a range of devices with syntax like `eth+` and we don't want to support that? Or more just to avoid conflicting configuration from similar options?

Comment (joestringer) [reply daemon/cmd/daemon.go:447]: Oh, I guess this is already in the tree. Well I'm still curious.

File: daemon/cmd/daemon_main.go [hunk 19]
```diff
@@ -1733,9 +1702,8 @@ func initKubeProxyReplacementOptions() {
 				option.Config.EnableExternalIPs = false
 			}
 		} else {
-			log.WithField(logfields.Interface, device).
-				Info("Using auto-derived device for BPF node port")
-			option.Config.Devices = []string{device}
+			log.WithField(logfields.Interface, option.Config.Devices).
+				Info("Using auto-derived devices for BPF node port")
```
Comment (joestringer) [inline daemon/cmd/daemon_main.go]: Might be nice to get the equivalent message for `DirectRoutingDevice` here as well.

**Review by joestringer — APPROVED** [review]
Just a few minor nits, LGTM.

**Comment by joestringer** [comment]
Oh, forgot to mention - I also tried this out on my microk8s setup locally and it "just worked"! Autodetected my wifi interface and I was able to access nodeports from my local network. I also tried manually configuring multiple devices and again the nodeport just worked. :+1:

**Comment by brb** [comment]
The CI 4.19 failures are legit:
```
2020-06-08T20:53:55.649102448Z level=warning msg="+ tc filter replace dev cilium_vxlan ingress prio 1 handle 1 bpf da obj bpf_overlay.o sec from-overlay" subsys=datapath-loader
2020-06-08T20:53:55.649106128Z level=warning subsys=datapath-loader
2020-06-08T20:53:55.649109465Z level=warning msg="Prog section '2/19' rejected: Argument list too long (7)!" subsys=datapath-loader
2020-06-08T20:53:55.649112927Z level=warning msg=" - Type:         3" subsys=datapath-loader
2020-06-08T20:53:55.649116262Z level=warning msg=" - Attach Type:  0" subsys=datapath-loader
2020-06-08T20:53:55.649119593Z level=warning msg=" - Instructions: 4487 (391 over limit)" subsys=datapath-loader
2020-06-08T20:53:55.649123054Z level=warning msg=" - License:      GPL" subsys=datapath-loader
```

Why we didn't see it before? The CI 4.19 runs with `--kube-proxy-replacement=probe`, `--enable-ipv{4,6}=true` and w/o any device specified. Because of this PR, `enp0s8` is detected as device for BPF NodePort, and this enables BPF NodePort. Previously, only `enp0s3` could have been detected (a device with a default route), but in the end it was not, because the detector could not find a default route for IPv6, and thus BPF NodePort was disabled.

Not sure whether we should block this PR, as https://github.com/cilium/cilium/pull/11915 should resolve the issue. However, if we merge it, then the CI 4.19 should be disabled.

**Comment by brb** [comment]
retest-4.9

**Comment by pchaigno** [comment]
> Not sure whether we should block this PR, as #11915 should resolve the issue. However, if we merge it, then the CI 4.19 should be disabled.

The specific verifier error you pasted is fixed in #11915 but there are many (4 and counting) others hidden behind. 

Maybe we should just disable kube-proxy-replacement on 4.19 instead of the whole pipeline?

File: daemon/cmd/kubeproxy_replacement_test.go (hunk 17 above)
Comment (brb) [reply daemon/cmd/kubeproxy_replacement_test.go:107]: The test case does not set neither IPv6 addr nor a default IPv6 route. Anyway, due to `option.Config.EnableIPv6`,
`linuxdatapath.NodeDeviceWithDefaultRoute()` will hit the case https://github.com/cilium/cilium/blob/pr/brb/auto-multi-dev-v3/pkg/datapath/linux/route/route_linux.go#L566 which will make the former function to skip the default route device detection.

File: daemon/cmd/daemon.go (hunk 18 above)
Comment (brb) [reply daemon/cmd/daemon.go:447]: > receives an iptables wildcard parameter which can specify either directly a device or a range of devices with syntax like eth+ and we don't want to support that?

Yes, that's the reason. Once we decouple BPF NodePort from BPF masq (in v1.9), I'm planning to add a support for `--egress-masquerade-interfaces` with BPF masq.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
4.9 CI is hitting https://github.com/cilium/cilium/issues/11972.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
> Maybe we should just disable kube-proxy-replacement on 4.19 instead of the whole pipeline (until this is fixed)?

Yep, just disabled: https://github.com/cilium/cilium/pull/11894/commits/96789002bb5c1b5c693a121788b0adcdd39e409a

**Review by aanm — APPROVED** [review]
Changes LGTM does this require changes in the upgrade guide or are they already available?

**Comment by brb** [comment]
> Changes LGTM does this require changes in the upgrade guide or are they already available?

@aanm I'm planning to add them once this PR has been merged.

**Comment by brb** [comment]
Ouch, disabling the kube-proxy replacement on 4.19 brought new BPF verifier issues:
```
2020-06-09T12:06:13.810448788Z level=error msg="Command execution failed" cmd="[tc filter replace dev lxc_health ingress prio 1 handle 1 bpf da obj 3990_next/bpf_lxc.o sec from-container]" error="exit status 1" subsys=datapath-loader
2020-06-09T12:06:13.810479333Z level=warning subsys=datapath-loader
2020-06-09T12:06:13.810482468Z level=warning msg="Prog section '2/7' rejected: Argument list too long (7)!" subsys=datapath-loader
2020-06-09T12:06:13.810484728Z level=warning msg=" - Type:         3" subsys=datapath-loader
2020-06-09T12:06:13.810486903Z level=warning msg=" - Attach Type:  0" subsys=datapath-loader
2020-06-09T12:06:13.810489039Z level=warning msg=" - Instructions: 2916 (0 over limit)" subsys=datapath-loader
2020-06-09T12:06:13.810491248Z level=warning msg=" - License:      GPL" subsys=datapath-loader
2020-06-09T12:06:13.810493431Z level=warning subsys=datapath-loader
2020-06-09T12:06:13.810495466Z level=warning msg="Verifier analysis:" subsys=datapath-loader
2020-06-09T12:06:13.81049759Z level=warning subsys=datapath-loader
2020-06-09T12:06:13.810499715Z level=warning msg="Skipped 10832472 bytes, use 'verb' option for the full verbose log." subsys=datapath-loader
2020-06-09T12:06:13.810502001Z level=warning msg="[...]" subsys=datapath-loader
2020-06-09T12:06:13.810612759Z level=warning msg="ue=4294967295,var_off=(0x0; 0xffffffff)) R6=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R7=inv1 R8_w=ctx(id=0,off=0,imm=0) R9=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R10=fp0,call_-1 fp-144=0 fp-152=0 fp-184=ctx fp-200=0 fp-216=0 fp-224=0 fp-240=0 fp-248=0 fp-256=0" subsys=datapath-loader
2020-06-09T12:06:13.810621535Z level=warning msg="2890: (b7) r9 = 0" subsys=datapath-loader
2020-06-09T12:06:13.810623851Z level=warning msg="2891: (b7) r1 = 8" subsys=datapath-loader
2020-06-09T12:06:13.810667897Z level=warning msg="2892: (05) goto pc-1276" subsys=datapath-loader
2020-06-09T12:06:13.810672589Z level=warning msg="1617: safe" subsys=datapath-loader
2020-06-09T12:06:13.810674831Z level=warning subsys=datapath-loader
2020-06-09T12:06:13.810709417Z level=warning msg="from 2884 to 2893: R0=inv0 R6=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R7=inv1 R8=inv0 R9=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R10=fp0,call_-1 fp-144=0 fp-152=0 fp-184=ctx fp-200=0 fp-216=0 fp-224=0 fp-240=0 fp-248=0 fp-256=0" subsys=datapath-loader
2020-06-09T12:06:13.810714104Z level=warning msg="2893: (b7) r9 = 0" subsys=datapath-loader
2020-06-09T12:06:13.810750426Z level=warning msg="2894: (63) *(u32 *)(r10 -96) = r9" subsys=datapath-loader
2020-06-09T12:06:13.810754647Z level=warning msg="2895: (bf) r2 = r10" subsys=datapath-loader
2020-06-09T12:06:13.81075687Z level=warning msg="2896: (07) r2 += -96" subsys=datapath-loader
2020-06-09T12:06:13.810804036Z level=warning msg="2897: (18) r1 = 0xffff8bd51198ac00" subsys=datapath-loader
2020-06-09T12:06:13.810808294Z level=warning msg="2899: (85) call bpf_map_lookup_elem#1" subsys=datapath-loader
2020-06-09T12:06:13.810810504Z level=warning msg="2900: (15) if r0 == 0x0 goto pc+7" subsys=datapath-loader
2020-06-09T12:06:13.810812721Z level=warning msg=" R0=map_value(id=0,off=0,ks=8,vs=24,imm=0) R6=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R7=inv1 R8=inv0 R9=inv0 R10=fp0,call_-1 fp-144=0 fp-152=0 fp-184=ctx fp-200=0 fp-216=0 fp-224=0 fp-240=0 fp-248=0 fp-256=0" subsys=datapath-loader
2020-06-09T12:06:13.810820855Z level=warning msg="2901: (b7) r1 = 1" subsys=datapath-loader
2020-06-09T12:06:13.810860762Z level=warning msg="2902: (db) lock *(u64 *)(r0 +8) += r1" subsys=datapath-loader
2020-06-09T12:06:13.810865176Z level=warning msg=" R0=map_value(id=0,off=0,ks=8,vs=24,imm=0) R1_w=inv1 R6=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R7=inv1 R8=inv0 R9=inv0 R10=fp0,call_-1 fp-144=0 fp-152=0 fp-184=ctx fp-200=0 fp-216=0 fp-224=0 fp-240=0 fp-248=0 fp-256=0" subsys=datapath-loader
2020-06-09T12:06:13.810904463Z level=warning msg=" R0=map_value(id=0,off=0,ks=8,vs=24,imm=0) R1_w=inv1 R6=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R7=inv1 R8=inv0 R9=inv0 R10=fp0,call_-1 fp-144=0 fp-152=0 fp-184=ctx fp-200=0 fp-216=0 fp-224=0 fp-240=0 fp-248=0 fp-256=0" subsys=datapath-loader
2020-06-09T12:06:13.810908994Z level=warning msg="2903: (79) r8 = *(u64 *)(r10 -184)" subsys=datapath-loader
2020-06-09T12:06:13.810940197Z level=warning msg="2904: (61) r1 = *(u32 *)(r8 +0)" subsys=datapath-loader
2020-06-09T12:06:13.810944408Z level=warning msg="2905: (db) lock *(u64 *)(r0 +16) += r1" subsys=datapath-loader
2020-06-09T12:06:13.810993574Z level=warning msg=" R0=map_value(id=0,off=0,ks=8,vs=24,imm=0) R1_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R6=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R7=inv1 R8_w=ctx(id=0,off=0,imm=0) R9=inv0 R10=fp0,call_-1 fp-144=0 fp-152=0 fp-184=ctx fp-200=0 fp-216=0 fp-224=0 fp-240=0 fp-248=0 fp-256=0" subsys=datapath-loader
2020-06-09T12:06:13.810998311Z level=warning msg=" R0=map_value(id=0,off=0,ks=8,vs=24,imm=0) R1_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R6=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R7=inv1 R8_w=ctx(id=0,off=0,imm=0) R9=inv0 R10=fp0,call_-1 fp-144=0 fp-152=0 fp-184=ctx fp-200=0 fp-216=0 fp-224=0 fp-240=0 fp-248=0 fp-256=0" subsys=datapath-loader
2020-06-09T12:06:13.811000872Z level=warning msg="2906: (b7) r1 = 32" subsys=datapath-loader
2020-06-09T12:06:13.811003062Z level=warning msg="2907: (05) goto pc-1291" subsys=datapath-loader
2020-06-09T12:06:13.811005172Z level=warning msg="1617: safe" subsys=datapath-loader
2020-06-09T12:06:13.811044851Z level=warning subsys=datapath-loader
2020-06-09T12:06:13.811088592Z level=warning msg="from 2900 to 2908: R0=inv0 R6=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R7=inv1 R8=inv0 R9=inv0 R10=fp0,call_-1 fp-144=0 fp-152=0 fp-184=ctx fp-200=0 fp-216=0 fp-224=0 fp-240=0 fp-248=0 fp-256=0" subsys=datapath-loader
2020-06-09T12:06:13.811093079Z level=warning msg="2908: (b7) r1 = 0" subsys=datapath-loader
2020-06-09T12:06:13.811095291Z level=warning msg="2909: (79) r8 = *(u64 *)(r10 -184)" subsys=datapath-loader
2020-06-09T12:06:13.811097401Z level=warning msg="2910: (61) r2 = *(u32 *)(r8 +56)" subsys=datapath-loader
2020-06-09T12:06:13.811099528Z level=warning msg="2911: (b7) r9 = 0" subsys=datapath-loader
2020-06-09T12:06:13.811135154Z level=warning msg="2912: (55) if r2 != 0x0 goto pc-1296" subsys=datapath-loader
2020-06-09T12:06:13.811139375Z level=warning msg=" R0=inv0 R1=inv0 R2=inv0 R6=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R7=inv1 R8=ctx(id=0,off=0,imm=0) R9=inv0 R10=fp0,call_-1 fp-144=0 fp-152=0 fp-184=ctx fp-200=0 fp-216=0 fp-224=0 fp-240=0 fp-248=0 fp-256=0" subsys=datapath-loader
2020-06-09T12:06:13.811188911Z level=warning msg="2913: (18) r9 = 0xffffff7b" subsys=datapath-loader
2020-06-09T12:06:13.811193492Z level=warning msg="2915: (05) goto pc-1119" subsys=datapath-loader
2020-06-09T12:06:13.811195743Z level=warning msg="1797: safe" subsys=datapath-loader
2020-06-09T12:06:13.811197831Z level=warning subsys=datapath-loader
2020-06-09T12:06:13.811199885Z level=warning msg="from 2912 to 1617: safe" subsys=datapath-loader
2020-06-09T12:06:13.811203299Z level=warning subsys=datapath-loader
2020-06-09T12:06:13.811239583Z level=warning msg="from 1604 to 2066: safe" subsys=datapath-loader
2020-06-09T12:06:13.81124382Z level=warning subsys=datapath-loader
2020-06-09T12:06:13.811245995Z level=warning msg="from 1602 to 1605: safe" subsys=datapath-loader
2020-06-09T12:06:13.81124829Z level=warning subsys=datapath-loader
2020-06-09T12:06:13.811291375Z level=warning msg="from 1600 to 1795: safe" subsys=datapath-loader
2020-06-09T12:06:13.811295851Z level=warning subsys=datapath-loader
2020-06-09T12:06:13.811297952Z level=warning msg="from 1588 to 1795: safe" subsys=datapath-loader
2020-06-09T12:06:13.811300042Z level=warning subsys=datapath-loader
2020-06-09T12:06:13.811302046Z level=warning msg="from 1583 to 1605: safe" subsys=datapath-loader
2020-06-09T12:06:13.811304112Z level=warning subsys=datapath-loader
2020-06-09T12:06:13.81134537Z level=warning msg="from 1553 to 1563: safe" subsys=datapath-loader
2020-06-09T12:06:13.811349577Z level=warning subsys=datapath-loader
2020-06-09T12:06:13.811351698Z level=warning msg="from 1551 to 1563: safe" subsys=datapath-loader
2020-06-09T12:06:13.811353799Z level=warning subsys=datapath-loader
2020-06-09T12:06:13.81139775Z level=warning msg="from 1506 to 1517: R0=inv(id=0) R1=inv(id=0,umax_value=65535,var_off=(0x0; 0xffff)) R2=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R3=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R4=inv128 R6=map_value(id=0,off=0,ks=14,vs=56,imm=0) R7=inv1 R8=inv(id=0) R9=inv1 R10=fp0,call_-1 fp-144=0 fp-152=0 fp-184=ctx fp-200=0 fp-216=0 fp-224=0 fp-232=map_ptr fp-240=0 fp-248=0 fp-256=0 fp-272=0" subsys=datapath-loader
2020-06-09T12:06:13.811402609Z level=warning msg="1517: (bf) r7 = r9" subsys=datapath-loader
2020-06-09T12:06:13.811404853Z level=warning msg="1518: (47) r7 |= 1" subsys=datapath-loader
2020-06-09T12:06:13.811406945Z level=warning msg="1519: (bf) r1 = r7" subsys=datapath-loader
2020-06-09T12:06:13.811447548Z level=warning msg="1520: (67) r1 <<= 32" subsys=datapath-loader
2020-06-09T12:06:13.811452072Z level=warning msg="1521: (77) r1 >>= 32" subsys=datapath-loader
2020-06-09T12:06:13.811454384Z level=warning msg="1522: (55) if r1 != 0x3 goto pc+12" subsys=datapath-loader
2020-06-09T12:06:13.811459635Z level=warning msg="1535: (7b) *(u64 *)(r10 -232) = r9" subsys=datapath-loader
2020-06-09T12:06:13.811497382Z level=warning msg="1536: (7b) *(u64 *)(r10 -272) = r4" subsys=datapath-loader
2020-06-09T12:06:13.81150177Z level=warning msg="1537: (79) r1 = *(u64 *)(r10 -264)" subsys=datapath-loader
2020-06-09T12:06:13.811503972Z level=warning msg="1538: (63) *(u32 *)(r10 -88) = r1" subsys=datapath-loader
2020-06-09T12:06:13.811541848Z level=warning msg="1539: (18) r1 = 0x100000000000040" subsys=datapath-loader
2020-06-09T12:06:13.811546041Z level=warning msg="1541: (7b) *(u64 *)(r10 -96) = r1" subsys=datapath-loader
2020-06-09T12:06:13.811548234Z level=warning msg="1542: (b7) r9 = 0" subsys=datapath-loader
2020-06-09T12:06:13.81158279Z level=warning msg="1543: (7b) *(u64 *)(r10 -80) = r9" subsys=datapath-loader
2020-06-09T12:06:13.811587001Z level=warning msg="1544: (63) *(u32 *)(r10 -84) = r9" subsys=datapath-loader
2020-06-09T12:06:13.81162219Z level=warning msg="BPF program is too large. Processed 131073 insn" subsys=datapath-loader
2020-06-09T12:06:13.811626416Z level=warning subsys=datapath-loader
2020-06-09T12:06:13.811628662Z level=warning msg="Error filling program arrays!" subsys=datapath-loader
2020-06-09T12:06:13.81166852Z level=warning msg="Unable to load program" subsys=datapath-loader
2020-06-09T12:06:13.817900404Z level=warning msg="JoinEP: Failed to load program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=3 endpointID=3990 error="Failed to load tc filter: exit status 1" file-path=3990_next/bpf_lxc.o identity=4 ipv4= ipv6= k8sPodName=/ subsys=datapath-loader veth=lxc_health
```
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Kernel/1979/testReport/junit/Suite-k8s-1/17/K8sDatapathConfig_MonitorAggregation_Checks_that_monitor_aggregation_restricts_notifications/

File: daemon/cmd/daemon_main.go [hunk 20]
```diff
@@ -253,9 +253,17 @@ func init() {
 	flags.StringSlice(option.DebugVerbose, []string{}, "List of enabled verbose debug groups")
 	option.BindEnv(option.DebugVerbose)
 
-	flags.StringSliceP(option.Device, "d", []string{}, "List of devices facing cluster/external network for attaching bpf_netdev (first device should be one used for direct routing if tunneling is disabled)")
+	flags.StringP(option.Device, "d", "",
+		fmt.Sprintf("Device facing cluster/external network for attaching bpf_host. Deprecated in favor of --%s", option.Devices))
+	flags.MarkDeprecated(option.Device, "This option will be removed in v1.10")
 	option.BindEnv(option.Device)
```
Comment (borkmann) [inline daemon/cmd/daemon_main.go:259]: Can't we remove this right here and describe in the upgrade notes what a user needs to do? Why wait until 1.10? (I doubt many users deploy with an explicit --device.)

File: daemon/cmd/daemon_main.go [hunk 21]
```diff
@@ -253,9 +253,17 @@ func init() {
...
 
+	flags.StringSlice(option.Devices, []string{}, "List of devices facing cluster/external network for attaching bpf_host")
+	option.BindEnv(option.Devices)
```
Comment (borkmann) [inline daemon/cmd/daemon_main.go:262]: I would drop the `bpf_host`. A user doesn't/shouldn't know what bpf_host means here. I'd just say `List of devices facing cluster/external network`.

File: daemon/cmd/daemon_main.go [hunk 22]
```diff
@@ -253,9 +253,17 @@ func init() {
...
+
+	flags.String(option.DirectRoutingDevice, "", "Device name used to connect nodes in direct routing mode (required only by BPF NodePort; derived automatically if empty)")
+	option.BindEnv(option.DirectRoutingDevice)
```
Comment (borkmann) [inline daemon/cmd/daemon_main.go:265]: I would briefly state from where (`derived automatically if empty`) this is derived.

Comment (borkmann) [reply daemon/cmd/daemon_main.go:265]: I presume this has to be part of `--devices` list. Perhaps should be stated.

File: daemon/cmd/daemon_main.go (hunk 20 above)
Comment (brb) [reply daemon/cmd/daemon_main.go:259]: We would break the existing deployments in which `--device` was specified. I thought that we have a policy that we can change a user facing flag in a second release after we have announced it? @aanm might know better.

File: daemon/cmd/daemon_main.go (hunk 21 above)
Comment (brb) [reply daemon/cmd/daemon_main.go:262]: Maybe I would add `(used for BPF NodePort, host firewall and BPF masquerading)` to make it clear.

File: daemon/cmd/daemon_main.go (hunk 20 above)
Comment (aanm) [reply daemon/cmd/daemon_main.go:259]: correct. We can't simply remove flags and hope for the best :-)

**Review by borkmann — APPROVED** [review]
Modulo mentioned nits.

File: daemon/cmd/daemon_main.go (hunk 21 above)
Comment (borkmann) [reply daemon/cmd/daemon_main.go:262]: I would make it all explained in detail in the doc, but it's probably also too much context for here (implementation detail).

File: daemon/cmd/daemon_main.go (hunk 22 above)
Comment (brb) [reply daemon/cmd/daemon_main.go:265]: > I presume this has to be part of --devices list. Perhaps should be stated.

It's derived from a device which as a k8s node IP (the device is used by the direct routing routes). If the device was not specified within `--devices`, then it will be added to the list.

File: daemon/cmd/daemon_main.go (hunk 20 above)
Comment (borkmann) [reply daemon/cmd/daemon_main.go:259]: > correct. We can't simply remove flags and hope for the best :-)

But we eventually are going to remove them. I don't think anyone will read the daemon help. So it's basically the same issue in the second release from now.

Comment (aanm) [reply daemon/cmd/daemon_main.go:259]: > > correct. We can't simply remove flags and hope for the best :-)
> 
> But we eventually are going to remove them. I don't think anyone will read the daemon help. So it's basically the same issue in the second release from now.

If the users use a deprecated flag it will show up in the logs, also Martynas will add some notes in the upgrade guide.

File: daemon/cmd/daemon_main.go (hunk 22 above)
Comment (borkmann) [reply daemon/cmd/daemon_main.go:265]: Given we would have detection working nicely for it, what k8s use-case do you have in mind where we would still need the explicit DirectRoutingDevice specified? (I just think from a user pov, it's confusing.)

Comment (brb) [reply daemon/cmd/daemon_main.go:265]: When a user manages routing by itself (e.g. via BGP; `--auto-direct-node-routes=false`). Then they might want to control which interface should be used for direct routing.

Comment (borkmann) [reply daemon/cmd/daemon_main.go:265]: Fair enough, if there are known users that need this control beyond default detection, then lets add. (I just think that all these knobs to specify devices are just limited since it requires all nodes to be exact homogeneous wrt their device [and device naming] setup in order to work.)

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-focus K8sService*

**Comment by brb** [comment]
retest-4.19

**Comment by brb** [comment]
test-me-please

File: pkg/node/types/node.go [hunk 23]
```diff
@@ -223,6 +223,22 @@ func (n *Node) getNodeIP(ipv6 bool) (net.IP, addressing.AddressType) {
 	return backupIP, ipType
 }
 
+// GetK8sNodeIPs returns k8s Node IP (either InternalIP or ExternalIP or nil;
+// the former is prefered).
+func (n *Node) GetK8sNodeIP() net.IP {
```
Comment (christarazi) [inline pkg/node/types/node.go:228]: I was looking at the file recently and noticed that we have two very similar functions: `GetK8sNodeIP` and `GetNodeIP` (immediately below). I tracked it down to this PR. I am just curious; why did we need to add this @brb?

Comment (brb) [reply pkg/node/types/node.go:228]: `GetNodeIP()` can return an IP which is neither k8s `InternalIP` nor k8s `ExternalIP`. For the device detection, we want to use k8s IPs, as they are used for communication between nodes. For this, I introduced `GetK8sNodeIP()`.
