### PR TITLE
operator: fix identity GC collection

### LINKED ISSUE #19648: Cilium-operator skipped all identity to delete during garbage collect
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi,
I was noticing pods blocked in `ContainerCreating` status with a warning by cilium:
```
Warning  FailedCreatePodSandBox  3m37s (x140 over 131m)  kubelet  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "4be9762c1b0dad27108efef6ae5afdab190b7d0dda5b799e7c07ce311bf9a02b": Unable to create endpoint: Cilium API client timeout exceeded
Warning  FailedCreatePodSandBox  40s (x144 over 132m)  kubelet  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "61d869b08299b6140c30932688812010c629fdcde47169e56b18e0423ef5acbe": Unable to create endpoint: [PUT /endpoint/{id}][429] putEndpointIdTooManyRequests
```
and on the cilium pod, I got the following log:
```
level=error msg="Failed to add PolicyMap key" bpfMapKey="{1111 0 0 0}" containerID= datapathPolicyRevision=0 desiredPolicyRevision=43 endpointID=1394 error="Unable to update element for cilium_policy_01394 map with file descriptor 116: the map is full, please consider resizing it. argument list too long" identity=17462 ipv4= ipv6= k8sPodName=/ port=0 subsys=endpoint
level=warning msg="generating BPF for endpoint failed, keeping stale directory." containerID=f9692d3403 datapathPolicyRevision=0 desiredPolicyRevision=43 endpointID=1011 file-path=1011_next_fail identity=17462 ipv4=10.210.58.227 ipv6= k8sPodName=toolkit-jobs/toolkit-jobs-job-1828e5e0-d257-477a-8479-0062d03c6125 subsys=endpoint

level=error msg="endpoint regeneration failed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=43 endpointID=499 error="unable to regenerate policy because PolicyMap synchronization failed: syncPolicyMap failed" identity=17462 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=warning msg="Regeneration of endpoint failed" bpfCompilation=0s bpfLoadProg=0s bpfWaitForELF=0s bpfWriteELF=0s containerID= datapathPolicyRevision=0 desiredPolicyRevision=43 endpointID=1394 error="unable to regenerate policy because PolicyMap synchronization failed: syncPolicyMap failed" identity=17462 ipv4= ipv6= k8sPodName=/ mapSync=66.947082ms policyCalculation="2.279µs" prepareBuild="100.772µs" proxyConfiguration="110.301µs" proxyPolicyCalculation=97.291602ms proxyWaitForAck=0s reason="kube-apiserver identity updated" subsys=endpoint total=172.257108ms waitingForCTClean=0s waitingForLock=585ns
level=error msg="endpoint regeneration failed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=43 endpointID=1394 error="unable to regenerate policy because PolicyMap synchronization failed: syncPolicyMap failed" identity=17462 ipv4= ipv6= k8sPodName=/ subsys=endpoint
```
My first change was to change the rate-limiting parameter & increasing the bpfPolicyMap from `16384` to `65536`.

The next day, I got the same error: rate limiting error and same log in cilium pod

I found the doc about limiting identity label, I followed it: https://docs.cilium.io/en/v1.11/operations/performance/scalability/identity-relevant-labels/.
With the change with the doc, the list of identity generated will be only a few identities instead of hundred/thousand of identity.
The change was applied, cilium operator and cilium pods were restarted, everything started but the identity list was not updated and I even found an identity of a pod deleted for at least 1 week.

I enabled debug in the config and restarted cilium-operator.
On cilium-operator log, during garbage collect of identities, I saw that all identities to delete are skipped because the min max displayed are `min: 0` & `max: 0`.
```
level=debug msg="Will delete identities if they are still unused" identities-to-delete="map[]" subsys=cilium-operator-generic
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/11528 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
```
I updated `identity-gc-interval` from the default `15m` to `5m` to run it more often.

To solve my issue, I deleted all identities skipped by calling `cilium kvstore delete cilium/state/identities/v1/id/$ID`. I thought my issue could be linked to the identity list which was full but cilium-operator is still skipping all identity to delete with min & max at `0`.

### Cilium Version

```
Client: 1.11.4 9d25463 2022-04-15T08:33:55-07:00 go version go1.17.9 linux/amd64
Daemon: 1.11.4 9d25463 2022-04-15T08:33:55-07:00 go version go1.17.9 linux/amd64
```

### Kernel Version

```
Linux dc1-8gpu-12 5.4.0-109-generic #123~18.04.1-Ubuntu SMP Fri Apr 8 09:48:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:32:02Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
```

### Sysdump

[cilium-sysdump-20220429-072751.tar.xz.zip](https://github.com/cilium/cilium/files/8591327/cilium-sysdump-20220429-072751.tar.xz.zip)
(not a zip file, it is a `.tar.xz`)

### Relevant log output

```shell
Logs of the cilium-operator leader after restarting the pod:

level=info msg="Started gops server" address="127.0.0.1:9891" subsys=cilium-operator-generic
level=info msg="  --bgp-announce-lb-ip='false'" subsys=cilium-operator-generic
level=info msg="  --bgp-config-path='/var/lib/cilium/bgp/config.yaml'" subsys=cilium-operator-generic
level=info msg="  --ces-max-ciliumendpoints-per-ces='100'" subsys=cilium-operator-generic
level=info msg="  --ces-slice-mode='cesSliceModeIdentity'" subsys=cilium-operator-generic
level=info msg="  --cilium-endpoint-gc-interval='5m0s'" subsys=cilium-operator-generic
level=info msg="  --cluster-id=''" subsys=cilium-operator-generic
level=info msg="  --cluster-name='default'" subsys=cilium-operator-generic
level=info msg="  --cluster-pool-ipv4-cidr=''" subsys=cilium-operator-generic
level=info msg="  --cluster-pool-ipv4-mask-size='24'" subsys=cilium-operator-generic
level=info msg="  --cluster-pool-ipv6-cidr=''" subsys=cilium-operator-generic
level=info msg="  --cluster-pool-ipv6-mask-size='112'" subsys=cilium-operator-generic
level=info msg="  --cmdref=''" subsys=cilium-operator-generic
level=info msg="  --cnp-node-status-gc-interval='2m0s'" subsys=cilium-operator-generic
level=info msg="  --cnp-status-update-interval='1s'" subsys=cilium-operator-generic
level=info msg="  --config=''" subsys=cilium-operator-generic
level=info msg="  --config-dir='/tmp/cilium/config-map'" subsys=cilium-operator-generic
level=info msg="  --debug='true'" subsys=cilium-operator-generic
level=info msg="  --disable-cnp-status-updates='true'" subsys=cilium-operator-generic
level=info msg="  --disable-endpoint-crd='false'" subsys=cilium-operator-generic
level=info msg="  --enable-cilium-endpoint-slice='false'" subsys=cilium-operator-generic
level=info msg="  --enable-ipv4='true'" subsys=cilium-operator-generic
level=info msg="  --enable-ipv4-egress-gateway='false'" subsys=cilium-operator-generic
level=info msg="  --enable-ipv6='false'" subsys=cilium-operator-generic
level=info msg="  --enable-k8s-api-discovery='false'" subsys=cilium-operator-generic
level=info msg="  --enable-k8s-endpoint-slice='true'" subsys=cilium-operator-generic
level=info msg="  --enable-k8s-event-handover='true'" subsys=cilium-operator-generic
level=info msg="  --enable-local-redirect-policy='true'" subsys=cilium-operator-generic
level=info msg="  --enable-metrics='true'" subsys=cilium-operator-generic
level=info msg="  --gops-port='9891'" subsys=cilium-operator-generic
level=info msg="  --identity-allocation-mode='kvstore'" subsys=cilium-operator-generic
level=info msg="  --identity-gc-interval='5m'" subsys=cilium-operator-generic
level=info msg="  --identity-gc-rate-interval='1m'" subsys=cilium-operator-generic
level=info msg="  --identity-gc-rate-limit='2500'" subsys=cilium-operator-generic
level=info msg="  --identity-heartbeat-timeout='15m'" subsys=cilium-operator-generic
level=info msg="  --ipam='kubernetes'" subsys=cilium-operator-generic
level=info msg="  --k8s-api-server=''" subsys=cilium-operator-generic
level=info msg="  --k8s-heartbeat-timeout='30s'" subsys=cilium-operator-generic
level=info msg="  --k8s-kubeconfig-path=''" subsys=cilium-operator-generic
level=info msg="  --k8s-namespace='kube-system'" subsys=cilium-operator-generic
level=info msg="  --k8s-service-proxy-name=''" subsys=cilium-operator-generic
level=info msg="  --kvstore='etcd'" subsys=cilium-operator-generic
level=info msg="  --kvstore-opt='{\"etcd.config\":,\"/var/lib/etcd-config/etcd.config\"}'" subsys=cilium-operator-generic
level=info msg="  --leader-election-lease-duration='15s'" subsys=cilium-operator-generic
level=info msg="  --leader-election-renew-deadline='10s'" subsys=cilium-operator-generic
level=info msg="  --leader-election-retry-period='2s'" subsys=cilium-operator-generic
level=info msg="  --limit-ipam-api-burst='4'" subsys=cilium-operator-generic
level=info msg="  --limit-ipam-api-qps='20'" subsys=cilium-operator-generic
level=info msg="  --log-driver=''" subsys=cilium-operator-generic
level=info msg="  --log-opt=''" subsys=cilium-operator-generic
level=info msg="  --nodes-gc-interval='2m0s'" subsys=cilium-operator-generic
level=info msg="  --operator-api-serve-addr='127.0.0.1:9234'" subsys=cilium-operator-generic
level=info msg="  --operator-prometheus-serve-addr=':6942'" subsys=cilium-operator-generic
level=info msg="  --parallel-alloc-workers='50'" subsys=cilium-operator-generic
level=info msg="  --pprof='false'" subsys=cilium-operator-generic
level=info msg="  --pprof-port='6061'" subsys=cilium-operator-generic
level=info msg="  --skip-crd-creation='false'" subsys=cilium-operator-generic
level=info msg="  --subnet-ids-filter=''" subsys=cilium-operator-generic
level=info msg="  --subnet-tags-filter=''" subsys=cilium-operator-generic
level=info msg="  --synchronize-k8s-nodes='true'" subsys=cilium-operator-generic
level=info msg="  --synchronize-k8s-services='true'" subsys=cilium-operator-generic
level=info msg="  --unmanaged-pod-watcher-interval='15'" subsys=cilium-operator-generic
level=info msg="  --version='false'" subsys=cilium-operator-generic

...



level=debug msg="Will delete identities if they are still unused" identities-to-delete="map[]" subsys=cilium-operator-generic
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/11528 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/20147 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/23599 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/25421 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/28407 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/30005 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/50555 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/53640 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/8797 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/14651 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/17722 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/18617 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/4178 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/20484 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/43690 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/43758 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/50750 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/61035 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/17753 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/37902 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/58850 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/14218 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/61467 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/64004 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/28915 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/3105 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/38800 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/56232 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/27790 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/2814 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/39248 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/52327 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/60844 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/7168 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/29405 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/30394 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/38039 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/43700 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/17462 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/42450 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/10218 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/25651 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/28684 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/52620 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/54314 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/22503 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/27850 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/50556 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/4518 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/60525 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/64667 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/1497 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/26824 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/26967 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/50605 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/13305 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/26747 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/3290 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/40532 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/47409 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/52011 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
level=debug msg="Skipping this key" key=cilium/state/identities/v1/id/56377 reason="out of local cluster identity range [0,0]" subsys=kvstorebackend
```
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by aanm**
As the operator uses a different constructor for the GC of the
allocator, this constructor was not being initialized with the min and
max values of the identities that it should be GC. This commit adds
those options making it possible for the Operator to GC those
identities.

Fixes: 0c0f96531286 ("operator: only GC identity keys of its own cluster")
Signed-off-by: André Martins <andre@cilium.io>

Fixes https://github.com/cilium/cilium/issues/19648

### CODE REVIEW

**Review by joestringer — APPROVED** [review]

**Review by aditighag — CHANGES_REQUESTED** [review]
The fix seems straightforward so LGTM. But looking at the linked "Fixed" PR, we seem to have different identity allocators, and an operator is required to GC identities only from their cluster. While ideally we should have a unified way of constructing the allocators to avoid such misses, but that's probably out of the scope of your PR. But at the very least, can we add some comments to the code (how min and max are set for the different allocators)?
The linked PR is very light on details in the commit description - https://github.com/aanm/cilium/commit/0c0f96531286be0a443d2849718568b72d1b9931.

**Review by aditighag — APPROVED** [review]
Synced up offline with André. Looks like the linked PR that introduced this regression relied mainly on unit tests to test the fix? 😕 The unit test passes a different allocator to `RunGC`.

Edit : Since the regression went unnoticed until now, it's likely that we don't have any e2e tests. :(

File: pkg/allocator/allocator.go [hunk 1]
```diff
@@ -155,7 +155,21 @@ type Allocator struct {
 type AllocatorOption func(*Allocator)
 
 // NewAllocatorForGC returns an allocator that can be used to run RunGC()
-func NewAllocatorForGC(backend Backend) *Allocator {
+//
+// The allocator can be configured by passing in additional options:
+//  - WithMin(id) - minimum ID to allocate (default: 1)
+//  - WithMax(id) - maximum ID to allocate (default max(uint64))
+func NewAllocatorForGC(backend Backend, opts ...AllocatorOption) *Allocator {
```
Comment (christarazi) [inline pkg/allocator/allocator.go:162]: I guess we can prevent this from ever happening again by making the constructors take the min and max, but maybe that's not useful anymore now. Good catch.

Comment (christarazi) [reply pkg/allocator/allocator.go:162]: Aditi above slightly touched on this.
