### PR TITLE
CI: fix bash complaining about "unexpected tokens" (parenthesis)

### LINKED ISSUE #11094: Fails to create bugtool directory for "(kube-proxy)" tests
When some kube-proxy tests fail, the creation of the bugtool directory fails because the test's name contains parentheses:
```
time="2020-04-21T22:21:32Z" level=debug msg="running command: mkdir -p /home/jenkins/workspace/Cilium-PR-K8s-GKE@6/src/github.com/cilium/cilium/test/test_results/114-/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_(kube-proxy)_with_externalTrafficPolicy=Local/bugtool-cilium-c5wp8"
time="2020-04-21T22:21:32Z" level=error msg="Error executing command 'mkdir -p /home/jenkins/workspace/Cilium-PR-K8s-GKE@6/src/github.com/cilium/cilium/test/test_results/114-/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_(kube-proxy)_with_externalTrafficPolicy=Local/bugtool-cilium-c5wp8'" error="exit status 1"
time="2020-04-21T22:21:32Z" level=error msg="Error executing command 'mkdir -p /home/jenkins/workspace/Cilium-PR-K8s-GKE@6/src/github.com/cilium/cilium/test/test_results/114-/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_(kube-proxy)_with_externalTrafficPolicy=Local/bugtool-cilium-c5wp8'" error="exit status 1"
cmd: "mkdir -p /home/jenkins/workspace/Cilium-PR-K8s-GKE@6/src/github.com/cilium/cilium/test/test_results/114-/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_(kube-proxy)_with_externalTrafficPolicy=Local/bugtool-cilium-c5wp8" exitCode: 1 duration: 1.074608ms stdout:

stderr:
bash: -c: line 0: syntax error near unexpected token `('
bash: -c: line 0: `mkdir -p /home/jenkins/workspace/Cilium-PR-K8s-GKE@6/src/github.com/cilium/cilium/test/test_results/114-/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_(kube-proxy)_with_externalTrafficPolicy=Local/bugtool-cilium-c5wp8'
```
Should we just rename the tests to avoid those parentheses?
/cc @brb

### PR DESCRIPTION
**Pull request by qmonnet**
In #11094, @pchaigno reported that a few K8sServices tests contain parenthesis in their names, and that this creates confusion for the bash command used to create the bugtool archive directory if one of those tests fails on the CI.

Let's fix this by enquoting the directory name in the relevant bash commands, to avoid the parenthesis to be interpreted. This was tested in draft PR #11230, where test `Tests NodePort (kube-proxy)` is forced to fail and where we can grep the CI logs for the `unexpected token` bash error.

While grepping for that message, it appeared that the logs had other occurrences of this `unexpected token` error. They are not related to the above issues, but instead come from a wrong usage of the optional arguments for `helpers.CurlFail()` at one location in K8sServices tests. Fix this one by removing the spurious (unnecessary) argument. The aforementioned PR also has this fix, and shows that it solves the complaint from bash.

Fixes: #11094

### CODE REVIEW

**Comment by qmonnet** [comment]
test-me-please

**Review by pchaigno — APPROVED** [review]

**Comment by qmonnet** [comment]
It looks like now the `curl` command is effectively run, it passes when the test expects it to fail. Not sure if the test should be changed or if there's a bug in Cilium. @gandro, you authored commit 54304819a1d242700667125e453ace3d1bf3795f, do you see what might be going wrong here?

**Review by aanm — APPROVED** [review]

**Review by nebril — COMMENTED** [review]
Good catch! LGTM overall, one question left inline, let's merge it when we are it's not breaking CI.

File: test/k8sT/Services.go [hunk 1]
```diff
@@ -385,7 +385,7 @@ var _ = Describe("K8sServicesTest", func() {
 		failRequests := func(url string, count int, fromPod string) {
 			By("Making %d curl requests from %s to %q", count, fromPod, url)
 			for i := 1; i <= count; i++ {
-				res, err := kubectl.ExecInHostNetNS(context.TODO(), fromPod, helpers.CurlFail(url, "--max-time 3"))
+				res, err := kubectl.ExecInHostNetNS(context.TODO(), fromPod, helpers.CurlFail(url))
```
Comment (nebril) [inline test/k8sT/Services.go:386]: Why is this changed? Can this be cause of our test fail?

Comment (qmonnet) [reply test/k8sT/Services.go:386]: From the commit log:
```
helpers.CurlFail() can take optional arguments, and at one location this
is used to pass the "--max-time" option to the curl command line.

But these optional arguments for helpers.CurlFail() are not intended to
be used that way; they should instead be used to format the target URL,
which is supposed to be a string containing the relevant format
specifiers. Because in the current case, the URL provided has no format
specifier, go appends the additional arguments at the end, with
extraneous characters. So instead of producing the final curl command:

   curl [...] http://192.168.36.11:30861 --max-time 3 [...]

We actually get:

   curl [...] --max-time 8 http://192.168.36.11:30861%!(EXTRA string=--max-time 3)

The first "--max-time 8" is added by helpers.CurlFail() itself.

Then of course bash fails to interpret that command, and complains with:

   bash: -c: line 0: syntax error near unexpected token `('

In order to fix it, let's remove the "--max-time 3" argument entirely.
As we can see from the resulting command line, "--max-time" is already
used (with "CurlMaxTimeout") anyway. We will wait a few seconds more,
but at least the curl command will effectively be run.
```

So with that change, the `curl` command _is_ run (previously bash would fail to parse the command and would not run it), and this apparently caused the test to fail (`curl` passed when it was supposed to fail). But this only means that the test was not run correctly so far. So if the `curl` command runs and fail, I understand that either the test is incorrect, or it raises a bug in Cilium. I haven't found time to investigate further for now.

**Comment by qmonnet** [comment]
test-me-please

File: test/k8sT/Services.go (hunk 1 above)
Comment (gandro) [reply test/k8sT/Services.go:386]: Apologies for the late reply, I did not see the mention before somehow. I think this fix is okay for now to unblock people, but it would be great to have a configurable `CurlMaxTimeout`, since this change will add 30 seconds (6*5 additional seconds) to the test time.

Unfortunately, the only way `failRequest` should actually fail is due to a timeout, so it will wait 8 seconds each invocation.

Comment (qmonnet) [reply test/k8sT/Services.go:386]: It will even add 6×8 seconds, since the 3-second long timeout was skipped so far (command not run). Yeah I can probably work out something to pass a configurable value. Could you please have a look at the other commit that changes some of the `failRequests()` to `doRequests()`?

**Comment by qmonnet** [comment]
Tests with `externalTrafficPolicy=Local` on k8s 1.11 remain unhappy, this need more works :/. Marking as draft.

File: test/k8sT/Services.go (hunk 1 above)
Comment (gandro) [reply test/k8sT/Services.go:386]: >  Could you please have a look at the other commit that changes some of the failRequests() to doRequests()?

I assume you are referring to https://github.com/cilium/cilium/pull/11307/commits/0be2205493bbbf0d261cc7a5abb1d86c9f1c9176 ?

If kube-proxy indeed forwards requests from local pods, then I think our implementation in NodePort BPF in the datapath is actually not compliant. The tests were written with NodePort BPF's implementation in mind, not kube-proxy. But I haven't worked on that code in a while, @brb would likely know more.

Edit: Discussed offline, our implementation should be compliant on a conceptual level. There might be a bug however.

Edit 2: After closer inspection, our implementation is incompatible with kube-proxy. kube-proxy forwards local requests, while cilium does not.

File: test/helpers/kubectl.go [hunk 2]
```diff
@@ -2791,14 +2791,14 @@ func (kub *Kubectl) DumpCiliumCommandOutput(ctx context.Context, namespace strin
 			}
 
 			archiveName := filepath.Join(logsPath, fmt.Sprintf("bugtool-%s", pod))
-			res = kub.ExecContext(ctx, fmt.Sprintf("mkdir -p %s", archiveName))
+			res = kub.ExecContext(ctx, fmt.Sprintf("mkdir -p \"%s\"", archiveName))
```
Comment (joestringer) [inline test/helpers/kubectl.go]: Drive-by nit: Can/should we use `%q` for this purpose?

Comment (qmonnet) [reply test/helpers/kubectl.go]: What for? As I understand it, it [does not escape parenthesis](https://stackoverflow.com/questions/56055300/what-does-safely-escaped-with-go-syntax-mean) or enquote its argument, does it?

File: test/k8sT/Services.go (hunk 1 above)
Comment (qmonnet) [reply test/k8sT/Services.go:386]: > I think this fix is okay for now to unblock people, but it would be great to have a configurable `CurlMaxTimeout`, since this change will add 30 seconds (6*5 additional seconds) to the test time.
> 
> Unfortunately, the only way `failRequest` should actually fail is due to a timeout, so it will wait 8 seconds each invocation.

I had another look and this is in fact not the case, because we should timeout on the value passed to `--connect-timeout` (5 seconds) here and not the one from `--max-time`. Test logs confirm that. So no change needed on that side.

**Comment by qmonnet** [comment]
test-me-please

**Review by gandro — APPROVED** [review]
The new test setup for externalTrafficPolicy=Local looks good to me, thanks a lot for taking care of this!

File: test/helpers/kubectl.go (hunk 2 above)
Comment (gandro) [reply test/helpers/kubectl.go]: While it does not escape all the characters (we would need something like https://godoc.org/github.com/alessio/shellescape for that), `%q` it would at least escape quotes, newline and other stuff which might break the command.

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
retest-runtime

File: test/helpers/kubectl.go (hunk 2 above)
Comment (qmonnet) [reply test/helpers/kubectl.go]: Ah right and I was mistaken, the `%q` does seem to enquote the string. I'll use it then, thanks.

**Comment by qmonnet** [comment]
test-me-please

**Comment by gandro** [comment]
retest-runtime

**Comment by qmonnet** [comment]
retest-runtime
