### PR TITLE
Fix issue where Cilium-agent fails to start on nodes without a default gateway

### LINKED ISSUE #11588: Cilium-agent fails to start in air-gapped network without default gateway set
## Bug report
Cilium-agent fails to start in air-gapped network without default gateway set.

> level=warning msg="Unable to automatically detect MTU" error="unable to lookup route to xxxx:xxxx:xxxx::xxxx: network is unreachable, unable to lookup route to 1.1.1.1: network is unreachable" subsys=mtu
> level=fatal msg="Unable to open service maps" error="Unable to create map /sys/fs/bpf/tc/globals/cilium_proxy4: cannot allocate memory" subsys=daemon

Based on the log analysis it seems that it is first failing to 'autoDetect' the 'mtu' and so fails to start the agent.
We see a fatal failure to open 'service maps'. Not sure if gateway is required.

- [ ] Need to document this behavior in the document and suggest the users to start the agent with manual 'mtu' setting to override the 'autoDetect', if the failure is due to 'autoDetec'.

- [ ] Update the error log with additional information on how to recover.

### PR DESCRIPTION
**Pull request by soumynathan**
This PR fixes the problem by checking for the default gateway
in the existing routes and if gateway is absent the 'autoDetect'
fails.
When autoDetect fails we set the default 'Ethernetmtu' and will
also raise a warning message.

Fixes: #11588
Signed-off-by: Swaminathan Vasudevan <svasudevan@suse.com>

### CODE REVIEW

File: pkg/mtu/detect_linux.go [hunk 1]
```diff
@@ -58,16 +58,18 @@ func autoDetect() (int, error) {
...
-	if mtu := link.Attrs().MTU; mtu != 0 {
-		log.Infof("Detected MTU %d", mtu)
-		return mtu, nil
+		if mtu := link.Attrs().MTU; mtu != 0 {
+			log.Infof("Detected MTU %d", mtu)
+			return mtu, nil
+		}
+		return EthernetMTU, nil
+	} else {
+		return 0, fmt.Errorf("unable to find default gateway from routes: %s", routes)
```
Comment (pchaigno) [inline pkg/mtu/detect_linux.go]: Nit: Might be nicer to implement this as an early check, to avoid one more indentation:
```go
if routes[0].Gw == nil {
    return 0, fmt.Errorf("unable to find default gateway from routes: %s", routes)
}
```

Comment (soumynathan) [reply pkg/mtu/detect_linux.go]: Done.

**Review by joestringer — APPROVED** [review]
Looks good. I renamed your PR so that it shows up in the release notes properly.

**Comment by joestringer** [comment]
test-me-please

**Comment by soumynathan** [comment]
This also a candidate for backport.

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
`Runtime-4.9` hit only known flake #10278; other required builds are passing.

**Review by tklauser — APPROVED** [review]
