### PR TITLE
Ignore collisions for named ports that are not actually used in an egress policy

### LINKED ISSUE #12514: Rate limit and/or postpone named port collision warning log
Cilium 1.8 issues log warnings on collisions between POD port names even across namespaces. This is due to potential use of named ports in egress policies, which could lead to incorrect policy if the destination port name cannot be uniquely mapped to a port number. Cilium policy processing abstracts egress policy destinations to a security ID that can represent multiple PODs, leading to a requirement for the POD port name specs to not have different port numbers for the same name.

These warning logs are meaningless if the network policies deployed in the cluster do not use named ports.

Solve this by postponing the warning message until (collided) named ports are used in a network policy.

It would be possible to keep track of the port name mappings on the granularity of a security ID, but that would require more considerable investment in Cilium policy processing logic refactoring. This will be done later if deemed necessary.

### PR DESCRIPTION
**Pull request by jrajahalme**
Do not warn of port name conflicts when ports are collected, but keep
the conflicting ports. This allows (any) warnings to be postponed until
the named ports are used in a policy.

Behavior in presence of conflicting port name/number mapping, when
the port name is used in a policy is slightly changed:

 - Now these collisions will not affect ingress policies at all
 - For egress the policy rule using the conflicting port is now ignored.
   Cilium needs to be running with debug on to see this happening.
   Previously rule was instantiated using one of the many port numbers,
   essentially selected randomly.
 - Missing port name mappings, when used in a policy applicable to
   the local node, are logged as warnings, but rate limited.

Pass Endpoint (or a subset interface) to potential users of Endpoint's
NamedPortsMap so that instead of preparing the map in advance it can
be created of demand in case it is actually needed.

NamedPortsMap is an interface that is implemented by both NamedPortMap
or NamedPortMultiMap, first of which is built from the POD spec, and
the latter is a collection of named ports across all the PODs in the
cluster. When a named port is used in an ingress policy, it can be
translated by using the PODs own NamedPortMap. When a named port is
used in an egress policy the named port can be one of any remote PODs,
so the collection of all the named ports in the cluster is used as the
individual destination POD is not known at policy computation
time. This could be optimized to the scope of PODs sharing the same
set of labels as the destination security IDs are known when policy is
configured.

Currently same port name resolving to different port numbers is
flagged as a runtime error when that specific port name is used in a
policy. Traffic to this/these ports is not allowed. To get around this the
port names should be made unique so that each name maps to the
same port number and protocol, or preferably the port names in the
egress policies should be replaced with the desired port numbers.

The maintenance of the collection of named ports across the cluster
described above is started only after first needed for computing the
bpf map entries from an egress policy that uses a port name instead
the number. This way the related overhead is avoided if named ports
are never used in egress policies.

Fixes: #12514

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-focus K8sConformance

**Comment by jrajahalme** [comment]
test-upstream-k8s

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Unrelated test flake in Cilium-PR-Ginkgo-Tests-K8s

File: pkg/proxy/mock_test.go [hunk 1]
```diff
@@ -24,7 +24,7 @@ import (
 	"github.com/cilium/cilium/pkg/proxy/accesslog"
 )
 
-type proxyUpdaterMock struct {
+type ProxyUpdaterMock struct {
```
Comment (joestringer) [inline pkg/proxy/mock_test.go]: If we're duplicating this in `pkg/envoy` and `pkg/proxy`, maybe we should place a single version under `pkg/testutils` instead?

File: pkg/endpoint/policy.go [hunk 2]
```diff
@@ -44,20 +44,38 @@ import (
 	"github.com/sirupsen/logrus"
 )
 
+// GetNamedPortsMap returns the map of named ports relevant for the given direction
+func (e *Endpoint) GetNamedPortsMap(ingress bool) policy.NamedPortsMap {
```
Comment (joestringer) [inline pkg/endpoint/policy.go]: I assume that the locking aspect is OK here because we return a map by value so there's no way the caller could interfere with the actual `e.k8sPorts` copy of the map?

**Review by joestringer — APPROVED** [review]
I didn't see at a glance how we continue to warn about collisions later on when implementing the policy, but I'm guessing that's because it's existing code somewhere that's not touched by this PR.

But otherwise looks good, couple of minor points below but could likely be deferred for subsequent cleanup.

File: pkg/proxy/mock_test.go (hunk 1 above)
Comment (jrajahalme) [reply pkg/proxy/mock_test.go]: Tried placing this in `pkg/testutils`, but unfortunately that introduced an import loop. Also, this will be removed from `pkg/proxy` by https://github.com/cilium/cilium/pull/12548.

File: pkg/endpoint/policy.go (hunk 2 above)
Comment (jrajahalme) [reply pkg/endpoint/policy.go]: Maps are always returned by reference, so here we trust that the caller is not messing with the returned map.

**Comment by jrajahalme** [comment]
@joestringer Currently we log on debug level about failures in name->port mappings.

File: pkg/endpoint/policy.go (hunk 2 above)
Comment (christarazi) [reply pkg/endpoint/policy.go]: Should we return a deep copy of the map in that case then?

Comment (joestringer) [reply pkg/endpoint/policy.go]: So we don't actually have any locking guarantee here then? Shouldn't we at least readlock while reading this?

**Comment by joestringer** [comment]
@jrajahalme SGTM, I presume these are different warnings so we can set the levels separately to an appropriate level? Main thing is just to ensure that potentially recurring messages wouldn't end up spamming the logs.

File: pkg/proxy/mock_test.go (hunk 1 above)
Comment (joestringer) [reply pkg/proxy/mock_test.go]: SGTM. I wonder if a new `pkg/testutils/proxy` package would make sense for this but if there's only going to be one instance soon anyway then the point is moot.

File: pkg/endpoint/bpf.go [hunk 3]
```diff
@@ -211,7 +211,7 @@ func (e *Endpoint) addNewRedirectsFromDesiredPolicy(ingress bool, desiredRedirec
 				var finalizeFunc revert.FinalizeFunc
 				var revertFunc revert.RevertFunc
 
-				proxyID, err := e.ProxyID(e.desiredPolicy.NamedPortsMap, l4)
+				proxyID, err := e.ProxyID(l4)
```
Comment (christarazi) [inline pkg/endpoint/bpf.go]: Typo is commit msg:

"of demand" -> "on demand"

File: pkg/envoy/mock_test.go [hunk 4]
```diff
@@ -0,0 +1,65 @@
+// Copyright 2017-2019 Authors of Cilium
```
Comment (christarazi) [inline pkg/envoy/mock_test.go]: This file doesn't have any tests in it. Is there a reason it is named "mock_test"? Could it just be "mock.go"?

Comment (christarazi) [reply pkg/envoy/mock_test.go]: We could also introduce a `mock` subpackage inside the `envoy` package, that way we don't pollute the `envoy` package namespace and reduce the burden of importing it.

File: pkg/ipcache/ipcache.go [hunk 5]
```diff
@@ -82,7 +82,8 @@ type IPCache struct {
 
 	listeners []IPIdentityMappingListener
 
-	namedPorts policy.NamedPortMultiMap
+	needNamedPorts bool
```
Comment (christarazi) [inline pkg/ipcache/ipcache.go:90]: I think it would be helpful context to briefly explain why `needNamePorts` needs to exist / its role.

File: pkg/envoy/mock_test.go (hunk 4 above)
Comment (christarazi) [reply pkg/envoy/mock_test.go]: Ah, didn't see the conversation about this earlier. Please ignore.

**Review by christarazi — APPROVED** [review]
LGTM, a few minor points down below.

File: pkg/envoy/mock_test.go (hunk 4 above)
Comment (jrajahalme) [reply pkg/envoy/mock_test.go]: @christarazi The mock is used from another *_test.go file, and need not be linked into the release code. My understanding is that Go does not automatically exclude dead code.

File: pkg/endpoint/policy.go (hunk 2 above)
Comment (aanm) [reply pkg/endpoint/policy.go]: @christarazi as long we document that the caller should not mess up with the map, it should be fine. We shouldn't do useless deepcopies.

+1 for the missing locking guarantee that Joe is pointing out

File: pkg/ipcache/ipcache.go (hunk 5 above)
Comment (aanm) [reply pkg/ipcache/ipcache.go:90]: +1 I'm also lost.

**Review by aanm — CHANGES_REQUESTED** [review]

File: pkg/ipcache/ipcache.go (hunk 5 above)
Comment (jrajahalme) [reply pkg/ipcache/ipcache.go:90]: Adding this comment:
```
	// needNamedPorts is initially 'false', but will be changd to 'true' when the
	// clusterwide named port mappings are needed for network policy computation
	// for the first time. This avoids the overhead of maintaining 'namedPorts' map
	// when it is known not to be needed.
	// Both needNamedPorts and namedPorts are protected by 'mutex'.
```

**Comment by jrajahalme** [comment]
@aanm Added a comment that also covers the locking requirements:
```
	// needNamedPorts is initially 'false', but will be changd to 'true' when the
	// clusterwide named port mappings are needed for network policy computation
	// for the first time. This avoids the overhead of maintaining 'namedPorts' map
	// when it is known not to be needed.
	// Protected by 'mutex'.
	needNamedPorts bool

	// namedPorts is a collection of all named ports in the cluster. This is needed
	// only if an egress policy refers to a port by name.
	// This map is returned to users so all updates must be made into a fresh map that
	// is then swapped in place while 'mutex' is being held.
```

File: pkg/endpoint/bpf.go (hunk 3 above)
Comment (jrajahalme) [reply pkg/endpoint/bpf.go]: Fixed, thanks!

File: pkg/endpoint/endpoint.go [hunk 6]
```diff
@@ -225,7 +225,7 @@ type Endpoint struct {
 
 	// k8sPorts contains container ports associated in the pod.
 	// It is used to enforce k8s network policies with port names.
-	k8sPorts policy.NamedPortsMap
+	k8sPorts policy.NamedPortMap
```
Comment (aditighag) [inline pkg/endpoint/endpoint.go:229]: Is there any significance to policy.NamedPortMap vs policy.NamedPortsMap.
You've renamed it in endpoint.go but not in l4.go.

**Comment by jrajahalme** [comment]
Noticed a locking problem, fixed in the third commit, plan to squash into earlier commits before merging.
Added two more commits to first refactor and then add warning log rate limiting (max 1 log every 10 seconds with a burst of 3). This rate limit should likely be tuned before merging.

File: pkg/endpoint/endpoint.go (hunk 6 above)
Comment (jrajahalme) [reply pkg/endpoint/endpoint.go:229]: `policy.NamedPortsMap` is now an interface that abstracts the implementation (simple map, used for ingress that only needs to consider named ports of the POD itself, or a multimap used for egress that needs to map a port name of destination PODs).

**Comment by jrajahalme** [comment]
test-upstream-k8s

**Comment by jrajahalme** [comment]
test-upstream-k8s

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Known flake #11847 in netnext

File: pkg/policy/portmap.go [hunk 7]
```diff
@@ -0,0 +1,170 @@
...
+	}
+	pp, err := ParsePortProto(port, protocol)
+	if err != nil {
+		return err
+	}
+	npm[name] = pp
+	return nil
+}
+
+// NamedPortMap abstracts different maps that implement GetNamedPort method
```
Comment (christarazi) [inline pkg/policy/portmap.go]: I think it would be helpful to describe why this abstraction is now implemented.

File: pkg/logging/limiter.go [hunk 8]
```diff
@@ -0,0 +1,36 @@
...
+	*rate.Limiter
+}
+
+func NewLimiter(r rate.Limit, b int) Limiter {
+	return Limiter{
+		Limiter: rate.NewLimiter(r, b),
+	}
+}
+
+func (ll Limiter) Allow() bool {
```
Comment (christarazi) [inline pkg/logging/limiter.go]: Can you provide the Golang docs for these exported types?

File: pkg/logging/limiter_test.go [hunk 9]
```diff
@@ -0,0 +1,43 @@
...
+	c.Assert(limiter.Allow(), Equals, false)
+	time.Sleep(1 * time.Second)
+	c.Assert(limiter.Allow(), Equals, true)
+	c.Assert(limiter.Allow(), Equals, false)
+	c.Assert(limiter.Allow(), Equals, false)
+	time.Sleep(2 * time.Second)
+	c.Assert(limiter.Allow(), Equals, true)
+	c.Assert(limiter.Allow(), Equals, true)
+	c.Assert(limiter.Allow(), Equals, false)
+	c.Assert(limiter.Allow(), Equals, false)
```
Comment (christarazi) [inline pkg/logging/limiter_test.go]: It'd be helpful to have a description of what this test is doing and what it expects.

File: pkg/ipcache/ipcache.go (hunk 5 above)
Comment (christarazi) [reply pkg/ipcache/ipcache.go:90]: Thanks for adding that. Sounds like an optimization. Just out of curiosity, did we measure the impact of this?

**Review by aanm — APPROVED** [review]

File: pkg/policy/portmap.go (hunk 7 above)
Comment (jrajahalme) [reply pkg/policy/portmap.go]: I'll have to go back and see if this is still needed. I added this in a phase where policy computation was given a map that could be either a regular/simple map (for ingress) or a collated multimap (for egress). Now that the port name resolution is always done via a callback this might not be needed any more.

**Comment by jrajahalme** [comment]
> Thanks for adding that. Sounds like an optimization. Just out of curiosity, did we measure the impact of this?

Did not measure the impact, but learned since release that (to me) surprisingly many POD specs are naming ports while the names are (likely) not used for anything. Maintaining the collection of all the named ports in the cluster was run every time a POD with a named port was added or removed (cluster-wide), so I felt it prudent to avoid that computation for the benefit or large clusters where port names are not used in egress policies.

**Comment by jrajahalme** [comment]
test-upstream-k8s

**Comment by jrajahalme** [comment]
test-me-please

File: pkg/policy/portmap.go [hunk 10]
```diff
@@ -0,0 +1,164 @@
...
+	"github.com/cilium/cilium/pkg/iana"
+	"github.com/cilium/cilium/pkg/u8proto"
+)
+
+var (
+	ErrNilMap               = errors.New("Nil map")
+	ErrUnknownNamedPort     = errors.New("Unknown named port")
+	ErrIncompatibleProtocol = errors.New("Incompatible protocol")
+	ErrNamedPortIsZero      = errors.New("Named port is zero")
+	ErrDuplicateNamedPorts  = errors.New("duplicate named ports")
```
Comment (christarazi) [inline pkg/policy/portmap.go]: Nit: I think the convention for error strings is to start lower-cased.

File: pkg/policy/portmap.go [hunk 11]
```diff
@@ -0,0 +1,164 @@
...
+)
+
+type PortProto struct {
```
Comment (christarazi) [inline pkg/policy/portmap.go:36]: Could you add go docs for the exported types?

**Review by christarazi — APPROVED** [review]
LGTM; a few non-blocking comments to address, and should be good to go from my perspective.

File: pkg/policy/portmap.go (hunk 10 above)
Comment (jrajahalme) [reply pkg/policy/portmap.go]: Fixed, thanks!

File: pkg/policy/portmap.go (hunk 11 above)
Comment (jrajahalme) [reply pkg/policy/portmap.go:36]: Added :-)

**Comment by jrajahalme** [comment]
Addressed Chris's comments and fixed a unit test broken by last refactoring.

**Comment by jrajahalme** [comment]
test-upstream-k8s

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-GKE

File: pkg/logging/limiter.go [hunk 12]
```diff
@@ -0,0 +1,47 @@
...
+	}
+}
+
+// Allow returns true if the log message is allowed under the
+// configured rate limit.
+func (ll Limiter) Allow() bool {
+	if ll.bucket == nil {
+		return true // limiter not initialized => no limit
+	}
+	return ll.bucket.Allow()
```
Comment (joestringer) [inline pkg/logging/limiter.go:46]: Should we add some metric when this returns false? I think it might be useful to know if we're dropping logs (+ at least the subsystem) and how many / how often.

This might be broader feedback for future usage of this limiter, but it's easier to ensure such capability is present from its first introduction.

File: pkg/policy/portmap.go [hunk 13]
```diff
@@ -0,0 +1,174 @@
...
+}
+
+// GetNamedPort returns the port number for the named port, if any.
+func (npm NamedPortMultiMap) GetNamedPort(name string, proto uint8) (uint16, error) {
+	if npm == nil {
+		return 0, ErrNilMap
+	}
+	pps, ok := npm[name]
+	if !ok {
+		// Return an error the caller can filer out as this happens only for egress policy
```
Comment (joestringer) [inline pkg/policy/portmap.go]: nit:

```suggestion
		// Return an error the caller can filter out as this happens only for egress policy
```

File: pkg/policy/l4.go [hunk 14]
```diff
@@ -273,26 +304,31 @@ func ParsePortProtocol(port int, protocol string) (np NamedPort, err error) {
...
 		return err
 	}
-	npm[name] = np
+	npm[name] = pp
 	return nil
 }
 
-func (npm NamedPortsMap) GetNamedPort(name string, proto uint8) (port uint16, err error) {
+// NamedPortMap abstracts different maps that implement GetNamedPort method
+type NamedPortsMap interface {
```
Comment (joestringer) [inline pkg/policy/l4.go]: nit: The comment is not consistent with the name of the interface.

Also, perhaps the `NamedPortMap` implementation should be something like `NamedPortSingleMap` to make it easier to tell the difference & not confuse whether code is referring to the interface or the concrete implementation?

File: pkg/endpoint/endpoint.go [hunk 15]
```diff
@@ -1171,6 +1171,14 @@ func (e *Endpoint) SetK8sMetadata(containerPorts []slim_corev1.ContainerPort) er
 	return nil
 }
 
+// GetK8sPorts returns the k8sPorts, which must not be modified by the caller
+func (e *Endpoint) GetK8sPorts() (k8sPorts policy.NamedPortMap) {
+	e.mutex.RLock()
```
Comment (joestringer) [inline pkg/endpoint/endpoint.go]: I'm not sure I understand the locking here. `pkg/endpoint/lock.go` has lock wrappers that attempt to protect us from various cases by for example propagating back up an error in the case that the endpoint disappears. 

We even have the `unconditionalRLock()` variations, including documentation, which do exactly what this is doing but have conditional comments to describe cases where it's OK to do this vs. `rlockAlive()`. Surely we should be using the wrappers rather than directly interacting with `e.mutex`, even if we decide that the actual logic here is OK because the caller has a reference to the endpoint object?

File: pkg/policy/l4.go [hunk 16]
```diff
@@ -963,12 +967,21 @@ func (l4 *L4Policy) AccumulateMapChanges(adds, deletes []identity.NumericIdentit
...
+		users[user] = struct{}{}
+	}
+	l4.mutex.RUnlock()
+
+	for epPolicy := range users {
 		// resolve named port
 		if port == 0 && l4Filter.PortName != "" {
 			var err error
-			port, err = epPolicy.NamedPortsMap.GetNamedPort(l4Filter.PortName, proto)
+			npMap := epPolicy.PolicyOwner.GetNamedPortsMap(direction == trafficdirection.Ingress)
```
Comment (joestringer) [inline pkg/policy/l4.go]: nit: performing comparisons to get the bool here to pass into `GetNamedPortsMap()` suggests that the callee should be taking `trafficdirection` directly (or otherwise why do we have a dedicated `trafficdirection` type?).

File: pkg/policy/resolve.go [hunk 17]
```diff
@@ -165,13 +162,15 @@ func (p *EndpointPolicy) computeDirectionL4PolicyMapEntries(l4PolicyMap L4Policy
 	for _, filter := range l4PolicyMap {
 		lookupDone := false
 		proxyport := uint16(0)
-		keysFromFilter := filter.ToMapState(p.NamedPortsMap, direction)
+		keysFromFilter := filter.ToMapState(p.PolicyOwner, direction)
 		for keyFromFilter, entry := range keysFromFilter {
 			// Fix up the proxy port for entries that need proxy redirection
 			if entry.IsRedirectEntry() {
-				if !lookupDone {
+				if !lookupDone && filter.IsRedirect() {
```
Comment (joestringer) [inline pkg/policy/resolve.go]: What's the implication of this extra check here? The entry is from `filter.ToMapState()`, so the filter must have a redirect otherwise presumably `entry.isRedirectEntry()` would return false ..?

**Review by joestringer — CHANGES_REQUESTED** [review]
Mostly minor style nits below. One possibly functional piece of feedback at the end.

File: pkg/logging/limiter.go (hunk 12 above)
Comment (jrajahalme) [reply pkg/logging/limiter.go:46]: Will have to leave this for a follow-on PR, as other PRs already depend on this one getting merged.

File: pkg/policy/portmap.go (hunk 13 above)
Comment (jrajahalme) [reply pkg/policy/portmap.go]: Fixed, thanks!

File: pkg/policy/l4.go (hunk 14 above)
Comment (jrajahalme) [reply pkg/policy/l4.go]: This interface is now removed in the latest version. Naming changes will have to wait for a folloow-on PR, if still deemed necessary.

File: pkg/policy/l4.go (hunk 16 above)
Comment (jrajahalme) [reply pkg/policy/l4.go]: Will have to clean this up in a follow-on PR. In this case, without wider refactoring, we'll have to use comparisons somewhere, as trafficdirection is not universally used yet.

File: pkg/endpoint/endpoint.go (hunk 15 above)
Comment (jrajahalme) [reply pkg/endpoint/endpoint.go]: Thanks for the reminder, I had completely overlooked this. Fixed.

File: pkg/policy/resolve.go (hunk 17 above)
Comment (jrajahalme) [reply pkg/policy/resolve.go]: This was a result of refactoring a corresponding check out of `LookupRedirectPortLocked()` (called below), but you are right, it is not needed due to filter's entry already being checked on the previous line. Removed :-)

**Comment by jrajahalme** [comment]
@joestringer Thanks for a thorough review. I'll have to leave some of the heavier lifting to follow-on PR, but I fixed the nits as indicated in the responses above.

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by aanm** [comment]
retest-net-next

File: pkg/endpoint/policy.go [hunk 18]
```diff
@@ -40,29 +41,89 @@ import (
...
+}
+
+func (e *Endpoint) getNamedPortIngress(npMap policy.NamedPortMap, name string, proto uint8) uint16 {
+	port, err := npMap.GetNamedPort(name, proto)
+	if err != nil && e.logLimiter.Allow() {
+		e.getLogger().WithFields(logrus.Fields{
+			logfields.PortName:         name,
+			logfields.Protocol:         u8proto.U8proto(proto).String(),
+			logfields.TrafficDirection: "ingress",
+		}).WithError(err).Warning("Skipping named port")
```
Comment (joestringer) [inline pkg/endpoint/policy.go:89]: Minor followup: This error condition is separate from the exact same message above on line 61 right? It would be helpful to have a way to distinguish the two in case this message is ever logged, so we know which case was hit.

**Review by joestringer — APPROVED** [review]
Minor followup comment, otherwise LGTM.

File: pkg/endpoint/policy.go (hunk 18 above)
Comment (aanm) [reply pkg/endpoint/policy.go:89]: @jrajahalme will take care of this as a follow up!
