### PR TITLE
bug: Prevent CiliumIdentities from Being Deleted Improperly

### LINKED ISSUE #19827: MasterKeyProtection never works with the CRD backend
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium never recreates master keys that are still in local use. It calls [crdBackend.UpdateKey](https://github.com/cilium/cilium/blob/dfa6b157e8e9484c65fd938b2b45a4f5f50c61f9/pkg/allocator/cache.go#L151) when a CiliumIdentity is removed, but UpdateKey does nothing because AcquireReference always returns nil. 
https://github.com/cilium/cilium/blob/dfa6b157e8e9484c65fd938b2b45a4f5f50c61f9/pkg/k8s/identitybackend/identity.go#L126

### Cilium Version

```
Client: 1.11.4 https://github.com/cilium/cilium/commit/9d2546357ef7302514f87b04534933c995340ec6 2022-04-15T08:33:55-07:00 go version go1.17.9 linux/amd64
Daemon: 1.11.4 9d25463 2022-04-15T08:33:55-07:00 go version go1.17.9 linux/amd64
```

### Kernel Version

```
$ uname -a
Linux rack0-cs5 5.15.32-flatcar #1 SMP Tue Apr 5 17:17:31 -00 2022 x86_64 AMD EPYC 7413 24-Core Processor AuthenticAMD GNU/Linux
```

### Kubernetes Version

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"archive", BuildDate:"2022-03-23T08:04:34Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
```

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by nathanjsweet**
Allocated CiliumIdentities can sometimes be improperly deleted before
being utilized. Instead of having the operator delete them immediately,
they are now "marked" for later deletion. This will give a Node a chance
to avoid racing the operator for the identity. If the CiliumIdentity
is going to be used by a Node the Node will see the mark for deletion
and remove it before utilizing the CiliumIdentity.

A race between unmarking for deletion on the Node and deletion
from the operator is avoided by enforcing a ResourceVersion
check on deletion in the operator logic.

Signed-off-by: Nate Sweet <nathanjsweet@pm.me>

```release-note
bug: Fixed a rare CiliumIdentity race deletion. 
```

Fixes: https://github.com/cilium/cilium/issues/19827

### CODE REVIEW

**Comment by timoreimann** [comment]
Hey @nathanjsweet 👋  thanks for this PR!

One quick question on the logic: IIUC, the problem to address here is that a CiliumEndpoint attempting to reference a CiliumIdentity could race with the operator that garbage-collects the identity too soon. I'm trying to understand how the change fixes the problem -- wouldn't we only shift the timing in the sense that CiliumEndpoints coming up near the end of the heartbeat interval could now race with the operator?

**Comment by nathanjsweet** [comment]
> One quick question on the logic: IIUC, the problem to address here is that a CiliumEndpoint attempting to reference a CiliumIdentity could race with the operator that garbage-collects the identity too soon.

@timoreimann That's my understanding as well. Here is how I see the race condition being eliminated:

1. A `CiliumIdentity` (`CI`) is marked for deletion by the operator.
2. The agent/node detects that the `CI` is marked for deletion but tries to recover it for a `CiliumEndpoint`. The agent/node will try to remove the heartbeat annotation from the `CI`. It will either fail to update the `CI` (because the `CI` was already deleted) or it will succeed (and the K8s API will bump the `ResourceVersion`).
3.  If the operator is in the process of deleting the `CI` at the same time, it will either succeed, in which case the agent will be unable to update a deleted resource (then `AcquireReference`  on the agent/node will return an error), or it will fail because the agent/node successfully removed the annotation, causing the K8s API  to bump the `ResourceVersion` and ensuring the [delete precondition](https://github.com/cilium/cilium/blob/1407761b4b20ad18aba8737d89c855472266cc49/operator/k8s_identity.go#L44) will not be met.

Does that make sense? Or is there a scenario that I've missed?

File: pkg/k8s/identitybackend/identity.go [hunk 1]
```diff
@@ -106,8 +110,43 @@ func (c *crdBackend) AllocateIDIfLocked(ctx context.Context, id idpool.ID, key a
...
+	)
+	// check to see if the cached copy of the identity
+	// has the annotation
+	ci, exists, err := c.getById(ctx, id)
+	if exists && err == nil {
+		ts, ok = ci.Annotations[HeartBeatAnnotation]
+	}
+	// double check the identity does not have the annotation
+	if !ok {
+		ci, err = c.Client.CiliumV2().CiliumIdentities().Get(ctx, id.String(), metav1.GetOptions{})
```
Comment (aanm) [inline pkg/k8s/identitybackend/identity.go]: why are we doing API call? The `c.getById` should contain the last information of the cilium identity.

**Review by aanm — CHANGES_REQUESTED** [review]

**Comment by aanm** [comment]
> > One quick question on the logic: IIUC, the problem to address here is that a CiliumEndpoint attempting to reference a CiliumIdentity could race with the operator that garbage-collects the identity too soon.
> 
> @timoreimann That's my understanding as well. Here is how I see the race condition being eliminated:
> 
> 1. A `CiliumIdentity` (`CI`) is marked for deletion by the operator.
> 2. The agent/node detects that the `CI` is marked for deletion but tries to recover it for a `CiliumEndpoint`. The agent/node will try to remove the heartbeat annotation from the `CI`. It will either fail to update the `CI` (because the `CI` was already deleted) or it will succeed (and the K8s API will bump the `ResourceVersion`).
> 3. If the operator is in the process of deleting the `CI` at the same time, it will either succeed, in which case the agent will be unable to update a deleted resource (then `AcquireReference`  on the agent/node will return an error), or it will fail because the agent/node successfully removed the annotation, causing the K8s API  to bump the `ResourceVersion` and ensuring the [delete precondition](https://github.com/cilium/cilium/blob/1407761b4b20ad18aba8737d89c855472266cc49/operator/k8s_identity.go#L44) will not be met.
> 
> Does that make sense? Or is there a scenario that I've missed?

@nathanjsweet that make sense. I think what Timo is asking is about this case:
> it will either succeed, in which case the agent will be unable to update a deleted resource (then `AcquireReference`  on the agent/node will return an error)

If this happens, what will the agent do? Will it retry to create the identity? Will it create a new identity? It would be nice to know what will be the behavior.

File: pkg/k8s/identitybackend/identity.go (hunk 1 above)
Comment (nathanjsweet) [reply pkg/k8s/identitybackend/identity.go]: Why is that the case? Isn't there the possibility of the operator adding the mark for deletion after the cache is refreshed?

**Comment by nathanjsweet** [comment]
> If this happens, what will the agent do? Will it retry to create the identity? Will it create a new identity? It would be nice to know what will be the behavior.

@aanm I see. At this point, `AcuireReference` will fail, and it will try to recreate the new identity. 99% of the time this will be because the CI was deleted and the recreation should work as expected. If there is some other reason that it fails (like a brief network blip that causes the API call to fail) then I think we could get some undefined behavior where the local node could end up using a deleted CI (like now). There will be a discernible log message for this situation though ("OnDelete MasterKeyProtection update for key").

File: pkg/k8s/identitybackend/identity.go (hunk 1 above)
Comment (nathanjsweet) [reply pkg/k8s/identitybackend/identity.go]: NVM, I understand this now.

**Review by aanm — APPROVED** [review]

**Comment by timoreimann** [comment]
Would the recreation of the identity function the same way in the master code today?

I'm asking because we have been seeing this supposed edge case happening frequently enough that I wouldn't want to attribute it to network blips or similar.

**Comment by nathanjsweet** [comment]
> Would the recreation of the identity by the agent function the same way in the master code today?

Actually, the recreation of the identity was not happening. `AcquireReference` always returning `nil` made it so that a recreation of the CI would never happen. This code finally makes `AcquireReference` do the right thing and actually try to lock the CI from being deleted.

> I'm asking because we have been seeing this supposed edge case happening frequently enough that I wouldn't want to attribute it to network blips or similar scenarios only.

@timoreimann It makes sense that you're seeing it a fair amount now. This change will make it very unlikely that you will ever see this problem again. However, I wanted to be honest that there is still a quite rare, theoretical case where a failing call to the K8 API would cause the local node to continue to use a GC'd CI. Even in the case of a node having a network outage or something like that, the chance of a GC'd CI being used would be low (presumably an "out" node would not be creating new pods, etc).

**Comment by timoreimann** [comment]
Got it, appreciate the extra context. This sounds like a great improvement over the status quo, looking forward to seeing it released. 🎉

Related, do you plan on backporting this back to 1.9? We are still on that Cilium version for critical parts of our infrastructure and would love to see the known identity problems fully fixed. (I submitted a fix for a related problem some time ago.)

**Comment by ysksuzuki** [comment]
@nathanjsweet Hi, thank you for the PR! Let me ask two questions about the PR.

> `AcuireReference` will fail, and it will try to recreate the new identity. 99% of the time this will be because the CI was deleted and the recreation should work as expected.

1. In the rest of 1%, cilium-agent successfully removes the heartbeat annotation and bumps the resource revision, and the operator's deletion fails because of the revision conflict. Is my understanding correct?
2. If the cilium-agent always recreates the new CiliumIdentity that is still in local use regardless of the heartbeat annotation, would that cause any problem?

**Comment by nathanjsweet** [comment]
@ysksuzuki

> In the rest of 1%, cilium-agent successfully removes the heartbeat annotation and bumps the resource revision, and the operator fails to delete it because of the revision conflict. Is my understanding correct?

No, that falls within the 99% case. That failure mode is acceptable because the identity will have already been deleted by the operator, so recreating the identity is safe.

[See my edited comment above](https://github.com/cilium/cilium/pull/19936#issuecomment-1137804976). The 1% (more like 0.001%, actually) failure mode is also an acceptable and obvious failure mode as any kind of API failure (e.g. network outage, key-store failure, et al) will simply result in failed recreation of the CI. It probably would never happen though as a lot of things would have to coincide for that to occur.

> If the cilium-agent always recreates the CiliumIdentity that is still in local use regardless of the heartbeat annotation, would that cause any problem? I still don't understand the necessity of the heartbeat annotation.

The recreation logic assumes that the failure to acquire the CI (and thus remove its heartbeat annotation) means that the CI does not exist. We need some way of locking deletion. Simply checking to see if the CI already exists (something that wasn't being done; `AcquireReference` was simply always "returning true") isn't enough and would also be less efficient. If we only checked if the CI existed (without the heartbeat annotation) it could still be getting deleted out from underneath the agent by the operator. The annotation works as a delete-reference lock, so if it is present the agent knows it must truly "acquire reference" rather than just continuing to use the CI.

The recreation logic was actually never even being used because (as I stated previously) `AcquireReference` was always "returning true" (`nil` actually, but you know what I mean). This change will allow us to finally take advantage of the recreation logic, which also protects us from the case where the operator wrongly deletes an in-use CI.

Does that make sense?

**Comment by ysksuzuki** [comment]
@nathanjsweet Thank you for your comment.

> No, that falls within the 99% case. That failure mode is acceptable because the identity will have already been deleted by the operator, so recreating the identity is safe.

UpdateKey is triggered by the CiliumIdentity's Delete event which means that AcquireReference is called when the operator actually deleted the CiliumIdentity. I doubt that the cilium agent can update the CiliumIdentity that is already removed. If the cilium agent needs to detect the operator marked a CiliumIdentity for the deletion beforehand, I think it needs to watch other events like the Update event.

**Comment by nathanjsweet** [comment]
> UpdateKey is triggered by the CiliumIdentity's Delete event which means that AcquireReference is called after the operator actually deleted the CiliumIdentity. 

That is not the only code path that calls into `UpdateKey` (and thus `AcquireReference`). Also, deletions of a CiliumIdentity can happen from other events other than the operator GC sweep.

> I doubt that the cilium agent has a chance to update the CiliumIdentity that has been already removed.

There is a definite possibility that `AcquireReference` can be in the middle of running while the CiliumIdentity is also being deleted by the operator (the listening behavior is not atomic). This will, of course, result in either `AcquireReference` failing or in the cilium agent recreating the CiliumIdentity.

> If the cilium agent needs to detect the operator marked a CiliumIdentity for the deletion beforehand, I think it needs to watch other events like the Update event.

We already do listen to update events for CiliumIdentities. You'll notice that this code does not prefetch the CiliumIdentity on the agent side; it simply checks to see if the annotation is present. We need some form of "final" communication between the agent and the operator to prevent the operator from deleting an in-use CiliumIdentity, **or** to prevent the agent from using an already-deleted CiliumIdentity (thus allowing the agent to recreate it).

> And if we will have the Cilium agent recreate the CiliumIdentity that has already been deleted by the operator, I think we need to consider the possibility that the Cilium agent is down when the operator deletes the CiliumIdentity.

I'm not sure I fully understand what you're saying here. That the operator logic should factor in the agent being down as it deletes a CiliumIdentity? If so, then there's no need. It is acceptable for the operator to GC a CiliumIdentity that will be used by the agent later as long as the agent can recreate the CiliumIdentity.

**Comment by ysksuzuki** [comment]
@nathanjsweet Thank you for the explanation. I will take a look at the CiliumIdentity handling logic again.

I tested this PR. The cilium agent didn't remove the heartbeat annotation after I annotate it to a CiliumIdentity that is referenced a CiliumEndpoint. And I could remove the CiliumIdentity. Is this the expected behavior?

I will test #19877 scenario as well.

```
$ kubectl -n dctest get ciliumendpoints.cilium.io
NAME                           ENDPOINT ID   IDENTITY ID   INGRESS ENFORCEMENT   EGRESS ENFORCEMENT   VISIBILITY POLICY   ENDPOINT STATE   IPV4         IPV6
suzuki-test-6958b4575b-pdlpv   1271          56713                                                                        ready            10.64.0.65   fe80::3cb5:edff:febb:5cd3

$ kubectl annotate ciliumidentities.cilium.io 56713 io.cilium.heartbeat=hoge

$ kubectl get ciliumidentities.cilium.io 56713 -o yaml
apiVersion: cilium.io/v2
kind: CiliumIdentity
metadata:
  annotations:
    io.cilium.heartbeat: hoge
  creationTimestamp: "2022-06-10T23:43:53Z"
  generation: 1
  labels:
    app.kubernetes.io/name: suzuki-test
    io.cilium.k8s.policy.cluster: default
    io.cilium.k8s.policy.serviceaccount: default
    io.kubernetes.pod.namespace: dctest
  name: "56713"
  resourceVersion: "789334"
  uid: 6a569138-76ea-4e6b-9690-79a628563436
security-labels:
  k8s:app.kubernetes.io/name: suzuki-test
  k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name: dctest
  k8s:io.cilium.k8s.policy.cluster: default
  k8s:io.cilium.k8s.policy.serviceaccount: default
  k8s:io.kubernetes.pod.namespace: dctest

$ kubectl delete ciliumidentities.cilium.io 56713
ciliumidentity.cilium.io "56713" deleted

$ kubectl get ciliumidentities.cilium.io 56713 -o yaml
Error from server (NotFound): ciliumidentities.cilium.io "56713" not found
```

**Comment by ysksuzuki** [comment]
I tested with this PR but the operator panicked. I think Annotations need to be initialized when it's nil.

```
level=info msg="Marking identity for later deletion" identity="&{{CiliumIdentity cilium.io/v2} {9173    deac3f58-598c-4ebf-91b5-12fe92f63a95 103617 1 2022-06-11 02:06:26 +0000 UTC <nil> <nil> map[deployVersion:v2 gossip_ring_member:true io.cilium.k8s.policy.cluster:default io.cilium.k8s.policy.serviceaccount:default io.kubernetes.pod.namespace:logging name:ingester statefulset.kubernetes.io/pod-name:ingester-0] map[] [] []  [{cilium-agent Update cilium.io/v2 2022-06-11 02:06:26 +0000 UTC FieldsV1 {\"f:metadata\":{\"f:labels\":{\".\":{},\"f:deployVersion\":{},\"f:gossip_ring_member\":{},\"f:io.cilium.k8s.policy.cluster\":{},\"f:io.cilium.k8s.policy.serviceaccount\":{},\"f:io.kubernetes.pod.namespace\":{},\"f:name\":{},\"f:statefulset.kubernetes.io/pod-name\":{}}},\"f:security-labels\":{\".\":{},\"f:k8s:deployVersion\":{},\"f:k8s:gossip_ring_member\":{},\"f:k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/instance\":{},\"f:k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name\":{},\"f:k8s:io.cilium.k8s.namespace.labels.pod-security.cybozu.com/policy\":{},\"f:k8s:io.cilium.k8s.namespace.labels.team\":{},\"f:k8s:io.cilium.k8s.policy.cluster\":{},\"f:k8s:io.cilium.k8s.policy.serviceaccount\":{},\"f:k8s:io.kubernetes.pod.namespace\":{},\"f:k8s:name\":{},\"f:k8s:statefulset.kubernetes.io/pod-name\":{}}} }]} map[k8s:deployVersion:v2 k8s:gossip_ring_member:true k8s:io.cilium.k8s.namespace.labels.app.kubernetes.io/instance:namespaces k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name:logging k8s:io.cilium.k8s.namespace.labels.pod-security.cybozu.com/policy:privileged k8s:io.cilium.k8s.namespace.labels.team:neco k8s:io.cilium.k8s.policy.cluster:default k8s:io.cilium.k8s.policy.serviceaccount:default k8s:io.kubernetes.pod.namespace:logging k8s:name:ingester k8s:statefulset.kubernetes.io/pod-name:ingester-0]}" subsys=cilium-operator-generic
panic: assignment to entry in nil map

goroutine 394 [running]:
main.identityGCIteration({0x27594a0, 0xc000797000})
        /go/src/github.com/cilium/cilium/operator/k8s_identity.go:117 +0x67c
main.startCRDIdentityGC.func1({0x27594a0, 0xc000797000})
        /go/src/github.com/cilium/cilium/operator/k8s_identity.go:171 +0x25
github.com/cilium/cilium/pkg/controller.(*Controller).runController(0xc000e8cc60)
        /go/src/github.com/cilium/cilium/pkg/controller/controller.go:206 +0x1bb
created by github.com/cilium/cilium/pkg/controller.(*Manager).updateController
        /go/src/github.com/cilium/cilium/pkg/controller/manager.go:111 +0xb45
```

**Comment by ysksuzuki** [comment]
Tested #19877 scenario with this PR patched to fix the operator panic and the permission error and confirmed that the cilium-agent called [syncLocalKeys](https://github.com/cilium/cilium/blob/6f9fedd43cc369b27f5a5a4c8a0634fe7629fe01/pkg/allocator/allocator.go#L839) to protect the CiliumIdentity.

```
# operator annotate the heartbeat
level=info msg="Marking identity for later deletion" identity="&{{ } {30888    3a263ea8-ba4e-447a-b117-a813340673b5 534113 1 2022-06-11 07:48:26 +0000 UTC <nil> <nil> map[app.kubernetes.io/name:suzuki-test io.cilium.k8s.policy.cluster:default io.cilium.k8s.policy.serviceaccount:default io.kubernetes.pod.namespace:dctest statefulset.kubernetes.io/pod-name:suzuki-test-0 suzuki-test.cybozu.com/role:primary] map[] [] []  [{cilium-agent Update cilium.io/v2 2022-06-11 07:48:26 +0000 UTC FieldsV1 {\"f:metadata\":{\"f:labels\":{\".\":{},\"f:app.kubernetes.io/name\":{},\"f:io.cilium.k8s.policy.cluster\":{},\"f:io.cilium.k8s.policy.serviceaccount\":{},\"f:io.kubernetes.pod.namespace\":{},\"f:statefulset.kubernetes.io/pod-name\":{},\"f:suzuki-test.cybozu.com/role\":{}}},\"f:security-labels\":{\".\":{},\"f:k8s:app.kubernetes.io/name\":{},\"f:k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name\":{},\"f:k8s:io.cilium.k8s.namespace.labels.pod-security.cybozu.com/policy\":{},\"f:k8s:io.cilium.k8s.policy.cluster\":{},\"f:k8s:io.cilium.k8s.policy.serviceaccount\":{},\"f:k8s:io.kubernetes.pod.namespace\":{},\"f:k8s:statefulset.kubernetes.io/pod-name\":{},\"f:k8s:suzuki-test.cybozu.com/role\":{}}} }]} map[k8s:app.kubernetes.io/name:suzuki-test k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name:dctest k8s:io.cilium.k8s.namespace.labels.pod-security.cybozu.com/policy:privileged k8s:io.cilium.k8s.policy.cluster:default k8s:io.cilium.k8s.policy.serviceaccount:default k8s:io.kubernetes.pod.namespace:dctest k8s:statefulset.kubernetes.io/pod-name:suzuki-test-0 k8s:suzuki-test.cybozu.com/role:primary]}" subsys=cilium-operator-generic
level=info msg="Updated identity" identity=30888 subsys=cilium-operator-generic

# cilium-agent removed the heartbeat annotation
level=info msg="Identity marked for deletion (at 2022-06-11T08:49:28.003645696Z); attempting to unmark it" identity="&{{ } {30888    3a263ea8-ba4e-447a-b117-a813340673b5 547879 1 2022-06-11 07:48:26 +0000 UTC <nil> <nil> map[app.kubernetes.io/name:suzuki-test io.cilium.k8s.policy.cluster:default io.cilium.k8s.policy.serviceaccount:default io.kubernetes.pod.namespace:dctest statefulset.kubernetes.io/pod-name:suzuki-test-0 suzuki-test.cybozu.com/role:primary] map[io.cilium.heartbeat:2022-06-11T08:49:28.003645696Z] [] []  [{cilium-agent Update cilium.io/v2 2022-06-11 07:48:26 +0000 UTC FieldsV1 {\"f:metadata\":{\"f:labels\":{\".\":{},\"f:app.kubernetes.io/name\":{},\"f:io.cilium.k8s.policy.cluster\":{},\"f:io.cilium.k8s.policy.serviceaccount\":{},\"f:io.kubernetes.pod.namespace\":{},\"f:statefulset.kubernetes.io/pod-name\":{},\"f:suzuki-test.cybozu.com/role\":{}}},\"f:security-labels\":{\".\":{},\"f:k8s:app.kubernetes.io/name\":{},\"f:k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name\":{},\"f:k8s:io.cilium.k8s.namespace.labels.pod-security.cybozu.com/policy\":{},\"f:k8s:io.cilium.k8s.policy.cluster\":{},\"f:k8s:io.cilium.k8s.policy.serviceaccount\":{},\"f:k8s:io.kubernetes.pod.namespace\":{},\"f:k8s:statefulset.kubernetes.io/pod-name\":{},\"f:k8s:suzuki-test.cybozu.com/role\":{}}} } {cilium-operator-generic Update cilium.io/v2 2022-06-11 08:49:28 +0000 UTC FieldsV1 {\"f:metadata\":{\"f:annotations\":{\".\":{},\"f:io.cilium.heartbeat\":{}}}} }]} map[k8s:app.kubernetes.io/name:suzuki-test k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name:dctest k8s:io.cilium.k8s.namespace.labels.pod-security.cybozu.com/policy:privileged k8s:io.cilium.k8s.policy.cluster:default k8s:io.cilium.k8s.policy.serviceaccount:default k8s:io.kubernetes.pod.namespace:dctest k8s:statefulset.kubernetes.io/pod-name:suzuki-test-0 k8s:suzuki-test.cybozu.com/role:primary]}" subsys=crd-allocator
```

However, the recreation logic triggered by the Delete event didn't work. The cilium-agent failed to remove the heartbeat annotation and the CiliumIdentity finally got deleted by the operator, but cilium-agent couldn't abort the deletion nor recreate the CiliumIdentity.  When the UpdateKey is triggered by the Delete event, the CiliumIdentity has been already removed from the in-memory-cache and AcquireReference returns nil. So the cilium-agent did nothing. I think we need to improve this. What do you think?

```
level=info msg="Marking identity for later deletion" identity="&{{ } {966    0d3af146-a2a5-4931-9663-613c89006d82 253891 1 2022-06-11 04:21:52 +0000 UTC <nil> <nil> map[app.kubernetes.io/name:suzuki-test io.cilium.k8s.policy.cluster:default io.cilium.k8s.policy.serviceaccount:default io.kubernetes.pod.namespace:dctest statefulset.kubernetes.io/pod-name:suzuki-test-0 suzuki-test.cybozu.com/role:primary] map[] [] []  [{cilium-agent Update cilium.io/v2 2022-06-11 04:21:52 +0000 UTC FieldsV1 {\"f:metadata\":{\"f:labels\":{\".\":{},\"f:app.kubernetes.io/name\":{},\"f:io.cilium.k8s.policy.cluster\":{},\"f:io.cilium.k8s.policy.serviceaccount\":{},\"f:io.kubernetes.pod.namespace\":{},\"f:statefulset.kubernetes.io/pod-name\":{},\"f:suzuki-test.cybozu.com/role\":{}}},\"f:security-labels\":{\".\":{},\"f:k8s:app.kubernetes.io/name\":{},\"f:k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name\":{},\"f:k8s:io.cilium.k8s.namespace.labels.pod-security.cybozu.com/policy\":{},\"f:k8s:io.cilium.k8s.policy.cluster\":{},\"f:k8s:io.cilium.k8s.policy.serviceaccount\":{},\"f:k8s:io.kubernetes.pod.namespace\":{},\"f:k8s:statefulset.kubernetes.io/pod-name\":{},\"f:k8s:suzuki-test.cybozu.com/role\":{}}} }]} map[k8s:app.kubernetes.io/name:suzuki-test k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name:dctest k8s:io.cilium.k8s.namespace.labels.pod-security.cybozu.com/policy:privileged k8s:io.cilium.k8s.policy.cluster:default k8s:io.cilium.k8s.policy.serviceaccount:default k8s:io.kubernetes.pod.namespace:dctest k8s:statefulset.kubernetes.io/pod-name:suzuki-test-0 k8s:suzuki-test.cybozu.com/role:primary]}" subsys=cilium-operator-generic
level=info msg="Updated identity" identity=966 subsys=cilium-operator-generic
level=info msg="Garbage collected identity" identity=966 subsys=cilium-operator-generic
```

**Comment by nathanjsweet** [comment]
@ysksuzuki 

> Tested https://github.com/cilium/cilium/issues/19877 scenario with this PR patched to fix the operator panic and the permission error and confirmed that the cilium-agent called [syncLocalKeys](https://github.com/cilium/cilium/blob/6f9fedd43cc369b27f5a5a4c8a0634fe7629fe01/pkg/allocator/allocator.go#L839) to protect the CiliumIdentity.

Wow! fantastic work. Thank you for doing that.

What I wrote didn't fix `AcquireReference`. If there's an error getting the identity, the current code will still "return true" (nil). Pushing a fix.

**Comment by ysksuzuki** [comment]
@nathanjsweet Tested #19877 scenario again and confirmed this patch is working as expected. Thanks for the fix!

File: operator/k8s_identity.go [hunk 2]
```diff
@@ -52,6 +53,20 @@ func deleteIdentity(ctx context.Context, identity *v2.CiliumIdentity) error {
...
 
+func updateIdentity(ctx context.Context, identity *v2.CiliumIdentity) error {
+	_, err := ciliumK8sClient.CiliumV2().CiliumIdentities().Update(
+		ctx,
+		identity,
+		metav1.UpdateOptions{})
+	if err != nil {
+		log.WithError(err).Error("Updating Identity")
+	} else {
+		log.WithField(logfields.Identity, identity.GetName()).Info("Updated identity")
```
Comment (gandro) [inline operator/k8s_identity.go]: Does this need to be `loglevel=info`? It might be a bit noisy in large clusters.

File: pkg/k8s/identitybackend/identity.go [hunk 3]
```diff
@@ -106,8 +110,45 @@ func (c *crdBackend) AllocateIDIfLocked(ctx context.Context, id idpool.ID, key a
...
+	ts, ok = ci.Annotations[HeartBeatAnnotation]
+	if ok {
+		log.WithField(logfields.Identity, ci).Infof("Identity marked for deletion (at %s); attempting to unmark it", ts)
+		delete(ci.Annotations, HeartBeatAnnotation)
+		_, err = c.Client.CiliumV2().CiliumIdentities().Update(ctx, ci, metav1.UpdateOptions{})
+		if err != nil {
+			// put the annotation back, as it was not
+			// actually deleted.
+			ci.Annotations[HeartBeatAnnotation] = ts
+			return err
```
Comment (gandro) [inline pkg/k8s/identitybackend/identity.go]: So this looks like we're mutating the cached `ci` here, i.e. this write to `ci.Annotations` is reflected in the store? Is this write operation here thread safe?

**Review by gandro — COMMENTED** [review]
Looks good overall! One question about mutating the cached identity (see inline comment)

File: pkg/k8s/identitybackend/identity.go (hunk 3 above)
Comment (nathanjsweet) [reply pkg/k8s/identitybackend/identity.go]: This write is a reversion of the cache back to its previous state, because the update failed. Is it thread-safe? Not exactly, but this should be a rare occurrence, and no other code references the identity Annotations so it should be safe by default (as no other code in the Agent references this part of the identity).

File: operator/k8s_identity.go (hunk 2 above)
Comment (nathanjsweet) [reply operator/k8s_identity.go]: Good point.

File: pkg/k8s/identitybackend/identity.go (hunk 3 above)
Comment (gandro) [reply pkg/k8s/identitybackend/identity.go]: If this codepath is rarely used, then let's copy the identity type via `ci.DeepCopy()` before we manipulate it.

I am very nervous about knowingly adding a data race. Since we also run CI on master with the data race detector enabled, this might introduce additional flakes, which I want to avoid as well.

File: operator/k8s_identity.go [hunk 4]
```diff
@@ -96,9 +111,25 @@ func identityGCIteration(ctx context.Context) {
 			continue
 		}
 		if !identityHeartbeat.IsAlive(identity.Name) {
+			if identity.Annotations == nil {
+				identity.Annotations = make(map[string]string)
+			}
+			ts, ok := identity.Annotations[identitybackend.HeartBeatAnnotation]
+			if !ok {
+				log.WithField(logfields.Identity, identity).Info("Marking identity for later deletion")
+				identity.Annotations[identitybackend.HeartBeatAnnotation] = timeNow.Format(time.RFC3339Nano)
```
Comment (gandro) [inline operator/k8s_identity.go:121]: This mutation here also updates the object in the cache, correct? Then it's also a data race I believe.

**Comment by nathanjsweet** [comment]
./test

**Review by gandro — APPROVED** [review]
Thanks a lot!

**Comment by nathanjsweet** [comment]
Seems like gke is failing because it is appending a "}" to the image names and they can't spin up a working cluster as all the image references are wrong.

**Comment by nathanjsweet** [comment]
I can confirm that this fix still works after modifying it slightly to update CIs using only cloned references (to avoid local data races).

**Comment by nathanjsweet** [comment]
We've had a full suite of successful tests. Only GKE is failing. I'm going to rebase, and if GKE passes I'm marking this as ready-to-merge.

File: install/kubernetes/cilium/templates/cilium-operator/clusterrole.yaml [hunk 5]
```diff
@@ -120,6 +120,13 @@ rules:
   - delete
   - list
   - watch
```
Comment (pchaigno) [inline install/kubernetes/cilium/templates/cilium-operator/clusterrole.yaml:122]: I see this PR is marked for backports into v1.10 but the above permissions (seem related to current PR) don't exist in v1.10. Is that expected? Do we need to backport something else?

Comment (nathanjsweet) [reply install/kubernetes/cilium/templates/cilium-operator/clusterrole.yaml:122]: So this part of the PR would be unnecessary. Because [this permission](https://github.com/cilium/cilium/blob/v1.10/install/kubernetes/cilium/templates/cilium-operator-clusterrole.yaml#L125) gives cilium-operator the permissions it needs and [this permission](https://github.com/cilium/cilium/blob/v1.10/install/kubernetes/cilium/templates/cilium-agent-clusterrole.yaml#L86) gives cilium-agent everything it needs. We reworked them in v1.12 to be more specific.

Comment (pchaigno) [reply install/kubernetes/cilium/templates/cilium-operator/clusterrole.yaml:122]: Oh, I see. Thanks for the explanation!
