### PR TITLE
Fix channel panic from ipcache kvstore reconnect

### LINKED ISSUE #15667: Fix possible panic on closed channel
If the connection restarts in https://github.com/cilium/cilium/blob/ad322a1764657c89d0677208b6dfba75101b5d85/pkg/ipcache/kvstore.go#L231-L242

the channel in
https://github.com/cilium/cilium/blob/ad322a1764657c89d0677208b6dfba75101b5d85/pkg/ipcache/kvstore.go#L274

might be closed more than one time causing a panic.

### PR DESCRIPTION
**Pull request by jomenxiao**
possible panic on closed channel with more than one time
fix #15667 

Signed-off-by: Jomen Xiao jomenxiao@gmail.com

### CODE REVIEW

File: pkg/ipcache/kvstore.go [hunk 1]
```diff
@@ -359,6 +360,13 @@ func (iw *IPIdentityWatcher) Close() {
 	})
 }
 
+//CloseSynced the IPIdentityWathcer and case panic
+func (iw *IPIdentityWatcher) CloseSynced() {
```
Comment (aanm) [inline pkg/ipcache/kvstore.go]: just a small nit, this function can be made private.

**Review by aanm — CHANGES_REQUESTED** [review]
LGTM, just a small nit.

**Review by aanm — APPROVED** [review]
Thank you!.

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

File: pkg/ipcache/kvstore.go [hunk 2]
```diff
@@ -271,7 +272,7 @@ restart:
 					listener.OnIPIdentityCacheGC()
 				}
 				IPIdentityCache.Unlock()
-				close(iw.synced)
+				iw.closeSynced()
```
Comment (joestringer) [inline pkg/ipcache/kvstore.go:275]: This is part of a "restart" block. Does this mean that if kvstore resynchronization must happen, we will start leaking these channels?

Comment (joestringer) [reply pkg/ipcache/kvstore.go:275]: I guess not because it's part of the current IPIdentityWatcher `iw` which only really signals synchronization once to the main daemon code. Never mind :+1:
