### PR TITLE
ipsec: do not nil out EncryptInterface when using IPAM ENI on netlink…

### LINKED ISSUE #33507: IPsec errors in 1.15.6
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After upgrading to 1.15.6 we see node frequently go into a bad state when trying to update IPsec configuration, at least going by the logs.  I see it often correlate with a device change message with the addition of a new ENI.

I see [this](https://github.com/cilium/cilium/blob/a09e05e6b63d82dbc3a1b0de1721a3407c340e7c/pkg/datapath/linux/ipsec/ipsec_linux.go#L909) comment about "file exist" errors, so I'm not sure if this is a legitimate problem or not.

Rotating the ipsec key is the only thing that seems to resolve this state.

Notes:
* We are using per-tunnel PSKs with ipsec

### Cilium Version

1.15.6

### Kernel Version

5.15.156-102.160.amzn2.x86_64

### Kubernetes Version

EKS 1.27

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell
time="2024-07-01T14:47:05Z" level=error msg="Failed to get local IPv4 for IPsec configuration" error="Link not found" subsys=linux-datapath

time="2024-07-01T14:47:05Z" level=error msg="Failed to add XFRM state due to conflicting state" destinationIP=10.34.81.11 nodeID=0x4f64 sourceIP="<nil>" spi=13 subsys=ipsec trafficDirection=ingress

time="2024-07-01T14:47:05Z" level=error msg="IPsec enable failed" error="unable to replace remote state: file exists" localIP=0.0.0.0/0 nodeID=0x4f64 reason="out IPv4" remoteIP=10.33.0.0/24 spi=0 subsys=linux-datapath

time="2024-07-01T14:47:05Z" level=error msg="Failed to add XFRM state due to conflicting state" destinationIP=10.34.81.11 nodeID=0x4f64 sourceIP="<nil>" spi=13 subsys=ipsec trafficDirection=ingress

time="2024-07-01T14:47:05Z" level=error msg="IPsec enable failed" error="unable to replace remote state: file exists" localIP=0.0.0.0/0 nodeID=0x4f64 reason="out IPv4" remoteIP=10.33.44.0/22 spi=0 subsys=linux-datapath

time="2024-07-01T14:47:05Z" level=error msg="Failed to add XFRM state due to conflicting state" destinationIP="<nil>" nodeID=0x4f64 sourceIP=10.34.81.11 spi=13 subsys=ipsec trafficDirection=ingress

time="2024-07-01T14:47:05Z" level=error msg="IPsec enable failed" error="unable to replace local state: file exists" localIP=0.0.0.0/0 nodeID=0x4f64 reason="in NodeInternalIPv4" remoteIP=10.33.44.0/22 spi=0 subsys=linux-datapath

time="2024-07-01T14:47:05Z" level=error msg="Failed to add XFRM state due to conflicting state" destinationIP=10.34.81.11 nodeID=0x4f64 sourceIP="<nil>" spi=13 subsys=ipsec trafficDirection=ingress

time="2024-07-01T14:47:05Z" level=error msg="IPsec enable failed" error="unable to replace remote state: file exists" localIP=0.0.0.0/0 nodeID=0x4f64 reason="out IPv4" remoteIP=10.33.128.0/25 spi=0 subsys=linux-datapath

time="2024-07-01T14:47:05Z" level=error msg="Failed to add XFRM state due to conflicting state" destinationIP="<nil>" nodeID=0x4f64 sourceIP=10.34.81.11 spi=13 subsys=ipsec trafficDirection=ingress

time="2024-07-01T14:47:05Z" level=error msg="IPsec enable failed" error="unable to replace local state: file exists" localIP=0.0.0.0/0 nodeID=0x4f64 reason="in NodeInternalIPv4" remoteIP=10.33.128.0/25 spi=0 subsys=linux-datapath

time="2024-07-01T14:47:05Z" level=error msg="Failed to add XFRM state due to conflicting state" destinationIP=10.34.81.11 nodeID=0x4f64 sourceIP="<nil>" spi=13 subsys=ipsec trafficDirection=ingress

time="2024-07-01T14:47:05Z" level=error msg="IPsec enable failed" error="unable to replace remote state: file exists" localIP=0.0.0.0/0 nodeID=0x4f64 reason="out IPv4" remoteIP=10.33.192.0/25 spi=0 subsys=linux-datapath

time="2024-07-01T14:47:05Z" level=error msg="Failed to add XFRM state due to conflicting state" destinationIP="<nil>" nodeID=0x4f64 sourceIP=10.34.81.11 spi=13 subsys=ipsec trafficDirection=ingress

time="2024-07-01T14:47:05Z" level=error msg="IPsec enable failed" error="unable to replace local state: file exists" localIP=0.0.0.0/0 nodeID=0x4f64 reason="in NodeInternalIPv4" remoteIP=10.33.192.0/25 spi=0 subsys=linux-datapath

time="2024-07-01T14:47:05Z" level=error msg="Failed to add XFRM state due to conflicting state" destinationIP=10.34.81.11 nodeID=0x4f64 sourceIP="<nil>" spi=13 subsys=ipsec trafficDirection=ingress

time="2024-07-01T14:47:05Z" level=error msg="IPsec enable failed" error="unable to replace remote state: file exists" localIP=0.0.0.0/0 nodeID=0x4f64 reason="out IPv4" remoteIP=10.34.64.0/19 spi=0 subsys=linux-datapath

time="2024-07-01T14:47:05Z" level=error msg="Failed to add XFRM state due to conflicting state" destinationIP="<nil>" nodeID=0x4f64 sourceIP=10.34.81.11 spi=13 subsys=ipsec trafficDirection=ingress

time="2024-07-01T14:47:05Z" level=error msg="IPsec enable failed" error="unable to replace local state: file exists" localIP=0.0.0.0/0 nodeID=0x4f64 reason="in NodeInternalIPv4" remoteIP=10.34.64.0/19 spi=0 subsys=linux-datapath

time="2024-07-01T14:47:05Z" level=error msg="Failed to add XFRM state due to conflicting state" destinationIP=10.34.81.11 nodeID=0x4f64 sourceIP="<nil>" spi=13 subsys=ipsec trafficDirection=ingress

time="2024-07-01T14:47:05Z" level=error msg="IPsec enable failed" error="unable to replace remote state: file exists" localIP=0.0.0.0/0 nodeID=0x4f64 reason="out IPv4" remoteIP=100.64.0.0/16 spi=0 subsys=linux-datapath

time="2024-07-01T14:47:05Z" level=error msg="Failed to add XFRM state due to conflicting state" destinationIP="<nil>" nodeID=0x4f64 sourceIP=10.34.81.11 spi=13 subsys=ipsec trafficDirection=ingress

time="2024-07-01T14:47:05Z" level=error msg="IPsec enable failed" error="unable to replace local state: file exists" localIP=0.0.0.0/0 nodeID=0x4f64 reason="in NodeInternalIPv4" remoteIP=100.64.0.0/16 spi=0 subsys=linux-datapath

time="2024-07-01T14:47:05Z" level=error msg="Failed to apply node handler during background sync. Cilium may have degraded functionality. See error message for details." error="failed to get local ipv4 for ipsec link: Link not found\nfailed to enable ipsec with out IPv4 using local IP 0.0.0.0/0, rem 10.33.0.0/24, spi 0: unable to replace remote state: file exists\nfailed to enable ipsec with out IPv4 using local IP 0.0.0.0/0, rem 10.33.44.0/22, spi 0: unable to replace remote state: file exists\nfailed to enable ipsec with in NodeInternalIPv4 using local IP 0.0.0.0/0, rem 10.33.44.0/22, spi 0: unable to replace local state: file exists\nfailed to enable ipsec with out IPv4 using local IP 0.0.0.0/0, rem 10.33.128.0/25, spi 0: unable to replace remote state: file exists\nfailed to enable ipsec with in NodeInternalIPv4 using local IP 0.0.0.0/0, rem 10.33.128.0/25, spi 0: unable to replace local state: file exists\nfailed to enable ipsec with out IPv4 using local IP 0.0.0.0/0, rem 10.33.192.0/25, spi 0: unable to replace remote state: file exists\nfailed to enable ipsec with in NodeInternalIPv4 using local IP 0.0.0.0/0, rem 10.33.192.0/25, spi 0: unable to replace local state: file exists\nfailed to enable ipsec with out IPv4 using local IP 0.0.0.0/0, rem 10.34.64.0/19, spi 0: unable to replace remote state: file exists\nfailed to enable ipsec with in NodeInternalIPv4 using local IP 0.0.0.0/0, rem 10.34.64.0/19, spi 0: unable to replace local state: file exists\nfailed to enable ipsec with out IPv4 using local IP 0.0.0.0/0, rem 100.64.0.0/16, spi 0: unable to replace remote state: file exists\nfailed to enable ipsec with in NodeInternalIPv4 using local IP 0.0.0.0/0, rem 100.64.0.0/16, spi 0: unable to replace local state: file exists" handler=linux-node-datapath node=ip-10-34-81-11.ec2.internal subsys=nodemanager
```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jasonaliyetti**
….LinkList() error

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

netlink.LinkList() can return an error due to a Kernel interrupt.  This can lead to inadvertently nilling out the EncryptInterface config when using IPAM ENI which leads to IPsec breaking.  

This change will retry the netlink.LinkList() call and surface an error instead for nilling the EncryptInterface configuration.

Fixes: #33507

### CODE REVIEW

**Review by dylandreimerink — COMMENTED** [review]
I understand that the early return makes it so we don't nil out the EncryptInterface on error. But I am a bit skeptical about the retry mechanism. Did you actually encounter transient errors which are fixed with a simple retry or is this based on a guess/assumption?

If the root cause is an error which persists or is caused by a specific situation, then this only adds a bunch of delay

Edit: Nevermind, I missed the PR description. Could you please add that explanation in the commit message as well as add a comment on the code explaining its purpose is to retry on kernel interrupts.

File: pkg/datapath/loader/base.go [hunk 1]
```diff
@@ -161,6 +167,24 @@ func cleanIngressQdisc(devices []string) error {
...
+		sleep := backoff.CalculateDuration(
+			linkListMinRetryInterval,
+			linkListMaxRetryInterval,
+			2.0,
+			false,
+			try)
+		time.Sleep(sleep)
+	}
+
+	return nil, errors.New("Could not load links")
```
Comment (dylandreimerink) [inline pkg/datapath/loader/base.go]: Can you use fmt.Errorf and then pass the original error as well with %w so that the original error can be debugged if it comes to this point.

File: pkg/datapath/loader/base.go [hunk 2]
```diff
@@ -161,6 +167,24 @@ func cleanIngressQdisc(devices []string) error {
 	return nil
 }
 
+func linkList() ([]netlink.Link, error) {
```
Comment (dylandreimerink) [inline pkg/datapath/loader/base.go:172]: Please add a comment here and in the commit message explaining the reason for the retries.

**Review by dylandreimerink — CHANGES_REQUESTED** [review]

File: pkg/datapath/loader/base.go (hunk 1 above)
Comment (jasonaliyetti) [reply pkg/datapath/loader/base.go]: Done

File: pkg/datapath/loader/base.go (hunk 2 above)
Comment (jasonaliyetti) [reply pkg/datapath/loader/base.go:172]: Done

**Review by dylandreimerink — APPROVED** [review]

**Comment by jasonaliyetti** [comment]
I saw PRs for backports.  Is there any chance of this getting into the current batch of backports?  I'm very eager to get this upgrade in soon and am not sure when the cutoff is for backports during the patch cycle.

**Comment by dylandreimerink** [comment]
Once merged it will be picked up, but I don't know where we currently are in the patch release cycle, so I can't say if the fix will make it into the upcoming or next patch release.

Do you happen to know if this effects Cilium versions older than 1.15?

**Comment by jasonaliyetti** [comment]
I'm pretty sure it'd impact 1.14 and 1.13.
