### PR TITLE
lbmap: Correct issue that port info display error

### LINKED ISSUE #13243: lbmap：Port information display error
- Cilium version: master latest version
- Kernel version 
uname -a
Linux jianlin 5.9.0-rc1+ #3 SMP Thu Aug 20 09:05:37 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

The endianness of my test environment is little endian;
The port information displayed by given maps(cilium_lb4_services_v2/cilium_lb4_backends/cilium_lb4_reverse_nat) is incorrect;
The port info is stored in network byte order;

```
root@jianlin:/home/jianlin/code/cilium-install# lscpu |grep Endian
Byte Order:                      Little Endian
root@jianlin:/home/jianlin/code/cilium-install# kubectl exec -it -n kube-system cilium-5dmnz -- cilium map get cilium_lb4_services_v2
Key                    Value                    State   Error
172.16.1.236:20480     0 (1024) [FLAGS: 0x40]   sync
10.169.208.214:21630   0 (1280) [FLAGS: 0x42]   sync
0.0.0.0:21630          0 (1536) [FLAGS: 0x2]    sync
172.16.1.1:47873       0 (256) [FLAGS: 0x40]    sync
172.16.1.10:49443      0 (768) [FLAGS: 0x40]    sync
172.16.1.10:13568      0 (512) [FLAGS: 0x40]    sync
root@jianlin:/home/jianlin/code/cilium-install# kubectl exec -it -n kube-system cilium-5dmnz -- cilium map get cilium_lb4_backends
Key   Value                    State   Error
6     ANY://10.0.0.89:20480    sync
7     ANY://10.0.1.230:20480   sync
8     ANY://10.0.1.219:20480   sync
root@jianlin:/home/jianlin/code/cilium-install# kubectl exec -it -n kube-system cilium-5dmnz -- cilium map get cilium_lb4_reverse_nat
Key    Value                  State   Error
1280   10.169.208.214:21630   sync
1536   0.0.0.0:21630          sync
256    172.16.1.1:47873       sync
768    172.16.1.10:49443      sync
512    172.16.1.10:13568      sync
1024   172.16.1.236:20480     sync
root@jianlin:/home/jianlin/code/cilium-install# kubectl exec -it -n kube-system cilium-5dmnz -- cilium service list
ID   Frontend               Service Type   Backend
1    172.16.1.1:443         ClusterIP      1 => 10.169.208.214:6443
2    172.16.1.10:53         ClusterIP      1 => 10.0.0.85:53
                                           2 => 10.0.0.100:53
3    172.16.1.10:9153       ClusterIP      1 => 10.0.0.85:9153
                                           2 => 10.0.0.100:9153
4    172.16.1.236:80        ClusterIP      1 => 10.0.0.89:80
                                           2 => 10.0.1.230:80
                                           3 => 10.0.1.219:80
5    10.169.208.214:32340   NodePort       1 => 10.0.0.89:80
                                           2 => 10.0.1.230:80
                                           3 => 10.0.1.219:80
6    0.0.0.0:32340          NodePort       1 => 10.0.0.89:80
                                           2 => 10.0.1.230:80
                                           3 => 10.0.1.219:80

*************************************************

root@jianlin:/home/jianlin/code/cilium-install# kubectl exec -it -n kube-system cilium-5dmnz -- bpftool map dump pinned /sys/fs/bpf/tc/globals/cilium_lb4_services_v2
key: 00 00 00 00 7e 54 01 00  00 00 00 00  value: 06 00 00 00 00 00 00 06  00 00 00 00
key: 00 00 00 00 7e 54 00 00  00 00 00 00  value: 00 00 00 00 03 00 00 06  02 00 00 00
key: 00 00 00 00 7e 54 03 00  00 00 00 00  value: 08 00 00 00 00 00 00 06  00 00 00 00
key: 0a a9 d0 d6 7e 54 01 00  00 00 00 00  value: 07 00 00 00 00 00 00 05  00 00 00 00
key: 00 00 00 00 7e 54 02 00  00 00 00 00  value: 07 00 00 00 00 00 00 06  00 00 00 00
key: ac 10 01 0a 00 35 00 00  00 00 00 00  value: 00 00 00 00 02 00 00 02  40 00 00 00
key: 0a a9 d0 d6 7e 54 00 00  00 00 00 00  value: 00 00 00 00 03 00 00 05  42 00 00 00
key: ac 10 01 0a 23 c1 00 00  00 00 00 00  value: 00 00 00 00 02 00 00 03  40 00 00 00
key: ac 10 01 ec 00 50 02 00  00 00 00 00  value: 07 00 00 00 00 00 00 04  00 00 00 00
key: ac 10 01 0a 23 c1 02 00  00 00 00 00  value: 05 00 00 00 00 00 00 03  00 00 00 00
key: ac 10 01 01 01 bb 00 00  00 00 00 00  value: 00 00 00 00 01 00 00 01  40 00 00 00
key: 0a a9 d0 d6 7e 54 03 00  00 00 00 00  value: 06 00 00 00 00 00 00 05  00 00 00 00
key: ac 10 01 0a 00 35 01 00  00 00 00 00  value: 02 00 00 00 00 00 00 02  00 00 00 00
key: 0a a9 d0 d6 7e 54 02 00  00 00 00 00  value: 08 00 00 00 00 00 00 05  00 00 00 00
key: ac 10 01 0a 23 c1 01 00  00 00 00 00  value: 03 00 00 00 00 00 00 03  00 00 00 00
key: ac 10 01 0a 00 35 02 00  00 00 00 00  value: 04 00 00 00 00 00 00 02  00 00 00 00
key: ac 10 01 ec 00 50 00 00  00 00 00 00  value: 00 00 00 00 03 00 00 04  40 00 00 00
key: ac 10 01 01 01 bb 01 00  00 00 00 00  value: 01 00 00 00 00 00 00 01  00 00 00 00
key: ac 10 01 ec 00 50 03 00  00 00 00 00  value: 08 00 00 00 00 00 00 04  00 00 00 00
key: ac 10 01 ec 00 50 01 00  00 00 00 00  value: 06 00 00 00 00 00 00 04  00 00 00 00
Found 20 elements
root@jianlin:/home/jianlin/code/cilium-install# kubectl exec -it -n kube-system cilium-5dmnz -- bpftool map dump pinned /sys/fs/bpf/tc/globals/cilium_lb4_backends
key: 02 00  value: 0a 00 00 55 00 35 00 00
key: 01 00  value: 0a a9 d0 d6 19 2b 00 00
key: 04 00  value: 0a 00 00 64 00 35 00 00
key: 08 00  value: 0a 00 01 db 00 50 00 00
key: 03 00  value: 0a 00 00 55 23 c1 00 00
key: 05 00  value: 0a 00 00 64 23 c1 00 00
key: 07 00  value: 0a 00 01 e6 00 50 00 00
key: 06 00  value: 0a 00 00 59 00 50 00 00
Found 8 elements
root@jianlin:/home/jianlin/code/cilium-install# kubectl exec -it -n kube-system cilium-5dmnz -- bpftool map dump pinned /sys/fs/bpf/tc/globals/cilium_lb4_reverse_nat
key: 00 05  value: 0a a9 d0 d6 7e 54
key: 00 01  value: ac 10 01 01 01 bb
key: 00 06  value: 00 00 00 00 7e 54
key: 00 04  value: ac 10 01 ec 00 50
key: 00 02  value: ac 10 01 0a 00 35
key: 00 03  value: ac 10 01 0a 23 c1
Found 6 elements

```

### PR DESCRIPTION
**Pull request by Jianlin-lv**
The port info is stored in the bpf map in network byte order;

bpftool map dump pinned /sys/fs/bpf/tc/globals/cilium_lb4_backends
key: 02 00  value: 0a 00 00 55 00 35 00 00
key: 01 00  value: 0a a9 d0 d6 19 2b 00 00
key: 04 00  value: 0a 00 00 64 00 35 00 00
key: 08 00  value: 0a 00 01 db 00 50 00 00
key: 03 00  value: 0a 00 00 55 23 c1 00 00
key: 05 00  value: 0a 00 00 64 23 c1 00 00
key: 07 00  value: 0a 00 01 e6 00 50 00 00
key: 06 00  value: 0a 00 00 59 00 50 00 00

cilium map get cilium_lb4_backends
Key   Value                    State   Error
6     ANY://10.0.0.89:20480    sync
7     ANY://10.0.1.230:20480   sync
8     ANY://10.0.1.219:20480   sync

When displaying the given lbmap content, the port needs to be
converted to host byte order.

cilium map get cilium_lb4_backends
Key   Value                 State   Error
8     ANY://10.0.0.64:80    sync
6     ANY://10.0.1.158:80   sync
7     ANY://10.0.1.66:80    sync

Signed-off-by: Jianlin Lv <Jianlin.Lv@arm.com>

Fixes: #13243

### CODE REVIEW

**Comment by qmonnet** [comment]
test-me-please

**Review by pchaigno — CHANGES_REQUESTED** [review]
Isn't the same issue present for the three IPv6 maps?

**Comment by Jianlin-lv** [comment]
> Isn't the same issue present for the three IPv6 maps?

Thanks for reminding, I will check it.

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
test-me-please

**Comment by Jianlin-lv** [comment]
> Isn't the same issue present for the three IPv6 maps?

@pchaigno  I want to honestly let you know that I have not verified this patch in my test environment;
Because I don’t have an ipv6 experimental environment, today I spent a long time building k8s cluster that supports IPv4/IPv6 dual-stack networking, but the cilium agent only received ipv4 service information; I don’t know what is wrong, nor how to set up a pure ipv6 network in the cluster.
In short, I did not successfully verify the patch.

**Comment by pchaigno** [comment]
No problem, I was expecting this; IPv6-only clusters are a bit painful to setup. I think that's fine since we both tested on IPv4 and the change is fairly trivial. I'll ask on Slack how folks usually setup their IPv6-only clusters, but I don't think we need to block on that.

**Comment by qmonnet** [comment]
test-me-please

**Comment by Jianlin-lv** [comment]
Please note, I will append a new patch to this RP to fix a newly discovered issue tomorrow.

**Comment by borkmann** [comment]
Please also add some CI tests, verifying that the output of `cilium service list`, `cilium bpf lb list` and `cilium map get cilium_lb*_backends` works as expected.

I just looked at one of the sysdumps from the CI and see the following:

The `cilium service list` looks okay:
```
ID   Frontend             Service Type   Backend                   
1    10.106.162.7:3000    ClusterIP                                
2    10.111.80.118:9090   ClusterIP      1 => 10.0.0.83:9090       
3    10.96.0.1:443        ClusterIP      1 => 192.168.36.11:6443   
4    10.96.0.10:53        ClusterIP      1 => 10.0.1.62:53         
```

But the `cilium bpf lb list` doesn't (though it was correct before the PR):
```
SERVICE ADDRESS       BACKEND ADDRESS
10.106.162.7:47115    0.0.0.0:0 (1) [ClusterIP]   
10.96.0.1:47873       192.168.36.11:6443 (3)      
                      0.0.0.0:0 (3) [ClusterIP]   
10.96.0.10:13568      0.0.0.0:0 (4) [ClusterIP]   
                      10.0.1.62:53 (4)            
10.111.80.118:33315   10.0.0.83:9090 (2)          
                      0.0.0.0:0 (2) [ClusterIP]   
```

**Comment by Jianlin-lv** [comment]
> Please also add some CI tests, verifying that the output of `cilium service list`, `cilium bpf lb list` and `cilium map get cilium_lb*_backends` works as expected.
> 
> I just looked at one of the sysdumps from the CI and see the following:
> 
> The `cilium service list` looks okay:
> 
> ```
> ID   Frontend             Service Type   Backend                   
> 1    10.106.162.7:3000    ClusterIP                                
> 2    10.111.80.118:9090   ClusterIP      1 => 10.0.0.83:9090       
> 3    10.96.0.1:443        ClusterIP      1 => 192.168.36.11:6443   
> 4    10.96.0.10:53        ClusterIP      1 => 10.0.1.62:53         
> ```
> 
> But the `cilium bpf lb list` doesn't (though it was correct before the PR):
> 
> ```
> SERVICE ADDRESS       BACKEND ADDRESS
> 10.106.162.7:47115    0.0.0.0:0 (1) [ClusterIP]   
> 10.96.0.1:47873       192.168.36.11:6443 (3)      
>                       0.0.0.0:0 (3) [ClusterIP]   
> 10.96.0.10:13568      0.0.0.0:0 (4) [ClusterIP]   
>                       10.0.1.62:53 (4)            
> 10.111.80.118:33315   10.0.0.83:9090 (2)          
>                       0.0.0.0:0 (2) [ClusterIP]   
> ```

What you found is correct. I am fixing this problem today and solved the RevNatKey display issue.
After applying this patch, the execution result of lb cmd as follows:
```
root@jianlin:~# kubectl exec -it -n kube-system cilium-mzrbn -- cilium service list
ID   Frontend               Service Type   Backend
1    172.16.1.10:53         ClusterIP      1 => 10.0.0.199:53
                                           2 => 10.0.0.111:53
2    172.16.1.10:9153       ClusterIP      1 => 10.0.0.199:9153
                                           2 => 10.0.0.111:9153
3    172.16.1.1:443         ClusterIP      1 => 10.169.208.214:6443
4    172.16.1.13:80         ClusterIP      1 => 10.0.1.144:80
                                           2 => 10.0.0.236:80
                                           3 => 10.0.1.78:80
5    10.169.208.214:31427   NodePort       1 => 10.0.1.144:80
                                           2 => 10.0.0.236:80
                                           3 => 10.0.1.78:80
6    0.0.0.0:31427          NodePort       1 => 10.0.1.144:80
                                           2 => 10.0.0.236:80
                                           3 => 10.0.1.78:80
root@jianlin:~# kubectl exec -it -n kube-system cilium-mzrbn --  cilium bpf lb list
SERVICE ADDRESS        BACKEND ADDRESS
172.16.1.10:9153       10.0.0.111:9153 (2)
                       10.0.0.199:9153 (2)
                       0.0.0.0:0 (2) [ClusterIP]
172.16.1.10:53         10.0.0.111:53 (1)
                       0.0.0.0:0 (1) [ClusterIP]
                       10.0.0.199:53 (1)
0.0.0.0:31427          10.0.1.144:80 (6)
                       10.0.0.236:80 (6)
                       0.0.0.0:0 (6) [NodePort, non-routable]
                       10.0.1.78:80 (6)
172.16.1.1:443         10.169.208.214:6443 (3)
                       0.0.0.0:0 (3) [ClusterIP]
172.16.1.13:80         10.0.1.78:80 (4)
                       10.0.0.236:80 (4)
                       0.0.0.0:0 (4) [ClusterIP]
                       10.0.1.144:80 (4)
10.169.208.214:31427   0.0.0.0:0 (5) [NodePort]
                       10.0.1.144:80 (5)
                       10.0.1.78:80 (5)
                       10.0.0.236:80 (5)
root@jianlin:~# kubectl exec -it -n kube-system cilium-mzrbn -- cilium map get cilium_lb4_services_v2
Key                    Value                 State   Error
172.16.1.10:53         0 (1) [FLAGS: 0x40]   sync
172.16.1.10:9153       0 (2) [FLAGS: 0x40]   sync
172.16.1.1:443         0 (3) [FLAGS: 0x40]   sync
172.16.1.13:80         0 (4) [FLAGS: 0x40]   sync
10.169.208.214:31427   0 (5) [FLAGS: 0x42]   sync
0.0.0.0:31427          0 (6) [FLAGS: 0x2]    sync
root@jianlin:~# kubectl exec -it -n kube-system cilium-mzrbn -- cilium map get cilium_lb4_backends
Key   Value                       State   Error
5     ANY://10.0.0.236:80         sync
6     ANY://10.0.0.111:9153       sync
7     ANY://10.0.0.111:53         sync
8     ANY://10.0.1.78:80          sync
1     ANY://10.169.208.214:6443   sync
2     ANY://10.0.0.199:9153       sync
3     ANY://10.0.0.199:53         sync
4     ANY://10.0.1.144:80         sync
root@jianlin:~# kubectl exec -it -n kube-system cilium-mzrbn -- cilium map get cilium_lb4_reverse_nat
Key   Value                  State   Error
4     172.16.1.13:80         sync
5     10.169.208.214:31427   sync
6     0.0.0.0:31427          sync
1     172.16.1.10:53         sync
2     172.16.1.10:9153       sync
3     172.16.1.1:443         sync

```

**Comment by pchaigno** [comment]
test-me-please

File: pkg/maps/lbmap/affinity.go [hunk 1]
```diff
@@ -103,7 +103,9 @@ func (k *AffinityMatchKey) GetKeyPtr() unsafe.Pointer { return unsafe.Pointer(k)
 func (v *AffinityMatchValue) GetValuePtr() unsafe.Pointer { return unsafe.Pointer(v) }
 
 // String converts the key into a human readable string format
-func (k *AffinityMatchKey) String() string { return fmt.Sprintf("%d %d", k.BackendID, k.RevNATID) }
+func (k *AffinityMatchKey) String() string {
```
Comment (brb) [inline pkg/maps/lbmap/affinity.go:99]: Some of the structs implement the `ToNetwork()` method. Have you considered adding `ToHost()` method? Same applies to all other changed `String()` methods.

File: pkg/maps/lbmap/ipv4.go [hunk 2]
```diff
@@ -56,7 +56,7 @@ var (
 				return nil, nil, err
 			}
 
-			return svcKey.ToNetwork(), svcVal.ToNetwork(), nil
+			return svcKey, svcVal.ToNetwork(), nil
```
Comment (brb) [inline pkg/maps/lbmap/ipv4.go]: Instead of calling `svcVal.ToNetwork()` we should really call `svcVal.ToHost()` (the method is not yet implemented).

**Review by brb — CHANGES_REQUESTED** [review]

**Comment by Jianlin-lv** [comment]
Fixed an issue that is when restarting cilium, Service`s port does not match;
Report by: https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/1939/execution/node/100/log/

**Comment by Jianlin-lv** [comment]
test-me-please

File: pkg/maps/lbmap/affinity.go (hunk 1 above)
Comment (Jianlin-lv) [reply pkg/maps/lbmap/affinity.go:99]: Encapsulating the conversion byte order to host is a good idea;
In addition, during the debugging process, I feel that the readability of the dumped information is not very friendly; lack of prompt information to help users understand the output;
I plan to make some improvements and optimizations for these issues in the next few days.

**Comment by pchaigno** [comment]
test-me-please

**Comment by Jianlin-lv** [comment]
Squash commits into one.

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
test-me-please

File: cilium/cmd/bpf_lb_list.go [hunk 3]
```diff
@@ -66,7 +68,17 @@ func dumpSVC(serviceList map[string][]string) {
 
 		svcKey := key.(lbmap.ServiceKey)
 		svcVal := value.(lbmap.ServiceValue)
-		svc := svcKey.String()
+		svc := net.JoinHostPort(svcKey.GetAddress().String(), fmt.Sprintf("%d", svcKey.GetPort()))
```
Comment (brb) [inline cilium/cmd/bpf_lb_list.go]: Could you explain why this change is needed, i.e. why calling `svcKey.String()` is not enough?

**Review by brb — CHANGES_REQUESTED** [review]
Are you planning to change https://github.com/cilium/cilium/pull/13244#discussion_r496743141 and others? Also, one comment re `svcKey.String()`.

File: cilium/cmd/bpf_lb_list.go (hunk 3 above)
Comment (Jianlin-lv) [reply cilium/cmd/bpf_lb_list.go]: That callback function parseSVCEntry receive the actual key and value by DumpParser()
```
lbmap.Service4MapV2.DumpWithCallbackIfExists
->m.DumpWithCallback
	->mk, mv, err = m.DumpParser(nextKey, value, mk, mv)
```
svcKey`s byte order has been changed before been return.
https://github.com/cilium/cilium/blob/master/pkg/maps/lbmap/ipv4.go#L59

This patch squash commits into one and also refer to your comment.

Comment (brb) [reply cilium/cmd/bpf_lb_list.go]: Couldn't you do `svcKey.ToNetwork().String()` instead to DRY? Anyway, this looks hacky to me. One idea is to avoid changing endianness in the dump parsers and only do it in the `String()` methods. Otherwise, we are risking accidentally mixing endianness because it gets more difficult to track in what order structs are. WDYT?

Comment (Jianlin-lv) [reply cilium/cmd/bpf_lb_list.go]: Agree with you,
I`m preparing another patch that gets rid of ToNetwork() in DumpParser(); 
I plan to submit another PR to complete this optimization.

Comment (brb) [reply cilium/cmd/bpf_lb_list.go]: Thanks. Could you put this change in the same PR?

**Comment by brb** [comment]
test-me-please

**Comment by Jianlin-lv** [comment]
> test-me-please

Cilium-Ginkgo-GKE failed with a reported issue： https://github.com/cilium/cilium/issues/13554

https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/2814/execution/node/139/log/?consoleFull

File: cilium/cmd/bpf_lb_list.go [hunk 4]
```diff
@@ -65,7 +65,7 @@ func dumpSVC(serviceList map[string][]string) {
 		var entry string
 
 		svcKey := key.(lbmap.ServiceKey)
```
Comment (brb) [inline cilium/cmd/bpf_lb_list.go:67]: `svcKey` is used in the few places afterwards. I think it would be safer if you do `svcKey = svcKey.ToHost()` after `svc := svcKey.String()`.

File: pkg/maps/lbmap/ipv4.go [hunk 5]
```diff
@@ -56,7 +56,7 @@ var (
 				return nil, nil, err
 			}
 
-			return svcKey.ToNetwork(), svcVal.ToNetwork(), nil
+			return svcKey, svcVal, nil
```
Comment (brb) [inline pkg/maps/lbmap/ipv4.go]: All changed callback parsers can be replaced with `bpf.ConvertKeyValue`.

**Review by brb — CHANGES_REQUESTED** [review]
A few more things (see comments below). Also, could you apply similar changes to `pkg/maps/lbmap/source_range.go`?

**Comment by brb** [comment]
@Jianlin-lv Thanks. However, there is a conflict with `pkg/maps/lbmap/ipv{4,6}.go`. Could you rebase against the latest master?

**Comment by Jianlin-lv** [comment]
> @Jianlin-lv Thanks. However, there is a conflict with `pkg/maps/lbmap/ipv{4,6}.go`. Could you rebase against the latest master?

Sure, I`m rebasing now.

**Comment by brb** [comment]
test-me-please

**Review by brb — APPROVED** [review]

**Review by aanm — CHANGES_REQUESTED** [review]
the following files have their permissions being changed from 644 to 755:
cilium/cmd/bpf_lb_list.go
pkg/maps/lbmap/affinity.go
pkg/maps/lbmap/ipv4.go
pkg/maps/lbmap/ipv6.go
pkg/maps/lbmap/lbmap.go
pkg/maps/lbmap/source_range.go
Please keep the file permissions unmodified.

**Comment by Jianlin-lv** [comment]
> the following files have their permissions being changed from 644 to 755:
> cilium/cmd/bpf_lb_list.go
> pkg/maps/lbmap/affinity.go
> pkg/maps/lbmap/ipv4.go
> pkg/maps/lbmap/ipv6.go
> pkg/maps/lbmap/lbmap.go
> pkg/maps/lbmap/source_range.go
> Please keep the file permissions unmodified.

Done, Thanks

**Comment by brb** [comment]
@aanm Considering that the tests have previously passed, we don't need to re-run them.

**Review by tklauser — APPROVED** [review]

**Review by vadorovsky — APPROVED** [review]

**Review by aanm — APPROVED** [review]
