### PR TITLE
bgp test: return error from upsertBGPCC

### LINKED ISSUE #44434: CI: operator/pkg/bgp: flake in TestRouterIDAllocation: the object has been modified; resource version mismatch
```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃   FAIL  package: github.com/cilium/cilium/operator/pkg/bgp   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

--- FAIL: TestRouterIDAllocation (3.12s)
--- FAIL: TestRouterIDAllocation/multiple_nodes_and_multiple_instances_with_single_cluster_configs_and_cleanup_the_2_instances_in_the_cluster_config (1.20s)

    logger.go:256: time=2026-02-19T08:39:14.258Z level=INFO source=/home/runner/work/cilium/cilium/vendor/github.com/cilium/hive/hive.go:385 msg="Starting hive"
    logger.go:256: time=2026-02-19T08:39:14.259Z level=INFO source=/home/runner/work/cilium/cilium/vendor/github.com/cilium/hive/hive.go:389 msg="Started hive" duration=45.779µs
    logger.go:256: time=2026-02-19T08:39:14.459Z level=INFO source=/home/runner/work/cilium/cilium/operator/pkg/bgp/manager.go:151 msg="BGP control plane operator started" module=bgp-cp-operator
    cluster_test.go:1637: 
        	Error Trace:	/home/runner/work/cilium/cilium/operator/pkg/bgp/cluster_test.go:1637
        	            				/home/runner/work/cilium/cilium/operator/pkg/bgp/cluster_test.go:1577
        	            				/opt/hostedtoolcache/go/1.26.0/x64/src/runtime/asm_amd64.s:1771
        	Error:      	Received unexpected error:
        	            	Operation cannot be fulfilled on ciliumbgpclusterconfigs.cilium.io "test-cc-multi-node": the object has been modified; resource version mismatch, current "18", got "15"
        	Test:       	TestRouterIDAllocation/multiple_nodes_and_multiple_instances_with_single_cluster_configs_and_cleanup_the_2_instances_in_the_cluster_config
    logger.go:256: time=2026-02-19T08:39:15.461Z level=INFO source=/home/runner/work/cilium/cilium/vendor/github.com/cilium/hive/hive.go:401 msg="Stopping hive"
    logger.go:256: time=2026-02-19T08:39:15.461Z level=INFO source=/home/runner/work/cilium/cilium/vendor/github.com/cilium/hive/hive.go:405 msg="Stopped hive" duration=601.289µs
```

https://github.com/cilium/cilium/actions/runs/22174214293/job/64118716945

Can easily be reproduced locally using `go test -c ./operator/pkg/bgp && stress ./bgp.test`.

cc @cilium/sig-bgp

### PR DESCRIPTION
**Pull request by liyihuang**
Changes upsertBGPCC helper function to return an error so it can handle EventuallyWith test case.

running go test -c ./operator/pkg/bgp && stress ./bgp.test for 5 mins now and dont see the issue anymore
```
5m0s: 312 runs so far, 0 failures, 12 active
5m5s: 317 runs so far, 0 failures, 12 active
5m10s: 323 runs so far, 0 failures, 12 active
```

Fixes: #44434

```release-note
fix the race condition for the TestRouterIDAllocation bgp test case
```

### CODE REVIEW

**Review by rastislavs — APPROVED** [review]
Thanks!

File: operator/pkg/bgp/cluster_test.go [hunk 1]
```diff
@@ -1574,7 +1575,9 @@ func TestRouterIDAllocation(t *testing.T) {
 				// version even after receiving an event for the new version.
 				if tt.FinalClusterConfigs != nil {
 					for _, clusterConfig := range tt.FinalClusterConfigs {
-						upsertBGPCC(req, ctx, f, clusterConfig)
+						if err := upsertBGPCC(ctx, f, clusterConfig); !assert.NoError(c, err) {
```
Comment (joestringer) [inline operator/pkg/bgp/cluster_test.go:1578]: nit: `!assert.NoError()` is pretty confusing due to the way different people interpret double negatives. Assertions should probably be unconditional too, or parameterized in the test if there's a legitimate error condition the test is looking for.

Comment (joestringer) [reply operator/pkg/bgp/cluster_test.go:1578]: I'll go ahead and merge this as-is given the approval from @rastislavs  but this seems like some minor tech debt we should consider improving on (also for all other instances in this testsuite, cc @cilium/sig-bgp ).

Comment (liyihuang) [reply operator/pkg/bgp/cluster_test.go:1578]: https://github.com/cilium/cilium/pull/44588 to clear this tech debt
