### PR TITLE
datapath: Support NodePort BPF on L2-less devices

### LINKED ISSUE #12317: NodePort fails when using IP attached to interface without HW address
## Bug report

**General Information**

- Cilium version : 1.8.0
- Kernel version : 5.3.0-59-generic 
- Orchestration system version in use : v1.15.9

**How to reproduce the issue**

When deploying Cilium, network iface auto-discovery doesn't work with our networking design. We need to explicitly define `--global.devices=eth0` to have Cilium running, but in this configuration, we are not able to establish a connection to a NodePort service.

I can provide some details on our network stack : 

- IPs to use are attached to the loopback, and are exported using Exabgp. The physical device is 'eth0'

```# ip r
default proto exabgp src 10.189.20.54 metric 500
	nexthop via 10.129.119.2 dev eth0 weight 1
	nexthop via 10.129.119.1 dev eth0 weight 1
```

```1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet 10.189.20.54/32 scope global lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 20:47:47:80:a8:d4 brd ff:ff:ff:ff:ff:ff
    inet 10.129.119.3/25 brd 10.129.119.127 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::2247:47ff:fe80:a8d4/64 scope link
       valid_lft forever preferred_lft forever
```

With this setup, Cilium's startup script is not able to detect eth0 as network interface

```level=error msg="Command execution failed" cmd="[/var/lib/cilium/bpf/init.sh /var/lib/cilium/bpf /var/run/cilium/state 10.174.66.75 <nil> direct lo <nil> <nil> 1500 false <nil> true true false /var/run/cilium/cgroupv2 /sys/fs/bpf true true v2 lo=0x3614bd0a <nil>]" error="exit status 1" subsys=datapath-loader
level=warning msg="+ set -o pipefail" subsys=datapath-loader
level=warning msg="++ command -v cilium-map-migrate" subsys=datapath-loader
level=warning msg="+ [[ ! -n /usr/bin/cilium-map-migrate ]]" subsys=datapath-loader
level=warning msg="+ rm /var/run/cilium/state/encap.state" subsys=datapath-loader
level=warning msg="+ true" subsys=datapath-loader
level=warning msg="+ DIR=/run/cilium/state/globals" subsys=datapath-loader
level=warning msg="+ case \"${MODE}\" in" subsys=datapath-loader
level=warning msg="+ HOST_DEV1=cilium_host" subsys=datapath-loader
level=warning msg="+ HOST_DEV2=cilium_net" subsys=datapath-loader
level=warning msg="+ setup_veth_pair cilium_host cilium_net" subsys=datapath-loader
level=warning msg="+ local -r NAME1=cilium_host" subsys=datapath-loader
level=warning msg="+ local -r NAME2=cilium_net" subsys=datapath-loader
level=warning msg="++ ip link show cilium_host type veth" subsys=datapath-loader
level=warning msg="++ cut -d ' ' -f 2" subsys=datapath-loader
level=warning msg="+ '[' cilium_host@cilium_net: '!=' cilium_host@cilium_net: ']'" subsys=datapath-loader
level=warning msg="+ setup_dev cilium_host" subsys=datapath-loader
level=warning msg="+ local -r NAME=cilium_host" subsys=datapath-loader
level=warning msg="+ ip link set cilium_host up" subsys=datapath-loader
level=warning msg="+ '[' '<nil>' '!=' '<nil>' ']'" subsys=datapath-loader
level=warning msg="+ '[' 10.174.66.75 '!=' '<nil>' ']'" subsys=datapath-loader
level=warning msg="+ echo 1" subsys=datapath-loader
level=warning msg="+ echo 0" subsys=datapath-loader
level=warning msg="+ echo 1" subsys=datapath-loader
level=warning msg="+ echo 0" subsys=datapath-loader
level=warning msg="+ setup_dev cilium_net" subsys=datapath-loader
level=warning msg="+ local -r NAME=cilium_net" subsys=datapath-loader
level=warning msg="+ ip link set cilium_net up" subsys=datapath-loader
level=warning msg="+ '[' '<nil>' '!=' '<nil>' ']'" subsys=datapath-loader
level=warning msg="+ '[' 10.174.66.75 '!=' '<nil>' ']'" subsys=datapath-loader
level=warning msg="+ echo 1" subsys=datapath-loader
level=warning msg="+ echo 0" subsys=datapath-loader
level=warning msg="+ echo 1" subsys=datapath-loader
level=warning msg="+ echo 0" subsys=datapath-loader
level=warning msg="+ ip link set cilium_host arp off" subsys=datapath-loader
level=warning msg="+ ip link set cilium_net arp off" subsys=datapath-loader
level=warning msg="+ ip link set cilium_host mtu 1500" subsys=datapath-loader
level=warning msg="+ ip link set cilium_net mtu 1500" subsys=datapath-loader
level=warning msg="+ case \"${MODE}\" in" subsys=datapath-loader
level=warning msg="+ sed -i '/^#.*CILIUM_NET_MAC.*$/d' /var/run/cilium/state/globals/node_config.h" subsys=datapath-loader
level=warning msg="++ ip link show cilium_net" subsys=datapath-loader
level=warning msg="++ grep ether" subsys=datapath-loader
level=warning msg="++ awk '{print $2}'" subsys=datapath-loader
level=warning msg="+ CILIUM_NET_MAC=ca:40:9c:dc:a2:49" subsys=datapath-loader
level=warning msg="++ mac2array ca:40:9c:dc:a2:49" subsys=datapath-loader
level=warning msg="++ echo '{0xca,0x40,0x9c,0xdc,0xa2,0x49}'" subsys=datapath-loader
level=warning msg="+ CILIUM_NET_MAC='{0xca,0x40,0x9c,0xdc,0xa2,0x49}'" subsys=datapath-loader
level=warning msg="+ sed -i '/^#.*CILIUM_NET_MAC.*$/d' /var/run/cilium/state/globals/node_config.h" subsys=datapath-loader
level=warning msg="+ echo '#ifndef CILIUM_NET_MAC'" subsys=datapath-loader
level=warning msg="+ echo '#define CILIUM_NET_MAC { .addr = {0xca,0x40,0x9c,0xdc,0xa2,0x49}}'" subsys=datapath-loader
level=warning msg="+ echo '#endif /* CILIUM_NET_MAC */'" subsys=datapath-loader
level=warning msg="+ sed -i '/^#.*HOST_IFINDEX.*$/d' /var/run/cilium/state/globals/node_config.h" subsys=datapath-loader
level=warning msg="++ cat /sys/class/net/cilium_net/ifindex" subsys=datapath-loader
level=warning msg="+ HOST_IDX=8" subsys=datapath-loader
level=warning msg="+ echo '#define HOST_IFINDEX 8'" subsys=datapath-loader
level=warning msg="+ sed -i '/^#.*HOST_IFINDEX_MAC.*$/d' /var/run/cilium/state/globals/node_config.h" subsys=datapath-loader
level=warning msg="++ ip link show cilium_host" subsys=datapath-loader
level=warning msg="++ grep ether" subsys=datapath-loader
level=warning msg="++ awk '{print $2}'" subsys=datapath-loader
level=warning msg="+ HOST_MAC=ca:4f:b3:98:ea:90" subsys=datapath-loader
level=warning msg="++ mac2array ca:4f:b3:98:ea:90" subsys=datapath-loader
level=warning msg="++ echo '{0xca,0x4f,0xb3,0x98,0xea,0x90}'" subsys=datapath-loader
level=warning msg="+ HOST_MAC='{0xca,0x4f,0xb3,0x98,0xea,0x90}'" subsys=datapath-loader
level=warning msg="+ echo '#define HOST_IFINDEX_MAC { .addr = {0xca,0x4f,0xb3,0x98,0xea,0x90}}'" subsys=datapath-loader
level=warning msg="+ sed -i '/^#.*CILIUM_IFINDEX.*$/d' /var/run/cilium/state/globals/node_config.h" subsys=datapath-loader
level=warning msg="++ cat /sys/class/net/cilium_host/ifindex" subsys=datapath-loader
level=warning msg="+ CILIUM_IDX=9" subsys=datapath-loader
level=warning msg="+ echo '#define CILIUM_IFINDEX 9'" subsys=datapath-loader
level=warning msg="++ cat /proc/sys/net/ipv4/ip_local_port_range" subsys=datapath-loader
level=warning msg="++ awk '{print $1}'" subsys=datapath-loader
level=warning msg="+ CILIUM_EPHEMERAL_MIN=32768" subsys=datapath-loader
level=warning msg="+ echo '#define EPHEMERAL_MIN 32768'" subsys=datapath-loader
level=warning msg="+ '[' true = true ']'" subsys=datapath-loader
level=warning msg="+ MAC_BY_IFINDEX_MACRO='#define NATIVE_DEV_MAC_BY_IFINDEX(IFINDEX) ({ \\" subsys=datapath-loader
level=warning msg="\tunion macaddr __mac = {.addr = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0}}; \\" subsys=datapath-loader
level=warning msg="\tswitch (IFINDEX) { \\\\\\n'" subsys=datapath-loader
level=warning msg="+ MAC_BY_IFINDEX_MACRO_END='\t} \\" subsys=datapath-loader
level=warning msg="\t__mac; })'" subsys=datapath-loader
level=warning msg="+ for NATIVE_DEV in ${NATIVE_DEVS//;/ }" subsys=datapath-loader
level=warning msg="++ cat /sys/class/net/lo/ifindex" subsys=datapath-loader
level=warning msg="+ IDX=1" subsys=datapath-loader
level=warning msg="++ ip link show lo" subsys=datapath-loader
level=warning msg="++ grep ether" subsys=datapath-loader
level=warning msg="++ awk '{print $2}'" subsys=datapath-loader
level=warning msg="+ MAC=" subsys=datapath-loader
level=error msg="Error while initializing daemon" error="exit status 1" subsys=daemon
level=fatal msg="Error while creating daemon" error="exit status 1" subsys=daemon
``` 

If i specify the flag --global.devices=eth0, and i a create a NodePort service, i'm not able to establish a connection to the IP specified on the 'lo' iface from outside of the cluster.

```
35   10.129.133.3:31619     NodePort       1 => 10.174.65.146:80
                                           2 => 10.174.66.115:80
36   0.0.0.0:31619          NodePort       1 => 10.174.65.146:80
                                           2 => 10.174.66.115:80
```

Establishing a connection to 10.189.20.54:31619 fail.

### PR DESCRIPTION
**Pull request by brb**
See commit msgs.

I haven't added IPv6 tests, as I'd need to extend https://github.com/cilium/kube-wireguarder to support it. At this point, it would be a waste of time, as we are planning to add the native Wireguard support in this release cycle. So we can add the tests once https://github.com/cilium/cilium/issues/15075 has been resolved.

To fix L2-less with the fast redirect I've opened https://github.com/cilium/cilium/issues/15075.

Fix #12317

```release-note
Add NodePort BPF support to L2-less devices (wireguard, tun, etc)
```

### CODE REVIEW

**Comment by brb** [comment]
test-net-next

**Comment by brb** [comment]
test-net-next

**Comment by brb** [comment]
test-net-next

**Comment by brb** [comment]
test-net-next

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-4.9

**Comment by brb** [comment]
test-net-next

**Comment by brb** [comment]
test-net-next

**Comment by brb** [comment]
test-net-next

**Comment by brb** [comment]
test-net-next

**Comment by brb** [comment]
test-net-next

**Comment by brb** [comment]
test-runtime

**Comment by brb** [comment]
test-4.9

**Comment by brb** [comment]
test-4.19

**Comment by brb** [comment]
test-gke

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-4.19

**Comment by brb** [comment]
Oh snap, there is a verifier error on 4.9 kernel:
```
0: (bf) r6 = r1" subsys=datapath-loader
1: (61) r9 = *(u32 *)(r6 +48)" subsys=datapath-loader
2: (b7) r1 = 0" subsys=datapath-loader
3: (63) *(u32 *)(r6 +48) = r1" subsys=datapath-loader
4: (18) r7 = 0xffffff7a" subsys=datapath-loader
6: (18) r1 = 0xe" subsys=datapath-loader
8: (18) r3 = 0xe" subsys=datapath-loader
10: (07) r3 += 40" subsys=datapath-loader
11: (67) r3 <<= 32" subsys=datapath-loader
12: (77) r3 >>= 32" subsys=datapath-loader
13: (61) r2 = *(u32 *)(r6 +76)" subsys=datapath-loader
14: (bf) r4 = r2" subsys=datapath-loader
15: (0f) r4 += r3" subsys=datapath-loader
cannot add integer value with 32 upper zero bits to ptr_to_packet" subsys=datapath-loader
```
The relevant piece of code:
```
; 	if (!validate_ethertype(ctx, &proto)) {
      82:	2d 23 97 08 00 00 00 00	if r3 > r2 goto +2199 <LBB10_314>

0000000000000298 LBB10_11:
      83:	b7 05 00 00 00 00 00 00	r5 = 0
; 	ctx->cb[off] = data;
      84:	63 56 38 00 00 00 00 00	*(u32 *)(r6 + 56) = r5
; 	switch (proto) {
      85:	57 01 00 00 ff ff 00 00	r1 &= 65535
      86:	15 01 cb 00 08 00 00 00	if r1 == 8 goto +203 <LBB10_22>
      87:	15 01 bf 08 08 06 00 00	if r1 == 1544 goto +2239 <LBB10_318>
      88:	18 07 00 00 75 ff ff ff 00 00 00 00 00 00 00 00	r7 = 4294967157 ll
      90:	55 01 8f 08 86 dd 00 00	if r1 != 56710 goto +2191 <LBB10_314>
      91:	b7 01 00 00 00 00 00 00	r1 = 0
; 	struct ipv6_ct_tuple tuple = {};
      92:	6b 1a 94 ff 00 00 00 00	*(u16 *)(r10 - 108) = r1
      93:	63 1a 90 ff 00 00 00 00	*(u32 *)(r10 - 112) = r1
      94:	7b 1a 88 ff 00 00 00 00	*(u64 *)(r10 - 120) = r1
      95:	7b 1a 80 ff 00 00 00 00	*(u64 *)(r10 - 128) = r1
      96:	7b 1a 78 ff 00 00 00 00	*(u64 *)(r10 - 136) = r1
      97:	7b 1a 70 ff 00 00 00 00	*(u64 *)(r10 - 144) = r1
; 	if (data + tot_len > data_end)
      98:	18 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00	r1 = 0 ll
     100:	18 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00	r2 = 0 ll
     102:	07 02 00 00 28 00 00 00	r2 += 40
     103:	67 02 00 00 20 00 00 00	r2 <<= 32
     104:	77 02 00 00 20 00 00 00	r2 >>= 32
     105:	bf 83 00 00 00 00 00 00	r3 = r8
     106:	0f 23 00 00 00 00 00 00	r3 += r2
     107:	18 07 00 00 7a ff ff ff 00 00 00 00 00 00 00 00	r7 = 4294967162 ll
; 	return (void *)(unsigned long)ctx->data_end;
     109:	61 62 50 00 00 00 00 00	r2 = *(u32 *)(r6 + 80)
```

**Comment by borkmann** [comment]
`cannot add integer value with 32 upper zero bits to ptr_to_packet" subsys=datapath-loader`

The verifier rejects it since it would go beyond max pkt size of 0xffff, it's limited due to concerns of overflow.

```
      98:	18 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00	r1 = 0 ll
     100:	18 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00	r2 = 0 ll
     102:	07 02 00 00 28 00 00 00	r2 += 40
     103:	67 02 00 00 20 00 00 00	r2 <<= 32
     104:	77 02 00 00 20 00 00 00	r2 >>= 32
```

And this one looks like the code generation is doing odd things given r2 would be a const imm. But presumably the shifts / cast to u32 would trash the known bounds.

**Comment by brb** [comment]
test-me-please

**Review by aanm — CHANGES_REQUESTED** [review]
Changes look good overall.

Needs documentation and disclaimers that it will likely won't work for large clusters (>500 or >1000 nodes) given that kube-wireguarder is watching for all events in CiliumNodes and K8s Nodes.

**Comment by brb** [comment]
> Needs documentation and disclaimers that it will likely won't work for large clusters (>500 or >1000 nodes) given that kube-wireguarder is watching for all events in CiliumNodes and K8s Nodes.

This PR is only for enabling bpf_host on Wireguard iface. The `kube-wireguarder` hack is only used for testing until we have it properly integrated into cilium-{agent,operator} ([WIP](https://github.com/cilium/cilium/tree/pr/wg))

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-gke

**Review by aanm — APPROVED** [review]

File: bpf/lib/common.h [hunk 1]
```diff
@@ -118,6 +119,17 @@ static __always_inline bool validate_ethertype(struct __ctx_buff *ctx,
 	void *data_end = ctx_data_end(ctx);
 	struct ethhdr *eth = data;
 
+#if __ctx_is == __ctx_skb
+	/* XDP does not support packets without L2 hdr, so skip the check.*/
```
Comment (borkmann) [inline bpf/lib/common.h]: Given it's not possible to attach to XDP for those devices, why do we need the extra `__ctx_is == __ctx_skb` check?

File: bpf/lib/common.h [hunk 2]
```diff
@@ -146,10 +160,18 @@ __revalidate_data_pull(struct __ctx_buff *ctx, void **data_, void **data_end_,
...
-	*l3 = data + ETH_HLEN;
+	*l3 = data + eth_hlen;
 	return true;
 }
 
+static __always_inline __maybe_unused bool
+__revalidate_data_pull(struct __ctx_buff *ctx, void **data, void **data_end,
+		       void **l3, const __u32 l3_len, const bool pull)
+{
+	return __revalidate_data_pull_with_eth_hlen(ctx, data, data_end, l3,
```
Comment (borkmann) [inline bpf/lib/common.h]: small nit: maybe just `____revalidate_data_pull`

File: bpf/lib/nodeport.h [hunk 3]
```diff
@@ -161,6 +161,37 @@ static __always_inline bool dsr_is_too_big(struct __ctx_buff *ctx __maybe_unused
 	return false;
 }
 
+static __always_inline int
+maybe_add_l2_hdr(struct __ctx_buff *ctx __maybe_unused,
+		 __u32 ifindex __maybe_unused,
+		 bool *l2_hdr_required __maybe_unused)
+{
+/* XDP does not support L2-less devices, so skip the checks. */
```
Comment (borkmann) [inline bpf/lib/nodeport.h]: For XDP, shouldn't these just be compiled out w/o the `__ctx_is == __ctx_skb` test? (`IS_L3_DEV` always false, `ETH_HLEN` always 14)

File: daemon/cmd/kube_proxy_replacement.go [hunk 4]
```diff
@@ -448,6 +415,43 @@ func finishKubeProxyReplacementInit(isKubeProxyReplacementStrict bool) {
 
 	// After this point, BPF NodePort should not be disabled
```
Comment (borkmann) [inline daemon/cmd/kube_proxy_replacement.go:418]: I think we need this as separate fix for 1.9 stable tree as well? So this should probably be broken out and then cherry-picked as single commit to 1.9.

File: daemon/cmd/kube_proxy_replacement.go [hunk 5]
```diff
@@ -448,6 +415,43 @@ func finishKubeProxyReplacementInit(isKubeProxyReplacementStrict bool) {
...
+		case option.Config.EnableEndpointRoutes:
+			msg = fmt.Sprintf("BPF host routing is incompatible with %s.", option.EnableEndpointRoutes)
+		case option.Config.EnableIPSec:
+			msg = fmt.Sprintf("BPF host routing is incompatible with %s.", option.EnableIPSecName)
+		// Non-BPF masquerade requires netfilter and hence CT.
+		case (option.Config.EnableIPv4Masquerade || option.Config.EnableIPv6Masquerade) &&
+			!option.Config.EnableBPFMasquerade:
+			msg = fmt.Sprintf("BPF host routing requires %s.", option.EnableBPFMasquerade)
+		case !hasHardwareAddress():
+			msg = fmt.Sprintf("BPF host routing is incompatible with devices without L2 addr.")
```
Comment (borkmann) [inline daemon/cmd/kube_proxy_replacement.go]: Could you elaborate on why incompatible? I think it should be working just that we need to push a L2 header before the redirect_peer? Although I'm not even sure if the stack cares about that even. Maybe needs the same change as in https://github.com/cilium/cilium/pull/15148 to get it working?

File: bpf/lib/common.h (hunk 1 above)
Comment (brb) [reply bpf/lib/common.h]: I wanted to compile out the case for XDP to save a few CPU cycles. Let me check whether compiler does it for us.

File: bpf/lib/nodeport.h (hunk 3 above)
Comment (brb) [reply bpf/lib/nodeport.h]: Let me check whether compiler removes them.

File: daemon/cmd/kube_proxy_replacement.go (hunk 4 above)
Comment (brb) [reply daemon/cmd/kube_proxy_replacement.go:418]: Yeah, I have it in my TODO.

File: daemon/cmd/kube_proxy_replacement.go (hunk 5 above)
Comment (brb) [reply daemon/cmd/kube_proxy_replacement.go]: > I think it should be working just that we need to push a L2 header before the redirect_peer?

As far as I've checked the code path, it should be enough. I didn't want to add to this PR to avoid making it too complex.

File: bpf/lib/common.h (hunk 1 above)
Comment (brb) [reply bpf/lib/common.h]: OK, just checked - this one gets compiled away :+1:

File: bpf/lib/nodeport.h (hunk 3 above)
Comment (brb) [reply bpf/lib/nodeport.h]: OK, this one gets compiled out too. I'm going to drop the redundant `__ctx_is` checks.

Comment (borkmann) [reply bpf/lib/nodeport.h]: Sounds good, the less such checks where not needed the better.

File: daemon/cmd/kube_proxy_replacement.go (hunk 5 above)
Comment (borkmann) [reply daemon/cmd/kube_proxy_replacement.go]: Ok, if it's follow-up, lets just say `currently not supported` rather than `incompatible`. Hopefully for 1.10 scope, we'll resolve it in time. I can also help if needed.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-gke

**Comment by brb** [comment]
test-gke

**Comment by brb** [comment]
test-4.19

**Review by nbusseneau — APPROVED** [review]

**Comment by brb** [comment]
Previously all tests have passed (except for the checkpatch's false positive). I've rebased against the latest master to resolve the trivial merge conflict in `daemon/cmd/kube_proxy_replacement.go`. PTAL.

File: bpf/include/bpf/helpers_skb.h [hunk 6]
```diff
@@ -60,4 +60,7 @@ static int BPF_FUNC(sk_release, struct bpf_sock *sk);
 static int BPF_FUNC(sk_assign, struct __sk_buff *skb, struct bpf_sock *sk,
 		    __u64 flags);
 
+static int BPF_FUNC(skb_change_head, struct __sk_buff *skb, __u32 head_room,
+		    __u64 flags);
```
Comment (borkmann) [inline bpf/include/bpf/helpers_skb.h]: nit: should go below `/* Packet manipulation */`

File: bpf/include/linux/if_ether.h [hunk 7]
```diff
@@ -29,7 +29,7 @@
  */
 
 #define ETH_ALEN	6		/* Octets in one ethernet addr	 */
-#define ETH_HLEN	14		/* Total octets in header.	 */
+#define __ETH_HLEN	14		/* Total octets in header.	 */
```
Comment (borkmann) [inline bpf/include/linux/if_ether.h:37]: Hm, I missed this earlier, but we should not mangle headers that we sync from upstream kernel. (bpf/include/linux/*)

Comment (brb) [reply bpf/include/linux/if_ether.h:37]: Ouch, then we would need to rename `ETH_HLEN` in our datapath code :-/

File: bpf/lib/nodeport.h [hunk 8]
```diff
@@ -653,6 +692,16 @@ int tail_nodeport_nat_ipv6(struct __ctx_buff *ctx)
 		goto drop_err;
 	}
 
+	ret = maybe_add_l2_hdr(ctx, DIRECT_ROUTING_DEV_IFINDEX,
+			       &l2_hdr_required);
+	if (ret != 0)
+		goto drop_err;
+	if (!l2_hdr_required)
+		goto out_send;
```
Comment (borkmann) [inline bpf/lib/nodeport.h:700]: nit: the __maybe_unused from `out_send: __maybe_unused` can then probably be removed.

**Review by borkmann — COMMENTED** [review]
modulo the minor bits, lgtm!

File: bpf/include/linux/if_ether.h (hunk 7 above)
Comment (borkmann) [reply bpf/include/linux/if_ether.h:37]: Hm :/ yeah I guess it would need a `L2_HLEN`...

File: pkg/datapath/linux/config/config.go [hunk 9]
```diff
@@ -510,6 +517,30 @@ func (h *HeaderfileWriter) WriteNodeConfig(w io.Writer, cfg *datapath.LocalNodeC
 	return fw.Flush()
 }
 
+func isL3DevMacro() (string, error) {
```
Comment (christarazi) [inline pkg/datapath/linux/config/config.go:522]: Might be worth briefly documenting this and why it exists

File: daemon/cmd/kube_proxy_replacement.go [hunk 10]
```diff
@@ -449,6 +415,45 @@ func finishKubeProxyReplacementInit(isKubeProxyReplacementStrict bool) {
 
 	// After this point, BPF NodePort should not be disabled
 
+	if !option.Config.EnableHostLegacyRouting {
```
Comment (christarazi) [inline daemon/cmd/kube_proxy_replacement.go:419]: Maybe it makes sense to make a separate commit to move this entire block, then a new commit adding the change you want, so that we don't lose the history / break git bisect?

File: daemon/cmd/kube_proxy_replacement.go [hunk 11]
```diff
@@ -434,7 +435,7 @@ func finishKubeProxyReplacementInit(isKubeProxyReplacementStrict bool) {
 		case (option.Config.EnableIPv4Masquerade || option.Config.EnableIPv6Masquerade) &&
 			!option.Config.EnableBPFMasquerade:
 			msg = fmt.Sprintf("BPF host routing requires %s.", option.EnableBPFMasquerade)
-		case !hasHardwareAddress():
+		case !mac.HaveMACAddr(option.Config.Devices):
```
Comment (christarazi) [inline daemon/cmd/kube_proxy_replacement.go:438]: If you break apart the commits like mentioned previously, then this commit can be squashed into the second commit, and this delta between commits won't exist.

**Review by christarazi — COMMENTED** [review]
:tada: Awesome! Just a few comments below

**Comment by brb** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

File: bpf/lib/nodeport.h [hunk 12]
```diff
@@ -161,6 +161,32 @@ static __always_inline bool dsr_is_too_big(struct __ctx_buff *ctx __maybe_unused
...
+		 * so we need to create L2 hdr first.
+		 */
+		__u16 proto = ctx_get_protocol(ctx);
+
+		if (ctx_change_head(ctx, __ETH_HLEN, 0))
+			return DROP_INVALID;
+
+		if (eth_store_proto(ctx, proto, 0) < 0)
+			return DROP_WRITE_ERROR;
+	}
```
Comment (pchaigno) [inline bpf/lib/nodeport.h:185]: AFAICS, the `ETH_LEN==0` case will maximize complexity here, so we might want to set that macro to 0 in `bpf/Makefile`.

File: daemon/cmd/kube_proxy_replacement.go [hunk 13]
```diff
@@ -449,6 +415,43 @@ func finishKubeProxyReplacementInit(isKubeProxyReplacementStrict bool) {
 
 	// After this point, BPF NodePort should not be disabled
 
+	if !option.Config.EnableHostLegacyRouting {
+		msg := ""
+		switch {
+		case !option.Config.EnableNodePort:
+			msg = fmt.Sprintf("BPF host routing requires %s.", option.EnableNodePort)
```
Comment (pchaigno) [inline daemon/cmd/kube_proxy_replacement.go:423]: AFAICS, we'll never hit this case because, as said above:
> After this point, BPF NodePort should not be disabled

So if NodePort is disabled for some reason other than explicitly disabled, `ENABLE_REDIRECT_FAST` will remain enabled in the datapath.

**Review by pchaigno — COMMENTED** [review]
Couple comments which we'll require follow ups if I didn't miss something.

File: bpf/lib/nodeport.h (hunk 12 above)
Comment (brb) [reply bpf/lib/nodeport.h:185]: https://github.com/cilium/cilium/pull/15343

File: daemon/cmd/kube_proxy_replacement.go (hunk 13 above)
Comment (brb) [reply daemon/cmd/kube_proxy_replacement.go:423]: This has resolved the issue https://github.com/cilium/cilium/pull/15240/files.
