### PR TITLE
endpoint: Fix spanstat corruption on RegenerateAllEndpoints()

### LINKED ISSUE #6021: Duration is negative on End
```
2018-10-23T01:34:29.195914374Z level=warning msg="Duration is negative on End" duration="-34.487µs" subsys=spanstat
2018-10-23T01:34:29.195924615Z goroutine 4025924 [running]:
2018-10-23T01:34:29.195927600Z runtime/debug.Stack(0x0, 0x0, 0x0)
2018-10-23T01:34:29.195930539Z  /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
2018-10-23T01:34:29.195933411Z runtime/debug.PrintStack()
2018-10-23T01:34:29.195936116Z  /usr/local/go/src/runtime/debug/stack.go:16 +0x22
2018-10-23T01:34:29.195938986Z github.com/cilium/cilium/pkg/spanstat.(*SpanStat).End(0xc4248aba18, 0x1)
2018-10-23T01:34:29.195941850Z  /go/src/github.com/cilium/cilium/pkg/spanstat/spanstat.go:57 +0x1c5
2018-10-23T01:34:29.195951018Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc4203d38c0, 0x2bf9020, 0xc4224a0140, 0xc4248ab880, 0x0, 0x0)
2018-10-23T01:34:29.195954255Z  /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:737 +0x6ef
2018-10-23T01:34:29.195957173Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate.func1(0xc4248ab880, 0x2bf9020, 0xc4224a0140, 0xc425564c40, 0xc4203d38c0)
2018-10-23T01:34:29.195960128Z  /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:842 +0x1fc
2018-10-23T01:34:29.195962939Z created by github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate
2018-10-23T01:34:29.195965789Z  /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:820 +0x123

```

Cilium version `1.3.0-rc4`

### PR DESCRIPTION
**Pull request by eloycoto**
On endpointmanager we call to endpoint.Regenerate with the same
regenerationContext, that means that all the spanStats are updated to a
new ones instead of the correct values.

With this change, all endpoint.RegenerationContext are different per
each endpoint and the metrics will be correct.

Fix #6021
Related to commit: 1d46a782704644ec88e001d402b87f8b91156b5c

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6025)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

File: pkg/endpointmanager/manager.go [hunk 1]
```diff
@@ -285,7 +285,9 @@ func RegenerateAllEndpoints(owner endpoint.Owner, regenContext *endpoint.Regener
 				ep.Unlock()
 				if regen {
 					// Regenerate logs status according to the build success/failure
-					<-ep.Regenerate(owner, regenContext)
+					// Create a new regenContext to not overwrite the spanStats
+					// values on the endpoint regeneration.
+					<-ep.Regenerate(owner, endpoint.NewRegenerationContext(regenContext.Reason))
```
Comment (tgraf) [inline pkg/endpointmanager/manager.go:292]: Please add a comment to the description of `RegenerateAllEndpoints()` that `regenContext` is cloned.

**Review by tgraf — CHANGES_REQUESTED** [review]

File: pkg/endpointmanager/manager.go (hunk 1 above)
Comment (eloycoto) [reply pkg/endpointmanager/manager.go:292]: Done!

**Comment by eloycoto** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
Build failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7488/testReport/junit/k8s-1/8/K8sHealthTest_checks_cilium_health_status_between_nodes/

etcd-operator pods timed out being ready. Related-to https://github.com/cilium/cilium/issues/5932 , so I am triggering another build.

**Comment by ianvernon** [comment]
test-me-please

**Comment by tgraf** [comment]
Hit #5667

**Comment by tgraf** [comment]
test-me-please
