### PR TITLE
Fix copy of annotations into CiliumNode

### LINKED ISSUE #25301: bug: node -> ciliumnode annotation copy not working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. I've tested https://github.com/cilium/cilium/pull/24914 with the container based on daa85a0f4af2f8279bc7bc80d1afe7ab9adb4f9a (both cilium and operator)
2. neither the bgp annotation, nor the Wireguard Pub Key Annotation gets copied

### Cilium Version

Manually installed container daa85a0f4af2f8279bc7bc80d1afe7ab9adb4f9a

### Kernel Version

5.10.0-22-amd64 #1 SMP Debian 5.10.178-3 (2023-04-22) x86_64 GNU/Linux


### Kubernetes Version

Client Version: v1.26.3+k3s1
Kustomize Version: v4.5.7
Server Version: v1.26.3+k3s1

### Sysdump

_No response_

### Relevant log output

```shell
Example annotations for node:

│ Annotations:        cilium.io/bgp-virtual-router.64512: router-id=172.0.0.3                                                                                                                                                                
│                     network.cilium.io/wg-pub-key: test       
```
Ciliumnode:
```
│ Annotations:  <none>                                                                                                                                                                                                                      
```

I've added test code to the `func (n *Node) ToCiliumNode() *ciliumv2.CiliumNode {`:
```
[...]
	for _, address := range n.IPAddresses {
		ipAddrs = append(ipAddrs, ciliumv2.NodeAddress{
			Type: address.Type,
			IP:   address.IP.String(),
		})
	}
	log.Infof("Annotations before: %v", n.Annotations)
[...]
```

The log output indicates, that the original annotations never came with the original node object `n`:
```
level=info msg="Annotations before: map[]" subsys=node 
```
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by meyskens**
This fixes the adding of relevant annotations to the created CiliumNode object. This was caused by the local node not containing this info.

Work for this regarding BGP an notations got added in https://github.com/cilium/cilium/pull/24914 but never properly synced as the localNode did store the info. this fix takes those from the received k8s node object to generate them.

Fixes:  #25301

```release-note
Fix syncing of relevant node annotations into CiliumNode
```

### CODE REVIEW

File: pkg/nodediscovery/nodediscovery.go [hunk 1]
```diff
@@ -454,7 +454,11 @@ func (n *NodeDiscovery) mutateNodeResource(nodeResource *ciliumv2.CiliumNode) er
 
 	nodeResource.ObjectMeta.Labels = k8sNodeParsed.Labels
 
-	localCN := n.localNode.ToCiliumNode()
+	// This is for syncing relevant node annotations from the k8s node to the
+	// CiliumNode object, ToCiliumNode will only copy used annotations.
+	ln := n.localNode.DeepCopy()
+	ln.Annotations = k8sNodeParsed.Annotations
+	localCN := ln.ToCiliumNode()
```
Comment (pippolo84) [inline pkg/nodediscovery/nodediscovery.go]: AFAIU we are creating a temporary `localNode` and setting its annotations to `k8sNodeParsed.Annotations` so that `ToCiliumNode` will "extract" the used ones (WireguardPubKey and BGP virtual router) in`localCN`.
What about adding an exported method to `types.Node` to extract the used annotations and use it both here (on `k8sNodeParsed`) and inside `*Node.ToCiliumNode`?

Comment (meyskens) [reply pkg/nodediscovery/nodediscovery.go]: Good idea, did that!

File: pkg/nodediscovery/nodediscovery.go [hunk 2]
```diff
@@ -454,8 +454,11 @@ func (n *NodeDiscovery) mutateNodeResource(nodeResource *ciliumv2.CiliumNode) er
 
 	nodeResource.ObjectMeta.Labels = k8sNodeParsed.Labels
 
-	localCN := n.localNode.ToCiliumNode()
-	nodeResource.ObjectMeta.Annotations = localCN.Annotations
+	// This is for syncing relevant node annotations from the k8s node to the
+	// CiliumNode object
+	ln := n.localNode.DeepCopy()
+	ln.Annotations = k8sNodeParsed.Annotations
+	nodeResource.ObjectMeta.Annotations = ln.GetCiliumAnnotations()
```
Comment (pippolo84) [inline pkg/nodediscovery/nodediscovery.go]: I think we can get rid of the deep copy with:

`nodeResource.ObjectMeta.Annotations = k8sNodeParsed.GetCiliumAnnotations()`

On a side note, unrelated to this PR, I see that the `types` package is imported twice:

```
	"github.com/cilium/cilium/pkg/node/types"
	nodeTypes "github.com/cilium/cilium/pkg/node/types"
```

So we can get rid of one of those (but let's leave that for a follow up PR, no need to do this here).

**Review by pippolo84 — APPROVED** [review]
LGTM, thanks! :rocket:

**Comment by ldelossa** [comment]
This looks good to me, I've also tested in our BGP labs :+1:

**Review by ldelossa — APPROVED** [review]

**Comment by meyskens** [comment]
CI failure seems to be related to https://github.com/cilium/cilium/issues/15455
