### PR TITLE
nodediscovery: retry CiliumNode updates on transient errors

### LINKED ISSUE #44388: cilium-agent crashes with Fatal on transient API server errors during CiliumNode update
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.18.7 and lower than v1.19.0

### What happened?

The cilium-agent calls `logging.Fatal()` (which triggers `os.Exit(-1)`) when it encounters a transient network error while updating the CiliumNode custom resource. This causes the agent to crash and restart, even though the datapath is fully functional and the API server connectivity issue is temporary.The error we observed:
```
evel=fatal msg="Unable to update CiliumNode resource" module=agent.controlplane.nodediscovery
error="Put \"https://100.124.0.150:6443/apis/cilium.io/v2/ciliumnodes/g10526c\":
http2: client connection lost"
```

**Expected behavior**: Cilium should retry on transient network errors with exponential
backoff, similar to how kubelet, kube-proxy, and other Kubernetes components handle
temporary API server unavailability. The API server may legitimately close HTTP/2 connections under load.

**Actual behavior**: Cilium crashes immediately. 

### Impact

- **BGP routes are withdrawn**: In environments using BGP control plane for inter-node
  routing, the crash kills BGP sessions, causing pods on the affected node to become
  unreachable from the rest of the cluster.
- **No graceful shutdown**: `os.Exit(-1).

### How can we reproduce the issue?

on a host 
iptables -A OUTPUT -p tcp --dport 443 -d <apiserver-ip> -j REJECT --reject-with tcp-reset
iptables -A OUTPUT -p tcp --dport 6443 -d <apiserver-ip> -j REJECT --reject-with tcp-reset
sleep 60
iptables -D OUTPUT -p tcp --dport 443 -d <apiserver-ip> -j REJECT --reject-with tcp-reset
iptables -D OUTPUT -p tcp --dport 6443 -d <apiserver-ip> -j REJECT --reject-with tcp-reset

### Cilium Version

1.18.x
1.17.x
1.16.x

### Kernel Version

6.8.12

### Kubernetes Version

v1.35, v1.34, v1.33, v1.32

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by nebojsaj1726**
Fixes: #44388

`updateCiliumNodeResource` retried only on conflict errors, calling `logging.Fatal` immediately on any other error. This caused the agent to crash on transient network failures such as a connection reset or HTTP/2 ping timeout, which would resolve themselves on a simple retry.   
                                                                                                                                                                 
Fix by retrying on all errors uniformly. The existing exhaustion-Fatal after `maxRetryCount` attempts still fires if the problem persists.  
                                                                                                                                              
A unit test is added that injects a permanent "connection reset by peer" error via a fake clientset reactor and asserts that all  `maxRetryCount` retries are attempted before giving up.

```release-note
Fix cilium-agent crash when a transient network error occurs during CiliumNode update. The agent now retries instead of calling Fatal.

### CODE REVIEW

**Review by rastislavs — APPROVED** [review]
Thanks for the fix!

File: pkg/nodediscovery/nodediscovery.go [hunk 1]
```diff
@@ -275,25 +274,19 @@ func (n *NodeDiscovery) updateCiliumNodeResource(ctx context.Context, ln *node.L
 		performGet = true
 		if performUpdate {
 			if _, err := n.clientset.CiliumV2().CiliumNodes().Update(ctx, nodeResource, metav1.UpdateOptions{}); err != nil {
-				if k8serrors.IsConflict(err) {
-					n.logger.Info("Unable to update CiliumNode resource, will retry", logfields.Error, err)
-					// Backoff before retrying
-					time.Sleep(backoffDuration)
-					continue
-				}
-				logging.Fatal(n.logger, "Unable to update CiliumNode resource", logfields.Error, err)
```
Comment (joestringer) [inline pkg/nodediscovery/nodediscovery.go:284]: What do you think is the right way to signal this error condition? If Cilium is persistently unable to update the CiliumNode resource, presumably that is a reasonably serious error we need to bring to the attention of the user.

Comment (joestringer) [reply pkg/nodediscovery/nodediscovery.go:284]: cc @cilium/sig-k8s

Comment (nebojsaj1726) [reply pkg/nodediscovery/nodediscovery.go:284]: Thanks for the question! The logging.Fatal is still present — it's been moved to after the retry loop exhausts all attempts (line 296). So a truly persistent failure (failing all 10 retries over ~5 seconds) still results in a fatal crash. The change only removes the immediate fatal for non-conflict errors on the first attempt, treating all errors as potentially transient.

That said, I'm open to a better signal if you think crash-restart isn't ideal here.

Comment (joestringer) [reply pkg/nodediscovery/nodediscovery.go:284]: Please don't use AI to communicate with others on PRs.

The existing failure condition will fatal out but the error will be hidden. Any errors that occur during this process should be emitted to the logs so the user has a chance at understanding what went wrong.

Comment (nebojsaj1726) [reply pkg/nodediscovery/nodediscovery.go:284]: Got it now, fixed the error logging.

**Comment by derailed** [comment]
@nebojsaj1726 Looks like there are some tests issues. Can you take a peek? Thank you!

**Comment by nebojsaj1726** [comment]
@derailed  I've fixed the lint error, PTAL.

**Comment by nebojsaj1726** [comment]
@joestringer @derailed I looked at the failing CI checks, don't seem to be related to my changes. Is there anything else I can do to move this forward?

**Comment by joestringer** [comment]
/test

EDIT: Evidently Ariane didn't properly respond to this one

**Comment by joestringer** [comment]
Indeed there was a temporary issue with CI causing that failure a few weeks ago. I triggered a rebase + re-run of the tests to move this forward.

**Comment by ChandonPierre** [comment]
@mhofstetter any chance we can get this backported into 1.18 as well?

**Comment by mhofstetter** [comment]
> @mhofstetter any chance we can get this backported into 1.18 as well?

According to [Cilium's backporting criterias](https://docs.cilium.io/en/latest/contributing/release/backports/#backport-criteria-for-x-y-1-z-and-x-y-2-z) we can give it a try. If this bug really lets the Cilium Agent crash.

> Major bugfixes relevant to the correct operation of Cilium

cc @joestringer
