### PR TITLE
Fix empty message when host legacy routing is true

### LINKED ISSUE #21237: eBPF based maquerading not supported on kernel 4.19?
attempted to enable eBPF based masquerading on kernel 4.19, it always fall back to iptables based masquerading

```
level=warning msg=" Falling back to iptables-based masquerading." subsys=daemon
```
if I remove `enable-host-legacy-routing: "true"` setting, then I got:

```
level=info msg=“BPF host routing requires kernel 5.10 or newer. Falling back to legacy host routing (enable-host-legacy-routing=true).” subsys=daemon
level=warning msg=” Falling back to iptables-based masquerading.” subsys=daemon
```
again it falls back to iptables based masqurading

so it is unclear if eBPF based masquerading is supported on 4.19 kernel or not, maybe https://docs.cilium.io/en/latest/operations/system_requirements/#admin-system-reqs should be updated to mention what kernel version start to support eBPF based masquerading, I could do test to verify.

### PR DESCRIPTION
**Pull request by vincentmli**
when missing tunnel and socketLB service check and  when legacy host routing
set to true, the msg is empty with log

"level=warning msg=" Falling back to iptables-based masquerading." subsys=daemon"

this is confusing to users and not sure why falling back to iptables-based masquerading

before the fix:

run cilium agent in kernel 4.19 with

1 BPF masq enabled
2 Host legacy routing enabled
3 Tunnel enabled
4 FullHostReachableServices false

Cilium agent logs:
 "level=warning msg=" Falling back to iptables-based masquerading." subsys=daemon"

the msg is empty because none of the switch cases matches, this could mis-lead users to
think BPF masquerade is not supported on kernel 4.19.

then when:

1 BPF masq enabled
2 Host legacy routing enabled
3 Tunnel disabled
4 Nodeport enabled

cilium agent keeps BPF masquerade enabled on kernel 4.19 without falling back to iptables-based masquerading

after the fix:

cilum agent log should log correct message + "Falling back to iptables-based masquerading."

Signed-off-by: Vincent Li <v.li@f5.com>

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

Fixes: #21237

```release-note
fix empty message when tunnel and socketLB service missing in switch case
```

### CODE REVIEW

**Review by ldelossa — APPROVED** [review]

File: daemon/cmd/daemon.go [hunk 1]
```diff
@@ -930,6 +930,9 @@ func NewDaemon(ctx context.Context, cleaner *daemonCleanup, epMgr *endpointmanag
 		case option.Config.EgressMasqueradeInterfaces != "":
 			msg = fmt.Sprintf("BPF masquerade does not allow to specify devices via --%s (use --%s instead).",
 				option.EgressMasqueradeInterfaces, option.Devices)
+		case option.Config.EnableHostLegacyRouting:
+			msg = fmt.Sprintf("BPF masquerade requires full host reachable services enabled in tunnel mode but host legacy routing (--%s=\"true\")",
```
Comment (pchaigno) [inline daemon/cmd/daemon.go]: Host reachable services (a.k.a. socket-level load balancing) and legacy host routing are two different things.

I think it would also be better to refactor this code so we don't have to keep the switch cases in sync. with the above if condition.

**Review by pchaigno — CHANGES_REQUESTED** [review]

File: daemon/cmd/daemon.go (hunk 1 above)
Comment (vincentmli) [reply daemon/cmd/daemon.go]: @brb it appears you are familiar with this part of code and the background, what do you think about the refactor?

Comment (vincentmli) [reply daemon/cmd/daemon.go]: it looks we can merge the if checks block and the switch case checks so we don't need to check the options twice.

Comment (vincentmli) [reply daemon/cmd/daemon.go]: I made an initial refactor, please check if that is ok, I could not test it locally as it appears `make dev-docker-image` stop working anymore probably due to some master branch changes

Comment (pchaigno) [reply daemon/cmd/daemon.go]: > I could not test it locally as it appears `make dev-docker-image` stop working anymore probably due to some master branch changes

It works fine for me (on commit 1059b958c8e9f9c88a810218ccc928900e4c98df). Are you on latest master? If you are and it persists, could you open a thread on Slack?

File: daemon/cmd/daemon.go [hunk 2]
```diff
@@ -921,9 +921,7 @@ func NewDaemon(ctx context.Context, cleaner *daemonCleanup,
 	// BPF masquerade depends on BPF NodePort and require host-reachable svc to
 	// be fully enabled in the tunneling mode, so the following checks should
 	// happen after invoking initKubeProxyReplacementOptions().
-	if option.Config.EnableIPv4Masquerade && option.Config.EnableBPFMasquerade &&
-		(!option.Config.EnableNodePort || option.Config.EgressMasqueradeInterfaces != "" || !option.Config.EnableRemoteNodeIdentity ||
-			(option.Config.TunnelingEnabled() && !hasFullHostReachableServices())) {
+	if option.Config.EnableIPv4Masquerade && option.Config.EnableBPFMasquerade {
```
Comment (pchaigno) [inline daemon/cmd/daemon.go:924]: This refactoring will end up always disabling BPF masquerading and throwing a warning.

File: daemon/cmd/daemon.go [hunk 3]
```diff
@@ -936,6 +934,13 @@ func NewDaemon(ctx context.Context, cleaner *daemonCleanup,
 		case option.Config.EgressMasqueradeInterfaces != "":
 			msg = fmt.Sprintf("BPF masquerade does not allow to specify devices via --%s (use --%s instead).",
 				option.EgressMasqueradeInterfaces, option.Devices)
+		case option.Config.TunnelingEnabled():
+			if !hasFullHostReachableServices() {
```
Comment (pchaigno) [inline daemon/cmd/daemon.go]:
```suggestion
		case option.Config.TunnelingEnabled() && !hasFullHostReachableServices() {
```

File: daemon/cmd/daemon.go [hunk 4]
```diff
@@ -936,6 +934,13 @@ func NewDaemon(ctx context.Context, cleaner *daemonCleanup,
...
+				msg = "BPF masquerade requires full host reachable services enabled in tunnel mode."
+			}
+		case option.Config.EnableHostLegacyRouting:
+			msg = fmt.Sprintf("BPF masquerade requires host legacy routing (--%s=\"false\")",
+				option.EnableHostLegacyRouting)
```
Comment (pchaigno) [inline daemon/cmd/daemon.go]: Why was this case added?

**Review by pchaigno — CHANGES_REQUESTED** [review]

File: daemon/cmd/daemon.go (hunk 4 above)
Comment (vincentmli) [reply daemon/cmd/daemon.go]: this is when I set host legacy routing to true in my test, then non of the switch cases match, result in empty msg, then following `log.Warn(msg + " Falling back to iptables-based masquerading.")` logs empty msg + `Falling back to iptables-based masquerading`, user will be confused why falling back to iptables-based masquerading,  the `if !option.Config.EnableHostLegacyRouting {` at the end of the block check does not match, so the `log.Info` is missed too

File: daemon/cmd/daemon.go (hunk 3 above)
Comment (vincentmli) [reply daemon/cmd/daemon.go]: the  suggestion result in error `daemon/cmd/daemon.go|938 col 35| expected ':', found '{' (and 3 more errors)`, what about 
```
case option.Config.TunnelingEnabled() && !hasFullHostReachableServices():
                        msg = "BPF masquerade requires full host reachable services enabled in tunnel mode."
```

File: daemon/cmd/daemon.go (hunk 2 above)
Comment (vincentmli) [reply daemon/cmd/daemon.go:924]: ah, maybe add `if (msg)` then set `option.Config.EnableBPFMasquerade = false`

File: daemon/cmd/daemon.go (hunk 3 above)
Comment (pchaigno) [reply daemon/cmd/daemon.go]: Yep, that's what I meant to write :+1:

File: daemon/cmd/daemon.go (hunk 4 above)
Comment (pchaigno) [reply daemon/cmd/daemon.go]: Are you sure this was related to legacy host routing? Could it not be because you had host reachable services disabled?

File: daemon/cmd/daemon.go (hunk 2 above)
Comment (vincentmli) [reply daemon/cmd/daemon.go:924]: I also don't need to add the switch `case option.Config.EnableHostLegacyRouting` after the refactor, since empty msg will not happen even I enable `option.Config.EnableHostLegacyRouting`

File: daemon/cmd/daemon.go (hunk 4 above)
Comment (vincentmli) [reply daemon/cmd/daemon.go]: after refactor and add `if msg`, does not make sense to add `option.Config.EnableHostLegacyRouting` switch case, the refactor seems not only improve the code, but also the logic, please check the new changes to see if it make sense

**Review by pchaigno — CHANGES_REQUESTED** [review]
The code looks good to me!

The commit description needs to be updated to reflect latest changes. Could you please also separate refactoring from fix, i.e. in 2 commits?

**Comment by vincentmli** [comment]
sure will do

File: daemon/cmd/daemon.go [hunk 5]
```diff
@@ -939,14 +939,16 @@ func NewDaemon(ctx context.Context, cleaner *daemonCleanup,
...
 		// this  statement, so it's OK to fallback to iptables-based MASQ.
-		option.Config.EnableBPFMasquerade = false
-		log.Warn(msg + " Falling back to iptables-based masquerading.")
-		// Too bad, if we need to revert to iptables-based MASQ, we also cannot
-		// use BPF host routing since we need the upper stack.
-		if !option.Config.EnableHostLegacyRouting {
-			option.Config.EnableHostLegacyRouting = true
-			log.Infof("BPF masquerade could not be enabled. Falling back to legacy host routing (--%s=\"true\").",
-				option.EnableHostLegacyRouting)
+		if len(msg) > 0 {
```
Comment (pchaigno) [inline daemon/cmd/daemon.go]: The check on `msg` belongs in the refactoring.

File: daemon/cmd/daemon.go [hunk 6]
```diff
@@ -936,6 +934,8 @@ func NewDaemon(ctx context.Context, cleaner *daemonCleanup,
 		case option.Config.EgressMasqueradeInterfaces != "":
 			msg = fmt.Sprintf("BPF masquerade does not allow to specify devices via --%s (use --%s instead).",
 				option.EgressMasqueradeInterfaces, option.Devices)
+		case option.Config.TunnelingEnabled() && !hasFullHostReachableServices():
+			msg = "BPF masquerade requires full host reachable services enabled in tunnel mode."
```
Comment (pchaigno) [inline daemon/cmd/daemon.go]: This change belongs in the fix commit. You'll have to place the fix commit before the refactoring commit to avoid introducing a regression in between the two commits.

**Review by pchaigno — CHANGES_REQUESTED** [review]

File: daemon/cmd/daemon.go (hunk 5 above)
Comment (vincentmli) [reply daemon/cmd/daemon.go]: ack

File: daemon/cmd/daemon.go (hunk 6 above)
Comment (vincentmli) [reply daemon/cmd/daemon.go]: yep, make sense

**Review by pchaigno — APPROVED** [review]

**Review by jibi — APPROVED** [review]
Not sure if it would be more idiomatic to make `msg` an `error` and then log it with `log.WithError(err).Warn("Falling back to iptables-based masquerading.")`?

**Comment by vincentmli** [comment]
> log.WithError(err).Warn("Falling back to iptables-based masquerading.")

you mean something like this?

```
diff --git a/daemon/cmd/daemon.go b/daemon/cmd/daemon.go
index e2f967d9a0..8f74241d0a 100644
--- a/daemon/cmd/daemon.go
+++ b/daemon/cmd/daemon.go
@@ -923,25 +923,25 @@ func NewDaemon(ctx context.Context, cleaner *daemonCleanup,
        // happen after invoking initKubeProxyReplacementOptions().
        if option.Config.EnableIPv4Masquerade && option.Config.EnableBPFMasquerade {
 
-               var msg string
+               var err error
                switch {
                case !option.Config.EnableNodePort:
-                       msg = fmt.Sprintf("BPF masquerade requires NodePort (--%s=\"true\").",
+                       err = fmt.Sprintf("BPF masquerade requires NodePort (--%s=\"true\").",
                                option.EnableNodePort)
                case !option.Config.EnableRemoteNodeIdentity:
-                       msg = fmt.Sprintf("BPF masquerade requires remote node identities (--%s=\"true\").",
+                       err = fmt.Sprintf("BPF masquerade requires remote node identities (--%s=\"true\").",
                                option.EnableRemoteNodeIdentity)
                case option.Config.EgressMasqueradeInterfaces != "":
-                       msg = fmt.Sprintf("BPF masquerade does not allow to specify devices via --%s (use --%s instead).",
+                       err = fmt.Sprintf("BPF masquerade does not allow to specify devices via --%s (use --%s instead).",
                                option.EgressMasqueradeInterfaces, option.Devices)
                case option.Config.TunnelingEnabled() && !hasFullHostReachableServices():
-                       msg = "BPF masquerade requires full host reachable services enabled in tunnel mode."
+                       err = "BPF masquerade requires full host reachable services enabled in tunnel mode."
                }
                // ipt.InstallRules() (called by Reinitialize()) happens later than
                // this  statement, so it's OK to fallback to iptables-based MASQ.
-               if len(msg) > 0 {
+               if err != nil {
                        option.Config.EnableBPFMasquerade = false
-                       log.Warn(msg + " Falling back to iptables-based masquerading.")
+                       log.WithError(err).Warn("Falling back to iptables-based masquerading.")
                        // Too bad, if we need to revert to iptables-based MASQ, we also cannot
                        // use BPF host routing since we need the upper stack.
                        if !option.Config.EnableHostLegacyRouting {
```

**Comment by jibi** [comment]
> you mean something like this?

yup, but using `fmt.Errorf()` instead of `fmt.Sprintf()`, as that will return an object of type `error` (also no need for the `.`s at the end of all the error messages then)

**Comment by vincentmli** [comment]
like `err = fmt.Errorf("BPF masquerade requires NodePort (--%s=\"true\")"` ?

**Review by jibi — APPROVED** [review]
Double approval :heavy_check_mark: :heavy_check_mark: 
Thanks for going through the refactoring and nits :pray:
