### PR TITLE
iptables: handle case where kernel IPv6 support is disabled

### LINKED ISSUE #18513: cilium-agents crashing / cmd="[ip6tables -w 5 -t nat -S]" error="exit status 3" subsys=iptable
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

i am currently implementing cilium CNI with a rke2 without kube-proxy mode. And currently facing the issue below.

### Cilium Version

cilium:v1.10.4 

### Kernel Version

workernodes
Ubuntu 20.04.3 LTS/ Kernel: Linux 5.4.0-84-generic
Oracle Linux Server 8.5/  Kernel: Linux 5.4.17-2136.300.7.el8uek.x86_64

### Kubernetes Version

v1.22.4+rke2r1

### Sysdump

n/a

### Relevant log output

```shell
level=error msg="Command execution failed" cmd="[ip6tables -w 5 -t nat -S]" error="exit status 3" subsys=iptables
level=warning msg="ip6tables v1.8.4 (legacy): can't initialize ip6tables table `nat': Address family not supported by protocol" subsys=iptables
level=warning msg="Perhaps ip6tables or your kernel needs to be upgraded." subsys=iptables
level=error msg="Command execution failed" cmd="[ip6tables -w 5 -t mangle -S]" error="exit status 3" subsys=iptables
level=warning msg="ip6tables v1.8.4 (legacy): can't initialize ip6tables table `mangle': Address family not supported by protocol" subsys=iptables
level=warning msg="Perhaps ip6tables or your kernel needs to be upgraded." subsys=iptables
level=error msg="Command execution failed" cmd="[ip6tables -w 5 -t raw -S]" error="exit status 3" subsys=iptables
level=warning msg="ip6tables v1.8.4 (legacy): can't initialize ip6tables table `raw': Address family not supported by protocol" subsys=iptables
level=warning msg="Perhaps ip6tables or your kernel needs to be upgraded." subsys=iptables
level=error msg="Command execution failed" cmd="[ip6tables -w 5 -t filter -S]" error="exit status 3" subsys=iptables
level=warning msg="ip6tables v1.8.4 (legacy): can't initialize ip6tables table `filter': Address family not supported by protocol" subsys=iptables
level=warning msg="Perhaps ip6tables or your kernel needs to be upgraded." subsys=iptables
level=error msg="Command execution failed" cmd="[ip6tables -w 5 -t nat -S]" error="exit status 3" subsys=iptables
level=warning msg="ip6tables v1.8.4 (legacy): can't initialize ip6tables table `nat': Address family not supported by protocol" subsys=iptables
level=warning msg="Perhaps ip6tables or your kernel needs to be upgraded." subsys=iptables
level=error msg="Command execution failed" cmd="[ip6tables -w 5 -t mangle -S]" error="exit status 3" subsys=iptables
level=warning msg="ip6tables v1.8.4 (legacy): can't initialize ip6tables table `mangle': Address family not supported by protocol" subsys=iptables
level=warning msg="Perhaps ip6tables or your kernel needs to be upgraded." subsys=iptables
level=error msg="Command execution failed" cmd="[ip6tables -w 5 -t raw -S]" error="exit status 3" subsys=iptables
level=warning msg="ip6tables v1.8.4 (legacy): can't initialize ip6tables table `raw': Address family not supported by protocol" subsys=iptables
level=warning msg="Perhaps ip6tables or your kernel needs to be upgraded." subsys=iptables
level=error msg="Command execution failed" cmd="[ip6tables -w 5 -t filter -S]" error="exit status 3" subsys=iptables
level=warning msg="ip6tables v1.8.4 (legacy): can't initialize ip6tables table `filter': Address family not supported by protocol" subsys=iptables
```
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #20672: Cilium Agent 1.10.13 fails to run w/ ipv6.disable=1 kernel parameter
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After upgrading from 1.10.12 to 1.10.13, our cilium-agent processes now fail with a `FATAL` log due to `ip6table` usage. My understanding is that this is because we have configured the kernel parameter `ipv6.disable=1`. 

Prior to 1.10.13, these were just error's that were ignored, I highlighted this back on https://github.com/cilium/cilium/issues/18513#issuecomment-1151357567. However, the iptables logic was reworked in https://github.com/cilium/cilium/pull/19693 which results in the same logic being handled as FATAL. 

Specifically, prior to 1.10.13:
* https://github.com/cilium/cilium/blob/v1.10.12/pkg/datapath/iptables/iptables.go#L202-L205 <--  just return'ed 
* https://github.com/cilium/cilium/blob/v1.10.12/pkg/datapath/iptables/iptables.go#L498 <-- no error handling, results in the errors getting logged but ignored otherwise. 

But in 1.10.13 we now return an error that get's bubbled up to FATAL:
* https://github.com/cilium/cilium/blob/v1.10.13/pkg/datapath/iptables/iptables.go#L219-L222 <-- now returns an err
* https://github.com/cilium/cilium/blob/v1.10.13/pkg/datapath/iptables/iptables.go#L366-L370 <-- now returns the err from above
* https://github.com/cilium/cilium/blob/v1.10.13/daemon/cmd/daemon_main.go#L1674 <-- where we end up and thus exit

Related to all of this is some additional complexity, even with the `ipv6.disable=1` kernel parameter configured, the ip6table modules loaded in https://github.com/cilium/cilium/blob/v1.10.13/pkg/datapath/iptables/iptables.go#L291 do exist on disk and successfully load but when used result in the error `ip6tables v1.8.4 (legacy): can't initialize ip6tables table `nat': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n (exit status 3)` getting thrown. We do run the agent's w/ `--enable-ipv6=false` configured but, the logic in this file still results in `haveIp6tables` to staying set to `true`. 

### Cilium Version

1.10.13

### Kernel Version

`Linux ip-10-128-59-96 5.15.0-1015-aws #19~20.04.1-Ubuntu SMP Wed Jun 22 19:07:51 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

`v1.21.9`

### Sysdump

_No response_

### Relevant log output

```shell
level=fatal msg="Error while creating daemon" error="failed to install iptables rules: unable to run 'ip6tables -t nat -S' iptables command: ip6tables v1.8.4 (legacy): can't initialize ip6tables table `nat': Address family not supported by protocol\nPerhaps ip6tables or your kernel needs to be upgraded.\n (exit status 3)" subsys=daemon
```
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jibi**
Currently, even if the kernel IPv6 support is disabled (i.e. the
ipv6.disable=1 kernel parameter is set), the agent will try to find or
load the ip6tables kernel modules, and if successful it will assume
ip6tables is supported.

This will result in a fatal error since all ip6tables commands will
fail with "Address family not supported".

This commit fixes this by setting the haveIp6tables IptablesManager's
property to false in case the kernel does not support IPv6.

Fixes: d812b925de ("iptables: don't ignore errors")
Fixes: #18513
Fixes: #20672

### CODE REVIEW

File: pkg/datapath/iptables/iptables.go [hunk 1]
```diff
@@ -297,6 +297,18 @@ func (m *IptablesManager) Init() {
 			"ip6tables kernel modules could not be loaded, so IPv6 cannot be used")
 		haveIp6tables = false
 	}
+
+	ipv6Disabled, err := sysctl.Read("net.ipv6.conf.all.disable_ipv6")
```
Comment (julianwiedmann) [inline pkg/datapath/iptables/iptables.go]: I'm a bit uneasy about [this part](https://github.com/torvalds/linux/blob/6e7765cb477a9753670d4351d14de93f1e9dbbd4/Documentation/networking/ip-sysctl.rst?plain=1#L1998):

> **Reading this value does not have any particular meaning**. It does not say
> whether IPv6 support is enabled or disabled. Returned value can be 1
> also in the case when some interface has ``disable_ipv6`` set to 0 and
> has configured IPv6 addresses.

If this is strictly about the `ipv6.disable=1` option, should we be looking at `/sys/module/ipv6/parameters/disable` instead?

**Review by julianwiedmann — CHANGES_REQUESTED** [review]
ugh, I remember having an uneasy feeling about this...

For the commit message:
- can you please add what specific case this covers? It's the [ipv6.disable=1](https://github.com/torvalds/linux/blob/master/Documentation/networking/ipv6.rst) module parameter, correct?
- think we need a `Fixes:` tag for the commit that introduced the regression.

File: pkg/datapath/iptables/iptables.go (hunk 1 above)
Comment (jibi) [reply pkg/datapath/iptables/iptables.go]: So in my test I set the `ipv6.disable=1` kernel parameter (which is what the bug report is about) which then results in `net.ipv6.conf.all.disable_ipv6` being set to `1`.

I'm going for this check mostly for consistency as we are already using it in another part of the codebase:

https://github.com/cilium/cilium/blob/94ea7fc93e0af5bf3ddab5b67508003ca47678cd/pkg/datapath/loader/base.go#L316

but relying on `/sys/module/ipv6/parameters/disable` would be fine as well

Comment (julianwiedmann) [reply pkg/datapath/iptables/iptables.go]: > So in my test I set the `ipv6.disable=1` kernel parameter (which is what the bug report is about) which then results in `net.ipv6.conf.all.disable_ipv6` being set to `1`.
> 
> I'm going for this check mostly for consistency as we are already using it in another part of the codebase:
> 
> https://github.com/cilium/cilium/blob/94ea7fc93e0af5bf3ddab5b67508003ca47678cd/pkg/datapath/loader/base.go#L316
> 
> but relying on `/sys/module/ipv6/parameters/disable` would be fine as well


The sysctl doesn't feel like a good fit for catching `ipv6.disable=1` to me. It just controls IPv6 operations on the selected network interface(s), no? For instance, if I manually set `net.ipv6.conf.all.disable_ipv6=1` in combination with `ipv6.disable=0`, then running the reproducer (`ip6tables -w 5 -t nat -S`) still works fine.

Comment (jibi) [reply pkg/datapath/iptables/iptables.go]: Right, setting `net.ipv6.conf.all.disable_ipv6=1` will not impact the `ip6tables` command, although the inet6 addresses get removed from the interfaces:
```
vagrant@k8s1:~$ ip a | grep inet6
vagrant@k8s1:~$
```

let's switch to `/sys/module/ipv6/parameters/disable` then :+1:

File: pkg/datapath/iptables/iptables.go [hunk 2]
```diff
@@ -297,6 +298,18 @@ func (m *IptablesManager) Init() {
...
+	ipv6Disabled, err := os.ReadFile("/sys/module/ipv6/parameters/disable")
+	if err != nil {
+		log.WithError(err).Warning(
+			"Unable to read /sys/module/ipv6/parameters/disable, disabling IPv6 iptables support")
+		haveIp6tables = false
+	} else if strings.TrimSuffix(string(ipv6Disabled), "\n") == "1" {
+		log.Debug(
+			"Kernel does not support IPv6, disabling IPv6 iptables support")
+		haveIp6tables = false
+	}
```
Comment (julianwiedmann) [inline pkg/datapath/iptables/iptables.go:315]: Wondering whether we should `Fatal()` if `option.Config.EnableIPv6` is set, to match what we do in the earlier check for the ip6_tables kernel modules.

**Review by julianwiedmann — APPROVED** [review]
lgtm, thanks for the quick fix jibi! One further comment, but feel free to ignore.

File: pkg/datapath/iptables/iptables.go (hunk 2 above)
Comment (jibi) [reply pkg/datapath/iptables/iptables.go:315]: Yeah good shout :+1:

File: pkg/datapath/iptables/iptables.go [hunk 3]
```diff
@@ -297,6 +298,22 @@ func (m *IptablesManager) Init() {
...
+	if err != nil {
+		if option.Config.EnableIPv6 {
+			log.WithError(err).Fatal(
+				"IPv6 is enabled but IPv6 kernel support could not be probed")
+		}
+		log.WithError(err).Warning(
+			"Unable to read /sys/module/ipv6/parameters/disable, disabling IPv6 iptables support")
+		haveIp6tables = false
+	} else if strings.TrimSuffix(string(ipv6Disabled), "\n") == "1" {
+		log.Debug(
```
Comment (YutaroHayakawa) [inline pkg/datapath/iptables/iptables.go:312]: I think we should show this message to users even if it is not a Fatal. Maybe it should be a Warning?

**Review by YutaroHayakawa — APPROVED** [review]
LGTM with a nit (almost the same as Julian's one) 👍

**Review by ldelossa — APPROVED** [review]

File: pkg/datapath/iptables/iptables.go (hunk 3 above)
Comment (jibi) [reply pkg/datapath/iptables/iptables.go:312]: I'm following the same pattern as above (i.e. emitting a debug logline in case we fail to find/load ip6tables modules):
https://github.com/cilium/cilium/blob/78d075d1bedf7f6e3890dd2a9fab20383201f3c4/pkg/datapath/iptables/iptables.go#L290-L297

**Comment by brb** [comment]
I thought that the issue got fixed with the closure of https://github.com/cilium/cilium/issues/18904

**Comment by jibi** [comment]
> I thought that the issue got fixed with the closure of #18904

That change only handles the case where IPv6 support is enabled in Cilium but we can't find the related ip6tables modules (but apparently we can still load them even if the kernel has disabled IPv6 support)

**Comment by niklaspm** [comment]
Same issue here on Debian 11 + IPTables (1.8.7-1)

**Comment by niklaspm** [comment]
Same issue here on Debian 11 + IPTables (1.8.7-1)
