### PR TITLE
daemon: cleaning up leftover veths

### LINKED ISSUE #696: Cleanup stale network interfaces
For several reasons, stale interfaces can be left behind if endpoint generation fails unexpectedly:
```
207: tmp2ba93@lxc2ba93: <BROADCAST,MULTICAST> mtu 1450 qdisc noop state DOWN mode DEFAULT group default
    link/ether 7e:65:13:a6:17:d2 brd ff:ff:ff:ff:ff:ff
208: lxc2ba93@tmp2ba93: <NO-CARRIER,BROADCAST,MULTICAST,UP,M-DOWN> mtu 1450 qdisc noqueue state LOWERLAYERDOWN mode DEFAULT group default
    link/ether 7a:b8:ac:ce:fb:9c brd ff:ff:ff:ff:ff:ff
209: tmp6c496@lxc6c496: <BROADCAST,MULTICAST> mtu 1450 qdisc noop state DOWN mode DEFAULT group default
    link/ether 6a:f3:b3:64:e4:1d brd ff:ff:ff:ff:ff:ff
210: lxc6c496@tmp6c496: <NO-CARRIER,BROADCAST,MULTICAST,UP,M-DOWN> mtu 1450 qdisc noqueue state LOWERLAYERDOWN mode DEFAULT group default
    link/ether b2:61:94:23:a7:d9 brd ff:ff:ff:ff:ff:ff
```

### PR DESCRIPTION
**Pull request by aanm**
On a development environment some veths can be left uncleaned leading to
a pile up of unused veths.

This commit tries to clean all veths created by cilium (veths with name
starting with "lxc") that are non longer being used by a moby container.

Signed-off-by: André Martins <andre@cilium.io>

Fixes #696

@tgraf I wasn't sure where to put the code. Also which proper level I should use to log the messages.

### CODE REVIEW

File: daemon/daemon.go [hunk 1]
```diff
@@ -969,3 +977,98 @@ func (d *Daemon) StopIgnoringContainer(id string) {
...
+	}
+
+	for _, pid := range pids {
+		nsPath := fmt.Sprintf("/proc/%d/ns/net", pid)
+		netNs, err := ns.GetNS(nsPath)
+		if err != nil {
+			log.Debugf("CleanVeths: Error openning netns %q: %s", nsPath, err)
+			continue
+		}
+		err = netNs.Do(func(_ ns.NetNS) error {
```
Comment (tgraf) [inline daemon/daemon.go]: Given the issue with go subroutines and namespaces. Is this safe?

File: daemon/daemon.go [hunk 2]
```diff
@@ -969,3 +977,98 @@ func (d *Daemon) StopIgnoringContainer(id string) {
...
+
+	if err != nil {
+		return fmt.Errorf("unable to retrieve host network interfaces: %s", err)
+	}
+
+	conts, err := dc.ContainerList(context.Background(), dTypes.ContainerListOptions{})
+	if err != nil {
+		return fmt.Errorf("unable to retrieve all containers running in docker: %s", err)
+	}
+
```
Comment (tgraf) [inline daemon/daemon.go]: I think you can drastically simplify this if we can make the following assumption:
- We never perform networking for an endpoint without the the peer veth being in another network namespace.

If we make that assumption then it becomes extremely simple to figure out whether it is an unused veth pair:
```
for _, l := range leftVeths {
        peerIndex := l.Attrs().ParentIndex
        if _, ok := leftVeths[peerIndex]; !ok && peerIndex {
                // peer of l is not in namespace, schedule l for removal
        }
}
```

**Review by tgraf — CHANGES_REQUESTED** [review]
Simplification suggestion, let me know what you think

**Review by tgraf — APPROVED** [review]
