### PR TITLE
dnsproxy: Do not bind to IPv4 or IPv6 when disabled

### LINKED ISSUE #7916: FQDN Proxy binding should not fail when IPv6 is disabled/missing
cilium-agent Fatals when it cannot bind the DNS proxy (after some minutes). This can happen when a machine boots without IPv6 and cannot bind to [::1].

```
level=debug msg="DNS Proxy port is configured to 0. A random port will be assigned by the OS." subsys=fqdn/dnsproxy
level=debug msg="DNS Proxy bound to address" address="0.0.0.0:41193" subsys=fqdn/dnsproxy
level=error msg="bindUDP failed for address ::1: listen ip:udp ::1: socket: address family not supported by protocol" subsys=fqdn/dnsproxy
level=error msg="Failed to start the udp DNS proxy on 0.0.0.0:41193" error="Unable to open raw UDP sockets for DNS Proxy" subsys=fqdn/dnsproxy
```

@jrajahalme I'm happy to make the patch for this but I wanted to double-check:
Should the check for this (https://github.com/cilium/cilium/blob/master/pkg/fqdn/dnsproxy/udp.go#L132) suppress the IPv6 case if IPv6 is not enabled? Is there a way to detect that it isn't enabled?
(I will also fix the final "Failed to start" message to report both IPv4 and IPv6 addresses)

It also seems like the `--tofqdns-proxy-port` CLI param is now unused. If so, I'll mark it deprecated (or just remove it, it's already "broken").

### PR DESCRIPTION
**Pull request by raybejjani**
It is common to boot with IPv6 disabled outright, and the IPv6 loopback
at ::1 won't exist. We assumed it did and would fail to bind, eventually
causing a fatal in the proxy.

Fixes https://github.com/cilium/cilium/issues/7916

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7917)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

File: pkg/fqdn/dnsproxy/udp.go [hunk 1]
```diff
@@ -55,37 +60,39 @@ type sessionUDP struct {
 	oob   []byte
 }
 
-var ciliumSessionUDPFactory = &sessionUDPFactory{}
```
Comment (raybejjani) [inline pkg/fqdn/dnsproxy/udp.go:58]: Removing this isn't great. We the options controlling this are parsed after init() or package variables would be created, though. Perhaps it is better to make this an init function like:
```
var sesssionFactoryOnce sync.Once

func makeCiliumSessionUDPFactory(ipv4, ipv6 bool) *ciliumSessionUDPFactory {
	sesssionFactoryOnce.Do(func() {
		ciliumSessionUDPFactory = &sessionUDPFactory{ipv4: ipv4, ipv6: ipv6}
	})
	return ciliumSessionUDPFactory
}
```

Comment (jrajahalme) [reply pkg/fqdn/dnsproxy/udp.go:58]: I see no harm in deleting this. Simpler the way you changed it in this PR.

File: pkg/fqdn/dnsproxy/udp.go [hunk 2]
```diff
@@ -42,6 +42,11 @@ var udpOOBSize = func() int {
 type sessionUDPFactory struct {
 	// A pool for UDP message buffers.
 	udpPool sync.Pool
+
+	// ipv4Enabled and ipv6Enabled are used when setting up the proxy sockets
+	// later, and determine if we bind to 127.0.0.1 and ::1, respectively.
+	// See sessionUDPFactory.SetSocketOptions
+	ipv4Enabled, ipv6Enabled bool
```
Comment (jrajahalme) [inline pkg/fqdn/dnsproxy/udp.go:49]: Looks like these would need to be named `ipv4` and `ipv6` for the code to compile?

**Review by jrajahalme — APPROVED** [review]
Looks OK in principle, might not compile yet, though.

File: pkg/fqdn/dnsproxy/udp.go (hunk 2 above)
Comment (raybejjani) [reply pkg/fqdn/dnsproxy/udp.go:49]: 😊 yup... a few things were wrong :/

**Comment by raybejjani** [comment]
test-me-please

File: pkg/fqdn/dnsproxy/udp.go [hunk 3]
```diff
@@ -55,37 +60,41 @@ type sessionUDP struct {
...
-	if err4 != nil && err6 != nil {
-		return err4
+	if ipv4 {
+		err4 = unix.SetsockoptInt(fd, unix.SOL_IP, unix.IP_TRANSPARENT, 1)
+		if err4 == nil {
+			err4 = unix.SetsockoptInt(fd, unix.SOL_IP, unix.IP_RECVORIGDSTADDR, 1)
+		}
+		// Only error out if both IPv4 and IPv6 fail, or if either fails and the
+		// other is disabled (the !ip* bits).
+		if (!ipv4 || err4 != nil) && (!ipv6 || err6 != nil) {
```
Comment (raybejjani) [inline pkg/fqdn/dnsproxy/udp.go]: I think this logic attempted to account for the case where ipv6 wasn't enabled, by only returning err4. Now that either type can be enabled or disabled, does this actually need to unconditionally return err6 above and err4 here?

File: pkg/fqdn/dnsproxy/udp.go [hunk 4]
```diff
@@ -126,10 +138,10 @@ func (f *sessionUDPFactory) SetSocketOptions(conn *net.UDPConn) error {
 	//   checking that a route exists from the source address before
 	//   the source address is replaced with the (transparently) changed one
 	udpOnce.Do(func() {
-		rawconn4 = bindUDP("127.0.0.1") // raw socket for sending IPv4
-		rawconn6 = bindUDP("::1")       // raw socket for sending IPv6
+		rawconn4 = bindUDP("127.0.0.1", f.ipv4Enabled, f.ipv6Enabled) // raw socket for sending IPv4
+		rawconn6 = bindUDP("::1", f.ipv4Enabled, f.ipv6Enabled)       // raw socket for sending IPv6
```
Comment (raybejjani) [inline pkg/fqdn/dnsproxy/udp.go]: @jrajahalme The comments for `transparentSetsockopt` suggest that either socket may receive traffic in either address family. Is this correct? (and does it need comments in case someone else ever debugs it?)

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

File: pkg/fqdn/dnsproxy/proxy.go [hunk 5]
```diff
@@ -171,14 +171,15 @@ func StartDNSProxy(address string, port uint16, lookupEPFunc LookupEndpointIDByI
...
+		UDPConn                *net.UDPConn
+		TCPListener            *net.TCPListener
+		err                    error
+		EnableIPv4, EnableIPv6 = option.Config.EnableIPv4, option.Config.EnableIPv6
 	)
 
 	start := time.Now()
 	for time.Since(start) < ProxyBindTimeout {
-		UDPConn, TCPListener, err = bindToAddr(address, port)
+		UDPConn, TCPListener, err = bindToAddr(address, port, option.Config.EnableIPv4, option.Config.EnableIPv6)
```
Comment (ianvernon) [inline pkg/fqdn/dnsproxy/proxy.go]: Why not pass `EnableIPv4` and `EnableIPv6` here ?

File: pkg/fqdn/dnsproxy/udp.go (hunk 3 above)
Comment (ianvernon) [reply pkg/fqdn/dnsproxy/udp.go]: This would return a nil error in the case of !ipv4 but an error from ipv6, though.

**Review by ianvernon — CHANGES_REQUESTED** [review]

**Comment by ianvernon** [comment]
I think this should be backported - thoughts @raybejjani ?

File: pkg/fqdn/dnsproxy/udp.go (hunk 3 above)
Comment (raybejjani) [reply pkg/fqdn/dnsproxy/udp.go]: How so? I see it breaking down as below, but I think I will just make this error out if either has an error and is enabled. There is too much subtlety here.
```
(!ipv4 || err4 != nil) && (!ipv6 || err6 != nil)
(true || err4 != nil) && (!ipv6 || err6 != nil) <-- ipv4 is disabled, !ipv4 is true
(true) && (!ipv6 || err6 != nil) <-- (!ipv4 || err4 != nil) is also true because of the ||
(true) && (false || err6 != nil) <-- ipv6 is enabled, !ipv6 is false
(true) && (false || true) <-- let's say err6 != nil, hence true
(true) && (true) <-- (!ipv6 || err6 != nil) is now true
so true
```

File: pkg/fqdn/dnsproxy/proxy.go (hunk 5 above)
Comment (raybejjani) [reply pkg/fqdn/dnsproxy/proxy.go]: Because I forgot! Good catch :)

**Comment by raybejjani** [comment]
@ianvernon Was this code in 1.5? it was merged on April 18. If it is, then it needs to be backported. If not, then the older code didn't have this specific issue because it only worked with IPv4 anyway.

**Comment by raybejjani** [comment]
I've hand tested this on a machine without ipv6... I think it's correct but I probably missed something. Unfortunately, I need to run so I'll revisit this later/

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

File: pkg/fqdn/dnsproxy/udp.go (hunk 3 above)
Comment (ianvernon) [reply pkg/fqdn/dnsproxy/udp.go]: Oops, you are right 🤦‍♂

**Review by ianvernon — APPROVED** [review]

**Comment by raybejjani** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
Saw the following errors in the CI run:
```
00:32:27.480  Failed to start the udp DNS proxy on [::]:39389
00:32:27.480  Failed to start the udp DNS proxy on [::]:37967
00:32:27.480  bindUDP failed for address 127.0.0.1: listen ip:udp 127.0.0.1: protocol not available
00:32:27.480  bindUDP failed for address ::1: listen ip:udp ::1: protocol not available
00:32:27.480  Unable to release endpoint ID
```

**Review by tgraf — CHANGES_REQUESTED** [review]
See errors in CI

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]
