### PR TITLE
daemon: drop the non headless service/endpoint resources

### LINKED ISSUE #35797: Cilium agents start duplicate Service/Endpointslice informers
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

Starting from v1.16, each Cilium agent starts two services and endpointslices informers, introducing extra load on the Kubernetes API Server. The main commits that appear to contribute to the regression are 99268e7ba1c7, cce40804c3ac and 0e8c5a64f37a,  because a few consumers leverage the filtered resources, while a few others the unfiltered ones.

The best fix is probably dropping the filtered resource altogether (assuming it is possible, adapting the consumers accordingly), to prevent regressions in the future due to the mixed usage of the two resources.

### How can we reproduce the issue?

This issue can be validated checking the `apiserver_longrunning_requests` Kubernetes API Server metric. For instance, on a four nodes kind cluster:

```
# Cilium agents are not running
$ kubectl get --raw /metrics | grep apiserver_longrunning_requests | egrep '"services|endpointslices"'
apiserver_longrunning_requests{component="apiserver",group="",resource="services",scope="cluster",subresource="",verb="WATCH",version="v1"} 13
apiserver_longrunning_requests{component="apiserver",group="discovery.k8s.io",resource="endpointslices",scope="cluster",subresource="",verb="WATCH",version="v1"} 7

# Cilium agents are running
$ kubectl get --raw /metrics | grep apiserver_longrunning_requests | egrep '"services|endpointslices"'
apiserver_longrunning_requests{component="apiserver",group="",resource="services",scope="cluster",subresource="",verb="WATCH",version="v1"} 21
apiserver_longrunning_requests{component="apiserver",group="discovery.k8s.io",resource="endpointslices",scope="cluster",subresource="",verb="WATCH",version="v1"} 15
```

### Cilium Version

Cilium v1.16 and above

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by MrFreezeex**
Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

Before this PR two types of resources were exposed for services and endpoints: one excluding headless services/endpoints and one including them. This PR drop the non headless resource (and make the necessary changes to accommodate that) to make sure we only start one informer for services and endpoints and lower the load the apiserver.

Fixes: #35797

```release-note
Remove duplicated watch on services and endpoint in the cilium-agent
```

### CODE REVIEW

**Comment by MrFreezeex** [comment]
All the usage of service/endpoints resources and service cache in the daemon: (not finished)
- Service cache support headless services: https://github.com/cilium/cilium/blob/6e7ea13b8daaf169fe6745f22f8bb616eaa4133c/pkg/k8s/service_cache.go#L337 -> https://github.com/cilium/cilium/blob/6e7ea13b8daaf169fe6745f22f8bb616eaa4133c/pkg/k8s/service.go#L210
- Policy: get service from service cache https://github.com/cilium/cilium/blob/6e7ea13b8daaf169fe6745f22f8bb616eaa4133c/pkg/policy/k8s/service.go#L100 & https://github.com/cilium/cilium/blob/6e7ea13b8daaf169fe6745f22f8bb616eaa4133c/pkg/policy/k8s/watcher.go#L35. Policy handling doesn't seems to require the frontend IP. Letting headless services be processed should result in CNP being able to process headless services without any new handling.
- BGP speaker (metallb integration): Doesn't seems to read the cluster IP at all but rather the IP in the load balancer ingress, see: https://github.com/cilium/cilium/blob/6e7ea13b8daaf169fe6745f22f8bb616eaa4133c/pkg/bgp/speaker/speaker.go#L324
- Datapath from service cache: The datapath already ignores headless services after processing via the service cache: https://github.com/cilium/cilium/blob/6e7ea13b8daaf169fe6745f22f8bb616eaa4133c/pkg/k8s/watchers/service.go#L213 & https://github.com/cilium/cilium/blob/6e7ea13b8daaf169fe6745f22f8bb616eaa4133c/pkg/k8s/watchers/service.go#L508

**Comment by MrFreezeex** [comment]
I believe this should be ready for reviews. Although, it needs reviews from more groups than sig-k8s/sig-agent, and in particular (according to code owners) @cilium/sig-bgp, @cilium/sig-policy , @cilium/sig-lb (for redirect policy).

I tried to summarize the impact of this change here: https://github.com/cilium/cilium/pull/35838#issuecomment-2462156948, TLDR: according to my research it should have no impact outside of policies that will start to include headless Services (which might count as an additional feature?). But this needs reviews from all the groups mentioned above to validate that and have their opinion.

Also cc @giorio94 @marseel that found this this issue (thanks again for finding it!)

File: pkg/k8s/service.go [hunk 1]
```diff
@@ -208,6 +208,9 @@ func ParseService(svc *slim_corev1.Service, nodePortAddrs []netip.Addr) (Service
 	}
 
 	headless := false
+	if svc.Labels != nil {
+		_, headless = svc.Labels[v1.IsHeadlessService]
+	}
```
Comment (giorio94) [inline pkg/k8s/service.go]: Nit. You don't need the `if` check, as you read from a nil map:

> A nil map is equivalent to an empty map except that no elements may be added.

File: pkg/k8s/watchers/service.go [hunk 2]
```diff
@@ -211,10 +211,9 @@ func (k *K8sServiceWatcher) RunK8sServiceHandler() {
 
 func (k *K8sServiceWatcher) delK8sSVCs(svc k8s.ServiceID, svcInfo *k8s.Service) {
 	// Headless services do not need any datapath implementation
-	if svcInfo.IsHeadless {
+	if svcInfo.IsHeadless && len(svcInfo.FrontendIPs) == 0 {
```
Comment (giorio94) [inline pkg/k8s/watchers/service.go:215]: I reckon that this is needed to avoid leftover entries when a non headless service is subsequently marked with the `service.kubernetes.io/headless` label. Could you please add a comment here (and as part of the commit message), so that we don't miss this context in the future?

File: pkg/k8s/watchers/service_test.go [hunk 3]
```diff
@@ -9,6 +9,7 @@ import (
 
 	"github.com/cilium/statedb"
 	"github.com/stretchr/testify/require"
+	v1 "k8s.io/api/core/v1"
```
Comment (giorio94) [inline pkg/k8s/watchers/service_test.go]: Nit. `corev1`

File: pkg/k8s/watchers/service_test.go [hunk 4]
```diff
@@ -2470,3 +2471,120 @@ func Test_addK8sSVCs_ExternalIPs(t *testing.T) {
 	require.EqualValues(t, del1stWanted, del1st)
 	require.EqualValues(t, del2ndWanted, del2nd)
 }
+
+func TestHeadless(t *testing.T) {
```
Comment (giorio94) [inline pkg/k8s/watchers/service_test.go:2477]: This test fails when run individually (I guess that some other test before is mangling with the global state):

```
$ got ./pkg/k8s/watchers/ --run TestHeadless --count=1

--- FAIL: TestHeadless (0.00s)
    service_test.go:2588: 
                Error Trace:    /home/marco/Documents/isovalent/cilium/pkg/k8s/watchers/service_test.go:2588
                Error:          Not equal: 
                                expected: []loadbalancer.SVC{loadbalancer.SVC{Frontend:loadbalancer.L3n4AddrID{L3n4Addr:loadbalancer.L3n4Addr{AddrCluster:types.AddrCluster{addr:netip.Addr{addr:netip.uint128{hi:0x0, lo:0xffffac001401}, z:unique.Handle[net/netip.addrDetail]{value:(*netip.addrDetail)(0xc0000137e8)}}, clusterID:0x0}, L4Addr:loadbalancer.L4Addr{Protocol:"UDP", Port:0x50}, Scope:0x0}, ID:0x0}, Backends:[]*loadbalancer.Backend{(*loadbalancer.Backend)(0xc0004f3680)}, Type:"ClusterIP", ForwardingMode:"", ExtTrafficPolicy:"", IntTrafficPolicy:"", NatPolicy:"", SessionAffinity:false, SessionAffinityTimeoutSec:0x0, HealthCheckNodePort:0x0, Name:loadbalancer.ServiceName{Namespace:"", Name:"", Cluster:""}, LoadBalancerSourceRanges:[]*cidr.CIDR(nil), L7LBProxyPort:0x0, LoopbackHostport:false, Annotations:map[string]string(nil)}}
                                actual  : []loadbalancer.SVC{loadbalancer.SVC{Frontend:loadbalancer.L3n4AddrID{L3n4Addr:loadbalancer.L3n4Addr{AddrCluster:types.AddrCluster{addr:netip.Addr{addr:netip.uint128{hi:0x0, lo:0xffffac001401}, z:unique.Handle[net/netip.addrDetail]{value:(*netip.addrDetail)(0xc0000137e8)}}, clusterID:0x0}, L4Addr:loadbalancer.L4Addr{Protocol:"ANY", Port:0x50}, Scope:0x0}, ID:0x0}, Backends:[]*loadbalancer.Backend{(*loadbalancer.Backend)(0xc0004f3780)}, Type:"ClusterIP", ForwardingMode:"", ExtTrafficPolicy:"", IntTrafficPolicy:"", NatPolicy:"", SessionAffinity:false, SessionAffinityTimeoutSec:0x0, HealthCheckNodePort:0x0, Name:loadbalancer.ServiceName{Namespace:"", Name:"", Cluster:""}, LoadBalancerSourceRanges:[]*cidr.CIDR(nil), L7LBProxyPort:0x0, LoopbackHostport:false, Annotations:map[string]string(nil)}}
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -20,3 +20,3 @@
                                     L4Addr: (loadbalancer.L4Addr) {
                                -     Protocol: (string) (len=3) "UDP",
                                +     Protocol: (string) (len=3) "ANY",
                                      Port: (uint16) 80
                                @@ -51,3 +51,3 @@
                                      L4Addr: (loadbalancer.L4Addr) {
                                -      Protocol: (string) (len=3) "UDP",
                                +      Protocol: (string) (len=3) "ANY",
                                       Port: (uint16) 8080
                Test:           TestHeadless
FAIL
FAIL    github.com/cilium/cilium/pkg/k8s/watchers       1.254s
FAIL
```

**Review by giorio94 — COMMENTED** [review]
Thanks for addressing this! A few minor comments inline.

> Redirect policy: Seems to be handling headless services well by ignoring service without frontend ips.

I assume this may be problematic in case of services marked as headless via the label, but associated with a ClusterIP, given that they would have a frontend IP.

> And policy handling doesn't seems to require the frontend IP. Letting headless services be processed should result in CNP being able to process headless services without any new handling.

I personally don't have enough context to comment on this.

**Comment by giorio94** [comment]
Requested extra reviews as per:

> Although, it needs reviews from more groups than sig-k8s/sig-agent, and in particular (according to code owners) @cilium/sig-bgp, @cilium/sig-policy , @cilium/sig-lb (for redirect policy).

**Comment by giorio94** [comment]
Marked for backport to v1.16, given that it is the only release affected from this.

File: pkg/k8s/watchers/service_test.go (hunk 4 above)
Comment (MrFreezeex) [reply pkg/k8s/watchers/service_test.go:2477]: Hmm that's true I am not super familiar with those tests but I can try to dig a bit more. This seems to affect some other tests in here too though:
```
❯ go test ./pkg/k8s/watchers/ --run TestChangeSVCPort --count=1
time="2024-11-11T16:03:13.74922495+01:00" level=warning msg="service not found" k8sNamespace=bar k8sSvcName=foo obj="{AddrCluster:172.0.20.1 L4Addr:{Protocol:ANY Port:80} Scope:0}" subsys=k8s-watcher
--- FAIL: TestChangeSVCPort (0.00s)
    service_test.go:483:
        	Error Trace:	/home/aouthenin/cilium/pkg/k8s/watchers/service_test.go:483
        	Error:      	Not equal:
        	            	expected: []loadbalancer.SVC{loadbalancer.SVC{Frontend:loadbalancer.L3n4AddrID{L3n4Addr:loadbalancer.L3n4Addr{AddrCluster:types.AddrCluster{addr:netip.Addr{addr:netip.uint128{hi:0x0, lo:0xffffac001401}, z:unique.Handle[net/netip.addrDetail]{value:(*netip.addrDetail)(0xc000013818)}}, clusterID:0x0}, L4Addr:loadbalancer.L4Addr{Protocol:"UDP", Port:0x50}, Scope:0x0}, ID:0x0}, Backends:[]*loadbalancer.Backend{(*loadbalancer.Backend)(0xc000a7a200)}, Type:"ClusterIP", ForwardingMode:"", ExtTrafficPolicy:"", IntTrafficPolicy:"", NatPolicy:"", SessionAffinity:false, SessionAffinityTimeoutSec:0x0, HealthCheckNodePort:0x0, Name:loadbalancer.ServiceName{Namespace:"", Name:"", Cluster:""}, LoadBalancerSourceRanges:[]*cidr.CIDR(nil), L7LBProxyPort:0x0, LoopbackHostport:false, Annotations:map[string]string(nil)}, loadbalancer.SVC{Frontend:loadbalancer.L3n4AddrID{L3n4Addr:loadbalancer.L3n4Addr{AddrCluster:types.AddrCluster{addr:netip.Addr{addr:netip.uint128{hi:0x0, lo:0xffffac001401}, z:unique.Handle[net/netip.addrDetail]{value:(*netip.addrDetail)(0xc000013818)}}, clusterID:0x0}, L4Addr:loadbalancer.L4Addr{Protocol:"UDP", Port:0x51}, Scope:0x0}, ID:0x0}, Backends:[]*loadbalancer.Backend{(*loadbalancer.Backend)(0xc000a7a280)}, Type:"ClusterIP", ForwardingMode:"", ExtTrafficPolicy:"", IntTrafficPolicy:"", NatPolicy:"", SessionAffinity:false, SessionAffinityTimeoutSec:0x0, HealthCheckNodePort:0x0, Name:loadbalancer.ServiceName{Namespace:"", Name:"", Cluster:""}, LoadBalancerSourceRanges:[]*cidr.CIDR(nil), L7LBProxyPort:0x0, LoopbackHostport:false, Annotations:map[string]string(nil)}}
        	            	actual  : []loadbalancer.SVC{loadbalancer.SVC{Frontend:loadbalancer.L3n4AddrID{L3n4Addr:loadbalancer.L3n4Addr{AddrCluster:types.AddrCluster{addr:netip.Addr{addr:netip.uint128{hi:0x0, lo:0xffffac001401}, z:unique.Handle[net/netip.addrDetail]{value:(*netip.addrDetail)(0xc000013818)}}, clusterID:0x0}, L4Addr:loadbalancer.L4Addr{Protocol:"ANY", Port:0x50}, Scope:0x0}, ID:0x0}, Backends:[]*loadbalancer.Backend{(*loadbalancer.Backend)(0xc000a7a380)}, Type:"ClusterIP", ForwardingMode:"", ExtTrafficPolicy:"", IntTrafficPolicy:"", NatPolicy:"", SessionAffinity:false, SessionAffinityTimeoutSec:0x0, HealthCheckNodePort:0x0, Name:loadbalancer.ServiceName{Namespace:"", Name:"", Cluster:""}, LoadBalancerSourceRanges:[]*cidr.CIDR(nil), L7LBProxyPort:0x0, LoopbackHostport:false, Annotations:map[string]string(nil)}, loadbalancer.SVC{Frontend:loadbalancer.L3n4AddrID{L3n4Addr:loadbalancer.L3n4Addr{AddrCluster:types.AddrCluster{addr:netip.Addr{addr:netip.uint128{hi:0x0, lo:0xffffac001401}, z:unique.Handle[net/netip.addrDetail]{value:(*netip.addrDetail)(0xc000013818)}}, clusterID:0x0}, L4Addr:loadbalancer.L4Addr{Protocol:"ANY", Port:0x51}, Scope:0x0}, ID:0x0}, Backends:[]*loadbalancer.Backend{(*loadbalancer.Backend)(0xc000a7a400)}, Type:"ClusterIP", ForwardingMode:"", ExtTrafficPolicy:"", IntTrafficPolicy:"", NatPolicy:"", SessionAffinity:false, SessionAffinityTimeoutSec:0x0, HealthCheckNodePort:0x0, Name:loadbalancer.ServiceName{Namespace:"", Name:"", Cluster:""}, LoadBalancerSourceRanges:[]*cidr.CIDR(nil), L7LBProxyPort:0x0, LoopbackHostport:false, Annotations:map[string]string(nil)}}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -20,3 +20,3 @@
        	            	     L4Addr: (loadbalancer.L4Addr) {
        	            	-     Protocol: (string) (len=3) "UDP",
        	            	+     Protocol: (string) (len=3) "ANY",
        	            	      Port: (uint16) 80
        	            	@@ -51,3 +51,3 @@
        	            	      L4Addr: (loadbalancer.L4Addr) {
        	            	-      Protocol: (string) (len=3) "UDP",
        	            	+      Protocol: (string) (len=3) "ANY",
        	            	       Port: (uint16) 8080
        	            	@@ -97,3 +97,3 @@
        	            	     L4Addr: (loadbalancer.L4Addr) {
        	            	-     Protocol: (string) (len=3) "UDP",
        	            	+     Protocol: (string) (len=3) "ANY",
        	            	      Port: (uint16) 81
        	            	@@ -128,3 +128,3 @@
        	            	      L4Addr: (loadbalancer.L4Addr) {
        	            	-      Protocol: (string) (len=3) "UDP",
        	            	+      Protocol: (string) (len=3) "ANY",
        	            	       Port: (uint16) 8080
        	Test:       	TestChangeSVCPort
FAIL
FAIL	github.com/cilium/cilium/pkg/k8s/watchers	0.019s
FAIL
```

**Comment by MrFreezeex** [comment]
> I assume this may be problematic in case of services marked as headless via the label, but associated with a ClusterIP, given that they would have a frontend IP.

Indeed! I can definitely add some additional check for that if needed (cc @cilium/sig-lb).

Note that AFAICT this handling of a service is treated as headless if the label has `service.kubernetes.io/headless` is not super common outside of kube-proxy/associated conformance tests IIUC. For instance coredns doesn't seems to treat a service like that as headless: https://github.com/coredns/coredns/blob/387f34db9a4f6fefd4a6b54884772ccd4fc059e7/plugin/kubernetes/object/service.go#L80 so as redirect policy is something specific to Cilium I believe we could choose to ignore headless services or to treat any service with a frontend IP as a valid candidate (whether it's headless or not) for redirect policy.

**Comment by giorio94** [comment]
> Note that AFAICT the handling of a service is treated as headless if the label has `service.kubernetes.io/headless` is not super common outside of kube-proxy/associated conformance tests IIUC. 

I agree, that looks really a corner case, which is probably not handled consistently by every project.

File: pkg/k8s/watchers/service_test.go (hunk 4 above)
Comment (giorio94) [reply pkg/k8s/watchers/service_test.go:2477]: My guess is that this is caused by a few other tests in the same file setting `option.Config.LoadBalancerProtocolDifferentiation = true` and never reverting it at the end of the test.

**Review by YutaroHayakawa — APPROVED** [review]
BGP looks good to me. Thanks!

File: pkg/k8s/watchers/service_test.go (hunk 4 above)
Comment (MrFreezeex) [reply pkg/k8s/watchers/service_test.go:2477]: Ohh yes indeed thanks! AFAICT this option should be set to true by default so it would makes sense to force it to true as some other test also does. I did this for `TestChangeSVCPort` that was missing this too

**Review by christarazi — APPROVED** [review]

**Review by thorn3r — APPROVED** [review]
LGTM, thanks for the quick attention :+1:

**Review by nathanjsweet — APPROVED** [review]

**Review by giorio94 — APPROVED** [review]
Sorry, I just noticed I had not explicitly approved it.

**Review by joamaki — APPROVED** [review]
