### PR TITLE
fix: Error using multiple allowRoutes namespaces in gateway

### LINKED ISSUE #30085: Error using multiple allowRoutes namespaces in Gateway
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When creating a gateway with multiple listeners, there is an issue when sections use different allowedRoutes configurations.  The section allowing routes from all namespaces is not honored and receive a `NotAllowedByListeners` status.

One of the sections is setup to allowRoutes from the same namespace and the other section should allow all. 
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  namespace: cilium-gateway
spec:
  gatewayClassName: cilium
  listeners:
  - protocol: HTTP
    port: 80
    name: http
    allowedRoutes:
      kinds:
        - kind: HTTPRoute
      namespaces:
        from: Same
  - protocol: HTTPS
    port: 443
    name: https
    tls:
      certificateRefs:
      - kind: Secret
        name: wildcard-production
        namespace: cilium-secrets
    allowedRoutes:
      namespaces:
        from: All
```

Then create a redirect HTTPRoute for the http listener
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: httpsredirect-internalgw
  namespace: cilium-gateway
spec:
  parentRefs:
    - name: internal
      namespace: cilium-gateway
      sectionName: http
  rules:
    - filters:
        - requestRedirect:
            scheme: https
            statusCode: 301
          type: RequestRedirect
```

And another HTTPRoute for the HTTPS listener in another namespace
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: httpbin
  namespace: test-zone
spec:
  parentRefs:
  - name: internal
    namespace: cilium-gateway
    sectionName: https
  hostnames:
  - "httpbin.test.tld"
  rules:
  - backendRefs:
    - name: httpbin
      port: 80
```

The httpbin HTTPRoute then returns
```
status:
  parents:
    - conditions:
        - lastTransitionTime: '2024-01-02T17:58:26Z'
          message: >-
            HTTPRoute is not allowed to attach to this Gateway due to namespace
            restrictions
          observedGeneration: 1
          reason: NotAllowedByListeners
          status: 'False'
          type: Accepted
        - lastTransitionTime: '2024-01-01T16:30:55Z'
          message: Service reference is valid
          observedGeneration: 1
          reason: ResolvedRefs
          status: 'True'
          type: ResolvedRefs
      controllerName: io.cilium/gateway-controller
      parentRef:
        group: gateway.networking.k8s.io
        kind: Gateway
        name: internal
        namespace: cilium-gateway
        sectionName: https
```

### Cilium Version

1.15.0-rc.0

### Kernel Version

```
uname -a
Linux rockchip1 5.10.160-rockchip #21 SMP Mon Nov 20 00:36:42 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

### Kubernetes Version

1.29.0+k3s1

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

Gateway Custom Resource Definition https://github.com/kubernetes-sigs/gateway-api/blob/v1.0.0/config/crd/standard/gateway.networking.k8s.io_gateways.yaml

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by chaunceyjiang**
Fixes: #30085

```release-note
Fix error when using multiple allowRoutes namespaces in gateway
```

### CODE REVIEW

**Comment by acelinkio** [comment]
Mentioned this in the parent issue, but also commenting here.  

Confirmed this fix works!  Tested by deploying the 1.15.0-rc0 helm chart and using the container image generated in the PR workflow ((https://github.com/cilium/cilium/actions/runs/7407854202/job/20154860573?pr=30100). 

values
```
operator:
  image:
   override: "quay.io/cilium/operator-generic-ci:bd0f507f2d5f3912c512f2fe728e0b19c974b88d"
```

File: operator/pkg/gateway-api/routechecks/gateway_checks.go [hunk 1]
```diff
@@ -34,10 +34,12 @@ func CheckGatewayAllowedForNamespace(input Input, parentRef gatewayv1.ParentRefe
...
 			continue
 		}
-
+		if parentRef.SectionName != nil && listener.Name != *parentRef.SectionName {
+			continue
+		}
 		// if gateway allows all namespaces, we do not need to check anything here
 		if *listener.AllowedRoutes.Namespaces.From == gatewayv1.NamespacesFromAll {
-			continue
+			return true, nil
```
Comment (meyskens) [inline operator/pkg/gateway-api/routechecks/gateway_checks.go:42]: We're returning here inside a loop over listeners? This would stop checks on the 2nd listener for any issues

File: operator/pkg/gateway-api/routechecks/gateway_checks.go [hunk 2]
```diff
@@ -63,22 +65,25 @@ func CheckGatewayAllowedForNamespace(input Input, parentRef gatewayv1.ParentRefe
 
 				return false, nil
 			}
+			return true, nil
```
Comment (meyskens) [inline operator/pkg/gateway-api/routechecks/gateway_checks.go:68]: same as above

File: operator/pkg/gateway-api/routechecks/gateway_checks.go [hunk 3]
```diff
@@ -63,22 +65,25 @@ func CheckGatewayAllowedForNamespace(input Input, parentRef gatewayv1.ParentRefe
...
-				Message: input.GetGVK().Kind + " is not allowed to attach to this Gateway due to namespace restrictions",
-			})
-
-			return false, nil
+			input.GetNamespace() == gw.GetNamespace() {
+			return true, nil
 		}
+		namespaceRestriction = true
+	}
+	if namespaceRestriction {
```
Comment (meyskens) [inline operator/pkg/gateway-api/routechecks/gateway_checks.go]: small nit can we name this to indicate it is a bool we set in the loop, maybe something like `hasNamespaceRestriction`?

**Review by meyskens — COMMENTED** [review]
Good catch for the bug just a few small things to look into

File: operator/pkg/gateway-api/routechecks/gateway_checks.go (hunk 1 above)
Comment (chaunceyjiang) [reply operator/pkg/gateway-api/routechecks/gateway_checks.go:42]: Assuming the first listener of the gateway is `All`, and the second listener is `Same`, and the `SectionName` of HTTPRoute is empty, if we continue to judge that the second listener is here, then issue #30085 still cannot be resolved.

According to the description at https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.ParentReference.

> If 1 of 2 Gateway listeners accept attachment from the referencing Route, the Route MUST be considered successfully attached

Therefore, I suggest using `return` here instead of `continue`.

File: operator/pkg/gateway-api/routechecks/gateway_checks.go (hunk 3 above)
Comment (chaunceyjiang) [reply operator/pkg/gateway-api/routechecks/gateway_checks.go]: Updated.

**Comment by sayboras** [comment]
Thanks for the ping. I was not aware of this PR, and was working on the fix for the same issue.

**Review by sayboras — APPROVED** [review]
Thanks and lgtm :heavy_check_mark:
