### PR TITLE
proxylib: Fix data races in unit tests

### LINKED ISSUE #16315: [Race Detector] Race in proxylib between `(*ClientSuite).TestRequestAllResources()` and `(*ClientSuite).UpsertNetworkPolicy`
Found in Travis CI:
* https://travis-ci.com/github/cilium/cilium/jobs/508002930
* https://travis-ci.com/github/cilium/cilium/jobs/507726146

```
WARNING: DATA RACE
Read at 0x00c000459fe0 by goroutine 24:
  github.com/cilium/cilium/proxylib/npds.(*ClientSuite).TestRequestAllResources()
      /home/travis/gopath/src/github.com/cilium/cilium/proxylib/npds/client_test.go:108 +0x2b7
  runtime.call16()
      /home/travis/.gimme/versions/go1.16.4.linux.amd64/src/runtime/asm_amd64.s:550 +0x3d
  reflect.Value.Call()
      /home/travis/.gimme/versions/go1.16.4.linux.amd64/src/reflect/value.go:337 +0xd8
  gopkg.in/check%2ev1.(*suiteRunner).forkTest.func1()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:775 +0xb3b
  gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:669 +0xe1

Previous write at 0x00c000459fe0 by goroutine 56:
  github.com/cilium/cilium/proxylib/npds.(*ClientSuite).UpsertNetworkPolicy.func1()
      /home/travis/gopath/src/github.com/cilium/cilium/proxylib/npds/client_test.go:67 +0x19a
  github.com/cilium/cilium/pkg/completion.(*Completion).Complete()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/completion/completion.go:166 +0x2b5
  github.com/cilium/cilium/pkg/envoy/xds.(*AckingResourceMutatorWrapper).HandleResourceVersionAck()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/envoy/xds/ack.go:339 +0xbb4
  github.com/cilium/cilium/pkg/envoy/xds.(*Server).processRequestStream()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/envoy/xds/server.go:353 +0x1093
  github.com/cilium/cilium/pkg/envoy/xds.(*Server).HandleRequestStream()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/envoy/xds/server.go:184 +0x395
  github.com/cilium/cilium/pkg/envoy.(*xdsGRPCServer).StreamNetworkPolicies()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/envoy/grpc.go:95 +0xc9
  github.com/cilium/proxy/go/cilium/api._NetworkPolicyDiscoveryService_StreamNetworkPolicies_Handler()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/github.com/cilium/proxy/go/cilium/api/npds.pb.go:1548 +0xcf
  google.golang.org/grpc.(*Server).processStreamingRPC()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/google.golang.org/grpc/server.go:1329 +0x1627
  google.golang.org/grpc.(*Server).handleStream()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/google.golang.org/grpc/server.go:1409 +0x131e
  google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/google.golang.org/grpc/server.go:746 +0xe6

Goroutine 24 (running) created at:
  gopkg.in/check%2ev1.(*suiteRunner).forkCall()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:666 +0x459
  gopkg.in/check%2ev1.(*suiteRunner).forkTest()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:757 +0x1c4
  gopkg.in/check%2ev1.(*suiteRunner).runTest()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:812 +0x23e
  gopkg.in/check%2ev1.(*suiteRunner).run()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:618 +0x1dc
  gopkg.in/check%2ev1.Run()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/run.go:92 +0x5a
  gopkg.in/check%2ev1.RunAll()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/run.go:84 +0x136
  gopkg.in/check%2ev1.TestingT()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/run.go:72 +0x5ef
  github.com/cilium/cilium/proxylib/npds.Test()
      /home/travis/gopath/src/github.com/cilium/cilium/proxylib/npds/client_test.go:37 +0x38
  testing.tRunner()
      /home/travis/.gimme/versions/go1.16.4.linux.amd64/src/testing/testing.go:1193 +0x202

Goroutine 56 (running) created at:
  google.golang.org/grpc.(*Server).serveStreams.func1()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/google.golang.org/grpc/server.go:744 +0xb8
  google.golang.org/grpc/internal/transport.(*http2Server).operateHeaders()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/google.golang.org/grpc/internal/transport/http2_server.go:442 +0x1850
  google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/google.golang.org/grpc/internal/transport/http2_server.go:483 +0x49c
  google.golang.org/grpc.(*Server).serveStreams()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/google.golang.org/grpc/server.go:742 +0x1c7
  google.golang.org/grpc.(*Server).handleRawConn.func1()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/google.golang.org/grpc/server.go:703 +0x4c
```

Might be related to https://github.com/cilium/cilium/issues/16296

/cc @jrajahalme

### LINKED ISSUE #16371: [Race Detector] Race in proxylib package between `(*AccessLogServer).Close()` and `StartAccessLogServer.func1()`
Found in Travis:  https://travis-ci.com/github/cilium/cilium/jobs/509157458
```
Read at 0x00c000502128 by goroutine 99:
  github.com/cilium/cilium/proxylib/test.(*AccessLogServer).Close()
      /home/travis/gopath/src/github.com/cilium/cilium/proxylib/test/accesslog_server.go:48 +0xbc
  github.com/cilium/cilium/proxylib.TestTwoRulesOnSamePortFirstNoL7()
      /home/travis/gopath/src/github.com/cilium/cilium/proxylib/proxylib_test.go:446 +0x265
  testing.tRunner()
      /home/travis/.gimme/versions/go1.16.4.linux.amd64/src/testing/testing.go:1193 +0x202

Previous write at 0x00c000502128 by goroutine 100:
  github.com/cilium/cilium/proxylib/test.StartAccessLogServer.func1()
      /home/travis/gopath/src/github.com/cilium/cilium/proxylib/test/accesslog_server.go:116 +0x1ed

Goroutine 99 (running) created at:
  testing.(*T).Run()
      /home/travis/.gimme/versions/go1.16.4.linux.amd64/src/testing/testing.go:1238 +0x5d7
  testing.runTests.func1()
      /home/travis/.gimme/versions/go1.16.4.linux.amd64/src/testing/testing.go:1511 +0xa6
  testing.tRunner()
      /home/travis/.gimme/versions/go1.16.4.linux.amd64/src/testing/testing.go:1193 +0x202
  testing.runTests()
      /home/travis/.gimme/versions/go1.16.4.linux.amd64/src/testing/testing.go:1509 +0x612
  testing.(*M).Run()
      /home/travis/.gimme/versions/go1.16.4.linux.amd64/src/testing/testing.go:1417 +0x3b3
  main.main()
      _testmain.go:291 +0x356

Goroutine 100 (finished) created at:
  github.com/cilium/cilium/proxylib/test.StartAccessLogServer()
      /home/travis/gopath/src/github.com/cilium/cilium/proxylib/test/accesslog_server.go:99 +0x42f
  github.com/cilium/cilium/proxylib.TestTwoRulesOnSamePortFirstNoL7()
      /home/travis/gopath/src/github.com/cilium/cilium/proxylib/proxylib_test.go:415 +0x66
  testing.tRunner()
      /home/travis/.gimme/versions/go1.16.4.linux.amd64/src/testing/testing.go:1193 +0x202
```

### PR DESCRIPTION
**Pull request by gandro**
This fixes two data races in the proxylib unit ests. I've verified this locally using:

```
go test -count 100 -race ./proxylib
```

Fixes: #16315
Fixes: #16371

### CODE REVIEW

File: proxylib/test/accesslog_server.go [hunk 1]
```diff
@@ -26,6 +27,7 @@ type AccessLogServer struct {
 	Logs     chan cilium.EntryType
 	closing  uint32 // non-zero if closing, accessed atomically
```
Comment (aditighag) [inline proxylib/test/accesslog_server.go]: NYC, but atomic read/write to this variable seems like an overkill in this particular context. Using channel/context might have been straightforward. But that might be outside of the scope of your PR.

**Review by aditighag — APPROVED** [review]

File: proxylib/npds/client_test.go [hunk 2]
```diff
@@ -94,6 +95,6 @@ func (s *ClientSuite) TestRequestAllResources(c *C) {
 	s.UpsertNetworkPolicy(c, xdsServer, resources[0])
 
 	time.Sleep(DialDelay * BackOffLimit)
-	c.Assert(s.acks, Equals, 1)
-	c.Assert(s.nacks, Equals, 0)
+	c.Assert(atomic.LoadUint64(&s.acks), Equals, 1)
```
Comment (aditighag) [inline proxylib/npds/client_test.go]: Travis failure is related - 

```
----------------------------------------------------------------------
FAIL: client_test.go:74: ClientSuite.TestRequestAllResources
client_test.go:98:
    c.Assert(atomic.LoadUint64(&s.acks), Equals, 1)
... obtained uint64 = 0x1
... expected int = 1
OOPS: 0 passed, 1 FAILED
--- FAIL: Test (11.00s)
```

```suggestion
	c.Assert(atomic.LoadUint64(&s.acks), Equals, uint64(1))
```

**Review by aditighag — CHANGES_REQUESTED** [review]
The updated test checks need to be fixed.

File: proxylib/npds/client_test.go (hunk 2 above)
Comment (gandro) [reply proxylib/npds/client_test.go]: Huh, thanks! Wonder why this didn't trigger when I tested locally. Maybe I tested the wrong package. Will first reproduce it locally and then fix.

File: proxylib/test/accesslog_server.go (hunk 1 above)
Comment (gandro) [reply proxylib/test/accesslog_server.go]: Yes, I had the thought, but I am not familiar at all with this code, so I figured I'd leave it for now. But since I have to revise anyways, I will take another look at this.

Comment (gandro) [reply proxylib/test/accesslog_server.go]: Decided to use a channel.

File: proxylib/npds/client_test.go (hunk 2 above)
Comment (gandro) [reply proxylib/npds/client_test.go]: Turns out I wasn't running tests in the sub package. Fixed now.

File: proxylib/npds/client_test.go [hunk 3]
```diff
@@ -27,8 +28,8 @@ func Test(t *testing.T) {
 }
 
 type ClientSuite struct {
-	acks  int
-	nacks int
+	acks  uint64
```
Comment (aditighag) [inline proxylib/npds/client_test.go:31]: I think you are having to make this an atomic variable just to synchronize the goroutine write and reads in the assert call in the test case. Again, nyc, but it looks like the the test case should've synchronized the calls via a channel instead of adding sleep. The callback function in `UpsertNetworkPolicy` can signal on a channel that the test case blocks on. Anyway I can revisit this in a separate PR. 

I don't really understand the sleep duration specified in this block - 

```
// Create version 1 with resource 0.
	s.UpsertNetworkPolicy(c, xdsServer, resources[0])

	time.Sleep(DialDelay * BackOffLimit) ------> there is no back-off?
	c.Assert(s.acks, Equals, 1)
	c.Assert(s.nacks, Equals, 0)
```

File: proxylib/test/accesslog_server.go [hunk 4]
```diff
@@ -25,7 +24,7 @@ import (
 type AccessLogServer struct {
 	Path     string
 	Logs     chan cilium.EntryType
-	closing  uint32 // non-zero if closing, accessed atomically
+	done     chan struct{}
```
Comment (aditighag) [inline proxylib/test/accesslog_server.go:27]: Looks much better now. Thanks!

**Review by aditighag — APPROVED** [review]

File: proxylib/npds/client_test.go (hunk 3 above)
Comment (gandro) [reply proxylib/npds/client_test.go:31]: Fully agreed, I have the same feeling here. But I haven't spend the time to understand it yet. 

I'll leave this open for now (as there is no urgency to merge it). If I find time in the next few to clean this up, I will do it in this PR, otherwise I'll label it ready-to-merge (assuming this doesn't need a Jenkins run, since it's unit tests only).

**Comment by gandro** [comment]
Marking this ready to merge, I will do the discussed improvements potentially in a follow-up PR (which then also doesn't have to be backported).

Both tests are covered by Travis, so no need to run Jenkins.
