### PR TITLE
node-neigh: Fix unit test flake

### LINKED ISSUE #16040: CI: RuntimePrivilegedUnitTests TestArpPingHandling failed, expected 'true' got 'false'
```
 node_linux_test.go:1049:
	     c.Assert(found, check.Equals, true)
	 ... obtained bool = false
	 ... expected bool = true
	 
START: node_linux_test.go:137: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest
PASS: node_linux_test.go:137: linuxPrivilegedIPv4OnlyTestSuite.TearDownTest	0.044s

FAIL: node_linux_test.go:955: linuxPrivilegedIPv4OnlyTestSuite.TestArpPingHandling
```

https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/4618/testReport/junit/(root)/Suite-runtime/RuntimePrivilegedUnitTests_Run_Tests/

[867e2c23_RuntimePrivilegedUnitTests_Run_Tests.zip](https://github.com/cilium/cilium/files/6435560/867e2c23_RuntimePrivilegedUnitTests_Run_Tests.zip)

### LINKED ISSUE #16075: CI: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest
## CI failure
Output from failure:
```
17:05:08  	 
17:05:08  	 START: node_linux_test.go:955: linuxPrivilegedIPv4OnlyTestSuite.TestArpPingHandling
17:05:08  	 START: node_linux_test.go:116: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest
17:05:08  	 PASS: node_linux_test.go:116: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest	0.001s
17:05:08  	 
17:05:08  	 node_linux_test.go:1161:
17:05:08  	     c.Assert(neighHwAddr(ip1.String()), check.Equals, mac.String())
17:05:08  	 ... obtained string = "f6:27:bb:80:88:10"
17:05:08  	 ... expected string = "4a:4c:8c:84:d1:20"
17:05:08  	 
```

Link to CI build: https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/4628/execution/node/99/log/?consoleFull

Link to PR where this happened: https://github.com/cilium/cilium/pull/16041

### PR DESCRIPTION
**Pull request by brb**
See commit msgs.

Fix #16040 
Fix #16075

### CODE REVIEW

**Comment by brb** [comment]
test-runtime

**Comment by brb** [comment]
test-net-next

File: pkg/datapath/linux/node_linux_test.go [hunk 1]
```diff
@@ -1026,18 +1027,41 @@ func (s *linuxPrivilegedIPv4OnlyTestSuite) TestArpPingHandling(c *check.C) {
...
+	}
+
 	nodev1 := nodeTypes.Node{
 		Name:        "node1",
 		IPAddresses: []nodeTypes.Address{{nodeaddressing.NodeInternalIP, ip1}},
 	}
+	now := time.Now()
 	err = linuxNodeHandler.NodeAdd(nodev1)
 	c.Assert(err, check.IsNil)
+	// insertNeighbor is invoked async
```
Comment (kkourt) [inline pkg/datapath/linux/node_linux_test.go:1058]: The same comment appears a few lines below. Was this maybe forgotten from an earlier version?

File: pkg/datapath/linux/node_linux_test.go [hunk 2]
```diff
@@ -1026,18 +1027,41 @@ func (s *linuxPrivilegedIPv4OnlyTestSuite) TestArpPingHandling(c *check.C) {
 	})
 	c.Assert(err, check.IsNil)
 
+	wait := func(now time.Time, nodeID nodeTypes.Identity, isDelete bool) {
+		err := testutils.WaitUntil(func() bool {
```
Comment (kkourt) [inline pkg/datapath/linux/node_linux_test.go:1032]: From my reading of the code `now` is a lower bound for when the operation happened.

However, it is used only for insertion and not deletion (since for the latter, we do not have a deletion timestamp to check).
Given this, and the overall structure of the function, I wonder if it would be better to have two versions of this function one for deletes and one for inserts.

I think this would also improve readability on the caller side (at the cost of some code duplication).

Comment (brb) [reply pkg/datapath/linux/node_linux_test.go:1032]: > From my reading of the code now is a lower bound for when the operation happened.

Did s/now/before/. Hope it's more clear.

> However, it is used only for insertion and not deletion

Made `before` as `*time.Time`, so that nil can be passed for the wait for the deletion.

> Given this, and the overall structure of the function, I wonder if it would be better to have two versions of this function one for deletes and one for inserts.

I want this waiting routine to be concise to avoid polluting the test case. Also, to follow DRY principle.

File: pkg/datapath/linux/node_linux_test.go (hunk 1 above)
Comment (brb) [reply pkg/datapath/linux/node_linux_test.go:1058]: Removed redundant comments.

File: pkg/datapath/linux/node_linux_test.go (hunk 2 above)
Comment (kkourt) [reply pkg/datapath/linux/node_linux_test.go:1032]: OK, sounds good.

**Review by kkourt — APPROVED** [review]

**Comment by brb** [comment]
@kkourt Thanks for the review! I pushed one more commit to fix #16075. PTAL.

**Comment by brb** [comment]
test-net-next

**Review by kkourt — APPROVED** [review]
Last patch looks good to me as well.

Out of curiosity, was this triggered because of the small refresh period:
```
option.Config.ARPPingRefreshPeriod = time.Duration(1 * time.Nanosecond)
```

**Comment by brb** [comment]
> Out of curiosity, was this triggered because of the small refresh period:
>
>> option.Config.ARPPingRefreshPeriod = time.Duration(1 * time.Nanosecond)

Noup, I've set such low refresh period to make sure that updates of the periodic goroutines (scheduled in the unit tests) don't return early due to the last ping check.
