### PR TITLE
Remove deadlock from AuthMap Endpoint GC

### LINKED ISSUE #29078: EndpointManager self-deadlocks via AuthMap GC
Observed and investigated: https://github.com/cilium/cilium/actions/runs/6799164465/job/18484995883

`EndpointManager`, when calling `EndpointDeleted` on subscribers, holds a read lock on its `RWMutex`. The AuthMap GC callback calls `GetEndpoints`, which also acquires the read lock of the endpoint manager.

This is a recursive `RLock` call, which can deadlock if another thread of execution calls `Lock` on the manager, as the second `RLock` is blocked by `Lock` (to avoid write starvation), but `Lock` is blocked by the held read lock. The `RWLock` [docs explain this too](https://pkg.go.dev/sync#RWMutex).

The issue was introduced by https://github.com/cilium/cilium/pull/27697 (cc @meyskens).

Stack trace of the recursive `RLock` call:

```
goroutine 3262 [sync.RWMutex.RLock, 4 minutes]:
sync.runtime_SemacquireRWMutexR(0x26?, 0xa8?, 0x41a1e8?)
        /usr/local/go/src/runtime/sema.go:82 +0x25
sync.(*RWMutex).RLock(...)
        /usr/local/go/src/sync/rwmutex.go:71
github.com/cilium/cilium/pkg/endpointmanager.(*endpointManager).GetEndpoints(0xc00122a2d0)
        /go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:589 +0x45
github.com/cilium/cilium/pkg/auth.(*authMapGarbageCollector).cleanupEndpoints(0xc00158fdd0, {0xc000d433b0?, 0xc0015e9048?})
        /go/src/github.com/cilium/cilium/pkg/auth/authmap_gc.go:427 +0x97
github.com/cilium/cilium/pkg/auth.(*authMapGarbageCollector).EndpointDeleted(0xc00158fdd0, 0xc0007ff180?, {0xd8?, 0xd3?})
```

In this case, a call to `RemoveEndpoint` was the interleaved `Lock` call, but it doesn't really matter which it is.

### PR DESCRIPTION
**Pull request by meyskens**
This changes that a create and delete event from the EndpointManager will also give a "state of the world" update of all current endpoints it has.
This allows the subscribers to check against other endpoints without calling a function that issues a lock when the event was send inside an RLock.

This is then used in the AuthMap GC code instead of doing a call that caused a deadlock.

Fixes: https://github.com/cilium/cilium/issues/29078

```release-note
Fix potential deadlock that results in stale authentication entries in Cilium
```

### CODE REVIEW

File: pkg/endpointmanager/subscribe.go [hunk 1]
```diff
@@ -10,12 +10,16 @@ type Subscriber interface {
 	// EndpointCreated is called at the end of endpoint creation.
 	// Implementations must not attempt write operations on the
 	// EndpointManager from this callback.
-	EndpointCreated(ep *endpoint.Endpoint)
+	// epList is the list of all endpoints that exist after the creation of
+	// the new endpoint.
+	EndpointCreated(ep *endpoint.Endpoint, epList []*endpoint.Endpoint)
```
Comment (bimmlerd) [inline pkg/endpointmanager/subscribe.go]: On the one hand a bit concerned with giving out pointers to all the EPs under a read lock, as it's then possible to change these in an unsafe way. On the other hand, that's been possible already, so it's not much worse.

File: pkg/endpointmanager/manager.go [hunk 2]
```diff
@@ -587,11 +587,17 @@ func (mgr *endpointManager) HasGlobalCT() bool {
 // GetEndpoints returns a slice of all endpoints present in endpoint manager.
 func (mgr *endpointManager) GetEndpoints() []*endpoint.Endpoint {
 	mgr.mutex.RLock()
+	defer mgr.mutex.RUnlock()
+	return mgr.getEndpointsLocked()
+}
+
+// getEndpointsLocked returns a slice of all endpoints present in endpoint manager.
+// it should only be called when holding a lock on the endpoint manager.
```
Comment (bimmlerd) [inline pkg/endpointmanager/manager.go]:
```suggestion
// it should only be called when holding the endpoint manager lock.
```

File: pkg/endpointmanager/subscribe.go [hunk 3]
```diff
@@ -10,12 +10,16 @@ type Subscriber interface {
 	// EndpointCreated is called at the end of endpoint creation.
 	// Implementations must not attempt write operations on the
```
Comment (bimmlerd) [inline pkg/endpointmanager/subscribe.go:11]: Could add the caveat of not locking the endpoint manager at all, since this suggests it's OK to do read operations, which it clearly isn't

**Review by bimmlerd — COMMENTED** [review]
couple of suggestions; but yep I believe this fixes the deadlock :+1:

File: pkg/endpointmanager/subscribe.go [hunk 4]
```diff
@@ -10,12 +10,16 @@ type Subscriber interface {
...
+	// the new endpoint.
+	EndpointCreated(ep *endpoint.Endpoint, epList []*endpoint.Endpoint)
 
 	// EndpointDeleted is called at the end of endpoint deletion.
 	// Implementations must not attempt write operations on the
 	// EndpointManager from this callback.
-	EndpointDeleted(ep *endpoint.Endpoint, conf endpoint.DeleteConfig)
+	// epList is the list of all endpoints that exist after the deletion of
+	// the endpoint.
+	EndpointDeleted(ep *endpoint.Endpoint, conf endpoint.DeleteConfig, epList []*endpoint.Endpoint)
```
Comment (christarazi) [inline pkg/endpointmanager/subscribe.go]: It seems like a bit of an abuse of this interface to bolt on `epList` when most subscribers are not going to use it. I wonder if instead of making this change to the interface and having to fetch the list of endpoints from the endpointmanager via `getEndpointsLocked`, we could build up a local cache of endpoints within the auth gc code. Upon initialization of auth gc, it can be initialized with the current list of endpoints from endpointmanager and then auth gc subscribes to `EndpointCreate` to further populate its local cache. Then that local cache can be used instead of reaching back out to the endpointmanager.

**Comment by christarazi** [comment]
For the release note, typically we'd want to describe the impact of the bug on the user, rather than a description of what the bug is. For example, we'd want to say something like "Fix potential deadlock that results in stale authentication entries in Cilium".

**Review by christarazi — APPROVED** [review]

File: pkg/auth/authmap_gc.go [hunk 5]
```diff
@@ -39,7 +39,10 @@ type authMapGarbageCollector struct {
 	ciliumIdentitiesSynced     bool
 	ciliumIdentitiesDeleted    map[identity.NumericIdentity]struct{}
 
-	endpointRepo endpointRepository
+	endpointRepo         endpointRepository
```
Comment (mhofstetter) [inline pkg/auth/authmap_gc.go]: `endpointRepo` is no longer used -> delete field and parameter in "constructor"

File: pkg/auth/authmap_gc.go [hunk 6]
```diff
@@ -405,30 +408,46 @@ func (r *authMapGarbageCollector) cleanupExpiredEntries(_ context.Context) error
...
+	r.endpointsCache[ep.GetID16()] = ep
+	r.endpointsCacheMutex.Unlock()
 }
 
 func (r *authMapGarbageCollector) EndpointDeleted(ep *endpoint.Endpoint, conf endpoint.DeleteConfig) {
+	r.endpointsCacheMutex.Lock()
+	delete(r.endpointsCache, ep.GetID16())
+	r.endpointsCacheMutex.Unlock()
+
 	// when an endpoint got removed clean the authmap entries
```
Comment (mhofstetter) [inline pkg/auth/authmap_gc.go:426]: Why do we cleanup endpoints immediately after receiving the deletion event? the rest of the authmap garbage collector  works the way that all events are captured first - and the actual GC execution removes them. 

The reason why I'm asking is because this also includes proper reporting of the error back to the timer-based job of the Hive-framework. Instead, only a warning gets logged here.

IMO we should fix and align this - even though this might be out of scope for this PR because it's not related to the actual issue and has been introduced with the EP garbage collection.

But i'd like to see this in a follow up PR if possible.

File: pkg/auth/authmap_gc.go [hunk 7]
```diff
@@ -39,7 +39,10 @@ type authMapGarbageCollector struct {
 	ciliumIdentitiesSynced     bool
 	ciliumIdentitiesDeleted    map[identity.NumericIdentity]struct{}
 
-	endpointRepo endpointRepository
+	endpointRepo         endpointRepository
+	endpointsCache       map[uint16]*endpoint.Endpoint
```
Comment (mhofstetter) [inline pkg/auth/authmap_gc.go:42]: We could improve this by only keeping the relevant information in the cache.

Instead of the whole Endpoint we should only keep its SecurityIdentity as value of this map. WDYT?

This way we preprocess the relevant data in the event handler instead of the GC execution itself.

**Review by mhofstetter — COMMENTED** [review]
Nice. Glad we ended up no longer having a dependency on the endpointrepo from the authmap cache at all. :pray: 

Only some non-blocking suggestions that i like to discuss.

File: pkg/auth/authmap_gc.go (hunk 7 above)
Comment (bimmlerd) [reply pkg/auth/authmap_gc.go:42]: > Instead of the whole Endpoint we should only keep its SecurityIdentity as value of this map. WDYT?

I'm not sure whether the SecurityIdentity of an EP can change during it's lifetime. If so, that could break stuff if we only keep the ID instead of the full EP reference, I think?

File: pkg/auth/authmap_gc.go [hunk 8]
```diff
@@ -405,30 +408,46 @@ func (r *authMapGarbageCollector) cleanupExpiredEntries(_ context.Context) error
 
 func (r *authMapGarbageCollector) subscribeToEndpointEvents(endpointManager endpointmanager.EndpointManager) {
 	endpointManager.Subscribe(r)
```
Comment (bimmlerd) [inline pkg/auth/authmap_gc.go]: Could move the `Subscribe` call into the below critical section unless I'm missing a reason not to. Subscribing before it allows events to come in prior to acquiring the snapshot, and that feels a bit racy (though I can't see an actual bug).

**Review by bimmlerd — APPROVED** [review]
Also solves the deadlock as far as I can tell :+1:

File: pkg/auth/authmap_gc.go (hunk 7 above)
Comment (mhofstetter) [reply pkg/auth/authmap_gc.go:42]: Good point. Would be great to know anyway - definitely worth a comment if this is the case. Maybe @christarazi can clarify this?

This is a good additional reason to keep the data kept in the GarbageCollector as little as possible - to get rid of these potential side-effects.

File: pkg/auth/authmap_gc.go (hunk 5 above)
Comment (meyskens) [reply pkg/auth/authmap_gc.go]: good catch!

File: pkg/auth/authmap_gc.go (hunk 6 above)
Comment (meyskens) [reply pkg/auth/authmap_gc.go:426]: The reason for this is that this change was done in hardening against possible attacks of stale entries in the auth map. Acting on deletion event itself would close the time gap where this is possible.

The error handling aspect of this might be a good follow up, feel free to file an issue for it happy to look into it

File: pkg/auth/authmap_gc.go (hunk 7 above)
Comment (meyskens) [reply pkg/auth/authmap_gc.go:42]: this would need some kind of "reference counting" and i am indeed not sure on security IDs changing, they can as we deal with pointers. In the first attempt of this i did something similar and got out of sync issues because of it, though i deleted all that code so couldn't tell exactly what i did.

Comment (mhofstetter) [reply pkg/auth/authmap_gc.go:42]: > this would need some kind of "reference counting"

_Assuming_ that the ep -> security id is stable: Why should it be necessary to count the references?

In the cleanup, it's only necessary to to get all security ids that are in use -> collecting & merging all values from the map `map[uint16]*identity.Identity` (ep -> SID) (therefore the reason to keep it as map and not keeping it "flatten" as the used security ids)

Comment (christarazi) [reply pkg/auth/authmap_gc.go:42]: Endpoint security identities can certainly change. The most common way is when the user modifies the labels for the underlying pod. So I think keeping a cache of live references allows fetching the most up to date security identity.

Comment (mhofstetter) [reply pkg/auth/authmap_gc.go:42]: Thanks for the info! Interesting that there's no "EndpointChanged/Updated" function on the subscriber interface.

**Review by mhofstetter — APPROVED** [review]
Good to go from my side! Thanks @meyskens

File: pkg/endpointmanager/subscribe.go [hunk 9]
```diff
@@ -10,11 +10,15 @@ type Subscriber interface {
 	// EndpointCreated is called at the end of endpoint creation.
 	// Implementations must not attempt write operations on the
 	// EndpointManager from this callback.
+	// This function is being called inside a RLock, so it must not attempt
```
Comment (aditighag) [inline pkg/endpointmanager/subscribe.go:13]: just an fyi: We typically follow the convention - `EndpointCreatedLocked`.

**Review by aditighag — APPROVED** [review]

**Comment by brb** [comment]
@aanm Could we merge this PR? I've just tried running it with the latest `main` - https://github.com/cilium/cilium/pull/29658. The failing `ci-l4lb` is resolved.
