### PR TITLE
pkg/dial/resolver: Fix KVStore service resolution on initialisation

### LINKED ISSUE #44527: Cilium 1.19 in kvstore identity mode fails when etcd is exposed behind a service
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.19.1 and lower than v1.20.0

### What happened?

In a cluster (cluster_A) in KVStore identity-allocation-mode we connect the Cilium agent to an etcd running on a different cluster (cluster_B). The FQDN for the etcd in cluster_B is something like `etcd.cluster_A_k8s.svc.cluster_B_fqdn`. On cluster_A, the Cilium agents try to connect to the etc in cluster_B during initialization but get stuck when trying to resolve the FQDN of the etcd endpoint.

We have narrowed down the deadlock to this for loop in the new `lbServiceResolver` `resolve` function
https://github.com/cilium/cilium/blob/cc9cd28cc5f0a3445ff8a07d97a5f4e61794ed32/pkg/dial/resolver.go#L157-L170 introduced in PR #42440.

It seems the initialization never happens as this etcd connection occurs too early on within the startup of the agent. One way we have found to fix this issue is to add a deadline to the loop function and fallback to returning the host. It then gets picked up by the host's DNS resolver and gets resolved properly. Ideally, this logic should not be used for resolving etcd host.

### How can we reproduce the issue?

This can be reproduced by setting up Cilium with `identity-allocation-mode: kvstore` and `kvstore: etcd`. The etcd endpoint can be in the format `etcd.namespace.svc.<cluster_fqdn>`.

### Cilium Version

v1.19.1

### Kernel Version

Linux 6.8.0-1044-aws #46~22.04.1-Ubuntu SMP Tue Dec  2 18:01:57 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes Version

v1.34.3

### Regression

v1.18.7

### Sysdump

_No response_

### Relevant log output

```shell
"2026-02-25T12:41:18.161Z","cluster-cni","Establishing connection to kvstore"
"2026-02-25T12:41:18.161Z","cluster-cni","Creating etcd client"
"2026-02-25T12:41:18.162Z","cluster-cni","Connecting to etcd server..."
"2026-02-25T12:41:18.794Z","cluster-cni","Error while getting Cilium status"
"2026-02-25T12:41:24.797Z","cluster-cni","Error while getting Cilium status"
"2026-02-25T12:41:32.798Z","cluster-cni","Error while getting Cilium status"
"2026-02-25T12:41:39.794Z","cluster-cni","Error while getting Cilium status"
```

### Anything else?

_No response_

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by 41ks**
This fixes a bug where the agent fails to initialize as it reaches a deadlock when trying to resolve the address of the KVStore if it is behind a K8s Service. The fix adds a clear dependency in the resolver on the K8s reflectors to force correct initialisation order.

Fixes: #44527

```release-note
Fixes issue where the Cilium agent fails to initialise when using KVStore identity mode with etcd behind a K8s Service
```

### CODE REVIEW

**Comment by 41ks** [comment]
Hey @joamaki, I took a go at implementing your suggestion for a fix for this issue and this seems to work. Let me know if this is what you had in mind.

**Review by joamaki — APPROVED** [review]

**Comment by joamaki** [comment]
Bunch of privileged tests are failing:
```
    logger.go:256: time=2026-03-06T14:57:30.200Z level=ERROR source=/host/vendor/github.com/cilium/hive/cell/invoke.go:52 msg="Invoke failed" error="missing type:\n\t- reflectors.K8sReflectorRegistered (did you mean to Provide it?)" function="clustermesh.registerServicesInitialized (pkg/clustermesh/service_merger.go:44)"
    cell_test.go:300: 
        	Error Trace:	/host/pkg/datapath/linux/ipsec/cell_test.go:300
        	            				/host/pkg/netns/netns_linux.go:175
        	            				/host/vendor/golang.org/x/sync/errgroup/errgroup.go:93
        	            				/root/sdk/go1.26.0/src/runtime/asm_amd64.s:1771
        	Error:      	Received unexpected error:
        	            	failed to populate object graph: missing type: reflectors.K8sReflectorRegistered
        	Test:       	TestPrivileged_TestIPSecCell/IPSecDisabled
--- FAIL: TestPrivileged_TestIPSecCell/IPSecDisabled (0.01s)
--- FAIL: TestPrivileged_TestIPSecCell (0.04s)
```

https://github.com/cilium/cilium/actions/runs/22767890933/job/66040826515

**Comment by 41ks** [comment]
Hey @joamaki, thank you for the review ! I think I need to tweak the privileged tests to provide the `reflectors.K8sReflectorRegistered` type or the cell altogether.

**Comment by 41ks** [comment]
@joamaki @giorio94 let me know if the new changes to the resolver look good to you.

**Review by heathermomof2 — APPROVED** [review]

**Review by rgo3 — APPROVED** [review]

File: pkg/dial/resolver.go [hunk 1]
```diff
@@ -131,7 +131,7 @@ type lbServiceResolver struct {
 	frontends statedb.Table[*loadbalancer.Frontend]
 }
 
-func newLBServiceResolver(jg job.Group, db *statedb.DB, frontends statedb.Table[*loadbalancer.Frontend]) Resolver {
+func newLBServiceResolver(_ reflectors.K8sReflectorRegistered, jg job.Group, db *statedb.DB, frontends statedb.Table[*loadbalancer.Frontend]) Resolver {
```
Comment (giorio94) [inline pkg/dial/resolver.go]: Nit. It would be good to add a comment about the reason for this dependency, otherwise there's a high likelihood it will get unintentionally removed in the future.

File: pkg/dial/resolver.go [hunk 2]
```diff
@@ -164,6 +176,16 @@ func (sr *lbServiceResolver) resolve(ctx context.Context, host string) string {
 			return host
 		case <-waitInit:
 			init = true
+		case <-initTimeout:
```
Comment (giorio94) [inline pkg/dial/resolver.go:183]: If this is intended to only be a circuit breaker to prevent issues in case of possible bugs (as the log being emitted at warning level seems to also imply), I'd suggest to increase the timeout to 5/10 seconds. 1 second seems low enough to me that it may be unnecessarily triggered if bootstrap is slow, and it may cause unnecessary requests to the API server especially for clustermesh (given that it targets the KVStoreMesh service in that case).

File: pkg/dial/resolver.go [hunk 3]
```diff
@@ -164,6 +176,16 @@ func (sr *lbServiceResolver) resolve(ctx context.Context, host string) string {
...
+			sr.log.Warn(
+				"Frontends table not initialized, falling back to kube-apiserver",
+				logfields.K8sNamespace, nsname.Namespace,
+				logfields.K8sSvcName, nsname.Name,
+			)
+			if ip := sr.resolveFromAPIServer(ctx, nsname); ip != "" {
+				return ip
+			}
+			return host
```
Comment (giorio94) [inline pkg/dial/resolver.go]: Nit. `return cmp.Or(sr.resolveFromAPIServer(ctx, nsname), host)` is more concise.

**Review by giorio94 — COMMENTED** [review]
Thanks! The changes look good to me, with only a couple of minor comments inline.

File: pkg/dial/resolver.go (hunk 2 above)
Comment (41ks) [reply pkg/dial/resolver.go:183]: I set it to 5 seconds which should be good enough to not trigger unnecessarily.

**Review by giorio94 — APPROVED** [review]
Thanks!
