### PR TITLE
operator/pkg/lbipam: fix LoadBalancerIPPool conditions update logic

### LINKED ISSUE #41321: cilium-operator fails to update LoadBalancerIPPool conditions
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.18.1 and lower than v1.19.0

### What happened?

There is an issue with the way conditions are set on LB pools:
```
	if ipam.setPoolCondition(pool, ciliumPoolIPsTotalCondition, meta_v1.ConditionUnknown, "noreason", totalCounts.Total.String()) ||
		ipam.setPoolCondition(pool, ciliumPoolIPsAvailableCondition, meta_v1.ConditionUnknown, "noreason", totalCounts.Available.String()) ||
		ipam.setPoolCondition(pool, ciliumPoolIPsUsedCondition, meta_v1.ConditionUnknown, "noreason", strconv.FormatUint(totalCounts.Used, 10)) {
		modifiedPoolStatus = true
	}
```
Short-circuit execution of the condition chain with `||` means that the first condition to return true pre-empts execution of subsequent setPoolCondition() calls.

This surfaces in two different ways:
1. when deleting a service that has an IP allocated, the IPsUsed condition does not decrement
2. when shrinking a LB Pool (removing an IP block from the spec), the IPsAvailable condition does not decrement

### How can we reproduce the issue?

First issue
1. Create LBPool with two /32's
2. Create two services 
3. Delete one service
4. IPsUsed will still be 2

Second issue
1. Create LBPool with two /32's
2. Remove one /32 from the spec
3. IPsAvailable will still be 2

### Cilium Version

1.18.0

### Kernel Version

Darwin Kernel Version 24.5.0

### Kubernetes Version

1.33.0

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell
issue 1 (with 2 active services):
spec:
    blocks:
    - cidr: 10.235.0.18/32
    - cidr: 10.235.0.19/32
    - cidr: 10.235.0.20/32
    - cidr: 10.235.0.21/32
    - cidr: 10.235.0.22/32
    - cidr: 10.235.0.29/32
    - cidr: 10.235.0.30/32
    - cidr: 10.235.0.31/32
    disabled: false
    serviceSelector:
      matchLabels:
        foo: bar
  status:
    conditions:
    - status: "False"
      type: cilium.io/PoolConflict
    - message: "8"
      type: cilium.io/IPsTotal
    - message: "6"
      type: cilium.io/IPsAvailable
    - message: "5"
      type: cilium.io/IPsUsed

issue 2 (with 2 active services)
 spec:
    blocks:
    - cidr: 10.235.0.21/32
    - cidr: 10.235.0.22/32
    - cidr: 10.235.0.29/32
    - cidr: 10.235.0.30/32
    - cidr: 10.235.0.31/32
    disabled: false
    serviceSelector:
      matchLabels:
        foo: bar
  status:
    conditions:
    - status: "False"
      type: cilium.io/PoolConflict
    - message: "5"
      type: cilium.io/IPsTotal
    - message: "6"
      type: cilium.io/IPsAvailable
    - message: "2"
      type: cilium.io/IPsUsed
```

### Anything else?

_No response_

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### LINKED ISSUE #41536: CiliumLoadBalancerIPPool shows blank IPsAvailable on second pool and incorrect number on first pool
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.18.1 and lower than v1.19.0

### What happened?

Two issues I've noticed on deploying a greenfield 1.18.1 instance that was working fine in 1.17.4.

## Issue 1:

When you make a second CiliumLoadBalancerIPPool the `IPsAvailable` is blank, it doesn't seem to matter what the CIDR used is or ordering of creation. The second one always has the issue.

The IPsAvailable then will become visible *after* an Ingress is created, even if that Ingress is annotated to go to a different pool.

Making the first pool:

```
# kubectl get ciliumloadbalancerippool 
No resources found

# cat private.yml 
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "private-vip-pool"
spec:
  blocks:
  - cidr: "10.11.0.0/24"

# kubectl apply -f private.yml 
ciliumloadbalancerippool.cilium.io/private-vip-pool created
# kubectl get ciliumloadbalancerippool 
NAME               DISABLED   CONFLICTING   IPS AVAILABLE   AGE
private-vip-pool   false      False         255             14s
```

So far so good, now we make a second pool:
```
# cat private2.yml
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "private-vip-pool2"
spec:
  blocks:
  - cidr: "10.12.0.0/24"

# kubectl apply -f private2.yml 
ciliumloadbalancerippool.cilium.io/private-vip-pool2 created
# kubectl get ciliumloadbalancerippool 
NAME                DISABLED   CONFLICTING   IPS AVAILABLE   AGE
private-vip-pool    false      False         255             2m58s
private-vip-pool2   false      False                         9s
```

Why is it blank?

```
# kubectl get ciliumloadbalancerippool -o yaml
apiVersion: v1
items:
- apiVersion: cilium.io/v2
  kind: CiliumLoadBalancerIPPool
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cilium.io/v2","kind":"CiliumLoadBalancerIPPool","metadata":{"annotations":{},"name":"private-vip-pool"},"spec":{"blocks":[{"cidr":"10.11.0.0/24"}]}}
    creationTimestamp: "2025-09-05T03:05:15Z"
    generation: 1
    name: private-vip-pool
    resourceVersion: "219568"
    uid: aaaf3efa-1653-4ef1-b9a6-7934fb0a4dcb
  spec:
    blocks:
    - cidr: 10.11.0.0/24
    disabled: false
  status:
    conditions:
    - lastTransitionTime: "2025-09-05T03:05:15Z"
      message: ""
      observedGeneration: 1
      reason: resolved
      status: "False"
      type: cilium.io/PoolConflict
    - lastTransitionTime: "2025-09-05T03:05:15Z"
      message: "256"
      observedGeneration: 1
      reason: noreason
      status: Unknown
      type: cilium.io/IPsTotal
    - lastTransitionTime: "2025-09-05T03:05:15Z"
      message: "255"
      observedGeneration: 1
      reason: noreason
      status: Unknown
      type: cilium.io/IPsAvailable
    - lastTransitionTime: "2025-09-05T03:05:15Z"
      message: "1"
      observedGeneration: 1
      reason: noreason
      status: Unknown
      type: cilium.io/IPsUsed
- apiVersion: cilium.io/v2
  kind: CiliumLoadBalancerIPPool
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cilium.io/v2","kind":"CiliumLoadBalancerIPPool","metadata":{"annotations":{},"name":"private-vip-pool2"},"spec":{"blocks":[{"cidr":"10.12.0.0/24"}]}}
    creationTimestamp: "2025-09-05T03:08:04Z"
    generation: 1
    name: private-vip-pool2
    resourceVersion: "220071"
    uid: 227fd614-2438-446a-a34c-13fc60187dea
  spec:
    blocks:
    - cidr: 10.12.0.0/24
    disabled: false
  status:
    conditions:
    - lastTransitionTime: "2025-09-05T03:08:04Z"
      message: ""
      observedGeneration: 1
      reason: resolved
      status: "False"
      type: cilium.io/PoolConflict
    - lastTransitionTime: "2025-09-05T03:08:05Z"
      message: "256"
      observedGeneration: 1
      reason: noreason
      status: Unknown
      type: cilium.io/IPsTotal
kind: List
metadata:
  resourceVersion: ""
```

It never makes it to a transition of type `cilium.io/IPsAvailable`? Not sure why.

Make a dummy Ingress:
```
# cat reserve.yml 
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-service
  namespace: kube-system
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reserve-shared-vip
  namespace: kube-system
  annotations:
    lbipam.cilium.io/ip-pool: private-vip-pool
    ingress.cilium.io/loadbalancer-mode: shared
spec:
  ingressClassName: cilium
  defaultBackend:
    service:
      name: dummy-service
      port:
        number: 80

# kubectl apply -f reserve.yml 
Warning: spec.SessionAffinity is ignored for headless services
service/dummy-service created
ingress.networking.k8s.io/reserve-shared-vip created
# kubectl get ciliumloadbalancerippool 
NAME                DISABLED   CONFLICTING   IPS AVAILABLE   AGE
private-vip-pool    false      False         255             7m48s
private-vip-pool2   false      False         256             4m59s
```

The column is no longer blank! Even though the `LoadBalancer` was created in `private-vip-pool` (`10.11.0.0/24`)...

```
# kubectl get svc -n kube-system cilium-ingress
NAME             TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
cilium-ingress   LoadBalancer   10.111.75.193   10.11.0.0     80:30556/TCP,443:31994/TCP   18h
```

### Issue 2

From above, you can see when the first pool is created, it says the number of IPs available is 255, then when you create the first Ingress it still says 255. I noticed if you create the pool with /32 CIDR, it says 0 available IPs, then you can create an Ingress and it works and now correctly reflects 0.

### How can we reproduce the issue?

cilium 1.18.1 installed via helm with 
```operator:
  replicas: 3

k8sServiceHost: {{ vip.address }}
k8sServicePort: {{ kubernetes.api_port }}
kubeProxyReplacement: true

ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList:
      - {{ kubernetes.pod_subnet }}
    clusterPoolIPv4MaskSize: 24

nodeinit:
  enabled: true

socketLB:
  hostNamespaceOnly: true

l2announcements:
  enabled: true
externalIPs:
  enabled: true

ingressController:
  enabled: true
  default: true
  loadbalancerMode: dedicated

authentication:
  mutual:
    spire:
      enabled: true
      install:
        enabled: true
        server:
          dataStorage:
            storageClass: ceph-block
            size: 5Gi

encryption:
  enabled: true
  type: wireguard```

### Cilium Version

1.18.1

### Kernel Version

6.8.0-79-generic #79-Ubuntu

### Kubernetes Version

1.34

### Regression

It was working fine in 1.17.4

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by alimehrabikoshki**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

When deleting services that have an IP assigned from a LoadBalancerIPPool, the cilium.io/IPsUsed condition is not decremented properly. This commit adds a test for this behaviour. Additionally, when shrinking an IP pool, the IPsAvailable condition is not decremented properly. Both issues have the same root cause of setPoolCondition() being chained with ||, leading to short-circuit execution of only the conditions up to the first "true" return.

Fixes: #41321 
Fixes: #41536

```release-note
operator/pkg/lbipam: fix LoadBalancerIPPool conditions update logic
```

### CODE REVIEW

File: operator/pkg/lbipam/lbipam_test.go [hunk 1]
```diff
@@ -2853,3 +2861,69 @@ func TestLBIPAMRestartOnFullPool(t *testing.T) {
...
+	}
+
+	poolA = fixture.GetPool("pool-a")
+	poolA.Spec.Blocks = []cilium_api_v2.CiliumLoadBalancerIPPoolIPBlock{
+		{Cidr: cilium_api_v2.IPv4orIPv6CIDR(blockToKeep)},
+	}
+	fixture.UpsertPool(t, poolA)
+
+	p = fixture.GetPool("pool-a")
+	require.Equal(t, "256", getPoolStatusCount(p, ciliumPoolIPsTotalCondition), "IPsTotal should be 254")
```
Comment (aspsk) [inline operator/pkg/lbipam/lbipam_test.go]: Why 254 (and 253 in the corresponding place on the line below)?

**Review by aspsk — COMMENTED** [review]
LGTM, just left one small question in the test.

(Also, please format the commit message in a paragraph, not a single huge line.)

File: operator/pkg/lbipam/lbipam_test.go (hunk 1 above)
Comment (alimehrabikoshki) [reply operator/pkg/lbipam/lbipam_test.go]: good catch, fixed. It was a remnant of allowFirstLastIPs confusion.

Also reformatted commit msg.

Comment (alimehrabikoshki) [reply operator/pkg/lbipam/lbipam_test.go]: @aspsk does it look good now?

**Review by aspsk — APPROVED** [review]

**Comment by dylandreimerink** [comment]
I seems like the ci-ginkgo workflow is very unhappy. Could we rebase this branch on main? That should hopefully resolve it.

**Comment by alimehrabikoshki** [comment]
> I seems like the ci-ginkgo workflow is very unhappy. Could we rebase this branch on main? That should hopefully resolve it.

@dylandreimerink done, thanks.
