### PR TITLE
endpoint: add optional way of propagating context.Context into regeneration

### LINKED ISSUE #7513: CI: K8sIstioTest: JoinEP: Failed to load program: Failed to replace Qdisc ...  Link not found
~~Similar to #6059, which was purportedly fixed by #7203~~, I'm now seeing this failure show up again in Istio bookinfo tests:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11076/testReport/junit/k8s-1/10/K8sIstioTest_Istio_Bookinfo_Demo_Tests_bookinfo_inter_service_connectivity/

### k8s-1.10.K8sIstioTest Istio Bookinfo Demo Tests bookinfo inter-service connectivity

Took 4 min 26 sec.

There is evidence of envoy proxy propagation time taking over one minute, during which presumably Cilium is unable to report back to CNI to report endpoint creation, which causes the link to be deleted, leading to JoinEP failure showing up in the logs and a testsuite failure.

### Conclusion

Need to pre-pull istio images to speed up pod bootstrap: https://github.com/cilium/cilium/issues/7532

#### Stacktrace
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:339
Found a "JoinEP: " in Cilium Logs
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:499
```
#### Standard Output
```
⚠️  Found a "JoinEP: " in logs
Number of "context deadline exceeded" in logs: 0
⚠️  Number of "level=error" in logs: 6
⚠️  Number of "level=warning" in logs: 7
Number of "Cilium API handler panicked" in logs: 0
⚠️  Number of "Goroutine took lock for more than" in logs: 76
Top 5 errors/warnings:
Ignoring error while deleting endpoint
Error parsing IP from key
error while receiving request from xDS stream
xDS stream context canceled
Endpoint cannot be created
Cilium pods: [cilium-f552f cilium-hlqnh]
Netpols loaded: 
CiliumNetworkPolicies loaded: default::cnp-second-namespace default::cnp-specs 
Endpoint Policy Enforcement:
Pod                                         Ingress   Egress
etcd-operator-58cf6d756d-6g5fp              false     false
kube-dns-f4d788bb7-km8jj                    false     false
details-v1-7d4c5d5fdc-tc7dh                 true      false
reviews-v2-6fcb99bfd9-t9nmq                 false     false
istio-citadel-84fb7985bf-vgprl              false     false
istio-policy-5455899b66-dmzhd               false     false
istio-galley-655c4f9ccd-z8lpr               false     false
cilium-etcd-vn6q7vnjjf                      false     false
prometheus-84bd4b9796-j9gd7                 false     false
cilium-etcd-jjrrjgk5dp                      false     false
ratings-v1-768bd6cc4c-2pxbr                 true      false
reviews-v1-6dff9b69d7-wbx9b                 false     false
istio-pilot-755ff66c74-j7fjr                false     false
istio-telemetry-584c9ff7f5-qrnv2            false     false
cilium-operator-5fb956fc65-499fp            false     false
istio-egressgateway-86f49899c9-bvq76        false     false
istio-ingressgateway-8695db5498-dtkm4       false     false
istio-statsd-prom-bridge-7f44bb5ddb-2r4fw   false     false
cilium-etcd-fw6gfccvdx                      false     false
Cilium agent 'cilium-f552f': Status: Ok  Health: Ok Nodes "k8s1 k8s2" ContinerRuntime: Ok Kubernetes: Ok KVstore: Ok Controllers: Total 50 Failed 0
Cilium agent 'cilium-hlqnh': Status: Ok  Health: Ok Nodes "k8s2 k8s1" ContinerRuntime: Ok Kubernetes: Ok KVstore: Ok Controllers: Total 76 Failed 0

Standard Error
STEP: Installing DNS Deployment
STEP: Deploying etcd-operator
STEP: Installing Cilium
STEP: Installing Cilium-Operator
STEP: Waiting for all etcd-operator pods are ready
STEP: Performing Cilium preflight check
STEP: Creating the istio-system namespace
STEP: Creating the Istio resources
STEP: Waiting for Istio pods to be ready
STEP: Waiting for Istio service "istio-statsd-prom-bridge" to be ready
STEP: Waiting for Istio service "istio-pilot" to be ready
STEP: Waiting for DNS to resolve Istio service "istio-statsd-prom-bridge"
STEP: Waiting for DNS to resolve Istio service "istio-pilot"
STEP: Creating policy in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/cnp-specs.yaml"
STEP: Creating resources in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/bookinfo-v2-istio.yaml"
STEP: Creating resources in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/bookinfo-v1-istio.yaml"
STEP: Waiting for Bookinfo pods to be ready
STEP: Waiting for Bookinfo endpoints to be ready
STEP: Waiting for Bookinfo service "details" to be ready
STEP: Waiting for Bookinfo service "ratings" to be ready
STEP: Waiting for Bookinfo service "reviews" to be ready
STEP: Waiting for Bookinfo service "productpage" to be ready
STEP: Waiting for DNS to resolve Bookinfo service "productpage"
STEP: Waiting for DNS to resolve Bookinfo service "reviews"
STEP: Waiting for DNS to resolve Bookinfo service "ratings"
STEP: Waiting for DNS to resolve Bookinfo service "details"
STEP: Testing L7 filtering
STEP: Checking that "reviews-v1-6dff9b69d7-wbx9b" can connect to "ratings.default.svc.cluster.local:9080/health"
STEP: Checking that "reviews-v1-6dff9b69d7-wbx9b" cannot connect to "ratings.default.svc.cluster.local:9080/ratings/0"
STEP: Checking that "productpage-v1-5f9d4dcd9c-l2k9z" can connect to "details.default.svc.cluster.local:9080/health"
STEP: Checking that "productpage-v1-5f9d4dcd9c-l2k9z" cannot connect to "ratings.default.svc.cluster.local:9080/health"
STEP: Checking that "productpage-v1-5f9d4dcd9c-l2k9z" cannot connect to "ratings.default.svc.cluster.local:9080/ratings/0"
=== Test Finished at 2019-03-26T18:46:49Z====
===================== TEST FAILED =====================
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE      NAME                                        READY     STATUS      RESTARTS   AGE       IP              NODE
	 default        details-v1-7d4c5d5fdc-tc7dh                 2/2       Running     0          1m        10.10.1.124     k8s2
	 default        productpage-v1-5f9d4dcd9c-l2k9z             2/2       Running     0          1m        10.10.1.86      k8s2
	 default        ratings-v1-768bd6cc4c-2pxbr                 2/2       Running     0          1m        10.10.1.141     k8s2
	 default        reviews-v1-6dff9b69d7-wbx9b                 2/2       Running     0          1m        10.10.0.168     k8s1
	 default        reviews-v2-6fcb99bfd9-t9nmq                 2/2       Running     0          1m        10.10.1.206     k8s2
	 istio-system   istio-citadel-84fb7985bf-vgprl              1/1       Running     0          2m        10.10.1.94      k8s2
	 istio-system   istio-cleanup-secrets-gkjt2                 0/1       Completed   0          2m        10.10.1.52      k8s2
	 istio-system   istio-egressgateway-86f49899c9-bvq76        1/1       Running     0          2m        10.10.0.67      k8s1
	 istio-system   istio-galley-655c4f9ccd-z8lpr               1/1       Running     0          2m        10.10.0.84      k8s1
	 istio-system   istio-ingressgateway-8695db5498-dtkm4       1/1       Running     0          2m        10.10.1.77      k8s2
	 istio-system   istio-pilot-755ff66c74-j7fjr                2/2       Running     0          2m        10.10.0.122     k8s1
	 istio-system   istio-policy-5455899b66-dmzhd               2/2       Running     0          2m        10.10.0.157     k8s1
	 istio-system   istio-security-post-install-wfhkx           0/1       Completed   0          2m        10.10.1.241     k8s2
	 istio-system   istio-statsd-prom-bridge-7f44bb5ddb-2r4fw   1/1       Running     0          2m        10.10.0.236     k8s1
	 istio-system   istio-telemetry-584c9ff7f5-qrnv2            2/2       Running     0          2m        10.10.1.111     k8s2
	 istio-system   prometheus-84bd4b9796-j9gd7                 1/1       Running     0          2m        10.10.1.201     k8s2
	 kube-system    cilium-etcd-fw6gfccvdx                      1/1       Running     0          19m       10.10.1.211     k8s2
	 kube-system    cilium-etcd-jjrrjgk5dp                      1/1       Running     0          19m       10.10.0.198     k8s1
	 kube-system    cilium-etcd-operator-6f5cf78d9c-gdpqn       1/1       Running     0          20m       192.168.36.11   k8s1
	 kube-system    cilium-etcd-vn6q7vnjjf                      1/1       Running     0          18m       10.10.1.153     k8s2
	 kube-system    cilium-f552f                                1/1       Running     0          12m       192.168.36.11   k8s1
	 kube-system    cilium-hlqnh                                1/1       Running     0          12m       192.168.36.12   k8s2
	 kube-system    cilium-operator-5fb956fc65-499fp            1/1       Running     0          14m       10.10.1.212     k8s2
	 kube-system    etcd-k8s1                                   1/1       Running     0          27m       192.168.36.11   k8s1
	 kube-system    etcd-operator-58cf6d756d-6g5fp              1/1       Running     0          20m       10.10.1.96      k8s2
	 kube-system    kube-apiserver-k8s1                         1/1       Running     0          27m       192.168.36.11   k8s1
	 kube-system    kube-controller-manager-k8s1                1/1       Running     0          27m       192.168.36.11   k8s1
	 kube-system    kube-dns-f4d788bb7-km8jj                    3/3       Running     0          28m       10.10.1.237     k8s2
	 kube-system    kube-proxy-6txdj                            1/1       Running     0          21m       192.168.36.12   k8s2
	 kube-system    kube-proxy-qpgvj                            1/1       Running     0          28m       192.168.36.11   k8s1
	 kube-system    kube-scheduler-k8s1                         1/1       Running     0          27m       192.168.36.11   k8s1
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-f552f -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                                   IPv6                 IPv4          STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                                                   
	 318        Disabled           Disabled          2703       k8s:io.cilium.k8s.policy.cluster=default                                      f00d::a0a:0:0:3d8a   10.10.0.84    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=istio-galley-service-account                                                     
	                                                            k8s:io.kubernetes.pod.namespace=istio-system                                                                             
	                                                            k8s:istio=galley                                                                                                         
	 864        Disabled           Disabled          101        k8s:app=etcd                                                                  f00d::a0a:0:0:1721   10.10.0.198   ready   
	                                                            k8s:etcd_cluster=cilium-etcd                                                                                             
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                 
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                          
	                                                            k8s:io.cilium/app=etcd-operator                                                                                          
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                                              
	 1099       Disabled           Disabled          53362      k8s:app=pilot                                                                 f00d::a0a:0:0:8594   10.10.0.122   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                 
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=istio-pilot-service-account                                                      
	                                                            k8s:io.kubernetes.pod.namespace=istio-system                                                                             
	                                                            k8s:istio=pilot                                                                                                          
	 1682       Disabled           Disabled          4          reserved:health                                                               f00d::a0a:0:0:a010   10.10.0.101   ready   
	 2475       Disabled           Disabled          39558      k8s:app=istio-egressgateway                                                   f00d::a0a:0:0:b84    10.10.0.67    ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                 
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=istio-egressgateway-service-account                                              
	                                                            k8s:io.kubernetes.pod.namespace=istio-system                                                                             
	                                                            k8s:istio=egressgateway                                                                                                  
	 3134       Disabled           Disabled          14287      k8s:app=policy                                                                f00d::a0a:0:0:fb38   10.10.0.157   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                 
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=istio-mixer-service-account                                                      
	                                                            k8s:io.kubernetes.pod.namespace=istio-system                                                                             
	                                                            k8s:istio-mixer-type=policy                                                                                              
	                                                            k8s:istio=mixer                                                                                                          
	 3444       Disabled           Disabled          20971      k8s:app=reviews                                                               f00d::a0a:0:0:843b   10.10.0.168   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                 
	                                                            k8s:io.cilium.k8s.policy.istiosidecarproxy=true                                                                          
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                          
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                                  
	                                                            k8s:track=stable                                                                                                         
	                                                            k8s:version=v1                                                                                                           
	                                                            k8s:zgroup=bookinfo                                                                                                      
	 3668       Disabled           Disabled          1318       k8s:io.cilium.k8s.policy.cluster=default                                      f00d::a0a:0:0:5f6e   10.10.0.236   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=istio-mixer-service-account                                                      
	                                                            k8s:io.kubernetes.pod.namespace=istio-system                                                                             
	                                                            k8s:istio=statsd-prom-bridge                                                                                             
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-f552f -- cilium bpf proxy list
Exitcode: 0 
Stdout:
 	 KEY                               VALUE                                         
	 10.10.0.235:43013 (17) => 46013   10.10.1.237:53 identity 52391 lifetime 1908   
	 10.10.0.131:33571 (17) => 46013   10.10.1.237:53 identity 28557 lifetime 1913   
	 10.10.0.235:57862 (17) => 46013   10.10.1.237:53 identity 52391 lifetime 1895   
	 10.10.0.131:37554 (17) => 46013   10.10.1.237:53 identity 28557 lifetime 1913   
	 10.10.0.131:59822 (17) => 46013   10.10.1.237:53 identity 28557 lifetime 1913   
	 10.10.0.235:47972 (17) => 46013   10.10.1.237:53 identity 52391 lifetime 1895   
	 10.10.0.235:44700 (17) => 46013   10.10.1.237:53 identity 52391 lifetime 1895   
	 10.10.0.235:50493 (17) => 46013   10.10.1.237:53 identity 52391 lifetime 1908   
	 10.10.0.131:55803 (17) => 46013   10.10.1.237:53 identity 28557 lifetime 1913   
	 10.10.0.235:48095 (17) => 46013   10.10.1.237:53 identity 52391 lifetime 1908   
	 10.10.0.131:33931 (17) => 46013   10.10.1.237:53 identity 28557 lifetime 1913   
	 10.10.0.235:48591 (17) => 46013   10.10.1.237:53 identity 52391 lifetime 1907   
	 10.10.0.235:48473 (17) => 46013   10.10.1.237:53 identity 52391 lifetime 1895   
	 10.10.0.213:45560 (6) => 18265    10.10.0.243:80 identity 52391 lifetime 2392   
	 10.10.0.235:32877 (17) => 46013   10.10.1.237:53 identity 52391 lifetime 1907   
	 10.10.0.235:49082 (17) => 46013   10.10.1.237:53 identity 52391 lifetime 1907   
	 10.10.0.235:32777 (17) => 46013   10.10.1.237:53 identity 52391 lifetime 1895   
	 10.10.0.235:46148 (17) => 46013   10.10.1.237:53 identity 52391 lifetime 1908   
	 10.10.0.235:46288 (17) => 46013   10.10.1.237:53 identity 52391 lifetime 1907   
	 10.10.0.131:42356 (17) => 46013   10.10.1.237:53 identity 28557 lifetime 1913   
	 10.10.0.235:52551 (17) => 46013   10.10.1.237:53 identity 52391 lifetime 1895   
	 10.10.0.235:54011 (17) => 46013   10.10.1.237:53 identity 52391 lifetime 1895   
	 10.10.0.235:53316 (17) => 46013   10.10.1.237:53 identity 52391 lifetime 1895   
	 10.10.0.131:58047 (17) => 46013   10.10.1.237:53 identity 28557 lifetime 1913   
	 10.10.0.131:55356 (17) => 46013   10.10.1.237:53 identity 28557 lifetime 1913   
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-hlqnh -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                                    IPv6                   IPv4          STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                                                      
	 75         Disabled           Disabled          63668      k8s:app=prometheus                                                             f00d::a0a:100:0:35a6   10.10.1.201   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                    
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=prometheus                                                                          
	                                                            k8s:io.kubernetes.pod.namespace=istio-system                                                                                
	 180        Disabled           Disabled          100        k8s:io.cilium.k8s.policy.cluster=default                                       f00d::a0a:100:0:9bff   10.10.1.96    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=cilium-etcd-sa                                                                      
	                                                            k8s:io.cilium/app=etcd-operator                                                                                             
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                                                 
	 779        Disabled           Disabled          19438      k8s:io.cilium.k8s.policy.cluster=default                                       f00d::a0a:100:0:e241   10.10.1.94    ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=istio-citadel-service-account                                                       
	                                                            k8s:io.kubernetes.pod.namespace=istio-system                                                                                
	                                                            k8s:istio=citadel                                                                                                           
	 814        Enabled            Disabled          40826      k8s:app=details                                                                f00d::a0a:100:0:65bb   10.10.1.124   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                    
	                                                            k8s:io.cilium.k8s.policy.istiosidecarproxy=true                                                                             
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                             
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                                     
	                                                            k8s:track=stable                                                                                                            
	                                                            k8s:version=v1                                                                                                              
	                                                            k8s:zgroup=bookinfo                                                                                                         
	 1076       Disabled           Disabled          101        k8s:app=etcd                                                                   f00d::a0a:100:0:9fc4   10.10.1.153   ready   
	                                                            k8s:etcd_cluster=cilium-etcd                                                                                                
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                    
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                             
	                                                            k8s:io.cilium/app=etcd-operator                                                                                             
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                                                 
	 1248       Disabled           Disabled          6794       k8s:app=productpage                                                            f00d::a0a:100:0:6fe6   10.10.1.86    ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                    
	                                                            k8s:io.cilium.k8s.policy.istiosidecarproxy=true                                                                             
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                             
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                                     
	                                                            k8s:track=stable                                                                                                            
	                                                            k8s:version=v1                                                                                                              
	                                                            k8s:zgroup=bookinfo                                                                                                         
	 1456       Disabled           Disabled          101        k8s:app=etcd                                                                   f00d::a0a:100:0:eb93   10.10.1.211   ready   
	                                                            k8s:etcd_cluster=cilium-etcd                                                                                                
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                    
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                             
	                                                            k8s:io.cilium/app=etcd-operator                                                                                             
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                                                 
	 1515       Disabled           Disabled          20313      k8s:app=istio-ingressgateway                                                   f00d::a0a:100:0:f1e    10.10.1.77    ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                    
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=istio-ingressgateway-service-account                                                
	                                                            k8s:io.kubernetes.pod.namespace=istio-system                                                                                
	                                                            k8s:istio=ingressgateway                                                                                                    
	 1904       Disabled           Disabled          6695       k8s:app=reviews                                                                f00d::a0a:100:0:12a4   10.10.1.206   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                    
	                                                            k8s:io.cilium.k8s.policy.istiosidecarproxy=true                                                                             
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                             
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                                     
	                                                            k8s:version=v2                                                                                                              
	                                                            k8s:zgroup=bookinfo                                                                                                         
	 2184       Disabled           Disabled          30563      k8s:app=telemetry                                                              f00d::a0a:100:0:41ad   10.10.1.111   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                    
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=istio-mixer-service-account                                                         
	                                                            k8s:io.kubernetes.pod.namespace=istio-system                                                                                
	                                                            k8s:istio-mixer-type=telemetry                                                                                              
	                                                            k8s:istio=mixer                                                                                                             
	 2384       Disabled           Disabled          105        k8s:io.cilium.k8s.policy.cluster=default                                       f00d::a0a:100:0:d0a3   10.10.1.212   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=cilium-operator                                                                     
	                                                            k8s:io.cilium/app=operator                                                                                                  
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                                                 
	                                                            k8s:name=cilium-operator                                                                                                    
	 2465       Disabled           Disabled          4          reserved:health                                                                f00d::a0a:100:0:9b15   10.10.1.229   ready   
	 3072       Disabled           Disabled          102        k8s:io.cilium.k8s.policy.cluster=default                                       f00d::a0a:100:0:7211   10.10.1.237   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=kube-dns                                                                            
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                                                 
	                                                            k8s:k8s-app=kube-dns                                                                                                        
	 3496       Enabled            Disabled          34382      k8s:app=ratings                                                                f00d::a0a:100:0:4074   10.10.1.141   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                    
	                                                            k8s:io.cilium.k8s.policy.istiosidecarproxy=true                                                                             
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                             
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                                     
	                                                            k8s:version=v1                                                                                                              
	                                                            k8s:zgroup=bookinfo                                                                                                         
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-hlqnh -- cilium bpf proxy list
Exitcode: 0 
Stdout:
 	 KEY   VALUE   
	 
Stderr:
 	 

===================== Existing AfterFailed =====================
STEP: Deleting resource in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/bookinfo-v2-istio.yaml"
STEP: Deleting resource in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/bookinfo-v1-istio.yaml"
STEP: Deleting policy in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/cnp-specs.yaml"

STEP: Deleting the Istio resources
STEP: Deleting the istio-system namespace
```

[test_results_Cilium-PR-Ginkgo-Tests-Validated_11076_BDD-Test-PR.zip](https://github.com/cilium/cilium/files/3010008/test_results_Cilium-PR-Ginkgo-Tests-Validated_11076_BDD-Test-PR.zip)

### PR DESCRIPTION
**Pull request by ianvernon**
All API calls made to the cilium-agent from clients are passed a `context.Context`, which is canceled whenever an API request times out.

When the Cilium CNI plugin is invoked, it performs an API call to the cilium-agent after creating the network device, links, etc. for the pod. This request goes into the `createEndpoint` function. This function initializes an endpoint with the information provided in the API request, and regenerates the endpoint. This includes compiling the program for the endpoint, and interacting with the network device, links, etc. for the pod. If this API request times out, the Cilium CNI plugin will immediately delete the endpoint and all associated network devices, links, etc. for the pod. 

Before this change, the cilium-agent did not stop regeneration if the API request timed out. As a result, the CNI plugin would delete the interfaces for the pod / endpoint while the regeneration was still ongoing. This would cause the datapath / loader interactions to fail for the endpoint, as the devices would no longer exist. This has caused a strain on our CI, as when such interactions with the datapath fail, the datapath packges log an error with the string `JoinEP`, which is searched for in the logs, and fails the CI if found ( https://github.com/cilium/cilium/issues/7513 ). 

To avoid such problems, Cilium needs to be able to know when the context passed in via the API request was canceled. This PR enhances the endpoint regeneration framework to be able to contain a context passed down in the regeneration request types. This context is only populated with the context provided to `createEndpoint` at this time. This context is used as a parent context for the proxy configuration Completion context, as well as the context passed due to the datapath / loader packages. If the context is canceled, we will return the error that the context itself was canceled instead of having `JoinEP` errors in the logs, which will fail the CI. The endpoint regeneration will then fail. This is OK, because it is assumed that the endpoint will be deleted if the context associated with `createEndpoint` is canceled. 

Another nice part of adding context to the endpoint regeneration request, is that this can be passed into the function which acquires the build semaphore for regenerations. If the context is canceled, the semaphore acquisition will be stopped as well. 

Fixes: #7513 

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7600)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
etcd-operator got into a bad state: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11324/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
CI failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11328/

Looks like there were issues connecting to the VM? There are no cilium logs, as attempts to get logs caused errors like 'failed to create session: EOF':

```
STEP: Setting up policy: /home/vagrant/go/src/github.com/cilium/cilium/test/runtime/manifests/Policies-l4-policy.json
time="2019-04-05T04:18:32Z" level=debug msg="running command: sudo cilium policy get -o json | jq '.revision'"
cmd: "cilium monitor -v | ts '[%Y-%m-%d %H:%M:%S]'" exitCode: 0 duration: 1.568000204s
time="2019-04-05T04:18:33Z" level=error msg="Error executing command 'sudo cilium policy get -o json | jq '.revision''" error="wait: remote command exited without exit status or exit signal"
time="2019-04-05T04:18:33Z" level=error msg="Error executing command 'sudo cilium policy get -o json | jq '.revision''" error="wait: remote command exited without exit status or exit signal"
cmd: "sudo cilium policy get -o json | jq '.revision'" exitCode: 1 duration: 1.166900049s stdout:
```

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Encryption + vxlan test failed due to cilium-etcd-operator getting into a bad state: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11353/testReport/junit/k8s-1/14/K8sDatapathConfig_Encapsulation_Check_connectivity_with_transparent_encryption_and_VXLAN_encapsulation/

**Comment by ianvernon** [comment]
Connection failed for DNS traffic during restart: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11353/testReport/junit/(root)/runtime/RuntimeChaos_Checking_that_during_restart_no_traffic_is_dropped_using_Egress___Ingress_Traffic/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
etcd-operator issue - https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11359/

not related to this PR, I think this is ready for review.

**Comment by ianvernon** [comment]
test-me-please

File: pkg/endpoint/regenerationcontext.go [hunk 1]
```diff
@@ -53,12 +53,22 @@ func (r DatapathRegenerationLevel) String() string {
 }
 
 func (e *ExternalRegenerationMetadata) toRegenerationContext() *regenerationContext {
+
+	pCtx := e.ParentContext
+	cFunc := e.ParentCancel
+
+	if pCtx == nil {
+		pCtx, cFunc = context.WithCancel(context.Background())
```
Comment (joestringer) [inline pkg/endpoint/regenerationcontext.go]: Whose responsibility is it to call the cancel function here?

According to the golang documentation in the link below, it appears that there's a goroutine associated with each context and we need to call cancel to prevent goroutine leak.

https://golang.org/pkg/context/#WithCancel

File: pkg/datapath/loader/loader.go [hunk 2]
```diff
@@ -66,7 +78,12 @@ func reloadDatapath(ctx context.Context, ep endpoint, dirs *directoryInfo) error
 				logfields.Path: objPath,
 				logfields.Veth: ep.InterfaceName(),
 			})
-			scopedLog.WithError(err).Warn("JoinEP: Failed to load program")
+			switch err {
+			case context.Canceled:
```
Comment (joestringer) [inline pkg/datapath/loader/loader.go]: I'm curious, in `pkg/command/exec/exec.go` we use `context.DeadlineExceeded()` and not `context.Canceled`. I guess that's because typically we've been creating contexts with a timeout and only testing that the timeout condition occurs, whereas now the API could potentially actually invoke the `Cancel()` function first.

I think we need to add this case to `combinedOutput()` in `pkg/command/exec` as well with this PR.

File: pkg/datapath/loader/netlink.go [hunk 3]
```diff
@@ -95,6 +101,12 @@ func replaceDatapath(ctx context.Context, ifName string, objPath string, progSec
 
 // graftDatapath replaces obj in tail call map
 func graftDatapath(ctx context.Context, mapPath, objPath, progSec string) error {
+	select {
+	case <-ctx.Done():
+		return ctx.Err()
```
Comment (joestringer) [inline pkg/datapath/loader/netlink.go]: If we push this stuff into `pkg/command/exec`, then I'm not sure whether there's a big win from putting these bits at the start of each function -- for example in this case it's only a couple of lines above the `exec.CommandContext()` call where we'd do such a check anyway.

File: pkg/endpoint/regenerationcontext.go [hunk 4]
```diff
@@ -110,9 +127,17 @@ type datapathRegenerationContext struct {
...
+func (ctx *datapathRegenerationContext) prepareForProxyUpdates(parentCtx context.Context) {
+	var (
+		completionCtx    context.Context
+		completionCancel context.CancelFunc
+	)
+
+	if parentCtx != nil {
+		completionCtx, completionCancel = context.WithTimeout(parentCtx, EndpointGenerationTimeout)
+	} else {
+		completionCtx, completionCancel = context.WithTimeout(context.Background(), EndpointGenerationTimeout)
```
Comment (joestringer) [inline pkg/endpoint/regenerationcontext.go]: When the context is derived from the parent, I'd imagine that the parent's `Cancel()` results in a `Cancel()` of the child. However, in this background case no-one would call the cancel function.

**Review by joestringer — CHANGES_REQUESTED** [review]
I'm excited about this, as I think the errors from canceling are going to be more intuitive and make more sense in general than the current approach where the datapath isn't at all aware of cancels happening earlier. That said, I have a few questions below.

Primary concern below is about contexts that are never canceled, which causes goroutine leaks. Incidentally, those docs also suggest to never store contexts in a struct type, as this prevents the static analysis tools from pointing out leaks in code: https://golang.org/pkg/context/

On the datapath side I think we could have very similar behaviour by moving the `ctx.Err() == context.Canceled` handling from each datapath replace function down into `combinedOutput()` in `pkg/command/exec`. We wouldn't need to return a different error like we do in the `context.DeadlineExceeded` case, but we **would** need to ensure that in the case `ctx.Err() == context.Canceled`, we actually return `ctx.Err()`, not the `err` from `cmd.CombinedOutput()`. (That's what the code currently does).

Which brings up the difference between `context.Canceled` and `context.DeadlineExceeded`. Seems like we probably need to handle both in a lot of these scenarios? Do you know whether the API handler stuff provides `WithCancel()` contexts or `WithTimeout()` contexts? (A quick grep seems to suggest it's all doing `WithTimeout()`, so `ctx.Err()` would return `context.DeadlineExceeded` which isn't handled in this PR).

How does testing work for this proposal?

File: pkg/endpoint/regenerationcontext.go (hunk 1 above)
Comment (ianvernon) [reply pkg/endpoint/regenerationcontext.go]: Good find, I never knew this. IMO this should be handled in `endpoint.Regenerate` since the endpoint's EventQueue can be drained, and the actual event handling logic may never occur for an endpoint regeneration that was queued up. It thus has to be the queuer's responsibility.

File: pkg/endpoint/regenerationcontext.go (hunk 4 above)
Comment (ianvernon) [reply pkg/endpoint/regenerationcontext.go]: The caller of `prepareForProxyUpdates` calls `defer datapathRegenCtxt.completionCancel()`.

Comment (joestringer) [reply pkg/endpoint/regenerationcontext.go]: Ok yeah. Looks like another potential candidate for doing the context creation in the same layer as the defer to keep management of the context/cancel all in one place.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

File: pkg/endpoint/regenerationcontext.go (hunk 1 above)
Comment (ianvernon) [reply pkg/endpoint/regenerationcontext.go]: Should be fixed now :)

File: pkg/datapath/loader/loader.go (hunk 2 above)
Comment (ianvernon) [reply pkg/datapath/loader/loader.go]: I think I have resolved this!

File: pkg/datapath/loader/netlink.go (hunk 3 above)
Comment (ianvernon) [reply pkg/datapath/loader/netlink.go]: Done! Added additional unit tests in `pkg/command/exec` as well.

**Comment by ianvernon** [comment]
Unit test failure: https://github.com/cilium/cilium/pull/7600/checks?check_run_id=97210627 

Investigating.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11434/

Doesn't appear related.

**Comment by ianvernon** [comment]
test-me-please

File: daemon/daemon.go [hunk 5]
```diff
@@ -275,25 +275,26 @@ func (d *Daemon) QueueEndpointBuild(epID uint64) func() {
 	d.uniqueIDMU.Unlock()
 
 	if err != nil {
-		return nil // Acquire failed
+		return nil, err // Acquire failed
 	}
 
 	// Acquire succeeded, but the context was canceled after?
 	if ctx.Err() == context.Canceled {
```
Comment (aanm) [inline daemon/daemon.go]: should be `ctx.Err != nil`?

File: pkg/endpoint/events.go [hunk 6]
```diff
@@ -45,7 +45,8 @@ func (ev *EndpointRegenerationEvent) Handle(res chan interface{}) {
 	// We should only queue the request after we use all the endpoint's
 	// lock/unlock. Otherwise this can get a deadlock if the endpoint is
 	// being deleted at the same time. More info PR-1777.
-	doneFunc := owner.QueueEndpointBuild(uint64(e.ID))
+	doneFunc, err := owner.QueueEndpointBuild(regenContext.parentContext, uint64(e.ID))
+	// If doneFunc != nil, error is nil.
```
Comment (aanm) [inline pkg/endpoint/events.go]: Instead of the comment, please check the error first.

File: pkg/endpoint/regenerationcontext.go [hunk 7]
```diff
@@ -110,9 +119,17 @@ type datapathRegenerationContext struct {
...
-func (ctx *datapathRegenerationContext) prepareForProxyUpdates() {
-	// Set up a context to wait for proxy completions.
-	completionCtx, completionCancel := context.WithTimeout(context.Background(), EndpointGenerationTimeout)
+func (ctx *datapathRegenerationContext) prepareForProxyUpdates(parentCtx context.Context) {
+	var (
+		completionCtx    context.Context
+		completionCancel context.CancelFunc
+	)
+
+	if parentCtx != nil {
```
Comment (aanm) [inline pkg/endpoint/regenerationcontext.go]: When would `parentCtx` be nil?

**Review by aanm — CHANGES_REQUESTED** [review]

File: pkg/endpoint/regenerationcontext.go (hunk 7 above)
Comment (ianvernon) [reply pkg/endpoint/regenerationcontext.go]: The behavior has changed now in this PR; It should never be nil at this point. I'll remove the nil check.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
@aanm I have addressed your comments, PTAL

**Comment by ianvernon** [comment]
test-me-please

File: pkg/endpoint/bpf.go [hunk 8]
```diff
@@ -380,7 +380,7 @@ func (e *Endpoint) regenerateBPF(owner Owner, regenContext *regenerationContext)
 	stats.waitingForLock.End(true)
 	defer owner.GetCompilationLock().RUnlock()
 
-	datapathRegenCtxt.prepareForProxyUpdates()
+	datapathRegenCtxt.prepareForProxyUpdates(regenContext.parentContext)
```
Comment (tgraf) [inline pkg/endpoint/bpf.go:383]: Given that you checked `regenMetadata.ParentContext` to be non-nil in an earlier commit I assume this could be nil and thus panic.

It might be easier to make sure that `regenMetadata.ParentContext` is always set and set it to `context.Background()` in `Regenerate()` if not set.

**Review by tgraf — CHANGES_REQUESTED** [review]

**Review by tgraf — APPROVED** [review]
Clarified on slack, code is good to go

File: pkg/endpoint/bpf.go (hunk 8 above)
Comment (ianvernon) [reply pkg/endpoint/bpf.go:383]: This is what is being done in the code - discussed offline.

**Review by joestringer — APPROVED** [review]

File: daemon/daemon.go [hunk 9]
```diff
@@ -243,19 +243,19 @@ func (d *Daemon) RemoveNetworkPolicy(e *endpoint.Endpoint) {
...
 	// Skip new build requests if the endpoint is already in the queue
 	// waiting. In this case the queued build will pick up any changes
 	// made so far, so there is no need to queue another build now.
 	if _, queued := d.uniqueID[epID]; queued {
 		d.uniqueIDMU.Unlock()
-		return nil
+		return nil, nil
 	}
 	// Store a cancel function to the 'uniqueID' map so that we can
 	// cancel the wait when the endpoint is being deleted.
```
Comment (raybejjani) [inline daemon/daemon.go:261]: Does the line below this mess things up? ctx variable is overwritten, isn't it? and then the cancel from the ctx parameter won't ever be seen. In particular, I'm not sure that the `ctx.Err()` check would ever trigger then.

File: daemon/daemon.go [hunk 10]
```diff
@@ -279,7 +279,7 @@ func (d *Daemon) QueueEndpointBuild(epID uint64) func() {
 	}
 
 	// Acquire succeeded, but the context was canceled after?
-	if ctx.Err() == context.Canceled {
+	if ctx.Err() != nil {
```
Comment (raybejjani) [inline daemon/daemon.go]: I might be missing it but, in older code, how would `ctx.Err()` ever be non-nil? It is created with `context.WithCancel(context.Background())`

File: pkg/datapath/loader/compile.go [hunk 11]
```diff
@@ -268,7 +268,12 @@ func compileDatapath(ctx context.Context, ep endpoint, dirs *directoryInfo, debu
 					logfields.Params: logfields.Repr(p),
 					logfields.Debug:  debug,
 				})
-				scopedLog.WithError(err).Debug("JoinEP: Failed to compile")
+				// Only log an error here if the context was not canceled or not
+				// timed out; this log message should only represent failures
+				// with respect to compiling the program.
+				if ctx.Err() == nil {
+					scopedLog.WithError(err).Debug("JoinEP: Failed to compile")
```
Comment (raybejjani) [inline pkg/datapath/loader/compile.go:275]: I hate to add more lines of code, but would a debug message when `ctx.Err() != nil` help to track cases where the timeouts happened? I'm not sure if there are other ways to correlate timings or sequences of events.

**Review by raybejjani — APPROVED** [review]

File: daemon/daemon.go (hunk 9 above)
Comment (ianvernon) [reply daemon/daemon.go:261]: Good catch, fixing.

File: daemon/daemon.go (hunk 10 above)
Comment (ianvernon) [reply daemon/daemon.go]: Fixed this by creating a new context with the `ctx` parameter from `QueueEndpointBuild` as the parent context.

File: daemon/daemon.go (hunk 9 above)
Comment (ianvernon) [reply daemon/daemon.go:261]: Fixed.

File: pkg/datapath/loader/compile.go (hunk 11 above)
Comment (ianvernon) [reply pkg/datapath/loader/compile.go:275]: If the context was canceled while the operation was occurring, the context's error should be propagated via the returned error, which can be logged by callers of the function. I am against this because we will be logging the same error multiple times in the same place, vs. here, the log indicates whether there is a problem with compilation / loading itself failing vs. due to the operation being canceled.

**Comment by ianvernon** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]

**Comment by ianvernon** [comment]
VM download failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11501/execution/node/57/log/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
DNS connectivity: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11502/testReport/junit/(root)/Suite-runtime/RuntimeChaos_Checking_that_during_restart_no_traffic_is_dropped_using_Egress___Ingress_Traffic/

**Comment by ianvernon** [comment]
test-me-please

**Comment by tgraf** [comment]
Awesome work @ianvernon
