### PR TITLE
loadbalancer: Add LookupFrontendByTuple and use from Hubble parser

### LINKED ISSUE #41623: cilium-agent memory leak after v1.18.1 upgrade
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.18.1 and lower than v1.19.0

### What happened?

We recently upgraded Cilium in our EKS clusters to v1.18.1 and started seeing memory leaks in cilium-agent: usually around 300M are used per pod but in this version it keeps growing indefinitely, especially visible on nodes with more traffic: there we saw some cilium-agents consume 2G in 24 hour which started affecting other workloads on the node.

There are no errors in the logs, memory usage just keeps growing and seems to do that faster when there's more traffic on the node.

### How can we reproduce the issue?

Following cilium settings are in use:
* routing-mode=native
* ipam=eni
* encryption.enabled=true
* encryption.type=wireguard

### Cilium Version

1.18.1

### Kernel Version

6.1.140 (Bottlerocket OS 1.41.0)

### Kubernetes Version

1.32.7-eks

### Regression

v1.18.0

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

downgrading to v1.18.0 seems to fix the mem leak.

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by joamaki**
676d346a1ead ("loadbalancer: Use unique for L3n4Addr") changed L3n4Addr to be backed by a `unique.Handle` to reduce memory usage and make hashing and comparisons fast. This significantly sped up the load-balancer control-plane as it was using `L3n4Addr` as a map key a lot. Unfortunately Go v1.24's unique package implementation wasn't tuned for very high rate of allocations and if `GOMAXPROCS` was low enough and allocation rate high enough this caused a huge backlog of `unique.Handle`s waiting to be cleaned up and memory usage kept ticking upwards. This was due to Go v1.24's unique implementing a cleanup with a background goroutine that iterated over the whole unique map to find `nil`d weak references. In Go v1.25 this issue doesn't exist as it uses `runtime.AddCleanup` to remove the references.

To fix the issue in v1.18 that uses Go v1.24 for some time now this introduces the `loadbalancer.LookupFrontendByTuple` that avoids creating a unique `L3n4Addr` value.

Benchmark results (GOMAXPROCS=4 benchtime=5s):
```
Go v1.24.0 no fix:
    BenchmarkGetServiceByAddr-4  3206036    2062·ns/op    1269·HeapSys+Released/MB    503·B/op    10·allocs/op⏎

Go v1.25.0 no fix:
    BenchmarkGetServiceByAddr-4  2083958    3425·ns/op    73.45·HeapSys+Released/MB    549·B/op    16·allocs/op⏎

Go v1.24.0 with LookupFrontendByTuple:
    BenchmarkGetServiceByAddr-4   18820899   315.4 ns/op    27.78 HeapSys+Released/MB      176 B/op     4 allocs/op

Go v1.25.0 with LookupFrontendByTuple:
    BenchmarkGetServiceByAddr-4   18694239   317.0 ns/op    28.14 HeapSys+Released/MB      176 B/op     4 allocs/op
```

In addition to fixing the leak this also sped up the best-case lookup times by 10x on both v1.24 and v1.25 due to avoiding the lookups into the unique map and allocations.

Fixes: #41623

```release-note
Fix increase in memory usage when service names are looked up at high rate during Hubble flow creation
```

### CODE REVIEW

File: pkg/loadbalancer/frontend.go [hunk 1]
```diff
@@ -239,6 +241,26 @@ var (
...
+// Prefer [FrontendByAddress] over this.
+func LookupFrontendByTuple(txn statedb.ReadTxn, fes statedb.Table[*Frontend], addrCluster cmtypes.AddrCluster, proto L4Type, port uint16, scope uint8) (fe *Frontend, found bool) {
+	rep := l3n4AddrRep{
+		addrCluster: addrCluster,
+		L4Addr:      L4Addr{Protocol: proto, Port: port},
+		scope:       scope,
+	}
+	// Construct a temporary L3n4Addr without going via unique.Make.
+	h := &struct{ rep *l3n4AddrRep }{&rep}
+	l3n4Addr := (*L3n4Addr)(unsafe.Pointer(h))
```
Comment (joamaki) [inline pkg/loadbalancer/frontend.go:259]: Really would've preferred to avoid doing something like this, but unfortunately I didn't have the foresight of exposing the ability to look up with raw keys in StateDB (e.g. `Index[].QueryRaw`).

I'll do a follow-up to expose that facility in a future StateDB version and we can then refactor this (https://github.com/cilium/statedb/pull/105). But as this is backported to v1.18 I would like to avoid tying this fix to a StateDB version bump.

**Review by ysksuzuki — APPROVED** [review]

**Review by rolinh — APPROVED** [review]
