### PR TITLE
allocator: fix race condition when allocating local identities upon bootstrap

### LINKED ISSUE #8342: Traffic to FQDN is always denied, even though there's a CIDR policy for it
Observed in Cilium master (v1.6 cycle), taking notes so the mitigation can be found:

There's an FQDN policy something like:

```
  {
    "endpointSelector": {
      "matchLabels": {
        "k8s:app": "foo",
        "k8s:io.kubernetes.pod.namespace": "default"
      }
    },
    "egress": [
      {
        "toCIDRSet": [
          {
            "cidr": "1.2.3.4/32"
          }
        ],
        "toFQDNs": [
          {
            "matchName": "my-external-service"
          }
        ]
      }
    ],
```

The BPF ipcache doesn't have a corresponding entry for the IP:

```
# cilium map get cilium_ipcache | grep 1.2.3.4
#
```

Cilium identity list shows a global (!) identity for the CIDR (*not* a local identity, which would start with 16xxxxxxx):

```
# cilium identity list | grep "35.201.64.140"                                                                                              
7804       cidr:1.2.3.4/32
```

The identity shows up in the kvstore
```
# cilium kvstore get --recursive "cilium/state/identities/v1/value" | grep cidr
level=info msg="Connecting to etcd server..." config=/var/lib/etcd-config/etcd.config endpoints="[https://cilium-etcd-client.kube-system.svc:2379]" subsys=kvstore
cilium/state/identities/v1/value/cidr:0.0.0.0/0=;...;cidr:1.2.3.4/32=;reserved:world=;/w.x.y.z => 7804
```

In this case, it is likely that a race condition has been hit during startup which has caused the FQDN CIDR to have a global identity allocated instead of a local identity.

Mitigation:

Add a new policy which selects the CIDR which is affected by this problem. This mitigation would be necessary until upgrading to a version that fixes the issue (should be addressed in v1.6).

### PR DESCRIPTION
**Pull request by ianvernon**
When identities are attempted to be allocated by `AllocateIdentity`, both the
labels are checked for if the identity is local, *and* whether the
`localIdentities` structure is non-nil:

```
...

if !identity.RequiresGlobalIdentity(lbls) && localIdentities != nil {
        return localIdentities.lookupOrCreate(lbls)
}

// else allocate global identity

...
```

Upon bootstrap, the creation of the localIdentities structure was done
asynchronously along with the creation of the global identity allocator. This
meant that if a local identity for a CIDR was attempted to be allocated upon
bootstrap soon after `InitIdentityAllocator` was invoked, there was no guarantee
as to whether `localIdentities` was initialized or not. Consequently, even if a
set of labels did correspond to a local identity (e.g., for a CIDR), there would
be no local identity allocated for the CIDR, and instead, a global identity
would be allocated. This is incorrect behavior.

Fix this incorrect behavior by doing the following:

* Create `localIdentities` synchronously with calls to `InitIdentityAllocator`.
The initialization of the global allocator is still done asynchronously.
* Do not asynchronously call `InitIdentityAllocator` upon bootstrap any more,
since `InitIdentityAllocator` synchronously creates the local identity allocator
now, but now creates the global identity allocator asynchronously.

Additionally, add another function, which calls the refactored
`InitIdentityAllocator` and waits for it to be initialized, to preserve existing
behavior in unit tests.

Fixes: f3bbcd8e88 ("identity: Use local identities to represent CIDR")
Fixes: #8342

Signed-off by: Ian Vernon <ian@cilium.io>

```release-note
Fix bug where global identities are allocated for CIDRs
```

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8345)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

File: pkg/identity/cache/allocator.go [hunk 1]
```diff
@@ -100,29 +100,44 @@ func InitIdentityAllocator(owner IdentityAllocatorOwner) {
...
-	localIdentities = newLocalIdentityCache(1, 0xFFFFFF, events)
+		IdentityAllocator = a
+		close(identityAllocatorInitialized)
+	}(events)
+}
 
+// InitIdentityAllocatorAndWait initializes the identity allocator and waits for
+// it to finish being initialized.
+func InitIdentityAllocatorAndWait(owner IdentityAllocatorOwner) {
+	go InitIdentityAllocator(owner)
```
Comment (joestringer) [inline pkg/identity/cache/allocator.go]: Why is the extra goroutine necessary here?

File: pkg/identity/cache/allocator.go [hunk 2]
```diff
@@ -100,29 +100,44 @@ func InitIdentityAllocator(owner IdentityAllocatorOwner) {
...
-	close(identityAllocatorInitialized)
-	localIdentities = newLocalIdentityCache(1, 0xFFFFFF, events)
+		IdentityAllocator = a
+		close(identityAllocatorInitialized)
+	}(events)
+}
 
+// InitIdentityAllocatorAndWait initializes the identity allocator and waits for
+// it to finish being initialized.
+func InitIdentityAllocatorAndWait(owner IdentityAllocatorOwner) {
```
Comment (joestringer) [inline pkg/identity/cache/allocator.go]: Hmm. This is only actually used by test code right?

**Review by joestringer — CHANGES_REQUESTED** [review]
I wonder if it'd be tidier to actually just return the `identityAllocatorInitialized` channel from the main `InitIdentityAllocator()` function instead; then in the daemon code you can do something like:

```
identitiesReadyChan := InitIdentityAllocator(...)
...
...
<-identitiesReadyChan
```

Then from the test code you could have nice shorthand:

```
<-InitIdentityAllocator(...)
```

Minor nits though. The main thing I question is below about the extra goroutine.

**Comment by ianvernon** [comment]
VM provisioning failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/13098/

```
23:01:39      k8s1-1.14: error execution phase bootstrap-token: error creating bootstrap ConfigMap: unable to create configmap: etcdserver: request timed out
23:01:39  The SSH command responded with a non-zero exit status. Vagrant
23:01:39  assumes that this means the command failed. The output for this command
23:01:39  should be in the log above. Please read the output to determine what
23:01:39  went wrong.
```

File: pkg/identity/cache/allocator.go (hunk 1 above)
Comment (ianvernon) [reply pkg/identity/cache/allocator.go]: It isn't strictly necessary, removing.

File: pkg/identity/cache/allocator.go (hunk 2 above)
Comment (ianvernon) [reply pkg/identity/cache/allocator.go]: Yes, correct. It's used across the codebase for initializing state.

**Comment by ianvernon** [comment]
@joestringer addressed your comments.

**Comment by ianvernon** [comment]
test-me-please

File: pkg/identity/cache/allocator.go [hunk 3]
```diff
@@ -100,29 +101,39 @@ func InitIdentityAllocator(owner IdentityAllocatorOwner) {
 
 	log.Info("Initializing identity allocator")
 
-	minID := idpool.ID(identity.MinimalAllocationIdentity)
-	maxID := idpool.ID(identity.MaximumAllocationIdentity)
+	// Local identity cache can be created synchronously since it doesn't
+	// reply upon any external resources (e.g., external kvstore).
```
Comment (joestringer) [inline pkg/identity/cache/allocator.go]:
```suggestion
	// rely upon any external resources (e.g., external kvstore).
```

File: daemon/daemon.go [hunk 4]
```diff
@@ -829,7 +829,7 @@ func NewDaemon(dp datapath.Datapath) (*Daemon, *endpointRestoreState, error) {
 	// This needs to be done after the node addressing has been configured
 	// as the node address is required as suffix.
 	// well known identities have already been initialized above
-	go cache.InitIdentityAllocator(&d)
+	cache.InitIdentityAllocator(&d)
```
Comment (joestringer) [inline daemon/daemon.go:834]: nit: Might be nice to comment that we're explicitly ignoring the return channel for now? Otherwise it's not entirely clear why.

**Review by joestringer — APPROVED** [review]
Thanks! LGMT, Minor nits. I think someone else with more familiarity with this code should also take a look. (@aanm / @tgraf ?)

File: pkg/identity/cache/allocator.go [hunk 5]
```diff
@@ -100,29 +101,39 @@ func InitIdentityAllocator(owner IdentityAllocatorOwner) {
...
+		}
 
-	IdentityAllocator = a
-	close(identityAllocatorInitialized)
-	localIdentities = newLocalIdentityCache(1, 0xFFFFFF, events)
+		IdentityAllocator = a
+		close(identityAllocatorInitialized)
+	}(owner, events)
 
+	return identityAllocatorInitialized
```
Comment (aanm) [inline pkg/identity/cache/allocator.go]: ~There's no need to return this channel as the function `WaitForInitialIdentities` should be used for the same purpose.~ See review description.

File: pkg/identity/cache/allocator.go [hunk 6]
```diff
@@ -100,29 +101,39 @@ func InitIdentityAllocator(owner IdentityAllocatorOwner) {
...
+		defer setupMutex.Unlock()
+		minID := idpool.ID(identity.MinimalAllocationIdentity)
+		maxID := idpool.ID(identity.MaximumAllocationIdentity)
+
+		// It is important to start listening for events before calling
+		// NewAllocator() as it will emit events while filling the
+		// initial cache
+		watcher.watch(owner, evs)
+
+		a, err := allocator.NewAllocator(IdentitiesPath, globalIdentity{},
```
Comment (aanm) [inline pkg/identity/cache/allocator.go:129]: The Async part can start in this line.

**Review by aanm — CHANGES_REQUESTED** [review]
Great finding.

Looking at the rest of the code unfortunately it does not fix all bugs related with this. As k8s is initialized first, so it is the CNP sync of which, if it contains a CIDR, also perform a `AllocateIdentity`. We should do the exact same behavior that we are doing for the global identities:

https://github.com/cilium/cilium/blob/2bc1fdeb97331761241f2e4b3fb88ad524a0681b/pkg/identity/cache/allocator.go#L212-L218

So, something like

```golang
	WaitForLocalIdentities(ctx)
	if !identity.RequiresGlobalIdentity(lbls) && localIdentities != nil {
		return localIdentities.lookupOrCreate(lbls)
	}
```

where `WaitForLocalIdentities` would wait for a channel to be closed once the `localIdentities` was initialized.

File: pkg/identity/cache/allocator.go (hunk 6 above)
Comment (ianvernon) [reply pkg/identity/cache/allocator.go:129]: Done.

**Comment by ianvernon** [comment]
@aanm the K8s syncing logic is not initialized until much later, after `InitIdentityAllocator` is invoked - this means that with my changes, we are guaranteed to have the local identity allocator initialized before K8s resources are synced.

`runDaemon` calls `NewDaemon`, which calls `InitIdentityAllocator`:

https://github.com/cilium/cilium/blob/1d25f1c25b7306b528154472de7dcb32ac58e9eb/daemon/daemon_main.go#L1239-L1263

https://github.com/cilium/cilium/blob/1d25f1c25b7306b528154472de7dcb32ac58e9eb/daemon/daemon.go#L832

https://github.com/cilium/cilium/blob/1d25f1c25b7306b528154472de7dcb32ac58e9eb/daemon/daemon_main.go#L1294-L1301

Looks like that comment is out of date ;) I will fix that one up as well.

However, I think that making this explicit is fine via waiting for a channel to be closed since that codifies this dependency and indicates what we expect to be bootstrapped when K8s is instantiated. Having these dependencies coded in explicitly via waiting for channels to be closed ensures that even if we ever change how `InitIdentityAllocator` operates in the future, we will ensure that the local identity allocator is always initialized. I'll add a follow-up commit with this shortly!

File: daemon/daemon.go (hunk 4 above)
Comment (ianvernon) [reply daemon/daemon.go:834]: Done!

**Comment by ianvernon** [comment]
test-me-please

File: daemon/k8s_watcher.go [hunk 7]
```diff
@@ -295,6 +296,11 @@ func (d *Daemon) waitForCacheSync(resourceNames ...string) {
 // initK8sSubsystem returns a channel for which it will be closed when all
 // caches essential for daemon are synchronized.
 func (d *Daemon) initK8sSubsystem() <-chan struct{} {
+	// We need to wait for the local identity allocator to be initialized before
+	// we sync CNPs from K8s, since those CNPs may contain CIDRs, the identities
+	// of which are created using local identity allocation.
+	cache2.WaitForLocalIdentityAllocator()
```
Comment (aanm) [inline daemon/k8s_watcher.go]: IMO this `WaitForLocalIdentityAllocator()` should be in the `AllocateIdentity` and `ReleaseIdentity` function, similar to the `WaitForInitialIdentities(ctx)`. Your comment even says "those CNPs may contain CIDRs" which does not mean that we should always block the k8s subsystem because of the local identities not being initialized.

**Review by aanm — CHANGES_REQUESTED** [review]

File: daemon/k8s_watcher.go (hunk 7 above)
Comment (ianvernon) [reply daemon/k8s_watcher.go]: Got it - I added the check in both `AllocateIdentity` and `ReleaseIdentity` and also removed the nil check from those functions since we now wait for it to be initialized. 

I'm going to keep it in the k8s initialization function as well to ensure that we maintain proper ordering in our bootstrap functionality.

**Comment by ianvernon** [comment]
test-me-please

File: daemon/k8s_watcher.go (hunk 7 above)
Comment (aanm) [reply daemon/k8s_watcher.go]: Please remove it, it only adds unnecessary complexity into this function.

**Review by aanm — CHANGES_REQUESTED** [review]

**Comment by ianvernon** [comment]
VM provisioning timed out: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/13138/

**Comment by ianvernon** [comment]
test-me-please

File: daemon/k8s_watcher.go (hunk 7 above)
Comment (ianvernon) [reply daemon/k8s_watcher.go]: I disagree. This codifies a dependency that we have within the Kubernetes subsystem to ensure that if we ever shift the order of bootstrapping around, that we will deadlock because the channel will not be closed. Explicitly specifying that we expect certain ordering of operations to be completed when we initialize K8s in the functions themselves provides this sort of guarantee in the code itself.

Comment (aanm) [reply daemon/k8s_watcher.go]: Kubernetes depends on the allocator, we are exposing allocator internals here which are unnecessary. Why don't we put a `kvstore.IsReady()` here since the allocator also depends on the kvstore is initialized? By adding this, we are unnecessarily blocking k8s setup where it could start fetching pods/nodes/cnps/netpol/namespace in parallel before even need to allocate an identity.

**Review by aanm — CHANGES_REQUESTED** [review]

**Comment by ianvernon** [comment]
@aanm I still disagree, but I will defer to you on this one.

**Comment by ianvernon** [comment]
test-me-please

File: daemon/k8s_watcher.go [hunk 8]
```diff
@@ -30,6 +30,7 @@ import (
 	"github.com/cilium/cilium/pkg/controller"
 	"github.com/cilium/cilium/pkg/endpointmanager"
 	"github.com/cilium/cilium/pkg/identity"
+	cache2 "github.com/cilium/cilium/pkg/identity/cache"
```
Comment (joestringer) [inline daemon/k8s_watcher.go]:
```
17:07:22      runtime: ./k8s_watcher.go:33:2: imported and not used: "github.com/cilium/cilium/pkg/identity/cache" as cache2
```

File: pkg/identity/cache/allocator.go [hunk 9]
```diff
@@ -205,13 +233,14 @@ func AllocateIdentity(ctx context.Context, owner IdentityAllocatorOwner, lbls la
...
-	if !identity.RequiresGlobalIdentity(lbls) && localIdentities != nil {
+	if !identity.RequiresGlobalIdentity(lbls) {
+		<-localIdentityAllocatorInitialized
 		return localIdentities.lookupOrCreate(lbls)
 	}
 
 	// This will block until the kvstore can be accessed and all identities
 	// were successfully synced
-	WaitForInitialIdentities(ctx)
+	WaitForInitialGlobalIdentities(ctx)
```
Comment (joestringer) [inline pkg/identity/cache/allocator.go:243]: `WaitForInitialGlobalIdentities()` returns an error, we should check it (and that should handle the `IdentityAllocator == nil` case below, if I follow correctly).

File: pkg/identity/cache/allocator.go [hunk 10]
```diff
@@ -260,7 +290,7 @@ func Release(ctx context.Context, owner IdentityAllocatorOwner, id *identity.Ide
...
```
Comment (joestringer) [inline pkg/identity/cache/allocator.go:293]: Check the error returned.

File: daemon/state.go [hunk 11]
```diff
@@ -281,7 +281,7 @@ func (d *Daemon) regenerateRestoredEndpoints(state *endpointRestoreState) (resto
 			// endpoints that don't have a fixed identity or are
 			// not well known.
 			if !identity.IsFixed() && !identity.IsWellKnown() {
-				cache.WaitForInitialIdentities(context.Background())
+				cache.WaitForInitialGlobalIdentities(context.Background())
```
Comment (joestringer) [inline daemon/state.go:284]: shouldn't we check/handle the error here?

**Review by joestringer — CHANGES_REQUESTED** [review]

File: daemon/state.go (hunk 11 above)
Comment (ianvernon) [reply daemon/state.go:284]: Only if we pass a context that is canceled (`context.Background()` is not). Otherwise we will wait forever on the channels in the `select` statements in the function / subsequent function calls in `WaitForInitialGlobalIdentities`. Perhaps we can replace `context.Background` to something with a timeout? This is somewhat out of scope of this PR in my opinion.

I guess we could assume that the function actually will return an error in the future (it won't ever in its current form how it is invoked here), and then signal: 

```
epRegenerated <- false
return
``` 

thoughts?

**Comment by ianvernon** [comment]
test-me-please

File: pkg/identity/cache/allocator.go (hunk 10 above)
Comment (ianvernon) [reply pkg/identity/cache/allocator.go:293]: See https://github.com/cilium/cilium/pull/8345#discussion_r295916349

File: daemon/state.go (hunk 11 above)
Comment (joestringer) [reply daemon/state.go:284]: Oh, because these functions only return an error if the context times out, I see.

Yeah, so not for this case but presumably the other cases should pass a timed context?

Agree this could be handled in a separate PR, just seemed weird to me that we ignore an error from a function that could return an error, then keep doing other stuff afterwards, almost as though we assume that this function did not return an error.

**Review by joestringer — APPROVED** [review]

File: daemon/k8s_watcher.go (hunk 7 above)
Comment (ianvernon) [reply daemon/k8s_watcher.go]: Removed.

File: daemon/state.go (hunk 11 above)
Comment (ianvernon) [reply daemon/state.go:284]: Filed this is a good first issue: https://github.com/cilium/cilium/issues/8368

File: pkg/identity/cache/allocator.go (hunk 10 above)
Comment (ianvernon) [reply pkg/identity/cache/allocator.go:293]: Filed this as a good first issue: https://github.com/cilium/cilium/issues/8368

**Comment by ianvernon** [comment]
Marking as ready to merge since I have addressed all pending comments directly.

**Review by jrajahalme — APPROVED** [review]
