### PR TITLE
clustermesh: correctly release allocator references for GC

### LINKED ISSUE #13446: 'cilium-agent' memory leak, possibly due to cluster mesh
## Bug report

**General Information**

- Cilium version (run `cilium version`):
```
Client: 1.8.3 54cf3810d 2020-09-04T14:01:53+02:00 go version go1.14.7 linux/amd64
Daemon: 1.8.3 54cf3810d 2020-09-04T14:01:53+02:00 go version go1.14.7 linux/amd64
```
- Kernel version (run `uname -a`): `Linux ip-10-2-36-164.ap-northeast-1.compute.internal 4.14.193-149.317.amzn2.x86_64 #1 SMP Thu Sep 3 19:04:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**How to reproduce the issue**

I'm not exactly sure how to reproduce it. The setup is 2 k8s clusters, connected using cluster mesh on AWS. Everything seemed to be working fine, until I noticed pods kept getting evicted. It seems like the memory usage for `cilium-agent` just kept rising, while trying to connect to the remote etcd cluster.

Sorry I haven't extracted the full logs, this is a production setup that needed to be fixed ASAP (basically restarted everything to make it work again). I'll keep monitoring now again to see if it happens and will provide full logs if so.

image

The repeating logs are (from Loki):

```
2020-10-07T12:23:27+03:00 {} level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
2020-10-07T12:23:27+03:00 {} level=info msg="Connecting to etcd server..." config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" subsys=kvstore
2020-10-07T12:23:27+03:00 {} level=warning msg="Error observed on etcd connection, reconnecting etcd" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 error="not able to connect to any etcd endpoints" kvstoreErr="not able to connect to any etcd endpoints" kvstoreStatus="not able to connect to any etcd endpoints" subsys=clustermesh
2020-10-07T12:23:27+03:00 {} level=info msg="Established connection to remote etcd" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 kvstoreErr="not able to connect to any etcd endpoints" kvstoreStatus="not able to connect to any etcd endpoints" subsys=clustermesh
2020-10-07T12:23:27+03:00 {} level=info msg="Connection to remote cluster established" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 kvstoreErr="<nil>" kvstoreStatus= subsys=clustermesh
2020-10-07T12:23:27+03:00 {} level=info msg="Successfully verified version of etcd endpoint" config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" etcdEndpoint="https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271" subsys=kvstore version=3.3.12
2020-10-07T12:23:25+03:00 {} {"level":"warn","ts":"2020-10-07T09:23:25.247Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthrough:///https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
2020-10-07T12:23:16+03:00 {} level=info msg="Initial etcd session established" config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" subsys=kvstore
2020-10-07T12:23:16+03:00 {} level=info msg="Got lock lease ID f0a74d136d82b3a" subsys=kvstore
2020-10-07T12:23:16+03:00 {} level=info msg="Got lease ID f0a74d136d82b38" subsys=kvstore
2020-10-07T12:23:06+03:00 {} {"level":"warn","ts":"2020-10-07T09:23:06.482Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-2e1ac3d5-992f-47d1-b0bb-4f49625602d2/prod-k8s-ap-northeast-1.mesh.cilium.io:32271","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}
2020-10-07T12:23:05+03:00 {} level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
2020-10-07T12:23:05+03:00 {} level=info msg="Connecting to etcd server..." config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" subsys=kvstore
2020-10-07T12:23:05+03:00 {} level=warning msg="Error observed on etcd connection, reconnecting etcd" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 error="not able to connect to any etcd endpoints" kvstoreErr="not able to connect to any etcd endpoints" kvstoreStatus="not able to connect to any etcd endpoints" subsys=clustermesh
2020-10-07T12:23:05+03:00 {} level=info msg="Established connection to remote etcd" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 kvstoreErr="not able to connect to any etcd endpoints" kvstoreStatus="not able to connect to any etcd endpoints" subsys=clustermesh
2020-10-07T12:23:04+03:00 {} level=info msg="Connection to remote cluster established" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 kvstoreErr="<nil>" kvstoreStatus= subsys=clustermesh
2020-10-07T12:23:04+03:00 {} level=info msg="Successfully verified version of etcd endpoint" config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" etcdEndpoint="https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271" subsys=kvstore version=3.3.12
2020-10-07T12:23:02+03:00 {} {"level":"warn","ts":"2020-10-07T09:23:02.996Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthrough:///https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
2020-10-07T12:22:55+03:00 {} level=info msg="Reloaded endpoint BPF program" containerID= datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=809 identity=1 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2020-10-07T12:22:54+03:00 {} level=info msg="Reloaded endpoint BPF program" containerID= datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=2729 identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2020-10-07T12:22:54+03:00 {} level=info msg="Reloaded endpoint BPF program" containerID=df2377d1f2 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=102 identity=106 ipv4=10.1.47.33 ipv6= k8sPodName=kube-system/coredns-6f4dfbffb4-qn2jd subsys=endpoint
2020-10-07T12:22:54+03:00 {} level=info msg="Reloaded endpoint BPF program" containerID=f3dae2d079 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=1736 identity=106 ipv4=10.1.59.55 ipv6= k8sPodName=kube-system/coredns-6f4dfbffb4-wbtwx subsys=endpoint
2020-10-07T12:22:54+03:00 {} level=info msg="Initial etcd session established" config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" subsys=kvstore
2020-10-07T12:22:54+03:00 {} level=info msg="Got lock lease ID 1e5974d137583c3b" subsys=kvstore
2020-10-07T12:22:54+03:00 {} level=info msg="Got lease ID 1e5974d137583c39" subsys=kvstore
2020-10-07T12:22:53+03:00 {} level=info msg="regenerating all endpoints" reason="datapath ipcache" subsys=endpoint-manager
2020-10-07T12:22:53+03:00 {} level=info msg="Setting sysctl net.ipv4.conf.eth0.rp_filter=2" subsys=datapath-loader
2020-10-07T12:22:53+03:00 {} level=info msg="Setting sysctl kernel.unprivileged_bpf_disabled=1" subsys=datapath-loader
2020-10-07T12:22:53+03:00 {} level=info msg="Setting sysctl net.ipv4.conf.all.rp_filter=0" subsys=datapath-loader
2020-10-07T12:22:53+03:00 {} level=info msg="Setting sysctl net.core.bpf_jit_enable=1" subsys=datapath-loader
2020-10-07T12:22:53+03:00 {} level=info msg="Setting up base BPF datapath (BPF v2 instruction set, ktime clock source)" subsys=datapath-loader
2020-10-07T12:22:53+03:00 {} level=info msg="Reloaded endpoint BPF program" containerID= datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=2729 identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2020-10-07T12:22:53+03:00 {} level=info msg="Reloaded endpoint BPF program" containerID= datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=809 identity=1 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2020-10-07T12:22:53+03:00 {} level=info msg="Reloaded endpoint BPF program" containerID=df2377d1f2 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=102 identity=106 ipv4=10.1.47.33 ipv6= k8sPodName=kube-system/coredns-6f4dfbffb4-qn2jd subsys=endpoint
2020-10-07T12:22:53+03:00 {} level=info msg="Reloaded endpoint BPF program" containerID=f3dae2d079 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=1736 identity=106 ipv4=10.1.59.55 ipv6= k8sPodName=kube-system/coredns-6f4dfbffb4-wbtwx subsys=endpoint
2020-10-07T12:22:52+03:00 {} level=info msg="regenerating all endpoints" reason="datapath ipcache" subsys=endpoint-manager
2020-10-07T12:22:51+03:00 {} level=info msg="Setting sysctl net.ipv4.conf.eth0.rp_filter=2" subsys=datapath-loader
2020-10-07T12:22:51+03:00 {} level=info msg="Setting sysctl kernel.unprivileged_bpf_disabled=1" subsys=datapath-loader
2020-10-07T12:22:51+03:00 {} level=info msg="Setting sysctl net.ipv4.conf.all.rp_filter=0" subsys=datapath-loader
2020-10-07T12:22:51+03:00 {} level=info msg="Setting sysctl net.core.bpf_jit_enable=1" subsys=datapath-loader
2020-10-07T12:22:51+03:00 {} level=info msg="Setting up base BPF datapath (BPF v2 instruction set, ktime clock source)" subsys=datapath-loader
2020-10-07T12:22:43+03:00 {} level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
2020-10-07T12:22:42+03:00 {} level=info msg="Connecting to etcd server..." config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" subsys=kvstore
2020-10-07T12:22:42+03:00 {} level=warning msg="Error observed on etcd connection, reconnecting etcd" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 error="not able to connect to any etcd endpoints" kvstoreErr="not able to connect to any etcd endpoints" kvstoreStatus="not able to connect to any etcd endpoints" subsys=clustermesh
2020-10-07T12:22:42+03:00 {} level=info msg="Established connection to remote etcd" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 kvstoreErr="not able to connect to any etcd endpoints" kvstoreStatus="not able to connect to any etcd endpoints" subsys=clustermesh
2020-10-07T12:22:42+03:00 {} level=info msg="Connection to remote cluster established" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 kvstoreErr="<nil>" kvstoreStatus= subsys=clustermesh
2020-10-07T12:22:42+03:00 {} level=info msg="Successfully verified version of etcd endpoint" config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" etcdEndpoint="https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271" subsys=kvstore version=3.3.12
2020-10-07T12:22:40+03:00 {} {"level":"warn","ts":"2020-10-07T09:22:40.749Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthrough:///https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
2020-10-07T12:22:31+03:00 {} level=info msg="Initial etcd session established" config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" subsys=kvstore
2020-10-07T12:22:31+03:00 {} level=info msg="Got lock lease ID 513f74d136b72b7e" subsys=kvstore
2020-10-07T12:22:31+03:00 {} level=info msg="Got lease ID 513f74d136b72b7c" subsys=kvstore
2020-10-07T12:22:21+03:00 {} level=info msg="Reloaded endpoint BPF program" containerID= datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=2729 identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2020-10-07T12:22:21+03:00 {} level=info msg="Reloaded endpoint BPF program" containerID= datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=809 identity=1 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2020-10-07T12:22:21+03:00 {} level=info msg="Reloaded endpoint BPF program" containerID=df2377d1f2 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=102 identity=106 ipv4=10.1.47.33 ipv6= k8sPodName=kube-system/coredns-6f4dfbffb4-qn2jd subsys=endpoint
2020-10-07T12:22:21+03:00 {} level=info msg="Reloaded endpoint BPF program" containerID=f3dae2d079 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=1736 identity=106 ipv4=10.1.59.55 ipv6= k8sPodName=kube-system/coredns-6f4dfbffb4-wbtwx subsys=endpoint
2020-10-07T12:22:21+03:00 {} level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
2020-10-07T12:22:20+03:00 {} level=info msg="regenerating all endpoints" reason="datapath ipcache" subsys=endpoint-manager
2020-10-07T12:22:20+03:00 {} level=info msg="Connecting to etcd server..." config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" subsys=kvstore
2020-10-07T12:22:20+03:00 {} level=warning msg="Error observed on etcd connection, reconnecting etcd" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 error="not able to connect to any etcd endpoints" kvstoreErr="not able to connect to any etcd endpoints" kvstoreStatus="not able to connect to any etcd endpoints" subsys=clustermesh
2020-10-07T12:22:20+03:00 {} level=info msg="Established connection to remote etcd" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 kvstoreErr="not able to connect to any etcd endpoints" kvstoreStatus="not able to connect to any etcd endpoints" subsys=clustermesh
2020-10-07T12:22:20+03:00 {} level=info msg="Connection to remote cluster established" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 kvstoreErr="<nil>" kvstoreStatus= subsys=clustermesh
2020-10-07T12:22:20+03:00 {} level=info msg="Successfully verified version of etcd endpoint" config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" etcdEndpoint="https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271" subsys=kvstore version=3.3.12
2020-10-07T12:22:20+03:00 {} level=info msg="Setting sysctl net.ipv4.conf.eth0.rp_filter=2" subsys=datapath-loader
2020-10-07T12:22:20+03:00 {} level=info msg="Setting sysctl kernel.unprivileged_bpf_disabled=1" subsys=datapath-loader
2020-10-07T12:22:20+03:00 {} level=info msg="Setting sysctl net.ipv4.conf.all.rp_filter=0" subsys=datapath-loader
2020-10-07T12:22:20+03:00 {} level=info msg="Setting sysctl net.core.bpf_jit_enable=1" subsys=datapath-loader
2020-10-07T12:22:20+03:00 {} level=info msg="Setting up base BPF datapath (BPF v2 instruction set, ktime clock source)" subsys=datapath-loader
2020-10-07T12:22:18+03:00 {} {"level":"warn","ts":"2020-10-07T09:22:18.501Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthrough:///https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
2020-10-07T12:22:09+03:00 {} level=info msg="Initial etcd session established" config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" subsys=kvstore
2020-10-07T12:22:09+03:00 {} level=info msg="Got lock lease ID 513f74d136b72b70" subsys=kvstore
2020-10-07T12:22:09+03:00 {} level=info msg="Got lease ID 513f74d136b72b6e" subsys=kvstore
2020-10-07T12:21:58+03:00 {} level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
2020-10-07T12:21:58+03:00 {} level=info msg="Connecting to etcd server..." config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" subsys=kvstore
2020-10-07T12:21:58+03:00 {} level=warning msg="Error observed on etcd connection, reconnecting etcd" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 error="not able to connect to any etcd endpoints" kvstoreErr="not able to connect to any etcd endpoints" kvstoreStatus="not able to connect to any etcd endpoints" subsys=clustermesh
2020-10-07T12:21:58+03:00 {} level=info msg="Established connection to remote etcd" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 kvstoreErr="not able to connect to any etcd endpoints" kvstoreStatus="not able to connect to any etcd endpoints" subsys=clustermesh
2020-10-07T12:21:58+03:00 {} level=info msg="Connection to remote cluster established" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 kvstoreErr="<nil>" kvstoreStatus= subsys=clustermesh
2020-10-07T12:21:58+03:00 {} level=info msg="Successfully verified version of etcd endpoint" config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" etcdEndpoint="https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271" subsys=kvstore version=3.3.12
2020-10-07T12:21:56+03:00 {} {"level":"warn","ts":"2020-10-07T09:21:56.209Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthrough:///https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
2020-10-07T12:21:47+03:00 {} level=info msg="Initial etcd session established" config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" subsys=kvstore
2020-10-07T12:21:47+03:00 {} level=info msg="Got lock lease ID 1e5974d137583c22" subsys=kvstore
2020-10-07T12:21:47+03:00 {} level=info msg="Got lease ID 1e5974d137583c20" subsys=kvstore
```

### LINKED ISSUE #22988: clustermesh: agent leaks memory when remote cluster connection is restarted
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We started to see memory increase when remote cluster connection was restarted. And each time the remote connection was restarted the more memory it leaked. The problematic cluster had around 20k identities which was fantastic because otherwise we would not see the leak so early.   

The memory should stay the same before and after the restart. (also the memory was not released when we totally removed the cluster from clustermesh). 

I can easily reproduce this if I manually update a selected remote cluster config (to trigger fsnotify) each time I do this, some memory is leaked.

### Cilium Version

```
Client: 1.12.4 ac046c95eb 2022-11-16T14:51:11+01:00 go version go1.18.8 linux/amd64
Daemon: 1.12.4 ac046c95eb 2022-11-16T14:51:11+01:00 go version go1.18.8 linux/amd64
```

### Kernel Version

`Linux tt-os2-n1.ko.iszn.cz 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8", GitCommit:"7061dbbf75f9f82e8ab21f9be7e8ffcaae8e0d44", GitTreeState:"clean", BuildDate:"2022-03-16T14:10:06Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8", GitCommit:"7061dbbf75f9f82e8ab21f9be7e8ffcaae8e0d44", GitTreeState:"clean", BuildDate:"2022-03-16T14:04:34Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

but it's not related to k8s as it happens also on nodes outside of k8s 

### Sysdump

_No response_

### Relevant log output

```shell
level=info msg="etcd configuration has changed, re-creating connection" clusterName=uacl-test-labrador-test config=/www/sasanka/secrets/cilium/configs/uacl-test-labrador-test kvstoreErr="<nil>" kvstoreStatus="etcd: 1/1 connected, lease-ID=3b2a847f52738930, lock lease-ID=3b2a847f52738935, has-quorum=true: https://uacl-test-labrador-test.ko.iszn.cz:31007 - 3.5.4" subsys=clustermesh
level=info msg="Creating etcd client" ConfigPath=/www/sasanka/secrets/cilium/configs/uacl-test-labrador-test KeepAliveHeartbeat=15s KeepAliveTimeout=25s RateLimit=20 subsys=kvstore
level=info msg="Connecting to etcd server..." config=/www/sasanka/secrets/cilium/configs/uacl-test-labrador-test endpoints="[https://uacl-test-labrador-test.ko.iszn.cz:31007]" subsys=kvstore
level=info msg="Got lease ID 10df847f53140be2 and the session TTL is 15m0s" subsys=kvstore
level=info msg="Got lock lease ID 10df847f53140be7" subsys=kvstore
level=info msg="Initial etcd session established" config=/www/sasanka/secrets/cilium/configs/uacl-test-labrador-test endpoints="[https://uacl-test-labrador-test.ko.iszn.cz:31007]" subsys=kvstore
level=info msg="Successfully verified version of etcd endpoint" config=/www/sasanka/secrets/cilium/configs/uacl-test-labrador-test endpoints="[https://uacl-test-labrador-test.ko.iszn.cz:31007]" etcdEndpoint="https://uacl-test-labrador-test.ko.iszn.cz:31007" subsys=kvstore version=3.5.4
level=info msg="Connection to remote cluster established" clusterName=uacl-test-labrador-test config=/www/sasanka/secrets/cilium/configs/uacl-test-labrador-test kvstoreErr="<nil>" kvstoreStatus= subsys=clustermesh
level=info msg="Established connection to remote etcd" clusterName=uacl-test-labrador-test config=/www/sasanka/secrets/cilium/configs/uacl-test-labrador-test kvstoreErr="<nil>" kvstoreStatus="etcd: 1/1 connected, lease-ID=10df847f53140be2, lock lease-ID=10df847f53140be7, has-quorum=true: https://uacl-test-labrador-test.ko.iszn.cz:31007 - 3.5.4" subsys=clustermesh
level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
```

### Anything else?

related slack thread https://cilium.slack.com/archives/C1MATJ5U5/p1672811968057149

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by oblazek**
On each reconnect we failed to release all references to the old Allocator, meaning it was not GCed properly, leaving out some parts still in memory -> resulting in a memleak.

By launching NewAllocator (a remote one) with `WithoutGC()` option we save a goroutine which is noop anyway (for the remote connection) and which was preventing the remoteAlloc to be released.

This commit fixes it.

Parca memory profile comparisons:
 
Master (before https://github.com/cilium/cilium/pull/23532 got merged) :
master1

With https://github.com/cilium/cilium/pull/23532 fixes:
PR-23532

After this fix:
fixed

Fixes: #22988
Fixes: #13446

```release-note
Fix memory leak caused on clustermesh reconnect.
```

Signed-off-by: Ondrej Blazek <ondrej.blazek@firma.seznam.cz>

### CODE REVIEW

**Comment by squeed** [comment]
This looks good to me, but the commit message could do with a re-write.

File: pkg/allocator/allocator.go [hunk 1]
```diff
@@ -389,10 +389,6 @@ func (a *Allocator) GetEvents() AllocatorEventChan {
 func (a *Allocator) Delete() {
 	close(a.stopGC)
 	a.mainCache.stop()
-
-	if a.events != nil {
-		close(a.events)
-	}
```
Comment (aditighag) [inline pkg/allocator/allocator.go:395]: This should've been cleaned up on L266 anyway in the `Close()` call so why move it outside of the `Delete()` function? Please mention the reasoning in the commit description.

File: pkg/identity/cache/allocator.go [hunk 2]
```diff
@@ -449,7 +453,7 @@ func (m *CachingIdentityAllocator) WatchRemoteIdentities(remoteName string, back
 		return nil, fmt.Errorf("error setting up remote allocator backend: %s", err)
 	}
 
-	remoteAlloc, err := allocator.NewAllocator(&key.GlobalIdentity{}, remoteAllocatorBackend, allocator.WithEvents(m.IdentityAllocator.GetEvents()))
+	remoteAlloc, err := allocator.NewAllocator(&key.GlobalIdentity{}, remoteAllocatorBackend, allocator.WithEvents(m.IdentityAllocator.GetEvents()), allocator.WithoutGC())
```
Comment (aditighag) [inline pkg/identity/cache/allocator.go:455]: What's the rationale of calling an allocator without GC? (Unfortunately, the existing code is super light on explanation for the GC part.)

On a related note, if an allocator is allocated without GC, then what does the stopping of the gc channel do in the `Delete()` - 

```
func (a *Allocator) Delete() {
	close(a.stopGC)
```

**Review by aditighag — COMMENTED** [review]
Great find! Couple of inline comments on the fix. 

The graphs are good as a before and after comparison, but they don't point to the objects leading to memory leak. Any chance you can attach a snippet of heap dump?
^^I echo Casey's comment.

This isn't a blocking comment for your PR, but I encourage code reviewers more familiar with this code path to think about unit/control/integration tests to proactively catch such regressions.

File: pkg/allocator/allocator.go (hunk 1 above)
Comment (oblazek) [reply pkg/allocator/allocator.go:395]: np,  so imho the right thing to do when closing the remoteCache would be to delete the whole remoteAllocator - i.e. running `remoteAlloc.Delete()` -- but the problem with that is that without moving this code outside it would close the event channel not owned by the remoteAlloc, but owned by the main `CachingIdentityAllocator`. This in fact breaks the event channel which is used to pass remoteIdentity events to the main allocator (and panics on writing to closed channel).

File: pkg/identity/cache/allocator.go (hunk 2 above)
Comment (oblazek) [reply pkg/identity/cache/allocator.go:455]: if the GC is enabled.. the code starts this go routine:
```
if !a.disableGC {
		go func() {
			select {
			case <-a.initialListDone:
			case <-time.After(option.Config.AllocatorListTimeout):
				log.Fatalf("Timeout while waiting for initial allocator state")
			}
			a.startLocalKeySync()
		}()
	}
```
which in fact starts this go routine:
```
go func(a *Allocator) {
		kvTimer, kvTimerDone := inctimer.New()
		defer kvTimerDone()
		for {
			if err := a.syncLocalKeys(); err != nil {
				log.WithError(err).Warning("Unable to run local key sync routine")
			}

			select {
			case <-a.stopGC:
				log.Debug("Stopped master key sync routine")
				return
			case <-kvTimer.After(option.Config.KVstorePeriodicSync):
			}
		}
	}(a)
```
if I do not stop the `stopGC` channel I have no way of stopping the goroutine which is the problematic part.

So the GC (and these goroutines) only makes sense for the local allocator (as they sync the local keys to the backend) but only for that (as there are no local keys for the remote backend).

File: pkg/identity/cache/allocator.go [hunk 3]
```diff
@@ -264,6 +264,10 @@ func (m *CachingIdentityAllocator) Close() {
 	}
 
 	m.IdentityAllocator.Delete()
+	if m.events != nil {
+		close(m.events)
+	}
```
Comment (giorio94) [inline pkg/identity/cache/allocator.go:268]: There is a potential issue here. The events channel gets initialized in the [`NewCachingIdentityAllocator` function](https://github.com/cilium/cilium/blob/master/pkg/identity/cache/allocator.go#L230-L241). According to the comments of the `Close` function, once it is executed, it should be possible to call `InitIdentityAllocator` again, which though uses the events channel. Hence, it would break, given that the channel would be closed.

~~It doesn't seem to me that `Close` is ever used outside of tests, so no actual difference should be noticed, still, I feel it might be better not to close that channel to better comply with the desired approach.~~

Edit: I missed [this usage](https://github.com/cilium/cilium/blob/8aa8dd5702f93b480d252702df632cd934650664/daemon/cmd/daemon.go#L1400); I adapted the comment based on that.

Comment (giorio94) [reply pkg/identity/cache/allocator.go:268]: I don't see any particularly clean ways for handling this (at the moment it does not lead to issues, since the allocator is never initialized again after having been closed). I wonder if the other code reviewers have any suggestion.

Comment (oblazek) [reply pkg/identity/cache/allocator.go:268]: yeah you are right about the comment, hmm.. if anybody sees a potential problem with this I can just revert this. The oneliner that fixes the memleak here is sufficient as well (`allocator.WithoutGC()`)

Comment (squeed) [reply pkg/identity/cache/allocator.go:268]: I think the code comment is moot; I see no evidence of Close() being called except for on daemon shutdown. I think we can just remove that comment and, if desired, panic on `InitIdentityAllocator` being called twice.

The real question: would this change be safe to backport? I'm checking.

Comment (squeed) [reply pkg/identity/cache/allocator.go:268]: In versions v1.13, v1.12, and v1.11, Close() isn't even called. So it's safe to say this comment is not useful.

**Review by aanm — COMMENTED** [review]
I'll defer my review to @giorio94

**Review by squeed — CHANGES_REQUESTED** [review]
Just need to change the docblock in CachingIdentityAllocator.Close() and this is good to go.

**Comment by giorio94** [comment]
> > Just need to change the docblock in CachingIdentityAllocator.Close() and this is good to go.
> 
> you also talked about rewriting the commit message.. any suggestion what to keep in/leave out?

I would personally suggest to also mention the reasoning behind changing the operations performed on `RemoteCache.Close`,  and the different handling of the events channel closure. Perhaps moving them in a separate commit with respect to the one introducing the `WithoutGC` option.

**Comment by oblazek** [comment]
> > > Just need to change the docblock in CachingIdentityAllocator.Close() and this is good to go.
> > 
> > 
> > you also talked about rewriting the commit message.. any suggestion what to keep in/leave out?
> 
> I would personally suggest to also mention the reasoning behind changing the operations performed on `RemoteCache.Close`, and the different handling of the events channel closure. Perhaps moving them in a separate commit with respect to the one introducing the `WithoutGC` option.

ok, sounds good.. let me split it into more commits

**Comment by oblazek** [comment]
I've split it into two commits and tried to explain the reasoning behind the changes. PTAL :)

**Review by giorio94 — APPROVED** [review]
/lgtm Thanks @oblazek

**Comment by giorio94** [comment]
I'm triaging the CI failures

**Comment by giorio94** [comment]
ConformanceGatewayAPI/ConformanceIngress hit https://github.com/cilium/cilium/issues/23960. Rerunning

**Comment by giorio94** [comment]
Rebasing, as ConformanceGatewayAPI checks fail due to a change in the parameters.

**Comment by giorio94** [comment]
Marked for backport to v1.13, as https://github.com/cilium/cilium/pull/23532

**Review by squeed — APPROVED** [review]

**Comment by sayboras** [comment]
While all required reviews are in, and CIs are all passed, I will wait for @aditighag to have a look at above comments before merging this one in.

**Review by aditighag — APPROVED** [review]
Thanks! Looks good for my code owners.

**Comment by aditighag** [comment]
@oblazek The release note in the commit description is missing. You can add something along these lines "Fix memory leak caused on clustermesh reconnect."
