### PR TITLE
bpf: ICMP checksum handling in SNAT RevNAT

### LINKED ISSUE #40827: Bug: ICMP error packets have incorrect checksum after SNAT RevNAT in LB-node
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.18.0 and lower than v1.19.0

### What happened?

ICMP error packets returned from LB's backend pod on other node have incorrect checksum after SNAT RevNAT in LB-node.
It occur when external-traffic-policy is cluster and LB mode is SNAT.

Image

How I think this error occurs is below.
- When SNAT RevNAT in LB-node, [snat_v4_rev_nat()](https://github.com/cilium/cilium/blob/1.18.0/bpf/lib/nat.h#L1041) is called.
- snat_v4_rev_nat() rewrite IP-address of inner-header in ICMP error packet's payload [by calling snat_v4_rev_nat_handle_icmp_error()](https://github.com/cilium/cilium/blob/1.18.0/bpf/lib/nat.h#L1117).
- [snat_v4_rev_nat_handle_icmp_error()](https://github.com/cilium/cilium/blob/1.18.0/bpf/lib/nat.h#L966) rewrite inner-header, but it doesn't rewrite ICMP header's checksum.
- After that, snat_v4_rev_nat()[ calls snat_v4_rewrite_headers()](https://github.com/cilium/cilium/blob/1.18.0/bpf/lib/nat.h#L1139) to rewrite outer-header.
- [snat_v4_rewrite_headers()](https://github.com/cilium/cilium/blob/1.18.0/bpf/lib/nat.h#L462) has some checksum update logic, but it doesn't correspond payload's update.(Only corresponding update of address or port.)

Note:
Currently, because [DNAT RevNAT of ICMP error is not supported](https://github.com/cilium/cilium/issues/32029), _the reply packet_(4 in above figure) cannot reach client correctly with or without this checksum bug.
(_The reply packet_ should have LB's VIP as saddr but currently it have backend pod's address as saddr.)
That might be why this bug wasn’t detected.

### How can we reproduce the issue?

Settings like above figure.

### Cilium Version

cilium image (running): 1.19.0-dev

### Kernel Version

6.8.0-60-generic

### Kubernetes Version

Client Version: v1.33.3
Kustomize Version: v5.6.0
Server Version: v1.29.0

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by yushoyamaguchi**
Fixes: https://github.com/cilium/cilium/issues/40827

When a LB node forwards packets to a backend-pod on another node,
the packets are SNATed.
The corresponding reverse NAT (RevNAT) is then applied
to the reply packets.

Checksum recaluculation is required when RevNAT.
When the reply packet is an ICMP error packet, the checksum
in the ICMP header must be recalculated to reflect the changes
of the inner packet header.
https://datatracker.ietf.org/doc/html/rfc5508#section-4.1

Since that logic was missing, it has been added in this commit.

The below is an error message of `nat4_icmp_error_tcp_snat_revnat` ([new test](https://github.com/cilium/cilium/pull/43196/commits/c4fff34f4e484af5328add58afff0f007a0ad002)) without the [checksum recalculate patch](https://github.com/cilium/cilium/pull/43196/commits/8495c0c5c063e2bd8c896e74f7d636f69666d18f).
<details><summary> <strong>An error message of RevNAT BPF-test</strong> </summary>

```
--- FAIL: TestBPF (39.66s)
--- FAIL: TestBPF/icmp_error_revnat.o (0.55s)
--- FAIL: TestBPF/icmp_error_revnat.o/nat4_icmp_error_tcp_snat_revnat (0.42s)

    bpf_test.go:577: icmp_error_revnat.c:137: CTX and buffer 'ICMP4_ERR_FRAG_NEEDED_AFTER_REVNAT' content mismatch 
    bpf_test.go:421:   Scapy asserts failed: 1
    bpf_test.go:428: 
        === START ./scapy.h:171 'icmp4_revnat_ok' ===
        >>> Expected (len: 164 bytes) <<<
        ###[ Ethernet ]### 
          dst       = 13:37:13:37:13:37
          src       = de:ad:be:ef:de:ef
          type      = IPv4
        ###[ IP ]### 
             version   = 4
             ihl       = 5
             tos       = 0x0
             len       = 68
             id        = 1
             flags     = 
             frag      = 0
             ttl       = 64
             proto     = icmp
             chksum    = 0xa60d
             src       = 192.168.0.2
             dst       = 10.0.10.1
             \options   \
        ###[ ICMP ]### 
                type      = dest-unreach
                code      = fragmentation-needed
                chksum    = 0xcbe5
                reserved  = 0
                length    = 0
                nexthopmtu= 1500
                unused    = ''
        ###[ IP in ICMP ]### 
                   version   = 4
                   ihl       = 5
                   tos       = 0x0
                   len       = 40
                   id        = 1
                   flags     = DF
                   frag      = 0
                   ttl       = 64
                   proto     = tcp
                   chksum    = 0x6624
                   src       = 10.0.10.1
                   dst       = 192.168.0.2
                   \options   \
        ###[ TCP in ICMP ]### 
                      sport     = 3030
                      dport     = http
                      seq       = 0
                      ack       = 0
                      dataofs   = 5
                      reserved  = 0
                      flags     = S
                      window    = 8192
                      chksum    = 0xaf11
                      urgptr    = 0
                      options   = ''
        
        >>> Got (len: 164 bytes) <<<
        ###[ Ethernet ]### 
          dst       = 13:37:13:37:13:37
          src       = de:ad:be:ef:de:ef
          type      = IPv4
        ###[ IP ]### 
             version   = 4
             ihl       = 5
             tos       = 0x0
             len       = 68
             id        = 1
             flags     = 
             frag      = 0
             ttl       = 64
             proto     = icmp
             chksum    = 0xa60d
             src       = 192.168.0.2
             dst       = 10.0.10.1
             \options   \
        ###[ ICMP ]### 
                type      = dest-unreach
                code      = fragmentation-needed
                chksum    = 0x788e
                reserved  = 0
                length    = 0
                nexthopmtu= 1500
                unused    = ''
        ###[ IP in ICMP ]### 
                   version   = 4
                   ihl       = 5
                   tos       = 0x0
                   len       = 40
                   id        = 1
                   flags     = DF
                   frag      = 0
                   ttl       = 64
                   proto     = tcp
                   chksum    = 0x6624
                   src       = 10.0.10.1
                   dst       = 192.168.0.2
                   \options   \
        ###[ TCP in ICMP ]### 
                      sport     = 3030
                      dport     = http
                      seq       = 0
                      ack       = 0
                      dataofs   = 5
                      reserved  = 0
                      flags     = S
                      window    = 8192
                      chksum    = 0xaf11
                      urgptr    = 0
                      options   = ''
        
        >>> Diff <<<
          --- a/pkt (Expected)
          +++ b/pkt (Got)
        
          - [ Ether ][ IP ][ ICMP ].chksum: 52197
          + [ Ether ][ IP ][ ICMP ].chksum: 30862
        
        === END ./scapy.h:171 'icmp4_revnat_ok' ===

┌──────────────────────────────────────────────────────────────────────────────────────────────┐
│  STATUS │ ELAPSED │                  PACKAGE                   │ COVER │ PASS │ FAIL │ SKIP  │
│─────────┼─────────┼────────────────────────────────────────────┼───────┼──────┼──────┼───────│
│  FAIL   │ 39.70s  │ github.com/cilium/cilium/bpf/tests/bpftest │  --   │ 594  │  3   │  0    │
└──────────────────────────────────────────────────────────────────────────────────────────────┘
```

</details>

```release-note
Fix ICMP error packet handling by adding the missing checksum recalculation performed during RevNAT for SNATed load-balanced traffic.
```

### CODE REVIEW

**Comment by yushoyamaguchi** [comment]
This fix is required before we support https://github.com/cilium/cilium/issues/32029.
In current implementation, even if we support https://github.com/cilium/cilium/issues/32029, reply ICMP error packet is not received because of the incorrect checksum.

**Comment by yushoyamaguchi** [comment]
@pchaigno @julianwiedmann 

Sorry for the delay.
Please review.

**Comment by pchaigno** [comment]
It looks like the CI may be failing because of https://github.com/cilium/cilium/issues/15474. You may need to rebase to pass.

File: bpf/lib/nat.h [hunk 1]
```diff
@@ -1074,10 +1126,25 @@ snat_v4_rev_nat_handle_icmp_error(struct __ctx_buff *ctx,
...
-	ret = snat_v4_rewrite_headers(ctx, tuple.nexthdr, (int)inner_l3_off, true, icmpoff,
-				      tuple.daddr, (*state)->to_daddr, IPV4_SADDR_OFF,
-				      tuple.dport, (*state)->to_dport, port_off);
+	ret = snat_v4_rewrite_icmp_error_headers(ctx, tuple.nexthdr, (int)inner_l3_off,
+						 true, icmpoff,
+						 tuple.daddr, (*state)->to_daddr, IPV4_SADDR_OFF,
+						 tuple.dport, (*state)->to_dport, port_off,
+						 outer_icmp_off,
+						 icmp_has_inner_l4_csum &&
+						 is_inner_l4_csum_enabled);
```
Comment (pchaigno) [inline bpf/lib/nat.h]: I'm unsure what our existing BPF tests (`bpf/tests/`) look for this, do we already have anything? Could we extend it to cover this change?

Comment (yushoyamaguchi) [reply bpf/lib/nat.h]: Sorry, I didn’t think about that.
I'll check if existing tests can testify my logic.

Comment (yushoyamaguchi) [reply bpf/lib/nat.h]: Do we need to verify the checksum in this test?
Currently, packets are being sent with an incorrect checksum, but all existing BPF tests are still passing.

Personally, I think that building a framework for checksum verification inside the BPF tests could be handled separately. Introducing checksum validation into the BPF tests would likely cause some of the existing code to start failing.

Comment (julianwiedmann) [reply bpf/lib/nat.h]: @msune recently added scapy support for BPF tests (https://github.com/cilium/cilium/pull/40294), I think that would be a perfect fit for validating these fixes. Could you please see if that's doable with a reasonable effort?

File: bpf/lib/nat.h [hunk 2]
```diff
@@ -528,6 +528,56 @@ snat_v4_rewrite_headers(struct __ctx_buff *ctx, __u8 nexthdr, int l3_off,
...
+		struct csum_offset csum = {
+			.offset = offsetof(struct icmphdr, checksum),
+			.flags = 0,
+		};
+		if (csum_l4_replace(ctx, outer_icmp_off, &csum, 0, diff_for_csum, 0) < 0)
+			return DROP_CSUM_L4;
+	}
+
+	return 0;
+}
```
Comment (julianwiedmann) [inline bpf/lib/nat.h]: (More as inspiration, this wouldn't necessarily need to happen as part of this PR)

Now that we have logic to calculate the `diff` that needs to be applied on the outer packet - can we hand this diff back to the caller, and have **them** apply it (as part of re-writing the outer headers) ? This would probably be an additional `csum_diff` parameter for `snat_v4_rewrite_headers()`.

Comment (yushoyamaguchi) [reply bpf/lib/nat.h]: Please let me confirm what you said.
You said that `snat_v4_rewrite_icmp_error_headers()` should just calculate `diff` for outer-header and pass it to `snat_v4_rev_nat_handle_icmp_error()` , then `snat_v4_rev_nat_handle_icmp_error()` apply the `diff` to outer-header, right?

Comment (yushoyamaguchi) [reply bpf/lib/nat.h]: How is `snat_v4_rewrite_headers()` related to your plan?
I guess  `snat_v4_rewrite_headers()` is for rewriting inner-header, not outer-header.

Comment (julianwiedmann) [reply bpf/lib/nat.h]: > Please let me confirm what you said.
> You said that `snat_v4_rewrite_icmp_error_headers()` should just calculate `diff` for outer-header and pass it to `snat_v4_rev_nat_handle_icmp_error()` , then `snat_v4_rev_nat_handle_icmp_error()` apply the `diff` to outer-header, right?

The picture I have in my head is that `snat_v4_rev_nat_handle_icmp_error()` modifies the inner headers, and as part of doing so calculates the resulting `diff`. It then reports this `diff` back to `snat_v4_rev_nat()`, which forwards it to `snat_v4_rewrite_headers()`. There the `diff` is mixed into the rewrite of the outer L4 header's `csum` field.

This for instance would allow us to avoid the additional special-casing for UDP - the outer layer will already check for this, and skip the L4 csum update accordingly.

Comment (yushoyamaguchi) [reply bpf/lib/nat.h]: @julianwiedmann 
I've understood. Thank you!
I've fixed.

File: bpf/lib/nat.h (hunk 1 above)
Comment (yushoyamaguchi) [reply bpf/lib/nat.h]: Please let me check whether my understanding of checksum verification in BPF tests that use scapy is correct.

By using `ASSERT_CTX_BUF_OFF`, we can compare the checksum field of a packet produced by Cilium’s BPF functions with the checksum field of the packet generated on the scapy side, right?

If that’s the case, then simply switching the SNAT-RevNAT tests to use scapy-generated packets should already allow us to automatically verify the checksum as well, right?

Comment (msune) [reply bpf/lib/nat.h]: `ASSERT_CTX_BUF_OFF()` compares the CTX contents with a scapy buffer, see:

https://github.com/cilium/cilium/blob/3ab1b9a54fa0e0e1b977025302ff9199f4af366d/bpf/tests/scapy.h#L234

It is meant to be used to compare entire packets, or the first part of it (`LEN`). Scapy - unless explicitely set - calculates and fills in L3 and L4 checksum.

So yes, using that assert will validate the checksum. Mind some unit tests store the return code in the first 4bytes of CTX.

I suggest you to read and follow this guide to port the test to scapy:

https://github.com/cilium/cilium/tree/main/bpf/tests/scapy#how-to-port-or-write-your-first-unit-test-with-scapy-buffers

Comment (yushoyamaguchi) [reply bpf/lib/nat.h]: @msune cc @julianwiedmann 
Okay, thank you!

https://github.com/cilium/cilium/blob/2c59ba7dfaa5065e3b71814b97be7d217e07cda3/bpf/tests/bpf_nat_tests.c
There are already many tests cases for validating `snat_v4_rev_nat()`.
- Should I rewrite these existing test cases to use _scapy_?
- Or is it sufficient for me to simply add new a test case that use _scapy_?
<br>
Is there any motivation or long-term direction to gradually replace the existing test cases with scapy-based ones?

Comment (yushoyamaguchi) [reply bpf/lib/nat.h]: @julianwiedmann   @msune 
I've implemented a new test case using scapy and I've confirmed this test case could also validate checksum.
Please review.

**Comment by pchaigno** [comment]
You'll need to address the warning from Check Patch. The two other failures look like flakes.

File: bpf/tests/icmp_error_revnat.c [hunk 3]
```diff
@@ -0,0 +1,140 @@
...
+#include <lib/nat.h>
+#include <lib/time.h>
+
+#include "bpf_nat_tuples.h"
+#include "scapy.h"
+
+/* IP addresses mapping to Scapy definitions (in host byte order):
+ * v4_node_one   = "10.0.10.1"  -> IP_HOST (the node being tested)
+ * v4_node_two   = "10.0.10.2"  -> IP_ROUTER (router sending ICMP error)
+ * v4_ext_one    = "110.0.11.1" -> IP_ENDPOINT (external endpoint)
```
Comment (julianwiedmann) [inline bpf/tests/icmp_error_revnat.c]:
```suggestion
 * v4_pod_one    = "110.0.11.1" -> IP_ENDPOINT
```

Since this is supposed to be a local endpoint that requires masquerading on egress, calling it "external" feels very confusing to me.

File: bpf/lib/nat.h [hunk 4]
```diff
@@ -523,11 +524,46 @@ snat_v4_rewrite_headers(struct __ctx_buff *ctx, __u8 nexthdr, int l3_off,
...
+	} else {
+		/* Calculate diff value for checksum.
+		 * If the inner L4 header does not include the L4 checksum,
+		 * only the port is modified within the inner L4 header.
+		 */
+		if (old_port != new_port)
+			*diff_for_csum = csum_diff(&old_port32, 4, &new_port32, 4, 0);
+	}
+}
+
```
Comment (julianwiedmann) [inline bpf/lib/nat.h:570]: I think eventually we'll want to integrate this logic into `snat_v4_rewrite_headers()` (so it literally tells the caller what csum-relevant changes it made, and the caller can then feed that information into the next stage of header rewrites). But not today.

:exploding_head: for the "truncated L4" scenario, this is such an annoying corner case to handle ...

File: bpf/lib/nat.h [hunk 5]
```diff
@@ -523,11 +524,46 @@ snat_v4_rewrite_headers(struct __ctx_buff *ctx, __u8 nexthdr, int l3_off,
 		if (csum.offset &&
 		    csum_l4_replace(ctx, l4_off, &csum, 0, sum, flags) < 0)
 			return DROP_CSUM_L4;
+
+		/* Apply additional L4 checksum diff if provided (for ICMP error messages). */
+		if (l4_csum_diff_from_inner && !csum.offset) {
+			csum.offset = offsetof(struct icmphdr, checksum);
+			if (csum_l4_replace(ctx, l4_off, &csum, 0, l4_csum_diff_from_inner, 0) < 0)
+				return DROP_CSUM_L4;
+		}
```
Comment (julianwiedmann) [inline bpf/lib/nat.h:537]: For the future - I wonder whether we can integrate this with the `l4_modify_port()` path.

File: bpf/lib/nat.h (hunk 1 above)
Comment (julianwiedmann) [reply bpf/lib/nat.h]: Awesome, thank you! You could even quote the test's error output (without your fix) in the patch description.

**Review by julianwiedmann — COMMENTED** [review]
Thank you! Looks good to me overall - I added a few comments, although I think we shouldn't attempt to optimize the logic further for now. Let's do that once we have addressed the bug.

One aspect I'd still want to confirm is what the effect on `skb->csum` is. Not sure whether we can easily validate that from within the BPF test suite today.

File: bpf/tests/scapy/icmp_err_pkt_defs.py [hunk 6]
```diff
@@ -0,0 +1,61 @@
+# Copyright Authors of Cilium
+# SPDX-License-Identifier: Apache-2.0
+
+from scapy.all import *
+
+from pkt_defs_common import *
+
+icmp4_frag_needed = (
+    Ether(
```
Comment (msune) [inline bpf/tests/scapy/icmp_err_pkt_defs.py]: We don't have a linter here, but can you please use the same format as in here for consistency:

https://github.com/yushoyamaguchi/cilium/blob/142715dab600d1be8c456dd345326f6811d4df11/bpf/tests/scapy/tc_l2_announce_pkt_defs.py#L9-L12

That is, generally one Layer per line with all fields there.

File: bpf/tests/scapy/pkt_defs.py [hunk 7]
```diff
@@ -11,3 +11,4 @@
 from tc_l2_announce_pkt_defs import *
 from tc_l2_announce6_pkt_defs import *
 from wg_from_netdev_pkt_defs import *
+from icmp_err_pkt_defs import *
```
Comment (msune) [inline bpf/tests/scapy/pkt_defs.py]: Very long but since this is specific to revnat only:

`icmp_err_revnat_pkt_defs.py`

File: bpf/tests/icmp_error_revnat.c [hunk 8]
```diff
@@ -0,0 +1,140 @@
...
+ *            with embedded packet showing original src (110.0.11.1:3030)
+ */
+PKTGEN("tc", "nat4_icmp_error_tcp_snat_revnat")
+int nat4_icmp_error_tcp_snat_revnat_pktgen(struct __ctx_buff *ctx)
+{
+	struct pktgen builder;
+	pktgen__init(&builder, ctx);
+
+	/* Use Scapy-generated ICMP error packet */
+	BUF_DECL(ICMP4_FRAG_NEEDED, icmp4_frag_needed);
```
Comment (msune) [inline bpf/tests/icmp_error_revnat.c]: `ICMP4_FRAG_NEEDED` is a rather generic name. Buffer name (today), are global. I'd suggest something more specific to this test.

File: bpf/tests/icmp_error_revnat.c [hunk 9]
```diff
@@ -0,0 +1,140 @@
...
+	status_code = data;
+
+	/* Verify SETUP succeeded */
+	if (*status_code != TEST_PASS)
+		test_fatal("SETUP failed with status code: %d", *status_code);
+
+	/* Compare the packet with expected output after rev-NAT.
+	 * Note: offset sizeof(__u32) to skip the return code prepended by framework.
+	 */
+	BUF_DECL(EXPECTED_PKT, icmp4_frag_needed_after_revnat);
```
Comment (msune) [inline bpf/tests/icmp_error_revnat.c]: Same thing here: `EXPECTED_PKT` is too generic. Prefix with the test name.

**Review by msune — CHANGES_REQUESTED** [review]
I only reviewed the Scapy part. Overall LGTM. Minor changes to style + naming required.

Thanks!

File: bpf/lib/nat.h (hunk 1 above)
Comment (yushoyamaguchi) [reply bpf/lib/nat.h]: After I fix the test case to address your feedback, I'll put the error message into this patch!

File: bpf/tests/icmp_error_revnat.c (hunk 3 above)
Comment (yushoyamaguchi) [reply bpf/tests/icmp_error_revnat.c]: @julianwiedmann 
I used inappropriate IP addresses for SNAT RevNAT in this test.
I've fixed.
Now, IP addresses of **outer** header are shown below.
- Before SNAT Revnat-> src: `pod_two`, dst: `pod_one`
- After SNAT Revnat(Expected)-> src: `pod_two`, dst: `node_one`

Is it appropriate?

Comment (yushoyamaguchi) [reply bpf/tests/icmp_error_revnat.c]: Actual packet in my kind cluster

Before RevNAT
スクリーンショット 2026-01-10 113650

After RevNAT
スクリーンショット 2026-01-10 113727

File: bpf/lib/nat.h (hunk 1 above)
Comment (yushoyamaguchi) [reply bpf/lib/nat.h]: @julianwiedmann 
I've added! 
https://github.com/cilium/cilium/pull/43196#issue-3703588614

**Review by julianwiedmann — APPROVED** [review]
Thank you, looks good to me!

So as follow-up actions, we'd want to
1. add more scapy tests (IPv4 and IPv6),
2. fix up the forward path (`snat_v4_nat_handle_icmp_error()`),
3. look at the suggested optimizations

**Comment by julianwiedmann** [comment]
> One aspect I'd still want to confirm is what the effect on skb->csum is. Not sure whether we can easily validate that from within the BPF test suite today.

for the record - the additional `l4_csum_replace()` call also affects `skb->csum`. But that's exactly what we need - it matches our update to the outer L4 header's `csum` field.

**Comment by msune** [comment]
@julianwiedmann should this be backported?

**Comment by julianwiedmann** [comment]
@yushoyamaguchi would you want to give the `v1.18` backport a try? We don't have scapy there, so it would be landing without a test ...

**Comment by yushoyamaguchi** [comment]
@julianwiedmann 

Thank you for your suggestion!
If it is okay to _backport_ this  to `v1.18` without test, I want to try.

To confirm the process: 
- create a branch off `v1.18`.
- cherry-pick the checksum fix commit.
- open a PR back to `v1.18`. 

Does that sound good?

**Comment by julianwiedmann** [comment]
> @julianwiedmann
> 
> Thank you for your suggestion! If it is okay to _backport_ this to `v1.18` without test, I want to try.
> 
> To confirm the process:
> 
>     * create a branch off `v1.18`.
> 
>     * cherry-pick the checksum fix commit.
> 
>     * open a PR back to `v1.18`.
> 
> 
> Does that sound good?

yep sounds good! There's full documentation [here](https://docs.cilium.io/en/stable/contributing/release/backports/#backporting-guide-for-the-backporter) as well.

**Comment by yushoyamaguchi** [comment]
@julianwiedmann 

I've made https://github.com/cilium/cilium/pull/43861.

There is no `bpf-test` to check the effect of this patch in `v1.18`, but I confirmed that cilium built from [this version](https://github.com/cilium/cilium/pull/43861/commits) works correctly about RevSNAT checksum in my KinD cluster

**Comment by julianwiedmann** [comment]
> So as follow-up actions, we'd want to
> 
>     1. add more scapy tests (IPv4 and IPv6),
> 
>     2. fix up the forward path (`snat_v4_nat_handle_icmp_error()`),
> 
>     3. look at the suggested optimizations

@yushoyamaguchi :wave: I noticed that we didn't take action on any of these. Would you have interest in fixing up the other ICMP paths - or should we open an issue to track those bugs / missing tests?

**Comment by yushoyamaguchi** [comment]
@julianwiedmann 

I'm currently busy with other PRs and probably won't have time to work on the issues above for a while. I'm sorry.

**Comment by julianwiedmann** [comment]
> @julianwiedmann
> 
> I'm currently busy with other PRs and probably won't have time to work on the issues above for a while. I'm sorry.

Opened https://github.com/cilium/cilium/issues/48291.
