### PR TITLE
CI: Fixed TestPodCIDRAllocatorOverlap

### LINKED ISSUE #21956: CI: TestPodCIDRAllocatorOverlap
The TestPodCIDRAllocatorOverlap test seems to be flakey.

https://app.travis-ci.com/github/cilium/cilium/jobs/587084359

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃   FAIL  package: github.com/cilium/cilium/operator/cmd   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
--- FAIL: TestPodCIDRAllocatorOverlap (2.10s)
                                             
Run 1/5
level=info msg="Starting to synchronize CiliumNode custom resources" subsys=cmd.test
level=info msg="CiliumNodes caches synced with Kubernetes" subsys=cmd.test
    allocator_test.go:152: Node A has no PodCIDRs
```

This test mocks out the API server in order to test that the Pod CIDR allocator doesn't assign overlapping pod CIDRs when initialing(a regression test). The test currently uses a timeout, if the allocator hasn't updated the CiliumNode objects in the mocked API server when it expires, this error will appear. 

We should replace this timeout mechanism with a positive signal so we known when the allocator is done, which should be more robust.

### PR DESCRIPTION
**Pull request by dylandreimerink**
Added an extra channel to the Pod CIDR allocator which is triggered after each resync. The `TestPodCIDRAllocatorOverlap` test has been updated to block on this channel three times which is when it is done syncing all changes to the API server.

Fixed: #21956

```release-note
Made the `TestPodCIDRAllocatorOverlap` test more robust
```

### CODE REVIEW

File: operator/cmd/allocator_test.go [hunk 1]
```diff
@@ -128,11 +96,15 @@ func podCIDRAllocatorOverlapTestRun(t *testing.T) {
...
+	<-podCidrManager.K8sReSyncChan
+
 	// Trigger the Resync after the cache sync signal
 	podCidrManager.Resync(ctx, time.Time{})
 
-	// Now wait until the APIServer state is stable
-	<-updated
+	// Now wait for two resync events, after which the API server is in sync
+	<-podCidrManager.K8sReSyncChan
+	<-podCidrManager.K8sReSyncChan
```
Comment (gandro) [inline operator/cmd/allocator_test.go]: Why do we expect two resyncs here?

Instead of relying on those notification that seem to rely in implementation behavior, could we change this unit test to just poll the mock APIServer and wait for changes, e.g. using [`testutils.WaitUntil`](https://github.com/cilium/cilium/blob/314ca7baeff4f568ffc0bad95124e40665b1f88c/pkg/testutils/condition.go#L19)

Comment (dylandreimerink) [reply operator/cmd/allocator_test.go]: I am not 100% on which event is triggered by which code path, this turned out to work experimentally. It gets a bit muddy since [syncNode](https://github.com/cilium/cilium/blob/6d561885ba40364491122cbc5ca92d54f09b808a/pkg/ipam/allocator/podcidr/podcidr.go#L576) also triggers the k8sReSync which itself is called at a number of locations. 

> could we change this unit test to just poll the mock APIServer and wait for changes

This is what the code did that I am currently replacing. You have to have a timeout when you give up, it is hard to set such a timeout since time seems to warp in the CI due to congestion(I suspect we get way less cpu cycles per second, so we start missing timeouts that otherwise make sense). This is an attempt to have a trigger that isn't based on time.

Though I have to agree that this is not ideal in case the implementation ever changes. :sigh:. I am starting to think that we should just remove this test all together, it is costing way to many cycles than it is worth.

Comment (gandro) [reply operator/cmd/allocator_test.go]: I agree that this is incredibly hard to test.

Could we simplify it, i.e. not trying to wait for the API server to become stable or observe resyncs. Instead, just poll nodeA and nodeB until they have the expected state (or fail if we detect an overlap)? Or would that never uncover the bug fixed by your previous PR?

Comment (gandro) [reply operator/cmd/allocator_test.go]: To be a bit more precise, I envision something along the lines of:

```go
	// Wait for the "node manager synced" signal, just like we would normally.
	<-ciliumNodeManagerQueueSynced

	// Trigger the Resync after the cache sync signal
	podCidrManager.Resync(ctx, time.Time{})

	err := testutils.WaitUntil(func() bool {
		// Get node A from the mock APIServer
		nodeAInt, err := fakeClient.Tracker().Get(ciliumnodesResource, "", "node-a")
		if err != nil {
			return false
		}
		nodeA := nodeAInt.(*cilium_api_v2.CiliumNode)

		// Get node B from the mock APIServer
		nodeBInt, err := fakeClient.Tracker().Get(ciliumnodesResource, "", "node-b")
		if err != nil {
			return false
		}
		nodeB := nodeBInt.(*cilium_api_v2.CiliumNode)

		if len(nodeA.Spec.IPAM.PodCIDRs) != 1 {
			return false
		}

		if len(nodeB.Spec.IPAM.PodCIDRs) != 1 {
			return false
		}

		// The PodCIDRs should be distinct.
		if nodeA.Spec.IPAM.PodCIDRs[0] == nodeB.Spec.IPAM.PodCIDRs[0] {
			t.Fatal("Node A and Node B are assigned overlapping PodCIDRs")
		}
		
		return true
	}, 2*time.Minute)
	if err != nil {
		t.Fatalf("nodes have no pod CIDR: %s", err)
	}
```

**Review by aanm — COMMENTED** [review]
I'll default to Sebastian's review

File: operator/cmd/allocator_test.go (hunk 1 above)
Comment (dylandreimerink) [reply operator/cmd/allocator_test.go]: I don't know if you tested this before hand, but it works beautifully. Drop in replacement!

**Review by gandro — APPROVED** [review]

**Comment by gandro** [comment]
Marking this ready to merge. This only touches unit test code and the corresponding unit test is green, no point in running the full CI suite: https://app.travis-ci.com/github/cilium/cilium/jobs/587588447#L537

This should hopefully improve stability of the affected test.
