### PR TITLE
daemon: listen on IPv4 and IPv6 for health endpoint

### LINKED ISSUE #13165: Health endpoint does not bind to tcp6 on a IPv6 only environment
## Bug report

**General Information**

- Cilium version 1.8.3
- Kernel version 5.8.7
- Kubernetes 1.19.1
- [cilium-sysdump-20200914-131007.zip](http://talpidae.net/~jonas.zeiger/public/paste/cilium-sysdump-20200914-131007.zip)

**How to reproduce the issue**

1. Install K8s 1.19.1 using kubeadm with IPv6 only, skipping addon/kube-proxy
2. Install cilium 1.8.3 using the attached config
3. Monitor logs and READY state of "cilium" pod
  * issue: cilium never becomes READY, health endpoint restarting endlessly
4. Create a pod like this and try to "ping6" your default gateway by IP (IPv6)
  * issue: connections or pings to nodes outside the cluster not possible, even if IP ranges are fully routable

### PR DESCRIPTION
**Pull request by tklauser**
If the agent liveness/readiness probe host is set to the IPv6 address
`::1` instead of the default IPv4 `127.0.0.1`, Cilium never becomes ready in
an IPv6-only environment. This is because the daemon health endpoint
currently listens on `localhost:9876` which will not listen on both IPv4
and IPv6.

To fix this, listen on both IPv4 and IPv6 explicitly (depending on the
daemon's `enable-ipv{4,6}` flags) and only fail with an error if both of
them fail or one was disabled and the other one fails.

Also change liveness and readiness probes to perform the requests on `127.0.0.1` or `::1` depending on the `enable-ipv4` flag as suggested in https://github.com/cilium/cilium/issues/13165#issuecomment-694086544.

Fixes #13165

```release-note
Fix agent liveness/readiness probes for IPv6-only environment.
```

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
Manually tested in the dev VM as follows:
  
1. IPv4 and IPv6:

```
# check that lo interface has both IPv4 and IPv6 address
$ ip addr show lo
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
$ sudo journalctl -u cilium | grep "healthz status API server"
Sep 17 10:25:10 runtime1 cilium-agent[16392]: level=info msg="Started healthz status API server on address 127.0.0.1:9876" subsys=daemon
Sep 17 10:25:10 runtime1 cilium-agent[16392]: level=info msg="Started healthz status API server on address [::1]:9876" subsys=daemon
$ curl -I 127.0.0.1:9876/healthz
HTTP/1.1 200 OK
Date: Thu, 17 Sep 2020 10:44:13 GMT
$ curl -I [::1]:9876/healthz
HTTP/1.1 200 OK
Date: Thu, 17 Sep 2020 10:44:34 GMT
```

2. IPv4 only:
```
# disable IPv6 address on lo interface
$ sudo ip addr del ::1/128 dev lo
$ ip addr show lo
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
$ sudo systemctl restart cilium
$ sudo journalctl -u cilium | grep "healthz status API server"
Sep 17 10:49:09 runtime1 cilium-agent[24453]: level=info msg="Started healthz status API server on address 127.0.0.1:9876" subsys=daemon
Sep 17 10:49:09 runtime1 cilium-agent[24453]: level=info msg="healthz status API server not available on [::1]:9876" subsys=daemon
$ curl -I 127.0.0.1:9876/healthz
HTTP/1.1 200 OK
Date: Thu, 17 Sep 2020 10:49:46 GMT
$ curl -I [::1]:9876/healthz
curl: (7) Couldn't connect to server
```

3. IPv6 only:

Currently, Cilium fails to come up propery if the lo interface is IPv6 only.

**Review by aanm — APPROVED** [review]
:100:

File: daemon/cmd/agenthealth.go [hunk 1]
```diff
@@ -73,18 +77,37 @@ func (d *Daemon) startAgentHealthHTTPService(addr string) {
...
+		lc := net.ListenConfig{Control: setsockoptReuseAddrAndPort}
+		addr := net.JoinHostPort(host, fmt.Sprintf("%d", port))
+		ln, err := lc.Listen(context.Background(), "tcp", addr)
+		if errors.Is(err, unix.EADDRNOTAVAIL) {
+			log.Infof("healthz status API server not available on %s", addr)
+			available--
+			continue
 		} else if err != nil {
-			log.WithError(err).Fatal("Unable to start healthz status API server")
+			log.WithError(err).Fatalf("Unable to listen on %s for healthz status API server", addr)
```
Comment (sayboras) [inline daemon/cmd/agenthealth.go]: will log.Fatalf here will lead to exit(1) here? If yes, the loop might not continue.

File: daemon/cmd/agenthealth.go [hunk 2]
```diff
@@ -73,18 +77,37 @@ func (d *Daemon) startAgentHealthHTTPService(addr string) {
...
+		go func(addr string, ln net.Listener) {
+			srv := &http.Server{
+				Addr:    addr,
+				Handler: mux,
+			}
+			err := srv.Serve(ln)
+			if errors.Is(err, http.ErrServerClosed) {
+				log.Info("healthz status API server shutdown")
+			} else if err != nil {
+				log.WithError(err).Fatal("Unable to start healthz status API server")
```
Comment (sayboras) [inline daemon/cmd/agenthealth.go]: available-- here? so that main thread will throw error as well ?

File: daemon/cmd/agenthealth.go [hunk 3]
```diff
@@ -73,18 +77,37 @@ func (d *Daemon) startAgentHealthHTTPService(addr string) {
...
+			}
+		}(addr, ln)
+		log.Infof("Started healthz status API server on address %s", addr)
```
Comment (sayboras) [inline daemon/cmd/agenthealth.go]: should this log inside goroutine ?

**Review by sayboras — COMMENTED** [review]
We have conformance test with ipv6 only cluster, just curious why underlying issue happened :thinking:

File: daemon/cmd/agenthealth.go (hunk 3 above)
Comment (tklauser) [reply daemon/cmd/agenthealth.go]: Same here, `srv.Serve` in the goroutine blocks, so we wouldn't see this message until the server exits.

File: daemon/cmd/agenthealth.go (hunk 2 above)
Comment (tklauser) [reply daemon/cmd/agenthealth.go]: The call to `srv.Serve` will block and only return once the HTTP server exits, which I think should lead to a `Fatal` which exits the process.

File: daemon/cmd/agenthealth.go (hunk 1 above)
Comment (tklauser) [reply daemon/cmd/agenthealth.go]: Yes, and since it is an unexpected error (the only one we expect is `EADDRNOTAVAIL`) I'd say it is fine to `exit(1)`. This was already the case before.

**Comment by tklauser** [comment]
Thanks for your review @sayboras 

> We have conformance test with ipv6 only cluster, just curious why underlying issue happened thinking

Just a guess, maybe because the helm chart was always hard-coding `127.0.0.1` and likely the `lo` interface in the ipv6 cluster still has IPv4 configured? I see the PR is currently failing on that GH action, so I will try to replicate and investigate further in a local `kind` cluster.

**Comment by sayboras** [comment]
I have checked the log in smoketest ipv6 failure, and notice below log, seems like newly built docker image was not used. Fixed in https://github.com/cilium/cilium/pull/13204 

```
2020-09-17T11:40:22.747698085Z level=info msg="Started healthz status API server on address localhost:9876" subsys=daemon
```

**Comment by tklauser** [comment]
> I have checked the log in smoketest ipv6 failure, and notice below log, seems like newly built docker image was not used. Fixed in #13204
> 
> ```
> 2020-09-17T11:40:22.747698085Z level=info msg="Started healthz status API server on address localhost:9876" subsys=daemon
> ```

Thanks, will rebase this PR once #13204 is approved and merged.

File: daemon/cmd/agenthealth.go (hunk 1 above)
Comment (sayboras) [reply daemon/cmd/agenthealth.go]: in this case, `continue` in next line can be removed to avoid any confusion?

**Comment by sayboras** [comment]
> Just a guess, maybe because the helm chart was always hard-coding 127.0.0.1 and likely the lo interface in the ipv6 cluster still has IPv4 configured?

You are right, thanks :100: 

```
$ ksysex cilium-gsws6 -- /bin/bash      
root@kind-worker:/home/cilium# ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
```

File: daemon/cmd/agenthealth.go [hunk 4]
```diff
@@ -46,14 +47,17 @@ func setsockoptReuseAddrAndPort(network, address string, c syscall.RawConn) erro
...
-func (d *Daemon) startAgentHealthHTTPService(addr string) {
-	lc := net.ListenConfig{Control: setsockoptReuseAddrAndPort}
-	ln, err := lc.Listen(context.Background(), "tcp", addr)
-	if err != nil {
-		log.WithError(err).Fatalf("Unable to listen on %s for healthz status API server", addr)
+// startAgentHealthHTTPService registers a handler function for the /healthz status HTTP endpoint
+// exposed on localhost (127.0.0.1 and/or ::1, depending on the values of ipv4 and ipv6). This
+// endpoint reports the agent health status and is equivalent to what the `cilium status --brief`
+// CLI tool reports.
+func (d *Daemon) startAgentHealthHTTPService(port int, ipv4, ipv6 bool) {
```
Comment (vadorovsky) [inline daemon/cmd/agenthealth.go]: nit: Maybe we can import and use `options` directly instead of passing options as arguments?

**Review by vadorovsky — COMMENTED** [review]
#13204 is merged, you can rebase now :)

File: install/kubernetes/cilium/charts/agent/templates/daemonset.yaml [hunk 5]
```diff
@@ -64,7 +64,11 @@ spec:
             - --brief
 {{- else }}
           httpGet:
+{{- if .Values.global.ipv4.enabled }}
```
Comment (sayboras) [inline install/kubernetes/cilium/charts/agent/templates/daemonset.yaml:67]: For dual stack, only ipv4 endpoint /healthz is used, so do we need to bring up both endpoints :)?

As per https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#httpgetaction-v1-core, can we just get rid of `host` attribute ?

> Host name to connect to, defaults to the pod IP. You probably want to set "Host" in httpHeaders instead.

**Review by sayboras — APPROVED** [review]
LGTM, few questions for my understanding only.

File: daemon/cmd/agenthealth.go (hunk 1 above)
Comment (tklauser) [reply daemon/cmd/agenthealth.go]: Good point, done.

File: daemon/cmd/agenthealth.go (hunk 4 above)
Comment (tklauser) [reply daemon/cmd/agenthealth.go]: The idea was to decouple the `(d *Daemon) startAgentHealthHTTPService` from from `pkg/options` in order to make it easier to re-factor and re-use in the future. But I guess this is so tightly coupled to the daemon anyway that it doesn't matter. Changed to use `pkg/option` and also take `AgentHealthPort` from there.

File: install/kubernetes/cilium/charts/agent/templates/daemonset.yaml (hunk 5 above)
Comment (tklauser) [reply install/kubernetes/cilium/charts/agent/templates/daemonset.yaml:67]: > For dual stack, only ipv4 endpoint /healthz is used, so do we need to bring up both endpoints :)?

We can't tell from the agent beforehand in which way users will be checking the endpoint (we have no access to the helm chart AFAIK), so the only way we have are the `--enable-ipv{4,6}` flags to decide which endpoints to bring up. These are already considered. Maybe we could change the agent options in the helm chart accordingly.

> As per https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#httpgetaction-v1-core, can we just get rid of `host` attribute ?
> 
> > Host name to connect to, defaults to the pod IP. You probably want to set "Host" in httpHeaders instead.

I'll look into that and send a follow-up PR if applicable.

**Comment by tklauser** [comment]
test-me-please

**Review by christarazi — APPROVED** [review]

**Comment by tklauser** [comment]
retest-net-next

**Review by vadorovsky — APPROVED** [review]

File: daemon/cmd/agenthealth.go [hunk 6]
```diff
@@ -73,18 +78,36 @@ func (d *Daemon) startAgentHealthHTTPService(addr string) {
...
+				Handler: mux,
+			}
+			err := srv.Serve(ln)
+			if errors.Is(err, http.ErrServerClosed) {
+				log.Info("healthz status API server shutdown")
+			} else if err != nil {
+				log.WithError(err).Fatalf("Unable to start healthz status API server on address %s", addr)
+			}
+		}(addr, ln)
+		log.Infof("Started healthz status API server on address %s", addr)
```
Comment (joestringer) [inline daemon/cmd/agenthealth.go]: These logs should use structured logging, not the format variant on the logger. For example, `log.WithFields(...).Info(...)`, not `log.Infof(...)`.

Ideally all of the above should include the address in the logfields so that if there's multiple served then the logs are not duplicated, but have different parameters.

**Review by joestringer — CHANGES_REQUESTED** [review]
Docs LGTM.

Please avoid format variants on logging functions in favour of structured logging.

File: daemon/cmd/agenthealth.go (hunk 6 above)
Comment (tklauser) [reply daemon/cmd/agenthealth.go]: Good point, thanks. Changed these to use `log.WithFields(...).Info(...)`.

**Comment by tklauser** [comment]
test-me-please
