### PR TITLE
test: Increase timeout on privileged unit tests

### LINKED ISSUE #12862: CI: RuntimePrivilegedUnitTests Run Tests: Context deadline exceeded
Example job: https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/1533/testReport/junit/(root)/Suite-runtime/RuntimePrivilegedUnitTests_Run_Tests/
[f651de81_RuntimePrivilegedUnitTests_Run_Tests.zip](https://github.com/cilium/cilium/files/5066472/f651de81_RuntimePrivilegedUnitTests_Run_Tests.zip)

Previously ran the tests with 3 lines BPF code changed and it passed. Now it has failed. Seems maybe timing related, perhaps recently-introduced privileged tests have put the privileged test runtime closer to some limit?

### Stacktrace
```
/home/jenkins/workspace/Cilium-PR-Runtime-4.9/runtime-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
Failed to run privileged unit tests
Expected command: sudo make -C /home/vagrant/go/src/github.com/cilium/cilium/ tests-privileged 
To succeed, but it failed:
Exitcode: 1 
Err: context deadline exceeded
...
```

### PR DESCRIPTION
**Pull request by pchaigno**
Flakes on privileged unit tests with `context deadline exceeded` are becoming a bit more common. There seem to be [a lot of variations](https://github.com/cilium/cilium/issues/12862#issuecomment-674085848) in actual duration of those tests, with a long tail of high durations.

This pull request doubles the timeout value in an effort to reduce flakes.

Fixes: #12862

### CODE REVIEW

**Comment by pchaigno** [comment]
retest-runtime

File: test/runtime/privileged_tests.go [hunk 1]
```diff
@@ -29,7 +29,7 @@ import (
 const (
 	// The privileged unit tests can take more than 4 minutes, the default
 	// timeout for helper commands.
-	privilegedUnitTestTimeout = 8 * time.Minute
+	privilegedUnitTestTimeout = 16 * time.Minute
```
Comment (rolinh) [inline test/runtime/privileged_tests.go:32]: :scream:

**Review by nebril — APPROVED** [review]
I am OK with merging that, but I wonder what would be the best way to track these spikes in execution, so we don't just increase timeouts ad infinitum.

File: test/runtime/privileged_tests.go (hunk 1 above)
Comment (pchaigno) [reply test/runtime/privileged_tests.go:32]: :shrug: It unlikely to increase the test duration on average since we never get "stuck" in unit tests and outliers with high duration are rare (although annoying).

> I wonder what would be the best way to track these spikes in execution, so we don't just increase timeouts ad infinitum.

@nebril I agree, but I'm unsure what to track next (it's not due to CPU frequency issues). Definitely not planning to increase the timeout beyond 16min :laughing:

**Review by kkourt — COMMENTED** [review]
> Flakes on privileged unit tests with context deadline exceeded are becoming a bit more common.

Can we have a metric on that? This way we can go back and check once this PR is applied whether the metric was improved or not.

**Comment by pchaigno** [comment]
> > Flakes on privileged unit tests with context deadline exceeded are becoming a bit more common.
> 
> Can we have a metric on that? This way we can go back and check once this PR is applied whether the metric was improved or not.

[This CI dashboard report](https://datastudio.google.com/s/lqNCHbMNMOs) has a comparison of number of failures biweekly. PR builds have more numbers but need to be interpreted with a bit more care (some failures are legitimate due to in-progress PRs).

**Comment by kkourt** [comment]
> > > Flakes on privileged unit tests with context deadline exceeded are becoming a bit more common.
> > 
> > 
> > Can we have a metric on that? This way we can go back and check once this PR is applied whether the metric was improved or not.
> 
> [This CI dashboard report](https://datastudio.google.com/s/lqNCHbMNMOs) has a comparison of number of failures biweekly. PR builds have more numbers but need to be interpreted with a bit more care (some failures are legitimate due to in-progress PRs).

Can these failures be filtered to count only those with context deadline exceeded?

**Comment by pchaigno** [comment]
> > > > Flakes on privileged unit tests with context deadline exceeded are becoming a bit more common.
> > > 
> > > 
> > > Can we have a metric on that? This way we can go back and check once this PR is applied whether the metric was improved or not.
> > 
> > 
> > [This CI dashboard report](https://datastudio.google.com/s/lqNCHbMNMOs) has a comparison of number of failures biweekly. PR builds have more numbers but need to be interpreted with a bit more care (some failures are legitimate due to in-progress PRs).
> 
> Can these failures be filtered to count only those with context deadline exceeded?

Not via the current dashboard, but it's maybe possible to extend the dashboard to have filters on the stacktrace text. It's on my TODO list to check once I have cycles.

**Comment by kkourt** [comment]
Overall, I'm worried by the "a bit more common" part which is not clear to me if this solves an actual problem or not, both because it is not easy to show the problem but also because we cannot verify that it indeed it solves it.

Having said that, I'm OK with merging this patch as a quality-of-life improvement for people working on CI so that we can tackle bigger issues first.

**Review by christarazi — APPROVED** [review]

**Comment by joestringer** [comment]
Do we get timestamps for each subtest that runs? Then maybe we could evaluate whether there are specific tests that end up taking a long time in the outlier cases?
