### PR TITLE
bgp,bugfix: parse ips when converting from slim_core to k8s service

### LINKED ISSUE #16967: BGP announcements not occurring on single-node cluster
## Bug report

**General Information**

- Cilium version: 1.10.3
- Kernel version: 5.10.43-flatcar
- Orchestration system version in use: 1.20.0
- Generate and upload a system zip:
[cilium-sysdump-20210721-162754.zip](https://github.com/cilium/cilium/files/6859260/cilium-sysdump-20210721-162754.zip)

**How to reproduce the issue**

I'm trying to deploy cilium on a single-node bare-metal cluster with BGP load balancer announcements enabled. I'm deploying with using helm with the following values.yaml file:

```yaml
debug:
  enabled: true
ipam:
  operator:
    clusterPoolIPv4PodCIDR: "10.101.0.0/16"
l7Proxy: false
encryption:
  enabled: true
  type: wireguard
bgp:
  enabled: true
  announce:
    loadbalancerIP: true
operator:
  replicas: 1
```

The BGP configmap is as as follows:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgp-config
  namespace: kube-system
data:
  config.yaml: |
    peers:
      - peer-address: 10.51.60.1
        peer-asn: 65500
        my-asn: 65501
    address-pools:
      - name: default
        protocol: bgp
        addresses:
          - 172.16.16.0/24
```
My BGP setup on the external router is VyOS with the following configuration:

```
protocols {
    bgp 65500 {
        neighbor 10.51.60.82 {
            description "Kubernetes load balancer"
            remote-as 65501
        }
        parameters {
            router-id 10.51.60.1
        }
    }
```
I confirmed that this setup seems to work perfectly with MetalLB (and BGP disabled in Cilium), but with the Cilium there are no BGP announcements happening. tcpdump shows periodic `KEEPALIVE` messages but no other updates. The logs for the cilium pod show a fair number of:
```
level=debug msg="event startUpdate msg start of service update" subsys=bgp-speaker
level=debug msg="event endUpdate msg end of service update" subsys=bgp-speaker
```
but that's the only indication of anything happening.

The LoadBalancer I'm trying to deploy is:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-test-lb
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    svc: test-lb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  selector:
    matchLabels:
      svc: test-lb
  template:
    metadata:
      labels:
        svc: test-lb
    spec:
      containers:
      - name: web
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
```
(Pretty much straight from the documentation.)

### PR DESCRIPTION
**Pull request by ldelossa**
this fixes #16967.

previous to this commit, when converting from a slim_core Service to our
k8s Service abstraction the parsed out loadBalancersIP were not
converted to the appropriate map of net.IP objects.

they were not converted because of a guard which only does this for when
"NodePort" configuration is set to true.

with the introduction of the BGP load balancer announcement feature, we
also need to parse IPs coming from the ServiceStatus field in a
slim_core Service.

If this change is not made, both the old and new services look exactly
the same to the k8sWatcher infrastructure and when the Service gets its
load balancer IP the entire event is thrown away.

Signed-off-by: Louis DeLosSantos <louis.delos@isovalent.com>

### CODE REVIEW

**Review by sayboras — COMMENTED** [review]
While the change looks simple, there is a lot of wisdom behind, I am going through the discussion in github issue to understand more. Right now, I don't even understand why nodeport check is there in the first place :thinking: 

Will be great if other team member can help to review this instead.

**Comment by ldelossa** [comment]
@sayboras That is where I'm currently at as well. Doing a deep dive. 

It appears the linked issue can be "worked-around" by ensuring "NodePort" is enabled off the bat. I didn't link this yet because I need to confirm. 

Also as I mention in this thread: https://cilium.slack.com/archives/C2B917YHE/p1641328782392200?thread_ts=1641245029.380700&cid=C2B917YHE

I believe a BPF backed NodePort should be completely orthognal to the BGP Announce LB feature, as that feature just cares about getting external traffic to a load balancer, not whether that load balancer is backed by a BPF node port impl, or the vanilla K8s impl. So part of me feels like this PR will actually change into decoupling the NodePort requirement from the BGP Announce LB feature all together. 

CC @aanm may have some insight.

File: daemon/cmd/daemon_main.go [hunk 1]
```diff
@@ -1517,14 +1517,6 @@ func initEnv(cmd *cobra.Command) {
 		}
 	}
 
-	// This is necessary because the code inside pkg/k8s.NewService() for
```
Comment (ldelossa) [inline daemon/cmd/daemon_main.go:1520]: This goes away, the BGP LB Announcement features are not coupled to the NodePort configuration.

**Comment by ldelossa** [comment]
Discussed this with @brb @aanm (separately)

The reason we do not parse IPs when "EnableNodePort" is false is to save on CPU cycles. When the umbrella feature flag "EnableNodePort" is disabled, Cilium does not care about Service events triggered by LoadBalancer Status updates. 

However, when the BGP Announce LB feature is enabled, Cilium must care about these updates in order for the k8s Watcher infra to generate a new Service event. 

The decision was made to keep the original "EnableNodePort" flag to continue to budget CPU if we don't need to spend it, but if BGP announcement feature is on, parse out the loadBalancerIPs so feature works without being coupled to "EnableNodePort" feature flag.

File: pkg/bgp/speaker/speaker.go [hunk 2]
```diff
@@ -128,7 +128,7 @@ func (s *MetalLBSpeaker) OnUpdateService(svc *slim_corev1.Service) error {
 	}
 
 	l.Debug("adding event to queue")
-	s.queue.Add(epEvent{
+	s.queue.Add(svcEvent{
```
Comment (ldelossa) [inline pkg/bgp/speaker/speaker.go:131]: good citizen change, this is mislabeled but causes no functional difference in the code, other then logging the wrong event type.

**Review by christarazi — APPROVED** [review]
Thanks, makes sense to me.

File: pkg/k8s/service.go [hunk 3]
```diff
@@ -444,11 +444,26 @@ func NewService(ips []net.IP, externalIPs, loadBalancerIPs, loadBalancerSourceRa
...
 		k8sLoadBalancerIPs = parseIPs(loadBalancerIPs)
 	}
 
+	// The BGP LB Announcement feature require that
+	// loadBalancerIPs be parsed. This is because
+	// an event must occur when a Service's Status field
+	// is updated with a new Ingress, ultimately triggering a
+	// BGP announcement. If we do not parse loadBalancerIPs
+	// this will not occur.
+	if option.Config.BGPAnnounceLBIP && k8sLoadBalancerIPs == nil {
```
Comment (aanm) [inline pkg/k8s/service.go]: Small nit, this can be done as an `else if` where it's the `else` of `if option.Config.EnableNodePort` and then we don't need to double check `k8sLoadBalancerIPs == nil`.

**Review by aanm — CHANGES_REQUESTED** [review]

File: pkg/k8s/service.go (hunk 3 above)
Comment (ldelossa) [reply pkg/k8s/service.go]: Updated.

**Review by aanm — APPROVED** [review]

File: pkg/k8s/service.go [hunk 4]
```diff
@@ -444,9 +444,22 @@ func NewService(ips []net.IP, externalIPs, loadBalancerIPs, loadBalancerSourceRa
 		loadBalancerSourceCIDRs[cidr.String()] = cidr
 	}
 
+	// If EnableNodePort is not true we do not want to process
+	// events which only differ in external or load balancer IPs.
+	// By omitting these IPs in the returned Service object, they
+	// are no longer considered in equality checks and thus save
+	// CPU cycles processing events Cilium will not act upon.
 	if option.Config.EnableNodePort {
```
Comment (brb) [inline pkg/k8s/service.go:452]: Have you considered completely removing the guard?

Comment (ldelossa) [reply pkg/k8s/service.go:452]: yes @aanm opt'd to keep to to avoid excess CPU processing. 

lets chat about this here. I'm not sure if any actual measuring was done to prove this necessary. 

To me, I don't like that we have a data model with fields that change based on configuration. I'd much rather see a consistent data model,  and the watcher code "filter" out events based on config, not alter a data model to perform that filtering.

File: daemon/cmd/daemon_main.go [hunk 5]
```diff
@@ -1517,14 +1517,6 @@ func initEnv(cmd *cobra.Command) {
...
-	// parsing services would not trigger unless NodePort is enabled. Without
-	// NodePort enabled, the external and LB IPs would not be parsed out.
-	if option.Config.BGPAnnounceLBIP {
```
Comment (kkourt) [inline daemon/cmd/daemon_main.go:1523]: I'm confused by the following comment:

> previous to this commit, when converting from a slim_core Service to our
> k8s Service abstraction the parsed out loadBalancersIP were not
> converted to the appropriate map of net.IP objects.
> 
> they were not converted because of a guard which only does this for when
> "NodePort" configuration is set to true.

Existing code (i.e., before this patch), seems to enable `NodePort` whenever `BGPAnnounceLBIP` was set. So doesn't this mean that the IPs would always be parsed correctly?

**Review by kkourt — APPROVED** [review]
LGTM (just a non-blocking comment).

File: daemon/cmd/daemon_main.go (hunk 5 above)
Comment (ldelossa) [reply daemon/cmd/daemon_main.go:1523]: In thoery yes, in practice, other code flips that bool on and off, so its becomes a crap shoot on whether EnableNodePort *stays* true, based on other configuration. This is what caused the issue to begin with.

File: pkg/k8s/service.go (hunk 4 above)
Comment (ldelossa) [reply pkg/k8s/service.go:452]: I got a thumbs up for my comment, @brb I don't think this will be handled in this PR. Should we move this one forward and plan for a larger change given we want to change how filtering works?

Comment (brb) [reply pkg/k8s/service.go:452]: SGTM.

**Review by brb — APPROVED** [review]

**Comment by ldelossa** [comment]
Latest failures are due to vagrant infra:

```
15:59:17  Failed in branch Copy code and boot vms
``` 

Rerunning tests.

**Comment by aditighag** [comment]
@ldelossa FYI - This bug fix warranted a release note as it's user-facing.
