### PR TITLE
datapath: Fix error propagation in bpf_lxc.

### LINKED ISSUE #20143: Drop notifications don't work correctly for packet LB
It looks like https://github.com/cilium/cilium/pull/17758 split out per-packet LB and during the refactor, it removed the `send_drop_notify()` calls that ensure that userspace is informed when the datapath drops a packet. Furthermore, because this is missing, that tail call may return a code that is not `CTX_ACT_OK` / `CTX_ACT_DROP`, so possibly Cilium could pass packets to the stack for continued forwarding when LB fails.

cc @DolceTriade @jrajahalme 

https://github.com/cilium/cilium/blob/4bcd7d23648341fedb6a4ba67243f52053ddee3a/bpf/bpf_lxc.c#L1163-L1164
https://github.com/cilium/cilium/blob/4bcd7d23648341fedb6a4ba67243f52053ddee3a/bpf/bpf_lxc.c#L1203-L1209
...
https://github.com/cilium/cilium/blob/4bcd7d23648341fedb6a4ba67243f52053ddee3a/bpf/bpf_lxc.c#L1220-L1224

### PR DESCRIPTION
**Pull request by DolceTriade**
handle_tail_ipv[4|6] both directly return raw error codes, but since
they are tail calls, they should be calling send_drop_notify() prior to
returning these error codes to translate to the appropriate drop return
code.

This was introduced as part of a refactor in
7575ba03ccaa5038255c8c1e5c31a8011ed9aaa1.

Fixes #20143

Signed-off-by: Harsh Modi <harshmodi@google.com>

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

```release-note
Fix error propagation in bpf_lxc
```

### CODE REVIEW

**Comment by DolceTriade** [comment]
Fixed style errors.

File: bpf/bpf_lxc.c [hunk 1]
```diff
@@ -685,6 +684,18 @@ int tail_handle_ipv6(struct __ctx_buff *ctx)
...
 	return ret;
 }
+
+__section_tail(CILIUM_MAP_CALLS, CILIUM_CALL_IPV6_FROM_LXC)
+int tail_handle_ipv6(struct __ctx_buff *ctx)
+{
+	int ret = __tail_handle_ipv6(ctx);
+
+	if (IS_ERR(ret)) {
+		return send_drop_notify(ctx, SECLABEL, 0, 0,
```
Comment (julianwiedmann) [inline bpf/bpf_lxc.c]:
```suggestion
		return send_drop_notify_error(ctx, SECLABEL,
```

File: bpf/bpf_lxc.c [hunk 2]
```diff
@@ -685,6 +684,18 @@ int tail_handle_ipv6(struct __ctx_buff *ctx)
...
+			ret, CTX_ACT_DROP, METRIC_EGRESS);
+	}
```
Comment (julianwiedmann) [inline bpf/bpf_lxc.c]: Please follow the established style - indentation of the function arguments, no curly braces around single statements. See the other `send_drop_notify()` calls in the same file.

File: bpf/bpf_lxc.c [hunk 3]
```diff
@@ -1234,6 +1244,18 @@ int tail_handle_ipv4(struct __ctx_buff *ctx)
...
 
+__section_tail(CILIUM_MAP_CALLS, CILIUM_CALL_IPV4_FROM_LXC)
+int tail_handle_ipv4(struct __ctx_buff *ctx)
+{
+	int ret = __tail_handle_ipv4(ctx);
+
+	if (IS_ERR(ret)) {
+		return send_drop_notify(ctx, SECLABEL, 0, 0,
+			ret, CTX_ACT_DROP, METRIC_EGRESS);
+	}
```
Comment (julianwiedmann) [inline bpf/bpf_lxc.c]: ditto

**Review by julianwiedmann — COMMENTED** [review]
Thank you! Just some small style nit-picks.

File: bpf/bpf_lxc.c (hunk 2 above)
Comment (DolceTriade) [reply bpf/bpf_lxc.c]: Done.

File: bpf/bpf_lxc.c (hunk 3 above)
Comment (DolceTriade) [reply bpf/bpf_lxc.c]: Done.

**Comment by joestringer** [comment]
Travis complaint will be addressed by #20171 . I'll see if we can run the full suite again.

**Comment by julianwiedmann** [comment]
That didn't work - @DolceTriade, could you please rebase your branch to pick up the build fix from https://github.com/cilium/cilium/pull/20171 ? Thanks!

**Comment by DolceTriade** [comment]
Rebased.

**Review by julianwiedmann — APPROVED** [review]
