### PR TITLE
loader: Check if device has BPF prog before trying to detach it

### LINKED ISSUE #13512: Clear error messages that should be marked as default
These errors are showed for the first time I enabled `kube-proxy-replacement` with `--device`
```
Oct 12 14:45:38 k8s2 cilium-agent[16875]: level=error msg="Command execution failed" cmd="[tc filter delete dev enp0s8 egress]" error="exit status 2" subsys=datapath-loader
Oct 12 14:45:38 k8s2 cilium-agent[16875]: level=warning msg="Error: Parent Qdisc doesn't exists." subsys=datapath-loader
Oct 12 14:45:38 k8s2 cilium-agent[16875]: level=warning msg="We have an error talking to the kernel, -1" subsys=datapath-loader
```

### PR DESCRIPTION
**Pull request by pchaigno**
When running Cilium with the devices set, but neither kube-proxy-free or the host firewall enabled, cilium-agent will attempt to remove the previous BPF program from the native devices' egress tc hook. If no program is attached there (i.e., Cilium was running without host firewall and kube-proxy replacement before restarting), the removal will fail with the following error.

    level=error msg="Command execution failed" cmd="[tc filter delete dev enp0s8 egress]" error="exit status 2" subsys=datapath-loader
    level=warning msg="Error: Parent Qdisc doesn't exists." subsys=datapath-loader
    level=warning msg="We have an error talking to the kernel, -1" subsys=datapath-loader

This commit fixes this error by first checking that the device has a BPF program attached on egress.

I tested this in the dev. VM, by first starting Cilium with our kube-proxy-replacement, then without but keeping the devices configuration.

Fixes: #10994
Fixes: #13512
Updates: #11799

### CODE REVIEW

**Comment by pchaigno** [comment]
test-me-please

File: pkg/datapath/loader/netlink.go [hunk 1]
```diff
@@ -141,3 +142,15 @@ func (l *Loader) DeleteDatapath(ctx context.Context, ifName, direction string) e
 
 	return nil
 }
+
+// HasDatapath return true if the interface as a tc filter attached on the given direction.
```
Comment (tklauser) [inline pkg/datapath/loader/netlink.go:146]:
```suggestion
// HasDatapath returns true if the interface has a tc filter attached on the given direction.
```

File: pkg/datapath/loader/netlink.go [hunk 2]
```diff
@@ -141,3 +142,15 @@ func (l *Loader) DeleteDatapath(ctx context.Context, ifName, direction string) e
...
+func (l *Loader) HasDatapath(ctx context.Context, ifName, direction string) (bool, error) {
+	args := []string{"filter", "show", "dev", ifName, direction}
+	cmd := exec.CommandContext(ctx, "tc", args...).WithFilters(libbpfFixupMsg)
+	output, err := cmd.Output(log, true)
+	if err != nil {
+		return true, fmt.Errorf("Failed to get tc filter: %s", err)
```
Comment (tklauser) [inline pkg/datapath/loader/netlink.go]: Use lowercase for the error string (see https://github.com/golang/go/wiki/CodeReviewComments#error-strings) and wrap the underlying error with `%w`:

```suggestion
		return true, fmt.Errorf("failed to get tc filter: %w", err)
```

I see other error strings in this file already use uppercase. These should probably be converted at some point as well.

**Review by tklauser — COMMENTED** [review]
Two small nits, otherwise LGTM.

**Review by tklauser — COMMENTED** [review]
Two small nits, otherwise LGTM.

File: pkg/datapath/loader/netlink.go (hunk 1 above)
Comment (pchaigno) [reply pkg/datapath/loader/netlink.go:146]: Ouch!

**Comment by pchaigno** [comment]
test-me-please

**Review by tklauser — APPROVED** [review]

**Comment by tklauser** [comment]
retest-4.9

File: pkg/datapath/loader/netlink.go [hunk 3]
```diff
@@ -141,3 +142,15 @@ func (l *Loader) DeleteDatapath(ctx context.Context, ifName, direction string) e
...
 	return nil
 }
+
+// HasDatapath returns true if the interface has a tc filter attached on the given direction.
+func (l *Loader) HasDatapath(ctx context.Context, ifName, direction string) (bool, error) {
+	args := []string{"filter", "show", "dev", ifName, direction}
+	cmd := exec.CommandContext(ctx, "tc", args...).WithFilters(libbpfFixupMsg)
+	output, err := cmd.Output(log, true)
+	if err != nil {
+		return true, fmt.Errorf("failed to get tc filter: %w", err)
```
Comment (kkourt) [inline pkg/datapath/loader/netlink.go]: Is `true` the proper thing to return here along with the error?
If there was an error, there will be other issues down the road so I guess it does not matter much

Comment (pchaigno) [reply pkg/datapath/loader/netlink.go]: Good question. So in that case, we don't know if the device has a program attached or not. So the rationale for returning true here is that I think we want to _attempt_ the removal of the BPF program. Having that program still attached to the device could lead to more errors than attempting to remove an absent program (removing an absent program will just generate the inconsequential error and warnings above).

Comment (kkourt) [reply pkg/datapath/loader/netlink.go]: Makes sense. Thanks for the explanation.

**Review by kkourt — APPROVED** [review]

File: pkg/datapath/loader/netlink.go (hunk 3 above)
Comment (aanm) [reply pkg/datapath/loader/netlink.go]: That's a good point, when a function returns an error all other values should be ignored. Since this is the case I would suggest to check for the error type in the caller of this function with the `errors.Is` function and perform some logic based on that information.

**Review by aanm — CHANGES_REQUESTED** [review]

**Comment by pchaigno** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Review by vadorovsky — APPROVED** [review]

File: pkg/datapath/loader/netlink.go [hunk 4]
```diff
@@ -141,3 +142,15 @@ func (l *Loader) DeleteDatapath(ctx context.Context, ifName, direction string) e
 
 	return nil
 }
+
+// HasDatapath return true if the interface as a tc filter attached on the given direction.
+func (l *Loader) HasDatapath(ctx context.Context, ifName, direction string) (bool, error) {
+	args := []string{"filter", "show", "dev", ifName, direction}
```
Comment (brb) [inline pkg/datapath/loader/netlink.go:148]: Out of curiosity, is there any tc filter native implementation in Go?

Comment (pchaigno) [reply pkg/datapath/loader/netlink.go:148]: Looks like Florian Lehner has one maybe: https://github.com/florianl/go-tc. IIRC, we discussed this during a recent SIG-Datapath meeting and concluded it would likely be easier to just write what we need using the netlink library.

Comment (brb) [reply pkg/datapath/loader/netlink.go:148]: Ah, I just remembered that we already have a similar code which is using the native implementation: https://github.com/cilium/cilium/blob/master/cilium/cmd/cleanup.go#L462.

Comment (pchaigno) [reply pkg/datapath/loader/netlink.go:148]: Ah, great! Given this is already `ready-to-merge` and addresses a `priority/release-blocker`, I'll switch to use the native implementation in a follow up. Looks like there are several other places where we could remove calls to the `tc` binary as well.
