### PR TITLE
ci: Do not label control plane nodes with cilium.io/node

### LINKED ISSUE #13395: CI: Don't label nodes with label kubernetes.io.role/master with cilium.io/node labels
## Bug report

**General Information**
When running tests against a target cluster, test pods do not tolerate scheduling on Kubernetes nodes with label role.kubernetes.io/master. The test suite automatically labels nodes in the cluster by name, but includes master nodes, causing some applications to fail to schedule properly.

**How to reproduce the issue**

1.K8S_VERSION=1.18 ginkgo -- -cilium.provision=false -cilium.kubeconfig=`echo ~/.kube/config` -cilium.image="cilium/cilium" -cilium.operator-image="cilium/operator" -cilium.hubble-relay-image="cilium/hubble-relay" -cilium.tag="v1.9.0-rc0" -cilium.operator-tag="v1.9.0-rc0" -cilium.hubble-relay-tag="v1.9.0-rc0"

```
kubectl get nodes --show-labels
NAME                 STATUS   ROLES    AGE     VERSION   LABELS
kind-control-plane   Ready    master   3h50m   v1.18.2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,cilium.io/ci-node=k8s1,kubernetes.io/arch=amd64,kubernetes.io/hostname=kind-control-plane,kubernetes.io/os=linux,node-role.kubernetes.io/master=
kind-worker          Ready    <none>   3h49m   v1.18.2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,cilium.io/ci-node=k8s2,kubernetes.io/arch=amd64,kubernetes.io/hostname=kind-worker,kubernetes.io/os=linux
kind-worker2         Ready    <none>   3h49m   v1.18.2   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,cilium.io/ci-node=k8s3,kubernetes.io/arch=amd64,kubernetes.io/hostname=kind-worker2,kubernetes.io/os=linux
```

### PR DESCRIPTION
**Pull request by vadorovsky**
Labeling control plane nodes with cilium.io/node when running against a
target cluster was causing some applications to fail to schedule
properly.

Fixes: #13395

### CODE REVIEW

**Comment by mrostecki** [comment]
test-me-please

**Comment by mrostecki** [comment]
test-me-please

**Comment by christarazi** [comment]
test-me-please

**Comment by mrostecki** [comment]
Vagrant test seem to be unhappy:

https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-4.9/754/consoleFull

```
22:47:12  • Failure in Spec Setup (BeforeEach) [5.227 seconds]
22:47:12  K8sServicesTest
22:47:12  /home/jenkins/workspace/Cilium-PR-K8s-1.19-kernel-4.9/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:478
22:47:12    Testing test script [BeforeEach]
22:47:12    /home/jenkins/workspace/Cilium-PR-K8s-1.19-kernel-4.9/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:478
22:47:12      Validating test script correctness
22:47:12      /home/jenkins/workspace/Cilium-PR-K8s-1.19-kernel-4.9/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
22:47:12  
22:47:12      Cannot get node by label k8s2
[2020-10-12T20:47:12.759Z]     Expected
[2020-10-12T20:47:12.759Z]         <*errors.errorString | 0xc000706990>: {
[2020-10-12T20:47:12.759Z]             s: "no matching node to read name with label 'k8s2'",
[2020-10-12T20:47:12.759Z]         }
[2020-10-12T20:47:12.759Z]     to be nil
22:47:12  
22:47:12      /home/jenkins/workspace/Cilium-PR-K8s-1.19-kernel-4.9/src/github.com/cilium/cilium/test/k8sT/Services.go:74
```

I thought that Vagrant node labels are set here and they will be not affected by my change:

https://github.com/cilium/cilium/blob/1662955a76f6ae4b2bf5fb9e69c493d9159a7cad/test/vagrant-ci-start.sh#L43-L46

**Comment by nebril** [comment]
Looks like the script indeed labeled the nodes: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-4.9/754/execution/node/103/log/

File: test/helpers/kubectl.go [hunk 1]
```diff
@@ -571,7 +571,7 @@ func (kub *Kubectl) PrepareCluster() {
 
 // labelNodes labels all Kubernetes nodes for use by the CI tests
 func (kub *Kubectl) labelNodes() error {
-	cmd := KubectlCmd + " get nodes -o json | jq -r '[ .items[].metadata.name ]'"
+	cmd := KubectlCmd + " get nodes --selector=node-role.kubernetes.io/controlplane!=,node-role.kubernetes.io/master!= -o json | jq -r '[ .items[].metadata.name ]'"
```
Comment (nebril) [inline test/helpers/kubectl.go]: I think you cannot exclude labels via selector right now, you should use jq for that.

`kubectl get nodes -o json | jq -r '[.items[] | select(.metadata.labels["node-role.kubernetes.io/controlplane"] == null).metadata.name]'`

**Review by nebril — CHANGES_REQUESTED** [review]

**Comment by nebril** [comment]
As for why the this doesn't work in it's current state - I don't know, the labels should be preserved.

File: test/helpers/kubectl.go (hunk 1 above)
Comment (vadorovsky) [reply test/helpers/kubectl.go]: That selector works for me locally on a kubeadm cluster (it selects the nodes which don't have those labels at all, it ignores the nodes having either `node-role.kubernetes.io/controlplane` or `node-role.kubernetes.io/master` with value "", kubeadm never sets any non-empty value for those labels.).

But the command you proposed looks safer and is not confusing like mine, so I will use it. Thanks!

**Comment by mrostecki** [comment]
test-me-please

**Comment by mrostecki** [comment]
retest-net-next

**Comment by mrostecki** [comment]
retest-net-next

**Comment by mrostecki** [comment]
test-me-please

**Comment by mrostecki** [comment]
test-gke

**Comment by mrostecki** [comment]
test-gke

**Review by nebril — APPROVED** [review]

**Comment by jrajahalme** [comment]
@mrostecki Bumped into similar problem running CI tests in Kind, it's master node has the `NoSchedule` taint, but it does not have the `node-role.kubernetes.io/controlplane` label. I'm wondering if the control plane node you needed to avoid labeling has a `NoSchedule` taint?

**Comment by mrostecki** [comment]
@jrajahalme Yes, it had both `NoSchedule` taint and the `node-role.kubernetes.io/controlplane` label. That's the default case on clusters deployed with kubeadm.
