### PR TITLE
Plumb Azure interface's VPC / primary CIDR and set it as native routing CIDR in Azure IPAM mode

### LINKED ISSUE #16693: CI: ConformanceAKS - Error: Connectivity test failed: timeout reached waiting for pod IDs in ipcache of Cilium pod kube-system/cilium-mvvgc
PR https://github.com/cilium/cilium/pull/16656 hit this failure. This happens because `cilium_host` is wrongly being assigned with a new IP address from list of available IPs when running with IPAM CRD:
```
6: cilium_host@cilium_net: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 16:f5:1d:44:2f:ee brd ff:ff:ff:ff:ff:ff
    inet 10.240.0.19/32 scope link cilium_host
       valid_lft forever preferred_lft forever
    inet 10.240.0.31/32 scope link cilium_host
       valid_lft forever preferred_lft forever
    inet6 fe80::14f5:1dff:fe44:2fee/64 scope link 
       valid_lft forever preferred_lft forever
```

This is already fixed for ENI and AlibabaCloud with https://github.com/cilium/cilium/pull/16672 but AKS seems to suffer from the same problem and to fix this bug in AKS will require more changes that @christarazi will submit in a PR.

### PR DESCRIPTION
**Pull request by christarazi**
- azure, ipam, k8s: Derive primary / VPC CIDR of Azure interface
- daemon: Add Azure IPAM mode for setting the native routing CIDR

Related: https://github.com/cilium/cilium/pull/16672
Fixes: https://github.com/cilium/cilium/issues/16693

### CODE REVIEW

**Comment by christarazi** [comment]
test-me-please

File: pkg/ipam/crd.go [hunk 1]
```diff
@@ -218,6 +218,14 @@ func deriveVpcCIDR(node *ciliumv2.CiliumNode) (result *cidr.CIDR) {
 			return
 		}
 	}
+	if len(node.Status.Azure.Interfaces) > 0 {
+		for _, azif := range node.Status.Azure.Interfaces {
+			c, err := cidr.ParseCIDR(azif.CIDR)
+			if err == nil {
+				result = c
+			}
```
Comment (aanm) [inline pkg/ipam/crd.go:227]: similarly to ENI, this should have a return here?

**Review by aanm — APPROVED** [review]
LGTM, only a small nit

File: pkg/ipam/crd.go (hunk 1 above)
Comment (christarazi) [reply pkg/ipam/crd.go:227]: Fixed

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
ci-aks
