### PR TITLE
operator: fix bugs on reading configuration from config-map

### LINKED ISSUE #10384: cilium-operator prints warnings for non existing flags in cilium-operator >= 1.8
```
2020-02-28T09:09:42.388194286Z level=warning msg="NodePort range was set but is empty." subsys=config
2020-02-28T09:09:42.388621406Z level=warning msg="Running Cilium with \"kvstore\"=\"\" requires identity allocation via CRDs. Changing identity-allocation-mode to \"crd\"" subsys=config
2020-02-28T09:09:42.388633365Z level=warning msg="user-provided parameter had value <= 0 , which is invalid ; setting to default" defaultValue=100 parameter=policy-queue-size subsys=config
2020-02-28T09:09:42.388669836Z level=warning msg="user-provided parameter had value <= 0 , which is invalid ; setting to default" defaultValue=25 parameter=endpoint-queue-size subsys=config
```

### PR DESCRIPTION
**Pull request by aanm**
`cobra.OnInitialize` should be called directly in the init function.

Due refactoring, `cilium-agent --version` and `cilium-operator --version` no longer work, this PR also fixes this bug by rewriting the code.

Also, stop executing flag validation if flags are not set

Fixes: 67b147c3f273 ("operator: add ability to ready options from a config directory")
Signed-off-by: André Martins <andre@cilium.io>

Fixes https://github.com/cilium/cilium/issues/10384

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10520)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by tklauser — COMMENTED** [review]
LGTM in general.

Noticed that `operator` now has two `init` functions one of which (in `operator/flags.go) calls `cobra.OnInitialize(option.InitConfig...)` hooking up the handling of `--version` and the other (in `operator/main.go`) handles `--version` by itself. Would it be possible to somehow merge the two so we can a centralized handling of `--version` in `InitConfig`?

**Comment by aanm** [comment]
test-me-please

**Comment by tklauser** [comment]
test-me-please

**Review by tklauser — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

File: test/helpers/kubectl.go [hunk 1]
```diff
@@ -1493,6 +1493,43 @@ func (kub *Kubectl) GetPublicIface() (string, error) {
...
+
+	ctx, cancel := context.WithTimeout(context.Background(), HelperTimeout)
+	defer cancel()
+
+	status := 1
+	for status > 0 {
+
+		select {
+		case <-ctx.Done():
+			return fmt.Errorf("timed out waiting to delete Cilium Operator: pods still remaining: %s", pods)
```
Comment (nebril) [inline test/helpers/kubectl.go:1518]: `pods` will be uninitialized here on first run, probably won't ever happen, but can we move whole `select` to the end of the loop body? I assume we want to run through the loop body at least once.

**Review by nebril — CHANGES_REQUESTED** [review]
One small comment, lgtm otherwise

File: test/helpers/kubectl.go (hunk 1 above)
Comment (aanm) [reply test/helpers/kubectl.go:1518]: @nebril I'm going to fix this in another PR as this PR is blocking some of my work.
