### PR TITLE
iptables: Don't use `ip{,6}tables` if unavailable

### LINKED ISSUE #18513: cilium-agents crashing / cmd="[ip6tables -w 5 -t nat -S]" error="exit status 3" subsys=iptable
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

i am currently implementing cilium CNI with a rke2 without kube-proxy mode. And currently facing the issue below.

### Cilium Version

cilium:v1.10.4 

### Kernel Version

workernodes
Ubuntu 20.04.3 LTS/ Kernel: Linux 5.4.0-84-generic
Oracle Linux Server 8.5/  Kernel: Linux 5.4.17-2136.300.7.el8uek.x86_64

### Kubernetes Version

v1.22.4+rke2r1

### Sysdump

n/a

### Relevant log output

```shell
level=error msg="Command execution failed" cmd="[ip6tables -w 5 -t nat -S]" error="exit status 3" subsys=iptables
level=warning msg="ip6tables v1.8.4 (legacy): can't initialize ip6tables table `nat': Address family not supported by protocol" subsys=iptables
level=warning msg="Perhaps ip6tables or your kernel needs to be upgraded." subsys=iptables
level=error msg="Command execution failed" cmd="[ip6tables -w 5 -t mangle -S]" error="exit status 3" subsys=iptables
level=warning msg="ip6tables v1.8.4 (legacy): can't initialize ip6tables table `mangle': Address family not supported by protocol" subsys=iptables
level=warning msg="Perhaps ip6tables or your kernel needs to be upgraded." subsys=iptables
level=error msg="Command execution failed" cmd="[ip6tables -w 5 -t raw -S]" error="exit status 3" subsys=iptables
level=warning msg="ip6tables v1.8.4 (legacy): can't initialize ip6tables table `raw': Address family not supported by protocol" subsys=iptables
level=warning msg="Perhaps ip6tables or your kernel needs to be upgraded." subsys=iptables
level=error msg="Command execution failed" cmd="[ip6tables -w 5 -t filter -S]" error="exit status 3" subsys=iptables
level=warning msg="ip6tables v1.8.4 (legacy): can't initialize ip6tables table `filter': Address family not supported by protocol" subsys=iptables
level=warning msg="Perhaps ip6tables or your kernel needs to be upgraded." subsys=iptables
level=error msg="Command execution failed" cmd="[ip6tables -w 5 -t nat -S]" error="exit status 3" subsys=iptables
level=warning msg="ip6tables v1.8.4 (legacy): can't initialize ip6tables table `nat': Address family not supported by protocol" subsys=iptables
level=warning msg="Perhaps ip6tables or your kernel needs to be upgraded." subsys=iptables
level=error msg="Command execution failed" cmd="[ip6tables -w 5 -t mangle -S]" error="exit status 3" subsys=iptables
level=warning msg="ip6tables v1.8.4 (legacy): can't initialize ip6tables table `mangle': Address family not supported by protocol" subsys=iptables
level=warning msg="Perhaps ip6tables or your kernel needs to be upgraded." subsys=iptables
level=error msg="Command execution failed" cmd="[ip6tables -w 5 -t raw -S]" error="exit status 3" subsys=iptables
level=warning msg="ip6tables v1.8.4 (legacy): can't initialize ip6tables table `raw': Address family not supported by protocol" subsys=iptables
level=warning msg="Perhaps ip6tables or your kernel needs to be upgraded." subsys=iptables
level=error msg="Command execution failed" cmd="[ip6tables -w 5 -t filter -S]" error="exit status 3" subsys=iptables
level=warning msg="ip6tables v1.8.4 (legacy): can't initialize ip6tables table `filter': Address family not supported by protocol" subsys=iptables
```
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by pchaigno**
Fixes: https://github.com/cilium/cilium/issues/18513.

```release-note
Fix agent crash when IPv6 is partially disabled in the host kernel.
```

### CODE REVIEW

**Review by jibi — APPROVED** [review]

**Comment by pchaigno** [comment]
/test-1.21-5.4

File: pkg/datapath/iptables/iptables.go [hunk 1]
```diff
@@ -494,17 +494,21 @@ func (m *IptablesManager) SupportsOriginalSourceAddr() bool {
...
-		tables6 := []string{"nat", "mangle", "raw", "filter"}
-		for _, t := range tables6 {
-			m.removeCiliumRules(t, ip6tables, prefix+"CILIUM_")
+	if option.Config.EnableIPv6 {
+		// Set of tables that have had ip6tables rules in any Cilium version
+		if m.haveIp6tables {
+			tables6 := []string{"nat", "mangle", "raw", "filter"}
+			for _, t := range tables6 {
+				m.removeCiliumRules(t, ip6tables, prefix+"CILIUM_")
+			}
```
Comment (joestringer) [inline pkg/datapath/iptables/iptables.go:511]: @joamaki Doesn't this mean that if you enable IPv6 in the agent, then disable IPv6 in the agent, then we'll leave a bunch of IPv6 configuration behind? I think it was the way it was before deliberately to try to clean up after Cilium when the user explicitly disables configuration.

Comment (pchaigno) [reply pkg/datapath/iptables/iptables.go:511]: I think that question was meant for me.

You're probably correct. Looking at how `haveIp6tables` is defined, it seems we will only execute this code if the IPv6 modules are loaded. So something else is causing the error reported in https://github.com/cilium/cilium/issues/18513. I'll revert and ask for more information.

**Comment by jibi** [comment]
> I'll revert and ask for more information.

I'll remove the needs-backport label then :+1:

File: pkg/datapath/iptables/iptables.go (hunk 1 above)
Comment (pchaigno) [reply pkg/datapath/iptables/iptables.go:511]: Revert sent at https://github.com/cilium/cilium/pull/18768.

Comment (joestringer) [reply pkg/datapath/iptables/iptables.go:511]: Ah yes got that mixed up, apologies for the noise :pray: . OK sounds good.
