### PR TITLE
.travis:fix up TestSpanStatRaceCondition failure

### LINKED ISSUE #12574: CI: Travis failed on arm64:  TestSpanStatRaceCondition Fail
CI failure Link:
https://travis-ci.com/github/cilium/cilium/jobs/361628402#L9712

```
panic: Log in goroutine after TestSpanStatRaceCondition/End_function has completed
goroutine 37 [running]:
testing.(*common).logDepth(0x4000156ea0, 0x40000341e0, 0x9a, 0x3)
	/home/travis/.gimme/versions/go1.14.4.linux.arm64/src/testing/testing.go:680 +0x3e8
testing.(*common).log(...)
	/home/travis/.gimme/versions/go1.14.4.linux.arm64/src/testing/testing.go:662
testing.(*common).Errorf(0x4000156ea0, 0x502374, 0x3, 0x4000119800, 0x1, 0x1)
	/home/travis/.gimme/versions/go1.14.4.linux.arm64/src/testing/testing.go:711 +0x6c
github.com/stretchr/testify/assert.Fail(0x5c1560, 0x4000156ea0, 0x40000265a0, 0x11, 0x0, 0x0, 0x0, 0x40815c)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/github.com/stretchr/testify/assert/assertions.go:261 +0x228
github.com/stretchr/testify/assert.NotEqual(0x5c1560, 0x4000156ea0, 0x44ff00, 0x9598a0, 0x44ff00, 0x5b3c80, 0x0, 0x0, 0x0, 0x524eb0)
	/home/travis/gopath/src/github.com/cilium/cilium/vendor/github.com/stretchr/testify/assert/assertions.go:650 +0x1dc
github.com/cilium/cilium/pkg/spanstat.TestSpanStatRaceCondition.func8.1(0x4000156ea0, 0x400000e120, 0x4000161380)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/spanstat/spanstat_test.go:185 +0x84
created by github.com/cilium/cilium/pkg/spanstat.TestSpanStatRaceCondition.func8
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/spanstat/spanstat_test.go:184 +0xcc
FAIL	github.com/cilium/cilium/pkg/spanstat	0.033s
FAIL
```

### PR DESCRIPTION
**Pull request by Jianlin-lv**
Improper use of the WaitGroup API caused goroutine
to execute out of order, which could be the cause of goroutine panic

Signed-off-by: Jianlin Lv <Jianlin.Lv@arm.com>

Fixes: #12574

### CODE REVIEW

**Review by rolinh — APPROVED** [review]

File: pkg/spanstat/spanstat_test.go [hunk 1]
```diff
@@ -182,10 +182,11 @@ func TestSpanStatRaceCondition(t *testing.T) {
 			for i := 0; i < 5; i++ {
 				wg.Add(1)
 				go func(span *SpanStat) {
+					defer wg.Done()
 					assert.NotEqual(t, tt.fields.runFunc(span), float64(0))
 				}(span)
 			}
-			wg.Done()
+			wg.Wait()
```
Comment (sayboras) [inline pkg/spanstat/spanstat_test.go:190]: opps, how come I missed this.

Thanks :tada:

Comment (sayboras) [reply pkg/spanstat/spanstat_test.go:190]: oh right, I rememberred now. Actually, I was supposed to remove this test, as it didn't fit well with entire test framework in code base (e.g. with TestSuite.C).

**Review by rolinh — CHANGES_REQUESTED** [review]
I just noticed that `TestSpanStatSecondsRaceCondition()` suffers from the same issue.
@Jianlin-lv Would you mind fixing this one as well?

File: pkg/spanstat/spanstat_test.go (hunk 1 above)
Comment (rolinh) [reply pkg/spanstat/spanstat_test.go:190]: >  it didn't fit well with entire test framework in code base (e.g. with TestSuite.C).

I think this is fine. These tests are standard table driven tests which we have a ton in `pkg/hubble` for instance.

**Comment by Jianlin-lv** [comment]
> I just noticed that `TestSpanStatSecondsRaceCondition()` suffers from the same issue.
> @Jianlin-lv Would you mind fixing this one as well?

Done, 
I did not notice this issue, Sorry

**Comment by Rolinh** [comment]
> > I just noticed that `TestSpanStatSecondsRaceCondition()` suffers from the same issue.
> > @Jianlin-lv Would you mind fixing this one as well?
> 
> Done,
> I did not notice this issue, Sorry

No problem! Would you mind squashing the 2 commits into 1 though? They essentially fix the same problem.

**Review by christarazi — APPROVED** [review]
Nice find!

**Comment by Jianlin-lv** [comment]
> > > I just noticed that `TestSpanStatSecondsRaceCondition()` suffers from the same issue.
> > > @Jianlin-lv Would you mind fixing this one as well?
> > 
> > 
> > Done,
> > I did not notice this issue, Sorry
> 
> No problem! Would you mind squashing the 2 commits into 1 though? They essentially fix the same problem.

Done

**Review by rolinh — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by Rolinh** [comment]
No need to run the full test suite as this is a fix for the non-privileged unit tests that are run by travis.
