### PR TITLE
Fix cilium startup failure when xt_socket kernel module is not available

### LINKED ISSUE #8982: Cilium v1.6.0 fails to start on GKE cos_containerd images
Cilium agent fails to start because it cannot configure transparent proxying iptables rules, likely due to a missing `xt_socket` kernel module (and friends `nf_socket_ipv4`, `nf_socket_ipv6`).

```
level=warning msg="Unable to flush Cilium iptables chain" error="exit status 1" obj="[-w 5 -t filter -F CILIUM_TRANSIENT_FORWARD]" subsys=iptables
level=warning msg="Unable to delete Cilium iptables chain" error="exit status 1" obj="[-w 5 -t filter -X CILIUM_TRANSIENT_FORWARD]" subsys=iptables
level=error msg="Command execution failed" cmd="[iptables -w 5 -t mangle -A CILIUM_PRE_mangle -m socket --transparent --nowildcard -m comment --comment cilium: mark transparent proxy traffic to be routed locally -j MARK --set-mark 0x00000200]" error="exit status 1" subsys=iptables
level=warning msg="iptables: No chain/target/match by that name." subsys=iptables
level=error msg="Error while initializing daemon" error="exit status 1" subsys=daemon
level=fatal msg="Error while creating daemon" error="exit status 1" subsys=daemon
```

### PR DESCRIPTION
**Pull request by joestringer**
Per #8982, Cilium v1.6.0 fails to start in some GKE environments because we attempt to configure an iptables rule which uses the socket match, for ensuring that tproxy traffic can reach proxies in direct routing mode.

Rather than crashing out entirely, this PR proposes to just print a warning in the logs that the rule was not configured, which could cause unexpected drops when using L7 policy in direct routing mode.

Future work can potentially look to better support this direct routing mode + L7 policy case with tproxy perhaps by substituting the iptables rule installation with instead disabling early demux, however this will require further testing and validation to ensure it works correctly. For now, it's better to allow common use cases such as Cilium in tunnel mode, or Cilium in direct routing without L7 policy, rather than always exiting out in such environments.

Fixes: #8982

I manually validated this locally by removing the `xt_socket` module and running Cilium to observe that the warning message is formatted correctly and Cilium continues to run in that case.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8983)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

File: pkg/datapath/iptables/iptables.go [hunk 1]
```diff
@@ -492,6 +531,21 @@ func (m *IptablesManager) installProxyNotrackRules() error {
 				"-m", "comment", "--comment", "cilium: NOTRACK for proxy return traffic",
 				"-j", "NOTRACK"), false)
 		}
+		if err == nil {
+			// Direct inbound TPROXYed traffic towards the socket
+			args := m.inboundProxyRedirectRule("-A")
+			if err2 := runProg("ip6tables", args, false); err2 != nil {
+				scopedLog := log.WithFields(logrus.Fields{
+					"cmd":            args,
+					logfields.Family: logfields.IPv4,
```
Comment (jrajahalme) [inline pkg/datapath/iptables/iptables.go]: Should this be `logfields.IPv6`?

**Review by jrajahalme — APPROVED** [review]

File: pkg/datapath/iptables/iptables.go (hunk 1 above)
Comment (joestringer) [reply pkg/datapath/iptables/iptables.go]: Good catch.

**Comment by joestringer** [comment]
test-me-please
