### PR TITLE
Stop waiting for pod when collecting logs

### LINKED ISSUE #11976: CI: Fetching command output from pods stuck for 40min
When Cilium fails to start, the log collection spends 40 minutes on `Fetching command output from pods`. This happens in Jenkins CI, locally, and with the new smoke test in GitHub Actions.

The reason is that the log collection keeps trying (10 times) to retrieve information from the Cilium pods and waits for them 4 minutes each time. We should teach it to recognize the Cilium pods are persistently down and we would save ~40 minutes per test. When Cilium is broken for all tests (e.g., BPF compilation error), we often spend 2h40min running just 4 failing tests...

Here is one example for the Smoke test:
https://github.com/cilium/cilium/pull/11969/checks?check_run_id=752762283
[logs_8634.zip](https://github.com/cilium/cilium/files/4750859/logs_8634.zip)

### PR DESCRIPTION
**Pull request by Weil0ng**
Signed-off-by: Weilong Cui <cuiwl@google.com>

Fixes: #11976

### CODE REVIEW

File: test/helpers/kubectl.go [hunk 1]
```diff
@@ -3806,7 +3806,7 @@ func (kub *Kubectl) ciliumServicePreFlightCheck() error {
 // commands are run on all pods matching selector
 func (kub *Kubectl) reportMapContext(ctx context.Context, path string, reportCmds map[string]string, ns, selector string) {
 	for cmd, logfile := range reportCmds {
-		results, err := kub.ExecInPods(ctx, ns, selector, cmd, true, ExecOptions{SkipLog: true})
+		results, err := kub.ExecInPods(ctx, ns, selector, cmd, false, ExecOptions{SkipLog: true})
```
Comment (pchaigno) [inline test/helpers/kubectl.go]: I'm not sure if that's the correct way to fix it, but in any case, it doesn't do what the commit message describes. As far as I can see, this boolean instructs `ExecInPods` to wait for the pods to be ready before running the log collection commands. Setting the boolean to true or false won't affect parallelization.

On whether this is the correct fix: We likely do need to wait for the pods to be ready, at least the first time we call `ExecInPods()`. @nebril can probably confirm.

**Review by pchaigno — CHANGES_REQUESTED** [review]

File: test/helpers/kubectl.go (hunk 1 above)
Comment (Weil0ng) [reply test/helpers/kubectl.go]: Hmm, my understanding is that if `wait` is set to `false`, then `ExecInPods` would NOT wait for pods to be ready before executing the cmds, and when the pods are indeed NOT ready, would record cmd failure. Am I missing something? https://github.com/cilium/cilium/blob/master/test/helpers/kubectl.go#L3154

Comment (Weil0ng) [reply test/helpers/kubectl.go]: Ah, you are right, it's not about parallelization, just skips the wait.

Comment (pchaigno) [reply test/helpers/kubectl.go]: > then `ExecInPods` would NOT wait for pods to be ready before executing the cmds, and when the pods are indeed NOT ready, would record cmd failure.

No, that's my understanding as well. But in some cases we might want to wait for the pods because we just deployed them (e.g., log gatherers).

Comment (Weil0ng) [reply test/helpers/kubectl.go]: Maybe a better solution is to call `ExecPodCmdBackground` instead so that these cmds ARE parallelized, and the total wait time should be roughly `1 * helper.Timeout` instead of `len(cmds) * helper.Timeout`?

Comment (pchaigno) [reply test/helpers/kubectl.go]: Yep that sounds worth a try, but it's more likely to have other consequences we're missing. Did you check the executed commands to ensure we don't risk overwriting the result of one command with another if we do that? I would expect we write to different files, but maybe worth double checking.

Comment (Weil0ng) [reply test/helpers/kubectl.go]: Yea `reportMapContext` handles the actual fs operations and it is using different logfile for different cmd. I'll update the commit to try out this solution.

Comment (Weil0ng) [reply test/helpers/kubectl.go]: Let's iterate on the new solution, closing this one since this was probably not the right fix.

**Comment by Weil0ng** [comment]
Please take another look :) Thanks!

**Comment by aanm** [comment]
test-me-please

**Review by pchaigno — APPROVED** [review]
I'm :+1: with this fix, but would really prefer some @cilium/ci eyes on this.

#12576 shows that it fixes the issue.

File: test/helpers/kubectl.go [hunk 2]
```diff
@@ -3805,10 +3805,14 @@ func (kub *Kubectl) ciliumServicePreFlightCheck() error {
...
+	if err != nil {
+		log.WithError(err).Errorf("cannot retrieve pod names with '%s': %s", selector, err)
+	}
 	for cmd, logfile := range reportCmds {
-		results, err := kub.ExecInPods(ctx, ns, selector, cmd, true, ExecOptions{SkipLog: true})
-		if err != nil {
-			log.WithError(err).Errorf("cannot retrieve command output '%s': %s", cmd, err)
+		results := make(map[string]*CmdRes)
+		for _, pod := range pods {
+			results[pod] = kub.ExecPodCmdBackground(ctx, ns, pod, cmd, ExecOptions{SkipLog: true})
```
Comment (nebril) [inline test/helpers/kubectl.go]: `ExecPodCmdBackground` will not wait for the command to be finished, so we will end up writing incomplete output to report files.

I think that proper way of fixing this is changing `ExecInPods` so that it's runs all the commands in parallel and waits for all execs to finish.

**Review by nebril — CHANGES_REQUESTED** [review]
Thanks for the PR! Very cool that you caught this unoptimized bit, I think we should fix this one level deeper so that all functions that use `ExecInPods` profit from this.

File: test/helpers/kubectl.go (hunk 2 above)
Comment (Weil0ng) [reply test/helpers/kubectl.go]: > `ExecPodCmdBackground` will not wait for the command to be finished, so we will end up writing incomplete output to report files.

Would adding calls to `WaitUntilFinish()` for each invocation of `ExecPodCmdBackground` here solve the problem of having incomplete results?

> I think that proper way of fixing this is changing `ExecInPods` so that it's runs all the commands in parallel and waits for all execs to finish.

A bit confused as from what I understand, the problem with calling `ExecInPods` is in the `wait` period where it waits for the pod to become ready and repeatedly do so for every invocation, hence parallelizing the cmd execution inside `ExecInPods` might not solve the problem?

Comment (Weil0ng) [reply test/helpers/kubectl.go]: @nebril thoughts?

Comment (Weil0ng) [reply test/helpers/kubectl.go]: PTAL :)

Comment (nebril) [reply test/helpers/kubectl.go]: @Weil0ng thanks for being patient. I meant that we should change implementation of `ExecInPods` so that each `ExecContext` call would be called in it's own goroutine, whole loop would be guarded by a waitgroup (`results` map would probably also need a lock to synchronize writing result from single call).

I am basically talking about rewriting this loop https://github.com/cilium/cilium/blob/3abfde24ea1a33693ca5a62c1fe32d7efce48b71/test/helpers/kubectl.go#L3153 to run goroutines inside and wait for them, similarly to what we do in `reportMapHost`: https://github.com/cilium/cilium/blob/3abfde24ea1a33693ca5a62c1fe32d7efce48b71/test/helpers/kubectl.go#L3831

Does this make sense?

Comment (Weil0ng) [reply test/helpers/kubectl.go]: @nebril Thanks for the detailed explanation! I guess what I was trying to say is that even if we optimize that for-loop to multiple goroutines, it won't solve the original problem because the `wait` block above is the culprit here I think unless I missed something?

https://github.com/cilium/cilium/blob/3abfde24ea1a33693ca5a62c1fe32d7efce48b71/test/helpers/kubectl.go#L3145

Comment (nebril) [reply test/helpers/kubectl.go]: @Weil0ng `WaitForPods` runs `kubectl wait` underneath and is there only to make sure that all pods matching selector are ready before running actual commands.

Additionally to parallelizing the loop, it might be good idea to pass `wait=false` in `reportMapContext` because all the pods are usually already running and if they are not ready we may want to get logs from them anyway.

Comment (pchaigno) [reply test/helpers/kubectl.go]: @nebril The issue we're trying to address here is that `kubectl wait` gets run multiple times for the same pods. When those pods are not running (typically because cilium-agent fataled), that leads to long waiting times (~40min to collect logs, see #11976).

Comment (nebril) [reply test/helpers/kubectl.go]: @pchaigno I see, thanks for explaining! in that case it would make sense to just switch `wait` argument to `ExecInPods` to false in all logging functions, no point in waiting for pods when we are just gathering logs.

Comment (pchaigno) [reply test/helpers/kubectl.go]: Don't we deploy log-gatherer pods (or similar) that we would need to wait for at least once?

Comment (nebril) [reply test/helpers/kubectl.go]: We are waiting for log-gatherer pods when we are creating kubectl object: https://github.com/cilium/cilium/blob/3abfde24ea1a33693ca5a62c1fe32d7efce48b71/test/helpers/kubectl.go#L356

Comment (pchaigno) [reply test/helpers/kubectl.go]: Great, makes sense! Thanks a lot @nebril!

Comment (Weil0ng) [reply test/helpers/kubectl.go]: Given that this is the only place `ExecInPods` is referenced, we might just get rid of the `wait` block entirely?

Comment (pchaigno) [reply test/helpers/kubectl.go]: @Weil0ng Sounds good to me :+1:

**Comment by pchaigno** [comment]
I've updated #12576 to test the new fix.

**Comment by pchaigno** [comment]
test-me-please

**Review by nebril — APPROVED** [review]

**Comment by pchaigno** [comment]
Marking for backports in 1.7 and 1.8 because I've noticed the same issue in 1.7 and it looks like it should be trivial (i.e., no conflicts).
