### PR TITLE
cmd: Fix issue reading string map type via config map

### LINKED ISSUE #18328: cmd: `subnet-tags-filter: k=v` (and other options) silently fail when provided via ConfigMap
When providing the flags like `subnet-tags-filter` via ConfigMap, we have assumed and documented that these flags (relying on `GetStringMapString`) can be populated via a `k=v` syntax. However, it turns out that when specified via ConfigMap, it needs to be JSON syntax (`{"k":"v"}`), and _not_ the `k=v` syntax as documented. The latter syntax only works if directly passed via command-line argument.

*As a result, using `subnet-tags-filter: foo=bar` in the ConfigMap will cause cilium-operator to read the flag as `nil` and not use any subnet filters at all*

Affected flags:
```
pkg/option/config.go
2771:	if m := viper.GetStringMapString(FixedIdentityMapping); len(m) != 0 {
2777:	if m := viper.GetStringMapString(KVStoreOpt); len(m) != 0 {
2781:	if m := viper.GetStringMapString(LogOpt); len(m) != 0 {
2785:	if m := viper.GetStringMapString(APIRateLimitName); len(m) != 0 {

operator/option/config.go
449:	if m := viper.GetStringMapString(IPAMSubnetsTags); len(m) != 0 {
453:	if m := viper.GetStringMapString(AWSInstanceLimitMapping); len(m) != 0 {
457:	if m := viper.GetStringMapString(ENITags); len(m) != 0 {
```

Upstream issue: https://github.com/spf13/viper/issues/911

We should replace `viper.GetStringMapString` by something which behaves the same regardless of wheater the flag has been provided via command-line argument or config-dir (i.e. ConfigMap) entry.

### PR DESCRIPTION
**Pull request by sayboras**
### Description

As mentioned in below upstream issue, there is a discrepancy in viper
while reading string map string data type i.e. kv pair format was not
supported, only `{"k":"v"}` format is allowed. This commit is to wrap
GetStringMapString implementation to handle such case. This is backward
compatible change.

Relates https://github.com/spf13/viper/issues/911
Fixes https://github.com/cilium/cilium/issues/18328

Signed-off-by: Tam Mach <tam.mach@isovalent.com>

### Testing

Testing was done locally as per below

<details>
<summary>before</summary>

```
$ cat tmp/subnet-tags-filter
k1=v1,k2=v2% 

/usr/lib/go-1.17/bin/go build -o /tmp/GoLand/___2go_build_github_com_cilium_cilium_operator github.com/cilium/cilium/operator #gosetup
/tmp/GoLand/___2go_build_github_com_cilium_cilium_operator --config-dir tmp/
level=info msg="Started gops server" address="127.0.0.1:9891" subsys=___2go_build_github_com_cilium_cilium_operator
level=warning msg="Running Cilium with \"kvstore\"=\"\" requires identity allocation via CRDs. Changing identity-allocation-mode to \"crd\"" subsys=config
...
level=info msg="  --subnet-ids-filter=''" subsys=___2go_build_github_com_cilium_cilium_operator
level=info msg="  --subnet-ids-filter=''" subsys=___2go_build_github_com_cilium_cilium_operator --> THIS IS EMPTY
level=info msg="  --synchronize-k8s-nodes='true'" subsys=___2go_build_github_com_cilium_cilium_operator
...
level=info msg="Cilium Operator  go version go1.17 linux/amd64" subsys=___2go_build_github_com_cilium_cilium_operator
```

</details>

<details>
<summary>after</summary>

```
/usr/lib/go-1.17/bin/go build -o /tmp/GoLand/___2go_build_github_com_cilium_cilium_operator github.com/cilium/cilium/operator #gosetup
/tmp/GoLand/___2go_build_github_com_cilium_cilium_operator --config-dir tmp/
level=info msg="Started gops server" address="127.0.0.1:9891" subsys=___2go_build_github_com_cilium_cilium_operator
level=warning msg="Running Cilium with \"kvstore\"=\"\" requires identity allocation via CRDs. Changing identity-allocation-mode to \"crd\"" subsys=config

...
level=info msg="  --subnet-ids-filter=''" subsys=___2go_build_github_com_cilium_cilium_operator
level=info msg="  --subnet-tags-filter='k1=v1,k2=v2'" subsys=___2go_build_github_com_cilium_cilium_operator --> THIS HAS CORRECT VALUE
level=info msg="  --synchronize-k8s-nodes='true'" subsys=___2go_build_github_com_cilium_cilium_operator
...
level=info msg="Cilium Operator  go version go1.17 linux/amd64" subsys=___2go_build_github_com_cilium_cilium_operator
```

</details>

```release-note
cmd: Fix issue reading string map type via config map
```

### CODE REVIEW

File: pkg/command/map_string.go [hunk 1]
```diff
@@ -0,0 +1,43 @@
+// SPDX-License-Identifier: Apache-2.0
+// Copyright 2022 Authors of Cilium
+
+package command
```
Comment (sayboras) [inline pkg/command/map_string.go:4]: I look around, and find this package is the most relevant, feel free to let me know otherwise.

File: contrib/scripts/check-viper-get-string-map-string.sh [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+
+# Simple script to make sure viper.GetStringMapString should not be used.
+if grep -r --exclude-dir={.git,_build,vendor,contrib} -i --include \*.go "viper.GetStringMapString" .; then
+  echo "Found viper.GetStringMapString(key) usage. Please use command.GetStringMapString(viper.GetViper(), key) instead";
```
Comment (sayboras) [inline contrib/scripts/check-viper-get-string-map-string.sh:20]: very naive check here, this will not work with import alias, but we all get used to viper.<something> I reckon.

File: pkg/command/map_string_test.go [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+			want: expectedResult,
+		},
+		{
+			name: "value with invalid json format",
+			args: args{
+				key:   "FOO_BAR",
+				value: `{"k1":"v1","k2":"v2",}`,
+			},
+			want: map[string]string{},
+		},
```
Comment (glibsm) [inline pkg/command/map_string_test.go]: in the error case like this i would usually check the error message for `strings.Contains` something specific like `bad json` or `extra comma`, I'm not sure what sort of a message is printed here.

File: pkg/command/map_string_test.go [hunk 4]
```diff
@@ -0,0 +1,81 @@
...
+
+import (
+	"strings"
+	"testing"
+
+	"github.com/spf13/viper"
+	"github.com/stretchr/testify/assert"
+)
+
+func TestGetStringMapString(t *testing.T) {
```
Comment (glibsm) [inline pkg/command/map_string_test.go:17]: some more diversity in input and output values would probably be welcome here, for instance `k1=v2, k1=v1`. What's the result there? I'd argue we should maybe error out

File: pkg/command/map_string.go [hunk 5]
```diff
@@ -0,0 +1,43 @@
...
+}
+
+func getStringMapString(vp *viper.Viper, key string, pairSeparator string, keyValueSeparator string) map[string]string {
+	data := vp.Get(key)
+	v, err := cast.ToStringMapStringE(data)
+	if err != nil {
+		var syntaxErr *json.SyntaxError
+		if errors.As(err, &syntaxErr) {
+			switch s := data.(type) {
+			case string:
```
Comment (glibsm) [inline pkg/command/map_string.go]: I think there is some potential of malformed json to not mix well with a value `=` here? Perhaps covering something like `{"foo": "bar",=asdf` would put me more at ease

**Comment by ldelossa** [comment]
@sayboras did we look at viper's marshaling functionality to accomplish this? https://github.com/spf13/viper#unmarshaling
https://sagikazarmark.hu/blog/decoding-custom-formats-with-viper/

This very well may not work, I'm just used to seeing Go librarys implement Marshal functions when having to deal with arbitrary text values.

**Comment by sayboras** [comment]
> did we look at viper's marshaling functionality to accomplish this? https://github.com/spf13/viper#unmarshaling https://sagikazarmark.hu/blog/decoding-custom-formats-with-viper/
> 
> This very well may not work, I'm just used to seeing Go libraries implement Marshal functions when having to deal with arbitrary text values.

:wave: I checked the custom marshall and unmarshall, however, it is nice apporach if we have a self-defined struct (e.g. config), which might not work in our case as we are getting value field by field.

File: pkg/command/map_string_test.go (hunk 3 above)
Comment (sayboras) [reply pkg/command/map_string_test.go]: good point, I see the actual error in debugger only, making sense to make it explicit so that others don't need to re-check it. Let me refactor a little bit, and address related comments below as well.

File: pkg/command/map_string.go [hunk 6]
```diff
@@ -0,0 +1,85 @@
...
+	"errors"
+	"fmt"
+	"regexp"
+	"strings"
+
+	"github.com/spf13/cast"
+	"github.com/spf13/viper"
+)
+
+var keyValueRegex = regexp.MustCompile(`((\w+)=(\w+,))+((\w+)=(\w+))$`)
```
Comment (sayboras) [inline pkg/command/map_string.go]: for better visualisation and checking 

https://jex.im/regulex/#!flags=&re=((%5Cw%2B)%3D(%5Cw%2B%2C))%2B((%5Cw%2B)%3D(%5Cw%2B))%24

File: pkg/command/map_string.go [hunk 7]
```diff
@@ -0,0 +1,85 @@
...
+		var syntaxErr *json.SyntaxError
+		if !errors.As(err, &syntaxErr) {
+			return v, err
+		}
+
+		switch s := data.(type) {
+		case string:
+			// if the input is starting with either '{' or '[', just preserve original json parsing error.
+			firstIndex := firstNonSpaceCharIndex(s)
+			if firstIndex != -1 && (s[firstIndex] == '{' || s[firstIndex] == '[') {
```
Comment (sayboras) [inline pkg/command/map_string.go]: the std json library didn't have dedicate error code for beginning of top level object, so checking first non space char here to make sure right error is returned.

File: pkg/command/map_string.go [hunk 8]
```diff
@@ -0,0 +1,85 @@
...
+				return map[string]string{}, fmt.Errorf("'%s' is not formatted as key=value,key1=value1", s)
+			}
+
+			var v = map[string]string{}
+			kvs := strings.Split(s, ",")
+			for _, kv := range kvs {
+				temp := strings.Split(kv, "=")
+				if len(temp) != 2 {
+					return map[string]string{}, fmt.Errorf("'%s' is not formatted as key=value,key1=value1", s)
+				}
```
Comment (sayboras) [inline pkg/command/map_string.go:65]: ideally, this code block is not required as above isValidKeyValuePair fucntion should cover for invalid format, it's just to be safe to have this check.

File: pkg/command/map_string.go (hunk 5 above)
Comment (sayboras) [reply pkg/command/map_string.go]: thanks, I have added a test case for the same.

File: pkg/command/map_string_test.go (hunk 4 above)
Comment (sayboras) [reply pkg/command/map_string_test.go:17]: good point :100:, I actually miss this scenario in first implementation, thanks :100:

File: pkg/command/map_string.go (hunk 6 above)
Comment (gandro) [reply pkg/command/map_string.go]: Should this be `((\w+)=(\w+,))*((\w+)=(\w+))$` (note: `*` instead of `+` )? 

Otherwise, this will reject single `k=v` pairs, and always require at least two pairs (`k1=v1,k2=v2`).

File: operator/option/config.go [hunk 9]
```diff
@@ -446,15 +447,15 @@ func (c *OperatorConfig) Populate() {
 		c.IPAMSubnetsIDs = m
 	}
 
-	if m := viper.GetStringMapString(IPAMSubnetsTags); len(m) != 0 {
+	if m := command.GetStringMapString(viper.GetViper(), IPAMSubnetsTags); len(m) != 0 {
```
Comment (gandro) [inline operator/option/config.go]: I think we should use `GetStringMapStringE` here, now that we have it, and fail with `log.Fatalf` for any parsing errors. The underlying issue this PR is intending to fix wasn't discovered for almost two years because viper silently swallowed the errors.

File: pkg/command/map_string.go [hunk 10]
```diff
@@ -0,0 +1,85 @@
...
+	"strings"
+
+	"github.com/spf13/cast"
+	"github.com/spf13/viper"
+)
+
+var keyValueRegex = regexp.MustCompile(`((\w+)=(\w+,))+((\w+)=(\w+))$`)
+
+// GetStringMapString contains one enhancement to support k1=v2,k2=v2 compared to original
+// implementation of GetStringMapString function
```
Comment (gandro) [inline pkg/command/map_string.go:21]: Might be worth giving a bit more context here. Could you maybe link to https://github.com/spf13/viper/issues/911 here or in the lint?

**Review by gandro — CHANGES_REQUESTED** [review]
Awesome, thanks a ton for taking care of this. I believe there might be an issue where we reject single `k=v` pairs. Very neat to see you also adding a lint.

File: pkg/command/map_string.go (hunk 6 above)
Comment (sayboras) [reply pkg/command/map_string.go]: Look at this the below unit test :face_exhaling: 

```
		{
			name: "valid format with one pair",
			args: args{
				str: "k1=v1,k2=v2", --> this should be only one kv pair as per description
			},
			want: true,
		},
``

**Review by gandro — APPROVED** [review]
Thanks!

Edit: Marking this for backport to v1.10, as we have users reporting issues with this flag on that version too.

**Comment by sayboras** [comment]
Seems like enabling log.Fatal for these map string fields discovers one issue with kvstore-opt, conformance test failure here is related to this PR, I am taking a closer look now.

File: pkg/command/map_string.go (hunk 1 above)
Comment (aanm) [reply pkg/command/map_string.go:4]: We also have `tools/`, what do you think?

File: pkg/command/map_string.go [hunk 11]
```diff
@@ -0,0 +1,93 @@
...
+// Related upstream issue https://github.com/spf13/viper/issues/911
+func GetStringMapString(vp *viper.Viper, key string) map[string]string {
+	v, _ := GetStringMapStringE(vp, key)
+	return v
+}
+
+// GetStringMapStringE is same as GetStringMapString, but with error
+func GetStringMapStringE(vp *viper.Viper, key string) (map[string]string, error) {
```
Comment (aanm) [inline pkg/command/map_string.go:29]: Why are we returning an initialized `map[string]string{}` for the error cases?

File: pkg/command/map_string.go [hunk 12]
```diff
@@ -0,0 +1,93 @@
...
+	data := vp.Get(key)
+	if data == nil {
+		return map[string]string{}, nil
+	}
+	v, err := cast.ToStringMapStringE(data)
+	if err != nil {
+		var syntaxErr *json.SyntaxError
+		if !errors.As(err, &syntaxErr) {
+			return v, err
```
Comment (aanm) [inline pkg/command/map_string.go:38]: Is this line covered in the unit tests?

**Review by aanm — CHANGES_REQUESTED** [review]

File: pkg/command/map_string.go (hunk 1 above)
Comment (sayboras) [reply pkg/command/map_string.go:4]: tools directory is used for extra utility (e.g. lint check, dev-doctor, etc), should not be used in any main application code.

File: pkg/command/map_string.go (hunk 11 above)
Comment (sayboras) [reply pkg/command/map_string.go:29]: this is to be aligned with upstream function.

https://github.com/spf13/cast/blob/master/caste.go#L863

File: pkg/command/map_string.go (hunk 12 above)
Comment (sayboras) [reply pkg/command/map_string.go:38]: good point :100:

File: pkg/command/map_string.go [hunk 13]
```diff
@@ -0,0 +1,93 @@
...
+		if !isSpace(str[i]) {
+			return i
+		}
+	}
+	return -1
+}
+
+// isSpace returns true if input is space
+// this is same as the function used in json package
+func isSpace(c byte) bool {
```
Comment (ldelossa) [inline pkg/command/map_string.go]: @sayboras Before this merges, can you take a look at the "unicode" package. I think some of these methods are redundant, such as: https://pkg.go.dev/unicode#IsSpace

Once over "unicode", "strings" and "bytes" packages to confirm if any of these helper methods have analogies in the stdlib.

**Review by ldelossa — CHANGES_REQUESTED** [review]

File: pkg/command/map_string.go (hunk 13 above)
Comment (sayboras) [reply pkg/command/map_string.go]: thanks, I was checking this one from std library, it was a private method though.

https://cs.opensource.google/go/go/+/refs/tags/go1.17.6:src/encoding/json/scanner.go;l=197-199

Comment (sayboras) [reply pkg/command/map_string.go]: you are right, it's much simpler with the below

```golang
			// if the input is starting with either '{' or '[', just preserve original json parsing error.
			firstIndex := strings.IndexFunc(s, func(r rune) bool {
				return !unicode.IsSpace(r)
			})
```

**Comment by sayboras** [comment]
Force push to address the above comment from Louis

Also, I add hyphen, dot, and forward slash to allowed value as it's common to have tags like kubernetes.io/cluster/cluster-name:owned if cluster is created by eksctl.

Please find below the diff

<details>
<summary>diff before force push</summary>

```diff
diff --git a/pkg/command/map_string.go b/pkg/command/map_string.go
index 7fe473340b..decb024ad4 100644
--- a/pkg/command/map_string.go
+++ b/pkg/command/map_string.go
@@ -9,12 +9,13 @@ import (
 	"fmt"
 	"regexp"
 	"strings"
+	"unicode"
 
 	"github.com/spf13/cast"
 	"github.com/spf13/viper"
 )
 
-var keyValueRegex = regexp.MustCompile(`((\w+)=(\w+,))*((\w+)=(\w+))$`)
+var keyValueRegex = regexp.MustCompile(`([\w-./]+=[\w-./]+,)*([\w-./]+=[\w-./]+)$`)
 
 // GetStringMapString contains one enhancement to support k1=v2,k2=v2 compared to original
 // implementation of GetStringMapString function
@@ -44,7 +45,9 @@ func GetStringMapStringE(vp *viper.Viper, key string) (map[string]string, error)
 			}
 
 			// if the input is starting with either '{' or '[', just preserve original json parsing error.
-			firstIndex := firstNonSpaceCharIndex(s)
+			firstIndex := strings.IndexFunc(s, func(r rune) bool {
+				return !unicode.IsSpace(r)
+			})
 			if firstIndex != -1 && (s[firstIndex] == '{' || s[firstIndex] == '[') {
 				return v, err
 			}
@@ -75,19 +78,3 @@ func isValidKeyValuePair(str string) bool {
 	}
 	return len(keyValueRegex.ReplaceAllString(str, "")) == 0
 }
-
-// firstNonSpaceCharIndex returns the first non-space character index
-func firstNonSpaceCharIndex(str string) int {
-	for i := range str {
-		if !isSpace(str[i]) {
-			return i
-		}
-	}
-	return -1
-}
-
-// isSpace returns true if input is space
-// this is same as the function used in json package
-func isSpace(c byte) bool {
-	return c <= ' ' && (c == ' ' || c == '\t' || c == '\r' || c == '\n')
-}
diff --git a/pkg/command/map_string_test.go b/pkg/command/map_string_test.go
index 42c0644134..0d511aaafd 100644
--- a/pkg/command/map_string_test.go
+++ b/pkg/command/map_string_test.go
@@ -65,6 +65,29 @@ func TestGetStringMapString(t *testing.T) {
 			want:    expectedResult,
 			wantErr: assert.NoError,
 		},
+		{
+			name: "valid kv format with forward slash",
+			args: args{
+				key:   "FOO_BAR",
+				value: "kubernetes.io/cluster/piano-eks-general-blue-01=owned,kubernetes.io/role/internal-elb=1",
+			},
+			want: map[string]string{
+				"kubernetes.io/cluster/piano-eks-general-blue-01": "owned",
+				"kubernetes.io/role/internal-elb":                 "1",
+			},
+			wantErr: assert.NoError,
+		},
+		{
+			name: "valid kv format with hyphens",
+			args: args{
+				key:   "FOO_BAR",
+				value: "cluster=my-cluster",
+			},
+			want: map[string]string{
+				"cluster": "my-cluster",
+			},
+			wantErr: assert.NoError,
+		},
 		{
 			name: "invalid kv format with extra comma",
 			args: args{
@@ -149,6 +172,28 @@ func Test_isValidKeyValuePair(t *testing.T) {
 			},
 			want: true,
 		},
+		{
+			name: "valid format with hyphen in k and v",
+			args: args{
+				str: "k-1=v-1,k-2=v-2",
+			},
+			want: true,
+		},
+		{
+			name: "valid format with multiple hyphens",
+			args: args{
+				str: "Cluster=piano-eks-general-blue-01",
+			},
+			want: true,
+		},
+		{
+			name: "valid format with forward slash",
+			args: args{
+				str: "kubernetes.io/cluster/piano-eks-general-blue-01=owned",
+			},
+			want: true,
+		},
+
 		{
 			name: "valid format with multiple pairs",
 			args: args{
```

</details>

**Review by ldelossa — APPROVED** [review]

**Comment by tmcatch** [comment]
test-1.22-4.19

**Comment by tmcatch** [comment]
/test-1.22-4.19

**Comment by sayboras** [comment]
/test-1.22-4.19

**Review by aanm — APPROVED** [review]

**Comment by aditighag** [comment]
Requested the review from the current tophat.

File: Documentation/cmdref/cilium-agent.md [hunk 14]
```diff
@@ -131,7 +131,7 @@ cilium-agent [flags]
       --endpoint-status strings                              Enable additional CiliumEndpoint status features (controllers,health,log,policy,state)
       --envoy-log string                                     Path to a separate Envoy log file, if any
       --exclude-local-address strings                        Exclude CIDR from being recognized as local address
-      --fixed-identity-mapping map                           Key-value for the fixed identity mapping which allows to use reserved label for fixed identities (default map[])
+      --fixed-identity-mapping map                           Key-value for the fixed identity mapping which allows to use reserved label for fixed identities
```
Comment (aditighag) [inline Documentation/cmdref/cilium-agent.md]: What do you think of giving an example similar to L20 and L207?

**Review by aditighag — CHANGES_REQUESTED** [review]
LGTM. Have given a suggestion around improving config usability.

File: Documentation/cmdref/cilium-agent.md (hunk 14 above)
Comment (sayboras) [reply Documentation/cmdref/cilium-agent.md]: good point, let me add example for related field.

**Comment by sayboras** [comment]
All CI passed, force push to add example values in cmdref only, please find below the diff

<details>
<summary>diff</summary>

```diff
diff --git a/Documentation/cmdref/cilium-agent.md b/Documentation/cmdref/cilium-agent.md
index 9c799098dd..45dcb6b942 100644
--- a/Documentation/cmdref/cilium-agent.md
+++ b/Documentation/cmdref/cilium-agent.md
@@ -131,7 +131,7 @@ cilium-agent [flags]
       --endpoint-status strings                              Enable additional CiliumEndpoint status features (controllers,health,log,policy,state)
       --envoy-log string                                     Path to a separate Envoy log file, if any
       --exclude-local-address strings                        Exclude CIDR from being recognized as local address
-      --fixed-identity-mapping map                           Key-value for the fixed identity mapping which allows to use reserved label for fixed identities
+      --fixed-identity-mapping map                           Key-value for the fixed identity mapping which allows to use reserved label for fixed identities, e.g. 128=kv-store,128=kv-store
       --force-local-policy-eval-at-source                    Force policy evaluation of all local communication at the source endpoint (default true)
       --gops-port int                                        Port for gops server to listen on (default 9890)
   -h, --help                                                 help for cilium-agent
@@ -196,7 +196,7 @@ cilium-agent [flags]
       --kvstore string                                       Key-value store type
       --kvstore-connectivity-timeout duration                Time after which an incomplete kvstore operation  is considered failed (default 2m0s)
       --kvstore-max-consecutive-quorum-errors int            Max acceptable kvstore consecutive quorum errors before the agent assumes permanent failure (default 2)
-      --kvstore-opt map                                      Key-value store options
+      --kvstore-opt map                                      Key-value store options e.g. etcd.address=127.0.0.1:4001
       --kvstore-periodic-sync duration                       Periodic KVstore synchronization interval (default 5m0s)
       --label-prefix-file string                             Valid label prefixes file path
       --labels strings                                       List of label prefixes used to determine identity of an endpoint
diff --git a/Documentation/cmdref/cilium-health.md b/Documentation/cmdref/cilium-health.md
index fddd7dcc39..889f97de4a 100644
--- a/Documentation/cmdref/cilium-health.md
+++ b/Documentation/cmdref/cilium-health.md
@@ -19,7 +19,7 @@ cilium-health [flags]
   -h, --help                 help for cilium-health
   -H, --host string          URI to cilium-health server API
       --log-driver strings   Logging endpoints to use for example syslog
-      --log-opt map          Log driver options for cilium-health
+      --log-opt map          Log driver options for cilium-health e.g. syslog.level=info,syslog.facility=local5,syslog.tag=cilium-agent
 ```
 
 ### SEE ALSO
diff --git a/Documentation/cmdref/cilium-health_completion.md b/Documentation/cmdref/cilium-health_completion.md
index f1659ff0e7..1f43b61f79 100644
--- a/Documentation/cmdref/cilium-health_completion.md
+++ b/Documentation/cmdref/cilium-health_completion.md
@@ -22,7 +22,7 @@ See each sub-command's help for details on how to use the generated script.
   -D, --debug                Enable debug messages
   -H, --host string          URI to cilium-health server API
       --log-driver strings   Logging endpoints to use for example syslog
-      --log-opt map          Log driver options for cilium-health
+      --log-opt map          Log driver options for cilium-health e.g. syslog.level=info,syslog.facility=local5,syslog.tag=cilium-agent
 ```
 
 ### SEE ALSO
diff --git a/Documentation/cmdref/cilium-health_completion_bash.md b/Documentation/cmdref/cilium-health_completion_bash.md
index bf87bc0aa5..a8ced74b28 100644
--- a/Documentation/cmdref/cilium-health_completion_bash.md
+++ b/Documentation/cmdref/cilium-health_completion_bash.md
@@ -45,7 +45,7 @@ cilium-health completion bash
   -D, --debug                Enable debug messages
   -H, --host string          URI to cilium-health server API
       --log-driver strings   Logging endpoints to use for example syslog
-      --log-opt map          Log driver options for cilium-health
+      --log-opt map          Log driver options for cilium-health e.g. syslog.level=info,syslog.facility=local5,syslog.tag=cilium-agent
 ```
 
 ### SEE ALSO
diff --git a/Documentation/cmdref/cilium-health_completion_fish.md b/Documentation/cmdref/cilium-health_completion_fish.md
index 754adc32f6..4ca095722c 100644
--- a/Documentation/cmdref/cilium-health_completion_fish.md
+++ b/Documentation/cmdref/cilium-health_completion_fish.md
@@ -36,7 +36,7 @@ cilium-health completion fish [flags]
   -D, --debug                Enable debug messages
   -H, --host string          URI to cilium-health server API
       --log-driver strings   Logging endpoints to use for example syslog
-      --log-opt map          Log driver options for cilium-health
+      --log-opt map          Log driver options for cilium-health e.g. syslog.level=info,syslog.facility=local5,syslog.tag=cilium-agent
 ```
 
 ### SEE ALSO
diff --git a/Documentation/cmdref/cilium-health_completion_powershell.md b/Documentation/cmdref/cilium-health_completion_powershell.md
index 08799f0987..b94e1099d5 100644
--- a/Documentation/cmdref/cilium-health_completion_powershell.md
+++ b/Documentation/cmdref/cilium-health_completion_powershell.md
@@ -33,7 +33,7 @@ cilium-health completion powershell [flags]
   -D, --debug                Enable debug messages
   -H, --host string          URI to cilium-health server API
       --log-driver strings   Logging endpoints to use for example syslog
-      --log-opt map          Log driver options for cilium-health
+      --log-opt map          Log driver options for cilium-health e.g. syslog.level=info,syslog.facility=local5,syslog.tag=cilium-agent
 ```
 
 ### SEE ALSO
diff --git a/Documentation/cmdref/cilium-health_completion_zsh.md b/Documentation/cmdref/cilium-health_completion_zsh.md
index 8d6b926a89..75e5262bc3 100644
--- a/Documentation/cmdref/cilium-health_completion_zsh.md
+++ b/Documentation/cmdref/cilium-health_completion_zsh.md
@@ -43,7 +43,7 @@ cilium-health completion zsh [flags]
   -D, --debug                Enable debug messages
   -H, --host string          URI to cilium-health server API
       --log-driver strings   Logging endpoints to use for example syslog
-      --log-opt map          Log driver options for cilium-health
+      --log-opt map          Log driver options for cilium-health e.g. syslog.level=info,syslog.facility=local5,syslog.tag=cilium-agent
 ```
 
 ### SEE ALSO
diff --git a/Documentation/cmdref/cilium-health_get.md b/Documentation/cmdref/cilium-health_get.md
index 1836be8e75..845662b895 100644
--- a/Documentation/cmdref/cilium-health_get.md
+++ b/Documentation/cmdref/cilium-health_get.md
@@ -21,7 +21,7 @@ cilium-health get [flags]
   -D, --debug                Enable debug messages
   -H, --host string          URI to cilium-health server API
       --log-driver strings   Logging endpoints to use for example syslog
-      --log-opt map          Log driver options for cilium-health
+      --log-opt map          Log driver options for cilium-health e.g. syslog.level=info,syslog.facility=local5,syslog.tag=cilium-agent
 ```
 
 ### SEE ALSO
diff --git a/Documentation/cmdref/cilium-health_ping.md b/Documentation/cmdref/cilium-health_ping.md
index 47e16fc579..96eee53119 100644
--- a/Documentation/cmdref/cilium-health_ping.md
+++ b/Documentation/cmdref/cilium-health_ping.md
@@ -20,7 +20,7 @@ cilium-health ping [flags]
   -D, --debug                Enable debug messages
   -H, --host string          URI to cilium-health server API
       --log-driver strings   Logging endpoints to use for example syslog
-      --log-opt map          Log driver options for cilium-health
+      --log-opt map          Log driver options for cilium-health e.g. syslog.level=info,syslog.facility=local5,syslog.tag=cilium-agent
 ```
 
 ### SEE ALSO
diff --git a/Documentation/cmdref/cilium-health_status.md b/Documentation/cmdref/cilium-health_status.md
index b9fd254891..0318b20546 100644
--- a/Documentation/cmdref/cilium-health_status.md
+++ b/Documentation/cmdref/cilium-health_status.md
@@ -24,7 +24,7 @@ cilium-health status [flags]
   -D, --debug                Enable debug messages
   -H, --host string          URI to cilium-health server API
       --log-driver strings   Logging endpoints to use for example syslog
-      --log-opt map          Log driver options for cilium-health
+      --log-opt map          Log driver options for cilium-health e.g. syslog.level=info,syslog.facility=local5,syslog.tag=cilium-agent
 ```
 
 ### SEE ALSO
diff --git a/Documentation/cmdref/cilium-operator-alibabacloud.md b/Documentation/cmdref/cilium-operator-alibabacloud.md
index ca33b5a93a..3252288c60 100644
--- a/Documentation/cmdref/cilium-operator-alibabacloud.md
+++ b/Documentation/cmdref/cilium-operator-alibabacloud.md
@@ -49,7 +49,7 @@ cilium-operator-alibabacloud [flags]
       --k8s-namespace string                      Name of the Kubernetes namespace in which Cilium Operator is deployed in
       --k8s-service-proxy-name string             Value of K8s service-proxy-name label for which Cilium handles the services (empty = all services without service.kubernetes.io/service-proxy-name label)
       --kvstore string                            Key-value store type
-      --kvstore-opt map                           Key-value store options
+      --kvstore-opt map                           Key-value store options e.g. etcd.address=127.0.0.1:4001
       --leader-election-lease-duration duration   Duration that non-leader operator candidates will wait before forcing to acquire leadership (default 15s)
       --leader-election-renew-deadline duration   Duration that current acting master will retry refreshing leadership in before giving up the lock (default 10s)
       --leader-election-retry-period duration     Duration that LeaderElector clients should wait between retries of the actions (default 2s)
diff --git a/Documentation/cmdref/cilium-operator-aws.md b/Documentation/cmdref/cilium-operator-aws.md
index 37658ec469..1a6299f4bf 100644
--- a/Documentation/cmdref/cilium-operator-aws.md
+++ b/Documentation/cmdref/cilium-operator-aws.md
@@ -53,7 +53,7 @@ cilium-operator-aws [flags]
       --k8s-namespace string                      Name of the Kubernetes namespace in which Cilium Operator is deployed in
       --k8s-service-proxy-name string             Value of K8s service-proxy-name label for which Cilium handles the services (empty = all services without service.kubernetes.io/service-proxy-name label)
       --kvstore string                            Key-value store type
-      --kvstore-opt map                           Key-value store options
+      --kvstore-opt map                           Key-value store options e.g. etcd.address=127.0.0.1:4001
       --leader-election-lease-duration duration   Duration that non-leader operator candidates will wait before forcing to acquire leadership (default 15s)
       --leader-election-renew-deadline duration   Duration that current acting master will retry refreshing leadership in before giving up the lock (default 10s)
       --leader-election-retry-period duration     Duration that LeaderElector clients should wait between retries of the actions (default 2s)
diff --git a/Documentation/cmdref/cilium-operator-azure.md b/Documentation/cmdref/cilium-operator-azure.md
index c71e411e02..fe6de3e49b 100644
--- a/Documentation/cmdref/cilium-operator-azure.md
+++ b/Documentation/cmdref/cilium-operator-azure.md
@@ -52,7 +52,7 @@ cilium-operator-azure [flags]
       --k8s-namespace string                      Name of the Kubernetes namespace in which Cilium Operator is deployed in
       --k8s-service-proxy-name string             Value of K8s service-proxy-name label for which Cilium handles the services (empty = all services without service.kubernetes.io/service-proxy-name label)
       --kvstore string                            Key-value store type
-      --kvstore-opt map                           Key-value store options
+      --kvstore-opt map                           Key-value store options e.g. etcd.address=127.0.0.1:4001
       --leader-election-lease-duration duration   Duration that non-leader operator candidates will wait before forcing to acquire leadership (default 15s)
       --leader-election-renew-deadline duration   Duration that current acting master will retry refreshing leadership in before giving up the lock (default 10s)
       --leader-election-retry-period duration     Duration that LeaderElector clients should wait between retries of the actions (default 2s)
diff --git a/Documentation/cmdref/cilium-operator-generic.md b/Documentation/cmdref/cilium-operator-generic.md
index 21211ff191..d1af2f9a14 100644
--- a/Documentation/cmdref/cilium-operator-generic.md
+++ b/Documentation/cmdref/cilium-operator-generic.md
@@ -48,7 +48,7 @@ cilium-operator-generic [flags]
       --k8s-namespace string                      Name of the Kubernetes namespace in which Cilium Operator is deployed in
       --k8s-service-proxy-name string             Value of K8s service-proxy-name label for which Cilium handles the services (empty = all services without service.kubernetes.io/service-proxy-name label)
       --kvstore string                            Key-value store type
-      --kvstore-opt map                           Key-value store options
+      --kvstore-opt map                           Key-value store options e.g. etcd.address=127.0.0.1:4001
       --leader-election-lease-duration duration   Duration that non-leader operator candidates will wait before forcing to acquire leadership (default 15s)
       --leader-election-renew-deadline duration   Duration that current acting master will retry refreshing leadership in before giving up the lock (default 10s)
       --leader-election-retry-period duration     Duration that LeaderElector clients should wait between retries of the actions (default 2s)
diff --git a/Documentation/cmdref/cilium-operator.md b/Documentation/cmdref/cilium-operator.md
index 8b3d9d9c05..a4442e6abe 100644
--- a/Documentation/cmdref/cilium-operator.md
+++ b/Documentation/cmdref/cilium-operator.md
@@ -58,7 +58,7 @@ cilium-operator [flags]
       --k8s-namespace string                      Name of the Kubernetes namespace in which Cilium Operator is deployed in
       --k8s-service-proxy-name string             Value of K8s service-proxy-name label for which Cilium handles the services (empty = all services without service.kubernetes.io/service-proxy-name label)
       --kvstore string                            Key-value store type
-      --kvstore-opt map                           Key-value store options
+      --kvstore-opt map                           Key-value store options e.g. etcd.address=127.0.0.1:4001
       --leader-election-lease-duration duration   Duration that non-leader operator candidates will wait before forcing to acquire leadership (default 15s)
       --leader-election-renew-deadline duration   Duration that current acting master will retry refreshing leadership in before giving up the lock (default 10s)
       --leader-election-retry-period duration     Duration that LeaderElector clients should wait between retries of the actions (default 2s)
diff --git a/Documentation/cmdref/cilium_preflight_migrate-identity.md b/Documentation/cmdref/cilium_preflight_migrate-identity.md
index 2f5b77b6d7..f37bbb632c 100644
--- a/Documentation/cmdref/cilium_preflight_migrate-identity.md
+++ b/Documentation/cmdref/cilium_preflight_migrate-identity.md
@@ -26,7 +26,7 @@ cilium preflight migrate-identity [flags]
       --k8s-api-server string        Kubernetes api address server (for https use --k8s-kubeconfig-path instead)
       --k8s-kubeconfig-path string   Absolute path of the kubernetes kubeconfig file
       --kvstore string               Key-value store type
-      --kvstore-opt map              Key-value store options
+      --kvstore-opt map              Key-value store options e.g. etcd.address=127.0.0.1:4001
 ```
 
 ### Options inherited from parent commands
diff --git a/cilium-health/cmd/root.go b/cilium-health/cmd/root.go
index b04465f7b7..249a31df14 100644
--- a/cilium-health/cmd/root.go
+++ b/cilium-health/cmd/root.go
@@ -59,7 +59,7 @@ func init() {
 	flags.StringP("host", "H", "", "URI to cilium-health server API")
 	flags.StringSlice("log-driver", []string{}, "Logging endpoints to use for example syslog")
 	flags.Var(option.NewNamedMapOptions("log-opts", &logOpts, nil),
-		"log-opt", "Log driver options for cilium-health")
+		"log-opt", "Log driver options for cilium-health e.g. syslog.level=info,syslog.facility=local5,syslog.tag=cilium-agent")
 	viper.BindPFlags(flags)
 
 	flags.StringVar(&cmdRefDir, "cmdref", "", "Path to cmdref output directory")
diff --git a/cilium/cmd/preflight.go b/cilium/cmd/preflight.go
index c183d0b88e..c387ce2a0a 100644
--- a/cilium/cmd/preflight.go
+++ b/cilium/cmd/preflight.go
@@ -63,7 +63,7 @@ func init() {
 	migrateIdentityCmd.Flags().StringVar(&k8sAPIServer, "k8s-api-server", "", "Kubernetes api address server (for https use --k8s-kubeconfig-path instead)")
 	migrateIdentityCmd.Flags().StringVar(&k8sKubeConfigPath, "k8s-kubeconfig-path", "", "Absolute path of the kubernetes kubeconfig file")
 	migrateIdentityCmd.Flags().StringVar(&kvStore, "kvstore", "", "Key-value store type")
-	migrateIdentityCmd.Flags().Var(option.NewNamedMapOptions("kvstore-opts", &kvStoreOpts, nil), "kvstore-opt", "Key-value store options")
+	migrateIdentityCmd.Flags().Var(option.NewNamedMapOptions("kvstore-opts", &kvStoreOpts, nil), "kvstore-opt", "Key-value store options e.g. etcd.address=127.0.0.1:4001")
 	preflightCmd.AddCommand(migrateIdentityCmd)
 
 	validateCNP.Flags().StringVar(&k8sAPIServer, "k8s-api-server", "", "Kubernetes api address server (for https use --k8s-kubeconfig-path instead)")
diff --git a/clustermesh-apiserver/main.go b/clustermesh-apiserver/main.go
index 248bfe302b..e206b7dc04 100644
--- a/clustermesh-apiserver/main.go
+++ b/clustermesh-apiserver/main.go
@@ -211,7 +211,7 @@ func runApiserver() error {
 	option.BindEnv(option.KVstorePeriodicSync)
 
 	flags.Var(option.NewNamedMapOptions(option.KVStoreOpt, &option.Config.KVStoreOpt, nil),
-		option.KVStoreOpt, "Key-value store options")
+		option.KVStoreOpt, "Key-value store options e.g. etcd.address=127.0.0.1:4001")
 	option.BindEnv(option.KVStoreOpt)
 
 	flags.StringVar(&cfg.serviceProxyName, option.K8sServiceProxyName, "", "Value of K8s service-proxy-name label for which Cilium handles the services (empty = all services without service.kubernetes.io/service-proxy-name label)")
diff --git a/daemon/cmd/daemon_main.go b/daemon/cmd/daemon_main.go
index e0b3a38559..67199f8cd8 100644
--- a/daemon/cmd/daemon_main.go
+++ b/daemon/cmd/daemon_main.go
@@ -449,7 +449,7 @@ func initializeFlags() {
 	option.BindEnvWithLegacyEnvFallback(option.DisableEnvoyVersionCheck, "CILIUM_DISABLE_ENVOY_BUILD")
 
 	flags.Var(option.NewNamedMapOptions(option.FixedIdentityMapping, &option.Config.FixedIdentityMapping, option.Config.FixedIdentityMappingValidator),
-		option.FixedIdentityMapping, "Key-value for the fixed identity mapping which allows to use reserved label for fixed identities")
+		option.FixedIdentityMapping, "Key-value for the fixed identity mapping which allows to use reserved label for fixed identities, e.g. 128=kv-store,128=kv-store")
 	option.BindEnv(option.FixedIdentityMapping)
 
 	flags.Duration(option.IdentityChangeGracePeriod, defaults.IdentityChangeGracePeriod, "Time to wait before using new identity on endpoint identity change")
@@ -527,7 +527,7 @@ func initializeFlags() {
 	option.BindEnv(option.IPAllocationTimeout)
 
 	flags.Var(option.NewNamedMapOptions(option.KVStoreOpt, &option.Config.KVStoreOpt, nil),
-		option.KVStoreOpt, "Key-value store options")
+		option.KVStoreOpt, "Key-value store options e.g. etcd.address=127.0.0.1:4001")
 	option.BindEnv(option.KVStoreOpt)
 
 	flags.Duration(option.K8sSyncTimeoutName, defaults.K8sSyncTimeout, "Timeout for synchronizing k8s resources before exiting")
diff --git a/operator/flags.go b/operator/flags.go
index f34f38c6fb..9dbce08fe6 100644
--- a/operator/flags.go
+++ b/operator/flags.go
@@ -223,7 +223,7 @@ func init() {
 	option.BindEnv(option.KVStore)
 
 	flags.Var(option.NewNamedMapOptions(option.KVStoreOpt, &option.Config.KVStoreOpt, nil),
-		option.KVStoreOpt, "Key-value store options")
+		option.KVStoreOpt, "Key-value store options e.g. etcd.address=127.0.0.1:4001")
 	option.BindEnv(option.KVStoreOpt)
 
 	flags.String(option.K8sAPIServer, "", "Kubernetes API server URL")

```

</details>

**Review by joestringer — APPROVED** [review]
LGTM from my codeowners

File: Documentation/cmdref/cilium-agent.md [hunk 15]
```diff
@@ -131,7 +131,7 @@ cilium-agent [flags]
       --endpoint-status strings                              Enable additional CiliumEndpoint status features (controllers,health,log,policy,state)
       --envoy-log string                                     Path to a separate Envoy log file, if any
       --exclude-local-address strings                        Exclude CIDR from being recognized as local address
-      --fixed-identity-mapping map                           Key-value for the fixed identity mapping which allows to use reserved label for fixed identities (default map[])
+      --fixed-identity-mapping map                           Key-value for the fixed identity mapping which allows to use reserved label for fixed identities, e.g. 128=kv-store,128=kv-store
```
Comment (aditighag) [inline Documentation/cmdref/cilium-agent.md]: Why is the k=v repeated in the example?

**Review by aditighag — APPROVED** [review]
Approved from contributing

File: Documentation/cmdref/cilium-agent.md (hunk 15 above)
Comment (sayboras) [reply Documentation/cmdref/cilium-agent.md]: Good spot, it should be 129=kube-dns, i messed up with my local git hook, so the push didn't come through.

Comment (sayboras) [reply Documentation/cmdref/cilium-agent.md]: small diff before force push


```diff
diff --git a/Documentation/cmdref/cilium-agent.md b/Documentation/cmdref/cilium-agent.md
index 45dcb6b942..7733f285c5 100644
--- a/Documentation/cmdref/cilium-agent.md
+++ b/Documentation/cmdref/cilium-agent.md
@@ -131,7 +131,7 @@ cilium-agent [flags]
       --endpoint-status strings                              Enable additional CiliumEndpoint status features (controllers,health,log,policy,state)
       --envoy-log string                                     Path to a separate Envoy log file, if any
       --exclude-local-address strings                        Exclude CIDR from being recognized as local address
-      --fixed-identity-mapping map                           Key-value for the fixed identity mapping which allows to use reserved label for fixed identities, e.g. 128=kv-store,128=kv-store
+      --fixed-identity-mapping map                           Key-value for the fixed identity mapping which allows to use reserved label for fixed identities, e.g. 128=kv-store,129=kube-dns
       --force-local-policy-eval-at-source                    Force policy evaluation of all local communication at the source endpoint (default true)
       --gops-port int                                        Port for gops server to listen on (default 9890)
   -h, --help                                                 help for cilium-agent
diff --git a/daemon/cmd/daemon_main.go b/daemon/cmd/daemon_main.go
index 67199f8cd8..31572ca397 100644
--- a/daemon/cmd/daemon_main.go
+++ b/daemon/cmd/daemon_main.go
@@ -449,7 +449,7 @@ func initializeFlags() {
 	option.BindEnvWithLegacyEnvFallback(option.DisableEnvoyVersionCheck, "CILIUM_DISABLE_ENVOY_BUILD")
 
 	flags.Var(option.NewNamedMapOptions(option.FixedIdentityMapping, &option.Config.FixedIdentityMapping, option.Config.FixedIdentityMappingValidator),
-		option.FixedIdentityMapping, "Key-value for the fixed identity mapping which allows to use reserved label for fixed identities, e.g. 128=kv-store,128=kv-store")
+		option.FixedIdentityMapping, "Key-value for the fixed identity mapping which allows to use reserved label for fixed identities, e.g. 128=kv-store,129=kube-dns")
 	option.BindEnv(option.FixedIdentityMapping)
 
 	flags.Duration(option.IdentityChangeGracePeriod, defaults.IdentityChangeGracePeriod, "Time to wait before using new identity on endpoint identity change")

```

**Review by glibsm — APPROVED** [review]

**Comment by sayboras** [comment]
All reviews are in and all ci jobs were passed before docs update, marking this ready to merge.
