### PR TITLE
ci:tcpdump: harden sniffer startup with retries

### LINKED ISSUE #45256: Conformance GKE: `Failed to execute tcpdump`
```
  🟥 Failed to start sniffers: Failed to start sniffer on client: Failed to execute tcpdump: command failed (pod=cilium-test-2/host-netns-rrzdd, container=host-netns): error sending request: Post "https://136.117.212.82/api/v1/namespaces/cilium-test-2/pods/host-netns-rrzdd/exec?command=nohup&command=sh&command=-c&command=%0A%7B%0A%09%23+Cleanup+any+leftover+files+from+previous+runs.%0A%09rm+-f+%2Ftmp%2Fpod-to-pod-encryption-v2.pid+%2Ftmp%2Fpod-to-pod-encryption-v2.pcap+%2Ftmp%2Fpod-to-pod-encryption-v2.log%0A%0A%09%23+Start+tcpdump+directly+in+background+and+capture+its+PID.%0A%09timeout+60+tcpdump+-i+eth0+-c+1+--immediate-mode+-U+-w+%2Ftmp%2Fpod-to-pod-encryption-v2.pcap+%22src+10.48.91.213+and+dst+10.48.89.101%22+%3E+%2Ftmp%2Fpod-to-pod-encryption-v2.log+2%3E%261+%26%0A%09pid%3D%24%21%0A%09echo+%24pid+%3E+%2Ftmp%2Fpod-to-pod-encryption-v2.pid%0A%0A%09%23+Wait+for+startup+confirmation+and+exit+with+success.%0A%09%23+Exit+with+error+code+if+process+is+not+running.%0A%09for+i+in+%24%28seq+1+10%29%3B+do%0A%09%09sleep+1%0A%09%09grep+-q+%22listening+on+eth0%22+%2Ftmp%2Fpod-to-pod-encryption-v2.log+%26%26+exit+0%0A%09%09kill+-0+%24pid+2%3E%2Fdev%2Fnull+%7C%7C+%7B%0A%09%09%09wait+%24pid%0A%09%09%09exit+%24%3F%0A%09%09%7D%0A%09done%0A%0A%09%23+Process+is+running+but+did+not+receive+confirmation%2C+kill+and+exit.%0A%09kill+-9+%24pid+2%3E%2Fdev%2Fnull%0A%09wait+%24pid%0A%09exit+%24%3F%0A%7D%0A&container=host-netns&stderr=true&stdout=true": dial tcp 136.117.212.82:443: i/o timeout
```
Example: https://github.com/cilium/cilium/actions/runs/24171610514/job/70544319018
Sysdump: [cilium-sysdumps-gke-Installation and Connectivity Test (1.34, us-west1-c, 4, no-tunnel, ).zip](https://github.com/user-attachments/files/26600754/cilium-sysdumps-gke-Installation.and.Connectivity.Test.1.34.us-west1-c.4.no-tunnel.zip)

### PR DESCRIPTION
**Pull request by smagnani96**
We recently observed an I/O timeout when starting the sniffer in CI (see issue below). After investigation, this reminds me of what we were potentially hitting while fixing a similar error in the past https://github.com/cilium/cilium/pull/40487.
It can happen that the API server is overloaded and the exec command fails. This commit implements a simple retry mechanism to attempt to start the sniffer multiple times before giving up, similarly to other commands in CI.

Fixes: https://github.com/cilium/cilium/issues/45256.

### CODE REVIEW

File: cilium-cli/connectivity/sniff/sniffer.go [hunk 1]
```diff
@@ -194,23 +197,32 @@ func Sniff(ctx context.Context, name string, target *check.Pod,
...
+			// Stop the remote sniffer despite tcpdump being wrapped within a `timeout`.
+			err = fmt.Errorf("Failed to execute tcpdump on %s (%s) after %d attempts: %w",
+				target.String(), target.NodeName(), attempt+1, err)
 			err = errors.Join(err, sniffer.stop())
+			return nil, nil, err
+		}
+
+		if err == nil {
+			return sniffer, sniffer.stop, nil
 		}
```
Comment (smagnani96) [inline cilium-cli/connectivity/sniff/sniffer.go:221]: Maybe a time sleep before next loop?

**Comment by smagnani96** [comment]
@pchaigno PTAL 🙏🏼

File: cilium-cli/connectivity/sniff/sniffer.go (hunk 1 above)
Comment (pchaigno) [reply cilium-cli/connectivity/sniff/sniffer.go:221]: I assume the failing command already has a timeout? I'm unsure whether a sleep would make a difference here. Maybe let's try like this and see?

**Review by pchaigno — APPROVED** [review]

File: cilium-cli/connectivity/sniff/sniffer.go (hunk 1 above)
Comment (smagnani96) [reply cilium-cli/connectivity/sniff/sniffer.go:221]: It shouldn't make much difference. I was just wondering, as I saw it being sometimes used in the codebase (as time.Sleep or backoff exponential) and other times don't.

Comment (pchaigno) [reply cilium-cli/connectivity/sniff/sniffer.go:221]: Yeah, ideally we should have some exponential backoff when doing retries, but probably a bit overkill here.
