### PR TITLE
Move CNI configuration file management in to the agent process

### LINKED ISSUE #14892: Embed cni-(un)install.sh behaviour in the agent process instead
# Proposal

The behaviour introduced [in this PR](https://github.com/cilium/cilium/pull/14192) caused some custom CNI deployments to break. Example: https://github.com/cilium/cilium/issues/14838. This also broke the deployment script bundled with `microk8s` (cc @joestringer), which we do aim to keep in a working state, although not being a part of this repo.

Since this was considered a (possibly) breaking change for some deployments, we didn't backport to 1.9 and earlier. Now we have some extra data points of how and where this can break, the scope for a refactor of `cni-(un)install.sh` has become clearer. Below is a blueprint of the work to be done.

Additionally, this behaviour needs some documentation in general, and Cilium's touch points with the CNI stack need to be more clearly defined. Currently, reading the script is required to understand how to correctly integrate Cilium with custom nodepool images.

## Baseline

A few rules we should aim for with the new implementation:

- `/etc/cni/net.d` should no longer written to by `cni-(un)install.sh`
- A CNI config is only installed by the agent when Cilium is ready
- `--read-cni-conf` and `--write-cni-conf-when-ready` and the machinery behind it should be used as the central code path behind managing a CNI config.
- Must implement CNI-exclusive mode (agent renames all non-Cilium CNI's to `*.cilium_bak`)
- Must implement CNI config cleanup right before agent stops

Misc:
- `cni-(un)install.sh` could be renamed to `k8s-poststart.sh` and `k8s-prestop.sh` if it no longer touches CNI resources. There are some leftover bits in there that shell out to `ip` for Flannel chaining and whatnot that we might need to preserve, but are not that critical.

## Scenarios to support

Below is a list of deployment/configuration scenarios we want to support. These scenarios were established by looking at the use cases of our users, as well as some bug reports we've received.

### 100% Cilium-managed (default)

Cilium takes full ownership of `/etc/cni/net.d/` on the host and takes exclusivity. A 'custom' CNI config can still be specified by pointing `--read-cni-conf` at a file by e.g. mounting a ConfigMap into the container, or by provisioning a template file on the host where the agent can access it. (e.g. using cloud-init)

-> Helm `cni.manual=false` (default)
-> Helm `cni.exclusive=true` (default)

- An appropriate CNI config is automatically chosen based on the chaining config when `--read-cni-conf` is empty. (default)
- If `--read-cni-conf` is set, read the file at the given path instead of automatically choosing one
- The selected config is written to `--write-cni-conf`'s path (default `/etc/cni/net.d/05-cilium.conf(list)

### Unmanaged/manual/custom CNI mode

Cilium doesn't touch `/etc/cni/net.d/` in any way. neither at startup nor during shutdown.

-> Helm `cni.manual=true` set, but also needs to obey existing `CILIUM_CUSTOM_CNI_CONF` for compatibility purposes.

- Disables all interactions with `/etc/cni/net.d/`, but still debating whether or not to still install the `cilium-cni` binary.
- `--read-cni-conf` and `--write-cni-conf..` should remain empty, but will be ignored either way

### Non-exclusive CNI

Cilium installs and cleans up its own CNI config when the agent is ready, but doesn't touch any others.

-> `cni.manual=false` (default)
-> `cni.exclusive=false` -> no CNI exclusivity

- A fitting CNI config is chosen at runtime just like in managed mode
- `--write-cni-conf..` and `--read-cni-conf` are obeyed

## Alternate proposal: `cilium cni`

Instead of embedding the logic into the agent daemon itself, create `cilium cni install/uninstall` commands to use as postStart and preStop respectively. This would be a simple lift&shift from the current shell scripts.

- `install`
  - Remove existing/active Cilium config(s)
  - Rename non-Cilium CNI configs to `*.cilium_bak`
  - Copy Cilium's CNI binary from the container to the host file system
  - Write out appropriate CNI config for the current environment
- `uninstall`
  - Remove active Cilium config
  - Remove Cilium CNI binary

@aanm

### PR DESCRIPTION
**Pull request by squeed**
Fixes: #14892

This removes almost all of the logic in `cni-install.sh` and brings it in the agent. It also obsoletes some (broken) environment variables, and generally cleans up how customizing CNI configuration is handled.

It also configures the agent's healthz handling so that the agent won't go Ready until a CNI configuration file has been written to disk. This means less of a risk that we take down clusters due to some kind of CNI issue.

~TODO:~
- [x] Remove obsolete / incorrect documentation
- [x] Move config file cleanup in to the agent
- [x] Write better docs :-)

```release-note
The CNI configuration file is now written only after the agent has successfully started up. Configuring a custom CNI configuration file is now simpler and more reliable. See the docs for more details.
```

### CODE REVIEW

**Comment by squeed** [comment]
I have a few small code comment updates, but I'll save them (and the inevitable CI run) for after the first round of review.

File: daemon/cmd/cni.go [hunk 1]
```diff
@@ -0,0 +1,354 @@
...
+// ** Cilium-manged configuration file **
+// cni.chainingMode -- : What "flavor" of CNI configuration to install
+// cni.logFile -- : A log file for the CNI plugin to write to
+// debug.enabled -- : Whether or not to enable debugging
+//
+// ** Installation options **
+// cni.exclusive -- : delete all other existing CNI configuration files
+// cni.confPath -- : path to CNI configuration directory on the host
+//
+// This should be run in a goroutine, as it will, in certain cases, watch
```
Comment (squeed) [inline daemon/cmd/cni.go]: This comment is wrong and will be deleted shortly.

File: daemon/cmd/cni.go [hunk 2]
```diff
@@ -0,0 +1,354 @@
...
+	cleaner.cleanupFuncs.Add(func() {
+		removeCNIConfFile(opts)
+	})
+}
+
+// installCNIConfFile writes the CNI configuration file to disk.
+// This is done once the daemon has started up, to signify to the
+// kubelet that we're ready to handle sandbox creation.
+// There are numerous, conflicting CNI options, exposed in Helm and
+// the cilium-config config map.
```
Comment (squeed) [inline daemon/cmd/cni.go]: I rewrote this comment to only discuss cilium-config settings, as they're more relevant.

File: daemon/cmd/cni.go [hunk 3]
```diff
@@ -0,0 +1,354 @@
...
+
+	if err := os.WriteFile(tempPath, data, 0644); err != nil {
+		return fmt.Errorf("failed to write temporary file %s: %w", tempPath, err)
+	}
+
+	if err := os.Rename(tempPath, realPath); err != nil {
+		return fmt.Errorf("failed to rename %s to %s: %w", tempPath, realPath, err)
+	}
+	return nil
+}
```
Comment (tklauser) [inline daemon/cmd/cni.go]: If possible, let's use the `github.com/google/renameio` package for atomic writes. We already vendor it and use it in some other places in the code base.

File: daemon/cmd/cni.go [hunk 4]
```diff
@@ -0,0 +1,354 @@
+package cmd
```
Comment (tklauser) [inline daemon/cmd/cni.go:4]: This file should have a license/copyright header:

```
// SPDX-License-Identifier: Apache-2.0                                                                                                                                                                                                                                          
// Copyright Authors of Cilium
```

Same for other newly added files. Ideally we'd add a CI check for that in the future :slightly_smiling_face:

File: daemon/cmd/cni.go [hunk 5]
```diff
@@ -0,0 +1,354 @@
...
+      "type": "portmap",
+      "capabilities": {"portMappings": true}
+    }
+  ]
+}
+`,
+}
+
+// The CNI plugin config we inject in to the plugins[] array of existing AWS configs
+var awsCNIEntry = `
```
Comment (tklauser) [inline daemon/cmd/cni.go]: Nit: this could be a `const`.

File: daemon/cmd/cni.go [hunk 6]
```diff
@@ -0,0 +1,354 @@
...
+	if err != nil {
+		return nil, fmt.Errorf("failed to modify existing AWS CNI config at %s: %w", found, err)
+	}
+	log.Infof("Inserting cilium in to CNI configuration file at %s", found)
+	return out, nil
+}
+
+// renderCNITemplate applies any cni template replacements
+// right now, just sets .Debug and Logfile
+func renderCNITemplate(in string, opts *option.DaemonConfig) string {
```
Comment (tklauser) [inline daemon/cmd/cni.go]: Let's return a `[]byte` here. It seems all call sites convert this to `[]byte` eventually, so rather return it in that form (and potentially avoid some unnecessary allocs).

```suggestion
func renderCNITemplate(in string, opts *option.DaemonConfig) []byte {
```

**Review by tklauser — COMMENTED** [review]
Some drive-bye comments, mostly nits. Will do an in-depth review by the end of the week.

**Review by qmonnet — APPROVED** [review]
Looks good to me, should the new options and Helm values be documented in Documentation/operations/upgrade.rst?

**Comment by squeed** [comment]
> Looks good to me, should the new options and Helm values be documented in Documentation/operations/upgrade.rst?

Sure, good point. There actually aren’t any new helm variables, but there are new config options. I’ll add those.

File: daemon/cmd/cni.go [hunk 7]
```diff
@@ -0,0 +1,354 @@
...
+}
+
+// mergeExistingAWSCNIConfig looks for an existing AWS cni configuration file
+// and modifies it to include Cilium. This is because they do something
+// "special" for v6-only clusters.
+//
+// cniDir is the directory in the container to look for AWS CNI config, and
+// pluginConfig is the raw json to insert
+//
+// This will wait for the file to exist.
```
Comment (squeed) [inline daemon/cmd/cni.go]: Note to self: this comment is wrong.

**Review by rolinh — APPROVED** [review]
Vendor and API changes lgtm.

**Comment by squeed** [comment]
@tklauser Updated based on feedback, PTAL

File: pkg/option/config.go [hunk 8]
```diff
@@ -2615,7 +2629,7 @@ func (c *DaemonConfig) Validate(vp *viper.Viper) error {
 			int64(defaults.KVstoreLeaseMaxTTL.Seconds()))
 	}
 
-	if c.WriteCNIConfigurationWhenReady != "" && c.ReadCNIConfiguration == "" {
+	if c.WriteCNIConfigurationWhenReady == "" && c.ReadCNIConfiguration != "" {
 		return fmt.Errorf("%s must be set when using %s", ReadCNIConfiguration, WriteCNIConfigurationWhenReady)
```
Comment (tklauser) [inline pkg/option/config.go]: This check no longer matches the error text. Do we even still need this check? It seems like `(*Daemon).startCNIConfWrite` will just bail out if `c.WriteCNIConfigurationWhenReady == ""`.

In case the error message is changed, we should probably reverse the dependency in the option's help texts as well:

https://github.com/cilium/cilium/blob/770d07534cf3626d45a5f37e0481152794fc3287/daemon/cmd/daemon_main.go#L879-L880

File: daemon/cmd/cni.go [hunk 9]
```diff
@@ -0,0 +1,331 @@
...
+  ]
+}
+`,
+}
+
+// The CNI plugin config we inject in to the plugins[] array of existing AWS configs
+const awsCNIEntry = `
+{
+	"type": "cilium-cni", 
+	"enable-debug": {{.Debug | js }},
```
Comment (tklauser) [inline daemon/cmd/cni.go]: Ultra-nit: trailing whitespaces
```suggestion
	"type": "cilium-cni",
	"enable-debug": {{.Debug | js }},
```

File: daemon/cmd/cni.go [hunk 10]
```diff
@@ -0,0 +1,331 @@
...
+	})
+}
+
+// installCNIConfFile tries to render and write the CNI configuration file to disk.
+// Returns error on failure.
+func installCNIConfFile(opts *option.DaemonConfig) error {
+	// Determine the path to the CNI conf directory
+	confDir, filename := path.Split(opts.WriteCNIConfigurationWhenReady)
+
+	// we used to document overriding the CNI file with tne env var CNI_CONF_NAME
```
Comment (tklauser) [inline daemon/cmd/cni.go]: nit:
```suggestion
	// we used to document overriding the CNI file with the env var CNI_CONF_NAME
```

**Review by tklauser — APPROVED** [review]
Nice work! I've mainly looked at the agent and CNI plugin bits and have one question inline about the reversed dependency between `write-cni-conf-when-ready` and `read-cni-conf`. Apart from that only two _very_ minor nits.

File: daemon/cmd/cni.go (hunk 9 above)
Comment (squeed) [reply daemon/cmd/cni.go]: Hah, I fixed this, but then my laptop died and took the hard drive with it :-)

File: pkg/option/config.go (hunk 8 above)
Comment (squeed) [reply pkg/option/config.go]: Fair enough -- we don't really need the error check. It would just catch an unlikely misconfiguration, essentially equivalent to `cp <src>` without the matching `<dst>`

**Review by sayboras — APPROVED** [review]
LGTM 💯

**Comment by squeed** [comment]
OK, updated for feedback, added some minor migration notes.

**Comment by squeed** [comment]
This needs to merge AFTER #21444

**Comment by squeed** [comment]
OK, dependent PR merged, rebased.

**Comment by sayboras** [comment]
Failure on docs generation seems related

```
make -C Documentation update-cmdref
```

**Comment by squeed** [comment]
> Failure on docs generation seems related

Whoops, fixed and rebased.

**Comment by sayboras** [comment]
Unit test failure in Travis seems related to this change. 

```
--- FAIL: TestRenderCNIConf (0.00s)
    cni_test.go:98: 
                Error Trace:    /home/tammach/go/src/github.com/cilium/cilium/daemon/cmd/cni_test.go:98
                Error:          Not equal: 
                                expected: []byte{0xa, 0x7b, 0xa, 0x9, 0x22, 0x74, 0x79, 0x70, 0x65, 0x22, 0x3a, 0x20, 0x22, 0x63, 0x69, 0x6c, 0x69, 0x75, 0x6d, 0x2d, 0x63, 0x6e, 0x69, 0x22, 0x2c, 0xa, 0x9, 0x22, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x2d, 0x64, 0x65, 0x62, 0x75, 0x67, 0x22, 0x3a, 0x20, 0x66, 0x61, 0x6c, 0x73, 0x65, 0x2c, 0xa, 0x9, 0x22, 0x6c, 0x6f, 0x67, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x3a, 0x20, 0x22, 0x2f, 0x6f, 0x70, 0x74, 0x5c, 0x22, 0x2f, 0x63, 0x6e, 0x69, 0x2e, 0x6c, 0x6f, 0x67, 0x22, 0xa, 0x7d, 0xa}
                                actual  : []byte{0xa, 0x7b, 0xa, 0x9, 0x22, 0x74, 0x79, 0x70, 0x65, 0x22, 0x3a, 0x20, 0x22, 0x63, 0x69, 0x6c, 0x69, 0x75, 0x6d, 0x2d, 0x63, 0x6e, 0x69, 0x22, 0x2c, 0x20, 0xa, 0x9, 0x22, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x2d, 0x64, 0x65, 0x62, 0x75, 0x67, 0x22, 0x3a, 0x20, 0x66, 0x61, 0x6c, 0x73, 0x65, 0x2c, 0x20, 0xa, 0x9, 0x22, 0x6c, 0x6f, 0x67, 0x2d, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x3a, 0x20, 0x22, 0x2f, 0x6f, 0x70, 0x74, 0x5c, 0x22, 0x2f, 0x63, 0x6e, 0x69, 0x2e, 0x6c, 0x6f, 0x67, 0x22, 0xa, 0x7d, 0xa}
                                
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,8 +1,8 @@
                                -([]uint8) (len=82) {
                                +([]uint8) (len=84) {
                                  00000000  0a 7b 0a 09 22 74 79 70  65 22 3a 20 22 63 69 6c  |.{.."type": "cil|
                                - 00000010  69 75 6d 2d 63 6e 69 22  2c 0a 09 22 65 6e 61 62  |ium-cni",.."enab|
                                - 00000020  6c 65 2d 64 65 62 75 67  22 3a 20 66 61 6c 73 65  |le-debug": false|
                                - 00000030  2c 0a 09 22 6c 6f 67 2d  66 69 6c 65 22 3a 20 22  |,.."log-file": "|
                                - 00000040  2f 6f 70 74 5c 22 2f 63  6e 69 2e 6c 6f 67 22 0a  |/opt\"/cni.log".|
                                - 00000050  7d 0a                                             |}.|
                                + 00000010  69 75 6d 2d 63 6e 69 22  2c 20 0a 09 22 65 6e 61  |ium-cni", .."ena|
                                + 00000020  62 6c 65 2d 64 65 62 75  67 22 3a 20 66 61 6c 73  |ble-debug": fals|
                                + 00000030  65 2c 20 0a 09 22 6c 6f  67 2d 66 69 6c 65 22 3a  |e, .."log-file":|
                                + 00000040  20 22 2f 6f 70 74 5c 22  2f 63 6e 69 2e 6c 6f 67  | "/opt\"/cni.log|
                                + 00000050  22 0a 7d 0a                                       |".}.|
                                 }
```

**Comment by squeed** [comment]
> Unit test failure in Travis seems related to this change.

Sure is. Whoops. Fixed.
