### PR TITLE
bpf: fix ipv6 extension header parsing error

### LINKED ISSUE #24187: Cilium is droping ipv6 packets with auth extension header
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

# env

##  pods

```
➜  cilium git:(v1.12.6) kubectl get pods -A -o wide
NAMESPACE            NAME                                         READY   STATUS    RESTARTS   AGE     IP             NODE                 NOMINATED NODE   READINESS GATES
kube-system          cilium-5xdwm                                 1/1     Running   0          6h38m   172.18.0.4     kind-worker3         <none>           <none>
kube-system          cilium-gqxdx                                 1/1     Running   0          6h38m   172.18.0.5     kind-worker          <none>           <none>
kube-system          cilium-operator-74559f97bf-gmkdm             1/1     Running   0          6h38m   172.18.0.3     kind-worker2         <none>           <none>
kube-system          cilium-rmbnl                                 1/1     Running   0          6h38m   172.18.0.2     kind-control-plane   <none>           <none>
kube-system          cilium-tbwqj                                 1/1     Running   0          6h38m   172.18.0.3     kind-worker2         <none>           <none>
kube-system          coredns-565d847f94-rh9g5                     1/1     Running   0          6h39m   10.244.1.233   kind-worker3         <none>           <none>
kube-system          coredns-565d847f94-v2vs7                     1/1     Running   0          6h39m   10.244.1.75    kind-worker3         <none>           <none>
kube-system          etcd-kind-control-plane                      1/1     Running   0          6h39m   172.18.0.2     kind-control-plane   <none>           <none>
kube-system          kube-apiserver-kind-control-plane            1/1     Running   0          6h39m   172.18.0.2     kind-control-plane   <none>           <none>
kube-system          kube-controller-manager-kind-control-plane   1/1     Running   0          6h39m   172.18.0.2     kind-control-plane   <none>           <none>
kube-system          kube-scheduler-kind-control-plane            1/1     Running   0          6h39m   172.18.0.2     kind-control-plane   <none>           <none>
local-path-storage   local-path-provisioner-684f458cdd-vgnx9      1/1     Running   0          6h39m   10.244.1.27    kind-worker3         <none>           <none>
test-pod1            test-pod1-6bdb469947-6bxl7                   1/1     Running   0          5h21m   10.244.2.84    kind-worker          <none>           <none>
test-pod2            test-pod2-76457d55db-b9vrt                   1/1     Running   0          5h21m   10.244.3.59    kind-worker2         <none>           <none>
```

# test

### cilium endpoint list

```
root@kind-worker:/home/cilium# cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                                IPv6                  IPv4           STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                                                  
249        Disabled           Disabled          1          reserved:host                                                                                                   ready   
684        Disabled           Disabled          31569      k8s:id=tk1                                                                 fd00:10:244:2::478f   10.244.2.84    ready   
                                                           k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=test-pod1                                                
                                                           k8s:io.cilium.k8s.policy.cluster=kind-kind                                                                              
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                                         
                                                           k8s:io.kubernetes.pod.namespace=test-pod1                                                                               
2630       Disabled           Disabled          4          reserved:health                                                            fd00:10:244:2::f51a   10.244.2.174   ready
```

### cilium monitor

ipv6 packets was dropped

```
xx drop (CT: Truncated or invalid header) flow 0x0 to endpoint 0, file bpf_lxc.c line 712, , identity 31569->unknown: fd00:10:244:2::478f -> fd00:10:244:3::22be
xx drop (CT: Truncated or invalid header) flow 0x0 to endpoint 0, file bpf_lxc.c line 712, , identity 31569->unknown: fd00:10:244:2::478f -> fd00:10:244:3::22be
xx drop (CT: Truncated or invalid header) flow 0x0 to endpoint 0, file bpf_lxc.c line 712, , identity 31569->unknown: fd00:10:244:2::478f -> fd00:10:244:3::22be
xx drop (CT: Truncated or invalid header) flow 0x0 to endpoint 0, file bpf_lxc.c line 712, , identity 31569->unknown: fd00:10:244:2::478f -> fd00:10:244:3::22be
xx drop (CT: Truncated or invalid header) flow 0x0 to endpoint 0, file bpf_lxc.c line 712, , identity 31569->unknown: fd00:10:244:2::478f -> fd00:10:244:3::22be
```

## test-pod1

```
[root@test-pod1-6bdb469947-6bxl7 /]# ip a show dev eth0
11: eth0@if12: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 22:67:c9:71:99:10 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.244.2.84/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fd00:10:244:2::478f/128 scope global nodad 
       valid_lft forever preferred_lft forever
    inet6 fe80::2067:c9ff:fe71:9910/64 scope link 
       valid_lft forever preferred_lft forever
```

send ipv6 packets to test-pod2 with scapy

```
#!/usr/bin/python2

from scapy.all import *
from socket import *
import sys

if __name__ == "__main__":
    if len(sys.argv) != 6:
        print("smac, dmac, saddr, daddr, iface needed")
        sys.exit(-1)

    smac = sys.argv[1]
    dmac = sys.argv[2]
    saddr = sys.argv[3]
    daddr = sys.argv[4]
    iface = sys.argv[5]

    # ipv6
    sendp(Ether(src=smac, dst=dmac)/IPv6(src=saddr, dst=daddr)/TCP(),
            iface=iface, loop=1, inter=0.1, count=5)
    # ipv6/hop/auth
    sa = SecurityAssociation(AH, spi=0x222, auth_algo='SHA2-384-192', auth_key=b'secret key')
    pkt = IPv6(src=saddr, dst=daddr)/IPv6ExtHdrHopByHop()/TCP()
    pkt = sa.encrypt(pkt)
    pkt = Ether(src=smac, dst=dmac)/pkt
    # pkt = Ether(src=smac, dst=dmac)/IPv6(src=saddr, dst=daddr)/IPv6ExtHdrHopByHop()/AH(nh=IPPROTO_TCP)/TCP()/"TEST"
    pkt.show2()
    sendp(pkt, iface=iface, loop=1, inter=0.1, count=5)
    # ipv6/hop/hop
    pkt = Ether(src=smac, dst=dmac)/IPv6(src=saddr, dst=daddr)/IPv6ExtHdrHopByHop()/IPv6ExtHdrHopByHop()/TCP()
    pkt.show2()
    sendp(pkt, iface=iface, loop=1, inter=0.1, count=5)
```

### cilium endpoint list

```
root@kind-worker:/home/cilium# cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                                IPv6                  IPv4           STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                                                                  
249        Disabled           Disabled          1          reserved:host                                                                                                   ready   
684        Disabled           Disabled          31569      k8s:id=tk1                                                                 fd00:10:244:2::478f   10.244.2.84    ready   
                                                           k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=test-pod1                                                
                                                           k8s:io.cilium.k8s.policy.cluster=kind-kind                                                                              
                                                           k8s:io.cilium.k8s.policy.serviceaccount=default                                                                         
                                                           k8s:io.kubernetes.pod.namespace=test-pod1                                                                               
2630       Disabled           Disabled          4          reserved:health                                                            fd00:10:244:2::f51a   10.244.2.174   ready
```

## test-pod2

```
[root@test-pod2-76457d55db-b9vrt /]# ip a show dev eth0
7: eth0@if8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 32:1e:42:44:b8:8b brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.244.3.59/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fd00:10:244:3::22be/128 scope global nodad 
       valid_lft forever preferred_lft forever
    inet6 fe80::301e:42ff:fe44:b88b/64 scope link 
       valid_lft forever preferred_lft forever
```

try capture packets

lost ipv6 packets with auth header. 

```
[root@test-pod2-76457d55db-b9vrt /]# tcpdump -A -i any host fd00:10:244:3::22be -nnne -w test.pcap
dropped privs to tcpdump
tcpdump: listening on any, link-type LINUX_SLL (Linux cooked v1), capture size 262144 bytes
^C20 packets captured
20 packets received by filter
0 packets dropped by kernel
[root@test-pod2-76457d55db-b9vrt /]# tcpdump -r test.pcap -nnne
reading from file test.pcap, link-type LINUX_SLL (Linux cooked v1)
dropped privs to tcpdump
17:15:55.391981  In e6:63:9a:c6:92:68 ethertype IPv6 (0x86dd), length 76: fd00:10:244:2::478f.20 > fd00:10:244:3::22be.80: Flags [S], seq 0, win 8192, length 0
17:15:55.391995 Out 32:1e:42:44:b8:8b ethertype IPv6 (0x86dd), length 76: fd00:10:244:3::22be.80 > fd00:10:244:2::478f.20: Flags [R.], seq 0, ack 1, win 0, length 0
17:15:55.492998  In e6:63:9a:c6:92:68 ethertype IPv6 (0x86dd), length 76: fd00:10:244:2::478f.20 > fd00:10:244:3::22be.80: Flags [S], seq 0, win 8192, length 0
17:15:55.493006 Out 32:1e:42:44:b8:8b ethertype IPv6 (0x86dd), length 76: fd00:10:244:3::22be.80 > fd00:10:244:2::478f.20: Flags [R.], seq 0, ack 1, win 0, length 0
17:15:55.594211  In e6:63:9a:c6:92:68 ethertype IPv6 (0x86dd), length 76: fd00:10:244:2::478f.20 > fd00:10:244:3::22be.80: Flags [S], seq 0, win 8192, length 0
17:15:55.594223 Out 32:1e:42:44:b8:8b ethertype IPv6 (0x86dd), length 76: fd00:10:244:3::22be.80 > fd00:10:244:2::478f.20: Flags [R.], seq 0, ack 1, win 0, length 0
17:15:55.695383  In e6:63:9a:c6:92:68 ethertype IPv6 (0x86dd), length 76: fd00:10:244:2::478f.20 > fd00:10:244:3::22be.80: Flags [S], seq 0, win 8192, length 0
17:15:55.695392 Out 32:1e:42:44:b8:8b ethertype IPv6 (0x86dd), length 76: fd00:10:244:3::22be.80 > fd00:10:244:2::478f.20: Flags [R.], seq 0, ack 1, win 0, length 0
17:15:55.796582  In e6:63:9a:c6:92:68 ethertype IPv6 (0x86dd), length 76: fd00:10:244:2::478f.20 > fd00:10:244:3::22be.80: Flags [S], seq 0, win 8192, length 0
17:15:55.796594 Out 32:1e:42:44:b8:8b ethertype IPv6 (0x86dd), length 76: fd00:10:244:3::22be.80 > fd00:10:244:2::478f.20: Flags [R.], seq 0, ack 1, win 0, length 0
17:15:56.446211  In e6:63:9a:c6:92:68 ethertype IPv6 (0x86dd), length 92: fd00:10:244:2::478f > fd00:10:244:3::22be: HBH HBH 20 > 80: Flags [S], seq 0, win 8192, length 0
17:15:56.446228 Out 32:1e:42:44:b8:8b ethertype IPv6 (0x86dd), length 140: fd00:10:244:3::22be > fd00:10:244:2::478f: ICMP6, parameter problem, next header - octet 40, length 84
17:15:56.548016  In e6:63:9a:c6:92:68 ethertype IPv6 (0x86dd), length 92: fd00:10:244:2::478f > fd00:10:244:3::22be: HBH HBH 20 > 80: Flags [S], seq 0, win 8192, length 0
17:15:56.548031 Out 32:1e:42:44:b8:8b ethertype IPv6 (0x86dd), length 140: fd00:10:244:3::22be > fd00:10:244:2::478f: ICMP6, parameter problem, next header - octet 40, length 84
17:15:56.649895  In e6:63:9a:c6:92:68 ethertype IPv6 (0x86dd), length 92: fd00:10:244:2::478f > fd00:10:244:3::22be: HBH HBH 20 > 80: Flags [S], seq 0, win 8192, length 0
17:15:56.649911 Out 32:1e:42:44:b8:8b ethertype IPv6 (0x86dd), length 140: fd00:10:244:3::22be > fd00:10:244:2::478f: ICMP6, parameter problem, next header - octet 40, length 84
17:15:56.751859  In e6:63:9a:c6:92:68 ethertype IPv6 (0x86dd), length 92: fd00:10:244:2::478f > fd00:10:244:3::22be: HBH HBH 20 > 80: Flags [S], seq 0, win 8192, length 0
17:15:56.751875 Out 32:1e:42:44:b8:8b ethertype IPv6 (0x86dd), length 140: fd00:10:244:3::22be > fd00:10:244:2::478f: ICMP6, parameter problem, next header - octet 40, length 84
17:15:56.853919  In e6:63:9a:c6:92:68 ethertype IPv6 (0x86dd), length 92: fd00:10:244:2::478f > fd00:10:244:3::22be: HBH HBH 20 > 80: Flags [S], seq 0, win 8192, length 0
17:15:56.853935 Out 32:1e:42:44:b8:8b ethertype IPv6 (0x86dd), length 140: fd00:10:244:3::22be > fd00:10:244:2::478f: ICMP6, parameter problem, next header - octet 40, length 84
```
# analysis

"xx drop (CT: Truncated or invalid header) flow 0x0 to endpoint 0, file bpf_lxc.c line 712, , identity 31569->unknown: fd00:10:244:2::478f -> fd00:10:244:3::22be", 

maybe packet was droped here 

`bpf/lib/ipv6.h@ipv6_hdrlen`

```
48:static __always_inline int ipv6_hdrlen(struct __ctx_buff *ctx, __u8 *nexthdr)
49-{
50-     int i, len = sizeof(struct ipv6hdr);
51-     struct ipv6_opt_hdr opthdr __align_stack_8;
52-     __u8 nh = *nexthdr;
53-
54-#pragma unroll
55-     for (i = 0; i < IPV6_MAX_HEADERS; i++) {
56-             switch (nh) {
57-             case NEXTHDR_NONE:
58-                     return DROP_INVALID_EXTHDR;
59-
60-             case NEXTHDR_FRAGMENT:
61-                     return DROP_FRAG_NOSUPPORT;
62-
63-             case NEXTHDR_HOP:
64-             case NEXTHDR_ROUTING:
65-             case NEXTHDR_AUTH:
66-             case NEXTHDR_DEST:
67-                     if (ctx_load_bytes(ctx, ETH_HLEN + len, &opthdr, sizeof(opthdr)) < 0)
68-                             return DROP_INVALID;
69-
70-                     nh = opthdr.nexthdr;
71-                     if (nh == NEXTHDR_AUTH)
72-                             len += ipv6_authlen(&opthdr);
73-                     else
74-                             len += ipv6_optlen(&opthdr);
75-                     break;
76-
77-             default:
78-                     *nexthdr = nh;
79-                     return len;
80-             }
81-     }
82-
83-     /* Reached limit of supported extension headers */
84-     return DROP_INVALID_EXTHDR;
85-}
```

Line 70 needs to be put after line 74

parse ipv6/hop/auth/tcp packet

**first loop**

before line:70 (nh = opthdr.nexthdr;)

nh=hop, len=sizeof(ipv6hdr), opthdr=head_of_hop

after line:70 

nh=auth, len=sizeof(ipv6hdr), opthdr=head_of_hop

after line: 74 (len += ipv6_optlen(&opthdr);)

nh=auth, len=sizeof(ipv6hdr) + auth_hdrlen

**second loop**

before line:70 (nh = opthdr.nexthdr;)

nh=auth, len=sizeof(ipv6hdr) + auth_hdrlen, opthdr=wrong offset(should be sizeof(ipv6hdr) + hop_hdrlen); **wrong here**

### Cilium Version

```
➜  cilium git:(v1.12.6) ✗ cilium version
cilium-cli: v0.12.13 compiled with go1.20 on linux/amd64
cilium image (default): v1.12.6
cilium image (stable): v1.13.0
cilium image (running): v1.12.6
```

### Kernel Version

```
➜  cilium git:(v1.12.6) ✗ uname -a 
Linux VM-34-184-centos 5.4.197-1.el7.elrepo.x86_64 #1 SMP Sat Jun 4 08:43:19 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
➜  ~ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-25T19:35:11Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
```

### Sysdump

file size too big.

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by chenyuezhou**
The ipv6_hdrlen function incorrectly sets the length of the extension header
during parsing, causing cilum to obtain the wrong next header and resulting
in packet loss.
    
This issue will affect the parsing of IPv6 packets that carry both the "auth"
and other extension headers, such as `ipv6/auth/hopbyhop/tcp`.
    
Fixes: 1ce3c7f6a4745bb6c420fb59106cfe0587ff18fa ("bpf: Skip over IPv6 extension headers")
Fixes: #24187

Signed-off-by: chenyuezhou <zcy.chenyue.zhou@gmail.com>

### CODE REVIEW

File: bpf/lib/ipv6.h [hunk 1]
```diff
@@ -60,11 +60,13 @@ static __always_inline int ipv6_hdrlen(struct __ctx_buff *ctx, __u8 *nexthdr)
...
 				return DROP_INVALID;
 
-			nh = opthdr.nexthdr;
 			if (nh == NEXTHDR_AUTH)
 				len += ipv6_authlen(&opthdr);
 			else
 				len += ipv6_optlen(&opthdr);
+
+			nh = opthdr.nexthdr;
+
```
Comment (borkmann) [inline bpf/lib/ipv6.h]: small nit: could you remove the extra added newline before the break? Otherwise lgtm, thanks! Please also add a proper commit description, e.g. you could add the PR description also as a commit description so that from git log it is easy to find. Generally, we discourage empty commit descriptions, especially when it comes to bug fixes. Thanks for the fix zcy!

Comment (chenyuezhou) [reply bpf/lib/ipv6.h]: adjusted

Comment (pchaigno) [reply bpf/lib/ipv6.h]: The commit description should also tell which packets are affected under what conditions, and if possible, it should point to the commit that introduced this bug with a `Fixes:` tags.

Comment (chenyuezhou) [reply bpf/lib/ipv6.h]: adjusted

Comment (pchaigno) [reply bpf/lib/ipv6.h]: It's still missing the `Fixes:` tag for the commit that introduced the bug. Is that commit unknown?

Comment (chenyuezhou) [reply bpf/lib/ipv6.h]: Sorry for my mistake. I added the commit that introduced this bug.

Comment (pchaigno) [reply bpf/lib/ipv6.h]: Oh, wow! That one is old. Thanks for digging this out!

**Review by borkmann — APPROVED** [review]

File: bpf/tests/pktgen.h [hunk 2]
```diff
@@ -138,6 +164,29 @@ int pktgen__free_layer(const struct pktgen *builder)
...
+		     "goto +1\n\t"
+		     "%[ret] = %[errno]\n\t"
+		     : [ret]"=r"(ret)
+		     : [ctx]"r"(ctx), [off]"r"(off),
+		       [offmax]"i"(0xff), [errno]"i"(-EINVAL)
+		     : "r1", "r2");
+
+	return ret;
+}
+
```
Comment (dylandreimerink) [inline bpf/tests/pktgen.h]: I am not 100% about this function. I believe this is masking a bigger issue we recently discovered but have not yet patched.

Long story short. Can you see if you can leave this function out. And instead update the structure of the pktgen like so:

```c
struct pktgen {
	struct __ctx_buff *ctx;
	__u16 cur_off;
	__u64 : 48;
	__u16 layer_offsets[PKT_BUILDER_LAYERS];
	enum pkt_layer layers[PKT_BUILDER_LAYERS];
};
```

The verifier works with 8-byte slots of memory, if you pack store more than 1 variable in a slot, the verifier will simply not record bounds check information. Adding the `__u64 : 48;` ensures that our variable never shares a slot with others on the stack which I think also fixes the behavior you were describing at the callsite in `pktgen__append_ipv6_extension_header`

**Review by dylandreimerink — CHANGES_REQUESTED** [review]
Very nice! Thank you for the additions to the tests and packet generator. I have one "little" thing we might want to look into

File: bpf/tests/pktgen.h (hunk 2 above)
Comment (chenyuezhou) [reply bpf/tests/pktgen.h]:
```
 struct pktgen {
        struct __ctx_buff *ctx;
        __u16 cur_off;
+       __u64 : 48;
        __u16 layer_offsets[PKT_BUILDER_LAYERS];
        enum pkt_layer layers[PKT_BUILDER_LAYERS];
 };
@@ -350,7 +351,9 @@ struct ipv6_opt_hdr *pktgen__append_ipv6_extension_header(struct pktgen *builder
         * code that verifier doesn't understand. try to open up a range on
         * the pkt reg
         */
-       if (ctx_data_valid(builder->ctx, builder->cur_off))
+       // if (ctx_data_valid(builder->ctx, builder->cur_off))
+       //      return NULL;
+       if ((void *) hdr + length > ctx_data_end(builder->ctx))
                return NULL;
 
        hdr->hdrlen = hdrlen;
```
```
                ; if (!hdr)
                217: (15) if r1 == 0x0 goto pc+854
                 R0_w=fp-44 R1=pkt(id=8,off=0,r=0,umax_value=65534,var_off=(0x0; 0xffff),s32_max_value=65535,u32_max_value=65535) R2=pkt(id=8,off=8,r=0,umax_value=65534,var_off=(0x0; 0xffff),s32_max_value=65535,u32_max_value=65535) R3_w=invP6 R4_w=inv6 R5_w=fp-50 R6=ctx(id=0,off=0,imm=0) R7=invP(id=4,umax_value=65510,var_off=(0x0; 0xffff)) R8_w=invP(id=0,umin_value=24,umax_value=65534,var_off=(0x0; 0xffff)) R10=fp0 fp-8=????0000 fp-16=0000mmmm fp-24=mmmmmmmm fp-32=mmmm0000 fp-40=mmmmmm00 fp-48=??????mm fp-56=ctx
                ; return (void *)(unsigned long)ctx->data_end;
                218: (61) r3 = *(u32 *)(r6 +4)
                ; if ((void *) hdr + length > ctx_data_end(builder->ctx))
                219: (2d) if r2 > r3 goto pc+852
                 R0=fp-44 R1=pkt(id=8,off=0,r=0,umax_value=65534,var_off=(0x0; 0xffff),s32_max_value=65535,u32_max_value=65535) R2=pkt(id=8,off=8,r=0,umax_value=65534,var_off=(0x0; 0xffff),s32_max_value=65535,u32_max_value=65535) R3=pkt_end(id=0,off=0,imm=0) R4=inv6 R5=fp-50 R6=ctx(id=0,off=0,imm=0) R7=invP(id=4,umax_value=65510,var_off=(0x0; 0xffff)) R8=invP(id=0,umin_value=24,umax_value=65534,var_off=(0x0; 0xffff)) R10=fp0 fp-8=????0000 fp-16=0000mmmm fp-24=mmmmmmmm fp-32=mmmm0000 fp-40=mmmmmm00 fp-48=??????mm fp-56=ctx
                220: (b7) r2 = 0
                ; hdr->hdrlen = hdrlen;
                221: (73) *(u8 *)(r1 +1) = r2
                invalid access to packet, off=1 size=1, R1(id=8,off=1,r=0)
                R1 offset is outside of the packet
                processed 190 insns (limit 1000000) max_states_per_insn 0 total_states 11 peak_states 11 mark_read 9
FAIL
FAIL    github.com/cilium/cilium/test/bpf_tests 2.076s
FAIL
make: *** [Makefile:92: run_bpf_tests] Error 1
make: Leaving directory '/home/ubuntu/cilium/test'
```

Sorry for the late reply.

I tried adding the patch mentioned above, but found that the range of the r1 register is still 0.

Comment (dylandreimerink) [reply bpf/tests/pktgen.h]: Alright, then we might still have separate issues, please disregard my comment

**Review by dylandreimerink — APPROVED** [review]

**Comment by pchaigno** [comment]
A rebase is needed before we can rerun the tests and merge :slightly_smiling_face:

**Comment by chenyuezhou** [comment]
rebase is done, pls test

File: bpf/tests/pktgen.h [hunk 3]
```diff
@@ -582,6 +714,43 @@ void pktgen__finish(const struct pktgen *builder)
...
+			if (i + 1 >= PKT_BUILDER_LAYERS)
+				return;
+
+			switch (builder->layers[i + 1]) {
+			case PKT_LAYER_IPV6_HOP_BY_HOP:
+				ipv6_opt_layer->nexthdr = NEXTHDR_HOP;
+				break;
+			case PKT_LAYER_IPV6_AUTH:
+				ipv6_opt_layer->nexthdr = NEXTHDR_AUTH;
+			case PKT_LAYER_TCP:
```
Comment (julianwiedmann) [inline bpf/tests/pktgen.h]: this is missing a `break`, no?

**Review by julianwiedmann — CHANGES_REQUESTED** [review]

File: bpf/tests/pktgen.h (hunk 3 above)
Comment (chenyuezhou) [reply bpf/tests/pktgen.h]: Sry, I haven't tested the case of ipv6/.../auth, so the test didn't cover this part of the code.

fixed.

**Review by julianwiedmann — CHANGES_REQUESTED** [review]
coccicheck complains about
`file ./tests/pktgen.h: variable ctx on line 181 should be declared constant`

**Comment by chenyuezhou** [comment]
fixed coccicheck and rebased

**Comment by julianwiedmann** [comment]
Please back out the recent change to `proxy.h`. It's unrelated to this PR, and will get addressed in https://github.com/cilium/cilium/pull/24606.

**Comment by chenyuezhou** [comment]
Revert the modifications to proxy.h.

**Review by julianwiedmann — APPROVED** [review]
Thanks!
