### PR TITLE
bpf: Fix maglev hash with hostServices.hostNamespaceOnly

### LINKED ISSUE #16966: bpf.lbExternalClusterIP=true doesn't work with Maglev when requested from outside cluster
## Bug report

**General Information**

- Cilium version (run `cilium version`)
1.10.3
- Kernel version (run `uname -a`)
5.10.40
- Orchestration system version in use (e.g. `kubectl version`, ...)
kubeadm
- Link to relevant artifacts (policies, deployments scripts, ...)
```
    --set k8sServiceHost="<>" \
    --set k8sServicePort=6443 \
    --set hostServices.enabled=true \
    --set hubble.listenAddress=":4244" \
    --set hubble.relay.enabled=true \
    --set hubble.ui.enabled=true \
    --set externalIPs.enabled=true \
    --set ipam.operator.clusterPoolIPv4PodCIDR="10.192.0.0/12" \
    --set ipam.operator.clusterPoolIPv4MaskSize="22" \
    --set ipam.operator.clusterPoolIPv6PodCIDR="<>" \
    --set ipam.operator.clusterPoolIPv6MaskSize="64" \
    --set ipMasqAgent.enabled=true \
    --set ipv6.enabled=true \
    --set kubeProxyReplacement=strict \
    --set kubeProxyReplacementHealthzBindAddr="[::]:10256" \
    --set maglev.tableSize=65521 \
    --set maglev.hashSeed="<>"  \
    --set nativeRoutingCIDR="10.192.0.0/12" \
    --set loadBalancer.algorithm=maglev \
    --set loadBalancer.mode=hybrid \
    --set nodePort.enabled=true \
    --set prometheus.enabled=true \
    --set tunnel=disabled \
    --set autoDirectNodeRoutes=false \
    --set externalWorkloads.enabled=true \
    --set containerRuntime.integration=containerd \
    --set cni.exclusive=false \
    --set bpf.lbExternalClusterIP=true \
    --set bpf.masquerade=true \
    --set egressGateway.enabled=true \
    --set bpf.mapDynamicSizeRatio=.0050 \
    --set prometheus.enabled=true \
    --set prometheus.port=19380
```

- Generate and upload a system zip:
```
 available on request
```

**How to reproduce the issue**

1. Enable bpf.lb.ExternalClusterIP=true
2. Attempt to access a ServiceIP hosted by kubeproxyreplacement 
3. See the following messages when attempting to connect:
xx drop (Service backend not found) flow 0xf6c2b1f8 to endpoint 0, identity 16777249->unknown: <client-ip-here>:62561 -> 10.217.142.187:80 tcp SYN

cilium bpf lb list shows a backend

10.217.142.187:80                               10.192.21.46:8080 (65)                            
                                                0.0.0.0:0 (65) [ClusterIP] 

The externalIPs service seems to be identical, and is reachable&routable:
<>.  :80                                 10.192.21.46:8080 (66)                            
                                                0.0.0.0:0 (66) [ExternalIPs]

### LINKED ISSUE #17474: Cilium drops packets destined to ClusterIP from Pods with hostServices.enabled=false and loadBalancer.algorithm=maglev
## Bug report

Cilium drops packets to ClusterIP services from Pods when Cilium is setup with kubeProxyReplacement=partial mode, hostServices.enabled=false and loadBalancer.algorithm=maglev.

Cilium tries to select a backend id using Maglev hash but there's no hash table for ClusterIP services, and then it drops the packet.
https://github.com/cilium/cilium/blob/f3887bd83f6f7495f5d487fe1002896488b9495f/bpf/bpf_lxc.c#L569 
https://github.com/cilium/cilium/blob/f3887bd83f6f7495f5d487fe1002896488b9495f/bpf/lib/lb.h#L1351

I expected that Cilium relies on kube-proxy for all internal traffic if hostServices.enabled is false but in fact, it tries to lookup service on its own.

**General Information**

- Cilium version: 1.10.4
- Kernel version: 5.11.0-34-generic
- Orchestration system version in use: kubernetes v1.21.1

**How to reproduce the issue**

1. Create a kind cluster  with `kind create cluster --config=kind-config.yaml`

kind-config.yaml
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
networking:
  disableDefaultCNI: true
```

2. Install cilium with helm

```
$ helm install cilium cilium/cilium --version 1.10.4 \
  --namespace=kube-system \
  --set kubeProxyReplacement=partial \
  --set nodePort.enabled=true \
  --set externalIPs.enabled=true \
  --set loadBalancer.algorithm=maglev \
  --set loadBalancer.dsrDispatch=ipip
```

3. core-dns can not access to kube-apiserver using a ClusterIP

```shell
$ kubectl -n kube-system logs coredns-558bd4d5db-578jp
[INFO] plugin/ready: Still waiting on: "kubernetes"
.:53
[INFO] plugin/reload: Running configuration MD5 = db32ca3650231d74073ff4cf814959a7
CoreDNS-1.8.0
linux/amd64, go1.15.3, 054c9ae
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
I0927 05:58:23.851379       1 trace.go:205] Trace[911902081]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156 (27-Sep-2021 05:57:53.850) (total time: 30000ms):
Trace[911902081]: [30.00045215s] [30.00045215s] END
I0927 05:58:23.851411       1 trace.go:205] Trace[140954425]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156 (27-Sep-2021 05:57:53.850) (total time: 30000ms):
Trace[140954425]: [30.000606722s] [30.000606722s] END
E0927 05:58:23.851442       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0": dial tcp 10.96.0.1:443: i/o timeout
E0927 05:58:23.851463       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.Namespace: failed to list *v1.Namespace: Get "https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0": dial tcp 10.96.0.1:443: i/o timeout
I0927 05:58:23.851515       1 trace.go:205] Trace[1474941318]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156 (27-Sep-2021 05:57:53.850) (total time: 30000ms):
Trace[1474941318]: [30.000567484s] [30.000567484s] END
E0927 05:58:23.851533       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: Get "https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0": dial tcp 10.96.0.1:443: i/o timeout
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"

$ kubectl -n kube-system exec cilium-wv7zb -- cilium monitor -v
xx drop (Service backend not found) flow 0xd57a15fa to endpoint 0, identity 6835->unknown: 10.0.2.58:40540 -> 10.96.0.1:443 tcp SYN
xx drop (Service backend not found) flow 0x66157d21 to endpoint 0, identity 6835->unknown: 10.0.2.58:40540 -> 10.96.0.1:443 tcp SYN
xx drop (Service backend not found) flow 0xb2eacd28 to endpoint 0, identity 52798->unknown: 10.0.2.142:60068 -> 10.96.0.1:443 tcp SYN
```

### PR DESCRIPTION
**Pull request by ysksuzuki**
This PR fixes the bug that Cilium drops packets destined to ClusterIP when configured in combination with　loadBalancer.algorithm=maglev and hostServices.hostNamespaceOnly=true. See the commit message for details.

Fixes: #17474
Fixes: #16966

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

### CODE REVIEW

File: bpf/lib/lb.h [hunk 1]
```diff
@@ -757,7 +780,8 @@ static __always_inline int lb6_local(const void *map, struct __ctx_buff *ctx,
 				     struct ipv6_ct_tuple *tuple,
 				     const struct lb6_service *svc,
 				     struct ct_state *state,
-				     const bool skip_l3_xlate)
+				     const bool skip_l3_xlate,
+				     const bool use_random_selection)
```
Comment (christarazi) [inline bpf/lib/lb.h]: While this approach presumably works, I think the main concern (for me at least) is that it will cause further strain on the complexity of the BPF progs because of changing the protoype of such a fundamental, common function and all its callers.

Ultimately, the behavior we want is to force `bpf_lxc` to use the random backend selection AFAIU. In that case, I think there are a couple of alternatives:

* Hardcode `LB_SELECTION` to random only for `bpf_lxc` at compile-time in the agent. The code for the endpoint-specific BPF prog (`bpf_lxc`) starts here: https://github.com/cilium/cilium/blob/25810847a11b659df9056a32b907e0da62fd5666/pkg/datapath/linux/config/config.go#L804. From my quick glance at the code, that seems like the right place given that `LB_SELECTION` is set inside the node variant `WriteNodeConfig()`.
* Provide a bpc_lxc-specific `lb{4,6}_xlate` function which will always use random backend selection, rather than rely on `LB_SELECTION` and is only called from the `bpf_lxc` code.

In both scenarios, we only pay the "cost" once, rather than at each packet (albeit almost negligible; optimization will likely help), and more importantly, reduce program complexity (no conditionals in BPF code) for future changes.

IMO, I think the first option seems cleaner to me, as it's simpler Go code mangling vs. C code changes which very likely will end up duplicating some code (I presume).

That's my 2 cents, but would love to hear what the others from the datapath team think (@cilium/bpf @brb).

File: test/k8sT/Services.go [hunk 2]
```diff
@@ -566,6 +566,41 @@ var _ = SkipDescribeIf(helpers.RunsOn54Kernel, "K8sServicesTest", func() {
...
+				err := kubectl.WaitforPods(helpers.DefaultNamespace, "-l zgroup=testapp", helpers.HelperTimeout)
+				Expect(err).Should(BeNil())
+			})
+
+			AfterAll(func() {
+				_ = kubectl.Delete(demoYAML)
+				ExpectAllPodsTerminated(kubectl)
+			})
+
+			It("Checks ClusterIP connectivity in combination with hostServices.hostNamespaceOnly and maglev", func() {
```
Comment (christarazi) [inline test/k8sT/Services.go]: Usually the `It` block text shouldn't overlap with the `Context` text. The context text can be describing what the test is and the `It` text can be describing what the assertion is.

So, I'd probably do something like:

```Go
Context("hostServices.hostNamespaceOnly and Maglev enabled")
...
    It("Checks ClusterIP connectivity")
```

**Review by christarazi — CHANGES_REQUESTED** [review]
Thanks for the PR!

I have a couple of comments below, one for datapath and a minor comment on the CI test. The datapath comment should be validated with the other members of the datapath team (which I've CC'd).

File: bpf/lib/lb.h (hunk 1 above)
Comment (ysksuzuki) [reply bpf/lib/lb.h]: Thank you for your feedback!

The first option makes sense to me too because it's simple, as you mentioned, while my current approach changes the common function and makes things more complex. 

How about this one? I could confirm that the e2e tests with this branch have passed in my environment.
https://github.com/ysksuzuki/cilium/commit/0d2dbc466bf82820e03f80e3a1357d8a3da4130e

With this change, LB_SELECTION, initially defined in globally scoped node_config.h will be overridden in ep_config.h, and then bpf_lxc will stick to LB_SELECTION_RANDOM.

**Review by brb — CHANGES_REQUESTED** [review]
Couldn't you just `#define LB_SELECTION LB_SELECTION_RANDOM` in bpf_lxc.c before including `lb.h`?

**Comment by ysksuzuki** [comment]
> Couldn't you just `#define LB_SELECTION LB_SELECTION_RANDOM` in bpf_lxc.c before including `lb.h`?

Yes, I could confirm that the e2e tests have passed with [this commit](https://github.com/ysksuzuki/cilium/commit/30724c25eccc4eb71a4d85b76f9fd7d96b810fea) that defines LB_SELECTION_RANDOM in bpf_lxc.c. Now I finally understand what you were saying.

**Comment by christarazi** [comment]
Thanks Martynas. I think it would be good to add the motivation / why in the commit msg and to also add a comment explaining briefly why this is necessary inside the code itself (above the `undef`).

**Review by christarazi — APPROVED** [review]

File: test/k8sT/Services.go [hunk 3]
```diff
@@ -566,6 +566,41 @@ var _ = SkipDescribeIf(helpers.RunsOn54Kernel, "K8sServicesTest", func() {
 
 			monitorRes.ExpectContains(clusterIP, "Service VIP not seen in monitor trace, indicating socket lb still in effect")
 		})
+
+		Context("hostServices.hostNamespaceOnly and Maglev enabled", func() {
```
Comment (brb) [inline test/k8sT/Services.go]: I'd suggest to avoid adding additional test case which redeploys cilium, and thus increases the test suite run time. Instead, you could reuse the `"Checks connectivity when skipping socket lb in pod ns"` test case.

**Review by brb — CHANGES_REQUESTED** [review]

File: bpf/bpf_lxc.c [hunk 4]
```diff
@@ -30,6 +30,14 @@
 #include "lib/nat46.h"
 #include "lib/identity.h"
 #include "lib/policy.h"
+
+/* Override LB_SELECTION initially defined in node_config.h to force bpf_lxc to use the random backend selection
+ * algorithm for in-cluster traffic. It will fail with the Maglev hash algorithm because Cilium doesn't provision
+ * the Maglev table for ClusterIP.
+ */
```
Comment (borkmann) [inline bpf/bpf_lxc.c:37]: Given ClusterIP can also be accessed from outside per Cilium config, can't we just include ClusterIP for the Maglev LUT? Is there a strong reason to have this special cased? (cc @brb)

Comment (ysksuzuki) [reply bpf/bpf_lxc.c:37]: I thought provisioning the Maglev lookup table for ClusterIP doesn't make sense, because it will not be accessed from outside cluster unless bpf.lbExternalClusterIP is set to true. However, it might be better to include ClusterIP [here](https://github.com/cilium/cilium/blob/master/pkg/service/service.go#L115) since it would handle both cases where bpf.lbExternalClusterIP is true and false.
What do you think?  @brb

Comment (brb) [reply bpf/bpf_lxc.c:37]: My thinking was that populating Maglev LUT for each ClusterIP SVC regardless of the lbExternalClusterIP setting would have a big memory footprint.

Comment (borkmann) [reply bpf/bpf_lxc.c:37]: But if we have lbExternalClusterIP enabled and Maglev as well, isn't that broken then? How is the service table populated/handled for external clients connecting to ClusterIP there?

Comment (ysksuzuki) [reply bpf/bpf_lxc.c:37]: In our cluster,  we have 63 LB services and 242 ClusterIP services. So the number of tables will increase 5-fold if we provision  the Maglev LUT for ClusterIP as well. It might be a waste to do so unconditionally. Do we include ClusterIP for Maglev LUT only if lbExternalClusterIP is set true, while adding `#define LB_SELECTION LB_SELECTION_RANDOM` to bpf_lxc ?

Comment (borkmann) [reply bpf/bpf_lxc.c:37]: That sounds reasonable way forward to me, wdyt @brb?

Comment (brb) [reply bpf/bpf_lxc.c:37]: Sounds good to me!

Comment (ysksuzuki) [reply bpf/bpf_lxc.c:37]: Thank you all! I will modify this patch accordingly.

**Comment by ysksuzuki** [comment]
I needed https://github.com/cilium/cilium/pull/18493 to pass the e2e in my environment. Will rebase the branch after it's merged.

**Comment by ysksuzuki** [comment]
This test is failing in my environment even with the master branch.

```
Summarizing 1 Failure:

[Fail] K8sPolicyTest Multi-node policy test validates fromEntities policies [It] Validates fromEntities all policy
/home/cybozu/go/src/github.com/cilium/cilium/test/k8sT/Policies.go:1686

Ran 89 of 411 Specs in 7176.412 seconds
FAIL! -- 88 Passed | 1 Failed | 0 Pending | 322 Skipped
--- FAIL: TestTest (7176.53s)
FAIL
```

File: bpf/bpf_lxc.c [hunk 5]
```diff
@@ -30,6 +30,14 @@
 #include "lib/nat46.h"
 #include "lib/identity.h"
 #include "lib/policy.h"
+
+/* Override LB_SELECTION initially defined in node_config.h to force bpf_lxc to use the random backend selection
+ * algorithm for in-cluster traffic. It will fail with the Maglev hash algorithm because Cilium doesn't provision
```
Comment (brb) [inline bpf/bpf_lxc.c]: Nit: "It will fail" => "Otherwise, it will fail".

File: pkg/service/service.go [hunk 6]
```diff
@@ -116,7 +116,8 @@ func (svc *svcInfo) useMaglev() bool {
 	return option.Config.NodePortAlg == option.NodePortAlgMaglev &&
 		((svc.svcType == lb.SVCTypeNodePort && !isWildcardAddr(svc.frontend)) ||
 			svc.svcType == lb.SVCTypeExternalIPs ||
-			svc.svcType == lb.SVCTypeLoadBalancer)
+			svc.svcType == lb.SVCTypeLoadBalancer ||
+			(option.Config.ExternalClusterIP && svc.svcType == lb.SVCTypeClusterIP))
```
Comment (brb) [inline pkg/service/service.go:123]: Could you add a comment to explain why to provision when ClusterIP && ExternalClusterIP?

File: test/k8sT/Services.go [hunk 7]
```diff
@@ -459,6 +459,7 @@ var _ = SkipDescribeIf(helpers.RunsOn54Kernel, "K8sServicesTest", func() {
 			BeforeAll(func() {
 				DeployCiliumOptionsAndDNS(kubectl, ciliumFilename, map[string]string{
 					"bpf.lbExternalClusterIP": "true",
+					"loadBalancer.algorithm":  "maglev",
```
Comment (brb) [inline test/k8sT/Services.go]: This needs a comment why we enable Maglev in this test case.

File: test/k8sT/Services.go [hunk 8]
```diff
@@ -492,6 +493,7 @@ var _ = SkipDescribeIf(helpers.RunsOn54Kernel, "K8sServicesTest", func() {
 		BeforeAll(func() {
 			DeployCiliumOptionsAndDNS(kubectl, ciliumFilename, map[string]string{
 				"hostServices.hostNamespaceOnly": "true",
+				"loadBalancer.algorithm":         "maglev",
```
Comment (brb) [inline test/k8sT/Services.go]: Ditto.

**Review by brb — CHANGES_REQUESTED** [review]
Getting closer to merging :rocket:

**Review by brb — APPROVED** [review]
Thanks!
