### PR TITLE
cli: Fix unreliable tests due to error emitted in Cilium logs "retrieving device lxc*: Link not found"

### LINKED ISSUE #36493: CI: Cilium E2E Upgrade: Endpoint missed a policy revision; triggering regeneration
## CI failure

In https://github.com/cilium/cilium/pull/36014 (Cilium operator metrics changes PR), the cilium-agent emitted a warning that must be investigated:

```
  ❌ Found 2 logs in kind-kind/kube-system/cilium-82l8g (cilium-agent) matching list of errors that must be investigated:
time="2024-12-09T22:11:47.598510226Z" level=warning msg="Endpoint missed a policy revision; triggering regeneration" ciliumEndpointName=cilium-test-2/client2-66475877c6-78vwg containerID=9ed53e8264 containerInterface= datapathPolicyRevision=175 desiredPolicyRevision=174 endpointID=2968 identity=18888 ipv4=10.244.2.129 ipv6="fd00:10:244:2::23c" k8sPodName=cilium-test-2/client2-66475877c6-78vwg subsys=endpoint (1 occurrences)
time="2024-12-09T22:11:47.598531595Z" level=warning msg="Endpoint missed a policy revision; triggering regeneration" ciliumEndpointName=cilium-test-2/client-645b68dcf7-mqrtw containerID=d6ef230408 containerInterface= datapathPolicyRevision=175 desiredPolicyRevision=174 endpointID=170 identity=17126 ipv4=10.244.2.73 ipv6="fd00:10:244:2::3d32" k8sPodName=cilium-test-2/client-645b68dcf7-mqrtw subsys=endpoint (1 occurrences)
```

Failure: https://github.com/cilium/cilium/actions/runs/12244949111/job/34158005309#step:23:490
Sysdump: https://github.com/cilium/cilium/actions/runs/12244949111/artifacts/2296692023

@squeed it looks like this warning was newly introduced in https://github.com/cilium/cilium/pull/36044 and is emitting a warning log on a condition that can regularly occur. Might be good to revisit this and figure out whether there's some condition we're unexpectedly hitting or whether the log message is just too noisy.

### PR DESCRIPTION
**Pull request by fristonio**
See commit message for more details:

Fixes #36493 #39370

### CODE REVIEW

**Comment by fristonio** [comment]
/test
CI E2E upgrade failure - #42101
Ginkgo failures seems unrelated. Retriggering failed tests.

**Review by bimmlerd — APPROVED** [review]

File: pkg/endpoint/policy.go [hunk 1]
```diff
@@ -682,20 +682,14 @@ func (e *Endpoint) UpdatePolicy(idsToRegen *set.Set[identityPkg.NumericIdentity]
...
-					"Endpoint missed a policy revision; triggering regeneration",
-					logfields.PolicyRevision, fromRev,
-				)
-			} else {
-				e.getLogger().Warn(
-					"Endpoint missed a policy revision; triggering regeneration",
-					logfields.PolicyRevision, fromRev,
-				)
-			}
+			// FIXME: https://github.com/cilium/cilium/issues/36493
```
Comment (joestringer) [inline pkg/endpoint/policy.go:685]: This issue is closed. Should we reopen it or reference one that is open?

**Review by joestringer — APPROVED** [review]
We'll need a subsequent release of cilium-cli and then to bump the version of the CLI used on stable branches in order to propagate this mitigation across the whole tree.

**Review by YutaroHayakawa — APPROVED** [review]

File: pkg/endpoint/policy.go (hunk 1 above)
Comment (joestringer) [reply pkg/endpoint/policy.go:685]: Oh right, no need as the fix in this PR supersedes the original fix https://github.com/cilium/cilium/pull/41095 .

**Comment by joestringer** [comment]
Known to affect 1.17 and 1.18 branches, and the error is beningn. Marking for backport + deferring to @fristonio to do the backport just since the CLI change is not necessary.
