### PR TITLE
Fix GAMMA reconciler for multiple HTTPRoutes

### LINKED ISSUE #39830: GAMMA support cannot have more than one HTTPRoute attached to the same Service
When using Cilium's GAMMA support, it currently only supports one HTTPRoute attaching to a Service. When multiple HTTPRoutes are attached, the last one reconciled will be the one that takes effect (this practically means that it's usually the last one _created_, but that may not always be the case).

This is because when I built the GAMMA reconciler(under #22512, in #32744) , I had it watch only HTTPRoute objects, and build the resulting CilumEnvoyConfig based on that single HTTPRoute, rather than watching Service objects and building the config on a per-Service basis.

This issue covers work to resolve this and make GAMMA reconciliation work properly, as in north/south Gateway API reconciliation.

This issue affects all releases of Cilium with GAMMA support (since Cilium v1.16).

I'm working on a fix already, but it involves rewriting the whole GAMMA reconciler, so I'm making I get it right this time.

### PR DESCRIPTION
**Pull request by youngnick**
This commit refactors and reimplements the GAMMA reconciler to
mainly act from Services rather than HTTPRoutes, which allows
multiple HTTPRoutes to attach to a single Service correctly.

It also refactors this pattern to use an index on HTTPRoutes
so that the Service reconcilation only acts on HTTPRoutes
that have that specific Service as a parent. This should
help this reconciler avoid some scaling problems.

This approach also updates HTTPRoute status using the Service
reconciler, rather than a separate HTTPRoute reconciler as in
the current Gateway implementation.

Fixes: #39830

```release-note
GAMMA reconciler now supports attaching multiple HTTPRoutes to the same Service.
```

### CODE REVIEW

File: operator/pkg/gateway-api/cell.go [hunk 1]
```diff
@@ -277,7 +277,8 @@ func registerReconcilers(mgr ctrlRuntime.Manager, translator translation.Transla
 		newGatewayReconciler(mgr, translator, logger, installedCRDs),
 		newReferenceGrantReconciler(mgr, logger),
 		newHTTPRouteReconciler(mgr, logger),
-		newGammaHttpRouteReconciler(mgr, translator, logger),
+		newGammaReconciler(mgr, translator, logger, installedCRDs),
+		// newGammaHttpRouteReconciler(mgr, translator, logger),
```
Comment (pippolo84) [inline operator/pkg/gateway-api/cell.go]: Nit: leftover

File: operator/pkg/gateway-api/gamma_reconcile.go [hunk 2]
```diff
@@ -0,0 +1,293 @@
...
+	httpRouteList := &gatewayv1.HTTPRouteList{}
+	if err := r.Client.List(ctx, httpRouteList, &client.ListOptions{
+		FieldSelector: fields.OneTermEqualSelector(gammaParentRefsIndex, client.ObjectKeyFromObject(svc).String()),
+	}); err != nil {
+		scopedLog.ErrorContext(ctx, "Unable to list HTTPRoutes", logfields.Error, err)
+		return controllerruntime.Fail(err)
+	}
+
+	if len(httpRouteList.Items) == 0 {
+		// scopedLog.Debug("Service is not a GAMMA Service")
```
Comment (pippolo84) [inline operator/pkg/gateway-api/gamma_reconcile.go]: Nit: leftover (I think the debug log at line 80 is more useful and less noisy)

File: operator/pkg/gateway-api/gamma_reconcile.go [hunk 3]
```diff
@@ -0,0 +1,293 @@
...
+	}
+
+	if err = r.ensureEndpoints(ctx, cep); err != nil {
+		scopedLog.ErrorContext(ctx, "Unable to ensure Endpoints", logfields.Error, err)
+		return r.handleReconcileErrorWithStatus(ctx, err, originalSvc, svc)
+	}
+
+	setGammaServiceProgrammed(svc, true, "Gamma Service has been programmed", CiliumGammaReasonProgrammed)
+	if err := r.updateStatus(ctx, originalSvc, svc); err != nil {
+		return ctrl.Result{}, fmt.Errorf("failed to update Gamma Service status: %w", err)
```
Comment (pippolo84) [inline operator/pkg/gateway-api/gamma_reconcile.go]: Nit: shouldn't we use `controllerruntime.Fail` here too? I see internally it does the same, but I think there is no reason to return an empty result manually.

File: operator/pkg/gateway-api/gamma_reconcile.go [hunk 4]
```diff
@@ -0,0 +1,293 @@
...
+
+	if cmp.Equal(oldStatus, newStatus, cmpopts.IgnoreFields(metav1.Condition{}, lastTransitionTime)) {
+		return nil
+	}
+	r.logger.Debug("Updating HTTRRoute status", "httpRoute", types.NamespacedName{Name: original.Name, Namespace: original.Namespace})
+	return r.Client.Status().Update(ctx, new)
+}
+
+func (r *gammaReconciler) handleHTTPRouteReconcileErrorWithStatus(ctx context.Context, reconcileErr error, original *gatewayv1.HTTPRoute, modified *gatewayv1.HTTPRoute) error {
+	return nil
```
Comment (pippolo84) [inline operator/pkg/gateway-api/gamma_reconcile.go:268]: Is there a reason not to propagate the reconcile error here?

File: operator/pkg/gateway-api/gamma_status.go [hunk 5]
```diff
@@ -0,0 +1,88 @@
...
+	CiliumGammaConditionProgrammed = CiliumGammaPrefix + "/GammaRoutesProgrammed"
+
+	CiliumGammaReasonProgrammed = "Programmed"
+)
+
+const (
+	CiliumGammaConditionResolvedRefs = CiliumGammaPrefix + "/GammaRoutesResolvedRefs"
+
+	CiliumGammaReasonResolvedRefs = "UnresolvedReference"
+)
```
Comment (pippolo84) [inline operator/pkg/gateway-api/gamma_status.go]: Those are actually unused, can we get rid of them for now?

File: operator/pkg/gateway-api/helpers/types.go [hunk 6]
```diff
@@ -44,10 +44,30 @@ func IsGammaServiceEqual(parent gatewayv1.ParentReference, gammaService *corev1.
 	gammaServiceGroup := gammaService.GroupVersionKind().Group
 	parentNamespace := NamespaceDerefOr(parent.Namespace, objNamespace)
 
-	return parent.Kind != nil && *parent.Kind == (gatewayv1.Kind)(gammaService.Kind) &&
-		parent.Group != nil && *parent.Group == (gatewayv1.Group)(gammaServiceGroup) &&
-		parent.Name == gatewayv1.ObjectName(gammaService.Name) &&
-		parentNamespace == gammaService.Namespace
+	// Broken out from one line to make testing easier.
```
Comment (pippolo84) [inline operator/pkg/gateway-api/helpers/types.go:47]: This is something that IMHO is useful beyond testing: it improves readability and debuggability. I suggest to squash this into the previous commit.

File: operator/pkg/gateway-api/gamma_status.go [hunk 7]
```diff
@@ -1,3 +1,6 @@
+// SPDX-License-Identifier: Apache-2.0
```
Comment (pippolo84) [inline operator/pkg/gateway-api/gamma_status.go:1]: Should be squashed into the previous commit

**Review by pippolo84 — CHANGES_REQUESTED** [review]
Nice, thanks! :rocket: 

Made a first pass, need to do another one for the tests. Some nits left inline. Main feedback is about the second commit: I suggest to squash the changes to the GAMMA reconciler into the the first commit if not strictly needed for testing, and maybe separate the removal of the old HTTPRoute reconciler in a commit of its own. This should help the reviewability of the PR.

File: operator/pkg/gateway-api/cell.go (hunk 1 above)
Comment (youngnick) [reply operator/pkg/gateway-api/cell.go]: This is removed in the last commit where the rest of the old reconciler is removed.

File: operator/pkg/gateway-api/gamma_status.go (hunk 5 above)
Comment (youngnick) [reply operator/pkg/gateway-api/gamma_status.go]: Sure, but they'll definitely come back soon.

File: operator/pkg/gateway-api/gamma_reconcile.go (hunk 4 above)
Comment (youngnick) [reply operator/pkg/gateway-api/gamma_reconcile.go:268]: 🤦 Oops. Fixed, thanks.

**Comment by sayboras** [comment]
First and third commit can be merged into one.

File: operator/pkg/gateway-api/gamma.go [hunk 8]
```diff
@@ -0,0 +1,205 @@
...
+func (r *gammaReconciler) SetupWithManager(mgr ctrl.Manager) error {
+	// This creates an index on HTTPRoutes, adding an field called `gammaParents` which lists
+	// all the GAMMA parents of that HTTPRoute.
+	// This is then be used by the Service reconciler to only retrieve any HTTPRoutes that have that specific
+	// Service as a parent.
+	if err := mgr.GetFieldIndexer().IndexField(context.Background(), &gatewayv1.HTTPRoute{}, gammaParentRefsIndex, getGammaHTTPRouteParentIndexFunc(r.logger)); err != nil {
+		return err
+	}
+
+	gammaBuilder := ctrl.NewControllerManagedBy(mgr).
```
Comment (sayboras) [inline operator/pkg/gateway-api/gamma.go:59]: service is the common object, so probably add Named(gamme) to avoid any potential conflict later.

File: operator/pkg/gateway-api/gamma.go [hunk 9]
```diff
@@ -0,0 +1,205 @@
...
+// enqueueRequestForOwningHTTPRoute returns an event handler for any changes with HTTP Routes
+// belonging to the given Gateway
+func (r *gammaReconciler) enqueueRequestForOwningHTTPRoute(logger *slog.Logger) handler.EventHandler {
+	return handler.EnqueueRequestsFromMapFunc(func(ctx context.Context, a client.Object) []reconcile.Request {
+		hr, ok := a.(*gatewayv1.HTTPRoute)
+		if !ok {
+			return nil
+		}
+
+		return getGammaReconcileRequestsForRoute(context.Background(), r.Client, a, hr.Spec.CommonRouteSpec, logger)
```
Comment (sayboras) [inline operator/pkg/gateway-api/gamma.go]: context.Background() -> ctx

File: operator/pkg/gateway-api/gamma.go [hunk 10]
```diff
@@ -0,0 +1,205 @@
...
+					}.String())
+				scopedLog.Debug("Added at least one GAMMA Service to GAMMA index", validGammaServices, gammaParentRefs)
+			}
+		}
+
+		return gammaParentRefs
+	}
+}
+
+// getGAMMAReconcileRequestsForRoute returns a list of GAMMA services to be reconciled bassd on the supplied HTTPRoute.
```
Comment (sayboras) [inline operator/pkg/gateway-api/gamma.go]:
```suggestion
// getGammaReconcileRequestsForRoute returns a list of GAMMA services to be reconciled based on the supplied HTTPRoute.
```

File: operator/pkg/gateway-api/cell.go [hunk 11]
```diff
@@ -277,7 +277,7 @@ func registerReconcilers(mgr ctrlRuntime.Manager, translator translation.Transla
 		newGatewayReconciler(mgr, translator, logger, installedCRDs),
 		newReferenceGrantReconciler(mgr, logger),
 		newHTTPRouteReconciler(mgr, logger),
-		newGammaHttpRouteReconciler(mgr, translator, logger),
+		newGammaReconciler(mgr, translator, logger, installedCRDs),
```
Comment (sayboras) [inline operator/pkg/gateway-api/cell.go]: seems like installedCRDs is not used

File: operator/pkg/gateway-api/gamma.go [hunk 12]
```diff
@@ -0,0 +1,205 @@
...
+		// Watch for changes to Reference Grants
+		Watches(&gatewayv1beta1.ReferenceGrant{}, r.enqueueRequestForReferenceGrant()).
+		// Watch created and owned resources
+		Owns(&ciliumv2.CiliumEnvoyConfig{})
+
+	return gammaBuilder.Complete(r)
+}
+
+// enqueueRequestForOwningHTTPRoute returns an event handler for any changes with HTTP Routes
+// belonging to the given Gateway
```
Comment (sayboras) [inline operator/pkg/gateway-api/gamma.go]:
```suggestion
// belonging to the given Service
```

File: operator/pkg/gateway-api/gamma.go [hunk 13]
```diff
@@ -0,0 +1,205 @@
...
+}
+
+func (r *gammaReconciler) enqueueRequestForReferenceGrant() handler.EventHandler {
+	return handler.EnqueueRequestsFromMapFunc(r.enqueueAll())
+}
+
+func (r *gammaReconciler) enqueueAll() handler.MapFunc {
+	return func(ctx context.Context, o client.Object) []reconcile.Request {
+		scopedLog := r.logger.With(
+			logfields.Controller, gateway,
```
Comment (sayboras) [inline operator/pkg/gateway-api/gamma.go]:
```suggestion
			logfields.Controller, gamma,
```

File: operator/pkg/gateway-api/gamma.go [hunk 14]
```diff
@@ -0,0 +1,205 @@
...
+			logfields.Resource, client.ObjectKeyFromObject(o),
+		)
+		list := &gatewayv1.GatewayList{}
```
Comment (sayboras) [inline operator/pkg/gateway-api/gamma.go]: should we list for service instead ?

File: operator/pkg/gateway-api/gamma.go [hunk 15]
```diff
@@ -0,0 +1,205 @@
...
+		requests := make([]reconcile.Request, 0, len(list.Items))
+		for _, item := range list.Items {
+			gw := client.ObjectKey{
+				Namespace: item.GetNamespace(),
+				Name:      item.GetName(),
+			}
+			requests = append(requests, reconcile.Request{
+				NamespacedName: gw,
+			})
+			scopedLog.Info("Enqueued Gateway for resource", gateway, gw)
```
Comment (sayboras) [inline operator/pkg/gateway-api/gamma.go]: same as above, we don't need to enqueue gateway for gamma service.

**Review by sayboras — COMMENTED** [review]
The most important point is to check reference grant enqueue.

Good stuffs :+1:

File: operator/pkg/gateway-api/cell.go (hunk 11 above)
Comment (youngnick) [reply operator/pkg/gateway-api/cell.go]: I guess starting this controller is gated by the presence of Gateway API CRDs, so it's probably not required, yeah.

**Review by sayboras — APPROVED** [review]
:+1:

**Review by pippolo84 — APPROVED** [review]
:100:

**Comment by dverzolla** [comment]
any chance of having this fix on next release? @youngnick 
thanks

**Comment by sayboras** [comment]
This should be part of 1.18.x now, feel free to give it a try. Thanks.

**Comment by dverzolla** [comment]
> This should be part of 1.18.x now, feel free to give it a try. Thanks.

Found it, I am testing and so far is working well. Thanks.

**Comment by aanm** [comment]
@youngnick FYI this PR has not been backported to v1.17 even tho it has the needs-backport/1.17 label.

**Comment by youngnick** [comment]
Thanks for the poke @aanm.
