### PR TITLE
tests: add exceptions for lease errors due to etcd

### LINKED ISSUE #24701: CI: K8sDatapathServicesTest Checks E/W loadbalancing (ClusterIP, NodePort from inside cluster, etc) Checks in-cluster KPR Tests HealthCheckNodePort
### Test Name

```shell
K8sDatapathServicesTest Checks E/W loadbalancing (ClusterIP, NodePort from inside cluster, etc) Checks in-cluster KPR Tests HealthCheckNodePort
```

### Failure Output

```shell
FAIL: Found 1 io.cilium/app=operator logs matching list of errors that must be investigated:
2023-03-31T08:22:34.151990553Z level=error msg="Failed to update lock: Put \"https://192.168.56.11:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cilium-operator-resource-lock?timeout=5s\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)" subsys=klog
```

### Stack Trace

```shell
/home/jenkins/workspace/Cilium-PR-K8s-1.26-kernel-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:415
Found 1 io.cilium/app=operator logs matching list of errors that must be investigated:
2023-03-31T08:22:34.151990553Z level=error msg="Failed to update lock: Put \"https://192.168.56.11:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cilium-operator-resource-lock?timeout=5s\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)" subsys=klog
/home/jenkins/workspace/Cilium-PR-K8s-1.26-kernel-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:413
```

### Standard Output

```shell
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
⚠️  Found "2023-03-31T08:22:34.151990553Z level=error msg=\"Failed to update lock: Put \\\"https://192.168.56.11:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cilium-operator-resource-lock?timeout=5s\\\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)\" subsys=klog" in logs 1 times
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 1
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
Top 1 errors/warnings:
Failed to update lock: Put \
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
⚠️  Number of "level=warning" in logs: 9
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
Top 4 errors/warnings:
Key allocation attempt failed
Unable to get node resource
Waiting for k8s node information
UpdateIdentities: Skipping Delete of a non-existing identity
Cilium pods: [cilium-bwfh5 cilium-vbbn9]
Netpols loaded: 
CiliumNetworkPolicies loaded: default::hairpin-validation-policy 
Endpoint Policy Enforcement:
Pod                          Ingress   Egress
app1-586cfd8997-gnqwc        false     false
test-k8s2-f5fdd6457-l7xpt    false     false
testclient-8grbw             false     false
testds-s987r                 false     false
app2-775964bd4-scdfb         false     false
echo-85bb976686-58j6v        false     false
testclient-v9vz9             false     false
testds-9k5k8                 false     false
prometheus-8c7df94b4-mhftx   false     false
app1-586cfd8997-smfkn        false     false
grafana-67ff49cd99-6rxvj     false     false
app3-5db68b966f-kzlbl        false     false
echo-85bb976686-lgvk8        false     false
coredns-6d97d5ddb-5895d      false     false
Cilium agent 'cilium-bwfh5': Status: Ok  Health: Ok Nodes "" ContainerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 43 Failed 0
Cilium agent 'cilium-vbbn9': Status: Ok  Health: Ok Nodes "" ContainerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 51 Failed 0
```

### Standard Error

```shell
08:21:52 STEP: Running BeforeAll block for EntireTestsuite
08:21:52 STEP: Starting tests: command line parameters: {Reprovision:false HoldEnvironment:false PassCLIEnvironment:true SSHConfig: ShowCommands:false TestScope: SkipLogGathering:false CiliumImage:quay.io/cilium/cilium-ci CiliumTag:0196205875e149ba03628d8a6fe827cb3f1883cb CiliumOperatorImage:quay.io/cilium/operator CiliumOperatorTag:0196205875e149ba03628d8a6fe827cb3f1883cb CiliumOperatorSuffix:-ci HubbleRelayImage:quay.io/cilium/hubble-relay-ci HubbleRelayTag:0196205875e149ba03628d8a6fe827cb3f1883cb ProvisionK8s:true Timeout:2h50m0s Kubeconfig:/home/jenkins/workspace/Cilium-PR-K8s-1.26-kernel-net-next/src/github.com/cilium/cilium/test/vagrant-kubeconfig KubectlPath:/tmp/kubectl RegistryCredentials: Multinode:true RunQuarantined:false Help:false} environment variables: [JENKINS_HOME=/var/jenkins_home ghprbSourceBranch=egressgw-default-value GIT_PREVIOUS_SUCCESSFUL_COMMIT=0a454658fbd78d318c5484e37ab0194ff939975a ghprbTriggerAuthorEmail=me@jibi.io VM_MEMORY=8192 MAIL=/var/mail/root KUBEPROXY=0 SSH_CLIENT=54.148.123.155 37776 22 USER=root PROJ_PATH=src/github.com/cilium/cilium RUN_CHANGES_DISPLAY_URL=https://jenkins.cilium.io/job/Cilium-PR-K8s-1.26-kernel-net-next/1564/display/redirect?page=changes ghprbPullDescription=GitHub pull request #24646 of commit 0196205875e149ba03628d8a6fe827cb3f1883cb, no merge conflicts. NETNEXT=1 ghprbActualCommit=0196205875e149ba03628d8a6fe827cb3f1883cb SHLVL=1 CILIUM_TAG=0196205875e149ba03628d8a6fe827cb3f1883cb NODE_LABELS=baremetal ginkgo nightly node-hot-donkey vagrant HUDSON_URL=https://jenkins.cilium.io/ GIT_COMMIT=4f7f535969a4ab4d8b768c6571fe7dd549d71da5 OLDPWD=/home/jenkins/workspace/Cilium-PR-K8s-1.26-kernel-net-next GINKGO_TIMEOUT=170m HOME=/home/jenkins/workspace/Cilium-PR-K8s-1.26-kernel-net-next ghprbTriggerAuthorLoginMention=@jibi BUILD_URL=https://jenkins.cilium.io/job/Cilium-PR-K8s-1.26-kernel-net-next/1564/ ghprbPullAuthorLoginMention=@MrFreezeex HUDSON_COOKIE=b6cbda83-d63d-4fdc-9efb-66dcae5452df JENKINS_SERVER_COOKIE=durable-ddcf1e6f3d494c51ecb3f9db359292a3 ghprbGhRepository=cilium/cilium DOCKER_TAG=0196205875e149ba03628d8a6fe827cb3f1883cb JobKernelVersion=net-next DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/0/bus KERNEL=net-next CONTAINER_RUNTIME=docker WORKSPACE=/home/jenkins/workspace/Cilium-PR-K8s-1.26-kernel-net-next ghprbPullLongDescription=Please ensure your pull request adheres to the following guidelines:\r\n\r\n- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)\r\n- [ ] All code is covered by unit and/or runtime tests where feasible.\r\n- [x] All commits contain a well written commit description including a title,\r\n      description and a `Fixes: #XXX` line if the commit addresses a particular\r\n      GitHub issue.\r\n- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then\r\n      please add the commit author[s] as reviewer[s] to this issue.\r\n- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)\r\n- [ ] Provide a title or release-note blurb suitable for the release notes.\r\n- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/master/USERS.md)\r\n- [x] Thanks for contributing!\r\n\r\n<!-- Description of change -->\r\nAlways init gatewayIP to 0.0.0.0 by default instead of the previous nil value. Before this commit the rules that didn't match any node where added in addMissingEgressRules and removed right after in removeUnusedEgressRules. The egressmap auto convert nil to 0.0.0.0 and removeUnusedEgressRules doesn't do anything to match nil and 0.0.0.0.\r\n\r\n K8S_NODES=3 TESTDIR=/home/jenkins/workspace/Cilium-PR-K8s-1.26-kernel-net-next/src/github.com/cilium/cilium/test LOGNAME=root NODE_NAME=node-hot-donkey ghprbCredentialsId=ciliumbot _=/usr/bin/java HUBBLE_RELAY_IMAGE=quay.io/cilium/hubble-relay-ci STAGE_NAME=BDD-Test-PR GIT_BRANCH=origin/pr/24646/merge EXECUTOR_NUMBER=0 NO_CILIUM_ON_NODE=k8s3 ghprbTriggerAuthorLogin=jibi TERM=xterm XDG_SESSION_ID=4 HOST_FIREWALL=0 CILIUM_OPERATOR_TAG=0196205875e149ba03628d8a6fe827cb3f1883cb BUILD_DISPLAY_NAME=egressgw: init gatewayIP to 0.0.0.0  https://github.com/cilium/cilium/pull/24646  #1564 ghprbPullAuthorLogin=MrFreezeex HUDSON_HOME=/var/jenkins_home ghprbTriggerAuthor=Gilberto Bertin JOB_BASE_NAME=Cilium-PR-K8s-1.26-kernel-net-next PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin:/root/go/bin sha1=origin/pr/24646/merge KUBECONFIG=/home/jenkins/workspace/Cilium-PR-K8s-1.26-kernel-net-next/src/github.com/cilium/cilium/test/vagrant-kubeconfig FOCUS=K8s BUILD_ID=1564 XDG_RUNTIME_DIR=/run/user/0 BUILD_TAG=jenkins-Cilium-PR-K8s-1.26-kernel-net-next-1564 RUN_QUARANTINED=false CILIUM_IMAGE=quay.io/cilium/cilium-ci JENKINS_URL=https://jenkins.cilium.io/ LANG=C.UTF-8 ghprbCommentBody=/test-1.26-net-next JOB_URL=https://jenkins.cilium.io/job/Cilium-PR-K8s-1.26-kernel-net-next/ ghprbPullTitle=egressgw: init gatewayIP to 0.0.0.0 GIT_URL=https://github.com/cilium/cilium ghprbPullLink=https://github.com/cilium/cilium/pull/24646 BUILD_NUMBER=1564 JENKINS_NODE_COOKIE=a4a05e8a-ee18-44a3-a7f3-1e57e9496d09 SHELL=/bin/bash GOPATH=/home/jenkins/workspace/Cilium-PR-K8s-1.26-kernel-net-next RUN_DISPLAY_URL=https://jenkins.cilium.io/job/Cilium-PR-K8s-1.26-kernel-net-next/1564/display/redirect IMAGE_REGISTRY=quay.io/cilium ghprbAuthorRepoGitUrl=https://github.com/MrFreezeex/cilium.git FAILFAST=false HUDSON_SERVER_COOKIE=693c250bfb7e85bf ghprbTargetBranch=master JOB_DISPLAY_URL=https://jenkins.cilium.io/job/Cilium-PR-K8s-1.26-kernel-net-next/display/redirect K8S_VERSION=1.26 JOB_NAME=Cilium-PR-K8s-1.26-kernel-net-next SSH_CONNECTION=54.148.123.155 37776 147.28.149.145 22 GIT_PREVIOUS_COMMIT=0a454658fbd78d318c5484e37ab0194ff939975a ghprbPullId=24646 CILIUM_OPERATOR_IMAGE=quay.io/cilium/operator HUBBLE_RELAY_TAG=0196205875e149ba03628d8a6fe827cb3f1883cb JobK8sVersion=1.26 VM_CPUS=3 PWD=/home/jenkins/workspace/Cilium-PR-K8s-1.26-kernel-net-next/src/github.com/cilium/cilium/test CILIUM_OPERATOR_SUFFIX=-ci]
08:21:52 STEP: Ensuring the namespace kube-system exists
08:21:52 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs")
08:22:00 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs") => <nil>
08:22:00 STEP: Preparing cluster
08:22:00 STEP: Labelling nodes
08:22:00 STEP: Cleaning up Cilium components
08:22:01 STEP: Running BeforeAll block for EntireTestsuite K8sDatapathServicesTest
08:22:01 STEP: Ensuring the namespace kube-system exists
08:22:01 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs")
08:22:01 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs") => <nil>
08:22:02 STEP: Running BeforeAll block for EntireTestsuite K8sDatapathServicesTest Checks E/W loadbalancing (ClusterIP, NodePort from inside cluster, etc)
08:22:02 STEP: Installing Cilium
08:22:04 STEP: Waiting for Cilium to become ready
08:23:10 STEP: Validating if Kubernetes DNS is deployed
08:23:10 STEP: Checking if deployment is ready
08:23:10 STEP: Kubernetes DNS is not ready: only 0 of 1 replicas are available
08:23:10 STEP: Restarting Kubernetes DNS (-l k8s-app=kube-dns)
08:23:11 STEP: Waiting for Kubernetes DNS to become operational
08:23:11 STEP: Checking if deployment is ready
08:23:11 STEP: Kubernetes DNS is not ready yet: only 0 of 1 replicas are available
08:23:12 STEP: Checking if deployment is ready
08:23:12 STEP: Kubernetes DNS is not ready yet: only 0 of 1 replicas are available
08:23:13 STEP: Checking if deployment is ready
08:23:13 STEP: Kubernetes DNS is not ready yet: only 0 of 1 replicas are available
08:23:14 STEP: Checking if deployment is ready
08:23:14 STEP: Kubernetes DNS is not ready yet: only 0 of 1 replicas are available
08:23:15 STEP: Checking if deployment is ready
08:23:15 STEP: Kubernetes DNS is not ready yet: only 0 of 1 replicas are available
08:23:16 STEP: Checking if deployment is ready
08:23:16 STEP: Kubernetes DNS is not ready yet: only 0 of 1 replicas are available
08:23:17 STEP: Checking if deployment is ready
08:23:17 STEP: Kubernetes DNS is not ready yet: only 0 of 1 replicas are available
08:23:18 STEP: Checking if deployment is ready
08:23:18 STEP: Kubernetes DNS is not ready yet: only 0 of 1 replicas are available
08:23:19 STEP: Checking if deployment is ready
08:23:19 STEP: Kubernetes DNS is not ready yet: only 0 of 1 replicas are available
08:23:20 STEP: Checking if deployment is ready
08:23:20 STEP: Kubernetes DNS is not ready yet: only 0 of 1 replicas are available
08:23:21 STEP: Checking if deployment is ready
08:23:21 STEP: Kubernetes DNS is not ready yet: only 0 of 1 replicas are available
08:23:22 STEP: Checking if deployment is ready
08:23:22 STEP: Checking if kube-dns service is plumbed correctly
08:23:22 STEP: Checking if pods have identity
08:23:22 STEP: Checking if DNS can resolve
08:23:25 STEP: Validating Cilium Installation
08:23:25 STEP: Performing Cilium controllers preflight check
08:23:25 STEP: Performing Cilium status preflight check
08:23:25 STEP: Performing Cilium health check
08:23:25 STEP: Checking whether host EP regenerated
08:23:33 STEP: Performing Cilium service preflight check
08:23:33 STEP: Cilium is not ready yet: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-bwfh5': Exitcode: 1 
Err: exit status 1
Stdout:
 	 
Stderr:
 	 Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
	 Error: Cannot get status/probe: Put "http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe": dial unix /var/run/cilium/health.sock: connect: no such file or directory
	 
	 command terminated with exit code 1
	 

08:23:33 STEP: Performing Cilium controllers preflight check
08:23:33 STEP: Performing Cilium status preflight check
08:23:33 STEP: Performing Cilium health check
08:23:33 STEP: Checking whether host EP regenerated
08:23:41 STEP: Performing Cilium service preflight check
08:23:46 STEP: Cilium is not ready yet: cilium services are not set up correctly: Error validating Cilium service on pod {cilium-bwfh5 [{0xc0003ebb40 0xc000015048} {0xc0003ebd00 0xc000015060} {0xc0003ebe80 0xc000015068} {0xc001d10000 0xc000015080} {0xc001d10200 0xc000015088} {0xc001d10400 0xc0000150a0}] map[10.105.57.107:9090:[10.0.0.61:9090 (4) (1) 0.0.0.0:0 (4) (0) [ClusterIP, non-routable]] 10.108.149.247:443:[0.0.0.0:0 (5) (0) [ClusterIP, InternalLocal, non-routable] 192.168.56.12:4244 (5) (1)] 10.96.0.10:53:[0.0.0.0:0 (1) (0) [ClusterIP, non-routable] 10.0.1.177:53 (1) (1) 10.0.0.41:53 (1) (2)] 10.96.0.10:9153:[0.0.0.0:0 (2) (0) [ClusterIP, non-routable] 10.0.0.41:9153 (2) (2) 10.0.1.177:9153 (2) (1)] 10.96.0.1:443:[0.0.0.0:0 (6) (0) [ClusterIP, non-routable] 192.168.56.11:6443 (6) (1)] 10.97.119.89:3000:[0.0.0.0:0 (3) (0) [ClusterIP, non-routable] 10.0.0.194:3000 (3) (1)]]}: Could not match cilium service backend address 10.0.0.41:53 with k8s endpoint
08:23:46 STEP: Performing Cilium controllers preflight check
08:23:46 STEP: Performing Cilium health check
08:23:46 STEP: Performing Cilium status preflight check
08:23:46 STEP: Checking whether host EP regenerated
08:23:53 STEP: Performing Cilium service preflight check
08:23:53 STEP: Performing K8s service preflight check
08:23:59 STEP: Waiting for cilium-operator to be ready
08:23:59 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator")
08:23:59 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator") => <nil>
08:24:01 STEP: WaitforPods(namespace="default", filter="")
08:24:28 STEP: WaitforPods(namespace="default", filter="") => <nil>
08:24:28 STEP: Making 10 HTTP requests from k8s1 to "http://192.168.56.12:32068", expecting HTTP 200
08:24:30 STEP: Making 10 HTTP requests from k8s2 to "http://192.168.56.12:32068", expecting HTTP 200
08:24:31 STEP: Making 10 HTTP requests from k8s1 to "http://192.168.56.11:32068", expecting HTTP 503
08:24:33 STEP: Making 10 HTTP requests from k8s2 to "http://192.168.56.11:32068", expecting HTTP 503
=== Test Finished at 2023-03-31T08:24:34Z====
08:24:34 STEP: Running JustAfterEach block for EntireTestsuite K8sDatapathServicesTest
FAIL: Found 1 io.cilium/app=operator logs matching list of errors that must be investigated:
2023-03-31T08:22:34.151990553Z level=error msg="Failed to update lock: Put \"https://192.168.56.11:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cilium-operator-resource-lock?timeout=5s\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)" subsys=klog
```

### Resources

- Jenkins URL: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.26-kernel-net-next/1564/
- ZIP file(s): https://jenkins.cilium.io/job/Cilium-PR-K8s-1.26-kernel-net-next/1564/artifact/8b2019b9_K8sDatapathServicesTest_Checks_E-W_loadbalancing_(ClusterIP,_NodePort_from_inside_cluster,_etc)_Checks_in-cluster_KPR_Tests_HealthCheckNodePort.zip

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jibi**
Following up on #23334, add more exceptions for errors that seem to not be related to Cilium but rather to etcd.

Fixes: #24701

### CODE REVIEW

File: test/helpers/cons.go [hunk 1]
```diff
@@ -242,6 +242,9 @@ const (
 	retrieveResLock              = "retrieving resource lock kube-system/cilium-operator-resource-lock" // cf. https://github.com/cilium/cilium/issues/16402#issuecomment-871155492
 	failedToRelLockEmptyName     = "Failed to release lock: resource name may not be empty"             // cf. https://github.com/cilium/cilium/issues/16402#issuecomment-985819560
 	failedToUpdateLockReqTimeout = "Failed to update lock: etcdserver: request timed out"
```
Comment (tklauser) [inline test/helpers/cons.go]: I guess `failedToUpdateLockReqTimeout` can be dropped in favor of the more generic `failedToUpdateLock` added below, given we match using `strings.Contains` https://github.com/cilium/cilium/blob/89f9525dc7ce42d81fd6ef794207c0ce996f02ab/test/helpers/utils.go#L459

Comment (jibi) [reply test/helpers/cons.go]: good shout, dropped :+1:

**Review by aanm — APPROVED** [review]

**Review by tklauser — APPROVED** [review]
