### PR TITLE
Fix deadlock in identity watcher

### LINKED ISSUE #30797: Cilium failed to reconnect to one remote etcd cluster after etcd upgrade
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We upgraded all our cilium etcd clusters in our clustermesh. We observed one Cilium pod in one cluster get stuck at 4/5 clusters ready:
```
ClusterMesh:            4/5 clusters ready, 13292 global-services
   REDACT-01-use1: not-ready, 41 nodes, 3997 endpoints, 0 identities, 4187 services, 4 failures (last: 18m31s ago)
   └  quorum check failed 39 times in a row: 18m21.655367018s since last heartbeat update has been received
   └  remote configuration: expected=false, retrieved=false
   └  synchronization status: nodes=false, endpoints=false,
```
10m later:
```
ClusterMesh:            4/5 clusters ready, 13286 global-services
   REDACT-01-use1: not-ready, 41 nodes, 3997 endpoints, 0 identities, 4187 services, 4 failures (last: 28m28s ago)
   └  quorum check failed 60 times in a row: 28m9.506119043s since last heartbeat update has been received
   └  remote configuration: expected=false, retrieved=false
   └  synchronization status: nodes=false, endpoints=false, identities=false, services=false
```
Confirmed that the etcd cluster was healthy and that this was the only pod in all six clusters that exhibited this issue (~300 nodes total in the mesh) and haven't seen this on previous etcd upgrades.

We ended up deleting the pod in question to get a new cilium pod which connected to all etcd clusters without issue. 

### Cilium Version

1.14.6

### Kernel Version

Linux 5.15.148 #1 SMP Wed Feb 7 02:54:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.25.16-eks-77b1e4e

### Sysdump

_No response_

### Relevant log output

```shell
level=info msg="Remote kvstore watcher successfully synchronized and registered" clusterName=REDACT-01-use1 subsys=allocator
{"level":"warn","ts":"2024-02-15T17:02:24.622789Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0007a8a80/REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
level=warning msg="Error observed on etcd connection, reconnecting etcd" clusterName=REDACT-01-use1 config=/var/lib/cilium/clustermesh/REDACT-01-use1 error="not able to connect to any etcd endpoints" kvstoreErr="not able to connect to any etcd endpoints" kvstoreStatus="not able to connect to any etcd endpoints" subsys=clustermesh
level=info msg="Stopped restartable watch store" clusterName=REDACT-01-use1 prefix=cilium/state/ip/v1/default/ subsys=shared-store
level=info msg="Stopped restartable watch store" clusterName=REDACT-01-use1 prefix=cilium/state/nodes/v1/REDACT-01-use1/ subsys=shared-store
level=info msg="Stopped restartable watch store" clusterName=REDACT-01-use1 prefix=cilium/state/services/v1/REDACT-01-use1/ subsys=shared-store
level=info msg="Stopped remote kvstore watcher" clusterName=REDACT-01-use1 subsys=allocator
level=info msg="Stopped watch store manager" clusterName=REDACT-01-use1 subsys=shared-store
level=info msg="Creating etcd client" ConfigPath=/var/lib/cilium/clustermesh/REDACT-01-use1 KeepAliveHeartbeat=15s KeepAliveTimeout=25s ListLimit=256 MaxInflight=100 RateLimit=100 subsys=kvstore
{"level":"warn","ts":"2024-02-15T17:02:24.623134Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0007a8a80/REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}
level=warning msg="Failed to revoke lock session while closing etcd client" config=/var/lib/cilium/clustermesh/REDACT-01-use1 endpoints="[https://REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379]" error="context canceled" subsys=kvstore
level=info msg="Connecting to etcd server..." config=/var/lib/cilium/clustermesh/REDACT-01-use1 endpoints="[https://REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379]" subsys=kvstore
level=info msg="Initial etcd session established" config=/var/lib/cilium/clustermesh/REDACT-01-use1 endpoints="[https://REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379]" subsys=kvstore
level=info msg="Successfully verified version of etcd endpoint" config=/var/lib/cilium/clustermesh/REDACT-01-use1 endpoints="[https://REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379]" etcdEndpoint="https://REDACT-01-use1-etcd.mesh.prod-001.cloud.teleportinfra.sh:2379" subsys=kvstore version=3.5.11
level=info msg="Connection to remote cluster established" clusterName=REDACT-01-use1 config=/var/lib/cilium/clustermesh/REDACT-01-use1 kvstoreErr="<nil>" kvstoreStatus="Waiting for initial connection to be established" subsys=clustermesh
level=warning msg="Remote cluster doesn't have cluster configuration, falling back to the old behavior. This is expected when connecting to the old cluster running Cilium without cluster configuration feature." clusterName=REDACT-01-use1 config=/var/lib/cilium/clustermesh/REDACT-01-use1 kvstoreErr="<nil>" kvstoreStatus="Waiting for initial connection to be established" subsys=clustermesh
level=info msg="Starting watch store manager" clusterName=REDACT-01-use1 subsys=shared-store
level=info msg="Starting restartable watch store" clusterName=REDACT-01-use1 prefix=cilium/state/ip/v1/default/ subsys=shared-store
level=info msg="Starting remote kvstore watcher" clusterName=REDACT-01-use1 subsys=allocator
level=info msg="Starting restartable watch store" clusterName=REDACT-01-use1 prefix=cilium/state/nodes/v1/REDACT-01-use1/ subsys=shared-store
level=info msg="Starting restartable watch store" clusterName=REDACT-01-use1 prefix=cilium/state/services/v1/REDACT-01-use1/ subsys=shared-store
{"level":"warn","ts":"2024-02-15T17:02:35.716098Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00986c380/REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379","attempt":0,"error":"rpc error: code = Internal desc = server closed the stream without sending trailers"}
level=warning msg="Unable to list keys before starting watcher" config=/var/lib/cilium/clustermesh/REDACT-01-use1 endpoints="[https://REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379]" error="rpc error: code = Internal desc = server closed the stream without sending trailers" prefix=cilium/state/ip/v1/default/ subsys=kvstore watcher=cilium/state/ip/v1/default/
{"level":"warn","ts":"2024-02-15T17:02:35.716445Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00986c380/REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379","attempt":0,"error":"rpc error: code = Internal desc = server closed the stream without sending trailers"}
{"level":"warn","ts":"2024-02-15T17:02:35.716529Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00986c380/REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379","attempt":0,"error":"rpc error: code = Internal desc = server closed the stream without sending trailers"}
level=warning msg="Unable to list keys before starting watcher" config=/var/lib/cilium/clustermesh/REDACT-01-use1 endpoints="[https://REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379]" error="rpc error: code = Internal desc = server closed the stream without sending trailers" prefix=cilium/state/identities/v1/id subsys=kvstore watcher=cilium/state/identities/v1/id
level=warning msg="Unable to list keys before starting watcher" config=/var/lib/cilium/clustermesh/REDACT-01-use1 endpoints="[https://REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379]" error="rpc error: code = Internal desc = server closed the stream without sending trailers" prefix=cilium/state/services/v1/REDACT-01-use1/ subsys=kvstore watcher=cilium/state/services/v1/REDACT-01-use1/
{"level":"warn","ts":"2024-02-15T17:02:45.141203Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00986c380/REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
level=warning msg="Error observed on etcd connection, reconnecting etcd" clusterName=REDACT-01-use1 config=/var/lib/cilium/clustermesh/REDACT-01-use1 error="not able to connect to any etcd endpoints" kvstoreErr="not able to connect to any etcd endpoints" kvstoreStatus="not able to connect to any etcd endpoints" subsys=clustermesh
level=info msg="Stopped restartable watch store" clusterName=REDACT-01-use1 prefix=cilium/state/nodes/v1/REDACT-01-use1/ subsys=shared-store
{"level":"warn","ts":"2024-02-15T17:02:45.141448Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00986c380/REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}
{"level":"warn","ts":"2024-02-15T17:02:45.141448Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00986c380/REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}
level=warning msg="Unable to list keys before starting watcher" config=/var/lib/cilium/clustermesh/REDACT-01-use1 endpoints="[https://REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379]" error="context canceled" prefix=cilium/state/services/v1/REDACT-01-use1/ subsys=kvstore watcher=cilium/state/services/v1/REDACT-01-use1/
level=info msg="Stopped restartable watch store" clusterName=REDACT-01-use1 prefix=cilium/state/services/v1/REDACT-01-use1/ subsys=shared-store
level=warning msg="Unable to list keys before starting watcher" config=/var/lib/cilium/clustermesh/REDACT-01-use1 endpoints="[https://REDACT-01-use1-etcd.mesh.prod-001.redact.com:2379]" error="context canceled" prefix=cilium/state/ip/v1/default/ subsys=kvstore watcher=cilium/state/ip/v1/default/
level=info msg="Stopped restartable watch store" clusterName=REDACT-01-use1 prefix=cilium/state/ip/v1/default/ subsys=shared-store
```

### Anything else?

_No response_

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dboslee**
A backend disconnect will cause the receiver of the watcher events to exit. If this occurs while and the sender has enough events to fill the channel buffer deadlock can occur.

Fixes: #30797

```release-note
Fixes deadlock in identity watcher. This fixes an issue where a kvstore disconnect can cause the event receiver to exit and the event sender to get stuck forever.
```

Heres a fix for the above issue we are planning to rollout. @giorio94 I saw your comment about removing the stopChan all together. I wasn't confident making that refactor myself so here is a less intrusive change that fixes the issue for us. Feel free to use this as a jumping off point or close it if you prefer a different solution.

### CODE REVIEW

File: pkg/kvstore/events.go [hunk 1]
```diff
@@ -81,6 +84,20 @@ func newWatcher(prefix string, chanSize int) *Watcher {
 	return w
 }
 
+// emit attempts to notify the watcher of an event within the given context.
+// returning false if the context is done before the event is emitted.
+func (w *Watcher) emit(ctx context.Context, scope string, event KeyValueEvent) bool {
+	queueStart := spanstat.Start()
+	var ok bool
+	select {
+	case <-ctx.Done():
```
Comment (giorio94) [inline pkg/kvstore/events.go:93]: I'd suggest adding an extra case for `<-w.stopWatch`, so that it covers both the case in which the stop signal is given via the context, and via `watcher.Stop`, for the sake of generality.

File: pkg/kvstore/etcd.go [hunk 2]
```diff
@@ -852,15 +852,16 @@ reList:
...
+				return
+			}
 		})
 
 		// Only send the list signal once
 		if !listSignalSent {
-			w.Events <- KeyValueEvent{Typ: EventTypeListDone}
+			if ok := w.emit(ctx, scope, KeyValueEvent{Typ: EventTypeListDone}); !ok {
+				return
+			}
```
Comment (giorio94) [inline pkg/kvstore/etcd.go]: Nit. Could be shortened as follows (same for the other occurrences):

```suggestion
			if !w.emit(ctx, scope, KeyValueEvent{Typ: EventTypeListDone}) {
				return
			}
```

File: pkg/kvstore/etcd.go [hunk 3]
```diff
@@ -852,15 +852,16 @@ reList:
 			if traceEnabled {
 				scopedLog.Debugf("Emitting EventTypeDelete event for %s", k)
 			}
-
-			queueStart := spanstat.Start()
-			w.Events <- event
-			trackEventQueued(scope, EventTypeDelete, queueStart.End(true).Total())
+			if ok := w.emit(ctx, scope, event); !ok {
+				return
+			}
```
Comment (giorio94) [inline pkg/kvstore/etcd.go]: This return statement does not have any effect, as it only returns from the internal function. One possibility could be to propagate the return value to `localCache.RemoveDeleted`, or alternatively add a subsequent select statement and exit if any of the context/stopChan conditions is met before possibly emitting the `listDone` event.

**Review by giorio94 — COMMENTED** [review]
Thanks @dboslee for the PR, overall looks good to me, I've just left a couple of minor comments inline. Could you please also extend the `release-note` to clarify in which conditions the deadlock could occur?

> Heres a fix for the above issue we are planning to rollout. @giorio94 I saw your comment about removing the stopChan all together. I wasn't confident making that refactor myself so here is a less intrusive change that fixes the issue for us. Feel free to use this as a jumping off point or close it if you prefer a different solution.

I'm personally fine with merging this as an initial fix (which should be also easier/less risky to backport) and then follow-up with a more involved refactoring to simplify the overall logic and remove the usages of the `stopChan` and `watcher.Stop` in favor of the contexts.

Edit: the CI is also complaining because the commit is not signed-off: https://github.com/cilium/cilium/pull/34611#issuecomment-2318636706. Could you please fix it?

File: pkg/kvstore/etcd.go (hunk 3 above)
Comment (dboslee) [reply pkg/kvstore/etcd.go]: I chose to propagate the return value

File: pkg/kvstore/etcd.go [hunk 4]
```diff
@@ -874,6 +875,8 @@ reList:
 				return
 			case <-ctx.Done():
 				return
+			case <-w.stopWatch:
+				return
```
Comment (dboslee) [inline pkg/kvstore/etcd.go:879]: Added `stopWatch` here as well just in case.

**Comment by dboslee** [comment]
@giorio94 updated the release note with some more context but feel free to edit it as you see fit.

**Review by giorio94 — APPROVED** [review]
Thanks!

**Comment by dboslee** [comment]
@giorio94 any action required here on my end to get this merged? Looks like [Conformance E2E](https://github.com/cilium/cilium/actions/runs/10687028808) is failing here.

**Comment by giorio94** [comment]
> @giorio94 any action required here on my end to get this merged? Looks like [Conformance E2E](https://github.com/cilium/cilium/actions/runs/10687028808) is failing here.

Looks a flake. I've retriggered it.

**Comment by giorio94** [comment]
Hmm, the issue appears to reproduce pretty consistently. Could you please rebase onto main? I did a quick local test, and I manage to repro it with the CI images, and appears to be fixed after a rebase. There must be a version mismatch somewhere...

**Comment by taraspos** [comment]
@nbusseneau @giorio94 any chance this can be backported into 1.15 as well?

**Comment by giorio94** [comment]
> any chance this can be backported into 1.15 as well?

I think it may be eligible, considering that a deadlock falls into the 

> Major bugfixes relevant to the correct operation of Cilium

category from https://docs.cilium.io/en/stable/contributing/release/backports/#backport-criteria-for-x-y-1-z-and-x-y-2-z.

I've added the needs-backport/v1.15 label.

**Comment by odinuge** [comment]
Is there a plan to backport to v1.14 given the [affects/v1.14](https://github.com/cilium/cilium/labels/affects%2Fv1.14) indicates this also affect that release? It seems like a bad showstopper for v1.14 as-is.. :/

**Comment by giorio94** [comment]
> Is there a plan to backport to v1.14 given the [affects/v1.14](https://github.com/cilium/cilium/labels/affects%2Fv1.14) indicates this also affect that release? It seems like a bad showstopper for v1.14 as-is.. :/

Please notice that this looks way scarier than it actually is. This specific deadlock can only occur in very specific conditions when stopping the kvstore identity watcher, which in turn practically only happens when clustermesh is used. Given that, and the fact that v1.14 is towards the end of its support period, I had personally leaned towards not backporting it, but that's definitely open for discussion if users are affected by it.

> edit: Also trying to understand how far back this has been an issue, but not too sure where this bug was introduced, or if its always been there.

AFAIK this specific bug has always been there, with the caveat that starting from v1.14 the clustermesh logic releasing a previous etcd connection (including stopping the identity watcher) is performed synchronously rather than in a separate go routine, hence causing it to become more apparent because it would block the subsequent reconnection.

**Comment by odinuge** [comment]
Thanks for the details here @giorio94! This makes a lot of sense now.
