### PR TITLE
service: Relax protocol matching for L7 Service

### LINKED ISSUE #34075: Gateway API implementation stops working on restart of cilium ds in 1.16
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0 and lower than v1.17.0

### What happened?

With Cilium 1.16, if I am using the built in Gateway API support, if you restart the cilium daemonset, I start getting connection refused for the listening port (BGP advertised IPs, in case it matters) defined in the gw configuration. i have to re-apply my gateway configuration with a port change, then re-apply with the port changed back, to reach the service.

### How can we reproduce the issue?

Install cilium with helm

values.yaml I used:
```
k8sServiceHost: auto
cluster:
  name: default
  id: 0
bpf:
  masquerade: true  
  hostLegacyRouting: false
bgpControlPlane:
  enabled: true
  secretsNamespace:
    create: false 
    name: kube-system
hubble:
  enabled: true
  relay:
    enabled: true
    rollOutPods: true
gatewayAPI:
  enabled: true
  enableProxyProtocol: false
  enableAppProtocol: true
  enableAlpn: true
  xffNumTrustedHops: 0
  externalTrafficPolicy: Local
  gatewayClass:
    create: auto
  secretsNamespace:
    create: true
    name: cilium-secrets
    sync: true
envoy:
  enabled: true
  securityContext:
    capabilities:
      envoy:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_BIND_SERVICE
      keepCapNetBindService: true
  rollOutPods: true
ipam:
  mode: "cluster-pool"
  ciliumNodeUpdateRate: "15s"
  operator:
    clusterPoolIPv4PodCIDRList: ["172.16.0.0/16"]
    clusterPoolIPv4MaskSize: 24
LBIPAM:
  requireLBClass: false
k8s:
  requireIPv4PodCIDR: false
  requireIPv6PodCIDR: false
kubeProxyReplacement: "true"
kubeProxyReplacementHealthzBindAddr: "0.0.0.0:10256"
```

Expose a service (I used the bookinfo app):
```
ormandj@k8s-01:~/cilium$ kubectl create ns bookinfo
namespace/bookinfo created
ormandj@k8s-01:~/cilium$ kubectl -n bookinfo apply -f https://raw.githubusercontent.com/istio/istio/release-1.22/samples/bookinfo/<snip snip>
```

Apply:
```
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: test-gw
  namespace: bookinfo
spec:
  gatewayClassName: cilium
  listeners:
  - protocol: HTTP
    port: 80
    name: web-gw
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-app-1
  namespace: bookinfo
spec:
  parentRefs:
  - name: test-gw
    namespace: bookinfo
  rules:
  - matches:
    - path:
        type: Exact
        value: /productpage
    - path:
        type: PathPrefix
        value: /static
    - path:
        type: Exact
        value: /login
    - path:
        type: Exact
        value: /logout
    - path:
        type: PathPrefix
        value: /api/v1/products
    backendRefs:
    - name: productpage
      port: 9080
```
Connect to validate GW responds
Restart the Cilium DS
Attempt to access the service. It will fail. Re-apply the above gw definition with port 8000, then re-apply with it at port 80 again. Request the service and it will work.

See logs section for example.

### Cilium Version

```
ormandj@k8s-01:~$ cilium version
cilium-cli: v0.16.13 compiled with go1.22.5 on linux/amd64
cilium image (default): v1.15.6
cilium image (stable): v1.16.0
cilium image (running): 1.16.0
```

### Kernel Version

```
ormandj@k8s-01:~$ uname -a
Linux k8s-01 6.1.0-23-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64 GNU/Linux
```

### Kubernetes Version

```
ormandj@k8s-01:~$ kubectl version
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.3
```

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell
ormandj@k8s-01:~/cilium$ curl http://192.168.202.3/productpage -I
HTTP/1.1 200 OK
server: envoy
date: Tue, 30 Jul 2024 01:48:47 GMT
content-type: text/html; charset=utf-8
content-length: 5293
vary: Cookie
x-envoy-upstream-service-time: 51

ormandj@k8s-01:~/cilium$ kubectl -n kube-system rollout restart ds/cilium
daemonset.apps/cilium restarted
ormandj@k8s-01:~/cilium$ curl http://192.168.202.3/productpage -I
curl: (7) Failed to connect to 192.168.202.3 port 80 after 0 ms: Couldn't connect to server
ormandj@k8s-01:~/cilium$ vim http-gw.yaml 
ormandj@k8s-01:~/cilium$ kubectl apply -f http-gw.yaml 
gateway.gateway.networking.k8s.io/test-gw configured
httproute.gateway.networking.k8s.io/http-app-1 configured
ormandj@k8s-01:~/cilium$ curl http://192.168.202.3:8000/productpage -I
HTTP/1.1 200 OK
server: envoy
date: Tue, 30 Jul 2024 01:50:22 GMT
content-type: text/html; charset=utf-8
content-length: 5293
vary: Cookie
x-envoy-upstream-service-time: 60

ormandj@k8s-01:~/cilium$ vim http-gw.yaml 
ormandj@k8s-01:~/cilium$ kubectl apply -f http-gw.yaml 
gateway.gateway.networking.k8s.io/test-gw configured
httproute.gateway.networking.k8s.io/http-app-1 configured
ormandj@k8s-01:~/cilium$ curl http://192.168.202.3/productpage -I
HTTP/1.1 200 OK
server: envoy
date: Tue, 30 Jul 2024 01:50:40 GMT
content-type: text/html; charset=utf-8
content-length: 4294
vary: Cookie
x-envoy-upstream-service-time: 40
```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sayboras**
### Description 

Currently, the service datapath maps for both ipv4 and ipv6 didn't
use protoc field, hence despite the protocol value is passed from k8s
Service spec, the same information is not stored in datapath maps. Upon
agent restart, service restoration will just perform no-op for such
field (i.e. NONE will be used), this will cause severe failure for L7
service due to the protocol mismatch [^1].

This commit is to make sure that UDP and SCTP are not allowed instead,
the reason is to avoid extra dependencies with ongoing work [^2], which
will treat values of lb.NONE, (newly added) lb.ANY and lb.TCP in the same
way.

Fixes: https://github.com/cilium/cilium/issues/34075

[^1]: https://github.com/cilium/cilium/blob/19c74877ffc0d35daf81f4e0cde81623d4246c5c/pkg/service/service.go#L697-L702
[^2]: https://github.com/cilium/cilium/pull/33434

Reported-by: Michael Kashin <mmkashin@gmail.com>
Signed-off-by: Tam Mach <tam.mach@cilium.io>

---
### Testing

Testing was done by just restart cilium agent and verify lb map

Before the fix, there is no L7 service and proxy details.

```shell
$ ksysex ds/cilium -- cilium bpf lb list | grep 10.103.194.131
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), wait-for-node-init (init), clean-cilium-state (init), install-cni-binaries (init)
10.103.194.131:443 (0)    0.0.0.0:0 (5) (0) [LoadBalancer]                               
10.103.194.131:80 (0)     0.0.0.0:0 (4) (0) [LoadBalancer]   
```

After the fix

```shell
$ ksysex ds/cilium -- cilium bpf lb list | grep 10.103.194.131                
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), wait-for-node-init (init), clean-cilium-state (init), install-cni-binaries (init)
10.103.194.131:443 (0)    0.0.0.0:0 (5) (0) [LoadBalancer]                                                        
10.103.194.131:80 (0)     0.0.0.0:0 (4) (0) [LoadBalancer, l7-load-balancer] (L7LB Proxy Port: 14408)   

$ ksysex ds/cilium -- cilium bpf lb list | grep l7-load-balancer
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), wait-for-node-init (init), clean-cilium-state (init), install-cni-binaries (init)
10.103.194.131:80 (0)     0.0.0.0:0 (4) (0) [LoadBalancer, l7-load-balancer] (L7LB Proxy Port: 14408)             
192.168.49.2:30191 (0)    0.0.0.0:0 (6) (0) [NodePort, l7-load-balancer] (L7LB Proxy Port: 14408)                 
10.98.62.74:80 (0)        0.0.0.0:0 (1) (0) [LoadBalancer, l7-load-balancer] (L7LB Proxy Port: 17837)             
0.0.0.0:30469 (0)         0.0.0.0:0 (3) (0) [NodePort, non-routable, l7-load-balancer] (L7LB Proxy Port: 17837)   
192.168.49.2:30469 (0)    0.0.0.0:0 (2) (0) [NodePort, l7-load-balancer] (L7LB Proxy Port: 17837)                 
0.0.0.0:30191 (0)         0.0.0.0:0 (7) (0) [NodePort, non-routable, l7-load-balancer] (L7LB Proxy Port: 14408)   
```

### CODE REVIEW

File: pkg/service/service.go [hunk 1]
```diff
@@ -220,7 +220,7 @@ type L7LBInfo struct {
 // 'ports' is typically short for no point optimizing the search.
 func (i *L7LBInfo) isProtoAndPortMatch(fe *lb.L4Addr) bool {
 	// L7 LB redirect is only supported for TCP frontends
-	if fe.Protocol != lb.TCP {
+	if fe.Protocol == lb.UDP || fe.Protocol == lb.SCTP {
```
Comment (mhofstetter) [inline pkg/service/service.go:226]: Thanks Tam. What about adapting the comment accordingly - or even better add a regression test? (I wouldn't expect future developers to check the commit history of a line :smiling_face_with_tear: )

Comment (sayboras) [reply pkg/service/service.go:226]: good point 👍 

On regression test, let me check if we can include it in upgrade/downgrade workflow (e.g. ipsec)

Comment (sayboras) [reply pkg/service/service.go:226]: ah actually, we used to have Ingress related test running as part of upgrade, but it got disabled due to flakiness. 

https://github.com/cilium/cilium/blob/c681d2fba2f53a0ec9836ca6e36b83c637ff1c7f/.github/workflows/tests-e2e-upgrade.yaml#L154

I have re-open the issue https://github.com/cilium/cilium/issues/30717, and start working on it

**Review by mhofstetter — APPROVED** [review]

File: pkg/service/service.go (hunk 1 above)
Comment (mhofstetter) [reply pkg/service/service.go:226]: Thanks Tam!

**Review by julianwiedmann — APPROVED** [review]
