### PR TITLE
bgpv2: Test_MergeRoutePolicies statements can be unordered

### LINKED ISSUE #36867: CI: Test_MergeRoutePolicies/both_set_standard_and_large_communities_with_differing_local_preference is flaky
## CI failure

```
--- FAIL: Test_MergeRoutePolicies (0.00s)
--- FAIL: Test_MergeRoutePolicies/both_set_standard_and_large_communities_with_differing_local_preference (0.00s)

    policies_test.go:486: 
        	Error Trace:	/host/pkg/bgpv1/manager/reconcilerv2/policies_test.go:486
        	Error:      	Not equal: 
        	            	expected: &types.RoutePolicy{Name:"policy", Type:0, Statements:[]*types.RoutePolicyStatement{(*types.RoutePolicyStatement)(0xc000a70360), (*types.RoutePolicyStatement)(0xc000a703f0)}}
        	            	actual  : &types.RoutePolicy{Name:"policy", Type:0, Statements:[]*types.RoutePolicyStatement{(*types.RoutePolicyStatement)(0xc000a70900), (*types.RoutePolicyStatement)(0xc000a70870)}}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -4,2 +4,24 @@
        	            	  Statements: ([]*types.RoutePolicyStatement) (len=2) {
        	            	+  (*types.RoutePolicyStatement)({
        	            	+   Conditions: (types.RoutePolicyConditions) {
        	            	+    MatchNeighbors: ([]string) (len=1) {
        	            	+     (string) (len=7) "fd00::3"
        	            	+    },
        	            	+    MatchPrefixes: ([]*types.RoutePolicyPrefixMatch) <nil>,
        	            	+    MatchFamilies: ([]types.Family) (len=1) {
        	            	+     (types.Family) {
        	            	+      Afi: (types.Afi) 2,
        	            	+      Safi: (types.Safi) 0
        	            	+     }
        	            	+    }
        	            	+   },
        	            	+   Actions: (types.RoutePolicyActions) {
        	            	+    RouteAction: (types.RoutePolicyAction) 1,
        	            	+    AddCommunities: ([]string) <nil>,
        	            	+    AddLargeCommunities: ([]string) (len=1) {
        	            	+     (string) (len=14) "3333:3333:3333"
        	            	+    },
        	            	+    SetLocalPreference: (*int64)(100)
        	            	+   }
        	            	+  }),
        	            	   (*types.RoutePolicyStatement)({
        	            	@@ -33,24 +55,2 @@
        	            	    }
        	            	-  }),
        	            	-  (*types.RoutePolicyStatement)({
        	            	-   Conditions: (types.RoutePolicyConditions) {
        	            	-    MatchNeighbors: ([]string) (len=1) {
        	            	-     (string) (len=7) "fd00::3"
        	            	-    },
        	            	-    MatchPrefixes: ([]*types.RoutePolicyPrefixMatch) <nil>,
        	            	-    MatchFamilies: ([]types.Family) (len=1) {
        	            	-     (types.Family) {
        	            	-      Afi: (types.Afi) 2,
        	            	-      Safi: (types.Safi) 0
        	            	-     }
        	            	-    }
        	            	-   },
        	            	-   Actions: (types.RoutePolicyActions) {
        	            	-    RouteAction: (types.RoutePolicyAction) 1,
        	            	-    AddCommunities: ([]string) <nil>,
        	            	-    AddLargeCommunities: ([]string) (len=1) {
        	            	-     (string) (len=14) "3333:3333:3333"
        	            	-    },
        	            	-    SetLocalPreference: (*int64)(100)
        	            	-   }
        	            	   })
        	Test:       	Test_MergeRoutePolicies/both_set_standard_and_large_communities_with_differing_local_preference
```

Recent example: https://github.com/cilium/cilium/actions/runs/12652309900/job/35255153384

Looks like the flaky test was introduced in https://github.com/cilium/cilium/pull/36414 /cc @dswaffordcw

### PR DESCRIPTION
**Pull request by harsimran-pabla**
Merged policies may have statements in different order compared to what is expected in the test case. Currently, we do not need ordering of statements so test should check unordered statements.

Test run 

```
go test -c -race . &&  stress ./reconcilerv2.test -test.run=Test_MergeRoutePolicies
5s: 40 runs so far, 0 failures
10s: 90 runs so far, 0 failures
15s: 130 runs so far, 0 failures
20s: 180 runs so far, 0 failures
25s: 220 runs so far, 0 failures
30s: 270 runs so far, 0 failures
35s: 310 runs so far, 0 failures
40s: 360 runs so far, 0 failures
45s: 407 runs so far, 0 failures
50s: 450 runs so far, 0 failures
```

Fixes: #36867

### CODE REVIEW

File: pkg/bgpv1/manager/reconcilerv2/policies_test.go [hunk 1]
```diff
@@ -483,8 +483,21 @@ func Test_MergeRoutePolicies(t *testing.T) {
...
+		return
+	}
+	if policyA == nil || policyB == nil {
+		req.Fail("policies are not equal")
+		return
+	}
 
+	req.Equal(policyA.Name, policyB.Name)
+	req.Equal(policyA.Type, policyB.Type)
+	req.ElementsMatch(policyA.Statements, policyB.Statements)
```
Comment (YutaroHayakawa) [inline pkg/bgpv1/manager/reconcilerv2/policies_test.go]: I'd slightly prefer sorting statements first and compare the entire struct using `Equal` instead of implementing our own `Equal` here, so that we don't need to change this function when we add a new field.

**Review by YutaroHayakawa — CHANGES_REQUESTED** [review]

File: pkg/bgpv1/manager/reconcilerv2/policies_test.go (hunk 1 above)
Comment (harsimran-pabla) [reply pkg/bgpv1/manager/reconcilerv2/policies_test.go]: Sounds good, for now sorting them based on the condition key, which is defined [here](https://github.com/cilium/cilium/blob/main/pkg/bgpv1/types/bgp.go#L131)

**Comment by sayboras** [comment]
Came across this change while checking the failure in my PR, thanks :heavy_check_mark:

File: pkg/bgpv1/manager/reconcilerv2/policies_test.go [hunk 2]
```diff
@@ -483,8 +484,25 @@ func Test_MergeRoutePolicies(t *testing.T) {
...
+	slices.SortFunc(statements, func(i, j *types.RoutePolicyStatement) int {
+		if i.Conditions.String() < j.Conditions.String() {
+			return -1
+		} else if i.Conditions.String() > j.Conditions.String() {
+			return 1
+		} else {
+			return 0
+		}
+	})
 }
```
Comment (sayboras) [inline pkg/bgpv1/manager/reconcilerv2/policies_test.go:508]: nitpick, feel free to ignore

```suggestion
func SortRouteStatementsByName(statements []*types.RoutePolicyStatement) {
	slices.SortFunc(statements, func(i, j *types.RoutePolicyStatement) int {
		return cmp.Compare(i.Conditions.String(), j.Conditions.String())
	})
}
```

**Review by sayboras — APPROVED** [review]

**Review by YutaroHayakawa — APPROVED** [review]

File: pkg/bgpv1/manager/reconcilerv2/policies_test.go (hunk 2 above)
Comment (julianwiedmann) [reply pkg/bgpv1/manager/reconcilerv2/policies_test.go:508]: I'll go ahead and merge the PR to fix CI. Let's clean this up later? I think this suggestion is valid.

Comment (harsimran-pabla) [reply pkg/bgpv1/manager/reconcilerv2/policies_test.go:508]: Sorry just checking this PR ( timezones ). Here is the follow up 
https://github.com/cilium/cilium/pull/36888

Comment (sayboras) [reply pkg/bgpv1/manager/reconcilerv2/policies_test.go:508]: agreed, I love to merge it in asap as well, that is why _feel free to ignore_.
