### PR TITLE
hubble/container: Properly deal with nil values in RingReader

### LINKED ISSUE #131: observe does not print anything when the ring buffer is full
When the ring buffer is full, queries such as `hubble observe --since 1h` or `hubble observe --last 1000` (with a ring buffer of size < 1000) does not print out anything.

/cc @gandro who observed this behavior while trying to reproduce #114

### PR DESCRIPTION
**Pull request by gandro**
When the ring-buffer is not full, we must treat nil values the same as
reads outside of the readable indices. This commit ensures that `read`
treats nil values the same way `readFrom` does.

This has an impact on the RingReader, as we should not try to either
increase or decrease the index if the current value is unreadable.
If the current index is unreadable, then we have either read past the
last written value, or we have tried to access an index which has
already been overwritten.

This commit therefore adds an error return type to
`RingReader.{Next,Prev}` in order to determine which of the two cases
occured.

Most notably, `Next` may now return ErrInvalidData. This means this
means that the value it tried to access just got overwritten by the
writer from behind. In such cases we want to return an error, as
otherwise `RingReader.Next` would silently stop reading and
subsequentially terminate the request as if it had reached most
recent value in the ring buffer (which it has not).

The error is also added to `Previous`, however in that case
we only ever expect ErrInvalidData, as it traverses the ring buffer
in the opposite direction of the writer.

The check for concurrent writes is currently missing from `readFrom`,
which can suffer from the same problem. This will be added in a
follow-up PR.

Fixes: cilium/hubble#131

### CODE REVIEW

**Comment by gandro** [comment]
test-me-please

File: pkg/hubble/container/ring_reader_test.go [hunk 1]
```diff
@@ -146,7 +155,14 @@ func TestRingReader_Next(t *testing.T) {
 			reader := NewRingReader(ring, tt.start)
 			var got []*v1.Event
 			for i := 0; i < tt.count; i++ {
-				got = append(got, reader.Next())
+				event, err := reader.Next()
+				if (err != nil) != tt.wantErr {
+					t.Errorf("\"%s\" error = %v, wantErr %v", name, err, tt.wantErr)
```
Comment (glibsm) [inline pkg/hubble/container/ring_reader_test.go]:
```
`"%s" .... `
```

File: pkg/hubble/container/ring_reader.go [hunk 2]
```diff
@@ -41,25 +44,43 @@ func NewRingReader(ring *Ring, start uint64) *RingReader {
...
+	// When the ring is not full, ring.read() may return ok=true but e=<nil>.
+	// Can treat this the same as we would treat ok=false, as
+	// `isReadAheadOfWriter` will still allow us to decide between which of the
+	// above cases occurred.
+	e, ok := r.ring.read(r.idx)
+	if !ok || e == nil {
+		if !r.ring.isReadAheadOfWriter(r.idx) {
+			return nil, ErrConcurrentWrite
+		}
+		return nil, nil // EOF
```
Comment (glibsm) [inline pkg/hubble/container/ring_reader.go]: `nil, nil` is a tricky return to handle properly on the consumer side. can we return `io.EOF` here instead?

**Comment by gandro** [comment]
test-me-please

**Comment by glibsm** [comment]
Are we expecting that the `--since 10y` is mostly fixed by this patch, or will those types of queries more often than not surface the concurrent writer error on busy nodes?

**Comment by gandro** [comment]
> Are we expecting that the `--since 10y` is mostly fixed by this patch, or will those types of queries more often than not surface the concurrent writer error on busy nodes?

I they will suffer from the concurrent writer issue. 

I'm currently thinking that the way to implement something like `hubble observe --all` (without changing the ring buffer implementation or introducing the lock) is to iterate the ring buffer from the most recent to the oldest entry. This way we can just stop once we hit the writer cursor.

**Comment by gandro** [comment]
I should also note: The `concurrent write error` only occurs if there really is a conflict, i.e. events we were about to read got overwritten. If the reader is reading quick enough to stay ahead of the writer, it can actually loop around and dump the ring buffer content at the time the request was started plus all flows that have been added since the request was started.

Me and @Rolinh didn't consider this a bug, but this last effect can easily be avoided if we never read past the initial `LastParallelWrite` value. I would mean however that `hubble observe` will never the very most recent flows that occured after the request was started.

**Review by michi-covalent — APPROVED** [review]
now i see all the flows from ring buffer:
```
bash-5.0# hubble observe --last 10000 -o json | wc -l
4095
bash-5.0# hubble observe --since 1h -o json | wc -l
4095
```
sometimes i get more than `len(ringbuffer) - 1` flows, but i guess this can happen if new flows are coming in as we read. 

regarding @gandro 's comment, i think it's totally fine to stop at the initial `LastParallelWrite` index. you can always follow if you want to get more.

**Comment by Rolinh** [comment]
> sometimes i get more than `len(ringbuffer) - 1` flows, but i guess this can happen if new flows are coming in as we read.

This feels non intuitive at first but it's definitely not a problem as long as the reader is able to eventually catch up with the writers.

> regarding @gandro 's comment, i think it's totally fine to stop at the initial `LastParallelWrite` index. you can always follow if you want to get more.

The problem is not really to "not get enough" but that the caller will in effect miss the most recent flows. I'd be in favor of keeping the current behavior unless it's a source of bugs.

File: pkg/hubble/container/ring_reader.go [hunk 3]
```diff
@@ -41,25 +45,43 @@ func NewRingReader(ring *Ring, start uint64) *RingReader {
...
+	// values we wanted to read. In this case, we return an error, as trying
+	// to catch up would be very racy.
+	//
+	// When the ring is not full, ring.read() may return ok=true but e=<nil>.
+	// Can treat this the same as we would treat ok=false, as
+	// `isReadAheadOfWriter` will still allow us to decide between which of the
+	// above cases occurred.
+	e, ok := r.ring.read(r.idx)
+	if !ok || e == nil {
+		if !r.ring.isReadAheadOfWriter(r.idx) {
```
Comment (rolinh) [inline pkg/hubble/container/ring_reader.go]: I think that this check is itself racy. What about having `ring.read()` return this information as well?

**Review by rolinh — CHANGES_REQUESTED** [review]
Thanks for having invested time into this issue. I know the ring buffer is tricky to work with :)
I think this is definitely going to the right direction. That said, I have one concern with a suggested change. Could you have a look at it please?

**Comment by gandro** [comment]
test-me-please

File: pkg/hubble/container/ring_reader.go (hunk 3 above)
Comment (gandro) [reply pkg/hubble/container/ring_reader.go]: Very good catch! I have moved all the logic inside `read`. It has made the code much cleaner.

File: pkg/hubble/container/ring_test.go [hunk 4]
```diff
@@ -503,20 +503,17 @@ func TestRingFunctionalityInParallel(t *testing.T) {
...
 	if entry.Timestamp.Seconds != int64(0) {
 		t.Errorf("Read Event should be %+v, got %+v instead", &timestamp.Timestamp{Seconds: 0}, entry.Timestamp)
 	}
 	lastWrite--
-	entry, ok = r.read(lastWrite)
-	if !ok {
-		t.Errorf("Should be able to read position %x", lastWrite)
-	}
-	if entry != nil {
-		t.Errorf("Read Event should be %+v, got %+v instead", nil, entry)
```
Comment (gandro) [inline pkg/hubble/container/ring_test.go:519]: Reviewer note: This test relied on `read` returning `nil` values. With this PR, we never allow `nil` values to be returned from `read` (same as `readFrom`, which had this restriction already for a while)

File: pkg/hubble/container/ring.go [hunk 5]
```diff
@@ -24,6 +26,13 @@ import (
 	"github.com/cilium/cilium/pkg/lock"
 )
 
+var (
+	// ErrConcurrentWrite indicates that a value was overwritten
+	ErrConcurrentWrite = errors.New("concurrent write detected")
+	// ErrEndOfBuffer is an alias for io.EOF
+	ErrEndOfBuffer = io.EOF
```
Comment (rolinh) [inline pkg/hubble/container/ring.go]: I don't think this alias is strictly necessary as `io.EOF` is widely accepted as meaning "end of whatever".
Besides, I'm still trying to understand what the "end" of a ring structure can be :)

File: pkg/hubble/container/ring.go [hunk 6]
```diff
@@ -24,6 +26,13 @@ import (
 	"github.com/cilium/cilium/pkg/lock"
 )
 
+var (
+	// ErrConcurrentWrite indicates that a value was overwritten
+	ErrConcurrentWrite = errors.New("concurrent write detected")
```
Comment (rolinh) [inline pkg/hubble/container/ring.go]: Your commit message mentions `ErrConcurrentRead`. I think that both names are misleading anyway as reading concurrently should not be a problem and a "concurrent write" error while reading is rather something unexpected. What about a more generic name like `ErrInvalidRead` for instance?

File: pkg/hubble/container/ring.go [hunk 7]
```diff
@@ -180,11 +198,34 @@ func (r *Ring) read(read uint64) (*v1.Event, bool) {
...
+	prevWriteCycle := (writeCycle - 1) & r.cycleMask
+	maxWriteCycle := (writeCycle + r.halfCycle) & r.cycleMask
+
+	switch {
+	// Case: Reader in current cycle and accessing valid indices
+	case readCycle == writeCycle && readIdx < lastWriteIdx:
+		if event == nil {
+			// This case should never happen, as the writer must never write
+			// a nil value. In case it happens anyway, we just stop reading.
+			return nil, ErrEndOfBuffer
```
Comment (rolinh) [inline pkg/hubble/container/ring.go]: `io.EOF`

File: pkg/hubble/container/ring.go [hunk 8]
```diff
@@ -180,11 +198,34 @@ func (r *Ring) read(read uint64) (*v1.Event, bool) {
...
+	case readCycle == prevWriteCycle && readIdx > lastWriteIdx:
+		if event == nil {
+			// If the ring buffer is not yet fully populated, we treat nil
+			// as a value which is about to be overwritten
+			return nil, ErrConcurrentWrite
+		}
+		return event, nil
+	// Case: Reader ahead of writer
+	case readCycle >= writeCycle && readCycle < maxWriteCycle:
+		return nil, ErrEndOfBuffer
```
Comment (rolinh) [inline pkg/hubble/container/ring.go]: `io.EOF`

File: pkg/hubble/container/ring_reader.go [hunk 9]
```diff
@@ -39,27 +39,36 @@ func NewRingReader(ring *Ring, start uint64) *RingReader {
...
 // Next reads the event at the current position and increment the read position.
-// When no more event can be read, Next returns nil.
-func (r *RingReader) Next() *v1.Event {
-	var e *v1.Event
-	// when the ring is not full, ring.read() may return <nil>, true
-	// in such a case, one should continue reading
-	for ok := true; e == nil && ok; r.idx++ {
-		e, ok = r.ring.read(r.idx)
+// Returns ErrEndOfBuffer if there are no more newer entries. May return
+// ErrConcurrentRead if the writer overtook this RingReader.
```
Comment (rolinh) [inline pkg/hubble/container/ring_reader.go]: What about something less specific, for instance:
> The error returned is io.EOF when no more entries can be read. If reading failed, `ErrInvalidRead` is returned.

File: pkg/hubble/observer/local_observer.go [hunk 10]
```diff
@@ -450,8 +454,9 @@ func newRingReader(ring *container.Ring, req *observerpb.GetFlowsRequest, whitel
 	// In order to avoid buffering events, we have to rewind first to find the
 	// correct index, then create a new reader that starts from there
 	for i := ring.Len(); i > 0; i, idx = i-1, idx-1 {
-		e := reader.Previous()
-		if e == nil {
+		e, err := reader.Previous()
+		if err != nil {
+			idx++ // we went backward 1 too far
```
Comment (rolinh) [inline pkg/hubble/observer/local_observer.go:464]: > we went backward 1 too far

Unless the error is `io.EOF`, no?

**Review by rolinh — COMMENTED** [review]
I think we're almost there but I left a few comments. Note that the commit message is really hard to comprehend, eg:
> If the current index is unreadable, then we have reached either end of the ring buffer.

What's the "end" of a ring structure?

> `Next` may return ErrConcurrentRead

I think that the error name has changed.

File: pkg/hubble/observer/local_observer.go (hunk 10 above)
Comment (gandro) [reply pkg/hubble/observer/local_observer.go:464]: Kinda, I was not sure how to handle this properly. If `Previous` returns `io.EOF`, then something went horribly wrong. But yeah, we can check the error for `ErrConcurrentWrite` and propagate everything else.

File: pkg/hubble/container/ring.go (hunk 6 above)
Comment (gandro) [reply pkg/hubble/container/ring.go]: Oh, the `ConcurrentRead` is a typo in the commit messages. I'll think about the naming some more. I don't want it to be too generic, since the error is also presented to the user, and `invalid read` sounds like something is broken internally, when in fact they just tried to read stale data.

**Comment by gandro** [comment]
test-me-please

File: pkg/hubble/container/ring.go [hunk 11]
```diff
@@ -153,9 +166,12 @@ func (r *Ring) LastWrite() uint64 {
 	return atomic.LoadUint64(&r.write) - 1
 }
 
-// read reads the *v1.Event from the given read position. Returns false if
-// that position is no longer available to be read, returns true otherwise.
-func (r *Ring) read(read uint64) (*v1.Event, bool) {
+// read reads the *v1.Event from the given read position. Returns an error if
```
Comment (glibsm) [inline pkg/hubble/container/ring.go]: `s/read reads the/read the/`

Comment (rolinh) [reply pkg/hubble/container/ring.go]: I think it's fine as as is; `read` is the method name and by convention the comment starts by the function/method name.

Comment (glibsm) [reply pkg/hubble/container/ring.go]: I'm not changing the first word, only the phrasing.

`func Delete(userid int)` shouldn't be commented as `Delete deletes the user data`, rather as `Delete the user data`.

**Comment by gandro** [comment]
test-me-please

**Review by rolinh — APPROVED** [review]
Awesome, thanks for the great work! LGTM.
