### PR TITLE
ipam: Fix ENI IPAM on smaller instance types

### LINKED ISSUE #13217: Cilium fails to start due to unavailable addresses
## Bug report

**General Information**

General Information

Cilium version 1.8.3 f842660 2020-09-16T15:05:27-07:00 go version go1.14.9 linux/amd64
docker tag v1.8 cilium@sha256:d80f2cc60a590f013d971e3006484b006ee724309459b02cd2b0128cc634ff40
Kernel version 4.14.193-149.317.amzn2.x86_64
Orchestration system version in use kube 1.15.11 on EKS

**How to reproduce the issue**
Cilium fails to start due to unavailable addresses. The following log is for t3a.small instance.  I can fix it by going in to ciliumnodes and changing to` first-interface-index: 0`  and to `pre-allocate: 4`.
```
cilium-agent
[Sep 18, 2020 2:23:09 PM GMT+3]
level=info msg="Using autodetected VPC CIDR." subsys=ipam vpc-cidr=10.253.0.0/16
cilium-agent
[Sep 18, 2020 2:23:09 PM GMT+3]
level=info msg="Waiting for IPs to become available in CRD-backed allocation pool" available=4 helpMessage="Check if cilium-operator pod is running and does not have any warnings or error messages." name=ip-10-xxx-xxx-xxx.eu-west-1.compute.internal required=8 subsys=ipam
cilium-agent
[Sep 18, 2020 2:23:14 PM GMT+3]
level=info msg="Ignoring autodetected VPC CIDR." native-routing-cidr=10.xxx.0.0/16 subsys=ipam vpc-cidr=10.xxx.0.0/16

```
1. Install using Get started for EKS using helm, on existing self-managed nodes using t3a.micro and t3a.small instances

### PR DESCRIPTION
**Pull request by christarazi**
See commit msgs.

Fixes: https://github.com/cilium/cilium/issues/13217

```release-note
Fix bug where Cilium on smaller instance types cannot allocate IPs
```

### CODE REVIEW

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
test-me-please

File: pkg/ipam/node.go [hunk 1]
```diff
@@ -782,3 +759,79 @@ func (n *Node) syncToAPIServer() (err error) {
...
+
+// adjustPreAllocateIfNeeded adjusts IPAM values depending on the instance
+// type. This is needed when the instance type is on the smaller side which
+// requires us to lower the PreAllocate value and include eth0 as an ENI device
+// because the instance type does not allow for additional ENIs to be attached
+// (hence limited).
+//
+// For now, this function is only needed in ENI IPAM mode. In the future, this
+// may also be needed for Azure IPAM as well.
+func adjustPreAllocateIfNeeded(node *v2.CiliumNode) {
```
Comment (christarazi) [inline pkg/ipam/node.go:831]: Reviewers: This function has duplicated logic (albeit small) with function `determineFirstInterfaceIndex` (seen further below). I would be open for suggestions on how to deduplicate the logic (if it seems necessary to people). The reason I didn't do it from the first time is because I couldn't think of a good place to put it besides the `eni` package. On top of that, it doesn't seem worth putting such small logic in a large package because when it would be imported here, it would be the only function used out of a large package.

File: pkg/ipam/node.go [hunk 2]
```diff
@@ -782,3 +748,51 @@ func (n *Node) syncToAPIServer() (err error) {
...
+			return origNode, node, nil
+		}
+	} else if updateErr != nil {
+		scopedLog.WithError(updateErr).WithFields(logrus.Fields{
+			logfields.Attempt: attempts,
+		}).Warning("Failed to update CiliumNode spec")
+
+		node, err = n.manager.k8sAPI.Get(node.Name)
+		if err != nil {
+			return origNode, node, err
```
Comment (aanm) [inline pkg/ipam/node.go:802]: `return nil, nil, err`

File: pkg/ipam/node.go [hunk 3]
```diff
@@ -782,3 +748,51 @@ func (n *Node) syncToAPIServer() (err error) {
...
+		}
+
+		// Propagate the error in case we exit the loop without succeeding in
```
Comment (aanm) [inline pkg/ipam/node.go]: this comment needs to be updated.

File: pkg/ipam/node.go [hunk 4]
```diff
@@ -782,3 +748,51 @@ func (n *Node) syncToAPIServer() (err error) {
...
+		// updating the resource.
+		err = updateErr
+		node = node.DeepCopy()
+		origNode = node.DeepCopy()
```
Comment (aanm) [inline pkg/ipam/node.go:815]: Can you spend a couple cycles to understand why are we DeepCopying this? I've seen like 6 DeepCopies already and, since the node structure is coming from kube-apiserver directly, there is no need to perform these many DeepCopies.

To avoid regressions it is likely better that we do these changes as a follow up PR that won't be backported.

**Review by aanm — CHANGES_REQUESTED** [review]

File: pkg/ipam/node.go (hunk 2 above)
Comment (christarazi) [reply pkg/ipam/node.go:802]: I don't think we want to do this because this function is called in a loop to retry in case of a failure. If we return nil for `node`, then on the next run, we may try to update the CiliumNode to `nil`. I'll add a comment to clarify that the return values need to stay the same, for this reason.

File: pkg/ipam/node.go (hunk 4 above)
Comment (christarazi) [reply pkg/ipam/node.go:815]: I think the reason we have deepcopy in this specific case is because if we successfully update the CiliumNode status, then we want the reference to `origNode` and `node` to be updated for the next call to update the CiliumNode spec. I'll add a comment to clarify propagating this, similar to the error.

**Comment by christarazi** [comment]
test-me-please

File: pkg/ipam/node.go (hunk 4 above)
Comment (christarazi) [reply pkg/ipam/node.go:815]: Synced offline. Will make a followup PR to remove the deep copies and just update the pointers by dereferencing, while also removing the redundant return values.

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
retest-runtime

**Comment by christarazi** [comment]
retest-gke

**Review by aanm — APPROVED** [review]
