### PR TITLE
fix: Hubble metrics not deleted for deleted pods

### LINKED ISSUE #36195: Clean up Hubble metrics api package
There are two functions named `ProcessCiliumEndpointDeletion`.
The one under `pkg/hubble/metrics/api/api.go` is not used in product code, but only in `pkg/hubble/metrics/api/registry_test.go`

### PR DESCRIPTION
**Pull request by rectified95**
The function that deletes metrics for deleted pods isn't getting called due to a mistake in previous refactoring.
Instead, the code that posts the deletion in a queue calls itself in a loop.
 
Fixes #36195

### CODE REVIEW

File: pkg/hubble/metrics/api/api.go [hunk 1]
```diff
@@ -95,18 +94,6 @@ func InitHandler(log logrus.FieldLogger, registry *prometheus.Registry, item *Na
 	return nil
 }
 
-// ProcessCiliumEndpointDeletion queries all handlers for a list of MetricVec and removes
```
Comment (rectified95) [inline pkg/hubble/metrics/api/api.go]: This instance of `ProcessCiliumEndpointDeletion` uses `DeleteMetricsAssociatedWithPod` but is only used in test code.
I'm curious where the code is that performs metric adjustment on pod deletion for product code.
It would seem here:
https://github.com/cilium/cilium/blob/62e26d498de76c734e8380ad9c1df7caf12a9d1a/pkg/hubble/metrics/metrics.go#L70-L75
but I can't see the analogous logic.

Comment (chancez) [reply pkg/hubble/metrics/api/api.go]: You can look at 782f934641df5bafd4a9ee737e00872f65f56b64 to see how the code was originally implemented. Things have changed, removed, and renamed quite a bit since then. Previously, `hubblemetrics.ProcessPodDeletion(pod)` was called within `func (k *K8sWatcher) deleteK8sPodV1` in `pkg/k8s/watchers/pod.go` and `hubblemetrics.ProcessPodDeletion` called `ctx.DeleteMetricsAssociatedWithPod`. 

Now it seems that `ProcessCiliumEndpointDeletion` is called by `func (k *K8sCiliumEndpointsWatcher) endpointDeleted(endpoint *types.CiliumEndpoint)` from `pkg/k8s/watchers/cilium_endpoint.go` and the rest remains the same.

However, I think the current code is broken. `initEndpointDeletionHandler` ends ups falling `ProcessCiliumEndpointDeletion` which adds the endpoint to the queue, and then when the item is retrieved from the queue, it ends up calling `ProcessCiliumEndpointDeletion` again. I think when the code got refactored, it accidentally ended up broken calling itself instead of using the `ProcessCiliumEndpointDeletion` in this package. This needs to be fixed instead of removed.

Comment (rectified95) [reply pkg/hubble/metrics/api/api.go]: Makes sense, thanks! Fixed in the new update.

**Review by chancez — APPROVED** [review]
