### PR TITLE
don't require k8s connectivity in kube_proxy_healthz

### LINKED ISSUE #39778: kubeproxyHealthzHandler should repot healthy when kube-api connectivity is down
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.4 and lower than v1.18.0

### What happened?

The cilium kubeproxyHealthzHandler reports unhealthy if it can't connects kube-apiserver. 

`requireK8sConnectivity` is set to true when calling statusCollector.GetStatus [here](https://github.com/cilium/cilium/blob/main/daemon/healthz/kube_proxy_healthz.go#L130)

This is problematic for load balancers that don't support fallback when all nodes are unhealthy. That means disruption in control plane will actually bring down load balancer services

I verified with kube-proxy. It still report 200 if kube-api connectivity is lost

#32724 allows to pass a header to  disable the requirement but there are load balancers that don't support passing extra headers.

The proposal is similar to #39434, adding a flag `kube-proxy-replacement-healthz-require-k8s-connectivity` to change the default value of that

### How can we reproduce the issue?

1. turns down kube-api or block via iptables
2. `curl -I localhost:10256/healthz`

### Cilium Version

head

### Kernel Version

n/a

### Kubernetes Version

n/a

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by liuyuan10**
Don't report unhealthy in kube_proxy_healthz when cilium can't connect to k8s-apiserver. This is because:

* This follows the same behavior of kube-proxy
* kube_proxy_healthz is used by load balancers to healthcheck nodes. Do this avoids data plane disruptions on control plane outrage.

Fixes: #39778

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #39778

```release-note
The kube_proxy_healthz endpoint no longer requires Kubernetes control plane connectivity to succeed
```

### CODE REVIEW

**Comment by liuyuan10** [comment]
@joestringer please take a look. thanks

**Review by doniacld — APPROVED** [review]

**Comment by liuyuan10** [comment]
does it make sense to backport?

File: daemon/healthz/kube_proxy_healthz.go [hunk 1]
```diff
@@ -127,7 +127,8 @@ func (h kubeproxyHealthzHandler) ServeHTTP(w http.ResponseWriter, r *http.Reques
 	lastUpdateTs := currentTs
 	// We piggy back here on Cilium daemon health. If Cilium is healthy, we can
 	// reasonably assume that the node networking is ready.
-	sr := h.statusCollector.GetStatus(true, true)
+	// Don't require k8s connectivity to follow kube-proxy healthz behavior.
```
Comment (joestringer) [inline daemon/healthz/kube_proxy_healthz.go]: nit: This comment makes me more confused than if the comment doesn't exist. This handler is defining the kube-proxy healthz behavior, so the "follow" relationship seems swapped here. Am I misunderstanding?

Comment (joestringer) [reply daemon/healthz/kube_proxy_healthz.go]: The parameter already determines the behavior, this is probably simpler just without the comment.
```suggestion
```

**Comment by joestringer** [comment]
> does it make sense to backport?

This is long standing behavior, so it generally does not make sense to make logical changes to nuanced details in a point release. Cilium v1.18 is around the corner anyway so I think it would be reasonable to include the change from that point.

On that note, it makes sense to add a note to the upgrade docs to highlight that kube_proxy healthz endpoint no longer reflects kube-apiserver connectivity state.

File: daemon/healthz/kube_proxy_healthz.go (hunk 1 above)
Comment (liuyuan10) [reply daemon/healthz/kube_proxy_healthz.go]: removed

**Comment by liuyuan10** [comment]
> On that note, it makes sense to add a note to the upgrade docs to highlight that kube_proxy healthz endpoint no longer reflects kube-apiserver connectivity state.

I added it into upgrade.rst. let me know if anything else needs done

**Review by joestringer — APPROVED** [review]
Looks good, thanks!

**Review by qmonnet — APPROVED** [review]
