### PR TITLE
pkg/node: Updates GetIPv6AllocCIDRs() to Properly Return Secondary CIDRs

### LINKED ISSUE #27836: pkg/node: GetIPv6AllocCIDRs() Returns Incorrect SecondaryAllocCIDRs
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Calling `GetIPv6AllocCIDRs()` does not return `IPv6SecondaryAllocCIDRs`.

xref: https://github.com/cilium/cilium/pull/18887

### Cilium Version

main branch

### Kernel Version

n/a

### Kubernetes Version

n/a

### Sysdump

n/a

### Relevant log output

```shell
n/a
```

### Anything else?

xref code: https://github.com/cilium/cilium/blame/main/pkg/node/types/node.go#L607-L616

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by danehans**
- Updates the GetIPv6AllocCIDRs() method to check the length of IPv6SecondaryAllocCIDRs instead of IPv4SecondaryAllocCIDRs.
- Adds test cases for GetIPv4AllocCIDRs() and GetIPv6AllocCIDRs() methods.

Fixes #27836

### CODE REVIEW

File: pkg/node/types/node_test.go [hunk 1]
```diff
@@ -273,3 +275,195 @@ func TestClusterServiceValidate(t *testing.T) {
...
+			}
+
+			expectCIDRs := make([]*cidr.CIDR, 0, len(tt.secAllocCIDRs)+1)
+			for _, c := range tt.expect {
+				if c != nil {
+					expectCIDR, err := cidr.ParseCIDR(*c)
+					assert.Nil(t, err)
+					expectCIDRs = append(expectCIDRs, expectCIDR)
+				}
+			}
```
Comment (tklauser) [inline pkg/node/types/node_test.go]: Instead of converting the CIDRs from string here as part of the test, how about using `cidr.MustParseCIDR` in the test case construction above and make the `allocCIDR` and `secAllocCIDRs` members of type `*cidr.CIDR` and the `expect` member `[]*cidr.CIDR` directly?

**Review by gandro — APPROVED** [review]
Oh, nice find! Thanks!

File: pkg/node/types/node_test.go (hunk 1 above)
Comment (danehans) [reply pkg/node/types/node_test.go]: @tklauser thanks for the review. Commit 8c95ae6 implements ^ suggestion.

**Review by tklauser — APPROVED** [review]
Thanks!
