### PR TITLE
garbage collect stale distributed locks

### LINKED ISSUE #9046: KVStore lock for identity gets stuck
### Environment

- Cilium v1.5.7
- Dedicated etcd
- Recent upgrade of etcd

### Symptoms

User cannot deploy a pod with particular labels into the cluster. Kubectl describe shows "Failed create pod sandbox errors" where the CNI failed to create the endpoint due to context deadline exceeded:

```
  Warning  FailedCreatePodSandBox  86s (x25 over 38m)  kubelet, node-1  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "7af5d7baf46f19244d1449b91e1aee645388015bfa4c961bb462f267f9c21612" network for pod "my-pod": NetworkPlugin cni failed to set up pod "my-pod" network: Unable to create endpoint: Put http:///var/run/cilium/cilium.sock/v1/endpoint/cilium-local:0: context deadline exceeded
```

Cilium status reports that etcd connectivity is fine:
```
$ cilium status
KVStore:                Ok         etcd: 3/3 connected, lease-ID=57486ccec4117090, lock lease-ID=57486ccec4117092, has-quorum=true: https://10.19.72.9:2379 - 3.3.10 (Leader); https://10.19.72.10:2379 - 3.3.10; https://10.19.72.11:2379 - 3.3.10
...
```

Cilium logs report endpoint creation failure:

```
level=warning msg="Creation of endpoint failed" containerID=6daec8e36e datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2149 error="request cancelled while resolving identity" ipv4=172.16.5.186 ipv6= k8sPodName=default/my-pod subsys=daemon
```

```
level=warning msg="Key allocation attempt failed" attempt=0 error="Error while locking path cilium/state/identities/v1/locks/k8s:app=my-pod...;: etcd client timeout exceeded" key="k8s:app=my-pod..." subsys=allocator
```

The endpoint also appears as `waiting-for-identity` in `cilium endpoint list` output on the node.

### Background

In this case, etcd was recently upgraded, one instance at a time. 

Restarting Cilium did not mitigate the issue. Restart was likely initiated around 11am and did not appear to fix the issue by 11:30am. Mitigation below was used around 12:00pm. This suggests that the lease interval was already exceeded but was not automatically released.

### Mitigation

Same as here:
https://github.com/cilium/cilium/issues/7966#issuecomment-507227459

Example command execution:
```
sudo -E etcdctl get cilium --prefix | grep locks
cilium/state/identities/v1/locks/k8s:app=my-pod...;/20f46cceb84f35c2
...
```

After revoking all of the leases (final part of the lock path for entries above), Cilium agents were able to lock the path and allocate a new identity. Normal operation resumed and the pods were scheduled. No additional Cilium restart was necessary.

### Prevention

Next step is to determine:
* In which case could the lock end up getting stuck?
* Why didn't the lock lease automatically expire to allow identity allocation eventually?

Related: #6667
Related: #7966

### LINKED ISSUE #9855: Stale etcd kvstore lock deadlock
A situation was observed where no nodes where able to schedule pods due to the kvstore lock acquisition operation timing out. This subsequently caused CNI ADD to timeout.

How to reproduce:
* k8s apiserver was unavailable for 20-30 minutes
* etcd observed peer communication errors in the logs due to the DNS ClusterIP not being routable. This has likely been caused by kube-proxy giving up on providing the ClusterIP iptables rule although this has not been fully confirmed.
* The etcd cluster eventually recovered.
* For a yet unknown reason, kvstore locks have been leaked.
* Incident was noticed
* Kvstore write ability was validated using `cilium kvstore set` command
* The kvstore lock for at least one security identity could no longer be acquired from any node.
* Manual removal of the entire kvstore lock key prefix resolved the situation immediately.

### PR DESCRIPTION
**Pull request by aanm**
Under special conditions [1], cilium-agent could leak distributed locks
into the KVStore making all cilium-agents to deadlock. To avoid this
cilium-operator will garbage collect stale distributed locks. If a lock
is being held for more than 2x default value of cilium's lock lease TTL,
cilium-operator will delete that lock from the KVStore. On a first sight
this might not be reasonable but cilium-agents only use the distributed
locks to coordinated across each other which one should pick the
security identity for a new set of labels. Even if 2 cilium-agents pick
2 different security identities for the same set of labels, only the
first one will be able to publish that identity into the KVStore. The
2nd agent will fail to publish the security identity that it picked for
the set of labels:

[1]
1) connect to a etcd member (https://node-A:2379) to create a lock with
   a 25 second lease (the default for cilium)
2) drop all peer packets, not client packets, to and from that etcd
   member (https://node-A:2380).
3) try releasing that lock immediately. The unlock will fail with the
   error level=error msg="Unable to unlock kvstore lock"
   error="etcdserver: request timed out".
4) As soon the unlock fails, resume connectivity dropped in 2), this
   re-connectivity needs to happen before the lease expires, which means
   the Unlock on step 3) needs to fail in less than 25 seconds, this is
   what happen for my case.
5) since the client resumed connectivity with the server in less than 25
   seconds, the lease didn't expire which means the server still thinks
   the client is still holding the lock but the client assumes the lock was
   unlocked.

Signed-off-by: André Martins <andre@cilium.io>

Fix https://github.com/cilium/cilium/issues/9855
Fix https://github.com/cilium/cilium/issues/9046

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9982)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

File: operator/kvstore_watchdog.go [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+		}
+	}
+	return oldestLeases
+}
+
+func startKvstoreWatchdog() {
+	log.Infof("Starting kvstore identity garbage collector with %s interval...", defaults.LockLeaseTTL)
+	backend, err := kvstoreallocator.NewKVStoreBackend(cache.IdentitiesPath, "", nil)
+	if err != nil {
+		log.WithError(err).Fatal("Unable to initialize kvstore backend for identity allocation")
```
Comment (joestringer) [inline operator/kvstore_watchdog.go]:
```suggestion
		log.WithError(err).Fatal("Unable to initialize kvstore backend for identity garbage collection")
```

File: pkg/allocator/allocator.go [hunk 2]
```diff
@@ -244,6 +244,12 @@ type Backend interface {
 	// backends, and may use leases to expire keys.
 	RunGC(ctx context.Context, staleKeysPrevRound map[string]uint64) (map[string]uint64, error)
 
+	// RunLocksGC reaps stale or unused locks within the Backend. It is used by
+	// the cilium-operator and is not invoked by cilium-agent.
+	// Note: not all Backend implementations rely on this, such as the kvstore
+	// backends, and may use leases to expire keys.
+	RunLocksGC(ctx context.Context, staleKeysPrevRound map[string]kvstore.Value) (map[string]kvstore.Value, error)
```
Comment (joestringer) [inline pkg/allocator/allocator.go:253]: Please document what the first result is supposed to be. (stale/unused locks that could not be GC'd last time?)

File: pkg/kvstore/allocator/allocator_test.go [hunk 3]
```diff
@@ -111,6 +115,117 @@ func (s *AllocatorSuite) BenchmarkAllocate(c *C) {
...
+		select {
+		case <-gotLock1:
+			return true
+		default:
+			return false
+		}
+	}, 5*time.Second), IsNil)
+
+	// wait until lock2 is hold
+	time.Sleep(time.Second)
```
Comment (joestringer) [inline pkg/kvstore/allocator/allocator_test.go:182]: Why `time.Sleep()`? Why not `<-gotLock2`?

File: pkg/kvstore/allocator/allocator_test.go [hunk 4]
```diff
@@ -111,6 +115,117 @@ func (s *AllocatorSuite) BenchmarkAllocate(c *C) {
...
+			sessionID = v.SessionID
+		}
+	}
+	staleLocks[allocatorName+"/locks/"+shortKey.GetKey()] = kvstore.Value{
+		ModRevision: oldestRev,
+		LeaseID:     oldestLeaseID,
+		SessionID:   sessionID,
+	}
+
+	// GC lock1 but we still get the lock2
```
Comment (joestringer) [inline pkg/kvstore/allocator/allocator_test.go]: What does "still get the lock2" mean?

File: pkg/kvstore/allocator/allocator_test.go [hunk 5]
```diff
@@ -111,6 +115,117 @@ func (s *AllocatorSuite) BenchmarkAllocate(c *C) {
...
+
+	// Wait until lock1 is gotten.
+	c.Assert(testutils.WaitUntil(func() bool {
+		select {
+		case <-gotLock1:
+			return true
+		default:
+			return false
+		}
+	}, 5*time.Second), IsNil)
```
Comment (joestringer) [inline pkg/kvstore/allocator/allocator_test.go:177]: The `IsNil()` here looks like it's checking that the passed function is nil, rather than checking that the result is true/false.. am I missing something?

File: pkg/kvstore/allocator/allocator.go [hunk 6]
```diff
@@ -396,6 +396,48 @@ func (k *kvstoreBackend) Release(ctx context.Context, key allocator.AllocatorKey
...
+			fieldLeaseID: fmt.Sprintf("%x", v.LeaseID),
+		})
+		// Only delete if this key was previously marked as to be deleted
+		if modRev, ok := staleKeysPrevRound[key]; ok &&
+			modRev.ModRevision == v.ModRevision &&
+			modRev.LeaseID == v.LeaseID &&
+			modRev.SessionID == v.SessionID {
+			if err := kvstore.Delete(ctx, key); err != nil {
+				scopedLog.WithError(err).
+					Warning("Unable to unlocked distributed lock due client staleness." +
```
Comment (joestringer) [inline pkg/kvstore/allocator/allocator.go]:
```suggestion
					Warning("Unable to unlock distributed lock due client staleness." +
```

File: pkg/kvstore/allocator/allocator.go [hunk 7]
```diff
@@ -396,6 +396,48 @@ func (k *kvstoreBackend) Release(ctx context.Context, key allocator.AllocatorKey
...
+						" Please check the connectivity between the KVStore and the client with that lease ID.")
+			} else {
+				scopedLog.Warning("Forcefully unlocked distributed lock due client staleness." +
```
Comment (joestringer) [inline pkg/kvstore/allocator/allocator.go]:
```suggestion
				scopedLog.Warning("Forcefully unlocked distributed lock due to client staleness." +
```

File: pkg/kvstore/allocator/allocator.go [hunk 8]
```diff
@@ -396,6 +396,48 @@ func (k *kvstoreBackend) Release(ctx context.Context, key allocator.AllocatorKey
...
+		})
+		// Only delete if this key was previously marked as to be deleted
+		if modRev, ok := staleKeysPrevRound[key]; ok &&
+			modRev.ModRevision == v.ModRevision &&
+			modRev.LeaseID == v.LeaseID &&
+			modRev.SessionID == v.SessionID {
+			if err := kvstore.Delete(ctx, key); err != nil {
+				scopedLog.WithError(err).
+					Warning("Unable to unlocked distributed lock due client staleness." +
+						" Please check the connectivity between the KVStore and the client with that lease ID.")
```
Comment (joestringer) [inline pkg/kvstore/allocator/allocator.go]: How does the user determine the client for that lease ID? (Can we document this somewhere and add a cilium.link for it?)

File: pkg/kvstore/allocator/allocator_test.go [hunk 9]
```diff
@@ -111,6 +115,117 @@ func (s *AllocatorSuite) BenchmarkAllocate(c *C) {
...
+		sessionID     string
+	)
+	for _, v := range staleLocks {
+		if v.ModRevision < oldestRev {
+			oldestRev = v.ModRevision
+			oldestLeaseID = v.LeaseID
+			sessionID = v.SessionID
+		}
+	}
+	staleLocks[allocatorName+"/locks/"+shortKey.GetKey()] = kvstore.Value{
```
Comment (joestringer) [inline pkg/kvstore/allocator/allocator_test.go:204]: Is `staleLocks` intended to be re-created here? It looks like one element is either added/replaced, so presumably it should still have at least 2 elements, which are both deleted immediately afterwards. So then I'm not sure what the waiting at the end of the test is for.. just to ensure that the other goroutine stopped running?

File: pkg/kvstore/allocator/allocator_test.go [hunk 10]
```diff
@@ -111,6 +115,117 @@ func (s *AllocatorSuite) BenchmarkAllocate(c *C) {
...
+		SessionID:   sessionID,
+	}
+
+	// GC lock1 but we still get the lock2
+	staleLocks, err = allocator.RunLocksGC(staleLocks)
+	c.Assert(err, IsNil)
+	c.Assert(len(staleLocks), Equals, 0)
+
+	// Wait until lock2 is gotten as it should have happen since we have
+	// GC lock1.
```
Comment (joestringer) [inline pkg/kvstore/allocator/allocator_test.go:216]: I'm confused between this and the line 179 which also appears to be trying to wait for the lock2 to be held.

File: pkg/kvstore/allocator/allocator.go [hunk 11]
```diff
@@ -396,6 +396,48 @@ func (k *kvstoreBackend) Release(ctx context.Context, key allocator.AllocatorKey
...
+		scopedLog := log.WithFields(logrus.Fields{
+			fieldKey:     key,
+			fieldLeaseID: fmt.Sprintf("%x", v.LeaseID),
+		})
+		// Only delete if this key was previously marked as to be deleted
+		if modRev, ok := staleKeysPrevRound[key]; ok &&
+			modRev.ModRevision == v.ModRevision &&
+			modRev.LeaseID == v.LeaseID &&
+			modRev.SessionID == v.SessionID {
+			if err := kvstore.Delete(ctx, key); err != nil {
```
Comment (joestringer) [inline pkg/kvstore/allocator/allocator.go]: Does this time out after a while? Just wondering if this GC somehow got stuck, could we find out from the logs. Presumably `ctx` should bound it but `ctx` is passed as `context.TODO()` so that won't do it for us..

**Review by joestringer — CHANGES_REQUESTED** [review]
I have a scattering of mostly cosmetic log fixups and minor confusions in the test case, see my feedback below.

Two main bits of feedback:
* How can the user know and look into the connectivity failure given just a `leaseID`? What should they do? etc. 
* Can the kvstore `Delete()` block indefinitely from operator and how would we know that it is making progress, ie this new GC operation didn't somehow get stuck?

If this was in cilium-agent, I'd want it to be a controller that we can somehow probe and monitor to check that it is successfully running periodically without having to log every iteration of GC. Potentially reflect in the health probe. Not sure that's an option here though?

File: pkg/kvstore/allocator/allocator.go (hunk 11 above)
Comment (aanm) [reply pkg/kvstore/allocator/allocator.go]: That's a good point. I've set the context with a timeout the same as the lease lock.

File: pkg/kvstore/allocator/allocator.go (hunk 8 above)
Comment (aanm) [reply pkg/kvstore/allocator/allocator.go]: Unfortunately it's tricky... One needs to access each cilium status on each cilium instance to know which lease ID the cilium-agent is using. I thought about this while developing the PR and the easiest would be to add it into the cilium node structure that we have. What do you think? Also, be aware this needs to be backported to 1.5 and 1.6

File: pkg/kvstore/allocator/allocator_test.go (hunk 5 above)
Comment (aanm) [reply pkg/kvstore/allocator/allocator_test.go:177]: `testutils.WaitUntil(` returns an error

File: pkg/kvstore/allocator/allocator_test.go (hunk 3 above)
Comment (aanm) [reply pkg/kvstore/allocator/allocator_test.go:182]: bad comment, the lock2 won't be held, line 160 will block until lock1 is released. (2 clients can't hold the lock at the same time that's why line 160 blocks)

File: pkg/kvstore/allocator/allocator_test.go (hunk 9 above)
Comment (aanm) [reply pkg/kvstore/allocator/allocator_test.go:204]: When a kvstore client tries to get a lock it will create a key with its lease ID and mod revision. If we have 10 clients trying to get a lock all of them will create a key for each lease so you end up having something like `key/foo/leaseID1`, `key/foo/leaseID2`, etc, if all of them try to get a lock of `key/foo`. As soon client1 unlocks its lock, it will remove `key/foo/leaseID1` and all clients will receive an event stating the key was deleted but only the one with the oldest mod revision can get the lock. If client2 stales this lock, cilium-operator needs to GC the oldest lock of `key/foo` so that client3 can stop being deadlocked. If cilium-operator would delete all keys with the prefix `key/foo`, all clients would lose their lock which is not what we want. Let me know if this was clear.

File: pkg/kvstore/allocator/allocator_test.go (hunk 4 above)
Comment (aanm) [reply pkg/kvstore/allocator/allocator_test.go]: rephrased

File: pkg/kvstore/allocator/allocator_test.go (hunk 10 above)
Comment (aanm) [reply pkg/kvstore/allocator/allocator_test.go:216]: Please read my explanation I think it will become clear to you.

**Review by aanm — COMMENTED** [review]
Thanks for the review @joestringer

**Comment by aanm** [comment]
test-me-please

File: pkg/kvstore/allocator/allocator.go (hunk 8 above)
Comment (joestringer) [reply pkg/kvstore/allocator/allocator.go]: I'm happy with "do this annoying thing by executing commands in a bunch of pods" for a safer backport.

It'd make a big difference for those users that hit such an issue to pinpoint where and tell them explicitly, but I'm less sure how invasive such a change is so probably worth tackling separately so we can review it closely.

File: operator/kvstore_watchdog.go [hunk 12]
```diff
@@ -0,0 +1,80 @@
...
+		if !ok || v.ModRevision < oldestLease.ModRevision {
+			oldestPaths[commonPath] = v
+			oldestLeases[k] = v
+		}
+	}
+	return oldestLeases
+}
+
+func startKvstoreWatchdog() {
+	log.Infof("Starting kvstore identity garbage collector with %s interval...", defaults.LockLeaseTTL)
```
Comment (tgraf) [inline operator/kvstore_watchdog.go]: Call this watchdog instead of garbage collector

File: pkg/allocator/allocator.go [hunk 13]
```diff
@@ -244,6 +244,14 @@ type Backend interface {
 	// backends, and may use leases to expire keys.
 	RunGC(ctx context.Context, staleKeysPrevRound map[string]uint64) (map[string]uint64, error)
 
+	// RunLocksGC reaps stale or unused locks within the Backend. It is used by
+	// the cilium-operator and is not invoked by cilium-agent. Returns
+	// a map of locks currently being held in the KVStore including the ones
+	// that failed to be GCed.
+	// Note: not all Backend implementations rely on this, such as the kvstore
+	// backends, and may use leases to expire keys.
+	RunLocksGC(ctx context.Context, staleKeysPrevRound map[string]kvstore.Value) (map[string]kvstore.Value, error)
```
Comment (tgraf) [inline pkg/allocator/allocator.go:253]: Consider renaming to `RunLocksWatchdog`

File: pkg/kvstore/allocator/allocator.go [hunk 14]
```diff
@@ -396,6 +396,49 @@ func (k *kvstoreBackend) Release(ctx context.Context, key allocator.AllocatorKey
...
+			modRev.ModRevision == v.ModRevision &&
+			modRev.LeaseID == v.LeaseID &&
+			modRev.SessionID == v.SessionID {
+			if err := kvstore.Delete(ctx, key); err == nil {
+				scopedLog.Warning("Forcefully unlocked distributed lock due to client staleness." +
+					" Please check the connectivity between the KVStore and the client with that lease ID.")
+				continue
+			}
+			scopedLog.WithError(err).
+				Warning("Unable to unlock distributed lock due to client staleness." +
```
Comment (tgraf) [inline pkg/kvstore/allocator/allocator.go]: Change this to indicate that removal of the lock key was attempted instead. Reading this log, I would assume that an `Unlock()` call failed

File: operator/kvstore_watchdog.go [hunk 15]
```diff
@@ -0,0 +1,80 @@
...
+	"github.com/cilium/cilium/pkg/allocator"
+	"github.com/cilium/cilium/pkg/defaults"
+	"github.com/cilium/cilium/pkg/identity/cache"
+	"github.com/cilium/cilium/pkg/kvstore"
+	kvstoreallocator "github.com/cilium/cilium/pkg/kvstore/allocator"
+)
+
+// getPath returns the path of the given key that contains a lease prefixed to
+// its path.
+func getPath(k string) string {
```
Comment (tgraf) [inline operator/kvstore_watchdog.go]: Please use a more specific function name as this is visible in the entire operator package

File: pkg/kvstore/allocator/allocator.go [hunk 16]
```diff
@@ -396,6 +396,49 @@ func (k *kvstoreBackend) Release(ctx context.Context, key allocator.AllocatorKey
...
+
+	// iterate over /../locks
+	for key, v := range allocated {
+		scopedLog := log.WithFields(logrus.Fields{
+			fieldKey:     key,
+			fieldLeaseID: fmt.Sprintf("%x", v.LeaseID),
+		})
+		// Only delete if this key was previously marked as to be deleted
+		if modRev, ok := staleKeysPrevRound[key]; ok &&
+			modRev.ModRevision == v.ModRevision &&
```
Comment (tgraf) [inline pkg/kvstore/allocator/allocator.go:421]: Please add a comment here describing how this works. The checking of the `ModRevision` ensures that the _same_ lock instance that existed since the last run

**Review by tgraf — CHANGES_REQUESTED** [review]

File: pkg/allocator/allocator.go (hunk 13 above)
Comment (aanm) [reply pkg/allocator/allocator.go:253]: That wouldn't be entirely correct in a sense that `RunLocksGC` has similar behavior has `RunGC`

**Comment by aanm** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

File: pkg/kvstore/allocator/allocator_test.go (hunk 3 above)
Comment (joestringer) [reply pkg/kvstore/allocator/allocator_test.go:182]: >  line 160 will block until lock1 is released.

This would be useful to point out above line 160.

**Review by joestringer — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please
