### PR TITLE
cni: reduce timeout on deletion to 1.5s

### LINKED ISSUE #40931: cilium-cni should skip connecting to cilium-agent on node shutdown
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.18.0 and lower than v1.19.0

### What happened?

On node shutdown,  some workload pods may refuse to die after sigterm, then sigkill is sent to them at almost the same time as the sigterm is sent to kube-system pods. However, kube-system pods respond to sigterm effectively so they exit before workload pods if not slightly later.

In this case, when StopSandbox() is called, cilium-cni is still trying to connect cilium-agent which results in error. StopSandbox() needs to be complete before Kubelet can delete Pod objects from apiserver.  So the workload pods stay in terminating state. 

The proposed resolution is to skip the timeout  and go to the fallback codepath when detecting the system is being shutdown. The detection of OS system shutdown can be simply checking the existence of the /run/nologin file which is created when systemd-logind receives the shutdown signal.

### How can we reproduce the issue?

It happens during a race condition mentioned above, so it will be hard to reproduce. 

### Cilium Version

Any version. 

### Kernel Version

NA.

### Kubernetes Version

NA.

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sugangli**
When kubelet enables graceful shutdown, and set shutdowngraceperiod to default value(30), long deletion timeout in cilium-cni could lead to containerd cannot finish StopPodSandbox before it is killed. As a result, kubelet cannot remove the pod from kube-api server, and the pod is leaked. 

Reducing timeout to 1.5s (3 * rest API timeout 500 ms) can ensure StopPod Sandbox can be finished before kubelet and containedd are terminated. 

Fixes: #40931

### CODE REVIEW

**Comment by sugangli** [comment]
cc @fristonio @joestringer

File: plugins/cilium-cni/lib/deletion_queue.go [hunk 1]
```diff
@@ -41,7 +41,7 @@ type DeletionFallbackClient struct {
 
 // the timeout for connecting and obtaining the lock
 // the default of 30 seconds is too long; kubelet will time us out before then
-const timeoutSeconds = 10
+const timeoutMilliSeconds = 1500
```
Comment (jingyuanliang) [inline plugins/cilium-cni/lib/deletion_queue.go]: If the two lines below are the only usages, does it make sense to just add the unit here (making this variable a time.Duration)?

Comment (sugangli) [reply plugins/cilium-cni/lib/deletion_queue.go]: Make sense.

**Review by fristonio — APPROVED** [review]

**Review by youngnick — APPROVED** [review]
I spent some time reading through #40931, thanks for the repro details and the great discussion there. My initial concern here was that lowering the timeout might induce flapping or other undesirable behavior, but it seems like this is hard enough to trigger anyway that the risk is low.

**Comment by fristonio** [comment]
/test
ci-e2e-upgrade: #41520
K8s NetPol E2E tests - Failure seems unrelated. Retrying.

**Comment by joestringer** [comment]
Why are the tests failing? As a maintainer if I see contributors constantly running the tests without any clear sign of investigation, I assume the PR is introducing instability and therefore the PR is not ready to merge. Here's the documented CI triage steps: https://docs.cilium.io/en/stable/contributing/testing/ci/#id1 .

**Comment by sugangli** [comment]
@joestringer Thanks for pointing me to the doc. 

I wasn't sure if it is a flake or an actual instability caused by this PR.  After 3~4 retries, we observe two issues:
1.  https://github.com/cilium/cilium/issues/41520
As mentioned by @fristonio  above. The first three attempts failed at this test only.  I saw lots of mentioning in the issue. 
3. https://github.com/cilium/cilium/issues/40813
Only once. 

This PR is only reducing the timeout on the cni deletion path from 10s to 1.5s. Not entirely sure how it will contribute to the connectivity test failure .

**Comment by joestringer** [comment]
@sugangli I see, thanks for triaging those. I see that others are experiencing the same failures and progress is being made on resolving those failures.

There's two remaining things I noted while looking over the PR:
1. There was a [second failure in ci-e2e-upgrade](https://github.com/cilium/cilium/actions/runs/17863574255/job/50800531398) not accounted for, in which there is a timeout but many of the individual test runs failed. This happened after upgrade, meaning it could be introduced by this PR. Hard to say though.
   * General status after upgrade install [seems fine](https://github.com/cilium/cilium/actions/runs/17863574255/job/50800531398#step:23:47).
   * Most other runs on this workflow passed, so it could be either a problem specific to this job which has different configuration from other jobs, or it could be a failure with a low % failure rate and was observed primarily just because this workflow runs the same test many times over.
3. The following comment is in the PR text but not in git at all. GitHub information for older PRs is generally less accessible to developers than in git, so ideally this should be included in the git commit message:
   > Reducing timeout to 1.5s (3 * rest API timeout 500 ms) can ensure StopPod Sandbox can be finished before kubelet and containedd are terminated.

> Not entirely sure how it will contribute to the connectivity test failure .

As a general observation, this lowers a timeout involved in deleting Pods. If this somehow makes a fallback path for CNI behavior more frequent and that fallback path has some issue, I could imagine it potentially triggering instability in the testsuite. At the same time I don't have a full picture about that failure condition and its failure frequency on main.

**Comment by sugangli** [comment]
Thanks @joestringer! 

> 2. The following comment is in the PR text but not in git at all. GitHub information for older PRs is generally less accessible to developers than in git, so ideally this should be included in the git commit message:

Updated the commit message accordingly.

> As a general observation, this lowers a timeout involved in deleting Pods. If this somehow makes a fallback path for CNI behavior more frequent and that fallback path has some issue, I could imagine it potentially triggering instability in the testsuite. At the same time I don't have a full picture about that failure condition and its failure frequency on main.

Should we wait for #41520 to be resolved to denoise the test flakiness? Or there is some area that I can take a look?

**Comment by joestringer** [comment]
> Should we wait for https://github.com/cilium/cilium/issues/41520 to be resolved to denoise the test flakiness? Or there is some area that I can take a look?

That issue is closed with a fix merged ~6h ago. Your rebase should have resolved the issue.

**Comment by sugangli** [comment]
Failed at: [Setup & Test (6, 6.1-20250917.183741, none, true, {eth0,eth1}, true, vxlan, snat, true, true, tes...](https://github.com/cilium/cilium/actions/runs/17923745658/job/50964698443#logs)

> failed to fetch cilium status: command failed (pod=kube-system/cilium-4v89c, container=cilium-agent): error sending request: Post "https://0.0.0.0:6443/api/v1/namespaces/kube-system/pods/cilium-4v89c/exec?command=cilium&command=status&command=-o&command=json&container=cilium-agent&stderr=true&stdout=true": EOF

cilium-4v89c was not brought up correctly?

**Comment by sugangli** [comment]
If the PR contributes to any regression to the CI, I would image that should happen at the teardown phase. Or am I missing anything? @fristonio

**Comment by sugangli** [comment]
Failed at ci-gateway-api, and has the same symptom as  #40243
