### PR TITLE
endpoint: trigger k8s sync controller on identity update

### LINKED ISSUE #15097: CI: AutoDirectNodeRoutes Check connectivity with automatic direct nodes routes
## CI failure

```
/home/jenkins/workspace/Cilium-PR-K8s-1.13-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
Connectivity test between nodes failed
Expected
    <bool>: false
to be true
/home/jenkins/workspace/Cilium-PR-K8s-1.13-net-next/src/github.com/cilium/cilium/test/k8sT/DatapathConfiguration.go:337
```

```
cmd: "kubectl exec -n 202102241522k8sdatapathconfigautodirectnoderoutescheckconnectiv testclient-67wmp -- ping -W 5 -c 5 10.0.0.205" exitCode: 1 duration: 9.699427536s stdout:
PING 10.0.0.205 (10.0.0.205) 56(84) bytes of data.

--- 10.0.0.205 ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 4106ms

err:
exit status 1
stderr:
command terminated with exit code 1
```

[9d8296f5_K8sDatapathConfig_AutoDirectNodeRoutes_Check_connectivity_with_automatic_direct_nodes_routes.zip](https://github.com/cilium/cilium/files/6037917/9d8296f5_K8sDatapathConfig_AutoDirectNodeRoutes_Check_connectivity_with_automatic_direct_nodes_routes.zip)

Job run: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.13-net-next/869/

### PR DESCRIPTION
**Pull request by jibi**
When an endpoint's identity is updated, Cilium does not sync immediately
the new state with k8s, but rather waits up to 10 seconds for the
sync-to-k8s-ciliumendpoint controller to run, meaning that the the new
identity can remain unannounced for up to 10 seconds.

This commit fixes this by explicitly triggering the k8s sync controller
whenever an endpoint's identity is updated.

Fixes https://github.com/cilium/cilium/issues/15097

### CODE REVIEW

**Comment by jibi** [comment]
test-me-please

File: pkg/controller/manager.go [hunk 1]
```diff
@@ -135,7 +136,7 @@ func (m *Manager) removeController(ctrl *Controller) {
 	ctrl.getLogger().Debug("Removed controller")
 }
 
-func (m *Manager) lookup(name string) *Controller {
+func (m *Manager) Lookup(name string) *Controller {
```
Comment (gandro) [inline pkg/controller/manager.go]: No action required, just a thought:

One thing that I just noticed is that this export here is the first export that gives access to a `Controller` struct outside of the package. All other methods of the `Manager` do not allow direct access to the `Controller`. While it seems safe (i.e. it seems that `m.mutex` is not protecting it), I wonder if it might be cleaner and more future-proof to expose a `TriggerController(name string)` method instead (similar to `TerminationChannel`), instead of allowing a a direct lookup.

File: pkg/endpoint/endpoint.go [hunk 2]
```diff
@@ -366,6 +370,11 @@ func (e *Endpoint) UpdateController(name string, params controller.ControllerPar
 	e.controllers.UpdateController(name, params)
 }
 
+// TriggerController triggers the endpoint's controller with the specified name.
+func (e *Endpoint) TriggerController(name string) {
+	e.controllers.Lookup(name).Trigger()
```
Comment (gandro) [inline pkg/endpoint/endpoint.go]: Since this is an exported function, we need to check that `Lookup(name) != nil`.

File: pkg/endpoint/endpoint.go [hunk 3]
```diff
@@ -366,6 +370,11 @@ func (e *Endpoint) UpdateController(name string, params controller.ControllerPar
 	e.controllers.UpdateController(name, params)
 }
 
+// TriggerController triggers the endpoint's controller with the specified name.
+func (e *Endpoint) TriggerController(name string) {
```
Comment (gandro) [inline pkg/endpoint/endpoint.go]: nit: I think this function does not necessarily need to be exported in the current implementation. We could even consider inlining it at the call site.

**Review by gandro — COMMENTED** [review]
Thanks a ton for taking care of this! Looks good overall. I have some minor nits (none of which need to be blocking)

File: pkg/controller/manager.go (hunk 1 above)
Comment (jibi) [reply pkg/controller/manager.go]: Yeah, makes sense, that's where `(e *Endpoint) TriggerController(name string)` should actually live :+1:

**Comment by jibi** [comment]
test-me-please

**Review by gandro — APPROVED** [review]

**Comment by jibi** [comment]
retest-gke

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
@jibi can you add the GH issue ID this fixes?

**Comment by jibi** [comment]
> @jibi can you add the GH issue ID this fixes?

@aanm it's in the second commit (I only linked it to #15097 as given the latest comment I don't think this fully fixes also #16302)

**Comment by jibi** [comment]
retest-runtime

File: pkg/endpoint/endpoint.go [hunk 4]
```diff
@@ -2335,3 +2343,12 @@ func (e *Endpoint) setDefaultPolicyConfig() {
...
 }
+
+// SetEndpointSyncControllerName sets the name of the endpoint controller used
+// to synchronize the endpoint itself to kubernetes.
+func (e *Endpoint) SetEndpointSyncControllerName(name string) {
+	e.mutex.Lock()
+	defer e.mutex.Unlock()
+
+	e.endpointSyncControllerName = name
+}
```
Comment (christarazi) [inline pkg/endpoint/endpoint.go]: I have a suggestion that is more aesthetic than it is functional:

What if we instead move `controllerNameOf()` into the endpoint package rather than storing an extra string in the `Endpoint` struct? This way the ep syncher watcher can call `controllerNameOf()` and then when we manually trigger the controller, we call `controllerNameOf()` to get the name of the controller to trigger. Thus, we can avoid storing extra data into the struct.

**Review by christarazi — COMMENTED** [review]
LGTM. I have one suggestion below, but LMK what you think on it.

**Comment by aanm** [comment]
> > @jibi can you add the GH issue ID this fixes?
> 
> @aanm it's in the second commit (I only linked it to #15097 as given the latest comment I don't think this fully fixes also #16302)

@jibi thank you, I meant in the PR description so that GH will close them automatically as soon this PR is merged.

File: pkg/endpoint/endpoint.go (hunk 4 above)
Comment (jibi) [reply pkg/endpoint/endpoint.go]: Yep, makes sense :+1: I was initially a bit hesitant as I felt we were mixing responsibilities (since this function is about a _controller_ name) but in the end it also relates to endpoints so I think it's fine to move it in the `endpoint` package

**Comment by jibi** [comment]
> > > @jibi can you add the GH issue ID this fixes?
> > 
> > 
> > @aanm it's in the second commit (I only linked it to #15097 as given the latest comment I don't think this fully fixes also #16302)
> 
> @jibi thank you, I meant in the PR description so that GH will close them automatically as soon this PR is merged.

My bad, I thought GH would look for that also in commit messages :man_facepalming:

**Comment by jibi** [comment]
test-me-please

**Comment by jibi** [comment]
retest-5.4

**Review by christarazi — APPROVED** [review]

**Comment by gandro** [comment]
Marked as ready to merge. All tests have passed, but the bot is currently known to be broken due to `Validate & Build HTML` being skipped on Non-Docs PR.

**Comment by nbusseneau** [comment]
Added for backporting to 1.10, otherwise we'll continue having these flakes in 1.10 automated jobs ad vitam æternam.
