### PR TITLE
ip-masq-agent: Ensure ip rules match the BPF ip-masq-agent configuration in AWS ENI mode

### LINKED ISSUE #35501: Inconsistent ip rules with BPF ip-masq-agent nonMasqueradeCIDRs
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.15.7 and lower than v1.16.0

### What happened?

# Short summary
Note that this issue is related to https://github.com/cilium/cilium/issues/18179 and https://github.com/cilium/cilium/issues/24000, however I am going to try to expand on both of these here.

We are running Cilium 1.15.9 in AWS in ENI IPAM mode with native routing (`--routing-mode=native`). 

Our goal was to masquerade all traffic which is outside the natively routable CIDRs. These CIDRs don't necessarily belong to the current VPC Cilium is running in: we also have peered VPCs which are natively routable.

In order to achieve this, we enabled BPF masquerading with `--enable-bpf-masquerade=true` and `--enable-ip-masq-agent=true` with the following `ip-masq-agent` configuration:
```yaml
data:
  config.yaml: |
    nonMasqueradeCIDRs:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 100.64.0.0/10
    - 192.168.0.0/16
    masqLinkLocal: false
```
We also don't explicitly set `--ipv4-native-routing-cidr` in our configuration.

Once we deployed Cilium with this configuration, we noticed that traffic to IPs in the peered VPCs was not getting through.

# Example
We have a Kubernetes cluster which is deployed in a VPC with the following CIDRs:
```
$ aws ec2 describe-vpcs --vpc-ids $VPC_ID --query 'Vpcs[].{
        PrimaryCidr: CidrBlock,
        SecondaryCidrs: CidrBlockAssociationSet[].CidrBlock
    }'     --output json
[
    {
        "PrimaryCidr": "10.102.0.0/19",
        "SecondaryCidrs": [
            "10.102.0.0/19",
            "100.130.0.0/16"
        ]
    }
]
```
If we describe a `CiliumNode` object in this cluster, we can see that Cilium correctly detects these CIDRs:
```
$ k get ciliumnode $NODE -o yaml
[...]
  eni:
        [...]
        vpc:
          cidrs:
          - 100.130.0.0/16
          primary-cidr: 10.102.0.0/19
```
Now, we enable BPF Masquerading on that node using the configuration above, we confirm that it was taken into account:
```
# cilium-dbg bpf ipmasq list
IP PREFIX/ADDRESS
10.0.0.0/8
100.64.0.0/10
169.254.0.0/16
172.16.0.0/12
```
We can exec in a test pod which is running on that node and try to reach different endpoints. 

1. Endpoints within the same VPC can be reached (trying with a test server in the same cluster):
```
# curl -v 100.130.57.184:8080
[...]
< HTTP/1.1 200 OK
< Date: Thu, 17 Oct 2024 16:03:22 GMT
< Content-Length: 0
[...]
```
2. Public internet connection is working as well, the IP is masqueraded:
```
# curl ifconfig.me
<This outputs the node's public IP address as expected>
```
3. However, traffic to an endpoint in a peered VPC is dropped:
```
# curl -kvm5 $ENDPOINT_IN_ANOTHER_VPC
*   Trying 10.128.3.79:443...
* After 2497ms connect time, move on!
* connect to 10.128.3.79 port 443 failed: Connection timed out
*   Trying 10.128.20.142:443...
* After 1248ms connect time, move on!
* connect to 10.128.20.142 port 443 failed: Connection timed out
```

If we examine the ip rules on the host, we can see that they look like this (our pod's IP is `100.130.49.239`):
```
$ sudo ip rule
9:	from all fwmark 0x200/0xf00 lookup 2004
20:	from all to 100.130.49.239 lookup main
100:	from all lookup local
109:	from all fwmark 0x80/0xf80 lookup main
111:	from 100.130.87.159 to 10.102.0.0/19 lookup 11
111:	from 100.130.87.159 to 100.130.0.0/16 lookup 11
111:	from 100.130.49.239 to 10.102.0.0/19 lookup 11
111:	from 100.130.49.239 to 100.130.0.0/16 lookup 11
32766:	from all lookup main
32767:	from all lookup default
```

The relevant part is:
```
111:	from 100.130.49.239 to 10.102.0.0/19 lookup 11
111:	from 100.130.49.239 to 100.130.0.0/16 lookup 11
```

The `to` CIDRs are the ones that Cilium auto-detected in the VPC. They will not get masqueraded and will exit through `ens6` (Cilium-managed interface for pods). 

Here is an example route for an endpoint in the same VPC:
```
$ sudo ip route get 100.130.66.240 from 100.130.49.239 iif lxc5c85881afe6f
100.130.66.240 from 100.130.49.239 via 100.130.0.1 dev ens6 table 11
    cache iif lxc5c85881afe6f
```

This is the route for a public internet IP, the traffic goes through `ens5` (primary host interface):
```
$ sudo ip route get 8.8.8.8 from 100.130.49.239 iif lxc5c85881afe6f
8.8.8.8 from 100.130.49.239 via 10.102.31.193 dev ens5
    cache iif lxc5c85881afe6f
```

However, if we try to reach our endpoint which is in another VPC, the traffic will also leave through `ens5`:
```
$ sudo ip route get 10.128.20.142 from 100.130.49.239 iif lxc5c85881afe6f
10.128.20.142 from 100.130.49.239 via 10.102.31.193 dev ens5
    cache iif lxc5c85881afe6f
```
Because we have `10.0.0.0/8` in `nonMasqueradeCIDRs`, the pod's source IP is not getting masqueraded on `ens5` and so the packet is dropped.

To conclude, the routing rules are incorrect, ideally we should have all `nonMasqueradeCIDRs` routed to `ens6` and everything else should be masqueraded and go through `ens5`.

# Possible solutions
Looking at the code, the ip rules are generated by the CNI plugin here:
https://github.com/cilium/cilium/blob/e3a93b184040afe69f394e08bbbc8e69a5feb671/pkg/datapath/linux/routing/routing.go#L88-L103

The CNI plugin takes the `info.IPv4CIDRs` used in the `To` argument from the Cilium Agent here:
https://github.com/cilium/cilium/blob/2bd21121c2f0b76800f55aa6a5746ff40281fe35/plugins/cilium-cni/cmd/cmd.go#L519

The Agent populates the data here:
https://github.com/cilium/cilium/blob/cad67ba4299a9c8f70e5edef7658747685cd7e41/pkg/ipam/crd.go#L686-L691

The problem is that it only uses the auto-detected VPC CIDRs and potentially the `ipv4-native-routing-cidr` parameter if it is specified. The `nonMasqueradeCIDRs` are ignored and thus there are no rules generated for them.

There are a couple of ways to solve this problem:
- If `nonMasqueradeCIDRs` are defined, they could also be added to `result.CIDRs` [here](https://github.com/cilium/cilium/blob/cad67ba4299a9c8f70e5edef7658747685cd7e41/pkg/ipam/crd.go#L686-L691) although I am not sure if this could cause any potential side-effects?
- We could also leverage the existing `ipv4-native-routing-cidr` parameter but it should be made into an array, as proposed in https://github.com/cilium/cilium/issues/24000. Having a single value is very limiting. The refactoring is not going to be trivial because this value is passed down all the way to eBPF code, for example [here](https://github.com/cilium/cilium/blob/164cd86c78e73b8a6fef33e2c4282143ff7dc398/bpf/lib/nat.h#L590-L597). 

Moreover, we could have a way to detect inconsistencies between `ipv4-native-routing-cidr` and `nonMasqueradeCIDRs` because it's easy to shoot yourself in the foot. To go even further, maybe we could even combine these two parameters into one because they serve a similar purpose?

I can help with contributing code if needed but I'm looking for input for us to agree on a direction here.

### How can we reproduce the issue?

This issue should be easy to reproduce if you deploy Cilium with the configuration described in the beginning. The `nonMasqueradeCIDRs` should be a superset of VPC CIDRs where Cilium is deployed to.

### Cilium Version
```
# cilium version
Client: 1.15.9 2653761d6e 2024-10-10T16:16:32+02:00 go version go1.22.7 linux/amd64
Daemon: 1.15.9 2653761d6e 2024-10-10T16:16:32+02:00 go version go1.22.7 linux/amd64
```
### Kernel Version
```
# uname -a
Linux 6.8.0-1016-aws #17~22.04.2-Ubuntu SMP Thu Sep 26 17:15:56 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
### Kubernetes Version
```
$ k version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.31.1-dd.2
```
### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by antonipp**
# Description
See detailed description of the issue in https://github.com/cilium/cilium/issues/35501

This PR ensures that when BPF Masquerading is enabled together with the BPF `ip-masq-agent`, the Cilium Agent managed datapath `ip rule`s are actually consistent with the `ip-masq-agent` configuration. The idea is that all `nonMasqueradeCIDRs` from `ip-masq-agent` configuration actually need to be propagated down to the datapath to ensure that these CIDRs are not masqueraded. 

As mentioned in the issue, the actual datapath `ip rule` setup is here: https://github.com/cilium/cilium/blob/e3a93b184040afe69f394e08bbbc8e69a5feb671/pkg/datapath/linux/routing/routing.go#L88-L103
The `To` CIDRs are coming from the response to the CNI IP Allocation request. The response is populated here:
https://github.com/cilium/cilium/blob/cad67ba4299a9c8f70e5edef7658747685cd7e41/pkg/ipam/crd.go#L686-L691

The newly added logic in my PR simply reads the `ip-masq-agent` config file and returns the non-masqueradable CIDRs in the CNI IP allocation response. 

It's somewhat of a hotpath so I made sure that it fails gracefully if something goes wrong. ~It also makes the best effort to read the CIDRs from memory and not from disk. I also moved the `fsnotify` Watcher instantiation to the `Start()` function to avoid its overhead in the codepath. Finally, in order to avoid race conditions with the `ip-masq-agent` startup and the IP allocation requests (the IPAM Allocator is started before the `ip-masq-agent`), this code doesn't rely on the `ip-masq-agent` being in running state.~ -> This part of the description is obsolete since I ended up doing a refactoring of the `ip-masq-agent` in https://github.com/cilium/cilium/pull/40347 to extract it into a separate Cell.

One small limitation is that the `ip rule`s will not be updated dynamically if the `ip-masq-agent` configuration changes. The new CIDRs will apply to all newly started pods however existing pods will need to be restarted in order for the new CIDRs to be applied. IMO it's not a big deal since the situation is already much better than what we had previously.

# Testing
## Before the PR
Taking the same AWS setup as described in my original issue, when we enable masquerading for a given pod, its `ip rule`s look something like this:
```
$ ip rule | grep 10.130.100.133
111:	from 10.130.100.133 to 10.128.0.0/13 lookup 11
111:	from 10.130.100.133 to 100.112.0.0/13 lookup 11
``` 
The `to` CIDRs are only coming from the VPC CIDRs auto-detected by the Operator. If we enable the `ip-masq-agent`, the rules stay the same.

## After the PR
Once we deploy the PR and then enable `ip-masq-agent` with the following config:
```yaml
  config.yaml: |
    nonMasqueradeCIDRs:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 100.64.0.0/10
    - 192.168.0.0/16
    masqLinkLocal: false
```
The CIDRs are now properly propagated down to the `ip rule` level:
```
$ ip rule | grep 10.112.49.248
111:	from 10.112.49.248 to 10.0.0.0/8 lookup 11
111:	from 10.112.49.248 to 100.64.0.0/10 lookup 11
111:	from 10.112.49.248 to 169.254.0.0/16 lookup 11
111:	from 10.112.49.248 to 172.16.0.0/12 lookup 11
111:	from 10.112.49.248 to 192.168.0.0/16 lookup 11
```

We can also confirm that cross-VPC traffic is no longer dropped.

Fixes: https://github.com/cilium/cilium/issues/35501

```release-note
ip-masq-agent: Ensure ip rules on the host match the BPF ip-masq-agent configuration in AWS ENI mode. Note that rules are set up once at pod creation and will not be regenerated if the ip-masq-agent configuration changes.
```

### CODE REVIEW

File: pkg/ipam/crd.go [hunk 1]
```diff
@@ -774,6 +775,18 @@ func (a *crdAllocator) buildAllocationResult(ip net.IP, ipInfo *ipamTypes.Alloca
 				if a.conf.IPv4NativeRoutingCIDR != nil {
 					result.CIDRs = append(result.CIDRs, a.conf.IPv4NativeRoutingCIDR.String())
 				}
+				// If the ip-masq-agent is enabled, get the CIDRs that are not masqueraded
+				if a.conf.EnableIPMasqAgent {
+					ipmasqAgent := ipmasq.NewIPMasqAgent(a.logger, nil, a.conf.IPMasqAgentConfigPath)
```
Comment (mhofstetter) [inline pkg/ipam/crd.go]: Instead of creating a new instance of the `IPMasqAgent` on every allocation (that is used to retrieve the non-masqueraded CIDRs)  it would actually be great if we could create a new Hive Cell for the `IPMasqAgent`.

It seems that all of the dependencies of the `IPMasqAgent` are already modularized - hence the complete lifecycle (init & start) of the agent could be handled by the Hive Cell instead of being initialized by `daemon_main.go`.

> Finally, in order to avoid race conditions with the ip-masq-agent startup and the IP allocation requests (the IPAM Allocator is started before the ip-masq-agent), this code doesn't rely on the ip-masq-agent being in running state.

Having a single instance of the `IPMasqAgent` provided by a Hive Cell would solve this. The IPAM logic could simply depend on the agent and Hive would ensure that the `IPMasqAgent` is already initialized. `Start` (and therefore `Update`) would already be called and `NonMasqCIDRsFromConfig` wouldn't have to read the config again.

File: pkg/ipmasq/ipmasq.go [hunk 2]
```diff
@@ -99,39 +100,39 @@ type IPMasqAgent struct {
...
-		watcher:                watcher,
 	}
-
-	return a, nil
+	return a
 }
 
 // Start starts the ip-masq-agent goroutine which tracks the config file and
 // updates the BPF map accordingly.
-func (a *IPMasqAgent) Start() {
```
Comment (mhofstetter) [inline pkg/ipmasq/ipmasq.go]: > It's somewhat of a hotpath so I made sure that it fails gracefully if something goes wrong. It also makes the best effort to read the CIDRs from memory and not from disk. I also moved the fsnotify Watcher instantiation to the Start() function to avoid its overhead in the codepath.

Thanks for this cleanup. This would already be a good starting point to extract the `IPMasqAgent` into its own Hive Cell (`newIPMasqAgent` could be called by the config phase & `Start` by the lifecycle start hook).

File: pkg/ipmasq/ipmasq.go [hunk 3]
```diff
@@ -262,6 +265,31 @@ func (a *IPMasqAgent) readConfig() (bool, error) {
 	return false, nil
 }
 
+func (a *IPMasqAgent) NonMasqCIDRsFromConfig() []netip.Prefix {
```
Comment (mhofstetter) [inline pkg/ipmasq/ipmasq.go:262]: It would be nice to have this method free of side-effects (no writes to `a.nonMasqCIDRsFromConfig`). IMO this is only "working" because IPAM creates its own instance of the `IPMasqAgent` - and isn't executed on the instance that gets managed by the Cilium Agent daemon. Ideally this logic would be part of  `readConfig` and executed during the start (and updates to the ipmasq config that trigger `Update`).

BTW: AFAIU, this never actually makes use of the cached info from the memory because it uses a new instance of `IPMasqAgent` on every allocation (it simply reuses the cached info from the start of that new instance).

**Review by mhofstetter — COMMENTED** [review]
Thanks a lot for your contribution @antonipp!

I think it would help to modularize the `IPMasqAgent` and provide it via [Hive Cell](https://docs.cilium.io/en/latest/contributing/development/hive/) first. See my comments inline.

Are you familiar with [Hive](https://docs.cilium.io/en/latest/contributing/development/hive/) and willing to do the extra steps?

File: pkg/ipam/crd.go (hunk 1 above)
Comment (antonipp) [reply pkg/ipam/crd.go]: Thank you for your suggestion! I did think about using Hive (since it would indeed fix the race condition) but I felt that the refactoring would be too much of a lift and would be beyond the scope of the original bug I wanted to fix. However since it could make the bug resolution easier I could give it a try.

Comment (mhofstetter) [reply pkg/ipam/crd.go]: > It seems that all of the dependencies of the IPMasqAgent are already modularized

It looks like the only additional thing would be to modularize and provide the `IPMasqMaps` too. Currently these are initialized by the daemon in `initMaps` (https://github.com/cilium/cilium/blob/main/daemon/cmd/datapath.go#L220-L231)and later used by the `IPMasqAgent`.

Comment (mhofstetter) [reply pkg/ipam/crd.go]: > Thank you for your suggestion! I did think about using Hive (since it would indeed fix the race condition) but I felt that the refactoring would be too much of a lift and would be beyond the scope of the original bug I wanted to fix. However since it could make the bug resolution easier I could give it a try.

That would be great! Maybe worth to tackle first in its own PR and than coming back to this PR and rebase. Sorry for that. In the meantime @pippolo84 can still give his feedback regarding this bugfix from an IPAM point of view.

File: pkg/ipam/crd.go [hunk 4]
```diff
@@ -774,6 +775,18 @@ func (a *crdAllocator) buildAllocationResult(ip net.IP, ipInfo *ipamTypes.Alloca
...
+					nonMasqCidrs := ipmasqAgent.NonMasqCIDRsFromConfig()
```
Comment (mhofstetter) [inline pkg/ipam/crd.go]: > One small limitation is that the ip rules will not be updated dynamically if the ip-masq-agent configuration changes. The new CIDRs will apply to all newly started pods however existing pods will need to be restarted in order for the new CIDRs to be applied. IMO it's not a big deal since the situation is already much better than what we had previously.

maybe worth to document this limitation in a small comment

File: pkg/ipmasq/ipmasq.go [hunk 5]
```diff
@@ -262,6 +265,31 @@ func (a *IPMasqAgent) readConfig() (bool, error) {
...
+	if len(a.nonMasqCIDRsFromConfig) > 0 {
+		return slices.Collect(maps.Values(a.nonMasqCIDRsFromConfig))
+	}
+
+	// If it's empty, populate from config file
+	isEmpty, err := a.readConfig()
+	if err != nil || isEmpty {
+		// Fallback to defaults
+		defaultCIDRs := slices.Collect(maps.Values(defaultNonMasqCIDRs))
+		defaultCIDRs = append(defaultCIDRs, linkLocalCIDRIPv4, linkLocalCIDRIPv6)
```
Comment (pippolo84) [inline pkg/ipmasq/ipmasq.go]: Shouldn't we check `masqLinkLocalIPv4` and `masqLinkLocalIPv6` here too before appending `linkLocalCIDRIPv4` and `linkLocalCIDRIPv6`?

File: pkg/ipam/crd_test.go [hunk 6]
```diff
@@ -130,6 +130,68 @@ func TestMarkForReleaseNoAllocate(t *testing.T) {
 	require.Equal(t, ipamOption.IPAMDoNotRelease, string(cn.Status.IPAM.ReleaseIPs["1.1.1.3"]))
 }
 
+func TestIpMasq(t *testing.T) {
+	cn := newCiliumNode("node1", 4, 4, 0)
+	dummyResource := ipamTypes.AllocationIP{Resource: "eni-1"}
+	cn.Spec.IPAM.Pool[fmt.Sprintf("10.1.1.226")] = dummyResource
```
Comment (pippolo84) [inline pkg/ipam/crd_test.go]: No need to use `fmt.Sprintf` here, we can just use the address as the key

File: pkg/ipam/crd_test.go [hunk 7]
```diff
@@ -130,6 +130,68 @@ func TestMarkForReleaseNoAllocate(t *testing.T) {
 	require.Equal(t, ipamOption.IPAMDoNotRelease, string(cn.Status.IPAM.ReleaseIPs["1.1.1.3"]))
 }
 
+func TestIpMasq(t *testing.T) {
```
Comment (pippolo84) [inline pkg/ipam/crd_test.go]: Nit: `TestIPMasq`

**Review by pippolo84 — COMMENTED** [review]
Couple of minor nits and a question left inline, but overall LGTM from an IPAM point of view.

I second Marco's suggestions about the ip-masq-agent "cellification" and the improvement of `NonMasqCIDRsFromConfig` cache usage.

File: pkg/ipam/crd.go (hunk 4 above)
Comment (pippolo84) [reply pkg/ipam/crd.go]: Might as well expand a bit the release note in the PR description to point out this limitation.

File: pkg/ipam/crd.go (hunk 1 above)
Comment (antonipp) [reply pkg/ipam/crd.go]: Thanks for all the advice, I finally found the time to do the Hive refactoring, here's the PR: https://github.com/cilium/cilium/pull/40347

File: pkg/ipam/crd.go (hunk 4 above)
Comment (antonipp) [reply pkg/ipam/crd.go]: Alright, added a comment and updated the release note to point out this limitation.

File: pkg/ipmasq/ipmasq.go (hunk 3 above)
Comment (antonipp) [reply pkg/ipmasq/ipmasq.go:262]: Makes sense, I completely refactored the code so that it relies on the IPMasqAgent already initialized by the Hive Cell, so now we can simply rely on `a.nonMasqCIDRsFromConfig` and not have any side-effects.

File: pkg/ipmasq/ipmasq.go (hunk 5 above)
Comment (antonipp) [reply pkg/ipmasq/ipmasq.go]: The idea was that when the config is not available, `linkLocalCIDRIPv4` and `linkLocalCIDRIPv6` should be included by default (since the config isn't there, we can't rely on `masqLinkLocalIPv4` and `masqLinkLocalIPv6`), same as https://github.com/cilium/cilium/blob/0a2680cc1eddcd25ad774e2a0f2b6c7b7b97c296/pkg/ipmasq/ipmasq.go#L224-L227

However now that I have refactored the code, we don't need this anymore.

**Comment by antonipp** [comment]
Alright, my `ip-masq-agent` Hive refactoring PR https://github.com/cilium/cilium/pull/40347 has been merged, so I rebased this current PR off the new changes. This simplified the code, LMK what you think!

File: daemon/cmd/daemon_main.go [hunk 8]
```diff
@@ -1399,7 +1398,6 @@ type daemonParams struct {
 	DNSProxy            bootstrap.FQDNProxyBootstrapper
 	DNSNameManager      namemanager.NameManager
 	KPRConfig           kpr.KPRConfig
-	IPMasqAgent         *ipmasq.IPMasqAgent
```
Comment (antonipp) [inline daemon/cmd/daemon_main.go:1402]: I moved the `IPMasqAgent` dependency from the main Daemon cell to the IPAM cell in `pkg/ipam/cell/cell.go`, since this is where it is really required

**Review by mhofstetter — APPROVED** [review]
`sig-agent` looks good to me. Thanks for extracting the IP Masq Agent into its own Hive Cell! It looks way cleaner this way.

**Review by pippolo84 — APPROVED** [review]
Thanks! :100:
