### PR TITLE
tests: rework custom calls's `AfterEach`/`AfterAll` blocks to skip if needed

### LINKED ISSUE #16633: Mispositioned `AfterAll` and `AfterEach` in K8sCustomCalls
The `AfterAll` and `AfterEach` blocks are in the wrong position in https://github.com/cilium/cilium/blob/master/test/k8sT/CustomCalls.go. They are outside the `SkipContextIf` block while the code they are supposed to cleanup is inside the `SkipContextIf` block. As a result they may fail when the `SkipContextIf` is skipped (on 4.9 & 4.19).

That can be seen in https://jenkins.cilium.io/job/Cilium-PR-K8s-1.20-kernel-4.19/769/consoleFull. It's also the reason why a test artifact is collected for K8sCustomCalls even though Jenkins doesn't consider the test failed: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.20-kernel-4.19/769/.

/cc @qmonnet

### PR DESCRIPTION
**Pull request by qmonnet**
The `AfterAll()` and `AfterEach()` blocks in the test file for custom calls run everytime, even if the Context block for the actual tests is skipped. In that case, running the final blocks results in an attempt to remove deployments that have never been set up in the first place. This may lead to the blocks failing when the tests were in fact skipped, and may produce test artifacts even though Jenkins does not considered the test failed.

Fixes: 37f6192c9e77 ("test: add CI test for tail calls hooks for custom programs")
Fixes: #13191
Fixes: #16633

### CODE REVIEW

**Comment by qmonnet** [comment]
test-only --focus="K8sCustomCalls"

**Review by pchaigno — APPROVED** [review]
LGTM, thanks!

We should run the full net-next job though. The installations/cleanups in one test can have impacts on other tests in the suite.

**Comment by qmonnet** [comment]
test-me-please
Yes, I figured the same after launching the focused test :/.

**Comment by pchaigno** [comment]
test-me-please

**Review by christarazi — APPROVED** [review]

File: test/k8sT/CustomCalls.go [hunk 1]
```diff
@@ -115,6 +110,10 @@ var _ = Describe("K8sCustomCalls", func() {
 			ExpectAllPodsTerminated(kubectl)
 		})
 
+		AfterAll(func() {
+			deploymentManager.DeleteAll()
```
Comment (pchaigno) [inline test/k8sT/CustomCalls.go:115]: It seems this is not exactly the same as:
```
 deploymentManager.DeleteCilium()
 deploymentManager.DeleteAll()
```
and doesn't remove the Cilium ConfigMap.

As a result, the few tests following K8sCustomCalls in the net-next job are failing to install Cilium with:
```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: ConfigMap, namespace: kube-system, name: cilium-config
```

**Review by pchaigno — CHANGES_REQUESTED** [review]

File: test/k8sT/CustomCalls.go (hunk 1 above)
Comment (qmonnet) [reply test/k8sT/CustomCalls.go:115]: I see, thanks for looking into it! I added the call to `DeleteCilium()` back, hopefully this time it should work better.

**Review by pchaigno — APPROVED** [review]

File: test/k8sT/CustomCalls.go (hunk 1 above)
Comment (pchaigno) [reply test/k8sT/CustomCalls.go:115]: Note the order is now inverted with this PR. Hopefully, it shouldn't matter.

**Comment by qmonnet** [comment]
test-me-please
