### PR TITLE
daemon, config: regenerate endpoint datapath on agent config change

### LINKED ISSUE #13902: change PolicyAuditMode config option through CLI doesn't affect datapath
## Bug report

**General Information**

- Cilium version v1.8.4
- Kernel version 4.14.67
- Orchestration system version in use K8S v1.17.3

**How to reproduce the issue**

1. create some test pods on node1 and a deny-all CiliumNetworkPolicy enforcing on them, all traffic accessing test pods should be denied
https://docs.cilium.io/en/v1.8/policy/language/#ingress-egress-default-deny
2. execute the following command in cilium-agent on node1 to enable `PolicyAuditMode` on this node, all traffic accessing test pods are expected to be allowed
```
cilium config PolicyAuditMode=enable
```
3. `cilium config | grep PolicyAuditMode` displays the expected output, but traffic to test pods are denied
```
PolicyAuditMode          Enabled
```
cc @ArthurChiao

### PR DESCRIPTION
**Pull request by jaffcheng**
Right now changing some agent options like `PolicyAuditMode` from
cilium CLI succeeds but doesn't affect datapath, e.g.:
# cilium config PolicyAuditMode=true
This patch fixes this by applying agent config changes to endpoint
header file and triggering endpoint datapath regeneration.

Fixes: #13902
Signed-off-by: Jaff Cheng <jaff.cheng.sh@gmail.com>

### CODE REVIEW

File: daemon/cmd/daemon.go [hunk 1]
```diff
@@ -425,6 +428,17 @@ func NewDaemon(ctx context.Context, epMgr *endpointmanager.EndpointManager, dp d
...
+	t, err = trigger.NewTrigger(trigger.Parameters{
+		Name:            "datapath_regeneration",
+		MetricsObserver: &policyTriggerMetrics{},
+		MinInterval:     option.Config.PolicyTriggerInterval,
+		TriggerFunc:     d.datapathRegen,
+	})
+	if err != nil {
+		return nil, nil, err
+	}
+	d.datapathRegenTrigger = t
```
Comment (christarazi) [inline daemon/cmd/daemon.go]: It seems that we are reusing the same `t` variable. Wouldn't that mess with the variable that's already set to the previous `t`?

File: daemon/cmd/daemon.go [hunk 2]
```diff
@@ -803,6 +820,21 @@ func (d *Daemon) TriggerReloadWithoutCompile(reason string) (*sync.WaitGroup, er
...
 
+func (d *Daemon) datapathRegen(reasons []string) {
+	log.Debugf("Regenerating all endpoints with datapath rewrite")
+	reason := strings.Join(reasons, ", ")
+
+	regenerationMetadata := &regeneration.ExternalRegenerationMetadata{
+		Reason:            reason,
+		RegenerationLevel: regeneration.RegenerateWithDatapathRewrite,
+	}
+	d.endpointManager.RegenerateAllEndpoints(regenerationMetadata)
```
Comment (christarazi) [inline daemon/cmd/daemon.go]: I believe regenerating all endpoints will already log a msg, do we need to log this again?

File: pkg/datapath/linux/config/config.go [hunk 3]
```diff
@@ -400,7 +400,8 @@ func (h *HeaderfileWriter) WriteNodeConfig(w io.Writer, cfg *datapath.LocalNodeC
 		ctmap.WriteBPFMacros(fw, nil)
 	}
 
-	if option.Config.PolicyAuditMode {
+	val, ok := option.Config.Opts.Opts[option.PolicyAuditMode]
+	if ok && val != option.OptionDisabled {
```
Comment (christarazi) [inline pkg/datapath/linux/config/config.go]:
```suggestion
	if val, ok := option.Config.Opts.Opts[option.PolicyAuditMode]; ok && val != option.OptionDisabled {
```

File: pkg/endpoint/endpoint.go [hunk 4]
```diff
@@ -684,6 +684,15 @@ func (e *Endpoint) applyOptsLocked(opts option.OptionMap) bool {
 	return changed
 }
 
+func (e *Endpoint) ApplyOpts(opts option.OptionMap) error {
```
Comment (christarazi) [inline pkg/endpoint/endpoint.go]: Could you add a godoc that describes that this function is?

File: pkg/endpointmanager/manager.go [hunk 5]
```diff
@@ -442,6 +442,16 @@ func (mgr *EndpointManager) RegenerateAllEndpoints(regenMetadata *regeneration.E
 	return &wg
 }
 
+func (mgr *EndpointManager) OverrideEndpointOpts(om option.OptionMap) error {
```
Comment (christarazi) [inline pkg/endpointmanager/manager.go]: Here as well

**Review by christarazi — CHANGES_REQUESTED** [review]
Thanks for the PR. Overall, I think it looks good. A few items to address below.

File: daemon/cmd/daemon.go (hunk 1 above)
Comment (jaffcheng) [reply daemon/cmd/daemon.go]: At this point, `t` should already be assigned to `d.policyTrigger` so I think it would be safe to change `t`. I'll use a new name to make it clearer.

File: pkg/endpointmanager/manager.go [hunk 6]
```diff
@@ -442,6 +442,17 @@ func (mgr *EndpointManager) RegenerateAllEndpoints(regenMetadata *regeneration.E
 	return &wg
 }
 
+// OverrideEndpointOpts applies the given options to all endpoints.
+func (mgr *EndpointManager) OverrideEndpointOpts(om option.OptionMap) error {
+	eps := mgr.GetEndpoints()
+	for _, ep := range eps {
```
Comment (christarazi) [inline pkg/endpointmanager/manager.go]:
```suggestion
	for _, ep := range mgr.GetEndpoints() {
```

File: daemon/cmd/daemon.go [hunk 7]
```diff
@@ -425,6 +428,17 @@ func NewDaemon(ctx context.Context, epMgr *endpointmanager.EndpointManager, dp d
 	}
 	d.policyTrigger = t
 
+	regenerationTrigger, err := trigger.NewTrigger(trigger.Parameters{
+		Name:            "datapath_regeneration",
```
Comment (christarazi) [inline daemon/cmd/daemon.go]:
```suggestion
		Name:            "datapath-regeneration",
```

There's a pattern in the code to use dashes.

**Review by christarazi — APPROVED** [review]
LGTM, just a few minor nits to address. Doesn't require another look from me. Can you rebase your PR on lastest master to pick up some CI changes? Currently, we have some Docker rate limiting issues and a rebase would pick up the new mitigations, so that we can run tests against this PR.

File: daemon/cmd/daemon.go (hunk 7 above)
Comment (jaffcheng) [reply daemon/cmd/daemon.go]: Ah seems I followed the pattern of `policy_update`
```
./pkg/ipam/node_manager.go-             Name:            "ipam-node-manager-resync",
./pkg/ipam/node_manager.go-                     Name:            fmt.Sprintf("ipam-pool-maintainer-%s", resource.Name),
./pkg/ipam/node_manager.go-                     Name:        fmt.Sprintf("ipam-pool-maintainer-%s-retry", resource.Name),
./pkg/ipam/node_manager.go-                     Name:            fmt.Sprintf("ipam-node-k8s-sync-%s", resource.Name),
./pkg/ipam/crd.go-              Name:        "crd-allocator-node-refresher",
./pkg/endpoint/endpoint.go-                     Name:        "sync_endpoint_header_file",
./daemon/cmd/daemon.go-         Name:            "policy_update",
```

**Comment by christarazi** [comment]
test-me-please

**Comment by sayboras** [comment]
test-me-please

**Comment by jibi** [comment]
test-me-please

File: daemon/cmd/daemon.go [hunk 8]
```diff
@@ -425,6 +428,17 @@ func NewDaemon(ctx context.Context, epMgr *endpointmanager.EndpointManager, dp d
 	}
 	d.policyTrigger = t
 
+	regenerationTrigger, err := trigger.NewTrigger(trigger.Parameters{
+		Name:            "datapath-regeneration",
+		MetricsObserver: &policyTriggerMetrics{},
```
Comment (jibi) [inline daemon/cmd/daemon.go:446]: Should we define a new `MetricsObserver` and a new constant for the `MinInterval` rather then reusing the ones for the policy trigger?

File: pkg/datapath/linux/config/config.go [hunk 9]
```diff
@@ -400,7 +400,7 @@ func (h *HeaderfileWriter) WriteNodeConfig(w io.Writer, cfg *datapath.LocalNodeC
 		ctmap.WriteBPFMacros(fw, nil)
 	}
 
-	if option.Config.PolicyAuditMode {
+	if val, ok := option.Config.Opts.Opts[option.PolicyAuditMode]; ok && val != option.OptionDisabled {
```
Comment (jibi) [inline pkg/datapath/linux/config/config.go:454]: I don't understand this change as that's the only case we are accessing `Config.Opts.Opts` in `config.go`

File: daemon/cmd/daemon.go (hunk 8 above)
Comment (jaffcheng) [reply daemon/cmd/daemon.go:446]: Not sure if we want to count this in another metric, for now, it's only triggered by agent configuration change, I chose to reuse policyTriggerMetrics according to this comment:
https://github.com/cilium/cilium/blob/9e48678686e213b0b36d616d0bf20f5104eeca04/daemon/cmd/policy.go#L78-L82

File: pkg/datapath/linux/config/config.go (hunk 9 above)
Comment (jaffcheng) [reply pkg/datapath/linux/config/config.go:454]: Hi, I added a comment to explain this change.

**Comment by jibi** [comment]
test-me-please

File: pkg/datapath/linux/config/config.go (hunk 9 above)
Comment (jibi) [reply pkg/datapath/linux/config/config.go:454]: Thanks! :pray:

File: daemon/cmd/daemon.go (hunk 8 above)
Comment (christarazi) [reply daemon/cmd/daemon.go:446]: I think just leaving a small comment to say this is deliberate would be good.

File: pkg/datapath/linux/config/config.go (hunk 9 above)
Comment (jibi) [reply pkg/datapath/linux/config/config.go:454]: On a second look I think this specific change (using `Config.Opts.Opts[option.PolicyAuditMode]` in place of `option.Config.PolicyAuditMode`) should be moved into a separate commit as it's kind of unrelated to the more general change proposed here of regenerating the datapath program on agent config changes

**Comment by jibi** [comment]
Changes LGTM, but there are a few tests in the `Runtime-4.9` suite failing

**Comment by jibi** [comment]
test-gke

**Comment by jaffcheng** [comment]
Thanks for the comments! Added a comment on reusing `policyTriggerMetrics` and split the change of using `Config.Opts.Opts[option.PolicyAuditMode]` to a separate commit. Please take another look

**Comment by jibi** [comment]
test-me-please

**Comment by jaffcheng** [comment]
> test-me-please

Runtime-4.9 failed tests, not sure if related to this PR:
Suite-runtime.RuntimePolicies Test egress with L7 policy to outside cluster
Suite-runtime.RuntimePolicies Extended HTTP Methods tests
Suite-runtime.RuntimePolicies CIDR L3 Policy validates toCIDR

**Comment by jibi** [comment]
> Runtime-4.9 failed tests, not sure if related to this PR:

I don't think this is a flake in the CI as your branch was rebased recently and the `Runtime-4.9` test suite is green on master

**Comment by jaffcheng** [comment]
I'll try to run runtime tests locally

**Comment by jaffcheng** [comment]
test-me-please

**Comment by jaffcheng** [comment]
runtime tests should pass now, please help trigger the tests.

**Comment by aditighag** [comment]
test-me-please

File: pkg/endpoint/endpoint.go [hunk 10]
```diff
@@ -681,6 +681,17 @@ func (e *Endpoint) applyOptsLocked(opts option.OptionMap) bool {
...
 }
 
+// ApplyOpts tries to lock endpoint, applies the given options to the
+// endpoint's options and returns true if there were any options changed.
+func (e *Endpoint) ApplyOpts(opts option.OptionMap) (bool, error) {
+	if err := e.lockAlive(); err != nil {
+		return false, err
+	}
+	defer e.unlock()
+	changed := e.applyOptsLocked(opts)
```
Comment (jibi) [inline pkg/endpoint/endpoint.go:702]: After giving this another look I have one last question: is it safe to _override_ the endpoint opts? Could this trash any option which was set afterwards and was not part of the ones explicitly stored in `option.Config`?

For example: I was looking at the logic in `policy.go`:
https://github.com/cilium/cilium/blob/f66515219c21041f17d424cb8f2ca2b1b81c4687/pkg/endpoint/policy.go#L298-L312 

which in one specific case is responsible for setting an additional option (`Conntrack`)

**Review by jibi — COMMENTED** [review]
I run the unit test locally as Travis CI is unhappy and they are green.
This LGTM now pending one last question

File: pkg/endpoint/endpoint.go (hunk 10 above)
Comment (jaffcheng) [reply pkg/endpoint/endpoint.go:702]: Thanks for the comment, if I understand you correctly, are you concerned about the specific case `opts[option.Conntrack]` not ensured when overriding endpoint opts? I've checked the code path, this is ensured right before regenerating bpf: https://github.com/cilium/cilium/blob/f66515219c21041f17d424cb8f2ca2b1b81c4687/pkg/endpoint/bpf.go#L831

Comment (jibi) [reply pkg/endpoint/endpoint.go:702]: Thanks for confirming :+1:

**Review by jibi — APPROVED** [review]

File: daemon/cmd/daemon.go [hunk 11]
```diff
@@ -803,6 +823,27 @@ func (d *Daemon) TriggerReloadWithoutCompile(reason string) (*sync.WaitGroup, er
...
+	}
+	d.endpointManager.RegenerateAllEndpoints(regenerationMetadata)
+}
+
+// TriggerDatapathRegen triggers policy updates for every daemon's endpoint.
+// The difference with TriggerPolicyUpdates is that this rewrites datapath.
+// This is only called after agent configuration changes for now.
+func (d *Daemon) TriggerDatapathRegen(force bool, reason string) {
+	if force {
+		log.Debugf("Artificially increasing policy revision to enforce policy recalculation")
```
Comment (joestringer) [inline daemon/cmd/daemon.go]:
```suggestion
		log.Debug("Artificially increasing policy revision to enforce policy recalculation")
```

File: daemon/cmd/config.go [hunk 12]
```diff
@@ -80,6 +80,11 @@ func (h *patchConfig) Handle(params PatchConfigParams) middleware.Responder {
 	}
 
 	changes += option.Config.Opts.ApplyValidated(om, changedOption, d)
+	err = d.endpointManager.OverrideEndpointOpts(om)
+	if err != nil {
+		msg := fmt.Errorf("Override endpoint configuration failed %s", err)
```
Comment (joestringer) [inline daemon/cmd/config.go]:
```suggestion
		msg := fmt.Errorf("Override endpoint configuration failed %w", err)
```

File: daemon/cmd/daemon.go (hunk 11 above)
Comment (joestringer) [reply daemon/cmd/daemon.go]: Would also be good to use a completely different log message here to differentiate it from the one in `TriggerPolicyUpdates()`.

File: pkg/endpointmanager/manager.go [hunk 13]
```diff
@@ -432,6 +432,16 @@ func (mgr *EndpointManager) RegenerateAllEndpoints(regenMetadata *regeneration.E
 	return &wg
 }
 
+// OverrideEndpointOpts applies the given options to all endpoints.
+func (mgr *EndpointManager) OverrideEndpointOpts(om option.OptionMap) error {
+	for _, ep := range mgr.GetEndpoints() {
+		if _, err := ep.ApplyOpts(om); err != nil {
+			return err
```
Comment (joestringer) [inline pkg/endpointmanager/manager.go]: If this succeeds for the first endpoint then fails for the second, then any third endpoint will be unaffected. I think that this should probably check the error, then if it is the "endpoint being removed" error, continue, otherwise log the error and continue.

File: daemon/cmd/config.go [hunk 14]
```diff
@@ -80,6 +80,11 @@ func (h *patchConfig) Handle(params PatchConfigParams) middleware.Responder {
...
+		return api.Error(PatchConfigFailureCode, msg)
+	}
```
Comment (joestringer) [inline daemon/cmd/config.go]: Strictly speaking, this has an unintended impact if some portion of the API request fails: If the above is successful, but then line 95 sees an error.. then the endpoint options will have been configured, but the changes will not have been applied yet. Then the API will return an error, but the changes were already made! Then next time someone tries to regenerate the endpoints for any reason, the changes may take effect.

There's two broad ways to solve this:
1. Undo these changes in the error condition below. One way we have done this in the past is to have the function like `OverrideEndpointOpts()` return a "revert function" (see `revertFunc') which can be run in the error condition below.
1. Move the configuration logic into the per-endpoint eventqueues for modifying endpoint state.

**Review by joestringer — CHANGES_REQUESTED** [review]
I have some concerns around corner case error condition handling below.

Also some misc nits around Errorf(), Debugf().

File: daemon/cmd/daemon.go (hunk 11 above)
Comment (joestringer) [reply daemon/cmd/daemon.go]: Actually, for that matter, does this even need to bump the policy revision? Maybe not.

File: pkg/endpointmanager/manager.go (hunk 13 above)
Comment (joestringer) [reply pkg/endpointmanager/manager.go]: ^ May need something like this so you have an error to compare correctly:

```
diff --git a/pkg/endpoint/lock.go b/pkg/endpoint/lock.go
index f9f35a1b140a..51c7f0747920 100644
--- a/pkg/endpoint/lock.go
+++ b/pkg/endpoint/lock.go
@@ -16,12 +16,16 @@ package endpoint

 import "fmt"

+var (
+       ErrEndpointDeleted = fmt.Errorf("lock failed: endpoint is in the process of being removed")
+)
+
 // lockAlive returns error if endpoint was removed, locks underlying mutex otherwise
 func (e *Endpoint) lockAlive() error {
        e.mutex.Lock()
        if e.IsDisconnecting() {
                e.mutex.Unlock()
-               return fmt.Errorf("lock failed: endpoint is in the process of being removed")
+               return ErrEndpointDeleted
        }
        return nil
 }
```

File: daemon/cmd/daemon.go (hunk 11 above)
Comment (jaffcheng) [reply daemon/cmd/daemon.go]: > Actually, for that matter, does this even need to bump the policy revision? Maybe not.

I have removed the code bumping policy revision in a previous patch version, but IT failed due to `PolicyEnforcement` config change needs a newer policy revision, so I kept the behavior from `TriggerPolicyUpdates`. I'll add logic to bump policy revision only on changes including `PolicyEnforcement`.

File: daemon/cmd/config.go (hunk 14 above)
Comment (jaffcheng) [reply daemon/cmd/config.go]: You are right, agent option changes should be reverted on error as well. I think it'd be better to put this into a separate commit before overriding endpoint opts.

**Comment by jaffcheng** [comment]
Rebased, please take another look

File: daemon/cmd/daemon.go [hunk 15]
```diff
@@ -225,9 +225,12 @@ func (d *Daemon) init() error {
 			}
 		}
 
+		option.Config.ConfigPatchMutex.RLock()
 		if err := d.Datapath().Loader().Reinitialize(d.ctx, d, d.mtuConfig.GetDeviceMTU(), d.Datapath(), d.l7Proxy); err != nil {
+			option.Config.ConfigPatchMutex.RUnlock()
 			return err
 		}
+		option.Config.ConfigPatchMutex.RUnlock()
```
Comment (christarazi) [inline daemon/cmd/daemon.go]: Nit: This can be simplified by deferring the `RUnlock()` after the `RLock()`

File: daemon/cmd/config.go [hunk 16]
```diff
@@ -82,16 +83,25 @@ func (h *patchConfig) Handle(params PatchConfigParams) middleware.Responder {
...
+			}
+			option.Config.Opts = oldConfigOpts
+			log.Debug("finished reverting agent configuration changes")
+			option.Config.ConfigPatchMutex.Unlock()
 			return api.Error(PatchConfigFailureCode, msg)
 		}
+		option.Config.ConfigPatchMutex.Unlock()
 		d.TriggerPolicyUpdates(true, "agent configuration update")
+	} else {
+		option.Config.ConfigPatchMutex.Unlock()
```
Comment (christarazi) [inline daemon/cmd/config.go]: Same here about deferring the `RUnlock()`. Eliminates the need to have if-else branches. We know that the unlock should take place at the exit points of the function anyway.

File: pkg/option/config.go [hunk 17]
```diff
@@ -2136,6 +2136,13 @@ func (c *DaemonConfig) SetIPv4NativeRoutingCIDR(cidr *cidr.CIDR) {
 	c.ConfigPatchMutex.Unlock()
 }
 
+// IPv4NativeRoutingCIDRRLocked returns the native routing CIDR if configured,
+// c.ConfigPatchMutex must be held when calling this function.
+func (c *DaemonConfig) IPv4NativeRoutingCIDRRLocked() (cidr *cidr.CIDR) {
+	cidr = c.ipv4NativeRoutingCIDR
+	return
+}
```
Comment (christarazi) [inline pkg/option/config.go]: We can simply return `c.ipv4NativeRoutingCIDR` without needing to make a copy of the pointer. This gets rid of the named return value.

If the intent was to protect `c.ipv4NativeRoutingCIDR`, then a deep copy is required.

File: pkg/endpointmanager/manager.go [hunk 18]
```diff
@@ -432,6 +432,17 @@ func (mgr *EndpointManager) RegenerateAllEndpoints(regenMetadata *regeneration.E
 	return &wg
 }
 
+// OverrideEndpointOpts applies the given options to all endpoints.
+func (mgr *EndpointManager) OverrideEndpointOpts(om option.OptionMap) {
+	for _, ep := range mgr.GetEndpoints() {
+		if _, err := ep.ApplyOpts(om); err != nil && err != endpoint.ErrEndpointDeleted {
```
Comment (christarazi) [inline pkg/endpointmanager/manager.go]: `golint` is advising here to use `errors.Is()` to compare errors.

**Review by christarazi — APPROVED** [review]

File: daemon/cmd/config.go [hunk 19]
```diff
@@ -56,8 +56,13 @@ func (h *patchConfig) Handle(params PatchConfigParams) middleware.Responder {
 	// Track changes to daemon's configuration
 	var changes int
 	var policyEnforcementChanged bool
+	// Copy old configurations for potential reversion
 	oldEnforcementValue := policy.GetPolicyEnabled()
 	oldConfigOpts := option.Config.Opts.DeepCopy()
+	oldEpConfigOpts := make(option.OptionMap)
```
Comment (aanm) [inline daemon/cmd/config.go]: small nit `oldEpConfigOpts := make(option.OptionMap, len(om))`

**Review by aanm — APPROVED** [review]
Just one small nit

File: daemon/cmd/config.go [hunk 20]
```diff
@@ -51,29 +51,30 @@ func (h *patchConfig) Handle(params PatchConfigParams) middleware.Responder {
 
 	// Serialize configuration updates to the daemon.
 	option.Config.ConfigPatchMutex.Lock()
+	defer option.Config.ConfigPatchMutex.Unlock()
```
Comment (joestringer) [inline daemon/cmd/config.go]: These locking changes make me nervous. It looks very easy to misunderstand the locking patterns and introduce a deadlock. I've looked for about half an hour now and I can't convince myself it's correct (it may be; but even if it is, it looks easy to break in future).

I believe this is attempting to address the comments here:
https://github.com/cilium/cilium/pull/13971#discussion_r530021699

Furthermore, I think it is trying to address a case like:
1. API request comes in to configure some setting A
   1. Previous configuration is stored
   1. Configuration is applied
   1. Lock is released
   1. Reinitialization is triggered
1. API request comes in to configure some setting B
   1. Configuration is applied concurrently with reinitialization
   1. Lock is released
   1. Reinitialize is triggered
1. The step (1.iv) fails, so we need to undo the attempt at reconfiguration
   1. Overwrite the configuration with the original state, which undoes setting B modifications
1. The step (2.iii) succeeds, but (3) already reverted the changes

Clearly this is not the behaviour we want the API to have so I agree we should address it :+1: 

That said, I don't think it's a good idea to extend the locking over the entire `Reinitialize()` and try to enforce various places underneath to grab the right locks at the right time. This extends the locking over a long period, and also forces various locations to have more understanding of the locking because the locks aren't following a simple obvious "lock, read/change, unlock" pattern. In fact, the `Reinitialize()` path is shelling out to an external script which runs other processes like a compiler and so on, so we have very few guarantees about how long that will take. It could take seconds or even minutes in a CPU-starved environment (not typical, but possible).

The general way we solve this problem in other cases like policyAdd is to have an eventqueue where the events are serialized, then the reconfiguration is handled from there. If the caller wants to wait for the results, there is a channel-based mechanism to listen for the success or failure of the changes. See `putPolicy.Handle` and its callee `Daemon.PolicyAdd()` for examples.

Why is this different from just grabbing the lock? It allows serialization of the API requests without forcing the underlying data structures to be locked for a long period. The locking of the underlying structures, if necessary, can be handled briefly from various goroutines without introducing arbitrarily long delays. I believe this is already the case today for data like `IPv4NativeRoutingCIDR`, which currently has quite granular locking (which this PR is currently proposing to extend to a long-held lock).

With this approach in place, the core logic of a new eventqueue's `struct ConfigModifyEvent` `Handle()` function could store the changes, lock, modify, unlock, `Reinitialize()`, then choose to either Lock+revert+Unlock or return success depending on the result of the reinitialization.

Originally I thought that maybe there's an alternative path, Undoing the changes in the event of a failure without holding the lock the whole time. For simple cases this *might* be doable to check that the settings are configured how we expect before reverting them in the error handling, but overall the most robust approach would be to follow the EventQueue approach.

**Review by joestringer — CHANGES_REQUESTED** [review]
Thanks for following up and investigating the concerns I brought up. I thought a bit longer about the solution here and I think we need to go further to provide strong guarantees and reduce the potential for long blocking mutexes in the agent. More detail below.

File: daemon/cmd/config.go (hunk 20 above)
Comment (jaffcheng) [reply daemon/cmd/config.go]: Thanks for the detailed write-up! I don't like the locking changes of various places as well. Sorry for not realizing the potential long execution time of `Reinitialize` and the benefit of using an event queue. Will try the suggested approach.

File: daemon/cmd/config.go [hunk 21]
```diff
@@ -89,12 +94,53 @@ func (h *patchConfig) Handle(params PatchConfigParams) middleware.Responder {
...
+	log.WithField(logfields.Params, logfields.Repr(params)).Debug("PATCH /config request")
+
+	c := &ConfigModifyEvent{
+		params: params,
+		h:      h,
+	}
+	cfgModEvent := eventqueue.NewEvent(c)
+	resChan, err := h.daemon.configModifyQueue.Enqueue(cfgModEvent)
+	if err != nil {
+		msg := fmt.Errorf("enqueue of ConfigModifyEvent failed: %s", err)
```
Comment (christarazi) [inline daemon/cmd/config.go]: Nit: `%w` for wrapping errors

File: daemon/cmd/daemon.go [hunk 22]
```diff
@@ -92,6 +93,9 @@ import (
 const (
 	// AutoCIDR indicates that a CIDR should be allocated
 	AutoCIDR = "auto"
+
+	// Size of the event queue for serializing configuration updates to the daemon
```
Comment (christarazi) [inline daemon/cmd/daemon.go]: Nit: godoc should start with `ConfigModifyQueueSize ...`

**Comment by aanm** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
Nice work!

**Comment by joestringer** [comment]
GKE CI job failed, but unclear why due to age. I'll rekick it.

**Comment by joestringer** [comment]
retest-gke

**Comment by joestringer** [comment]
I had originally nominated this for v1.9 backport assuming it is a fairly small change and given the proximity to the v1.9.0 release. At this point, I think the changes are structurally a bit more significant and this goes a bit outside the usual bugfixes for the latest release. Unless I hear a strong argument for why this change is safe to backport to v1.9, I will opt to drop that backport proposal and instead we'll include it in the upcoming v1.10 release.
