### PR TITLE
netkit: Don't let systemd change the MAC address

### LINKED ISSUE #37265: Kubevirt VMs not running with Cilium netkit enabled
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.5 and lower than v1.17.0

### What happened?

Kubevirt VMs are not running when using with Cilium netkit feature. This feature comes to enable a faster connections between the pod and the host devices. They have changed the communication from l2 to l3. Therefore it seems that they're not assigning a mac address to pods anymore. I don't know if this is intended. 

Below, you can see that the mac address is all "zeroed" when using netkit, however, when I rollback to the veth, that is the default config for cilium, it is assigning a mac address. 
 
netkit
```bash
32: eth0@if33: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP,M-DOWN> mtu 9000 qdisc noqueue qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 10.42.1.96/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::200:ff:fe00:0/64 scope link 
       valid_lft forever preferred_lft forever
```
veth
``` bash
40: eth0@if41: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 9000 qdisc noqueue qlen 1000
    link/ether 32:ff:a5:13:fa:09 brd ff:ff:ff:ff:ff:ff
    inet 10.42.0.239/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::30ff:a5ff:fe13:fa09/64 scope link 
       valid_lft forever preferred_lft forever
```

### How can we reproduce the issue?

Enable bpf.datapathMode=netkit on cilium values it will reproduce that. 

cilium values.yaml
``` values.yaml
autoDirectNodeRoutes: true
bandwidthManager:
  enabled: true
  bbr: true
bgpControlPlane:
  enabled: true
bpf:
  datapathMode: netkit
  hostLegacyRouting: false
  masquerade: true
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
cni:
  exclusive: false
devices: bond0
enableIPv4BIGTCP: true
gatewayAPI:
  enabled: true
hubble:
  enabled: true
  relay:
    enabled: true
ipam:
  mode: kubernetes
ipv4NativeRoutingCIDR: 10.42.0.0/16
k8sServiceHost: 127.0.0.1
k8sServicePort: '7445'
kubeProxyReplacement: true
nodePort:
  enabled: true
operator:
  replicas: 2
routingMode: native
securityContext:
  capabilities:
    ciliumAgent:
    - CHOWN
    - KILL
    - NET_ADMIN
    - NET_RAW
    - IPC_LOCK
    - SYS_ADMIN
    - SYS_RESOURCE
    - DAC_OVERRIDE
    - FOWNER
    - SETGID
    - SETUID
    cleanCiliumState:
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RESOURCE
socketLB:
  enabled: true
  hostNamespaceOnly: true
```

### Cilium Version

❯ cilium version
cilium-cli: v0.16.23 compiled with go1.23.4 on darwin/arm64
cilium image (default): v1.16.5
cilium image (stable): v1.16.6
cilium image (running): 1.16.3

### Kernel Version

6.12.9-talos

### Kubernetes Version

v1.32.0

### Regression

if I use veth and not netkit it works fine. 

### Sysdump

_No response_

### Relevant log output

```shell
All connectivity works from pods to pods inside kubernetes with this new cilium feature, however, when I try to create a VM the virt-handler pod crashes. It shows that cannot parse a empty mac address. 

`{"component":"virt-launcher","kind":"","level":"error","msg":"Defining the VirtualMachineInstance failed.","name":"ubuntu-jammy","namespace":"tnt-gabriel-0","pos":"libvirt_helper.go:136","reason":"virError(Code=27, Domain=20, Message='XML error: unable to parse mac address ''')","timestamp":"2025-01-24T21:08:10.715132Z","uid":"d4e7bc50-8efb-4e24-a7aa-4fe22cef250e"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to sync vmi","name":"ubuntu-jammy","namespace":"tnt-gabriel-0","pos":"server.go:202","reason":"virError(Code=27, Domain=20, Message='XML error: unable to parse mac address ''')","timestamp":"2025-01-24T21:08:10.715227Z","uid":"d4e7bc50-8efb-4e24-a7aa-4fe22cef250e"}`


❯ kubectl describe vmi ubuntu-jammy 
Name:         ubuntu-jammy
Namespace:    tnt-gabriel-0
.
.
.
Events:
  Type     Reason            Age                     From                         Message
  ----     ------            ----                    ----                         -------
  Normal   SuccessfulCreate  5m43s                   disruptionbudget-controller  Created PodDisruptionBudget kubevirt-disruption-budget-dlhj6
  Normal   SuccessfulCreate  5m43s                   virtualmachine-controller    Created virtual machine pod virt-launcher-ubuntu-jammy-chzpp
  Warning  SyncFailed        2m43s (x16 over 5m28s)  virt-handler                 server error. command SyncVMI failed: "LibvirtError(Code=27, Domain=20, Message='XML error: unable to parse mac address ''')"
  Warning  SyncFailed        29s                     virt-handler                 cannot detect vm "ubuntu-jammy", err: dial unix //pods/a6086fe3-4700-4d37-94c3-8f4149cbb9f0/volumes/kubernetes.io~empty-dir/sockets/launcher-sock: connect: connection refused
```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jrife**
Systemd will change the random MAC addresses generated for a netkit device pair when [MACAddressPolicy=persistent](https://www.freedesktop.org/software/systemd/man/latest/systemd.link.html#MACAddressPolicy=), seemingly the default on my system and presumably others. Apply the same workaround used in SetupVethWithNames() where "manually" generate and assign a MAC address for both the primary and peer devices, so that Systemd doesn't do this.

Fixes: #37265

```release-note
netkit: Fix issue where MAC addresses get changed by systemd in L2 mode causing health checks to fail
```

### CODE REVIEW

**Comment by jrife** [comment]
FYI @borkmann

File: pkg/datapath/connector/netkit.go [hunk 1]
```diff
@@ -49,14 +51,36 @@ func SetupNetkit(id string, mtu, groIPv6MaxSize, gsoIPv6MaxSize, groIPv4MaxSize,
...
+			return nil, nil, fmt.Errorf("unable to generate rnd mac addr: %w", err)
+		}
 	}
 	netkit := &netlink.Netkit{
 		LinkAttrs: netlink.LinkAttrs{
-			Name:   lxcIfName,
-			TxQLen: 1000,
+			Name:         lxcIfName,
+			TxQLen:       1000,
+			HardwareAddr: net.HardwareAddr(epHostMAC),
```
Comment (borkmann) [inline pkg/datapath/connector/netkit.go:83]: Does this also work for netkit L3 mode? Or does the netlink Go lib not set the attribute if its 0 mac?

**Comment by borkmann** [comment]
> FYI @borkmann

lgtm, thanks!

**Review by borkmann — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Comment by gcezaralmeida** [comment]
Hi @jrife, thank you so much for adding this PR. Which version it will be available? I just checked the new release v.1.17.2 and I didn't find this PR on the release notes.

**Comment by jrife** [comment]
@gcezaralmeida, this isn't currently marked for backport, but I'll check to see if it can be.

**Comment by gcezaralmeida** [comment]
Big shout out to @jrife, thank you so much. I updated to 1.17.3 and it is working fine with Kubevirt.
