### PR TITLE
kvstore/consul: fix race condition

### LINKED ISSUE #984: Possible data race in kvstore
```
WARNING: DATA RACE
Write at 0x00c42044a230 by goroutine 79:
  github.com/cilium/cilium/pkg/kvstore.(*ConsulClient).GetWatcher.func1()
      /home/tgraf/dev/go/src/github.com/cilium/cilium/pkg/kvstore/consul.go:378 +0x17c

Previous read at 0x00c42044a230 by goroutine 61:
  github.com/cilium/cilium/pkg/kvstore.(*ConsulClient).GetWatcher.func1.1()
      /home/tgraf/dev/go/src/github.com/cilium/cilium/pkg/kvstore/consul.go:394 +0x70

Goroutine 79 (running) created at:
  github.com/cilium/cilium/pkg/kvstore.(*ConsulClient).GetWatcher()
      /home/tgraf/dev/go/src/github.com/cilium/cilium/pkg/kvstore/consul.go:399 +0x96
  main.(*Daemon).EnableKVStoreWatcher()
      /home/tgraf/dev/go/src/github.com/cilium/cilium/daemon/kvstore_watcher.go:33 +0xa5
  main.runDaemon()
      /home/tgraf/dev/go/src/github.com/cilium/cilium/daemon/main.go:467 +0x3ce
  main.glob..func1()
      /home/tgraf/dev/go/src/github.com/cilium/cilium/daemon/main.go:92 +0x34
  github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).execute()
      /home/tgraf/dev/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:648 +0x85d
  github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).ExecuteC()
      /home/tgraf/dev/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:735 +0x46b
  github.com/cilium/cilium/vendor/github.com/spf13/cobra.(*Command).Execute()
      /home/tgraf/dev/go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:693 +0x38
  main.main()
      /home/tgraf/dev/go/src/github.com/cilium/cilium/daemon/main.go:97 +0x4e

Goroutine 61 (finished) created at:
  github.com/cilium/cilium/pkg/kvstore.(*ConsulClient).GetWatcher.func1()
      /home/tgraf/dev/go/src/github.com/cilium/cilium/pkg/kvstore/consul.go:397 +0x396
```

### PR DESCRIPTION
**Pull request by aanm**
Signed-off-by: André Martins <andre@cilium.io>

Fixes #984

### CODE REVIEW

File: pkg/kvstore/consul.go [hunk 1]
```diff
@@ -389,12 +389,14 @@ func (c *ConsulClient) GetWatcher(key string, timeSleep time.Duration) <-chan []
 			}
 			curSeconds = time.Second
 			qo.WaitIndex = q.LastIndex
-			go func() {
+			cpyValue := make([]byte, len(k.Value))
+			copy(cpyValue, k.Value)
+			go func(cpyValue []byte) {
```
Comment (tgraf) [inline pkg/kvstore/consul.go]: I assume the purpose of the go subroutine is to avoid blocking on the channel. Does it make sense to instead use a larger buffer for the channel? You are essentially building a buffer using go subroutines and have no limit whatsoever.

At the very least, this needs a good comment explaining why this is done one way or another.

**Review by tgraf — CHANGES_REQUESTED** [review]
At the very least needs a commit message explaining the race and the resolution.

File: pkg/kvstore/consul.go (hunk 1 above)
Comment (tgraf) [reply pkg/kvstore/consul.go]: Any update on this?

Comment (aanm) [reply pkg/kvstore/consul.go]: >  You are essentially building a buffer using go subroutines and have no limit whatsoever.

I gave more thought about it. Changed the commit accordingly, looks good?

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
Looks great now 👍
