### PR TITLE
ipvlan: Avoid spammy dmesg info messages

### LINKED ISSUE #17703: cilium_host/cilium_net: Caught tx_queue_len zero misconfig
**General Information**
- Cilium version (run `cilium version`)
cilium-cli: v0.9.1 compiled with go1.17.1 on darwin/amd64
cilium image (default): v1.10.4
cilium image (stable): unknown
cilium image (running): v1.10.5

- Kernel version (run `uname -a`)
"Linux cp-lab-amukesh4-vmss000000 5.4.0-1062-azure 65~18.04.1-Ubuntu SMP Tue Oct 12 11:26:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux"
- Orchestration system version in use (e.g. `kubectl version`, ...)
kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.13", GitCommit:"53c7b65d4531a749cd3a7004c5212d23daa044a9", GitTreeState:"clean", BuildDate:"2021-07-15T20:53:19Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}

- Link to relevant artifacts (policies, deployments scripts, ...)
https://docs.cilium.io/en/stable/gettingstarted/k8s-install-kubeadm/
**How to reproduce the issue**

These are the kubernetes cluster built via kubeadm on azure VMs.
1. Install cilium 1.10.5 via helm3 and saw the messages reported.
2. Are they going to impact the cluster network connectivity or any other issues in prod?
3. Currently the cluster is healthy and network connectivity is fine but seeing the messages "cilium_net: Caught tx_queue_len zero misconfig" frequently.

1. Cilium Installation via Helm3:
helm install cilium cilium/cilium --version 1.10.5 --namespace kube-system --debug

2.
cilium status
    /¯¯\
 /¯¯\__/¯¯\    Cilium:         OK
 \__/¯¯\__/    Operator:       OK
 /¯¯\__/¯¯\    Hubble:         disabled
 \__/¯¯\__/    ClusterMesh:    disabled
    \__/

DaemonSet         cilium             Desired: 28, Ready: 28/28, Available: 28/28
Deployment        cilium-operator    Desired: 2, Ready: 2/2, Available: 2/2
Containers:       cilium             Running: 28
                  cilium-operator    Running: 2
Cluster Pods:     219/250 managed by Cilium
Image versions    cilium             ******.com/cilium/cilium:v1.10.5: 28
                  cilium-operator    *******.com/cilium/operator-generic:v1.10.5: 2

3. After cilium got initialised, all the nodes in the cluster showing below messages via dmesg -T command

[Mon Oct 25 06:01:29 2021] IPv6: ADDRCONF(NETDEV_CHANGE): cali11641feb8ae: link becomes ready
[Mon Oct 25 06:48:01 2021] IPv6: ADDRCONF(NETDEV_CHANGE): cilium_net: link becomes ready
[Mon Oct 25 06:48:01 2021] IPv6: ADDRCONF(NETDEV_CHANGE): cilium_host: link becomes ready
[Mon Oct 25 06:48:01 2021] NET: Registered protocol family 38
[Mon Oct 25 06:48:02 2021] IPv6: ADDRCONF(NETDEV_CHANGE): lxc_health: link becomes ready
[Mon Oct 25 06:48:03 2021] cilium_host: Caught tx_queue_len zero misconfig
[Mon Oct 25 06:48:03 2021] cilium_net: Caught tx_queue_len zero misconfig
[Mon Oct 25 06:48:08 2021] lxc_health: Caught tx_queue_len zero misconfig

[Mon Oct 25 07:22:27 2021] lxc667d091cb0ea: Caught tx_queue_len zero misconfig
[Mon Oct 25 07:22:27 2021] lxc742557edbdd8: Caught tx_queue_len zero misconfig
[Mon Oct 25 07:22:27 2021] lxc_health: Caught tx_queue_len zero misconfig
[Mon Oct 25 07:22:27 2021] lxcb7215aa13fc7: Caught tx_queue_len zero misconfig
[Mon Oct 25 07:22:30 2021] hv_balloon: Max. dynamic memory size: 16384 MB

### PR DESCRIPTION
**Pull request by chendotjs**
Avoid spamming the kernel log with below messages when creating ipvlan slave:

[Tue Oct 26 14:20:38 2021] cilium: renamed from tmp_svwpi
[Tue Oct 26 14:20:38 2021] cilium: Caught tx_queue_len zero misconfig
[Tue Oct 26 14:20:46 2021] cilium_host: Caught tx_queue_len zero misconfig
[Tue Oct 26 14:32:11 2021] eth0: renamed from tmp6fed1
[Tue Oct 26 14:32:11 2021] eth0: Caught tx_queue_len zero misconfig

@mukeshkwm reported similar issue on veth datapath, which also applies to ipvlan datapath.

Fixes: #17703
Signed-off-by: Chen Yaqi <chendotjs@gmail.com>

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]

**Review by borkmann — APPROVED** [review]

File: pkg/datapath/connector/ipvlan.go [hunk 1]
```diff
@@ -156,6 +156,7 @@ func createIpvlanSlave(lxcIfName string, mtu, masterDev int, mode string, ep *mo
 		LinkAttrs: netlink.LinkAttrs{
 			Name:        lxcIfName,
 			ParentIndex: masterDev,
+			TxQLen:      1000,
```
Comment (joamaki) [inline pkg/datapath/connector/ipvlan.go:159]: While it probably makes no difference in the ipvlan case, I think the proper fix might be to set it `-1` instead:
https://github.com/vishvananda/netlink/blob/master/link_linux.go#L1370

**Review by joamaki — CHANGES_REQUESTED** [review]

File: pkg/datapath/connector/ipvlan.go (hunk 1 above)
Comment (joamaki) [reply pkg/datapath/connector/ipvlan.go:159]: @borkmann what's the effect of having tx_queue_length set to a high number for ipvlan or veth? Should we change it to -1 in the veth case as well?

EDIT: Ah, net/pkt_sched.h has the default tx_queue_length set to 1000 and that's also used at least for veth, so makes no practical difference currently if it's 1000 or -1 here.

**Review by joamaki — APPROVED** [review]
Approving, but consider using `-1` as the constant instead of `1000` so it'll pick whatever is the kernel default.

File: pkg/datapath/connector/ipvlan.go (hunk 1 above)
Comment (borkmann) [reply pkg/datapath/connector/ipvlan.go:159]: We were basically hitting this one:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/sched/sch_api.c#n1237

Comment (borkmann) [reply pkg/datapath/connector/ipvlan.go:159]: I think the underlying issue is on kernel side to some extend in that for veth devs we don't intent to add a "real" qdisc, but rather clsact one. I'd think this spam message should be guarded behind != TC_H_INGRESS, e.g. when someone tries to attach htb and such. tx_queue_length is never used in case of clsact.

**Comment by pchaigno** [comment]
Reviews are in. k8s-1.16-kernel-netnext hit known flake https://github.com/cilium/cilium/issues/17661. Marking ready to merge and merging.
