### PR TITLE
bpf: only clean up XDP from devices with XDP attached

### LINKED ISSUE #13526: Traffic disruption during cilium-agent upgrade/restart with Mellanox NICs
## Bug report

We found that when upgrading cilium-agent from `1.7.4` to `1.8.4`, both **node traffic** as well as **Pod traffic** would get interrupted for a few seconds (e.g. `1~10s` according to our observation). The problem is 100% reproducible.

Further tests show that event **restart cilium-agent container** could reproduce this interruption.

**General Information**

- Cilium version: `1.8.4`
- Kernel version: `4.19.118`
- **NIC: `mlx5`, Mellanox Technologies MT27710 Family [ConnectX-4 Lx]**

**Note that we find this problem only appears on nodes that shipped with Mellanox NICs.**

## Trace the problem

We notice that each time the problem appears, there will be a `Link up` message in `dmesg`:

```
[Tue Oct 13 10:12:03 2020] mlx5_core 0000:08:00.0 eth0: Link up
[Tue Oct 13 10:12:03 2020] mlx5_core 0000:08:00.1 eth1: Link up
```

Further digging we find that it is originated from `init.sh` during agent start/restart, which unconditionally performs XDP resets:

https://github.com/cilium/cilium/blob/master/bpf/init.sh#L658

```shell
# Remove bpf_xdp.o from previously used devices
for iface in $(ip -o -a l | awk '{print $2}' | cut -d: -f1 | cut -d@ -f1 | grep -v cilium); do
	[ "$iface" == "$XDP_DEV" ] && continue
	for mode in xdpdrv xdpgeneric; do
		xdp_unload "$iface" "$mode"
	done
done

function xdp_unload()
{
	DEV=$1
	MODE=$2

	ip link set dev $DEV $MODE off 2> /dev/null || true
}
```

It seems this works fine for NICs from many vendors (e.g. Intel), but not for Mellanox ones.

As a quick test, comment out the above `xdp_unload`, the problem disappears.

@jaffcheng is working on a patch to fix this.

### PR DESCRIPTION
**Pull request by jaffcheng**
Currently, during agent startup, cilium removes XDP from all
interfaces except for `cilium_host`, `cilium_net` and `$XDP_DEV`
regardless of whether there is an XDP program attached to it.

For some drivers, e.g. Mellanox mlx5, the following command will
cause device reset regardless of whether there is an XDP program
attached to it, which introduces node and pod network interruption:
`ip link set dev $DEV xdpdrv off`.

This patch adds a check of XDP program existence to avoid such
network interruption.

Fixes: #13526
Reported-by: ArthurChiao <arthurchiao@hotmail.com>
Signed-off-by: Jaff Cheng <jaff.cheng.sh@gmail.com>

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

File: bpf/init.sh [hunk 1]
```diff
@@ -656,7 +656,7 @@ if [ "$HOST_DEV1" != "$HOST_DEV2" ]; then
 fi
 
 # Remove bpf_xdp.o from previously used devices
-for iface in $(ip -o -a l | awk '{print $2}' | cut -d: -f1 | cut -d@ -f1 | grep -v cilium); do
+for iface in $(ip -o -a l | grep prog/xdp | awk '{print $2}' | cut -d: -f1 | cut -d@ -f1 | grep -v cilium); do
```
Comment (pchaigno) [inline bpf/init.sh:659]: @qmonnet IIRC, that `prog/xdp` tag isn't present with older versions of iproute2, right? Do you remember what version is needed?

Comment (qmonnet) [reply bpf/init.sh:659]: [Commit a0b5b7cf5c05](https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/commit/?id=a0b5b7cf5c05) (`bpf: consolidate dumps to use bpf_dump_prog_info`) seems to be in iproute2 v4.13 (`iproute2-ss170905`)

Comment (qmonnet) [reply bpf/init.sh:659]: For what it's worth `bpftool net show` supports it from version 4.20, but with the added benefit of failing if listing XDP programs is not supported.

On an unrelated note, we have an occasion here to make the command above cleaner by doing the text processing in `awk` only instead of spawning additional processes for `cut` and `grep`. I would even be inclined to using `ip`'s JSON output, but I don't think we currently require `jq` be always present on the machines?

Comment (pchaigno) [reply bpf/init.sh:659]: Ok, so this change is safe to backport to 1.8 and 1.7 if needed since we use iproute2 v4.20 there.

**Review by pchaigno — APPROVED** [review]

File: bpf/init.sh (hunk 1 above)
Comment (jaffcheng) [reply bpf/init.sh:659]: Hi, thanks for the comment. I think the newly added `grep` is expected to exclude most devices in the first place, so the existing `cut` and `grep` process may not affect performance, what about improving readability in a separate PR?

**Review by vadorovsky — APPROVED** [review]

**Review by tklauser — APPROVED** [review]
