### PR TITLE
bgpv1 + bgpv2: Fix DiffStore to work with multiple server instances

### LINKED ISSUE #33076: LoadBalancer IPs don't seem to be being advertised (pod cidr works)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi All,

Not sure if this is me or my setup but Im pretty sure I've setup everything in a way where it should now be advertising external IP Loadbalancer routes from my worker for a plex pod, but when I check with FRR routing and opnsense (my upstream routers).  I can't see anything being advertised other than the podCidr range.

If I do a show ip bgp neighbor received routes it shows nothing from the LB pools and I've checked they are not being accidently filtered.

I've tried all wierd and wonderful ways of trying to select the ippool but whatever happens it is never advertised even though kubectl get all is showing the loadbalancerIP is there in the namespace attached to the service.

My config settings are as follows:

```
root@kube4master:~/k8s# kubectl get all -n plex -o wide
NAME                        READY   STATUS    RESTARTS   AGE   IP           NODE          NOMINATED NODE   READINESS GATES
pod/plex-798d4bfb9f-qdlj6   1/1     Running   0          23h   10.0.5.108   kube6worker   <none>           <none>

NAME              TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)           AGE   SELECTOR
service/plex-lb   LoadBalancer   10.43.109.182   10.100.198.10   32400:32624/TCP   22h   app=plex

NAME                   READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES                    SELECTOR
deployment.apps/plex   1/1     1            1           12d   plex4        linuxserver/plex:latest   app=plex

NAME                              DESIRED   CURRENT   READY   AGE   CONTAINERS   IMAGES                    SELECTOR
replicaset.apps/plex-575cf8f9fd   0         0         0       12d   plex4        linuxserver/plex:latest   app=plex,pod-template-hash=575cf8f9fd
replicaset.apps/plex-678f59468    0         0         0       12d   plex4        linuxserver/plex:latest   app=plex,pod-template-hash=678f59468
replicaset.apps/plex-77758bb5d5   0         0         0       12d   plex4        linuxserver/plex:latest   app=plex,pod-template-hash=77758bb5d5
replicaset.apps/plex-798d4bfb9f   1         1         1       10d   plex4        linuxserver/plex:latest   app=plex,pod-template-hash=798d4bfb9f
replicaset.apps/plex-c87dcc9d7    0         0         0       12d   plex4        linuxserver/plex:latest   app=plex,pod-template-hash=c87dcc9d7
```

```
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
 name: 01-bgp-peering-policy-node-supa1
spec: # CiliumBGPPeeringPolicySpec
 nodeSelector:
   matchLabels:
     bgp-policy: node-supa1
 virtualRouters: # []CiliumBGPVirtualRouter
 - localASN: 100
   exportPodCIDR: false
   neighbors: # []CiliumBGPNeighbor
    - peerAddress: '10.12.89.1/32'
      peerASN: 65551
      #authSecretRef: secretname
      eBGPMultihopTTL: 3
      connectRetryTimeSeconds: 5
      holdTimeSeconds: 180
      keepAliveTimeSeconds: 60
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 12
    - peerAddress: '10.12.95.1/24'
      peerASN: 65010
      #authSecretRef: secretname
      eBGPMultihopTTL: 3
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 12
      families:
      - afi: ipv4
        safi: unicast
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "wizznet-pool"
spec:
  blocks:
  - cidr: "10.100.198.0/24"

```

another attempt

```
root@kube4master:~/k8s# cat bgp-config-pol-node-supa1.yaml
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
 name: 01-bgp-peering-policy-node-supa1
spec: # CiliumBGPPeeringPolicySpec
 nodeSelector:
   matchLabels:
     bgp-policy: node-supa1
 virtualRouters: # []CiliumBGPVirtualRouter
 - localASN: 100
   exportPodCIDR: true
   podIPPoolSelector:
      matchLabels:
        io.cilium.podippool.name: wizznet-pool
#      matchExpressions:
#         - {key: somekey, operator: NotIn, values: ['never-used-value']}
   neighbors: # []CiliumBGPNeighbor
#    - peerAddress: '10.12.89.1/32'
#      peerASN: 65551
#      #authSecretRef: secretname
 #     eBGPMultihopTTL: 3
 #     connectRetryTimeSeconds: 5
 #     holdTimeSeconds: 180
 #     keepAliveTimeSeconds: 60
 #     gracefulRestart:
 #       enabled: true
 #       restartTimeSeconds: 12
    - peerAddress: '10.12.95.1/24'
      peerASN: 65010
      #authSecretRef: secretname
      eBGPMultihopTTL: 3
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 12
#      families:
#      - afi: ipv4
#        safi: unicast
#      connectRetryTimeSeconds: 5
#      holdTimeSeconds: 180
#      keepAliveTimeSeconds: 60
#      gracefulRestart:
#        enabled: true
#        restartTimeSeconds: 12
#    - peerAddress: '10.12.95.11/32'
 #     peerASN: 65011
      #authSecretRef: secretname
#      eBGPMultihopTTL: 2
#      connectRetryTimeSeconds: 15
#      holdTimeSeconds: 5
#      keepAliveTimeSeconds: 5
#      gracefulRestart:
#        enabled: true
#        restartTimeSeconds: 12
#    - peerAddress: '10.12.95.12/32'
#      peerASN: 65012
#      #authSecretRef: secretname
#      eBGPMultihopTTL: 2
#      connectRetryTimeSeconds: 15
#      holdTimeSeconds: 5
#      keepAliveTimeSeconds: 5
#      gracefulRestart:
#        enabled: true
#        restartTimeSeconds: 12
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "wizznet-pool"
spec:
  blocks:
  - cidr: "10.100.198.0/24"
```

`kubectl label nodes kube6worker bgp-policy=node-supa1 --overwrite`

FRR upstream
```
*kube4master(10.12.95.151)                      4        100     11022     11056        0    0    0 09:10:25            2       11 N/A
*kube6worker(10.12.95.152)                      4        100     11029     11056        0    0    0 09:10:27            2       11 N/A
*kube1(10.12.95.155)                            4        100     11012     11056        0    0    0 09:10:27            0       11 N/A
```

```
supa1# show ip bgp neighbors 10.12.95.152 received-routes
BGP table version is 103, local router ID is 10.12.89.10, vrf id 0
Default local pref 100, local AS 65010
Status codes:  s suppressed, d damped, h history, * valid, > best, = multipath,
               i internal, r RIB-failure, S Stale, R Removed
Nexthop codes: @NNN nexthop's vrf id, < announce-nh-self
Origin codes:  i - IGP, e - EGP, ? - incomplete
RPKI validation codes: V valid, I invalid, N Not found

    Network          Next Hop            Metric LocPrf Weight Path
 *> 10.12.10.0/24    10.12.95.152                           0 100 65551 i
 *> 10.12.89.0/24    10.12.95.152                           0 100 65551 i

Total number of prefixes 2
supa1# show ip bgp neighbors 10.12.95.152 filtered-routes
BGP table version is 103, local router ID is 10.12.89.10, vrf id 0
Default local pref 100, local AS 65010
Status codes:  s suppressed, d damped, h history, * valid, > best, = multipath,
               i internal, r RIB-failure, S Stale, R Removed
Nexthop codes: @NNN nexthop's vrf id, < announce-nh-self
Origin codes:  i - IGP, e - EGP, ? - incomplete
RPKI validation codes: V valid, I invalid, N Not found

    Network          Next Hop            Metric LocPrf Weight Path

```

```
root@kube4master:~# cilium config view
agent-not-ready-taint-key                         node.cilium.io/agent-not-ready
arping-refresh-period                             30s
auto-direct-node-routes                           false
bgp-announce-lb-ip                                true
bpf-lb-acceleration                               disabled
bpf-lb-external-clusterip                         false
bpf-lb-map-max                                    65536
bpf-lb-sock                                       false
bpf-map-dynamic-size-ratio                        0.0025
bpf-policy-map-max                                16384
bpf-root                                          /sys/fs/bpf
cgroup-root                                       /run/cilium/cgroupv2
cilium-endpoint-gc-interval                       5m0s
cluster-id                                        0
cluster-name                                      default
cluster-pool-ipv4-cidr                            10.0.0.0/8
cluster-pool-ipv4-mask-size                       24
cni-exclusive                                     true
cni-log-file                                      /var/run/cilium/cilium-cni.log
custom-cni-conf                                   false
debug                                             true
debug-verbose
dnsproxy-enable-transparent-mode                  true
egress-gateway-reconciliation-trigger-interval    1s
enable-auto-protect-node-port-range               true
enable-bgp-control-plane                          true
enable-bpf-clock-probe                            false
enable-endpoint-health-checking                   true
enable-health-check-loadbalancer-ip               false
enable-health-check-nodeport                      true
enable-health-checking                            true
enable-hubble                                     true
enable-ipv4                                       true
enable-ipv4-big-tcp                               false
enable-ipv4-masquerade                            true
enable-ipv6                                       false
enable-ipv6-big-tcp                               false
enable-ipv6-masquerade                            true
enable-k8s-networkpolicy                          true
enable-k8s-terminating-endpoint                   true
enable-l2-neigh-discovery                         true
enable-l7-proxy                                   true
enable-local-redirect-policy                      false
enable-masquerade-to-route-source                 false
enable-metrics                                    true
enable-policy                                     default
enable-remote-node-identity                       true
enable-sctp                                       false
enable-svc-source-range-check                     true
enable-vtep                                       false
enable-well-known-identities                      false
enable-wireguard                                  true
enable-xt-socket-fallback                         true
external-envoy-proxy                              false
hubble-disable-tls                                false
hubble-export-file-max-backups                    5
hubble-export-file-max-size-mb                    10
hubble-listen-address                             :4244
hubble-socket-path                                /var/run/cilium/hubble.sock
hubble-tls-cert-file                              /var/lib/cilium/tls/hubble/server.crt
hubble-tls-client-ca-files                        /var/lib/cilium/tls/hubble/client-ca.crt
hubble-tls-key-file                               /var/lib/cilium/tls/hubble/server.key
identity-allocation-mode                          crd
identity-gc-interval                              15m0s
identity-heartbeat-timeout                        30m0s
install-no-conntrack-iptables-rules               false
ipam                                              cluster-pool
ipam-cilium-node-update-rate                      15s
k8s-client-burst                                  20
k8s-client-qps                                    10
kube-proxy-replacement                            strict
kube-proxy-replacement-healthz-bind-address
max-connected-clusters                            255
mesh-auth-enabled                                 true
mesh-auth-gc-interval                             5m0s
mesh-auth-queue-size                              1024
mesh-auth-rotated-identities-queue-size           1024
monitor-aggregation                               medium
monitor-aggregation-flags                         all
monitor-aggregation-interval                      5s
node-port-bind-protection                         true
nodes-gc-interval                                 5m0s
operator-api-serve-addr                           127.0.0.1:9234
operator-prometheus-serve-addr                    :9963
policy-cidr-match-mode
preallocate-bpf-maps                              false
procfs                                            /host/proc
proxy-connect-timeout                             2
proxy-max-connection-duration-seconds             0
proxy-max-requests-per-connection                 0
proxy-prometheus-port                             9964
remove-cilium-node-taints                         true
routing-mode                                      tunnel
service-no-backend-response                       reject
set-cilium-is-up-condition                        true
set-cilium-node-taints                            true
sidecar-istio-proxy-image                         cilium/istio_proxy
skip-cnp-status-startup-clean                     false
synchronize-k8s-nodes                             true
tofqdns-dns-reject-response-code                  refused
tofqdns-enable-dns-compression                    true
tofqdns-endpoint-max-ip-per-hostname              50
tofqdns-idle-connection-grace-period              0s
tofqdns-max-deferred-connection-deletes           10000
tofqdns-proxy-response-max-delay                  100ms
tunnel-protocol                                   vxlan
unmanaged-pod-watcher-interval                    15
vtep-cidr
vtep-endpoint
vtep-mac
vtep-mask
write-cni-conf-when-ready                         /host/etc/cni/net.d/05-cilium.conflist
```

I'm running out of things to check, I seemed to have no problems when using the older technique of using MetalLB.

Any help or pointers appreciated.

Thanks,
Jon.

### Cilium Version

1.15.5

### Kernel Version

Linux kube4master 6.8.4-3-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.4-3 (2024-05-02T11:55Z) x86_64 GNU/Linux

### Kubernetes Version

k3s v1.29.5+k3s1

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rastislavs**
As the same DiffStore instance is used to diff services when reconciling for multiple server instances (virtual routers), we need to differentiate the diff per instance (and to be future-proof per reconciler as well) for diff to work properly.

Fixes: #33076

```release-note
BGPv1 + BGPv2: Fix incorrect service reconciliation in setups with multiple BGP instances (virtual routers)
```

### CODE REVIEW

**Review by harsimran-pabla — APPROVED** [review]
Thanks, lgtm  🚀

File: pkg/bgpv1/manager/store/diffstore.go [hunk 1]
```diff
@@ -115,22 +121,30 @@ func (ds *diffStore[T]) handleEvent(event resource.Event[T]) {
...
 	defer ds.mu.Unlock()
 
 	if ds.store == nil {
 		return nil, nil, ErrStoreUninitialized
 	}
 
+	updatedKeys, ok := ds.callerUpdatedKeys[callerID]
+	if !ok {
+		// caller-specific updated keys map does not exist yet, create and return all items as upserted
+		ds.callerUpdatedKeys[callerID] = make(updatedKeysMap)
```
Comment (YutaroHayakawa) [inline pkg/bgpv1/manager/store/diffstore.go]: While we create the `callerUpdatedKeys` entry here, we don't have any logic to remove the entry. This results in leaking the memory for the diffs for the BGP instance that no longer exists. Also, when we delete and re-add the BGP instance, it potentially gets some garbage diffs.

In the current design, ServiceReconciler keeps the per-instance state locally, which I think causes this leakage. We don't have any "hook" to clean the per-instance data in the reconciler because we declined this design in the past and decided to keep the per-instance state in the metadata. Maybe it's time for us to revisit this?

**Review by YutaroHayakawa — CHANGES_REQUESTED** [review]

File: pkg/bgpv1/manager/store/diffstore.go (hunk 1 above)
Comment (rastislavs) [reply pkg/bgpv1/manager/store/diffstore.go]: Ah right, looks like we may need to introduce something like a new `Cleanup(instance)` method for the reconcilers to cleanup per-instance state held outside of the reconciler metadata.

Comment (YutaroHayakawa) [reply pkg/bgpv1/manager/store/diffstore.go]: +1 to introduce `Cleanup(instance)`.

**Comment by rastislavs** [comment]
@YutaroHayakawa , @harsimran-pabla changes since the previous version:
- The `DiffStore` got two new methods, `InitDiff` and `CleanupDiff`.
- The `InitDiff` is necessary so that we do not miss delete events between the full reconcile and the initial caller-specific `Diff`. We call `InitDiff` upon full reconciliation in the reconcilers, so that `Diff` returns changes since the last full or partial reconcile.
- In BGPv1 we were doing partial reconciliation even during the first reconcile. It wasn't a problem, since all changes were in the diffstore, but now we always start with a full reconcile.
- To wire the `CleanupDiff` call, new reconciler method `Cleanup(instance)` has been introduced for both BGPv1 and v2.
- `Cleanup(instance)` is NOT called when the instance is re-created by the preflight reconcilers. It is not a problem ATM, as that always causes a full reconciliation, during which `InitDiff` is called and we start with a clean diff in the reconciler. 

However, we need to think about how we can call `Cleanup(instance)` for all reconcilers when it the instance is re-created from the preflight reconcilers if we want to remove the common reconciler metadata in the future. I was thinking of removing the preflight "reconcilers" and moving their logic into manager, or having some other way to tell the manager that the instance needs to be re-created. Right now it is kind of weird that these reconcilers are modifying manager-specific stuff (instance and metadata).

File: pkg/bgpv1/manager/reconcilerv2/service.go [hunk 2]
```diff
@@ -147,7 +161,7 @@ func (r *ServiceReconciler) reconcileServices(ctx context.Context, p ReconcilePa
 
 		// get services to reconcile and to withdraw.
 		// Note : we should only call svc diff only once in a reconcile loop.
-		toReconcile, toWithdraw, err := r.diffReconciliationServiceList()
+		toReconcile, toWithdraw, err := r.diffReconciliationServiceList(p)
```
Comment (harsimran-pabla) [inline pkg/bgpv1/manager/reconcilerv2/service.go:172]: In cases we call partial reconciliation before full reconciliation and init is not yet done, error will be returned.
Should we attempt to trigger full reconciliation in those cases? For both in v1 and v2 versions. 

I am thinking if there is a such a situation, we will not be able to recover unless something changes in BGP configuration which will trigger full reconciliation.

File: pkg/bgpv1/manager/store/diffstore.go [hunk 3]
```diff
@@ -115,22 +127,36 @@ func (ds *diffStore[T]) handleEvent(event resource.Event[T]) {
...
 	ds.mu.Lock()
 	defer ds.mu.Unlock()
 
 	if ds.store == nil {
 		return nil, nil, ErrStoreUninitialized
 	}
 
+	updatedKeys, ok := ds.callerUpdatedKeys[callerID]
+	if !ok {
+		return nil, nil, fmt.Errorf("diff not initialized for caller %s", callerID)
```
Comment (harsimran-pabla) [inline pkg/bgpv1/manager/store/diffstore.go]: It would be nice to have defined error type for this condition, which caller can use to resolve it.

File: pkg/bgpv1/manager/reconcilerv2/service.go (hunk 2 above)
Comment (rastislavs) [reply pkg/bgpv1/manager/reconcilerv2/service.go:172]: I would say performing a partial reconciliation before full reconciliation is done is a bug in the reconciler, but yeah, to be more resilient we can put this recovery logic (catching this error running full reconcile upon it) into the reconcilers.

**Review by YutaroHayakawa — APPROVED** [review]

**Comment by YutaroHayakawa** [comment]
> Cleanup(instance) is NOT called when the instance is re-created by the preflight reconcilers. It is not a problem ATM, as that always causes a full reconciliation, during which InitDiff is called and we start with a clean diff in the reconciler.

How about introducing `Init(instance)` which is called when the instance is created?

**Comment by rastislavs** [comment]
> How about introducing `Init(instance)` which is called when the instance is created instead of lazily call it on the initial reconciliation?

Yes I think introducing `Init(instance)` to the reconciler API makes sense, that should also address @harsimran-pabla 's concern about potentially calling partial reconciliation before full reconciliation (that would not be a problem anymore). 

However, as we do not have an easy way to call `Init(instance)` of the other reconcilers from the preflight reconciler, some further refactoring of the preflight logic will anyway be needed to allow removing `InitDiff(callerID)` call from the full reconciliation.

**Comment by rastislavs** [comment]
@YutaroHayakawa , @harsimran-pabla I have added `Init(instance)` method as well, and included ASN in the "instance" structs (otherwise it was not available during `Init`).

File: pkg/bgpv1/manager/store/diffstore.go (hunk 3 above)
Comment (rastislavs) [reply pkg/bgpv1/manager/store/diffstore.go]: defined an error for it

File: pkg/bgpv1/manager/reconcilerv2/service.go (hunk 2 above)
Comment (rastislavs) [reply pkg/bgpv1/manager/reconcilerv2/service.go:172]: This is no longer an issue - we now initialize the store in the new `Init(instance)` reconciler method.

**Review by harsimran-pabla — APPROVED** [review]
Thanks, lgtm!

File: pkg/bgpv1/manager/instance/instance.go [hunk 4]
```diff
@@ -22,6 +22,9 @@ import (
 //
 // This is used in BGPv1 implementation.
 type ServerWithConfig struct {
+	// ASN is the local ACN number of the virtual router instance.
```
Comment (YutaroHayakawa) [inline pkg/bgpv1/manager/instance/instance.go]: Nit: ACN => ASN

File: pkg/bgpv1/manager/reconciler/reconciler.go [hunk 5]
```diff
@@ -30,6 +30,12 @@ type ConfigReconciler interface {
 	// Priority is used to determine the order in which reconcilers are called. Reconcilers are called from lowest to
 	// highest.
 	Priority() int
+	// Init is called upon virtual router instance creation. Reconcilers can initialize any instance-specific
+	// resources here, and clean them up upon Cleanup call.
+	Init(sc *instance.ServerWithConfig) error
+	// Cleanup is called upon virtual router instance deletion. When called, reconcilers are supposed
+	// to clean up all instance-specific resourced saved outside the ReconcilerMetadata.
```
Comment (YutaroHayakawa) [inline pkg/bgpv1/manager/reconciler/reconciler.go]: resourced => resources

File: pkg/bgpv1/manager/reconciler/service.go [hunk 6]
```diff
@@ -100,6 +116,8 @@ func (r *ServiceReconciler) requiresFullReconciliation(p ReconcileParams) bool {
 	var existingSelector *slim_metav1.LabelSelector
 	if p.CurrentServer != nil && p.CurrentServer.Config != nil {
 		existingSelector = p.CurrentServer.Config.ServiceSelector
+	} else {
+		return true // the first reconciliation should be always full
```
Comment (YutaroHayakawa) [inline pkg/bgpv1/manager/reconciler/service.go:120]: Do we still need this after we introduce `Init`?

**Review by YutaroHayakawa — APPROVED** [review]
Nice work! A few non-blocking comments.

File: pkg/bgpv1/manager/reconciler/service.go (hunk 6 above)
Comment (rastislavs) [reply pkg/bgpv1/manager/reconciler/service.go:120]: Yes, I think we should still start with a full reconcile - otherwise we could miss the events between the `DiffStore` creation and `InitDiff` call for the instance.
