### PR TITLE
bpf: Remove CT_REOPENED, return CT_NEW instead

### LINKED ISSUE #27762: CI: Conformance E2E: client-egress-l7-named-port/pod-to-pod: command terminated with exit code 28 (timeout)
## CI failure

Matrix entry: (5, 5.15-20230420.212204, iptables, true, disabled, dsr, true, true, true)

```
ℹ️  📜 Applying CiliumNetworkPolicy 'client-egress-only-dns' to namespace 'cilium-test'..
  ℹ️  📜 Applying CiliumNetworkPolicy 'client-egress-l7-http-named-port' to namespace 'cilium-test'..
  [-] Scenario [client-egress-l7-named-port/pod-to-pod]
  [.] Action [client-egress-l7-named-port/pod-to-pod/curl-ipv4-0: cilium-test/client-6b4b857d98-hnf49 (10.244.1.76) -> cilium-test/echo-other-node-8f5d547bf-sgh62 (10.244.2.69:8080)]
  [.] Action [client-egress-l7-named-port/pod-to-pod/curl-ipv6-0: cilium-test/client-6b4b857d98-hnf49 (fd00:10:244:1::47c6) -> cilium-test/echo-other-node-8f5d547bf-sgh62 (fd00:10:244:2::294e:8080)]
  [.] Action [client-egress-l7-named-port/pod-to-pod/curl-ipv4-1: cilium-test/client-6b4b857d98-hnf49 (10.244.1.76) -> cilium-test/echo-same-node-7c978647dc-xr2kt (10.244.1.111:8080)]
  [.] Action [client-egress-l7-named-port/pod-to-pod/curl-ipv6-1: cilium-test/client-6b4b857d98-hnf49 (fd00:10:244:1::47c6) -> cilium-test/echo-same-node-7c978647dc-xr2kt (fd00:10:244:1::19cd:8080)]
  [.] Action [client-egress-l7-named-port/pod-to-pod/curl-ipv4-2: cilium-test/client2-646b88fb9b-x8j2f (10.244.1.44) -> cilium-test/echo-other-node-8f5d547bf-sgh62 (10.244.2.69:8080)]
  ❌ command "curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code} --silent --fail --show-error --output /dev/null --connect-timeout 2 --max-time 10 http://10.244.2.69:8080/" failed: command terminated with exit code 28
  ℹ️  curl output:


📋 Test Report
connectivity test failed: 1 tests failed
❌ 1/53 tests failed (1/575 actions), 8 tests skipped, 0 scenarios skipped:
Test [client-egress-l7-named-port]:
  ❌ client-egress-l7-named-port/pod-to-pod/curl-ipv4-2: cilium-test/client2-646b88fb9b-x8j2f (10.244.1.44) -> cilium-test/echo-other-node-8f5d547bf-sgh62 (10.244.2.69:8080)
Error: Process completed with exit code 1.
```

Looks similar to https://github.com/cilium/cilium/issues/27672 but not related to multicluster.

From a quick sysdump check, there seems to be something wrong with Envoy and the http conneciton:

```
$ cat hubble-flows-cilium-* | hubble observe --input-file - --numeric --to-ip 10.244.2.69 --port 8080 --from-ip 10.244.1.44 --type l7
Aug 28 17:16:59.869: 10.244.1.44:44528 (ID:11576) -> 10.244.2.69:8080 (ID:25450) http-request FORWARDED (HTTP/1.1 GET http://10.244.2.69:8080/)
Aug 28 17:17:21.203: 10.244.1.44:54076 (ID:11576) -> 10.244.2.69:8080 (ID:25450) http-request FORWARDED (HTTP/1.1 GET http://10.244.2.69:8080/)
Aug 28 17:15:50.297: 10.244.1.44:37878 (ID:11576) -> 10.244.2.69:8080 (ID:25450) http-request FORWARDED (HTTP/1.1 GET http://10.244.2.69:8080/public)
Aug 28 17:15:50.377: 10.244.1.44:45332 (ID:11576) -> 10.244.2.69:8080 (ID:25450) http-request DROPPED (HTTP/1.1 GET http://10.244.2.69:8080/private)
Aug 28 17:15:50.453: 10.244.1.44:45348 (ID:11576) -> 10.244.2.69:8080 (ID:25450) http-request FORWARDED (HTTP/1.1 GET http://10.244.2.69:8080/private)
Aug 28 17:16:18.302: 10.244.1.44:45148 (ID:11576) -> 10.244.2.69:8080 (ID:25450) http-request FORWARDED (HTTP/1.1 GET http://10.244.2.69:8080/public)
Aug 28 17:16:18.375: 10.244.1.44:45162 (ID:11576) -> 10.244.2.69:8080 (ID:25450) http-request DROPPED (HTTP/1.1 GET http://10.244.2.69:8080/private)
Aug 28 17:16:18.445: 10.244.1.44:45166 (ID:11576) -> 10.244.2.69:8080 (ID:25450) http-request FORWARDED (HTTP/1.1 GET http://10.244.2.69:8080/private)
```

[cilium-sysdump-5-final.zip](https://github.com/cilium/cilium/files/12458796/cilium-sysdump-5-final.zip)

### PR DESCRIPTION
**Pull request by jrajahalme**
CT_REOPENED was originally added in https://github.com/cilium/cilium/pull/13340 to emit policy verdicts for apparently re-opened TCP connections, which are in fact more likely to be newly opened TCP connections rather than re-opened ones, as the CT entries may live minutes after the TCP state from the endpoints has already timed out.

This added complexity to call sites, forcing differentiation between CT_NEW and CT_REOPENED. In all cases some CT entry field values were left stale, e.g., 'proxy_redirect' after a policy change.

Instead of adjusting each call site to behave properly for CT_REOPENED, return CT_NEW instead, and make the observable CT lookup behavior the same as for CT_NEW in that case, most notably by not updating the passed in `*ct_state'.

This change fixes proxy redirection bug where return packets are not redirected to an L7 proxy when (a stale) CT entry is missing the 'proxy_redirect' flag.

For this bug to trigger a pod needs to open a new TCP connection using the same (ephemeral) source port to the same destination before and after a change in policy adding an L7 policy applicable to that connection. While this is a bug that has surfaced in CI, this bug is less likely to be hit when policies are more stable. Given this we need further discussion about backporting this bug fix to the stable releases.

Fixes: #27762
Fixes: #13340

Note: This PR is an alternative to https://github.com/cilium/cilium/pull/32614, only one of these should be merged.

```release-note
Datapath conntrack entries for reopened connections are fully reinitialized to fix rare L7 proxy redirect failures.
```

### CODE REVIEW

**Comment by julianwiedmann** [comment]
Thank you for the context on why `CT_REOPENED` was introduced in the first place! That makes it way easier to evaluate the change.

Looking at all [the info](https://github.com/cilium/cilium/blob/bf74e877ea34ed111c5cf2d1905dad1412b7c37f/bpf/lib/common.h#L945) in the `ct_entry` and what's already [cleared](https://github.com/cilium/cilium/blob/bf74e877ea34ed111c5cf2d1905dad1412b7c37f/bpf/lib/conntrack.h#L318) by the CT lookup, there isn't much that would be worth preserving from the "old" connection. Essentially just `packets` and `bytes`. The `lifetime` looks like [ct_create4()](https://github.com/cilium/cilium/blob/bf74e877ea34ed111c5cf2d1905dad1412b7c37f/bpf/lib/conntrack.h#L994) will end up setting the same value. We probably should have a look at how `monitor` gets sets for the `CT_REOPENED` path, so that `last_tx_report` / `last_rx_report` stay in sync with that. But besides that, completely resetting the `ct_entry` seems alright.

So this makes a lot of sense to me :+1:. And we can figure out what to do about stale `CT_ESTABLISHED` lookup results separately.

File: bpf/lib/conntrack.h [hunk 1]
```diff
@@ -320,7 +321,11 @@ __ct_lookup(const void *map, struct __ctx_buff *ctx, const void *tuple,
 				entry->seen_non_syn = false;
 
 				*monitor = ct_update_timeout(entry, is_tcp, dir, seen_flags);
-				return CT_REOPENED;
+
+				/* Return CT_NEW so that the caller creates a new entry instead of
+				 * updating the old one. (For policy drops the old entry remains.)
+				 */
+				return CT_NEW;
```
Comment (julianwiedmann) [inline bpf/lib/conntrack.h:328]: Do you think we should remove the `ct_reset_closing()` and `ct_reset_seen_flags()` here as well? I'm undecided on the `ct_update_timeout()` call ... it almost feels like we should just have a `goto ct_new`.

File: bpf/bpf_lxc.c [hunk 2]
```diff
@@ -1979,28 +1961,11 @@ ipv4_policy(struct __ctx_buff *ctx, struct iphdr *ip4, int ifindex, __u32 src_la
...
-				ct_has_nodeport_egress_entry4(get_ct_map4(tuple),
-							      tuple, NULL, false);
-
-			ct_state_new.node_port = node_port;
-			if (ret == CT_REOPENED &&
-			    ct_state->node_port != node_port)
-				ct_update_nodeport(get_ct_map4(tuple), tuple,
-						   node_port);
-		}
-	}
```
Comment (julianwiedmann) [inline bpf/bpf_lxc.c]: https://github.com/cilium/cilium/pull/32642 already landed, so this will need a trivial rebase.

File: bpf/lib/nodeport.h [hunk 3]
```diff
@@ -2106,10 +2105,8 @@ nodeport_extract_dsr_v4(struct __ctx_buff *ctx,
 #endif
 
 	/* SYN for a new connection that's not / no longer DSR.
-	 * If it's reopened, avoid sending subsequent traffic down the DSR path.
+	 * If it's reopened, the CT entry will be re-created with a cleared dsr flag.
 	 */
-	if (tuple->nexthdr == IPPROTO_TCP)
-		ct_update_dsr(get_ct_map4(&tmp), &tmp, false);
```
Comment (julianwiedmann) [inline bpf/lib/nodeport.h]: I'm not 100% on this. Right now it covers not just `CT_REOPENED`, but also the case where we receive multiple SYNs (by a oddly-behaving client :)). The 2nd/3rd/... SYN would get matched as `CT_ESTABLISHED`, no? So we still want to update the DSR-state accordingly.

File: api/v1/flow/flow.proto [hunk 4]
```diff
@@ -196,7 +196,7 @@ enum TraceReason {
     ESTABLISHED = 2;
     REPLY = 3;
     RELATED = 4;
-    REOPENED = 5;
+    DEPRECATED_REOPENED = 5;
```
Comment (kaworu) [inline api/v1/flow/flow.proto]: I'm fine with internal renamings for clarity, but this one would be a breaking change because enums are represented with their text value (i.e. not their protobuf field number) when marshaled into JSON according to our configuration.
```suggestion
    REOPENED = 5 [deprecated=true];
```

**Review by kaworu — CHANGES_REQUESTED** [review]

File: bpf/lib/conntrack.h (hunk 1 above)
Comment (jrajahalme) [reply bpf/lib/conntrack.h:328]: Not sure. It is still possible that a new entry will not be created due to a policy DROP, so I left these be.

File: bpf/lib/nodeport.h (hunk 3 above)
Comment (jrajahalme) [reply bpf/lib/nodeport.h]: This was not done for `CT_ESTABLISHED`, so this change is correct IMO. Also, I don't know if it is possible for dsr to be `true` in the case you refer to (re-transmitted `SYN`s).

File: api/v1/flow/flow.proto (hunk 4 above)
Comment (jrajahalme) [reply api/v1/flow/flow.proto]: Did not realize this, thanks! Reverted this change, except for `[deprecated=true]` you suggested and the Go const name.

File: bpf/bpf_lxc.c (hunk 2 above)
Comment (jrajahalme) [reply bpf/bpf_lxc.c]: Done!

File: bpf/lib/conntrack.h (hunk 1 above)
Comment (julianwiedmann) [reply bpf/lib/conntrack.h:328]: Hmm yes makes sense.

File: bpf/lib/nodeport.h (hunk 3 above)
Comment (julianwiedmann) [reply bpf/lib/nodeport.h]: >This was not done for CT_ESTABLISHED, so this change is correct IMO.

I don't follow, could you elaborate?

>Also, I don't know if it is possible for dsr to be true in the case you refer to (re-transmitted SYNs).

How do you mean? Yes, I'm pretty sure the described scenario (first SYN with DSR-info, second SYN without DSR-info) is possible.

**Review by kaworu — APPROVED** [review]
Thanks for the update, Hubble changes LGTM now.

File: bpf/lib/nodeport.h (hunk 3 above)
Comment (jrajahalme) [reply bpf/lib/nodeport.h]: You are right, I had this mixed up. Reverted this change (also for v6).

**Review by julianwiedmann — APPROVED** [review]
Looks good, thank you Jarno!

:heavy_check_mark:, assuming that `ct_update_dsr()` is re-instated to fix the build.

**Review by julianwiedmann — APPROVED** [review]

**Review by ysksuzuki — APPROVED** [review]
