### PR TITLE
pkg/endpoint: close and reopen policy map if dump fails

### LINKED ISSUE #4229: policy synchronization to bpf map fails with bad file descriptor
```
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])   IPv6                 IPv4            STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                     
17471      Enabled            Enabled           30534      container:id.server           f00d::a0f:0:0:443f   10.15.244.141   ready   
28219      Enabled            Enabled           28411      container:id.curl2            f00d::a0f:0:0:6e3b   10.15.197.39    ready   
29898      Enabled            Enabled           4          reserved:health               f00d::a0f:0:0:74ca   10.15.242.54    ready   
34700      Enabled            Enabled           37903      container:id.httpd            f00d::a0f:0:0:878c   10.15.213.77    ready   
                                                           container:id.service1                                                      
35132      Enabled            Enabled           29594      container:id.httpd_deny       f00d::a0f:0:0:893c   10.15.223.69    ready   
                                                           container:id.service1                                                      
42380      Enabled            Enabled           49577      container:id.curl             f00d::a0f:0:0:a58c   10.15.249.57    ready   
50640      Enabled            Enabled           40075      container:id.client           f00d::a0f:0:0:c5d0   10.15.166.9     ready   
```

#### BPF Policy Get 17471

```
DIRECTION   LABELS (source:key[=value])   PORT/PROTO   BYTES      PACKETS   
Ingress     container:id.client           ANY          54192711   837762    
Ingress     reserved:host                 ANY          0          0         

```

Most likely reason

```
  sync-policymap-17471                 never          0s ago       11      synchronizing desired PolicyMap state failed: [Unable to update element: bad file descriptor Unable to update element: bad file descriptor]  
```

The ICMP requests were actually denied by the L3 policy but I'm not sure how would that be possible since the bpf policy map does not contain egress policy
```
[2018-05-23 20:29:38] CPU 01: MARK 0x820bbc60 FROM 50640 from-endpoint: 118 bytes, state new, identity 40075->0
[2018-05-23 20:29:38] Ethernet	{Contents=[..14..] Payload=[..110..] SrcMAC=da:0f:8c:3e:02:c4 DstMAC=8a:be:6e:ff:da:d0 EthernetType=IPv6 Length=0}
[2018-05-23 20:29:38] IPv6	{Contents=[..40..] Payload=[..64..] Version=6 TrafficClass=0 FlowLabel=789378 Length=64 NextHeader=ICMPv6 HopLimit=64 SrcIP=f00d::a0f:0:0:c5d0 DstIP=f00d::a0f:0:0:443f HopByHop=nil}
[2018-05-23 20:29:38] ICMPv6	{Contents=[..8..] Payload=[..56..] TypeCode=EchoRequest Checksum=40278 TypeBytes=[79, 0, 0, 0]}
[2018-05-23 20:29:38] CPU 01: MARK 0x820bbc60 FROM 50640 DEBUG: Handling ICMPv6 type=128
[2018-05-23 20:29:38] CPU 01: MARK 0x820bbc60 FROM 50640 DEBUG: Successfully mapped daddr.p4=[::0:443f] to identity=30534
[2018-05-23 20:29:38] CPU 01: MARK 0x820bbc60 FROM 50640 DEBUG: Attempting local delivery for container id 17471 from seclabel 40075
[2018-05-23 20:29:38] CPU 01: MARK 0x820bbc60 FROM 50640 DEBUG: Local container found ifindex lxc4ace3 seclabel 30534
[2018-05-23 20:29:38] ------------------------------------------------------------------------------
[2018-05-23 20:29:38] CPU 01: MARK 0x820bbc60 FROM 17471 to-endpoint: 118 bytes, state new, interface lxc4ace3, identity 40075->30534, to endpoint 17471
[2018-05-23 20:29:38] Ethernet	{Contents=[..14..] Payload=[..110..] SrcMAC=da:5f:9d:78:5d:f1 DstMAC=7a:6f:b2:ee:ec:93 EthernetType=IPv6 Length=0}
[2018-05-23 20:29:38] IPv6	{Contents=[..40..] Payload=[..64..] Version=6 TrafficClass=0 FlowLabel=789378 Length=64 NextHeader=ICMPv6 HopLimit=63 SrcIP=f00d::a0f:0:0:c5d0 DstIP=f00d::a0f:0:0:443f HopByHop=nil}
[2018-05-23 20:29:38] ICMPv6	{Contents=[..8..] Payload=[..56..] TypeCode=EchoRequest Checksum=40278 TypeBytes=[79, 0, 0, 0]}
[2018-05-23 20:29:38] ------------------------------------------------------------------------------
[2018-05-23 20:29:38] CPU 01: MARK 0x16ed3f0 FROM 17471 from-endpoint: 118 bytes, state new, identity 30534->0
[2018-05-23 20:29:38] Ethernet	{Contents=[..14..] Payload=[..110..] SrcMAC=7a:6f:b2:ee:ec:93 DstMAC=da:5f:9d:78:5d:f1 EthernetType=IPv6 Length=0}
[2018-05-23 20:29:38] IPv6	{Contents=[..40..] Payload=[..64..] Version=6 TrafficClass=0 FlowLabel=224769 Length=64 NextHeader=ICMPv6 HopLimit=64 SrcIP=f00d::a0f:0:0:443f DstIP=f00d::a0f:0:0:c5d0 HopByHop=nil}
[2018-05-23 20:29:38] ICMPv6	{Contents=[..8..] Payload=[..56..] TypeCode=EchoReply Checksum=40022 TypeBytes=[79, 0, 0, 0]}
[2018-05-23 20:29:38] CPU 01: MARK 0x16ed3f0 FROM 17471 DEBUG: Handling ICMPv6 type=129
[2018-05-23 20:29:38] CPU 01: MARK 0x16ed3f0 FROM 17471 DEBUG: Successfully mapped daddr.p4=[::0:c5d0] to identity=40075
[2018-05-23 20:29:38] CPU 01: MARK 0x16ed3f0 FROM 17471 DEBUG: Policy evaluation would deny packet from 30534 to 40075
[2018-05-23 20:29:38] ------------------------------------------------------------------------------
[2018-05-23 20:29:38] CPU 01: MARK 0x16ed3f0 FROM 17471 DROP: 118 bytes, reason Policy denied (L3), to ifindex 0, identity 30534->0
[2018-05-23 20:29:38] Ethernet	{Contents=[..14..] Payload=[..110..] SrcMAC=7a:6f:b2:ee:ec:93 DstMAC=da:5f:9d:78:5d:f1 EthernetType=IPv6 Length=0}
[2018-05-23 20:29:38] IPv6	{Contents=[..40..] Payload=[..64..] Version=6 TrafficClass=0 FlowLabel=224769 Length=64 NextHeader=ICMPv6 HopLimit=64 SrcIP=f00d::a0f:0:0:443f DstIP=f00d::a0f:0:0:c5d0 HopByHop=nil}
[2018-05-23 20:29:38] ICMPv6	{Contents=[..8..] Payload=[..56..] TypeCode=EchoReply Checksum=40022 TypeBytes=[79, 0, 0, 0]}
```

Related with https://github.com/cilium/cilium/issues/3970

The logs from this output can be found here https://github.com/cilium/cilium/issues/3970#issuecomment-391496306

### PR DESCRIPTION
**Pull request by ianvernon**
Sometimes, policy map updates for endpoints fail in CI with errors like the following:

"Unable to update element: bad file descriptor"

It is not known why this occurs; to mitigate this, try to close the existing map, and then reopen the PolicyMap for the endpoint again upon the first access of it in syncPolicyMap,
which is the dumping of the map into a slice of PolicyKey entries. After reopening the map, attempt to dump again.

Furthermore, this PR sets the file descriptor of the PolicyMap to be 0 once the `Close()` operation is performed upon it. It also logs when `Close()` is called for easier debugging of the lifecycle of a `PolicyMap`.

Fixes: #4229

Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4299)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
@eloycoto there are no logs for the build https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/3688/ which caused the test failure. Do you know why? The contents of `test-output.log` just seem to stop after we try to get Cilium logs :(

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

File: pkg/endpoint/bpf.go [hunk 1]
```diff
@@ -622,18 +622,15 @@ func (e *Endpoint) regenerateBPF(owner Owner, epdir, reason string) (uint64, err
 		}
 	}()
 
-	// Create the policymap on the first pass
 	if e.PolicyMap == nil {
 		e.PolicyMap, createdPolicyMap, err = policymap.OpenMap(e.PolicyMapPathLocked())
 		if err != nil {
-			e.Mutex.Unlock()
```
Comment (tgraf) [inline pkg/endpoint/bpf.go]: Why are you removing the Unlock?

File: pkg/endpoint/bpf.go [hunk 2]
```diff
@@ -622,18 +622,15 @@ func (e *Endpoint) regenerateBPF(owner Owner, epdir, reason string) (uint64, err
...
 			return 0, err
 		}
 		// Clean up map contents
-		log.Debugf("Flushing old policies map")
+		e.getLogger().Debug("flushing old PolicyMap")
 		err = e.PolicyMap.Flush()
 		if err != nil {
-			e.Mutex.Unlock()
```
Comment (tgraf) [inline pkg/endpoint/bpf.go]: Why are you removing the Unlock?

File: pkg/endpoint/endpoint.go [hunk 3]
```diff
@@ -2408,6 +2408,10 @@ func (e *Endpoint) InsertEvent() {
 // Must be called with e.Mutex locked.
 func (e *Endpoint) syncPolicyMap() error {
 
+	var (
+		err error
```
Comment (tgraf) [inline pkg/endpoint/endpoint.go]: This is probably not needed but also not wrong

**Review by tgraf — DISMISSED** [review]

File: pkg/endpoint/endpoint.go [hunk 4]
```diff
@@ -2422,8 +2426,24 @@ func (e *Endpoint) syncPolicyMap() error {
 
 	currentMapContents, err := e.PolicyMap.DumpToSlice()
 
+	// If map is unable to be dumped, attempt to close map and open it again.
 	if err != nil {
-		return fmt.Errorf("unable to dump PolicyMap for endpoint: %s", err)
+		// Close to avoid file descriptor leaking.
+		err := e.PolicyMap.Close()
```
Comment (raybejjani) [inline pkg/endpoint/endpoint.go]: This shadows the err declared at the start of this function (we have a similar setup in the `for _, entry := range currentMapContents` loop. It should be fine, because we return a different error directly, but it might make for some subtle bugs at some point (or you intended for it to be this way because `err2` and `err3` seem silly?)

File: pkg/maps/policymap/policymap.go [hunk 5]
```diff
@@ -257,9 +263,22 @@ func (pm *PolicyMap) Flush() error {
...
+	log.WithFields(logrus.Fields{
+		logfields.BPFMapPath: pm.path,
+		logfields.BPFMapFD:   pm.Fd,
+	}).Debug("closing PolicyMap")
+	err := bpf.ObjClose(pm.Fd)
+	if err == nil {
+		// Set file descriptor to zero so that if accesses are attempted on this
+		// PolicyMap even after this call to Close, the access aren't to a file
+		// descriptor that has been reassigned elsewhere.
+		pm.Fd = 0
```
Comment (raybejjani) [inline pkg/maps/policymap/policymap.go]: this might be racey with other closes. The struct doesn't seems to have any concurrency guards but it might also be intended as immutable (or that all the mutable state is held in-kernel).

File: pkg/endpoint/endpoint.go [hunk 6]
```diff
@@ -2422,8 +2426,24 @@ func (e *Endpoint) syncPolicyMap() error {
...
+		if err != nil {
+			return fmt.Errorf("unable to close PolicyMap which was not able to be dumped: %s", err)
```
Comment (raybejjani) [inline pkg/endpoint/endpoint.go]: In the cases where we see an error from `DumpToSlice` isn't it also likely that we would see an error with `Close`? Would we ever get past this return to actually try to reopen the map?

File: pkg/endpoint/endpoint.go [hunk 7]
```diff
@@ -2422,8 +2426,24 @@ func (e *Endpoint) syncPolicyMap() error {
 
 	currentMapContents, err := e.PolicyMap.DumpToSlice()
```
Comment (raybejjani) [inline pkg/endpoint/endpoint.go:2423]: Would it be possible to move some of this dump/close/retry logic to a helper function? That would allow some context in the doc comment, and make it clear that all this logic is grouped together.

File: pkg/maps/policymap/policymap.go (hunk 5 above)
Comment (raybejjani) [reply pkg/maps/policymap/policymap.go]: oh, is the expectation that these maps are guarded by the endpoint lock?

**Review by raybejjani — CHANGES_REQUESTED** [review]

File: pkg/endpoint/endpoint.go (hunk 6 above)
Comment (ianvernon) [reply pkg/endpoint/endpoint.go]: This is something I was wondering myself. The problem I am having with trying to 'fix' this PR is that I have not been able to reproduce the issue locally, and need more data to fully determine the cause of the problem. Given that we can't access the map anyway in the cases where we get this 'bad file descriptor' error, I figure that if this does function in the way that you suspect, that we aren't in any worse shape than we are now, and can change the code accordingly. I'm hoping that additional logging can help provide insight into this as well :/

File: pkg/endpoint/bpf.go (hunk 2 above)
Comment (ianvernon) [reply pkg/endpoint/bpf.go]: Fat finger error, will fix.

File: pkg/maps/policymap/policymap.go (hunk 5 above)
Comment (ianvernon) [reply pkg/maps/policymap/policymap.go]: I would presume that this expects the endpoint lock to be held, although other BPF Maps have a mutex (in `pkg/bpf/map.go:Map`). Given that each policymap corresponds to an endpoint, I'd assume that the endpoint's lock is held during PolicyMap lifecycle-related operations.

My motivating concern here is that the FD could have been released / closed, but the operation failed due to other reasons, meaning that the userspace code would reference an invalid FD.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

File: pkg/endpoint/bpf.go (hunk 1 above)
Comment (ianvernon) [reply pkg/endpoint/bpf.go]: Fixed.

File: pkg/endpoint/bpf.go (hunk 2 above)
Comment (ianvernon) [reply pkg/endpoint/bpf.go]: Fixed.

File: pkg/endpoint/endpoint.go (hunk 3 above)
Comment (ianvernon) [reply pkg/endpoint/endpoint.go]: Agreed, removed.

**Review by raybejjani — APPROVED** [review]

File: pkg/endpoint/endpoint.go (hunk 6 above)
Comment (tgraf) [reply pkg/endpoint/endpoint.go]: I understand, the goal is to improve the probability of recovery and reliability. Not doing anything is the worst decision we can make here.

@raybejjani is correct that the Close() will likely fail as well. We should log an error that includes the value of the fd and then continue to re-open. If the map is really still open, close will not fail unless the fd is invalid. If the fd is invalid but not released there is nothing we can do except exiting the agent eventually. The best way to see if need to do that eventually is to log an error but continue.

File: pkg/maps/policymap/policymap.go (hunk 5 above)
Comment (tgraf) [reply pkg/maps/policymap/policymap.go]: If you set it to 0, i would also check for 0 before you close. Let's just add a mutex here to protect this. Doesn't hurt and makes it 100% reliable.

**Review by tgraf — CHANGES_REQUESTED** [review]

File: pkg/maps/policymap/policymap.go (hunk 5 above)
Comment (ianvernon) [reply pkg/maps/policymap/policymap.go]: ObjClose already does that:
```
// ObjClose closes the map's fd.
func ObjClose(fd int) error {
	if fd > 0 {
		return unix.Close(fd)
	}
	return nil
}
```

I'll add a mutex.

File: pkg/endpoint/endpoint.go (hunk 6 above)
Comment (ianvernon) [reply pkg/endpoint/endpoint.go]: Fixed in latest upload. `PolicyMap.Close()` will log the file descriptor for the map being closed, and now an error is logged instead of returning one.

**Comment by ianvernon** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

File: pkg/endpoint/endpoint.go [hunk 8]
```diff
@@ -2422,8 +2422,29 @@ func (e *Endpoint) syncPolicyMap() error {
...
 	if err != nil {
-		return fmt.Errorf("unable to dump PolicyMap for endpoint: %s", err)
+		e.getLogger().WithError(err).Error("unable to dump PolicyMap when trying to sync desired and realized PolicyMap state")
+
+		// Close to avoid leaking of file descriptors, but still continue in case
+		// Close() does not succeed, because otherwise the map will never be
+		// opened again unless the agent is restarted.
+		err := e.PolicyMap.Close()
+		if err != nil {
+			e.getLogger().WithError(err).Error("unable to close PolicyMap which was not able to be dumped")
```
Comment (joestringer) [inline pkg/endpoint/endpoint.go:2435]: We probably could drop this to `Info`, since the close(2) manuals state that "a failure return should be used only for diagnostic purposes (i.e., a warning to the application that there may still be I/O pending or there may have been failed I/O) or remedial purposes (e.g.,  writing  the  file  once more or creating a backup).". That said, I don't really expect us to hit this warning now that this PR is setting the FD to 0 so it's no biggie.

File: pkg/maps/policymap/policymap.go [hunk 9]
```diff
@@ -44,9 +49,12 @@ const (
...
 )
 
+var log = logging.DefaultLogger
+
 type PolicyMap struct {
-	path string
-	Fd   int
+	path  string
+	Fd    int
+	mutex lock.Mutex
```
Comment (joestringer) [inline pkg/maps/policymap/policymap.go:57]: As a general style thing, are we deliberately avoiding the following style?

```
type PolicyMap struct {
    lock.Mutex
    ...
}
```

I kinda like the form of `policymap.Lock()`.

(Just starting a discussion, don't bother addressing this in this PR - we can follow up separately)

File: pkg/maps/policymap/policymap.go (hunk 5 above)
Comment (joestringer) [reply pkg/maps/policymap/policymap.go]: I think that we should unconditionally zero it.

From close(2) manual pages:

```
   Dealing with error returns from close()
       A careful programmer will check the return value of close(), since it is quite possible that errors on a previous write(2) operation are reported only on the final close() that releases the open file description.  Failing to check the return
       value when closing a file may lead to silent loss of data.  This can especially be observed with NFS and with disk quota.

       Note, however, that a failure return should be used only for diagnostic purposes (i.e., a warning to the application that there may still be I/O pending or there may have been failed I/O) or remedial purposes (e.g.,  writing  the  file  once
       more or creating a backup).

       Retrying  the  close() after a failure return is the wrong thing to do, since this may cause a reused file descriptor from another thread to be closed.  This can occur because the Linux kernel always releases the file descriptor early in the
       close operation, freeing it for reuse; the steps that may return an error, such as flushing data to the filesystem or device, occur only later in the close operation.

       Many other implementations similarly always close the file descriptor (except in the case of EBADF, meaning that the file descriptor was invalid) even if they subsequently report an error on return from close().  POSIX.1 is currently  silent
       on this point, but there are plans to mandate this behavior in the next major release of the standard

       A careful programmer who wants to know about I/O errors may precede close() with a call to fsync(2).

       The EINTR error is a somewhat special case.  Regarding the EINTR error, POSIX.1-2013 says:

              If close() is interrupted by a signal that is to be caught, it shall return -1 with errno set to EINTR and the state of fildes is unspecified.

       This  permits  the behavior that occurs on Linux and many other implementations, where, as with other errors that may be reported by close(), the file descriptor is guaranteed to be closed.  However, it also permits another possibility: that
       the implementation returns an EINTR error and keeps the file descriptor open.  (According to its documentation, HP-UX's close() does this.)  The caller must then once more use close() to close the file descriptor, to  avoid  file  descriptor
       leaks.   This  divergence  in  implementation  behaviors provides a difficult hurdle for portable applications, since on many implementations, close() must not be called again after an EINTR error, and on at least one, close() must be called
       again.  There are plans to address this conundrum for the next major release of the POSIX.1 standard.
```

I'm particularly looking at **"... on Linux and many other implementations, where, as with other errors that may be reported by close(), the file descriptor is guaranteed to be closed."**

We can document here that we're relying on this behaviour, but these maps themselves are relying on BPF support in the kernel so unless something changes significantly, we're guaranteed to run this logic on a Linux kernel where the fd will be properly closed (and therefore we can zero it).

Comment (joestringer) [reply pkg/maps/policymap/policymap.go]: ~~Also, we could consider logging this error at some level.~~

EDIT: I realise this responsibility is deferred to the caller.

**Comment by ianvernon** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
LGTM, thanks!

File: pkg/maps/policymap/policymap.go (hunk 9 above)
Comment (raybejjani) [reply pkg/maps/policymap/policymap.go:57]: While I sneak the embedded lock style into my PRs (no one ever says anything!), one reason to keep with the in-place style is that our code doesn't keep lock usage inside objects. We often (almost always?) lock an object outside its methods, and modify state. This leads to more public variables on these objects, and that means there is no easy way to distinguish between fields that will change and ones that won't (and so don't need the lock and can be exposed directly). In some cases we place the named `mutex lock.Mutex` above the fields it protects to make it more clear what the boundaries are. I don't think we're terribly consistent, though.
