### PR TITLE
iptables: Don't track tunneling traffic (v2)

### LINKED ISSUE #42121: CI: Conformance GKE - datapath-mode=tunnel|tunnel-ipsec connectivity test unable to start
## CI failure

On main we have a 100% failure rate on main under Conformance GKE for any tests with datapath-mode=tunnel|tunnel-ipsec. The failure presents itself in `Run connectivity test (*)` like so:
```
timeout reached waiting for lookup for localhost from pod cilium-test-1/client3-795488bf5-szgfg to server on pod cilium-test-1/echo-same-node-5f8bc55867-z5ccd to succeed (last error: command failed (pod=cilium-test-1/client3-795488bf5-szgfg, container=): context deadline exceeded)
```

Example of this failure: https://github.com/cilium/cilium/actions/runs/18410506117/job/52461351590

There are also plenty to pick from in https://github.com/cilium/cilium/actions/workflows/conformance-gke.yaml?query=branch%3Amain

Sysdump: [cilium-sysdumps-Installation and Connectivity Test (1.31, us-west3-a, 2, tunnel).zip](https://github.com/user-attachments/files/22853865/cilium-sysdumps-Installation.and.Connectivity.Test.1.31.us-west3-a.2.tunnel.zip)

### PR DESCRIPTION
**Pull request by bersoare**
Reintroduces https://github.com/cilium/cilium/pull/38782, which was reverted because it caused GKE tests to break due to pod to pod traffic being dropped when in tunnel mode. the goal of that change is to reduce pressure in handling conntrack states in the kernel for tunnel (node to node) packets.

the reason for it to make GKE tests fail is that for the GKE deployment, the OUTPUT chain in the filter table has its policy set to DROP. Cilium, currently does not install any rules that explicitly allow tunnel traffic in the outbound direction. however, tunnel traffic was still allowed in the GKE nodes because among other customizations in the iptables rules done by the provider we have an entry that accepts packets with NEW ctstate:

```
-A OUTPUT -m state --state NEW,RELATED,ESTABLISHED -j ACCEPT
```

when https://github.com/cilium/cilium/pull/38782 added a rule and we were no longer creating ctstates for tunnel packets, the rule above no longer matched such packets, which ended up getting dropped by the chain policy.

in this PR we bring back the original commit to not create conntrack entries for tunnel packets, and also add explicit rules to allow tunnel packets in the outbound direction.

Fixes: #42121

```release-note
Add iptables rule to allow tunnel traffic egressing the node when tunnel routing mode is used
```

### CODE REVIEW

**Comment by bersoare** [comment]
https://github.com/cilium/cilium/actions/runs/18882571627 < ci-gke passing

File: pkg/datapath/iptables/encryption.go [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+
+package iptables
+
+import (
+	"fmt"
+
+	"github.com/cilium/cilium/pkg/datapath/linux/linux_defaults"
+)
+
+// insertAcceptEncryptMark adds and accept rule to a `chain` on a `table` for traffic matching the encryption skb marks
```
Comment (jrife) [inline pkg/datapath/iptables/encryption.go]: nit: "adds and" -> "adds an"? same below.

File: pkg/datapath/iptables/iptables.go [hunk 2]
```diff
@@ -1833,41 +1833,32 @@ func (m *Manager) addCiliumAcceptEncryptionRules() error {
...
+				if m.sharedCfg.EnableWireguard {
+					if err := insertAcceptEncryptMark(m.ip4tables, chain.table, chain.name); err != nil {
+						return err
+					}
+				} else if m.sharedCfg.EnableIPSec {
+					if err := insertAcceptEncryptIpsec(m.ip4tables, chain.table, chain.name); err != nil {
+						return err
+					}
 				}
+
```
Comment (jrife) [inline pkg/datapath/iptables/iptables.go]: nit: remove the random line?

**Review by jrife — CHANGES_REQUESTED** [review]
Your second commit, "iptables: add ACCEPT rule for ipsec packets" also affects wireguard traffic, so let's mention that in the commit description.

Also, can you clarify whether or not the explicit ACCEPT rules are necessary without the notrack rules? Are the ACCEPT rules a consequence of adding the notrack rules or was there a problem before? Is this a problem in any other platforms other than GKE?

**Review by julianwiedmann — CHANGES_REQUESTED** [review]
Let's please land this as two PRs. The tunnel parts are an enhancement, the ipsec change is a bug fix.

**Comment by bersoare** [comment]
@julianwiedmann , here's the one for ipsec: https://github.com/cilium/cilium/pull/42475

**Comment by bersoare** [comment]
@jrife , this can happen on any node where the OUTPUT policy is drop and there is no rule present (outside of cilium) that accepts the packet.
the failures were not triggered since the the following entry seems to be added by gke (at least this is what i see in the sysdump):
```
[56356:36056560] -A OUTPUT -m state --state NEW,RELATED,ESTABLISHED -j ACCEPT
``` 

vxlan packets would then have a ctstate to be matched.
once we skipped state tracking on the commit that broke it, we no longer could match on the tunnel packets ctstate and they would have no match before the default rule (chain policy) gets hit.

hope it makes sense.

File: pkg/datapath/iptables/encryption.go (hunk 1 above)
Comment (bersoare) [reply pkg/datapath/iptables/encryption.go]: moved this to a different pr (https://github.com/cilium/cilium/pull/42475)

File: pkg/datapath/iptables/iptables.go (hunk 2 above)
Comment (bersoare) [reply pkg/datapath/iptables/iptables.go]: moved this to a different pr (https://github.com/cilium/cilium/pull/42475)

**Comment by julianwiedmann** [comment]
Could you please improve the PR description, so that it covers the entire proposed change? Something like "Re-introduce #38782, but also do ... to address ... as seen on GKE".

Also adding the original reviewers and author of https://github.com/cilium/cilium/pull/38782.

**Comment by julianwiedmann** [comment]
cc @BenoitKnecht

**Comment by julianwiedmann** [comment]
(adjusted the release-note label, since we already pick up the one from #38782)

**Comment by joestringer** [comment]
I can't tell from the PR description why the original PR was reverted and why the solution might be different this time. That would be super useful detail for reviewers to see.

When I see CI being constantly re-run, that gives me great concern that this PR is not reliable. We have a [failure triage process](https://docs.cilium.io/en/stable/contributing/testing/ci/#id1) to investigate failures and discover whether they are affecting the entire tree or introduced by this PR. Given the number of CI runs I see, and lack of comment describing what is going on, I will assume for now that the code is not reliable and work still needs to be done to ensure the tests pass with these changes.

**Comment by bersoare** [comment]
hi @joestringer ,
thanks for the feedback. ive gone through the PR description again and i believe the description is accurate and describes what we want to accomplish here. can i ask you to elaborate a bit more on what you would like to see there?

on the ci runs, ginkgo was indeed failing quite a lot for most builds (https://github.com/cilium/cilium/actions/workflows/conformance-ginkgo.yaml?query=branch%3Amain) and it was a known issue from what i can tell.
the ci-multi-pool trigger i don't recall which failure it was and did a single retry. next time i will make sure i stop and gather more information about the cause, but im positive it wouldn't be caused by the changes in this PR.

 and there were no re tries after the rebase and push submitted yesterday. 
let me know if you still have any concerns, and if that's the case, how they can be addressed.

thank you.

**Comment by joestringer** [comment]
> can i ask you to elaborate a bit more on what you would like to see there?

Sure thing. I see that this "reintroduces" https://github.com/cilium/cilium/pull/38782 . From that I infer that the original PR was introduced then reverted because of reason "X". I'm not familiar with why that was and I couldn't find it when I looked at that PR. Presumably when this PR reintroduces the change, it solves the problem "X" by approaching the problem differently from the previous proposal.

Maybe I'm parsing the description wrong, but I interpreted it to be doing two things:
* Reintroduce https://github.com/cilium/cilium/pull/38782 (no explanation why that was reverted before, what's different from last time we introduced the change, why we won't need to revert this PR also)
* Add explicit ACCEPT to handle some GKE case

To convey this information, it can help to structure the description something like this:

"Previously we introduced https://github.com/cilium/cilium/pull/38782 in order to fix ____. However, that PR broke ______, so we reverted it in PR ____. This PR reintroduces https://github.com/cilium/cilium/pull/38782 and addresses the problem from before by _____."
 
(Rest of the details about the ACCEPT rule case from the existing description follows)

---

> next time i will make sure i stop and gather more information about the cause, but im positive it wouldn't be caused by the changes in this PR.

Thanks, please do. I want to ensure we take every failure seriously and fix the underlying unreliability in the testsuite. It does us all a disservice if we train ourselves to ignore the test results we see. If the test results are not helpful, then the path forward for the entire community is to collaborate to make those test results more reliable, either by fixing the underlying functional bug in the production code or by improving the test cases to validate the intended functionality in a more reliable manner. I appreciate that for you it may be obvious that your changes do not introduce instability, but at the scale of the Cilium project we simply can't rely on contributors to self-evaluate these things. We need to simplify the CI to give accurate results. There have been too many cases in the past where people believe the PR does not impact test reliability, we merge it, and that then wastes a lot of time for other developers chasing down why the main branch is unstable.

**Comment by bersoare** [comment]
@joestringer thank you for the feedback! added more details to the PR description - hope it makes more sense now.

**Review by joestringer — APPROVED** [review]
Changes LGTM.

nit: It's also good to include the detailed description in the commit messages. If you peruse `git log main` you should see plenty of such examples. Cilium developers frequently refer to older changes in the tree by using `git blame` + `git log` + `git show`. In future if there is some problem with this change, it's useful for a developer to look at these commits and be able to answer "Why are these changes necessary?". Similar to the PR description, if the git commit logs explain that these rules are being added because certain cloud providers have a default deny on their iptables rules, and we want to avoid connection tracking in order to prevent unnecessary conntrack entry creation in environments with high traffic flow... that is golden context. Future developers (including yourself) will thank you for explaining why these changes were important, so we can retain those benefits when making further changes to this code.

I note the above because while we do have this context in GitHub, it's much harder to locate this PR than it is to use `git blame` or `git log -- <path>` (or equivalent IDE extensions) locally in order to locate the "why" context about this change.

File: pkg/datapath/iptables/iptables.go [hunk 3]
```diff
@@ -1887,6 +1891,37 @@ func (m *Manager) addCiliumNoTrackEncryptionRules() (err error) {
...
+	if m.sharedCfg.EnableIPv6 {
+		if err := m.ip6tables.runProg(cmd); err != nil {
+			return err
+		}
+	}
+
+	return nil
+}
+
```
Comment (julianwiedmann) [inline pkg/datapath/iptables/iptables.go:1924]: (For a future PR) - looking at this, it feels like we should integrate the logic that installs `NOTRACK` and `ACCEPT` better. Checking the identical conditions twice is bound to drift over time.

What I'd expect from the overall codeflow is that it **first** install the `ACCEPT` rules, and only then the **identical** `NOTRACK` rules. Driven from the same conditions, using the same rule templates etc.

File: pkg/datapath/iptables/iptables.go [hunk 4]
```diff
@@ -1835,6 +1891,37 @@ func (m *Manager) addCiliumNoTrackEncryptionRules() (err error) {
...
+	cmd := []string{
+		"-t", "filter",
+		"-A", ciliumOutputChain,
+		"-p", "udp",
+		"--dport", strconv.Itoa(int(port)),
+		"-m", "comment", "--comment", "cilium: ACCEPT for tunnel traffic",
+		"-j", "ACCEPT",
+	}
+
+	if m.sharedCfg.EnableIPv4 {
```
Comment (julianwiedmann) [inline pkg/datapath/iptables/iptables.go:1910]:
```suggestion
	if m.sharedCfg.EnableIPv4 && ip4tables != nil {
```

(Purely from what we do in the NOTRACK path)

File: pkg/datapath/iptables/iptables.go [hunk 5]
```diff
@@ -1835,6 +1891,37 @@ func (m *Manager) addCiliumNoTrackEncryptionRules() (err error) {
...
+		if err := m.ip4tables.runProg(cmd); err != nil {
+			return err
+		}
+	}
+
+	if m.sharedCfg.EnableIPv6 {
```
Comment (julianwiedmann) [inline pkg/datapath/iptables/iptables.go:1916]:
```suggestion
	if m.sharedCfg.EnableIPv6 && ip6tables != nil {
```

**Review by julianwiedmann — APPROVED** [review]
Looks good to me overall, thank you for bringing this functionality back!

Some comments inline, but I believe they can be addressed in a follow-up PR.

**Comment by julianwiedmann** [comment]
(I'll arm the PR for merging - please consider the review comments, and resolve them accordingly)

File: pkg/datapath/iptables/iptables.go (hunk 4 above)
Comment (bersoare) [reply pkg/datapath/iptables/iptables.go:1910]: ip4tables global doesn't exist anymore. maybe i forgot to adjust it

Comment (bersoare) [reply pkg/datapath/iptables/iptables.go:1910]: i dont know how the compiler isnt complaining, but ip4tables isnt set anywhere

Comment (bersoare) [reply pkg/datapath/iptables/iptables.go:1910]: oh right, those 2 are passed by the caller (https://github.com/cilium/cilium/pull/42356/files#diff-465a6b3f4ab9e1e94fe39e5aefe81c41eaa1dc99c66500161072e564029c2f51R641)

File: pkg/datapath/iptables/iptables.go (hunk 3 above)
Comment (bersoare) [reply pkg/datapath/iptables/iptables.go:1924]: follow up pr: https://github.com/cilium/cilium/pull/42660

**Comment by julianwiedmann** [comment]
@jrife there's a change request from your side, but I believe the relevant parts (the rules for encryption) have actually been dropped.

**Comment by bersoare** [comment]
@jrife ping 🙏🏽

**Review by jrife — APPROVED** [review]
