### PR TITLE
change log level for `lock failed: endpoint is in the process of being removed`

### LINKED ISSUE #16422: Error `lock failed: endpoint is in the process of being removed` should be debug
This error message should actually be debug or info in case of `endpoint is in the process of being removed`:
```
level=error msg="when trying to refresh endpoint labels" containerID=75a61a07be datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=2338 error="lock failed: endpoint is in the process of being removed" identity=35693 ipv4=10.0.0.154 ipv6="fd02::1e" k8sPodName=default/xwing-6f56868789-br4x5 subsys=endpoint
```

### PR DESCRIPTION
**Pull request by akshatagarwl**
Change the log level for `lock failed: endpoint is in the process of
being removed` from error to debug

Fixes: #16422 

---
Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Thanks for contributing!

### CODE REVIEW

File: pkg/endpoint/lock.go [hunk 1]
```diff
@@ -66,5 +66,5 @@ func (e *Endpoint) unconditionalRLock() {
 
 // logDisconnectedMutexAction gets the logger and logs given error with context
 func (e *Endpoint) logDisconnectedMutexAction(err error, context string) {
-	e.getLogger().WithError(err).Error(context)
+	e.getLogger().WithError(err).Debug(context)
```
Comment (jrajahalme) [inline pkg/endpoint/lock.go:69]: Given that this is only ever called after failing `rlockAlive()` and the only error condition therein is `ErrNotAlive = errors.New("rlock failed: endpoint is in the process of being removed")`, this is the right thing to do.

**Review by jrajahalme — APPROVED** [review]
