### PR TITLE
daemon: Remove old proxymaps on startup, use proxy with legacy fix

### LINKED ISSUE #8721: bpf: Delete legacy proxymaps on startup
`cilium-envoy` get's confused by the presence of the `cilium_proxy4` and `cilium_proxy6` left over after upgrade to Cilium 1.6. Make Cilium 1.6 to delete the proxymaps before `cilium-envoy` is launched.

### PR DESCRIPTION
**Pull request by jrajahalme**
Old proxymaps confuse cilium-envoy, which is compatible also with
earlier Cilium releases. Delete the old proxymaps on startup so that
cilium-envoy can operate normally with the current Cilium TPROXY use.

Use cilium-envoy with a fix for regression that broke support for
Cilium versions without TPROXY support (< 1.6).

Fixes: #6921
Fixes: #8721
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8703)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Seems like after upgrade the old proxymap is still available, but not updated by the datapath. Will need to get around this in the proxy, or make sure the proxymap is gone in cilium-agent.

**Comment by jrajahalme** [comment]
test-me-please

File: daemon/daemon.go [hunk 1]
```diff
@@ -385,6 +385,17 @@ func (d *Daemon) initMaps() error {
 		return nil
 	}
 
+	// Delete old proxymaps if left over from an upgrade.
+	// TODO: Remove this code when Cilium 1.6 is the oldest supported release
+	for _, name := range []string{"cilium_proxy4", "cilium_proxy6"} {
+		path := bpf.MapPath(name)
+		if _, err := os.Stat(path); err == nil {
+			if err = os.RemoveAll(path); err == nil {
```
Comment (joestringer) [inline daemon/daemon.go:393]: Does this have any impact on upgrading then deciding to downgrade? Or same as any L7 impact (process is restarted so connections are reset)?

**Review by joestringer — APPROVED** [review]

File: daemon/daemon.go (hunk 1 above)
Comment (jrajahalme) [reply daemon/daemon.go:393]: Correct, no more impact than normal restart, as the L7 proxies are restarted with the cilium-agent.

**Review by aanm — APPROVED** [review]
