### PR TITLE
datapath: Fix ICMP ECHO tuple ports

### LINKED ISSUE #12625: nat: Some ICMP entries are not GC'd
While doing some testing with the latest Cilium I've noticed that after running `cilium bpf ct flush global` some ICMP NAT entries were not garbage collected:
```
ICMP IN 192.168.34.12:0 -> 192.168.34.11:38193 XLATE_DST 192.168.34.11:38193 Created=6292sec HostLocal=1
ICMP OUT 192.168.34.11:38193 -> 192.168.34.12:0 XLATE_SRC 192.168.34.11:38193 Created=6292sec HostLocal=1
```

Previously, there was the following CT entry which got removed upon flush:

```
ICMP OUT 192.168.34.11:0 -> 192.168.34.12:38193 expires=16783063 RxPackets=0 RxBytes=0 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=1 TxBytes=50 TxFlagsSeen=0x00 LastTxReport=16783005 Flags=0x0000 [ ] RevNAT=0 SourceSecurityID=0 IfIndex=0
```

### PR DESCRIPTION
**Pull request by brb**
Previously, when an ICMP EchoRequest was sent from one node A to another node B with `Echo ID > NAT_MIN_EGRESS`, the ICMP EchoReply sent from `B -> A` created a CT entry and NAT entries which could not be related by GC. E.g. node A (`192.168.34.12`) pings node B (`192.168.34.11`):

        ICMP IN 192.168.34.12:0 -> 192.168.34.11:38193 XLATE_DST
        192.168.34.11:38193 Created=6292sec HostLocal=1
        ICMP OUT 192.168.34.11:38193 -> 192.168.34.12:0 XLATE_SRC
        192.168.34.11:38193 Created=6292sec HostLocal=1

        ICMP OUT 192.168.34.11:0 -> 192.168.34.12:38193 expires=16783063
        RxPackets=0 RxBytes=0 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=1
        TxBytes=50 TxFlagsSeen=0x00 LastTxReport=16783005 Flags=0x0000 [ ]
        RevNAT=0 SourceSecurityID=0 IfIndex=0

This made the NAT entries to escape the CT GC meaning that the CT entry was removed, while the NAT entries were kept which made them to stay forever until a user manually ran `cilium bpf nat flush`.

Fix this by setting ICMP Echo ID in a port which belongs to addr of the local node, so that the CT GC could relate the NAT entries. In the previous example, the CT entry after the fix is the following:

        ICMP OUT 192.168.34.11:38193 -> 192.168.34.12:0 expires=16783063
        RxPackets=0 RxBytes=0 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=1
        TxBytes=50 TxFlagsSeen=0x00 LastTxReport=16783005 Flags=0x0000 [ ]
        RevNAT=0 SourceSecurityID=0 IfIndex=0

The fix does not change the ID placement in a port for the case when B -> A sends ICMP EchoRequest.

Fix #12625

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

File: pkg/maps/ctmap/ctmap_privileged_test.go [hunk 1]
```diff
@@ -93,3 +94,120 @@ func (k *CTMapTestSuite) Benchmark_MapUpdate(c *C) {
...
+	c.Assert(err, IsNil)
+	natKey = &nat.NatKey4{
+		tuple.TupleKey4Global{
+			tuple.TupleKey4{
+				SourceAddr: types.IPv4{192, 168, 34, 12},
+				DestAddr:   types.IPv4{192, 168, 34, 11},
+				SourcePort: 0,
+				DestPort:   0x3195,
+				NextHeader: u8proto.ICMP,
+				Flags:      1,
```
Comment (borkmann) [inline pkg/maps/ctmap/ctmap_privileged_test.go:176]: flags.TUPLE_F_IN ?

**Review by borkmann — APPROVED** [review]

**Comment by brb** [comment]
test-gke

File: pkg/maps/ctmap/ctmap_privileged_test.go (hunk 1 above)
Comment (brb) [reply pkg/maps/ctmap/ctmap_privileged_test.go:176]: Will do it in a follow-up PR (removal of orphan NAT entries).
