### PR TITLE
ipmasq: fix race causing potential concurrent map read/write.

### LINKED ISSUE #40855: CI: [ci-integration] github.com/cilium/cilium/pkg/ipmasq: fatal error: concurrent map writes
## CI failure

- Set title to be in the format `CI: <test-name>`.

```
fatal error: concurrent map writes

goroutine 46 [running]:
internal/runtime/maps.fatal({0x2f2c73?, 0x22ae40?})
	/opt/hostedtoolcache/go/1.24.5/arm64/src/runtime/panic.go:1058 +0x20
github.com/cilium/cilium/pkg/ipmasq.(*IPMasqAgent).Update(0x400025c120)
	/home/runner/work/cilium/cilium/pkg/ipmasq/ipmasq.go:202 +0x45c
github.com/cilium/cilium/pkg/ipmasq.(*IPMasqAgent).Start.func1()
	/home/runner/work/cilium/cilium/pkg/ipmasq/ipmasq.go:152 +0x2bc
created by github.com/cilium/cilium/pkg/ipmasq.(*IPMasqAgent).Start in goroutine 44
	/home/runner/work/cilium/cilium/pkg/ipmasq/ipmasq.go:140 +0x3d8

goroutine 1 [chan receive]:
testing.(*T).Run(0x4000003c00, {0x2f4ac1?, 0x40001a3b38?}, 0x3072c0)
	/opt/hostedtoolcache/go/1.24.5/arm64/src/testing/testing.go:1859 +0x388
testing.runTests.func1(0x4000003c00)
	/opt/hostedtoolcache/go/1.24.5/arm64/src/testing/testing.go:2279 +0x40
testing.tRunner(0x4000003c00, 0x40001a3c68)
	/opt/hostedtoolcache/go/1.24.5/arm64/src/testing/testing.go:1792 +0xe4
testing.runTests(0x400000c198, {0x550360, 0x8, 0x8}, {0x4000068ee0?, 0x7?, 0x558040?})
	/opt/hostedtoolcache/go/1.24.5/arm64/src/testing/testing.go:2277 +0x3ec
testing.(*M).Run(0x400007fa40)
	/opt/hostedtoolcache/go/1.24.5/arm64/src/testing/testing.go:2142 +0x588
main.main()
	_testmain.go:69 +0x90

goroutine 44 [runnable]:
github.com/cilium/cilium/pkg/ipmasq.(*IPMasqAgent).Update(0x400025c120)
	/home/runner/work/cilium/cilium/pkg/ipmasq/ipmasq.go:206 +0x4f4
github.com/cilium/cilium/pkg/ipmasq.TestNonMasqCIDRsFromConfig(0x40001616c0)
	/home/runner/work/cilium/cilium/pkg/ipmasq/ipmasq_test.go:580 +0x2ec
testing.tRunner(0x40001616c0, 0x3072c0)
	/opt/hostedtoolcache/go/1.24.5/arm64/src/testing/testing.go:1792 +0xe4
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.24.5/arm64/src/testing/testing.go:1851 +0x374

goroutine 45 [select]:
github.com/fsnotify/fsnotify.(*shared).sendEvent(...)
	/home/runner/work/cilium/cilium/vendor/github.com/fsnotify/fsnotify/shared.go:25
github.com/fsnotify/fsnotify.(*inotify).readEvents(0x4000132c80)
	/home/runner/work/cilium/cilium/vendor/github.com/fsnotify/fsnotify/backend_inotify.go:396 +0x680
created by github.com/fsnotify/fsnotify.newBackend in goroutine 44
	/home/runner/work/cilium/cilium/vendor/github.com/fsnotify/fsnotify/backend_inotify.go:155 +0x1e8

```

Link: https://github.com/cilium/cilium/actions/runs/16639732210/job/47087690119

### PR DESCRIPTION
**Pull request by tommyp1ckles**
Fixes: https://github.com/cilium/cilium/issues/40855

### CODE REVIEW

File: pkg/ipmasq/ipmasq.go [hunk 1]
```diff
@@ -86,6 +87,8 @@ type IPMasqMap interface {
 
 // IPMasqAgent represents a state of the ip-masq-agent
 type IPMasqAgent struct {
+	lock.Mutex
```
Comment (bimmlerd) [inline pkg/ipmasq/ipmasq.go]: nit: this exposes the lock to the outside, let's hide it so that `Lock` isn't public

**Review by bimmlerd — APPROVED** [review]
nit, but LGTM

File: pkg/ipmasq/ipmasq.go (hunk 1 above)
Comment (tommyp1ckles) [reply pkg/ipmasq/ipmasq.go]: ah yeah good point

Comment (tommyp1ckles) [reply pkg/ipmasq/ipmasq.go]: fixed
