### PR TITLE
loader: Fix tunneling when device is set without NodePort

### LINKED ISSUE #11972: Setting devices without NodePort breaks multi-node connectivity
Setting `--device` with the private iface seems to break multi-node connectivity in multiple scenarios. For example, commit 7dc74091e8b79b606268539754a31f41e5e3f96e implements that change in CI and https://jenkins.cilium.io/job/Cilium-PR-K8s-newest-kernel-4.9/654/testReport/ has the corresponding results. The following tests are failing:
```
Suite-k8s-1.18.K8sPolicyTest Basic Test Allows traffic with k8s default-allow egress policy
Suite-k8s-1.18.K8sPolicyTest Basic Test Validate to-entities policies Validate toEntities All
Suite-k8s-1.18.K8sPolicyTest Basic Test Validate to-entities policies Validate toEntities World
Suite-k8s-1.18.K8sPolicyTest Basic Test Validate to-entities policies Validate toEntities Cluster
Suite-k8s-1.18.K8sPolicyTest Basic Test Traffic redirections to proxy Tests DNS proxy visibility without policy
Suite-k8s-1.18.K8sPolicyTest  Multi-node policy test validates fromEntities policies with remote-node  identity disabled Allows from all hosts with cnp fromEntities host  policy
Suite-k8s-1.18.K8sPolicyTest  Multi-node policy test validates fromEntities policies with remote-node  identity enabled Validates fromEntities remote-node policy
Suite-k8s-1.18.K8sIstioTest Istio Bookinfo Demo Tests bookinfo inter-service connectivity
Suite-k8s-1.18.K8sHealthTest checks cilium-health status between nodes
Suite-k8s-1.18.K8sFQDNTest Validate that multiple specs are working correctly
Suite-k8s-1.18.K8sConformance Portmap Chaining Check connectivity-check compliance with portmap chaining
Suite-k8s-1.18.K8sConformance Portmap Chaining Check one node connectivity-check compliance with portmap chaining
Suite-k8s-1.18.K8sDatapathConfig MonitorAggregation Checks that monitor aggregation restricts notifications
Suite-k8s-1.18.K8sDatapathConfig MonitorAggregation Checks that monitor aggregation flags send notifications
Suite-k8s-1.18.K8sDatapathConfig Encapsulation Check connectivity with sockops and VXLAN encapsulation
Suite-k8s-1.18.K8sDatapathConfig Encapsulation Check connectivity with VXLAN encapsulation
Suite-k8s-1.18.K8sDatapathConfig Encapsulation Check connectivity with Geneve encapsulation
Suite-k8s-1.18.K8sDatapathConfig AutoDirectNodeRoutes Check connectivity with automatic direct nodes routes
Suite-k8s-1.18.K8sDatapathConfig AutoDirectNodeRoutes Check direct connectivity with per endpoint routes
Suite-k8s-1.18.K8sDatapathConfig AutoDirectNodeRoutes Check connectivity with sockops and direct routing
Suite-k8s-1.18.K8sDatapathConfig  Transparent encryption DirectRouting Check connectivity with  transparent encryption and direct routing
Suite-k8s-1.18.K8sDatapathConfig IPv4Only Check connectivity with IPv6 disabled
Suite-k8s-1.18.K8sDatapathConfig Etcd Check connectivity
Suite-k8s-1.18.K8sHubbleTest Hubble Observe Test L3/L4 Flow with hubble-relay
Suite-k8s-1.18.K8sHubbleTest Hubble Observe Test L7 Flow with hubble-relay
Suite-k8s-1.18.K8sServicesTest Checks service across nodes Checks ClusterIP Connectivity
Suite-k8s-1.18.K8sServicesTest Checks service across nodes Tests NodePort (kube-proxy)
Suite-k8s-1.18.K8sServicesTest Checks service across nodes Tests NodePort (kube-proxy) with externalTrafficPolicy=Local
Suite-k8s-1.18.K8sServicesTest Checks service across nodes with L4 policy Tests NodePort with L4 Policy
Suite-k8s-1.18.K8sServicesTest Checks service across nodes with L7 policy Tests NodePort with L7 Policy
Suite-k8s-1.18.K8sKafkaPolicyTest Kafka Policy Tests KafkaPolicies
Suite-k8s-1.18.K8sChaosTest Connectivity demo application Endpoint can still connect while Cilium is not running
Suite-k8s-1.18.K8sDemosTest Tests Star Wars Demo
```
I am able to reproduce locally, although the connectivity checks work fine with `--device=enp0s3,enp0s8` in the multi-node dev. Vagrant setup.

I'm setting as `priority/release-blocker` because it is needed for the host firewall.

/cc @brb 

Related: #11969, #11799.

### PR DESCRIPTION
**Pull request by pchaigno**
Many tests are failing when configuring a device while BPF-based NodePort is disabled (cf. #11972). A bug in the loader causes it to call `init.sh` with the mode set to direct instead of e.g., vxlan. The `cilium_vxlan` is then not created (or even removed if it existed) which causes connectivity disruptions in multiple scenarios (mostly multi-node).

This commit fixes the wrong assumption that multiple devices are only set when NodePort is enabled. That assumption might have been correct when that code was introduced (in 3a83623).

Fixes: #11972
Fixes: 3a83623 ("bpf: add support for local NodePort via tunnel")
/cc @brb @borkmann

### CODE REVIEW

File: pkg/datapath/loader/base.go [hunk 1]
```diff
@@ -238,8 +238,7 @@ func (l *Loader) Reinitialize(ctx context.Context, o datapath.BaseProgramOwner,
 		}
 
 		args[initArgMode] = mode
-		if option.Config.EnableNodePort &&
-			strings.ToLower(option.Config.Tunnel) != "disabled" {
+		if strings.ToLower(option.Config.Tunnel) != "disabled" {
```
Comment (brb) [inline pkg/datapath/loader/base.go]: Nit (unrelated to your PR, but while we are here...)
```suggestion
		if option.Config.Tunnel != option.TunnelDisabled {
```

**Review by brb — APPROVED** [review]
Nice find, thanks!

File: pkg/datapath/loader/base.go (hunk 1 above)
Comment (pchaigno) [reply pkg/datapath/loader/base.go]: Fixed. I simplified the code a bit and got rid of the `mode` variable while at it.

**Comment by pchaigno** [comment]
test-me-please

File: pkg/datapath/loader/base.go [hunk 2]
```diff
@@ -231,17 +230,14 @@ func (l *Loader) Reinitialize(ctx context.Context, o datapath.BaseProgramOwner,
 			}
 		}
 
-		if option.Config.DatapathMode == datapathOption.DatapathModeIpvlan {
-			mode = "ipvlan"
+		if option.Config.Tunnel != option.TunnelDisabled {
```
Comment (brb) [inline pkg/datapath/loader/base.go:233]: Hmm, unrelated to your PR, but I'm wondering whether we could move it completely away outside the `if len(option.Config.Devices) != 0` to the line 223, get rid of the tunnel setting at 234, and also move away the flannel setting (the line 246) outside the if-block.

**Review by brb — APPROVED** [review]

File: pkg/datapath/loader/base.go (hunk 2 above)
Comment (pchaigno) [reply pkg/datapath/loader/base.go:233]: Yep, it looks like the `args[initArgMode]` assignments could be simplified a lot (also the `"routed"` assignment on line 253).
Since the tests started and this fix is required for two different `priority/release-blocker` PRs, maybe we can do that as a followup? I'll add a TODO to my list to not forget.

Comment (brb) [reply pkg/datapath/loader/base.go:233]: Sure, let's do it as a follow-up.

**Review by tgraf — APPROVED** [review]

**Review by borkmann — APPROVED** [review]
