### PR TITLE
Fix behavior where packets leave node if there are no backends

### LINKED ISSUE #21453: Packet will leave node if destination is a service without backends
I see this behavior in 1.11, but from the source code: 

https://github.com/cilium/cilium/blob/58e4081c3c2a6e052d7c5e3443be33dd6ae5024b/bpf/bpf_lxc.c#L1253-L1275 

It looks like the behavior is still the same where `DROP_NO_SERVICE` is returned for the cases either service is not found or backend is not found in here: https://github.com/cilium/cilium/blob/master/bpf/lib/lb.h#L1505 

I am wondering if this is the correct behavior. Should we drop the packet if we know it belongs to a service without backend, as opposed to allowing it to exit the node.

### PR DESCRIPTION
**Pull request by michaelasp**
This PR resolves an issue where an outgoing packet destined for a service will not be dropped if it does not have any backends. Currently we will not return the service if there are no backends for it, causing https://github.com/cilium/cilium/blob/58e4081c3c2a6e052d7c5e3443be33dd6ae5024b/bpf/bpf_lxc.c#L1254-L1266

To never be run, meaning we will never drop a packet in this case and instead simply route it through the kernels default routes.

Let me know if there is anything I am missing here, I think this is the behavior of kube-proxy and other CNI's. 

Fixes: #21453

Signed-off-by: Michael Aspinwall <maspinwall@google.com>

### CODE REVIEW

**Comment by julianwiedmann** [comment]
Hi @michaelasp, thank you for the fix! Agree that dropping (`DROP_NO_SERVICE`) such a packet would be the expected behaviour.
But walking down the code a bit further, I'm surprised that this change is sufficient - don't we need to catch the `svc->count == 0` case in `lb4_local()` now?

For the record, I think there's three paths to consider:

- `bpf_lxc.c` (from-container)
- `nodeport_lb4()` / `nodeport_lb6()`, from-external)
- `bpf_sock.c` (socket LB)


Have you looked into adding a test for this issue?

**Comment by michaelasp** [comment]
Hey @julianwiedmann! I was testing this locally and it seemed like it was enough to change the behavior in tcpdump when I created a service. When I had a service before I would see stray packets when I tried to [ing it from a pod even when it had no backends, afterwards it was correctly dropping the packets, meaning it never even showed up in tcpdump. I'll add some tests for this and look into this more. Thanks for the quick response!

I think the reasoning behind this is that if `lb4_local()` sees `svc->count == 0` it returns an error, dropping the packet in the process while `lb4_lookup_service()` simply returns NULL, allowing us to keep going on in the code rather than returning an error.

**Comment by julianwiedmann** [comment]
> I think the reasoning behind this is that if `lb4_local()` sees `svc->count == 0` it returns an error, dropping the packet in the process while `lb4_lookup_service()` simply returns NULL, allowing us to keep going on in the code rather than returning an error.

:100:, and this certainly feels like the right way to fix it!

My concern is whether **all** paths in `lb4_local()` can suddenly deal with a `svc->count` of 0, or whether it's better to fence this right at the beginning. The semantics here for instance are not exactly trivial:

https://github.com/cilium/cilium/blob/61d7ff0083f40cc620990d96e1bf50c3e074d5c1/bpf/lib/lb.h#L1541-L1544

https://github.com/cilium/cilium/blob/61d7ff0083f40cc620990d96e1bf50c3e074d5c1/bpf/lib/lb.h#L1278-L1287

**Comment by julianwiedmann** [comment]
`bpf_sock.c` definitely needs a closer look, I'll do that tomorrow.

Re: testing - looks like https://github.com/cilium/cilium/blob/master/bpf/tests/xdp_nodeport_lb4_test.c could be adapted to cover the N/S case. And maybe https://github.com/cilium/cilium/blob/master/bpf/tests/hairpin_flow.c for the E/W path with `ENABLE_PER_PACKET_LB`?

**Comment by michaelasp** [comment]
I agree with that, I've only been testing the datapath for containers and while that seems to work, it may not be applicable for all other ways we handle services in cilium. This would definitely benefit from having a guard, even from a readability standpoint. Thanks for the pointers, this is my first time working with the cilium datapath code so I appreciate it :)

**Comment by aditighag** [comment]
@michaelasp I had sent a fix for a somewhat similar issue - https://github.com/cilium/cilium/pull/20637. Does it work for you? /cc @julianwiedmann

**Comment by michaelasp** [comment]
Makes sense, I'll do something similar. I just want to make sure that by modifying `lb4_local()\lb6_local()`  doesn't affect any other points in the datapath. Should I wait for your change to be merged then use the same error code?

**Comment by julianwiedmann** [comment]
FYI, I hacked some tests for the per-packet path together here: https://github.com/julianwiedmann/cilium/tree/lb-no-backends

**Comment by julianwiedmann** [comment]
> Makes sense, I'll do something similar. I just want to make sure that by modifying `lb4_lookup_service()` \ `lb6_lookup_service` doesn't affect any other points in the datapath. Should I wait for your change to be merged then use the same error code @aditighag ?

Hi @michaelasp , my suggestion would be the following:
1. ignore `bpf_sock.c` for now. Imho the desired behaviour is much less clear there, and its use of `lb?_lookup_service()` is not exactly straight-forward (with the fallback to wildcard lookup). So let's tackle that separately.
2. to preserve existing behaviour, push all the lookup logic into new `__lb?_lookup_service()` variants, and do the checks (`svc->count`, L7-LB etc) in `lb?_lookup_service()`.
3. then use the `__lb?_lookup_service()` variants in the per-packet paths (`bpf_lxc.c`, `nodeport.h`), manually check the returned `svc->count`, and drop with `DROP_NO_SERVICE`. We automatically get metrics for that from `send_drop_notify()`.
4. once we are confident that `lb?_local()` can actually handle `svc->count == 0` in all its paths, we can refactor at a later time.

**Comment by michaelasp** [comment]
Awesome, thanks @julianwiedmann ! I added the changes you recommended to the pull request, thanks for the help!

File: bpf/bpf_lxc.c [hunk 1]
```diff
@@ -678,8 +678,11 @@ static __always_inline int __tail_handle_ipv6(struct __ctx_buff *ctx)
 		 * the CT entry for destination endpoints where we can't encode the
 		 * state in the address.
 		 */
-		svc = lb6_lookup_service(&key, is_defined(ENABLE_NODEPORT));
+		svc = __lb6_lookup_service(&key, is_defined(ENABLE_NODEPORT));
 		if (svc) {
+			if (svc->count==0) 
+				return DROP_NO_SERVICE;
```
Comment (julianwiedmann) [inline bpf/bpf_lxc.c]: This check needs to move down a bit, right in front of the `lb6_local()` call. Otherwise it interferes with L7 LB (which have no backend).

File: bpf/bpf_lxc.c [hunk 2]
```diff
@@ -1250,8 +1253,11 @@ static __always_inline int __tail_handle_ipv4(struct __ctx_buff *ctx)
 				return ret;
 		}
 
-		svc = lb4_lookup_service(&key, is_defined(ENABLE_NODEPORT));
+		svc = __lb4_lookup_service(&key, is_defined(ENABLE_NODEPORT));
 		if (svc) {
+			if (svc->count==0) 
+				return DROP_NO_SERVICE;
```
Comment (julianwiedmann) [inline bpf/bpf_lxc.c]: same here, move after the L7 case.

File: bpf/lib/lb.h [hunk 3]
```diff
@@ -575,16 +575,29 @@ struct lb6_service *lb6_lookup_service(struct lb6_key *key,
 	if (svc) {
 		if (!scope_switch || !lb6_svc_is_local_scope(svc))
 			/* Packets for L7 LB are redirected even when there are no backends. */
```
Comment (julianwiedmann) [inline bpf/lib/lb.h:577]: remove the stale comment?

File: bpf/lib/lb.h [hunk 4]
```diff
@@ -1210,7 +1223,7 @@ lb4_to_lb6_service(const struct lb4_service *svc __maybe_unused)
 }
 
 static __always_inline
-struct lb4_service *lb4_lookup_service(struct lb4_key *key,
+struct lb4_service *__lb4_lookup_service(struct lb4_key *key,
```
Comment (julianwiedmann) [inline bpf/lib/lb.h]: still need to remove the checks for `svc->count` etc from this variant

File: bpf/lib/nodeport.h [hunk 5]
```diff
@@ -736,10 +736,11 @@ static __always_inline int nodeport_lb6(struct __ctx_buff *ctx,
 			return ret;
 	}
 
-	svc = lb6_lookup_service(&key, false);
+	svc = __lb6_lookup_service(&key, false);
 	if (svc) {
 		const bool skip_l3_xlate = DSR_ENCAP_MODE == DSR_ENCAP_IPIP;
-
+		if (svc->count == 0) 
+			return DROP_NO_SERVICE;
```
Comment (julianwiedmann) [inline bpf/lib/nodeport.h]: Move this check after the `ENABLE_L7_LB` part.

File: bpf/lib/nodeport.h [hunk 6]
```diff
@@ -1628,10 +1629,11 @@ static __always_inline int nodeport_lb4(struct __ctx_buff *ctx,
 			return ret;
 	}
 
-	svc = lb4_lookup_service(&key, false);
+	svc = __lb4_lookup_service(&key, false);
 	if (svc) {
 		const bool skip_l3_xlate = DSR_ENCAP_MODE == DSR_ENCAP_IPIP;
-
+		if (svc->count == 0) 
+			return DROP_NO_SERVICE;
```
Comment (julianwiedmann) [inline bpf/lib/nodeport.h]: Move this check right before the `lb4_local()` call, to avoid interfering with L7 or NAT46 LBs (which both have no backends).

**Review by julianwiedmann — CHANGES_REQUESTED** [review]
Hi @michaelasp , thanks! Some fix-ups needed, and then I think we're good.

For the record, there's a rare call to `lb?_lookup_service()` inside `lb?_local()` too. There we don't need to convert to `__lb?_local()`, but can just continue to use the existing checks.

Feel free to pick up the two unit-tests from my branch as well. Otherwise I'll submit them afterwards.

File: bpf/bpf_lxc.c (hunk 2 above)
Comment (aditighag) [inline bpf/bpf_lxc.c]: The error code is confusing. Can we keep the error codes consistent with https://github.com/cilium/cilium/pull/20637? /cc @julianwiedmann

Comment (michaelasp) [reply bpf/bpf_lxc.c]: Until that PR is merged we won't have that error code, will defer this to @julianwiedmann to decide.

File: bpf/lib/nodeport.h (hunk 6 above)
Comment (michaelasp) [reply bpf/lib/nodeport.h]: Got it, does this look right?

File: bpf/lib/nodeport.h (hunk 5 above)
Comment (michaelasp) [reply bpf/lib/nodeport.h]: Done

File: bpf/lib/lb.h (hunk 4 above)
Comment (michaelasp) [reply bpf/lib/lb.h]: Oops, missed that, done!

File: bpf/lib/lb.h (hunk 3 above)
Comment (michaelasp) [reply bpf/lib/lb.h:577]: Done

File: bpf/bpf_lxc.c (hunk 2 above)
Comment (michaelasp) [reply bpf/bpf_lxc.c]: Done.

File: bpf/bpf_lxc.c (hunk 1 above)
Comment (michaelasp) [reply bpf/bpf_lxc.c]: Makes sense, done!

**Comment by michaelasp** [comment]
@julianwiedmann Cherry picked the bpf tests and resolved comments, ptal!

File: bpf/bpf_lxc.c [hunk 7]
```diff
@@ -678,14 +678,18 @@ static __always_inline int __tail_handle_ipv6(struct __ctx_buff *ctx)
 		 * the CT entry for destination endpoints where we can't encode the
 		 * state in the address.
 		 */
-		svc = lb6_lookup_service(&key, is_defined(ENABLE_NODEPORT));
+		svc = __lb6_lookup_service(&key, is_defined(ENABLE_NODEPORT));
 		if (svc) {
+			
+
```
Comment (julianwiedmann) [inline bpf/bpf_lxc.c]: Remove these extra empty lines.

File: bpf/lib/lb.h [hunk 8]
```diff
@@ -1220,18 +1232,29 @@ struct lb4_service *lb4_lookup_service(struct lb4_key *key,
...
 	}
 
 	return NULL;
 }
 
+static __always_inline
+struct lb4_service *lb4_lookup_service(struct lb4_key *key,
+				       const bool scope_switch)
+{
+	struct lb4_service *svc;
```
Comment (julianwiedmann) [inline bpf/lib/lb.h]: Add an empty line here.

File: bpf/lib/nodeport.h [hunk 9]
```diff
@@ -736,10 +736,10 @@ static __always_inline int nodeport_lb6(struct __ctx_buff *ctx,
 			return ret;
 	}
 
-	svc = lb6_lookup_service(&key, false);
+	svc = __lb6_lookup_service(&key, false);
 	if (svc) {
 		const bool skip_l3_xlate = DSR_ENCAP_MODE == DSR_ENCAP_IPIP;
-
+
```
Comment (julianwiedmann) [inline bpf/lib/nodeport.h]: Some unintended formatting change?

File: bpf/lib/nodeport.h [hunk 10]
```diff
@@ -1628,10 +1630,9 @@ static __always_inline int nodeport_lb4(struct __ctx_buff *ctx,
 			return ret;
 	}
 
-	svc = lb4_lookup_service(&key, false);
+	svc = __lb4_lookup_service(&key, false);
 	if (svc) {
 		const bool skip_l3_xlate = DSR_ENCAP_MODE == DSR_ENCAP_IPIP;
-
```
Comment (julianwiedmann) [inline bpf/lib/nodeport.h:1831]: Keep this empty line.

File: bpf/lib/nodeport.h [hunk 11]
```diff
@@ -1643,11 +1644,14 @@ static __always_inline int nodeport_lb4(struct __ctx_buff *ctx,
 								  (__be16)svc->l7_lb_proxy_port);
 		}
 #endif
+
```
Comment (julianwiedmann) [inline bpf/lib/nodeport.h]: Some unintended formatting change?

**Review by julianwiedmann — CHANGES_REQUESTED** [review]
Hi @michaelasp, thanks! Functionally looks good now, but please do fix up the formatting issues below.

File: bpf/bpf_lxc.c (hunk 2 above)
Comment (julianwiedmann) [reply bpf/bpf_lxc.c]: I don't think we can just re-use `REASON_LB_NO_ACTIVE_BACKEND_SLOT` (a metric) as valid DROP reason in the datapath. So we would need an additional `DROP_NO_SERVICE_BACKEND`.

I'm not opposed to that, but then we also need to adjust the existing cases of "no backend found" like eg. https://github.com/cilium/cilium/blob/4bafe1750f7b67fcab4b057c6e1aa9e8b9142584/bpf/lib/lb.h#L1612-L1619

to keep things consistent.

I think we can do that in a follow-on PR. But if you (@aditighag) feel strongly that this already needs to happen as part of this PR, then let's do so.

File: bpf/bpf_lxc.c (hunk 7 above)
Comment (michaelasp) [reply bpf/bpf_lxc.c]: Done

**Comment by julianwiedmann** [comment]
> Hi @michaelasp, thanks! Functionally looks good now, but please do fix up the formatting issues below.

Also see the output from the checkpatch test :o).

File: bpf/lib/lb.h (hunk 8 above)
Comment (michaelasp) [reply bpf/lib/lb.h]: Fixed

File: bpf/lib/nodeport.h (hunk 9 above)
Comment (michaelasp) [reply bpf/lib/nodeport.h]: Yep, fixed!

File: bpf/lib/nodeport.h (hunk 10 above)
Comment (michaelasp) [reply bpf/lib/nodeport.h:1831]: Done

File: bpf/lib/nodeport.h (hunk 11 above)
Comment (michaelasp) [reply bpf/lib/nodeport.h]: Done

**Comment by michaelasp** [comment]
Fixed formatting issues, let me know if everything looks good :)

**Comment by julianwiedmann** [comment]
> Fixed formatting issues, let me know if everything looks good :)

Some more checkpatch complaints, sorry :/.

https://github.com/cilium/cilium/actions/runs/3228467217/jobs/5284684449

**Comment by michaelasp** [comment]
Just saw those in the test failures and corrected them haha. Should be good now?

File: bpf/bpf_lxc.c (hunk 2 above)
Comment (aditighag) [reply bpf/bpf_lxc.c]: > So we would need an additional DROP_NO_SERVICE_BACKEND.

Yes, I am suggesting to add a new drop reason to indicate that a service has no backends. 

>I'm not opposed to that, but then we also need to adjust the existing cases of "no backend found" like eg.

Note that this is different from the backend not found reason (or in DROP_NO_SERVICE in the datapath). The code that you've highlighted is for the case when a service has backends, but the selected backend doesn't exist anymore. Both the cases are different. IMO, overloading the existing service drop code can confuse users.

That's why I propose adding a new drop error code in this PR itself, let's call it `DROP_NO_SERVICE_ACTIVE_BACKEND`. (Service backends can be non-active states such as quarantined, maintenance, etc [1]). This is quite straight forward, and we won't leave the users guessing. You'll need to extend this list with the same error code as the datapath - https://github.com/cilium/cilium/blob/master/pkg/monitor/api/drop.go#L17. 

[1] https://isovalent.com/blog/post/cilium-release-112/#quarantining

**Comment by anfernee** [comment]
/test-1.23-5.4

**Review by aditighag — CHANGES_REQUESTED** [review]
Forgot to request changes - https://github.com/cilium/cilium/pull/21539#discussion_r992834505

File: bpf/lib/lb.h [hunk 12]
```diff
@@ -574,17 +573,29 @@ struct lb6_service *lb6_lookup_service(struct lb6_key *key,
...
-		if (svc && (svc->count || lb6_svc_is_l7loadbalancer(svc)))
-			return svc;
+		return svc;
 	}
 
 	return NULL;
 }
 
+static __always_inline
+struct lb6_service *lb6_lookup_service(struct lb6_key *key,
```
Comment (aditighag) [inline bpf/lib/lb.h]: As mentioned on Slack, this is introducing technical debt by adding two variants of lb{4,6}_lookup_service helpers as we would have to update the same code at two different places going forward. Generally, when we have a function name prefixed by `__`, it implies that it's an internal function. But these changes are not following those semantics, most of the logic is duplicated, except one has service backend checks, while the other doesn't.
Can you add a note to the helpers highlighting what the difference is?

File: bpf/bpf_lxc.c (hunk 2 above)
Comment (julianwiedmann) [reply bpf/bpf_lxc.c]: > Note that this is different from the backend not found reason (or in DROP_NO_SERVICE in the datapath). The code that you've highlighted is for the case when a service has backends, but the selected backend doesn't exist anymore. Both the cases are different. IMO, overloading the existing service drop code can confuse users.

I expanded the scope of the quoted code section above a bit. Note how it eg. already reports a `!svc` as `DROP_NO_SERVICE`, which includes the `svc->count == 0` case.

FWIW I'm perfectly fine with adding more detailed drop reasons. But personally I think this is technical debt we can resolve separately.

**Comment by julianwiedmann** [comment]
> Just saw those in the test failures and corrected them haha. Should be good now?

Good from my perspective, thank you! Holding off on approving for now, as the verifier reject will presumably require additional changes :(.

File: bpf/lib/lb.h (hunk 12 above)
Comment (michaelasp) [reply bpf/lib/lb.h]: Done, thanks!

**Review by aditighag — CHANGES_REQUESTED** [review]
@michaelasp Instead of duplicating the current lookup helpers into one that checks for service backends and other doesn't, let's extend the helpers with a third parameter (`check_svc_backends`). Set the parameter to `false` for the bpf_lxc cases where the intention is to drop packets (make sure you keep the current L7 logic as-is). This way if you don't want to tackle socket-lb cases, the PR at least won't introduce new technical debt with almost similar named functions, and having duplicate code paths. As for introducing a new error code for the no backends case, it's okay if we keep things consistent with the rest of the code for now.

**Comment by michaelasp** [comment]
> @michaelasp Instead of duplicating the current lookup helpers into one that checks for service backends and other doesn't, let's extend the helpers with a third parameter (`check_svc_backends`). Set the parameter to `false` for the bpf_lxc cases where the intention is to drop packets (make sure you keep the current L7 logic as-is). This way if you don't want to tackle socket-lb cases, the PR at least won't introduce new technical debt with almost similar named functions, and having duplicate code paths. As for introducing a new error code for the no backends case, it's okay if we keep things consistent with the rest of the code for now.

Sounds good, this makes it a lot cleaner. I think our main concern was editing the codepath at all for lb{4,6}_lookup_service. I don't think this adds any behavior that's different from before as long as `check_svc_backends` is set to true. Let me know what you think @aditighag and @julianwiedmann! I tested this again locally and it seems like it passes the verifier.

**Comment by julianwiedmann** [comment]
@michaelasp note that the `net-next` CI run is calling out another complexity issue :/.

```
...
BPF program is too large. Processed 1000001 insn
processed 1000001 insns (limit 1000000) max_states_per_insn 32 total_states 69749 peak_states 2651 mark_read 70

libbpf: -- END LOG --
libbpf: failed to load program 'tail_handle_ipv4_from_netdev'
...
libbpf: failed to load object './test/bpf/../../bpf/bpf_host.o'
...
FAIL: Failed to load BPF program bpf_host with datapath configuration:
-DSKIP_DEBUG=1 -DENABLE_IPV4=1 -DENABLE_IPV6=1 -DENABLE_SOCKET_LB_TCP=1 -DENABLE_SOCKET_LB_UDP=1 -DENABLE_ROUTING=1 -DNO_REDIRECT=1 -DPOLICY_VERDICT_NOTIFY=1 -DALLOW_ICMP_FRAG_NEEDED=1 -DENABLE_IDENTITY_MARK=1 -DMONITOR_AGGREGATION=3 -DCT_REPORT_FLAGS=0x0002 -DENABLE_HOST_FIREWALL=1 -DENABLE_ICMP_RULE=1 -DENABLE_CUSTOM_CALLS=1 -DENABLE_SRV6=1 -DHAVE_LPM_TRIE_MAP_TYPE=1 -DHAVE_LRU_HASH_MAP_TYPE=1 -DENABLE_MASQUERADE=1 -DENABLE_SRC_RANGE_CHECK=1 -DENABLE_NODEPORT=1 -DENABLE_NODEPORT_ACCELERATION=1 -DENABLE_SESSION_AFFINITY=1 -DENABLE_DSR_ICMP_ERRORS=1 -DENABLE_DSR=1 -DENABLE_DSR_HYBRID=1 -DENABLE_IPV4_FRAGMENTS=1 -DENABLE_TPROXY=1 -DENABLE_HOST_ROUTING=1 -DENABLE_BANDWIDTH_MANAGER=1 -DETH_HLEN=0 -DENCAP_IFINDEX=1 -DTUNNEL_MODE=1 -DENABLE_EGRESS_GATEWAY=1 -DENABLE_VTEP=1 -DENABLE_SCTP=1 
Expected command: kubectl exec -n default test-verifier -- env TC_PROGS="" XDP_PROGS="" CG_PROGS="" TC_PROGS="bpf_host" ./test/bpf/verifier-test.sh
```

**Comment by michaelasp** [comment]
Sigh, guess with the extra conditional it's too large in net-next. Think I should switch back to the old method with separate helpers. It adds some tech debt but I think it'll pass the verifier. Or do you think there's a way to reduce the complexity keeping it in the same function?

**Comment by julianwiedmann** [comment]
> Sigh, guess with the extra conditional it's too large in net-next. Think I should switch back to the old method with separate helpers? It adds some tech debt but I think it'll pass the verifier. Or do you think there's a way to reduce the complexity keeping it in the same function?

Just to be sure, can you check locally if the previous version passes the verifier on `net-next`?

**Comment by michaelasp** [comment]
Yep will do, don't think the net-next version had issues iirc, just 4.19.

**Comment by aditighag** [comment]
> Sigh, guess with the extra conditional it's too large in net-next. Think I should switch back to the old method with separate helpers? It adds some tech debt but I think it'll pass the verifier. Or do you think there's a way to reduce the complexity keeping it in the same function?

Can you try wrapping the checks with the `unlikely` macro. We've had instances of it appeasing the verifier in the past. In any case, service backends count being `0` is likely to be uncommon scenario anyway.

**Comment by michaelasp** [comment]
@aditighag Unfortuantely, seems to still fail the verifier. Think I should switch it back? Or is there something else I can try to get under the complexity limit?

**Comment by michaelasp** [comment]
Actually on further investigation I found out that it seems like the goto in lb{4,6}_local was causing some grief, seems to pass the verifier now. Looks like we can keep the refactored lb{4,6}_lookup_service and still have the verifier pass net-next. Haven't checked on other kernels yet since the test takes a while but hopefully it passes on them too.

File: bpf/lib/lb.h [hunk 13]
```diff
@@ -851,7 +852,10 @@ static __always_inline int lb6_local(const void *map, struct __ctx_buff *ctx,
 
 	ipv6_addr_copy(&client_id.client_ip, &tuple->saddr);
 #endif
-
+	if (unlikely(svc->count == 0)) {
+		tuple->flags = flags;
+		return DROP_NO_SERVICE;
+	}
 	/* See lb4_local comments re svc endpoint lookup process */
 	ret = ct_lookup6(map, tuple, ctx, l4_off, CT_SERVICE, state, &monitor);
```
Comment (julianwiedmann) [inline bpf/lib/lb.h]: No need to restore `tuple->flags` here, as we didn't call `ct_lookup6()` yet:

```suggestion
	if (unlikely(svc->count == 0))
		return DROP_NO_SERVICE;

	/* See lb4_local comments re svc endpoint lookup process */
	ret = ct_lookup6(map, tuple, ctx, l4_off, CT_SERVICE, state, &monitor);
```

File: bpf/lib/lb.h [hunk 14]
```diff
@@ -1221,11 +1225,12 @@ struct lb4_service *lb4_lookup_service(struct lb4_key *key,
...
 			/* Packets for L7 LB are redirected even when there are no backends. */
-			return (svc->count || lb4_to_lb6_service(svc) ||
+			return (svc->count || !check_svc_backends || lb4_to_lb6_service(svc) ||
 				lb4_svc_is_l7loadbalancer(svc)) ? svc : NULL;
 		key->scope = LB_LOOKUP_SCOPE_INT;
 		svc = map_lookup_elem(&LB4_SERVICES_MAP_V2, key);
-		if (svc && (svc->count || lb4_svc_is_l7loadbalancer(svc)))
+
+		if (svc && (svc->count || !check_svc_backends || lb4_svc_is_l7loadbalancer(svc)))
 			return svc;
```
Comment (julianwiedmann) [inline bpf/lib/lb.h]: Stray newline?

```suggestion
		if (svc && (svc->count || !check_svc_backends || lb4_svc_is_l7loadbalancer(svc)))
			return svc;
```

File: bpf/lib/lb.h [hunk 15]
```diff
@@ -1523,6 +1528,10 @@ static __always_inline int lb4_local(const void *map, struct __ctx_buff *ctx,
 		.client_ip = saddr,
 	};
 #endif
+	if (unlikely(svc->count == 0)) {
+		tuple->flags = flags;
+		return DROP_NO_SERVICE;
+	}
 	ret = ct_lookup4(map, tuple, ctx, l4_off, CT_SERVICE, state, &monitor);
```
Comment (julianwiedmann) [inline bpf/lib/lb.h]: Same here:

```suggestion
#endif

	if (unlikely(svc->count == 0))
		return DROP_NO_SERVICE;

	ret = ct_lookup4(map, tuple, ctx, l4_off, CT_SERVICE, state, &monitor);
```

**Review by julianwiedmann — CHANGES_REQUESTED** [review]
The things we do to appease the verifier :slightly_smiling_face:. The remaining CI fails all look like known flakes now.

Just some minor cleanup comments from my side.

File: bpf/lib/lb.h (hunk 15 above)
Comment (michaelasp) [reply bpf/lib/lb.h]: Done

File: bpf/lib/lb.h (hunk 14 above)
Comment (michaelasp) [reply bpf/lib/lb.h]: Changed, thanks!

File: bpf/lib/lb.h (hunk 13 above)
Comment (michaelasp) [reply bpf/lib/lb.h]: Sounds good, wasn't sure so I just left it as it was in the goto.

**Comment by michaelasp** [comment]
Seems like the tests are running into failures, however I see the exact same thing here https://github.com/cilium/cilium/pull/21874 so don't think it's isolated to this change.

**Comment by jibi** [comment]
> Seems like the tests are running into failures, however I see the exact same thing here #21874 so don't think it's isolated to this change.

Could you rebase on top of master? That should help with some of the failing test

**Comment by michaelasp** [comment]
> > Seems like the tests are running into failures, however I see the exact same thing here #21874 so don't think it's isolated to this change.
> 
> Could you rebase on top of master? That should help with some of the failing test

Done!

**Comment by julianwiedmann** [comment]
/test-1.24-4.19

**Review by julianwiedmann — APPROVED** [review]
Code looks good, and confident that the CI fail is just known flakes. Thank you @michaelasp !

**Review by aditighag — APPROVED** [review]
Looks good! 👍

**Comment by nbusseneau** [comment]
Thanks for your contribution @michaelasp :)

**Comment by julianwiedmann** [comment]
Think we want this for `v1.12` as well. But there the verifier is acting up again (see https://github.com/cilium/cilium/pull/21943), so will backport manually.

**Comment by nbusseneau** [comment]
I think this PR might have introduced #21979 on `master`.

**Comment by nbusseneau** [comment]
For information: I am reverting this PR in #21981.

**Comment by joestringer** [comment]
@julianwiedmann FYI I have removed the needs-backport label since this has been reverted on the master branch. We should follow up on the resubmission of this PR and set the label on that PR if it is still applicable.

**Comment by julianwiedmann** [comment]
For the record, this is the minimal config to reproduce the complexity issue:

```
diff --git a/bpf/complexity-tests/419/bpf_host.txt b/bpf/complexity-tests/419/bpf_host.txt
index 71a8cba21b..ea03035231 100644
--- a/bpf/complexity-tests/419/bpf_host.txt
+++ b/bpf/complexity-tests/419/bpf_host.txt
@@ -1,3 +1,4 @@
 -DSKIP_DEBUG=1 -DENABLE_IPV4=1 -DENABLE_IPV6=1 -DENABLE_SOCKET_LB_TCP=1 -DENABLE_SOCKET_LB_UDP=1 -DENABLE_ROUTING=1 -DNO_REDIRECT=1 -DPOLICY_VERDICT_NOTIFY=1 -DALLOW_ICMP_FRAG_NEEDED=1 -DENABLE_IDENTITY_MARK=1 -DMONITOR_AGGREGATION=3 -DCT_REPORT_FLAGS=0x0002 -DENABLE_HOST_FIREWALL=1 -DENABLE_ICMP_RULE=1 -DENABLE_CUSTOM_CALLS=1 -DENABLE_SRV6=1 -DHAVE_LPM_TRIE_MAP_TYPE=1 -DHAVE_LRU_HASH_MAP_TYPE=1 -DENABLE_MASQUERADE=1 -DENABLE_SRC_RANGE_CHECK=1 -DENABLE_NODEPORT=1 -DENABLE_NODEPORT_ACCELERATION=1 -DENABLE_SESSION_AFFINITY=1 -DENABLE_DSR_ICMP_ERRORS=1 -DENABLE_DSR=1 -DENABLE_DSR_HYBRID=1 -DENABLE_IPV4_FRAGMENTS=1 -DENCAP_IFINDEX=1 -DTUNNEL_MODE=1
+-DSKIP_DEBUG=1 -DENABLE_IPV4=1 -DENABLE_IPV6=1 -DENABLE_SOCKET_LB_TCP=1 -DENABLE_SOCKET_LB_UDP=1 -DENABLE_ROUTING=1 -DNO_REDIRECT=1 -DPOLICY_VERDICT_NOTIFY=1 -DALLOW_ICMP_FRAG_NEEDED=1 -DENABLE_IDENTITY_MARK=1 -DMONITOR_AGGREGATION=3 -DCT_REPORT_FLAGS=0x00ff -DENABLE_HOST_FIREWALL=1 -DENABLE_ICMP_RULE=1 -DENABLE_CUSTOM_CALLS=1 -DENABLE_SRV6=1 -DHAVE_LPM_TRIE_MAP_TYPE=1 -DHAVE_LRU_HASH_MAP_TYPE=1 -DENABLE_MASQUERADE=1 -DENABLE_SRC_RANGE_CHECK=1 -DENABLE_NODEPORT=1 -DENABLE_NODEPORT_ACCELERATION=1 -DENABLE_SESSION_AFFINITY=1 -DENABLE_DSR_ICMP_ERRORS=1 -DENABLE_DSR=1 -DENABLE_DSR_HYBRID=1 -DENABLE_IPV4_FRAGMENTS=1 -DENCAP_IFINDEX=1 -DTUNNEL_MODE=1 -DDISABLE_LOOPBACK_LB=1
 -DSKIP_DEBUG=1 -DENABLE_IPV4=1 -DENABLE_SOCKET_LB_TCP=1 -DENABLE_SOCKET_LB_UDP=1 -DENABLE_ROUTING=1 -DNO_REDIRECT=1 -DPOLICY_VERDICT_NOTIFY=1 -DALLOW_ICMP_FRAG_NEEDED=1 -DENABLE_IDENTITY_MARK=1 -DMONITOR_AGGREGATION=3 -DCT_REPORT_FLAGS=0x0002 -DENABLE_HOST_FIREWALL=1 -DENABLE_ICMP_RULE=1 -DENABLE_CUSTOM_CALLS=1 -DENABLE_SRV6=1 -DHAVE_LPM_TRIE_MAP_TYPE=1 -DHAVE_LRU_HASH_MAP_TYPE=1 -DENABLE_MASQUERADE=1 -DENABLE_SRC_RANGE_CHECK=1 -DENABLE_NODEPORT=1 -DENABLE_NODEPORT_ACCELERATION=1 -DENABLE_SESSION_AFFINITY=1 -DENABLE_DSR_ICMP_ERRORS=1 -DENABLE_DSR=1 -DENABLE_DSR_HYBRID=1 -DENABLE_IPV4_FRAGMENTS=1 -DENCAP_IFINDEX=1 -DTUNNEL_MODE=1
 -DSKIP_DEBUG=1 -DENABLE_IPV6=1 -DENABLE_SOCKET_LB_TCP=1 -DENABLE_SOCKET_LB_UDP=1 -DENABLE_ROUTING=1 -DNO_REDIRECT=1 -DPOLICY_VERDICT_NOTIFY=1 -DALLOW_ICMP_FRAG_NEEDED=1 -DENABLE_IDENTITY_MARK=1 -DMONITOR_AGGREGATION=3 -DCT_REPORT_FLAGS=0x0002 -DENABLE_HOST_FIREWALL=1 -DENABLE_ICMP_RULE=1 -DENABLE_CUSTOM_CALLS=1 -DENABLE_SRV6=1 -DHAVE_LPM_TRIE_MAP_TYPE=1 -DHAVE_LRU_HASH_MAP_TYPE=1 -DENABLE_MASQUERADE=1 -DENABLE_SRC_RANGE_CHECK=1 -DENABLE_NODEPORT=1 -DENABLE_NODEPORT_ACCELERATION=1 -DENABLE_SESSION_AFFINITY=1 -DENABLE_DSR_ICMP_ERRORS=1 -DENABLE_DSR=1 -DENABLE_DSR_HYBRID=1 -DENABLE_IPV4_FRAGMENTS=1 -DENCAP_IFINDEX=1 -DTUNNEL_MODE=1
```

**Comment by julianwiedmann** [comment]
@michaelasp FYI - I freed up some complexity with PR https://github.com/cilium/cilium/pull/22342. Re-spin of this one is in https://github.com/cilium/cilium/pull/22388.

**Comment by michaelasp** [comment]
Awesome, thanks for the help with this @julianwiedmann! The bpf verifier is a finnicky thing 😢.
