### PR TITLE
hubble: Added nil check in filterByTCPFlags() to avoid segfault

### LINKED ISSUE #18830: Cilium segfaults when L7 visibility is enabled in conjuction with querying Hubble server using tcp-flag filter
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. Enable L7 visibility for a pod (add `io.cilium.proxy-visibility` annotation)
2. Enable Hubble and run hubble-observe with `tcp-flags` filter (`hubble obseve -f --tcp-flags syn`)
3. Send some HTTP traffic
4. `cilium-agent` which is responsible for providing the L7 visibility will crash due to segfault.

### Cilium Version

v1.11.1

### Kernel Version

N/A

### Kubernetes Version

N/A

### Sysdump

N/A

### Relevant log output

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x29 pc=0x1d145b5]

goroutine 21447 [running]:
github.com/cilium/cilium/pkg/hubble/filters.filterByTCPFlags.func1(0x0)
        /go/src/github.com/cilium/cilium/pkg/hubble/filters/tcp.go:27 +0x95
github.com/cilium/cilium/pkg/hubble/filters.FilterFuncs.MatchAll({0xc00221e510, 0x1, 0xc002d12702}, 0xc000c802a0)
        /go/src/github.com/cilium/cilium/pkg/hubble/filters/filters.go:29 +0x56
github.com/cilium/cilium/pkg/hubble/filters.BuildFilterList.func1(0xc001760618)
        /go/src/github.com/cilium/cilium/pkg/hubble/filters/filters.go:116 +0x2b
github.com/cilium/cilium/pkg/hubble/filters.FilterFuncs.MatchOne({0xc002c55b80, 0x2, 0xc002d127c0}, 0xc0028391d0)
        /go/src/github.com/cilium/cilium/pkg/hubble/filters/filters.go:44 +0x76
github.com/cilium/cilium/pkg/hubble/filters.Apply({0xc002c55b80, 0x2c52a70, 0xc002d127c0}, {0x4872150, 0x0, 0x0}, 0xc003255978)
        /go/src/github.com/cilium/cilium/pkg/hubble/filters/filters.go:23 +0x35
github.com/cilium/cilium/pkg/hubble/observer.(*eventsReader).Next(0xc000c80240, {0x2c52a70, 0xc002d127c0})
        /go/src/github.com/cilium/cilium/pkg/hubble/observer/local_observer.go:567 +0x19d
github.com/cilium/cilium/pkg/hubble/observer.(*LocalObserverServer).GetFlows(0xc000434280, 0xc00244c580, {0x2c85710, 0xc002c55b60})
        /go/src/github.com/cilium/cilium/pkg/hubble/observer/local_observer.go:273 +0x5f5
github.com/cilium/cilium/api/v1/observer._Observer_GetFlows_Handler({0x2671860, 0xc000434280}, {0x2c77810, 0xc0012b8e40})
        /go/src/github.com/cilium/cilium/api/v1/observer/observer_grpc.pb.go:207 +0xd0
google.golang.org/grpc.(*Server).processStreamingRPC(0xc0017e56c0, {0x2c96a90, 0xc00135d680}, 0xc00289e120, 0xc000cbfce0, 0x42e6ae0, 0x0)
        /go/src/github.com/cilium/cilium/vendor/google.golang.org/grpc/server.go:1540 +0xeba
google.golang.org/grpc.(*Server).handleStream(0xc0017e56c0, {0x2c96a90, 0xc00135d680}, 0xc00289e120, 0x0)
        /go/src/github.com/cilium/cilium/vendor/google.golang.org/grpc/server.go:1620 +0x9e5
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /go/src/github.com/cilium/cilium/vendor/google.golang.org/grpc/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /go/src/github.com/cilium/cilium/vendor/google.golang.org/grpc/server.go:919 +0x294
```

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by wazir-ahmed**
Cilium agent crashes when an L7/HTTP flow is passed to TCP flag flow
filter (`filterByTCPFlags`). This is because HTTP flows will have
some L4/TCP info such as src/dst port in the flow struct, but will not
contain TCP flags.

Added `nil` check for TCP flag pointer to avoid the segfault.

Fixes: #18830

Signed-off-by: Wazir Ahmed <wazir@accuknox.com>

### CODE REVIEW

File: pkg/hubble/filters/tcp.go [hunk 1]
```diff
@@ -13,7 +13,11 @@ import (
 
 func filterByTCPFlags(flags []*flowpb.TCPFlags) (FilterFunc, error) {
 	return func(ev *v1.Event) bool {
-		l4tcp := ev.GetFlow().GetL4().GetTCP()
+		flow := ev.GetFlow()
+		if flow == nil || flow.Type != flowpb.FlowType_L3_L4 {
```
Comment (gandro) [inline pkg/hubble/filters/tcp.go]: I have an alternative proposal: Instead of checking if this is an L3/L4 flow, let's just check if `l4tcp.GetFlags()` is nil. i.e. add an `if flowFlags == nil { return false }` here:

https://github.com/cilium/cilium/blob/76d34dbdfc1bf14cb8976a86ccf1e98dae6d72c5/pkg/hubble/filters/tcp.go#L20

Otherwise the bug might be re-introduced if we ever change the L3/L4 parser to not always populate the TCP flags.

**Review by gandro — CHANGES_REQUESTED** [review]
Thanks a lot, nice find!

File: pkg/hubble/filters/tcp.go (hunk 1 above)
Comment (wazir-ahmed) [reply pkg/hubble/filters/tcp.go]: Okay, I have changed the logic as suggested.

**Review by gandro — APPROVED** [review]
Thanks a ton!

**Comment by kaworu** [comment]
Thanks for the patch @wazir-ahmed, LGTM. Could we add a testcase for this bug in `tcp_test.go` please?

**Review by kaworu — CHANGES_REQUESTED** [review]
Let's get the fix in, we can add a unit test later.

**Review by kaworu — APPROVED** [review]
Oops, last comment was meant to approve :sweat_smile:

**Comment by kaworu** [comment]
@gandro filtering by TCP flags has been [introduced first in v1.10](https://github.com/cilium/cilium/commit/7b041c2132bd0869d18f8f135de02f69054c8dce), removed `needs-backport/1.9`.
