### PR TITLE
kvstore: Fix event watcher serialization

### LINKED ISSUE #14028: JSON based logging not applied everywhere
## Bug report

When running the `cilium-operator` with `--log-opt=format=json` CLI param I see JSON logs but interleaved some text logs:
```
{"level":"debug","msg":"Controller func execution time: 1.003627711s","name":"ipam-node-interval-refresh","subsys":"controller","uuid":"26d222cf-2605-11eb-9fee-124cf99b3437"}
{"instanceID":"i-0e658366a511b30d4","level":"debug","msg":"Refreshing node","name":"ip-10-0-35-70.ec2.internal","subsys":"ipam"}
{"instanceID":"i-0e658366a511b30d4","level":"debug","msg":"Updating node in apiserver","name":"ip-10-0-35-70.ec2.internal","poolSize":14,"subsys":"ipam"}
{"instanceID":"i-07c8bc1020981ea1d","level":"debug","msg":"Updating node in apiserver","name":"ip-10-0-37-108.ec2.internal","poolSize":14,"subsys":"ipam"}
{"instanceID":"i-07c8bc1020981ea1d","level":"warning","msg":"Instance not found! Please delete corresponding ciliumnode if instance has already been deleted.","name":"ip-10-0-37-108.ec2.internal","subsys":"ipam"}
{"instanceID":"i-07c8bc1020981ea1d","level":"warning","msg":"Instance not found! Please delete corresponding ciliumnode if instance has already been deleted.","name":"ip-10-0-37-108.ec2.internal","subsys":"ipam"}
Failed to obtain reader, failed to marshal fields to JSON, json: unsupported type: kvstore.EventChan
Failed to obtain reader, failed to marshal fields to JSON, json: unsupported type: kvstore.EventChan
{"eventType":2,"key":"cilium/state/nodes/v1/default/ip-10-0-37-108.ec2.internal","level":"debug","msg":"Received key update via kvstore [value ]","storeName":"store-cilium/state/nodes/v1","subsys":"shared-store"}
{"level":"debug","msg":"Controller func execution time: 2.545µs","name":"restart-unmanaged-kube-dns","subsys":"controller","uuid":"02d0905c-2605-11eb-9fee-124cf99b3437"}
Failed to obtain reader, failed to marshal fields to JSON, json: unsupported type: kvstore.EventChan
Failed to obtain reader, failed to marshal fields to JSON, json: unsupported type: kvstore.EventChan
```

**General Information**

- Cilium version (run `cilium version`)
`1.8.4`
- Kernel version (run `uname -a`)
`Linux ip-10-0-2-53.ec2.internal 4.15.0-2000-aws-fips #4-Ubuntu SMP Tue Jan 28 12:41:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"a9e59e859b0b7f535905a99afd434d7caeb0642c", GitTreeState:"clean", BuildDate:"2020-08-24T14:13:02Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"a9e59e859b0b7f535905a99afd434d7caeb0642c", GitTreeState:"clean", BuildDate:"2020-08-24T14:10:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Link to relevant artifacts (policies, deployments scripts, ...)
None
- Generate and upload a system zip:
None

**How to reproduce the issue**

1. Deploy `cilium-operator` version `1.8.4` and enable `--log-opt=format=json` with external `etcd` as the data store
2. Observe `STDOUT`

### PR DESCRIPTION
**Pull request by joestringer**
When using the watcher in log messages with JSON-based logging, logrus
would give up on trying to generate the log message and print this to
the logs instead:

    Failed to obtain reader, failed to marshal fields to JSON, json:
    unsupported type: kvstore.EventChan

Fix it by fixing the JSON serialization tags to the structure to avoid
serializing fields that don't make sense to be serialized, and to export
the fields that do make sense to be serialized.

Manually tested by applying this diff:

    diff --git a/pkg/kvstore/base_test.go b/pkg/kvstore/base_test.go
    index e9ee7da296bf..eb5a3548039b 100644
    --- a/pkg/kvstore/base_test.go
    +++ b/pkg/kvstore/base_test.go
    @@ -292,3 +292,10 @@ func (s *BaseTests) TestListAndWatch(c *C) {

            w.Stop()
     }
    +
    +func (s *BaseTests) TestFoo(c *C) {
    +       w := ListAndWatch(context.TODO(), "testWatcher2", "foo2/", 100)
    +       c.Assert(c, Not(IsNil))
    +
    +       log.WithField(fieldWatcher, w).Fatal("Stopped watcher")
    +}
    diff --git a/pkg/logging/logging.go b/pkg/logging/logging.go
    index 9989e8db0280..6a651c0c87f4 100644
    --- a/pkg/logging/logging.go
    +++ b/pkg/logging/logging.go
    @@ -50,7 +50,7 @@ const (

            // DefaultLogFormat is the string representation of the default logrus.Formatter
            // we want to use (possible values: text or json)
    -       DefaultLogFormat LogFormat = LogFormatText
    +       DefaultLogFormat LogFormat = LogFormatJSON
     )

     var (

Fixes: #14028

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Review by fristonio — APPROVED** [review]
LGTM :partying_face:

**Comment by nathanjsweet** [comment]
test-me-please

File: pkg/kvstore/events.go [hunk 1]
```diff
@@ -70,10 +70,10 @@ type stopChan chan struct{}
 // Watcher represents a KVstore watcher
 type Watcher struct {
 	// Events is the channel to which change notifications will be sent to
-	Events EventChan
+	Events EventChan `json:"-"`
 
-	name      string
-	prefix    string
+	Name      string `json:"name"`
```
Comment (aditighag) [inline pkg/kvstore/events.go:75]: What's the reasoning behind capitalizing these fields?

Comment (nathanjsweet) [reply pkg/kvstore/events.go:75]: Serialization packages in go (including json) don't work unless the member is public.

**Comment by aanm** [comment]
retest-gke

**Comment by joestringer** [comment]
retest-gke

**Comment by joestringer** [comment]
I don't see a way that the GKE build could fail while the others are all successful, so given the problems with running GKE CI runs right now I think it's reasonable to bypass that check and merge.

**Comment by errordeveloper** [comment]
retest-gke

**Comment by errordeveloper** [comment]
GKE Failed again, and it definitely looks unrelated.
```
===================== Exiting AfterFailed =====================
15:24:30 STEP: Running AfterEach for block EntireTestsuite K8sServicesTest
FAIL: terminating containers are not deleted after timeout
Expected
    <*errors.errorString | 0xc0004bdd40>: {
        s: "Pods are still not deleted after a timeout: 4m0s timeout expired",
    }
to be nil
15:28:30 STEP: Running AfterEach for block EntireTestsuite
```
