### PR TITLE
cilium-cli status: fail fast on terminal error

### LINKED ISSUE #34537: Update the smoke tests to fail more quickly and more clearly when there is a fatal error in the agent
### Problem Statement

Currently if there is a fatal error introduced during development into the cilium-agent, the smoke tests will attempt to [Wait for Cilium Status to be ready](https://github.com/cilium/cilium/blob/983bb6f2307a219b50610ed6b2d0098c0cd942ec/.github/workflows/tests-smoke.yaml#L166), which times out after five minutes by default.

The output from the test will flood the logs with repeated `cilium status` attempts, which ultimately will look a bit like this, repeated for around 4000 lines:

```
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             3 errors
 \__/¯¯\__/    Operator:           1 errors
 /¯¯\__/¯¯\    Envoy DaemonSet:    OK
 \__/¯¯\__/    Hubble Relay:       1 errors, 1 warnings
    \__/       ClusterMesh:        disabled

DaemonSet              cilium             Desired: 2, Unavailable: 2/2
Deployment             hubble-relay       Desired: 1, Unavailable: 1/1
DaemonSet              cilium-envoy       Desired: 2, Ready: 2/2, Available: 2/2
Deployment             cilium-operator    Desired: 1, Unavailable: 1/1
Containers:            cilium             Running: 2
                       hubble-relay       Pending: 1
                       cilium-envoy       Running: 2
                       cilium-operator    Running: 1
Cluster Pods:          0/4 managed by Cilium
Helm chart version:    
Image versions         cilium             quay.io/cilium-dev/cilium-ci:<tag>: 2
                       hubble-relay       quay.io/cilium-dev/hubble-relay-ci:<tag>: 1
                       cilium-envoy       quay.io/cilium/cilium-envoy:<tag>: 2
                       cilium-operator    quay.io/cilium-dev/operator-generic-ci:<tag>: 1
Errors:                cilium             cilium                           2 pods of DaemonSet cilium are not ready
                       cilium             cilium-jzk7s                     unable to retrieve cilium status: container cilium-agent is in CrashLoopBackOff, exited with code 2:     /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1194 +0x51
                       cilium             cilium-r6lrd                     unable to retrieve cilium status: container cilium-agent is in CrashLoopBackOff, exited with code 2:     /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1194 +0x51
                       hubble-relay       hubble-relay                     1 pods of Deployment hubble-relay are not ready
                       cilium-operator    cilium-operator                  1 pods of Deployment cilium-operator are not ready
Warnings:              hubble-relay       hubble-relay-798d7c889d-dznck    pod is pending
Error: Process completed with exit code 1.
```

In order to resolve this issue, I can go into the workflow Summary, download the sysdump, then start investigating the logs for more details. This is good, it's possible to solve the underlying problem. It could be better though.

### Proposal

This proposal is to make cilium-cli a bit smarter to detect when there is a fatal error in the previous cilium logs, then print those fatal errors in their entirety (probably involves listing the last ~50 messages in the previous agent log), then exit with a non-zero code immediately rather than retrying for the rest of the 5-minute timeout.

### Details

This could be implemented by making the Cilium CLI `cilium status --wait` command check if a Cilium pod has failed / has restarts, then check the previous run's logs for any message with `level=fatal`. In that case, maybe rather than retrying, the CLI should fail out the status wait command instead.

Some details that could help make an implementation easier:
- If the fatal error is detected, we could just list the last 50 messages from the _previous_ agent run to provide a baseline. This is probably the easiest while providing the info developers are likely to need. Alternatives would be to print a higher number by default, or print all non-debug messages, or only print logs with "warning" level or above. The only downside with filtering the logs by level is that I think that some things like Hive might print useful stack traces and I'm not sure those output messages use proper log-structuring, so this could filter out useful info.
- It would be nice to have this enabled by default even for user environments, but it would not be required to work this way in user environment by default. If necessary to simplify rollout we could enable it with a custom hidden flag, then update the workflows to use the flag.
- This could be tested by introducing a deliberate failure like a panic into the main function of the agent, then check that the CLI more quickly detects the failure and prints error output that is easy to understand.

### PR DESCRIPTION
**Pull request by nimishamehta5**
Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #34537

* Allow the `cilium status --wait` command to fail fast when there is a terminal error and not continue to retry.
* Allow collection of previous cilium agent container logs when there are restarts.

Testing -

Intentionally introduce a panic in the cilium agent to induce CrashLoopBackOff state.
Build and run `cilium status --wait`, it fails fast with the logs printed in the output:
```
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             3 errors
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    OK
 \__/¯¯\__/    Hubble Relay:       disabled
    \__/       ClusterMesh:        disabled

DaemonSet              cilium             Desired: 2, Unavailable: 2/2
DaemonSet              cilium-envoy       Desired: 2, Ready: 2/2, Available: 2/2
Deployment             cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
Containers:            cilium             Running: 2
                       cilium-envoy       Running: 2
                       cilium-operator    Running: 1
Cluster Pods:          0/0 managed by Cilium
Helm chart version:    1.17.0-dev
Image versions         cilium             localhost:5000/cilium/cilium-dev:local: 2
                       cilium-envoy       quay.io/cilium/cilium-envoy:v1.30.4-1725856146-ae435a5bef3856f4de98fa360ecfa6a0f5b0f7a1@sha256:f9c2a725a702d9fe4a4e038588a79e72955cf46c789914f940d906d65e92527e: 2
                       cilium-operator    localhost:5000/cilium/operator-generic:local: 1
Errors:                cilium             cilium          2 pods of DaemonSet cilium are not ready
                       cilium             cilium-dr4ql    unable to retrieve cilium status: container cilium-agent is in CrashLoopBackOff, exited with code 2: time="2024-09-26T04:55:38.054243877Z" level=debug msg="Skipped reading configuration file" error="Config File \"cilium\" Not Found in \"[/root]\"" subsys=config
time="2024-09-26T04:55:38.05457721Z" level=info msg="Memory available for map entries (0.003% of 4108660736B): 10271651B" subsys=config
time="2024-09-26T04:55:38.054587502Z" level=debug msg="Total memory for default map entries: 149422080" subsys=config
panic: Inducing crashloopbackoff

goroutine 1 [running]:
github.com/cilium/cilium/pkg/option.(*DaemonConfig).calculateDynamicBPFMapSizes(0x6bbde60, 0x3d2f8eb?, 0xf4e53000, 0x56d200?)
    /go/src/github.com/cilium/cilium/pkg/option/config.go:3928 +0x140
github.com/cilium/cilium/pkg/option.(*DaemonConfig).calculateBPFMapSizes(0x6bbde60, 0x40006ed6c0)
    /go/src/github.com/cilium/cilium/pkg/option/config.go:3879 +0x344
github.com/cilium/cilium/pkg/option.(*DaemonConfig).Populate(0x6bbde60, 0x40006ed6c0)
    /go/src/github.com/cilium/cilium/pkg/option/config.go:3298 +0x26e4
github.com/cilium/cilium/daemon/cmd.initDaemonConfig(0x40006ed6c0)
    /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1206 +0x54
github.com/cilium/cilium/daemon/cmd.NewAgentCmd.func3()
    /go/src/github.com/cilium/cilium/daemon/cmd/root.go:72 +0x24
github.com/spf13/cobra.(*Command).preRun(...)
    /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:1019
github.com/spf13/cobra.(*Command).execute(0x4000760008, {0x4000140010, 0x1, 0x1})
    /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:929 +0x424
github.com/spf13/cobra.(*Command).ExecuteC(0x4000760008)
    /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
    /go/src/github.com/cilium/cil
    cilium    cilium-ndpqt    unable to retrieve cilium status: container cilium-agent is in CrashLoopBackOff, exited with code 2: time="2024-09-26T04:55:57.162269969Z" level=debug msg="Skipped reading configuration file" error="Config File \"cilium\" Not Found in \"[/root]\"" subsys=config
time="2024-09-26T04:55:57.162573178Z" level=info msg="Memory available for map entries (0.003% of 4108660736B): 10271651B" subsys=config
time="2024-09-26T04:55:57.162586803Z" level=debug msg="Total memory for default map entries: 149422080" subsys=config
panic: Inducing crashloopbackoff
```

### CODE REVIEW

**Review by giorio94 — APPROVED** [review]
/lgtm for the clustermesh changes.

File: cilium-cli/status/k8s.go [hunk 1]
```diff
@@ -601,6 +604,7 @@ func (k *K8sStatusCollector) status(ctx context.Context) *Status {
 					var s *models.StatusResponse
 					var eps []*models.Endpoint
 					var err, epserr error
+					var isTerminalError bool
```
Comment (derailed) [inline cilium-cli/status/k8s.go]: nit: perhaps isTerminated or hasCrashed might be a better name?

File: cilium-cli/status/k8s.go [hunk 2]
```diff
@@ -350,11 +350,14 @@ func (k *K8sStatusCollector) Status(ctx context.Context) (*Status, error) {
 	for {
 		select {
 		case <-ctx.Done():
+			if errors.Is(ctx.Err(), context.Canceled) {
+				return mostRecentStatus, fmt.Errorf("operation canceled due to terminal error: %w", ctx.Err())
```
Comment (derailed) [inline cilium-cli/status/k8s.go]: nit: we should perhaps rephrase this error message to better represent the container has crashed or was terminated.

**Review by derailed — CHANGES_REQUESTED** [review]
@nimishamehta5 Good catch!

File: cilium-cli/status/k8s.go (hunk 1 above)
Comment (nimishamehta5) [reply cilium-cli/status/k8s.go]: updated to `isTerminated`

File: cilium-cli/status/k8s.go (hunk 2 above)
Comment (nimishamehta5) [reply cilium-cli/status/k8s.go]: updated

**Review by derailed — APPROVED** [review]
@nimishamehta5 Thanks for the updates!

File: cilium-cli/status/k8s.go [hunk 3]
```diff
@@ -350,11 +350,14 @@ func (k *K8sStatusCollector) Status(ctx context.Context) (*Status, error) {
 	for {
 		select {
 		case <-ctx.Done():
+			if errors.Is(ctx.Err(), context.Canceled) {
+				return mostRecentStatus, fmt.Errorf("wait canceled, cilium agent container has crashed or terminated: %w", ctx.Err())
```
Comment (derailed) [inline cilium-cli/status/k8s.go]: Change: "or was terminated"

Comment (nimishamehta5) [reply cilium-cli/status/k8s.go]: thanks, updated

**Comment by nimishamehta5** [comment]
@youngnick: do you mind reviewing this small PR?  thanks!

**Review by aanm — APPROVED** [review]

**Review by youngnick — APPROVED** [review]
