### PR TITLE
operator: Skip reconcile for non-GAMMA xRoutes without a Cilium-managed Gateway

### LINKED ISSUE #34754: cilium-operator: attempts to reconcile non-Cilium xRoutes
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

When enabling the Gateway API functionality in the 1.16.1 helm chart in our k8s clusters, the cilium-operator began reconciling HTTPRoutes owned by the Kong Kubernetes Ingress Controller, which caused both controllers to update the same HTTPRoutes in a tight loop.

### How can we reproduce the issue?

1. Install the Cilium helm chart with Gateway API enabled
2. Install the Kong Kubernetes Ingress Controller chart
3. Create a KIC Gateway and an associated HTTPRoute
4. Observe the KIC and Cilium operators reconciling the HTTPRoute in a tight loop

### Cilium Version

v1.16.1

### Kernel Version

6.1.102

### Kubernetes Version

v1.28.12-eks

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by aetimmes**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

This is a revival of https://github.com/cilium/cilium/pull/34753.

As of 1.16.3, the Cilium Gateway API operator currently makes several assumptions around it being the only Gateway API reconciler in a given cluster; deploying the Cilium operator alongside another Gateway API operator causes an infinite back-and-forth loop of reconciliation.

This PR makes the following changes:
- adds logic to the (non-GAMMA) xRoute reconcilers to check for the existence of the Cilium gateway operator class
- ~~adds a test to ensure that the HTTPRoute reconciler does not update HTTPRoutes that do not have a cilium-managed Gateway in its parentRefs~~
- ~~updates the `non-existent gateway` test to ensure that the operator correctly errors without updating the status when a malformed HTTPRoute is encountered~~

(The above-mentioned tests have been removed in the most current iteration of this PR since the logic has been moved out of the reconciliation functions and into the builder predicates.)

Fixes: https://github.com/cilium/cilium/issues/34754

```release-note
operator: don't reconcile non-GAMMA xRoutes without a Cilium-managed Gateway
```

### CODE REVIEW

File: operator/pkg/gateway-api/helpers.go [hunk 1]
```diff
@@ -178,3 +179,22 @@ func setMergedLabelsAndAnnotations(temp, desired client.Object) {
 	temp.SetAnnotations(mergeMap(temp.GetAnnotations(), desired.GetAnnotations()))
 	temp.SetLabels(mergeMap(temp.GetLabels(), desired.GetLabels()))
 }
+
+// hasCiliumManagedGateway checks if any of the route's parent refs point to a Cilium-managed gateway.
+// Returns true if at least one parent gateway is managed by Cilium, false otherwise.
+func hasCiliumManagedGateway(ctx context.Context, c client.Client, parentRefs []gatewayv1.ParentReference, getGatewayFn func(ref gatewayv1.ParentReference) (*gatewayv1.Gateway, error), logger *slog.Logger) (bool, error) {
+	for _, parent := range parentRefs {
+		if (parent.Group == nil || *parent.Group == gatewayv1.GroupName) &&
```
Comment (aetimmes) [inline operator/pkg/gateway-api/helpers.go]: This check exists in the helpers module, but when I tried to import/reference that method here I got some mod-vendor compilation errors that I didn't have enough golang-fu to resolve, so I've inlined them for now.

**Review by byxorna — APPROVED** [review]

File: operator/pkg/gateway-api/helpers.go [hunk 2]
```diff
@@ -178,3 +179,22 @@ func setMergedLabelsAndAnnotations(temp, desired client.Object) {
...
+			(parent.Kind == nil || *parent.Kind == kindGateway) {
+
+			gw, err := getGatewayFn(parent)
+			if err != nil {
+				return false, fmt.Errorf("failed to get Gateway: %w", err)
```
Comment (aetimmes) [inline operator/pkg/gateway-api/helpers.go]: @sayboras The end result of this line is that if there is no Gateway associated with a route, errors will be logged - I don't know to what extent this behavior is breaking existing integration tests and whether this particular failure mode should be a warning instead of an error.

Comment (sayboras) [reply operator/pkg/gateway-api/helpers.go]: sorry for late reply, I am taking a look at this PR and get back to you soon.

Comment (sayboras) [reply operator/pkg/gateway-api/helpers.go]: WDYT about expanding the predicate function ? 

https://github.com/cilium/cilium/blob/ac46da9fcc48dce1d5f9e7ca4d600aa8332622b1/operator/pkg/gateway-api/httproute.go#L131

Comment (aetimmes) [reply operator/pkg/gateway-api/helpers.go]: Just pushed a new set of commits that adopts that approach; will test locally and see if this is viable

**Comment by aetimmes** [comment]
Not stale!

File: operator/pkg/gateway-api/helpers.go (hunk 2 above)
Comment (aetimmes) [reply operator/pkg/gateway-api/helpers.go]: Looks like this method is working as intended:

`cilium-operator-86649d6bc8-xlk9r cilium-operator 2024-12-28T17:00:46.774617211-05:00 time=2024-12-28T22:00:46Z level=debug msg="Gateway does not have matching controller, skipping" module=operator.operator-controlplane.leader-lifecycle.gateway-api controller=gateway resource=default/non-cilium-httproute`

**Comment by aetimmes** [comment]
future TODO: ensure we only clobber status entries from our matching controller name (in case someone's using the same route with two Gateways/GatewayClasses; I'm not doing this so I'm punting on it for now)

File: operator/pkg/gateway-api/grpcroute.go [hunk 3]
```diff
@@ -62,7 +62,8 @@ func (r *grpcRouteReconciler) SetupWithManager(mgr ctrl.Manager) error {
 
 	builder := ctrl.NewControllerManagedBy(mgr).
 		// Watch for changes to GRPCRoute
-		For(&gatewayv1.GRPCRoute{}).
+		For(&gatewayv1.GRPCRoute{},
+			builder.WithPredicates(predicate.NewPredicateFuncs(r.hasMatchingGatewayParent()))).
```
Comment (aetimmes) [inline operator/pkg/gateway-api/grpcroute.go:66]: With the hasMatchingGatewayParent logic moving into the builder predicates (as opposed to being inside the reconciler functions in previous iterations of this MR), I'm no longer sure where to put tests for this condition. Would be open to ideas here - maybe writing a quick+dirty unit test for the `hasMatchingGatewayParent` function would be easiest?

File: operator/pkg/gateway-api/helpers.go (hunk 2 above)
Comment (sayboras) [reply operator/pkg/gateway-api/helpers.go]: thanks for your help investigating and confirming the result :heavy_check_mark:

File: operator/pkg/gateway-api/grpcroute.go (hunk 3 above)
Comment (sayboras) [reply operator/pkg/gateway-api/grpcroute.go:66]: sounds good to me :heavy_check_mark:

Comment (aetimmes) [reply operator/pkg/gateway-api/grpcroute.go:66]: Just pushed `operator/pkg/gateway-api/httproute_test.go` with those tests. Let me know if that's the right place or if we want to merge them into the reconciler test file

**Comment by aetimmes** [comment]
Force-pushed update to fix missing header comments

**Comment by aetimmes** [comment]
[this](https://github.com/cilium/cilium/actions/runs/12585985734/job/35078930489#step:14:112) failure feels unrelated to my change?

**Review by sayboras — APPROVED** [review]
Thanks a lot for your continued work on this issue :+1:
