### PR TITLE
LRP: Fix loopback in per packet LB mode

### LINKED ISSUE #30558: Local Redirect Policy results in loopback when socket-LB is disabled
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

[PR#13287 ](https://github.com/cilium/cilium/pull/13287/) was added to prevent the local-redirect service from looping back packets from the service's node-local backend to itself. However, this solution works only when socket load balancing mode is fully enabled (`ENABLE_SOCKET_LB_FULL`) or when the node local backend uses host network (`ENABLE_SOCKET_LB_HOST_ONLY`). We would run into the same loopback issue when the local-redirect service uses pod network and we probably need to have a loop prevention logic added in the lxc ebpf code.

cc: @sugangli ,  @liuyuan10 , @aojea 

### Cilium Version

Client: 1.13.10
Daemon: 1.13.10

### Kernel Version

Linux default-byac 6.1.58+ #1 SMP PREEMPT_DYNAMIC Sat Nov  4 14:14:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.28.5
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3-gke.1203001

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by pravk03**
This PR fixes cases with the local redirect policy datapath behavior with per-packet LB resulting in loopback. The loopback occurs when the request originates from the node local backend and the local redirect service translation in the bpf program at the LXC interface causes the request to be redirected back to itself. This PR extends the fix in #26144 to work for per-packet LB mode. 

Fixes: #30558

```release-note
Fix loopback with LRP when per-packet LB is used. 
```

### CODE REVIEW

**Comment by joestringer** [comment]
@pravk03 thanks for the fix! Please make sure to sign off your commits per the comment from the bot above before marking PRs ready for review.

**Comment by joestringer** [comment]
Smoke tests are just highlighting some style/linting issues. I've kicked off the broader testsuite which should bring back results in the next hour or so. I suggest waiting until all the tests provide feedback before addressing any issues raised by the CI.

File: bpf/bpf_lxc.c [hunk 1]
```diff
@@ -72,6 +72,36 @@
...
+	key.netns_cookie = cookie;
+	key.address = address;
+	key.port = port;
+	val = map_lookup_elem(&LB4_SKIP_MAP, &key);
+	if (val)
+		return true;
+	return false;
+}
+#endif /* ENABLE_LOCAL_REDIRECT_POLICY */
+
```
Comment (aditighag) [inline bpf/bpf_lxc.c]: Why duplicate this function along with the comment? Can we move the function from `bpf_sock.c` to `lb.h` instead? Please do these changes in a separate commit.

File: bpf/bpf_lxc.c [hunk 2]
```diff
@@ -135,6 +173,27 @@ static __always_inline int __per_packet_lb_svc_xlate_4(void *ctx, struct iphdr *
...
+	memset(&key, 0, sizeof(key));
+	key.netns_cookie = cookie;
+	key.address = addr;
+	key.port = port;
+	val = map_lookup_elem(&LB6_SKIP_MAP, &key);
+	if (val)
+		return true;
+	return false;
+}
+#endif /* ENABLE_LOCAL_REDIRECT_POLICY */
```
Comment (aditighag) [inline bpf/bpf_lxc.c]: Same as above.

File: pkg/endpoint/cache.go [hunk 3]
```diff
@@ -113,6 +115,16 @@ func (ep *epInfoCache) GetIdentityLocked() identity.NumericIdentity {
 	return ep.identity
 }
 
+// GetEndpointNetnsCookie returns the network namespace cookie for the endpoint
+func (ep *epInfoCache) GetEndpointNetnsCookie() uint64 {
+	return ep.netNsCookie
+}
```
Comment (aditighag) [inline pkg/endpoint/cache.go]: The function body is same as `GetEndpointNetnsCookieLocked`. Is that expected? Should this function try to acquire a lock?

File: bpf/bpf_lxc.c [hunk 4]
```diff
@@ -110,10 +140,18 @@ static __always_inline int __per_packet_lb_svc_xlate_4(void *ctx, struct iphdr *
...
+	#if defined(ENABLE_SOCKET_LB_FULL)
 		if (unlikely(lb4_svc_is_localredirect(svc)))
 			goto skip_service_lookup;
-#endif /* ENABLE_LOCAL_REDIRECT_POLICY && ENABLE_SOCKET_LB_FULL */
+	#endif /* ENABLE_SOCKET_LB_FULL */
+	#ifdef HAVE_NETNS_COOKIE
+		if (unlikely(lb4_svc_is_localredirect(svc)) &&
+		    lb4_skip_xlate_from_ctx_to_svc(ENDPOINT_NETNS_COOKIE, tuple.daddr, tuple.sport))
+			goto skip_service_lookup;
+	#endif
```
Comment (aditighag) [inline bpf/bpf_lxc.c]: Can we move this logic to the code where the datapath detects [loopback traffic](https://github.com/cilium/cilium/blob/main/bpf/lib/lb.h#L1638)? We can avoid the penalty of executing this for regular traffic on a per packet basis.

**Review by aditighag — CHANGES_REQUESTED** [review]
Nice work! 🚀 Good to see the BPF tests as well. Please see inline comments from the first pass. 

- I presume you've tested this e2e on a GKE cluster? Can you add details of the testing along with packet traces showing LRP service LB getting skipped as expected? 
- Please extend the LRP doc with the GKE Cloud DNS deployment setup - https://docs.cilium.io/en/latest/network/kubernetes/local-redirect-policy/#use-cases.

File: pkg/endpoint/cache.go (hunk 3 above)
Comment (joestringer) [reply pkg/endpoint/cache.go]: This function is completely unused isn't it? Then we should remove it.

The fooLocked aspect is also a bit quirky.. my recollection is that part of the idea behind `epInfoCache` is that we take a snapshot of important info from the `Endpoint` object into a thread-local copy while holding a lock, then we can release the Endpoint lock and continue processing async. The fact that `epInfoCache` and the interfaces define `xxxLocked()` variants is a bit of a code smell, suggesting that knowledge of locks is leaking across interfaces when it shouldn't be.. but probably the epInfoCache needs to satisfy the same interfaces as `Endpoint` in different parts of the code. Ideally we'd work to remove those over time, but that's a broader effort so we don't need to address that in this PR. In context specifically of this PR change, if the data being accessed doesn't use a lock and it's only being referenced from this copy, then we probably don't need to name it with the `Locked` suffix. Unless it's just there to satisfy the same interface as `Endpoint`, in which case sure we can keep the Locked suffix for consistency.

**Comment by pravk03** [comment]
> Nice work! 🚀 Good to see the BPF tests as well. Please see inline comments from the first pass.
> 
> * I presume you've tested this e2e on a GKE cluster? Can you add details of the testing along with packet traces showing LRP service LB getting skipped as expected?
> * Please extend the LRP doc with the GKE Cloud DNS deployment setup - https://docs.cilium.io/en/latest/network/kubernetes/local-redirect-policy/#use-cases.

I verified this on a kind cluster with a same setup as in #30558. We do not have cilium with your changes (#https://github.com/cilium/cilium/pull/26144) available on GKE yet :).

File: bpf/bpf_lxc.c (hunk 2 above)
Comment (pravk03) [reply bpf/bpf_lxc.c]: Done.

File: bpf/bpf_lxc.c (hunk 1 above)
Comment (pravk03) [reply bpf/bpf_lxc.c]: Done.

File: pkg/endpoint/cache.go (hunk 3 above)
Comment (pravk03) [reply pkg/endpoint/cache.go]: We need GetEndpointNetnsCookieLocked() in pkg/datapath/linux/config/config.go, so i had to implement this in other places to satisfy the interface.

File: bpf/bpf_lxc.c (hunk 4 above)
Comment (pravk03) [reply bpf/bpf_lxc.c]: Made the suggested change. But lb4/6_local() is invoked from bpf_host.c and bpf_overlay.c as well. I pass an invalid value for netns cookie for those invocations.

File: pkg/datapath/loader/template.go [hunk 5]
```diff
@@ -28,6 +28,7 @@ const (
 	templateLxcID               = uint16(65535)
 	templatePolicyVerdictFilter = uint32(0xffff)
 	templateIfIndex             = math.MaxUint32
+	templateEndpointNetNsCookie = uint64(0)
```
Comment (lmb) [inline pkg/datapath/loader/template.go]: This probably needs to be non-zero to avoid clang inlining things.

File: pkg/endpoint/cache.go (hunk 3 above)
Comment (lmb) [reply pkg/endpoint/cache.go]: Took a look as well, and I don't understand why `linux/config/config.go` needs this?

**Review by lmb — CHANGES_REQUESTED** [review]

File: pkg/endpoint/cache.go (hunk 3 above)
Comment (pravk03) [reply pkg/endpoint/cache.go]: There is an existing implementation of [GetEndpointNetnsCookie()](https://github.com/cilium/cilium/blob/e541aa0d6bff185c3f45cacacb48830bc9b7527e/pkg/endpoint/identifiers.go#L166) but we need an a variant of this function which doesn't acquire the lock to be called from `linux/config/config.go`. I could just have `GetEndpointNetnsCookieLocked()` in cache.go and template.go, but created `GetEndpointNetnsCookie()` just to keep things consistent with other functions like `GetIdentity()` and `GetIdentityLocked()`. I can go ahead and remove `GetEndpointNetnsCookie()` from cache.go and template.go if that is more readable, but i don't think we can lose the Locked suffix.

File: pkg/datapath/loader/template.go (hunk 5 above)
Comment (pravk03) [reply pkg/datapath/loader/template.go]: Done.

File: pkg/endpoint/cache.go (hunk 3 above)
Comment (lmb) [reply pkg/endpoint/cache.go]: Hm I don't understand that whole function in the first place.
1. e.NetNsCookie is exported, so not all accesses are locked by definition.
2. It doesn't seem like the field is ever changed after creating the struct.

Maybe the right solution is to drop the lock (cc @aditighag why is it necessary?) or to turn the NetNsCookie into an `atomic` type.

**Review by christarazi — APPROVED** [review]
ci-structure LGTM

File: pkg/endpoint/cache.go (hunk 3 above)
Comment (aditighag) [reply pkg/endpoint/cache.go]: We can drop the `GetEndpointNetnsCookie` function altogether as `NetNsCookie`  is never updated after init, which is why it's exported similar to other exported ep fields. I'll send a PR.

File: bpf/lib/lb.h [hunk 6]
```diff
@@ -1627,6 +1709,13 @@ static __always_inline int lb4_local(const void *map, struct __ctx_buff *ctx,
 	if (lb4_svc_is_affinity(svc))
 		lb4_update_affinity_by_addr(svc, &client_id, backend_id);
 #endif
+
+#if defined(ENABLE_LOCAL_REDIRECT_POLICY) && defined(HAVE_NETNS_COOKIE)
+	if (netns_cookie > 0 && unlikely(lb4_svc_is_localredirect(svc)) &&
+	    lb4_skip_xlate_from_ctx_to_svc(netns_cookie, tuple->daddr, tuple->sport))
+		return CTX_ACT_OK;
+#endif /* ENABLE_LOCAL_REDIRECT_POLICY && HAVE_NETNS_COOKIE */
```
Comment (aditighag) [inline bpf/lib/lb.h]: I meant moving this logic for the case `saddr == backend->address`, so that the map lookups are done only for loopback case.

**Review by aditighag — CHANGES_REQUESTED** [review]
(1) >https://docs.cilium.io/en/latest/network/kubernetes/local-redirect-policy/#advanced-configurations

The LRP doc note needs to be updated - https://docs.cilium.io/en/latest/network/kubernetes/local-redirect-policy/#advanced-configurations now that the `skipRedirectFromBackend` flag is supported for per-packet LB as well. 

(1) >[bpf: dedup LBx_SKIP_MAP lookup functions](https://github.com/cilium/cilium/pull/33721/commits/4b49eb14cd072bc393d2c95e30ede1893c8e3eb6)

Please rearrange the commits so that this commit becomes a preparatory commit.

File: bpf/lib/lb.h (hunk 6 above)
Comment (pravk03) [reply bpf/lib/lb.h]: Done

**Review by qmonnet — APPROVED** [review]
Just validating the doc update - I didn't look into the code changes in details.

File: bpf/lib/lb.h [hunk 7]
```diff
@@ -1636,6 +1719,11 @@ static __always_inline int lb4_local(const void *map, struct __ctx_buff *ctx,
 	 * to make it appear from an outside address.
 	 */
 	if (saddr == backend->address) {
+	#if defined(ENABLE_LOCAL_REDIRECT_POLICY) && defined(HAVE_NETNS_COOKIE)
+		if (netns_cookie > 0 && unlikely(lb4_svc_is_localredirect(svc)) &&
+		    lb4_skip_xlate_from_ctx_to_svc(netns_cookie, tuple->daddr, tuple->sport))
+			return CTX_ACT_OK;
+	#endif /* ENABLE_LOCAL_REDIRECT_POLICY && HAVE_NETNS_COOKIE */
```
Comment (aditighag) [inline bpf/lib/lb.h:1718]: This shouldn't be under `#ifndef DISABLE_LOOPBACK_LB`.

File: bpf/bpf_lxc.c [hunk 8]
```diff
@@ -72,6 +72,7 @@
 #ifdef ENABLE_PER_PACKET_LB
 
 #ifdef ENABLE_IPV4
+
```
Comment (aditighag) [inline bpf/bpf_lxc.c]: Please revert these whitespace changes, there are more in the file.

**Review by aditighag — CHANGES_REQUESTED** [review]
@pravk03 Please fix the issue reported by the build commit job -https://github.com/cilium/cilium/actions/runs/9969376694/job/27561190095?pr=33721

One of the ginkgo test failures seems to be a flakes - 

```
12:53:30 STEP: Running JustAfterEach block for EntireTestsuite K8sDatapathConfig
FAIL: Found 1 io.cilium/app=operator logs matching list of errors that must be investigated:
2024-07-17T12:53:29.710604600Z time="2024-07-17T12:53:29Z" level=error msg="Failed to update lock optimitically: Put \"https://172.18.0.2:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cilium-operator-resource-lock?timeout=5s\": net/http: request canceled (Client.Timeout exceeded while awaiting headers), falling back to slow path" subsys=klog
```

Please check other test failures - https://docs.cilium.io/en/latest/contributing/testing/ci/#ci-failure-triage.

File: bpf/bpf_lxc.c (hunk 8 above)
Comment (pravk03) [reply bpf/bpf_lxc.c]: Done

File: bpf/lib/lb.h (hunk 7 above)
Comment (pravk03) [reply bpf/lib/lb.h:1718]: Done. 

I can move the check for LRP loopback into a separate block if thats more readable. That would add an additional (saddr == backend->address) check.

File: pkg/endpoint/cache.go (hunk 3 above)
Comment (pravk03) [reply pkg/endpoint/cache.go]: Thanks @aditinag. Do i wait for your changes and rebase ?. I could also create a commit to  drop GetEndpointNetnsCookie() from identifiers.go.

Comment (aditighag) [reply pkg/endpoint/cache.go]: This is the PR - https://github.com/cilium/cilium/pull/33856. 

>Do i wait for your changes and rebase ?

I don't quite understand why you are dependent on that change.

**Comment by aditighag** [comment]
@pravk03 It's good that you've added a BPF unit test, but can we also add an e2e test as there are some minor differences with respect to NETNS cookie retrieval? We already have one - https://github.com/cilium/cilium-cli/blob/main/connectivity/builder/local_redirect_policy.go#L43, and it's currently run with socket-LB enabled. I would suggest running it with socket-LB disabled flag as well. I'm okay if you want to do this in a separate PR, but it'll be great to do this in 1.16 so that we can also mark this PR for backporting to 1.16. Feel free to ping me or @ysksuzuki on cilium slack channels (#sig-datapath or #testing) if you have any questions.

File: pkg/endpoint/cache.go (hunk 3 above)
Comment (pravk03) [reply pkg/endpoint/cache.go]: I see that you have merged your PR. Updated the commit.

Its related because [Endpoint](https://github.com/cilium/cilium/blob/0a4ec831ec9c6b95b60fa2a73fe6e417149b442d/pkg/endpoint/endpoint.go#L144) needs to implement the [EndpointConfiguration](https://github.com/cilium/cilium/blob/0a4ec831ec9c6b95b60fa2a73fe6e417149b442d/pkg/datapath/types/config.go#L90) interface and we need a getter function for NetNs Cookie (which does not acquire any locks) in  linux/config/config.go.

Comment (aditighag) [reply pkg/endpoint/cache.go]: I'm confused: NetNscookie filed is exported. Why do you need a getter? See my above PR.

**Review by aditighag — APPROVED** [review]
@pravk03 Thanks for the follow-ups. I'm approving the PR for sig-datapath CODEOWNERS contingent upon the fact that you'll work/resolve on the follow-ups - 

- I'm still confused about the endpoint related changes - https://github.com/cilium/cilium/pull/33721#discussion_r1683612582. Will lean on @lmb's review to follow-up on this. 
-  [Documenting](https://github.com/cilium/cilium/pull/33721/#pullrequestreview-2173150364) the GKE cloud dns use case. I've filed https://github.com/cilium/cilium/issues/33916. **I'm unable to assign the issue to you for some reason. Can you self-assign this issue?**
- E2E test: I've filed - https://github.com/cilium/cilium/issues/33918. **I'm unable to assign the issue to you for some reason. Can you self-assign this issue?**

I've marked the PR for 1.16 backport, but please note that the e2e test needs to be added as a dependency. I see that you've already created a draft PR on cilium-cli. 

/cc @ysksuzuki

**Comment by joestringer** [comment]
> I'm unable to assign the issue to you for some reason. Can you self-assign this issue?

For contributors who are not members of the Cilium organization, they will need to post a comment onto the issue first and then a committer/reviewer should be able to assign them.

**Review by lmb — APPROVED** [review]

File: pkg/endpoint/cache.go (hunk 3 above)
Comment (pravk03) [reply pkg/endpoint/cache.go]: The input to the function [writeStaticData]( https://github.com/cilium/cilium/blob/50b9a31dd25e5498079528bb534059106b5bbb51/pkg/datapath/linux/config/config.go#L985) is [EndpointConfiguration](https://github.com/cilium/cilium/blob/0a4ec831ec9c6b95b60fa2a73fe6e417149b442d/pkg/datapath/types/config.go#L90)  and we cannot access NetNscookie cookie directly. We call this function with [Endpoint](https://github.com/cilium/cilium/blob/0a4ec831ec9c6b95b60fa2a73fe6e417149b442d/pkg/endpoint/endpoint.go#L144) which implements the [EndpointConfiguration](https://github.com/cilium/cilium/blob/0a4ec831ec9c6b95b60fa2a73fe6e417149b442d/pkg/datapath/types/config.go#L90) interface.

**Comment by joestringer** [comment]
Hi @pravk03 , please rebase against the `main` branch to drop the merge commits, and force push to update the PR here.

**Comment by pravk03** [comment]
Thanks for the reviews and suggestions @aditighag. I have left comments on https://github.com/cilium/cilium/issues/33918 on https://github.com/cilium/cilium/issues/33916 so that you could assign them to me. I havn't been able to spend too much time on adding E2E tests and i will take @ysksuzuki's help with adding them.

@joestringer I have rebased main and updated this PR.

**Comment by joestringer** [comment]
CI got a bit confused, closed and reopened the PR to reset the state.

**Comment by ysksuzuki** [comment]
@pravk03 Sorry, I forgot to mention. You need to push a branch to cilium/cilium repo and open a pull request from there to test a workflow change. I can test it with a separate PR. Could you drop it on this PR?

**Comment by pravk03** [comment]
> @pravk03 Sorry, I forgot to mention. You need to push a branch to cilium/cilium repo and open a pull request from there to test a workflow change. I can test it on a separate PR. Could you drop it on this PR?

Thanks @ysksuzuki. Done.

**Review by viktor-kurchenko — APPROVED** [review]

**Comment by ysksuzuki** [comment]
ci-l4lb is consistently failing. I think https://github.com/cilium/cilium/commit/809ce56bdfdeef2dddf49188a577cd56412358c9 fixes this falure. @pravk03 Could you rebase your branch?

```
time="2024-07-31T12:04:37Z" level=fatal msg="failed to start: daemon creation failed: CRD Identity allocation mode requires k8s to be configured\nfailed to stop: unable to find controller ipcache-inject-labels" subsys=daemon
```

**Comment by pravk03** [comment]
@ysksuzuki rebased.

**Comment by ysksuzuki** [comment]
I will add e2e test before backporting the PR to v1.16.

**Review by ysksuzuki — APPROVED** [review]

File: Documentation/network/kubernetes/local-redirect-policy.rst [hunk 9]
```diff
@@ -531,7 +531,7 @@ When a local redirect policy is applied, cilium BPF datapath redirects traffic g
 However, for traffic originating from a node-local backend pod destined to the policy frontend, users may want to
 skip redirecting the traffic back to the node-local backend pod, and instead forward the traffic to the original frontend.
 This behavior can be enabled by setting the ``skipRedirectFromBackend`` flag to ``true`` in the local redirect policy spec.
-The configuration is only supported with socket-based load-balancing, and requires ``SO_NETNS_COOKIE`` feature
+The configuration is supported with socket-based load-balancing and per packet based load-balancing, and requires ``SO_NETNS_COOKIE`` feature
 available in Linux kernel version >= 5.8.
```
Comment (julianwiedmann) [inline Documentation/network/kubernetes/local-redirect-policy.rst:535]:
```suggestion
This configuration requires the ``SO_NETNS_COOKIE`` feature available in Linux kernel version >= 5.8.
```

If it now works for either variant of load-balancing, let's not have the user worry about unnecessary details :).

File: bpf/tests/skip_lb_xlate_lrp_per_packet_lb.c [hunk 10]
```diff
@@ -0,0 +1,333 @@
...
+	if (!l3)
+		return TEST_ERROR;
+	l3->saddr = V4_BACKEND_IP;
+	l3->daddr = V4_SERVICE_IP;
+	/* Push TCP header */
+	l4 = pktgen__push_default_tcphdr(&builder);
+	if (!l4)
+		return TEST_ERROR;
+	l4->source = tcp_src_one;
+	l4->dest = SERVICE_PORT;
```
Comment (julianwiedmann) [inline bpf/tests/skip_lb_xlate_lrp_per_packet_lb.c:72]: Use `pktgen__push_ipv4_tcp_packet()` here? (same in the other PKTGEN stage below)

File: bpf/tests/skip_lb_xlate_lrp_per_packet_lb.c [hunk 11]
```diff
@@ -0,0 +1,333 @@
...
+	/* Add an IPCache entry for pod 1 */
+	cache_key.lpm_key.prefixlen = 32;
+	cache_key.family = ENDPOINT_KEY_IPV4;
+	cache_key.ip4 = V4_BACKEND_IP;
+	/* a random sec id for the pod */
+	cache_value.sec_identity = 112233;
+	map_update_elem(&IPCACHE_MAP, &cache_key, &cache_value, BPF_ANY);
+	ep_key.ip4 = V4_BACKEND_IP;
+	ep_key.family = ENDPOINT_KEY_IPV4;
+	map_update_elem(&ENDPOINTS_MAP, &ep_key, &ep_value, BPF_ANY);
```
Comment (julianwiedmann) [inline bpf/tests/skip_lb_xlate_lrp_per_packet_lb.c:141]: I want to believe that we have helpers for most of this in `bpf/tests/lib/...` now. Except the `LB4_SKIP_MAP` operations, which would be a good addition?

**Review by julianwiedmann — COMMENTED** [review]
Just a few non-blocking comments, maybe you want to address these in a follow-up PR.

File: bpf/tests/skip_lb_xlate_lrp_per_packet_lb.c (hunk 11 above)
Comment (pravk03) [reply bpf/tests/skip_lb_xlate_lrp_per_packet_lb.c:141]: Thanks. Created https://github.com/cilium/cilium/pull/34443.

File: bpf/tests/skip_lb_xlate_lrp_per_packet_lb.c (hunk 10 above)
Comment (pravk03) [reply bpf/tests/skip_lb_xlate_lrp_per_packet_lb.c:72]: https://github.com/cilium/cilium/pull/34443.

File: Documentation/network/kubernetes/local-redirect-policy.rst (hunk 9 above)
Comment (pravk03) [reply Documentation/network/kubernetes/local-redirect-policy.rst:535]: https://github.com/cilium/cilium/pull/34443.
