### PR TITLE
bpf: nodeport: add RevDNAT-based FIB lookup for reply traffic 

### LINKED ISSUE #26166: DSR broken with VLANs on 1.13.3
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We use cilium on tagged VLAN. Main interface has static address and VLAN interface has dynamically assigned (keepalived)  external addresses.

The following commit breaks DSR on our setup: https://github.com/cilium/cilium/commit/78f93188ae0e4a74c3794b517047e33b9c3984c5

Before 1.13.3 packets were output as it should be - on tagged interface (`wan0.4000` in our case) and with 1.13.3 packets are outputed:
* through `wan0.4000` interface if source address (packet was received on) currently directly belongs to this server (this is correct)
* through `wan0` interface in other situation and this breaks connectivity

It seems that new code ignores ip rules.

For test in VM (full setup: https://github.com/kvaster/k8s-test-guide):
10.117.10.x/24 - static internet addresses assigned to `wan0`. This addresses are used to connect via ssh to servers and to connect to internet from inside kubernetes.
10.117.12.x/24 - static addresses assigned to tagged vlan `wan0.4000`. This addresses are internal static network - used by kubernetes nodes
10.117.11.x/24 - dynamic internet addresses assigned `wan0.4000` devices via keepalived. This addresses are used by clients to connect to kubernetes ingress from outside of the world.

Following additional routes applied:
```
10.117.11.0/24 dev wan0.4000
10.117.11.0/24 dev wan0.4000 table vswitch
10.117.12.0/24 dev wan0.4000 table vswitch
```

Following additional rules applied:
```
from all to 10.244.0.0/16 lookup main priority 200
from 10.117.11.0/24 table vswitch priority 201
from 10.117.12.100 lookup vswitch priority 202
from 10.117.12.0/24 lookup vswitch priority 202
```

### Cilium Version

1.13.3

### Kernel Version

6.3.4

### Kubernetes Version

1.26.4

### Sysdump

[cilium-sysdump-20230613-124152.zip](https://github.com/cilium/cilium/files/11733377/cilium-sysdump-20230613-124152.zip)

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by julianwiedmann**
When moving the RevDNAT for backend replies from `bpf_lxc` into `bpf_host`, we lost the routing based on the post-RevDNAT layout of the packet. Depending on the installed routing rules, we then end up sending the (RevDNATed) packet from the wrong egress interface.

So as part of the RevDNAT processing in `to-netdev`, do a FIB lookup that considers the desired source IP.  And redirect the packet if it's currently on the wrong interface. We intentionally delay the actual RevDNAT rewrite until the packet has reached the correct interface, so that the packet looks as expected to components in `to-netdev` (in particular HostFW).

Long-term we would want
- a `FIB_DONE` mark on the packet (similar to `SNAT_DONE`),  to skip additional lookups.
- improve the FIB lookup  in `from-container` (for BPF Host Routing) to already consider service RevDNAT.

The initial idea was to have this check at the very top of the to-netdev program (see https://github.com/cilium/cilium/pull/26635). But we're hitting program size limits in 4.19 there, and improving that is too much of a refactor for a fix PR.

Fixes: https://github.com/cilium/cilium/issues/26166

### CODE REVIEW

**Review by gentoo-root — APPROVED** [review]

**Comment by brb** [comment]
Before merging this PR, it would be good to get `Tests with secondary NodePort device` running. Currently, it's disabled in `ci-ginkgo` (as it doesn't create a secondary network, while the Vagrant setup did), and CLI's connectivity tests used in `ci-e2e` don't test NodePort service access via multiple networks.

Anyway, the suggested testing plan for `ci-e2e`:

1. Extend some matrix configurations (with KPR=true) in the conformance-e2e.yaml with `secondary-network: true`.
2. When provisioning a Kind cluster, pass `--secondary-network` (introduced in https://github.com/cilium/cilium/pull/26338) depending on the option above. 
3. Extend [the feature detection](https://github.com/cilium/cilium-cli/blob/main/connectivity/check/features.go) to detect that Kind has multiple networks.
4. In the [NodePort from outside test case](https://github.com/cilium/cilium-cli/blob/main/connectivity/tests/service.go#L253) consider all node IP addresses.

**Comment by julianwiedmann** [comment]
Rebased to resolve trivial `bpf/tests` conflicts with https://github.com/cilium/cilium/pull/27134.

File: bpf/lib/nodeport.h [hunk 1]
```diff
@@ -3012,12 +3073,14 @@ int tail_handle_nat_fwd_ipv4(struct __ctx_buff *ctx)
...
+	ret = __handle_nat_fwd_ipv4(ctx, cluster_id, &trace, &ext_err);
 	if (IS_ERR(ret))
-		return send_drop_notify_error(ctx, 0, ret, CTX_ACT_DROP, METRIC_EGRESS);
+		return send_drop_notify_error_ext(ctx, 0, ret, ext_err,
+						  CTX_ACT_DROP, METRIC_EGRESS);
 
-	send_trace_notify(ctx, obs_point, 0, 0, 0, 0, trace.reason,
-			  trace.monitor);
+	if (ret == CTX_ACT_OK)
+		send_trace_notify(ctx, obs_point, 0, 0, 0, 0, trace.reason,
```
Comment (gentoo-root) [inline bpf/lib/nodeport.h:3082]: For my education... do we only trace the forwarded packets at the destination interface?

Comment (julianwiedmann) [reply bpf/lib/nodeport.h:3082]: I'm not sure if we have a strict precedent for it at the moment.

I could be convinced that throwing notifications for the intermediate interfaces has value. But then we should also apply proper CT-driven aggregration, and include the corresponding ifindex?

**Comment by julianwiedmann** [comment]
No intentions to backport this into v1.13 anymore. Doing so would require https://github.com/cilium/cilium/pull/26136 and https://github.com/cilium/cilium/pull/26290.
