### PR TITLE
Fix --exclude-local-address with eBPF Host-Routing

### LINKED ISSUE #41241: --exclude-local-address incompatible with eBPF Host Routing
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.0 and lower than v1.18.0

### What happened?

# Description
We enabled eBPF Host Routing and noticed that on nodes where Cilium Agents had `--exclude-local-address="169.254.20.10/31"` (for the NodeLocal DNSCache), all pods' DNS requests started failing.

Disabling eBPF Host Routing solves the issue. If we keep eBPF Host Routing enabled and remove `--exclude-local-address`, the issue is gone as well. 

What we see on the pod when the issue is happening:
```
# dig google.com
;; communications error to 169.254.20.10#53: timed out
;; communications error to 169.254.20.10#53: timed out
[...]
```

`cilium monitor` is showing:
<pre>
[...]
xx <b>drop (FIB lookup failed, 4)</b> flow 0x13a0ac9f to endpoint 0, ifindex 30, file bpf_lxc.c:1364, , identity 560589->16777241: 10.132.84.141:38658 -> 169.254.20.10:53 udp
[...]
</pre>

Looking further at the code, when an address is part of `--exclude-local-address`, it doesn't get added to the `lxc_map` (= `ENDPOINT_MAP` in the bpf code) as a local host entry (which is expected):
https://github.com/cilium/cilium/blob/5e4e4bff963488a9fdfe18d6b10b8fdbc22cff7a/daemon/cmd/hostips-sync.go#L150-L153
https://github.com/cilium/cilium/blob/492bfe8e1398dc04006be95e4836ecf830326d18/pkg/maps/lxcmap/lxcmap.go#L212-L224

The problem is that this seems to cause confusion in the eBPF Host Routing code. This lookup fails: https://github.com/cilium/cilium/blob/7a6622f94076f3942d1fdb8397ef8775166f44dd/bpf/bpf_lxc.c#L1203

and so the code continues down to the `fib_redirect` section: https://github.com/cilium/cilium/blob/7a6622f94076f3942d1fdb8397ef8775166f44dd/bpf/bpf_lxc.c#L1312

Which fails with the `FIB lookup failed, 4` error shown above. The error code `4` seems to correspond to `BPF_FIB_LKUP_RET_NOT_FWDED`:
https://github.com/cilium/cilium/blob/7a6622f94076f3942d1fdb8397ef8775166f44dd/bpf/include/linux/bpf.h#L6965

I believe this `BPF_FIB_LKUP_RET_NOT_FWDED` error is returned because the route is `local`:
```
ip route get 169.254.20.10 from 10.132.84.141 iif lxc04d54872a51f
local 169.254.20.10 from 10.132.84.141 dev lo table local
    cache <local> iif lxc04d54872a51f
```

So the packet is never delivered and we get DNS query timeouts.

# Possible remediation
I have a POC which seems to solve the issue: https://github.com/DataDog/cilium/commit/844f1c8c6c1c0ed47f6d58acf5acca9b2021f851

The idea is that we can keep track of excluded local addresses in a new map which can be consulted by the eBPF Host Routing code. When a destination ip is in that map, we avoid the fib lookup codepath and simply pass the packet to the kernel's stack. This way nothing changes identity-wise, the only change is related to routing.

Let me know if this solution is on the right path, I can open a PR

### How can we reproduce the issue?

1. Enable eBPF Host Routing
2. Set `--exclude-local-address="169.254.20.10/31"`
3. Try to reach `169.254.20.10` from a pod and confirm that there is a timeout

### Cilium Version

`1.17.6`

### Kernel Version

`6.8.0`

### Kubernetes Version

`v1.33.1`

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by antonipp**
# Description
The problem is described in detail in the original issue https://github.com/cilium/cilium/issues/41241

This PR adds error-handling logic that fixes routing for local addresses which have been passed in `--exclude-local-address`. The routing code will always attempt a FIB lookup for packets destined to these addresses and it will always fail with `BPF_FIB_LKUP_RET_NOT_FWDED` because the addresses are local. The routing code will now remediate this by passing the packet to the kernel's routing stack when encountering this scenario.

Another idea I originally had was to keep track of excluded local addresses in a separate map ( https://github.com/DataDog/cilium/commit/844f1c8c6c1c0ed47f6d58acf5acca9b2021f851 ) but this obviously introduces more complexity that the current PR.

# Testing 
Setup: deploy a pod with NLD bound to `169.254.20.10`. Set `--exclude-local-address="169.254.20.10/31"` and enable eBPF Host-Routing on the Cilium Agent.

Before the PR:
```
# dig google.com
;; communications error to 169.254.20.10#53: timed out
;; communications error to 169.254.20.10#53: timed out
[...]
```

After the PR:
```
# dig google.com
; <<>> DiG 9.18.30-0ubuntu0.20.04.2-Ubuntu <<>> google.com
;; global options: +cmd
;; Got answer:
[...]
```

Fixes: https://github.com/cilium/cilium/issues/41241

```release-note
Fix --exclude-local-address with eBPF Host-Routing
```

### CODE REVIEW

File: bpf/bpf_lxc.c [hunk 1]
```diff
@@ -1310,6 +1310,9 @@ static __always_inline int handle_ipv4_from_lxc(struct __ctx_buff *ctx, __u32 *d
 		int oif = 0;
 
 		ret = fib_redirect_v4(ctx, ETH_HLEN, ip4, false, false, ext_err, &oif);
+		if (ret == DROP_NO_FIB && *ext_err == BPF_FIB_LKUP_RET_NOT_FWDED) {
```
Comment (41ks) [inline bpf/bpf_lxc.c:1317]: You can maybe add a comment here indicating that this handles cases where the route is local.

**Comment by pchaigno** [comment]
> /test

@antonipp It's strange that you couldn't trigger tests. Have you had this issue before?

File: bpf/bpf_lxc.c [hunk 2]
```diff
@@ -1310,6 +1310,10 @@ static __always_inline int handle_ipv4_from_lxc(struct __ctx_buff *ctx, __u32 *d
 		int oif = 0;
 
 		ret = fib_redirect_v4(ctx, ETH_HLEN, ip4, false, false, ext_err, &oif);
+		/* Error handling for local routes - just pass the packet to the kernel stack */
+		if (ret == DROP_NO_FIB && *ext_err == BPF_FIB_LKUP_RET_NOT_FWDED) {
```
Comment (jrife) [inline bpf/bpf_lxc.c:1317]: nit: Drop the braces to keep things consistent with other single-line if blocks.

**Review by jrife — COMMENTED** [review]
Should something similar be done in `handle_ipv6_from_lxc`? Also just a heads up, you might want to rebase and test with https://github.com/cilium/cilium/pull/37725 which just got merged. AFAIK it shouldn't impact anything, but slightly changes how the fib lookup happens with the addition of the `BPF_FIB_LOOKUP_SKIP_NEIGH` flag.

File: bpf/bpf_lxc.c (hunk 2 above)
Comment (borkmann) [reply bpf/bpf_lxc.c:1317]: nit: also IPv6 side needs to be addressed?

**Comment by antonipp** [comment]
Thanks for the reviews, addressed the comments 👍 

> It's strange that you couldn't trigger tests. Have you had this issue before?

Yep, I did notice that this was quite flaky recently. For example in this PR, I was not able to run them consistently: https://github.com/cilium/cilium/pull/41154

I also noticed that the current PR has more failed E2E tests than usual 🤔 https://github.com/cilium/cilium/actions/runs/17077534336/job/48422818273

And this BPF complexity verifier failure looks legit as well: https://github.com/cilium/cilium/actions/runs/17077535162/job/48422742276 (need to look further into it)

**Comment by pchaigno** [comment]
/test

> And this BPF complexity verifier failure looks legit as well: https://github.com/cilium/cilium/actions/runs/17077535162/job/48422742276 (need to look further into it)

Ouch, that's going to be tricky to work around. I'm guessing we're probably already quite "close" to the complexity limit and, since your change is adding new branches, it's enough to push complexity over the limit.

> I also noticed that the current PR has more failed E2E tests than usual 🤔 https://github.com/cilium/cilium/actions/runs/17077534336/job/48422818273

Probably related to the complexity issue, no?

**Comment by pchaigno** [comment]
My bad, it's not a complexity issue but a good old verifier reject:
```
; if (ret == DROP_NO_FIB && *ext_err == BPF_FIB_LKUP_RET_NOT_FWDED) {
1849: (79) r1 = *(u64 *)(r10 -144)    ; R1_w=scalar() R10=fp0
; __u8 new_ttl, ttl = ip4->ttl;
1850: (71) r3 = *(u8 *)(r1 +22)
R1 invalid mem access 'scalar'
verification time 74405 usec
```
Are we sure `ext_err` is always defined on that code path?

File: bpf/bpf_lxc.c [hunk 3]
```diff
@@ -1310,6 +1313,9 @@ static __always_inline int handle_ipv4_from_lxc(struct __ctx_buff *ctx, __u32 *d
 		int oif = 0;
 
 		ret = fib_redirect_v4(ctx, ETH_HLEN, ip4, false, false, ext_err, &oif);
+		/* Error handling for local routes - just pass the packet to the kernel stack */
+		if (ret == DROP_NO_FIB && ext_err && *ext_err == BPF_FIB_LKUP_RET_NOT_FWDED)
```
Comment (pchaigno) [inline bpf/bpf_lxc.c]: I double checked and `ext_err` is always set when we return `DROP_NO_FIB`, so we don't need to read it here. If that ever changes, the verifier will complain.

Comment (antonipp) [reply bpf/bpf_lxc.c]: Hmm you are right, the `ext_err` check seems unnecessary after all and we still have the same verifier error: https://github.com/cilium/cilium/actions/runs/17101667870/job/48499637711
```
        	; if (ret == DROP_NO_FIB && ext_err && *ext_err == BPF_FIB_LKUP_RET_NOT_FWDED)
        	2624: (79) r1 = *(u64 *)(r10 -144)    ; R1_w=scalar() R10=fp0
        	; __u8 new_ttl, ttl = ip4->ttl;
        	2625: (71) r3 = *(u8 *)(r1 +22)
        	R1 invalid mem access 'scalar'
```
Looks like the problem is with the `new_ttl, ttl = ip4->ttl;` access, so I wonder if it's some kind of pointer issue that happens in `pass_to_stack` -> `ipv4_l3()` -> `ipv4_dec_ttl()`?
https://github.com/cilium/cilium/blob/feca6d1480ba45f89c08e63df1b517c90cd1154a/bpf/lib/ipv4.h#L62
So the `ipv4` pointer is somehow not valid anymore?

Comment (antonipp) [reply bpf/bpf_lxc.c]: ok, removed the unnecessary `ext_err` check and I believe I fixed the bad codepath by adding a check on the `ipv4` pointer before passing it to `ipv4_l3`:
https://github.com/cilium/cilium/blob/f9b5a55f3e62f86fed535f4351424a7b4e9c8cab/bpf/bpf_lxc.c#L1342-L1343

The verifier seems happy now: https://github.com/cilium/cilium/actions/runs/17126425420

Comment (pchaigno) [reply bpf/bpf_lxc.c]: Awesome!

I think we'll need a lot more context in the commit description, on why this new check is needed, but also to add all the context from the pull request description.

Comment (antonipp) [reply bpf/bpf_lxc.c]: Done, added all the context to the commit description 👍

File: bpf/bpf_lxc.c [hunk 4]
```diff
@@ -1333,6 +1339,8 @@ static __always_inline int handle_ipv4_from_lxc(struct __ctx_buff *ctx, __u32 *d
 
 pass_to_stack:
 #ifdef ENABLE_ROUTING
+	if (!revalidate_data(ctx, &data, &data_end, &ip4))
```
Comment (jrife) [inline bpf/bpf_lxc.c]: > The additional revalidate_data check on the ipv4 pointer is needed because it can get invalidated in fib_redirect_v4 so it should be checked before being passed further

nit: I slightly feel like this should live close to the `fib_redirect_v4` then before the `goto pass_to_stack` so it's clear what it's related to. Does this work? Also, is something similar needed in the IPv6 case? I'm a bit suspicious of the asymmetry there.

Comment (antonipp) [reply bpf/bpf_lxc.c]: You're right, I moved it closer, I think it should do the trick.

And AFAICT the asymmetry comes from the fact that `ipv6_l3` never directly uses the `ip6` pointer: 
https://github.com/cilium/cilium/blob/367db3e6d224ccbd5250e9b9120b585e4ec45679/bpf/bpf_lxc.c#L785

So the verifier is happy.

**Comment by jrife** [comment]
* [`ci-ipsec-e2e`](https://github.com/cilium/cilium/actions/runs/17150367398) failures look like a flake I've seen before: https://github.com/cilium/cilium/issues/41012
* [`ci-eks`](https://github.com/cilium/cilium/actions/runs/17150367684/job/48655061223) hit https://github.com/cilium/cilium/issues/31097

I'll retrigger these.

**Review by jrife — APPROVED** [review]

**Review by borkmann — APPROVED** [review]
