### PR TITLE
bgp: withdraw route when svc has no endpoints

### LINKED ISSUE #40438: Cilium LoadBalancer w/Local and BGP drops traffic on no endpoints
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.11 and lower than v1.17.0

### What happened?

Hi
For some reason when I have a LoadBalancer service with no endpoints (due to health checks etc) and BGP (with anycast using ECMP on the TOR/router level), it just drops all traffic to that given IP from within the k8s cluster when no endpoints exist and externalTrafficPolicy: Local

### How can we reproduce the issue?

1. install Cilium
2. set up BGP with switch/router
3. Create a cilium loadbalancer with BGP
4. Create a svc with no existing endpoints like this
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    io.cilium/lb-ipam-ips: 10.229.8.15
    io.cilium/lb-ipam-sharing-key: ashley1.oa
    lbipam.cilium.io/ips: 10.229.8.15
    lbipam.cilium.io/sharing-key: ashley1.oa
  labels:
    bgp: yespls
  name: apiserver-test
spec:
  allocateLoadBalancerNodePorts: false
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  loadBalancerClass: io.cilium/bgp-control-plane
  ports:
  - name: apiserver
    port: 6443
    protocol: TCP
    targetPort: 6443
  selector:
    app: apiservers
  sessionAffinity: None
  type: LoadBalancer
```

5. have NO endpoints working
6. try CURLing to the `10.229.8.15` IP from within the cluster
7. observe
```bash
root@worker-az2-b8f5bfb5-l6h4q:/# curl -v http://10.229.8.15:6443
*   Trying 10.229.8.15:6443...
* Immediate connect fail for 10.229.8.15: Operation not permitted
* Closing connection 0
curl: (7) Couldn't connect to server
```
8. Observe IP being dropped somewhere in bpf code instead of being let go through the BGP completely disobeying any reason to ever use BGP and anycast

### Cilium Version

tested with 1.15.x (multiple versions) and 1.16.8

### Kernel Version

6.11.0 branch, Ubuntu

### Kubernetes Version

tested 1.32.x and 1.33.x

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by oblazek**
We have services with either externalTrafficPolicy or internalTrafficPolicy. We have discussed in the issue https://github.com/cilium/cilium/issues/40438 that according to the docs - externalTrafficPolicy applies to loadBalancerIP and/or externalIP and internalTrafficPolicy applies to clusterIP. There was also a comment that it doesn't matter where the client is located as e.g. loadBalancerIP can also be accessed from within the cluster (from e.g. pod) even though it's not that common. 
When endpoints are taken into account the value of the externalTP or internalTP  matters. In BGP world when either is set to `Local`, the IP (LBIP, externalIP or clusterIP) is announced only if the node hosts an endpoint. When eTP/iTP is set to the other value - `Cluster`, then all nodes will announce the IP even though they do not host any relevant pod/endpoint.

In the current codebase the code doesn't handle properly when service has zero endpoints and the eTP/iTP is set to `Cluster`. In this case only for `Local` the node will stop announcing the IP and the packet targetted to the service will be dropped [here](https://github.com/cilium/cilium/blob/main/bpf/bpf_sock.c#L290-L291). The problem is that this doesn't take eTP/iTP value into account and dropps the packet in both cases.

[We've agreed](https://github.com/cilium/cilium/issues/40438#issuecomment-3090582533) that for eTP/iTP == `Cluster` 
we will not drop the packet, but will forward it to the stack. Aditionally our cilium bgp subsystem will stop announcing the IP so that setups that use e.g. anycast can benefit from this (and traffic will be forwarded to e.g. another DC which [announces the same VIP](https://github.com/cilium/cilium/issues/40438#issuecomment-3053556535)).   

This PR handles this scenario.

TLDR:
* add a new flag which defaults to true, so that current behavior is not changed
* keep track of services when corresponding epDiffstore objects has been updated
* withdraw a route when service has 0 endpoint newly for eTP/iTP=Cluster
* socklb - do not drop packets when service has 0 endpoints and eTP/iTP=Cluster

Fixes: [#40438](https://github.com/cilium/cilium/issues/40438)

cc @rastislavs 

```release-note
bgp: optionally withdraw route when service has 0 endpoints to allow balancing to a different DC/cluster (anycast)
```

### CODE REVIEW

**Comment by rastislavs** [comment]
@oblazek I think you will also need to update tests in `pkg/bgpv1/test/testdata` to provide endpointslices, for example as in `/pkg/bgpv1/test/testdata/svc-traffic-policy.txtar`

**Comment by oblazek** [comment]
thanks :), will take a look

**Comment by oblazek** [comment]
I seem to have broken `adverts_tests.go` tested with e.g. `PRIVILEGED_TESTS=true go test -exec "sudo -E" . -test.run TestPrivilegedLBEgressAdvertisementWithLoadBalancerIP`. Any idea what could be the reason @rastislavs ?

**Comment by rastislavs** [comment]
> I seem to have broken `adverts_tests.go` tested with e.g. `PRIVILEGED_TESTS=true go test -exec "sudo -E" . -test.run TestPrivilegedLBEgressAdvertisementWithLoadBalancerIP`. Any idea what could be the reason @rastislavs ?

I guess you will need to set `BGPNoEndpointsRoutable` to true in this test hive setup for BGPv1 tests: https://github.com/cilium/cilium/blob/88a14660d7974cde0afdedf82fc2254c4fc01088/pkg/bgpv1/test/fixtures.go#L196-L257

BTW, I should have said it earlier, but not sure if adding support for this to BGPv1 adds much value as it is already deprecated, probably doing this just for BGPv2 would suffice. But as you have already done all that work, lets do that, at least it will be in sync until we remove BGPv1.

File: pkg/bgpv1/manager/reconciler/service.go [hunk 1]
```diff
@@ -24,24 +25,34 @@ import (
 	"github.com/cilium/cilium/pkg/k8s/slim/k8s/apis/labels"
 	slim_metav1 "github.com/cilium/cilium/pkg/k8s/slim/k8s/apis/meta/v1"
 	"github.com/cilium/cilium/pkg/loadbalancer"
+	"github.com/cilium/cilium/pkg/option"
 	ciliumslices "github.com/cilium/cilium/pkg/slices"
 )
 
+type RoutesConfig struct {
```
Comment (rastislavs) [inline pkg/bgpv1/manager/reconciler/service.go]: This config seems to be defined at 2 places now. What about defining a common `pkg/bgpv1/config` and using it from there? In the future, we can move there other BGP-specific config options, such as `bgp-secrets-namespace`

File: pkg/bgpv1/cell.go [hunk 2]
```diff
@@ -91,6 +91,10 @@ var Cell = cell.Module(
 	// Provides the reconcilers used by the route manager to update the config
 	reconciler.ConfigReconcilers,
 
+	cell.Config(reconcilerv2.RoutesConfig{
+		BGPNoEndpointsRoutable: option.Config.BGPNoEndpointsRoutable,
```
Comment (rastislavs) [inline pkg/bgpv1/cell.go]: Could we define something like `DefaultRoutesConfig` and provide that into the hive, like in this example: https://docs.cilium.io/en/latest/contributing/development/hive/#config ?

Comment (oblazek) [reply pkg/bgpv1/cell.go]: thanks, did that

File: pkg/bgpv1/manager/reconciler/service.go (hunk 1 above)
Comment (oblazek) [reply pkg/bgpv1/manager/reconciler/service.go]: sounds good

**Comment by oblazek** [comment]
ci-verifier fail is not relevant, failing on:
```
go: golang.org/dl/go1.24.5@latest: golang.org/dl@v0.0.0-20250708172407-27a85deea5c3: verifying module: golang.org/dl@v0.0.0-20250708172407-27a85deea5c3: Get "https://sum.golang.org/lookup/golang.org/dl@v0.0.0-20250708172407-27a85deea5c3": dial tcp: lookup sum.golang.org on 127.0.0.53:53: server misbehaving
```

**Review by asauber — APPROVED** [review]
Approving for config changes

File: pkg/datapath/linux/config/config.go [hunk 3]
```diff
@@ -341,6 +341,10 @@ func (h *HeaderfileWriter) WriteNodeConfig(w io.Writer, cfg *datapath.LocalNodeC
 			// always runs with "hostNetwork: true".
 			cDefinesMap["HOST_NETNS_COOKIE"] = fmt.Sprintf("%d", cookie)
 		}
+
+		if option.Config.BGPNoEndpointsRoutable {
+			cDefinesMap["NO_ENDPOINTS_ROUTABLE"] = "1"
```
Comment (rgo3) [inline pkg/datapath/linux/config/config.go]: Could we use the new Cilium config mechanism for this datapath config? You can take a look at https://docs.cilium.io/en/stable/contributing/development/datapath_config/ for reference. Take a look at e.g. `bpf/include/bpf/config/lxc.h` and create something analog to this for bpf_sock.c to use `DECLARE_CONFIG` for your new config.

Comment (oblazek) [reply pkg/datapath/linux/config/config.go]: totally! thanks I had no idea there is a new way

File: pkg/option/config.go [hunk 4]
```diff
@@ -992,6 +992,9 @@ const (
 	// EnableBGPControlPlaneStatusReport enables BGP Control Plane CRD status reporting
 	EnableBGPControlPlaneStatusReport = "enable-bgp-control-plane-status-report"
 
+	// BGPNoEndpointsRoutable enables advertising of services with 0 endpoints
+	BGPNoEndpointsRoutable = "bgp-no-endpoints-routable"
```
Comment (bimmlerd) [inline pkg/option/config.go]: nit: I don't have context on this change, but in general adding to `option/config` is no longer the way to go. Is there a way these can move into config cells instead?

Comment (oblazek) [reply pkg/option/config.go]: yeah totally, let me see if I am able to pass the tests without this.. maybe I am missing something

Comment (oblazek) [reply pkg/option/config.go]: but will have to figure out how do I pass that to the `pkg/datapath/config...`

Comment (oblazek) [reply pkg/option/config.go]: done, ptal :)

File: pkg/datapath/linux/config/config.go (hunk 3 above)
Comment (oblazek) [reply pkg/datapath/linux/config/config.go]: done :)

File: pkg/option/config.go (hunk 4 above)
Comment (bimmlerd) [reply pkg/option/config.go]: Nice, thank you. If you mark the PR as ready for review I can give a LGTM - otherwise the approval won't count once you mark it ready, because GitHub 🤷‍♂️

File: install/kubernetes/cilium/templates/cilium-configmap.yaml [hunk 5]
```diff
@@ -777,6 +777,10 @@ data:
   kube-proxy-replacement-healthz-bind-address: {{ default "" .Values.kubeProxyReplacementHealthzBindAddr | quote}}
 {{- end }}
 
+{{- if hasKey .Values "enableNoEndpointsRoutable" }}
+  enable-no-endpoints-routable: {{ .Values.enableNoEndpointsRoutable | quote }}
```
Comment (gandro) [inline install/kubernetes/cilium/templates/cilium-configmap.yaml]: We should document this in the values.yaml.tmpl. Also consider not making this a top-level value, but add it as a bgp subvalue, e.g. `bgp.enableNoEndpointsRoutable`.

I also wonder if we should prefix the agent flag with `bgp`, since it isn't clear without context that `enable-no-endpoints-routable` refers to a BGP behavior.

**Review by gandro — COMMENTED** [review]
Reviewed Helm changes

File: install/kubernetes/cilium/templates/cilium-configmap.yaml (hunk 5 above)
Comment (oblazek) [reply install/kubernetes/cilium/templates/cilium-configmap.yaml]: I was hesitant about this since this also modifies socketLB behaviour not strictly BGP only, but it makes more sense to me as well

**Review by bimmlerd — APPROVED** [review]

File: install/kubernetes/cilium/templates/cilium-configmap.yaml (hunk 5 above)
Comment (rastislavs) [reply install/kubernetes/cilium/templates/cilium-configmap.yaml]: I am torn whether this should be BGP specific config or not.. 

> this also modifies socketLB behaviour not strictly BGP only

Is there any use-case for enabling `enable-no-endpoints-routable` outside of the BGP one?

**Review by rastislavs — APPROVED** [review]
BGP changes LGTM!

File: install/kubernetes/cilium/templates/cilium-configmap.yaml (hunk 5 above)
Comment (oblazek) [reply install/kubernetes/cilium/templates/cilium-configmap.yaml]: Yeah, might be not that common, but when bgpControlPlane is not enabled and the classic services of type LoadBalancer provided by external loadbalancer there still will be svc entry in a bpf map, so that packet can be decapsulated and a "socket" found. When accessed from within the cluster the code will end up in exactly the same place and it won't matter if BGP is enabled or not.

Comment (oblazek) [reply install/kubernetes/cilium/templates/cilium-configmap.yaml]: but no objection in adding the bgp prefix

Comment (rastislavs) [reply install/kubernetes/cilium/templates/cilium-configmap.yaml]: > When accessed from within the cluster the code will end up in exactly the same place and it won't matter if BGP is enabled or not

Right, because of this (potential use of external loadbalancer other than BGP) I would slightly prefer to keep the agent flag as it is (= not prefixed with BGP). I guess that's also the reason why you moved the config to a package outside of the bgp code tree (`pkg/svcrouteconfig/cell.go`).

Comment (gandro) [reply install/kubernetes/cilium/templates/cilium-configmap.yaml]: I'm also fine with keeping it top-level if it affects SockLB too. My only other suggestion would be to clarify that we're talking about services, e.g. `enableNoServiceEndpointsRoutable` because the term "endpoint" is very overloaded in Cilium (i.e. there are also the concept of a Cilium endpoints. There's a feature called endpoint routes, which I originally though this related to, which is why I suggested adding the BGP context).

But I don't feel strongly at all about this, just bikeshedding here, so feel free to ignore.

Comment (oblazek) [reply install/kubernetes/cilium/templates/cilium-configmap.yaml]: no you are right, it might sound like endpoint-routes which is really not related, let me add the `Service` => `enableNoServiceEndpointsRoutable`

File: pkg/datapath/config/gen.go [hunk 6]
```diff
@@ -13,3 +13,4 @@ package config
 //go:generate go run github.com/cilium/cilium/tools/dpgen -path ../../../bpf/bpf_overlay.o -embed Node -kind object -name BPFOverlay -out overlay_config.go
 //go:generate go run github.com/cilium/cilium/tools/dpgen -path ../../../bpf/bpf_network.o -embed Node -kind object -name BPFNetwork -out network_config.go
 //go:generate go run github.com/cilium/cilium/tools/dpgen -path ../../../bpf/bpf_wireguard.o -embed Node -kind object -name BPFWireguard -out wireguard_config.go
+//go:generate go run github.com/cilium/cilium/tools/dpgen -path ../../../bpf/bpf_sock.o -kind object -name BPFSocket -out sock_config.go
```
Comment (rgo3) [inline pkg/datapath/config/gen.go]: Lets keep the `Node` object embedded as with the other configuration structs (mainly for future use) and keep the naming in line with the C/.o bpf files:
```suggestion
//go:generate go run github.com/cilium/cilium/tools/dpgen -path ../../../bpf/bpf_sock.o -embed Node -kind object -name BPFSock -out sock_config.go
```

**Review by rgo3 — APPROVED** [review]
LGTM, assuming my open comment will be addressed. Thanks @oblazek!

**Review by gandro — APPROVED** [review]
Looks good for Helm!

File: pkg/datapath/config/gen.go (hunk 6 above)
Comment (oblazek) [reply pkg/datapath/config/gen.go]: understood, I'm on it

**Review by marseel — APPROVED** [review]
Thanks!

File: pkg/datapath/config/gen.go (hunk 6 above)
Comment (oblazek) [reply pkg/datapath/config/gen.go]: done, but had to export/move `nodeConfig()` function to avoid import cycle loop :/

**Review by joestringer — COMMENTED** [review]
The changes I see look fine, but two minor points:

1. The release note in the PR description implies that this changes the default setting to withdraw routes, but the rest of the text implies there is no change to the default. Could you clarify that in the release note? When users read the release note, they may read that note and take away that there was a change to this behavior by default when there isn't.

2. I was requested review as a member of @cilium/docs-structure , but this new functionality doesn't appear to have any docs. Not sure if there's a good place to document this new behavior but did you consider how to explain this feature to other users?

**Comment by oblazek** [comment]
Added a documentation part for the new flag so that it's explained to the users in more detail. Fixed the release note. Thanks Joe. PTAL

**Comment by oblazek** [comment]
rebased - resolved the conflict

**Review by joestringer — APPROVED** [review]
LGTM, thanks.

**Review by aditighag — CHANGES_REQUESTED** [review]
Hi! Couple of clarifying questions - 
(1) >socketLB: include svcRouteConfig package
Can you add context to the commit/PR description why this change is only needed in socket-LB and not per packet-LB? We have `DROP_NO_SERVICE` drops in per-packet LB datapath as well. 
(2) The PR mentions that when there was no service endpoints, packets would be routed by BGP installed routes. This suggests that the config needs to be enabled only when BGP control plane is enabled, no?

**Comment by oblazek** [comment]
@aditighag hi :)
1) Tbh in our setup we do not have PER_PACKET_LB enabled (and are running 1.16.X) so I totally missed there is `DROP_NO_SERVICE` part which sends out ICMPs. This means in our case the ideal scenario would be returning `LB_PUNT_TO_STACK` to return OK and continue via the slowpath. WDYT?
2) True, but we also have a setup with external LB so we need the config to be enabled (or disabled) even if bgpControlPlane is false. See my comment https://github.com/cilium/cilium/pull/40717#discussion_r2282141865

**Comment by aditighag** [comment]
> 1. Tbh in our setup we do not have PER_PACKET_LB enabled (and are running 1.16.X) so I totally missed there is `DROP_NO_SERVICE` part which sends out ICMPs. This means in our case the ideal scenario would be returning `LB_PUNT_TO_STACK` to return OK and continue via the slowpath. WDYT?

`LB_PUNT_TO_STACK` seems to be an alias to `DROP_PUNT_PROXY`, so not sure if that's what you want. 
I would expect we want the same behavior in per-packet LB as socket-LB -- so not dropping packets for a cluster scoped service when the new config you added is enabled.

> 2. True, but we also have a setup with external LB so we need the config to be enabled (or disabled) even if bgpControlPlane is false. See my comment [bgp: withdraw route when svc has no endpoints #40717 (comment)](https://github.com/cilium/cilium/pull/40717#discussion_r2282141865)

Got it, thanks for the context. Appreciate the detailed PR description, there is a lot to unpack here. :)

**Comment by oblazek** [comment]
> LB_PUNT_TO_STACK seems to be an alias to DROP_PUNT_PROXY, so not sure if that's what you want.
I would expect we want the same behavior in per-packet LB as socket-LB -- so not dropping packets for a cluster scoped service when the new config you added is enabled.

Thanks, no that's not what I want. :sweat_smile: Understood, working on it, but trying to find out a way to test the PER_PACKET_LB.

**Comment by aditighag** [comment]
> > LB_PUNT_TO_STACK seems to be an alias to DROP_PUNT_PROXY, so not sure if that's what you want.
> > I would expect we want the same behavior in per-packet LB as socket-LB -- so not dropping packets for a cluster scoped service when the new config you added is enabled.
> 
> Thanks, no that's not what I want. 😅 Understood, working on it, but trying to find out a way to test the PER_PACKET_LB.

👍 Feel free to ping me on the #datapath or cilium dev channel if you need pointers on testing side of things.

**Comment by oblazek** [comment]
Rebased from master, moved the svcroute package dependency to LNC so that it's accessible from PER_PACKET_LB code easily. Added/updated BPF tests.

File: bpf/bpf_lxc.c [hunk 7]
```diff
@@ -127,14 +127,27 @@ static __always_inline int __per_packet_lb_svc_xlate_4(void *ctx, struct iphdr *
...
-		if (ret == DROP_NO_SERVICE)
-			ret = tail_call_internal(ctx, CILIUM_CALL_IPV4_NO_SERVICE,
-						 ext_err);
+					ret = tail_call_internal(ctx, CILIUM_CALL_IPV4_NO_SERVICE,
+								 ext_err);
 #endif
-
-		if (IS_ERR(ret))
+				}
+			}
```
Comment (aditighag) [inline bpf/bpf_lxc.c]: I think moving this inner nested logic to a helper could improve code readability and reuse. You can invoke the same helper down below in nodeport handling code path.

**Comment by oblazek** [comment]
I squashed one commit, errors should be fixed now.

**Review by aditighag — COMMENTED** [review]
The job checking every commit compiles is failing -- can you take a look?

File: bpf/bpf_lxc.c (hunk 7 above)
Comment (oblazek) [reply bpf/bpf_lxc.c]: sounds good, thanks, will do

Comment (oblazek) [reply bpf/bpf_lxc.c]: done

File: bpf/lib/lb.h [hunk 8]
```diff
@@ -2420,3 +2432,29 @@ __wsum icmp_wsum_accumulate(void *data_start, void *data_end, int sample_len)
...
+{
+	if ((lb4_svc_is_external(svc) &&
+	     (svc->flags & SVC_FLAG_EXT_LOCAL_SCOPE)) ||
+	   (!lb4_svc_is_external(svc) &&
+	    (svc->flags2 & SVC_FLAG_INT_LOCAL_SCOPE))) {
+		return DROP_NO_SERVICE;
+	}
+	/* continue via the slowpath */
+	return CTX_ACT_OK;
+}
```
Comment (aditighag) [inline bpf/lib/lb.h:2447]: Bonus: you can use this helper in bpf_sock as well. The call site at bpf_sock and bpf_lxc can return the appropriate error code.

**Review by aditighag — APPROVED** [review]
Thanks for the revisions, lgtm! Left one more suggestion for code dedup. 
Edit: Since all tests passed, feel free to address this as a follow-up.

**Comment by oblazek** [comment]
As this will conflict with https://github.com/cilium/cilium/pull/40916 which is ready for merge let's wait until that is merged so that I can resolve the conflicts, agreed?

**Review by rgo3 — APPROVED** [review]
LGTM!

**Comment by aditighag** [comment]
@oblazek FYI -- the change is merged.

**Comment by oblazek** [comment]
finishing up the rebase.. will push update soon

**Comment by oblazek** [comment]
BPF checks is failing on unable to find docker image :/

**Comment by joestringer** [comment]
Heads up the context on that failure is in https://github.com/cilium/image-tools/issues/385 .

**Comment by joestringer** [comment]
I believe that the current failure should be resolved if you rebase once more against the tip of `main` branch.

File: pkg/bgpv1/manager/reconcilerv2/service.go [hunk 9]
```diff
@@ -367,13 +371,19 @@ func (r *ServiceReconciler) updateServiceAdvertisementsMetadata(p ReconcileParam
 	r.setMetadata(p.BGPInstance, serviceMetadata)
 }
 
-func hasLocalBackends(p ReconcileParams, fe *loadbalancer.Frontend) bool {
+// hasLocalBackends loops through Frontend backends and returns:
```
Comment (rastislavs) [inline pkg/bgpv1/manager/reconcilerv2/service.go]: Thanks for the patience and update!

One nit: given the func name (hasLocalBackends), I find it a bit confusing that we now return `true, false` when there are no backends at all. I would suggest returning `false, false` in that case, and maybe using named return values to increase readability, e.g.:

```go
func hasBackends(p ReconcileParams, fe *loadbalancer.Frontend) (hasBackends bool, hasLocalBackends bool) {
```

Comment (oblazek) [reply pkg/bgpv1/manager/reconcilerv2/service.go]: sounds good, let me fix that

File: bpf/lib/lb.h (hunk 8 above)
Comment (oblazek) [reply bpf/lib/lb.h:2447]: true, my bad.. though let me do that in a quick follow-up

File: pkg/bgpv1/manager/reconcilerv2/service.go [hunk 10]
```diff
@@ -367,13 +371,22 @@ func (r *ServiceReconciler) updateServiceAdvertisementsMetadata(p ReconcileParam
...
-func hasLocalBackends(p ReconcileParams, fe *loadbalancer.Frontend) bool {
+// hasBackends loops through Frontend backends and returns:
+// 1) true, false - backends > 0, no local backend
+// 2) true, true - backends > 0, at least 1 local backend
+// 3) false, false - no backends, no local backend
+func hasBackends(p ReconcileParams, fe *loadbalancer.Frontend) (hasBackends, hasLocalBackends bool) {
+	n := 0
 	for backend := range fe.Backends {
+		n++
+		hasBackends = true
```
Comment (rastislavs) [inline pkg/bgpv1/manager/reconcilerv2/service.go]: last (very small) nit: we don't seem to need the `n`  counter anymore

Comment (oblazek) [reply pkg/bgpv1/manager/reconcilerv2/service.go]: done

**Comment by oblazek** [comment]
`ci-integration` seems to be failing on `FAIL   │  3.26s   │ github.com/cilium/cilium/pkg/loadbalancer/redirectpolicy`. but that runs normally on localhost :thinking:

**Comment by aditighag** [comment]
> `ci-integration` seems to be failing on `FAIL │ 3.26s │ github.com/cilium/cilium/pkg/loadbalancer/redirectpolicy`. but that runs normally on localhost 🤔

Can you file an issue per the documented steps - https://docs.cilium.io/en/stable/contributing/testing/ci/#id1?

**Comment by aditighag** [comment]
@oblazek FYI -- merging is blocked as there were some unresolved comments. I resolved all of them to unblock merging, including this one as you mentioned addressing that as a follow-up - https://github.com/cilium/cilium/pull/40717#discussion_r2334014566.

**Comment by joestringer** [comment]
@oblazek do you think there's a chance this change might have introduced the following regression? https://github.com/cilium/cilium/issues/45252

**Comment by oblazek** [comment]
> @oblazek do you think there's a chance this change might have introduced the following regression? #45252

Yeah, sure, so we are talking about socketLB. That was kind of the agreement, see this comment https://github.com/cilium/cilium/issues/40438#issuecomment-3071748346. 

>  However, this routing decision should use the internalTrafficPolicy, because this is internal traffic nontheless.

When taking the comment ^ into account, this actually should not use internalTrafficPolicy as that targets the externally facing IP. (https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/)

"externalTrafficPolicy describes how nodes distribute service traffic they receive on one of the Service's "externally-facing" addresses (NodePorts, ExternalIPs, and LoadBalancer IPs)."

**Comment by atykhyy** [comment]
@oblazek That is so, but [Kubernetes documentation](https://kubernetes.io/docs/reference/kubernetes-api/core/service-v1/#ServiceSpec) for `externalTrafficPolicy` also says (in the same paragraph as the sentence you quoted) that
> Note that traffic sent to an External IP or LoadBalancer IP from within the cluster will always get "Cluster" semantics
