### PR TITLE
bpf: update dsr flag properly

### LINKED ISSUE #17759: Some tcp sessions in DSR mode are not SNATed properly
## Bug report

I’m using cilium with dsr mode enabled and Kubernetes service with externalIP. 

The issue is that after receiving SYN packet some SYN-ACK packets (less than 1% but noticeable with 1k+ rps) are not SNATed and leave node with PodIp as source instead of service’s ExternalIp. Restarting service pods (after every pod in deployment is restarted) sometimes temporarily fixes the issue but after some time it appears again. 
TCP options headers in received SYN packets are the same for wrong and right sessions. 
Cilium monitor doesn’t show any problem and I can see both wrong and right SNATed flows there. 
For sessions that are not snated properly there is no record in `cilium bpf nat list` table and no DSR flag in `cilium bpf ct list global` although `tcpdump` shows that every SYN packet from LB node has DSR ipv4 option header
```
$ cilium bpf ct list global | grep 10.81.147.141:8443 | grep -v DSR
TCP IN 10.218.9.136:44002 -> 10.81.147.141:8443 expires=66354 RxPackets=549 RxBytes=45085 RxFlagsSeen=0x1b LastRxReport=44726 TxPackets=964 TxBytes=70612 TxFlagsSeen=0x16 LastTxReport=44754 Flags=0x0010 [ SeenNonSyn ] RevNAT=0 SourceSecurityID=16777697 IfIndex=0
TCP IN 10.218.9.136:43344 -> 10.81.147.141:8443 expires=66354 RxPackets=459 RxBytes=37709 RxFlagsSeen=0x1b LastRxReport=44726 TxPackets=799 TxBytes=58622 TxFlagsSeen=0x16 LastTxReport=44754 Flags=0x0010 [ SeenNonSyn ] RevNAT=0 SourceSecurityID=16777697 IfIndex=0
TCP IN 10.218.9.136:44740 -> 10.81.147.141:8443 expires=66399 RxPackets=464 RxBytes=38127 RxFlagsSeen=0x1b LastRxReport=44782 TxPackets=818 TxBytes=59996 TxFlagsSeen=0x16 LastTxReport=44799 Flags=0x0010 [ SeenNonSyn ] RevNAT=0 SourceSecurityID=16777697 IfIndex=0
TCP IN 10.218.9.136:43144 -> 10.81.147.141:8443 expires=66304 RxPackets=523 RxBytes=42953 RxFlagsSeen=0x1b LastRxReport=44688 TxPackets=903 TxBytes=66202 TxFlagsSeen=0x16 LastTxReport=44704 Flags=0x0010 [ SeenNonSyn ] RevNAT=0 SourceSecurityID=16777697 IfIndex=0
TCP IN 10.218.9.136:43822 -> 10.81.147.141:8443 expires=66226 RxPackets=476 RxBytes=39107 RxFlagsSeen=0x1b LastRxReport=44626 TxPackets=821 TxBytes=60302 TxFlagsSeen=0x16 LastTxReport=44626 Flags=0x0010 [ SeenNonSyn ] RevNAT=0 SourceSecurityID=16777697 IfIndex=0
```
```
$ cilium bpf nat list | grep 44740 | wc -l
0
```
Traffic path from client to pod is
```
Client -> Kubernetes node with bgp announcement of ExternalIp -> Kubernetes node with Pod handling request -> Pod -> Client
```
So there is no way for tcp session to be established directly with application node and create CT entry without DSR flag

CT and NAT maps are far from being full
```
BPF Maps:   dynamic sizing: on (ratio: 0.002500)
  Name                          Size
  Non-TCP connection tracking   296263
  TCP connection tracking       592527
  Endpoint policy               65535
  Events                        16
  IP cache                      512000
  IP masquerading agent         16384
  IPv4 fragmentation            8192
  IPv4 service                  65536
  IPv6 service                  65536
  IPv4 service backend          65536
  IPv6 service backend          65536
  IPv4 service reverse NAT      65536
  IPv6 service reverse NAT      65536
  Metrics                       1024
  NAT                           592527
  Neighbor table                592527
  Global policy                 16384
  Per endpoint policy           65536
  Session affinity              65536
  Signal                        16
  Sockmap                       65535
  Sock reverse NAT              296263
  Tunnel                        65536
```
```
$ cilium bpf nat list | wc -l
36289
$ cilium bpf ct list global | wc -l
47385
```

**General Information**

- Cilium version 1.10.5 b0836e8
- Kernel version 5.4.0-89-generic 
- Orchestration system version in use Kubernetes v1.19.4
```
cilium status --verbose
KVStore:                Ok   Disabled
Kubernetes:             Ok   1.19 (v1.19.4) [linux/amd64]
Kubernetes APIs:        ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1beta1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:   Strict   [eth0 10.213.33.206 (Direct Routing)]
Cilium:                 Ok   1.10.5 (v1.10.5-b0836e8)
NodeMonitor:            Listening for events on 16 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok
IPAM:                   IPv4: 6/254 allocated from 10.81.147.0/24,
Allocated addresses:
  10.81.147.134 (filebeat-system/filebeat-k2x2d)
  10.81.147.141 (istio-system/istio-internal-ingressgateway-0)
  10.81.147.149 (sla-prober-system/sla-prober-daemonset-nmzfp)
  10.81.147.215 (router)
  10.81.147.53 (health)
  10.81.147.99 (kube-system/vsphere-csi-node-wqmtv)
BandwidthManager:       Disabled
Host Routing:           Legacy
Masquerading:           BPF   [eth0]   10.81.128.0/17 [IPv4: Enabled, IPv6: Disabled]
Clock Source for BPF:   ktime
Controller Status:      35/35 healthy
  Name                                  Last success    Last error   Count   Message
  cilium-health-ep                      48s ago         never        0       no error
  dns-garbage-collector-job             57s ago         never        0       no error
  endpoint-1213-regeneration-recovery   never           never        0       no error
  endpoint-1977-regeneration-recovery   never           never        0       no error
  endpoint-2536-regeneration-recovery   never           never        0       no error
  endpoint-2680-regeneration-recovery   never           never        0       no error
  endpoint-284-regeneration-recovery    never           never        0       no error
  endpoint-39-regeneration-recovery     never           never        0       no error
  endpoint-gc                           1m57s ago       never        0       no error
  k8s-heartbeat                         23s ago         never        0       no error
  mark-k8s-node-as-available            12h41m51s ago   never        0       no error
  metricsmap-bpf-prom-sync              7s ago          never        0       no error
  neighbor-table-refresh                1m51s ago       never        0       no error
  resolve-identity-1213                 1m50s ago       never        0       no error
  resolve-identity-1977                 1m50s ago       never        0       no error
  resolve-identity-2536                 1m50s ago       never        0       no error
  resolve-identity-2680                 1m51s ago       never        0       no error
  resolve-identity-284                  1m50s ago       never        0       no error
  resolve-identity-39                   1m50s ago       never        0       no error
  sync-endpoints-and-host-ips           49s ago         never        0       no error
  sync-lb-maps-with-k8s-services        12h41m51s ago   never        0       no error
  sync-policymap-1213                   7s ago          never        0       no error
  sync-policymap-1977                   7s ago          never        0       no error
  sync-policymap-2536                   7s ago          never        0       no error
  sync-policymap-2680                   7s ago          never        0       no error
  sync-policymap-284                    7s ago          never        0       no error
  sync-policymap-39                     7s ago          never        0       no error
  sync-to-k8s-ciliumendpoint (1213)     6s ago          never        0       no error
  sync-to-k8s-ciliumendpoint (1977)     6s ago          never        0       no error
  sync-to-k8s-ciliumendpoint (2536)     6s ago          never        0       no error
  sync-to-k8s-ciliumendpoint (2680)     7s ago          never        0       no error
  sync-to-k8s-ciliumendpoint (284)      7s ago          never        0       no error
  sync-to-k8s-ciliumendpoint (39)       7s ago          never        0       no error
  template-dir-watcher                  never           never        0       no error
  update-k8s-node-annotations           12h41m56s ago   never        0       no error
Proxy Status:   OK, ip 10.81.147.215, 0 redirects active on ports 10000-20000
Hubble:         Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 465.90   Metrics: Ok
KubeProxyReplacement Details:
  Status:                Strict
  Socket LB Protocols:   TCP, UDP
  Devices:               eth0 10.213.33.206 (Direct Routing)
  Mode:                  DSR
  Backend Selection:     Maglev (Table Size: 16381)
  Session Affinity:      Enabled
  XDP Acceleration:      Disabled
  Services:
  - ClusterIP:      Enabled
  - NodePort:       Enabled (Range: 30000-32767)
  - LoadBalancer:   Enabled
  - externalIPs:    Enabled
  - HostPort:       Enabled
BPF Maps:   dynamic sizing: on (ratio: 0.002500)
  Name                          Size
  Non-TCP connection tracking   295822
  TCP connection tracking       591645
  Endpoint policy               65535
  Events                        16
  IP cache                      512000
  IP masquerading agent         16384
  IPv4 fragmentation            8192
  IPv4 service                  65536
  IPv6 service                  65536
  IPv4 service backend          65536
  IPv6 service backend          65536
  IPv4 service reverse NAT      65536
  IPv6 service reverse NAT      65536
  Metrics                       1024
  NAT                           591645
  Neighbor table                591645
  Global policy                 16384
  Per endpoint policy           65536
  Session affinity              65536
  Signal                        16
  Sockmap                       65535
  Sock reverse NAT              295822
  Tunnel                        65536
Encryption:                                                 Disabled
```

### PR DESCRIPTION
**Pull request by Inode1**
I reproduced this [issue](#17759) and after this patch new tcp sessions with dsr flag update the already created entries in the conntrack table.

```release-note
Fix TCP connectivity issues in the DSR mode when conntrack entries with missing DSR flag are reused.
```

Fixes: #17759

### CODE REVIEW

**Comment by Inode1** [comment]
test-1.22-4.19

**Comment by Inode1** [comment]
/test-1.22-4.19

**Comment by Inode1** [comment]
@pchaigno Hello, could you recheck this commit please. IMO, based on the logs of failed tests, I don’t think my PR was the cause of these problems.

File: bpf/bpf_lxc.c [hunk 1]
```diff
@@ -1119,19 +1119,22 @@ ipv6_policy(struct __ctx_buff *ctx, int ifindex, __u32 src_label, __u8 *reason,
...
-	{
+	if (ret == CT_NEW || ret == CT_REOPENED) {
 		bool dsr = false;
 
 		ret = handle_dsr_v6(ctx, &dsr);
 		if (ret != 0)
 			return ret;
 
-		ct_state_new.dsr = dsr;
+		if (ret == CT_NEW)
```
Comment (brb) [inline bpf/bpf_lxc.c]: I would set the dsr flag regardless whether it was `CT_NEW` or `CT_REOPENED`. Otherwise, `ct_state` is not correct wrt to DSR if consumed later in the code.

File: bpf/bpf_lxc.c [hunk 2]
```diff
@@ -1421,19 +1424,22 @@ ipv4_policy(struct __ctx_buff *ctx, int ifindex, __u32 src_label, __u8 *reason,
...
-	{
+	if (ret == CT_NEW || ret == CT_REOPENED) {
 		bool dsr = false;
 
 		ret = handle_dsr_v4(ctx, &dsr);
 		if (ret != 0)
 			return ret;
 
-		ct_state_new.dsr = dsr;
+		if (ret == CT_NEW)
```
Comment (brb) [inline bpf/bpf_lxc.c]: Ditto.

**Review by brb — CHANGES_REQUESTED** [review]
Thanks for the PR!

A few comments. Also, could you improve the commit msg. In particular, it should describe the problem your commit tries to solve, and then briefly discuss the solution.

I've checked the CI failures - all of them are flakes and unrelated to your changes.

File: bpf/bpf_lxc.c (hunk 1 above)
Comment (Inode1) [reply bpf/bpf_lxc.c]: We use `ct_state_new` late in the code only if it's `CT_NEW` state, but if it's  `CT_REOPENED` state, `ct_state_new` is not consumed later in the code. I understand your concern, if you insist I can change it.

**Comment by Inode1** [comment]
@brb, Hello. Here you are, I update the commit msg and describe the problem and discuss the solution.

File: bpf/bpf_lxc.c (hunk 1 above)
Comment (brb) [reply bpf/bpf_lxc.c]: Let's change it.

Comment (Inode1) [reply bpf/bpf_lxc.c]: I rechecked the code and realized that I had overwritten the state:
```		
                ret = handle_dsr_v6(ctx, &dsr);
		if (ret != 0)
			return ret;
```
I fix it up also.

File: bpf/bpf_lxc.c (hunk 2 above)
Comment (Inode1) [reply bpf/bpf_lxc.c]: Done

**Review by brb — APPROVED** [review]

File: bpf/lib/conntrack.h [hunk 3]
```diff
@@ -817,6 +817,19 @@ ct_update6_rev_nat_index(const void *map, const struct ipv6_ct_tuple *tuple,
 	entry->rev_nat_index = state->rev_nat_index;
 }
 
+static __always_inline void
+ct_update6_dsr(const void *map, const struct ipv6_ct_tuple *tuple,
+	       bool dsr)
```
Comment (aditighag) [inline bpf/lib/conntrack.h]:
```suggestion
	       const bool dsr)
```

File: bpf/lib/conntrack.h [hunk 4]
```diff
@@ -911,6 +924,19 @@ ct_update4_rev_nat_index(const void *map, const struct ipv4_ct_tuple *tuple,
 	entry->rev_nat_index = state->rev_nat_index;
 }
 
+static __always_inline void
+ct_update4_dsr(const void *map, const struct ipv4_ct_tuple *tuple,
+	       bool dsr)
```
Comment (aditighag) [inline bpf/lib/conntrack.h]:
```suggestion
	       const bool dsr)
```

**Review by aditighag — CHANGES_REQUESTED** [review]

File: bpf/lib/conntrack.h (hunk 3 above)
Comment (Inode1) [reply bpf/lib/conntrack.h]: i don't mind. Done

File: bpf/lib/conntrack.h (hunk 4 above)
Comment (Inode1) [reply bpf/lib/conntrack.h]: Done

**Review by joamaki — APPROVED** [review]

**Review by aditighag — APPROVED** [review]

**Comment by aditighag** [comment]
4.19 hit a known flake - https://github.com/cilium/cilium/issues/16122. 

I'm filing a bug for gke failure for now.

**Comment by aditighag** [comment]
@Inode1 Can you fix some formatting issues flagged by checkpatch script - https://github.com/cilium/cilium/runs/4449441401?check_suite_focus=true? Thanks!

**Comment by aditighag** [comment]
Also, could you add a [release note](https://docs.cilium.io/en/latest/contributing/development/contributing_guide/) to the commit description?

Example - 

```release-note
Fix TCP connectivity issues in the DSR mode when conntrack entries with missing DSR flag are reused.
```

**Comment by Inode1** [comment]
> @Inode1 Can you fix some formatting issues flagged by checkpatch script - https://github.com/cilium/cilium/runs/4449441401?check_suite_focus=true? Thanks!
> 
> ```
>   Warning: WARNING:LINE_SPACING: Missing a blank line after declarations
>   #33: FILE: bpf/bpf_lxc.c:1127:
>   +		int ret2 = handle_dsr_v6(ctx, &dsr);
>   +		if (ret2 != 0)
>   
>   Warning: WARNING:LINE_SPACING: Missing a blank line after declarations
>   #60: FILE: bpf/bpf_lxc.c:1431:
>   +		int ret2 = handle_dsr_v4(ctx, &dsr);
>   +		if (ret2 != 0)
> ```

Done.

**Review by brb — APPROVED** [review]

**Comment by brb** [comment]
test-gke

**Comment by Inode1** [comment]
@brb, Hello. There are several failed tests, is it somehow connected with my PR? Do you need any help from me?

**Comment by brb** [comment]
The test failures are unrelated (https://github.com/cilium/cilium/issues/18218). Marking as ready to merge.

**Comment by nbusseneau** [comment]
@Inode1 Thanks for your contribution :) Merging the PR.

**Comment by Inode1** [comment]
Thanks, good news.
