### PR TITLE
Don't orphan CEPs when node IPV6 is preferred at dual stack k8s config

### LINKED ISSUE #28139: Cilium can fail to take over ownership of CEP in k8s dual stack cluster with preferred ipv6
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Running cilium in a k8s dual stack cluster with preferred ipv6 (pod hostIP is ipv6)  the agents are reporting orphan CEPs log entries `endpoint sync cannot take ownership of CEP that is not local...` (full log line at `Relevant log output`)

The issue seems to be caused by https://github.com/cilium/cilium/blob/main/pkg/k8s/watchers/endpointsynchronizer.go#L374, due to it's comparing same node ips but from distinct family. The `GetCiliumEndpointNodeIP` function https://github.com/cilium/cilium/blob/main/pkg/node/address.go#L300 , is always returning ipv4 if `EnableIPv4` is set, but this is not always true at k8s dual stack configurations and how pod `status.hostIP` are set by kubelet.  In k8s dual stack clusters, the preference of ipv4 over ipv6 or at the reverse can be set, so the `status.hostIP` set by kubelet at pods may be node ipv4 or ipv6, but the cilium k8s `endpointsynchronizer` watcher is just checking node ipv4.

Proposals for solution:
1. Similar to `HubblePreferIpv6` https://github.com/cilium/cilium/blob/main/pkg/option/config.go#L968 add a new parameter like `preferIpv6`, to allow users to set the ip family preference and update the `GetCiliumEndpointNodeIP` function answering based on the new parameter.
2. Update the `updateCEPUID` function at cilium k8s `endpointsynchronizer`, checking both families node ips before returning the error

### Cilium Version

1.14.1

### Kernel Version

6.1.0

### Kubernetes Version

1.26.6

### Sysdump

_No response_

### Relevant log output

```shell
cilium-agent level=warning msg="could not take ownership of existing ciliumendpoint" containerID=<CONTAINER_ID> controller="sync-to-k8s-ciliumendpoint (710)" datapathPolicyRevision=3 desiredPolicyRevision=3 endpointID=710 error="endpoint sync cannot take ownership of CEP that is not local: CEP's pod \"<POD_NAME>\", pod's hostIP \"<CILIUM_AGENT_IPV6>\", cilium nodeIP \"<CILIUM_AGENT_IPV4>\")" identity=49340 ipv4=<POD_IPV4> ipv6="<POD_IPV6>" k8sPodName=<POD_NAME> subsys=endpointsynchronizer
```
```


### Anything else?

Related to issue https://github.com/cilium/cilium/issues/25094 and PR https://github.com/cilium/cilium/pull/26281



### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rawmind0**
This commit prevents a soft deadlock in the cilium agent on dual stack k8s config with ipv6 preferred by making it check to both ip families CEP's node IPs.

Fixes: #28139

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

Fixes: #28139

### CODE REVIEW

**Comment by rawmind0** [comment]
Branch rebased

**Comment by rawmind0** [comment]
Branch rebased

**Comment by rawmind0** [comment]
Branch rebased

**Comment by rawmind0** [comment]
Branch rebased

**Comment by squeed** [comment]
poke @tommyp1ckles  for review :-)

File: pkg/k8s/watchers/endpointsynchronizer.go [hunk 1]
```diff
@@ -371,9 +370,13 @@ func updateCEPUID(scopedLog *logrus.Entry, e *endpoint.Endpoint, localCEP *ciliu
 	if podHostIP == "" {
 		return fmt.Errorf("endpoint sync cannot take ownership of CEP: no pod HostIP")
 	}
-	if podHostIP != nodeIP {
-		return fmt.Errorf("endpoint sync cannot take ownership of CEP that is not local: CEP's pod %q, pod's hostIP %q, cilium nodeIP %q)",
-			e.GetK8sPodName(), podHostIP, nodeIP)
+	if nodeIP := node.GetCiliumEndpointNodeIP(); podHostIP != nodeIP {
+		// Also checking node ipv6 for k8s dual stack with ipv6 preference where
+		// podHostIP is gonna be node ipv6
+		if nodeIPV6 := node.GetIPv6().String(); podHostIP != nodeIPV6 {
```
Comment (squeed) [inline pkg/k8s/watchers/endpointsynchronizer.go:382]: What happens if the node doesn't have a v6 IP?

File: pkg/k8s/watchers/endpointsynchronizer.go [hunk 2]
```diff
@@ -371,9 +370,13 @@ func updateCEPUID(scopedLog *logrus.Entry, e *endpoint.Endpoint, localCEP *ciliu
 	if podHostIP == "" {
 		return fmt.Errorf("endpoint sync cannot take ownership of CEP: no pod HostIP")
 	}
-	if podHostIP != nodeIP {
-		return fmt.Errorf("endpoint sync cannot take ownership of CEP that is not local: CEP's pod %q, pod's hostIP %q, cilium nodeIP %q)",
-			e.GetK8sPodName(), podHostIP, nodeIP)
+	if nodeIP := node.GetCiliumEndpointNodeIP(); podHostIP != nodeIP {
```
Comment (tommyp1ckles) [inline pkg/k8s/watchers/endpointsynchronizer.go]: Can we use `GetIPv4().String()` instead of `GetCiliumEndpointNodeIP()` to make it more clear what's happening here (if we're going to be checking both ip types)?

Comment (rawmind0) [reply pkg/k8s/watchers/endpointsynchronizer.go]: Sure thing. Rebased and updated

File: pkg/k8s/watchers/endpointsynchronizer.go (hunk 1 above)
Comment (rawmind0) [reply pkg/k8s/watchers/endpointsynchronizer.go:382]: In that case first ipv4 check should match for right CEP or it would be detected as non local, `podHostIP != nodeIPV6`

**Review by tommyp1ckles — APPROVED** [review]

File: pkg/k8s/watchers/endpointsynchronizer.go (hunk 1 above)
Comment (tommyp1ckles) [reply pkg/k8s/watchers/endpointsynchronizer.go:382]: @squeed

**Review by squeed — APPROVED** [review]

**Comment by rawmind0** [comment]
Branch rebased

**Comment by rawmind0** [comment]
Branch rebased
