### PR TITLE
endpoint: Fix the initialization of endpoints' datapath configs

### LINKED ISSUE #13773: CI: `K8sDatapathConfig Encapsulation Check iptables masquerading with random-fully` fails on k8s-all
every build on https://jenkins.cilium.io/job/cilium-master-K8s-all/ fails

```
/home/jenkins/workspace/cilium-master-K8s-all/1.14-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
Pod "testclient-gzk8w" can not connect to "http://google.com"
Expected command: kubectl exec -n 202010260914k8sdatapathconfigencapsulationcheckiptablesmasquera testclient-gzk8w -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 http://google.com -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" --retry 10 
To succeed, but it failed:
Exitcode: 1 
Err: context deadline exceeded
Stdout:
 	 
Stderr:
```

### PR DESCRIPTION
**Pull request by pchaigno**
See commits for details.

Fixes: https://github.com/cilium/cilium/issues/13773.

```release-note
Fix bug where `enable-endpoint-routes` change required all pods to restart to take effect
```

### CODE REVIEW

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
test-1.13-netnext

**Comment by pchaigno** [comment]
test-1.19-4.19

**Comment by pchaigno** [comment]
test-1.19-4.19

**Comment by pchaigno** [comment]
test-1.13-netnext

File: pkg/endpoint/endpoint.go [hunk 1]
```diff
@@ -870,6 +870,28 @@ func parseEndpoint(ctx context.Context, owner regeneration.Owner, bEp []byte) (*
 	return &ep, nil
 }
 
+// NewDatapathConfiguration return the default endpoint datapath configuration
+// based on whether per-endpoint routes are enabled.
+func NewDatapathConfiguration() models.EndpointDatapathConfiguration {
```
Comment (gandro) [inline pkg/endpoint/endpoint.go:876]: nit: Is there a reason we don't just return a `*models.EndpointDatapathConfiguration`? No caller seems to use it by value and returning pointers to `models.` types is a very common pattern in Cilium.

Comment (pchaigno) [reply pkg/endpoint/endpoint.go:876]: `parseEndpoint` and `CreateHostEndpoint` use it by value. Should I still change and dereference for those callers? :-/

Comment (gandro) [reply pkg/endpoint/endpoint.go:876]: Ah, I missed that! In that case let's leave it as is.

**Comment by pchaigno** [comment]
test-me-please

**Review by gandro — APPROVED** [review]
The health related change looks good to me!

I also didn't spot any obvious defects in the rest of the code, but I'm not familiar enough with the datapath.

**Review by aanm — APPROVED** [review]

File: pkg/datapath/loader/loader.go [hunk 2]
```diff
@@ -342,16 +342,27 @@ func (l *Loader) reloadDatapath(ctx context.Context, ep datapath.Endpoint, dirs
...
+			err := RemoveTCFilters(ep.InterfaceName(), netlink.HANDLE_MIN_EGRESS)
+			if err != nil {
+				log.WithField("device", ep.InterfaceName()).Error(err)
+			}
 		}
 	}
 
-	if ep.RequireEndpointRoute() {
-		if ip := ep.IPv4Address(); ip.IsSet() {
+	if ip := ep.IPv4Address(); ip.IsSet() {
```
Comment (qmonnet) [inline pkg/datapath/loader/loader.go:353]: What is the motivation for reordering the conditions?

**Review by qmonnet — APPROVED** [review]

File: pkg/datapath/loader/loader.go (hunk 2 above)
Comment (pchaigno) [reply pkg/datapath/loader/loader.go:353]: No strong motivation. I guess it made more sense that way to me. Happy to change it back if others disagree.

**Review by joestringer — CHANGES_REQUESTED** [review]
I think that this is potentially breaking modes where the cilium-cni specifies datapath configuration options to the cilium-agent, thread below.

File: daemon/cmd/endpoint.go [hunk 3]
```diff
@@ -306,25 +306,8 @@ func (m *endpointCreationManager) DebugStatus() (output string) {
...
-		// cilium_host interface is bypassed
-		epTemplate.DatapathConfiguration.RequireEgressProg = true
-
-		// Delegate routing to the Linux stack rather than tail-calling
-		// between BPF programs.
-		disabled := false
-		epTemplate.DatapathConfiguration.RequireRouting = &disabled
-	}
+	dpConfig := endpoint.NewDatapathConfiguration()
+	epTemplate.DatapathConfiguration = &dpConfig
```
Comment (joestringer) [inline daemon/cmd/endpoint.go]: The previous code here would override *some* fields in the `models.EndpointDatapathConfiguration` object passed from the cilium-cni, but the new version just creates the datapath configuration from scratch. Was this intentional?

Comment (pchaigno) [reply daemon/cmd/endpoint.go]: Ouch, yes. You are correct and generic-veth uses those other fields.

**Comment by pchaigno** [comment]
test-me-please

**Review by christarazi — APPROVED** [review]

File: daemon/cmd/endpoint.go [hunk 4]
```diff
@@ -306,26 +306,32 @@ func (m *endpointCreationManager) DebugStatus() (output string) {
...
-		epTemplate.DatapathConfiguration.RequireEgressProg = true
-
-		// Delegate routing to the Linux stack rather than tail-calling
-		// between BPF programs.
-		disabled := false
-		epTemplate.DatapathConfiguration.RequireRouting = &disabled
 	}
 
+	dpConfig := endpoint.NewDatapathConfiguration()
+	epTemplate.DatapathConfiguration = &dpConfig
```
Comment (joestringer) [inline daemon/cmd/endpoint.go]: This is still overriding the configuration provided by cilium-cni right?

**Review by joestringer — CHANGES_REQUESTED** [review]

File: daemon/cmd/endpoint.go (hunk 4 above)
Comment (pchaigno) [reply daemon/cmd/endpoint.go]: :facepalm: that's a leftover from copy/paste while fixing the above. Fixed now. Sorry about that.

**Comment by pchaigno** [comment]
test-me-please

File: pkg/datapath/loader/loader.go [hunk 5]
```diff
@@ -342,16 +342,27 @@ func (l *Loader) reloadDatapath(ctx context.Context, ep datapath.Endpoint, dirs
...
+		if ep.RequireEndpointRoute() {
 			upsertEndpointRoute(ep, *ip.IPNet(32))
+		} else {
+			removeEndpointRoute(ep, *ip.IPNet(32))
```
Comment (joestringer) [inline pkg/datapath/loader/loader.go:357]: nit: Apparently we've just been ignoring errors here. For the remove case it may be run when there is no underlying route so at least for the "ENOENT" type errors we should not be logging. But seems like we should follow up to make sure we don't just hide errors here..

File: pkg/endpoint/endpoint.go [hunk 6]
```diff
@@ -489,9 +489,7 @@ func CreateHostEndpoint(owner regeneration.Owner, proxy EndpointProxy, allocator
 	ep := createEndpoint(owner, proxy, allocator, 0, ifName)
 	ep.isHost = true
 	ep.nodeMAC = mac
-	ep.DatapathConfiguration = models.EndpointDatapathConfiguration{
-		RequireEgressProg: true,
-	}
+	ep.DatapathConfiguration = NewDatapathConfiguration()
```
Comment (joestringer) [inline pkg/endpoint/endpoint.go:492]: Previously this hardcoded `RequireEgressProg: true` for the host, but with the new option this will only be the case when `config.EnableEndpointRoutes` is true. Do we need to take a second look at host endpoint + no endpoint routes?

**Review by joestringer — APPROVED** [review]
My previous concerns have been addressed. I have another couple of nits to follow up on but I don't think that they necessarily need to be solved in this PR, up to you @pchaigno .

File: pkg/endpoint/endpoint.go (hunk 6 above)
Comment (pchaigno) [reply pkg/endpoint/endpoint.go:492]: Nice catch! I checked that case already, but should have added a note in the commit.

The host endpoint actually ignores `RequireEgressProg` and attaches to both ingress and egress (cf. `reloadHostDatapath()`). I'm setting it here just for consistency with other endpoints, but you could argue it should be true just to be consistent with the datapath state. I don't have a strong opinion either way.

File: pkg/datapath/loader/loader.go (hunk 5 above)
Comment (pchaigno) [reply pkg/datapath/loader/loader.go:357]: I opened `good-first-issue` https://github.com/cilium/cilium/issues/15282 for it. I'll address it if noone takes it.

File: pkg/endpoint/endpoint.go (hunk 6 above)
Comment (joestringer) [reply pkg/endpoint/endpoint.go:492]: In that case I'm not too worried about it, one could argue that the `RequireEgressProg` semantics is specific to managed endpoints rather than hosts.

File: daemon/cmd/endpoint.go [hunk 7]
```diff
@@ -306,24 +306,20 @@ func (m *endpointCreationManager) DebugStatus() (output string) {
 // createEndpoint attempts to create the endpoint corresponding to the change
 // request that was specified.
 func (d *Daemon) createEndpoint(ctx context.Context, owner regeneration.Owner, epTemplate *models.EndpointChangeRequest) (*endpoint.Endpoint, int, error) {
-	if option.Config.EnableEndpointRoutes {
-		if epTemplate.DatapathConfiguration == nil {
-			epTemplate.DatapathConfiguration = &models.EndpointDatapathConfiguration{}
+	if epTemplate.DatapathConfiguration == nil {
+		dpConfig := endpoint.NewDatapathConfiguration()
+		epTemplate.DatapathConfiguration = &dpConfig
+	} else {
```
Comment (joestringer) [inline daemon/cmd/endpoint.go:312]: Doesn't this mean that endpoint routes mode is only ever applied if the caller specifies the `epTemplate.DatapathConfiguration`? Why isn't this broken?

Comment (pchaigno) [reply daemon/cmd/endpoint.go:312]: Yes, that's my understanding as well :thinking: 

Not sure why it doesn't break in tests. I've set a reminder to look tomorrow (or at least open an issue if I don't get time to debug).

Comment (pchaigno) [reply daemon/cmd/endpoint.go:312]: I'm still unsure why it's not breaking anything in CI. I suspected that maybe we never received nil `epTemplate.DatapathConfiguration`s but checked the client's code and we should receive it. I even went so far as to [reproduce the marshalling bits](https://play.golang.org/p/T-IGW5Nt7UH) to double check it doesn't turn nil into an empty structure. It doesn't.

If we were hitting this, the agent would consider endpoint routes to be disabled for all new endpoints added via the API AFAICS. Looking at a couple tests with endpoint routes enabled, that's clearly not the case (I see the expected routes and BPF programs).

It's still a bug so I'll send a PR to fix, but we're missing something here :thinking:
