### PR TITLE
identity: cache: close channel in writing party

### LINKED ISSUE #25235: CI: daemon/cmd test panic'ed in TravisCI
## CI failure

Hit in https://github.com/cilium/cilium/pull/25221: ~~https://app.travis-ci.com/github/cilium/cilium/builds/262730618#L637-L657~~ (apparently the logs have been overwritten after restarting the job).

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━���━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                                                                                                  
┃   PANIC  package: github.com/cilium/cilium/daemon/cmd • Test   ┃                                                                                                  
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛                                                                                                  

panic: send on closed channel                                                                                                                                       

goroutine 787 [running]:                                                                                                                                            
github.com/cilium/cilium/pkg/identity/cache.(*localIdentityCache).lookupOrCreate(0x4001e2a3c0, 0x4000928930, 0x0?)                                                  
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/identity/cache/local.go:109 +0x438                                                                             
github.com/cilium/cilium/pkg/identity/cache.(*CachingIdentityAllocator).AllocateIdentity(0x4001a4b2c0, {0x3425ef8, 0x4000252500}, 0x4000928930, 0x80?, 0x40?)       
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/identity/cache/allocator.go:339 +0x55c                                                                         
github.com/cilium/cilium/pkg/ipcache.(*IPCache).resolveIdentity(0x40005bfe00, {0x3425ef8, 0x4000252500}, {{{0x400254efc0?, 0x0?}, 0x4000114030?}, 0x0?}, 0x0?, 0x0?)
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/ipcache/metadata.go:436 +0xb24                                                                                 
github.com/cilium/cilium/pkg/ipcache.(*IPCache).InjectLabels(0x40005bfe00, {0x3425ef8, 0x4000252500}, {0x400092e9c0, 0x3, 0x3})                                     
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/ipcache/metadata.go:197 +0x4a8                                                                                 
github.com/cilium/cilium/pkg/ipcache.(*IPCache).TriggerLabelInjection.func1({0x3425ef8, 0x4000252500})                                                              
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/ipcache/metadata.go:547 +0x50                                                                                  
github.com/cilium/cilium/pkg/controller.(*Controller).runController(0x4000bbe120)                                                                                   
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/controller/controller.go:216 +0x1f0                                                                           
created by github.com/cilium/cilium/pkg/controller.(*Manager).updateController                                                                                      
	/home/travis/gopath/src/github.com/cilium/cilium/pkg/controller/manager.go:111 +0x8e8                                                                               
FAIL	github.com/cilium/cilium/daemon/cmd	12.711s
```

### PR DESCRIPTION
**Pull request by bimmlerd**
As part of the shutdown procedure involving IPCache and the identity allocation components, it was possible to hit a 'write on closed channel' panic, caused by writes of the localIdentityCache to the events channel, which is closed as part of the shutdown of the identity allocator.

Instead of directly closing the channel, call into the localIdentityCache (the only writer) to do so, with proper mutual exclusion guaranteed by the mutex.

The offending writes happened in `lookupOrCreate` as well as `release`, both of which take the mutex, and hence are correctly synchronised with the new `close()` method.

Fixes: #25235

Since this affects the shutdown procedure, I believe this not to impact actual cilium deployments, merely our integration tests; hence `release-note/misc`.

### CODE REVIEW

**Comment by bimmlerd** [comment]
CI triage:
- Travis CI hit https://github.com/cilium/cilium/issues/25272
- ConformanceGatewayAPI / gateway-api-conformance-test failed with something new seemingly

```
=== RUN   TestConformance/TLSRouteSimpleSameNamespace
    suite.go:258: Applying tests/tlsroute-simple-same-namespace.yaml
    apply.go:211: Creating gateway-conformance-infra-test TLSRoute
    apply.go:211: Creating gateway-tlsroute Gateway
    helpers.go:290: Gateway expected observedGeneration to be updated for all conditions, only 0/1 were updated. stale conditions are: Accepted
    helpers.go:441: Accepted condition set to Status False with Reason InvalidTLSRoute, expected Status True
    helpers.go:441: Accepted was not in conditions list [[{Accepted False 1 2023-05-10 12:36:01 +0000 UTC InvalidTLSRoute Gateway.gateway.networking.k8s.io "gateway-tlsroute" not found}]]
    helpers.go:441: Accepted condition set to Status False with Reason InvalidTLSRoute, expected Status True
    helpers.go:441: Accepted was not in conditions list [[{Accepted False 1 2023-05-10 12:36:01 +0000 UTC InvalidTLSRoute Gateway.gateway.networking.k8s.io "gateway-tlsroute" not found}]]
    helpers.go:441: Accepted condition set to Status False with Reason InvalidTLSRoute, expected Status True
    [SNIP, lots of repetition]
    helpers.go:441: Accepted was not in conditions list [[{Accepted False 1 2023-05-10 12:36:01 +0000 UTC InvalidTLSRoute Gateway.gateway.networking.k8s.io "gateway-tlsroute" not found}]]
    helpers.go:441: Accepted condition set to Status False with Reason InvalidTLSRoute, expected Status True
    helpers.go:441: Accepted was not in conditions list [[{Accepted False 1 2023-05-10 12:36:01 +0000 UTC InvalidTLSRoute Gateway.gateway.networking.k8s.io "gateway-tlsroute" not found}]]
    tlsroute-simple-same-namespace.go:51: 
        	Error Trace:	/home/runner/work/cilium/cilium/vendor/sigs.k8s.io/gateway-api/conformance/utils/kubernetes/helpers.go:445
        	            				/home/runner/work/cilium/cilium/vendor/sigs.k8s.io/gateway-api/conformance/utils/kubernetes/helpers.go:606
        	            				/home/runner/work/cilium/cilium/vendor/sigs.k8s.io/gateway-api/conformance/tests/tlsroute-simple-same-namespace.go:51
        	            				/home/runner/work/cilium/cilium/vendor/sigs.k8s.io/gateway-api/conformance/utils/suite/suite.go:262
        	            				/home/runner/work/cilium/cilium/vendor/sigs.k8s.io/gateway-api/conformance/utils/suite/suite.go:220
        	Error:      	Received unexpected error:
        	            	timed out waiting for the condition
        	Test:       	TestConformance/TLSRouteSimpleSameNamespace
        	Messages:   	error waiting for TLSRoute to have parents matching expectations
    apply.go:219: Deleting gateway-tlsroute Gateway
    apply.go:219: Deleting gateway-conformance-infra-test TLSRoute


     --- FAIL: TestConformance/TLSRouteSimpleSameNamespace (61.07s)
FAIL
FAIL	github.com/cilium/cilium/operator/pkg/gateway-api	117.095s
FAIL
```

rerunning to see if it's flaky or just broken by me

File: pkg/identity/cache/local.go [hunk 1]
```diff
@@ -191,3 +191,15 @@ func (l *localIdentityCache) GetIdentities() map[identity.NumericIdentity]*ident
...
+
+// close closes the events channel. Since the local identity cache is the
+// writing party, it is responsible for closing the channel.
+func (l *localIdentityCache) close() {
+	l.mutex.Lock()
+	defer l.mutex.Unlock()
+
+	if l.events != nil {
+		close(l.events)
+		l.events = nil
```
Comment (gandro) [inline pkg/identity/cache/local.go:203]: If we set `l.events` to nil (which is different variable compared to removed `m.events` above), we will have to guard all uses of `l.events` in `localIdentityCache` with an `if m.events != nil` statement, otherwise the send statements that previously paniced after close will now block forever.

File: pkg/identity/cache/allocator.go [hunk 2]
```diff
@@ -273,7 +273,9 @@ func (m *CachingIdentityAllocator) Close() {
 
 	m.IdentityAllocator.Delete()
 	if m.events != nil {
-		close(m.events)
```
Comment (gandro) [inline pkg/identity/cache/allocator.go:276]: nit: Since we don't close `m.events` anymore, could we make `type AllocatorEventChan chan AllocatorEvent` into `type AllocatorEventChan chan <-AllocatorEvent` to disallow any code from accidentally closing it?

You might will to change the signature of `newLocalIdentityCache`, but all other receivers should hopefully be fine with a receive-only channel.

**Review by gandro — CHANGES_REQUESTED** [review]
Thanks! One nit and one potentially blocking issue.

File: pkg/identity/cache/local.go (hunk 1 above)
Comment (bimmlerd) [reply pkg/identity/cache/local.go:203]: This is already the case (afaict, the only two writes are `lookupOrCreate` and `release`). `events` is nil in most of the tests.

**Review by tommyp1ckles — APPROVED** [review]

File: pkg/identity/cache/local.go (hunk 1 above)
Comment (gandro) [reply pkg/identity/cache/local.go:203]: Oh, apologies, I missed that!

**Review by gandro — APPROVED** [review]

File: pkg/identity/cache/allocator.go (hunk 2 above)
Comment (bimmlerd) [reply pkg/identity/cache/allocator.go:276]: Hmm this is actually a bit more involved than I though - looking into other uses of that type.

**Comment by bimmlerd** [comment]
I've redone the PR somewhat, to try to implement Sebastian's suggestion of encoding who writes/reads from the channel in the type system. It's a bit messy, however, since the caching identity allocator needs to pass it's channel on to the actual allocator, hence needs to maintain both a recv/send variant of the same channel (or a bidirectional reference, hence losing the type safety). I'm on the fence in terms of which variant is better, feedback welcome.

File: pkg/identity/cache/allocator.go [hunk 3]
```diff
@@ -49,8 +49,12 @@ type CachingIdentityAllocator struct {
 
 	identitiesPath string
 
-	events  allocator.AllocatorEventChan
-	watcher identityWatcher
+	// We maintain both a send- and receive-only channel to encode what
+	// operations are allowed in the type system. These must point to the same
+	// underlying channel.
+	eventsRecv allocator.AllocatorEventRecvChan
+	eventsSend allocator.AllocatorEventSendChan
```
Comment (gandro) [inline pkg/identity/cache/allocator.go]: Honestly, I think I'd just stick to the generic type here and leave a comment that only senders are allowed to close it.

```suggestion
	//  This field exists is to hand out references that are either for sending and receiving.
	// It should not be used directly without converting it first to a allocator.AllocatorEventSendChan
	// or allocator.AllocatorEventRecvChan.
	events allocator.AllocatorEventChan
```

**Review by gandro — APPROVED** [review]
Awesome, thanks!

File: pkg/identity/cache/allocator.go (hunk 3 above)
Comment (bimmlerd) [reply pkg/identity/cache/allocator.go]: yeah, fair. done

**Comment by bimmlerd** [comment]
CI triage
- ci-multicluster
```
Errors: 1 pods of DaemonSet cilium are not ready
Warnings:         cilium             cilium-tq5q9    pod is pending

Error: Unable to install Cilium: timeout while waiting for status to become successful: context deadline exceeded
```

Didn't really find anything interesting; in the k8s events there's some references to the node not being ready. No logs, cilium's init containers didn't even run.

File: pkg/identity/cache/allocator.go [hunk 4]
```diff
@@ -49,6 +49,9 @@ type CachingIdentityAllocator struct {
 
 	identitiesPath string
 
+	// This field exists is to hand out references that are either for sending
```
Comment (giorio94) [inline pkg/identity/cache/allocator.go:52]:
```suggestion
	// This field exists to hand out references that are either for sending
```

Nit.

File: pkg/identity/cache/allocator.go [hunk 5]
```diff
@@ -273,7 +276,9 @@ func (m *CachingIdentityAllocator) Close() {
 
 	m.IdentityAllocator.Delete()
 	if m.events != nil {
-		close(m.events)
+		// Have the now only remaining writing party close the events channel,
+		// to ensure we don't panic with 'send on closed channel'.
```
Comment (giorio94) [inline pkg/identity/cache/allocator.go:280]: I'm not confident that this statement is guaranteed to be true in a clustermesh scenario. The events channel is also [propagated to remote watchers](https://github.com/cilium/cilium/blob/main/pkg/identity/cache/allocator.go#L465), which might still be running when the main allocator is closed (the clustermesh subsystem is never stopped on shutdown). Likely not a big deal though, since that should be extremely rare and we are already shutting down. For this reason I wonder if it is something actually worth solving it in this PR (it might be quite complex to fix).

**Review by giorio94 — APPROVED** [review]
One minor concern inline, but I feel that it might be also left as a followup, as it will like require some refactoring around clustermesh.

**Review by nebril — APPROVED** [review]

File: pkg/identity/cache/allocator.go (hunk 5 above)
Comment (bimmlerd) [reply pkg/identity/cache/allocator.go:280]: Yeah, you're right, that's still broken. 

It's kind of unclear to me what the ownership relations are in the clustermesh scenario. Does a `m.IdentityAllocator` own its remote caches (and hence, should `Allocator.Delete()` call `.Close()` on them)?

Comment (giorio94) [reply pkg/identity/cache/allocator.go:280]: Currently the cache corresponding to a given remote cluster is closed [here](https://github.com/cilium/cilium/blob/9534fbdd8e3fa8bed5b24ec4d990a2c951467bec/pkg/clustermesh/remote_cluster.go#L150), which happens when the associated cluster configuration is removed, but is not triggered when the agent is shut down.

The two possible alternatives seem to be either ensuring that the clustermesh subsystem is stopped before the allocator is closed, or making sure that  `m.IdentityAllocator` stops also the remote caches when closed. I'm not sure how the first approach plays with the current structure, given that clustermesh has not yet been converted to a Cell module. The second approach instead requires to protect `RemoteCache.Close()` from being called twice, as it would panic.

> Does a m.IdentityAllocator own its remote caches?

I would tend to say so, since a remote cache is pointless to exist without the main allocator (but their lifecycle is currently managed externally).
