### PR TITLE
ipsec: Fix unencrypted traffic when IPsec is used with L7 egress proxy

### LINKED ISSUE #31984: Unencrypted traffic among nodes when IPsec is used with L7 egress proxy
Security advisory: https://github.com/cilium/cilium/security/advisories/GHSA-j89h-qrvr-xc36

Previous PRs (#29530, #29594, #30095) addressed the vulnerabilities for IPsec and L7 ingress proxy, this issue is opened for IPsec and L7 **egress** proxy.

## Initial Attempts 

In the first place we tried to simply add an ip rule for from-egress-proxy traffic, just like what we did at https://github.com/cilium/cilium/pull/29530/commits/bca5f075b795bc9bc29a7500bf7ce5a533dc8e19, which added an ip rule for from-ingress-proxy traffic. This commit (https://github.com/cilium/cilium/pull/31980/commits/1c97de7da4c93ef228574e145fdb57cd9ec53a34) implemented the idea, 

However, it has turned out to be not enough. We realized iptables also needs to be taken care of, so the second commit (https://github.com/cilium/cilium/pull/31980/commits/1b5e7d6e777e77b1bf77fbb8881dd4178fcdecd7) followed. Please see the commit message for reasons.

After above two patches, ci-ipsec-e2e seemed to be happy, even with leak detection, but ci-ipsec-upgrade turned broken badly. We found the failure happened during downgrade from, say, 1.15-patched to 1.14-tip (minor downgrade). 1.15-patches will install the new from-egress-proxy rule + new iptables rule; after downgrade to 1.14-tip, the new iptables rule is cleaned up, but the new from-egress-proxy rule is left over, because the old 1.14-tip doesn't recognise from-egress-rule at all. The stale ip rule messed up.

To handle rules carefully without breaking downgrade, I propose the two-stage patches as followed.

### Stage one

We will have to merge the following PRs:

- [x] #31923 
- [x] #31922 
- [x] #31926 
- [x] #31928 
- [ ] #31930 (Closed as commented at https://github.com/cilium/cilium/pull/31930#issuecomment-2126383055)

These PRs are doing a simple thing: remove from-egress-proxy rule, even they doesn't install the rule. The rule is probably installed by higher version of cilium.

### Stage two

After PRs in stage one are all merged into stable branches and released in weeks, we can proceed with the following PRs:

- [ ] ~~#31955~~
- [ ] https://github.com/cilium/cilium/pull/32683 
- [ ] ~~#31975~~ 
- [ ] https://github.com/cilium/cilium/pull/32932
- [ ] #31976 
- [ ] #31977 

Right now they consists of two commits described in "Initial Attempts" section, plus "manually specify downgrade version", plus leak detection CI checks. I will clean up the PRs once ready, for now the leak detection patches and "manually specify" patch are temporarily added to demonstrate the solution works. We have noted that ci-ipsec-upgrade and ci-ipsec-e2e are mostly in green status.

## Outstanding issues

Leak detection check sometimes failes at the very end of ci-ipsec-e2e. The latest speculation is it's caused by conn-disrupt pods deletion.

If conn-disrupt-server is deleted with its ipcache entry, but an skb holding conn-disrupt-client -> conn-disrupt-server already gets emitted, then this skb at from_host@cilium_host won't be marked as need-ipsec-encryption (0xe00) due to ipcache entry missing. bpftrace wil then catch it.

Right now there is no obvious solution (if the theory turns out to be correct). We will move forward and discuss it later.

### PR DESCRIPTION
**Pull request by jschwinger233**
This PR fixes unencrypted traffic among nodes when IPsec is used with L7 egress proxy.

This PR supersedes #31955 that didn't take https://github.com/cilium/proxy/pull/742 into consideration.

(The last three patches are temporarily added to run leak detection in CI, they'll be dropped after approval. Leak detection will be added separately soon.)

Fixes:  #31984

```release-note
Fixes unencrypted traffic among nodes when IPsec is used with L7 egress proxy.
```

### CODE REVIEW

**Comment by jschwinger233** [comment]
Maybe even the first 2 patches are also not needed? Will try later.

File: bpf/bpf_host.c [hunk 1]
```diff
@@ -400,6 +400,12 @@ handle_ipv6_cont(struct __ctx_buff *ctx, __u32 secctx, const bool from_host,
 					 info->sec_identity, true, false);
```
Comment (pchaigno) [inline bpf/bpf_host.c:400]: *(On first commit description.)*

We might want to avoid the use of @somerandomstring or everyone with a matching GitHub account will receive a notification every time this commit is pushed somewhere :sweat_smile: 

Very nice commit description however!

File: bpf/bpf_host.c [hunk 2]
```diff
@@ -400,6 +400,12 @@ handle_ipv6_cont(struct __ctx_buff *ctx, __u32 secctx, const bool from_host,
...
 #endif
 
+#if defined(ENABLE_IPSEC)
+	if (from_proxy &&
+	    (!info || !identity_is_cluster(info->sec_identity)))
+		ctx->mark = MARK_MAGIC_PROXY_TO_WORLD;
+#endif /* ENABLE_IPSEC */
+
```
Comment (pchaigno) [inline bpf/bpf_host.c:406]: Couldn't we set this mark directly at bpf_lxc so that pod-to-world packets have the same magic mark end-to-end? I fear that having magic marks that are only used on part of packet paths will make the readability of packet paths worth.

File: pkg/proxy/proxy.go [hunk 3]
```diff
@@ -430,36 +429,35 @@ func (p *Proxy) ReinstallRoutingRules() error {
...
 
 	return nil
 }
 
-func requireFromProxyRoutes() bool {
-	return (option.Config.EnableEnvoyConfig || option.Config.EnableIPSec) && !option.Config.TunnelingEnabled()
+func requireFromProxyRoutes() (fromIngressProxy, fromEgressProxy bool) {
+	fromIngressProxy = (option.Config.EnableEnvoyConfig || option.Config.EnableIPSec) && !option.Config.TunnelingEnabled()
+	fromEgressProxy = option.Config.EnableIPSec && !option.Config.TunnelingEnabled()
+	return
```
Comment (pchaigno) [inline pkg/proxy/proxy.go:460]: I'm still a bit bugged by this. IIUC, removing the IPsec condition here causes the CI to fail. So it breaks something when IPsec is disabled, but we should trust IPsec fixes it? It would be the first time IPsec fixes something :sweat_smile:

File: .github/actions/bpftrace/start/action.yaml [hunk 4]
```diff
@@ -24,8 +24,11 @@ runs:
             # bpftrace v0.20.1 doesn't seem to play well with Linux 4.19
             # https://github.com/bpftrace/bpftrace/issues/3011
             # Let's buy us some time, and keep installing v0.19.1 for the moment.
-            echo 'deb http://deb.debian.org/debian trixie main' >> /etc/apt/sources.list
-            apt update && apt install -y bpftrace -t trixie
+
+            curl -L https://github.com/bpftrace/bpftrace/releases/download/v0.19.1/bpftrace -o bpftrace
+            install -m 755 bpftrace /usr/local/bin/bpftrace
+
+            # apt update && apt install -y bpftrace
```
Comment (pchaigno) [inline .github/actions/bpftrace/start/action.yaml]: Should we remove this?

**Review by pchaigno — COMMENTED** [review]
The nice commit history makes it easy to follow, as always :pray:

File: bpf/bpf_host.c (hunk 2 above)
Comment (jschwinger233) [reply bpf/bpf_host.c:406]: bpf_lxc has already set 0x200 mark to the pod2world skb in the case of proxy hijack, I'm afraid of mark conflict. 

What's worse is the skb at lxc is not the one having trouble at iptables PREROUTING: the former one will be consumed by proxy process, then proxy sends to world a new skb, the one which we want to teach iptables not to set 0x200 mark on.

File: .github/actions/bpftrace/start/action.yaml (hunk 4 above)
Comment (jschwinger233) [reply .github/actions/bpftrace/start/action.yaml]: Yeah! I'll improve the leak detection yamls in a separate PR. This PR will drop the last three patches before merge.

File: pkg/proxy/proxy.go (hunk 3 above)
Comment (jschwinger233) [reply pkg/proxy/proxy.go:460]: :laughing: Actually, the complete storyline is:
1. https://github.com/cilium/cilium/pull/29530 installs `0xa00 lookup 2005` when `ipsec=on`
2. https://github.com/cilium/cilium/pull/32367 extends the condition of installing above routing to `envoy=on || ipsec=on`
3. this pr wants to install a new routing `0xb00 lookup 2005`. If we keep using the condition `envoy=on || ipsec=on`, the new routing will also be installed when envoy=on && ipsec=off, but some errors in ci-e2e (non-ipsec) were seen.  Therefore I decide to limit the new routing to ipsec only, here we are, two different conditions.

Comment (pchaigno) [reply pkg/proxy/proxy.go:460]: I was mostly wondering if we can make this code become:
```go
fromEgressProxy = !option.Config.TunnelingEnabled()
```
Or even just:
```go
fromEgressProxy = true
```
:sweat_smile: 

But I guess then we'd pay the price of one more redirect per packet so it's probably not worth it...

**Review by pchaigno — APPROVED** [review]

File: bpf/bpf_host.c (hunk 1 above)
Comment (jschwinger233) [reply bpf/bpf_host.c:400]: I'll amend the commit message after getting more reviews, thank you Paul!

File: bpf/bpf_host.c [hunk 5]
```diff
@@ -856,6 +862,12 @@ handle_ipv4_cont(struct __ctx_buff *ctx, __u32 secctx, const bool from_host,
...
 	return CTX_ACT_OK;
```
Comment (julianwiedmann) [inline bpf/bpf_host.c]: For my understanding - we *could* limit this to `native-routing` (and fold it into the code section above), as we don't install the `0xb00/0xf00 lookup 2005` rule otherwise. Correct?

File: pkg/proxy/proxy.go (hunk 3 above)
Comment (julianwiedmann) [reply pkg/proxy/proxy.go:460]: I think we're definitely due for a wider re-design of the via-proxy traffic paths, to eliminate all the current special cases. Maybe introduce IPsec logic in `to-netdev` instead, and not rely on `bpf_host` so much?

But that's most likely not backport-able, and it's been tricky enough just to get *this* part working :grimacing:.

**Review by julianwiedmann — COMMENTED** [review]
Just one clarification, otherwise looks as expected :+1:. Thank you Gray!

**Review by julianwiedmann — APPROVED** [review]
:rocket:

**Comment by jschwinger233** [comment]
CI checks are almost green:
image

Except ci-ipsec-e2e: https://github.com/cilium/cilium/actions/runs/9348861747
The above failure is a known issue due to the race condition of leak detection, that will be fixed soon. 

Leak detection is a non-goal in this PR, I'll drop the last three commits:
- conformance-ipsec-e2e: add leaked unencrypted packets check
- bpftrace: install from release instead that using apt
- conformance-ipsec-e2e: run leak check before/after key rotation

**Review by jrajahalme — APPROVED** [review]
LGTM.

Should the backporters note that release branches must pick up `cilium/proxy` with backport of https://github.com/cilium/proxy/pull/742 before backporting this? Or does this work correctly even if `cilium-envoy` does not have https://github.com/cilium/proxy/pull/742?

File: bpf/bpf_host.c [hunk 6]
```diff
@@ -854,7 +858,11 @@ handle_ipv4_cont(struct __ctx_buff *ctx, __u32 secctx, const bool from_host,
 	if (from_proxy && info->tunnel_endpoint && encrypt_key)
 		return set_ipsec_encrypt(ctx, encrypt_key, info->tunnel_endpoint,
 					 info->sec_identity, true, false);
-#endif
+
+	if (from_proxy &&
+	    (!info || !identity_is_cluster(info->sec_identity)))
+		ctx->mark = MARK_MAGIC_PROXY_TO_WORLD;
+#endif /* ENABLE_IPSEC && !TUNNEL_MODE */
```
Comment (julianwiedmann) [inline bpf/bpf_host.c:865]: @jschwinger233 coming back to this - I only now realized that https://github.com/cilium/cilium/issues/36329 also applies here, and the mark potentially gets scrubbed on the transfer between `cilium_host` and `cilium_net`. Which is why we're still setting `use_meta=true` in the `set_ipsec_encrypt()` call above.

So I suppose this mark works well as mechanism to skip the transparent-socket match in iptables - but we can't really trust yet that it also survives until `cilium_net` (or a subsequent `to-netdev`) would see it.

Comment (jschwinger233) [reply bpf/bpf_host.c:865]: :fearful:
