### PR TITLE
labelsfilter: add reserved labels to default identity label list

### LINKED ISSUE #14100: Exposing new BPF failed: invalid LXC MAC: invalid MAC address
Caused by security-relevant-labels configuration changes. Not sure if this is the expected behavior, or a bug.

# General Information

- Cilium version: 1.8.4
- Kernel version: 4.19.118

# Dig inside

According to https://docs.cilium.io/en/v1.8/operations/scalability/identity-relevant-labels/#configuring-identity-relevant-labels,
after specifying a security relevant label list to cilium agent and restart the agent, all endpoints on this node will be regenerated with the given labels + default labels.

One problem is that, if `reserved:.host` (or `reserved:.*`) is not included in the provided label list, the `cilium_host` endpoint will lose `reserved:host` label. This is ok for now.

But when rolling back the change, that is, removing the specified label list and restarting the agent, it will raise the above errors.
Note that subsequently, all pods' traffic on this node will be interrupted.

My understanding is that `IsHost()` returns `false` for `cilium_host` endpoint during this case: https://github.com/cilium/cilium/blob/master/pkg/endpoint/bpf.go#L629

In the next, it will treat this endpoint as a normal endpoint, and try to get its `lxcMAC`, then failed as `cilium_host` has no corresponding `lxcMAC`. 

# Try-outs

Quickly tested that follow two ways could avoid the problem:

1. Via config: add `reserved:host` (or `reserved:.*`) to the custom label list.
2. Via patch: add `reserved:host` (or `reserved:.*`) to the (hard-coded) default label list, and re-compile cilium agent, https://github.com/cilium/cilium/blob/master/pkg/labelsfilter/filter.go#L163

Thanks!

@joestringer

### PR DESCRIPTION
**Pull request by ArthurChiao**
Fix #14100

When using custom identity-relevant-label-list in whitelist mode, if
`reserved:host` (or `reserved:.*`) label is not included in the custom
list, the `cilium_host` endpoint will lose its `reserved:host` label.

When rolling back the default configuration, that is, removing the specified
label list and restarting the agent, cilium agent will raise errors like
following:

```
level=warning msg="Regeneration of endpoint failed" .. error="Exposing new BPF failed: invalid LXC MAC: invalid MAC address "
level=error msg="endpoint regeneration failed" ..  error="Exposing new BPF failed: invalid LXC MAC: invalid MAC address "
```

And subsequently, all pods' traffic on this node will be interrupted.

This is because the agent relies on this label to distinguish `cilium_host`
endpoint from normal endpoints, and the former has no `lxcMAC`.
Add reserved labels to the default label list could solve the problem.

Signed-off-by: ArthurChiao <arthurchiao@hotmail.com>

### CODE REVIEW

**Comment by ArthurChiao** [comment]
@pchaigno please have a review, thanks!

**Review by aanm — COMMENTED** [review]
Reserved labels shouldn't never be excluded for any reason since they are reserved. @ArthurChiao or @pchaigno where in the code are we checking if `cilium_host` is `reserved`?

**Comment by ArthurChiao** [comment]
@aanm  https://github.com/cilium/cilium/blob/master/pkg/endpoint/endpoint.go#L809

```
	// If host label is present, it's the host endpoint.
	ep.isHost = ep.HasLabels(labels.LabelHost)
```

**Comment by aanm** [comment]
> @aanm https://github.com/cilium/cilium/blob/master/pkg/endpoint/endpoint.go#L809
> 
> ```
> 	// If host label is present, it's the host endpoint.
> 	ep.isHost = ep.HasLabels(labels.LabelHost)
> ```

That is odd given that `ep.HasLabels` checks for all labels, including information labels. Can you try this patch instead?
```patch
diff --git a/pkg/endpointmanager/manager.go b/pkg/endpointmanager/manager.go
index ff5f530a2..10964ac6c 100644
--- a/pkg/endpointmanager/manager.go
+++ b/pkg/endpointmanager/manager.go
@@ -504,7 +504,7 @@ func (mgr *EndpointManager) AddHostEndpoint(ctx context.Context, owner regenerat
        // Give the endpoint a security identity
        newCtx, cancel := context.WithTimeout(ctx, launchTime)
        defer cancel()
-       ep.UpdateLabels(newCtx, epLabels, nil, true)
+       ep.UpdateLabels(newCtx, epLabels, epLabels, true)
        if errors.Is(newCtx.Err(), context.DeadlineExceeded) {
                log.WithError(newCtx.Err()).Warning("Timed out while updating security identify for host endpoint")
        }
```

cc @pchaigno

**Comment by ArthurChiao** [comment]
Hi @aanm, just tested your patch, the problem still exists.

**Comment by pchaigno** [comment]
> Reserved labels shouldn't never be excluded for any reason since they are reserved. @ArthurChiao or @pchaigno where in the code are we checking if `cilium_host` is `reserved`?

To determine if an endpoint is the host endpoint, we also may check the security ID directly: https://github.com/cilium/cilium/blob/641c0f9b3072a014c9541ecaa4e00a2b24c98d97/daemon/cmd/datapath.go#L267
In some cases, we may rely on the security labels to set that security ID: https://github.com/cilium/cilium/blob/641c0f9b3072a014c9541ecaa4e00a2b24c98d97/pkg/identity/identity.go#L250-L251
:point_up: that might be why we get the reported bug when changing security-relevant label filters.

I think we should ensure the reserved labels are never excluded by our filtering logic (`filterLabels`). Probably best to warn the user if they try to exclude reserved labels. It's also not enough to add it to the list of default filters because that list will be overwritten when loading custom filters from a file (cf. `readLabelPrefixCfgFrom`).

**Comment by ArthurChiao** [comment]
> It's also not enough to add it to the list of default filters because that list will be overwritten when loading custom filters from a file (cf. readLabelPrefixCfgFrom).

Nice point! @pchaigno

**Comment by pchaigno** [comment]
It would probably also make sense to apply @aanm's suggested change, even if it doesn't fix the problem at hand.

**Comment by pchaigno** [comment]
@ArthurChiao Are you still planning to work on this?

**Comment by ArthurChiao** [comment]
Yes, I'd like to, but i'm not sure what's the suggested way to fix this. Can you detail more? Thanks! @pchaigno

**Comment by pchaigno** [comment]
We need to ensure `reserved:.*` labels are never excluded by either (1) modifying `filterLabels` or (2) adding `reserved:.*` to `validLabelPrefixes` in `ParseLabelPrefixCfg`. The second approach is simpler and probably enough (users would still be able to explicitly exclude specific reserved labels, but at this point they are just looking for trouble).

**Comment by ArthurChiao** [comment]
I'll try the 2nd one and update this PR then. Thank you! @pchaigno

**Comment by ArthurChiao** [comment]
Hi @pchaigno , I have refactored the patch, with changes:

1. Logs some messages to help users understand how label-list-parsing works
2. Add `reserved:.*` to default label list
3. Warn users if they overwrite the default label list with `--label-prefix-file` but not include `reserved:.*` in both label file and `--labels=<list>`. I appended a test file in the commit message.

But there is one thing I still don't quite understand: you suggested adding `reserved:.*` to `validLabelPrefixes` in `ParseLabelPrefixCfg()`, instead of in `defaultLabelPrefixCfg()`, could you please explain more?

Any comments welcomed! Thanks!

File: pkg/labelsfilter/filter.go [hunk 1]
```diff
@@ -131,9 +148,24 @@ func ParseLabelPrefixCfg(prefixes []string, file string) error {
...
+		for _, label := range cfg.LabelPrefixes {
+			if label.Source+":"+label.Prefix == reservedLabelsPattern {
+				found = true
+				break
+			}
+		}
+
+		if !found {
+			log.Warnf("'%s' is not included in the final label list, which may result to "+
+				"traffic interruptions when label list changed", reservedLabelsPattern)
```
Comment (pchaigno) [inline pkg/labelsfilter/filter.go]: I think we should error out here instead:
```suggestion
			log.Errorf("'%s' needs to be included in the final label list for " +
				"Cilium to work properly.", reservedLabelsPattern)
```

**Review by pchaigno — COMMENTED** [review]
Sorry for the delay in reviewing :disappointed: I missed the update over the holidays.

The pull request looks great! Just one comment below on the warning which I think should be an error or maybe even a fatal.

> But there is one thing I still don't quite understand: you suggested adding `reserved:.*` to `validLabelPrefixes` in `ParseLabelPrefixCfg()`, instead of in `defaultLabelPrefixCfg()`, could you please explain more?

I think the approach you took with a warning is fine; it's more explicit for the users.

**Comment by pchaigno** [comment]
test-me-please

**Comment by ArthurChiao** [comment]
> Sorry for the delay in reviewing

It's OK, enjoy your holidays :smiley: @pchaigno 

I've merged the suggested changes to the patch, thank you!

**Review by pchaigno — APPROVED** [review]
Thanks!

File: pkg/labelsfilter/filter.go [hunk 2]
```diff
@@ -131,9 +148,24 @@ func ParseLabelPrefixCfg(prefixes []string, file string) error {
...
+		found := false
+		for _, label := range cfg.LabelPrefixes {
+			if label.Source+":"+label.Prefix == reservedLabelsPattern {
+				found = true
+				break
+			}
+		}
+
+		if !found {
+			log.Errorf("'%s' needs to be included in the final label list for " +
```
Comment (pchaigno) [inline pkg/labelsfilter/filter.go]: The plus should be right after the double quotes here. See the GitHub action failures. Sorry for misleading you :disappointed:

**Comment by ArthurChiao** [comment]
My carelessness! Just fixed it :) @pchaigno

**Comment by pchaigno** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by pchaigno** [comment]
Marking for backport into v1.8 and v1.9 as it can affect the host firewall on those versions.
