### PR TITLE
Use policy for IPCache LPM prefix length generation, not IPCache

### LINKED ISSUE #4188: CI: Master regression: runtime.RuntimeValidatedPolicies TestsEgressToHost Tests egress with CIDR+L4 policy to external https service
## runtime.RuntimeValidatedPolicies TestsEgressToHost Tests egress with CIDR+L4 policy to external https service (from (runtime.xml))

Link: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/856/testReport/junit/(root)/runtime/RuntimeValidatedPolicies_TestsEgressToHost_Tests_egress_with_CIDR_L4_policy_to_external_https_service/

### Failing for the past 1 build (Since Failed#856 )
Took 56 sec.

### Stacktrace
```
/home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:338
Expected to be able to access /public in host Docker container
Expected
    <string>: 000
to contain substring
    <string>: 200
/home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/runtime/Policies.go:1111
```
### Standard Output
```
STEP: Setting PolicyEnforcement=default
STEP: Pinging "10.0.2.15" from "app1" before importing policy (should work)
STEP: Pinging "172.17.0.1" from "app1" before importing policy (should work)
STEP: Flushing global connection tracking table before importing policy
STEP: Importing policy which allows egress to "172.17.0.1" from "app1"
�[1mSTEP�[0m: Setting up policy: /home/vagrant/go/src/github.com/cilium/cilium/test/policy_36d9ff45.json
STEP: Pinging "host" from "app1" (should not work)
STEP: Accessing index.html using Docker container using host networking from "app1" (should work)
===================== TEST FAILED =====================
cmd: sudo cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])   IPv6                 IPv4            STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                     
13949      Disabled           Disabled          10425      container:id.httpd3           f00d::a0f:0:0:367d   10.15.42.252    ready   
                                                           container:id.service1                                                      
15124      Disabled           Disabled          47576      container:id.httpd1           f00d::a0f:0:0:3b14   10.15.195.213   ready   
                                                           container:id.service1                                                      
25729      Disabled           Disabled          14097      container:id.httpd2           f00d::a0f:0:0:6481   10.15.101.61    ready   
                                                           container:id.service1                                                      
29381      Disabled           Enabled           21020      container:id.app1             f00d::a0f:0:0:72c5   10.15.193.100   ready   
29898      Disabled           Disabled          38607      reserved:health               f00d::a0f:0:0:74ca   10.15.242.54    ready   
48896      Disabled           Disabled          38894      container:id.app2             f00d::a0f:0:0:bf00   10.15.13.37     ready   
60670      Disabled           Disabled          38172      container:id.app3             f00d::a0f:0:0:ecfe   10.15.167.158   ready   

===================== EXITING REPORT GENERATION =====================
```

[test_results_master_856.zip](https://github.com/cilium/cilium/files/2018500/test_results_master_856.zip)

### PR DESCRIPTION
**Pull request by joestringer**
Previously, CIDR insertion in policy would queue updates for the IPCache                                                                                                                                             
via the KVstore, then go straight into policy add / policy regeneration         
for endpoints. This would reach into IPCache to fetch the set of prefix         
lengths (ipcache.ToBPFData()) before the original IPCache KVstore update        
has propagated into the local IPCache.                                          
                                                                                
Thus, the set of prefix lengths used in generating the BPF programs may         
not include the prefix lengths for the newly inserted CIDRs. When the           
IPCache KVstore event is eventually processed, no regeneration of BPF is        
triggered so the old set of prefix lengths is used for endpoints until          
the next time the endpoints are regenerated. This leads to improper             
CIDR->Identity mapping in the datapath, which may lead to unexpected            
packet drops as the broader "reserved:world" policy would apply rather          
than the CIDR policy.                                                           
                                                                                
For reference, one plausible solution would be to trigger regeneration          
from IPCache, however this could be costly if you have dozens of IPCache        
updates occurring. There's no good way to batch the updates for these           
currently. Furthermore, it would trigger multiple rebuilds of the               
datapath based on a single policy update.                                       
                                                                                
Alternatively, we should have enough information already during policy          
resolution to generate the appropriate set of prefix lengths for the            
datapath from that policy path. This patch implements this. In other            
words:                                                                          
* Policy generation inserts elements into the L3Policy                          
* Endpoint regeneration uses the L3Policy to determine which CIDR               
prefixes need to be used by the endpoint to perform CIDR->ID mappings           
in order to implement that policy                                               
* The IPCache (by way of the KVstore) will plumb the actual CIDR->ID            
mappings into the BPF maps.                                                     
                                                                                
This should mean that the datapath is eventually consistent with the            
configured CIDR policies.

Note that this will not solve all of the problems; there is still no ability to wait
for the ipcache to be in sync with the policy. However, it does address the
problem that the endpoint BPF programs get stuck in a state where they
can't properly look up the CIDR identity for an extended period.
                                       
Fixes: https://github.com/cilium/cilium/issues/4188
Related: https://github.com/cilium/cilium/issues/4055 (This should further improve test reliability)

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4231)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
CI failed due to weird Jenkins issue:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/3491/

```
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from http://github.com/cilium/cilium
    at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:862)
    at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1129)
    at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1160)
    at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:113)
    at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:85)
    at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:75)
    at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
    at hudson.security.ACL.impersonate(ACL.java:290)
    at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress http://github.com/cilium/cilium +refs/pull/*:refs/remotes/origin/pr/*" returned status code 128:
```

Re-trying.

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Unit test issue, fixed up in the next revision.

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

File: pkg/endpoint/bpf.go [hunk 1]
```diff
@@ -263,9 +262,12 @@ func (e *Endpoint) writeHeaderfile(prefix string, owner Owner) error {
 		return err
 	}
 
+	ipcachePrefixes6, ipcachePrefixes4 := policy.GetDefaultPrefixLengths()
 	if e.L3Policy != nil {
-		ipv6Ingress, ipv4Ingress := e.L3Policy.Ingress.ToBPFData()
+		// Only egress CIDR policy uses IPCache for now.
+		ipcachePrefixes6, ipcachePrefixes4 = e.L3Policy.Egress.ToBPFData()
```
Comment (jrajahalme) [inline pkg/endpoint/bpf.go]: As this reassigns the prefix length arrays ToBPFData() must also include the default prefix lengths in the returned arrays. Maybe add a comment to that effect here?

**Review by jrajahalme — APPROVED** [review]
LGTM, a minor comment below.

**Comment by jrajahalme** [comment]
Excellent description, btw!

**Comment by joestringer** [comment]
CI failure:

```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:373
"app3" expects curl public URL on httpd2 (10.15.193.100) to succeed
Expected
    <bool>: false
to be true
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/runtime/Policies.go:342
```

Failure in `test-output.log`:
```
time="2018-05-23T23:10:12Z" level=debug msg="running command: docker exec -i  app3 curl -s --fail --connect-timeout 5 --max-time 5 http://10.15.193.100:80/public"                                                                                             
cmd: "docker exec -i  app3 curl -s --fail --connect-timeout 5 --max-time 5 http://10.15.193.100:80/public" exitCode: 28
```

Policy drop for world identity in `monitor.log`:
```
[2018-05-23 23:10:12] CPU 01: MARK 0x782439b3 FROM 173 from-endpoint: 74 bytes, state new, identity 53343->0
[2018-05-23 23:10:12] Ethernet>.{Contents=[..14..] Payload=[..62..] SrcMAC=aa:4d:47:4e:5c:fa DstMAC=9e:9d:e4:02:c1:4e EthernetType=IPv4 Length=0}
[2018-05-23 23:10:12] IPv4>.....{Contents=[..20..] Payload=[..40..] Version=4 IHL=5 TOS=0 Length=60 Id=38989 Flags=DF FragOffset=0 TTL=64 Protocol=TCP Checksum=14399 SrcIP=10.15.148.173 DstIP=10.15.193.100 Options=[] Padding=[]}
[2018-05-23 23:10:12] TCP>......{Contents=[..40..] Payload=[] SrcPort=37234 DstPort=80(http) Seq=1314511748 Ack=0 DataOffset=10 FIN=false SYN=true RST=false PSH=false ACK=false URG=false ECE=false CWR=false NS=false Window=28200 Checksum=27230 Urgent=0 O#
[2018-05-23 23:10:12] CPU 01: MARK 0x782439b3 FROM 173 DEBUG: Conntrack lookup 1/2: src=10.15.148.173:37234 dst=10.15.193.100:80
[2018-05-23 23:10:12] CPU 01: MARK 0x782439b3 FROM 173 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=1
[2018-05-23 23:10:12] CPU 01: MARK 0x782439b3 FROM 173 DEBUG: CT verdict: New, revnat=0
[2018-05-23 23:10:12] CPU 01: MARK 0x782439b3 FROM 173 DEBUG: Successfully mapped daddr=10.15.193.100 to identity=2
[2018-05-23 23:10:12] CPU 01: MARK 0x782439b3 FROM 173 DEBUG: Policy evaluation would deny packet from 53343 to 2
```

However, at least when the IPCache was dumped by the bugtool, the IPCache already had this destination (bugtool's `cmd/cilium-bpf-ipcache-list.md`:                                            
                                                                                
```                                                                             
IP PREFIX/ADDRESS        IDENTITY                                               
f00d::a0f:0:0:8ad6/128   1                                                                                                                                                                                                                                     
10.15.42.252/32          49285                                                  
10.15.129.91/32          19860                                                  
10.15.13.37/32           52110                                                  
fc00::10ca:1/128         1                                                      
f00d::a0f:0:0:367d/128   49285                                                  
10.15.250.189/32         30000                                                  
10.0.2.15/32             1                                                      
f00d::a0f:0:0:ad/128     53343                                                  
10.15.242.54/32          4                                                      
f00d::/64                3                                                      
f00d::a0f:0:0:bf00/128   52110                                                  
10.0.0.0/8               3                                                      
0.0.0.0/0                2                                                      
f00d::a0f:0:0:72c5/128   41806                                                  
10.15.148.173/32         53343                                                  
::/0                     2                                                      
f00d::a0f:0:0:981b/128   30000                                                  
10.15.28.238/32          1                                                      
f00d::a0f:0:0:74ca/128   4                                                      
10.15.193.100/32         41806                                                  
f00d::a0f:0:0:dc06/128   19860                                                  
                                                                                
``` 

Looking into `lib/cilium/state/173/lxc_config.h`, the prefixes are just plain wrong:

```
$ grep PREFIXES lib/cilium/state/173/lxc_config.h 
#define IPCACHE6_PREFIXES 2,1,0,
#define IPCACHE4_PREFIXES 2,1,0,
```

I'll work on fixing this up.

[9acb0442_RuntimeValidatedPolicies_L3-L4_Checks (1).zip](https://github.com/cilium/cilium/files/2033216/9acb0442_RuntimeValidatedPolicies_L3-L4_Checks.1.zip)

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

EDIT: Green build: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/3511/

Re-running for some attempt to reproduce flake.

**Comment by joestringer** [comment]
Green build: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/3511/

Re-running for some attempt to reproduce flake.

**Comment by joestringer** [comment]
test-me-please

EDIT: Green build.

File: pkg/policy/l3_test.go [hunk 2]
```diff
@@ -15,26 +15,56 @@
...
 
 	. "gopkg.in/check.v1"
 )
 
-func (ds *PolicyTestSuite) TestToBPFData(c *C) {
-	cidrPolicy := NewCIDRPolicy()
-	m := cidrPolicy.Ingress
+// init prepares the node's allocation range so that the ``ToBPFData()`` calls
+// below can successfully fetch the cluster range.
+func init() {
```
Comment (aanm) [inline pkg/policy/l3_test.go]: I would prefer that you use the TearUp / TearDown function to set and unset the node allocation range  to make sure the `node.Set..` doesn't affect other tests.

**Review by aanm — DISMISSED** [review]

File: pkg/policy/l3_test.go (hunk 2 above)
Comment (joestringer) [reply pkg/policy/l3_test.go]: I had to introduce a new `Uninitialize()` function in the node package for the teardown. Done this locally, will push out soon.

**Comment by joestringer** [comment]
test-me-please

EDIT: Third green build.

**Review by aanm — APPROVED** [review]

**Review by manalibhutiyani — APPROVED** [review]
