### PR TITLE
policy: Resolve named ports for egress policies based on destination identities

### LINKED ISSUE #30003: NetworkPolicy with named port is not working when there are more than one port with the same name
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We use named ports in our containers for ingress traffic. When multiple pods have containers with the same port name but with different values, traffic is not allowed.
The issue can be reproduced with the following two pods and a single NetworkPolicy:
```
apiVersion: v1
kind: Pod
metadata:
  name: cilium-np-test01
  namespace: default
  labels:
    app.kubernetes.io/name: cilium-np-test01
    network-rules-egress: cilium-np-test
spec:
  containers:
  - name: debug
    ports:
    - name: http-test
      containerPort: 8000
      protocol: TCP
```
```
apiVersion: v1
kind: Pod
metadata:
  name: cilium-np-test02
  namespace: default
  labels:
    app.kubernetes.io/name: cilium-np-test02
spec:
  containers:
  - name: nginx
    ports:
    - name: http-test
      containerPort: 8080
      protocol: TCP
```
```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
  name: allow-egress
  namespace: default
spec:
  podSelector:
    matchLabels:
      network-rules-egress: cilium-np-test
  egress:
  - ports:
    - port: http-test
      protocol: TCP
  policyTypes:
  - Egress
```
The `cilium-np-test01` pod can't reach `cilium-np-test02` when both pods have a `http-test` port with different port values. If I change the `containerPort` on `cilium-np-test01` to 8080 it works or if I remove the `name` from the port on `cilium-np-test01` it works.

### Cilium Version

```
cilium version
Client: 1.14.5 85db28be 2023-12-11T14:30:29+01:00 go version go1.20.12 linux/amd64
Daemon: 1.14.5 85db28be 2023-12-11T14:30:29+01:00 go version go1.20.12 linux/amd64
```

### Kernel Version

```
uname -a
Linux cp03-43a2f386 5.15.0-87-generic #97-Ubuntu SMP Mon Oct 2 21:09:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.6+rke2r1
```

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

This is a clone of the #24779 issue, that was marked as stale and closed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by TheBeeZee**
Previously, egress policies using named ports would consider all named port definitions across the cluster. This could lead to 'ErrDuplicateNamedPorts' errors if different pods, not targeted by the policy, used the same port name with different port numbers.

This commit enhances the named port resolution mechanism for egress policies by filtering the available named port mappings based on the destination identities selected by the policy. The set of potential destination identities is now passed to the `GetNamedPort` function.

The underlying `NamedPortMultiMap` and `PortProtoSet` data structures have been updated to store the association between named port definitions and the endpoint identities that own them. This allows `GetNamedPort` to accurately resolve the port number by only considering the definitions from the endpoints matching the policy's selectors.

Fixes: #30003

```release-note
Egress policies with named ports now only consider ports from selected endpoints, preventing duplicate port errors.
```

### CODE REVIEW

**Comment by TheBeeZee** [comment]
@squeed Might want to look at this one.

File: pkg/policy/l4.go [hunk 1]
```diff
@@ -696,6 +696,21 @@ func (l4 *L4Filter) makeMapStateEntry(logger *slog.Logger, p *EndpointPolicy, po
...
 }
 
+// Identities extracts the set of identities corresponding to selectors.
+func (l4 *L4Filter) Identities() map[identity.NumericIdentity]struct{} {
+	idSet := make(map[identity.NumericIdentity]struct{})
+	for cs := range l4.PerSelectorPolicies {
+		if cs == nil {
+			continue
+		}
+		ids := cs.GetSelections()
```
Comment (jrajahalme) [inline pkg/policy/l4.go]: It would be better to use `GetSelectionsTxn()` instead with a snapshot taken with `SelectorCache.GetSelectorSnapshot()` higher up the call stack so that the identities taken on L4Filters would be from the same view of the selectors.

Comment (jrajahalme) [reply pkg/policy/l4.go]: Better yet, pass the result of the `GetSelectionsTxn()` already done by the caller, e.g., `toMapState()` ( you'll have to move the `GetSelectionsTxn()` call higher up, before the `GetNamedPort()` call.

Comment (jrajahalme) [reply pkg/policy/l4.go]: Wonder if using only the added and/or deleted identities in the incremental `AccumulateMapChanges` call path would suffice?

**Review by jrajahalme — COMMENTED** [review]
I wonder if we could keep selector cache use "transactional" by using the snapshot already being used during policy calculation?

File: pkg/policy/l4.go (hunk 1 above)
Comment (TheBeeZee) [reply pkg/policy/l4.go]: > It would be better to use `GetSelectionsTxn()` instead with a snapshot taken with `SelectorCache.GetSelectorSnapshot()` higher up the call stack so that the identities taken on L4Filters would be from the same view of the selectors.

Apologies for my ignorance, but I can't find the string "GetSelectionsTxn" anywhere in the Cilium code base. What am I missing?

Comment (TheBeeZee) [reply pkg/policy/l4.go]: Ok, I think I was able to change the logic so it uses the snapshot, let me know if this makes sense. I put the changes into a separate commit.

File: pkg/types/portmap.go [hunk 2]
```diff
@@ -32,38 +32,62 @@ type PortProto struct {
 // NamedPortMap maps port names to port numbers and protocols.
 type NamedPortMap map[string]PortProto
 
-// PortProtoSet is a reference-counted set of unique PortProto values.
-type PortProtoSet counter.Counter[PortProto]
+// PortProtoSet maps PortProto to a set of endpoint IDs that define it.
+type PortProtoSet map[PortProto]map[identity.NumericIdentity]struct{}
```
Comment (smagnani96) [inline pkg/types/portmap.go]:
```suggestion
type PortProtoSet map[PortProto]map[identity.NumericIdentity]int
```

Shouldn't we keep reference count for each NumericIdentity? (with also the needed logic in the other methods to account for this)

I'm afraid that the following scenario could happen when creating a deployment of two pods:

| Step | Action | Old (Refcount) | New (Identity Set) |
| :--- | :--- | :--- | :--- |
| 1 | Pod A Upsert | `refcount = 1` | `epSet = {X}` |
| 2 | Pod B Upsert | `refcount = 2` | `epSet = {X}` |
| 3 | Pod A Delete | `refcount = 1` | `epSet = { }` |

So PodB is still alive, but the `epSet` is empty.

Comment (TheBeeZee) [reply pkg/types/portmap.go]: Thanks for the review. You are of course right. I have added a commit that restores the reference count.

File: pkg/policy/l4.go (hunk 1 above)
Comment (jrajahalme) [reply pkg/policy/l4.go]: > Apologies for my ignorance, but I can't find the string "GetSelectionsTxn" anywhere in the Cilium code base. 
> What am I missing?

My bad, sorry, it is `GetSelectionsAt()`.

File: pkg/endpoint/policy.go [hunk 3]
```diff
@@ -104,7 +104,15 @@ func (e *Endpoint) proxyID(l4 *policy.L4Filter, listener string) (string, uint16
 		protocol = proto
 	}
 	if port == 0 && l4.PortName != "" {
-		port = e.GetNamedPort(l4.Ingress, l4.PortName, protocol, l4.Identities())
+		idSet := make(map[identity.NumericIdentity]struct{}, 0)
+		if rp := e.realizedPolicy; rp != nil {
+			if sp := rp.SelectorPolicy; sp != nil {
+				if sc := sp.SelectorCache; sc != nil {
+					idSet = l4.Identities(sc.GetSelectorSnapshot())
```
Comment (jrajahalme) [inline pkg/endpoint/policy.go]: This `proxyID` call is used for adding new redirects, as required for a new policy. I have not checked for this, but using the `e.realizedPolicy` runs the risk of it being `nil` while the caller already has the new `selectorPolicy` based on which the named ports should be resolved.

The caller (`Endpoint.addNewRedirects()`) is executing after the new selector policy has been computed, but before a snapshot is taken for the eventual endpoint policy computation. Taking a separate snapshot here feels potentially racy, but maybe this was already racy, not sure.

Either way if would be better have the caller pass a lambda that could take a single snapshot when needed  and retain it for all proxyID calls? Something like this (not tested):

```
 diff --git a/pkg/endpoint/bpf.go b/pkg/endpoint/bpf.go
index 6da8f96b09..988d924aa0 100644
--- a/pkg/endpoint/bpf.go
+++ b/pkg/endpoint/bpf.go
@@ -263,6 +263,13 @@ func (e *Endpoint) addNewRedirects(selectorPolicy policy.SelectorPolicy, proxyWa
 		updatedStats []*models.ProxyStatistics
 	)
 
+	var scSnapshot policy.SelectorSnapshot
+	scSnapshotGetter := func() policy.SelectorSnapshot {
+		if !scSnapshot.IsValid() {
+			scSnapshot = selectorPolicy.GetSelectorCache().GetSelectorSnapshot()
+		}
+		return scSnapshot
+	}
 	// create or update proxy redirects
 	for l4, policySelectorTuple := range selectorPolicy.RedirectFilters() {
 		// Possible listener name for both the proxy ID and the proxyPolicy below.
@@ -270,7 +277,7 @@ func (e *Endpoint) addNewRedirects(selectorPolicy policy.SelectorPolicy, proxyWa
 
 		// proxyID() returns also the destination port for the policy,
 		// which may be resolved from a named port
-		proxyID, dstPort, dstProto := e.proxyID(l4, listener)
+		proxyID, dstPort, dstProto := e.proxyID(l4, listener, scSnapshotGetter)
 		if proxyID == "" {
 			// Skip redirects for which a proxyID cannot be created.
 			// This may happen due to the named port mapping not
diff --git a/pkg/endpoint/policy.go b/pkg/endpoint/policy.go
index 87c18b1c62..81e1840d3e 100644
--- a/pkg/endpoint/policy.go
+++ b/pkg/endpoint/policy.go
@@ -93,7 +93,7 @@ func (e *Endpoint) getNamedPortEgress(npMap types.NamedPortMultiMap, name string
 // For port ranges the proxy is identified by the first port in
 // the range, as overlapping proxy port ranges are not supported.
 // Must be called with e.mutex held.
-func (e *Endpoint) proxyID(l4 *policy.L4Filter, listener string) (string, uint16, u8proto.U8proto) {
+func (e *Endpoint) proxyID(l4 *policy.L4Filter, listener string, scSnapshotGetter func() policy.SelectorSnapshot) (string, uint16, u8proto.U8proto) {
 	port := l4.Port
 	protocol := l4.U8Proto
 	// Calculate protocol if it is 0 (default) and
@@ -103,7 +103,7 @@ func (e *Endpoint) proxyID(l4 *policy.L4Filter, listener string) (string, uint16
 		protocol = proto
 	}
 	if port == 0 && l4.PortName != "" {
-		port = e.GetNamedPort(l4.Ingress, l4.PortName, protocol)
+		port = e.GetNamedPort(l4.Ingress, l4.PortName, protocol, l4.Identities(scSnapshotGetter()))
 		if port == 0 {
 			return "", 0, 0
 		}
```

File: pkg/policy/l4.go [hunk 4]
```diff
@@ -1623,10 +1623,11 @@ func (l4Policy *L4Policy) AccumulateMapChanges(logger *slog.Logger, l4 *L4Filter
 	l4Policy.mutex.RLock()
 	defer l4Policy.mutex.RUnlock()
 
+	idSet := identity.NumericIdentitySlice(append(adds, deletes...)).AsSet()
```
Comment (jrajahalme) [inline pkg/policy/l4.go]: Would be better condition this transformation on `port == 0 && l4.PortName != ""` so that the cost is paid only if named ports are in use.

File: pkg/policy/selectorcache.go [hunk 5]
```diff
@@ -275,8 +275,8 @@ type SelectorCache struct {
 	userHandlerDone chan struct{}
 }
 
-// GetReadTxn returns a read-only state of the current selectors in the selector cache.
-// The returned SelectorReadTxn should be Close()d as soon as possible to limit memory use.
+// GetSelectorSnapshot returns a read-only state of the current selectors in the selector cache.
+// The returned SelectorSnapshot should be Close()d as soon as possible to limit memory use.
```
Comment (jrajahalme) [inline pkg/policy/selectorcache.go]: The comment was even more stale; there is no `Close()`, but `Invalidate()` should be called on a snapshot if stored in the heap and not needed any more. While you are at it, could you update the comment to state the above?

File: pkg/endpoint/policy.go (hunk 3 above)
Comment (jrajahalme) [reply pkg/endpoint/policy.go]: `GetSelectorCache()` would need to be a new method in the SelectorPolicy interface.

File: pkg/types/portmap.go [hunk 6]
```diff
@@ -198,7 +242,19 @@ func (npm *namedPortMultiMap) GetNamedPort(name string, proto u8proto.U8proto) (
...
+	for pp, epSet := range pps {
+		// Check if this PortProto is defined by any of the target endpoint IDs
+		validEp := false
+		for epID := range epIDs {
+			if _, exists := epSet[epID]; exists {
+				validEp = true
+				break
+			}
+		}
+		if !validEp {
```
Comment (jrajahalme) [inline pkg/types/portmap.go:248]: Given that the passed in map is only used for iteration it seems that the transformations performed to form it in the first place are mostly wasted. How about passing an `iter.Seq[identity.NumericIdentity]` instead of a map, and then returning that from `L4Filter.Identities()`, directly iterating the PerSelectorPolicies within the returned iterator? This would avoid the temporary map, and yes, would loose deduplication, but maybe avoiding the allocation and initialization for the map would be worth some duplicate iterated identities?

File: pkg/policy/l4.go [hunk 7]
```diff
@@ -674,6 +674,21 @@ func (l4 *L4Filter) makeMapStateEntry(logger *slog.Logger, p *EndpointPolicy, po
...
+		if cs == nil {
+			continue
+		}
+		ids := cs.GetSelectionsAt(txn)
+		for _, id := range ids {
+			idSet[id] = struct{}{}
+		}
+	}
+	return idSet
+}
```
Comment (jrajahalme) [inline pkg/policy/l4.go:692]: Seems like it would be better to return an iterator than allocating and populating a temporary map here, e.g. something like:
```
func (l4 *L4Filter) Identities(txn SelectorSnapshot) iter.Seq[identity.NumericIdentity] {
	return func(yield func(identity.NumericIdentity) bool) {
		for cs := range l4.PerSelectorPolicies {
			if cs != nil {
				for _, id := range cs.GetSelectionsAt(txn) {
					if !yield(id) {
						return
					}
				}
			}
		}
	}	
}
```

File: pkg/policy/l4.go (hunk 4 above)
Comment (jrajahalme) [reply pkg/policy/l4.go]: Using an iterator here would also avoid the temporary slice and map allocations and initializations here.

**Review by jrajahalme — CHANGES_REQUESTED** [review]
Some suggestions for improvement, did not review the reference counting side of things.

File: pkg/policy/l4.go (hunk 7 above)
Comment (TheBeeZee) [reply pkg/policy/l4.go:692]: Thank you, using iter.Seq indeed makes this much cleaner.

File: pkg/types/portmap.go (hunk 6 above)
Comment (TheBeeZee) [reply pkg/types/portmap.go:248]: Thanks for the suggestion. Done.

File: pkg/policy/selectorcache.go (hunk 5 above)
Comment (TheBeeZee) [reply pkg/policy/selectorcache.go]: Updated.

File: pkg/policy/l4.go (hunk 4 above)
Comment (TheBeeZee) [reply pkg/policy/l4.go]: Update to use iterator.

File: pkg/endpoint/policy.go (hunk 3 above)
Comment (TheBeeZee) [reply pkg/endpoint/policy.go]: Thanks for the details. I have added a commit that implements this.

**Review by jrajahalme — APPROVED** [review]
Thanks!

**Comment by jrajahalme** [comment]
@smagnani96 Could you check that the reference counting is now fixed?

**Review by vipul-21 — APPROVED** [review]
lgtm for my codeowners

File: pkg/types/portmap.go [hunk 8]
```diff
@@ -32,38 +33,69 @@ type PortProto struct {
...
-func (pps PortProtoSet) Add(pp PortProto) bool {
-	return counter.Counter[PortProto](pps).Add(pp)
+// Add increments the reference count for the epID associated with the PortProto.
+// Returns true if the epID was not previously in the map (count was 0).
+func (pps PortProtoSet) Add(pp PortProto, epID identity.NumericIdentity) bool {
+	epCounts, ok := pps[pp]
+	if !ok {
+		epCounts = make(map[identity.NumericIdentity]int)
+		pps[pp] = epCounts
+	}
```
Comment (smagnani96) [inline pkg/types/portmap.go:68]:
```suggestion
	}
	return counter.Counter[identity.NumericIdentity](epCounts).Add(epID)
```

File: pkg/types/portmap.go [hunk 9]
```diff
@@ -32,38 +33,69 @@ type PortProto struct {
...
+	return oldCount == 0
 }
 
-// Delete decrements the reference count for the specified key.
-func (pps PortProtoSet) Delete(pp PortProto) bool {
-	return counter.Counter[PortProto](pps).Delete(pp)
+// Delete decrements the reference count for the epID associated with the PortProto.
+// It returns true if the epID was deleted.
+func (pps PortProtoSet) Delete(pp PortProto, epID identity.NumericIdentity) bool {
+	if epCounts, ok := pps[pp]; ok {
```
Comment (smagnani96) [inline pkg/types/portmap.go]:
```suggestion
	epCounts, ok := pps[pp]
	if !ok {
		return false
	}
	return counter.Counter[identity.NumericIdentity](epCounts).Delete(epID)
```

File: pkg/types/portmap.go [hunk 10]
```diff
@@ -32,38 +33,69 @@ type PortProto struct {
...
+	oldCount := epCounts[epID]
+	epCounts[epID] = oldCount + 1
+	return oldCount == 0
 }
 
-// Delete decrements the reference count for the specified key.
-func (pps PortProtoSet) Delete(pp PortProto) bool {
-	return counter.Counter[PortProto](pps).Delete(pp)
+// Delete decrements the reference count for the epID associated with the PortProto.
+// It returns true if the epID was deleted.
```
Comment (smagnani96) [inline pkg/types/portmap.go:73]: False with the current implementation, as it returns true also when count keeps being >= 0. If you adjust the method accordingly to my suggestion below (basically how it was before) then this comment is correct.

File: pkg/types/portmap.go (hunk 9 above)
Comment (smagnani96) [reply pkg/types/portmap.go]: This requires to adjust `portmap_test.go` tests accordingly.

**Review by smagnani96 — CHANGES_REQUESTED** [review]
Almost there. The logic has been restored, I believe we can slightly enhance it.
After this iteration, LGTM.
Thanks for the contrib (and the patience waiting for reviews).

File: pkg/types/portmap.go (hunk 10 above)
Comment (TheBeeZee) [reply pkg/types/portmap.go:73]: Thank you.

**Comment by TheBeeZee** [comment]
> Almost there. The logic has been restored, I believe we can slightly enhance it. After this iteration, LGTM. Thanks for the contrib (and the patience waiting for reviews).

Thanks for your help!

File: pkg/endpoint/bpf.go [hunk 11]
```diff
@@ -263,14 +263,22 @@ func (e *Endpoint) addNewRedirects(selectorPolicy policy.SelectorPolicy, proxyWa
 		updatedStats []*models.ProxyStatistics
 	)
 
+	var scSnapshot policy.SelectorSnapshot
+	scSnapshotGetter := func() policy.SelectorSnapshot {
+		if !scSnapshot.IsValid() {
+			scSnapshot = selectorPolicy.GetSelectorCache().GetSelectorSnapshot()
```
Comment (smagnani96) [inline pkg/endpoint/bpf.go]:
```suggestion
			scSnapshot = selectorPolicy.GetSelectorSnapshot()
```

File: pkg/types/portmap_test.go [hunk 12]
```diff
@@ -86,123 +88,177 @@ func TestPolicyNamedPortMap(t *testing.T) {
...
+	require.Equal(t, 0, pps[pp][id2])
+	require.Len(t, pps[pp], 1)
+
+	// Remove id1 again
+	require.True(t, pps.Delete(pp, id1))
+	require.Equal(t, 0, pps[pp][id1])
+	require.Equal(t, 0, pps[pp][id2])
+	require.Empty(t, pps[pp])
+
+	// Test removing non-existent id
```
Comment (smagnani96) [inline pkg/types/portmap_test.go]:
```suggestion
	// Remove id1 again — last identity, so the PortProto entry is cleaned up
	require.True(t, pps.Delete(pp, id1))
	require.Nil(t, pps[pp]) // entire PortProto entry removed
	require.Empty(t, pps)

	// Test removing non-existent id from existing PortProto
```

File: pkg/types/portmap.go [hunk 13]
```diff
@@ -32,38 +34,57 @@ type PortProto struct {
...
+func (pps PortProtoSet) Delete(pp PortProto, epID identity.NumericIdentity) bool {
+	epCounts, ok := pps[pp]
+	if !ok {
+		return false
+	}
+	return counter.Counter[identity.NumericIdentity](epCounts).Delete(epID)
```
Comment (smagnani96) [inline pkg/types/portmap.go]:
```suggestion
	deleted := counter.Counter[identity.NumericIdentity](epCounts).Delete(epID)
	if deleted && len(epCounts) == 0 {
		delete(pps, pp)
	}
	return deleted
```

File: pkg/policy/resolve.go [hunk 14]
```diff
@@ -159,6 +160,9 @@ type SelectorPolicy interface {
 	// DistillPolicy returns the policy in terms of connectivity to peer
 	// Identities.
 	DistillPolicy(logger *slog.Logger, owner PolicyOwner, redirects map[string]uint16) *EndpointPolicy
+
+	// GetSelectorCache returns the selector cache
+	GetSelectorCache() *SelectorCache
```
Comment (smagnani96) [inline pkg/policy/resolve.go]:
```suggestion
	// GetSelectorSnapshot returns a read-only snapshot of selector state.
	GetSelectorSnapshot() SelectorSnapshot
```

File: pkg/policy/resolve.go [hunk 15]
```diff
@@ -184,6 +188,10 @@ type selectorPolicy struct {
 	EgressPolicyEnabled bool
 }
 
+func (p *selectorPolicy) GetSelectorCache() *SelectorCache {
+	return p.SelectorCache
```
Comment (smagnani96) [inline pkg/policy/resolve.go]:
```suggestion
func (p *selectorPolicy) GetSelectorSnapshot() SelectorSnapshot {
	return p.SelectorCache.GetSelectorSnapshot()
```

File: pkg/fqdn/service/service_test.go [hunk 16]
```diff
@@ -719,6 +719,10 @@ func (sp *testSelectorPolicy) RedirectFilters() iter.Seq2[*policy.L4Filter, poli
 	}
 }
 
+func (sp *testSelectorPolicy) GetSelectorCache() *policy.SelectorCache {
+	return nil
```
Comment (smagnani96) [inline pkg/fqdn/service/service_test.go]:
```suggestion
func (sp *testSelectorPolicy) GetSelectorSnapshot() policy.SelectorSnapshot {
	return policy.SelectorSnapshot{}
```

**Review by smagnani96 — CHANGES_REQUESTED** [review]
Another pass with a clear head:

* `PortProtoSet.Delete()`: we need to clean empty entries (`pp`) in the outer map, and adjust tests accordingly.
* `type SelectorPolicy interface`: we can directly export the method `GetSelectorSnapshot` rather than getting the whole `SelectorCache`, and adjust tests accordingly.

File: pkg/endpoint/bpf.go (hunk 11 above)
Comment (TheBeeZee) [reply pkg/endpoint/bpf.go]: Thanks, that gets rid of a lot of the cruftiness.

**Review by smagnani96 — APPROVED** [review]
LGTM 👍🏼

**Comment by joestringer** [comment]
@TheBeeZee @cilium/sig-policy I see a proposal to backport to 1.19 here: https://github.com/cilium/cilium/issues/30003#issuecomment-4050879543 . It would be good to get a sense for how confident we are about the change and risk of regression (that is, it fixes one issue but introduces another). Generally speaking [we backport most bugfixes](https://docs.cilium.io/en/stable/contributing/release/backports/#backport-criteria-for-current-minor-release) to the latest branch so this proposal to backport matches that expectation. At the same time if we feel any further baking on main or subsequent testing is useful, then we can defer for a bit.

**Comment by andsens** [comment]
Although I am anxiously waiting to use this, I (and surely others) have been using port numbers in lieu of names for quite a while now. Personally I am quite alright with waiting a bit more if it means cilium has an increased chance of being stable throughout minor versions.  
Wouldn't it make more sense to put this into a `1.20.0-pre.1` to let people play with it?  
Even though one might classify this as a bugfix it really is more of a new feature by now.

**Comment by TheBeeZee** [comment]
Considering how long this bug has been there, it seems like the testing for named ports isn't ideal, so having a bit more bake time would likely be beneficial.  I don't have a good sense of how many people actually use 1.20-pre vs the main branch, so not sure how much benefit there will be from putting it into 1.20. I'll defer to those with more experience in the Cilium release process, I'm fine either way.

**Comment by joestringer** [comment]
For the next few months, 1.20-pre.* are just monthly tags from `main` prepared around the start of each month ([full schedule here](https://github.com/cilium/cilium/discussions/44333)). It'll automatically show up in the April prerelease drop. We post messages to encourage community members to try these out and report bugs in order to get early feedback for the next stable release, but yes the usage is quite a bit lower than the stable releases.
