### PR TITLE
operator: fix CES sync in identity-based batching

### LINKED ISSUE #31564: v1.15 Operator deletes and creates EndpointSlices on startup
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

First noticed that upgrading from v1.14 to v1.15 this happens. But now have had it happen even when v1.15 operator is just restarted.

If there are enough endpoints in the cluster and network policies exist. Pods lose connectivity for minutes at a time due to the delay between Delete and Create events.

### Cilium Version

1.15.2 7cf57829 2024-03-13T15:34:43+02:00 go version go1.21.8 linux/amd64

### Kernel Version

5.15.0-1055-aws #60~20.04.1-Ubuntu

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.13-eks-508b6b3", GitCommit:"26dbbc7674e3d15b579cec35cdd6aede55c1d426", GitTreeState:"clean", BuildDate:"2024-01-29T20:58:43Z", GoVersion:"go1.20.13", Compiler:"gc", Platform:"linux/amd64"}

### Regression

v1.14.x

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

https://github.com/cilium/cilium/pull/26836 seems relevant

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by thorn3r**
When CiliumEndpointSlice is enabled, any existing
CiliumEndpointSlices need to be added to the Cilium Operator's cache on start up.

The 'cesManagerIdentity' used for the identity-based slicing mode has 2 additional maps to track which CES map to which identity, and vice-versa. Currently these maps are not populated on the initial sync, causing the operator to believe the identity of a CiliumEndpoint has changed and removing it from the CES on first update. This causes all CiliumEndpointSlices to be recreated whenever the operator restarts.

This commit adds an override method to 'cesManagerIdentity' to populate the identity mapping on initial sync, allowing the operator to properly sync the existing CiliumEndpointSlices and avoid recreating them.

Fixes: #31564

```release-note
Fix synchronization of CiliumEndpointSlices when running the Cilium Operator in identity-based slicing mode.
```

### CODE REVIEW

**Comment by thorn3r** [comment]
lint workflow was broken due to hive renaming that was merged earlier today: https://github.com/cilium/cilium/pull/32020
updated the branch to fix this

File: operator/pkg/ciliumendpointslice/manager.go [hunk 1]
```diff
@@ -286,6 +288,16 @@ func (c *cesManagerIdentity) removeCESToIdentity(id int64, cesName CESName) {
 	delete(c.cesToIdentity, cesName)
 }
 
+// initializeMappingForCES overrides the same method on cesMgr and is used to
```
Comment (pippolo84) [inline operator/pkg/ciliumendpointslice/manager.go]: Nit: should be `// initializeMappingCEPtoCES overrides ...`

**Review by pippolo84 — APPROVED** [review]
Nice, thanks! :100: 

Just a non-blocking nit left inline.

File: operator/pkg/ciliumendpointslice/manager.go (hunk 1 above)
Comment (thorn3r) [reply operator/pkg/ciliumendpointslice/manager.go]: :laughing: good catch, thanks!
