### PR TITLE
k8s: Skip endpoints without conditions

### LINKED ISSUE #41194: CI: Conformance Ginkgo (ci-ginkgo): E2E Test (1.33, f14-datapath-service-ns-xdp-2): ClusterIP can be accessed when external access is enabled
## CI failure

```
• Failure [168.672 seconds]
K8sDatapathServicesTest
/home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:461
  Checks N/S loadbalancing
  /home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:461
    With ClusterIP external access
    /home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:461
      ClusterIP can be accessed when external access is enabled [It]
      /home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:515

      cannot curl to service IP from host: time-> DNS: '0.000021()', Connect: '0.000000',Transfer '0.000000', total '0.000000'command terminated with exit code 7
      
      Expected command: kubectl exec -n kube-system log-gatherer-mq9b8 -- curl -k --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 [http://10.96.127.51:80/](http://10.96.127.51/) -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
      To succeed, but it failed:
      Exitcode: 7 
      Err: exit status 7
      Stdout:
       	 time-> DNS: '0.000021()', Connect: '0.000000',Transfer '0.000000', total '0.000000'
      Stderr:
       	 command terminated with exit code 7
      	 
      

      /home/runner/work/cilium/cilium/test/k8s/services.go:711
```

This seems to be happening consistently: https://github.com/cilium/cilium/actions/workflows/conformance-ginkgo.yaml

Examples:
* [This run](https://github.com/cilium/cilium/actions/runs/16992137171/job/48174315532) from https://github.com/cilium/cilium/pull/41190
* [This run](https://github.com/cilium/cilium/actions/runs/16995613903/job/48185514653) from https://github.com/cilium/cilium/pull/37725

[cilium-sysdumps-1.33-f14-datapath-service-ns-xdp-2.zip](https://github.com/user-attachments/files/21800599/cilium-sysdumps-1.33-f14-datapath-service-ns-xdp-2.zip)
[cilium-junits (9).zip](https://github.com/user-attachments/files/21800603/cilium-junits.9.zip)

### PR DESCRIPTION
**Pull request by joamaki**
Skip endpoints in endpoint slices that have no conditions set as those are not yet ready to serve traffic. Before this they were marked quarantined which caused issues as the quarantined state was restored and not cleared until health checked (and we usually don't have a health checker). 

While we do want to keep unready endpoints around, we'll need to figure out what to mark them as that doesn't have the interaction with health checking. This is thus a temporary fix to go back to the old behavior. Opened issue https://github.com/cilium/cilium/issues/41244 to follow up on this.

Fixes: #41194
Fixes: 6f41c986bbfce ("loadbalancer: Keep non-serving terminating backends")

### CODE REVIEW

**Review by borkmann — APPROVED** [review]
ack lgtm, I presume this was also the behavior prior to the set of fixes, right?

**Comment by joamaki** [comment]
> ack lgtm, I presume this was also the behavior prior to the set of fixes, right?

Correct, prior to https://github.com/cilium/cilium/commit/6f41c986bbfceae31fde143b0e029970d343b83c we just skipped such backends.

File: pkg/k8s/endpoints.go [hunk 1]
```diff
@@ -288,9 +288,16 @@ func ParseEndpointSliceV1(logger *slog.Logger, ep *slim_discovery_v1.EndpointSli
 	}
 
 	for i, sub := range ep.Endpoints {
+		conditions := ParseEndpointConditionsV1(sub.Conditions)
+		if conditions == 0 {
```
Comment (marseel) [inline pkg/k8s/endpoints.go:292]: I don't think it's correct, if endpoint fails readiness check it will also have all false conditions.

Comment (joamaki) [reply pkg/k8s/endpoints.go:292]: True, we should be keeping these endpoints around for the existing connections. This however was the prior behavior. WDYT about merging this to fix CI and I'll work on figuring out how to properly handle this scenario?

**Review by marseel — APPROVED** [review]
from offline discussion: this change (revert) is incorrect as mentioned above  from service load balancing point of view, but it unblocks CI for everyone. Approve pending creating issue to track it.

**Comment by joamaki** [comment]
> from offline discussion: this change (revert) is incorrect as mentioned above from service load balancing point of view, but it unblocks CI for everyone. Approve pending creating issue to track it.

https://github.com/cilium/cilium/issues/41244
