### PR TITLE
Egress Rule supports CiliumCIDRGroup

### LINKED ISSUE #30597: CiliumCIDRGroup not work for egress rules
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am using CiliumCIDRGroup to optimize my cnp, however I found it only work for ingress rule, but not for egress rule.

Here is my spec

apiVersion: cilium.io/v2alpha1
kind: CiliumCIDRGroup
metadata:
  name: myipset
spec:
  externalCIDRs: 
  - 10.118.0.0/16
  - 10.119.0.0/16

apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: mycnp
  namespace: myns
spec:
  endpointSelector:
    matchLabels:
      app: test
  egress:
  - toCIDRSet:
    - cidrGroupRef: myipset

I see in the code CiliumCIDRGroup is only supported in ingress rule, but not egress rule, is there any specific consideration?
Also the doc doesn't mention this limitation.  If it can work for ingress, it is nature to assume it should also work for egress 

### Cilium Version

1.14

### Kernel Version

5.15

### Kubernetes Version

1.23

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by chaunceyjiang**
Fixes: #30597

```release-note
Add support for matching CiliumCIDRGroups in Egress policy rules
```

### CODE REVIEW

File: pkg/k8s/watchers/cilium_cidr_group_test.go [hunk 1]
```diff
@@ -266,6 +266,96 @@ func TestHasCIDRGroupRef(t *testing.T) {
...
+					TypeMeta: metav1.TypeMeta{
+						APIVersion: "cilium.io/v2",
+						Kind:       "CiliumNetworkPolicy",
+					},
+					ObjectMeta: metav1.ObjectMeta{
+						Name:      "test-policy",
+						Namespace: "test-namespace",
+					},
+					Spec: &api.Rule{
+						Ingress: []api.IngressRule{
```
Comment (pippolo84) [inline pkg/k8s/watchers/cilium_cidr_group_test.go]: We should test the Egress rule in this case

File: pkg/k8s/watchers/cilium_cidr_group_test.go [hunk 2]
```diff
@@ -680,10 +770,12 @@ func TestCIDRGroupRefsTranslate(t *testing.T) {
 					},
 					Spec: &api.Rule{
 						Ingress: []api.IngressRule{},
+						Egress:  []api.EgressRule{},
```
Comment (pippolo84) [inline pkg/k8s/watchers/cilium_cidr_group_test.go]: Nit: we should update the test case name in "nil FromCidrSet and ToCIDRSet rules"

File: pkg/k8s/watchers/cilium_cidr_group_test.go [hunk 3]
```diff
@@ -735,6 +829,17 @@ func TestCIDRGroupRefsTranslate(t *testing.T) {
 								},
 							},
 						},
+						Egress: []api.EgressRule{
```
Comment (pippolo84) [inline pkg/k8s/watchers/cilium_cidr_group_test.go]: Nit: we should update the test case name in "with FromCidrSet and ToCIDRSet rules"

File: pkg/k8s/watchers/cilium_cidr_group_test.go [hunk 4]
```diff
@@ -858,6 +1022,29 @@ func TestCIDRGroupRefsTranslate(t *testing.T) {
...
```
Comment (pippolo84) [inline pkg/k8s/watchers/cilium_cidr_group_test.go]: Nit: we should update the test case name in "with mixed FromCidrSet and ToCIDRSet rules"

**Review by pippolo84 — CHANGES_REQUESTED** [review]
Thanks for the PR! :pray: 
Overall LGTM, just some minor changes to do for the tests.

One thing left to update is the documentation here:

https://github.com/cilium/cilium/blob/475157148f009f85c2336c1cb003e73b370b852b/pkg/policy/api/cidr.go#L38

To account for Egress and EgressDeny

**Comment by chaunceyjiang** [comment]
https://github.com/cilium/cilium/actions/runs/7931518067/job/21655935864
- https://github.com/cilium/cilium/issues/30139

File: pkg/policy/k8s/cilium_cidr_group_test.go [hunk 5]
```diff
@@ -266,6 +266,96 @@ func TestHasCIDRGroupRef(t *testing.T) {
...
+								IngressCommonRule: api.IngressCommonRule{
+									FromCIDRSet: api.CIDRRuleSlice{
+										{
+											CIDRGroupRef: "cidr-group-1",
+										},
+									},
+								},
+							},
+						},
+					},
```
Comment (pippolo84) [inline pkg/policy/k8s/cilium_cidr_group_test.go]: Here we should have a policy with a reference to the `cidr-group-1` in the `Egress` field, not in the "ingress" one.
That's because the test case is about "CIDR in Spec (Egress)". The ability to reference a CIDRGroup in the Ingress field is already tested in the `CIDR in Spec (Ingress)` above.

File: pkg/policy/k8s/cilium_cidr_group_test.go [hunk 6]
```diff
@@ -266,6 +266,96 @@ func TestHasCIDRGroupRef(t *testing.T) {
...
+										FromCIDRSet: api.CIDRRuleSlice{
+											{
+												Cidr: "1.1.1.1/32",
+											},
+										},
+									},
+								},
+							},
+						},
+					},
```
Comment (pippolo84) [inline pkg/policy/k8s/cilium_cidr_group_test.go]: I think we can remove the `Specs` part for this test case, since we are testing it in the next one.

File: pkg/policy/k8s/cilium_cidr_group_test.go (hunk 5 above)
Comment (chaunceyjiang) [reply pkg/policy/k8s/cilium_cidr_group_test.go]: Updated.

File: pkg/policy/k8s/cilium_cidr_group_test.go (hunk 6 above)
Comment (chaunceyjiang) [reply pkg/policy/k8s/cilium_cidr_group_test.go]: Done.

**Review by pippolo84 — APPROVED** [review]
Thanks, LGTM! :100:

File: pkg/policy/api/cidr.go [hunk 7]
```diff
@@ -35,7 +35,7 @@ type CIDRRule struct {
 
 	// CIDRGroupRef is a reference to a CiliumCIDRGroup object.
 	// A CiliumCIDRGroup contains a list of CIDRs that the endpoint, subject to
-	// the rule, can (Ingress) or cannot (IngressDeny) receive connections from.
+	// the rule, can (Ingress/Egress) or cannot (IngressDeny/EgressDeny) receive connections from.
```
Comment (pippolo84) [inline pkg/policy/api/cidr.go]: > To account for Egress and EgressDeny

It turned out that we were actually missing support for CIDRGroupRef in IngressDeny, despite the docstring mentioning it (thanks to @gandro for the heads up). I opened a PR to fix that: https://github.com/cilium/cilium/pull/30933

Regarding this PR, I think this is fine as is, we just need to remove the "EgressDeny" part added here. Then, we can add support for EgressDeny in a follow up PR (IMHO this is better to avoid ending up with a PR too large).

Could you please remove the reference to `EgressDeny` here? Sorry for the confusion :pray:

**Review by nathanjsweet — APPROVED** [review]
Assuming doc changes. Thanks!

File: pkg/policy/api/cidr.go (hunk 7 above)
Comment (chaunceyjiang) [reply pkg/policy/api/cidr.go]: Updated.
