### PR TITLE
cmd: Detect BPF map root properly

### LINKED ISSUE #4521: CLI tools break if BPFFS mounts in non-default path /var/run/cilium/...
```
root@minikube:~# cilium bpf ct list global | wc -l
Error: Unable to open /sys/fs/bpf/tc/globals/cilium_ct6_global: Unable to get object /sys/fs/bpf/tc/globals/cilium_ct6_global: no such file or directory
0
```
```
root@minikube:~# mount | grep bpf
sysfs on /sys/fs/bpf type sysfs (rw,relatime)
/run/cilium/bpffs on /run/cilium/bpffs type bpf (rw,relatime)
/run/cilium/bpffs on /run/cilium/bpffs/xdp type bpf (rw,relatime)
/run/cilium/bpffs on /run/cilium/bpffs/ip type bpf (rw,relatime)
```

### PR DESCRIPTION
**Pull request by vadorovsky**
Cilium CLI should detect the map root on its own, using the
mountinfo package, because there is no way to get the information
from daemon process.

Fixes #4521

Signed-off-by: Michal Rostecki <mrostecki@suse.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4545)

### CODE REVIEW

**Comment by vadorovsky** [comment]
test-me-please

**Comment by vadorovsky** [comment]
@joestringer 

```
 mrostecki   bpffs-cli  …  github.com  cilium  cilium  kubectl --namespace=kube-system exec -ti cilium-zkrjk bash
root@minikube:~# cilium bpf ct list global | wc -l
6
root@minikube:~# cilium bpf ct list global        

ICMP IN 10.15.190.125:0 -> 10.15.0.1:0 related  expires=717 rx_packets=1 rx_bytes=50 tx_packets=0 tx_bytes=0 flags=10 revnat=0 src_sec_id=1
ICMP IN 10.15.190.125:2048 -> 10.15.0.1:0  expires=717 rx_packets=1 rx_bytes=50 tx_packets=1 tx_bytes=50 flags=0 revnat=0 src_sec_id=1
TCP IN 10.15.190.125:4240 -> 10.15.0.1:39274  expires=22254 rx_packets=5 rx_bytes=475 tx_packets=5 tx_bytes=464 flags=10 revnat=0 src_sec_id=1
TCP IN 10.15.190.125:4240 -> 10.15.0.1:39178  expires=22224 rx_packets=5 rx_bytes=475 tx_packets=5 tx_bytes=464 flags=10 revnat=0 src_sec_id=1

root@minikube:~# mount | grep bpf
sysfs on /sys/fs/bpf type sysfs (rw,relatime)
/run/cilium/bpffs on /run/cilium/bpffs type bpf (rw,relatime)
/run/cilium/bpffs on /run/cilium/bpffs/xdp type bpf (rw,relatime)
/run/cilium/bpffs on /run/cilium/bpffs/ip type bpf (rw,relatime)
```

File: pkg/bpf/bpffs.go [hunk 1]
```diff
@@ -72,11 +72,37 @@ func MapPrefixPath() string {
...
 func MapPath(name string) string {
 	once.Do(lockDown)
 	return filepath.Join(mapRoot, mapPrefix, name)
 }
 
+// MapPathCLI returns a path for a BPF map with a given name.
+// NOTE: This function should be used by CLI or any component which is not
+// daemon.
+func MapPathCLI(name string) (string, error) {
+	var mapRootMountInfo *mountinfo.MountInfo
```
Comment (tgraf) [inline pkg/bpf/bpffs.go]: This var declaration is unnecessary

File: pkg/bpf/bpffs.go [hunk 2]
```diff
@@ -72,11 +72,37 @@ func MapPrefixPath() string {
...
+// NOTE: This function should be used only by cilium daemon.
 func MapPath(name string) string {
 	once.Do(lockDown)
 	return filepath.Join(mapRoot, mapPrefix, name)
 }
 
+// MapPathCLI returns a path for a BPF map with a given name.
+// NOTE: This function should be used by CLI or any component which is not
+// daemon.
+func MapPathCLI(name string) (string, error) {
```
Comment (tgraf) [inline pkg/bpf/bpffs.go]: Instead of doing this, can we detect inside of `MapPath()` whether we run as part of cilium-agent and fall back to using mountinfo instead? I really dislike encoding CLI logic into the generic bpf package.

If we are not running in the agent and we can't rely on mountinfo we might as well just error out with Fatal from within the `MapPath()` function.

**Review by tgraf — CHANGES_REQUESTED** [review]

File: pkg/bpf/bpffs.go [hunk 3]
```diff
@@ -72,11 +72,37 @@ func MapPrefixPath() string {
...
+	var mapRootMountInfo *mountinfo.MountInfo
+	mountInfos, err := mountinfo.GetMountInfo()
+	if err != nil {
+		return "", err
+	}
+
+	for _, mountInfo := range mountInfos {
+		if mountInfo.FilesystemType == mountinfo.FilesystemTypeBPFFS {
+			mapRootMountInfo = mountInfo
+			break
```
Comment (tgraf) [inline pkg/bpf/bpffs.go]: Just return directly from here instead of using break.

**Review by tgraf — CHANGES_REQUESTED** [review]

**Comment by vadorovsky** [comment]
@tgraf Done. Although there is one problem about checking whether we run as a part of cilium-agent. From now, `MapRoot` function's signature changed, because it returns `error`. I needed to do a lot of changes in many modules to handle this error. It seems to be quite insecure for a quick bugfix which needs to be backported.

I pushed my old code to the another branch - https://github.com/mrostecki/cilium/tree/bpffs-cli-old

**Comment by vadorovsky** [comment]
test-me-please

**Comment by vadorovsky** [comment]
Seems like CI failed on etcd watcher, let's keep the link to logs:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4233/consoleFull

**Comment by vadorovsky** [comment]
test-me-please

**Comment by tgraf** [comment]
> Done. Although there is one problem about checking whether we run as a part of cilium-agent. From now, MapRoot function's signature changed, because it returns error. I needed to do a lot of changes in many modules to handle this error. It seems to be quite insecure for a quick bugfix which needs to be backported.

All of the error handlers do `Fatal()` and there is no way for us to ever recover in these scenarios. How about we just `Fatal()` in `MapRoot()` itself?

**Comment by vadorovsky** [comment]
@tgraf Done, I used `log.Fatal`.

**Comment by vadorovsky** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
The CI failure may have uncovered a real bug

**Comment by joestringer** [comment]
From the CI:
```
17:07:00 level=fatal msg="Could not find BPF map root"
```

FWIW, this is a unit test so you can probably shortcut reproducing it via `make unit-tests`.

**Comment by vadorovsky** [comment]
test-me-please

**Comment by vadorovsky** [comment]
@tgraf @joestringer The problem was that daemon unit tests are trying to run the whole daemon, including the bpffs functionality and `MapRoot` calls occur even before bpffs mount. So the old behavior of `MapRoot` should work both for `cilium-agent` and `daemon.test` binaries.

**Comment by vadorovsky** [comment]
@tgraf @joestringer Everything green now
