### PR TITLE
daemon: implemented a endpoint status

### LINKED ISSUE #128: Better feedback loop when compilation fails
Due to the lack of the labels being available at network plumbing time. We have to request the labels asynchronously and then generate & compile the code after the container has already been started. If compilation or generation fails for some reason, we have no choice but to log the error in the logfile which is often not observed by the user. This leaves the user with an unconnected container.

Provide better feedback:
- Work on getting labels earlier and do generation synchronously when orchestration system asks for networking to be setup.
- Status field in cilium endpoint structure indicating the failure
- Consider delaying returning from networking call until labels have been retrieved

### PR DESCRIPTION
**Pull request by aanm**
```
$ cilium endpoint inspect endpoint 35542
Endpoint status: 
2016-09-19T21:01:58-07:00 - OK - Policy regenerated
2016-09-19T21:01:58-07:00 - OK - Regenerated BPF code
2016-09-19T21:01:58-07:00 - OK - Policy regenerated
2016-09-19T21:01:58-07:00 - OK - Successfully regenerated program for endpoint
2016-09-19T21:00:58-07:00 - OK - Policy regenerated
2016-09-19T21:00:58-07:00 - OK - Successfully regenerated program for endpoint
2016-09-19T20:58:47-07:00 - OK - Policy regenerated
$ cilium endpoint list
ENDPOINT ID   LABEL ID   LABELS (source:key[=value])   IPv6                     IPv4          STATUS                                                         
35542         259        cilium:io.cilium.client       f00d::c0a8:210b:0:8ad6   10.1.28.238   2016-09-19T21:01:58-07:00 - OK - Policy regenerated
```

With the cilium endpoint status the user will be able to see the last
256 log messages for a particular endpoint when it's being inspected.

Fixes #128 
Signed-off-by: André Martins andre@cilium.io

### CODE REVIEW

File: cilium/endpoint/endpoint.go [hunk 1]
```diff
@@ -479,7 +483,7 @@ func removePolicyKey(ctx *cli.Context) {
 }
 
 func dumpFirstEndpoint(w *tabwriter.Writer, ep *types.Endpoint, seclabel string, label string) {
-	fmt.Fprintf(w, "%d\t%s\t%s\t%s\t%s\t\n", ep.ID, seclabel, label, ep.IPv6.String(), ep.IPv4.String())
+	fmt.Fprintf(w, "%d\t%s\t%s\t%s\t%s\t%s\t\n", ep.ID, seclabel, label, ep.IPv6.String(), ep.IPv4.String(), ep.Status.String())
```
Comment (tgraf) [inline cilium/endpoint/endpoint.go:486]: (For a follow-up commit: Need to start making the columns more compact. Maybe "ENDPOINT ID" => "ID". The ID can never be more than 6 digits, label id is never more than 5 digits.)

The status itself. I would drop the timemstamp and verbose message. Keep it to a simple: { OK | BUILD | FAIL } to indicate status.

File: cilium/endpoint/endpoint.go [hunk 2]
```diff
@@ -287,7 +287,11 @@ func dumpLXCInfo(ctx *cli.Context) {
 		return
 	}
 
+	es := ep.Status.DeepCopy()
+	// We will omit the endpoints status so we don't duplicate them
+	ep.Status = types.EndpointStatus{}
 	fmt.Printf("Endpoint %d\n%s\n", ep.ID, ep)
+	fmt.Printf("Endpoint status: \n%s\n", es.DumpLog())
```
Comment (tgraf) [inline cilium/endpoint/endpoint.go]: :+1:

File: common/types/endpoint.go [hunk 3]
```diff
@@ -138,6 +142,60 @@ type Endpoint struct {
...
+}
+
+type statusLog struct {
+	Status    Status    `json:"status"`
+	Timestamp time.Time `json:"timestamp"`
+}
+
+type EndpointStatus struct {
+	Log     *[maxLogs]*statusLog `json:"log"`
+	Index   uint8                `json:"index"`
```
Comment (tgraf) [inline common/types/endpoint.go]: You limit this both with the `uint8` and maxLogs. Chaning maxLogs down the line will not work. I suggest to use int here and limit exclusively by maxLogs.

File: daemon/daemon/ct.go [hunk 4]
```diff
@@ -35,6 +36,7 @@ func runGC(e *types.Endpoint, prefix string, ctType ctmap.CtType) {
 	fd, err := bpf.ObjGet(file)
 	if err != nil {
 		log.Warningf("Unable to open CT map %s: %s\n", file, err)
+		e.LogStatus(types.Warning, fmt.Sprintf("Unable to open CT map %s: %s", file, err))
```
Comment (tgraf) [inline daemon/daemon/ct.go:39]: A helper which does both, log and update endpoint status would be great

File: daemon/daemon/policy.go [hunk 5]
```diff
@@ -265,7 +266,12 @@ func (d *Daemon) triggerPolicyUpdates(added []uint32) {
 	}
 
 	for _, ep := range d.endpoints {
-		d.regenerateEndpointPolicy(ep, true)
+		err := d.regenerateEndpointPolicy(ep, true)
+		if err != nil {
+			ep.LogStatus(types.Failure, err.Error())
+		} else {
+			ep.LogStatusOK("Policy regenerated")
```
Comment (tgraf) [inline daemon/daemon/policy.go:273]: This could potentially become very verbose. Let's keep it in but we might have to restrict it later.

File: common/types/endpoint.go (hunk 3 above)
Comment (aanm) [reply common/types/endpoint.go]: I know, I did that because I didn't want to write the following code eheh:

```
func (e *Endpoint) LogStatus(code StatusCode, msg string) {
....
      e.Status.Index++
      if e.Status.Index >= maxLogs {
         e.Status.Index = 0
      }
```

I'll make that change ;)

File: daemon/daemon/ct.go (hunk 4 above)
Comment (aanm) [reply daemon/daemon/ct.go:39]: A little difficult, the logger itself has different types of printing the log messages (warning,debug,info, etc). Do you have any ideas on how to do that?

Comment (tgraf) [reply daemon/daemon/ct.go:39]: OK, leave it for now then.

File: common/types/endpoint.go [hunk 6]
```diff
@@ -343,3 +414,38 @@ func (e *Endpoint) InvalidatePolicy() {
 		e.Consumable.Iteration = 0
 	}
 }
+
+func (e *Endpoint) LogStatus(code StatusCode, msg string) {
```
Comment (tgraf) [inline common/types/endpoint.go:409]: So this creates a stack of log messages which are categorized which is great. I don't think we can always refer to the last entry as the current status though. A warning may be followed by an OK log message but the user will still want to see the warning. A reconfiguration event by the user may fix the warning in which case the status should then switch back to OK.

I think we'll need both, a log of relevant status messages which preserve the history for particular endpoint transitions.

In addition to that, a managed status for health field which represents the current state of the endpoint:
- OK: Endpoint is functional in the configuration provided
- Build: Endpoint is currently undergoing a rebuild of the programs
- Warn: A non fatal warning has occurred since the last configuration/poilcy change but the endpoint should be partially operational
- Fail: A fatal warning has occurred, the endpoint is not functional.

**Review by tgraf — CHANGES_REQUESTED** [review]

File: common/types/endpoint.go (hunk 6 above)
Comment (aanm) [reply common/types/endpoint.go:409]: Hmm that's true. But how can we define if an endpoint is functional? I was assuming that, since the last endpoint operation was OK then the endpoint is operational. I consider the log status messages are relevant and sufficient, so far so good.

What I propose then is to develop function that performs particular tests (TBD) on that endpoint. 
That function/tests would be triggered whenever the user inspects the endpoint or lists the endpoints on the CLI. The result of those tests would then result on your proposal for status health (OK, Build, Warn, Fail)

Comment (tgraf) [reply common/types/endpoint.go:409]: I'm fine with merging what you have for now and then address this in a follow-up commit.

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
Pending CI build fix, this LGTM

File: common/types/endpoint.go (hunk 6 above)
Comment (aanm) [reply common/types/endpoint.go:409]: https://github.com/cilium/cilium/projects/2#card-203426

**Comment by aanm** [comment]
@tgraf can you review the commit 1ca79ac? After your LGTM I'll squash them both.

**Review by tgraf — APPROVED** [review]
