### PR TITLE
cilium-dbg: show encryption status even if daemon is unresponsive

### LINKED ISSUE #31897: `cilium encrypt status` fails when agents are down
In a sysdump for a cluster where all Cilium agents are down:
```
$ cat cilium-encrypt-status.md 
Error: Cannot get daemon encryption status: Get "http://localhost/v1/healthz": dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
> Error while running 'cilium encrypt status':  exit status 1
```
That shouldn't be happening: we should display what we can from Linux state and BPF maps. Only the state of IPsec/WireGuard enablement should require a connection to the agent.

### PR DESCRIPTION
**Pull request by bersoare**
fetch status directly from the kernel to allow
showing wireguard status even if the agent daemon is down

Fixes: [#31897](https://github.com/cilium/cilium/issues/31897)

```
cilium encrypt status shows ipsec/wg tunneling configuration even when daemon is unresponsive 
```

### CODE REVIEW

**Comment by bersoare** [comment]
there is probably a way to identify the ipsec states added by cilium among other states.
moving pr back to draft until it gets implemented

File: cilium-dbg/cmd/encrypt_status.go [hunk 1]
```diff
@@ -185,6 +208,10 @@ func maxSequenceNumber() (string, error) {
 	return fmt.Sprintf("0x%x/0xffffffffffffffff", maxSeqNum), nil
 }
 
+// isDecryptionInterface returns whether we thing an interface is used for decryption or not.
+// FIXME: this simply checks for the existence of the cil_from_network or cil_from_netdev programs
+// in the filter list of the interface - ideally there should be a less ambiguous way of knowing if
+// an interface is used for decryption such as evaluating the addresses in the xfrm states.
```
Comment (pchaigno) [inline cilium-dbg/cmd/encrypt_status.go]: I'd argue that's more ambiguous :sweat_smile: I think I prefer if we keep it simple and tied to the function of the device (i.e., a hook point for BPF programs).

File: cilium-dbg/cmd/encrypt_status.go [hunk 2]
```diff
@@ -57,71 +58,107 @@ func init() {
...
-		return models.EncryptionStatus{}, err
+		result.Msg = err.Error()
+	} else {
+		result.Mode = resp.Payload.Encryption.Mode
+	}
+
+	result.Ipsec, err = dumpIPsecStatus()
+	if err != nil {
+		return result, err
 	}
```
Comment (pchaigno) [inline cilium-dbg/cmd/encrypt_status.go:197]: At least for IPsec, I'm not sure I like this approach. I think I'd prefer if we don't try to deduce anything for that field if we can't reach the agent. This command is often used in error cases so I'd prefer if we don't tie the status to the presence of XFRM states. We can easily get in a situation where IPsec is disabled in the agent, but there are still states lying around, or IPsec is enabled, but we failed to install any states.

**Review by pchaigno — CHANGES_REQUESTED** [review]
See comments below. I'm not sure we should try to be smart for that field.

File: cilium-dbg/cmd/encrypt_status.go (hunk 2 above)
Comment (ldelossa) [reply cilium-dbg/cmd/encrypt_status.go:197]: I totally get this point. 

It feels a bit odd to me that we want to understand Cilium's state during a period of time where Cilium's state is unreliable. 

Coupled with the fact that we don't truly have a solid way of identifying what state/policies. 

That being said, what is your opinion about the original linked issue then @pchaigno - a noop?

Comment (bersoare) [reply cilium-dbg/cmd/encrypt_status.go:197]: not sure i understand what the problem here would be. to my knowledge, the source of truth of the ipsec configuration is the kernel, and that is not changing in the pr. the problem described in the issue https://github.com/cilium/cilium/issues/31897 is that we get no output if the cli can't communicate with the agent, and we should still be able to dump whatever is in the kernel - and it is what i tried to address in this pr

File: cilium-dbg/cmd/encrypt_status.go (hunk 1 above)
Comment (bersoare) [reply cilium-dbg/cmd/encrypt_status.go]: the current code assumes that if an interface has a bpf program on one of its filters that match a certain naming scheme, it is an encryption/decryption interface. but taking the information from the actual element than deals with the encryption (ex: xfrm policies addresses) is a more educated guess on whether an interface is doing encryption or not.

File: cilium-dbg/cmd/encrypt_status.go (hunk 2 above)
Comment (pchaigno) [reply cilium-dbg/cmd/encrypt_status.go:197]: > That being said, what is your opinion about the original linked issue then @pchaigno - a noop?

The point of the original issue is that we don't display anything at all if the agent can't be reached, even though only the first field depends on the agent. I think we should keep displaying other fields which don't rely on the agent.

> to my knowledge, the source of truth of the ipsec configuration is the kernel, and that is not changing in the pr.

Unfortunately, it's a bit more complicated. The agent and the kernel both have part of the "truth". The error scenarios have described above have happened in the past.

Comment (pchaigno) [reply cilium-dbg/cmd/encrypt_status.go:197]: Let me add an example to make it more concrete:
Instead of:
```
$ cilium-dbg encrypt status
Error: Cannot get daemon encryption status: Get "http://localhost/v1/healthz": dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
```
I'd like us to output:
```
$ cilium-dbg encrypt status
Encryption: Couldn't connect to agent                     
Decryption interface(s): eth0
Keys in use: 8                         
Max Seq. Number: 0x5f/0xffffffffffffffff
Errors: 0
```

Comment (bersoare) [reply cilium-dbg/cmd/encrypt_status.go:197]: that is not much different from what we have in the pr:
```
# crictl exec -it $(crictl ps | grep cilium-agent | cut -d " " -f 1) cilium encrypt status
Msg: Get "http://localhost/v1/healthz": dial unix /var/run/cilium/cilium.sock: connect: no such file or directoryEncryption:
Decryption interface(s):
Keys in use: 8
Max Seq. Number: N/A
Errors: 1518
	XfrmInNoStates: 11
	XfrmOutPolBlock: 1507
```

There is a `Msg` field in the status, and to me it looks like it's the right place to propagate errors. The encryption field is a typed string that represents an encryption type i believe, and `Couldn't connect to agent ` doesn't really look like an encryption mode. sounds a bit confusing to me.

but if regardless of that line of thought you still think it makes sense to display it as you pointed out, im happy to change it. let me know what you think

File: cilium-dbg/cmd/encrypt_status.go (hunk 1 above)
Comment (pchaigno) [reply cilium-dbg/cmd/encrypt_status.go]: There's no guarantee that the address(es) on the decryption interface(s) will match the addresses on the XFRM policies (if any). The goal here is simply to identify interfaces that we expect to be carrying the BPF logic for IPsec decryption. Matching on the naming scheme isn't ideal, but short of checking the BPF bytecode, I'm not sure we can do better.

Comment (bersoare) [reply cilium-dbg/cmd/encrypt_status.go]: i can drop the comment, then

**Comment by bersoare** [comment]
output:
```
ipsec enabled

root@kind-worker:/# crictl exec -it $(crictl ps | grep cilium-agent | cut -d " " -f 1) cilium encrypt status
Encryption: IPsec
Decryption interface(s):
Keys in use: 8
Max Seq. Number: 0xd7/0xffffffffffffffff
Errors: 0

// delete socket
root@kind-worker:/# rm /var/run/cilium/*sock
root@kind-worker:/# crictl exec -it $(crictl ps | grep cilium-agent | cut -d " " -f 1) cilium encrypt status
Msg: Get "http://localhost/v1/healthz": dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
Encryption:
Decryption interface(s):
Keys in use: 8
Max Seq. Number: 0x198/0xffffffffffffffff
Errors: 0

wireguard enabled

root@kind-worker:/# crictl exec -it $(crictl ps | grep cilium-agent | cut -d " " -f 1) cilium encrypt status
Encryption: Wireguard
Interface: cilium_wg0
	Public key: +wBNbuYb5qKJ2ir7sPGt8/ustRO0eEzHnWN7BP+yLmA=
	Number of peers: 1

// delete socket
root@kind-worker:/# rm /var/run/cilium/*sock
root@kind-worker:/# crictl exec -it $(crictl ps | grep cilium-agent | cut -d " " -f 1) cilium encrypt status
Msg: Get "http://localhost/v1/healthz": dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
Encryption:
Interface: cilium_wg0
	Public key: +wBNbuYb5qKJ2ir7sPGt8/ustRO0eEzHnWN7BP+yLmA=
	Number of peers: 1
root@kind-worker:/#

disabled:

root@kind-worker:/# crictl exec -it $(crictl ps | grep cilium-agent | cut -d " " -f 1) cilium encrypt status
Encryption: Disabled

root@kind-worker:/# rm /var/run/cilium/*sock
root@kind-worker:/# crictl exec -it $(crictl ps | grep cilium-agent | cut -d " " -f 1) cilium encrypt status
Msg: Get "http://localhost/v1/healthz": dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
Encryption:
```

@pchaigno , how does that look to you?

File: cilium-dbg/cmd/encrypt_status.go (hunk 2 above)
Comment (pchaigno) [reply cilium-dbg/cmd/encrypt_status.go:197]: I think I misunderstood the code changes when I initially read them. The output looks good to me!

I'm not sure however what you mean by:

> fetch status directly from the kernel to allow showing wireguard and ipsec status even if the agent daemon is down

~~You haven't changed where the status (whether that's the `Encryption` field or the whole command output) is taken from, right?~~ I see what you meant now. Maybe it's worth explaining a bit more what the commit is doing.

Comment (pchaigno) [reply cilium-dbg/cmd/encrypt_status.go:197]: I wonder if we couldn't go about this the other way around: check WireGuard first and if there's no WireGuard setup, we assume IPsec and just display stuff as is. If IPsec is also disabled, we will get null data, but I think that's fine.

That way we don't tie the assumption that IPsec is disabled on the XFRM states being there. It does assume instead that WireGuard is disabled if there are no WireGuard devices.

File: cilium-dbg/cmd/encrypt_status.go [hunk 3]
```diff
@@ -57,71 +58,93 @@ func init() {
...
 	params := daemon.NewGetHealthzParamsWithTimeout(timeout)
 	params.SetBrief(&brief)
+
 	resp, err := client.Daemon.GetHealthz(params)
 	if err != nil {
-		return models.EncryptionStatus{}, err
+		result.Msg = err.Error()
+	} else {
+		result.Mode = resp.Payload.Encryption.Mode
 	}
```
Comment (smagnani96) [inline cilium-dbg/cmd/encrypt_status.go:198]:
```suggestion
	enc := resp.Payload.Encryption
	switch enc.Mode {
	case models.EncryptionStatusModeIPsec:
		return dumpIPsecStatus()
	case models.EncryptionStatusModeWireguard:
		return dumpWireGuardStatusFromAgent(enc), nil
	default:
		// here let's not return err in case cilium_wg0 does not exist
		result.Wireguard, err = dumpWireGuardStatus()
		if err != nil {
			return result, err
		}
		result.Ipsec, err = dumpIPsecStatus()
		if err != nil {
			return result, err
		}
	}
	return result, nil 
```

What's your opinion on this?
* if we received a reply from agent:
   * If Wireguard, we already have data to display, so use the response payload
   * If IPSec, skip wireguard
* in case the agent did not respond, try both and don't fail at obvious errors (eg if cilium_wg0 does not exist we should still continue and check IPSec)

File: cilium-dbg/cmd/encrypt_status.go [hunk 4]
```diff
@@ -57,71 +58,93 @@ func init() {
...
-		status.Wireguard.Interfaces = append(status.Wireguard.Interfaces, &models.WireguardInterface{
-			Name:      wg.Name,
-			PublicKey: wg.PublicKey,
-			PeerCount: wg.PeerCount,
+func dumpWireGuardStatus() (*models.WireguardStatus, error) {
+	wgClient, err := wgctrl.New()
+	if err != nil {
+		return nil, err
+	}
+
```
Comment (smagnani96) [inline cilium-dbg/cmd/encrypt_status.go:267]:
```suggestion
  defer wgClient.Close()

```

File: cilium-dbg/cmd/encrypt_status.go [hunk 5]
```diff
@@ -57,71 +58,93 @@ func init() {
...
+	devices, err := wgClient.Devices()
```
Comment (smagnani96) [inline cilium-dbg/cmd/encrypt_status.go]: Nice, but I'd use directly the `types.IfaceName` value (cilium_wg0) as in the `WireguardAgent.Status` function [here](https://github.com/cilium/cilium/blob/main/pkg/wireguard/agent/agent.go#L840). The aim in this case (fallback, no reply from agent) is exactly to mimic that. If enabled we have at max 1 wireguard interface. I'm afraid with `wgClient.Devices()` we would pick also non-Cilium related ones, if any 😃

File: cilium-dbg/cmd/encrypt_status.go [hunk 6]
```diff
@@ -223,17 +251,21 @@ func getDecryptionInterfaces() ([]string, error) {
 }
 
 func printEncryptionStatus(status models.EncryptionStatus) {
+	if status.Msg != "" {
+		fmt.Printf("Msg: %s\n", status.Msg)
+	}
+
 	fmt.Printf("Encryption: %-26s\n", status.Mode)
-	switch status.Mode {
```
Comment (smagnani96) [inline cilium-dbg/cmd/encrypt_status.go:286]: I'd suggest trying to use `status.Mode` from agent reply, or to set it after the inference, and preserve the switch here. That would avoid dumping info for both IPSec and Wireguard when one of them is not enabled (dirty data from previous state).

For instance, if the WireGuard inference did not fail (interface exists and wgClient.Device(types.IfaceName) do not fail) we set mode to Wireguard. Same for IPSec.

**Review by smagnani96 — CHANGES_REQUESTED** [review]
Provided general comments + WireGuard-specific.
I very like that we're still somehow able to display data when the agent does not reply, nice!
PR is on the right track, I think it simply needs another small iteration for few adjustments. Let me know 😃

File: cilium-dbg/cmd/encrypt_status.go (hunk 6 above)
Comment (bersoare) [reply cilium-dbg/cmd/encrypt_status.go:286]: i think displaying erratic data that was left over still has its value as it points out to a failure in the agent, which didn't clear up state when it was supposed to.
there's no inference on the encryption type, though. if the agent does not respond, the field is not populated. that way, we can both know what mode is explicitly enabled and whether there is any state on the not enabled feature. an operator could take that as a hint that there is a failure in the agent instead of silently ignoring the stale state (esp since this is a debug command, taken during times people want to understand what really is going on)

File: cilium-dbg/cmd/encrypt_status.go (hunk 3 above)
Comment (bersoare) [reply cilium-dbg/cmd/encrypt_status.go:198]: i believe there is value in retrieving everything regardless, see https://github.com/cilium/cilium/pull/41827#discussion_r2378287723

File: cilium-dbg/cmd/encrypt_status.go (hunk 6 above)
Comment (pchaigno) [reply cilium-dbg/cmd/encrypt_status.go:286]: > i think displaying erratic data that was left over still has its value as it points out to a failure in the agent, which didn't clear up state when it was supposed to.

I agree with this. I'm starting to wonder if we shouldn't just split up the command into an `ipsec status` and a `wireguard status` commands.

File: cilium-dbg/cmd/encrypt_status.go (hunk 5 above)
Comment (bersoare) [reply cilium-dbg/cmd/encrypt_status.go]: yes! that makes sense. just like we did in the ipsec (we filter our states by the value we know the agent added to the states it manages) - this way we can avoid returning state that was added by non-cilium things on the node
i'll implement that

File: cilium-dbg/cmd/encrypt_status.go (hunk 2 above)
Comment (bersoare) [reply cilium-dbg/cmd/encrypt_status.go:197]: @pchaigno ,
the way i was looking at what would be expected from this command is that:
- it contacts the agent, and see what encryption configuration is there (what do i expect to have in the kernel? wireguard or ipsec?)
- regardless of the result obtained from contacting the agent, search for both ipsec and wireguard state from the kernel

with that, some of the possible outcomes for the command (with the pr changes in) are:
- agent responds with an encryption mode that is enabled, and the debug command returns the actual state from the expected tunneling configuration in the kernel. this is the usual path and is what we want to see when there are no issues
- agent responds with an encryption mode that is enabled, and the debug command returns the actual state from the kernel and displays two different tunneling configurations. this can indicate there is an issue with the agent logic
- agent fails to respond, but the command finds tunneling configuration in the kernel. we still see what the kernel configuration looks like (both for wg and ipsec). 

i see that there is value on all the three outcomes - and we keep the expected state (what does the agent say we should have? is it ipsec wireguard or none?) and actual state (is there ipsec and/or wireguard configuration?) separate, and the command can ultimately help identifying a mismatch between the two (expected state vs actual state).

let me know what you think.

File: cilium-dbg/cmd/encrypt_status.go (hunk 1 above)
Comment (bersoare) [reply cilium-dbg/cmd/encrypt_status.go]: @pchaigno , im still not very familiar with how the ipsec plumbing is done - but can you give me an example where the ipsec state is set up with an address but the encryption interface is a different one? (or a decryption interface without an ip)
im thinking here that we could maybe improve this logic to be more accurate and do some extra checking, considering the different arrangements in the configuration

File: cilium-dbg/cmd/encrypt_status.go (hunk 5 above)
Comment (bersoare) [reply cilium-dbg/cmd/encrypt_status.go]: https://github.com/cilium/cilium/pull/41827/commits/2f072993947ac372f77d9f46e1c196e26560e184

File: cilium-dbg/cmd/encrypt_status.go (hunk 3 above)
Comment (smagnani96) [reply cilium-dbg/cmd/encrypt_status.go:198]: Understood, I see... but I'd not ignore the agent reply.
That would be the expected outcome. We can still do our lookup here and if it doesn't match then we report the diff.

File: cilium-dbg/cmd/encrypt_status.go (hunk 5 above)
Comment (smagnani96) [reply cilium-dbg/cmd/encrypt_status.go]:
```go
dev, err := wgClient.Device(types.IfaceName)
if err != nil {
	return fmt.Errorf("failed to obtain WireGuard device: %w", err)
}
```

Can directly use this rather than getting all devices and loop.
Feel free to mark this as solved if ok.

File: cilium-dbg/cmd/encrypt_status.go (hunk 6 above)
Comment (smagnani96) [reply cilium-dbg/cmd/encrypt_status.go:286]: It makes sense, it is just that we don't officially support switching encryption type in the same cluster 🤔
Anyway, feels like that's a good way to go to inspect such possible situation.
Feel free to solve this conversation.

File: cilium-dbg/cmd/encrypt_status.go (hunk 3 above)
Comment (bersoare) [reply cilium-dbg/cmd/encrypt_status.go:198]: the agent reply isn't ignored, really - the difference is that the reply is only used to populate the status field (the one that says ipsec or wireguard)

File: cilium-dbg/cmd/encrypt_status.go (hunk 5 above)
Comment (bersoare) [reply cilium-dbg/cmd/encrypt_status.go]: oh, it makes sense - let me implement that

File: cilium-dbg/cmd/encrypt_status.go (hunk 3 above)
Comment (smagnani96) [reply cilium-dbg/cmd/encrypt_status.go:198]: 1. `cilium debuginfo` calls WGAgent.Status(true) and gets peers info
2. `cilium encrypt status -o json` calls WGAgent.Status(false), no peer info, but it at least returns the list of interfaces (cilium_wg0)

You would basically use the agent reply to check only if IPSec/WG, and then populate other fields by running commands anyway, right? If so, WGAgent.Status() would be useful also for (1).

That's just to make sure I'm getting the point, thanks for the comprehension 🙏🏼

File: cilium-dbg/cmd/encrypt_status.go (hunk 1 above)
Comment (pchaigno) [reply cilium-dbg/cmd/encrypt_status.go]: > can you give me an example where the ipsec state is set up with an address but the encryption interface is a different one?

Whenever `--use-cilium-internal-ip-for-ipsec` is set.

In any case, we tend to try to avoid FIXME/TODO comments in the sources. If we see something that can be improved, let's open an issue about it.

File: cilium-dbg/cmd/encrypt_status.go (hunk 2 above)
Comment (pchaigno) [reply cilium-dbg/cmd/encrypt_status.go:197]: Let's go with current approach for now. I think we should just have separate commands for IPsec and WireGuard anyway, but we can handle that in a separate PR.

File: cilium-dbg/cmd/encrypt_status.go (hunk 1 above)
Comment (bersoare) [reply cilium-dbg/cmd/encrypt_status.go]: makes sense, i'll remove the comment - and will also open an issue for us to investigate

File: cilium-dbg/cmd/encrypt_status.go (hunk 3 above)
Comment (bersoare) [reply cilium-dbg/cmd/encrypt_status.go:198]: the big difference between the debuginfo command and the `cilium encrypt status` is that the debuginfo call contacts the agent and the Status() method relies on agent state (like a.wgConn, a.wgConfig, and so on) - which aren't available at the cilium-dbg runtime - unless the agent can be contacted successfully.

so you are basically saying that (at least for wireguard), if we are able to contact the agent in the cilium-dbg command, use the agent to retrieve the wg state from the kernel, else fallback to using the wireguard library to query for the state. did i get it right?

Comment (smagnani96) [reply cilium-dbg/cmd/encrypt_status.go:198]: What I'm saying is that IF the agent replies, we could double check that the reply (list of interfaces) is at least included in the state you're retrieving. In case they're mismatching, I'd add two lines in the Msg.
What do you think?

File: cilium-dbg/cmd/encrypt_status.go [hunk 7]
```diff
@@ -87,71 +92,110 @@ func init() {
...
+	wgDevice, err := wgClient.Device(wgTypes.IfaceName)
+	if err != nil {
+		// if we fail here, we probably dont have an interface, so just bail out
+		return nil, nil
 	}
-	return status
+
+	var result models.WireguardStatus
+
+	result.Interfaces = append(result.Interfaces, &models.WireguardInterface{
```
Comment (smagnani96) [inline cilium-dbg/cmd/encrypt_status.go:278]: Commit `cilium-dbg: filter wireguard interfaces for cilium ifname` could be squashed straight in the 1st commit. 
Let's also double-check if there's anything from other commits that could be squashed so we keep clean history.

**Review by smagnani96 — CHANGES_REQUESTED** [review]
Overall LGTM. We can squash some commit (see my review) for clarity.
Let me know, happy to take another sight 👀

File: cilium-dbg/cmd/encrypt_status.go (hunk 3 above)
Comment (bersoare) [reply cilium-dbg/cmd/encrypt_status.go:198]: it makes sense!

File: cilium-dbg/cmd/encrypt_status.go [hunk 8]
```diff
@@ -86,72 +94,183 @@ func init() {
...
+	for _, expectedIntf := range expected.Interfaces {
+		if !containsInterface(actual.Interfaces, expectedIntf) {
+			return fmt.Errorf("%w: interface %s not found or did not match in the expected set of interfaces", errWireguardStateMismatch, expectedIntf.Name)
+		}
+	}
+
+	return nil
+}
+
 func getEncryptionStatus() (models.EncryptionStatus, error) {
```
Comment (smagnani96) [inline cilium-dbg/cmd/encrypt_status.go]: No need anymore to return an `error` here. (see patch in my comment)

File: cilium-dbg/cmd/encrypt_status.go [hunk 9]
```diff
@@ -86,72 +94,183 @@ func init() {
...
+		// if we fail here, we probably dont have an interface, so just bail out
+		return nil, nil
 	}
-	return status
+
+	var result models.WireguardStatus
+
+	result.Interfaces = append(result.Interfaces, &models.WireguardInterface{
+		Name:      wgDevice.Name,
+		PublicKey: wgDevice.PublicKey.String(),
```
Comment (smagnani96) [inline cilium-dbg/cmd/encrypt_status.go]: We could also add `ListenPort` here so that we're coherent to what the agent returns. (see patch in my comment)

File: cilium-dbg/cmd/encrypt_status.go [hunk 10]
```diff
@@ -86,72 +94,183 @@ func init() {
...
+}
+
 func getEncryptionStatus() (models.EncryptionStatus, error) {
+	var result models.EncryptionStatus
+
 	params := daemon.NewGetHealthzParamsWithTimeout(timeout)
 	params.SetBrief(&brief)
+
 	resp, err := client.Daemon.GetHealthz(params)
+	if err == nil {
```
Comment (smagnani96) [inline cilium-dbg/cmd/encrypt_status.go]: I think this could all be streamlined a bit for clarity, but overall LGTM. (see patch above in my comment)

File: cilium-dbg/cmd/encrypt_status.go [hunk 11]
```diff
@@ -86,72 +94,183 @@ func init() {
 	command.AddOutputOption(encryptStatusCmd)
 }
 
+// containsInterface returns whether an `intf` is contained within a set of interfaces.
```
Comment (smagnani96) [inline cilium-dbg/cmd/encrypt_status.go]: I leave here a patch with the same logic streamlined, plus some updates.
Feel free to use it or take inspiration from it.
(haven't tested it)

```patch
From dde293dcb53af022ddc551910baed9ea09c0cc9b Mon Sep 17 00:00:00 2001
From: Simone Magnani <simone.magnani@isovalent.com>
Date: Fri, 10 Oct 2025 21:33:11 +0200
Subject: [PATCH] cilium-dbg: improve WireGuard status comparison

Signed-off-by: Simone Magnani <simone.magnani@isovalent.com>
---
 cilium-dbg/cmd/encrypt_status.go | 169 ++++++++++++++++---------------
 1 file changed, 89 insertions(+), 80 deletions(-)

diff --git a/cilium-dbg/cmd/encrypt_status.go b/cilium-dbg/cmd/encrypt_status.go
index b44fd52760..1e264f4606 100644
--- a/cilium-dbg/cmd/encrypt_status.go
+++ b/cilium-dbg/cmd/encrypt_status.go
@@ -50,10 +50,7 @@ var encryptStatusCmd = &cobra.Command{
 	Short: "Display the current encryption state",
 	Run: func(cmd *cobra.Command, args []string) {
 		common.RequireRootPrivilege("cilium encrypt status")
-		status, err := getEncryptionStatus()
-		if err != nil {
-			Fatalf("Cannot get encryption status: %s", err)
-		}
+		status := getEncryptionStatus()
 		if command.OutputOption() {
 			if err := command.PrintOutput(status); err != nil {
 				Fatalf("error getting output in JSON: %s\n", err)
@@ -94,102 +91,113 @@ func init() {
 	command.AddOutputOption(encryptStatusCmd)
 }
 
-// containsInterface returns whether an `intf` is contained within a set of interfaces.
-// we do not compare the list of peers, just the peer count and public key.
-func containsInterface(intfList []*models.WireguardInterface, intf *models.WireguardInterface) bool {
-	for _, i := range intfList {
-		if i.Name == intf.Name && i.PeerCount == intf.PeerCount &&
-			i.PublicKey == intf.PublicKey {
-			return true
+// validateWireguardStates compares the WireguardStatus from the agent and kernel,
+// returning an error if they do not match.
+func validateWireguardStates(agent, kernel *models.WireguardStatus) error {
+	switch {
+	case agent == nil && kernel == nil:
+		return fmt.Errorf("%w: both agent and kernel states are empty", errWireguardStateMismatch)
+	case agent == nil && kernel != nil:
+		return fmt.Errorf("%w: agent state is empty", errWireguardStateMismatch)
+	case agent != nil && kernel == nil:
+		return fmt.Errorf("%w: kernel state is empty", errWireguardStateMismatch)
+	}
+
+	var errs error
+	seenIfaces := make(map[string]struct{})
+
+	findIface := func(ifaces []*models.WireguardInterface, name string) *models.WireguardInterface {
+		for _, iface := range ifaces {
+			if iface.Name == name {
+				return iface
+			}
 		}
+		return nil
 	}
 
-	return false
-}
+	compareIfaces := func(from, to []*models.WireguardInterface, fromLabel, toLabel string) {
+		for _, f := range from {
+			if _, seen := seenIfaces[f.Name]; seen {
+				continue
+			}
+			seenIfaces[f.Name] = struct{}{}
 
-// validateWireguardState compares two models.WireguardStatus struct and returns
-// an error if they are not the same (if there's a mismatch on the interfaces, peers, keys).
-func validateWireguardState(expected, actual *models.WireguardStatus) error {
-	if expected == nil {
-		if actual != nil {
-			return fmt.Errorf("%w: agent state is empty", errWireguardStateMismatch)
-		}
-	}
+			t := findIface(to, f.Name)
+			if t == nil {
+				errs = errors.Join(errs, fmt.Errorf("interface %q exists in %s but is missing in %s",
+					f.Name, fromLabel, toLabel))
+				continue
+			}
 
-	if actual == nil {
-		return fmt.Errorf("%w: actual (kernel) state is empty", errWireguardStateMismatch)
+			if f.PeerCount != t.PeerCount {
+				errs = errors.Join(errs, fmt.Errorf("interface %q: peer count mismatch (%s=%d, %s=%d)",
+					f.Name, fromLabel, f.PeerCount, toLabel, t.PeerCount))
+			}
+			if f.ListenPort != t.ListenPort {
+				errs = errors.Join(errs, fmt.Errorf("interface %q: listen port mismatch (%s=%d, %s=%d)",
+					f.Name, fromLabel, f.ListenPort, toLabel, t.ListenPort))
+			}
+			if f.PublicKey != t.PublicKey {
+				errs = errors.Join(errs, fmt.Errorf("interface %q: public key mismatch (%s=%s, %s=%s)",
+					f.Name, fromLabel, f.PublicKey, toLabel, t.PublicKey))
+			}
+		}
 	}
 
-	if len(actual.Interfaces) != len(expected.Interfaces) {
-		return fmt.Errorf(
-			"%w: interface count did not match between agent state and kernel state. agent: %d, kernel: %d",
-			errWireguardStateMismatch, len(expected.Interfaces), len(actual.Interfaces),
-		)
+	if len(agent.Interfaces) != len(kernel.Interfaces) {
+		errs = errors.Join(errs, fmt.Errorf("interface count mismatch (agent=%d, kernel=%d)",
+			len(agent.Interfaces), len(kernel.Interfaces)))
 	}
 
-	// we need to go over both lists and make sure all
-	// interfaces on one side are seen on the other side
-	// and the other way around.
-	// this is high complexity but it's not a critical code path
-	for _, actualIntf := range actual.Interfaces {
-		if !containsInterface(expected.Interfaces, actualIntf) {
-			return fmt.Errorf("%w: interface %s not found or did not match in the actual set of interfaces", errWireguardStateMismatch, actualIntf.Name)
-		}
-	}
+	compareIfaces(agent.Interfaces, kernel.Interfaces, "agent", "kernel")
+	compareIfaces(kernel.Interfaces, agent.Interfaces, "kernel", "agent")
 
-	for _, expectedIntf := range expected.Interfaces {
-		if !containsInterface(actual.Interfaces, expectedIntf) {
-			return fmt.Errorf("%w: interface %s not found or did not match in the expected set of interfaces", errWireguardStateMismatch, expectedIntf.Name)
-		}
+	if errs != nil {
+		return errors.Join(errWireguardStateMismatch, errs)
 	}
-
 	return nil
 }
 
-func getEncryptionStatus() (models.EncryptionStatus, error) {
-	var result models.EncryptionStatus
+func getEncryptionStatus() (status models.EncryptionStatus) {
+	var err error
 
+	// retrieve IPSec state (if any) from kernel anyway.
+	status.Ipsec, err = dumpIPsecStatus()
+	if err != nil {
+		status.Msg += "\n" + err.Error()
+	}
+	// retrieve WireGuard state (if any) from kernel anyway.
+	status.Wireguard, err = dumpWireGuardStatus()
+	if err != nil {
+		status.Msg += "\n" + err.Error()
+	}
+
+	// retrieve encryption state from agent.
 	params := daemon.NewGetHealthzParamsWithTimeout(timeout)
 	params.SetBrief(&brief)
-
 	resp, err := client.Daemon.GetHealthz(params)
-	if err == nil {
-		result = *resp.Payload.Encryption
-		if result.Mode == models.EncryptionStatusModeWireguard {
-			actualWgState, err := dumpWireGuardStatus()
-			if err != nil {
-				result.Msg = err.Error()
-			}
-
-			err = validateWireguardState(result.Wireguard, actualWgState)
-			if err != nil {
-				result.Msg += err.Error()
-			}
-		} else {
-			result.Ipsec, err = dumpIPsecStatus()
-			if err != nil {
-				result.Msg += err.Error()
-			}
-		}
-
-		return result, nil
-	}
-
-	// if we get here, the agent failed to respond.
-	// get state from the kernel and return it back
-	result.Msg = err.Error()
-
-	result.Ipsec, err = dumpIPsecStatus()
 	if err != nil {
-		result.Msg += "\n" + err.Error()
+		status.Msg += err.Error()
+		return
 	}
 
-	result.Wireguard, err = dumpWireGuardStatus()
-	if err != nil {
-		result.Msg += "\n" + err.Error()
+	// the agent replied, let's set the encryption mode
+	status.Mode = resp.Payload.Encryption.Mode
+
+	// in WireGuard mode, the agent replies with the list of interfaces and peers,
+	// we can use that to validate the state against what we see in the kernel.
+	// this is a nop in case of IPSec or no encryption mode.
+	switch status.Mode {
+	case models.EncryptionStatusModeWireguard:
+		err = validateWireguardStates(status.Wireguard, resp.Payload.Encryption.Wireguard)
+		if err != nil {
+			status.Msg += err.Error()
+		}
+	case models.EncryptionStatusModeDisabled, models.EncryptionStatusModeIPsec:
+	default:
 	}
 
-	return result, nil
+	return
 }
 
 // filterReqID returns the subset of the `xfrmStates` that match the `reqID` passed in.
@@ -265,9 +273,10 @@ func dumpWireGuardStatus() (*models.WireguardStatus, error) {
 	var result models.WireguardStatus
 
 	result.Interfaces = append(result.Interfaces, &models.WireguardInterface{
-		Name:      wgDevice.Name,
-		PublicKey: wgDevice.PublicKey.String(),
-		PeerCount: int64(len(wgDevice.Peers)),
+		Name:       wgDevice.Name,
+		ListenPort: int64(wgDevice.ListenPort),
+		PublicKey:  wgDevice.PublicKey.String(),
+		PeerCount:  int64(len(wgDevice.Peers)),
 	})
 
 	return &result, nil
-- 
2.48.1
```

**Review by smagnani96 — CHANGES_REQUESTED** [review]
Thanks for addressing the feedback🙏🏼
I believe there are some minor updates we could add, then we're good to go 👍🏼

File: cilium-dbg/cmd/encrypt_status.go [hunk 12]
```diff
@@ -8,6 +8,7 @@ package cmd
 
 import (
```
Comment (smagnani96) [inline cilium-dbg/cmd/encrypt_status.go:9]: Leaving a comment here as a memo: did we test this?
PR LGTM though!

**Review by smagnani96 — APPROVED** [review]
This LGTM now, just wondering if we have test this and make sure it behaves as expected 🙏🏼

File: cilium-dbg/cmd/encrypt_status.go (hunk 12 above)
Comment (bersoare) [reply cilium-dbg/cmd/encrypt_status.go:9]: yup, i did manually test it against a kind cluster

File: cilium-dbg/cmd/encrypt_status.go [hunk 13]
```diff
@@ -215,6 +347,7 @@ func maxSequenceNumber() (string, error) {
 	return fmt.Sprintf("0x%x/0xffffffffffffffff", maxSeqNum), nil
 }
 
+// isDecryptionInterface returns whether we thing an interface is used for decryption or not.
```
Comment (asauber) [inline cilium-dbg/cmd/encrypt_status.go]:
```suggestion
// isDecryptionInterface returns whether we think an interface is used for decryption or not.
```

**Review by asauber — APPROVED** [review]

**Comment by pchaigno** [comment]
Could you merge the last commit into the one it fixes?

File: cilium-dbg/cmd/encrypt_status.go [hunk 14]
```diff
@@ -362,6 +365,31 @@ func isDecryptionInterface(link netlink.Link) (bool, error) {
 		}
 	}
 
+	progs, err := ebpf_link.QueryPrograms(
+		ebpf_link.QueryOptions{
+			Target: link.Attrs().Index,
+			Attach: ebpf.AttachTCXIngress,
+		},
+	)
```
Comment (pchaigno) [inline cilium-dbg/cmd/encrypt_status.go]: Oh, nice! I'd consider that a bugfix, so we should probably send as a separate PR and backport. IIRC, tcx attachment is already in stable releases.

Comment (bersoare) [reply cilium-dbg/cmd/encrypt_status.go]: https://github.com/cilium/cilium/pull/42328

**Review by pchaigno — APPROVED** [review]
