### PR TITLE
policy: Fix Endpoint Selector Policy Deadlock

### LINKED ISSUE #38056: Detected Cilium deadlock in policy subsystem
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.1 and lower than v1.18.0

### What happened?

Detected in CI in one of my PRs, but looking at the involved paths it may be actually related to https://github.com/cilium/cilium/pull/37910. 

Link: https://github.com/cilium/cilium/actions/runs/13704897636/job/38327821808
Sysdump: [cilium-sysdump-context2-final-2-disabled-none-false-511-migration.zip](https://github.com/user-attachments/files/19123436/cilium-sysdump-context2-final-2-disabled-none-false-511-migration.zip)

Extract of the stack trace:

```
1: sync.Mutex.Lock [7 minutes] [Created by http.(*Server).Serve in goroutine 1337 @ server.go:3454]
    sync            sema.go:95                  runtime_SemacquireMutex(#33, 0xc0, #1652)
    sync            mutex.go:149                (*Mutex).lockSlow(#1575)
    sync            mutex.go:70                 (*Mutex).Lock(...)
    sync            mutex.go:46                 (*Mutex).Lock(...)
    sync            rwmutex.go:150              (*RWMutex).Lock(0)
    policy          l4.go:1641                  (*L4Policy).removeUser(#1574, #1036)
    policy          resolve.go:149              (*selectorPolicy).removeUser(...)
    policy          resolve.go:229              (*EndpointPolicy).Detach(#1036)
    endpoint        endpoint.go:1229            (*Endpoint).leaveLocked(#1284, {0x50, 0x33})
    endpoint        endpoint.go:2540            (*Endpoint).Delete(#1284, {8, 0xc})
    endpointmanager manager.go:455              (*endpointManager).removeEndpoint(#830, #1284, {0, 0})
    endpointmanager manager.go:469              (*endpointManager).RemoveEndpoint(#242, #933, {0x9b, 0x14})
    cmd             endpoint.go:796             (*Daemon).deleteEndpointQuiet(...)
    cmd             endpoint.go:774             (*Daemon).deleteEndpointRelease(#1081, #1284, 0)
    cmd             endpoint.go:785             (*Daemon).deleteEndpoint(...)
    cmd             endpoint.go:854             (*Daemon).deleteEndpointByContainerID(#1081, {#876, 0x40})
    cmd             endpoint.go:150             deleteEndpointHandler(#1081, {#973, #1474})
    cmd             api_handlers.go:64          (*apiHandler[...]).Handle(#730, {#973, #1474})
    endpoint        delete_endpoint.go:58       (*DeleteEndpoint).ServeHTTP(#739, {#124, #653}, #973)
    middleware      operation.go:28             (*Context).RoutesHandler.NewOperationExecutor.func1({#124, #653}, #973)
    http            server.go:2294              HandlerFunc.ServeHTTP(#1086, {#124, #653}, 1)
    middleware      router.go:80                NewRouter.func1({#124, #653}, #972)
    http            server.go:2294              HandlerFunc.ServeHTTP(#1173, {#124, #653}, 6)
    middleware      ui_options.go:164           Redoc.serveUI.func1({#124, #653}, #972)
    http            server.go:2294              HandlerFunc.ServeHTTP(#1173, {#124, #653}, #433)
    middleware      spec.go:72                  Spec.func1({#124, #653}, #972)
    http            server.go:2294              HandlerFunc.ServeHTTP(#1690, {#124, #653}, 3)
    metrics         middleware.go:63            (*APIEventTSHelper).ServeHTTP(#602, {#123, #1076}, #972)
    api             apipanic.go:56              (*APIPanicHandler).ServeHTTP(#1174, {#123, #1076}, #934)
    http            server.go:2822              (*ServeMux).ServeHTTP(#17, {#123, #1076}, #972)
    http            server.go:3301              serverHandler.ServeHTTP({#117}, {#123, #1076}, 1)
    http            server.go:2102              (*conn).serve(#1712, {#132, #576})

1: sync.Mutex.Lock [7 minutes] [Created by eventqueue.(*EventQueue).Run in goroutine 1377 @ eventqueue.go:228]
    sync            sema.go:95                  runtime_SemacquireMutex(#1099, 0xaf, #1100)
    sync            mutex.go:149                (*Mutex).lockSlow(#1285)
    sync            mutex.go:70                 (*Mutex).Lock(...)
    sync            mutex.go:46                 (*Mutex).Lock(...)
    sync            rwmutex.go:150              (*RWMutex).Lock(0xc1ea9703c95caf2a)
    endpoint        lock.go:17                  (*Endpoint).lockAlive(#1284)
    endpoint        policy.go:604               (*Endpoint).SetRegenerateStateIfAlive(#1284, #561)
    endpoint        policy.go:702               (*Endpoint).RegenerateIfAlive(#1284, #561)
    policy          l4.go:1757                  (*L4Policy).detach(#1574, #747, 0, 0xd17)
    policy          resolve.go:159              (*selectorPolicy).detach(...)
    policy          distillery.go:188           (*cachedSelectorPolicy).setPolicy(#992, #600, 0xd17)
    policy          distillery.go:103           (*policyCache).updateSelectorPolicy(#590, #600, 0xd17)
    policy          repository.go:634           (*Repository).GetSelectorPolicy(#992, #600, 2, {#118, #215}, 0xd17)
    endpoint        policy.go:219               (*Endpoint).regeneratePolicy(#1283, #215, #1476)
    endpoint        bpf.go:639                  (*Endpoint).runPreCompilationSteps(#1283, #214)
    endpoint        bpf.go:391                  (*Endpoint).regenerateBPF(#1283, #214)
    endpoint        policy.go:477               (*Endpoint).regenerate(#1283, #214)
    endpoint        events.go:77                (*EndpointRegenerationEvent).Handle(#662, #1560)
    eventqueue      eventqueue.go:244           (*EventQueue).run.func1()
    sync            once.go:78                  (*Once).doSlow(#39, #1303)
    sync            once.go:69                  (*Once).Do(...)
    eventqueue      eventqueue.go:232           (*EventQueue).run(#1395)

1: sync.Mutex.Lock [4 minutes] [Created by eventqueue.(*EventQueue).Run in goroutine 4743 @ eventqueue.go:228]
    sync            sema.go:95                  runtime_SemacquireMutex(#36, 0xa0, #1430)
    sync            mutex.go:149                (*Mutex).lockSlow(#487)
    sync            mutex.go:70                 (*Mutex).Lock(...)
    sync            mutex.go:46                 (*Mutex).Lock(...)
    policy          distillery.go:89            (*policyCache).updateSelectorPolicy(#590, #1440, 0x33a)
    policy          repository.go:634           (*Repository).GetSelectorPolicy(#992, #1440, 0, {#118, #1545}, 0x33a)
    endpoint        policy.go:219               (*Endpoint).regeneratePolicy(#1127, #1545, #1145)
    endpoint        policy.go:826               (*Endpoint).ComputeInitialPolicy(#1127, #1544)
    endpoint        events.go:39                (*EndpointRegenerationEvent).Handle(#515, #1642)
    eventqueue      eventqueue.go:244           (*EventQueue).run.func1()
    sync            once.go:78                  (*Once).doSlow(#39, #1424)
    sync            once.go:69                  (*Once).Do(...)
    eventqueue      eventqueue.go:232           (*EventQueue).run(#1705)
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by nathanjsweet**
The selectorPolicy, when replaced, triggers
endpoint regeneration for any other endpoints that use it. 
If an endpoint undergoes deletion simultaneously, the 
endpoint lock, in concert with the selectorPolicy lock, 
can create a deadlock. To prevent this, the selectorPolicy 
can regenerate the endpoints via a go routine, so
 that the selectorPolicy is guaranteed to unlock after 
triggering regeneration.

Fixes: 12565044f0b7 ("endpoint: Trigger Regeneration on SelectorPolicy Update")
Fixes: #37910
Fixes: #38056

### CODE REVIEW

File: pkg/policy/l4.go [hunk 1]
```diff
@@ -1754,7 +1754,7 @@ func (l4 *L4Policy) detach(selectorCache *SelectorCache, isDelete bool, endpoint
 	if !isDelete {
 		for ePolicy := range l4.users {
 			if endpointID != ePolicy.PolicyOwner.GetID() {
-				ePolicy.PolicyOwner.RegenerateIfAlive(&regeneration.ExternalRegenerationMetadata{
+				go ePolicy.PolicyOwner.RegenerateIfAlive(&regeneration.ExternalRegenerationMetadata{
```
Comment (joestringer) [inline pkg/policy/l4.go:1833]: This seems like it should address the reported issue :+1: .

I dug a little bit, first I was wondering why the `endpointID != ePolicy.PolicyOwner.GetID()` check didn't catch it, but we could have parallel regeneration for two endpoints with the same security identity (and this is even expected if a policy change affects multiple endpoints for a deployment). So both would regenerate, both could attempt to calculate the new policy and may be holding their own Endpoint mutex while calling into this policy calculation code. I think it makes sense to keep the equality check as-is just to avoid triggering regeneration again for the current endpoint in the average case.

Then I was thinking about how many goroutines may spawn - one per "extra" Endpoint with the same Security Identity, per L4Policy (which should be roughly per Security Identity?) - conclusion, not a large number.

I wondered very briefly about whether we'd still need this if we reworked the way that we trigger network policy regeneration, and I think it may even still make sense to keep like this, but maybe if we triggered network policy regeneration from the local identity cache without holding the endpoint locks then maybe we could drop the goroutine... but I'm speculating about a much more complicated change which is clearly out of scope for the current PR.

All that's to say.. I think we're good?

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
We can probably add:

Fixes: 12565044f0b7 ("endpoint: Trigger Regeneration on SelectorPolicy Update")
Fixes: #37910
Fixes: #38056

**Comment by joestringer** [comment]
I changed the labels since the patch that introduced the deadlock doesn't seem to have been backported.

**Comment by julianwiedmann** [comment]
Checked with @squeed, no need to backport for v1.17.
