### PR TITLE
Fixing endpoint status

### LINKED ISSUE #207: Endpoint list shows Status OK even if bpf program can't be build
When listing `cilium endpoint list` to see the endpoint status. The status presented can be deceiving because of the `Policy regenerated` messages.

```
Endpoint status: 
2016-12-01T15:42:40Z - OK - Policy regenerated
2016-12-01T15:42:05Z - OK - Policy regenerated
2016-12-01T15:41:38Z - OK - Policy regenerated
2016-12-01T15:40:39Z - Failure - error: "exit status 1" command output: "Join EP id=29898_update ifname=lxcefaff
``` 

We should add priority to the status messages, for example on this case, bpf recompilation is more important than Policy regenerated and therefore we should show Status Failure on endpoint list.

Or stop the policy regenerated for the endpoint until the bpf program is properly recompiled.

### LINKED ISSUE #316: endpoint incorrectly shows status as `ready` when the endpoint bpf program failed to build
I noticed the endpoint was not reachable nor the bpf program was successfully compiled, however the status for that endpoint was being wrongly marked as `ready`.
```
$ cilium endpoint get 33115
{
  ...
  "state": "ready",
  "status": [
    {
      "code": "Failure",
      "message": "error:...
      "timestamp": "2017-03-15T15:57:51Z"
    },
    {
      "code": "Failure",
      "message": "error:...
      "timestamp": "2017-03-15T15:57:51Z"
    },
    {
      "code": "Failure",
      "message": "error:...
      "timestamp": "2017-03-15T15:57:49Z"
    },
    {
      "code": "OK",
      "message": "Policy regenerated",
      "timestamp": "2017-03-15T15:57:47Z"
    }
  ]
}
$ cilium endpoint list
ENDPOINT   IDENTITY   LABELS (source:key[=value])                   IPv6                   IPv4            STATUS
33115      265        k8s:io.cilium.k8s.k8s-app=kube-dns            f00d::ac10:16:0:815b   10.202.220.6    ready
                      k8s:io.cilium.k8s.version=v20
                      k8s:io.kubernetes.pod.namespace=kube-system
```

### PR DESCRIPTION
**Pull request by aanm**
@tgraf I can squash the last 2 commits if you want.

Fixes #207 
Fixes #316
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/cilium/cilium/pull/339%23discussion_r106771024%22%2C%20%22https%3A//github.com/cilium/cilium/pull/339%23discussion_r106772091%22%2C%20%22https%3A//github.com/cilium/cilium/pull/339%23discussion_r106772158%22%2C%20%22https%3A//github.com/cilium/cilium/pull/339%23discussion_r106772592%22%2C%20%22https%3A//github.com/cilium/cilium/pull/339%23discussion_r106772927%22%2C%20%22https%3A//github.com/cilium/cilium/pull/339%23issuecomment-287516912%22%2C%20%22https%3A//github.com/cilium/cilium/pull/339%23discussion_r106791258%22%2C%20%22https%3A//github.com/cilium/cilium/pull/339%23discussion_r106791529%22%2C%20%22https%3A//github.com/cilium/cilium/pull/339%23discussion_r106791535%22%2C%20%22https%3A//github.com/cilium/cilium/pull/339%23discussion_r106791829%22%2C%20%22https%3A//github.com/cilium/cilium/pull/339%23discussion_r106791839%22%2C%20%22https%3A//github.com/cilium/cilium/pull/339%23discussion_r106792961%22%2C%20%22https%3A//github.com/cilium/cilium/pull/339%23discussion_r106794097%22%2C%20%22https%3A//github.com/cilium/cilium/pull/339%23discussion_r106821999%22%2C%20%22https%3A//github.com/cilium/cilium/pull/339%23discussion_r106822096%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/cilium/cilium/pull/339%23issuecomment-287516912%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22TODO%3A%20Implement%20map%20for%20%60CurrentStatus%60%20to%20keep%20low%20priority%20non-OK%20messages.%22%2C%20%22created_at%22%3A%20%222017-03-18T05%3A02%3A10Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/5714066%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/aanm%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%2C%20%22Pull%207c7bc3cb5c93e33f6ed323a9ac5c39ce4f6e2227%20pkg/endpoint/endpoint.go%2017%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/cilium/cilium/pull/339%23discussion_r106771024%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22What%20kind%20of%20Validation%20you%20were%20talking%20about%3F%22%2C%20%22created_at%22%3A%20%222017-03-18T02%3A38%3A52Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/5714066%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/aanm%22%7D%7D%2C%20%7B%22body%22%3A%20%22The%20case%20where%20the%20value%20of%20state%20is%20not%20one%20of%20the%20model%20enum.%22%2C%20%22created_at%22%3A%20%222017-03-18T03%3A40%3A56Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/1417913%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tgraf%22%7D%7D%5D%2C%20%22title%22%3A%20%22File%3A%20pkg/endpoint/endpoint.go%3AL229-236%22%7D%2C%20%22Pull%20d28ee136c7916dd819b2fcc4d77a3d546eabe21d%20pkg/endpoint/endpoint.go%2031%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/cilium/cilium/pull/339%23discussion_r106822096%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Minor%20as%20it%20is%20private%20but%20I%20would%20rename%20this%20as%20well%20to%20%60statusTypeSlice%60%22%2C%20%22created_at%22%3A%20%222017-03-19T23%3A11%3A10Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/1417913%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tgraf%22%7D%7D%5D%2C%20%22title%22%3A%20%22File%3A%20pkg/endpoint/endpoint.go%3AL236-305%22%7D%2C%20%22Pull%2072fc17c736c247588d2f8090b3f7de6a4aa2ec50%20pkg/endpoint/endpoint.go%2069%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/cilium/cilium/pull/339%23discussion_r106772592%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40tgraf%20Tell%20me%20if%20by%20only%20reading%20this%20explanation%20it%20makes%20sense%20to%20you%20or%20if%20you%20had%20any%20doubts.%22%2C%20%22created_at%22%3A%20%222017-03-18T04%3A15%3A23Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/5714066%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/aanm%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%27m%20not%20sure%20I%20fully%20understand%20the%20concept%20yet.%20The%20fundamental%20problem%20is%20that%20you%20have%20multiple%20causes%20for%20an%20endpoint%20to%20be%20considered%20in%20an%20failed%20state%3A%5Cr%5Cn%20-%20bpf%20generation%20or%20compilation%5Cr%5Cn%20-%20policy%20calculation%5Cr%5Cn%20-%20....%5Cr%5Cn%5Cr%5CnEach%20of%20these%20causes%20can%20be%20OK/warning/failure.%20You%20want%20to%20report%20an%20overall%20status.%20You%20also%20want%20to%20store%20a%20log%20of%20status%20changes%20for%20each.%20The%20priority%20seems%20to%20indicate%20that%20a%20BPF%20failure%20always%20overwrites%20a%20policy%20failure%20but%20that%20seems%20incomplete.%5Cr%5Cn%5Cr%5CnLet%27s%20assume%3A%5Cr%5Cn1.%20bpf%20fails%5Cr%5Cn2.%20policy%20fails%5Cr%5Cn3.%20bpf%20succeeds%5Cr%5Cn%5Cr%5CnYou%20still%20want%20the%20overall%20state%20to%20say%20failure.%5Cr%5Cn%5Cr%5CnI%20think%20instead%20of%20priority%2C%20what%20you%20want%20is%20this%3A%5Cr%5Cn%60%60%60map%5BStatusComponent%5DstatusLogMsg%60%60%60%5Cr%5Cn%5Cr%5CnBPF%20and%20priority%20are%20both%20%60StatusComponent%60%5Cr%5Cn%5Cr%5CnOverallStatus%20is%20Failure%20if%20any%20of%20the%20components%20failed%2C%20else%20warning%20if%20any%20component%20is%20warning%2C%20else%20OK.%5Cr%5Cn%5Cr%5CnThe%20log%20shows%20the%20latest%20n%20status%20changes%20of%20the%20endpoint.%5Cr%5Cn%5Cr%5Cn%5Cr%5Cn%5Cr%5Cn%5Cr%5Cn%5Cr%5Cn%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222017-03-18T04%3A38%3A39Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/1417913%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tgraf%22%7D%7D%5D%2C%20%22title%22%3A%20%22File%3A%20pkg/endpoint/endpoint.go%3AL249-305%22%7D%2C%20%22Pull%20da8e17c03c66878fdc2294e84650cc94d7d37906%20pkg/endpoint/endpoint.go%2057%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/cilium/cilium/pull/339%23discussion_r106772158%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Can%20you%20explain%20this%20priority%20system%20a%20bit.%20I%20assume%20the%20point%20is%20to%20not%20undo%20failure%20state%20unless%20we%20know%20that%20the%20actual%20failure%20is%20gone.%20How%20does%20this%20priority%20actual%20fix%20it%3F%5Cr%5Cn%5Cr%5CnDon%27t%20we%20need%20a%20bitmask%20which%20indicates%20the%20status%20of%20each%20failure%20mode%20and%20if%20any%20of%20them%20is%20set%20to%20failure%20the%20entire%20endpoint%20is%20marked%20as%20failed%3F%22%2C%20%22created_at%22%3A%20%222017-03-18T03%3A45%3A51Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/1417913%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tgraf%22%7D%7D%5D%2C%20%22title%22%3A%20%22File%3A%20pkg/endpoint/endpoint.go%3AL255-279%22%7D%2C%20%22Pull%2062445d87a0664f2dd6fad0e0cf024481862f44d8%20pkg/endpoint/endpoint.go%2019%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/cilium/cilium/pull/339%23discussion_r106791258%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Looks%20great.%20What%20does%20priority%20mean%20in%20this%20context%3F%20I%20would%20rename%20this%20to%20%60componentStatus%60%22%2C%20%22created_at%22%3A%20%222017-03-18T21%3A15%3A28Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/1417913%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tgraf%22%7D%7D%2C%20%7B%22body%22%3A%20%22Should%20I%20renamed%20the%20%60StatusPriority%60%20to%20%60StatusComponent%60%3F%22%2C%20%22created_at%22%3A%20%222017-03-18T21%3A27%3A28Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/5714066%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/aanm%22%7D%7D%2C%20%7B%22body%22%3A%20%22It%20needs%20to%20have%20a%20sense%20of%20a%20priority%20in%20the%20name.%20Suggestions%3F%22%2C%20%22created_at%22%3A%20%222017-03-18T21%3A27%3A59Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/5714066%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/aanm%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20think%20you%20want%20a%20struct%20%60ComponentStatus%60%20which%20is%20a%20member%20%60Latest%60%20in%20%60EndpointStatus%60.%20I%20know%20what%20you%20mean%20by%20priority%20but%20it%27s%20misleading.%20I%20think%20you%20really%20mean%20the%20latest%20status.%22%2C%20%22created_at%22%3A%20%222017-03-18T21%3A41%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/1417913%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tgraf%22%7D%7D%2C%20%7B%22body%22%3A%20%22Or%20%60ComponentStatuses%60%20which%20is%20a%20slice%20of%20%60ComponentStatus%60%22%2C%20%22created_at%22%3A%20%222017-03-18T21%3A42%3A32Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/1417913%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tgraf%22%7D%7D%2C%20%7B%22body%22%3A%20%22And%20the%20%60StatusPriority%60%20should%20I%20keep%20it%20as%20is%3F%22%2C%20%22created_at%22%3A%20%222017-03-18T22%3A33%3A20Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/5714066%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/aanm%22%7D%7D%2C%20%7B%22body%22%3A%20%22How%20about%20%60EndpointComponentName%60%3F%22%2C%20%22created_at%22%3A%20%222017-03-18T23%3A41%3A16Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars2.githubusercontent.com/u/1417913%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tgraf%22%7D%7D%2C%20%7B%22body%22%3A%20%22Change%20it%20to%20%60StatusType%60%2C%20I%20think%20it%20makes%20sense.%22%2C%20%22created_at%22%3A%20%222017-03-19T23%3A07%3A28Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/5714066%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/aanm%22%7D%7D%5D%2C%20%22title%22%3A%20%22File%3A%20pkg/endpoint/endpoint.go%3AL236-305%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [x] <a href='#crh-comment-Pull 7c7bc3cb5c93e33f6ed323a9ac5c39ce4f6e2227 pkg/endpoint/endpoint.go 17'></a> &nbsp;<b><a href='https://github.com/cilium/cilium/pull/339#discussion_r106771024'>File: pkg/endpoint/endpoint.go:L229-236</a></b>
- <a href='https://github.com/aanm'></a> What kind of Validation you were talking about?
- <a href='https://github.com/tgraf'></a> The case where the value of state is not one of the model enum.
- [x] <a href='#crh-comment-Pull da8e17c03c66878fdc2294e84650cc94d7d37906 pkg/endpoint/endpoint.go 57'></a> &nbsp;<b><a href='https://github.com/cilium/cilium/pull/339#discussion_r106772158'>File: pkg/endpoint/endpoint.go:L255-279</a></b>
- <a href='https://github.com/tgraf'></a> Can you explain this priority system a bit. I assume the point is to not undo failure state unless we know that the actual failure is gone. How does this priority actual fix it?
Don't we need a bitmask which indicates the status of each failure mode and if any of them is set to failure the entire endpoint is marked as failed?
- [x] <a href='#crh-comment-Pull 72fc17c736c247588d2f8090b3f7de6a4aa2ec50 pkg/endpoint/endpoint.go 69'></a> &nbsp;<b><a href='https://github.com/cilium/cilium/pull/339#discussion_r106772592'>File: pkg/endpoint/endpoint.go:L249-305</a></b>
- <a href='https://github.com/aanm'></a> @tgraf Tell me if by only reading this explanation it makes sense to you or if you had any doubts.
- <a href='https://github.com/tgraf'></a> I'm not sure I fully understand the concept yet. The fundamental problem is that you have multiple causes for an endpoint to be considered in an failed state:
- bpf generation or compilation
- policy calculation
- ....
Each of these causes can be OK/warning/failure. You want to report an overall status. You also want to store a log of status changes for each. The priority seems to indicate that a BPF failure always overwrites a policy failure but that seems incomplete.
Let's assume:
1. bpf fails
2. policy fails
3. bpf succeeds
You still want the overall state to say failure.
I think instead of priority, what you want is this:
```map[StatusComponent]statusLogMsg```
BPF and priority are both `StatusComponent`
OverallStatus is Failure if any of the components failed, else warning if any component is warning, else OK.
The log shows the latest n status changes of the endpoint.
- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/cilium/cilium/pull/339#issuecomment-287516912'>General Comment</a></b>
- <a href='https://github.com/aanm'></a> TODO: Implement map for `CurrentStatus` to keep low priority non-OK messages.
- [ ] <a href='#crh-comment-Pull 62445d87a0664f2dd6fad0e0cf024481862f44d8 pkg/endpoint/endpoint.go 19'></a> &nbsp;<b><a href='https://github.com/cilium/cilium/pull/339#discussion_r106791258'>File: pkg/endpoint/endpoint.go:L236-305</a></b>
- <a href='https://github.com/tgraf'></a> Looks great. What does priority mean in this context? I would rename this to `componentStatus`
- <a href='https://github.com/aanm'></a> Should I renamed the `StatusPriority` to `StatusComponent`?
- <a href='https://github.com/aanm'></a> It needs to have a sense of a priority in the name. Suggestions?
- <a href='https://github.com/tgraf'></a> I think you want a struct `ComponentStatus` which is a member `Latest` in `EndpointStatus`. I know what you mean by priority but it's misleading. I think you really mean the latest status.
- <a href='https://github.com/tgraf'></a> Or `ComponentStatuses` which is a slice of `ComponentStatus`
- <a href='https://github.com/aanm'></a> And the `StatusPriority` should I keep it as is?
- <a href='https://github.com/tgraf'></a> How about `EndpointComponentName`?
- <a href='https://github.com/aanm'></a> Change it to `StatusType`, I think it makes sense.
- [ ] <a href='#crh-comment-Pull d28ee136c7916dd819b2fcc4d77a3d546eabe21d pkg/endpoint/endpoint.go 31'></a> &nbsp;<b><a href='https://github.com/cilium/cilium/pull/339#discussion_r106822096'>File: pkg/endpoint/endpoint.go:L236-305</a></b>
- <a href='https://github.com/tgraf'></a> Minor as it is private but I would rename this as well to `statusTypeSlice`

<a href='https://www.codereviewhub.com/cilium/cilium/pull/339?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/cilium/cilium/pull/339?approve=1'></a>&nbsp;<a href='https://github.com/cilium/cilium/pull/339'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by aanm** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/cilium/cilium/pull/339'>Refresh</a>.<a href='#crh-update-none'></a>

File: pkg/endpoint/endpoint.go [hunk 1]
```diff
@@ -224,7 +229,7 @@ func (e *Endpoint) GetModel() *models.Endpoint {
 		InterfaceName:    e.IfName,
 		Mac:              e.LXCMAC.String(),
 		HostMac:          e.NodeMAC.String(),
-		State:            models.EndpointState(e.State), // TODO: Validate
+		State:            currentState, // TODO: Validate
```
Comment (aanm) [inline pkg/endpoint/endpoint.go:234]: What kind of Validation you were talking about?

Comment (tgraf) [reply pkg/endpoint/endpoint.go:234]: The case where the value of state is not one of the model enum.

File: pkg/endpoint/endpoint.go [hunk 2]
```diff
@@ -283,10 +255,24 @@ func (e *EndpointStatus) getAndIncIdx() int {
...
+		e.Log[e.Index] == e.CurrentStatus &&
+		e.CurrentStatus.Status.Code != OK {
+		e.Index++
+	}
 	return idx
 }
 
-func (e *EndpointStatus) addStatusLog(s *statusLog) {
+func (e *EndpointStatus) addStatusLog(s *statusLogMsg) {
+	if e.CurrentStatus.Status.Code == OK {
```
Comment (tgraf) [inline pkg/endpoint/endpoint.go]: Can you explain this priority system a bit. I assume the point is to not undo failure state unless we know that the actual failure is gone. How does this priority actual fix it?

Don't we need a bitmask which indicates the status of each failure mode and if any of them is set to failure the entire endpoint is marked as failed?

**Review by tgraf — COMMENTED** [review]
Separation into commits as-is OK, see question on priority.

File: pkg/endpoint/endpoint.go [hunk 3]
```diff
@@ -277,16 +249,56 @@ func (e *EndpointStatus) lastIndex() int {
...
+		e.Index++
+		if e.Index >= maxLogs {
+			e.Index = 0
+		}
+	}
 	return idx
 }
 
-func (e *EndpointStatus) addStatusLog(s *statusLog) {
+// addStatusLog adds statusLogMsg to endpoint log.
```
Comment (aanm) [inline pkg/endpoint/endpoint.go:339]: @tgraf Tell me if by only reading this explanation it makes sense to you or if you had any doubts.

Comment (tgraf) [reply pkg/endpoint/endpoint.go:339]: I'm not sure I fully understand the concept yet. The fundamental problem is that you have multiple causes for an endpoint to be considered in an failed state:
 - bpf generation or compilation
 - policy calculation
 - ....

Each of these causes can be OK/warning/failure. You want to report an overall status. You also want to store a log of status changes for each. The priority seems to indicate that a BPF failure always overwrites a policy failure but that seems incomplete.

Let's assume:
1. bpf fails
2. policy fails
3. bpf succeeds

You still want the overall state to say failure.

I think instead of priority, what you want is this:
```map[StatusComponent]statusLogMsg```

BPF and priority are both `StatusComponent`

OverallStatus is Failure if any of the components failed, else warning if any component is warning, else OK.

The log shows the latest n status changes of the endpoint.

**Comment by aanm** [comment]
TODO: Implement map for `CurrentStatus` to keep low priority non-OK messages.

File: pkg/endpoint/endpoint.go [hunk 4]
```diff
@@ -236,39 +236,69 @@ func (e *Endpoint) GetModel() *models.Endpoint {
...
 
-type EndpointStatus struct {
-	Log     []*statusLog `json:"log,omitempty"`
-	Index   int          `json:"index"`
-	indexMU sync.RWMutex
+// statusLog represents a slice of statusLogMsg.
+type statusLog []*statusLogMsg
+
+// priorityStatus represents a map of a single statusLogMsg by StatusPriority.
+type priorityStatus map[StatusPriority]*statusLogMsg
```
Comment (tgraf) [inline pkg/endpoint/endpoint.go]: Looks great. What does priority mean in this context? I would rename this to `componentStatus`

Comment (aanm) [reply pkg/endpoint/endpoint.go]: Should I renamed the `StatusPriority` to `StatusComponent`?

Comment (aanm) [reply pkg/endpoint/endpoint.go]: It needs to have a sense of a priority in the name. Suggestions?

Comment (tgraf) [reply pkg/endpoint/endpoint.go]: I think you want a struct `ComponentStatus` which is a member `Latest` in `EndpointStatus`. I know what you mean by priority but it's misleading. I think you really mean the latest status.

Comment (tgraf) [reply pkg/endpoint/endpoint.go]: Or `ComponentStatuses` which is a slice of `ComponentStatus`

Comment (aanm) [reply pkg/endpoint/endpoint.go]: And the `StatusPriority` should I keep it as is?

Comment (tgraf) [reply pkg/endpoint/endpoint.go]: How about `EndpointComponentType`?

Comment (aanm) [reply pkg/endpoint/endpoint.go]: I change it to `StatusType`, I think it makes sense.

File: pkg/endpoint/endpoint.go [hunk 5]
```diff
@@ -236,39 +236,69 @@ func (e *Endpoint) GetModel() *models.Endpoint {
...
+// priorityStatus.
+func (ps componentStatus) contains(s *statusLogMsg) bool {
+	return ps[s.Status.Type] == s
 }
 
-func (e *EndpointStatus) GetModel() []*models.EndpointStatusChange {
-	e.indexMU.RLock()
-	defer e.indexMU.RUnlock()
+// sPriority represents a slice of StatusType, is used for sorting purposes.
+type sPriority []StatusType
```
Comment (tgraf) [inline pkg/endpoint/endpoint.go]: Minor as it is private but I would rename this as well to `statusTypeSlice`

**Review by tgraf — APPROVED** [review]
Despite the minor comment, this looks fine now.
