### PR TITLE
Fetch MTU from the nodeIP interface

### LINKED ISSUE #10309: MTU autoDetect() fetches always the MTU from the gateway interface
## Bug report
If I deploy cilium-agent on a host that has more than 1 NIC, it is possible that the NIC used for cluster communication is not the same as the NIC used as gateway. However, Cilium will always autodetect the MTU by reading the mtu of the NIC used as gateway. As a consequence, if the MTUs are different, the detected MTU will be wrong.

This could be solved if the autodetection would take the assigned nodeIP for that cilium-agent, find the interface that holds that IP and then fetch the MTU from that interface.

**General Information**

- Cilium version: master
- Kernel version: Not relevant
- Orchestration system version in use: Kubernetes
- Link to relevant artifacts: https://github.com/cilium/cilium/blob/master/pkg/mtu/detect_linux.go#L49-L73

**How to reproduce the issue**

1. Having a server with 2 NICs, use NIC1 as gateway with mtu=1500. Use NIC2 for cluster communication with mtu=9000
2. Deploy Cilium and even if cilium-agent pods take the IP of NIC2, the autodetected mtu is 1500

### PR DESCRIPTION
**Pull request by manuelbuil**
The detected MTU is always the one belonging to the interface that acts
as gateway. That interface does not necessarily need to be the one that
holds nodeIP and thus the one that Cilium will use to send traffic
inside the k8s cluster. This patch fixes this and detects the mtu of the
interface used for cluster communications

Fixes: #10309
Signed-off-by: Manuel Buil <mbuil@suse.com>

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

The detected MTU is always the one belonging to the interface that acts
as gateway. That interface does not necessarily need to be the one that
holds nodeIP and thus the one that Cilium will use to send traffic
inside the k8s cluster. This patch fixes this and detects the mtu of the
interface used for cluster communications

Fixes: #10309

```release-note
Autodetection of the mtu correctly detects the mtu of the interface used for the kubernetes cluster communication. The mtu was incorrectly detected in cases where multiple interfaces were present and the gateway interface was not the one used for kubernetes cluster communication
```

### CODE REVIEW

**Comment by joestringer** [comment]
Travis failure seems relevant:

```
# github.com/cilium/cilium/daemon/cmd
vet: daemon/cmd/status_test.go:83:96: too few arguments in call to mtu.NewConfiguration
make[1]: *** [govet] Error 2
make[1]: Leaving directory `/home/travis/gopath/src/github.com/cilium/cilium'
make: *** [unit-tests] Error 2
```

**Comment by mrostecki** [comment]
test-me-please

File: pkg/mtu/detect_linux.go [hunk 1]
```diff
@@ -71,3 +71,33 @@ func autoDetect() (int, error) {
...
+		for _, addr := range addrs {
+			myIP, _, err := net.ParseCIDR(addr.String())
+
+			if err != nil {
+				return 0, fmt.Errorf("Unable to parse the CIDR: %s", err)
+			}
+
+			if myIP.Equal(ip) == true {
+				myMTU := iface.MTU
+				log.Infof("Kubernetes network interface usesd MTU %d. Cilium will use this one", myMTU)
```
Comment (vadorovsky) [inline pkg/mtu/detect_linux.go]: s/usesd/uses/

**Review by vadorovsky — CHANGES_REQUESTED** [review]
One nit. Otherwise looks good.

File: pkg/mtu/detect_linux.go [hunk 2]
```diff
@@ -71,3 +71,33 @@ func autoDetect() (int, error) {
 
 	return EthernetMTU, nil
 }
+
+// getMTUFromIf finds the interface that holds the ip and returns its mtu
+func getMTUFromIf(ip net.IP) (int, error) {
```
Comment (aanm) [inline pkg/mtu/detect_linux.go:84]: You need to add a "dummy" function in the `pkg/mtu/detect_darwin.go`

**Review by aanm — CHANGES_REQUESTED** [review]
@jrfastab PTAL as well

**Comment by manuelbuil** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by mrostecki** [comment]
test-me-please

**Comment by mrostecki** [comment]
Travis hit the flake #10615. we can ignore it

**Review by aanm — APPROVED** [review]

**Comment by mrostecki** [comment]
test-me-please

File: daemon/cmd/daemon.go [hunk 3]
```diff
@@ -414,6 +414,18 @@ func NewDaemon(ctx context.Context, dp datapath.Datapath) (*Daemon, *endpointRes
 			log.Info("k8s mode: Allowing localhost to reach local endpoints")
 		}
 
+		// Now that we know the node nodeIP of the node, we can get the mtu of the interface that holds that IP
+		if node.GetExternalIPv4() != nil {
+			mtuConfig = mtu.NewConfiguration(authKeySize, option.Config.EnableIPSec, option.Config.Tunnel != option.TunnelDisabled, configuredMTU, node.GetExternalIPv4())
```
Comment (tgraf) [inline daemon/cmd/daemon.go]: This seems incredibly fragile as the old MTU has already been passed into the NodeDiscovery layer and thus been pushed down to the datapath layer. We need to find a better way. This will create very subtle bugs in the future if we change the MTU suddenly underneath after some of the initialization has already happened.

**Review by tgraf — CHANGES_REQUESTED** [review]

File: daemon/cmd/daemon.go (hunk 3 above)
Comment (vadorovsky) [reply daemon/cmd/daemon.go]: That's right. It seems that we need to move the whole section:

```
bootstrapStats.k8sInit.Start()
[...]
bootstrapStats.cleanup.Start()
[...]
if k8s.IsEnabled() {
[...]
}
```

before we call `nodediscovery.NewNodeDiscovery()` and before we create an instance of `Daemon` struct.

@manuelbuil can you try that? You will need possibly to figure out whether `bootstrapStats.k8sInit.Start()` can be done before the first call of `mtu.NewConfiguration` and move up other variables which might be need for that.

**Review by vadorovsky — CHANGES_REQUESTED** [review]

File: daemon/cmd/daemon.go (hunk 3 above)
Comment (manuelbuil) [reply daemon/cmd/daemon.go]: Yes, I am planning to look into this as soon as I have some time. I am currently busy with some urgent stuff. Hopefully by the end of this week I'll have some time :)

Comment (manuelbuil) [reply daemon/cmd/daemon.go]: @mrostecki I tried what you suggested and it is possible to move code before the daemon creation. At least I haven't found any problem by manual testing and now the correct mtu is calculated before the daemon is created. I'll update the new version + rebase in a minute

**Comment by mrostecki** [comment]
test-me-please

**Comment by mrostecki** [comment]
Hitting the flake #10882

**Comment by mrostecki** [comment]
test-me-please

**Review by vadorovsky — APPROVED** [review]
Looks good, thanks!

**Comment by mrostecki** [comment]
@tgraf PTAL

**Comment by mrostecki** [comment]
restart-ginkgo

**Comment by joestringer** [comment]
@mrostecki Be aware there are at least three different types of issues with some of the services /nodeports tests , make sure you check the exit code and ensure it matches the corresponding issue. I can't tell if the failure seen before was #10882 because there's no link any more, but that one saw exit code 7 and was only seen in PRs that updated the cilium-runtime image so I suspect this saw a different issue, such as #10942 .

**Comment by mrostecki** [comment]
test-me-please

**Comment by mrostecki** [comment]
The log of failing GKE test is full of errors like:

```
11:23:19  getting kubeconfig for https://container.googleapis.com/v1/projects/cilium-ci/zones/us-west1-a/clusters/cilium-ci-8 (will store in /home/jenkins/workspace/Cilium-PR-K8s-GKE@8/src/github.com/cilium/cilium/test/gke/gke-kubeconfig)
11:23:20  Fetching cluster endpoint and auth data.
11:23:20  kubeconfig entry generated for cilium-ci-8.
11:23:20  aquiring cluster lock
11:23:23  Error from server (AlreadyExists): error when creating "/home/jenkins/workspace/Cilium-PR-K8s-GKE@8/src/github.com/cilium/cilium/test/gke/lock.yaml": deployments.apps "lock" already exists
11:23:23  error: --overwrite is false but found the following declared annotation(s): 'lock' already has a value (1)
11:23:23  1
```

@nebril @raybejjani Can we ignore it? Or should we wait for fix?

**Review by jrfastab — APPROVED** [review]
LGTM, should we rerun the gke tests with latest changes there?

**Comment by aanm** [comment]
@manuelbuil sorry, can you rebase against master?

**Review by tgraf — APPROVED** [review]
Moving the k8s init code to such an early point looked worrisome at first but it doesn't depend on any of the code it was moved in front of.

**Comment by manuelbuil** [comment]
> @manuelbuil sorry, can you rebase against master?

I have just tried but I noticed that I need to apply some extra changes as this patch https://github.com/cilium/cilium/commit/513296652c0244c08914ac0760d6717f0a466004 added a daemon dependency inside the `if k8s.IsEnabled()` that I was trying to move upwards. I'll try to update fix it during this week

**Comment by aanm** [comment]
@manuelbuil thanks, I'll mark the PR as draft in the meanwhile. Once it's ready for review please mark it ready and re-request reviews.

**Comment by manuelbuil** [comment]
> @manuelbuil thanks, I'll mark the PR as draft in the meanwhile. Once it's ready for review please mark it ready and re-request reviews.

I rebased again and changed the code so that it adapts to the tip of master. The code now is better and I have to move less things around thanks to https://github.com/cilium/cilium/commit/513296652c0244c08914ac0760d6717f0a466004 :)

**Comment by mrostecki** [comment]
test-me-please

**Comment by manuelbuil** [comment]
> test-me-please

Could it be that tests are hitting a timeout?

**Comment by joestringer** [comment]
Yes, this looks to be the case:
https://jenkins.cilium.io/job/Cilium-PR-K8s-oldest-net-next/295/

> Timeout has been exceeded

I'm aware there has been some provider issues combined with this particular job having more tests than the others which can lead to this situation. Given the code changes here I think it's fairly unlikely to actually introduce a kernel-specific regression on net-next; it's also passed all the other jobs so as long as we're fine with the latest code changes then this should be good to merge.

**Comment by joestringer** [comment]
@manuelbuil are you still making any changes? If not, please mark "ready to review".

**Comment by manuelbuil** [comment]
> @manuelbuil are you still making any changes? If not, please mark "ready to review".

No, patch is ready to review. I can't add or remove any label, so not sure how to mark it as ready to review or change the draft status. Can you help me?

**Comment by mrostecki** [comment]
test-me-please

**Comment by mrostecki** [comment]
https://jenkins.cilium.io/job/Cilium-PR-K8s-newest-kernel-4.9/358 failed with

```
12:38:10  • Failure [298.763 seconds]
12:38:10  K8sDatapathConfig
12:38:10  /home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:436
12:38:10    Etcd
12:38:10    /home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:436
12:38:10      Check connectivity [It]
12:38:10      /home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:471
12:38:10  
12:38:10      cilium pre-flight checks failed
[2020-05-25T10:38:10.986Z]     Expected
[2020-05-25T10:38:10.986Z]         <*errors.errorString | 0xc00025e130>: {
[2020-05-25T10:38:10.986Z]             s: "Cilium validation failed: 4m0s timeout expired: Last polled error: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-s7rdp': Exitcode: 255 \nStdout:\n \t \nStderr:\n \t Error: Cannot get status/probe: Put \"http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe\": context deadline exceeded\n\t \n\t command terminated with exit code 255\n\t \n",
[2020-05-25T10:38:10.986Z]         }
[2020-05-25T10:38:10.986Z]     to be nil
12:38:10  
12:38:10      /home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/helpers/manifest.go:313
```

File: pkg/mtu/detect_linux.go [hunk 4]
```diff
@@ -75,3 +75,33 @@ func autoDetect() (int, error) {
...
+	ifaces, err := net.Interfaces()
+	if err != nil {
+		return 0, fmt.Errorf("Unable to list interfaces: %s", err)
+	}
+
+	for _, iface := range ifaces {
+		addrs, err := iface.Addrs()
+		if err != nil {
+			return 0, fmt.Errorf("Unable to list the addresses: %s", err)
```
Comment (joestringer) [inline pkg/mtu/detect_linux.go]: What kind of failures can trigger this line? Will they affect all interfaces?

Wondering if it's more robust to log a warning and `continue` instead.

File: pkg/mtu/detect_linux.go [hunk 5]
```diff
@@ -75,3 +75,33 @@ func autoDetect() (int, error) {
...
+		}
+
+		for _, addr := range addrs {
+			myIP, _, err := net.ParseCIDR(addr.String())
+
+			if err != nil {
+				return 0, fmt.Errorf("Unable to parse the CIDR: %s", err)
```
Comment (joestringer) [inline pkg/mtu/detect_linux.go]: Same comment as above, presumably it's better to skip cases we can't handle than to error out on the MTU detection entirely?

File: pkg/mtu/detect_linux.go [hunk 6]
```diff
@@ -75,3 +75,33 @@ func autoDetect() (int, error) {
...
+			}
+
+			if myIP.Equal(ip) == true {
+				myMTU := iface.MTU
+				log.Infof("External network interface uses MTU %d. Cilium will use that MTU too", myMTU)
```
Comment (joestringer) [inline pkg/mtu/detect_linux.go]: Please format these logs with all of the info about how this MTU was detected, using the `WithFields()` syntax as that's friendlier to log parsers. Example (note some `logfields` constants might not exist from here, you may need to add them):

```suggestion
				log.WithFields(
				  logfields.Device: iface.Name(),
				  logfields.IPAddr: ip,
				  logfields.MTU: myMTU,
				).Info("Inheriting MTU from external network interface")
```

File: pkg/mtu/mtu.go [hunk 7]
```diff
@@ -96,13 +98,17 @@ type Configuration struct {
 // specified, otherwise it will be automatically detected. if encapEnabled is
 // true, the MTU is adjusted to account for encapsulation overhead for all
 // routes involved in node to node communication.
-func NewConfiguration(authKeySize int, encryptEnabled bool, encapEnabled bool, mtu int) Configuration {
+func NewConfiguration(authKeySize int, encryptEnabled bool, encapEnabled bool, mtu int, nodeInternalIP net.IP) Configuration {
```
Comment (joestringer) [inline pkg/mtu/mtu.go]: nit: This variable is named `nodeInternalIP`, but the parameter is passed from `node.GetExternalIP()`. From the `mtu` package perspective there's no difference, this is just the `mtuDetectIP` so it would be less confusing to name it more neutrally (or at the very least, matching the callers).

File: pkg/mtu/detect_linux.go [hunk 8]
```diff
@@ -75,3 +75,33 @@ func autoDetect() (int, error) {
 
 	return EthernetMTU, nil
 }
+
+// getMTUFromIf finds the interface that holds the ip and returns its mtu
+func getMTUFromIf(ip net.IP) (int, error) {
+	ifaces, err := net.Interfaces()
+	if err != nil {
+		return 0, fmt.Errorf("Unable to list interfaces: %s", err)
```
Comment (joestringer) [inline pkg/mtu/detect_linux.go]: I think that we should use `errors.Wrap()` here to retain the original error properly through the stack. Similarly for other instances.

File: daemon/cmd/daemon.go [hunk 9]
```diff
@@ -288,7 +288,15 @@ func NewDaemon(ctx context.Context, dp datapath.Datapath) (*Daemon, *endpointRes
...
-	mtuConfig := mtu.NewConfiguration(authKeySize, option.Config.EnableIPSec, option.Config.Tunnel != option.TunnelDisabled, configuredMTU)
+	var mtuConfig mtu.Configuration
+	if node.GetExternalIPv4() != nil {
+		mtuConfig = mtu.NewConfiguration(authKeySize, option.Config.EnableIPSec, option.Config.Tunnel != option.TunnelDisabled, configuredMTU, node.GetExternalIPv4())
+	} else if node.GetIPv6() != nil {
+		mtuConfig = mtu.NewConfiguration(authKeySize, option.Config.EnableIPSec, option.Config.Tunnel != option.TunnelDisabled, configuredMTU, node.GetIPv6())
+	} else {
+		log.Warn("Nodes don't have an external IP. MTU will be fetched from the default interface")
+		mtuConfig = mtu.NewConfiguration(authKeySize, option.Config.EnableIPSec, option.Config.Tunnel != option.TunnelDisabled, configuredMTU, nil)
+	}
```
Comment (joestringer) [inline daemon/cmd/daemon.go]: nit, this is probably a little simpler with:
```suggestion
	externalIP := node.GetExternalIPv4() 
	if externalIP == nil {
		externalIP = node.GetIPv6()
	}
	mtuConfig := mtu.NewConfiguration(authKeySize, option.Config.EnableIPSec, option.Config.Tunnel != option.TunnelDisabled, configuredMTU, externalIP)
```

Then the extra log warning here about not having external IP will already be implied by the other log messages in the path taken inside `mtu.NewConfiguration()`.

**Review by joestringer — CHANGES_REQUESTED** [review]
Overall the idea of taking the externalIP from k8s and using that to determine which device provides 'external' connectivity (and hence governs MTU) seems like a reasonable approach. I wish there were a better way to figure this out than iterating all IPs associated with all devices, but I'm not sure the kernel gives us any better APIs. 

I have a bunch of minor nits that should be easy to address below.

File: pkg/mtu/detect_linux.go (hunk 4 above)
Comment (manuelbuil) [reply pkg/mtu/detect_linux.go]: As far as I see, the error can be triggered because:

1 - iface is nil
2 - The syscalls return an error:
       2.1 - syscall.NetlinkRIB returns an error
       2.2 - syscall.ParseNetlinkMessage returns an error

If any of those errors happen, there will be no slice of addresses and therefore we cannot continue. I am thinking now that if there is an error here, we should default to calculate the mtu as it was originally done, to at least have a value

File: pkg/mtu/detect_linux.go (hunk 5 above)
Comment (manuelbuil) [reply pkg/mtu/detect_linux.go]: Ok, let me redo this and in case of error move to what we had before this patch

File: pkg/mtu/detect_linux.go (hunk 4 above)
Comment (manuelbuil) [reply pkg/mtu/detect_linux.go]: @joestringer ok, I have just realized that I already did that, if there is an error then we will default mtu = EthernetMTU which is 1500. Would substituting the Errors with Warnings solve your concerns? 

```
107                 if nodeInternalIP != nil {
108                         mtu, err = getMTUFromIf(nodeInternalIP)
109                 } else {
110                         mtu, err = autoDetect()
111                 }
112                 if err != nil {
113                         log.WithError(err).Warning("Unable to automatically detect MTU")
114                         mtu = EthernetMTU
115                 }
```

File: pkg/mtu/detect_linux.go (hunk 6 above)
Comment (manuelbuil) [reply pkg/mtu/detect_linux.go]: Ah, thanks! This is a good idea

File: pkg/mtu/mtu.go (hunk 7 above)
Comment (manuelbuil) [reply pkg/mtu/mtu.go]: ok, makes sense, thanks

File: daemon/cmd/daemon.go (hunk 9 above)
Comment (manuelbuil) [reply daemon/cmd/daemon.go]: ok, I'll add a comment to clarify this

File: pkg/mtu/detect_linux.go (hunk 8 above)
Comment (manuelbuil) [reply pkg/mtu/detect_linux.go]: Ok, thanks!

File: pkg/mtu/detect_linux.go (hunk 4 above)
Comment (joestringer) [reply pkg/mtu/detect_linux.go]: My concern was specifically if we have a device list like:

- random dev
- random dev that fails in some way (eg fail to dump addresses)
- device with the IP we're looking for

Then even if we would otherwise be able to fetch the addresses from the right device, the failure from a previous device may cause the autodetection to fail overall.

It's probably a bit far-fetched that we hit a case like this, but I wanted to at least ask the queston to see whether it's worth taking a `log; continue` approach in this detection logic.

**Review by manuelbuil — COMMENTED** [review]
Thanks for the review @joestringer

File: pkg/mtu/detect_linux.go (hunk 4 above)
Comment (manuelbuil) [reply pkg/mtu/detect_linux.go]: Ok, I understand what you mean now. You are right, it would fail and we don't want that. Let me change the code following your suggestion

**Comment by mrostecki** [comment]
test-me-please

**Comment by mrostecki** [comment]
test-me-please

**Review by vadorovsky — APPROVED** [review]

**Comment by mrostecki** [comment]
test-me-please

**Comment by mrostecki** [comment]
I guess that the GKE test failure can be ignored.

**Review by joestringer — APPROVED** [review]
