### PR TITLE
Fix downgrade from Cilium 1.2 to earlier versions

### LINKED ISSUE #4899: nil pointer dereference in cilium 1.0.4 after running master
One of my PRs got a test failure, the PR itself is not changing any fundamental things. https://github.com/cilium/cilium/pull/4877

Unfortunately it got a panic on the cilium to master upgrade test.

```
2018-07-19T00:00:47.763062707Z panic: runtime error: invalid memory address or nil pointer dereference

2018-07-19T00:00:47.763095759Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8781eb]
2018-07-19T00:00:47.763100173Z 
2018-07-19T00:00:47.763103458Z goroutine 126 [running]:
2018-07-19T00:00:47.763107129Z github.com/cilium/cilium/pkg/option.(*BoolOptions).IsEnabled(0x0, 0x1dd2cc6, 0x5, 0x0)
2018-07-19T00:00:47.763109916Z 	/go/src/github.com/cilium/cilium/pkg/option/option.go:172 +0x2b
2018-07-19T00:00:47.763114334Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).updateLogger(0xc421731900)
2018-07-19T00:00:47.763118656Z 	/go/src/github.com/cilium/cilium/pkg/endpoint/log.go:56 +0x752
2018-07-19T00:00:47.763123166Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).getLogger(0xc421731900, 0xc42162b400)
2018-07-19T00:00:47.763127455Z 	/go/src/github.com/cilium/cilium/pkg/endpoint/log.go:30 +0x2b
2018-07-19T00:00:47.763131664Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).logStatusLocked(0xc421731900, 0x0, 0x0, 0x1dee783, 0x10)
2018-07-19T00:00:47.763136104Z 	/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:1543 +0x1b8
2018-07-19T00:00:47.763139429Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).SetStateLocked(0xc421731900, 0x1de5043, 0xc, 0x1dee783, 0x10, 0xc4214ed0e0)
2018-07-19T00:00:47.763142624Z 	/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:1989 +0x134
2018-07-19T00:00:47.763145327Z github.com/cilium/cilium/pkg/endpoint.(*Endpoint).LeaveLocked(0xc421731900, 0x2e11980, 0xc420461c00, 0x2e05940, 0xc4201b1c80, 0xc4214ed070)
2018-07-19T00:00:47.763168508Z 	/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:1763 +0x16d
2018-07-19T00:00:47.763173399Z main.(*Daemon).deleteEndpointQuiet(0xc420461c00, 0xc421731900, 0x45, 0xc4214abf80, 0x1)
2018-07-19T00:00:47.76317751Z 	/go/src/github.com/cilium/cilium/daemon/endpoint.go:433 +0x33b
2018-07-19T00:00:47.763180687Z main.(*Daemon).SyncState.func1(0xc421615101, 0xc420461c00, 0xc421731900, 0xc421615110, 0xc421615180)
2018-07-19T00:00:47.763183568Z 	/go/src/github.com/cilium/cilium/daemon/state.go:79 +0xa4e
2018-07-19T00:00:47.763186577Z created by main.(*Daemon).SyncState
2018-07-19T00:00:47.763190022Z 	/go/src/github.com/cilium/cilium/daemon/state.go:67 +0x1e4
```

Cilium revision 228c4e597d0e75f447c593bd2098501b8128ff23

This might have been introduced by recent changes in https://github.com/cilium/cilium/pull/4828

[test_results_Cilium-PR-Ginkgo-Tests-Validated_5084_BDD-Test-PR.zip](https://github.com/cilium/cilium/files/2210039/test_results_Cilium-PR-Ginkgo-Tests-Validated_5084_BDD-Test-PR.zip)

### PR DESCRIPTION
**Pull request by joestringer**
Commits 607b8179ff7a ("option: Refactor BoolOptions into IntOptions")
and 8f0279e3788e ("endpoint: Rename Opts -> Options") reworked the
options for an endpoint to be based on integers rather than booleans. To
avoid introducing upgrade problems, the field was renamed. However, this
introduced downgrade problems: If an endpoint is created when running
Cilium 1.2 or later, then the Cilium version is set to 1.1 or earlier,
then the earlier version of Cilium will attempt to restore the endpoints
that were serialized to the `lxc_config.h` from Cilium 1.2.

Since Cilium 1.2 doesn't serialize the `Opts` field (as map[string]bool)
the earlier version of Cilium can't restore the options correctly, and
as a result may dereference the options field of such restored endpoints
and even crash.

To avoid this, on newer versions of Cilium we will always serialize both
forms of the options: the `Opts` (map[string]bool) from earlier
versions, and `Options` (map[string]int) from newer versions. This means
that older versions can restore using `Opts`, and newer versions can
restore using `Options`.

In a subsequent Cilium release, perhaps 1.5 or later, we can consider
dropping support for downgrade to 1.1 or earlier and remove this code.

Fixes: #4899

Manually tested via `cilium/cilium:fix-options-downgrade` image on DockerHub, then following v1.0 upgrade instructions.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4917)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

File: pkg/endpoint/endpoint.go [hunk 1]
```diff
@@ -461,6 +461,11 @@ type Endpoint struct {
 	// Proxy port 0 indicates no proxy redirection.
 	// All fields within the PolicyKey and the proxy port must be in host byte-order.
 	desiredMapState PolicyMapState
+
+	///////////////////////
+	// DEPRECATED FIELDS //
```
Comment (ianvernon) [inline pkg/endpoint/endpoint.go:466]: Nit: can you mark the code as deprecated here. Use the standard golang convention for deprecated fields:

https://blog.golang.org/godoc-documenting-go-code , search for "Deprecated".

Example: https://golang.org/src/archive/tar/common.go?h=Deprecated%3A#L175

Also specify when this field is used here.

**Review by ianvernon — DISMISSED** [review]

File: pkg/endpoint/endpoint.go (hunk 1 above)
Comment (joestringer) [reply pkg/endpoint/endpoint.go:466]: Thanks for the example, I didn't realise there was a convention. I'll fix this up.

I would like to put a big banner for three sections here actually, public (ensure API stability), private (if it's in this section and exported then that's erroneous), and deprecated (please please please don't use or extend). At the moment, I find it difficult to figure out exactly which fields we care about API stability for.

**Comment by joestringer** [comment]
Green build, I'll rebase and do a comment update to address @ianvernon's comment.

File: pkg/endpoint/endpoint.go (hunk 1 above)
Comment (ianvernon) [reply pkg/endpoint/endpoint.go:466]: Agreed, organizing the fields within the endpoint to represent their state / meaningfulness to API stability is a great idea.
