### PR TITLE
CI: Wait for cilium to regenerate when updating k8s network policies 

### LINKED ISSUE #10760: CI: K8sPolicyTest varied flakes
This seems like a race between adding this policy and regenerating. My current guess is that the way we wait for k8s netpols to regenerate is not as robust as what we do for CNPs.

These are all of the form:
```
Expected command: kubectl exec -n 202003300621k8spolicytestbasictestchecksallkindofkubernetespoli app2-64975875bc-j29hw -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 8 http://1.1.1.1/ -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'"
To have failed, but it was successful:
```

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/10979/testReport/junit/Suite-k8s-1/11/K8sPolicyTest_Basic_Test_Denies_traffic_with_k8s_default_deny_ingress_egress_policy/

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/10976/testReport/junit/Suite-k8s-1/18/K8sPolicyTest_Basic_Test_Denies_traffic_with_k8s_default_deny_egress_policy/

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/10970/

https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/10967/

There may be cross-test effects. In one case a number of tests failed later with cilium preflight failures (no socket found) https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/10971/

### PR DESCRIPTION
**Pull request by raybejjani**
Reviewers: I'm pretty sure that I haven't introduced new instability to our tests. I'm not sure that this fixes https://github.com/cilium/cilium/issues/10760.

We recently made some of the update logic around policies async. This
has allowed a hidden race with netpols when using the `.PolicyAction`
functions to add policies. We previously simply checked that the policy
was present in cilium. We now also wait for the regeration to complete.

### CODE REVIEW

**Comment by raybejjani** [comment]
test-focus K8sPolicyTest Basic Test Denies traffic with k8s default.*

**Comment by raybejjani** [comment]
test-gke K8sPolicyTest Basic Test Denies traffic with k8s default.*

**Comment by raybejjani** [comment]
test-focus K8sPolicyTest Basic Test Denies traffic with k8s default.*

**Comment by raybejjani** [comment]
test-gke K8sPolicyTest Basic Test Denies traffic with k8s default.*

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-gke K8sPolicyTest Basic Test Denies traffic with k8s default.*

**Comment by raybejjani** [comment]
test-focus K8sPolicyTest Basic Test Denies traffic with k8s default.*

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-gke K8s.*

**Comment by raybejjani** [comment]
test-focus K8s.*

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-gke K8s.*

**Comment by raybejjani** [comment]
test-focus K8s.*

**Comment by raybejjani** [comment]
test-me-please

**Comment by raybejjani** [comment]
test-gke

File: test/helpers/kubectl.go [hunk 1]
```diff
@@ -2094,17 +2108,21 @@ func (kub *Kubectl) CiliumPolicyAction(namespace, filepath string, action Resour
...
 					kub.Logger().Infof("Policy '%s' is not ready on Cilium pod '%s'", item, ciliumPod)
 					return false
 				}
+
+				ctx, cancel := context.WithTimeout(context.Background(), ShortCommandTimeout)
+				defer cancel()
+				desiredRevision := revisions[ciliumPod] + 1
+				res := kub.CiliumExecContext(ctx, ciliumPod, fmt.Sprintf("cilium policy wait %d --max-wait-time %f", desiredRevision, ShortCommandTimeout.Seconds()))
+				if !(res.GetExitCode() != 0) {
+					kub.Logger().Infof("Failed to wait for policy revision %d on pod %s", desiredRevision, ciliumPod)
```
Comment (aanm) [inline test/helpers/kubectl.go:2123]: Doesn't the same fix needs to be applied a couple lines bellow in the `CiliumClusterwidePolicyAction` function?

**Review by aanm — CHANGES_REQUESTED** [review]

File: test/helpers/kubectl.go (hunk 1 above)
Comment (raybejjani) [reply test/helpers/kubectl.go:2123]: No, that one seems to have a status field that we update (so it's more like the CNP handling above). Since you're here, though, you don't happen to know if there is a status that we update on the netpol? I would prefer that over this little hack.

Comment (aanm) [reply test/helpers/kubectl.go:2123]: discussed offline, I thought this was for the CNP and not K8s netpol

**Review by aanm — APPROVED** [review]
