### PR TITLE
egress gw exclude internal traffic

### LINKED ISSUE #16147: Egress for destination CIDR 0.0.0.0/0 blocks all network connections
## Bug report

**General Information**

- Cilium version (run `cilium version`)
- Kernel version (run `uname -a`)
- Orchestration system version in use (e.g. `kubectl version`, ...)
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

1. Use the following egress rule
```
apiVersion: cilium.io/v2alpha1
kind: CiliumEgressNATPolicy
metadata:
  name: egress-mailserver
spec:
  egress:
  - podSelector:
      matchLabels:
        # The following label selects default namespace
        io.kubernetes.pod.namespace: mailserver
    # Or use namespace label selector to select multiple namespaces
    # namespaceSelector:
    #  matchLabels:
    #    ns: default
  destinationCIDRs:
  - 0.0.0.0/0
  egressSourceIP: "51.195.x.x" 
```
2. curl http://checkip.amazonaws.com from a pod
 
Expected result: 51.195.x.x
Actual result: bash-5.0# curl http://checkip.amazonaws.com
curl: (6) Could not resolve host: checkip.amazonaws.com

### PR DESCRIPTION
**Pull request by kkourt**
This PR aims to do fix an issue where egress gw policy is incorrectly applied to internal cluster traffic, using a patch originally from @anfernee. In addition to that, it refactors the function `snat_v4_needed` so that it is easier to follow. Since this is brittle code, the refactoring is split into small patches so that they are easy to review.

Fixes: #16147

```release-note
fix incorrect application of egress gateway policy to internal cluster traffic.
require  a 5.2 kernel or later for the egress gateway policy feature.
```

### CODE REVIEW

**Comment by kkourt** [comment]
/test-only --focus="K8sEgressGateway" --kernel_version="net-next"

File: bpf/bpf_lxc.c [hunk 1]
```diff
@@ -797,6 +797,21 @@ static __always_inline int handle_ipv4_from_lxc(struct __ctx_buff *ctx,
...
+		if (ipv4_is_in_subnet(ip4->daddr, IPV4_SNAT_EXCLUSION_DST_CIDR,
+				      IPV4_SNAT_EXCLUSION_DST_CIDR_LEN))
+			goto skip_egress_gateway;
+#endif
+
+		/* If tunnel endpoint is found in ipcache, it means the remote endpoint is
+		 * in cluster. In this case, we should skip egress gateway. If destination
+		 * is either remote node or host node, also skip egress gateway.
+		 */
+		if (tunnel_endpoint != 0 || *dst_id == REMOTE_NODE_ID || *dst_id == HOST_ID)
```
Comment (pchaigno) [inline bpf/bpf_lxc.c:804]: Isn't the `tunnel_endpoint` check only required if `IPV4_SNAT_EXCLUSION_DST_CIDR` is undefined?

File: bpf/lib/nodeport.h [hunk 2]
```diff
@@ -1207,6 +1188,22 @@ static __always_inline bool snat_v4_needed(struct __ctx_buff *ctx, __be32 *addr,
...
+	if (info->sec_label != REMOTE_NODE_ID) {
+		struct egress_info *einfo;
+
+		einfo = lookup_ip4_egress_endpoint(ip4->saddr, ip4->daddr);
+		if (einfo) {
+			*addr = einfo->egress_ip;
+			*from_endpoint = true;
+			return true;
+		}
+	}
```
Comment (pchaigno) [inline bpf/lib/nodeport.h]: Instead of checking if the destination is a remote node here, couldn't we extend the previous check (`info->sec_label == REMOTE_NODE_ID` on line 1188) to also run if `!defined(TUNNEL_MODE) && defined(ENABLE_EGRESS_GATEWAY)`? Then, we wouldn't need this code here (lines 1191--1206) and we could run the next egressgw map lookup regardless of whether `ep` is NULL or not. It seems it would simplify the code a bit.

The indentation for this block also seems broken.

File: bpf/lib/nodeport.h [hunk 3]
```diff
@@ -1189,20 +1189,20 @@ static __always_inline bool snat_v4_needed(struct __ctx_buff *ctx, __be32 *addr,
...
+			if (info->sec_label != REMOTE_NODE_ID) {
+				struct egress_info *einfo;
+
+				einfo = lookup_ip4_egress_endpoint(ip4->saddr, ip4->daddr);
+				if (einfo) {
+					*addr = einfo->egress_ip;
+					*from_endpoint = true;
+					return true;
+				}
+			}
```
Comment (pchaigno) [inline bpf/lib/nodeport.h:1218]: Please merge `bpf: snat_v4_needed: fix indentation` in previous patch.

File: bpf/lib/nodeport.h [hunk 4]
```diff
@@ -1157,6 +1157,20 @@ static __always_inline bool snat_v4_needed(struct __ctx_buff *ctx, __be32 *addr,
 		return false;
 #endif
 
+#ifdef ENABLE_IP_MASQ_AGENT
```
Comment (pchaigno) [inline bpf/lib/nodeport.h:1168]: Nit: Commit title has a small typo: `bpf: snat_v4_needed: move ip-masq-agent further ip` (`ip` -> `up`).

File: bpf/lib/nodeport.h [hunk 5]
```diff
@@ -1157,71 +1158,72 @@ static __always_inline bool snat_v4_needed(struct __ctx_buff *ctx, __be32 *addr,
...
 
 	ep = __lookup_ip4_endpoint(ip4->saddr);
-	if (ep && !(ep->flags & ENDPOINT_F_HOST)) {
-		struct remote_endpoint_info *info;
-		*from_endpoint = true;
+	/* If this is a localhost endpoint, no SNAT is needed. */
+	if (ep && ep->flags & ENDPOINT_F_HOST)
+		return false;
+
+	*from_endpoint = true;
```
Comment (pchaigno) [inline bpf/lib/nodeport.h]: So `from_endpoint` used to be true only if the source endpoint was local to the node, now it will also be true if the source endpoint is remote. AFAICS, that only happens for the egress gateway case. The only consumer I found of this variable is `snat_v4_can_skip`, but I'm not able to tell if this change could cause issues there. Maybe @brb can have a second look.

(@brb `snat_v4_can_skip` could really use a couple comments to clarify the intent of the different conditions.)

File: bpf/lib/nodeport.h [hunk 6]
```diff
@@ -1167,17 +1181,6 @@ static __always_inline bool snat_v4_needed(struct __ctx_buff *ctx, __be32 *addr,
...
-		/* Do not SNAT if dst belongs to any ip-masq-agent
-		 * subnet.
-		 */
-		struct lpm_v4_key pfx;
-
-		pfx.lpm.prefixlen = 32;
-		memcpy(pfx.lpm.data, &ip4->daddr, sizeof(pfx.addr));
-		if (map_lookup_elem(&IP_MASQ_AGENT_IPV4, &pfx))
-			return false;
-#endif
```
Comment (pchaigno) [inline bpf/lib/nodeport.h:1196]: This commit doesn't just optimize but also changes the logic. We used to only lookup the ipmasq map if (1) the source was a local endpoint and (2) the destination was present in the ipcache. This logic was introduced by commit 0a6160f6102 ("datapath: Add ip-masq-agent implementation"). The commit description makes me think that (1) might have been intentional. (2) seems stranger but I suspect @brb had a good reason to add the map lookup in this exact location.

File: bpf/lib/nodeport.h [hunk 7]
```diff
@@ -1211,19 +1209,24 @@ static __always_inline bool snat_v4_needed(struct __ctx_buff *ctx, __be32 *addr,
 		}
 #endif
 
-		tuple.nexthdr = ip4->protocol;
-		tuple.daddr = ip4->daddr;
-		tuple.saddr = ip4->saddr;
```
Comment (pchaigno) [inline bpf/lib/nodeport.h]: I'm not sure I see the benefit of `bpf: snat_v4_needed: refactor reply check`. If anything, the incorrect indentation (w.r.t. to the conditions) feels misleading to me. If the goal is to have the value of `is_reply` at hand when reading the consumer code, maybe moving the initialization of this variable here would be enough?

File: bpf/lib/nodeport.h [hunk 8]
```diff
@@ -1231,22 +1233,6 @@ static __always_inline bool snat_v4_needed(struct __ctx_buff *ctx, __be32 *addr,
...
-		struct egress_info *einfo;
-
-		einfo = lookup_ip4_egress_endpoint(ip4->saddr, ip4->daddr);
-		if (einfo) {
-			*addr = einfo->egress_ip;
-			*from_endpoint = true;
-			return true;
-		}
-	}
-#endif
```
Comment (pchaigno) [inline bpf/lib/nodeport.h]: Commit `bpf: snat_v4_needed: single egress gw policy check` can be merged into the commit it fixes if you move the refactoring logic to the beginning of the PR's commit history. That way reviewers wouldn't waste time commenting on the first commits...

File: bpf/lib/nodeport.h [hunk 9]
```diff
@@ -1175,9 +1175,7 @@ static __always_inline bool snat_v4_needed(struct __ctx_buff *ctx, __be32 *addr,
 		return false;
 
 	*from_endpoint = true;
-
-	info = ipcache_lookup4(&IPCACHE_MAP, ip4->daddr,
-			       V4_CACHE_KEY_LEN);
```
Comment (pchaigno) [inline bpf/lib/nodeport.h]: I'm guessing commit `bpf: snat_v4_needed: misc refactor cleanups` was intended to contain more misc. changes as you implemented but didn't end up containing any others? This simple newline could be removed in the commit where you removed the indentation; that wouldn't make it harder to review.

File: test/k8sT/Egress.go [hunk 10]
```diff
@@ -106,7 +106,7 @@ var _ = SkipDescribeIf(func() bool {
 
 	AfterFailed(func() {
 		// Especially check if there are duplicated address allocated on cilium_host
-		kubectl.CiliumReport("ip addr", "cilium bpf egress list", "cilium bpf nat list")
```
Comment (pchaigno) [inline test/k8sT/Egress.go:109]: Nit: Seems there might be a small typo somewhere in clause `which resulted in commands that were executed at failure to diagnose issues to with the policy removed.` in the commit description (commit `k8sT/Egress: restructure test`). I'm not able to parse it.

File: test/k8sT/Egress.go [hunk 11]
```diff
@@ -179,22 +179,33 @@ var _ = SkipDescribeIf(func() bool {
...
-				testConnectivity(false)
-				testConnectivity(true)
+			Context("egress gw policy", func() {
+				BeforeAll(func() {
+					applyEgressPolicy()
+					kubectl.WaitForEgressPolicyEntry(k8s1IP, outsideIP)
+					kubectl.WaitForEgressPolicyEntry(k8s2IP, outsideIP)
+				})
+				AfterAll(func() {
+					defer kubectl.Delete(policyYAML)
```
Comment (pchaigno) [inline test/k8sT/Egress.go]:
```suggestion
					kubectl.Delete(policyYAML)
```

File: Documentation/gettingstarted/egress-gateway.rst [hunk 12]
```diff
@@ -12,6 +12,10 @@ Egress Gateway (beta)
 
 .. include:: ../beta.rst
 
+.. note::
```
Comment (pchaigno) [inline Documentation/gettingstarted/egress-gateway.rst:15]: In commit `daemon: require kernel >= 5.4 for egress gateway`, seems a part of the first sentence is missing:

> After the modifications in recent , 4.19 kernel is unable to verify bpf_lxc:

File: Documentation/gettingstarted/egress-gateway.rst [hunk 13]
```diff
@@ -12,6 +12,10 @@ Egress Gateway (beta)
...
+
+   Egress Gateway requires a 5.4 or more recent kernel.
```
Comment (pchaigno) [inline Documentation/gettingstarted/egress-gateway.rst]: The 1M instructions limit was introduced in Linux v5.2, with commit https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=c04c0d2b968ac45d6ef020316808ef6c82325a82.
```suggestion
   Egress Gateway requires a 5.2 or more recent kernel.
```

File: Documentation/operations/system_requirements.rst [hunk 14]
```diff
@@ -186,6 +186,7 @@ Full support for :ref:`session-affinity`    >= 5.7
 BPF-based proxy redirection                 >= 5.7
 BPF-based host routing                      >= 5.10
 Socket-level LB bypass in pod netns         >= 5.7
+:ref:`egress-gateway`                       >= 5.4
```
Comment (pchaigno) [inline Documentation/operations/system_requirements.rst]:
```suggestion
:ref:`egress-gateway`                       >= 5.2
```

File: bpf/Makefile [hunk 15]
```diff
@@ -169,7 +169,9 @@ HOST_OPTIONS = $(LXC_OPTIONS) \
 
 ifndef MAX_HOST_OPTIONS
 MAX_HOST_OPTIONS = $(MAX_BASE_OPTIONS) -DENCAP_IFINDEX=1 -DTUNNEL_MODE=1
-ifneq ("$(KERNEL)","49")
+
+# Egress Gateway should only be enabled for >= 5.4 kernels
+ifneq (,$(filter $(KERNEL),"54" "netnext"))
```
Comment (pchaigno) [inline bpf/Makefile:174]: Oh, wow! We can do that? :exploding_head:

File: daemon/cmd/daemon.go [hunk 16]
```diff
@@ -663,6 +664,11 @@ func NewDaemon(ctx context.Context, cancel context.CancelFunc, epMgr *endpointma
 				option.EnableHostLegacyRouting)
 		}
 	}
+	if option.Config.EnableEgressGateway {
+		if !probes.NewProbeManager().GetMisc().HaveLargeInsnLimit {
+			return nil, nil, fmt.Errorf("egress gateway needs kernel 5.4 or newer")
```
Comment (pchaigno) [inline daemon/cmd/daemon.go]:
```suggestion
			return nil, nil, fmt.Errorf("egress gateway needs kernel 5.2 or newer")
```

File: test/helpers/utils.go [hunk 17]
```diff
@@ -515,7 +515,7 @@ func DoesNotRunOn419Kernel() bool {
 	return !RunsOn419Kernel()
 }
 
-// RunsOn419OrLaterKernel checks whether a test case is running on the bpf-next,
+// RunsOn419OrLaterKernel checks whether a test case is running on 4.19 or later kernel
 // 4.19.x (x > 57), or 5.4 kernels.
```
Comment (pchaigno) [inline test/helpers/utils.go]:
```suggestion
// RunsOn419OrLaterKernel checks whether a test case is running on 4.19 or
// later kernel.
```

File: test/k8sT/Egress.go [hunk 18]
```diff
@@ -25,7 +25,7 @@ import (
 )
 
 var _ = SkipDescribeIf(func() bool {
-	return helpers.RunsOnEKS() || helpers.RunsOnGKE() || helpers.DoesNotRunWithKubeProxyReplacement() || helpers.DoesNotExistNodeWithoutCilium()
+	return helpers.RunsOnEKS() || helpers.RunsOnGKE() || helpers.DoesNotRunWithKubeProxyReplacement() || helpers.DoesNotExistNodeWithoutCilium() || helpers.DoesNotRunOn54Kernel()
```
Comment (pchaigno) [inline test/k8sT/Egress.go]:
```suggestion
	return helpers.RunsOnEKS() || helpers.RunsOnGKE() || helpers.DoesNotRunWithKubeProxyReplacement() || helpers.DoesNotExistNodeWithoutCilium() || helpers.DoesNotRunOn54OrLaterKernel()
```

**Review by pchaigno — CHANGES_REQUESTED** [review]
The code changes look good to me overall and it's nice to see a bit of refactoring to the SNAT logic. I think some of the changes need a careful review from @brb as they change the logic a bit besides the intended refactoring/optimization.

The commit history however makes it painful to review. It seems a lot of care was taken to avoid changing the first commit—I'm not sure why. As a result, comments on the first commit end up being addressed by later commits and I had to review the same piece of code several times. I've tried to leave comments on how that can be improved.

(If we need this merged quickly, I think several pieces of refactoring could be moved to another pull request as the egress gateway fix does not depend on them. In general, I'd advise for such smaller pull requests when possible anyway. Easier to review, faster to merge, easier to backport.)

File: bpf/bpf_lxc.c (hunk 1 above)
Comment (kkourt) [reply bpf/bpf_lxc.c:804]: I'm not sure 🤔  @brb?

File: bpf/lib/nodeport.h (hunk 2 above)
Comment (kkourt) [reply bpf/lib/nodeport.h]: > couldn't we extend the previous check 

The previous check will `return false`. Do you mean to `return false` if `info->sec_label == REMOTE_NODE_ID` when `ENABLE_EGRESS_GATEWAY` is defined? Would this be correct? I am not sure.

File: bpf/lib/nodeport.h (hunk 3 above)
Comment (kkourt) [reply bpf/lib/nodeport.h:1218]: Makes sense will do.

File: bpf/lib/nodeport.h (hunk 6 above)
Comment (kkourt) [reply bpf/lib/nodeport.h:1196]: I did this change together with @brb and said it was fine, but I guess it is worth another look.

File: bpf/lib/nodeport.h (hunk 5 above)
Comment (kkourt) [reply bpf/lib/nodeport.h]: Ah good catch.

I guess maintaining the original semantics would mean doing:
```
if (ep)
   *from_endpoint = true;
```

File: bpf/lib/nodeport.h (hunk 9 above)
Comment (kkourt) [reply bpf/lib/nodeport.h]: Yeah, not sure what the best approach here. I could also fold this one as well. @brb said that it would be easier to review if the modifications were small and obvious. I probably took that too far :)

File: bpf/lib/nodeport.h (hunk 7 above)
Comment (kkourt) [reply bpf/lib/nodeport.h]: For me it's easier to understand what is going on if variables are declared exactly when they are used. Because by looking at this:
```
+               {
+                       bool is_reply = false;
+                       struct ipv4_ct_tuple tuple = {
+                               .nexthdr = ip4->protocol,
+                               .daddr = ip4->daddr,
+                               .saddr = ip4->saddr,
+                       };
+
+                       /* The packet is a reply, which means that outside
+                        * has initiated the connection, so no need to SNAT
+                        * the reply.
+                        */
+                       if (!ct_is_reply4(get_ct_map4(&tuple), ctx,
+                                         ETH_HLEN + ipv4_hdrlen(ip4),
+                                         &tuple, &is_reply) &&
+                           is_reply)
+                               return false;
+               }
```

instead of this:


```
-               tuple.nexthdr = ip4->protocol;
-               tuple.daddr = ip4->daddr;
-               tuple.saddr = ip4->saddr;
-
-               /* The packet is a reply, which means that outside
-                * has initiated the connection, so no need to SNAT
-                * the reply.
-                */
-               if (!ct_is_reply4(get_ct_map4(&tuple), ctx,
-                                 ETH_HLEN + ipv4_hdrlen(ip4),
-                                 &tuple, &is_reply) &&
-                   is_reply)
-                       return false;
```

The following questions have obvious answers:
 * are there fields in the tuple that are initialized elsewhere?
 * is the tuple and is_reply used somewhere after this function?

Might be just me though :)

File: bpf/lib/nodeport.h (hunk 8 above)
Comment (kkourt) [reply bpf/lib/nodeport.h]: OK, if people think that the logic is correct, I think the best approach is what you said: fold: the original fix, the indentation fix, and this one into one commit. and the refactoring fixes we can put on top (or remove).

File: Documentation/gettingstarted/egress-gateway.rst (hunk 13 above)
Comment (kkourt) [reply Documentation/gettingstarted/egress-gateway.rst]: @jibi any reason this was `5.4` in the original commit?

File: test/k8sT/Egress.go (hunk 10 above)
Comment (kkourt) [reply test/k8sT/Egress.go:109]: thanks, will fix.

File: bpf/bpf_lxc.c (hunk 1 above)
Comment (brb) [reply bpf/bpf_lxc.c:804]: Yeah, if the `IPV4_SNAT_EXCLUSION_DST_CIDR` is undefined, we can remove the check, as they both check for the same - whether the dst is a pod.

File: bpf/lib/nodeport.h [hunk 19]
```diff
@@ -1207,6 +1188,22 @@ static __always_inline bool snat_v4_needed(struct __ctx_buff *ctx, __be32 *addr,
 			if (info->sec_label == REMOTE_NODE_ID)
 				return false;
 #endif
+#if defined(ENABLE_EGRESS_GATEWAY) && !defined(IS_BPF_OVERLAY)
```
Comment (brb) [inline bpf/lib/nodeport.h]: Having comment why `!defined(IS_BPF_OVERLAY)` would be useful.

File: bpf/lib/nodeport.h (hunk 3 above)
Comment (brb) [reply bpf/lib/nodeport.h:1218]: Let's do once all reviews are done :-)

File: bpf/lib/nodeport.h (hunk 5 above)
Comment (brb) [reply bpf/lib/nodeport.h]: With the introduction of egress GW `from_endpoint` has changed it meaning - previously it meant a local endpoint, now it means both - local endpoint and a remote endpoint which is a target of egress GW policy.

> (@brb snat_v4_can_skip could really use a couple comments to clarify the intent of the different conditions.)

:+1:

File: bpf/lib/nodeport.h (hunk 6 above)
Comment (brb) [reply bpf/lib/nodeport.h:1196]: Could you elaborate why the logic is changed in this commit? (1) and (2) premises are still there?

Re (2): scratching my head, but I don't see any reason why the ip-masq-agent check should depend on (2).

Comment (brb) [reply bpf/lib/nodeport.h:1196]: Oh, GH was showing this comment already for the previous commit which confused me :F

File: bpf/lib/nodeport.h (hunk 4 above)
Comment (brb) [reply bpf/lib/nodeport.h:1168]: I think it's been moved too much further up. LPM trie lookup can be expensive. We should do that only if we know that the src is an endpoint.

File: bpf/bpf_lxc.c (hunk 1 above)
Comment (pchaigno) [reply bpf/bpf_lxc.c:804]: Up to you @kkourt. It will reduce complexity a little bit when `IPV4_SNAT_EXCLUSION_DST_CIDR` is defined but at the cost of slightly harder to read code I guess. I don't have a preference of what to do.

File: bpf/lib/nodeport.h (hunk 6 above)
Comment (pchaigno) [reply bpf/lib/nodeport.h:1196]: Ok. So we don't care about (2) but we do for (1) for performance reasons if I'm reading https://github.com/cilium/cilium/pull/17639/commits/64357b35302cb7536f7833b405598216aed083ce#r735072541 correctly.

Also, now that I think about it, I suspect this commit will have a negative complexity impact. In general (though not always true), the further down in the control flow graph you can move a piece of code, the better it is for complexity.

File: bpf/lib/nodeport.h (hunk 7 above)
Comment (pchaigno) [reply bpf/lib/nodeport.h]: I had not though about that second point (clarifies scope of variables); that's a good point. It's really a nit and we don't have a consistent rule today, so I'm fine either way :-)

File: bpf/lib/nodeport.h (hunk 9 above)
Comment (pchaigno) [reply bpf/lib/nodeport.h]: My rationale here is: (1) this change is only possible if a previous commit (the one fixing indentation) exists and (2) it is trivial. Thus, I'd merge both commits (and then would merge in the first commit they both fix). Another way I'd approach this is: style fixes don't merit their own commit unless the code they fix is already in master.

File: bpf/lib/nodeport.h (hunk 6 above)
Comment (brb) [reply bpf/lib/nodeport.h:1196]: >  So we don't care about (2) but we do for (1) for performance reasons

Yep.

File: bpf/lib/nodeport.h [hunk 20]
```diff
@@ -1175,42 +1155,67 @@ static __always_inline bool snat_v4_needed(struct __ctx_buff *ctx, __be32 *addr,
...
 			if (map_lookup_elem(&IP_MASQ_AGENT_IPV4, &pfx))
 				return false;
+		}
 #endif
+
+	ep = __lookup_ip4_endpoint(ip4->saddr);
+	/* If this is a localhost endpoint, no SNAT is needed. */
+	if (ep && ep->flags & ENDPOINT_F_HOST)
+		return false;
+
```
Comment (brb) [inline bpf/lib/nodeport.h]: Maybe we should add comment here saying that "at this point we know, that the src is either a local endpoint or a forwarded packet which might be the subject to egress GW SNAT".

File: Documentation/gettingstarted/egress-gateway.rst (hunk 13 above)
Comment (jibi) [reply Documentation/gettingstarted/egress-gateway.rst]: Just me mistaking versions

File: bpf/lib/nodeport.h (hunk 4 above)
Comment (kkourt) [reply bpf/lib/nodeport.h:1168]: OK, dropping this patch.

File: bpf/lib/nodeport.h (hunk 6 above)
Comment (kkourt) [reply bpf/lib/nodeport.h:1196]: Since this is more complicated that I  originally thought, I'll drop the patch for now.

File: test/k8sT/Egress.go (hunk 10 above)
Comment (kkourt) [reply test/k8sT/Egress.go:109]: wow, the message was really bad. Fixed it.

File: bpf/lib/nodeport.h (hunk 20 above)
Comment (kkourt) [reply bpf/lib/nodeport.h]: Ended up dropping this patch since @pchaigno pointed out some complications that I missed. We can revisit refactoring the function in another PR.

File: bpf/bpf_lxc.c (hunk 1 above)
Comment (kkourt) [reply bpf/bpf_lxc.c:804]: How about we continue this discussion in: https://github.com/cilium/cilium/pull/17688#discussion_r735408426, so that we do not block this PR?

File: bpf/lib/nodeport.h (hunk 19 above)
Comment (kkourt) [reply bpf/lib/nodeport.h]: As @brb pointed offline, there is a check some lines above for this, so I'll remove it

File: bpf/lib/nodeport.h [hunk 21]
```diff
@@ -1207,6 +1188,25 @@ static __always_inline bool snat_v4_needed(struct __ctx_buff *ctx, __be32 *addr,
...
 #endif
+#if defined(ENABLE_EGRESS_GATEWAY)
+			/* We want to exclude internal cluster traffic from the
+			 * egress gateway NAT policy. To this end, we only check
+			 * the map if either of the following conditions are
+			 * true:
+			 *  1. destination is a not a remote node
+			 *  2. there is no local endpoint for source address
+			 */
+			if (info->sec_label != REMOTE_NODE_ID || !ep) {
```
Comment (jibi) [inline bpf/lib/nodeport.h]: I'm not sure I'm following this check. Policies apply only to traffic originating from an endpoint and destined to the outside of the cluster, so why not explicitly check `if (ep && info->sec_label == WORLD_ID)`?

To my understanding with this check we may end up doing some lookups in the policy map when we should not (resulting in internal cluster traffic being SNAT'ed):

* with `info->sec_label != REMOTE_NODE_ID` we are making sure traffic is not destined to a remote node in the cluster, but it could still be destined to a remote endpoint (and so should not be SNAT'ed)
* with `!ep` we are making sure traffic is not originating from an endpoint, but why? Egress policies should always match traffic originating from an endpoint, so we should never find a policy in the map if `ep` is `NULL`

Comment (kkourt) [reply bpf/lib/nodeport.h]: Hm... I also just realized that `!ep` is never true in this case, so the patch does not make any sense as it is :(

Comment (kkourt) [reply bpf/lib/nodeport.h]: > so why not explicitly check if (ep && info->sec_label == WORLD_ID)?

So the first thing I would like to resolve is whether we only need to apply egress gw policy iff `ep != NULL`. (above comment seems to imply that this is the case).

ep is:
```
ep = __lookup_ip4_endpoint(ip4->saddr);
```

And so according to my understanding we will perform the SNAT at the gateway node where we might not have an endpoint for the source address. So I think we should apply the egress policy check both when `ep` and `!ep`. Let me try another version...

Comment (kkourt) [reply bpf/lib/nodeport.h]: Pushed a new version with what, according to my understanding, we need to do. Please let me know what you think.

Comment (kkourt) [reply bpf/lib/nodeport.h]: After discussing this offline, we settled on using ` info->sec_label == WORLD_ID` as a test.

**Review by pchaigno — CHANGES_REQUESTED** [review]
Were all changes merged by mistake into a single commit? It now seems all refactoring changes are in the first commit, with the fix itself. The commit description doesn't reflect that (or even describe the fix correctly) and it's obviously harder to review. Happy to help split it correctly if needed.

File: bpf/lib/nodeport.h (hunk 21 above)
Comment (kkourt) [reply bpf/lib/nodeport.h]: We discussed this with @pchaigno offline, and decided to not use WORLD_ID because, as Paul pointed out, egress traffic might not have a WORLD_ID because it matches CIDR policies.

File: bpf/lib/nodeport.h [hunk 22]
```diff
@@ -1208,8 +1189,31 @@ static __always_inline bool snat_v4_needed(struct __ctx_buff *ctx, __be32 *addr,
 		if (info->sec_label == REMOTE_NODE_ID)
 			return false;
 #endif
+ #if defined(ENABLE_EGRESS_GATEWAY)
+		/* check egress gateway  policy only for traffic which is:
+		 *  - remote, i.e., not from a local endpoint (inc. local host)
+		 *  - is not destined for a remote node
+		 */
+		if (!ep || info->sec_label != REMOTE_NODE_ID) {
+			struct egress_info *einfo;
```
Comment (pchaigno) [inline bpf/lib/nodeport.h:1204]: The code and comment are consistent with the commit description, but I think the comment could use a bit more detail. Maybe something like:
```
/* Check egress gateway policy only for traffic which matches one of the
 * following conditions.
 *  - Not from a local endpoint (inc. local host): that tells us the
 *    traffic was redirected by an egress gateway policy to this node to
 *    be masqueraded.
 *  - Not destined for a remote node: that tells us the traffic is leaving
 *    the cluster. Inter-node traffic to remote pods would either leave
 *    through the tunnel or match the above IPV4_SNAT_EXCLUSION_DST_CIDR
 *    check.
 */
```

(Worth noting this assumes `IPV4_SNAT_EXCLUSION_DST_CIDR` will always be defined when both native routing and BPF masquerading are enabled, which I think is true.)

**Review by pchaigno — APPROVED** [review]
One minor comment on a code comment below, but the logic for the fix & refactoring looks good to me! Thanks for the cleaner commit history as well! :pray:

File: test/k8sT/manifests/egress-nat-policy.yaml [hunk 23]
```diff
@@ -13,3 +13,21 @@ spec:
...
+      matchLabels:
+        zgroup: testDSClient
+    namespaceSelector:
+      matchLabels:
+        ns: cilium-test
+  # Route everything to a black hole.
+  # It shouldn't affect in-cluster traffic.
+  destinationCIDRs:
+  - 0.0.0.0/0
+  egressSourceIP: 1.1.1.1 # It's a black hole
```
Comment (qmonnet) [inline test/k8sT/manifests/egress-nat-policy.yaml]: Probably doesn't matter much, but I think using 1.1.1.1 as a black hole is an abuse of the standards. Traffic probably get discarded anyway, but there _is_ something at that address now - Cloudflare's DNS and some web page at least. (But then I don't have a better suggestion.)

**Review by qmonnet — APPROVED** [review]
Looks good to me

File: test/k8sT/manifests/egress-nat-policy.yaml (hunk 23 above)
Comment (jibi) [reply test/k8sT/manifests/egress-nat-policy.yaml]: Maybe we can use a documentation address for example from the `192.0.2.0/24` block? (See https://datatracker.ietf.org/doc/html/rfc5737#section-3)

**Review by jibi — APPROVED** [review]

**Comment by jibi** [comment]
(Also in commit 5498ca1a248a53d32ec9632eba9e8c47dd3c7d61 the description says "Fix issue:16147", and I believe it should be formatted as "Fixes: #16147" in order to get the issue actually closed once this gets merged)

**Comment by kkourt** [comment]
Thanks for the review!

> (Also in commit [5498ca1](https://github.com/cilium/cilium/commit/5498ca1a248a53d32ec9632eba9e8c47dd3c7d61) the description says "Fix issue:16147", and I believe it should be formatted as "Fixes: #16147" in order to get the issue actually closed once this gets merged)

This is intended so that we do not spam the issues with every rebase. But I should have the proper format in the PR description (will fix momentarily).

**Review by christarazi — COMMENTED** [review]
Came across this PR and noticed the first two commits don't have a descriptive title describing what is changing and why, which made it harder to understand why it is needed. They only state "refactor x/2". If it's not too much of a hassle, could we add a bit more to it?

**Comment by kkourt** [comment]
Thanks for having a look!

> Came across this PR and noticed the first two commits don't have a descriptive title describing what is changing and why, which made it harder to understand why it is needed. They only state "refactor x/2". If it's not too much of a hassle, could we add a bit more to it?

What would you suggest?

The refactor x/2, together with the rest of the commit message:
> This is a preparation patch for subsequent changes. The patch intends to maintain the code behavior.

Was the best I could think of.

**Comment by pchaigno** [comment]
> What would you suggest?
> The refactor x/2, together with the rest of the commit message:
>    "This is a preparation patch for subsequent changes. The patch intends to maintain the code behavior."
> Was the best I could think of.

That's certainly the most important piece of information (i.e., no intended change in behavior), but I think Chris is looking for something along the lines of:
- Commit 1: Exit early in case source endpoint is not local, to simplify the code.
- Commit 2: Move variable declarations closer to the code using them, to clarify their scope.

It does make reviewing a bit easier because we now know what was the intended change in the logic. You had similar descriptions in previous versions of the commit history :-)

File: test/k8sT/manifests/egress-nat-policy.yaml (hunk 23 above)
Comment (qmonnet) [reply test/k8sT/manifests/egress-nat-policy.yaml]: Sound like a good idea to me

File: bpf/lib/nodeport.h [hunk 24]
```diff
@@ -1116,11 +1117,11 @@ static __always_inline bool snat_v4_needed(struct __ctx_buff *ctx, __be32 *addr,
 	 * cluster.
 	 */
 	if (1) {
```
Comment (brb) [inline bpf/lib/nodeport.h]: While we are here - any reason for `if (1)`?

File: bpf/lib/nodeport.h [hunk 25]
```diff
@@ -1176,55 +1177,56 @@ static __always_inline bool snat_v4_needed(struct __ctx_buff *ctx, __be32 *addr,
...
 
 	ep = __lookup_ip4_endpoint(ip4->saddr);
-	if (ep && !(ep->flags & ENDPOINT_F_HOST)) {
-		struct remote_endpoint_info *info;
-		*from_endpoint = true;
+	/* If this is not a local endpoint, or if this is a localhost endpoint,
+	 * no SNAT is needed.
+	 */
+	if (!ep || (ep->flags & ENDPOINT_F_HOST))
+		return false;
```
Comment (brb) [inline bpf/lib/nodeport.h:1164]: Thinking out loud: this branch is very unlikely to happen, as for majority of cases it's going to be from pod or from host traffic. Also, the check against `IPV4_MASQUERADE` above should catch the localhost endpoint case for majority of cases. Maybe it's a good use case for `unlikely()`?

**Review by brb — APPROVED** [review]
Thanks! Also, :+1: for the detailed commit msg. A few non-blocking comments. Also, out of curiosity - have you checked what is a complexity increase after the refactoring in the bpf_host?

File: bpf/lib/nodeport.h (hunk 24 above)
Comment (kkourt) [reply bpf/lib/nodeport.h]: I don't think so, seems to me it's just a way of defining a scope.

File: bpf/lib/nodeport.h (hunk 25 above)
Comment (kkourt) [reply bpf/lib/nodeport.h:1164]: I can add it. I've seen it being used elsewhere in the datapath, but have no idea if it generally helps or not.

(I generally avoid it for x86, since I've never been able to see any perf improvement when using it.)

File: test/k8sT/manifests/egress-nat-policy.yaml (hunk 23 above)
Comment (kkourt) [reply test/k8sT/manifests/egress-nat-policy.yaml]: Thanks, used 192.0.2.13

File: bpf/lib/nodeport.h (hunk 22 above)
Comment (kkourt) [reply bpf/lib/nodeport.h:1204]: added, thanks!

**Comment by kkourt** [comment]
> It does make reviewing a bit easier because we now know what was the intended change in the logic. You had similar descriptions in previous versions of the commit history :-)

Added something close to Paul's suggestions (even though, I had to truncate them). Thanks!

File: bpf/lib/nodeport.h (hunk 25 above)
Comment (pchaigno) [reply bpf/lib/nodeport.h:1164]: I've seen noticeable improvements on DPDK code. Never checked on BPF. Compiler definitely takes it into account since we've since it fix a complexity issue once (just because code was reordered).

**Comment by kkourt** [comment]
In an offline discussion, @pchaigno and @brb pointed out that for the fix to work, `enable-remote-node-identity` should be set in the agent. Added a patch to check this when agent is initialized.

File: bpf/lib/nodeport.h (hunk 25 above)
Comment (brb) [reply bpf/lib/nodeport.h:1164]: Probably @borkmann could comment on this too.

Comment (borkmann) [reply bpf/lib/nodeport.h:1164]: I would leave this case probably as is rather than marking as unlikely() given afaiu this could be hit under multi-dev case.
