### PR TITLE
bgpv1: fix Test_PodIPPoolAdvert flakiness

### LINKED ISSUE #30237: CI: Conformance Runtime - Test_PodIPPoolAdvert failure
## CI failure

Hit on https://github.com/cilium/cilium/pull/30183
Link: https://github.com/cilium/cilium/actions/runs/7480430927/job/20359924251

```
--- FAIL: Test_PodIPPoolAdvert (8.07s)
    --- FAIL: Test_PodIPPoolAdvert/matching_ipv4_pool (0.00s)
        adverts_test.go:430: expected events: [{65001 11.1.1.0 24 false []}]
        adverts_test.go:431: received events: [{65001 10.1.1.0 24 false []}]
        adverts_test.go:432: 
            	Error Trace:	/host/pkg/bgpv1/test/adverts_test.go:432
            	Error:      	elements differ
            	            	
            	            	extra elements in list A:
            	            	([]interface {}) (len=1) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.1.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	            	
            	            	
            	            	extra elements in list B:
            	            	([]interface {}) (len=1) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "10.1.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	            	
            	            	
            	            	listA:
            	            	([]test.routeEvent) (len=1) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.1.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	            	
            	            	
            	            	listB:
            	            	([]test.routeEvent) (len=1) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "10.1.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	Test:       	Test_PodIPPoolAdvert/matching_ipv4_pool
            	Messages:   	matching ipv4 pool
    --- FAIL: Test_PodIPPoolAdvert/update_matching_ipv4_pool (0.00s)
        adverts_test.go:430: expected events: [{65001 11.1.1.0 24 true []} {65001 11.2.1.0 24 false []}]
        adverts_test.go:431: received events: [{65001 10.1.2.0 24 false []} {65001 11.1.1.0 24 false []}]
        adverts_test.go:432: 
            	Error Trace:	/host/pkg/bgpv1/test/adverts_test.go:432
            	Error:      	elements differ
            	            	
            	            	extra elements in list A:
            	            	([]interface {}) (len=2) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.1.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) true,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 },
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.2.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	            	
            	            	
            	            	extra elements in list B:
            	            	([]interface {}) (len=2) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "10.1.2.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 },
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.1.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	            	
            	            	
            	            	listA:
            	            	([]test.routeEvent) (len=2) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.1.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) true,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 },
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.2.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	            	
            	            	
            	            	listB:
            	            	([]test.routeEvent) (len=2) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "10.1.2.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 },
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.1.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	Test:       	Test_PodIPPoolAdvert/update_matching_ipv4_pool
            	Messages:   	update matching ipv4 pool
    --- FAIL: Test_PodIPPoolAdvert/matching_ipv6_pool (0.00s)
        adverts_test.go:430: expected events: [{65001 2001:0:0:1234:5678:: 96 false []} {65001 11.2.1.0 24 true []}]
        adverts_test.go:431: received events: [{65001 10.1.2.0 24 true []} {65001 10.1.1.0 24 true []}]
        adverts_test.go:432: 
            	Error Trace:	/host/pkg/bgpv1/test/adverts_test.go:432
            	Error:      	elements differ
            	            	
            	            	extra elements in list A:
            	            	([]interface {}) (len=2) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=20) "2001:0:0:1234:5678::",
            	            	  prefixLen: (uint8) 96,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 },
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.2.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) true,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	            	
            	            	
            	            	extra elements in list B:
            	            	([]interface {}) (len=2) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "10.1.2.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) true,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 },
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "10.1.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) true,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	            	
            	            	
            	            	listA:
            	            	([]test.routeEvent) (len=2) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=20) "2001:0:0:1234:5678::",
            	            	  prefixLen: (uint8) 96,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 },
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.2.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) true,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	            	
            	            	
            	            	listB:
            	            	([]test.routeEvent) (len=2) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "10.1.2.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) true,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 },
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "10.1.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) true,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	Test:       	Test_PodIPPoolAdvert/matching_ipv6_pool
            	Messages:   	matching ipv6 pool
    --- FAIL: Test_PodIPPoolAdvert/update_matching_ipv6_pool (0.00s)
        adverts_test.go:430: expected events: [{65001 2001:0:0:1234:5678:: 96 true []} {65001 2002:0:0:1234:5678:: 96 false []}]
        adverts_test.go:431: received events: [{65001 11.2.1.0 24 false []} {65001 11.1.1.0 24 true []}]
        adverts_test.go:432: 
            	Error Trace:	/host/pkg/bgpv1/test/adverts_test.go:432
            	Error:      	elements differ
            	            	
            	            	extra elements in list A:
            	            	([]interface {}) (len=2) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=20) "2001:0:0:1234:5678::",
            	            	  prefixLen: (uint8) 96,
            	            	  isWithdrawn: (bool) true,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 },
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=20) "2002:0:0:1234:5678::",
            	            	  prefixLen: (uint8) 96,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	            	
            	            	
            	            	extra elements in list B:
            	            	([]interface {}) (len=2) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.2.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 },
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.1.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) true,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	            	
            	            	
            	            	listA:
            	            	([]test.routeEvent) (len=2) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=20) "2001:0:0:1234:5678::",
            	            	  prefixLen: (uint8) 96,
            	            	  isWithdrawn: (bool) true,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 },
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=20) "2002:0:0:1234:5678::",
            	            	  prefixLen: (uint8) 96,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	            	
            	            	
            	            	listB:
            	            	([]test.routeEvent) (len=2) {
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.2.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) false,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 },
            	            	 (test.routeEvent) {
            	            	  sourceASN: (uint32) 65001,
            	            	  prefix: (string) (len=8) "11.1.1.0",
            	            	  prefixLen: (uint8) 24,
            	            	  isWithdrawn: (bool) true,
            	            	  extraPathAttributes: ([]bgp.PathAttributeInterface) <nil>
            	            	 }
            	            	}
            	Test:       	Test_PodIPPoolAdvert/update_matching_ipv6_pool
            	Messages:   	update matching ipv6 pool
```

### PR DESCRIPTION
**Pull request by rastislavs**
Since the test updates multiple k8s resources in each test step, and each step depends on the previous one, we should be careful about how many k8s resources are we actually changing in each step, to not trigger multiple reconciliations with different results (advertisements) in a single step.

This change ensures we change only one value that affects the advertisement in each test step.

Fixes: #30237

(tested locally with 100 x `Test_PodIPPoolAdvert` runs, which would always fail as in #30237 before this fix)

### CODE REVIEW

File: pkg/bgpv1/test/adverts_test.go [hunk 1]
```diff
@@ -394,16 +449,18 @@ func Test_PodIPPoolAdvert(t *testing.T) {
...
+				switch step.ipPoolOp {
+				case "add":
 					err = tracker.Add(obj)
-				}
-			} else {
-				for _, obj := range poolObjs {
+				case "update":
 					err = tracker.Update(v2alpha1.SchemeGroupVersion.WithResource("ciliumpodippools"), obj, "")
+				case "delete":
+					err = tracker.Delete(v2alpha1.SchemeGroupVersion.WithResource("ciliumpodippools"), "", obj.Name)
```
Comment (harsimran-pabla) [inline pkg/bgpv1/test/adverts_test.go:460]: require.NoError(t, err) should be moved after switch case, line 461. Otherwise, we overwrite the err.

**Review by harsimran-pabla — CHANGES_REQUESTED** [review]
Minor change required, otherwise LGTM.

**Review by harsimran-pabla — APPROVED** [review]
