### PR TITLE
ipsec: Fix packet mark for FWD XFRM policy

### LINKED ISSUE #23090: Cross node connectivity fails with IPsec +  tunneling + endpoint routes
Tried to enable the following configuration in the https://github.com/cilium/cilium/pull/22825:
```
name: '3'
kernel: '5.10-main'
kube-proxy: 'iptables'
kpr: 'disabled'
tunnel: 'vxlan'
encryption: 'ipsec'
endpoint-routes: 'true'
```

Unfortunately, the connectivity test failed with that configuration (https://github.com/cilium/cilium/actions/runs/3909668341/jobs/6686245297):
```
 Deployment        cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
DaemonSet         cilium             Desired: 3, Ready: 3/3, Available: 3/3
Containers:       cilium             Running: 3
                  cilium-operator    Running: 1
Cluster Pods:     3/3 managed by Cilium
Image versions    cilium-operator    quay.io/cilium/operator-generic-ci:647a726040a30492f06e0bc6db612ac87d4c36e1: 1
                  cilium             quay.io/cilium/cilium-ci:647a726040a30492f06e0bc6db612ac87d4c36e1: 3
✨ [kind-kind] Creating namespace cilium-test for connectivity check...
✨ [kind-kind] Deploying echo-same-node service...
✨ [kind-kind] Deploying DNS test server configmap...
✨ [kind-kind] Deploying same-node deployment...
✨ [kind-kind] Deploying client deployment...
✨ [kind-kind] Deploying client2 deployment...
✨ [kind-kind] Deploying echo-other-node service...
✨ [kind-kind] Deploying other-node deployment...
✨ [kind-kind] Deploying host-netns daemonset...
⌛ [kind-kind] Waiting for deployments [client client2 echo-same-node] to become ready...
⌛ [kind-kind] Waiting for deployments [echo-other-node] to become ready...
⌛ [kind-kind] Waiting for CiliumEndpoint for pod cilium-test/client-755fb678bd-llgxm to appear...
⌛ [kind-kind] Waiting for CiliumEndpoint for pod cilium-test/client2-5b97d7bc66-4bnpw to appear...
⌛ [kind-kind] Waiting for pod cilium-test/client-755fb678bd-llgxm to reach DNS server on cilium-test/echo-same-node-64774c64d5-p5xg5 pod...
⌛ [kind-kind] Waiting for pod cilium-test/client2-5b97d7bc66-4bnpw to reach DNS server on cilium-test/echo-same-node-64774c64d5-p5xg5 pod...
⌛ [kind-kind] Waiting for pod cilium-test/client-755fb678bd-llgxm to reach DNS server on cilium-test/echo-other-node-67b74b6685-6l5dc pod...
connectivity test failed: timeout reached waiting lookup for localhost from pod cilium-test/client-755fb678bd-llgxm to server on pod cilium-test/echo-other-node-67b74b6685-6l5dc to succeed (last error: context deadline exceeded)
Error: Process completed with exit code 1.
```

The sysdump: [cilium-sysdump-5.10-main-final.zip](https://github.com/cilium/cilium/files/10413115/cilium-sysdump-5.10-main-final.zip)

### PR DESCRIPTION
**Pull request by pchaigno**
First commit fixes https://github.com/cilium/cilium/issues/23090; second extends the existing test. See commits for details.

### CODE REVIEW

**Review by YutaroHayakawa — APPROVED** [review]
Oh wow, complicated bug... LGTM.

File: pkg/datapath/linux/ipsec/ipsec_linux.go [hunk 1]
```diff
@@ -196,11 +196,11 @@ func _ipSecReplacePolicyInFwd(src, dst *net.IPNet, tmplSrc, tmplDst net.IP, prox
 	policy := ipSecNewPolicy()
 	policy.Dir = dir
 	policy.Dst = dst
-	policy.Mark = &netlink.XfrmMark{
-		Mask: linux_defaults.IPsecMarkMaskIn,
-	}
 	if dir == netlink.XFRM_DIR_IN {
 		policy.Src = src
+		policy.Mark = &netlink.XfrmMark{
```
Comment (sahid) [inline pkg/datapath/linux/ipsec/ipsec_linux.go:201]: I surely don't have the whole knowledge, based on your well descriptive commit message my understanding is that we should not mark packet for `dir == netlink.XFRM_DIR_FWD`. You decided to move the mark under `dir == netlink.XFRM_DIR_IN` which is right (for sure :-)), but should not be more specific with condition like:

```
if dir != netlink.XFRM_DIR_FWD` {
  // We want to mark packet...
  policy.Mark = ...
}
```

Based on the current algorithm I'm worry to see `dir` with something else than `XFRM_DIR_IN` and basically have packet not marked.

**Review by nebril — APPROVED** [review]
ci bits look good

File: pkg/datapath/linux/ipsec/ipsec_linux.go (hunk 1 above)
Comment (pchaigno) [reply pkg/datapath/linux/ipsec/ipsec_linux.go:201]: I don't think it's generally a good idea to make the code more convoluted to better match what the commit description says.

More specifically, in this case, (1) I would be very surprised if we need to support a new direction besides In, Out, and Fwd (it's baked in the kernel and netfilter) and (2) if that ever happened, I would argue that not matching on the mark would likely be a better default.

Comment (sahid) [reply pkg/datapath/linux/ipsec/ipsec_linux.go:201]: Fair enough, thank you Paul. I would have suggested to at least add a comment  but I imagine we could use git blame to understand the reason of this move. ++

**Review by sahid — APPROVED** [review]

**Comment by pchaigno** [comment]
This PR was never actually backported to v1.12. Remarding.
