### PR TITLE
cilium: fix socket termination for v4-in-v6 clients

### LINKED ISSUE #39470: bpf-lb-sock-terminate-pod-connections does not correctly terminate long-lived udp ipv6 connections
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.15.16 and lower than v1.16.0

### What happened?

We have the following setup:

- A server (statsd) that binds an ipv4 udp socket on `0.0.0.0:8126`
- A `SingleStack` service created in k8s for this server
- A client that talks to the service using the v4-mapped-on-v6 address type. I.e. the client creates an `AF_INET6` socket, and then uses the `::ffff:` prefix to talk to the service, e.g. `::ffff:10.2.3.4`.

This all works fine until the statsd server restarts. Once restarted, the client continues to send udp packets to the _old_ statsd pod ip address.

This seems very similar to other issues around socket closure that have been reported, e.g.:

- https://github.com/cilium/cilium/issues/35773
- https://github.com/cilium/cilium/issues/37577

We have the following relevant cilium options set (using cilium version `v1.16.0`):
```
  bpf-lb-sock: "true"
  bpf-lb-sock-hostns-only: "false"
  bpf-lb-sock-terminate-pod-connections: "true"
```

Some interesting things we've observed:
- With `bpf-lb-sock` and `bpf-lb-sock-terminate-pod-connections` set, if the client uses an ipv4 `AF_INET` socket instead, sockets get forcibly closed / terminated as expected.
- If both the server, service, and client use ipv6, they are not closed as expected.

Essentially it seems like the stale-socket-finding-and-destruction business is working correctly for ipv4, but not ipv6.

### How can we reproduce the issue?

1. Bind a `SOCK_DGRAM` `AF_INET` socket in a server.
2. Create a corresponding kubernetes `Service` for this server.
3. In a client, create a `SOCK_DGRAM` `AF_INET6` socket. Configure the address to use a v4-mapped-on-v6 address type. E.g. if the kubernetes service address is `10.2.3.4`, configure the address the client will connect to as `::ffff:10.2.3.4`.
4. Use the `connect() + send()` syscalls to create a long-lived udp socket, and send packets at some interval (e.g. every 10 seconds) from the client to the server. Note: using `sendto()`, i.e. a short-lived socket effectively works around the issue, and does not produce the undesired behavior.
5. Restart the server
6. Notice how the packets from the client are still sent to the old server ip address.

### Cilium Version

`v1.16.0`

### Kernel Version

`Linux 5.4.0-204-generic #224-Ubuntu SMP Thu Dec 5 13:38:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

`v1.30.6`

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by borkmann**
(see commit desc)

Fixes: #39470

(For KPR=true we also need the fix in https://github.com/cilium/cilium/pull/40026 to trigger the reconciler.)

### CODE REVIEW

**Review by youngnick — APPROVED** [review]
LGTM from sig-k8s

**Comment by borkmann** [comment]
(As discussed with Max, given this is a regression and fix for KPR, we need to land it before release.)

**Review by joamaki — APPROVED** [review]
LGTM

File: bpf/bpf_sock.c [hunk 1]
```diff
@@ -154,12 +154,13 @@ static __always_inline int sock4_update_revnat(struct bpf_sock_addr *ctx,
 	return ret;
 }
 
-static __always_inline int sock4_delete_revnat(struct bpf_sock *ctx)
+static __always_inline int sock4_delete_revnat(struct bpf_sock *ctx,
+					       struct bpf_sock *ctx_full)
```
Comment (dylandreimerink) [inline bpf/bpf_sock.c:158]: Nit: this is confusing. When I see `ctx` I expect its a usable context. I would make the first argument `ctx_fake` and the second `ctx`. Hopefully that hints that the first isn't usable as proper context.

Better yet, change to `int sock4_delete_revnat(struct bpf_sock *ctx, __u32 address, __u16 port);` since most of the fake ctx is uninitialized anyway.

**Review by dylandreimerink — APPROVED** [review]

File: bpf/bpf_sock.c (hunk 1 above)
Comment (borkmann) [reply bpf/bpf_sock.c:158]: > Nit: this is confusing. When I see ctx I expect its a usable context. I would make the first argument ctx_fake and the second ctx. Hopefully that hints that the first isn't usable.

The ctx + ctx_full scheme is similarly as with other function signatures, so I didn't want to suddenly reverse the order compared to the others.

> Better yet, change to int sock4_delete_revnat(struct bpf_sock *ctx, __u32 address, __u16 port); since most of the fake ctx is uninitialized anyway.

I can look into it, though then its a bit less in line compared to sock6_delete_revnat, so maybe we need sth similar there too to be consistent.

File: pkg/loadbalancer/reconciler/termination.go [hunk 2]
```diff
@@ -239,13 +239,15 @@ func terminateUDPConnectionsToBackend(p socketTerminationParams, l3n4Addr lb.L3n
...
 	if p.ExtConfig.EnableSocketLBPodConnectionTermination && !p.ExtConfig.BPFSocketLBHostnsOnly {
 		iter, errs := p.NetNSOps.all()
-		for name, ns := range iter {
-			destroy(name, ns)
-		}
 		for err := range errs {
 			p.Log.Debug("Error opening netns, skipping",
 				logfields.Error, err)
 		}
+		if iter != nil {
```
Comment (joamaki) [inline pkg/loadbalancer/reconciler/termination.go:246]: This does not work. We must iterate over `iter` first as otherwise we'll block forever in `for err := range errs`.

Comment (borkmann) [reply pkg/loadbalancer/reconciler/termination.go:246]: (resolved via https://github.com/cilium/cilium/commit/7c29d343352f3cf7d6afca11f2122a6b7607726a)
