### PR TITLE
Test: Validate DNS before trying to connect on curl

### LINKED ISSUE #3462: CI failure: guestbook cannot netcat to redis in spite of policy
Jenkins failures: 
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/515/

[K8sValidatedPolicyTestGuestBookExamplescheckspolicyexample.zip](https://github.com/cilium/cilium/files/1868662/K8sValidatedPolicyTestGuestBookExamplescheckspolicyexample.zip)

### LINKED ISSUE #3675: CI: Star Wars Demo failed
Build link: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/603/

Failure output: 
```19:37:03 • Failure [350.011 seconds]
19:37:03 K8sValidatedDemosTest
19:37:03 /home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:280
19:37:03   Tests Star Wars Demo [It]
19:37:03   /home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:312
19:37:03 
19:37:03   able to access deathstar.default.svc.cluster.local/v1/exhaust-port when policy disallows it; 000command terminated with exit code 7
19:37:03   command terminated with exit code 7
19:37:03   
19:37:03   Expected
19:37:03       <string>: 000command terminated with exit code 7
19:37:03       command terminated with exit code 7
19:37:03       
19:37:03   to contain substring
19:37:03       <string>: 403
19:37:03 
19:37:03   /home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/k8sT/demos.go:169
19:37:03 ------------------------------
```

Logs from right when test failed:
```
19:35:36 time="2018-04-11T19:35:36Z" level=debug msg="running command: kubectl exec -n kube-system cilium-wmtpx -- cilium endpoint list -o json"
19:35:37 time="2018-04-11T19:35:37Z" level=info msg="Waiting for cilium endpoints" invalid=8 pod=cilium-wmtpx testName=K8sValidatedDemosTest valid=4
19:35:41 time="2018-04-11T19:35:41Z" level=debug msg="running command: kubectl exec -n kube-system cilium-wmtpx -- cilium endpoint list -o json"
19:35:42 STEP: Showing how alliance cannot access deathstar.default.svc.cluster.local/v1/exhaust-port without force header in API request after importing L7 Policy
19:35:42 time="2018-04-11T19:35:41Z" level=debug msg="running command: kubectl exec -n default xwing-77cb49f96-5v8sz -- curl -s --output /dev/stderr -w '%!{(MISSING)http_code}' --connect-timeout 5 -X PUT http://deathstar.default.svc.cluster.local/v1/exhaust-port"
```

Logs: 
[test_results_master_603.tar.zip](https://github.com/cilium/cilium/files/1900648/test_results_master_603.tar.zip)

### LINKED ISSUE #3676: CI: CNP Specs test failed (unable to connect to ratings)
Build link: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/604
Failure output:
```
20:24:47 • Failure [289.889 seconds]
20:24:47 K8sValidatedServicesTest
20:24:47 /home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:280
20:24:47   CNP Specs Test [It]
20:24:47   /home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:312
20:24:47 
20:24:47   Unable to connect from reviews-v1-2690276606-94zt1 to ratings:9080/health: --2018-04-11 20:24:00--  http://ratings:9080/health
20:24:47   Resolving ratings (ratings)... 10.109.154.237
20:24:47   Connecting to ratings (ratings)|10.109.154.237|:9080... connected.
20:24:47   HTTP request sent, awaiting response... 404 Not Found
20:24:47   2018-04-11 20:24:00 ERROR 404: Not Found.
20:24:47   
20:24:47   --2018-04-11 20:24:00--  http://ratings:9080/health
20:24:47   Resolving ratings (ratings)... 10.109.154.237
20:24:47   Connecting to ratings (ratings)|10.109.154.237|:9080... connected.
20:24:47   HTTP request sent, awaiting response... 404 Not Found
20:24:47   2018-04-11 20:24:00 ERROR 404: Not Found.
20:24:47   
20:24:47   
20:24:47   Expected
20:24:47       <bool>: false
20:24:47   to be true
20:24:47 
20:24:47   /home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/k8sT/Services.go:323
```

Logs from when test failed:
```
20:24:02 STEP: After policy import
20:24:02 STEP: Checking that reviews-v1-2690276606-94zt1 can connect to ratings:9080/health
20:24:02 time="2018-04-11T20:24:00Z" level=debug msg="running command: kubectl exec -t reviews-v1-2690276606-94zt1 wget -- --tries=2 --connect-timeout 10 ratings:9080/health"
```

Possibly related to: #3470 

Logs: 
[test_results_master_604.tar.zip](https://github.com/cilium/cilium/files/1900679/test_results_master_604.tar.zip)

### LINKED ISSUE #3692: CI: K8s 1.10 upgrade test failed in datapath check
Build link: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/2062/

Relevant output:
```
14:27:28 • Failure [659.169 seconds]
14:27:28 K8sValidatedUpdates
14:27:28 /home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:280
14:27:28   Updating Cilium stable to master [It]
14:27:28   /home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:312
14:27:28 
14:27:28   Cannot curl app1-service
14:27:28   Expected
14:27:28       <bool>: false
14:27:28   to be true
14:27:28 
14:27:28   /home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/k8sT/Updates.go:120
```

Console output from when build failed: 
```
14:26:13 time="2018-04-12T14:26:12Z" level=debug msg="running command: kubectl exec -n kube-system cilium-598gd -- cilium endpoint list -o json"
14:26:13 time="2018-04-12T14:26:13Z" level=info msg="GetAppPods: pod=\"app1-5cbb58b8c6-7bgzt\" assigned to \"app1\""
14:26:13 time="2018-04-12T14:26:13Z" level=info msg="GetAppPods: pod=\"app2-744d8b5f79-wqsqj\" assigned to \"app2\""
14:26:13 time="2018-04-12T14:26:13Z" level=info msg="GetAppPods: pod=\"app3-746666c789-qpv64\" assigned to \"app3\""
14:26:13 time="2018-04-12T14:26:13Z" level=debug msg="running command: kubectl exec -n default app2-744d8b5f79-wqsqj -- curl -s --fail --connect-timeout 5 --max-time 5 http://app1-service/public"
```

Logs: 
[test_results_Ginkgo-CI-Tests-Pipeline_2062.tar.zip](https://github.com/cilium/cilium/files/1903879/test_results_Ginkgo-CI-Tests-Pipeline_2062.tar.zip)

### LINKED ISSUE #3694: CI: add function which waits for DNS to resolve host names of services
Add a function implement some waiting function which waits until the host names for services resolve. Also revert the changes in #3695 so that tests are querying host names again instead of service IPs.

### LINKED ISSUE #3695: CI: change failing tests to query service IPs instead of host names
There have been multiple issues with tests failing to resolve host names for services:

* https://github.com/cilium/cilium/issues/3675
* https://github.com/cilium/cilium/issues/3462
* https://github.com/cilium/cilium/issues/3676

In the short term, change these tests to query the service IPs directly instead of the host names.

A long term fix is to implement some waiting function which waits until the host names for services resolve. This work is tracked by #3694.

### LINKED ISSUE #3710: CI : Star Wars demo failed
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/100/execution/node/43/log/

```
00:17:49 K8sValidatedDemosTest
00:17:49 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:280
00:17:49   Tests Star Wars Demo [It]
00:17:49   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:312
00:17:49 
00:17:49   unable to curl deathstar.default.svc.cluster.local/v1: 000command terminated with exit code 6
00:17:49   command terminated with exit code 6
00:17:49   
00:17:49   Expected
00:17:49       <string>: 000command terminated with exit code 6
00:17:49       command terminated with exit code 6
00:17:49       
00:17:49   to contain substring
00:17:49       <string>: 200
```

### LINKED ISSUE #3712: CI: K8sValidatedUpdates Updating Cilium stable to master fails on 1.7 k8s on master
Job link: https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/623/
Stacktrace:
```
/home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:312
Cannot curl app1-service
Expected
    <bool>: false
to be true
/home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/k8sT/Updates.go:120
```

### PR DESCRIPTION
**Pull request by eloycoto**
This commit intruduced a new Kubectl method that make sure that the DNS
exits before pods try to connect to other pod using DNS.

On the other hand, changed all services names to use the full FQDN, some
containers didn't use the search directive commands [0] and the name
resolution didn't work as expected:

Example trace:
```
U +0.477121 10.10.0.77:47324 -> 10.10.0.18:53
~''''''''''''deathstar'default'''''
U +0.000141 10.10.0.18:19419 -> 8.8.8.8:53
'''''''''''''deathstar'default'''''
U +0.000320 10.10.0.18:19419 -> 8.8.4.4:53
'''''''''''''deathstar'default'''''
U +0.000318 10.10.0.77:47324 -> 10.10.0.18:53
'''''''''''''deathstar'default'''''
U +0.000070 10.10.0.18:40244 -> 8.8.8.8:53
'''''''''''''deathstar'default'''''
U +0.064932 8.8.4.4:53 -> 10.10.0.18:19419
'''''''''''''deathstar'default''''''''''''Q{'@'a'root-servers'net''nstld'verisign-grs'com'xH'''''''''''':'''Q'
```

[0] https://github.com/gliderlabs/docker-alpine/blob/master/docs/caveats.commands#dns

Fix #3712
Fix #3710 
Fix #3675
Fix #3462
Fix #3676
Fix #3694
Fix #3695
Fix #3692

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

File: test/helpers/kubectl.go [hunk 1]
```diff
@@ -463,6 +463,41 @@ func (kub *Kubectl) WaitKubeDNS() error {
...
+	svcSuffix := "svc.cluster.local"
+	logger := kub.logger.WithField("dnsName", name)
+
+	if !strings.HasSuffix(name, svcSuffix) {
+		name = fmt.Sprintf("%s.%s", name, svcSuffix)
+	}
+	// https://bugs.launchpad.net/ubuntu/+source/bind9/+bug/854705
+	digCMD := "dig +short %s @%s | grep -v -e '^$'"
+
+	podsIPs, err := kub.GetPodsIPs(KubeSystemNamespace, "k8s-app=kube-dns")
```
Comment (rlenglet) [inline test/helpers/kubectl.go:480]: I thought pods were using the kube-dns service cluster IP, and not the kube-dns pod IPs?

**Review by rlenglet — APPROVED** [review]

File: test/helpers/kubectl.go (hunk 1 above)
Comment (eloycoto) [reply test/helpers/kubectl.go:480]: Yes, but we executed the dig command from the base host. The main reason is because cilium image does not have `host`, `nslookup` or `dig` installed. So we test from base host to the kubedns host to validate that it's ready.

Comment (rlenglet) [reply test/helpers/kubectl.go:480]: Ok.

Comment (rlenglet) [reply test/helpers/kubectl.go:480]: Ok.

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
Marking as needing a backport since this has been the root cause of many CI failures.
