### PR TITLE
datapath: Fix update to NodeAddress table and prioritize Node IP

### LINKED ISSUE #33234: NodeAddress controller can drop addresses on table update
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This issue was discovered on Talos clusters with the [Virtual IP](https://www.talos.dev/v1.7/talos-guides/network/vip/) feature enabled. Each control-plane node can be assigned the VIP address for high-availability access to the cluster API.
At any time we expect one node to have two IPs on it's main interface. Here the VIP is `10.0.0.10` and it is affected to node `k8s-xyz-cp-1`:
```
❯ talosctl get members
NODE        NAMESPACE   TYPE     ID                   VERSION   HOSTNAME             MACHINE TYPE   OS               ADDRESSES
10.0.0.11   cluster     Member   k8s-xyz-cp-1         2         k8s-xyz-cp-1         controlplane   Talos (v1.7.4)   ["10.0.0.10","10.0.0.11"]
10.0.0.11   cluster     Member   k8s-xyz-cp-2         2         k8s-xyz-cp-2         controlplane   Talos (v1.7.4)   ["10.0.0.12"]
10.0.0.11   cluster     Member   k8s-xyz-cp-3         3         k8s-xyz-cp-3         controlplane   Talos (v1.7.4)   ["10.0.0.13"]
10.0.0.11   cluster     Member   k8s-xyz-worker-a-1   1         k8s-xyz-worker-a-1   worker         Talos (v1.7.4)   ["10.0.0.21"]
10.0.0.11   cluster     Member   k8s-xyz-worker-b-1   1         k8s-xyz-worker-b-1   worker         Talos (v1.7.4)   ["10.0.0.22"]
10.0.0.11   cluster     Member   k8s-xyz-worker-c-1   1         k8s-xyz-worker-c-1   worker         Talos (v1.7.4)   ["10.0.0.23"]
```
Rebooting this node would reassign the address to an other node, causing the NodeAddress controller to process an update.

The problem can be found in the [`update` function of `nodeAddressController`](https://github.com/cilium/cilium/blob/97f4e25b9093ab19aadd2a60f4ee73c5d4e80f22/pkg/datapath/tables/node_address.go#L355), more specifically this section:
```go
	// Insert new addresses that did not exist.
	for addr := range new {
		if !existing.Has(addr) {
			updated = true
			n.NodeAddresses.Insert(txn, addr)
		}
	}

	// Remove addresses that were not part of the new set.
	for addr := range existing {
		// Ensure full device name match. 'device' may be a prefix of DeviceName, and we don't want
		// to delete node addresses of `cilium_host` because they are not on `cilium`.
		if prefixLen != len(addr.DeviceName) {
			continue
		}

		if !new.Has(addr) {
			updated = true
			n.NodeAddresses.Delete(txn, addr)
		}
	}
```
Let's take for example a node initialy having one address `10.0.0.11`. This `NodeAddress` will have `NodePort` and `Primary` to True as there was a single address.
Then when the  VIP `10.0.0.10` is added to the node, `getAddressesFromDevice` is likely to select this new address as primary and NodePort. Subsequently, a bug is triggered in the `update` function. In the first loop `10.0.0.11` will be re-inserted because it doesn't exist in the table with the same field values. Database will update the existing entry. Then in the second loop, because we don't check the live table but `existing`, the test is true for old field values and the freshly updated entry is deleted.

This bug is very noticiable with the Service LoadBalancer for hostNetwork Pods, as the Service endpoint for the Node bearing the VIP will be unreachable.
Restarting cilium-agent on the node will fix the issue as the bug cannot trigger when the table is empty.

I'm unsure how to fix this except by querying the table again before the deletion loop.
Perhaps there's a smarter approach to this?

### Cilium Version

Client: 1.15.6 a09e05e6b6 2024-06-08T21:31:01Z go version go1.21.11 linux/amd64
Daemon: 1.15.6 a09e05e6b6 2024-06-08T21:31:01Z go version go1.21.11 linux/amd64

### Kernel Version

Linux k8s-xyz-cp-2 6.6.32-talos #1 SMP Tue May 28 13:25:34 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.1

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by joamaki**
When new node addresses were added after Cilium had started the update to the internal table of node addresses accidentally removed existing addresses due to wrong kind of comparison operation.

As part of fixing this issue a similar type of problem was found with update to the fallback addresses (used as backup when selecting BPF masquerading address). This commit also fixes this issue.

This only impacts users running v1.15 with the runtime device detection enabled.

The second commit adds in the prioritization of the K8s Node IP when selecting the NodeAddress. This was a semantic
difference between the old and new code and should have been retained.

Fixes: #33234 

```release-note
Fix an issue in updates to node addresses which may have caused missing NodePort frontend IP addresses. May have affected NodePort/LoadBalancer services for users running with runtime device detection enabled when node's IP addresses were changed after Cilium had started.
Node IP as defined in the Kubernetes Node is now preferred when selecting the NodePort frontend IPs.
```

### CODE REVIEW

File: pkg/datapath/tables/node_address.go [hunk 1]
```diff
@@ -436,12 +476,13 @@ func (n *nodeAddressController) getAddressesFromDevice(dev *Device) sets.Set[Nod
 		index := len(addrs)
 
 		isPublic := ip.IsPublicAddr(addr.Addr.AsSlice())
-		primary := false
 		if addr.Addr.Is4() {
-			if !ipv4Found {
-				ipv4Found = true
-				primary = true
+			if addr.Addr.Unmap() == n.k8sIPv4.Unmap() {
```
Comment (dylandreimerink) [inline pkg/datapath/tables/node_address.go:478]: The `Unmap` seems unnecessary if both IPs are confirmed to be IPv4 addresses

**Review by dylandreimerink — APPROVED** [review]
Just a small nit

File: pkg/datapath/tables/node_address.go (hunk 1 above)
Comment (joamaki) [reply pkg/datapath/tables/node_address.go:478]: What would you propose doing instead? If I remove Unmap the tests fail as one of these ends up being an IPv4-mapped IPv6 address (either MustParseAddr or AddrFromSlice causes it, probably the latter...).

EDIT: could use our `ip.AddrFromIP` instead, but perhaps safer to compare with Unmap'd addresses still?

Comment (dylandreimerink) [reply pkg/datapath/tables/node_address.go:478]: > If I remove Unmap the tests fail as one of these ends up being an IPv4-mapped IPv6 address

That is odd, the branch is guarded by an `if addr.Addr.Is4() {` check so `addr.Addr` should be an IPv4 for sure. Which means that we allow IPv4-mapped-IPv6 addresses as valid value for `n.k8sIPv4`.

If we truly support that then there is nothing wrong with the code. I just didn't expected that

**Review by brb — CHANGES_REQUESTED** [review]
As discussed offline, let's split the first commit into two, and then update the commit msg to include more info on the first fix.

**Comment by joamaki** [comment]
> As discussed offline, let's split the first commit into two, and then update the commit msg to include more info on the first fix.

Done!

File: pkg/datapath/tables/node_address.go [hunk 2]
```diff
@@ -265,24 +272,43 @@ func (n *nodeAddressController) register() {
...
+	localNodeChanges := stream.ToChannel(ctx, n.LocalNode)
+	n.updateK8sNodeIPs(<-localNodeChanges)
+
 	limiter := rate.NewLimiter(nodeAddressControllerMinInterval, 1)
 	for {
 		txn := n.DB.WriteTxn(n.NodeAddresses)
 		for change, _, ok := n.deviceChanges.Next(); ok; change, _, ok = n.deviceChanges.Next() {
 			dev := change.Object
 
-			// Note: prefix match! existing may contain node addresses from devices with names
```
Comment (joamaki) [inline pkg/datapath/tables/node_address.go:277]: Note to self/backporter: Verify whether this code is needed in v1.15 or whether this workaround is still needed.

**Review by brb — APPROVED** [review]
Thanks!
