### PR TITLE
Fix bug where cilium-health reports connectivity failures to stale IPs

### LINKED ISSUE #11532: Inconsistent view of nodes across agents
## Bug report

- Cilium version (run `cilium version`)
```
Client: 1.7.3 952090308 2020-04-29T15:29:53-07:00 go version go1.13.10 linux/amd64
Daemon: 1.7.3 952090308 2020-04-29T15:29:53-07:00 go version go1.13.10 linux/amd64
```

- Kernel version (run `uname -a`)
```
Linux ip-10-101-8-142 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 GNU/Linux
```

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Upload a system dump

will be passed to a maintainer privately

**How to reproduce the issue**

Don't know the exact steps, but probably what lead to this was a constantly rolling cluster – i.e., nodes were continuously being replaced by `kops rolling-update` (we were running a resiliency test) over the course of 7 days. After a couple of days I noticed that one agent was reporting `cilium_unreachable_nodes=1`. After investigating, I found that one agent was still listing a node that's been terminated over 9 hours ago in `cilium-health status` and in the `node list`:

```
root@ip-10-101-12-162:~# cilium-health status | grep -A4 'ip-10-101-20-58.ec2.internal'
  ip-10-101-20-58.ec2.internal:
    Endpoint connectivity to 100.67.34.21:
      ICMP to stack:   Connection timed out
      HTTP to agent:   Get http://100.67.34.21:4240/hello: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  ip-10-101-21-110.ec2.internal:
root@ip-10-101-12-162:~# cilium node list | grep '58'
ip-10-101-22-225.ec2.internal   10.101.22.225   100.67.58.0/24
```

### PR DESCRIPTION
**Pull request by kkourt**
NodeAdd and NodeUpdate update the node state for clients so that they
can return the changes when client requests so. If a node was added and
then updated, its old and new version would be on the added list and its
old on the removed list. Instead, we can just update the node on the
added list.

Note that the setNodes() function on pkg/health/server/prober.go first
deletes the removed nodes and then adds the new ones, which means that
the old version of the node would be added and remain as stale on the
health server.

This was found during investigation of issues with inconsistent health
reports when nodes are added/removed from the cluster (e.g., #11532),
and it seems to fix inconsistencies observed a small-scale test I did to
reproduce the issue.

Fixes #11532.

### CODE REVIEW

File: daemon/cmd/status.go [hunk 1]
```diff
@@ -388,8 +388,20 @@ func (c *clusterNodesClient) NodeAdd(newNode nodeTypes.Node) error {
 
 func (c *clusterNodesClient) NodeUpdate(oldNode, newNode nodeTypes.Node) error {
 	c.Lock()
-	c.NodesAdded = append(c.NodesAdded, newNode.GetModel())
-	c.NodesRemoved = append(c.NodesRemoved, oldNode.GetModel())
+	// If the node is on the added list, just update it
+	found := -1
+	for i, added := range c.NodesAdded {
+		if added.Name == newNode.Fullname() {
+			found = i
```
Comment (pchaigno) [inline daemon/cmd/status.go]: Maybe `found` could be `newNodeIdx`? ~~Also possible to break here.~~ Saw second commit, could you squash them?

File: daemon/cmd/status.go [hunk 2]
```diff
@@ -388,8 +388,21 @@ func (c *clusterNodesClient) NodeAdd(newNode nodeTypes.Node) error {
...
+			break
+		}
+	}
+	if found != -1 {
+		c.NodesAdded[found] = newNode.GetModel()
```
Comment (pchaigno) [inline daemon/cmd/status.go]: Couldn't this be moved to inside the loop and then the `found` variable wouldn't be needed?

File: daemon/cmd/status.go (hunk 1 above)
Comment (kkourt) [reply daemon/cmd/status.go]: I thought it would be better to separate the concerns, but yes I can squash them into one commit.

File: daemon/cmd/status.go (hunk 2 above)
Comment (kkourt) [reply daemon/cmd/status.go]: Since this i mostly a matter of style, I tried to follow the style of the function below (delete), but yes, I can move it inside the loop.

File: daemon/cmd/status.go (hunk 1 above)
Comment (pchaigno) [reply daemon/cmd/status.go]: Ah I see, I had missed that you also changed `NodeDelete`'s implementation. Either way LGTM then!

**Comment by christarazi** [comment]
test-me-please

**Review by christarazi — APPROVED** [review]

**Review by fristonio — APPROVED** [review]

File: daemon/cmd/status.go [hunk 3]
```diff
@@ -388,9 +388,19 @@ func (c *clusterNodesClient) NodeAdd(newNode nodeTypes.Node) error {
 
 func (c *clusterNodesClient) NodeUpdate(oldNode, newNode nodeTypes.Node) error {
 	c.Lock()
+	defer c.Unlock()
+
+	// If the node is on the added list, just update it
+	for i, added := range c.NodesAdded {
+		if added.Name == newNode.Fullname() {
+			c.NodesAdded[i] = newNode.GetModel()
+			return nil
```
Comment (joestringer) [inline daemon/cmd/status.go:397]: How do we remove IPs that were part of the old model in this case?

Broadly we track two IPs per node in this model: The node's IP for health-checking the node, then the health IP for the simulated health endpoint. Consider node A that is not changing, If a node B's Cilium agent restarts and triggers a node update across the cluster to update the cilium-health endpoint IP corresponding to this node, then I would expect that node A should receive that update, then pass the old IP and new IP through to the node A cilium-health agent so that it can follow the remove-then-add logic to ensure the old address is cleaned up:

https://github.com/cilium/cilium/blob/7457ce6299dc64f4b6a810fef8c8dd9f2bc4f4fa/pkg/health/server/prober.go#L189-L197

File: daemon/cmd/status.go [hunk 4]
```diff
@@ -388,9 +388,19 @@ func (c *clusterNodesClient) NodeAdd(newNode nodeTypes.Node) error {
...
+		}
+	}
+
+	// otherwise, add the new node and remove the old one
```
Comment (joestringer) [inline daemon/cmd/status.go:401]: > Note that the setNodes() function on pkg/health/server/prober.go first
deletes the removed nodes and then adds the new ones, which means that
the old version of the node would be added and remain as stale on the
health server.

Can you elaborate on the timeline a bit more here? Do you mean that you think we are missing node delete events for some portion of the cluster?

**Review by joestringer — CHANGES_REQUESTED** [review]
Thanks for digging into this! I have some questions below, even if this may address some use cases I don't understand how we don't cause regressions in other areas with the current version. Would be good to get a clearer outline of the exact set of steps we believe are happening and how this addresses that case, and make sure we're not missing *other* cases in the fix for this case.

I think this also highlights that if we can come up with some better ways to automate testing in this area, we would benefit greatly.

File: daemon/cmd/status.go (hunk 3 above)
Comment (joestringer) [reply daemon/cmd/status.go:397]: At a glance it looks like with this change we will continue to ping the original health IP from node B forever (until node A gets restarted, but then that will cause the same problem again for other nodes in the cluster).

Comment (joestringer) [reply daemon/cmd/status.go:397]: Ah, I think one piece I was missing in initial review is that in this particular case, the node being updated was not yet sent through to the health client yet at all, so there's nothing to remove.

The comment `If the node is on the added list, just update it` explains *what*, but not *why*. Studying `NodeDelete()` shows that this kind of code is specifically for handling the collection of updates for the next bulk node update to the cilium-health server, where presence in the `c.NodesAdded` slice implies changes that have not yet been propagated to the nodes client (ie cilium-health server).

**Review by pchaigno — APPROVED** [review]

File: daemon/cmd/status.go (hunk 4 above)
Comment (joestringer) [reply daemon/cmd/status.go:401]: Just re-read through a few times and I get it now :-)

* Add (node-v1) -> v1 in c.Added
* Update (node-v2) -> v1 is still in c.Added because of the first step; we now add v1 to c.Removed and *also* add v2 to c.Added. So even though the health server removes the old version, it then readds it because the update didn't handle the update correctly.

**Review by joestringer — APPROVED** [review]

File: daemon/cmd/status.go (hunk 4 above)
Comment (kkourt) [reply daemon/cmd/status.go:401]: As far as I understand, `c.NodesAdded` and `c.NodesDeleted` maintain the nodes added and deleted from the last request of the client. Whenever the client requests the changes, the two structures above are sent, then cleared, and subsequently updated with new changes.

Let's say that the following things happen before client has a chance to make a request:
 - Node A is added (A0)
 - Node A is updated (A1)

With the old code this will result in:

- NodeAdd(A0) -> NodesAdded: [A0], NodesDeleted: []
- NodeUpdate(A0, A1) -> NodesAdded: [A0, A1], NodesDeleted: [A0]

The code https://github.com/cilium/cilium/blob/326487aa506df7b384603cd403b2b2504fec4312/pkg/health/server/prober.go#L185 that adds them to the health server roughly does:

```
for node in NodesDeleted:
     - remove node
for node in NodesAdded:
     - add node
```

Which means that A0 from the example above will be added to the nodes.

**Comment by kkourt** [comment]
> Just re-read through a few times and I get it now :-)

I also wrote a more detailed explanation, hope it helps.

**Comment by pchaigno** [comment]
retest-4.9

**Comment by joestringer** [comment]
Filed #12993 to follow up on 4.9 failures, seems like an unrelated issue.

**Comment by joestringer** [comment]
K8s-1.12-Kernel-netnext CI failure `Suite-k8s-1.12.K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with direct routing and DSR` is a known flaky test, can retry but I'm guessing it'll pass

**Comment by joestringer** [comment]
retest-net-next

**Comment by joestringer** [comment]
4.9 kernel CI failures got worse this time, Up from 22 failures to 71 :thinking: :
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-4.9/304/testReport/

**Comment by joestringer** [comment]
Observed that this is not the only PR to be affected by the 4.9 issues so do not plan to have that block this PR. They also look completely unrelated to the code changes here.
