### PR TITLE
Silence spurious clustermesh-related warnings

### LINKED ISSUE #35865: Warnings on clustermesh startup
On clustermesh startup, we're getting a bunch of warnings as follows. Those probably shouldn't be warnings (or should be happening) given they're just signaling transitory startup issues while everything settles down.
```
msg="Unable to get remote cluster configuration" clusterName=c1 error="failed to retrieve cluster configuration: not found" hint="If KVStoreMesh is enabled, check whether it is connected to the target cluster. Additionally, ensure that the cluster name is correct."
msg="Unable to list keys before starting watcher" config=/var/lib/cilium/clustermesh/c1 endpoints="[https://clustermesh-apiserver.kube-system.svc:2379/]" error="context canceled" prefix=cilium/.heartbeat
msg="Error observed on etcd connection, reconnecting etcd" clusterName=cluster2-with-long-name-01234567 error="etcd cluster ID has changed: expected 11231715032166824766, got 10786513292270824672"
msg="Unable to list keys before starting watcher" config=/var/lib/cilium/clustermesh/cluster2-with-long-name-01234567 endpoints="[https://cluster2-with-long-name-01234567.mesh.cilium.io:32380/]" error="etcdserver: permission denied" prefix=cilium/.heartbeat
```
From https://github.com/cilium/cilium/actions/runs/11661644313.

cc @giorio94

### PR DESCRIPTION
**Pull request by giorio94**
Please refer to the individual commits for additional details.

Fixes: https://github.com/cilium/cilium/issues/35865
Marked for backport to v1.16 to prevent issues on downgrade when warning logs start being flagged in CI.

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Review by marseel — APPROVED** [review]

File: pkg/clustermesh/common/remote_cluster.go [hunk 1]
```diff
@@ -158,7 +158,12 @@ func (rc *remoteCluster) restartRemoteConnection() {
 					if backend != nil {
 						backend.Close()
 					}
-					rc.logger.WithError(err).Warning("Unable to establish etcd connection to remote cluster")
```
Comment (pchaigno) [inline pkg/clustermesh/common/remote_cluster.go:161]: @giorio94 I see you did not backport this change to v1.16. Was that intentional? I'm seeing it on downgrades to v1.16: https://github.com/cilium/cilium/actions/runs/11935307422/job/33266363458. Should I just allowlist it until v1.17 is out?

Comment (giorio94) [reply pkg/clustermesh/common/remote_cluster.go:161]: Thanks for noticing. It seems I mistakenly linked a different backport to this one, and marked this one as completed (rather than the other one). Marking again for backport, so that it gets included in the next round.

Comment (pchaigno) [reply pkg/clustermesh/common/remote_cluster.go:161]: Aah, that's why the commits looked so different :laughing:
