### PR TITLE
Fix API breakage for host vs world behaviour in Cilium 1.1 release candidates

### LINKED ISSUE #4297: Document / resolve host => world identity change for NodePort
The commit #3988 has introducing a behavioral change because Cilium can now properly differentiate between host and world for traffic that is coming in via NodePort even if the traffic is being SNATed. There are two scenarios where host to endpoint is allowed:

- Manual policy that allows from host
- Kubernetes mode where host to pod is always allowed

In either of the above scenarios, traffic via NodePort was automatically allowed if the traffic was SNATed Cilium 1.1 as-is would no longer allow such traffic. This is a API breakage.

**Proposal:**
- [x] Introduce flag `--k8s-legacy-host-allows-world[=true]` which defaults to `true`.
  - [x] The flag is only effective in Kubernetes mode and continues to allow world when host is allowed.
- [x] Add the flag to the DaemonSet file and set it via an env variable that is defined in the ConfigMap.
- [x] In the ConfigMap, disable the flag by default. This leads to the following backwards compatible behavior:
   - Existing users will not upgrade the ConfigMap and thus will continue to see the existing behavior.
   - New users will see the new behavior where host and world are properly separate for NodePort.
- [x] Update the ginkgo upgrade tests to install stable Cilium without the new parameter
- [x] Document this in the upgrade instructions and make sure existing users that upgrade know how to opt into the new behavior.

### LINKED ISSUE #4345: Add option to preserve behavior that host allows world

### PR DESCRIPTION
**Pull request by joestringer**
This PR fixes the API breakage caused by #3988 by retaining existing behaviour for users upgrading from an earlier release, while defaulting new users to the new behaviour. It also documents the behaviour in the upgrade notes section. For more information, see #4297.

Related: #3988
Fixes: #4297 
Fixes: #4345

Todo:
* [x] Add link for `https://cilium.link/host-vs-world`

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4360)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-docs-please

File: daemon/daemon.go [hunk 1]
```diff
@@ -1073,6 +1073,15 @@ func NewDaemon() (*Daemon, error) {
 			log.Info("k8s mode: Allowing localhost to reach local endpoints")
```
Comment (ianvernon) [inline daemon/daemon.go:1074]: Typo in commit message:

"In either of the above scenarios, traffic via NodePort was automatically
allowed if the traffic was SNATed Cilium" --> "In either of the above scenarios, traffic via NodePort was automatically allowed if the traffic was SNATed. Cilium..."

**Review by ianvernon — APPROVED** [review]
Great work!!

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Docs build passed last time.

File: daemon/daemon.go (hunk 1 above)
Comment (joestringer) [reply daemon/daemon.go:1074]: Fixed.

File: examples/kubernetes/templates/v1/cilium-ds.yaml.sed [hunk 2]
```diff
@@ -57,6 +57,7 @@ spec:
         args:
           - "--debug=$(CILIUM_DEBUG)"
           - "-t=vxlan"
+          - "--k8s-legacy-host-allows-world=$(CILIUM_LEGACY_HOST_ALLOWS_WORLD)"
```
Comment (aanm) [inline examples/kubernetes/templates/v1/cilium-ds.yaml.sed]: You can remove this option configure viper to use the value from the environment variable of `CILIUM_LEGACY_HOST_ALLOWS_WORLD`

**Review by aanm — DISMISSED** [review]

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
Failed inside jsonnet:

```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:330
Cilium cannot be installed
Expected
    <*errors.errorString | 0xc4204639f0>: {
        s: "cmd: kubectl apply -f  /home/vagrant/go/src/github.com/cilium/cilium/test/9acb0442_cilium_ds.jsonnet\nerror: no objects passed to apply\n",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Services.go:54
```

`test-output.log` seems to show a healthy YAML.

**Comment by joestringer** [comment]
Tried locally, didn't hit the jsonnet issue, so will retry to see if it's a flake.

**Comment by joestringer** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]
