### PR TITLE
fix pod-to-pod MTU drop when both in+egress proxy and IPSec enabled

### LINKED ISSUE #33168: Pod to pod packets via egress + ingress proxy are MTU dropped when IPsec is enabled
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Steps:

1. Kind install cilium

```
export IMAGE=kindest/node:v1.29.4@sha256:3abb816a5b1061fb15c6e9e60856ec40d56b7b52bcea5f5f1350bc6e2320b6f8
     ./contrib/scripts/kind.sh --xdp --secondary-network "" 3 "" "" none dual 0.0.0.0 6443
 kubectl patch node kind-worker3 --type=json -p='[{"op":"add","path":"/metadata/labels/cilium.io~1no-schedule","value":"true"}]'

  if [[ "gcm(aes)" == "gcm(aes)" ]]; then
    key="rfc4106(gcm(aes)) $(dd if=/dev/urandom count=20 bs=1 2> /dev/null | xxd -p -c 64) 128"
  elif [[ "gcm(aes)" == "cbc(aes)" ]]; then
    key="hmac(sha256) $(dd if=/dev/urandom count=32 bs=1 2> /dev/null| xxd -p -c 64) cbc(aes) $(dd if=/dev/urandom count=32 bs=1 2> /dev/null| xxd -p -c 64)"
  else
    echo "Invalid key type"; exit 1
  fi
  kubectl create -n kube-system secret generic cilium-ipsec-keys \
    --from-literal=keys="3+ ${key}"
./cilium-cli install --wait     --chart-directory=./install/kubernetes/cilium     --helm-set=debug.enabled=true     --helm-set=debug.verbose=envoy     --helm-set=hubble.eventBufferCapacity=65535     --helm-set=bpf.monitorAggregation=none     --helm-set=cluster.name=default     --helm-set=authentication.mutual.spire.enabled=false     --nodes-without-cilium     --helm-set-string=kubeProxyReplacement=true     --set='' --helm-set=image.repository=quay.io/cilium/cilium-ci     --helm-set=image.useDigest=false     --helm-set=image.tag=412a46c753eaeff229cba3d83332e2dea3e192f3     --helm-set=operator.image.repository=quay.io/cilium/operator     --helm-set=operator.image.suffix=-ci     --helm-set=operator.image.tag=412a46c753eaeff229cba3d83332e2dea3e192f3     --helm-set=operator.image.useDigest=false     --helm-set=hubble.relay.image.repository=quay.io/cilium/hubble-relay-ci     --helm-set=hubble.relay.image.tag=412a46c753eaeff229cba3d83332e2dea3e192f3     --helm-set=hubble.relay.image.useDigest=false --helm-set-string=routingMode=native --helm-set-string=autoDirectNodeRoutes=true --helm-set-string=ipv4NativeRoutingCIDR=10.244.0.0/16 --helm-set-string=ipv6NativeRoutingCIDR=fd00:10:244::/56   --helm-set-string=endpointRoutes.enabled=true --helm-set=ipv6.enabled=true --helm-set=bpf.masquerade=true  --helm-set=encryption.enabled=true --helm-set=encryption.type=ipsec --helm-set=encryption.nodeEncryption=false
```

2. Install cilium-cli-next
```
 cid=$(docker create quay.io/cilium/cilium-cli-ci:5401ce3551cc46052489b7153468b577830a63a4 ls)
  docker cp $cid:/usr/local/bin/cilium .//cilium-cli-next
  docker rm $cid
```

3. Run connectivity test and see failures
```
./cilium-cli-next connectivity test --include-unsafe-tests  --flush-ct --test "pod-to-pod-with-l7-policy-encryption/"  -v  -p
```

Please note it only happens when both ingress policy and egress policy are working at the same time. Once deleting either ingress/egress policy, the connectivity is back.

### Cilium Version

```
$ ./cilium-cli version
cilium-cli: v0.16.7 compiled with go1.22.2 on linux/amd64
cilium image (default): v1.15.4
cilium image (stable): v1.15.6
cilium image (running): 1.16.0-dev
```

### Kernel Version

```
$ uname -a
Linux liangzc-l-PF4RDLEQ 6.5.0-1024-oem #25-Ubuntu SMP PREEMPT_DYNAMIC Mon May 20 14:47:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
$ kubectl version
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4
```

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

This is yet another MTU issue, ipsec xfrm makes it even harder.

## Fact one: IPsec xfrm reduces MTU from 1500 to 1446.

Even if all the net ifaces on the cilium node have been set MTU 1500 (even for those in 2005 route table), xfrm makes MTU 1446 on the sneak.

This happens in the ip_forward():

```
// https://elixir.bootlin.com/linux/v6.2/source/net/ipv4/ip_forward.c#L124
int ip_forward(struct sk_buff *skb)
{
[...]
	if (!xfrm4_route_forward(skb)) {
		SKB_DR_SET(reason, XFRM_POLICY);
		goto drop;
	}
	rt = skb_rtable(skb);

	if (opt->is_strictroute && rt->rt_uses_gateway)
		goto sr_failed;

	IPCB(skb)->flags |= IPSKB_FORWARDED;
	mtu = ip_dst_mtu_maybe_forward(&rt->dst, true);
	if (ip_exceeds_mtu(skb, mtu)) {
[...]
}
```

We know that before entering `ip_forward()` in `ip_route_input_noref()` , the skb has been set `skb->_skb_refdst`, which is used to determine MTU. However, the code above indicates the existence of xfrm could change the MTU inside `ip_forward()`: `xfrm4_route_forward()` can change `skb->_skb_refdst` to the result of `xfrm_lookup_with_ifid()`. 

The xfrm MTU has a special algorithm at https://elixir.bootlin.com/linux/v6.2/source/net/xfrm/xfrm_state.c#L2747, I didn't check all the details but I did use bpftrace to fetch the new MTU from `xfrm4_route_forward()`, in our cilium case the MTU indeed is reduced from 1500 to 1446.

## Fact two: traffic from (local egress) proxy to (remote ingress) proxy has a different MTU from pod to pod 

Either pod to pod or pod to remote ingress proxy has MTU 1423, which is set on the route instead of iface:

```
$ nspod client2-ccd7b8bdf-nt4nn ip r
default via 10.244.1.12 dev eth0 mtu 1423 
10.244.1.12 dev eth0 scope link
```

However, proxy to proxy traffic has MTU 1500. This subtle change explains why we see issues only if ingress and egress policy are installed together, the scenario we never covered in test before.

## Proposed solution

It seems we can just change MTU for routing in the 2005 table, because proxy traffic will always end up there due to 0xa00/0xb00 mark.

For example, the current routes in 2005 table are

```
$ nscontainer kind-control-plane ip r s t 2005
default via 10.244.0.100 dev cilium_host proto kernel 
10.244.0.100 dev cilium_host proto kernel scope link 
```

We could change that to

```
default via 10.244.0.100 dev cilium_host proto kernel mtu 1446
10.244.0.100 dev cilium_host proto kernel scope link mtu 1446
```

(Haven't checked IPv6)

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by smagnani96**
This PR fixes the pod-to-pod traffic being dropped because of using a higher MTU value. This is caused by a non-configuration of the routes from proxy, in the routing table n. 2005 respectively. While the pod-to-pod route is being adjusted according to the IPSec overhead and the adjusted size of the authentication key, the from-proxy route is not changed as well.

This also enables the `pod-to-pod-with-l7-policy-encryption` test for IPSec in IPv4. Such test is therefore skipped if/for:
1.  IPv6, please refer to the follow-up issue #35485;
2. cilium version < 17.0.0, need to backport the fix before enabling the test.

Fixes: #33168

```release-note
Fix packet drops for pod-to-pod connections that pass through ingress & egress proxy when using IPsec, caused by MTU misconfiguration.
```

### CODE REVIEW

File: cilium-cli/connectivity/builder/pod_to_pod_encryption.go [hunk 1]
```diff
@@ -25,17 +26,17 @@ func (t podToPodEncryption) build(ct *check.ConnectivityTest, _ map[string]strin
...
+			WithFeatureRequirements(
+				features.RequireEnabled(features.L7Proxy),
+				features.RequireMode(features.EncryptionPod, encryption),
+			).
+			WithCiliumPolicy(clientsEgressL7HTTPFromAnyPolicyYAML).
+			WithCiliumPolicy(echoIngressL7HTTPFromAnywherePolicyYAML).
+			WithScenarios(
+				tests.PodToPodEncryption(features.RequireEnabled(features.EncryptionPod)),
+			)
+	}
```
Comment (julianwiedmann) [inline cilium-cli/connectivity/builder/pod_to_pod_encryption.go]: drive-by - we'll need to guard the IPsec part here to only run against v1.17 releases, until we've backported the fix into stable branches. Otherwise the test will for example run against an unfixed `v1.14` branch, and fail.

It probably also makes sense to split this change into two patches (Cilium agent vs CLI), so that it's easier to drop the CLI change when backporting.

Comment (smagnani96) [reply cilium-cli/connectivity/builder/pod_to_pod_encryption.go]: You're right, thanks for the catch!

File: pkg/proxy/proxy.go [hunk 2]
```diff
@@ -528,16 +528,21 @@ func (p *Proxy) SetProxyPort(name string, proxyType types.ProxyType, port uint16
...
 // ReinstallRoutingRules ensures the presence of routing rules and tables needed
 // to route packets to and from the L7 proxy.
-func (p *Proxy) ReinstallRoutingRules() error {
+func (p *Proxy) ReinstallRoutingRules(mtu int) error {
 	fromIngressProxy, fromEgressProxy := requireFromProxyRoutes()
 
+	// Use RouteMTU only when both ingress and egress proxy.
+	if !fromIngressProxy || !fromEgressProxy {
+		mtu = 0
+	}
```
Comment (jschwinger233) [inline pkg/proxy/proxy.go:537]: This reminds me: the reason in some situation we don't install 2005 rules (`!fromXgressProxy`), is tunnel routing mode already has `default dev cilium_host` to route proxy traffic. In this case we need to make sure those default routes rather than 2005 rules have correct MTU.

But it could be a bad idea to affect all the other normal from-host traffic, I need to think about this.

What did CI say? Any failure in tunnel scenarios for pod-to-pod-with-l7-policy-encryption?

**Review by jschwinger233 — COMMENTED** [review]
Re https://github.com/cilium/cilium/actions/runs/11240829491/job/31251421453:

I found the leak packets are all TCP reset:

```
 Error: bpftrace output is not empty
[18:14:44:129639] fd00:10:244:1::f085:34820 -> fd00:10:244:3::82cc:8080 (proto: 6, TCP flags: ...R, encap: 1, ifindex: 10, netns: f0000098, override: 0)
```

(Love this tcp flag information, love Marco!)

So it's probably caused by ipcache race issue when pods are removed but packets are still lingering around, maybe there is a small window when ipcache entry for that lingered packet is gone. We saw the similar issue before but forgot how we worked around it...

**Comment by jschwinger233** [comment]
Interesting, failed jobs are all vxlan tunnel.

> What did CI say? Any failure in tunnel scenarios for pod-to-pod-with-l7-policy-encryption?

Maybe that's how CI warned us? But geneve tunnel was green...

Can you check the v6 route table, what's the mtu there, does that look good to you?

File: pkg/proxy/proxy.go (hunk 2 above)
Comment (smagnani96) [reply pkg/proxy/proxy.go:537]: To be honest, I was not considering the overlay scenario when working on this patch. Trying to play locally with Overlay doesn't seem to report any error to connectivity even before this patch (ESP packet not fragmented). Though, I would like to replicate locally with the exact kernel that are failing and see what happens with this test enabled.

AFAIU, CI seems to confirm this, connectivity tests are passing. The plain text IPv6 packet we're recording should be an exception and should not indicate that the whole communication was plain text (right?): I would expect more than one entry in the bpftool output otherwise, let me know if I'm mistaken.

**Comment by smagnani96** [comment]
> Can you check the v6 route table, what's the mtu there, does that look good to you?

All configs failing are using VxLan. Tests with Geneve are working.
Connectivity is ok.
Unencrypted RST between:

| Pod | Identity | IPv4 | IPv6 | Node | IPv4 | IPv6 | Agent | Envoy |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| client | 24974 | 10.244.1.111 | fd00:10:244:1::f085 | kind-worker | 10.244.1.124 | fd00:10:244:1::5c12 | cilium-scxv9 | cilium-envoy-8r5tp |
| echo-other-node | 61410 | 10.244.3.239 | fd00:10:244:3::82cc | kind-worker2 | 10.244.3.91 | fd00:10:244:3::dda9 | cilium-hcv5v | cilium-envoy-px94d |

```bash
fd00:10:244:1::f085:34820 -> fd00:10:244:3::82cc:8080 (proto: 6, TCP flags: ...R, encap: 1, ifindex: 10, netns: f0000098, override: 0)
```

## Table 200

Default table to use for IPSec routing rules (0xe00, 0xd00). MTU set to 1450: 1500 - 50 (tunnel overhead)

```bash
# IPv4
local 10.244.1.0/24 dev cilium_vxlan proto kernel scope host 
10.244.0.0/24 dev cilium_host proto kernel mtu 1450 
10.244.3.0/24 dev cilium_host proto kernel mtu 1450 

# IPv6
local fd00:10:244:1::/64 dev cilium_vxlan proto kernel metric 1024 pref medium
fd00:10:244::/64 dev cilium_host proto kernel metric 1024 mtu 1450 pref medium
fd00:10:244:3::/64 dev cilium_host proto kernel metric 1024 mtu 1450 pref medium

```

## Table 2004

Default table to use routing rules to the proxy.

```bash
# IPv4
local default dev lo proto kernel scope host 

# IPv6
local default dev lo proto kernel metric 1024 pref medium
```

## Default

MTU set to 1373: 1500 - 50 (tunnel) - 77 (IPSec)

```bash
# IPv4
default via 172.18.0.1 dev eth0 
10.244.0.0/24 via 10.244.1.124 dev cilium_host proto kernel src 10.244.1.124 mtu 1373 
10.244.1.0/24 via 10.244.1.124 dev cilium_host proto kernel src 10.244.1.124 
10.244.1.124 dev cilium_host proto kernel scope link 
10.244.3.0/24 via 10.244.1.124 dev cilium_host proto kernel src 10.244.1.124 mtu 1373 
172.18.0.0/16 dev eth0 proto kernel scope link src 172.18.0.4 
192.168.0.0/16 dev eth1 proto kernel scope link src 192.168.0.2 

# IPv6
fc00:c111::/64 dev eth0 proto kernel metric 256 pref medium
fc00:c112::/64 dev eth1 proto kernel metric 256 pref medium
fd00:10:244::/64 dev cilium_host proto kernel src fd00:10:244:1::5c12 metric 1024 mtu 1373 pref medium
fd00:10:244:1::5c12 dev cilium_host proto kernel metric 256 pref medium
fd00:10:244:1::/64 dev cilium_host proto kernel src fd00:10:244:1::5c12 metric 1024 pref medium
fd00:10:244:3::/64 dev cilium_host proto kernel src fd00:10:244:1::5c12 metric 1024 mtu 1373 pref medium
fe80::/64 dev eth0 proto kernel metric 256 pref medium
fe80::/64 dev eth1 proto kernel metric 256 pref medium
fe80::/64 dev cilium_net proto kernel metric 256 pref medium
fe80::/64 dev cilium_vxlan proto kernel metric 256 pref medium
fe80::/64 dev lxc_health proto kernel metric 256 pref medium
fe80::/64 dev lxc61a1aee0bc58 proto kernel metric 256 pref medium
fe80::/64 dev lxc2a78580b2efb proto kernel metric 256 pref medium
fe80::/64 dev lxc408d98fc6df1 proto kernel metric 256 pref medium
default via fc00:c111::1 dev eth0 metric 1024 pref medium
```

I'm not seeing particular differences wrt routing table with Geneve.
I'll keep investigating logs and try to replicate with the exact same kernel.

File: pkg/proxy/proxy.go (hunk 2 above)
Comment (jschwinger233) [reply pkg/proxy/proxy.go:537]: > The plain text IPv6 packet we're recording should be an exception and should not indicate that the whole communication was plain text.

Yes. It's a transient issue coming from...maybe from pod deletion, policy creating and deleting....

Can you open another draft PR to run the pod2pod encryption test, but without any other changes you made here such as routing MTU. I suspect the leak isn't caused by your PR, it's been there since forever.

Comment (jschwinger233) [reply pkg/proxy/proxy.go:537]: Withdraw what I said above.... without your changes pod2pod encryption test can't pass connectivity checks....

Comment (smagnani96) [reply pkg/proxy/proxy.go:537]: > Can you open another draft PR to run the pod2pod encryption test, but without any other changes you made here such as routing MTU. I suspect the leak isn't caused by your PR, it's been there since forever.

Yep sure, I wanted to test CI local to avoid opening a draft PR :joy: I'll open it in a minute. I suspect too it is not affected by our MTU patch, but still addressing it in this issue would be a good option.

Comment (smagnani96) [reply pkg/proxy/proxy.go:537]: > Withdraw what I said above.... without your changes pod2pod encryption test can't pass connectivity checks....

Not in native routive, but it still should pass in geneve/vxlan (apparently not in vxlan), right?

**Comment by jschwinger233** [comment]
Thank you Simone. I feel the TCP reset seems to be a clue, because there shouldn't be tcp reset during connectivity test? We can maybe narrow down the scope by finding which test caused tcp reset. (`cli connectivity test --include-unsafe-tests  --flush-ct --test "echo-ingress,!client-egress" ` can use `--test` to run or not run specific tests.)

**Comment by smagnani96** [comment]
Another detail, I need to check if it is deterministic or not:

`rhel8-20240404.144247` and `bpf-next-20240711.013133` are failing after the 1st connectivity test (plain text packet leaked), while for `5.15-20240710.064909` the plain text packet is observed after the 2nd connectivity test performed after the IPSec Key Rotation.

File: pkg/proxy/proxy.go (hunk 2 above)
Comment (smagnani96) [reply pkg/proxy/proxy.go:537]: https://github.com/cilium/cilium/actions/runs/11273423172

1. `rhel8-20240404.144247` failing with same reason
2. `5.15-20240710.064909` failing but immediately after the 1st connectivity test (no after rotation)
3.  `bpf-next-20240711.013133` passing :open_mouth: 

All the other ones are failing because there's no the commit with the MTU fix, I was focusing on these 3.

**Comment by jschwinger233** [comment]
@smagnani96 If you feel hard to make progress, it's okay to fix v4 first, leaving a v6 issue for tracking. You can skip running pod-to-pod-encryption test for v6 in cli/connectivity.

File: pkg/proxy/proxy.go (hunk 2 above)
Comment (smagnani96) [reply pkg/proxy/proxy.go:537]: Resolving for now, moving the whole conversation concerning the tests in a new issue+PR.

**Comment by smagnani96** [comment]
Moving the discussion of tests and their enabling into a different issue/pr #35485.
Leaving this only for the fix of MTU.

**Review by pchaigno — APPROVED** [review]

**Comment by jschwinger233** [comment]
Maybe worth enabling `pod-to-pod-with-l7-policy-encryption` connectivity test for IPv4 only in this PR? 

Inside this block: https://github.com/cilium/cilium/blob/main/cilium-cli/connectivity/tests/encryption.go#L347
we can add 
```
if ipFam == features.IPFamilyV6 {
    // comment, #issue_no
    return
}
```

File: cilium-cli/connectivity/tests/encryption.go [hunk 3]
```diff
@@ -197,6 +197,26 @@ func isWgEncap(t *check.Test) bool {
...
+// 2. usage of IPv6, for which the test is flaky (see https://github.com/cilium/cilium/issues/35485).
+//
+// Once the above reasons are fixed, this function can be removed.
+func checkIPSecPodToPod(t *check.Test, ipFam features.IPFamily) error {
+	if e, ok := t.Context().Feature(features.EncryptionPod); !(ok && e.Enabled && e.Mode == "ipsec") {
+		return nil
+	}
+	if !versioncheck.MustCompile(">=1.17.0")(t.Context().CiliumVersion) {
+		return fmt.Errorf("enabling test for IPSec requires backporting")
+	}
```
Comment (jschwinger233) [inline cilium-cli/connectivity/tests/encryption.go:213]: feature and version checks can be put in cilium-cli/connectivity/builder/pod_to_pod_encryption.go to skip the whole test at all with clear skip reason. Like what you did at https://github.com/cilium/cilium/pull/35486/files#diff-7a17abdbd1cb8e727bf901ec2001452944a48e4d03d83a46ee7e8e760fe9e6b3R30-R39

Comment (smagnani96) [reply cilium-cli/connectivity/tests/encryption.go:213]: Ok, but then I don't think the following is enough [here](https://github.com/cilium/cilium/blob/main/cilium-cli/connectivity/tests/encryption.go#L347), as it would prevent also WireGuard+IPv6:

```go
if ipFam == features.IPFamilyV6 {
    // comment, #issue_no
    return
}
```

I would need to add:

```go
if f, ok := t.Context().Feature(features.EncryptionPod); ok && f.Enabled && f.Mode == "ipsec" && ipFam == features.IPFamilyV6 {
    // comment, #issue_no
    return
}
		
```

and that is why I decided to create a unique function where to check both the requirements (cilium version and ipFamily with IPSec).

Comment (jschwinger233) [reply cilium-cli/connectivity/tests/encryption.go:213]: You are correct. Resolve the conversation.

**Review by jschwinger233 — APPROVED** [review]
Thank you! Keep an eye on https://github.com/cilium/cilium/actions/runs/11477726748/job/31940507230 (and ci-e2e for wireguard), check the log and make sure `pod-to-pod-with-l7-policy-encryption` does get enabled.

File: cilium-cli/connectivity/tests/encryption.go (hunk 3 above)
Comment (smagnani96) [reply cilium-cli/connectivity/tests/encryption.go:213]: Let me know what is the preferred way, I'm ok with both. If we want to split the checks between the two files (version in `pod_to_pod_encryption.go` and IPSec+IPv6 in `encryption.go`) I'll correct the last commit :+1:

**Comment by smagnani96** [comment]
> Thank you! Keep an eye on https://github.com/cilium/cilium/actions/runs/11477726748/job/31940507230 (and ci-e2e for wireguard), check the log and make sure `pod-to-pod-with-l7-policy-encryption` does get enabled.

I'm checking at the raw logs for:

1. in `ci-eks-upgrade` WireGuard (tests n. 9,10,11,12,16) is passing and with both ipv4/ipv6 being executed (two dots in the output)
2. in `ci-ipsec-upgrade` IPSec tests are being executed and passing (only one dot in the output, presumably since only IPv4 is executed -- would need `--debug` to see the message)

**Review by sayboras — APPROVED** [review]

**Review by rgo3 — APPROVED** [review]

**Comment by julianwiedmann** [comment]
@smagnani96 word-smithing the release note a bit, I'd suggest

>Fix pod-to-pod MTU drop when using in+egress ~~egress~~ proxy with IPSec ~~and enable IPv4 test~~

or slightly rephrased
> Fix packet drops for pod-to-pod connections that pass through ingress & egress proxy when using IPsec, caused by MTU misconfiguration.


Striking the test change, as it's not user-relevant (and this note also gets copied into the release note for stable releases when backporting)

**Comment by julianwiedmann** [comment]
I think this is also worth backporting to v1.15. Adding the label, please shout if you disagree.

**Comment by julianwiedmann** [comment]
> > I think this is also worth backporting to v1.15. Adding the label, please shout if you disagree.
> 
> MTU+IPsec+ingress L7+egress L7 doesn't really scream [major bugfix](https://docs.cilium.io/en/stable/contributing/release/backports/#backport-criteria-for-x-y-1-z-and-x-y-2-z) to me 😅

The MTU aspect isn't something that users would actively (mis-)configure though, no? It's just what's causing the problem.

Imho we shouldn't straight-out break connectivity like this, in particular when users have no easy work-around (disable IPsec or L7 policies, pick your security poison?).
