### PR TITLE
Ignore empty Maglev map from breaking `bpf lb maglev list`

### LINKED ISSUE #18037: Maglev list no longer seems to work
With v1.11.0-rc3 version of Cilium the "lb maglev list" command no longer works:
```
root@demo-load-balancer:~# docker exec cilium-agent cilium bpf lb maglev list
Error: Cannot initialize maglev maps: cannot determine v6 outer maglev map's table size
```

Potential regression from https://github.com/cilium/cilium/commit/789eef0d148d0aa590d2a1b2da7fd69da6dafc47?

### PR DESCRIPTION
**Pull request by ti-mo**
While working on a solution to #18037, I also encountered a few minor issues with the Maglev code. This commit aims to make the code a bit more idiomatic. 

- Fix an ipv6 (or ipv4) Maglev map without any services from breaking `bpf lb maglev list` by always performing both dumps.
- Reduced the length of the 'get' handler in particular by carving the logic out into separate functions.
- Implemented more logic as methods instead of free functions wherever it made sense.
- Added sanity checks to prevent e.g. double-initialization of the Maglev maps, since their handles are stored in global variables. (this should be addressed at some point)
- Store the Maglev table size intended by the user in a global var to avoid having multiple copies littered throughout outer/inner map structs.
- Use errors to convey error states to the caller instead of opaque catch-all 'UnknownMaglevTableSize' return.
- Provide helpers like MaglevOuterMap.UpdateService() that are friendlier to work with and somewhat easier to reason about.
- Provide dump methods on both outer and inner map types.

Fixes: https://github.com/cilium/cilium/issues/18037

```release-note
Fix `bpf lb maglev list` command when ipv4 or ipv6 Maglev lookup tables are empty
```

### CODE REVIEW

File: cilium/cmd/bpf_lb_maglev_get.go [hunk 1]
```diff
@@ -23,51 +25,69 @@ var bpfMaglevGetCmd = &cobra.Command{
...
 		}
 
-		TablePrinter("SVC ID", "LOOKUP TABLE", lookupTables)
+		TablePrinter("SVC ID", "LOOKUP TABLE", backends)
 	},
 }
 
+// getMaglevServiceBackends queries the v4 and v6 Maglev maps for the backends
+// of the given service ID.
+func getMaglevServiceBackends(svcID uint64) (map[string][]string, error) {
```
Comment (brb) [inline cilium/cmd/bpf_lb_maglev_get.go]: Nit: svcID is u16 (I know, the previous code had it u64).

File: cilium/cmd/bpf_lb_maglev_list.go [hunk 2]
```diff
@@ -21,52 +22,59 @@ var bpfMaglevListCmd = &cobra.Command{
...
-	innerValue, err := innerMap.Lookup(&innerKey)
+	v6, err := dumpMaglevTable(lbmap.MaglevOuter6MapName)
 	if err != nil {
-		Fatalf("Unable to lookup element in map by fd %d: %s", value.FD, err)
+		return nil, err
 	}
 
-	tables[fmt.Sprintf("%d", key.ToNetwork().RevNatID)] = []string{fmt.Sprintf("%v", innerValue.BackendIDs)}
+	// Merge v6 lookup tables into v4 result.
+	// Overlapping entries will clobber each other.
```
Comment (brb) [inline cilium/cmd/bpf_lb_maglev_list.go]: They should not overlap, as it's not possible that two services will end up with the same ID (even if they belong to different IP families).

**Review by brb — APPROVED** [review]
Thanks! Two nits.
