### PR TITLE
fix(3891): mirror parent pod labels to cilium endpoints

### LINKED ISSUE #3891: CEPs should mirror parent pod labels
1 CEP (CiliumEndpoint) object is created per pod managed by cilium. The name of the CEP is the same as the pod, which makes it easier to select. Label based selection is common, however, and quite convenient. If we mirror the pod's labels onto the corresponding CEP object we can issue an equivalent kubectl command with label filters to get the list.

### PR DESCRIPTION
**Pull request by fristonio**
* Fixes #3891

This allows label based selection for CiliumEndpoints.

image

### CODE REVIEW

**Comment by fristonio** [comment]
test-me-please

**Review by aanm — CHANGES_REQUESTED** [review]
What happens if the pod changes labels? Will the CEP also have its labels changed?

**Comment by fristonio** [comment]
Sorry :sweat_smile: 
I forgot to handle that, I thought this was a simple change.
This should be easy though, we already watch for pod changes in the K8swatcher. We can check if the labels have changed for the pod and can mirror the changes in the CiliumEndpoint CRD object.
I will update the pull request with the required changes.

**Comment by fristonio** [comment]
test-me-please

File: pkg/k8s/watchers/pod.go [hunk 1]
```diff
@@ -273,6 +284,69 @@ func realizePodAnnotationUpdate(podEP *endpoint.Endpoint) {
 	}
 }
 
+// updateCiliumEndpointLabels update the Labels in CiliumEndpoint object by mirroring
```
Comment (christarazi) [inline pkg/k8s/watchers/pod.go]: Nit:

```suggestion
// updateCiliumEndpointLabels updates the Labels in CiliumEndpoint object by mirroring
```

**Review by christarazi — APPROVED** [review]
Minor nit; change looks good to me. Looks like it has passed CI, so no need to run it again. The nit is non-functional. Assuming no other reviewers / other changes, this PR looks good to go.

File: pkg/k8s/watchers/cilium_endpoint.go [hunk 2]
```diff
@@ -62,6 +62,14 @@ func (k *K8sWatcher) ciliumEndpointsInit(ciliumNPClient *k8s.K8sCiliumClient, as
...
 						if newCE := k8s.ObjToCiliumEndpoint(newObj); newCE != nil {
 							valid = true
+
+							// Local processing of CiliumEndpoints does not include the use of Labels.
+							// So if there is an update in the labels of CiliumEndpoint we just ignore it here.
+							// We update CEPs labels only when there is an update in the Pod Labels which
+							// is managed by K8S Pod watcher.
+							oldCE.Labels = nil
+							newCE.Labels = nil
+
```
Comment (aanm) [inline pkg/k8s/watchers/cilium_endpoint.go]: This is not required since the labels are already set to nil here https://github.com/cilium/cilium/blob/b41bbc08eabd4f508e8a35a66076c6f679b542d4/pkg/k8s/factory_functions.go#L682-L685

File: pkg/k8s/watchers/pod.go [hunk 3]
```diff
@@ -244,6 +249,12 @@ func (k *K8sWatcher) updateK8sPodV1(oldK8sPod, newK8sPod *slim_corev1.Pod) error
 		if err != nil {
 			return err
 		}
+
+		err = updateCiliumEndpointLabels(podEP, newPodLabels)
+		if err != nil {
+			log.WithError(err).Debugf("Error while updating CiliumEndpoint object with new Pod labels")
+			return err
+		}
```
Comment (aanm) [inline pkg/k8s/watchers/pod.go]: This should be replaced with a controller so that it runs in the background. This controller needs to be associated with the endpoint `podEP` so that the controller is deleted once the EP is gone.

**Review by aanm — CHANGES_REQUESTED** [review]

**Comment by fristonio** [comment]
test-me-please

**Comment by fristonio** [comment]
test-me-please

File: pkg/k8s/watchers/pod.go [hunk 4]
```diff
@@ -271,6 +281,85 @@ func realizePodAnnotationUpdate(podEP *endpoint.Endpoint) {
...
+						labelsPatch,
+						meta_v1.PatchOptions{})
+					if err != nil {
+						scopedLog.WithError(err).Debug("Error while updating CiliumEndpoint object with new Pod labels")
+						return err
+					}
+
+				default:
+					status := v2.EndpointStatus{}
+					ep.GetCiliumEndpointStatus(option.Config).DeepCopyInto(&status)
```
Comment (aanm) [inline pkg/k8s/watchers/pod.go]: nit: this can be `status := ep.GetCiliumEndpointStatus(option.Config).DeepCopy()` if the PR is merged after https://github.com/cilium/cilium/pull/12680. I'm fine leave it as is.

**Review by aanm — APPROVED** [review]

**Comment by fristonio** [comment]
test-me-please

**Comment by fristonio** [comment]
test-me-please
