### PR TITLE
treat empty NetworkPolicyPort as "all ports on TCP" during parsing

### LINKED ISSUE #14678: Egress network policy allows traffic that should be denied
## Bug report

A network policy which should only allow traffic to a single pod based on labels, also allows traffic to other pods without the label.

Expected connectivity matrix:

There are 9 pods, so 9x9 = 81 possible requests from pod to pod.
The pod issuing the request is in the left column; the pod receiving the request is in the top row.
An `X` means the request was denied; a `.` means the request was allowed.

```
+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
|  -  | X/A | X/B | X/C | Y/A | Y/B | Y/C | Z/A | Z/B | Z/C |
+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
| x/a | X   | X   | X   | X   | .   | X   | X   | X   | X   |
| x/b | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| x/c | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| y/a | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| y/b | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| y/c | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| z/a | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| z/b | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| z/c | .   | .   | .   | .   | .   | .   | .   | .   | .   |
+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
```

Measured connectivity:

```
+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
|  -  | X/A | X/B | X/C | Y/A | Y/B | Y/C | Z/A | Z/B | Z/C |
+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
| x/a | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| x/b | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| x/c | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| y/a | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| y/b | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| y/c | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| z/a | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| z/b | .   | .   | .   | .   | .   | .   | .   | .   | .   |
| z/c | .   | .   | .   | .   | .   | .   | .   | .   | .   |
+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
```

This is based on namespaces/pods with labels:

Namespace x (labels: {"ns": "x"})
  - pod a (labels {"pod": "a"})
  - pod b (labels {"pod": "b"})
  - pod c (labels {"pod": "c"})
Namespace y (labels: {"ns": "y"})
  - pod a (labels {"pod": "a"})
  - pod b (labels {"pod": "b"})
  - pod c (labels {"pod": "c"})
Namespace z (labels: {"ns": "z"})
  - pod a (labels {"pod": "a"})
  - pod b (labels {"pod": "b"})
  - pod c (labels {"pod": "c"})

**General Information**

- Cilium version 1.9.1
- Kernel version: `Linux netpol-cilium-control-plane 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use:

        kubectl version
        Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:08:32Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
        Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

- KinD version: 0.9.0
- containerd

**How to reproduce the issue**

1. create kind cluster with cilium

        #!/usr/bin/env bash
        
        set -e
        
        CLUSTER=${CLUSTER:-netpol-cilium}
        CONFIG=${CONFIG:-netpol-cilium-conf.yaml}
        
        cat << EOF > "$CONFIG"
        kind: Cluster
        apiVersion: kind.x-k8s.io/v1alpha4
        nodes:
        - role: control-plane
        - role: worker
        - role: worker
        - role: worker
        networking:
          disableDefaultCNI: true
        EOF
        
        
        
        kind create cluster --name="$CLUSTER" --config="$CONFIG"
        until kubectl cluster-info;  do
            echo "$(date) waiting for cluster..."
            sleep 2
        done
        
        
        CILIUM_VERSION="1.9.1"
        
        # Add Cilium Helm repo
        helm repo add cilium https://helm.cilium.io/
        
        # Pre-load images
        docker pull cilium/cilium:"v${CILIUM_VERSION}"
        
        # Install cilium with Helm
        helm install cilium cilium/cilium \
          --version ${CILIUM_VERSION} \
          --namespace kube-system \
          --set nodeinit.enabled=true \
          --set kubeProxyReplacement=partial \
          --set hostServices.enabled=false \
          --set externalIPs.enabled=true \
          --set nodePort.enabled=true \
          --set hostPort.enabled=true \
          --set bpf.masquerade=false \
          --set image.pullPolicy=IfNotPresent \
          --set ipam.mode=kubernetes

2. create network policy in `netpol.yaml`

        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: vary-egress-8-0-0-2-0
          namespace: x
        spec:
          egress:
          - ports:
            - {}
            to:
            - namespaceSelector:
                matchLabels:
                  ns: "y"
              podSelector:
                matchLabels:
                  pod: b
          - ports:
            - port: 53
              protocol: UDP
          podSelector:
            matchLabels:
              pod: a
          policyTypes:
          - Egress

3. download [cyclonus 0.0.7](https://github.com/mattfenwick/cyclonus/releases/tag/v0.0.7) and invoke it with `cyclonus_0.0.7 probe --noisy=true --policy-path netpol.yaml`

### PR DESCRIPTION
**Pull request by mattfenwick**
Fixes: #14678

```release-note
Treat empty NetworkPolicyPort as "all ports on TCP" during network policy parsing
```

## Test plan

```
cd cilium

pushd pkg/k8s && go test
popd

pushd pkg/policy && go test
popd

pushd pkg/policy/api && go test
popd
```

### CODE REVIEW

**Comment by mattfenwick** [comment]
👋 wanted to put this up for preliminary feedback even though it's failing some tests!

**Review by aanm — CHANGES_REQUESTED** [review]
@jrajahalme do you mind taking a look. The port number is optional in a k8s network policy so we it can be 0. To me the proposed fixed by @mattfenwick makes sense.

**Comment by jrajahalme** [comment]
> gets the tests to pass, but not sure if that would have other bad downstream consequences?

Removing the zero test seems ok, my only concern is that L7 policies can only be applied if a port number has been specified. Would be good to add a test case with a port with default values and make sure it is rejected. Policy could be like this:
```
...
    toPorts:
    - ports:
      - {}
      rules:
        http:
        - method: "POST"
...
```

To be on the safe side this should be rejected by rule validation, maybe like this:
```
	// Sanitize L7 rules
	if !pr.Rules.IsEmpty() {
+		// Check if any of the ports was zero ("0"), maybe via a return value from 'pr.Ports[i].Sanitize()'
+		If haveZeroPort {
+			return fmt.Errorf("Port cannot be 0")
+		}
		if err := pr.Rules.sanitize(pr.Ports); err != nil {
			return err
		}
	}
```

**Comment by joestringer** [comment]
Marking as "draft" while feedback is addressed. If you would like clarification on the feedback, feel free to respond and ping the person who provided the feedback :slightly_smiling_face:  When you would like additional review, scroll to the bottom of the page and click the "Ready for review" button.

**Comment by mattfenwick** [comment]
> Marking as "draft" while feedback is addressed. If you would like clarification on the feedback, feel free to respond and ping the person who provided the feedback 🙂 When you would like additional review, scroll to the bottom of the page and click the "Ready for review" button.

Thanks for the reminder! 😄

**Comment by mattfenwick** [comment]
> > gets the tests to pass, but not sure if that would have other bad downstream consequences?
> 
> Removing the zero test seems ok, my only concern is that L7 policies can only be applied if a port number has been specified. Would be good to add a test case with a port with default values and make sure it is rejected. Policy could be like this:
> 
> ```
> ...
>     toPorts:
>     - ports:
>       - {}
>       rules:
>         http:
>         - method: "POST"
> ...
> ```
> 
> To be on the safe side this should be rejected by rule validation, maybe like this:
> 
> ```
> 	// Sanitize L7 rules
> 	if !pr.Rules.IsEmpty() {
> +		// Check if any of the ports was zero ("0"), maybe via a return value from 'pr.Ports[i].Sanitize()'
> +		If haveZeroPort {
> +			return fmt.Errorf("Port cannot be 0")
> +		}
> 		if err := pr.Rules.sanitize(pr.Ports); err != nil {
> 			return err
> 		}
> 	}
> ```

thanks for the tip @jrajahalme !

I pushed an update to add an L7, but there's still something not quite right and one of the tests in the pkg/policy/api package is now failing.

I think the problem is I'm not separating the code paths for validation for L3/L4 from L7, can you take a look?

File: pkg/policy/api/rule_validation_test.go [hunk 1]
```diff
@@ -237,6 +237,33 @@ func (s *PolicyAPITestSuite) TestL7RulesWithNonTCPProtocols(c *C) {
...
+							{},
+						},
+					},
+				}},
+			},
+		},
+	}
+
+	err := invalidL7PortRule.Sanitize()
+	c.Assert(err, Not(IsNil))
```
Comment (mattfenwick) [inline pkg/policy/api/rule_validation_test.go:264]: This test fails at the moment -- error is nil.

**Comment by mattfenwick** [comment]
ping @jrajahalme can you take a look when you get a chance ?

**Comment by mattfenwick** [comment]
bump @jrajahalme can you take a look when you get a chance?

File: pkg/policy/api/rule_validation_test.go (hunk 1 above)
Comment (jrajahalme) [reply pkg/policy/api/rule_validation_test.go:264]: The issue is with the new validation of the ports when L7 rules are present. The ports have already been validated above, so the added validation always succeeds. The validation is best moved to the beginning of `L7Rules.sanitize()` and it needs to explicitly check for port value `"0"`, like so:

NOTE: See below for a later comment, this one is a bit too simplistic, leaving this here for reference, though.

```
diff --git a/pkg/policy/api/rule_validation.go b/pkg/policy/api/rule_validation.go
index 695de01559..f9fc2d07aa 100644
--- a/pkg/policy/api/rule_validation.go
+++ b/pkg/policy/api/rule_validation.go
@@ -284,6 +284,12 @@ func (e *EgressRule) sanitize() error {
 }
 
 func (pr *L7Rules) sanitize(ports []PortProtocol) error {
+	for _, pp := range ports {
+		if pp.Port == "0" {
+			return fmt.Errorf("L7 rules can not be used when a port is 0")
+		}
+	}
+
 	nTypes := 0
 
 	if pr.HTTP != nil {
@@ -362,11 +368,6 @@ func (pr *PortRule) sanitize(ingress bool) error {
 
 	// Sanitize L7 rules
 	if !pr.Rules.IsEmpty() {
-		for _, pp := range pr.Ports {
-			if err := pp.Sanitize(); err != nil {
-				return err
-			}
-		}
 		if err := pr.Rules.sanitize(pr.Ports); err != nil {
 			return err
 		}
```
With this change the new unit test passes as expected.

Comment (jrajahalme) [reply pkg/policy/api/rule_validation_test.go:264]: @mattfenwick Sorry for the delay!

**Comment by jrajahalme** [comment]
@mattfenwick Left a comment above: https://github.com/cilium/cilium/pull/14720#discussion_r617053214

File: pkg/policy/api/rule_validation_test.go (hunk 1 above)
Comment (mattfenwick) [reply pkg/policy/api/rule_validation_test.go:264]: np thanks @jrajahalme !

**Comment by mattfenwick** [comment]
Addressed comments and rebased onto master.

**Comment by jrajahalme** [comment]
The change I proposed above was a bit too brittle, as it would allow port values such as `"00"` pass the new check. It's better to do by tracking the parsed zero values in PortProtocol validation and return a boolean telling if the port was zero:
```
diff --git a/pkg/policy/api/rule_validation.go b/pkg/policy/api/rule_validation.go
index 695de01559..d4c8778efb 100644
--- a/pkg/policy/api/rule_validation.go
+++ b/pkg/policy/api/rule_validation.go
@@ -338,14 +338,20 @@ func (pr *L7Rules) sanitize(ports []PortProtocol) error {
 }
 
 func (pr *PortRule) sanitize(ingress bool) error {
+	haveZeroPort := false
+
 	if len(pr.Ports) > maxPorts {
 		return fmt.Errorf("too many ports, the max is %d", maxPorts)
 	}
 	for i := range pr.Ports {
-		if err := pr.Ports[i].Sanitize(); err != nil {
+		var isZero bool
+		var err error
+		if isZero, err = pr.Ports[i].sanitize(); err != nil {
 			return err
 		}
-
+		if isZero {
+			haveZeroPort = true
+		}
 		hasDNSRules := pr.Rules != nil && len(pr.Rules.DNS) > 0
 		// DNS L7 rules can be TCP, UDP or ANY, all others are TCP only.
 		switch {
@@ -362,11 +368,10 @@ func (pr *PortRule) sanitize(ingress bool) error {
 
 	// Sanitize L7 rules
 	if !pr.Rules.IsEmpty() {
-		for _, pp := range pr.Ports {
-			if err := pp.Sanitize(); err != nil {
-				return err
-			}
+		if haveZeroPort {
+			return fmt.Errorf("L7 rules can not be used when a port is 0")
 		}
+
 		if err := pr.Rules.sanitize(pr.Ports); err != nil {
 			return err
 		}
@@ -374,9 +379,9 @@ func (pr *PortRule) sanitize(ingress bool) error {
 	return nil
 }
 
-func (pp *PortProtocol) Sanitize() error {
+func (pp *PortProtocol) sanitize() (isZero bool, err error) {
 	if pp.Port == "" {
-		return fmt.Errorf("Port must be specified")
+		return isZero, fmt.Errorf("Port must be specified")
 	}
 
 	// Port names are formatted as IANA Service Names.  This means that
@@ -385,19 +390,15 @@ func (pp *PortProtocol) Sanitize() error {
 	if iana.IsSvcName(pp.Port) {
 		pp.Port = strings.ToLower(pp.Port) // Normalize for case insensitive comparison
 	} else {
-		_, err := strconv.ParseUint(pp.Port, 0, 16)
+		p, err := strconv.ParseUint(pp.Port, 0, 16)
 		if err != nil {
-			return fmt.Errorf("Unable to parse port: %s", err)
+			return isZero, fmt.Errorf("Unable to parse port: %s", err)
 		}
+		isZero = p == 0
 	}
 
-	var err error
 	pp.Protocol, err = ParseL4Proto(string(pp.Protocol))
-	if err != nil {
-		return err
-	}
-
-	return nil
+	return isZero, err
 }
 
 // sanitize the given CIDR. If successful, returns the prefixLength specified

```

**Comment by jrajahalme** [comment]
@mattfenwick Sorry for the churn, I was kind of hoping I could have sent the latter comment above before you do any additional work on this! Anyway, there is a new diff w.r.t to your PR before the changes I suggested a bit earlier.

**Comment by mattfenwick** [comment]
> @mattfenwick Sorry for the churn, I was kind of hoping I could have sent the latter comment above before you do any additional work on this! Anyway, there is a new diff w.r.t to your PR before the changes I suggested a bit earlier.

np 😄 applied the diff and updated!

**Comment by twpayne** [comment]
test-me-please

**Comment by twpayne** [comment]
The runtime tests all failed, which looks like a flake: https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/4480/

I'll re-trigger the tests.

**Comment by twpayne** [comment]
retest-runtime

**Comment by twpayne** [comment]
test-runtime

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
test-1.21-4.9

**Review by twpayne — APPROVED** [review]
LGTM, thanks so much for the fix :)

**Review by jrajahalme — APPROVED** [review]

**Comment by christarazi** [comment]
Merging as we have approval and CI is all green.
