### PR TITLE
controller: make RemoveControllerAndWait tolerate missing controller

### LINKED ISSUE #38842: Cilium doesn't clean up `ipcache-inject-labels` controller properly on shutdown
See https://github.com/cilium/cilium/issues/37817#issuecomment-2789778887. It seems that if Cilium crashes earlier in the dameon init, the shutdown function that cleans up controllers seems to also error as well.

### PR DESCRIPTION
**Pull request by asdfmi**
controller: make RemoveControllerAndWait tolerate missing controller

Fixes: https://github.com/cilium/cilium/issues/38842
Related: #41272

```release-note
controller: avoid spurious errors when RemoveControllerAndWait is invoked when the controller does not exist
```

### CODE REVIEW

File: pkg/controller/manager.go [hunk 1]
```diff
@@ -195,13 +195,14 @@ func (m *Manager) RemoveController(name string) error {
 
 // RemoveControllerAndWait stops and removes a controller using
 // RemoveController() and then waits for it to run to completion.
+// This function is idempotent; if the controller does not exist, it is a no-op.
 func (m *Manager) RemoveControllerAndWait(name string) error {
-	oldCtrl, err := m.removeAndReturnController(name)
```
Comment (bimmlerd) [inline pkg/controller/manager.go:199]: I'm not sure this is great - is there no specific error that we can match against? This ignores _any_ error thrown by `removeAndReturnController` (now but also in the future)

File: pkg/ipcache/ipcache.go [hunk 2]
```diff
@@ -178,8 +178,8 @@ func NewIPCache(c *Configuration) *IPCache {
 }
 
 // Shutdown cleans up asynchronous routines associated with the IPCache.
-func (ipc *IPCache) Shutdown() error {
-	return ipc.controllers.RemoveControllerAndWait(LabelInjectorName)
+func (ipc *IPCache) Shutdown() {
```
Comment (bimmlerd) [inline pkg/ipcache/ipcache.go]: This doesn't make sense to me; either we drop the error from `RemoveControllerAndWait` too (but let's not!) or we do return its error.

**Review by bimmlerd — CHANGES_REQUESTED** [review]

**Comment by joestringer** [comment]
Marking draft pending feedback from @asdfmi. You can use "Ready for Review" button at bottom of page when changes have been made to bring it back to the attention of reviewers.

**Comment by asdfmi** [comment]
still working

**Comment by asdfmi** [comment]
@bimmlerd 
Thanks for the feedback. `RemoveControllerAndWait` now treats missing controllers as a no-op while still propagating other errors, and I added unit tests to capture that behavior. Appreciate another look.

**Review by bimmlerd — APPROVED** [review]
LGMT, let's see what the tests say.

**Comment by julianwiedmann** [comment]
:wave: Should we backport this fix? What would be a release-note that describes the user-visible impact of the addressed issue?

**Comment by asdfmi** [comment]
I think it's worth backporting. It simply turns the case where the controller doesn't exist into a no-op and removes the spurious shutdown noise.

Added a release note to the PR description.
