### PR TITLE
datapath: Fix wrong rev-NAT xlation due to stale conntrack entry

### LINKED ISSUE #10983: Stale conntrack entry might lead to invalid rev-DNAT xlation for reply from NodePort service
If a service endpoint is accessed via two different NodePort services from the same source IP and port, a reply from the endpoint will be wrongly rev-DNAT xlated.

E.g.:
```
CPU 01: MARK 0x6a60e2e6 FROM 0 DEBUG: Conntrack lookup 1/2: src=172.29.50.224:33632 dst=172.29.2.21:32532
CPU 01: MARK 0x6a60e2e6 FROM 0 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=4
CPU 01: MARK 0x6a60e2e6 FROM 0 DEBUG: CT verdict: New, revnat=0
CPU 01: MARK 0x6a60e2e6 FROM 0 DEBUG: Slave service lookup: slave=1, dport=32532
CPU 01: MARK 0x6a60e2e6 FROM 0 DEBUG: Conntrack create: proxy-port=0 revnat=8 src-identity=0 lb=0.0.0.0
CPU 01: MARK 0x6a60e2e6 FROM 0 DEBUG: Conntrack lookup 1/2: src=172.29.50.224:33632 dst=10.42.1.254:3306
CPU 01: MARK 0x6a60e2e6 FROM 0 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=1
CPU 01: MARK 0x6a60e2e6 FROM 0 DEBUG: CT entry found lifetime=501525, revnat=22
CPU 01: MARK 0x6a60e2e6 FROM 0 DEBUG: CT verdict: Established, revnat=22
CPU 01: MARK 0xa140b3a1 FROM 0 DEBUG: Conntrack lookup 1/2: src=10.42.1.254:3306 dst=172.29.50.224:33632
CPU 01: MARK 0xa140b3a1 FROM 0 DEBUG: Conntrack lookup 2/2: nexthdr=6 flags=0
CPU 01: MARK 0xa140b3a1 FROM 0 DEBUG: CT entry found lifetime=523408, revnat=22
CPU 01: MARK 0xa140b3a1 FROM 0 DEBUG: CT verdict: Reply, revnat=22
CPU 01: MARK 0xa140b3a1 FROM 0 DEBUG: Reverse NAT lookup, index=22
CPU 01: MARK 0xa140b3a1 FROM 0 DEBUG: Performing reverse NAT, address=192.168.58.0 port=3306

TCP OUT 172.29.2.21:32532 -> 172.29.50.224:33632 service expires=501869 RxPackets=0 RxBytes=28 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=0 TxBytes=0 TxFlagsSeen=0x02 LastTxReport=501808 Flags=0x0000 [ ] RevNAT=8 SourceSecurityID=0
TCP OUT 192.168.58.0:3306 -> 172.29.50.224:33632 service expires=523409 RxPackets=0 RxBytes=28 RxFlagsSeen=0x00 LastRxReport=0 TxPackets=0 TxBytes=0 TxFlagsSeen=0x1f LastTxReport=501808 Flags=0x0012 [ TxClosing SeenNonSyn ] RevNAT=22 SourceSecurityID=0
TCP OUT 172.29.50.224:33632 -> 10.42.1.254:3306 expires=523409 RxPackets=8 RxBytes=637 RxFlagsSeen=0x1b LastRxReport=501808 TxPackets=13 TxBytes=861 TxFlagsSeen=0x1f LastTxReport=501808 Flags=0x0032 [ TxClosing SeenNonSyn NodePort ] RevNAT=22 SourceSecurityID=2
```

First, the endpoint was accessed via `172.29.50.224:33632 -> 192.168.58.0:3306`, and afterwards by `172.29.50.224:33632 -> 172.29.2.21:32532`. In the second flow, the src IP and port of the reply was wrongly xlated to `192.168.58.0:3306`.

### PR DESCRIPTION
**Pull request by brb**
See commit msgs.

In addition to the CI tests, I've tested the fix on a user's cluster which previously was hit by #10983 - the fix resolved the problem.

Fix #10983
Also, this might resolve some of the NodePort BPF flakes.

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-gke

File: bpf/lib/nodeport.h [hunk 1]
```diff
@@ -541,13 +542,16 @@ static __always_inline int nodeport_lb6(struct __ctx_buff *ctx,
 
 	case CT_ESTABLISHED:
 	case CT_REPLY:
+		if (ct_state.rev_nat_index != svc->rev_nat_index) {
+			goto redo_all;
+		}
```
Comment (borkmann) [inline bpf/lib/nodeport.h]: Small nit: no extra braces here and below (kernel style) and wrap in unlikely().

Comment (borkmann) [reply bpf/lib/nodeport.h]: Isn't this racy? E.g. what happens if we had an earlier entry in there where packets are in flight and replies to be expected to go out from the Pod to the client? They will then go out with the wrong svc tuple?

Comment (borkmann) [reply bpf/lib/nodeport.h]: Otoh, we have the same logic in https://github.com/cilium/cilium/blob/master/bpf/bpf_lxc.c#L199 . Given there can only be one such svc at the same time, it really must have been stale. Could we consolidate such check with the one from bpf_lxc into a small helper and add a comment on why it's okay to redo the full tuple? Also, is there any advantage to explicitly delete the existing one first? Perhaps we should remove that from bpf_lxc.c so both cases would be the same logic.

**Comment by brb** [comment]
GKE hit the Kafka panic flake and `K8sDatapathConfig MonitorAggregation Checks that monitor aggregation restricts notifications` flake.

**Comment by brb** [comment]
test-gke

File: bpf/lib/nodeport.h (hunk 1 above)
Comment (brb) [reply bpf/lib/nodeport.h]: > Isn't this racy?

The stale conntrack entry problem can only happen when a packet is sent from the same IP addr and port. So, this means that the client before sending a request to the other svc waited long enough (TIME_WAIT) until the port became available again. Therefore, I assume that such races are very unlikely to happen.

> Could we consolidate such check with the one from bpf_lxc into a small helper and add a comment on why it's okay to redo the full tuple?

The check in bpf_lxc.c compares rev_nat_index from two ct_states, while in nodeport.h - from svc and ct_state. Probably it's OK to replace the former to check against svc instead of ct_state_new, so then the consolidation would make sense.

> Also, is there any advantage to explicitly delete the existing one first?

ct_delete{4,6}() also tries to remove related SNAT entries. Perhaps, it's fine to keep the SNAT related entries in the case of the nodeport.h, as it can be reused by snat_process() later on. In the case of bpf_lxc.c, do you see a case in which SNAT entries would be created?

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

File: bpf/lib/nodeport.h (hunk 1 above)
Comment (borkmann) [reply bpf/lib/nodeport.h]: Not that I'm aware of, so it would make sense to have both logic the same, meaning we likely could just remove the ct_delete*().

**Comment by brb** [comment]
test-me-please

File: bpf/lib/nodeport.h (hunk 1 above)
Comment (brb) [reply bpf/lib/nodeport.h]: PTAL - I removed the ct_delete*()'s, but I didn't add a helper "ct_belongs_to_svc()", as IMO it might confuse developers by allowing them to think that passing any CT entry would test whether it belongs to the given svc. This is a wrong assumption, as not all entries have rev_nat_index set (e.g. CT_INGRESS).

**Review by borkmann — APPROVED** [review]
LGTM

**Comment by brb** [comment]
CI timeout due to not cached Docker image.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-gke

**Comment by brb** [comment]
test-me-please

**Comment by tgraf** [comment]
restart-ginkgo

**Comment by brb** [comment]
CI timed out.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Comment by joestringer** [comment]
@brb do you consider this PR to be a major bugfix / affecting multiple users to justify backport to v1.6? Seems like there's non-trivial conflicts and without your assistance it will not make its way into a v1.6 release.

https://docs.cilium.io/en/latest/contributing/release/backports/#backport-criteria-for-x-y-1-z-and-x-y-2-z

**Comment by brb** [comment]
@joestringer I do not expect that many users are accessing the same endoint via two different services from outside. So, it's OK to not include in v1.6. If we hear any reports, than I will backport it manually.
