### PR TITLE
endpoint, proxy: Fix deadlock with ipcache and K8s watcher

### LINKED ISSUE #20915: Scale-down event of EKS kube-apiserver causes network outage
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

AWS EKS scales its kube-apiserver(s) out and in. I notice that whenever a kube-apiserver is removed, the cilium-agent and -operator continue to make API requests to this now decommissioned kube-apiserver. What's annoying is that this kube-apiserver does not seem to close existing connections. Instead, it now returns a 401 Unauthorized as a response to all requests. This could also be considered an EKS bug. The result is that cilium can no longer create endpoints, allocate ENIs or IPs and that the CiliumLocalRedirectPolicy and DNS proxy seem to stop functioning; potentially causing a cluster-wide network outage until cilium connects to a working kube-apiserver

I know that it is caused by a kube-apiserver being removed because I am monitoring the endpoints in `kubectl -n default get endpoints kubernetes`. Whenever an endpoint is removed, the problems start.

Restarting the agent and the operator restores functionality. Without a restart it takes about 5 minutes before cilium connects to a working endpoint.

From the operator:
```
cilium-operator-78d4dc7dbb-lv8q2 cilium-operator error retrieving resource lock kube-system/cilium-operator-resource-lock: Unauthorized
cilium-operator-78d4dc7dbb-lv8q2 cilium-operator level=error msg="error retrieving resource lock kube-system/cilium-operator-resource-lock: Unauthorized" subsys=klo
```

I don't know exactly how to reproduce this. What I do know is that new EKS clusters see the most scaling events of the kube-apiserver. I reproduce it myself by creating a new cluster and then scheduling a lot of pods. This often leads to scaling events.

Our cilium is installed with the following helm values:

```
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
        - key: kubernetes.io/arch
          operator: In
          values:
          - amd64
        - key: eks.amazonaws.com/compute-type
          operator: NotIn
          values:
          - fargate
bpf:
  hostRouting: false
  masquerade: true
  tproxy: true
cni:
  chainingMode: none
  configMap: cni-configuration
  customConf: true
devices: eth0
enableCiliumEndpointSlice: true
endpointHealthChecking:
  enabled: false
eni:
  awsEnablePrefixDelegation: true
  ec2APIEndpoint: ec2.eu-west-1.amazonaws.com
  enabled: true
  instanceTagsFilter: aws:eks:cluster-name=ci-eks-4qrg9g
  updateEC2AdapterLimitViaAPI: true
healthChecking: false
hubble:
  enabled: true
  eventBufferCapacity: "8191"
  metrics:
    enabled: null
    serviceMonitor:
      enabled: true
  relay:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: k8s-app
              operator: In
              values:
              - hubble-relay
          topologyKey: kubernetes.io/hostname
    enabled: true
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1
    replicas: 3
    rollOutPods: true
  ui:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: k8s-app
              operator: In
              values:
              - hubble-ui
          topologyKey: kubernetes.io/hostname
    enabled: true
    ingress:
      annotations: {}
      enabled: true
      hosts:
      - hubble.example.com
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1
    replicas: 3
    rollOutPods: true
ipam:
  mode: eni
k8sServiceHost: C0F975EE951307D359FFC679CA1FDD1F.sk1.eu-west-1.eks.amazonaws.com
k8sServicePort: 443
kubeProxyReplacement: strict
l7Proxy: true
loadBalancer:
  serviceTopology: true
localRedirectPolicy: true
operator:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: io.cilium/app
            operator: In
            values:
            - operator
          - key: name
            operator: In
            values:
            - cilium-operator
        topologyKey: kubernetes.io/hostname
  extraArgs:
  - --unmanaged-pod-watcher-interval=0
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1
  priorityClassName: system-cluster-critical
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  replicas: 3
  rollOutPods: true
  tolerations:
  - key: node.cilium.io/agent-not-ready
    operator: Exists
  - key: node.kubernetes.io/not-ready
    operator: Exists
priorityClassName: system-node-critical
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
svcSourceRangeCheck: "false"
tunnel: disabled
updateStrategy:
  type: OnDelete
```

### Cilium Version

```
❯ cilium version
cilium-cli: 0.12.1 compiled with go1.18.5 on linux/amd64
cilium image (default): v1.12.0
cilium image (stable): v1.12.0
cilium image (running): v1.12.0
```

### Kernel Version

Several:
```
5.15.54-25.126.amzn2.x86_64
5.4.204-113.362.amzn2.x86_64
```

### Kubernetes Version

```
Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.22.11-eks-18ef993
```

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by christarazi**
- endpoint, proxy: Fix deadlock with ipcache and K8s watcher
- proxy: Refactor dnsRedirect to prevent regressions
- proxy: Remove unused dnsConfiguration type

Fixes: https://github.com/cilium/cilium/issues/20915
Fixes: https://github.com/cilium/cilium/pull/18996

```release-note
[EKS] Fix deadlock causing network connectivity outages when kube-apiservers scale down
```

### CODE REVIEW

File: pkg/endpoint/bpf.go [hunk 1]
```diff
@@ -601,6 +601,17 @@ func (e *Endpoint) regenerateBPF(regenContext *regenerationContext) (revnum uint
...
+	// above (runPreCompilationSteps()), but this caused a deadlock with the
+	// ipcache. It's not necessary to run this code within the  critical
+	// section as the only use for the DNS rules is for restoring them upon the
+	// Agent restart.
+	rules := e.owner.GetDNSRules(uint16(e.ID))
+	if err := e.lockAlive(); err != nil {
+		return 0, compilationExecuted, err
+	}
+	e.OnDNSPolicyUpdateLocked(rules)
+	e.unlock()
```
Comment (joestringer) [inline pkg/endpoint/bpf.go:614]: This shift looks good to me. I'll CC @jrajahalme as well for an extra pair of eyes.

In reality I suspect that we may not even need this code at all, because it will be triggered when regularly syncing the headerfile anyway, but we can look into that subsequently.

image

Comment (joestringer) [reply pkg/endpoint/bpf.go:614]: I suspect that this may increase the frequency with which we sync these, given that it will trigger not only when the L7 policy is newly created+applied, but also for all endpoint regenerations (along with each time we sync the headerfile via controller, ~5s IIRC). Unless the new location somehow triggers uninitialized pointers or such for the proxy reference, I think we should be fine with that though. I don't expect this operation to be overly expensive.

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
Given the nature of the [k8s-1.16-kernel-4.19 failures](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-kernel-4.19/21/), we'll need to dig closely through to understand whether there could be a DNS availability impact with these new changes. At a glance I'm not really sure.

File: pkg/endpoint/bpf.go (hunk 1 above)
Comment (jrajahalme) [reply pkg/endpoint/bpf.go:614]: +1 for the increase on # of runs at this location, especially when many endpoints might not have any DNS rules at all, or if they do they likely do not change much over time.

Comment (jrajahalme) [reply pkg/endpoint/bpf.go:614]: We are executing the finalizers right below here, looks to me that the right way to fix this is to shift the code block in question to a finalizer that would then be called already in the right context. Currenty the location of the code block does not return a finalizer function, so some refactoring would be needed on that regard.

**Review by jrajahalme — COMMENTED** [review]
Looks like shifting the contested code block to a finalizer would be the right thing to do.

**Comment by jrajahalme** [comment]
> Looks like shifting the contested code block to a finalizer would be the right thing to do.

@christarazi Or is the issue that `DefaultDNSProxy.GetRules()` should not be called while the *endpoint* is locked?

**Review by jrajahalme — APPROVED** [review]
OK, read up on the issue, which boils down to that nowadays we should not take IPCache lock while holding an endpoint lock. As such this fix is correct, but I'd like the new comment to clearly state the correct locking order (since GetDNSRules() needs to take IP Cache lock, it needs to be called without holding an endpoint lock), and that this is not called more frequently than necessary.

**Comment by christarazi** [comment]
> > Looks like shifting the contested code block to a finalizer would be the right thing to do.
> 
> @christarazi Or is the issue that `DefaultDNSProxy.GetRules()` should not be called while the _endpoint_ is locked?

@jrajahalme Yes I believe the issue is calling `DefaultDNSProxy.GetRules()` while the endpoint is locked is the main issue, as that issues invokes an ipcache read operation. Given that the ipcache is already locked [1] while handling `removeLabelsFromIPs`, these are the 3 actors involved in the deadlock.

[1]: https://github.com/cilium/cilium/issues/20915#issuecomment-1433268691

**Comment by christarazi** [comment]
> Given the nature of the [k8s-1.16-kernel-4.19 failures](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-kernel-4.19/21/), we'll need to dig closely through to understand whether there could be a DNS availability impact with these new changes. At a glance I'm not really sure.

I took a look at the failures and they seem to be unrelated as the DNS look (`dig +short kubernetes.default.svc.cluster.local @10.96.0.10`) was failed for some reason. I could not find any info on why it was failing; the CEP existed, ipcache entry plumbed, service backends plumbed into Cilium, etc. The root issue seems to boil down to [this](https://github.com/cilium/cilium/issues/23845) flake, but can't tell why it occurred.

**Comment by christarazi** [comment]
/test-1.16-4.19

**Comment by aanm** [comment]
/test-1.16-4.19

**Comment by squeed** [comment]
Marking as ready for review, as this seems to have reached consensus (and tests are passing). Plus Chris is out.

**Comment by squeed** [comment]
GKE [failed on deleting the cilium-test namespace](https://github.com/cilium/cilium/actions/runs/4200699587/jobs/7286990604), which shouldn't have been caused by this PR. The pods were successfully deleted; just the Namespace object itself was the issue.

**Comment by joestringer** [comment]
I've reassessed the affected branches and traced the bug introduction to https://github.com/cilium/cilium/pull/18996 .

**Comment by squeed** [comment]
> @squeed Can you link to the known flake?

Sure, done. (I've been on previous projects that preferred not to create the breadcrumbs b/c it "spams" the flake issue).

**Comment by squeed** [comment]
to summarize: test-1.16-4.19 flake is #23845. gke flake is #22368. Marking this as ready-to-merge.
