### PR TITLE
connectivity: rework sniffer to execute tcpdump in background

### LINKED ISSUE #38643: CI: Cilium E2E Upgrade (ci-e2e-upgrade) - node-to-node-encryption: "Failed to execute tcpdump [...] command terminated with exit code 14"
https://github.com/cilium/cilium/actions/runs/14175754328/job/39710202809

```
  [-] Scenario [node-to-node-encryption/node-to-node-encryption]
  [.] Action [node-to-node-encryption/node-to-node-encryption/ping-ipv4: cilium-test-4/client-645b68dcf7-4ls4f (10.244.1.5) -> cilium-test-4/host-netns-vncpf (172.18.0.4:0)]
  [.] Action [node-to-node-encryption/node-to-node-encryption/ping-ipv4: cilium-test-4/host-netns-jcjpk (172.18.0.5) -> cilium-test-4/host-netns-vncpf (172.18.0.4:0)]
  [.] Action [node-to-node-encryption/node-to-node-encryption/curl-ipv4: cilium-test-4/host-netns-jcjpk (172.18.0.5) -> cilium-test-4/echo-other-node-6f459f56b9-72mrm (10.244.3.135:8080)]
  [.] Action [node-to-node-encryption/node-to-node-encryption/ping-ipv6: cilium-test-4/client-645b68dcf7-4ls4f (fd00:10:244:1::8031) -> cilium-test-4/host-netns-vncpf (fc00:c111::4:0)]
  [.] Action [node-to-node-encryption/node-to-node-encryption/ping-ipv6: cilium-test-4/host-netns-jcjpk (fc00:c111::5) -> cilium-test-4/host-netns-vncpf (fc00:c111::4:0)]
  [.] Action [node-to-node-encryption/node-to-node-encryption/curl-ipv6: cilium-test-4/host-netns-jcjpk (fc00:c111::5) -> cilium-test-4/echo-other-node-6f459f56b9-72mrm (fd00:10:244:3::8e9:8080)]
  🟥 Failed to execute tcpdump on cilium-test-4/host-netns-jcjpk (kind-worker2): command failed (pod=cilium-test-4/host-netns-jcjpk, container=): command terminated with exit code 14

...

❌ 1/21 tests failed (1/259 actions), 2 tests skipped, 0 scenarios skipped:
Test [node-to-node-encryption]:
  ❌ node-to-node-encryption/node-to-node-encryption/curl-ipv6: cilium-test-4/host-netns-jcjpk (fc00:c111::5) -> cilium-test-4/echo-other-node-6f459f56b9-72mrm (fd00:10:244:3::8e9:8080)
    ⛑️ The following owners are responsible for reliability of the testsuite: 
        - @cilium/sig-encryption (node-to-node-encryption)
        - @cilium/ci-structure (.github/workflows/tests-e2e-upgrade.yaml)

📋 Test Report [cilium-test-5]
❌ 1/21 tests failed (1/229 actions), 4 tests skipped, 0 scenarios skipped:
Test [client-egress-tls-sni]:
  ❌ client-egress-tls-sni/pod-to-world/https-to-one.one.one.one.-ipv4-2: cilium-test-5/client3-795488bf5-47fqv (10.244.0.107) -> one.one.one.one.-https (one.one.one.one.:443)
    ⛑️ The following owners are responsible for reliability of the testsuite: 
        - @cilium/proxy (pod-to-world)
        - @cilium/ci-structure (.github/workflows/tests-e2e-upgrade.yaml)
```

Logs: [logs_36473274235.zip](https://github.com/user-attachments/files/19547594/logs_36473274235.zip)
Features tested: [features-tested.zip](https://github.com/user-attachments/files/19547624/features-tested.zip)
Sysdump:
- [cilium-sysdump-15-20250331-160540.zip](https://github.com/user-attachments/files/19547626/cilium-sysdump-15-20250331-160540.zip)
- [cilium-sysdump-15-20250331-160626.zip](https://github.com/user-attachments/files/19547630/cilium-sysdump-15-20250331-160626.zip)
- [cilium-sysdump-15-final.zip](https://github.com/user-attachments/files/19547634/cilium-sysdump-15-final.zip)

### PR DESCRIPTION
**Pull request by smagnani96**
Please do refer to commit messages for a detailed explanation.
I'd love as many feedback as possible, given this ended up being a not so easy change 😅 

1st and 2nd commit are the major updates. Sometimes while re-reading them they do feel quite hacky, but haven't found a better way to implement that.
3rd commit `connectivity: limit tcpdump capture also for Assert mode` is a **Why not?**, definitively can go in a different PR (or even cancel it if I missed the reason why we shouldn't do that).

Fixes: #38643

### CODE REVIEW

File: cilium-cli/connectivity/sniff/sniffer.go [hunk 1]
```diff
@@ -25,17 +25,105 @@ const (
...
+		sleep 1
+		grep -q "listening on {{ .Iface }}" {{ .LogPath }} && exit 0
+		kill -0 $pid 2>/dev/null || {
+			wait $pid
+			exit $?
+		}
+	done
+
+	# Process is running but did not receive confirmation, kill and exit.
+	kill -2 $pid 2>/dev/null
```
Comment (giorio94) [inline cilium-cli/connectivity/sniff/sniffer.go]: Nit. Any reason for using `SIGINT` vs `SIGKILL`?

File: cilium-cli/connectivity/sniff/sniffer.go [hunk 2]
```diff
@@ -25,17 +25,105 @@ const (
...
+
+	// Command executed to start the remote tcpdump in background inside a pod.
+	//
+	// We send tcpdump output to a file inside the pod rather than stdout,
+	// to avoid GH Issue #38643: tcpdump failing with error 14 due to one of
+	// its output streams not being available anymore.
+	// (tcpdump: Unable to write output: Broken pipe)
+	//
+	// Runs silently: succeeds if tcpdump is active ("listening on <iface>"),
+	// else fails with its error code. Includes `timeout 30` to prevent orphaned
```
Comment (giorio94) [inline cilium-cli/connectivity/sniff/sniffer.go]: Nit. The reference to `timeout 30` looks incorrect.

File: cilium-cli/connectivity/sniff/sniffer.go [hunk 3]
```diff
@@ -25,17 +25,105 @@ const (
...
+		kill -2 $pid 2>/dev/null
+	fi
+
+	# Confirm that process has been stopped and exit with success code.
+	for i in $(seq 1 {{ .WaitSeconds }}); do
+		if ! kill -0 $pid 2>/dev/null; then
+			exit 0
+		fi
+		sleep 1
+	done
```
Comment (giorio94) [inline cilium-cli/connectivity/sniff/sniffer.go]: Any reason for not calling `wait` as for the start case, and let the command context handle the timeout?

File: cilium-cli/connectivity/sniff/sniffer.go [hunk 4]
```diff
@@ -25,17 +25,105 @@ const (
...
 	// leveraged as a sanity check to verify that the filter is correct.
 	ModeSanity Mode = "sanity"
+
+	// Max wait time for tcpdump to start/stop in remote shell.
+	sniffScriptTimeout = 10 * time.Second
+	// Max timeout before aborting k8s connection in Start/Stop; must exceed sniffScriptTimeout.
+	sniffConnectionTimeout = sniffScriptTimeout + 5*time.Second
+	// Max remote sniffer runtime to prevent lingering processes in the pod.
+	// NOTE: too low may kill tcpdump while test is running.
+	sniffKillTimeout = sniffConnectionTimeout * 4
```
Comment (giorio94) [inline cilium-cli/connectivity/sniff/sniffer.go:35]: This is problematic, as there are tests that may require a long-running tcpdump capture, e.g., to verify that certain packets are not seen during the entire connectivity suite execution. I general I don't think it is possible to reliably define a maximum duration of the capture.

File: cilium-cli/connectivity/sniff/sniffer.go [hunk 5]
```diff
@@ -158,32 +234,40 @@ func (sniffer *Sniffer) Validate(ctx context.Context, a *check.Action) {
...
 		}
-		return err
 
-	default:
-		ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
+		// Finally wrap the resulting command.
+		sniffer.stopCmd = append([]string{"sh", "-c"}, buf.String())
+
+		// Context with timeout for stopping tcpdump.
+		// NOTE: Context is not passed anymore to to this function to avoid premature cancellation.
```
Comment (giorio94) [inline cilium-cli/connectivity/sniff/sniffer.go]: Nit. `s/to to/to/`

File: cilium-cli/connectivity/sniff/sniffer.go [hunk 6]
```diff
@@ -73,13 +73,22 @@ const (
...
 
 	// Command executed to stop the remote tcpdump inside a pod.
+	// On successful sniffer stop, prints captured packets and their total count to stdout.
 	sniffScriptStopTmpl = `
 {
+	# Print captured packets and their count to stdout.
+	# Redirect stderr to /dev/null, as tcpdump logs to stderr.
+	report() {
+		tcpdump -r {{ .DumpPath }} --count 2>/dev/null || true
+		tcpdump -r {{ .DumpPath }}         2>/dev/null || true
```
Comment (giorio94) [inline cilium-cli/connectivity/sniff/sniffer.go]: Nit. Could be worth adding `-n` to avoid IP to name conversions (I know that it was already missing before).

File: cilium-cli/connectivity/sniff/sniffer.go [hunk 7]
```diff
@@ -25,17 +25,105 @@ const (
...
+`
+
+	// Command executed to stop the remote tcpdump inside a pod.
+	sniffScriptStopTmpl = `
+{
+	# Ignore signals received when killing tcpdump.
+	trap '' TERM INT HUP
+
+	# Exit with success code in case tcpdump is not running.
+	if [ ! -f "{{ .PidPath }}" ]; then
```
Comment (giorio94) [inline cilium-cli/connectivity/sniff/sniffer.go]: I assume this should be an error, as nothing should have deleted the PID file.

File: cilium-cli/connectivity/sniff/sniffer.go [hunk 8]
```diff
@@ -197,38 +208,25 @@ func Sniff(ctx context.Context, name string, target *check.Pod,
...
+		a.Failf("Captured unexpected packets (count=%s)", strings.TrimRight(count, "\n\r"))
 		a.Infof("Capture executed on %s (%s): %s", sniffer.target.String(), sniffer.target.NodeName(), strings.Join(sniffer.cmd, " "))
-
-		cmd := []string{"/bin/sh", "-c", fmt.Sprintf("tcpdump -r %s 2>/dev/null", sniffer.dumpPath)}
-		out, err := sniffer.target.K8sClient.ExecInPod(ctx, sniffer.target.Pod.Namespace, sniffer.target.Pod.Name, "", cmd)
-		if err != nil {
-			a.Fatalf("Failed to retrieve tcpdump output on %s (%s): %s", sniffer.target.String(), sniffer.target.NodeName(), err)
-		}
-		a.Infof("Captured packets:\n%s", out.String())
+		a.Infof("Captured packets:\n%s", sniffer.out.String())
```
Comment (giorio94) [inline cilium-cli/connectivity/sniff/sniffer.go:233]: Nit. Should probably trim the first line from the output, that contains the count of the packets.

File: cilium-cli/connectivity/sniff/sniffer.go [hunk 9]
```diff
@@ -197,38 +208,25 @@ func Sniff(ctx context.Context, name string, target *check.Pod,
...
 	// Stop tcpdump if needed.
 	if err := sniffer.stop(); err != nil {
 		a.Fatal(err)
 	}
 
-	// Redirect stderr to /dev/null, as tcpdump logs to stderr, and ExecInPod
-	// will return an error if any char is written to stderr. Anyway, the count
-	// is written to stdout.
-	cmd := []string{"/bin/sh", "-c", fmt.Sprintf("tcpdump -r %s --count 2>/dev/null", sniffer.dumpPath)}
-	count, err := sniffer.target.K8sClient.ExecInPod(ctx, sniffer.target.Pod.Namespace, sniffer.target.Pod.Name, "", cmd)
```
Comment (giorio94) [inline cilium-cli/connectivity/sniff/sniffer.go:134]: It is curious that this one never failed, while the issue was always with the startup of tcpdump. So it is probably not strictly a stdout/stderr issue, but more a problem with some tcpdump expectations there.

**Review by giorio94 — COMMENTED** [review]
Nice! A few drive-by comments.

**Comment by gentoo-root** [comment]
ci-e2e-upgrade didn't fail with the tcpdump error in [22 attempts](https://github.com/cilium/cilium/actions/runs/16510556706/attempts/22). Some tests are unsuccessful because of other flakes and quay outage.

I'd say it's stable: the debug pull request https://github.com/cilium/cilium/pull/40692/ can reproduce it after 3–4 retries, while this one survived 22 in a row.

File: cilium-cli/connectivity/sniff/sniffer.go (hunk 4 above)
Comment (gentoo-root) [reply cilium-cli/connectivity/sniff/sniffer.go:35]: But we do have timeouts on all our tests in the CI (big ones, like 1 hour). If we already have expectations about the duration of the entire test, can we set the tcpdump timeout to that value?

Also, could you please point me at those tests (or how to find them) that run tcpdump for extended periods? We could set different timeouts for short and long tests.

As we run tcpdump in the background, there is no reliable way to kill it after the test finishes, that's why we need those timeouts as a robustness measure.

File: cilium-cli/connectivity/sniff/sniffer.go (hunk 2 above)
Comment (gentoo-root) [reply cilium-cli/connectivity/sniff/sniffer.go]: Yeah, thanks, looks like it's 60, according to the calculation above.

File: cilium-cli/connectivity/sniff/sniffer.go (hunk 1 above)
Comment (gentoo-root) [reply cilium-cli/connectivity/sniff/sniffer.go]: Good point, I'd suggest SIGKILL too, because tcpdump returns exit code 0 when killed with SIGINT, and we don't want to return 0 (success) in this case.

File: cilium-cli/connectivity/sniff/sniffer.go (hunk 3 above)
Comment (gentoo-root) [reply cilium-cli/connectivity/sniff/sniffer.go]: `wait` doesn't have a built-in timeout. You can't run `timeout 30 wait $pid` either, because `wait` is a built-in bash command, but `timeout` is an external one (an executable).

File: cilium-cli/connectivity/sniff/sniffer.go [hunk 10]
```diff
@@ -25,17 +25,105 @@ const (
...
+
+	# Confirm that process has been stopped and exit with success code.
+	for i in $(seq 1 {{ .WaitSeconds }}); do
+		if ! kill -0 $pid 2>/dev/null; then
+			exit 0
+		fi
+		sleep 1
+	done
+
+	# Process still exists, exit with error.
```
Comment (gentoo-root) [inline cilium-cli/connectivity/sniff/sniffer.go:116]: We can send a SIGKILL at this point, just in case.

**Review by gentoo-root — COMMENTED** [review]
Simone is on vacation, I'm taking it over for the while.

File: cilium-cli/connectivity/sniff/sniffer.go (hunk 8 above)
Comment (gentoo-root) [reply cilium-cli/connectivity/sniff/sniffer.go:233]: I think it's alright as is. `count` has been read with `ReadString()`, which has advanced the position in the buffer, so `String()` will return the remaining stuff (the packets).

File: cilium-cli/connectivity/sniff/sniffer.go (hunk 4 above)
Comment (gentoo-root) [reply cilium-cli/connectivity/sniff/sniffer.go:35]: > to verify that certain packets are not seen during the entire connectivity suite execution

One that comes to my mind is the one that looks for unencrypted leaks, but it's based on bpftrace, not tcpdump.

File: cilium-cli/connectivity/sniff/sniffer.go [hunk 11]
```diff
@@ -25,17 +25,116 @@ const (
...
+	# Exit with success code in case tcpdump is not running.
+	if [ ! -f "{{ .PidPath }}" ]; then
+		report
+		exit 0
+	fi
+	
+	pid=$(cat {{ .PidPath }} )
+
+	# Kill the process if it is still running.
+	if kill -0 $pid 2>/dev/null; then
```
Comment (gentoo-root) [inline cilium-cli/connectivity/sniff/sniffer.go:98]: I think we should error out if it's no longer running. If @giorio94 is [right](https://github.com/cilium/cilium/pull/40487#discussion_r2231523844), this will allow us to detect long-running tcpdump tests that would kill tcpdump on timeout, before the test finishes.

File: cilium-cli/connectivity/sniff/sniffer.go (hunk 8 above)
Comment (giorio94) [reply cilium-cli/connectivity/sniff/sniffer.go:233]: Ah, right, I had missed this was acting against a buffer, which then gets consumed.

File: cilium-cli/connectivity/sniff/sniffer.go (hunk 3 above)
Comment (giorio94) [reply cilium-cli/connectivity/sniff/sniffer.go]: Yeah, my point is that we could theoretically just block forever in this script, and let the caller (i.e., `ExecInPod`) handle the timeout via its context. But the current approach works as well.

File: cilium-cli/connectivity/sniff/sniffer.go (hunk 4 above)
Comment (pchaigno) [reply cilium-cli/connectivity/sniff/sniffer.go:35]: > One that comes to my mind is the one that looks for unencrypted leaks, but it's based on bpftrace, not tcpdump.

The current timeout is at 1 min. Won't that be way too low for the tests you mention?

File: cilium-cli/connectivity/sniff/sniffer.go [hunk 12]
```diff
@@ -25,17 +25,111 @@ const (
...
+
+	// Command executed to start the remote tcpdump in background inside a pod.
+	//
+	// We send tcpdump output to a file inside the pod rather than stdout,
+	// to avoid GH Issue #38643: tcpdump failing with error 14 due to one of
+	// its output streams not being available anymore.
+	// (tcpdump: Unable to write output: Broken pipe)
+	//
+	// Runs silently: succeeds if tcpdump is active ("listening on <iface>"),
+	// else fails with its error code. Includes `timeout 60` to prevent orphaned
```
Comment (pchaigno) [inline cilium-cli/connectivity/sniff/sniffer.go:45]: Nit in case of repush:
```suggestion
	// else fails with its error code. Includes `timeout` to prevent orphaned
```
given the timeout is not hardcoded here.

File: cilium-cli/connectivity/sniff/sniffer.go [hunk 13]
```diff
@@ -163,12 +163,13 @@ func Sniff(ctx context.Context, name string, target *check.Pod,
...
-		// them to be seen (i.e., in sanity mode). Otherwise, better to capture
-		// them all to provide more informative debug messages on failures.
-		sanity = "-c 1"
+	// Limit packet capture to avoid large files: 1 in sanity mode, 1000 in assert mode.
+	var count int
+	switch sniffer.mode {
+	case ModeSanity:
+		count = 1
+	case ModeAssert:
+		count = 1000
```
Comment (pchaigno) [inline cilium-cli/connectivity/sniff/sniffer.go:172]: IMO, even 100 would be largely enough. I wouldn't delay the PR on this though.

**Review by pchaigno — APPROVED** [review]
LGTM! Nice commit history! :pray:

File: cilium-cli/connectivity/sniff/sniffer.go (hunk 9 above)
Comment (gentoo-root) [reply cilium-cli/connectivity/sniff/sniffer.go:134]: A hypothesis, after looking at a log with my [debug prints](https://github.com/cilium/cilium/pull/40692):

```
2025-07-25T20:56:56.3826162Z XXX: stdout err EOF, sniffer 0xc00091c200
2025-07-25T20:56:56.4852893Z XXX: tcpdump is listening, sniffer 0xc00091c200
2025-07-25T20:56:56.4853573Z XXX: leaving Sniff, sniffer 0xc00091c200
2025-07-25T20:56:56.5962425Z XXX: stopAndWait, sniffer 0xc00091c200
2025-07-25T20:56:56.5963731Z XXX: sniffer.cancel() 0xc00091c200
2025-07-25T20:56:56.6225101Z 
2025-07-25T20:56:56.6228007Z XXX: sniffer 0xc00091c200 exited with err command failed (pod=cilium-test-3/host-netns-2stxb, container=): command terminated with exit code 14
2025-07-25T20:56:56.6232855Z XXX: sniffer.exited 0xc00091c200 after cancel, err command failed (pod=cilium-test-3/host-netns-2stxb, container=): command terminated with exit code 14
2025-07-25T20:56:56.6234036Z XXX: leaving stopAndWait, sniffer 0xc00091c200
```

So, `sniffer.cancel()` canceled `cmdctx`, and **maybe** it first closes the pipes, then kills the process. If tcpdump wrote something in the meantime, it would fail and exit with code 14 by itself, before it's killed.

That also explains why we never fail with error 14 when reading the pcap.

File: cilium-cli/connectivity/sniff/sniffer.go (hunk 4 above)
Comment (gentoo-root) [reply cilium-cli/connectivity/sniff/sniffer.go:35]: The CI seems to pass with this timeout. I'd keep it small wherever it works, because some tests spawn multiple sniffers. If we find some long-running test, we can put a custom timeout for that test.

File: cilium-cli/connectivity/sniff/sniffer.go [hunk 14]
```diff
@@ -25,17 +25,122 @@ const (
...
+		exit 199
+	fi
+
+	pid=$(cat {{ .PidPath }} )
+
+	# Kill the process if it is still running.
+	# Return an error if tcpdump timed out before capturing any packets.
+	if kill -0 $pid 2>/dev/null; then
+		kill -2 $pid 2>/dev/null
+	elif [ "$(tcpdump -r {{ .DumpPath }} --count 2>/dev/null)" = "0 packets" ]; then
```
Comment (smagnani96) [inline cilium-cli/connectivity/sniff/sniffer.go:100]: @gentoo-root I believe this is incorrect for the ModeAssert where having `0 packets` is good.
Isn't this checked later in Go anyway?

Comment (gentoo-root) [reply cilium-cli/connectivity/sniff/sniffer.go:100]: The point is to error out if tcpdump exited prematurely. If it didn't collect any packets and exited, it means it may have missed some packets, so we better fail the test.

In ModeAssert, however, we expect that tcpdump survives until it's killed on line 99. We don't hit the check on line 100 if everything works properly. Only if tcpdump was running during the entire test, we can be sure that 0 packets is indeed 0 packets, and we return 0 on line 111 in this case. So it's all good.

Comment (smagnani96) [reply cilium-cli/connectivity/sniff/sniffer.go:100]: Nope, given we now have also `-c 1000` for ModeAssert.
Tcpdump might have already recorded 1000 packets and exited before our check here.
