### PR TITLE
endpoint: Place IngressIPs to endpoints map

### LINKED ISSUE #32980: Cilium does not send ICMPv6 NA for reserved:ingress endpoints
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

- Running an IPv6-only cluster with cilium in native routing mode, every pod gets a globally routable IP, masquerade is off.
- Enabled Ingress controller with an ingress pointing to an nginx pod. Upon testing, expected to see nginx test page, instead, envoy sends "upstream connect error or disconnect/reset before headers. reset reason: connection timeout"

I started debugging:

- Examined envoy logs. Confirmed that request from envoy to the upstream timed out
- Examined `hubble observe`. Saw packets in both directions between reserved:ingress IP and upstream IP

That's weird, where is the packet getting lost?

- Ran tcpdump on the upstream host. Saw packets in both directions
- Ran tcpdump on the envoy host. Only saw outgoing packets, no returning packets from upstream
- Ran `ip -6 neigh` and noticed that reserved:ingress IP was missing from list, but other endpoints were there
- Ran `ndisc6` on reserved:ingress IP, times out with no response

I did some digging in the code to see where this was happening. Looks like `bpf/lib/icmp6.h` is where cilium handles responding to NS requests with NA. Specifically at [line 311 in that file](https://github.com/cilium/cilium/blob/025fc0f68e68b0eb6b951445671988f890cb2cf7/bpf/lib/icmp6.h#L311) the program tries to look up an endpoint. For the reserved:ingress endpoint, I suspected it wasn't being found. I confirmed this with some debug prints.

I then looked into the implementation for the reserved:ingress endpoint, mainly stumbling across #28126. It looks like the reserved:ingress endpoint only exists to enforce policies, but no BPF things are done for the endpoint? I don't have a great understanding of how exactly this works, but perhaps that's why the icmp6.h can't find the reserved:ingress ep?

Cilium should respond to these NS requests for reserved:ingress as well.

### Cilium Version

1.15.5

This issue exists on 1.14 and 1.16 as well, and likely even earlier.

### Kernel Version

6.6.31

### Kubernetes Version

1.30.1

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jrajahalme**
Cilium agent manages Ingress endpoint for the purpose of policy generation for Cilium Ingress. The Ingress endpoint has IPs from the node's CIDR range like any other endpoint, but it does not have any representation at the bpf datapath, as it is only used for policy enforcement and for IP addressing at the Envoy proxy. Due to the lacking bpf datapath representation IPv6 ND does not currently work for the Ingress IPs, which causes IPv6 communication with backends not working.

Fix this by introducing minimal bpf datapath representation for the Ingress endpoint via Ingress endpoint entries in the lxcmap, which is used by the IPV6 ND implementation in the Cilium bpf datapath to enable ND advertisements to be sent when ND request for the Ingress IPv6 has been received.

A new endpoint flag ENDPOINT_F_ATHOSTNS is added to inform the datapath to deliver endpoint's traffic to the host stack, but for which ARP and IPv6 ND are still served by the bpf datapath due to the endpoint's IP being from the node's IP allocation CIDR range.

Fixes: #32980

```release-note
Ingress endpoint is now included in the lxcmap so that ARP and ND6 work for them.
```

### CODE REVIEW

File: pkg/endpoint/endpoint.go [hunk 1]
```diff
@@ -79,6 +79,7 @@ const (
 
 	// PropertySkipBPFPolicy will mark the endpoint to skip ebpf
 	// policy regeneration.
+	// Endpoint is still placed in the endpoints map  so that ARP and ND work.
```
Comment (tklauser) [inline pkg/endpoint/endpoint.go]: super nit:

```suggestion
	// Endpoint is still placed in the endpoints map so that ARP and ND work.
```

**Review by tklauser — APPROVED** [review]
LGTM, thanks.

FWIW, failing "Build commits" workflow should be fixed on rebase now that https://github.com/cilium/cilium/pull/35141 was merged.

**Comment by julianwiedmann** [comment]
could you explain a bit more what the Ingress IPs are? From my understanding these are somehow used by Envoy, and allocated from the PodCIDR? And there is a special identity (`ReservedIdentityIngress`) associated with them?

And from a BPF-routing perspective - I'd expect that these IPs reside in Host network namespace, and *not* in a normal pod (== veth pair) ?

**Comment by jrajahalme** [comment]
> could you explain a bit more what the Ingress IPs are? From my understanding these are somehow used by Envoy, and allocated from the PodCIDR? And there is a special identity (`ReservedIdentityIngress`) associated with them?
> 
> And from a BPF-routing perspective - I'd expect that these IPs reside in Host network namespace, and _not_ in a normal pod (== veth pair) ?

Simplest way of describing Ingress IPs is: IPs (IPv4 and IPv6) allocated from the PodCIDR range of the node that are used as the source addresses of traffic forwarded by Cilium Ingress (and GW API) in the node. There is no real/full Cilium endpoint with these addresses, so there is no BPF datapath (bpf_lxc) nor bpf policy maps for them. Cilium agent computes a policy for the special entity though, and sends it to Envoy so that Envoy can enforce policy on the traffic forwarded by Cilium Ingress (or GW API).

ARP table on the destination node would normally be updated due to the traffic being sent from Cilium Ingress, but if it is flushed for any reason, or for IPv6 ND, the node with these IPs may need to be able to respond to ARP/ND to recover the flushed/missing ARP/ND table entry on the destination node.

No process in the node is listening on these addresses, so ARP/ND is only relevant for getting reply packets back to the node.

**Comment by julianwiedmann** [comment]
> No process in the node is listening on these addresses, so ARP/ND is only relevant for getting reply packets back to the node.

So if a local pod would receive a connection by such an IngressIP, and attempts to send a reply - where should that reply get forwarded to? With the IngressIP now visible in the local endpoint map to `bpf_lxc`, the [relevant code](https://github.com/cilium/cilium/blob/1d2c6b661f724985e1165ee6ca50b6def5916c39/bpf/bpf_lxc.c#L1176) needs to understand whether the packet should be delivered (a) into another pod or (b) the host network namespace.

**Comment by jrajahalme** [comment]
> > No process in the node is listening on these addresses, so ARP/ND is only relevant for getting reply packets back to the node.
> 
> So if a local pod would receive a connection by such an IngressIP, and attempts to send a reply - where should that reply get forwarded to? With the IngressIP now visible in the local endpoint map to `bpf_lxc`, the [relevant code](https://github.com/cilium/cilium/blob/1d2c6b661f724985e1165ee6ca50b6def5916c39/bpf/bpf_lxc.c#L1176) needs to understand whether the reply should be delivered (a) into another pod or (b) to the host network namespace.

Are you saying that since the IngressIPs are now in the endpoints map, this lookup now succeeds and finds a non-null `ep`?:
```
		/* Lookup IPv4 address, this will return a match if:
		 *  - The destination IP address belongs to a local endpoint
		 *    managed by cilium
		 *  - The destination IP address is an IP address associated with the
		 *    host itself
		 *  - The destination IP address belongs to endpoint itself.
		 */
		ep = __lookup_ip4_endpoint(daddr);
```

The desired action would be to route to host. Envoy uses an `IP_TRANSPARENT` socket to open the connection to the destination, with the `IngressIP` as the source address. Therefore there is a host networking namespace socket open on the (return) address, and routing the traffic through the host stack would allow it be delivered to Envoy, due to iptables rules we already have for proxy redirect (reply) traffic.

**Comment by julianwiedmann** [comment]
> The desired action would be to route to host.

Then I think we'll need a bit more work, so the programs that handle a delivery to local endpoint (eg from-container, from-overlay) understand that they should let the packet pass through into hostns, and not attempt a delivery via [policy tailcall](https://github.com/cilium/cilium/blob/8c315f02f3be6278a77af279fd135ec9b26646c2/bpf/lib/maps.h#L41).

Right now that works by setting the `ENDPOINT_F_HOST` flag on the endpoint. But I'd actually want us to use two flags - one for "lives in hostns" (to drive the delivery), a second for "is a node IP" (to device whether BPF masq is needed).

**Comment by jrajahalme** [comment]
> > The desired action would be to route to host.
> 
> Then I think we'll need a bit more work, so the programs that handle a delivery to local endpoint (eg from-container, from-overlay) understand that they should let the packet pass through into hostns, and not attempt a delivery via [policy tailcall](https://github.com/cilium/cilium/blob/8c315f02f3be6278a77af279fd135ec9b26646c2/bpf/lib/maps.h#L41).
> 
> Right now that works by setting the `ENDPOINT_F_HOST` flag on the endpoint. But I'd actually want us to use two flags - one for "lives in hostns" (to drive the delivery mechanism), a second for "is a node IP" (to decide whether BPF masq is needed).

Right, the current `ENDPOINT_F_HOST` causes the neighbor request to be forwarded to the hostns without sending the ND advertisement, while for this we need the opposite. Currently this seems to work OK for IPv6 ND when the `ENDPOINT_F_HOST` flag is not set. Are you saying that we'd need another flag that triggers the same behavior as `ENDPOINT_F_HOST` elsewhere in the bpf datapath (`from-container`, `from-overlay`)?

**Comment by julianwiedmann** [comment]
> Right, the current `ENDPOINT_F_HOST` causes the neighbor request to be forwarded to the hostns without sending the ND advertisement, while for this we need the opposite.

You mean [this spot](https://github.com/cilium/cilium/blob/8c315f02f3be6278a77af279fd135ec9b26646c2/bpf/lib/icmp6.h#L314), correct? Makes sense. Note how it currently special-cases the IPv6-Router IP (which is *also* carved from the PodCIDR and lives in hostns, just like your IngressIP).

> Are you saying that we'd need another flag that triggers the same behavior as ENDPOINT_F_HOST elsewhere in the bpf datapath (from-container, from-overlay)?

My suggestion would be
* `s/ENDPOINT_F_HOST/ENDPOINT_F_HOSTNS`, and use that whenever the packet needs to be delivered into host netns.
* add a new `ENDPOINT_F_NODE_IP`. And use that for the ICMPv6 case you're trying to fix, and the [BPF masq](https://github.com/cilium/cilium/blob/8c315f02f3be6278a77af279fd135ec9b26646c2/bpf/lib/nat.h#L642) case. Potentially more :).

File: pkg/endpoint/bpf.go [hunk 2]
```diff
@@ -396,6 +396,16 @@ func (e *Endpoint) regenerateBPF(regenContext *regenerationContext) (revnum uint
...
+		// Ingress endpoint needs entries in the endpoints map so that IPv6 ND works for it.
+		if e.isProperty(PropertyAtHostNS) {
+			stats.mapSync.Start()
+			err = lxcmap.WriteEndpoint(datapathRegenCtxt.epInfoCache)
+			stats.mapSync.End(err == nil)
+			if err != nil {
+				return 0, fmt.Errorf("Exposing endpoint in endpoints BPF map failed: %w", err)
+			}
+		}
+
```
Comment (julianwiedmann) [inline pkg/endpoint/bpf.go]: Maybe update the comment, since this isn't really specific to IPv6 ND anymore ?

This code path looks completely tuned to what we currently need for the Ingress endpoint :smile:. But abstracting it is a future problem ...

File: bpf/lib/common.h [hunk 3]
```diff
@@ -325,7 +325,9 @@ struct tunnel_value {
 	__u16 pad;
 } __packed;
 
-#define ENDPOINT_F_HOST		1 /* Special endpoint representing local host */
+#define ENDPOINT_F_HOST			1 /* Special endpoint representing local host */
+#define ENDPOINT_F_ATHOSTNS		2 /* Endpoint located at the host networking namespace */
+#define ENDPOINT_MASK_HOST_DELIVERY	(ENDPOINT_F_HOST | ENDPOINT_F_ATHOSTNS)
```
Comment (julianwiedmann) [inline bpf/lib/common.h:330]: Nice, I like the mask approach for compatibility!

Future task will be to switch over the existing `cilium_host` endpoints to set `ENDPOINT_F_ATHOSTNS`, but not `ENDPOINT_F_HOST`. And then remove the special handling in `icmp6.h`.

**Review by julianwiedmann — COMMENTED** [review]
Thank you Jarno, looks good! Some minor remarks below.

I'd suggest to split the change into two patches:
1. introduce `ENDPOINT_F_ATHOSTNS`, `ENDPOINT_MASK_HOST_DELIVERY` etc and motivate why it's needed.
2. switch the Ingress endpoint to set `ENDPOINT_F_ATHOSTNS`.

Besides that, could you please update the PR / patch description to reflect the latest changes? Right now it's still very much focused on the IPv6 ND problem ...

File: pkg/endpoint/bpf.go (hunk 2 above)
Comment (jrajahalme) [reply pkg/endpoint/bpf.go]: Updated to:
```
	// Ingress endpoint needs entries in the endpoints map so that the return traffic,
	// ARP, and IPv6 ND are delivered to the host stack in all datapath configurations.
```

**Comment by jrajahalme** [comment]
@julianwiedmann Split into two commits, updated comments and description.

**Review by julianwiedmann — APPROVED** [review]
ty Jarno, looks good! We should also ping https://github.com/cilium/cilium/issues/35277 about testing once this is merged.

**Comment by julianwiedmann** [comment]
Adding backport label, in particular as this is needed to unblock additional fixes (https://github.com/cilium/cilium/pull/35098, https://github.com/cilium/cilium/pull/35418).
