### PR TITLE
identity: Fix user-space security identity lookup in cluster mesh

### LINKED ISSUE #13076: Hubble fails to resolve identities across a cluster mesh.
## Bug report

After deploying Hubble (in distributed mode) on a mesh of three clusters (`kvstore: etcd`, `identity-allocation-mode: kvstore`), the Cilium agents are generating a huge amount of logs like the following one:

```
cilium-agent level=warning msg="failed to resolve identity" error="identity 185344 not found" identity=185344 subsys=hubble
```

I tried to run `cilium get identity 185344` on the cluster where the log message originated and got a `404` error. Then I tried running the same on another cluster of the mesh and got a successful result (probably because the workload is running on that cluster).

**General Information**

- Cilium version (run `cilium version`)

```
# cilium version
Client: 1.8.2 aa42034f0 2020-07-23T15:02:39-07:00 go version go1.14.6 linux/amd64
Daemon: 1.8.2 aa42034f0 2020-07-23T15:02:39-07:00 go version go1.14.6 linux/amd64
```

- Kernel version (run `uname -a`)

```
Linux vm-k8s-STAG-LD4-Z0-00-master-2 5.7.10-050710-generic #202007220834 SMP Wed Jul 22 08:52:23 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T21:54:15Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Link to relevant artifacts (policies, deployments scripts, ...)

N/A

- Generate and upload a system zip:

```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

1. Create a mesh of two or more clusters according to https://docs.cilium.io/en/v1.8/gettingstarted/clustermesh/.
2. Enable Hubble in distributed mode according to https://docs.cilium.io/en/v1.8/gettingstarted/hubble-enable/.

### PR DESCRIPTION
**Pull request by gandro**
When looking up a security identity (either by its numeric id or by
labels) in user-space (e.g. in Hubble or the API), we want to ensure to
also include identities owned by remote clusters in cluster mesh too.

Before this commit, `GetIdentities` function of the identity allocator
(e.g. used for `cilium identity list`) would return all global
identities (i.e. including the ones from remote clusters as well), while
`LookupIdentity{,ByID}` would only return identitiies found the main
kvstore, ignoring any attached remote kvstores. This commit

This fixes multiple missed annotations which can occur in cluster-mesh
setups:

  - Hubble failed to annotate identities from remote clusters (#13076).

  - While the API would list remote identities in `/v1/identities`,
    performing a lookup on identities from remote clusters via API would
    fail with a "not found error". This 404 could be observed in
    `cilium identity get <remote-id>` or in `cilium bpf policy get`.

  - DNS proxy logrecords would not have the destination endpoint labels
    populated.

  - The `CiliumEndpoint.Status.Policy` CRD field would not contain
    labels for identities for remote clusters (if CEP status updates
    were enabled).

Fixes: #13076

```release-note
Fix bug where Hubble and the Cilium CLI would fail to resolve security identities across a cluster mesh.
```

### CODE REVIEW

File: pkg/identity/cache/cache.go [hunk 1]
```diff
@@ -201,7 +201,8 @@ func (w *identityWatcher) stop() {
 
 // LookupIdentity looks up the identity by its labels but does not create it.
 // This function will first search through the local cache and fall back to
-// querying the kvstore.
+// querying all connected kvstores (first the main kvstore, followed by any
+// watched remote kvstores in clustermesh)
 func (m *CachingIdentityAllocator) LookupIdentity(ctx context.Context, lbls labels.Labels) *identity.Identity {
```
Comment (gandro) [inline pkg/identity/cache/cache.go:205]: Note to reviewers: While we surely want to fix the lookup in this function for the API to work correctly (any identity returned by `/v1/identities` should also be fetchable via labels), the only non-API call site (outside of unit tests) of this function is in the IPCache:

https://github.com/cilium/cilium/blob/3a49c6c53dce1a768756f76b1c29e38c65e7d54a/pkg/ipcache/cidr.go#L118

IPCache is performing a lookup on CIDR labels. I don't think we want to send that lookup to remote kvstores (since CIDR identies are always local), so maybe we have to introduce an additional lookup function for the IPCache usecase? Unfortunatley I'm not too familiar with local identity management, so feedback welcome.

**Comment by gandro** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]
LGTM except for what we discussed on Zoom

**Comment by gandro** [comment]
Pushed the discussed change to not query remote backends in order avoid accidental DDoS. We now only check the remote caches. [Diff of change since approval](https://github.com/cilium/cilium/compare/4d2ed3b04d2218cdce540551d63d2f270365ad18..b2ea9104f16f49f1648751a2e17eb113e8b7e7bb)

**Comment by gandro** [comment]
test-me-please

File: pkg/identity/cache/cache.go (hunk 1 above)
Comment (joestringer) [reply pkg/identity/cache/cache.go:205]: Yeah, CIDR identities are purely local to the agent (not even shared across the cluster), so we should follow up to change the lookup function to reflect this usage.

**Review by joestringer — APPROVED** [review]
