### PR TITLE
wireguard: respect underlay-protocol for peer endpoint selection

### LINKED ISSUE #44560: WireGuard peer endpoint ignores underlay-protocol=ipv6 in dual-stack clusters
### What happened?

When running Cilium 1.19.1 in **tunnel mode** (Geneve) with `underlay-protocol: ipv6` and `encryption.enabled: true` (WireGuard) on a **dual-stack cluster** where nodes can only reach each other via IPv6 (IPv4 addresses are private/unreachable across nodes), WireGuard peer endpoints are always set to the IPv4 node address. This causes WireGuard handshakes to fail and **all cross-node pod-to-pod traffic is silently dropped**.

### Root Cause

In `pkg/wireguard/agent/agent.go`, the `updatePeer()` function unconditionally prefers IPv4 for WireGuard peer endpoints:

```go
ep := ""
if a.config.EnableIPv4 && nodeIPv4 != nil {
    ep = net.JoinHostPort(nodeIPv4.String(), strconv.Itoa(types.ListenPort))
} else if a.config.EnableIPv6 && nodeIPv6 != nil {
    ep = net.JoinHostPort(nodeIPv6.String(), strconv.Itoa(types.ListenPort))
} else {
    return fmt.Errorf("missing node IP for node %q", nodeName)
}
```

When `enable-ipv4: true` and the node has an IPv4 InternalIP (even a private/unreachable one), WireGuard always selects IPv4 for the peer endpoint regardless of `underlay-protocol: ipv6`.

The `underlay-protocol` setting correctly influences Geneve tunnel endpoint selection (via PR #40324 / `GetCiliumEndpointNodeIP()`), but the WireGuard agent has no equivalent check.

### Evidence

WireGuard debug info from the control plane node shows:

```
peer: 7tnF...
  endpoint: 192.168.7.200:51871    ← private IPv4, unreachable from OCI
  latest handshake: 0001-01-01T00:00:00.000Z   ← never completed
  transfer: 0 B received, 2080584 B sent

peer: 2d9V...
  endpoint: 10.0.0.3:51871         ← private IPv4, unreachable from OCI
  latest handshake: 0001-01-01T00:00:00.000Z   ← never completed
  transfer: 0 B received, 196100 B sent
```

`cilium-health status` confirms: 1/3 nodes reachable (localhost only).

Meanwhile, the Geneve tunnel endpoints correctly use IPv6 (visible in BPF ipcache):
```
10.244.1.0/24 tunnelendpoint=2a01:e11:2440:2430:... flags=hastunnel,ipv6tunnel
```

### Topology

- 3 nodes: 1 OCI cloud (ARM64), 2 edge baremetal workers (AMD64)
- All nodes connected via globally routable IPv6
- IPv4 addresses: OCI uses VCN private (`10.0.10.x`), edge nodes use LAN private (`192.168.7.x`, `10.0.0.x`)
- IPv4 is NOT routable between cloud and edge nodes
- Tunnel mode: Geneve over IPv6 underlay
- Pod networking: dual-stack (IPv4 + IPv6)

### Expected behavior

When `underlay-protocol: ipv6` is set, WireGuard should use IPv6 node addresses for peer endpoints, consistent with how Geneve tunnel endpoints are selected.

### Proposed fix

Check the underlay protocol configuration in `updatePeer()` before selecting the endpoint address family:

```go
ep := ""
underlayIPv6 := a.config.TunnelingEnabled && a.config.UnderlayProtocol == tunnel.IPv6
if underlayIPv6 && a.config.EnableIPv6 && nodeIPv6 != nil {
    ep = net.JoinHostPort(nodeIPv6.String(), strconv.Itoa(types.ListenPort))
} else if a.config.EnableIPv4 && nodeIPv4 != nil {
    ep = net.JoinHostPort(nodeIPv4.String(), strconv.Itoa(types.ListenPort))
} else if a.config.EnableIPv6 && nodeIPv6 != nil {
    ep = net.JoinHostPort(nodeIPv6.String(), strconv.Itoa(types.ListenPort))
} else {
    return fmt.Errorf("missing node IP for node %q", nodeName)
}
```

### CI test gap

The existing CI config #29 (dual-stack + IPv6 underlay + WireGuard) runs on a Kind cluster where IPv4 is fully routable between nodes via the Docker bridge network. This means WireGuard successfully uses IPv4 endpoints and the bug is not detected. Config #33 (IPv6-only + WireGuard) tests the IPv6-only case but without dual-stack pods.

No test covers: **dual-stack pods + IPv6 underlay + WireGuard + IPv4 NOT routable between nodes**.

### Cilium version

```
Cilium version: 1.19.1 (v1.19.1-d0d0c879)
Kernel: 6.18.5-talos (control plane), 6.18.13-arch1-1 (edge workers)
Kubernetes: v1.35.0
OS: Talos Linux v1.12.2
```

### Relevant PRs

- #40051 — Fixed BPF datapath to encrypt IPv6 overlay traffic with WireGuard (does NOT fix `updatePeer()`)
- #40324 — Fixed Geneve tunnel endpoints for dual-stack + IPv6 underlay (does NOT fix WireGuard endpoints)

### Helm values (relevant subset)

```yaml
ipv4.enabled: true
ipv6.enabled: true
routingMode: tunnel
tunnelProtocol: geneve
underlayProtocol: ipv6
encryption.enabled: true
encryption.type: wireguard
```

/label area/wireguard area/encryption

### PR DESCRIPTION
**Pull request by tibrezus**
## Summary

Fixes #44560

WireGuard peer endpoints now respect the `underlay-protocol=ipv6` setting in dual-stack clusters. When tunneling is enabled with IPv6 underlay, WireGuard will use IPv6 node addresses for peer endpoints instead of unconditionally preferring IPv4.

This aligns WireGuard behavior with Geneve tunnel endpoint selection introduced in #40324.

/cc @julianwiedmann

```release-note
WireGuard now respects the `underlay-protocol=ipv6` setting when selecting peer endpoints in dual-stack clusters with IPv6 underlay, fixing connectivity issues where IPv4 was incorrectly used despite being unreachable across nodes.
```

### CODE REVIEW

**Comment by tibrezus** [comment]
## Validation Results - Custom CI Image Testing

Tested PR with custom CI images from commit `19a6375c38743d110ea5c84f7d358e9f77152455`:

**Images Used**:
- `quay.io/cilium/cilium-ci:19a6375c38743d110ea5c84f7d358e9f77152455`
- `quay.io/cilium/operator-generic-ci:19a6375c38743d110ea5c84f7d358e9f77152455`

**Environment**: 
- Dual-stack cluster (IPv4 + IPv6 pods)
- IPv6-only underlay (IPv4 NOT routable between nodes)
- WireGuard encryption enabled
- Geneve tunnel mode

### WireGuard Peer Endpoints (Issue Fixed)

**Before PR**: WireGuard peers failed to establish (tried unreachable IPv4)

**After PR**: 
```
Encryption: Wireguard [cilium_wg0, port: 51871, peers: 1]
Peer endpoint: <edge-worker-ipv6>:51871 (IPv6 selected, not IPv4)
```

### Evidence: IPv6 Underlay Working

**1. WireGuard Peers Using IPv6 Endpoints**:
```
$ kubectl exec -n kube-system cilium-<pod> -- wg show
interface: cilium_wg0
  listening port: 51871
peer: <peer-public-key>
  endpoint: <edge-worker-ipv6>:51871
  allowed ips: fd00:10:244:1::/64, 10.244.1.0/24
  latest handshake: 1 minute ago
```

**2. Cross-Node Ping Test (IPv6 Pod Addresses)**:
```
$ kubectl exec -n <namespace> <pod> -- ping -c 100 <remote-pod-ipv6>
100 packets transmitted, 100 received, 0% packet loss
rtt min/avg/max/mdev = 7.851/8.339/9.103/0.207 ms
```

**3. WireGuard Tunnel Traffic**:
```
$ kubectl exec -n kube-system cilium-<pod> -- cilium-dbg bpf tunnel list
TUNNEL        VALUE
<remote-ipv6> 1 (IPv6 endpoint, not IPv4)
```

**4. Pod-to-Pod Connectivity Across Nodes**:
```
$ kubectl exec -n <namespace> <pod-edge> -- ping -c 3 <pod-control-plane-ipv6>
3 packets transmitted, 3 received, 0% packet loss
rtt min/avg/max/mdev = 7.996/8.020/8.064/0.030 ms
```

All traffic encrypted through `cilium_wg0` interface with IPv6 underlay.


### Conclusion

PR #44629 successfully fixes the WireGuard IPv6 underlay endpoint selection issue.

WireGuard peers now correctly use IPv6 endpoints when `underlay-protocol=ipv6` is configured, enabling full cross-node connectivity in dual-stack clusters where only IPv6 is routable.

**Comment by rgo3** [comment]
Nice catch indeed @tibrezus. I guess the connectivity tests don't catch this even though we have a wireguard [config with ipv6](https://github.com/cilium/cilium/blob/2b73b2ce9ba86a682037c0156324b7be3ba2529d/.github/actions/e2e/wireguard.yaml#L71) underlay because ipv4 stays routable.

Could you add a unit test for these changes?

**Comment by tibrezus** [comment]
I added `TestAgent_PeerEndpointSelection` as a new test rather than extending `TestAgent_PeerConfig` or `TestAgent_AllowedIPsRestoration` because:
 - **Different concern** - The existing tests focus on `AllowedIPs` management, while this fix is about `peer.endpoint` selection. Mixing them would make the tests harder to reason about.
 - **No existing endpoint coverage** - The current tests never assert on `peer.endpoint`, so there was nothing to extend.

Is this approach acceptable, or would you prefer endpoint assertions integrated into the existing test flows? 
Happy to refactor if needed.

File: pkg/wireguard/agent/agent_test.go [hunk 1]
```diff
@@ -564,3 +565,181 @@ func TestAgent_AllowedIPsRestoration(t *testing.T) {
...
+
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			wgAgent, _ := newTestAgent(t.Context(), hivetest.Logger(t), newFakeWgClient(), tt.config)
+
+			err := wgAgent.updatePeer(k8s1NodeName, k8s1PubKey, tt.nodeIPv4, tt.nodeIPv6)
+
+			if tt.expectError {
+				require.Error(t, err)
+				require.Contains(t, err.Error(), "missing node IP")
```
Comment (rgo3) [inline pkg/wireguard/agent/agent_test.go]: I wouldn't hardcode the expected error string here. Just expecting an error if the node has no IPs should suffice

**Review by rgo3 — APPROVED** [review]
LGTM, assuming my inline comment will be addressed.

File: pkg/wireguard/agent/agent_test.go (hunk 1 above)
Comment (tibrezus) [reply pkg/wireguard/agent/agent_test.go]: Agree, change pushed.

**Comment by zealousGnu** [comment]
Broken because of hubble-relay? It would be really awesome if this bug was fixed.

**Comment by rgo3** [comment]
Seems to be pretty consistent although don't know how it could be related to the changes we introduce here. I can't find any issues about this either. So let's rebase on main and see if it disappears. If it does we can hopefully get this merged asap.

**Comment by tibrezus** [comment]
@rgo3 rebase done, seems e2e tests need manual trigger

**Comment by Artyop** [comment]
@julianwiedmann @tibrezus marked this backport as `backport/author` since v1.19 doesn't have the requirements for a smooth backport  
Attempted to fix it by pulling https://github.com/cilium/cilium/commit/4112e5b25886ae09ecd61b09828f5f5d768ec3cc & https://github.com/cilium/cilium/commit/532ec2dae7469d0e212a61abee1185a30c6e4455 but still had wireguard issue in v1.19 CI
