### PR TITLE
ci/gke: Fix Hubble Relay on GKE

### LINKED ISSUE #12452: CI: Suite-k8s-1.14.K8sHubbleTest Hubble Observe Test {L3/L4, L7} Flow (with hubble-relay)
Hubble-relay POD is in crashloop backoff in GKE.

```
/home/jenkins/workspace/Cilium-PR-K8s-GKE/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:461
hubble-relay was not able to get into ready state
Expected
    <*errors.errorString | 0xc0004946d0>: {
        s: "timed out waiting for pods with filter -l k8s-app=hubble-relay to be ready: 10m0s timeout expired",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-K8s-GKE/src/github.com/cilium/cilium/test/k8sT/hubble.go:124
```

```
07:02:45 STEP: cmd: kubectl describe pods -n cilium -l k8s-app=hubble-relay
Exitcode: 0 
Stdout:
 	 Name:           hubble-relay-54c5c9bb68-5tn79
	 Namespace:      cilium
	 Priority:       0
	 Node:           gke-cilium-ci-20-cilium-ci-20-8f0a9b36-t2nw/10.128.0.42
	 Start Time:     Tue, 07 Jul 2020 06:48:50 +0000
	 Labels:         k8s-app=hubble-relay
	                 pod-template-hash=54c5c9bb68
	 Annotations:    <none>
	 Status:         Running
	 IP:             10.44.1.12
	 IPs:            <none>
	 Controlled By:  ReplicaSet/hubble-relay-54c5c9bb68
	 Containers:
	   hubble-relay:
	     Container ID:  docker://7f1a2f34cf617269ae91b2de1c9ab9fc8337d9ee93ccf1a0140db4b1cc70dc3c
	     Image:         147.75.55.179/cilium/hubble-relay:d5946a267afd2a8f341542137bf4f9098702a0dd
	     Image ID:      docker-pullable://147.75.55.179/cilium/hubble-relay@sha256:f64c540b6c59b6889e383abac6972ef5fcd7784fce2e01357f6993b4c3edc661
	     Port:          4245/TCP
	     Host Port:     0/TCP
	     Command:
	       hubble-relay
	     Args:
	       serve
	       --peer-service=unix:///var/run/cilium/hubble.sock
	       --listen-address=:4245
	     State:          Running
	       Started:      Tue, 07 Jul 2020 07:02:32 +0000
	     Last State:     Terminated
	       Reason:       Completed
	       Exit Code:    0
	       Started:      Tue, 07 Jul 2020 07:02:09 +0000
	       Finished:     Tue, 07 Jul 2020 07:02:31 +0000
	     Ready:          False
	     Restart Count:  9
	     Liveness:       tcp-socket :grpc delay=0s timeout=1s period=10s #success=1 #failure=3
	     Readiness:      tcp-socket :grpc delay=0s timeout=1s period=10s #success=1 #failure=3
	     Environment:    <none>
	     Mounts:
	       /var/run/cilium from hubble-sock-dir (ro)
	       /var/run/secrets/kubernetes.io/serviceaccount from default-token-88dcq (ro)
	 Conditions:
	   Type              Status
	   Initialized       True 
	   Ready             False 
	   ContainersReady   False 
	   PodScheduled      True 
	 Volumes:
	   hubble-sock-dir:
	     Type:          HostPath (bare host directory volume)
	     Path:          /var/run/cilium
	     HostPathType:  Directory
	   default-token-88dcq:
	     Type:        Secret (a volume populated by a Secret)
	     SecretName:  default-token-88dcq
	     Optional:    false
	 QoS Class:       BestEffort
	 Node-Selectors:  <none>
	 Tolerations:     
	 Events:
	   Type     Reason           Age                   From                                                  Message
	   ----     ------           ----                  ----                                                  -------
	   Normal   Scheduled        13m                   default-scheduler                                     Successfully assigned cilium/hubble-relay-54c5c9bb68-5tn79 to gke-cilium-ci-20-cilium-ci-20-8f0a9b36-t2nw
	   Normal   Pulling          13m                   kubelet, gke-cilium-ci-20-cilium-ci-20-8f0a9b36-t2nw  Pulling image "147.75.55.179/cilium/hubble-relay:d5946a267afd2a8f341542137bf4f9098702a0dd"
	   Warning  FailedMount      13m (x2 over 13m)     kubelet, gke-cilium-ci-20-cilium-ci-20-8f0a9b36-t2nw  MountVolume.SetUp failed for volume "default-token-88dcq" : couldn't propagate object cache: timed out waiting for the condition
	   Warning  NetworkNotReady  13m (x6 over 13m)     kubelet, gke-cilium-ci-20-cilium-ci-20-8f0a9b36-t2nw  network is not ready: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
	   Normal   Pulling          12m (x2 over 13m)     kubelet, gke-cilium-ci-20-cilium-ci-20-8f0a9b36-t2nw  Pulling image "147.75.55.179/cilium/hubble-relay:d5946a267afd2a8f341542137bf4f9098702a0dd"
	   Normal   Killing          12m                   kubelet, gke-cilium-ci-20-cilium-ci-20-8f0a9b36-t2nw  Container hubble-relay failed liveness probe, will be restarted
	   Normal   Pulled           12m (x2 over 13m)     kubelet, gke-cilium-ci-20-cilium-ci-20-8f0a9b36-t2nw  Successfully pulled image "147.75.55.179/cilium/hubble-relay:d5946a267afd2a8f341542137bf4f9098702a0dd"
	   Normal   Created          12m (x2 over 13m)     kubelet, gke-cilium-ci-20-cilium-ci-20-8f0a9b36-t2nw  Created container hubble-relay
	   Normal   Started          12m (x2 over 13m)     kubelet, gke-cilium-ci-20-cilium-ci-20-8f0a9b36-t2nw  Started container hubble-relay
	   Warning  Unhealthy        12m (x4 over 13m)     kubelet, gke-cilium-ci-20-cilium-ci-20-8f0a9b36-t2nw  Readiness probe failed: dial tcp 10.44.1.12:4245: i/o timeout
	   Warning  Unhealthy        12m (x4 over 13m)     kubelet, gke-cilium-ci-20-cilium-ci-20-8f0a9b36-t2nw  Liveness probe failed: dial tcp 10.44.1.12:4245: i/o timeout
	   Warning  BackOff          3m24s (x31 over 10m)  kubelet, gke-cilium-ci-20-cilium-ci-20-8f0a9b36-t2nw  Back-off restarting failed container
	 
Stderr:
 	 

FAIL: hubble-relay was not able to get into ready state
Expected
    <*errors.errorString | 0xc0004946d0>: {
        s: "timed out waiting for pods with filter -l k8s-app=hubble-relay to be ready: 10m0s timeout expired",
    }
to be nil
```
[cb97cbd7_K8sHubbleTest_Hubble_Observe_Test_L3-L4_Flow.zip](https://github.com/cilium/cilium/files/4888046/cb97cbd7_K8sHubbleTest_Hubble_Observe_Test_L3-L4_Flow.zip)

### PR DESCRIPTION
**Pull request by gandro**
As our [documentation states](https://docs.cilium.io/en/v1.8/gettingstarted/k8s-install-gke/), GKE requires unmanaged pods to be restarted after Cilium is deployed. Because Hubble Relay is deployed together with Cilium, it can end up being an unmanaged pod depending on when it is scheduled, so has to be restarted.

This PR adds an additional step to the GKE setup where we also restart all unmanaged (non-hostNetwork) pods in the `cilium` namespace.

I have manually verified that when the `hubble-relay` pod enters a `CrashLoopBackoff` with the same logs output described in #12452, that it is indeed not managed (i.e. it did not show up in `cilium endpoint list`). Deleting the pod made the pod managed and fixed the connectivity issue immediately

Fixes #12452

### CODE REVIEW

File: test/k8sT/hubble.go [hunk 1]
```diff
@@ -105,167 +105,164 @@ var _ = Describe("K8sHubbleTest", func() {
 			"hubble observe: filter %q never matched expected string %q", filter, expected)
 	}
 
-	// Skipping on GKE due to hubble-relay not getting ready
-	SkipContextIf(helpers.SkipGKEQuarantined, "All Hubble Tests", func() {
```
Comment (gandro) [inline test/k8sT/hubble.go:109]: Reviewer note: This commit only removes this condition. All other line changes in this commit are simply whitelist changes due to the changed indentation.

**Comment by gandro** [comment]
test-gke

**Review by rolinh — APPROVED** [review]
Awesome, thanks!

**Review by nebril — APPROVED** [review]

**Review by michi-covalent — APPROVED** [review]

**Comment by gandro** [comment]
Seems to have passed GKE. I'll run GKE again as part of `test-me-please` (and making sure the changes didn't break any other CI)

**Comment by gandro** [comment]
test-me-please

**Comment by gandro** [comment]
net-next seems unrelated; restarting https://jenkins.cilium.io/job/Cilium-PR-K8s-1.12-net-next/341/testReport/junit/Suite-k8s-1/12/K8sPolicyTest_Multi_node_policy_test_validates_ingress_CIDR_dependent_L4_With_host_policy_Connectivity_is_restored_after_importing_ingress_policy/

**Comment by gandro** [comment]
retest-net-next
