### PR TITLE
policy: Improve PASS handling for non-consecutive tiers and wildcard fallbacks

### LINKED ISSUE #43916: PASS verdict broken for non-consecutive tiers and with default-allow
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.18.6 and lower than v1.19.0

### What happened?

There are two issues with the newly implemented policy rule priorities and pass verdict for policies:

1. When a PASS and ALLOW/DENY rule exist for the same identity at non-consecutive tiers (e.g. tier 0 and tier 2), the policy engine throws an error (`endpoint policy direction has more than 2^24 distinct priorities`)

2. When a PASS rule exists for a specific identity at a higher tier with a wildcard ALLOW rule at a lower tier, the policy engine incorrectly retains the PASS rule as an invalid rule, which throws off the policy evaluation. The wildcard ALLOW is never added for the affected identity.

### How can we reproduce the issue?

See the added test cases in the PR.

### Cilium Version

1.19

### Kernel Version

N/A

### Kubernetes Version

N/A

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by TheBeeZee**
Fixes errors when PASSing over tiers (e.g., Tier 0 to Tier 2)

Fixes: #43916

### CODE REVIEW

**Review by fristonio — APPROVED** [review]

File: pkg/policy/distillery_precedence_test.go [hunk 1]
```diff
@@ -497,6 +497,32 @@ func TestOrderedPolicyValidation(t *testing.T) {
...
+					Priority: 10,
+					L3:       selectors1111,
+					Verdict:  types.Deny,
+				},
+			},
+			expected: mapStateMap{
+				// default allow ingress
+				ingressKey(0, 0, 0, 0): newAllowEntryWithLabels(LabelsAllowAnyIngress),
+
+				egressKey(identity1111, 0, 0, 0): denyEntry.withLevel(3000).withPassPriority(0, 0, 0),
```
Comment (jrajahalme) [inline pkg/policy/distillery_precedence_test.go]: The correct expected entry is:
```
denyEntry.withLevel(1).withPassPriority(0, 0, 3000)
```
- the key has a pass entry at priority `0`, with tier (0) priority starting at `0`, and ending at 2999 (next tier starts at `3000`)
- the deny entry is promoted from its priority on its tier (3000) to follow the priority of the pass verdict applicable to it (`1`)

File: pkg/policy/mapstate.go [hunk 2]
```diff
@@ -1219,7 +1219,7 @@ func (ms *mapState) insertWithPasses(tierMaxPrecedence types.Precedence, key Key
 				}
 				// else keep the highest precedence covering pass key for each tier
 				passes.Collect(pass)
-			} else if isCoveringKey && pass.precedence > entry.Precedence {
+			} else if isCoveringKey && tierMaxPrecedence == pass.tierMaxPrecedence && pass.precedence > entry.Precedence {
```
Comment (jrajahalme) [inline pkg/policy/mapstate.go]: This change should be reverted, as the actual flaw is due to the `pass.tierMinPrecedence` being incorrect in the first if statement (before this `else if`) due to the skipped tier.

This fix is to be applied at `pkg/policy/rules.go`:
```
diff --git a/pkg/policy/rules.go b/pkg/policy/rules.go
index 94ad9b2486..bd11a8f946 100644
--- a/pkg/policy/rules.go
+++ b/pkg/policy/rules.go
@@ -58,6 +58,9 @@ const perTierRoundUp = 1000
 // Full range of the remaining tiers must be included so that we know to leave sufficient space
 // after each pass verdict for the rules promoted from the remaining tiers.
 //
+// Note that since the the full range of remaining tiers is included, the returned range for
+// tiers without any rules is the same as the next tier.
+//
 // Since the full range of the remaining tiers is included, the base priority of each tier can be
 // calculated as follows (range is the returned slice):
 //
@@ -155,8 +158,11 @@ func (rules ruleSlice) resolveL4Policy(policyCtx PolicyContext) (L4DirectionPoli
 			if priority > types.LowestPriority {
 				return result, ErrTooManyPriorityLevels
 			}
-			tier = r.Tier
-			priority -= types.Priority(tierPriorityLevels[tier])
+			priority -= types.Priority(tierPriorityLevels[r.Tier])
+			for tier++; tier < r.Tier; tier++ {
+				// fill in the same base priority for all skipped tiers
+				result.tierBasePriority[tier] = priority
+			}
 			result.tierBasePriority[tier] = priority
 
 			increment = types.Priority(1) // reset increment to default
```

**Review by jrajahalme — CHANGES_REQUESTED** [review]
Turns out the flaw was due to uninitialized (left at 0) tier base priorities for the skipped tiers, which led to an incorrect `tierMinPrecedence` for the pass entry on higher tier to the skipped tier.

File: pkg/policy/mapstate.go (hunk 2 above)
Comment (TheBeeZee) [reply pkg/policy/mapstate.go]: Thanks. I have reverted the original change and applied yours. Perhaps it would be better that you submit the PR, so it is attributed to you and not to me.

**Review by jrajahalme — APPROVED** [review]

**Comment by glrf** [comment]
I had some trouble backporting this to v1.19. The code in v1.19 is slightly different and I don't want to do something wrong for policy relevant code. Marking this as `backport/author`

**Comment by squeed** [comment]
@glrf thanks for the attempt. @jrajahalme will do the backport.
