### PR TITLE
fqdn proxy: fix data race by using separate sessionUDPFactories

### LINKED ISSUE #28156: DATARACE: dns.(*sessionUDPFactory).InitPool()
```
2023-09-13T23:24:24.735935486Z ==================
2023-09-13T23:24:24.736105785Z WARNING: DATA RACE
2023-09-13T23:24:24.736111956Z Write at 0x0000075f0fc0 by goroutine 996:
2023-09-13T23:24:24.736115182Z   github.com/cilium/dns.(*sessionUDPFactory).InitPool()
2023-09-13T23:24:24.736117957Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/dns/udp.go:95 +0xc4
2023-09-13T23:24:24.736120642Z   github.com/cilium/dns.(*Server).init()
2023-09-13T23:24:24.736123297Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/dns/server.go:277 +0x2e2
2023-09-13T23:24:24.736125892Z   github.com/cilium/dns.(*Server).ActivateAndServe()
2023-09-13T23:24:24.736128357Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/dns/server.go:355 +0x1a4
2023-09-13T23:24:24.736130891Z   github.com/cilium/cilium/pkg/fqdn/dnsproxy.StartDNSProxy.func1()
2023-09-13T23:24:24.736133356Z       /go/src/github.com/cilium/cilium/pkg/fqdn/dnsproxy/proxy.go:670 +0x264
2023-09-13T23:24:24.736136131Z   github.com/cilium/cilium/pkg/fqdn/dnsproxy.StartDNSProxy.func3()
2023-09-13T23:24:24.736138646Z       /go/src/github.com/cilium/cilium/pkg/fqdn/dnsproxy/proxy.go:680 +0x41
2023-09-13T23:24:24.736140980Z 
2023-09-13T23:24:24.736143575Z Previous write at 0x0000075f0fc0 by goroutine 994:
2023-09-13T23:24:24.736146180Z   github.com/cilium/dns.(*sessionUDPFactory).InitPool()
2023-09-13T23:24:24.736148765Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/dns/udp.go:95 +0xc4
2023-09-13T23:24:24.736151450Z   github.com/cilium/dns.(*Server).init()
2023-09-13T23:24:24.736154064Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/dns/server.go:277 +0x2e2
2023-09-13T23:24:24.736156870Z   github.com/cilium/dns.(*Server).ActivateAndServe()
2023-09-13T23:24:24.736159394Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/dns/server.go:355 +0x1a4
2023-09-13T23:24:24.736161890Z   github.com/cilium/cilium/pkg/fqdn/dnsproxy.StartDNSProxy.func1()
2023-09-13T23:24:24.736164323Z       /go/src/github.com/cilium/cilium/pkg/fqdn/dnsproxy/proxy.go:670 +0x264
2023-09-13T23:24:24.736166768Z   github.com/cilium/cilium/pkg/fqdn/dnsproxy.StartDNSProxy.func3()
2023-09-13T23:24:24.736169173Z       /go/src/github.com/cilium/cilium/pkg/fqdn/dnsproxy/proxy.go:680 +0x41
2023-09-13T23:24:24.736171397Z 
2023-09-13T23:24:24.736173962Z Goroutine 996 (running) created at:
2023-09-13T23:24:24.736176567Z   github.com/cilium/cilium/pkg/fqdn/dnsproxy.StartDNSProxy()
2023-09-13T23:24:24.736187076Z       /go/src/github.com/cilium/cilium/pkg/fqdn/dnsproxy/proxy.go:662 +0xea4
2023-09-13T23:24:24.736189811Z   github.com/cilium/cilium/daemon/cmd.(*Daemon).bootstrapFQDN()
2023-09-13T23:24:24.736192416Z       /go/src/github.com/cilium/cilium/daemon/cmd/fqdn.go:379 +0x1c13
2023-09-13T23:24:24.736194871Z   github.com/cilium/cilium/daemon/cmd.newDaemon()
2023-09-13T23:24:24.736197406Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon.go:826 +0x5c16
2023-09-13T23:24:24.736199881Z   github.com/cilium/cilium/daemon/cmd.newDaemonPromise.func1()
2023-09-13T23:24:24.736202696Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1682 +0xa4
2023-09-13T23:24:24.736205070Z   github.com/cilium/cilium/pkg/hive.Hook.Start()
2023-09-13T23:24:24.736207375Z       /go/src/github.com/cilium/cilium/pkg/hive/lifecycle.go:34 +0x70
2023-09-13T23:24:24.736209969Z   github.com/cilium/cilium/pkg/hive.(*Hook).Start()
2023-09-13T23:24:24.736212524Z       <autogenerated>:1 +0x1f
2023-09-13T23:24:24.736214798Z   github.com/cilium/cilium/pkg/hive.(*DefaultLifecycle).Start()
2023-09-13T23:24:24.736217132Z       /go/src/github.com/cilium/cilium/pkg/hive/lifecycle.go:103 +0x3f1
2023-09-13T23:24:24.736219457Z   github.com/cilium/cilium/pkg/hive.(*Hive).Start()
2023-09-13T23:24:24.736221811Z       /go/src/github.com/cilium/cilium/pkg/hive/hive.go:291 +0x152
2023-09-13T23:24:24.736388773Z   github.com/cilium/cilium/pkg/hive.(*Hive).Run()
2023-09-13T23:24:24.736393893Z       /go/src/github.com/cilium/cilium/pkg/hive/hive.go:191 +0xc4
2023-09-13T23:24:24.736396297Z   github.com/cilium/cilium/daemon/cmd.NewAgentCmd.func1()
2023-09-13T23:24:24.736398581Z       /go/src/github.com/cilium/cilium/daemon/cmd/root.go:39 +0x264
2023-09-13T23:24:24.736401446Z   github.com/spf13/cobra.(*Command).execute()
2023-09-13T23:24:24.736403871Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:944 +0xcb8
2023-09-13T23:24:24.736406186Z   github.com/spf13/cobra.(*Command).ExecuteC()
2023-09-13T23:24:24.736408540Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:1068 +0x5c4
2023-09-13T23:24:24.736411395Z   github.com/spf13/cobra.(*Command).Execute()
2023-09-13T23:24:24.736414121Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:992 +0x2e
2023-09-13T23:24:24.736416936Z   github.com/cilium/cilium/daemon/cmd.Execute()
2023-09-13T23:24:24.736419451Z       /go/src/github.com/cilium/cilium/daemon/cmd/root.go:79 +0x2f
2023-09-13T23:24:24.736422125Z   main.main()
2023-09-13T23:24:24.736424760Z       /go/src/github.com/cilium/cilium/daemon/main.go:14 +0xa9
2023-09-13T23:24:24.736467180Z 
2023-09-13T23:24:24.736469884Z Goroutine 994 (running) created at:
2023-09-13T23:24:24.736472289Z   github.com/cilium/cilium/pkg/fqdn/dnsproxy.StartDNSProxy()
2023-09-13T23:24:24.736474573Z       /go/src/github.com/cilium/cilium/pkg/fqdn/dnsproxy/proxy.go:662 +0xea4
2023-09-13T23:24:24.736476838Z   github.com/cilium/cilium/daemon/cmd.(*Daemon).bootstrapFQDN()
2023-09-13T23:24:24.736479132Z       /go/src/github.com/cilium/cilium/daemon/cmd/fqdn.go:379 +0x1c13
2023-09-13T23:24:24.736481416Z   github.com/cilium/cilium/daemon/cmd.newDaemon()
2023-09-13T23:24:24.736483740Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon.go:826 +0x5c16
2023-09-13T23:24:24.736486105Z   github.com/cilium/cilium/daemon/cmd.newDaemonPromise.func1()
2023-09-13T23:24:24.736488489Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1682 +0xa4
2023-09-13T23:24:24.736490773Z   github.com/cilium/cilium/pkg/hive.Hook.Start()
2023-09-13T23:24:24.736493068Z       /go/src/github.com/cilium/cilium/pkg/hive/lifecycle.go:34 +0x70
2023-09-13T23:24:24.736501614Z   github.com/cilium/cilium/pkg/hive.(*Hook).Start()
2023-09-13T23:24:24.736504549Z       <autogenerated>:1 +0x1f
2023-09-13T23:24:24.736550545Z   github.com/cilium/cilium/pkg/hive.(*DefaultLifecycle).Start()
2023-09-13T23:24:24.736553190Z       /go/src/github.com/cilium/cilium/pkg/hive/lifecycle.go:103 +0x3f1
2023-09-13T23:24:24.736555855Z   github.com/cilium/cilium/pkg/hive.(*Hive).Start()
2023-09-13T23:24:24.736558480Z       /go/src/github.com/cilium/cilium/pkg/hive/hive.go:291 +0x152
2023-09-13T23:24:24.736561175Z   github.com/cilium/cilium/pkg/hive.(*Hive).Run()
2023-09-13T23:24:24.736563870Z       /go/src/github.com/cilium/cilium/pkg/hive/hive.go:191 +0xc4
2023-09-13T23:24:24.736566465Z   github.com/cilium/cilium/daemon/cmd.NewAgentCmd.func1()
2023-09-13T23:24:24.736568970Z       /go/src/github.com/cilium/cilium/daemon/cmd/root.go:39 +0x264
2023-09-13T23:24:24.736571795Z   github.com/spf13/cobra.(*Command).execute()
2023-09-13T23:24:24.736574380Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:944 +0xcb8
2023-09-13T23:24:24.736576874Z   github.com/spf13/cobra.(*Command).ExecuteC()
2023-09-13T23:24:24.736579569Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:1068 +0x5c4
2023-09-13T23:24:24.736582154Z   github.com/spf13/cobra.(*Command).Execute()
2023-09-13T23:24:24.736584729Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:992 +0x2e
2023-09-13T23:24:24.736587244Z   github.com/cilium/cilium/daemon/cmd.Execute()
2023-09-13T23:24:24.736589838Z       /go/src/github.com/cilium/cilium/daemon/cmd/root.go:79 +0x2f
2023-09-13T23:24:24.736592764Z   main.main()
2023-09-13T23:24:24.736595429Z       /go/src/github.com/cilium/cilium/daemon/main.go:14 +0xa9
2023-09-13T23:24:24.736597954Z ==================
2023-09-13T23:24:24.736793288Z ==================
2023-09-13T23:24:24.736797887Z WARNING: DATA RACE
2023-09-13T23:24:24.736800251Z Write at 0x00c0012f5550 by goroutine 997:
2023-09-13T23:24:24.736802576Z   github.com/cilium/cilium/pkg/fqdn/dnsproxy.(*sessionUDPFactory).InitPool()
2023-09-13T23:24:24.736804940Z       /go/src/github.com/cilium/cilium/pkg/fqdn/dnsproxy/udp.go:166 +0xc4
2023-09-13T23:24:24.736807425Z   github.com/cilium/dns.(*Server).init()
2023-09-13T23:24:24.736810270Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/dns/server.go:277 +0x2e2
2023-09-13T23:24:24.736812915Z   github.com/cilium/dns.(*Server).ActivateAndServe()
2023-09-13T23:24:24.736815630Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/dns/server.go:355 +0x1a4
2023-09-13T23:24:24.736818135Z   github.com/cilium/cilium/pkg/fqdn/dnsproxy.StartDNSProxy.func1()
2023-09-13T23:24:24.736820709Z       /go/src/github.com/cilium/cilium/pkg/fqdn/dnsproxy/proxy.go:670 +0x264
2023-09-13T23:24:24.736823204Z   github.com/cilium/cilium/pkg/fqdn/dnsproxy.StartDNSProxy.func3()
2023-09-13T23:24:24.736825659Z       /go/src/github.com/cilium/cilium/pkg/fqdn/dnsproxy/proxy.go:680 +0x41
2023-09-13T23:24:24.736827973Z 
2023-09-13T23:24:24.736830498Z Previous write at 0x00c0012f5550 by goroutine 995:
2023-09-13T23:24:24.736833063Z   github.com/cilium/cilium/pkg/fqdn/dnsproxy.(*sessionUDPFactory).InitPool()
2023-09-13T23:24:24.736835557Z       /go/src/github.com/cilium/cilium/pkg/fqdn/dnsproxy/udp.go:166 +0xc4
2023-09-13T23:24:24.736838092Z   github.com/cilium/dns.(*Server).init()
2023-09-13T23:24:24.736840597Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/dns/server.go:277 +0x2e2
2023-09-13T23:24:24.736960310Z   github.com/cilium/dns.(*Server).ActivateAndServe()
2023-09-13T23:24:24.736965660Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/dns/server.go:355 +0x1a4
2023-09-13T23:24:24.736976039Z   github.com/cilium/cilium/pkg/fqdn/dnsproxy.StartDNSProxy.func1()
2023-09-13T23:24:24.736978895Z       /go/src/github.com/cilium/cilium/pkg/fqdn/dnsproxy/proxy.go:670 +0x264
2023-09-13T23:24:24.736981741Z   github.com/cilium/cilium/pkg/fqdn/dnsproxy.StartDNSProxy.func3()
2023-09-13T23:24:24.736984375Z       /go/src/github.com/cilium/cilium/pkg/fqdn/dnsproxy/proxy.go:680 +0x41
2023-09-13T23:24:24.736986579Z 
2023-09-13T23:24:24.736989355Z Goroutine 997 (running) created at:
2023-09-13T23:24:24.736991599Z   github.com/cilium/cilium/pkg/fqdn/dnsproxy.StartDNSProxy()
2023-09-13T23:24:24.736993903Z       /go/src/github.com/cilium/cilium/pkg/fqdn/dnsproxy/proxy.go:662 +0xea4
2023-09-13T23:24:24.736996157Z   github.com/cilium/cilium/daemon/cmd.(*Daemon).bootstrapFQDN()
2023-09-13T23:24:24.736998502Z       /go/src/github.com/cilium/cilium/daemon/cmd/fqdn.go:379 +0x1c13
2023-09-13T23:24:24.737000776Z   github.com/cilium/cilium/daemon/cmd.newDaemon()
2023-09-13T23:24:24.737003120Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon.go:826 +0x5c16
2023-09-13T23:24:24.737143613Z   github.com/cilium/cilium/daemon/cmd.newDaemonPromise.func1()
2023-09-13T23:24:24.737148853Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1682 +0xa4
2023-09-13T23:24:24.737151557Z   github.com/cilium/cilium/pkg/hive.Hook.Start()
2023-09-13T23:24:24.737154212Z       /go/src/github.com/cilium/cilium/pkg/hive/lifecycle.go:34 +0x70
2023-09-13T23:24:24.737156937Z   github.com/cilium/cilium/pkg/hive.(*Hook).Start()
2023-09-13T23:24:24.737159362Z       <autogenerated>:1 +0x1f
2023-09-13T23:24:24.737162117Z   github.com/cilium/cilium/pkg/hive.(*DefaultLifecycle).Start()
2023-09-13T23:24:24.737164782Z       /go/src/github.com/cilium/cilium/pkg/hive/lifecycle.go:103 +0x3f1
2023-09-13T23:24:24.737167236Z   github.com/cilium/cilium/pkg/hive.(*Hive).Start()
2023-09-13T23:24:24.737169772Z       /go/src/github.com/cilium/cilium/pkg/hive/hive.go:291 +0x152
2023-09-13T23:24:24.737172537Z   github.com/cilium/cilium/pkg/hive.(*Hive).Run()
2023-09-13T23:24:24.737175062Z       /go/src/github.com/cilium/cilium/pkg/hive/hive.go:191 +0xc4
2023-09-13T23:24:24.737177446Z   github.com/cilium/cilium/daemon/cmd.NewAgentCmd.func1()
2023-09-13T23:24:24.737220186Z       /go/src/github.com/cilium/cilium/daemon/cmd/root.go:39 +0x264
2023-09-13T23:24:24.737222580Z   github.com/spf13/cobra.(*Command).execute()
2023-09-13T23:24:24.737224894Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:944 +0xcb8
2023-09-13T23:24:24.737328768Z   github.com/spf13/cobra.(*Command).ExecuteC()
2023-09-13T23:24:24.737333497Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:1068 +0x5c4
2023-09-13T23:24:24.737335932Z   github.com/spf13/cobra.(*Command).Execute()
2023-09-13T23:24:24.737338266Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:992 +0x2e
2023-09-13T23:24:24.737340550Z   github.com/cilium/cilium/daemon/cmd.Execute()
2023-09-13T23:24:24.737343145Z       /go/src/github.com/cilium/cilium/daemon/cmd/root.go:79 +0x2f
2023-09-13T23:24:24.737345710Z   main.main()
2023-09-13T23:24:24.737348164Z       /go/src/github.com/cilium/cilium/daemon/main.go:14 +0xa9
2023-09-13T23:24:24.737350238Z 
2023-09-13T23:24:24.737352523Z Goroutine 995 (running) created at:
2023-09-13T23:24:24.737354757Z   github.com/cilium/cilium/pkg/fqdn/dnsproxy.StartDNSProxy()
2023-09-13T23:24:24.737357301Z       /go/src/github.com/cilium/cilium/pkg/fqdn/dnsproxy/proxy.go:662 +0xea4
2023-09-13T23:24:24.737360047Z   github.com/cilium/cilium/daemon/cmd.(*Daemon).bootstrapFQDN()
2023-09-13T23:24:24.737362431Z       /go/src/github.com/cilium/cilium/daemon/cmd/fqdn.go:379 +0x1c13
2023-09-13T23:24:24.737460294Z   github.com/cilium/cilium/daemon/cmd.newDaemon()
2023-09-13T23:24:24.737464722Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon.go:826 +0x5c16
2023-09-13T23:24:24.737467337Z   github.com/cilium/cilium/daemon/cmd.newDaemonPromise.func1()
2023-09-13T23:24:24.737470102Z       /go/src/github.com/cilium/cilium/daemon/cmd/daemon_main.go:1682 +0xa4
2023-09-13T23:24:24.737472617Z   github.com/cilium/cilium/pkg/hive.Hook.Start()
2023-09-13T23:24:24.737475112Z       /go/src/github.com/cilium/cilium/pkg/hive/lifecycle.go:34 +0x70
2023-09-13T23:24:24.737477696Z   github.com/cilium/cilium/pkg/hive.(*Hook).Start()
2023-09-13T23:24:24.737480352Z       <autogenerated>:1 +0x1f
2023-09-13T23:24:24.737482756Z   github.com/cilium/cilium/pkg/hive.(*DefaultLifecycle).Start()
2023-09-13T23:24:24.737485180Z       /go/src/github.com/cilium/cilium/pkg/hive/lifecycle.go:103 +0x3f1
2023-09-13T23:24:24.737487554Z   github.com/cilium/cilium/pkg/hive.(*Hive).Start()
2023-09-13T23:24:24.737490180Z       /go/src/github.com/cilium/cilium/pkg/hive/hive.go:291 +0x152
2023-09-13T23:24:24.737492634Z   github.com/cilium/cilium/pkg/hive.(*Hive).Run()
2023-09-13T23:24:24.737538901Z       /go/src/github.com/cilium/cilium/pkg/hive/hive.go:191 +0xc4
2023-09-13T23:24:24.737542016Z   github.com/cilium/cilium/daemon/cmd.NewAgentCmd.func1()
2023-09-13T23:24:24.737544321Z       /go/src/github.com/cilium/cilium/daemon/cmd/root.go:39 +0x264
2023-09-13T23:24:24.737599799Z   github.com/spf13/cobra.(*Command).execute()
2023-09-13T23:24:24.737604969Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:944 +0xcb8
2023-09-13T23:24:24.737607453Z   github.com/spf13/cobra.(*Command).ExecuteC()
2023-09-13T23:24:24.737609598Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:1068 +0x5c4
2023-09-13T23:24:24.737611852Z   github.com/spf13/cobra.(*Command).Execute()
2023-09-13T23:24:24.737614136Z       /go/src/github.com/cilium/cilium/vendor/github.com/spf13/cobra/command.go:992 +0x2e
2023-09-13T23:24:24.737616430Z   github.com/cilium/cilium/daemon/cmd.Execute()
2023-09-13T23:24:24.737618584Z       /go/src/github.com/cilium/cilium/daemon/cmd/root.go:79 +0x2f
2023-09-13T23:24:24.737620688Z   main.main()
2023-09-13T23:24:24.737622892Z       /go/src/github.com/cilium/cilium/daemon/main.go:14 +0xa9
2023-09-13T23:24:24.737625117Z ==================
```

Detected with the source code from https://github.com/cilium/cilium/pull/27979

Introduced by https://github.com/cilium/cilium/commit/5304088fbe100ace9c54c417b3c37c4bfa78fd79

### PR DESCRIPTION
**Pull request by mhofstetter**
PR #25309 introduced a data race by sharing the sessionUDPFactory between the DNS server instances for the different IP families (IPv4 & IPv6). This has been detected by #27979.

This commit fixes the data race by using dedicated instances of the sessionUDPFactory.

In addition the global response UDP connections (IPv4 & IPv6) variables have been replaced with fields in the `SessionUDPFactory`. This way the connections can already be setup during construction of the factory and the `sync.Once`s (global vars) can be removed.

Fixes: #28156

### CODE REVIEW

File: pkg/fqdn/dnsproxy/udp.go [hunk 1]
```diff
@@ -30,14 +31,48 @@ var udpOOBSize = func() int {
...
 	// A pool for UDP message buffers.
 	udpPool sync.Pool
 
-	// ipv4Enabled and ipv6Enabled are used when setting up the proxy sockets
-	// later, and determine if we bind to 127.0.0.1 and ::1, respectively.
-	// See sessionUDPFactory.SetSocketOptions
-	ipv4Enabled, ipv6Enabled bool
+	// responseConn4 and responseConn6 are used to send the response
+	// See sessionUDP.WriteResponse
+	responseConn4, responseConn6 *net.IPConn
```
Comment (jrajahalme) [inline pkg/fqdn/dnsproxy/udp.go]: How about keeping only one pointer (`responseConn`) in the factory? Each factory instance only has one family defined, so we do not need two pointers here?

**Review by jrajahalme — COMMENTED** [review]
Could simplify a bit by keeping only one conn pointer in the factory.

File: pkg/fqdn/dnsproxy/udp.go (hunk 1 above)
Comment (mhofstetter) [reply pkg/fqdn/dnsproxy/udp.go]: The reason is that the "building blocks" (e.g. SessionUDPFactory, setting transparent socket options, ...) were all built when a socket bound to a Cilium DNS server supported multiple IP Famliies (IPv4 & IPv6).

But this is no longer necessary since we use a dedicated DNS Server (& socket) per IPFamily.

Therefore i agree that this could be simplified. But for all cases.

=> I refactored the SessionUDPFactory & "setting the transparent socket options" to only support one IPFamily. All the relevant information are read from the `IPFamily` struct that gets passed down - to keep the code agnostic of the actual IP Family.

File: pkg/fqdn/proxy/ipfamily/ipfamily.go [hunk 2]
```diff
@@ -3,33 +3,41 @@
...
-	TCPAddress  string
-	Localhost   string
+	Name       string
+	UDPAddress string
+	TCPAddress string
+	Localhost  string
+
+	SocketOptsFamily              int
+	SocketOptsTransparent         int
+	SocketOptsRecvOrIgnoreDstAddr int
```
Comment (jrajahalme) [inline pkg/fqdn/proxy/ipfamily/ipfamily.go]: This should be `SocketOptsRecvOrigDstAddr` (receive original destination address)

**Review by jrajahalme — APPROVED** [review]
One nit I hope you address.

File: pkg/fqdn/proxy/ipfamily/ipfamily.go (hunk 2 above)
Comment (mhofstetter) [reply pkg/fqdn/proxy/ipfamily/ipfamily.go]: the "power" of autocompletion :joy_cat: addressed and fixed - thanks!

File: pkg/fqdn/dnsproxy/udp.go [hunk 3]
```diff
@@ -51,41 +70,29 @@ type sessionUDP struct {
...
-		if err := unix.SetsockoptInt(fd, unix.SOL_IPV6, unix.IPV6_TRANSPARENT, 1); err != nil {
-			return fmt.Errorf("setsockopt(IPV6_TRANSPARENT) failed: %w", err)
-		}
-		if err := unix.SetsockoptInt(fd, unix.SOL_IPV6, unix.IPV6_RECVORIGDSTADDR, 1); err != nil {
-			return fmt.Errorf("setsockopt(IPV6_RECVORIGDSTADDR) failed: %w", err)
-		}
+// By design, a socket of a DNS Server can only receive IPv4 or IPv6 traffic.
+func transparentSetsockopt(fd int, ipFamily ipfamily.IPFamily) error {
+	if err := unix.SetsockoptInt(fd, ipFamily.SocketOptsFamily, ipFamily.SocketOptsTransparent, 1); err != nil {
+		return fmt.Errorf("setsockopt(IP(V6)_TRANSPARENT) failed: %w", err)
```
Comment (pippolo84) [inline pkg/fqdn/dnsproxy/udp.go]: i think the error string should contain `IPv6` or `IPv4` based on `ipFamily`

File: pkg/fqdn/dnsproxy/udp.go [hunk 4]
```diff
@@ -51,41 +70,29 @@ type sessionUDP struct {
...
 	}
-	if ipv4 {
-		if err := unix.SetsockoptInt(fd, unix.SOL_IP, unix.IP_TRANSPARENT, 1); err != nil {
-			return fmt.Errorf("setsockopt(IP_TRANSPARENT) failed: %w", err)
-		}
-		if err := unix.SetsockoptInt(fd, unix.SOL_IP, unix.IP_RECVORIGDSTADDR, 1); err != nil {
-			return fmt.Errorf("setsockopt(IP_RECVORIGDSTADDR) failed: %w", err)
-		}
+	if err := unix.SetsockoptInt(fd, ipFamily.SocketOptsFamily, ipFamily.SocketOptsRecvOrigDstAddr, 1); err != nil {
+		return fmt.Errorf("setsockopt(IP(V6)_RECVORIGDSTADDR) failed: %w", err)
```
Comment (pippolo84) [inline pkg/fqdn/dnsproxy/udp.go]: Same here

**Review by pippolo84 — COMMENTED** [review]
Just a minor thing related to an error string, apart from that LGTM!

File: pkg/fqdn/dnsproxy/udp.go (hunk 3 above)
Comment (mhofstetter) [reply pkg/fqdn/dnsproxy/udp.go]: thanks, i changed the error message to contain the name of the `ipFamily`

**Comment by mhofstetter** [comment]
> Just a minor thing related to an error string, apart from that LGTM!

Thanks, i adapted the error messages

**Review by pippolo84 — APPROVED** [review]
:100:
