### PR TITLE
Test: Fix hack in `SetAndWaitForEndpointConfiguration`

### LINKED ISSUE #3489: Test: RuntimeValidatedConntrackTest mistmatch
```
Stacktrace

/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:270
Endpoint configuration Conntrack does not match
Expected
    <string>: Enabled
to equal
    <string>: Disabled
/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/runtime/connectivity.go:660
```

[RuntimeValidatedConntrackTestConntrack-relatedconfigurationoptionsforendpoints.zip](https://github.com/cilium/cilium/files/1871566/RuntimeValidatedConntrackTestConntrack-relatedconfigurationoptionsforendpoints.zip)

Jenkins build: https://github.com/cilium/cili​um/issues/3489

### PR DESCRIPTION
**Pull request by eloycoto**
The max retry was too small, and it didn't use WithTimeout function.
This uses the same helpers as others functions.

Fix #3489

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/3490)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

File: test/helpers/cilium.go [hunk 1]
```diff
@@ -97,37 +97,37 @@ func (s *SSHMeta) GetEndpointMutableConfigurationOption(endpointID, optionName s
...
-
-	log.Infof("Setting endpoint %s config %s=%s", endpointID, optionName, expectedValue)
-
-	// HACK:
-	// Retry multiple times as policy generations can still be queued up in
-	// which case the value will immediately swap back
-	for retry := 1; retry <= maxRetries; retry++ {
+func (s *SSHMeta) SetAndWaitForEndpointConfiguration(endpointID, optionName, expectedValue string) error {
+	logger := s.logger.WithFields(logrus.Fields{
+		"ep":     endpointID,
```
Comment (ianvernon) [inline test/helpers/cilium.go]: We have `pkg/logfields` which has a variety of constants like `logfields.EndpointID`. Having uniformity across CI and Cilium with these fields makes it easier for developers to debug since it is similar to what Cilium has. Can you use `logfields.EndpointID`?

File: test/helpers/cilium.go [hunk 2]
```diff
@@ -97,37 +97,37 @@ func (s *SSHMeta) GetEndpointMutableConfigurationOption(endpointID, optionName s
...
+		"value":  expectedValue})
+	body := func() bool {
+		logger.Infof("Setting endpoint config")
 		status := s.EndpointSetConfig(endpointID, optionName, expectedValue)
-		if retry == maxRetries {
-			gomega.ExpectWithOffset(1, status).Should(gomega.BeTrue(), "could not set %s=%s on endpoint %q", optionName, expectedValue, endpointID)
-		} else if !status {
-			continue
+		if !status {
+			logger.Error("Cannot set endppoint config")
```
Comment (ianvernon) [inline test/helpers/cilium.go]: endppoint --> endpoint

File: test/helpers/cilium.go [hunk 3]
```diff
@@ -97,37 +97,37 @@ func (s *SSHMeta) GetEndpointMutableConfigurationOption(endpointID, optionName s
...
+			return status
 		}
 
 		value, err := s.GetEndpointMutableConfigurationOption(endpointID, optionName)
-		gomega.ExpectWithOffset(1, err).To(gomega.BeNil(), "Cannot get endpoint configuration")
+		if err != nil {
+			log.WithError(err).Error("cannot get endpoinpt configuration")
```
Comment (ianvernon) [inline test/helpers/cilium.go]: Please be careful with typos. endpoinpt --> endpoint

File: test/helpers/cilium.go [hunk 4]
```diff
@@ -97,37 +97,37 @@ func (s *SSHMeta) GetEndpointMutableConfigurationOption(endpointID, optionName s
...
 		if value == expectedValue {
 			return true
 		}
-
-		if retry == maxRetries {
-			gomega.ExpectWithOffset(1, value).To(gomega.Equal(expectedValue), "Endpoint configuration %s does not match", optionName)
-		}
-
-		time.Sleep(time.Duration(retry) * time.Second)
+		logger.Debugf("Endpoint config mistmatch %q=%q", value, expectedValue)
```
Comment (ianvernon) [inline test/helpers/cilium.go]: mistmatch --> mismatch

Comment (ianvernon) [reply test/helpers/cilium.go]: This log message is cryptic; say something like `..."expected configuration option to have value %s, but got %s", expectedValue, value)`

File: test/helpers/cilium.go [hunk 5]
```diff
@@ -97,37 +97,37 @@ func (s *SSHMeta) GetEndpointMutableConfigurationOption(endpointID, optionName s
...
+		return false
 	}
 
-	return false
+	err := WithTimeout(
+		body,
+		fmt.Sprintf("cannot set endpoint config for ep %q", endpointID),
```
Comment (ianvernon) [inline test/helpers/cilium.go]: ep --> endpoint. Please use uniform vocabulary across logs, it makes searching the logs easier.

File: test/runtime/connectivity.go [hunk 6]
```diff
@@ -641,8 +641,10 @@ var _ = Describe("RuntimeValidatedConntrackTest", func() {
 			By(fmt.Sprintf("Testing with endpoint configuration option: ConntrackLocal=%s", conntrackLocalOptionMode))
 
 			for _, endpointToConfigure := range endpointsToConfigure {
-				vm.SetAndWaitForEndpointConfiguration(endpointToConfigure, helpers.OptionConntrackLocal, conntrackLocalOptionMode)
-
+				err := vm.SetAndWaitForEndpointConfiguration(
+					endpointToConfigure, helpers.OptionConntrackLocal, conntrackLocalOptionMode)
+				Expect(err).To(BeNil(), "Cannot %q ConntrackLocal to endpoint %q",
```
Comment (ianvernon) [inline test/runtime/connectivity.go]: `..."Cannot set ConnTrackLocal=%q for endpoint %s", conntrackLocalOptionMode, endpointToConfigure)`

File: test/runtime/connectivity.go [hunk 7]
```diff
@@ -656,8 +658,10 @@ var _ = Describe("RuntimeValidatedConntrackTest", func() {
 
 		for _, endpointToConfigure := range endpointsToConfigure {
 			// ConntrackLocal must be disabled as it depends on Conntrack
-			vm.SetAndWaitForEndpointConfiguration(endpointToConfigure, helpers.OptionConntrackLocal, helpers.OptionDisabled)
-			vm.SetAndWaitForEndpointConfiguration(endpointToConfigure, helpers.OptionConntrack, helpers.OptionDisabled)
+			err := vm.SetAndWaitForEndpointConfiguration(endpointToConfigure, helpers.OptionConntrackLocal, helpers.OptionDisabled)
+			Expect(err).To(BeNil(), "Cannot disable ConntrackLocal for the endpoint %q", endpointToConfigure)
+			err = vm.SetAndWaitForEndpointConfiguration(endpointToConfigure, helpers.OptionConntrack, helpers.OptionDisabled)
+			Expect(err).To(BeNil(), "Cannot disable Conntrackl for the endpoint %q", endpointToConfigure)
```
Comment (ianvernon) [inline test/runtime/connectivity.go]: Please be more careful about typing in log messages. 
`Conntrackl` --> `ConnTrackLocal`.

**Review by ianvernon — DISMISSED** [review]
Logic looks fine; please fix the typos, though. I will review again.

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
@ianvernon ready for review it again.

**Review by ianvernon — APPROVED** [review]
