### PR TITLE
iptables: skip NOTRACK rules deletion

### LINKED ISSUE #20714: Cilium failed to delete iptables
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

cilium failed to delete iptables rules, and due to resent change #19693 cause cilium agent failed to start.

```
level=warning msg="Failed to install iptables rules" error="unable to run 'iptables -t raw -D OLD_CILIUM_OUTPUT_raw -o eth0 -m mark --mark 0xa00/0xfffffeff -m comment --comment cilium: NOTRACK for proxy return traffic -j NOTRACK' iptables command: iptables: Bad rule (does a matching rule exist in that chain?).\n (exit status 1)" subsys=iptables
```

Cilium container is using ubuntu:20.04 with iptables v1.8.4 (nf_tables) , is the root cause.

### Cilium Version

v1.12.0

### Kernel Version

NA

### Kubernetes Version

NA

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

Update base images to ubuntu:22.10 with  iptables v1.8.7 can solve the problem.

But will break current exist chain check  
https://github.com/cilium/cilium/commit/d812b925dec2d8be09834277050050d67681fd7c#diff-b4039bd03e60cc92838935c6a68fb7dde71ac58ae26d90818b38148684f5f769R104  
```
# iptables -V
iptables v1.8.4 (nf_tables)
# iptables -t filter -L OLD_CILIUM_INPUT
iptables: No chain/target/match by that name.

# iptables -V
iptables v1.8.7 (nf_tables)
# iptables -t filter -L OLD_CILIUM_INPUT
iptables v1.8.7 (nf_tables): chain `OLD_CILIUM_INPUT' in table `filter' is incompatible, use 'nft' tool.
```
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jibi**
The Iptables version shipped with Cilium (1.8.4) does not fully support
the iptables-legacy - nft translation of NOTRACK rules, which in turn
causes the agent to crash whenever it tries to delete any old/backup
ruleset.

This commit introduces a workaround for this by ignoring the `-j
NOTRACK` and `-j CT --notrack` rules when deleting all rules belonging
to an old/backup ruleset.

This is not an issue (although it's not optimal) as eventually the agent
will just flush and remove all the Cilium managed Iptables chains.

Fixes: #20714

```release-note
Fix bug where Cilium would crash on startup with an error about being unable to delete iptables rules.
```

### CODE REVIEW

File: pkg/datapath/iptables/iptables.go [hunk 1]
```diff
@@ -234,6 +234,18 @@ func (m *IptablesManager) removeCiliumRules(table string, prog iptablesInterface
...
 
+		// Temporary fix while Iptables is upgraded to >= 1.8.5
+		// (See GH-20884).
+		//
+		// The version currently shipped with Cilium (1.8.4) does not
+		// support the deletion of NOTRACK rules, so we will just ignore
+		// them here and let the agent remove them when it deletes the
+		// entire chain.
+		if strings.Contains(rule, "-j NOTRACK") ||
+			strings.Contains(rule, "-j CT --notrack") {
```
Comment (brb) [inline pkg/datapath/iptables/iptables.go]: Doesn't the `-j CT --notrack` work on < 1.8.5?

Comment (jibi) [reply pkg/datapath/iptables/iptables.go]: I think I tested restarting a 1.11 agent (which is using `-j CT --notrack`) and it failed to delete the old rules, but I might be mixing things up at this point, let me rerun the test

Comment (jibi) [reply pkg/datapath/iptables/iptables.go]: You are right, no need to do anything with `-j CT --notrack` rules :+1:

**Review by joestringer — APPROVED** [review]

**Review by brb — APPROVED** [review]

**Review by aanm — APPROVED** [review]
