### PR TITLE
egress gateway: fix non-tunnel mode

### LINKED ISSUE #17386: egress gw: Non-tunnel mode is broken
The egress GW datapath is broken when running in the direct routing mode.

To illustrate this, let's imagine a client pod sending a request to the internet via the egress GW:

```
client pod @ node A (runs cilium) -- vxlan tunnel --> egress GW @ node B (runs cilium) ----> the internet
```

The request gets SNAT-ed to the egress GW IP addr, and then sent to the internet. When the reply hits the egress GW node, it gets rev-SNAT-ed in bpf_host by:

```
"from-netdev" -> handle_netdev() -> do_netdev() -> .... handle_ipv4() -> nodeport_lb4() -> ... -> snat_v4_process()
```

And then is passed to the stack by `handle_ipv4()` which is called after the rev-SNAT-ed packet is recircled via tail calls.

In the upper-stack we have the iptables filter rules which default policy is DROP. As no Cilium's FORWARD rule matches the reply, the reply is DROP-ed by the default policy. In the case of tunneling, we have a rule (`cilium: any->cluster on cilium_host forward accept`) which matches the reply, and thus it is successfully sent to the client.

During [the initial testing of the feature](https://github.com/cilium/cilium/pull/14830#issuecomment-805745010) the direct routing mode was not broken, as all traffic was flowing through the tunnel (see https://github.com/cilium/cilium/pull/16328 for the context).

One way to fix the issue is to send the reply over the tunnel instead of passing to the stack (it also removes asymmetry of the return path). For this we would need to identify that a reply is part of the egress GW traffic. As @pchaigno suggested, this can be done by the following:

> if rev-SNATed IP ∈ native CIDR && rev-SNATed IP !∈ node pod CIDR => send to tunnel

Another alternative is to add a flag to the `struct nat_entry` denoting that the traffic belong to the egress GW. This would allow us to avoid the IPCache lookup (required by `rev-SNATed IP !∈ node pod CIDR`). However, not sure whether it's easy to propagate that flag after the rev-SNAT  to `handle_ipv4()`.

### PR DESCRIPTION
**Pull request by kkourt**
Fixes: https://github.com/cilium/cilium/issues/17386

When a client uses an egress gateway node, it forwards traffic via a vxlan tunnel to the egress gateway node. If datapath is configured in non-tunnel mode (direct routing), replies from the gateway to the client do not go via the tunnel. This causes these replies to be dropped by iptables because no Cilium's FORWARD rule matches them

This patch identifies above packets (i.e., from egress gw to client), and steers them via the vlxan tunnel after rev-SNAT is performed even when datapath is configured in non-tunnel mode.

PR also adds a test for egress gateway functionality.

Signed-off-by: Kornilios Kourtis <kornilios@isovalent.com>

```release-note
egress gateway: fix non-tunnel (direct routing) mode
```

### CODE REVIEW

**Comment by kkourt** [comment]
test-1.16-netnext

**Comment by kkourt** [comment]
test-me-please

**Comment by kkourt** [comment]
/test-1.16-netnext

**Comment by kkourt** [comment]
/test-1.21-4.9

**Comment by pchaigno** [comment]
Would it be possible to remove my GitHub handle and Martynas's from the commit description to avoid this :point_down: :grin: 
image

**Comment by kkourt** [comment]
> Would it be possible to remove my GitHub handle and Martynas's from the commit description to avoid this point_down grin image
> 
> EDIT: One other way to acknowledge would be `Suggested-by: ...`.

Woops! I thought it would be good to have the @ but I didn't anticipate it will spam you so much. Will remove it on the next iteration.

File: bpf/lib/nodeport.h [hunk 1]
```diff
@@ -1938,6 +1938,8 @@ static __always_inline int nodeport_lb4(struct __ctx_buff *ctx,
  * a remote backend and we got here after reverse SNAT from the
  * tail_nodeport_nat_ipv4().
  *
+ * Also, reverse NAT handling return path egress-gw traffic.
```
Comment (brb) [inline bpf/lib/nodeport.h:1941]: It's probably a time to rename the function :grimacing:

**Review by brb — APPROVED** [review]
LGTM!

A few non-blocking comments:
- s/@martynas/@brb/ in the first comment
- Could you extend the msg of the testing commit saying that you have dropped the 0.0.0.0/0 and explain why?

**Comment by kkourt** [comment]
Updated commit messages according to the suggestions of @brb and @pchaigno.

**Comment by kkourt** [comment]
/test-1.16-netnext

**Comment by brb** [comment]
Travis CI hit:
> docker: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.

Restarted.

File: bpf/lib/nodeport.h [hunk 2]
```diff
@@ -1967,6 +1970,32 @@ static __always_inline int rev_nodeport_lb4(struct __ctx_buff *ctx, int *ifindex
...
+			struct remote_endpoint_info *info;
+
+			info = ipcache_lookup4(&IPCACHE_MAP, ip4->daddr, V4_CACHE_KEY_LEN);
+			if (info && info->tunnel_endpoint != 0) {
+				tunnel_endpoint = info->tunnel_endpoint;
+				goto encap_redirect;
+			}
+		}
+	}
+#endif /* ENABLE_EGRESS_GATEWAY */
```
Comment (borkmann) [inline bpf/lib/nodeport.h:1994]: Looks ok, is there a reason you place this right after the CT lookup? Why is this extra cost needed for egress gw?

Comment (kkourt) [reply bpf/lib/nodeport.h:1994]: Ah good point, there is no reason.

I was expecting to find a ct entry for egress gw traffic and use it for the check, but, as it turns out, there is not CT entry created for egress gw packets. I can move it further up  to avoid the ct lookup overhead.

Comment (kkourt) [reply bpf/lib/nodeport.h:1994]: pushed new version with above fix.

File: bpf/lib/nodeport.h [hunk 3]
```diff
@@ -1983,23 +2011,10 @@ static __always_inline int rev_nodeport_lb4(struct __ctx_buff *ctx, int *ifindex
 #ifdef TUNNEL_MODE
 		{
 			struct remote_endpoint_info *info;
-
```
Comment (borkmann) [inline bpf/lib/nodeport.h:1986]: small nit: this seems unrelated? usually we keep an empty line after declarations.

**Review by borkmann — APPROVED** [review]

File: bpf/lib/nodeport.h (hunk 3 above)
Comment (kkourt) [reply bpf/lib/nodeport.h:1986]: Indeed it does. I'll wait for a review from @pchaigno, since he wanted to have a look. If there are only stylistic changes (i.e., whitespace), I'll take a screenshot of the---currently green---CI,  push a new version and mark this as ready-to-merge. If there more substantial changes requested, then we will need to run CI anyway.

File: bpf/lib/nodeport.h [hunk 4]
```diff
@@ -1964,6 +1967,31 @@ static __always_inline int rev_nodeport_lb4(struct __ctx_buff *ctx, int *ifindex
 	l4_off = l3_off + ipv4_hdrlen(ip4);
 	csum_l4_offset_and_flags(tuple.nexthdr, &csum_off);
 
+#if defined(ENABLE_EGRESS_GATEWAY) && !defined(TUNNEL_MODE)
+	/* traffic from clients to egress gateway nodes, reaches said gateways
```
Comment (pchaigno) [inline bpf/lib/nodeport.h]: Nit:
```suggestion
	/* Traffic from clients to egress gateway nodes reaches said gateways
```

File: test/helpers/kubectl.go [hunk 5]
```diff
@@ -4279,6 +4297,7 @@ func GenerateNamespaceForTest(seed string) string {
 	replaced := strings.Replace(lowered, " ", "", -1)
 	replaced = strings.Replace(replaced, "_", "", -1)
 	replaced = strings.Replace(replaced, "/", "", -1)
+	replaced = strings.Replace(replaced, "-", "", -1)
```
Comment (pchaigno) [inline test/helpers/kubectl.go:4300]: Why is this change needed? Should it be in its own commit?

File: test/k8sT/Egress.go [hunk 6]
```diff
@@ -0,0 +1,298 @@
+// Copyright 2017-2021 Authors of Cilium
```
Comment (pchaigno) [inline test/k8sT/Egress.go]:
```suggestion
// Copyright 2021 Authors of Cilium
```

File: test/k8sT/Egress.go [hunk 7]
```diff
@@ -0,0 +1,298 @@
...
+		outsideIP string
+
+		assignIPYAML string
+		echoPodYAML  string
+		policyYAML   string
+
+		namespaceSelector string = "ns=cilium-test"
+	)
+
+	// TODO(anfernee): Check a better way to deduplicate it with similar snippet in DatapathConfiguration.go
```
Comment (pchaigno) [inline test/k8sT/Egress.go]: I think we should either remove the comment or address this.

File: test/k8sT/manifests/egress-ip-deployment.yaml [hunk 8]
```diff
@@ -0,0 +1,38 @@
...
+      - name: egress-ip
+        image: docker.io/library/busybox:1.31.1
+        command: ["/bin/sh","-c"]
+        securityContext:
+          privileged: true
+        env:
+        - name: EGRESS_IPS
+          value: "INPUT_EGRESS_IP/24"
+        args:
+        - "for i in $EGRESS_IPS; do ip address add $i dev enp0s8; done; sleep 10000000"
```
Comment (pchaigno) [inline test/k8sT/manifests/egress-ip-deployment.yaml:31]:
```suggestion
        - "ip address add $EGRESS_IP dev enp0s8; sleep 10000000"
```

File: test/k8sT/manifests/egress-ip-deployment.yaml [hunk 9]
```diff
@@ -0,0 +1,38 @@
...
+        cilium.io/ci-node: k8s2
+      hostNetwork: true
+      containers:
+      - name: egress-ip
+        image: docker.io/library/busybox:1.31.1
+        command: ["/bin/sh","-c"]
+        securityContext:
+          privileged: true
+        env:
+        - name: EGRESS_IPS
```
Comment (pchaigno) [inline test/k8sT/manifests/egress-ip-deployment.yaml:28]:
```suggestion
        - name: EGRESS_IP
```

File: test/k8sT/manifests/egress-ip-deployment.yaml [hunk 10]
```diff
@@ -0,0 +1,38 @@
...
+          value: "INPUT_EGRESS_IP/24"
+        args:
+        - "for i in $EGRESS_IPS; do ip address add $i dev enp0s8; done; sleep 10000000"
+        lifecycle:
+          preStop:
+            exec:
+              command:
+              - "/bin/sh"
+              - "-c"
+              - "for i in $EGRESS_IPS; do ip address del $i dev enp0s8; done"
```
Comment (pchaigno) [inline test/k8sT/manifests/egress-ip-deployment.yaml:38]:
```suggestion
              - "ip address del $EGRESS_IP dev enp0s8"
```

File: test/k8sT/Egress.go [hunk 11]
```diff
@@ -0,0 +1,298 @@
...
+		// Wait egressIP online
+		srcPod, _ := fetchPodsWithOffset(kubectl, helpers.DefaultNamespace, "", "name=egress-ip-assign", "", false, 0)
+		res = kubectl.ExecPodCmd(helpers.DefaultNamespace, srcPod, helpers.PingWithCount(egressIP, 5))
+		res.ExpectSuccess()
+	}
+
+	BeforeAll(func() {
+		if helpers.DoesNotRunWithKubeProxyReplacement() {
+			Skip("EgressGatewayTest requires KubeProxyReplacement")
+		}
```
Comment (pchaigno) [inline test/k8sT/Egress.go:82]: This check can be removed and instead `!helpers.RunsOn419OrLaterKernel()` above replaced with `helper.DoesNotRunWithKubeProxyReplacement()`

File: test/k8sT/Egress.go [hunk 12]
```diff
@@ -0,0 +1,298 @@
...
+		_, k8s1IP = kubectl.GetNodeInfo(helpers.K8s1)
+		_, k8s2IP = kubectl.GetNodeInfo(helpers.K8s2)
+		_, outsideIP = kubectl.GetNodeInfo(helpers.GetNodeWithoutCilium())
+
+		egressIP = getEgressIP(k8s1IP)
+
+		deploymentManager.SetKubectl(kubectl)
+
+		ciliumFilename = helpers.TimestampFilename("cilium.yaml")
+		DeployCiliumAndDNS(kubectl, ciliumFilename)
```
Comment (pchaigno) [inline test/k8sT/Egress.go:95]: Why do we need to redeploy Cilium here?

File: test/k8sT/Egress.go [hunk 13]
```diff
@@ -0,0 +1,298 @@
...
+
+			testEgressGateway(false)
+			testEgressGateway(true)
+			testConnectivity(false)
+			testConnectivity(true)
+		})
+
+	})
+
+	Context("tunnel vxlan", func() {
```
Comment (pchaigno) [inline test/k8sT/Egress.go:251]: Could we also check VXLAN + endpoint routes?

File: test/k8sT/Egress.go [hunk 14]
```diff
@@ -0,0 +1,298 @@
...
+		policyYAML = strings.Trim(res.Stdout(), "\n")
+		kubectl.ExecMiddle(fmt.Sprintf("sed 's/INPUT_EGRESS_IP/%s/' %s > %s",
+			egressIP, originalPolicyYAML, policyYAML)).ExpectSuccess()
+		kubectl.ExecMiddle(fmt.Sprintf("sed 's/INPUT_OUTSIDE_NODE_IP/%s/' -i %s",
+			outsideIP, policyYAML)).ExpectSuccess()
+		res = kubectl.ApplyDefault(policyYAML)
+		Expect(res).Should(helpers.CMDSuccess(), "unable to apply %s", policyYAML)
+	}
+
+	Context("tunnel disabled with endpoint routes enabled", func() {
```
Comment (pchaigno) [inline test/k8sT/Egress.go:169]: Is it possible to refactor the 3 `Context` blocks to avoid duplicate code? They seem identical except for some of the Cilium options.

**Review by pchaigno — COMMENTED** [review]
Looks good overall, only minor stuff below :slightly_smiling_face:

File: test/helpers/kubectl.go (hunk 5 above)
Comment (kkourt) [reply test/helpers/kubectl.go:4300]: I think it's because the test is using a `cilium-test` namespace. IMHO, having a separate commit just for this change is not worth it.

Comment (pchaigno) [reply test/helpers/kubectl.go:4300]: > I think it's because the test is using a cilium-test namespace.

I saw that, but if we're using cilium-test I don't get why we even need `GenerateNamespaceForTest` :-/

File: test/k8sT/manifests/egress-ip-deployment.yaml (hunk 8 above)
Comment (kkourt) [reply test/k8sT/manifests/egress-ip-deployment.yaml:31]: Since this seems to be similar to what we have in our docs, https://docs.cilium.io/en/latest/gettingstarted/egress-gateway/#configure-egress-ips, are we sure we want to change it?

Comment (pchaigno) [reply test/k8sT/manifests/egress-ip-deployment.yaml:31]: I think so yes, unless we can use the exact same file for both the test and the docs. We'll also need to remove that manifest from the docs at some point anyway because it's very confusing to users (they often blindly apply it without understanding what it does).

File: bpf/lib/nodeport.h (hunk 3 above)
Comment (kkourt) [reply bpf/lib/nodeport.h:1986]: fixed

File: bpf/lib/nodeport.h (hunk 4 above)
Comment (kkourt) [reply bpf/lib/nodeport.h]: fixed.

File: test/k8sT/Egress.go (hunk 6 above)
Comment (kkourt) [reply test/k8sT/Egress.go]: fixed.

File: test/helpers/kubectl.go (hunk 5 above)
Comment (kkourt) [reply test/helpers/kubectl.go:4300]: To be addressed in:  #17581

File: test/k8sT/Egress.go (hunk 11 above)
Comment (kkourt) [reply test/k8sT/Egress.go:82]: To be addressed in:  #17581

File: test/k8sT/Egress.go (hunk 12 above)
Comment (kkourt) [reply test/k8sT/Egress.go:95]: To be addressed in:  #17581

File: test/k8sT/manifests/egress-ip-deployment.yaml (hunk 8 above)
Comment (kkourt) [reply test/k8sT/manifests/egress-ip-deployment.yaml:31]: To be addressed in:  #17581

File: test/k8sT/Egress.go (hunk 14 above)
Comment (kkourt) [reply test/k8sT/Egress.go:169]: To be addressed in:  #17581

File: test/k8sT/Egress.go (hunk 13 above)
Comment (kkourt) [reply test/k8sT/Egress.go:251]: To be addressed in:  #17581

**Review by pchaigno — APPROVED** [review]
LGTM.

FYI, the diff is also available here :point_down: , by clicking on `force-pushed`: 
image

**Comment by kkourt** [comment]
After Paul's ✅  and reasoning on https://github.com/cilium/cilium/pull/17517#issuecomment-940913196, marking ready-to-merge.
