### PR TITLE
metricsmap: fix retrieval of possible CPU count

### LINKED ISSUE #4559: CLI: "unable to parse sysfs to get CPU count"
It seems for any CLI command executed, the message "unable to parse sysfs to get CPU count" is printed.

```
$ cilium endpoint list
level=error msg="unable to parse sysfs to get CPU count" error="input does not match format"
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])   IPv6                 IPv4            STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                     
20928      Disabled           Disabled          59281      mesos:id=web-server           f00d::a0f:0:0:51c0   10.15.137.206   ready   
23520      Disabled           Disabled          4          reserved:health               f00d::a0f:0:0:5be0   10.15.162.64    ready
```

```
$ cilium status
level=error msg="unable to parse sysfs to get CPU count" error="input does not match format"
KVStore:                Ok         Consul: 172.18.0.2:8300
ContainerRuntime:       Ok         docker daemon: OK
Kubernetes:             Disabled   
Cilium:                 Ok         OK
NodeMonitor:            Disabled
Cilium health daemon:   Ok   
IPv4 address pool:      4/65535 allocated
IPv6 address pool:      3/65535 allocated
Controller Status:      15/15 healthy
Proxy Status:           OK, ip 10.15.0.1, port-range 10000-20000
Cluster health:   1/1 reachable   (2018-06-19T15:14:28Z)
```

This happens with current master in the mesos guide. (a new mesos guide version is available in https://github.com/cilium/cilium/pull/4558)

The bug is probably caused by 
https://github.com/cilium/cilium/blob/a5910535291914762cd80d6b596d4cd40f115362/pkg/maps/metricsmap/metricsmap.go#L243-L267

### PR DESCRIPTION
**Pull request by brb**
We use `/sys/devices/system/cpu/possible` to get a number of possible CPUs. The number is used to determine how many entries there are per value in a BPF map of the `BPF_MAP_TYPE_*_PERCPU_*` type.

Previously, the retrieval function contained two bugs:

- It didn't handle the case of sparse CPU allocations.
- It logged the error when only one CPU was possible.

The side-effect of the second bug was that upon issuing a cilium cli cmd, `level=error msg="unable to parse sysfs to get CPU count" error="input does not match format"` was printed as a part of the cmd output.

Fixes #4559.

I'm going to fix https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/testing/selftests/bpf/bpf_util.h#n10 (from which the function was previously derived) once the PR has been approved.

Signed-off-by: Martynas Pumputis <martynas@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6427)

### CODE REVIEW

**Comment by brb** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by brb** [comment]
test-me-please

File: pkg/maps/metricsmap/metricsmap_test.go [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+		{"0-7", 8},
+		{"0,2-3", 3},
+		{"", 0},
+		{"foobar", 0},
+	}
+
+	for _, t := range tests {
+		f, err := ioutil.TempFile("", "")
+		c.Assert(err, IsNil)
+		defer func() { os.Remove(f.Name()) }()
```
Comment (joestringer) [inline pkg/maps/metricsmap/metricsmap_test.go]: If `getNumPossibleCPUsFromFile()` received a reader of some sort, then you wouldn't need this logic.

I'm also not strictly sure whether `defer()`s will run if you perform `c.Assert()`. I feel like I've had problems with similar sorts of unit tests before where I ended up leaving files behind if the test fails.

File: pkg/maps/metricsmap/metricsmap.go [hunk 2]
```diff
@@ -200,49 +195,47 @@ func SyncMetricsMap() error {
...
+		// So, just ignore it, as a partial match (e.g. when there is only one
+		// CPU) is expected.
+		n, _ := fmt.Sscanf(s, "%d-%d", &start, &end)
+
+		switch n {
+		case 0:
 			log.WithError(err).Error("failed to retrieve number of possible CPUs!")
-		} else if n == 1 {
-			end = start
+			return 0
```
Comment (joestringer) [inline pkg/maps/metricsmap/metricsmap.go:236]: While you're looking at this code, do you think we should include 's' in the error message above on line 231/225? This code is unlikely to trigger but it'd be nice to know what the input was if it is ever triggered.

**Review by joestringer — CHANGES_REQUESTED** [review]
I'm not sure that in the event of a test failure that the files are guaranteed to be cleaned up. Would you mind taking a look at that?

File: pkg/maps/metricsmap/metricsmap.go (hunk 2 above)
Comment (brb) [reply pkg/maps/metricsmap/metricsmap.go:236]: Good idea, sure!

File: pkg/maps/metricsmap/metricsmap_test.go (hunk 1 above)
Comment (brb) [reply pkg/maps/metricsmap/metricsmap_test.go]: Just validated - if any `c.Assert` invoked after the `defer` fails, the `defer` will be run.

Anyway, I like the idea of passing `io.Reader` instead, so I will change accordingly.

**Comment by brb** [comment]
test-me-please

File: pkg/maps/metricsmap/metricsmap.go [hunk 3]
```diff
@@ -200,49 +199,52 @@ func SyncMetricsMap() error {
...
-func calculateNumCpus() {
-	var start, end int
+// getNumPossibleCPUs returns a total number of possible CPUS, i.e. CPUs that
+// have been allocated resources and can be brought online if they are present.
+// The number is retrieved by parsing /sys/device/system/cpu/possible.
+//
+// See https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/linux/cpumask.h?h=v4.19#n50
+// for more details.
+func getNumPossibleCPUs() int {
+	f, err := os.Open(possibleCPUSysfsPath)
```
Comment (joestringer) [inline pkg/maps/metricsmap/metricsmap.go:209]: Missing the corresponding `f.Close()`?

**Review by joestringer — CHANGES_REQUESTED** [review]
The changes look good, much simpler. However the close of the file seems to be missing now.

File: pkg/maps/metricsmap/metricsmap.go (hunk 3 above)
Comment (brb) [reply pkg/maps/metricsmap/metricsmap.go:209]: Oops, fixed.

**Comment by brb** [comment]
test-me-please

**Comment by brb** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
