### PR TITLE
fix: reallocate envoy port on binding failure

### LINKED ISSUE #42858: Cilium Ingress fails to recover from port binding errors
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.18.4 and lower than v1.19.0

### What happened?

When all Cilium Ingress resources in the cluster are deleted, the iptables tproxy rules may not be cleaned up properly. If another process then binds to the orphaned port, and a new Ingress resource with the same `ingressClass: cilium` is created, `cilium-envoy` fails to bind to the port with an "Address already in use" error. The system does not attempt to use a different port, causing the Ingress to remain in a failed state.

### How can we reproduce the issue?

1. Create a Cilium Ingress resource with `ingressClass: cilium`:
   ```yaml
   apiVersion: networking.k8s.io/v1
   kind: Ingress
   metadata:
     name: test-ingress
   spec:
     ingressClassName: cilium
     rules:
     - host: example.com
       http:
         paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: example-service
               port:
                 number: 80
   ```

2. Verify that the Ingress is working and note the port that tproxy `cilium-envoy` is using (check `iptables -t mangle -L` on the node).

3. Delete all of cilium ingress class Ingress resource:
   ```bash
   kubectl delete ingress test-ingress
   ```

4. On the same node where Cilium is running, bind another process to the same port that was used by the Ingress:
   ```bash
   # On the node, use netcat to listen on the port
   # Replace <port> with the actual port number used by tproxy of cilium-envoy
   nc -l <port>
   ```
   
   **Note**: You can find the port by examining iptables rules that may still reference the port.

5. Create the Ingress resource again with the same configuration:
   ```bash
   kubectl apply -f test-ingress.yaml
   ```

6. Observe that `cilium-envoy` fails to bind with an "Address already in use" error and does not recover. Check the logs:
   ```bash
   kubectl logs -n kube-system -l app.kubernetes.io/name=cilium-agent
   ```

### Cilium Version

1.18.4

### Kernel Version

6.8.0

### Kubernetes Version

v1.33.5

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell
### node(force intercept tproxy port)

ubuntu@worker7:~$ sudo iptables -t mangle -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
CILIUM_PRE_mangle  all  --  anywhere             anywhere             /* cilium-feeder: CILIUM_PRE_mangle */

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
CILIUM_POST_mangle  all  --  anywhere             anywhere             /* cilium-feeder: CILIUM_POST_mangle */

Chain CILIUM_POST_mangle (1 references)
target     prot opt source               destination

Chain CILIUM_PRE_mangle (1 references)
target     prot opt source               destination
MARK       all  --  anywhere             anywhere             socket --transparent mark match ! 0xe00/0xf00 mark match ! 0x800/0xf00 /* cilium: any->pod redirect proxied traffic to host proxy */ MARK set 0x200
TPROXY     tcp  --  anywhere             anywhere             mark match 0x11a90200 /* cilium: TPROXY to host cilium-dns-egress proxy */ TPROXY redirect 127.0.0.1:43281 mark 0x200/0xffffffff
TPROXY     udp  --  anywhere             anywhere             mark match 0x11a90200 /* cilium: TPROXY to host cilium-dns-egress proxy */ TPROXY redirect 127.0.0.1:43281 mark 0x200/0xffffffff
TPROXY     tcp  --  anywhere             anywhere             mark match 0x6a300200 /* cilium: TPROXY to host kube-system/cilium-ingress/listener proxy */ TPROXY redirect 127.0.0.1:12394 mark 0x200/0xffffffff
TPROXY     udp  --  anywhere             anywhere             mark match 0x6a300200 /* cilium: TPROXY to host kube-system/cilium-ingress/listener proxy */ TPROXY redirect 127.0.0.1:12394 mark 0x200/0xffffffff

Chain KUBE-IPTABLES-HINT (0 references)
target     prot opt source               destination

Chain KUBE-KUBELET-CANARY (0 references)
target     prot opt source               destination

ubuntu@worker7:~$ nc -l 12394
# ...


### cilium-agent

time=2025-11-18T15:32:54.402425338Z level=warn msg="completing NACK: &{32 type.googleapis.com/envoy.config.listener.v3.Listener map[]}" module=agent.controlplane.envoy-proxy xdsAckedVersion=31 xdsNonce=32 xdsClientNode=127.0.0.1 xdsTypeURL=type.googleapis.com/envoy.config.listener.v3.Listener
time=2025-11-18T15:32:54.402466826Z level=warn msg="NACK received for versions between the reported version up to the response nonce; waiting for a version update before sending again" module=agent.controlplane.envoy-proxy xdsStreamID=5 xdsClientNode=host~127.0.0.1~no-id~localdomain version=31 xdsTypeURL=type.googleapis.com/envoy.config.listener.v3.Listener xdsNonce=32 xdsDetail="Error adding/updating listener(s) kube-system/cilium-ingress/listener: cannot bind '127.0.0.1:12394': Address already in use\n"
time=2025-11-18T15:33:09.408677171Z level=info msg="starting xDS stream processing" module=agent.controlplane.envoy-proxy xdsStreamID=14 xdsTypeURL=type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment
time=2025-11-18T15:33:09.409073265Z level=info msg="Received first request in a new xDS stream" module=agent.controlplane.envoy-proxy xdsStreamID=14 xdsClientNode=host~127.0.0.1~no-id~localdomain version="" xdsTypeURL=type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment xdsNonce=""
time=2025-11-18T15:33:09.424436204Z level=warn msg="completing NACK: &{34 type.googleapis.com/envoy.config.listener.v3.Listener map[]}" module=agent.controlplane.envoy-proxy xdsAckedVersion=33 xdsNonce=34 xdsClientNode=127.0.0.1 xdsTypeURL=type.googleapis.com/envoy.config.listener.v3.Listener
time=2025-11-18T15:33:09.42447919Z level=warn msg="NACK received for versions between the reported version up to the response nonce; waiting for a version update before sending again" module=agent.controlplane.envoy-proxy xdsStreamID=5 xdsClientNode=host~127.0.0.1~no-id~localdomain version=33 xdsTypeURL=type.googleapis.com/envoy.config.listener.v3.Listener xdsNonce=34 xdsDetail="Error adding/updating listener(s) kube-system/cilium-ingress/listener: cannot bind '127.0.0.1:12394': Address already in use\n"


### cilium-envoy

[2025-11-18 15:35:54.649][7][error][config] [external/envoy/source/common/listener_manager/listener_manager_impl.cc:1241] listener 'kube-system/cilium-ingress/listener' failed to bind or apply socket options: cannot bind '127.0.0.1:12394': Address already in use
[2025-11-18 15:35:54.649][7][warning][config] [external/envoy/source/extensions/config_subscription/grpc/grpc_subscription_impl.cc:138] gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) kube-system/cilium-ingress/listener: cannot bind '127.0.0.1:12394': Address already in use
```

### Anything else?

_No response_

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by inerplat**
Fixes: #42858

This PR adds:

1. **Port binding error detection** (`isPortBindingError`): Detects port binding failures by checking error messages for common indicators like "cannot bind", "address already in use", and "eaddrinuse".

2. **Port reallocation function** (`AllocateCRDProxyPortWithReallocate`): Forces reallocation of a new port by resetting both `ProxyPort` and `rulesPort` when `forceReallocate` is true, ensuring a truly new random port is allocated.

3. **Retry logic** (`retryWithNewPorts`): When a port binding failure is detected:
   - Reallocates a new port for affected listeners
   - Clones only the listeners that need port reallocation (for efficiency)
   - Updates listener addresses with the new port
   - Updates port allocation callbacks
   - Retries the Envoy resource update

4. **Integration** (`Update` method): Integrates the retry logic into the Envoy reconciler's update flow.

**Testing**
- [x] Tested manually by reproducing the issue scenario
- [x] Verified that port reallocation works correctly
- [x] Confirmed that iptables rules are updated with the new port
- [x] Ensured backward compatibility (existing functionality unchanged)

```release-note
Fix: Cilium Ingress now automatically reallocates ports and retries when cilium-envoy fails to bind due to port conflicts
```

### CODE REVIEW

**Comment by inerplat** [comment]
Oops, I missed the test code for the newly added function.

I have re-verified the previously failing test suites:
- `lint-go` was executed locally and passed successfully.
- `Integration Tests (ci-integration)` were run on my personal fork, and the [workflow](  https://github.com/inerplat/cilium/actions/runs/19642010324/job/56247707870) completed successfully

Could you please re-run the tests to confirm everything is working correctly? @pchaigno

**Comment by inerplat** [comment]
@pchaigno 
Regarding the failed Cilium `E2E Upgrade (ci-e2e-upgrade)` test, I verified that it passed successfully on my personal fork using the same commit SHA `158060f`.

Successful run: https://github.com/inerplat/cilium/actions/runs/19655926227

The error appears to be a transient failure. Could you please re-run the failed job?

Failed job: https://github.com/cilium/cilium/actions/runs/19645818650/job/56260701695

Thanks!

File: pkg/ciliumenvoyconfig/cec_resource_parser.go [hunk 1]
```diff
@@ -115,6 +115,7 @@ func newCECResourceParser(params parserParams) *CECResourceParser {
 
 type PortAllocator interface {
 	AllocateCRDProxyPort(name string) (uint16, error)
+	AllocateCRDProxyPortWithReallocate(name string, forceReallocate bool) (uint16, error)
```
Comment (jrajahalme) [inline pkg/ciliumenvoyconfig/cec_resource_parser.go]: This interface would be cleaner if the new function was just:
```
ReallocateCRDProxyPort(name string) (uint16, error)
```

File: pkg/ciliumenvoyconfig/reconciler.go [hunk 2]
```diff
@@ -77,6 +85,78 @@ func (ops *envoyOps) Prune(ctx context.Context, txn statedb.ReadTxn, objects ite
...
+func (ops *envoyOps) retryWithNewPorts(ctx context.Context, prevResources, resources envoy.Resources) error {
+	newListeners := make([]*envoy_config_listener.Listener, 0, len(resources.Listeners))
+
+	for _, listener := range resources.Listeners {
+		if listener.GetInternalListener() != nil {
+			newListeners = append(newListeners, listener)
+			continue
+		}
+
+		if listener.GetAddress() != nil {
```
Comment (jrajahalme) [inline pkg/ciliumenvoyconfig/reconciler.go]: Unfortunately this check does not have the effect it should.

Specifically, the port should NOT be reallocated if it was already specified in the CEC/CCEC resource where this listener was specified. When not specified in the CEC/CCEC resource, the `ParseResources` function allocates the proxy port with `AllocateCRDProxyPort`, and only in this case is it correct to try to reallocate the listener port. If the listener address was already specified in the CEC/CCEC resource, it may also have a specific IP address and a specific port, and reallocating a new localhost port would be incorrect.

It looks like `resources.PortAllocationCallbacks` will have an entry for the listener only if the port was dynamically allocated via `AllocateCRDProxyPort`, so maybe this could be used as a condition where the reallocation is skipped if `resources.PortAllocationCallbacks` is empty or does not have an entry for this listener?

File: pkg/ciliumenvoyconfig/reconciler.go [hunk 3]
```diff
@@ -90,6 +170,23 @@ func (ops *envoyOps) Update(ctx context.Context, txn statedb.ReadTxn, _ statedb.
...
 	err := ops.xds.UpdateEnvoyResources(ctx, prevResources, resources)
+
+	if err != nil && isPortBindingError(err) {
+		ops.log.Warn("Port binding failed, attempting to reallocate ports and retry",
+			logfields.Error, err)
+
+		retryResources := resources
+		retryErr := ops.retryWithNewPorts(ctx, prevResources, retryResources)
+		if retryErr == nil {
+			resources = retryResources
```
Comment (jrajahalme) [inline pkg/ciliumenvoyconfig/reconciler.go]: I'm not sure if update of `resources` is allowed here, @joamaki could you chime in here? Is `res.Resources` here considered read-only, i.e., is it stored in statedb? If yes, what would be the right way to retry with a new proxy port number? If not, then the shallow-copies here and cloning of the listener in `retryWithNewPorts` would not be necessary.

**Review by jrajahalme — CHANGES_REQUESTED** [review]

**Comment by jrajahalme** [comment]
@joamaki Could you take a look, especially if the Listener resource mutation (with the new proxy port) happens in the right place w.r.t. statedb read-only data?

File: pkg/ciliumenvoyconfig/reconciler.go (hunk 3 above)
Comment (joamaki) [reply pkg/ciliumenvoyconfig/reconciler.go]: `Update` is called with a shallow cloned (https://github.com/cilium/cilium/blob/main/pkg/ciliumenvoyconfig/tables.go#L251) object so it is allowed to modify it. As you're not mutating the existing `resources.Listeners` but rather creating a new one this should all be fine.

Comment (joamaki) [reply pkg/ciliumenvoyconfig/reconciler.go]: One more thing though. The reconciler reconciles objects with a read txn and persists results at the end with a write txn. If there's a conflict the resulting new object is thrown away. So you'll need to make sure this is idempotent as it might get retried and earlier changes to `resources.Listeners` have been thrown away.

File: pkg/ciliumenvoyconfig/cec_resource_parser.go (hunk 1 above)
Comment (inerplat) [reply pkg/ciliumenvoyconfig/cec_resource_parser.go]: Thanks for the review! 🤗 @jrajahalme 
I've updated the interface to use ReallocateCRDProxyPort(name string) (uint16, error) as you recommended. The interface now looks like:

https://github.com/cilium/cilium/pull/42859/changes#diff-1bbbcb1785e27b5d2be51df46efe33be7d93d08d88161524302b52b358a20806R118

The ReallocateCRDProxyPort implementation always forces reallocation, making the intent clearer.

File: pkg/ciliumenvoyconfig/reconciler.go (hunk 2 above)
Comment (inerplat) [reply pkg/ciliumenvoyconfig/reconciler.go]: Great catch! I've implemented your suggestion. The code now uses resources.PortAllocationCallbacks to determine if a port was dynamically allocated:

https://github.com/cilium/cilium/pull/42859/changes#diff-0203f5650506b33cc97358a93c91be0c16212dd6ad01ffefc5708011cbad9f19R126-R127

Additionally, before calling retryWithNewPorts, I check if there are any dynamically allocated ports:

https://github.com/cilium/cilium/pull/42859/changes#diff-0203f5650506b33cc97358a93c91be0c16212dd6ad01ffefc5708011cbad9f19R191-R202

This ensures that listeners with explicitly specified addresses in CEC/CCEC (like hostNetwork mode with specific port) will never have their ports reallocated.

File: pkg/ciliumenvoyconfig/reconciler.go (hunk 3 above)
Comment (inerplat) [reply pkg/ciliumenvoyconfig/reconciler.go]: Thanks @joamaki  for the clarification!
To ensure idempotency, I've made two changes:

1. retryWithNewPorts returns the updated resources instead of modifying in place:
https://github.com/cilium/cilium/pull/42859/changes#diff-0203f5650506b33cc97358a93c91be0c16212dd6ad01ffefc5708011cbad9f19R155-R157

2. Reconciled listener addresses are preserved across retries: When ReconciledResources exists, listener addresses from previous successful reconciliation are copied to current resources:
https://github.com/cilium/cilium/pull/42859/changes#diff-0203f5650506b33cc97358a93c91be0c16212dd6ad01ffefc5708011cbad9f19R172-R185

This ensures that if a port was reallocated in a previous cycle but the write txn had a conflict, the next retry will use the reallocated port from ReconciledResources rather than re-parsing the original CEC (which would have the old port).

**Comment by inerplat** [comment]
@jrajahalme 
I’ve rebased my branch to fix the CI failure caused by the missing flag in the upstream, so could you please trigger the tests again?

File: pkg/ciliumenvoyconfig/reconciler.go [hunk 4]
```diff
@@ -87,9 +167,59 @@ func (ops *envoyOps) Update(ctx context.Context, txn statedb.ReadTxn, _ statedb.
...
+				logfields.Error, err)
+
+			updatedResources, retryErr := ops.retryWithNewPorts(ctx, prevResources, resources)
+			if retryErr == nil {
+				resources = updatedResources
+				err = nil
+			} else {
+				ops.log.Error("Failed to retry with new ports after binding failure",
+					logfields.Error, retryErr)
+				return fmt.Errorf("failed to reallocate ports after binding failure: %w (original error: %w)", retryErr, err)
```
Comment (jrajahalme) [inline pkg/ciliumenvoyconfig/reconciler.go:207]: It would be more idiomatic Go to check for error, return from the if block and then not have an else block at all, e.g.:
```
	updatedResources, retryErr := ops.retryWithNewPorts(ctx, prevResources, resources)
	if retryErr != nil {
		ops.log.Error("Failed to retry with new ports after binding failure",
			logfields.Error, retryErr)
		return fmt.Errorf("failed to reallocate ports after binding failure: %w (original error: %w)", retryErr, err)
	}
	resources = updatedResources
	err = nil
```
Also, should not log the error IF the caller is going to log the returned error anyway (did not check it that is the case).

File: pkg/ciliumenvoyconfig/script_test.go [hunk 5]
```diff
@@ -516,6 +516,11 @@ func (s staticPortAllocator) AllocateCRDProxyPort(name string) (uint16, error) {
 	return 1000, nil
 }
 
+// ReallocateCRDProxyPort implements PortAllocator.
+func (s staticPortAllocator) ReallocateCRDProxyPort(name string) (uint16, error) {
+	return 1000, nil
```
Comment (jrajahalme) [inline pkg/ciliumenvoyconfig/script_test.go]: maybe return `1001` here just to make the point that it is different?

File: pkg/proxy/proxyports/proxyports_test.go [hunk 6]
```diff
@@ -323,3 +323,56 @@ func TestRestoredPort(t *testing.T) {
...
+
+	// First allocation using AllocateCRDProxyPort
+	port1, err := p.AllocateCRDProxyPort("listener1")
+	require.NoError(t, err)
+	require.NotEqual(t, uint16(0), port1)
+
+	// ACK the port to set rulesPort
+	err = p.AckProxyPortWithReference(context.TODO(), "listener1")
+	require.NoError(t, err)
+
```
Comment (jrajahalme) [inline pkg/proxy/proxyports/proxyports_test.go]: Upon a bind failure it would be expected that the originally allocated port is NOT acknowledged. So this part of the test should be removed

**Review by jrajahalme — CHANGES_REQUESTED** [review]
Looking good, only small nits left. After addressing these, please squash the commits together to retain cleaner commit history when this is merged (we do not squash automatically on merge).

**Comment by inerplat** [comment]
@jrajahalme Thanks for the review. I have addressed all the comments and squashed the commits as requested.

Regarding the logging concern:
> Also, should not log the error IF the caller is going to log the returned error anyway (did not check it that is the case).

I verified the behavior and confirmed that the returned error is **not** logged to stdout/stderr by the caller. Instead, I observed that the error is persisted in `statedb` through the existing error handling mechanism.
Therefore, I decided to keep the warn log when `hasDynamicallyAllocatedPorts` is true to explicitly indicate that a "port binding failed and a retry is in progress." Detailed root causes can be inspected via `statedb` (using `cilium-dbg`).

Here are the verification results from my local reproduction:

**Case 1: Port conflict triggers reallocation (Success)**
The warning logs appear as expected, and the port is successfully reallocated.

```text
time=2026-01-24T04:26:08.744569461Z level=warn msg="NACK received for versions between the reported version up to the response nonce; waiting for a version update before sending again" module=agent.controlplane.envoy-proxy xdsStreamID=3 xdsClientNode=host~127.0.0.1~no-id~localdomain version=170 xdsTypeURL=[type.googleapis.com/envoy.config.listener.v3.Listener](https://type.googleapis.com/envoy.config.listener.v3.Listener) xdsNonce=171 xdsDetail="Error adding/updating listener(s) kube-system/cilium-ingress/listener: cannot bind '127.0.0.1:17523': Address already in use\n"

time=2026-01-24T04:26:08.744682142Z level=warn msg="Port binding failed, attempting to reallocate ports and retry" module=agent.controlplane.ciliumenvoyconfig error="NACK received: Error adding/updating listener(s) kube-system/cilium-ingress/listener: cannot bind '127.0.0.1:17523': Address already in use\n"

time=2026-01-24T04:26:08.760985838Z level=info msg="Reallocated proxy port due to binding failure" module=agent.controlplane.ciliumenvoyconfig listener=kube-system/cilium-ingress/listener proxyPort=14616
```

**Case 2: Port range exhaustion (Error Persistence)**
I simulated a scenario where no ports are available (`--proxy-portrange-max=10000`, `--proxy-portrange-min=10000`). The error persists and is correctly reflected in statedb.

Agent Logs:

```text
time=2026-01-24T04:23:46.400139593Z level=warn msg="NACK received for versions between the reported version up to the response nonce; waiting for a version update before sending again" module=agent.controlplane.envoy-proxy xdsStreamID=4 xdsClientNode=host~127.0.0.1~no-id~localdomain version=160 xdsTypeURL=[type.googleapis.com/envoy.config.listener.v3.Listener](https://type.googleapis.com/envoy.config.listener.v3.Listener) xdsNonce=161 xdsDetail="Error adding/updating listener(s) kube-system/cilium-ingress/listener: cannot bind '127.0.0.1:10000': Address already in use\n"

time=2026-01-24T04:23:46.400433595Z level=warn msg="Port binding failed, attempting to reallocate ports and retry" module=agent.controlplane.ciliumenvoyconfig error="NACK received: Error adding/updating listener(s) kube-system/cilium-ingress/listener: cannot bind '127.0.0.1:10000': Address already in use\n"
```

StateDB Verification (cilium-dbg):

```bash
$ cilium-dbg shell -- db/show envoy-resources
Name                             Listeners                           Endpoints                           References                          Status   Since   Error
# ...
cec:kube-system/cilium-ingress   kube-system/cilium-ingress/listener                                                                     Error    10s     failed to reallocate ports after binding failure: failed to reallocate proxy port for listener kube-system/cilium-ingress/listener: no available proxy ports (original error: NACK received: Error adding/updating listener(s) kube-system/cilium-ingress/listener: cannot bind '127.0.0.1:10000': Address already in use)

$ cilium-dbg statedb | grep failed
    {"ID":{"Module":["agent","controlplane","ciliumenvoyconfig"],"Component":["job-reconcile"]},"Level":"Degraded","Message":"1 error(s)","Error":"failed to reallocate ports after binding failure: failed to reallocate proxy port for listener kube-system/cilium-ingress/listener: no available proxy ports (original error: NACK received: Error adding/updating listener(s) kube-system/cilium-ingress/listener: cannot bind '127.0.0.1:10000': Address already in use\n)","LastOK":"0001-01-01T00:00:00Z","Updated":"2026-01-24T04:19:31.152330937Z","Stopped":"0001-01-01T00:00:00Z","Final":"","Count":165},
    {"Name":{"Origin":"cec","Cluster":"","Namespace":"kube-system","Name":"cilium-ingress"},"Status":{"updated-at":"2026-01-24T04:19:31.150824728Z","error":"failed to reallocate ports after binding failure: failed to reallocate proxy port for listener kube-system/cilium-ingress/listener: no available proxy ports (original error: NACK received: Error adding/updating listener(s) kube-system/cilium-ingress/listener: cannot bind '127.0.0.1:10000': Address already in use\n)","id":543,"kind":"Error"}
# ...
```

**Review by jrajahalme — APPROVED** [review]
