### PR TITLE
cilium: fix redirect limits on multi dev case

### LINKED ISSUE #13331: follow-up todos for redirect set
TODOs 1.9:
- [x] rebuild bpftool for cilium container (https://github.com/cilium/image-tools/pull/64)
- [x] Helm option
- [x] Documentation for upgrade guide
- [x] multi-dev support + CI (pod-pod, pod-world, routing w/o neigh?)
   - [x] https://patchwork.ozlabs.org/project/netdev/patch/20201008145314.116800-1-toke@redhat.com/
- [x] CI test coverage on bpf-next tree (waiting on packet-ci llvm11 decision)
  - [x] vbox updates for bpf-next (redirect_peer still needed in master, https://github.com/cilium/cilium/pull/13862)
- [x] status output
- [x] move redir peer under host routing
- [x] https://github.com/cilium/cilium/pull/13330#discussion_r498446694
- [x] https://github.com/cilium/cilium/pull/13330#discussion_r498007895
- [x] redirect neigh signature update
- [x] follow-up on https://github.com/cilium/cilium/pull/12441
- [x] Pod to Pod bench for blog
- [x] status dump for time clock source

TODO fixes:

- [x] ICMP csum below seen with ping from Podns to remote hostns (Pod to Pod does not trigger it), needs investigation whether general datapath issue or only redirect_neigh related (only ICMP, not seen on TCP); also investigate host->pod:
```
[17073.035858] eth0: hw csum failure
[17073.036335] skb len=64 headroom=110 headlen=64 tailroom=1490
               mac=(76,14) net=(90,20) trans=110
               shinfo(txflags=0 nr_frags=0 gso(size=0 type=0 segs=0))
               csum(0x0 ip_summed=2 complete_sw=0 valid=0 level=0)
               hash(0xff6828d9 sw=0 l4=0) proto=0x0800 pkttype=0 iif=15
[17073.038651] dev name=eth0 feat=0x0x000061104fdd59e9
[17073.039114] skb linear:   00000000: 00 00 21 91 34 aa 00 28 9a 1c 7f 5f 00 00 00 00
[17073.039587] skb linear:   00000010: c3 4d 0e 00 00 00 00 00 10 11 12 13 14 15 16 17
[17073.040076] skb linear:   00000020: 18 19 1a 1b 1c 1d 1e 1f 20 21 22 23 24 25 26 27
[17073.040545] skb linear:   00000030: 28 29 2a 2b 2c 2d 2e 2f 30 31 32 33 34 35 36 37
[17073.041007] CPU: 2 PID: 0 Comm: swapper/2 Not tainted 5.9.0-rc6bench+ #140
[17073.041008] Hardware name: Supermicro X10SLM-F/X10SLM-F, BIOS 1.1b 11/01/2013
[17073.041008] Call Trace:
[17073.041009]  <IRQ>
[17073.041015]  dump_stack+0x74/0x95
[17073.041018]  netdev_rx_csum_fault.part.122+0x40/0x50
[17073.041019]  netdev_rx_csum_fault+0x2b/0x30
[17073.041022]  __skb_checksum_complete+0xee/0x100
[17073.041024]  ? skb_send_sock_locked+0x2c0/0x2c0
[17073.041025]  ? reqsk_fastopen_remove+0x1a0/0x1a0
[17073.041026]  icmp_rcv+0xa8/0x3b0
[17073.041029]  ip_protocol_deliver_rcu+0x193/0x1c0
[17073.041030]  ip_local_deliver_finish+0x48/0x50
[17073.041031]  ip_local_deliver+0x7e/0xe0
[17073.041032]  ? ip_rcv_finish_core.isra.22+0x66/0x430
[17073.041033]  ip_rcv_finish+0x86/0xa0
[17073.041034]  ip_rcv+0xbc/0xd0
[17073.041036]  __netif_receive_skb_one_core+0x86/0xa0
[17073.041037]  __netif_receive_skb+0x18/0x60
[17073.041039]  process_backlog+0xa9/0x170
[17073.041040]  net_rx_action+0x140/0x3e0
[17073.041043]  __do_softirq+0xe4/0x2da
[17073.041045]  asm_call_on_stack+0x12/0x20
[17073.041045]  </IRQ>
[17073.041048]  do_softirq_own_stack+0x3f/0x50
[17073.041050]  irq_exit_rcu+0xa4/0xb0
[17073.041052]  common_interrupt+0x79/0x140
[17073.041054]  asm_common_interrupt+0x1e/0x40
[17073.041056] RIP: 0010:poll_idle+0x95/0xbd
[17073.041057] Code: ff 7f 5b 44 89 e8 41 5c 41 5d 41 5e 5d c3 4c 89 f7 48 89 de e8 ac 7c de ff 49 89 c6 b8 c9 00 00 00 65 48 8b 14 25 c0 7b 01 00 <48> 8b 12 83 e2 08 75 aa f3 90 83 e8 01 75 e8 65 8b 3d 25 44 30 4a
[17073.041058] RSP: 0018:ffffbb43400a3e30 EFLAGS: 00000202
[17073.041059] RAX: 0000000000000010 RBX: ffff9b45ffd37700 RCX: 000000000000001f
[17073.041059] RDX: ffff9b45fc0b96c0 RSI: ffff9b45ffd37700 RDI: ffffffffb695c5e0
[17073.041060] RBP: ffffbb43400a3e50 R08: 0000000000000002 R09: 000000000002b840
[17073.041060] R10: ffffbb43400a3e00 R11: 00000000000003cb R12: 00000f87203c7949
[17073.041061] R13: 0000000000000000 R14: 00000000000007d0 R15: ffffffffb695c5e0
[17073.041065]  cpuidle_enter_state+0x92/0x3d0
[17073.041066]  cpuidle_enter+0x2e/0x40
[17073.041068]  do_idle+0x224/0x2b0
[17073.041069]  cpu_startup_entry+0x1d/0x20
[17073.041071]  start_secondary+0x111/0x150
[17073.041073]  secondary_startup_64+0xa4/0xb0
```

### PR DESCRIPTION
**Pull request by borkmann**
Few misc leftover items from #13331.
Closes: #13331

### CODE REVIEW

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
retest-net-next

File: bpf/lib/fib.h [hunk 1]
```diff
@@ -0,0 +1,120 @@
...
+	struct bpf_fib_lookup fib_params = {
+		.family		= AF_INET,
+		.ifindex	= ctx->ingress_ifindex,
+		.ipv4_src	= ip4->saddr,
+		.ipv4_dst	= ip4->daddr,
+	};
+
+	ret = fib_lookup(ctx, &fib_params, sizeof(fib_params),
+			 BPF_FIB_LOOKUP_DIRECT);
+	if (unlikely(ret == BPF_FIB_LKUP_RET_NOT_FWDED || ret < 0))
```
Comment (pchaigno) [inline bpf/lib/fib.h]: Don't we also need to check for `BPF_FIB_LKUP_RET_BLACKHOLE`, `BPF_FIB_LKUP_RET_UNREACHABLE`, and `BPF_FIB_LKUP_RET_PROHIBIT`?

File: pkg/datapath/linux/config/config.go [hunk 2]
```diff
@@ -583,6 +583,9 @@ func (h *HeaderfileWriter) writeTemplateConfig(fw *bufio.Writer, e datapath.Endp
 			return err
 		}
 		fmt.Fprintf(fw, "#define DIRECT_ROUTING_DEV_IFINDEX %d\n", directRoutingIfIndex)
+		if option.Config.NodePortHairpin {
+			fmt.Fprintf(fw, "#define ENABLE_SKIP_FIB 1\n")
```
Comment (pchaigno) [inline pkg/datapath/linux/config/config.go:587]: Why can we skip the FIB lookup in case of a one-legged load balancer? If it's just because there's a single interface, maybe best to write it explicitly:
```go
if len(option.Config.Devices) == 1 {
```

File: pkg/client/client.go [hunk 3]
```diff
@@ -416,6 +416,15 @@ func FormatStatusResponse(w io.Writer, sr *models.StatusResponse, sd StatusDetai
 		fmt.Fprintf(w, "Masquerading:\t%s\n", status)
 	}
 
+	if sr.ClockSource != nil {
+		status := sr.ClockSource.Mode
+		if sr.ClockSource.Mode == models.ClockSourceModeJiffies {
+			status = fmt.Sprintf("%s\t[%d Hz]",
+				sr.ClockSource.Mode, sr.ClockSource.Hertz)
+		}
+		fmt.Fprintf(w, "Clock Source for BPF:\t%s\n", status)
```
Comment (pchaigno) [inline pkg/client/client.go:429]: Should this be under `--verbose`? It looks minor compared to the other information we dump in `cilium status`. It's a single line so I don't have a strong opinion :slightly_smiling_face:

**Review by pchaigno — APPROVED** [review]
Minor comments only.

File: pkg/datapath/linux/config/config.go (hunk 2 above)
Comment (borkmann) [reply pkg/datapath/linux/config/config.go:587]: Yeah, it's exactly for that reason. I can write it explicitly, the NodePortHairpin is the same, but maybe it's more readable when it's spelled out as `len(option.Config.Devices) == 1`.

File: pkg/client/client.go (hunk 3 above)
Comment (borkmann) [reply pkg/client/client.go:429]: No strong opinion either. :) I can do that.

File: bpf/lib/fib.h [hunk 4]
```diff
@@ -0,0 +1,120 @@
...
+		return CTX_ACT_DROP;
+	if (ret == BPF_FIB_LKUP_RET_NO_NEIGH) {
+		nh_params.nh_family = fib_params.family;
+		__bpf_memcpy_builtin(&nh_params.ipv6_nh, &fib_params.ipv6_dst,
```
Comment (brb) [inline bpf/lib/fib.h:101]: Shouldn't we s/6/4/?

File: bpf/lib/fib.h [hunk 5]
```diff
@@ -0,0 +1,120 @@
...
+}
+#endif /* ENABLE_IPV6 */
+
+#ifdef ENABLE_IPV4
+static __always_inline int
+redirect_direct_v4(struct __ctx_buff *ctx __maybe_unused,
+		   int l3_off __maybe_unused,
+		   struct iphdr *ip4 __maybe_unused)
+{
+# ifdef ENABLE_REDIRECT_FAST
```
Comment (brb) [inline bpf/lib/fib.h]: Do we need this #ifdef? The caller already checks whether it's defined.

File: bpf/lib/fib.h [hunk 6]
```diff
@@ -0,0 +1,120 @@
...
+	return redirect(oif, 0);
+#  endif /* ENABLE_SKIP_FIB */
+# endif /* ENABLE_REDIRECT_FAST */
+	return CTX_ACT_DROP;
+}
+#endif /* ENABLE_IPV6 */
+
+#ifdef ENABLE_IPV4
+static __always_inline int
+redirect_direct_v4(struct __ctx_buff *ctx __maybe_unused,
```
Comment (brb) [inline bpf/lib/fib.h:71]: I think a function comment describing high-level logic would be useful.

File: bpf/lib/fib.h [hunk 7]
```diff
@@ -0,0 +1,120 @@
...
+		   int l3_off __maybe_unused,
+		   struct iphdr *ip4 __maybe_unused)
+{
+# ifdef ENABLE_REDIRECT_FAST
+	int ret, nh_size = 0, oif = DIRECT_ROUTING_DEV_IFINDEX;
+	struct bpf_redir_neigh *nh = NULL;
+	bool no_neigh = true;
```
Comment (brb) [inline bpf/lib/fib.h]: Shouldn't this be set to false? Otherwise, I don't see how this can become non-true.

**Review by brb — COMMENTED** [review]
A few comments.

File: bpf/lib/fib.h (hunk 4 above)
Comment (borkmann) [reply bpf/lib/fib.h:101]: The v4 gw could also be v6 based on kernel code, so this follows also the selftest.

File: bpf/lib/fib.h (hunk 5 above)
Comment (borkmann) [reply bpf/lib/fib.h]: yeah I'll remove

File: bpf/lib/fib.h (hunk 7 above)
Comment (borkmann) [reply bpf/lib/fib.h]: indeed, good catch, it should be `no_neigh = !is_defined(EMABLE_SKIP_FIB)`

**Comment by borkmann** [comment]
test-me-please

**Review by brb — APPROVED** [review]

**Comment by borkmann** [comment]
retest-runtime

**Comment by borkmann** [comment]
net-next hitting https://github.com/cilium/cilium/issues/12596

**Comment by pchaigno** [comment]
> net-next hitting #12596

It looks like a different flake actually, the error messages are different.

**Comment by borkmann** [comment]
retest-net-next

**Comment by borkmann** [comment]
One (unrelated to PR) issue I saw with ICMP & BPF masq during local testing despite correct native-routing-cidr is: https://github.com/cilium/cilium/issues/12544#issuecomment-660004540 . Happens when host-legacy-routing is off and also on.

**Comment by borkmann** [comment]
test-focus K8sDatapathConfig*

**Comment by borkmann** [comment]
test-focus K8sPolicyTest*

**Review by christarazi — APPROVED** [review]

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-focus K8sDatapathConfig*

File: Documentation/operations/upgrade.rst [hunk 8]
```diff
@@ -333,6 +333,15 @@ Annotations:
   install --set ipv4.enabled=true``. The following section calls out specific
   values where the prefix cannot be simply dropped followed by a full
   table of old and new Helm values.
+* In case the BPF kube-proxy replacement is enabled under direct routing operation
+  as well as BPF-based masquerading, then the agent will probe the underlying
+  kernel for availability of BPF-based routing and neighbor resolution in the
```
Comment (ti-mo) [inline Documentation/operations/upgrade.rst]: > the agent will probe the underlying kernel for availability of BPF-based routing and neighbor resolution

Where does this feature availability check take place? I couldn't find anything directly related in these commits.

> it also means that netfilter/iptables rules in the host namespace are not considered

Default behavioural changes like these should be featured a bit more prominently, as this one in particular significantly alters the way in which a packet moves through the kernel. This might interfere with other networking-related tools the user might have deployed, don't underestimate the amount of observability tooling built around iptables that will suddenly be disarmed for good. :slightly_smiling_face:  Right now this info is a bit buried in context.

We should lead with the most important info:
> **On kernel 5.10 and above, running the BPF kube-proxy replacement could bypass iptables in the host network namespace in some cases.**

.. and then continue providing detailed background info.

Alternatively, if we have many such gotchas in a release, we could consider adding a 'breaking changes' heading with distilled information to give a better overview.

File: api/v1/openapi.yaml [hunk 9]
```diff
@@ -2500,6 +2503,22 @@ definitions:
...
+    properties:
+      mode:
+        description: Datapath clock source
+        type: string
+        enum:
+        - ktime
+        - jiffies
+      hertz:
+        description: Kernel Hz
+        type: integer
```
Comment (brb) [inline api/v1/openapi.yaml:2521]: Having current time would be very useful when debugging e.g. CT issues. Maybe worth adding?

File: Documentation/operations/upgrade.rst (hunk 8 above)
Comment (aanm) [reply Documentation/operations/upgrade.rst]: +1!

**Review by aanm — APPROVED** [review]
Nothing else to point out besides what Timo point it out already.

File: Documentation/operations/upgrade.rst (hunk 8 above)
Comment (borkmann) [reply Documentation/operations/upgrade.rst]: Makes sense, I'll rewrite this bit. Keep in mind that 5.10 is not out the gate, so users are not running it at this point hence also no breakage from live-upgrade. Anyway, I'll make it a bit more clear.

**Comment by borkmann** [comment]
test-focus K8sPolicyTest*

**Comment by borkmann** [comment]
test-me-please

**Review by kaworu — APPROVED** [review]
Helm related changes LGTM

**Review by ti-mo — APPROVED** [review]

**Comment by borkmann** [comment]
test-focus K8sPolicyTest*

**Comment by borkmann** [comment]
test-focus K8sPolicyTest*

**Comment by borkmann** [comment]
test-focus K8sPolicyTest*

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-focus K8sPolicyTest*

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-focus K8sPolicyTest*

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-focus K8sPolicyTest*

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-focus K8sPolicyTest*

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-focus K8sPolicyTest*

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
(Potentially related for 1.8 https://github.com/cilium/cilium/issues/12205 where https://github.com/cilium/cilium/pull/13884/commits/bd340764a9cdbff359f2091539bceff4f9cad5a1 might potentially solve it.)

**Comment by borkmann** [comment]
retest-4.9

**Comment by borkmann** [comment]
retest-4.19

**Comment by borkmann** [comment]
retest-4.9

**Comment by borkmann** [comment]
retest-net-next

**Comment by borkmann** [comment]
test-focus K8sService*

**Comment by borkmann** [comment]
retest-net-next

**Comment by borkmann** [comment]
test-focus K8sService*

**Comment by borkmann** [comment]
retest-net-next

**Comment by borkmann** [comment]
test-focus K8sService*

**Comment by borkmann** [comment]
retest-net-next
