### PR TITLE
Change default ENI property FirstInterfaceIndex to 0 and improve IPAM logic in ENI & Azure modes

### LINKED ISSUE #13217: Cilium fails to start due to unavailable addresses
## Bug report

**General Information**

General Information

Cilium version 1.8.3 f842660 2020-09-16T15:05:27-07:00 go version go1.14.9 linux/amd64
docker tag v1.8 cilium@sha256:d80f2cc60a590f013d971e3006484b006ee724309459b02cd2b0128cc634ff40
Kernel version 4.14.193-149.317.amzn2.x86_64
Orchestration system version in use kube 1.15.11 on EKS

**How to reproduce the issue**
Cilium fails to start due to unavailable addresses. The following log is for t3a.small instance.  I can fix it by going in to ciliumnodes and changing to` first-interface-index: 0`  and to `pre-allocate: 4`.
```
cilium-agent
[Sep 18, 2020 2:23:09 PM GMT+3]
level=info msg="Using autodetected VPC CIDR." subsys=ipam vpc-cidr=10.253.0.0/16
cilium-agent
[Sep 18, 2020 2:23:09 PM GMT+3]
level=info msg="Waiting for IPs to become available in CRD-backed allocation pool" available=4 helpMessage="Check if cilium-operator pod is running and does not have any warnings or error messages." name=ip-10-xxx-xxx-xxx.eu-west-1.compute.internal required=8 subsys=ipam
cilium-agent
[Sep 18, 2020 2:23:14 PM GMT+3]
level=info msg="Ignoring autodetected VPC CIDR." native-routing-cidr=10.xxx.0.0/16 subsys=ipam vpc-cidr=10.xxx.0.0/16

```
1. Install using Get started for EKS using helm, on existing self-managed nodes using t3a.micro and t3a.small instances

### PR DESCRIPTION
**Pull request by christarazi**
See commit msgs.

Fixes: https://github.com/cilium/cilium/pull/13865
Fixes: https://github.com/cilium/cilium/issues/13217

### CODE REVIEW

**Comment by christarazi** [comment]
test-me-please

File: pkg/ipam/node.go [hunk 1]
```diff
@@ -203,6 +200,7 @@ func (n *Node) getPreAllocate() int {
 	if n.resource.Spec.ENI.PreAllocate != 0 {
 		return n.resource.Spec.ENI.PreAllocate
 	}
+
```
Comment (christarazi) [inline pkg/ipam/node.go]: Nit: unnecessary change

File: pkg/aws/eni/node.go [hunk 2]
```diff
@@ -538,3 +539,43 @@ func (n *Node) GetMaximumAllocatableIPv4() int {
...
+	if !limitsAvailable {
+		n.loggerLocked().WithFields(logrus.Fields{
+			"adaptors-limit":        "unknown",
+			"first-interface-index": index,
+			"pre-allocate":          minimum,
+		}).Warning("Could not determine instance limits, falling back to default pre-allocate value")
+		return minimum
+	}
+
+	return math.IntMin(minimum, limits.Adapters*limits.IPv4)
```
Comment (tgraf) [inline pkg/aws/eni/node.go]: I guess this should be something like this in case `FirstInterfaceIndex` is not `0`.

``` go
if index >= limits.Adapters {
   return 0
}

return math.IntMin(minimum, (limits.Adapters-index)*limits.IPv4)
```

**Review by tgraf — CHANGES_REQUESTED** [review]
LGTM

Considering the migration. Existing nodes will continue with index 1. New nodes will start with 0. I think this warrants an entry in the upgrade guide to ensure users understand that the index must be set to 1 if the current behavior should be kept.

File: pkg/aws/eni/node.go (hunk 2 above)
Comment (christarazi) [reply pkg/aws/eni/node.go]: Ah good catch. Fixed. 

Yep will add an entry to the upgrade guide.

File: pkg/aws/eni/node.go [hunk 3]
```diff
@@ -538,3 +539,49 @@ func (n *Node) GetMaximumAllocatableIPv4() int {
 	// Return the maximum amount of IP addresses allocatable on the instance
 	return (limits.Adapters - firstInterfaceIndex) * limits.IPv4
 }
+
+// GetMinimumAllocatableIPv4 returns the minimum amount of IPv4 addresses that
+// must be allocated to the instance.
+func (n *Node) GetMinimumAllocatableIPv4() int {
+	n.mutex.RLock()
+	defer n.mutex.RUnlock()
```
Comment (qmonnet) [inline pkg/aws/eni/node.go:564]: My knowledge of mutexes in Golang is limited, so this is probably a naive question. Isn't the `n.mutex.RLock()` above defeated by the `n.mutex.Lock()` that you take before calling the `GetMinimumAllocatableIPv4()` function?

**Review by qmonnet — COMMENTED** [review]
One question below to better understand what you do with the mutexes, but looks good to me otherwise

File: pkg/aws/eni/node.go (hunk 3 above)
Comment (christarazi) [reply pkg/aws/eni/node.go:564]: Good question. Looking at the code, I see why you're confused. The answer doesn't have to do with anything specific to Golang mutexes. The `Node` in `GetMinimumAllocatableIPv4()` refers to the `pkg/aws/eni.Node` type, whereas at the site of the caller where the `Lock()` takes place as you observed is of type `pkg/ipam.Node`. These mutexes are locking different structures, although they are named the same, so it can be confusing to misleading to readers.  :)

File: Documentation/operations/upgrade.rst [hunk 4]
```diff
@@ -347,6 +347,10 @@ Annotations:
   as well as the default CNI plugins shipped by most managed Kubernetes
   distributions. Set the ``cni.exclusive=false`` Helm flag to disable this
   behaviour.
+* For AWS ENI IPAM mode, Cilium has changed the ``first-interface-index``
+  default from ``1`` to ``0``. Existing nodes in the cluster will continue to
+  use ``1`` and new nodes will use ``0``. In order to stay with Cilium's
+  current behavior, set the value to ``0`` in the CiliumNode resource.
```
Comment (Robert-Stam) [inline Documentation/operations/upgrade.rst]: ``0`` --> ``1``

**Review by Robert-Stam — COMMENTED** [review]
1 small comment issue, further LGTM, however see: https://cilium.slack.com/archives/C53TG4J4R/p1612348650081200?thread_ts=1610618291.011600&cid=C53TG4J4R

File: pkg/aws/eni/node.go (hunk 3 above)
Comment (qmonnet) [reply pkg/aws/eni/node.go:564]: Ah I see, ok thank you! :)

**Review by qmonnet — APPROVED** [review]
Looks good from my side.

File: Documentation/operations/upgrade.rst (hunk 4 above)
Comment (christarazi) [reply Documentation/operations/upgrade.rst]: Good catch, thanks. Fixed

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
test-me-please

File: pkg/aws/eni/node.go [hunk 5]
```diff
@@ -538,3 +539,49 @@ func (n *Node) GetMaximumAllocatableIPv4() int {
...
+
+	if n.k8sObj == nil || n.k8sObj.Spec.ENI.FirstInterfaceIndex == nil {
+		n.loggerLocked().WithFields(logrus.Fields{
+			"adaptors-limit": "unknown",
+			"pre-allocate":   minimum,
+		}).Warning("Could not determine first-interface-index, falling back to default pre-allocate value")
+		return minimum
+	}
+
+	index := *n.k8sObj.Spec.ENI.FirstInterfaceIndex
```
Comment (tgraf) [inline pkg/aws/eni/node.go:576]: Is this safe? Can't `FirstInterfaceIndex` be nil?

**Review by tgraf — CHANGES_REQUESTED** [review]
Please update the upgrade instructions a bit more to make it clear what the implications of the change are:


> For AWS ENI IPAM mode, Cilium has changed the ``first-interface-index``
  default from ``1`` to ``0``. This means that pods will start using IPs of ``eth0`` instead of ``eth1``. This allows using the maximum number of IPs available on an instance by default. **Be aware:** Depending on your security groups configuration of the ``eth0`` interface, pods may be associated with a different security group all of a sudden. In order to stay with Cilium's current behavior, set the value to ``1`` in the CiliumNode resource.

File: pkg/aws/eni/node.go (hunk 5 above)
Comment (christarazi) [reply pkg/aws/eni/node.go:576]: Yes, there is a check for it already a few lines above.

**Comment by christarazi** [comment]
Previous push consisted of rebasing and addresses @tgraf's suggestions about the upgrade guide.

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
test-runtime

**Review by tgraf — APPROVED** [review]

**Review by jibi — APPROVED** [review]

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
test-me-please

**Comment by aanm** [comment]
hit https://github.com/cilium/cilium/issues/11847 merging...
