### PR TITLE
policy: Fix Deny Precedence Bug

### LINKED ISSUE #15198: ClusterWideNetworkPolicy deny to CIDR not enforced
## Bug report

**General Information**

I am running a Kubernetes cluster on AWS and I want to restrict access to the AWS metadata service by default such that it is opt in. It seems that the `CiliumClusterwideNetworkPolicy` is not enforced when using `egressDeny` with `toCIDR`.

- Cilium version (run `cilium version`)
```
# cilium version
Client: 1.7.5 f524ca028 2020-06-12T14:10:36+02:00 go version go1.13.12 linux/amd64
Daemon: 1.7.5 f524ca028 2020-06-12T14:10:36+02:00 go version go1.13.12 linux/amd64
```
- Kernel version (run `uname -a`)
```
# uname -r
5.4.92-flatcar
```

Policy that is not getting enforced by cilium:
```
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "block-aws-metadata-service"
spec:
  endpointSelector:
    matchExpressions:
      - key: k8s:io.kubernetes.pod.namespace
        operator: NotIn
        values:
          - kube-system
  egressDeny:
  - toCIDR:
    - 169.254.169.254/32
```

**How to reproduce the issue**

1. `kubectl apply` the "block-aws-metadata-service" policy to the cluster
2. exec into a pod that is not in kube-system and run `curl http://169.254.169.254`

I would expect that this request will time out, but it does succeed.

### PR DESCRIPTION
**Pull request by nathanjsweet**
When the policy map state is created CIDRs
are now checked against one another to ensure
that deny-rules that supersede allow-rules
when they should.

Fixes: #15198

```release-note
policy: Promote Deny Policies from Beta to Stable
```

### CODE REVIEW

File: pkg/policy/mapstate.go [hunk 1]
```diff
@@ -147,6 +152,29 @@ func (e *MapStateEntry) RemoveDependent(key Key) {
 	}
 }
 
+func (e *MapStateEntry) getNets(identities Identities, id identity.NumericIdentity) []*net.IPNet {
```
Comment (jrajahalme) [inline pkg/policy/mapstate.go]: The receiver `e` is not used, so maybe this should be a bare function?

File: pkg/policy/mapstate.go [hunk 2]
```diff
@@ -292,23 +320,30 @@ func (keys MapState) deleteKeyWithChanges(key Key, owner MapStateOwner, adds, de
...
+	newEntryNets := newEntry.getNets(identities, identity.NumericIdentity(newKey.Identity))
 
 	if newEntry.IsDeny {
-		// case for an existing allow L4-only and we are inserting deny L3-only
 		switch {
+		// case for inserting a deny L3-only
 		case newKey.DestPort == 0 && newKey.Nexthdr == 0 && newKey.Identity != 0:
 			l4OnlyAllows := MapState{}
+			// look for broad allows "all/unknown" identity and insert the same
+			// entry, but with the specifc L3-deny identity. This ensures that
```
Comment (jrajahalme) [inline pkg/policy/mapstate.go]: typo

File: pkg/policy/mapstate.go [hunk 3]
```diff
@@ -292,23 +320,30 @@ func (keys MapState) deleteKeyWithChanges(key Key, owner MapStateOwner, adds, de
...
+			// the broad allow is being overriden in the marginal circumstance of
+			// as subset of its allow being denied by another policy.
 			for k, v := range keys {
+				vNets := v.getNets(identities, identity.NumericIdentity(k.Identity))
 				if newKey.TrafficDirection == k.TrafficDirection &&
 					!v.IsDeny &&
-					k.Identity == 0 && (k.DestPort != 0 || k.Nexthdr != 0) {
+					(k.Identity == 0 || netsContainAny(newEntryNets, vNets)) &&
```
Comment (jrajahalme) [inline pkg/policy/mapstate.go]: break the if statement into two so that `vNets` is computed only if needed.

File: pkg/policy/mapstate.go [hunk 4]
```diff
@@ -392,6 +449,23 @@ func (keys MapState) denyPreferredInsertWithChanges(newKey Key, newEntry MapStat
 	keys.redirectPreferredInsert(newKey, newEntry, adds, deletes)
 }
 
+func netsContainAny(a, b []*net.IPNet) bool {
+	for _, an := range a {
+		aMask, _ := an.Mask.Size()
+		aIsIPv4 := an.IP.To4() != nil
+		for _, bn := range b {
+			bIsIPv4 := bn.IP.To4() != nil
+			if aIsIPv4 == bIsIPv4 {
```
Comment (jrajahalme) [inline pkg/policy/mapstate.go:458]: What about IPv6?

File: pkg/policy/distillery_test.go [hunk 5]
```diff
@@ -381,28 +383,58 @@ func (d *policyDistillery) distillPolicy(owner PolicyOwner, epLabels labels.Labe
...
+	l4IngressPolicy.Detach(selectorCache)
+	result.clearOwners()
+
+	// Prepare the L4 policy so we know whether L4 policy may apply
+	egressL4 := SearchContext{
+		From:  epLabels,
+		Trace: TRACE_VERBOSE,
+	}
+	egressL4.Logging = stdlog.New(d.log, "", 0)
+	io.WriteString(d.log, fmt.Sprintf("[distill] Evaluating L4 Engress -> %s", epLabels))
```
Comment (joestringer) [inline pkg/policy/distillery_test.go]: nit:
```suggestion
	io.WriteString(d.log, fmt.Sprintf("[distill] Evaluating L4 Egress -> %s", epLabels))
```

File: pkg/policy/mapstate.go [hunk 6]
```diff
@@ -292,23 +320,30 @@ func (keys MapState) deleteKeyWithChanges(key Key, owner MapStateOwner, adds, de
...
 
 	if newEntry.IsDeny {
-		// case for an existing allow L4-only and we are inserting deny L3-only
 		switch {
+		// case for inserting a deny L3-only
 		case newKey.DestPort == 0 && newKey.Nexthdr == 0 && newKey.Identity != 0:
 			l4OnlyAllows := MapState{}
+			// look for broad allows "all/unknown" identity and insert the same
+			// entry, but with the specifc L3-deny identity. This ensures that
+			// the broad allow is being overriden in the marginal circumstance of
```
Comment (joestringer) [inline pkg/policy/mapstate.go]:
```suggestion
			// the broad allow is being overridden in the marginal circumstance of
```

File: pkg/policy/mapstate.go [hunk 7]
```diff
@@ -292,23 +320,30 @@ func (keys MapState) deleteKeyWithChanges(key Key, owner MapStateOwner, adds, de
...
+			// as subset of its allow being denied by another policy.
```
Comment (joestringer) [inline pkg/policy/mapstate.go]:
```suggestion
			// the broad allow is being overriden in the marginal circumstance of
			// a subset of its allow being denied by another policy.
```

File: pkg/policy/mapstate.go [hunk 8]
```diff
@@ -392,6 +449,23 @@ func (keys MapState) denyPreferredInsertWithChanges(newKey Key, newEntry MapStat
 	keys.redirectPreferredInsert(newKey, newEntry, adds, deletes)
 }
 
+func netsContainAny(a, b []*net.IPNet) bool {
```
Comment (joestringer) [inline pkg/policy/mapstate.go]:
```suggestion
// netsContainAny checks whether any IP range in 'a' is a superset of any IP range in 'b'.
func netsContainAny(a, b []*net.IPNet) bool {
```

(This is probably also a good candidate to sit in `pkg/ip` as a generic IP range comparison function, in case we need it again in future)

File: pkg/policy/mapstate.go [hunk 9]
```diff
@@ -147,6 +152,29 @@ func (e *MapStateEntry) RemoveDependent(key Key) {
...
+	lbls := identities.GetLabels(id)
+	var nets []*net.IPNet
+	for _, lbl := range lbls {
+		if lbl.Source == labels.LabelSourceCIDR {
+			_, netIP, err := net.ParseCIDR(lbl.Key)
+			if err == nil {
+				nets = append(nets, netIP)
+			}
+		}
+	}
```
Comment (joestringer) [inline pkg/policy/mapstate.go]: It's worth noting that, let's say the identity is for the CIDR `10.0.0.0/8`, there will be the following labels:

- `reserved:world`
- `cidr:0.0.0.0/0`
- `cidr:0.0.0.0/1`
- `cidr:0.0.0.0/2`
- `cidr:0.0.0.0/3`
- `cidr:0.0.0.0/4`
- `cidr:8.0.0.0/5`
- `cidr:8.0.0.0/6`
- `cidr:10.0.0.0/7`
- `cidr:10.0.0.0/8`

A comment above this function that describes such behaviour would go a long way to prevent misuse of this utility function.

Comment (joestringer) [reply pkg/policy/mapstate.go]: Looking a bit closer at the usage in the functions below, I think that you're expecting this function to only return the most-specific IP range for `id`.

If we had the actual `*identity`, then we could potentially look up the cached `id.CIDRLabel` field, but it's also valid to just go through the labels and find the most specific CIDR range.

File: pkg/policy/mapstate.go [hunk 10]
```diff
@@ -345,25 +380,47 @@ func (keys MapState) denyPreferredInsertWithChanges(newKey Key, newEntry MapStat
...
 		default:
-			// Do not insert 'newKey' if the map state already denies traffic
+			// We do not insert 'newKey' if the map state already denies traffic
 			// which is a superset of (or equal to) 'newKey'
 			newKeyCpy := newKey
 			newKeyCpy.DestPort = 0
 			newKeyCpy.Nexthdr = 0
 			v, ok := keys[newKeyCpy]
 			if ok && v.IsDeny {
-				// Found a L3-only Deny so we won't accept any L3-L4 policies
```
Comment (joestringer) [inline pkg/policy/mapstate.go:355]: Why is this comment being removed? Is it wrong?

File: pkg/policy/mapstate.go [hunk 11]
```diff
@@ -292,23 +320,30 @@ func (keys MapState) deleteKeyWithChanges(key Key, owner MapStateOwner, adds, de
...
 	// If we have a deny "all" we don't accept any kind of map entry
 	if v, ok := keys[allCpy]; ok && v.IsDeny {
 		return
 	}
+	newEntryNets := newEntry.getNets(identities, identity.NumericIdentity(newKey.Identity))
 
 	if newEntry.IsDeny {
-		// case for an existing allow L4-only and we are inserting deny L3-only
 		switch {
+		// case for inserting a deny L3-only
```
Comment (joestringer) [inline pkg/policy/mapstate.go]: Would this help clarify?

```suggestion
		// case for inserting a deny L3-only when there are existing allows for the same traffic at L3 or L4
```

Comment (joestringer) [reply pkg/policy/mapstate.go]: Actually, due to `(k.DestPort != 0 || k.Nexthdr != 0) `, this is still only handling the case where there is an existing l4-only allow.

File: pkg/policy/mapstate.go [hunk 12]
```diff
@@ -345,25 +380,47 @@ func (keys MapState) denyPreferredInsertWithChanges(newKey Key, newEntry MapStat
...
+		}
+		// Delete all L3-L4 if we are inserting a deny L3-only and
+		// there aren't allow L4-only for the existing deny L3-L4
+		for k, v := range keys {
+			vNets := v.getNets(identities, identity.NumericIdentity(k.Identity))
+			if k.TrafficDirection == newKey.TrafficDirection &&
+				(newKey.DestPort == 0 || k.DestPort == newKey.DestPort) &&
+				(newKey.Nexthdr == 0 || k.Nexthdr == newKey.Nexthdr) &&
+				!v.IsDeny &&
+				(k.Identity == newKey.Identity || netsContainAny(newEntryNets, vNets)) {
```
Comment (joestringer) [inline pkg/policy/mapstate.go]: Assuming that the `netContainsAny()` statement here evaluates that the specific CIDR for `vNets` is a subset of the specific CIDR for `newEntryNets`, this seems right :+1:

File: pkg/policy/mapstate.go [hunk 13]
```diff
@@ -345,25 +380,47 @@ func (keys MapState) denyPreferredInsertWithChanges(newKey Key, newEntry MapStat
...
 			newKeyCpy.Nexthdr = 0
 			v, ok := keys[newKeyCpy]
 			if ok && v.IsDeny {
-				// Found a L3-only Deny so we won't accept any L3-L4 policies
 				return
 			}
-		}
 
+		}
+		// Delete all L3-L4 if we are inserting a deny L3-only and
```
Comment (joestringer) [inline pkg/policy/mapstate.go]: The comment here says "inserting a deny L3-only", but the condition below also checks for the case where we are inserting a deny L3+L4.

File: pkg/policy/mapstate.go [hunk 14]
```diff
@@ -345,25 +380,47 @@ func (keys MapState) denyPreferredInsertWithChanges(newKey Key, newEntry MapStat
...
+				(k.Identity == newKey.Identity || netsContainAny(newEntryNets, vNets)) {
+				keys.deleteKeyWithChanges(k, nil, adds, deletes)
+			}
+		}
 		keys.addKeyWithChanges(newKey, newEntry, adds, deletes)
 		return
-	} else if newKey.Identity == 0 && newKey.DestPort != 0 {
-		// case for an existing deny L3-only and we are inserting allow L4-only
+	} else {
+		// Do not insert L3-L4 if we have inserted a deny L3-only or mathcing L3-L4 deny.
```
Comment (joestringer) [inline pkg/policy/mapstate.go]: I think the previous comment was trying to start with a high-level that this case is now for broadly inserting an allow into a mapstate that already has a conflicting deny. It would be good to retain that broad characterization to help center the reader onto the specific set of cases. (It may likely make sense to also include the new comment in addition, since it gets into more specifics)

Comment (joestringer) [reply pkg/policy/mapstate.go]: The new comment suggests that it's about not inserting L3-L4, but I think that this case will also prevent inserting an L3 allow if there is an existing L3 deny that matches a superset of the traffic.

Comment (joestringer) [reply pkg/policy/mapstate.go]: Maybe, 

```
// Do not insert the allow (L3 or L3-L4) if the existing map has a deny at L3 or L3-L4 that matches a superset of the allow rule
```

(feel free to accept/reject/change to suit, I know this is difficult to express both in English and in Go)

File: pkg/policy/mapstate.go [hunk 15]
```diff
@@ -345,25 +380,47 @@ func (keys MapState) denyPreferredInsertWithChanges(newKey Key, newEntry MapStat
...
 
+		}
+		// Delete all L3-L4 if we are inserting a deny L3-only and
+		// there aren't allow L4-only for the existing deny L3-L4
+		for k, v := range keys {
+			vNets := v.getNets(identities, identity.NumericIdentity(k.Identity))
+			if k.TrafficDirection == newKey.TrafficDirection &&
+				(newKey.DestPort == 0 || k.DestPort == newKey.DestPort) &&
+				(newKey.Nexthdr == 0 || k.Nexthdr == newKey.Nexthdr) &&
+				!v.IsDeny &&
```
Comment (joestringer) [inline pkg/policy/mapstate.go]: nit: I'd probably put the `!v.IsDeny` check at the start of the if statement here just to make it clearer that we only care about the case where we're inserting a deny that intersects with an existing allow rule. This would also be consistent with the way that the similar / reverse condition is laid out down on line 412.

File: pkg/policy/mapstate.go (hunk 10 above)
Comment (joestringer) [reply pkg/policy/mapstate.go:355]: I guess technically the new key could be either L4-only or L3-L4, but it otherwise still seems accurate.

File: pkg/policy/mapstate.go [hunk 16]
```diff
@@ -345,25 +392,47 @@ func (keys MapState) denyPreferredInsertWithChanges(newKey Key, newEntry MapStat
 				}
 			}
 		default:
-			// Do not insert 'newKey' if the map state already denies traffic
+			// We do not insert 'newKey' if the map state already denies traffic
 			// which is a superset of (or equal to) 'newKey'
```
Comment (joestringer) [inline pkg/policy/mapstate.go]: nit: With the current code, I think that if we attempt to insert a new L3 deny that is more specific than an existing L3 deny (eg insert a deny 10.0.0.0/8 when 0.0.0.0/0 is already denied), this will result in two entries being inserted, one for each deny.  I think that this is ~OK, but it's subtly different from what this (existing) comment is describing, which is that in such a case we wouldn't insert the deny 10.0.0.0/8.

In order for the code to match the comment, we would probably need to do a check here also for whether there is any superset deny of `newKey` in `keys` and skip in that case also. But that said, I'm not sure we actually need the implementation to do that. There's pluses and minuses to this - more iteration while handling inserts, but fewer map entries in this corner case.

One alternative is something like:
```suggestion
			// We do not insert 'newKey' if the map state already denies traffic
			// which is a superset of (or equal to) 'newKey'.
			// Caveat: In the case of overlapping CIDRs, multiple denies may be
			// inserted. We could optimize this further to minimize the set of
			// map entries, but the current implementation is functionally correct.
```

File: pkg/policy/mapstate.go [hunk 17]
```diff
@@ -374,12 +443,12 @@ func (keys MapState) denyPreferredInsertWithChanges(newKey Key, newEntry MapStat
...
 		}
-		keys.addKeyWithChanges(newKey, newEntry, adds, deletes)
-		return
+
 	}
 	// branch for adding a new allow L3-L4
-
 	newKeyCpy := newKey
 	newKeyCpy.DestPort = 0
 	newKeyCpy.Nexthdr = 0
```
Comment (joestringer) [inline pkg/policy/mapstate.go]: The conditional check below checks whether there is an L3-only deny that covers the new entry, and skips in that case. However, I think that the new code on lines 423-426 already handle this case so we probably don't need this check any more?

File: pkg/policy/mapstate.go (hunk 9 above)
Comment (joestringer) [reply pkg/policy/mapstate.go]: (incidentally, given the above, I feel like there should be a bug that this code triggers but I can't quite wrap my head around what that bug would look like just yet.)

File: pkg/policy/mapstate.go (hunk 2 above)
Comment (joestringer) [reply pkg/policy/mapstate.go]: There's still a few typos in this comment. `specifc`, `as`

File: pkg/policy/mapstate.go [hunk 18]
```diff
@@ -292,23 +334,28 @@ func (keys MapState) deleteKeyWithChanges(key Key, owner MapStateOwner, adds, de
...
+			// look for broad allows "all/unknown" identity and insert the same
+			// entry, but with the specifc L3-deny identity. This ensures that
+			// the broad allow is being overridden in the marginal circumstance of
+			// as subset of its allow being denied by another policy.
 			for k, v := range keys {
 				if newKey.TrafficDirection == k.TrafficDirection &&
 					!v.IsDeny &&
-					k.Identity == 0 && (k.DestPort != 0 || k.Nexthdr != 0) {
+					(k.Identity == 0 ||
+						netsContainAny(newEntry.getNets(identities, newKey.Identity), v.getNets(identities, k.Identity))) &&
```
Comment (joestringer) [inline pkg/policy/mapstate.go]: incidentally, you could probably fold the `k.Identity == 0` check into the `netContainsAny` because the numeric identity `0` should contain all identities.

File: pkg/policy/mapstate.go [hunk 19]
```diff
@@ -807,7 +894,7 @@ func (mc *MapChanges) consumeMapChanges(policyMapState MapState) (adds, deletes
 			// insert but do not allow non-redirect entries to overwrite a redirect entry,
 			// nor allow non-deny entries to overwrite deny entries.
 			// Collect the incremental changes to the overall state in 'mc.adds' and 'mc.deletes'.
-			policyMapState.denyPreferredInsertWithChanges(mc.changes[i].Key, mc.changes[i].Value, adds, deletes)
+			policyMapState.denyPreferredInsertWithChanges(mc.changes[i].Key, mc.changes[i].Value, adds, deletes, nil)
```
Comment (joestringer) [inline pkg/policy/mapstate.go]: I presume that you plan to look closer into these `nil` cases? I'll skip thinking about them for now but I suspect they'll need to be populated somehow.

File: pkg/policy/distillery_test.go [hunk 20]
```diff
@@ -1127,3 +1160,167 @@ func Test_AllowAll(t *testing.T) {
...
+		WithEgressDenyRules([]api.EgressDenyRule{{
+			EgressCommonRule: api.EgressCommonRule{
+				ToCIDRSet: api.CIDRRuleSlice{worldSubnetRule},
+			},
+		}}).
+		WithEndpointSelector(api.WildcardEndpointSelector)
+	mapKeyL3L4__SubnetIngress = Key{worldSubnetIdentity.Uint32(), 0, 0, trafficdirection.Ingress.Uint8()}
+	mapKeyL3L4__SubnetEgress  = Key{worldSubnetIdentity.Uint32(), 0, 0, trafficdirection.Egress.Uint8()}
+
+	ruleL3L4__DenySmallerSubnet = api.NewRule().
```
Comment (joestringer) [inline pkg/policy/distillery_test.go]: These variables are named `ruleL3L4*`, but I only see an L3 component. Maybe these should be...?
```suggestion
	ruleL3____DenySmallerSubnet = api.NewRule().
```

Comment (joestringer) [reply pkg/policy/distillery_test.go]: incidentally just fyi, the reason for all these underscore characters in these variable names in the existing cases is just to allow the table to line up in the test listings below so it's easier to compare the results of the output.

File: pkg/policy/distillery_test.go [hunk 21]
```diff
@@ -1127,3 +1160,167 @@ func Test_AllowAll(t *testing.T) {
...
+		}}).
+		WithEgressRules([]api.EgressRule{{
+			EgressCommonRule: api.EgressCommonRule{
+				ToCIDRSet: api.CIDRRuleSlice{api.CIDRRule{Cidr: worldSubnet}},
+			},
+		}}).
+		WithEndpointSelector(api.WildcardEndpointSelector)
+
+	mapKeyL3L4__SmallerSubnetIngress = Key{worldIPIdentity.Uint32(), 0, 0, trafficdirection.Ingress.Uint8()}
+	mapKeyL3L4__SmallerSubnetEgress  = Key{worldIPIdentity.Uint32(), 0, 0, trafficdirection.Egress.Uint8()}
```
Comment (joestringer) [inline pkg/policy/distillery_test.go]: It looks like these are only evaluating the L3 conflict cases. It would be good to have corner cases to test the subsets in case of mixed L3 and L3L4 rules, eg a deny for a smaller L3 that conflicts with an allow for a wider L3+L4, or intersection between an L3-only and an L4-only rule, one deny and one not.

**Review by joestringer — CHANGES_REQUESTED** [review]
I think that this broad approach should work. There's one main concern I have with the logic to pull the CIDR from the identity labels below. A lot of the comments are a scattering of random typo fixes and proposed comment updates just to try to help the readability in this area of the code. Some of the comments date from the previous iteration of the change, as I didn't realize you were updating the PR concurrently.

We'll also want to delete the limitation from the docs as part of this PR after the following PR is merged: https://github.com/cilium/cilium/pull/23095

File: pkg/policy/mapstate.go (hunk 9 above)
Comment (nathanjsweet) [reply pkg/policy/mapstate.go]: > (incidentally, given the above, I feel like there should be a bug that this code triggers but I can't quite wrap my head around what that bug would look like just yet.)

I don't think there is a possible bug because the largest subnet in `a` will at least check against the smallest subnet in `b`.

File: pkg/policy/mapstate.go (hunk 11 above)
Comment (nathanjsweet) [reply pkg/policy/mapstate.go]: It is handling the case of a deny L3-only. What it is doing within that case is documented further down.

File: pkg/policy/mapstate.go (hunk 18 above)
Comment (nathanjsweet) [reply pkg/policy/mapstate.go]: Moving that function to `pkg/ip` precludes that I think, but I see what you mean.

File: pkg/policy/mapstate.go (hunk 10 above)
Comment (nathanjsweet) [reply pkg/policy/mapstate.go:355]: I removed it because it restated what the comment immediately above it already said. So it seems unnecessary.

File: pkg/policy/mapstate.go (hunk 14 above)
Comment (nathanjsweet) [reply pkg/policy/mapstate.go]: > I think the previous comment was trying to start with a high-level that this case is now for broadly inserting...

This comment is preserved on line 431 (below) where the logic was moved.

File: pkg/policy/mapstate.go (hunk 17 above)
Comment (nathanjsweet) [reply pkg/policy/mapstate.go]: That checks only the deny rules; this is here for the allow rules as well.

File: pkg/policy/mapstate.go (hunk 1 above)
Comment (nathanjsweet) [reply pkg/policy/mapstate.go]: This is definitely being used now.

File: pkg/policy/mapstate.go (hunk 9 above)
Comment (joestringer) [reply pkg/policy/mapstate.go]: The concern I have is that the largest subnet in `a` will be 0.0.0.0/0, and that will match any subnet in `b`. So rather than determining whether `b` is a subset, the function `NetsContainsAny()` always returns true with these inputs.

File: pkg/policy/mapstate.go (hunk 17 above)
Comment (joestringer) [reply pkg/policy/mapstate.go]: :thinking: I'm not sure I follow.

The above case does:

```
		for k, v := range keys {
			if v.IsDeny && k.TrafficDirection == newKey.TrafficDirection &&
				(k.DestPort == 0 || k.DestPort == newKey.DestPort) &&
				(k.Nexthdr == 0 || k.Nexthdr == newKey.Nexthdr) &&
				(k.Identity == 0 || k.Identity == newKey.Identity ||
					ip.NetsContainsAny(v.getNets(identities, k.Identity), newEntry.getNets(identities, newKey.Identity))) {
				return
			}
```

If we boil this down to the L3-only deny case that's being handled in these lines, we would get something like:

```
		for k, v := range keys {
			if v.IsDeny && k.TrafficDirection == newKey.TrafficDirection &&
				(k.DestPort == 0) &&
				(k.Nexthdr == 0) &&
				(k.Identity == newKey.Identity) {
				return
			}
```

Functionally this seems the same as the code below:

```
          newKeyCpy := newKey                                                                                                                                                                                                                                                              
          newKeyCpy.DestPort = 0                                                                                                                                                                                                                                                           
          newKeyCpy.Nexthdr = 0                                                                                                                                                                                                                                                            
          v, ok := keys[newKeyCpy]                                                                                                                                                                                                                                                         
          if ok && v.IsDeny {                                                                                                                                                                                                                                                              
                  // Found a L3-only Deny so we won't accept any L3-L4 allow policies                                                                                                                                                                                                      
                  return                                                                                                                                                                                                                                                                   
          }
```

File: pkg/policy/mapstate.go (hunk 9 above)
Comment (joestringer) [reply pkg/policy/mapstate.go]: (discussed out-of-band, should be an easy fix to find the most specific CIDR)

File: pkg/ip/cidr.go [hunk 22]
```diff
@@ -110,3 +110,23 @@ func IPsToNetPrefixes(ips []net.IP) []netip.Prefix {
...
+func NetsContainsAny(a, b []*net.IPNet) bool {
+	for _, an := range a {
+		aMask, _ := an.Mask.Size()
+		aIsIPv4 := an.IP.To4() != nil
+		for _, bn := range b {
+			bIsIPv4 := bn.IP.To4() != nil
+			isSameFamily := aIsIPv4 == bIsIPv4
+			if isSameFamily {
+				bMask, _ := bn.Mask.Size()
+				if an.Contains(bn.IP) && bMask >= aMask {
```
Comment (schlosna) [inline pkg/ip/cidr.go]: nit: Should we flip the condition to potentially short circuit on cheaper mask int comparison test first?

```suggestion
				if bMask >= aMask && an.Contains(bn.IP) {
```

**Review by qmonnet — APPROVED** [review]
Looks good, as far as I can tell

**Comment by christarazi** [comment]
CI is looking good :tada:

File: pkg/policy/mapstate.go [hunk 23]
```diff
@@ -147,6 +171,61 @@ func (e *MapStateEntry) RemoveDependent(key Key) {
...
+	if e.dependents == nil {
+		return false
+	}
+	_, ok := e.dependents[key]
+	return ok
+}
+
+// getNets gets every cidr associated with an identity.
+// This includes generated cidrs associated with this identity,
+// which mean that this slice can easily be dozens of subnets large.
```
Comment (jrajahalme) [inline pkg/policy/mapstate.go]: This comment is confusing given that the function below seems to return a slice of max 2 CIDRs?

File: pkg/policy/mapstate.go [hunk 24]
```diff
@@ -289,107 +368,139 @@ func (keys MapState) deleteKeyWithChanges(key Key, owner MapStateOwner, adds, de
...
-					kCpy.Identity = 0
-					if _, ok := l4OnlyAllows[kCpy]; !ok {
-						keys.deleteKeyWithChanges(k, nil, adds, deletes)
+			if !v.IsDeny {
+				if entryIdentityIsSupersetOf(k, v, newKey, newEntry, identities) {
+					if newKey.PortProtoIsBroader(k) {
+						// If this iterated-allow-entry is a superset of the new-entry
+						// and it has a more specific port-protocol than the new-entry
+						// then an additional copy of the new-entry with the more
+						// specific port-porotocol of the iterated-allow-entry must be inserted.
```
Comment (jrajahalme) [inline pkg/policy/mapstate.go]: typo "porotocol" -> "protocol"

**Review by jrajahalme — APPROVED** [review]
The way in which the internal loops in `denyPreferredInsertWithChanges()` are flipped, while simplifying the logic, make it super hard to track what changed and what did not change. It would have been beneficial to have a refactoring commit flipping the looping without any functional changes first, then have the functional changes in a separate commit.

**Comment by nbusseneau** [comment]
@nathanjsweet Do you wish to address the comment nits from Jarno before we merge? I see that CI is green, so if you only do a comment edit I will be OK to merge as-is without re-running the CI.

File: pkg/endpoint/bpf.go [hunk 25]
```diff
@@ -195,6 +197,21 @@ func (e *Endpoint) writeHeaderfile(prefix string) error {
...
+	*Endpoint
+}
+
+// GetLabels implements the policy.Identites interface{} method GetLabels,
+// which allows Endpoint.addNewRedirectsFromDesiredPolicy to call `l4.ToMapState`
+// with a label cache. This enables `l4.ToMapstate` to look up CIDRs associated with
+// identites to make a final determination about whether they should even be inserted into
+// an Endpoint's policy map.
+func (p *policyIdentitiesLabelLookup) GetLabels(id identity.NumericIdentity) labels.LabelArray {
+	ident := p.allocator.LookupIdentityByID(context.Background(), id)
```
Comment (christarazi) [inline pkg/endpoint/bpf.go:211]: This can actually return nil so we might have a potential nil ptr deref here

Comment (joestringer) [reply pkg/endpoint/bpf.go:211]: Looks like the caller attempts to iterate the result of this function, which should simply iterate zero times. It's a bit more elaborate than this example but I think the core behaviour should be the same:

https://go.dev/play/p/VxqzqgcGqkX

Comment (joestringer) [reply pkg/endpoint/bpf.go:211]: Yeah this code shouldn't just index into the result of this function. @nathanjsweet could you send a patch?

Comment (nathanjsweet) [reply pkg/endpoint/bpf.go:211]: For your consideration: https://github.com/cilium/cilium/pull/24416

**Comment by christarazi** [comment]
FYI, https://github.com/cilium/cilium/pull/24322 was merged which was introduced by this PR.
