### PR TITLE
Fix FQDN memory leak

### LINKED ISSUE #16300: Memory leak with FQDN policies
## Bug report

**General Information**

- Cilium version (run `cilium version`)
```
Client: 1.9.5 079bdaf 2021-03-10T13:12:19-08:00 go version go1.15.8 linux/amd64
Daemon: 1.9.5 079bdaf 2021-03-10T13:12:19-08:00 go version go1.15.8 linux/amd6
```
- Kernel version (run `uname -a`)
```
Linux 5.8.0-40-lowlatency #45~20.04.1-Ubuntu SMP PREEMPT Fri Jan 15 12:34:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
- Orchestration system version in use (e.g. `kubectl version`, ...)
```
v1.20.4+k3s1
```

- Generate and upload a system zip:
[cilium-sysdump-20210525-150354.zip](https://github.com/cilium/cilium/files/6539133/cilium-sysdump-20210525-150354.zip)

**Description**

One pod has memory leak. It happened a few days ago with another node(pod), restart pod had help
image

### PR DESCRIPTION
**Pull request by aanm**
In the FQDN architecture there's a DNS Cache per endpoint, used to track
which domain names each endpoint makes DNS requests, and a global DNS
Cache where its main functionality is to help tracking which
api.FQDNSelector present in the policy applies to locally running
endpoints. The latter, as opposed to the former, didn't have any
cleanup mechanism for the map that tracked which entries should be
garbage collected, making the global DNS Cache to grow.
This commit prevents those entries from being tracked for Garbage
Collection in the global DNS Cache.

Fixes https://github.com/cilium/cilium/issues/16300

```release-note
Fix memory leak that can occur with the presence of FQDN policies
```

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by joamaki — APPROVED** [review]
Just to double check that I understood this correctly: 
1) The memory leak was due to the "cleanup" map growing without bounds due to the default DNS cache not running a GC on the cache
2) The default DNS cache only contains a few entries which is on the order of number of local endpoints
3) These entries are cleaned up when the endpoints change, but we were left with the "cleanup" map entries?

If I understood correctly, then LGTM.

File: daemon/cmd/fqdn.go [hunk 1]
```diff
@@ -131,6 +131,10 @@ func (d *Daemon) bootstrapFQDN(possibleEndpoints map[uint16]*endpoint.Endpoint,
 		Cache:           fqdn.NewDNSCache(option.Config.ToFQDNsMinTTL),
 		UpdateSelectors: d.updateSelectors,
 	}
+	// Disable cleanup tracking on the default DNS cache. This cache simply
+	// tracks which api.FQDNSelector are present in policy which apply to
+	// locally running endpoints.
+	cfg.Cache.DisableCleanupTrack()
```
Comment (aditighag) [inline daemon/cmd/fqdn.go:137]: I read some of this code for the first time in the last week so I'm not fully familiar with it yet. But the fix seems a bit weird to me - isn't there a better way to handle fix this rather than disabling writes to the cache, thereby GC as the PR changes suggest?

**Review by aditighag — CHANGES_REQUESTED** [review]
Good spotting! I have some reservations about the temporary fix put in in this PR. /cc @jrajahalme who might have more context.

Edit: Also, is this a regression in recent releases? I'm surprised that the issue wasn't reported until now.

**Comment by aanm** [comment]
> Just to double check that I understood this correctly:
> 
> 1. The memory leak was due to the "cleanup" map growing without bounds due to the default DNS cache not running a GC on the cache

yes

> 2. The default DNS cache only contains a few entries which is on the order of number of local endpoints

not quite, from my experiments it contains as many entries as the number of DNS requests performed by each endpoint

> 3. These entries are cleaned up when the endpoints change, but we were left with the "cleanup" map entries?
> 

The entries were never cleaned up.

> If I understood correctly, then LGTM.

@joamaki replied inline.

File: daemon/cmd/fqdn.go (hunk 1 above)
Comment (aanm) [reply daemon/cmd/fqdn.go:137]: > isn't there a better way to handle fix this rather than disabling writes to the cache, thereby GC as the PR changes suggest?

I don't understand the question nor what is being proposed. Bare in mind this fix needs to be minimal to avoid regressions in backports to older branches. Feel free to propose a different fix that does not need to be backported as a follow up PR.

**Comment by aanm** [comment]
> Edit: Also, is this a regression in recent releases? I'm surprised that the issue wasn't reported until now.

@aditighag I don't believe it's a regression since this code exists since the feature was introduced.

File: pkg/fqdn/cache.go [hunk 2]
```diff
@@ -160,6 +160,12 @@ func NewDNSCacheWithLimit(minTTL int, limit int) *DNSCache {
 	return c
 }
 
+func (c *DNSCache) DisableCleanupTrack() {
```
Comment (christarazi) [inline pkg/fqdn/cache.go:163]:
```suggestion
func (c *DNSCache) DisableCleanupTracking() {
```

**Review by christarazi — APPROVED** [review]
I think the change (depending on my understanding) LGTM. One minor nit on the naming. 

Similar to Aditi's comments though, why is this particular change safe. AFAIU, we are setting the map to nil so that we never insert entries into it, effectively disabling the DNS cache for expired FQDNs altogether. Is that safe? I _think_ this is probably what @aditighag was trying to get at. 

I assume that it's safe, but would be good to document the "why" in the commit msg.

**Comment by aanm** [comment]
> I think the change (depending on my understanding) LGTM. One minor nit on the naming.
> 
> Similar to Aditi's comments though, why is this particular change safe. AFAIU, we are setting the map to nil so that we never insert entries into it, effectively disabling the DNS cache for expired FQDNs altogether. Is that safe? I _think_ this is probably what @aditighag was trying to get at.

@christarazi AFAICT we are not disabling the DNS cache for expired FQDNs, we are not tracking which entries should be cleaned up by the GC because these entries are cleaned up when the endpoints change.

> 
> I assume that it's safe, but would be good to document the "why" in the commit msg.

File: daemon/cmd/fqdn.go (hunk 1 above)
Comment (aditighag) [reply daemon/cmd/fqdn.go:137]: Why don't we run `GC` on the global cache if we are still continuing to keep the cache around similar to how it's run on the per-endpoint cache? At the very least, is there a reason why we don't block the writes to the cache at the entry point (e.g., [ReplaceFromCacheByNames](https://github.com/cilium/cilium/blob/master/pkg/fqdn/cache.go#L374))? The current fix is rendering most of this code as dead code based on my limited understanding of the code.

Comment (aanm) [reply daemon/cmd/fqdn.go:137]: > Why don't we run `GC` on the global cache if we are still continuing to keep the cache around similar to how it's run on the per-endpoint cache? 

It's not necessary because the Cache is replaced here https://github.com/cilium/cilium/blob/fcc345ec0a00ad4a385f650910f1d35e653a1a2e/daemon/cmd/fqdn.go#L220

> At the very least, is there a reason why we don't block the writes to the cache at the entry point (e.g., [ReplaceFromCacheByNames](https://github.com/cilium/cilium/blob/master/pkg/fqdn/cache.go#L374))? The current fix is rendering most of this code as dead code based on my limited understanding of the code.

I'm not following, block which writes?

Comment (aditighag) [reply daemon/cmd/fqdn.go:137]: Well, I was referring to this check added by the PR - 

```
func (c *DNSCache) addNameToCleanup(entry *cacheEntry) {
	if c.cleanup == nil {
		return
	}
```

Some of the code is shared between global and per-endpoint cache updates so teasing out the clean-up tracking related code can complicate backports. We can go with this minimal fix as you mentioned about keeping the changes minimal for backports.

**Review by aditighag — APPROVED** [review]
