### PR TITLE
gateway-api: Fix Gateway reconciler failure when TLSRoute CRD is not installed

### LINKED ISSUE #38420: Gateway reconciler fails if experimental TLSRoute CRD is not installed
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.2 and lower than v1.18.0

### What happened?

I am trying to use the Gateway API implementation in Cilium. According to the official documentation, the experimental Gateway API CRDs are not required if you are not going to use TLSRoutes: https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/#prerequisites

Image

However, if I install the standard channel CRDs and create a Gateway using the `cilium` GatewayClass, I see errors in the logs related to TLSRoutes (see logs section further below) and the Gateway keeps indefinitely waiting for the controller:

```
kubectl -n default get gateways.gateway.networking.k8s.io test-gateway
NAME           CLASS    ADDRESS   PROGRAMMED   AGE
test-gateway   cilium             Unknown      2m9s

kubectl -n default describe gateways.gateway.networking.k8s.io test-gateway
Name:         test-gateway
<snip>
Status:
  Conditions:
    Last Transition Time:  1970-01-01T00:00:00Z
    Message:               Waiting for controller
    Reason:                Pending
    Status:                Unknown
    Type:                  Accepted
    Last Transition Time:  1970-01-01T00:00:00Z
    Message:               Waiting for controller
    Reason:                Pending
    Status:                Unknown
    Type:                  Programmed
Events:                    <none>
```

After installing the experimental CRDs (including TLSRoute), the Gateway starts working as expected.

The issue seems to happen right here: https://github.com/cilium/cilium/blob/375906fd1196c0c3416d2f0ad59593be5f1a4ea3/operator/pkg/gateway-api/gateway_reconcile.go#L95-L99

It tries to retrieve TLSRoutes, which it cannot do because the CRD does not exist.

I expect that either the code needs to be modified to not try to retrieve TLSRoutes if the CRD does not exist, or the documentation needs to be changed to indicate that the experimental CRDs are required.

### How can we reproduce the issue?

1. Install the API gateway CRDs from the standard release channel, which does not include the `TLSRoute` CRD (tested with both version 1.2.0 and 1.2.1)
```shell
kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.0/standard-install.yaml
```
2. Install Cilium 1.17.2 with the Gateway API enabled according to https://docs.cilium.io/en/v1.17/network/servicemesh/gateway-api/gateway-api/#installation. For full reference, I use Helm with the following values:
```yaml
bgpControlPlane:
  enabled: true
kubeProxyReplacement: true
k8sServiceHost: k8s-prod
k8sServicePort: 6443
gatewayAPI:
  enabled: true
```
3. Create a Gateway using the `cilium` GatewayClass and some resources to use it, I used the following test NGINX deployment:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: test-gateway
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      port: 80
      protocol: HTTP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx-test-route
spec:
  parentRefs:
    - kind: Gateway
      name: test-gateway
  rules:
    - backendRefs:
        - name: nginx-test-svc
          port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-deploy
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test-svc
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      protocol: TCP
```
4. Observe errors in the logs regarding TLSRoutes (see log section further below), and see that the created Gateway does not get an address and will wait indefinitely for the controller.

To 'fix' this, install the experimental Gateway API CRDs and observe that it'll start working as expected:

```shell
kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.0/experimental-install.yaml
kubectl rollout restart -n kube-system deployment cilium-operator
```

Log output afterward:
```
time=2025-03-22T19:26:53Z level=info msg="Successfully reconciled Gateway" module=operator.operator-controlplane.leader-lifecycle.gateway-api controller=gateway resource=prod/lab-gateway
time=2025-03-22T19:26:53Z level=info msg="Reconciling Gateway" module=operator.operator-controlplane.leader-lifecycle.gateway-api controller=gateway resource=default/test-gateway
```

And the Gateway now has an address assigned and works as expected:
```shell
kubectl -n default get gateways.gateway.networking.k8s.io
NAME           CLASS    ADDRESS       PROGRAMMED   AGE
test-gateway   cilium   172.16.21.0   True         15m

kubectl -n default describe gateways.gateway.networking.k8s.io test-gateway
Name:         test-gateway
<snip>
Status:
  Addresses:
    Type:   IPAddress
    Value:  172.16.21.0
  Conditions:
    Last Transition Time:  2025-03-22T19:26:53Z
    Message:               Gateway successfully scheduled
    Observed Generation:   1
    Reason:                Accepted
    Status:                True
    Type:                  Accepted
    Last Transition Time:  2025-03-22T19:26:53Z
    Message:               Gateway successfully reconciled
    Observed Generation:   1
    Reason:                Programmed
    Status:                True
    Type:                  Programmed
```

### Cilium Version

1.17.2

### Kernel Version

6.8.0-55-generic

### Kubernetes Version

1.31.4

### Regression

Nope, not as far as I know.

### Sysdump

_No response_

### Relevant log output

```shell
time=2025-03-22T19:13:59Z level=info msg="Reconciling Gateway" module=operator.operator-controlplane.leader-lifecycle.gateway-api controller=gateway resource=default/test-gateway
time=2025-03-22T19:13:59Z level=error msg="Unable to list TLSRoutes" module=operator.operator-controlplane.leader-lifecycle.gateway-api controller=gateway resource=default/test-gateway error="no kind is registered for the type v1alpha2.TLSRouteList in scheme \"k8s.io/client-go/kubernetes/scheme/register.go:83\""
time=2025-03-22T19:13:59Z level=error msg="Reconciler error" module=operator.operator-controlplane.leader-lifecycle.controller-runtime controller=gateway controllerGroup=gateway.networking.k8s.io controllerKind=Gateway Gateway.name=test-gateway Gateway.namespace=default namespace=default name=test-gateway reconcileID=4470c0c4-2bd6-41b9-8a81-00834a2d1da0 error="no kind is registered for the type v1alpha2.TLSRouteList in scheme \"k8s.io/client-go/kubernetes/scheme/register.go:83\""
```

### Anything else?

Previous PRs related to this:
- https://github.com/cilium/cilium/pull/34212
- https://github.com/cilium/cilium/pull/34817

Comment in a different issue of someone who seemingly ran into the same thing: https://github.com/cilium/cilium/issues/38123#issuecomment-2731163560

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by syedazeez337**
## Description

This PR fixes an issue where the Gateway API reconciler fails when the experimental TLSRoute CRD is not installed. According to the documentation, the experimental Gateway API CRDs are not required if TLSRoutes are not going to be used. However, the current implementation tries to list TLSRoutes unconditionally, which fails with an error when the CRD is not installed.

The fix adds a check to determine if the TLSRoute CRD is supported in the cluster before attempting to list TLSRoutes. When the CRD is not installed, the Gateway reconciler now uses an empty TLSRouteList instead of failing with an error.

## Related issues

Fixes: #38420

## How has this been tested

I've tested this by:
1. Creating a unit test for the `HasTLSRouteSupport` helper function
2. Verifying that the Gateway reconciler works correctly when the TLSRoute CRD is not installed

## Checklist

- [x] I have read the [Documentation](https://docs.cilium.io)
- [x] I have read the [Contributing documentation](https://docs.cilium.io/en/latest/contributing/development/)
- [x] I have read the [Code of Conduct](https://docs.cilium.io/en/latest/contributing/code-of-conduct/)
- [x] I have signed the [Developer's Certificate of Origin](https://github.com/cilium/cilium/blob/main/Documentation/contributing/contributing.rst#developers-certificate-of-origin)
- [x] I have added unit tests for my changes
- [x] I have tested the changes and verified that they work and don't break existing tests

### CODE REVIEW

File: operator/pkg/gateway-api/gateway_reconcile.go [hunk 1]
```diff
@@ -125,7 +132,13 @@ func (r *gatewayReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ct
...
 
 	httpRoutes := r.filterHTTPRoutesByGateway(ctx, gw, httpRouteList.Items)
-	tlsRoutes := r.filterTLSRoutesByGateway(ctx, gw, tlsRouteList.Items)
+
+	// Only filter TLSRoutes if the CRD is installed
+	var tlsRoutes []gatewayv1alpha2.TLSRoute
+	if helpers.HasTLSRouteSupport(r.Client.Scheme()) {
+		tlsRoutes = r.filterTLSRoutesByGateway(ctx, gw, tlsRouteList.Items)
+	}
+
```
Comment (sayboras) [inline operator/pkg/gateway-api/gateway_reconcile.go]: do we need to perform the check here? If TLSRoute is not installed, the list will be empty, so filtered result will be empty as well right?

File: operator/pkg/gateway-api/gateway_reconcile.go [hunk 2]
```diff
@@ -538,7 +551,11 @@ func (r *gatewayReconciler) setListenerStatus(ctx context.Context, gw *gatewayv1
 
 		var attachedRoutes int32
 		attachedRoutes += int32(len(r.filterHTTPRoutesByListener(ctx, gw, &l, httpRoutes.Items)))
-		attachedRoutes += int32(len(r.filterTLSRoutesByListener(ctx, gw, &l, tlsRoutes.Items)))
+
+		// Only process TLSRoutes if the CRD is installed
+		if helpers.HasTLSRouteSupport(r.Client.Scheme()) {
+			attachedRoutes += int32(len(r.filterTLSRoutesByListener(ctx, gw, &l, tlsRoutes.Items)))
+		}
```
Comment (sayboras) [inline operator/pkg/gateway-api/gateway_reconcile.go]: same as above

File: operator/pkg/gateway-api/gateway_reconcile.go [hunk 3]
```diff
@@ -92,10 +92,17 @@ func (r *gatewayReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ct
 		return r.handleReconcileErrorWithStatus(ctx, err, original, gw)
 	}
 
-	tlsRouteList := &gatewayv1alpha2.TLSRouteList{}
-	if err := r.Client.List(ctx, tlsRouteList); err != nil {
-		scopedLog.ErrorContext(ctx, "Unable to list TLSRoutes", logfields.Error, err)
-		return r.handleReconcileErrorWithStatus(ctx, err, original, gw)
+	var tlsRouteList *gatewayv1alpha2.TLSRouteList
```
Comment (sayboras) [inline operator/pkg/gateway-api/gateway_reconcile.go]: what do you think about the below diff ? This is to keep the same coding style, and easier to follow.

```diff
diff --git i/operator/pkg/gateway-api/gateway_reconcile.go w/operator/pkg/gateway-api/gateway_reconcile.go
index 00acb6d13d..4ebac4e3f1 100644
--- i/operator/pkg/gateway-api/gateway_reconcile.go
+++ w/operator/pkg/gateway-api/gateway_reconcile.go
@@ -92,17 +92,12 @@ func (r *gatewayReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ct
 		return r.handleReconcileErrorWithStatus(ctx, err, original, gw)
 	}
 
-	var tlsRouteList *gatewayv1alpha2.TLSRouteList
+	tlsRouteList := &gatewayv1alpha2.TLSRouteList{}
 	if helpers.HasTLSRouteSupport(r.Client.Scheme()) {
-		tlsRouteList = &gatewayv1alpha2.TLSRouteList{}
 		if err := r.Client.List(ctx, tlsRouteList); err != nil {
 			scopedLog.ErrorContext(ctx, "Unable to list TLSRoutes", logfields.Error, err)
 			return r.handleReconcileErrorWithStatus(ctx, err, original, gw)
 		}
-	} else {
-		// TLSRoute CRD is not installed, use an empty list
-		tlsRouteList = &gatewayv1alpha2.TLSRouteList{}
-		scopedLog.Debug("TLSRoute CRD is not installed, skipping TLSRoute processing")
 	}
 
 	// TODO(tam): Only list the services / ServiceImports used by accepted Routes
@@ -132,13 +127,7 @@ func (r *gatewayReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ct
 	}
 
 	httpRoutes := r.filterHTTPRoutesByGateway(ctx, gw, httpRouteList.Items)
-
-	// Only filter TLSRoutes if the CRD is installed
-	var tlsRoutes []gatewayv1alpha2.TLSRoute
-	if helpers.HasTLSRouteSupport(r.Client.Scheme()) {
-		tlsRoutes = r.filterTLSRoutesByGateway(ctx, gw, tlsRouteList.Items)
-	}
-
+	tlsRoutes := r.filterTLSRoutesByGateway(ctx, gw, tlsRouteList.Items)
 	grpcRoutes := r.filterGRPCRoutesByGateway(ctx, gw, grpcRouteList.Items)
 
 	httpListeners, tlsPassthroughListeners := ingestion.GatewayAPI(ingestion.Input{
@@ -551,12 +540,7 @@ func (r *gatewayReconciler) setListenerStatus(ctx context.Context, gw *gatewayv1
 
 		var attachedRoutes int32
 		attachedRoutes += int32(len(r.filterHTTPRoutesByListener(ctx, gw, &l, httpRoutes.Items)))
-
-		// Only process TLSRoutes if the CRD is installed
-		if helpers.HasTLSRouteSupport(r.Client.Scheme()) {
-			attachedRoutes += int32(len(r.filterTLSRoutesByListener(ctx, gw, &l, tlsRoutes.Items)))
-		}
-
+		attachedRoutes += int32(len(r.filterTLSRoutesByListener(ctx, gw, &l, tlsRoutes.Items)))
 		found := false
 		for i := range gw.Status.Listeners {
 			if l.Name == gw.Status.Listeners[i].Name {
```

**Review by sayboras — COMMENTED** [review]
Thanks for your PR, I have couple of comments as per below.

File: operator/pkg/gateway-api/gateway_reconcile.go (hunk 3 above)
Comment (syedazeez337) [reply operator/pkg/gateway-api/gateway_reconcile.go]: Thank you @sayboras for reviewing my PR and providing valuable feedback!

I agree with your suggested implementation approach. It's cleaner and more consistent with the existing codebase style. The key points of your suggestion are:

Always initialize tlsRouteList as an empty list
Only perform the List operation if the TLSRoute CRD is supported
Remove the additional conditional checks when filtering TLSRoutes since an empty list will result in empty filtered results
This approach achieves the same goal of preventing the Gateway reconciler from failing when the TLSRoute CRD is not installed, while keeping the code simpler and more maintainable.

I'll update the PR with your suggested changes. The main benefit of this approach is that it:

Fixes the issue where the Gateway reconciler fails when the TLSRoute CRD is not installed
Maintains consistency with how other similar checks are implemented in the codebase
Reduces code complexity by removing unnecessary conditional checks
Would you like me to make any other adjustments to the implementation?

**Comment by syedazeez337** [comment]
Thank you @sayboras for your feedback! I've implemented your suggested changes to simplify the code:

1. Always initialize `tlsRouteList` as an empty list
2. Only perform the List operation if the TLSRoute CRD is supported
3. Remove conditional checks when filtering TLSRoutes since an empty list will result in empty filtered results

This approach maintains the core functionality while making the code cleaner and more consistent with the existing codebase style.

Let me know if you'd like me to make any additional changes!

**Comment by youngnick** [comment]
This LGTM but we won't be able to merge it without the "Signed-off-by:".

I use
```
git commit --amend --sign
```

To update that when I forget, personally.

**Review by sayboras — APPROVED** [review]
Thanks and LGTM :heavy_check_mark:

**Comment by liyihuang** [comment]
Just some FYI, I created a follow up [PR](https://github.com/cilium/cilium/pull/39122) to enhance this one

**Comment by pippolo84** [comment]
Marked this as eligible for backporting to v1.17, see this [message](https://github.com/cilium/cilium/pull/39214#issuecomment-2843983474) for more info.
