### PR TITLE
daemon: fix race in config handler

### LINKED ISSUE #17321: race: between `github.com/cilium/cilium/daemon/cmd.(*Daemon).startStatusCollector.func1()` and `daemon/cmd.(*getConfig).Handle()`
Observed in https://jenkins.cilium.io/view/Race%20Detection/job/cilium-master-k8s-1.16-kernel-net-next-race-detection/189/

Artifacts: 
[d0a3e240_K8sDatapathConfig_Encapsulation_Check_connectivity_with_Geneve_encapsulation.zip](https://github.com/cilium/cilium/files/7116038/d0a3e240_K8sDatapathConfig_Encapsulation_Check_connectivity_with_Geneve_encapsulation.zip)

```
2021-09-05T23:14:14.244995470Z ==================
2021-09-05T23:14:14.245001428Z WARNING: DATA RACE
2021-09-05T23:14:14.245006215Z Write at 0x0000053a7a18 by goroutine 81:
2021-09-05T23:14:14.245011643Z   github.com/cilium/cilium/pkg/lock.(*internalRWMutex).Lock()
2021-09-05T23:14:14.245016574Z       /go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:53 +0x84
2021-09-05T23:14:14.245021325Z   github.com/cilium/cilium/daemon/cmd.(*Daemon).startStatusCollector.func1()
2021-09-05T23:14:14.245025996Z       /go/src/github.com/cilium/cilium/daemon/cmd/status.go:663 +0x3e
2021-09-05T23:14:14.245030625Z   github.com/cilium/cilium/pkg/status.(*Collector).runProbe.func1()
2021-09-05T23:14:14.245035307Z       /go/src/github.com/cilium/cilium/pkg/status/status.go:172 +0x81
2021-09-05T23:14:14.245040162Z 
2021-09-05T23:14:14.245044686Z Previous read at 0x0000053a7a18 by goroutine 295:
2021-09-05T23:14:14.245049325Z   reflect.typedmemmove()
2021-09-05T23:14:14.245053857Z       /usr/local/go/src/runtime/mbarrier.go:178 +0x0
2021-09-05T23:14:14.245058505Z   reflect.packEface()
2021-09-05T23:14:14.245062988Z       /usr/local/go/src/reflect/value.go:123 +0xae
2021-09-05T23:14:14.245067591Z   reflect.valueInterface()
2021-09-05T23:14:14.245072086Z       /usr/local/go/src/reflect/value.go:1381 +0x18a
2021-09-05T23:14:14.245076700Z   reflect.Value.Interface()
2021-09-05T23:14:14.245081332Z       /usr/local/go/src/reflect/value.go:1351 +0x524
2021-09-05T23:14:14.245086013Z   github.com/cilium/cilium/daemon/cmd.(*getConfig).Handle()
2021-09-05T23:14:14.245090792Z       /go/src/github.com/cilium/cilium/daemon/cmd/config.go:165 +0x399
2021-09-05T23:14:14.245095510Z   github.com/cilium/cilium/api/v1/server/restapi/daemon.(*GetConfig).ServeHTTP()
2021-09-05T23:14:14.245100184Z       /go/src/github.com/cilium/cilium/api/v1/server/restapi/daemon/get_config.go:60 +0x237
2021-09-05T23:14:14.245104996Z   github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1()
2021-09-05T23:14:14.245109577Z       /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/operation.go:28 +0x95
2021-09-05T23:14:14.245114283Z   net/http.HandlerFunc.ServeHTTP()
2021-09-05T23:14:14.245118930Z       /usr/local/go/src/net/http/server.go:2046 +0x4d
2021-09-05T23:14:14.245123533Z   github.com/go-openapi/runtime/middleware.NewRouter.func1()
2021-09-05T23:14:14.245140984Z       /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/router.go:78 +0x35d
2021-09-05T23:14:14.245145919Z   net/http.HandlerFunc.ServeHTTP()
2021-09-05T23:14:14.245150065Z       /usr/local/go/src/net/http/server.go:2046 +0x4d
2021-09-05T23:14:14.245154200Z   github.com/go-openapi/runtime/middleware.Redoc.func1()
2021-09-05T23:14:14.245158402Z       /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/redoc.go:72 +0x2c8
2021-09-05T23:14:14.245162571Z   net/http.HandlerFunc.ServeHTTP()
2021-09-05T23:14:14.245166676Z       /usr/local/go/src/net/http/server.go:2046 +0x4d
2021-09-05T23:14:14.245172158Z   github.com/go-openapi/runtime/middleware.Spec.func1()
2021-09-05T23:14:14.245176479Z       /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/spec.go:46 +0x241
2021-09-05T23:14:14.245180659Z   net/http.HandlerFunc.ServeHTTP()
2021-09-05T23:14:14.245184610Z       /usr/local/go/src/net/http/server.go:2046 +0x4d
2021-09-05T23:14:14.245188871Z   github.com/cilium/cilium/pkg/metrics.(*APIEventTSHelper).ServeHTTP()
2021-09-05T23:14:14.245193009Z       /go/src/github.com/cilium/cilium/pkg/metrics/middleware.go:58 +0x1c4
2021-09-05T23:14:14.245197126Z   github.com/cilium/cilium/pkg/api.(*APIPanicHandler).ServeHTTP()
2021-09-05T23:14:14.245201252Z       /go/src/github.com/cilium/cilium/pkg/api/apipanic.go:42 +0xf9
2021-09-05T23:14:14.245221016Z   net/http.serverHandler.ServeHTTP()
2021-09-05T23:14:14.245225288Z       /usr/local/go/src/net/http/server.go:2878 +0x89a
2021-09-05T23:14:14.245229476Z   net/http.(*conn).serve()
2021-09-05T23:14:14.245233499Z       /usr/local/go/src/net/http/server.go:1929 +0x12e4
2021-09-05T23:14:14.245237534Z   net/http.(*Server).Serve·dwrap·82()
2021-09-05T23:14:14.245242297Z       /usr/local/go/src/net/http/server.go:3033 +0x58
2021-09-05T23:14:14.245246454Z 
2021-09-05T23:14:14.245250388Z Goroutine 81 (running) created at:
2021-09-05T23:14:14.245254472Z   github.com/cilium/cilium/pkg/status.(*Collector).runProbe()
2021-09-05T23:14:14.245258630Z       /go/src/github.com/cilium/cilium/pkg/status/status.go:171 +0x456
2021-09-05T23:14:14.245262856Z   github.com/cilium/cilium/pkg/status.(*Collector).spawnProbe.func1()
2021-09-05T23:14:14.245267007Z       /go/src/github.com/cilium/cilium/pkg/status/status.go:137 +0x10e
2021-09-05T23:14:14.245271150Z 
2021-09-05T23:14:14.245275039Z Goroutine 295 (running) created at:
2021-09-05T23:14:14.245279031Z   net/http.(*Server).Serve()
2021-09-05T23:14:14.245283123Z       /usr/local/go/src/net/http/server.go:3033 +0x847
2021-09-05T23:14:14.245287309Z   github.com/cilium/cilium/api/v1/server.(*Server).Serve.func1()
2021-09-05T23:14:14.245291345Z       /go/src/github.com/cilium/cilium/api/v1/server/server.go:199 +0xd2
2021-09-05T23:14:14.245300543Z   github.com/cilium/cilium/api/v1/server.(*Server).Serve·dwrap·2()
2021-09-05T23:14:14.245305196Z       /go/src/github.com/cilium/cilium/api/v1/server/server.go:203 +0x58
2021-09-05T23:14:14.245309967Z ==================
```

### PR DESCRIPTION
**Pull request by h3llix**
Fixes: #17321

### CODE REVIEW

File: daemon/cmd/config.go [hunk 1]
```diff
@@ -156,16 +156,18 @@ func (h *getConfig) Handle(params GetConfigParams) middleware.Responder {
...
 	d := h.daemon
 	m := make(map[string]interface{})
+	option.Config.ConfigPatchMutex.RLock()
 	e := reflect.ValueOf(option.Config).Elem()
 
 	for i := 0; i < e.NumField(); i++ {
 		if e.Field(i).Kind() != reflect.Func {
 			// Remove configurable opttions from read-only map
-			if e.Type().Field(i).Name != "Opts" {
+			if e.Type().Field(i).Name != "Opts" || e.Type().Field(i).Name != "ConfigPatchMutex" {
```
Comment (joamaki) [inline daemon/cmd/config.go]:
```suggestion
			if e.Type().Field(i).Name != "Opts" && e.Type().Field(i).Name != "ConfigPatchMutex" {
```

This should be an AND, since we want to skip both "Opts" and "ConfigPatchMutex".

**Review by joamaki — CHANGES_REQUESTED** [review]
Thanks for the contribution! One minor comment. 

How did you figure out that "ConfigPatchMutex" shouldn't be serialized? Wondering if there's other fields that should be skipped and whether there's a better way than manually skipping specific fields...

**Comment by joestringer** [comment]
> How did you figure out that "ConfigPatchMutex" shouldn't be serialized? Wondering if there's other fields that should be skipped and whether there's a better way than manually skipping specific fields...

I had prompted this, because "ConfigPatchMutex" isn't a configuration option, it's a mutex used internally inside the daemon to synchronize state. So it doesn't make sense to me that we would try to serialize a synchronization primitive onto the wire. Interesting question though, for instance when I peruse the `DaemonConfig` structure I see a couple of other fields that aren't actually agent configuration options, they're just conveniently placed directly into this structure. I'm looking at things like `DryMode` which is only used for unit tests. Maybe `CreationTime` falls under this category also. It probably makes sense for us to collect these options together in a dedicated section maybe at the start of the `DaemonConfig` structure (or even in a dedicated structure that's embedded directly into `DaemonConfig`) so that it's easier to identify these and that they should not be serialized.

File: daemon/cmd/config.go (hunk 1 above)
Comment (h3llix) [reply daemon/cmd/config.go]: I am sorry. Silly mistake I'll just correct it.

**Comment by h3llix** [comment]
@joestringer That makes sense. We could have embedded structs containing configurations which do not need to be serialized. Simply skipping the struct at the time of mapping.

**Review by joestringer — APPROVED** [review]
Fix LGTM, thanks.

**Comment by joestringer** [comment]
test-me-please

**Review by joamaki — APPROVED** [review]
LGTM now, thanks!

**Comment by joestringer** [comment]
[ci-aks failure](https://github.com/cilium/cilium/runs/3667067189?check_suite_focus=true) is likely a variation of the flake #16938.
[test-1.16-netnext failure](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/1484/testReport/junit/Suite-k8s-1/16/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_direct_routing_Tests_NodePort/) looks like https://github.com/cilium/cilium/issues/12511.
[ci-l4lb failure](https://github.com/cilium/cilium/runs/3667067489?check_suite_focus=true) appears to be #17305.

No need to block this PR on the test failures since they are unrelated to the PR.
