### PR TITLE
cilium-cli: add connectivity test for service loopback

### LINKED ISSUE #33194: kpr: stabilize Service handling for loopback connections
The handling for IPv4 Service loopback connections in the per-packet LB (client connects to itself via a service) is a tricky beast. https://github.com/cilium/cilium/pull/32480 improved the situation quite a bit, but there's still some work to do:

* [x] add connectivity tests to catch regressions
* [x] add support for IPv6 loopback (https://github.com/cilium/cilium/issues/26733)
    - Ongoing PR at https://github.com/cilium/cilium/pull/39594.
* [ ] document the special handling (for instance: emphasize that no network policy is needed)

### PR DESCRIPTION
**Pull request by saiaunghlyanhtet**
Connectivity tests to catch regressions after service loopback support for IPv6 is [available](https://github.com/cilium/cilium/pull/39594).

```release-note
Connectivity tests for service loopback to catch regressions
```

Fixes: #33194

### CODE REVIEW

File: cilium-cli/connectivity/tests/service.go [hunk 1]
```diff
@@ -406,3 +406,43 @@ func (s *podToL7Service) Run(ctx context.Context, t *check.Test) {
...
+
+			t.ForEachIPFamily(func(ipFamily features.IPFamily) {
+				t.NewAction(s, fmt.Sprintf("curl-l7lb-%s-%d", ipFamily, i), &pod, svc, ipFamily).Run(func(a *check.Action) {
+					a.ExecInPod(ctx, a.CurlCommand(svc))
+					a.ValidateFlows(ctx, pod, a.GetEgressRequirements(check.FlowParameters{
+						DNSRequired: true,
+						AltDstPort:  svc.Port(),
+					}))
+					a.ValidateMetrics(ctx, pod, a.GetEgressMetricsRequirements())
+				})
```
Comment (julianwiedmann) [inline cilium-cli/connectivity/tests/service.go:446]: Note that the connectivity tests will run on all supported Cilium releases, and so we'd need to skip the IPv6 test for versions that don't have your patches.

Similar as in https://github.com/cilium/cilium/pull/42148.

File: cilium-cli/connectivity/tests/service.go [hunk 2]
```diff
@@ -406,3 +406,43 @@ func (s *podToL7Service) Run(ctx context.Context, t *check.Test) {
...
+
+func (s *podToItselfViaService) Run(ctx context.Context, t *check.Test) {
+	var i int
+	ct := t.Context()
+
+	for _, pod := range ct.L7LBClientPods() {
+		for _, svc := range ct.L7LBService() {
+
+			t.ForEachIPFamily(func(ipFamily features.IPFamily) {
+				t.NewAction(s, fmt.Sprintf("curl-l7lb-%s-%d", ipFamily, i), &pod, svc, ipFamily).Run(func(a *check.Action) {
```
Comment (julianwiedmann) [inline cilium-cli/connectivity/tests/service.go]: You'll want to adjust the `curl-l7lb-` naming here :)

File: cilium-cli/connectivity/builder/service_loopback.go [hunk 3]
```diff
@@ -0,0 +1,21 @@
...
+	"github.com/cilium/cilium/cilium-cli/connectivity/check"
+	"github.com/cilium/cilium/cilium-cli/connectivity/tests"
+	"github.com/cilium/cilium/cilium-cli/utils/features"
+)
+
+type serviceLoopback struct{}
+
+func (t serviceLoopback) build(ct *check.ConnectivityTest, _ map[string]string) {
+	newTest("pod-to-itself-via-service", ct).
+		WithFeatureRequirements(features.RequireEnabled(features.L7LoadBalancer)).
```
Comment (julianwiedmann) [inline cilium-cli/connectivity/builder/service_loopback.go]: I think we'd need to refactor the `L7LBClientPods` workload a bit, so that we don't have to depend on `features.L7LoadBalancer` for running the tests. And can increase the test coverage.

**Review by julianwiedmann — COMMENTED** [review]
Thank you! Some initial thoughts below.

File: cilium-cli/connectivity/tests/service.go (hunk 1 above)
Comment (saiaunghlyanhtet) [reply cilium-cli/connectivity/tests/service.go:446]: Added version check for 1.19.0. I think 1.19.0 would be the first one to include my patch.

File: cilium-cli/connectivity/tests/service.go (hunk 2 above)
Comment (saiaunghlyanhtet) [reply cilium-cli/connectivity/tests/service.go]: Set to match with others.

File: cilium-cli/connectivity/builder/service_loopback.go (hunk 3 above)
Comment (saiaunghlyanhtet) [reply cilium-cli/connectivity/builder/service_loopback.go]: Refactored L7LB pods and services to be deployed unconditionally during connectivity test setup.

**Comment by saiaunghlyanhtet** [comment]
Re-basing. Any update on this?

**Comment by julianwiedmann** [comment]
> Re-basing. Any update on this?

it's on my plate, just backlogged - sorry. Probably won't get to it before the holiday break.

File: cilium-cli/connectivity/tests/service.go [hunk 4]
```diff
@@ -406,3 +406,53 @@ func (s *podToL7Service) Run(ctx context.Context, t *check.Test) {
...
+				})
+			} else {
+				t.NewAction(s, fmt.Sprintf("curl-%d", i), &pod, svc, features.IPFamilyAny).Run(func(a *check.Action) {
+					a.ExecInPod(ctx, a.CurlCommand(svc))
+					a.ValidateFlows(ctx, pod, a.GetEgressRequirements(check.FlowParameters{
+						DNSRequired: true,
+						AltDstPort:  svc.Port(),
+					}))
+					a.ValidateMetrics(ctx, pod, a.GetEgressMetricsRequirements())
+				})
```
Comment (julianwiedmann) [inline cilium-cli/connectivity/tests/service.go]: I think you want something along the lines of

```
ForEachFamily() {
   if (IPv6 && version < 1.19.0)
     continue

   t.NewAction(s, fmt.Sprintf("curl-%s-%d", ipFamily, i), &pod, svc, ipFamily).Run(func(a *check.Action)
   ...
}
```

No need for falling back to `features.IPFamilyAny`.

File: cilium-cli/connectivity/tests/service.go [hunk 5]
```diff
@@ -406,3 +406,53 @@ func (s *podToL7Service) Run(ctx context.Context, t *check.Test) {
...
+func (s *podToItselfViaService) Name() string {
+	return "pod-to-itself-via-service"
+}
+
+func (s *podToItselfViaService) Run(ctx context.Context, t *check.Test) {
+	var i int
+	ct := t.Context()
+
+	for _, pod := range ct.L7LBClientPods() {
+		for _, svc := range ct.L7LBService() {
```
Comment (julianwiedmann) [inline cilium-cli/connectivity/tests/service.go]: I'm struggling a bit here - my expectation would be that we re-use the existing hairpin test pieces as much as possible, but build a non-L7 service from them.

If we access the L7-annotated services here, then we test hairpinning via Envoy (and not actually testing the new BPF code). No?

Comment (saiaunghlyanhtet) [reply cilium-cli/connectivity/tests/service.go]: What about re-using echo services here?

Comment (saiaunghlyanhtet) [reply cilium-cli/connectivity/tests/service.go]: Sorry. I think echo services won't work. I will create a new non-L7 service for L7LBClientPods and use it.

Comment (julianwiedmann) [reply cilium-cli/connectivity/tests/service.go]: If we can tweak them to reliably produce a pod-to-itself-via-service scenario, sure!

**Comment by pchaigno** [comment]
@ysksuzuki @viktor-kurchenko We're waiting for your reviews here :pleading_face:

**Review by viktor-kurchenko — APPROVED** [review]
LGTM, thanks!

File: cilium-cli/connectivity/builder/service_loopback.go
Comment (tklauser) [inline cilium-cli/connectivity/builder/service_loopback.go:1]: Could you please add an entry to `CODEOWNERS` for this file, assigning it to @cilium/sig-lb? Thanks.

Comment (saiaunghlyanhtet) [reply cilium-cli/connectivity/builder/service_loopback.go:1]: Added to `CODEOWNERS`.

**Review by tklauser — APPROVED** [review]
Thanks!

**Review by bimmlerd — APPROVED** [review]
CODEOWNERS lgtm

**Comment by tklauser** [comment]
@cilium/sig-lb @ysksuzuki could you please take a look?

**Review by ysksuzuki — APPROVED** [review]
LGTM
