### PR TITLE
datapath: Retry netlink.LinkList when interrupted

### LINKED ISSUE #35055: Agent Unable to write node config header: interrupted system call
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

Agent fails to regenerate endpoints due to failing to write node config header, which leads to all bpf compilations to fail.

### How can we reproduce the issue?

Happens randomly, not easy to reproduce.

### Cilium Version

Cilium 1.17.0-dev 8fa83406 2024-08-22T14:10:51+02:00 go version go1.23.1 linux/amd64

### Kernel Version

Linux/x86 6.10.0-rc6

### Kubernetes Version

N/A

### Regression

_No response_

### Sysdump

[RuntimeAgentFQDNPolicies_With_verbose_policy_logs_Validates_DNSSEC_responses.zip](https://github.com/user-attachments/files/17150290/RuntimeAgentFQDNPolicies_With_verbose_policy_logs_Validates_DNSSEC_responses.zip)

### Relevant log output

```shell
time="2024-09-26T13:15:45.933969654Z" level=error msg="Unable to write node config header" error="failed to write node configuration file at /var/run/cilium/state/globals/node_config.h: rendering vlan filter macros: listing network interfaces: interrupted system call" subsys=datapath-loader
...
time="2024-09-26T13:15:46.100906287Z" level=error msg="Failed to compile bpf_lxc.o: exit status 1" compiler-pid=793 subsys=datapath-loader
time="2024-09-26T13:15:46.100944558Z" level=warning msg="In file included from /var/lib/cilium/bpf/bpf_lxc.c:18:" subsys=datapath-loader
time="2024-09-26T13:15:46.100961449Z" level=warning msg="In file included from /var/lib/cilium/bpf/lib/auth.h:6:" subsys=datapath-loader
time="2024-09-26T13:15:46.100969916Z" level=warning msg="In file included from /var/lib/cilium/bpf/lib/common.h:1279:" subsys=datapath-loader
time="2024-09-26T13:15:46.100978361Z" level=warning msg="In file included from /var/lib/cilium/bpf/lib/overloadable.h:10:" subsys=datapath-loader
time="2024-09-26T13:15:46.100987608Z" level=warning msg="In file included from /var/lib/cilium/bpf/lib/overloadable_skb.h:8:" subsys=datapath-loader
time="2024-09-26T13:15:46.100997066Z" level=warning msg="/var/lib/cilium/bpf/lib/clustermesh.h:18:23: error: use of undeclared identifier '__config_identity_length'" subsys=datapath-loader
time="2024-09-26T13:15:46.101011563Z" level=warning msg="   18 |         __u32 identity_len = CONFIG(identity_length);" subsys=datapath-loader
time="2024-09-26T13:15:46.101018676Z" level=warning msg="      |                              ^" subsys=datapath-loader
time="2024-09-26T13:15:46.101138079Z" level=warning msg="/var/lib/cilium/bpf/lib/static_data.h:75:10: note: expanded from macro 'CONFIG'" subsys=datapath-loader
```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jrajahalme**
Retry netlink.LinkList call if it returns EINTR error, due to an upstream netlink library change to fail if `NLM_F_DUMP_INTR ` flag is set in the netlink response (https://github.com/vishvananda/netlink/pull/925).

After we get our netlink dependency updated to include https://github.com/vishvananda/netlink/pull/1018, we can change this retry condition to look for `netlink.ErrDumpInterrupted` instead.

This fixes this failure mode seen frequently in the CI recently:

time="2024-09-26T13:15:45.933969654Z" level=error msg="Unable to write node config header" error="failed to write node configuration file at /var/run/cilium/state/globals/node_config.h: rendering vlan filter macros: listing network interfaces: interrupted system call" subsys=datapath-loader ...
time="2024-09-26T13:15:46.100906287Z" level=error msg="Failed to compile bpf_lxc.o: exit status 1" compiler-pid=793 subsys=datapath-loader time="2024-09-26T13:15:46.100944558Z" level=warning msg="In file included from /var/lib/cilium/bpf/bpf_lxc.c:18:" subsys=datapath-loader time="2024-09-26T13:15:46.100961449Z" level=warning msg="In file included from /var/lib/cilium/bpf/lib/auth.h:6:" subsys=datapath-loader time="2024-09-26T13:15:46.100969916Z" level=warning msg="In file included from /var/lib/cilium/bpf/lib/common.h:1279:" subsys=datapath-loader time="2024-09-26T13:15:46.100978361Z" level=warning msg="In file included from /var/lib/cilium/bpf/lib/overloadable.h:10:" subsys=datapath-loader time="2024-09-26T13:15:46.100987608Z" level=warning msg="In file included from /var/lib/cilium/bpf/lib/overloadable_skb.h:8:" subsys=datapath-loader time="2024-09-26T13:15:46.100997066Z" level=warning msg="/var/lib/cilium/bpf/lib/clustermesh.h:18:23: error: use of undeclared identifier '__config_identity_length'" subsys=datapath-loader
time="2024-09-26T13:15:46.101011563Z" level=warning msg="   18 |         __u32 identity_len = CONFIG(identity_length);" subsys=datapath-loader
time="2024-09-26T13:15:46.101018676Z" level=warning msg="      |                              ^" subsys=datapath-loader
time="2024-09-26T13:15:46.101138079Z" level=warning msg="/var/lib/cilium/bpf/lib/static_data.h:75:10: note: expanded from macro 'CONFIG'" subsys=datapath-loader

Fixes: #35055

```release-note
Cilium no longer fails compiling bpf programs if listing network links is interrupted.
```

### CODE REVIEW

File: pkg/datapath/linux/config/config.go [hunk 1]
```diff
@@ -839,6 +840,17 @@ func getEphemeralPortRangeMin(sysctl sysctl.Sysctl) (int, error) {
 	return ephemeralPortMin, nil
 }
 
+// ignoringEINTR makes a function call and repeats it if it returns an
+// EINTR error.
+func ignoringEINTR(fn func() error) error {
+	for {
```
Comment (rgo3) [inline pkg/datapath/linux/config/config.go:846]: Is there any risk in retrying indefinitely? I think we also have the `resiliency` pkg that already offers some sort of retry functions, but not sure if these APIs ever gained any traction in the codebase...
Also pinging @ti-mo, IIRC he was involved in some offline discussions around improving the handling of EINTR, especially in the context of netlink. Does this go in the right direction or do you have something else in mind?

Comment (jrajahalme) [reply pkg/datapath/linux/config/config.go:846]: IFAIK it is customary to retry indefinitely when getting EINTR, see e.g.: https://github.com/golang/go/blob/master/src/os/file_posix.go#L242-L256

Comment (ti-mo) [reply pkg/datapath/linux/config/config.go:846]: > Also pinging @ti-mo, IIRC he was involved in some offline discussions around improving the handling of EINTR, especially in the context of netlink. Does this go in the right direction or do you have something else in mind?

Any netlink library call can return EINTR, this needs to be fixed in the lib itself.

Comment (jrajahalme) [reply pkg/datapath/linux/config/config.go:846]: @ti-mo wrote:

> Any netlink library call can return EINTR, this needs to be fixed in the lib itself.

Looks like this is not _actually_ an `EINTR` from a system call, but a mapped one from `NLM_F_DUMP_INTR` netlink flag, set by the kernel when the resource being dumped changes during the dump. This mapping is a recent change in the netlink library, there seems to be an upstream fix for this: https://github.com/vishvananda/netlink/pull/1018. Using this involves retrying the the dump in this specific error condition, IMO.

We can address this error condition by the change in this PR, or by looking for the new (in [#1018](https://github.com/vishvananda/netlink/pull/1018)) error `netlink.ErrDumpInterrupted` instead of `EINTR` after we have updated the lib.

**Comment by jrajahalme** [comment]
Maybe listing network interfaces is kind of susceptible for `NLM_F_DUMP_INTR` given that busy nodes have new veths coming and going very frequently?

File: pkg/datapath/linux/config/config.go (hunk 1 above)
Comment (jrajahalme) [reply pkg/datapath/linux/config/config.go:846]: Updated the title and description in light of the above information.

**Comment by jrajahalme** [comment]
@ti-mo Could you consider accepting this or proposing another fix soonish? I keep hitting this in my PRs pretty consistently (e.g. https://github.com/cilium/cilium/actions/runs/11418520360/attempts/2)

**Review by ti-mo — APPROVED** [review]
