### PR TITLE
pkg/k8s: add support for multi-stack

### LINKED ISSUE #9214: For k8s dual-stack POD ipv6 addresses are not assigned from the configured CIDR
## Bug report

I file this as a bug, but it is a bit unfair since k8s dual-stack is not release yet.

When using `cilium` in k8s dual-stack the ipv6 addresses for PODs seems to be taken from `f00d::b00:0:0:0/80` (`f00d::11.0.0.0:0:0:0/80`). While this works, that is not the configured range.

In k8s dual-stack the `kube-controller-manager` is configured with a 2-item array, for example;
```
--cluster-cidr=11.0.0.0/16,1100::/16
```
In the first release both ipv4 and ipv6 must have the same maskbits /16 in this case. This is a temporary constraint and will be fixed later.

K8s will assign ranges to each node, but the new in dual-stack is the `podCIDRs` attribute in the k8s node objects;
```
    "spec": {
        "podCIDR": "11.0.3.0/24",
        "podCIDRs": [
            "11.0.3.0/24",
            "1100:300::/24"
        ]
    },
```
The POD ipv6 addresses shall be taken from "1100:300::/24" in this case.

**General Information**

- Cilium version (run `cilium version`)
  v1.6.1
- Kernel version (run `uname -a`)
  `Linux vm-005 5.1.7 #11 SMP Tue Sep 17 10:09:10 CEST 2019 x86_64 GNU/Linux`
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
  K8s; `v1.16.0-rc.1`
- Link to relevant artifacts (policies, deployments scripts, ...)
- Upload a system dump (run `curl -sLO

**How to reproduce the issue**

1. Use K8s v1.16.0-rc.1 which includes the dual-stack support
2. Use `--feature-gates IPv6DualStack=true` to k8s binaries and configure ranges where appropriate
3. Install cilium with `quick-install.yaml` but with `enable-ipv6: "true"`
4. Check the assigned podIPs

### PR DESCRIPTION
**Pull request by aanm**
Kubernetes has introduced support for multi-stack environments. This
commit adds the missing integration with k8s for multi-stack.

Signed-off-by: André Martins <andre@cilium.io>

Fixes: https://github.com/cilium/cilium/issues/9214

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9215)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by vadorovsky — APPROVED** [review]

File: pkg/k8s/factory_functions.go [hunk 1]
```diff
@@ -471,6 +471,7 @@ func ConvertToNode(obj interface{}) interface{} {
 			ObjectMeta:      concreteObj.ObjectMeta,
 			StatusAddresses: concreteObj.Status.Addresses,
 			SpecPodCIDR:     concreteObj.Spec.PodCIDR,
+			SpecPodCIDRs:    concreteObj.Spec.PodCIDRs,
```
Comment (ianvernon) [inline pkg/k8s/factory_functions.go:474]: How will this work in the cases of where `IPv4Range` and `IPv6Range` are set in the configuration for Cilium? Should some type of precedence be established?

Comment (aanm) [reply pkg/k8s/factory_functions.go:474]: Same as it works today where `IPv4Range` is set in the the configuration for Cilium?

Comment (ianvernon) [reply pkg/k8s/factory_functions.go:474]: I must be missing something then :/ so there is no overlap between the aforementioned `IPv*Range` variables and the PodCIDRs which are provided here? These CIDRs are for node events, yes, but it looks like we also provide a way to configure the pod CIDRs via our CLI. What do those variables do then vs. the PodCIDRs being allocated by K8s for a given node?

Comment (aanm) [reply pkg/k8s/factory_functions.go:474]: The CLI flags overwrite the pod CIDRs from k8s node spec.

**Review by ianvernon — APPROVED** [review]
