### PR TITLE
clustermesh: fix missing remote backends when multiple service ports share the same target port

### LINKED ISSUE #45109: Cilium Cluster Mesh: Missing global service backends when service port points to the same target port
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.14 and lower than v1.18.0

### What happened?

After upgrading Cilium from version 1.17.3 to version 1.181, our frontier cluster was no longer able to connect to some remote cluster services.
Specifically, we noticed that for services that expose different ports but reference the same container target port, Cilium's endpoint propagation behavior was anomalous because not all remote service endpoints and their ports were propagated to the other clusters.

We planned a gradual migration of the clusters that make up the mesh, so you'll find different Cilium versions in the descriptions for this reason.

The frontier cluster uses the Nutanix Kubernetes Platform and the remote GKE cluster, but the same problem applies to other use cases where GKE becomes a frontier cluster.

### How can we reproduce the issue?

Below is an example created with nginx and deployed on the remote cluster.

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: cilium-port-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-port-test
  namespace: cilium-port-test
  labels:
    app: nginx-port-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-port-test
  template:
    metadata:
      labels:
        app: nginx-port-test
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-port-test
  namespace: cilium-port-test
  annotations:
    service.cilium.io/global: "true"
    service.cilium.io/affinity: "remote"
spec:
  type: ClusterIP
  selector:
    app: nginx-port-test
  ports:
    
    - name: http-direct
      port: 80
      targetPort: http
      protocol: TCP
    - name: http-remapped
      port: 8080
      targetPort: http
      protocol: TCP
    - name: http-alt
      port: 9090
      targetPort: http
      protocol: TCP
```

Here, however, is the same service deployed in the same namespace in the frontier cluster:
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: cilium-port-test
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-port-test
  namespace: cilium-port-test
  annotations:
    service.cilium.io/global: "true"
    service.cilium.io/affinity: "remote"
spec:
  type: ClusterIP
  selector:
    app: nginx-port-test
  ports:
    - name: http-direct
      port: 80
      targetPort: http
      protocol: TCP
    - name: http-remapped
      port: 8080
      targetPort: http
      protocol: TCP
    - name: http-alt
      port: 9090
      targetPort: http
      protocol: TCP
```

If we look at the ebpf maps in the frontier cluster, we see this behavior:

```bash
 k exec -n kube-system -it ds/cilium -c cilium-agent  -- cilium bpf lb list | grep 10.124.99.158
10.124.99.158:80/TCP (0)       0.0.0.0:0 (93) (0) [ClusterIP, non-routable]                     
10.124.99.158:8080/TCP (0)     0.0.0.0:0 (94) (0) [ClusterIP, non-routable]                     
10.124.99.158:9090/TCP (0)     0.0.0.0:0 (95) (0) [ClusterIP, non-routable]                     
10.124.99.158:8080/TCP (1)     10.125.86.133:80/TCP (94) (1)    
```

In the remote backend cluster, the ebpf maps look like this (the service responds on all ports):

```bash
 k exec -n kube-system -it ds/cilium -c cilium-agent  -- cilium bpf lb list | grep 10.117.75.185             
10.117.75.185:9090/TCP (0)     0.0.0.0:0 (65) (0) [ClusterIP, non-routable]                     
10.117.75.185:80/TCP (1)       10.125.86.133:80/TCP (63) (1)                                    
10.117.75.185:9090/TCP (1)     10.125.86.133:80/TCP (65) (1)                                    
10.117.75.185:8080/TCP (0)     0.0.0.0:0 (64) (0) [ClusterIP, non-routable]                     
10.117.75.185:80/TCP (0)       0.0.0.0:0 (63) (0) [ClusterIP, non-routable]                     
10.117.75.185:8080/TCP (1)     10.125.86.133:80/TCP (64) (1)  
```

### Cilium Version

Frontier Cluster: v1.18.1
Remote Cluster: v1.17.3

### Kernel Version

.

### Kubernetes Version

Frontier Cluster: v1.34.3
Remote Cluster: v1.33.5 

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by RiccardoAtzori91**
Using Cluster Mesh, when a Kubernetes Service exposes multiple ports that resolve to the same container target port (e.g., service ports 80, 8080, and 9090 all mapping to target port 80), the `ClusterServiceToBackendParams` function previously created separate `loadbalancer.Backend` instances for each port name. However, since these backends share the same `L3n4Addr`, and `updateBackends` uses `BackendKey{ServiceName, Address, SourcePriority}` as a unique key, subsequent insertions overwrote earlier ones. As a result, only the last port name was retained, and the remaining service ports lost their remote backends in the eBPF maps.
This patch modifies `ClusterServiceToBackendParams` to group port configurations by protocol and port number during iteration, ensuring that a single `Backend` is emitted per unique L4 address with all associated port names correctly aggregated. Unit tests covering the affected scenarios have been added.

Fixes: #45109

```release-note
Fix missing global service backends in Cluster Mesh when multiple service ports point to the same target port.
```

### CODE REVIEW

File: pkg/clustermesh/service_merger.go [hunk 1]
```diff
@@ -98,26 +98,41 @@ func ClusterServiceToBackendParams(service *serviceStore.ClusterService) (beps [
...
 
+		// Group port names by L4 address (protocol + port) so that multiple
+		// service ports mapping to the same target port result in a single
+		// backend with all associated port names, rather than separate backends
+		// that overwrite each other due to sharing the same BackendKey.
+		type l4Key struct {
+			Protocol loadbalancer.L4Type
+			Port     uint16
+		}
+		grouped := make(map[l4Key]*loadbalancer.Backend)
```
Comment (MrFreezeex) [inline pkg/clustermesh/service_merger.go]: You don't actually need to introduce a new type here and as you could use `serviceStore.PortConfiguration`/the `l4` variable in the loop below

File: pkg/clustermesh/service_merger.go [hunk 2]
```diff
@@ -98,26 +98,41 @@ func ClusterServiceToBackendParams(service *serviceStore.ClusterService) (beps [
...
 		for name, l4 := range portConfig {
-			portNames := []string(nil)
-			if name != "" {
-				portNames = []string{name}
+			key := l4Key{Protocol: l4.Protocol, Port: l4.Port}
+			bep, exists := grouped[key]
+			if !exists {
+				bep = &loadbalancer.Backend{
```
Comment (MrFreezeex) [inline pkg/clustermesh/service_merger.go]: I know I have originally suggested that but I gave another thought and doing this will introduce a lot of small memory allocation within those loops which could hinder performance (specifically the map allocation but also this line that I am commenting here (`bep = &loadbalancer.Backend{`).

What I would propose instead is to reuse a slice instead (and reset it's len on each loop) with essentially the following pattern:

```go
var currentBeps []loadbalancer.Backend

for ipString, portConfig := range service.Backends {

  // ...

  currentBeps = currentBeps[:0]
  for name, l4 := range portConfig {
    // use slices.IndexFunc to update an existing bep (by finding one with the same port/protocol) or append a new one in currentBeps
  }
  
  // append currentBeps to beps
}

// ...
```

This looks a good compromise between not making the implementation too complex and having good performance IMO

File: pkg/clustermesh/service_merger.go [hunk 3]
```diff
@@ -98,26 +98,41 @@ func ClusterServiceToBackendParams(service *serviceStore.ClusterService) (beps [
...
-				State:     loadbalancer.BackendStateActive,
-				Zone:      backendZone,
+			if name != "" {
+				bep.PortNames = append(bep.PortNames, name)
 			}
-			beps = append(beps, bep)
+		}
+
+		for _, bep := range grouped {
+			beps = append(beps, *bep)
```
Comment (MrFreezeex) [inline pkg/clustermesh/service_merger.go]: I think we might need to sort the port names before appending since ordering in maps are not always consistent so we could (unfortunately) have ports in different ordering if we don't do anything here :(

**Review by MrFreezeex — COMMENTED** [review]
Thanks for the PR! I left a few suggestion inline to improve the implementation

File: pkg/clustermesh/service_merger.go (hunk 2 above)
Comment (RiccardoAtzori91) [reply pkg/clustermesh/service_merger.go]: I agree, elegant solution

**Comment by RiccardoAtzori91** [comment]
Updated code implementing suggestions.

File: pkg/clustermesh/service_merger.go [hunk 4]
```diff
@@ -91,34 +92,50 @@ func (sm *serviceMerger) MergeExternalServiceUpdate(service *serviceStore.Cluste
...
 		addrCluster := cmtypes.MustParseAddrCluster(ipString)
 		var backendZone *loadbalancer.BackendZone
 		if zone, ok := service.Zones[ipString]; ok {
 			backendZone = ptr.To(zone.ToLBBackendZone())
 		}
 
+		// Group port names by L4 address (protocol + port) so that multiple
+		// service ports mapping to the same target port result in a single
+		// backend with all associated port names, rather than separate backends
+		// that overwrite each other due to sharing the same BackendKey.
```
Comment (MrFreezeex) [inline pkg/clustermesh/service_merger.go]: nit: I would write the comment below rather to something like this:
```suggestion
		// Cilium loadbalancer needs to encode a Service with multiple port names
		// for the same target port with a single loadbalancer.Backend with multiple
		// port names. The clustermesh service data on the other end contains all the
		// ports as distinct entries so we need to de-duplicate those,
```

The existing comments focus on explaining the current change but when we will be reading back that code it would not be while having this PR in mind so it sounds slightly better to not do comparison here. Feel free to modify the comment I am suggesting or take it as is!

Also I think it would be slightly better to move it right before the `slices.IndexFunc` call

File: pkg/clustermesh/service_merger_test.go [hunk 5]
```diff
@@ -0,0 +1,240 @@
+// SPDX-License-Identifier: Apache-2.0
```
Comment (MrFreezeex) [inline pkg/clustermesh/service_merger_test.go]: We already have an end to end test in `pkg/clustermesh/testdata/clusterservice.txtar` you could probably simply add another clusterservice within that file with different port names for the same target port and you should be able to test the new behavior

**Review by MrFreezeex — COMMENTED** [review]
Thanks I left a few comments inline! Otherwise it sounds pretty good to me.

@joamaki could you review this as well to confirm that's the correct behavior 🙏? I am a bit unsure about if the empty port names is correctly handled here for instance as I am wondering how the loadbalancer knows which backend have an empty port name if we need to dedup port like that 🤔.

**Comment by joamaki** [comment]
> Thanks I left a few comments inline! Otherwise it sounds pretty good to me.
> 
> @joamaki could you review this as well to confirm that's the correct behavior 🙏? I am a bit unsure about if the empty port names is correctly handled here for instance as I am wondering how the loadbalancer knows which backend have an empty port name if we need to dedup port like that 🤔.

https://github.com/cilium/cilium/blob/eaca42ce6dad0eea74169e6d2bae33477af61389/pkg/loadbalancer/writer/writer.go#L440

If the frontend mentions a port name and the backend has port names but none match then it'll skip. The backend port names are not consulted if the frontend doesn't mention one, so I think this is fine. While we're looking into this issue I would strongly recommend also extending `clusterservice.txtar` (or maybe creating another test script) to validate the different combinations. From the test script it's a bit easier to see what the expected behaviour is and it's more likely to survive refactorings vs unit tests. 

The change otherwise makes sense to me.

File: pkg/clustermesh/service_merger.go [hunk 6]
```diff
@@ -91,34 +92,50 @@ func (sm *serviceMerger) MergeExternalServiceUpdate(service *serviceStore.Cluste
 }
 
 func ClusterServiceToBackendParams(service *serviceStore.ClusterService) (beps []loadbalancer.Backend) {
+	var currentBeps []loadbalancer.Backend
```
Comment (joamaki) [inline pkg/clustermesh/service_merger.go]: Instead of maintaining a separate slice we could just hold onto the index into `beps` and then do `currentBeps := beps[currentIdx:]`. The rest of the code would be the same, but appending into `beps` instead.

**Review by joamaki — CHANGES_REQUESTED** [review]

File: pkg/clustermesh/service_merger_test.go (hunk 5 above)
Comment (RiccardoAtzori91) [reply pkg/clustermesh/service_merger_test.go]: @MrFreezeex could I add an E2E test case like this?

```txtar

-- clusterservice-multiport.json --
{
  "name": "echo",
  "namespace": "test",
  "includeExternal": true,
  "shared": true,
  "cluster": "cluster2",
  "clusterID": 2,
  "backends": {
    "20.0.0.2": {
      "tcp": {
        "Protocol": "TCP",
        "Port": 9090
      },
      "tcp-alt": {
        "Protocol": "TCP",
        "Port": 9090
      }
    }
  }
}

-- backends-multiport.table --
Address              PortNames     NodeName
10.1.0.1:8080/TCP    tcp           nodeport-worker
20.0.0.2:9090/TCP    tcp,tcp-alt

-- clusterservice-multiport-3.json --
{
  "name": "echo",
  "namespace": "test",
  "includeExternal": true,
  "shared": true,
  "cluster": "cluster2",
  "clusterID": 2,
  "backends": {
    "20.0.0.2": {
      "http": {
        "Protocol": "TCP",
        "Port": 80
      },
      "http-alt": {
        "Protocol": "TCP",
        "Port": 80
      },
      "http-remapped": {
        "Protocol": "TCP",
        "Port": 80
      }
    }
  }
}

-- backends-multiport-3.table --
Address              PortNames                  NodeName
10.1.0.1:8080/TCP    tcp                        nodeport-worker
20.0.0.2:80/TCP      http,http-alt,http-remapped
```

File: pkg/clustermesh/service_merger.go (hunk 6 above)
Comment (RiccardoAtzori91) [reply pkg/clustermesh/service_merger.go]: Yep, if adding the test case as written in the comment above is ok, I push the change to the slices and the E2E test case.

File: pkg/clustermesh/service_merger_test.go (hunk 5 above)
Comment (MrFreezeex) [reply pkg/clustermesh/service_merger_test.go]: Yeah that seems fine, actually I just saw that we have a test called `clusterservice-without-local-eps.txtar` so you could probably copy this one and simplify it to not have those _v2 service and the logic to test the delete/update parts and just test the ports name logic

Comment (RiccardoAtzori91) [reply pkg/clustermesh/service_merger_test.go]: Added clusterservice-multiport.txtar for E2E testing:

```txtar
#! --cluster-id=1 --cluster-name=cluster1

hive/start

# Create a service without selector (no epslices) with multiple ports
# sharing the same target port, to verify that remote backends are
# correctly grouped into a single backend with all port names.
k8s/add service.yaml

# Add a remote cluster service where multiple port names map to the
# same target port (http-direct, http-remapped, http-alt all on 80/TCP).
# The backends should be grouped into a single entry with all port names.
kvstore/update cilium/state/services/v1/cluster2/test/echo clusterservice2.json
db/cmp backends backends.table
db/cmp frontends frontends-with-clusterservice.table

# Removing the cluster service removes the backends
kvstore/delete cilium/state/services/v1/cluster2/test/echo
db/empty backends

###

-- backends.table --
Address              PortNames                            NodeName
20.0.0.2:80/TCP      http-alt,http-direct,http-remapped

-- frontends-with-clusterservice.table --
Address            Type       ServiceName   Status  Backends
10.0.0.1:80/TCP    ClusterIP  test/echo     Done    20.0.0.2:80/TCP
10.0.0.1:8080/TCP  ClusterIP  test/echo     Done    20.0.0.2:80/TCP
10.0.0.1:9090/TCP  ClusterIP  test/echo     Done    20.0.0.2:80/TCP

-- clusterservice2.json --
{
  "name": "echo",
  "namespace": "test",
  "includeExternal": true,
  "shared": true,
  "cluster": "cluster2",
  "clusterID": 2,
  "backends": {
    "20.0.0.2": {
      "http-direct": {
        "Protocol": "TCP",
        "Port": 80
      },
      "http-remapped": {
        "Protocol": "TCP",
        "Port": 80
      },
      "http-alt": {
        "Protocol": "TCP",
        "Port": 80
      }
    }
  }
}

-- service.yaml --
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.cilium.io/global: "true"
  name: echo
  namespace: test
spec:
  clusterIP: 10.0.0.1
  clusterIPs:
  - 10.0.0.1
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
  - name: http-direct
    port: 80
    protocol: TCP
    targetPort: 80
  - name: http-remapped
    port: 8080
    protocol: TCP
    targetPort: 80
  - name: http-alt
    port: 9090
    protocol: TCP
    targetPort: 80
  type: ClusterIP
```

Comment (MrFreezeex) [reply pkg/clustermesh/service_merger_test.go]: The unit test can be remove now, if there's anything else that you want to test you can add it to the hive script tests.

File: pkg/clustermesh/testdata/clusterservice-multiport.txtar [hunk 7]
```diff
@@ -0,0 +1,86 @@
+#! --cluster-id=1 --cluster-name=cluster1
+
+hive/start
+
+# Create a service without selector (no epslices) with multiple ports
+# sharing the same target port, to verify that remote backends are
+# correctly grouped into a single backend with all port names.
```
Comment (MrFreezeex) [inline pkg/clustermesh/testdata/clusterservice-multiport.txtar]: nit: the rest of the sentence is more related to the backends parts, there's no need to explain all of that here IMO
```suggestion
# Create a service to which to add the external backends with multiple ports.
```

File: pkg/clustermesh/service_merger_test.go (hunk 5 above)
Comment (RiccardoAtzori91) [reply pkg/clustermesh/service_merger_test.go]: Removed unit tests and updated E2E tests with these test cases:

### Test Case 1: All service ports map to the same target port
A remote cluster service exposes three port names (http-direct, http-remapped, http-alt) all resolving to the same target port 80/TCP. The test verifies that a single backend (20.0.0.2:80/TCP) is created with all three port names aggregated, and that all three local frontends (ports 80, 8080, 9090) correctly route to that single backend.

### Test case 2 — Mixed grouped and distinct target ports
A remote cluster service exposes three port names where two (http-direct, http-remapped) share target port 80/TCP and one (https) maps to a different target port 443/TCP. The test verifies that two separate backends are created: one for 80/TCP with the two grouped port names, and one for 443/TCP with a single port name. Each frontend is correctly associated with its matching backend.

### Test case 3 — Multiple backend IPs with grouped ports
A remote cluster service exposes two backend IPs (20.0.0.2, 20.0.0.3), each with two port names (http-direct, http-remapped) mapping to the same target port 80/TCP. The test verifies that two backends are created (one per IP), each with both port names correctly aggregated, and that all frontends list both backends.

File: pkg/clustermesh/testdata/clusterservice-multiport.txtar [hunk 8]
```diff
@@ -0,0 +1,182 @@
...
+# Update the cluster service with a mix of grouped and distinct ports:
+# http-direct and http-remapped share target port 80, https is separate on 443.
+kvstore/update cilium/state/services/v1/cluster2/test/echo clusterservice2_mixed.json
+db/cmp backends backends_mixed.table
+db/cmp frontends frontends-with-clusterservice_mixed.table
+
+# Update the cluster service with two backend IPs, both with grouped ports.
+kvstore/update cilium/state/services/v1/cluster2/test/echo clusterservice2_multi_ip.json
+db/cmp backends backends_multi_ip.table
+db/cmp frontends frontends-with-clusterservice_multi_ip.table
```
Comment (MrFreezeex) [inline pkg/clustermesh/testdata/clusterservice-multiport.txtar]: Could you make all those in a single clusterservice? I think it would make it more straightforward while we could test all those within the single thing ~

File: pkg/clustermesh/service_merger.go [hunk 9]
```diff
@@ -98,26 +99,40 @@ func ClusterServiceToBackendParams(service *serviceStore.ClusterService) (beps [
...
+						l4.Port,
+						loadbalancer.ScopeExternal,
+					),
+					Weight:    loadbalancer.DefaultBackendWeight,
+					NodeName:  "",
+					ClusterID: service.ClusterID,
+					State:     loadbalancer.BackendStateActive,
+					Zone:      backendZone,
+				})
+				idx = len(beps) - 1 - currentIdx
```
Comment (MrFreezeex) [inline pkg/clustermesh/service_merger.go]: It seems to be equivalent to this?
```suggestion
				idx = len(currentBeps)
```

And actually I am not sure the `idx = len(currentBeps) - 1` was correct from the previous version of this code, as if for instance the len is `0` idx would have been `-1` 🤔

File: pkg/clustermesh/service_merger.go [hunk 10]
```diff
@@ -98,26 +99,40 @@ func ClusterServiceToBackendParams(service *serviceStore.ClusterService) (beps [
...
-				State:     loadbalancer.BackendStateActive,
-				Zone:      backendZone,
+			if name != "" {
+				beps[currentIdx+idx].PortNames = append(beps[currentIdx+idx].PortNames, name)
 			}
-			beps = append(beps, bep)
+		}
+
+		for i := currentIdx; i < len(beps); i++ {
+			slices.Sort(beps[i].PortNames)
```
Comment (MrFreezeex) [inline pkg/clustermesh/service_merger.go]: This could probably use a regular iterator like this:
```suggestion
		for _, bep := range beps {
			slices.Sort(bep.PortNames)
```

**Review by MrFreezeex — CHANGES_REQUESTED** [review]

File: pkg/clustermesh/service_merger.go (hunk 9 above)
Comment (RiccardoAtzori91) [reply pkg/clustermesh/service_merger.go]: You're right, my mistake. 
Would it be enough to use `idx = len(currentBeps)` since `len(currentBeps)` points to the newly added element?

File: pkg/clustermesh/service_merger.go (hunk 10 above)
Comment (RiccardoAtzori91) [reply pkg/clustermesh/service_merger.go]: Could I move the range with sort, as per your suggestion, out of the outer loop?

File: pkg/clustermesh/service_merger.go (hunk 9 above)
Comment (MrFreezeex) [reply pkg/clustermesh/service_merger.go]: Yep I think that `idx = len(currentBeps)` should work fine here!

File: pkg/clustermesh/service_merger.go (hunk 10 above)
Comment (MrFreezeex) [reply pkg/clustermesh/service_merger.go]: Ah yep indeed good catch done like that it would need to be done right before the final return ~ (which looks good I think?)

It also probably deserve a small comment saying that we do that because map iteration are not necessarily consistent we have to sort to ensure PortNames are in a stable order for DeepEquals to work ~.

Comment (RiccardoAtzori91) [reply pkg/clustermesh/service_merger.go]: Moved the range with sort out of the outer loop and added a comment

File: pkg/clustermesh/testdata/clusterservice-multiport.txtar (hunk 8 above)
Comment (RiccardoAtzori91) [reply pkg/clustermesh/testdata/clusterservice-multiport.txtar]: I should have moved everything to a single clusterservice. @MrFreezeex  Could you check if everything works?

File: pkg/clustermesh/testdata/clusterservice-multiport.txtar [hunk 11]
```diff
@@ -0,0 +1,106 @@
+#! --cluster-id=1 --cluster-name=cluster1
+
+hive/start
+
+# Create a service to which to add the external backends with multiple ports.
+k8s/add service.yaml
+
+# Add a remote cluster service with two backend IPs where multiple port names
+# map to the same target port and one port maps to a distinct target port.
+# http-direct and http-remapped both resolve to 80/TCP, https resolves to 443/TCP.
```
Comment (MrFreezeex) [inline pkg/clustermesh/testdata/clusterservice-multiport.txtar]: nit: we could probably simplify this comment as folks reading this could just read the actual backends below to understand it and this comment might get out of date if we update what's tested and forgetting about this comment.

Probably something like this should works:
```suggestion
# Add a remote cluster service with multiple backend IPs and ports.
# Some ports are the same and should be added to a single backend entry
# containing all the associated port names.
```

**Review by MrFreezeex — APPROVED** [review]
Thanks for the followup fixes, I added a minor nit inline about one comment in the test but otherwise LGTM, thanks again for spotting this issue and actually fixing it :D!

File: pkg/clustermesh/testdata/clusterservice-multiport.txtar (hunk 8 above)
Comment (MrFreezeex) [reply pkg/clustermesh/testdata/clusterservice-multiport.txtar]: Yep seems fine, thanks!

**Comment by MrFreezeex** [comment]
@RiccardoAtzori91 we don't squash when merging so you need to fixup/squash your second commit in the first one.

**Comment by RiccardoAtzori91** [comment]
> Thanks for the followup fixes, I added a minor nit inline about one comment in the test but otherwise LGTM, thanks again for spotting this issue and actually fixing it :D!

Thank you for your support

**Comment by RiccardoAtzori91** [comment]
> @RiccardoAtzori91 we don't squash when merging so you need to fixup/squash your second commit in the first one.

@MrFreezeex I merged the two commits into one

**Comment by MrFreezeex** [comment]
It look like the test added here is failing, see the CI run here https://github.com/cilium/cilium/actions/runs/24191528619/job/70609785435 (you could also test locally by launching `go test` on the `pkg/clustermesh` directory btw)

**Review by joamaki — APPROVED** [review]

**Comment by RiccardoAtzori91** [comment]
@MrFreezeex  the integration pipeline still fails. I'll analyze the problem and try to fix it.

File: pkg/clustermesh/testdata/clusterservice-multiport.txtar [hunk 12]
```diff
@@ -0,0 +1,114 @@
...
+# Add a remote cluster service with multiple backend IPs and ports.
+# Some ports are the same and should be added to a single backend entry
+# containing all the associated port names.
+kvstore/update cilium/state/services/v1/cluster2/test/echo clusterservice2.json
+db/cmp backends backends.table
+db/cmp frontends frontends-with-clusterservice.table
+
+# Removing the cluster service removes the backends
+kvstore/delete cilium/state/services/v1/cluster2/test/echo
+db/empty backends
```
Comment (joamaki) [inline pkg/clustermesh/testdata/clusterservice-multiport.txtar:20]: unlike `db/cmp` the `db/empty` doesn't retry by itself. The script test has the `*` modifier to retry a section (delimited by a comment), so change this to:

```
# Remove the cluster service
kvstore/delete cilium/state/services/v1/cluster2/test/echo

# Backends should now be empty
* db/empty backends
```

We need two sections here as otherwise we'd retry `kvstore/delete` which would fail on second attempt.

https://docs.cilium.io/en/latest/contributing/development/hive/#command-reference

Comment (RiccardoAtzori91) [reply pkg/clustermesh/testdata/clusterservice-multiport.txtar:20]: @MrFreezeex @joamaki  Could something like this solve this?

```txtar
#! --cluster-id=1 --cluster-name=cluster1

hive/start

# Create a service to which to add the external backends with multiple ports.
k8s/add service.yaml

# Add a remote cluster service with multiple backend IPs and ports.
# Some ports are the same and should be added to a single backend entry
# containing all the associated port names.
kvstore/update cilium/state/services/v1/cluster2/test/echo clusterservice2.json

# Verify backends and frontends are correctly populated
* db/cmp backends backends.table
* db/cmp frontends frontends-with-clusterservice.table

# Remove the cluster service
kvstore/delete cilium/state/services/v1/cluster2/test/echo

# Backends should now be empty
* db/empty backends
* db/cmp frontends frontends-without-clusterservice.table

###

-- backends.table --
Address              PortNames                           NodeName
20.0.0.2:80/TCP      http-alt,http-direct,http-remapped
20.0.0.2:443/TCP     https
20.0.0.3:80/TCP      http-alt,http-direct,http-remapped
20.0.0.3:443/TCP     https

-- frontends-with-clusterservice.table --
Address            Type       ServiceName   Status  Backends
10.0.0.1:80/TCP    ClusterIP  test/echo     Done    20.0.0.2:80/TCP, 20.0.0.3:80/TCP
10.0.0.1:443/TCP   ClusterIP  test/echo     Done    20.0.0.2:443/TCP, 20.0.0.3:443/TCP
10.0.0.1:8080/TCP  ClusterIP  test/echo     Done    20.0.0.2:80/TCP, 20.0.0.3:80/TCP
10.0.0.1:9090/TCP  ClusterIP  test/echo     Done    20.0.0.2:80/TCP, 20.0.0.3:80/TCP

-- frontends-without-clusterservice.table --
Address            Type       ServiceName   Status  Backends
10.0.0.1:80/TCP    ClusterIP  test/echo     Done
10.0.0.1:443/TCP   ClusterIP  test/echo     Done
10.0.0.1:8080/TCP  ClusterIP  test/echo     Done
10.0.0.1:9090/TCP  ClusterIP  test/echo     Done

-- clusterservice2.json --
{
  "name": "echo",
  "namespace": "test",
  "includeExternal": true,
  "shared": true,
  "cluster": "cluster2",
  "clusterID": 2,
  "backends": {
    "20.0.0.2": {
      "http-alt": {
        "Protocol": "TCP",
        "Port": 80
      },
      "http-direct": {
        "Protocol": "TCP",
        "Port": 80
      },
      "http-remapped": {
        "Protocol": "TCP",
        "Port": 80
      },
      "https": {
        "Protocol": "TCP",
        "Port": 443
      }
    },
    "20.0.0.3": {
      "http-alt": {
        "Protocol": "TCP",
        "Port": 80
      },
      "http-direct": {
        "Protocol": "TCP",
        "Port": 80
      },
      "http-remapped": {
        "Protocol": "TCP",
        "Port": 80
      },
      "https": {
        "Protocol": "TCP",
        "Port": 443
      }
    }
  }
}

-- service.yaml --
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.cilium.io/global: "true"
  name: echo
  namespace: test
spec:
  clusterIP: 10.0.0.1
  clusterIPs:
  - 10.0.0.1
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
  - name: http-direct
    port: 80
    protocol: TCP
    targetPort: 80
  - name: http-remapped
    port: 8080
    protocol: TCP
    targetPort: 80
  - name: http-alt
    port: 9090
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  type: ClusterIP
```

Comment (RiccardoAtzori91) [reply pkg/clustermesh/testdata/clusterservice-multiport.txtar:20]: Local tests passed, changes committed

Comment (MrFreezeex) [reply pkg/clustermesh/testdata/clusterservice-multiport.txtar:20]: Hmm are the retry actually needed? I don't see any retry in the other script so it looks a bit weird 🤔

Comment (RiccardoAtzori91) [reply pkg/clustermesh/testdata/clusterservice-multiport.txtar:20]: Sorry, I misunderstood db/cmp's behavior.
Could we keep **db/cmp backend** and **db/cmp frontend** without * since it's redundant and leave it alone in db/empty backend, since the latter doesn't retry?

Comment (MrFreezeex) [reply pkg/clustermesh/testdata/clusterservice-multiport.txtar:20]: Hmm I think you just need to invert the order of empty and cmp and then remove all the `*` since when the cmp will pass empty will also pass. I think that's what the other script are relying on to work ~.

Comment (RiccardoAtzori91) [reply pkg/clustermesh/testdata/clusterservice-multiport.txtar:20]: > Hmm I think you just need to invert the order of empty and cmp and then remove all the `*` since when the cmp will pass empty will also pass. I think that's what the other script are relying on to work ~.

Ok, that makes sense to me. Updated tests.

**Comment by RiccardoAtzori91** [comment]
@MrFreezeex / @joamaki The Conformance L7-only (ci-l7) and Conformance L3-L4 only (ci-l3-l4) failures are infrastructure-related (etcd pod timeout and DaemonSet not ready), i supposed. Is it possible, please, re-trigger them?

**Comment by RiccardoAtzori91** [comment]
@MrFreezeex Thank you for your support and patience.
This was my first contribution, and I'm very happy to have been able to help fix the bug.
