### PR TITLE
test: Fix fragment tracking test under KUBEPROXY=1

### LINKED ISSUE #10929: CI: K8sServicesTest Checks service across nodes Supports IPv4 Fragments: Failed to account for IPv4 fragments
## K8sServicesTest Checks service across nodes Supports IPv4 Fragments

Failed with:
```
18:45:16  • Failure [65.024 seconds]
18:45:16  K8sServicesTest
18:45:16  /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:395
18:45:16    Checks service across nodes
18:45:16    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:395
18:45:16      Supports IPv4 fragments [It]
18:45:16      /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430
18:45:16  
18:45:16      Failed to account for IPv4 fragments (in)
[2020-04-10T01:45:16.250Z]     Expected
[2020-04-10T01:45:16.250Z]         <[]int | len:2, cap:2>: [21, 20]
[2020-04-10T01:45:16.250Z]     To satisfy at least one of these matchers: [%!s(*matchers.EqualMatcher=&{[16 24]}) %!s(*matchers.EqualMatcher=&{[20 20]})]
```

Seen here:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/18664/
-->
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/18664/execution/node/198/log/?consoleFull
PR #10910

Dump:
[3db90426_K8sServicesTest_Checks_service_across_nodes_Supports_IPv4_fragments.zip](https://github.com/cilium/cilium/files/4459754/3db90426_K8sServicesTest_Checks_service_across_nodes_Supports_IPv4_fragments.zip)

```
18:44:10  ------------------------------
18:44:10  K8sServicesTest Checks service across nodes 
18:44:10    Supports IPv4 fragments
18:44:10    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430
18:44:12  STEP: Sending a fragmented packet from testclient-jtsw2 to endpoint 10.109.193.120:10069
18:44:17  STEP: Sending a fragmented packet from testclient-jtsw2 to endpoint 192.168.36.11:31165
18:44:21  STEP: Sending a fragmented packet from testclient-jtsw2 to endpoint ::ffff:192.168.36.11:31165
18:44:26  STEP: Sending a fragmented packet from testclient-jtsw2 to endpoint 192.168.36.12:31165
18:44:31  STEP: Sending a fragmented packet from testclient-jtsw2 to endpoint ::ffff:192.168.36.12:31165
18:44:35  STEP: Sending a fragmented packet from testclient-jtsw2 to endpoint 127.0.0.1:31165
18:44:40  STEP: Sending a fragmented packet from testclient-jtsw2 to endpoint ::ffff:127.0.0.1:31165
18:44:45  STEP: Sending a fragmented packet from testclient-jtsw2 to endpoint 10.10.0.137:31165
18:44:49  STEP: Sending a fragmented packet from testclient-jtsw2 to endpoint ::ffff:10.10.0.137:31165
18:44:54  STEP: Sending a fragmented packet from testclient-jtsw2 to endpoint 10.10.1.184:31165
18:44:56  === Test Finished at 2020-04-10T01:44:56Z====
18:44:56  ===================== TEST FAILED =====================
18:44:57  cmd: kubectl get pods -o wide --all-namespaces
18:44:57  Exitcode: 0 
18:44:57  Stdout:
18:44:57   	 NAMESPACE     NAME                               READY   STATUS    RESTARTS   AGE   IP              NODE   NOMINATED NODE
18:44:57  	 default       test-k8s2-848b6f7864-wtdsq         2/2     Running   0          19m   10.10.1.121     k8s2   <none>
18:44:57  	 default       testclient-jtsw2                   1/1     Running   0          19m   10.10.0.59      k8s1   <none>
18:44:57  	 default       testclient-kbt2w                   1/1     Running   0          19m   10.10.1.38      k8s2   <none>
18:44:57  	 default       testds-fh7kp                       2/2     Running   0          19m   10.10.1.11      k8s2   <none>
18:44:57  	 default       testds-l22kb                       2/2     Running   0          19m   10.10.0.34      k8s1   <none>
18:44:57  	 kube-system   cilium-nws8f                       1/1     Running   0          1m    192.168.36.11   k8s1   <none>
18:44:57  	 kube-system   cilium-operator-645465fc56-cbqfc   1/1     Running   0          1m    192.168.36.12   k8s2   <none>
18:44:57  	 kube-system   cilium-tmz5l                       1/1     Running   0          1m    192.168.36.12   k8s2   <none>
18:44:57  	 kube-system   coredns-687db6485c-scn4s           1/1     Running   0          1m    10.10.1.60      k8s2   <none>
18:44:57  	 kube-system   etcd-k8s1                          1/1     Running   0          27m   192.168.36.11   k8s1   <none>
18:44:57  	 kube-system   kube-apiserver-k8s1                1/1     Running   0          27m   192.168.36.11   k8s1   <none>
18:44:57  	 kube-system   kube-controller-manager-k8s1       1/1     Running   0          27m   192.168.36.11   k8s1   <none>
18:44:57  	 kube-system   kube-scheduler-k8s1                1/1     Running   0          27m   192.168.36.11   k8s1   <none>
18:44:57  	 kube-system   log-gatherer-cbhxj                 1/1     Running   0          24m   192.168.36.12   k8s2   <none>
18:44:57  	 kube-system   log-gatherer-txst6                 1/1     Running   0          24m   192.168.36.13   k8s3   <none>
18:44:57  	 kube-system   log-gatherer-vjdqj                 1/1     Running   0          24m   192.168.36.11   k8s1   <none>
18:44:57  	 kube-system   registry-adder-4qf7h               1/1     Running   0          25m   192.168.36.11   k8s1   <none>
18:44:57  	 kube-system   registry-adder-gd5tg               1/1     Running   0          25m   192.168.36.12   k8s2   <none>
18:44:57  	 kube-system   registry-adder-zbmv8               1/1     Running   0          25m   192.168.36.13   k8s3   <none>
18:44:57  	 
18:44:57  Stderr:
18:44:57   	 
18:44:57  
18:44:57  Fetching command output from pods [cilium-nws8f cilium-tmz5l]
18:45:16  cmd: kubectl exec -n kube-system cilium-nws8f -- cilium service list
18:45:16  Exitcode: 0 
18:45:16  Stdout:
18:45:16   	 ID   Frontend               Service Type   Backend                   
18:45:16  	 1    10.96.0.1:443          ClusterIP      1 => 192.168.36.11:6443   
18:45:16  	 2    10.96.0.10:53          ClusterIP      1 => 10.10.1.60:53        
18:45:16  	 3    192.168.36.240:80      LoadBalancer   1 => 10.10.0.34:80        
18:45:16  	                                            2 => 10.10.1.11:80        
18:45:16  	 4    192.168.36.241:80      LoadBalancer                             
18:45:16  	 19   10.107.95.129:80       ClusterIP      1 => 10.10.0.34:80        
18:45:16  	                                            2 => 10.10.1.11:80        
18:45:16  	 20   10.107.95.129:69       ClusterIP      1 => 10.10.0.34:69        
18:45:16  	                                            2 => 10.10.1.11:69        
18:45:16  	 21   10.109.193.120:10080   ClusterIP      1 => 10.10.0.34:80        
18:45:16  	                                            2 => 10.10.1.11:80        
18:45:16  	 22   10.109.193.120:10069   ClusterIP      1 => 10.10.0.34:69        
18:45:16  	                                            2 => 10.10.1.11:69        
18:45:16  	 23   0.0.0.0:31129          NodePort       1 => 10.10.0.34:80        
18:45:16  	                                            2 => 10.10.1.11:80        
18:45:16  	 24   192.168.36.11:31129    NodePort       1 => 10.10.0.34:80        
18:45:16  	                                            2 => 10.10.1.11:80        
18:45:16  	 25   10.10.0.137:31129      NodePort       1 => 10.10.0.34:80        
18:45:16  	                                            2 => 10.10.1.11:80        
18:45:16  	 26   10.10.0.137:31165      NodePort       1 => 10.10.0.34:69        
18:45:16  	                                            2 => 10.10.1.11:69        
18:45:16  	 27   0.0.0.0:31165          NodePort       1 => 10.10.0.34:69        
18:45:16  	                                            2 => 10.10.1.11:69        
18:45:16  	 28   192.168.36.11:31165    NodePort       1 => 10.10.0.34:69        
18:45:16  	                                            2 => 10.10.1.11:69        
18:45:16  	 29   10.104.253.7:10080     ClusterIP      1 => 10.10.0.34:80        
18:45:16  	                                            2 => 10.10.1.11:80        
18:45:16  	 30   10.104.253.7:10069     ClusterIP      1 => 10.10.0.34:69        
18:45:16  	                                            2 => 10.10.1.11:69        
18:45:16  	 31   0.0.0.0:31440          NodePort       1 => 10.10.0.34:80        
18:45:16  	 32   192.168.36.11:31440    NodePort       1 => 10.10.0.34:80        
18:45:16  	 33   10.10.0.137:31440      NodePort       1 => 10.10.0.34:80        
18:45:16  	 34   0.0.0.0:31699          NodePort       1 => 10.10.0.34:69        
18:45:16  	 35   192.168.36.11:31699    NodePort       1 => 10.10.0.34:69        
18:45:16  	 36   10.10.0.137:31699      NodePort       1 => 10.10.0.34:69        
18:45:16  	 37   10.98.104.99:10080     ClusterIP      1 => 10.10.1.121:80       
18:45:16  	 38   10.98.104.99:10069     ClusterIP      1 => 10.10.1.121:69       
18:45:16  	 39   0.0.0.0:32096          NodePort                                 
18:45:16  	 40   192.168.36.11:32096    NodePort                                 
18:45:16  	 41   10.10.0.137:32096      NodePort                                 
18:45:16  	 42   0.0.0.0:30340          NodePort                                 
18:45:16  	 43   192.168.36.11:30340    NodePort                                 
18:45:16  	 44   10.10.0.137:30340      NodePort                                 
18:45:16  	 45   10.108.142.75:10080    ClusterIP      1 => 10.10.1.121:80       
18:45:16  	 46   10.108.142.75:10069    ClusterIP      1 => 10.10.1.121:69       
18:45:16  	 47   0.0.0.0:32658          NodePort       1 => 10.10.1.121:80       
18:45:16  	 48   192.168.36.11:32658    NodePort       1 => 10.10.1.121:80       
18:45:16  	 49   10.10.0.137:32658      NodePort       1 => 10.10.1.121:80       
18:45:16  	 50   0.0.0.0:30795          NodePort       1 => 10.10.1.121:69       
18:45:16  	 51   192.168.36.11:30795    NodePort       1 => 10.10.1.121:69       
18:45:16  	 52   10.10.0.137:30795      NodePort       1 => 10.10.1.121:69       
18:45:16  	 53   10.109.125.148:80      ClusterIP      1 => 10.10.0.34:80        
18:45:16  	                                            2 => 10.10.1.11:80        
18:45:16  	 54   0.0.0.0:31767          NodePort       1 => 10.10.0.34:80        
18:45:16  	                                            2 => 10.10.1.11:80        
18:45:16  	 55   192.168.36.11:31767    NodePort       1 => 10.10.0.34:80        
18:45:16  	                                            2 => 10.10.1.11:80        
18:45:16  	 56   10.10.0.137:31767      NodePort       1 => 10.10.0.34:80        
18:45:16  	                                            2 => 10.10.1.11:80        
18:45:16  	 57   10.109.100.175:80      ClusterIP      1 => 10.10.1.121:80       
18:45:16  	 58   0.0.0.0:30574          NodePort                                 
18:45:16  	 59   192.168.36.11:30574    NodePort                                 
18:45:16  	 60   10.10.0.137:30574      NodePort                                 
18:45:16  	 61   192.168.36.12:8080     HostPort       1 => 10.10.1.121:80       
18:45:16  	 62   192.168.36.12:6969     HostPort       1 => 10.10.1.121:69       
18:45:16  	 
18:45:16  Stderr:
18:45:16   	 
18:45:16  
18:45:16  cmd: kubectl exec -n kube-system cilium-nws8f -- cilium endpoint list
18:45:16  Exitcode: 0 
18:45:16  Stdout:
18:45:16   	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                       IPv6                 IPv4         STATUS   
18:45:16  	            ENFORCEMENT        ENFORCEMENT                                                                                                      
18:45:16  	 2043       Disabled           Disabled          4          reserved:health                                   f00d::a0b:0:0:789    10.10.0.71   ready   
18:45:16  	 3197       Disabled           Disabled          16933      k8s:io.cilium.k8s.policy.cluster=default          f00d::a0b:0:0:615b   10.10.0.34   ready   
18:45:16  	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                             
18:45:16  	                                                            k8s:io.kubernetes.pod.namespace=default                                                     
18:45:16  	                                                            k8s:zgroup=testDS                                                                           
18:45:16  	 3646       Disabled           Disabled          2250       k8s:io.cilium.k8s.policy.cluster=default          f00d::a0b:0:0:abb8   10.10.0.59   ready   
18:45:16  	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                             
18:45:16  	                                                            k8s:io.kubernetes.pod.namespace=default                                                     
18:45:16  	                                                            k8s:zgroup=testDSClient                                                                     
18:45:16  	 
18:45:16  Stderr:
18:45:16   	 
18:45:16  
18:45:16  cmd: kubectl exec -n kube-system cilium-tmz5l -- cilium service list
18:45:16  Exitcode: 0 
18:45:16  Stdout:
18:45:16   	 ID   Frontend               Service Type   Backend                   
18:45:16  	 1    10.96.0.1:443          ClusterIP      1 => 192.168.36.11:6443   
18:45:16  	 2    10.96.0.10:53          ClusterIP      1 => 10.10.1.60:53        
18:45:16  	 3    192.168.36.240:80      LoadBalancer   1 => 10.10.0.34:80        
18:45:16  	                                            2 => 10.10.1.11:80        
18:45:16  	 4    192.168.36.241:80      LoadBalancer   1 => 10.10.1.121:80       
18:45:16  	 19   10.107.95.129:80       ClusterIP      1 => 10.10.0.34:80        
18:45:16  	                                            2 => 10.10.1.11:80        
18:45:16  	 20   10.107.95.129:69       ClusterIP      1 => 10.10.0.34:69        
18:45:16  	                                            2 => 10.10.1.11:69        
18:45:16  	 21   10.109.193.120:10080   ClusterIP      1 => 10.10.0.34:80        
18:45:16  	                                            2 => 10.10.1.11:80        
18:45:16  	 22   10.109.193.120:10069   ClusterIP      1 => 10.10.0.34:69        
18:45:16  	                                            2 => 10.10.1.11:69        
18:45:16  	 23   0.0.0.0:31129          NodePort       1 => 10.10.0.34:80        
18:45:16  	                                            2 => 10.10.1.11:80        
18:45:16  	 24   192.168.36.12:31129    NodePort       1 => 10.10.0.34:80        
18:45:16  	                                            2 => 10.10.1.11:80        
18:45:16  	 25   10.10.1.184:31129      NodePort       1 => 10.10.0.34:80        
18:45:16  	                                            2 => 10.10.1.11:80        
18:45:16  	 26   0.0.0.0:31165          NodePort       1 => 10.10.0.34:69        
18:45:16  	                                            2 => 10.10.1.11:69        
18:45:16  	 27   192.168.36.12:31165    NodePort       1 => 10.10.0.34:69        
18:45:16  	                                            2 => 10.10.1.11:69        
18:45:16  	 28   10.10.1.184:31165      NodePort       1 => 10.10.0.34:69        
18:45:16  	                                            2 => 10.10.1.11:69        
18:45:16  	 29   10.104.253.7:10069     ClusterIP      1 => 10.10.0.34:69        
18:45:16  	                                            2 => 10.10.1.11:69        
18:45:16  	 30   10.104.253.7:10080     ClusterIP      1 => 10.10.0.34:80        
18:45:16  	                                            2 => 10.10.1.11:80        
18:45:16  	 31   0.0.0.0:31699          NodePort       1 => 10.10.1.11:69        
18:45:16  	 32   192.168.36.12:31699    NodePort       1 => 10.10.1.11:69        
18:45:16  	 33   10.10.1.184:31699      NodePort       1 => 10.10.1.11:69        
18:45:16  	 34   192.168.36.12:31440    NodePort       1 => 10.10.1.11:80        
18:45:16  	 35   10.10.1.184:31440      NodePort       1 => 10.10.1.11:80        
18:45:16  	 36   0.0.0.0:31440          NodePort       1 => 10.10.1.11:80        
18:45:16  	 37   10.98.104.99:10080     ClusterIP      1 => 10.10.1.121:80       
18:45:16  	 38   10.98.104.99:10069     ClusterIP      1 => 10.10.1.121:69       
18:45:16  	 39   0.0.0.0:32096          NodePort       1 => 10.10.1.121:80       
18:45:16  	 40   192.168.36.12:32096    NodePort       1 => 10.10.1.121:80       
18:45:16  	 41   10.10.1.184:32096      NodePort       1 => 10.10.1.121:80       
18:45:16  	 42   0.0.0.0:30340          NodePort       1 => 10.10.1.121:69       
18:45:16  	 43   192.168.36.12:30340    NodePort       1 => 10.10.1.121:69       
18:45:16  	 44   10.10.1.184:30340      NodePort       1 => 10.10.1.121:69       
18:45:16  	 45   10.108.142.75:10080    ClusterIP      1 => 10.10.1.121:80       
18:45:16  	 46   10.108.142.75:10069    ClusterIP      1 => 10.10.1.121:69       
18:45:16  	 47   192.168.36.12:32658    NodePort       1 => 10.10.1.121:80       
18:45:16  	 48   10.10.1.184:32658      NodePort       1 => 10.10.1.121:80       
18:45:16  	 49   0.0.0.0:32658          NodePort       1 => 10.10.1.121:80       
18:45:16  	 50   0.0.0.0:30795          NodePort       1 => 10.10.1.121:69       
18:45:16  	 51   192.168.36.12:30795    NodePort       1 => 10.10.1.121:69       
18:45:16  	 52   10.10.1.184:30795      NodePort       1 => 10.10.1.121:69       
18:45:16  	 53   10.109.125.148:80      ClusterIP      1 => 10.10.0.34:80        
18:45:16  	                                            2 => 10.10.1.11:80        
18:45:16  	 54   0.0.0.0:31767          NodePort       1 => 10.10.0.34:80        
18:45:16  	                                            2 => 10.10.1.11:80        
18:45:16  	 55   192.168.36.12:31767    NodePort       1 => 10.10.0.34:80        
18:45:16  	                                            2 => 10.10.1.11:80        
18:45:16  	 56   10.10.1.184:31767      NodePort       1 => 10.10.0.34:80        
18:45:16  	                                            2 => 10.10.1.11:80        
18:45:16  	 57   10.109.100.175:80      ClusterIP      1 => 10.10.1.121:80       
18:45:16  	 58   0.0.0.0:30574          NodePort       1 => 10.10.1.121:80       
18:45:16  	 59   192.168.36.12:30574    NodePort       1 => 10.10.1.121:80       
18:45:16  	 60   10.10.1.184:30574      NodePort       1 => 10.10.1.121:80       
18:45:16  	 61   192.168.36.12:8080     HostPort       1 => 10.10.1.121:80       
18:45:16  	 62   192.168.36.12:6969     HostPort       1 => 10.10.1.121:69       
18:45:16  	 
18:45:16  Stderr:
18:45:16   	 
18:45:16  
18:45:16  cmd: kubectl exec -n kube-system cilium-tmz5l -- cilium endpoint list
18:45:16  Exitcode: 0 
18:45:16  Stdout:
18:45:16   	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                       IPv6                 IPv4          STATUS   
18:45:16  	            ENFORCEMENT        ENFORCEMENT                                                                                                       
18:45:16  	 453        Disabled           Disabled          6937       k8s:io.cilium.k8s.policy.cluster=default          f00d::a0c:0:0:e6e9   10.10.1.60    ready   
18:45:16  	                                                            k8s:io.cilium.k8s.policy.serviceaccount=coredns                                              
18:45:16  	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                  
18:45:16  	                                                            k8s:k8s-app=kube-dns                                                                         
18:45:16  	 571        Disabled           Disabled          16933      k8s:io.cilium.k8s.policy.cluster=default          f00d::a0c:0:0:aec6   10.10.1.11    ready   
18:45:16  	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                              
18:45:16  	                                                            k8s:io.kubernetes.pod.namespace=default                                                      
18:45:16  	                                                            k8s:zgroup=testDS                                                                            
18:45:16  	 864        Disabled           Disabled          4          reserved:health                                   f00d::a0c:0:0:c3eb   10.10.1.170   ready   
18:45:16  	 2544       Disabled           Disabled          18702      k8s:io.cilium.k8s.policy.cluster=default          f00d::a0c:0:0:d20b   10.10.1.121   ready   
18:45:16  	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                              
18:45:16  	                                                            k8s:io.kubernetes.pod.namespace=default                                                      
18:45:16  	                                                            k8s:zgroup=test-k8s2                                                                         
18:45:16  	 3376       Disabled           Disabled          2250       k8s:io.cilium.k8s.policy.cluster=default          f00d::a0c:0:0:7d8a   10.10.1.38    ready   
18:45:16  	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                              
18:45:16  	                                                            k8s:io.kubernetes.pod.namespace=default                                                      
18:45:16  	                                                            k8s:zgroup=testDSClient                                                                      
18:45:16  	 
18:45:16  Stderr:
18:45:16   	 
18:45:16  
18:45:16  ===================== Exiting AfterFailed =====================
18:45:16  <Checks>
18:45:16  Number of "context deadline exceeded" in logs: 0
18:45:16  Number of "level=error" in logs: 0
18:45:16  Number of "level=warning" in logs: 0
18:45:16  Number of "Cilium API handler panicked" in logs: 0
18:45:16  Number of "Goroutine took lock for more than" in logs: 0
18:45:16  No errors/warnings found in logs
18:45:16  Cilium pods: [cilium-nws8f cilium-tmz5l]
18:45:16  Netpols loaded: 
18:45:16  CiliumNetworkPolicies loaded: 
18:45:16  Endpoint Policy Enforcement:
18:45:16  Pod                          Ingress   Egress
18:45:16  test-k8s2-848b6f7864-wtdsq             
18:45:16  testclient-jtsw2                       
18:45:16  testclient-kbt2w                       
18:45:16  testds-fh7kp                           
18:45:16  testds-l22kb                           
18:45:16  coredns-687db6485c-scn4s               
18:45:16  Cilium agent 'cilium-nws8f': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 19 Failed 0
18:45:16  Cilium agent 'cilium-tmz5l': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 26 Failed 0
18:45:16  
18:45:16  </Checks>
18:45:16  
18:45:16  [[ATTACHMENT|3db90426_K8sServicesTest_Checks_service_across_nodes_Supports_IPv4_fragments.zip]]
18:45:16  
18:45:16  • Failure [65.024 seconds]
18:45:16  K8sServicesTest
18:45:16  /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:395
18:45:16    Checks service across nodes
18:45:16    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:395
18:45:16      Supports IPv4 fragments [It]
18:45:16      /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:430
18:45:16  
18:45:16      Failed to account for IPv4 fragments (in)
[2020-04-10T01:45:16.250Z]     Expected
[2020-04-10T01:45:16.250Z]         <[]int | len:2, cap:2>: [21, 20]
[2020-04-10T01:45:16.250Z]     To satisfy at least one of these matchers: [%!s(*matchers.EqualMatcher=&{[16 24]}) %!s(*matchers.EqualMatcher=&{[20 20]})]
18:45:16  
18:45:16      /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.11-gopath/src/github.com/cilium/cilium/test/k8sT/Services.go:548
18:45:16  ------------------------------
```

### PR DESCRIPTION
**Pull request by pchaigno**
First commit simplifies fragment tracking test to match on 3-tuple instead of 4-tuple. The second commit fixes the test to support `KUBEPROXY=1`. See commit messages for details.

Fixes: #10929
/cc @qmonnet

### CODE REVIEW

**Comment by pchaigno** [comment]
test-me-please

File: test/k8sT/Services.go [hunk 1]
```diff
@@ -450,11 +450,13 @@ var _ = Describe("K8sServicesTest", func() {
...
 		// dstIP:       Target endpoint IP for sending the datagram
 		// dstPort:     Target endpoint port for sending the datagram
-		doFragmentedRequest := func(srcPod string, srcIP string, fromNode string, dstPodPort int, dstIP string, dstPort int32) {
+		// kubeProxy:   True if kube-proxy is enabled
+		doFragmentedRequest := func(srcPod, srcIP, fromNode string, dstPodPort int, dstIP string, dstPort int32, kubeProxy bool) {
 			var (
 				blockSize  = 5120
 				blockCount = 1
 				srcPort    = 12345
+				hostIP     = "10.0.2.15"
```
Comment (qmonnet) [inline test/k8sT/Services.go]: Could we get this value from elsewhere? Not sure if `node.GetExternalIPv4()` is relevant?

File: test/k8sT/Services.go [hunk 2]
```diff
@@ -479,29 +482,55 @@ var _ = Describe("K8sServicesTest", func() {
...
+				if strings.HasSuffix(dstIP, k8s2IP) {
+					newSrcIP1, err = kubectl.GetCiliumHostIPv4(context.TODO(), helpers.K8s2)
+					Expect(err).Should(BeNil(), "Cannot retrieve remote cilium_host ipv4")
+					newSrcIP2 = hostIP
+				} else {
+					newSrcIP1 = hostIP
+					newSrcIP2, err = kubectl.GetCiliumHostIPv4(context.TODO(), helpers.K8s1)
+					Expect(err).Should(BeNil(), "Cannot retrieve local cilium_host ipv4")
+				}
+			}
```
Comment (qmonnet) [inline test/k8sT/Services.go]: Maybe turn that block into a `if { } else { }` and do all the setting for `endpoingK8s*` and `patternInK8s*` in it? introducing the `newSrcIP*` on the kube-free path does not help readability I think.

File: test/k8sT/Services.go [hunk 3]
```diff
@@ -479,29 +482,55 @@ var _ = Describe("K8sServicesTest", func() {
...
 			// Field #11 is "TxPackets=<n>"
 			cmdOut := "cilium bpf ct list global | awk '/%s/ { sub(\".*=\",\"\", $11); print $11 }'"
 
+			if kubeProxy {
+				// If kube-proxy is enabled, we see packets in ctmap with the
+				// service's IP address and port, not backend's.
+				dstIPv4 := strings.Replace(dstIP, "::ffff:", "", 1)
+				endpointK8s1 = fmt.Sprintf("%s:%d", dstIPv4, dstPort)
+				endpointK8s2 = endpointK8s1
+			}
```
Comment (qmonnet) [inline test/k8sT/Services.go:496]: Move this to the previous `if kubeProxy`?

**Review by qmonnet — COMMENTED** [review]
Thanks a lot! This looks great and looks correct in regard to my understanding of the issue.

The test does become more complicated to read, but I see no ideal solution. We could decouple the test function for the kubeproxy/kube-free cases, but we would end up with something longer in total and with a lot of duplicated code. Still, a few suggestions inline.

Could you please explain what you mean about the `fromNode == helpers.K8s2` case? I didn't get your point :/.

File: test/k8sT/Services.go (hunk 1 above)
Comment (pchaigno) [reply test/k8sT/Services.go]: We can't use that method in tests, can we?

I don't like this either. I looked at using e.g., `GetNodeIPByLabel(..., true)`, but it wasn't returning anything (the `ExternalIP` field didn't exist in kubectl's JSON output). This seems expected since other tests are also hardcoding the IP:
```
$ git grep 10.0.2.15
k8sT/Services.go:                               hostIP     = "10.0.2.15"
runtime/Policies.go:            hostIP := "10.0.2.15"
runtime/Policies.go:                    endpointID, _ := createEndpoint("ping", "10.0.2.15")
runtime/Policies.go:                            endpointID, _ := createEndpoint("ping", "10.0.2.15")
runtime/Policies.go:                    hostIP := "10.0.2.15"
```
At the very least, we could move this value to some shared file, like `helpers.K8s1IP`.

File: test/k8sT/Services.go [hunk 4]
```diff
@@ -479,29 +482,55 @@ var _ = Describe("K8sServicesTest", func() {
...
+			newSrcIP2 := srcIP
+			if kubeProxy {
+				// If kube-proxy is enabled, source IP address are SNATed.
+				if strings.HasSuffix(dstIP, k8s2IP) {
+					newSrcIP1, err = kubectl.GetCiliumHostIPv4(context.TODO(), helpers.K8s2)
+					Expect(err).Should(BeNil(), "Cannot retrieve remote cilium_host ipv4")
+					newSrcIP2 = hostIP
+				} else {
+					newSrcIP1 = hostIP
+					newSrcIP2, err = kubectl.GetCiliumHostIPv4(context.TODO(), helpers.K8s1)
```
Comment (pchaigno) [inline test/k8sT/Services.go]: For the `fromNode == helpers.K8s2` case:
Here we are basically inverting `newSrcIP1` and `newSrcIP2` based on whether the destination is on `k8s1` or `k8s2`. I'm expecting this does not actually depend on `k8s1` vs. `k8s2`, but on whether the destination is on the same node as the source or not. So this depends on `fromNode`.

However, as far as I can see, the tests do not make use of the `fromNode` parameter, so I'm wondering if we should just remove it and consider we always send from `k8s1`.

**Comment by pchaigno** [comment]
Thanks for taking a look!

> The test does become more complicated to read, but I see no ideal solution. We could decouple the test function for the kubeproxy/kube-free cases, but we would end up with something longer in total and with a lot of duplicated code.

What about:
> Maybe matching on the source port without the source IP address
would be enough?

Do we really risk having flakes if we match on the 3-tuple instead of the 4-tuple? I've had tcpdump running for a long time during those tests and never saw anything else using UDP port 12345. I think it would simplify the test a lot.

File: test/k8sT/Services.go (hunk 4 above)
Comment (qmonnet) [reply test/k8sT/Services.go]: Ok, thanks. Yeah, you're probably right, we can try that.

**Comment by qmonnet** [comment]
> Do we really risk having flakes if we match on the 3-tuple instead of the 4-tuple?

Probably not. I used as much as I could for a maximum of caution, but it sound very unlikely that we get a duplicate flow by matching just on the 3-tuple. That's a good idea.

File: test/k8sT/Services.go (hunk 1 above)
Comment (qmonnet) [reply test/k8sT/Services.go]: I'm good with moving it to a helper, let's not spend too much on this. We can improve in the future if necessary, or maybe someone else will review and have an idea on how to get it in a clean way.

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
I ran the fragment tracking test locally, 29 times with kube-proxy and 160 times without kube-proxy. Haven't seen any flakes, so matching on 3-tuple is probably safe. We could have issues once we start running the test in the context of the test suites though.

**Comment by qmonnet** [comment]
We look at the number of packets right before and right after sending the datagram, so to have a conflict not only would we need to have another flow with the same IP and ports which is not very likely, but it would also have to send frames within a very short window. I think it's safe to match on the 3-tuple.

**Review by qmonnet — APPROVED** [review]
Looks great, thanks a lot for debugging and patching this!

**Review by aanm — APPROVED** [review]
