### PR TITLE
pkg/datapath: ignore certain error types on route delete

### LINKED ISSUE #15728: Give better UX to log message "Failed to remove route" error="no such process"
It seems to me this is actually a failure that can be ignored if the error message is "no such process".

```
2021-04-15T16:02:44.730739174Z level=info msg="Identity of endpoint changed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=728 identity=57859 identityLabels="k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=default,k8s:run=my-nginx" ipv4= ipv6= k8sPodName=/ oldIdentity="no identity" subsys=endpoint
2021-04-15T16:02:44.730742827Z level=info msg="Waiting for endpoint to be generated" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=728 identity=57859 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2021-04-15T16:02:44.945170674Z level=warning msg="Failed to remove route" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=728 error="no such process" identity=57859 ipv4= ipv6= k8sPodName=/ subsys=datapath-loader veth=lxce78b6c6e9f92
2021-04-15T16:02:44.945197439Z level=info msg="Rewrote endpoint BPF program" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=728 identity=57859 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2021-04-15T16:02:44.945201664Z level=info msg="Successful endpoint creation" containerID= datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=728 identity=57859 ipv4= ipv6= k8sPodName=/ subsys=daemon
2021-04-15T16:02:44.945204938Z level=info msg="API call has been processed" name=endpoint-create processingDuration=214.922573ms subsys=rate totalDuration=215.035693ms uuid=431803e6-c08e-4838-b7f4-f16e62ba8446 waitDurationTotal=0s
2021-04-15T16:02:44.952217637Z level=warning msg="Failed to remove route" containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=159 error="no such process" identity=57859 ipv4= ipv6= k8sPodName=/ subsys=datapath-loader veth=lxc76c65a67ae83
```

### PR DESCRIPTION
**Pull request by aanm**
When removing endpoint routes it is not always necessary to log errors.
One example would be in case the returned error from the kernel would be
"no such process"

Fixes: c4581b37dc1c ("loader : Log upsert and remove route errors")
Signed-off-by: André Martins <andre@cilium.io>

Fixes https://github.com/cilium/cilium/issues/15728

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by qmonnet — APPROVED** [review]

File: pkg/datapath/loader/loader.go [hunk 1]
```diff
@@ -360,7 +362,7 @@ func (l *Loader) reloadDatapath(ctx context.Context, ep datapath.Endpoint, dirs
 				scopedLog.WithError(err).Warn("Failed to upsert route")
 			}
 		} else {
-			if err := removeEndpointRoute(ep, *ip.IPNet(32)); err != nil {
+			if err := removeEndpointRoute(ep, *ip.IPNet(32)); err != nil && !errors.Is(err, syscall.ESRCH) {
```
Comment (pchaigno) [inline pkg/datapath/loader/loader.go:365]: Is that returned when the route was already removed? If so, when and why was it removed?

Comment (pchaigno) [reply pkg/datapath/loader/loader.go:365]: Discussed offline: given it's called in `reloadDatapath`, we will attempt to delete the route every time we reload the endpoint's BPF programs, even if we never even installed the route. So the ESRCH makes sense :+1:

**Review by pchaigno — APPROVED** [review]

**Comment by aanm** [comment]
test-1.16-netnext

**Comment by aanm** [comment]
Merging since it hit https://github.com/cilium/cilium/issues/15737 and https://github.com/cilium/cilium/issues/15744

**Comment by joestringer** [comment]
Wow, weird! I would have expected ENOENT.
