### PR TITLE
.travis:fix up TestShuffle failure on Arm64

### LINKED ISSUE #12512: CI: Travis failed on arm64: TestShuffle FAIL
CI failure Link:
https://travis-ci.com/github/cilium/cilium/jobs/359548956#L13718

```
=== RUN   TestShuffle
    TestShuffle: safe_rand_test.go:68: Shuffle() did not modify s2 in 10 retries
--- FAIL: TestShuffle (0.00s)
FAIL
coverage: 22.9% of statements in ./...
FAIL	github.com/cilium/cilium/pkg/rand	0.018s
FAIL
```

### PR DESCRIPTION
**Pull request by Jianlin-lv**
After shuffling, there is a small probability event that
the order of elements has not changed;
The results of multiple tests should prevail.

Signed-off-by: Jianlin Lv <Jianlin.Lv@arm.com>

Fixes: #12512

### CODE REVIEW

**Review by pchaigno — APPROVED** [review]
Thanks a lot @Jianlin-lv!

Am I understanding correctly that this flake isn't actually specific to ARM?

I validated this by running this unit test 10k times in a loop. Without this patch it failed 93/10000 (~1%); with this patch it didn't fail even once :tada:

**Comment by Jianlin-lv** [comment]
> Thanks a lot @Jianlin-lv!
> 
> Am I understanding correctly that this flake isn't actually specific to ARM?
> 
> I validated this by running this unit test 10k times in a loop. Without this patch it failed 93/10000 (~1%); with this patch it didn't fail even once 🎉

From the experience of fixing multiple Travis issues on the ARM platform,
Most of them are caused by code defects, and are not strongly related to the architecture; it is only easier to expose these issue on the Arm platform.

File: pkg/rand/safe_rand_test.go [hunk 1]
```diff
@@ -37,16 +37,14 @@ func TestIntn(t *testing.T) {
...
 	s1 := []string{"1", "2", "3", "4", "5"}
 	s2 := make([]string, len(s1))
 	copy(s2, s1)
 
 	var same int
-	for retry := 0; retry < 1; retry++ {
+	for retry := 0; retry < 10; retry++ {
 		same = 0
-
+		r0 := NewSafeRand(time.Now().UnixNano())
```
Comment (qmonnet) [inline pkg/rand/safe_rand_test.go]: I agree we should try more than once (this `retry < 1` looks like a mistake in the first place), but I don't think it should be necessary to recreate a `NewSafeRand()` each time? Have you tried by simply setting the number of retries to `10`, without moving this line?

**Review by qmonnet — CHANGES_REQUESTED** [review]

File: pkg/rand/safe_rand_test.go (hunk 1 above)
Comment (Jianlin-lv) [reply pkg/rand/safe_rand_test.go]: I have verified that, in the case of the same seed, each call to r0.Shuffle will get a different array sequence;
Your suggestion is feasible, I will update this patch. Thanks!

**Review by qmonnet — APPROVED** [review]
Thanks a lot!

**Comment by qmonnet** [comment]
The for loop with the single retry has been backported to v1.7 and v1.8, I'm marking this commit for backports too so as to limit CI flakes.
