### PR TITLE
kvstore: Fix identity override with labels prefix

### LINKED ISSUE #7559: Wrong identity labels in Cilium Identity
## Bug report

**General Information**

- Cilium version (run `cilium version`)
```
Client: 1.4.90 dbb2ef1c2 2019-03-22T13:27:57-07:00 go version go1.12.1 linux/amd64
Daemon: 1.4.90 dbb2ef1c2 2019-03-22T13:27:57-07:00 go version go1.12.1 linux/amd64
```
- Kernel version (run `uname -a`)
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
- Link to relevant artifacts (policies, deployments scripts, ...)
- Upload a system dump (run `curl -sLO
releases.cilium.io/tools/cluster-diagnosis.zip &&
python cluster-diagnosis.zip sysdump` and then attach the generated zip file)

**How to reproduce the issue**

1. Run the following command in a cluster with multiple worker nodes (i.e. running multiple Cilium pods).
2. Observe that the output of `cilium identity get` is inconsistent for the same identity on distinct nodes.

```
$ k exec -it cilium-tw9tc -n kube-system -- bash
root@ip-172-0-124-60:~# cilium identity get 61725 -o json
[
  {
    "id": 61725,
    "labels": [
      "k8s:io.kubernetes.pod.namespace=default",
      "k8s:io.cilium.k8s.policy.cluster=default",
      "k8s:io.cilium.k8s.policy.serviceaccount=default"
    ],
    "labelsSHA256": "eaabc3506e8c6ffa845f082db93722cf3589986f46a6c682ee863533258b2e3d"
  }
]
```
```
$ k exec -it cilium-45247 -n kube-system -- bash
root@ip-172-0-163-219:~# cilium identity get 61725 -o json
[
  {
    "id": 61725,
    "labels": [
      "k8s:name=echo",
      "k8s:io.cilium.k8s.policy.cluster=default",
      "k8s:io.cilium.k8s.policy.serviceaccount=default",
      "k8s:io.kubernetes.pod.namespace=default"
    ],
    "labelsSHA256": "0442def83549945cf069a8bc4f932e1a945e9d5f4253825fd7173eb78d533e8a"
  }
]
```
The second output is the correct one. The first one misses the "k8s:name=echo" tag.

### PR DESCRIPTION
**Pull request by joestringer**
```release-note
Fix bug where creating a pod with no labels could cause drops for other pods within the same namespace.
```

Previously, when attempting to determine whether an identity exists for
a set of labels, we would perform a prefix lookup with the desired
labels and if an identity is found, unconditionally use that identity,
without checking that the set of specified labels matches the labels of
the identity that was found. This could lead to a situation where if an
endpoint is deployed on a node with a labels subset of another
endpoint's labels, the local node would override the labels for that
identity with the shorter set of labels. As a result, policy which
selects the longer set of labels may potentially not apply, which
assuming a "deny-all" ingress security posture, would lead to packet
drops when the policy would appear to allow traffic to the endpoint with
the longer set of labels.

This patch fixes the issue by returning the key that was found, then
trimming the suffix (which represents the node IP), then comparing the
length of this key against the labels that were used to perform the
lookup. If the length is the same, then the labels are the same and the
identity can be reused. Otherwise, it cannot be reused and we will back
out and attempt to allocate a new numeric identity for this set of
labels.

Note this still leaves one possibility open: The kvstore GetPrefix()
interface does not guarantee which key will be found if two keys with
the same prefix are in the kvstore and a prefix lookup is performed for
the shorter key. In this case, GetNoCache() may return that no key is
found when there is in fact an identity for the shorter prefix. This
could potentially lead to an increase in the number of identities for
the shorter prefix, however this will not affect existing identities.
This situation is deemed unlikely enough that cleaning up this case is
deferred for now.

Fixes: #7559

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7565)

### CODE REVIEW

**Comment by joestringer** [comment]
I've run the `daemon`, `pkg/kvstore`, `pkg/kvstore/allocator` tests locally and validated that they pass.

**Comment by joestringer** [comment]
test-me-please

EDIT: Green build.

File: pkg/kvstore/base_test.go [hunk 1]
```diff
@@ -91,14 +93,50 @@ func (s *BaseTests) TestGetSet(c *C) {
...
 	}
 
-	val, err = GetPrefix(context.Background(), prefix)
+	key, val, err = GetPrefix(context.Background(), prefix)
 	c.Assert(err, IsNil)
 	c.Assert(val, IsNil)
+	c.Assert(key, Equals, "")
+}
+
+func (s *BaseTests) TestGetPrefix(c *C) {
```
Comment (joestringer) [inline pkg/kvstore/base_test.go:108]: NB: This new test doesn't actually test the bug, but it was also missing. I played around a little with a `pkg/kvstore/allocator` test to validate the fix but I couldn't figure it out just yet, will need more time to work through unit test structure issues.

File: pkg/kvstore/allocator/allocator.go [hunk 2]
```diff
@@ -590,18 +590,33 @@ func (a *Allocator) Get(ctx context.Context, key AllocatorKey) (idpool.ID, error
 	return a.GetNoCache(ctx, key)
 }
 
+func prefixMatchesKey(prefix, key string) bool {
+	// cilium/state/identities/v1/value/label;foo;bar;/172.0.124.60
+	//
+	// Presumably node IPs could also be IPv6
+	k := strings.TrimRight(key, "/0123456789abcdef:")
```
Comment (joestringer) [inline pkg/kvstore/allocator/allocator.go]: This assumes that the key version of the labels list ends with a semicolon. This appears to be the case based on real entries dumped from a test Cilium cluster.

**Comment by joestringer** [comment]
test-me-please

EDIT: Hit a variation on #7495

File: pkg/kvstore/allocator/allocator.go [hunk 3]
```diff
@@ -590,18 +590,35 @@ func (a *Allocator) Get(ctx context.Context, key AllocatorKey) (idpool.ID, error
 	return a.GetNoCache(ctx, key)
 }
 
+func prefixMatchesKey(prefix, key string) bool {
+	// cilium/state/identities/v1/value/label;foo;bar;/172.0.124.60
+	//
+	// labels.SortedList() ensures that the final character in the list of
+	// labels is a semi-colon, which we explicitly leave out of the call
+	// below to strings.TrimRight().
+	k := strings.TrimRight(key, "/0123456789abcdef:")
```
Comment (tgraf) [inline pkg/kvstore/allocator/allocator.go]: I'm not sure if that cutset will work. An alternative would be something like this:
```
k := strings.TrimPrefix(key, prefix)
return k[0] == '/' && strings.Count(k, "/") == 1
```

It would mean that we don't support `/` as part of the node name but it will be liberal otherwise.

**Review by tgraf — CHANGES_REQUESTED** [review]

File: pkg/kvstore/allocator/allocator.go (hunk 3 above)
Comment (joestringer) [reply pkg/kvstore/allocator/allocator.go]: Ah, is the node name not guaranteed to be an IP, so we try to leave the option open to allow FQDNs in these keys in future or something? Or do you have another case in mind?

Another alternative would be to just do a `strings.Split(key, '/')` and join all but the last. Might be a bit more expensive though.

Comment (joestringer) [reply pkg/kvstore/allocator/allocator.go]: How about something like this?

```
        lastSlash := strings.LastIndex(key, "/")                                
        return len(prefix) == lastSlash
```

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
`runtime.RuntimePrivilegedUnitTests Run Tests` failed. Unclear why. Trying again.

**Comment by tgraf** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Comment by ianvernon** [comment]
Istio test failure : https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11238/

This is a known issue which occurs due to endpoint deletion while an endpoint program is being built. Not related to this PR; merging.
