### PR TITLE
SocketLB: Terminate connections for services with mixed protocols

### LINKED ISSUE #37577: Long lived unidirectional UDP connections trough a service failing to reach new endpoints
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.0 and lower than v1.18.0

### What happened?

Hello,

We use Cilium 1.17.0 with kube-proxy replacement mode enabled.

We have recently installed the Datadog agent on our clusters. The Datadog agent expose a Datadog service. The clients will send a continuous UDP stream (using the `statsd` protocol) to this service.

At first, everything seemed to work well, but after a few days we noticed an extreme increase in the number of dropped packets reported by Hubble exporter.

After investigation, these packets were drop as the destination IP was no longer the IP of an existing Datadog pod (that would register as an endpoint in the Datadog service).

Once we restart the Datadog Daemonset, the `statsd` protocol stop working.

I started to try to understand how Cilium ended up in this state. My theory is that when we open a socket with a service IP, the service IP will be replaced by an endpoint IP in the following Kernel function (on RHEL9) by Cilium eBPF:

[https://elixir.bootlin.com/linux/v5.14/source/kernel/bpf/cgroup.c#L1066](https://elixir.bootlin.com/linux/v5.14/source/kernel/bpf/cgroup.c#L1066)

As this happen at socket creation, each time the Datadog agent will use the `write` syscall on the socket file descriptor, the IP of the endpoint found in the sock structure will be used.

This is something that work very well for TCP connections as they will be broken when the old endpoints are stopped and then be reopened later. It also doesn't cause issue with short lived UDP connections. But this cannot work for long lived unidirectional UDP connections as the source have no way to know that the socket must be reopened.

Obviously these is some simple protocol changes that would fix the issue on the Datadog side, and I could also deploy Datadog using hostNetwork. Meanwhile I'm reporting this issue as this is a legit network communication pattern not properly supported by Cilium at the moment.

Best Regards.

### How can we reproduce the issue?

1. Install Cilium 1.17.0 with kube-proxy replacement mode
2. Create a deployment of pods exposing an UDP server
3. Create a service with these pods as endpoints
4. Create a deployment continuously sending packets to this service
5. Restart the server deployment
6. The UDP packets no longer reach the servers

### Cilium Version

1.17.0

### Kernel Version

5.14.0-503.16.1.el9_5.x86_64

### Kubernetes Version

1.31.2

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by foyerunix**
Hello,

Fixes: https://github.com/cilium/cilium/issues/37577

Following my issue, I continued my investigations to understand why the UDP sockets weren't closed.

I first added a log line at the beginning of `TerminateUDPConnectionsToBackend` to check if I enter the function as I ddin't see the "handling udp connections to deleted backend" log.

What I discovered is that the `l3n4Addr.Protocol` field wasn't set to "UDP" but to "ANY", which I understood being due to having both a TCP and an UDP port on my service.

I therefore added a check for "ANY" in `l3n4Addr.Protocol` and then set the `protocol` variable to UDP.

It resolved my issue in my environment, and, as I understand the code, cannot cause any new issue.

Best Regards.

```release-note
Fix connections to deleted service backends not getting terminated in certain cases involving services with multiple protocol ports.
```

### CODE REVIEW

**Comment by foyerunix** [comment]
Hello @aditighag,

Thanks for running the tests. I've reviewed the failures:

"The action 'Wait for images to be available (downgrade)' has timed out after 10 minutes."

- This seems to be a build error unrelated to my PR.

"Failed to execute tcpdump on cilium-test-3/host-netns-wtqnd (kind-worker2): command failed (pod=cilium-test-3/host-netns-wtqnd, container=): error reading from error stream: next reader: websocket: close 1006 (abnormal closure): unexpected EOF"

- This appears to be an error during the test setup. Tcpdump needs to run to check if the captured packets match some condition.

"command 'curl -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code}\n --silent --fail --show-error --output /dev/null --connect-timeout 2 --max-time 10 http://[fc00:c111::5]:30755' failed: command failed (pod=cilium-test-4/host-netns-non-cilium-pjg8p, container=host-netns-non-cilium): command terminated with exit code 28"

- This might indicate my PR is breaking TCP connections.

"Expected to capture packets, but none found. This check might be broken."

- This could be a flaky test.

"timeout=5s error='rpc error: code = Unavailable desc = dns: A record lookup error: lookup hubble-peer.kube-system.svc.cluster.local. on 10.100.0.10:53: read udp 192.168.122.27:33793->10.100.0.10:53: i/o timeout' subsys=hubble-relay"

- This might be due to my patch overclosing sockets.

Could you help me distinguish between CI issues and those caused by my fix?

Additionally, I'd appreciate your feedback on the code itself. It works in my environment without issues, but I'm open to reworking my PR if you see a better solution.

Best regards.

File: pkg/service/connections.go [hunk 1]
```diff
@@ -43,6 +43,8 @@ func (s *Service) TerminateUDPConnectionsToBackend(l3n4Addr *lb.L3n4Addr) {
 	switch l3n4Addr.Protocol {
 	case lb.UDP:
 		protocol = unix.IPPROTO_UDP
+	case lb.ANY:
```
Comment (aditighag) [inline pkg/service/connections.go]:
```suggestion
	case lb.UDP, lb.ANY:
	        protocol = unix.IPPROTO_UDP
```

**Review by aditighag — CHANGES_REQUESTED** [review]
Could you rebase your PR? There were certain CI issues that were fixed upstream recently. 
I wonder if this is a regression introduced by the protocol differentiation changes - https://github.com/cilium/cilium/pull/33434/commits. Are you able to reproduce this issue by setting the config flag `bpf-lb-proto-diff` to `false`?
Also, I've added a release note to the PR description - https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request.

**Comment by foyerunix** [comment]
Hello @aditighag,

Thank for fixing the release note, I thought my PR title was suitable as a release note.

I made the following test:
- deploy Cilium 1.17.0
- set `bpf-lb-proto-diff` to `false` in the Cilium configmap
- restart the Cilium daemonset
- restart the daemonset of the service that is receiving packets from long lived UDP connections

After looking at Hubble, I still see the symptomatic drops of UDP packets going to non-existing backends.

The PR was rebased and I accepted your change.

Best Regards.

**Comment by aditighag** [comment]
@foyerunix All tests passed. Can you drop my sign-off from the commit? Once you've force pushed to the PR, we need not run the full CI test suite before merging the PR.

**Comment by aditighag** [comment]
@foyerunix I wasn't able to reproduce the issue locally. See snippets from my testing below.

Can you share the repro steps including your service manifest?

```
$ k get svc
NAME            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)           AGE
echo            ClusterIP   10.96.132.231   <none>        80/TCP,69/UDP     119s

$ ks logs cilium-mtskr | grep -i handling
time="2025-03-04T21:31:24.278942184Z" level=info msg="handling udp connections to deleted backend 10.244.1.54:80/TCP" subsys=service
time="2025-03-04T21:31:24.279089498Z" level=info msg="handling udp connections to deleted backend 10.244.1.54:69/UDP" subsys=service

diff --git a/pkg/service/connections.go b/pkg/service/connections.go
index 292d1ba4db..b12465a541 100644
--- a/pkg/service/connections.go
+++ b/pkg/service/connections.go
@@ -25,6 +25,7 @@ import (
 var opSupported = true

 func (s *Service) TerminateUDPConnectionsToBackend(l3n4Addr *lb.L3n4Addr) {
+       log.Infof("handling udp connections to deleted backend %v", l3n4Addr)
        // With socket-lb, existing client applications can continue to connect to
        // deleted backends. Destroy any client sockets connected to the deleted backend.
        if !(option.Config.EnableSocketLB || option.Config.BPFSocketLBHostnsOnly) {
```

**Comment by foyerunix** [comment]
Hello @aditighag,

I dropped your sign-off from the commit.

I didn't build a minimal reproducer that allow to reproduce the issue without having to install the Datadog agent.

I have looked at your snippets and:

```
time="2025-03-04T21:31:24.278942184Z" level=info msg="handling udp connections to deleted backend 10.244.1.54:80/TCP" subsys=service
time="2025-03-04T21:31:24.279089498Z" level=info msg="handling udp connections to deleted backend 10.244.1.54:69/UDP" subsys=service
```

Is not what I got when I added debugging. You should have: `10.244.1.54:69/ANY`.

Here is my service spec:

```
spec:
  clusterIP: [redacted]
  clusterIPs:
  - [redacted]
  internalTrafficPolicy: Local
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dogstatsdport
    port: 8125
    protocol: UDP
    targetPort: 8125
  - name: traceport
    port: 8126
    protocol: TCP
    targetPort: 8126
  selector:
    app: datadog
  sessionAffinity: None
  type: ClusterIP
```

Best Regards.

**Comment by joestringer** [comment]
Seems like this stalled - are we looking for further confirmation from @foyerunix or do we think the change is right? As far as I follow it seems like the calling code doesn't discriminate on the protocol of the service, and ANY could mean there are UDP connections. Or do we already expand out ANY to each individual protocol in `l3n4Addr`?

I couldn't immediately find tests for this functionality but I guess if we extended the testsuite that could help to prove the correct behavior.

**Comment by foyerunix** [comment]
Hello @aditighag,

I can confirm that I have the same issue with Cilium 1.17.2.

**Comment by borkmann** [comment]
> I have looked at your snippets and:
> 
> ```
> time="2025-03-04T21:31:24.278942184Z" level=info msg="handling udp connections to deleted backend 10.244.1.54:80/TCP" subsys=service
> time="2025-03-04T21:31:24.279089498Z" level=info msg="handling udp connections to deleted backend 10.244.1.54:69/UDP" subsys=service
> ```

Does this mean that we also attempt to close TCP from above, but eventually fail since socket cookie + TCP doesn't exist?
I think temporary we could land this, but iirc @tommyp1ckles might be following up with actually terminating TCP as well which should then also land till 1.18.

**Comment by aditighag** [comment]
Hi @foyerunix Could you rebase your PR?

**Comment by foyerunix** [comment]
Hi @aditighag,

Done.

Best Regards.

**Comment by aditighag** [comment]
>🟥 failed to flush ct entries: %w command failed (pod=kube-system/cilium-zds6t, container=cilium-agent): "time=\"2025-04-16T15:13:14.440649371Z\" level=info msg=\"completed ctmap gc pass\" aliveEntries=0 deleted=3611 family=ipv4 proto=TCP skipped=0 subsys=map-ct\ntime=\"2025-04-16T15:13:14.444586669Z\" level=info msg=\"completed ctmap gc pass\" aliveEntries=0 deleted=422 family=ipv4 proto=non-TCP skipped=0 subsys=map-ct\ntime=\"2025-04-16T15:13:14.446563167Z\" level=info msg=\"completed ctmap gc pass\" aliveEntries=0 deleted=120 family=ipv6 proto=TCP skipped=0 subsys=map-ct\ntime=\"2025-04-16T15:13:14.447961547Z\" level=info msg=\"completed ctmap gc pass\" aliveEntries=0 deleted=66 family=ipv6 proto=non-TCP skipped=0 subsys=map-ct\n"

Hit unrelated CI issue.

**Review by aditighag — APPROVED** [review]

**Comment by deadok22** [comment]
Hey @foyerunix, thanks for the fix! 

We just ran into this very issue!

Could you help me understand the new behavior?

Once `s.backendConnectionHandler.Destroy(...)` is called, what is going to happen, from the perspective of a client attempting writes through a connected udp socket? Do such clients get to continue using the existing socket fd or do they need to make a new one?

**Comment by foyerunix** [comment]
Hello @julianwiedmann,

I can confirm that my Datadog service was created before upgrading to Cilium 1.17.

**Comment by ysksuzuki** [comment]
When `loadBalancer.protocolDifferentiation.enabled=false`, the service protocol is treated as `ANY`. In this case, `TerminateUDPConnectionsToBackend` does not terminate UDP sockets. Since v1.17 supports protocol differentiation but it may be disabled, we should backport this fix.
https://github.com/cilium/cilium/blob/7206f0f7003cc5ca2f1ddeed531892ff2ecb2a4b/pkg/k8s/watchers/service.go#L554-L558
