### PR TITLE
kvstore: fix lease lifetime issues causing permanently impaired agent/operator

### LINKED ISSUE #42596: Cilium Agent stuck with KVStore Operations failing with "lease not found"
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.18.3 and lower than v1.19.0

### What happened?

In one of our clusters running Cilium 1.18.2 in KVStore mode, one Agent got stuck in a degraded state for 16h. It suddenly seemed unable to perform `update` operations on `ip/v1` and `nodes/v1`, as well as `create` and `update` on `identities/v1`.

Failing KVStore operations:

Image

Successful KVStore operations:

Image

Looking at Agent logs, all of them seemed to have the "lease not found" error, for example like this:
```
retrying of unary invoker failed
rpc error: code = NotFound desc = etcdserver: requested lease not found

{
  "caller": "v3/retry_interceptor.go:65",
  "method": "/etcdserverpb.KV/Put",
  "level": "warn",
  "attempt": 0,
  "ts": "2025-11-03T18:13:52.631390Z",
}
```

Another example:

<pre>
Unable to re-create alive ipcache entry
etcdserver: requested lease not found

{
  "level": "warn",
  "module": "agent.controlplane.ipcache",
  "time": "2025-11-03T15:02:48.092110338Z",
  "ipAddr": "<b>IP_HERE</b>",
}
</pre>

With a corresponding server-side etcd log:

<pre>
failed to apply request
lease not found

{
  "took": "7.169µs",
  "request": "header:ID:4225108826588833389 username:\"cilium-agent\" auth_revision:1  
put:key:\"cilium/state/ip/v1/default/<b>SAME_IP_HERE</b>\" value_size:249 <b>lease:6262424858532430636</b> ",
  "caller": "etcdserver/util.go:123",
  "level": "warn",
  "response": "",
  "ts": "2025-11-03T15:02:52.872705Z",
}
</pre>

Searching for all etcd server-side failure logs with **lease:6262424858532430636**, shows that they have been erroring for hours:

Image

The errors stopped when we rotated the pod.

Unfortunately we haven't been able to take a sysdump, so we only have logs and metrics to investigate. I wonder if there could be some race condition in the [`etcdLeaseManager`](https://github.com/cilium/cilium/blob/2be1f9d8ace25b9020a3cb755f140dd46184550d/pkg/kvstore/etcd_lease.go#L30) causing the client to be stuck for hours with a non-existent lease?

### How can we reproduce the issue?

Unclear for now

### Cilium Version

`1.18.2`

### Kernel Version

```
Linux #43~22.04.1-Ubuntu SMP Wed Sep 24 23:11:19 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
```

### Kubernetes Version

```
Server Version: v1.33.1
```

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

Etcd version:
```
3.5.17
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by odinuge**
This fixes an issue where cilium will incorrectly use an expired kvstore lease. This was reported in https://github.com/cilium/cilium/issues/42596 by @antonipp. See the commit message for more details.

~Opening now to run test to ensure we don't regress. Will look into catching this in a test.~ test done ✅ 

Fixes: https://github.com/cilium/cilium/issues/42596 
Fixes: e9b47957 ("kvstore: introduce the lease manager")

```release-note
Fix rare kvstore issue where cilium continues to use an expired lease causing kvstore operations to fail consistently
```

### CODE REVIEW

File: pkg/kvstore/etcd_lease.go [hunk 1]
```diff
@@ -168,6 +168,8 @@ func (elm *etcdLeaseManager) GetSession(ctx context.Context, key string) (*concu
 	elm.leases[session.Lease()] = &leaseInfo{session: session}
 	elm.mu.Unlock()
 
+	go elm.waitForExpiration(session)
+
 	return elm.GetSession(ctx, key)
```
Comment (odinuge) [inline pkg/kvstore/etcd_lease.go:178]: There is always a chance of this `GetSession` call running in a loop, but that is not something new in this change - although it can happen _more_ often. So I think that deserves a separate change if we deem it a problem.

File: pkg/kvstore/etcd_lease_test.go [hunk 2]
```diff
@@ -144,9 +150,41 @@ func TestLeaseManager(t *testing.T) {
...
+			wg.Done()
+		}(i)
+	}
+	wg.Wait()
+
+	// Wait for all leases to expire and do cleanup
+	mgr.Wait()
+
+	// Ensure all leases have been cleaned up since they have all expired
+	require.Equal(t, uint32(0), mgr.TotalLeases())
```
Comment (odinuge) [inline pkg/kvstore/etcd_lease_test.go:177]: Consistently getting an error here when running against latest `main`, altough the number is different each time;
```
    etcd_lease_test.go:183:
                Error Trace:    /mnt/code/pkg/kvstore/etcd_lease_test.go:183
                Error:          Not equal:
                                expected: 0x0
                                actual  : 0x3
                Test:           TestLeaseThatExpiresImmediately
```

File: pkg/kvstore/etcd_lease.go [hunk 3]
```diff
@@ -253,7 +255,6 @@ func (elm *etcdLeaseManager) newSession(ctx context.Context) (session *concurren
 	}
 
 	elm.wg.Add(1)
```
Comment (giorio94) [inline pkg/kvstore/etcd_lease.go]: The `elm.wg.Add` line should be moved as well. Even better, the two of them could be replaced by `elm.wg.Go(func() { elm.waitForExpiration(session) })`, additionally dropping `defer elm.wg.Done()` from `waitForExpiration`.

File: pkg/kvstore/etcd_lease.go [hunk 4]
```diff
@@ -168,6 +168,8 @@ func (elm *etcdLeaseManager) GetSession(ctx context.Context, key string) (*concu
 	elm.leases[session.Lease()] = &leaseInfo{session: session}
 	elm.mu.Unlock()
 
+	go elm.waitForExpiration(session)
```
Comment (giorio94) [inline pkg/kvstore/etcd_lease.go]: Nit. Could you please also add a brief comment here that this needs to be run after inserting the entry into the local data structure? Just to complement the amazing commit message and make sure that we don't lose context over time, if there were to be a refactoring.

File: pkg/kvstore/etcd_lease.go (hunk 1 above)
Comment (giorio94) [reply pkg/kvstore/etcd_lease.go:178]: Yep. Arguably, the only case in which that could happen continuously is if the just acquired lease keeps expiring instantly (and then it would be down to who wins the race between the expiration check and the next iteration). If there are concerns, though, we could add a safeguard to return an error after a given number of attempts, to prevent the risk of an infinite recursion.

File: pkg/kvstore/etcd_lease_test.go [hunk 5]
```diff
@@ -144,9 +150,41 @@ func TestLeaseManager(t *testing.T) {
...
+		cancel()
+		mgr.Wait()
+	})
+
+	// Perform multiple requests in parallel, simulating a lot of clients that
+	// are trying to get leases concurrently that all effectively expire immediately.
+	cl.grantDelay = 1 * time.Millisecond
+
+	var wg sync.WaitGroup
+	for i := range 10000 {
```
Comment (giorio94) [inline pkg/kvstore/etcd_lease_test.go]: Nit. I'd suggest to lower this number to 1K or 2K, so that the test is much faster (which means it is also easier to check that it is not flaky), as that still seems to catch the previously incorrect behavior with high probability.

**Review by giorio94 — APPROVED** [review]
Thanks a lot! Looks great to me, I've just left a couple of minor comments inline.

File: pkg/kvstore/etcd_lease_test.go (hunk 5 above)
Comment (odinuge) [reply pkg/kvstore/etcd_lease_test.go]: Good call. Seems like its pretty reliable at failing at 1k when removing the `cl.grantDelay = 1 * time.Millisecond`, so I can update to do that instead 👍

File: pkg/kvstore/etcd_lease.go (hunk 3 above)
Comment (odinuge) [reply pkg/kvstore/etcd_lease.go]: Hmm, yeah, I was also thinking about this, and thought keeping the existing behavior makes sense.

The main think is that even the current `elm.wg.Add(1)` is executed _after_ the goroutine is started / the new session is created. So this can in theory (right?) result in the `func (elm *etcdLeaseManager) Wait()` succeeding after a lease is created but before its added by `elm.wg.Add(1)`.

Sooo, my hunch is that its easier to fix that in a separate PR, or do you disagree? I can also add a separate commit here as well, since I've effectively already done that locally.

File: pkg/kvstore/etcd_lease.go (hunk 4 above)
Comment (odinuge) [reply pkg/kvstore/etcd_lease.go]: Sounds good, can do!

File: pkg/kvstore/etcd_lease.go (hunk 3 above)
Comment (odinuge) [reply pkg/kvstore/etcd_lease.go]: But the`wg.Go(func()` suggestion is great in general. I'll switch to that in the test case!

Comment (giorio94) [reply pkg/kvstore/etcd_lease.go]: > The main think is that even the current elm.wg.Add(1) is executed after the goroutine is started / the new session is created. So this can in theory (right?) result in the func (elm *etcdLeaseManager) Wait() succeeding after a lease is created but before its added by elm.wg.Add(1)

I agree that from a functional point of view there's no practical difference. The reason for my comment is mostly around readability, as otherwise the link between the waitgroup and the `waitForExpiration` goroutine is lost, and subsequent readers (or ourselves in the future) may start wondering why that is the case, and potentially incorrectly add one more `elm.wg.Add(1)` call right before the goroutine.

Comment (odinuge) [reply pkg/kvstore/etcd_lease.go]: Yee, makes sense. I'll move it then, and we can FLUP the wg lifetime in a separate change 👍

Comment (giorio94) [reply pkg/kvstore/etcd_lease.go]: Thanks!

**Review by giorio94 — APPROVED** [review]
:rocket:

File: pkg/kvstore/etcd_lease.go (hunk 3 above)
Comment (odinuge) [reply pkg/kvstore/etcd_lease.go]: I wonder if something like this is a good way of doing it, or do you have a better idea?

```diff
diff --git a/pkg/kvstore/etcd_lease.go b/pkg/kvstore/etcd_lease.go
index 55cbab3638..ad8fde3272 100644
--- a/pkg/kvstore/etcd_lease.go
+++ b/pkg/kvstore/etcd_lease.go
@@ -137,6 +137,12 @@ func (elm *etcdLeaseManager) GetSession(ctx context.Context, key string) (*concu
        // while acquiring a new lease, since it might be a slow operation.
        elm.mu.Unlock()

+       // Add a delta to the WaitGroup that is cleared when the function returns to ensure that elm.Wait will
+       // block as long as this is running. In case a new lease is created, a separate delta will be added
+       // before this one is cleared
+       elm.wg.Add(1)
+       defer elm.wg.Done()
+
        // Someone else is already acquiring a new lease. Wait until
        // it completes, and then retry again.
        if acquiring != nil {
```

Found it hard to create a nice way of doing it without doing a lot of `if this context is cancelled then`. I think this should be all good, since we know that the `elm.client.Ctx()` context is cancelled before `elm.Wait()` is executed..

Comment (odinuge) [reply pkg/kvstore/etcd_lease.go]: Hmm, the check of `elm.client.Ctx()` below only happens if `acquiring != nil` so maybe thats not sufficient then..

Comment (giorio94) [reply pkg/kvstore/etcd_lease.go]: Hmm, I'm not so sure this is something actually worthy fixing TBH, unless I'm missing something. 

The lifecycle of the main etcd client, used when Cilium is configured in kvstore mode is handled via Hive, and all of its consumers are expected to have already stopped when `Close` is called (and thus `GetSession` cannot be called at that time). This is not totally true as of today, but the only consequence of this (arguably very rare) race condition is that a newly created goroutine would terminate slightly later, given that the context is canceled anyways. 

It is also not a problem in the context of Cluster Mesh, both because the client is shutdown more cleanly there (i.e., all consumers have already terminated when closed), and because leases are not used in that context.

My main reservation about fixing it is that it would essentially couple `Wait` with this manager cannot be used anymore (i.e., letting GetSession always return an error in that case), which is fine, but a more convoluted change that probably doesn't add much value.
