### PR TITLE
bpf,test: Fixed bugs when running BPF tests on older kernels

### LINKED ISSUE #22779: bpf_tests: Loading of unused programs causes test failures on older kernels
Running the BPF unit tests on older (pre 5.8) kernels results in errors while loading.

```
ubuntu@dev:~/go/src/github.com/cilium/cilium$ make -C test run_bpf_tests
make: Entering directory '/home/ubuntu/go/src/github.com/cilium/cilium/test'
make -C ../bpf/tests all
make[1]: Entering directory '/home/ubuntu/go/src/github.com/cilium/cilium/bpf/tests'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/ubuntu/go/src/github.com/cilium/cilium/bpf/tests'
go test ./bpf_tests -exec sudo -bpf-test-path /home/ubuntu/go/src/github.com/cilium/cilium/bpf/tests 
--- FAIL: TestBPF (0.18s)
    bpf_test.go:215: Unknown message type=0 arg1=3520 arg2=65664
    bpf_test.go:215: Conntrack lookup 1/2: src=192.168.0.1:22334 dst=172.16.10.1:80
    bpf_test.go:215: Conntrack lookup 2/2: nexthdr=132 flags=4
    bpf_test.go:215: CT verdict: New, revnat=0
    bpf_test.go:215: Service backend slot lookup: slot=1, dport=80
    bpf_test.go:215: Conntrack create: proxy-port=0 revnat=256 src-identity=0 lb=0.0.0.0
    bpf_test.go:215: Loopback SNAT from=192.168.0.1 to=10.245.255.31
    bpf_test.go:215: Conntrack lookup 1/2: src=10.245.255.31:22334 dst=192.168.0.1:80
    bpf_test.go:215: Conntrack lookup 2/2: nexthdr=132 flags=1
    bpf_test.go:215: CT verdict: New, revnat=0
    bpf_test.go:215: Failed to map addr=192.168.0.1 to identity
    bpf_test.go:215: Conntrack create: proxy-port=0 revnat=256 src-identity=1048575 lb=10.245.255.31
    bpf_test.go:215: Attempting local delivery for container id 0 from seclabel 1048575
    bpf_test.go:215: Conntrack lookup 1/2: src=192.168.0.1:80 dst=10.245.255.31:22334
    bpf_test.go:215: Conntrack lookup 2/2: nexthdr=132 flags=1
    bpf_test.go:215: CT entry found lifetime=2741446, revnat=256
    bpf_test.go:215: CT verdict: Reply, revnat=256
    bpf_test.go:215: Failed to map addr=10.245.255.31 to identity
    bpf_test.go:215: Reverse NAT lookup, index=256
    bpf_test.go:215: Performing reverse NAT, address=172.16.10.1 port=80
    bpf_test.go:215: Loopback reverse SNAT from=10.245.255.31 to=192.168.0.1
    bpf_test.go:215: Attempting local delivery for container id 0 from seclabel 1048575
    bpf_test.go:154: new coll: program cil_sock6_getpeername: load program: invalid argument
FAIL
FAIL	github.com/cilium/cilium/test/bpf_tests	0.225s
FAIL
make: *** [Makefile:88: run_bpf_tests] Error 1
make: Leaving directory '/home/ubuntu/go/src/github.com/cilium/cilium/test'
```

Root cause is that the `cil_sock6_getpeername` program is a `cgroup/getpeername6` program which was introduced in kernel 5.8.
Additionally, cgroups have no support for BPF_PROG_RUN, so loading such a program is useless in the first place. Therefor my suggested fix for this issue is to modify the runner so it only loads programs that are relavent(executed as part of the test suite or are values in a tail call map).

### LINKED ISSUE #22780: bpf_tests: Not removing the memory lock on pre 5.11 kernels causes the tests to fail
When executing the BPF Unit/Integration tests on a pre 5.11 kernel the following error occurs:

```
ubuntu@dev:~/go/src/github.com/cilium/cilium$ make -C test run_bpf_tests
make: Entering directory '/home/ubuntu/go/src/github.com/cilium/cilium/test'
make -C ../bpf/tests all
make[1]: Entering directory '/home/ubuntu/go/src/github.com/cilium/cilium/bpf/tests'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/ubuntu/go/src/github.com/cilium/cilium/bpf/tests'
go test ./bpf_tests -exec sudo -bpf-test-path /home/ubuntu/go/src/github.com/cilium/cilium/bpf/tests 
--- FAIL: TestBPF (0.00s)
    bpf_test.go:149: new coll: map test_cilium_ipcache: map create: prealloc maps not supported (requires >= v4.6)
FAIL
FAIL	github.com/cilium/cilium/test/bpf_tests	0.055s
FAIL
make: *** [Makefile:88: run_bpf_tests] Error 1
make: Leaving directory '/home/ubuntu/go/src/github.com/cilium/cilium/test'
ubuntu@dev:~/go/src/github.com/cilium/cilium$ uname -a
Linux dev 5.4.0-124-generic #140-Ubuntu SMP Thu Aug 4 02:27:01 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

While seemingly unrelated to the root cause, this issue is in fact because the test runner doesn't remove the memlock rlimit. During debugging, adding a call to `rlimit.RemoveMemlock()` before loading any collections resolved this issue.

### PR DESCRIPTION
**Pull request by dylandreimerink**
The BPF unit/integration tests had some trouble running on older kernels (<=5.8). That is because the test runner always attempted to load all programs in the ELF. This fix makes it so we only attempt to load XDP and TC programs, both of which have `BPF_PROG_RUN` support.

This PR also removes the rlimit memory lock which is required on pre-5.11 kernels.

Fixes: #22779
Fixes: #22780

```release-note
Fixed BPF tests which would fail on older kernels (<=5.8) due to unsupported program loading
```

### CODE REVIEW

**Comment by ldelossa** [comment]
@dylandreimerink changes look OK to me, just a bit confused about one thing. 


Seems like these changes were to help support kernels <= 5.8, but these changes seem to be blanket, for all kernels. Is this OK? I imagine these changes were not necessary for >= 5.8, and if so do we loose some coverage on non-XDP/TC programs?

**Review by ldelossa — APPROVED** [review]

**Comment by dylandreimerink** [comment]
This PR only touches the CI runner which is covered by Travis CI, no need for E2E tests. Marking as ready-to-merge.

File: test/bpf_tests/bpf_test.go [hunk 1]
```diff
@@ -269,9 +274,21 @@ func loadAndPrepSpec(t *testing.T, elfPath string) *ebpf.CollectionSpec {
 		mspec.Pinning = ebpf.PinNone
 	}
 
-	// Detect program type mismatches
 	var progTestType ebpf.ProgramType
-	for _, prog := range spec.Programs {
+	for progName, prog := range spec.Programs {
+		switch prog.Type {
+		case ebpf.XDP, ebpf.SchedACT, ebpf.SchedCLS:
+		case ebpf.UnspecifiedProgram:
```
Comment (joestringer) [inline test/bpf_tests/bpf_test.go:281]: What does `ebpf.UnspecifiedProgram` match? :thinking:

Comment (dylandreimerink) [reply test/bpf_tests/bpf_test.go:281]: Actually most programs in cilium since we tend to no start our ELF section names with `SEC("tc/` or `SEC("xdp/` so the loader has no clue what program types its dealing with. All of the tests have the mandatory program types as part of the declaration which we then use to infer the rest of the program types.
