### PR TITLE
test: Mend gingko-ext

### LINKED ISSUE #11497: GKE: [Fail] K8sServicesTest Checks ClusterIP Connectivity [It] Checks service accessing itself (hairpin flow): timed out waiting for pods with filter -l zgroup=testapp to be ready
```
K8sServicesTest Checks ClusterIP Connectivity 
  Checks service accessing itself (hairpin flow)
  /Users/ilya/Code/cilium/test/ginkgo-ext/scopes.go:471
15:57:48 STEP: Running BeforeEach block for Checks ClusterIP Connectivity
FAIL: Expected
    <*errors.errorString | 0xc0004ee870>: {
        s: "timed out waiting for pods with filter -l zgroup=testapp to be ready: 4m0s timeout expired",
    }
to be nil
```

Here's what's happening:
```
  Type     Reason                  Age                   From                                                          Message
  ----     ------                  ----                  ----                                                          -------
  Normal   Scheduled               13m                   default-scheduler                                             Successfully assigned default/app1-9cd98d48d-5pp24 to gke-ilya-test-cluste-ilya-test-cluste-2cc30d4b-cbtp
  Warning  FailedCreatePodSandBox  13m                   kubelet, gke-ilya-test-cluste-ilya-test-cluste-2cc30d4b-cbtp  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "bc435d66216c3c09a95060563186b2fe3f95b61290bb23314f9ac8a9c2c8c0a4" network for pod "app1-9cd98d48d-5pp24": NetworkPlugin cni failed to set up pod "app1-9cd98d48d-5pp24_default" network: failed to find plugin "cilium-cni" in path [/home/kubernetes/bin], failed to clean up sandbox container "bc435d66216c3c09a95060563186b2fe3f95b61290bb23314f9ac8a9c2c8c0a4" network for pod "app1-9cd98d48d-5pp24": NetworkPlugin cni failed to teardown pod "app1-9cd98d48d-5pp24_default" network: failed to find plugin "cilium-cni" in path [/home/kubernetes/bin]]
  Normal   SandboxChanged          3m21s (x48 over 13m)  kubelet, gke-ilya-test-cluste-ilya-test-cluste-2cc30d4b-cbtp  Pod sandbox changed, it will be killed and re-created.

```

<details>

```
$ kubectl describe pods                     
Name:           app1-9cd98d48d-5pp24
Namespace:      default
Priority:       0
Node:           gke-ilya-test-cluste-ilya-test-cluste-2cc30d4b-cbtp/10.128.0.10
Start Time:     Tue, 12 May 2020 15:57:50 +0100
Labels:         id=app1
                pod-template-hash=9cd98d48d
                zgroup=testapp
Annotations:    kubernetes.io/limit-ranger: LimitRanger plugin set: cpu request for container web; cpu request for container udp
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/app1-9cd98d48d
Containers:
  web:
    Container ID:   
    Image:          docker.io/cilium/demo-httpd:latest
    Image ID:       
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:        100m
    Readiness:    http-get http://:80/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from app1-account-token-bjrtn (ro)
  udp:
    Container ID:   
    Image:          docker.io/cilium/echoserver-udp:v2020.01.30
    Image ID:       
    Port:           69/UDP
    Host Port:      0/UDP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:        100m
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from app1-account-token-bjrtn (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  app1-account-token-bjrtn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  app1-account-token-bjrtn
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  cilium.io/ci-node=k8s1
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                   From                                                          Message
  ----     ------                  ----                  ----                                                          -------
  Normal   Scheduled               13m                   default-scheduler                                             Successfully assigned default/app1-9cd98d48d-5pp24 to gke-ilya-test-cluste-ilya-test-cluste-2cc30d4b-cbtp
  Warning  FailedCreatePodSandBox  13m                   kubelet, gke-ilya-test-cluste-ilya-test-cluste-2cc30d4b-cbtp  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "bc435d66216c3c09a95060563186b2fe3f95b61290bb23314f9ac8a9c2c8c0a4" network for pod "app1-9cd98d48d-5pp24": NetworkPlugin cni failed to set up pod "app1-9cd98d48d-5pp24_default" network: failed to find plugin "cilium-cni" in path [/home/kubernetes/bin], failed to clean up sandbox container "bc435d66216c3c09a95060563186b2fe3f95b61290bb23314f9ac8a9c2c8c0a4" network for pod "app1-9cd98d48d-5pp24": NetworkPlugin cni failed to teardown pod "app1-9cd98d48d-5pp24_default" network: failed to find plugin "cilium-cni" in path [/home/kubernetes/bin]]
  Normal   SandboxChanged          3m21s (x48 over 13m)  kubelet, gke-ilya-test-cluste-ilya-test-cluste-2cc30d4b-cbtp  Pod sandbox changed, it will be killed and re-created.


Name:           app1-9cd98d48d-lzbs6
Namespace:      default
Priority:       0
Node:           gke-ilya-test-cluste-ilya-test-cluste-2cc30d4b-cbtp/10.128.0.10
Start Time:     Tue, 12 May 2020 15:57:50 +0100
Labels:         id=app1
                pod-template-hash=9cd98d48d
                zgroup=testapp
Annotations:    kubernetes.io/limit-ranger: LimitRanger plugin set: cpu request for container web; cpu request for container udp
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/app1-9cd98d48d
Containers:
  web:
    Container ID:   
    Image:          docker.io/cilium/demo-httpd:latest
    Image ID:       
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:        100m
    Readiness:    http-get http://:80/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from app1-account-token-bjrtn (ro)
  udp:
    Container ID:   
    Image:          docker.io/cilium/echoserver-udp:v2020.01.30
    Image ID:       
    Port:           69/UDP
    Host Port:      0/UDP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:        100m
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from app1-account-token-bjrtn (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  app1-account-token-bjrtn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  app1-account-token-bjrtn
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  cilium.io/ci-node=k8s1
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                   From                                                          Message
  ----     ------                  ----                  ----                                                          -------
  Normal   Scheduled               13m                   default-scheduler                                             Successfully assigned default/app1-9cd98d48d-lzbs6 to gke-ilya-test-cluste-ilya-test-cluste-2cc30d4b-cbtp
  Warning  FailedCreatePodSandBox  13m                   kubelet, gke-ilya-test-cluste-ilya-test-cluste-2cc30d4b-cbtp  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "d81028d17cfc78ad630fc3e535c04099d7ede1a3ed549b05fc26e4a3a56d019d" network for pod "app1-9cd98d48d-lzbs6": NetworkPlugin cni failed to set up pod "app1-9cd98d48d-lzbs6_default" network: failed to find plugin "cilium-cni" in path [/home/kubernetes/bin], failed to clean up sandbox container "d81028d17cfc78ad630fc3e535c04099d7ede1a3ed549b05fc26e4a3a56d019d" network for pod "app1-9cd98d48d-lzbs6": NetworkPlugin cni failed to teardown pod "app1-9cd98d48d-lzbs6_default" network: failed to find plugin "cilium-cni" in path [/home/kubernetes/bin]]
  Normal   SandboxChanged          3m29s (x47 over 13m)  kubelet, gke-ilya-test-cluste-ilya-test-cluste-2cc30d4b-cbtp  Pod sandbox changed, it will be killed and re-created.


Name:           app2-b58dc9b5c-hfkg5
Namespace:      default
Priority:       0
Node:           gke-ilya-test-cluste-ilya-test-cluste-2cc30d4b-cbtp/10.128.0.10
Start Time:     Tue, 12 May 2020 15:57:51 +0100
Labels:         appSecond=true
                id=app2
                pod-template-hash=b58dc9b5c
                zgroup=testapp
Annotations:    kubernetes.io/limit-ranger: LimitRanger plugin set: cpu request for container app-frontend
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/app2-b58dc9b5c
Containers:
  app-frontend:
    Container ID:  
    Image:         docker.io/cilium/demo-client:latest
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      sleep
    Args:
      1000h
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:        100m
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from app2-account-token-k9zb2 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  app2-account-token-k9zb2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  app2-account-token-k9zb2
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  cilium.io/ci-node=k8s1
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                   From                                                          Message
  ----     ------                  ----                  ----                                                          -------
  Normal   Scheduled               13m                   default-scheduler                                             Successfully assigned default/app2-b58dc9b5c-hfkg5 to gke-ilya-test-cluste-ilya-test-cluste-2cc30d4b-cbtp
  Warning  FailedCreatePodSandBox  13m                   kubelet, gke-ilya-test-cluste-ilya-test-cluste-2cc30d4b-cbtp  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "714c344d50ba1fb5d26059dec35cccb2fdd2b46dcca90f5de9aad2703b235202" network for pod "app2-b58dc9b5c-hfkg5": NetworkPlugin cni failed to set up pod "app2-b58dc9b5c-hfkg5_default" network: failed to find plugin "cilium-cni" in path [/home/kubernetes/bin], failed to clean up sandbox container "714c344d50ba1fb5d26059dec35cccb2fdd2b46dcca90f5de9aad2703b235202" network for pod "app2-b58dc9b5c-hfkg5": NetworkPlugin cni failed to teardown pod "app2-b58dc9b5c-hfkg5_default" network: failed to find plugin "cilium-cni" in path [/home/kubernetes/bin]]
  Normal   SandboxChanged          3m23s (x48 over 13m)  kubelet, gke-ilya-test-cluste-ilya-test-cluste-2cc30d4b-cbtp  Pod sandbox changed, it will be killed and re-created.


Name:           app3-6cc4675d54-dq9l8
Namespace:      default
Priority:       0
Node:           gke-ilya-test-cluste-ilya-test-cluste-2cc30d4b-cbtp/10.128.0.10
Start Time:     Tue, 12 May 2020 15:57:51 +0100
Labels:         id=app3
                pod-template-hash=6cc4675d54
                zgroup=testapp
Annotations:    kubernetes.io/limit-ranger: LimitRanger plugin set: cpu request for container app-frontend
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/app3-6cc4675d54
Containers:
  app-frontend:
    Container ID:  
    Image:         docker.io/cilium/demo-client:latest
    Image ID:      
    Port:          80/TCP
    Host Port:     0/TCP
    Command:
      sleep
    Args:
      1000h
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:        100m
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-zhkdv (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-zhkdv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-zhkdv
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  cilium.io/ci-node=k8s1
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                   From                                                          Message
  ----     ------                  ----                  ----                                                          -------
  Normal   Scheduled               13m                   default-scheduler                                             Successfully assigned default/app3-6cc4675d54-dq9l8 to gke-ilya-test-cluste-ilya-test-cluste-2cc30d4b-cbtp
  Warning  FailedCreatePodSandBox  13m                   kubelet, gke-ilya-test-cluste-ilya-test-cluste-2cc30d4b-cbtp  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "2af4b847d5e570621f730112c7fa11e3994a2a2204665545fb95923db2443e64" network for pod "app3-6cc4675d54-dq9l8": NetworkPlugin cni failed to set up pod "app3-6cc4675d54-dq9l8_default" network: failed to find plugin "cilium-cni" in path [/home/kubernetes/bin], failed to clean up sandbox container "2af4b847d5e570621f730112c7fa11e3994a2a2204665545fb95923db2443e64" network for pod "app3-6cc4675d54-dq9l8": NetworkPlugin cni failed to teardown pod "app3-6cc4675d54-dq9l8_default" network: failed to find plugin "cilium-cni" in path [/home/kubernetes/bin]]
  Normal   SandboxChanged          3m19s (x48 over 13m)  kubelet, gke-ilya-test-cluste-ilya-test-cluste-2cc30d4b-cbtp  Pod sandbox changed, it will be killed and re-created.


Name:           echo-55c967bd48-qsd7h
Namespace:      default
Priority:       0
Node:           gke-ilya-test-cluste-ilya-test-cluste-2cc30d4b-vszz/10.128.0.9
Start Time:     Tue, 12 May 2020 15:57:52 +0100
Labels:         name=echo
                pod-template-hash=55c967bd48
Annotations:    kubernetes.io/limit-ranger: LimitRanger plugin set: cpu request for container echo-container; cpu request for container echo-container-udp
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/echo-55c967bd48
Containers:
  echo-container:
    Container ID:   
    Image:          docker.io/cilium/json-mock:1.2
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:        100m
    Liveness:     exec [curl -sS -o /dev/null localhost] delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:    exec [curl -sS -o /dev/null localhost] delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-zhkdv (ro)
  echo-container-udp:
    Container ID:   
    Image:          docker.io/cilium/echoserver-udp:v2020.01.30
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:        100m
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-zhkdv (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-zhkdv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-zhkdv
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                   From                                                          Message
  ----     ------                  ----                  ----                                                          -------
  Normal   Scheduled               13m                   default-scheduler                                             Successfully assigned default/echo-55c967bd48-qsd7h to gke-ilya-test-cluste-ilya-test-cluste-2cc30d4b-vszz
  Warning  FailedCreatePodSandBox  13m                   kubelet, gke-ilya-test-cluste-ilya-test-cluste-2cc30d4b-vszz  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "90e47564569c452433463776ce0b095d815354fbe1c502cdb65bfd1729a79ce9" network for pod "echo-55c967bd48-qsd7h": NetworkPlugin cni failed to set up pod "echo-55c967bd48-qsd7h_default" network: failed to find plugin "cilium-cni" in path [/home/kubernetes/bin], failed to clean up sandbox container "90e47564569c452433463776ce0b095d815354fbe1c502cdb65bfd1729a79ce9" network for pod "echo-55c967bd48-qsd7h": NetworkPlugin cni failed to teardown pod "echo-55c967bd48-qsd7h_default" network: failed to find plugin "cilium-cni" in path [/home/kubernetes/bin]]
  Normal   SandboxChanged          3m22s (x48 over 13m)  kubelet, gke-ilya-test-cluste-ilya-test-cluste-2cc30d4b-vszz  Pod sandbox changed, it will be killed and re-created.
```
</details>

### PR DESCRIPTION
**Pull request by errordeveloper**
- fix source of flakieness in scope counter - shouldn't set global counter
  inside of recursive function (`calculateCounters`) and set it explicitly
  upon return; this fixes #11497 and potentially other flakes where the
  `AfterAll` gets misscheduled and causes premature deletions
- add mutex around the scope counter for extra safety (doesn't appear to
  aid the original issue, but signifies the brittle nature of the counter
  variable to a reader)
- remove unnecessary closure of `cs` variable that was also hard to read
  due to shadowing of `after` function inside the loop

### CODE REVIEW

**Comment by errordeveloper** [comment]
test-gke

**Comment by errordeveloper** [comment]
Just to clarify, while testing new GitOps-managed clusters in GKE, I've noticed a few flakes re-occurring very frequently. Once looking into one of them, I set `-focus="Checks ClusterIP Connectivity" -cilium.testScope=K8s" and was getting consistent failures (I captured my findings in #11497).
After looking into `scope.go` aside from it being convoluted in general, I managed to spot a few things which this PR addresses.
Having ran same subset of test over and over I've not been able to reproduce failures any more, but reverting back to master brings failures back.

**Review by michi-covalent — APPROVED** [review]
let's roll

File: test/ginkgo-ext/scopes.go [hunk 1]
```diff
@@ -453,10 +455,13 @@ func wrapNilContextFunc(fn func(string, func()) bool) func(string, func()) bool
 // execute AfterAll. This is tracked via scope.focusedTests and .normalTests.
 // This function is similar to wrapMeasureFunc.
 func wrapItFunc(fn func(string, interface{}, ...float64) bool, focused bool) func(string, interface{}, ...float64) bool {
-	if !countersInitialized {
-		countersInitialized = true
+	if rootScope.counter == -1 {
```
Comment (nebril) [inline test/ginkgo-ext/scopes.go]: Shouldn't these also be protected by mutex?

File: test/ginkgo-ext/scopes.go [hunk 2]
```diff
@@ -476,10 +481,13 @@ func wrapItFunc(fn func(string, interface{}, ...float64) bool, focused bool) fun
 // execute AfterAll. This is tracked via scope.focusedTests and .normalTests.
 // This function is similar to wrapItFunc.
 func wrapMeasureFunc(fn func(text string, body interface{}, samples int) bool, focused bool) func(text string, body interface{}, samples int) bool {
-	if !countersInitialized {
-		countersInitialized = true
+	if rootScope.counter == -1 {
```
Comment (nebril) [inline test/ginkgo-ext/scopes.go]: Same as above - should this be protected?

**Review by nebril — CHANGES_REQUESTED** [review]
I don't understand why this helps, but if it does, let's ship it. Two change requests in comments.

**Comment by errordeveloper** [comment]
> I don't understand why this helps, but if it does, let's ship it. Two change requests in comments.

`calculateCounters` is a recursive function, it was setting a global variable before one out of 3 `return` statements. Global variables are a common source of bugs, setting one inside a recursive functions is definitely not a good idea.

File: test/ginkgo-ext/scopes.go (hunk 1 above)
Comment (errordeveloper) [reply test/ginkgo-ext/scopes.go]: I don't think it's necessary, and the other mutex is not strictly necessary either, but as I stated in the commit message - it's to highlight the brittle nature of this hacky code. So I'll put the counter behind a method.

**Comment by errordeveloper** [comment]
Some unrelated failures:
```
16:20:58  • Failure in Spec Setup (BeforeEach) [443.919 seconds]
16:20:58  K8sPolicyTest
16:20:58  /home/jenkins/workspace/Cilium-PR-K8s-GKE@4/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:438
16:20:58    Basic Test [BeforeEach]
16:20:58    /home/jenkins/workspace/Cilium-PR-K8s-GKE@4/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:438
16:20:58      checks all kind of Kubernetes policies
16:20:58      /home/jenkins/workspace/Cilium-PR-K8s-GKE@4/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:476
16:20:58  
16:20:58      cilium pre-flight checks failed
[2020-05-15T15:20:58.684Z]     Expected
[2020-05-15T15:20:58.684Z]         <*errors.errorString | 0xc00078b930>: {
[2020-05-15T15:20:58.684Z]             s: "Cilium validation failed: 4m0s timeout expired: Last polled error: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-67lq7': Exitcode: 255 \nStdout:\n \t \nStderr:\n \t Error: Cannot get status/probe: Put \"http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe\": context deadline exceeded\n\t \n\t command terminated with exit code 255\n\t \n",
[2020-05-15T15:20:58.684Z]         }
[2020-05-15T15:20:58.684Z]     to be nil
```

**Comment by errordeveloper** [comment]
test-gke

**Comment by errordeveloper** [comment]
@nebril can you please take a look at Jenkins, I'm not sure what actually failed there...

**Comment by nebril** [comment]
@errordeveloper 
```
12:12:43  ginkgo-ext/scopes.go:134:31: undefined: val
12:12:43  ginkgo-ext/scopes.go:137:20: undefined: val
```

File: test/ginkgo-ext/scopes.go [hunk 3]
```diff
@@ -116,6 +119,33 @@ func init() {
...
+	return (s.counter == -1)
+}
+
+func (s *scope) isZero() bool {
+	s.mutex.Lock()
+	defer s.mutex.Unlock()
+	return (s.counter == 0)
+}
+
+func (s *scope) setSafely(int val) {
```
Comment (nebril) [inline test/ginkgo-ext/scopes.go]: `s/int val/val int`

**Review by nebril — CHANGES_REQUESTED** [review]
ci failing because of bad func argument

**Comment by errordeveloper** [comment]
> ci failing because of bad func argument

Thanks! That was buried very deeply. Fortunately we have #11528, which should make this and more nuanced problems much quicker to recognise.

**Comment by errordeveloper** [comment]
test-gke

**Review by nebril — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Comment by nebril** [comment]
retest-4.9

**Comment by nebril** [comment]
retest-net-next

**Comment by nebril** [comment]
retest-4.19

**Comment by errordeveloper** [comment]
Node manager unit tests are failing on Travis:
```
FAIL: node_manager_test.go:563: ENISuite.TestNodeManagerManyNodes
node_manager_test.go:602:
    c.Errorf("Node %s allocation mismatch. expected: %d allocated: %d", s.name, minAllocate, node.Stats().AvailableIPs)
... Error: Node node30 allocation mismatch. expected: 10 allocated: 18
node_manager_test.go:602:
    c.Errorf("Node %s allocation mismatch. expected: %d allocated: %d", s.name, minAllocate, node.Stats().AvailableIPs)
... Error: Node node42 allocation mismatch. expected: 10 allocated: 18
node_manager_test.go:617:
    c.Assert(metricsapi.AllocatedIPs("available"), check.Equals, numNodes*minAllocate)
... obtained int = 1016
... expected int = 1000
```

**Comment by tklauser** [comment]
Jenkins failures look legitimate:

https://jenkins.cilium.io/job/Cilium-PR-K8s-oldest-net-next/226/
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Kernel/1534/
https://jenkins.cilium.io/job/Cilium-PR-K8s-newest-kernel-4.9/207/

**Comment by errordeveloper** [comment]
@tklauser thanks, I will rebase and address those error :)

File: test/ginkgo-ext/scopes.go [hunk 4]
```diff
@@ -116,6 +119,33 @@ func init() {
...
+	defer s.mutex.Unlock()
+	s.counter = int32(val)
+}
+
+func (s *scope) decrementSafely() {
+	s.mutex.Lock()
+	defer s.mutex.Unlock()
+	s.counter--
+	if s.counter < 0 {
+		panic("unexpected negative scope counter value")
```
Comment (errordeveloper) [inline test/ginkgo-ext/scopes.go]: @nebril so from the Jenkins logs it looks we do actually hit this, and my understanding was that code was assuming it doesn't actually go below zero - WDYT?

**Comment by errordeveloper** [comment]
So it looks like we maybe seeing more of unexpected behaviour of scope counters, waiting to see if #11534 fixes it.

**Comment by errordeveloper** [comment]
test-me-please

File: test/ginkgo-ext/scopes.go (hunk 4 above)
Comment (errordeveloper) [reply test/ginkgo-ext/scopes.go]: I added the actual value here also, so we can see if it's `-1` or `-99` :)

**Comment by errordeveloper** [comment]
So here is what it looks like:
```
  [2020-05-20T19:27:12.233Z] [91m[1m•! Panic in Spec Teardown (AfterEach) [111.779 seconds][0m
  [2020-05-20T19:27:12.233Z] EntireTestsuite K8sConformance
  [2020-05-20T19:27:12.233Z] [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:27:12.233Z]   [91m[1mEntireTestsuite K8sConformance Portmap Chaining [AfterEach][0m
  [2020-05-20T19:27:12.233Z]   [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:27:12.233Z]     EntireTestsuite K8sConformance Portmap Chaining Check connectivity-check compliance with portmap chaining
  [2020-05-20T19:27:12.233Z]     [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:501[0m
  [2020-05-20T19:27:12.233Z] 
  [2020-05-20T19:27:12.233Z]     [91m[1mTest Panicked[0m
  [2020-05-20T19:27:12.233Z]     [91munexpected negative scope counter value: -1[0m
  [2020-05-20T19:27:12.233Z]     /home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:145
--
  [2020-05-20T19:28:42.023Z] [91m[1m•! Panic in Spec Teardown (AfterEach) [89.333 seconds][0m
  [2020-05-20T19:28:42.023Z] EntireTestsuite K8sDatapathConfig
  [2020-05-20T19:28:42.023Z] [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:28:42.023Z]   [91m[1mEntireTestsuite K8sDatapathConfig MonitorAggregation [AfterEach][0m
  [2020-05-20T19:28:42.023Z]   [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:28:42.023Z]     EntireTestsuite K8sDatapathConfig MonitorAggregation Checks that monitor aggregation restricts notifications
  [2020-05-20T19:28:42.023Z]     [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:501[0m
  [2020-05-20T19:28:42.023Z] 
  [2020-05-20T19:28:42.023Z]     [91m[1mTest Panicked[0m
  [2020-05-20T19:28:42.023Z]     [91munexpected negative scope counter value: -1[0m
  [2020-05-20T19:28:42.023Z]     /home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:145
--
  [2020-05-20T19:29:31.442Z] [91m[1m•! Panic in Spec Teardown (AfterEach) [49.240 seconds][0m
  [2020-05-20T19:29:31.442Z] EntireTestsuite K8sDatapathConfig
  [2020-05-20T19:29:31.442Z] [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:29:31.442Z]   [91m[1mEntireTestsuite K8sDatapathConfig MonitorAggregation [AfterEach][0m
  [2020-05-20T19:29:31.442Z]   [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:29:31.442Z]     EntireTestsuite K8sDatapathConfig MonitorAggregation Checks that monitor aggregation flags send notifications
  [2020-05-20T19:29:31.442Z]     [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:501[0m
  [2020-05-20T19:29:31.442Z] 
  [2020-05-20T19:29:31.442Z]     [91m[1mTest Panicked[0m
  [2020-05-20T19:29:31.442Z]     [91munexpected negative scope counter value: -2[0m
  [2020-05-20T19:29:31.442Z]     /home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:145
--
  [2020-05-20T19:30:32.388Z] [91m[1m•! Panic in Spec Teardown (AfterEach) [61.832 seconds][0m
  [2020-05-20T19:30:32.388Z] EntireTestsuite K8sDatapathConfig
  [2020-05-20T19:30:32.388Z] [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:30:32.388Z]   [91m[1mEntireTestsuite K8sDatapathConfig Encapsulation [AfterEach][0m
  [2020-05-20T19:30:32.388Z]   [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:30:32.388Z]     EntireTestsuite K8sDatapathConfig Encapsulation Check connectivity with sockops and VXLAN encapsulation
  [2020-05-20T19:30:32.388Z]     [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:501[0m
  [2020-05-20T19:30:32.388Z] 
  [2020-05-20T19:30:32.388Z]     [91m[1mTest Panicked[0m
  [2020-05-20T19:30:32.388Z]     [91munexpected negative scope counter value: -4[0m
  [2020-05-20T19:30:32.388Z]     /home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:145
--
  [2020-05-20T19:31:14.175Z] [91m[1m•! Panic in Spec Teardown (AfterEach) [41.714 seconds][0m
  [2020-05-20T19:31:14.175Z] EntireTestsuite K8sDatapathConfig
  [2020-05-20T19:31:14.175Z] [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:31:14.175Z]   [91m[1mEntireTestsuite K8sDatapathConfig Encapsulation [AfterEach][0m
  [2020-05-20T19:31:14.175Z]   [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:31:14.175Z]     EntireTestsuite K8sDatapathConfig Encapsulation Check connectivity with VXLAN encapsulation
  [2020-05-20T19:31:14.175Z]     [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:501[0m
  [2020-05-20T19:31:14.175Z] 
  [2020-05-20T19:31:14.175Z]     [91m[1mTest Panicked[0m
  [2020-05-20T19:31:14.175Z]     [91munexpected negative scope counter value: -5[0m
  [2020-05-20T19:31:14.175Z]     /home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:145
--
  [2020-05-20T19:32:00.758Z] [91m[1m•! Panic in Spec Teardown (AfterEach) [46.747 seconds][0m
  [2020-05-20T19:32:00.758Z] EntireTestsuite K8sDatapathConfig
  [2020-05-20T19:32:00.758Z] [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:32:00.758Z]   [91m[1mEntireTestsuite K8sDatapathConfig Encapsulation [AfterEach][0m
  [2020-05-20T19:32:00.758Z]   [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:32:00.758Z]     EntireTestsuite K8sDatapathConfig Encapsulation Check connectivity with Geneve encapsulation
  [2020-05-20T19:32:00.758Z]     [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:501[0m
  [2020-05-20T19:32:00.758Z] 
  [2020-05-20T19:32:00.758Z]     [91m[1mTest Panicked[0m
  [2020-05-20T19:32:00.758Z]     [91munexpected negative scope counter value: -6[0m
  [2020-05-20T19:32:00.758Z]     /home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:145
--
  [2020-05-20T19:32:42.876Z] [91m[1m•! Panic in Spec Teardown (AfterEach) [42.146 seconds][0m
  [2020-05-20T19:32:42.876Z] EntireTestsuite K8sDatapathConfig
  [2020-05-20T19:32:42.876Z] [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:32:42.876Z]   [91m[1mEntireTestsuite K8sDatapathConfig AutoDirectNodeRoutes [AfterEach][0m
  [2020-05-20T19:32:42.876Z]   [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:32:42.876Z]     EntireTestsuite K8sDatapathConfig AutoDirectNodeRoutes Check connectivity with automatic direct nodes routes
  [2020-05-20T19:32:42.876Z]     [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:501[0m
  [2020-05-20T19:32:42.876Z] 
  [2020-05-20T19:32:42.876Z]     [91m[1mTest Panicked[0m
  [2020-05-20T19:32:42.876Z]     [91munexpected negative scope counter value: -10[0m
  [2020-05-20T19:32:42.876Z]     /home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:145
--
  [2020-05-20T19:34:35.139Z] [91m[1m•! Panic in Spec Teardown (AfterEach) [52.687 seconds][0m
  [2020-05-20T19:34:35.139Z] EntireTestsuite K8sDatapathConfig
  [2020-05-20T19:34:35.139Z] [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:34:35.139Z]   [91m[1mEntireTestsuite K8sDatapathConfig AutoDirectNodeRoutes [AfterEach][0m
  [2020-05-20T19:34:35.139Z]   [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:34:35.139Z]     EntireTestsuite K8sDatapathConfig AutoDirectNodeRoutes Check connectivity with sockops and direct routing
  [2020-05-20T19:34:35.139Z]     [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:501[0m
  [2020-05-20T19:34:35.139Z] 
  [2020-05-20T19:34:35.139Z]     [91m[1mTest Panicked[0m
  [2020-05-20T19:34:35.139Z]     [91munexpected negative scope counter value: -12[0m
  [2020-05-20T19:34:35.139Z]     /home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:145
--
  [2020-05-20T19:35:30.401Z] [91m[1m•! Panic in Spec Teardown (AfterEach) [55.420 seconds][0m
  [2020-05-20T19:35:30.401Z] EntireTestsuite K8sDatapathConfig
  [2020-05-20T19:35:30.401Z] [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:35:30.401Z]   [91m[1mEntireTestsuite K8sDatapathConfig Transparent encryption DirectRouting [AfterEach][0m
  [2020-05-20T19:35:30.401Z]   [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:35:30.401Z]     EntireTestsuite K8sDatapathConfig Transparent encryption DirectRouting Check connectivity with transparent encryption and direct routing
  [2020-05-20T19:35:30.401Z]     [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:501[0m
  [2020-05-20T19:35:30.401Z] 
  [2020-05-20T19:35:30.401Z]     [91m[1mTest Panicked[0m
  [2020-05-20T19:35:30.401Z]     [91munexpected negative scope counter value: -22[0m
  [2020-05-20T19:35:30.401Z]     /home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:145
--
  [2020-05-20T19:36:02.961Z] [91m[1m•! Panic in Spec Teardown (AfterEach) [32.643 seconds][0m
  [2020-05-20T19:36:02.961Z] EntireTestsuite K8sDatapathConfig
  [2020-05-20T19:36:02.961Z] [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:36:02.961Z]   [91m[1mEntireTestsuite K8sDatapathConfig IPv4Only [AfterEach][0m
  [2020-05-20T19:36:02.961Z]   [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:36:02.961Z]     EntireTestsuite K8sDatapathConfig IPv4Only Check connectivity with IPv6 disabled
  [2020-05-20T19:36:02.961Z]     [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:501[0m
  [2020-05-20T19:36:02.961Z] 
  [2020-05-20T19:36:02.961Z]     [91m[1mTest Panicked[0m
  [2020-05-20T19:36:02.961Z]     [91munexpected negative scope counter value: -23[0m
  [2020-05-20T19:36:02.961Z]     /home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:145
--
  [2020-05-20T19:36:55.675Z] [91m[1m•! Panic in Spec Teardown (AfterEach) [52.540 seconds][0m
  [2020-05-20T19:36:55.675Z] EntireTestsuite K8sDatapathConfig
  [2020-05-20T19:36:55.675Z] [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:36:55.675Z]   [91m[1mEntireTestsuite K8sDatapathConfig Etcd [AfterEach][0m
  [2020-05-20T19:36:55.675Z]   [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:36:55.675Z]     EntireTestsuite K8sDatapathConfig Etcd Check connectivity
  [2020-05-20T19:36:55.675Z]     [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:501[0m
  [2020-05-20T19:36:55.675Z] 
  [2020-05-20T19:36:55.675Z]     [91m[1mTest Panicked[0m
  [2020-05-20T19:36:55.675Z]     [91munexpected negative scope counter value: -24[0m
  [2020-05-20T19:36:55.675Z]     /home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:145
--
  [2020-05-20T19:38:41.097Z] [91m[1m•! Panic in Spec Teardown (AfterEach) [104.845 seconds][0m
  [2020-05-20T19:38:41.097Z] EntireTestsuite K8sKafkaPolicyTest
  [2020-05-20T19:38:41.097Z] [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:38:41.097Z]   EntireTestsuite K8sKafkaPolicyTest Kafka Policy Tests
  [2020-05-20T19:38:41.097Z]   [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:38:41.097Z]     [91m[1mEntireTestsuite K8sKafkaPolicyTest Kafka Policy Tests KafkaPolicies [AfterEach][0m
  [2020-05-20T19:38:41.097Z]     [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:501[0m
  [2020-05-20T19:38:41.097Z] 
  [2020-05-20T19:38:41.097Z]     [91m[1mTest Panicked[0m
  [2020-05-20T19:38:41.097Z]     [91munexpected negative scope counter value: -1[0m
  [2020-05-20T19:38:41.097Z]     /home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:145
--
  [2020-05-20T19:40:45.613Z] [91m[1m•! Panic in Spec Teardown (AfterEach) [124.532 seconds][0m
  [2020-05-20T19:40:45.613Z] EntireTestsuite K8sFQDNTest
  [2020-05-20T19:40:45.613Z] [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:40:45.613Z]   [91m[1mEntireTestsuite K8sFQDNTest Restart Cilium validate that FQDN is still working [AfterEach][0m
  [2020-05-20T19:40:45.613Z]   [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:501[0m
  [2020-05-20T19:40:45.613Z] 
  [2020-05-20T19:40:45.613Z]   [91m[1mTest Panicked[0m
  [2020-05-20T19:40:45.613Z]   [91munexpected negative scope counter value: -1[0m
  [2020-05-20T19:40:45.613Z]   /home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:145
  [2020-05-20T19:40:45.613Z] 
  [2020-05-20T19:40:45.613Z]   [91mFull Stack Trace[0m
--
  [2020-05-20T19:40:57.844Z] [91m[1m•! Panic in Spec Teardown (AfterEach) [12.231 seconds][0m
  [2020-05-20T19:40:57.844Z] EntireTestsuite K8sFQDNTest
  [2020-05-20T19:40:57.844Z] [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:40:57.844Z]   [91m[1mEntireTestsuite K8sFQDNTest Validate that multiple specs are working correctly [AfterEach][0m
  [2020-05-20T19:40:57.844Z]   [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:501[0m
  [2020-05-20T19:40:57.844Z] 
  [2020-05-20T19:40:57.844Z]   [91m[1mTest Panicked[0m
  [2020-05-20T19:40:57.844Z]   [91munexpected negative scope counter value: -2[0m
  [2020-05-20T19:40:57.844Z]   /home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:145
  [2020-05-20T19:40:57.844Z] 
  [2020-05-20T19:40:57.844Z]   [91mFull Stack Trace[0m
--
  [2020-05-20T19:41:50.298Z] [91m[1m•! Panic in Spec Teardown (AfterEach) [53.227 seconds][0m
  [2020-05-20T19:41:50.298Z] EntireTestsuite K8sDemosTest
  [2020-05-20T19:41:50.298Z] [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:41:50.298Z]   [91m[1mEntireTestsuite K8sDemosTest Tests Star Wars Demo [AfterEach][0m
  [2020-05-20T19:41:50.298Z]   [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:501[0m
  [2020-05-20T19:41:50.298Z] 
  [2020-05-20T19:41:50.298Z]   [91m[1mTest Panicked[0m
  [2020-05-20T19:41:50.298Z]   [91munexpected negative scope counter value: -1[0m
  [2020-05-20T19:41:50.298Z]   /home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:145
  [2020-05-20T19:41:50.298Z] 
  [2020-05-20T19:41:50.298Z]   [91mFull Stack Trace[0m
--
  [2020-05-20T19:43:30.246Z] [91m[1m•! Panic in Spec Teardown (AfterEach) [58.117 seconds][0m
  [2020-05-20T19:43:30.246Z] EntireTestsuite K8sIdentity
  [2020-05-20T19:43:30.246Z] [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:43:30.246Z]   [91m[1mEntireTestsuite K8sIdentity Identity expiration [AfterEach][0m
  [2020-05-20T19:43:30.246Z]   [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:43:30.246Z]     EntireTestsuite K8sIdentity Identity expiration Expiration of CiliumIdentity
  [2020-05-20T19:43:30.246Z]     [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:501[0m
  [2020-05-20T19:43:30.246Z] 
  [2020-05-20T19:43:30.246Z]     [91m[1mTest Panicked[0m
  [2020-05-20T19:43:30.246Z]     [91munexpected negative scope counter value: -1[0m
  [2020-05-20T19:43:30.246Z]     /home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:145
--
  [2020-05-20T19:44:32.279Z] [91m[1m•! Panic in Spec Teardown (AfterEach) [62.595 seconds][0m
  [2020-05-20T19:44:32.279Z] EntireTestsuite K8sServicesTest
  [2020-05-20T19:44:32.280Z] [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:44:32.280Z]   EntireTestsuite K8sServicesTest Checks ClusterIP Connectivity
  [2020-05-20T19:44:32.280Z]   [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:44:32.280Z]     [91m[1mEntireTestsuite K8sServicesTest Checks ClusterIP Connectivity Checks service on same node [AfterEach][0m
  [2020-05-20T19:44:32.280Z]     [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:501[0m
  [2020-05-20T19:44:32.280Z] 
  [2020-05-20T19:44:32.280Z]     [91m[1mTest Panicked[0m
  [2020-05-20T19:44:32.280Z]     [91munexpected negative scope counter value: -1[0m
  [2020-05-20T19:44:32.280Z]     /home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:145
--
  [2020-05-20T19:44:32.910Z] [91m[1m•! Panic in Spec Teardown (AfterEach) [0.576 seconds][0m
  [2020-05-20T19:44:32.910Z] EntireTestsuite K8sServicesTest
  [2020-05-20T19:44:32.910Z] [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:44:32.910Z]   EntireTestsuite K8sServicesTest Checks ClusterIP Connectivity
  [2020-05-20T19:44:32.910Z]   [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:44:32.910Z]     [91m[1mEntireTestsuite K8sServicesTest Checks ClusterIP Connectivity Checks service accessing itself (hairpin flow) [AfterEach][0m
  [2020-05-20T19:44:32.910Z]     [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:501[0m
  [2020-05-20T19:44:32.910Z] 
  [2020-05-20T19:44:32.910Z]     [91m[1mTest Panicked[0m
  [2020-05-20T19:44:32.910Z]     [91munexpected negative scope counter value: -2[0m
  [2020-05-20T19:44:32.910Z]     /home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:145
--
  [2020-05-20T19:53:25.162Z] [91m[1m•! Panic in Spec Teardown (AfterEach) [40.063 seconds][0m
  [2020-05-20T19:53:25.162Z] EntireTestsuite K8sServicesTest
  [2020-05-20T19:53:25.162Z] [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:53:25.162Z]   EntireTestsuite K8sServicesTest Bookinfo Demo
  [2020-05-20T19:53:25.162Z]   [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:464[0m
  [2020-05-20T19:53:25.162Z]     [91m[1mEntireTestsuite K8sServicesTest Bookinfo Demo Tests bookinfo demo [AfterEach][0m
  [2020-05-20T19:53:25.162Z]     [90m/home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:501[0m
  [2020-05-20T19:53:25.162Z] 
  [2020-05-20T19:53:25.162Z]     [91m[1mTest Panicked[0m
  [2020-05-20T19:53:25.162Z]     [91munexpected negative scope counter value: -1[0m
  [2020-05-20T19:53:25.162Z]     /home/jenkins/workspace/Cilium-PR-K8s-newest-kernel-4.9/k8s-1.18-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:145
```
I'm gonna look at this code a bit more now and try to understand if I might have misunderstood whether the counter shouldn't get below zero...

File: test/ginkgo-ext/scopes.go [hunk 5]
```diff
@@ -344,14 +374,11 @@ func RunAfterEach(cs *scope) {
 	}
 
 	// Only run afterAll when all the counters are 0 and all afterEach are executed
```
Comment (errordeveloper) [inline test/ginkgo-ext/scopes.go:382]: This is the only part of the code the suggests anything about the bounds of this counter, and based on this I think this counter is definitely assumed to go from 0 to N (when N>0), and back to 0, and any negative values are therefore unexpected. It's possible that flakes where cause by this also, as this counter is just completely off.

File: test/ginkgo-ext/scopes.go [hunk 6]
```diff
@@ -538,7 +570,7 @@ func wrapTest(f interface{}) interface{} {
 func calculateCounters(s *scope, focusedOnly bool) (int, bool) {
```
Comment (errordeveloper) [inline test/ginkgo-ext/scopes.go:579]: I wish I could understand what is meant to happen, but right now I find it very difficult and I do have many too many doubts about what's going.

File: test/ginkgo-ext/scopes.go (hunk 5 above)
Comment (errordeveloper) [reply test/ginkgo-ext/scopes.go:382]: I've double-checked with @eloycoto and negative counts are defo unexpected.

**Comment by errordeveloper** [comment]
test-gke

**Comment by errordeveloper** [comment]
test-gke

**Comment by errordeveloper** [comment]
test-gke

**Comment by errordeveloper** [comment]
test-gke

File: test/ginkgo-ext/scopes.go (hunk 5 above)
Comment (errordeveloper) [reply test/ginkgo-ext/scopes.go:382]: Looks like the negative count was due to my changes here, as `+=` is being used, the initial `-1` gets added up over and over. The previous version was setting children scope counters  in inexplicit way, which is exactly the line that's been dropped in my changes.

File: test/ginkgo-ext/scopes.go [hunk 7]
```diff
@@ -564,7 +615,6 @@ func calculateCounters(s *scope, focusedOnly bool) (int, bool) {
 	if !focusedOnly && !haveFocused {
 		count += s.normalTests + normalChildren
 	}
-	s.counter = int32(count)
```
Comment (errordeveloper) [inline test/ginkgo-ext/scopes.go:567]: This line was setting child counter in inexplicit way.

File: test/ginkgo-ext/scopes.go [hunk 8]
```diff
@@ -538,21 +579,31 @@ func wrapTest(f interface{}) interface{} {
...
+	focusedChildren := 0
 	for _, child := range s.children {
 		if child.focused {
+			if !child.isUnset() {
+				panic("unexepcted redundant recursive call")
+			}
+			child.setSafely(0)
 			c, _ := calculateCounters(child, false)
+			child.setSafely(c)
 			focusedChildren += c
```
Comment (errordeveloper) [inline test/ginkgo-ext/scopes.go:591]: This another `+=`  line were causing negative values to grow.

**Comment by errordeveloper** [comment]
test-4.9

**Comment by errordeveloper** [comment]
@nebril can we merge this on the basis of `K8s-1.18-kernel-4.9` passing?

**Comment by errordeveloper** [comment]
@nebril thanks!
