### PR TITLE
clustermesh: fix remote service deletion on endpointslicesync

### LINKED ISSUE #32931: CI: Integration tests - Test_meshEndpointSlice_Reconcile
## CI failure

```
/tmp/go-stress-20240606T093130-3062731158
I0606 09:32:49.496892  156987 endpointslice_controller.go:296] "Starting endpoint slice controller"
I0606 09:32:49.496976  156987 shared_informer.go:313] Waiting for caches to sync for endpoint_slice
I0606 09:32:49.497011  156987 shared_informer.go:320] Caches are synced for endpoint_slice
--- FAIL: Test_meshEndpointSlice_Reconcile (0.31s)
    logger.go:257: time=2024-06-06T09:32:49.294+02:00 level=INFO source=/home/marco/Documents/isovalent/cilium/vendor/github.com/cilium/hive/hive.go:337 msg=Starting
    logger.go:257: time=2024-06-06T09:32:49.294+02:00 level=INFO source=/home/marco/Documents/isovalent/cilium/vendor/github.com/cilium/hive/hive.go:341 msg=Started duration=95.581µs
    --- FAIL: Test_meshEndpointSlice_Reconcile/Create_global_service_then_service (0.01s)
        endpointslice_test.go:189: 
                Error Trace:    /home/marco/Documents/isovalent/cilium/pkg/clustermesh/endpointslicesync/endpointslice_test.go:189
                Error:          Not equal: 
                                expected: 1
                                actual  : 0
                Test:           Test_meshEndpointSlice_Reconcile/Create_global_service_then_service
    logger.go:257: time=2024-06-06T09:32:49.590+02:00 level=INFO source=/home/marco/Documents/isovalent/cilium/vendor/github.com/cilium/hive/hive.go:353 msg=Stopping
    logger.go:257: time=2024-06-06T09:32:49.590+02:00 level=INFO source=/home/marco/Documents/isovalent/cilium/pkg/hive/health/provider.go:62 msg="health.job-module-status-metrics (rev=2)" module=health
FAIL
```

I managed to reproduce it locally (although it seems fairly rare) with:

```
$ go install golang.org/x/tools/cmd/stress@latest
$ go test -c -race ./pkg/clustermesh/endpointslicesync
$ stress -p 250 ./endpointslicesync.test
```

/cc @MrFreezeex

### PR DESCRIPTION
**Pull request by MrFreezeex**
This fixes remote service deletion in endpointslicesync (see second commit).

And it also fixes tests by using EventuallyWithT instead of waiting for the controller queue to be empty. The queue being empty does not signify that the reconciliation is done as the controller pops elements when the reconciliation starts and not when it ends.

cc @giorio94 
Fixes #32931

### CODE REVIEW

File: pkg/clustermesh/endpointslicesync/endpointslice_test.go [hunk 1]
```diff
@@ -156,22 +138,21 @@ func Test_meshEndpointSlice_Reconcile(t *testing.T) {
...
+		require.EventuallyWithT(t, func(c *assert.CollectT) {
+			epList, err := getEndpointSlice(&fakeClient, svcName)
+			assert.NoError(c, err)
+			assert.Equal(c, 1, len(epList.Items))
+			assert.Equal(c, map[string]string{
+				discovery.LabelServiceName:        svcName,
+				discovery.LabelManagedBy:          utils.EndpointSliceMeshControllerName,
+				mcsapiv1alpha1.LabelSourceCluster: remoteClusterName,
+				corev1.IsHeadlessService:          "",
+			}, epList.Items[0].Labels)
```
Comment (giorio94) [inline pkg/clustermesh/endpointslicesync/endpointslice_test.go]: This does not work as intended, because the function does not exit if the above assertion fails, hence causing an index out-of-range panic here. You should either check the return value of `assert.Equal`, or move the subsequent assertions after that `EventuallyWithT` completes.

File: pkg/clustermesh/endpointslicesync/endpointslice_test.go [hunk 2]
```diff
@@ -201,24 +181,22 @@ func Test_meshEndpointSlice_Reconcile(t *testing.T) {
 		svcStore.CacheStore().Add(svc1)
 		serviceInformer.refreshAllCluster(svc1)
 
-		queue := getControllerQueue(controller)
-		require.NoError(t, waitEmptyQueue(queue))
-
-		epList, err := getEndpointSlice(&fakeClient, svcName)
-		require.NoError(t, err)
-		require.Zero(t, len(epList.Items))
+		require.EventuallyWithT(t, func(c *assert.CollectT) {
```
Comment (giorio94) [inline pkg/clustermesh/endpointslicesync/endpointslice_test.go:199]: This would not work as expected (and similarly the other ones asserting 0 epslices), because at the beginning the number of epslices is already 0. I'd suggest to manually create an epslice, and assert that it gets deleted.

File: pkg/clustermesh/endpointslicesync/endpointslice_test.go [hunk 3]
```diff
@@ -262,22 +238,21 @@ func Test_meshEndpointSlice_Reconcile(t *testing.T) {
...
+			assert.Equal(c, 1, len(epList.Items))
+			svc1.Annotations[annotation.GlobalServiceSyncEndpointSlices] = "false"
+			svcStore.CacheStore().Update(svc1)
+			serviceInformer.refreshAllCluster(svc1)
+
+			assert.EventuallyWithT(t, func(c *assert.CollectT) {
+				epList, err := getEndpointSlice(&fakeClient, svcName)
+				assert.NoError(c, err)
+				assert.Zero(c, len(epList.Items))
+			}, timeout, tick, "endpointslice is not reconciled correctly")
```
Comment (giorio94) [inline pkg/clustermesh/endpointslicesync/endpointslice_test.go]: I'd move this out of the first EventuallyWithT, to simplify troubleshooting possible failures.

File: pkg/clustermesh/endpointslicesync/endpointslice_test.go [hunk 4]
```diff
@@ -156,22 +138,21 @@ func Test_meshEndpointSlice_Reconcile(t *testing.T) {
...
-			corev1.IsHeadlessService:          "",
-		}, epList.Items[0].Labels)
-		require.Equal(t, 1, len(epList.Items[0].Endpoints))
-
-		require.NotNil(t, 1, epList.Items[0].Endpoints[0].Hostname)
-		require.Equal(t, *epList.Items[0].Endpoints[0].Hostname, hostname)
+		require.EventuallyWithT(t, func(c *assert.CollectT) {
+			epList, err := getEndpointSlice(&fakeClient, svcName)
+			assert.NoError(c, err)
+			assert.Equal(c, 1, len(epList.Items))
```
Comment (giorio94) [inline pkg/clustermesh/endpointslicesync/endpointslice_test.go]: Nit. `assert.Len` is more idiomatic.

**Review by giorio94 — CHANGES_REQUESTED** [review]
Thanks. I've left a couple of comments inline.

File: pkg/clustermesh/endpointslicesync/endpointslice_test.go (hunk 1 above)
Comment (MrFreezeex) [reply pkg/clustermesh/endpointslicesync/endpointslice_test.go]: Ahhh I thought `EventuallyWithT` was not blocking will do that then thanks!

File: pkg/clustermesh/endpointslicesync/endpointslice_test.go (hunk 2 above)
Comment (MrFreezeex) [reply pkg/clustermesh/endpointslicesync/endpointslice_test.go:199]: Yep indeed, and I actually caught a bug writing the correct code for that... When a service gets deleted on a remote cluster we can never reconcile this deletion back :(.  TLDR that's because in the service informer the List call no longer returns this deleted service so it never reach the Reconcile method where we should be deleting it in our custom cleanup hook. Will work on a fix this weekend!

**Comment by MrFreezeex** [comment]
Thanks for the feedback and finding the issue + the root cause of the test @giorio94 :pray:.

I unfortunately had to remove one of the test involving a remote service and no local service because I cannot really create an endpointslice locally and check that it's removed because this deletion is made through the normal ownerreferences.

File: pkg/clustermesh/endpointslicesync/endpointslice_test.go [hunk 5]
```diff
@@ -181,12 +164,13 @@ func Test_meshEndpointSlice_Reconcile(t *testing.T) {
...
+		var epList *discovery.EndpointSliceList
+		require.EventuallyWithT(t, func(c *assert.CollectT) {
+			epList, err = getEndpointSlice(&fakeClient, svcName)
+			assert.NoError(c, err)
+		}, timeout, tick, "endpointslice is not reconciled correctly")
 
-		epList, err := getEndpointSlice(&fakeClient, svcName)
-		require.NoError(t, err)
-		require.Equal(t, 1, len(epList.Items))
+		require.Len(t, epList.Items, 1)
```
Comment (giorio94) [inline pkg/clustermesh/endpointslicesync/endpointslice_test.go]: I assume this should be moved to the eventually body.

File: pkg/clustermesh/endpointslicesync/endpointslice_test.go [hunk 6]
```diff
@@ -247,12 +204,11 @@ func Test_meshEndpointSlice_Reconcile(t *testing.T) {
...
-		require.NoError(t, waitEmptyQueue(queue))
-
-		epList, err := getEndpointSlice(&fakeClient, svcName)
-		require.NoError(t, err)
-		require.Equal(t, 0, len(epList.Items))
+		require.EventuallyWithT(t, func(c *assert.CollectT) {
+			epList, err := getEndpointSlice(&fakeClient, svcName)
+			assert.NoError(c, err)
+			assert.Len(c, epList.Items, 0)
+		}, timeout, tick, "endpointslice is not reconciled correctly")
```
Comment (giorio94) [inline pkg/clustermesh/endpointslicesync/endpointslice_test.go:229]: This test also suffers from the issue of not creating an endpointslice at the beginning.

File: pkg/clustermesh/endpointslicesync/endpointslice_test.go [hunk 7]
```diff
@@ -262,22 +218,24 @@ func Test_meshEndpointSlice_Reconcile(t *testing.T) {
...
 		svcStore.CacheStore().Update(svc1)
 		serviceInformer.refreshAllCluster(svc1)
 
-		require.NoError(t, waitEmptyQueue(queue))
+		assert.EventuallyWithT(t, func(c *assert.CollectT) {
+			epList, err := getEndpointSlice(&fakeClient, svcName)
+			assert.NoError(c, err)
+			assert.Len(c, epList.Items, 0)
+		}, timeout, tick, "endpointslice is not reconciled correctly")
+	})
```
Comment (giorio94) [inline pkg/clustermesh/endpointslicesync/endpointslice_test.go:256]: This line should be dropped from the first commit, otherwise the tests don't compile there.

File: pkg/clustermesh/endpointslicesync/service_informer.go [hunk 8]
```diff
@@ -191,17 +194,36 @@ type meshServiceLister struct {
...
-	for _, clusterSvc := range clusterSvcs {
-		if svc, err := l.informer.clusterSvcToSvc(clusterSvc, false); err == nil {
-			svcs = append(svcs, svc)
+	svcIter := l.informer.serviceStore.IterKeys()
+	clusters := l.informer.meshNodeInformer.ListClusters()
+	var svcs []*v1.Service
+	for svcIter.Next() {
+		if svcIter.Key().Namespace != l.namespace {
+			continue
+		}
```
Comment (giorio94) [inline pkg/clustermesh/endpointslicesync/service_informer.go]: It could make sense to register a namespace indexer to the store and use `ByIndex` here, to avoid having to iterate over all services.

**Review by giorio94 — COMMENTED** [review]
A couple of final comments, but overall looks good to me, thanks!

**Comment by giorio94** [comment]
> I unfortunately had to remove one of the test involving a remote service and no local service because I cannot really create an endpointslice locally and check that it's removed because this deletion is made through the normal ownerreferences.

How about asserting in one of the tests that the resulting endpointslice has the correct owner reference? That would give us confidence that k8s will then take care of removing the stale endpointslices.

File: pkg/clustermesh/endpointslicesync/endpointslice_test.go (hunk 6 above)
Comment (MrFreezeex) [reply pkg/clustermesh/endpointslicesync/endpointslice_test.go:229]: Ah yep, I think this one is already covered by "Create service with global annotation and remove it" actually so it can be removed

File: pkg/clustermesh/endpointslicesync/endpointslice_test.go (hunk 5 above)
Comment (MrFreezeex) [reply pkg/clustermesh/endpointslicesync/endpointslice_test.go]: Oups yes, good catch thanks!

File: pkg/clustermesh/endpointslicesync/service_informer.go (hunk 8 above)
Comment (MrFreezeex) [reply pkg/clustermesh/endpointslicesync/service_informer.go]: Should I add that to `ServiceResource` in `pkg/k8s/resource_ctors.go` similarly to the indexer in `CiliumSlimEndpointResource`?

Comment (giorio94) [reply pkg/clustermesh/endpointslicesync/service_informer.go]: Yeah, sounds reasonable to me.

File: pkg/clustermesh/endpointslicesync/endpointslice_test.go [hunk 9]
```diff
@@ -156,22 +138,28 @@ func Test_meshEndpointSlice_Reconcile(t *testing.T) {
...
 		}, epList.Items[0].Labels)
-		require.Equal(t, 1, len(epList.Items[0].Endpoints))
+		require.Len(t, epList.Items[0].Endpoints, 1)
 
-		require.NotNil(t, 1, epList.Items[0].Endpoints[0].Hostname)
+		require.NotNil(t, epList.Items[0].Endpoints[0].Hostname)
 		require.Equal(t, *epList.Items[0].Endpoints[0].Hostname, hostname)
+
+		assert.Len(t, epList.Items[0].OwnerReferences, 1)
+		assert.Equal(t, epList.Items[0].OwnerReferences[0].APIVersion, "v1")
```
Comment (giorio94) [inline pkg/clustermesh/endpointslicesync/endpointslice_test.go]: Nit. The second and third parameters should be inverted (Equal assumes that the second one is the expected value).

File: pkg/k8s/resource_ctors.go [hunk 10]
```diff
@@ -51,6 +51,16 @@ func (def Config) Flags(flags *pflag.FlagSet) {
 	flags.String("k8s-service-proxy-name", def.K8sServiceProxyName, "Value of K8s service-proxy-name label for which Cilium handles the services (empty = all services without service.kubernetes.io/service-proxy-name label)")
 }
 
+// ciliumSlimServiceNamespaceIndexFunc is an IndexFunc that indexes Cilium slim
+// Service types by their namespace.
+func ciliumSlimServiceNamespaceIndexFunc(obj any) ([]string, error) {
+	object, ok := obj.(*slim_corev1.Service)
```
Comment (giorio94) [inline pkg/k8s/resource_ctors.go]: Nit. I'd suggest to generalize this and make it agnostic of the actual underlying type. For instance, you could rename the function to `namespaceIndexFunc`, and here cast to the `utils.NamespaceNameGetter` interface.

File: pkg/k8s/resource_ctors.go [hunk 11]
```diff
@@ -60,11 +70,18 @@ func ServiceResource(lc cell.Lifecycle, cfg Config, cs client.Clientset, opts ..
 	if err != nil {
 		return nil, err
 	}
+	indexers := cache.Indexers{
+		"namespace": ciliumSlimServiceNamespaceIndexFunc,
```
Comment (giorio94) [inline pkg/k8s/resource_ctors.go]: Nit. It could make sense to extract `"namespace"` into a `NamespaceIndex` constant.

File: pkg/clustermesh/endpointslicesync/endpointslice_test.go [hunk 12]
```diff
@@ -156,22 +138,28 @@ func Test_meshEndpointSlice_Reconcile(t *testing.T) {
...
 			corev1.IsHeadlessService:          "",
 		}, epList.Items[0].Labels)
-		require.Equal(t, 1, len(epList.Items[0].Endpoints))
+		require.Len(t, epList.Items[0].Endpoints, 1)
 
-		require.NotNil(t, 1, epList.Items[0].Endpoints[0].Hostname)
+		require.NotNil(t, epList.Items[0].Endpoints[0].Hostname)
 		require.Equal(t, *epList.Items[0].Endpoints[0].Hostname, hostname)
+
+		assert.Len(t, epList.Items[0].OwnerReferences, 1)
```
Comment (giorio94) [inline pkg/clustermesh/endpointslicesync/endpointslice_test.go]: Nit `s/assert/require` (same for the three occurrences below).

File: pkg/clustermesh/endpointslicesync/endpointslice_test.go [hunk 13]
```diff
@@ -181,12 +169,13 @@ func Test_meshEndpointSlice_Reconcile(t *testing.T) {
 		svcStore.CacheStore().Add(svc1)
 		serviceInformer.refreshAllCluster(svc1)
 
-		queue := getControllerQueue(controller)
-		require.NoError(t, waitEmptyQueue(queue))
+		var epList *discovery.EndpointSliceList
+		require.EventuallyWithT(t, func(c *assert.CollectT) {
+			epList, err = getEndpointSlice(&fakeClient, svcName)
+			assert.NoError(c, err)
+			require.Len(t, epList.Items, 1)
```
Comment (giorio94) [inline pkg/clustermesh/endpointslicesync/endpointslice_test.go]:
```suggestion
			assert.Len(c, epList.Items, 1)
```

File: pkg/clustermesh/endpointslicesync/endpointslice_test.go [hunk 14]
```diff
@@ -262,22 +207,48 @@ func Test_meshEndpointSlice_Reconcile(t *testing.T) {
...
+			assert.NoError(c, err)
+			assert.Len(c, epList.Items, 1)
+		}, timeout, tick, "endpointslice is not reconciled correctly")
 
 		svc1.Annotations[annotation.GlobalServiceSyncEndpointSlices] = "false"
 		svcStore.CacheStore().Update(svc1)
 		serviceInformer.refreshAllCluster(svc1)
 
-		require.NoError(t, waitEmptyQueue(queue))
+		assert.EventuallyWithT(t, func(c *assert.CollectT) {
```
Comment (giorio94) [inline pkg/clustermesh/endpointslicesync/endpointslice_test.go]:
```suggestion
		require.EventuallyWithT(t, func(c *assert.CollectT) {
```

File: pkg/clustermesh/endpointslicesync/endpointslice_test.go [hunk 15]
```diff
@@ -262,22 +207,48 @@ func Test_meshEndpointSlice_Reconcile(t *testing.T) {
...
+			epList, err = getEndpointSlice(&fakeClient, svcName)
+			assert.NoError(c, err)
+			assert.Len(c, epList.Items, 1)
+		}, timeout, tick, "endpointslice is not reconciled correctly")
+
+		globalService.OnDelete(clusterSvc)
+		// We manually call the rest of the informer for convenience
+		podInformer.onClusterServiceDelete(clusterSvc)
+
+		assert.EventuallyWithT(t, func(c *assert.CollectT) {
```
Comment (giorio94) [inline pkg/clustermesh/endpointslicesync/endpointslice_test.go]:
```suggestion
		require.EventuallyWithT(t, func(c *assert.CollectT) {
```

**Review by giorio94 — APPROVED** [review]
Thanks, just a couple of nits inline. I've re-run the stress test, and hit no failures after 5k runs.

File: pkg/k8s/resource_ctors.go (hunk 10 above)
Comment (MrFreezeex) [reply pkg/k8s/resource_ctors.go]: Ah yes! I was trying to find a type that was matching this earlier but wasn't able to, thanks!

File: pkg/clustermesh/endpointslicesync/endpointslice_test.go [hunk 16]
```diff
@@ -181,12 +169,13 @@ func Test_meshEndpointSlice_Reconcile(t *testing.T) {
 		svcStore.CacheStore().Add(svc1)
 		serviceInformer.refreshAllCluster(svc1)
 
-		queue := getControllerQueue(controller)
-		require.NoError(t, waitEmptyQueue(queue))
+		var epList *discovery.EndpointSliceList
+		require.EventuallyWithT(t, func(c *assert.CollectT) {
+			epList, err = getEndpointSlice(&fakeClient, svcName)
+			assert.NoError(c, err)
+			assert.Len(t, epList.Items, 1)
```
Comment (giorio94) [inline pkg/clustermesh/endpointslicesync/endpointslice_test.go:179]:
```suggestion
			assert.Len(c, epList.Items, 1)
```

Otherwise the test will incorrectly fail if the assertion fails once.

**Comment by giorio94** [comment]
@MrFreezeex One of the unit test failures are legitimate:

```
 --- FAIL: Test_meshEndpointSlice_Reconcile/Create_service_then_global_service (0.01s)

I0611 09:13:26.678082   49847 endpointslice_controller.go:296] "Starting endpoint slice controller"
I0611 09:13:26.678103   49847 shared_informer.go:313] Waiting for caches to sync for endpoint_slice
I0611 09:13:26.678110   49847 shared_informer.go:320] Caches are synced for endpoint_slice
    endpointslice_test.go:161: 
        	Error Trace:	/home/runner/work/cilium/cilium/pkg/clustermesh/endpointslicesync/endpointslice_test.go:161
        	Error:      	Not equal: 
        	            	expected: "service"
        	            	actual  : "Service"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-service
        	            	+Service
        	Test:       	Test_meshEndpointSlice_Reconcile/Create_service_then_global_service
```

**Comment by MrFreezeex** [comment]
> @MrFreezeex One of the unit test failures are legitimate:
> 
> ```
>  --- FAIL: Test_meshEndpointSlice_Reconcile/Create_service_then_global_service (0.01s)
> 
> I0611 09:13:26.678082   49847 endpointslice_controller.go:296] "Starting endpoint slice controller"
> I0611 09:13:26.678103   49847 shared_informer.go:313] Waiting for caches to sync for endpoint_slice
> I0611 09:13:26.678110   49847 shared_informer.go:320] Caches are synced for endpoint_slice
>     endpointslice_test.go:161: 
>         	Error Trace:	/home/runner/work/cilium/cilium/pkg/clustermesh/endpointslicesync/endpointslice_test.go:161
>         	Error:      	Not equal: 
>         	            	expected: "service"
>         	            	actual  : "Service"
>         	            	
>         	            	Diff:
>         	            	--- Expected
>         	            	+++ Actual
>         	            	@@ -1 +1 @@
>         	            	-service
>         	            	+Service
>         	Test:       	Test_meshEndpointSlice_Reconcile/Create_service_then_global_service
> ```

Woops indeed my bad!

**Comment by giorio94** [comment]
@MrFreezeex, could you please rebase this PR? That should fix the failing tests

**Comment by aanm** [comment]
@MrFreezeex can you rebase? it looks there are a couple of conflicting files.

**Review by aanm — APPROVED** [review]
