### PR TITLE
Best effort for xdp

### LINKED ISSUE #24768: XDP: Failing to attach XDP program to a tagged VLAN interface
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

With Cilium 1.13.0, we could successfully enable XDP when a node has a single native VLAN. However, after we added a tagged VLAN (namely, vlan3 with the vlan id 3) on the same node along with the native VLAN, and then restarted its cilium agent, we got the following error.
```
Failed to compile XDP program" error="program cil_xdp_entry: attaching XDP program to interface vlan3: operation not supported" subsys=datapath-loader
```
Here is our installation parameter set. Basically we use BPG to advertise both POD CIRD and Service CIDR with xvlan tunneling for Pod-to-pod communication.
```
helm upgrade --namespace kube-system cilium cilium/cilium --version 1.13.0 --set bgpControlPlane.enabled=true,bpf.masquerade=true,cluster.id=0,cluster.name=k8s-cluster-01,encryption.nodeEncryption=false,ipMasqAgent.enabled=true,ipam.mode=kubernetes,ipam.operator.clusterPoolIPv4MaskSize=26,ipam.operator.clusterPoolIPv4PodCIDR=172.16.0.0/12,kubeProxyReplacement=strict,loadBalancer.acceleration=native,operator.replicas=1,serviceAccounts.cilium.name=cilium,serviceAccounts.operator.name=cilium-operator,tunnel=vxlan
Release "cilium" has been upgraded. Happy Helming!
NAME: cilium
LAST DEPLOYED: Tue Apr  4 15:47:21 2023
NAMESPACE: kube-system
STATUS: deployed
REVISION: 9
TEST SUITE: None
NOTES:
You have successfully installed Cilium with Hubble.

Your release version is 1.13.0.
```
Just in case, here is an example of the success case when there is only a single VLAN as a good reference. I think such a result can prove our Mellanox driver supports XDP.
But unfortunately I could not see such a good result after adding a tagged VLAN on the native VLAN interface.
```
# bpftool net
xdp:
ens785np0(2) driver id 1641

tc:
ens785np0(2) clsact/ingress cilium-ens785np0 id 1754
ens785np0(2) clsact/egress cilium-ens785np0 id 1756
cilium_net(4) clsact/ingress cilium-cilium_net id 1737
cilium_host(5) clsact/ingress cilium-cilium_host id 1718
cilium_host(5) clsact/egress cilium-cilium_host id 1724
cilium_vxlan(6) clsact/ingress bpf_overlay.o:[from-overlay] id 1576
cilium_vxlan(6) clsact/egress bpf_overlay.o:[to-overlay] id 1587
lxc_health(11) clsact/ingress cilium-lxc_health id 1674
```

### Cilium Version

1.13.0

### Kernel Version

Linux worknode-1 5.15.0-67-generic #74~20.04.1-Ubuntu SMP Wed Feb 22 14:52:34 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.24.10+rke2r1

### Sysdump

Somehow my sysdump file is too big (189MB), I cannot upload it here because its size exceeds 25 MB.

### Relevant log output

```shell
$ cilium status
...
...
Errors:           cilium             cilium-jmgtm    unable to retrieve cilium status: container cilium-agent is in CrashLoopBackOff, exited with code 1: level=fatal msg="Failed to compile XDP program" error="program cil_xdp_entry: attaching XDP program to interface vlan3: operation not supported" subsys=datapath-loader
...
```

### Anything else?

# lspci | grep -i ether
01:00.0 Ethernet controller: Intel Corporation Ethernet Controller 10G X550T (rev 01)
65:00.0 Ethernet controller: Mellanox Technologies MT28908 Family [ConnectX-6]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by poblahblahblah**
Please ensure your pull request adheres to the following guidelines:

- [X] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [?] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [X] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [X] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [X] Provide a title or release-note blurb suitable for the release notes.
- [?] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [X] Thanks for contributing!

This allows a user to specify a new mode, `best-effort` when enabling XDP. We need this ability since we are running physical hosts where the primary NICs do support XDP, but have additional `vlan` devices that _do not_ have XDP support in the driver.

More background can be found in #24768, but to summarize we have 1 physical device (ens785np0) per host and due to network design we need an additional `vlan` type interface (`vlan3`). Regrettably the `vlan` driver in the kernel does not support XDP. When enabling XDP without this change Cilium enters a crashloop with this error:

```
level=fatal msg="Failed to compile XDP program" error="program cil_xdp_entry: attaching XDP program to interface vlan3: operation not supported" subsys=datapath-loader
```

With this change applied and by setting `loadBalancer.acceleration` to `best-effort` in our values.yaml file we get the following log output with XDP enabled only on devices that support it:

```
level=info msg="attaching XDP program to interface vlan3 failed. Ignoring" subsys=datapath-loader
```

```
$ sudo bpftool net
xdp:
ens785np0(2) driver id 28652

tc:
ens785np0(2) clsact/ingress cil_from_netdev-ens785np0 id 28699
ens785np0(2) clsact/egress cil_to_netdev-ens785np0 id 28721
vlan3(4) clsact/ingress cil_from_netdev-vlan3 id 28731
vlan3(4) clsact/egress cil_to_netdev-vlan3 id 28739
cilium_net(5) clsact/ingress cil_to_host-cilium_net id 28692
cilium_host(6) clsact/ingress cil_to_host-cilium_host id 28674
cilium_host(6) clsact/egress cil_from_host-cilium_host id 28686
cilium_vxlan(7) clsact/ingress cil_from_overlay-cilium_vxlan id 28663
cilium_vxlan(7) clsact/egress cil_to_overlay-cilium_vxlan id 28664
lxc_health(11) clsact/ingress cil_from_container-lxc_health id 28708

flow_dissector:
```

I initially created https://github.com/cilium/cilium/pull/25870 and it was indicated in [this comment thread](https://github.com/cilium/cilium/pull/25870#discussion_r1313247066) that swallowing these errors if set to "best-effort" would be an acceptable solution.

Any and all feedback would be very welcome!

Fixes: #24768

```release-note
Adds "best-effort" mode for XDP to skip interfaces without driver support
```

### CODE REVIEW

File: pkg/option/config.go [hunk 1]
```diff
@@ -881,6 +881,9 @@ const (
 	// XDPModeNative for loading progs with XDPModeLinkDriver
 	XDPModeNative = "native"
 
+	// XDPModeBestEffort for loading progs with XDPModeLinkDriver
+	XDPModeBestEffort = "best-effort"
```
Comment (mhofstetter) [inline pkg/option/config.go:878]: The additional value `best-effort` should be documented in the helm chart too. Maybe it's also worth to add the already missing value `generic`.

https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml.tmpl#L1774-L1776

Please follow the instructions in the Cilium docs: https://docs.cilium.io/en/latest/contributing/development/dev_setup/#making-changes-to-the-helm-chart

Comment (mhofstetter) [inline pkg/option/config.go:878]: The additional value `best-effort` needs to be reflected in the Cilium CLI model too. It's used by the command `cilium status --verbose`.

https://github.com/cilium/cilium/blob/main/api/v1/models/kube_proxy_replacement.go#L1137-L1138
&
https://github.com/cilium/cilium/blob/main/api/v1/models/kube_proxy_replacement.go#L1195-L1205

**Review by mhofstetter — CHANGES_REQUESTED** [review]
Thanks for the contribution @poblahblahblah

Added some config-related comments.

@borkmann Adding you as reviewer because it seems that you already have the context from the issue and the previous PR

File: pkg/datapath/loader/link.go [hunk 2]
```diff
@@ -27,6 +27,14 @@ func SetXDPMode(mode string) error {
 			return fmt.Errorf("XDP Mode conflict: current mode is %s, trying to set conflicting %s",
 				option.Config.XDPMode, option.XDPModeLinkGeneric)
 		}
+	case option.XDPModeBestEffort:
```
Comment (rgo3) [inline pkg/datapath/loader/link.go]: Could this case be combined with `case option.XDPModeNative` to avoid the code duplication?

File: pkg/datapath/loader/xdp.go [hunk 3]
```diff
@@ -21,6 +21,8 @@ func xdpModeToFlag(xdpMode string) uint32 {
 	switch xdpMode {
 	case option.XDPModeNative:
 		return nl.XDP_FLAGS_DRV_MODE
+	case option.XDPModeBestEffort:
```
Comment (rgo3) [inline pkg/datapath/loader/xdp.go]: nit: we could combine some of cases on the switch here as well as a drive-by.

File: pkg/datapath/loader/netlink.go [hunk 4]
```diff
@@ -170,7 +170,11 @@ func attachProgram(link netlink.Link, prog *ebpf.Program, progName string, qdisc
 		// Omitting XDP_FLAGS_UPDATE_IF_NOEXIST equals running 'ip' with -force,
 		// and will clobber any existing XDP attachment to the interface.
 		if err := netlink.LinkSetXdpFdWithFlags(link, prog.FD(), int(xdpFlags)); err != nil {
-			return fmt.Errorf("attaching XDP program to interface %s: %w", link.Attrs().Name, err)
+			if option.Config.NodePortAcceleration == option.XDPModeBestEffort {
+				log.Infof("attaching XDP program to interface %s failed. Ignoring", link.Attrs().Name)
```
Comment (rgo3) [inline pkg/datapath/loader/netlink.go]: Should we include the error in the log message to display a reason for the failure for debugging purposes?

**Review by rgo3 — CHANGES_REQUESTED** [review]
Thanks, just a couple nits.

File: pkg/option/config.go (hunk 1 above)
Comment (poblahblahblah) [reply pkg/option/config.go:878]: No matter what I did I could not figure out how to get those files to be updated. Here's what I ran:

```
make generate-api
```

However, having these updated does not appear to be necessary. Here's the output from `cilium status --verbose`:

```
KubeProxyReplacement Details:
  Status:                 Strict
  Socket LB:              Enabled
  Socket LB Tracing:      Enabled
  Socket LB Coverage:     Full
  Devices:                ens785np0 10.121.160.29 (Direct Routing)
  Mode:                   SNAT
  Backend Selection:      Random
  Session Affinity:       Enabled
  Graceful Termination:   Enabled
  NAT46/64 Support:       Disabled
  XDP Acceleration:       Best-Effort
  Services:
  - ClusterIP:      Enabled
  - NodePort:       Enabled (Range: 30000-32767)
  - LoadBalancer:   Enabled
  - externalIPs:    Enabled
  - HostPort:       Enabled
```

**Comment by poblahblahblah** [comment]
I'll squash commits into a single commit once this is looking like it will be ready for merge.

File: pkg/option/config.go (hunk 1 above)
Comment (mhofstetter) [reply pkg/option/config.go:878]: You should be able to update the [OpenAPI model](https://github.com/cilium/cilium/blob/main/api/v1/openapi.yaml#L2335) and re-generate with `make generate-api`.

At least for the sake of completeness

File: pkg/datapath/loader/netlink.go [hunk 5]
```diff
@@ -170,7 +170,11 @@ func attachProgram(link netlink.Link, prog *ebpf.Program, progName string, qdisc
 		// Omitting XDP_FLAGS_UPDATE_IF_NOEXIST equals running 'ip' with -force,
 		// and will clobber any existing XDP attachment to the interface.
 		if err := netlink.LinkSetXdpFdWithFlags(link, prog.FD(), int(xdpFlags)); err != nil {
-			return fmt.Errorf("attaching XDP program to interface %s: %w", link.Attrs().Name, err)
+			if option.Config.NodePortAcceleration == option.XDPModeBestEffort {
```
Comment (squeed) [inline pkg/datapath/loader/netlink.go]: I don't like swallowing the error here; this function is not specific to NodePorts. Rather, this config check should be specific to the code path that attaches the NodePort XDP program

**Review by squeed — CHANGES_REQUESTED** [review]

File: install/kubernetes/cilium/values.yaml.tmpl [hunk 6]
```diff
@@ -1772,7 +1772,7 @@ loadBalancer:
   # mode: snat
 
   # -- acceleration is the option to accelerate service handling via XDP
-  # e.g. native, disabled
+  # e.g. native, disabled, generic, best-effort
```
Comment (squeed) [inline install/kubernetes/cilium/values.yaml.tmpl]: As @mhofstetter, it would be nice to have a word or two explaining what these different options are (or, a link to the documentation). Helm chart docs, sadly, don't well with paragraph breaks / formatting because of some silly transformations we do :crying_cat_face:. So, if documenting this gets hard, it should be a section in the XDP documentation.

Sorry, I know this is a bit more work than you bargained for.

**Comment by squeed** [comment]
A few small changes, but looks basically good. Thanks!

File: pkg/datapath/loader/netlink.go (hunk 5 above)
Comment (rgo3) [reply pkg/datapath/loader/netlink.go]: While not entirely specific to NodePort code path it could live in `reinitializeXDPLocked()`. I think the original PR #25870 placed its logic there as well. Plus there is already logic to skip certain devices in that function.

File: install/kubernetes/cilium/values.yaml.tmpl (hunk 6 above)
Comment (poblahblahblah) [reply install/kubernetes/cilium/values.yaml.tmpl]: No worries - I will take care of this either way

File: pkg/datapath/loader/netlink.go (hunk 5 above)
Comment (poblahblahblah) [reply pkg/datapath/loader/netlink.go]: Yeah, this section felt like a pretty good fit when I was going through everything. Happy to adjust if there are strong opinions about it.

File: pkg/option/config.go (hunk 1 above)
Comment (poblahblahblah) [reply pkg/option/config.go:878]: That is very helpful, thank you @mhofstetter

File: install/kubernetes/cilium/values.yaml.tmpl (hunk 6 above)
Comment (poblahblahblah) [reply install/kubernetes/cilium/values.yaml.tmpl]: Also updated the regular documentation (Documentation/bpf/progtypes.rst) in commit 305dfa694c82987ab69733e9b1e199f672b44350

**Review by mhofstetter — APPROVED** [review]
LGTM for the agent bits.

File: pkg/datapath/loader/netlink.go (hunk 5 above)
Comment (squeed) [reply pkg/datapath/loader/netlink.go]: I'll let @cilium/loader make the final decision.

**Review by squeed — APPROVED** [review]

File: pkg/datapath/loader/netlink.go [hunk 7]
```diff
@@ -170,7 +170,11 @@ func attachProgram(link netlink.Link, prog *ebpf.Program, progName string, qdisc
...
+				log.Infof("attaching XDP program to interface %s failed. Ignoring. %w", link.Attrs().Name, err)
```
Comment (joamaki) [inline pkg/datapath/loader/netlink.go]: nit: `log.WithError(err).WithField(logfields.Device, link.Attrs().Name).Info("Attaching ... ")`. This way the device name and error are available in the structured logging as separate fields.

File: pkg/datapath/loader/netlink.go (hunk 5 above)
Comment (joamaki) [reply pkg/datapath/loader/netlink.go]: A good rule of thumb to apply is to avoid use of `option.Config` at deeper layers since that makes testing fairly annoying since now in tests you'll need to mutate the global `option.Config` and then restore it. 

One possibility here is to just pass the `option.Config.XDPMode` that `reinitializeXDPLocked` grabs all the way down to `attachProgram` and handle the "BestEffort" option there and then convert to XDP flags. This way this low-level function isn't coupled to the `option.Config` global. E.g. just move the "xdpModeToFlags" from `replaceDatapath` to `attachProgram`.

Also talking about tests, could you look into adding a test case for this into `netlink_test.go`? `TestAttachProgram` already has a "XDP" sub-test which would be easy to copy + adapt.

File: pkg/datapath/loader/xdp.go [hunk 8]
```diff
@@ -19,13 +19,9 @@ import (
 
 func xdpModeToFlag(xdpMode string) uint32 {
 	switch xdpMode {
-	case option.XDPModeNative:
+	case option.XDPModeNative, option.XDPModeLinkDriver, option.XDPModeBestEffort:
```
Comment (joamaki) [inline pkg/datapath/loader/xdp.go:30]: Hmm, now `XDPModeBestEffort` in a way implies `XDPModeLinkDriver`. Perhaps it'd be better to reflect that in the name? `XDPModeLinkDriverBestEffort`or `XDPModeTryLinkDriver` come to mind, but they're a bit of a mouthful.

File: Documentation/bpf/progtypes.rst [hunk 9]
```diff
@@ -323,6 +323,13 @@ talked about XDP this mode is typically implied.
   production environment either the native or offloaded mode is better
   suited and the recommended way to run XDP.
 
+..
+
+* **Best Effort**
```
Comment (joamaki) [inline Documentation/bpf/progtypes.rst]: This is generic, non-cilium specific, documentation about BPF and thus this doesn't belong here.

File: pkg/datapath/loader/netlink.go (hunk 5 above)
Comment (joamaki) [reply pkg/datapath/loader/netlink.go]: Also I wonder if skipping is the right thing to do here. We can also try the generic mode before skipping entirely. OTOH, quite likely we'd prefer the tc filter program as a fallback to generic XDP... Perhaps someone from sig-loader can chime in on whether it'd make sense or not.

**Review by joamaki — CHANGES_REQUESTED** [review]

File: install/kubernetes/cilium/values.yaml.tmpl [hunk 10]
```diff
@@ -1772,7 +1772,17 @@ loadBalancer:
...
+  # disabled - do not use XDP
+  # native - XDP BPF program is run directly out of the networking driver’s
+  #   early receive path.
+  # generic - For drivers not implementing native or offloaded XDP yet, the
+  #   kernel provides an option for generic XDP which does not require any
+  #   driver changes since run at a much later point out of the networking
+  #   stack. This setting is primarily targeted at developers who want to
+  #   write and test programs against the kernel’s XDP API, and will not
+  #   operate at the performance rate of the native or offloaded modes.
+  # best-effort - Use native where possible, but ignore devices without XDP
```
Comment (joamaki) [inline install/kubernetes/cilium/values.yaml.tmpl]: "ignore devices" can be a bit misleading. Cilium will still handle traffic to/from this device using the program attached to a TC filter. Perhaps something like "Use native mode XDP acceleration on devices that support it".

File: pkg/datapath/loader/netlink.go (hunk 5 above)
Comment (poblahblahblah) [reply pkg/datapath/loader/netlink.go]: @joamaki From the documentation it doesn't sound like Generic is recommended outside of testing scenarios.

Taken from https://docs.cilium.io/en/stable/bpf/progtypes/

```
For drivers not implementing native or offloaded XDP yet, the kernel provides an option for generic XDP which does not require any driver changes since run at a much later point out of the networking stack. This setting is primarily targeted at developers who want to write and test programs against the kernel’s XDP API, and will not operate at the performance rate of the native or offloaded modes. For XDP usage in a production environment either the native or offloaded mode is better suited and the recommended way to run XDP.
```

As this PR is currently written it will fall back to tc if XDP "native" fails.

File: pkg/datapath/loader/xdp.go (hunk 8 above)
Comment (poblahblahblah) [reply pkg/datapath/loader/xdp.go:30]: Happy to update this to whatever consensus the Cilium project can reach!

File: Documentation/bpf/progtypes.rst (hunk 9 above)
Comment (poblahblahblah) [reply Documentation/bpf/progtypes.rst]: Will remove.

**Comment by ti-mo** [comment]
Note there's also https://github.com/cilium/cilium/pull/28308 in-flight that needs to work with this. Ideally the xdp_link stuff should go in first.

File: pkg/datapath/loader/xdp.go (hunk 8 above)
Comment (qmonnet) [reply pkg/datapath/loader/xdp.go:30]: For what it's worth I like `XDPModeTryLinkDriver`, it's not that long.

Comment (poblahblahblah) [reply pkg/datapath/loader/xdp.go:30]: Does anyone have a strong opinion on this?

Keep in mind that BestEffort is what was originally suggested by @borkmann so this wasn't just me pulling something out of thin air!

File: pkg/datapath/loader/netlink.go (hunk 5 above)
Comment (poblahblahblah) [reply pkg/datapath/loader/netlink.go]: Does anyone else want to weigh in on this?

**Comment by poblahblahblah** [comment]
@joamaki 

Responding to a comment from above that I can't respond to inline

```
A good rule of thumb to apply is to avoid use of option.Config at deeper layers since that makes testing fairly annoying since now in tests you'll need to mutate the global option.Config and then restore it.

One possibility here is to just pass the option.Config.XDPMode that reinitializeXDPLocked grabs all the way down to attachProgram and handle the "BestEffort" option there and then convert to XDP flags. This way this low-level function isn't coupled to the option.Config global. E.g. just move the "xdpModeToFlags" from replaceDatapath to attachProgram.

Also talking about tests, could you look into adding a test case for this into netlink_test.go? TestAttachProgram already has a "XDP" sub-test which would be easy to copy + adapt.
```

I went with using option.Config here because option.Config was already being called when defining the bpf filter on line 194. Is this a change you still want to see made?

Happy to attempt a test regardless, but do let me know your thoughts on the above question

File: pkg/datapath/loader/netlink.go (hunk 5 above)
Comment (borkmann) [reply pkg/datapath/loader/netlink.go]: > Also I wonder if skipping is the right thing to do here. We can also try the generic mode before skipping entirely. OTOH, quite likely we'd prefer the tc filter program as a fallback to generic XDP... Perhaps someone from sig-loader can chime in on whether it'd make sense or not.

Generic mode should not be used in production, it will bypass GRO engine. Fallback to tc is significantly better.

File: install/kubernetes/cilium/values.yaml.tmpl [hunk 11]
```diff
@@ -1772,7 +1772,17 @@ loadBalancer:
...
-  # e.g. native, disabled
+  # disabled - do not use XDP
+  # native - XDP BPF program is run directly out of the networking driver’s
+  #   early receive path.
+  # generic - For drivers not implementing native or offloaded XDP yet, the
+  #   kernel provides an option for generic XDP which does not require any
+  #   driver changes since run at a much later point out of the networking
+  #   stack. This setting is primarily targeted at developers who want to
+  #   write and test programs against the kernel’s XDP API, and will not
+  #   operate at the performance rate of the native or offloaded modes.
```
Comment (borkmann) [inline install/kubernetes/cilium/values.yaml.tmpl]: small nit: Lets leave out 'generic' as imho nobody should use it. It also won't work with 'generic' the undocumented string would be 'testing-only'.

File: Documentation/bpf/progtypes.rst [hunk 12]
```diff
@@ -323,6 +323,13 @@ talked about XDP this mode is typically implied.
...
+
+  Attempt to use Native XDP on all devices, but ignore devices without XDP
+  driver support in the kernel.
```
Comment (borkmann) [inline Documentation/bpf/progtypes.rst]: small nit: Please remove this doc extension in progtypes, because this refers to kernel types, not Cilium.

Please extend https://github.com/cilium/cilium/blob/main/Documentation/network/kubernetes/kubeproxy-free.rst#loadbalancer--nodeport-xdp-acceleration instead given there the option 'best-effort' should be mentioned.

File: install/kubernetes/cilium/values.yaml [hunk 13]
```diff
@@ -1775,7 +1775,17 @@ loadBalancer:
...
-  # e.g. native, disabled
+  # disabled - do not use XDP
+  # native - XDP BPF program is run directly out of the networking driver’s
+  #   early receive path.
+  # generic - For drivers not implementing native or offloaded XDP yet, the
+  #   kernel provides an option for generic XDP which does not require any
+  #   driver changes since run at a much later point out of the networking
+  #   stack. This setting is primarily targeted at developers who want to
+  #   write and test programs against the kernel’s XDP API, and will not
+  #   operate at the performance rate of the native or offloaded modes.
```
Comment (borkmann) [inline install/kubernetes/cilium/values.yaml]: (ditto wrt removing generic on the auto-generated yaml)

File: pkg/datapath/loader/xdp.go (hunk 8 above)
Comment (borkmann) [reply pkg/datapath/loader/xdp.go:30]: small nit: could you pls not squash the switch/case, but just add option.XDPModeBestEffort with fall through. 

@joamaki isn't the option.XDPModeLink* from the old-style XDP code where we had the prefilter?

**Comment by borkmann** [comment]
Hi Patrick, pls also squash your commits into a single one or multiple but logically split rather than the PR feedback diffs, so it better helps to review. Thanks a lot for pushing this fwd!

File: pkg/datapath/loader/xdp.go (hunk 8 above)
Comment (poblahblahblah) [reply pkg/datapath/loader/xdp.go:30]: @borkmann done

**Comment by poblahblahblah** [comment]
@borkmann I think I've taken care of your feedback! Thank you for the review!

**Review by joamaki — APPROVED** [review]

**Comment by joamaki** [comment]
> @joamaki
> 
> Responding to a comment from above that I can't respond to inline
> 
> ```
> A good rule of thumb to apply is to avoid use of option.Config at deeper layers since that makes testing fairly annoying since now in tests you'll need to mutate the global option.Config and then restore it.
> 
> One possibility here is to just pass the option.Config.XDPMode that reinitializeXDPLocked grabs all the way down to attachProgram and handle the "BestEffort" option there and then convert to XDP flags. This way this low-level function isn't coupled to the option.Config global. E.g. just move the "xdpModeToFlags" from replaceDatapath to attachProgram.
> 
> Also talking about tests, could you look into adding a test case for this into netlink_test.go? TestAttachProgram already has a "XDP" sub-test which would be easy to copy + adapt.
> ```
> 
> I went with using option.Config here because option.Config was already being called when defining the bpf filter on line 194. Is this a change you still want to see made?
> 
> Happy to attempt a test regardless, but do let me know your thoughts on the above question

Yep, I'd be still happy to see this change and the test as they shouldn't be too much effort. I'm however OK with this so marking approved from my side (heading on vacation today).

File: Documentation/network/kubernetes/kubeproxy-free.rst [hunk 14]
```diff
@@ -675,7 +675,9 @@ In case of a multi-device environment, where Cilium's device auto-detection sele
 more than a single device to expose NodePort or a user specifies multiple devices
 with ``devices``, the XDP acceleration is enabled on all devices. This means that
 each underlying device's driver must have native XDP support on all Cilium managed
-nodes. In addition, for performance reasons we recommend kernel >= 5.5 for
+nodes. If you have an environment where some devices support XDP but others do not
+You can have XDP enabled on the supported devices by setting loadBalancer.mode to 
+"best-effort". In addition, for performance reasons we recommend kernel >= 5.5 for
```
Comment (qmonnet) [inline Documentation/network/kubernetes/kubeproxy-free.rst]: Phrasing/formatting nitpicks:

```suggestion
nodes. If you have an environment where some devices support XDP but others do not,
you can enable XDP on the supported devices by setting ``loadBalancer.mode`` to 
``best-effort``. For performance reasons we recommend kernel >= 5.5 for
```

File: Documentation/network/kubernetes/kubeproxy-free.rst [hunk 15]
```diff
@@ -675,7 +675,9 @@ In case of a multi-device environment, where Cilium's device auto-detection sele
 more than a single device to expose NodePort or a user specifies multiple devices
 with ``devices``, the XDP acceleration is enabled on all devices. This means that
 each underlying device's driver must have native XDP support on all Cilium managed
-nodes. In addition, for performance reasons we recommend kernel >= 5.5 for
+nodes. If you have an environment where some devices support XDP but others do not
+You can have XDP enabled on the supported devices by setting loadBalancer.mode to
```
Comment (qmonnet) [inline Documentation/network/kubernetes/kubeproxy-free.rst]: Shouldn't this be `loadBalancer.acceleration` rather than `loadBalancer.mode`??

File: install/kubernetes/cilium/values.yaml.tmpl [hunk 16]
```diff
@@ -1772,7 +1772,11 @@ loadBalancer:
   # mode: snat
 
   # -- acceleration is the option to accelerate service handling via XDP
-  # e.g. native, disabled
+  # disabled - do not use XDP
+  # native - XDP BPF program is run directly out of the networking driver’s
+  #   early receive path.
+  # best-effort - Use native mode XDP acceleration on devices that support
+  #   it.
```
Comment (qmonnet) [inline install/kubernetes/cilium/values.yaml.tmpl]: I see you updated both `.../values.yaml` and `.../values.yaml.tmpl`, but you also need to run `make -C install/kubernetes` to propagate the change to `install/kubernetes/cilium/README.md`.

When you do so, you should observe that the formatting you're using here (the list) translates rather badly in the `README.md`, where the comment lines are joined together. Can you please improve it? For example:

```suggestion
  # Applicable values can be: disabled (do not use XDP), native (XDP BPF
  # program is run directly out of the networking driver's early receive path),
  # or best-effort (use native mode XDP acceleration on devices that support it).
```

File: install/kubernetes/cilium/values.yaml.tmpl [hunk 17]
```diff
@@ -1772,7 +1772,11 @@ loadBalancer:
   # mode: snat
 
   # -- acceleration is the option to accelerate service handling via XDP
-  # e.g. native, disabled
+  # disabled - do not use XDP
+  # native - XDP BPF program is run directly out of the networking driver’s
```
Comment (qmonnet) [inline install/kubernetes/cilium/values.yaml.tmpl]: Please avoid curly apostrophes, they're a pain for grepping.

**Review by qmonnet — CHANGES_REQUESTED** [review]

File: Documentation/network/kubernetes/kubeproxy-free.rst (hunk 14 above)
Comment (qmonnet) [reply Documentation/network/kubernetes/kubeproxy-free.rst]: This should also address the complaint in the CI workflow for documentation.

File: Documentation/network/kubernetes/kubeproxy-free.rst (hunk 15 above)
Comment (poblahblahblah) [reply Documentation/network/kubernetes/kubeproxy-free.rst]: Yes, good catch.

File: install/kubernetes/cilium/values.yaml.tmpl (hunk 17 above)
Comment (poblahblahblah) [reply install/kubernetes/cilium/values.yaml.tmpl]: Oh weird. Not sure how that snuck in.

File: install/kubernetes/cilium/values.yaml.tmpl (hunk 16 above)
Comment (poblahblahblah) [reply install/kubernetes/cilium/values.yaml.tmpl]: I thought I had run `make -C install/kubernetes` in order to generate values.yaml but I didn't see it making any changes to install/kubernetes/cilium/README.md. I'll do this again and dig a little bit.

Comment (poblahblahblah) [reply install/kubernetes/cilium/values.yaml.tmpl]: Ok - figured out the issue here.

Since `acceleration` was cancelled out it was never showing up in the helm chart's README.md file since it wasn't registering as being a value that could be set.

For now I have uncommented it in `values.yaml.tmpl` setting it to `disabled` as the default and ran `make -C install/kubernetes`.

it's now documented in the README.

Does this look good @qmonnet?

File: Documentation/network/kubernetes/kubeproxy-free.rst [hunk 18]
```diff
@@ -675,8 +675,10 @@ In case of a multi-device environment, where Cilium's device auto-detection sele
 more than a single device to expose NodePort or a user specifies multiple devices
 with ``devices``, the XDP acceleration is enabled on all devices. This means that
 each underlying device's driver must have native XDP support on all Cilium managed
-nodes. In addition, for performance reasons we recommend kernel >= 5.5 for
-the multi-device XDP acceleration.
+nodes. If you have an environment where some devices support XDP but others do not
+you can have XDP enabled on the supported devices by setting
+``loadBalancer.acceleration`` to   ``best-effort``. In addition, for performance
```
Comment (qmonnet) [inline Documentation/network/kubernetes/kubeproxy-free.rst]:
```suggestion
``loadBalancer.acceleration`` to ``best-effort``. In addition, for performance
```

File: install/kubernetes/cilium/values.yaml.tmpl (hunk 16 above)
Comment (qmonnet) [reply install/kubernetes/cilium/values.yaml.tmpl]: OK, sorry I didn't realise the `acceleration` was simply left out. I didn't mean you had to uncomment it, but that's probably fine. And yes, the reformatted comment looks better to me, thank you!

File: install/kubernetes/cilium/values.yaml.tmpl (hunk 17 above)
Comment (qmonnet) [reply install/kubernetes/cilium/values.yaml.tmpl]: Not sure in this particular case, but I sometimes see them sneaking in when someone copy-paste from a Google doc or some other source that turned straight apostrophes/quotes to curly ones automatically.

File: pkg/datapath/loader/netlink.go (hunk 5 above)
Comment (ti-mo) [reply pkg/datapath/loader/netlink.go]: > Generic mode should not be used in production, it will bypass GRO engine. Fallback to tc is significantly better.

Agreed. Also, adding a retry loop will make the pending changes in #28308 a bit more painful to integrate. Making best-effort mode result in 'optional' XDP progs will result in the least friction overall.

#28308 lifts the `LinkSetXdpFdWithFlags()` here into a new `attachXDPProgram()` function and renames `attachProgram()` to `attachTCProgram()`, so the if statement here will have to move to the call site in `replaceDatapath()`. That all looks :+1:.

**Review by qmonnet — CHANGES_REQUESTED** [review]
Looks better, thanks! But now I don't understand where the new files `install/kubernetes/cilium/Chart.yaml-e`, `...-ee`, and `...-eee` come from. Were they committed by mistake?

File: install/kubernetes/cilium/values.yaml.tmpl (hunk 16 above)
Comment (qmonnet) [reply install/kubernetes/cilium/values.yaml.tmpl]: Ah, if you keep the uncommented `acceleration`, then you need to run `make -C Documentation update-helm-values` as well and commit the changes. This is what the integration tests complain about.

File: install/kubernetes/cilium/values.yaml.tmpl (hunk 17 above)
Comment (poblahblahblah) [reply install/kubernetes/cilium/values.yaml.tmpl]: Those were generated by `make -C install/kubernetes` and yes, they were committed by mistake!

File: install/kubernetes/cilium/values.yaml.tmpl (hunk 16 above)
Comment (poblahblahblah) [reply install/kubernetes/cilium/values.yaml.tmpl]: Ok - I think we are good here.

Comment (poblahblahblah) [reply install/kubernetes/cilium/values.yaml.tmpl]: Also, thank you for all of the help with this!

**Review by ti-mo — APPROVED** [review]

**Comment by ti-mo** [comment]
@poblahblahblah I've merged https://github.com/cilium/cilium/pull/28308 in the meantime, so I gave this a rebase and moved the error check to `reinitializeXDPLocked()`. I'll kick off tests as well.

**Comment by poblahblahblah** [comment]
I'm not super familiar with the failures we're seeing. Can/should these be run again?

@qmonnet you've been very generous with your time and I appreciate that. It looks like there's another helm failure. Do you have any insight into this?

**Review by nathanjsweet — APPROVED** [review]
Approval for API.

**Comment by qmonnet** [comment]
> It looks like there's another helm failure. Do you have any insight into this?

Just as the workflow output says :slightly_smiling_face::

```
HINT: to fix this, run 'make -C Documentation update-helm-values'
```

So please try running this command and committing the changes in `Documentation/helm-reference.rst` (This is a different command from `make -C install/kubernetes`).

**Comment by poblahblahblah** [comment]
> Just as the workflow output says 🙂

Can't believe I missed that. Apologies!

**Review by rgo3 — APPROVED** [review]

**Review by qmonnet — APPROVED** [review]
Thank you!

**Comment by qmonnet** [comment]
Jussi, Daniel, Nate and I are all part of sig-datapath, so I think we can skip Louis' review.

**Review by borkmann — APPROVED** [review]

**Comment by poblahblahblah** [comment]
Thank you for the help, everyone!

Great experience all around!

**Comment by julianwiedmann** [comment]
:wave: should the new `bpf-lb-acceleration` value ("best-effort") also be mentioned in the agent documentation?
https://docs.cilium.io/en/v1.15/cmdref/cilium-agent/#options

>       --bpf-lb-acceleration string                                BPF load balancing acceleration via XDP ("native", "disabled") (default "disabled")
