### PR TITLE
Use feature probes to detect kernel support for sockops

### LINKED ISSUE #10931: Use feature probes to detect kernel support for sockops
To test kernel support for sockops, we currently attempt to compile and load sockops BPF program and fail with a warning in case of error, assuming we failed because of missing kernel support.
https://github.com/cilium/cilium/blob/5958dd6fa2105cdf2c769b22568d2ad3858608d6/daemon/cmd/daemon.go#L190-L198

This behavior is non-ideal because 1) we get compilation errors in logs and 2) we may miss compilation and loading errors caused by actual bugs.

Instead, we should be using [our feature probes](https://github.com/cilium/cilium/blob/master/pkg/datapath/linux/probes/probes.go) to check for the appropriate support. Here's what's needed:
- [x] Find and list required kernel features (including [attach points used in Go code](https://github.com/cilium/cilium/blob/5958dd6fa2105cdf2c769b22568d2ad3858608d6/pkg/sockops/sockops.go#L62) and [map type used in C code](https://github.com/cilium/cilium/blob/5958dd6fa2105cdf2c769b22568d2ad3858608d6/bpf/sockops/bpf_sockops.h#L34)).
- [x] Check kernel support in [initEnv()](https://github.com/cilium/cilium/blob/7e5f30dfc1b89c1ace10c37774247a7ab2c7d8f0/daemon/cmd/daemon_main.go#L796), as we already do for e.g., `EnableNodePort`.
- [x] Update [daemon initialization](https://github.com/cilium/cilium/blob/5958dd6fa2105cdf2c769b22568d2ad3858608d6/daemon/cmd/daemon.go#L190-L198) to error in case of failure to load+compile.
- [x] Disable the [whitelisting of compilation errors in sockops tests](https://github.com/cilium/cilium/blob/6fc0b5b09d41dc4968290ced850da5c181847a40/test/k8sT/DatapathConfiguration.go#L78-L81).

### PR DESCRIPTION
**Pull request by soumynathan**
This patch probes the kernel for bpf sockops support and validates
the user configuration for SockopsEnable.

Fixes: #10931
Signed-off-by: Swaminathan Vasudevan <svasudevan@suse.com>

### CODE REVIEW

File: daemon/cmd/daemon.go [hunk 1]
```diff
@@ -188,15 +188,14 @@ func (d *Daemon) init() error {
 		}
 
 		if option.Config.SockopsEnable {
-			disableSockops := func(err error) {
-				option.Config.SockopsEnable = false
-				log.WithError(err).Warn("Disabled '--sockops-enable' due to missing BPF kernel support")
+			errSockops := func(err error) {
```
Comment (pchaigno) [inline daemon/cmd/daemon.go]: I think we can simplify this to avoid the function call given that it's now a simple error.

File: daemon/cmd/daemon.go [hunk 2]
```diff
@@ -188,15 +188,14 @@ func (d *Daemon) init() error {
...
+				log.WithError(err).Error("BPF kernel support for 'sockops' missing")
```
Comment (pchaigno) [inline daemon/cmd/daemon.go]: If we're failing here and we've properly checked for support in `initEnv()`, we're not failing because of missing kernel support. I think the error message needs to be updated to reflect this. Maybe something like `Failed to enable {Sockmsg,Sockmap}.`?

File: daemon/cmd/daemon_main.go [hunk 3]
```diff
@@ -1436,6 +1437,22 @@ func (d *Daemon) instantiateAPI() *restapi.CiliumAPI {
 	return restAPI
 }
 
+func checkifKernelSockmapOptionsConfigured() {
+	if option.Config.SockopsEnable {
+		found := false
+		if h := probes.NewProbeManager().GetHelpers("sock_ops"); h != nil {
```
Comment (pchaigno) [inline daemon/cmd/daemon_main.go]: I don't think this is enough; it looks like at least the [`msg_verdict` attach type](https://github.com/torvalds/linux/commit/4f738adba30a7cfc006f605707e7aee847ffefa0) and [the sockhash map type](https://github.com/torvalds/linux/commit/81110384441a59cff47430f20f049e69b98c17f4) were introduced after [the `sock_op` program type](https://github.com/torvalds/linux/commit/40304b2a1567fecc321f640ee4239556dd0f3ee0). Could you double check? I think we need to verify support for all of these.

File: daemon/cmd/daemon_main.go [hunk 4]
```diff
@@ -1436,6 +1437,22 @@ func (d *Daemon) instantiateAPI() *restapi.CiliumAPI {
...
+			if _, ok := h["bpf_map_lookup_elem"]; ok {
+				found = true
+			}
+		}
+		if !found {
+			msg := "BPF Sock_ops not supported by kernel."
+			log.Warn(msg + " Disabling the feature.")
```
Comment (pchaigno) [inline daemon/cmd/daemon_main.go]: We're not handling a `strict` mode as in NodePort, so we can probably get rid of the `msg` variable.

**Review by pchaigno — CHANGES_REQUESTED** [review]
Thanks @soumynathan for taking care of this!

File: daemon/cmd/daemon_main.go (hunk 3 above)
Comment (soumynathan) [reply daemon/cmd/daemon_main.go]: > I don't think this is enough; it looks like at least the [`msg_verdict` attach type](https://github.com/torvalds/linux/commit/4f738adba30a7cfc006f605707e7aee847ffefa0) and [the sockhash map type](https://github.com/torvalds/linux/commit/81110384441a59cff47430f20f049e69b98c17f4) were introduced after [the `sock_op` program type](https://github.com/torvalds/linux/commit/40304b2a1567fecc321f640ee4239556dd0f3ee0). Could you double check? I think we need to verify support for all of these.

I am not sure exactly what should be the prog and map type. Should it be 'sk_msg' instead of 'sock_ops' or 'sk_msg_redirect' and for the maps should we need to check for 'bpf_sock_hash_update'?

File: daemon/cmd/daemon_main.go (hunk 4 above)
Comment (soumynathan) [reply daemon/cmd/daemon_main.go]: will fix this.

File: daemon/cmd/daemon.go (hunk 2 above)
Comment (soumynathan) [reply daemon/cmd/daemon.go]: fixed this

File: daemon/cmd/daemon_main.go (hunk 3 above)
Comment (pchaigno) [reply daemon/cmd/daemon_main.go]: I'm expecting the sockhash map is accessed through the usual map helpers so you'll need to check the sockhash map itself is supported.

It looks like `bpftool feature` doesn't expose attach type support yet, so maybe checking for the `sk_msg` program type instead would be enough for the time being. It was introduced in the same commit as the `msg_verdict` attach type.

File: daemon/cmd/daemon.go [hunk 5]
```diff
@@ -188,15 +188,11 @@ func (d *Daemon) init() error {
...
-				option.Config.SockopsEnable = false
-				log.WithError(err).Warn("Disabled '--sockops-enable' due to missing BPF kernel support")
-			}
 			eppolicymap.CreateEPPolicyMap()
 			if err := sockops.SockmapEnable(); err != nil {
-				disableSockops(err)
+				log.WithError(err).Error("Failed to enable Sockmap")
 			} else if err := sockops.SkmsgEnable(); err != nil {
-				disableSockops(err)
+				log.WithError(err).Error("Failed to enable Sockmap")
```
Comment (pchaigno) [inline daemon/cmd/daemon.go]: This should be `Failed to enable Sockmsg`, right?

Comment (soumynathan) [reply daemon/cmd/daemon.go]: Yes will fix it.

File: daemon/cmd/daemon_main.go (hunk 3 above)
Comment (soumynathan) [reply daemon/cmd/daemon_main.go]: @pchaigno For some reason still even with 'sk_msg' the bpftool does not return any helper functions. Is there anything I am missing?

File: daemon/cmd/daemon.go [hunk 6]
```diff
@@ -193,15 +193,11 @@ func (d *Daemon) init() error {
...
-				option.Config.SockopsEnable = false
-				log.WithError(err).Warn("Disabled '--sockops-enable' due to missing BPF kernel support")
-			}
 			eppolicymap.CreateEPPolicyMap()
 			if err := sockops.SockmapEnable(); err != nil {
-				disableSockops(err)
+				log.WithError(err).Error("Failed to enable Sockmsg")
 			} else if err := sockops.SkmsgEnable(); err != nil {
-				disableSockops(err)
+				log.WithError(err).Error("Failed to enable Sockmsg")
```
Comment (aanm) [inline daemon/cmd/daemon.go:200]: The error message should be `Failed to enable Skmsg`

**Review by aanm — CHANGES_REQUESTED** [review]

File: daemon/cmd/daemon_main.go (hunk 3 above)
Comment (pchaigno) [reply daemon/cmd/daemon_main.go]: @soumynathan It does, but `bpf_sock_hash_update` is not part of those helpers:
```
$ sudo bpftool feature probe macros | grep sk_msg | grep "1$" | wc -l
20
$ sudo bpftool feature probe macros | grep sk_msg | grep bpf_sock_hash_update
#define BPF__PROG_TYPE_sk_msg__HELPER_bpf_sock_hash_update 0
```
I'm not sure why you're checking support for the `bpf_sock_hash_update` helper though. Wouldn't checking support for `sk_msg` and `sock_op` program types be enough?

**Comment by tklauser** [comment]
test-me-please

File: daemon/cmd/daemon_main.go [hunk 7]
```diff
@@ -1436,6 +1437,21 @@ func (d *Daemon) instantiateAPI() *restapi.CiliumAPI {
...
+func checkifKernelSockmapOptionsConfigured() {
+	if option.Config.SockopsEnable {
+		found := false
+		if h := probes.NewProbeManager().GetHelpers("sk_msg"); h != nil {
+			if _, ok := h["bpf_sock_hash_update"]; ok {
+				found = true
+			}
+		}
+		if !found {
+			log.Warn("BPF Sock ops not supported by kernel. Disabling the feature.")
```
Comment (qmonnet) [inline daemon/cmd/daemon_main.go]: `Disabling '--sockops-enable'` like in original message to tell exactly what option failed?

File: daemon/cmd/daemon_main.go [hunk 8]
```diff
@@ -1436,6 +1437,21 @@ func (d *Daemon) instantiateAPI() *restapi.CiliumAPI {
...
+			option.Config.SockopsEnable = false
+		}
+	}
+}
```
Comment (qmonnet) [inline daemon/cmd/daemon_main.go:1468]: Two remarks on that function.

1. Maybe find another name? Not sure what “kernel sockmap options configured” refers to. Something shorter, maybe `checkSockmapSupport()` or `initSockmapOption()` or ...

2. You could get rid of the `found` variable by doing `return nil` if you find the helper. Then the `log.Warn()` does not need to be under a `if`.

File: test/k8sT/DatapathConfiguration.go [hunk 9]
```diff
@@ -75,10 +74,6 @@ var _ = Describe("K8sDatapathConfig", func() {
 		}
 
 		blacklist := helpers.GetBadLogMessages()
-		if strings.Contains(CurrentGinkgoTestDescription().TestText, "sockops") {
-			delete(blacklist, helpers.ClangErrorsMsg)
-			delete(blacklist, helpers.ClangErrorMsg)
-		}
 		kubectl.ValidateListOfErrorsInLogs(CurrentGinkgoTestDescription().Duration, blacklist)
```
Comment (qmonnet) [inline test/k8sT/DatapathConfiguration.go]: Should `blacklist` and `kubectl.ValidateListOfErrorsInLogs()` be kept here, or should commit d7e4299bcf47 be reverted? /cc @pchaigno. Since it's no longer used, it would need a comment at the very least.

**Review by qmonnet — CHANGES_REQUESTED** [review]

File: test/k8sT/DatapathConfiguration.go (hunk 9 above)
Comment (pchaigno) [reply test/k8sT/DatapathConfiguration.go]: Commit d7e4299 shouldn't be reverted, but `ValidateListOfErrorsInLogs` can be replaced by `ValidateNoErrorsInLogs`.

File: daemon/cmd/daemon_main.go (hunk 3 above)
Comment (soumynathan) [reply daemon/cmd/daemon_main.go]: Ok, I think with the latest kernel, I am able to list out the 'bpf' helper functions for the 'sk_msg'. What are the functions that we should be checking, probably
```
                    bpf_msg_pop_data:{}
                    bpf_msg_pull_data:{}
                    bpf_msg_push_data:{}
                    bpf_msg_redirect_hash:{}
                    bpf_msg_redirect_map:{}

```
```
Apr 16 01:38:46 k8s1 cilium-agent[17595]: level=warning msg="BPF Sock ops.%smap[bpf_get_numa_node_id:{}
                    bpf_get_prandom_u32:{}
                    bpf_get_smp_processor_id:{}
                    bpf_jiffies64:{}
                    bpf_ktime_get_ns:{}
                    bpf_map_delete_elem:{}
                    bpf_map_lookup_elem:{}
                    bpf_map_peek_elem:{}
                    bpf_map_pop_elem:{}
                    bpf_map_push_elem:{}
                    bpf_map_update_elem:{}
                    bpf_msg_apply_bytes:{}
                    bpf_msg_cork_bytes:{}
                    bpf_msg_pop_data:{}
                    bpf_msg_pull_data:{}
                    bpf_msg_push_data:{}
                    bpf_msg_redirect_hash:{}
                    bpf_msg_redirect_map:{}
                    bpf_spin_lock:{}
                    bpf_spin_unlock:{}
                    bpf_tail_call:{}]

Comment (pchaigno) [reply daemon/cmd/daemon_main.go]: Our `sk_msg` program seems to only be using base helpers and `msg_redirect_hash()`. The latter was introduced at the same time as the sockhash map type so I don't think we need to check for any helper here.

File: daemon/cmd/daemon.go [hunk 10]
```diff
@@ -193,15 +193,11 @@ func (d *Daemon) init() error {
...
 
 		if option.Config.SockopsEnable {
-			disableSockops := func(err error) {
-				option.Config.SockopsEnable = false
-				log.WithError(err).Warn("Disabled '--sockops-enable' due to missing BPF kernel support")
-			}
 			eppolicymap.CreateEPPolicyMap()
 			if err := sockops.SockmapEnable(); err != nil {
-				disableSockops(err)
+				log.WithError(err).Error("Failed to enable Skmsg")
```
Comment (aanm) [inline daemon/cmd/daemon.go]: The error message should be `Failed to enable Sockmap`

**Review by aanm — CHANGES_REQUESTED** [review]

File: daemon/cmd/daemon.go (hunk 10 above)
Comment (soumynathan) [reply daemon/cmd/daemon.go]: Sure will fix it. It was originally Sockmap but based on previous review comment I have to change it to Skmsg, will revert it.

File: daemon/cmd/daemon_main.go (hunk 7 above)
Comment (soumynathan) [reply daemon/cmd/daemon_main.go]: Sure will add it back to the message.

File: daemon/cmd/daemon_main.go (hunk 8 above)
Comment (soumynathan) [reply daemon/cmd/daemon_main.go:1468]: Will address it

File: test/k8sT/DatapathConfiguration.go (hunk 9 above)
Comment (soumynathan) [reply test/k8sT/DatapathConfiguration.go]: Will address your comments.

File: daemon/cmd/daemon.go (hunk 5 above)
Comment (aanm) [reply daemon/cmd/daemon.go]: @soumynathan line 198 should be `Failed to enable Sockmap`, line 200 should be `Failed to enable Skmsg`

**Review by aanm — CHANGES_REQUESTED** [review]

**Review by aanm — APPROVED** [review]

File: test/k8sT/DatapathConfiguration.go [hunk 11]
```diff
@@ -75,11 +74,7 @@ var _ = Describe("K8sDatapathConfig", func() {
 		}
 
 		blacklist := helpers.GetBadLogMessages()
-		if strings.Contains(CurrentGinkgoTestDescription().TestText, "sockops") {
-			delete(blacklist, helpers.ClangErrorsMsg)
-			delete(blacklist, helpers.ClangErrorMsg)
-		}
-		kubectl.ValidateListOfErrorsInLogs(CurrentGinkgoTestDescription().Duration, blacklist)
+		kubectl.ValidateNoErrorsInLogs(CurrentGinkgoTestDescription().Duration, blacklist)
```
Comment (pchaigno) [inline test/k8sT/DatapathConfiguration.go]: `ValidateNoErrorsInLogs()` takes a single argument.

**Comment by aanm** [comment]
@soumynathan it seems a real failure:
```
    ./test/k8sT/... \
    ./tools/...
go: warning: "./hubble-proxy/..." matched no packages
# github.com/cilium/cilium/daemon/cmd
daemon/cmd/daemon_main.go:1463:5: too many arguments to return
	have (nil)
	want ()
# github.com/cilium/cilium/daemon/cmd
vet: daemon/cmd/daemon_main.go:1463:12: no result values expected
make[1]: *** [govet] Error 2
make[1]: Leaving directory `/home/travis/gopath/src/github.com/cilium/cilium'
make: *** [unit-tests] Error 2
The command "./.travis/build.sh" exited with 2.
```

File: daemon/cmd/daemon_main.go [hunk 12]
```diff
@@ -1455,6 +1456,18 @@ func (d *Daemon) instantiateAPI() *restapi.CiliumAPI {
 	return restAPI
 }
 
+func initSockmapOption() {
+	if option.Config.SockopsEnable {
+		if h := probes.NewProbeManager().GetHelpers("sk_msg"); h != nil {
+			if _, ok := h["bpf_msg_redirect_hash"]; ok {
+				return nil
```
Comment (qmonnet) [inline daemon/cmd/daemon_main.go]: The `return nil` here might be the cause for the build error. Simply `return` should work?

Note: Instead of having all the code of that function if the `if option.Config.SockopsEnable` block, you could also return early if the option is not set and avoid indenting all the rest:

``` go
if !option.Config.SockopsEnable {
        return
}
if h := probes.NewProbeManager()...
```
It usually makes the code a bit easier to read, I find.

Comment (pchaigno) [reply daemon/cmd/daemon_main.go]: @qmonnet The probe still needs to be fixed anyway ;-)

Comment (soumynathan) [reply daemon/cmd/daemon_main.go]: ok will fix it. @pchaigno is the probe fix that you mentioned above related to this patch or we need to handle it in a different PR>

Comment (pchaigno) [reply daemon/cmd/daemon_main.go]: Related to this patch. Please see https://github.com/cilium/cilium/pull/10941#discussion_r407888034 and https://github.com/cilium/cilium/pull/10941#discussion_r408650529.

File: daemon/cmd/daemon_main.go (hunk 3 above)
Comment (soumynathan) [reply daemon/cmd/daemon_main.go]: > I'm expecting the sockhash map is accessed through the usual map helpers so you'll need to check the sockhash map itself is supported.
> 
> It looks like `bpftool feature` doesn't expose attach type support yet, so maybe checking for the `sk_msg` program type instead would be enough for the time being. It was introduced in the same commit as the `msg_verdict` attach type.

So we are currently collecting the helper functions for 'sk_msg'? So just checking for 'sk_msg' program types would be enough?

Comment (pchaigno) [reply daemon/cmd/daemon_main.go]: @soumynathan I think you need to check support for:
1. the `sk_msg` program type;
0. the `sock_op` program type;
0. `sockhash` map type.

Comment (soumynathan) [reply daemon/cmd/daemon_main.go]: Thanks for the clarification. Will address your review comments.

**Comment by pchaigno** [comment]
test-me-please

**Review by pchaigno — APPROVED** [review]
Thanks @soumynathan! LGTM!

File: daemon/cmd/daemon_main.go [hunk 13]
```diff
@@ -1451,6 +1452,21 @@ func (d *Daemon) instantiateAPI() *restapi.CiliumAPI {
 	return restAPI
 }
 
+func initSockmapOption() {
+	if !option.Config.SockopsEnable {
+		return
+	}
+	if probes.NewProbeManager().GetMapTypes().HaveSockhashMapType {
+		k := probes.NewProbeManager().GetHelpers("sock_ops")
+		h := probes.NewProbeManager().GetHelpers("sk_msg")
```
Comment (qmonnet) [inline daemon/cmd/daemon_main.go:1461]:
```suggestion
		pm := probes.NewProbeManager()
		k := pm.GetHelpers("sock_ops")
		h := pm.GetHelpers("sk_msg")
```

Not an issue because probe results are cached, but suggestion for next time: don't create more probe managers than necessary :)

**Review by qmonnet — APPROVED** [review]
Looks good, thanks
