### PR TITLE
agent: Accept traffic to Cilium in FORWARD chain

### LINKED ISSUE #2015: NodePort broken when no of the backend endpoints are local
- All Cilium versions
- All kernel versions
- Kubernetes

### PR DESCRIPTION
**Pull request by tgraf**
kube-proxy does not change the default policy of the FORWARD chain which
means that while packets to services are properly DNAT'ed, they are
later dropped in the FORWARD chain. The issue has been resolved in
k8s#52569 and will be fixed in k8s >= 1.8. The following is a workaround
for earlier Kubernetes versions.

Also clear the masquerade bit in the FORWARD chain to skip the
masquerade rule installed by kube-proxy. All packets into cilium_host
will always be properly source PATed.

Fixes: #2015

```release-note
Accept traffic to Cilium in FORWARD chain
Also clear the masquerade bit in the FORWARD chain to skip the masquerade rule installed by kube-proxy
```

### CODE REVIEW

File: daemon/daemon.go [hunk 1]
```diff
@@ -536,38 +543,80 @@ func (d *Daemon) removeMasqRule() {
...
+		"-o", "cilium_host",
+		"-m", "comment", "--comment", "cilium: clear masq bit for pkts to cilium_host",
+		"-j", "MARK", "--set-xmark", "0x0000/0x4000"}, false); err != nil {
+		return err
+	}
+
+	// kube-proxy does not change the default policy of the FORWARD chain
+	// which means that while packets to services are properly DNAT'ed,
+	// they are later dropped in the FORWARD chain. The issue has been
+	// resolved in #52569 and will be fixed in k8s >= 1.8. The following is
```
Comment (aanm) [inline daemon/daemon.go:568]: With PR #52569 merged, will this workaround affect k8s behavior?

Comment (tgraf) [reply daemon/daemon.go:568]: The rules would not be needed in that case and they would be no-ops.
