### PR TITLE
bpf: added --bpf-lb-bypass-fib-lookup flag

### LINKED ISSUE #14911: BPF Service implementation - Gateway problem with FHRP
## Bug report

When running Cilium with the KubeProxyReplacement set to "strict". The BPF based service implementation, uses a "non standard L2 packet forwarding in a vPC environment".

So essentially what happens is that a packet comes into our k8 host (in this case a UDP packet with a DNS request) from a source MAC address that is different from the currently active FHRP peer . The response is generated and sent off directly with the source MAC address now as the destination.

In a vPC (Virtual Port Channel) environment with FHRP (in our case Cisco HSRP) the gateway has a virtual MAC address learned via ARP, so the response should have been sent towards the virtual gateway mac learned via ARP. This is what the Linux kernel normally does, and also works in the iptables implementation with kube-proxy.

There's a potential workaround we could do, by enabled "Peer Gateway" on our nexus distribution switches.

But perhaps this is something that could/should be handled by Cilium?

I believe the "correct" way to send the reply would be to use the MAC learned from default gateway here and not assume the reply should be sent towards the source MAC?

image

In the excerpt above 10.161.192.2 is the currently active HSRP peer, and 10.161.192.1 is the HSRP Gateway VIP

Some more information can also be found here, where the scenario is also described;
https://community.cisco.com/t5/networking-documents/peer-gateway-feature-on-the-nexus-7000/ta-p/3113290
https://www.dclessons.com/vpc-enhancements

Happy to assist on this in any way i can.

- Cilium version
`Client: 1.9.4 07b62884c 2021-02-03T11:45:44-08:00 go version go1.15.7 linux/amd64
Daemon: 1.9.4 07b62884c 2021-02-03T11:45:44-08:00 go version go1.15.7 linux/amd64`

- Kernel version
`Linux srvp00569 5.8.0-41-generic #46-Ubuntu SMP Mon Jan 18 16:48:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

- Orchestration system version in use
`Client Version: v1.20.2+k3s1
Server Version: v1.20.2+k3s1`

- Generate and upload a system zip:
[cilium-sysdump-20210209-155555.zip](https://github.com/cilium/cilium/files/5952535/cilium-sysdump-20210209-155555.zip)

### PR DESCRIPTION
**Pull request by skuffe**
This commit adds a boolean flag, which when enabled will cause the BPF nodeport reverse NAT handling to attempt to use a MAC address which was previously associated with the remote endpoint when sending its reply, instead of doing a FIB lookup.

If the flag is toggled off, this optimization is disabled, and a FIB lookup is always done.

This is useful if Cilium is to be used on nodes which default gateway is a FHRP VIP/MAC, such as with VRRP or Cisco's HSRP.

Fixes: #14911

Signed-off-by: Danni Skov Høglund <skuffe@pwnz.dk>

```release-note
Added --bpf-lb-bypass-fib-lookup flag, which toggles the BPF nodeport reverse NAT FIB lookup optimization
```

### CODE REVIEW

**Review by twpayne — APPROVED** [review]

File: bpf/lib/nodeport.h [hunk 1]
```diff
@@ -1649,7 +1654,8 @@ static __always_inline int rev_nodeport_lb4(struct __ctx_buff *ctx, int *ifindex
 		}
 #endif
 
-		dmac = map_lookup_elem(&NODEPORT_NEIGH4, &ip4->daddr);
+		if (fib_lookup_bypass())
+			dmac = map_lookup_elem(&NODEPORT_NEIGH4, &ip4->daddr);
```
Comment (borkmann) [inline bpf/lib/nodeport.h:1659]: IPv6 counterpart is missing.

File: pkg/defaults/defaults.go [hunk 2]
```diff
@@ -405,4 +405,7 @@ const (
 
 	// KubeProxyReplacementHealthzBindAddr is the default kubeproxyReplacement healthz server bind addr
 	KubeProxyReplacementHealthzBindAddr = ""
+
+	// EnableBPFBypassFIBLookup instructs Cilium to enable the FIB lookup bypass optimization for nodeport reverse NAT handling.
+	EnableBPFBypassFIBLookup = true
```
Comment (borkmann) [inline pkg/defaults/defaults.go:410]: should be false by default, no?

Could you also update the Documentation/gettingstarted/kubeproxy-free.rst doc so that this knob's purpose is documented for users? Thx

**Review by borkmann — CHANGES_REQUESTED** [review]

File: pkg/defaults/defaults.go (hunk 2 above)
Comment (skuffe) [reply pkg/defaults/defaults.go:410]: If the default is "true" the behavior before these changes will be retained. IE. the optimization will be done by default. That way only the users with a FHRP gateway setup will need to set this to false.

I will take a look at the doc and get that updated!

File: bpf/lib/nodeport.h (hunk 1 above)
Comment (skuffe) [reply bpf/lib/nodeport.h:1659]: Missed that woops, added it in just now.

**Comment by brb** [comment]
@skuffe Thanks. Could you squash both commits?

**Comment by skuffe** [comment]
> 
> 
> @skuffe Thanks. Could you squash both commits?

done

File: pkg/defaults/defaults.go (hunk 2 above)
Comment (skuffe) [reply pkg/defaults/defaults.go:410]: @borkmann would you prefer to have any doc related commits in the same pull, and sqashed into the same single commit?

**Comment by brb** [comment]
test-me-please

File: pkg/defaults/defaults.go (hunk 2 above)
Comment (borkmann) [reply pkg/defaults/defaults.go:410]: Ack, true, should have had my coffee first. :) Yeah, can be same commit or separate one, but within the same PR would be good.

**Comment by brb** [comment]
test-me-please

**Review by christarazi — APPROVED** [review]

**Review by brb — APPROVED** [review]
Thanks!

Have you tested both SNAT and DSR mode?

**Comment by brb** [comment]
test-me-please

**Review by kkourt — APPROVED** [review]
Thanks!

**Comment by skuffe** [comment]
> 
> 
> Thanks!
> 
> Have you tested both SNAT and DSR mode?

Yup,. tested both, as well as with externalTrafficPolicy: Cluster and externalTrafficPolicy: Local set on the service.

Would there be any more settings that could be interesting to test this against?

**Comment by brb** [comment]
> Would there be any more settings that could be interesting to test this against?

No need for more, as SNAT/DSR should be enough.

**Comment by brb** [comment]
@skuffe Could you close and then reopen the PR? GH actions got stuck, and need to be retriggered.

**Review by borkmann — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by skuffe** [comment]
Hmm, that's odd that some of those tests failed. Functionally - in the default configuration, there should be no difference from whats otherwise on the master branch.
Flaky test?

**Comment by brb** [comment]
test-runtime

**Comment by brb** [comment]
net-next hit  the flake #12511.

**Comment by brb** [comment]
test-net-next

**Comment by brb** [comment]
test-gke

**Comment by liuyuan10** [comment]
@brb If I disable bpf-lb-bypass-fib-lookup, will there be problem when the l2 entry is not available so that fib_lookup returns BPF_FIB_LKUP_RET_NO_NEIGH?

**Comment by brb** [comment]
@liuyuan10 Yep, in that case the packet will be dropped. To avoid this, for the relevant actors, we do arping when cilium-agent is configured with either ipsec or kube-proxy replacement.
