### PR TITLE
Fix compilation error when enabling Wireguard and XDP

### LINKED ISSUE #25354: Compilation failure of bpf_xdp.o when enabling Wireguard with XDP
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In conjunction with `bpf-lb-acceleration=native`,  `enable-wireguard=true` and `encrypt-node=true`, the cilium-agent crashed with the following error log. I think we need to have an agent check to reject configs with wireguard and XDP.

```
level=error msg="Failed to compile bpf_xdp.o: exit status 1" compiler-pid=107 linker-pid=108 subsys=datapath-loader
level=warning msg="In file included from /var/lib/cilium/bpf/bpf_xdp.c:37:" subsys=datapath-loader
level=warning msg="In file included from /var/lib/cilium/bpf/lib/nodeport.h:21:" subsys=datapath-loader
level=warning msg="In file included from /var/lib/cilium/bpf/lib/encap.h:11:" subsys=datapath-loader
level=warning msg="/var/lib/cilium/bpf/lib/wireguard.h:76:12: error: no member named 'mark' in 'struct xdp_md'" subsys=datapath-loader
level=warning msg="        if ((ctx->mark & MARK_MAGIC_WG_ENCRYPTED) == MARK_MAGIC_WG_ENCRYPTED)" subsys=datapath-loader
level=warning msg="             ~~~  ^" subsys=datapath-loader
level=warning msg="1 error generated." subsys=datapath-loader
level=fatal msg="Failed to compile XDP program" error="Failed to compile bpf_xdp.o: exit status 1" subsys=datapath-loader
```

### Cilium Version

v1.14.0-snapshot.2

### Kernel Version

Linux rack0-cs4 5.15.106-flatcar

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"ff2c119726cc1f8926fb0585c74b25921e866a28", GitTreeState:"clean", BuildDate:"2023-01-18T19:22:09Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"ff2c119726cc1f8926fb0585c74b25921e866a28", GitTreeState:"archive", BuildDate:"2023-02-06T09:05:12Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ysksuzuki**
This PR fixes the compilation failure of bpf_xdp.o when enabling Wireguard with XDP by adding a guard for Wireguard and XDP. Also, it shows a warning message to alert users about certain traffic(between an intermediate node and a backend node)
not being encrypted.

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

Fixes: #25354

### CODE REVIEW

**Comment by ysksuzuki** [comment]
It seems that we need to exclude cilium_wg0 from the target devices when XDP acceleration is enabled

```
level=fatal msg="Failed to compile XDP program" error="program cil_xdp_entry: attaching XDP program to interface cilium_wg0: operation not supported" subsys=datapath-loader
```

File: daemon/cmd/kube_proxy_replacement.go [hunk 1]
```diff
@@ -155,6 +155,13 @@ func initKubeProxyReplacementOptions() error {
 			return fmt.Errorf("Invalid value for --%s: %s", option.NodePortAcceleration, option.Config.NodePortAcceleration)
 		}
 
+		if option.Config.NodePortAcceleration != option.NodePortAccelerationDisabled &&
+			option.Config.EnableWireguard && option.Config.EncryptNode {
+			log.Warnf("With %s: %s and %s, %s enabled, N/S Loadbalancer traffic won't be encrypted "+
```
Comment (gentoo-root) [inline daemon/cmd/kube_proxy_replacement.go]: I think such configuration should be blocked with a fatal error, not just a warning. Therefore, the BPF compilation improvements seem to be unneeded too. There is an issue to implement that properly (https://github.com/cilium/cilium/issues/23032, item 2). Ping @brb for more insights.

**Review by gentoo-root — CHANGES_REQUESTED** [review]

File: daemon/cmd/kube_proxy_replacement.go (hunk 1 above)
Comment (ysksuzuki) [reply daemon/cmd/kube_proxy_replacement.go]: @brb and I talked about this. @brb What do you think?
https://github.com/cilium/cilium/issues/25354#issuecomment-1552473562

> I think for now we could add a warning to the agent saying that N/S LB traffic won't be encrypted, and then protect the invocation of wg_maybe_redirect_to_encrypt() in encap.h with #if __ctx_is == __ctx_skb.

Comment (ysksuzuki) [reply daemon/cmd/kube_proxy_replacement.go]: I think https://github.com/cilium/cilium/issues/23032, item 2 is a task to remove a temporary solution(not attach bpf_host on cilium_wg0). Even if we stop attaching it on cilium_wg0, we can't enable XDP with wireguard without `#if __ctx_is == __ctx_skb` guard.

There is no functionality to redirect from bpf_xdp to cilium_wg0 for now. (do native encryption or fall back to TC?)

Comment (brb) [reply daemon/cmd/kube_proxy_replacement.go]: At the moment, `--encrypt-node` is used to encrypt both - N/S LB traffic and node-to-node traffic (incl. node-to-pod and pod-to-node). If we fatal, then the latter with the XDP on won't be possible.

I think the cleanest solution would be to introduce `--encrypt-lb`, and then panic if it's enabled with the XDP. @gandro WDYT?

Comment (gandro) [reply daemon/cmd/kube_proxy_replacement.go]: Given these limitations, yeah I think an `--encrypt-lb` flag makes sense.

Comment (ysksuzuki) [reply daemon/cmd/kube_proxy_replacement.go]: `--encrypt-lb` is true, and either XDP or DSR is enabled, then we throw the fatal error? The DSR doesn't support N/S LB traffic encryption, right?

I have a feeling that SNAT mode + Tunnel  + No XDP is also not supported
https://github.com/cilium/cilium/issues/25354#issuecomment-1565456915

Comment (brb) [reply daemon/cmd/kube_proxy_replacement.go]: > --encrypt-lb is true, and either XDP or DSR is enabled, then we throw the fatal error? The DSR doesn't support N/S LB traffic encryption, right?

Yep. I can introduce the flag, or let me know if you want to do this.

> I have a feeling that SNAT mode + Tunnel + No XDP is also not supported

Yep, it's listed in https://github.com/cilium/cilium/issues/23032.

Comment (ysksuzuki) [reply daemon/cmd/kube_proxy_replacement.go]: > let me know if you want to do this.

I want to do this, but I can't test the changes to conformance-e2e. Is there any way to do it?
> It will not work with a branch from a fork (missing secrets).
https://github.com/cilium/cilium/blob/7eb40a095a5407b90afc3c489b6089c83db582f3/.github/workflows/conformance-e2e.yaml#L11-L24

We need to add `--encrypt-lb` to conformance-e2e, right?
https://github.com/cilium/cilium/pull/19401/files#diff-9e53f731e74bddbc0167de35296f2ae4325ca6ea679cc2bbd21635f3e44e7c31

Comment (ysksuzuki) [reply daemon/cmd/kube_proxy_replacement.go]: Also, we need to consider a way to opt out of encrypting LB traffic when `--encrypt-lb=false`. One possible solution is to mark packets to skip encryption at nodeport.h.

Comment (brb) [reply daemon/cmd/kube_proxy_replacement.go]: > I want to do this, but I can't test the changes to conformance-e2e. Is there any way to do it?

https://github.com/cilium/cilium/pull/25813#issuecomment-1579934285

> We need to add --encrypt-lb to conformance-e2e, right?

Only to the configurations which run with VXLAN + WG. We don't have LB XDP yet (I will add it).

> One possible solution is to mark packets to skip encryption at nodeport.h.

I think an SKB mark is a scarce resource, so let's better add if-defs :-)

Comment (ysksuzuki) [reply daemon/cmd/kube_proxy_replacement.go]: How can we distinguish LB traffic and node-to-node traffic here?
https://github.com/cilium/cilium/blob/2ec713e8e3c94ea26aae4dae8d3b359b633c53ab/bpf/lib/wireguard.h#L86-L89

Comment (brb) [reply daemon/cmd/kube_proxy_replacement.go]: Aye, you are right. At the moment, it's impossible to distinguish between LB and non-LB traffic in the linked code. We can use `skb->tc_index` for that (we already use in some places, just grep for it). Basically, set it in `nodeport_lb{4,6}()` when a backend is remote, and then in `wireguard.h` bypass the encryption if `--encrypt-lb=false` and the corresponding bit is set in the `tc_index`.

Comment (ysksuzuki) [reply daemon/cmd/kube_proxy_replacement.go]: Thanks! I will look into that

Comment (ysksuzuki) [reply daemon/cmd/kube_proxy_replacement.go]: We found out that more time is needed to introduce `encrypt-lb` flag to opt-out N/S traffic encryption completely. 
https://github.com/cilium/cilium/pull/26095#issuecomment-1588369930

Shall we proceed with this PR as it is? Or should we make changes to fatal the agent when either XDP or DSR is enabled?

Comment (brb) [reply daemon/cmd/kube_proxy_replacement.go]: After back-and-forth - let's not panic. Instead, document the limitation as this PR already does, and then log a message to users. This will allow XDP users to encrypt node-to-node traffic.

Comment (ysksuzuki) [reply daemon/cmd/kube_proxy_replacement.go]: OK, I will resolve the conflict and rebase this PR, then

**Comment by ysksuzuki** [comment]
ConformanceKindEnvoyDaemonSet seems to be stabilized by https://github.com/cilium/cilium/pull/26260

File: Documentation/security/network/encryption-wireguard.rst [hunk 2]
```diff
@@ -283,6 +283,13 @@ options:
   key in its corresponding ``CiliumNode`` CRD when a worker node's public key
   changes, given that the worker node will be unable to do so itself.
 
+  N/S Loadbalancer traffic won't be encrypted when an intermediate node redirects
+  a request to another node where a selected backend is running,
+  with the following configuration:
+
+  - LoadBalancer & NodePort XDP Acceleration
+  - Direct Server Return (DSR)
```
Comment (zacharysarah) [inline Documentation/security/network/encryption-wireguard.rst]: Edits for clarity, use present tense, use clear, plain language
```suggestion
  N/S load balancer traffic isn't encrypted when an intermediate node redirects
  a request to a different node with the following backend configuration:

  - LoadBalancer & NodePort XDP Acceleration
  - Direct Server Return (DSR)
```

**Review by zacharysarah — APPROVED** [review]
@ysksuzuki Good work. Some nits for clarity, otherwise LGTM. Approving to unblock with the understanding that changes are required prior to merge.

File: Documentation/security/network/encryption-wireguard.rst (hunk 2 above)
Comment (ysksuzuki) [reply Documentation/security/network/encryption-wireguard.rst]: Thank you for your comment! I have updated the doc accordingly.

**Comment by ysksuzuki** [comment]
K8sUpstreamNetConformance is unstable. It has been reported here
https://cilium.slack.com/archives/C7PE7V806/p1686843215310069

**Comment by ysksuzuki** [comment]
I don't see any jenkins jobs. Do we no longer run the Jenkins jobs?

**Comment by brb** [comment]
> I don't see any jenkins jobs. Do we no longer run the Jenkins jobs?

Noup, they got moved to the new `ci-ginkgo` GHA :sunglasses:

**Review by brb — APPROVED** [review]
Thanks!

**Comment by ysksuzuki** [comment]
> Noup, they got moved to the new ci-ginkgo GHA 😎

Great! It's a tremendous boost to development productivity, isn't it?

**Review by gentoo-root — APPROVED** [review]
Looks good to me, as far as you reached an agreement with @brb.

File: daemon/cmd/kube_proxy_replacement.go (hunk 1 above)
Comment (gandro) [reply daemon/cmd/kube_proxy_replacement.go]: Looks good to me! We have a soft rule that every warning should be something where the user can do something to make the warning go away. Should we mention in the warning message that to encrypt that LB traffic, one has to disable XDP? 

We have this "hint" system in other places too, see e.g. 
https://github.com/cilium/cilium/blob/8735ad61f2c2f41faa589174c5d9586b7b49dcad/pkg/wireguard/agent/agent.go#L129-L132

**Review by gandro — APPROVED** [review]

File: daemon/cmd/kube_proxy_replacement.go (hunk 1 above)
Comment (ysksuzuki) [reply daemon/cmd/kube_proxy_replacement.go]: Thank you for your comment! Is it something like this?

```go
log.WithField(logfields.Hint,
	"Disable XDP acceleration to encrypt N/S Loadbalancer traffic.").
	Warnf("With %s: %s and %s, %s enabled, N/S Loadbalancer traffic won't be encrypted "+
		"when an intermediate node redirects a request to another node where a selected backend is running.",
		option.NodePortAcceleration, option.Config.NodePortAcceleration, option.EnableWireguard, option.EncryptNode)
```

Comment (gandro) [reply daemon/cmd/kube_proxy_replacement.go]: That looks great!

**Comment by ysksuzuki** [comment]
Hit https://github.com/cilium/cilium/issues/25816

**Review by rgo3 — APPROVED** [review]
