### PR TITLE
kubectl get cep returns empty columns of policies statuses

### LINKED ISSUE #17880: kubectl get ciliumendpoint returns empty columns of INGRESS ENFORCEMENT, EGRESS ENFORCEMENT, VISIBILITY POLICY
## Bug report

**General Information**

- Cilium version (run `cilium version`)
v1.10.5

command: kubectl get cep -A
output:
```
 $ kubectl get cep -n test
NAME                        ENDPOINT ID   IDENTITY ID   INGRESS ENFORCEMENT   EGRESS ENFORCEMENT   VISIBILITY POLICY   ENDPOINT STATE   IPV4              IPV6
deathstar-c74d84667-94gsn   388           3714                                                                         ready            100.124.213.131   
deathstar-c74d84667-dkwdb   1857          3714                                                                         ready            100.124.236.142   
mediabot                    3691          17733                                                                        ready            100.124.252.187   
tiefighter                  613           16586                                                                        ready            100.124.234.76    
xwing                       2515          17533                                                                        ready            100.124.248.237   
```

### PR DESCRIPTION
**Pull request by romanspb80**
This patch will set "Status N.A." for the fields INGRESS ENFORCEMENT, EGRESS ENFORCEMENT, VISIBILITY POLICY if Cilium run with --endpoint-status disabled.

Fixes: #17880

Signed-off-by: Roman Ptitcyn romanspb@yahoo.com

### CODE REVIEW

**Review by aditighag — COMMENTED** [review]
Thanks! Can you add a snippet of the command output to the commit description with your changes?

**Review by aditighag — CHANGES_REQUESTED** [review]
For the test failures - 

BPF patchcheck: Can you add a sign-off according to the guidelines - https://docs.cilium.io/en/stable/contributing/development/contributing_guide/? 
golang generate-k8s-api: 
>Please run make generate-k8s-api and submit your changes.
Merge ability: I've added a release note.

**Comment by romanspb80** [comment]
> Thanks! Can you add a snippet of the command output to the commit description with your changes?

Thank you for the review. 
kubectl_get_cep

**Comment by romanspb80** [comment]
There are two failed tests. But I think it's not related to my changes

**Comment by aditighag** [comment]
> > Thanks! Can you add a snippet of the command output to the commit description with your changes?
> 
> Thank you for the review. kubectl_get_cep

I meant that add the command output text to the commit description, not as a screenshot in a comment. :)

**Review by aditighag — APPROVED** [review]

**Comment by gandro** [comment]
(on top hat duty) Is this really ready to merge? It seems to break the CRD definition after all, which I believe has upgrade/downgrade implications.

I'd like to get a review from an kubernetes or API codeowner, as to how to this schema changes affects the upgrade path.

File: pkg/endpoint/endpoint_status.go [hunk 1]
```diff
@@ -20,6 +21,11 @@ import (
 	"github.com/cilium/cilium/pkg/policy"
 )
 
+const (
+	// StatusNA is value of fields in the outpu of 'kubectl get cep' in case of disabled --endpoint-status
+	StatusNA = "Status N.A."
```
Comment (squeed) [inline pkg/endpoint/endpoint_status.go]: suggestion: just the string "disabled".

File: pkg/k8s/apis/cilium.io/v2/types.go [hunk 2]
```diff
@@ -141,6 +141,7 @@ type EndpointPolicyDirection struct {
 	Removing AllowedIdentityList `json:"removing,omitempty"`
 	// Deprecated
 	Adding AllowedIdentityList `json:"adding,omitempty"`
+	State  string              `json:"state,omitempty"`
```
Comment (squeed) [inline pkg/k8s/apis/cilium.io/v2/types.go]: Bikeshedding: `state` generally implies a machine-readable enumeration, rather than a freeform string. Perhaps this could be something like
```go
type EndpointPolicyState string

const (
    EndpointPolicyStateEnforcing EndpointPolicyState = "enforcing"
    EndpointPolicyStateNonEnforcing EndpointPolicyState = "non-enforcing"
    EndpointPolicyStateDisabled EndpointPolicyState = "disabled"
)
```

File: pkg/endpoint/endpoint_status.go (hunk 1 above)
Comment (romanspb80) [reply pkg/endpoint/endpoint_status.go]: > suggestion: just the string "disabled".

So it was decided when discussing the issue https://github.com/cilium/cilium/issues/17880

Comment (aanm) [reply pkg/endpoint/endpoint_status.go]: Yes, presenting it as "disabled" would suggest the user that the policy enforcement is not enabled.

File: pkg/k8s/apis/cilium.io/v2/types.go (hunk 2 above)
Comment (aanm) [reply pkg/k8s/apis/cilium.io/v2/types.go]: Yes, agreed. An enum would probably be better suitable for this case.

**Review by aanm — CHANGES_REQUESTED** [review]
As @gandro point it out, this will require a couple more changes, namely incrementing the patch value of https://github.com/cilium/cilium/blob/24a7e412b1196e829d76c22ad44613d56937d58b/pkg/k8s/apis/cilium.io/v2/register.go#L26

File: pkg/endpoint/endpoint_status.go (hunk 1 above)
Comment (romanspb80) [reply pkg/endpoint/endpoint_status.go]: OK. Thanks

File: pkg/k8s/apis/cilium.io/v2/types.go (hunk 2 above)
Comment (romanspb80) [reply pkg/k8s/apis/cilium.io/v2/types.go]: Ok. Will do

**Comment by gandro** [comment]
According to CI, there seem to be some uncommitted changes:

https://github.com/cilium/cilium/runs/7544682764?check_suite_focus=true

```
Ungenerated deepcopy source code:
diff --git a/pkg/k8s/apis/cilium.io/client/crds/v2/ciliumendpoints.yaml b/pkg/k8s/apis/cilium.io/client/crds/v2/ciliumendpoints.yaml
index bd3b4d3..1ee29c8 100644
--- a/pkg/k8s/apis/cilium.io/client/crds/v2/ciliumendpoints.yaml
+++ b/pkg/k8s/apis/cilium.io/client/crds/v2/ciliumendpoints.yaml
@@ -344,6 +344,8 @@ spec:
                           type: object
                         type: array
                       state:
+                        description: 'EndpointPolicyState defines the state of the
+                          Policy mode: "enforcing", "non-enforcing", "disabled"'
                         type: string
                     required:
                     - enforcing
@@ -433,6 +435,8 @@ spec:
                           type: object
                         type: array
                       state:
+                        description: 'EndpointPolicyState defines the state of the
+                          Policy mode: "enforcing", "non-enforcing", "disabled"'
                         type: string
                     required:
                     - enforcing
Please run make generate-k8s-api and submit your changes
```

**Comment by romanspb80** [comment]
Done.
Guys, could you please check?

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
Merging since the changes are controplane-related and not datapath.
