### PR TITLE
Fix various issues (data races, flakes) related to DaemonSuite and Endpoint related test code

### LINKED ISSUE #11955: CI: TestEndpointAddNoLabels: metrics assertion failed
```
FAIL: <autogenerated>:1: DaemonEtcdSuite.TestEndpointAddNoLabels
endpoint_test.go:150:
    c.Errorf("Metrics assertion failed on line %d for Endpoint state %s: obtained %d, expected %d",
        line, state, obtained, expected)
... Error: Metrics assertion failed on line 104 for Endpoint state waiting-to-regenerate: obtained 0, expected 1
```

```
	// Create the endpoint without any labels.
	epTemplate := getEPTemplate(c, ds.d)
	_, _, err := ds.d.createEndpoint(context.TODO(), epTemplate)
	c.Assert(err, IsNil)

	// Endpoint enters WaitingToRegenerate as it has its labels updated during
	// creation.
->	assertOnMetric(c, string(models.EndpointStateWaitingToRegenerate), 1)
```
@christarazi createEndpoint will regenerate the endpoint in the background so line 104 might fail depending on the machine load. I would suggest to add a function that waits until the metric with that particular value similar to:

https://github.com/cilium/cilium/blob/3c9c9709cf6a82da9060fa824119c24463e18c0a/pkg/kvstore/allocator/allocator_test.go#L174-L182

### PR DESCRIPTION
**Pull request by christarazi**
See commit msgs.

Fixes: https://github.com/cilium/cilium/issues/11955 (Specifically commit 355f03797ec2bd39de2819ed44f9063ee67c0863 )

### CODE REVIEW

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
All green CI on first try :tada:

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
retest-net-next

File: daemon/cmd/daemon.go [hunk 1]
```diff
@@ -91,6 +91,8 @@ const (
 // Daemon is the cilium daemon that is in charge of perform all necessary plumbing,
 // monitoring when a LXC starts.
 type Daemon struct {
+	lock.RWMutex // This mutex used to synchronize test setups. It is not used for implementation code.
```
Comment (ianvernon) [inline daemon/cmd/daemon.go]: It makes sense why this is needed in the context of how the tests are written, but it makes me sad that the tests make this a requirement - in other words, code smell.

Ideally our unit tests are not dependent on one another at all. We should ask ourselves the following questions:

* what are the pieces of the daemon (or types it depends on) which are singletons in our code base? Can we remove the need for these types? One thing comes to mind to me is `ipcache` - I had a PR out a while back which tried to remove the need for this singleton, but I never got it merged.
* are there external dependencies that the unit test suite is reliant upon (e.g., kvstore?) can we create a fake KVstore for daemon tests and instead rely upon the etcd / consul test suites to test the actual functionality?

**Comment by christarazi** [comment]
CI went green. Pushing some rewording of the commits; no functional changes...

File: daemon/cmd/daemon.go (hunk 1 above)
Comment (christarazi) [reply daemon/cmd/daemon.go]: Thanks for the feedback; this is helpful to think about going forward.

File: daemon/cmd/fqdn.go [hunk 2]
```diff
@@ -188,7 +188,10 @@ func (d *Daemon) bootstrapFQDN(restoredEndpoints *endpointRestoreState, preCache
 			namesToClean = append(namesToClean, d.dnsPoller.DNSHistory.GC(GCStart, nil)...)
 
 			// Cleanup each endpoint cache, deferring deletions via DNSZombies.
+			d.RLock()
```
Comment (nebril) [inline daemon/cmd/fqdn.go]: Why is this lock needed here? I have two problems with this line:

`GetEndpoints` uses `EndpointManager` mutex to RLock, which should be enough to not race.

This lock is used in actual implementation code, which is in contradiction to comment in `daemon/cmd/daemon.go` which reads "It is not used for implementation code."

File: daemon/cmd/daemon.go (hunk 1 above)
Comment (nebril) [inline daemon/cmd/daemon.go]: I would rather have this lock be explicitly called as `testLock` or something similar, this will make sure that we don't lose track of getting rid of it at some point and will make anyone who tries to use it outside of tests think twice (it will also be easier to spot these occurences in reviews).

**Review by nebril — CHANGES_REQUESTED** [review]

File: daemon/cmd/daemon.go (hunk 1 above)
Comment (aanm) [reply daemon/cmd/daemon.go]: @christarazi is @ianvernon 's comment going to be addressed? I didn't leave a review as I assumed his concerns would be addressed in this PR. I agree that having a `lock.RWMutex` in the daemon structure seems confusing. I'm not against the field addition itself, I'm worried that the only way to fix the tests is the addition of this field.

**Review by aanm — CHANGES_REQUESTED** [review]

File: daemon/cmd/daemon.go (hunk 1 above)
Comment (christarazi) [reply daemon/cmd/daemon.go]: Yes I've found a way to avoid relying on a mutex by taking a deeper look at the cause of the race. I'll push an updated version soon.

Comment (christarazi) [reply daemon/cmd/daemon.go]: I've found a way to avoid using a mutex: bb4712c4f9ed72fef45eef8a6d6cef34cf91dab3

File: daemon/cmd/fqdn.go (hunk 2 above)
Comment (christarazi) [reply daemon/cmd/fqdn.go]: Thanks for the review. I've found a way to avoid using a mutex: bb4712c4f9ed72fef45eef8a6d6cef34cf91dab3

File: daemon/cmd/daemon.go (hunk 1 above)
Comment (christarazi) [reply daemon/cmd/daemon.go]: I've found a way to avoid using a mutex: bb4712c

**Comment by christarazi** [comment]
test-me-please

**Review by nebril — APPROVED** [review]

File: pkg/endpointmanager/idallocator/allocator.go [hunk 3]
```diff
@@ -26,17 +27,22 @@ const (
 )
 
 var (
-	pool = idpool.NewIDPool(minID, maxID)
+	mutex = lock.RWMutex{} // Protects access to `pool` below.
+	pool  = idpool.NewIDPool(minID, maxID)
```
Comment (aanm) [inline pkg/endpointmanager/idallocator/allocator.go]: This will slow down the access of the `pool` which already has a mutex builtin. I know the mutex is protecting the variable `pool` not the contents of `pool`. This entire mutex is only being added because of `ReallocatePool` which is only used in unit tests. Since this is the case we should avoid using a mutex entirely and re-write the `ReallocatePool` function to do something like:
```
// ReallocatePool starts over with a new pool.
// This function is only used for tests and its implementation is not
// optimized for production.
func ReallocatePool() {
	for i := minID; i < maxID; i++ {
		pool.Release(i)
	}
}
```

File: pkg/policy/repository.go [hunk 4]
```diff
@@ -32,7 +32,7 @@ import (
 	"github.com/cilium/cilium/pkg/metrics"
 	"github.com/cilium/cilium/pkg/option"
 	"github.com/cilium/cilium/pkg/policy/api"
-	"github.com/cilium/proxy/go/cilium/api"
+	cilium "github.com/cilium/proxy/go/cilium/api"
```
Comment (aanm) [inline pkg/policy/repository.go]: leftover?

File: daemon/cmd/endpoint.go [hunk 5]
```diff
@@ -282,7 +282,7 @@ func (m *endpointCreationManager) DebugStatus() (output string) {
 
 // createEndpoint attempts to create the endpoint corresponding to the change
 // request that was specified.
-func (d *Daemon) createEndpoint(ctx context.Context, epTemplate *models.EndpointChangeRequest) (*endpoint.Endpoint, int, error) {
+func (d *Daemon) createEndpoint(ctx context.Context, owner regeneration.Owner, epTemplate *models.EndpointChangeRequest) (*endpoint.Endpoint, int, error) {
```
Comment (aanm) [inline daemon/cmd/endpoint.go:285]: I don't understand this change, why can't we keep the old way and still pass `d` to the functions on line 316, 412 and 497?

**Review by aanm — CHANGES_REQUESTED** [review]

**Comment by aanm** [comment]
Also I've removed all needs-backport labels at for older branches to reduce the risk of introducing regressions

File: pkg/policy/repository.go (hunk 4 above)
Comment (christarazi) [reply pkg/policy/repository.go]: Yes, will remove

File: daemon/cmd/endpoint.go (hunk 5 above)
Comment (christarazi) [reply daemon/cmd/endpoint.go:285]: This change allows us to pass `DaemonSuite` as the `owner`, because it implements the `regeneration.Owner` interface. This is useful because we can mock out certain calls that happen during the creation of the endpoint. Specifically, to fix the metrics assertion flake (as mentioned in the commit msg and in the PR body), we want to mock out the call to `(*Daemon).QueueEndpointBuild` because that causes the endpoint to transition states extremely quickly. By mocking this out, we allow the test to become more deterministic, thus less flaky. See [this comment](https://github.com/cilium/cilium/issues/11955#issuecomment-646340820) for more info on this. 

Does that make sense? Happy to clarify further.

File: pkg/endpointmanager/idallocator/allocator.go (hunk 3 above)
Comment (christarazi) [reply pkg/endpointmanager/idallocator/allocator.go]: Ah, thanks for extra insight. I agree that the mutex would slow things down. Good catch on noticing that `ReallocatePool` isn't used in implementation code. 

Will add this and remote the mutex.

File: daemon/cmd/endpoint.go (hunk 5 above)
Comment (aanm) [reply daemon/cmd/endpoint.go:285]: oh I miss that we were passing `ds` in the tests and not `ds.d`

**Review by aanm — APPROVED** [review]

File: pkg/allocator/allocator.go [hunk 6]
```diff
@@ -150,7 +150,7 @@ type Allocator struct {
 	initialListDone waitChan
 
 	// idPool maintains a pool of available ids for allocation.
-	idPool *idpool.IDPool
+	idPool idpool.IDPool
```
Comment (aanm) [inline pkg/allocator/allocator.go:153]: I don't think this changes anything WRT go's GC because the variable is only initialized once when the agent starts.

Comment (christarazi) [reply pkg/allocator/allocator.go:153]: True; in this specific case, the impact in minimal. The general rule I try to follow is to only make a variable a pointer if it must be one. I noticed while looking at this code, it didn't need to be a pointer, and changing it so was quite trivial. I think moving forward we should also consider reducing our usage of pointers. Over time, we may find that we improve the performance of Cilium because it'll reduce the load on the GC.

**Comment by christarazi** [comment]
test-me-please
