### PR TITLE
operator: Wait for CRDs before running informers

### LINKED ISSUE #10814: Errors while starting operator
Starting operator in latest master when the operator is deployed at the same time as the cilium-agent and the CRDs are not registered yet

```
level=error msg=k8sError error="github.com/cilium/cilium/operator/k8s_identity.go:133: Failed to list *v2.CiliumIdentity: the server could not find the requested resource (get ciliumidentities.cilium.io)" subsys=k8s
level=error msg=k8sError error="github.com/cilium/cilium/operator/cilium_node.go:84: Failed to list *v2.CiliumNode: the server could not find the requested resource (get ciliumnodes.cilium.io)" subsys=k8s
level=error msg=k8sError error="github.com/cilium/cilium/operator/cilium_node.go:84: Failed to list *v2.CiliumNode: the server could not find the requested resource (get ciliumnodes.cilium.io)" subsys=k8s
level=error msg=k8sError error="github.com/cilium/cilium/operator/k8s_identity.go:133: Failed to list *v2.CiliumIdentity: the server could not find the requested resource (get ciliumidentities.cilium.io)" subsys=k8s
```

### PR DESCRIPTION
**Pull request by vadorovsky**
Running CRD informers was sometimes resulting in errors when
cilium-operator was launched before cilium-agent created CRDs. This
change adds the waitForCRD() function which waits for the given CRD with
the timeout.

Fixes: #10814

Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>

```release-note
cilium-operator: Wait for CRDs before running Informers
```

### CODE REVIEW

**Comment by mrostecki** [comment]
test-me-please

File: operator/crd.go [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+// CRDBackoff is the backoff for initial creation of CRDs by cilium-agent.
+var CRDBackoff = wait.Backoff{
+	Duration: 30 * time.Second,
+	Steps:    15,
+	Factor:   1.0,
+	Jitter:   0.1,
+}
+
+func getCRD(client clientset.Interface, CRDName string) error {
+	_, err := client.ApiextensionsV1beta1().CustomResourceDefinitions().Get(context.TODO(), CRDName, metav1.GetOptions{})
```
Comment (aanm) [inline operator/crd.go]: it needs the following in the clusterrole of cilium-operator

```
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
```

File: operator/crd.go [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+	return err
+}
+
+func waitForCRDWithBackoff(client clientset.Interface, backoff wait.Backoff, CRDname string) error {
+	if err := retry.OnError(retry.DefaultBackoff, k8serrors.IsNotFound, func() error {
+		return getCRD(client, CRDname)
+	}); err != nil {
+		return errors.Wrapf(err, "timeout exceeded when waiting for CRD %s", CRDname)
+	}
+	return nil
```
Comment (aanm) [inline operator/crd.go]: couldn't this be replaced with a cilium controller? It will also retry on error and we don't need to import more external packages.

**Review by aanm — CHANGES_REQUESTED** [review]

**Comment by mrostecki** [comment]
test-me-please

File: operator/crd.go (hunk 2 above)
Comment (vadorovsky) [reply operator/crd.go]: Cilium controller seems to have much more complex purpose than just simple "retry on error" action which I need here? I can try to think of the way of reusing parts of it, or rewriting it a bit in a way it will be easy to use for CRD watching.

File: operator/crd.go (hunk 1 above)
Comment (vadorovsky) [reply operator/crd.go]: Thanks! I was testing it on vagrant, where operator is managed by systemd... I should've try minikube and microk8s as well.

File: operator/crd.go (hunk 2 above)
Comment (vadorovsky) [reply operator/crd.go]: Or nevermind, sorry, I think I can use pkg/controller without any changes.

**Comment by mrostecki** [comment]
test-me-please

**Comment by aanm** [comment]
please wait on https://github.com/cilium/cilium/pull/11083 to be merged first.

File: operator/main.go [hunk 3]
```diff
@@ -194,7 +205,9 @@ func runOperator(cmd *cobra.Command) {
 			log.WithError(err).Fatal("Unable to start Azure allocator")
 		}
 
-		startSynchronizingCiliumNodes(nodeManager)
+		if err := startSynchronizingCiliumNodes(nodeManager); err != nil {
+			log.WithError(err).Fatal("Unable to start synchronizing Cilium nodes")
+		}
```
Comment (christarazi) [inline operator/main.go]: The code in this switch statement is basically the same except for the cloud provider. We can eliminate the duplication by extracting the minimal necessary information from the switch statement and then proceeding outside the switch statement with the generic operation, like calling `Init()`, and the rest. 

For example, it seems like the only piece of info we need out of this is the specific allocator and provider.

```
ipamAllocatorAWS, providerBuiltin := allocatorProviders["aws"]
```
```
ipamAllocatorAzure, providerBuiltin := allocatorProviders["azure"] 
```

File: operator/crd.go [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+	"time"
+
+	"github.com/cilium/cilium/pkg/controller"
+
+	"github.com/pkg/errors"
+	"k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset"
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+)
+
+func getCRD(client clientset.Interface, CRDName string) error {
```
Comment (christarazi) [inline operator/crd.go]: Nit: `CRDName` can just be `name` or `crdName`.

File: operator/crd.go [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+		log.WithError(err).Debugf("Could not get CRD %s from Kubernetes apiserver, retrying", CRDName)
+		return err
+	}
+	log.Debugf("Check of CRD %s successful", CRDName)
+	return nil
+}
+
+// waitForCRD waits for the given CRD to be available until the timeout defined
+// by CRDRetry. Returns an error when timeout exceeded.
+func waitForCRD(client clientset.Interface, CRDname string) error {
```
Comment (christarazi) [inline operator/crd.go]: Nit: `CRDName` can just be `name` or `crdName`.

File: operator/crd.go [hunk 6]
```diff
@@ -0,0 +1,54 @@
...
+	ctrlMgr := controller.NewManager()
+	ctrlName := fmt.Sprintf("wait-for-crd-%s", CRDname)
```
Comment (christarazi) [inline operator/crd.go]: I think this can just be a simple concatenation instead of a call to `Sprintf`. Helps remove an import of `fmt` :smile:

**Review by christarazi — CHANGES_REQUESTED** [review]
Thanks for the PR! Looks good, aside for a few minor comments

File: operator/main.go (hunk 3 above)
Comment (vadorovsky) [reply operator/main.go]: The code has changed during the last rebase, everything is handled in the one case now,

File: operator/crd.go (hunk 4 above)
Comment (vadorovsky) [reply operator/crd.go]: done

File: operator/crd.go (hunk 5 above)
Comment (vadorovsky) [reply operator/crd.go]: done

File: operator/crd.go (hunk 6 above)
Comment (vadorovsky) [reply operator/crd.go]: done

**Comment by mrostecki** [comment]
test-me-please

File: operator/crd.go [hunk 7]
```diff
@@ -0,0 +1,53 @@
...
+		RunInterval: 15 * time.Second,
+		DoFunc: func(ctx context.Context) error {
+			return getCRD(client, name)
+		},
+	})
+	if err := ctrlMgr.RemoveControllerAndWait(ctrlName); err != nil {
+		return errors.Wrapf(err, "Could not wait for CRD %s status", name)
+	}
+	return nil
+}
```
Comment (aanm) [inline operator/crd.go]: I'm a little lost by this function. It seems it will create a controller and then will remove it. Is this intended?

File: operator/k8s_identity.go [hunk 8]
```diff
@@ -169,5 +169,9 @@ func startManagingK8sIdentities() {
 		identityStore,
 	)
 
+	if err := waitForCRD(apiextensionsK8sClient, "ciliumidentities.cilium.io"); err != nil {
```
Comment (aanm) [inline operator/k8s_identity.go]: Isn't `ciliumidentities` + `.cilium.io` defined anywhere?

File: operator/cnp_event.go [hunk 9]
```diff
@@ -136,6 +136,10 @@ func enableCNPWatcher() error {
 		cnpConverterFunc,
 		cnpStore,
 	)
+
+	if err := waitForCRD(apiextensionsK8sClient, "ciliumnetworkpolicies.cilium.io"); err != nil {
```
Comment (aanm) [inline operator/cnp_event.go]: Isn't `ciliumnetworkpolicies` + `.cilium.io` defined anywhere?

File: operator/cilium_node.go [hunk 10]
```diff
@@ -72,12 +72,17 @@ func startSynchronizingCiliumNodes(nodeManager allocator.NodeEventHandler) {
 		k8s.ConvertToCiliumNode,
 	)
 
+	if err := waitForCRD(apiextensionsK8sClient, "ciliumnodes.cilium.io"); err != nil {
```
Comment (aanm) [inline operator/cilium_node.go]: Isn't `ciliumnodes` + `.cilium.io` defined anywhere?

**Review by aanm — CHANGES_REQUESTED** [review]

File: operator/crd.go (hunk 7 above)
Comment (vadorovsky) [reply operator/crd.go]: Yes - my intention is to initially wait until we can get the CRD and then remove the contoller once we get it successfully. I don't see any need to have that controller running afterwards.

File: operator/k8s_identity.go (hunk 8 above)
Comment (vadorovsky) [reply operator/k8s_identity.go]: `ciliumidentities` is not defined anywhere as a global variable, it's defined as a local variable here:

https://github.com/cilium/cilium/blob/3a72ffc4f1808c29077d5ebb645c1b28af257996/pkg/k8s/apis/cilium.io/v2/client/register.go#L463-L479

But defining CRD names as global (const) variables is a good idea, I can do that.

File: operator/cnp_event.go (hunk 9 above)
Comment (vadorovsky) [reply operator/cnp_event.go]: ditto

File: operator/cilium_node.go (hunk 10 above)
Comment (vadorovsky) [reply operator/cilium_node.go]: ditto

File: operator/k8s_identity.go (hunk 8 above)
Comment (vadorovsky) [reply operator/k8s_identity.go]: Seems like `pkg/k8s/apis/cilium.io/const.go` is a good place for global variables. I will move them there.

**Comment by mrostecki** [comment]
test-me-please

**Comment by mrostecki** [comment]
test-me-please

**Review by christarazi — APPROVED** [review]

File: operator/crd.go (hunk 7 above)
Comment (aanm) [reply operator/crd.go]: Right but line 43 is non blocking, i.e. the controller will be updated and removed immediately.

**Review by aanm — CHANGES_REQUESTED** [review]

File: operator/crd.go (hunk 7 above)
Comment (vadorovsky) [reply operator/crd.go]: `RemoveControllerAndWait` will wait until the controller has completed and as far as I understand, it's blocking. That's my log from cilium-operator:

```
May 18 15:43:43 k8s1 cilium-operator[18801]: level=debug msg="Getting CRD ciliumnetworkpolicies.cilium.io from Kubernetes apiserver" subsys=cilium-operator
May 18 15:43:43 k8s1 cilium-operator[18801]: level=debug msg="Controller func execution time: 1.336µs" name=kvstore-sync-store-cilium/state/cnpstatuses/v2 subsys=controller uuid=5a5870de-991e-11ea-820a-08002737a2e9
May 18 15:43:43 k8s1 cilium-operator[18801]: level=debug msg="Controller run succeeded; waiting for next controller update or stop" name=kvstore-sync-store-cilium/state/cnpstatuses/v2 subsys=controller uuid=5a5870de-991e-11ea-820a-08002737a2e9
May 18 15:43:43 k8s1 cilium-operator[18801]: level=debug msg="Starting watcher..." config=/var/lib/cilium/etcd-config.yml endpoints="[https://192.168.33.11:2379]" subsys=kvstore watcher=cnpStatusWatcher
May 18 15:43:43 k8s1 cilium-operator[18801]: level=debug msg="Distributed lock successful, etcd has quorum" config=/var/lib/cilium/etcd-config.yml endpoints="[https://192.168.33.11:2379]" subsys=kvstore
May 18 15:43:43 k8s1 cilium-operator[18801]: level=debug msg="List response from etcd len=0: &{Header:cluster_id:6438720328480595214 member_id:1326427008500738502 revision:408 raft_term:2  Kvs:[] More:false Count:0}" config=/var/lib/cilium/etcd-config.yml endpoints="[https://192.168.33.11:2379]" prefix=cilium/state/cnpstatuses/v2 subsys=kvstore watcher=cnpStatusWatcher
May 18 15:43:43 k8s1 cilium-operator[18801]: level=debug msg="Starting to watch a prefix" config=/var/lib/cilium/etcd-config.yml endpoints="[https://192.168.33.11:2379]" prefix=cilium/state/cnpstatuses/v2 revision=409 subsys=kvstore watcher=cnpStatusWatcher
May 18 15:43:43 k8s1 cilium-operator[18801]: level=debug msg="Check of CRD ciliumnetworkpolicies.cilium.io successful" subsys=cilium-operator
May 18 15:43:43 k8s1 cilium-operator[18801]: level=debug msg="Controller func execution time: 55.037927ms" name=wait-for-crd-ciliumnetworkpolicies.cilium.io subsys=controller uuid=5a58728f-991e-11ea-820a-08002737a2e9
May 18 15:43:43 k8s1 cilium-operator[18801]: level=debug msg="Shutting down controller" name=wait-for-crd-ciliumnetworkpolicies.cilium.io subsys=controller uuid=5a58728f-991e-11ea-820a-08002737a2e9
```

Which seems to prove that the controller was blocked until it finished its successful iteration.

But on the other hand, it's the first time when I ever use the controller, so I might be wrong.

**Comment by mrostecki** [comment]
test-me-please

File: operator/crd.go (hunk 7 above)
Comment (vadorovsky) [reply operator/crd.go]: Anyway, if I'm wrong, I'm open for suggestions how should I use the controller to wait until it's first successful run.

**Comment by mrostecki** [comment]
test-me-please

File: operator/crd.go (hunk 7 above)
Comment (vadorovsky) [reply operator/crd.go]: Or no, sorry, I'm wrong. There is no guarantee that there was at least one successful iteration of controller when using `RemoveControllerAndWait`. I need to come up with some solution which will ensure at least one success.

**Comment by mrostecki** [comment]
test-me-please

**Comment by mrostecki** [comment]
test-me-please

File: operator/crd.go (hunk 7 above)
Comment (vadorovsky) [reply operator/crd.go]: Should be fixed now by 62ce6814d6429b79d2ce0a351a123f28bac68124

**Comment by mrostecki** [comment]
@aanm PTAL again. I made changes in the controller module to allow to wait for the first success with a timeout - 62ce6814d6429b79d2ce0a351a123f28bac68124

So now waiting with retries and intervals for CRDs should be blocking.

**Comment by mrostecki** [comment]
netlify failure seems unrelated https://app.netlify.com/sites/cilium-docs/deploys/5ecbb5a90a77de0007bb5fd9

File: pkg/controller/controller.go [hunk 11]
```diff
@@ -259,18 +264,42 @@ func (c *Controller) runController() {
...
-			// If we receive a signal on both channels c.stop and c.update,
-			// golang will pick either c.stop or c.update randomly.
+			// If we receive a signal both on c.update and any other channel,
+			// golang will pick either c.update or the other channel randomly.
 			// This select will make sure we don't execute the controller
 			// while we are shutting down.
 			select {
 			case <-c.stop:
 				goto shutdown
+			case <-c.stopOnSuccessCh:
```
Comment (vadorovsky) [inline pkg/controller/controller.go]: I don't like the fact that I had to copy the whole `case <-c.stopOnSuccessCh` section here, but I had no better idea. I'm open for suggestions.

**Comment by mrostecki** [comment]
test-me-please

**Comment by mrostecki** [comment]
test-me-please

File: pkg/controller/controller.go (hunk 11 above)
Comment (christarazi) [reply pkg/controller/controller.go]: One simpler approach would be to put the `case` body into a helper function. I'm not sure what would happen to the `goto` statements, but you'll likely need to refactor the `goto`s out in order to use this approach. Just an idea. :)

Comment (christarazi) [reply pkg/controller/controller.go]: If I understand correctly, the code written here depends on reading from channels in some order. Golang's `select` statement randomness is causing you to nest the `select` statement and duplicate the case body into another case, because you can't know in which order the channels became ready.

Another approach could be to separate out the `select` statement for only the use of reading from `c.stopOnSuccessCh` (assuming that's the one you want to give priority to). Then you could keep the other `select` with `c.update`'s case body slimmer (without the duplicated `c.stopOnSuccessCh` case) in there. Does that make sense? Happy to clarify :)

File: pkg/k8s/apis/cilium.io/register.go [hunk 12]
```diff
@@ -15,6 +15,86 @@
...
+
+	// CustomResourceDefinitionVersion is the current version of the resource
+	CustomResourceDefinitionVersion = "v2"
+
+	// CustomResourceDefinitionSchemaVersion is semver-conformant version of CRD schema
+	// Used to determine if CRD needs to be updated in cluster
+	CustomResourceDefinitionSchemaVersion = "1.20"
+
+	// CustomResourceDefinitionSchemaVersionKey is key to label which holds the CRD schema version
+	CustomResourceDefinitionSchemaVersionKey = "io.cilium.k8s.crd.schema.version"
```
Comment (aanm) [inline pkg/k8s/apis/cilium.io/register.go]: At list these consts are bounded to a particular version so they should belong to at least `...cilium.io/v2/register.go`

File: operator/crd.go [hunk 13]
```diff
@@ -0,0 +1,62 @@
...
+
+// WaitForCRD waits for the given CRD to be available until the timeout defined
+// by CRDRetry. Returns an error when timeout exceeded.
+func WaitForCRD(client clientset.Interface, name string) error {
+	return waitForCRD(client, name, defaultRunInterval, defaultTimeout)
+}
```
Comment (aanm) [inline operator/crd.go]: Sorry, I gave a little more thought to this section. Instead of poling we could do something similar to this https://github.com/kubernetes/kubernetes/pull/88935/commits/e053fdd08ae00d1bff3dd42a2c034f4810f8a55d#diff-934760ea1a4e195e49bcd10625cf4e46R384 where we would watch and wait until that particular CRD is populated. This wouldn't require any changes in the controller code.

File: install/kubernetes/cilium/charts/operator/templates/clusterrole.yaml [hunk 14]
```diff
@@ -53,3 +53,9 @@ rules:
   - ciliumidentities/status
   verbs:
   - '*'
+- apiGroups:
+  - apiextensions.k8s.io
+  resources:
+  - customresourcedefinitions
+  verbs:
+  - get
```
Comment (aanm) [inline install/kubernetes/cilium/charts/operator/templates/clusterrole.yaml:61]: Based on the suggestions we would need to add `list` and `watch` verbs here.

File: install/kubernetes/quick-install.yaml [hunk 15]
```diff
@@ -317,6 +317,12 @@ rules:
   - ciliumidentities/status
   verbs:
   - '*'
+- apiGroups:
+  - apiextensions.k8s.io
+  resources:
+  - customresourcedefinitions
+  verbs:
+  - get
```
Comment (aanm) [inline install/kubernetes/quick-install.yaml:308]: Based on the suggestions we would need to add `list` and `watch` verbs here.

**Review by aanm — CHANGES_REQUESTED** [review]

File: pkg/controller/controller.go (hunk 11 above)
Comment (vadorovsky) [reply pkg/controller/controller.go]: Thanks for suggestions! :) By following @aanm's suggestion, I don't need nay changes in controller anymore.

File: pkg/k8s/apis/cilium.io/register.go (hunk 12 above)
Comment (vadorovsky) [reply pkg/k8s/apis/cilium.io/register.go]: Done.

File: operator/crd.go (hunk 13 above)
Comment (vadorovsky) [reply operator/crd.go]: Good idea! Done.

File: install/kubernetes/cilium/charts/operator/templates/clusterrole.yaml (hunk 14 above)
Comment (vadorovsky) [reply install/kubernetes/cilium/charts/operator/templates/clusterrole.yaml:61]: Done

File: install/kubernetes/quick-install.yaml (hunk 15 above)
Comment (vadorovsky) [reply install/kubernetes/quick-install.yaml:308]: Done

**Comment by mrostecki** [comment]
test-me-please

**Comment by mrostecki** [comment]
@aanm @christarazi I removed all changes in the controller module and used a watcher instead. Thanks for review!

**Review by christarazi — APPROVED** [review]

File: operator/crd.go [hunk 16]
```diff
@@ -0,0 +1,83 @@
...
+const (
+	defaultTimeout = 300 * time.Second
+)
+
+func waitForCRD(client clientset.Interface, name string, timeout time.Duration) error {
+	ctx, cancelFunc := context.WithTimeout(context.Background(), timeout)
+	defer cancelFunc()
+
+	selector := fields.OneTermEqualSelector("metadata.name", name).String()
+	fmt.Println(selector)
```
Comment (aanm) [inline operator/crd.go]: leftover

File: operator/crd.go [hunk 17]
```diff
@@ -0,0 +1,83 @@
...
+			return false, errors.New("CRD not found")
+		}
+		return false, ErrInvalidTypeCRD
+	}
+	ev, err := toolswatch.UntilWithSync(ctx, w, &v1beta1.CustomResourceDefinition{}, nil, cond)
+	if err != nil {
+		return errors.Wrapf(err, "timeout waiting for CRD %s", name)
+	}
+	if crd, ok := ev.Object.(*v1beta1.CustomResourceDefinition); ok {
+		fmt.Println(crd)
```
Comment (aanm) [inline operator/crd.go]: leftover

**Review by aanm — CHANGES_REQUESTED** [review]

**Comment by mrostecki** [comment]
test-me-please

**Comment by mrostecki** [comment]
test-me-please

File: pkg/policy/groups/helpers.go [hunk 18]
```diff
@@ -20,10 +20,9 @@ import (
 
 	"github.com/cilium/cilium/pkg/k8s"
 	cilium_v2 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2"
-	cilium_client_v2 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2/client"
 	"github.com/cilium/cilium/pkg/policy/api"
 
-	"k8s.io/apimachinery/pkg/apis/meta/v1"
+	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
```
Comment (aanm) [inline pkg/policy/groups/helpers.go]: unnecessary change

File: operator/k8s_identity.go [hunk 19]
```diff
@@ -119,13 +119,13 @@ func startCRDIdentityGC() {
 		})
 }
 
-func startManagingK8sIdentities() {
+func startManagingK8sIdentities() error {
```
Comment (aanm) [inline operator/k8s_identity.go]: can you pass `apiextensionsK8sClient` as an argument of this function and add documentation stating the function will wait until the creation of the CRD for `CiliumIdentities`?

File: operator/k8s_identity.go [hunk 20]
```diff
@@ -22,12 +22,12 @@ import (
 	operatorOption "github.com/cilium/cilium/operator/option"
 	"github.com/cilium/cilium/operator/watchers"
 	"github.com/cilium/cilium/pkg/controller"
-	"github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2"
+	v2 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2"
```
Comment (aanm) [inline operator/k8s_identity.go]: unnecessary change

File: operator/k8s_identity.go [hunk 21]
```diff
@@ -22,12 +22,12 @@ import (
...
 	"github.com/cilium/cilium/pkg/k8s/informer"
 	"github.com/cilium/cilium/pkg/logging/logfields"
 
 	"github.com/sirupsen/logrus"
-	"k8s.io/api/core/v1"
+	v1 "k8s.io/api/core/v1"
```
Comment (aanm) [inline operator/k8s_identity.go]: unnecessary change

File: operator/errors.go [hunk 22]
```diff
@@ -0,0 +1,23 @@
...
+// Unless required by applicable law or agreed to in writing, software
+// distributed under the License is distributed on an "AS IS" BASIS,
+// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+// See the License for the specific language governing permissions and
+// limitations under the License.
+
+package main
+
+import (
+	"github.com/pkg/errors"
```
Comment (aanm) [inline operator/errors.go]: `s+github.com/pkg/errors+errors`

File: operator/crd.go [hunk 23]
```diff
@@ -0,0 +1,80 @@
...
+	toolswatch "k8s.io/client-go/tools/watch"
+)
+
+const (
+	defaultTimeout = 300 * time.Second
+)
+
+func waitForCRD(client clientset.Interface, name string, timeout time.Duration) error {
+	ctx, cancelFunc := context.WithTimeout(context.Background(), timeout)
+	defer cancelFunc()
```
Comment (aanm) [inline operator/crd.go]: Instead of passing `timeout time.Duration` can't the function receive the context instead?

File: operator/crd.go [hunk 24]
```diff
@@ -0,0 +1,80 @@
...
+// See the License for the specific language governing permissions and
+// limitations under the License.
+
+package main
+
+import (
+	"context"
+	"time"
+
+	"github.com/pkg/errors"
```
Comment (aanm) [inline operator/crd.go]: `s+github.com/pkg/errors+errors`

File: operator/cnp_event.go [hunk 25]
```diff
@@ -27,7 +27,7 @@ import (
 	"github.com/cilium/cilium/pkg/metrics"
 	"github.com/cilium/cilium/pkg/policy/groups"
 
-	"k8s.io/api/core/v1"
+	v1 "k8s.io/api/core/v1"
```
Comment (aanm) [inline operator/cnp_event.go]: unnecessary change

File: operator/cnp_event.go [hunk 26]
```diff
@@ -27,7 +27,7 @@ import (
...
 	"k8s.io/apimachinery/pkg/fields"
 	"k8s.io/apimachinery/pkg/util/runtime"
 	"k8s.io/apimachinery/pkg/util/wait"
```
Comment (aanm) [inline operator/cnp_event.go:34]: line49: can you pass `apiextensionsK8sClient` as an argument of this function and add documentation stating the function will wait until the creation of the CRD for `CiliumNetworkPolicies`?

File: operator/cilium_node.go [hunk 27]
```diff
@@ -19,11 +19,11 @@ import (
 
 	"github.com/cilium/cilium/pkg/ipam/allocator"
 	"github.com/cilium/cilium/pkg/k8s"
-	"github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2"
+	v2 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2"
 	"github.com/cilium/cilium/pkg/k8s/informer"
 	k8sversion "github.com/cilium/cilium/pkg/k8s/version"
 
-	"k8s.io/api/core/v1"
+	v1 "k8s.io/api/core/v1"
```
Comment (aanm) [inline operator/cilium_node.go]: unnecessary change

File: operator/cilium_node.go [hunk 28]
```diff
@@ -19,11 +19,11 @@ import (
 
 	"github.com/cilium/cilium/pkg/ipam/allocator"
 	"github.com/cilium/cilium/pkg/k8s"
-	"github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2"
+	v2 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2"
```
Comment (aanm) [inline operator/cilium_node.go]: unnecessary change

File: operator/cilium_node.go [hunk 29]
```diff
@@ -32,15 +32,15 @@ import (
 
 var k8sCiliumNodesCacheSynced = make(chan struct{})
 
-func startSynchronizingCiliumNodes(nodeManager allocator.NodeEventHandler) {
+func startSynchronizingCiliumNodes(nodeManager allocator.NodeEventHandler) error {
```
Comment (aanm) [inline operator/cilium_node.go]: can you pass `apiextensionsK8sClient` as an argument of this function and add documentation stating the function will wait until the creation of the CRD for `CiliumNodes`?

File: operator/crd.go [hunk 30]
```diff
@@ -0,0 +1,80 @@
...
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	"k8s.io/apimachinery/pkg/fields"
+	"k8s.io/apimachinery/pkg/runtime"
+	"k8s.io/apimachinery/pkg/watch"
+	"k8s.io/client-go/tools/cache"
+	toolswatch "k8s.io/client-go/tools/watch"
+)
+
+const (
+	defaultTimeout = 300 * time.Second
```
Comment (aanm) [inline operator/crd.go]: Any reason for the 5 minutes? I think this can be decreased to `2 * time.Minute`.

**Review by aanm — CHANGES_REQUESTED** [review]

File: operator/k8s_identity.go (hunk 19 above)
Comment (vadorovsky) [reply operator/k8s_identity.go]: ~Why should I pass a global variable as an argument? `ciliumK8sClient` is a global variable too and it's used straight in `k8s_identity.go`, so I just wanted to be consistent. Keeping k8s clients as globals seems to be an approach used in the whole Cilium. Having one client (`ciliumK8sClient`) as a global, and the other client (`apiextensionsK8sClient`) as a local variable in `main` being passed seems a bit odd to me.~

~I agree about adding a documentation/comment to the function.~

aanm is right, I will fix that

File: pkg/policy/groups/helpers.go (hunk 18 above)
Comment (vadorovsky) [reply pkg/policy/groups/helpers.go]: I don't know why, but my gofmt/golint hook always adds that. :( And I've seen those `v1 "k8s.io/foo/v1"` imports in many places and even in Cilium. I can't google why this is happening. I guess I have to disable lint hook on save for now.

Comment (vadorovsky) [reply pkg/policy/groups/helpers.go]: OK, that was because of `goimports`. I will stop using it for Cilium.

Comment (vadorovsky) [reply pkg/policy/groups/helpers.go]: Fixed

**Comment by mrostecki** [comment]
test-me-please

File: operator/k8s_identity.go (hunk 19 above)
Comment (vadorovsky) [reply operator/k8s_identity.go]: done

File: operator/cnp_event.go (hunk 26 above)
Comment (vadorovsky) [reply operator/cnp_event.go:34]: done

File: operator/cilium_node.go (hunk 29 above)
Comment (vadorovsky) [reply operator/cilium_node.go]: done

**Comment by mrostecki** [comment]
test-me-please

**Comment by mrostecki** [comment]
Doesn't look like a flake observed anywhere else:

```
16:35:47  • Failure [78.397 seconds]
16:35:47  K8sServicesTest
16:35:47  /home/jenkins/workspace/Cilium-PR-K8s-oldest-net-next/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:476
16:35:47    Checks service across nodes
16:35:47    /home/jenkins/workspace/Cilium-PR-K8s-oldest-net-next/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:476
16:35:47      Tests NodePort BPF
16:35:47      /home/jenkins/workspace/Cilium-PR-K8s-oldest-net-next/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:476
16:35:47        Tests with TC, direct routing and Hybrid [It]
16:35:47        /home/jenkins/workspace/Cilium-PR-K8s-oldest-net-next/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:512
16:35:47  
16:35:47        Request from k8s1 to service tftp://10.98.65.141:10069/hello failed
[2020-06-15T14:35:47.212Z]       Expected command: kubectl exec -n kube-system log-gatherer-ff75s -- /bin/bash -c 'fails=""; id=$RANDOM; for i in $(seq 1 10); do if curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 tftp://10.98.65.141:10069/hello -H "User-Agent: cilium-test-$id/$i"; then echo "Test round $id/$i exit code: $?"; else fails=$fails:$id/$i=$?; fi; done; if [ -n "$fails" ]; then echo "failed: $fails"; fi; cnt="${fails//[^:]}"; if [ ${#cnt} -gt 0 ]; then exit 42; fi' 
[2020-06-15T14:35:47.212Z]       To succeed, but it failed:
[2020-06-15T14:35:47.212Z]       Exitcode: 42 
[2020-06-15T14:35:47.212Z]       Stdout:
[2020-06-15T14:35:47.212Z]        	 
[2020-06-15T14:35:47.212Z]       	 Hostname: testds-lc54h
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       	 Request Information:
[2020-06-15T14:35:47.212Z]       	 	client_address=192.168.36.11
[2020-06-15T14:35:47.212Z]       	 	client_port=60970
[2020-06-15T14:35:47.212Z]       	 	real path=/hello
[2020-06-15T14:35:47.212Z]       	 	request_scheme=tftp
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       	 Test round 8698/1 exit code: 0
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       	 Hostname: testds-sbckv
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       	 Request Information:
[2020-06-15T14:35:47.212Z]       	 	client_address=10.0.0.232
[2020-06-15T14:35:47.212Z]       	 	client_port=60917
[2020-06-15T14:35:47.212Z]       	 	real path=/hello
[2020-06-15T14:35:47.212Z]       	 	request_scheme=tftp
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       	 Test round 8698/2 exit code: 0
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       	 Hostname: testds-lc54h
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       	 Request Information:
[2020-06-15T14:35:47.212Z]       	 	client_address=192.168.36.11
[2020-06-15T14:35:47.212Z]       	 	client_port=40519
[2020-06-15T14:35:47.212Z]       	 	real path=/hello
[2020-06-15T14:35:47.212Z]       	 	request_scheme=tftp
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       	 Test round 8698/3 exit code: 0
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       	 Hostname: testds-lc54h
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       	 Request Information:
[2020-06-15T14:35:47.212Z]       	 	client_address=192.168.36.11
[2020-06-15T14:35:47.212Z]       	 	client_port=44661
[2020-06-15T14:35:47.212Z]       	 	real path=/hello
[2020-06-15T14:35:47.212Z]       	 	request_scheme=tftp
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       	 Test round 8698/4 exit code: 0
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       	 Hostname: testds-lc54h
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       	 Request Information:
[2020-06-15T14:35:47.212Z]       	 	client_address=192.168.36.11
[2020-06-15T14:35:47.212Z]       	 	client_port=44781
[2020-06-15T14:35:47.212Z]       	 	real path=/hello
[2020-06-15T14:35:47.212Z]       	 	request_scheme=tftp
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       	 Test round 8698/5 exit code: 0
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       	 Hostname: testds-lc54h
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       	 Request Information:
[2020-06-15T14:35:47.212Z]       	 	client_address=192.168.36.11
[2020-06-15T14:35:47.212Z]       	 	client_port=36642
[2020-06-15T14:35:47.212Z]       	 	real path=/hello
[2020-06-15T14:35:47.212Z]       	 	request_scheme=tftp
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       	 Test round 8698/6 exit code: 0
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       	 Hostname: testds-sbckv
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       	 Request Information:
[2020-06-15T14:35:47.212Z]       	 	client_address=10.0.0.232
[2020-06-15T14:35:47.212Z]       	 	client_port=45078
[2020-06-15T14:35:47.212Z]       	 	real path=/hello
[2020-06-15T14:35:47.212Z]       	 	request_scheme=tftp
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       	 Test round 8698/7 exit code: 0
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       	 Hostname: testds-sbckv
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       	 Request Information:
[2020-06-15T14:35:47.212Z]       	 	client_address=10.0.0.232
[2020-06-15T14:35:47.212Z]       	 	client_port=57279
[2020-06-15T14:35:47.212Z]       	 	real path=/hello
[2020-06-15T14:35:47.212Z]       	 	request_scheme=tftp
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       	 Test round 8698/8 exit code: 0
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       	 Hostname: testds-sbckv
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       	 Request Information:
[2020-06-15T14:35:47.212Z]       	 	client_address=10.0.0.232
[2020-06-15T14:35:47.212Z]       	 	client_port=43503
[2020-06-15T14:35:47.212Z]       	 	real path=/hello
[2020-06-15T14:35:47.212Z]       	 	request_scheme=tftp
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       	 Test round 8698/9 exit code: 0
[2020-06-15T14:35:47.212Z]       	 failed: :8698/10=28
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       Stderr:
[2020-06-15T14:35:47.212Z]        	 command terminated with exit code 42
[2020-06-15T14:35:47.212Z]       	 
[2020-06-15T14:35:47.212Z]       
16:35:47  
```

**Review by aanm — APPROVED** [review]
:100:

**Comment by aanm** [comment]
hit https://github.com/cilium/cilium/issues/8945

**Comment by aanm** [comment]
test-net-next --focus="K8sServicesTest"

**Comment by aanm** [comment]
retest-net-next

**Comment by mrostecki** [comment]
It's green now, thanks a lot!

**Review by christarazi — APPROVED** [review]
Well done!

**Review by joestringer — APPROVED** [review]
Policy / helm changes LGTM.

File: operator/crd.go [hunk 31]
```diff
@@ -0,0 +1,82 @@
...
+	}
+	if _, ok := ev.Object.(*v1beta1.CustomResourceDefinition); ok {
+		return nil
+	}
+	return ErrInvalidTypeCRD
+}
+
+// WaitForCRD waits for the given CRD to be available until the default timeout,
+// after which cilium-agent should be ready. Returns an error when timeut
+// esceeded.
```
Comment (joestringer) [inline operator/crd.go]:
```suggestion
// after which cilium-agent should be ready. Returns an error when timeout
// is exceeded.
```

File: operator/crd_test.go [hunk 32]
```diff
@@ -0,0 +1,76 @@
...
+	_, err := client.ApiextensionsV1beta1().CustomResourceDefinitions().Create(context.TODO(), crd, metav1.CreateOptions{})
+	c.Assert(err, IsNil)
+
+	// Try to get existing CRD
+	err = WaitForCRD(client, "foo")
+	c.Assert(err, IsNil)
+
+	// Try to get non-existing CRD
+	err = waitForCRD(context.TODO(), client, "bar")
+	c.Assert(err, ErrorMatches, ".*timeout waiting for CRD bar.*")
```
Comment (joestringer) [inline operator/crd_test.go:75]: What's the timeout here? Seems like it should be the one coming from `UntilWithSync()` but I can't tell what it would be by default. Mainly just want to make sure we're not just adding arbitrary idle time into the unit test runs.

On a related note, I don't see this test name in the Travis output and when I tried to run it locally, it didn't get automatically hooked into the standard CI targets:

```
$ SKIP_VET=1 SKIP_KVSTORES=1 make unit-tests TESTPKGS=operator
dirname: missing operand
Try 'dirname --help' for more information.
  GO    tools/maptool/maptool
dirname: missing operand
Try 'dirname --help' for more information.
=== RUN   Test
OK: 1 passed
--- PASS: Test (0.00s)
=== RUN   Test_getOldestLeases
=== RUN   Test_getOldestLeases/test-1
=== RUN   Test_getOldestLeases/test-2
--- PASS: Test_getOldestLeases (0.00s)
    --- PASS: Test_getOldestLeases/test-1 (0.00s)
    --- PASS: Test_getOldestLeases/test-2 (0.00s)
=== RUN   Test_getPath
=== RUN   Test_getPath/test-1
=== RUN   Test_getPath/test-2
--- PASS: Test_getPath (0.00s)
    --- PASS: Test_getPath/test-1 (0.00s)
    --- PASS: Test_getPath/test-2 (0.00s)
PASS
coverage: 17.1% of statements in github.com/cilium/cilium/operator
ok      github.com/cilium/cilium/operator       0.037s  coverage: 17.1% of statements in github.com/cilium/cilium/operator
dirname: missing operand
Try 'dirname --help' for more information.
dirname: missing operand
Try 'dirname --help' for more information.
```

File: operator/crd.go [hunk 33]
```diff
@@ -0,0 +1,82 @@
...
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	"k8s.io/apimachinery/pkg/fields"
+	"k8s.io/apimachinery/pkg/runtime"
+	"k8s.io/apimachinery/pkg/watch"
+	"k8s.io/client-go/tools/cache"
+	toolswatch "k8s.io/client-go/tools/watch"
+)
+
+const (
+	defaultTimeout = 2 * time.Minute
```
Comment (joestringer) [inline operator/crd.go]: Followup: would be nice to be able to configure this in case it lines up poorly with any other timeouts.

**Review by joestringer — APPROVED** [review]
I think the core change here looks right; there's definitely some points for follow up noted below. 

EDIT: Given that my unit-test concern is mitigated, these are more "nice-to-haves".

File: operator/crd_test.go (hunk 32 above)
Comment (joestringer) [reply operator/crd_test.go:75]: The above assumption I made is wrong, apparently it is run, it's just that gocheck doesn't report it for whatever reason (maybe I'm missing gocheck-specific verbosity flags):

```
$ git diff
diff --git a/operator/crd_test.go b/operator/crd_test.go
index 81d4435e9a89..75b4c70229ba 100644
--- a/operator/crd_test.go
+++ b/operator/crd_test.go
@@ -73,4 +73,6 @@ func (s *crdTestSuite) TestGetCRD(c *C) {
        // Try to get non-existing CRD
        err = waitForCRD(context.TODO(), client, "bar")
        c.Assert(err, ErrorMatches, ".*timeout waiting for CRD bar.*")
+
+       c.Assert(true, Equals, false)
 }
$ SKIP_VET=1 SKIP_KVSTORES=1 make unit-tests TESTPKGS=operator
dirname: missing operand
Try 'dirname --help' for more information.
  GO    tools/maptool/maptool
dirname: missing operand
Try 'dirname --help' for more information.
=== RUN   Test

----------------------------------------------------------------------
FAIL: crd_test.go:63: crdTestSuite.TestGetCRD

crd_test.go:77:
    c.Assert(true, Equals, false)
... obtained bool = true
... expected bool = false

OOPS: 0 passed, 1 FAILED
--- FAIL: Test (0.00s)
=== RUN   Test_getOldestLeases
=== RUN   Test_getOldestLeases/test-1
=== RUN   Test_getOldestLeases/test-2
--- PASS: Test_getOldestLeases (0.00s)
    --- PASS: Test_getOldestLeases/test-1 (0.00s)
    --- PASS: Test_getOldestLeases/test-2 (0.00s)
=== RUN   Test_getPath
=== RUN   Test_getPath/test-1
=== RUN   Test_getPath/test-2
--- PASS: Test_getPath (0.00s)
    --- PASS: Test_getPath/test-1 (0.00s)
    --- PASS: Test_getPath/test-2 (0.00s)
FAIL
coverage: 17.1% of statements in github.com/cilium/cilium/operator
FAIL    github.com/cilium/cilium/operator       0.039s
FAIL
make: *** [Makefile:225: unit-tests] Error 1
```

**Comment by joestringer** [comment]
All tests passed, we requested @mrostecki via Slack to just bump the timeout to 5 minutes. Plan is to merge this imminently to make it for the 1.8.0 train :bullettrain_front:

File: operator/crd.go (hunk 33 above)
Comment (vadorovsky) [reply operator/crd.go]: Will do in a separate PR.

File: operator/crd.go (hunk 31 above)
Comment (vadorovsky) [reply operator/crd.go]: Done

**Comment by joestringer** [comment]
All basic sanity checks passed, along with prior full CI pass this is good to go. Thanks @mrostecki !
