### PR TITLE
bgpv2: Support overlapping selector matches on CiliumBGPAdvertisement

### LINKED ISSUE #35721: BGPv2: CiliumBGPAdvertisement ignores overlapping matches
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

When configuring `CiliumBGPAdvertisement` with overlapping sector-based matches, the last sequential match is used and previous matches are ignored.  There are no errors thrown.  Based on https://github.com/cilium/cilium/blob/main/pkg/bgpv1/manager/reconcilerv2/service.go#L295 and my own log messages, overlapping matches are carried through to this loop and each previous match is overwritten by the next.

I believe an assumption was made that the administrator would only define a single match for each combination of `advertisementType` and `selector`.  The lack of an error message leads me to believe that I am trying to configure Cilium for a use case that wasn't considered, rather than an intentionally not supported one.

As a cloud operator, I have a use case that would ideally be served by setting a dynamic combination of BGP communities based on the workload deployed.  As an example, consider:
* Matching the label "customer" which sets the BGP Community `100:100`. 
* Matching the label "customer-vpc" which sets the BGP Community `110:110`.  
* Matching the label "backbone" which specifies the BGP Community `200:200`.

In this example, all advertisements from the customer's workload include at minimum BGP Community `100:100`.  Some advertisements may contain BGP Communities `100:100` and `110:110`, while others may contain `100:100` and `200:200`.

I would like to modify Cilium to permit overlapping matches for `CiliumBGPAdvertisement.advertisements` with the following logic:
* When overlapping entries define `communities` (`standard`, `wellKnown`, or `large`), treat it as an append operation.  All matches within the same type (`standard` vs. `large`) are combined.
* When overlapping entries define `localPreference`, regardless of being accompanied by `communities` or in isolation,  if their `localPreference` values are different -- throw an error and stop processing the CR.

Example:
```
    - advertisementType: "Service"
      service:
        addresses:
        - ClusterIP
      selector:
        matchExpressions:
        - {key: somekey, operator: NotIn, values: ['never-used-value']}
      attributes:
        communities:
          standard: [ "101:101" ]
    - advertisementType: "Service"
      service:
        addresses:
        - ClusterIP
      selector:
        matchExpressions:
        - {key: somekey, operator: NotIn, values: ['never-used-value']}
      attributes:
        communities:
          standard: [ "202:202" ]
```

When processed by Cilium, this is the same as:
```
    - advertisementType: "Service"
      service:
        addresses:
        - ClusterIP
      selector:
        matchExpressions:
        - {key: somekey, operator: NotIn, values: ['never-used-value']}
      attributes:
        communities:
          standard: [ "101:101", "202:202" ]
```

### How can we reproduce the issue?

Cilium Configuration:
```
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp-cp
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: bgp-cplane-dev-v4-control-plane
  bgpInstances:
  - name: "control-plane"
    localASN: 65001
    peers:
    - name: "frr"
      peerASN: 65000
      peerAddress: 10.0.1.1
      peerConfigRef:
        name: "cilium-cp-frr-peer"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp-worker
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: bgp-cplane-dev-v4-worker
  bgpInstances:
  - name: "worker"
    localASN: 65002
    peers:
    - name: "frr"
      peerASN: 65000
      peerAddress: 10.0.2.1
      peerConfigRef:
        name: "cilium-cp-frr-peer"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: "cilium-cp-frr-peer"
spec:
  gracefulRestart:
    enabled: true
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgp"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: "bgp-advertisements"
  labels:
    advertise: "bgp"
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
        - ClusterIP
      selector:
        matchExpressions:
        - {key: somekey, operator: NotIn, values: ['never-used-value']}
      attributes:
        communities:
          standard: [ "101:101" ]
    - advertisementType: "Service"
      service:
        addresses:
        - ClusterIP
      selector:
        matchExpressions:
        - {key: somekey, operator: NotIn, values: ['never-used-value']}
      attributes:
        communities:
          standard: [ "202:202" ]
    - advertisementType: "Service"
      service:
        addresses:
        - ClusterIP
      selector:
        matchExpressions:
        - {key: somekey, operator: NotIn, values: ['never-used-value']}
      attributes:
        communities:
          standard: [ "303:303" ]
---
```

### Cilium Version

```
$  cilium version
cilium-cli: v0.16.7-40-g9316d0ac compiled with go1.22.2 on linux/amd64
cilium image (default): v1.15.5
cilium image (stable): v1.16.3
cilium image (running): 1.17.0-dev
```

I am running a local build of Cilium using the BGP Control Plane's Kind dev environment:

```
git log
commit d32ff87a6aa69b64f027fae40083d9148d283d1e (HEAD -> dswaffordcw/bgp-adverts-additive, upstream/main, main)
Author: André Martins <andre@cilium.io>
Date:   Thu Sep 12 11:07:02 2024 +0200
```

### Kernel Version

Linux hostname 6.5.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

```
$  k version
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.15-enhanced-describe-dirty", GitCommit:"ac2e2baa7d4039cc4c68f2e869e4edbe2d60b305", GitTreeState:"dirty", BuildDate:"2023-03-02T00:33:46Z", GoVersion:"go1.20.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"30", GitVersion:"v1.30.0", GitCommit:"7c48c2bd72b9bf5c44d21d7338cc7bea77d0ad2a", GitTreeState:"clean", BuildDate:"2024-05-13T22:00:36Z", GoVersion:"go1.22.2", Compiler:"gc", Platform:"linux/amd64"}
```

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

**FRR** (from BGP Control Plane's Dev Environment)
```
router0# show ip bgp sum

IPv4 Unicast Summary (VRF default):
BGP router identifier 10.0.0.1, local AS number 65000 vrf-id 0
BGP table version 3
RIB entries 5, using 960 bytes of memory
Peers 2, using 1434 KiB of memory
Peer groups 1, using 64 bytes of memory

Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
10.0.1.2        4          0         0         0        0    0    0    never       Active        0 N/A
10.0.2.2        4      65002         4         4        0    0    0 00:00:01            3        3 N/A

Total number of neighbors 2
router0# show ip bgp
BGP table version is 6, local router ID is 10.0.0.1, vrf id 0
Default local pref 100, local AS 65000
Status codes:  s suppressed, d damped, h history, * valid, > best, = multipath,
               i internal, r RIB-failure, S Stale, R Removed
Nexthop codes: @NNN nexthop's vrf id, < announce-nh-self
Origin codes:  i - IGP, e - EGP, ? - incomplete
RPKI validation codes: V valid, I invalid, N Not found

   Network          Next Hop            Metric LocPrf Weight Path
*= 10.2.0.1/32      10.0.1.2                               0 65001 i
*>                  10.0.2.2                               0 65002 i
*= 10.2.0.10/32     10.0.1.2                               0 65001 i
*>                  10.0.2.2                               0 65002 i
*= 10.2.236.92/32   10.0.1.2                               0 65001 i
*>                  10.0.2.2                               0 65002 i

Displayed  3 routes and 6 total paths
router0# show ip bgp 10.2.0.1
BGP routing table entry for 10.2.0.1/32, version 5
Paths: (2 available, best #2, table default)
  Advertised to non peer-group peers:
  10.0.1.2 10.0.2.2
  65001
    10.0.1.2 from 10.0.1.2 (10.0.1.2)
      Origin IGP, valid, external, multipath
      Community: 303:303
      Last update: Mon Nov  4 00:04:01 2024
  65002
    10.0.2.2 from 10.0.2.2 (10.0.2.2)
      Origin IGP, valid, external, multipath, best (Older Path)
      Community: 303:303
      Last update: Mon Nov  4 00:03:59 2024
```

### Anything else?

_No response_

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dswaffordcw**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

# bgpv2: Support overlapping selector matches on CiliumBGPAdvertisement

## Overview

**When configuring CiliumBGPAdvertisement with overlapping selector matches prior to this PR, the last sequential match was used, and previous matches were ignored.**

This PR modifies Cilium to support overlapping matches. Overlaps are handled as additive operations for attributes that can be unioned (standard and large communities).  When differing Local Preference values are set, the higher value is selected.  This is in line with [RFC 4271](https://datatracker.ietf.org/doc/html/rfc4271) which states "The higher degree of preference MUST be preferred."

The purpose of this change is to offer more flexibility for administrators of Cilium using the BGP Control Plane.  The flexibility added allows the administrator to configure any combination of BGP communities for Service announcements without explicitly defining every possible combination in advance on their `CiliumBGPAdvertisement`.

Prior to this change, an administrator would have been required to define a Kubernetes label for every possible combination of BGP communities and then define on their  `CiliumBGPAdvertisement` in the `advertisements` section a label selector-based match for each unique combination of communities.  In more complex networks, this poses a significant administrative burden and introduces the risk of configuration drift.

Instead, the administrator now needs to define one label per BGP community that they wish to set.  On their  `CiliumBGPAdvertisement`, the `advertisements` section simply needs a label selector match for each individual community.  If two `advertisements` match, the BGP communities defined on each entry will be applied to the corresponding advertisement.  The `CiliumBGPAdvertisement` no longer needs to be aware of the various combinations of communities that could be desired.  Instead, combinations of communities are set by simply labeling the respective Kubernetes Service with the respective labels.

The use-case above is further described in this [GitHub Issue](https://github.com/cilium/cilium/issues/35721).

Fixes: https://github.com/cilium/cilium/issues/35721

## Description

**`service.go`**:

The focus of this PR are the changes made to `pkg/bgpv1/manager/reconcilerv2/service.go` on ` getDesiredSvcRoutePolicies()`.  Prior to this change, each iteration simply updated the map named `desiredSvcRoutePolicies` without checking for an existing value.

**`policies.go`**:

This PR adds the function `MergeRoutePolicies()` to `policies.go`, which implements the merge operation.  The reconciliation process sequentially passes each overlapping match through that.  The final policy applied represents the merge of all which matched.

The merge operation is defined as:
```
// MergeRoutePolicies evaluates two instances of RoutePolicy{} and returns a single RoutePolicy{} representing
// the merger of the two.  The merge operation focuses on each policy's Statements.  Statements define one or more
// Actions, and these actions may include setting BGP Communities, Local Preference, and others.  Statements are
// keyed by their Conditions, which define the BGP Neighbor, AF, and Prefixes it applies to.
//
// The merge operation evaluates Actions across only those statements with the same key. For these Statements,
// the merge takes the union of all BGP Communities set.  When differing Local Preference values are set, the
// higher value is selected.
```

**`types/bgp.go`**:

In this file, a change was made to add a `String()` method for the type `RoutePolicyConditions`.  As the merge operation uses a map to track each unique set of `RoutePolicyConditions`, the new `String()` method provides a simple hashable key.

## Docs

This PR updates the BGPv2 Control Plane Docs to describe the change in behavior, shown below:

Screenshot 2024-12-20 at 11 21 21 AM

Screenshot 2024-12-20 at 11 21 27 AM

### Unit Tests

**`service_test.go`:**

Unit tests for `ClusterIP`,`External`, and `LoadBalancer` Service advertisements were updated to each add a new test that configures overlapping advertisements.  The overlapping advertisement tests each configure three advertisements, compared to all other tests which configure one.  The advertisements configured set the following sets of attributes:

```
	localPrefHigh             = int64(200)
	redPeer65001BgpAttributes = &v2alpha1.BGPAttributes{
		Communities: &v2alpha1.BGPCommunities{
			Standard:  []v2alpha1.BGPStandardCommunity{"101:101"},
			Large:     []v2alpha1.BGPLargeCommunity{"1111:1111:1111"},
			WellKnown: []v2alpha1.BGPWellKnownCommunity{"no-export"},
		},
		LocalPreference: &localPrefHigh,
	}

	localPrefLow               = int64(50)
	redPeer65001BgpAttributes2 = &v2alpha1.BGPAttributes{
		Communities: &v2alpha1.BGPCommunities{
			Standard:  []v2alpha1.BGPStandardCommunity{"202:202"},
			Large:     []v2alpha1.BGPLargeCommunity{"2222:2222:2222"},
			WellKnown: []v2alpha1.BGPWellKnownCommunity{"no-export"},
		},
		LocalPreference: &localPrefLow,
	}

	redPeer65001BgpAttributes3 = &v2alpha1.BGPAttributes{
		Communities: &v2alpha1.BGPCommunities{
			Standard: []v2alpha1.BGPStandardCommunity{"202:202", "303:303"},
			Large:    []v2alpha1.BGPLargeCommunity{"2222:2222:2222", "3333:3333:3333"},
		},
		LocalPreference: &localPrefLow,
	}
```

The first and second each set unique communities for `Standard` and `Large`.  The third first sets the same communities as the second, then adds a unique `Standard` and `Large` community.  The first and latter two set different `LocalPreference` values.

**`policies_test.go`:**
Tests were added here to cover expected and edge cases for `MergeRoutePolicies()`.

### Manual Testing

The lab from https://github.com/cilium/cilium/tree/main/contrib/containerlab/bgpv2/service was used to manually test this change.  Using the `Makefile` from that directory, I brought up a Kind cluster running Cilium with an instance of FRR.  I commented out the lines that applied configuration to Cilium.

Instead, I applied the following `yaml` file using `kubectl`:
 
```
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      bgp: "65001"
  bgpInstances:
  - name: "65001"
    localASN: 65001
    peers:
    - name: "65000"
      peerASN: 65000
      peerAddress: fd00:10::1
      peerConfigRef:
        name: "cilium-peer"

---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  authSecretRef: bgp-auth-secret
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgp"
    - afi: ipv6
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgp"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: "bgp-advertisements"
  labels:
    advertise: "bgp"
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
        - ClusterIP
      selector:
        matchExpressions:
        - {key: somekey, operator: NotIn, values: ['never-used-value']}
      attributes:
        communities:
          standard: [ "202:202" ]
          large: [ "2222:2222:2222" ]
    - advertisementType: "Service"
      service:
        addresses:
        - ClusterIP
      selector:
        matchExpressions:
        - {key: somekey, operator: NotIn, values: ['never-used-value']}
      attributes:
        communities:
          standard: [ "303:303" ]
          large: [ "3333:3333:3333" ]
          wellKnown: [ "no-export" ]
    - advertisementType: "Service"
      service:
        addresses:
        - ClusterIP
      selector:
        matchExpressions:
        - {key: somekey, operator: NotIn, values: ['never-used-value']}
      attributes:
        communities:
          standard: [ "444:4444" ]
          large: [ "4444:4444:4444" ]
          wellKnown: [ "no-advertise" ]
```

**Inspecting FRR**

On FRR, shown below, I saw the superset of all communities defined above set on the Service announcement:
```
router0# show ip bgp  10.2.86.210
BGP routing table entry for 10.2.86.210/32, version 29
Paths: (2 available, best #2, table default, not advertised to EBGP peer)
  Not advertised to any peer
  65001
    fd00:10:0:1::2 from fd00:10:0:1::2 (10.0.1.2)
      Origin IGP, valid, external, multipath
      Community: 202:202 303:303 444:4444 no-export no-advertise
      Large Community: 2222:2222:2222 3333:3333:3333 4444:4444:4444
      Last update: Thu Dec  5 15:36:06 2024
  65001
    fd00:10:0:2::2 from fd00:10:0:2::2 (10.0.2.2)
      Origin IGP, valid, external, multipath, best (Older Path)
      Community: 202:202 303:303 444:4444 no-export no-advertise
      Large Community: 2222:2222:2222 3333:3333:3333 4444:4444:4444
      Last update: Thu Dec  5 15:36:06 2024
```

### Coverage

Using the [`uncover`](https://github.com/gregoryv/uncover) command line, coverage for `pkg/bgpv1/manager/reconcilerv2` under this PR is now:
```
total:    (statements)    71.1%
```

On `main` as of writing, it was:
```
total:    (statements)    69.6%
```

Fixes: #35721 

```release-note
BGPv2:  Support overlapping selector matches on CiliumBGPAdvertisement
```

### CODE REVIEW

File: pkg/bgpv1/manager/reconcilerv2/service.go [hunk 1]
```diff
@@ -271,29 +271,47 @@ func (r *ServiceReconciler) getDesiredSvcRoutePolicies(p ReconcileParams, desire
...
 				// LoadBalancerIP
 				lbPolicy, err := r.getLoadBalancerIPRoutePolicy(p, peer, agentFamily, svc, advert, ls)
 				if err != nil {
 					return nil, fmt.Errorf("failed to get desired LoadBalancerIP route policy: %w", err)
 				}
 				if lbPolicy != nil {
-					desiredSvcRoutePolicies[lbPolicy.Name] = lbPolicy
+					currentLbPolicy := desiredSvcRoutePolicies[lbPolicy.Name]
+					if currentLbPolicy != nil {
+						r.handleOverlappingDesiredSvcRoutePolicies(currentLbPolicy, lbPolicy, advert)
```
Comment (dswaffordcw) [inline pkg/bgpv1/manager/reconcilerv2/service.go]: @harsimran-pabla I'd like your opinion on this approach --

Normally, I would approach this in a purely functional style.  I'm not a fan of functions that modify one or more inputs.  Though that is exactly what is going on here.

In a functional style, this block would be:
```
if currentLbPolicy != nil {
    lbPolicy = r.handleOverlappingDesiredSvcRoutePolicies(currentLbPolicy, lbPolicy, advert)
}
desiredSvcRoutePolicies[lbPolicy.Name] = lbPolicy
```


To approach this in a purely functional style, that is, having `handleOverlappingDesiredSvcRoutePolicies()` make no modifications to it's inputs and simply return a new `RoutePolicy{}` reflecting the merged policies, I would need to instantiate a new instance of `RoutePolicy{}` within `handleOverlappingDesiredSvcRoutePolicies()`.  There, I would copy over un-modified fields to the new instance.

That approach introduces a new risk -- if we add an attribute to `RoutePolicy{}` where it's defined, and where used in various other locations, then we need to remember and update `handleOverlappingDesiredSvcRoutePolicies()` to make sure that the new field is also carried over.

Though, the current approach also adds a risk.  The risk here is that we have a function that's modifying one of its inputs, and it's hard to make that obvious through the function name or comments.

File: pkg/bgpv1/manager/reconcilerv2/service.go [hunk 2]
```diff
@@ -302,6 +320,70 @@ func (r *ServiceReconciler) getDesiredSvcRoutePolicies(p ReconcileParams, desire
...
+func (r *ServiceReconciler) handleOverlappingDesiredSvcRoutePolicies(
+	existingPolicy *types.RoutePolicy,
+	candidatePolicy *types.RoutePolicy,
+	advert v2alpha1.BGPAdvertisement,
+) {
+
+	// For tests, we must maintain the original order.  Communities will hold
+	// the unique set of standard communities defined across both policies.
+	communities := []string{}
+	communitiesSeen := sets.New[string]()
```
Comment (dswaffordcw) [inline pkg/bgpv1/manager/reconcilerv2/service.go]: @harsimran-pabla I'd also like your opinion here --

I first wrote this using sets.  But, that led to flaky unit tests due to the lack of ordering.  On the test side, I observed that order is significant when two structs are compared using `req.Equalf()`.

File: pkg/bgpv1/manager/reconcilerv2/service.go [hunk 3]
```diff
@@ -302,6 +320,70 @@ func (r *ServiceReconciler) getDesiredSvcRoutePolicies(p ReconcileParams, desire
...
+		communitiesSeen.Insert(statement.Actions.AddCommunities...)
+
+		largeCommunities = append(largeCommunities, statement.Actions.AddLargeCommunities...)
+		largeCommunitiesSeen.Insert(statement.Actions.AddLargeCommunities...)
+	}
+	logMessagePreviousCommunities := fmt.Sprint(communities)
+	logMessagePreviousLargeCommunities := fmt.Sprint(largeCommunities)
+
+	// Extract this policy's communities
+	for _, statement := range candidatePolicy.Statements {
```
Comment (dswaffordcw) [inline pkg/bgpv1/manager/reconcilerv2/service.go]: @harsimran-pabla As you look at this, I'm curious to hear if other ideas come to your mind that would be more efficient?  I feel like I'm iterating way too many times in this function.

As a reminder, I observed this code path being executed for each Service (ClusterIP, Loadbalancer, etc.) running on a given Node.  If a node has 100s of services, I wouldn't want this to code path to slow down reconciliation.

Because of that, I changed the log message below from `r.Logger.Warnf()` to `Debugf()`.

File: pkg/bgpv1/manager/reconcilerv2/service_test.go [hunk 4]
```diff
@@ -1577,6 +1774,8 @@ func Test_ServiceVIPSharing(t *testing.T) {
 		upsertEPs        []*k8s.Endpoints
 		expectedMetadata ServiceReconcilerMetadata
 	}{
+		// Note: one or more tests below leave artifacts behind that later tests in
+		// the same sequence depend on. Order is significant.
```
Comment (dswaffordcw) [inline pkg/bgpv1/manager/reconcilerv2/service_test.go]: @harsimran-pabla FYI - this caught me by surprise!  I first added the new test just after the existing "Add Service" ones and before "Delete Service 1".  That caused "Delete Service 1" to fail.  After moving the new test to the end of this sequence, everything worked fine.

File: pkg/bgpv1/manager/reconcilerv2/service_test.go [hunk 5]
```diff
@@ -1868,6 +2135,9 @@ func Test_ServiceVIPSharing(t *testing.T) {
 
 		// validate that advertised paths match expected metadata
 		advertisedPrefixesMatch(req, testBGPInstance, tt.expectedMetadata.ServicePaths)
+
+		// validate that advertised policies match expected attributes
+		advertisedPoliciesAttributesMatch(req, testBGPInstance, tt.expectedMetadata.ServiceRoutePolicies)
```
Comment (dswaffordcw) [inline pkg/bgpv1/manager/reconcilerv2/service_test.go:2144]: @harsimran-pabla I noticed that `advertisedPrefixesMatch()` is only inspecting the metadata cache on `testBGPInstance` but not actually making calls to `testBGPInstance.Router`.  I believe this could lead to inconsistent tests, if there were an issue between the metadata updates and actually configuring GoBGP.

In `advertisedPoliciesAttributesMatch()`, you'll see that I am making calls to `testBGPInstance.Router` for `GetRoutePolicies()` to inspect further.  I wanted to point out the difference here.

File: pkg/bgpv1/manager/reconcilerv2/service.go (hunk 1 above)
Comment (harsimran-pabla) [reply pkg/bgpv1/manager/reconcilerv2/service.go]: I'd prefer functional style over mutating input parameters. Something along these lines : 

```
MergeRoutePolicies(policyA, policyB) Policy
```

We can add unit test for MergeRoutePolicy, where different combinations can be tested out and not expand existing test cases to validate corner cases of merging policies.

File: pkg/bgpv1/manager/reconcilerv2/service.go (hunk 2 above)
Comment (harsimran-pabla) [reply pkg/bgpv1/manager/reconcilerv2/service.go]: I think you should simplify this code, and in the test you can use req.ElementsMatchf() to ignore order in the slice.

File: pkg/bgpv1/manager/reconcilerv2/service.go (hunk 3 above)
Comment (harsimran-pabla) [reply pkg/bgpv1/manager/reconcilerv2/service.go]: Does using only set simplify the code? I understand however you'd need to repeat the pattern for Communities, and largeCommunitites per statement, I suppose it is unavoidable.

File: pkg/bgpv1/manager/reconcilerv2/service.go [hunk 6]
```diff
@@ -302,6 +320,70 @@ func (r *ServiceReconciler) getDesiredSvcRoutePolicies(p ReconcileParams, desire
...
+		for _, largeCommunity := range statement.Actions.AddLargeCommunities {
+			if largeCommunitiesSeen.Has(largeCommunity) {
+				continue
+			}
+			largeCommunities = append(largeCommunities, largeCommunity)
+		}
+	}
+
+	// Update the existing policy's communities to be the updated sequence created above
+	for _, statement := range existingPolicy.Statements {
```
Comment (harsimran-pabla) [inline pkg/bgpv1/manager/reconcilerv2/service.go]: It seems all statements will get same communities, don't we need to match on the conditions as well ? 

For eg, Policy A
Statement 1, Cond 1, Action 1a, 2a 
Statement 2, Cond 2, Action 3a

Policy B
Statement1, Cond 1, Action 1b

Expected Merged Policy
Statement1: Cond 1, Action 1a, 2a, 1b
Statement2: Cond 2, Action 3a

In the code, we will now get the following
Merged Policy
Statement 1: Cond 1, Action 1a, 2a, 3a, 1b 
Statement 2: Cond 2, Action 1a, 2a, 3a, 1b

**Review by harsimran-pabla — CHANGES_REQUESTED** [review]
Nice to see this in action, I have some concern regarding policy merge ( more in the comments above ).

File: pkg/bgpv1/manager/reconcilerv2/service.go (hunk 6 above)
Comment (dswaffordcw) [reply pkg/bgpv1/manager/reconcilerv2/service.go]: Thanks @harsimran-pabla for the review!  I'll make the requested changes and be back in touch.

Re: "It seems all statements will get the same communities",

It looks to me that they all get the same communities.  Help me double-check this -- looking at `master`:

1) `getDesiredSvcRoutePolicies()` for the ClusterIP case calls `getClusterIPRoutePolicy()`

2) `getClusterIPRoutePolicy()` then calls `CreatePolicy()` toward the end

3) `CreatePolicy()` calls `getCommunities()` and passes the original `advert` variable in.  This variable comes from the for loop on `getDesiredSvcRoutePolicies()`


Compared to the case for Loadbalancer, that also calls into `CreatePolicy()` and constructs the communities from the original `advert`.  I don't see any variance as it comes to conditions or actions?

File: pkg/bgpv1/manager/reconcilerv2/service.go (hunk 1 above)
Comment (dswaffordcw) [reply pkg/bgpv1/manager/reconcilerv2/service.go]: @harsimran-pabla Regarding the test cases, would you prefer that I write tests for `MergeRoutePolicy()` **alone** and not extend the current higher-level tests?

NOTE:  That would leave most of the conditional handling in these blocks under `getDesiredSvcRoutePolicies()` uncovered:
```
if lbPolicy != nil {
	currentLbPolicy := desiredSvcRoutePolicies[lbPolicy.Name]
	if currentLbPolicy != nil {
		r.handleOverlappingDesiredSvcRoutePolicies(currentLbPolicy, lbPolicy, advert)
	} else {
		desiredSvcRoutePolicies[lbPolicy.Name] = lbPolicy
	}
}
```

File: pkg/bgpv1/manager/reconcilerv2/service.go (hunk 2 above)
Comment (dswaffordcw) [reply pkg/bgpv1/manager/reconcilerv2/service.go]: TY for pointing out `req.ElementsMatchf()`!  I was looking for something like that but didn't see it.

File: pkg/bgpv1/manager/reconcilerv2/service_test.go (hunk 4 above)
Comment (harsimran-pabla) [reply pkg/bgpv1/manager/reconcilerv2/service_test.go]: These unit tests are not independent, each sub-test rely on previous step. It is mainly to test sequence of actions, so ordering becomes important. One hint is name `steps` vs `tests` in line 1769, I agree though, it can be easily missed.

File: pkg/bgpv1/manager/reconcilerv2/service_test.go (hunk 5 above)
Comment (harsimran-pabla) [reply pkg/bgpv1/manager/reconcilerv2/service_test.go:2144]: Thanks, yes it makes sense to also validate state of fake router. It is not consistently followed in the test cases. Ideally, both metadata and underlying router state should be compared.

File: pkg/bgpv1/manager/reconcilerv2/service.go (hunk 6 above)
Comment (harsimran-pabla) [reply pkg/bgpv1/manager/reconcilerv2/service.go]: In the current implementation, you're right - callers always create policy with single statement ( we create different policy for v4 and v6 ). However, `merge` method is assuming that multiple matched advertisements will have same conditions ( which is true today ) but may not be always the case. We can tackle this when such case arises. 

So, we can assume now that if policy name matches, statements and conditions will be same. Only actions of the statements will be merged.

For eg, this is the only case

Policy A
Statement 1, Cond 1, Action 1a, 2a
Policy B
Statement1, Cond 1, Action 1b

Expected Merged Policy
Statement1: Cond 1, Action 1a, 2a, 1b

File: pkg/bgpv1/manager/reconcilerv2/service.go (hunk 1 above)
Comment (harsimran-pabla) [reply pkg/bgpv1/manager/reconcilerv2/service.go]: I think we need both, `MergeRoutePolicy` unit tests for all corner cases which may come up. For eg
- Passed policies being nil.
- Deduplication of communities, large comm etc.
- Local preference pick when multiple policies are setting it. 
- Multiple conditions in the policy, like mentioned in this [example](https://github.com/cilium/cilium/pull/36414#discussion_r1876451858).

Conditional handling in `getDesiredSvcRoutePolicies` should also be tested, but it can be simpler test case.
- Two advertisements for a service which are merged. ( With basic community attribute ).

File: Documentation/network/bgp-control-plane/bgp-control-plane-v2.rst [hunk 7]
```diff
@@ -738,6 +738,17 @@ Similarly, ``internalTrafficPolicy`` is considered for ``ClusterIP`` advertiseme
...
 
+Overlapping Advertisements
+~~~~~~~~~~~~~~~~~~~~~~~~~~
+
+When configuring ``CiliumBGPAdvertisement``, it is possible that two or more 
+advertisments match for a given Service.  Prior to Cilum ``1.17.TODO``, 
+overlapping matches were not expected and the last sequential match was used. 
+Today, overlapping advertisements are supported.  Overlaps are handled as 
+additive operations for attributes that can be unioned (communities). If 
+local preference was set, it remains set to the first advertisement matched.
```
Comment (qmonnet) [inline Documentation/network/bgp-control-plane/bgp-control-plane-v2.rst]: Please keep the `.. _bgp-override:` anchor right above the related subsection, do not insert your paragraph between the two.

Doc subsection looks good otherwise, thanks!

Seeing that the PR is now waiting for the next branching to happen before being merged, your `1.17.TODO` will most likely be `1.18`.

**Review by qmonnet — CHANGES_REQUESTED** [review]

File: pkg/bgpv1/manager/reconcilerv2/service.go [hunk 8]
```diff
@@ -850,6 +871,77 @@ func checkServiceAdvertisement(advert v2alpha1.BGPAdvertisement, advertServiceTy
...
+			Conditions: statement.Conditions,
+		})
+		communities.Insert(statement.Actions.AddCommunities...)
+		largeCommunities.Insert(statement.Actions.AddLargeCommunities...)
+		routePolicyConditionsSeen.Insert(statement.Conditions.String())
+	}
+
+	// Extract the second policy's non-overlapping statements, and communities from all statements
+	for _, statement := range policyB.Statements {
+		if !routePolicyConditionsSeen.Has(statement.Conditions.String()) {
```
Comment (dswaffordcw) [inline pkg/bgpv1/manager/reconcilerv2/service.go]: @harsimran-pabla 
Looking back to the original version of this function, I was iterating through `policyA.Statements` and re-assigning the `Actions.SetCommunities` and `Actions.SetLargeCommunities` values on each.

After moving to the functional approach (which I ❤️  much better now, thanks for that nudge), and eliminating any modification of the inputs, I picked up on a potential bug in the first version.  That is, I was assuming `len(policyA.Statements) == len(policyB.Statements)` but I'm not confident now that this is a safe assumption.

That is what this logic is trying to address.  `routePolicyConditionsSeen` is a set that stores a string representation (key) for a statements `.Conditions`.  While I used a set, I was thinking about maps at the time and trying to index/key each unique combination of `.Conditions`, to understand when I see ones that I've seen before vs. a new one. 

A few lines up in the earlier loop, you'll see:
```
routePolicyConditionsSeen.Insert(statement.Conditions.String())
```

Then in this loop, I check:
```
if !routePolicyConditionsSeen.Has(statement.Conditions.String()) {
```
And if it's new, I add another `RoutePolicyStatement` to the merged policy to represent this new unique set of conditions.

This is adding a bit more logic, but seems to make it less risky.  What do you think?  I'm happy to rip that handling out as well if it's looking too far ahead.

This is the reason for adding the `String()` method in `bgp.go`.

File: pkg/bgpv1/manager/reconcilerv2/service.go [hunk 9]
```diff
@@ -850,6 +871,77 @@ func checkServiceAdvertisement(advert v2alpha1.BGPAdvertisement, advertServiceTy
...
+		}
+		for _, community := range statement.Actions.AddCommunities {
+			communities.Insert(community)
+		}
+		for _, largeCommunity := range statement.Actions.AddLargeCommunities {
+			largeCommunities.Insert(largeCommunity)
+		}
+	}
+
+	bestLocalPreference := int64(0)
```
Comment (dswaffordcw) [inline pkg/bgpv1/manager/reconcilerv2/service.go]: In the original version, I was ignoring Local Pref entirely and just leaving it set to whatever `policyA` had.  Given the complex handling for communities, that didn't feel right.

Here, I'm selecting the highest (best) local preference value across the two policies and using that.  If this seems reasonable, I'll move this into a new function.

File: pkg/bgpv1/manager/reconcilerv2/service_test.go [hunk 10]
```diff
@@ -1868,6 +2133,33 @@ func Test_ServiceVIPSharing(t *testing.T) {
...
+	}
+}
+
+func Test_mergeRoutePolicies(t *testing.T) {
```
Comment (dswaffordcw) [inline pkg/bgpv1/manager/reconcilerv2/service_test.go]: This section is a TODO still.

File: pkg/bgpv1/types/bgp.go [hunk 11]
```diff
@@ -114,6 +115,19 @@ type RoutePolicyConditions struct {
 	MatchFamilies []Family
 }
 
+// String() constructs a string identifier
+func (r RoutePolicyConditions) String() string {
```
Comment (dswaffordcw) [inline pkg/bgpv1/types/bgp.go:131]: This is composing a hashable/comparable string identifier for the instance of `RoutePolicyConditions`.  Think map key.

File: pkg/bgpv1/manager/reconcilerv2/service.go [hunk 12]
```diff
@@ -850,6 +871,77 @@ func checkServiceAdvertisement(advert v2alpha1.BGPAdvertisement, advertServiceTy
...
+		return nil, fmt.Errorf("route policy is nil")
+	}
+	if policyA.Name != policyB.Name {
+		return nil, fmt.Errorf("route policy names do not match")
+	}
+	if policyA.Type != policyB.Type {
+		return nil, fmt.Errorf("route policy types do not match")
+	}
+
+	communities := sets.NewString()
```
Comment (dswaffordcw) [inline pkg/bgpv1/manager/reconcilerv2/service.go]: @harsimran-pabla I'm back to sets 🥳 !   When I had trouble w/ the tests before, it was because I was using `.UnsortedList()` when converting sets back to slices.  When I had looked before, I thought that was the only method available for casting into a slice.  I was wrong.  There is `.List()` which sorts the set as it casts it.

On the test side, I didn't need anything complicated and simply had to sort the values before comparing.

On the simplification point, I dropped the log message that I had before.  I had already turned it down to `DEBUG` after seeing how noisy it was.  Removing that cut out a good bit of visual noise in this function.

File: Documentation/network/bgp-control-plane/bgp-control-plane-v2.rst [hunk 13]
```diff
@@ -736,6 +736,63 @@ Similarly, ``internalTrafficPolicy`` is considered for ``ClusterIP`` advertiseme
     and ignores the configuration of ``.spec.internalTrafficPolicy``.
 
 
+Overlapping Advertisements
```
Comment (dswaffordcw) [inline Documentation/network/bgp-control-plane/bgp-control-plane-v2.rst:739]: @qmonnet and @harsimran-pabla Could you two look over the Docs update again?

Here's what it looks like on my end:

Screenshot 2024-12-12 at 9 54 45 PM

File: pkg/bgpv1/manager/reconcilerv2/service.go [hunk 14]
```diff
@@ -850,6 +871,77 @@ func checkServiceAdvertisement(advert v2alpha1.BGPAdvertisement, advertServiceTy
 	return true, nil
 }
 
+func mergeRoutePolicies(policyA *types.RoutePolicy, policyB *types.RoutePolicy) (*types.RoutePolicy, error) {
```
Comment (dswaffordcw) [inline pkg/bgpv1/manager/reconcilerv2/service.go]: @harsimran-pabla From a style perspective, do you prefer this to be standalone or as a member of the Reconciler instance:
```
func (r *ServiceReconciler) mergeRoutePolicies(...) {
```

**Comment by dswaffordcw** [comment]
@harsimran-pabla Is there a specific linter and formatter that I should be using?

I typically use `golangci-lint ` and [`golines`](https://github.com/segmentio/golines) w/ line length set to 120.   I tried out `golines` Reconcilerv2 just now and it is suggesting a ton of line length-related changes, so I backed that out.

File: Documentation/network/bgp-control-plane/bgp-control-plane-v2.rst (hunk 13 above)
Comment (qmonnet) [reply Documentation/network/bgp-control-plane/bgp-control-plane-v2.rst:739]: Looks good to me now, thank you!

**Review by qmonnet — APPROVED** [review]

File: Documentation/network/bgp-control-plane/bgp-control-plane-v2.rst [hunk 15]
```diff
@@ -736,6 +736,63 @@ Similarly, ``internalTrafficPolicy`` is considered for ``ClusterIP`` advertiseme
...
+
+We have a deployment named `hello-world` which was labeled using:
+
+.. code-block:: bash
+
+    kubectl label deployment hello-world vpc1=true 
+    kubectl label deployment hello-world vpc2=true
+
+The resulting BGP advertisment will set both communities `65000:100` and `65000:200`.
+All possible combinations of communities (`Standard`, `Large`, `WellKnown`) are
```
Comment (qmonnet) [inline Documentation/network/bgp-control-plane/bgp-control-plane-v2.rst]: Documentation workflow complains: you need double-backquotes in RST to inline literals (single-backquotes currently default to the proper formatting but have a different meaning in RST and could be redefined for another role).

You also have a typo on `advertisment`.

```suggestion
The resulting BGP advertisement will set both communities ``65000:100`` and ``65000:200``.
All possible combinations of communities (``Standard``, ``Large``, ``WellKnown``) are 
```

**Review by qmonnet — CHANGES_REQUESTED** [review]

File: pkg/bgpv1/types/bgp_test.go [hunk 16]
```diff
@@ -0,0 +1,120 @@
+package types
```
Comment (qmonnet) [inline pkg/bgpv1/types/bgp_test.go:4]: Please add the missing SPDX and copyright header to this file:

```suggestion
// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

package types
```

I don't know whether this is what the golangci-lint workflow complains about :thinking: :

```
  pkg/bgpv1/types/bgp_test.go:1: Missed header for check (goheader)
```

File: pkg/bgpv1/manager/reconcilerv2/service.go (hunk 14 above)
Comment (harsimran-pabla) [reply pkg/bgpv1/manager/reconcilerv2/service.go]: I think it can be standalone, also moved to route_policy.go file, so if required we can reuse it for merging route policies in other reconcilers.

File: pkg/bgpv1/manager/reconcilerv2/service.go (hunk 8 above)
Comment (harsimran-pabla) [reply pkg/bgpv1/manager/reconcilerv2/service.go]: I like this new approach. I think we are very close to having comm, large comm and local pref per statement, instead of global for the policy. 

Since statement key is basically unified `statement.Conditions.String()`. Instead of a set, we can have a map, and value for it could be merged metadata ( statement actions and conditions ). Once we fill in this map after iterating over two policies, we can recreate merged policy from the actions stored in the map.

It is slightly easier to reason about and also provides us flexibility when we do add multiple statements with different conditions.

File: pkg/bgpv1/manager/reconcilerv2/service.go [hunk 17]
```diff
@@ -850,6 +871,77 @@ func checkServiceAdvertisement(advert v2alpha1.BGPAdvertisement, advertServiceTy
...
+			continue
+		}
+		if len(statement.Actions.AddCommunities) != 0 {
+			statement.Actions.AddCommunities = communities.List()
+		}
+		if len(statement.Actions.AddLargeCommunities) != 0 {
+			statement.Actions.AddLargeCommunities = largeCommunities.List()
+		}
+		// RFC 4271 states "The higher degree of preference MUST be preferred."
+		localPreference := *statement.Actions.SetLocalPreference
```
Comment (harsimran-pabla) [inline pkg/bgpv1/manager/reconcilerv2/service.go]: This can be nil, should handle that case.

File: pkg/bgpv1/manager/reconcilerv2/service.go (hunk 9 above)
Comment (harsimran-pabla) [reply pkg/bgpv1/manager/reconcilerv2/service.go]: Thanks, yes it makes sense.

File: pkg/bgpv1/types/bgp_test.go [hunk 18]
```diff
@@ -0,0 +1,120 @@
...
+					{
+						Afi:  AfiIPv6,
+						Safi: SafiUnicast,
+					},
+				},
+			},
+			expected: "ipv6-unicast",
+		},
+		{
+			name: "sets only families",
```
Comment (harsimran-pabla) [inline pkg/bgpv1/types/bgp_test.go]: duplicate test case.

File: Documentation/network/bgp-control-plane/bgp-control-plane-v2.rst (hunk 15 above)
Comment (dswaffordcw) [reply Documentation/network/bgp-control-plane/bgp-control-plane-v2.rst]: Thanks for correcting that!

File: Documentation/network/bgp-control-plane/bgp-control-plane-v2.rst [hunk 19]
```diff
@@ -736,6 +736,63 @@ Similarly, ``internalTrafficPolicy`` is considered for ``ClusterIP`` advertiseme
...
+When configuring ``CiliumBGPAdvertisement``, it is possible that two or more
+advertisments match the same Service. Prior to Cilum 1.18, overlapping matches 
+were not expected and the last sequential match was used. Today, overlapping 
+advertisements are supported and their handling varies by attribute:
+
+* Communities: the union of elements is taken across all matches
+* Local Preference: the largest value is selected
+
+As an example, below we have two advertisements which each define a selector 
+match.  One matches on the label "vpc1" while the other on "vpc1".
```
Comment (qmonnet) [inline Documentation/network/bgp-control-plane/bgp-control-plane-v2.rst]: Formatting. Plus you probably mean the second matches on `vpc2` and not `vpc1`.

```suggestion
match.  One matches on the label ``vpc1`` while the other matches on ``vpc2``.
```

File: Documentation/network/bgp-control-plane/bgp-control-plane-v2.rst [hunk 20]
```diff
@@ -736,6 +736,63 @@ Similarly, ``internalTrafficPolicy`` is considered for ``ClusterIP`` advertiseme
...
+          selector:
+            matchExpressions:
+              - { key: vpc2, operator: In, values: [ true ] }
+          attributes:
+            communities:
+              standard: [ "65000:200" ]
+
+We have a deployment named `hello-world` which was labeled using:
+
+.. code-block:: bash
```
Comment (qmonnet) [inline Documentation/network/bgp-control-plane/bgp-control-plane-v2.rst]:
```suggestion
.. code-block:: shell-session
```

File: Documentation/network/bgp-control-plane/bgp-control-plane-v2.rst [hunk 21]
```diff
@@ -736,6 +736,63 @@ Similarly, ``internalTrafficPolicy`` is considered for ``ClusterIP`` advertiseme
     and ignores the configuration of ``.spec.internalTrafficPolicy``.
 
 
+Overlapping Advertisements
+~~~~~~~~~~~~~~~~~~~~~~~~~~
+
+When configuring ``CiliumBGPAdvertisement``, it is possible that two or more
+advertisments match the same Service. Prior to Cilum 1.18, overlapping matches
```
Comment (qmonnet) [inline Documentation/network/bgp-control-plane/bgp-control-plane-v2.rst]:
```suggestion
advertisements match the same Service. Prior to Cilium 1.18, overlapping matches 
```

**Review by qmonnet — CHANGES_REQUESTED** [review]
Some more nits below that I missed from the previous workflow failure, please fix them.

Can you also please squash your commits into a single one?

File: pkg/bgpv1/manager/reconcilerv2/service.go (hunk 8 above)
Comment (dswaffordcw) [reply pkg/bgpv1/manager/reconcilerv2/service.go]: @harsimran-pabla That was a GREAT suggestion!  After getting deep into writing tests for all of the various combinations, I found a bug in one edge case that your map idea immediately solved.

The map approach is also considerably less complex ❤️ !  One aspect where it is now simplified is that I threw out the duplicate checking and instead handled de-duplication as a post-processing step.  Similarly for the Local Preference side, handling that in-line was far more straightforward.

File: pkg/bgpv1/manager/reconcilerv2/policies.go [hunk 22]
```diff
@@ -197,6 +197,106 @@ func CreatePolicy(name string, peerAddr netip.Addr, v4Prefixes, v6Prefixes types
...
 
+// MergeRoutePolicies evaluates two instances of RoutePolicy{} and returns a single RoutePolicy{} representing
+// the merger of the two.  The merge operation focuses on each policy's Statements.  Statements define one or more
+// Actions, and these actions may include setting BGP Communities, Local Preference, and others.  Statements are
+// keyed by their Conditions, which define the BGP Neighbor, AF, and Prefixes it applies to.
+//
+// The merge operation evaluates Actions across only those statements with the same key. For these Statements,
+// the merge takes the union of all BGP Communities set.  When differing Local Preference values are set, the
+// higher value is selected.
+func MergeRoutePolicies(policyA *types.RoutePolicy, policyB *types.RoutePolicy) (*types.RoutePolicy, error) {
```
Comment (dswaffordcw) [inline pkg/bgpv1/manager/reconcilerv2/policies.go:208]: @harsimran-pabla This is ready for another look --

This version is based on the map approach, simplifies handling of duplicates, and moves local pref handling in-line.

File: pkg/bgpv1/manager/reconcilerv2/policies.go [hunk 23]
```diff
@@ -197,6 +197,106 @@ func CreatePolicy(name string, peerAddr netip.Addr, v4Prefixes, v6Prefixes types
...
+	}
+
+	// Maps a string key representing a unique RoutePolicyConditions{} (where unique is defined by the values of all
+	// attributes) to a RoutePolicyStatement{}.  When multiple instances of the same key representing
+	// RoutePolicyConditions{} are observed, the existing RoutePolicyStatement{} will be updated to reflect the union
+	// of all instances.
+	conditionsToMergedRoutePolicyStatement := map[string]*types.RoutePolicyStatement{}
+
+	// Extract the first policy's statements and communities
+	for _, statement := range policyA.Statements {
```
Comment (dswaffordcw) [inline pkg/bgpv1/manager/reconcilerv2/policies.go]: As you look through this loop, and the duplicate of it starting on line 257 for `policyB`, I am curious to hear if you would replace both with a function call?

I am leaning that way, but it would add the complexity related to passing around and updating the map.

File: pkg/bgpv1/manager/reconcilerv2/policies_test.go [hunk 24]
```diff
@@ -0,0 +1,479 @@
...
+						Actions: types.RoutePolicyActions{
+							RouteAction:        types.RoutePolicyActionAccept,
+							SetLocalPreference: nil,
+						},
+					},
+				},
+			},
+		},
+		{
+			name: "both set standard communities",
```
Comment (dswaffordcw) [inline pkg/bgpv1/manager/reconcilerv2/policies_test.go:186]: These tests could use another round of polish.  I intend to refactor this a bit more tomorrow using variables for some of the duplicate blocks.

File: pkg/bgpv1/manager/reconcilerv2/policies.go (hunk 23 above)
Comment (harsimran-pabla) [reply pkg/bgpv1/manager/reconcilerv2/policies.go]: Yep, let's replace this with function call. I suspect this code will grow in future as we add support for more attributes.

File: pkg/bgpv1/manager/reconcilerv2/policies.go [hunk 25]
```diff
@@ -197,6 +197,106 @@ func CreatePolicy(name string, peerAddr netip.Addr, v4Prefixes, v6Prefixes types
...
+				conditionsToMergedRoutePolicyStatement[key].Actions.AddCommunities = append(
+					conditionsToMergedRoutePolicyStatement[key].Actions.AddCommunities, statement.Actions.AddCommunities...)
+			}
+			if len(statement.Actions.AddLargeCommunities) > 0 {
+				conditionsToMergedRoutePolicyStatement[key].Actions.AddLargeCommunities = append(
+					conditionsToMergedRoutePolicyStatement[key].Actions.AddLargeCommunities, statement.Actions.AddLargeCommunities...)
+			}
+			// RFC 4271 states "The higher degree of preference MUST be preferred."
+			if statement.Actions.SetLocalPreference != nil &&
+				*statement.Actions.SetLocalPreference > *conditionsToMergedRoutePolicyStatement[key].Actions.SetLocalPreference {
```
Comment (harsimran-pabla) [inline pkg/bgpv1/manager/reconcilerv2/policies.go]: `*conditionsToMergedRoutePolicyStatement[key].Actions.SetLocalPreference` can be nil de-reference as well, right?

File: pkg/bgpv1/manager/reconcilerv2/service_test.go [hunk 26]
```diff
@@ -1932,3 +2200,25 @@ func advertisedPrefixesMatch(req *require.Assertions, bgpInstance *instance.BGPI
...
+
+	// Index policies by name
+	expectedPolicies := make(map[string]*types.RoutePolicy)
+	for _, routePolicyMap := range expectedResourceRoutePolicyMap {
+		for policyName, policy := range routePolicyMap {
+			expectedPolicies[policyName] = policy
+		}
+	}
+
+	for _, policy := range response.Policies {
```
Comment (harsimran-pabla) [inline pkg/bgpv1/manager/reconcilerv2/service_test.go:2228]: Should there also be a len check between `response.Policies` and `expectedPolicies`,  if `response.Policies` has extra items we will not catch it.

File: pkg/bgpv1/manager/reconcilerv2/policies.go (hunk 25 above)
Comment (dswaffordcw) [reply pkg/bgpv1/manager/reconcilerv2/policies.go]: Is this what you are thinking about?
```
var nilPointerInt64 *int64

policyA: &types.RoutePolicy{
Name: "policy",
Statements: []*types.RoutePolicyStatement{
	{
		Conditions: types.RoutePolicyConditions{},
		Actions: types.RoutePolicyActions{
			RouteAction:        types.RoutePolicyActionAccept,
			SetLocalPreference: nilPointerInt64,
		},
	},
},
```

Expanding on that, in this test it seems to be the same as if it were `nil` to begin with:
```
	var nilPointerInt64 *int64
	t.Errorf("nilPointerInt64 is %+v\n", nilPointerInt64)

	policy := &types.RoutePolicy{
		Name: "policy",
		Statements: []*types.RoutePolicyStatement{
			{
				Conditions: types.RoutePolicyConditions{},
				Actions: types.RoutePolicyActions{
					RouteAction:        types.RoutePolicyActionAccept,
					SetLocalPreference: nil,
				},
			},
		},
	}
	t.Errorf("policy's SetLocalPref is %+v\n", policy.Statements[0].Actions.SetLocalPreference)

	req := require.New(t)
	req.Equal(nilPointerInt64, policy.Statements[0].Actions.SetLocalPreference)
```

That test passes and shows:
```
    policies_test.go:21: nilPointerInt64 is <nil>
    policies_test.go:35: policy's SetLocalPref is <nil>
```

File: pkg/bgpv1/manager/reconcilerv2/service_test.go (hunk 26 above)
Comment (dswaffordcw) [reply pkg/bgpv1/manager/reconcilerv2/service_test.go:2228]: Added!

File: pkg/bgpv1/manager/reconcilerv2/policies.go [hunk 27]
```diff
@@ -197,6 +197,100 @@ func CreatePolicy(name string, peerAddr netip.Addr, v4Prefixes, v6Prefixes types
...
+		if len(statement.Actions.AddLargeCommunities) != 0 {
+			uniqueLargeCommunities := sets.NewString(statement.Actions.AddLargeCommunities...).List()
+			statement.Actions.AddLargeCommunities = uniqueLargeCommunities
+		}
+	}
+
+	return mergedPolicy, nil
+}
+
+func mergePolicy(
```
Comment (dswaffordcw) [inline pkg/bgpv1/manager/reconcilerv2/policies.go:255]: @harsimran-pabla This is refactored as a function now.  Let me know how that looks.

I still have a round of polishing to do on `policies_test.go`.

File: pkg/bgpv1/manager/reconcilerv2/policies.go (hunk 25 above)
Comment (harsimran-pabla) [reply pkg/bgpv1/manager/reconcilerv2/policies.go]: I think both are same, this is the test which would cause panic

```
		{
			name: "nil dereferenced statement.Action.SetLocalPref",
			policyA: &types.RoutePolicy{
				Name: "policy",
				Statements: []*types.RoutePolicyStatement{
					{
						Conditions: types.RoutePolicyConditions{},
						Actions: types.RoutePolicyActions{
							RouteAction:        types.RoutePolicyActionAccept,
							SetLocalPreference: nil, // can be nil or nilPointerInt64
						},
					},
				},
			},
			policyB: &types.RoutePolicy{
				Name: "policy",
				Statements: []*types.RoutePolicyStatement{
					{
						Conditions: types.RoutePolicyConditions{},
						Actions: types.RoutePolicyActions{
							RouteAction:        types.RoutePolicyActionAccept,
							SetLocalPreference: ptr.To[int64](100), // In policy B, have some local pref value
						},
					},
				},
			},
			errorExpected: false,
			expected: &types.RoutePolicy{
				Name: "policy",
				Statements: []*types.RoutePolicyStatement{
					{
						Conditions: types.RoutePolicyConditions{},
						Actions: types.RoutePolicyActions{
							RouteAction:        types.RoutePolicyActionAccept,
							SetLocalPreference: ptr.To[int64](100),
						},
					},
				},
			},
		},
```

File: pkg/bgpv1/manager/reconcilerv2/service_test.go (hunk 26 above)
Comment (harsimran-pabla) [reply pkg/bgpv1/manager/reconcilerv2/service_test.go:2228]: nit: len check is only required once, outside the loop.

Comment (dswaffordcw) [reply pkg/bgpv1/manager/reconcilerv2/service_test.go:2228]: 🤦   TY!

File: pkg/bgpv1/manager/reconcilerv2/policies.go (hunk 25 above)
Comment (dswaffordcw) [reply pkg/bgpv1/manager/reconcilerv2/policies.go]: TY!  I repro'd the panic with that one:
```
--- FAIL: Test_MergeRoutePolicies (0.00s)
    --- FAIL: Test_MergeRoutePolicies/nil_dereferenced_statement.Action.SetLocalPref (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2dea3c2]
```

**Comment by dswaffordcw** [comment]
@harsimran-pabla I believe this is ready for a final review.  Thanks for your deep attention to detail throughout!

On the test side, I thought there was more duplication to clean up but after going through it again, I realized that each test introduces a slight variation.  I ended up leaving most as is, as I think it'll be harder to follow if I replace all of those instances of `RoutePolicy{}` with variables defined elsewhere.  Let me know though if you disagree or see other opportunities to simplify.

**Review by harsimran-pabla — APPROVED** [review]
🚀

File: Documentation/network/bgp-control-plane/bgp-control-plane-v2.rst [hunk 28]
```diff
@@ -736,6 +736,63 @@ Similarly, ``internalTrafficPolicy`` is considered for ``ClusterIP`` advertiseme
...
+            addresses:
+              - ClusterIP
+          selector:
+            matchExpressions:
+              - { key: vpc2, operator: In, values: [ true ] }
+          attributes:
+            communities:
+              standard: [ "65000:200" ]
+
+We have a deployment named `hello-world` which was labeled using:
```
Comment (harsimran-pabla) [inline Documentation/network/bgp-control-plane/bgp-control-plane-v2.rst]: Docs linter is complaining here, I think hello-world requires double quotes. 
```
/github/workspace/Documentation/network/bgp-control-plane/bgp-control-plane-v2.rst:784: WARNING: 'any' reference target not found: hello-world

```

Comment (harsimran-pabla) [reply Documentation/network/bgp-control-plane/bgp-control-plane-v2.rst]: I will run the test suite after you push a fix for it, and also rebase on latest.

Comment (dswaffordcw) [reply Documentation/network/bgp-control-plane/bgp-control-plane-v2.rst]: Awesome!

I just caught one more issue w/ the docs.  Working on that at the moment.  With a fresh round of local testing, I noticed that the labels such as `vpc1=true` need to be set on the K8s "Service", not the Pod/Deployment.  I missed this before because I was only testing with the more generic:
```
selector:
        matchExpressions:
        - {key: somekey, operator: NotIn, values: ['never-used-value']}
```

I.e., one needs to run:
```
k label service hello-world vpc1=true
k label service hello-world vpc2=true
```

Then, I saw:
```
dswafford-2% k get service hello-world --show-labels
NAME          TYPE           CLUSTER-IP   EXTERNAL-IP   PORT(S)          AGE     LABELS
hello-world   LoadBalancer   10.2.65.71   <pending>     8080:30569/TCP   3m46s   app=hello-world,vpc1=true,vpc2=true
```

And in FRR, I saw:
```
router0# show ip bgp sum

IPv4 Unicast Summary (VRF default):
BGP router identifier 10.0.0.1, local AS number 65000 vrf-id 0
BGP table version 32
RIB entries 1, using 192 bytes of memory
Peers 2, using 1434 KiB of memory
Peer groups 1, using 64 bytes of memory

Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
fd00:10:0:1::2  4      65001      1532      1441        0    0    0 11:38:59            1        1 N/A
fd00:10:0:2::2  4      65001      1530      1438        0    0    0 11:55:12            1        1 N/A

Total number of neighbors 2
router0# show ip bgp 10.2.65.71
BGP routing table entry for 10.2.65.71/32, version 32
Paths: (2 available, best #1, table default)
  Advertised to non peer-group peers:
  fd00:10:0:1::2 fd00:10:0:2::2
  65001
    fd00:10:0:1::2 from fd00:10:0:1::2 (10.0.1.2)
      Origin IGP, valid, external, multipath, best (Older Path)
      Large Community: 1111:1111:1111 2222:2222:2222
      Last update: Fri Dec 20 18:21:48 2024
  65001
    fd00:10:0:2::2 from fd00:10:0:2::2 (10.0.2.2)
      Origin IGP, valid, external, multipath
      Large Community: 1111:1111:1111 2222:2222:2222
      Last update: Fri Dec 20 18:21:48 2024
```

That was using:
```
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: "bgp-advertisements"
  labels:
    advertise: "bgp"
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
        - ClusterIP
        - LoadBalancerIP
      selector:
        matchExpressions:
        - {key: vpc1, operator: In, values: ['true']}
      attributes:
        communities:
          large: [ "1111:1111:1111" ]
    - advertisementType: "Service"
      service:
        addresses:
        - ClusterIP
        - LoadBalancerIP
      selector:
        matchExpressions:
        - {key: vpc2, operator: In, values: ['true']}
      attributes:
        communities:
          large: [ "2222:2222:2222" ]
    - advertisementType: "Service"
      service:
        addresses:
        - ClusterIP
        - LoadBalancerIP
      selector:
        matchExpressions:
        - {key: vpc3, operator: In, values: ['true']}
      attributes:
        communities:
          large: [ "3333:3333:3333" ]
    - advertisementType: "Service"
      service:
        addresses:
        - ClusterIP
        - LoadBalancerIP
      selector:
        matchExpressions:
        - {key: vpc4, operator: In, values: ['true']}
      attributes:
        communities:
          large: [ "4444:4444:4444" ]
---
```

The Containerlab setup here was `contrib/containerlab/bgpv2/service`.

**Comment by dswaffordcw** [comment]
@harsimran-pabla The docs are updated, and the PR summary now includes the latest screenshots.

Ready for tests!

**Comment by dswaffordcw** [comment]
@harsimran-pabla It looks like three commits landed on `main` since you started the test runs.  I just rebased and updated this one.

If you didn't see though, the `E2E` test suite had a failure on the first round (will update w/ link).

Also, I saw that GH was still showing 1 Change requested from @qmonnet.  That was an earlier request to squash, which you can see we are squashed now.  I clicked "Re-request review", but wonder now if I should have left the warning alone.

**Review by qmonnet — APPROVED** [review]
It's OK I can approve now :)

**Comment by dswaffordcw** [comment]
@harsimran-pabla or @qmonnet Are you able to re-run these test suites?
* Conformance Gateway API (ci-gateway-api)
* Integration Tests (ci-integration)

Both failed.  The first looks like it may be a transient issue.  TY!

**Comment by qmonnet** [comment]
Sorry, I was out for the holidays - done now!

**Comment by dswaffordcw** [comment]
Thanks @qmonnet and @harsimran-pabla for all of your help throughout this PR!
