### PR TITLE
pkg/policy: fix toGroups derivative policy for clusterwide policies

### LINKED ISSUE #12857: Verify CCNP with toGroups
Something tells me they won't work... This function is used for both CCNP and CNP. If a CCNP has a `toGroups` field, it will create a derivative CNP, not a derivative CCNP.

https://github.com/cilium/cilium/blob/5d1025eda37fa8bdfebddc4b413b143113e06a09/pkg/policy/groups/actions.go#L130-L177

### PR DESCRIPTION
**Pull request by fristonio**
```release-note
Fix the creation of "toGroups" derivative policies for "CiliumClusterwideNetworkPolicies".
```

See commit message for a detailed explanation.

* The third commit only includes a Documentation change discussed on slack. This is to make sure someone does not get confused when working with `toServices` rules. The type docs now specify the current status of `toServices` in Cilium, which is that we only support toServices for K8s services without a selector.

Tested on EKS(k8s version 1.17). 

Create a new CiliumClusterwideNetworkPolicy with `toGroups`.

```
$ cat ccnp.yaml && kubectl apply -f ccnp.yaml
kind: CiliumClusterwideNetworkPolicy
apiVersion: cilium.io/v2
metadata:
  name: to-groups-sample-ccnp
spec:
  endpointSelector:
    matchLabels:
      app: test
  egress:
  - toPorts:
    - ports:
      - port: '80'
        protocol: TCP
    toGroups:
    - aws:
        securityGroupsIds:
        - 'sg-xxxxxxx'
```

Check the deployed policies and automatically created derived policy.

```
$ kubectl get ccnp
NAME                                                                  AGE
to-groups-sample-ccnp                                                 13m
to-groups-sample-ccnp-togroups-d0c962bc-6e7a-4535-9b41-f334668a7cfc   13m

$ kubectl get ccnp to-groups-sample-ccnp-togroups-d0c962bc-6e7a-4535-9b41-f334668a7cfc -o yaml
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  creationTimestamp: "2020-08-18T16:53:03Z"
  generation: 1
  labels:
    io.cilium.network.policy.kind: derivative
    io.cilium.network.policy.parent.uuid: d0c962bc-6e7a-4535-9b41-f334668a7cfc
  name: to-groups-sample-ccnp-togroups-d0c962bc-6e7a-4535-9b41-f334668a7cfc
  ownerReferences:
  - apiVersion: cilium.io/v2
    blockOwnerDeletion: true
    kind: CiliumClusterwideNetworkPolicy
    name: to-groups-sample-ccnp
    uid: d0c962bc-6e7a-4535-9b41-f334668a7cfc
  resourceVersion: "58976"
  selfLink: /apis/cilium.io/v2/ciliumclusterwidenetworkpolicies/to-groups-sample-ccnp-togroups-d0c962bc-6e7a-4535-9b41-f334668a7cfc
  uid: 8c503b6e-d784-4a73-86dd-d0465e2a44b0
specs:
- egress:
  - toCIDRSet:
    - cidr: x.x.x.x/32
    - cidr: x.x.x.x.x/32
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
  endpointSelector:
    matchLabels:
      any:app: test
  labels:
  - key: io.cilium.k8s.policy.derived-from
    source: k8s
    value: CiliumClusterwideNetworkPolicy
  - key: io.cilium.k8s.policy.name
    source: k8s
    value: to-groups-sample-ccnp
  - key: io.cilium.k8s.policy.uid
    source: k8s
    value: d0c962bc-6e7a-4535-9b41-f334668a7cfc
```

- [x] Fixes #12857 
- [x] Add unit tests to check changed behaviour.

### CODE REVIEW

File: pkg/policy/groups/actions.go [hunk 1]
```diff
@@ -55,7 +55,27 @@ func AddDerivativeCNPIfNeeded(cnp *cilium_v2.CiliumNetworkPolicy) bool {
...
+				return addDerivativePolicy(ctx, cnp, false)
+			},
+		})
+	return true
+}
+
+// AddDerivativeCCNPIfNeeded will create a new CCNP if the given NetworkPolicy has any rule
+// that need to create a new derivative policy.
+// It returns a boolean, true in case that all actions are correct, false if
+// something fails
```
Comment (christarazi) [inline pkg/policy/groups/actions.go]: Nit:

```suggestion
// AddDerivativeCCNPIfNeeded will create a new CCNP if the given NetworkPolicy has any rules
// that need to create a new derivative policy.
// It returns a boolean, true in case that all actions are correct, false if
// something fails.
```

File: pkg/policy/groups/helpers.go [hunk 2]
```diff
@@ -123,24 +169,74 @@ func updateDerivativeStatus(cnp *cilium_v2.CiliumNetworkPolicy, derivativeName s
...
+		Get(context.TODO(), cnp.ObjectMeta.Name, v1.GetOptions{})
+
+	if clientErr != nil {
+		return fmt.Errorf("cannot get Kubernetes policy: %s", clientErr)
+	}
+
+	if k8sCCNP.ObjectMeta.UID != cnp.ObjectMeta.UID {
+		// This case should not happen, but if the UID does not match make sure
+		// that the new policy is not in the cache to not loop over it. The
+		// kubernetes watcher should take care about that.
```
Comment (christarazi) [inline pkg/policy/groups/helpers.go]:
```suggestion
		// This case should not happen, but if the UID does not match make sure
		// that the new policy is not in the cache to not loop over it. The
		// kubernetes watcher should take care of that.
```

**Comment by fristonio** [comment]
test-me-please

File: pkg/policy/groups/actions.go [hunk 3]
```diff
@@ -85,10 +105,42 @@ func UpdateDerivativeCNPIfNeeded(newCNP *cilium_v2.CiliumNetworkPolicy, oldCNP *
...
+				return addDerivativePolicy(ctx, newCNP, false)
+			},
+		})
+	return true
+}
+
+// UpdateDerivativeCCNPIfNeeded updates or creates a CCNP if the given CCNP has
+// any rule that needs to create a new derivative policy(eg: ToGroups). In case
+// that the new CCNP does not have any derivative policy and the old one had
+// one, it will delete the old policy.
```
Comment (christarazi) [inline pkg/policy/groups/actions.go:122]: I think we can document when this returns `true` or `false`. Can you update the other similar functions as well?

File: pkg/policy/groups/actions.go [hunk 4]
```diff
@@ -127,53 +178,90 @@ func DeleteDerivativeCNP(cnp *cilium_v2.CiliumNetworkPolicy) error {
...
+		})
+	} else {
+		scopedLog = log.WithFields(logrus.Fields{
+			logfields.CiliumNetworkPolicyName: cnp.ObjectMeta.Name,
+			logfields.K8sNamespace:            cnp.ObjectMeta.Namespace,
+		})
+	}
+
+	var derivativePolicy *cilium_v2.CiliumNetworkPolicy
+	var derivativeErr, err error
```
Comment (christarazi) [inline pkg/policy/groups/actions.go]: Style nit:

Can you use:

```
var (
...
)
```

File: pkg/policy/groups/helpers.go [hunk 5]
```diff
@@ -65,9 +67,32 @@ func createDerivativeCNP(ctx context.Context, cnp *cilium_v2.CiliumNetworkPolicy
...
+		// Update the Kind of owner if the policy is CCNP derived.
+		derivativeCNP.ObjectMeta.OwnerReferences[0].Kind = cilium_v2.CCNPKindDefinition
+		rules, err = ccnp.Parse()
+	} else {
+		rules, err = cnp.Parse()
+	}
+
 	if err != nil {
-		return nil, fmt.Errorf("Cannot parse policies: %s", err)
+		return derivativeCNP, fmt.Errorf("Cannot parse policies: %s", err)
```
Comment (christarazi) [inline pkg/policy/groups/helpers.go]: Why was it necessary to change this?

Comment (christarazi) [reply pkg/policy/groups/helpers.go]: Nit:

```suggestion
		return derivativeCNP, fmt.Errorf("cannot parse policies: %v", err)
```

File: pkg/policy/groups/helpers.go [hunk 6]
```diff
@@ -123,24 +169,74 @@ func updateDerivativeStatus(cnp *cilium_v2.CiliumNetworkPolicy, derivativeName s
...
 	// This CNP can be modified by cilium agent or operator. To be able to push
 	// the status correctly fetch the last version to avoid updates issues.
-	k8sCNPStatus, clientErr := k8s.CiliumClient().CiliumV2().
-		CiliumNetworkPolicies(cnp.ObjectMeta.Namespace).
+	k8sCNP, clientErr := k8s.CiliumClient().CiliumV2().CiliumNetworkPolicies(cnp.ObjectMeta.Namespace).
 		Get(context.TODO(), cnp.ObjectMeta.Name, v1.GetOptions{})
+
 	if clientErr != nil {
-		return fmt.Errorf("Cannot get Kubernetes policy: %s", clientErr)
+		return fmt.Errorf("cannot get Kubernetes policy: %s", clientErr)
```
Comment (christarazi) [inline pkg/policy/groups/helpers.go]: Nit: in the places that you've modified the error return, change the format string to `%v` for errors, instead of `%s`.

File: pkg/policy/groups/helpers.go [hunk 7]
```diff
@@ -123,24 +169,74 @@ func updateDerivativeStatus(cnp *cilium_v2.CiliumNetworkPolicy, derivativeName s
...
+	k8sCCNP.SetDerivedPolicyStatus(derivativeName, status)
+	groupsCNPCache.UpdateCNP(&cilium_v2.CiliumNetworkPolicy{
+		TypeMeta:   k8sCCNP.TypeMeta,
+		ObjectMeta: k8sCCNP.ObjectMeta,
+		Spec:       k8sCCNP.Spec,
+		Specs:      k8sCCNP.Specs,
+		Status:     k8sCCNP.Status,
+	})
+
+	// TODO: Switch to JSON patch
```
Comment (christarazi) [inline pkg/policy/groups/helpers.go:279]: Is this meant for this PR or as a followup? Might be nice to provide context why.

**Review by christarazi — CHANGES_REQUESTED** [review]
LGTM overall; some minor nits / questions to address.

File: pkg/policy/groups/helpers.go (hunk 5 above)
Comment (fristonio) [reply pkg/policy/groups/helpers.go]: https://github.com/cilium/cilium/blob/fb0c3e592d7a9da854f9d38345fbb5720ea3b073/pkg/policy/groups/actions.go#L149-L156 - Here in line 156 we use `derivativeCNP.ObjectMeta.Name`. Now if `cnp.Parse()` fails in `createDerivativeCNP` and returns nil this will panic.

File: pkg/policy/groups/helpers.go (hunk 7 above)
Comment (fristonio) [reply pkg/policy/groups/helpers.go:279]: This will be a follow-up. This is an old TODO actually that we had from earlier, so I wanted to take this up in a separate PR.

File: pkg/policy/groups/helpers.go (hunk 5 above)
Comment (christarazi) [reply pkg/policy/groups/helpers.go]: Thanks for the explanation. That makes sense. Can you add a comment as to why we return a valid pointer in the error case? The convention is usually to return `nil`, so it might catch other people's eyes by surprise.

**Review by christarazi — APPROVED** [review]

**Review by christarazi — APPROVED** [review]
LGTM; just need to address:

> Thanks for the explanation. That makes sense. Can you add a comment as to why we return a valid pointer in the error case? The convention is usually to return nil, so it might catch other people's eyes by surprise.

and should be good to go. No need for second review.

File: pkg/policy/groups/helpers.go (hunk 5 above)
Comment (fristonio) [reply pkg/policy/groups/helpers.go]: Thanks for the review, I have updated the pull request.

File: pkg/policy/groups/actions.go [hunk 8]
```diff
@@ -85,10 +107,44 @@ func UpdateDerivativeCNPIfNeeded(newCNP *cilium_v2.CiliumNetworkPolicy, oldCNP *
...
+// one, it will delete the old policy.
+// The function returns true if an update is required for the derivative policy
+// and false otherwise.
+func UpdateDerivativeCCNPIfNeeded(newCCNP *cilium_v2.CiliumNetworkPolicy, oldCCNP *cilium_v2.CiliumNetworkPolicy) bool {
+	if !newCCNP.RequiresDerivative() && oldCCNP.RequiresDerivative() {
+		log.WithFields(logrus.Fields{
+			logfields.CiliumClusterwideNetworkPolicyName: newCCNP.ObjectMeta.Name,
+		}).Info("New CCNP does not have derivative policy, but old had. Deleting old policies")
+
+		controllerManager.UpdateController(fmt.Sprintf("delete-derivatve-ccnp-%s", oldCCNP.ObjectMeta.Name),
```
Comment (jrajahalme) [inline pkg/policy/groups/actions.go]: "derivatve" -> "derivative"

File: pkg/policy/groups/actions.go [hunk 9]
```diff
@@ -127,53 +182,92 @@ func DeleteDerivativeCNP(cnp *cilium_v2.CiliumNetworkPolicy) error {
...
+		derivativeErr, err error
+	)
 
 	// The maxNumberOfAttempts is to not hit the limits of cloud providers API.
 	// Also, the derivativeErr is never returned, if not the controller will
 	// hit this function and the cloud providers limit will be raised. This
 	// will cause a disaster, due all other policies will hit the limit as
 	// well.
-	// If the createDerivativeCNP() fails, a new all block rule will be inserted and
+	// If the createDerivative{CNP,CCNP}() fails, a new all block rule will be inserted and
```
Comment (jrajahalme) [inline pkg/policy/groups/actions.go]: Seems like this change does not reflect the code below.

File: pkg/policy/groups/helpers.go [hunk 10]
```diff
@@ -123,24 +172,74 @@ func updateDerivativeStatus(cnp *cilium_v2.CiliumNetworkPolicy, derivativeName s
 		status.OK = true
 	}
 
+	if clusterScoped {
+		return updateDerivativeCNPStatus(cnp, status, derivativeName)
+	}
+
+	return updateDerivativeCCNPStatus(cnp, status, derivativeName)
```
Comment (jrajahalme) [inline pkg/policy/groups/helpers.go]: The logic here seems flipped, `clusterScoped == true` should pair with `CCNP`, not the other way around?

File: pkg/policy/groups/helpers_test.go [hunk 11]
```diff
@@ -57,13 +57,22 @@ func (s *GroupsTestSuite) TestCorrectDerivativeName(c *C) {
 		derivativeCNP.ObjectMeta.Name,
 		Equals,
 		fmt.Sprintf("%s-togroups-%s", name, cnp.ObjectMeta.UID))
+
+	// Test clusterwide policy helper functions
+	ccnpName := "ccnp-test"
+	ccnp := getSamplePolicy(ccnpName, "")
+	derivativeCCNP, err := createDerivativeCNP(context.TODO(), ccnp, true)
```
Comment (jrajahalme) [inline pkg/policy/groups/helpers_test.go]: Naming here is confusing as `createDerivativeCNP()` would indicate a `CNP` being created, but then a `CCNP` is returned?

**Review by jrajahalme — CHANGES_REQUESTED** [review]
Mostly minor nits, but also one logic flaw below.

File: pkg/policy/groups/actions.go (hunk 9 above)
Comment (fristonio) [reply pkg/policy/groups/actions.go]: Ah, I forgot to change it back when I reverted some changes.

File: pkg/policy/groups/helpers.go (hunk 10 above)
Comment (fristonio) [reply pkg/policy/groups/helpers.go]: Yeah, good catch.

File: pkg/policy/groups/helpers_test.go (hunk 11 above)
Comment (fristonio) [reply pkg/policy/groups/helpers_test.go]: That makes sense, I will update the name.

**Comment by fristonio** [comment]
test-me-please

File: pkg/policy/groups/actions.go (hunk 8 above)
Comment (aanm) [inline pkg/policy/groups/actions.go]: You fixed the typo on line 97 but you copy paste it here :)

File: pkg/policy/groups/actions.go [hunk 12]
```diff
@@ -127,15 +182,47 @@ func DeleteDerivativeCNP(cnp *cilium_v2.CiliumNetworkPolicy) error {
...
 
-	var derivativeCNP *cilium_v2.CiliumNetworkPolicy
-	var derivativeErr error
+	if !ccnp.RequiresDerivative() {
+		scopedLog.Debug("CCNP does not have derivative policies, skipped")
+		return nil
+	}
+
+	err := k8s.CiliumClient().CiliumV2().CiliumClusterwideNetworkPolicies().DeleteCollection(
+		context.TODO(),
```
Comment (aanm) [inline pkg/policy/groups/actions.go:198]: follow up, we can pass the context from the controller that is calling this function.

File: pkg/policy/groups/actions.go [hunk 13]
```diff
@@ -127,15 +182,47 @@ func DeleteDerivativeCNP(cnp *cilium_v2.CiliumNetworkPolicy) error {
...
+		scopedLog = log.WithFields(logrus.Fields{
+			logfields.CiliumNetworkPolicyName: cnp.ObjectMeta.Name,
+			logfields.K8sNamespace:            cnp.ObjectMeta.Namespace,
+		})
+	}
+
+	var (
+		derivativePolicy   *cilium_v2.CiliumNetworkPolicy
+		derivativeErr, err error
+	)
```
Comment (aanm) [inline pkg/policy/groups/actions.go]: Nit, we can initialize the all vars on line 210 (I'm referring to these ones and the `scopedLog`)

File: pkg/policy/groups/cache_test.go [hunk 14]
```diff
@@ -21,7 +21,6 @@ import (
 )
 
 func (s *GroupsTestSuite) TestCacheWorkingCorrectly(c *C) {
-
```
Comment (aanm) [inline pkg/policy/groups/cache_test.go]: This file has irrelevant changes

File: pkg/policy/groups/helpers.go [hunk 15]
```diff
@@ -44,7 +44,9 @@ func getDerivativeName(cnp *cilium_v2.CiliumNetworkPolicy) string {
 }
 
 // createDerivativeCNP will return a new CNP based on the given rule.
-func createDerivativeCNP(ctx context.Context, cnp *cilium_v2.CiliumNetworkPolicy) (*cilium_v2.CiliumNetworkPolicy, error) {
+// ccnpDerived argument indicates if the provided CNP is derived from CCNP or not.
+// This is to make sure we call `Parse()` for the right construct so it don't fail.
+func createDerivativeCNP(ctx context.Context, cnp *cilium_v2.CiliumNetworkPolicy, ccnpDerived bool) (*cilium_v2.CiliumNetworkPolicy, error) {
```
Comment (aanm) [inline pkg/policy/groups/helpers.go]: It's probably better to create another function that `createDerivativeCCNP`. My main concern is that we are mixing up the 2 types (CCNP and CNP) and we might create bugs because of that.

Discussed offline.

**Review by aanm — CHANGES_REQUESTED** [review]

**Comment by fristonio** [comment]
test-me-please

File: pkg/policy/groups/helpers.go [hunk 16]
```diff
@@ -91,6 +99,71 @@ func createDerivativeCNP(ctx context.Context, cnp *cilium_v2.CiliumNetworkPolicy
...
+		if !rule.RequiresDerivative() {
+			derivativeCCNP.Specs[i] = rule
+			continue
+		}
+		newRule, err := rule.CreateDerivative(ctx)
+		if err != nil {
+			return derivativeCCNP, err
+		}
+		derivativeCCNP.Specs[i] = newRule
+	}
```
Comment (aanm) [inline pkg/policy/groups/helpers.go:163]: This can be done as a follow up but this section is the same as done in the `createDerivativeCNP`. This can be done as part of a dedicated function.

I can see that `createDerivativeCCNP` is returning a CCNP on line 160 (in case of a error) which would make it difficult to have a dedicated function for this section. That's why I'm saying that it can be done as a follow up because it will require changes in the caller of the `createDerivativeCCNP` to ignore the returned CCNP in case of an error. We shouldn't use the returned values if `err != nil`.

File: pkg/policy/groups/actions.go [hunk 17]
```diff
@@ -146,34 +234,47 @@ func addDerivativeCNP(ctx context.Context, cnp *cilium_v2.CiliumNetworkPolicy) e
...
+		}
+
 		if derivativeErr == nil {
 			break
 		}
 		metrics.PolicyImportErrors.Inc()
 		metrics.PolicyImportErrorsTotal.Inc()
 		scopedLog.WithError(derivativeErr).Error("Cannot create derivative rule. Installing deny-all rule.")
-		statusErr := updateDerivativeStatus(cnp, derivativeCNP.ObjectMeta.Name, derivativeErr)
+		statusErr := updateDerivativeStatus(cnp, derivativePolicy.GetName(), derivativeErr, clusterScoped)
```
Comment (aanm) [inline pkg/policy/groups/actions.go:251]: follow up, we shouldn't use `derivativePolicy` if `derivativeErr != nil`

File: pkg/policy/groups/actions.go [hunk 18]
```diff
@@ -146,34 +234,47 @@ func addDerivativeCNP(ctx context.Context, cnp *cilium_v2.CiliumNetworkPolicy) e
 	// the derivative status in the parent policy  will be updated with the
 	// error.
 	for numAttempts := 0; numAttempts <= maxNumberOfAttempts; numAttempts++ {
```
Comment (aanm) [inline pkg/policy/groups/actions.go:236]: Follow up, this should be more reliable, with a controller for example.

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

File: pkg/policy/groups/helpers.go (hunk 16 above)
Comment (fristonio) [reply pkg/policy/groups/helpers.go:163]: Make sense. I will create a follow-up issue once this is merged to address all the remaining issues.
