### PR TITLE
Fixing policy delete root

### LINKED ISSUE #410: cilium endpoint list takes too much time

### PR DESCRIPTION
**Pull request by aanm**
Fixes #410 #411 
The commits have their own descriptions. I can't split the commits into multiple PRs since they are slightly tight together.

I ran the test from #436  (start 10 containers, wait them to be ready then delete those 10 containers) against this PR and against master. I got this results:
master:
```
real 125.61
user 1.54
sys 0.33
```
This PR:
```
real 8.20
user 1.96
sys 0.38
```

I ran the runtime tests multiple times to ensure I didn't see any race conditions nor deadlocks (with and without `--race` flag).

### CODE REVIEW

**Comment by aanm** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/cilium/cilium/pull/424'>Refresh</a>.<a href='#crh-update-none'></a>

File: tests/07-performance.sh [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+
+set -e
+
+current_branch="$(git rev-parse --abbrev-ref HEAD)"
+TEST_NET="cilium"
+
+function cleanup {
+    cd "${dir}/.."
+	git checkout "${current_branch}"
+	git stash pop
```
Comment (tgraf) [inline tests/07-performance.sh]: indent

File: tests/07-performance.sh [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+    sudo make install
+    sudo service cilium-docker restart
+}
+
+trap cleanup EXIT
+
+function install_master {
+    cd "${dir}/.."
+    git stash
+    git checkout origin/master
```
Comment (tgraf) [inline tests/07-performance.sh]: This is pretty brutal. I totally get where you want to go an this data is very useful. I'm not sure we can stash/pop an just bluntly run make install in a test. People may run this outside of vagrant inside their dev environment. I'll think about this.

Comment (aanm) [reply tests/07-performance.sh]: Yeah, I got problems myself when there was nothing to stash and when cleaning up I was blindly doing `git stash pop`

**Comment by tgraf** [comment]
Can we split this into two PRs. One which introduces the parallel build and one which adds the test? We could use the parallel builds for the released version.

**Comment by aanm** [comment]
>Can we split this into two PRs. One which introduces the parallel build and one which adds the test? We could use the parallel builds for the released version.

Done #436

**Comment by tgraf** [comment]
@aanm Can you fix the unit test? This looks ready to be merged otherwise.

**Comment by aanm** [comment]
@tgraf I wasn't aware of the unit tests, I'm still working on this ;-)

**Review by tgraf — DISMISSED** [review]

**Comment by aanm** [comment]
@tgraf l7 proxy demo doesn't work + the go race tool detects some data races that makes me feel uncomfortable and I was not able to fix them all.

File: pkg/option/option.go [hunk 3]
```diff
@@ -121,6 +122,7 @@ func (om OptionMap) DeepCopy() OptionMap {
 }
 
 type BoolOptions struct {
+	optsMU  sync.RWMutex
```
Comment (tgraf) [inline pkg/option/option.go]: 👍

File: pkg/bpf/bpffs.go [hunk 4]
```diff
@@ -29,8 +30,13 @@ var (
 
 	// Set to true on first get request to detect misorder
 	lockedDown = false
+	once       sync.Once
```
Comment (tgraf) [inline pkg/bpf/bpffs.go:33]: Did you run into a race with the existing code? I wonder whether it makes sense to start using abool instead.
https://github.com/tevino/abool

I assume that setting the boolean will not include any memory barriers so if other go subroutines rely on this it would still race. The existing code was not assuming parallelism but just coding mistakes.

File: daemon/docker_watcher.go [hunk 5]
```diff
@@ -280,9 +270,11 @@ func (d *Daemon) handleCreateContainer(id string, retry bool) {
 		}
 
 		var orchLabelsModified bool
-		containerCopy, ok := d.retrieveWorkingContainerCopy(id)
+		d.containersMU.RLock()
+		containerCopy, ok := d.containers[id]
+		d.containersMU.RUnlock()
```
Comment (tgraf) [inline daemon/docker_watcher.go]: We should rename the variable as it is not a copy anymore. Can be done in a follow-up commit though.

File: daemon/docker_watcher.go [hunk 6]
```diff
@@ -280,9 +270,11 @@ func (d *Daemon) handleCreateContainer(id string, retry bool) {
...
 		if ok {
-			if orchLabelsModified = updateOrchLabels(&containerCopy, lbls); !orchLabelsModified {
+			if orchLabelsModified = updateOrchLabels(containerCopy, lbls); !orchLabelsModified {
```
Comment (tgraf) [inline daemon/docker_watcher.go]: How is it guaranteed that only one go subroutine modifies the container object via `updateOrchLabels()`?

File: pkg/policy/rule_consumers.go [hunk 7]
```diff
@@ -112,7 +112,7 @@ func (a *AllowRule) Allows(ctx *SearchContext) ConsumableDecision {
 // RuleConsumers allows the following consumers.
 type RuleConsumers struct {
 	Coverage []*labels.Label `json:"coverage,omitempty"`
-	Allow    []AllowRule     `json:"allow"`
+	Allow    []*AllowRule    `json:"allow"`
```
Comment (tgraf) [inline pkg/policy/rule_consumers.go]: What is the motivation behind this change?

File: pkg/labels/labels.go [hunk 8]
```diff
@@ -98,8 +99,9 @@ type Label struct {
 	Key   string `json:"key"`
 	Value string `json:"value,omitempty"`
 	// Source can be on of the values present in const.go (e.g.: CiliumLabelSource)
-	Source string `json:"source"`
-	absKey string
+	Source   string `json:"source"`
+	absKeyMU sync.RWMutex
```
Comment (tgraf) [inline pkg/labels/labels.go]: Can you explain the case where this mutex is needed? Is the Label shared between multiple rules?

File: daemon/ct.go [hunk 9]
```diff
@@ -65,21 +65,23 @@ func (d *Daemon) EnableConntrackGC() {
...
 
 			for k := range d.endpoints {
 				e := d.endpoints[k]
+				e.Mutex.RLock()
 				if e.Consumable == nil {
+					e.Mutex.RUnlock()
 					continue
 				}
-
+				e.Mutex.RUnlock()
```
Comment (tgraf) [inline daemon/ct.go:77]: Why is it safe to continue accessing the endpoint structure after unlocking the mutex? Are you just using the mutex to protect the Consumable pointer? If so, please document it.

File: daemon/config.go [hunk 10]
```diff
@@ -38,6 +38,7 @@ type Config struct {
 	BpfDir                string                  // BPF template files directory
 	LibDir                string                  // Cilium library files directory
 	RunDir                string                  // Cilium runtime directory
+	LXCMapMU              sync.Mutex              // LXCMapMU is the mutex to access the LXCMap FIXME move this to the LXCMap struct?
```
Comment (tgraf) [inline daemon/config.go]: Yes, please move to LXCMap struct. I think we should even move it into the generic BPF map abstraction.

File: daemon/daemon.go [hunk 11]
```diff
@@ -80,6 +81,9 @@ type Daemon struct {
 	loopbackIPv4       net.IP
 	maxCachedLabelIDMU sync.RWMutex
 	maxCachedLabelID   policy.NumericIdentity
+	buildEndpointChan  chan *endpoint.Request
+	uniqueID           map[uint16]bool
```
Comment (tgraf) [inline daemon/daemon.go]: We should stop hardcoding uint16 everyone. It will be very painful to undo. Let's just use uint64 here to never run into any issues. The build ID must not directly translate to a uint16 datapath ID.

File: daemon/daemon.go [hunk 12]
```diff
@@ -88,13 +92,69 @@ func (d *Daemon) GetProxy() *proxy.Proxy {
...
+// RemoveFromEndpointQueue removes the endpoint from the queue.
+func (d *Daemon) RemoveFromEndpointQueue(epID uint16) {
+	d.uniqueIDMU.Lock()
+	delete(d.uniqueID, epID)
+	d.uniqueIDMU.Unlock()
+}
+
+// EndpointBuilder creates #CPUs go routines that listen on the
+// `d.buildEndpointChan` for new endpoints.
+func (d *Daemon) EndpointBuilder() {
```
Comment (tgraf) [inline daemon/daemon.go]: Can we call this `StartEndpointBuilders()`?

File: daemon/daemon.go [hunk 13]
```diff
@@ -88,13 +92,69 @@ func (d *Daemon) GetProxy() *proxy.Proxy {
...
+	log.Debugf("Creating %d worker threads", runtime.NumCPU())
+	// Create the same amount of worker threads as there are CPUs
+	for w := 0; w < runtime.NumCPU(); w++ {
```
Comment (tgraf) [inline daemon/daemon.go]: This should be configurable as well.

Comment (tgraf) [reply daemon/daemon.go]: Although I'm fine leaving it as-is for an initial version.

File: daemon/daemon.go [hunk 14]
```diff
@@ -88,13 +92,69 @@ func (d *Daemon) GetProxy() *proxy.Proxy {
...
+				// Set the endpoint to "building" state
+				d.uniqueID[e.ID] = true
+				e.MyTurn <- true
+				d.uniqueIDMU.Unlock()
+				// Wait for the endpoint to build
+				<-e.Done
+				d.uniqueIDMU.Lock()
+				if isBuilding := d.uniqueID[e.ID]; isBuilding {
+					// Delete the endpoint from the queue
+					// only if was marked as isBuilding
```
Comment (tgraf) [inline daemon/daemon.go]: The comment states what the code does which is obvious, why is it only deleting the entry if it was marked? In what case is it not marked given we do `d.uniqueID[e.ID] = true` just above?

File: daemon/daemon.go [hunk 15]
```diff
@@ -88,13 +92,69 @@ func (d *Daemon) GetProxy() *proxy.Proxy {
...
 		return fmt.Errorf("Unable to update eBPF map: %s", err)
 	}
 
 	return nil
 }
 
+// QueueEndpoint puts the given request in the endpoints queue for processing.
+// The given request will receive 'true' in the MyTurn channel whenever it's its
+// turn or false if the request was denied/canceled.
+func (d *Daemon) QueueEndpoint(req *endpoint.Request) {
```
Comment (tgraf) [inline daemon/daemon.go]: Can we rename this to `QueueEndpointBuild()`?

File: pkg/labels/labels.go.orig [hunk 16]
```diff
@@ -0,0 +1,499 @@
+// Copyright 2016-2017 Authors of Cilium
```
Comment (tgraf) [inline pkg/labels/labels.go.orig]: Unwanted addition to the commit

File: pkg/endpoint/policy.go [hunk 17]
```diff
@@ -311,41 +309,61 @@ func (e *Endpoint) regenerate(owner Owner) error {
...
+// Regenerate forces the regeneration of endpoint programs & policy
+func (e *Endpoint) Regenerate(owner Owner) <-chan bool {
+	newReq := &Request{
+		ID:           e.ID,
+		MyTurn:       make(chan bool),
+		Done:         make(chan bool),
+		ExternalDone: make(chan bool),
+	}
+	owner.QueueEndpoint(newReq)
+	go func(e *Endpoint, myTurn <-chan bool, finish chan<- bool, externalFinish chan<- bool) {
```
Comment (tgraf) [inline pkg/endpoint/policy.go]: Should this goroutine be cancelled if the endpoint is deleted before the build happens?

**Review by tgraf — CHANGES_REQUESTED** [review]

File: pkg/bpf/bpffs.go (hunk 4 above)
Comment (aanm) [reply pkg/bpf/bpffs.go:33]: Are you talking of the race conditions between line 41 and the others like 48 for example?

File: daemon/docker_watcher.go (hunk 5 above)
Comment (aanm) [reply daemon/docker_watcher.go]: It was fixed on a later commit, should I fix this on this commit?

File: daemon/docker_watcher.go (hunk 6 above)
Comment (aanm) [reply daemon/docker_watcher.go]: I made a whole bunch of changes on this PR and afterwards I split them into logic commits. The `containerCopy` is not guarantee that only a go subroutine modifies the container object at this time. I can move the `d.containerMU.RUnlock()` after the `updateOrchLabels` as a `Unlock()` on this commit. That way there won't be "bad" commits, sounds good?

File: pkg/policy/rule_consumers.go (hunk 7 above)
Comment (aanm) [reply pkg/policy/rule_consumers.go]: `AllowRule` contains a `Label` which contains a mutex. `go vet` complains that the mutex pointer is being copied if the `AllowRule` is not a pointer.

File: pkg/bpf/bpffs.go (hunk 4 above)
Comment (tgraf) [reply pkg/bpf/bpffs.go:33]: The whole point of `lockedDown` is to catch whether the map root prefix is changed after the map root has been read. My question is whether you saw an actual race because just using `once` doesn't change the fact that this will still not have memory barriers around the access of `lockedDown` os if there was a real race, this would not fix it.

Comment (aanm) [reply pkg/bpf/bpffs.go:33]: Addressed

File: pkg/labels/labels.go (hunk 8 above)
Comment (aanm) [reply pkg/labels/labels.go]: There was a race condition, the `AbsoluteKey()` is called in multiple place like policy check, that can happen in parallel.

File: daemon/config.go (hunk 10 above)
Comment (aanm) [reply daemon/config.go]: Moved to LXCMap struct. Created an issue to have a mutex in the generic BPF map abstraction.

File: daemon/ct.go (hunk 9 above)
Comment (aanm) [reply daemon/ct.go:77]: I add this:
```
// We can unlock the endpoint mutex sense
// in runGC it will be locked as needed.
```
Sounds sufficient?

File: daemon/daemon.go (hunk 11 above)
Comment (aanm) [reply daemon/daemon.go]: Addressed

File: daemon/daemon.go (hunk 15 above)
Comment (aanm) [reply daemon/daemon.go]: Addressed

File: daemon/daemon.go (hunk 12 above)
Comment (aanm) [reply daemon/daemon.go]: Addressed

File: daemon/daemon.go (hunk 13 above)
Comment (aanm) [reply daemon/daemon.go]: Addressed

File: daemon/daemon.go (hunk 14 above)
Comment (aanm) [reply daemon/daemon.go]:
```
// In a case where the same endpoint enters the
// building queue, while it was still being build,
// it will be marked as `false`/"not building",
// thus, we only delete the endpoint from the
// queue only if it is marked as isBuilding.
```
Better?

File: pkg/endpoint/policy.go (hunk 17 above)
Comment (aanm) [reply pkg/endpoint/policy.go]: Nice catch, I changed the `StartEndpointBuilders` code a little bit:
```
...
go func() {
			for e := range d.buildEndpointChan {
				d.uniqueIDMU.Lock()
+				if _, ok := d.uniqueID[e.ID]; !ok {
+					// If the request is not present in the uniqueID,
+					// it means the request was deleted from the queue
+					// so we deny the request's turn.
+					e.MyTurn <- false
+					d.uniqueIDMU.Unlock()
+					continue
+				}
				// Set the endpoint to "building" state
				d.uniqueID[e.ID] = true
				e.MyTurn <- true
				d.uniqueIDMU.Unlock()
```

This way the goroutine sees that its turn was denied and ends cleanly.

File: pkg/labels/labels.go.orig (hunk 16 above)
Comment (aanm) [reply pkg/labels/labels.go.orig]: Addressed

File: daemon/docker_watcher.go (hunk 5 above)
Comment (tgraf) [reply daemon/docker_watcher.go]: That's fine then.

File: daemon/docker_watcher.go (hunk 6 above)
Comment (tgraf) [reply daemon/docker_watcher.go]: Sounds good.

File: daemon/ct.go (hunk 9 above)
Comment (tgraf) [reply daemon/ct.go:77]: The comment doesn't make sense to me because I don't see `runGC` taking any locks. I assuming accessing `e.ID` and calling `e.LogStatus` is fine without a lock is fine as we are holding `d.endpointsMU` so endpoints can't disappear. I think overall what will help to put a comment to every mutex to describe what the mutex is supposed to protect exactly. Is `e.Mutex` is supposed to protect writes to endpoints but reads are fine?

Comment (aanm) [reply daemon/ct.go:77]: Yes, that's true. So usually, mutexes are put before the variable they are protecting. That's something missing in the our mutexes. The endpoint ID is being written once, and that happens inside the endpoint with `NewEndpointFromChangeModel`, we don't need a mutex for the ID because of that. The `e.LogStatus` can be called because it's a public method and all public methods can be called since the lock will be locked by the receiver's function.

I'll move all mutex to the proper places and add a comment regarding which variables are they protecting.

**Comment by tgraf** [comment]
Other than the mutex related comment, this looks good to go otherwise.

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
BTW, please add an entry to `NEWS.rst` file to describe this big enhacement

**Comment by aanm** [comment]
@tgraf the news.rst sounds good?

**Review by tgraf — APPROVED** [review]
