### PR TITLE
pkg/node: change setDefaultPrefix for ipv6

### LINKED ISSUE #38471: ipv6 only cluster doesn't work well with multi pool ipam
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.2 and lower than v1.18.0

### What happened?

If using IPAM multi pool in ipv6 only environment with some k8s distribution(Openshift and EKS). the agent could complains
`level=fatal msg="Cannot autocomplete node addresses" error="IPv6 allocation CIDR is not configured. Please specify --ipv6-range" subsys=daemon
`

That's because their k8s nodes could have empty spec for example
```
apiVersion: v1
kind: Node
metadata:
  annotations:
    machineconfiguration.openshift.io/controlPlaneTopology: HighlyAvailable
    machineconfiguration.openshift.io/currentConfig: rendered-worker-e3216e04ae1b9e67ce70c8c1f555cce5
    machineconfiguration.openshift.io/desiredConfig: rendered-worker-e3216e04ae1b9e67ce70c8c1f555cce5
    machineconfiguration.openshift.io/desiredDrain: uncordon-rendered-worker-e3216e04ae1b9e67ce70c8c1f555cce5
    machineconfiguration.openshift.io/lastAppliedDrain: uncordon-rendered-worker-e3216e04ae1b9e67ce70c8c1f555cce5
    machineconfiguration.openshift.io/lastSyncedControllerConfigResourceVersion: "19503"
    machineconfiguration.openshift.io/reason: ""
    machineconfiguration.openshift.io/state: Done
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2025-03-23T16:21:06Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: ocp-workers-0
    kubernetes.io/os: linux
    node-role.kubernetes.io/worker: ""
    node.openshift.io/os_id: rhcos
  name: ocp-workers-0
  resourceVersion: "282168"
  uid: 7340c9f7-dc9f-4e47-8633-eac706f97239
spec: {}
```
However, our agent code doesn't consider the newer IPAM mode(like multi-pool) and only copy from `CiliumNode` when it's cluster-pool mode.

https://github.com/liyihuang/cilium/blob/4912f7a79eabc8e7bd3eec5a0364cde15fe87ec5/daemon/k8s/init.go#L38-L77

In dual stack mode, we assign the ipv6 CIDR from the ipv4.
https://github.com/cilium/cilium/blob/50a5a2e21f8dcce67f241203a99c6aba9dab4b2c/pkg/node/address.go#L138-L149

If it's ipv6 mode, we will get the error log that I posted here.

### How can we reproduce the issue?

disable ipv4, enable the ipv6  and use the IPAM multipool

### Cilium Version

any

### Kernel Version

any

### Kubernetes Version

any

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by liyihuang**
In #27018 we learnt that

> Cilium-Agents IPv4/IPv6AllocRange is Cilium's internal representation of the local node's PodCIDR. The concept of a single allocation CIDR however is outdated, since in many IPAM modes (ENI, Azure, AlibabaCloud, MultiPool) there either is no PodCIDR to begin with (and pod IPs are allocated using a different scheme), or there are multiple PodCIDRs (in the case of MultiPool).

When it’s multi-pool IPAM with dual stack mode,  currently the IPv6AllocCIDR is set based on the ipv4 value where it doesn’t represent the real pod IP range based on my understanding, it’s like a random values.  For example, If I have the following config for the pool IP for multi-pool IPAM

```
apiVersion: cilium.io/v2alpha1
kind: CiliumPodIPPool
metadata:
  name: default
  labels:
    pool: blue
spec:
  ipv4:
    cidrs:
      - 100.100.0.0/16
    maskSize: 24
  ipv6:
    cidrs:
      - fd00:100:1::/48
    maskSize: 64
```

 
 I can see it auto generates the prefix for `10.3.0.0/16` and `f00d::3:0:0/96`
```
time="2025-06-16T23:25:53Z" level=info msg="Using autogenerated IPv4 allocation range" subsys=node v4Prefix=10.3.0.0/16                                                                                                                                                                                                                                                                                                                   
time="2025-06-16T23:25:53Z" level=info msg="Using autogenerated IPv6 allocation range from node IPv6" subsys=node v6Prefix="f00d::3:0:0/96"           
```
the pod gets the following IP
```
    podIPs:
    - ip: fd00:100:1:1::f9a9
    - ip: 100.100.1.50
```

When it's multi-pool IPAM mode with ipv6 only cluster, there is no IPv4 as the seed to generate the IPv6AllocCIDR. Therefore, I read from node ipv6 address as the seed to autogeneate the prefix

In the kubernetes and cluster-pool IPAM mode where IPv4/IPv6AllocRange makes sense. The IPV4/IPv6AllocCIDR is set by k8s Node or CiliumNode where set the default prefix logic will not executed.

The reaon I picked`ip[12], ip[13], ip[14], ip[15]` is because ip[0], ip[1], ip[2], ip[3] will have higher chance to read the ipv6 preifx where the `ip[12], ip[13], ip[14], ip[15]` might still pick the ipv4 address if the ipv6 address scheme is mapped from ipv4 address.

Set the default ipv6 prefix as the workaround for ipv6 only cluster before we remove the AllocCIDR from cilium https://github.com/cilium/cilium/issues/27018.

Based on my test, we need this PR and https://github.com/cilium/cilium/pull/38472 and https://github.com/cilium/cilium/pull/39877 together to support the ipv6 and multi-pool IPAM to fully resolve #38471 



Fixes: #38471

```release-note
Change the Endpoint IPAM range to derive a range from the Node's IPv6 address for ipv6 only cluster
```

### CODE REVIEW

**Review by joamaki — APPROVED** [review]

File: pkg/node/address.go [hunk 1]
```diff
@@ -141,23 +140,30 @@ func setDefaultPrefix(logger *slog.Logger, cfg *option.DaemonConfig, device stri
...
+			if ip == nil {
+				// This should not happen, as we set the node IP above.
+				logging.Panic(logger, "BUG: Node IPv6 address is not available to derive IPv6 pod CIDR")
+			}
+
+			// We use the last 4 bytes of the node's IPv6 address to build the pod CIDR.
+			// This makes the allocation logic independent of IPv4.
 			v6range := fmt.Sprintf("%s%02x%02x:%02x%02x:0:0/%d",
-				cfg.IPv6ClusterAllocCIDRBase, ip[0], ip[1], ip[2], ip[3], 96)
+				cfg.IPv6ClusterAllocCIDRBase, ip[12], ip[13], ip[14], ip[15], 96)
```
Comment (joestringer) [inline pkg/node/address.go]: Can you describe what's going on here? There's some discrepancies in the rendering of the prefix range. I also didn't follow why this patch is making changes to the bytes used to construct the IPv6 allocation range.

**Review by joestringer — CHANGES_REQUESTED** [review]

File: pkg/node/address.go (hunk 1 above)
Comment (liyihuang) [reply pkg/node/address.go]: thanks. I think I should put more context in the first place. I will update it at here https://github.com/cilium/cilium/pull/39917#issue-3121812021. I will update it and request for review later

Comment (joestringer) [reply pkg/node/address.go]: The prefix range still looks wrong here (both before this change and after this change), the comment is wrong and the rendering of the IPv6 address doesn't make sense.

EDIT: This statement is unhelpful, see below for a better analysis.

Comment (joestringer) [reply pkg/node/address.go]: Let me take a step back and iterate through step by step:
- This logic only applies if the user hasn't provided an IPv6 allocation range
- There's some input IP configured on the node `SSSS:TTTT:UUUU:VVVV:WWWW:XXXX:YYYY:ZZZZ`
- Cilium forms some CIDR `fd00::____:____:0:0`
- Previously the logic would pick up the IPv4 address and put it into the template
- This logic constructs `fd00::YYYY:ZZZZ:0:0` from the IPv6 address
- As you mention in the PR description, IPv4-mapped IPv6 addresses may map a full IPv4 address into this lower segment. In the case that the user uses IPv4-mapped IPv6 addresses for node IPs, this may retain the equivalent allocation behavior as before. Otherwise it's just picking whatever the most specific section of the IPv6 address to use as a range further up in the space.

On first review I did not expect some lower bytes in the address to be shuffled into an upper range. I expected some masking operation or taking the segments at the equivalent offset and placing those into the IPv6 range. Now I step through it this is not a fair assumption.

**Comment by joestringer** [comment]
I removed the `feature/ipv6-only` label and added `feature/ipv6` since the code path here runs regardless of whether IPv4 support is enabled or not.

I also added the `upgrade-impact` label because any environment that currently relies on the default IPv6 CIDR allocation range could break on upgrade to this PR. What I anticipate is that users who have not explicitly configured the IPv6 Pod IPAM range will now assign IPs in a different IP range after upgrade. Existing workloads allocated with the old IPAM range will continue to use their old IPs, but this node will no longer distribute routes to other nodes to direct that traffic to this node. This could break connectivity. At this stage I'm not sure what is the best way to identify and report this to users, or how to instruct them to migrate onto a Cilium version with this patch.

**Comment by joestringer** [comment]
I think this needs some kind of upgrade path to avoid breaking users. At *minimum* clear release notes with mitigating instructions; alternatively we could make this configurable, retain the current behavior, and allow the user to opt in to the new allocation heuristic. I don't know if the latter is really necessary, but it would provide a longer ramp for users to choose whether to adopt the new behavior and potentially migrate at their discretion.

**Comment by liyihuang** [comment]
I totally understand where your concern comes from.

I could add the previous logic to auto generate the ipv6 based on ipv4 and fall back to this logic only if ipv4 is not available to avoid the breaking changes to existing users. 

Let me also confirm my understanding of this field better to see if adding it back is really necessary.

@gandro do you mind to help me understand how my PR https://github.com/cilium/cilium/pull/39917#issue-3121812021  will impact the users or why we even set this default prefix? My understanding is IPAM cluster-pool and kubernetes will set `IPv4/IPv6AllocRange` where the default prefix is not really necessary, and other IPAM mode dont really use `IPv4/IPv6AllocRange` since it has its own way to manage the IP address. Is the default prefix more like a placeholder to avoid the nil value?

**Comment by gandro** [comment]
> @gandro do you mind to help me understand [..] why we even set this default prefix?

The reason why we have the default prefix is unknown to me too - maybe @joestringer knows, but my feeling is that this is very very old logic. 

My _assumption_ (but this would have to be verified) is that if a user only has IPv4 addresses on the node, Cilium can still (and usually did, before we disabled IPv6 by default a couple years ago) assign an IPv6 address to every endpoint even if the underlay is IPv4-only and `ipam: kubernetes` doesn't assign a IPv6 pod CIDR. As long as pod-to-pod traffic is tunneled, this is totally fine. You won't be able to egress to world or K8s services using IPv6, but you can still reach an endpoint (pod) via it's IPv6 address, even if the node has no IPv6 address and K8s doesn't known about IPv6 either.

If that mode of operation still works, then I agree with Joe that this is likely a breaking change for such setups. I do suspect these setups are rare these days (since IPv6 is no longer enabled by default), but they could still exist.

>  Is the default prefix more like a placeholder to avoid the nil value?

Practically speaking, this is true for IPAM modes ENI and Multi-Pool (https://github.com/cilium/cilium/issues/27018). But I think it probably also still serves a real purpose where a user has dual-stack on the dataplane, without actually having dual-stack on the nodes or K8s.

*If* this weird mode of having a IPv6-enabled overlay without IPv6 support on the node or K8s still works with `ipam: kubernetes` then I concur with Joe that we need a more smoother upgrade path. Long-term, I do think we want disable this default prefix logic by default (since it only serves very niche use-cases and causes harm in most other IPAM modes), but for that we need a decent upgrade path.

**Comment by liyihuang** [comment]
Thanks. I think I can change this PR to put the old logic back to avoid breaking changes to existing users even though that's rare.

I did try to comment out the default prefix generation.

Here is where the CI fails. It's more around the multi -pool and ENI ipam.


https://github.com/cilium/cilium/pull/39550

**Comment by joestringer** [comment]
I don't know the original motivation, but I would guess it comes from the perspective of attempting to automatically take care of networking configuration if the user didn't explicitly configure the IPAM range and doesn't care about the configuration. It most likely predates all of the more recent IPAM modes that Cilium supports. If someone just needs a basic networking plugin and isn't integrating their IPAM with other systems then maybe they can just deploy Cilium with overlay mode, masquerading to node IPs, then it doesn't matter much what IP ranges Cilium chooses to assign to Pods because those IPs aren't used anywhere else and all the Pods would connect with one another via virtual IPs (Services). 

At the same time I think that we have occasionally seen situations where in something like the ENI IPAM mode it does not make sense to define a default prefix because IPAM is handled by an external system, but then this default prefix is defined and then potentially used in iptables rules. This can create surprising behavior. Probably we should do a review of how this default prefix logic fits into overall datapath configurations and reconsider the design. For instance if the default IPAM is cluster-pool and therefore cilium-operator assigns prefixes to nodes, then I don't see why we would need logic to auto-assign some fallback IP range. In fact if we do so when Cilium is configured this way then it probably means something went wrong. Cilium might be better off in that case to just report a failure on startup rather than picking some random range and continuing on.

**Comment by liyihuang** [comment]
Will adjust this PR to add the ipv6 only logic and to keep dual stack logic so there will be no impact for users upgrading to this.

**Review by gandro — APPROVED** [review]

**Review by joestringer — APPROVED** [review]
