### PR TITLE
Fix kubectl CI flakiness

### LINKED ISSUE #18060: CI: failed to ensure kubectl version: failed to download kubectl
## CI failure

`failed to download kubectl`
Could be just a temporary issue when downloading kubectl. Still, I'm filing an issue to track this, as I observed it for two different PRs (https://github.com/cilium/cilium/pull/17762, https://github.com/cilium/cilium/pull/18027), with the Jenkins runs separated by several hours.

### Test Name
```test-name
K8sDemosTest Tests Star Wars Demo
```
with K8s 1.16.

Also observed with K8s 1.18 on:
```
K8sConformance Portmap Chaining Check connectivity-check compliance with portmap chaining
```

### Failure Output
```failure-output
FAIL: failed to ensure kubectl version: failed to download kubectl
```

### Stacktrace

```stack-trace
/home/jenkins/workspace/Cilium-PR-K8s-1.16-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:465
failed to ensure kubectl version: failed to download kubectl
/home/jenkins/workspace/Cilium-PR-K8s-1.16-net-next/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:647
```

### Standard Output

```stack-output
```

### Standard Error

```stack-error
18:20:19 STEP: Running BeforeAll block for EntireTestsuite K8sDemosTest
FAIL: failed to ensure kubectl version: failed to download kubectl
18:20:19 STEP: Running JustAfterEach block for EntireTestsuite K8sDemosTest
===================== TEST FAILED =====================
18:20:19 STEP: Running AfterFailed block for EntireTestsuite K8sDemosTest
Skipped gathering logs due to kubectl not being initialized
===================== Exiting AfterFailed =====================
18:20:19 STEP: Running AfterEach for block EntireTestsuite K8sDemosTest
18:20:19 STEP: Deleting all resources created during test
18:20:19 STEP: Running AfterEach for block EntireTestsuite
```

### Resources

- ZIP Links: 
[test_results_Cilium-PR-K8s-1.16-net-next_2081_BDD-Test-PR.zip](https://github.com/cilium/cilium/files/7625790/test_results_Cilium-PR-K8s-1.16-net-next_2081_BDD-Test-PR.zip)

- Jenkins URL: https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-net-next/2081/

### PR DESCRIPTION
**Pull request by aanm**
Fixes https://github.com/cilium/cilium/issues/18060

### CODE REVIEW

**Review by joestringer — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

File: test/helpers/kubectl.go [hunk 1]
```diff
@@ -4477,9 +4476,16 @@ func (kub *Kubectl) ensureKubectlVersion() error {
 		return err
 	}
 	path := path.Join(GetKubectlPath(), "kubectl")
+	rcVersion := fmt.Sprintf("v%s.0-rc.0", GetCurrentK8SEnv())
+	switch GetCurrentK8SEnv() {
+	// These versions never released a ".0". Only since 1.19 Kubernetes started
+	// to release RC starting from '0'.
+	case "1.16", "1.17", "1.18":
+		rcVersion = fmt.Sprintf("v%s.0-rc.1", GetCurrentK8SEnv())
```
Comment (joestringer) [inline test/helpers/kubectl.go]: Why do we need the RC version for these ones if they already had a final release?

Comment (joestringer) [reply test/helpers/kubectl.go]: (functionally I assume it's equivalent so if this is the easiest way then :+1: )

Comment (aanm) [reply test/helpers/kubectl.go]: Because I didn't think this through :facepalm:

**Review by joestringer — APPROVED** [review]

**Review by nbusseneau — APPROVED** [review]
