### PR TITLE
endpoint: do not return error if endpoint RLock fails due to endpoint being removed

### LINKED ISSUE #6721: resolve-identity controller should not treat RLockAlive() error as error
```
 controller resolve-identity-2939 failure 'rlock failed: endpoint is in the process of being removed'
```

The error means that the endpoint was removed, the controller should exit gracefully.

### PR DESCRIPTION
**Pull request by ianvernon**
The Cilium CI has failed recently on multiple occasions due to errors appearing
for controllers for endpoints which resolve the identity for said endpoints.
The errors were "rlock failed: endpoint is in the process of being removed".
If an endpoint is being removed, its identity no longer needs to be resolved, so
we do not need to return an error in this case within `identityLabelsChanged`.

Fixes: #6721

Signed-off by: Ian Vernon <ian@cilium.io>

Nominating for 1.3 backport since this is affecting the v1.3 CI as well.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6750)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

File: pkg/endpoint/endpoint.go [hunk 1]
```diff
@@ -1998,7 +1998,7 @@ func (e *Endpoint) runLabelsResolver(owner Owner, myChangeRev int, blocking bool
 
 func (e *Endpoint) identityLabelsChanged(owner Owner, myChangeRev int) error {
 	if err := e.RLockAlive(); err != nil {
-		return err
+		return nil
```
Comment (aanm) [inline pkg/endpoint/endpoint.go]: `identityLabelsChanged` is not only called in a controller and this is also misleading as there was indeed an error the caller should be aware off.

I would suggest to create an error type called `ErrNotAlive` returned by `RLockAlive` and the caller of `identityLabelsChanged` would check if the error returned is a `ErrNotAlive` or a "normal" error. By checking `ErrNotAlive` it would probably be able to exit the controller.

Similar to https://github.com/cilium/cilium/blob/3d5785f37393d42725e31e891e808455ee68a632/pkg/endpointmanager/errors.go#L23

**Review by aanm — DISMISSED** [review]

**Comment by aanm** [comment]
> The Cilium CI has failed recently on multiple occasions due to errors appearing
> for controllers for endpoints which resolve the identity for said endpoints.
> The errors were "rlock failed: endpoint is in the process of being removed".
> If an endpoint is being removed, its identity no longer needs to be resolved, so
> we do not need to return an error in this case within `identityLabelsChanged`.
> 
How did we end up in that situation? I thought the endpoint would be deleted and all controllers if the container would not be able to be created.

File: pkg/endpoint/endpoint.go (hunk 1 above)
Comment (ianvernon) [reply pkg/endpoint/endpoint.go]: `identityLabelsChanged` is called in `runLabelsResolver`, in two places:

https://github.com/cilium/cilium/blob/b0471e8dd05cae3d5a25263615e8401708d58135/pkg/endpoint/endpoint.go#L1965-L1997

The caller is not made aware of this error because `runLabelsResolver` doesn't return any errors. Consequently, I don't see why we need to create a new error type. If there is an error resolving the identity for an endpoint, we log it. We always start the controller in `runLabelsResolver` as well. I do not think that there is a need to say that there is an error resolving an identity for an endpoint which is being deleted, because it's going to be deleted anyway. The logic behind `RLockAlive` is to avoid doing operations on endpoints which are being deleted, so I think returning no error in this case is fine because it means that we don't have to do any more operations on the endpoint.

**Comment by ianvernon** [comment]
> How did we end up in that situation? I thought the endpoint would be deleted and all controllers if the container would not be able to be created.

"If the container would not be able to be created" - can you elaborate on this please?

There is a possibility of a race occurring while an endpoint is being deleted for the `resolve-identity` controller to run, and return an error.

File: pkg/endpoint/endpoint.go (hunk 1 above)
Comment (aanm) [reply pkg/endpoint/endpoint.go]: In `identityLabelsChanged`, the `e.RLockAlive()` is used in more than one place, does this means you will switch all of them to `return nil` if `e.RLockAlive()` returns an error?

>no error in this case is fine because it means that we don't have to do any more operations on the endpoint.

Tomorrow, or next week, or in a month, I'll use `identityLabelsChanged` for a totally different thing, how do I know the function succeeded if in error cases we are also returning nil? It does not make any sense to me.

Comment (ianvernon) [reply pkg/endpoint/endpoint.go]: I do not see `identityLabelsChanged` using `e.RLockAlive()` in more than one place. There are usages of `e.LockAlive()` - are you referring to that?

My argument is that this isn't really an 'error' case. It's a case that we want to handle gracefully. If an endpoint is being deleted, I do not think we need to run the controller for it at all. The only case in which `RLockAlive` returns an error is if the endpoint is disconnecting / disconnected. 

I'll implement what you have asked for.

**Comment by tgraf** [comment]
> How did we end up in that situation? I thought the endpoint would be deleted and all controllers if the container would not be able to be created.

Stopping the controller waits for the controller run to complete. There is no way to abort an already running controller run.

**Comment by ianvernon** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]
