### PR TITLE
loader: XDP attach type fallback logic

### LINKED ISSUE #44063: XDP program upgrade/downgrade between v1.19 and main broken
At the moment upgrades from v1.19 to main and downgrades from main to v1.19 cause errors in loader when XDP is enabled.

`interface eth0: updating link /sys/fs/bpf/cilium/devices/eth0/links/cil_xdp_entry for program cil_xdp_entry: updating link /sys/fs/bpf/cilium/devices/eth0/links/cil_xdp_entry: update link: invalid argument`

The reason for these errors is changes made in https://github.com/cilium/ebpf/pull/1919. What has changed is that we have now started to explicitly set the XDP attach type when loading XDP programs. This brings cilium/ebpf in line with what libbpf does. This became important in kernel v6.18 because prog array maps since that version enforce that programs have the same attach type. So programs loaded by cilium/ebpf (attach_type: none) and those loaded by libbpf (attach_type: xdp) can't co-exist in the same map anymore.

The side effect is that a BPF link also does not allow you to switch the attach type. So a BPF link created as attach_type: none, can not be updated with a program loaded as attach_type: xdp. Which breaks both upgrade and downgrade.

Unfortunately there is no easy workaround. You have to remove the existing link and re-create a new link, which causes us to miss packets. We still need to do some experimentation to see if we can utilize the old netlink attach to switch the attach type without missing packets. Alternatively we need to figure out which links were loaded with which attach type and match that, by manually setting the attach type to None or XDP depending on existing links. But this is a bit painful to implement, and thus a last resort.

Bonus: add a hint to the error string reported by the second `loadAssignAttach()` that enables XDP frags. It's pretty confusing to figure out why it's failing to load since there's no verifier error.

### PR DESCRIPTION
**Pull request by dylandreimerink**
Due to changes in newer kernels and the cilium/ebpf library, XDP programs will in future be loaded as ebpf.AttachXDP. However, older Cilium versions will have already created links with ebpf.AttachNone programs. The kernel does not allow us to change the program of a link if its attach type does not match.

This means that we can only use the new XDP attach type when a link is newly created. This commit adds logic which detects errors on link update and attempts to load and attach with the other attach type instead. So when upgrading from an older version to a newer version, new links are created as XDP attach type, but existing links will remain using the AttachNone. On downgrade, all links will be created with AttachNone, and existing links will continue to use AttachXDP.

Fixes: #44063

```release-note
Enable Cilium upgrade and downgrade when existing XDP attach types differ from new XDP programs
```

### CODE REVIEW

File: pkg/datapath/loader/xdp.go [hunk 1]
```diff
@@ -173,48 +174,92 @@ func compileAndLoadXDPProg(ctx context.Context, logger *slog.Logger, lnc *datapa
...
+		err error
+		obj xdpObjects
+	)
 	defer obj.Close()
 
-	if err := attachXDPProgram(logger, iface, obj.Entrypoint, symbolFromHostNetdevXDP,
-		bpffsDeviceLinksDir(bpf.CiliumPath(), iface), xdpConfigModeToFlag(xdpMode)); err != nil {
-		return fmt.Errorf("interface %s: %w", iface.Attrs().Name, err)
-	}
+	for _, p := range loadPermutations {
```
Comment (ti-mo) [inline pkg/datapath/loader/xdp.go]: `loadPermutations` (I'd call this `xdpPermutations`) could return an `iter.Seq[ebpf.CollectionSpec]` that applies a permutation before yielding the spec. Try to keep concerns separated or this becomes a junk drawer.

File: pkg/datapath/loader/xdp.go [hunk 2]
```diff
@@ -173,48 +174,92 @@ func compileAndLoadXDPProg(ctx context.Context, logger *slog.Logger, lnc *datapa
...
+					logfields.Error, err,
+					logfields.AttachType, p.FlipAttachType,
+					logfields.WithFrags, p.WithFrags,
+				)
+
+				obj.Close()
+				continue
+			}
+
+			return fmt.Errorf("unable to attach XDP program: %w", err)
```
Comment (ti-mo) [inline pkg/datapath/loader/xdp.go]: This can include the retry number once `xdpPermutations` returns a Seq.

```suggestion
			return fmt.Errorf("unable to attach XDP program after %d retries: %w", i, err)
```

File: pkg/datapath/loader/xdp_test.go [hunk 3]
```diff
@@ -248,3 +250,65 @@ func getLink(tb testing.TB, link netlink.Link) netlink.Link {
 
 	return req
 }
+
+func TestPrivilegedChangeAttachType(t *testing.T) {
```
Comment (ti-mo) [inline pkg/datapath/loader/xdp_test.go]: I'd split testing this into stages to avoid having to touch `xdpConfigs` and `xdpRenames` (careful, these are globals).

We mainly care about two behaviours:
1. the right permutations being applied in the right sequence
2. link create and update succeeding in all scenarios

The first point can be solved by lifting out the logic for permutation application as I suggested above. The second currently requires some hacks, mostly ends up exercising the kernel itself, and doesn't exercise half of the functionality (frags) since that would require an actual device with a driver that supports/requires frags.

As such, I'd suggest dropping the privileged tests altogether and instead make sure we get 1. right, since some cases are missing. Note that the `xdp.frags/` section makes the CollectionSpec roll out of the ELF reader with the frags bit set, so this should also be included as one of the test cases. (not the section parsing itself, but feeding in a ProgramSpec with F_XDP_HAS_FRAGS)

This means the function doesn't need to take a `bpffsRoot` parameter any longer either.

File: pkg/datapath/loader/xdp.go [hunk 4]
```diff
@@ -173,48 +174,92 @@ func compileAndLoadXDPProg(ctx context.Context, logger *slog.Logger, lnc *datapa
...
+				// * The configured MTU on the device is so large that the driver requires us to load with
+				//   BPF_F_XDP_HAS_FRAGS, but we didn't. In that case, we can retry with the flag set.
+				// * There is an existing link with a program loaded with a different attach type. We
+				//   have to try the other attach type.
+				//
+				// We cannot tell which is the case, so we simply run the next permutation until all are exhausted.
+
+				logger.Info("attaching XDP program failed with current permutation",
+					logfields.Error, err,
+					logfields.AttachType, p.FlipAttachType,
```
Comment (ti-mo) [inline pkg/datapath/loader/xdp.go]: I'd log the actual attach type and flags that were used, since its exact value will depend on the input ELF and the ebpf-go version. This will be really hard to figure out from a sysdump.

File: pkg/datapath/loader/xdp.go [hunk 5]
```diff
@@ -173,48 +174,92 @@ func compileAndLoadXDPProg(ctx context.Context, logger *slog.Logger, lnc *datapa
...
+		commit, err = bpf.LoadAndAssign(logger, &obj, spec, &bpf.CollectionOptions{
+			Constants:  xdpConfiguration(lnc, iface),
+			MapRenames: xdpMapRenames(lnc, iface),
+			CollectionOptions: ebpf.CollectionOptions{
+				Maps: ebpf.MapOptions{PinPath: filepath.Join(bpffsRoot, defaults.TCGlobalsPath)},
+			},
+			ConfigDumpPath: filepath.Join(bpfStateDeviceDir(iface.Attrs().Name), xdpConfig),
+		})
+		if err != nil {
+			return fmt.Errorf("fail to load: %w", err)
```
Comment (ti-mo) [inline pkg/datapath/loader/xdp.go]: 'fail' is redundant in an error string, use `loading collection:` or whatever we use in other places.

**Review by ti-mo — COMMENTED** [review]
Thanks! Left some comments.

File: pkg/datapath/loader/xdp_test.go (hunk 3 above)
Comment (dylandreimerink) [reply pkg/datapath/loader/xdp_test.go]: > I'd split testing this into stages to avoid having to touch xdpConfigs and xdpRenames (careful, these are globals).

I tried a few things locally. But I cannot find a good way to do the slit without making something nasty or awkward. You would have to tear out the options generation, and put it where? Now you have to put all the logic of the pin dirs ect in the calling function.

Not setting the global variables would require us to pass in the registries as dependencies instead of global variables. This can technically be done, but the argument list is already huge.

> the right permutations being applied in the right sequence

Hmm. So now I need to define the same permutations in the tests as well, and assert that the sequence in the tests matches that of the logic. It looks really dumb, and it does not change anything about the outcome, the sequence of permutations is purely an optimization to try the most likely things first.

> Note that the xdp.frags/ section makes the CollectionSpec roll out of the ELF reader with the frags bit set, so this should also be included as one of the test cases. (not the section parsing itself, but feeding in a ProgramSpec with F_XDP_HAS_FRAGS)

We don't use the `xdp.frags/ ` section, ever. We can make a scenario for it, but since we hard code that particular flag to set or not set, it does nothing even if it were provided.

All in all. I frankly don't see a way to improve the current situation without a refactor that is larger than the changes as a whole. If you do, could I get a more concrete plan?

**Review by ti-mo — APPROVED** [review]

**Review by HadrienPatte — APPROVED** [review]
vendor LGTM

**Review by rastislavs — APPROVED** [review]
