### PR TITLE
Fix dropped NodePort traffic to hostNetwork backends with Geneve+DSR

### LINKED ISSUE #36901: Cilium with geneve and DSR drops external traffic to host network backends
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.5 and lower than v1.17.0

### What happened?

I run cilium with geneve overlay and DSR enabled. When running a workload in host network mode and exposing it through a LoadBalancer service, I see the following cilium logs through `cilium dbg-monitor` (and the traffic is dropped):
```
xx drop (No tunnel/encapsulation endpoint (datapath BUG!)) flow 0x91b4c88a to endpoint 0, ifindex 2, file nodeport.h:2320, , identity unknown->unknown: 10.8.60.118:57126 -> 10.35.216.56:443 tcp SYN
xx drop (No tunnel/encapsulation endpoint (datapath BUG!)) flow 0x91b4c88a to endpoint 0, ifindex 2, file nodeport.h:2320, , identity unknown->unknown: 10.8.60.118:57126 -> 10.35.216.56:443 tcp SYN
```

If the backend workload is not in hostNetwork mode, it works as expected and if DSR is disabled it also works as expected.

### How can we reproduce the issue?

1. Install cilium with geneve overlay and dsr enabled with geneve dispatch
2. Deploy a workload with `hostNetwork: true` and expose it through a LoadBalancer service
3. Connect to the LoadBalancer external IP

### Cilium Version

1.16.5

### Kernel Version

5.15.0-124-generic

### Kubernetes Version

1.29.7

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

This seems somewhat similar to https://github.com/cilium/cilium/issues/10789 which however was solved.

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by tommasopozzetti**
This PR fixes DSR dispatch with Geneve to hostNetworked pods by ensuring tunnel_endpoint is always populated in ipcache, even for directly reachable endpoints. Unneeded encapsulation is avoided by passing the skiptunnel flag for such endpoints.

Fixes: #36901

### CODE REVIEW

**Comment by julianwiedmann** [comment]
Thank you! I'll have a closer look later.

Also queued up https://github.com/cilium/cilium/pull/36982. Once that's merged, we can rebase this PR so that we get immediate feedback on the connectivity test.

**Review by Artyop — APPROVED** [review]
lgtm

**Comment by julianwiedmann** [comment]
> Also queued up #36982. Once that's merged, we can rebase this PR so that we get immediate feedback on the connectivity test.

Merged, I'll auto-rebase the branch...

**Comment by tommasopozzetti** [comment]
Thanks for the quick look!
I see some connectivity test cases failed waiting for the new pod that gets introduced though not 100% sure how to go check more details about those setups. Any pointer would be appreciated, first time going through the cilium CI process! 😄

**Comment by tommasopozzetti** [comment]
@julianwiedmann fixed the conflict. Any tips on next steps to get this in?

File: bpf/lib/nodeport.h [hunk 1]
```diff
@@ -1617,12 +1617,16 @@ static __always_inline int encap_geneve_dsr_opt4(struct __ctx_buff *ctx, int l3_
...
 		return DROP_NO_TUNNEL_ENDPOINT;
 
-	tunnel_endpoint = info->tunnel_endpoint;
 	dst_sec_identity = info->sec_identity;
 
+	if (identity_is_remote_node(dst_sec_identity))
+		tunnel_endpoint = ip4->daddr;
+	else
+		tunnel_endpoint = info->tunnel_endpoint;
+
```
Comment (julianwiedmann) [inline bpf/lib/nodeport.h]: Let's preserve old behavior here

```suggestion
	if (info->tunnel_endpoint)
		tunnel_endpoint = info->tunnel_endpoint;
	else if (identity_is_remote_node(dst_sec_identity))
	        tunnel_endpoint = ip4->daddr;
	else
		return DROP_NO_TUNNEL_ENDPOINT;

```

File: cilium-cli/connectivity/builder/north_south_loadbalancing.go [hunk 2]
```diff
@@ -16,5 +16,8 @@ func (t northSouthLoadbalancing) build(ct *check.ConnectivityTest, _ map[string]
 		WithFeatureRequirements(
 			withKPRReqForMultiCluster(ct, features.RequireEnabled(features.NodeWithoutCilium))...,
 		).
-		WithScenarios(tests.OutsideToNodePort())
+		WithScenarios(
+			tests.OutsideToNodePort(),
+			tests.OutsideToNodePortForHostNetNs(),
+		)
```
Comment (julianwiedmann) [inline cilium-cli/connectivity/builder/north_south_loadbalancing.go]: For compatibility we'll need some variant of `WithCiliumVersion(">=1.18.0")` here, until the backports to older Cilium versions have landed.

File: bpf/lib/nodeport.h [hunk 3]
```diff
@@ -1617,12 +1617,16 @@ static __always_inline int encap_geneve_dsr_opt4(struct __ctx_buff *ctx, int l3_
...
 	info = lookup_ip4_remote_endpoint(ip4->daddr, 0);
-	if (!info || info->tunnel_endpoint == 0)
+	if (!info)
 		return DROP_NO_TUNNEL_ENDPOINT;
 
-	tunnel_endpoint = info->tunnel_endpoint;
 	dst_sec_identity = info->sec_identity;
 
+	if (identity_is_remote_node(dst_sec_identity))
+		tunnel_endpoint = ip4->daddr;
```
Comment (julianwiedmann) [inline bpf/lib/nodeport.h]: One unresolved question would be how this works for IPv6 (in `encap_geneve_dsr_opt6()`). We currently don't support overlay network over IPv6, so there we can't easily fall back to the backend IP :grimacing:.

The big hammer would be to touch https://github.com/cilium/cilium/blob/3d75eba2e41d6c0fd839feb4b4eb99904250edb3/pkg/node/manager/manager.go#L567. In native-routing that would nicely address this problem. But in overlay mode it would cause *all* `to-remote-node` traffic to flow via the overlay network. Which is something we've avoided so far ...

**Review by julianwiedmann — COMMENTED** [review]
Some comments inline, before I forgot about the CLI compatibility aspect again ...

**Comment by julianwiedmann** [comment]
> @julianwiedmann fixed the conflict. Any tips on next steps to get this in?

In general - please rebase on-top of `main`, instead of merging `main` into your branch.

> I see some connectivity test cases failed waiting for the new pod that gets introduced though not 100% sure how to go check more details about those setups.

IIRC the CLI tests for cluster-internal connectivity to all the nodeport services on startup, before running the connectivity tests. Is that what's failing? Let's re-run the workflow and find out.

**Comment by tommasopozzetti** [comment]
@julianwiedmann appreciate your help!
I will rebase over main and add your suggested logic to keep the drop shortly. I will also add a condition to the test to execute the new one only on 1.18+.

For what concerns the tests, it seems a few of the namespaces get stuck in waiting for the new host netns pod to come up. They hit timeout.
```
timeout reached waiting for deployment cilium-test-4/echo-host-netns to become ready (last error: only 0 of 1 replicas are available)
timeout reached waiting for deployment cilium-test-5/echo-host-netns to become ready (last error: only 0 of 1 replicas are available)
timeout reached waiting for deployment cilium-test-3/echo-host-netns to become ready (last error: only 0 of 1 replicas are available)
```
However, other namespaces in the same test progress further. It's not immediately clear to me how to check what the pod status is and why it isn't up. Testing this locally works fine and I am not familiar with all the nuances of the full cilium ci test suite. Any tips on where I can look at more details of the test run would be appreciated. I'm not sure if there is something about the configs of those tests that prevents them from starting that pod or if by adding one pod I am now running out of some quotas somewhere that prevent the pod from properly starting up in the test environment.

> One unresolved question would be how this works for IPv6 (in encap_geneve_dsr_opt6()). We currently don't support overlay network over IPv6, so there we can't easily fall back to the backend IP 😬.

Would it make sense to add into the ipcache the tunnel endpoint for remote identities only for those that are ipv6? As you mentioned, ipv6 does not support overlay anyways so you would not run into extra overlay traffic, while for ipv4 we have solved it this way. If in the future cilium were to support overlay for ipv6, this could be adjusted to have the same fix as ipv4. 

Another thought would be to, instead of dropping traffic, fall back to SNAT lb if the tunnel endpoint is unavailable for ipv6, which will mean DSR won't work, but it is likely still better than the traffic get completely dropped.

Irrespectively of this, I'd like to propose we open a separate issue to discuss the ipv6 side since it seems to require a little more thought, and I'd be more than happy to propose a PR for that as well if you can point me in the right direction, however I do think the current bug is significant as it makes DSR+geneve essentially unusable as one traffic path is completely dropped so I believe that even just getting this half of the fix in would be a great initial win for all the environments using only ipv4.

**Comment by tommasopozzetti** [comment]
Looking through the failures, it looks like every run fails waiting for the pod for a couple of the namespaces while the other succeed and proceed. Which namespace seems to vary for every test case
https://github.com/cilium/cilium/actions/runs/12824739486

This makes me think of some quota of some kind being hit in the environment that needs to be increased to account for the extra pod being deployed across all the namespaces for the new connectivity test

**Comment by tommasopozzetti** [comment]
@julianwiedmann all done. Let me know your thoughts for the potential quota issues and the ipv6 counterpart.

**Review by Artyop — APPROVED** [review]

**Review by dylandreimerink — CHANGES_REQUESTED** [review]
> One unresolved question would be how this works for IPv6 (in encap_geneve_dsr_opt6()). We currently don't support overlay network over IPv6, so there we can't easily fall back to the backend IP 😬.

I think its important to address this and not make the IPv4 and IPv6 paths even more asymmetrical then it already is.

I suggest that we change the logic in the agent to always populate the `tunnel_endpoint` field. In addition also set the `flag_skip_tunnel` [flag](https://github.com/cilium/cilium/pull/29796). This flag should prevent regular tunneling to the host endpoints (unwanted behavior @julianwiedmann pointed out) but still gives us access for the purposes of DSR. Since current Cilium versions already respect the flag, except for this DSR logic, this should also be safe during upgrades and downgrades as well. We would have to make sure to not set this flag when the host firewall feature is enabled.

**Comment by tommasopozzetti** [comment]
Hi @dylandreimerink, thanks for the suggestion. I was not aware of that flag.
I'd like to take a stab at this solution. I am very new to the Cilium codebase so I have been looking around to get an idea on how to propagate that flag correctly but as far as I can tell that flag is not really referenced or ready to be set essentially anywhere.
As far as I can tell most of the logic around ipcache updates treats the entries as only potentially possessing an identity, a hostIP (tunnel endpoint) and an encryption key. The new flags would need to be added across the board as the fourth property of each entry, requiring a refactoring of many methods to include that extra parameter.
We'd need  a new IPMetadata type like [TunnelPeer](https://github.com/cilium/cilium/blob/cf1e615e4c20c895aec005367ea0874d639e8395/pkg/ipcache/types/types.go#L83) that sets the value encoding those flags as info for entries. We'd need to retrieve and process that field in the [label injection logic](https://github.com/cilium/cilium/blob/cf1e615e4c20c895aec005367ea0874d639e8395/pkg/ipcache/metadata.go#L357), passing it down to the [ipcache upsertion logic](https://github.com/cilium/cilium/blob/cf1e615e4c20c895aec005367ea0874d639e8395/pkg/ipcache/metadata.go#L545) and then again process it and pass it down to the [listener](https://github.com/cilium/cilium/blob/cf1e615e4c20c895aec005367ea0874d639e8395/pkg/ipcache/ipcache.go#L482) (which would also need to be tweaked to accept the extra param) so that it can finally set it in the bpf map.

Before attempting such a change I just wanted to confirm if I'm on the right path or there's some further considerations or simpler ways to achieve this that you could point me towards!
Thanks!

**Comment by dylandreimerink** [comment]
I took a look. There is indeed some plumbing to do, but it seems to be mostly passing the flags around. But I am not super well versed in this bit of the codebase myself. As soon as these files get touched, an additional reviewer for this bit will be assigned onto the PR to check the details.

> Before attempting such a change I just wanted to confirm if I'm on the right path

I think you are. I wrote out the major change points, of course you will likely need to update a  few other things as well when we start changing function signatures.

* Add a new type of metadata in pkg/ipcache/types.go for flags(just skipTunnel for now)
* Update `manager.NodeUpdated` in pkg/node/manager/manager.go to always set the tunnel ip
   and pass the new flags metadata to `IPCache.UpsertMetadata`
* Add a new flags field to `resourceInfo` in pkg/ipcache/types.go
* Update `BPFListener.OnIPIdentityCacheChange` in pkg/datapath/ipcache/listener.go to take a flags argument, and add it to the map value.
* Update `IPCache.upsertLocked` in pkg/ipcache/ipcache.go to take the flag and pass to `OnIPIdentityCacheChange`
* Update `IPCache.doInjectLabels` in pkg/ipcache/metadata.go to take flags from `resourceInfo` and pass to `IPCache.upsertLocked`

> We'd need a new IPMetadata type like [TunnelPeer](https://github.com/cilium/cilium/blob/cf1e615e4c20c895aec005367ea0874d639e8395/pkg/ipcache/types/types.go#L83) that sets the value encoding those flags as info for entries.

This is the bit I have the most doubts about myself. I am not sure if we should aim for very specific metadata here which gets translated into the one flag, perhaps in the `resourceInfo` were we seem to go from metadata types to specific strucs, or if we should add a more generic "Flags" type metadata, so the infra is there in case we ever add new flags.

I hope that would be easy to change if we have to. I will also see if we can get someone to weigh in on this.

**Comment by tommasopozzetti** [comment]
@dylandreimerink thanks, appreciate the sanity check and guidance!
I took a stab at this last night and I did exactly that. For now I added a more generic endpointFlags parameter with the idea of it being an easy to expand plumbing in place for future flags but easy enough to change if we’d rather keep it more focused.
I encountered some trouble while testing last night so I have some more work to do but I’ll push up a first pass as soon as I have it

**Comment by tommasopozzetti** [comment]
@dylandreimerink I refactored the PR to a potential implementation of the above solution. Curious to hear any feedback.

Given the larger scope of this PR with respect to before, I have also split the original PR into two, splitting off the cilium-cli tests into #37235 so the two can be reviewed and merged separately

**Review by jschwinger233 — APPROVED** [review]
encryption parts LGTM.

(my personal feeling is, maybe we can split it into two commits, one for "always set tunnel_endpoint in ipcache", the other for "propagate endpointFlags")

**Comment by tommasopozzetti** [comment]
Happy to split up into two commits if we think that is preferred. I'll wait for some more feedback on the preference and execute if so!
I see 3 e2e test scenarios seem to have failed while all others succeeded. Any pointer on where to go look for more info on why that is and/or the configurations of such tests so I can reproduce them?
Thanks!

**Comment by dylandreimerink** [comment]
> I see 3 e2e test scenarios seem to have failed while all others succeeded. Any pointer on where to go look for more info on why that is and/or the configurations of such tests so I can reproduce them?

The e2e tests can be flaky, I see they made it on the 2nd try. Passing the `ci-e2e-upgrade` tests is a good indicator.

> Happy to split up into two commits if we think that is preferred. I'll wait for some more feedback on the preference and execute if so!

Splitting the commits would be the nicest approach. The first adding the endpoint flags everywhere, and the second using that capability to implement the DSR fix.

**Comment by tommasopozzetti** [comment]
> Splitting the commits would be the nicest approach. The first adding the endpoint flags everywhere, and the second using that capability to implement the DSR fix.

Done! And thanks for the clarification on the flaky e2e tests!

**Review by dylandreimerink — APPROVED** [review]

**Review by Artyop — APPROVED** [review]

**Comment by tommasopozzetti** [comment]
Fixed up the unit test

**Review by derailed — APPROVED** [review]
@tommasopozzetti Nice work!

**Review by thorn3r — APPROVED** [review]
agent changes LGTM :+1:

**Comment by tommasopozzetti** [comment]
Hi @dylandreimerink, is there anything else that I can do to help push this through?

**Comment by dylandreimerink** [comment]
We need a review from @doniacld and @sayboras, or someone else from the @cilium/envoy and @cilium/ipcache code owners.

**Review by sayboras — APPROVED** [review]
Thanks, the changes look good for envoy related file (e.g. pkg/envoy/resources.go)

**Comment by dylandreimerink** [comment]
:sigh: CI is failing, seems because this branch is now starting to lag behind main. Could you rebase onto main? That should resolve this.

**Review by doniacld — APPROVED** [review]
LGTM but asking peers from [cilium/ipcache](https://github.com/orgs/cilium/teams/ipcache) to have a second look regarding the addition of a new field to `IPCache`. cc @squeed

**Comment by julianwiedmann** [comment]
Sorry, I think we'll have to revert this from v1.17. I believe it causes a regression, as described [here](https://github.com/cilium/cilium/pull/38099). We can keep it in `main` for now if that helps.

**Comment by julianwiedmann** [comment]
I've queued up the revert [here](https://github.com/cilium/cilium/pull/38101).

I actually like the approach of always setting the `tunnel_endpoint`, and thus associating an endpoint with its node's "primary" IP. I don't think we've had such an association before, and it feels beneficial. It even allows for a subsequent lookup in the `node_map`, and thus a decision whether two remote endpoints live on the **same** remote node.

But the way we currently handle pod-to-remote-node traffic (SNAT instead of tunnel), along with how the skip_tunnel flag was initially intended, makes this harder to implement. I'd be happy to give this a bit more thought & experimentation (post-PTO :)), I'm optimistic we can make it work and end up with a better overall design for pod-to-remote-node connections.

**Comment by tommasopozzetti** [comment]
@julianwiedmann sorry to hear that!
Fixing the original issue here is still very much critical to us as without this fix there still is a significant issue with dropped traffic with that configuration!
I’d be happy to help tackle it differently in the meantime if you have suggestions or contribute to the solution any way I can

**Comment by tommasopozzetti** [comment]
I’m also curious if you could expand (or point to docs) on the original intent of that flag
Reading through the code block you pointed out causes the issue with the pod to remote node traffic it’s not clear to me why the presence of the skip_tunnel flag would skip SNAT. Considering the current implementation never uses overlay tunneling for that communication to begin with, why would it need a different behavior depending on the value of that flag?
