### PR TITLE
pkg/bpf: Synchronize access to map in DumpReliablyWithCallback

### LINKED ISSUE #37383: Concurrent access of CT map might lead to early closure of CT map while doing GC?
This race condition was caught by golang's race detector.

After analyzing the code a little bit it might look that the m.Close done on line 858:
https://github.com/cilium/cilium/blob/d0b23f1afe32d068ab9ddfaad144b7863c9c8b98/pkg/maps/ctmap/ctmap.go#L846-L858

Could close the fd making the `DumpReliablyWithCallback` to fail while iterating the same map.

https://github.com/cilium/cilium/blob/60f074d63f9f8b3e6cfccf62d99f7c58b4d6c11d/pkg/bpf/map_linux.go#L717

The following stack trace shows this happening when doing a `GetModel`, which happens on a `cilium sysdump` for example, but I believe the same can theoretically happen while doing a GC of the CT map since the `CalculateCTMapPressure` controller runs every 30 seconds and if the GC takes more than 30 then the cleanup will be interrupted in the middle.

I didn't find any locking mechanism to prevent this from happening.

```
2025-01-30T21:27:22.005325276Z Read at 0x00c0099535a8 by goroutine 6096710:
2025-01-30T21:27:22.005373476Z   github.com/cilium/ebpf/internal/sys.(*FD).Uint()
2025-01-30T21:27:22.005379677Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/internal/sys/fd.go:71 +0x144
2025-01-30T21:27:22.005446912Z   github.com/cilium/ebpf.(*Map).nextKey()
2025-01-30T21:27:22.005454006Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/map.go:993 +0x112
2025-01-30T21:27:22.005553101Z   github.com/cilium/ebpf.(*Map).NextKey()
2025-01-30T21:27:22.005560745Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/map.go:950 +0xae
2025-01-30T21:27:22.005640643Z   github.com/cilium/cilium/pkg/bpf.(*Map).NextKey()
2025-01-30T21:27:22.005647146Z       /go/src/github.com/cilium/cilium/pkg/bpf/map_linux.go:606 +0x11e
2025-01-30T21:27:22.005712027Z   github.com/cilium/cilium/pkg/bpf.(*Map).DumpReliablyWithCallback()
2025-01-30T21:27:22.005718629Z       /go/src/github.com/cilium/cilium/pkg/bpf/map_linux.go:768 +0x71b
2025-01-30T21:27:22.005815760Z   github.com/cilium/cilium/pkg/bpf.(*Map).GetModel()
2025-01-30T21:27:22.005822322Z       /go/src/github.com/cilium/cilium/pkg/bpf/map_linux.go:1413 +0x511
2025-01-30T21:27:22.005880481Z   github.com/cilium/cilium/pkg/bpf.GetOpenMaps()
2025-01-30T21:27:22.005886152Z       /go/src/github.com/cilium/cilium/pkg/bpf/map_register_linux.go:64 +0x2ad
2025-01-30T21:27:22.006024930Z   github.com/cilium/cilium/pkg/maps.(*getMapHandler).Handle()
2025-01-30T21:27:22.006034067Z       /go/src/github.com/cilium/cilium/pkg/maps/api.go:146 +0x24
2025-01-30T21:27:22.006242771Z   github.com/cilium/cilium/api/v1/server/restapi/daemon.(*GetMap).ServeHTTP()
2025-01-30T21:27:22.006254163Z       /go/src/github.com/cilium/cilium/api/v1/server/restapi/daemon/get_map.go:56 +0x289
2025-01-30T21:27:22.006259241Z   github.com/go-openapi/runtime/middleware.(*Context).RoutesHandler.NewOperationExecutor.func1()
2025-01-30T21:27:22.006263830Z       /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/operation.go:28 +0x8d
2025-01-30T21:27:22.006268328Z   net/http.HandlerFunc.ServeHTTP()
2025-01-30T21:27:22.006272597Z       /usr/local/go/src/net/http/server.go:2220 +0x47
2025-01-30T21:27:22.006277075Z   github.com/go-openapi/runtime/middleware.NewRouter.func1()
2025-01-30T21:27:22.006281593Z       /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/router.go:80 +0x316
2025-01-30T21:27:22.006285891Z   net/http.HandlerFunc.ServeHTTP()
2025-01-30T21:27:22.006290169Z       /usr/local/go/src/net/http/server.go:2220 +0x47
2025-01-30T21:27:22.006302292Z   github.com/go-openapi/runtime/middleware.Redoc.serveUI.func1()
2025-01-30T21:27:22.006306871Z       /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/ui_options.go:164 +0x119
2025-01-30T21:27:22.006311239Z   net/http.HandlerFunc.ServeHTTP()
2025-01-30T21:27:22.006315867Z       /usr/local/go/src/net/http/server.go:2220 +0x47
2025-01-30T21:27:22.006320435Z   github.com/go-openapi/runtime/middleware.Spec.func1()
2025-01-30T21:27:22.006325495Z       /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/spec.go:72 +0x230
2025-01-30T21:27:22.006330965Z   net/http.HandlerFunc.ServeHTTP()
2025-01-30T21:27:22.006336205Z       /usr/local/go/src/net/http/server.go:2220 +0x47
2025-01-30T21:27:22.006341785Z   github.com/cilium/cilium/pkg/metrics.(*APIEventTSHelper).ServeHTTP()
2025-01-30T21:27:22.006346464Z       /go/src/github.com/cilium/cilium/pkg/metrics/middleware.go:63 +0x3c4
2025-01-30T21:27:22.006351363Z   github.com/cilium/cilium/pkg/api.(*APIPanicHandler).ServeHTTP()
2025-01-30T21:27:22.006357275Z       /go/src/github.com/cilium/cilium/pkg/api/apipanic.go:49 +0xf4
2025-01-30T21:27:22.006362744Z   net/http.(*ServeMux).ServeHTTP()
2025-01-30T21:27:22.006368355Z       /usr/local/go/src/net/http/server.go:2747 +0x255
2025-01-30T21:27:22.006373885Z   net/http.serverHandler.ServeHTTP()
2025-01-30T21:27:22.006379416Z       /usr/local/go/src/net/http/server.go:3210 +0x2a1
2025-01-30T21:27:22.006385236Z   net/http.(*conn).serve()
2025-01-30T21:27:22.006391047Z       /usr/local/go/src/net/http/server.go:2092 +0x12a4
2025-01-30T21:27:22.006395776Z   net/http.(*Server).Serve.gowrap3()
2025-01-30T21:27:22.006400966Z       /usr/local/go/src/net/http/server.go:3360 +0x4f
2025-01-30T21:27:22.006406075Z 
2025-01-30T21:27:22.006410985Z Previous write at 0x00c0099535a8 by goroutine 4182:
2025-01-30T21:27:22.006418068Z   github.com/cilium/ebpf/internal/sys.(*FD).Disown()
2025-01-30T21:27:22.006423969Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/internal/sys/fd.go:93 +0x8e
2025-01-30T21:27:22.006429549Z   github.com/cilium/ebpf/internal/sys.(*FD).Close()
2025-01-30T21:27:22.006435180Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/internal/sys/fd.go:84 +0x47
2025-01-30T21:27:22.006870411Z   github.com/cilium/ebpf.(*Map).Close()
2025-01-30T21:27:22.006879989Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/map.go:1371 +0x1e6
2025-01-30T21:27:22.006884858Z   github.com/cilium/cilium/pkg/bpf.(*Map).Close()
2025-01-30T21:27:22.006890338Z       /go/src/github.com/cilium/cilium/pkg/bpf/map_linux.go:591 +0x1ac
2025-01-30T21:27:22.006895778Z   github.com/cilium/cilium/pkg/maps/ctmap.CalculateCTMapPressure.func1.deferwrap1()
2025-01-30T21:27:22.006901959Z       /go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:858 +0x33
2025-01-30T21:27:22.006907119Z   runtime.deferreturn()
2025-01-30T21:27:22.006957073Z       /usr/local/go/src/runtime/panic.go:605 +0x5d
2025-01-30T21:27:22.006962683Z   github.com/cilium/cilium/pkg/controller.(*controller).runController()
2025-01-30T21:27:22.007064754Z       /go/src/github.com/cilium/cilium/pkg/controller/controller.go:251 +0xa2
2025-01-30T21:27:22.007072437Z   github.com/cilium/cilium/pkg/controller.(*Manager).createControllerLocked.gowrap1()
2025-01-30T21:27:22.007077677Z       /go/src/github.com/cilium/cilium/pkg/controller/manager.go:111 +0xbc
2025-01-30T21:27:22.007081986Z 
2025-01-30T21:27:22.007089579Z Goroutine 6096710 (running) created at:
2025-01-30T21:27:22.007095280Z   net/http.(*Server).Serve()
2025-01-30T21:27:22.007100720Z       /usr/local/go/src/net/http/server.go:3360 +0x8ec
2025-01-30T21:27:22.007114326Z   github.com/cilium/cilium/api/v1/server.(*Server).Start.func1()
2025-01-30T21:27:22.007119435Z       /go/src/github.com/cilium/cilium/api/v1/server/server.go:460 +0xd1
2025-01-30T21:27:22.007124324Z   github.com/cilium/cilium/api/v1/server.(*Server).Start.gowrap1()
2025-01-30T21:27:22.007129814Z       /go/src/github.com/cilium/cilium/api/v1/server/server.go:464 +0x4f
2025-01-30T21:27:22.007134142Z 
2025-01-30T21:27:22.007138921Z Goroutine 4182 (running) created at:
2025-01-30T21:27:22.007144712Z   github.com/cilium/cilium/pkg/controller.(*Manager).createControllerLocked()
2025-01-30T21:27:22.007150583Z       /go/src/github.com/cilium/cilium/pkg/controller/manager.go:111 +0x777
2025-01-30T21:27:22.007156023Z   github.com/cilium/cilium/pkg/controller.(*Manager).updateController()
2025-01-30T21:27:22.007161153Z       /go/src/github.com/cilium/cilium/pkg/controller/manager.go:84 +0x50f
2025-01-30T21:27:22.007166964Z   github.com/cilium/cilium/pkg/controller.(*Manager).UpdateController()
2025-01-30T21:27:22.007175199Z       /go/src/github.com/cilium/cilium/pkg/controller/manager.go:52 +0x257
2025-01-30T21:27:22.007180209Z   github.com/cilium/cilium/pkg/maps/ctmap.CalculateCTMapPressure()
2025-01-30T21:27:22.007185198Z       /go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:840 +0x75
2025-01-30T21:27:22.007222557Z   github.com/cilium/cilium/pkg/maps/ctmap/gc.(*GC).Enable.func3()
2025-01-30T21:27:22.007230763Z       /go/src/github.com/cilium/cilium/pkg/maps/ctmap/gc/gc.go:257 +0x12a
```

### PR DESCRIPTION
**Pull request by aditighag**
The method previously accessed the map construct directly, which could result in race conditions with other operations on the map, such as in the `Close` method.

One such data race was reported in the ctmap, where the map was closed by a periodically running controller while it was simultaneously accessed in `DumpReliablyWithCallback`. Currently, callers can invoke map operations in the callback
that acquire the map (write) lock. To allow such callbacks without causing a deadlock, acquire the (write) lock instead
of RLock.

(snippet)

```
2025-01-30T21:27:22.005325276Z Read at 0x00c0099535a8 by goroutine 6096710:
2025-01-30T21:27:22.005373476Z   github.com/cilium/ebpf/internal/sys.(*FD).Uint()
2025-01-30T21:27:22.005379677Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/internal/sys/fd.go:71 +0x144
2025-01-30T21:27:22.005446912Z   github.com/cilium/ebpf.(*Map).nextKey()
2025-01-30T21:27:22.005454006Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/map.go:993 +0x112
2025-01-30T21:27:22.005553101Z   github.com/cilium/ebpf.(*Map).NextKey()
2025-01-30T21:27:22.005560745Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/map.go:950 +0xae
2025-01-30T21:27:22.005640643Z   github.com/cilium/cilium/pkg/bpf.(*Map).NextKey()
2025-01-30T21:27:22.005647146Z       /go/src/github.com/cilium/cilium/pkg/bpf/map_linux.go:606 +0x11e
2025-01-30T21:27:22.005712027Z   github.com/cilium/cilium/pkg/bpf.(*Map).DumpReliablyWithCallback()
2025-01-30T21:27:22.005718629Z       /go/src/github.com/cilium/cilium/pkg/bpf/map_linux.go:768 +0x71b
2025-01-30T21:27:22.005815760Z   github.com/cilium/cilium/pkg/bpf.(*Map).GetModel()
2025-01-30T21:27:22.005822322Z       /go/src/github.com/cilium/cilium/pkg/bpf/map_linux.go:1413 +0x511
2025-01-30T21:27:22.005880481Z   github.com/cilium/cilium/pkg/bpf.GetOpenMaps()
2025-01-30T21:27:22.005886152Z       /go/src/github.com/cilium/cilium/pkg/bpf/map_register_linux.go:64 +0x2ad
2025-01-30T21:27:22.006024930Z   github.com/cilium/cilium/pkg/maps.(*getMapHandler).Handle()
2025-01-30T21:27:22.006034067Z       /go/src/github.com/cilium/cilium/pkg/maps/api.go:146 +0x24

```

```
2025-01-30T21:27:22.006410985Z Previous write at 0x00c0099535a8 by goroutine 4182:
2025-01-30T21:27:22.006418068Z   github.com/cilium/ebpf/internal/sys.(*FD).Disown()
2025-01-30T21:27:22.006423969Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/internal/sys/fd.go:93 +0x8e
2025-01-30T21:27:22.006429549Z   github.com/cilium/ebpf/internal/sys.(*FD).Close()
2025-01-30T21:27:22.006435180Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/internal/sys/fd.go:84 +0x47
2025-01-30T21:27:22.006870411Z   github.com/cilium/ebpf.(*Map).Close()
2025-01-30T21:27:22.006879989Z       /go/src/github.com/cilium/cilium/vendor/github.com/cilium/ebpf/map.go:1371 +0x1e6
2025-01-30T21:27:22.006884858Z   github.com/cilium/cilium/pkg/bpf.(*Map).Close()
2025-01-30T21:27:22.006890338Z       /go/src/github.com/cilium/cilium/pkg/bpf/map_linux.go:591 +0x1ac
2025-01-30T21:27:22.006895778Z   github.com/cilium/cilium/pkg/maps/ctmap.CalculateCTMapPressure.func1.deferwrap1()
2025-01-30T21:27:22.006901959Z       /go/src/github.com/cilium/cilium/pkg/maps/ctmap/ctmap.go:858 +0x33
2025-01-30T21:27:22.006907119Z   runtime.deferreturn()
2025-01-30T21:27:22.006957073Z       /usr/local/go/src/runtime/panic.go:605 +0x5d
2025-01-30T21:27:22.006962683Z   github.com/cilium/cilium/pkg/controller.(*controller).runController()
2025-01-30T21:27:22.007064754Z       /go/src/github.com/cilium/cilium/pkg/controller/controller.go:251 +0xa2
2025-01-30T21:27:22.007072437Z   github.com/cilium/cilium/pkg/controller.(*Manager).createControllerLocked.gowrap1()
2025-01-30T21:27:22.007077677Z       /go/src/github.com/cilium/cilium/pkg/controller/manager.go:111 +0xbc
```

Fixes: https://github.com/cilium/cilium/issues/37383

```release-note
Fix data race involving DumpReliablyWithCallback map operation.
```

### CODE REVIEW

**Comment by tommyp1ckles** [comment]
There's a couple other places we access that directly, such as in the batch iterator: IterateAll function.

**Comment by aditighag** [comment]
The test failures are due to a deadlock where map entries are being deleted while iterating over the map. The tricky thing is that the cilium agent has a common pattern where map entries are deleted while the map is being iterated.  The logic is written with the assumption that `DumpReliablyWithCallback` doesn't acquire the map lock. Do we need some kind of implicit ref counting for map open and close operations as opposed to the current locking approach?

```
sync.(*RWMutex).Lock(0xc003cd74c0?)
        /usr/local/go/src/sync/rwmutex.go:155 +0x6a
github.com/cilium/cilium/pkg/bpf.(*Map).Delete(0xc0026276c0, {0x5727130, 0xc00093c9e0})
        ./pkg/bpf/map_linux.go:1283 +0x45
github.com/cilium/cilium/pkg/maps/ctmap.purgeCtEntry(0xc0026276c0?, {0x57704b0, 0xc00093c9e0}, 0xc001f44c00, 0x0, 0xc00147d500, 0x0)
        ./pkg/maps/ctmap/ctmap.go:387 +0x50
github.com/cilium/cilium/pkg/maps/ctmap.doGCForFamily.cleanup.func3({0x5727130?, 0xc00093c9e0}, {0x5727068, 0xc001f44c00})
        ./pkg/maps/ctmap/ctmap.go:463 +0x398
github.com/cilium/cilium/pkg/bpf.(*Map).DumpReliablyWithCallback(0xc0026276c0, 0xc001f171d0, 0xc001f17130)
        ./pkg/bpf/map_linux.go:799 +0x4df
github.com/cilium/cilium/pkg/maps/ctmap.iterate[...](0xc0026276c0, 0xc000ffb580, 0xc001f171d0)
        ./pkg/maps/ctmap/ctmap.go:415 +0x6c
github.com/cilium/cilium/pkg/maps/ctmap.doGCForFamily(0xc0026276c0, {0x0?, 0xc0?, 0x0?, 0xc00074d230?}, 0xc00147d500, 0xc00147d540, 0x0)
        ./pkg/maps/ctmap/ctmap.go:375 +0xa05
github.com/cilium/cilium/pkg/maps/ctmap.doGC(0xc000e7dc30?, {0x90?, 0xc0?, 0x0?, 0xc00074d230?}, 0x479ef60?, 0xc002627710?)
        ./pkg/maps/ctmap/ctmap.go:503 +0x65
```

File: pkg/bpf/map_linux.go [hunk 1]
```diff
@@ -739,6 +740,17 @@ func (m *Map) DumpReliablyWithCallback(cb DumpCallback, stats *DumpStats) error
 		return err
 	}
 
+	// Acquire a (write) lock here as callers can invoke map operations in the
+	// DumpCallback that need a (write) lock.
+	// See GH issue - https://github.com/cilium/cilium/pull/38590.
```
Comment (rgo3) [inline pkg/bpf/map_linux.go]: You are linking the current PR instead of an issue, is that intended?

**Review by rgo3 — COMMENTED** [review]
I see other functions that call `m.Delete`, e.g. `doFlush4/6`, which are passed as a callback to `DumpReliablyWithCallback`. Shouldn't those call `m.DeleteLocked` instead?

As a nit, there is a typo in the second commit message, referring to nat as "nap".

File: pkg/bpf/map_linux.go (hunk 1 above)
Comment (aditighag) [reply pkg/bpf/map_linux.go]: Yes, I intend to link the PR as it has more context.

**Comment by aditighag** [comment]
> I see other functions that call `m.Delete`, e.g. `doFlush4/6`, which are passed as a callback to `DumpReliablyWithCallback`. Shouldn't those call `m.DeleteLocked` instead?
> 
> As a nit, there is a typo in the second commit message, referring to nat as "nap".

Thanks, fixed. I also added a unit test for the `doFlush{4,6}` functions.

**Comment by aditighag** [comment]
Rebased to resolve the merge conflicts in the latest push.

**Comment by rgo3** [comment]
ci-e2e-upgrade shows a failure/flake when deleting CT entries on the first run. Is that an existing flake or are we potentially creating a new one here?

**Comment by aditighag** [comment]
> ci-e2e-upgrade shows a failure/flake when deleting CT entries on the first run. Is that an existing flake or are we potentially creating a new one here?

It's similar to this one - https://github.com/cilium/cilium/issues/38498. @tommyp1ckles We could have similar error reports during ct flush operation as LRU might've kicked some keys.

**Comment by tommyp1ckles** [comment]
@aditighag @rgo3 The ctmap flush command uses the same [underlying code ](https://github.com/cilium/cilium/blob/main/pkg/maps/ctmap/ctmap.go#L616) (i.e. doGCForFamily) as the general GC. So that should be captured by the same recent fix: https://github.com/cilium/cilium/blob/main/pkg/maps/ctmap/ctmap.go#L462

File: pkg/bpf/map_linux.go [hunk 2]
```diff
@@ -1307,6 +1307,14 @@ func (m *Map) Delete(key MapKey) error {
 	return err
 }
 
+// DeleteLocked deletes the map entry corresponding to the given key. Must be called
+// with m.lock.
```
Comment (tommyp1ckles) [inline pkg/bpf/map_linux.go]: This does feel like a bit of a strange API choice given that the underlying lock is a implementation detail that is not exported.  Since the actual intention is to provide an API that can be called from a iterator callback function without causing deadlocks, we should probably just say that.

Comment (tommyp1ckles) [reply pkg/bpf/map_linux.go]: Otherwise, this is sort of a limitation with the whole callback iterator approach.

One idea I have to improve this is to amend the DumpCallback type to be something like:

```go
type DumpCallback func(key MapKey, value MapValue, mh MapHandle)
```

Where MapHandle implements the "unlocked" versions of bpf operations, which would look something like:

```go
m.DumpReliablyWithCallback(func(k MapKey, v MapValue, mh MapHandle) {
    mh.Delete(k)
}, stats)
```

Comment (aditighag) [reply pkg/bpf/map_linux.go]: >Since the actual intention is to provide an API that can be called from a iterator callback function without causing deadlocks, we should probably just say that.

Fair enough! I'll update it.

>Where MapHandle implements the "unlocked" versions of bpf operations

Sg, we could potentially make the function private.

**Review by tommyp1ckles — APPROVED** [review]

**Review by rgo3 — APPROVED** [review]

**Comment by julianwiedmann** [comment]
@aditighag given this is `release-note/bug`, should the fix also go back into v1.17? Or is the severity low enough that we can skip the backport?
