### PR TITLE
Fixing k8s 1.6 and 1.7 compatibility with CRD and TPR

### LINKED ISSUE #947: Extend Cilium TPR with CRD
K8s Third Party Resources will be deprecated so we need to replace them with the new Custom Resource Definitions.

More info:
https://github.com/kubernetes/kubernetes.github.io/blob/release-1.7/docs/tasks/access-kubernetes-api/extend-api-third-party-resource.md#migration-to-customresourcedefinitions

### LINKED ISSUE #1168: Log is spammed with Failed to list *v1.NetworkPolicy
```
time="2017-07-23T23:27:24Z" level=error msg="github.com/cilium/cilium/daemon/k8s_watcher.go:139: Failed to list *v1.NetworkPolicy: the server could not find the requested resource"
```

### LINKED ISSUE #1187: Re-add v1beta1 NetworkPolicy
The transition is very difficult if we don't support  both over a period of time.

### PR DESCRIPTION
**Pull request by aanm**
This PR was first created to deal with the huge SPAM of log messages stating `v1.NetworkPolicy does not exist` that were appearing in k8s `v1.6.x`. Instead, there were solved a couple of problems where the description and the solution for each one are resumed here.

**Problem 1**:

Since we dropped the support for `v1beta1.NetworkPolicy` in `0.10.0` we soon realized we should kept the old `v1beta1` for a one or 2 cilium versions (TBD). Without the support for `v1beta1` users running k8s `1.6.x` won't be able to test network policy enforcement with cilium.

**Solution** :

Cilium will detected if `v1.NetworkPolicy` is **not** available and will stop to listen for this object type. It will print a suggestion to a user running k8s `1.6.x` that he should update its kubernetes version to `>=1.7.x`

**Problem 2**:
Since we have upgrade k8s to `1.7.0` in the runtime tests, we started seeing failures that were occurring sporadically for the getting started guide for k8s and the L7 stresstests tests. We soon realized the kubernetes `1.7.0` had issues with Third Party Resources (TPR) and cilium wasn't receiving Cilium Network Policies from k8s api server, causing pods that weren't allow to talk with each other to talk with each other.

**Solution**:
Changed Cilium Network Policy definition to Custom Resource Definition (CRD). We changed all TPR code to CRD.

**Problem 3**:

CRD is not available in k8s <=`1.6.x`.

**Solution**:

Kept some of the TPR code so that we could have a transition period.

**Problem 4**:

TPR and CRD conflict if they are used at the same time in the same cluster. This causes Cilium to receive some updates of the cilium network policies added in the kubernetes cluster but if that policy is deleted then cilium might or might not receive that update.

**Solution**:

Bumped the CiliumNetworkPolicy definition to v2. If the user tries to run cilium in k8s `1.7.x` with TPR resources installed, he will see a warning message:

```
level=warning msg="Detected conflicting TPR and CRD, please migrate all ThirdPartyResource to CustomResourceDefinition! More info: https://cilium.link/migrate-tpr"
level=warning msg="Due conflicting TPR and CRD rules CiliumNetworkPolicy enforcement can't be guaranteed!"
```

The user will be in charge of changing all CiliumNetworkPolicy specs to v2.

TODO: ~Replace the short link with a cilium link~ giving some instructions regarding this issue with some examples on how to remove the old CiliumNetworkPolicy TPR.

**Problem 5**:

After all k8s issues were resolved we have noticed the L7 proxy library might have a small delay of 1-5 seconds if the system is under heavy load, when it's being set up to enforce L7 rules.

**Solution**:

Add a `sleep 10s` after setting up NetworkPolicies in kubernetes to give the L7 proxy more than reasonable time to set up.
Add a missing log.Error in case the L7 proxy fails to be set up.

The L7 proxy library will be fixed in a follow-up PR.

Fixes #947
Fixes #1168 
Fixes #1187

### CODE REVIEW

File: daemon/k8s_watcher.go [hunk 1]
```diff
@@ -62,17 +63,25 @@ func k8sErrorHandler(e error) {
...
-		})
+	errstr := e.Error()
+	k8sErrMsgMU.Lock()
+	// if the error message already exists in the map then in print it
+	// otherwise we create a new timer for that specific message in the
+	// k8sErrMsg map.
+	if t, ok := k8sErrMsg[errstr]; !ok {
+		// Omitting the 'connection refused' common messages and
+		// Failed to list NetworkPolicy for k8s < 1.7
+		if strings.Contains(errstr, "connection refused") ||
```
Comment (tgraf) [inline daemon/k8s_watcher.go]: This is better but we should check k8s version and omit it altogether if it has no chance of succeeding. I suggest we don't even start listening for NetworkPolicy for 1.7. Instead, in that case, a single warning message, in the beginning, should indicate that due to version, NetworkPolicy is not supported.

Once a minute still means  1440 duplicate log messages every day.

**Review by tgraf — CHANGES_REQUESTED** [review]

File: daemon/k8s_watcher.go [hunk 2]
```diff
@@ -94,24 +96,63 @@ func k8sErrorHandler(e error) {
 	log.Error(e)
 }
 
-func (d *Daemon) createThirdPartyResources() error {
+func createCustomResourceDefinitions(clientset apiextensionsclient.Interface) error {
```
Comment (tgraf) [inline daemon/k8s_watcher.go]: This would mean that we can't use CNP < 1.7, correct?

Comment (aanm) [reply daemon/k8s_watcher.go]: Correct. I can make ThirdPartyResource for k8s < 1.7, should I?

Comment (dqminh) [reply daemon/k8s_watcher.go]: i was also working on some related changes for this. I think we should support both at least until tpr was deprecated fully. Probably something like this should suffice

```
ver, err := k8s.ClusterVersion()
useCRD := len(ver) >= 2 && ver[1] >= 7
// check and use crd, otherwise tpr
```

also we probably want to have a migrator that migrates things from tpr to crd ? not sure if its worth it though or users should just recreate things.

Comment (aanm) [reply daemon/k8s_watcher.go]: Fixed

File: daemon/k8s_watcher.go [hunk 3]
```diff
@@ -246,6 +260,51 @@ func (d *Daemon) deleteK8sNetworkPolicy(obj interface{}) {
...
+		return
+	}
+
+	opts := AddOptions{Replace: true}
+	if _, err := d.PolicyAdd(rules, &opts); err != nil {
+		log.Errorf("Error while adding kubernetes v1beta1 network policy %+v: %s", rules, err)
+		return
+	}
+
+	log.Infof("Kubernetes v1beta1 network policy '%s' successfully add", k8sNP.Name)
```
Comment (tgraf) [inline daemon/k8s_watcher.go]: nit: added

File: daemon/k8s_watcher.go [hunk 4]
```diff
@@ -62,17 +64,28 @@ func k8sErrorHandler(e error) {
...
+	// if the error message already exists in the map then in print it
+	// otherwise we create a new timer for that specific message in the
+	// k8sErrMsg map.
+	if t, ok := k8sErrMsg[errstr]; !ok {
+		// Omitting the 'connection refused' common messages
+		if strings.Contains(errstr, "connection refused") {
+			k8sErrMsg[errstr] = time.NewTimer(k8sErrLogTimeout)
+			k8sErrMsgMU.Unlock()
+		} else {
+			log.Warningf("Consider upgrading kubernetes to >=1.7 to enforce NetworkPolicy version 1")
```
Comment (tgraf) [inline daemon/k8s_watcher.go]: Where is the `k8sErrMsgMU.Unlock()` in this path?

**Review by tgraf — CHANGES_REQUESTED** [review]

File: daemon/k8s_watcher.go (hunk 4 above)
Comment (aanm) [reply daemon/k8s_watcher.go]: I miss it, thanks!

File: daemon/k8s_watcher.go [hunk 5]
```diff
@@ -62,17 +66,29 @@ func k8sErrorHandler(e error) {
...
+	// otherwise we create a new timer for that specific message in the
+	// k8sErrMsg map.
+	if t, ok := k8sErrMsg[errstr]; !ok {
+		// Omitting the 'connection refused' common messages
+		if strings.Contains(errstr, "connection refused") {
+			k8sErrMsg[errstr] = time.NewTimer(k8sErrLogTimeout)
+			k8sErrMsgMU.Unlock()
+		} else {
+			k8sErrMsgMU.Unlock()
+			log.Warningf("Consider upgrading kubernetes to >=1.7 to enforce NetworkPolicy version 1")
```
Comment (ianvernon) [inline daemon/k8s_watcher.go]: Shouldn't this log message be within the following if-block?

File: daemon/k8s_watcher.go [hunk 6]
```diff
@@ -81,19 +97,76 @@ func k8sErrorHandler(e error) {
...
+		},
+	}
+
+	_, err := clientset.ApiextensionsV1beta1().CustomResourceDefinitions().Create(res)
+	if err != nil && !errors.IsAlreadyExists(err) {
+		return err
+	}
+
+	log.Infof("k8s: Waiting for CRD to be established in k8s api-server...")
+	// wait for CRD being established
```
Comment (ianvernon) [inline daemon/k8s_watcher.go:132]: Wait for CRD to be established

File: daemon/k8s_watcher.go [hunk 7]
```diff
@@ -81,19 +97,76 @@ func k8sErrorHandler(e error) {
...
+					return false, err
+				}
+			}
+		}
+		return false, err
+	})
+	if err != nil {
+		deleteErr := clientset.ApiextensionsV1beta1().CustomResourceDefinitions().Delete(cnpCRDName, nil)
+		if deleteErr != nil {
+			return fmt.Errorf("k8s: unable to delete CRD %s. Deleting CRD due: %s", deleteErr, err)
```
Comment (ianvernon) [inline daemon/k8s_watcher.go:156]: due to:

File: daemon/k8s_watcher.go [hunk 8]
```diff
@@ -110,20 +183,49 @@ func (d *Daemon) EnableK8sWatcher(reSyncPeriod time.Duration) error {
...
+	if err != nil {
+		return fmt.Errorf("Unable to create rest configuration for k8s CRD: %s", err)
+	}
+
+	clientName := "custom resource definition"
+
+	if err := createCustomResourceDefinitions(apiextensionsclientset); errors.IsNotFound(err) {
+		// If CRD was not found it might mean we are running in k8s <1.7
+		// then we should set up TPR instead
+		log.Debugf("Detected k8s <1.7, using TPR instead of CRD")
```
Comment (ianvernon) [inline daemon/k8s_watcher.go]: The log says it 'might mean' we are running k8s with version <1.7, but can we be sure of that? We should check the version of K8s via the API if possible, as this log statement might be incorrect based on the above comment.

File: daemon/k8s_watcher.go [hunk 9]
```diff
@@ -81,19 +97,76 @@ func k8sErrorHandler(e error) {
...
 
+	res := &apiextensionsv1beta1.CustomResourceDefinition{
+		ObjectMeta: metav1.ObjectMeta{
+			Name: cnpCRDName,
+		},
+		Spec: apiextensionsv1beta1.CustomResourceDefinitionSpec{
+			Group:   k8s.CustomResourceDefinitionGroup,
+			Version: k8s.CustomResourceDefinitionVersion,
+			Names: apiextensionsv1beta1.CustomResourceDefinitionNames{
+				Plural:     "ciliumnetworkpolicies",
```
Comment (ianvernon) [inline daemon/k8s_watcher.go:117]: Nit - would be better to have these strings as constants as some of them (e.g., the plural) are used elsewhere in the code.

File: daemon/k8s_watcher.go [hunk 10]
```diff
@@ -246,6 +348,51 @@ func (d *Daemon) deleteK8sNetworkPolicy(obj interface{}) {
...
+	k8sNP, ok := obj.(*v1beta1.NetworkPolicy)
+	if !ok {
+		log.Errorf("Ignoring invalid k8s v1beta1.NetworkPolicy deletion")
+		return
+	}
+
+	labels := labels.ParseSelectLabelArray(k8s.ExtractPolicyNameDeprecated(k8sNP))
+
+	if _, err := d.PolicyDelete(labels); err != nil {
+		log.Errorf("Error while deleting v1beta1 kubernetes network policy %+v: %s", labels, err)
```
Comment (ianvernon) [inline daemon/k8s_watcher.go:399]: General comment - a lot of these logs are inconsistent in how they phrase things, for example:
`v1beta1 kubernetes network policy` vs `kubernetes v1beta1`, `NetworkPolicy` vs `network policy`, `kubernetes` vs. `k8s`.

I think it's important for us to stick to convention when writing these logs, esp. for when we are searching logs to debug. If there is not a convention, we might miss out on key information.

File: pkg/k8s/network_policy_v1beta.go [hunk 11]
```diff
@@ -0,0 +1,132 @@
...
+		//   If this field is empty or missing, this rule matches all
+		//   sources (traffic not restricted by source).
+		if iRule.From == nil || len(iRule.From) == 0 {
+			all := api.NewESFromLabels(
+				labels.NewLabel(labels.IDNameAll, "", labels.LabelSourceReserved),
+			)
+			ingress.FromEndpoints = append(ingress.FromEndpoints, all)
+		} else {
+			for _, rule := range iRule.From {
+				// Only one or the other can be set, not both
```
Comment (ianvernon) [inline pkg/k8s/network_policy_v1beta.go:56]: This is saying that only rule.PodSelector or rule.NamespaceSelector can be set, but not both; should we check to see if both are set, and error out accordingly?

File: pkg/k8s/network_policy_v1beta.go [hunk 12]
```diff
@@ -0,0 +1,132 @@
...
+				if rule.PodSelector != nil {
+					if rule.PodSelector.MatchLabels == nil {
+						rule.PodSelector.MatchLabels = map[string]string{}
+					}
+					// The PodSelector should only reflect to the same namespace
```
Comment (ianvernon) [inline pkg/k8s/network_policy_v1beta.go:61]: 'should only reflect the namespace for which the policy is being stored'

File: pkg/k8s/network_policy_v1beta.go [hunk 13]
```diff
@@ -0,0 +1,132 @@
...
+					matchLabels := map[string]string{}
+					// We use our own special label prefix for namespace metadata,
+					// thus we need to prefix that prefix to all NamespaceSelector.MatchLabels
+					for k, v := range rule.NamespaceSelector.MatchLabels {
+						matchLabels[policy.JoinPath(PodNamespaceMetaLabels, k)] = v
+					}
+					rule.NamespaceSelector.MatchLabels = matchLabels
+
+					// We use our own special label prefix for namespace metadata,
+					// thus we need to prefix that prefix to all NamespaceSelector.MatchLabels
```
Comment (ianvernon) [inline pkg/k8s/network_policy_v1beta.go:77]: This comment is duplicated from above, and doesn't seem to apply here.

File: daemon/k8s_watcher.go (hunk 5 above)
Comment (aanm) [reply daemon/k8s_watcher.go]: Fixed!

**Comment by aanm** [comment]
@ianvernon Let's do the nits / comments on a following PR
@tgraf the PR has passed the last 2 builds. I've triggered one last time to see how it goes. The `sleep 10s` seems to have worked.

**Comment by tgraf** [comment]
> @ianvernon Let's do the nits / comments on a following PR
> @tgraf the PR has passed the last 2 builds. I've triggered one last time to see how it goes. The sleep 10s seems to have worked.

Sounds good. The only remaining question I have is the removal of TPR if CRD is present. Is this a requirement? It will mean that users *have* to migrate to CRD if they want to use k8s 1.7.

**Comment by aanm** [comment]
@tgraf ready to be merged!

**Comment by ianvernon** [comment]
Fantastic work !

**Review by tgraf — APPROVED** [review]

**Comment by tgraf** [comment]
Great work @aanm !!!
