### PR TITLE
datapath/iptables: Masquerade hairpin traffic that traversed the stack

### LINKED ISSUE #9784: Request time out from container to other container using hostIP:hostPort on same host with portmap CNI chained
## Bug report

**General Information**

- Cilium version (run `cilium version`)
```
Client: 1.6.4 8048d320a 2019-11-27T17:00:12+01:00 go version go1.12.13 linux/amd64
Daemon: 1.6.4 8048d320a 2019-11-27T17:00:12+01:00 go version go1.12.13 linux/amd64
```
- Kernel version (run `uname -a`)
```
Linux tender-drake 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
```
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:09:21Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Link to relevant artifacts (policies, deployments scripts, ...)
- Upload a system dump (run `curl -sLO
releases.cilium.io/tools/cluster-diagnosis.zip &&
python cluster-diagnosis.zip sysdump` and then attach the generated zip file)

( The sysdump was too big to attach. Please let me know if it's needed and I'll send or make it available somehow. )

**How to reproduce the issue**

1. Install Cilium 1.6.4 using Helm chart from https://github.com/cilium/cilium/archive/v1.6.4.tar.gz with the following values:
```yaml
---
global:
  tag: v1.6.4
  cluster:
    name: "k8slab"
    id: "1"
  cni:
    install: true
    chainingMode: portmap
  ipv4:
    enabled: true
  ipv6:
    enabled: false
  prometheus:
    enabled: false
```
2. Deploy container using `hostPort`
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
            hostPort: 35000
```
3. Deploy some debug container connecting to the `hostPort` service
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ubuntu
spec:
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command:
          - '/bin/bash'
          - '-c'
          - '--'
        args:
          - 'apt-get update -y; apt-get install -y netcat curl; while true; do sleep 30; done;'
```
4. Select a `hostPort` pod and debug pod on the same host (e.g. `nginx-2cb8j` and `ubuntu-vf44z` in the example below)
```shell
$ kubectl get po -owide
NAME           READY   STATUS    RESTARTS   AGE   IP             NODE            NOMINATED NODE   READINESS GATES
nginx-2cb8j    1/1     Running   0          24m   172.16.3.16    tender-drake    <none>           <none>
nginx-7b4wr    1/1     Running   0          24m   172.16.7.154   mutual-dodo     <none>           <none>
nginx-drtk8    1/1     Running   0          24m   172.16.8.63    full-evil       <none>           <none>
nginx-dzk7n    1/1     Running   0          24m   172.16.4.59    right-ferret    <none>           <none>
nginx-l89zr    1/1     Running   0          24m   172.16.6.17    loving-gopher   <none>           <none>
nginx-l9ntn    1/1     Running   0          24m   172.16.5.128   strong-caiman   <none>           <none>
ubuntu-bb44g   1/1     Running   0          20m   172.16.5.210   strong-caiman   <none>           <none>
ubuntu-hhpv7   1/1     Running   0          20m   172.16.7.223   mutual-dodo     <none>           <none>
ubuntu-n2p99   1/1     Running   0          20m   172.16.4.245   right-ferret    <none>           <none>
ubuntu-rlv5c   1/1     Running   0          20m   172.16.6.156   loving-gopher   <none>           <none>
ubuntu-tjr88   1/1     Running   0          20m   172.16.8.70    full-evil       <none>           <none>
ubuntu-vf44z   1/1     Running   0          20m   172.16.3.47    tender-drake    <none>           <none>
```
5. Try to contact `hostPort` pod via its `hostIP`
Using the above example:
```shell
$ kubectl get pod nginx-2cb8j -ojsonpath='{.status.hostIP}'
10.24.214.230
$ kubectl exec -ti ubuntu-vf44z bash
root@ubuntu-vf44z:/# curl 10.24.214.230:35000 -v
* Rebuilt URL to: 10.24.214.230:35000/
*   Trying 10.24.214.230...
* TCP_NODELAY set
* connect to 10.24.214.230 port 35000 failed: Connection timed out
* Failed to connect to 10.24.214.230 port 35000: Connection timed out
* Closing connection 0
curl: (7) Failed to connect to 10.24.214.230 port 35000: Connection timed out
```

The `cilium monitor` output is (where id 568 is the debug pod `ubuntu-vf44z`):
```shell
cilium monitor --related-to 568
Listening for events on 32 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
level=info msg="Initializing dissection cache..." subsys=monitor
-> host from flow 0xab4466b0 identity 111636->1 state new ifindex cilium_net: 172.16.3.47:49290 -> 10.24.214.230:35000 tcp SYN
-> endpoint 568 flow 0x85c0bb7d identity 111706->111636 state new ifindex lxc2faa014a7904: 172.16.3.16:80 -> 172.16.3.47:49290 tcp SYN, ACK
-> host from flow 0x65945f77 identity 111636->1 state established ifindex cilium_net: 172.16.3.47:49290 -> 10.24.214.230:35000 tcp SYN
-> host from flow 0x405d06ef identity 111636->1 state established ifindex cilium_net: 172.16.3.47:49290 -> 10.24.214.230:35000 tcp SYN
-> host from flow 0xc974addb identity 111636->1 state established ifindex cilium_net: 172.16.3.47:49290 -> 10.24.214.230:35000 tcp SYN
-> host from flow 0x73876df9 identity 111636->1 state established ifindex cilium_net: 172.16.3.47:49290 -> 10.24.214.230:35000 tcp SYN
```

Contacting the hostPort pod using its ClusterIP works:
```shell
root@ubuntu-vf44z:/# curl 172.16.3.16:80 -I
HTTP/1.1 200 OK
...
```
and contacting a pod running on another host using the hostIP and hostPort works:
```shell
$ kubectl get pod nginx-7b4wr -ojsonpath='{.status.hostIP}'
10.24.214.232
root@ubuntu-vf44z:/# curl 10.24.214.232:35000 -I   
HTTP/1.1 200 OK
...
```

It seems the issue only arises when the source and destination pod is on the same host and the hostIP:hostPort is used.

### PR DESCRIPTION
**Pull request by tgraf**
This PR builds on https://github.com/cilium/cilium/pull/10926

The traffic is sent to the stack and hairpin'ed back into a local pod
after a component on the stack has applied a DNAT rule, the traffic must
be SNATed to ensure the reverse NAT can take place. This can happen if
portmap or kiam is being used and redirection happens to a local
destination.

The masquerade filter must be limited as not all DNAT traffic may be
affected. NodePort traffic from a non-local source must remain
unmasqueraded in order for trafficPolicy=local to continue working.

Also, when EnableEndpointRoutes is enabled, traffic always traverses the
stack and must not be masqueraded either.

Fixes: #9784
Requires: #10926

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by christarazi** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

File: pkg/datapath/iptables/iptables.go [hunk 1]
```diff
@@ -959,6 +959,35 @@ func (m *IptablesManager) InstallRules(ifName string) error {
...
+			//  - kiam if source and server are on the same node
+			if !option.Config.EnableEndpointRoutes {
+				if err := runProg("iptables", append(
+					m.waitArgs,
+					"-t", "nat",
+					"-A", ciliumPostNatChain,
+					"-m", "mark", "--mark", fmt.Sprintf("%#08x/%#08x", linux_defaults.MagicMarkIdentity, linux_defaults.MagicMarkHostMask),
+					"-o", localDeliveryInterface,
+					"-m", "conntrack", "--ctstate", "DNAT",
+					"-m", "comment", "--comment", "hairpin traffic that originating from a local pod",
```
Comment (qmonnet) [inline pkg/datapath/iptables/iptables.go]: `that originating` -> `originating` or `that originates`?

Another typo in commit log, `unmaqueraded`.

**Review by borkmann — APPROVED** [review]
Given we haven't seen this in non-chaining scenarios so far, should we gate this to avoid adding the rule for native Cilium setups?

File: pkg/datapath/linux/linux_defaults/mark.go [hunk 2]
```diff
@@ -72,6 +72,11 @@ const (
 	// MagicMarkHost determines that the traffic is sourced from the local
 	// host and not from a proxy.
 	MagicMarkHost int = 0x0C00
+
+	// MagicMarkIdentity determines that the traffic carries a security
+	// identity in the skb->mark
+	MagicMarkIdentity int = 0x0F00
+
```
Comment (qmonnet) [inline pkg/datapath/linux/linux_defaults/mark.go:74]: Should the comment above the `const` block be updated?

**Review by qmonnet — COMMENTED** [review]
Looks good to me, with minor nits.

**Comment by tgraf** [comment]
> Given we haven't seen this in non-chaining scenarios so far, should we gate this to avoid adding the rule for native Cilium setups?

This can happen in direct routing mode as well if `ENABLE_ROUTING` is enabled.

File: pkg/datapath/linux/linux_defaults/mark.go (hunk 2 above)
Comment (tgraf) [reply pkg/datapath/linux/linux_defaults/mark.go:74]: The meaning of the flag is unchanged. We use the fact that the identity is carried as proof that another Cilium endpoint is the source of the traffic.

Comment (tgraf) [reply pkg/datapath/linux/linux_defaults/mark.go:74]: @borkmann has since removed that comment since it was out of date

**Comment by tgraf** [comment]
test-me-please

**Review by joestringer — COMMENTED** [review]
Change looks good, do we have a small repro we can integrate into the CI? This type of bug seems easy to break by just rearranging rules a bit.

**Comment by tgraf** [comment]
> Change looks good, do we have a small repro we can integrate into the CI? This type of bug seems easy to break by just rearranging rules a bit.

Good point. I've extended the connectivity-check YAML to include hostport and added it to the CI. This uncovered one more case that needed fixing which required an additional commit.

**Comment by tgraf** [comment]
test-me-please

File: examples/kubernetes/connectivity-check/connectivity-check.yaml [hunk 3]
```diff
@@ -73,10 +73,62 @@ spec:
       - name: echo-container
         image: docker.io/cilium/json-mock:1.0
         imagePullPolicy: IfNotPresent
+        ports:
+        - containerPort: 80
+          hostPort: 40000
```
Comment (borkmann) [inline examples/kubernetes/connectivity-check/connectivity-check.yaml:78]: Also added one here for services (https://github.com/cilium/cilium/commit/ebd73929c3ae97a7a37424b10c603cd87d591bc8) but only for the BPF case so far. I wonder if we somewhat could consolidate both, just a thought; not needed for this series in here.

**Review by borkmann — APPROVED** [review]

**Comment by joestringer** [comment]
Tests were interrupted, retrying:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/18901/execution/node/198/log/?consoleFull

**Comment by joestringer** [comment]
restart-ginkgo

**Comment by tgraf** [comment]
restart-ginkgo

**Review by aanm — APPROVED** [review]
