### PR TITLE
proxy: Check whether a port is already open before allocating

### LINKED ISSUE #5532: Upgrade test fail from 1.2 to master due proxy context timeout
```
2018-09-12T05:38:01.615395888Z level=debug msg="Queueing container event" containerID=2235c7a429 event=exec_die subsys=workload-watcher
2018-09-12T05:38:02.182627101Z level=debug msg="Goroutine took lock for more than 0.10 seconds" goroutine=" 1663" seconds=53.927578637 subsys=lock-lib
2018-09-12T05:38:02.182647138Z goroutine 1663 [running]:
2018-09-12T05:38:02.182649689Z goroutine 1663 runtime/debug.Stack(0xbede47610f11d570, 0x21fe16a0d, 0x393c3c0)
2018-09-12T05:38:02.182651699Z goroutine 1663 	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
2018-09-12T05:38:02.182653863Z goroutine 1663 github.com/cilium/cilium/pkg/lock.(*internalMutex).Unlock(0xc42398cba0)
2018-09-12T05:38:02.182655834Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:105 +0xc6
2018-09-12T05:38:02.182657831Z goroutine 1663 github.com/cilium/cilium/pkg/completion.(*WaitGroup).Wait(0xc42398cb90, 0x29ecd80, 0x3e85a20)
2018-09-12T05:38:02.182659876Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/completion/completion.go:89 +0x25d
2018-09-12T05:38:02.182661928Z goroutine 1663 github.com/cilium/cilium/pkg/endpoint.(*Endpoint).WaitForProxyCompletions(0xc421763080, 0xc42398cb90, 0x1, 0x1)
2018-09-12T05:38:02.182663937Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:531 +0x16e
2018-09-12T05:38:02.182665937Z goroutine 1663 github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF(0xc421763080, 0x2a382a0, 0xc4214eb800, 0xc424951ac0, 0xa, 0xc423d58840, 0x0, 0x0, 0x0, 0x0)
2018-09-12T05:38:02.182667985Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:573 +0xc1e
2018-09-12T05:38:02.182670003Z goroutine 1663 github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc421763080, 0x2a382a0, 0xc4214eb800, 0xc423d58840, 0x0, 0x0)
2018-09-12T05:38:02.182672468Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:771 +0x6d1
2018-09-12T05:38:02.182674527Z goroutine 1663 github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate.func1(0xc423d58840, 0x2a382a0, 0xc4214eb800, 0xc423f47340, 0xc421763080)
2018-09-12T05:38:02.182676547Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:845 +0x1fc
2018-09-12T05:38:02.182678504Z goroutine 1663 created by github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate
2018-09-12T05:38:02.182680447Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:823 +0x123
2018-09-12T05:38:02.182682398Z level=debug msg="Goroutine took lock for more than 0.10 seconds" goroutine=" 1663" seconds=55.074056503 subsys=lock-lib
2018-09-12T05:38:02.182684615Z goroutine 1663 [running]:
2018-09-12T05:38:02.182686537Z goroutine 1663 runtime/debug.Stack(0xbede4760c6580345, 0x1db8ccde1, 0x393c3c0)
2018-09-12T05:38:02.182696504Z goroutine 1663 	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
2018-09-12T05:38:02.182699146Z goroutine 1663 github.com/cilium/cilium/pkg/lock.(*internalRWMutex).RUnlock(0xc421d74e40)
2018-09-12T05:38:02.182700928Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:84 +0xc6
2018-09-12T05:38:02.182702897Z goroutine 1663 github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF(0xc421763080, 0x2a382a0, 0xc4214eb800, 0xc424951ac0, 0xa, 0xc423d58840, 0x0, 0x1, 0x29e74e0, 0xc4245c68d0)
2018-09-12T05:38:02.182704741Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:575 +0xcbd
2018-09-12T05:38:02.1827065Z goroutine 1663 github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc421763080, 0x2a382a0, 0xc4214eb800, 0xc423d58840, 0x0, 0x0)
2018-09-12T05:38:02.182708329Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:771 +0x6d1
2018-09-12T05:38:02.182710112Z goroutine 1663 github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate.func1(0xc423d58840, 0x2a382a0, 0xc4214eb800, 0xc423f47340, 0xc421763080)
2018-09-12T05:38:02.182711878Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:845 +0x1fc
2018-09-12T05:38:02.18271357Z goroutine 1663 created by github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate
2018-09-12T05:38:02.182717624Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:823 +0x123
2018-09-12T05:38:02.182719512Z level=warning msg="generating BPF for endpoint failed, keeping stale directory." containerID=4291d5ad67 datapathPolicyRevision=0 desiredPolicyRevision=4 endpointID=54070 file-path=54070_next_fail ipv4=10.10.0.130 ipv6="f00d::a0a:0:0:d336" k8sPodName=default/app1-7c5785f7f7-d4774
2018-09-12T05:38:02.182721821Z level=debug msg="Completed endpoint regeneration with no pending regeneration requests" code=OK containerID=4291d5ad67 datapathPolicyRevision=0 desiredPolicyRevision=4 endpointID=54070 endpointState=ready ipv4=10.10.0.130 ipv6="f00d::a0a:0:0:d336" k8sPodName=default/app1-7c5785f7f7-d4774 policyRevision=0 type=0
2018-09-12T05:38:02.182724018Z level=debug msg="Goroutine took lock for more than 0.10 seconds" goroutine=" 1663" seconds=56.211521531 subsys=lock-lib
2018-09-12T05:38:02.182725893Z goroutine 1663 [running]:
2018-09-12T05:38:02.182727589Z goroutine 1663 runtime/debug.Stack(0xbede476079c31fa9, 0x197c25651, 0x393c3c0)
2018-09-12T05:38:02.18272931Z goroutine 1663 	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
2018-09-12T05:38:02.182731803Z goroutine 1663 github.com/cilium/cilium/pkg/lock.(*internalMutex).Unlock(0xc421763280)
2018-09-12T05:38:02.182733837Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/lock/lock_debug.go:105 +0xc6
2018-09-12T05:38:02.182735641Z goroutine 1663 github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc421763080, 0x2a382a0, 0xc4214eb800, 0xc423d58840, 0x29e74e0, 0xc4245c68d0)
2018-09-12T05:38:02.182737459Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:778 +0x901
2018-09-12T05:38:02.182739363Z goroutine 1663 github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate.func1(0xc423d58840, 0x2a382a0, 0xc4214eb800, 0xc423f47340, 0xc421763080)
2018-09-12T05:38:02.182743486Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:845 +0x1fc
2018-09-12T05:38:02.182745343Z goroutine 1663 created by github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate
2018-09-12T05:38:02.182747056Z goroutine 1663 	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:823 +0x123
2018-09-12T05:38:02.182748898Z level=warning msg="Regeneration of endpoint failed" bpfCompilation=1.058972167s buildDuration=56.215753051s containerID=4291d5ad67 datapathPolicyRevision=0 desiredPolicyRevision=4 endpointID=54070 error="Error while configuring proxy redirects: proxy state changes failed: context deadline exceeded" ipv4=10.10.0.130 ipv6="f00d::a0a:0:0:d336" k8sPodName=default/app1-7c5785f7f7-d4774 mapSync="48.935µs" policyCalculation="883.416µs" prepareBuild=1.630066ms proxyConfiguration=7.609811ms proxyPolicyCalculation=3.255198ms proxyWaitForAck=0s reason="syncing state to host" waitingForCTClean=0s waitingForLock=1.137175844s
2018-09-12T05:38:02.182752312Z level=debug msg="Error regenerating endpoint: Error while configuring proxy redirects: proxy state changes failed: context deadline exceeded" code=Failure containerID=4291d5ad67 datapathPolicyRevision=0 desiredPolicyRevision=4 endpointID=54070 endpointState=ready ipv4=10.10.0.130 ipv6="f00d::a0a:0:0:d336" k8sPodName=default/app1-7c5785f7f7-d4774 policyRevision=0 type=200
2018-09-12T05:38:02.182754569Z level=warning msg="Failed while regenerating endpoint" endpointID=54070 subsys=daemon
```

https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1580/testReport/junit/k8s-1/11/K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master/
[a31fe822_K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master.zip](https://github.com/cilium/cilium/files/2373884/a31fe822_K8sUpdates_Tests_upgrade_and_downgrade_from_a_Cilium_stable_image_to_master.zip)

### PR DESCRIPTION
**Pull request by rlenglet**
#5495 removed a check that was performed before allocating any TCP
port to a new proxy redirect, which tried opening and closing
the port. That check was triggering errors in Envoy when it tried
to open the allocated port too soon after the check closed the
port. 

However, removing that check exposed Envoy to legitimate port
conflicts with other processes opening ports in the same port
rannge.

Re-add a check before port allocation, implemented by listing the
currently open ports (like netstat) instead of opening and closing
the ports.

Fixes: #5532
Fixes: #5495
Signed-off-by: Romain Lenglet <romain@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5552)

### CODE REVIEW

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
test-me-please

File: pkg/proxy/netstat.go [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+// readOpenLocalTCPPorts returns the set of TCP ports currently open locally.
+func readOpenLocalTCPPorts() (map[uint16]struct{}, error) {
+	openLocalPorts := make(map[uint16]struct{}, 128)
+
+	for _, file := range procNetTCPFiles {
+		bytes, err := ioutil.ReadFile(file)
+		if err != nil {
+			return nil, fmt.Errorf("cannot read proc file %s: %s", file, err)
+		}
+		lines := strings.Split(string(bytes), "\n")
```
Comment (aanm) [inline pkg/proxy/netstat.go]: Did you consider using `bytes.Split`?

File: pkg/proxy/netstat.go [hunk 2]
```diff
@@ -0,0 +1,52 @@
+package proxy
```
Comment (aanm) [inline pkg/proxy/netstat.go:15]: Needs copywrite header

File: pkg/proxy/netstat.go [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+		// The header line won't match and will be ignored.
+		for _, line := range lines {
+			groups := procNetTCPRegexp.FindStringSubmatch(line)
+			if len(groups) != 2 { // no match
+				continue
+			}
+			// The port number is in hexadecimal.
+			localPort, err := strconv.ParseUint(groups[1], 16, 16)
+			if err != nil {
+				return nil, fmt.Errorf("invalid local port number in %s: %s", file, err)
```
Comment (aanm) [inline pkg/proxy/netstat.go]: Should we stop the allocation of a Port just because we can't read single port number? Can't we ignore the error?

**Review by aanm — CHANGES_REQUESTED** [review]

**Review by tgraf — DISMISSED** [review]
Needs a commit and PR description

File: pkg/proxy/netstat.go (hunk 2 above)
Comment (rlenglet) [reply pkg/proxy/netstat.go:15]: Done.

File: pkg/proxy/netstat.go (hunk 3 above)
Comment (rlenglet) [reply pkg/proxy/netstat.go]: On the contrary, it may be better to even `log.Fatalf()` in that case?

File: pkg/proxy/netstat.go (hunk 2 above)
Comment (ianvernon) [reply pkg/proxy/netstat.go:15]: @rlenglet I am not seeing the copyright header?

File: pkg/proxy/netstat.go [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+		"/proc/net/tcp6",
+	}
+
+	// procNetTCPRegexp matches the first two columns of /proc/net/tcp* files
+	// and submatches on the local port number.
+	procNetTCPRegexp = regexp.MustCompile("^ *[[:digit:]]*: *[[:xdigit:]]*:([[:xdigit:]]*) ")
+)
+
+// readOpenLocalTCPPorts returns the set of TCP ports currently open locally.
+func readOpenLocalTCPPorts() (map[uint16]struct{}, error) {
```
Comment (ianvernon) [inline pkg/proxy/netstat.go]: An idea - to make this unit-testable, you could add a slice of strings as a parameter to the function. In the actual code base, you could then call this with `procNetTCPFiles` as a parameter. You could then create dummy files for unit testing to ensure that this functions correctly and that we don't break the behavior in the future.

File: pkg/proxy/netstat.go [hunk 5]
```diff
@@ -0,0 +1,52 @@
...
+	openLocalPorts := make(map[uint16]struct{}, 128)
```
Comment (ianvernon) [inline pkg/proxy/netstat.go]: Any particular reason for using 128?

File: pkg/proxy/netstat.go (hunk 1 above)
Comment (rlenglet) [reply pkg/proxy/netstat.go]: Good call, that's cleaner.

File: pkg/proxy/netstat.go (hunk 5 above)
Comment (rlenglet) [reply pkg/proxy/netstat.go]: It's just very probably that the map will not be empty, so it's bad for sure to start with a map with capacity 0. I just randomly picked 128 as a random positive integer.

File: pkg/proxy/netstat.go (hunk 4 above)
Comment (rlenglet) [reply pkg/proxy/netstat.go]: Good point. This will also allow using this with UDP, since the format of the `/proc/net/udp*` files is the same. Done.

**Comment by rlenglet** [comment]
test-me-please

File: pkg/proxy/netstat.go (hunk 3 above)
Comment (aanm) [reply pkg/proxy/netstat.go]: Why? It's a single port out of many. I think `log.Fatalf` is extreme for this

Comment (rlenglet) [reply pkg/proxy/netstat.go]: This error is pretty extreme. It would mean that we parse the line OK, but the port is not in hexadecimal and/or doesn't fit in a 16-bit unsigned int.

**Review by tgraf — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by aanm** [comment]
@jrajahalme Waiting for your review
