### PR TITLE
pkg/allocator: Improve 'Key allocation attempt failed' handling for C…

### LINKED ISSUE #11487: "Key allocation attempt failed" on first attempt counted as warning
## Proposal

**General Information**

- Cilium version (run `cilium version`)
```
Client: 1.7.90 78e703c44 2020-04-22T17:41:28-07:00 go version go1.14.2 linux/amd64
Daemon: 1.7.90 78e703c44 2020-04-22T17:41:28-07:00 go version go1.14.2 linux/amd64
```

- Kernel version (run `uname -a`)
```
Linux REDACTED 5.6.5-1.el7.elrepo.x86_64 #1 SMP Thu Apr 16 14:02:22 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
```
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Link to relevant artifacts (policies, deployments scripts, ...)
None

- Upload a system dump (run `curl -sLO
https://github.com/cilium/cilium-sysdump/releases/latest/download/cilium-sysdump.zip &&
python cilium-sysdump.zip` and then attach the generated zip file)
None

**How to reproduce the issue**
1. Deploy a Job on Kubernetes that is starting Pods often
2. Observe the Cilium `cilium_errors_warnings_total` metric, which should increase
3. Have a look at the logs of Cilium Agent and you will notice similar messages of `level=warning`:
```
level=warning msg="Key allocation attempt failed" attempt=0 error="slave key creation failed 'k8s:io.cilium.k8s.policy.cluster=REDACTED;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=appl-REDACTED;k8s:spark-app-selector=spark-application-1589257336750;k8s:spark-exec-id=3;k8s:spark-role=executor;': identity does not exist" key="[k8s:io.cilium.k8s.policy.cluster=REDACTED k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=appl-REDACTED k8s:spark-app-selector=spark-application-1589257336750 k8s:spark-exec-id=3 k8s:spark-role=executor]" subsys=allocator
level=warning msg="Key allocation attempt failed" attempt=0 error="slave key creation failed 'k8s:io.cilium.k8s.policy.cluster=REDACTED;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=appl-REDACTED;k8s:spark-app-selector=spark-application-1589258897678;k8s:spark-exec-id=3;k8s:spark-role=executor;': identity does not exist" key="[k8s:io.cilium.k8s.policy.cluster=REDACTED k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=appl-REDACTED k8s:spark-app-selector=spark-application-1589258897678 k8s:spark-exec-id=3 k8s:spark-role=executor]" subsys=allocator
level=warning msg="Key allocation attempt failed" attempt=0 error="slave key creation failed 'k8s:io.cilium.k8s.policy.cluster=REDACTED;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=appl-REDACTED;k8s:spark-app-selector=spark-application-1589265176423;k8s:spark-exec-id=3;k8s:spark-role=executor;': identity does not exist" key="[k8s:io.cilium.k8s.policy.cluster=REDACTED k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=appl-REDACTED k8s:spark-app-selector=spark-application-1589265176423 k8s:spark-exec-id=3 k8s:spark-role=executor]" subsys=allocator
level=warning msg="Key allocation attempt failed" attempt=0 error="slave key creation failed 'k8s:io.cilium.k8s.policy.cluster=REDACTED;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=appl-REDACTED;k8s:spark-app-selector=spark-application-1589266270885;k8s:spark-exec-id=3;k8s:spark-role=executor;': identity does not exist" key="[k8s:io.cilium.k8s.policy.cluster=REDACTED k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=appl-REDACTED k8s:spark-app-selector=spark-application-1589266270885 k8s:spark-exec-id=3 k8s:spark-role=executor]" subsys=allocator
level=warning msg="Key allocation attempt failed" attempt=0 error="slave key creation failed 'k8s:io.cilium.k8s.policy.cluster=REDACTED;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=appl-REDACTED;k8s:spark-app-selector=spark-application-1589268972865;k8s:spark-exec-id=2;k8s:spark-role=executor;': identity does not exist" key="[k8s:io.cilium.k8s.policy.cluster=REDACTED k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=appl-REDACTED k8s:spark-app-selector=spark-application-1589268972865 k8s:spark-exec-id=2 k8s:spark-role=executor]" subsys=allocator
level=warning msg="Key allocation attempt failed" attempt=0 error="slave key creation failed 'k8s:io.cilium.k8s.policy.cluster=REDACTED;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=appl-REDACTED;k8s:spark-app-selector=spark-application-1589268972865;k8s:spark-exec-id=7;k8s:spark-role=executor;': identity does not exist" key="[k8s:io.cilium.k8s.policy.cluster=REDACTED k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=appl-REDACTED k8s:spark-app-selector=spark-application-1589268972865 k8s:spark-exec-id=7 k8s:spark-role=executor]" subsys=allocator
level=warning msg="Key allocation attempt failed" attempt=0 error="slave key creation failed 'k8s:io.cilium.k8s.policy.cluster=REDACTED;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=appl-REDACTED;k8s:spark-app-selector=spark-080aa23163a042d182f43c3eac2c51ab;k8s:spark-exec-id=3;k8s:spark-role=executor;': identity does not exist" key="[k8s:io.cilium.k8s.policy.cluster=REDACTED k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=appl-REDACTED k8s:spark-app-selector=spark-080aa23163a042d182f43c3eac2c51ab k8s:spark-exec-id=3 k8s:spark-role=executor]" subsys=allocator
level=warning msg="Key allocation attempt failed" attempt=0 error="slave key creation failed 'k8s:io.cilium.k8s.policy.cluster=REDACTED;k8s:io.cilium.k8s.policy.serviceaccount=default;k8s:io.kubernetes.pod.namespace=appl-REDACTED;k8s:spark-app-selector=spark-ce6ecaf9fbbc42cc9eb5b9541f795b6d;k8s:spark-exec-id=3;k8s:spark-role=executor;': identity does not exist" key="[k8s:io.cilium.k8s.policy.cluster=REDACTED k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=appl-REDACTED k8s:spark-app-selector=spark-ce6ecaf9fbbc42cc9eb5b9541f795b6d k8s:spark-exec-id=3 k8s:spark-role=executor]" subsys=allocator
```

**Impact**
The warning count metric is increased depending on the frequency how often pods are being deployed. This makes alerting on that metric more difficult

**Expected behaviour**
If the `Key allocation attempt failed` fails on `attempt=0`, the logged message should be at level `info`. If the attempt value is higher, it should be kept at `warning`.

**Question**
If you have also the same expectations about the behaviour, I will create a PR for an according condition around https://github.com/cilium/cilium/blob/8b609abe6c9f7927ffaa3eeffd18736815330f11/pkg/allocator/allocator.go#L637

### PR DESCRIPTION
**Pull request by aanm**
…RD mode

In CRD mode, the Cilium agent uses CRD to create identities. After an identity is created, the agent acquires a reference for that key. This involves fetching the CRD from the local Kubernetes cache and checking for an annotation applied by cilium-operator to mark the identity for deletion. However, there may be a delay before the Cilium Identity is cached locally, leading to the 'Key allocation attempt failed' error. This patch ensures that we fallback to the newly allocated Cilium Identity if it's not found in the Kubernetes cache.

```release-note
Fix false positives of 'Key allocation attempt failed' in CRD mode
```

Fixes https://github.com/cilium/cilium/issues/11487

### CODE REVIEW

File: pkg/k8s/identitybackend/identity.go [hunk 1]
```diff
@@ -100,11 +101,14 @@ func (c *crdBackend) AllocateID(ctx context.Context, id idpool.ID, key allocator
 		SecurityLabels: key.GetAsMap(),
 	}
 
-	_, err := c.Client.CiliumV2().CiliumIdentities().Create(ctx, identity, metav1.CreateOptions{})
-	return err
+	ci, err := c.Client.CiliumV2().CiliumIdentities().Create(ctx, identity, metav1.CreateOptions{})
+	if err != nil {
+		return nil, err
+	}
+	return key.PutBackendKey(ci), nil
```
Comment (giorio94) [inline pkg/k8s/identitybackend/identity.go]: Instead of storing the entire CiliumIdentities object, it should be sufficient to have a Created flag (or something similar) only. If the identity has just been created, then it is expected that it should not have been marked for deletion by the operator (the annotation would not be present in that case). 

Optionally, if useful, PutBackendKey could also be something like PutMeta (of WithValue), which allows to store arbitrary key/value pairs like in the case of contexts.

File: pkg/allocator/allocator.go [hunk 2]
```diff
@@ -202,11 +202,15 @@ type Backend interface {
 	// error in that case is not expected to be fatal. The actual ID is obtained
 	// by Allocator from the local idPool, which is updated with used-IDs as the
 	// Backend makes calls to the handler in ListAndWatch.
-	AllocateID(ctx context.Context, id idpool.ID, key AllocatorKey) error
+	// The implementation of the backend might return an AllocatorKey that is
+	// a copy of 'key' with an internal reference of the backend key.
```
Comment (giorio94) [inline pkg/allocator/allocator.go]: I'd suggest to slightly rephrase this comment, as I personally read it as "sometimes the AllocatorKey might be nil". Instead, IIUC, it is only the `BackendKey` which might not be set (unless a non-nil error is returned, which is expected).

Comment (aanm) [reply pkg/allocator/allocator.go]: I've changed it slightly to the following:
```
	// The implementation of the backend might return an AllocatorKey that is
	// a copy of 'key' with an internal reference of the backend key or, if it
	// doesn't use the internal reference of the backend key it suply returns
	// 'key'. In case of an error the returned 'AllocatorKey' should be nil.
```

File: pkg/allocator/allocator.go [hunk 3]
```diff
@@ -202,11 +202,17 @@ type Backend interface {
 	// error in that case is not expected to be fatal. The actual ID is obtained
 	// by Allocator from the local idPool, which is updated with used-IDs as the
 	// Backend makes calls to the handler in ListAndWatch.
-	AllocateID(ctx context.Context, id idpool.ID, key AllocatorKey) error
+	// The implementation of the backend might return an AllocatorKey that is
+	// a copy of 'key' with an internal reference of the backend key or, if it
+	// doesn't use the internal reference of the backend key it suply returns
```
Comment (giorio94) [inline pkg/allocator/allocator.go]: Nit. s/suply/simply/

File: pkg/allocator/allocator.go [hunk 4]
```diff
@@ -202,11 +202,17 @@ type Backend interface {
...
+	// 'key'. In case of an error the returned 'AllocatorKey' should be nil.
+	AllocateID(ctx context.Context, id idpool.ID, key AllocatorKey) (AllocatorKey, error)
 
 	// AllocateIDIfLocked behaves like AllocateID but when lock is non-nil the
 	// operation proceeds only if it is still valid.
-	AllocateIDIfLocked(ctx context.Context, id idpool.ID, key AllocatorKey, lock kvstore.KVLocker) error
+	// The implementation of the backend might return an AllocatorKey that is
+	// a copy of 'key' with an internal reference of the backend key.
```
Comment (giorio94) [inline pkg/allocator/allocator.go]: Same here about the extended comment about the possible return value.

File: pkg/k8s/identitybackend/identity.go [hunk 5]
```diff
@@ -136,7 +141,12 @@ func (c *crdBackend) AcquireReference(ctx context.Context, id idpool.ID, key all
 		return err
 	}
 	if !exists {
-		return fmt.Errorf("identity (id:%q,key:%q) does not exist", id, key)
+		// fall back to the key stored in the allocator key. If it's not present
+		// they return the error.
```
Comment (giorio94) [inline pkg/k8s/identitybackend/identity.go]: Nit. s/they/then/

File: pkg/identity/key/global_identity.go [hunk 6]
```diff
@@ -32,13 +40,34 @@ func (gi *GlobalIdentity) GetAsMap() map[string]string {
...
+
+// PutValue puts metadata inside the global identity for the given 'key' with
+// the given 'value'.
+func (gi *GlobalIdentity) PutValue(key, value any) allocator.AllocatorKey {
+	newMap := map[any]any{}
+	if gi.metadata != nil {
+		for k, v := range gi.metadata {
+			newMap[k] = v
+		}
+	}
```
Comment (giorio94) [inline pkg/identity/key/global_identity.go]: Nit. Could likely use `maps.Clone()` or `maps.Copy()`

**Review by giorio94 — COMMENTED** [review]
A couple of nits inline.

About _"Instead of storing the entire CiliumIdentities object, it should be sufficient to have a Created flag (or something similar) only."_, do you think it could be make sense or not being worthy?

File: pkg/identity/key/global_identity.go (hunk 6 above)
Comment (aanm) [reply pkg/identity/key/global_identity.go]: TIL

**Comment by aanm** [comment]
> About _"Instead of storing the entire CiliumIdentities object, it should be sufficient to have a Created flag (or something similar) only."_, do you think it could be make sense or not being worthy?

Idk TBH, the "created" flag doesn't provide the state which is also what I was going for. Have in mind that although it's storing the entire CI object, that Key will be GC since it's only used [here](https://github.com/cilium/cilium/blob/ee9ce2cb4e85bdd0ff0b2fc9da8a7ee165bd1378/pkg/allocator/allocator.go#L597-L608).

**Comment by giorio94** [comment]
> Idk TBH, the "created" flag doesn't provide the state which is also what I was going for. Have in mind that although it's storing the entire CI object, that Key will be GC since it's only used [here](https://github.com/cilium/cilium/blob/ee9ce2cb4e85bdd0ff0b2fc9da8a7ee165bd1378/pkg/allocator/allocator.go#L597-L608).

Yeah, I saw that it is currently not stored anywhere. I was just a bit concerned that at a certain point we start storing it for other reasons, and we end up with bloated objects. Mostly curiosity though, makes sense as approach to me given the current structure.

**Review by giorio94 — APPROVED** [review]

**Review by joamaki — APPROVED** [review]

**Review by sayboras — APPROVED** [review]
Thanks ✅

**Review by nathanjsweet — APPROVED** [review]
