### PR TITLE
test: Fix artifact collection for FQDN matchPattern test

### LINKED ISSUE #16753: Missing artifact for RuntimeFQDNPolicies Implements matchPattern: "*"
See for example https://jenkins.cilium.io/job/cilium-master-runtime-kernel-4.9/2247/testReport/junit/(root)/Suite-runtime/RuntimeFQDNPolicies_Implements_matchPattern_____/. The logs have:
```
17:38:25  Recording test results
17:38:26  Attachment ad391c17_RuntimeFQDNPolicies_Implements_matchPattern:_"*".zip was referenced from the test 'Suite-runtime' but it doesn't exist. Skipping.
```
Note the artifact is there but just not linked to the test and therefore not presented in the WebUI page specific to the test.

This is probably due to the asterisk. I'll send a fix later today.

### LINKED ISSUE #16754: Bugtool report missing in RuntimeFQDNPolicies Implements matchPattern: "*"
See https://jenkins.cilium.io/job/cilium-master-runtime-kernel-4.9/2247/ and it's artifact 
[ad391c17_RuntimeFQDNPolicies_Implements_matchPattern _ .zip](https://github.com/cilium/cilium/files/6752652/ad391c17_RuntimeFQDNPolicies_Implements_matchPattern._.zip)

In the logs, we can find:
```
time="2021-06-29T17:32:12Z" level=debug msg="running command: sudo cilium-bugtool -t /home/vagrant/go/src/github.com/cilium/cilium/test/test_results/RuntimeFQDNPolicies_Implements_matchPattern:_\"*\""
cmd: "sudo cilium-bugtool -t /home/vagrant/go/src/github.com/cilium/cilium/test/test_results/RuntimeFQDNPolicies_Implements_matchPattern:_\"*\"" exitCode: 1 duration: 9.750824ms
time="2021-06-29T17:32:12Z" level=error msg="Error running bugtool: Failed to create debug directory stat /home/vagrant/go/src/github.com/cilium/cilium/test/test_results/RuntimeFQDNPolicies_Implements_matchPattern:_*: no such file or directory\n"
time="2021-06-29T17:32:12Z" level=error msg="Error running bugtool: Failed to create debug directory stat /home/vagrant/go/src/github.com/cilium/cilium/test/test_results/RuntimeFQDNPolicies_Implements_matchPattern:_*: no such file or directory\n"
```

This is probably due to the asterisk. I'll send a fix later today.

### PR DESCRIPTION
**Pull request by pchaigno**
This pull request fixes a couple artifact collection bugs. See the commits for details.

It was tested with a purposely-broken test at https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/5208/testReport/junit/(root)/Suite-runtime/RuntimeFQDNPolicies_Implements_matchPattern___/. You can see the artifact there and it also has the bugtool report. To be compared to the broken artifact collection at https://jenkins.cilium.io/job/cilium-master-runtime-kernel-4.9/2247/testReport/junit/(root)/Suite-runtime/RuntimeFQDNPolicies_Implements_matchPattern_____/.

Fixes: https://github.com/cilium/cilium/issues/16753.
Fixes: https://github.com/cilium/cilium/issues/16754.

### CODE REVIEW

**Comment by pchaigno** [comment]
test-runtime

File: test/helpers/cilium.go [hunk 1]
```diff
@@ -732,7 +732,7 @@ func (s *SSHMeta) DumpCiliumCommandOutput() {
 	// No need to create file for bugtool because it creates an archive of files
 	// for us.
 	res := s.ExecWithSudo(
-		fmt.Sprintf("%s -t %s", CiliumBugtool, filepath.Join(s.basePath, testPath)),
+		fmt.Sprintf("%s -t \"%s\"", CiliumBugtool, filepath.Join(s.basePath, testPath)),
```
Comment (twpayne) [inline test/helpers/cilium.go]: Maybe use `%q` instead.

**Review by twpayne — APPROVED** [review]

File: test/helpers/cilium.go (hunk 1 above)
Comment (pchaigno) [reply test/helpers/cilium.go]: Thanks! Fixed and tested locally that it also works.

**Review by nebril — APPROVED** [review]

**Comment by pchaigno** [comment]
test-runtime

**Comment by pchaigno** [comment]
test-runtime

**Comment by pchaigno** [comment]
I don't think we need the @cilium/proxy review here. Other team reviews are covered and tests are passing. Merging.

**Comment by pchaigno** [comment]
Marking for backports as it can significantly help flake debugging.
