### PR TITLE
Fixes for ip-masq-agent

### LINKED ISSUE #26262: ip-masq-agent broken for IPv4-only
### What happened?

@gandro reports that, after https://github.com/cilium/cilium/pull/23219, he tested the ip-masq-agent in an IPv4-only cluster and observes the following error:

```
Controller Status:      21/22 healthy
  Name                            Last success   Last error   Count   Message
  bpf-map-sync-cilium_ipmasq_v6   never          9s ago       12      loading pinned map /sys/fs/bpf/tc/globals/cilium_ipmasq_v6: no such file or directory   
```

Adding that the ip-masq-agent seems broken, with the IPv4 map not containing any CIDRs anymore.

To be investigated as soon as possible - Worst case, we'll need to revert IPv6 ip-masq-agent before we cut 1.14.

### Cilium Version

`main` branch, on top of https://github.com/cilium/cilium/pull/23219

### PR DESCRIPTION
**Pull request by qmonnet**
It looks like I didn't test the ip-masq-agent quite enough when adding support for IPv6 - in particular, I didn't test with IPv4 only. Sebastian reported that when IPv6 is off, ip-masq-agent is broken. This PR contains a number of fixes to address that.

Fixes: #26262

```release-note
Fix some map handling logic as well as some issues with CLI commands related to ip-masq-agent, introduced with IPv6 support
```

### CODE REVIEW

File: test/k8s/datapath_configuration.go [hunk 1]
```diff
@@ -361,6 +361,18 @@ var _ = Describe("K8sDatapathConfig", func() {
 			testIPMasqAgent()
 		})
 
+		It("DirectRouting, IPv4 only", func() {
```
Comment (brb) [inline test/k8s/datapath_configuration.go:364]: JFYI, we want to move this to CLI connectivity test in v1.15.

**Review by brb — APPROVED** [review]

File: test/k8s/datapath_configuration.go (hunk 1 above)
Comment (qmonnet) [reply test/k8s/datapath_configuration.go:364]: OK thanks, this shouldn't be an issue I think? Or do you have an alternative to suggest?

**Review by bimmlerd — APPROVED** [review]
contributing lgtm

**Review by learnitall — APPROVED** [review]
LGTM on changes in examples/

**Review by christarazi — APPROVED** [review]
LGTM for ci-structure. It would be good to have a tracking issue for migrating the test out of Ginkgo.

**Comment by qmonnet** [comment]
Ok, I added an item to https://github.com/cilium/cilium/issues/26074. Where would be the best location for this test? Basically I want to make sure that Cilium deploys well with the ip-masq-agent on IPv4 only (and that we don't reintroduce this IPv6-map-related warning that would make it unhealthy) and that the feature works as expected. Would connectivity tests be the way to go (as a follow-up)?

File: test/k8s/datapath_configuration.go (hunk 1 above)
Comment (brb) [reply test/k8s/datapath_configuration.go:364]: For this PR it's not an issue. I'm expecting the move to happen early in the v1.15 dev cycle.

File: pkg/datapath/maps/map.go [hunk 2]
```diff
@@ -204,13 +204,12 @@ func (ms *MapSweeper) RemoveDisabledMaps() {
...
 	}
 
-	if !option.Config.EnableIPMasqAgent {
-		if option.Config.EnableIPv4 {
-			maps = append(maps, ipmasq.MapNameIPv4)
-		}
-		if option.Config.EnableIPv6 {
-			maps = append(maps, ipmasq.MapNameIPv6)
-		}
+	if !option.Config.EnableIPMasqAgent || !option.Config.EnableIPv4Masquerade {
```
Comment (lmb) [inline pkg/datapath/maps/map.go]: Nit: took me a bit to parse this. Maybe `!(EnableIPMasqAgent && EnableIPv4Masquerade)` is easier?

File: cilium/cmd/bpf_ipmasq_list.go [hunk 3]
```diff
@@ -26,7 +26,7 @@ var bpfIPMasqListCmd = &cobra.Command{
 	Run: func(cmd *cobra.Command, args []string) {
 		common.RequireRootPrivilege("cilium bpf ipmasq list")
 
-		cidrs, err := (&ipmasq.IPMasqBPFMap{}).Dump()
+		cidrs, err := (&ipmasq.IPMasqBPFMap{}).DumpForProtocols(getMasqueradingProtocols())
```
Comment (lmb) [inline cilium/cmd/bpf_ipmasq_list.go]: `getMasqueradingProtocols` seems like a pretty big hammer to me. Could you instead call `IPMasq6Map` and `IPMasq4Map` (ignoring any "file doesn't exist" error) before `Dump()`?

**Review by gandro — APPROVED** [review]
Looks good to me, thanks for fixing this!

File: cilium/cmd/bpf_ipmasq_list.go (hunk 3 above)
Comment (qmonnet) [reply cilium/cmd/bpf_ipmasq_list.go]: As discussed offline -- This won't work, because we're trying to `Open()` the map in `DumpWithCallback()`, so if we initialise `ipmasq.ipMasq6Map` by calling `ipmasq.IPMasq6Map()` in the CLI, we get an error:

```console
root@kind-worker:/home/cilium# cilium bpf ipmasq list
error dumping contents of map: loading pinned map /sys/fs/bpf/tc/globals/cilium_ipmasq_v6: no such file or directory
```

I'll follow your alternate suggestion instead, using the result of `ipv4Needed := ipmasq.IPMasq4Map().Open() == nil` (and v6) to check whether the maps are open and get the booleans to pass to `DumpForProtocols()`, instead of going for the API request.

Thanks for the review!

**Review by lmb — APPROVED** [review]

File: daemon/cmd/datapath.go [hunk 4]
```diff
@@ -414,12 +414,12 @@ func (d *Daemon) initMaps() error {
 		datapathIpcache.NewListener(d, d, d.ipcache),
 	})
 
-	if option.Config.EnableIPv4 && option.Config.EnableIPMasqAgent {
+	if option.Config.EnableIPv4Masquerade && option.Config.EnableIPMasqAgent {
```
Comment (derailed) [inline daemon/cmd/datapath.go]: We could refactor this a bit here as both checks only happen if EnableIPMasqAgent is set.

File: pkg/datapath/maps/map.go [hunk 5]
```diff
@@ -204,13 +204,12 @@ func (ms *MapSweeper) RemoveDisabledMaps() {
...
 	}
 
-	if !option.Config.EnableIPMasqAgent {
-		if option.Config.EnableIPv4 {
-			maps = append(maps, ipmasq.MapNameIPv4)
-		}
-		if option.Config.EnableIPv6 {
-			maps = append(maps, ipmasq.MapNameIPv6)
-		}
+	if !(option.Config.EnableIPMasqAgent && option.Config.EnableIPv4Masquerade) {
```
Comment (derailed) [inline pkg/datapath/maps/map.go:207]: Same here don't need to recheck EnableIPMasqAgent is not set.

File: pkg/maps/ipmasq/ipmasq.go [hunk 6]
```diff
@@ -86,32 +86,42 @@ type IPMasqBPFMap struct{}
 
 func (*IPMasqBPFMap) Update(cidr net.IPNet) error {
 	if ip.IsIPv4(cidr.IP) {
```
Comment (derailed) [inline pkg/maps/ipmasq/ipmasq.go:88]: Could combine the if and the one below and return if ipv4 is enable. No need for else clause

File: pkg/maps/ipmasq/ipmasq.go [hunk 7]
```diff
@@ -86,32 +86,42 @@ type IPMasqBPFMap struct{}
...
+			return IPMasq6Map().Update(keyIPv6(cidr), &Value{})
+		}
 	}
+	return nil
 }
 
 func (*IPMasqBPFMap) Delete(cidr net.IPNet) error {
 	if ip.IsIPv4(cidr.IP) {
-		return IPMasq4Map().Delete(keyIPv4(cidr))
+		if option.Config.EnableIPv4Masquerade {
```
Comment (derailed) [inline pkg/maps/ipmasq/ipmasq.go:102]: Same here.

File: pkg/maps/ipmasq/ipmasq.go [hunk 8]
```diff
@@ -86,32 +86,42 @@ type IPMasqBPFMap struct{}
...
+		if option.Config.EnableIPv6Masquerade {
+			return IPMasq6Map().Delete(keyIPv6(cidr))
+		}
 	}
+	return nil
 }
 
-func (*IPMasqBPFMap) Dump() ([]net.IPNet, error) {
+func (*IPMasqBPFMap) DumpForProtocols(ipv4Needed, ipv6Needed bool) ([]net.IPNet, error) {
 	cidrs := []net.IPNet{}
```
Comment (derailed) [inline pkg/maps/ipmasq/ipmasq.go:120]: nit: Prefer var cidrs []net.IPNet{} or pre-allocate if known size to ease up on GC

File: pkg/maps/ipmasq/ipmasq.go [hunk 9]
```diff
@@ -121,6 +131,10 @@ func (*IPMasqBPFMap) Dump() ([]net.IPNet, error) {
 	return cidrs, nil
 }
 
+func (*IPMasqBPFMap) Dump() ([]net.IPNet, error) {
```
Comment (derailed) [inline pkg/maps/ipmasq/ipmasq.go:142]: Still used? Also no comment on exported method. 

Perhaps a larger discussion here but this sounds like prime candidates for generics. 
There is very little use for this type as shown below as since this is just a `marker` type that just keep checking what kind of ips are at play and whether the correct matching configs are set. 
> Note: in this case we need an instance that is passed in on the fly.

File: pkg/maps/ipmasq/ipmasq.go [hunk 10]
```diff
@@ -86,32 +86,42 @@ type IPMasqBPFMap struct{}
...
 func (*IPMasqBPFMap) Update(cidr net.IPNet) error {
 	if ip.IsIPv4(cidr.IP) {
-		return IPMasq4Map().Update(keyIPv4(cidr), &Value{})
+		if option.Config.EnableIPv4Masquerade {
+			return IPMasq4Map().Update(keyIPv4(cidr), &Value{})
+		}
 	} else {
-		return IPMasq6Map().Update(keyIPv6(cidr), &Value{})
+		if option.Config.EnableIPv6Masquerade {
+			return IPMasq6Map().Update(keyIPv6(cidr), &Value{})
```
Comment (derailed) [inline pkg/maps/ipmasq/ipmasq.go:94]: Same here

File: pkg/maps/ipmasq/ipmasq.go [hunk 11]
```diff
@@ -86,32 +86,42 @@ type IPMasqBPFMap struct{}
 
 func (*IPMasqBPFMap) Update(cidr net.IPNet) error {
 	if ip.IsIPv4(cidr.IP) {
-		return IPMasq4Map().Update(keyIPv4(cidr), &Value{})
+		if option.Config.EnableIPv4Masquerade {
+			return IPMasq4Map().Update(keyIPv4(cidr), &Value{})
```
Comment (derailed) [inline pkg/maps/ipmasq/ipmasq.go:90]: We should be using the Value() constructor.

**Review by derailed — CHANGES_REQUESTED** [review]
@qmonnet Nice work! Just a few picks...

File: pkg/datapath/maps/map.go (hunk 5 above)
Comment (qmonnet) [reply pkg/datapath/maps/map.go:207]: Are you sure about this one? I don't think I can group both IPv4 and IPv6 options under `if !option.Config.EnableIPMasqAgent {` here, the condition wouldn't be the same. I want to append the map if either `EnableIPMasqAgent` or `EnableIPv4Masquerade` is unset.

File: pkg/maps/ipmasq/ipmasq.go (hunk 6 above)
Comment (qmonnet) [reply pkg/maps/ipmasq/ipmasq.go:88]: Couldn't?

I understand you mean the following:

```go
	if ip.IsIPv4(cidr.IP) && option.Config.EnableIPv4Masquerade {
		return IPMasq4Map().Update(keyIPv4(cidr), &Value{})
	}
	if option.Config.EnableIPv6Masquerade {
		return IPMasq6Map().Update(keyIPv6(cidr), &Value{})
	}
	return nil
```

What if the CIDR is IPv4, `EnableIPv4Masquerade` is not set, but `EnableIPv6Masquerade` is set? In this case, without the `else`, we would attempt to add the CIDR to the IPv6 map, instead of skipping the entry.

Or did I get you wrong?

File: pkg/maps/ipmasq/ipmasq.go (hunk 9 above)
Comment (qmonnet) [reply pkg/maps/ipmasq/ipmasq.go:142]: Still used, in the agent. The method didn't have a comment so far and I didn't think of adding one; but I can do, for both.

As for the generics, it makes sense, but have we been using them so far in the code base? This PR is a set of fixes, I'd as well avoid moving things too much or introducing generics in here.

File: pkg/maps/ipmasq/ipmasq.go (hunk 8 above)
Comment (qmonnet) [reply pkg/maps/ipmasq/ipmasq.go:120]: OK but we don't know the size here, this depends on contents of the maps. The maps themselves have a fixed size at the moment and I could allocate for the maximal size, but that wouldn't be efficient in terms of memory usage. Do you think it's worth it?

File: pkg/maps/ipmasq/ipmasq.go (hunk 9 above)
Comment (derailed) [reply pkg/maps/ipmasq/ipmasq.go:142]: Totally Quentin, I understand. Just a quick note, for potential refacs at some other time.

File: pkg/maps/ipmasq/ipmasq.go (hunk 8 above)
Comment (derailed) [reply pkg/maps/ipmasq/ipmasq.go:120]: Thanks Quentin! I see what your are saying. You would know best here is there is something we could use based on the expected/average number of cidrs coming back.  Then this would avoid some GC churn. But this is an optimization and I understand you're trying to push thru bugs so feel free to disregard if not a good time to do so.

File: pkg/maps/ipmasq/ipmasq.go (hunk 6 above)
Comment (derailed) [reply pkg/maps/ipmasq/ipmasq.go:88]: Rats! I see what you are saying. You are totally correct!

File: pkg/maps/ipmasq/ipmasq.go (hunk 8 above)
Comment (qmonnet) [reply pkg/maps/ipmasq/ipmasq.go:120]: OK thank you! The only value we could use is the max size for the map, otherwise we'll get partial dumps if users ever fill their maps. Now I've got very little idea of whether the trade-off between GC churn and memory consumption would be interesting if we did so. As you say, I'll consider it beyond the scope of the PR and will leave it for another day. But thanks!

File: pkg/datapath/maps/map.go (hunk 5 above)
Comment (derailed) [reply pkg/datapath/maps/map.go:207]: I was thinking something along this line.

```go
  if !option.Config.EnableIPMaskAgent {
      switch {
      case !...EnableIPV4...:
      case !...EnableIPV6...:
      }
    }
```

Comment (qmonnet) [reply pkg/datapath/maps/map.go:207]: But we also want to append the map if `option.Config.EnableIPv4Masquerade` is unset, _but_ `option.Config.EnableIPMaskAgent` is set. But with your suggestion we'll never reach the `switch` in that case?

[EDIT: Based on this comment, I left this check unchanged in the last revision.]

File: pkg/maps/ipmasq/ipmasq.go (hunk 7 above)
Comment (qmonnet) [reply pkg/maps/ipmasq/ipmasq.go:102]: Let's keep the `else`, same as above, as per the other discussion

**Comment by qmonnet** [comment]
I addressed the feedback from Fernand - I factored a check in `daemon/cmd/datapath.go`, and added comments for the two exported `Dump*()` functions - and rebased.

File: pkg/datapath/maps/map.go (hunk 5 above)
Comment (derailed) [reply pkg/datapath/maps/map.go:207]: Ah makes sense.  Tx Quentin!

**Review by derailed — APPROVED** [review]
@qmonnet LGTM. Thank you for the updates!

**Comment by qmonnet** [comment]
All codeowners are covered by reviews, and CI is green. Let's get these fixes merged
