### PR TITLE
Node: Try to prioritize the InternalIPv[46] from restore.

### LINKED ISSUE #7637: CI: runtime.RuntimeFQDNPolicies Enforces ToFQDNs policy
```
Top 2 errors/warnings:
Failed to re-allocate IP of endpoint. Not restoring endpoint.
Detected allocation CIDR change to 10.1.0.0/16, previous router IP 10.15.0.1
```

```
Expected command: docker exec -i  app1 curl -s  -D /dev/stderr --output /dev/stderr -w '%{http_code}' --connect-timeout 5 http://world1.cilium.test 
```

### PR DESCRIPTION
**Pull request by eloycoto**
On case of Cilium restore can choose different Node CIDR, and the
endpoints will no restore correctly due to the IP CIDR mismatch.

This change will list all IPS, and if the IP that it is on
`node_config.h` is present in the list of the IPs will be selected, in
case that it is not present (new installation) will list all the address
with the RT_SCOPE_UNIVERSE  and sort that to try to return always the
same results.

Fix #7637

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7690)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

File: pkg/node/node_address_linux.go [hunk 1]
```diff
@@ -42,15 +44,33 @@ func firstGlobalV4Addr(intf string) (net.IP, error) {
 		return nil, err
 	}
 
+	wishIP := GetInternalIPv4()
```
Comment (raybejjani) [inline pkg/node/node_address_linux.go]: I'm not sure that using the global value is the safest choice. It means that this is sensitive to the order of operations before calling this function. It would be clearer if we passed in `preferredIPv4` and `preferredIPv6`. This might mean propagating that value up the call-tree a little bit more but it will be clear when in time the IP value was taken to be used here.

**Comment by eloycoto** [comment]
test-me-please

**Comment by eloycoto** [comment]
test-me-please

File: pkg/node/node_address_linux.go [hunk 2]
```diff
@@ -17,23 +17,27 @@
...
 
 	"golang.org/x/sys/unix"
 
 	"github.com/vishvananda/netlink"
 )
 
-func firstGlobalV4Addr(intf string) (net.IP, error) {
+// firstGlobalV4Addr  returns the first IP address for the given interface, if
+// the wishIP is send it'll return the wishIP if is in the list of address.
+func firstGlobalV4Addr(intf string, wishIP net.IP) (net.IP, error) {
```
Comment (raybejjani) [inline pkg/node/node_address_linux.go]: Can we switch `wishIP` to `preferredIP`? I realise that wishIP makes sense but it's a little ambiguous because it might mean we're allocating that IP (maybe it's clear... shrug)

**Review by tgraf — APPROVED** [review]

File: pkg/node/node_address_linux.go (hunk 2 above)
Comment (raybejjani) [inline pkg/node/node_address_linux.go]: It's in the name but the comment might be a little more clear with
```
firstGlobalV4Addr returns the first IPv4 global IP of an interface, where the IPs are sorted in ascending order. when intf is defined only IPs belonging to that interface are considered. If wishIP is present in the IP list it is returned irrespective of the sort order. Passing intf and wishIP will only return wishIP if it is in the IPs that belong to intf. In all cases, if intf is not found all interfaces are considered.
```
(something similar will apply to the v6 one below)

**Review by raybejjani — CHANGES_REQUESTED** [review]

**Comment by eloycoto** [comment]
test-me-please

**Review by raybejjani — APPROVED** [review]
