### PR TITLE
operator: remove pod list of an entire cluster

### LINKED ISSUE #11472: operator: identityHeartbeat is nil in k8s_cep_gc.go
## Bug report

**General Information**

- Cilium version (run `cilium version`) - current master
- Kernel version (run `uname -a`) - `Linux k8s1 4.9.212-0409212-generic #202001300045 SMP Thu Jan 30 00:48:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...) - vagrant dev VM
- Link to relevant artifacts (policies, deployments scripts, ...)
- Upload a system dump (run `curl -sLO
https://github.com/cilium/cilium-sysdump/releases/latest/download/cilium-sysdump.zip &&
python cilium-sysdump.zip` and then attach the generated zip file)

**How to reproduce the issue**

1. Set up the Vagrant development VM - `K8S=1 ./contrib/vagrant/start.sh`
2. Observe the following error occuring many times (after each time, operator gets restarted) in `journalctl -u cilium-operator`:

```
May 11 14:51:05 k8s1 cilium-operator[8153]: level=debug msg="Marking identity alive" identity=104 subsys=identity-heartbeat
May 11 14:51:05 k8s1 cilium-operator[8153]: panic: runtime error: invalid memory address or nil pointer dereference
May 11 14:51:05 k8s1 cilium-operator[8153]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x18f8e10]
May 11 14:51:05 k8s1 cilium-operator[8153]: goroutine 174 [running]:
May 11 14:51:05 k8s1 cilium-operator[8153]: github.com/cilium/cilium/operator/identity.(*IdentityHeartbeatStore).MarkAlive(0x0, 0xc00082a750, 0x3, 0xbfa67776308d0bd0, 0xa91ec13, 0x302fd00)
May 11 14:51:05 k8s1 cilium-operator[8153]:         /home/vagrant/go/src/github.com/cilium/cilium/operator/identity/heartbeat.go:50 +0x170
May 11 14:51:05 k8s1 cilium-operator[8153]: main.enableCiliumEndpointSyncGC.func1(0x20b02a0, 0xc0001bd740, 0x302fd00, 0x0)
May 11 14:51:05 k8s1 cilium-operator[8153]:         /home/vagrant/go/src/github.com/cilium/cilium/operator/k8s_cep_gc.go:102 +0xbce
May 11 14:51:05 k8s1 cilium-operator[8153]: github.com/cilium/cilium/pkg/controller.(*Controller).runController(0xc00071ce00)
May 11 14:51:05 k8s1 cilium-operator[8153]:         /home/vagrant/go/src/github.com/cilium/cilium/pkg/controller/controller.go:205 +0xa2a
May 11 14:51:05 k8s1 cilium-operator[8153]: created by github.com/cilium/cilium/pkg/controller.(*Manager).updateController
May 11 14:51:05 k8s1 cilium-operator[8153]:         /home/vagrant/go/src/github.com/cilium/cilium/pkg/controller/manager.go:120 +0xb09
May 11 14:51:05 k8s1 systemd[1]: cilium-operator.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 11 14:51:05 k8s1 systemd[1]: cilium-operator.service: Failed with result 'exit-code'.
May 11 14:51:05 k8s1 systemd[1]: cilium-operator.service: Service hold-off time over, scheduling restart.
May 11 14:51:05 k8s1 systemd[1]: cilium-operator.service: Scheduled restart job, restart counter is at 7.
May 11 14:51:05 k8s1 systemd[1]: Stopped cilium operator.
May 11 14:51:05 k8s1 systemd[1]: cilium-operator.service: Start request repeated too quickly.
May 11 14:51:05 k8s1 systemd[1]: cilium-operator.service: Failed with result 'exit-code'.
May 11 14:51:05 k8s1 systemd[1]: Failed to start cilium operator.
```

### PR DESCRIPTION
**Pull request by aanm**
Doing a pod list every 30 minutes can be brutal for kube-apiserver, specially if it is not running with a limit of the number of pods that should be returned. Having a watcher that receives notifications for the pods running as well as the CEPs, is enough to provide a GC for Cilium Identities and CEPs.
    
Since we have a k8s watcher and the CEPs have an owner set to themselves the CEP GC interval was decreased to 5 minutes.
    
Also, given that we don't depend on the CEP GC to perform Cilium IdentityGC we can set the identity heartbeat timeout to 2* the KVStore Lease TTL.

Signed-off-by: André Martins <andre@cilium.io>

Fixes https://github.com/cilium/cilium/issues/11472

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by nebril — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

File: operator/k8s_cep_gc.go [hunk 1]
```diff
@@ -51,81 +47,48 @@ func enableCiliumEndpointSyncGC() {
...
+					_, exists, err := watchers.PodStore.GetByKey(cepFullName)
+					if err != nil {
+						scopedLog.WithError(err).Warn("Unable to get pod from store")
+						continue
 					}
-					if ceps.Continue != "" {
-						// there is more data, continue
-						continue perCEPFetch
+					if !exists {
+						// FIXME: this is fragile has we might have received the
```
Comment (errordeveloper) [inline operator/k8s_cep_gc.go]: there are a few typos in this comment...

File: operator/watchers/cilium_endpoint.go [hunk 2]
```diff
@@ -0,0 +1,128 @@
...
+package watchers
+
+import (
+	"errors"
+	"fmt"
+	"reflect"
+	"strconv"
+
+	cilium_v2 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2"
+	ciliumv2 "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/cilium.io/v2"
```
Comment (errordeveloper) [inline operator/watchers/cilium_endpoint.go]: Is this the current convention? I find the two import names too similar and wouldn't be able to tell which one is which without referring back to the these lines.

File: operator/watchers/cilium_endpoint.go [hunk 3]
```diff
@@ -0,0 +1,128 @@
...
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	"k8s.io/apimachinery/pkg/fields"
+	"k8s.io/apimachinery/pkg/util/wait"
+	"k8s.io/client-go/tools/cache"
+)
+
+const identityIndex = "identity"
+
+var (
+	errNoCE  = errors.New("object has is not a *cilium_v2.CiliumEndpoint meta")
```
Comment (errordeveloper) [inline operator/watchers/cilium_endpoint.go]: There is a typo here, you probably want to drop "has"...

Also, I think it'd be nice to use `fmt.Errorf("unexpected object type - found %T, expected %T)", obj, &CiliumEndpoint{})`  for this, and make the error much more meaningful.

File: operator/watchers/cilium_endpoint.go [hunk 4]
```diff
@@ -0,0 +1,128 @@
...
+		cache.ResourceEventHandlerFuncs{},
+		convertToCiliumEndpoint,
+		CiliumEndpointStore,
+	)
+	go ciliumEndpointInformer.Run(wait.NeverStop)
+}
+
+// convertToCiliumEndpoint converts a CiliumEndpoint to a minimal CiliumEndpoint
+// containing only a minimal set of entities used to identity a CiliumEndpoint
+// Not intended to use the CiliumEndpoints store in this cache to use them to
```
Comment (errordeveloper) [inline operator/watchers/cilium_endpoint.go]: I'm not able to parse this line...

File: operator/watchers/cilium_endpoint.go [hunk 5]
```diff
@@ -0,0 +1,128 @@
...
+			TypeMeta: concreteObj.TypeMeta,
+			ObjectMeta: metav1.ObjectMeta{
+				Name:      concreteObj.Name,
+				Namespace: concreteObj.Namespace,
+			},
+			Status: cilium_v2.EndpointStatus{
+				Identity: concreteObj.Status.Identity,
+			},
+		}
+		*concreteObj = cilium_v2.CiliumEndpoint{}
```
Comment (errordeveloper) [inline operator/watchers/cilium_endpoint.go]: Is is a GC optimisation?

Comment (aanm) [reply operator/watchers/cilium_endpoint.go]: yes

**Comment by aanm** [comment]
test-me-please

**Review by vadorovsky — APPROVED** [review]

File: operator/k8s_cep_gc.go (hunk 1 above)
Comment (errordeveloper) [inline operator/k8s_cep_gc.go]:
```suggestion
						// FIXME: this is fragile as we might have received the
```
is this what you meant?

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
retest-net-next

**Comment by aanm** [comment]
test-me-please

File: operator/k8s_identity.go [hunk 6]
```diff
@@ -84,6 +85,9 @@ func identityGCIteration() {
 				"nodes":            identity.Status.Nodes,
 			}).Debug("Deleting unused identity")
 			deleteIdentity(identity)
+		} else {
+			// If the identity is alive then mark it as alive
+			identityHeartbeat.MarkAlive(identity.Name, timeNow)
```
Comment (tgraf) [inline operator/k8s_identity.go]: This breaks the expiration logic. Given that the identity GC interval is smaller than the identity heartbeat duration, identities will be continuously marked alive and never be expired.

File: operator/identity/heartbeat.go [hunk 7]
```diff
@@ -57,6 +58,11 @@ func (i *IdentityHeartbeatStore) IsAlive(identity string) bool {
 	i.mutex.RLock()
 	defer i.mutex.RUnlock()
 
+	// The identity is definitely alive if there's a CE using it.
+	if watchers.HasCEWithIdentity(identity) {
```
Comment (tgraf) [inline operator/identity/heartbeat.go]: This looked very expensive at first but the index makes it bearable it seems.

**Review by tgraf — CHANGES_REQUESTED** [review]

File: operator/k8s_identity.go (hunk 6 above)
Comment (aanm) [reply operator/k8s_identity.go]: Discussed offline, fixed.

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by aanm** [comment]
hit https://github.com/cilium/cilium/issues/11512
