### PR TITLE
Fix complaint about nil IP address on restore of cilium_host

### LINKED ISSUE #18118: Cilium complains "Failed to remove old router IPs (restored IP: <nil>) from cilium_host. Manual intervention is required to remove all other old IPs."
Found in this v1.11 backport CI job:
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.23-kernel-4.9/49/testReport/junit/Suite-k8s-1/23/K8sDemosTest_Tests_Star_Wars_Demo/

```
Top 2 errors/warnings:
Failed to remove old router IPs (restored IP: <nil>) from cilium_host. Manual intervention is required to remove all other old IPs.
```

This seems like an extraneous warning that we should not report randomly in CI.

cc @christarazi

### PR DESCRIPTION
**Pull request by christarazi**
- daemon/cmd: Fix complaint about nil IP address on restore of cilium_host
- pkg/datapath/loader: Export SetupBaseDevice
- daemon/cmd: Add new privileged test suite
- pkg/netns: Expand godoc on ReplaceNetNSWithName

Fixes: https://github.com/cilium/cilium/issues/18118

### CODE REVIEW

File: daemon/cmd/daemon.go [hunk 1]
```diff
@@ -324,7 +324,9 @@ func (d *Daemon) restoreCiliumHostIPs(ipv6 bool, fromK8s net.IP) {
 // then it attempts to clear all IPs from the interface.
 func removeOldRouterState(ipv6 bool, restoredIP net.IP) error {
 	l, err := netlink.LinkByName(defaults.HostDevice)
-	if err != nil {
+	if _, linkNotFoundErr := err.(netlink.LinkNotFoundError); linkNotFoundErr && restoredIP == nil {
```
Comment (ldelossa) [inline daemon/cmd/daemon.go]: Can `errors.As()` be used here to simplify this?

**Review by ldelossa — APPROVED** [review]
LGTM, a small note on whether errors.As maybe applicable.

File: daemon/cmd/daemon.go (hunk 1 above)
Comment (christarazi) [reply daemon/cmd/daemon.go]: Unfortunately, this is not possible with how netlink [exposes](https://github.com/vishvananda/netlink/blob/c94808a88ba452844600de07ac14ed0ee9badca7/link.go#L1346) `LinkNotFoundError`. I [mentioned](https://github.com/vishvananda/netlink/issues/325#issuecomment-1201609182) this to the maintainer of netlink, and they fairly said to "submit a PR" essentially. :)

File: daemon/cmd/daemon_privileged_test.go [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+
+	_, ipnet, _ := net.ParseCIDR("192.0.2.1/32")
+	assert.NoError(t, netlink.AddrAdd(dummy, &netlink.Addr{IPNet: ipnet}))
+
+	netns0, err := netns.ReplaceNetNSWithName(netnsName)
+	assert.NoError(t, err)
+	assert.NotNil(t, netns0)
+	cleanup = func() {
+		cleanup1()
+		netns0.Close()
```
Comment (pippolo84) [inline daemon/cmd/daemon_privileged_test.go]: This way, in the cleanup, the deletion of the link device will be completed before the network namespace closing. Is this done on purpose (or is this irrelevant)?

**Review by pippolo84 — APPROVED** [review]
LGTM, one question left inline.

File: daemon/cmd/daemon.go (hunk 1 above)
Comment (ldelossa) [reply daemon/cmd/daemon.go]: cool :)

Comment (christarazi) [reply daemon/cmd/daemon.go]: @pippolo84 Tested my assumptions and asserted that `errors.As()` should still work. I was able to confirm it too. Pushed. Thanks both!

File: daemon/cmd/daemon_privileged_test.go (hunk 2 above)
Comment (christarazi) [reply daemon/cmd/daemon_privileged_test.go]: Yes I intended for the device to be deleted and then the entire namespace to be deleted. Is that a concern?

Comment (pippolo84) [reply daemon/cmd/daemon_privileged_test.go]: Nope, that's fine! :+1:
I asked just because it caught my eye that this is not the usual LIFO cleanup order that we would get using two separate calls to `defer` or to `t.Cleanup`. Just wanted to be sure I got your intention right.

**Review by borkmann — APPROVED** [review]

**Comment by christarazi** [comment]
CI has passed and we have approving reviews. Marking ready to merge.

**Comment by tklauser** [comment]
Commit 205810f2785ec09f149251ec827a880ff7560e26 added by this PR caused merge conflicts on backport to v1.10 and v1.11 because it relies on changes from #20453. AFAICT, the main reason we want to backport this PR is the first commit 08205dde0f6dad5cfaf18a947d17e7c67f60cbcc which applies cleanly. So I've only picked that one for now.

@christarazi do you think this is ok or should the remaining commits still be backported?
