### PR TITLE
Fix 5.10+ complexity issue with `kubeProxyReplacement=disabled`

### LINKED ISSUE #14726: Complexity issue on 5.10+ with kubeProxyReplacement=disabled
Disabling the kube-proxy replacement on net-next results in complexity issues for the IPv4 path of `bpf_lxc`:
```
level=error msg="Command execution failed" cmd="[tc filter replace dev lxcd7934e21d6b8 ingress prio 1 handle 1 bpf da obj 1885_next/bpf_lxc.o sec from-container]" error="exit status 1" subsys=datapath-loader
[...]
level=warning msg="Prog section '2/7' rejected: Argument list too long (7)!" subsys=datapath-loader
level=warning msg=" - Type:         3" subsys=datapath-loader
level=warning msg=" - Attach Type:  0" subsys=datapath-loader
level=warning msg=" - Instructions: 3307 (0 over limit)" subsys=datapath-loader
level=warning msg=" - License:      GPL" subsys=datapath-loader
level=warning subsys=datapath-loader
level=warning msg="Verifier analysis:" subsys=datapath-loader
level=warning subsys=datapath-loader
[...]
level=warning msg="BPF program is too large. Processed 1000001 insn" subsys=datapath-loader
```
An example can be found at https://jenkins.cilium.io/job/Cilium-PR-K8s-1.13-net-next/556/testReport/Suite-k8s-1/13/K8sDatapathConfig_Encapsulation_Check_connectivity_with_transparent_encryption_and_VXLAN_encapsulation/.
Sysdump: 
[b91bb5b3_K8sDatapathConfig_Encapsulation_Check_connectivity_with_transparent_encryption_and_VXLAN_encapsulation.zip](https://github.com/cilium/cilium/files/5870027/b91bb5b3_K8sDatapathConfig_Encapsulation_Check_connectivity_with_transparent_encryption_and_VXLAN_encapsulation.zip)
(IPSec is enabled in this example but it doesn't make a difference.)

This is closely related to #14234.

### PR DESCRIPTION
**Pull request by pchaigno**
This pull request fixes https://github.com/cilium/cilium/issues/14726, our complexity issue with `kubeProxyReplacement=disabled` when running Linux 5.10+. The fix is less general than originally hoped and only applies to 5.10+; other complexity issues are therefore not fixed by this change. With a bit more work, we may able to extend it to 5.1+ in the future.

See commits for details. As a summary:
1. Implements a couple changes to allow our BPF datapath to pass the verifier when compiled with `mattr=+alu32`.
2. Compile our BPF datapath with `mcpu=v3` (implies `mattr=+alu32`) on kernels 5.10+.
3. Disable a workaround for https://github.com/cilium/cilium/issues/14726 in tests, to make sure the complexity issue is fixed.

In addition to the end-to-end tests, these changes were also tested on kernels 5.10 and 5.11 with datapath configurations `KERNEL=419` and `KERNEL=netnext`.

### CODE REVIEW

**Comment by pchaigno** [comment]
test-me-please

File: bpf/lib/metrics.h [hunk 1]
```diff
@@ -34,10 +34,10 @@ static __always_inline void update_metrics(__u32 bytes, __u8 direction,
 	entry = map_lookup_elem(&METRICS_MAP, &key);
 	if (entry) {
 		entry->count += 1;
-		entry->bytes += (__u64)bytes;
+		entry->bytes += bytes;
 	} else {
 		newEntry.count = 1;
-		newEntry.bytes = (__u64)bytes;
+		newEntry.bytes = bytes;
```
Comment (michi-covalent) [inline bpf/lib/metrics.h:40]: not sure why it started complaining about this now 🤔 : https://github.com/cilium/cilium/pull/16084/checks?check_run_id=2556550015#step:4:11

Comment (pchaigno) [reply bpf/lib/metrics.h:40]: That's safe to ignore IMO. `checkpatch` is configured to only checks the changed code lines, so it only complains about this now because I touched this line.

**Review by michi-covalent — APPROVED** [review]

**Comment by pchaigno** [comment]
ci-aks

File: bpf/include/bpf/ctx/xdp.h [hunk 2]
```diff
@@ -262,7 +262,7 @@ ctx_redirect(const struct xdp_md *ctx, int ifindex, const __u32 flags)
 	return XDP_TX;
 }
 
-static __always_inline __maybe_unused __u32
+static __always_inline __maybe_unused __u64
 ctx_full_len(const struct xdp_md *ctx)
```
Comment (borkmann) [inline bpf/include/bpf/ctx/xdp.h:266]: nit: would be good to also adjust the skb related `ctx_full_len` so they end up with the same signature

File: bpf/lib/nodeport.h [hunk 3]
```diff
@@ -443,7 +443,7 @@ static __always_inline int dsr_reply_icmp6(struct __ctx_buff *ctx,
 	const __u32 l3_max = sizeof(*ip6) + orig_dgram;
 	__be16 type = bpf_htons(ETH_P_IPV6);
 	__s32 len_new = off + sizeof(*ip6) + orig_dgram;
-	__s32 len_old = ctx_full_len(ctx);
+	__u64 len_old = ctx_full_len(ctx);
 	void *data_end = ctx_data_end(ctx);
```
Comment (borkmann) [inline bpf/lib/nodeport.h:447]: nit: given we later on do `if (ctx_adjust_troom(ctx, -(len_old - len_new)) < 0)`, we should also convert len_new.

**Comment by pchaigno** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]
lgtm!

**Review by christarazi — APPROVED** [review]
:rocket:

**Review by aditighag — APPROVED** [review]
🚀

**Comment by pchaigno** [comment]
Known flakes:
- ConformanceAKS due to https://github.com/cilium/cilium/issues/16097.
- k8s-1.16-kernel-netnext due to https://github.com/cilium/cilium/issues/12511.
- k8s-1.19-kernel-5.4 failed only after the rebase and looks unrelated (checked the artifacts). Filed https://github.com/cilium/cilium/issues/16122 for it.
- runtime due to https://github.com/cilium/cilium/issues/16040, which was failed but the fix is not included in this PR.

All team reviews are covered. Marking as ready to merge.

**Review by joestringer — APPROVED** [review]

File: pkg/datapath/loader/compile.go [hunk 4]
```diff
@@ -166,9 +166,20 @@ var (
...
+			// tested it and need it to work around complexity issues.
+			if h := manager.GetHelpers("sched_cls"); h != nil {
+				if _, ok := h["bpf_redirect_neigh"]; ok {
+					nameBPFCPU = "v3"
+					return
+				}
+			}
+			// We want to enable v2 on all kernels that support it, that is,
+			// kernels 4.14+.
 			if h := probes.NewProbeManager().GetHelpers("xdp"); h != nil {
```
Comment (borkmann) [inline pkg/datapath/loader/compile.go:183]: nit: saw too late, but could you do a small cleanup in that the 2nd GetHelpers() could also use prior defined manager?

Comment (pchaigno) [reply pkg/datapath/loader/compile.go:183]: Oh, ***. I defined that manager variable for nothing :facepalm: 

TBH, I don't think it matters much: `probes.NewProbeManager()` is a singleton ;-)

**Comment by brb** [comment]
@pchaigno Don't we want to backport this to v1.9? Asking, as https://github.com/cilium/cilium/issues/14960 was reporting the complexity issue.

**Comment by pchaigno** [comment]
> @pchaigno Don't we want to backport this to v1.9? Asking, as #14960 was reporting the complexity issue.

It's on my radar to backport to both v1.9 and v1.8. I want to finish testing with the latest BPF security fixes first as those will be backported to all LTS kernels. Looks good so far, but I didn't run the full e2e tests yet.

**Comment by pchaigno** [comment]
Marking for backport to v1.9.

**Comment by diversario** [comment]
> > @pchaigno Don't we want to backport this to v1.9? Asking, as #14960 was reporting the complexity issue.
> 
> @brb It's on my radar to backport to both v1.9 and v1.8. I want to finish testing with the latest BPF security fixes first as those will be backported to all LTS kernels. Looks good so far, but I didn't run the full e2e tests yet.

Is this not going to be backported to 1.8 after all?

**Comment by pchaigno** [comment]
> Is this not going to be backported to 1.8 after all?

Probably not. It's a fair bit of effort to backport to stable branches because several other PRs need to be backported as well. v1.8 is also not supported since the release of v1.11.
