### PR TITLE
daemon: Make cilium status independent from k8s status

### LINKED ISSUE #31702: CFP: Avoid killing a cilium-agent when all kube-apiservers are down
## Cilium Feature Proposal

**Is your proposed feature related to a problem?**

Currently, cilium-agent is killed by livenessProbe when the connectivity with kube-apiserver is lost.
BGP session for that node is also disabled because the cilium-agent contains a BGP speaker.
This causes a problem that k8s service endpoint pods cannot be accessed via cilium L4LB when all kube-apiservers are down (or lose connectivity with all nodes) since the routes to all nodes are no longer advertized.
Network connectivity of the cluster should be provided even if the k8s control-plane is down just as kubelet keeps pods alive in the same case.

Mechanism of killing cilium-agent:
1. Connection between cilium-agent and the kube-apiserver is lost.
2. [kubernetes probe](https://github.com/cilium/cilium/blob/e2e97f3e07843f568813f90500ba75b21c462b8b/daemon/cmd/status.go#L796-L843) fails after about 1 min (depends on the cluster size).
(this was after maximum 15 mins before https://github.com/cilium/cilium/pull/31019 merged)
3. livenessProbe (/healthz) starts to fail after up to 30 secs (depends on the livenessProbe config).
4. cilium-agent is killed by livenessProbe after 5 minutes (depends on the livenessProbe config).

**Describe the feature you'd like**

Current behavior:
Cilium-agent is killed when the connectivity with kube-apiserver is lost.
This behavior would be correct because the cilium-agent cannot re-configure the service endpoints when a Service resource is updated.

Proposed feature:
- Avoid killing a cilium-agent when all kube-apiservers are down.
- Kill cilium-agents like the current behavior, when a node can't access to the kube-apiserver and the others can.

### PR DESCRIPTION
**Pull request by tkna**
This PR adds `requireK8sConnectivity` flag (default: true) to exclude the K8s probe from the result of health probe.
This flag can be set by a newly added http header `require-k8s-connectivity` of /healthz cilium API and pod's /healthz endpoint.

Fixes: https://github.com/cilium/cilium/issues/31702

### CODE REVIEW

**Comment by ldelossa** [comment]
@tkna I'm going to mark this for more discussion. While I see your issue, I'm not sure if disabling liveliness probes is ideal from Cilium's point of view. 

I'm going to pull in some folks in your linked CFP for further discussion. Lets go over this in that issue.

**Comment by YutaroHayakawa** [comment]
I think this solution makes sense. We have discussed about this issue in the APAC community meeting and concluded that killing the whole Cilium agent on k8s disconnection is too aggressive. We might want to kill the certain subsystem, but maybe not entire agent.

For example, the real impact of k8s disconnection for BGP Control Plane is the user's configuration change may not be propagated in timely manner. BGP works without any problem otherwise. I'd assume most of the time, users want to avoid connectivity loss instead of configuration delay.

We might have a subsystem which this behavior is desirable, so opt-in might be a safer option. However, in my personal opinion, we can just completely remove k8s connectivity from health criteria and fix such a subsystem to stop individually.

Let me CC @joestringer as a person who was involved in the original discussion and also as a core maintainer.

File: daemon/cmd/agenthealth.go [hunk 1]
```diff
@@ -33,6 +34,14 @@ func (d *Daemon) startAgentHealthHTTPService() {
 
 	mux := http.NewServeMux()
 	mux.Handle("/healthz", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
+		includeK8sCheck := false
+		if v := r.Header.Get("include-k8s-check"); v != "" {
+			res, err := strconv.ParseBool(v)
+			if err != nil {
+				log.WithError(err).WithFields(logrus.Fields{"value": v}).Warn("include-k8s-check should be bool")
+			}
+			includeK8sCheck = res
```
Comment (YutaroHayakawa) [inline daemon/cmd/agenthealth.go]: Nit: I think the return value of the `ParseBool` on error is undefined. I'd set false (default) explicitly on failure or return 400 (Bad Request).

File: api/v1/openapi.yaml [hunk 2]
```diff
@@ -47,6 +47,12 @@ paths:
         in: header
         required: false
         type: boolean
+      - name: include-k8s-check
```
Comment (joestringer) [inline api/v1/openapi.yaml]: nit: For clarity, I might suggest naming this a little bit more explicitly, something like:

```suggestion
      - name: require-k8s-connectivity
```

**Review by joestringer — COMMENTED** [review]
I've been thinking for a while that the cilium-agent connectivity probably shouldn't depend on k8s-apiserver availability, so I think the idea here seems reasonable. I'm not sure if there is a specific argument to keep kube-apiserver connectivity as part of the base health check.

If we are concerned that we may need to retain the previous behavior, then it makes sense to keep it optional. I'm not sure whether we need this as part of the API, in which case we should add a flag to the `cilium-dbg status` CLI in order to control this API parameter. Alternatively, we could just create a cilium-agent daemon flag to control this optional behaviour.

Another question I would have is: With this implementation, how can a user detect that Cilium is not connecting to the kube-apiserver? Previously it would be obvious at some point because the cilium-agent would crash. I suppose there may be metrics like `cilium_event_ts` for the most recent event from the control plane.. but should we add another metric to make this more obvious?

**Comment by marseel** [comment]
I've been thinking about this PR too :sweat_smile: 

AFAIK controller that updates connectivity to apiserver is still running here: https://github.com/cilium/cilium/blob/0001f4b3fcf950ba6a3bb6fb0cba14931b340ce3/daemon/cmd/status.go#L804

So I would **at least** expect `cilium-dbg status` to show whether connectivity to k8s works, but a metric about the general status of Cilium connectivity to control-plane (K8s control plane / kvstore) would be nice too. 

FYI, there is also a controller that is supposed to close all connections if the health check of the k8s apiserver fails: https://github.com/cilium/cilium/blob/c32980607c16cf6daddea300f8318e217e31bc34/pkg/k8s/client/cell.go#L290
so if this part works, there is also that fail-safe mechanism.

> I'm not sure if there is a specific argument to keep kube-apiserver connectivity as part of the base health check.

There was some bug in the past with connectivity to kube-apiserver, that was only resolved with the restart of the agent: https://github.com/cilium/cilium/issues/20915
So while I also lean towards enabling it by default too, we still definitely need an option to retain previous behavior, just in case, for a transition period.


CC @hemanthmalla we talked about it before a little bit, I am guessing you might be interested in this too and probably have some thoughts as well. I guess you might want something similar for kvstore so potentially we might want to make it a bit more generic.

**Comment by learnitall** [comment]
Isn't one of the assumptions users can make about the restart behavior of the cilium-agent is that connectivity will continue to work even as the cilium-agent is killed or restarted? I'm confused by the comments here because they assume there is a coupling between cilium agent availability and Pod network connectivity. Are we referring to "connectivity loss" as connectivity that is out of sync with user configured state in the k8s apiserver?

**Comment by rouke-broersma** [comment]
> Isn't one of the assumptions users can make about the restart behavior of the cilium-agent is that connectivity will continue to work even as the cilium-agent is killed or restarted? I'm confused by the comments here because they assume there is a coupling between cilium agent availability and Pod network connectivity. Are we referring to "connectivity loss" as connectivity that is out of sync with user configured state in the k8s apiserver? 

The issue is bgp advertisement. If cilium agent is offline when kube-api is unavailable, cilium also can't advertise routes to bgp peers so this effectively means kube-api availability now has impact on loadbalancer availability, for which there is no good reason.

**Comment by joestringer** [comment]
> Isn't one of the assumptions users can make about the restart behavior of the cilium-agent is that connectivity will continue to work even as the cilium-agent is killed or restarted?

The other aspect I'll point out is that this PR suggests that if the kube-apiserver goes down, that will force every cilium-agent instance in the cluster to also go down. Similar to how you're asserting that the dataplane should continue without the local control plane, I think it makes sense for the local control plane to continue without the central control plane.

**Comment by joestringer** [comment]
What's the next step on this PR? I see a few comments suggesting to change some things. @tkna are you still working on this? Do you have any questions for reviewers?

**Comment by tkna** [comment]
@joestringer @marseel @YutaroHayakawa @ysksuzuki @ldelossa @learnitall 

I made some minor corrections.
As far as I know, the remaining discussions are as follows:

1. whether `--require-k8s-connectivity` should be implemented as an API parameter or a daemon config
I just implemented it as an API parameter for now.
I think implementing it as an API parameter is more flexible and easy to apply/rollback since it is configured by HTTP header and we can change it per request.

1. whether `--require-k8s-connectivity` should be false or true by default
I just implemented it as default:false for now, but the discussion is still open.

> So while I also lean towards enabling it by default too, we still definitely need an option to retain previous behavior, just in case, for a transition period.

In my understanding, in @marseel's opinion `--require-k8s-connevtivity` should be true by default at this point.

3. whether we should generalize this mechanism (to exclude kvstore probe etc.)
I don't think the generalization is necessary unless there is a requirement.

4. whether we should introduce a new metric
As @marseel mentioned, connectivity to kube-apiserver can be checked by cilium-dbg status and logs from "k8s-heartbeat" mechanism, so I don't think the new metric is necessary at least for this PR.
(can be another PR)

**Comment by marseel** [comment]
Thanks @tkna for the detailed summary. 

> whether --require-k8s-connectivity should be false or true by default
I just implemented it as default:false for now, but the discussion is still open.

I think long-term it should be true by default, but it would require significantly more testing. I'm fine withhaving it as false by default for now and then following up with making it true.

**Comment by tkna** [comment]
@marseel 
Just for clarification, `--require-k8s-connectivity: true` retains the existing behavior, and `false` makes `cilium-dbg status`(and livenessProbe) independent from the k8s probe.

Do you mean:
  long-term: `default: false` (make `cilium-dbg status` independent from the k8s probe)
  for now: `default: true` (retaining existing behavior)
?

**Comment by marseel** [comment]
yea, sorry I wasn't clear. I meant long-term k8s health-check would be disabled by default, but for now let's keep current behaviour.

**Comment by tkna** [comment]
@marseel 
Fixed to keep the existing behavior by default.
Considering making a boolean option for `cilium-dbg status`, I changed the option's name from `require-k8s-connectivity` to `without-k8s-connectivity` to make it false by default.

If this PR seems to be OK, could you trigger E2E tests?

**Comment by tkna** [comment]
@ovidiutirla Some E2E tests seemed to be failing for reasons unrelated to this PR. I just rebased it, so could you run the E2E tests again?

**Comment by youngnick** [comment]
Looks like @tkna has made all the requested changes as agreed on here, is there anything else that we need to do to keep this moving? @joestringer, @YutaroHayakawa, @marseel?

**Review by YutaroHayakawa — APPROVED** [review]
I think it's good. Thanks!

**Review by ovidiutirla — APPROVED** [review]

**Review by marseel — APPROVED** [review]
lgtm for my codeowners.
I would still change the naming to what Joe suggested - `require-k8s-connectivity` instead to make it easier to read

**Review by ldelossa — APPROVED** [review]
LGTM

File: cilium-dbg/cmd/status.go [hunk 3]
```diff
@@ -50,6 +51,7 @@ func init() {
 	statusCmd.Flags().BoolVar(&statusDetails.AllClusters, "all-clusters", false, "Show all clusters")
 	statusCmd.Flags().BoolVar(&allHealth, "all-health", false, "Show all health status, not just failing")
 	statusCmd.Flags().BoolVar(&brief, "brief", false, "Only print a one-line status message")
+	statusCmd.Flags().BoolVar(&withoutK8sConnectivity, "without-k8s-connectivity", false, "whether the result of connectivity check to kube-apiserver should affect the result of health status of daemon")
```
Comment (learnitall) [inline cilium-dbg/cmd/status.go]: Do you mind syncing the description here with the one used in `openapi.yaml`? They seem to be different.

Also, slight wording suggestion:

```suggestion
	statusCmd.Flags().BoolVar(&withoutK8sConnectivity, "without-k8s-connectivity", false, "Controls if the result of the connectivity check to the kube-apiserver impacts the health status of the daemon")
```

**Review by learnitall — CHANGES_REQUESTED** [review]
Two small nits, but otherwise LGTM for API changes. Thanks!

File: cilium-dbg/cmd/status.go (hunk 3 above)
Comment (tkna) [reply cilium-dbg/cmd/status.go]: Fixed: https://github.com/cilium/cilium/compare/a2e5a0150b090521f12e741c5e9e0e5e576ac55f..91617b22e67baba63e0d147cb1cda4cff980d18a

**Review by learnitall — APPROVED** [review]
LGTM, thanks!

**Comment by tkna** [comment]
@ldelossa Is there anything else I should do about this PR?

File: cilium-dbg/cmd/status.go [hunk 4]
```diff
@@ -50,6 +51,7 @@ func init() {
 	statusCmd.Flags().BoolVar(&statusDetails.AllClusters, "all-clusters", false, "Show all clusters")
 	statusCmd.Flags().BoolVar(&allHealth, "all-health", false, "Show all health status, not just failing")
 	statusCmd.Flags().BoolVar(&brief, "brief", false, "Only print a one-line status message")
+	statusCmd.Flags().BoolVar(&withoutK8sConnectivity, "without-k8s-connectivity", false, "Controls if the result of the connectivity check to the kube-apiserver impacts the health status of the daemon")
```
Comment (joestringer) [inline cilium-dbg/cmd/status.go]: I'm not sure why the flag was switched from `--require-k8s-connectivity` to `--without-k8s-connectivity`. The latter seems a bit misleading, because this implementation still prints k8s connectivity results in the CLI status output:

```
# cilium-dbg status --without-k8s-connectivity | grep -i kubernetes
Kubernetes:             Ok   1.29 (v1.29.2) [linux/amd64]
Kubernetes APIs:        ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
```

I think that the flag works the way we want - report k8s status but do not fail if k8s connectivity is broken - but the flag name and description should be clearer.
```suggestion
	statusCmd.Flags().BoolVar(&withoutK8sConnectivity, "require-k8s-connectivity", true, "If set to true, failure of the agent to connect to the Kubernetes control plane will cause the status command to also fail.")
```

Or maybe even better...

```suggestion
	statusCmd.Flags().BoolVar(&withoutK8sConnectivity, "require-k8s-connectivity", true, "If true, when the cilium-agent cannot access the Kubernetes control plane, this status command returns a non-zero exit status.")
```

**Review by joestringer — CHANGES_REQUESTED** [review]
Sorry for the delay on this. I think it's almost ready to merge.

Paul was assigned for CLI but he has moved on to other areas, so I gave feedback from a @cilium/cli perspective.

File: cilium-dbg/cmd/status.go (hunk 4 above)
Comment (joestringer) [reply cilium-dbg/cmd/status.go]: /cc also @learnitall , I see you had given feedback on the command. I think the feedback was good to help to improve the flag text, but I think that this language is even clearer: Rather than using the abstract "control if ... impacts ...", it describes exactly which value ("if true") and describes what this command will do (" ... the status command to also fail").

Comment (learnitall) [reply cilium-dbg/cmd/status.go]: Thanks for the CC, I agree this is more clear. Thanks @joestringer :+1:

Comment (tkna) [reply cilium-dbg/cmd/status.go]: @joestringer Thank you for the feedback. I reverted the flag name from `--without-k8s-connectivity` to `--require-k8s-connectivity`.

**Review by joestringer — APPROVED** [review]
Thanks!

**Comment by joestringer** [comment]
Thanks for the contribution @tkna !

**Comment by tkna** [comment]
@joestringer 
Do you think this comment should be modified since it is out of date?
https://github.com/cilium/cilium/pull/32724#issue-2318459880
> `withoutK8sConnectivity`

**Comment by joestringer** [comment]
@tkna yes, that would be helpful. When this PR becomes part of a release, the release notes will point back to this PR. If a user is interested in the feature, they may open this PR and read the description.

**Comment by tkna** [comment]
@joestringer 
https://github.com/cilium/cilium/pull/32724#issue-2318459880
modified to `requireK8sConnectivity`.
