### PR TITLE
fix(datapath): disable VF info collection in netlink

### LINKED ISSUE #43516: cilium can hold `rtnl_mutex` for long on SR-IOV hosts due to VF info filling
## Summary

On nodes with SR-IOV enabled, `cilium-agent` issues RTM_GETLINK dumps that end up spending most of their time in the kernel filling per-VF attributes (`IFLA_VFINFO_LIST`). This happens under the global RTNL mutex, and can block other components that also need RTNL,  resulting in latency spikes / datapath disruption.

## Impact / symptoms

Thanks to research from @mkplv we observed `ovs-vswitchd` main thread waiting on RTNL for long periods while `cilium-agent` was the lock owner:

* ~867–869 ms stalls (two separate instances)
* ~291 ms stall on a “healthier” node (and additional ~158 ms instances)

These stalls are large enough to cause visible network disruption in OVS-based datapaths.

### Bad node example (where RTNL wait dominated by VF info)

Two consecutive waits observed:

* `ovs wait: 867354395 ns`  (~867.35 ms)
* `ovs wait: 868929658 ns`  (~868.93 ms)

In both cases the bfptrace histograms show `ovs-vswitchd` waiting in the `[64M, 128M)` ns bucket (12 samples), while `cilium-agent` spends time in `rtnl_fill_vfinfo()` for `eth0` in the `[1M, 2M)` ns bucket (768 samples).

**ovs_waiting_for_h[cilium-agent]** (n=12)

| Bucket | Count | % | 
|---|---:|---|
| `[64M, 128M)` | 12 | 100.0% | 

**rtnl_fill_vfinfo_time_per_dev[eth0]** (n=768)

| Bucket | Count | % | 
|---|---:|---|
| `[1M, 2M)` | 768 | 100.0% |

Total VF fill time reported for one wait instance: `rtnl_fill_vfinfo_time_total: 867325131 ns` (~867.33 ms), i.e. essentially the entire OVS wait.

The observed multiplicative factor matches VF count:
* 12 calls to `rtnl_getlink()` × 64 VFs ≈ **768 calls** to `rtnl_fill_vfinfo()`.

### Healthier node example

On a node where overall stalls were smaller:

* `ovs wait: 291167071 ns` (~291.17 ms) with `rtnl_fill_vfinfo_time_total: 0` (no VF fill captured under the chosen threshold in that particular instance)
* Another instance: `ovs wait: 158359256 ns` (~158.36 ms) with
  `rtnl_fill_vfinfo_time_total: 157249684 ns` (~157.25 ms)

**Prettified histograms (healthier node)**

**ovs_waiting_for_h[cilium-agent]** (n=11)

| Bucket | Count | % | 
|---|---:|---|
| `[8M, 16M)` | 11 | 100.0% |

**rtnl_fill_vfinfo_time_per_dev[eth0]** (n=704)

| Bucket | Count | % | 
|---|---:|---|
| `[128K, 256K)` | 703 |  99.9% |
| `[256K, 512K)` | 1 |   0.1% | 

Same “12 × 64” pattern is present, but each VF fill is ~40× faster than on the bad node.

###  Root cause

Relevant path in kernel:

* [`rtnl_getlink()` ](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/core/rtnetlink.c#n4133)

* [`rtnl_fill_ifinfo()` ](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/core/rtnetlink.c#n2027)

* VF loop / helpers ([`rtnl_fill_vf()`](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/core/rtnetlink.c#n1642) / [`rtnl_fill_vfinfo()`](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/core/rtnetlink.c#n1496))  

The gating mechanism is the extended mask attribute:

* UAPI definitions ([`IFLA_EXT_MASK`](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/if_link.h#n335))  

In other words, kernel only includes `IFLA_VFINFO_LIST` in dumps when userspace requests it via `IFLA_EXT_MASK`. So if userspace does *not* set bit, VF info is *not* generated and the expensive per-VF loop is avoided.

Cilium uses github.com/vishvananda/netlink , which utilizes RTM_GETLINK operations. In the observed configuration, the requests include `IFLA_EXT_MASK` with `RTEXT_FILTER_VF` set, which causes the kernel to generate `IFLA_VFINFO_LIST` (per-VF data) during the dump.

### Practical approach

Cilium should use the new capability introduces in vishvananda/netlink#1097 to stop requesting VF info by default.

#### Why this is safe

* VF info is optional extended data. Most Cilium logic doesn’t require it.
* Without `RTEXT_FILTER_VF`, the kernel will simply omit `IFLA_VFINFO_LIST`.
* Userspace parsing code can still handle VF info when present; it just won’t be requested by default.

### PR DESCRIPTION
**Pull request by pasteley**
Disable Virtual Function information collection in netlink handle operations to avoid hold of `rtnl_mutex` on systems with SR-IOV devices.

Fixes: #43516

```release-note
Reduces rtnl_mutex contention on SR-IOV nodes by not requesting VF information in netlink RTM_GETLINK operations
```

### CODE REVIEW

File: pkg/datapath/linux/safenetlink/netlink_linux.go [hunk 1]
```diff
@@ -20,6 +21,28 @@ const (
...
 )
 
+// NewHandle wraps netlink.NewHandle with deafult options overwrite
+func NewHandle(nlFamilies ...int) (*netlink.Handle, error) {
+	//nolint:forbidigo
+	handle, err := netlink.NewHandle(nlFamilies...)
+	if err != nil {
+		return nil, err
+	}
+	handle.DisableVFInfoCollection()
```
Comment (bersoare) [inline pkg/datapath/linux/safenetlink/netlink_linux.go]: can we make this configurable instead?
we're doing some work around sr-iov at https://github.com/cilium/cilium/tree/feature/dra-driver, and the changes here would prevent us from reusing the handles from this package as we want to retrieve vf info as well.

**Comment by bersoare** [comment]
overall code looks good to me. there's a failed test, but it could be a flake. havent looked into it yet. hopefully someone can hit the retry
other than that, you're missing the release note in the pr description. mind adding it? 🙏🏽

**Comment by ti-mo** [comment]
Hi, what problem does this solve, exactly? Is there an existing issue that points out why the lock being held is a problem? Thanks.

**Comment by pasteley** [comment]
> Is there an existing issue that points out why the lock being held is a problem? Thanks.

@ti-mo  yes, you can find it mentioned in PR description: https://github.com/cilium/cilium/issues/43516

**Comment by bersoare** [comment]
@pasteley , can you add a release note message to the pr description?
something similar to this one (in the code block): https://github.com/cilium/cilium/pull/42896#issue-3647980157

**Review by bersoare — APPROVED** [review]

**Comment by bersoare** [comment]
https://github.com/cilium/cilium/actions/runs/20848915321 looks like a flake. i see a similar failure on other branches too
https://github.com/cilium/cilium/actions/workflows/conformance-l7.yaml

File: pkg/datapath/linux/safenetlink/netlink_linux.go [hunk 2]
```diff
@@ -20,6 +21,46 @@ const (
...
+	}
+
+	if !cfg.enableVFInfo {
+		handle.DisableVFInfoCollection()
+	}
+
+	return handle, nil
+}
+
+// NewHandleAt wraps netlink.NewHandleAt with configurable options
```
Comment (ti-mo) [inline pkg/datapath/linux/safenetlink/netlink_linux.go]: Where is this used in our codebase? We generally prefer calling `NewHandle()` within `NetNS.Do()`, so I'm not sure if we'll ever use this.

File: pkg/datapath/linux/safenetlink/netlink_linux.go [hunk 3]
```diff
@@ -20,6 +21,46 @@ const (
 	netlinkRetryMax      = 30
 )
 
+// NewHandle wraps netlink.NewHandle with configurable options
+func NewHandle(opts ...Option) (*netlink.Handle, error) {
```
Comment (ti-mo) [inline pkg/datapath/linux/safenetlink/netlink_linux.go]: With this addition, we're drifting further away from the upstream library's API, which is problematic as `safenetlink` is supposed to be a thin wrapper around the upstream package, not an abstraction layer on top. It's a matter of taste, but I'm not a fan of the `...Option` mechanism, this should probably be a simple options struct instead, that tends to be easier to read and maintain in the long term.

The design of `handle.DisableVFInfoCollection()` also painted us into a corner, since we cannot default it to false and (re-)enable it later. A simple `Handle.SetVFInfoCollection(bool)` would've been easier to work with for whomever needs more control (or, the options mechanism should live in the upstream lib). It's only a flag used during message assembly, there's no real need to lock it down after handle creation.

To keep things straightforward, I suggest the following:

```go
func NewHandle(nlFamilies ...int, opts *HandleOptions) (*netlink.Handle, error) { ... }
```

This keeps things mostly the same, and we can rip the options out later if they would cause a problem. There are only a few callsites, so it doesn't cause any unreasonable churn.

File: pkg/datapath/linux/safenetlink/netlink_unspecified.go [hunk 4]
```diff
@@ -14,8 +14,17 @@ import (
...
 
 	"github.com/vishvananda/netlink"
+	"github.com/vishvananda/netns"
 )
 
+func NewHandle(opts ...Option) (*netlink.Handle, error) {
+	return nil, netlink.ErrNotImplemented
+}
+
+func NewHandleAt(ns netns.NsHandle, opts ...Option) (*netlink.Handle, error) {
```
Comment (ti-mo) [inline pkg/datapath/linux/safenetlink/netlink_unspecified.go]: Idem, unused.

**Review by ti-mo — CHANGES_REQUESTED** [review]
Thanks, not sure how I missed the issue link. Left a few comments outlining my thoughts and the way forward for this package.

File: pkg/datapath/linux/safenetlink/netlink_linux.go (hunk 3 above)
Comment (pasteley) [reply pkg/datapath/linux/safenetlink/netlink_linux.go]: Thank you for review, I see that are clearly some flaws in netlink changes design. Not only that, `netlink.HandleOptions` internal fields are unexported. Reworked `NewHandle()` according to suggestions

**Comment by bersoare** [comment]
looking into this test failure

**Comment by bersoare** [comment]
issue for the ci failure: https://github.com/cilium/cilium/issues/43930

**Comment by bersoare** [comment]
ci failure: https://github.com/cilium/cilium/issues/43770

**Comment by bersoare** [comment]
@ti-mo , i think this one is ready for 👀

**Comment by julianwiedmann** [comment]
I believe @YutaroHayakawa dropped from `sig-datapath`, let's try to get a new assignee.

File: pkg/datapath/linux/safenetlink/netlink_linux.go [hunk 5]
```diff
@@ -20,6 +20,25 @@ const (
 	netlinkRetryMax      = 30
 )
 
+type HandleOptions struct {
```
Comment (ti-mo) [inline pkg/datapath/linux/safenetlink/netlink_linux.go]: Define this in a common file so it doesn't need to be redeclared in _linux and _unspecified.

File: pkg/datapath/linux/safenetlink/netlink_linux.go [hunk 6]
```diff
@@ -20,6 +20,25 @@ const (
...
+	EnableVFInfo bool
```
Comment (ti-mo) [inline pkg/datapath/linux/safenetlink/netlink_linux.go]:
```suggestion
    // EnableVFInfoCollection ... <explain what it does>
	EnableVFInfoCollection bool
```

File: pkg/datapath/linux/safenetlink/netlink_linux.go [hunk 7]
```diff
@@ -20,6 +20,25 @@ const (
...
+}
+
+// NewHandle wraps netlink.NewHandle with VF info collection disabled by default.
+func NewHandle(opts *HandleOptions, nlFamilies ...int) (*netlink.Handle, error) {
+	//nolint:forbidigo
```
Comment (ti-mo) [inline pkg/datapath/linux/safenetlink/netlink_linux.go:29]:
```suggestion
	if opts == nil {
		opts = &HandleOptions{}
	}

	//nolint:forbidigo
```

File: pkg/datapath/linux/safenetlink/netlink_linux.go [hunk 8]
```diff
@@ -20,6 +20,25 @@ const (
 	netlinkRetryMax      = 30
 )
 
+type HandleOptions struct {
+	EnableVFInfo bool
+}
+
+// NewHandle wraps netlink.NewHandle with VF info collection disabled by default.
+func NewHandle(opts *HandleOptions, nlFamilies ...int) (*netlink.Handle, error) {
```
Comment (ti-mo) [inline pkg/datapath/linux/safenetlink/netlink_linux.go]: Move nlFamilies into HandleOptions. On the call sites, this looks the same in 99.9% of cases (`NewHandle(nil)`).

```suggestion
func NewHandle(opts *HandleOptions) (*netlink.Handle, error) {
```

File: pkg/datapath/linux/safenetlink/netlink_linux.go [hunk 9]
```diff
@@ -20,6 +20,25 @@ const (
 	netlinkRetryMax      = 30
 )
 
+type HandleOptions struct {
+	EnableVFInfo bool
+}
+
+// NewHandle wraps netlink.NewHandle with VF info collection disabled by default.
```
Comment (ti-mo) [inline pkg/datapath/linux/safenetlink/netlink_linux.go]: The VFInfo collection is an implementation detail, and the user can figure this out by themselves by looking at HandleOptions (assuming it has sane defaults and comments 🙂).

```suggestion
// NewHandle wraps netlink.NewHandle with HandleOptions.
```

**Review by ti-mo — CHANGES_REQUESTED** [review]
Thanks! Looks better, though I'd make NewHandle take a HandleOptions only, since nlFamilies also serves as configuration for the netlink socket.

File: pkg/datapath/linux/safenetlink/netlink_linux.go (hunk 3 above)
Comment (pasteley) [reply pkg/datapath/linux/safenetlink/netlink_linux.go]: Renamed to `HandleConfig` to avoid confusion with vendored `netlink.HandleOptions`

**Review by ti-mo — APPROVED** [review]
Solid, thanks! 💯

**Review by ti-mo — CHANGES_REQUESTED** [review]
I just realized this completely sidesteps the purpose of the `safenetlink` package, since NewHandle returns a `netlink.Handle`, whose methods aren't intercepted by the safenetlink package. I think we need to introduce a `safenetlink.Handle` that wraps the netlink one and also wraps its methods with a retry loop.

@gandro PTAL

**Comment by gandro** [comment]
Took a look - since we moved to `forbidigo`, we will actually detect calls to the `netlink.Handle`. So the PR here doesn't sidestep our linter, it will still complain if you call unsafe functions on the handle returned by `safenetlink.NewHandle`.

Calling unsafe functions on the handle require you to use `safenetlink.WithRetry*` - here's an example from our codebase:
https://github.com/nebius/cilium/blob/d06fe451b641338b41e4542661c1eb34fda4bd85/pkg/datapath/linux/route/reconciler/reconciler.go#L349-L356

If we introduce a wrapper, then we have to make sure that all wrapped functions are safe. So from a safety perspective, I think this PR is fine as is. But it would probably be a potential improvement if we wrapped `netlink.Handle` to offer safe methods as well.

**Comment by gandro** [comment]
On a only slightly related node: What we could consider is making sure that `netlink.NewHandle` is also forbidden by adding it to the list here: https://github.com/cilium/cilium/blob/dcf00f5782d3c79d3ebe15682012ce6e2c5c2011/.golangci.yaml#L63

That way, new code would have to always use `safenetlink.NewHandle` (or explicitly opt out if they want to see VFs)

**Comment by ti-mo** [comment]
@pasteley I'd like to hold off on this PR a bit as it runs the risk of regressing. In its current state, it doesn't handle `netlink.ErrDumpInterrupted`. I've created an issue in the library to hopefully be able to remove `safenetlink` in the medium term: https://github.com/vishvananda/netlink/issues/1163.

**Comment by gandro** [comment]
> @pasteley I'd like to hold off on this PR a bit as it runs the risk of regressing. In its current state, it doesn't handle `netlink.ErrDumpInterrupted`. I've created an issue in the library to hopefully be able to remove `safenetlink` in the medium term: [vishvananda/netlink#1163](https://github.com/vishvananda/netlink/issues/1163).

I'm not sure I follow? Our linter _does_ complain if you call a function on `netlink.Handle` that may return `netlink.ErrDumpInterrupted`, _even_ if the handle was constructed via `safenetlink.NewHandle` introduced by this PR.

**Comment by ti-mo** [comment]
> I'm not sure I follow? Our linter _does_ complain if you call a function on `netlink.Handle` that may return `netlink.ErrDumpInterrupted`, _even_ if the handle was constructed via `safenetlink.NewHandle` introduced by this PR.

Ohhh, I see. We already have a bunch of places where Handle is used, forbidigo silenced, and an explicit retry loop added. Of course, then we can merge this as-is. Just need to figure out how to disable VF collection by default if/when we manage to get a retry mechanism added upstream. I'll spend some time on that when I make an upstream proposal.

**Review by ti-mo — APPROVED** [review]

**Comment by pasteley** [comment]
@cilium/sig-datapath ptal

**Review by smagnani96 — APPROVED** [review]
LGTM. I don't see us using the retrieved `link.Attrs().Vfs` in our codebase nowadays.
