### PR TITLE
fqdn: Add a nil check for security id lookup

### LINKED ISSUE #13881: Segfault triggered by race condition when restarting Cilium 1.8.5 while handling DNS packets and logging to cilium monitor
I deployed Cilium 1.8.5 into a GKE cluster, then deployed all https://github.com/cilium/chaos-monkeys , then restarted the Cilium pods.

Upon restart, Cilium crashed out:

```
level=info msg="Waiting until all pre-existing resources related to policy have been received" subsys=k8s-watcher
level=info msg="Initializing node addressing" subsys=daemon
level=info msg="Restored router address from node_config" file=/var/run/cilium/state/globals/node_config.h ipv4=10.4.1.185 ipv6="<nil>" subsys=node
level=info msg="Initializing kubernetes IPAM" subsys=ipam v4Prefix=10.4.1.0/24 v6Prefix="<nil>"
level=info msg="Restoring endpoints..." subsys=daemon
level=info msg="Policy Add Request" ciliumNetworkPolicy="[&{EndpointSelector:{\"matchLabels\":{\"any:name\":\"chaos-et-calls-google-fqdn-policy\",\"k8s:io.kubernetes.pod.namespace\":\"chaos-testing\"}} NodeSelector:{} Ingress:[] Egress:[{ToEndpoints:[{\"matchLabels\":{\"any:k8s-app\":\"kube-dns\",\"k8s:io.kubernetes.pod.namespace\":\"kube-system\"}}] ToRequires:[] ToPorts:[{Ports:[{Port:53 Protocol:ANY}] TerminatingTLS:<nil> OriginatingTLS:<nil> Rules:0xc00020ab60}] ToCIDR: ToCIDRSet:[] ToEntities:[] ToServices:[] ToFQDNs:[] ToGroups:[] aggregatedSelectors:[]} {ToEndpoints:[] ToRequires:[] ToPorts:[] ToCIDR: ToCIDRSet:[] ToEntities:[] ToServices:[] ToFQDNs:[{MatchName:www.google.com MatchPattern:}] ToGroups:[] aggregatedSelectors:[{LabelSelector:0xc00019da80 requirements:0xc00019db00 cachedLabelSelectorString:&LabelSelector{MatchLabels:map[string]string{reserved.none: ,},MatchExpressions:[]LabelSelectorRequirement{},}}]} {ToEndpoints:[] ToRequires:[] ToPorts:[] ToCIDR:[1.1.1.1/32] ToCIDRSet:[] ToEntities:[] ToServices:[] ToFQDNs:[] ToGroups:[] aggregatedSelectors:[{LabelSelector:0xc000f8e480 requirements:0xc000f8e500 cachedLabelSelectorString:&LabelSelector{MatchLabels:map[string]string{cidr.1.1.1.1/32: ,},MatchExpressions:[]LabelSelectorRequirement{},}}]}] Labels:[k8s:io.cilium.k8s.policy.derived-from=CiliumNetworkPolicy k8s:io.cilium.k8s.policy.name=chaos-test-et-call-fqdn-et-call-home-fqdn-policy k8s:io.cilium.k8s.policy.namespace=chaos-testing k8s:io.cilium.k8s.policy.uid=271af9a1-2b86-4c58-a295-4baf3ecf32a7] Description:}]" policyAddRequest=df36a691-1e16-11eb-98e3-42010aa80fc2 subsys=daemon
level=debug msg="Proxy stats not found when updating" PolicyID.L4="671:egress:TCP:53" containerID=e9eacff2bd datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=671 identity=21311 ipv4=10.4.1.209 ipv6= k8sPodName=chaos-testing/alexa-top-dns-645fdf7d94-84m6q subsys=endpoint
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1de784b]

goroutine 301 [running]:
github.com/cilium/cilium/daemon/cmd.(*Daemon).notifyOnDNSMsg.func3(0xc000dca380)
        /go/src/github.com/cilium/cilium/daemon/cmd/fqdn.go:546 +0x5eb
github.com/cilium/cilium/pkg/proxy/logger.NewLogRecord(0x28179c0, 0x41160c0, 0x288bc40, 0xc000aa6900, 0x23d6caf, 0x7, 0xffffff00, 0xc000eebae8, 0x5, 0x5, ...)
        /go/src/github.com/cilium/cilium/pkg/proxy/logger/logger.go:110 +0x261
github.com/cilium/cilium/daemon/cmd.(*Daemon).notifyOnDNSMsg(0xc0009b81c0, 0xbfe08eccaff5985e, 0x82228bd9, 0x3bbf8e0, 0xc000aa6900, 0xc00039dbd0, 0x10, 0xc00039dc50, 0xc, 0xc000abddd0, ...)
        /go/src/github.com/cilium/cilium/daemon/cmd/fqdn.go:509 +0xc62
github.com/cilium/cilium/pkg/fqdn/dnsproxy.(*DNSProxy).ServeDNS(0xc000abd200, 0x287e920, 0xc000a20e40, 0xc000abddd0)
        /go/src/github.com/cilium/cilium/pkg/fqdn/dnsproxy/proxy.go:569 +0x1695
github.com/miekg/dns.(*Server).serveDNS(0xc000272ff0, 0xc00092d380, 0x33, 0x33, 0xc000a20e40)
        /go/src/github.com/cilium/cilium/vendor/github.com/miekg/dns/server.go:597 +0x20b
github.com/miekg/dns.(*Server).serveTCPConn(0xc000272ff0, 0xc00031c630, 0x2880000, 0xc00000e1d0)
        /go/src/github.com/cilium/cilium/vendor/github.com/miekg/dns/server.go:520 +0x200
created by github.com/miekg/dns.(*Server).serveTCP
        /go/src/github.com/cilium/cilium/vendor/github.com/miekg/dns/server.go:432 +0x354

```

After a couple of restarts, Cilium successfully came back up.

### PR DESCRIPTION
**Pull request by aditighag**
The security id lookup could return nil if the cache
isn't initialized during endpoints restore time,
resulting in a crash.

Signed-off-by: Aditi Ghag <aditi@cilium.io>

Fixes: #13881

### CODE REVIEW

File: daemon/cmd/fqdn.go [hunk 1]
```diff
@@ -470,13 +470,15 @@ func (d *Daemon) notifyOnDNSMsg(lookupTime time.Time, ep *endpoint.Endpoint, epI
...
 				secID := d.identityAllocator.LookupIdentityByID(d.ctx, serverSecID.ID)
 				// TODO: handle IPv6
-				lr.LogRecord.DestinationEndpoint = accesslog.EndpointInfo{
-					IPv4: serverIP,
-					// IPv6:         serverEP.GetIPv6Address(),
-					Labels:       secID.Labels.GetModel(),
-					LabelsSHA256: secID.GetLabelsSHA256(),
-					Identity:     uint64(serverSecID.ID.Uint32()),
-					Port:         uint16(serverPort),
+				if secID != nil {
```
Comment (joestringer) [inline daemon/cmd/fqdn.go]: I presume this means that we will still send a log message, but it will be missing destination endpoint information.

I wonder whether instead we should just try to do a check earlier in the function for whether the identity cache is initialized, and drop the entire notification if the daemon is not ready?

@jrajahalme any thoughts on this?

**Review by joestringer — COMMENTED** [review]
I wasn't able to to reproduce the issue with an image derived from this change yet, so seems like it is likely to resolve #13881.

File: daemon/cmd/fqdn.go (hunk 1 above)
Comment (jrajahalme) [reply daemon/cmd/fqdn.go]: I presume this can happen now due to DNS proxy being initialized earlier in bootstrap, hence this should also be marked as `Fixes: #12964` and backported to 1.7., 1.8, and 1.9.

I'm fine by doing the access log, but leaving out the info we don't have yet. To that end I'd prefer setting the fields not dependent on `secID` and leaving only those out if `secID` is `nil`.

**Review by jrajahalme — CHANGES_REQUESTED** [review]

**Comment by aditighag** [comment]
test-me-please

**Comment by aditighag** [comment]
Hit an infrastructure related issue in the istio test - https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Kernel/3685/

**Comment by aditighag** [comment]
test-me-please

**Comment by aditighag** [comment]
> All the tests passed except K8s-1.18-Kernel-4.19. Hit an infrastructure related issue in the istio test - https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Kernel/3685/

Minor fix in the latest commit - 

<details>
<summary>git diff for latest commit</summary>
```

diff --git a/daemon/cmd/fqdn.go b/daemon/cmd/fqdn.go
index 47997da49..6af327618 100644
--- a/daemon/cmd/fqdn.go
+++ b/daemon/cmd/fqdn.go
@@ -475,8 +475,7 @@ func (d *Daemon) notifyOnDNSMsg(lookupTime time.Time, ep *endpoint.Endpoint, epI
                                        Identity: uint64(serverSecID.ID.Uint32()),
                                        Port:     uint16(serverPort),
                                }
-                               secID := d.identityAllocator.LookupIdentityByID(d.ctx, serverSecID.ID)
-                               if secID != nil {
+                               if secID := d.identityAllocator.LookupIdentityByID(d.ctx, serverSecID.ID); secID != nil {
                                        lr.LogRecord.DestinationEndpoint.Labels = secID.Labels.GetModel()
                                        lr.LogRecord.DestinationEndpoint.LabelsSHA256 = secID.GetLabelsSHA256()
                                }

```

</details>

**Review by christarazi — APPROVED** [review]

**Review by jibi — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
Docker ratelimiting on CI :(

**Comment by joestringer** [comment]
Given that the overall CI was green earlier except one flake, the change is simple, and the smoke tests are all green, I don't think we need to re-kick the rest of CI and gamble with dockerhub. I'm OK to merge as-is.
