### PR TITLE
On-demand policy wildcarding

### LINKED ISSUE #9996: Enabling TLS-visibility for FQDN rule breaks other FQDN rules.
**Summary:**

Specifying TLS-termination for one FQND rule breaks all other FQDN rules on the same Port.

**More detailes:**

Following @danwent 's getting started guide (https://github.com/cilium/cilium/pull/9808) to enable TLS visibility, I deployed and enabled TLS-visibility successfully for swap demo app:

1. Applied L7 policy with TLS termination:

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
description: "L7 policy with TLS"
metadata:
  name: "l7-visibility-tls"
spec:
  endpointSelector:
    matchLabels:
      org: empire
      class: mediabot
  egress:
  - toFQDNs:
    - matchName: "swapi.co"
    toPorts:
    - ports:
      - port: "443"
        protocol: "TCP"
      terminatingTLS:
        secret:
          namespace: "kube-system"
          name: "swapi-tls-data"
      originatingTLS:
        trustedCA: "ca-certificates.crt"
        secret:
          namespace: "kube-system"
          name: "tls-orig-data"
      rules:
        http:
        - {}
  - toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
          - matchPattern: "*"
```

2. Make HTTPS request to swapi.co, as per getting started guide:
```
kubectl exec -it mediabot -- curl -sL https://swapi.co/api/planets/1/
```

3. Using hubble I was able to observe HTTPS request with L7 information:
```
Jan 30 06:14:41.673 [...]: default/mediabot:46760 -> 104.31.76.248:443(https) http-request FORWARDED (HTTP/1.1 GET https://swapi.co/api/planets/1/)
```
4. Make request to https://api.twitter.com

```
kubectl exec -it mediabot -- curl -v -sL https://api.twitter.com
```
Using hubble I observe Dropped flow as expected

```
Jan 30 06:16:10.477 [...]: default/mediabot:41318 -> 104.244.42.2:443(https) Policy denied (L3) DROPPED (TCP Flags: SYN)
```

5. Modify mentioned policy to add whitelist api.twitter.com:

```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
description: "L7 policy with TLS"
metadata:
  name: "l7-visibility-tls"
spec:
  endpointSelector:
    matchLabels:
      org: empire
      class: mediabot
  egress:
  - toFQDNs:
    - matchName: "api.twitter.com"
    toPorts:
    - ports:
      - port: "443"
        protocol: "TCP"
  - toFQDNs:
    - matchName: "swapi.co"
    toPorts:
    - ports:
      - port: "443"
        protocol: "TCP"
      terminatingTLS:
        secret:
          namespace: "kube-system"
          name: "swapi-tls-data"
      originatingTLS:
        trustedCA: "ca-certificates.crt"
        secret:
          namespace: "kube-system"
          name: "tls-orig-data"
      rules:
        http:
        - {}
  - toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
          - matchPattern: "*"
```

**6. Repeat step 4 and make https request to api.twitter.com**

```
➜  cilium git:(master) kubectl exec -it mediabot -- curl -v -sL https://api.twitter.com
* Rebuilt URL to: https://api.twitter.com/
*   Trying 104.244.42.2...
* TCP_NODELAY set
* Connected to api.twitter.com (104.244.42.2) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* Unknown SSL protocol error in connection to api.twitter.com:443 
* Curl_http_done: called premature == 1
* Closing connection 0
command terminated with exit code 35

```

expected the request to be successful, instead TLS handshake fails.

7. Changing port from 443 to 8443 for swapi fqdn rule, allows api.twitter.com rule to work properly.

### PR DESCRIPTION
**Pull request by jrajahalme**
Replace the current model of mass L7 wildcarding with on-demand wildcarding to allow for redirecting some but not all selectors for a given L4 filter.

L4 filters without L7 rules are now wildcarded either when merged with L4/L7 rules, or when used by the L7 proxies.

Bpf policy lookup now always looks up both L3/L4 and L4-only rules to find out if either of them redirects to proxy. This allows elimination of additionally generated policy map entries that would otherwise needed to ensure L4-only policy redirects to the proxy in the presence of L3/L4 policies that do not redirect.

Some context for reviewing:
- The functionality of `L4Filter.CachedSelectors` has been merged into the `L4Filter.L7RulesPerEp` (which has been renamed as `L7RulesPerSelector`). This is needed to efficiently keep track of which selectors have L7 rules and which not. The latter case is represented by a nil value in the map.
- L7 proxy code dealing with `L7RulesPerEp` has been modified to threat `nil` values as L7 wildcards (DNS, Kafka, Envoy)
- L7 wildcarding rules are generated on-demand when merging a non-L7 L4 rule with a L4/L7 rule.
- `L4Filter.ToKeys()` has been renamed as `L4Filter.ToMapState` as it now returns a map (MapState) instead of just the keys. Map entries tell if the entry needs L7 redirection or not. This makes it possible for a single L4 filter to create redirects for some of the allowed security IDs, but not necessarily all of them.
- Tracking of MapState entries now relies on each CachedSelector tracked by an L4Filter to be in the L7RulesPerSelector map. nil vs. non-nil value in the map is used to determine if the new map entry needs redirection or not. This is then used to test if the proxy port value needs to be set, so that even if the L7Proxy type of the L4 filter is set, selectors without L7 rules do not generate proxy redirection in the bpf policy map.
- These changes mean that L3-dependent L7 processing in the proxy now relies on L3/L4 entries in addition to L3/L4/L7 entries in the NetworkPolicy. This required removal of some sidecar-specific code from `cilium-envoy` that was never exercised earlier due to the "mass wildcarding" model.
- `policy/selectorcache.go` required an interesting fix relating to use of interfaces as map keys (like in `L4Filter.L7RulesPerSelector` :-) 
- Policy map lookup order in the bpf datapath is changed from `L3/L4 -> L3/* -> */L4 -> */*` to `L3/L4 -> */L4 -> L3/* -> */*` as this removes the need to generate L7 wildcards for L3-only entries.
- L3/L4 keys are now supressed from the bpf policy maps if a L4-only key exists and does what L3/L4 entry would have needed to do. This removes the need to generate wildcards for L3/L4 keys when L4-only key redirects.

Fixes: #9996

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/10054)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-me-please

**Comment by raybejjani** [comment]
@jrajahalme  some jenkins happened and the GKE tests triggered for this PR. You should ignore them (as they will fail). Sorry!

File: daemon/policy_test.go [hunk 1]
```diff
@@ -364,6 +422,90 @@ func (ds *DaemonSuite) TestUpdateConsumerMap(c *C) {
...
+	expectedNetworkPolicy := &cilium.NetworkPolicy{
+		Name:             QAIPv4Addr.String(),
+		Policy:           uint64(qaBarSecLblsCtx.ID),
+		ConntrackMapName: "global",
+		IngressPerPortPolicies: []*cilium.PortNetworkPolicy{
+			{
+				Port:     80,
+				Protocol: envoy_api_v2_core.SocketAddress_TCP,
+				Rules: []*cilium.PortNetworkPolicyRule{
+					{},
```
Comment (joestringer) [inline daemon/policy_test.go:488]: Does this empty brackets denote L4 allow-all without rules?

File: pkg/envoy/server.go [hunk 2]
```diff
@@ -831,6 +836,48 @@ func getPortNetworkPolicyRule(sel policy.CachedSelector, l7Parser policy.L7Parse
...
+			wildcardFound = true
+			break
+		}
+
+		for _, id := range sel.GetSelections() {
+			remoteMap[uint64(id)] = struct{}{}
+		}
+
+		if l7 != nil {
+			log.Warning("Wildcard L4 L7DataMap has L7 rules!")
```
Comment (joestringer) [inline pkg/envoy/server.go]: Can we get more info here? From my reading this is basically not possible to hit right now but if someone ever did hit it, it might be useful to have some kind of selector info to help debug?

File: pkg/envoy/server.go [hunk 3]
```diff
@@ -855,32 +902,43 @@ func getDirectionNetworkPolicy(l4Policy policy.L4PolicyMap, policyEnforced bool)
...
 		// causing all the applicable rules to be evaluated instead.
 		canShortCircuit := true
-		for sel, l7 := range l4.L7RulesPerEp {
-			rule, cs := getPortNetworkPolicyRule(sel, l4.L7Parser, l7)
-			if !cs {
-				canShortCircuit = false
-			}
+
+		if l4.Port == 0 {
+			// Wildcard L4 rule, must generate L7 allow-all in case there are other
```
Comment (joestringer) [inline pkg/envoy/server.go]: nit: 
```suggestion
			// L3-only rule, must generate L7 allow-all in case there are other
```

I feel like we've always talked about l3-only, l4-only, l3-dependent-l7 (L3+L4+L7), l4-dependent-l7 (L4+L7) as the standard way to think about these rules.

**Review by raybejjani — APPROVED** [review]
One straightforward change to the dns tests (sent offline) but LGTM otherwise.

One thing I noticed was that this policy resolved to a L7 wildcard in the proxy. It's "correct" but master handled it as if the L3/L4 rule didn't exist. This is exactly the point of this PR, right?
```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: "tofqdn-dns-visibility"
spec:
  endpointSelector:
    matchLabels:
      any:org: alliance
  egress:
  - toEndpoints:
    - matchLabels:
       "k8s:io.kubernetes.pod.namespace": kube-system
       "k8s:k8s-app": kube-dns
    toPorts:
      - ports:
         - port: "53"
           protocol: ANY

  - toEndpoints:
    - matchLabels:
       "k8s:io.kubernetes.pod.namespace": kube-system
       "k8s:k8s-app": kube-dns
    toPorts:
      - ports:
         - port: "53"
           protocol: ANY
        rules:
          dns:
            - matchPattern: "google.com"
```

File: pkg/fqdn/dnsproxy/proxy_test.go [hunk 4]
```diff
@@ -550,4 +550,32 @@ func (s *DNSProxyTestSuite) TestFullPathDependence(c *C) {
 	allowed, err = s.proxy.CheckAllowed(epID3, 53, dstID2, "example.com")
 	c.Assert(err, Equals, nil, Commentf("Error when checking allowed"))
 	c.Assert(allowed, Equals, false, Commentf("request was allowed when it should be rejected"))
+
+	// | EP3  | DstID1 |      53 | *    |
```
Comment (joestringer) [inline pkg/fqdn/dnsproxy/proxy_test.go]: Please update the table at the start of this function to describe this case in more detail, so it's easier to get a summary of how this compares to the other test cases here.

Comment (joestringer) [reply pkg/fqdn/dnsproxy/proxy_test.go]: Actually, this line doesn't make sense in context of the current batch of tests at all. Similarly on line 571.

Comment (joestringer) [reply pkg/fqdn/dnsproxy/proxy_test.go]: Can we just expand the set of tests to include all the cases at the start to avoid this confusion? Or are you specifically trying to test incremental policy, in which case would it help to have a separate test for incremental testing?

**Comment by jrajahalme** [comment]
@raybejjani @joestringer Sorry for the rebase if you happened to be in a middle of a review. However, the unit test changes should be less confusing now, as I reverted the changes I had made to the test *input*. Also added the fix @raybejjani sent me offline.

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
@raybejjani Yes, the intent was to add the wildcard rule to an L3/L4 rule when merging with an L7 rule. Functionally, master should behave the same, but I'm not 100% sure it does (if not, then this would also be a bug fix). For the example you gave, are you saying that master redirects port 53 to the dns proxy, which then *only allows requests for `google.com`*? If so, I'd say master is behaving badly.

File: pkg/policy/distillery_test.go [hunk 5]
```diff
@@ -424,26 +420,24 @@ func Test_MergeRules(t *testing.T) {
 		{3, api.Rules{rule____NoAllow, rule____NoAllow, rule____NoAllow, rule__L4__Allow, ruleL3____Allow}, MapState{mapKeyAllow___L4: mapEntryL7None_, mapKeyAllowFoo__: mapEntryL7None_}},
 		{4, api.Rules{rule____NoAllow, rule____NoAllow, ruleL3L4__Allow, rule____NoAllow, rule____NoAllow}, MapState{mapKeyAllowFooL4: mapEntryL7None_}},
 		{5, api.Rules{rule____NoAllow, rule____NoAllow, ruleL3L4__Allow, rule____NoAllow, ruleL3____Allow}, MapState{mapKeyAllowFooL4: mapEntryL7None_, mapKeyAllowFoo__: mapEntryL7None_}},
-		{6, api.Rules{rule____NoAllow, rule____NoAllow, ruleL3L4__Allow, rule__L4__Allow, rule____NoAllow}, MapState{mapKeyAllow___L4: mapEntryL7None_}},                                    // Differs from spreadsheet(!)
+		{6, api.Rules{rule____NoAllow, rule____NoAllow, ruleL3L4__Allow, rule__L4__Allow, rule____NoAllow}, MapState{mapKeyAllowFooL4: mapEntryL7None_, mapKeyAllow___L4: mapEntryL7None_}}, // Differs from spreadsheet(!)??
```
Comment (joestringer) [inline pkg/policy/distillery_test.go]: In this particular case it doesn't differ from the spreadsheet any more with this change. Would you mind double-checking the rest of these distillery test changes against the spreadsheet?

https://docs.google.com/spreadsheets/d/1WANIoZGB48nryylQjjOw6lKjI80eVgPShrdMTMalLEw/edit#gid=0

File: pkg/policy/l4_filter_test.go [hunk 6]
```diff
@@ -243,22 +249,15 @@ func (ds *PolicyTestSuite) TestMergeAllowAllL3AndShadowedL7(c *C) {
...
 	expected := L4PolicyMap{"80/TCP": &L4Filter{
-		Port:            80,
-		Protocol:        api.ProtoTCP,
-		U8Proto:         6,
-		allowsAllAtL3:   true,
-		CachedSelectors: CachedSelectorSlice{wildcardCachedSelector},
-		L7Parser:        "http",
-		L7RulesPerEp: L7DataMap{
-			wildcardCachedSelector: &PerEpData{
+		Port:     80,
```
Comment (joestringer) [inline pkg/policy/l4_filter_test.go:253]: Was the previous comment above this misleading or wrong? It seems like it's trying to provide additional guidance on how to interpret the testing operations below.

File: pkg/policy/resolve.go [hunk 7]
```diff
@@ -125,10 +125,10 @@ func (p *selectorPolicy) DistillPolicy(policyOwner PolicyOwner) *EndpointPolicy
 	// computeDesiredL4PolicyMapEntires() call finishes may
 	// already be applied to the PolicyMapState, specifically:
 	//
-	// - PolicyMapChanges may contain an addition of an entry that
+	// - policyMapChanges may contain an addition of an entry that
 	//   is already added to the PolicyMapState
 	//
-	// - PolicyMapChanges may congtain a deletion of an entry that
+	// - policyMapChanges may congtain a deletion of an entry that
```
Comment (joestringer) [inline pkg/policy/resolve.go]:
```suggestion
	// - policyMapChanges may contain a deletion of an entry that
```

File: pkg/policy/resolve.go [hunk 8]
```diff
@@ -154,26 +154,33 @@ func (p *EndpointPolicy) computeDesiredL4PolicyMapEntries() {
...
 	}
 }
 
+// ConsumeMapChanges transfers the changes from MapChanges to the caller,
+// locking the selector cache to make sure concurrent identity updates
+// have completed.
+func (p *EndpointPolicy) ConsumeMapChanges() (adds, deletes MapState) {
+	p.selectorPolicy.SelectorCache.mutex.Lock()
+	defer p.selectorPolicy.SelectorCache.mutex.Unlock()
+	return p.policyMapChanges.consumeMapChanges()
```
Comment (joestringer) [inline pkg/policy/resolve.go:181]: Is this a potential bugfix?

File: pkg/policy/l4.go [hunk 9]
```diff
@@ -319,9 +309,10 @@ func (l4 *L4Filter) IdentitySelectionUpdated(selector CachedSelector, selections
 		logfields.DeletedPolicyID:  deleted,
 	}).Debug("identities selected by L4Filter updated")
 
-	// Skip updates on filter that wildcards L3.
-	// This logic mirrors the one in ToKeys().
-	if l4.AllowsAllAtL3() && !l4.HasL3DependentL7Rules() {
+	// Skip updates on wildcard selectors, as datapath and L7
+	// proxies do not need enumeration of all ids for L3 wildcard.
```
Comment (joestringer) [inline pkg/policy/l4.go:349]: I guess the implication here is that if L3 is wildcarded then we already calculated the L4-only / L4-dependent L7 changes necessary for the datapath, so the fact that some new identity showed up for an L3 doesn't make any difference to the eventual policy.

File: pkg/policy/l4.go [hunk 10]
```diff
@@ -373,20 +365,24 @@ func (l7 L7DataMap) GetRelevantRulesForKafka(nid identity.NumericIdentity) []api
 
 	for cs, r := range l7 {
 		if cs.IsWildcard() || cs.Selects(nid) {
+			if r == nil {
+				r = &PerSelectorPolicy{L7Rules: api.L7Rules{Kafka: []api.PortRuleKafka{}}}
```
Comment (joestringer) [inline pkg/policy/l4.go:405]: nit: We should probably standardize these kinds of `AllowAllKafka` representations into public variables to make it more clear and ensure consistency across different parts of the code.

File: pkg/policy/l4.go [hunk 11]
```diff
@@ -485,32 +479,44 @@ func createL4Filter(policyCtx PolicyContext, peerEndpoints api.EndpointSelectorS
...
 		}
 	}
 
 	return l4, nil
 }
 
+func (l4 *L4Filter) removeSelectors(selectorCache *SelectorCache, all bool) {
+	selectors := make(CachedSelectorSlice, 0, len(l4.L7RulesPerSelector))
+	for cs, l7 := range l4.L7RulesPerSelector {
+		if all || l7 == nil {
```
Comment (joestringer) [inline pkg/policy/l4.go]: This function adds a bool for `all` but AFAICT the `false` version is never used. I also can't quite wrap my head around why we don't release references in the selectorCache for selectors used with L7 rules assuming that we ever passed false. Do we need this extra complexity?

File: pkg/policy/mapstate.go [hunk 12]
```diff
@@ -67,15 +67,40 @@ type MapStateEntry struct {
 	// The proxy port, in host byte order.
 	// If 0 (default), there is no proxy redirection for the corresponding
 	// Key.
+	// Values less than 1024 may be used for internal purposes, but are never used
+	// as actual proxy listening port numbers.
```
Comment (joestringer) [inline pkg/policy/mapstate.go]: Is there any code that ensures this constraint?

I guess if we're only using 1, then it's unlikely we're going to cause problems with... *\*checks notes\**... the deprecated TCPMUX protocol? ;-)

File: pkg/policy/l4.go (hunk 10 above)
Comment (joestringer) [reply pkg/policy/l4.go:405]: nit2: Seems like we sanitized the rule used here before, not sure if there was a specific reason that was necessary..?

File: pkg/policy/repository_test.go [hunk 13]
```diff
@@ -1280,54 +1245,50 @@ func (ds *PolicyTestSuite) TestWildcardL4RulesEgress(c *C) {
 	repo.Mutex.RLock()
 	defer repo.Mutex.RUnlock()
 
-	policy, err := repo.ResolveL4EgressPolicy(ctx)
+	logBuffer := new(bytes.Buffer)
+	policy, err := repo.ResolveL4EgressPolicy(ctx.WithLogger(logBuffer))
 	c.Assert(err, IsNil)
 
+	// Bar1 should not be forwarded to the proxy, but if it is (e.g., for visibility),
+	// the L3/L4 allow should pass it without a L7 wildcard.
```
Comment (joestringer) [inline pkg/policy/repository_test.go]: nit:
```suggestion
	// the L3/L4 allow should pass it without an explicit L7 wildcard.
```

File: pkg/policy/rule_test.go [hunk 14]
```diff
@@ -1962,12 +1973,27 @@ func (ds *PolicyTestSuite) TestL3L4L7Merge(c *C) {
...
+		Port: 80, Protocol: api.ProtoTCP, U8Proto: 6,
+		L7Parser: "http",
+		L7RulesPerSelector: L7DataMap{
+			cachedSelectorC: nil,
+			wildcardCachedSelector: &PerSelectorPolicy{
+				L7Rules: api.L7Rules{
+					HTTP: []api.PortRuleHTTP{{Path: "/", Method: "GET"}},
+				},
+			},
+			cachedSelectorC: nil,
```
Comment (joestringer) [inline pkg/policy/rule_test.go]: nit: Looks like you're specifying `cachedSelectorC` here twice?

File: test/runtime/Policies.go [hunk 15]
```diff
@@ -528,31 +532,17 @@ var _ = Describe("RuntimePolicies", func() {
...
-		// to httpd1 from app3. This is what tests L3-dependent L7 policy is applied
-		// correctly.
-		// * no increase in requests denied by the proxy.
-		// * two more corresponding responses forwarded / received to the aforementioned requests due to policy
-		// allowing connectivity via http / http6.
-		checkProxyStatistics(app3EndpointID, 6, 8, 2, 6, 6)
+		// Since policy allows connectivity on L3 from app3 to httpd2, and such
+		// packets are not forwarded to the proxy, we expect no changes in proxy
+		// stats.
+		checkProxyStatistics(app3EndpointID, 2, 4, 2, 2, 2)
```
Comment (joestringer) [inline test/runtime/Policies.go:545]: :tada:

**Comment by jrajahalme** [comment]
test-me-please

File: pkg/policy/rule.go [hunk 16]
```diff
@@ -58,46 +58,44 @@ func (r *rule) String() string {
 	return fmt.Sprintf("%v", r.EndpointSelector)
 }
 
-func (l4 *L4Filter) mergeCachedSelectors(from *L4Filter, selectorCache *SelectorCache) {
-	for _, cs := range from.CachedSelectors {
-		if l4.CachedSelectors.Insert(cs) {
-			// Update selector owner to the existingFilter
-			selectorCache.ChangeUser(cs, from, l4)
+func (epd *PerSelectorPolicy) appendL7WildcardRules(ctx *SearchContext) *PerSelectorPolicy {
+	switch {
```
Comment (joestringer) [inline pkg/policy/rule.go:63]: nits: what about the default case, including go extensions?

Comment (joestringer) [reply pkg/policy/rule.go:63]: Looking at the other L7 handling piece in this file, I guess we don't support merging for such L7 rules. That said I think it's probably worth raising at least a policy trace line, but probably also a warning of some kind that you're doing something not-supported in that case?

**Review by joestringer — APPROVED** [review]
Mostly nits and questions to make sure I'm following correctly below, and a couple of notes where we might be able to help subsequent readers of the code to understand.

We should double-check the google doc corresponding to distillery_test, at least the first case now conforms with the doc.

Also some of the new L7 rules handling statements don't handle default case in any way, which I guess results in silent ignorance of things that the current code wasn't thought through for. Might be good to add some kind of message to those cases?

None of the above are major hold backs. Only other remaining question I have is whether we've been able to run this in non-trivial situations and observe things like the selectorCache to ensure that we got the reference counting correct.

File: pkg/fqdn/dnsproxy/proxy_test.go (hunk 4 above)
Comment (joestringer) [reply pkg/fqdn/dnsproxy/proxy_test.go]: I guess this may have been addressed already by Ray's patch.

File: daemon/policy_test.go (hunk 1 above)
Comment (jrajahalme) [reply daemon/policy_test.go:488]: It denotes L4 allow-all without any L3 restrictions (nil Remotepolicies as well as nil L7)

File: pkg/envoy/server.go (hunk 2 above)
Comment (jrajahalme) [reply pkg/envoy/server.go]: Will add the selector and the l7 rules to the message.

File: pkg/envoy/server.go (hunk 3 above)
Comment (jrajahalme) [reply pkg/envoy/server.go]: Will change.

File: pkg/policy/distillery_test.go (hunk 5 above)
Comment (jrajahalme) [reply pkg/policy/distillery_test.go]: Checked the changed lines against the spreadsheet. The cases 12-15 all have an L4-only rule redirecting to proxy, and an L3/L4 rule that is allowed without redirecting. Now the latter case will not be sent to the proxy as it is not required for policy enforcement, but this may be problematic for a visibility policy?

Comment (jrajahalme) [reply pkg/policy/distillery_test.go]: Updated the comments to reflect the above!

File: pkg/policy/l4.go (hunk 9 above)
Comment (jrajahalme) [reply pkg/policy/l4.go:349]: Right. We generate the L4-only key (L3=0) regardless the actual IDs the wildcard selector maps to.

File: pkg/policy/l4.go (hunk 10 above)
Comment (jrajahalme) [reply pkg/policy/l4.go:405]: Could also move to make Kafka proxy accept `nil` instead?

IMO Sanitizing would not change this rule. egress Kafka is not supported, but here the call comes from the already running proxy.

File: pkg/policy/l4.go (hunk 11 above)
Comment (jrajahalme) [reply pkg/policy/l4.go]: This is a remnant from an intermediate state of the code, will clean it up!

File: pkg/policy/l4_filter_test.go (hunk 6 above)
Comment (jrajahalme) [reply pkg/policy/l4_filter_test.go:253]: Now that the wildcard rule is explicitly generated, the explanation was not entirely correct anymore, and IMO not needed.

Comment (jrajahalme) [reply pkg/policy/l4_filter_test.go:253]: Note: I don't know where the L7 wildcard would have been created for the proxy before this change. Maybe it worked due to L4-only allow possibly NOT redirecting to the proxy at all?

File: pkg/policy/mapstate.go (hunk 12 above)
Comment (jrajahalme) [reply pkg/policy/mapstate.go]: All callers compare the entry against 0 value, so the 1 value is actually not used for comparisons. Will enforce this by un-exporting the `RedirectEntry`.

Comment (jrajahalme) [reply pkg/policy/mapstate.go]: Also changed the comment to indicate that any non-zero value signifies a redirect.

File: pkg/policy/repository_test.go (hunk 13 above)
Comment (jrajahalme) [reply pkg/policy/repository_test.go]: Done.

File: pkg/policy/resolve.go (hunk 7 above)
Comment (jrajahalme) [reply pkg/policy/resolve.go]: Fixed, thanks!

File: pkg/policy/resolve.go (hunk 8 above)
Comment (jrajahalme) [reply pkg/policy/resolve.go:181]: Not sure. It is needed now, but likely not if all L4 entries redirected before if there was an L7 on the same port.

File: pkg/policy/rule.go (hunk 16 above)
Comment (jrajahalme) [reply pkg/policy/rule.go:63]: go extensions do not need a L7 rule to be triggered as the parser type/id is explicitly invoked in the policy. Even if no rules acts as a wildcard, an empty set would need to be appended here. Will fix!

File: pkg/policy/rule_test.go (hunk 14 above)
Comment (jrajahalme) [reply pkg/policy/rule_test.go]: Not needed, will remove the other!

**Comment by jrajahalme** [comment]
test-me-please

File: pkg/policy/l4.go (hunk 10 above)
Comment (joestringer) [reply pkg/policy/l4.go:405]: Well, it's a debate with Kafka whether to make any further changes given the Envoy support for that protocol now..

File: pkg/fqdn/dnsproxy/proxy_test.go (hunk 4 above)
Comment (raybejjani) [reply pkg/fqdn/dnsproxy/proxy_test.go]: yup, that was exactly my request. It should declare everything up top now and only try the new cases at the end.

**Comment by raybejjani** [comment]
@jrajahalme Changes (still) look good to me.

>  For the example you gave, are you saying that master redirects port 53 to the dns proxy, which then only allows requests for google.com? If so, I'd say master is behaving badly.

Yup! master is behaving badly. For that example, talking to kube-dns only allows google.com lookups despite the implicit wildcard. Talking to 1.1.1.1 only allows cloudhmar.com (which is correct). So, +1 bugfix!

**Comment by jrajahalme** [comment]
test-me-please

File: pkg/policy/rule.go (hunk 16 above)
Comment (jrajahalme) [reply pkg/policy/rule.go:63]: Added a commit to address this :-)

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
@joestringer Added a note to the description about the bpf changes added in a new commit.

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Changed bpf datapath policy lookup order from:
L3/L4 -> L3/* -> */L4 -> */*
to:
L3/L4 -> */L4 -> L3/* -> */*

This helps redirecting to the proxies in visibility cases without playing with L3-only map entries.

Additionally, generation of L3/L4 keys is suppressed if L4-only key already does what L3/L4 would need to be doing (considering also that L3/L4 would need to redirect if */L4 redirects).

**Comment by jrajahalme** [comment]
Changed bpf datapath policy lookup order from:
L3/L4 -> L3/* -> */L4 -> */*
to:
L3/L4 -> */L4 -> L3/* -> */*

This helps redirecting to the proxies in visibility cases without playing with L3-only map entries.

Additionally, generation of L3/L4 keys is suppressed if L4-only key already does what L3/L4 would need to be doing (considering also that L3/L4 would need to redirect if */L4 redirects).

File: pkg/policy/l4.go [hunk 17]
```diff
@@ -185,6 +185,8 @@ type L4Filter struct {
 	Protocol api.L4Proto `json:"protocol"`
 	// U8Proto is the Protocol in numeric format, or 0 for NONE
 	U8Proto u8proto.U8proto `json:"-"`
+	// wildcard is the cached selector representing a wildcard in this filter, if any.
```
Comment (joestringer) [inline pkg/policy/l4.go:188]: Might be helpful for future developers to note what this means in terms of higher-layer policies, which cases this wildcard field would be set, etc.

File: pkg/policy/l4.go [hunk 18]
```diff
@@ -256,7 +256,28 @@ func (l4 *L4Filter) ToMapState(direction trafficdirection.TrafficDirection) MapS
...
+		// summary, if have both L3/L4 and L4-only keys:
+		//
+		// L3/L4        L4-only      Skip generating L3/L4 key
+		// redirect     no redirect  no   (this case tested below)
+		// no redirect  no redirect  yes  (same effect)
+		// redirect     redirect     yes  (same effect)
+		// no redirect  redirect     yes  (must redirect if L4-only redirects)
+		//
+		// have wildcard?        this is a L3L4 key?  not the "no" case?
+		if l4.wildcard != nil && cs != l4.wildcard && !(l7 != nil && wildcardL7Policy == nil) {
```
Comment (joestringer) [inline pkg/policy/l4.go:284]: Is it possible to demonstrate this specific line of functionality concisely with a unit test as well?

There's a couple of other cases not mentioned in the table immediately above, which is the presence (or lack thereof) of an l4-only rule at all, which is what I think the first term of the conditional statement here is checking.

Also want to make sure that this is handling correctly while iterating the `l4.L7RulesPerSelector` entry for the L4-only filter case. (EDIT: Ah, that's the `cs != l4.wildcard` case, OK).

**Review by joestringer — CHANGES_REQUESTED** [review]
Couple of other minor comments on the new pieces.

File: pkg/policy/l4.go [hunk 19]
```diff
@@ -256,7 +256,28 @@ func (l4 *L4Filter) ToMapState(direction trafficdirection.TrafficDirection) MapS
...
+			continue
```
Comment (joestringer) [inline pkg/policy/l4.go:292]: Is there an appropriate way to log the skipping here? I'm concerned that if this silently discards some map entry generation then in future we'll be wondering where it went.

File: pkg/policy/l4.go [hunk 20]
```diff
@@ -256,7 +256,28 @@ func (l4 *L4Filter) ToMapState(direction trafficdirection.TrafficDirection) MapS
...
+
 	for cs, l7 := range l4.L7RulesPerSelector {
+		// Skip generating L3/L4 keys if L4-only key (for the same L4 port and
+		// protocol) has the same effect w.r.t. redirecting to the proxy or not,
+		// considering that L3/L4 key should redirect if L4-only key does. In
+		// summary, if have both L3/L4 and L4-only keys:
+		//
+		// L3/L4        L4-only      Skip generating L3/L4 key
+		// redirect     no redirect  no   (this case tested below)
+		// no redirect  no redirect  yes  (same effect)
```
Comment (joestringer) [inline pkg/policy/l4.go:279]: Does `l4.L7RulesPerSelector` have an entry for these cases where there is no redirect? ie are we actually handling that case in this loop?

Comment (joestringer) [reply pkg/policy/l4.go:279]: Technically I think we could still install the l3/l4 key in this case and it would save one map lookup for packets that match the l3/l4 policy on the dataplane, but we can probably optimize this later.

File: pkg/policy/distillery_test.go [hunk 21]
```diff
@@ -420,16 +385,16 @@ func Test_MergeRules(t *testing.T) {
...
-		{13, api.Rules{rule____NoAllow, rule__L4L7Allow, ruleL3L4__Allow, rule____NoAllow, ruleL3____Allow}, MapState{mapKeyAllow___L4: mapEntryL7Proxy, mapKeyAllowFooL4: mapEntryL7None_, mapKeyAllowFoo__: mapEntryL7None_}}, // Differs from spreadsheet(!) L3L4 does not redirect
-		{14, api.Rules{rule____NoAllow, rule__L4L7Allow, ruleL3L4__Allow, rule__L4__Allow, rule____NoAllow}, MapState{mapKeyAllowFooL4: mapEntryL7None_, mapKeyAllow___L4: mapEntryL7Proxy}},                                    // Differs from spreadsheet(!), L3L4 not going to proxy (not required, but maybe problematic for a visibility policy?)
-		{15, api.Rules{rule____NoAllow, rule__L4L7Allow, ruleL3L4__Allow, rule__L4__Allow, ruleL3____Allow}, MapState{mapKeyAllow___L4: mapEntryL7Proxy, mapKeyAllowFoo__: mapEntryL7None_, mapKeyAllowFooL4: mapEntryL7None_}}, // Differs from spreadsheet(!) L3L4 does not redirect
+		{12, api.Rules{rule____NoAllow, rule__L4L7Allow, ruleL3L4__Allow, rule____NoAllow, rule____NoAllow}, MapState{mapKeyAllow___L4: mapEntryL7Proxy}},                                    // identical L3L4 entry suppressed
```
Comment (joestringer) [inline pkg/policy/distillery_test.go]: The comment for these ones says `identical`, but this case is the L4-L7 rule overriding the L3+L4(no-L7).

**Review by joestringer — APPROVED** [review]
Few more minor nits, nothing consequential. Consider following up separately afterwards on these points.

File: pkg/policy/l4.go (hunk 17 above)
Comment (jrajahalme) [reply pkg/policy/l4.go:188]:
```
	// wildcard is the cached selector representing a wildcard in this filter, if any,
	// This is nil when none of the selectors in 'L7RulesPerSelector' is a wildcard.
	// When there is a wildcard selector in 'L7RulesPerSelector' this is set to that
	// same selector, which can then be used as a map key to find the correspondng L7
	// policy.
```

File: pkg/policy/l4.go (hunk 18 above)
Comment (jrajahalme) [reply pkg/policy/l4.go:284]: The table driven cases of `distillery_test.go` cover this line. I started with the 'no' lines for non-existing L4-only cases, but took it away. I'll put them back :-)

File: pkg/policy/l4.go (hunk 19 above)
Comment (jrajahalme) [reply pkg/policy/l4.go:292]: Good point, I'll add a debug line. Will change "ToKeys" to "ToMapState" also in the debug messages.

File: pkg/policy/l4.go (hunk 20 above)
Comment (jrajahalme) [reply pkg/policy/l4.go:279]: As one of the changes in this PR overall, `l4.L7RulesPerSelector` now has an entry also for non-redirects, with `nil` value.

On the second point, yes we can do that, but the effect is now smaller due to the change in the lookup order in the datapath.

File: pkg/policy/distillery_test.go (hunk 21 above)
Comment (jrajahalme) [reply pkg/policy/distillery_test.go]: Historical reasons :-) I used to 1st convert a non-redirect case to a redirect case when needed, and then remove redundant L3L4 cases. These are now done in one step. I'll update the comment(s).

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
Another VM provisioning fail due to timeout.

**Comment by jrajahalme** [comment]
Have to rebase again for bpf bindata conflict.

**Comment by jrajahalme** [comment]
Adding a commit that bumps Jenkins timeouts.

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
No change, but had to rebase due to `daemon/bpf.sha` (aka bindata).

**Comment by jrajahalme** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]
I've reviewed this PR in terms of risk merging this late and after longer evaluation I'm OK to merge it. I think it's borderline and we should avoid any such invasive PR this late in the cycle but the alternative is not much better given we expect this to become a major use case for Cilium.

**Comment by tgraf** [comment]
Great work in preparing this in time for the release @jrajahalme
