### PR TITLE
ipcache: Fix handling of endpoint IP events

### LINKED ISSUE #3976: Shift ipcache listeners list to ipcache package
These could be managed inside `pkg/ipcache` rather than in the daemon:

https://github.com/cilium/cilium/blob/7b5d362d2cdb241cd320b5f1303066bf152f5bb1/daemon/daemon.go#L1114-L1118

### LINKED ISSUE #4798: Can't find IP in NPHDS cache
This is killing my agent regularly.

```
level=fatal msg="Can't find IP in NPHDS cache" identity=4 ipAddr=10.2.3.140 modification=Delete
```

### LINKED ISSUE #4803: Envoy update fails with NACK because of duplicate NPHDS entry
Envoy update fails with a NACK, due to duplicate NPHDS entries:
```
2018-07-10T10:25:36.551683606Z level=warning msg="[external/envoy/source/common/config/grpc_mux_impl.cc:218] gRPC config for type.googleapis.com/cilium.NetworkPolicyHosts update rejected: NetworkPolicyHosts: Duplicate host entry '10.10.0.213' for policy 3, already mapped to 3" subsys=envoy-upstream threadID=5218
```
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1207/consoleFull
[9acb0442_K8sValidatedServicesTest_Bookinfo_Demo_Tests_bookinfo_demo.zip](https://github.com/cilium/cilium/files/2180890/9acb0442_K8sValidatedServicesTest_Bookinfo_Demo_Tests_bookinfo_demo.zip)

### PR DESCRIPTION
**Pull request by rlenglet**
Move the slice of ipcache listeners from `Daemon` into `IPCache`.
Factorize and encapsulate the handling of listeners into `IPCache`'s `Upsert` and `Delete` methods to reduce the complexity of callers.

Modify the signature of the `OnIPIdentityCacheChange` method in the `IPIdentityMappingListener` interface.
Specify that the given IP is always in CIDR form, with a prefix length, even when it represents an endpoint IP.
Use stronger types in the signature to clarify that only the identity and host IP associated with the CIDR may be modified.

Fix the `Upsert` and `Delete` to handle all cases of CIDR shadowing by endpoint IP:

- If inserting a new CIDR that is shadowed by an existing endpoint IP, don't callback the listeners about the insert.
- If inserting a new endpoint IP that is shadowing an existing CIDR, notify the listeners of an update of the identity associated with the CIDR, instead of an insert. If the shadowed CIDR and the endpoint IP are associated with the same identity, don't callback.
- If deleting a CIDR that was shadowed by an endpoint IP, don't callback the listeners about the delete.
- If deleting an endpoint IP that was shadowing a CIDR, notify the listeners of an update of the identity associated with the CIDR, instead of a delete. If the shadowed CIDR and the endpoint IP were associated with the same identity, don't callback.

In `Upsert`, when updating an IP's identity, delete the old identity from the identity-to-IP map.

Cache the mappings from endpoint IP / CIDR to host IP (maybe `nil`), in order to detect when the host IP for an endpoint changes.
Don't bypass the ipcache listener notifications when the host IP changes but the identity is identical.

Fixes: https://github.com/cilium/cilium/issues/4803
Fixes: https://github.com/cilium/cilium/issues/4798
Fixes: #3976

Signed-off-by: Romain Lenglet <romain@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/4810)

### CODE REVIEW

**Comment by rlenglet** [comment]
tests/10-proxy.sh passes. This is still WIP because I need to fix the unit tests.

**Comment by rlenglet** [comment]
Unit tests are passing.
Will run several CI builds.

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
Successful CI build:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4844/

**Comment by rlenglet** [comment]
test-me-please

File: pkg/ipcache/ipcache.go [hunk 1]
```diff
@@ -180,77 +189,193 @@ func allowOverwrite(existing, new Source) bool {
...
 		case net.IPv6len * 8:
 			refPrefixLength(ipc.v6PrefixLengths, pl)
 		case net.IPv4len * 8:
 			refPrefixLength(ipc.v4PrefixLengths, pl)
 		}
+
+		ones, bits := cidr.Mask.Size()
+		if ones == bits {
+			if _, endpointIPFound := ipc.ipToIdentityCache[cidr.IP.String()]; endpointIPFound {
+				scopedLog.Info("Upserting CIDR shadowed by endpoint IP")
```
Comment (tgraf) [inline pkg/ipcache/ipcache.go]: Let's make this info message more readable for an end user:
`Ignoring CIDR to identity mapping as it would shadow an endpoint IP`

File: pkg/ipcache/ipcache.go [hunk 2]
```diff
@@ -180,77 +189,193 @@ func allowOverwrite(existing, new Source) bool {
...
+			IP:   endpointIP,
+			Mask: net.CIDRMask(bits, bits),
+		}
+
+		// Check whether the upserted endpoint IP will shadow that CIDR, and
+		// replace its mapping with the listeners if that was the case.
+		if !found {
+			if cidrIdentity, cidrFound := ipc.ipToIdentityCache[cidr.String()]; cidrFound {
+				if cidrIdentity.ID != newIdentity.ID {
+					scopedLog.Info("Upserting endpoint IP shadowing CIDR")
```
Comment (tgraf) [inline pkg/ipcache/ipcache.go]: `New endpoint IP started shadowing existing CIDR to identity mapping`

File: pkg/ipcache/ipcache.go [hunk 3]
```diff
@@ -180,77 +189,193 @@ func allowOverwrite(existing, new Source) bool {
...
+					oldIdentity = &cidrIdentity.ID
+				} else {
+					// The endpoint IP and the CIDR are associated with the
+					// same identity. Nothing changes for the listeners.
+					callbackListeners = false
```
Comment (tgraf) [inline pkg/ipcache/ipcache.go]: This seems wrong as the endpoint IP based mapping can have a different hostIP that needs to be plumbed.

File: pkg/ipcache/ipcache.go [hunk 4]
```diff
@@ -180,77 +189,193 @@ func allowOverwrite(existing, new Source) bool {
...
+			unrefPrefixLength(ipc.v6PrefixLengths, pl)
+		case net.IPv4len * 8:
+			unrefPrefixLength(ipc.v4PrefixLengths, pl)
+		}
+
+		// Check whether the deleted CIDR was shadowed by an endpoint IP. In
+		// this case, skip calling back the listeners since they don't know
+		// about its mapping.
+		if _, endpointIPFound := ipc.ipToIdentityCache[cidr.IP.String()]; endpointIPFound {
+			scopedLog.Info("Deleting CIDR shadowed by endpoint IP")
```
Comment (tgraf) [inline pkg/ipcache/ipcache.go]: Why does this need a info message?

File: pkg/ipcache/ipcache.go [hunk 5]
```diff
@@ -180,77 +189,193 @@ func allowOverwrite(existing, new Source) bool {
...
+		cidr = &net.IPNet{
+			IP:   endpointIP,
+			Mask: net.CIDRMask(bits, bits),
+		}
+
+		// Check whether the deleted endpoint IP was shadowing that CIDR, and
+		// restore its mapping with the listeners if that was the case.
+		if cidrIdentity, cidrFound := ipc.ipToIdentityCache[cidr.String()]; cidrFound {
+			if cidrIdentity.ID != cachedIdentity.ID {
+				scopedLog.Info("Deleting endpoint IP shadowing CIDR, restoring CIDR")
```
Comment (tgraf) [inline pkg/ipcache/ipcache.go]: Removal of endpoint IP revives shadowed CIDR to identity mapping

File: pkg/ipcache/ipcache.go [hunk 6]
```diff
@@ -180,77 +189,193 @@ func allowOverwrite(existing, new Source) bool {
...
+				cacheModification = Upsert
+				oldIdentity = &cachedIdentity.ID
+				newIdentity = cidrIdentity
+			} else {
+				// The endpoint IP and the CIDR were associated with the same
+				// identity. Nothing changes for the listeners.
+				callbackListeners = false
```
Comment (tgraf) [inline pkg/ipcache/ipcache.go]: This needs to take into account a potential change in the hostIP as well. Otherwise we may continue to encap.

**Review by tgraf — CHANGES_REQUESTED** [review]
Great change and I understand the fix of detecting shadowed CIDRs.

I don't understand yet how this fixes #4808 as the listener update is only skipped if the identity is already equal. In the commit message it says:

```
If inserting a new endpoint IP that is shadowing an existing
CIDR, notify the listeners of an update of the identity associated
with the CIDR, instead of an insert.
```

Where is the code that does that?

File: pkg/ipcache/ipcache.go (hunk 3 above)
Comment (rlenglet) [reply pkg/ipcache/ipcache.go]: This is not worse than the current behavior. Currently, if we call `Upsert` with the same IP and same ID, but a different host IP, the listeners won't be called back either.

My take is that this is OK since the host IP for an endpoint IP will never change, given how we're allocating endpoint IPs in Cilium. And the initial association between an endpoint IP and its host IP will always be forwarded to the listeners. So it will continue to work as it does now.

If we wanted ipcache to be responsible for mapping endpoint IPs to host IPs, the logic to determine whether to callback the listeners and with what parameters should have been different and more complicated. Notably, we should maintain a map of IP to host IP, because we'd need to keep track of the old host IP so it could be passed to the listeners and so we could determine whether to callback the listeners when the host IP changes.

**Comment by rlenglet** [comment]
> If inserting a new endpoint IP that is shadowing an existing
> CIDR, notify the listeners of an update of the identity associated
> with the CIDR, instead of an insert.
>
> Where is the code that does that?

It's in `Upsert`:
```
		// Check whether the upserted endpoint IP will shadow that CIDR, and
		// replace its mapping with the listeners if that was the case.
		if !found {
			if cidrIdentity, cidrFound := ipc.ipToIdentityCache[cidr.String()]; cidrFound {
				if cidrIdentity.ID != newIdentity.ID {
					scopedLog.Info("Upserting endpoint IP shadowing CIDR")
					oldIdentity = &cidrIdentity.ID
				} else {
					// The endpoint IP and the CIDR are associated with the
					// same identity. Nothing changes for the listeners.
					callbackListeners = false
				}
			}
		}
```

File: pkg/ipcache/ipcache.go (hunk 1 above)
Comment (rlenglet) [reply pkg/ipcache/ipcache.go]: Done.

File: pkg/ipcache/ipcache.go (hunk 2 above)
Comment (rlenglet) [reply pkg/ipcache/ipcache.go]: Done.

File: pkg/ipcache/ipcache.go (hunk 3 above)
Comment (rlenglet) [reply pkg/ipcache/ipcache.go]: Just to clarify: in which cases does the host IP for an endpoint IP change? I thought that this couldn't happen in Cilium.

File: pkg/ipcache/ipcache.go (hunk 4 above)
Comment (rlenglet) [reply pkg/ipcache/ipcache.go]: For some reason, the shadowing-related log messages were at info level. I just wanted to be consistent. I agree this should be debug.
Changed all of them.

File: pkg/ipcache/ipcache.go (hunk 6 above)
Comment (rlenglet) [reply pkg/ipcache/ipcache.go]: Yes, agreed. :/
I think this will require keeping a mapping of IP to host IP, so we know whether the host IP changes or not because of un/shadowing.
The daemon callback will need to be changed as well, since this callback wouldn't be a `Delete` but an `Upsert` with a `nil` new host IP.

**Comment by rlenglet** [comment]
CI build failure:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/4845/
```
08:38:22 K8sValidatedDemosTest
08:38:22 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
08:38:22   Tests Star Wars Demo [It]
08:38:22   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
08:38:22 
08:38:22   unable to access deathstar.default.svc.cluster.local/v1/exhaust-port when policy allows it; 000
08:38:22   Expected
08:38:22       <string>: 000
08:38:22   to contain substring
08:38:22       <string>: 503
08:38:22 
08:38:22   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/demos.go:159
```

**Comment by rlenglet** [comment]
test-me-please

File: pkg/ipcache/ipcache.go [hunk 7]
```diff
@@ -180,77 +189,193 @@ func allowOverwrite(existing, new Source) bool {
...
+					oldIdentity = &cidrIdentity.ID
+				} else {
+					// The endpoint IP and the CIDR are associated with the
+					// same identity. Nothing changes for the listeners.
+					callbackListeners = false
+				}
+			}
+		}
+	} else {
+		scopedLog.Debug("Attempt to upsert invalid IP into ipcache layer")
```
Comment (joestringer) [inline pkg/ipcache/ipcache.go]: `.WithError(err)`?

File: pkg/ipcache/ipcache.go (hunk 3 above)
Comment (joestringer) [reply pkg/ipcache/ipcache.go]: Is it a bad thing to complain loudly in the logs here if the hostIP doesn't match?

File: pkg/ipcache/ipcache.go [hunk 8]
```diff
@@ -180,77 +189,193 @@ func allowOverwrite(existing, new Source) bool {
...
+	}
+
+	var cidr *net.IPNet
+	cacheModification := Delete
+	var oldIdentity *identity.NumericIdentity
+	newIdentity := cachedIdentity
+	callbackListeners := true
 
+	var err error
+	if _, cidr, err = net.ParseCIDR(ip); err == nil {
```
Comment (joestringer) [inline pkg/ipcache/ipcache.go:342]: This logic (the next ~40-50LoC) feels like it should be able to be shared with `Upsert()`.

File: pkg/ipcache/ipcache.go (hunk 6 above)
Comment (joestringer) [reply pkg/ipcache/ipcache.go]: Should hostIP changes be a separate cache modification type? Then the proxy can ignore it easily. Only the BPF side needs to be aware of such changes, right?

File: pkg/ipcache/kvstore.go [hunk 9]
```diff
@@ -362,106 +338,37 @@ restart:
...
+
 			case kvstore.EventTypeCreate, kvstore.EventTypeModify:
+				var ipIDPair identity.IPIdentityPair
 				err := json.Unmarshal(event.Value, &ipIDPair)
 				if err != nil {
-					scopedLog.WithError(err).Errorf("not adding entry to ip cache; error unmarshaling data from key-value store")
+					scopedLog.WithError(err).Errorf("Not adding entry to ip cache; error unmarshaling data from key-value store")
 					continue
 				}
+				IPIdentityCache.Upsert(ipIDPair.PrefixString(), ipIDPair.HostIP, Identity{
```
Comment (joestringer) [inline pkg/ipcache/kvstore.go:354]: :tada:

File: pkg/ipcache/kvstore.go [hunk 10]
```diff
@@ -362,106 +338,37 @@ restart:
 			//   the deletion event.
 			switch event.Typ {
 			case kvstore.EventTypeListDone:
-				for _, listener := range listeners {
+				for _, listener := range IPIdentityCache.listeners {
```
Comment (joestringer) [inline pkg/ipcache/kvstore.go]: Unlocked access to the listeners?

EDIT: Specifically, I believe that `InitIPIdentityWatcher()`->`Watch()` here  is called prior to `SetListeners`, so this could be running while the daemon sets the listeners.

**Review by joestringer — COMMENTED** [review]
+5 LoC and so much tidier. Glad to see this!

I added some minor feedback, in particular one shared variable access without holding a lock.

File: pkg/ipcache/ipcache.go (hunk 3 above)
Comment (tgraf) [reply pkg/ipcache/ipcache.go]: I'm happy with a loud log message for now but would feel more comfortable if we hand it gracefully at some point. I'm sure we'll forget about the assumption we're making here.

File: pkg/ipcache/ipcache.go (hunk 6 above)
Comment (rlenglet) [reply pkg/ipcache/ipcache.go]: I’ve been thinking about this. I would like that very much. However I don’t think that would be possible since the ID and host IP need to change together to be able to compute the correct BPF map key, cf the callback implementation in the daemon.

File: pkg/ipcache/ipcache.go (hunk 3 above)
Comment (rlenglet) [reply pkg/ipcache/ipcache.go]: Unfortunately, to be able to detect a mismatch I’ll have to maintain a map of IP to host IP. If we’re biting the bullet and manage that mapping anyway, we might as well do it the right way.

**Comment by tgraf** [comment]
@rlenglet How does this fix #4803? The code only seems to avoid updates when the ID is identical and Envoy also bails out if the identity is different. I'm not sure we can fix this without touching the Envoy filter. I must be missing something.

File: pkg/ipcache/ipcache.go (hunk 3 above)
Comment (ianvernon) [reply pkg/ipcache/ipcache.go]: I don't understand the concern that " the endpoint IP based mapping can have a different hostIP that needs to be plumbed" - when can this be the case? When could such a mismatch occur?

Comment (tgraf) [reply pkg/ipcache/ipcache.go]: The most likely scenario are outdated ipcache entries in the kvstore that then get overwritten by a node reusing a previously used PodCIDR with a changed hostIP. In general I find it highly dangerous to make assumptions in such generic code that is at the foundation of everything. We can exclude this case for now and track it in an issue but we should really turn it around and proof that a hostIP can never change instead of arguing about likeliness of it changing.

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
Added a commit to maintain a mapping of endpoint IP to host IP, and properly call the listeners when the host IP changes but not the identity.

File: pkg/ipcache/ipcache.go (hunk 7 above)
Comment (rlenglet) [reply pkg/ipcache/ipcache.go]: I have no `error` to work with. When `net.ParseIP` can't parse, it just returns a `nil` value, and no error.
I made this an `Error` log statement.

**Comment by rlenglet** [comment]
So we now properly support host IP changes.

File: pkg/ipcache/kvstore.go (hunk 10 above)
Comment (rlenglet) [reply pkg/ipcache/kvstore.go]: Added locking around this. Good catch!

`SetListeners` is called from `Daemon.init`, which is called prior to `ipcache.InitIPIdentityWatcher`, cf. `NewDaemon`:
```
	if err = d.init(); err != nil {
		log.WithError(err).Error("Error while initializing daemon")
		return nil, err
	}

	// Start watcher for endpoint IP --> identity mappings in key-value store.
	// this needs to be done *after* init() for the daemon in that function,
	// we populate the IPCache with the host's IP(s).
	ipcache.InitIPIdentityWatcher()
```

**Comment by rlenglet** [comment]
test-me-please

File: pkg/ipcache/ipcache.go (hunk 3 above)
Comment (rlenglet) [reply pkg/ipcache/ipcache.go]: I updated ipcache to properly handle changing the host IP for an endpoint.

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
CI build failure:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5069/execution/node/92/log/
```
20:45:52 K8sValidatedChaosTest
20:45:52 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
20:45:52   Endpoint can still connect while Cilium is not running [It]
20:45:52   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
20:45:52 
20:45:52   DNS entry is not ready after timeout
20:45:52   Expected
20:45:52       <*errors.errorString | 0xc4203e8130>: {
20:45:52           s: "Timeout reached: DNS \"testds-service.default.svc.cluster.local\" is not ready after timeout",
20:45:52       }
20:45:52   to be nil
20:45:52 
20:45:52   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Chaos.go:122
```
```
20:48:05 K8sValidatedServicesTest
20:48:05 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
20:48:05   Checks service across nodes
20:48:05   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
20:48:05     Tests NodePort [It]
20:48:05     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
20:48:05 
20:48:05     Pod "testclient-5vs6j" can not connect to service "http://192.168.36.11:30559"
20:48:05     Expected command: kubectl exec -n default testclient-5vs6j -- curl -s -D /dev/stderr --fail --connect-timeout 3 --max-time 3 http://192.168.36.11:30559 
20:48:05     To succeed, but it failed:
20:48:05     Exitcode: 28 
20:48:05     Stdout:
20:48:05      	 
20:48:05     Stderr:
20:48:05      	 
20:48:05     
20:48:05 
20:48:05     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Services.go:195
```
```
21:07:33 K8sValidatedServicesTest
21:07:33 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
21:07:33   Bookinfo Demo
21:07:33   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
21:07:33     Tests bookinfo demo [It]
21:07:33     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
21:07:33 
21:07:33     DNS entry is not ready after timeout
21:07:33     Expected
21:07:33         <*errors.errorString | 0xc420458360>: {
21:07:33             s: "Timeout reached: DNS \"productpage.default.svc.cluster.local\" is not ready after timeout",
21:07:33         }
21:07:33     to be nil
21:07:33 
21:07:33     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Services.go:398
```
```
21:23:45 K8sValidatedPolicyTest
21:23:45 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
21:23:45   GuestBook Examples
21:23:45   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
21:23:45     checks policy example [It]
21:23:45     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
21:23:45 
21:23:45     DNS entry is not ready after timeout
21:23:45     Expected
21:23:45         <*errors.errorString | 0xc42a29ff80>: {
21:23:45             s: "Timeout reached: DNS \"redis-master.default.svc.cluster.local\" is not ready after timeout",
21:23:45         }
21:23:45     to be nil
21:23:45 
21:23:45     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Policies.go:680
```

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5069/execution/node/93/log/
```
20:48:35 K8sValidatedChaosTest
20:48:35 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
20:48:35   Endpoint can still connect while Cilium is not running [It]
20:48:35   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
20:48:35 
20:48:35   DNS entry is not ready after timeout
20:48:35   Expected
20:48:35       <*errors.errorString | 0xc42040c0a0>: {
20:48:35           s: "Timeout reached: DNS \"testds-service.default.svc.cluster.local\" is not ready after timeout",
20:48:35       }
20:48:35   to be nil
20:48:35 
20:48:35   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Chaos.go:122
```
```
20:52:20 K8sValidatedServicesTest
20:52:20 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
20:52:20   Checks service across nodes
20:52:20   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
20:52:20     Tests NodePort [It]
20:52:20     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
20:52:20 
20:52:20     Pod "testclient-6v5lr" can not connect to service "http://192.168.36.11:30275"
20:52:20     Expected command: kubectl exec -n default testclient-6v5lr -- curl -s -D /dev/stderr --fail --connect-timeout 3 --max-time 3 http://192.168.36.11:30275 
20:52:20     To succeed, but it failed:
20:52:20     Exitcode: 28 
20:52:20     Stdout:
20:52:20      	 
20:52:20     Stderr:
20:52:20      	 command terminated with exit code 28
20:52:20     	 
20:52:20     
20:52:20 
20:52:20     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Services.go:195
```
```
21:10:56 K8sValidatedServicesTest
21:10:56 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
21:10:56   Bookinfo Demo
21:10:56   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
21:10:56     Tests bookinfo demo [It]
21:10:56     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
21:10:56 
21:10:56     DNS entry is not ready after timeout
21:10:56     Expected
21:10:56         <*errors.errorString | 0xc4215e4230>: {
21:10:56             s: "Timeout reached: DNS \"productpage.default.svc.cluster.local\" is not ready after timeout",
21:10:56         }
21:10:56     to be nil
21:10:56 
21:10:56     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Services.go:398
```
```
22:09:06 K8sValidatedKafkaPolicyTest
22:09:06 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
22:09:06   Kafka Policy Tests
22:09:06   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
22:09:06     KafkaPolicies [BeforeEach]
22:09:06     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
22:09:06 
22:09:06     DNS entry of kafka-service is not ready after timeout
22:09:06     Expected
22:09:06         <*errors.errorString | 0xc4203ce1a0>: {
22:09:06             s: "Timeout reached: DNS \"kafka-service.default.svc.cluster.local\" is not ready after timeout",
22:09:06         }
22:09:06     to be nil
22:09:06 
22:09:06     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/KafkaPolicies.go:118
```

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
Another CI build failure, for the same reason ("DNS not ready"...):
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5088/

**Comment by rlenglet** [comment]
test-me-please

**Comment by tgraf** [comment]
> Another CI build failure, for the same reason ("DNS not ready"...):

We have not seen that in a while so it may be something related to this PR.

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
> We have not seen that in a while so it may be something related to this PR.

Yes, my latest commit to handle changing host IP had a bug.

**Comment by rlenglet** [comment]
Successful CI build:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5117

Will run another build.

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
CI build failure:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5122/execution/node/92/log/?consoleFull
```
20:22:55 K8sValidatedServicesTest
20:22:55 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
20:22:55   Bookinfo Demo
20:22:55   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
20:22:55     Tests bookinfo demo [It]
20:22:55     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
20:22:55 
20:22:55     Error creating policy "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/cnp-specs.yaml"
20:22:55     Expected
20:22:55         <*helpers.SSHMetaError | 0xc420b34620>: Error: Timeout reached: cannot change state of resource correctly; command timed out
20:22:55     Extended info: Policy version when cilium start
20:22:55     Cilium-agent "cilium-c213l" started with policy revision '81' and finished with '87' 
20:22:55     Cilium-agent "cilium-r9xq3" started with policy revision '86' and finished with '92' 
20:22:55     
20:22:55     
20:22:55     to be nil
20:22:55 
20:22:55     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Services.go:420
```
```
20:22:54 ⚠️  Cilium agent "cilium-r9xq3": Status: Ok  Health: Ok Nodes "k8s1 k8s2" ContinerRuntime: Ok Kubernetes: Ok KVstore: Ok Controllers: Total 41 Failed 1
```

The `sync-cnp-policy-status` controller is unhealthy:
```
$ more cilium-r9xq3_status.txt 
KVStore:                Ok   etcd: 1/1 connected: http://k8s1:9732 - 3.1.0 (Leader)
ContainerRuntime:       Ok   docker daemon: OK
Kubernetes:             Ok   OK
Kubernetes APIs:        ["cilium/v2::CiliumNetworkPolicy", "networking.k8s.io/v1::NetworkPolicy", "core/v1::Service", "core/v1::Endpoint", "core/v1::Pods", "core/v1::Node", "CustomResourceDefinition"]
Cilium:                 Ok   OK
NodeMonitor:            Listening for events on 2 CPUs with 64x4096 of shared memory
Cilium health daemon:   Ok   
IPv4 address pool:      6/255 allocated
IPv6 address pool:      5/65535 allocated
Controller Status:      34/35 healthy
  Name                                                       Last success   Last error   Count   Message
...
  sync-cnp-policy-status (v2 default/multi-rules)            never          15s ago      15      context deadline exceeded   
...
```

Seeing logs of those warning log messages:
```
pod-kube-system-cilium-c213l-cilium-agent.log:2018-07-19T19:50:02.184804344Z level=warning msg="Unable to update ipcache entry of Kubernetes node" error="no/invalid Cilium-Host IP: "
```
Updated the code to include the host IP in that log message.

The logs from the failing controller are:
```
2018-07-19T20:09:03.525194778Z level=debug msg="successfully updated with status" ciliumNetworkPolicyName=multi-rules k8sApiVersion= k8sNamespace=default status="{map[k8s2:{true  2018-07-19 20:08:34.960038298 +0000 UTC 82 true map[]} k8s1:{true  2018-07-19 20:09:03.44743958 +0000 UTC m=+1622.909607868 87 false map[]}]}"
2018-07-19T20:09:03.525587051Z level=debug msg="Controller run failed" consecutiveErrors=1 error="context deadline exceeded" name="sync-cnp-policy-status (v2 default/multi-rules)" subsys=controller uuid=834e0c11-8b8f-11e8-bb69-08002707f0ef
```
Those logs indicate that each call to `endpointmanager.WaitForEndpointsAtPolicyRev` is failing.

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
New CI build failure:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5127/execution/node/92/log/?consoleFull
```
23:10:50 K8sValidatedUpdates
23:10:50 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
23:10:50   Updating Cilium stable to master [BeforeEach]
23:10:50   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
23:10:50 
23:10:50   cannot apply cilium example daemonset
23:10:50   Expected command: kubectl apply -f  /home/vagrant/go/src/github.com/cilium/cilium/test/cilium_ds_9acb0442.json 
23:10:50   To succeed, but it failed:
23:10:50   Exitcode: 1 
23:10:50   Stdout:
23:10:50    	 configmap "cilium-config" created
23:10:50   	 
23:10:50   Stderr:
23:10:50    	 error: json: line 0: invalid character '}' after object key
23:10:50   	 
23:10:50   
23:10:50 
23:10:50   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/helpers/utils.go:195
```
This is not caused by this PR. I think this is because the test code doesn't flush the file before using it:
Cf. `test/helpers/utils.go`'s `InstallExampleCilium`:
```
	fp, err := os.Create(newCiliumDSName)
	defer fp.Close()
	Expect(err).To(BeNil())

	fmt.Fprint(fp, result.String())

	kubectl.Apply(GetFilePath(newCiliumDSName)).ExpectSuccess(
		"cannot apply cilium example daemonset")
```

**Comment by tgraf** [comment]
test-me-please

**Comment by rlenglet** [comment]
Another CI build failure:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5130/execution/node/92/log/?consoleFull
```
01:13:37 K8sValidatedServicesTest
01:13:37 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
01:13:37   Bookinfo Demo
01:13:37   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
01:13:37     Tests bookinfo demo [It]
01:13:37     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
01:13:37 
01:13:37     Error creating policy "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/cnp-specs.yaml"
01:13:37     Expected
01:13:37         <*helpers.SSHMetaError | 0xc421321800>: Error: Timeout reached: cannot change state of resource correctly; command timed out
01:13:37     Extended info: Policy version when cilium start
01:13:37     Cilium-agent "cilium-8ms44" started with policy revision '40' and finished with '42' 
01:13:37     Cilium-agent "cilium-zd0zd" started with policy revision '38' and finished with '40' 
01:13:37     
01:13:37     
01:13:37     to be nil
01:13:37 
01:13:37     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Services.go:420
```

**Comment by rlenglet** [comment]
I will remove the host IP fix commit and retry.

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
CI build failed, apparently because of DNS:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5132/execution/node/92/log/?consoleFull
```
02:12:49 K8sValidatedChaosTest
02:12:49 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
02:12:49   Endpoint can still connect while Cilium is not running [It]
02:12:49   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
02:12:49 
02:12:49   DNS entry is not ready after timeout
02:12:49   Expected
02:12:49       <*errors.errorString | 0xc420088210>: {
02:12:49           s: "Timeout reached: DNS \"testds-service.default.svc.cluster.local\" is not ready after timeout",
02:12:49       }
02:12:49   to be nil
02:12:49 
02:12:49   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Chaos.go:122
```
```
02:24:44 K8sValidatedDemosTest
02:24:44 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
02:24:44   Tests Star Wars Demo [It]
02:24:44   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
02:24:44 
02:24:44   DNS entry is not ready after timeout
02:24:44   Expected
02:24:44       <*errors.errorString | 0xc420089240>: {
02:24:44           s: "Timeout reached: DNS \"deathstar.default.svc.cluster.local\" is not ready after timeout",
02:24:44       }
02:24:44   to be nil
02:24:44 
02:24:44   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/demos.go:131
```
```
02:27:31 K8sValidatedServicesTest
02:27:31 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
02:27:31   Checks service across nodes
02:27:31   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
02:27:31     Tests NodePort [It]
02:27:31     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
02:27:31 
02:27:31     Pod "testclient-bvxqr" can not connect to service "http://192.168.36.11:31605"
02:27:31     Expected command: kubectl exec -n default testclient-bvxqr -- curl -s -D /dev/stderr --fail --connect-timeout 3 --max-time 3 http://192.168.36.11:31605 
02:27:31     To succeed, but it failed:
02:27:31     Exitcode: 28 
02:27:31     Stdout:
02:27:31      	 
02:27:31     Stderr:
02:27:31      	 
02:27:31     
02:27:31 
02:27:31     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Services.go:195
```
```
02:45:13 K8sValidatedServicesTest
02:45:13 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
02:45:13   Bookinfo Demo
02:45:13   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
02:45:13     Tests bookinfo demo [It]
02:45:13     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
02:45:13 
02:45:13     DNS entry is not ready after timeout
02:45:13     Expected
02:45:13         <*errors.errorString | 0xc42083eb20>: {
02:45:13             s: "Timeout reached: DNS \"productpage.default.svc.cluster.local\" is not ready after timeout",
02:45:13         }
02:45:13     to be nil
02:45:13 
02:45:13     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Services.go:398
```
```
02:56:39 K8sValidatedUpdates
02:56:39 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
02:56:39   Updating Cilium stable to master [It]
02:56:39   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
02:56:39 
02:56:39   DNS entry is not ready after timeout
02:56:39   Expected
02:56:39       <*errors.errorString | 0xc424d52b50>: {
02:56:39           s: "Timeout reached: DNS \"app1-service.default.svc.cluster.local\" is not ready after timeout",
02:56:39       }
02:56:39   to be nil
02:56:39 
02:56:39   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Updates.go:201
```
```
03:15:49 K8sValidatedPolicyTest
03:15:49 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
03:15:49   GuestBook Examples
03:15:49   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
03:15:49     checks policy example [It]
03:15:49     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
03:15:49 
03:15:49     DNS entry is not ready after timeout
03:15:49     Expected
03:15:49         <*errors.errorString | 0xc420c1b010>: {
03:15:49             s: "Timeout reached: DNS \"redis-master.default.svc.cluster.local\" is not ready after timeout",
03:15:49         }
03:15:49     to be nil
03:15:49 
03:15:49     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Policies.go:680
```
```
03:28:51 K8sValidatedKafkaPolicyTest
03:28:51 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
03:28:51   Kafka Policy Tests
03:28:51   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:344
03:28:51     KafkaPolicies [BeforeEach]
03:28:51     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
03:28:51 
03:28:51     DNS entry of kafka-service is not ready after timeout
03:28:51     Expected
03:28:51         <*errors.errorString | 0xc422b3a090>: {
03:28:51             s: "Timeout reached: DNS \"kafka-service.default.svc.cluster.local\" is not ready after timeout",
03:28:51         }
03:28:51     to be nil
03:28:51 
03:28:51     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/KafkaPolicies.go:118
```

This is similar to a previous CI build failure, with the host IP fix commit.
So the DNS failures are not due to that commit, I will re-include it in this PR.

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
Successful CI build: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/5133/

**Comment by rlenglet** [comment]
Will run another build to be sure.

**Comment by rlenglet** [comment]
test-me-please

**Comment by tgraf** [comment]
Latest CI failure seems unrelated, ping to outside world did not succeed. All other tests succeeded.

**Review by tgraf — APPROVED** [review]
