### PR TITLE
Documentation: fix CI to catch untracked generated files

### LINKED ISSUE #44636: ci: missing Documentation/cmdref/cilium-dbg_policy_subject-selectors.md was not caught in #42580
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.19.1 and lower than v1.20.0

### What happened?

https://github.com/cilium/cilium/pull/42580 (and backported https://github.com/cilium/cilium/commit/5852bf0020e827f39d64f716674a5a36dca53cce) introduced `cilium-dbg policy subject-selectors` command but its doc was not added. It was later added in unrelated PR https://github.com/cilium/cilium/pull/43057. This should have been caught by CI.

### How can we reproduce the issue?

Push a PR with a missing cmdref file.

### Cilium Version

HEAD

### Kernel Version

Irrelevant

### Kubernetes Version

Irrelevant

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by MrHohn**
When new commands are added or new documentation is generated, the scripts in Documentation/ check for diffs using 'git diff --quiet'. However, this does not catch new, untracked files. This can lead to CI passing even if required documentation files are missing from the PR (but generated during the CI run).

This PR adds 'git add --intent-to-add' before the diff check to ensure new files are also considered.

Fixes https://github.com/cilium/cilium/issues/44636

### CODE REVIEW

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
I rebased the PR because smoke tests were consistently failing, and I suspect it's because of a runtime conflict with a patch merged after the base commit of the PR. Re-triggering tests.

File: Documentation/check-cmdref.sh [hunk 1]
```diff
@@ -7,6 +7,9 @@ set -o pipefail
 script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 cmdref_dir="${script_dir}/cmdref"
 
+# Ensure new files are also considered in the diff
+git add --intent-to-add -- "${cmdref_dir}"
+
 if ! git diff --quiet -- "${cmdref_dir}" ; then
```
Comment (qmonnet) [inline Documentation/check-cmdref.sh:13]: Note: Another way to do that would be to compare with the latest commit, no need to add to the index:

```bash
if ! git diff --quiet HEAD -- "${cmdref_dir}" ; then
```

`git-diff` man page says:

```
Various ways to check your working tree

       $ git diff            (1)
       $ git diff --cached   (2)
       $ git diff HEAD       (3)
       $ git diff AUTO_MERGE (4)
    1. Changes in the working tree not yet staged for the next commit.
    2. Changes between the index and your last commit; what you would be committing if you run git commit without -a option.
    3. Changes in the working tree since your last commit; what you would be committing if you run git commit -a
    4. Changes in the working tree you’ve made to resolve textual conflicts so far.
```

Comment (joestringer) [reply Documentation/check-cmdref.sh:13]: I guess this would be slightly less invasive if someone happened to leave unintended files in the directory and locally ran one of these targets. But the benefit of changing the approach seems marginal. @qmonnet would you like to see this changed or should we just merge as-is?

Comment (qmonnet) [reply Documentation/check-cmdref.sh:13]: I'm good with the current approach, that's why I simply commented. Sorry, I didn't realise the “unresolved” conversation was blocking the auto-merge.
