### PR TITLE
kpr: ensure DirectRoutingDevice is in devices

### LINKED ISSUE #14052: failed to start cilium agent with devices and directRoutingDevice set
## Bug report

**General Information**

- Cilium version (run `cilium version`) 1.9.0
- Kernel version (run `uname -a`) Linux compute1 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
- Link to relevant artifacts (policies, deployments scripts, ...)
   
`eth0 is nic to the default gateway, eth1 is the nic I want cilium for direct route.`

`kubeadm init --apiserver-advertise-address=192.168.50.11 --pod-network-cidr=10.0.0.0/16 
--service-cidr=10.17.0.0/16 --kubernetes-version=v1.19.4  --skip-phases=addon/kube-proxy
`

`helm install cilium cilium/cilium --version 1.9.0  --namespace kube-system  
--set tunnel=disabled     --set autoDirectNodeRoutes=true    
--set kubeProxyReplacement=strict        
--set loadBalancer.acceleration=native   
--set loadBalancer.algorithm=maglev 
--set loadBalancer.mode=hybrid    
--set k8sServiceHost=192.168.50.11  
--set k8sServicePort=6443 
--set nativeRoutingCIDR=192.168.51.0/24 
--set nodePort.directRoutingDevice=eth1 
--set devices=eth0`

- Generate and upload a system zip:
[http://paste.openstack.org/show/800078/](url)

**How to reproduce the issue**

1. instruction 1
2. instruction 2

### PR DESCRIPTION
**Pull request by kkourt**
As reported by #14052, there can be a panic if the congfigured
DirectRoutingDevice is not included in devices. (InitNodePortAddrs() is
called with option.Config.Devices.)

~Fix this by checking that the specified is included and fail otherwise
since this is probably a user error.~

docs state that:
 If the direct routing device does not exist within devices, Cilium
 will add the device to the latter list.

so this patch adds the device to the list.

Fixes #14052

Signed-off-by: Kornilios Kourtis <kornilios@isovalent.com>

### CODE REVIEW

**Comment by kkourt** [comment]
Set to draft because it's untested.

**Review by brb — CHANGES_REQUESTED** [review]
Thanks for debugging and fixing.

According to [the docs](https://docs.cilium.io/en/v1.9/gettingstarted/kubeproxy-free/#nodeport-devices-port-and-bind-settings):

> If the direct routing device does not exist within devices, Cilium will add the device to the latter list.

So I guess instead of panicking we should just add the direct routing device to the devices list.

**Comment by kkourt** [comment]
> So I guess instead of panicking we should just add the direct routing device to the devices list.

modified the patch to do so.

File: daemon/cmd/kube_proxy_replacement.go [hunk 1]
```diff
@@ -307,6 +307,28 @@ func detectNativeDevices(strict bool) {
 // replacement after all devices are known.
 func finishKubeProxyReplacementInit(isKubeProxyReplacementStrict bool) {
 	if option.Config.EnableNodePort {
+
```
Comment (borkmann) [inline daemon/cmd/kube_proxy_replacement.go]: nit: extra newline not needed

File: daemon/cmd/kube_proxy_replacement.go [hunk 2]
```diff
@@ -307,6 +307,28 @@ func detectNativeDevices(strict bool) {
...
+		// Check whether the DirectRoutingDevice (if specified) is defined within devices
+		if option.Config.DirectRoutingDevice != "" {
+			directDev := option.Config.DirectRoutingDevice
+			directDevFound := false
+			for _, iface := range option.Config.Devices {
+				if iface == directDev { // found
```
Comment (borkmann) [inline daemon/cmd/kube_proxy_replacement.go]: nit `found` comment neither

File: daemon/cmd/kube_proxy_replacement.go [hunk 3]
```diff
@@ -307,6 +307,28 @@ func detectNativeDevices(strict bool) {
...
+					break
+				}
+			}
+
+			if !directDevFound {
+				// docs state that:
+				//   If the direct routing device does not exist within
+				//   devices, Cilium will add the device to the latter
+				//   list.
+				log.Infof("DirectRoutingDevice %s not included in specified devices %v: adding it", directDev, option.Config.Devices)
```
Comment (borkmann) [inline daemon/cmd/kube_proxy_replacement.go]: also I think we probably don't need to emit an extra info message here given we fix this up anyway on behalf of the user?

Comment (borkmann) [reply daemon/cmd/kube_proxy_replacement.go]: rest lgtm

Comment (kkourt) [reply daemon/cmd/kube_proxy_replacement.go]: I think the message might be useful if the user specified their own devices and we need to add one to the one they specified. But, I'll remove it to avoid confusion.

File: daemon/cmd/kube_proxy_replacement.go [hunk 4]
```diff
@@ -307,6 +307,26 @@ func detectNativeDevices(strict bool) {
...
+			directDevFound := false
+			for _, iface := range option.Config.Devices {
+				if iface == directDev {
+					directDevFound = true
+					break
+				}
+			}
+
+			if !directDevFound {
+				// docs state that:
```
Comment (christarazi) [inline daemon/cmd/kube_proxy_replacement.go]: Nit: Not sure I get why we need to specifically call out that the docs state this?

**Review by christarazi — APPROVED** [review]
LGTM. Non-blocking comment.

File: daemon/cmd/kube_proxy_replacement.go (hunk 4 above)
Comment (kkourt) [reply daemon/cmd/kube_proxy_replacement.go]: That's a good point. I wanted to document the reasoning for choosing this behavior but it does not make sense.
I'll remove it.

**Review by jibi — APPROVED** [review]

**Comment by jibi** [comment]
test-me-please

File: daemon/cmd/kube_proxy_replacement.go [hunk 5]
```diff
@@ -307,6 +307,22 @@ func detectNativeDevices(strict bool) {
 // replacement after all devices are known.
 func finishKubeProxyReplacementInit(isKubeProxyReplacementStrict bool) {
 	if option.Config.EnableNodePort {
+		// Check whether the DirectRoutingDevice (if specified) is defined within devices
```
Comment (brb) [inline daemon/cmd/kube_proxy_replacement.go]: Maybe it make sense to move the new code to `detectNativeDevices(...)` function, and then rename the function to `handleNativeDevices(...)` or so?

Comment (kkourt) [reply daemon/cmd/kube_proxy_replacement.go]: don't have a strong opinion either way, but I pushed a patch with the change above.

File: daemon/cmd/kube_proxy_replacement.go [hunk 6]
```diff
@@ -301,6 +301,24 @@ func detectNativeDevices(strict bool) {
 			l.Info("Using auto-derived devices for BPF node port")
 		}
 	}
```
Comment (brb) [inline daemon/cmd/kube_proxy_replacement.go]:
```suggestion
	} else if option.Config.EnableNodePort { // both --devices and --direct-routing-device are specified by user
	        // Check whether the DirectRoutingDevice (if specified) is
		// defined within devices and if not, add it.
		if option.Config.DirectRoutingDevice != "" {
			directDev := option.Config.DirectRoutingDevice
			directDevFound := false
			for _, iface := range option.Config.Devices {
				if iface == directDev {
					directDevFound = true
					break
				}
			}
			if !directDevFound {
				option.Config.Devices = append(option.Config.Devices, directDev)
			}
		}
	}
	
```

Comment (kkourt) [reply daemon/cmd/kube_proxy_replacement.go]: So there is no case where a user will specify a `--direct-routing-device` that will not be auto-detected by the device detection?

Comment (brb) [reply daemon/cmd/kube_proxy_replacement.go]: The proposed else if branch handles the case when user have provided both `--direct-routing-device` and `--devices`, i.e. the case when no auto detection takes place.

Comment (kkourt) [reply daemon/cmd/kube_proxy_replacement.go]: > The proposed else if branch handles the case when user have provided both --direct-routing-device and --devices, i.e. the case when no auto detection takes place.

Indeed. 

I'm asking, however, about the case where the user specifies `--direct-routing-device` but not `--devices`.

Specifically, I'm asking whether there is a possibility that a panic can happen in this case. That is, can the user define a valid device with `--direct-routing-device` that will not be on the auto-detected list? AFAIU this will cause a panic (see below) with your else if suggestion but not with the original code.



 
Details

* We are indexing `nodePortIPv4Addrs` with `directRoutingIface` in https://github.com/cilium/cilium/blob/89c0f08cc13125deb2a4fe409d465b48301ba34c/pkg/datapath/linux/config/config.go#L341 where `directRoutingIface` is `option.Config.DirectRoutingDevice`. We seem to checking that `directRoutingDevice` is a real iface, since we are getting its index.

* `nodePortIPv4Addrs` is the return of `GetNodePortIPv4AddrsWithDevices` which seems to be copying `ipv4NodePortAddrs`  which is set in `InitNodePortAddrs` https://github.com/cilium/cilium/blob/89c0f08cc13125deb2a4fe409d465b48301ba34c/pkg/node/address.go#L131
* `InitNodePortAddrs` is called by `finishKubeProxyReplacementInit` with `option.Config.Devices` https://github.com/cilium/cilium/blob/89c0f08cc13125deb2a4fe409d465b48301ba34c/daemon/cmd/kube_proxy_replacement.go#L334

So, AFAIU, if we somehow manage to get a valid device in `option.Config.DirectRoutingDevice` that is not in `option.Config.Devices` the agent will panic.

Comment (brb) [reply daemon/cmd/kube_proxy_replacement.go]: Thanks for the detailed comment. I've just tried running with `--direct-routing-devices=$SOME_DEV_WHICH_CANNOT_BE_DETECTED` and without specifying `--devices` - it didn't panic!

Comment (kkourt) [reply daemon/cmd/kube_proxy_replacement.go]: OK, I guess that's good enough. pushed with the suggested change.

**Comment by kkourt** [comment]
test-me-please

**Review by brb — APPROVED** [review]
Thanks!

**Comment by kkourt** [comment]
retest-runtime

**Comment by kkourt** [comment]
(runtime test failed because it could not provision a VM)
