### PR TITLE
endpoint, policy: Don't accidentally clear out endpoint policy maps

### LINKED ISSUE #38998: Traffic drop due to empty policy map after retry due to endpoint regeneration failure
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

There appears to be a race condition causing endpoints whose regeneration process has been retried due to a temporary error to end up being associated with an empty policy map, eventually causing all traffic from/to them to be dropped. 

### How can we reproduce the issue?

Reproduced on latest main as of today (2ab44c251cb2e5a0b6ba673c830d4ed588859ba2), applying a patch [1] on top to simulate an error during bpf collection loading. 

Created a simple development cluster with `make kind && make kind-image && make kind-install-cilium`, and deployed a test application with `k create deploy podinfo --image=stefanprodan/podinfo --replicas=5`. 

Eventually, all endpoints turned ready as expected, but a few appear to be associated with an empty policy map [2]. Any traffic from/to the affected pods gets subsequently dropped.

```
$ kgpwide podinfo-849bfb5c8d-l99dx
NAME                       READY   STATUS    RESTARTS   AGE   IP             NODE                 NOMINATED NODE   READINESS GATES
podinfo-849bfb5c8d-l99dx   1/1     Running   0          25m   10.244.0.247   kind-control-plane   <none>           <none>

$ cilium endpoint list | grep 3066
3066       Disabled           Disabled          3718       k8s:app=podinfo        10:244::f9c7   10.244.0.247   ready

$ cilium bpf policy get 3066
POLICY   DIRECTION   LABELS (source:key[=value])   PORT/PROTO   PROXY PORT   AUTH TYPE   BYTES   PACKETS   PREFIX
Policy stats empty. Perhaps the policy enforcement is disabled?

$ hubble observe -f --namespace=default
Apr 17 08:31:52.982: default/podinfo-849bfb5c8d-l99dx:41072 (ID:3718) <> 10.96.0.10:53 (world-ipv4) from-endpoint FORWARDED (UDP)
Apr 17 08:31:52.982: default/podinfo-849bfb5c8d-l99dx:41072 (ID:3718) <> kube-system/coredns-6f6b679f8f-mxnj2:53 (ID:60937) Policy denied DROPPED (UDP)
```

[1]:   

```patch
diff --git a/pkg/bpf/collection.go b/pkg/bpf/collection.go
index 5c56c437a7ac..ca7ff284423b 100644
--- a/pkg/bpf/collection.go
+++ b/pkg/bpf/collection.go
@@ -8,6 +8,7 @@ import (
 	"errors"
 	"fmt"
 	"os"
+	"sync/atomic"
 
 	"github.com/cilium/ebpf"
 	"github.com/cilium/ebpf/asm"
@@ -264,6 +265,8 @@ type CollectionOptions struct {
 	MapRenames map[string]string
 }
 
+var count atomic.Int32
+
 // LoadCollection loads the given spec into the kernel with the specified opts.
 // Returns a function that must be called after the Collection's entrypoints are
 // attached to their respective kernel hooks. This function commits pending map
@@ -315,6 +318,9 @@ func LoadCollection(spec *ebpf.CollectionSpec, opts *CollectionOptions) (*ebpf.C
 
 	// Attempt to load the Collection.
 	coll, err := ebpf.NewCollectionWithOptions(spec, opts.CollectionOptions)
+	if count.Add(1) < 5 {
+		return nil, nil, fmt.Errorf("test error: %w", os.ErrExist)
+	}
 
 	// Collect key names of maps that are not compatible with their pinned
 	// counterparts and remove their pinning flags.
```

[2]: to be precise, the issue did not happen upon first deployment, but after restarting the Cilium agents. I don't think that this is a precondition though (as I've observed the same issue without restarting the agents), but rather indicates that this is probably caused by a race condition that does not always manifest.

### Sysdump

[cilium-sysdump-20250417-103605.zip](https://github.com/user-attachments/files/19791210/cilium-sysdump-20250417-103605.zip)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jrife**
Transient errors inside `regenerateBPF` can lead to an endpoint's policy map either not being initialized or being accidentally cleared out, resulting in broken connectivity.

### Scenario
In this scenario, a transient error causes the first call to `regenerateBPF` to fail for an endpoint. The second regeneration attempt succeeds, but the final policy map state is empty.

```
initial state:
    e.desiredPolicy == e.realizedPolicy == <empty EndpointPolicy>

0:  e.ComputeInitialPolicy(...)
1:      e.regeneratePolicy(...)
2:          result := &policyGenerateResult{
                endpointPolicy:   e.desiredPolicy,
                identityRevision: e.identityRevision,
            }
3:          selectorPolicy, ... = e.policyRepo.GetSelectorPolicy(...)
            ...
4:          result.endpointPolicy = selectorPolicy.DistillPolicy(...)
            ...
5:      e.setDesiredPolicy(...)
6:          e.setNextPolicyRevision(res.policyRevision)
7:              e.nextPolicyRevision = revision
8:          if ... && res.endpointPolicy != e.desiredPolicy {
                ...
9:              e.desiredPolicy = res.endpointPolicy
10:             datapathRegenCtx.revertStack.Push(func() error {
                    ...
                    e.desiredPolicy = e.realizedPolicy
                    ...
                    _, _, err = e.syncPolicyMapWith(currentMap, false);
                    ...
                })
            }
12:         res.endpointPolicy = nil

current state:
    e.desiredPolicy = <computed policy>
    e.realizedPolicy = <empty policy>

13: e.regenerate(...)
14:     revision, err := e.regenerateBPF(...)
            e.runPreCompilationSteps(regenContext)
	        e.regeneratePolicy(...)
		    ...
		    selectorPolicy, ... = e.policyRepo.GetSelectorPolicy(...)
		    <no-op, since selectorPolicy == nil>
                e.setDesiredPolicy(...) <no-op - e.desiredPolicy matches
                                         the computed policy from above>
15:         defer func() {
                if !e.isProperty(PropertyFakeEndpoint) {
                    e.finalizeProxyState(regenContext, reterr)
                }
            }()
	    ...
16:         err = e.realizeBPFState(regenContext)
17:         if err != nil {
                <e.realizeBPFState returns an error>
                ...
            }
18:         e.finalizeProxyState(regenContext, reterr) <run deferred
	                                                function>
19:             datapathRegenCtx.revertStack.Revert() <run pushed
                                                       revertStack
                                                       function from 10>
20:                 e.desiredPolicy = e.realizedPolicy <from 10>

current state:
    e.desiredPolicy == e.realizedPolicy == <empty policy>

<reattempt regeneration>
22: e.regenerate(...)
23:     revision, err := e.regenerateBPF(...)
            e.runPreCompilationSteps(regenContext)
	        e.regeneratePolicy(...)
		    ...
		    selectorPolicy, ... = e.policyRepo.GetSelectorPolicy(...)
		    <no-op, since selectorPolicy == nil>
                e.setDesiredPolicy(...) <no-op - e.desiredPolicy still
                                         points to e.realizedPolicy,
					 which is empty>
	    ...

current state:
    e.desiredPolicy == e.realizedPolicy == <empty policy>

25:         err = e.realizeBPFState(regenContext) <e.realizeBPFState
                                                   succeeds>
	    ...
	...
26:     return e.updateRealizedState(stats, origDir, revision) <
            ...
            e.realizedPolicy = e.desiredPolicy <"locks in" the empty
                                                map>
            ...

current state:
    e.desiredPolicy == e.realizedPolicy == <empty policy>

<regeneration is done>
```

### Explanation
The second regeneration attempt does not recompute the endpoint policy, since we update `e.nextPolicyRevision` in the first attempt, and hence, `e.desiredPolicy` is not changed. The call succeeds, then the empty map state is "locked in" until a recomputation happens in the future.

### The Fix
To remedy this, revert `nextPolicyRevision` in the revert stack to ensure that `e.desiredPolicy` is recomputed on the next regeneration attempt.

### Make Sure e.realizedPolicy Reflects Reality
Note that the `revertStack` function above relies on the assumption that `e.realizedPolicy` reflects the current endpoint policy map state. However, if the agent has just started, `e.realizedPolicy` may be empty even for existing endpoints. Copy the state from the `policyMapDump` to `e.realizedPolicy` inside `e.runPreCompilationSteps` to make sure the restore logic actually works in these situations instead of clearing out the existing map.

### Testing
I tested this manually using the repro described in [#38998](https://github.com/cilium/cilium/issues/38998#issuecomment-2994303949). Before applying this patch, the repro resulted in broken connectivity to the `coredns` pods every time I started up my kind cluster. After applying this patch, they start up reliably and all liveness/readiness probes succeed.

Fixes: #38998

```release-note
policy: Fix a bug where transient errors in endpoint regeneration lead to broken connectivity.
```

### CODE REVIEW

**Comment by jrife** [comment]
@tsotne95, since you [also reproduced](https://github.com/cilium/cilium/issues/38998#issuecomment-3017106611)  #38998, could you retest in your environment with this patch as well? It would be useful to repro with your methodology and see if this patch resolves the issues you saw. It's possible there are some other weird issues resulting from transient errors in the regeneration path.

**Comment by tsotne95** [comment]
I [commented on issue](https://github.com/cilium/cilium/issues/38998#issuecomment-3022655204)

**Comment by jrife** [comment]
@tommyp1ckles @derailed Could you take a look at this when you get a chance? This fix addresses an issue which is currently a 1.18 release blocker, though the issue actually exists in 1.17 as well.

**Review by derailed — APPROVED** [review]
@jrife Nice work!

**Review by anubhabMajumdar — APPROVED** [review]
Thanks for the fix.

**Comment by squeed** [comment]
Thanks for the excellent PR description. I'm reading through it, to make sure I understand all the implications. I haven't dropped it on the floor, I promise :-)

**Comment by squeed** [comment]
Rather than trying to back-fill `e.realizedPolicy()`, what about setting `e.forcePolicyCompute = true` when reverting policy? Would that have the desired effect?

**Comment by jrife** [comment]
@squeed Thanks for taking a look!

> Rather than trying to back-fill e.realizedPolicy(), what about setting e.forcePolicyCompute = true when reverting policy? Would that have the desired effect?

Isn't the intent of the revert to go back to a map state that was "good" instead of leaving it in some weird intermediate state? If so, I'm not sure that `e.forcePolicyCompute` really accomplishes the same thing. Actually, if we're referring to this block:

```
defer func(p *policy.EndpointPolicy) {
	e.desiredPolicy = p
}(e.desiredPolicy)
```

I didn't want to force policy recomputation for fear that it would be unnecessarily expensive if we get stuck in some loop where this condition keeps occurring. After all, `e.desiredPolicy` should be perfectly fine and there's no real reason to recompute it on the next go around; it's just the BPF map state that needs to be synchronized.

**Review by tommyp1ckles — APPROVED** [review]

File: pkg/endpoint/policy.go [hunk 1]
```diff
@@ -334,6 +334,18 @@ func (e *Endpoint) setDesiredPolicy(datapathRegenCtxt *datapathRegenerationConte
...
+				// Make sure e.desiredPolicy still reflects the
+				// desired state of the world after reverting
+				// back to the last known good state. On the
+				// next regeneration attempt, res.endpointPolicy
+				// will not be recalculated, since we already
+				// updated e.nextPolicyRevision; we want to
+				// preserve the desired policy calculated in
+				// this round so that we don't just end up with
+				// an empty map. See GH-38998.
+				defer func(p *policy.EndpointPolicy) {
```
Comment (squeed) [inline pkg/endpoint/policy.go:345]: I understand why you added this, but this defer (in a revert function!) makes it much, much harder to reason about. Can we fix this by changing the policy calculation logic instead? Something to prevent short-circuiting policy calculation if `e.desiredPolicy` has the wrong revision?

Comment (squeed) [reply pkg/endpoint/policy.go:345]: Note that `e.desiredPolicy.Detach()` has been called, so it is no longer getting incremental policy updates. I'm pretty sure we can't re-use it at this point.

**Comment by squeed** [comment]
> Isn't the intent of the revert to go back to a map state that was "good"

@jrife yah, fair enough. Some of the code special-cases `e.realizedPolicy.Empty() == true` for handling the before-first-regeneration state. But, clearly, not consistently. Plus, there's no guarantee that `e.realizedPolicy.Empty()` won't be true in the future (e.g. policy disabled).

That said, I'm not _super_ concerned about a few extra policy computations. I'd rather do correctness first, then skip calculations when we understand all possible cases. This bug is a clear example of that :-). In particular, the conditions in `runPreCompilationSteps()` deciding whether or not to regenerate policy are probably incorrect.

File: pkg/endpoint/policy.go (hunk 1 above)
Comment (jrife) [reply pkg/endpoint/policy.go:345]: > Can we fix this by changing the policy calculation logic instead?

I can't shake the feeling that this is the wrong place to deal with this. I may be missing some context which makes this clear, but at a high level, this revertStack function is just attempting to walk back the BPF map state to match `e.realizedPolicy`, which presumably represents our last known "good state".

The fact that this code touches `e.desiredPolicy` at all seems strange to me and seems driven by the fact that `syncPolicyMapWith` does its synchronization against `e.desiredPolicy`. I wonder if it wouldn't be better if we just adjusted the interface a bit or added an additional `syncPolicyMapWith` variant that does the synchronization against `e.realizedPolicy` (maybe `revertPolicyMap(...)`?). I think this would make this section easier to reason about, since there is less state flying around, and would express the intent more directly.

WDYT? Is there a reason that `e.desiredPolicy` *should* be `Detach`ed and recalculated in this scenario or can we simplify here?

**Comment by squeed** [comment]
> The fact that this code touches e.desiredPolicy at all seems strange to me and seems driven by the fact that syncPolicyMapWith does its synchronization against `e.desiredPolicy`. 

These are great questions. Which has me wondering: do we even need `e.desiredPolicy`? Obviously that would be a refactor, not a bugfix, but it would make the state management so much clearer.

File: pkg/endpoint/policy.go (hunk 1 above)
Comment (squeed) [reply pkg/endpoint/policy.go:345]: > WDYT? Is there a reason that e.desiredPolicy should be Detached and recalculated in this scenario or can we simplify here?

Because, ultimately, the code expects that after regeneration is done -- successful or not - , `e.desiredPolicy == e.realizedPolicy`. I can't say exactly what, precisely, depends on this, but I do know it's an assumption in multiple places. So, I'd rather a few unnecessary policy calculations than a large refactor. Again, policy calculations are pretty cheap these days. Especially because all of the hard work is already cached when computing the SelectorPolicy, and distilling the SelectorPolicy to an EndpointPolicy is easy.

**Comment by squeed** [comment]
One more question. In your (excellent) timeline, there are the steps

```
<reattempt regeneration>
22: e.regenerate(...)
23:     revision, err := e.regenerateBPF(...)
            e.runPreCompilationSteps(regenContext)
	        e.regeneratePolicy(...)
		    ...
		    selectorPolicy, ... = e.policyRepo.GetSelectorPolicy(...)
		    <no-op, since selectorPolicy == nil>
```

why is `selectorPolicy` nil here?

File: pkg/endpoint/policy.go (hunk 1 above)
Comment (jrife) [reply pkg/endpoint/policy.go:345]: > Because, ultimately, the code expects that after regeneration is done -- successful or not - , e.desiredPolicy == e.realizedPolicy. I can't say exactly what, precisely, depends on this, but I do know it's an assumption in multiple places.

Fair enough. I might poke at this a bit later to see if things can be simplified, but for now, let's just force a recalculation on the next go.

**Comment by jrife** [comment]
> why is selectorPolicy nil here?

I believe I was referring to this condition:

https://github.com/cilium/cilium/blob/aedded1dc2e15531d8488138267d06e75c609d3b/pkg/policy/repository.go#L496-L500

`GetSelectorPolicy` returns `nil` in the timeline, since we already advanced `e.nextPolicyRevision` in the first attempt.

File: pkg/endpoint/policy.go (hunk 1 above)
Comment (jrife) [reply pkg/endpoint/policy.go:345]: In the latest push, I swapped this out for a call to `e.forcePolicyComputation()`.

**Comment by squeed** [comment]
> GetSelectorPolicy returns nil in the timeline, since we already advanced e.nextPolicyRevision in the first attempt.

That's the bug!!! We have to revert that as well.

**Comment by jrife** [comment]
> That's the bug!!! We have to revert that as well.

Ah yeah, I think I avoided this the first time around for the same reason I avoided `forcePolicyComputation`, namely I didn't want to recompute something that didn't need recomputing. Since that's not a concern, I agree reverting `e.nextPolicyRevision` makes a bit more sense here.

Edit: I went ahead and changed the revert logic here so that we preserve the old `e.nextPolicyRevision` and revert it inside the revert stack function. I did another round of manual testing to make sure things work with the bug repro and it seems sound.

**Comment by joestringer** [comment]
@jrife heads up the command is just `/` + the bit in the brackets, for instance `/ci-clustermesh`. Was there a particular failure, for instance https://github.com/cilium/cilium/issues/39370 ? I know that one has come up quite a bit recently in clustermesh tests.

**Comment by jrife** [comment]
@joestringer Thanks for the tip. At a glance, the latest clustermesh failure looks the same as #39370, although I haven't spent a ton of time digging into it yet. It looks like it failed again on the wireguard variant of ci-clustermesh in the most recent run.

**Comment by joestringer** [comment]
Yep looks the same way to me. ci-gateway-api also failed with an existing unreliable test failure https://github.com/cilium/cilium/issues/40243 .

**Comment by jrife** [comment]
And the `ci-ipsec-e2e` failure looks similar to #39764

**Review by squeed — APPROVED** [review]
Thanks!!!!

**Comment by jrife** [comment]
@joestringer It looks like those tests are green after retriggering them. One test (K8s Network E2E tests (dual)) timed out yesterday, but I'm not sure I'm able to retrigger this one.

**Comment by joestringer** [comment]
@jrife `K8s Network E2E tests and kube-apiserver HA` test is not marked as required. I think we're lacking owners to drive that workflow to a reliability rate we could tolerate in Cilium pre-merge CI. As such I'm not considering that a blocker for this PR.

**Comment by joestringer** [comment]
I've removed the `dont-merge/discussion` label given @squeed's approval above.

**Comment by joestringer** [comment]
@jrife did you have a short writeup of the CI triage you performed? It'd be helpful to understand which issues the PR is facing.

Background context is that it's easy to set the bar for merging at "can CI pass once", but in reality what we need is "CI failure rate does not increase". It'd be useful to get some indication as to whether the CI runs are hitting known issues in the tree, or if it's possible that something about this change increases the failure rate. If everyone aims for "can CI pass once", then the impact on the tree is that we end up with a highly unreliable set of tests.

Overall the changes made here look like they make sense and seem unlikely to introduce a regression, so I am somewhat inclined to just get this into the tree. For more context here I will acknowledge that the CI is all green and I'll try one more re-run of the full CI just to try to get more of a sense for whether the failure rate is consistent with the tree or not.

**Comment by jrife** [comment]
> @jrife did you have a short writeup of the CI triage you performed? It'd be helpful to understand which issues the PR is facing.

It depends on what you mean by writeup. I tried to link the CI failures I saw with some known issues above. The latest failure with `ci-clustermesh` looks the same as the failure I saw earlier in `ci-eks`:

```
check-log-errors/no-errors-in-logs:pkg/endpoint:kind-cluster2-16478452662/kube-system/cilium-r5jtl (cilium-agent): Found 1 logs in kind-cluster2-16478452662/kube-system/cilium-r5jtl (cilium-agent) matching list of errors that must be investigated:
time=2025-07-23T18:13:22.859972997Z level=warn source=/go/src/github.com/cilium/cilium/pkg/endpoint/endpoint.go:1785 msg="Unable to fetch kubernetes labels" desiredPolicyRevision=1 ciliumEndpointName=kube-system/coredns-f89dfbcc7-sp4r7 endpointID=3762 containerID=182d4fe81b containerInterface="" datapathPolicyRevision=1 ipv6=fd00:10:244:1::695b identity=5 k8sPodName=kube-system/coredns-f89dfbcc7-sp4r7 ipv4=10.244.1.31 subsys=resolve-labels error="pod.core \"coredns-f89dfbcc7-sp4r7\" not found" (30 occurrences)
```

There's a warning coming out of this block at some point in the logs:

https://github.com/cilium/cilium/blob/1222c37dff49abf46de2e986faa1368835bd0415/pkg/endpoint/endpoint.go#L1779-L1789

I see this which seems like the same thing: https://github.com/cilium/cilium/issues/40682

**Comment by joestringer** [comment]
@jrife Ah sorry I think I just didn't parse the comments very well. When I saw all the re-run comments and looked earlier in the PR, I just didn't identify the information from the posts above. The most obvious format to understand this would be a comment in the following form:

* ci-eks run `<here>` hit `<issue>`
* clustermesh run `<here>` hit `<issue>`
* gateway-api run `<here>` hit `<issue>`
* ipsec-e2e run `<here>` hit `<issue>`

Now that we've re-run I can see that the same tests are failing again. At least as of yesterday, I was aware that the clustermesh test was somewhat unreliable, but I wasn't aware of the failures for these other branches.

**Comment by joestringer** [comment]
Looking over the failures again, I'm wondering if the tree further destabilized over the past day or two. At a glance the failures aren't obviously related to the PR, but that's often the case whether they are related or not; that's the downside with relying so much on e2e tests :cry:  .

Here's the general trend from the CI dashboard for `main` branch over the past week, but the failure rates only seem to increase proportionately to the number of tests that are run:

image

**Comment by joestringer** [comment]
In this screenshot I've filtered `main` branch for the last week for only scheduled/regular builds. Top graph shows a fairly consistent green bar (total runs) and no obvious trend for orange bars (total failures). Trailing end on right hand side is just the latest 6h data is not yet triggered or not scraped yet.

image

**Comment by joestringer** [comment]
@jrife as for your most recent report, I agree those look similar and given Marcel's update / investigation in the thread, that particular failure case was likely introduced into the tree recently.

**Comment by jrife** [comment]
> The most obvious format to understand this would be a comment in the following form:

@joestringer Sure, I can organize things a bit more in a single comment. I'll go back through the failures and link to those that match existing CI flake issues. I *think* all of them look like reported issues, but I'll admit that I can't be 100% sure that this change isn't related. I don't see any obvious reasons why this PR should increase the failure rate, but I have been surprised by seemingly benign changes before :).

**Comment by jrife** [comment]
@joestringer I wonder if it would be worth opening another PR at the same base commit without the changes in this PR just to get a better baseline?

**Comment by joestringer** [comment]
@jrife I was just thinking about the same thing. CI will skip some jobs if it seems like the PR doesn't touch those tests, so based on the `.github/ariane-config.yaml` we'd probably want to add some line to some code file, even a comment should do the trick.

I was just glancing through some of the other recent PRs on main also, but that's not providing much signal. ci-clustermesh is definitely unreliable due to https://github.com/cilium/cilium/issues/39764. You pointed out the other labels one which Marcel was investigating, so it seems likely that was introduced recently. Not sure about the others.

**Comment by jrife** [comment]
@joestringer I was thinking of just commenting out the existing code, so I imagine the same checks would run? Not sure how smart the test filtering is...

**Comment by jrife** [comment]
Just summarizing the latest batch of failures. Looks like a lot are due to https://github.com/cilium/cilium/issues/40682

#### Failure Summary

### `ci-clustermesh`
* [Run](https://github.com/cilium/cilium/actions/runs/16478455041/job/46586237130) hit  https://github.com/cilium/cilium/issues/39370

### `ci-e2e-upgrade`
* [Run](https://github.com/cilium/cilium/actions/runs/16478455564/job/46586258383) looks similar to https://github.com/cilium/cilium/issues/40659

### `ci-clustermesh`
* [Run](https://github.com/cilium/cilium/actions/runs/16478452662/job/46586238912) hit https://github.com/cilium/cilium/issues/40682

### `ci-eks`
* [Run](https://github.com/cilium/cilium/actions/runs/16478453272/job/46586231608) hit https://github.com/cilium/cilium/issues/40682

### `ci-ipsec-e2e`
* [Run](https://github.com/cilium/cilium/actions/runs/16478453291/job/46586236496) looks similar to https://github.com/cilium/cilium/issues/38481

**Comment by joestringer** [comment]
> ci-clustermesh
[Run](https://github.com/cilium/cilium/actions/runs/16478455041/job/46586237130) hit https://github.com/cilium/cilium/issues/40682

This one looks like https://github.com/cilium/cilium/issues/39370 instead (error="retrieving device lxc2772fac915a8: Link not found"). The other assessments look accurate though yeah.

**Comment by jrife** [comment]
@joestringer Looks like both of those are present in that run. I updated the comment to list them both. FWIW I also saw these both in the `ci-clustermesh` run [over in my dummy PR](https://github.com/cilium/cilium/pull/40686#issuecomment-3110143683).

**Comment by joestringer** [comment]
@jrife I don't see "subsys=resolve-labels" in ~that run~ the run linked in my last post. Are you sure?

**Comment by jrife** [comment]
> @jrife I don't see "subsys=resolve-labels" in that run the run linked in my last post. Are you sure?

You're right. I just saw "not found" there and thought it was the same.

> time=2025-07-23T18:22:21.072492528Z level=error source=/go/src/github.com/cilium/cilium/pkg/endpointmanager/endpointsynchronizer.go:309 msg="Cannot update CEP" containerInterface=eth0 identity=33752 k8sPodName=kube-system/clustermesh-apiserver-6f5c4d98cb-kqc4r endpointID=2551 ciliumEndpointName=kube-system/clustermesh-apiserver-6f5c4d98cb-kqc4r datapathPolicyRevision=0 ipv6=fd00:10:242:2::e996 desiredPolicyRevision=2 ipv4=10.242.2.126 containerID=23c2fbbd38 subsys=endpointsynchronizer controller="sync-to-k8s-ciliumendpoint (2551)" error="ciliumendpoints.cilium.io \"clustermesh-apiserver-6f5c4d98cb-kqc4r\" not found" 

It's coming from a different place in the code than https://github.com/cilium/cilium/issues/40682

**Comment by joestringer** [comment]
@jrife thanks for helping to dig into the root causes of those issues affecting the tree! Merging now.

**Comment by joestringer** [comment]
@jrife Oh, what happened between commit https://github.com/cilium/cilium/commit/e03ca9ef0184691b829d1e65309420c57acd8458 until the final version committed here https://github.com/cilium/cilium/commit/f052828b3a7378f116c7785090d6132f3c6c4e7b ? I thought the intent was to move away from the defer approach. Was that intentional?

**Comment by jrife** [comment]
> @jrife Oh, what happened between commit https://github.com/cilium/cilium/commit/e03ca9ef0184691b829d1e65309420c57acd8458 until the final version committed here https://github.com/cilium/cilium/commit/f052828b3a7378f116c7785090d6132f3c6c4e7b ? I thought the intent was to move away from the defer approach. Was that intentional?

Nope, mistake on my part. I did the rebase earlier against an older version of this branch -_-. I'll go ahead and create a new PR.
