### PR TITLE
Fix bgp manager check active backend state, fixes #45276

### LINKED ISSUE #45276: LB service removes bgp route after pods are terminated, not before
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.19.2 and lower than v1.20.0

### What happened?

Hello
it seems that when you have enabled `enableNoServiceEndpointsRoutable: false` and have a service where all the endpoints are terminating, the BGP route gets withdrawn AFTER the pods are actually removed from the API, not by the time the pods are terminated and thus cannot serve.

I've pinpointed the issue to this code: https://github.com/cilium/cilium/blob/main/pkg/bgp/manager/reconciler/service.go#L376

it ALWAYS sets `hasBackends` ignoring any fact that they may be terminating.

I have this patch compiled locally and it fixes the issue: 
```patch
diff --git a/pkg/bgp/manager/reconciler/service.go b/pkg/bgp/manager/reconciler/service.go
index fa7adfa5a3..2c55b1ecaa 100644
--- a/pkg/bgp/manager/reconciler/service.go
+++ b/pkg/bgp/manager/reconciler/service.go
@@ -387,8 +387,11 @@ func (r *ServiceReconciler) updateServiceAdvertisementsMetadata(p ReconcileParam
 // 3) false, false - no backends, no local backend
 func hasBackends(p ReconcileParams, fe *loadbalancer.Frontend) (hasBackends, hasLocalBackends bool) {
        for backend := range fe.Backends {
+               if backend.State != loadbalancer.BackendStateActive {
+                       continue
+               }
                hasBackends = true
-               if backend.NodeName == p.CiliumNode.Name && backend.State == loadbalancer.BackendStateActive {
+               if backend.NodeName == p.CiliumNode.Name {
                        hasLocalBackends = true
                        return
                }
```
if the behaviour is NOT intended this way then please close the issue, but it doesn't make sense to me :-) 

I can send PR with this patch if you agree.

Thanks!

### How can we reproduce the issue?

1. install cilium with `enableNoServiceEndpointsRoutable: false`
2. create LB service with `externalTrafficPolicy: Cluster`
3. terminate all pods
4. observe the BGP route still present until the pods actually get removed, not immediatily as the pods are being terminated (same for when the pods are starting up but not ready yet)

### Cilium Version

1.19.2

### Kernel Version

6.17.0-19-generic (but irrelevant)

### Kubernetes Version

1.35 branch

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by CallMeFoxie**
Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Checks for backend state == active when checking IP path for BGP announcements.

Fixes: #45276 

```release-note
Respect backends for BGP only when they are in state: active
```

### CODE REVIEW

File: pkg/bgp/manager/reconciler/service.go
Comment (oblazek) [inline pkg/bgp/manager/reconciler/service.go]: maybe we should also update the comments to include the "active" state? I.e. "active backends > 0"

**Review by oblazek — CHANGES_REQUESTED** [review]
I would like to see a failing test as a first commit to see that it's broken and then the fix commit

**Review by YutaroHayakawa — CHANGES_REQUESTED** [review]
As @oblazek said, it's nice to have a test to detect this failure so that we don't reintroduce it. Let me request change here.

**Comment by oblazek** [comment]
https://github.com/cilium/cilium/actions/runs/24557635260 says it clearly, without the fix the test fails

**Review by oblazek — APPROVED** [review]

File: pkg/bgp/test/testdata/svc-no-endpoints.txtar [hunk 1]
```diff
@@ -32,8 +32,8 @@ k8s/add endpoints.yaml
 gobgp/routes -o routes.actual
 * cmp gobgp-routes.expected routes.actual
 
-# Delete the service
-k8s/delete service.yaml
```
Comment (YutaroHayakawa) [inline pkg/bgp/test/testdata/svc-no-endpoints.txtar:36]: Let's don't delete the existing case. We can test terminate -> delete flow here instead.

**Review by YutaroHayakawa — CHANGES_REQUESTED** [review]
Thanks for the fix!

File: pkg/bgp/test/testdata/svc-no-endpoints.txtar (hunk 1 above)
Comment (CallMeFoxie) [reply pkg/bgp/test/testdata/svc-no-endpoints.txtar:36]: What flow should we test then? Because at that point the route will be withdrawn anyways and thus should not appear in the bgp list. To test it fully it should be set terminated -> check empty -> set ready -> check not empty -> delete -> check empty?
or maybe add it to the top, do the flow as
- create svc
- check empty
- add not ready/terminated endpoints
- check empty
- update ready
- check announced
- delete
- check empty

instead?

Comment (YutaroHayakawa) [reply pkg/bgp/test/testdata/svc-no-endpoints.txtar:36]: Ah, right. I think it's ok to go with the current way then. I think other test cases such as [this](https://github.com/cilium/cilium/blob/main/pkg/bgp/test/testdata/svc-adverts.txtar) already covers the deletion case, so it's ok to uncover it here. Sorry for the noise 🙏

**Review by YutaroHayakawa — APPROVED** [review]

**Comment by julianwiedmann** [comment]
(rebasing to pull in a CI fix for Gateway API)

File: pkg/bgp/manager/reconciler/service.go
Comment (julianwiedmann) [reply pkg/bgp/manager/reconciler/service.go]: @oblazek @CallMeFoxie FYI in order to merge the PR, this comment will need to be resolved.

Comment (CallMeFoxie) [reply pkg/bgp/manager/reconciler/service.go]: ah ok, I've added the `active` to the comment so it should be fine then
