### PR TITLE
Policy fix mapstate owners

### LINKED ISSUE #18581: eBPF map "policy" fills up (resource leak)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Using Cilium version 1.11.0 (and 1.11.1) we run into problems with exceeding the eBPF map size for the *policy* map of the clusters CoreDNS Pods. We already increased bpf-map-dynamic-size-ratio from 0.0025 (the default setting) to 0.01 to increase all map sizes. However, after some hours (and several hundred very short-lived CronJob Pods later) we again hit the policy map size limit.

Once the eBPB map is full, traffic to CoreDNS will be dropped and (affected) workloads on the cluster start to fail as they no longer can resolve DNS names.

It looks like there is some garbage collection issues (bug) with Cilium not removing old (stale) map entries, kind-of-a resource leak. 

Below the `CiliumNetworkPolicy` which causes this problem. Removing that policy from our clusters resolves the problem.

```yaml
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: coredns
  namespace: kube-system
spec:
  endpointSelector:
    matchLabels:
      k8s-app: coredns
  ingress:
    # Allow DNS access from any namespace and pod inside this Kubernetes cluster.
    - fromEntities:
        - cluster
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
        - ports:
            - port: "53"
              protocol: TCP 
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: grafana-agent
            app.kubernetes.io/instance: grafana-agent-metrics
            io.kubernetes.pod.namespace: grafana-agent-system
        - matchLabels:
            app.kubernetes.io/name: datadog
            app.kubernetes.io/component: cluster-agent
            io.kubernetes.pod.namespace: kube-system
        - matchLabels:
            app.kubernetes.io/name: datadog
            app.kubernetes.io/component: agent
            io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "9153"
  egress:
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
        - ports:
            - port: "53"
              protocol: TCP
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
```

### Cilium Version

We observe that behavior with the following Cilium version:
- 1.11.1
- 1.11.0

### Kernel Version

We observe this behavior with the following kernel version:
- 5.4.156
- 5.10.75

### Kubernetes Version

1.21 (EKS)

### Sysdump

_No response_

### Relevant log output

```shell
msg="Failed to add PolicyMap key" bpfMapKey="{31163 53 6 0}" containerID=94cb79724b datapathPolicyRevision=12 desiredPolicyRevision=12 endpointID=2200 error="Unable to update element for cilium_policy_02200 map with file descriptor 88: the map is full, please consider resizing it. argument list too long" identity=7935 ipv4=10.176.27.102 ipv6= k8sPodName=kube-system/coredns-6df967c45d-fcfnk port=0 subsys=endpoint
```

### Anything else?

Related [Slack thread](https://cilium.slack.com/archives/C01JALNQAR1/p1640211424433400)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #19003: Make owners (dependents) tracking in policy computation reliable
Related to [PR](https://github.com/cilium/cilium/pull/19002), the existing owners (and dependents) tracking in the policy area is buggy. In certain conditions, there can be entries left in the policy map state with no owners while doing incremental policy map changes. This led to BPF identity leaks like https://github.com/cilium/cilium/issues/18581. 

There are some issues in the code - 

- The owners and dependents related book-keeping in the policy map state doesn't have any guardrails/tracking which makes tracking where and how these fields are being set/unset difficult. So functions like [deleteKeyWithChanges](http://github.com/cilium/cilium/blob/master/pkg/policy/mapstate.go#L245-L245) can't enforce invariants like "there shouldn't be any identity tracking entries with no owners (empty owners or `nil` owners).
- Commit 0d585f110846237eb3611e88d0992ba26a162f72 introduced new changes to the design with the expectations that the owners and dependents related book-keeping is not leaked to other callers. @jrajahalme suggested "In retrospect it would have been cleaner to use a different type for the returned adds and deletes that does not have the owners and dependents fields which would make it clearer that the returned maps are not supposed to have any owners or dependents."

### PR DESCRIPTION
**Pull request by jrajahalme**
When an identity is deleted, the agent processes the incremental policy
map changes against previously saved policy state with owners and
dependents of the identity key to decide if an identity can be marked for
deletion. In some cases, the `owners` field for the identity entry was
nil (due to them being redacted when returned by ConsumeMapChanges()
previously), and the deleteKeyWithChanges would return early without
tracking the identity for deletion. As a result, when this information is
consumed later to delete the identity from the BPF maps, the identity was
being leaked in those cases.

Callers of ConsumeMapChanges() and AddVisibilityKeys() depend on the
returned added and deleted keys to perform datapath policy map updates
without iterating whole policy maps. Moreover, the "realized" version of
endpoint's policy map used to be updated solely based on these returned
entries.

Make this less fragile and error prone by only returning the added and
deleted map keys (no values). AddVisibilityKeys() supports reverting the
changes, so it still needs to return the full MapState (keys and values)
for any changed entries.

Now that ConsumeMapChanges() and AddVisibilityKeys() return the keys of
added entries, the caller needs to find the value to be inserted from the
desired policy map using the given key.

Fixes: #18581
Fixes: 0d585f110846237eb3611e88d0992ba26a162f72
Fixes: https://github.com/cilium/cilium/issues/19003
Co-authored-by: Aditi Ghag <aditi@cilium.io>
Signed-off-by: Jarno Rajahalme <jarno@isovalent.com>

```release-note
Fixed a bug where deleted identities would remain in BPF policy maps.
```

### CODE REVIEW

**Comment by aditighag** [comment]
>[policy: Keep internal state in added and deleted mapstate entries](https://github.com/cilium/cilium/pull/19005/commits/19af1183967f4226abc2e7261843a0cd7b162764)

🚀 As discussed on the [issue](https://github.com/cilium/cilium/issues/18581#issuecomment-1044021479) and offline, I originally found this to be the right fix as I was unable to reproduce the issue. Remote debugging also confirmed the same. You'll need to fix the unit tests, see failures in this temporary PR I had created - https://github.com/cilium/cilium/pull/18805.
Change Signed-off-by to Co-authored-by.

Also, can you add "Fixes: https://github.com/aditighag/cilium/commit/0d585f110846237eb3611e88d0992ba26a162f72" to this commit to record the history.

**Comment by aditighag** [comment]
I would also suggest adding more description to the commit around how the identities were leaked. Something along the lines of - 

```
When an identity is deleted, the agent processes the incremental policy
map changes against previously saved policy state with owners
and dependents of the identity key to decide if an identity can be marked for
deletion in the `deletes` map. In some cases, the `owners` field for the identity
entry was nil, and the deleteKeyWithChanges would return early without tracking
the identity for deletion. As a result, when this information is consumed
later to delete the identity from the BPF maps, the identity was being leaked
in those cases.
```

File: pkg/endpoint/bpf.go [hunk 1]
```diff
@@ -1242,13 +1231,25 @@ func (e *Endpoint) applyPolicyMapChanges() (proxyChanges bool, err error) {
 				proxyChanges = true
 			}
 		}
-		if !e.addPolicyKey(keyToAdd, entry, true) {
+		if e.addBPFPolicyKey(keyToAdd, entry, true) {
+			// Operation was successful, add to realized state.
+			e.realizedPolicy.PolicyMapState[keyToAdd] = entry
```
Comment (aditighag) [inline pkg/endpoint/bpf.go]: >so that the update can be made to the correct map in
syncDesiredPolicyMapWith().

Not sure I understand the motivation for this move. Both the places are pointing to the same policy state map, no?

File: pkg/endpoint/bpf.go [hunk 2]
```diff
@@ -1087,7 +1087,7 @@ func (e *Endpoint) updatePolicyMapPressureMetric() {
 // The bool pointed by hadProxy, if not nil, will be set to 'true' if
 // the deleted entry had a proxy port assigned to it.  *hadProxy is
 // not otherwise changed (e.g., it is never set to 'false').
-func (e *Endpoint) deletePolicyKey(keyToDelete policy.Key, incremental bool, hadProxy *bool) bool {
+func (e *Endpoint) deleteBPFPolicyKey(keyToDelete policy.Key, incremental bool) bool {
```
Comment (aditighag) [inline pkg/endpoint/bpf.go]: Nit : The function description needs to be updated.

**Review by aditighag — CHANGES_REQUESTED** [review]

File: pkg/endpoint/bpf.go (hunk 1 above)
Comment (jrajahalme) [reply pkg/endpoint/bpf.go]: Here yes, but on the other call site not always (map is passed down as a parameter).

File: pkg/endpoint/bpf.go (hunk 2 above)
Comment (jrajahalme) [reply pkg/endpoint/bpf.go]: Thanks, fixed.

**Comment by jrajahalme** [comment]
@aditighag Working on the unit tests I noticed that an added entry misses any changes made to owners and dependents due to other entries being added afterwards, as it takes a copy of the entry at the time. Trying to make the returned copy always be the latest one basically would mean reading it from the policy map before returning. Since the caller also has access to the (desired) policy map it is better not to return the map values at all. Instead just return the added and deleted keys and let the caller worry about coping the entry with that key from desired to realised policy map. This makes the code more robust and simplifies the unit tests as well.

**Review by twpayne — COMMENTED** [review]
It looks like the tests in `pkg/policy/mapstate_test.go` need to be updated as they still rely on the `export()` method.

**Comment by aditighag** [comment]
> @aditighag Working on the unit tests I noticed that an added entry misses any changes made to owners and dependents due to other entries being added afterwards, as it takes a copy of the entry at the time. Trying to make the returned copy always be the latest one basically would mean reading it from the policy map before returning. 

I'm not sure I understand this - Take an example of `deleteKeyWithChanges` (or add), the desired keys that need to be added or deleted are already fixed, no? Share a link if you are referring to some other code path?

>Since the caller also has access to the (desired) policy map it is better not to return the map values at all. Instead just return the added and deleted keys and let the caller worry about coping the entry with that key from desired to realised policy map. This makes the code more robust and simplifies the unit tests as well.

I suppose this could could work as long as the desired keys are in sync with the realized ones. What happens when there were sync-up errors? 

Can you also share the unit test that's failing?

**Comment by aditighag** [comment]
I was looking at this example - http://github.com/cilium/cilium/blob/a66538b31e206bb7f4470daeacd879e858177a4d/pkg/endpoint/bpf.go#L1211-L1211. We'll need to read the entries before and after the `AddVisibilityKeys` calls if we avoid populating the entries in the adds/deletes map? But since we can't track all the calls to the entries, how can be sure that the entries weren't modified outside of the current processing path? 
One solution could be adding per entry lock?

**Comment by jrajahalme** [comment]
> I was looking at this example - [http://github.com/cilium/cilium/blob/a66538b31e206bb7f4470daeacd879e858177a4d/pkg/endpoint/bpf.go#L1211-L1211](https://github.com/cilium/cilium/blob/a66538b31e206bb7f4470daeacd879e858177a4d/pkg/endpoint/bpf.go#L1211-L1211). We'll need to read the entries before and after the `AddVisibilityKeys` calls if we avoid populating the entries in the adds/deletes map? But since we can't track all the calls to the entries, how can be sure that the entries weren't modified outside of the current processing path? One solution could be adding per entry lock?

I think this should happen as the (policy) regeneration logic runs at most once in parallel for each endpoint and all policy map updates are done within this logic. I added a new warning log if the entry for an added key can not be found to make sure we learn about any unexpected behaviour here.

**Comment by twpayne** [comment]
Sorry, I'm really not familiar enough with this part of the code or functionality to be able to give more than a rubber-stamp review.

File: pkg/endpoint/bpf.go [hunk 3]
```diff
@@ -1110,26 +1108,17 @@ func (e *Endpoint) deletePolicyKey(keyToDelete policy.Key, incremental bool, had
...
-	}, "deletePolicyKey")
+		logfields.BPFMapKey: keyToDelete,
+		"incremental":       incremental,
+	}, "deleteBPFPolicyKey")
 
 	return true
 }
 
-func (e *Endpoint) addPolicyKey(keyToAdd policy.Key, entry policy.MapStateEntry, incremental bool) bool {
+func (e *Endpoint) addBPFPolicyKey(keyToAdd policy.Key, entry policy.MapStateEntry, incremental bool) bool {
```
Comment (aditighag) [inline pkg/endpoint/bpf.go]: `addBPFPolicyKey` and `deleteBPFPolicyKey` aren't symmetrical anymore. Is that intentional? Can we get `entry` at the caller site too?

File: pkg/endpoint/bpf.go [hunk 4]
```diff
@@ -1110,26 +1108,17 @@ func (e *Endpoint) deletePolicyKey(keyToDelete policy.Key, incremental bool, had
...
-	delete(e.realizedPolicy.PolicyMapState, keyToDelete)
 	e.updatePolicyMapPressureMetric()
 
 	e.PolicyDebug(logrus.Fields{
-		logfields.BPFMapKey:   keyToDelete,
-		logfields.BPFMapValue: entry,
-		"incremental":         incremental,
-	}, "deletePolicyKey")
+		logfields.BPFMapKey: keyToDelete,
+		"incremental":       incremental,
```
Comment (aditighag) [inline pkg/endpoint/bpf.go]: The log messaging printing both key and entry with owners and dependents was useful during debugging. Since we are retrieving entry at the consumer site, can we add a new log there?

File: pkg/endpoint/bpf.go [hunk 5]
```diff
@@ -1110,26 +1108,17 @@ func (e *Endpoint) deletePolicyKey(keyToDelete policy.Key, incremental bool, had
...
 
-	var entry policy.MapStateEntry
-	var ok bool
-	if entry, ok = e.realizedPolicy.PolicyMapState[keyToDelete]; ok && entry.ProxyPort != 0 && hadProxy != nil {
-		*hadProxy = true
-	}
-
-	// Operation was successful, remove from realized state.
-	delete(e.realizedPolicy.PolicyMapState, keyToDelete)
 	e.updatePolicyMapPressureMetric()
```
Comment (joestringer) [inline pkg/endpoint/bpf.go]: The `e.updatePolicyMapPressureMetric()` call is intended to update the metrics for policy map usage whenever the contents change. I think this call should also move to the caller to ensure that it is correctly updated whenever the map is modified.

Ditto for `addBPFPolicyKey()`.

File: pkg/endpoint/bpf.go (hunk 1 above)
Comment (joestringer) [reply pkg/endpoint/bpf.go]: :+1: The `syncPolicyMapWithDump()` case passes not the endpoint's stored realized state map, but instead it takes a fresh dump of the "real" realized state and uses that for comparison (not this line of code, lower down). LGTM.

File: pkg/policy/mapstate.go [hunk 6]
```diff
@@ -459,9 +460,9 @@ var visibilityDerivedFrom = labels.LabelArrayList{visibilityDerivedFromLabels}
 // L4-only key allowing the port is added.
 //
 // 'adds' and 'deletes' are updated with the changes made. 'adds' contains the new values
-// for both added and changed keys. 'deletes' contains the old values for both deleted and
-// changed keys.
-func (keys MapState) AddVisibilityKeys(e PolicyOwner, redirectPort uint16, visMeta *VisibilityMetadata, adds, deletes MapState) {
+// for both added and changed keys. 'deletes' contains the old values for changed keys.
+// This function does not delete any keys.
+func (keys MapState) AddVisibilityKeys(e PolicyOwner, redirectPort uint16, visMeta *VisibilityMetadata, adds Keys, oldValues MapState) {
```
Comment (joestringer) [inline pkg/policy/mapstate.go]: This code changes the named return value for `deletes`, please update the comment to reflect this change.

File: pkg/endpoint/bpf.go [hunk 7]
```diff
@@ -1202,23 +1202,31 @@ func (e *Endpoint) applyPolicyMapChanges() (proxyChanges bool, err error) {
...
 			if redirectPort, exists := e.realizedRedirects[proxyID]; exists && redirectPort != 0 {
-				e.desiredPolicy.PolicyMapState.AddVisibilityKeys(e, redirectPort, visMeta, adds, deletes)
+				e.desiredPolicy.PolicyMapState.AddVisibilityKeys(e, redirectPort, visMeta, adds, nil)
 			}
 		}
 		for _, visMeta := range e.visibilityPolicy.Egress {
 			proxyID := policy.ProxyID(e.ID, visMeta.Ingress, visMeta.Proto.String(), visMeta.Port)
 			if redirectPort, exists := e.realizedRedirects[proxyID]; exists && redirectPort != 0 {
-				e.desiredPolicy.PolicyMapState.AddVisibilityKeys(e, redirectPort, visMeta, adds, deletes)
+				e.desiredPolicy.PolicyMapState.AddVisibilityKeys(e, redirectPort, visMeta, adds, nil)
```
Comment (joestringer) [inline pkg/endpoint/bpf.go:1224]: Why do we no longer care about the `oldValues` here?

File: pkg/endpoint/bpf.go [hunk 8]
```diff
@@ -1202,23 +1202,31 @@ func (e *Endpoint) applyPolicyMapChanges() (proxyChanges bool, err error) {
...
 		// AddVisibilityKeys() records changed keys in both 'deletes' (old value) and 'adds' (new value).
 		// Remove the key from 'deletes' to keep the new entry.
 		delete(deletes, keyToAdd)
 
+		entry, exists := e.desiredPolicy.PolicyMapState[keyToAdd]
+		if !exists {
+			e.getLogger().WithFields(logrus.Fields{
+				logfields.AddedPolicyID: keyToAdd,
+			}).Warn("Tried adding policy map key not in policy")
+			continue
```
Comment (joestringer) [inline pkg/endpoint/bpf.go:1240]: Is this an expected condition, reliant on a race condition? Or is it an unexpected condition that would demonstrate a bug? I'm mostly wondering whether there's any possibility that, for instance, in a high churn cluster with identities being introduced & removed all the time, could this warning message be triggered regularly? Could it flood the logs? Is the plan for us to gather any instances of this warning and use them to investigate further issues?

**Review by joestringer — CHANGES_REQUESTED** [review]
I must admit, I did not fully follow what's going on here. Would probably take another one or two attempts to get my head around what's really going on. I picked out a couple of small nits, most notably that the metrics would not be synced correctly in the current state.

File: pkg/endpoint/bpf.go (hunk 8 above)
Comment (aditighag) [reply pkg/endpoint/bpf.go:1240]: The main motivation of changing `MapState` type to `Keys` is to avoid hitting this condition as we don't allow callers to erroneously mutate owners of a `Key`. `consumeMapChanges` (ideally) should be the only one doing book-keeping of owners and hence removal of keys from the policy map.
So this condition hopefully allows us to identify the cases where this doesn't hold true during the add operation. (I didn't exactly answer your question about the end goal, just giving more context. :))
@jrajahalme Thinking out loud - do we need a reciprocal condition in the delete path? A key is being deleted but it exists in the policy map?

**Comment by jrajahalme** [comment]
@joe An attempt for a big-picture explanation with the weekends separation from this work:

- As part of an endpoint regeneration, incremental policy map updates are retrieved via `ConsumeMapChanges()`
  - As part of this call the collected changes are applied into Endpoint's desired policy 'mapstate'
- Endpoint regeneration logic can then use the returned maps to
  1. update the bpf policy map of the endpoint by inserting and removing map entries
  2. update the endpoint's realized policy MapState so that after all updates it becomes the same as the endpoint's desired MapState
- Prior to this PR the map updates were made with keys and values returned by `ConsumeMapChanges()`, but the returned values missed the `owners` and `dependents` fields, causing the realized MapState to deviate from the desired MapState
  - ultimately when the identity is GC'd this lead to the entry to not be deleted as it missed the `owner` field.
- This PR changes the above so that `ConsumeMapChanges()` only returns the added and deleted keys, and the caller uses the Endpoint's desired policy map to retrieve the map entry. This fixes the GC bug by not losing the `owners` and `dependents` fields when applying incremental policy updates.
- The simpler approach of just copying also the `owners` and `dependents` fields when returning them from `ConsumeMapChanges()` would become more complex due to the need to copy the final values of the map entries as the entry's `dependents` field is modified when a dependent entry (with a different key) is added. It is more robust to just return the keys and have the caller copy the entry from `desired` to `relalized` map.

File: pkg/endpoint/bpf.go (hunk 3 above)
Comment (jrajahalme) [reply pkg/endpoint/bpf.go]: These functions should still be symmetrical, the realized policy map manipulation was removed from both.

File: pkg/endpoint/bpf.go (hunk 4 above)
Comment (jrajahalme) [reply pkg/endpoint/bpf.go]: I'll add the entry the parameters of `deleteBPFPolicyKey()` so that we can keep logging it.

File: pkg/endpoint/bpf.go (hunk 5 above)
Comment (jrajahalme) [reply pkg/endpoint/bpf.go]: BPF policy map is still updated in this function (now called `deleteBPFPolicyKey()`), the caller updates the endpoint's realized policy map. Maybe the intent of the metric is to indicate the pressure on the BPF maps instead of the Go maps? If that is the case then the metric update is in the right place :-)

File: pkg/policy/mapstate.go (hunk 6 above)
Comment (jrajahalme) [reply pkg/policy/mapstate.go]: Thanks, done!

File: pkg/endpoint/bpf.go (hunk 7 above)
Comment (jrajahalme) [reply pkg/endpoint/bpf.go:1224]: `AddVisibilityKeys()` does not delete any keys so I changed the semantics of it to not return `deleted` values, but `oldValues`. The old values of any changed (or deleted) keys are only needed if the changes can be reverted, and that is not the case here.

File: pkg/endpoint/bpf.go (hunk 8 above)
Comment (jrajahalme) [reply pkg/endpoint/bpf.go:1240]: This should be an internal (to the agent) error condition. I'll add unit tests covering addition and deletion of an entry on the same round of incremental updates, even though the code implementing it is pretty clearly removing the key from adds or deletes, if the key us deleted or added, respectively.

**Comment by jrajahalme** [comment]
Renamed the 2nd commit to match the contents.

**Review by joestringer — APPROVED** [review]
I follow now, the regular policy generation path would correctly generate the entries with an 'owner', but the incremental policy path through `ConsumeMapChanges()` would deliberately drop the owner references there. The latter path would then trigger an unintentional override of the `desiredPolicy` map's entries to replace the entries. The replaced entries would no longer contain the owner references.

Then `addKeyWithChanges()` / `deleteKeyWithChanges()` don't really have any handling for the case where the owner is nil / unknown. So once those entries with nil owners end up in the `desiredPolicy` map, they get stuck there and Cilium would always resolve the intended datapath state from that datapath state. Hence the leak.

File: pkg/endpoint/bpf.go [hunk 9]
```diff
@@ -1283,14 +1283,16 @@ func (e *Endpoint) syncPolicyMap() error {
...
 	return err
 }
 
-// syncDesiredPolicyMapWith updates the bpf policy map state based on the
+// syncPolicyMapsWith updates the bpf policy map state based on the
 // difference between the given 'realized' and desired policy state without
 // dumping the bpf policy map.
-func (e *Endpoint) syncDesiredPolicyMapWith(realized policy.MapState, withDiffs bool) (diffCount int, diffs []policy.MapChange, err error) {
+// Changes are synced to endpoint's realized policy mapstate, 'realized' is
+// not modified.
```
Comment (joestringer) [inline pkg/endpoint/bpf.go:1302]: I'm not sure I quite follow the meaning in this last sentence.

It looks to me like we go through the desired policy map, and apply all desired changes that the daemon thinks have not yet been realized. So it's more that the _bpf_ policymaps are synced to the _desired_ state based on the daemon's understanding of the realized state.

Comment (joestringer) [reply pkg/endpoint/bpf.go:1302]: The whole terminology here of "sync desired policy map with ( realized )" just seems kinda confusing to me. The goal here is to sync the BPF policy maps with the desired state, right? But we just make it more efficient by using the current realized state view.

Comment (joestringer) [reply pkg/endpoint/bpf.go:1302]: (thinking aloud if there's another less confusing naming convention here..)

Comment (joestringer) [reply pkg/endpoint/bpf.go:1302]: I think that part of my confusion above is that "sync `<x>` with `<y>`" can be interpreted in a way that describes the way that the information is flowing, basically that `<x>` is the thing that changes and `<y>` is the source of truth. But right now, the thing that actually changes (bpf) is not explicitly mentioned, and it's implied that the desired policy changes here... which doesn't seem to be the case.

Comment (joestringer) [reply pkg/endpoint/bpf.go:1302]: Looking a little further, with the latest version of this PR, this statement seems to be incorrect: `'realized' is not modified.`

`addPolicyKey()` and `deletePolicyKey()` are still modifying the `realizedPolicy`.

**Review by aditighag — APPROVED** [review]

File: pkg/endpoint/bpf.go (hunk 9 above)
Comment (jrajahalme) [reply pkg/endpoint/bpf.go:1302]: This function can be called with a temporary 'realized' map, dumped from the datapath, or with the endpoint's realized policy map. Either way diffs between this passed in map and endpoint's desired policy map are applied to the bpf policy map *and* the endpoint's realized policy map, not the passed in 'realized' map. For the call where 'realized' is the endpoint's realized policy map this does not mean much, but in the case where 'realized' is a temporary map dumped from the datapath there is no point updating it after computing the diff (as the temporary map is thrown away right after), and this way the endpoint's own realized policy map becomes (more) synced with the datapath bpf map.

**Comment by jrajahalme** [comment]
net next provisioning had failed, triggering the test again.

**Comment by jrajahalme** [comment]
test-1.23-net-next

**Comment by aditighag** [comment]
/test-1.23-net-next

File: pkg/endpoint/bpf.go (hunk 9 above)
Comment (joestringer) [reply pkg/endpoint/bpf.go:1302]: Ah, okay - I was wondering why this 'realized' map was explicitly handed in, as I assumed that this `realized` map was exactly the same as `e.realizedPolicy`, but that's not the case. This stuff is pretty subtle :thinking:

**Comment by christarazi** [comment]
Thanks Jarno for https://github.com/cilium/cilium/pull/19005#issuecomment-1060771478. This made sense to me.
