### PR TITLE
Fix cilium-health healthchecking remote endpoint in ENI mode

### LINKED ISSUE #10810: Investigate cilium-health enablement in ENI mode
`cilium-health` appears to be enabled by default in ENI mode, but there are easily reproducible issues in multinode clusters where the cilium-health instances on some nodes are unable to communicate with simulated endpoints on other nodes.

We should investigate these, and:
* Determine whether there is a bug in the cilium-health logic
* If so, fix it; if not, document here why not with proof;
* And/or consider disabling cilium-health in ENI mode until we can confirm that it works reliably.

### PR DESCRIPTION
**Pull request by christarazi**
See commit messages. Manually tested on EKS.

Fixes: #10810 

```release-note
Fix issue where cilium-health cannot healthcheck remote endpoint in ENI mode 
```

### CODE REVIEW

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
Build went green on first try!

File: pkg/aws/eni/routing/routing.go [hunk 1]
```diff
@@ -0,0 +1,158 @@
+// Copyright 2020 Authors of Cilium
```
Comment (joestringer) [inline pkg/aws/eni/routing/routing.go:1]: I assume this is basically just a copy+paste / move from the previous code? For future review it's useful to have pure changes like this in a separate commit, just in case we have to bisect a problem later as it'll be easier to find bugs in smaller commits.

LMK if there are any specific changes you think I should look at in this package.

File: daemon/cmd/ipam.go [hunk 2]
```diff
@@ -353,3 +365,41 @@ func (d *Daemon) bootstrapIPAM() {
 	d.ipam = ipam.NewIPAM(d.datapath.LocalNodeAddressing(), option.Config, d.nodeDiscovery, d.k8sWatcher)
 	bootstrapStats.ipam.End(true)
 }
+
+func (d *Daemon) parseHealthEndpointInfo(result *ipam.AllocationResult) error {
```
Comment (joestringer) [inline daemon/cmd/ipam.go:370]: Is there any chance of further sharing this implementation with `plugins/cilium-cni/eni.go:eniAdd()`?

File: cilium-health/launch/endpoint.go [hunk 3]
```diff
@@ -228,12 +229,20 @@ type EndpointAdder interface {
...
 // cleanup of prior cilium-health endpoint instances.
-func LaunchAsEndpoint(baseCtx context.Context, owner regeneration.Owner, n *node.Node, mtuConfig mtu.Configuration, epMgr EndpointAdder, proxy endpoint.EndpointProxy, allocator cache.IdentityAllocator) (*Client, error) {
+func LaunchAsEndpoint(baseCtx context.Context,
+	owner regeneration.Owner,
+	n *node.Node,
+	mtuConfig mtu.Configuration,
+	epMgr EndpointAdder,
+	proxy endpoint.EndpointProxy,
+	allocator cache.IdentityAllocator,
+	eniHealthRouting *enirouting.RoutingInfo) (*Client, error) {
```
Comment (joestringer) [inline cilium-health/launch/endpoint.go:245]: As a general cleanup, we can avoid directly depending on the eni package from this health endpoint package by defining an interface something like the following, then accepting that as a parameter into this function:

```
type routeConfiguration interface{
    ConfigureRoutes(ip string, mtu int, masquerade bool)
}
```

The other step of this would require instantiating an object to associate this function with, so basically adjust the `Install()` function below to take the `RoutingInfo` as a pointer receiver.

I'd expect this interface to be `nil` if ENI is disabled, or an instance of the `RoutingInfo` if ENI is enabled.

In this specific case I don't think it makes a huge difference, but over time this general approach helps to separate the code, helps unit testing, and avoids tying everything together too tightly with direct implementations.

File: daemon/cmd/daemon_main.go [hunk 4]
```diff
@@ -1291,6 +1285,12 @@ func runDaemon() {
 		d.SendNotification(monitorAPI.AgentNotifyStart, repr)
 	}
 
+	bootstrapStats.healthCheck.Start()
+	if option.Config.EnableHealthChecking {
+		d.initHealth()
+	}
+	bootstrapStats.healthCheck.End(true)
```
Comment (joestringer) [inline daemon/cmd/daemon_main.go]: Is there a particular reason for moving this?

File: daemon/cmd/ipam.go (hunk 2 above)
Comment (joestringer) [reply daemon/cmd/ipam.go:370]: I wonder if we could try the interfaces approach from above, where the `ipam.AllocationResult` object implements a bunch of getters for stuff like the Gateway IP, CIDRs, MAC and then a function in `pkg/aws/eni/routing` like `NewRoutingInfo()` accepts an interface for any object that implements these functions, and uses these to construct the RoutingInfo object, which the daemon can then just set like `d.healthEndpointRouting = enirouting.NewRoutingInfo(result)`.

The cilium-cni code could then do a similar thing with `models.IPAMAddressResponse` (or probably more likely, a wrapper for this since the `models` code tends to be autogenerated), and furthermore you could also pass a dummy implementation into the enirouting package for testing purposes.

**Review by joestringer — APPROVED** [review]
Nice work!

I have a few comments below around structuring the code to reduce interdependency and ideally reduce the number of different parts of the code that need to know this detail about the ENI implementation. Feel free to reach out if they don't make sense.

Main question I have is whether we could take this slightly further and further reduce the duplication of code. Secondary thought is it'd be nice to unit-test this as well, though I recognize that the existing code is lacking unit tests and this will be a bugfix that we likely intend to backport at least to v1.7 so there's also value in keeping the shear number of changes to a minimum.

None of my comments below block merging this implementation as it all looks good to me, but it'd be nice to evaluate whether there's some additional technical debt we could address while we have this area of the code fresh in our heads.

File: pkg/aws/eni/routing/routing.go (hunk 1 above)
Comment (christarazi) [reply pkg/aws/eni/routing/routing.go:1]: Yes it is just copy-paste. Noted regarding future review, will keep in mind for next time.

File: daemon/cmd/daemon_main.go (hunk 4 above)
Comment (christarazi) [reply daemon/cmd/daemon_main.go]: I think I preemptively moved it after our discussion, but didn't actually verify that it needed to be moved. My guess is no, but I'll double check.

File: cilium-health/launch/endpoint.go (hunk 3 above)
Comment (christarazi) [reply cilium-health/launch/endpoint.go:245]: Thanks, this is good feedback. I'll try this out.

**Comment by christarazi** [comment]
@joestringer Should this be a candidate for 1.7 backports?

**Comment by joestringer** [comment]
@christarazi I think that's reasonable, we'll support v1.7 for a while and risk should be fairly low. We'll be supporting users on v1.7 for a while so having this validation of underlying connectivity could be useful.

**Review by tgraf — APPROVED** [review]
Awesome implementation!

File: daemon/cmd/daemon_main.go (hunk 4 above)
Comment (aanm) [reply daemon/cmd/daemon_main.go]: Not resolved?

**Review by aanm — COMMENTED** [review]
@christarazi based on the conversation with Joe in this PR, I assume this PR is still wip? I'll mark has draft. Feel free to mark it as "Ready for review" and re-request for my and / or Joe's review.

**Comment by christarazi** [comment]
test-me-please

File: daemon/cmd/daemon_main.go (hunk 4 above)
Comment (christarazi) [reply daemon/cmd/daemon_main.go]: Removed. The initialization code didn't need to be moved.

**Comment by christarazi** [comment]
Assuming all tests pass, this PR can be merged. I will create a follow-up addressing the refactoring suggestions.

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
test-gke
