### PR TITLE
ipcache: Add ExternalIP of the local node to ipcache

### LINKED ISSUE #14765: NodePort BPF is not accessible via ExternalIP on GKE and EKS
## Bug report

There is no Service resolution happening when a client inside the cluster tries to connect to a NodePort Service via ExternalIP of the local k8s node.

**General Information**

- Cilium version (run `cilium version`) - 1.8.2
- Kernel version (run `uname -a`) 5.4
- kubeproxyReplacement=strict

**How to reproduce the issue**

1. Create a GKE cluster with Cilium
2. Create a Deployment.

```
cat <<EOF | k apply -f -                                                                                                                                                              
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx  
spec:      
  replicas: 2 
  selector:
    matchLabels:   
      app: nginx
  template:         
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
EOF
```
3. Create a NodePort Service

```
cat <<EOF | kubectl apply -f -                                                                                                                                                        
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
EOF
```

4. Check public IPs of your Nodes and NodePort of `nginx-service`

```
kubectl get nodes -o wide |  awk {'print $1" " $2 " " $7'} | column -t                                                                                                                

NAME                                        STATUS  EXTERNAL-IP
gke-cilium-test-default-pool-ef74a9bc-5lb2  Ready   a.b.c.d
gke-cilium-test-default-pool-ef74a9bc-llzm  Ready   w.x.y.z
```

```
kubectl get svc nginx-service -owide                                                                                                                                                  
NAME            TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE   SELECTOR
nginx-service   NodePort   10.112.12.31   <none>        80:31474/TCP   14s   app=nginx
```

5. Create a test pod that runs on Node with public IP `w.x.y.z` and try to reach NodePort service using public IPs of the node.

```
kubectl run -l app=foo --image=alpine --restart=Never --rm -i -t test
# wget -qO- a.b.c.d:31474
Welcome to nginx!
# wget -qO- w.x.y.z:31474
Connection timeout
```

I used Hubble to observe the packets of `test` pod. It looks like Cilium performed Service resolution for one public IP but not for the other. 

```
TIMESTAMP             SOURCE                                         DESTINATION                                    TYPE          VERDICT     SUMMARY
Jan 28 05:54:14.696   default/test:57540                             w.x.y.z:31474                            to-stack      FORWARDED   TCP Flags: SYN
Jan 28 05:54:28.937   default/test:34148                             default/nginx-deployment-6b474476c4-gh6zn:80   to-stack      FORWARDED   TCP Flags: SYN
Jan 28 05:54:28.937   default/test:34148                             default/nginx-deployment-6b474476c4-gh6zn:80   to-endpoint   FORWARDED   TCP Flags: SYN
Jan 28 05:54:28.937   default/nginx-deployment-6b474476c4-gh6zn:80   default/test:34148                             to-stack      FORWARDED   TCP Flags: SYN, ACK
Jan 28 05:54:28.937   default/nginx-deployment-6b474476c4-gh6zn:80   default/test:34148                             to-endpoint   FORWARDED   TCP Flags: SYN, ACK
Jan 28 05:54:28.937   default/test:34148                             default/nginx-deployment-6b474476c4-gh6zn:80   to-stack      FORWARDED   TCP Flags: ACK
Jan 28 05:54:28.937   default/test:34148                             default/nginx-deployment-6b474476c4-gh6zn:80   to-endpoint   FORWARDED   TCP Flags: ACK
Jan 28 05:54:28.937   default/test:34148                             default/nginx-deployment-6b474476c4-gh6zn:80   to-stack      FORWARDED   TCP Flags: ACK, PSH
Jan 28 05:54:28.937   default/test:34148                             default/nginx-deployment-6b474476c4-gh6zn:80   to-endpoint   FORWARDED   TCP Flags: ACK, PSH
Jan 28 05:54:28.938   default/nginx-deployment-6b474476c4-gh6zn:80   default/test:34148                             to-stack      FORWARDED   TCP Flags: ACK, PSH
Jan 28 05:54:28.938   default/nginx-deployment-6b474476c4-gh6zn:80   default/test:34148                             to-endpoint   FORWARDED   TCP Flags: ACK, PSH
Jan 28 05:54:28.940   default/test:34148                             default/nginx-deployment-6b474476c4-gh6zn:80   to-stack      FORWARDED   TCP Flags: ACK, FIN
Jan 28 05:54:28.940   default/test:34148                             default/nginx-deployment-6b474476c4-gh6zn:80   to-endpoint   FORWARDED   TCP Flags: ACK, FIN
Jan 28 05:54:28.940   default/nginx-deployment-6b474476c4-gh6zn:80   default/test:34148                             to-stack      FORWARDED   TCP Flags: ACK, FIN
Jan 28 05:54:28.940   default/nginx-deployment-6b474476c4-gh6zn:80   default/test:34148                             to-endpoint   FORWARDED   TCP Flags: ACK, FIN
Jan 28 05:54:28.940   default/test:34148                             default/nginx-deployment-6b474476c4-gh6zn:80   to-stack      FORWARDED   TCP Flags: ACK
Jan 28 05:54:28.940   default/test:34148                             default/nginx-deployment-6b474476c4-gh6zn:80   to-endpoint   FORWARDED   TCP Flags: ACK
```

```
# cilium service list
8    10.128.0.28:31474   NodePort       1 => 10.108.1.4:80        
                                        2 => 10.108.0.9:80        
9    0.0.0.0:31474       NodePort       1 => 10.108.1.4:80        
                                        2 => 10.108.0.9:80  
```

Is this an expected behaviour? If yes, then what's the reason for this? If this is a bug, please help me and I can work on fixing this quickly.

### PR DESCRIPTION
**Pull request by AnishShah**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

ExternalIP of the local k8s node is not added to the IPCache. So when a client inside the cluster tries to connect to a NodePort Service via ExternalIP of the local k8s node, no service resolution happens.

Fixes: #14765 

```release-note
Fix a bug that affects connectivity to NodePort service via ExternalIP of the local k8s node.
```

### CODE REVIEW

**Comment by AnishShah** [comment]
@brb  Can you take a look?

**Comment by jibi** [comment]
@AnishShah could you please rebase this branch on top of master (as that should fix the 2 smoke tests that are failing)?

**Comment by AnishShah** [comment]
@jibi Thanks! I rebased it and smoke tests are passing now.

**Comment by pchaigno** [comment]
test-me-please

**Comment by AnishShah** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

**Comment by AnishShah** [comment]
All tests passed :)

**Comment by AnishShah** [comment]
Is it possible to get some review on this as this bug is causing our kubernetes conformance test to fail?

File: pkg/node/address.go [hunk 1]
```diff
@@ -236,6 +237,16 @@ func GetIPv4Router() net.IP {
 	return ipv4RouterAddress
 }
 
+// SetExternalIP sets the external IP node address. It must be a public IP.
+func SetExternalIP(ip net.IP) {
```
Comment (brb) [inline pkg/node/address.go]: I think we should rename this to `SetK8sExternalIP` (same goes to `GetExternalIP`) to better reflect that this is k8s Node ExternalIP rather than a public facing iface IP addr?

Also, what happens in the DualStack setup? Is it possible to have different IP addrs for IPv4 and IPv6? /cc @fristonio

File: pkg/node/address.go [hunk 2]
```diff
@@ -46,6 +46,7 @@ var (
 	ipv6NodePortAddrs map[string]net.IP // iface name => ip addr
 	ipv4AllocRange    *cidr.CIDR
 	ipv6AllocRange    *cidr.CIDR
+	externalAddress   net.IP
```
Comment (brb) [inline pkg/node/address.go]: Could you add a comment saying that this is k8s Node ExternalIP?

**Review by brb — CHANGES_REQUESTED** [review]
Thanks for the PR. Some nits.

Also, I'm not very familiar with the IPCache subsystem. Therefore we need to get a review from @cilium/ipcache

File: pkg/node/address.go (hunk 1 above)
Comment (AnishShah) [reply pkg/node/address.go]: Renamed it to `SetExternalIPv4` and `SetExternalIPv6`. I think in DualStack setup, it is possible to have different IP address for IPV4 and IPV6.

File: pkg/node/address.go (hunk 2 above)
Comment (AnishShah) [reply pkg/node/address.go]: Done.

File: pkg/node/address.go [hunk 3]
```diff
@@ -216,30 +216,30 @@ func GetIPv6AllocRange() *cidr.CIDR {
...
+// SetIPv4Router sets the cilium internal IPv4 node address, it is allocated from the node prefix
+func SetIPv4Router(ip net.IP) {
+	ipv4RouterAddress = ip
 }
 
-// GetInternalIPv4 returns the internal IPv4 node address
-func GetInternalIPv4() net.IP {
-	return ipv4InternalAddress
+// GetIPv4Router returns the cilium internal IPv4 node address
+func GetIPv4Router() net.IP {
```
Comment (joestringer) [inline pkg/node/address.go]: Maybe, `[SG]etInternalIPv4Router()`?

I believe that the intent behind the previous "InternalIPv4()" naming was not to conflate with k8s internal IPs, but instead to hint that this IP address is only relevant internally within the Cilium-managed network (or in the case of direct routing, only within the node). AFAIK Cilium (or the Linux stack) won't respond to ARP for this IP on the native devices, only on the `cilium_host` device. It'd be nice if we could retain this context in the naming and/or godoc here.

File: pkg/k8s/init.go [hunk 4]
```diff
@@ -245,6 +245,9 @@ func WaitForNodeInformation() error {
 
 		node.SetLabels(n.Labels)
 
+		node.SetK8sExternalIPv4(n.GetExternalIP(false))
```
Comment (joestringer) [inline pkg/k8s/init.go:248]: The commit message here says:

> NodePort is not accessible via ExternalIP of the local node. This is
because the ExternalIP of the local node is not added to the IPCache and
hence service resolution does not happen.

The above does not describe whether this was the behaviour before or after this change, and therefore lacks the declaration of intent of what is trying to be achieved. This means it's up to the reader to try to figure out whether you are trying to define what the problem was (and hence what this commit fixes), or what the intended behaviour is (in which case it should match exactly what the code says).

Please consider describing the intent with broader context inside the commit message, roughly:

* *Previously,* accessing a NodePort on the ExternalIP of the node would result in `<behaviour>`. This is because `<reason>`.
* This commit changes/resolves this by adding the local ExternalIP to the ipcache.

File: pkg/node/address.go [hunk 5]
```diff
@@ -236,6 +240,16 @@ func GetIPv4Router() net.IP {
...
 
+// SetK8sExternalIPv4 sets the external IPv4 node address. It must be a public IP.
+func SetK8sExternalIPv4(ip net.IP) {
+	ipv4ExternalAddress = ip
+}
+
+// GetK8sExternalIPv4 returns the external IPv4 node address.
+func GetK8sExternalIPv4() net.IP {
+	return ipv4ExternalAddress
+}
```
Comment (joestringer) [inline pkg/node/address.go]: What's the semantic difference between the `GetIPv4()` and `GetK8sExternalIPv4()`? How does someone in future decide which one to use? Are they really different IP addresses?

File: pkg/k8s/init.go [hunk 6]
```diff
@@ -245,6 +245,9 @@ func WaitForNodeInformation() error {
...
+		node.SetK8sExternalIPv6(n.GetExternalIP(true))
```
Comment (joestringer) [inline pkg/k8s/init.go:249]: Did you intend to do an `if option.Config.EnableIPv4` /  `if option.Config.EnableIPv6`  check here anywhere? At face value I would assume that if the IP protocol is disabled, we should not be attempting to configure that particular IP.

**Review by joestringer — CHANGES_REQUESTED** [review]
Hi @anishshah, thanks for the submission.

The core fix to add the IP to the IPcache makes sense to me. Given that other nodes already have corresponding IPcache entries for the ExternalIPs, I don't think that there are other regular IPcache concerns (such as how it may affect policy, for instance).

I'm a little concerned that we're making the IP address configuration even more confusing in the codebase by renaming & adding yet another (maybe different? maybe not?) IP address to deal with in the node package. It would be helpful for review if there was a description with an overview of the addresses involved in configuration, ideally with examples from a demo cluster. Some of my questions/comments in review below are trying to drive at this question.

This PR also fixes a bug, but there is no accompanying integration test. Logically the argument seems correct, but without a test it's hard to guarantee that this change fixes the issue, and also in future without a test Cilium could easily regress. Maybe @brb has an idea how to bootstrap a simple test to verify this fix (eg, a similar test that this could be based upon)?

File: pkg/k8s/init.go (hunk 6 above)
Comment (AnishShah) [reply pkg/k8s/init.go:249]: I didn't do `if option.Config.EnableIPv4 / if option.Config.EnableIPv6` check here because of the comment on line 232.

https://github.com/cilium/cilium/blob/0c760d8c5b4437e1017eb0ef9c0a74f84e68a6d4/pkg/k8s/init.go#L232-L237

Comment (AnishShah) [reply pkg/k8s/init.go:249]: Should I still add it?

File: pkg/k8s/init.go (hunk 4 above)
Comment (AnishShah) [reply pkg/k8s/init.go:248]: Done. I also added information about `[SG]etK8sExternalIPv4` to the commit.

File: pkg/node/address.go (hunk 3 above)
Comment (AnishShah) [reply pkg/node/address.go]: Done. Added this information in the commit as well as godoc.

File: pkg/node/address.go (hunk 5 above)
Comment (AnishShah) [reply pkg/node/address.go]: Added details to the godoc as well as the commit. Basically,

`GetK8sExternalIPv4()` is strictly an IPv4 address that is routable on the public internet.

`GetIPv4()` can be one of the address with the following priority:
- `NodeInternalIP`
- `NodeExternalIP`
- other IP address types.

**Comment by AnishShah** [comment]
@joestringer Regarding integration test, I have added reproduction steps in the issue #14765. Maybe we can convert it into an integration test. #14728 also documents connectivity test failure on AWS. If this CL fixes that test, is enough?

**Comment by joestringer** [comment]
> #14728 also documents connectivity test failure on AWS. If this CL fixes that test, is enough?

Yes, if https://github.com/cilium/cilium-cli is validating the feature then that's enough.

File: pkg/node/address.go [hunk 7]
```diff
@@ -216,30 +220,55 @@ func GetIPv6AllocRange() *cidr.CIDR {
...
+// - NodeExternalIP
+// - other IP address type.
+// It must be reachable on the network.
+func GetIPv4() net.IP {
+	return ipv4Address
+}
+
+// SetInternalIPv4Router sets the cilium internal IPv4 node address, it is allocated from the node prefix.
+// This must not be conflated with k8s internal IP as this IP address is only relevant within the node.
+// Cilium doesn't respond to ARP for this IP on the native devices, but only on the `cilium_host` device.
```
Comment (joestringer) [inline pkg/node/address.go]: While I believe that this statement is correct today, I don't think it's a good idea to document it here since that behaviour would be subject to entirely different code so this comment could easily be wrong or get out of date as changes are made to the codebase.

```suggestion
```

File: pkg/node/address.go [hunk 8]
```diff
@@ -216,30 +220,55 @@ func GetIPv6AllocRange() *cidr.CIDR {
...
+// - NodeInternalIP
+// - NodeExternalIP
+// - other IP address type.
+// It must be reachable on the network.
+func GetIPv4() net.IP {
+	return ipv4Address
+}
+
+// SetInternalIPv4Router sets the cilium internal IPv4 node address, it is allocated from the node prefix.
+// This must not be conflated with k8s internal IP as this IP address is only relevant within the node.
```
Comment (joestringer) [inline pkg/node/address.go]: I don't think that `only relevant within the node` is quite correct; in some situations, this IP may be used as the IP for host -> remote pod traffic. I would use the terms `only relevant within the Cilium-managed network`.

We could potentially further qualify it by saying that this means "within the node" for direct routing mode or "on the overlay" for tunnel mode, though that might be bordering on too much detail...? :thinking:

File: pkg/k8s/init.go (hunk 6 above)
Comment (joestringer) [reply pkg/k8s/init.go:249]: In that case, maybe not. I presume that these external IPs would be suitable for use from clustermesh given that the requirement is they're publicly routable (though obviously this code is not making such a change as yet).

**Review by joestringer — CHANGES_REQUESTED** [review]
Couple of other minor nits on the new comments. Otherwise it seems fine to me.

File: pkg/node/address.go (hunk 7 above)
Comment (AnishShah) [reply pkg/node/address.go]: Fixed.

File: pkg/node/address.go (hunk 8 above)
Comment (AnishShah) [reply pkg/node/address.go]: Fixed.

**Comment by AnishShah** [comment]
I don't see any integration tests in https://github.com/cilium/cilium-cli. 

But it has connectivity tests https://github.com/cilium/cilium-cli/blob/master/connectivity/test_service.go where it filters packets observed by Hubble. This is exactly what I want to test. Do we have similar test in this repo? @brb @joestringer

**Comment by AnishShah** [comment]
There's two things we can do in the integration test -
1. check `cilium bpf ipcache list` contains external IP of all the nodes.
2. do connectivity test to NodePort service using ExternalIP of the local and use hubble to observe if there was service resolution.

I found this [file](https://github.com/cilium/cilium/blob/1dbc3c2669ea46b78c8d7a904250dce3df3a8d68/test/k8sT/Services.go) where we test BPF NodePort but I don't see it using any external IP. Any idea if the clusters/VM created as a part of integration test have an external IP?

**Comment by brb** [comment]
> I found this file where we test BPF NodePort but I don't see it using any external IP. Any idea if the clusters/VM created as a part of integration test have an external IP?

The tests should be run on GKE (https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline-GKE/). I'd add a test case which checks whether NodePort service is accessible from inside a cluster by sending request to self InternalIP and ExternalIP + NodePort.

**Comment by AnishShah** [comment]
@brb It looks like the tests on GKE runs with kube-proxy only.  https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline-GKE/2958/testReport/Suite-k8s-1/16/

`Nodeport BPF` test was skipped. Am I missing something?

**Comment by AnishShah** [comment]
I have created an initial commit that implements integration test. Let me know if this is a correct direction.

**Comment by brb** [comment]
@AnishShah To me it looks like a correct direction. The following suite should be run on GKE:
```
SkipItIf(helpers.RunsWithoutKubeProxy, "Tests NodePort (kube-proxy)", func() {
			testNodePort(false, false, false, 0)
		})
```
I think on the GKE CI jobs, we have set `kubeProxyReplacement=probe` which should enable the host-reachable services (aka bpf_sock), so it should stress test your change.

File: test/k8sT/Services.go [hunk 9]
```diff
@@ -1124,6 +1130,20 @@ Secondary Interface %s :: IPv4: (%s, %s), IPv6: (%s, %s)`, helpers.DualStackSupp
 			}
 
 			if helpers.RunsOnGKE() {
+				if bpfNodePort && helpers.RunsWithoutKubeProxy() {
```
Comment (brb) [inline test/k8sT/Services.go]: Let's remove the `bpfNodePort && helpers.RunsWithoutKubeProxy()` condition. Otherwise it won't be tested on the current GKE CI job (see https://github.com/cilium/cilium/pull/14793#issuecomment-772379577).

File: test/k8sT/Services.go [hunk 10]
```diff
@@ -93,8 +95,12 @@ var _ = Describe("K8sServicesTest", func() {
 			}
 		}
 
-		k8s1NodeName, k8s1IP = kubectl.GetNodeInfo(helpers.K8s1)
-		k8s2NodeName, k8s2IP = kubectl.GetNodeInfo(helpers.K8s2)
+		k8s1NodeName, k8s1InternalIP = kubectl.GetNodeInfo(helpers.K8s1)
```
Comment (brb) [inline test/k8sT/Services.go]: Nit: can we make `GetNodeInfo` to return both IP addrs?

File: test/k8sT/Services.go (hunk 9 above)
Comment (AnishShah) [reply test/k8sT/Services.go]: Fixed.

File: test/k8sT/Services.go (hunk 10 above)
Comment (AnishShah) [reply test/k8sT/Services.go]: Fixed.

**Comment by AnishShah** [comment]
Can we start GKE CI jobs?

**Comment by brb** [comment]
test-gke

**Comment by brb** [comment]
@AnishShah You can run it by yourself too: https://docs.cilium.io/en/v1.9/contributing/testing/e2e/#running-in-gke

**Comment by pchaigno** [comment]
All CI jobs including GitHub actions seem stuck. I'll try to close/reopen to trigger it. If that doesn't work, you might need to push again.

**Comment by pchaigno** [comment]
test-gke

**Comment by brb** [comment]
test-gke

**Comment by AnishShah** [comment]
I was able to run the tests myself. When I ran the test against HEAD, it failed. When I ran the test with my fix, it passed.

**Comment by AnishShah** [comment]
The tests passed. Is this ready to be merged?

File: test/helpers/kubectl.go [hunk 11]
```diff
@@ -3654,12 +3654,13 @@ func (kub *Kubectl) GetCiliumPodOnNode(node string) (string, error) {
...
-func (kub *Kubectl) GetNodeInfo(label string) (nodeName, nodeIP string) {
+func (kub *Kubectl) GetNodeInfo(label string) (nodeName, nodeInternalIP, nodeExternalIP string) {
 	nodeName, err := kub.GetNodeNameByLabel(label)
 	gomega.ExpectWithOffset(1, err).To(gomega.BeNil(), "Cannot get node by label "+label)
-	nodeIP, err = kub.GetNodeIPByLabel(label, false)
-	gomega.ExpectWithOffset(1, err).Should(gomega.BeNil(), "Can not retrieve Node IP for "+label)
-	return nodeName, nodeIP
+	nodeInternalIP, err = kub.GetNodeIPByLabel(label, false)
+	gomega.ExpectWithOffset(1, err).Should(gomega.BeNil(), "Can not retrieve Node Internal IP for "+label)
+	nodeExternalIP, _ = kub.GetNodeIPByLabel(label, true)
```
Comment (nebril) [inline test/helpers/kubectl.go]: If this ever fails it will be pretty hard to figure it out. Please handle the error with `gomega.ExpectWithOffset(1, err).Should(gomega.BeNil(), "Can not retrieve Node External IP for "+label)`, same as is done for internal IP.

**Review by nebril — CHANGES_REQUESTED** [review]
Thanks for the PR! There is one issue that I think requires fixing in `GetNodeInfo` error handling.

File: test/helpers/kubectl.go (hunk 11 above)
Comment (AnishShah) [reply test/helpers/kubectl.go]: I'm not sure if we should fail in case we can't retrieve ExternalIP. Does all the integration tests include kubernetes node with an external IP?

Comment (AnishShah) [reply test/helpers/kubectl.go]: We return an error if a node does not have any external IP assigned. If all k8s nodes in our integration test has an ExternalIP, then it is safe to fail here. Otherwise this should be fine.

https://github.com/cilium/cilium/blob/e567f8bfa7e8cc4d71566f224f60d7222d3d874b/test/helpers/kubectl.go#L1082-L1100

Comment (nebril) [reply test/helpers/kubectl.go]: These tests can be run on any k8s cluster that is set up to run them ( https://docs.cilium.io/en/v1.9/contributing/testing/e2e/#running-end-to-end-tests-in-other-environments-via-kubeconfig ), lack of handling this error potentially costs a developer debugging the test on a cluster without external IPs non-trivial amount of time. If we just fail the test here saying "there are no external IPs and there should be", we give the developer a clear message on what is wrong with their setup.

Comment (AnishShah) [reply test/helpers/kubectl.go]: The issue is `GetNodeInfo` function is used in many tests including ones that don't need k8s node with externalIPs. So my question was whether all nodes in CIlium CI jobs have external IPs? If not, then the tests will fail even if they didn't need k8s node with externalIPs.

Comment (nebril) [reply test/helpers/kubectl.go]: Ah, I see what you mean. In this case, we should log a warning that the external IP was not retrieved, silently ignoring errors will lead to a lot of frustrations.

**Comment by AnishShah** [comment]
test-me-please

File: test/helpers/kubectl.go (hunk 11 above)
Comment (AnishShah) [reply test/helpers/kubectl.go]: Thanks. I changed things a bit. I try to retrieve ExternalIP of the Node only when we run on GKE as that's when we need it. I fail the test if we can't retrieve it.

**Comment by brb** [comment]
test-me-please

**Review by brb — APPROVED** [review]

**Review by nebril — APPROVED** [review]

**Comment by AnishShah** [comment]
Can we re-run the failing test? I think it is a flake.

**Comment by brb** [comment]
test-net-next

**Comment by brb** [comment]
@joestringer Could you take another look?

File: test/k8sT/Services.go [hunk 12]
```diff
@@ -1124,6 +1124,17 @@ Secondary Interface %s :: IPv4: (%s, %s), IPv6: (%s, %s)`, helpers.DualStackSupp
 			}
 
 			if helpers.RunsOnGKE() {
+				k8s1ExternalIP, err := kubectl.GetNodeIPByLabel(helpers.K8s1, true)
+				Expect(err).Should(BeNil(), "Cannot retrieve Node External IP for"+helpers.K8s1)
```
Comment (christarazi) [inline test/k8sT/Services.go]: `"Cannot retrieve Node External IP for"+helpers.K8s1`

There's no space between `for` and `helpers.K8s1`, could you add spacing in between there?

Also, `Should*` accepts a format string as the second argument, and additional args. For ex:

```
Expect(err).Should(BeNil(), "Cannot retrieve Node External IP for %s", helpers.K8s1)
```

This should be preferred.

File: test/k8sT/Services.go [hunk 13]
```diff
@@ -1124,6 +1124,17 @@ Secondary Interface %s :: IPv4: (%s, %s), IPv6: (%s, %s)`, helpers.DualStackSupp
...
+				k8s2ExternalIP, err := kubectl.GetNodeIPByLabel(helpers.K8s2, true)
+				Expect(err).Should(BeNil(), "Cannot retrieve Node External IP for"+helpers.K8s2)
```
Comment (christarazi) [inline test/k8sT/Services.go]: Same here

**Review by christarazi — CHANGES_REQUESTED** [review]
Thanks for the PR, overall looks good! A few minor nits regarding the e2e test commit:

- See below comments
- Could you rename the commit to `test: Add test to check NodePort service connectivity from inside cluster`? This follows the pattern that exists in our [developer guide](https://docs.cilium.io/en/latest/contributing/development/contributing_guide/#submitting-a-pull-request).
- I noticed that you reference the issue in each commit, even though technically only the first two are needed in order to fix the issue. Therefore, I think it makes more sense to mention the `Fixes` line in the PR body itself and remove them from the individual commits.

File: test/k8sT/Services.go (hunk 12 above)
Comment (AnishShah) [reply test/k8sT/Services.go]: Fixed.

File: test/k8sT/Services.go (hunk 13 above)
Comment (AnishShah) [reply test/k8sT/Services.go]: Fixed.

**Review by christarazi — APPROVED** [review]
:tada:

**Comment by aanm** [comment]
test-me-please

**Comment by AnishShah** [comment]
can someone re-run `test-net-next` as it is flaky?

**Comment by brb** [comment]
test-net-next

**Review by joestringer — APPROVED** [review]
LGTM.

**Comment by joestringer** [comment]
Proxy codeowners changes are negligible and I'm not worried about missing janitor codeowners given that we've had several reviews so we're bound to have looked at the code that's caught by janitor codeowner. CI all passing, good to merge.
