### PR TITLE
ingress/model: Support multiple certs based on SNI

### LINKED ISSUE #22668: ingress: generated envoy config for TLS is incorrect
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. Setup Cilium on Kubernetes 1.25, with Ingress in `loadbalancerMode: "shared"`

<details><summary>Expand: My Helm Configuration Values</summary>

```python
values = {
    "kubeProxyReplacement": "strict",
    "k8sServiceHost": "{snip}",
    "k8sServicePort": "6443",
    "hubble": {
        "tls": {"auto": {"method": "cronJob"}},
        "listenAddress": ":4244",
        "relay": {"enabled": True},
        "ui": {"enabled": True},
    },
    "ipam": {
        "mode": "cluster-pool",
        "operator": {
            "clusterPoolIPv4PodCIDRList": ["10.244.0.0/16"],
            "clusterPoolIPv6PodCIDRList": ["(snip)/112"],
        },
    },
    "bpf": {
      "masquerade": True,
    },
    # needed for bpf masquerade
    "enableIPv6Masquerade": False,
    "ipv6": {
        "enabled": True,
    },
    "ipv4": {
        "enabled": True,
    },
    "k8s": {
        "requireIPv6PodCIDR": True,
        "requireIPv4PodCIDR": True,
    },
    "ingressController": {
        "enabled": True,
        "loadbalancerMode": "shared",
        "enforceHttps": True,
        "service": {
            # Hardcode the shared loadbalancer IP, since lots of external DNS points to it and it should not change easily.
            "annotations": { "metallb.universe.tf/loadBalancerIPs": f"{v4_cidr},{v6_cidr}" },
        },
        # first two are default values, we aren't using them as of 2022
        "ingressLBAnnotationPrefixes": ['service.beta.kubernetes.io', 'service.kubernetes.io', 'metallb.universe.tf'],
    },
}
```

</details>

2. Create two different Ingress in two different namespace, with two different hosts and two different TLS certificates. e.x. `thing1.corp.net` with matching TLS cert, then `thing2.corp.net` with matching TLS cert

3. The envoy config that gets generated looks like (in the ciliumenvoyconfig object for `cilium-ingress` in `kube-system`)...

```yaml
      transportSocket:
        name: envoy.transport_sockets.tls
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          commonTlsContext:
            tlsCertificateSdsSecretConfigs:
            - name: cilium-secrets/thing1-thing1-server-tls
              sdsConfig:
                apiConfigSource:
                  apiType: GRPC
                  grpcServices:
                  - envoyGrpc:
                      clusterName: xds-grpc-cilium
                  transportApiVersion: V3
                resourceApiVersion: V3
            - name: cilium-secrets/thing2-thing2-ingress-tls
              sdsConfig:
                apiConfigSource:
                  apiType: GRPC
                  grpcServices:
                  - envoyGrpc:
                      clusterName: xds-grpc-cilium
                  transportApiVersion: V3
                resourceApiVersion: V3
```

However, according to Envoy docs, specifying the certificates this way means "the first certificate listed is used" -- see https://github.com/envoyproxy/envoy/blob/master/docs/root/intro/arch_overview/security/ssl.rst#certificate-selection. So this means that all Ingresses use `thing1`'s certificate.

Expected behavior: thing1 uses thing1's certificate, and thing2 uses thing2's certificate

Actual behavior: both thing1 and thing2 use thing1's certificate

### Cilium Version

```
cilium-cli: 0.12.11 compiled with go1.19.3 on darwin/arm64
cilium image (default): v1.12.2
cilium image (stable): v1.12.4
cilium image (running): v1.13.0-rc2
```

### Kernel Version

Linux (snip) 6.0.10 #1-NixOS SMP PREEMPT_DYNAMIC Sat Nov 26 08:27:56 UTC 2022 x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:49:09Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sayboras**
## Description

As per [cert-selection] docs, only the first certificate listed is used, this causes the bug in which the wrong certs are used in either Ingress or Gateway API.

This commit is to add serverNames, which are having values same as host name, in TLS filter chain.

[cert-selection]: https://github.com/envoyproxy/envoy/blob/main/docs/root/intro/arch_overview/security/ssl.rst#certificate-selection

Fixes: #22668

Reported-by: Nikhil Jha <hi@nikhiljha.com>
Signed-off-by: Tam Mach <tam.mach@cilium.io>

```release-note
ingress/model: Support multiple certs based on SNI
```

## Testing

Testing was done before and after changes with below manifest

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tls-ingress
  namespace: default
spec:
  ingressClassName: cilium
  rules:
  - host: hipstershop.cilium.rocks
    http:
      paths:
      - backend:
          service:
            name: details
            port:
              number: 9080
        path: /details
        pathType: Prefix
  - host: bookinfo.tam.rocks
    http:
      paths:
      - backend:
          service:
            name: productpage
            port:
              number: 9080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - hipstershop.cilium.rocks
    secretName: demo-cert
  - hosts:
    - bookinfo.tam.rocks
    secretName: demo-tam-cert
```

<details>
<summary>Before</summary>

```
# Error in cilium agent
2022-12-11T11:08:45.476453454Z level=warning msg="Failed to update CiliumEnvoyConfig" ciliumEnvoyConfigName=cilium-ingress error="NACK received: Error adding/updating listener(s) kube-system/cilium-ingress/listener: Failed to load certificate chain from <inline>, at most one certificate of a given type may be specified\n" k8sApiVersion= k8sNamespace=kube-system k8sUID=74722a46-0962-4cf9-9983-06501a9fa0d0 subsys=k8s-watcher

# Generated cilium envoy configuration
...
      transportSocket:
        name: envoy.transport_sockets.tls
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          commonTlsContext:
            tlsCertificateSdsSecretConfigs:
            - name: cilium-secrets/default-demo-tam-cert
              sdsConfig:
                apiConfigSource:
                  apiType: GRPC
                  grpcServices:
                  - envoyGrpc:
                      clusterName: xds-grpc-cilium
                  transportApiVersion: V3
                resourceApiVersion: V3
            - name: cilium-secrets/default-demo-cert
              sdsConfig:
                apiConfigSource:
                  apiType: GRPC
                  grpcServices:
                  - envoyGrpc:
                      clusterName: xds-grpc-cilium
                  transportApiVersion: V3
                resourceApiVersion: V3
...

```

</details>

<details>
<summary>After</summary>

```
...
# Generated Cilium Envoy config
    - filterChainMatch:
        serverNames:
        - bookinfo.tam.rocks
        transportProtocol: tls
      filters:
      - name: envoy.filters.network.http_connection_manager
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          httpFilters:
          - name: envoy.filters.http.router
          rds:
            routeConfigName: listener-secure
          statPrefix: listener-secure
          upgradeConfigs:
          - upgradeType: websocket
      transportSocket:
        name: envoy.transport_sockets.tls
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          commonTlsContext:
            tlsCertificateSdsSecretConfigs:
            - name: cilium-secrets/default-demo-tam-cert
              sdsConfig:
                apiConfigSource:
                  apiType: GRPC
                  grpcServices:
                  - envoyGrpc:
                      clusterName: xds-grpc-cilium
                  transportApiVersion: V3
                resourceApiVersion: V3
    - filterChainMatch:
        serverNames:
        - hipstershop.cilium.rocks
        transportProtocol: tls
      filters:
      - name: envoy.filters.network.http_connection_manager
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          httpFilters:
          - name: envoy.filters.http.router
          rds:
            routeConfigName: listener-secure
          statPrefix: listener-secure
          upgradeConfigs:
          - upgradeType: websocket
      transportSocket:
        name: envoy.transport_sockets.tls
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          commonTlsContext:
            tlsCertificateSdsSecretConfigs:
            - name: cilium-secrets/default-demo-cert
              sdsConfig:
                apiConfigSource:
                  apiType: GRPC
                  grpcServices:
                  - envoyGrpc:
                      clusterName: xds-grpc-cilium
                  transportApiVersion: V3
                resourceApiVersion: V3
...


$ curl -s --cacert minica.pem https://hipstershop.cilium.rocks/details/1
{"id":1,"author":"William Shakespeare","year":1595,"type":"paperback","pages":200,"publisher":"PublisherA","language":"English","ISBN-10":"1234567890","ISBN-13":"123-1234567890"}

$ curl -s --cacert minica.pem https://bookinfo.tam.rocks                
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Bookstore App</title>
...

```

</details>

### CODE REVIEW

**Comment by nikhiljha** [comment]
We're now running [this commit](https://github.com/cilium/cilium/commit/d2fdc7241f14521355253a1efc893e6d1d0a7e37) (~~in production lol~~)-- appears to work :)

Thanks @sayboras !

**Comment by sayboras** [comment]
> We're now running [this commit](https://github.com/cilium/cilium/commit/d2fdc7241f14521355253a1efc893e6d1d0a7e37) (in production lol)-- appears to work :)

Thanks a lot for your issue, as well as the effort in testing the change. This got overlooked as part of another work item in https://github.com/cilium/cilium/issues/19698.

> Support multiple TLSs in envoy downstream context, see https://github.com/cilium/cilium/pull/18867#discussion_r842070230.

**Comment by tklauser** [comment]
I got assigned to review this on behalf of @cilium/operator. The change itself (and the package it touches) looks servicemesh-specific, so I've sent https://github.com/cilium/cilium/pull/22683 such that these kinds of changes get reviewed by @cilium/sig-servicemesh in the future as well.

File: operator/pkg/model/translation/envoy_listener_test.go [hunk 1]
```diff
@@ -49,20 +43,40 @@ func TestNewListener(t *testing.T) {
...
-		require.Equal(t, "dummy-secret-namespace/dummy-namespace-dummy-secret-2", downStreamTLS.CommonTlsContext.TlsCertificateSdsSecretConfigs[1].GetName())
+		secretNames = append(secretNames, downStreamTLS.CommonTlsContext.TlsCertificateSdsSecretConfigs[0].GetName())
+
+		err = proto.Unmarshal(listener.FilterChains[2].TransportSocket.ConfigType.(*envoy_config_core_v3.TransportSocket_TypedConfig).TypedConfig.Value, downStreamTLS)
+		require.NoError(t, err)
+
+		require.Len(t, downStreamTLS.CommonTlsContext.TlsCertificateSdsSecretConfigs, 1)
+		sort.Slice(downStreamTLS.CommonTlsContext.TlsCertificateSdsSecretConfigs, func(i, j int) bool {
+			return downStreamTLS.CommonTlsContext.TlsCertificateSdsSecretConfigs[i].Name < downStreamTLS.CommonTlsContext.TlsCertificateSdsSecretConfigs[j].Name
+		})
```
Comment (pippolo84) [inline operator/pkg/model/translation/envoy_listener_test.go:74]: Since we have just one config at a time, we can avoid the sorting here and at line 63.

**Review by pippolo84 — APPROVED** [review]
Left a comment inline regarding the unit test.
Apart from that, LGTM :rocket:

**Comment by joestringer** [comment]
codeowners for this PR seem to include @cilium/operator , but the code itself doesn't look very relevant to that code owner. Perhaps we could drop that codeowner from these files. For this particular PR, I'm OK to accept the change with just servicemesh review (which was already provided by Fabio above, thanks!)

**Comment by sayboras** [comment]
/test-1.24-5.4

**Comment by sayboras** [comment]
/test-1.26-net-next

File: operator/pkg/model/translation/envoy_listener_test.go (hunk 1 above)
Comment (sayboras) [reply operator/pkg/model/translation/envoy_listener_test.go:74]: good point, let me clean this up in subsequent PR, just to avoid re-run all tests.

**Comment by joestringer** [comment]
Per Slack, the previous failures were:
- https://github.com/cilium/cilium/issues/15455
- https://github.com/cilium/cilium/issues/22750
- Provisioning failure

Tam, if you re-run tests, please provide an explanation like the above that demonstrates why the PR is not at cause for the failures. We have had too many cases recently where we've merged PRs that have blatant issues in them, because PR authors have not triaged the issues and we've ignored the CI in order to merge the PRs.

**Comment by joestringer** [comment]
I've taken a stab at one step forward on #15455, at least some further investigation. It looks like #22750 has recent activity pushing the issue forwards, so I'm not as worried about that one. I'm not sure where to look to improve the reliability of the "provisioning error" cases but if it comes up more frequently then we should spent some time looking deeper into it.

Given that this is a bugfix and a release-blocker, I'll merge this now.
