### PR TITLE
Do not log on errant release of reserved identity

### LINKED ISSUE #23192: Errors and warnings about identity release
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We are experiencing some identity release related errors and warnings ever since we've upgraded Cilium 1.12.2 to 1.12.4 (we are running 1.12.5 at the moment and the errors persist) which are causing our log volume to snowball. 
The logs are:

```level=error msg="Unable to find identity of previously used CIDR" cidr=10.212.176.195/32 subsys=ipcache```

```level=warning msg="Unexpected release of non-CIDR identity, will leak this identity. Please report this issue to the developers." identity=remote-node labels="reserved:remote-node" subsys=ipcache```

Things checked:

When all Cilium agents are restarted these errors go away but after a while they come back and keep increasing over time:
image

Further looking for more information about the IPs present in the error message, we see that these IPs were always used in the past by Kubernetes nodes. Example:
```
level=error msg="Unable to find identity of previously used CIDR" cidr=10.212.176.195/32 subsys=ipcache
```

The associated identity:
```
$ k8s-cilium-exec.sh cilium bpf ipcache list | grep 10.212.176.195
10.212.176.195/32                           identity=16787104 encryptkey=0 tunnelendpoint=0.0.0.0
```

Identity labels (notice the `reserved:remote-node` label in one of the agents):
```
$ k8s-cilium-exec.sh cilium identity get 16787104
...
==== detail from pod cilium-4fmbb , on node ip-10-212-156-19.eu-west-1.compute.internal
ID         LABELS
16787104   cidr:52.218.118.16/32
           reserved:world
==== detail from pod cilium-mthdb , on node ip-10-212-146-165.eu-west-1.compute.internal
ID         LABELS
16787104   cidr:10.212.176.195/32
           reserved:remote-node
           reserved:world
...
```

There also seems to be a correlation with failed `endpoint-delete` API calls as shown:
image
However we couldn't find much information about the reason for these failed calls.

All of this is suggesting that there can be a relationship between these errors logs and IPs that were assigned to nodes in the past but later reused by Pods. It's also worth mentioning that we autoscale nodes and services, as such, IPs are often recycled - here are some metrics for better context:
image

Unfortunately we couldn't replicate this in a test environment.

Happy to share more details if needed.

### Cilium Version

1.12.5

### Kernel Version

Linux ip-10-211-126-220.eu-west-1.compute.internal 5.4.226-129.415.amzn2.x86_64 #1 SMP Fri Dec 9 12:54:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.13-eks-fb459a0", GitCommit:"55bd5d5cb7d32bc35e4e050f536181196fb8c6f7", GitTreeState:"clean", BuildDate:"2022-10-24T20:35:40Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

Cannot share due to sensitive information

### Relevant log output

_No response_

### Anything else?

FWIW, it seems that there were some recent changes to the identity releasing logic that can be related, namely in commits https://github.com/cilium/cilium/commit/5f20d7de700e859abe32f0bcfaf4a237498e7e80 https://github.com/cilium/cilium/commit/adbde6763580c3587648ad3cf39d980049dc88f5.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by asauber**
There have been multiple reports of excessive log pressure due to mistaken invocations of releaseCIDRIdentities with CIDRs that are mapped to a reserved identity. This is a first-pass fix for this overall issue by not logging in this case.

The logging issue, in one case, coincides with this issue which has been fixed:  https://github.com/cilium/cilium/pull/23764

Fixes: #23192

```release-note
Do not log on errant release of reserved identity
```

### CODE REVIEW

File: pkg/ipcache/cidr.go [hunk 1]
```diff
@@ -220,6 +220,15 @@ func (ipc *IPCache) ReleaseCIDRIdentitiesByID(ctx context.Context, identities []
 		if id := ipc.IdentityAllocator.LookupIdentityByID(ctx, nid); id != nil {
 			prefix, ok := cidrLabelToPrefix(id)
 			if !ok {
+				// If we have arrived here because the identity is a
+				// reserved identity, then the caller was mistaken. This
+				// currently has a number of occurrences, in which case we
+				// do not log here because this has caused excessive log
+				// pressure. https://github.com/cilium/cilium/issues/23192
+				if id.IsReserved() {
+					continue
```
Comment (gandro) [inline pkg/ipcache/cidr.go]: While I agree a warning is the wrong log level here, I still I think we should debug log in this case. It's a mistake by the caller, we should not silently ignore that.

**Review by gandro — APPROVED** [review]
