### PR TITLE
api: fix inconsistencies in policy rule marshalling behavior

### LINKED ISSUE #38010: CiliumNetworkPolicy does not marshal to JSON correctly
(I recall seeing some duplicate issues, but I can't find them now)

If you create this sort of network policy:

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-client-to-dns
spec:
  endpointSelector:
    matchLabels:
      app: client
```

but in Go, then serialize to yaml or json, you get
```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-client-to-dns
spec:
  endpointSelector:
    matchLabels:
      any:app: client
```

Note the added `any:app` in the endpointSelector, which is wrong.

We should ensure that policy API types are (practically) unchanged through json -> type -> json conversion

### PR DESCRIPTION
**Pull request by fristonio**
See commit message for details.

EndpointSelector marshalling behavior:
**Before**

image

**After**

image

Fixes: #38010

```release-note
api: fix inconsistencies in policy rule marshalling behavior
```

### CODE REVIEW

File: pkg/policy/api/rule.go [hunk 1]
```diff
@@ -139,7 +139,9 @@ type Rule struct {
 // MarshalJSON returns the JSON encoding of Rule r. We need to overwrite it to
 // enforce omitempty on the EndpointSelector nested structures.
 func (r *Rule) MarshalJSON() ([]byte, error) {
-	type common struct {
+	type ruleInternal struct {
```
Comment (squeed) [inline pkg/policy/api/rule.go]: now that go has omitzero, can we get rid of this MarshalJSON function entirely?

File: pkg/policy/api/selector.go [hunk 2]
```diff
@@ -62,38 +73,26 @@ func (n EndpointSelector) CachedString() string {
...
 }
 
 // MarshalJSON returns a JSON representation of the byte array.
+// If the object is not sanitized, we return the seralized value of
+// underlying selector. When sanitized, we convert the label keys to
+// Cilium's internal representation with source prefix in format
+// `<source>:<key>` before serialization.
 func (n EndpointSelector) MarshalJSON() ([]byte, error) {
 	ls := slim_metav1.LabelSelector{}
-
```
Comment (squeed) [inline pkg/policy/api/selector.go:92]: Can we get rid of this entire function? When we're dumping sanitized (a.k.a. "internal") endpoint selectors, it is an internal representation in which case we might want to preserve the dots.

Comment (fristonio) [reply pkg/policy/api/selector.go:92]: The choice of words here from me might not be the best, by internal representation I meant key format for Cilium(`<source>:<key>`), the internal representation as you said is actually `<source>.<key>`.
I think we should keep the custom marshalling logic if the selector is sanitized. If we remove this custom implementation then marshalling behavior is not idempotent.

For example:
1. Lets say we have a ES - `"endpointSelector": { "matchLabels": { "k8s:label": "value" } }`
2. After sanitizing this becomes - `endpointSelector": { "matchLabels": { "k8s.label": "value" } }`
3. If we now do `Marshal -> Unmarshal -> Sanitize` we end with an additional prefix:
    - `"endpointSelector": { "matchLabels": { "any.k8s.label": "value" } }`

So for each cycle of `Marshal -> Unmarshal -> Sanitize` we keep ending with an additional `any.` prefix. I think once sanitized the marshal behavior should reflect that. This also helps us preserve existing behavior so there will be no side effects to this change. Thougts?

File: pkg/policy/api/rule.go (hunk 1 above)
Comment (fristonio) [reply pkg/policy/api/rule.go]: I was not sure if changing the API type directly will have any side effect. But seems like it doesn't change the generated clientsets and shouldn't have any effect on the unmarshal logic. So yeah we can probably get rid of this 🚀

**Review by qmonnet — APPROVED** [review]
I haven't looked at the changes in detail, I think `docs-structure` was pulled for the changes on `examples/policies/l3/match-expressions/` files - which look OK to me. Thanks! Great to see you active on the project again, welcome back! :slightly_smiling_face:

**Review by aanm — APPROVED** [review]
wow :rocket:

**Review by christarazi — APPROVED** [review]
Nice work!

**Review by derailed — APPROVED** [review]
@fristonio Nice!

File: pkg/policy/api/selector.go (hunk 2 above)
Comment (squeed) [reply pkg/policy/api/selector.go:92]: My only thought is that doing `cilium-dbg policy list` shows the real state of the PolicyRepository, with the source-parsing already done. This may make it easier to debug. However, I agree that making json marshalling consistent is probably more useful. So this seems fine.

**Review by squeed — APPROVED** [review]
Great work!
