### PR TITLE
datapath: Improve sysctl warning for bpf_jit_enable

### LINKED ISSUE #19847: Cilium 1.10.11 is unable to enable eBPF JIT: open /proc/sys/net/core/bpf_jit_enable: no such file or directory
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium logs report:

```
level=warning msg="Failed to sysctl -w" error="could not open the sysctl file /proc/sys/net/core/bpf_jit_enable: open /proc/sys/net/core/bpf_jit_enable: no such file or directory" subsys=sysctl sysParamName=net.core.bpf_jit_enable sysParamValue=1
```

### Cilium Version

1.10.11

### Kernel Version

Ubuntu 5.14.0-1034-oem

### Kubernetes Version

v1.21.1

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by joamaki**
When running Cilium with a KinD or Minikube installation it will be ran in a non-host
network namespace under which many bpf related proc files are not available. Since
it's a common way of testing and developing Cilium, improve the warning so that the
user is not alarmed by this.

The log message under KinD will look like this:
```
  level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.core.bpf_jit_enable sysParamValue=1
  level=warning msg="Could not enable BPF JIT compilation. This can be ignored when running inside non-host network namespace (KinD, Minikube)"
    error="could not open the sysctl file /proc/sys/net/core/bpf_jit_enable: open /proc/sys/net/core/bpf_jit_enable: no such file or directory"
    subsys=sysctl sysParamName=net.core.bpf_jit_enable sysParamValue=1
```
Fixes: #19847

### CODE REVIEW

File: pkg/datapath/loader/base.go [hunk 1]
```diff
@@ -247,7 +247,7 @@ func (l *Loader) Reinitialize(ctx context.Context, o datapath.BaseProgramOwner,
 	args = make([]string, initArgMax)
 
 	sysSettings := []sysctl.Setting{
-		{Name: "net.core.bpf_jit_enable", Val: "1", IgnoreErr: true},
+		{Name: "net.core.bpf_jit_enable", Val: "1", IgnoreErr: true, Warn: "Could not enable BPF JIT compilation. This can be ignored when running inside non-host network namespace (KinD, Minikube)"},
```
Comment (YutaroHayakawa) [inline pkg/datapath/loader/base.go]: "Could not enable BPF JIT compilation" sounds a bit odd to me. In kind or minikube case, we even can't know if it is already enabled or not right? In that case, just telling the fact like "Unable to ensure BPF JIT is enabled" should be sufficient I think.

**Review by YutaroHayakawa — APPROVED** [review]
Made a comment about wording, but the code change looks good to me.

File: pkg/datapath/loader/base.go (hunk 1 above)
Comment (joestringer) [reply pkg/datapath/loader/base.go]: While we're at it, kind upstream just uses `kind` rather than `KinD`, even if that's where then name came from. Should keep consistent with them.

**Review by joestringer — APPROVED** [review]
Tidy fix, thanks. Yutaro's suggestion seems reasonable.

File: pkg/datapath/loader/base.go (hunk 1 above)
Comment (joamaki) [reply pkg/datapath/loader/base.go]: Thanks, applied the suggestions!
