### PR TITLE
pkg/k8s: fix heartbeat unit test flake

### LINKED ISSUE #10750: CI: Travis failed K8sSuite.Test_runHeartbeat
CI failure Link:
arm64: 
    https://travis-ci.com/github/cilium/cilium/jobs/306711137#L1205
x86: 
    https://travis-ci.com/github/cilium/cilium/jobs/305920402#L1314

----------------------------------------------------------------------
FAIL: client_test.go:183: K8sSuite.Test_runHeartbeat
client_test.go:202:
    c.Error("Heartbeat should have closed all connections")
... Error: Heartbeat should have closed all connections
OOPS: 60 passed, 1 skipped, 1 FAILED
--- FAIL: Test (3.43s)

### PR DESCRIPTION
**Pull request by aanm**
Change unit tests to wait for a particular condition to be ready by
polling to avoid flakiness if using selects.

Fix https://github.com/cilium/cilium/issues/10750

Signed-off-by: André Martins <andre@cilium.io>

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

File: pkg/k8s/client_test.go [hunk 1]
```diff
@@ -199,7 +199,11 @@ func (s *K8sSuite) Test_runHeartbeat(c *C) {
 
 	select {
 	case <-time.After(5 * time.Millisecond):
```
Comment (tgraf) [inline pkg/k8s/client_test.go]: Isn't it a lot easier to simply increase this timeout to a couple of seconds?

**Review by tgraf — CHANGES_REQUESTED** [review]

**Comment by aanm** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Review by tgraf — CHANGES_REQUESTED** [review]
Tests still failed:
```
----------------------------------------------------------------------
FAIL: client_test.go:183: K8sSuite.Test_runHeartbeat
client_test.go:228:
    c.Error("Heartbeat should have closed all connections")
... Error: Heartbeat should have closed all connections
```

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-pelase

**Comment by aanm** [comment]
test-me-please

**Comment by borkmann** [comment]
```
FAIL: client_test.go:184: K8sSuite.Test_runHeartbeat
client_test.go:268:
    c.Assert(err, IsNil, Commentf("Heartbeat should have closed all connections"))
... value *errors.errorString = &errors.errorString{s:"timeout reached while waiting for condition"} ("timeout reached while waiting for condition")
... Heartbeat should have closed all connections
OOPS: 60 passed, 1 skipped, 1 FAILED
--- FAIL: Test (2.43s)
```

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

File: pkg/k8s/client_test.go [hunk 2]
```diff
@@ -197,11 +198,16 @@ func (s *K8sSuite) Test_runHeartbeat(c *C) {
 		},
 	)
 
-	select {
-	case <-time.After(5 * time.Millisecond):
-		c.Error("Heartbeat should have closed all connections")
-	case <-called:
-	}
+	err := testutils.WaitUntil(func() bool {
```
Comment (tgraf) [inline pkg/k8s/client_test.go:203]: Please add a comment on why the select in `WaitUntil` is needed. Otherwise, it's not clear why a standard `time.After()` timeout in a single select isn't sufficient.

**Review by tgraf — CHANGES_REQUESTED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by tklauser** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]
