### PR TITLE
option: avoid error on dynamic NAT table size if CT map sizes are static

### LINKED ISSUE #13843: Error on dynamic NAT map sizing with static sizes for CT maps
Timo Reimann [reports on Slack](https://cilium.slack.com/archives/C1MATJ5U5/p1604092720015200?thread_ts=1604075768.489700&cid=C1MATJ5U5), that Cilium fails to start on a 128 GB instance where if the CT maps are statically sized while the NAT map is dynamically sized:

```
Invalid daemon configuration: specified NAT tables size 1185960 must not exceed maximum CT table size 786432
```

The settings they used were:

```
bpf-ct-global-tcp-max: "524288"	
bpf-ct-global-any-max: "262144"
bpf-map-dynamic-size-ratio: "0.0025"
```

### PR DESCRIPTION
**Pull request by tklauser**
If the CT map sizes are configured statically, depending on system
memory and the dynamic ration it might happen that the dynamically
determined size for the NAT table exceeds
(CTMapTCPSize+CTMapAnySize)*2/3 which is leads to an error in
`(*DaemonConfig).checkMapSizeLimits`:

```
Invalid daemon configuration: specified NAT tables size 1185960 must not exceed maximum CT table size 786432
```

Fix this by already capping the dynamically determined NAT table size in
`(*DaemonConfig).calculateDynamicBPFMapSizes` accordingly.

Fixes: #13843
Fixes: 0316bc205d21 ("daemon: add option to dynamically size BPF maps based on system memory")
Reported-by: Timo Reimann on Slack

```release-note
Fix dynamic NAT table size calculation if CT map sizes are configured statically.
```

### CODE REVIEW

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
retest-net-next

File: pkg/option/config.go [hunk 1]
```diff
@@ -3055,6 +3055,12 @@ func (c *DaemonConfig) calculateDynamicBPFMapSizes(totalMemory uint64, dynamicSi
 			getEntries(NATMapEntriesGlobalDefault, LimitTableAutoNatGlobalMin, LimitTableMax)
 		log.Infof("option %s set by dynamic sizing to %v",
 			NATMapEntriesGlobalName, c.NATMapEntriesGlobal)
+		if c.NATMapEntriesGlobal > c.CTMapEntriesGlobalTCP+c.CTMapEntriesGlobalAny {
+			// CT table size was specified manually, make sure that the NAT table size
+			// does not exceed maximum CT table size. See
+			// (*DaemonConfig).checkMapSizeLimits.
+			c.NATMapEntriesGlobal = int((c.CTMapEntriesGlobalTCP + c.CTMapEntriesGlobalAny) * 2 / 3)
```
Comment (pchaigno) [inline pkg/option/config.go]: So in case dynamic sizing is enabled but map sizes are also explicitly specific, we will follow the dynamic sizing up to the explicit size? Do we have a note on that behavior in the documentation already? I think we should also print an info or warning message in logs since several Cilium flags are at odds.

Comment (tklauser) [reply pkg/option/config.go]: I don't think we have a note on that behavior in our docs yet, will add one (as well as a warning message for this case).

**Review by christarazi — APPROVED** [review]

**Comment by tklauser** [comment]
test-me-please

**Review by pchaigno — APPROVED** [review]

**Review by twpayne — APPROVED** [review]
LGTM

**Comment by tklauser** [comment]
retest-net-next

**Comment by tklauser** [comment]
retest-gke

**Review by borkmann — APPROVED** [review]
