### PR TITLE
Extend the CT expiration timeout for egress gateway packets

### LINKED ISSUE #23289: Egress Gateway interrupts long running tcp connections
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Our Pod uses an external Postgres database. The connection is established over a Cilium Egress Gateway and the connection is kept open over quite some time. 
After a few minutes (~15-20 minutes) the TCP connection gets closed improperly. The pod cannot interact with the database any longer. The connection is not re-established.

We found a similar issue here:
https://github.com/cilium/cilium/issues/22377

What we found out so far:
- the problem is not limited to our database connection
  - it is also reproducible with a ssh connection from the pod to an external server (also via Cilium Egress Gateway)
  -  without egress gateway the problem does not occur
- the issue seems only to happen if pod runs on a non-egress node
- if container runs on an egress node, the problem does not occur
- there might be a some issue with the NAT table cleanup of the cilium agent
  - we checked by running `cilium bpf nat list | wc -l` in the cilium agent pod on the egress node
  - if the count goes down, the connection (from pod on non-egress node) is interrupted

helm values:
```
autoDirectNodeRoutes: true
bpf:
  masquerade: true
cluster:
  id: 0
  name: k3s-cluster
egressGateway:
  enabled: true
encryption:
  nodeEncrpytion: false
externalIPs:
  enabled: true
hostPort:
  enabled: true
hubble:
  metrics:
    enabled:
    - dns
    - drop
    - tcp
    - flow
    - icmp
    - http
    serviceMonitor:
      enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
ipam:
  operator:
    clusterPoolIPv4PodCIDR: 10.100.0.0/16
ipv4NativeRoutingCIDR: 10.100.0.0/16
k8sServiceHost: 10.0.0.254
k8sServicePort: 6443
kubeProxyReplacement: strict
l7Proxy: true
loadBalancer:
  mode: dsr
nodePort:
  enabled: true
operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  replicas: 2
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
tunnel: disabled
```

### Cilium Version

1.12.5

### Kernel Version

Linux 5.15.0-56-generic #62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4+k3s1", GitCommit:"0dc63334c0db3e7b99244427615e091909fc486e", GitTreeState:"clean", BuildDate:"2022-11-18T18:17:40Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

_No response_

### Relevant log output

```shell
2023-01-19 06:06:27,587 WARNING  [-] Database settings are not available, using defaults. error: connection already closed
2023-01-19 06:06:27,588 WARNING  [-] Database settings are not available, using defaults. error: connection already closed
2023-01-19 06:08:27,710 WARNING  [-] Database settings are not available, using defaults. error: connection already closed
2023-01-19 06:08:27,711 WARNING  [-] Database settings are not available, using defaults. error: connection already closed
```

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by gentoo-root**
When the SNAT entry already exists for a connection that goes through the egress gateway (i.e. it's not the first packet), ct_lookup4 is skipped. That means that ct_update_timeout is not called, and the CT entry will be garbage collected while the connection is still active.

To fix this bug, do the CT lookups for the second and further packets of connections using egress gateway as well.

Fixes: https://github.com/cilium/cilium/commit/453299601c8c ("bpf: nat: always track egress gateway connections")

Similarly, add connection tracking for egress
gateway reply packets as well, in order to extend the expiration timeout
of the conntrack entry when reply packets arrive.

```release-note
Fix the bug when long-living connections using egress gateway may be reset.
```

### CODE REVIEW

File: bpf/lib/nat.h [hunk 1]
```diff
@@ -1040,6 +1040,8 @@ snat_v4_rev_nat(struct __ctx_buff *ctx, const struct ipv4_nat_target *target)
 
 	if (snat_v4_rev_nat_can_skip(target, &tuple))
 		return NAT_PUNT_TO_STACK;
+	if (egress_gw_rev_snat_ct_needed(ip4))
+		target->egress_gateway = true;
```
Comment (julianwiedmann) [inline bpf/lib/nat.h]: I believe this won't work as-is. The reply hasn't been RevSNATed yet (that only happens in `snat_v4_rewrite_ingress()`), so `ip4->daddr` is still the EgressIP and the packet won't match any EgressGW policy entry. We also don't capture the `from_local_endpoint` condition, so EgressGW replies to local endpoints would get double-accounted.

I wonder if we can simplify the whole logic quite a bit ... when initially creating the SNAT & RevSNAT entries on Egress, just store a `needs_ct` flag into each entry (like the `host_local` flag today - or maybe we can even re-use that flag? It originated from the same purpose). And then just use that flag to decide whether a `ct_lookup()` is needed for subsequent packets.

**Review by julianwiedmann — CHANGES_REQUESTED** [review]
Thanks @gentoo-root! The fix for the outbound direction looks great, I think that on its own should be sufficient to resolve https://github.com/cilium/cilium/issues/23289 already.

The reply direction is a bit trickier, see below.

File: bpf/lib/nat.h (hunk 1 above)
Comment (gentoo-root) [reply bpf/lib/nat.h]: >I believe this won't work as-is. The reply hasn't been RevSNATed yet (that only happens in snat_v4_rewrite_ingress()), so ip4->daddr is still the EgressIP and the packet won't match any EgressGW policy entry.

How does it work for SNAT then? snat_v4_prepare_state also happens before SNAT is performed, and this is the point where `target->egress_gateway = true` is set.

>We also don't capture the from_local_endpoint condition, so EgressGW replies to local endpoints would get double-accounted.

Hmm, for some reason, after going through the code, I thought this was not relevant for the other direction. I'll add the check.

>when initially creating the SNAT & RevSNAT entries on Egress, just store a needs_ct flag into each entry

Great idea, thanks!

Comment (julianwiedmann) [reply bpf/lib/nat.h]: > > I believe this won't work as-is. The reply hasn't been RevSNATed yet (that only happens in snat_v4_rewrite_ingress()), so ip4->daddr is still the EgressIP and the packet won't match any EgressGW policy entry.
> 
> How does it work for SNAT then? snat_v4_prepare_state also happens before SNAT is performed, and this is the point where `target->egress_gateway = true` is set.
> 

On egress SNAT, `ip4->saddr` is the PodIP and `ip4->daddr` is the externalIP. So it matches the policy (and we set `target->egress_gateway` and `target->addr` accordingly). The packet then gets masqueraded with the policy's EgressIP (based on `target->addr`).

Before ingress revSNAT, `ip4->saddr` is the externalIP and `ip4->daddr` is the EgressIP. The revSNAT switches `ip4->daddr` to the PodIP - so now the packet matches the policy entry again.

> > We also don't capture the from_local_endpoint condition, so EgressGW replies to local endpoints would get double-accounted.
> 
> Hmm, for some reason, after going through the code, I thought this was not relevant for the other direction. I'll add the check.
> 

It shouldn't break things completely. But we would update the CT entry here, and then a second time in `to-container`. So every reply packet gets accounted twice.

> > when initially creating the SNAT & RevSNAT entries on Egress, just store a needs_ct flag into each entry
> 
> Great idea, thanks!

Comment (gentoo-root) [reply bpf/lib/nat.h]: Got it, thank you!

Comment (gentoo-root) [reply bpf/lib/nat.h]: I fixed that, please take a look.

Also I think I should add the relevant tests here, including [yours](https://github.com/cilium/cilium/commit/414d8185dce5b750dab87d75ec9e3f5d21ea3fa3).

Comment (julianwiedmann) [reply bpf/lib/nat.h]: Looks good! Cool that we can re-use the existing flag for both cases!

One slightly annoying thing is that we duplicate the `needs_ct` decision logic in two places - `snat_v4_track_connection()` and then again in `snat_v4_new_mapping()`. It was like that already for `host_local`, so no worries. But besides the usual risk of the code drifting apart - I believe we might want to backport this to `v1.12`, and the NAT code is **very** tricky complexity-wise... 

I think we could lift that whole logic into `snat_v4_nat_handle_mapping()`, and drive both functions with it (only call `snat_v4_track_connection()` if needed, pass `needs_ct` as parameter to `snat_v4_new_mapping()`). And then just look at `state->needs_ct` in the revSNAT path. If that doesn't get *too* invasive, I think it's worth doing the change right away  (instead of cleaning up after). wdyt?

Comment (julianwiedmann) [reply bpf/lib/nat.h]: >Also I think I should add the relevant tests here, including [yours](https://github.com/cilium/cilium/commit/414d8185dce5b750dab87d75ec9e3f5d21ea3fa3).

Absolutely! It was a quick hack, but it's good enough to increase the coverage. And we can always improve it later.

Comment (gentoo-root) [reply bpf/lib/nat.h]: I wrote a test for reply packets, and it seems this implementation is still buggy:

```
--- FAIL: TestBPF (3.28s)
    --- FAIL: TestBPF/tc_egressgw_snat.o (0.14s)
        bpf_test.go:231: Conntrack lookup 1/2: src=1.0.168.192:111 dst=1.11.0.110:1234
        bpf_test.go:231: Conntrack lookup 2/2: nexthdr=6 flags=1
        bpf_test.go:231: CT verdict: New, revnat=0
        bpf_test.go:231: Conntrack create: proxy-port=0 revnat=0 src-identity=0 lb=0.0.0.0
        bpf_test.go:231: Failed to map addr=1.11.0.110 to identity
        bpf_test.go:231: Conntrack lookup 1/2: src=1.11.0.110:1234 dst=4.3.2.1:34615
        bpf_test.go:231: Conntrack lookup 2/2: nexthdr=6 flags=0
        bpf_test.go:231: CT verdict: New, revnat=0
        bpf_test.go:231: Conntrack create: proxy-port=0 revnat=0 src-identity=0 lb=0.0.0.0
        --- FAIL: TestBPF/tc_egressgw_snat.o/tc_egressgw_snat2_reply (0.00s)
            bpf_test.go:437: bad RX packet count (expected 1, actual 0)
        bpf_test.go:231: Conntrack lookup 1/2: src=1.0.168.192:111 dst=1.11.0.110:1234
        bpf_test.go:231: Conntrack lookup 2/2: nexthdr=6 flags=1
        bpf_test.go:231: CT entry found lifetime=265870, revnat=0
        bpf_test.go:231: CT verdict: Established, revnat=0
        --- FAIL: TestBPF/tc_egressgw_snat.o/tc_egressgw_snat3 (0.00s)
            bpf_test.go:437: bad RX packet count (expected 1, actual 0)
```

The reply packet doesn't match the CT entry, because revSNAT hasn't been done at that point yet =/

Comment (julianwiedmann) [reply bpf/lib/nat.h]: > The reply packet doesn't match the CT entry, because revSNAT hasn't been done at that point yet =/

:exploding_head: oh joy. Yes, sure looks like it - on egress we're creating the CT_EGRESS entry with the pre-NAT tuple, but on ingress the CT lookup then uses a pre-revNAT tuple. So the CT lookup won't find a match at all, and we just create a new CT_INGRESS entry instead? wow. Are you actually seeing that additional CT entry in your testing?

So we'd basically need to revSNAT the tuple that's used for the lookup. And this is already affecting host-originating connections. Then maybe let's just go with your minimal EgressGW fix after all, and sort out the whole reply-path mess in a separate PR? :disappointed:

Ugh. And it's even more complicated. We're jumping through all sort of hoops to extract the L4 ports in `snat_v4_nat()` - but then `ct_lookup4()` of course does its own extraction again.

Comment (gentoo-root) [reply bpf/lib/nat.h]: >Then maybe let's just go with your minimal EgressGW fix after all, and sort out the whole reply-path mess in a separate PR?

Yes, makes sense, let's deploy the minimal fix, I'll update this pull request and create a follow-up one.

>Are you actually seeing that additional CT entry in your testing?

I'll check that.

Comment (gentoo-root) [reply bpf/lib/nat.h]: Follow-up pull request (not ready yet): https://github.com/cilium/cilium/pull/25112

Please review this one, so that I can progress with the hotfix.

>Are you actually seeing that additional CT entry in your testing?

Yes, I checked that an additional entry is indeed created.

File: bpf/tests/tc_egressgw_snat.c [hunk 2]
```diff
@@ -308,7 +308,18 @@ int egressgw_snat3_setup(struct __ctx_buff *ctx)
...
+	struct egress_gw_policy_key in_key = {
+		.lpm_key = { EGRESS_PREFIX_LEN(24), {} },
+		.saddr   = CLIENT_IP,
+		.daddr   = EXTERNAL_SVC_IP & 0Xffffff,
+	};
+
+	/* Remove the policy to eliminate interference with other tests. */
+	map_delete_elem(&EGRESS_POLICY_MAP, &in_key);
+
+	return ret;
```
Comment (julianwiedmann) [inline bpf/tests/tc_egressgw_snat.c:322]: For my understanding, is that a fix for the existing excluded-CIDR test below? We're using the same key, so it should just overwrite the existing policy entry - no?

File: bpf/lib/nat.h (hunk 1 above)
Comment (julianwiedmann) [reply bpf/lib/nat.h]: >Yes, I checked that an additional entry is indeed created.

nice / ugh. At least that confirms our understanding of the code.

**Review by julianwiedmann — APPROVED** [review]
Thank you, looks good!

**Review by julianwiedmann — APPROVED** [review]

File: bpf/tests/tc_egressgw_snat.c (hunk 2 above)
Comment (gentoo-root) [reply bpf/tests/tc_egressgw_snat.c:322]: >We're using the same key, so it should just overwrite the existing policy entry - no?

I noticed that the excluded-CIDR test below runs first, not last. It's probably because of the alphabetic order.

File: bpf/lib/nat.h [hunk 3]
```diff
@@ -319,17 +319,17 @@ static __always_inline int snat_v4_track_connection(struct __ctx_buff *ctx,
...
-		 * the connection is already tracked).
-		 */
-		else if (target->egress_gateway && !target->from_local_endpoint)
-			needs_ct = true;
+	/* Track egress gateway connections, but only if they are related to a
+	 * remote endpoint (if the endpoint is local then the connection is
+	 * already tracked). NAT_DIR_EGRESS is implied. Do ct_lookup4 also for
+	 * established connections to extend the expiration timeout.
+	 */
+	} else if (target->egress_gateway && !target->from_local_endpoint) {
```
Comment (jibi) [inline bpf/lib/nat.h:328]: nit: I think we can get rid of all these brackes

File: bpf/tests/tc_egressgw_snat.c [hunk 4]
```diff
@@ -149,87 +150,185 @@ int egressgw_snat_check(const struct __ctx_buff *ctx)
...
-int egressgw_skip_excluded_cidr_snat_pktgen(struct __ctx_buff *ctx)
+PKTGEN("tc", "tc_egressgw_snat1")
+int egressgw_snat1_pktgen(struct __ctx_buff *ctx)
 {
-	struct pktgen builder;
-	struct tcphdr *l4;
-	struct ethhdr *l2;
-	struct iphdr *l3;
-	void *data;
+	return egressgw_snat_pktgen(ctx, false);
```
Comment (jibi) [inline bpf/tests/tc_egressgw_snat.c:238]: nit: having an enum (or just defining a couple of constants) would help figuring out more quickly what we are testing

**Review by jibi — APPROVED** [review]
LGTM, thanks again for tacking this! Just a couple of non blocking comments for next time we touch this code

File: bpf/lib/nat.h (hunk 3 above)
Comment (gentoo-root) [reply bpf/lib/nat.h:328]: Speaking of the next time we touch this code, I have a follow-up WIP pull request, and this snippet looks better there:

https://github.com/cilium/cilium/pull/25112/commits/5e81d6d04a2c1908c4afb4dec58fd888fcb678c6#diff-ef710180f228e8f6bbad249e2670dbc42a54f45da3bbc4c5aebbb1f3865979e9R309-R325

(Although still with brackets, but the comments naturally fit inside.)
