### PR TITLE
ipam: Fix overlapping/duplicate PodCIDR allocation when nodes are added while operator is down

### LINKED ISSUE #21482: cilium-operator with IPAM cluster-pool handing out duplicate CIDRs
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I noticed in newly provisioned k8s clusters with cilium we run into network issues where packets are routed to the wrong nodes which resulted in pod crashes and connectivity issues.

Digging further into this I found that cilium had handed out the same pod CIDRs for different machines.

**A rough timeline of how these things happen:**

It's easiest to reproduce when we bootstrap new HA clusters.

- k8s-master-1 node comes up
- cilium-operator (run 1): comes up
- cilium-operator (run 1): acquires lease `kube-system/cilium-operator-resource-lock`
- ciliumnode for the 1st master node is created
- worker-node-1 comes up
- k8s-master-2 comes up
- cilium-operator (run 1): cannot get to master due to leader change, loses leader status and stops itself
- cilium-operator gets restarted by k8s
- cilium-operator (run 2): starts normal and acquires new lease. Is now the leader
- cilium-operator (run 2): starts cluster pool ip allocator
- assigns the pod cidr from k8s-master-1 also to worker-node-1

I did some digging through the code and unless I missed anything it looks like the following happens:

- cilium-operator (run 1): hands out 192.168.0.0/25
- the restart happens
- cilium-operator (run 2): waits for k8s informer caches to be synced
- starts working on the ciliumnode work queue where it initially receives all existing ciliumnodes one by one
- for nodes that have a recorded cidr in the spec it tries to reuse it and learns it
- but nodes that don't have it get a new cidr assigned

It looks to me that this makes it possible that new cidrs are handed out before the mechanism went through all existing nodes. (not 100% sure I was following the path correctly)
If this holds true, then there should probably an initialization phase that first learns about all the cidrs in the cluster before it's allowed to hand out new ones.

This issue is a bit hard to reproduce at first but it can definitely happen to any cluster that uses cluster-pool IPAM and launches a new node while cilium-operator was restarted.

### Cilium Version

Daemon: 1.11.9 4409e95 2022-09-14T15:13:58+02:00 go version go1.17.13 linux/amd64

### Kernel Version

5.10.0-0.bpo.15-amd64 #1 SMP Debian 5.10.120-1~bpo10+1 (2022-06-13) x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.22.12

### Sysdump

Cannot fully disclose 

### Relevant log output

```shell
see attached files
```

### Anything else?

[cilium-operator-run-1.log](https://github.com/cilium/cilium/files/9666214/cilium-operator-run-1.log)
[cilium-operator-run-2.log](https://github.com/cilium/cilium/files/9666215/cilium-operator-run-2.log)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dylandreimerink**
This PR fixes an edge case in the `NodesPodCIDRManager`.
If there were any nodes on operator startup which have no PodCIDRs, the
operator would sometimes assign PodCIDRs to these nodes which have
already been allocated to other nodes.

The operator assumed that when `k8sCiliumNodesCacheSynced` closes, all
node events have been processed. And it proceeds to call `Resync` on
the `nodeManager`.

The `NodesPodCIDRManager` will queue any nodes
without PodCIDRs to be allocated once the `canAllocatePodCIDRs` variable
is set. This variable is set by the `Resync`.

So, the assumption/expected behavior is that the
`NodesPodCIDRManager.Update` function has been called for all nodes in
the cache before `Resync` is called. However, this wasn't the case.
The `startSynchronizingCiliumNodes` function starts the informer
and connects the nodeManager to it. But instead of handling the events
at once, the callbacks enqueue the events, to be handled by a separate
go routine. This means that `k8sCiliumNodesCacheSynced` is closed once
all of the node events are enqueued, not when they have been processed
by the `nodeManager`.

This commit fixes this behavior by processing all events at once
in the informer callbacks until the full sync is complete, at which
point we will switch over to using the workqueue.

Fixes: #21482

```release-note
Fix overlapping/duplicate PodCIDR allocation when nodes are added while operator is down
```

### CODE REVIEW

**Review by gandro — APPROVED** [review]
Really nice find, thanks for fixing this!

File: operator/cmd/allocator_test.go [hunk 1]
```diff
@@ -124,6 +125,14 @@ func TestPodCIDRAllocatorOverlap(t *testing.T) {
...
 	nodeB := nodeBInt.(*cilium_api_v2.CiliumNode)
 
+	if len(nodeA.Spec.IPAM.PodCIDRs) != 1 {
+		t.Fatal("Node A has no PodCIDRs")
+	}
+
+	if len(nodeB.Spec.IPAM.PodCIDRs) != 1 {
+		t.Fatal("Node B has no PodCIDRs")
+	}
+
```
Comment (pchaigno) [inline operator/cmd/allocator_test.go:158]: Shouldn't changes to this file be in the first commit?

File: operator/cmd/cilium_node.go [hunk 2]
```diff
@@ -191,7 +209,16 @@ func startSynchronizingCiliumNodes(ctx context.Context, clientset k8sClient.Clie
...
+					// Only enqueue key if already synced, handle at once while initializing
+					select {
+					case <-k8sCiliumNodesCacheSynced:
+						nodeManagerQueue.Add(key)
+					default:
+						err = nodeManagerSyncHandler(key)
+						if err != nil {
+							log.WithError(err).Errorf("initial sync %q failed with %v", key, err)
+						}
+					}
```
Comment (pchaigno) [inline operator/cmd/cilium_node.go]: We've got the exact same code in three places. Would it be worth refactoring a bit?

**Review by pchaigno — APPROVED** [review]
Thanks for the fix & nice explanation!

The explanation makes sense to me and this is covered by a test, so I think we're good to go, but I'll note I'm not very familiar with this logic and don't understand all consequences this change can have.
Looking at the commit history, @aanm may be a good candidate to review this if nobody else feels confident enough.

File: operator/cmd/allocator_test.go (hunk 1 above)
Comment (dylandreimerink) [reply operator/cmd/allocator_test.go:158]: Yes, that would be cleaner

**Comment by dylandreimerink** [comment]
> note I'm not very familiar with this logic and don't understand all consequences this change can have

Me neither. This change bypasses a queuing / rate limiting mechanism on startup. So it might cause more load on the API server on startup. Digging into the commit history, that doesn't seem to be the reason for introducing the queue.

This [PR](https://github.com/cilium/cilium/pull/17873) introduces the queue, the commit says "this commit introduces the right
way of handling Kubernetes events, with a workqueue" but I am not sure why this is the right way. @aanm could you clarify?

**Comment by gandro** [comment]
@aanm Is unavailable for two weeks. 

An alternative solution which would preserve rate limiting is to enqueue the "k8s cached synced" event as well. Since the queue already allows `any` type to be enqueued, we could enqueue a special "resync" key and invoke `nodeManager.Resync` when we dequeue the key.

**Comment by dylandreimerink** [comment]
> An alternative solution which would preserve rate limiting is to enqueue the "k8s cached synced" event as well. 

Yes, that is also something that crossed my mind. I initially went for this approach because it is the minimal change, and reverts to the behavior of <=v1.10. I don't see the added benefit of the worker queue personally since events are already queued internally in the informer.

I would personally like to refactor this code at some point to use the new [Resources](https://github.com/cilium/cilium/pull/21352). The event handling of the NodeManagers is currently split across packages and files and relies on these global variables to synchronize across at least 3 goroutines. Having each node manager be its own Cell with a dependency on Resource[CiliumNode] and Invoking one of them depending on config. Then making the KVStore synchronization its own Cell would remove a lot of complexity.

**Comment by dylandreimerink** [comment]
All tests green, except for the connectivity test, which has the following error:
```
curl: (22) The requested URL returned error: 503
```
So I guess cloudflare has a bad day, seem unrelated to these changes.

We have decided to merge the fix into master now without waiting for André's feedback. Removing the backport labels for now in case there turns out to be an issue with this. Will re-add the labels as soon as we get the all clear next week.

**Comment by pchaigno** [comment]
> `curl: (22) The requested URL returned error: 503`

In this case it's okay, but there's one case where we can cause a 503, that's when L7 policies are enforced.

**Comment by dylandreimerink** [comment]
> The reason why there's a workqueue instead of processing the event directly from within the informer callbacks is because that processing will actually delay the informer itself. With the workqueue, you receive events and push them into a queue for the work to be done later, without blocking the informer itself.

That is fair, but for the node sync we have our own dedicated `ciliumNodeInformer`. So the only thing we are impacting is the sync to the KVStore which should be handled after `nodeManagerSyncHandler` anyways. So I don't think it matters that much, unless I am missing something

File: operator/cmd/cilium_node.go [hunk 3]
```diff
@@ -145,16 +145,29 @@ func startSynchronizingCiliumNodes(ctx context.Context, clientset k8sClient.Clie
...
+				// Only enqueue key if already synced, handle at once while initializing
+				select {
+				case <-k8sCiliumNodesCacheSynced:
+					nodeManagerQueue.Add(key)
+				default:
+					err = nodeManagerSyncHandler(key)
+					if err != nil {
+						log.WithError(err).Errorf("initial sync %q failed with %v", key, err)
+					}
+				}
```
Comment (christarazi) [inline operator/cmd/cilium_node.go]: @dylandreimerink I think in order to preserve the new behavior, which is more ideal with rate limiting / queuing, Sebastian's idea in https://github.com/cilium/cilium/pull/21526#issuecomment-1267044210 seems like it would be a better way to solve this. I can imagine that in large clusters where the Operator has to sync all CiliumNodes, potentially in the 100s or more, blocking the informer is something we should avoid when possible.

**Review by christarazi — CHANGES_REQUESTED** [review]

**Comment by dylandreimerink** [comment]
Changed the fix to use the solution proposed by @gandro, we now insert a special key in the queue and added a second channel. So we now have the original cacheInSync signal which is closes as soon as the informer has perform the initial sync. The new signal closes as soon as the nodeManager is in sync, which is triggered by consuming the special key from the queue.

File: operator/cmd/cilium_node.go [hunk 4]
```diff
@@ -48,8 +48,11 @@ var (
 	ciliumNodeStore cache.Store
 
 	k8sCiliumNodesCacheSynced = make(chan struct{})
+	ciliumNodeMangerSynced    = make(chan struct{})
```
Comment (christarazi) [inline operator/cmd/cilium_node.go]:
```suggestion
	ciliumNodeManagerSynced    = make(chan struct{})
```

File: operator/cmd/cilium_node.go [hunk 5]
```diff
@@ -48,8 +48,11 @@ var (
...
 )
 
+type CacheInSync struct{}
```
Comment (christarazi) [inline operator/cmd/cilium_node.go]: Does this need to be exported?

Also, we could probably do with a more descriptive name? How about
```suggestion
type ciliumNodeManagerSyncedKey struct{}
```

**Review by christarazi — COMMENTED** [review]
Implementation looks good! A few nits.

**Review by gandro — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Comment by julianwiedmann** [comment]
FYI, resolving the failures in `1.25-net-next` would require a rebase. There are some new/updated tests that depend on recent cilium changes (ie. another case of https://github.com/cilium/cilium/issues/15474).

**Review by nebril — APPROVED** [review]

**Comment by dylandreimerink** [comment]
Now the k8s-1.16-kernel-4.9 fails, which passed before the rebase. The ` Transparent encryption DirectRouting Check connectivity with transparent encryption and direct routing` test failed, which doesn't seem to be related to this PR. So marking as ready-to-merge.

File: operator/cmd/allocator_test.go [hunk 6]
```diff
@@ -0,0 +1,151 @@
...
+	// Sync channel to know when the APIServer state is stable.
+	updated := make(chan struct{})
+	var timer *time.Timer
+
+	// Add a reactor to the fake client, the callback is triggered for each Update to the APIServer.
+	poolReactor := &k8s_testing.SimpleReactor{
+		Verb:     "update",
+		Resource: "ciliumnodes",
+		Reaction: func(action k8s_testing.Action) (handled bool, ret runtime.Object, err error) {
+			// Close `updated` 1 second after the last update
```
Comment (aanm) [inline operator/cmd/allocator_test.go]: Why?

File: operator/cmd/allocator_test.go [hunk 7]
```diff
@@ -0,0 +1,151 @@
...
+		CiliumFakeClientset: fakeClient,
+	}
+
+	// Create a new pod manager with only our IPv4 allocator and fake client set.
+	podCidrManager := podcidr.NewNodesPodCIDRManager([]podcidr.CIDRAllocator{
+		set,
+	}, nil, &ciliumNodeUpdateImplementation{clientset: fakeSet}, nil)
+
+	// start synchronization.
+	if err := startSynchronizingCiliumNodes(context.Background(), fakeSet, podCidrManager, true); err != nil {
```
Comment (aanm) [inline operator/cmd/allocator_test.go]: why is the KVStore set to `true` if it's not configured? We should probably configured it or set it to `false`.

File: operator/cmd/allocator_test.go [hunk 8]
```diff
@@ -0,0 +1,151 @@
...
+		t.Fatal(err)
+	}
+
+	// Wait for the "cache synced" signal, just like we would normally.
+	<-k8sCiliumNodesCacheSynced
+
+	// Trigger the Resync after the cache sync sisgnal
```
Comment (aanm) [inline operator/cmd/allocator_test.go]: `s/sisgnal/signal`

File: operator/cmd/cilium_node.go [hunk 9]
```diff
@@ -48,8 +48,11 @@ var (
 	ciliumNodeStore cache.Store
 
 	k8sCiliumNodesCacheSynced = make(chan struct{})
+	ciliumNodeManagerSynced   = make(chan struct{})
```
Comment (aanm) [inline operator/cmd/cilium_node.go]: I would suggest to either:
a) rename this to `nodeManagerQueueSynced`
b) rename `nodeManagerQueue` to `ciliumNodeManagerQueue` and `ciliumNodeManagerSynced` to `ciliumNodeManagerQueueSynced`

**Review by aanm — CHANGES_REQUESTED** [review]
Nice catch!
Unfortunately the test in the first commit only fails on my side 6 out of 10 times.
I took a look at all other usages of `k8sCiliumNodesCacheSynced` and they have the right behavior.

File: operator/cmd/allocator_test.go (hunk 6 above)
Comment (dylandreimerink) [reply operator/cmd/allocator_test.go]: Later on in the code we block on `updated` the idea here is that we want to know when we are done processing. We don't really have an indicator other than updates on the mocked API server. This detects the burst of updates by closing the channel once we have seen at least one update and it has been 1 second since the last update we have seen.

File: operator/cmd/allocator_test.go (hunk 7 above)
Comment (dylandreimerink) [reply operator/cmd/allocator_test.go]: Yea, I think so, will change that

**Comment by dylandreimerink** [comment]
@aanm 
> Unfortunately the test in the first commit only fails on my side 6 out of 10 times.

Hmm, shit. Didn't run into this myself, it looks like this is because the nodes are stored in `NodesPodCIDRManager.nodesToAllocate` which is a map and then iterated over so the order is randomized each time. I have tried increasing the amount of nodes to make it more likely that we get a map order that triggers the bug, but I still can't get it 100% reliable. Also can't rerun the test x times until it fails due to global state and never stopping goroutines. So I think I can't make it reliable.

Do we leave the test in, in which case it will flake if we ever regress or do we remove the test which leaves us with no regression detection?

**Comment by aanm** [comment]
> @aanm
> 
> > Unfortunately the test in the first commit only fails on my side 6 out of 10 times.
> 
> Hmm, shit. Didn't run into this myself when initially making the test, it looks like this is because the nodes are stored in `NodesPodCIDRManager.nodesToAllocate` which is a map and then iterated over so the order is randomized each time.
> 
> I have tried increasing the amount of nodes to make it more likely that we get a map order that triggers the bug, but I still can't get it 100% reliable. Also can't rerun the test x times until it fails due to global state and never stopping goroutines. So I think I can't make it reliable.
> 
> Do we leave the test in, in which case it will flake if we ever regress or do we remove the test which leaves us with no regression detection?

@dylandreimerink lets keep the test in. Please add a comment in the test stating that if it's flaking it's likely a real failure because its not possible to make it reliable.

**Comment by christarazi** [comment]
@dylandreimerink 

> Also can't rerun the test x times until it fails due to global state and never stopping goroutines. So I think I can't make it reliable.

You can store the global state at test startup and then revert it at test teardown. We do this in a few tests already throughout the code. 

And which goroutines are never stopping? I think we should change the code to make testing more reliable, no?

File: operator/cmd/allocator_test.go (hunk 6 above)
Comment (aanm) [reply operator/cmd/allocator_test.go]: This was a hint to leave a comment in the code since it's not obvious :)

**Review by aanm — CHANGES_REQUESTED** [review]
@dylandreimerink I don't think my previous review was fully addressed :thinking:

**Comment by dylandreimerink** [comment]
> This was a hint to leave a comment in the code since it's not obvious :)

Oh, missed that hint. Added a verbose comment explaining the mechanism, should be clear now.

**Comment by christarazi** [comment]
@dylandreimerink Are you considering https://github.com/cilium/cilium/pull/21526#issuecomment-1276690839?

**Comment by dylandreimerink** [comment]
> You can store the global state at test startup and then revert it at test teardown. We do this in a few tests already throughout the code.
>
> And which goroutines are never stopping? 

I will take a gander at it. Might indeed not be a big an issue as I initially thought. There are two never ending goroutines: [here](https://github.com/cilium/cilium/blob/0c118bbbf5a399ce800963c617f6a024e3d6f37a/operator/cmd/cilium_node.go#L225) and [here](https://github.com/cilium/cilium/blob/0c118bbbf5a399ce800963c617f6a024e3d6f37a/operator/cmd/cilium_node.go#L247). Though both seem to only modify local variables or arguments and do not modify the global state, so I think I can keep them running without issues.

> I think we should change the code to make testing more reliable, no?

Yes. Agreed. This PR was mainly for the actual bug fix, not to improve the operators structure so it is more testable. I would honestly prefer to do that in a separate PR in line with [Jussi's modularization work](https://github.com/cilium/cilium/commit/4bafe1750f7b67fcab4b057c6e1aa9e8b9142584)

**Comment by dylandreimerink** [comment]
I updated the test, to run up to 5 times now which seems to make this test reliable enough to remove the flake warnings. In my testing it typically triggers the bug now in run 1 or 2. This still leaks goroutines, but it doesn't impact this test case. I am writing an issue for the refactoring now

**Review by aanm — CHANGES_REQUESTED** [review]
@dylandreimerink I don't think my previous review was fully addressed :thinking:

**Comment by dylandreimerink** [comment]
@aanm I added my detailed comment on the wrong commit, changed that now, does this address your previous review?

**Comment by pchaigno** [comment]
@dylandreimerink IMO the best way to make sure you didn't miss anything is to mark resolved everything that you think you addressed. If something isn't marked resolved then maybe it was missed?

File: operator/cmd/cilium_node.go (hunk 9 above)
Comment (aanm) [reply operator/cmd/cilium_node.go]: @dylandreimerink I meant this one

Comment (dylandreimerink) [reply operator/cmd/cilium_node.go]: Went for option B, should be good now

**Review by aanm — APPROVED** [review]
