### PR TITLE
pkg/labels: Fix missing source field in policy labels

### LINKED ISSUE #40912: Ciliumnetworkpolicy (re-identify the rule or to store metadata) label src are not populating
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.6 and lower than v1.18.0

### What happened?

If you configure in cnp or ccnp rule with re-indentify label ( https://github.com/cilium/cilium/blob/main/pkg/k8s/apis/cilium.io/client/crds/v2/ciliumnetworkpolicies.yaml#L3457-L3477 ), it's source (k8s?) is missing in flow exports or when checking policy.

### How can we reproduce the issue?

Create cnp or ccnp where rule has identify labels. 

Like this ccnp with labels "key: policy-comment":
```
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: test-01
specs:
- egress:
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: test-01
  endpointSelector:
    matchLabels:
      io.kubernetes.pod.namespace: test-01
  ingress:
  - fromEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: test-01
  labels:
  - key: policy-comment
    value: allow all traffic inside namespace
```

### Cilium Version

1.17.5

### Kernel Version

6.8

### Kubernetes Version

v1.31.4

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

checking with `cilium-dbg policy get` got:

```shell
  {
    "endpointSelector": {
      "matchLabels": {
        "any:io.kubernetes.pod.namespace": "test-01"
      }
    },
    "ingress": [
      {
        "fromEndpoints": [
          {
            "matchLabels": {
              "any:io.kubernetes.pod.namespace": "test-01"
            }
          }
        ]
      }
    ],
    "egress": [
      {
        "toEndpoints": [
          {
            "matchLabels": {
              "any:io.kubernetes.pod.namespace": "test-01"
            }
          }
        ]
      }
    ],
    "labels": [
      {
        "key": "io.cilium.k8s.policy.derived-from",
        "value": "CiliumClusterwideNetworkPolicy",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.name",
        "value": "test-01",
        "source": "k8s"
      },
      {
        "key": "io.cilium.k8s.policy.uid",
        "value": "636a8ce5-88b4-4035-83eb-a5a2c9925372",
        "source": "k8s"
      },
      {
        "key": "policy-comment",
        "value": "allow all inside namespace",
        "source": ""
      }
    ],
    "enableDefaultDeny": {
      "ingress": true,
      "egress": true
    }
  },
```

Also flow exports shows missing source (starts with colon ':' ):

```shell
    "ingress_allowed_by": [
      {
        "name": "test-01",
        "labels": [
          "k8s:io.cilium.k8s.policy.derived-from=CiliumClusterwideNetworkPolicy",
          "k8s:io.cilium.k8s.policy.name=test-01",
          "k8s:io.cilium.k8s.policy.uid=33a24b4e-4f46-4650-aa31-6faa86c3045c",
          ":policy-comment=allow all traffic inside namespace"
        ],
        "revision": "37",
        "kind": "CiliumClusterwideNetworkPolicy"
      }
    ]
```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by pillai-ashwin**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer's Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

## Description

This PR fixes an issue where CiliumNetworkPolicy labels with empty `source` fields were not being assigned a default source value, causing issues in policy debugging and Hubble flow exports.

### Problem
When parsing CiliumNetworkPolicy labels from YAML like:
```yaml
labels:
- key: policy-comment
  value: allow all traffic inside namespace
```

Labels with empty source fields were passed through without any default source assignment, resulting in:
- `cilium-dbg policy get` showing empty source fields: `"source": ""`
- Hubble flow exports showing labels starting with `:` instead of `unspec:` (e.g., `:policy-comment=allow all traffic inside namespace`)
- Policy correlation and debugging difficulties

### Root Cause
The `ParseToCiliumLabels` function in `pkg/k8s/apis/cilium.io/utils/utils.go` was not handling labels with empty source fields. Since CNP `Parse` can be called directly from the policy directory watcher (not just from Kubernetes resources), we cannot assume the label source is always `k8s`.

### Solution
- Modified `ParseToCiliumLabels()` to convert empty source fields to `LabelSourceUnspec` ("unspec")
- Labels with `unspec` source remain as `unspec` (unchanged)
- Labels with explicit sources (k8s, custom, etc.) are preserved as-is
- Added comprehensive unit tests to verify the correct source assignment behavior

### Main idea
Labels with empty source will be set to 'unspec' and will be internally handled as `LabelSourceAny` when required for matching. This ensures consistent behavior across both Kubernetes-sourced policies and directory watcher-sourced policies.

### Testing
- All existing tests pass
- New test case "parse labels with empty source" verifies correct behavior
- Labels now correctly appear as `"unspec:policy-comment=allow all traffic inside namespace"`

Fixes: #40912

```release-note
Fix CiliumNetworkPolicy labels without explicit source field defaulting to empty string instead of "unspec", resolving issues in policy debugging and Hubble flow exports.
```

### CODE REVIEW

**Comment by aanm** [comment]
@squeed @joestringer you have more context to review this one than me.

**Comment by joestringer** [comment]
I'll give @cilium/sig-policy the opportunity for first review on this, lmk if there are specific questions.

**Review by christarazi — COMMENTED** [review]
I think the fix makes sense, but stepping back; shouldn't the source be `k8s` instead of `unspec` if the label being added was done so through k8s labels? I'm not saying the default should be `k8s`, but why isn't the `policy-comment` label that is being picked up by Cilium detected as coming from `k8s` to begin with?

File: pkg/labels/labels.go [hunk 1]
```diff
@@ -474,7 +474,12 @@ func (l *Label) UnmarshalJSON(data []byte) error {
 			return fmt.Errorf("invalid Label: '%s' does not contain label key", data)
 		}
 
-		l.Source = aux.Source
+		// If source is empty, default to LabelSourceUnspec
+		if aux.Source == "" {
```
Comment (fristonio) [inline pkg/labels/labels.go]: Thanks for the fix.
While this seems like a reasonable change, for the issue described this is not what we expect the behavior to be. If the policy is coming from k8s we should assign the source label as K8s instead of unspec.

We parse CiliumNetworkPolicy from k8s to cilium API rule representation here:
https://github.com/cilium/cilium/blob/main/pkg/k8s/apis/cilium.io/utils/utils.go#L383
https://github.com/cilium/cilium/blob/main/pkg/k8s/apis/cilium.io/v2/cnp_types.go#L163
We should make sure that the label source is set to k8s here.

**Review by fristonio — CHANGES_REQUESTED** [review]

File: pkg/labels/labels.go (hunk 1 above)
Comment (pillai-ashwin) [reply pkg/labels/labels.go]: Thanks! done.

File: pkg/k8s/apis/cilium.io/utils/utils.go [hunk 2]
```diff
@@ -399,5 +399,17 @@ func ParseToCiliumLabels(namespace, name string, uid types.UID, ruleLbs labels.L
 	}
 
 	policyLbls := GetPolicyLabels(namespace, name, uid, resourceType)
-	return append(policyLbls, ruleLbs...).Sort()
+
+	// Ensure user-defined labels from CiliumNetworkPolicy have k8s source
+	userLbls := make(labels.LabelArray, len(ruleLbs))
+	for i, lbl := range ruleLbs {
```
Comment (fristonio) [inline pkg/k8s/apis/cilium.io/utils/utils.go:401]: Thanks for the fix. I think we should still keep the old fix you had earlier for `UnmarshalJSON` along with this change. https://github.com/cilium/cilium/commit/948be07daf2e20c863fb1e5b4b5ebd173cd60087
When parsing cilium K8s rule we can check for both Upsec and empty source to populate source as K8s here.

File: pkg/k8s/apis/cilium.io/utils/policy_label_test.go [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+import (
+	"testing"
+
+	"github.com/stretchr/testify/require"
+	"k8s.io/apimachinery/pkg/types"
+
+	"github.com/cilium/cilium/pkg/labels"
+)
+
+// TestPolicyLabelSourceFix tests the fix for issue #40912
```
Comment (fristonio) [inline pkg/k8s/apis/cilium.io/utils/policy_label_test.go]: nit: I don't think we need to reference the issue here.

File: pkg/k8s/apis/cilium.io/utils/policy_label_test.go [hunk 4]
```diff
@@ -0,0 +1,63 @@
...
+// where CiliumNetworkPolicy labels without explicit source field
+// were getting empty source instead of being set to "k8s" source.
+func TestPolicyLabelSourceFix(t *testing.T) {
```
Comment (fristonio) [inline pkg/k8s/apis/cilium.io/utils/policy_label_test.go]: nit:
```suggestion
func TestParseToCiliumLabels(t *testing.T) {
```

**Review by fristonio — CHANGES_REQUESTED** [review]
One comment and a minor nit.

File: pkg/k8s/apis/cilium.io/utils/policy_label_test.go (hunk 4 above)
Comment (pillai-ashwin) [reply pkg/k8s/apis/cilium.io/utils/policy_label_test.go]: There's already a `TestParseToCiliumLabels` function in `utils_test.go` so can't do that.

File: pkg/k8s/apis/cilium.io/utils/utils.go (hunk 2 above)
Comment (pillai-ashwin) [reply pkg/k8s/apis/cilium.io/utils/utils.go:401]: Done!

File: pkg/k8s/apis/cilium.io/utils/policy_label_test.go (hunk 4 above)
Comment (fristonio) [reply pkg/k8s/apis/cilium.io/utils/policy_label_test.go]: I think it makes more sense to extend the existing test cases in `TestParseToCiliumLabels` instead of creating a new test(or file). This test is already testing the codepath but needs these additional scenario to cover the changes in this PR.

File: pkg/labels/labels.go (hunk 1 above)
Comment (squeed) [reply pkg/labels/labels.go]: Are we sure this is right? We previously had a bug where Cilium network policy objects were not JSON round-trip-able. In other words, if you parse a JSON / YAML to the `CiliumNetworkPolicy` type, then re-export to YAML, the result was distinct (and invalid for submission to the apiserver). I would prefer JSON unmarshal-marshal to have no effect.

Comment (fristonio) [reply pkg/labels/labels.go]: Thats a good point. However, in this particular case the Label itself is represented as a [struct of source,key,value fields](https://github.com/cilium/cilium/blob/main/pkg/labels/labels.go#L170) so it is round-trip-able(this is cilium internal label not k8s). But it does mean that Unmarshal/Marshal on the Label will yield a different result(Source as Unspec vs empty) but functionally its idempotent as we treat both the same way.
I don't have a strong opinion, but given we have had issues in the past with custom marshalling logic, I would also lean towards not changing the semantics during unmarshal.

@pillai-ashwin sorry for the back and forth on this, but what are your thoughts?

File: pkg/k8s/apis/cilium.io/utils/policy_label_test.go (hunk 4 above)
Comment (pillai-ashwin) [reply pkg/k8s/apis/cilium.io/utils/policy_label_test.go]: Yes, that would be easier too. Moved the test cases to `TestParseToCiliumLabels`.

File: pkg/labels/labels.go (hunk 1 above)
Comment (fristonio) [reply pkg/labels/labels.go]: As discussed in community meeting @pillai-ashwin I think we want to avoid this custom Unmarshal behavior for cilium api types. Lets remove the changes here and assume that correct source will be populated once the CNP is parsed.

**Review by fristonio — CHANGES_REQUESTED** [review]

File: pkg/labels/labels.go (hunk 1 above)
Comment (pillai-ashwin) [reply pkg/labels/labels.go]: Thanks for the review @fristonio! Made changes -
* Removed the custom unmarshaling behavior that defaulted empty sources to "unspec"
* Removed test cases that tested the UnmarshalJSON defaulting behavior

**Review by fristonio — APPROVED** [review]
Thanks for the contribution. LGTM <3

**Review by squeed — APPROVED** [review]
Nice!

**Comment by squeed** [comment]
Note that the failing tests are real -- you'll have to look in to them.

**Comment by pillai-ashwin** [comment]
> Note that the failing tests are real -- you'll have to look in to them.

fixed it! The integration test was failing because the initial fix was converting both empty ("") AND "unspec" sources to "k8s" but the test expected "unspec" labels to remain as "unspec".

```
// Before (caused test failure)
if lbl.Source == "" || lbl.Source == labels.LabelSourceUnspec {
    userLbls[i] = labels.NewLabel(lbl.Key, lbl.Value, labels.LabelSourceK8s)

// After (correct fix)
if lbl.Source == "" {
    userLbls[i] = labels.NewLabel(lbl.Key, lbl.Value, labels.LabelSourceK8s)
```

**Comment by fristonio** [comment]
Hey @pillai-ashwin  The initial fix I suggested was under the assumption that a label from these utilities can only be parsed in context of k8s types(CNP/CCNP), so converting empty/unspec source to k8s made sense. The latest change seem to be introducing inconsistent behavior, ideally `Unspec` and `Empty` source should yield the same parsed labels. So we should either:

1. Set source as `k8s` for both `empty` and `unspec` and fix the failing tests to conform with this behavior.
2. Set source as `unspec` if input label has empty source.

I don't have a strong opinion either way. @squeed thoughts?

**Comment by pillai-ashwin** [comment]
@fristonio My understanding now is that both empty and unspec sources represent the same semantic concept - "user didn't specify a source" - and since `ParseToCiliumLabels` only operates in Kubernetes CNP/CCNP context. So, both should logically result in `k8s` source.

I can go with convert both empty and unspec sources to `k8s`, and update the failing test to expect this consistent behavior. This makes more semantic sense since all user-defined labels in CNP context should have `k8s` source.

The test was expecting unspec to remain unspec, but that was based on the old inconsistent behavior. The correct expectation should be that all user labels in CNP context get `k8s` source.

File: pkg/k8s/apis/cilium.io/utils/utils.go [hunk 5]
```diff
@@ -395,5 +395,17 @@ func ParseToCiliumLabels(namespace, name string, uid types.UID, ruleLbs labels.L
...
+		if lbl.Source == "" || lbl.Source == labels.LabelSourceUnspec {
```
Comment (fristonio) [inline pkg/k8s/apis/cilium.io/utils/utils.go]: Hey @pillai-ashwin 
Looking at the changes again, I missed that CNP `Parse` can be called directly from policy directory watcher as well. In that case, its incorrect to assume that the label source is k8s by default if not specified. I think the correct behavior will be to set the label source as unspec if empty. This will be internally handled as `LabelSourceAny` when required for matching.
Sorry for the back and forth on this.

**Review by fristonio — CHANGES_REQUESTED** [review]

File: pkg/k8s/apis/cilium.io/utils/utils.go (hunk 5 above)
Comment (pillai-ashwin) [reply pkg/k8s/apis/cilium.io/utils/utils.go]: Thanks for the review! Hmm yeah - CNP `Parse` can be called from the policy directory watcher, so we can't assume k8s source.

```go
if lbl.Source == "" {
    // If source is empty, set it to unspec
    userLbls[i] = labels.NewLabel(lbl.Key, lbl.Value, labels.LabelSourceUnspec)
} else {
    userLbls[i] = lbl
}
```

This will now ensure correct behavior for both Kubernetes-sourced CNPs and directory watcher-sourced CNPs. The labels with empty source will be internally handled as `LabelSourceAny` when needed for matching.

**Comment by pillai-ashwin** [comment]
@fristonio the failing test seems to be unrelated.

**Comment by fristonio** [comment]
Yeah, it seems like a known flake - https://github.com/cilium/cilium/issues/42124
I have retried the job, lets see if that helps.

**Review by fristonio — APPROVED** [review]
