### PR TITLE
fix(socketlb): only detach cilium-owned cgroup programs

### LINKED ISSUE #43877: Failure detaching non-Cilium BPF cgroup programs
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.18.6 and lower than v1.19.0

### What happened?

When the BPF load balancer is disabled, and a non-Cilium application on the node is using its own BPF cgroup programs within the root/main cgroup, on restart Cilium will try to detach them and report a failure:

```
level=warn source=/go/src/github.com/cilium/cilium/pkg/datapath/orchestrator/orchestrator.go:220 msg="Failed to initialize datapath, retrying later" module=agent.datapath.orchestrator error="detach cgroup: detach programs from cgroup /run/cilium/cgroupv2 attach type CGroupInet4Connect: can't detach program: no such file or directory" retryDelay=10s
level=debug source=/go/src/github.com/cilium/cilium/pkg/hive/health/provider.go:89 msg="upserting health status" module=health lastLevel=OK reporter-id=agent.datapath.orchestrator.job-reinitialize status="agent.datapath.orchestrator.job-reinitialize: [Degraded] Failed to reinitialize datapath: detach cgroup: detach programs from cgroup /run/cilium/cgroupv2 attach type CGroupInet4Connect: can't detach program: no such file or directory"
```

They fail to be detached because the non-Cilium process is still using them.

Cilium status is reported as OK and health seems fine so I'm not sure whether this affects any functionality.

This seems to happen due to Cilium trying to detach all BPF programs, even those of other processes, in the root/main cgroup with relevant attachment types if Cilium's BPF pins can't be found. The pins are only created if BPF load balancer is enabled.
https://github.com/cilium/cilium/blob/e75169db3fb77d3dfe4fc7805fd8a397697fd4cf/pkg/socketlb/cgroup.go#L231-L251

Ideally, Cilium should only attempt to detach programs which belong to it, to reduce risk of affecting other applications. This could be done by checking the program name starts with `cil_` before detaching it.

### How can we reproduce the issue?

1. Install Cilium
2. Build the cgroup example from https://github.com/cilium/ebpf/tree/main/examples/cgroup_skb but with the below patch
3. Place the built example on the node and run it as root
4. Restart Cilium pod
5. Check Cilium pod logs

```
diff --git a/examples/cgroup_skb/cgroup_skb.c b/examples/cgroup_skb/cgroup_skb.c
index a9879df..1066e43 100644
--- a/examples/cgroup_skb/cgroup_skb.c
+++ b/examples/cgroup_skb/cgroup_skb.c
@@ -11,17 +11,7 @@ struct {
        __uint(max_entries, 1);
 } pkt_count SEC(".maps");
 
-SEC("cgroup_skb/egress")
+SEC("cgroup/connect4")
 int count_egress_packets(struct __sk_buff *skb) {
-       u32 key      = 0;
-       u64 init_val = 1;
-
-       u64 *count = bpf_map_lookup_elem(&pkt_count, &key);
-       if (!count) {
-               bpf_map_update_elem(&pkt_count, &key, &init_val, BPF_ANY);
-               return 1;
-       }
-       __sync_fetch_and_add(count, 1);
-
        return 1;
 }
diff --git a/examples/cgroup_skb/main.go b/examples/cgroup_skb/main.go
index 57edfc8..e73dc4a 100644
--- a/examples/cgroup_skb/main.go
+++ b/examples/cgroup_skb/main.go
@@ -43,7 +43,7 @@ func main() {
        // Link the count_egress_packets program to the cgroup.
        l, err := link.AttachCgroup(link.CgroupOptions{
                Path:    cgroupPath,
-               Attach:  ebpf.AttachCGroupInetEgress,
+               Attach:  ebpf.AttachCGroupInet4Connect,
                Program: objs.CountEgressPackets,
        })
        if err != nil {
```

### Cilium Version

cilium-cli: v0.18.9 compiled with go1.25.5 on linux/amd64
cilium image (default): v1.18.3
cilium image (stable): v1.18.6
cilium image (running): 1.18.6

### Kernel Version

Linux 6.14.0-37-generic #37~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.34.3
Kustomize Version: v5.7.1
Server Version: v1.34.0

### Regression

_No response_

### Sysdump

[cilium-sysdump-20260119-174905.zip](https://github.com/user-attachments/files/24721780/cilium-sysdump-20260119-174905.zip)

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by puwun**
When detaching BPF cgroup programs, check if the program name starts with `'cil_'` before detaching. This prevents cilium from accidentally detaching programs belonging to other applications on the node.

Previously, cilium would detach all programs of a given attach type from the cgroup, causing errors when other applications had their own BPF programs attached.

Fixes: #43877

```release-note
fix(socketlb): only detach Cilium-owned cgroup programs
```

### CODE REVIEW

**Comment by pchaigno** [comment]
@puwun The Conformance Cluster Mesh failures persist so could you try to rebase on latest main and we'll see if that fixes it? I don't see how it could be related to your changes.

**Comment by puwun** [comment]
@pchaigno thanks, done 👍🏼

**Comment by joestringer** [comment]
During the community meeting, we triaged this PR. The [ginkgo](https://github.com/cilium/cilium/actions/runs/21913180965/job/63273542271#step:12:400) and [ipsec](https://github.com/cilium/cilium/actions/runs/21913177062/job/63272909791#step:27:116) workflows failed hitting timeouts, in part due to the LVH VM initialization taking too long. The [integration test failure](https://github.com/cilium/cilium/actions/runs/21913193074/job/63272884358#step:18:119) looks like an instance of https://github.com/cilium/cilium/issues/44414, already fixed in `main`. So I don't think the test results are providing meaningful feedback.

Next step is for @cilium/loader / @ti-mo to review

File: pkg/socketlb/cgroup_test.go [hunk 1]
```diff
@@ -191,3 +191,86 @@ func TestPrivilegedDetachCGroupWithExistingLink(t *testing.T) {
...
 }
+
+// Verify that non-Cilium programs (programs without "cil_" prefix) are preserved
+// during cgroup detachment. This is a regression test for issue #43877.
+func TestPrivilegedDetachCGroupPreservesNonCiliumPrograms(t *testing.T) {
+	testutils.PrivilegedTest(t)
+	logger := hivetest.Logger(t)
+
+	// Create a program with a name that does NOT start with "cil_"
+	nonCiliumProg, err := ebpf.NewProgram(&ebpf.ProgramSpec{
```
Comment (ti-mo) [inline pkg/socketlb/cgroup_test.go]: Why not use `mustCgroupProgram` here? It creates programs with empty names, should work fine for this purpose.

File: pkg/socketlb/cgroup_test.go [hunk 2]
```diff
@@ -191,3 +191,86 @@ func TestPrivilegedDetachCGroupWithExistingLink(t *testing.T) {
...
+	})
+	if err != nil {
+		t.Skipf("cgroup sockaddr programs not supported: %s", err)
+	}
+	defer nonCiliumProg.Close()
+
+	linkPath := testutils.TempBPFFS(t)
+	cgroupPath := testutils.TempCgroup(t)
+	f, err := os.Open(cgroupPath)
+	if err != nil {
```
Comment (ti-mo) [inline pkg/socketlb/cgroup_test.go]: Let's use `require`/`assert` in new tests please.

File: pkg/socketlb/cgroup_test.go [hunk 3]
```diff
@@ -191,3 +191,86 @@ func TestPrivilegedDetachCGroupWithExistingLink(t *testing.T) {
...
+	// Query the cgroup to verify the non-Cilium program is still attached
+	ids, err := link.QueryPrograms(link.QueryOptions{
+		Target: int(f.Fd()),
+		Attach: ebpf.AttachCGroupInet4Connect,
+	})
+	if err != nil {
+		t.Fatalf("failed to query cgroup programs: %s", err)
+	}
+
+	if len(ids.Programs) == 0 {
```
Comment (ti-mo) [inline pkg/socketlb/cgroup_test.go]: I'd assert len == 1 here if we're going to access `Programs[0]` later.

File: pkg/socketlb/cgroup_test.go [hunk 4]
```diff
@@ -191,3 +191,86 @@ func TestPrivilegedDetachCGroupWithExistingLink(t *testing.T) {
...
+	info, err := prog.Info()
+	if err != nil {
+		t.Fatalf("failed to get program info: %s", err)
+	}
+	if info.Name != "other_app_prog" {
+		t.Fatalf("expected program name 'other_app_prog', got '%s'", info.Name)
+	}
+
+	// Clean up: manually detach the non-Cilium program
+	if err := link.RawDetachProgram(link.RawDetachProgramOptions{
```
Comment (ti-mo) [inline pkg/socketlb/cgroup_test.go]: Do this in a `t.Cleanup` registered after a successful `RawAttachProgram`.

File: pkg/socketlb/cgroup.go
Comment (ti-mo) [inline pkg/socketlb/cgroup.go]: Looks like this assumption is no longer valid then, this comment will need to be changed.

File: pkg/socketlb/cgroup.go [hunk 5]
```diff
@@ -233,10 +238,24 @@ func detachAll(logger *slog.Logger, attach ebpf.AttachType, cgroupRoot string) e
...
 		defer prog.Close()
 
+		// Only detach programs that belong to Cilium (name starts with "cil_").
+		// This prevents accidentally detaching programs from other applications.
+		info, err := prog.Info()
+		if err != nil {
+			return fmt.Errorf("could not get info for program id %d: %w", id.ID, err)
+		}
+		if !strings.HasPrefix(info.Name, ciliumProgPrefix) {
+			logger.Debug("Skipping non-Cilium program",
```
Comment (ti-mo) [inline pkg/socketlb/cgroup.go]: I don't think this log statement is really useful, and it doesn't contain any context. (Skipped where? Why?) Feel free to remove it.

File: pkg/socketlb/cgroup.go [hunk 6]
```diff
@@ -233,10 +238,24 @@ func detachAll(logger *slog.Logger, attach ebpf.AttachType, cgroupRoot string) e
...
 		}
 		defer prog.Close()
 
+		// Only detach programs that belong to Cilium (name starts with "cil_").
+		// This prevents accidentally detaching programs from other applications.
+		info, err := prog.Info()
+		if err != nil {
+			return fmt.Errorf("could not get info for program id %d: %w", id.ID, err)
+		}
+		if !strings.HasPrefix(info.Name, ciliumProgPrefix) {
```
Comment (ti-mo) [inline pkg/socketlb/cgroup.go]: This may sound counter-intuitive, but I've removed a few of these`"cil_"` constants lately, since there were multiple. I just inlined them. Feel free to do the same here, I should really just make a single helper for this across the code base.

**Review by ti-mo — COMMENTED** [review]
Thanks for picking this up, left a few nits.

**Comment by derailed** [comment]
@puwun There are a few issues to resolve. Could you take a peek?

**Comment by puwun** [comment]
@ti-mo @derailed  thanks, updated 👍🏼

**Comment by joestringer** [comment]
The smoke tests are failing, but if you rebase against the tip of main then I think that should be fixed.

**Review by ti-mo — APPROVED** [review]
Thanks!

**Comment by joestringer** [comment]
We were reviewing PRs during the community meeting and noticed this needed a rebase + re-run the tests, so I rebased and re-ran the tests.
