### PR TITLE
Service / LoadBalancer synchronization fixes

### LINKED ISSUE #1295: cilium service delete after restarting cilium-agent fails
```
+ cilium service delete --all
ERRO[0000] Cannot delete service 6: [DELETE /service/{id}][500] deleteServiceIdFailure  Unable to delete element: no such file or directory
ERRO[0000] Cannot delete service 7: [DELETE /service/{id}][404] deleteServiceIdNotFound
ERRO[0000] Cannot delete service 1: [DELETE /service/{id}][500] deleteServiceIdFailure  Unable to delete element: no such file or directory
ERRO[0000] Cannot delete service 2: [DELETE /service/{id}][500] deleteServiceIdFailure  Unable to delete element: no such file or directory
ERRO[0000] Cannot delete service 3: [DELETE /service/{id}][500] deleteServiceIdFailure  Unable to delete element: no such file or directory
ERRO[0000] Cannot delete service 4: [DELETE /service/{id}][500] deleteServiceIdFailure  Unable to delete element: no such file or directory
```

### PR DESCRIPTION
**Pull request by ianvernon**
* common/types: add String() function for LBBackend & L3n4AddrID, add Slave
member to L3n4AddrID, add debug logs throughout, and update LBSVC object
with its SHA256 hash.
* daemon: clean all LB, RevNAT maps on host when restore mode is not enabled.
Add debug logs in the service-related code. When a service is updated or
deleted, clean BPF LB maps of old map entries for the given service. Fix
logic for syncing Cilium's LB maps with the BPF maps on disk when Cilium is
restarted and restore mode is enabled.
* pkg/maps/lbmap: add logs when services or RevNAT entries change state.
* tests: refactor 06-lb.sh into functions to reduce duplicate code, and add
test that ensures restore mode works appropriately for LB Maps when Cilium
is restarted.
    
Signed-off by: Ian Vernon <ian@cilium.io>
Fixes #1295

### CODE REVIEW

**Comment by ianvernon** [comment]
Hitting an issue in the K8s multinode tests which I haven't seen before, so I'm removing this from pending-review until I can get those tests passing.

File: common/types/loadbalancer.go [hunk 1]
```diff
@@ -47,6 +48,10 @@ type LBBackEnd struct {
 	Weight uint16
 }
 
+func (lbbe *LBBackEnd) String() string {
+	return fmt.Sprintf("%s, weight: %d", lbbe.L3n4Addr.String(), lbbe.Weight)
```
Comment (aanm) [inline common/types/loadbalancer.go:53]: Isn't there a String() already for this? I was 80% sure there was.

File: daemon/loadbalancer.go [hunk 2]
```diff
@@ -32,6 +32,10 @@ import (
 // RevNAT value (feCilium.L3n4Addr) to the lb's RevNAT map for the given feCilium.ID.
 func (d *Daemon) addSVC2BPFMap(feCilium types.L3n4AddrID, feBPF lbmap.ServiceKey,
 	besBPF []lbmap.ServiceValue, addRevNAT bool) error {
+	log.Debugf("adding service %d to BPF maps", feCilium.ID)
+
+	// Try to delete service before adding it and ignore errors as it might not exist.
+	_ = d.svcDeleteByFrontendLocked(&feCilium.L3n4Addr)
```
Comment (aanm) [inline daemon/loadbalancer.go]: at least run the erros in debug mode.

File: daemon/loadbalancer.go [hunk 3]
```diff
@@ -182,47 +191,89 @@ func (h *deleteServiceID) Handle(params DeleteServiceIDParams) middleware.Respon
...
+	if err != nil {
+		return fmt.Errorf("key %s is not in lbmap", svcKey.ToNetwork())
 	}
 
-	d.loadBalancer.DeleteService(svc)
+	vval := val.(lbmap.ServiceValue)
+	numBackends := uint16(vval.GetCount())
+
+	// ServiceKeys are unique by their slave number, which corresponds to the number of backends. Delete each of these.
+	for i := numBackends; i > 0; i-- {
```
Comment (aanm) [inline daemon/loadbalancer.go:262]: Do you need to delete all map entries?

File: daemon/loadbalancer.go [hunk 4]
```diff
@@ -502,33 +537,59 @@ func (d *Daemon) SyncLBMap() error {
...
+	}
+	lbmap.RevNat6Map.Dump(lbmap.RevNat6DumpParser, parseRevNATEntries)
+	if err != nil {
+		log.Warningf("error dumping RevNat6Map: %s", err)
+	}
 
-		if err := lbmap.DeleteService(svcKey); err != nil {
+	// Clean services and rev nats from BPF maps that failed to be restored.
+	for _, svc := range failedSyncSVC {
+		log.Debugf("Unable to restore, so rmoving service: %s", svc.FE)
```
Comment (aanm) [inline daemon/loadbalancer.go]: typo `s/rmoving/removing`

File: pkg/maps/lbmap/lbmap.go [hunk 5]
```diff
@@ -19,6 +19,7 @@ import (
 	"net"
 	"unsafe"
 
+	log "github.com/Sirupsen/logrus"
```
Comment (aanm) [inline pkg/maps/lbmap/lbmap.go]: OOOI

File: pkg/maps/lbmap/lbmap.go [hunk 6]
```diff
@@ -361,17 +368,18 @@ func AddSVC2BPFMap(fe ServiceKey, besValues []ServiceValue, addRevNAT bool, revN
 
 // L3n4Addr2ServiceKey converts the given l3n4Addr to a ServiceKey with the slave ID
 // set to 0.
```
Comment (aanm) [inline pkg/maps/lbmap/lbmap.go:371]: Update function's comment.

**Review by aanm — DISMISSED** [review]
`OOOI - Out Of Order Imports`

File: common/types/loadbalancer.go (hunk 1 above)
Comment (ianvernon) [reply common/types/loadbalancer.go:53]: Since `LBBackEnd` is embedded with an `L3n4Addr`, I guess we could call `String()` on it, and it would use the `L3n4Addr.String()` function, but we wouldn't get the value for the weight for the `LBBackEnd`.

File: daemon/loadbalancer.go (hunk 3 above)
Comment (ianvernon) [reply daemon/loadbalancer.go:262]: If we're deleting the service, we should clean all of the entries out of the BPF map. Why would we not want to delete all of the entries?

File: daemon/loadbalancer.go (hunk 2 above)
Comment (ianvernon) [reply daemon/loadbalancer.go]: Fixed.

File: daemon/loadbalancer.go (hunk 4 above)
Comment (ianvernon) [reply daemon/loadbalancer.go]: Fixed.

File: pkg/maps/lbmap/lbmap.go (hunk 5 above)
Comment (ianvernon) [reply pkg/maps/lbmap/lbmap.go]: Fixed.

File: pkg/maps/lbmap/lbmap.go (hunk 6 above)
Comment (ianvernon) [reply pkg/maps/lbmap/lbmap.go:371]: Fixed.

**Comment by ianvernon** [comment]
I'm reverting some patches that I pulled in from master in this branch to get around being blocked so I can get this done as soon as fixes for those patches that broke master go in. I will be removing those commits once master is fixed.

File: common/types/loadbalancer.go [hunk 7]
```diff
@@ -372,7 +391,12 @@ func (a *L3n4Addr) IsIPv6() bool {
 // KVStore.
 type L3n4AddrID struct {
 	L3n4Addr
-	ID ServiceID
+	ID    ServiceID
+	Slave uint16 // Number of slaves associated with this L3n4AddrID
```
Comment (tgraf) [inline common/types/loadbalancer.go]: This changes the structure used in the kvstore. Is this safe? What will happen if we upgrade Cilium and the kvstore contains old services entries?

File: daemon/loadbalancer.go [hunk 8]
```diff
@@ -182,47 +194,89 @@ func (h *deleteServiceID) Handle(params DeleteServiceIDParams) middleware.Respon
...
 	if !ok {
 		return fmt.Errorf("Service frontend not found %+v", frontend)
 	}
 	return d.svcDelete(&svc)
 }
 
+// Deletes a service by the frontend address
+func (d *Daemon) svcDeleteByFrontend(frontend *types.L3n4Addr) error {
+	d.loadBalancer.BPFMapMU.Lock()
+	defer d.loadBalancer.BPFMapMU.Unlock()
```
Comment (tgraf) [inline daemon/loadbalancer.go:228]: This is confusing, can't we take this lock in the loadbalancer itself? Is this lock protecting the data structures in the daemon as well?

**Review by tgraf — DISMISSED** [review]

File: common/types/loadbalancer.go (hunk 7 above)
Comment (ianvernon) [reply common/types/loadbalancer.go]: You're right. This actually isn't used anywhere in the cilium-agent code, so I'm going to revert it. I figured it would be nice to have to add it now and then actually implement it at a later date, but if it's going to mess with the kv-store, I don't think it's worth it at this time. I'll have this removed in the next upload.

File: daemon/loadbalancer.go (hunk 8 above)
Comment (ianvernon) [reply daemon/loadbalancer.go:228]: I made this function to give flexibility when we need to delete a service by its `L3n4Addr` depending on if we have already acquired `BPFMapMU`. This is similar to other functions throughout the daemon. Can we sync up over video chat about this? It would be easier to explain that way.

**Comment by ianvernon** [comment]
Please review.

File: common/types/loadbalancer.go (hunk 1 above)
Comment (aanm) [reply common/types/loadbalancer.go:53]: I mean for LBBackend. It's fine now

File: common/types/loadbalancer.go [hunk 9]
```diff
@@ -101,15 +107,20 @@ type LoadBalancer struct {
 func (lb *LoadBalancer) AddService(svc LBSVC) bool {
 	oldSvc, ok := lb.SVCMapID[svc.FE.ID]
 	if ok {
-		// If service already existed, remove old entry from map
+		// If service already existed, remove old entry from Cilium's map
+		log.Debugf("service %s is already in lb.SVCMapID; deleting old entry and updating it with new entry", svc.FE.String())
 		delete(lb.SVCMap, oldSvc.Sha256)
 	}
+	log.Debugf("adding service %s with SHA %s to lb.SVCMap", svc.FE.String(), svc.Sha256)
```
Comment (aanm) [inline common/types/loadbalancer.go:114]: Do we still need all this debug messages?

File: common/types/loadbalancer.go [hunk 10]
```diff
@@ -225,7 +236,11 @@ func NewL3n4Addr(protocol L4Type, ip net.IP, portNumber uint16) (*L3n4Addr, erro
 	if err != nil {
 		return nil, err
 	}
-	return &L3n4Addr{IP: ip, L4Addr: *lbport}, nil
+
+	addr := L3n4Addr{IP: ip, L4Addr: *lbport}
+	log.Debugf("created new L3n4Addr %s", addr)
```
Comment (aanm) [inline common/types/loadbalancer.go:241]: here as well

**Review by aanm — COMMENTED** [review]
Can we check if we actually need all debug messages?

File: common/types/loadbalancer.go (hunk 9 above)
Comment (ianvernon) [reply common/types/loadbalancer.go:114]: I found that the debug messages I added were useful in determining what was going on in this code. There were very few logs when I started out with this branch in the service code. I don't see a downside to having this log - it provides important information about the state managed in Cilium.

File: common/types/loadbalancer.go (hunk 10 above)
Comment (ianvernon) [reply common/types/loadbalancer.go:241]: I don't see the disadvantage of having more debug logs - see my comments above.

**Review by tgraf — APPROVED** [review]
