### PR TITLE
policy: Add missing import error metric calls

### LINKED ISSUE #7022: Policy import error metric is broken
The following error is shown in the log:
```
level=error msg="unable to construct selector in label selector" EndpointLabelSelector="&LabelSelector{MatchLabels:map[string]string{any.k8s: strimzi.io/name=testingk196-entity-operator,k8s.io.kubernetes.pod.namespace: covalent,},MatchExpressions:[],}" error="invalid label value: \"strimzi.io/name=testingk196-entity-operator\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')" subsys=policy-api
```

but the policy import error metric stays at 0

### PR DESCRIPTION
**Pull request by vadorovsky**
After this change, policy import error metric is increased after every
logged error in the whole pkg/policy package in functions/methods which
are called when policies are imported.

Fixes #7022

Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7161)

### CODE REVIEW

**Comment by vadorovsky** [comment]
test-me-please

**Comment by vadorovsky** [comment]
test-me-please

File: pkg/policy/groups/actions.go [hunk 1]
```diff
@@ -162,13 +166,15 @@ func addDerivativeCNP(cnp *cilium_v2.CiliumNetworkPolicy) error {
 	if err != nil {
 		statusErr := updateDerivativeStatus(cnp, derivativeCNP.ObjectMeta.Name, err)
 		if statusErr != nil {
+			metrics.PolicyImportErrors.Inc()
```
Comment (joestringer) [inline pkg/policy/groups/actions.go:168]: In this case, the error is returned to the caller so I think it should already be measured?

Oh, but sometimes the caller ignores the error and in general it tends to be handled by controllers. Hmm, I see. In that case it's probably more consistent to keep this here so at least this entire function guarantees that the error is incremented in bad conditions.

File: pkg/policy/repository.go [hunk 2]
```diff
@@ -203,6 +203,7 @@ func (p *Repository) ResolveCIDRPolicy(ctx *SearchContext) *CIDRPolicy {
 func (p *Repository) allowsL4Egress(ctx *SearchContext) api.Decision {
 	egressL4Policy, err := p.ResolveL4EgressPolicy(ctx)
 	if err != nil {
+		metrics.PolicyImportErrors.Inc()
```
Comment (joestringer) [inline pkg/policy/repository.go]: This should not be policy import time, this is evaluating the policy.

File: pkg/policy/repository.go [hunk 3]
```diff
@@ -222,6 +223,7 @@ func (p *Repository) allowsL4Egress(ctx *SearchContext) api.Decision {
 func (p *Repository) allowsL4Ingress(ctx *SearchContext) api.Decision {
 	ingressPolicy, err := p.ResolveL4IngressPolicy(ctx)
 	if err != nil {
+		metrics.PolicyImportErrors.Inc()
```
Comment (joestringer) [inline pkg/policy/repository.go]: Same here, this is not importing the policy but applying the policy.

**Review by joestringer — CHANGES_REQUESTED** [review]
Looking at these error handling cases, I don't understand why we don't always return errors to the caller for handling. If we *are* triggering these bad conditions during policy import and they're not otherwise triggered then we should be incrementing the metrics.

I have a few comments below. In particular the `allows...` are not policy import.

File: pkg/policy/groups/actions.go (hunk 1 above)
Comment (vadorovsky) [reply pkg/policy/groups/actions.go:168]: Yes, I think we should keep it here. Otherwise we would need to have logic for detecting specific errors in `UpdateController` method of Manager.

**Comment by vadorovsky** [comment]
test-me-please

File: pkg/policy/api/selector.go [hunk 4]
```diff
@@ -158,6 +159,7 @@ func (n EndpointSelector) GetMatch(key string) ([]string, bool) {
 func labelSelectorToRequirements(labelSelector *metav1.LabelSelector) *k8sLbls.Requirements {
 	selector, err := metav1.LabelSelectorAsSelector(labelSelector)
 	if err != nil {
+		metrics.PolicyImportErrors.Inc()
```
Comment (ianvernon) [inline pkg/policy/api/selector.go:162]: We should ideally never hit errors here and should resolve this at import time - I filed  https://github.com/cilium/cilium/issues/7176 to account for that. Having the metric here in the meantime is good.

File: pkg/policy/groups/actions.go [hunk 5]
```diff
@@ -150,9 +152,11 @@ func addDerivativeCNP(cnp *cilium_v2.CiliumNetworkPolicy) error {
 		if derivativeErr == nil {
 			break
 		}
+		metrics.PolicyImportErrors.Inc()
 		scopedLog.WithError(derivativeErr).Error("Cannot create derivative rule. Installing deny-all rule.")
 		statusErr := updateDerivativeStatus(cnp, derivativeCNP.ObjectMeta.Name, derivativeErr)
 		if statusErr != nil {
+			metrics.PolicyImportErrors.Inc()
```
Comment (ianvernon) [inline pkg/policy/groups/actions.go]: I don't think this one is necessary here because updating status doesn't affect whether there was an error importing the policy itself.

File: pkg/policy/groups/actions.go [hunk 6]
```diff
@@ -162,13 +166,15 @@ func addDerivativeCNP(cnp *cilium_v2.CiliumNetworkPolicy) error {
...
 			scopedLog.WithError(err).Error("Cannot update CNP status for derivative policy")
 		}
 		return statusErr
 	}
 
 	err = updateDerivativeStatus(cnp, derivativeCNP.ObjectMeta.Name, nil)
 	if err != nil {
+		metrics.PolicyImportErrors.Inc()
```
Comment (ianvernon) [inline pkg/policy/groups/actions.go]: Same here.

**Review by ianvernon — CHANGES_REQUESTED** [review]

**Review by aanm — APPROVED** [review]

**Comment by vadorovsky** [comment]
@ianvernon Thanks, PTAL!

**Comment by vadorovsky** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
