### PR TITLE
fix: kube-proxy-healthz to return 503 if node terminating

### LINKED ISSUE #39911: Drain connections from a node gracefully when node is terminated.
Proposing this feature in Cilium based on a KEP: 
https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/3836-kube-proxy-improved-ingress-connectivity-reliability#implementation-history

Problem statement:
https://github.com/Azure/AKS/issues/5038

### PR DESCRIPTION
**Pull request by tamilmani1989**
This PR addresses this [KEP]( https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/3836-kube-proxy-improved-ingress-connectivity-reliability#implementation-history). kube-proxy healthz handler will return 503 if node is being deleted. Leveraged existing local node watcher to watch for deletion events and added `IsBeingDeleted` field in LocalNode structure. `IsBeingDeleted` field will be set to true on node deletion. Kube-proxy health handler will get local node details via get call and if `IsBeingDeleted` set, it returns 503 (ServiceUnavailable) error.

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

Fixes: #39911

```release-note
Fix kube-proxy healthz to return 503 if node in terminating state  
```

### CODE REVIEW

File: daemon/healthz/kube_proxy_healthz.go [hunk 1]
```diff
@@ -135,6 +144,13 @@ func (h kubeproxyHealthzHandler) ServeHTTP(w http.ResponseWriter, r *http.Reques
 		statusCode = http.StatusServiceUnavailable
 		lastUpdatedAt = h.lastUpdateAter.GetLastUpdatedAt()
 	}
+
+	ln, err := h.localNode.Get(context.TODO())
```
Comment (paulgmiller) [inline daemon/healthz/kube_proxy_healthz.go]: nit request has a context you could use?

**Comment by tamilmani1989** [comment]
@thorn3r would you able to review my PR please?

**Review by thorn3r — APPROVED** [review]
Looks great! Kudos for the thorough testing :+1:

**Comment by 11siddarth** [comment]
@tamilmani1989 Could you please provide instruction on how to implement/apply this fix/PR on our AKS environment that uses cilium.

**Comment by tklauser** [comment]
Hit non-trivial merge conflicts when attempting to backport this to `v1.17`. This will need a manual backport PR in case we still want this in `v1.17`.

**Comment by tamilmani1989** [comment]
> Hit non-trivial merge conflicts when attempting to backport this to `v1.17`. This will need a manual backport PR in case we still want this in `v1.17`.

created backport to 1.17 https://github.com/cilium/cilium/pull/40317

**Comment by 11siddarth** [comment]
> @tamilmani1989 
> Thank you for working on it and getting this fix for the issue.
> Had couple of questions with this fix :
> 1) How can we implement this in AKS cluster for immediate testing. I see that my AKS cluster would pick cilium image from MCR for 1.17.4 , is your changes integrated/applied in MCR as well for cilium images ?
> 2) Will this fix gracefully drain existing connections in the intermediate node avoiding service disruption during node termination or if it only stops new connections to the node to be deleted and still the existing connections get affected with this fix?

since this is specific to AKS, i moved the discussion to AKS thread: https://github.com/Azure/AKS/issues/5038#issuecomment-3028569759

**Comment by aanm** [comment]
@tamilmani1989 FYI this PR has not been backported to v1.17 even tho it has the needs-backport/1.17 label.

**Comment by aanm** [comment]
> @tamilmani1989 FYI this PR has not been backported to v1.17 even tho it has the needs-backport/1.17 label.

Oh it turns out it was backported in https://github.com/cilium/cilium/pull/40317. All good!
