### PR TITLE
Fix issue where traffic from a pod could be dropped despite allow policy when DNS L7 rules are used

### LINKED ISSUE #11517: Cilium drops pod traffic that should be allowed by policy (due to CIDR / FQDN identity)
## Summary

Cilium 1.7.3. Issue reported from the community during upgrade testing from v1.6.x.
Kernel 4.15.

Connectivity from pod to pod is rejected by policy despite the policy allowing that traffic.

## Symptoms

Cilium monitor reports drops for traffic that should be allowed by policy:

```
# cilium monitor --type=drop
Listening for events on 16 CPUs with 64x4096 of shared memory
Press Ctrl-C to quit
level=info msg="Initializing dissection cache..." subsys=monitor
xx drop (Policy denied) flow 0xb6b3b6b3 to endpoint 1585, identity 16777388->33623: 10.0.x.y:55454 -> 10.0.a.b:c tcp SYN
```

Source ip `10.0.x.y` Userspace report of ipcache reports that the IP is mapped to a pod identity:

```
# cilium map get cilium_ipcache | grep 10.0.x.y
10.0.x.y/32                                6464 0 10.0.x.y    sync
```

BPF map dump fails due to lack of kernel support:

```
# cilium bpf ipcache list
error dumping contents of map: Unable to get next key from map with file descriptor 5: errno 524
```

The IP also appears in the identity list as a CIDR identity:
```
cilium-identity-list.md:16777388   cidr:10.0.x.y/32
```

Furthermore it is listed in `cilium fqdn cache list`:

```
cilium-fqdn-cache-list.md:3906       lookup       foo.namespace.svc.cluster.local.              3600     2020-05-12T19:02:17.413Z   10.0.x.y  
```

Cilium status reports that the ipcache-bpf-garbage-collection controller has recently run successfully on the node, so userspace should be in sync with the datapath:

```
 ipcache-bpf-garbage-collection              1m47s ago      never        0       no error
```

Endpoint was regenerated regularly per expected ipcache GC controller behaviour:

```
$ grep -e "Endpoint Log" -e "ipcache" cilium-debuginfo-20200512-180805.689+0000-UTC.md | grep -A 200 1585 | head -n+8
#### Endpoint Log 1585
2020-05-12T18:06:16Z   OK       waiting-to-regenerate   Successfully regenerated endpoint program (Reason: datapath ipcache)
2020-05-12T18:06:13Z   OK       regenerating            Regenerating endpoint: datapath ipcache
2020-05-12T18:06:13Z   OK       waiting-to-regenerate   Triggering endpoint regeneration due to datapath ipcache
2020-05-12T18:01:12Z   OK       waiting-to-regenerate   Successfully regenerated endpoint program (Reason: datapath ipcache)
2020-05-12T18:01:10Z   OK       regenerating            Regenerating endpoint: datapath ipcache
2020-05-12T18:01:08Z   OK       waiting-to-regenerate   Triggering endpoint regeneration due to datapath ipcache
2020-05-12T17:56:06Z   OK       ready                   Successfully regenerated endpoint program (Reason: datapath ipcache)
```

If we look more broadly at the regenerations occurring around the time of the ipcache-triggered regenerations, we also see other reasons and there is not a 1-1 correlation between triggers and moving the endpoint into "ready" state, for example:

```
2020-05-12T18:06:27Z   OK       waiting-to-regenerate   Triggering endpoint regeneration due to one or more identities created or deleted
2020-05-12T18:06:16Z   OK       ready                   Successfully regenerated endpoint program (Reason: one or more identities created or deleted)
2020-05-12T18:06:16Z   OK       ready                   Completed endpoint regeneration with no pending regeneration requests
2020-05-12T18:06:16Z   OK       regenerating            Regenerating endpoint: one or more identities created or deleted
2020-05-12T18:06:16Z   OK       waiting-to-regenerate   Successfully regenerated endpoint program (Reason: datapath ipcache)
2020-05-12T18:06:16Z   OK       waiting-to-regenerate   Triggering endpoint regeneration due to one or more identities created or deleted
2020-05-12T18:06:13Z   OK       regenerating            Regenerating endpoint: datapath ipcache
2020-05-12T18:06:13Z   OK       waiting-to-regenerate   Triggering endpoint regeneration due to datapath ipcache
2020-05-12T18:05:33Z   OK       ready                   Successfully regenerated endpoint program (Reason: one or more identities created or deleted)
```

### PR DESCRIPTION
**Pull request by joestringer**
From the commit message:

    Cilium defines a precedence ordering between sources for mappings from
    IP to Identity, defined in pkg/source/source.go. These are used to
    determine which Identity should be used for an IP when multiple sources
    provide conflicting reports of the Identity to be associated with an IP.
    
    This ordering was handled in the case of source.Generated CIDR/FQDN
    -sourced identities by inserting potentially two overlapping entries
    into the ipcache.IPIdentityCache when an endpoint's IP is the same as a
    CIDR mapping:
    
    * An endpoint Identity would be inserted with the key 'w.x.y.z', and
    * A CIDR Identity would be inserted with the key 'w.x.y.z/32'. (IPv6: /128)
    
    During Upsert() and Delete(), when overlapping entries existed in the
    map, this overlap would be resolved by directly checking whether another
    entry exists with/without the `/32` suffix (IPv6: /128) and either
    hiding the update from listeners (when a shadowed mapping is upserted),
    or converting the delete to an update (when a shadowing entry is
    deleted, revealing the underlying shadowed entry).
    
    During DumpToListenerLocked() however, this shadowing would not be
    resolved and instead both entries would be dumped to the caller in an
    arbitrary order. This is particularly notable on Linux 4.11 to 4.15
    where LPM support is available but deletion is not supported. In these
    cases, Cilium periodically dumps the ipcache to a listener using this
    function, and populates the BPF ipcache map using this dump. Any time this
    dump occurs (default 5 minutes), it would be possible for the ipcache
    mapping to be modified to map the IP to either of the cached identities.
    Depending on the Go runtime in use by the version of Cilium, this may or
    may not consistently provide particular dump ordering.
    
    Resolve this issue by keeping track of shadowed entries with an
    explicit boolean field in the value of the map, and avoiding dumping
    such entries in the DumpToListenerLocked() function.

This issue would require a pod on the node with the affected pod to make a request for a DNS name that maps to an IP which represents a remote pod, for that request to be processed via L7 DNS policy, and for the remote pod to subsequently make requests to the affected pod in direct routing mode on Linux 4.11-4.15.

This was only observed on v1.7.x, however I've marked it for backport to v1.6.x as well in an abundance of caution. Cilium v1.6 and v1.7 use different Go versions (v1.12 vs v1.13) so it's likely that the map iteration behaviour is different between these versions. Go doesn't make any guarantees about map iteration ordering, so this PR addresses this by explicitly resolving the overlap between identities for the same IP.

Shout outs also to @tklauser @jrajahalme for their help tracking this down.

Fixes: #11517

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

File: pkg/ipcache/ipcache.go [hunk 1]
```diff
@@ -277,6 +283,8 @@ func (ipc *IPCache) Upsert(ip string, hostIP net.IP, hostKey uint8, k8sMeta *K8s
 				oldHostIP, _ = ipc.getHostIPCache(cidrStr)
 				if cidrIdentity.ID != newIdentity.ID || !oldHostIP.Equal(hostIP) {
 					scopedLog.Debug("New endpoint IP started shadowing existing CIDR to identity mapping")
+					cidrIdentity.shadowed = true
+					ipc.ipToIdentityCache[cidrStr] = cidrIdentity
```
Comment (jrajahalme) [inline pkg/ipcache/ipcache.go:287]: Can you elaborate why we map to cidrIdentity when it is being shadowed?

**Review by jrajahalme — APPROVED** [review]

**Review by tklauser — APPROVED** [review]

**Comment by tklauser** [comment]
retest-4.9

**Comment by tklauser** [comment]
retest-4.19

**Review by aanm — COMMENTED** [review]
why is it ok to keep shadowed identities in ipToIdentityCache but not in the listeners? and which identity is going to be shadowed?

**Comment by joestringer** [comment]
> why is it ok to keep shadowed identities in ipToIdentityCache but not in the listeners? and which identity is going to be shadowed?

@aanm good question, I didn't cover that in the commit/PR details.

### Summary

The core issue is the concern of a policy having two entries:
* One that allows traffic to/from an IP based on a CIDR /32
* One that allows traffic to/from pod labels for a pod which happens to have the same IP as the CIDR /32 in the policy rule above.

In this scenario, the 'shadowing' rules of Cilium state that the endpoint identity takes precedence over the /32 CIDR allow. You can't accidentally allow access to/from an endpoint based on the IP it gets assigned; you must explicitly declare the intent to allow traffic to/from that endpoint based on its labels. The tricky part with the shadowing is how we resolve it when dynamic changes occur such as creating/destroying endpoints with the overlapping IP, I'll discuss this later in this explanation.

### Listeners vs. IPIdentityCache

The listeners represent the BPF datapath map / proxy ip-to-identity map. The ipcache there maps exactly from a CIDR prefix to one identity, there's no way to store multiple values for the same IP. So at that layer, there must be exactly one identity for a given IP.

For the in-memory IPIdentityCache, the rules are a bit more loose - it's keyed by a string. The most common case of overlapping identities is between an endpoint IP and a CIDR allocated through policy. To ensure that insertion/deletion of IP->Identity mappings consistently behave in the same manner, we keep track of both. This way, we can support the exact case that is implemented in the unit test; If an endpoint shadows an IP used in CIDR policy, then the endpoint labels take precedence and we can allow traffic to/from that endpoint based on the labels. If we then remove the endpoint again then we fall back to resolving the IP to its CIDR identity, allowing us to implement policy via CIDR/FQDN logic.

### Overlapping IP->Identity mappings

Consider first for a moment, if we have fresh Cilium and import a CIDR policy that allows `w.x.y.z/32` in the policy. We will allocate a CIDR identity `A` for policy use and push down an ipcache mapping that maps `w.x.y.z`->`A`. Let's say we then create a pod that has the same IP, `w.x.y.z` with labels-based identity `B`. Now we push down the mapping `w.x.y.z` -> `B`. Now we can apply label-based policy to control access from that endpoint. But wait, what happens when we remove the endpoint? Do we remove `w.x.y.z` -> `B`? If we simply removed the mapping for `w.x.y.z`, then we would also no longer allow the traffic based on CIDR; the datapath ipcache would fall back to resolving the identity as 'world' based on LPM rules. This would be inconsistent with the actual policy in place right now that allows traffic to/from that `w.x.y.z/32`. It's also inconsistent with initial state after we inserted the CIDR policy but didn't yet create the endpoint. To mitigate this, we track the CIDR identities that were previously used (shadowed), and reinstate them when the pod identity is removed.

### Implementation

Implementation-wise the current version tracks both shadowed/non-shadowed entries all in one map with a value field to track whether it's shadowed or not. We could consider instead using a map -> list or two maps - shadowed/non-shadowed. This could potentially help to ensure that only the latest, unshadowed entries are propagated to the listeners and API, but in practical terms I'm not sure there are any differences from the current implementation.
