### PR TITLE
cilium: Small health cleanup improvements

### LINKED ISSUE #32689: CI: Cilium E2E Upgrade - no-errors-in-logs - retrieving device lxc_health: Link not found
## CI failure

Hit on https://github.com/cilium/cilium/pull/32688
Link: https://github.com/cilium/cilium/actions/runs/9209728129/job/25335026937
Sysdump: [cilium-sysdump-7-final.zip](https://github.com/cilium/cilium/files/15419428/cilium-sysdump-7-final.zip)

```
❌ Found 2 logs in kind-kind/kube-system/cilium-d2588 (cilium-agent) matching list of errors that must be investigated:
time="2024-05-23T14:34:10Z" level=error msg="Error while reloading endpoint BPF program" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=2584 error="retrieving device lxc_health: Link not found" identity=4 ipv4=10.244.0.12 ipv6="fd00:10:244::1cd5" k8sPodName=/ subsys=endpoint (1 occurrences)
time="2024-05-23T14:34:10Z" level=error msg="endpoint regeneration failed" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=2584 error="retrieving device lxc_health: Link not found" identity=4 ipv4=10.244.0.12 ipv6="fd00:10:244::1cd5" k8sPodName=/ subsys=endpoint (1 occurrences)
```

### PR DESCRIPTION
**Pull request by borkmann**
(see commit msg)

Fixes: https://github.com/cilium/cilium/issues/32689

### CODE REVIEW

File: daemon/cmd/state.go [hunk 1]
```diff
@@ -82,6 +83,8 @@ func (d *Daemon) validateEndpoint(ep *endpoint.Endpoint) (valid bool, err error)
 		if err := os.RemoveAll(healthStateDir); err != nil {
 			scopedLog.Warning("Cannot clean up old health state directory")
 		}
+		// Remove health related devices if they still exist
```
Comment (gandro) [inline daemon/cmd/state.go]: After re-reading the code, this seems like the proper place to do cleanup for now.

I think we should invoke `health.KillEndpoint()` here too. Otherwise we try to remove the network namespace of a running process, which I'm not sure works well.

**Review by gandro — COMMENTED** [review]
I think this looks good. Have you tested if this fixes CI?

File: daemon/cmd/health.go [hunk 2]
```diff
@@ -147,5 +147,4 @@ func (d *Daemon) cleanupHealthEndpoint() {
 			log.WithError(err).Debug("Error occurred while deleting cilium-health endpoint")
 		}
 	}
-	health.CleanupEndpoint()
```
Comment (gandro) [inline daemon/cmd/health.go:149]: We should keep this here, otherwise the health device might be leaked if cilium is never started again

**Review by gandro — APPROVED** [review]
Code looks good to me. We should also test if this really fixes CI like the previous PR did: https://github.com/cilium/cilium/pull/33410/commits/dd94c27a4741bf0e56225f9b65d9763783875475

**Review by aanm — APPROVED** [review]

**Comment by borkmann** [comment]
Interestingly, the cleanup in the beginning still did not help:
```
[...]
2024-07-11T13:06:11.305181694Z time="2024-07-11T13:06:11Z" level=info msg="Restoring endpoints..." subsys=daemon
2024-07-11T13:06:11.305185120Z time="2024-07-11T13:06:11Z" level=debug msg="Killing old health endpoint process" pidfile=/var/run/cilium/state/health-endpoint.pid subsys=cilium-health-launcher
2024-07-11T13:06:11.305196952Z time="2024-07-11T13:06:11Z" level=debug msg="Didn't find existing device" error="Link not found" interface=cilium_health subsys=cilium-health-launcher
2024-07-11T13:06:11.305199717Z time="2024-07-11T13:06:11Z" level=debug msg="Didn't find existing device" error="Link not found" interface=lxc_health subsys=cilium-health-launcher
2024-07-11T13:06:11.305202552Z time="2024-07-11T13:06:11Z" level=debug msg="Removing old health endpoint state directory" endpointID=2527 file-path=/var/run/cilium/state/2527 subsys=daemon
2024-07-11T13:06:11.305205157Z time="2024-07-11T13:06:11Z" level=debug msg="Restoring endpoint" ciliumEndpointName=/ endpointID=2959 subsys=daemon
[...]
2024-07-11T13:06:59.063745646Z time="2024-07-11T13:06:59Z" level=debug msg="Controller func execution time: 7.720565ms" name=ct-map-pressure subsys=controller uuid=98a32dc0-b5da-455b-8f4d-6618ec7af3dd
2024-07-11T13:06:59.064512265Z time="2024-07-11T13:06:59Z" level=info msg="Launching Cilium health endpoint" subsys=daemon
2024-07-11T13:06:59.065306735Z time="2024-07-11T13:06:59Z" level=debug msg="Starting new controller" name=cilium-health-ep subsys=controller uuid=899e6e16-9003-4a06-b216-d3d268d84391
2024-07-11T13:06:59.065948300Z time="2024-07-11T13:06:59Z" level=info msg="Cleaning up Cilium health endpoint" subsys=daemon
2024-07-11T13:06:59.065955123Z time="2024-07-11T13:06:59Z" level=debug msg="Killing old health endpoint process" pidfile=/var/run/cilium/state/health-endpoint.pid subsys=cilium-health-launcher
2024-07-11T13:06:59.066043027Z time="2024-07-11T13:06:59Z" level=debug msg="Didn't find existing cilium-health endpoint to delete" subsys=daemon
2024-07-11T13:06:59.066047125Z time="2024-07-11T13:06:59Z" level=debug msg="Didn't find existing device" error="Link not found" interface=cilium_health subsys=cilium-health-launcher
2024-07-11T13:06:59.066050050Z time="2024-07-11T13:06:59Z" level=debug msg="Didn't find existing device" error="Link not found" interface=lxc_health subsys=cilium-health-launcher
2024-07-11T13:06:59.075560441Z time="2024-07-11T13:06:59Z" level=debug msg="Compiling datapath" clang="clang version 17.0.6 (https://github.com/llvm/llvm-project.git 6009708b4367171ccdbf4b5905cb6a803753fe18)\nTarget: unknown\nThread model: posix\nInstalledDir: /usr/local/bin\n" debug=true subsys=datapath-loader
2024-07-11T13:06:59.075939908Z time="2024-07-11T13:06:59Z" level=debug msg="Launching compiler" args="[-I/var/run/cilium/state/globals -I/var/run/cilium/state/templates/40cd79ad4efe0858c6dddfc5d87fbf57b44f0930942d12240d3bb96ad21aa672 -I/var/lib/cilium/bpf -I/var/lib/cilium/bpf/include -E -O2 --target=bpf -std=gnu89 -nostdinc -Wall -Wextra -Werror -Wshadow -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-gnu-variable-sized-type-not-at-end -Wdeclaration-after-statement -Wimplicit-int-conversion -Wenum-conversion -D__NR_CPUS__=4 -mcpu=v3 -c /var/lib/cilium/bpf/bpf_lxc.c -o -]" subsys=datapath-loader target=clang
2024-07-11T13:06:59.084486312Z time="2024-07-11T13:06:59Z" level=debug msg="Created veth pair" subsys=endpoint-connector vethPair="[cilium lxc_health]"
2024-07-11T13:06:59.095243265Z time="2024-07-11T13:06:59Z" level=info msg="Started healthz status API server" address="127.0.0.1:9879" subsys=daemon
[...]
2024-07-11T13:06:59.118809675Z time="2024-07-11T13:06:59Z" level=debug msg="Controller func execution time: 21.568989ms" name=node-neighbor-link-updater subsys=controller uuid=505b153c-19b7-4289-85e3-f237ec485b3a
2024-07-11T13:06:59.120142649Z time="2024-07-11T13:06:59Z" level=debug msg="Controller run failed" consecutiveErrors=1 error="unable to determine next hop IPv4 address for eth1 (172.18.0.4): remote node IP is non-routable\nunable to determine next hop IPv6 address for eth1 (fc00:c111::4): remote node IP is non-routable\nunable to determine next hop IPv4 address for eth1 (172.18.0.5): remote node IP is non-routable\nunable to determine next hop IPv6 address for eth1 (fc00:c111::5): remote node IP is non-routable" name=node-neighbor-link-updater subsys=controller uuid=505b153c-19b7-4289-85e3-f237ec485b3a
2024-07-11T13:06:59.120158228Z time="2024-07-11T13:06:59Z" level=debug msg="Created lxc_health devices!!!" subsys=cilium-health-launcher
[...]
ime="2024-07-11T13:11:40Z" level=debug msg="Inserted program handle_policy into cilium_call_policy slot 3813" subsys=datapath-loader
2024-07-11T13:11:40.494169001Z time="2024-07-11T13:11:40Z" level=error msg="Error while reloading endpoint BPF program" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3813 error="retrieving device lxc_health: Link not found" identity=4 ipv4=10.244.0.89 ipv6="fd00:10:244::8f21" k8sPodName=/ subsys=endpoint
2024-07-11T13:11:40.507246888Z time="2024-07-11T13:11:40Z" level=debug msg="Reverting endpoint changes after BPF regeneration failed" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3813 identity=4 ipv4=10.244.0.89 ipv6="fd00:10:244::8f21" k8sPodName=/ subsys=endpoint
2024-07-11T13:11:40.508978725Z time="2024-07-11T13:11:40Z" level=debug msg="Reverting proxy redirect removals" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3813 identity=4 ipv4=10.244.0.89 ipv6="fd00:10:244::8f21" k8sPodName=/ subsys=endpoint
2024-07-11T13:11:40.515374522Z time="2024-07-11T13:11:40Z" level=debug msg="Finished reverting proxy redirect removals" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3813 identity=4 ipv4=10.244.0.89 ipv6="fd00:10:244::8f21" k8sPodName=/ subsys=endpoint
2024-07-11T13:11:40.517227445Z time="2024-07-11T13:11:40Z" level=debug msg="Reverting proxy redirect additions" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3813 identity=4 ipv4=10.244.0.89 ipv6="fd00:10:244::8f21" k8sPodName=/ subsys=endpoint
2024-07-11T13:11:40.526316210Z time="2024-07-11T13:11:40Z" level=debug msg="Finished reverting proxy redirect additions" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3813 identity=4 ipv4=10.244.0.89 ipv6="fd00:10:244::8f21" k8sPodName=/ subsys=endpoint
2024-07-11T13:11:40.535427326Z time="2024-07-11T13:11:40Z" level=debug msg="Finished reverting endpoint changes after BPF regeneration failed" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3813 identity=4 ipv4=10.244.0.89 ipv6="fd00:10:244::8f21" k8sPodName=/ subsys=endpoint
2024-07-11T13:11:40.537228281Z time="2024-07-11T13:11:40Z" level=info msg="generating BPF for endpoint failed, keeping stale directory" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3813 error="retrieving device lxc_health: Link not found" file-path=3813_next_fail identity=4 ipv4=10.244.0.89 ipv6="fd00:10:244::8f21" k8sPodName=/ subsys=endpoint
2024-07-11T13:11:40.553245035Z time="2024-07-11T13:11:40Z" level=debug msg="removing directory" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=1 directory=3813_next_fail endpointID=3813 identity=4 ipv4=10.244.0.89 ipv6="fd00:10:244::8f21" k8sPodName=/ subsys=endpoint
2024-07-11T13:11:40.554469286Z time="2024-07-11T13:11:40Z" level=debug msg="removing directory" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=1 directory=3813_next endpointID=3813 identity=4 ipv4=10.244.0.89 ipv6="fd00:10:244::8f21" k8sPodName=/ subsys=endpoint
2024-07-11T13:11:40.555065818Z time="2024-07-11T13:11:40Z" level=debug msg="Completed endpoint regeneration with no pending regeneration requests" ciliumEndpointName=/ code=OK containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3813 endpointState=ready identity=4 ipv4=10.244.0.89 ipv6="fd00:10:244::8f21" k8sPodName=/ policyRevision=0 subsys=endpoint type=0
2024-07-11T13:11:40.561285586Z time="2024-07-11T13:11:40Z" level=warning msg="Regeneration of endpoint failed" bpfCompilation=0s bpfLoadProg=1.639026581s bpfWaitForELF="209.771µs" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3813 error="retrieving device lxc_health: Link not found" identity=4 ipv4=10.244.0.89 ipv6="fd00:10:244::8f21" k8sPodName=/ mapSync=0s policyCalculation="95.999µs" prepareBuild=3.13949ms proxyConfiguration="9.368µs" proxyPolicyCalculation=521ns proxyWaitForAck=0s reason="updated security labels" subsys=endpoint total=4m40.369994788s waitingForCTClean=10.346679ms waitingForLock=4m38.649503748s waitingForPolicyRepository=781ns
2024-07-11T13:11:40.562000108Z time="2024-07-11T13:11:40Z" level=debug msg="Error regenerating endpoint: retrieving device lxc_health: Link not found" ciliumEndpointName=/ code=Failure containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3813 endpointState=ready identity=4 ipv4=10.244.0.89 ipv6="fd00:10:244::8f21" k8sPodName=/ policyRevision=0 subsys=endpoint type=200
2024-07-11T13:11:40.569426315Z time="2024-07-11T13:11:40Z" level=debug msg="EventQueue event processing statistics" eventConsumeOffQueueWaitTime="315.989µs" eventEnqueueWaitTime=1.934585ms eventHandlingDuration=4m40.376406694s eventType="*endpoint.EndpointRegenerationEvent" name=endpoint-3813 subsys=eventqueue
2024-07-11T13:11:40.572378476Z time="2024-07-11T13:11:40Z" level=error msg="endpoint regeneration failed" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3813 error="retrieving device lxc_health: Link not found" identity=4 ipv4=10.244.0.89 ipv6="fd00:10:244::8f21" k8sPodName=/ subsys=endpoint
2024-07-11T13:11:40.576671254Z time=2024-07-11T13:11:40Z level=debug msg="upserting health status" module=health lastLevel=none reporter-id="agent.controlplane.endpoint-manager.cilium-endpoint-3813 (/).datapath-regenerate" status="agent.controlplane.endpoint-manager.cilium-endpoint-3813 (/).datapath-regenerate: [Degraded] Endpoint regeneration failed: retrieving device lxc_health: Link not found"
2024-07-11T13:11:40.577546725Z time="2024-07-11T13:11:40Z" level=debug msg="Deleting endpoint" ciliumEndpointName=/ code=OK containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3813 endpointState=disconnecting identity=4 ipv4=10.244.0.89 ipv6="fd00:10:244::8f21" k8sPodName=/ policyRevision=0 subsys=endpoint type=0
2024-07-11T13:11:40.584349501Z time="2024-07-11T13:11:40Z" level=debug msg="Registered BPF map" path=/sys/fs/bpf/tc/globals/cilium_call_policy subsys=bpf
2024-07-11T13:11:40.589723724Z time="2024-07-11T13:11:40Z" level=debug msg="Unregistered BPF map" path=/sys/fs/bpf/tc/globals/cilium_call_policy subsys=bpf
```

**Comment by borkmann** [comment]
[logs-cilium-df9gx-cilium-agent-20240711-132748.log](https://github.com/user-attachments/files/16190627/logs-cilium-df9gx-cilium-agent-20240711-132748.log)

This one looks interesting as well which could have caused an unexpected removal in between:
```
2024-07-11T13:10:00.339933129Z time="2024-07-11T13:10:00Z" level=debug msg="Cannot find socket" error="stat /var/run/cilium/health.sock: no such file or directory" file-path=/var/run/cilium/health.sock subsys=cilium-health-launcher
2024-07-11T13:10:01.024499589Z time="2024-07-
[logs-cilium-df9gx-cilium-agent-20240711-132748.log](https://github.com/user-attachments/files/16190622/logs-cilium-df9gx-cilium-agent-20240711-132748.log)
11T13:10:01Z" level=info msg="Cleaning up Cilium health endpoint" subsys=daemon
2024-07-11T13:10:01.024764002Z time="2024-07-11T13:10:01Z" level=debug msg="Killing old health endpoint process" pidfile=/var/run/cilium/state/health-endpoint.pid subsys=cilium-health-launcher
2024-07-11T13:10:01.028980479Z time="2024-07-11T13:10:01Z" level=debug msg="Killed endpoint process" pid=749 pidfile=/var/run/cilium/state/health-endpoint.pid subsys=cilium-health-launcher
2024-07-11T13:10:01.029171454Z time="2024-07-11T13:10:01Z" level=debug msg="Removing existing cilium-health endpoint" subsys=daemon
2024-07-11T13:10:01.030259441Z time=2024-07-11T13:10:01Z level=debug msg="delete health sub-tree" module=health 
prefix="agent.controlplane.endpoint-manager.cilium-endpoint-3813 (/)" deleted=0
```

**Comment by borkmann** [comment]
Turns out the failure is reliably triggered with `lb-acceleration: 'testing-only'` enabled in the setup 7 test.

**Comment by borkmann** [comment]
In one of the recent runs:
```
[...]
1:09:05.786827495Z time="2024-07-15T11:09:05Z" level=debug msg="GET /endpoint request" params="{HTTPRequest:0xc0027159e0 Labels:[]}" subsys=daemon
2024-07-15T11:09:05.786854756Z time="2024-07-15T11:09:05Z" level=debug msg="Processing API request with rate limiter" name=endpoint-list parallelRequests=87 subsys=rate uuid=945d0040-94fd-4b02-82f2-556971a7efdb
2024-07-15T11:09:05.786861178Z time="2024-07-15T11:09:05Z" level=debug msg="API request released by rate limiter" burst=175 limit=86.50/s maxWaitDurationLimiter="-48.771µs" name=endpoint-list parallelRequests=87 subsys=rate uuid=945d0040-94fd-4b02-82f2-556971a7efdb waitDurationLimiter=0s waitDurationTotal="57.818µs"
2024-07-15T11:09:05.786866237Z time="2024-07-15T11:09:05Z" level=debug msg="API call has been processed" name=endpoint-list processingDuration=1.685331ms subsys=rate totalDuration=1.771191ms uuid=945d0040-94fd-4b02-82f2-556971a7efdb waitDurationTotal="57.818µs"
2024-07-15T11:09:06.631291891Z time="2024-07-15T11:09:06Z" level=info msg="Cleaning up Cilium health endpoint" subsys=daemon
2024-07-15T11:09:06.631309674Z time="2024-07-15T11:09:06Z" level=debug msg="Killing old health endpoint process" pidfile=/var/run/cilium/state/health-endpoint.pid subsys=cilium-health-launcher
2024-07-15T11:09:06.631313741Z time="2024-07-15T11:09:06Z" level=debug msg="Killed endpoint process" pid=560 pidfile=/var/run/cilium/state/health-endpoint.pid subsys=cilium-health-launcher
2024-07-15T11:09:06.631317168Z time="2024-07-15T11:09:06Z" level=debug msg="Removing existing cilium-health endpoint" subsys=daemon
2024-07-15T11:09:06.631320645Z time="2024-07-15T11:09:06Z" level=debug msg="EndpointManager policymap event metric update triggered" subsys=endpoint-manager
2024-07-15T11:09:06.631590047Z time="2024-07-15T11:09:06Z" level=debug msg="stopping EventQueue" name=endpoint-2546 subsys=eventqueue
2024-07-15T11:09:06.631603041Z time="2024-07-15T11:09:06Z" level=debug msg="exiting retrying regeneration goroutine due to endpoint being deleted" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2546 identity=4 ipv4=10.244.2.93 ipv6="fd00:10:244:2::9e31" k8sPodName=/ subsys=endpoint
2024-07-15T11:09:06.631607048Z time="2024-07-15T11:09:06Z" level=debug msg="Controller func execution time: 3m0.82927473s" name=endpoint-2546-regeneration-recovery subsys=controller uuid=1a16711a-4941-4594-a7fe-c60cf79f3b13
2024-07-15T11:09:06.631613540Z time="2024-07-15T11:09:06Z" level=debug msg="Controller run succeeded; waiting for next controller update or stop" name=endpoint-2546-regeneration-recovery subsys=controller uuid=1a16711a-4941-4594-a7fe-c60cf79f3b13
2024-07-15T11:09:06.631418227Z time=2024-07-15T11:09:06Z level=debug msg="delete health sub-tree" module=health prefix="agent.controlplane.endpoint-manager.cilium-endpoint-2546 (/)" deleted=0
2024-07-15T11:09:06.638703985Z time="2024-07-15T11:09:06Z" level=debug msg="Process exited" cmd="cilium-health-responder [--listen 4240 --pidfile /var/run/cilium/state/health-endpoint.pid]" exitCode="signal: killed" subsys=launcher
2024-07-15T11:09:06.780636130Z time="2024-07-15T11:09:06Z" level=debug msg="Cannot find socket" error="stat /var/run/cilium/health.sock: no such file or directory" file-path=/var/run/cilium/health.sock subsys=cilium-health-launcher
2024-07-15T11:09:07.645408985Z time="2024-07-15T11:09:07Z" level=debug msg="Controller func execution time: 105.957µs" name=daemon-validate-config subsys=controller uuid=9d166239-4361-4ace-bd15-687278797da3
2024-07-15T11:09:07.767900127Z time="2024-07-15T11:09:07Z" level=debug msg="Cannot find socket" error="stat /var/run/cilium/health.sock: no such file or directory" file-path=/var/run/cilium/health.sock subsys=cilium-health-launcher
2024-07-15T11:09:08.772598657Z time="2024-07-15T11:09:08Z" level=debug msg="Cannot find socket" error="stat /var/run/cilium/health.sock: no such file or directory" file-path=/var/run/cilium/health.sock subsys=cilium-health-launcher
2024-07-15T11:09:09.723010745Z time="2024-07-15T11:09:09Z" level=debug msg="Controller func execution time: 1.683µs" name=bpf-map-sync-cilium_lxc subsys=controller uuid=b8a9a69b-74ea-480b-8470-c87cb0cf5dad
2024-07-15T11:09:09.773233020Z time="2024-07-15T11:09:09Z" level=debug msg="Cannot find socket" error="stat /var/run/cilium/health.sock: no such file or directory" file-path=/var/run/cilium/health.sock subsys=cilium-health-launcher
2024-07-15T11:09:10.789596134Z time="2024-07-15T11:09:10Z" level=debug msg="Cannot find socket" error="stat /var/run/cilium/health.sock: no such file or directory" file-path=/var/run/cilium/health.sock subsys=cilium-health-launcher
2024-07-15T11:09:10.813630011Z time="2024-07-15T11:09:10Z" level=debug msg="Controller func execution time: 1.022µs" name=node-neighbor-link-updater subsys=controller uuid=ebecbc0d-c81c-47ef-a28f-d84bdddf4a0b
[...]
```
Then ~30s nothing in terms of endpint 2546, but then:
```
[...]
695276432Z time="2024-07-15T11:09:36Z" level=debug msg="Triggering endpoint regeneration due to devices changed" ciliumEndpointName=cilium-test/test-conn-disrupt-client-5ccc6f6497-xpm4b code=OK containerID=6d4b618a72 containerInterface=eth0 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=830 endpointState=waiting-to-regenerate identity=23500 ipv4=10.244.2.111 ipv6="fd00:10:244:2::5048" k8sPodName=cilium-test/test-conn-disrupt-client-5ccc6f6497-xpm4b policyRevision=1 subsys=endpoint type=0
2024-07-15T11:09:36.696848672Z time="2024-07-15T11:09:36Z" level=debug msg="Starting policy recalculation..." ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2546 identity=4 ipv4=10.244.2.93 ipv6="fd00:10:244:2::9e31" k8sPodName=/ subsys=endpoint
2024-07-15T11:09:36.698154857Z time="2024-07-15T11:09:36Z" level=debug msg="EndpointManager policymap received event" subsys=endpoint-manager value=0.00018310546875
[...]
2024-07-15T11:09:37.837903586Z time="2024-07-15T11:09:37Z" level=debug msg="Inserted program handle_policy into cilium_call_policy slot 2546" subsys=datapath-loader
2024-07-15T11:09:37.844021227Z time="2024-07-15T11:09:37Z" level=error msg="Error while reloading endpoint BPF program" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=2546 error="retrieving device lxc_health: Link not found" identity=4 ipv4=10.244.2.93 ipv6="fd00:10:244:2::9e31" k8sPodName=/ subsys=endpoint
[...]
```

**Comment by borkmann** [comment]
Some random interesting data points.. the 'setup and test 7' one is the most frequent failing, same config but instead of bpf-next we'd use 5.15 or 6.1, I wasn't able to get this triggered. However, the issue is definitely also unrelated to anything tcx, since occasionally it also triggers on older kernels such as 5.15 in 'setup & test 14':

```
  ❌ Found 2 logs in kind-kind/kube-system/cilium-gvps5 (cilium-agent) matching list of errors that must be investigated:
time="2024-07-15T16:37:11Z" level=error msg="Error while reloading endpoint BPF program" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=2454 error="retrieving device lxc_health: Link not found" identity=4 ipv4=10.244.1.77 ipv6="fd00:10:244:1::5900" k8sPodName=/ subsys=endpoint (1 occurrences)
time="2024-07-15T16:37:11Z" level=error msg="endpoint regeneration failed" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=2454 error="retrieving device lxc_health: Link not found" identity=4 ipv4=10.244.1.77 ipv6="fd00:10:244:1::5900" k8sPodName=/ subsys=endpoint (1 occurrences)
```

**Comment by tommyp1ckles** [comment]
@borkmann 

Started to do some [digging](https://github.com/cilium/cilium/pull/33876#issuecomment-2235591239) to see if I can't lend a fresh perspective.  Some initial things i've observed that seem unexpected:

* In many of the failures, two lxc_health endpoints attempt to get generated with different endpointIDs, one of them eventually gets removed with `msg="Removed endpoint"` - seemingly right before the second one succeeds regenerating.
* As mentioned, restored health endpoint appears to be detected and cleaned up prior to being regenerated.

**Comment by borkmann** [comment]
Endpoint removal as also seen by Tom (identity=4 aka HEALTH_ID) :
```
2024-07-18T13:10:59.528654278Z time="2024-07-18T13:10:59Z" level=debug msg="Endpoint removed" ciliumEndpointName=/ code=OK containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3228 endpointState=disconnected identity=4 ipv4=10.244.1.44 ipv6="fd00:10:244:1::1dac" k8sPodName=/ policyRevision=0 subsys=endpoint type=0
2024-07-18T13:10:59.529017145Z time="2024-07-18T13:10:59Z" level=info msg="Removed endpoint" ciliumEndpointName=/ containerID= containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=3228 identity=4 ipv4=10.244.1.44 ipv6="fd00:10:244:1::1dac" k8sPodName=/ subsys=endpoint
```

[logs-cilium-spjqp-cilium-agent-20240718-133610.log](https://github.com/user-attachments/files/16286556/logs-cilium-spjqp-cilium-agent-20240718-133610.log)

**Review by nathanjsweet — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Review by ldelossa — APPROVED** [review]
LGTM

**Comment by joestringer** [comment]
I see the upgrades test failed with the same original error this is trying to fix, but after downgrading. This means it's actually not the version with this patch/fix that's failing, it's the previous release. Presumably then we can ignore that specific CI result: https://github.com/cilium/cilium/actions/runs/10065195269/job/27826569570 .

File: pkg/endpoint/endpoint.go [hunk 3]
```diff
@@ -2474,6 +2474,12 @@ func (e *Endpoint) Delete(conf DeleteConfig) []error {
 
 	e.Stop()
 
+	// Wait for any pending endpoint regenerate() calls to finish. The
+	// latter bails out after taking the lock when it detects that the
+	// endpoint state is disconnecting.
+	e.buildMutex.Lock()
+	defer e.buildMutex.Unlock()
```
Comment (joestringer) [inline pkg/endpoint/endpoint.go:2481]: Given the comment above `leaveLocked()` I'm surprised this was missing from this path. The lock ordering here looks correct compared to other usage of `buildMutex` (vs. `e.mutex`). It's hard to fully understand the impact of this with deletions potentially blocking more often depending on other endpoint creation/regeneration events going on in the system, but it does seem to be more correct behaviour.

**Review by joestringer — APPROVED** [review]

**Comment by borkmann** [comment]
> I see the upgrades test failed with the same original error this is trying to fix, but after downgrading. This means it's actually not the version with this patch/fix that's failing, it's the previous release. Presumably then we can ignore that specific CI result: https://github.com/cilium/cilium/actions/runs/10065195269/job/27826569570 .

Yeah, that's correct, @tommyp1ckles and I suspect this will be fixed once backported to 1.16.

**Comment by joestringer** [comment]
OK cool. I'll prepare backport for this + one other outstanding 1.16 blocker shortly.
