### PR TITLE
Top 5 errors/warnings in CI

### LINKED ISSUE #5087: CI request: output top 5 error/warning logs
These new summaries in the CI standard output are awesome:

```
Number of "context deadline exceeded" in logs: 0
⚠️  Number of "level=error" in logs: 26
⚠️  Number of "level=warning" in logs: 372
Number of "Cilium API handler panicked" in logs: 0
```

It would be neat if also we could fetch those error/warning logs from the logs, and maybe even just print the first five. 

A more sophisticated logic might get these logs, `sort` them, strip changeable parts like timestamps etc. and run through `uniq` to find each unique error that's occurring. That said, I think that to keep such output to a summary it would still need to be kept to maximum of maybe 10-20 unique messages.

### PR DESCRIPTION
**Pull request by nebril**
fixes #5087

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7321)

### CODE REVIEW

**Comment by nebril** [comment]
test-me-please

**Comment by eloycoto** [comment]
`00:22:24.122  test/helpers/logutils/utils_test.go:21: ExampleLogErrorsSummaryEmpty refers to unknown identifier: LogErrorsSummaryEmpty`

**Comment by nebril** [comment]
test-me-please

File: test/helpers/logutils/utils.go [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+
+	for msg, count := range errors {
+		errs = append(errs, message{msg, count, true})
+	}
+
+	for msg, count := range warnings {
+		errs = append(errs, message{msg, count, false})
+	}
+
+	sort.Sort(sort.Reverse(byImportance(errs)))
```
Comment (eloycoto) [inline test/helpers/logutils/utils.go:85]: instead of doing all the work with the byImportance type I would use here a `sort.Slice`

https://play.golang.org/p/JNhlfYoZgCV

**Review by eloycoto — APPROVED** [review]

**Comment by nebril** [comment]
test-me-please

File: test/helpers/logutils/utils.go [hunk 2]
```diff
@@ -0,0 +1,114 @@
...
+		fmt.Fprintf(&sb, "%sNumber of %q in logs: %d\n", prefix, message, result)
+	}
+	sb.WriteString("Top 5 errors/warnings:\n")
+
+	warns := getErrorWarningMsgs(logs, 5)
+	sb.WriteString(strings.Join(warns, "\n"))
+	return sb.String()
+}
+
+func getErrorWarningMsgs(logs string, n int) []string {
```
Comment (ianvernon) [inline test/helpers/logutils/utils.go:61]: Please add a short comment indicating what this function does for future code maintainers.

File: test/helpers/logutils/utils.go [hunk 3]
```diff
@@ -0,0 +1,114 @@
...
+	msgRegex := regexp.MustCompile(`msg=".*?"( |$)`)
+	errors := map[string]int{}
+	warnings := map[string]int{}
+	for _, line := range strings.Split(logs, "\n") {
+		if strings.Contains(line, errorLogs) {
+			msg := msgRegex.FindString(line)
+			msg = msg[5 : len(msg)-2]
+			errors[msg]++
+		} else if strings.Contains(line, warningLogs) {
+			msg := msgRegex.FindString(line)
```
Comment (ianvernon) [inline test/helpers/logutils/utils.go]: This will only work if the `msg` field is generic and we use `WithFields` for variable information in the logger. I think we use this liberally, but if we are going to move with this approach, we should not be using formatting directives at all in our logs. This is out of scope of this PR, though, just a thought.

File: test/helpers/logutils/utils_test.go [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+Mar 05 07:51:17 runtime cilium-agent[11336]: level=error msg="xDS stream context canceled" error="context canceled" subsys=xds xdsStreamID=3
+Mar 05 07:51:17 runtime cilium-agent[11336]: level=info msg="Envoy: Closing access log connection" subsys=envoy-manager
+Mar 05 07:51:17 runtime cilium-agent[11336]: level=debug msg="xDS stream closed" subsys=xds xdsStreamID=3
+Mar 05 07:51:17 runtime cilium-agent[11336]: level=error msg="error while receiving request from xDS stream" error="rpc error: code = Canceled desc = context canceled" subsys=xds xdsStreamID=2
+Mar 05 07:51:17 runtime cilium-agent[11336]: level=error msg="xDS stream context canceled" error="context canceled" subsys=xds xdsStreamID=1
+Mar 05 07:51:17 runtime cilium-agent[11336]: level=error msg="xDS stream context canceled" error="context canceled" subsys=xds xdsStreamID=1
+Mar 05 07:51:17 runtime cilium-agent[11336]: level=error msg="error while receiving request from xDS stream" error="rpc error: code = Canceled desc = context canceled" subsys=xds xdsStreamID=1`
+	fmt.Println(LogErrorsSummary(log))
```
Comment (ianvernon) [inline test/helpers/logutils/utils_test.go]: I don't see how this is a test - shouldn't there be some form of assertion made here?

**Review by ianvernon — COMMENTED** [review]
Looks great overall! Just some misc. comments / questions.

File: test/helpers/cons.go [hunk 5]
```diff
@@ -192,17 +192,11 @@ const (
 	IPv6Host = "fdff::ff"
 
 	// Logs messages that should not be in the cilium logs.
-	panicMessage        = "panic:"
-	deadLockHeader      = "POTENTIAL DEADLOCK:"               // from github.com/sasha-s/go-deadlock/deadlock.go:header
-	segmentationFault   = "segmentation fault"                // from https://github.com/cilium/cilium/issues/3233
-	NACKreceived        = "NACK received for version"         // from https://github.com/cilium/cilium/issues/4003
-	RunInitFailed       = "JoinEP: "                          // from https://github.com/cilium/cilium/pull/5052
-	selfishThresholdMsg = "Goroutine took lock for more than" // from https://github.com/cilium/cilium/pull/5268
```
Comment (joestringer) [inline test/helpers/cons.go:200]: Do we need to drop this to implement this feature? I think it's important to keep this visible.

File: test/helpers/logutils/utils.go [hunk 6]
```diff
@@ -0,0 +1,114 @@
...
+}
+
+func getErrorWarningMsgs(logs string, n int) []string {
+	msgRegex := regexp.MustCompile(`msg=".*?"( |$)`)
+	errors := map[string]int{}
+	warnings := map[string]int{}
+	for _, line := range strings.Split(logs, "\n") {
+		if strings.Contains(line, errorLogs) {
+			msg := msgRegex.FindString(line)
+			msg = msg[5 : len(msg)-2]
```
Comment (joestringer) [inline test/helpers/logutils/utils.go]: Where does the magic "-2" come from? speech mark  + (space OR endline character)?

**Review by joestringer — COMMENTED** [review]
Excited for this! Definitely agree with @ianvernon about forming messages properly, otherwise common errors will be hidden by the "top5" view. And it'd be nice to simplify the sorting per @eloycoto 's suggestion.

Otherwise LGTM. 

FWIW, the current failure on this PR looks like this:

```
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
Top 5 errors/warnings:
Cilium pods: [cilium-8gktt cilium-fp5wf]
```
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/10544/testReport/k8s-1/8/K8sPolicyTest_Namespaces_policies_Kubernetes_Network_Policy_by_namespace_selector/

Not sure whether there should actually be nonzero values for this. Also, it would be good that if no errors/warnings are found, it somehow prints "None found" or something, to make it clear that there were no errors/warnings in the logs.

File: test/helpers/cons.go (hunk 5 above)
Comment (joestringer) [reply test/helpers/cons.go:200]: Oh, it just got moved to the other file, never mind:)

File: test/helpers/logutils/utils.go (hunk 6 above)
Comment (joestringer) [reply test/helpers/logutils/utils.go]: ~~This will probably actually truncate the final character when logfields are used.~~

Comment (joestringer) [reply test/helpers/logutils/utils.go]: (same elsewhere too)

File: test/helpers/logutils/utils_test.go (hunk 4 above)
Comment (nebril) [reply test/helpers/logutils/utils_test.go]: This is an example: https://golang.org/pkg/testing/#hdr-Examples which is run as part of test suite. I learned about them just recently and I liked them enough to use them. I can change it into normal test with assertion.

**Comment by nebril** [comment]
@eloycoto I did not use `sort.Slice` because it requires you to use inline closure function to define the `less` function, which is for me less explicit than implementing `sort.Interface` by the `byImportance` type.

I just don't see the advantage from using `sort.Slice` here.

File: test/helpers/logutils/utils.go (hunk 6 above)
Comment (nebril) [reply test/helpers/logutils/utils.go]: You're right, I dropped the trailing space/newline from regex and changed this to `len(msg)-1`

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

File: test/helpers/logutils/utils_test.go (hunk 4 above)
Comment (joestringer) [reply test/helpers/logutils/utils_test.go]: @nebril if this doesn't fail a unit test, we *will* ignore the output  :)

Comment (ianvernon) [reply test/helpers/logutils/utils_test.go]: @nebril had no idea about `Examples`, nice! I do think a test would be nice to have, though.

File: test/helpers/logutils/utils.go (hunk 3 above)
Comment (ianvernon) [reply test/helpers/logutils/utils.go]: Filed https://github.com/cilium/cilium/pull/7321#discussion_r263055692 for tracking this.

File: test/helpers/logutils/utils_test.go (hunk 4 above)
Comment (ianvernon) [reply test/helpers/logutils/utils_test.go]: Oops, resolving, you added the assertions.

**Review by ianvernon — APPROVED** [review]

**Comment by joestringer** [comment]
test-me-please

**Comment by tgraf** [comment]
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:339
Test Panicked
/usr/local/go/src/runtime/panic.go:502

```

**Comment by tgraf** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by tgraf** [comment]
@nebril Did you look into the failure? It seems real.

**Comment by nebril** [comment]
@tgraf yeah, the `test panicked` seems like it could be real, I am on it.

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please

**Comment by nebril** [comment]
test-me-please
