### PR TITLE
gateway-api: Align GatewayClass SupportedFeatures 

### LINKED ISSUE #34266: Gateway API SupportedFeatures API change
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0 and lower than v1.17.0

### What happened?

https://github.com/kubernetes-sigs/gateway-api/pull/3200 introduced a breaking change to SupportedFeatures experimental API. 

https://github.com/cilium/cilium/blob/69a626c336098dd7ced33994680aad4cdc7426ea/operator/pkg/gateway-api/gatewayclass_reconcile.go#L47-L66 has to be changed.

I believe it will broke the controller otherwise. 

/cc @youngnick 

### How can we reproduce the issue?

N/A

### Cilium Version

N/A

### Kernel Version

N/A

### Kubernetes Version

Gateway API prospective version 1.2

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by LiorLieberman**
https://github.com/kubernetes-sigs/gateway-api/pull/3200 introduced a breaking change to SupportedFeatures experimental API. This PR aligns the controller with the new API structure.

I had to bump some dependencies to make it work, let me know if this is the way to go

Fixes: #34266 
Also fixes #34262 

```release-note
Align GatewayClass SupportedFeatures with the new upstream API
```

### CODE REVIEW

**Comment by LiorLieberman** [comment]
I dont think I have permissions to add `release-note` label

**Comment by LiorLieberman** [comment]
@aanm Thanks. Not sure how important it is, but I am not sure it is a "proper" bug, it is mostly to align the API with the new changes introduced in the upstream.

File: operator/pkg/gateway-api/gatewayclass_status.go [hunk 1]
```diff
@@ -4,24 +4,59 @@
...
 )
 
 const (
 	gatewayClassAcceptedMessage    = "Valid GatewayClass"
 	gatewayClassNotAcceptedMessage = "Invalid GatewayClass"
 )
 
+var supportedFeatures = features.AllFeatures
+
+var gatewayClassSupportedFeatures = getSupportedFeatures()
```
Comment (sayboras) [inline operator/pkg/gateway-api/gatewayclass_status.go:23]: assume the package level variable is used to avoid re-evaluating

File: operator/pkg/gateway-api/gatewayclass_status.go [hunk 2]
```diff
@@ -4,24 +4,59 @@
...
+
+var exemptFeatures = []features.SupportedFeature{
+	"GatewayStaticAddresses",
+	"HTTPRouteParentRefPort",
+	"MeshConsumerRoute",
+}
```
Comment (sayboras) [inline operator/pkg/gateway-api/gatewayclass_status.go:29]: just a small question, do we still need to specify the exempt feature in GHA workflow (e.g.  conformance-gateway-api.yaml)? or will the test framework read from gateway class status?

**Review by sayboras — COMMENTED** [review]
Thanks a lot for your kind help, I have two small questions as per below, just for my understanding.

File: operator/pkg/gateway-api/gatewayclass_status.go (hunk 1 above)
Comment (LiorLieberman) [reply operator/pkg/gateway-api/gatewayclass_status.go:23]: exactly 👍

File: operator/pkg/gateway-api/gatewayclass_status.go (hunk 2 above)
Comment (LiorLieberman) [reply operator/pkg/gateway-api/gatewayclass_status.go:29]: We still havent added the change for the framework to read from GWC. We need to graduate this feature before we do it.

Comment (sayboras) [reply operator/pkg/gateway-api/gatewayclass_status.go:29]: ah thanks for sharing, and thanks for your work in upstream :medal_military:

**Comment by sayboras** [comment]
Gateway API failures seem to be related to this change. Is this feature only available for experimental  channel ? If yes, we might need to skip the test for standard channel and conformance profile run.

**Review by learnitall — APPROVED** [review]
Vendor changes LGTM. Thank you so much!

**Comment by LiorLieberman** [comment]
> Gateway API failures seem to be related to this change. Is this feature only available for experimental channel ? If yes, we might need to skip the test for standard channel and conformance profile run.

it is only available in experimental, but regardless of the upstream change, SupportedFeatures is experimental so it makes me think how the test worked previously

**Comment by LiorLieberman** [comment]
The Gateway API test fails both for experimental `true` and `false` for the same error, so probably not related

**Review by youngnick — COMMENTED** [review]
Changes LGTM, but I wonder if we should be updating the `gwc` pointer with the result of the function (since in each case we're returning the `gwc` pointer?

I agree that it does look like the failures in the tests are related to something about this change.

**Comment by LiorLieberman** [comment]
> Changes LGTM, but I wonder if we should be updating the `gwc` pointer with the result of the function (since in each case we're returning the `gwc` pointer?

true, I think we can just not returning it, like 
```go
func setGatewayClassSupportedFeatures(gwc *gatewayv1.GatewayClass) {
	gwc.Status.SupportedFeatures = gatewayClassSupportedFeatures
}
```

**Comment by youngnick** [comment]
@LiorLieberman, I think the Gateway API CI failures will probably be fixed with a rebase (which we need for the `go.mod` conflict anyway)

**Comment by sayboras** [comment]
> The Gateway API test fails both for experimental `true` and `false` for the same error, so probably not related to experimental/not experimental

Thanks both, I am taking a look on this failure, will push this change forward.

**Comment by sayboras** [comment]
Ah it's due to the CRD version used in CI, can you add the below patch in your PR ? 

The changes are tested in https://github.com/cilium/cilium/pull/34445 with https://github.com/cilium/cilium/actions/runs/10447139206/job/28925606662

```patch
diff --git a/.github/workflows/conformance-gateway-api.yaml b/.github/workflows/conformance-gateway-api.yaml
index e012ff55276..d1645ef90d4 100644
--- a/.github/workflows/conformance-gateway-api.yaml
+++ b/.github/workflows/conformance-gateway-api.yaml
@@ -60,7 +60,9 @@ concurrency:
 
 env:
   kind_config: .github/kind-config.yaml
-  gateway_api_version: v1.1.0
+  # Use the upstream main branch for the gateway-api version for development.
+  # Please update to tag when releasing.
+  gateway_api_version: main
   timeout: 5m
 
 jobs:
```

**Comment by LiorLieberman** [comment]
> Ah it's due to the CRD version used in CI, can you add the below patch in your PR ?
> 
> The changes are tested in #34445 with https://github.com/cilium/cilium/actions/runs/10447139206/job/28925606662

Just did that, thanks!

**Review by sayboras — APPROVED** [review]

File: .github/workflows/conformance-gateway-api.yaml [hunk 3]
```diff
@@ -60,7 +60,9 @@ concurrency:
 
 env:
   kind_config: .github/kind-config.yaml
-  gateway_api_version: v1.1.0
+  # Use the upstream main branch for the gateway-api version for development.
+  # Please update to tag when releasing.
+  gateway_api_version: main
```
Comment (viktor-kurchenko) [inline .github/workflows/conformance-gateway-api.yaml:65]: Is it correct to understand that the version should be updated to a specific tag during the Cilium release?

Comment (sayboras) [reply .github/workflows/conformance-gateway-api.yaml:65]: you are right,  probably it will be v1.2.0 :+1:.

It might not be a strict requirement, but we would love to keep  stable branch pinned, and main branch floating (so that any breaking will be highlighted earlier).

Comment (viktor-kurchenko) [reply .github/workflows/conformance-gateway-api.yaml:65]: I wonder if this needs to be reflected in the release doc not to forget?

Comment (sayboras) [reply .github/workflows/conformance-gateway-api.yaml:65]: yes, I can take the follow-up action :+1:

Comment (viktor-kurchenko) [reply .github/workflows/conformance-gateway-api.yaml:65]: Thank you!!!
