### PR TITLE
daemon: do not add endpoint if client connection closes during add operation

### LINKED ISSUE #6059: Failed to replace Qdisc for lxcfc6dee5519e6: Link not found
Link:
https://jenkins.cilium.io/job/cilium-ginkgo/job/cilium/job/master/1802/execution/node/98/log/?consoleFull

```
15:38:06 STEP: Waiting for all etcd-operator pods are ready
15:38:54 STEP: Applying deployments
15:38:57 STEP: Waiting for pods to be ready
15:44:10 === Test Finished at 2018-10-24T15:43:59Z====
15:44:18 ===================== TEST FAILED =====================
15:44:25 prometheus-core-5c9fbf5cc6-j59nk => none
15:44:25 deathstar-7bbc6d774d-8kz26 => none
15:44:25 etcd-operator-8b5cbb6d6-znr96 => none
15:44:25 deathstar-7bbc6d774d-79ljj => none
15:44:25 spaceship-6db9c5df76-msf2q => none
15:44:25 cilium-etcd-ztslk8vpf2 => none
15:44:25 kube-dns-6f4c8dbcd4-2bckf => none
15:44:25 cilium-etcd-cbhx49xbjm => none
15:44:25 cilium-etcd-lztngq7fbr => none
15:44:25 microscope => none
15:44:25 spaceship-6db9c5df76-9k22d => none
15:44:25 spaceship-6db9c5df76-k92dd => none
15:44:25 spaceship-6db9c5df76-wvp6c => none
15:44:25 xwing-f6d5fc5-vlhcv => none
15:44:30 <Checks>
15:44:30 ⚠️  Found a 'JoinEP: ' in logs
15:44:30 Number of 'context deadline exceeded' in logs: 4
15:44:30 ⚠️  Number of 'level=error' in logs: 15
15:44:30 ⚠️  Number of 'level=warning' in logs: 85
15:44:30 Number of 'Cilium API handler panicked' in logs: 0
15:44:30 ⚠️  Number of 'Goroutine took lock for more than' in logs: 542
15:44:30 Cilium pods: [cilium-7tmcj cilium-r4dcg]
15:44:30 Netpols loaded: 
15:44:30 CiliumNetworkPolicies loaded: 
15:44:30 Endpoint Policy Enforcement:
15:44:30      prometheus-core-5c9fbf5cc6-j59nk   =>   none
15:44:30      deathstar-7bbc6d774d-8kz26         =>   none
15:44:30      etcd-operator-8b5cbb6d6-znr96      =>   none
15:44:30      deathstar-7bbc6d774d-79ljj         =>   none
15:44:30      spaceship-6db9c5df76-msf2q         =>   none
15:44:30      cilium-etcd-ztslk8vpf2             =>   none
15:44:30      kube-dns-6f4c8dbcd4-2bckf          =>   none
15:44:30      cilium-etcd-cbhx49xbjm             =>   none
15:44:30      cilium-etcd-lztngq7fbr             =>   none
15:44:30      microscope                         =>   none
15:44:30      spaceship-6db9c5df76-9k22d         =>   none
15:44:30      spaceship-6db9c5df76-k92dd         =>   none
15:44:30      spaceship-6db9c5df76-wvp6c         =>   none
15:44:30      xwing-f6d5fc5-vlhcv                =>   none
15:44:30 
15:44:30 </Checks>
15:44:30 
15:44:30 [[ATTACHMENT|3410ba8d_K8sDemosTest_Tests_Star_Wars_Demo.zip]]
15:44:30 
15:44:30 • Failure [1631.186 seconds]
15:44:30 K8sDemosTest
15:44:30 /home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:351
15:44:30   Tests Star Wars Demo [It]
15:44:30   /home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:383
15:44:30 
15:44:30   Pods are not ready after timeout
15:44:30   Expected
15:44:30       <*errors.errorString | 0xc4201dc870>: {
15:44:30           s: "Timeout reached: timed out waiting for pods with filter  to be ready",
15:44:30       }
15:44:30   to be nil
15:44:30 
15:44:30   /home/jenkins/workspace/cilium-ginkgo_cilium_master-QVKDPVJ2A6E272IRUX7X6DCB5FBLCQDKRTOMHPZS7ZECX3RM5C3A/src/github.com/cilium/cilium/test/k8sT/demos.go:118
```

From `cilium-test.log`:
```
2018-10-24T15:42:44.573472079Z level=warning msg="JoinEP: Failed to load program" containerID=3ef3d84dc0 datapathPolicyRevision=0 desiredPolicyRevision=3 endpointID=37832 error="Failed to replace Qdisc for lxcfc6dee5519e6: Link not found" file-path=37832_next/bpf_lxc.o ipv4=10.10.0.52 ipv6="f00d::a0a:0:0:93c8" k8sPodName=default/spaceship-6db9c5df76-k92dd subsys=datapath-loader veth=lxcfc6dee5519e6
2018-10-24T15:42:44.573493534Z level=info msg="Recompiled endpoint BPF program" BPFCompilationTime=3m28.91959295s containerID=3ef3d84dc0 datapathPolicyRevision=0 desiredPolicyRevision=3 endpointID=37832 error="Failed to replace Qdisc for lxcfc6dee5519e6: Link not found" ipv4=10.10.0.52 ipv6="f00d::a0a:0:0:93c8" k8sPodName=default/spaceship-6db9c5df76-k92dd subsys=endpoint
2018-10-24T15:42:44.573615477Z level=error msg="Restoring endpoint state after BPF regeneration failed" containerID=3ef3d84dc0 datapathPolicyRevision=0 desiredPolicyRevision=3 endpointID=37832 ipv4=10.10.0.52 ipv6="f00d::a0a:0:0:93c8" k8sPodName=default/spaceship-6db9c5df76-k92dd subsys=endpoint
```

We may need to check upon endpoint restore that the link device for an endpoint still exists, it seems like perhaps the device disappeared while Cilium was down/restarting.

Unfortunately for this one, we're missing most of the bugtool output from the zip (@eloycoto , any ideas why?)

[3410ba8d_K8sDemosTest_Tests_Star_Wars_Demo (1).zip](https://github.com/cilium/cilium/files/2516778/3410ba8d_K8sDemosTest_Tests_Star_Wars_Demo.1.zip)

### PR DESCRIPTION
**Pull request by aanm**
If a client closes the connection during a endpoint creation with the
cilium-agent while the cilium-agent is resolving the identity for that
particular endpoint, the cilium-agent will continue to create the endpoint
although the endpoint should not be created as the connection with the client
was terminated.

This bug also explains the problem when an interface does not exist when
cilium-agent tries to regenerate the endpoint. Since the client, in this case
cilium-cni, times out while waiting for a response from the cilium-agent,
cilium-cni cleans up the interface as it assumes the cilium-agent will not be
able to perform the task requested. As cilium-agent was not aware the client
terminated the connection, once it tries to regenerate the endpoint, it will
fail to do so as the interface no longer exists since the interface was removed
by the client, cilium-cni.

Fixes: 65fe98c4f391 ("cni: Synchroneous pod label retrieval on CNI add")
Signed-off-by: André Martins <andre@cilium.io>

Fixes: https://github.com/cilium/cilium/issues/6059

Adding `area/k8s` to trigger more tests

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6551)

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
Previous test passed but forgot to add k8s tests

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

File: daemon/endpoint.go [hunk 1]
```diff
@@ -213,6 +213,14 @@ func (d *Daemon) createEndpoint(ctx context.Context, epTemplate *models.Endpoint
...
 	ep.UpdateLabels(d, addLabels, infoLabels, true)
 
+	// Do not add endpoint to the endpoint manager if client abort connection
+	select {
+	case <-ctx.Done():
+		log.WithError(ctx.Err()).Warn("Aborting endpoint join due client connection closed")
+		return PutEndpointIDFailedCode, fmt.Errorf("aborting endpoint %d join due client connection closed", ep.ID)
+	default:
+	}
+
```
Comment (brb) [inline daemon/endpoint.go:223]: What happens if a client closes the connection after `AddEndpoint` has successfully returned?

Wouldn't it make sense to do a cleanup at the end of the method `createEndpoint` if we detect that the connection has been closed?

Comment (aanm) [reply daemon/endpoint.go:223]: That should be covered by lines 290-297 of this file.

**Comment by aanm** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]

**Comment by ianvernon** [comment]
Great find @aanm !
