### PR TITLE
bpf: fix flakes when checking metrics map values.

### LINKED ISSUE #28280: CI: [v1.13] BPF unit/integration tests - TestBPF/ipsec_from_lxc_test.o
## CI failure

Hit on https://github.com/cilium/cilium/pull/28251: https://github.com/cilium/cilium/actions/runs/6309322047/job/17129032069?pr=28251
Succeeded when rerun a second time.

```
go test ./bpf_tests -exec sudo -bpf-test-path /home/runner/work/cilium/cilium/bpf/tests 
--- FAIL: TestBPF (3.02s)
    --- FAIL: TestBPF/ipsec_from_lxc_test.o (0.17s)
        bpf_test.go:212: Conntrack lookup 1/2: src=192.168.0.1:22330 dst=192.168.0.2:80
        bpf_test.go:212: Conntrack lookup 2/2: nexthdr=6 flags=1
        bpf_test.go:212: CT verdict: New, revnat=0
        bpf_test.go:212: Successfully mapped addr=192.168.0.2 to identity=233
        bpf_test.go:212: Conntrack create: proxy-port=0 revnat=0 src-identity=1048575 lb=0.0.0.0
        bpf_test.go:212: Unknown message type=197 arg1=74 arg2=65610
        --- FAIL: TestBPF/ipsec_from_lxc_test.o/01_ipv4_from_lxc_no_node_id (0.00s)
            bpf_test.go:421: assert failed at ipsec_from_lxc_test.c:142
        bpf_test.go:212: Conntrack lookup 1/2: src=192.168.0.1:22330 dst=192.168.0.2:80
        bpf_test.go:212: Conntrack lookup 2/2: nexthdr=6 flags=1
        bpf_test.go:212: CT entry found lifetime=296, revnat=0
        bpf_test.go:212: CT verdict: Established, revnat=0
        bpf_test.go:212: Successfully mapped addr=192.168.0.2 to identity=233
        bpf_test.go:212: Local container found ifindex 74 seclabel 18944
        bpf_test.go:212: Conntrack lookup 1/2: src=[::0:1]:22330 dst=[::0:2]:80
        bpf_test.go:212: Conntrack lookup 2/2: nexthdr=6 flags=1
        bpf_test.go:212: CT verdict: New, revnat=0
        bpf_test.go:212: Successfully mapped addr.p4=[::0:2] to identity=233
        bpf_test.go:212: Conntrack create: proxy-port=0 revnat=0 src-identity=1048575
        bpf_test.go:212: Encapsulating to node 94 (0x5e) from seclabel 65630
        bpf_test.go:212: Local container found ifindex 94 seclabel 24064
FAIL
FAIL	github.com/cilium/cilium/test/bpf_tests	3.064s
FAIL
make: *** [Makefile:88: run_bpf_tests] Error 1
make: Leaving directory '/home/runner/work/cilium/cilium/test'
Run 'make -C test run_bpf_tests' locally to investigate failures
```

### PR DESCRIPTION
**Pull request by tommyp1ckles**
The ipsec_from_lxc_test and tc_lxc_policy_drop test files both perform assertions on expected count values stored in the metric map. This results in test flakes as if the map put and map get are performed while running on different cpus then the assertions may fail.

This introduces a new helper macro in tests which iterates possible percpu hash values for a particular key until an expected count is found or we exceed the number of cpu slots.

Fixes: #28280

### CODE REVIEW

File: bpf/tests/common.h [hunk 1]
```diff
@@ -272,4 +272,27 @@ _Pragma("unroll")						\
...
+	struct metrics_value *__entry = NULL; \
+	bool found = false; \
+	/* Iterate until lookup encounters null when hitting cpu number */ \
+	/* Assumes at most 128 CPUS */ \
+	for (int i = 0; i < 128; i++) { \
+		__entry = map_lookup_percpu_elem(&METRICS_MAP, &key, i); \
+		if (!__entry) { \
+			break; \
+		} \
+		if (__entry->count == count) { \
```
Comment (jschwinger233) [inline bpf/tests/common.h]: Maybe we should accumulate `__entry->count` and compare the `count` with summed up `__entry->count`?

Something like:
```suggestion
__u64 sum;
for (int i = 0; i < 128; i++) {
    __entry = map_lookup_percpu_elem(&METRICS_MAP, &key, i);
    if (!__entry) break;
    sum += __entry->count;
}
if (sum == count) found=true;
```

Comment (jschwinger233) [reply bpf/tests/common.h]: I think it depends on the semantics of macro. The macro we create here is `assert_metrics_contains`, so your implementation above is accurate. My suggested code is more like `assert_metrics_count`.

**Review by jschwinger233 — COMMENTED** [review]
Thanks Tom! Just a small question regarding macro semantic.

File: bpf/tests/common.h [hunk 2]
```diff
@@ -272,4 +272,27 @@ _Pragma("unroll")						\
 	return 0;						\
 }
 
+static void *(*map_lookup_percpu_elem)(void *map, const void *key, unsigned int cpu) = (void *)195;
```
Comment (gentoo-root) [inline bpf/tests/common.h]: Any reason not to use BPF_FUNC and put it in bpf/include/bpf/helpers.h?

File: bpf/tests/common.h (hunk 1 above)
Comment (tommyp1ckles) [reply bpf/tests/common.h]: This makes sense, made the change 👍

File: bpf/tests/common.h [hunk 3]
```diff
@@ -272,4 +272,25 @@ _Pragma("unroll")						\
...
+
+/* Asserts that the per-cpu metrics map contains at least one entry that */
+/* contains a specified count given a metrics_key.*/
+#define assert_metrics_count(key, count) \
+({ \
+	struct metrics_value *__entry = NULL; \
+	__u64 sum = 0; \
+	/* Iterate until lookup encounters null when hitting cpu number */ \
+	/* Assumes at most 128 CPUS */ \
+	for (int i = 0; i < 128; i++) { \
```
Comment (gentoo-root) [inline bpf/tests/common.h]: Let's maybe `#define NR_CPUS 128` somewhere in a header file? If we can't determine the real number of CPUs, it would still be better to define this constant with the standard name (as used in the kernel), than bury it deep in the code.

**Comment by tommyp1ckles** [comment]
@gentoo-root sorry meant to hit the rerequest review button on grays review but you posted yours at that moment 😅

File: bpf/tests/common.h (hunk 2 above)
Comment (tommyp1ckles) [reply bpf/tests/common.h]: I'm using the cilium-builder docker image to build this, I get:

```
/home/tom/go/src/github.com/cilium/cilium/bpf/include/linux/../bpf/helpers.h:38:13: error: use of undeclared identifier 'BPF_FUNC_map_lookup_percpu_elem'
static void BPF_FUNC(map_lookup_percpu_elem, const void *map, const void *key, unsigned int cpu);
```

It seems like the version of `linux/bpf.h` we're using doesn't include that definition.

Comment (tommyp1ckles) [reply bpf/tests/common.h]: @gentoo-root not sure the best course of action here, any advice?

Comment (gentoo-root) [reply bpf/tests/common.h]: We can update bpf.h, we do that when needed:

https://github.com/cilium/cilium/commit/049a3a9da86e5221867013ba99a7bbb581b1b131
https://github.com/cilium/cilium/commit/271a96da32113b9c02465aca3e2587584164924a

Comment (tommyp1ckles) [reply bpf/tests/common.h]: Added a commit to sync with latest upstream commit, there's a few changes in the diff - I assume those are all ok/compatible?

Comment (tommyp1ckles) [reply bpf/tests/common.h]: @gentoo-root

Comment (gentoo-root) [reply bpf/tests/common.h]: Yeah, should be good, as long as the tests don't start failing due to this.

**Review by gentoo-root — APPROVED** [review]

File: bpf/tests/common.h [hunk 4]
```diff
@@ -272,4 +275,22 @@ _Pragma("unroll")						\
...
+	__u64 sum = 0; \
+	/* Iterate until lookup encounters null when hitting cpu number */ \
+	/* Assumes at most 128 CPUS */ \
+	for (int i = 0; i < NR_CPUS; i++) { \
+		__entry = map_lookup_percpu_elem(&METRICS_MAP, &key, i); \
+		if (!__entry) { \
+			break; \
+		} \
+		sum++; \
+		break; \
```
Comment (jschwinger233) [inline bpf/tests/common.h]: This `break` limits `sum` from increasing beyond 1, is it intentional?

And maybe we should `sum += __entry->count` instead of `sum++`? Otherwise sum is always set to the number of CPUs.

**Review by jschwinger233 — CHANGES_REQUESTED** [review]

File: bpf/tests/common.h (hunk 4 above)
Comment (tommyp1ckles) [reply bpf/tests/common.h]: Woops yup thanks 😅 , fixed

**Review by jschwinger233 — APPROVED** [review]
Thanks!
