### PR TITLE
bpf: Re-introduce ICMPv6 NS responder on from-netdev

### LINKED ISSUE #30926: Cilium doesn't send neighbor advertisements in response to neighbor solicitiations for pod IPv6 IPs
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/cilium/cilium/pull/12086 introduced a feature that cilium can respond to IPv6 NS on behalf of the pods on the same host, but this feature doesn't work on v1.15.

### Cilium Version

v1.15.1

### Kernel Version

Linux gray-Latitude-5530 6.5.0-18-generic #18~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb  7 11:40:03 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-15T00:36:28Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}

### Regression

Yes, v1.13 still works.

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

Repro steps:

1. write a helm.values file with following content:

```
bpf:
  masquerade: true
enableIPv6Masquerade: false
extraConfig:
  enable-ipv6-ndp: "true"
  ipv6-mcast-device: eth0
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4MaskSize: "23"
    clusterPoolIPv4PodCIDRList:
      - 10.128.0.0/10
    clusterPoolIPv6PodCIDRList:
      - fc00:f853:ccd:e793::100:0/104
    clusterPoolIPv6PodCIDRMask: 120
ipv6:
  enabled: true
k8sServiceHost: kind-control-plane
k8sServicePort: "6443"
kubeProxyReplacement: true
```

2. create a kind cluster

```
./contrib/scripts/kind.sh --xdp --secondary-network "" 3 "" "" iptables dual 0.0.0.0 6443
```

3. create cilium v1.15.1, without kind-worker3

```
kubectl patch node kind-worker3 --type=json -p='[{"op":"add","path":"/metadata/labels/cilium.io~1no-schedule","value":"true"}]'

cilium install --nodes-without-cilium=kind-worker3 --wait     --chart-directory=./install/kubernetes/cilium        -f ./helm.values  --version v1.15.1
```
4. create a Nginx pod

```
kubectl apply -f https://k8s.io/examples/application/deployment.yaml
```

5. add a route on kind-worker3 to make sure kind-worker3 sends IPv6 NS for nginx pod:

```
docker exec -it kind-worker3 ip -6 r a $ipv6_of_nginx_pod dev eth0
```

6. check connectivity between kind-worker3 and nginx pod, should be fine but broken

```
docker exec -it kind-worker3 curl [c00:f853:ccd:e793::100:18b]:80
```

Running tcpdump on kind-worker3 eth0, it turns out IPv6 NS for pod never got reply:

```
# fc00:f853:ccd:e793::100:18b is ipv6 of nginx pod

listening on eth0, link-type EN10MB (Ethernet), snapshot length 262144 bytes
12:50:21.439388 IP6 fc00:c111::4 > ff02::1:ff00:18b: ICMP6, neighbor solicitation, who has fc00:f853:ccd:e793::100:18b, length 32
12:50:22.468934 IP6 fc00:c111::4 > ff02::1:ff00:18b: ICMP6, neighbor solicitation, who has fc00:f853:ccd:e793::100:18b, length 32
12:50:23.493014 IP6 fc00:c111::4 > ff02::1:ff00:18b: ICMP6, neighbor solicitation, who has fc00:f853:ccd:e793::100:18b, length 32
^C
```

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jschwinger233**
This reverts commit 658071414ca4606e537bc4bbb37dcae5e18cd7dc, to fix the breakage of "IPv6 NS responder for pod" introduced by https://github.com/cilium/cilium/pull/12086 (bpf: Reply NA when recv ND for local IPv6 endpoints).

658071414ca4606e537bc4bbb37dcae5e18cd7dc was merged to solve https://github.com/cilium/cilium/issues/14509. To not revive #14509, this commit also passes through ICMPv6 NS if the target is native node IP (eth0's addr). By letting stack take care of those NS-for-node-IP packets, we managed to:

1. Solve #14509 again, but in a way keeping NS responder. The cause of #14509 was NS responder always generates ND whose source IP is "router_ip" (cilium_internal_ip) rather than "node_ip". Once we pass those NS-for-node-IP packets to stack, the ND response would naturally have "node_ip" as source.

2. Avoid the fib_lookup failure mentioned at https://github.com/cilium/cilium/pull/30837#issuecomment-1960897445.

This PR also adds bpf unit test to cover IPv6 NS responder feature.

Fixes: #30926 

```release-note
Fixes an IPv6 issue that cilium doesn't respond to Neighbor Solicitation targeting the pods on same node.
```

### CODE REVIEW

**Comment by jschwinger233** [comment]
> ci-e2e keeps failing on north-south-loadbalancing but I couldn't make a local repro: https://github.com/cilium/cilium/actions/runs/7971912812/job/21798175918
> 
> Adding pwru gh action to see if I can get something useful.

This turns out to be a kernel specific bug.

https://github.com/cilium/cilium/commit/c0dfeb0f8460f44c3983d5bfa15b6afcdc5baf51 (cc @julianwiedmann ) added a testcase for 5.4 with KPR=on + routing=vxlan, revealed this hidden bug which was accidentally fixed on 1.14, but now come back again when I intended to simply revert #25329 .

The scenario is NS connectivity, we are curling from outside to node_ip:node_port. The key part is when first TCP reply with syn+ack arrives at cilium_vxlan, it is supposed to be rev-NAT-ed to the original tuple, then to do a bpf_fib_lookup followed by bpf_redirect. 

With or without bpf NS responder makes a difference for v6 neighbor system:
1. without bpf NS responder, when curling from outside, the ICMP6 NS for node_ip from outside will be handled by stack, as a result a ipv6 neigh entry will be recorded on the node.
2. with bpf NS responder, the NS for node_ip from outside is taken care of be bpf (XDP?), and kernel doesn't get a chance to generate a v6 neigh entry for outside source ip.

Then it's going to affect bpf_fib_lookup:
1. without bpf NS responder, bpf_fib_lookup returns 0
2. with bpf NS responder, bpf_fib_lookup returns NO_NEIGH, and
   1. for kernel 5.10+, we have `HAVE_FIB_INDEX` to tolerate NO_NEIGH, so that cilium can call the `bpf_redirecet_neigh` to make things right
   2. for kernel 5.4, without `HAVE_FIB_INDEX`, cilium turns to use `DIRECT_ROUTING_DEV_IFINDEX` as fallback, which unfortunately is set to the index of eth1 instead of eth0 for some reasons. So skb ends up being redirected to a wrong netdev, breaking the connectivity.

https://github.com/cilium/cilium/issues/27642 is going to be helpful once we have the necessary kernel patch backport.

For now, I'm going to work another solution: bring back bpf NS responder only if the NS is asking for a pod; if NS is asking for the node IP, just hand it over to stack.

**Comment by julianwiedmann** [comment]
> 2\. for kernel 5.4, without `HAVE_FIB_INDEX`, cilium turns to use `DIRECT_ROUTING_DEV_IFINDEX` as fallback, which unfortunately is set to the index of eth1 instead of eth0 for some reasons. So skb ends up being redirected to a wrong netdev, breaking the connectivity.

It actually should be using the `ifindex` from the CT entry, which was cached when processing the connection's first request:
https://github.com/cilium/cilium/blob/190733402d6b190cbdba220f29d87b56b674f87b/bpf/lib/nodeport.h#L1398-L1400
https://github.com/cilium/cilium/blob/190733402d6b190cbdba220f29d87b56b674f87b/bpf/lib/nodeport.h#L960-L962

**Comment by jschwinger233** [comment]
@julianwiedmann Thanks for pointing this out :thanks:

What will happen if the cluster is created with `kind.sh --secondary-network` + `cilium install --helm-set=devices='{eth0,eth1}'?

It looks `patchHostNetdevDatapath()` will finally be called with device=eth1:

https://github.com/cilium/cilium/blob/190733402d6b190cbdba220f29d87b56b674f87b/pkg/datapath/loader/loader.go#L366

then NATIVE_DEV_IFINDEX will be set to index of eth1?

https://github.com/cilium/cilium/blob/190733402d6b190cbdba220f29d87b56b674f87b/pkg/datapath/loader/loader.go#L184-L186

That could explain why eth1 is chosen when bpf_fib_lookup fails on NO_NEIGH.

**Comment by julianwiedmann** [comment]
> > What will happen if the cluster is created with `kind.sh --secondary-network` + `cilium install --helm-set=devices='{eth0,eth1}'` ?
> > It looks `patchHostNetdevDatapath()` will finally be called with device=eth1:
> 
> My expectation would be that we attach `bpf_host` to both `eth0` and `eth1`. And while loading the program, the agent then patches `NATIVE_DEV_IFINDEX` in the template with the respective `ifindex`.

discussing offline, Gray found an issue in how we inject `NATIVE_DEV_IFINDEX` into `bpf_xdp` (which would create the relevant CT entry, as the test scenario uses `lb-acceleration`).

**Comment by julianwiedmann** [comment]
Just to confirm my understanding:

We hook the IPv6 NS responder code back into `from-netdev`, `from-host` and `to-netdev`. But now only send replies for local pods. This restores the missing functionality from https://github.com/cilium/cilium/pull/12086.

I understand that we need the hook in `from-netdev`. But why `from-host` and `to-netdev`?

File: bpf/lib/icmp6.h [hunk 1]
```diff
@@ -309,15 +310,27 @@ static __always_inline int __icmp6_handle_ns(struct __ctx_buff *ctx, int nh_off)
...
+			 * We pass these packets to stack to make sure:
+			 *
+			 * 1. The response NA has node IP as source address instead of
+			 * router IP, to address https://github.com/cilium/cilium/issues/14509.
+			 *
+			 * 2. Kernel stack can record a neighbor entry for the
+			 * source IP, to avoid bpf_fib_lookup failure as mentioned at
+			 * https://github.com/cilium/cilium/pull/30837#issuecomment-1960897445.
+			 */
+			return CTX_ACT_OK;
```
Comment (julianwiedmann) [inline bpf/lib/icmp6.h:332]: Just to note - as this is executed in a tail-call, such traffic then skips all subsequent code that would normally be present in `from-netdev`. That's quite subtle :slightly_smiling_face:.

**Comment by jschwinger233** [comment]
> But why from-host and to-netdev?

Indeed, let me wrap the `icmp6_host_handle()` inside a `if (!from_host)`.

File: bpf/bpf_host.c [hunk 2]
```diff
@@ -495,7 +494,7 @@ handle_to_netdev_ipv6(struct __ctx_buff *ctx, struct trace_ctx *trace, __s8 *ext
 		return hdrlen;
 
 	if (likely(nexthdr == IPPROTO_ICMPV6)) {
-		ret = icmp6_host_handle(ctx, ETH_HLEN + hdrlen);
+		ret = icmp6_host_handle(ctx, ETH_HLEN + hdrlen, ext_err);
```
Comment (julianwiedmann) [inline bpf/bpf_host.c]: This user would now also pick up the changed behaviour in `icmp6_host_handle()`. Is that intentional, or should we pass a flag that we don't want the NS responder to be active for this code path?

File: bpf/lib/icmp6.h [hunk 3]
```diff
@@ -446,9 +463,6 @@ icmp6_host_handle(struct __ctx_buff *ctx, int l4_off)
 	 * |       ICMPv6-unassigned         |  CTX_ACT_DROP   |      |
 	 */
 
-	if (type == ICMP6_NS_MSG_TYPE)
-		return CTX_ACT_OK;
-
```
Comment (julianwiedmann) [inline bpf/lib/icmp6.h]: Do we want to keep this now, to tolerate NS for `!handle_ns` ?

File: bpf/bpf_host.c [hunk 4]
```diff
@@ -144,31 +144,28 @@ handle_ipv6(struct __ctx_buff *ctx, __u32 secctx __maybe_unused,
...
+	__u8 nexthdr;
 
 	if (!revalidate_data(ctx, &data, &data_end, &ip6))
 		return DROP_INVALID;
 
-#ifdef ENABLE_HOST_FIREWALL
 	nexthdr = ip6->nexthdr;
 	hdrlen = ipv6_hdrlen(ctx, &nexthdr);
 	if (hdrlen < 0)
 		return hdrlen;
```
Comment (julianwiedmann) [inline bpf/bpf_host.c:161]: Looking at it, I think we could limit this code section to `is_defined(ENABLE_HOST_FIREWALL) || !from_host`. But let's consider that in a follow-up.

**Review by julianwiedmann — APPROVED** [review]
lgtm, thank you Gray! Let's hope that CI still likes it :slightly_smiling_face:.

**Comment by jschwinger233** [comment]
CI was all green, having done a rebase to catch up with Dylan's tailcall patches with small changes:

```diff
--- a/bpf/tests/ipv6_ndp_from_netdev_test.c
+++ b/bpf/tests/ipv6_ndp_from_netdev_test.c
@@ -65,7 +65,7 @@ int ipv6_from_netdev_ns_for_pod_setup(struct __ctx_buff *ctx)
 {
 	endpoint_v6_add_entry((union v6addr *)v6_pod_three, 0, 0, 0,
 			     (__u8 *)mac_three, (__u8 *)mac_two);
-	tail_call_static(ctx, &entry_call_map, FROM_NETDEV);
+	tail_call_static(ctx, entry_call_map, FROM_NETDEV);
 	return TEST_ERROR;
 }
 
@@ -186,7 +186,7 @@ int ipv6_from_netdev_ns_for_node_ip_setup(struct __ctx_buff *ctx)
 	BPF_V6(node_ip, HOST_IP);
 	endpoint_v6_add_entry((union v6addr *)&node_ip, 0, 0, ENDPOINT_F_HOST,
 			     (__u8 *)mac_three, (__u8 *)mac_two);
-	tail_call_static(ctx, &entry_call_map, FROM_NETDEV);
+	tail_call_static(ctx, entry_call_map, FROM_NETDEV);
 	return TEST_ERROR;
 }
```
