### PR TITLE
pkg/k8s: fix node update sync from k8s to kvstore

### LINKED ISSUE #20925: Wireguard connectivity issue between pods on different nodes
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We rollout our kubernetes cluster CNI from cilium version 1.10.11 to version 1.11.7 and started to encounter some network connectivity issue between pods running on different nodes.

Cilium is configured with wireguard enabled. We are using node auto-scaling as well, so nodes might join/disappear from the cluster randomly (spot instances). From our testing kube cluster, it seems that impacted nodes are missing some wireguard peers. A restart of the cilium agent on the impacted nodes is solving the issue.

As an example we have:
* pod client-test-555d4d8447-7859f (IP 100.96.12.242) on node ip-10-0-6-168.eu-west-1.compute.internal
* pod server-test-8xkn9 (IP 100.96.16.21) on node ip-10-0-4-16.eu-west-1.compute.internal

### Client to server ICMP

Here is the result of an ICMP request from client to server:

```
# ping -c 4 100.96.16.21
PING 100.96.16.21 (100.96.16.21) 56(84) bytes of data.
--- 100.96.16.21 ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 3066ms
```

The local cilium agent actually has a wireguard tunnel to the remote node, running the server pod.

```
cilium debuginfo --output json | jq .encryption | grep endpoint
            "endpoint": "10.0.4.205:51871",
            "endpoint": "10.0.6.121:51871",
            "endpoint": "10.0.4.27:51871",
            "endpoint": "10.0.5.111:51871",
            "endpoint": "10.0.6.206:51871",
            "endpoint": "10.0.4.143:51871",
            "endpoint": "10.0.4.16:51871", # node running the server pod
```

### Server to client ICMP

Here is the result of an ICMP request from server to client:

```
# ping 100.96.12.242
PING 100.96.12.242 (100.96.12.242) 56(84) bytes of data.
From 100.96.16.209 icmp_seq=1 Destination Host Unreachable
From 100.96.16.209 icmp_seq=2 Destination Host Unreachable
From 100.96.16.209 icmp_seq=3 Destination Host Unreachable
From 100.96.16.209 icmp_seq=4 Destination Host Unreachable
From 100.96.16.209 icmp_seq=5 Destination Host Unreachable
From 100.96.16.209 icmp_seq=6 Destination Host Unreachable
From 100.96.16.209 icmp_seq=7 Destination Host Unreachable
From 100.96.16.209 icmp_seq=8 Destination Host Unreachable
From 100.96.16.209 icmp_seq=9 Destination Host Unreachable
From 100.96.16.209 icmp_seq=10 Destination Host Unreachable
^C
--- 100.96.12.242 ping statistics ---
10 packets transmitted, 0 received, +10 errors, 100% packet loss, time 9210ms
```

The local cilium agent does not have any up-to-date tunnel to remote node, especially the one running the client pod. I guess this is why it responds with an ICMP destination host unreachable to the pod.

```
cilium debuginfo --output json | jq .encryption | grep "endpoint"
            "endpoint": "10.0.6.206:51871",
            "endpoint": "10.0.4.27:51871",
            "endpoint": "10.0.6.121:51871",
            "endpoint": "10.0.5.111:51871",
            "endpoint": "10.0.4.205:51871",
```

I'm wondering how does the cilium agent is updating wireguard peers, when these peers might join/disappear randomly ? We didn't faced the issue in cilium v1.10.11

### Cilium Version

v1.11.7

### Kernel Version

5.10.130-118

### Kubernetes Version

v1.23.8

### Sysdump

[cilium-sysdump-20220816-175255.zip](https://github.com/cilium/cilium/files/9352675/cilium-sysdump-20220816-175255.zip)

I filtered out sysdump to only include the two impacted nodes from the example in description.

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by aanm**
This commit simplifies the synchronization between the k8s node and
kvstore. The local node state has all the information up to date so
whenever we want to update it to the KVStore, or re-push it to the
CiliumNode CRD, we should use this information.

Fixes: 01cbc595ad48 ("k8s: keep CiliumNode labels synced with Node object")
Signed-off-by: André Martins <andre@cilium.io>

Fixes https://github.com/cilium/cilium/issues/20925

```release-note
Fix Wireguard connectivity issues when using kvstore mode
```

Depends on https://github.com/cilium/cilium/pull/21087

### CODE REVIEW

File: pkg/k8s/watchers/node.go [hunk 1]
```diff
@@ -41,9 +34,9 @@ func (k *K8sWatcher) RegisterNodeSubscriber(s subscriber.Node) {
 
 // The KVStoreNodeUpdater interface is used to provide an abstraction for the
 // nodediscovery.NodeDiscovery object logic used to update a node entry in the
-// KV store.
+// KVStore.
 type KVStoreNodeUpdater interface {
```
Comment (jibi) [inline pkg/k8s/watchers/node.go]: nit: should we rename this given that it's used both for updating the k8s `CiliumNode` and the KVStore entry?

**Review by jibi — APPROVED** [review]
I think I understand the changes:
* thanks to https://github.com/cilium/cilium/pull/21087 whenever there's a node update we end up calling `k.NodeChain.OnUpdateNode()` in `pkg/k8s/watchers/node.go`, which in turn calls `OnUpdateNode()` in `pkg/endpointmanager/host.go`, responsible for setting the new labels in the global state we keep in the `node` package.
* then we call `UpdateLocalNode()`, which is responsible triggering the sync of the local information we have for the node to k8s/the KVStore

As I've already discussed offline with @aanm at some point we should unify step 1 and 2, but that can be a follow up

File: pkg/k8s/watchers/node.go [hunk 2]
```diff
@@ -127,25 +120,24 @@ func (k *K8sWatcher) GetK8sNode(_ context.Context, nodeName string) (*v1.Node, e
...
 	return &ciliumNodeUpdater{
-		k8sWatcher:         k8sWatcher,
 		kvStoreNodeUpdater: kvStoreNodeUpdater,
 	}
 }
 
 func (u *ciliumNodeUpdater) OnAddNode(newNode *v1.Node, swg *lock.StoppableWaitGroup) error {
-	u.updateCiliumNode(u.kvStoreNodeUpdater, newNode)
-
+	// We don't need to run OnAddNode because Cilium will fetch the state from
```
Comment (tklauser) [inline pkg/k8s/watchers/node.go:132]: Could we make the comment a bit more specific and say which component of Cilium will fetch state and populate KV store? I assume this is what's implemented in the operator here: https://github.com/cilium/cilium/blob/dbc538ef02ed34cbc7c401e2336c7ef02cb44409/operator/cmd/cilium_node.go#L52

File: pkg/k8s/watchers/node.go [hunk 3]
```diff
@@ -154,49 +146,12 @@ func (u *ciliumNodeUpdater) OnDeleteNode(*v1.Node, *lock.StoppableWaitGroup) err
...
-				return fmt.Errorf("failed to update CiliumNode labels: %w", err)
-			}
-		}
-
-		return nil
+func (u *ciliumNodeUpdater) updateCiliumNode(node *v1.Node) {
+	if node.Name != nodeTypes.GetName() {
+		// The cilium node updater should only update the information relevant
+		// to itself. It should not update any of the other nodes.
+		panic(fmt.Sprintf("trying to update node %q while we should only run for %q", node.Name, nodeTypes.GetName()))
```
Comment (tklauser) [inline pkg/k8s/watchers/node.go]: I wonder whether we should just log an error here and ignore the update. Or is this really an unrecoverable error which would prevent Cilium from working correctly going forward?

**Review by tklauser — APPROVED** [review]
Two minor questions/comments, otherwise LGTM. Thanks.

File: pkg/k8s/watchers/node.go (hunk 3 above)
Comment (aanm) [reply pkg/k8s/watchers/node.go]: This is a developer's mistake and should never happen. This event handler is only intended for the node where the agent is running. I will change the log files to report an error as BUG and ignore the update as you suggested.

File: pkg/k8s/watchers/node.go (hunk 2 above)
Comment (aanm) [reply pkg/k8s/watchers/node.go:132]: I've updated the comment with the two places where this is used.

File: pkg/k8s/watchers/node.go [hunk 4]
```diff
@@ -127,25 +119,26 @@ func (k *K8sWatcher) GetK8sNode(_ context.Context, nodeName string) (*v1.Node, e
...
 	}
 }
 
 func (u *ciliumNodeUpdater) OnAddNode(newNode *v1.Node, swg *lock.StoppableWaitGroup) error {
-	u.updateCiliumNode(u.kvStoreNodeUpdater, newNode)
-
+	// We don't need to run OnAddNode because Cilium will fetch the state from
+	// k8s upon initialization and will populate the KVStore [1] node with this
+	// information or create a Cilium Node CR [2].
+	// [1] https: // github.com/cilium/cilium/blob/2bea69a54a00f10bec093347900cc66395269154/daemon/cmd/daemon.go#L1102
```
Comment (tklauser) [inline pkg/k8s/watchers/node.go]: Thanks for adding these links!

Minor nit:
```suggestion
	// [1] https://github.com/cilium/cilium/blob/2bea69a54a00f10bec093347900cc66395269154/daemon/cmd/daemon.go#L1102
```

**Comment by aanm** [comment]
Tests were passing, the commit was only fixing a formatting issue.

**Comment by glibsm** [comment]
Unmarking 1.10 backport: `OnUpdateNode` doesn't exist
