### PR TITLE
cilium, socklb: Add a flag for opting into terminating all protos

### LINKED ISSUE #40463: Regression from terminating TCP sockets PR
https://github.com/cilium/cilium/pull/40304 introduced a significant regression in servicechurn scale test, almost x6 more cpu usage

Image

Image

Attached cpu pprof:
[cpu.zip](https://github.com/user-attachments/files/21163495/cpu.zip)

### PR DESCRIPTION
**Pull request by borkmann**
(see commit msg)

Closes: #40463

### CODE REVIEW

File: pkg/loadbalancer/config.go [hunk 1]
```diff
@@ -504,6 +504,7 @@ type ExternalConfig struct {
 	BPFSocketLBHostnsOnly                  bool
 	EnableSocketLB                         bool
 	EnableSocketLBPodConnectionTermination bool
+	EnableSocketLBConnectionTerminationAll bool
```
Comment (marseel) [inline pkg/loadbalancer/config.go]: nit: I guess this should be part of `UserConfig` rather than `DaemonConfig`? Taking into account that we already have `EnableSocketLBPodConnectionTermination`, it may be fine to add it here as well. I don't have strong opinion, just saying :)

**Review by marseel — APPROVED** [review]
lgtm from scalability point of view, thanks!

**Review by ysksuzuki — APPROVED** [review]

File: pkg/loadbalancer/config.go (hunk 1 above)
Comment (borkmann) [reply pkg/loadbalancer/config.go]: ack, makes sense, I'll change it on Mo

Comment (borkmann) [reply pkg/loadbalancer/config.go]: done, much shorter patch, I like it! thanks for the suggestion!

**Comment by jrife** [comment]
> Disable this by default for now until we find optimizations to make this less costly, for example, in-kernel socket iterators.

FYI I'm working on https://github.com/cilium/cilium/pull/38693 which uses BPF socket iterators to do socket termination. I wonder if this will improve performance here.
