### PR TITLE
make Cilium's CNI conf the only one available

### LINKED ISSUE #13152: Cilium not cleaning cni configuration while uninstalling.
While testing Cilium in Azure CNI mode ( without chaining ), It seems like cilium is not cleaning up the `05-cilium.conf` file from the `/etc/cni/net.d` directory, During uninstallation. This is causing Kubelet to generate lots of error like below

`kubelet[3524]: W0911 13:15:36.525325    3524 cni.go:202] Error validating CNI config &{cilium 0.3.1 false [0xc001103120] [123 34 99 110 105 86 101 114 115 105 111 110 34 58 34 48 46 51 46 49 34 44 34 110 97 109 101 34 58 34 99 105 108 105 117 109 34 44 34 112 108 117 103 105 110 115 34 58 91 123 34 99 110 105 86 101 114 115 105 111 110 34 58 34 48 46 51 46 49 34 44 34 101 110 97 98 108 101 45 100 101 98 117 103 34 58 102 97 108 115 101 44 34 110 97 109 101 34 58 34 99 105 108 105 117 109 34 44 34 116 121 112 101 34 58 34 99 105 108 105 117 109 45 99 110 105 34 125 93 125]}: [failed to find plugin "cilium-cni" in path [/opt/cni/bin]]`.

**General Information**

- Cilium version 1.8.3
- Kernel version 1.8.3
- Orchestration system version in use: Kubectl v1.18.0, Azure AKS
- Link to relevant artifacts (policies, deployments scripts, ...)

**How to reproduce the issue**

1.  Use the default instruction for installing cilium in azure cni mode
2. Check the directory containing the config file `/etc/cni/net.d/05-cilium.conf`
3. Remove cilium using helm delete and verify that files are `/etc/cni/net.d/05-cilium.conf` present
4. Furthur error logs can be seen from running `journalctl -fu kubelet`

### LINKED ISSUE #14128: Prevent Kubelet from using a different CNI on Cilium upgrades
The initial implementation of CNI in Kubelet was made by checking for a valid configuration file, `*.conf`, in the configuration directory, which has the default of `/etc/cni/net.d`. This behavior allowed Cilium to be safely upgraded while other CNI configuration files were available as Kubelet would keep retrying Cilium’s configuration file until the Cilium CNI binary was available, where this binary is removed and re-added for each upgrade.

Unfortunately, this behavior has changed and Kubelet now picks the first valid CNI configuration file with a valid CNI binary. In a machine where multiple CNI configuration files are available, this might cause issues during a Cilium upgrade where Kubelet will use a different CNI plugin, for application pods, making those application pods to never be managed by Cilium.

To avoid this issue a proposed solution is to change the file extension of existing (edit: non-Cilium) CNI configuration files from `*.conf` and `*.conflist` to `*.conf.cilium_bak` and `*.conflist.cilium_bak` respectively. These files would only be reverted when the user would want to explicitly uninstall Cilium or when `cilium cleanup` command would be executed in this host. Since Kubelet only checks for the presence of `*.conf` and `*.conflist` it will not consider any other CNI configuration when setting up the application pods.

cc @ti-mo

### PR DESCRIPTION
**Pull request by aanm**
The initial implementation of CNI in Kubelet was made by checking for a valid configuration file, *.conf, in the configuration directory, which has the default of /etc/cni/net.d. This behavior allowed Cilium to be safely upgraded while other CNI configuration files were available as Kubelet would keep retrying Cilium’s configuration file until the Cilium CNI binary was available, since this binary is removed and re-added for each upgrade.

Unfortunately, this behavior has changed and Kubelet now picks the first valid CNI configuration file with a valid CNI binary. In a machine where multiple CNI configuration files are available, this might cause issues during a Cilium upgrade where Kubelet will use a different CNI plugin, for application pods, making those application pods to never be managed by Cilium.

To avoid this issue this commit changes he file extension of existing non-Cilium CNI configuration files from *.conf and *.conflist to *.conf.cilium_bak and *.conflist.cilium_bak respectively. These files will be reverted when the user wants to explicitly uninstall Cilium by performing a cilium cleanup command in the host. Since Kubelet only checks for the presence of *.conf and *.conflist it will not consider any other CNI configuration when setting up the application pods. This new behavior can be reverted by passing `--backup-cni-conf=false` to the postStart exec command in Cilium's DaemonSet.

Tested locally:

```
$ minikube start --network-plugin=cni --memory=4096 && minikube ssh -- sudo mount bpffs -t bpf /sys/fs/bpf

docker@minikube:~$ ls -la /etc/cni/net.d/
total 48
drwxr-xr-x. 1 root root 4096 Nov 26 21:07 .
drwxr-xr-x. 1 root root 4096 Aug 25 22:55 ..
-rw-r--r--. 1 root root  438 Jul 29 11:12 100-crio-bridge.conf
-rw-r--r--. 1 root root   54 Jun 22 18:23 200-loopback.conf
-rw-r--r--. 1 root root  639 May 25  2020 87-podman-bridge.conflist

docker@minikube:~$ ls -la /etc/cni/net.d/
total 52
drwxr-xr-x. 1 root root 4096 Nov 26 21:07 .
drwxr-xr-x. 1 root root 4096 Aug 25 22:55 ..
-rw-r--r--. 1 root root   97 Nov 26 21:07 05-cilium.conf
-rw-r--r--. 1 root root  438 Jul 29 11:12 100-crio-bridge.conf.cilium_bak
-rw-r--r--. 1 root root   54 Jun 22 18:23 200-loopback.conf.cilium_bak
-rw-r--r--. 1 root root  639 May 25  2020 87-podman-bridge.conflist.cilium_bak

docker@minikube:~$ ls -la /etc/cni/net.d/
total 52
drwxr-xr-x. 1 root root 4096 Nov 26 21:07 .
drwxr-xr-x. 1 root root 4096 Aug 25 22:55 ..
-rw-r--r--. 1 root root   97 Nov 26 21:07 05-cilium.conf
-rw-r--r--. 1 root root  438 Jul 29 11:12 100-crio-bridge.conf.cilium_bak
-rw-r--r--. 1 root root   54 Jun 22 18:23 200-loopback.conf.cilium_bak
-rw-r--r--. 1 root root  639 May 25  2020 87-podman-bridge.conflist.cilium_bak

docker@minikube:~$ ls -la /etc/cni/net.d/
total 52
drwxr-xr-x. 1 root root 4096 Nov 26 21:07 .
drwxr-xr-x. 1 root root 4096 Aug 25 22:55 ..
-rw-r--r--. 1 root root  438 Jul 29 11:12 100-crio-bridge.conf
-rw-r--r--. 1 root root   54 Jun 22 18:23 200-loopback.conf
-rw-r--r--. 1 root root  639 May 25  2020 87-podman-bridge.conflist
```

```release-note
Make Cilium the only CNI configuration available in the host to avoid pods from being managed by other CNIs while performing Cilium upgrades.
```

Fixes https://github.com/cilium/cilium/issues/14128
Fixes https://github.com/cilium/cilium/issues/13152

### CODE REVIEW

File: plugins/cilium-cni/cni-install.sh [hunk 1]
```diff
@@ -169,6 +169,15 @@ if [ ! -d $(dirname $CILIUM_CNI_CONF) ]; then
 	mkdir -p $(dirname $CILIUM_CNI_CONF)
 fi
 
+# Make sure only Cilium is used to setup an application pod. See GH-14128.
+find "$(dirname ${CILIUM_CNI_CONF})" \
```
Comment (aanm) [inline plugins/cilium-cni/cni-install.sh]: depth 1

**Comment by aanm** [comment]
test-me-please

File: cilium/cmd/cleanup.go [hunk 2]
```diff
@@ -217,7 +217,7 @@ func (c ciliumCleanup) whatWillBeRemoved() []string {
 		defaults.LibraryPath))
 	toBeRemoved = append(toBeRemoved, fmt.Sprintf("endpoint state in %s",
 		defaults.RuntimePath))
-	toBeRemoved = append(toBeRemoved, fmt.Sprintf("CNI configuration at %s, %s, %s",
+	toBeRemoved = append(toBeRemoved, fmt.Sprintf("CNI configuration at %s, %s, %s, %s",
```
Comment (ti-mo) [inline cilium/cmd/cleanup.go:225]: This change should probably be applied in the previous commit instead.

**Comment by ti-mo** [comment]
Need to run some more manual testing with this tomorrow, but this should be ready to review.
@aanm Could you take another look? I've closed https://github.com/cilium/cilium/pull/14095 in favor of this one.

File: plugins/cilium-cni/cni-install.sh [hunk 3]
```diff
@@ -83,6 +83,23 @@ if [ "${CILIUM_CUSTOM_CNI_CONF}" = "true" ]; then
 	exit 0
 fi
 
+
```
Comment (christarazi) [inline plugins/cilium-cni/cni-install.sh:94]: Seems like this commit can just be squashed with the previous commit.

**Review by christarazi — APPROVED** [review]
LGTM, just one minor fixup

File: plugins/cilium-cni/cni-install.sh [hunk 4]
```diff
@@ -83,6 +84,14 @@ if [ "${CILIUM_CUSTOM_CNI_CONF}" = "true" ]; then
 	exit 0
 fi
 
+# Remove any active Cilium CNI configurations left over from previous installs
+# to make sure the one we're installing later will take effect.
+echo "Removing active Cilium CNI configurations from ${CNI_CONF_DIR}})..."
```
Comment (aanm) [inline plugins/cilium-cni/cni-install.sh:86]: Between this line and line 205 (`mv "${CNI_CONF_NAME}" "${CILIUM_CNI_CONF}"`) kubelet will be unable to create a pod. I know it will retry but ideally we should do `mv "${CNI_CONF_NAME}" "${CILIUM_CNI_CONF}"` first and then perform the deletes of the all confs that are not `${CNI_CONF_NAME}`

**Review by aanm — COMMENTED** [review]
@ti-mo just one small comment here

File: plugins/cilium-cni/cni-install.sh (hunk 3 above)
Comment (ti-mo) [reply plugins/cilium-cni/cni-install.sh:94]: Done!

File: plugins/cilium-cni/cni-install.sh (hunk 4 above)
Comment (ti-mo) [reply plugins/cilium-cni/cni-install.sh:86]: This was done semi-intentionally because:
- this time window should be minimal
- this is during agent prestart, so not sure what Cilium CNI's pod creation behaviour is when the agent is not running yet
- there might be a timeframe where there are multiple Cilium CNI configs in the directory during upgrades, e.g. `05-cilium-cni.conflist` and a newer `05-cilium.conflist`.

I don't see the points above as problematic, it just seems safer to me to put the CNI directory into a clean state and only then install a new config. It also slightly simplifies the code.

Comment (aanm) [reply plugins/cilium-cni/cni-install.sh:86]: Answered inline.

> This was done semi-intentionally because:
> 
> * this time window should be minimal

yeah I know, but it can happen.

> * this is during agent prestart, so not sure what Cilium CNI's pod creation behaviour is when the agent is not running yet

Cilium CNI is smart enough and it will retry to connect to the agent multiple times before returns a failure to kubelet.

> * there might be a timeframe where there are multiple Cilium CNI configs in the directory during upgrades, e.g. `05-cilium-cni.conflist` and a newer `05-cilium.conflist`.
> 

IMO that is fine because in both cases Cilium is the one managing the network for the pod. Even if the 'wrong' CNI configuration is picked, that configuration is from Cilium.

> I don't see the points above as problematic, it just seems safer to me to put the CNI directory into a clean state and only then install a new config. It also slightly simplifies the code.

My main concern is during Cilium agent restarts, if the cilium pod is restarted, there will be a point in time where kubelet will fail hard to create pods because there isn't a single CNI configuration available.

Comment (ti-mo) [reply plugins/cilium-cni/cni-install.sh:86]: > Even if the 'wrong' CNI configuration is picked, that configuration is from Cilium.

True, but one might be a CNI chaining config, and the other might be a native IPAM config.

> if the cilium pod is restarted, there will be a point in time where kubelet will fail hard to create pods because there isn't a single CNI configuration available

IMO failing hard early is preferred over successfully launching a pod in the wrong networking config. The latter could mean  a security vulnerability (although it's a stretch).

**Comment by aanm** [comment]
test-me-please

**Comment by ti-mo** [comment]
Tested this extensively on AKS yesterday and today, and everything is working as expected. Switching back and forth between CNI chaining (with custom config from a ConfigMap) and native CNI also works perfectly.

**Comment by ti-mo** [comment]
Removed backport labels as this can be regarded a breaking change to users of ie. https://github.com/cni-genie/CNI-Genie.
Added upgrade documentation to bring this to our users' attention that this is enabled by default.

File: cilium/cmd/cleanup.go [hunk 5]
```diff
@@ -320,14 +328,34 @@ func confirmCleanup() bool {
...
 	if os.IsNotExist(err) {
 		return nil
 	}
 	return err
 }
 
+// revertCNIBackup removes the ".cilium_bak" suffix from all files in cniPath,
+// reverting them back to their original filenames.
+func revertCNIBackup() error {
+	return filepath.Walk(cniPath,
```
Comment (aanm) [inline cilium/cmd/cleanup.go:343]: Just a small note here, `filepath.Walk` walks all directories recursive, not only the "top-level" one. It is likely to not affect anything but just a FYI.

**Review by ti-mo — APPROVED** [review]

**Review by christarazi — APPROVED** [review]
:rocket:

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-gke

**Comment by aanm** [comment]
test-4.9

File: plugins/cilium-cni/cni-install.sh [hunk 6]
```diff
@@ -72,8 +79,42 @@ fi
...
+    -name '*.conflist' \
+  \) \
+  -not -name "${CNI_CONF_NAME}" \
+  -delete
+
+# Rename all remaining CNI configurations to *.cilium_bak. This ensures only
+# Cilium's CNI plugin will remain active. This makes sure Pods are not
+# scheduled by another CNI when the Cilium agent is down during upgrades
+# or restarts. See GH-14128 and related issues for more context.
+if [ "${CNI_EXCLUSIVE}" != "false" ]; then
```
Comment (joestringer) [inline plugins/cilium-cni/cni-install.sh:99]: Was the intent here to force users to opt out of exclusive control over the CNI?

I noticed that if the user fails to update their YAML files during the upgrade to this version, `CNI_EXCLUSIVE` will be undefined, and therefore does not match `false` and automatically takes this path.

**Comment by joestringer** [comment]
Just given that this modifies behaviour around management of the CNI configuration file, I've added upgrade-impact label. Idea being that if someone does end up hitting upgrade issues, we can list issues with `upgrade-impact` and decide whether this PR could play a role or whether it's one of the other `upgrade-impact`-labelled PRs.

File: plugins/cilium-cni/cni-install.sh (hunk 6 above)
Comment (ti-mo) [reply plugins/cilium-cni/cni-install.sh:99]: > Was the intent here to force users to opt out of exclusive control over the CNI?

Correct, it's opt-out since it can cause pods to be scheduled by other CNIs during Cilium upgrade/downtime. This is a potential security issue since network policies won't be enforced with those other CNIs. This has been documented in the upgrade notes. We didn't feel like this kind of change was appropriate to backport given its magnitude.

Didn't know about the `upgrade-impact` label, thanks!
