### PR TITLE
test: Update FQDN related domain and IP

### LINKED ISSUE #38752: CI: Conformance Ginkgo: E2E Test fails because host/IP cannot be reached
## CI failure

https://github.com/cilium/cilium/actions/runs/14260796244/job/39977290421

The endpoint for `vagrant-cache.ci.cilium.io` has changed. The tests related to this endpoint are failing.
https://github.com/search?q=repo%3Acilium%2Fcilium+vagrant-cache.ci.cilium.io&type=code

### PR DESCRIPTION
**Pull request by sayboras**
The FQDN tests use both the host and the IP to run curl. This change updates the endpoint used in this test.

Fixes: #38752

### CODE REVIEW

**Review by auriaave — APPROVED** [review]
LGTM - it updates the endpoints to reachable endpoints that match (host/IP).

**Review by michi-covalent — APPROVED** [review]

**Review by kaworu — APPROVED** [review]

File: test/k8s/fqdn.go [hunk 1]
```diff
@@ -27,8 +27,8 @@ var _ = SkipDescribeIf(helpers.RunsOn54Kernel, "K8sAgentFQDNTest", func() {
 		appPods map[string]string
 
 		// The IPs are updated in BeforeAll
-		worldTarget          = "vagrant-cache.ci.cilium.io"
-		worldTargetIP        = "147.75.38.95"
```
Comment (bimmlerd) [inline test/k8s/fqdn.go:31]: is this IP stable?

**Review by bimmlerd — APPROVED** [review]
LGTM to unblock CI

File: test/k8s/fqdn.go (hunk 1 above)
Comment (sayboras) [reply test/k8s/fqdn.go:31]: yes, it is.

**Review by viktor-kurchenko — APPROVED** [review]
