### PR TITLE
fqdn: Fix missing IsNil checks in unit tests

### LINKED ISSUE #11943: CI: RuntimePrivilegedUnitTests: Panic in DNSProxyTestSuite
https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/652/testReport/(root)/Suite-runtime/RuntimePrivilegedUnitTests_Run_Tests/

```
... Panic: runtime error: invalid memory address or nil pointer dereference (PC=0x4363F5)
 
/usr/local/go/src/runtime/panic.go:969
  in gopanic
/usr/local/go/src/runtime/panic.go:212
  in panicmem
/usr/local/go/src/runtime/signal_unix.go:695
  in sigpanic
proxy_test.go:329
  in DNSProxyTestSuite.TestRejectNonMatchingRefusedResponse
/usr/local/go/src/reflect/value.go:321
  in Value.Call
/usr/local/go/src/runtime/asm_amd64.s:1373
  in goexit
PANIC: proxy_test.go:306: DNSProxyTestSuite.TestRejectNonMatchingRefusedResponse
```

[29c4edf5_RuntimePrivilegedUnitTests_Run_Tests.zip](https://github.com/cilium/cilium/files/4744109/29c4edf5_RuntimePrivilegedUnitTests_Run_Tests.zip)

### PR DESCRIPTION
**Pull request by pchaigno**
Fixes: #11943
Fixes: #9587

The same error is also present in v1.7 and v1.6 (#9587 was backported), but I'm not sure it's worth backporting to either.

### CODE REVIEW

**Comment by pchaigno** [comment]
test-me-please

**Review by tklauser — APPROVED** [review]

**Comment by pchaigno** [comment]
test-focus RuntimePrivilegedUnitTests

**Comment by pchaigno** [comment]
`Runtime-4.9` passed so marking as ready to merge.

File: pkg/fqdn/dnsproxy/proxy_test.go [hunk 1]
```diff
@@ -325,12 +325,14 @@ func (s *DNSProxyTestSuite) TestRejectNonMatchingRefusedResponse(c *C) {
 
 	// reject a query with NXDomain
 	s.proxy.SetRejectReply(option.FQDNProxyDenyWithNameError)
-	response, _, _ := s.dnsTCPClient.Exchange(request, s.proxy.TCPServer.Listener.Addr().String())
+	response, _, err := s.dnsTCPClient.Exchange(request, s.proxy.TCPServer.Listener.Addr().String())
+	c.Assert(err, IsNil, Commentf("DNS request from test client failed when it should succeed"))
```
Comment (christarazi) [inline pkg/fqdn/dnsproxy/proxy_test.go:329]: TIL: I didn't know you can pass `Commentf` to customize the assertion failure :)
