### PR TITLE
Fix CIDR to World Entity Conversion Bug

### LINKED ISSUE #22610: NetworkPolicy and CiliumNetworkPolicy allow IPv6 egress if 0.0.0.0/0 is allowed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When applying a `NetworkPolicy` or a `CiliumNetworkPolicy` which only allows cluster-external traffic to `0.0.0.0/0`, Cilium will continue to allow traffic to cluster-external IPv6 targets.
This behaviour is not present for subnets of `0.0.0.0/0`, like `0.0.0.0/1` or in case an `except` rule is present.

Cilium seems to treat `0.0.0.0/0` differently from other prefixes.

`NetworkPolicy` allowing IPv6 traffic:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ipv4-only
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
    - to:
        - podSelector: {}
    - to:
        - namespaceSelector: {}
```

Same `NetworkPolicy` with `except` rule, blocking IPv6 traffic:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ipv4-except
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 0.0.0.0/8
    - to:
        - podSelector: {}
    - to:
        - namespaceSelector: {}
```

Another `NetworkPolicy` not using `0.0.0.0/0`, blocking IPv6 traffic

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ipv4-only-subnet
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/1
    - to:
        - podSelector: {}
    - to:
        - namespaceSelector: {}
```

`CiliumNetworkPolicy` allowing IPv6 traffic:

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: ipv4-only
spec:
  endpointSelector: {}
  egress:
    - toCIDRSet:
        - cidr: 0.0.0.0/0
    - toEndpoints:
        - {}
    - toEntities:
        - cluster
```

Same `CiliumNetworkPolicy` with `except` rule, blocking IPv6 traffic:

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: ipv4-except
spec:
  endpointSelector: {}
  egress:
    - toCIDRSet:
        - cidr: 0.0.0.0/0
          except:
            - 0.0.0.0/8
    - toEndpoints:
        - {}
    - toEntities:
        - cluster
```

### Expected bahaviour

I would expect Cilium to treat all IPv4 prefixes the same and not to treat `0.0.0.0/0` differently to allow IPv6 communication as well.

### Cilium Version

Client: 1.12.4 6eaecaf 2022-11-16T05:45:01+00:00 go version go1.18.8 linux/amd64
Daemon: 1.12.4 6eaecaf 2022-11-16T05:45:01+00:00 go version go1.18.8 linux/amd64

### Kernel Version

Linux k8s0-controleplane0 5.19.0-2-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1 (2022-09-24) x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:28:30Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:49:09Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

`cilium status`:
```
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.25 (v1.25.3) [linux/amd64]
Kubernetes APIs:         ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    Strict    [internet 192.0.2.1 2001:db8::1 (Direct Routing)]
Host firewall:           Enabled   [internet]
CNI Chaining:            none
Cilium:                  Ok   1.12.4 (v1.12.4-6eaecaf)
NodeMonitor:             Listening for events on 4 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok   
IPAM:                    IPv4: 4/254 allocated from 10.0.2.0/24, IPv6: 4/65534 allocated from 2001:db8:1f::2:0/112
BandwidthManager:        EDT with BPF [BBR] [internet]
Host Routing:            BPF
Masquerading:            BPF   [internet]   10.0.0.0/8 [IPv4: Enabled, IPv6: Disabled]
Controller Status:       30/30 healthy
Proxy Status:            OK, ip 10.0.2.231, 0 redirects active on ports 10000-20000
Global Identity Range:   min 256, max 65535
Hubble:                  Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 45.90   Metrics: Ok
Encryption:              Disabled
Cluster health:          3/3 reachable   (2022-12-08T00:45:43Z)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by nathanjsweet**
Previously if either the "0.0.0.0/0" CIDR (hereafter "world-ipv4")
or a world-ipv6 (i.e. "::/0") CIDR was present the selector creation logic
for CIDRs would also add the "reserved:world" entity to the
selector labels generated by the CIDR for the sake of the policy engine.
    
This does not work when Cilium is dual-stack mode as the "reserved:world"
entity covers both IPv4 and IPv6, so both CIDRs should be present before such
an addition to the policy engine logic is made. Moreover, dual-stack mode lacks
any mechanism to distinguish world-ipv4 and world-ipv6 from one another. 
This bug has prevented the possibility of managing world-ipv4 and world-ipv6
separately from one another in network policies.
    
Separate identities (and labels, etc) for world-ipv4 and world-ipv6 now exist
so they can be distinguished.

Signed-off-by: Nate Sweet <nathanjsweet@pm.me>

Fixes: #22610 
```release-note
bug: In dual-stack mode (both IPv4 and IPv6 are enabled), Cilium incorrectly converted CIDRs that covered all possible addresses for an IP Family (e.g. 0.0.0.0/0) to the "reserved:world" entity. Both IP families must be completely covered for "reserved:world" to apply. This resulted in dual-stack mode network policies that could not distinguish between world IPv4 and IPv6 traffic, treating them as one entity instead.
```

### CODE REVIEW

**Review by aanm — APPROVED** [review]
LGTM @nathanjsweet just a heads-up that since we have branched v1.13, this PR will not be part of the 1.13 unless it is set with the needs-backport/1.13 label.

**Review by joestringer — APPROVED** [review]
Thanks for the fix! LGTM.

**Comment by joestringer** [comment]
@nathanjsweet it looks like the [Cilium Datapath](https://github.com/cilium/cilium/actions/runs/3692343304) tests are failing consistently on a CIDR deny policy issue. Do you think that this may be related to the PR content? I don't see any similar failures in other [recent failures for the workflow](https://github.com/cilium/cilium/actions/workflows/conformance-datapath.yaml?query=is%3Afailure).

**Comment by pchaigno** [comment]
> @nathanjsweet it looks like the [Cilium Datapath](https://github.com/cilium/cilium/actions/runs/3692343304) tests are failing consistently on a CIDR deny policy issue. Do you think that this may be related to the PR content? I don't see any similar failures in other [recent failures for the workflow](https://github.com/cilium/cilium/actions/workflows/conformance-datapath.yaml?query=is%3Afailure).

I checked one of the failure and it does include a policy with the 0.0.0.0/0 CIDR. Since all tests are failing with the exact same test cases, I assume they all have the same policy. Seems fairly likely to be related to the changes here.

File: pkg/policy/api/cidr.go [hunk 1]
```diff
@@ -75,19 +67,24 @@ func (s CIDRSlice) GetAsEndpointSelectors() EndpointSelectorSlice {
...
+		if cidr == ipv6All {
+			hasIPv6AllBeenAdded = true
 		}
 		lbl, err := cidrpkg.IPStringToLabel(string(cidr))
 		if err == nil {
 			slice = append(slice, NewESFromLabels(lbl))
 		}
 		// TODO: Log the error?
 	}
+	if hasIPv4AllBeenAdded && hasIPv6AllBeenAdded {
```
Comment (pchaigno) [inline pkg/policy/api/cidr.go]: Couldn't we take into account whether we are running an IPv4-only or IPv6-only cluster? As Joe mentioned offline, this fix may have a big impact on the policy map size because that one entry will now be converted into one entry per existing CIDR IIUC. So if we can limit its effect to dual-stack clusters, that would probably be best.

File: pkg/policy/api/cidr.go [hunk 2]
```diff
@@ -75,19 +68,31 @@ func (s CIDRSlice) GetAsEndpointSelectors() EndpointSelectorSlice {
...
+			hasIPv6AllBeenAdded = true
 		}
 		lbl, err := cidrpkg.IPStringToLabel(string(cidr))
 		if err == nil {
 			slice = append(slice, NewESFromLabels(lbl))
 		}
 		// TODO: Log the error?
 	}
+	// We want to add the world selector whenever possible as it limits the growth of the
+	// ipcache.
```
Comment (joestringer) [inline pkg/policy/api/cidr.go]: Now I'm second-guessing whether there's really an optimization to make here or not. The thinking I had when I raised the question was whether the "allow to world" could become an "allow all" match, and hence be encoded with one entry in the datapath. But in reality we can only inject that match if the policy says "toEntities: all", ie matching also identities within the cluster. Maybe the best that this will achieve is just to shortcut some of the selection logic for the case where it's single stack and the broadest CIDR is allowed by a policy.

I'm not sure this will actually impact either ipcache or policymaps size at this point.

Comment (joestringer) [reply pkg/policy/api/cidr.go]: (The logic is probably fine either way, the latest version here is a little more complicated but still correct. It's just the comment that I think may not be accurate).

**Comment by joestringer** [comment]
@nathanjsweet were you able to reproduce / track down the datapath failure?

**Comment by nathanjsweet** [comment]
@joestringer no, not yet. I was waiting to see if this fixed it.

File: pkg/policy/api/cidr.go (hunk 2 above)
Comment (pchaigno) [reply pkg/policy/api/cidr.go]: Ah, yes. That's not going to impact the policy map size because we *append* the world entity to the CIDR slice.

But then, why do we even do that in the first place? Doesn't the 0.0.0.0/0 CIDR identity already match all traffic?

(I'm a bit worried that, if we don't do that to optimize, then maybe it's nothing we can't just skip doing. And maybe it explains the previous CI failure in ConformanceDatapath.)

Comment (joestringer) [reply pkg/policy/api/cidr.go]: yeah I'd expect `0.0.0.0/0` CIDR identity to match all (IPv4) traffic already. Maybe we didn't need the extra world selector insertion after all, we just never revisited this. I think it's important that the _identities_ we create have the `reserved:world` label to make sure that any `toEntities: world` policy matches those identities, but I don't think we need to inject the `reserved:world` labelSelector into the _policy parsing_ piece for the selectors that then select the identities.

**Review by pchaigno — DISMISSED** [review]
Blocking on above conversation with Joe and CI failure. I suspect the two are related :slightly_smiling_face:

**Comment by nathanjsweet** [comment]
I meant to update this PR, but never did. This PR is also blocked on https://github.com/cilium/cilium/pull/22966 as it significantly alters the policy engine code. Making this change should happen after that PR is merged.

**Comment by nathanjsweet** [comment]
All of the kernel and runtime tests appear to be `git pull` timeouts. The gateway API conformance test is the result of cilium not coming up. The multi-cluster test is reliably producing a failure for `allow-all-except-world`, which would appear to be related to this change (although not really, as the rule for the test does not use CIDRs at all), however, I cannot reproduce the failure locally.

**Comment by nathanjsweet** [comment]
/test-1.25-4.19

**Comment by nathanjsweet** [comment]
"multi-cluster" is now passing with a simple rebase.

**Comment by nathanjsweet** [comment]
All tests have technically passed.

**Comment by pchaigno** [comment]
I'm unsure why the Cilium Datapath workflow is marked as passing because it completely failed: https://github.com/cilium/cilium/actions/runs/4347773966.

**Comment by nathanjsweet** [comment]
[This PR](https://github.com/cilium/cilium-cli/pull/1447) in cilium-cli needs to be merged and updated in CI (probably for backport CI as well, as we want to backport this fix). When this is done these tests will pass.

**Review by joestringer — COMMENTED** [review]
Could you add an upgrade guide note that a CIDR match for `0.0.0.0/0` no longer allows the CIDR `::/0` for IPv6 traffic?

**Comment by nathanjsweet** [comment]
/test-1.27-net-next

**Comment by kaworu** [comment]
deferring review to @chancez as I don't have enough context on metrics to evaluate the Hubble changes :pray:

File: pkg/hubble/metrics/flows-to-world/handler.go [hunk 3]
```diff
@@ -53,7 +53,10 @@ func (h *flowsToWorldHandler) Init(registry *prometheus.Registry, options api.Op
 		Name:      "flows_to_world_total",
 		Help:      "Total number of flows to reserved:world",
 	}, labels)
-	h.worldLabel = fmt.Sprintf("%s:%s", pkglabels.LabelSourceReserved, pkglabels.IDNameWorld)
+	h.worldLabels = make(map[string]struct{})
```
Comment (chancez) [inline pkg/hubble/metrics/flows-to-world/handler.go]: Any reason to use a map over something simpler like a switch statement? Also, perhaps we should move `isReservedWorld` into `pkg/identity/numericidentity.go`? It doesn't seem like it needs to be a method, and checking if something is "world" seems like something we should be able to reuse.

Comment (nathanjsweet) [reply pkg/hubble/metrics/flows-to-world/handler.go]: I didn't want to modify this logic too much. I don't know why this `worldLabels` solution was chosen, perhaps for no particular reason.  If there is another compelling reason to modify this PR then I will try to refactor this logic.

Comment (chancez) [reply pkg/hubble/metrics/flows-to-world/handler.go]: Gotcha. Then maybe we can just move these labels to 3 global `var` and use a switch/if instead of a map? I think that aligns more closely with the previous logic, and avoids the map allocation.

File: pkg/labels/labels.go [hunk 4]
```diff
@@ -542,10 +556,12 @@ func (l Labels) IsReserved() bool {
...
-func (l Labels) Has(label Label) bool {
-	for _, lbl := range l {
-		if lbl.matches(&label) {
-			return true
+func (l Labels) Has(args ...Label) bool {
+	for _, label := range args {
+		for _, lbl := range l {
+			if lbl.matches(&label) {
+				return true
+			}
```
Comment (aanm) [inline pkg/labels/labels.go]: I don't understand this change and why it's necessary. Can you clarify it? Thank you

**Review by aanm — CHANGES_REQUESTED** [review]

File: pkg/labels/labels.go (hunk 4 above)
Comment (nathanjsweet) [reply pkg/labels/labels.go]: It gets used [here](https://github.com/cilium/cilium/pull/22625/files#diff-bb1165de1a65911d59ac7f9a002aa9f1e25c30e073547adec11b174a174fdca6R431).

**Comment by nathanjsweet** [comment]
[Upgrade documentation PR](https://github.com/cilium/cilium/pull/25204).

File: pkg/labels/labels.go (hunk 4 above)
Comment (nathanjsweet) [reply pkg/labels/labels.go]: I suppose I could just or together the `Has` invocations.

**Comment by nathanjsweet** [comment]
All tests (except K8s 1.27, which is failing for its own reasons) are passing.  I'm going to address the current requests and circulate this PR one last time, but it is ready to go.

**Review by chancez — APPROVED** [review]
LGTM

**Review by aanm — APPROVED** [review]

**Review by joestringer — APPROVED** [review]
This came out really tidy, nice work.

**Review by christarazi — APPROVED** [review]

**Comment by nathanjsweet** [comment]
Per [this comment](https://github.com/cilium/cilium/pull/22625#issuecomment-1536644683), this PR already passed CI. The subsequent changes that were made addressed smaller concerns that are not reflected in any of the CI flakes that occurred. Marking as ready-to-merge.

**Comment by aditighag** [comment]
Hey @nathanjsweet There are 3 test failures for mandatory CI test jobs, but your comment only addresses on of them. Can you check the other 2 failures, and drop a note around why it's okay to ignore those failures? Please also link issues if these are flakes. Thanks!

**Comment by nathanjsweet** [comment]
/test-1.26-net-next

**Review by gandro — APPROVED** [review]
Thanks a lot for tackling this! My code owners look good to me. We should probably document this in the upgrade notes too.

**Comment by nathanjsweet** [comment]
/test-1.26-net-next

**Comment by nathanjsweet** [comment]
/test-1.26-net-next

**Comment by christarazi** [comment]
While reviewing https://github.com/cilium/cilium/pull/25601/commits/7afe0af4900f08f50c22ac5dabaee6d856e2d0d9, I realized that we may need to check for all instances of `WORLD_ID` in the datapath and also check for the newly added world identities from this PR.

cc @pchaigno

**Comment by nathanjsweet** [comment]
/test-1.26-net-next

**Review by christarazi — CHANGES_REQUESTED** [review]
I think we need to block on my previous [comment](https://github.com/cilium/cilium/pull/22625#issuecomment-1560234953) until we have datapath experts chime in and says it's fine.

File: bpf/node_config.h [hunk 5]
```diff
@@ -47,6 +47,13 @@ DEFINE_IPV6(HOST_IP, 0xbe, 0xef, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0xa, 0x
 
 #define HOST_ID 1
 #define WORLD_ID 2
+#if defined ENABLE_IPV4 && defined ENABLE_IPV6
+# define WORLD_IPV4_ID 9
+# define WORLD_IPV6_ID 10
+#else
+# define WORLD_IPV4_ID 2
+# define WORLD_IPV6_ID 2
+#endif
```
Comment (christarazi) [inline bpf/node_config.h:58]: Nice :+1:

**Comment by nathanjsweet** [comment]
I need to confirm that this fixes a corner case (it should).

File: bpf/lib/nodeport.h [hunk 6]
```diff
@@ -304,7 +304,7 @@ static __always_inline int encap_geneve_dsr_opt6(struct __ctx_buff *ctx,
 						IPV4_DIRECT_ROUTING,
 						src_port,
 						tunnel_endpoint,
-						WORLD_ID,
+						WORLD_IPV4_ID,
```
Comment (lmb) [inline bpf/lib/nodeport.h]: To be on the safe side: the function seems to be dealing with v6, but here we want the v4 id?

**Review by lmb — APPROVED** [review]

File: bpf/lib/nodeport.h (hunk 6 above)
Comment (nathanjsweet) [reply bpf/lib/nodeport.h]: Good catch. I double-checked all the other references to `WORLD_*` in this PR. They are all correct. I think this was a rebase error (the PR modifies high-commit files, so there have been numerous rebases).

**Comment by christarazi** [comment]
/test-1.26-net-next

**Review by pchaigno — APPROVED** [review]
IIUC, when in dual-stack mode and fully upgraded, the datapath should not have any reference to `WORLD_ID` anymore. Does that mean we can remove the `WORLD_ID` entry from the policy map for entity world in v1.15?

In dual-stack mode, there is one reference to `WORLD_ID` left at the beginning of `handle_netdev`, in the `send_drop_notify` call.

Regarding the upgrade impact, I've seen https://github.com/cilium/cilium/pull/25204/files. For dual-stack clusters using the `world` entity in policies, I would expect packet drops or policy bypasses if the ipcache catch-all entry is updated (from 0.0.0.0/0=>2 to 0.0.0.0/0=>9) before the bpf_lxc programs and their policy maps.

How was the upgrade tested? Were such policies loaded? @joestringer Do you know how the ipcache is updated in such situations?

Regarding downgrade, couldn't we avoid the connectivity breakage with a patch in v1.13?

Policy changes with upgrade impacts are very tricky. Nice work driving this through!

**Comment by christarazi** [comment]
Speaking of 

> We felt that documenting the potential connection issue on downgrade was good enough.

I don't see the PR adding any docs. Did you plan to do that as a followup or in this PR?

**Comment by nathanjsweet** [comment]
> I don't see the PR adding any docs. Did you plan to do that as a followup or in this PR?

@christarazi It got lost in the GitHub UI comment collapse. It needs to be rebased, but [this is it](https://github.com/cilium/cilium/pull/25204).

**Review by christarazi — APPROVED** [review]

File: bpf/TAGS
Comment (asauber) [inline bpf/TAGS:1]: was this tags file committed intentionally?

Comment (nathanjsweet) [reply bpf/TAGS:1]: Yeah.

**Review by asauber — APPROVED** [review]

**Comment by nathanjsweet** [comment]
sig-agent and proxy are covered by the current reviewers. Marking ready-to-merge.

File: pkg/policy/l4.go [hunk 7]
```diff
@@ -583,6 +583,19 @@ func (l4Filter *L4Filter) toMapState(p *EndpointPolicy, identities Identities, f
 			keyToAdd.Identity = id.Uint32()
 			if entryCb(keyToAdd, &entry) {
 				p.PolicyMapState.denyPreferredInsertWithChanges(keyToAdd, entry, identities, features, changes)
+				// If Cilium is in dual-stack mode then the "World" identity
+				// needs to be split into two identities to represent World
+				// IPv6 and IPv4 traffic distinctly from one another.
+				if id == identity.ReservedIdentityWorld && option.Config.IsDualStack() {
```
Comment (joestringer) [inline pkg/policy/l4.go:589]: Why doesn't `cs.GetSelections()` already select both of the world identities if world was selected?

File: bpf/node_config.h [hunk 8]
```diff
@@ -49,6 +49,13 @@ DEFINE_IPV6(HOST_IP, 0xbe, 0xef, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0xa, 0x
 
 #define HOST_ID 1
 #define WORLD_ID 2
```
Comment (joestringer) [inline bpf/node_config.h:51]: Should we drop WORLD_ID now to ensure that all code respects the protocol-specific identities?

Comment (joestringer) [reply bpf/node_config.h:51]: Ah I guess the idea is that even in dual-stack the WORLD_ID handles traffic that isn't IPv4 or IPv6.

My general concern here is that new code might naively continue to use `WORLD_ID` when it should actually use `WORLD_ID_IPV4`/v6 and this could introduce weird bugs. Would it make sense to rename `WORLD_ID` to `WORLD_ID_NO_PROTO` with a comment describing to datapath folks how it should only be used for traffic handling when the traffic is not IPv4/IPv6?

File: pkg/datapath/linux/config/config.go [hunk 9]
```diff
@@ -1014,6 +1022,8 @@ func (h *HeaderfileWriter) writeStaticData(fw io.Writer, e datapath.EndpointConf
 
 	secID := e.GetIdentityLocked().Uint32()
 	fmt.Fprint(fw, defineUint32("SECLABEL", secID))
+	fmt.Fprint(fw, defineUint32("SECLABEL_IPV4", secID))
+	fmt.Fprint(fw, defineUint32("SECLABEL_IPV6", secID))
```
Comment (joestringer) [inline pkg/datapath/linux/config/config.go:1034]: Why is this necessary?

I was under the impression that SECLABEL is always the endpoint's security identity, which should not change depending on the protocol. Given that this code is serializing it exactly the same as `SECLABEL`, what's the difference to the datapath handling?

File: pkg/policy/api/selector.go [hunk 10]
```diff
@@ -234,6 +234,8 @@ var (
 		labels.IDNameHost:       newReservedEndpointSelector(labels.IDNameHost),
 		labels.IDNameRemoteNode: newReservedEndpointSelector(labels.IDNameRemoteNode),
 		labels.IDNameWorld:      newReservedEndpointSelector(labels.IDNameWorld),
+		labels.IDNameWorldIPv4:  newReservedEndpointSelector(labels.IDNameWorldIPv4),
+		labels.IDNameWorldIPv6:  newReservedEndpointSelector(labels.IDNameWorldIPv6),
```
Comment (joestringer) [inline pkg/policy/api/selector.go:238]: Shouldn't the world reserved selector also select IPv4 and IPv6 world labels now?

The issue IIRC is that a `0.0.0.0/0` CIDR policy was implicitly translated into a world selector, but it should really be translated to world-ipv4 selector. However, if a user actually adds `ToEntities: - world` then that should select both IPv4 and IPv6 destinations, no?

Comment (joestringer) [reply pkg/policy/api/selector.go:238]: I guess the answer to this question depends on whether the new reserved identities are declared with the world label in addition to the world-$proto or not.

Comment (joestringer) [reply pkg/policy/api/selector.go:238]: Ah I see in `pkg/identity/numericidentity.go` the proto-specific world identities don't have the `reserved:world` label in them.

File: bpf/lib/identity.h [hunk 11]
```diff
@@ -137,7 +185,18 @@ static __always_inline __u32 inherit_identity_from_host(struct __ctx_buff *ctx,
...
 	} else {
+#if defined ENABLE_IPV4 && defined ENABLE_IPV6
+		__u16 proto = ctx_get_protocol(ctx);
+
+		if (proto == bpf_htons(ETH_P_IP))
+			*identity = WORLD_IPV4_ID;
+		else if (proto == bpf_htons(ETH_P_IPV6))
+			*identity = WORLD_IPV6_ID;
+		else
+			*identity = WORLD_ID;
```
Comment (joestringer) [inline bpf/lib/identity.h:196]: nit: We could probably factor this into a function to share between here and `bpf_host.c`, like `world_identity(proto)`.

File: pkg/policy/l4.go (hunk 7 above)
Comment (joestringer) [reply pkg/policy/l4.go:589]: ^ Answer is that the `toEntities: - world` selector doesn't select the world-ipv4 / world-ipv6 identities currently, see my previous comments above. I'd argue that we should just put those labels into the world selector, then this code doesn't need to be handled as a special case here in `toMapState()`.

File: pkg/policy/api/selector.go (hunk 10 above)
Comment (joestringer) [reply pkg/policy/api/selector.go:238]: (If we do change this, it looks like it needs to happen here and in `entity.go`.)

**Review by joestringer — COMMENTED** [review]
I re-reviewed for sig-agent and while I was at it, looked back over the whole PR. I'm not sure I understand why `SECLABEL` needs to be split by protocol, we can discuss in the thread.

Other than that there's just a couple of potential minor cleanups like if we make the world selector select the new world-ipv4 / world-ipv6 identities then we can remove a special case in `toMapState()`. I also saw a small piece of reusable code in the datapath that could potentially be defined once and reused.

File: pkg/policy/api/selector.go (hunk 10 above)
Comment (nathanjsweet) [reply pkg/policy/api/selector.go:238]: Making those selectable is out-of-scope for this PR. That's something we can certainly explore in the future.

File: pkg/policy/l4.go (hunk 7 above)
Comment (nathanjsweet) [reply pkg/policy/l4.go:589]: I prefer to do that in another PR. Making these labels selectable **could** open up a can of worms.

File: bpf/node_config.h (hunk 8 above)
Comment (nathanjsweet) [reply bpf/node_config.h:51]: We need to have a broader conversation about this with datapath folks. I would categorize this as a possible next step, but it changes the UX of the policy engine. We should do that in another PR.

File: pkg/policy/l4.go (hunk 7 above)
Comment (joestringer) [reply pkg/policy/l4.go:589]: Please do follow up. What concerns me is that if we have to place logic like this here, then there could be other places in the policy engine where we're handling world identity and this logic is missing. Embedding the selection into the selectors seems like a more comprehensive way to solve this issue without having to add this extra logic here.

File: pkg/policy/api/selector.go (hunk 10 above)
Comment (joestringer) [reply pkg/policy/api/selector.go:238]: (same thread as https://github.com/cilium/cilium/pull/22625#discussion_r1293797898, resolving per that comment)

File: pkg/datapath/linux/config/config.go (hunk 9 above)
Comment (nathanjsweet) [reply pkg/datapath/linux/config/config.go:1034]: `SECLABEL_IPV4` and `SECLABEL_IPV6` are used in most cases in the `/bpf` code now so they have to be defined, even when they are not "relevant". Cases where they are relevant are the "bpf_host.c", "bpf_lxc.c", and "bpf_xdp.c" programs, where `SECLABEL` is compiled into the program as `WORLD_ID` (see `loader/base.go` as an example). In dual-stack mode this needs to be on a per IP-version basis.

File: bpf/node_config.h (hunk 8 above)
Comment (joestringer) [reply bpf/node_config.h:51]: Why does it change the UX of policy engine? It seems like this PR already splits world into three identities depending on L3 protocol, so if this has any repercussions then I think that's important to raise & engage with, since folks will need to develop future datapath changes based on that understanding.

(I didn't see anything particularly concerning in this PR and I don't think that this needs to block merging this bugfix, but I do want to make sure this discussion happens with datapath folks).

File: bpf/bpf_overlay.c [hunk 12]
```diff
@@ -487,8 +487,8 @@ int tail_handle_arp(struct __ctx_buff *ctx)
 		return send_drop_notify_error(ctx, 0, ret, CTX_ACT_DROP, METRIC_EGRESS);
 	if (info->tunnel_endpoint) {
 		ret = __encap_and_redirect_with_nodeid(ctx, 0, info->tunnel_endpoint,
-						       LOCAL_NODE_ID, WORLD_ID,
-						       WORLD_ID, &trace);
+						       LOCAL_NODE_ID, WORLD_IPV4_ID,
+						       WORLD_IPV4_ID, &trace);
```
Comment (joestringer) [inline bpf/bpf_overlay.c:496]: Hmm, setting the VNI field in the packet to `WORLD_IPV4_ID` could potentially cause confusion for other agents in the cluster when transmitting these packets, until those peer agents have also upgraded to a version that understands `WORLD_IPV4_ID`. How is this code exercised?

File: pkg/policy/l4.go (hunk 7 above)
Comment (nathanjsweet) [reply pkg/policy/l4.go:589]: Done: https://github.com/cilium/cilium/issues/27494

File: pkg/datapath/linux/config/config.go (hunk 9 above)
Comment (joestringer) [reply pkg/datapath/linux/config/config.go:1034]: I see. I'm not sure I logically follow how SECLABEL is now used in those cases, but I buy your argument :+1: . I missed the loader/base.go handling.

File: bpf/bpf_overlay.c (hunk 12 above)
Comment (joestringer) [reply bpf/bpf_overlay.c:496]: Probably what this should do is transmit WORLD_ID and then the receive side should decide to treat "WORLD_ID" as "WORLD_IPV4_ID" iff dualstack is enabled at the destination. That would ensure that this doesn't cause connectivity issues if the peer node doesn't understand WORLD_IPV4_ID upon upgrade.

Comment (joestringer) [reply bpf/bpf_overlay.c:496]: (discovered while freshly looking at the multiprotocol SECLABEL handling in the PR, but I didn't search around for whether there might be any other similar cases)

File: bpf/lib/identity.h (hunk 11 above)
Comment (joestringer) [reply bpf/lib/identity.h:196]: ^ We can always follow up on this too, it's a nit.

File: pkg/fqdn/dnsproxy/proxy.go [hunk 13]
```diff
@@ -851,6 +851,13 @@ func (p *DNSProxy) ServeDNS(w dns.ResponseWriter, request *dns.Msg) {
 	}
 
 	targetServerID := identity.ReservedIdentityWorld
+	if option.Config.IsDualStack() {
+		if targetServerIP.To4() == nil {
```
Comment (christarazi) [inline pkg/fqdn/dnsproxy/proxy.go]: If `To4()` returns nil, then we set the ID to world-ipv4? Shouldn't the condition be

```suggestion
		if targetServerIP.To4() != nil {
```

[1]

File: pkg/proxy/logger/endpoint/epinfo.go [hunk 14]
```diff
@@ -73,7 +74,15 @@ func (r *endpointInfoRegistry) FillEndpointInfo(info *accesslog.EndpointInfo, ip
...
-			id = identity.ReservedIdentityWorld
+			if option.Config.IsDualStack() {
+				if ipAddr.To4() == nil {
+					id = identity.ReservedIdentityWorldIPv6
+				} else {
+					id = identity.ReservedIdentityWorldIPv4
+				}
+			} else {
+				id = identity.ReservedIdentityWorld
+			}
```
Comment (christarazi) [inline pkg/proxy/logger/endpoint/epinfo.go]: Maybe it's best to define a util function somewhere that returns the identity based on the IP, so that we keep the code DRY and prevent bugs such as [1]

**Review by christarazi — CHANGES_REQUESTED** [review]
Reviewed just proxy-related code files.

File: bpf/bpf_overlay.c (hunk 12 above)
Comment (nathanjsweet) [reply bpf/bpf_overlay.c:496]: So it will only be for dual-stack. It is an upgrade issue that I hadn't considered, but I don't see any way around it.

Comment (joestringer) [reply bpf/bpf_overlay.c:496]: Hmm, digging back through the git history, it looks like this encap identity here is specifically for the VTEP support. Using any VNI other than 2 may just break that feature. I think the right solution here is to keep the second to last parameter as `WORLD_ID`. The intermediate parameter can stay as `WORLD_IPV4_ID`, since that is used for local trace notifications only.

Even if we wanted to transition this to transmitting a different identity, I think that in general we should be introducing that gradually to minimize cluster disruption during the upgrades. But in this particular case with VTEP I don't even see a path for that.

Comment (nathanjsweet) [reply bpf/bpf_overlay.c:496]: [It looks like the `tunnel_id` is also set to the SECLABEL when VTEP is not enabled](https://github.com/cilium/cilium/blob/b3a19b54269435248419d2cbe6ff42afd9b479b7/bpf/lib/overloadable_skb.h#L202). Woulnd't that also be a problem?

Comment (joestringer) [reply bpf/bpf_overlay.c:496]: Hmm yeah I didn't step deep enough. 

My gut feeling here is that the right approach for the backportable fix is to set both to WORLD_ID. Even if we wanted to start transmitting the newer identity, that change should only be introduced in v1.15 after we backported this [PR transmitting `WORLD_ID`] to at least v1.14.

Then it's a question of exactly which paths care about handling ARP from a tunnel peer. I think the reason it's important in a VTEP case is that the VTEP doesn't have another out-of-bound mechanism to learn Pod IP locations. However I'm not sure whether Cilium ever sends ARP like this over the tunnels. If this is purely for VTEP then in this case I think it's both (a) fine to leave these as WORLD_ID and (b) there's no further changes necessary, it's the correct fix.

On the other hand if there is a non-VTEP case where this path is expected to do ARP response then the peer's handling of the security identity should be further inspected.

Comment (nathanjsweet) [reply bpf/bpf_overlay.c:496]: I'll try this out, but I got tunneling errors in CI before I made the SECLABEL changes.

File: pkg/fqdn/dnsproxy/proxy.go (hunk 13 above)
Comment (nathanjsweet) [reply pkg/fqdn/dnsproxy/proxy.go]: Good catch.

File: bpf/bpf_overlay.c (hunk 12 above)
Comment (joestringer) [reply bpf/bpf_overlay.c:496]: Those tunneling errors could potentially be the first sign of upgrade compatibility impact, because new identities were being transmitted and the corresponding receive paths were not handling them. Hard to say without seeing them directly though.

File: bpf/node_config.h (hunk 8 above)
Comment (nathanjsweet) [reply bpf/node_config.h:51]: > Why does it change the UX of policy engine?

Well, maybe not directly, but these entities could be selectable. Of course we could figure out a way to not expose them as referenceable entities in a policy file.

**Review by christarazi — APPROVED** [review]
LGTM from proxy side

File: bpf/node_config.h (hunk 8 above)
Comment (joestringer) [reply bpf/node_config.h:51]: I don't think they need to be user-facing entities. It's sufficient for these _identities_ selected by the existing policy APIs, as an internal detail.

**Review by joestringer — CHANGES_REQUESTED** [review]
The latest changes for encap look good, and there's one decap case handled, then I think there's a couple more remaining decap cases in `bpf/bpf_overlay.c:handle_ipv4()` and `bpf/bpf_overlay.c:handle_ipv6()` , both for the high scale and regular tunnel decap cases without encryption.

These suggest to me that we don't have policy coverage for an IPv4-only `0.0.0.0/0` allow for pods where the traffic is received from outside the cluster through a nodeport on a different node. That sort of test should be able to highlight a policy deny issue with this latest implementation.

File: bpf/bpf_overlay.c (hunk 12 above)
Comment (joestringer) [reply bpf/bpf_overlay.c:496]: The approach in the latest changes LGTM in principle for solving the issue raised by this thread, there's just another couple of missing cases. I'll mark this thread as resolved.

File: bpf/bpf_overlay.c [hunk 15]
```diff
@@ -75,13 +75,15 @@ static __always_inline int handle_ipv6(struct __ctx_buff *ctx,
 
 	decrypted = ((ctx->mark & MARK_MAGIC_HOST_MASK) == MARK_MAGIC_DECRYPT);
 	if (decrypted) {
-		if (info)
-			*identity = key.tunnel_id = info->sec_identity;
+		if (info) {
+			*identity = info->sec_identity;
+			key.tunnel_id = get_tunnel_id(info->sec_identity);
```
Comment (joestringer) [inline bpf/bpf_overlay.c:80]: I don't think that we need to change this case since the security identity is coming from ipcache?

Even if we need to change this line, I don't think that `*identity` and `key.tunnel_id` should diverge.

File: bpf/bpf_overlay.c [hunk 16]
```diff
@@ -321,16 +323,18 @@ static __always_inline int handle_ipv4(struct __ctx_buff *ctx,
 	decrypted = ((ctx->mark & MARK_MAGIC_HOST_MASK) == MARK_MAGIC_DECRYPT);
 	/* If packets are decrypted the key has already been pushed into metadata. */
 	if (decrypted) {
-		if (info)
-			*identity = key.tunnel_id = info->sec_identity;
+		if (info) {
+			*identity = info->sec_identity;
+			key.tunnel_id = get_tunnel_id(info->sec_identity);
```
Comment (joestringer) [inline bpf/bpf_overlay.c:328]: Same comment as IPv6 path.

File: bpf/bpf_overlay.c [hunk 17]
```diff
@@ -321,16 +323,18 @@ static __always_inline int handle_ipv4(struct __ctx_buff *ctx,
...
+		}
 	} else {
 #ifdef ENABLE_HIGH_SCALE_IPCACHE
-		key.tunnel_id = *identity;
+		key.tunnel_id = get_tunnel_id(*identity);
```
Comment (joestringer) [inline bpf/bpf_overlay.c:332]: This should also be `get_id_from_tunnel_id()` right? Effectively that function is the "receive" side converter, while `get_tunnel_id()` is the transmit side?
```suggestion
		key.tunnel_id = get_id_from_tunnel_id(*identity);
```

File: bpf/lib/overloadable_skb.h [hunk 18]
```diff
@@ -183,6 +183,30 @@ static __always_inline bool ctx_snat_done(const struct __sk_buff *ctx)
 	return (ctx->mark & MARK_MAGIC_HOST_MASK) == MARK_MAGIC_SNAT_DONE;
 }
 
+static __always_inline __u32 get_tunnel_id(__u32 identity)
```
Comment (joestringer) [inline bpf/lib/overloadable_skb.h]: Why do we need to define these functions twice? There is nothing specific to skb or xdp buffers here. We should be able to define these functions once in `lib/identity.h`?

**Review by joestringer — CHANGES_REQUESTED** [review]

File: bpf/lib/overloadable_skb.h (hunk 18 above)
Comment (nathanjsweet) [reply bpf/lib/overloadable_skb.h]: It can't live in `identity.h` as `identity.h` implicitly requires `overloadable_xxx.h`.

Comment (joestringer) [reply bpf/lib/overloadable_skb.h]: Ah right. I guess `lib/common.h` is an option to avoid duplication.

File: bpf/bpf_overlay.c (hunk 17 above)
Comment (nathanjsweet) [reply bpf/bpf_overlay.c:332]: No. Any tunnel key look-up should always convert `WORLD_IPVX_ID` to `WORLD_ID`. It doesn't matter if its on the receive-side.

File: bpf/bpf_overlay.c (hunk 15 above)
Comment (nathanjsweet) [reply bpf/bpf_overlay.c:80]: An ipcache lookup could still result in the identity being `WORLD_IPV6_ID`.

Comment (joestringer) [reply bpf/bpf_overlay.c:80]: That's correct on receive, right? Internally the datapath would understand `WORLD_IPV6_ID`, it's only when we serialize/deserialize we need to understand that peers may be transmitting `WORLD_ID`.

File: bpf/bpf_overlay.c (hunk 17 above)
Comment (joestringer) [reply bpf/bpf_overlay.c:332]: I disagree. What's important is that on the wire, `WORLD_ID` is used to ensure compatibility with older releases. At the same time, internally in the datapath if running in dual-stack mode, the datapath should consistently identify the identity of that peer and if it's an IPv4-based world identity peer that should be `WORLD_IPV4_ID`. That way, when we receive traffic with `WORLD_ID`, we can convert that to `WORLD_IPV4_ID`, then generate hubble flows with `WORLD_IPV4_ID` and do network policy lookups with `WORLD_IPV4_ID` in order to properly reflect that this new version of Cilium is identifying this traffic as a more narrowly scoped "world" for the specific protocol.

At the minimum, the policy lookup needs to use the protocol-scoped world identity to perform the lookup, otherwise the traffic could be denied by an "allow `0.0.0.0/0`" policy (which is encoded in the policymap as "allow from identity `9`" in dual-stack scenarios). If we're doing that for policy lookup, then the datapath should likewise emit all hubble events with the identity that the datapath is considering this traffic to correspond to. Otherwise we'll have a lot of difficulty debugging problems related to these new protocol-specific world identities.

File: bpf/bpf_overlay.c (hunk 15 above)
Comment (joestringer) [reply bpf/bpf_overlay.c:80]: ^ Reviewing afresh with Nathan,this path is updating `key.tunnel_id` to ensure that whenever we modify that field, we always encode `WORLD_IPV*_ID` into `WORLD_ID`, and whenever decoding from that field, we convert back.

I'm still a little bit concerned about the potential for divergence here, but this is probably easier to ensure that the implementation is correct because any subsequent reads from the `tunnel_id` field will convert back. I withdraw my comment here :+1:

File: bpf/bpf_overlay.c (hunk 17 above)
Comment (joestringer) [reply bpf/bpf_overlay.c:332]: Reading through this afresh, I assumed that with the `#ifdef ENABLE_HIGH_SCALE_IPCACHE` function that the macro if/else was updating the same variables / fields and that this line was updating `*identity`. I then argued above that internally within the datapath we should always be using the newer protocol-specific world identities. The first assumption was wrong and this code is enforcing the exact property that I was arguing for. :sweat_smile: 

Sorry for the confusion! LGTM.

Comment (joestringer) [reply bpf/bpf_overlay.c:332]: (I'm now a bit confused why the high scale ipcache code here doesn't update `*identity`, but that has nothing to do with this PR).

**Review by joestringer — APPROVED** [review]

File: bpf/node_config.h (hunk 8 above)
Comment (joestringer) [reply bpf/node_config.h:51]: ^ No reason to block this PR on this discussion point, but we can continue to discuss out-of-band on the implications here and longer term supportability.

File: pkg/policy/l4.go (hunk 7 above)
Comment (squeed) [reply pkg/policy/l4.go:589]: We did miss this logic; world is a label, not an identity. https://github.com/cilium/cilium/pull/29958 fixes this.

We might be able to remove this code now.

File: bpf/bpf_overlay.c [hunk 19]
```diff
@@ -345,7 +349,7 @@ static __always_inline int handle_ipv4(struct __ctx_buff *ctx,
 			if (!vtep)
 				goto skip_vtep;
 			if (vtep->tunnel_endpoint) {
-				if (*identity != WORLD_ID)
+				if (identity_is_world_ipv4(*identity))
```
Comment (joestringer) [inline bpf/bpf_overlay.c:352]: This looks like it reversed the logic, breaking VTEP support, see https://github.com/cilium/cilium/issues/31023.
