### PR TITLE
services: Fix metric from not publishing

### LINKED ISSUE #26511: Missing `services_events_total` metric
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I deployed cilium 1.13.4 on kubernetes.
I am scraping both the operator and the agents with prometheus.
I deployed the default grafana dashboard.

I don't have data for one chart, turns out the `cilium_services_events_total` is not exposed by either components.

Looking at the code it looks like the metric should always be exposed

### Cilium Version

1.13.4

### Kernel Version

5.15.111-flatcar

### Kubernetes Version

v1.24.15

### Sysdump

_No response_

### Relevant log output

```shell
# curl -s localhost:9962/metrics|grep services_events_total
#
```

```
# curl -s localhost:9963/metrics|grep services_events_total
#
```
```


### Anything else?

it's not about the metric being without data, the description is not there in the exporter outputs.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by christarazi**
- metrics, service: Rename metric for clarity
- services: Fix metric from not publishing

```release-note
Fix missing metric "cilium_services_events_total"
```

Fixes: https://github.com/cilium/cilium/issues/26511

### CODE REVIEW

**Comment by chancez** [comment]
Odd. I'm reading the docs on `WithLabelValues` to figure out the cause of the behavior described in your commit message. It refers to https://pkg.go.dev/github.com/prometheus/client_golang/prometheus#CounterVec.GetMetricWithLabelValues which says:

> Keeping the Counter for later use is possible (and should be considered if performance is critical), but keep in mind that Reset, DeleteLabelValues and Delete can be used to delete the Counter from the CounterVec. In that case, the Counter will still exist, but it will not be exported anymore, even if a Counter with the same label values is created later.

Do we do anything like call Reset or Delete*?

File: pkg/service/service.go [hunk 1]
```diff
@@ -33,12 +33,6 @@ import (
 
 const anyPort = "*"
 
-var (
-	updateMetric = metrics.ServicesCount.WithLabelValues("update")
```
Comment (ysksuzuki) [inline pkg/service/service.go:37]: This code is called before `NewLegacyMetrics` initializes ServicesCount, and calls `NoOpCounterVec.WithLabelValues` (returns `NoOpGauge`). That's the reason `services_events_total` is missing. Is my understanding correct?

Comment (christarazi) [reply pkg/service/service.go:37]: Yes, I think you're right. I opened a small thread about this in #development and that's what Andre suspected as well. :+1:

Comment (christarazi) [reply pkg/service/service.go:37]: cc @chancez

Comment (chancez) [reply pkg/service/service.go:37]: Gotcha. How can we prevent this from reoccurring?

Comment (christarazi) [reply pkg/service/service.go:37]: I'm not too sure to be honest. We have https://github.com/cilium/customvet where we can write our own linting checkers. However, this is the only case that I've found in the code base. Moving forward there is an effort to move metrics into their modules (see https://github.com/cilium/cilium/pull/25651) which should help, but techincally not a guarantee.

Comment (ysksuzuki) [reply pkg/service/service.go:37]: For example, we can configure a workflow for the metrics check in which we set up Prometheus and scrape the agent's metrics, fetch the metrics key list using promql-cli or Prometheus API, and then check if all metrics are available. But I'm not sure if such an expensive test suite is worth the cost.

**Review by ysksuzuki — APPROVED** [review]
The changes look good to me

File: pkg/service/service.go (hunk 1 above)
Comment (christarazi) [reply pkg/service/service.go:37]: In the past, I've seen metrics not published unless Cilium modified its value. At least, this is what I observed with `cilium metrics list` and not sure if the same would apply to simply hitting the Prometheus endpoint. If they are not published, then this will make this workflow suggested a bit more complicated.

Comment (chancez) [reply pkg/service/service.go:37]: The option is to get rid of these NoOp metrics potentially. The approach we're using is a bit odd from my perspective but I haven't really dug into why we do it this way. There's a lot of history probably in how we decided that approach.

We could choose to always create the 'real' metrics (removing NoOps), and then change the logic to not register them instead when the metrics are disabled. However it's probably a bigger/harder change to make (and shouldn't block this PR). Then the metrics would still exist (they're just atomic counters) but they won't be exported (because they aren't registered).

Comment (christarazi) [reply pkg/service/service.go:37]: That seams quite reasonable to me. I guess I didn't question the structure, but now that I think about it a bit, they're likely defined this way (NoOp) because of the problem of having global metrics defined in one place rather than per module. Due to them being exposed as global vars, they can be accessed at any time without any guarantee that they've been initialized, so NoOp wrapper was created to prevent panics / crashes in case that happened. That's my guess.

cc @aanm (for adding NoOp) and @dylandreimerink (for whether we still need the idea of "NoOp" metrics going forward)

Comment (dylandreimerink) [reply pkg/service/service.go:37]: > The option is to get rid of these NoOp metrics potentially. The approach we're using is a bit odd from my perspective but I haven't really dug into why we do it this way

The NoOp metrics exist as a stopgap, currently a lot of the code base still uses global variables to get metrics which is subject to ordering. 

> they're likely defined this way (NoOp) because of the problem of having global metrics defined in one place rather than per module. Due to them being exposed as global vars, they can be accessed at any time without any guarantee that they've been initialized, so NoOp wrapper was created to prevent panics / crashes in case that happened.

Yes, that is indeed correct.

Ideally, all metrics are provided to components via parameters during construction, but this conversion takes some time. We can remove NoOps once all global metric variables are gone.

Comment (chancez) [reply pkg/service/service.go:37]: There's an intermediate step I mentioned that wasn't addressed: You can have globals, without NoOp metrics, but not call `registry.Register(yourMetric)`. This avoids ordering issues and nil globals.

**Comment by christarazi** [comment]
@chancez Is there anything that you think is blocking merging this PR?

File: pkg/service/service.go (hunk 1 above)
Comment (christarazi) [reply pkg/service/service.go:37]: Btw, I've updated the second commit's description to describe the global variable vs initialization ordering as the root cause of the bug.

**Review by chancez — APPROVED** [review]

File: pkg/service/service.go (hunk 1 above)
Comment (dylandreimerink) [reply pkg/service/service.go:37]: > There's an intermediate step I mentioned that wasn't addressed: You can have globals, without NoOp metrics, but not call registry.Register(yourMetric). This avoids ordering issues and nil globals.

Yes, you could init the global var and then upon creating the registry determine if you want to add that metric to the registry or not. 

I am not sure why NoOps were chosen over that approach, it is not something invented for the modular metrics, it was already the way things worked. The main thing that changed was init ordering.

I would argue that removing all global variables in favor of dependency injection ASAP is a better use of cycles then refactoring the NoOps away first.

**Review by dylandreimerink — APPROVED** [review]
