### PR TITLE
bpf: fix nodeport ipv6 services

### LINKED ISSUE #13047: In v1.8.2 dual-stack mode external traffic to a IPv6 loadBalancerIP fails
## Bug report

In a dual-stack private-cloud (no public cloud-provider) a service is defined as;

```
$ kubectl get svc mconnect-ipv6 -o json | jq .spec,.status
{
  "clusterIP": "fd00:4000::c83f",
  "externalTrafficPolicy": "Cluster",
  "ipFamily": "IPv6",
  "loadBalancerIP": "1000::",
  "ports": [
    {
      "nodePort": 30139,
      "port": 5001,
      "protocol": "TCP",
      "targetPort": 5001
    }
  ],
  "selector": {
    "app": "mconnect"
  },
  "sessionAffinity": "None",
  "type": "LoadBalancer"
}
{
  "loadBalancer": {
    "ingress": [
      {
        "ip": "1000::"
      }
    ]
  }
}
```
The service should be reachable from an external machine on address `[1000::]:5001` but there is no response (no syn-ack, nothing).

The service _is_ however reachable on the loadBalancerIP from a node inside the cluster;
```
$ telnet 1000:: 5001
mconnect-deployment-d6c79bdc5-ll9pc
```
(the endpoint replies with it's hostname)

The problem also exists for NodePort, it can be accessed from a node within the cluster but not from an external source.

This works (same service) in Cilium 1.7.8.

**General Information**

- Cilium version (run `cilium version`); v1.8.2
- Kernel version (run `uname -a`); 
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...); K8s v1.19.0
- Link to relevant artifacts (policies, deployments scripts, ...);
- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

1. Install K8s with dual-stack
2. Install Cilium with [quick-install.yaml.txt](https://github.com/cilium/cilium/files/5161210/quick-install.yaml.txt)
3. Install some app with a service similar to that above. My setup; [mconnect-dual.yaml.txt](https://github.com/cilium/cilium/files/5161241/mconnect-dual.yaml.txt)
4. Assign the loadBalancerIP, e.g with [assign-lb-ip](https://github.com/Nordix/assign-lb-ip)
5. Setup a ipv6 route on an external machine to the loadBalancerIP via some K8s nodes
6. Access the loadBalancerIP

### PR DESCRIPTION
**Pull request by fristonio**
See commit messages for more details

- [x] Fixes IPv6 NodePort service handling - Fixes #13047 
- [x] Add test to validate the behavior in tests.

```release-note
Fix issue in NodePort service revnat handling where the interface index was not properly restored from the conntrack state leading to packet redirects to an invalid interface.
```

### CODE REVIEW

**Comment by fristonio** [comment]
test-only --focus="K8sServicesTest.*Tests IPv6 NodePort Services" --kernel_version=net-next --k8s-version=1.19

**Comment by fristonio** [comment]
test-only --focus="K8sServicesTest.*Tests IPv6 NodePort Services" --kernel_version=net-next --k8s_version=1.19

**Comment by fristonio** [comment]
test-only --focus="K8sServicesTest.*Tests IPv6 NodePort Services" --kernel_version=net-next --k8s_version=1.19

**Comment by fristonio** [comment]
retest-net-next

**Comment by fristonio** [comment]
retest-net-next

**Comment by fristonio** [comment]
retest-net-next

**Comment by fristonio** [comment]
retest-net-next

**Comment by fristonio** [comment]
retest-net-next

**Comment by fristonio** [comment]
test-me-please

**Comment by fristonio** [comment]
retest-net-next

**Comment by fristonio** [comment]
test-me-please

**Review by borkmann — APPROVED** [review]

**Review by vadorovsky — COMMENTED** [review]
```
16:56:29  •! Panic [21.610 seconds]
16:56:29  K8sServicesTest
16:56:29  /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Kernel/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:478
16:56:29    Checks service across nodes
16:56:29    /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Kernel/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:478
16:56:29      Tests IPv6 NodePort Services
16:56:29      /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Kernel/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:478
16:56:29        Test IPv6 connectivity to NodePort service [It]
16:56:29        /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Kernel/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:514
16:56:29  
16:56:29        Test Panicked
16:56:29        runtime error: invalid memory address or nil pointer dereference
16:56:29        /usr/local/go/src/runtime/panic.go:212
16:56:29  
16:56:29        Full Stack Trace
16:56:29        github.com/cilium/cilium/test/helpers.(*Buffer).String(0x0, 0x8, 0xc0007d2688)
16:56:29        	/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Kernel/src/github.com/cilium/cilium/test/helpers/buffer.go:45 +0x2d
16:56:29        github.com/cilium/cilium/test/helpers.(*CmdRes).Stdout(...)
16:56:29        	/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Kernel/src/github.com/cilium/cilium/test/helpers/cmd.go:178
16:56:29        github.com/cilium/cilium/test/helpers.(*CmdRes).OutputPrettyPrint(0xc000b3ed20, 0x70, 0x1caa240)
16:56:29        	/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Kernel/src/github.com/cilium/cilium/test/helpers/cmd.go:418 +0xd3
16:56:29        github.com/cilium/cilium/test/helpers.(*BeSuccesfulMatcher).FailureMessage(0x313d3a8, 0x1d4d940, 0xc000b3ed20, 0x2084300, 0x0)
16:56:29        	/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Kernel/src/github.com/cilium/cilium/test/helpers/cmd.go:569 +0x69
16:56:29        github.com/onsi/gomega/internal/assertion.(*Assertion).match(0xc00155a500, 0x20b87e0, 0x313d3a8, 0x1, 0xc0006bf0a0, 0x1, 0x1, 0xc00155a500)
16:56:29        	/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Kernel/src/github.com/cilium/cilium/vendor/github.com/onsi/gomega/internal/assertion/assertion.go:74 +0xfb
16:56:29        github.com/onsi/gomega/internal/assertion.(*Assertion).Should(0xc00155a500, 0x20b87e0, 0x313d3a8, 0xc0006bf0a0, 0x1, 0x1, 0x1a59901)
16:56:29        	/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Kernel/src/github.com/cilium/cilium/vendor/github.com/onsi/gomega/internal/assertion/assertion.go:28 +0xc7
16:56:29        github.com/cilium/cilium/test/helpers.(*CmdRes).ExpectSuccess(0xc000b3ed20, 0xc0006bf0a0, 0x1, 0x1, 0x0)
16:56:29        	/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Kernel/src/github.com/cilium/cilium/test/helpers/cmd.go:232 +0xd5
16:56:29        github.com/cilium/cilium/test/k8sT.glob..func12.19.16(0x0, 0x0, 0x1d89b1b, 0x6, 0xc000a35440, 0x20)
16:56:29        	/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Kernel/src/github.com/cilium/cilium/test/k8sT/Services.go:687 +0x182
16:56:29        github.com/cilium/cilium/test/k8sT.glob..func12.19.18(0x1d9dd01, 0xc0007bdd42, 0x7, 0xc0007bdd40, 0x2, 0xc0007bdd60, 0xd, 0x0, 0x0, 0xc0007bdd70, ...)
16:56:29        	/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Kernel/src/github.com/cilium/cilium/test/k8sT/Services.go:848 +0x91e
16:56:29        github.com/cilium/cilium/test/k8sT.glob..func12.19.31.3()
16:56:29        	/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Kernel/src/github.com/cilium/cilium/test/k8sT/Services.go:1378 +0xc6
16:56:29        reflect.Value.call(0x1a1c220, 0xc0004ad500, 0x13, 0x1d8710a, 0x4, 0x313d3a8, 0x0, 0x0, 0x0, 0x0, ...)
16:56:29        	/usr/local/go/src/reflect/value.go:460 +0x8ab
16:56:29        reflect.Value.Call(0x1a1c220, 0xc0004ad500, 0x13, 0x313d3a8, 0x0, 0x0, 0x2, 0xc0007d3270, 0x44e45c)
16:56:29        	/usr/local/go/src/reflect/value.go:321 +0xb4
16:56:29        github.com/cilium/cilium/test/ginkgo-ext.applyAdvice.func1(0x313d3a8, 0x0, 0x0, 0x0, 0x0, 0x0)
16:56:29        	/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Kernel/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:562 +0xb1
16:56:29        reflect.callReflect(0xc000a16a50, 0xc0007d33e8, 0xc0007d33d0)
16:56:29        	/usr/local/go/src/reflect/value.go:549 +0x322
16:56:29        reflect.makeFuncStub(0xc0007d340e, 0xc000594720, 0xc0007d3458, 0xc0007d3450, 0xc0018ac9a0, 0xc0007d3458, 0xc0006f2ba0, 0xc0007d340e, 0x1e83db0, 0xc0007d3450, ...)
16:56:29        	/usr/local/go/src/reflect/asm_amd64.s:20 +0x42
16:56:29        github.com/cilium/cilium/test.TestTest(0xc00073e240)
16:56:29        	/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Kernel/src/github.com/cilium/cilium/test/test_suite_test.go:109 +0x313
16:56:29        testing.tRunner(0xc00073e240, 0x1e82ac8)
16:56:29        	/usr/local/go/src/testing/testing.go:992 +0xdc
16:56:29        created by testing.(*T).Run
16:56:29        	/usr/local/go/src/testing/testing.go:1043 +0x357
```

**Comment by fristonio** [comment]
retest-4.19

**Comment by fristonio** [comment]
test-me-please

File: test/k8sT/Services.go [hunk 1]
```diff
@@ -672,18 +672,22 @@ var _ = Describe("K8sServicesTest", func() {
 			), "Failed to account for IPv4 fragments to %s (out)", dstIP)
 		}
 
-		getIPv4Andv6AddrForIface := func(nodeName, iface string) (string, string) {
+		getIPv4AddrForIface := func(nodeName, iface string) string {
```
Comment (christarazi) [inline test/k8sT/Services.go:683]: I know you didn't modify the body of this function, but we might as well fix-up the incorrect expectation. Because the expectation is inside a function, we need to use `ExpectWithOffset`.

File: test/k8sT/Services.go [hunk 2]
```diff
@@ -672,18 +672,22 @@ var _ = Describe("K8sServicesTest", func() {
...
 
-			cmd = fmt.Sprintf("ip -6 -o a s dev %s scope global | awk '{print $4}' | cut -d/ -f1", iface)
-			res = kubectl.ExecInHostNetNS(context.TODO(), nodeName, cmd)
+			return ipv4
+		}
+
+		getIPv6AddrForIface := func(nodeName, iface string) string {
+			cmd := fmt.Sprintf("ip -6 -o a s dev %s scope global | awk '{print $4}' | cut -d/ -f1", iface)
+			res := kubectl.ExecInHostNetNS(context.TODO(), nodeName, cmd)
 			res.ExpectSuccess(cmd)
```
Comment (christarazi) [inline test/k8sT/Services.go:695]: Because the expectation is inside a function, we need to use `ExpectWithOffset`.

File: test/k8sT/Services.go [hunk 3]
```diff
@@ -672,18 +672,22 @@ var _ = Describe("K8sServicesTest", func() {
...
 			ipv4 := strings.Trim(res.Stdout(), "\n")
 
-			cmd = fmt.Sprintf("ip -6 -o a s dev %s scope global | awk '{print $4}' | cut -d/ -f1", iface)
-			res = kubectl.ExecInHostNetNS(context.TODO(), nodeName, cmd)
+			return ipv4
+		}
+
+		getIPv6AddrForIface := func(nodeName, iface string) string {
+			cmd := fmt.Sprintf("ip -6 -o a s dev %s scope global | awk '{print $4}' | cut -d/ -f1", iface)
```
Comment (christarazi) [inline test/k8sT/Services.go]: Nit: I find it helpful to put the long names of args, etc in scripts / tests so that it is clear what is happening without needing to remember all the aliases or having to look them up.

File: test/k8sT/Services.go [hunk 4]
```diff
@@ -831,6 +835,61 @@ var _ = Describe("K8sServicesTest", func() {
...
+		// It is the job of the caller to make sure that all the node have assigned
+		// routable IPV6 addresses reachable from other nodes.
+		testNodePortIPv6 := func(testFromOutside bool, data *v1.Service) {
+			var wg sync.WaitGroup
+
+			k8s1IPv6 := getIPv6AddrForIface(k8s1NodeName, helpers.SecondaryIface)
+			k8s2IPv6 := getIPv6AddrForIface(k8s2NodeName, helpers.SecondaryIface)
+
+			Expect(k8s1IPv6).ToNot(Equal(""), "Cannot get IPv6 address for K8s1 node")
+			Expect(k8s2IPv6).ToNot(Equal(""), "Cannot get IPv6 address for K8s2 node")
```
Comment (christarazi) [inline test/k8sT/Services.go]: Because the expectation is inside a function, we need to use `ExpectWithOffset`. Also, I think we can use `ToNot(BeEmpty()` or `ToNot(HaveLen(0)` (whichever exists :) )

File: test/k8sT/Services.go [hunk 5]
```diff
@@ -1277,6 +1336,42 @@ var _ = Describe("K8sServicesTest", func() {
...
+			return helpers.RunsWithKubeProxy() || helpers.GetCurrentIntegration() != ""
+		}, "Tests IPv6 NodePort Services", func() {
+			var (
+				testDSIPv6 string = "fd03::310"
+				data       v1.Service
+			)
+
+			BeforeAll(func() {
+				err := kubectl.Get(helpers.DefaultNamespace, "service test-nodeport").Unmarshal(&data)
+				ExpectWithOffset(1, err).Should(BeNil(), "Cannot retrieve service")
```
Comment (christarazi) [inline test/k8sT/Services.go]: This does not need to be an `ExpectWithOffset`.

**Review by christarazi — CHANGES_REQUESTED** [review]
Reviewed from CI perspective. A few comments to address.

File: test/k8sT/Services.go (hunk 1 above)
Comment (fristonio) [reply test/k8sT/Services.go:683]: We are using `res.ExpectSuccess` which internally uses `ExpectWithOffset`. I am not sure if I understand the usage of `ExpectWithOffset` correctly but do we still need to use that here?

File: test/k8sT/Services.go (hunk 3 above)
Comment (fristonio) [reply test/k8sT/Services.go]: Do you mean using `ip -family inet6 -oneline address show dev wlo1 scope global | awk '{print $4}' | cut -d/ -f1` instead?

File: test/k8sT/Services.go [hunk 6]
```diff
@@ -831,6 +835,61 @@ var _ = Describe("K8sServicesTest", func() {
 			wg.Wait()
 		}
 
+		// This function tests NodePort srvices using IPV6 addresses
```
Comment (vadorovsky) [inline test/k8sT/Services.go]:
```suggestion
		// This function tests NodePort services using IPV6 addresses
```

**Review by vadorovsky — COMMENTED** [review]
nit

**Comment by fristonio** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

File: test/k8sT/Services.go (hunk 3 above)
Comment (christarazi) [reply test/k8sT/Services.go]: Haha, that's quite long isn't now. I think you can omit the `family` and the IPv6 stuff. I was mostly interested in the actual subcommands to `ip`. In this case they are `address` and `show`.

```
ip -6 -oneline addr show dev ...
``` 

Looks good to me ^

File: test/k8sT/Services.go (hunk 1 above)
Comment (christarazi) [reply test/k8sT/Services.go:683]: `ExpectWithOffset` is used when you define a helper function that's called inside an `It()` block. Ideally, all expectations should be done inside the `It()` block, and therefore using `Expect` is proper. However, sometimes it is convenient to define helpers and call them within `It()` blocks, hence the need for an "offset".

Comment (christarazi) [reply test/k8sT/Services.go:683]: In the case of `res.ExpectSuccess`, there are two offsets. One for the actual call to it, and one from the call to `getIPv4AddrForIface` from the `It()` block. It's confusing and unreadable, huh? :) And what's worse is that when a test fails with the wrong offset or `ExpectWithOffset` was wrongly used, the stacktrace for the CI failure is off, which makes debugging / triaging a pain. That's why I've been trying to simplify our "expectations" in Ginkgo.

Comment (fristonio) [reply test/k8sT/Services.go:683]: Ah, that makes sense. So for this, do you think creating a new helper function like `CmdRes.ExpectSuccessWithOffset` where we make use of right offset make sense? I don't want to edit the parts of the code the PR does not touch. Also, we can take this as a followup and I can fix all the `ExpectSuccess` calls from within a helper function using this new method.

Comment (christarazi) [reply test/k8sT/Services.go:683]: Hmm, I'm towards just "deprecating" `ExpectSuccess` because it's just as easy to do something like:

```
Expect(foo()).To(helper.CMDSuccess())
```
or
```
ExpectWithOffset(foo(), offset).To(helper.CMDSuccess())
```

So I don't really see the benefit for `ExpectSuccess` defined on the `CmdRes` object anyway, so I'd stay away from adding yet another helper function.

But for this PR, I agree. No need to make unrelated changes; can be a followup.

**Review by christarazi — APPROVED** [review]
