### PR TITLE
datapath/loader: Fix route upsert failure on late ep device registration

### LINKED ISSUE #42592: CI: Conformance Cluster Mesh - Pod has no connectivity
## CI failure

Observed in Ci, but it look like a real bug.

* Link: https://github.com/cilium/cilium/actions/runs/19055747842/job/54425433320
* Sysdump: [cilium-sysdump-context2-final-6-vxlan-ipv4-disabled-none-kvstoremesh-helm-cluster-cluster-255-enabled-false-enabled.zip](https://github.com/user-attachments/files/23339051/cilium-sysdump-context2-final-6-vxlan-ipv4-disabled-none-kvstoremesh-helm-cluster-cluster-255-enabled-false-enabled.zip)

#### TL;DR;

The clustermesh-apiserver pod is in CrashLoopBackOff because it cannot access the Kubernetes API Server:

```
NAMESPACE            NAME                                                         READY   STATUS             RESTARTS      AGE     IP            NODE           
...
kube-system          clustermesh-apiserver-9c4c5d56f-qwf7v                        1/3     CrashLoopBackOff   4 (32s ago)   7m40s   11.10.1.144   cluster2-19055747842-worker2 
```

```
level=fatal source=/go/src/github.com/cilium/cilium/pkg/logging/slog.go:159 msg="failed to start: Get \"https://10.245.0.1:443/api/v1/namespaces/kube-system\": dial tcp 10.245.0.1:443: i/o timeout"
```

In turn, this seems to be caused by a missing endpoint route, due to the following error:

```
time=2025-11-04T02:28:39.262165877Z level=warn source=/go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:777 msg="Failed to upsert route" containerInterface="" desiredPolicyRevision=1 ipv4=11.10.1.144 ciliumEndpointName=kube-system/clustermesh-apiserver-9c4c5d56f-qwf7v endpointID=121 datapathPolicyRevision=0 ipv6="" k8sPodName=kube-system/clustermesh-apiserver-9c4c5d56f-qwf7v containerID=50d4bd7d07 identity=16720700 subsys=datapath-loader interface=lxcba0153a9f667 error="device 9 not found for endpoint 121"
```

Indeed, the routes statedb table on the hosting node does not include any entry for `11.10.1.144`:

```
  "routes": [
    {"Table":254,"LinkIndex":2,"Type":1,"Scope":0,"Dst":"::/0","Src":"","Gw":"fc00:f853:ccd:e793::1","Priority":1024,"MTU":0},
    {"Table":254,"LinkIndex":2,"Type":1,"Scope":0,"Dst":"0.0.0.0/0","Src":"","Gw":"172.18.0.1","Priority":0,"MTU":0},
    {"Table":254,"LinkIndex":2,"Type":1,"Scope":253,"Dst":"172.18.0.0/16","Src":"172.18.0.5","Gw":"","Priority":0,"MTU":0},
    {"Table":254,"LinkIndex":2,"Type":1,"Scope":0,"Dst":"fc00:f853:ccd:e793::/64","Src":"","Gw":"","Priority":256,"MTU":0},
    {"Table":254,"LinkIndex":2,"Type":1,"Scope":0,"Dst":"fe80::/64","Src":"","Gw":"","Priority":256,"MTU":0},
    {"Table":254,"LinkIndex":3,"Type":1,"Scope":0,"Dst":"fe80::/64","Src":"","Gw":"","Priority":256,"MTU":0},
    {"Table":254,"LinkIndex":4,"Type":1,"Scope":0,"Dst":"11.10.0.0/24","Src":"11.10.1.218","Gw":"11.10.1.218","Priority":0,"MTU":1450},
    {"Table":254,"LinkIndex":4,"Type":1,"Scope":253,"Dst":"11.10.1.218/32","Src":"","Gw":"","Priority":0,"MTU":0},
    {"Table":254,"LinkIndex":4,"Type":1,"Scope":0,"Dst":"11.10.2.0/24","Src":"11.10.1.218","Gw":"11.10.1.218","Priority":0,"MTU":1450},
    {"Table":254,"LinkIndex":4,"Type":1,"Scope":0,"Dst":"fe80::/64","Src":"","Gw":"","Priority":256,"MTU":0},
    {"Table":254,"LinkIndex":5,"Type":1,"Scope":0,"Dst":"fe80::/64","Src":"","Gw":"","Priority":256,"MTU":0},
    {"Table":254,"LinkIndex":7,"Type":1,"Scope":253,"Dst":"11.10.1.244/32","Src":"","Gw":"","Priority":0,"MTU":0},
    {"Table":254,"LinkIndex":7,"Type":1,"Scope":0,"Dst":"fe80::/64","Src":"","Gw":"","Priority":256,"MTU":0},
    {"Table":254,"LinkIndex":9,"Type":1,"Scope":0,"Dst":"fe80::/64","Src":"","Gw":"","Priority":256,"MTU":0},
    {"Table":255,"LinkIndex":1,"Type":2,"Scope":0,"Dst":"::1/128","Src":"","Gw":"","Priority":0,"MTU":0},
    {"Table":255,"LinkIndex":1,"Type":2,"Scope":254,"Dst":"127.0.0.0/8","Src":"127.0.0.1","Gw":"","Priority":0,"MTU":0},
    {"Table":255,"LinkIndex":1,"Type":2,"Scope":254,"Dst":"127.0.0.1/32","Src":"127.0.0.1","Gw":"","Priority":0,"MTU":0},
    {"Table":255,"LinkIndex":1,"Type":3,"Scope":253,"Dst":"127.255.255.255/32","Src":"127.0.0.1","Gw":"","Priority":0,"MTU":0},
    {"Table":255,"LinkIndex":2,"Type":2,"Scope":254,"Dst":"172.18.0.5/32","Src":"172.18.0.5","Gw":"","Priority":0,"MTU":0},
    {"Table":255,"LinkIndex":2,"Type":3,"Scope":253,"Dst":"172.18.255.255/32","Src":"172.18.0.5","Gw":"","Priority":0,"MTU":0},
    {"Table":255,"LinkIndex":2,"Type":2,"Scope":0,"Dst":"fc00:f853:ccd:e793::5/128","Src":"","Gw":"","Priority":0,"MTU":0},
    {"Table":255,"LinkIndex":2,"Type":2,"Scope":0,"Dst":"fe80::6452:e6ff:fe90:a5be/128","Src":"","Gw":"","Priority":0,"MTU":0},
    {"Table":255,"LinkIndex":2,"Type":5,"Scope":0,"Dst":"ff00::/8","Src":"","Gw":"","Priority":256,"MTU":0},
    {"Table":255,"LinkIndex":3,"Type":2,"Scope":0,"Dst":"fe80::7c19:93ff:fec9:f7cb/128","Src":"","Gw":"","Priority":0,"MTU":0},
    {"Table":255,"LinkIndex":3,"Type":5,"Scope":0,"Dst":"ff00::/8","Src":"","Gw":"","Priority":256,"MTU":0},
    {"Table":255,"LinkIndex":4,"Type":2,"Scope":254,"Dst":"11.10.1.218/32","Src":"11.10.1.218","Gw":"","Priority":0,"MTU":0},
    {"Table":255,"LinkIndex":4,"Type":2,"Scope":0,"Dst":"fe80::9470:92ff:fef8:c7bb/128","Src":"","Gw":"","Priority":0,"MTU":0},
    {"Table":255,"LinkIndex":4,"Type":5,"Scope":0,"Dst":"ff00::/8","Src":"","Gw":"","Priority":256,"MTU":0},
    {"Table":255,"LinkIndex":5,"Type":2,"Scope":0,"Dst":"fe80::c4c7:4bff:fed5:e039/128","Src":"","Gw":"","Priority":0,"MTU":0},
    {"Table":255,"LinkIndex":5,"Type":5,"Scope":0,"Dst":"ff00::/8","Src":"","Gw":"","Priority":256,"MTU":0},
    {"Table":255,"LinkIndex":7,"Type":2,"Scope":0,"Dst":"fe80::d8ba:2eff:fe74:5832/128","Src":"","Gw":"","Priority":0,"MTU":0},
    {"Table":255,"LinkIndex":7,"Type":5,"Scope":0,"Dst":"ff00::/8","Src":"","Gw":"","Priority":256,"MTU":0},
    {"Table":255,"LinkIndex":9,"Type":2,"Scope":0,"Dst":"fe80::ec0c:d5ff:feb4:c747/128","Src":"","Gw":"","Priority":0,"MTU":0},
    {"Table":255,"LinkIndex":9,"Type":5,"Scope":0,"Dst":"ff00::/8","Src":"","Gw":"","Priority":256,"MTU":0},
    {"Table":2004,"LinkIndex":1,"Type":2,"Scope":254,"Dst":"0.0.0.0/0","Src":"","Gw":"","Priority":0,"MTU":0}
  ],
```

And obviously the corresponding route is not present:

```
default via 172.18.0.1 dev eth0 
11.10.0.0/24 via 11.10.1.218 dev cilium_host proto kernel src 11.10.1.218 mtu 1450 
11.10.1.218 dev cilium_host proto kernel scope link 
11.10.1.244 dev lxc_health proto kernel scope link 
11.10.2.0/24 via 11.10.1.218 dev cilium_host proto kernel src 11.10.1.218 mtu 1450 
172.18.0.0/16 dev eth0 proto kernel scope link src 172.18.0.5 
```

The device 9 mentioned in the warning log is the pod interface:

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0@if9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 66:52:e6:90:a5:be brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.18.0.5/16 brd 172.18.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fc00:f853:ccd:e793::5/64 scope global nodad 
       valid_lft forever preferred_lft forever
    inet6 fe80::6452:e6ff:fe90:a5be/64 scope link 
       valid_lft forever preferred_lft forever
3: cilium_net@cilium_host: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 7e:19:93:c9:f7:cb brd ff:ff:ff:ff:ff:ff
    inet6 fe80::7c19:93ff:fec9:f7cb/64 scope link 
       valid_lft forever preferred_lft forever
4: cilium_host@cilium_net: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 96:70:92:f8:c7:bb brd ff:ff:ff:ff:ff:ff
    inet 11.10.1.218/32 scope global cilium_host
       valid_lft forever preferred_lft forever
    inet6 fe80::9470:92ff:fef8:c7bb/64 scope link 
       valid_lft forever preferred_lft forever
5: cilium_vxlan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default 
    link/ether c6:c7:4b:d5:e0:39 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::c4c7:4bff:fed5:e039/64 scope link 
       valid_lft forever preferred_lft forever
7: lxc_health@if6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether da:ba:2e:74:58:32 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::d8ba:2eff:fe74:5832/64 scope link 
       valid_lft forever preferred_lft forever
9: lxcba0153a9f667@if8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether ee:0c:d5:b4:c7:47 brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::ec0c:d5ff:feb4:c747/64 scope link 
       valid_lft forever preferred_lft forever
```

It looks like the log is emitted here, but no other remediation is attempted in case it occurs: https://github.com/cilium/cilium/blob/8c3672f25d78892773ac0e6a2e226a71cfa00e40/pkg/datapath/loader/loader.go#L771-L789

/cc @dylandreimerink As it may be related to 92abc8f87caac1c8a7b55f45b931f98953ff39b7 (I assume that the link creation event has not been observed/processed at that point yet).

### PR DESCRIPTION
**Pull request by dylandreimerink**
Currently its possible for endpoint datapath initialization to be triggered before the device table has been populated with the endpoint's device. This happens because the CNI plugin creates the device and then makes an API call to the agent to do the rest. The API server and endpoint subsystem do not wait for the device creation event to be processed by the device controller before proceeding with endpoint initialization using the ifindex obtained from the API call.

Most of the time this works fine, but its a race condition that once in a while causes route upserts to fail. When that happens, no error is returned and thus no retry is attempted, leading to missing routes for the endpoint and persistent connectivity issues.

So, for now we will wait for up to 5 seconds for the device to appear in the table before we give up. And if we do fail to upsert routes, we will return an error so that the endpoint initialization is retried.

Long term, we should make the device object part of the endpoint and have the endpoint subsystem wait for its creation instead.

Fixes: #42592

```release-note
Fixed a race condition while trying to create per endpoint routes which could result in connectivity issues
```

### CODE REVIEW

File: pkg/datapath/loader/loader.go
Comment (ti-mo) [inline pkg/datapath/loader/loader.go]: Btw, `logger` is unused in this function.

File: pkg/datapath/loader/loader.go [hunk 1]
```diff
@@ -165,9 +164,28 @@ func upsertEndpointRoute(logger *slog.Logger, db *statedb.DB, devices statedb.Ta
...
+	ctx, cancel := context.WithTimeout(context.Background(), devTableWaitTimeout)
+	defer cancel()
+
+	// Find the device associated with the endpoint. Up to this point we have only got the ifindex
+	// and the table may not yet have been populated with devices. Wait for the device to appear.
+	var epDev *tables.Device
+	for {
+		var found bool
+		var watch <-chan struct{}
+		epDev, _, watch, found = devices.GetWatch(db.ReadTxn(), tables.DeviceIDIndex.Query(ep.GetIfIndex()))
```
Comment (ti-mo) [inline pkg/datapath/loader/loader.go]: Somewhat out of the scope of this PR, but it would be really convenient if GetWatch would take some kind of timeout value or Context so the caller wouldn't be burdened with this kind of logic.

**Review by ti-mo — APPROVED** [review]

File: pkg/datapath/loader/loader.go (hunk 1 above)
Comment (dylandreimerink) [reply pkg/datapath/loader/loader.go]: Well, that is technically not possible. The way stateDB operates is these channels are incorporated in the data structure of the underlying storage. And when the table is modified, it closes channels associated with the nodes that have been modified.

So the GetWatch itself does not block, it returns a channel that closes when the result you got is now possibly invalid due to modifications.

And you don't want to close the channel based on a context passed by one GetWatch, since there may be many observers of the table which would all be triggered if you were to close it.

**Comment by joestringer** [comment]
(Removed the label since tests are not currently passing, but this looks good to merge once those failures are addressed)

File: pkg/datapath/loader/loader.go (hunk 1 above)
Comment (ti-mo) [reply pkg/datapath/loader/loader.go]: I see. In that case, why not lift this logic into a small helper? (here, not in statedb)

Comment (ti-mo) [reply pkg/datapath/loader/loader.go]: I see. In that case, why not lift this logic into a small helper? (here, not in statedb)

**Comment by joestringer** [comment]
Sounds like more of a bug, should this be backported?

**Comment by dylandreimerink** [comment]
> Sounds like more of a bug, should this be backported?

Yea, it only effects v1.19. Was originally marked as misc since we had not branched off yet. But merging has taking so long that by now we need to backport it to that branch.

**Comment by ti-mo** [comment]
I re-ran the tests and labeled `needs-backport/1.19` just in case. If we merge it today, does it really still need to be backported? I'm not super up-to-date on what the branch status is.

**Comment by joestringer** [comment]
Only thing blocking the merge is this comment thread: https://github.com/cilium/cilium/pull/42915#discussion_r2588995556

The v1.19 branch is not yet created. Setting the label is a good way to handle that. When we merge the v1.19 branch prep PR, we'll sweep through `needs-backport/1.19` PRs to account for PRs that made it into the tree before the branch-off.
