### PR TITLE
gateway-api: ALPN support

### LINKED ISSUE #30794: CFP: Gateway API - add ALPN negotiation to cilium-envoy for gRPC support
## Cilium Feature Proposal

`cilium-envoy` is currently missing ALPN config section in the `DownstreamTlsContext` which results in envoy not exposing ALPN [altogether](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/tls.proto#envoy-v3-api-field-extensions-transport-sockets-tls-v3-commontlscontext-alpn-protocols).

The reason why we even need ALPN config is because as per gRPC protocol, clients must use HTTP2 and _they must negotiate ALPN_. While the requirement for HTTP2 is understandable, it's not clear to me why doesn't gRPC allow http2-prior-knowledge (HTTP/2 over a plain TCP connection). grpc/grpc-java#5167 grpc/grpc-java#7201 grpc/grpc-java#5543 This is reproducible throughout most of the platforms: I tried Java, Go, Python, PHP, and all of them fail sending gRPC tls client requests without ALPN.

Supporting ALPN is a very trivial patch to cilium-operator:

```
Index: operator/pkg/model/translation/envoy_listener.go
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/operator/pkg/model/translation/envoy_listener.go b/operator/pkg/model/translation/envoy_listener.go
--- a/operator/pkg/model/translation/envoy_listener.go	(revision 93d4f151799025dfe50b290e2c8f249773f13f9c)
+++ b/operator/pkg/model/translation/envoy_listener.go	(date 1706955589616)
@@ -277,6 +277,7 @@
 	downStreamContext := envoy_extensions_transport_sockets_tls_v3.DownstreamTlsContext{
 		CommonTlsContext: &envoy_extensions_transport_sockets_tls_v3.CommonTlsContext{
 			TlsCertificateSdsSecretConfigs: tlsSdsConfig,
+			AlpnProtocols:                  []string{"h2,http/1.1"},
 		},
 	}
```

It will unbreak gRPC support, but _will break_ backends that do not serve dual HTTP1.1/HTTP2-H2C.

Since envoy is set up with `useDownstreamProtocolConfig` for connecting to upstream backends (i.e pods), it works fine for regular browser requests because without ALPN, browser will choose HTTP1.1 and receive the expected response.

However, if ALPN protocols setting is present (we will need `h2,http/1.1`), then browser will prefer HTTP2 over HTTP1.1, so requests to backends only serving HTTP1.1 will effectively fail with '502 protocol error'.

To address that, I have a suggestion to solve #30452 first.

### PR DESCRIPTION
**Pull request by rauanmayemir**
This feature is hidden behind `enable-gateway-api-alpn` flag on the operator gwapi cell.
The implementation will change envoy listener configuration to expose ALPN suggesting both HTTP/2 and HTTP/1.1.

Fixes: #30794

### CODE REVIEW

File: operator/pkg/model/translation/cec_translator.go [hunk 1]
```diff
@@ -59,14 +60,15 @@ type cecTranslator struct {
 }
 
 // NewCECTranslator returns a new translator
-func NewCECTranslator(secretsNamespace string, useProxyProtocol bool, useAppProtocol bool, hostNameSuffixMatch bool, idleTimeoutSeconds int,
+func NewCECTranslator(secretsNamespace string, useProxyProtocol bool, useAppProtocol bool, useAlpn bool, hostNameSuffixMatch bool, idleTimeoutSeconds int,
```
Comment (sayboras) [inline operator/pkg/model/translation/cec_translator.go]: Originally, we have any a few params, but this list is getting bigger and bigger, wdyt about changing this list to a struct ? We can even extend a little bit more with functional extension pattern (e.g. WithUseAlpn)?

**Review by sayboras — COMMENTED** [review]
One comment as per below, the rest seems reasonable to me. Thanks for your help.

File: operator/pkg/model/translation/cec_translator.go (hunk 1 above)
Comment (rauanmayemir) [reply operator/pkg/model/translation/cec_translator.go]: That would work. Should I only do it for ALPN?

Comment (sayboras) [reply operator/pkg/model/translation/cec_translator.go]: if possible, you can do it in the first commit, the second one will be to support alpn.

Comment (sayboras) [reply operator/pkg/model/translation/cec_translator.go]: ah ignore my above comment, doing it for ALPN is fine, I can do refactor separately.

Comment (rauanmayemir) [reply operator/pkg/model/translation/cec_translator.go]: @sayboras please see if I understood it correctly. I made it togglable like `WithUseAlpn(useAlpn bool)`.

Comment (sayboras) [reply operator/pkg/model/translation/cec_translator.go]: yes, it should be good enough :heavy_check_mark:

**Comment by youngnick** [comment]
The code itself looks good, but I think we should spend some time thinking about what this means for users.

Could you walk through some scenarios for me?

What happens when:

- someone turns this on and is doing other TLS connections over HTTP2?
- someone turns this on and is doing other TLS connections over HTTP1.1 (only)?

Bascially, what I'm trying to think of here are situations where we should call out in the docs how this could break people _before_ they enable it.

**Comment by rauanmayemir** [comment]
@youngnick enabling ALPN doesn't change anything for connections explicitly specifying their protocols, it only plays if client asks for available ALPN protocols (i.e initiates negotiation).

With ALPN exposed, you can exec curl commands with either of `--http1.1`, `--http2` or `--http2-prior-knowledge`, commands will work fine.

It could have broken clients if I negotiated http2, but my client only serves http1.1.
But if you check the helm chart values, enabling ALPN will also enable `appProtocol` support which will opt to use HTTP1.1 by default for upstreams.

We can call out in the docs that if you enable ALPN, it will also enable appProtocol, so if one's upstream is serving HTTP2, they should specify `appProtocol: kubernetes.io/h2c` on their Service specs.

**Comment by rauanmayemir** [comment]
> someone turns this on and is doing other TLS connections over HTTP2?

If their backend is only serving HTTP2 and they don't specify `appProtocol: kubernetes.io/h2c` and they enable ALPN (enabling appProtocol alongside), their requests will fail with 502 protocol error.

(unless they're using GRPCRoute which will force HTTP2 on the upstream whether you have appProtocol or not)

> someone turns this on and is doing other TLS connections over HTTP1.1 (only)?

Nothing will break.

**Comment by rauanmayemir** [comment]
> If their backend is only serving HTTP2 and they don't specify appProtocol: kubernetes.io/h2c and they enable ALPN (enabling appProtocol alongside), their requests will fail with 502 protocol error.

Here, I was talking about hypothetical protocol negotiating scenario. ALPN doesn't change much for this case, because what breaks the traffic flow is enabling appProtocol, not ALPN.

**Comment by rauanmayemir** [comment]
@youngnick Anything else we need for this to go in?

File: install/kubernetes/cilium/values.yaml.tmpl [hunk 2]
```diff
@@ -812,6 +812,8 @@ gatewayAPI:
   enableProxyProtocol: false
   # -- Enable Backend Protocol selection support (GEP-1911) for Gateway API via appProtocol.
   enableAppProtocol: false
+  # -- Enable ALPN for Gateway API.
```
Comment (youngnick) [inline install/kubernetes/cilium/values.yaml.tmpl]:
```suggestion
  # -- Enable ALPN for all listeners configured with Gateway API. ALPN will attempt HTTP/2, then HTTP 1.1. Note that this will also enable `appProtocol` support, and services that wish to use HTTP/2 will need to indicate that via their `appProtocol`.
```
Maybe just to make this one hundred percent clear? Ideally, we would add a tutorial to `Documentation/network/servicemesh/gateway-api/` as well walking through what's required.

**Review by youngnick — CHANGES_REQUESTED** [review]
I think the code is great, but we need to clarify the requirements and behavior a bit more. Any chance you'd be up to write a small tutorial demonstrating how the feature would work? If not, I think we at least need a similar change to what I've asked for below.

File: install/kubernetes/cilium/values.yaml.tmpl (hunk 2 above)
Comment (rauanmayemir) [reply install/kubernetes/cilium/values.yaml.tmpl]: Can we leave the documentation part for a different PR? I would like to actually run this in my env before writing any tutorials. 😅 

Will add the detailed description for the helm values.

**Review by youngnick — APPROVED** [review]
Thanks for the changes, LGTM.

**Comment by rauanmayemir** [comment]
@youngnick those flaky checks again. 😩

File: install/kubernetes/cilium/values.yaml.tmpl (hunk 2 above)
Comment (bardiharborow) [reply install/kubernetes/cilium/values.yaml.tmpl]: Circling back on this, as a user it is fairly unclear which direction the ALPN is in, i.e, client <-> envoy or envoy <-> backend, or both. "listeners" implies the former to me, but "appProtocol" implies the latter. Could we write that tutorial now? 😅

Comment (rauanmayemir) [reply install/kubernetes/cilium/values.yaml.tmpl]: You're right, alpn is for client <-> envoy and appProtocol is for envoy <-> backend. I'll try to free some cycles for this.
