### PR TITLE
pkg/kvstore: fix concurrent access of var in testing

### LINKED ISSUE #16370: [Race Detector] Race in kvstore between `(*EtcdSuite).TestETCDVersionCheck()` and `(*etcdClient).checkMinVersion()`
detected in travis: https://travis-ci.com/github/cilium/cilium/jobs/509173348
```
WARNING: DATA RACE
Write at 0x000001d47760 by goroutine 145:
  github.com/cilium/cilium/pkg/kvstore.(*EtcdSuite).TestETCDVersionCheck()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/kvstore/etcd_test.go:170 +0xa2b
  runtime.call16()
      /home/travis/.gimme/versions/go1.16.4.linux.amd64/src/runtime/asm_amd64.s:550 +0x3d
  reflect.Value.Call()
      /home/travis/.gimme/versions/go1.16.4.linux.amd64/src/reflect/value.go:337 +0xd8
  gopkg.in/check%2ev1.(*suiteRunner).forkTest.func1()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:775 +0xb3b
  gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:669 +0xe1

Previous read at 0x000001d47760 by goroutine 20:
  github.com/cilium/cilium/pkg/kvstore.(*etcdClient).checkMinVersion()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/kvstore/etcd.go:856 +0x1a4
  github.com/cilium/cilium/pkg/kvstore.connectEtcdClient.func3()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/kvstore/etcd.go:770 +0x34f

Goroutine 145 (running) created at:
  gopkg.in/check%2ev1.(*suiteRunner).forkCall()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:666 +0x459
  gopkg.in/check%2ev1.(*suiteRunner).forkTest()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:757 +0x1c4
  gopkg.in/check%2ev1.(*suiteRunner).runTest()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:812 +0x23e
  gopkg.in/check%2ev1.(*suiteRunner).run()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:618 +0x1dc
  gopkg.in/check%2ev1.Run()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/run.go:92 +0x5a
  gopkg.in/check%2ev1.RunAll()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/run.go:84 +0x136
  gopkg.in/check%2ev1.TestingT()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/run.go:72 +0x5ef
  github.com/cilium/cilium/pkg/kvstore.Test()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/kvstore/kvstore_test.go:26 +0x38
  testing.tRunner()
      /home/travis/.gimme/versions/go1.16.4.linux.amd64/src/testing/testing.go:1193 +0x202

Goroutine 20 (running) created at:
  github.com/cilium/cilium/pkg/kvstore.connectEtcdClient()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/kvstore/etcd.go:753 +0xc27
  github.com/cilium/cilium/pkg/kvstore.(*etcdModule).newClient()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/kvstore/etcd.go:246 +0x8ee
  github.com/cilium/cilium/pkg/kvstore.initClient()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/kvstore/client.go:35 +0x1ef
  github.com/cilium/cilium/pkg/kvstore.setupDummyWithConfigOpts()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/kvstore/dummy.go:41 +0x150
  github.com/cilium/cilium/pkg/kvstore.SetupDummy()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/kvstore/dummy.go:21 +0x65
  github.com/cilium/cilium/pkg/kvstore.(*EtcdSuite).SetUpTest()
      /home/travis/gopath/src/github.com/cilium/cilium/pkg/kvstore/etcd_test.go:43 +0x44
  runtime.call16()
      /home/travis/.gimme/versions/go1.16.4.linux.amd64/src/runtime/asm_amd64.s:550 +0x3d
  reflect.Value.Call()
      /home/travis/.gimme/versions/go1.16.4.linux.amd64/src/reflect/value.go:337 +0xd8
  gopkg.in/check%2ev1.(*suiteRunner).runFixture.func1()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:724 +0x1d0
  gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1()
      /home/travis/gopath/src/github.com/cilium/cilium/vendor/gopkg.in/check.v1/check.go:669 +0xe1
```

### PR DESCRIPTION
**Pull request by aanm**
This variable can be accessed with the atomic library and will prevent
the race detector from complaining about concurrent access of this
variable.

Fixes https://github.com/cilium/cilium/issues/16370

### CODE REVIEW

File: pkg/kvstore/etcd.go [hunk 1]
```diff
@@ -84,7 +85,7 @@ var (
 	// versionCheckTimeout is the time we wait trying to verify the version
 	// of an etcd endpoint. The timeout can be encountered on network
 	// connectivity problems.
-	versionCheckTimeout = 30 * time.Second
+	versionCheckTimeout = int64(30 * time.Second)
```
Comment (tklauser) [inline pkg/kvstore/etcd.go:89]: Maybe add a comment that this is to be accessed atomically?

**Review by tklauser — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
hit https://github.com/cilium/cilium/issues/15097 which is fixed
