### PR TITLE
EndpointSlice Conditions semantics: Ready, Serving and Terminating

### LINKED ISSUE #18241: Cilium 1.11 fails the kubernetes e2e test "[sig-network] Services should create endpoints for unready pods"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium 1.11 fails the kubernetes e2e test `[sig-network] Services should create endpoints for unready pods`
https://github.com/kubernetes/kops/pull/12919 is a PR that only changes the default cilium version to 1.11.

The test log can be found at https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/12919/pull-kops-e2e-cni-cilium/1469638304646303744/build-log.txt
The pod logs and config maps can be found at https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kops/12919/pull-kops-e2e-cni-cilium/1469638304646303744/artifacts/cluster-info/kube-system/

### Cilium Version

1.11.0

### Kernel Version

Linux ip-172-20-33-11 5.10.0-9-cloud-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux

### Kubernetes Version

1.23.0

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by aojea**
Fix the usage of the EndpointSlice Conditions semantics: Ready, Serving and Terminating.

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

The EndpointSlice conditions describe 3 states for an Endpoint: Ready, Service and Terminating.

If the Endpoint is Ready it must leverage that value, independently of the other Conditions, this is the reason why the Kubernetes test mentioned in #18241 fails, since using `service.Spec.publishNotReadyAddresses` force this Ready state in the Endpoint.

In addition, Terminating endpoints must be included only of they are Serving, since that indicates that the Endpoint is valid, this state has to be introduced in the API for handling backward compatibility between versions adding an undesired complexity to consumers, so apologize for that 😄 

In KEP https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1669-proxy-terminating-endpoints  we describe the behavior for Terminating Endpoints in case there are no existing Ready endpoints, to allow to implement zero downtime strategies during rolling updates.

Add a job to run Kubernetes sig-network tests, to guarantee that there is no regression and also benefit Cilium of these tests, that should guarantee a standard and conformance behavior with Kubernetes sig-network defined behaviors.

Fixes: #18241

```release-note
Services backends with publishNotReadyAddresses are able to receive traffic independently if they are Terminating, since is the user intent to make them reachable despite its state.
```

### CODE REVIEW

**Comment by aojea** [comment]
/assign @aanm @squeed @aditighag 

I've verified that this commits fixes https://github.com/cilium/cilium/issues/18241, the e2e passes with this patch.

However, I want to add some unit tests and a second commit to fix ProxyTerminatingEndpoints and implement https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1669-proxy-terminating-endpoints per Kubernetes KEP

I'm sending this PR just for  testing the CI and for guidance and early feedback, since is my first contribution to cilium

Thanks

**Comment by sayboras** [comment]
Thanks for your PR.

You probably already see the below page. Also, you can mark this PR as draft if you want. 

PS: Glad to see you here contributing to Cilium, we are heavily using Kind cluster as part our tests ;). The IPv6 related workflow was possible, thanks to your time helping me a few years back :+1:. 

https://docs.cilium.io/en/v1.13/contributing/development/contributing_guide/

**Review by squeed — APPROVED** [review]

**Comment by squeed** [comment]
The [travis failure](https://app.travis-ci.com/github/cilium/cilium/builds/261198614) is legit:
```
    testcase.go:300: lbmap mismatch:
        --- /home/travis/gopath/src/github.com/cilium/cilium/test/controlplane/services/graceful-termination/lbmap2.golden
        +++ <actual>
        @@ -1,15 +1,15 @@
          - Services ---------------------------------------------------------------------
         | ID |                   Name |      Type |               Frontend | Backend IDs |
         |----+------------------------+-----------+------------------------+-------------
         |  0 |     default/kubernetes | ClusterIP |     10.96.0.1:443/NONE |           1 |
         |  1 | test/graceful-term-svc | ClusterIP | 10.96.116.33:8081/NONE |           0 |
          --------------------------------------------------------------------------------
         
        - - Backends -------------------------------------------------
        -| ID |              L3n4Addr |       State | Linked Services |
        -|----+-----------------------+-------------+-----------------
        -|  0 | 10.244.0.112:8081/TCP | terminating |               1 |
        -|  1 |   172.18.0.2:6443/TCP |      active |               0 |
        - ------------------------------------------------------------
        + - Backends --------------------------------------------
        +| ID |              L3n4Addr |  State | Linked Services |
        +|----+-----------------------+--------+-----------------
        +|  0 | 10.244.0.112:8081/TCP | active |               1 |
        +|  1 |   172.18.0.2:6443/TCP | active |               0 |
        + -------------------------------------------------------
```

(You can run these with `go test ./test/controlplane`)

**Comment by aojea** [comment]
ok, let me work a bit more on this, I didn't expect this to be easy 😄  but looks promising

The other tests that fail is the "should reject", I think that cilium drops instead of reject (sending and ICMP or RST), I will disable it by now unless you tell me that there is another knob to enable them

@sayboras is ok to disable kube-proxy completely on the kind configuration or do you rely on it for some tests?

**Comment by sayboras** [comment]
> is ok to disable kube-proxy completely on the kind configuration or do you rely on it for some tests?

Can you clarify more here ? AFAIK, the kind configuration we are using is pretty much simple (i.e. disableDefaultCNI, podSubnet and serviceSubnet)? 

Also, this is a new worklow, so we can start with _sensible_ configuration and take it from there. It means that you can create new configuration which makes sense.

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.26.0
    kubeadmConfigPatches:
      # To make sure that there is no taint for master node.
      # Otherwise additional worker node might be required for conformance testing.
      - |
        apiVersion: kubeadm.k8s.io/v1beta3
        kind: InitConfiguration
        nodeRegistration:
          taints: []
  - role: worker
    image: kindest/node:v1.26.0
networking:
  disableDefaultCNI: true
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.245.0.0/16"
```

**Comment by aojea** [comment]
> Can you clarify more here ? AFAIK, the kind configuration we are using is pretty much simple (i.e. disableDefaultCNI, podSubnet and serviceSubnet)? Is it kubeProxyMode:node ?

yeah, that one

```
diff --git a/.github/kind-config.yaml b/.github/kind-config.yaml
index 359babc607..b2d607a1ef 100644
--- a/.github/kind-config.yaml
+++ b/.github/kind-config.yaml
@@ -17,3 +17,4 @@ networking:
   disableDefaultCNI: true
   podSubnet: "10.244.0.0/16"
   serviceSubnet: "10.245.0.0/16"
+  kubeProxyMode: "none"
```

**Comment by sayboras** [comment]
ah we have used kubeProxyMode in local dev  only but not in CI, I would suggest to create a new kind configuration for your new workflow here. Otherwise, we might spend a lot of time debugging/fixing other CI jobs.

We can merge kind config once things are in better shape and less moving pieces later.

**Comment by aojea** [comment]
@squeed @sayboras how can I make to run the new job with the kind sig-network conformance tests?

**Review by varunmar — APPROVED** [review]
Thanks Antonio!
I reviewed the first two commits, they look good to me.

I'll leave the test one for the cilium maintainers, although I do think it's a good idea to run the conformance tests continuously.

**Comment by sayboras** [comment]
> how can I make to run the new job with the kind sig-network conformance tests?

For first time contributor, Cilium committer needs to trigger CI jobs. I am not sure about the reason behind, but my guess is to save the CI cost in some cases. Once your first PR is merged, general GHA jobs (not using any cloud credentials) will be run automatically.

**Comment by sayboras** [comment]
here is the result of the tests

https://github.com/cilium/cilium/actions/runs/4345547684/jobs/7596997299

```
Summarizing 3 Failures:
  [FAIL] [sig-network] HostPort [It] validates that there is no conflict between pods with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance]
  test/e2e/network/hostport.go:161
  [FAIL] [sig-network] Services [It] should be possible to connect to a service via ExternalIP when the external IP is not assigned to a node
  test/e2e/network/service.go:1355
  [FAIL] [sig-network] Networking [It] should check kube-proxy urls
  test/e2e/framework/network/utils.go:541
```

File: pkg/service/service.go [hunk 1]
```diff
@@ -696,10 +696,16 @@ func (s *Service) upsertService(params *lb.SVC) (bool, lb.ID, error) {
 	// only contain local backends (i.e. it has externalTrafficPolicy=Local)
 	if option.Config.EnableHealthCheckNodePort {
 		if svc.isExtLocal() && filterBackends {
-			_, activeBackends, _ := segregateBackends(backendsCopy)
-
+			// HealthCheckNodePort is used by external systems to poll the state of the Service,
+			// it should never take into consideration Terminating backends.
```
Comment (aditighag) [inline pkg/service/service.go]: This was already skipping `Terminating` backends, but this PR changes the segregateBackends logic a bit. 
nit: I would suggest extending this comment: "it should never take into consideration Terminating backends even when there are only Terminating backends."

File: pkg/service/service.go [hunk 2]
```diff
@@ -1679,6 +1685,8 @@ func isWildcardAddr(frontend lb.L3n4AddrID) bool {
 	return cmtypes.MustParseAddrCluster("0.0.0.0").Equal(frontend.AddrCluster)
 }
 
+// segregateBackends returns the list of active, preferred and nonActive backends to be
+// added to the lbmaps.
```
Comment (aditighag) [inline pkg/service/service.go]: It's an internal function with named returns, so your comment isn't adding anything new. But if you do want to add the comment, let's mention that `activeBackends` may contain `Terminating` backends in some cases.

**Comment by aojea** [comment]
> s, although I do think it's a good idea to run the conformance tests continuously.

this is a a subset and very cheap, we develop KIND to run in CI like this, I really recommend to keep them, I'm happy to attend issues and questions and support that job

**Comment by sayboras** [comment]
> > s, although I do think it's a good idea to run the conformance tests continuously.
> 
> this is a a subset and very cheap, we develop KIND to run in CI like this, I really recommend to keep them, I'm happy to attend issues and questions and support that job

I don't have anything against running it continuously, however, I defer this point to ci-structure and github-sec teams (already here as required reviewers).

**Review by aditighag — CHANGES_REQUESTED** [review]
Thanks a lot for your contribution! 🚀 The first two commits look good to me. Do you mind extending the documentation with a note saying that terminating backends may be considered to service new traffic in some cases - https://github.com/cilium/cilium/blob/master/Documentation/network/kubernetes/kubeproxy-free.rst#graceful-termination? 

>This Serving state must be used to include and endpoint that is
Terminating, not Serving pods should not be used as backends.

Can you please revisit this sentence? Looks like there are typos.

**Comment by aditighag** [comment]
Just making a note here: With per packet LB, we select a new active backend when there is a tuple collision in the conntrack map - https://github.com/cilium/cilium/blob/master/bpf/lib/lb.h#L921. I suppose we could skip selecting a new backend when there a service has only one (terminating) backend by checking service backends count as an optimization.

File: .github/workflows/conformance-k8s-kind.yaml [hunk 3]
```diff
@@ -0,0 +1,194 @@
...
+            --version="
+          HUBBLE_ENABLE_DEFAULTS="--chart-directory=install/kubernetes/cilium \
+            --relay-image=quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/hubble-relay-ci:${SHA} \
+            --relay-version=${SHA}"
+          CONNECTIVITY_TEST_DEFAULTS="--flow-validation=disabled --hubble=false --collect-sysdump-on-failure \
+            --test '!/pod-to-cidr' --external-target bing.com"
+          echo cilium_install_defaults=${CILIUM_INSTALL_DEFAULTS} >> $GITHUB_OUTPUT
+          echo hubble_enable_defaults=${HUBBLE_ENABLE_DEFAULTS} >> $GITHUB_OUTPUT
+          echo connectivity_test_defaults=${CONNECTIVITY_TEST_DEFAULTS} >> $GITHUB_OUTPUT
+          echo sha=${SHA} >> $GITHUB_OUTPUT
```
Comment (sayboras) [inline .github/workflows/conformance-k8s-kind.yaml]: I don't think we run cilium connnectivity test in this workflow, so this can be removed.

File: .github/workflows/conformance-k8s-kind.yaml [hunk 4]
```diff
@@ -0,0 +1,194 @@
...
+
+      - name: Enable Relay
+        run: |
+          cilium hubble enable ${{ steps.vars.outputs.hubble_enable_defaults }}
+
+      - name: Port forward Relay
+        run: |
+          cilium hubble port-forward&
+          sleep 10s
+          [[ $(pgrep -f "cilium.*hubble.*port-forward|kubectl.*port-forward.*hubble-relay" | wc -l) == 2 ]]
```
Comment (sayboras) [inline .github/workflows/conformance-k8s-kind.yaml]: these two steps are required if we run cilium connectivity tests + flow validation, so we can remove them in this workflow.

File: .github/workflows/conformance-k8s-kind.yaml [hunk 5]
```diff
@@ -0,0 +1,194 @@
...
+            --report-dir=${E2E_REPORT_DIR}                \
+            --disable-log-dump=true
+
+      - name: Post-test information gathering
+        if: ${{ !success() }}
+        run: |
+          kubectl get pods --all-namespaces -o wide
+          cilium status
+          cilium sysdump --output-filename cilium-sysdump-final
+          /usr/local/bin/kind export logs --name  ${{ env.cluster_name }} --loglevel=debug ./_artifacts/logs
```
Comment (sayboras) [inline .github/workflows/conformance-k8s-kind.yaml]: this is handy :100:

File: .github/workflows/conformance-k8s-kind.yaml [hunk 6]
```diff
@@ -0,0 +1,194 @@
...
+          name: kind-logs
+          path: ./_artifacts/logs
+          retention-days: 5
+
+      - name: Upload Kubernetes e2e Junit Reports
+        if: ${{ success() }}
+        uses: actions/upload-artifact@v2
+        with:
+          name: kubernetes-e2e-junit
+          path: './_artifacts/*.xml'
```
Comment (sayboras) [inline .github/workflows/conformance-k8s-kind.yaml]: nit: newline

**Review by sayboras — APPROVED** [review]
I don't have other comments apart from what mentioned above on segragate function.

The rest looks good to me with some minor nits/cleanup.

File: pkg/service/service.go (hunk 1 above)
Comment (aojea) [reply pkg/service/service.go]: yeah, that is a good point, you read my intentions perfectly 😄

File: pkg/service/service.go (hunk 2 above)
Comment (aojea) [reply pkg/service/service.go]: absolutely

**Comment by aojea** [comment]
removed the commit with the CI job to a different PR https://github.com/cilium/cilium/pull/24209 and updated addressing comments

**Review by squeed — APPROVED** [review]

File: Documentation/network/kubernetes/kubeproxy-free.rst [hunk 7]
```diff
@@ -1200,6 +1200,11 @@ gracefully. The endpoint state is fully removed when the agent receives
 a Kubernetes delete event for the endpoint. The `Kubernetes
 pod termination <https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination>`_
 documentation contains more background on the behavior and configuration using ``terminationGracePeriodSeconds``.
+There are some special cases, like zero disruption during rolling updates, that require to be able to send traffic
+to Terminating Pods that are still Serving traffic during the Terminating period, the Kubernetes blog
+`Advancements in Kubernetes Traffic Engineering
+<https://kubernetes.io/blog/2022/12/30/advancements-in-kubernetes-traffic-engineering/#traffic-loss-from-load-balancers-during-rolling-updates>`
```
Comment (squeed) [inline Documentation/network/kubernetes/kubeproxy-free.rst]: This needs an underscore after the backtick. Don't ask me why.

e.g.
```
`Foo <https://example.com>`_
```

**Comment by squeed** [comment]
One extraordinarily silly thing, then this should be good to go.

File: Documentation/network/kubernetes/kubeproxy-free.rst (hunk 7 above)
Comment (aojea) [reply Documentation/network/kubernetes/kubeproxy-free.rst]: done

**Review by squeed — APPROVED** [review]

**Review by qmonnet — APPROVED** [review]
Doc change looks good.

Code changes seem good as far as I can tell, although I'm not super familiar with EndpointSlice conditions and only took a brief look.

**Comment by squeed** [comment]
Test failure looks like a flake:

```
Expected command: kubectl exec -n 202303071052k8sdatapathconfighostfirewallwithvxlan testclient-rtvnc -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 [http://192.168.56.11:80/](http://192.168.56.11/) -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 1 
Err: exit status 1
Stdout:
 	 
Stderr:
 	 error: unable to upgrade connection: Authorization error (user=kube-apiserver-kubelet-client, verb=create, resource=nodes, subresource=proxy)
```

**Comment by squeed** [comment]
/test-1.25-4.19

**Comment by squeed** [comment]
All green! Woo!

**Review by aditighag — APPROVED** [review]
🚢 Thanks for the docs update. Reviews are in, and tests passed so marking it as ready for merge.

**Comment by sayboras** [comment]
Reviews from required groups are in, tests are all passed. Merging.

Thanks a lot for your awesome contribution.

**Comment by julianwiedmann** [comment]
@xyll is asking in https://github.com/cilium/cilium/issues/24613 whether this PR should be backported to `v1.12`:

> It describes exactly our case and it is pending to be backported to1.13.2.
> It is possible to backport that to 1.12.X as well to enable smooth upgrade?
> We can run tests and validate images if you publish nightly builds with this patch.

**Comment by aojea** [comment]
> @xyll is asking in #24613 whether this PR should be backported to `v1.12`:
> 
> > It describes exactly our case and it is pending to be backported to1.13.2.
> > It is possible to backport that to 1.12.X as well to enable smooth upgrade?
> > We can run tests and validate images if you publish nightly builds with this patch.

I highly recommend it, the logic was not completely correct and some features like the one referenced by that user are totally broken without it

**Comment by aditighag** [comment]
I agree that we can backport this to 1.12.  @aojea AFAIK, the delta between the master and 1.12 implementation might not be too big. But in case there are conflicts, will you be able to help in resolving the conflicts?

**Comment by aojea** [comment]
> will you be able to help in resolving the conflicts?

absolutely, I joined cilium slack so I can be reachable, but in case I have slow response Casey knows how to contact me

**Comment by xyll** [comment]
Hello!
Do you have maybe the ETA  for the backport to the 1.12?
Thanks!

**Comment by gandro** [comment]
This needs PR needs to be backported manually to v1.12 from someone with expertise in the affected area, as it has non-trivial conflicts against v1.12.

@aojea Would you be able to open a PR against the v1.12 branch?

**Comment by aojea** [comment]
hmm, it interferes with https://github.com/cilium/cilium/pull/21161/, it seems that backporting requires to bring some code that is not necessary  ... it seems that users will have to update to 1.13 :/

**Comment by gandro** [comment]
> 

Thanks for investigating. Yeah, let's remove the backport label for now then.

/cc @squeed

**Comment by ElvinEfendi** [comment]
Does this also fix https://github.com/cilium/cilium/issues/23744?

**Comment by aojea** [comment]
> Does this also fix #23744? It seems like it could.

I expect it, but I don't have time to test it so I can only guess 😄

**Comment by borkmann** [comment]
Hey @aojea :wave: it's been a while on this PR, but I had a follow-up question. Suppose you have the following condition during termination:
```
      ready: false
      serving: false             <----------
      terminating: true
```
This can happen where during termination `serving` flips from `true` to `false` due to ready/liveness probe going down with the initial SIGTERM signal whereas the application in the Pod is still alive though and still able to handle the established traffic. Shouldn't we in this case continue to handle the traffic until the last point up to when the Pod gets the SIGKILL?

(Right now with the PR the current behavior is that as soon as `serving` flips to `false` under `terminating: true` then the established connection breaks. Is this inline with the intended behavior?)

**Comment by aojea** [comment]
> (Right now with the PR the current behavior is that as soon as `serving` flips to `false` under `terminating: true` then the established connection breaks. Is this inline with the intended behavior?)

This is how Cilium works, Cilium implements Services differently than kube-proxy (kube-proxy does not break existing connections), instead, it breaks the connection if is not present in the endpoint more on this in https://github.com/cilium/cilium/issues/23761#issuecomment-1477760382

My thinking based on user feedback is that if we need to generalize, it should work as in this https://github.com/kubernetes/kubernetes/issues/108523#issuecomment-1694521909 in all Services implementations
The main problem is that most likely people is building on top of the existing behaviors, so any change here can always break someone workflow,  but I find "less surprising" to allow existing connections to drain ... and people that wants to break connections they can just remove completely the endpoint, but Services implementations allow the established connections to go through meanwhile "they are aware" there is an endpoint

**Comment by borkmann** [comment]
> > (Right now with the PR the current behavior is that as soon as `serving` flips to `false` under `terminating: true` then the established connection breaks. Is this inline with the intended behavior?)
> 
> This is how Cilium works, Cilium implements Services differently than kube-proxy (kube-proxy does not break existing connections), instead, it breaks the connection if is not present in the endpoint more on this in [#23761 (comment)](https://github.com/cilium/cilium/issues/23761#issuecomment-1477760382)

With the sock LB under KPR, this works as expected. I'm thinking this behavior for the per-packet LB is likely due to skipping !serving:

```
			// filter not Serving endpoints since those can not receive traffic
			if !isServing {
				log.Debugf("discarding Endpoint on EndpointSlice %s: not Serving and EnableK8sTerminatingEndpoint %v", ep.Name, option.Config.EnableK8sTerminatingEndpoint)
				continue
			}
```

Cilium does not terminate established connections when the service entry is removed from the service map, only once the backend is removed as well. So we need to rework this a bit to look at isServing differently.

**Comment by aojea** [comment]
> 
> Cilium does not terminate established connections when the service entry is removed from the service map, only once the backend is removed as well. So we need to rework this a bit to look at isServing differently.

I see, there are different Cilium implementations of Services ... my cilium knowledge is not as deep as my kube-proxy understanding so apologies if I made some wrong assumptions. 

The completely removal of a Service is not something I heard complains or use cases about it, main frictions are with the backend removal, and I think there are two important use cases:
- backend is terminating, IMHO draining is preferrable and what most people expects, but when it stops Serving no new connections allowed
- backend is removed from the service deliberately , my understanding is that people is looking for breaking established connections to implement some sort of A/B deployment
