### PR TITLE
agent:overlay: Add underlayProtocol 'Auto' for automatic underlay selection

### LINKED ISSUE #40877: Ineffective encryption with IPsec + IPv6-only + native routing
There's no ESP traffic being encrypted or going out when running IPsec in an IPv6-only cluster with native routing. 

### Reproduction Steps
```
sudo sysctl -w fs.file-max=1000000
sudo sysctl -w fs.inotify.max_user_instances=1024
export IMAGE=quay.io/cilium/kindest-node:v1.33.0@sha256:03032c2e474eef9d706416a077f2eeb14600653eecbdfada9fc2d81a4e0461f9
key="hmac(sha256) $(dd if=/dev/urandom count=32 bs=1 2> /dev/null| xxd -p -c 64) cbc(aes) $(dd if=/dev/urandom count=32 bs=1 2> /dev/null| xxd -p -c 64)"
kubectl create -n kube-system secret generic cilium-ipsec-keys --from-literal=keys="3 ${key}"
helm install cilium cilium/cilium   --version 1.18.0   --namespace kube-system   --set ipv6.enabled=true   --set ipv4.enabled=false   --set ipam.mode=kubernetes   --set routingMode=native   --set autoDirectNodeRoutes=true   --set ipv6NativeRoutingCIDR=fd00:10:244::/56   --set encryption.enabled=true   --set encryption.type=ipsec
```

Then `tcpdump -ni esp` doesn't show anything and XFRM state counters stay at 0.

### Sysdump

[cilium-sysdump-20250801-180034.zip](https://github.com/user-attachments/files/21551376/cilium-sysdump-20250801-180034.zip)

### PR DESCRIPTION
**Pull request by smagnani96**
Superseeds https://github.com/cilium/cilium/pull/42861.

Please refer to commit messages:

1. Add new default `underlayProtocol: "auto"`. This will allow Cilium to automatically pick an enabled underlay as protocol (IPv4 first, otherwise IPv6). The change is transparent to all users who do not explicitly define `underlayProtocol`.
2. Prohibit setting a disabled `underlayProtocol`. Prior to this, Cilium did not throw any error, but it was using the wrong TunnelOverhead while computing routeMTU for pods in pkg/mtu.

Fixes: #40877.

### CODE REVIEW

File: pkg/datapath/tunnel/tunnel.go [hunk 1]
```diff
@@ -88,7 +93,16 @@ func newConfig(in newConfigIn) (Config, error) {
...
 	switch UnderlayProtocol(in.Cfg.UnderlayProtocol) {
-	case IPv4, IPv6:
+	case IPv4:
+		if !in.DaemonCfg.EnableIPv4 {
+			in.Logger.Info("Selected underlay IPv4 is disabled, switching to IPv6.")
+			in.Cfg.UnderlayProtocol = string(IPv6)
+		}
+	case IPv6:
+		if !in.DaemonCfg.EnableIPv6 {
+			in.Logger.Info("Selected underlay IPv6 is disabled, switching to IPv4.")
```
Comment (pchaigno) [inline pkg/datapath/tunnel/tunnel.go]: Should this be a warning so people can update their configmap accordingly and we don't switch on every restart?

**Review by pchaigno — APPROVED** [review]

File: pkg/datapath/tunnel/tunnel.go (hunk 1 above)
Comment (smagnani96) [reply pkg/datapath/tunnel/tunnel.go]: Are you suggesting to KEEP the switching logic but log this as Warning? If so, I agree. Otherwise I don't, I'd still want something to happen to avoid wrong MTU computation. Agent failure would've been my 1st option, but that would cause problems to users with a valid IPV6-only+NativeRouting config (see discussion https://github.com/cilium/cilium/pull/42861#issuecomment-3551959763).

Comment (pchaigno) [reply pkg/datapath/tunnel/tunnel.go]: > Are you suggesting to KEEP the switching logic but log this as Warning?

Yes.

Comment (smagnani96) [reply pkg/datapath/tunnel/tunnel.go]: Done. Thanks for clarifying!

Comment (smagnani96) [reply pkg/datapath/tunnel/tunnel.go]: Changing log to Warn makes `ci-clustermesh` [fail](https://github.com/cilium/cilium/actions/runs/20858980298/job/59933379371).
That of course happened in [NativeRoutingIPv6](https://github.com/cilium/cilium/blob/pr/smagnani96/overlay-switch-underlay/.github/workflows/conformance-clustermesh.yaml#L164-L176) where tunneling is disabled. We should still specify the correct underlay to not receive the warning.
That warning makes our CI to fail.
Added a new commit to this PR.

**Review by marseel — APPROVED** [review]

**Comment by marseel** [comment]
I've added `wait-until-release` for now to give a chance for Joe to take a look.
I know that you went through all PRs last week  @joestringer but I wasn't sure if you meant that it's fine to merge after rebase or not.

**Comment by joestringer** [comment]
This seemed to me like a bugfix but I wasn't sure how risky it was. Given that, I was hesitant to mark it for v1.18 backport. It could be pulled into the tree before v1.19, then if we do end up needing to revert or add another fix, we could do so early in the v1.19 maintenance cycle.

Note that if we do want this in v1.19, there will be some time (Release ETA start of Feb, see [milestones discussion](https://github.com/cilium/cilium/discussions/41523)); if it goes in ~now then it would be automatically part of v1.19. In the next couple of days we will branch for v1.19, so if it doesn't land before then we would need to backport to the branch.

File: pkg/datapath/tunnel/tunnel.go [hunk 2]
```diff
@@ -88,7 +93,16 @@ func newConfig(in newConfigIn) (Config, error) {
 	}
 
 	switch UnderlayProtocol(in.Cfg.UnderlayProtocol) {
-	case IPv4, IPv6:
+	case IPv4:
+		if !in.DaemonCfg.EnableIPv4 {
+			in.Logger.Warn("Selected underlay IPv4 is disabled, switching to IPv6.")
+			in.Cfg.UnderlayProtocol = string(IPv6)
+		}
```
Comment (joestringer) [inline pkg/datapath/tunnel/tunnel.go:111]: Did you consider just returning an error here?

As a general configuration problem, when the user explicitly asks for option A && option B, we should validate the combination and either accept or reject it. However if the user doesn't explicitly ask for this combination, it is reasonable to autodetect an option.

The concern I would have with this pattern specifically is if the user explicitly selected `--helm-set=underlayProtocol=ipv6` and did not enable IPv6, they might continue to operate Cilium assuming that the underlay uses IPv6 (as they have configured) and only later realize that Cilium overrode their configuration to work differently. That is surprising behavior, and generally speaking users don't love to be surprised.

Comment (smagnani96) [reply pkg/datapath/tunnel/tunnel.go:111]: My favorite option would be to return error, so that users are well aware of what needs to be set/changed.
However, in https://github.com/cilium/cilium/pull/42861#issuecomment-3551959763 Julian had the following concern:

> Just saying that IPv6-only with native-routing has been a valid config for a long time, and all those folks would need to fix-up their config now (the underlay-protocol config option only exists since v1.18)

And that's because the default value would be `underlayProtocol: ipv4`, even though these users are in IPv6-only clusters. It's also a bit controversial to me that users need to specify the correct underlay even though they're in NativeRouting, but apparently we still do use it in `pkg/mtu` [here](https://github.com/cilium/cilium/blob/main/pkg/mtu/cell.go#L88-L96) and [here](https://github.com/cilium/cilium/blob/main/pkg/mtu/mtu.go#L91-L95).

I'm super open for any kind of suggestions. Don't know what's the preferred way to go in such cases 😃

Comment (joestringer) [reply pkg/datapath/tunnel/tunnel.go:111]: Could we have an `underlayProtocol: auto` that picks ipv4 or ipv6 (in that order), based on which protocols are enabled in the config? If we then set that as the default, it should generally have the right behavior, but then for dual-stack environments the user could choose to opt in to a specific underlay. Then we could still error out if explicitly configured the wrong way.

Comment (smagnani96) [reply pkg/datapath/tunnel/tunnel.go:111]: The `auto` solution sounds good, don't see any issue ATM. Tomorrow I'll give it a try, thanks Joe 💯

Comment (smagnani96) [reply pkg/datapath/tunnel/tunnel.go:111]: My "Tomorrow" has a two-weeks lag 😁 
Just updated the PR with the `auto` solution.

**Comment by smagnani96** [comment]
I just updated the PR accordingly to Joe's [suggestion](https://github.com/cilium/cilium/pull/43057#discussion_r2683315350).

The new default underlay value is `Auto`.
Second commit additionally prohibits to set a disabled underlay.

The change is transparent to all those users not previously defining `underlayProtocol:`. In case they were explicitly setting it, please be aware that 2nd commit will make sure their underlay is enabled.

**Review by pchaigno — APPROVED** [review]
In general, I'm a bit wary of `auto` flags as it tends to create an unstable environment for users, but in this case, it's only dependent on other config flags, so I think we should be fine.

**Comment by smagnani96** [comment]
Had to force-push again to pick up Helm and Doc-related changes I forgot to push before 😞

**Review by qmonnet — APPROVED** [review]
Ack for doc change, thanks!

**Review by joestringer — APPROVED** [review]

**Review by gandro — APPROVED** [review]
