### PR TITLE
 ipcache/metadata: flatten metadata once on read 

### LINKED ISSUE #40134: CI: ci-e2e-upgrade: timed out waiting for policy updates to be processed: panic: runtime error in pkg/ipcache
```
2025-06-19T09:13:42.560077701Z 	/go/src/github.com/cilium/cilium/pkg/ipcache/metadata.go:1000 +0x1ec
2025-06-19T09:13:42.560449556Z github.com/cilium/cilium/pkg/controller.(*controller).runController(0xc0031729a0)
2025-06-19T09:13:42.561113976Z 	/go/src/github.com/cilium/cilium/pkg/controller/controller.go:333 +0x1c7
2025-06-19T09:13:42.561730457Z created by github.com/cilium/cilium/pkg/controller.(*Manager).createControllerLocked in goroutine 610
2025-06-19T09:13:42.561954215Z 	/go/src/github.com/cilium/cilium/pkg/controller/manager.go:124 +0x4ae
  ❌ Error finalizing 'client-egress-to-cidr-deny': timed out waiting for policy updates to be processed on Cilium agents: command failed (pod=kube-system/cilium-t44br, container=cilium-agent): command terminated with exit code 1: "Error: cannot list endpoints: Get \"http://localhost/v1/endpoint\": dial unix /var/run/cilium/cilium.sock: connect: connection refused\nIs the agent running?\n\n"
🔍 Collecting sysdump with cilium-cli version: 857761f7, args: [connectivity test --include-unsafe-tests --collect-sysdump-on-failure --conn-disrupt-test-restarts-path ./cilium-conn-disrupt-restarts --conn-disrupt-test-xfrm-errors-path ./cilium-conn-disrupt-xfrm-errors --flush-ct --sysdump-hubble-flows-count=1000000 --sysdump-hubble-flows-timeout=5m --sysdump-output-filename cilium-sysdump-conn-disrupt-test-cilium-upgrade-2-concurrent-<ts> --junit-file cilium-junits/conn-disrupt-test-cilium-upgrade-2-concurrent.xml --junit-property github_job_step=Run conn disrupt tests (cilium-upgrade-2-concurrent) --log-code-owners --code-owners=CODEOWNERS --exclude-code-owners=@cilium/github-sec --test !seq-.* --test-concurrency=5 --expected-xfrm-errors +inbound_no_state]

```

https://github.com/cilium/cilium/actions/runs/15753959815/job/44405066318

### PR DESCRIPTION
**Pull request by squeed**
The ipcache aggregates metadata for a given prefix by resource. When
determining the ultimate metadata, it loops through all the
resource-level metadata to determine the value for each property.

This changes the code to flatten all the metadata once. It serves two
purposes:

1. It fixes a race condition, where we performed metadata reads
       without holding the ipcache metadata lock. Since the values were
       updated in-place, this caused races. Specifically, if a resource was
       deleted for a prefix while injection was happening, this caused
       nil panics.
2. It prevents needless prefix updates when multiple resources all
   provide the same information. This is particularly prevalent for CIDR
   labels.

As a further optimization, if a given metadata update would not change
the flattened metadata, then we short-cut the prefix update and save an
ipcache iteration.

This includes another commit which fixes an awkward usage of the metadata data that interacted poorly with this change.

Fixes: https://github.com/cilium/cilium/issues/40134
Fixes: https://github.com/cilium/cilium/commit/495164abb76c49cb1cb2c855a31555cac8102a6c

### CODE REVIEW

File: pkg/ipcache/metadata.go [hunk 1]
```diff
@@ -221,9 +221,12 @@ func canonicalPrefix(prefixCluster cmtypes.PrefixCluster) cmtypes.PrefixCluster
 	return cmtypes.NewPrefixCluster(p, clusterID)
 }
 
+// upsertLocked inserts / updates the set of metadata associated with this resource for this prefix.
+// It returns the set of affected prefixes. It may return nil if
```
Comment (bimmlerd) [inline pkg/ipcache/metadata.go]: nit: unfinished sentence in comment

File: pkg/ipcache/types.go [hunk 2]
```diff
@@ -194,211 +245,202 @@ func (s *prefixInfo) sortedBySourceThenResourceID() []ipcachetypes.ResourceID {
...
 			} else {
-				requestedID = info.requestedIdentity
+				out.requestedIdentity = info.requestedIdentity
 				requestedIDResourceID = resourceID
 			}
 		}
 
-		if info.endpointFlags.IsValid() {
-			if endpointFlags.IsValid() {
+		// TODO: if there are ever more flags, merge them
```
Comment (bimmlerd) [inline pkg/ipcache/types.go]: nit: leftover TODO?

File: pkg/ipcache/types.go [hunk 3]
```diff
@@ -194,211 +245,202 @@ func (s *prefixInfo) sortedBySourceThenResourceID() []ipcachetypes.ResourceID {
...
 }
 
-func (s *prefixInfo) EncryptKey() ipcachetypes.EncryptKey {
-	for rid := range s.byResource {
-		if k := s.byResource[rid].encryptKey; k.IsValid() {
-			return k
-		}
+func (r *resourceInfo) EncryptKey() ipcachetypes.EncryptKey {
+	if r == nil {
+		return 0
```
Comment (bimmlerd) [inline pkg/ipcache/types.go]: should this be `ipcachetypes.EncryptKeyEmpty?`

File: pkg/ipcache/types.go [hunk 4]
```diff
@@ -194,211 +245,202 @@ func (s *prefixInfo) sortedBySourceThenResourceID() []ipcachetypes.ResourceID {
...
 }
 
-func (s *prefixInfo) RequestedIdentity() ipcachetypes.RequestedIdentity {
-	for _, rid := range s.sortedBySourceThenResourceID() {
-		if id := s.byResource[rid].requestedIdentity; id.IsValid() {
-			return id
-		}
+func (r *resourceInfo) RequestedIdentity() ipcachetypes.RequestedIdentity {
+	if r == nil {
+		return 0
```
Comment (bimmlerd) [inline pkg/ipcache/types.go]: similarly here; `ipcachetypes.RequestedIdentity(identity.InvalidIdentity)`?

File: pkg/ipcache/metadata_test.go [hunk 5]
```diff
@@ -1274,7 +1207,7 @@ func Test_metadata_mergeParentLabels(t *testing.T) {
 			existing: map[string]labels.Labels{
 				"1.1.0.0/16": labels.ParseLabelArray("cidr:1.1.0.0/16", "reserved:world-ipv4", "cidrgroup:foo=yes").Labels(),
 			},
-			prefix:     "::ffff:1.1.1.1/24",
```
Comment (bimmlerd) [inline pkg/ipcache/metadata_test.go:1277]: what's the reason for these prefix test changes?

File: pkg/k8s/watchers/endpoints.go [hunk 6]
```diff
@@ -138,31 +143,22 @@ func (k *K8sEndpointsWatcher) addKubeAPIServerServiceEndpoints(eps *k8s.Endpoint
...
-	//     an update event.
-	//   * if the entire object is deleted, then it will quickly be recreated
-	//     and this will be in the form of an add event.
-	k.ipcache.RemoveLabelsExcluded(
-		labels.LabelKubeAPIServer,
-		desiredIPs,
-		rid,
-	)
+	// remove stale IPs
+	for ip := range k.existingAPIServers.Members() {
```
Comment (bimmlerd) [inline pkg/k8s/watchers/endpoints.go]: Is this really equivalent to what was there before?
Here, we remove the label from all existing and not desired IPs and below add it to all desired but not known IPs. But the previous logic would look through _all_ IPs and remove the label from there unless desired. Can there not be some way (maybe restoration?) where an IP has that label without being present in either existing nor desired?

**Review by bimmlerd — CHANGES_REQUESTED** [review]
few nits in first pass; but this feels rather non-trivial for how late in the cycle we are and I don't feel confident in being the only @cilium/ipcache eyes on it; so if someone else form the team could take a look :pray: 

You also mention a race; could you spell that out a bit more explicitly for me so I can retrace it and understand how it's fixed now?

File: pkg/k8s/watchers/endpoints.go [hunk 7]
```diff
@@ -53,6 +55,9 @@ type K8sEndpointsWatcher struct {
 	k8sAPIGroups *k8sSynced.APIGroups
 	resources    agentK8s.Resources
 
+	// The set of already-upserted IPs with the API server label.
+	existingAPIServers set.Set[cmtypes.PrefixCluster]
```
Comment (christarazi) [inline pkg/k8s/watchers/endpoints.go]: Maybe a comment explaining the assumption for why a lock is needed not here (because k8s events should be serialized so there shouldn't be another thread writing to `existingAPIServers`)

File: pkg/k8s/watchers/endpoints.go (hunk 6 above)
Comment (christarazi) [reply pkg/k8s/watchers/endpoints.go]: Hmm, in the original logic, the code checked all prefixes labeled with `kube-apiserver`. The modified version now only considers prefixes that Cilium receives directly from k8s. While these two approaches are slightly different in scope of IPs considered, the actual content should be identical, so there shouldn’t be any functional difference.

The only potential distinction is that the previous logic might have, _in theory_, included additional IPs if they were tagged with the `kube-apiserver` label. However, I can't think of any realistic scenario where Kubernetes-related IPs would come from a source other than what Cilium gets from Kubernetes itself.

File: pkg/ipcache/metadata.go [hunk 8]
```diff
@@ -264,14 +264,26 @@ func (ipc *IPCache) GetMetadataSourceByPrefix(prefix cmtypes.PrefixCluster) sour
...
 }
 
-func (m *metadata) getLocked(prefix cmtypes.PrefixCluster) prefixInfo {
-	return m.m[canonicalPrefix(prefix)]
+// getLocked returns a deep copy of the flattened prefix info
+func (m *metadata) getLocked(prefix cmtypes.PrefixCluster) *resourceInfo {
+	if pi, ok := m.m[canonicalPrefix(prefix)]; ok {
+		if pi.flattened == nil {
+			// re-compute the flattened set of prefixes
+			pi.flattened = pi.flatten(m.logger.With(
```
Comment (joestringer) [inline pkg/ipcache/metadata.go]: Is it OK for multiple goroutines to grab the read lock, enter the critical section, and attempt to update the `pi.flattened` cache here?

File: pkg/ipcache/types.go [hunk 9]
```diff
@@ -194,211 +245,202 @@ func (s *prefixInfo) sortedBySourceThenResourceID() []ipcachetypes.ResourceID {
...
+					if exists && !otherLabel.DeepEqual(&newLabel) {
+						scopedLog.Warn(
+							"Detected conflicting label for prefix. "+
+								"This may cause connectivity issues for this address.",
+							logfields.Labels, out.labels,
+							logfields.ConflictingLabels, otherLabel,
+						)
+					} else if !exists {
+						out.labels[key] = newLabel
+					}
```
Comment (christarazi) [inline pkg/ipcache/types.go]: So now labels are being merged in this `flatten` function. Are we sure we have allocated a new identity for these label changes then?

**Review by christarazi — COMMENTED** [review]
I like the direction of this PR, I had considered something like this previously recently so nice to see it happening now. I have a few comments on top of David's review.

File: pkg/ipcache/types.go [hunk 10]
```diff
@@ -186,208 +245,202 @@ func (s prefixInfo) sortedBySourceThenResourceID() []ipcachetypes.ResourceID {
...
 
-func (s prefixInfo) Source() source.Source {
-	src := source.Unspec
-	for _, v := range s {
-		if source.AllowOverwrite(src, v.source) {
-			src = v.source
-		}
+func (r *resourceInfo) Source() source.Source {
+	if r == nil {
+		return ""
```
Comment (joestringer) [inline pkg/ipcache/types.go]: nit: Use `source.Unspec` due to the special `AllowOverwrite()` behavior for the unspec vs. empty string.
```suggestion
		return source.Unspec
```

File: pkg/ipcache/types.go [hunk 11]
```diff
@@ -186,208 +245,202 @@ func (s prefixInfo) sortedBySourceThenResourceID() []ipcachetypes.ResourceID {
...
+			if len(out.labels) > 0 {
+				// merge labels, complaining if the value exists
+				for key, newLabel := range info.labels {
+					otherLabel, exists := out.labels[key]
+					if exists && !otherLabel.DeepEqual(&newLabel) {
+						scopedLog.Warn(
+							"Detected conflicting label for prefix. "+
+								"This may cause connectivity issues for this address.",
+							logfields.Labels, out.labels,
+							logfields.ConflictingLabels, otherLabel,
```
Comment (joestringer) [inline pkg/ipcache/types.go]: nit: Can we include the conflicting resourceIDs in this log message too? I'm imagining that debugging this issue would be a lot easier if the source of the conflicting label sets was declared in the log message.

File: pkg/ipcache/types.go (hunk 2 above)
Comment (joestringer) [reply pkg/ipcache/types.go]: I think this comment probably belongs in `pkg/ipcache/types/types.go` instead, where the `EndpointFlags` structure is declared. Otherwise future writers adding a new endpoint flag may not fully appreciate that this function also needs to be updated.

I'd phrase this not as `TODO` (which implies that there is known work to do right now) but rather as an instruction to the developer changing `EndpointFlags` that they must also evaluate how a new flag should impact flattening of prefixInfo in `pkg/ipcache`.

File: pkg/ipcache/types_test.go [hunk 12]
```diff
@@ -59,3 +66,225 @@ func Test_sortedByResourceIDsAndSource(t *testing.T) {
...
+	}
+
+	for i, test := range tests {
+		t.Run(strconv.Itoa(i), func(t *testing.T) {
+			logger := hivetest.Logger(t)
+			logger.Info("warnings are expected here")
+			pi := newPrefixInfo()
+
+			pi.byResource["before"] = test.before
+			pi.byResource["after"] = test.after
```
Comment (joestringer) [inline pkg/ipcache/types_test.go]: nit: The use of "before" and "after" here may confuse future readers, since the ResourceID concept in `pkg/ipcache` is not about time or change but about multiple conflicting sources of truth being de-conflicted by the `flatten()` call. I think it would reinforce a more accurate view of the corresponding code if the test cases just used `resourceA`, `resourceB` or even more use-case oriented cases like using actual resource IDs like `cnp/cidr-policy-a` or `daemon/fqdn-name-manager/cilium.io` or such.

File: pkg/ipcache/types.go (hunk 9 above)
Comment (joestringer) [reply pkg/ipcache/types.go]: The callpath should be `resolveIdentity()` -> `mergeParentLabels()` -> `getLocked()` -> `flatten()`, then after the `mergeParentLabels()` there is the allocation. Looks OK to me through that path. Is there another path you're concerned about?

**Review by joestringer — COMMENTED** [review]
One locking question, the rest are nits.

Main question I'm wondering about beyond this PR is just whether to hold the v1.18.0-rc.0 until we merge this or not. This could provide more time for users to try out this new codepath prior to the v1.18.0 final release. Thoughts?

File: pkg/ipcache/types.go (hunk 9 above)
Comment (christarazi) [reply pkg/ipcache/types.go]: No other code path; just wanted to double check we aren't missing anything. :+1:

File: pkg/ipcache/metadata.go (hunk 8 above)
Comment (squeed) [reply pkg/ipcache/metadata.go]: no, not even remotely safe :see_no_evil:. Thanks to the specifics of the logic, this was not causing a data race, but it's a bad look. I'll fix it.

In fact, we can probably just drop the lock to a standard Mutex; the access patterns don't really make sense for a RWMutex. There aren't actually any other readers besides the label injection controller, which is how this didn't cause any issues.

File: pkg/k8s/watchers/endpoints.go (hunk 6 above)
Comment (squeed) [reply pkg/k8s/watchers/endpoints.go]: This is a good point. Rather than dig through all the possibilities, I'll drop this commit. It was a nice-to-have anyways.

File: pkg/ipcache/metadata_test.go (hunk 5 above)
Comment (squeed) [reply pkg/ipcache/metadata_test.go:1277]: These prefixes weren't in the ipcache metadata layer for the tests. Thanks to some laziness around how the code treated labels, this worked, even though the actual `*prefixInfo` was nil.

The actual, production ipcache label-resolving code will *never* try and determine the set of labels for a prefix with no metadata, so this change to the test code is valid.

**Comment by squeed** [comment]
> Main question I'm wondering about beyond this PR is just whether to hold the v1.18.0-rc.0 until we merge this or not. 

@joestringer Good question. The answer isn't clear. How many -rc releases were you hoping to cut? I would definitely like to either see this in the release, or revert the entire FQDN pre-allocation code. The race here is a ticking time bomb.

I think merging this will be cleaner than reverting all of the FQDN changes. So, I suppose I have a weak vote for "delay rc.0 for a day or two". I'll have an updated version addressing feedback in a few hours.

**Comment by joestringer** [comment]
@squeed :+1: Makes sense to me yep. We're planning two RCs, two weeks apart, with the full release in about a month's time. The full [milestones list](https://github.com/cilium/cilium/discussions/39217) is pinned in the discussions tab.

File: pkg/ipcache/types.go (hunk 11 above)
Comment (squeed) [reply pkg/ipcache/types.go]: Sure, just have to map every label key to the resources that supplied it.

Comment (joestringer) [reply pkg/ipcache/types.go]: It's probably enough to just add the last resourceID for labels on the stack like the other stack variables for resource IDs?

Comment (squeed) [reply pkg/ipcache/types.go]: Indeed, we just need to map per key.

File: pkg/ipcache/metadata.go (hunk 8 above)
Comment (squeed) [reply pkg/ipcache/metadata.go]: Converted the mutex to a standard one.

**Comment by squeed** [comment]
> You also mention a race; could you spell that out a bit more explicitly for me so I can retrace it and understand how it's fixed now?

I updated the description a bit, but the race was thus:

1. the reader would lock, retrieve the `prefixInfo`, then unlock. `prefixInfo` is, however, a map so the returned value is a pointer
2. while the reader is looping over the set of resources in `prefixInfo`, another writer removes one of the resources
3. There is now concurrent reading and writing to the same map, leading to races and, sometimes, nil pointers.

File: pkg/ipcache/types.go (hunk 2 above)
Comment (joestringer) [reply pkg/ipcache/types.go]: Unmarked as "resolved" as this comment was not yet resolved. Feel free to follow up on this in a separate PR if there's no other requested changes, but please do remove this. 

As-is the TODO will highly likely be overlooked by anyone attempting to make such a change. That's not to mention that TODOs almost always get completely ignored even if they're tagged with a specific owner. Generally speaking, if there's a TODO, we should either do it or resolve that the TODO is not important and skip the pretense that someone might do it by adding a comment to the tree.

Comment (joestringer) [reply pkg/ipcache/types.go]: (Reading further I see the suggestion above was taken, but the TODO is still here. I suggest just dropping the TODO.)
```suggestion
```

**Review by joestringer — APPROVED** [review]
Latest version LGTM. One minor nit about not adding a `TODO` comment.

I dug through the users of the Lock and I agree that the RWMutex seems unnecessary and overoptimizing given the current ipcache usage patterns. Switching to a Mutex looks unlikely to cause a regression as far as I can tell.

**Comment by squeed** [comment]
Whoops. Changed the TODO to a short note. CI was green with zero flakes :-). Let's see if it stays that way.

File: pkg/ipcache/types.go [hunk 13]
```diff
@@ -186,208 +245,207 @@ func (s prefixInfo) sortedBySourceThenResourceID() []ipcachetypes.ResourceID {
...
+						"Detected conflicting identity override for prefix. "+
+							"This may cause connectivity issues for this address.",
+						logfields.Labels, out.labels,
+						logfields.Resource, overrideResourceID,
+						logfields.ConflictingLabels, info.labels,
+						logfields.ConflictingResource, resourceID,
+					)
+				} else {
+					out.identityOverride = true
+					out.labels = info.labels
```
Comment (gandro) [inline pkg/ipcache/types.go:375]: If we have an identity override, we must not merge any additional labels into `out.labels`. I think this is no longer the case with the new implementation, since we'll continue to merge the next `info.labels` into `out.labels` without checking if `out.identityOverride` is set.

**Review by gandro — CHANGES_REQUESTED** [review]

File: pkg/ipcache/types.go (hunk 13 above)
Comment (squeed) [reply pkg/ipcache/types.go:375]: oh, very good catch!

Comment (squeed) [reply pkg/ipcache/types.go:375]: fixed and added a test case, PTAL

**Review by gandro — APPROVED** [review]
Thanks, LGTM now!

File: pkg/ipcache/types.go (hunk 13 above)
Comment (squeed) [reply pkg/ipcache/types.go:375]: This makes me wonder if we have a cilium-cli CI test case that uses this.

Comment (gandro) [reply pkg/ipcache/types.go:375]: I don't think we do. The original user was/is external workloads, for which we removed support in the Cilium CLI a while a go. The code in Cilium CNI has been deprecated but not yet removed to my knowledge.

Apparently we also use the feature in the code below, maybe for that particular case there's another solution, so we can get rid of this override function completely

https://github.com/cilium/cilium/blob/a719911acb08f86a815159ee296b9046b45a767d/daemon/cmd/hostips-sync.go#L202

Comment (gandro) [reply pkg/ipcache/types.go:375]: Ah, so apparently external workload has been removed from Cilium CNI also: https://github.com/cilium/cilium/pull/37418

But the code overwriting the identity based on node labels hasn't, though I pretty sure this is dead code:
https://github.com/cilium/cilium/blob/ae12c40e4dab35deeda941ed55f7b0c7ecc5980b/pkg/node/manager/manager.go#L626-L629

**Comment by squeed** [comment]
CI is green :). Just a review needed for logfields changes.

**Review by tklauser — APPROVED** [review]
Ack on behalf of @cilium/cli for the logfields change. Didn't review the rest in-depth.

**Comment by squeed** [comment]
I'll let @bimmlerd give this another pass, then this should be good.
