### PR TITLE
Test: Add size mismatch log entry to failed ones.

### LINKED ISSUE #7851: CI: fail test if any "mismatch" log messages are present
This ensures we do not merge changes which break seamless datapath upgrade.

### PR DESCRIPTION
**Pull request by eloycoto**
Fail if size mismatch is found in the logs after executing the test.

Fix #7851

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7852)

### CODE REVIEW

**Comment by eloycoto** [comment]
test-me-please

File: test/helpers/cons.go [hunk 1]
```diff
@@ -197,6 +197,7 @@ const (
 	segmentationFault = "segmentation fault"        // from https://github.com/cilium/cilium/issues/3233
 	NACKreceived      = "NACK received for version" // from https://github.com/cilium/cilium/issues/4003
 	RunInitFailed     = "JoinEP: "                  // from https://github.com/cilium/cilium/pull/5052
+	sizeMismatch      = "size-mismatch"             // from https://github.com/cilium/cilium/issues/7851
```
Comment (ianvernon) [inline test/helpers/cons.go]: I was unclear in my issue description :/ sorry about that. This should be a search for "size mismatch for BPF map" instead:

https://github.com/cilium/cilium/blob/7881196da7be4d8b90458098f9cdcdbc5f3d0296/pkg/bpf/bpf_linux.go#L316

https://github.com/cilium/cilium/blob/7881196da7be4d8b90458098f9cdcdbc5f3d0296/pkg/bpf/bpf_linux.go#L324

**Review by ianvernon — CHANGES_REQUESTED** [review]

**Comment by eloycoto** [comment]
test-me-please

File: test/helpers/cons.go (hunk 1 above)
Comment (brb) [reply test/helpers/cons.go]: We should search for https://github.com/cilium/cilium/blob/7881196da7be4d8b90458098f9cdcdbc5f3d0296/pkg/bpf/bpf_linux.go#L339 and https://github.com/cilium/cilium/blob/7881196da7be4d8b90458098f9cdcdbc5f3d0296/pkg/bpf/bpf_linux.go#L332.

I haven't seen any key/value size mismatch in CI logs.

**Comment by ianvernon** [comment]
test-me-please

File: test/helpers/cons.go (hunk 1 above)
Comment (ianvernon) [reply test/helpers/cons.go]: Welp, I was wrong (again)! Sorry for the churn, @eloycoto - thanks for clarifying, @brb .

**Comment by ianvernon** [comment]
@aanm why was this merged? The comments weren't addressed.

**Comment by aanm** [comment]
> @aanm why was this merged? The comments weren't addressed.

@ianvernon which comments?

**Comment by ianvernon** [comment]
@aanm https://github.com/cilium/cilium/pull/7852#discussion_r278961783
