### PR TITLE
endpoint: signal when BPF program is compiled for the first time

### LINKED ISSUE #5859: Endpoint is not ready in istio test
***Summary***: Endpoint on Istio test does not get in ready state after timeout

Fail
```
home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:383
Endpoints are not ready after timeout
Expected
    <*helpers.SSHMetaError | 0xc424e670e0>: Error: Timeout reached: Endpoints are not ready after timeout
Extended info: 	Cilium Pod: cilium-5dvq5 	Endpoint: 3154 	Identity: 4	 State: ready
	Cilium Pod: cilium-5dvq5 	Endpoint: 10271 	Identity: 27690	 State: ready
	Cilium Pod: cilium-5dvq5 	Endpoint: 23570 	Identity: 62332	 State: ready
	Cilium Pod: cilium-5dvq5 	Endpoint: 28293 	Identity: 128	 State: ready
	Cilium Pod: cilium-5dvq5 	Endpoint: 30015 	Identity: 128	 State: ready
	Cilium Pod: cilium-5dvq5 	Endpoint: 30128 	Identity: 129	 State: ready
	Cilium Pod: cilium-5dvq5 	Endpoint: 30540 	Identity: 21151	 State: ready
	Cilium Pod: cilium-5dvq5 	Endpoint: 33196 	Identity: 37219	 State: ready
	Cilium Pod: cilium-5dvq5 	Endpoint: 62365 	Identity: 35029	 State: ready
	Cilium Pod: cilium-5dvq5 	Endpoint: 64728 	Identity: 29638	 State: ready
	Cilium Pod: cilium-ssdw9 	Endpoint: 8465 	Identity: 7130	 State: ready
	Cilium Pod: cilium-ssdw9 	Endpoint: 8570 	Identity: 40569	 State: ready
	Cilium Pod: cilium-ssdw9 	Endpoint: 10008 	Identity: 43158	 State: ready
	Cilium Pod: cilium-ssdw9 	Endpoint: 16757 	Identity: 44364	 State: not-ready
	Cilium Pod: cilium-ssdw9 	Endpoint: 20133 	Identity: 128	 State: ready
	Cilium Pod: cilium-ssdw9 	Endpoint: 22232 	Identity: 63832	 State: ready
	Cilium Pod: cilium-ssdw9 	Endpoint: 24347 	Identity: 28966	 State: ready
	Cilium Pod: cilium-ssdw9 	Endpoint: 28818 	Identity: 32336	 State: ready
	Cilium Pod: cilium-ssdw9 	Endpoint: 30313 	Identity: 29492	 State: ready
	Cilium Pod: cilium-ssdw9 	Endpoint: 33009 	Identity: 128	 State: ready
	Cilium Pod: cilium-ssdw9 	Endpoint: 39371 	Identity: 46782	 State: ready
	Cilium Pod: cilium-ssdw9 	Endpoint: 42140 	Identity: 4	 State: ready
	Cilium Pod: cilium-ssdw9 	Endpoint: 64117 	Identity: 11734	 State: ready
```

Full output: 
```
Number of 'context deadline exceeded' in logs: 4
⚠️  Number of 'level=error' in logs: 8
⚠️  Number of 'level=warning' in logs: 11
Number of 'Cilium API handler panicked' in logs: 0
⚠️  Number of 'Goroutine took lock for more than' in logs: 115
Cilium pods: [cilium-5dvq5 cilium-ssdw9]
Netpols loaded: 
CiliumNetworkPolicies loaded: default::cnp-second-namespace default::cnp-specs default::istio-sidecar 
Endpoint Policy Enforcement:
     cilium-etcd-bskkvd6dtz                      =>   none
     istio-galley-5664cf4486-thmwz               =>   none
     istio-telemetry-5c7b4697dd-9z8qk            =>   none
     istio-sidecar-injector-7ddfb55469-2cdbx     =>   none
     cilium-etcd-98nkhhwqnm                      =>   none
     etcd-operator-7cb79cdf99-f4fjq              =>   none
     istio-egressgateway-7d4f6d4ccd-lbsv5        =>   none
     istio-policy-746f846dd5-4bsq9               =>   none
     cilium-etcd-s2g7cd7j47                      =>   none
     prometheus-core-5888d94764-vb6q2            =>   none
     details-v1-5f85dc9586-nb49h                 =>   ingress
     reviews-v2-57456d49fb-tl55p                 =>   none
     reviews-v1-769dc8c876-86snt                 =>   none
     istio-citadel-657777464f-vmk4w              =>   none
     istio-ingressgateway-5c4cf57d59-wkbpv       =>   none
     istio-pilot-84bc576c97-dtwx4                =>   none
     istio-statsd-prom-bridge-67bbcc746c-k8fmk   =>   none
     prometheus-6967c997cf-4llnw                 =>   none
     productpage-v1-5bdbc7dbb8-7tkgw             =>   none
     ratings-v1-85c7c99486-7cfrc                 =>   ingress
     coredns-65b788cf-tsjks                      =>   none
Cilium agent 'cilium-5dvq5': Status: Ok  Health: Ok Nodes "k8s2 k8s1" ContinerRuntime: Ok Kubernetes: Ok KVstore: Ok Controllers: Total 78 Failed 0
Cilium agent 'cilium-ssdw9': Status: Ok  Health: Ok Nodes "k8s1 k8s2" ContinerRuntime: Ok Kubernetes: Ok KVstore: Ok Controllers: Total 89 Failed 0

Standard Error

STEP: Creating the istio-system namespace
STEP: Creating the Istio resources
STEP: Waiting for Istio pods to be ready
STEP: Waiting for Istio service "istio-statsd-prom-bridge" to be ready
STEP: Waiting for Istio service "istio-pilot" to be ready
STEP: Waiting for DNS to resolve Istio service "istio-statsd-prom-bridge"
STEP: Waiting for DNS to resolve Istio service "istio-pilot"
STEP: Creating policy in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/istio-sidecar-init-policy.yaml"
STEP: Creating policy in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/cnp-specs.yaml"
STEP: Creating resources in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/bookinfo-v2-istio.yaml"
STEP: Creating resources in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/bookinfo-v1-istio.yaml"
STEP: Waiting for Bookinfo pods to be ready
STEP: Waiting for Bookinfo endpoints to be ready
=== Test Finished at 2018-10-11T07:38:14Z====
===================== TEST FAILED =====================
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE      NAME                                        READY   STATUS      RESTARTS   AGE     IP              NODE   NOMINATED NODE
	 default        details-v1-5f85dc9586-nb49h                 2/2     Running     1          8m34s   10.10.0.124     k8s1   <none>
	 default        productpage-v1-5bdbc7dbb8-7tkgw             2/2     Running     0          8m34s   10.10.1.154     k8s2   <none>
	 default        ratings-v1-85c7c99486-7cfrc                 2/2     Running     0          8m35s   10.10.0.50      k8s1   <none>
	 default        reviews-v1-769dc8c876-86snt                 2/2     Running     0          8m34s   10.10.1.104     k8s2   <none>
	 default        reviews-v2-57456d49fb-tl55p                 2/2     Running     0          8m35s   10.10.0.74      k8s1   <none>
	 istio-system   istio-citadel-657777464f-vmk4w              1/1     Running     0          11m     10.10.0.113     k8s1   <none>
	 istio-system   istio-cleanup-secrets-2tgxx                 0/1     Completed   0          11m     10.10.1.87      k8s2   <none>
	 istio-system   istio-egressgateway-7d4f6d4ccd-lbsv5        1/1     Running     0          11m     10.10.1.77      k8s2   <none>
	 istio-system   istio-galley-5664cf4486-thmwz               1/1     Running     0          11m     10.10.0.77      k8s1   <none>
	 istio-system   istio-ingressgateway-5c4cf57d59-wkbpv       1/1     Running     0          11m     10.10.1.172     k8s2   <none>
	 istio-system   istio-pilot-84bc576c97-dtwx4                2/2     Running     0          11m     10.10.1.204     k8s2   <none>
	 istio-system   istio-policy-746f846dd5-4bsq9               2/2     Running     0          11m     10.10.1.250     k8s2   <none>
	 istio-system   istio-security-post-install-8j9qv           0/1     Completed   5          11m     10.10.0.49      k8s1   <none>
	 istio-system   istio-sidecar-injector-7ddfb55469-2cdbx     1/1     Running     0          11m     10.10.0.153     k8s1   <none>
	 istio-system   istio-statsd-prom-bridge-67bbcc746c-k8fmk   1/1     Running     0          11m     10.10.0.162     k8s1   <none>
	 istio-system   istio-telemetry-5c7b4697dd-9z8qk            2/2     Running     0          11m     10.10.0.223     k8s1   <none>
	 istio-system   prometheus-6967c997cf-4llnw                 1/1     Running     0          11m     10.10.0.22      k8s1   <none>
	 kube-system    cilium-5dvq5                                1/1     Running     0          57m     192.168.36.12   k8s2   <none>
	 kube-system    cilium-etcd-98nkhhwqnm                      1/1     Running     0          57m     10.10.0.238     k8s1   <none>
	 kube-system    cilium-etcd-bskkvd6dtz                      1/1     Running     0          56m     10.10.0.189     k8s1   <none>
	 kube-system    cilium-etcd-s2g7cd7j47                      1/1     Running     0          57m     10.10.1.248     k8s2   <none>
	 kube-system    cilium-ssdw9                                1/1     Running     0          57m     192.168.36.11   k8s1   <none>
	 kube-system    coredns-65b788cf-tsjks                      1/1     Running     0          58m     10.10.1.80      k8s2   <none>
	 kube-system    etcd-k8s1                                   1/1     Running     0          84m     192.168.36.11   k8s1   <none>
	 kube-system    etcd-operator-7cb79cdf99-f4fjq              1/1     Running     0          58m     10.10.1.197     k8s2   <none>
	 kube-system    kube-apiserver-k8s1                         1/1     Running     0          84m     192.168.36.11   k8s1   <none>
	 kube-system    kube-controller-manager-k8s1                1/1     Running     0          84m     192.168.36.11   k8s1   <none>
	 kube-system    kube-proxy-cwsx9                            1/1     Running     0          85m     192.168.36.11   k8s1   <none>
	 kube-system    kube-proxy-nlw5k                            1/1     Running     0          78m     192.168.36.12   k8s2   <none>
	 kube-system    kube-scheduler-k8s1                         1/1     Running     0          84m     192.168.36.11   k8s1   <none>
	 monitoring     prometheus-core-5888d94764-vb6q2            1/1     Running     0          77m     10.10.1.24      k8s2   <none>
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-5dvq5 -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                                    IPv6                   IPv4          STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                                                      
	 3154       Disabled           Disabled          4          reserved:health                                                                f00d::a0a:100:0:c52    10.10.1.42    ready   
	 10271      Disabled           Disabled          27690      k8s:app=istio-ingressgateway                                                   f00d::a0a:100:0:281f   10.10.1.172   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                    
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=istio-ingressgateway-service-account                                                
	                                                            k8s:io.kubernetes.pod.namespace=istio-system                                                                                
	                                                            k8s:istio=ingressgateway                                                                                                    
	 23570      Disabled           Disabled          62332      k8s:app=policy                                                                 f00d::a0a:100:0:5c12   10.10.1.250   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                    
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=istio-mixer-service-account                                                         
	                                                            k8s:io.kubernetes.pod.namespace=istio-system                                                                                
	                                                            k8s:istio-mixer-type=policy                                                                                                 
	                                                            k8s:istio=mixer                                                                                                             
	 28293      Disabled           Disabled          128        container:annotation.etcd.version=3.3.9                                        f00d::a0a:100:0:6e85   10.10.1.248   ready   
	                                                            k8s:app=etcd                                                                                                                
	                                                            k8s:etcd_cluster=cilium-etcd                                                                                                
	                                                            k8s:etcd_node=cilium-etcd-s2g7cd7j47                                                                                        
	                                                            k8s:io.cilium.fixed-identity=kv-store                                                                                       
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                    
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                             
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                                                 
	 30015      Disabled           Disabled          128        k8s:io.cilium.fixed-identity=kv-store                                          f00d::a0a:100:0:753f   10.10.1.197   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                    
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=cilium-etcd-sa                                                                      
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                                                 
	                                                            k8s:name=etcd-operator                                                                                                      
	 30128      Disabled           Disabled          129        k8s:io.cilium.fixed-identity=kube-dns                                          f00d::a0a:100:0:75b0   10.10.1.80    ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                    
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=coredns                                                                             
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                                                 
	                                                            k8s:k8s-app=kube-dns                                                                                                        
	 30540      Disabled           Disabled          21151      k8s:app=istio-egressgateway                                                    f00d::a0a:100:0:774c   10.10.1.77    ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                    
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=istio-egressgateway-service-account                                                 
	                                                            k8s:io.kubernetes.pod.namespace=istio-system                                                                                
	                                                            k8s:istio=egressgateway                                                                                                     
	 33196      Disabled           Disabled          37219      k8s:app=productpage                                                            f00d::a0a:100:0:81ac   10.10.1.154   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                    
	                                                            k8s:io.cilium.k8s.policy.istiosidecarproxy=true                                                                             
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                             
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                                     
	                                                            k8s:track=stable                                                                                                            
	                                                            k8s:version=v1                                                                                                              
	                                                            k8s:zgroup=bookinfo                                                                                                         
	 62365      Disabled           Disabled          35029      k8s:app=pilot                                                                  f00d::a0a:100:0:f39d   10.10.1.204   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                    
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=istio-pilot-service-account                                                         
	                                                            k8s:io.kubernetes.pod.namespace=istio-system                                                                                
	                                                            k8s:istio=pilot                                                                                                             
	 64728      Disabled           Disabled          29638      k8s:app=reviews                                                                f00d::a0a:100:0:fcd8   10.10.1.104   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                    
	                                                            k8s:io.cilium.k8s.policy.istiosidecarproxy=true                                                                             
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                             
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                                     
	                                                            k8s:track=stable                                                                                                            
	                                                            k8s:version=v1                                                                                                              
	                                                            k8s:zgroup=bookinfo                                                                                                         
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-5dvq5 -- cilium bpf proxy list
Exitcode: 0 
Stdout:
 	 KEY   VALUE   
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-ssdw9 -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                                      IPv6                 IPv4          STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                                                      
	 8465       Disabled           Disabled          7130       k8s:app=reviews                                                                  f00d::a0a:0:0:2111   10.10.0.74    ready       
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                        
	                                                            k8s:io.cilium.k8s.policy.istiosidecarproxy=true                                                                                 
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                                 
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                                         
	                                                            k8s:version=v2                                                                                                                  
	                                                            k8s:zgroup=bookinfo                                                                                                             
	 8570       Disabled           Disabled          40569      k8s:io.cilium.k8s.policy.cluster=default                                         f00d::a0a:0:0:217a   10.10.0.77    ready       
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=istio-galley-service-account                                                            
	                                                            k8s:io.kubernetes.pod.namespace=istio-system                                                                                    
	                                                            k8s:istio=galley                                                                                                                
	 10008      Disabled           Disabled          43158      k8s:io.cilium.k8s.policy.cluster=default                                         f00d::a0a:0:0:2718   10.10.0.162   ready       
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=istio-mixer-service-account                                                             
	                                                            k8s:io.kubernetes.pod.namespace=istio-system                                                                                    
	                                                            k8s:istio=statsd-prom-bridge                                                                                                    
	 16757      Enabled            Disabled          44364      k8s:app=details                                                                  f00d::a0a:0:0:4175   10.10.0.124   not-ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                        
	                                                            k8s:io.cilium.k8s.policy.istiosidecarproxy=true                                                                                 
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                                 
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                                         
	                                                            k8s:track=stable                                                                                                                
	                                                            k8s:version=v1                                                                                                                  
	                                                            k8s:zgroup=bookinfo                                                                                                             
	 20133      Disabled           Disabled          128        container:annotation.etcd.version=3.3.9                                          f00d::a0a:0:0:4ea5   10.10.0.189   ready       
	                                                            k8s:app=etcd                                                                                                                    
	                                                            k8s:etcd_cluster=cilium-etcd                                                                                                    
	                                                            k8s:etcd_node=cilium-etcd-bskkvd6dtz                                                                                            
	                                                            k8s:io.cilium.fixed-identity=kv-store                                                                                           
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                        
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                                 
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                                                     
	 22232      Disabled           Disabled          63832      k8s:app=prometheus                                                               f00d::a0a:0:0:56d8   10.10.0.22    ready       
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                        
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=prometheus                                                                              
	                                                            k8s:io.kubernetes.pod.namespace=istio-system                                                                                    
	 28818      Enabled            Disabled          32336      k8s:app=ratings                                                                  f00d::a0a:0:0:7092   10.10.0.50    ready       
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                        
	                                                            k8s:io.cilium.k8s.policy.istiosidecarproxy=true                                                                                 
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                                 
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                                         
	                                                            k8s:version=v1                                                                                                                  
	                                                            k8s:zgroup=bookinfo                                                                                                             
	 30313      Disabled           Disabled          29492      k8s:app=telemetry                                                                f00d::a0a:0:0:7669   10.10.0.223   ready       
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                        
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=istio-mixer-service-account                                                             
	                                                            k8s:io.kubernetes.pod.namespace=istio-system                                                                                    
	                                                            k8s:istio-mixer-type=telemetry                                                                                                  
	                                                            k8s:istio=mixer                                                                                                                 
	 33009      Disabled           Disabled          128        container:annotation.etcd.version=3.3.9                                          f00d::a0a:0:0:80f1   10.10.0.238   ready       
	                                                            k8s:app=etcd                                                                                                                    
	                                                            k8s:etcd_cluster=cilium-etcd                                                                                                    
	                                                            k8s:etcd_node=cilium-etcd-98nkhhwqnm                                                                                            
	                                                            k8s:io.cilium.fixed-identity=kv-store                                                                                           
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                        
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                                 
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                                                     
	 39371      Disabled           Disabled          46782      k8s:io.cilium.k8s.policy.cluster=default                                         f00d::a0a:0:0:99cb   10.10.0.113   ready       
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=istio-citadel-service-account                                                           
	                                                            k8s:io.kubernetes.pod.namespace=istio-system                                                                                    
	                                                            k8s:istio=citadel                                                                                                               
	 42140      Disabled           Disabled          4          reserved:health                                                                  f00d::a0a:0:0:a49c   10.10.0.242   ready       
	 64117      Disabled           Disabled          11734      k8s:io.cilium.k8s.policy.cluster=default                                         f00d::a0a:0:0:fa75   10.10.0.153   ready       
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=istio-sidecar-injector-service-account                                                  
	                                                            k8s:io.kubernetes.pod.namespace=istio-system                                                                                    
	                                                            k8s:istio=sidecar-injector                                                                                                      
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-ssdw9 -- cilium bpf proxy list
Exitcode: 0 
Stdout:
 	 KEY   VALUE   
	 
Stderr:
 	 

===================== Existing AfterFailed =====================
STEP: Deleting resource in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/bookinfo-v2-istio.yaml"
STEP: Deleting resource in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/bookinfo-v1-istio.yaml"
STEP: Deleting policy in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/istio-sidecar-init-policy.yaml"
STEP: Deleting policy in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/cnp-specs.yaml"
STEP: Deleting the Istio resources
STEP: Deleting the istio-system namespace

[[ATTACHMENT|75421305_K8sIstioTest_Istio_Bookinfo_Demo_Tests_bookinfo_inter-service_connectivity.zip]]
```

Link: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/4368/testReport/k8s-1/12/K8sIstioTest_Istio_Bookinfo_Demo_Tests_bookinfo_inter_service_connectivity/
Logs: 
[75421305_K8sIstioTest_Istio_Bookinfo_Demo_Tests_bookinfo_inter-service_connectivity.zip](https://github.com/cilium/cilium/files/2468228/75421305_K8sIstioTest_Istio_Bookinfo_Demo_Tests_bookinfo_inter-service_connectivity.zip)

### PR DESCRIPTION
**Pull request by ianvernon**
The Istio CI test has been unstable because of behavior in some pods where, if DNS fails to resolve, before the BPF program for the pod is installed, even after the pod has a BPF program installed, it will not be able to connect to the DNS server to resolve DNS again until the pod restarts.

Prior to this change, if Cilium is running in tandem with Istio, we returned before the BPF program was installed for the endpoint to avoid deadlock when configuring Envoy. To ensure that this sort of behavior in pods does not occur again, return from endpoint creation if the endpoint has been determined to be Istio-injected, and has a BPF program installed.

This PR adds a channel which is closed once the initial BPF compilation has occurred for an endpoint. The state of this channel is used to determine if a BPF program has been compiled for the endpoint.
    
Fixes: #5859
    
Signed-off by: Ian Vernon <ian@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5869)

### CODE REVIEW

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Review by rlenglet — APPROVED** [review]

**Comment by ianvernon** [comment]
runtime tests failed because gofmt complained (I am running with v1.11 of go):
```
23:14:00     runtime: contrib/scripts/check-fmt.sh
23:14:02     runtime: Unformatted Go source code:
23:14:02     runtime: ./pkg/endpoint/endpoint.go
23:14:02     runtime: diff -u ./pkg/endpoint/endpoint.go.orig ./pkg/endpoint/endpoint.go
23:14:02     runtime: --- ./pkg/endpoint/endpoint.go.orig	2018-10-11 23:14:00.852875475 +0000
23:14:02     runtime: +++ ./pkg/endpoint/endpoint.go	2018-10-11 23:14:00.852875475 +0000
23:14:02     runtime: @@ -2067,8 +2067,8 @@
23:14:02     runtime:  		e.getLogger().WithFields(logrus.Fields{
23:14:02     runtime:  			logfields.EndpointState + ".from": fromState,
23:14:02     runtime:  			logfields.EndpointState + ".to":   toState,
23:14:02     runtime: -			"file":                            fileName,
23:14:02     runtime: -			"line":                            fileLine,
23:14:02     runtime: +			"file": fileName,
23:14:02     runtime: +			"line": fileLine,
23:14:02     runtime:  		}).Info("Invalid state transition skipped")
23:14:02     runtime:  	}
23:14:02     runtime:  	e.logStatusLocked(Other, Warning, fmt.Sprintf("Skipped invalid state transition to %s due to: %s", toState, reason))
23:14:02     runtime: Makefile:231: recipe for target 'precheck' failed
```

Will fix and reupload.

**Comment by ianvernon** [comment]
test-me-please

File: daemon/endpoint.go [hunk 1]
```diff
@@ -271,7 +271,7 @@ func (h *putEndpointID) Handle(params PutEndpointIDParams) middleware.Responder
 				hasSidecarProxy := e.HasSidecarProxy()
 				e.RUnlock()
 
-				if hasSidecarProxy {
+				if hasSidecarProxy && e.HasBPFProgram() {
```
Comment (tgraf) [inline daemon/endpoint.go:274]: Does this need a timeout?

**Review by tgraf — DISMISSED** [review]

File: daemon/endpoint.go (hunk 1 above)
Comment (tgraf) [reply daemon/endpoint.go:274]: Where does it actually block until the BPF program is ready?

Comment (ianvernon) [reply daemon/endpoint.go:274]: This is still WIP. I will mark it as ready for review when it is ready.

Comment (ianvernon) [reply daemon/endpoint.go:274]: To answer your question - the logic in `endpoint.HasBPFProgram()` returns true if the channel is closed, false otherwise (which is achieved via `select`). It shouldn't be blocking. The line you commented on, 274 is within a for loop. If `e.HasBPFProgram()` returns false, the for loop will iterate again. This blocks until the BPF program is ready.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build successful: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7206

Running again a few more times to see if the Istio test changes are stable.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Rebased to master, and reverted the disabling of the Istio test.

**Comment by ianvernon** [comment]
test-me-please

File: pkg/endpoint/endpoint.go [hunk 2]
```diff
@@ -694,10 +715,11 @@ func (e *Endpoint) RunK8sCiliumEndpointSync() {
...
 	ep := &Endpoint{
-		ID:      ID,
-		Options: option.NewIntOptions(&EndpointMutableOptionLibrary),
-		Status:  NewEndpointStatus(),
-		state:   state,
+		ID:            ID,
+		Options:       option.NewIntOptions(&EndpointMutableOptionLibrary),
+		Status:        NewEndpointStatus(),
+		state:         state,
+		hasBPFProgram: make(chan struct{}, 0),
```
Comment (tgraf) [inline pkg/endpoint/endpoint.go:738]: Is the channel leaked if the endpoint is created but never built?

File: daemon/state.go [hunk 3]
```diff
@@ -216,6 +216,8 @@ func (d *Daemon) regenerateRestoredEndpoints(state *endpointRestoreState) {
 				return
 			}
 
+			ep.CreateBPFProgramChannel()
```
Comment (tgraf) [inline daemon/state.go]: The channel is leaked when the endpoint generation fails and the endpoint is never built again.

**Review by tgraf — CHANGES_REQUESTED** [review]

File: daemon/state.go (hunk 3 above)
Comment (ianvernon) [reply daemon/state.go]: By “leaked” do you mean that it persists even if the endpoint is deleted ? Does GC not take effect in that case? If the endpoint is never rebuilt , then its BPF program hasn’t been compiled and the channel is still open.

Comment (tgraf) [reply daemon/state.go]: It will persist if anyone is blocking on it. If no references exist anymore, gc will eventually remove it. The current code is all non-blocking but this is a potentially very hard to find memory leak as it assumes that nobody ever blocks on the channel while the endpoint is deleted for a build that has failed.

Comment (ianvernon) [reply daemon/state.go]: Added code which closes the channel on endpoint deletion to ensure that the channel is GC'd when the endpoint is removed and that no one is blocking on it. Also removed the exported function to create the channel, and instead set its value internally within the Endpoint package. Let me know if this is what you had in mind.

**Comment by ianvernon** [comment]
test-me-please

**Review by tgraf — DISMISSED** [review]

**Comment by ianvernon** [comment]
The Istio tests failed with my change :(

**Comment by ianvernon** [comment]
Build failed: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7232

The previous istio-proxy container from the ratings pod (`pod-default-ratings-v1-666fb56bf4-h64rb-istio-proxy-previous.log` in the log archive for the build) couldn't resolve an IP via DNS:
```
2018-10-12T19:16:17.538295085Z 2018-10-12T19:16:17.538187Z	info	Version root@localhost-docker.io/istio-ba018d0ddf819f36a3e3c8d0e494b2743ea1387c-ba018d0ddf819f36a3e3c8d0e494b2743ea1387c-Clean
2018-10-12T19:16:17.538354705Z 2018-10-12T19:16:17.538239Z	info	Proxy role: model.Proxy{ClusterID:"", Type:"sidecar", IPAddress:"10.10.1.248", ID:"ratings-v1-666fb56bf4-h64rb.default", Domain:"default.svc.cluster.local", Metadata:map[string]string(nil)}
2018-10-12T19:16:17.538368838Z 2018-10-12T19:16:17.538252Z
```

This caused it to crash eventually:

```
2018-10-12T19:19:57.422014616Z [2018-10-12 19:19:57.421][57][critical][main] external/envoy/source/server/server.cc:78] error initializing configuration '/etc/istio/proxy/envoy-rev0.json': malformed IP address: istio-statsd-prom-bridge.istio-system
2018-10-12T19:19:57.423592255Z [2018-10-12 19:19:57.423][57][info][main] external/envoy/source/server/server.cc:449] exiting
2018-10-12T19:19:57.425185612Z 2018-10-12T19:19:57.425022Z	warn	Epoch 0 terminated with an error: exit status 1
2018-10-12T19:19:57.425203632Z 2018-10-12T19:19:57.425047Z	warn	Aborted all epochs
2018-10-12T19:19:57.425206Z 2018-10-12T19:19:57.425069Z	error	Permanent error: budget exhausted trying to fulfill the desired configuration
2018-10-12T19:19:57.425257099Z 2018-10-12T19:19:57.425074Z	error	cannot start the proxy with the desired configuration
2018-10-12T19:19:57.42526041Z 2018-10-12T19:19:57.425086Z	error	
```

I tried looking at the microscope output at this time to see why the DNS request was dropped, but couldn't find any drops nor traces. It turns out that the microscope pod is started *after* the pods are started, meaning we have no logs from the bootstrapping of the istio-proxy at this time:

```
[2018-10-12 19:17:34] ['cilium', 'monitor', '--json']
[2018-10-12 19:17:34] 2018-10-12 19:17:34,363 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2460)'))': /api/v1/namespaces/kube-system/pods/cilium-dmdsz
[2018-10-12 19:17:34] 
```

I changed the ordering of this in the test to start the microscope within the `Context`. Trying again to see if we can reproduce and get more logs, and also doing more analysis of the above failure locally.

**Comment by ianvernon** [comment]
test-me-please

**Comment by rlenglet** [comment]
Istio test passed:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7236/
Starting a new build.

**Comment by rlenglet** [comment]
test-me-please

**Review by aanm — DISMISSED** [review]
This doesn't have to be a channel as you are not using any features provided by the channel. Since you've similar functions to "set/get" you can use `atomic.StoreInt32` with 0 that represents "no-bpf-program" and 1 that represents "has-bpf-program".

Also, in `daemon/endpoint.go:L251` there's the following comment:
```
// Wait for any successful BPF regeneration, which is indicated by any
// positive policy revision (>0). As long as at least one BPF
// regeneration is successful, the endpoint has network connectivity
// so we can return from the creation API call.
```

So, why do we need to "re-check" there's a bpf program if `revCh` already signalizes that?

**Comment by rlenglet** [comment]
@aanm we can't wait for a complete regeneration in this case, because it would deadlock with the sidecar proxy configuration. That's why this signals specifically that a BPF program has been installed, NOT for a regeneration to be complete.

**Comment by rlenglet** [comment]
> This doesn't have to be a channel as you are not using any features provided by the channel.

We just needed a boolean state that can be checked and updated atomically. Why not a channel?

**Comment by rlenglet** [comment]
Istio test failed in latest CI build:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7238/execution/node/94/log/
Some pods don't get ready.

The Bookinfo pods are created at 00:03:34:
```
STEP: Creating resources in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/bookinfo-v2-istio.yaml"
time="2018-10-13T00:03:34Z" level=debug msg="creating /home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/bookinfo-v2-istio.yaml"
```

This time, microscope was started beforehand, as intended:
```
$ head -n 1 monitor.log 
[2018-10-13 00:03:31] ['cilium', 'monitor', '--json']
```

The last check for the Bookinfo endpoints' status happens at 00:10:47:
```
time="2018-10-13T00:10:47Z" level=debug msg="running command: kubectl exec -n kube-system cilium-gvqjs -- uptime"
cmd: "kubectl exec -n kube-system cilium-gvqjs -- cilium endpoint list -o json" exitCode: 0 duration: 1.038864896s stdout:
```

Only `cilium-gvqjs` sees a non-`ready` endpoint (1 out of 15):
```
$ grep 'Waiting for cilium endpoints to be ready' test-output.log | grep -v invalid=0
time="2018-10-13T00:05:48Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:05:52Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:05:57Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:06:02Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:06:07Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:06:12Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:06:17Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:06:22Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:06:27Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:06:32Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:06:37Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:06:42Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:06:47Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:06:52Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:06:57Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:07:02Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:07:07Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:07:12Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:07:17Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:07:22Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:07:27Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:07:32Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:07:37Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:07:42Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:07:48Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:07:52Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:07:57Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:08:03Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:08:08Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:08:12Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:08:17Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:08:22Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:08:27Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:08:32Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:08:37Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:08:42Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:08:47Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:08:52Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:08:57Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:09:02Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
time="2018-10-13T00:09:07Z" level=info msg="Waiting for cilium endpoints to be ready" invalid=1 pod=cilium-gvqjs total=15
...
```

The non-`ready` pod is `details`. It has endpoint ID `45657`, and got identity `18539` from the start.
It failed its first generation:
```
      "log": [
        {
          "code": "Failure",
          "message": "Error regenerating endpoint: Error while configuring proxy redirects: proxy state changes failed: context deadline exceeded",
          "state": "ready",
          "timestamp": "2018-10-13T00:05:37Z"
        }
      ],
```

```
$ grep '"Regenerating endpoint"\|"Regeneration of endpoint failed"\|"Completed endpoint regeneration"' pod-kube-system-cilium-gvqjs-cilium-agent.log | grep endpointID=45657
2018-10-13T00:03:37.359294859Z level=info msg="Regenerating endpoint" containerID=e371be61ab datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=45657 ipv4=10.10.1.20 ipv6="f00d::a0a:100:0:b259" k8sPodName=/ reason="updated security labels" startTime="2018-10-13 00:03:37.358708101 +0000 UTC m=+263.843410608" subsys=endpoint
2018-10-13T00:04:40.348690305Z level=warning msg="Regeneration of endpoint failed" bpfCompilation=3.298946308s buildDuration=1m2.9898967s containerID=e371be61ab datapathPolicyRevision=0 desiredPolicyRevision=25 endpointID=45657 error="Error while configuring proxy redirects: proxy state changes failed: context deadline exceeded" ipv4=10.10.1.20 ipv6="f00d::a0a:100:0:b259" k8sPodName=default/details-v1-7994657c46-svzcw mapSync="690.735µs" policyCalculation=1.77174ms prepareBuild="434.067µs" proxyConfiguration="68.741µs" proxyPolicyCalculation=2.35365ms proxyWaitForAck=51.700818314s reason="updated security labels" subsys=endpoint waitingForCTClean=0s waitingForLock=7.980379964s
2018-10-13T00:04:42.378058118Z level=info msg="Regenerating endpoint" containerID=e371be61ab datapathPolicyRevision=0 desiredPolicyRevision=25 endpointID=45657 ipv4=10.10.1.20 ipv6="f00d::a0a:100:0:b259" k8sPodName=default/details-v1-7994657c46-svzcw reason="one or more identities created or deleted" startTime="2018-10-13 00:04:42.377742767 +0000 UTC m=+328.862445273" subsys=endpoint
2018-10-13T00:05:37.40914177Z level=warning msg="Regeneration of endpoint failed" bpfCompilation=0s buildDuration=54.956031583s containerID=e371be61ab datapathPolicyRevision=0 desiredPolicyRevision=25 endpointID=45657 error="Error while configuring proxy redirects: proxy state changes failed: context deadline exceeded" ipv4=10.10.1.20 ipv6="f00d::a0a:100:0:b259" k8sPodName=default/details-v1-7994657c46-svzcw mapSync=0s policyCalculation=0s prepareBuild=1.8652ms proxyConfiguration=0s proxyPolicyCalculation=0s proxyWaitForAck=0s reason="one or more identities created or deleted" subsys=endpoint waitingForCTClean=0s waitingForLock=54.953826124s
2018-10-13T00:09:09.676897884Z level=info msg="Regenerating endpoint" containerID=e371be61ab datapathPolicyRevision=0 desiredPolicyRevision=25 endpointID=45657 ipv4=10.10.1.20 ipv6="f00d::a0a:100:0:b259" k8sPodName=default/details-v1-7994657c46-svzcw reason="one or more identities created or deleted" startTime="2018-10-13 00:09:09.675999204 +0000 UTC m=+596.160701709" subsys=endpoint
2018-10-13T00:10:04.728194677Z level=warning msg="Regeneration of endpoint failed" bpfCompilation=0s buildDuration=54.990054854s containerID=e371be61ab datapathPolicyRevision=0 desiredPolicyRevision=26 endpointID=45657 error="Error while configuring proxy redirects: proxy state changes failed: context deadline exceeded" ipv4=10.10.1.20 ipv6="f00d::a0a:100:0:b259" k8sPodName=default/details-v1-7994657c46-svzcw mapSync=0s policyCalculation=0s prepareBuild=1.426859ms proxyConfiguration=1.732738ms proxyPolicyCalculation=0s proxyWaitForAck=54.963390203s reason="one or more identities created or deleted" subsys=endpoint waitingForCTClean=0s waitingForLock=54.985089902s
2018-10-13T00:10:05.187346868Z level=info msg="Regenerating endpoint" containerID=e371be61ab datapathPolicyRevision=0 desiredPolicyRevision=26 endpointID=45657 ipv4=10.10.1.20 ipv6="f00d::a0a:100:0:b259" k8sPodName=default/details-v1-7994657c46-svzcw reason="one or more identities created or deleted" startTime="2018-10-13 00:10:05.187292822 +0000 UTC m=+651.671995330" subsys=endpoint
2018-10-13T00:11:00.191035239Z level=warning msg="Regeneration of endpoint failed" bpfCompilation=0s buildDuration=54.997439842s containerID=e371be61ab datapathPolicyRevision=0 desiredPolicyRevision=29 endpointID=45657 error="Error while configuring proxy redirects: proxy state changes failed: context deadline exceeded" ipv4=10.10.1.20 ipv6="f00d::a0a:100:0:b259" k8sPodName=default/details-v1-7994657c46-svzcw mapSync="56.192µs" policyCalculation=0s prepareBuild="489.875µs" proxyConfiguration="85.788µs" proxyPolicyCalculation=26.909348ms proxyWaitForAck=54.968224216s reason="one or more identities created or deleted" subsys=endpoint waitingForCTClean=0s waitingForLock="8.23µs"
```

The endpoint had the `reserved:init` identity when the first regeneration started:
```
$ grep '"Refreshing labels of endpoint".*endpointID=45657' pod-kube-system-cilium-gvqjs-cilium-agent.log  | head -n 2
2018-10-13T00:03:37.331869764Z level=debug msg="Refreshing labels of endpoint" containerID=e371be61ab endpointID=45657 identityLabels="reserved:init" infoLabels= subsys=endpoint
2018-10-13T00:03:37.363029933Z level=debug msg="Refreshing labels of endpoint" containerID=e371be61ab endpointID=45657 identityLabels="k8s:app=details,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.istiosidecarproxy=true,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=default,k8s:track=stable,k8s:version=v1,k8s:zgroup=bookinfo" infoLabels="container:annotation.kubernetes.io/config.seen=2018-10-13T00:03:35.45641598Z,container:annotation.kubernetes.io/config.source=api,container:annotation.sidecar.istio.io/status={\"version\":\"7c483d21f2b4d2a2216a5946f7721f8938f54b2b92ac0deb5691f75d6a6eb71a\",\"initContainers\":[\"sleep\",\"istio-init\"],\"containers\":[\"istio-proxy\"],\"volumes\":[\"cilium-unix-sock-dir\",\"istio-envoy\",\"istio-certs\"],\"imagePullSecrets\":null},container:io.kubernetes.container.name=POD,container:io.kubernetes.docker.type=podsandbox,container:io.kubernetes.pod.name=details-v1-7994657c46-svzcw,container:io.kubernetes.pod.uid=6ddd6da5-ce7b-11e8-804b-080027b66966,k8s:pod-template-hash=7994657c46" subsys=endpoint
```

The identity change seems to happen before the policy recalculation etc. happens in the first regeneration:
```
$ grep '"Identity of endpoint changed"\|"flushing old PolicyMap"' pod-kube-system-cilium-gvqjs-cilium-agent.log | grep endpointID=45657
2018-10-13T00:03:37.33325609Z level=info msg="Identity of endpoint changed" containerID=e371be61ab datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=45657 identity=5 identityLabels="reserved:init" ipv4=10.10.1.20 ipv6="f00d::a0a:100:0:b259" k8sPodName=/ oldIdentity="no identity" subsys=endpoint
2018-10-13T00:03:37.471060205Z level=info msg="Identity of endpoint changed" containerID=e371be61ab datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=45657 identity=18539 identityLabels="k8s:app=details,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.istiosidecarproxy=true,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=default,k8s:track=stable,k8s:version=v1,k8s:zgroup=bookinfo" ipv4=10.10.1.20 ipv6="f00d::a0a:100:0:b259" k8sPodName=default/details-v1-7994657c46-svzcw oldIdentity=5 subsys=endpoint
2018-10-13T00:03:45.342037667Z level=debug msg="flushing old PolicyMap" containerID=e371be61ab datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=45657 ipv4=10.10.1.20 ipv6="f00d::a0a:100:0:b259" k8sPodName=default/details-v1-7994657c46-svzcw subsys=endpoint
```
So I will assume that the pod received identity `18539` before its first regeneration resolved the policy.

The first BPF compilation completed at 00:03:48:
```
$ grep '"Recompiled endpoint BPF program".*endpointID=45657' pod-kube-system-cilium-gvqjs-cilium-agent.log 
2018-10-13T00:03:48.657366575Z level=info msg="Recompiled endpoint BPF program" BPFCompilationTime=3.298946308s containerID=e371be61ab datapathPolicyRevision=0 desiredPolicyRevision=25 endpointID=45657 error="<nil>" ipv4=10.10.1.20 ipv6="f00d::a0a:100:0:b259" k8sPodName=default/details-v1-7994657c46-svzcw subsys=endpoint
```

However, the sidecar proxy only starts at 00:08:07:
```
$ head -n 1 pod-default-details-v1-7994657c46-svzcw-istio-proxy-previous.log 
2018-10-13T00:08:07.643940602Z 2018-10-13T00:08:07.643765Z	info	Version root@localhost-docker.io/istio-ba018d0ddf819f36a3e3c8d0e494b2743ea1387c-ba018d0ddf819f36a3e3c8d0e494b2743ea1387c-Clean
```

I.e., the sidecar proxy starts more than 4 minutes after the BPF program is installed and the endpoint is created. That explains why the regeneration times out waiting for an ACK from the sidecar proxy during regeneration.

**Possible solution: cache the Istio sidecar image before the test starts.**

**Comment by rlenglet** [comment]
test-me-please

**Review by tgraf — COMMENTED** [review]
Leaving aside the analysis aside and assuming the race is on the early side. The fix is also incomplete as have not yet written the entry in the lxcmap yet so it does not exist from a routing perspective.

I think we have to do a full BPF plumbing before attempting to configure the proxy for the first time including writing to the lxcmap and syncing the policymap.

Can't we just defer the proxy configuration to the very end and then keep on retrying to build it?

**Comment by rlenglet** [comment]
> The fix is also incomplete as have not yet written the entry in the lxcmap yet so it does not exist from a routing perspective.

 @tgraf Ah, good point. But how would that explain that we're seeing no trace of any traffic to/from the pod in the monitor output?

**Comment by rlenglet** [comment]
> Can't we just defer the proxy configuration to the very end and then keep on retrying to build it?

Yes, we can safely swap the LXC map update and the proxy wait + final policy map update. We'll do that and only signal once both the BPF program is installed AND the LXC map is updated.

File: pkg/endpoint/bpf.go [hunk 4]
```diff
@@ -727,7 +727,16 @@ func (e *Endpoint) regenerateBPF(owner Owner, currentDir, nextDir string, regenC
 			Debug("BPF header file unchanged, skipping BPF compilation and installation")
 	}
 
+	// Hook the endpoint into the endpoint table and expose it
+	stats.mapSync.Start()
+	err = lxcmap.WriteEndpoint(epInfoCache)
```
Comment (tgraf) [inline pkg/endpoint/bpf.go:737]: This will introduce drops now as the policy map is not ready when the endpoint is announced.

Comment (rlenglet) [reply pkg/endpoint/bpf.go:737]: It is. There are 2 policy map updates. The 1st (and most important one) is done on line 607. The only purpose of the 2nd policy map update below is to add newly created L7 redirects.

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
test-me-please

File: pkg/endpoint/bpf.go (hunk 4 above)
Comment (tgraf) [reply pkg/endpoint/bpf.go:737]: OK, it still moves the lxcmap update in front of waiting for the ctmap cleanup to finish so we could clean up while initial active connections can start being created.

Comment (tgraf) [reply pkg/endpoint/bpf.go:737]: We may actually need to wait for the ct cleanup to complete before the BPF generation is performed

**Comment by rlenglet** [comment]
test-me-please

File: pkg/endpoint/bpf.go (hunk 4 above)
Comment (rlenglet) [reply pkg/endpoint/bpf.go:737]: OK, I will add a commit to do that.
I will keep the setting of `Endpoint.ctCleaned` to `true` where it is, i.e. after waiting for proxy ACK, because I don't want to acquire the lock earlier.

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
The Istio test passed:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7272/execution/node/94/log/
```
01:15:47.984 ------------------------------
01:15:47.985 K8sIstioTest Istio Bookinfo Demo 
01:15:47.985   Tests bookinfo inter-service connectivity
01:15:47.985   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:383
01:15:50.191 STEP: Pulling the Istio proxy image
01:16:51.119 STEP: Creating the istio-system namespace
01:16:51.120 STEP: Creating the Istio resources
01:16:51.120 STEP: Waiting for Istio pods to be ready
01:18:33.476 STEP: Waiting for Istio service "istio-statsd-prom-bridge" to be ready
01:18:33.476 STEP: Waiting for Istio service "istio-pilot" to be ready
01:18:33.476 STEP: Waiting for DNS to resolve Istio service "istio-statsd-prom-bridge"
01:18:33.476 STEP: Waiting for DNS to resolve Istio service "istio-pilot"
01:18:43.955 STEP: Creating policy in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/istio-sidecar-init-policy.yaml"
01:18:47.898 STEP: Creating policy in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/cnp-specs.yaml"
01:18:53.829 STEP: Creating resources in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/bookinfo-v2-istio.yaml"
01:18:53.829 STEP: Creating resources in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/bookinfo-v1-istio.yaml"
01:18:55.387 STEP: Waiting for Bookinfo pods to be ready
01:21:07.831 STEP: Waiting for Bookinfo endpoints to be ready
01:24:51.922 STEP: Waiting for Bookinfo service "details" to be ready
01:24:51.922 STEP: Waiting for Bookinfo service "ratings" to be ready
01:24:51.922 STEP: Waiting for Bookinfo service "reviews" to be ready
01:24:51.922 STEP: Waiting for Bookinfo service "productpage" to be ready
01:24:51.922 STEP: Waiting for DNS to resolve Bookinfo service "productpage"
01:24:51.922 STEP: Waiting for DNS to resolve Bookinfo service "reviews"
01:24:51.922 STEP: Waiting for DNS to resolve Bookinfo service "ratings"
01:24:51.922 STEP: Waiting for DNS to resolve Bookinfo service "details"
01:24:51.922 STEP: Testing L7 filtering
01:24:51.922 STEP: Checking that "reviews-v1-7b8f59575d-68c8z" can connect to "ratings.default.svc.cluster.local:9080/health"
01:24:51.922 STEP: Checking that "reviews-v1-7b8f59575d-68c8z" cannot connect to "ratings.default.svc.cluster.local:9080/ratings/0"
01:24:51.922 STEP: Checking that "productpage-v1-bb54dc5d4-jpcvg" can connect to "details.default.svc.cluster.local:9080/health"
01:24:51.922 STEP: Checking that "productpage-v1-bb54dc5d4-jpcvg" cannot connect to "ratings.default.svc.cluster.local:9080/health"
01:24:51.922 STEP: Checking that "productpage-v1-bb54dc5d4-jpcvg" cannot connect to "ratings.default.svc.cluster.local:9080/ratings/0"
01:24:52.459 === Test Finished at 2018-10-15T23:22:52Z====
```
Note that it took ~1 minute to pull the Istio proxy images onto the nodes. That's as much time shaved from the Bookinfo pods startup.
Also, it took >5 minutes for the Bookinfo endpoints to be ready after creating the resources.
Since the test passed, we won't have logs to investigate further.

**Comment by rlenglet** [comment]
test-me-please

**Comment by rlenglet** [comment]
Unrelated CI failure:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7281/execution/node/94/log/
Every single k8s (1.8 and 1.12) test failed:
```
00:30:21.205 • Failure in Spec Setup (BeforeEach) [1369.878 seconds]
00:30:21.205 K8sPolicyTest
00:30:21.205 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:351
00:30:21.206   Basic Test [BeforeEach]
00:30:21.206   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:351
00:30:21.206     checks all kind of Kubernetes policies
00:30:21.206     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:383
00:30:21.206 
00:30:21.206     cilium was not able to get into ready state
00:30:21.206     Expected
00:30:21.206         <*errors.errorString | 0xc420361690>: {
00:30:21.206             s: "Timeout reached: timed out waiting for pods with filter -l k8s-app=cilium to be ready",
00:30:21.206         }
00:30:21.206     to be nil
00:30:21.206 
00:30:21.207     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Policies.go:65
```

The Cilium pod `cilium-8qcgr` doesn't seem to be able to connect to etcd within 30 seconds, and it gets killed by kubelet:
```
$ head -n 1 pod-kube-system-cilium-8qcgr-cilium-agent-previous.log 
2018-10-15T23:59:11.875559782Z level=debug msg="bpffs is not mounted yet; adding to list of maps to open once it is mounted" bpfMapName=cilium_lxc subsys=bpf

$ grep -v 'level=debug\|level=info' pod-kube-system-cilium-8qcgr-cilium-agent-previous.log | grep level=
2018-10-15T23:59:15.346415019Z level=warning msg="Unable to open map" error="Unable to get object /sys/fs/bpf/tc/globals/cilium_ct_any4_global: no such file or directory" file-path=/sys/fs/bpf/tc/globals/cilium_ct_any4_global subsys=endpoint
2018-10-15T23:59:15.346561088Z level=warning msg="Unable to open map" error="Unable to get object /sys/fs/bpf/tc/globals/cilium_ct6_global: no such file or directory" file-path=/sys/fs/bpf/tc/globals/cilium_ct6_global subsys=endpoint
2018-10-15T23:59:15.348017546Z level=warning msg="Unable to open map" error="Unable to get object /sys/fs/bpf/tc/globals/cilium_ct_any6_global: no such file or directory" file-path=/sys/fs/bpf/tc/globals/cilium_ct_any6_global subsys=endpoint
2018-10-15T23:59:42.522830682Z level=warning msg="Unable to verify version of etcd endpoint" error="context deadline exceeded" etcdEndpoint="https://cilium-etcd-client.kube-system.svc:2379" subsys=kvstore

$ tail -n 1 pod-kube-system-cilium-8qcgr-cilium-agent-previous.log 
2018-10-16T00:01:40.328751567Z level=info msg="Exiting due to signal" signal=terminated subsys=pidfile
```

In any case, this doesn't seem to be related to this PR.

**Comment by rlenglet** [comment]
test-me-please

**Comment by tgraf** [comment]
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:383
Expected
    <string>: Connection timed out
to be empty
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Health.go:112
Standard Output
Number of 'context deadline exceeded' in logs: 0
Number of 'level=error' in logs: 0
⚠️  Number of 'level=warning' in logs: 21
Number of 'Cilium API handler panicked' in logs: 0
⚠️  Number of 'Goroutine took lock for more than' in logs: 14
Cilium pods: [cilium-8n496 cilium-vjjfd]
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
     app3-bf49c776d-htdtm               =>   none
     cilium-etcd-h5cbc57cr4             =>   none
     kube-dns-6f4c8dbcd4-v66zq          =>   none
     microscope                         =>   none
     prometheus-core-5c9fbf5cc6-6hv5p   =>   none
     app2-75f77ffdbf-k8xwt              =>   none
Cilium agent 'cilium-8n496': Status: Failure  Health: Ok Nodes "k8s1 k8s2" ContinerRuntime: Ok Kubernetes: Ok KVstore: Failure Controllers: Total 18 Failed 0
Cilium agent 'cilium-vjjfd': Status: Failure  Health: Ok Nodes "k8s2 k8s1" ContinerRuntime: Ok Kubernetes: Ok KVstore: Failure Controllers: Total 30 Failed 0

Standard Error
STEP: checking that cilium API exposes health instances
STEP: checking that `cilium-health --probe` succeeds
STEP: checking API response for "{.nodes[0].endpoint.icmp.status}"
STEP: checking API response for "{.nodes[0].endpoint.http.status}"
=== Test Finished at 2018-10-16T02:42:38Z====
===================== TEST FAILED =====================
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE     NAME                               READY     STATUS    RESTARTS   AGE       IP              NODE
	 kube-system   cilium-8n496                       1/1       Running   0          22s       192.168.36.11   k8s1
	 kube-system   cilium-vjjfd                       1/1       Running   0          22s       192.168.36.12   k8s2
	 kube-system   etcd-k8s1                          1/1       Running   0          1h        192.168.36.11   k8s1
	 kube-system   etcd-operator-8b5cbb6d6-94qfd      1/1       Running   0          23s       10.10.1.100     k8s2
	 kube-system   kube-apiserver-k8s1                1/1       Running   0          1h        192.168.36.11   k8s1
	 kube-system   kube-controller-manager-k8s1       1/1       Running   0          1h        192.168.36.11   k8s1
	 kube-system   kube-dns-6f4c8dbcd4-4gcl9          3/3       Running   0          27s       10.10.1.167     k8s2
	 kube-system   kube-proxy-jttbr                   1/1       Running   0          1h        192.168.36.11   k8s1
	 kube-system   kube-proxy-x44kj                   1/1       Running   0          59m       192.168.36.12   k8s2
	 kube-system   kube-scheduler-k8s1                1/1       Running   0          1h        192.168.36.11   k8s1
	 monitoring    prometheus-core-5c9fbf5cc6-6hv5p   1/1       Running   0          59m       10.10.1.188     k8s2
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-8n496 -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])   IPv6                IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                 
	 2456       Disabled           Disabled          4          reserved:health               f00d::a0a:0:0:998   10.10.0.77   ready   
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-vjjfd -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                              IPv6                   IPv4          STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                                
	 8492       Disabled           Disabled          100        k8s:io.cilium.k8s.policy.cluster=default                 f00d::a0a:100:0:212c   10.10.1.100   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=cilium-etcd-sa                                                
	                                                            k8s:io.cilium/app=etcd-operator                                                                       
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                           
	 50124      Disabled           Disabled          4          reserved:health                                          f00d::a0a:100:0:c3cc   10.10.1.220   ready   
	 59013      Disabled           Disabled          102        k8s:io.cilium.k8s.policy.cluster=default                 f00d::a0a:100:0:e685   10.10.1.167   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=kube-dns                                                      
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                           
	                                                            k8s:k8s-app=kube-dns                                                                                  
	 
Stderr:
```

**Comment by tgraf** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failure (for looking into after we try again): https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7293/

**Comment by ianvernon** [comment]
Rebased against Istio v1.0.2 changes that were just merged to master; re-triggering tests.

**Comment by ianvernon** [comment]
test-me-please

**Comment by rlenglet** [comment]
test-me-please

**Comment by tgraf** [comment]
Let's submit `endpoint: Wait for CT cleanup to complete before BPF compilation` as a separate PR so we can backport it.

**Comment by tgraf** [comment]
Isn't this still very fragile in the sense that it requires the sidecar to come up within the initial proxy timeout period as otherwise the endpoint build is considered failed and regeneration is never reattempted?

**Comment by ianvernon** [comment]
> Isn't this still very fragile in the sense that it requires the sidecar to come up within the initial proxy timeout period as otherwise the endpoint build is considered failed and regeneration is never reattempted?

@rlenglet and I came to the same conclusion offline. Cilium is at a point in the lifecycle where it has to return from CNI Add in order for the pod creation to proceed, but given that one of the containers in the pod is needed for networking to function (istio-proxy), it becomes a chicken-and-egg problem AFAICT. I believe such problems are the motivation behind things like PodReady++ - https://github.com/kubernetes/community/blob/master/keps/sig-network/0007-pod-ready%2B%2B.md . 

At a certain point though, Cilium is correct that the endpoint is 'not-ready' if the istio-proxy has not come up yet, because it can't say that the networking is configured if it can't contact Envoy.

Is there a way to ensure that the istio-proxy container comes up first in a pod? This would at least ensure that the application container would not be running if istio-proxy isn't running.

**Comment by rlenglet** [comment]
> Is there a way to ensure that the istio-proxy container comes up first in a pod? This would at least ensure that the application container would not be running if istio-proxy isn't running.

AFAIK, there's no way to do that.

**Comment by rlenglet** [comment]
> Let's submit endpoint: Wait for CT cleanup to complete before BPF compilation as a separate PR so we can backport it.

Filed https://github.com/cilium/cilium/pull/5912.

**Comment by ianvernon** [comment]
Build passed after pulling in changes which rebased on top of Istio v1.0.2: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7313/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Successful build: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7320/

**Comment by ianvernon** [comment]
test-me-please

**Comment by rlenglet** [comment]
Build failed due to k8s 1.8 Cilium upgrade test failure:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7326/
```
01:26:55.094 K8sUpdates
01:26:55.094 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:351
01:26:55.095   Tests upgrade and downgrade from a Cilium stable image to master [It]
01:26:55.095   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:383
01:26:55.095 
01:26:55.095   Endpoints are not ready after timeout
01:26:55.095   Expected
01:26:55.095       <*helpers.SSHMetaError | 0xc42211bf40>: Error: Timeout reached: Endpoints are not ready after timeout
01:26:55.095   Extended info: 	Cilium Pod: cilium-h2476 	Endpoint: 3043 	Identity: 102	 State: ready
01:26:55.095   	Cilium Pod: cilium-h2476 	Endpoint: 21780 	Identity: 4	 State: ready
01:26:55.095   	Cilium Pod: cilium-h2476 	Endpoint: 25535 	Identity: 100	 State: ready
01:26:55.095   	Cilium Pod: cilium-h2476 	Endpoint: 56541 	Identity: 3200	 State: restoring
01:26:55.095   
01:26:55.095   
01:26:55.095   to be nil
01:26:55.095 
01:26:55.095   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/k8sT/Updates.go:259
```

I saw similar failures in master builds, so it doesn't seem caused by this PR.

**The Istio test passed.**
Rebasing and retrying again.

**Comment by rlenglet** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build passed : 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7327/

**Comment by ianvernon** [comment]
test-me-please

**Comment by rlenglet** [comment]
The latest build executed the Istio test first and Cilium + the etcd operator got configured correctly. The confirms that commit that is fixing this is working.
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7329/execution/node/94/log/?consoleFull

**Comment by ianvernon** [comment]
Build failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7329/

Timeline of events from the console output:

```
06:24:57 STEP: Pulling the Istio proxy image
06:26:23 STEP: Creating the istio-system namespace
06:26:23 STEP: Creating the Istio resources
06:26:27 STEP: Waiting for Istio pods to be ready
06:27:11 STEP: Waiting for Istio service "istio-statsd-prom-bridge" to be ready
06:27:11 STEP: Waiting for Istio service "istio-pilot" to be ready
06:27:11 STEP: Waiting for DNS to resolve Istio service "istio-statsd-prom-bridge"
06:27:11 STEP: Waiting for DNS to resolve Istio service "istio-pilot"
06:28:02 STEP: Creating policy in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/istio-sidecar-init-policy.yaml"
06:28:03 STEP: Creating policy in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/cnp-specs.yaml"
06:28:10 STEP: Creating resources in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/bookinfo-v2-istio.yaml"
06:28:10 STEP: Creating resources in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/bookinfo-v1-istio.yaml"
06:28:11 STEP: Waiting for Bookinfo pods to be ready
06:32:13 STEP: Waiting for Bookinfo endpoints to be ready
06:37:14 === Test Finished at 2018-10-17T06:37:13Z====
```

Yet again, the details pod is not ready:

```
06:37:18 	 30518      Enabled            Disabled          60033      k8s:app=details                                                         f00d::a0a:100:0:7736   10.10.1.209   not-ready   
06:37:18 	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                 
06:37:18 	                                                            k8s:io.cilium.k8s.policy.istiosidecarproxy=true                                                                          
06:37:18 	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                          
06:37:18 	                                                            k8s:io.kubernetes.pod.namespace=default                                                                                  
06:37:18 	                                                            k8s:track=stable                                                                                                         
06:37:18 	                                                            k8s:version=v1                                                                                                           
06:37:18 	                                                            k8s:zgroup=bookinfo  
```

Said pod was being managed by cilium pod `cilium-mjn92`. I don't understand why it is always the details pod that behaves in this way. Maybe we should look at this problem from that angle?

Timeline of events for the pod per its metadata. The information was grabbed from the file `pods.txt` in the log archive from the above build.

Pod created: `2018-10-17T06:28:10Z`
Pod initialized: `2018-10-17T06:28:32Z`
Istio-init container "started": `2018-10-17T06:28:31Z`
Istio-init container "finished" `2018-10-17T06:28:32Z`
Bookinfo-details container "startedAt": `2018-10-17T06:28:33Z`
Istio-proxy container (first run) started at: `2018-10-17T06:28:34Z`
Istio-proxy container (first run) went into error state at: `2018-10-17T06:32:14Z`
Istio-proxy container (after restart) started: `2018-10-17T06:32:14Z`
Containers ready: `2018-10-17T06:32:15Z`
Entire pod ready: `2018-10-17T06:32:15Z`

We need to correlate these events with Cilium regeneration events.

However, the execution of `cilium debuginfo` failed for the aforementioned cilium pod:

```
> Error while running 'cilium debuginfo':  exec timeout
```

We are running a ton of pods on this node:

```
cmd: kubectl exec -n kube-system cilium-8wmb4 -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                                    IPv6                 IPv4          STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                                                    
	 17071      Disabled           Disabled          63431      k8s:app=productpage                                                            f00d::a0a:0:0:42af   10.10.0.171   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                  
	                                                            k8s:io.cilium.k8s.policy.istiosidecarproxy=true                                                                           
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                           
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                                   
	                                                            k8s:track=stable                                                                                                          
	                                                            k8s:version=v1                                                                                                            
	                                                            k8s:zgroup=bookinfo                                                                                                       
	 19730      Disabled           Disabled          33161      k8s:app=istio-egressgateway                                                    f00d::a0a:0:0:4d12   10.10.0.124   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                  
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=istio-egressgateway-service-account                                               
	                                                            k8s:io.kubernetes.pod.namespace=istio-system                                                                              
	                                                            k8s:istio=egressgateway                                                                                                   
	 26298      Disabled           Disabled          8127       k8s:app=pilot                                                                  f00d::a0a:0:0:66ba   10.10.0.247   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                  
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=istio-pilot-service-account                                                       
	                                                            k8s:io.kubernetes.pod.namespace=istio-system                                                                              
	                                                            k8s:istio=pilot                                                                                                           
	 30693      Disabled           Disabled          57315      k8s:app=reviews                                                                f00d::a0a:0:0:77e5   10.10.0.84    ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                  
	                                                            k8s:io.cilium.k8s.policy.istiosidecarproxy=true                                                                           
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                           
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                                   
	                                                            k8s:track=stable                                                                                                          
	                                                            k8s:version=v1                                                                                                            
	                                                            k8s:zgroup=bookinfo                                                                                                       
	 48462      Disabled           Disabled          56841      k8s:app=istio-ingressgateway                                                   f00d::a0a:0:0:bd4e   10.10.0.251   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                  
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=istio-ingressgateway-service-account                                              
	                                                            k8s:io.kubernetes.pod.namespace=istio-system                                                                              
	                                                            k8s:istio=ingressgateway                                                                                                  
	 52938      Disabled           Disabled          58211      k8s:io.cilium.k8s.policy.cluster=default                                       f00d::a0a:0:0:ceca   10.10.0.193   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=istio-mixer-service-account                                                       
	                                                            k8s:io.kubernetes.pod.namespace=istio-system                                                                              
	                                                            k8s:istio=statsd-prom-bridge                                                                                              
	 57900      Disabled           Disabled          101        k8s:app=etcd                                                                   f00d::a0a:0:0:e22c   10.10.0.82    ready   
	                                                            k8s:etcd_cluster=cilium-etcd                                                                                              
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                  
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                           
	                                                            k8s:io.cilium/app=etcd-operator                                                                                           
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                                               
	 60576      Disabled           Disabled          4          reserved:health                                                                f00d::a0a:0:0:eca0   10.10.0.85    ready   
	 61414      Disabled           Disabled          9595       k8s:io.cilium.k8s.policy.cluster=default                                       f00d::a0a:0:0:efe6   10.10.0.100   ready   
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=istio-galley-service-account                                                      
	                                                            k8s:io.kubernetes.pod.namespace=istio-system                                                                              
	                                                            k8s:istio=galley                    
```

The cilium pod is running on node `k8s2`:

```
kube-system    cilium-mjn92                                1/1     Running     0          11m     192.168.36.12   k8s2   <none>
```

From the gathered logs for k8s2, there is a ton of load on this host, specifically from python (maybe from microscope?):

```
top - 06:38:41 up 22 min,  0 users,  load average: 8.50, 7.30, 4.50
Tasks: 225 total,   8 running, 217 sleeping,   0 stopped,   0 zombie
%Cpu(s): 21.8 us, 23.6 sy,  0.2 ni, 46.4 id,  1.9 wa,  0.0 hi,  6.1 si,  0.0 st
KiB Mem :  4044512 total,   364668 free,  2102820 used,  1577024 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  1648404 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
14760 root      20   0  210328  82800   4576 R  58.8  2.0   5:18.76 python
 2603 root      20   0  107080  42644   6788 R  29.4  1.1   0:02.62 python
14761 root      20   0  228812 115416   4576 R  29.4  2.9   5:14.73 python
 3450 root      20   0 1314804 125904  54804 S  17.6  3.1   1:16.15 kubelet
14311 root      20   0  141860  48640   7488 S  17.6  1.2   0:37.46 python
12549 root      20   0    9964   5984   3960 S  11.8  0.1   0:19.81 docker-con+
  863 root      20   0 1298916 111172  39152 S   5.9  2.7   1:27.65 dockerd
```

This could contribute to the starting of istio-proxy being slow.

Since we have no output of `cilium debuginfo`, I am consulting the logs:


06:28:11.640620232: Endpoint creation
```
2018-10-17T06:28:11.640620232Z level=debug msg="Endpoint creation" code=OK containerID=c34786ecf3 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=30518 endpointState=waiting-for-identity ipv4= ipv6= k8sPodName=/ policyRevision=0 subsys=endpoint type=0
2018-10-17T06:28:11.641640782Z level=debug msg="Refreshing labels of endpoint" containerID=c34786ecf3 endpointID=30518 identityLabels="reserved:init" infoLabels= subsys=endpoint
2018-10-17T06:28:11.646358125Z level=debug msg="Endpoint has reserved identity, changing synchronously" containerID=c34786ecf3 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=30518 identityLabels="reserved:init" ipv4=10.10.1.209 ipv6="f00d::a0a:100:0:7736" k8sPodName=/ subsys=endpoint
2018-10-17T06:28:11.646655068Z level=debug msg="Resolving identity for labels" containerID=c34786ecf3 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=30518 identityLabels="reserved:init" ipv4=10.10.1.209 ipv6="f00d::a0a:100:0:7736" k8sPodName=/ subsys=endpoint
2018-10-17T06:28:11.647251183Z level=debug msg="Assigned new identity to endpoint" containerID=c34786ecf3 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=30518 identity=5 identityLabels="reserved:init" ipv4=10.10.1.209 ipv6="f00d::a0a:100:0:7736" k8sPodName=/ subsys=endpoint
2018-10-17T06:28:11.647734141Z level=debug msg="Set identity for this endpoint" code=OK containerID=c34786ecf3 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=30518 endpointState=ready ipv4=10.10.1.209 ipv6="f00d::a0a:100:0:7736" k8sPodName=/ policyRevision=0 subsys=endpoint type=0
2018-10-17T06:28:11.648000208Z level=info msg="Identity of endpoint changed" containerID=c34786ecf3 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=30518 identity=5 identityLabels="reserved:init" ipv4=10.10.1.209 ipv6="f00d::a0a:100:0:7736" k8sPodName=/ oldIdentity="no identity" subsys=endpoint
2018-10-17T06:28:11.648031473Z level=debug msg="Triggering regeneration due to new identity" code=OK containerID=c34786ecf3 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=30518 endpointState=waiting-to-regenerate ipv4=10.10.1.209 ipv6="f00d::a0a:100:0:7736" k8sPodName=/ policyRevision=0 subsys=endpoint type=0
```

The endpoint create call is synchronously waiting for endpoint regeneration:
```
2018-10-17T06:28:11.668999714Z level=debug msg="Synchronously waiting for endpoint to regenerate" containerID=c34786ecf3364c273f89b9359ce99c584bdfa385f4d8875e5b3cd5cad8003f96 endpointID=30518 eventID=d2024a31-d1d5-11e8-a8ef-080027b66966 subsys=daemon
```

06:28:11.658558544: regeneration is triggered 

```
2018-10-17T06:28:11.658558544Z level=info msg="Regenerating endpoint" containerID=c34786ecf3 datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=30518 ipv4=10.10.1.209 ipv6="f00d::a0a:100:0:7736" k8sPodName=/ reason="updated security labels" startTime="2018-10-17 06:28:11.657857677 +0000 UTC m=+135.606006791" subsys=endpoint
```

06:28:23.045346785: BPF compilation process begins

```
2018-10-17T06:28:23.045346785Z level=debug msg="BPF header file hashed (was: \"\")" bpfHeaderfileHash=18d1ac96eb45c29ca3a87a3aa67c4869 containerID=c34786ecf3 datapathPolicyRevision=0 desiredPolicyRevision=11 endpointID=30518 ipv4=10.10.1.209 ipv6="f00d::a0a:100:0:7736" k8sPodName=default/details-v1-5667f4fd65-gnjlt subsys=endpoint
2018-10-17T06:28:23.325162882Z level=debug msg="Preparing to compile BPF" bpfHeaderfilesChanged=true containerID=c34786ecf3 datapathPolicyRevision=0 desiredPolicyRevision=11 endpointID=30518 ipv4=10.10.1.209 ipv6="f00d::a0a:100:0:7736" k8sPodName=default/details-v1-5667f4fd65-gnjlt subsys=endpoint
```

06:28:34.142211724Z: `pod-default-details-v1-5667f4fd65-gnjlt-istio-proxy-previous.log` shows that the istio-proxy finally starts.


```
2018-10-17T06:28:34.142211724Z 2018-10-17T06:28:34.142063Z	info	Version root@localhost-docker.io/istio-a29e304c6be717e0f970dabd77b27ffb3061463b-a29e304c6be717e0f970dabd77b27ffb3061463b-Clean
```

06:28:49.167026662: istio-proxy can't resolve the IP for istio-statds-prom-bridge and fails. This continues until T06:32:14.053247063 , when the pod crashes.

```
2018-10-17T06:28:49.167026662Z [2018-10-17 06:28:49.166][18][critical][main] external/envoy/source/server/server.cc:80] error initializing configuration '/etc/istio/proxy/envoy-rev0.json': malformed IP address: istio-statsd-prom-bridge.istio-system
2018-10-17T06:28:49.1713902Z [2018-10-17 06:28:49.171][18][info][main] external/envoy/source/server/server.cc:486] exiting
```


06:29:18.037072165: Regeneration failed. I believe this is the first regeneration (for the init identity) because the datapathPolicyRevision is 0 for the endpoint, indicating that the entire regeneration process (including proxy configuration) has succeeded. The BPF program has been installed at this point.

```
2018-10-17T06:29:18.036851377Z level=warning msg="generating BPF for endpoint failed, keeping stale directory." containerID=c34786ecf3 datapathPolicyRevision=0 desiredPolicyRevision=11 endpointID=30518 file-path=30518_next_fail ipv4=10.10.1.209 ipv6="f00d::a0a:100:0:7736" k8sPodName=default/details-v1-5667f4fd65-gnjlt subsys=endpoint
...
k8sPodName=default/details-v1-5667f4fd65-gnjlt policyRevision=0 subsys=endpoint type=0
2018-10-17T06:29:18.037072165Z level=warning msg="Regeneration of endpoint failed" bpfCompilation=8.010823385s buildDuration=1m6.379094487s containerID=c34786ecf3 datapathPolicyRevision=0 desiredPolicyRevision=11 endpointID=30518 error="Error while configuring proxy redirects: proxy state changes failed: context deadline exceeded" ipv4=10.10.1.209 ipv6="f00d::a0a:100:0:7736" k8sPodName=default/details-v1-5667f4fd65-gnjlt mapSync="321.966µs" policyCalculation=7.421402ms prepareBuild=280.510329ms proxyConfiguration="94.852µs" proxyPolicyCalculation=5.555818ms proxyWaitForAck=46.695126934s reason="updated security labels" subsys=endpoint waitingForCTClean=279.528742ms waitingForLock=11.369439301s
2018-10-17T06:29:18.037108923Z level=debug msg="Error regenerating endpoint: Error while configuring proxy redirects: proxy state changes failed: context deadline exceeded" code=Failure containerID=c34786ecf3 datapathPolicyRevision=0 desiredPolicyRevision=11 endpointID=30518 endpointState=waiting-to-regenerate ipv4=10.10.1.209 ipv6="f00d::a0a:100:0:7736" k8sPodName=default/details-v1-5667f4fd65-gnjlt policyRevision=0 subsys=endpoint type=200
```


06:28:31.335857285: BPF compilation succeeded. Note that this is *before* the istio-proxy starts. The datapath should be ready at this point, so the sidecar proxy should be able to access DNS: 

```2018-10-17T06:28:31.335857285Z level=info msg="Recompiled endpoint BPF program" BPFCompilationTime=8.010823385s containerID=c34786ecf3 datapathPolicyRevision=0 desiredPolicyRevision=11 endpointID=30518 error="<nil>" ipv4=10.10.1.209 ipv6="f00d::a0a:100:0:7736" k8sPodName=default/details-v1-5667f4fd65-gnjlt subsys=endpoint```

06:31:08.081299779: regeneration failed again because the the istio-proxy did not complete configuring itself in time. 

```
2018-10-17T06:31:08.081299779Z level=warning msg="Regeneration of endpoint failed" bpfCompilation=0s buildDuration=54.93045232s containerID=c34786ecf3 datapathPolicyRevision=0 desiredPolicyRevision=11 endpointID=30518 error="Error while configuring proxy redirects: proxy state changes failed: context deadline exceeded" ipv4=10.10.1.209 ipv6="f00d::a0a:100:0:7736" k8sPodName=default/details-v1-5667f4fd65-gnjlt mapSync=0s policyCalculation=0s prepareBuild="25.582µs" proxyConfiguration=0s proxyPolicyCalculation=0s proxyWaitForAck=0s reason="one or more identities created or deleted" subsys=endpoint waitingForCTClean=0s waitingForLock="6.538µs"
2018-10-17T06:31:08.081335061Z level=debug msg="Error regenerating endpoint: Error while configuring proxy redirects: proxy state changes failed: context deadline exceeded" code=Failure containerID=c34786ecf3 datapathPolicyRevision=0 desiredPolicyRevision=11 endpointID=30518 endpointState=ready ipv4=10.10.1.209 ipv6="f00d::a0a:100:0:7736" k8sPodName=default/details-v1-5667f4fd65-gnjlt policyRevision=0 subsys=endpoint type=200
```

The `istio-proxy` container finally restarts and appears to be in a good state:

```
018-10-17T06:32:14.99265197Z 2018-10-17T06:32:14.992536Z	info	Version root@localhost-docker.io/istio-a29e304c6be717e0f970dabd77b27ffb3061463b-a29e304c6be717e0f970dabd77b27ffb3061463b-Clean
```

The monitor logs show policy drops:
```
$ grep "10.10.1.209" monitor.log 
[2018-10-17 06:34:51] k8s2: trace ( 10.10.1.209:58903) => (reserved:unknown 10.96.0.10:53)
[2018-10-17 06:34:51] k8s2: debug: Conntrack lookup 1/2: src=10.10.1.209:58903 dst=10.96.0.10:53 on CPU 01:
[2018-10-17 06:34:51] k8s2: debug: Conntrack lookup 1/2: src=10.10.1.209:58903 dst=10.10.1.182:53 on CPU 01:
[2018-10-17 06:34:51] k8s2: debug: Conntrack lookup 1/2: src=10.10.1.209:58903 dst=10.10.1.182:53 on CPU 01:
[2018-10-17 06:34:51] k8s2: drop: Policy denied (L3) ( 10.10.1.209:58903) => (kube-system/coredns-779ffd89bd-2s4df 10.10.1.182:53)
[2018-10-17 06:34:51] k8s2: trace ( 10.10.1.209:55382) => (reserved:unknown 10.96.0.10:53)
[2018-10-17 06:34:51] k8s2: debug: Conntrack lookup 1/2: src=10.10.1.209:55382 dst=10.96.0.10:53 on CPU 01:
[2018-10-17 06:34:51] k8s2: debug: Conntrack lookup 1/2: src=10.10.1.209:55382 dst=10.10.1.182:53 on CPU 01:
[2018-10-17 06:34:51] k8s2: debug: Conntrack lookup 1/2: src=10.10.1.209:55382 dst=10.10.1.182:53 on CPU 01:
[2018-10-17 06:34:51] k8s2: drop: Policy denied (L3) ( 10.10.1.209:55382) => (kube-system/coredns-779ffd89bd-2s4df 10.10.1.182:53)
[2018-10-17 06:35:12] k8s2: trace ( 10.10.1.209:46810) => (reserved:unknown 10.96.0.10:53)
[2018-10-17 06:35:12] k8s2: debug: Conntrack lookup 1/2: src=10.10.1.209:46810 dst=10.96.0.10:53 on CPU 01:
[2018-10-17 06:35:12] k8s2: debug: Conntrack lookup 1/2: src=10.10.1.209:46810 dst=10.10.1.182:53 on CPU 01:
[2018-10-17 06:35:12] k8s2: debug: Conntrack lookup 1/2: src=10.10.1.209:46810 dst=10.10.1.182:53 on CPU 01:
[2018-10-17 06:35:12] k8s2: drop: Policy denied (L3) ( 10.10.1.209:46810) => (kube-system/coredns-779ffd89bd-2s4df 10.10.1.182:53)
[2018-10-17 06:35:12] k8s2: trace ( 10.10.1.209:46810) => (reserved:unknown 10.96.0.10:53)
[2018-10-17 06:35:12] k8s2: debug: Conntrack lookup 1/2: src=10.10.1.209:46810 dst=10.96.0.10:53 on CPU 01:
[2018-10-17 06:35:12] k8s2: debug: Conntrack lookup 1/2: src=10.10.1.209:46810 dst=10.10.1.182:53 on CPU 01:
[2018-10-17 06:35:12] k8s2: debug: Conntrack lookup 1/2: src=10.10.1.209:46810 dst=10.10.1.182:53 on CPU 01:
[2018-10-17 06:35:12] k8s2: drop: Policy denied (L3) ( 10.10.1.209:46810) => (kube-system/coredns-779ffd89bd-2s4df 10.10.1.182:53)
[2018-10-17 06:35:51] k8s2: trace ( 10.10.1.209:47474) => (reserved:unknown 10.96.0.10:53)
[2018-10-17 06:35:51] k8s2: debug: Conntrack lookup 1/2: src=10.10.1.209:47474 dst=10.96.0.10:53 on CPU 01:
[2018-10-17 06:35:51] k8s2: debug: Conntrack lookup 1/2: src=10.10.1.209:47474 dst=10.10.1.182:53 on CPU 01:
[2018-10-17 06:35:51] k8s2: debug: Conntrack lookup 1/2: src=10.10.1.209:47474 dst=10.10.1.182:53 on CPU 01:
[2018-10-17 06:35:51] k8s2: drop: Policy denied (L3) ( 10.10.1.209:47474) => (kube-system/coredns-779ffd89bd-2s4df 10.10.1.182:53)
[2018-10-17 06:35:51] k8s2: trace ( 10.10.1.209:47474) => (reserved:unknown 10.96.0.10:53)
[2018-10-17 06:35:51] k8s2: debug: Conntrack lookup 1/2: src=10.10.1.209:47474 dst=10.96.0.10:53 on CPU 01:
[2018-10-17 06:35:51] k8s2: debug: Conntrack lookup 1/2: src=10.10.1.209:47474 dst=10.10.1.182:53 on CPU 01:
[2018-10-17 06:35:51] k8s2: debug: Conntrack lookup 1/2: src=10.10.1.209:47474 dst=10.10.1.182:53 on CPU 01:
[2018-10-17 06:35:51] k8s2: drop: Policy denied (L3) ( 10.10.1.209:47474) => (kube-system/coredns-779ffd89bd-2s4df 10.10.1.182:53)
```

I do wonder how reliable the timestamping within microscope is though?

**Comment by rlenglet** [comment]
Those L3 policy drops are really fishy, because those flows are explicitly allowed by the init policy, and there are no egress rules in any of the non-init policies.

And we still have no explanation why we see no packets at all to/from the pod until the istio-proxy container restarts.

**Comment by rlenglet** [comment]
Microscope seems to have connectivity issues to the `cilium-mjn92` pod:
```
$ grep WARNING monitor.log 
[2018-10-17 06:28:03] 2018-10-17 06:28:02,488 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2460)'))': /api/v1/namespaces/kube-system/pods/cilium-mjn92
```

This happens before the `istio-proxy` container starts (at 06:28:34), which would explain why we're not seeing any packets to/from that pod.

**Comment by rlenglet** [comment]
The dropped flows are to the DNS cluster IP address `10.96.0.10`, which gets properly translated into `10.10.1.182`, which is the IP address of coredns.
That translation is consistent with the Cilium's view of the service, cf. `cilium-bpf-lb-list.md`:
```
10.96.0.10:53          0.0.0.0:0 (0)
                       10.10.1.182:53 (1)
```
The IP cache correctly maps that IP address to identity `104`:
```
$ grep 10.10.1.182 cilium-bpf-ipcache-list.md 
10.10.1.182/32             104        
```
In the pod's `cilium endpoint get` output, `allowed-egress-identities` includes identity `104`, and there are no L4 or L7 egresss rules.
**So according to the pod's `cilium endpoint get` output, these flows should NOT be dropped at L3 by the datapath.**

One hypothesis is that either the ipcache map and/or the pod's policy map are not consistent.

**Comment by rlenglet** [comment]
We see significant loss of monitor events:
```
$ grep lost cilium-*_status.txt 
cilium-8wmb4_status.txt:                        163790 events lost, 0 unknown notifications
cilium-mjn92_status.txt:                        19324 events lost, 0 unknown notifications
```
Probably because of the load incurred by all the pods running in this test.

**Comment by rlenglet** [comment]
The IP cache mapping for the dns IP happens early, before the `istio-proxy` container starts:
```
$ grep 'Upserting IP into ipcache layer.*104' pod-kube-system-cilium-mjn92-cilium-agent.log 
2018-10-17T06:26:59.240423709Z level=debug msg="Upserting IP into ipcache layer" identity="{104 kvstore}" ipAddr="f00d::a0a:100:0:4464" subsys=ipcache
2018-10-17T06:26:59.241465599Z level=debug msg="Upserting IP into ipcache layer" identity="{104 kvstore}" ipAddr=10.10.1.182 subsys=ipcache
```
So there is no issue with the consistency of the in-memory IP cache.

**Comment by ianvernon** [comment]
Added additional debugging information to get policy map state from the BPF filesystem even if the cilium API cannot be accessed, which was the case last time. Running the build again.

Filed this as a separate PR: #5925

**Comment by ianvernon** [comment]
Also pushed a commit which should only have the Istio test run in the CI to reduce turnaround time in verifying the stability of the test.

**Comment by ianvernon** [comment]
test-me-please

EDIT: tests will fail due to `cmdref` not being built. Re-built it and running tests again.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7355/

Will triage.


Test timeline:
```
19:25:18   Tests bookinfo inter-service connectivity
19:25:18   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:383
19:25:19 STEP: Pulling the Istio proxy image
19:27:04 STEP: Creating the istio-system namespace
19:27:04 STEP: Creating the Istio resources
19:27:07 STEP: Waiting for Istio pods to be ready
19:28:37 STEP: Waiting for Istio service "istio-statsd-prom-bridge" to be ready
19:28:37 STEP: Waiting for Istio service "istio-pilot" to be ready
19:28:37 STEP: Waiting for DNS to resolve Istio service "istio-statsd-prom-bridge"
19:28:37 STEP: Waiting for DNS to resolve Istio service "istio-pilot"
19:28:40 STEP: Creating policy in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/istio-sidecar-init-policy.yaml"
19:28:42 STEP: Creating policy in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/cnp-specs.yaml"
19:28:48 STEP: Creating resources in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/bookinfo-v2-istio.yaml"
19:28:48 STEP: Creating resources in file "/home/vagrant/go/src/github.com/cilium/cilium/test/k8sT/manifests/bookinfo-v1-istio.yaml"
19:28:49 STEP: Waiting for Bookinfo pods to be ready
19:29:16 STEP: Waiting for Bookinfo endpoints to be ready
19:34:21 === Test Finished at 2018-10-17T19:34:17Z====
19:34:21 ===================== TEST FAILED ====================
```

Details pod went into not-ready state:

```
19:34:21 	 53768      Enabled            Disabled          30003      k8s:app=details                                                                f00d::a0a:100:0:d208   10.10.1.2     not-ready   
19:34:21 	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                                        
19:34:21 	                                                            k8s:io.cilium.k8s.policy.istiosidecarproxy=true                                                                                 
19:34:21 	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                                 
19:34:21 	                                                            k8s:io.kubernetes.pod.namespace=default                                                                                         
19:34:21 	                                                            k8s:track=stable                                                                                                                
19:34:21 	                                                            k8s:version=v1                                                                                                                  
19:34:21 	                                                            k8s:zgroup=bookinfo  
```

The pod was managed by `cilium-xkdg2`. 

We finally see policy drops from the monitor:

```
$ grep "drop.*10.10.1.2:" monitor.log 
[2018-10-17 19:32:03] k8s2: drop: Policy denied (L3) ( 10.10.1.2:46411) => (kube-system/coredns-779ffd89bd-td94v 10.10.1.242:53)
[2018-10-17 19:32:03] k8s2: drop: Policy denied (L3) ( 10.10.1.2:46411) => (kube-system/coredns-779ffd89bd-td94v 10.10.1.242:53)
[2018-10-17 19:32:06] k8s2: drop: Policy denied (L3) ( 10.10.1.2:51256) => (istio-system/istio-pilot-6c76769f69-plclz 10.10.1.172:15011)
[2018-10-17 19:32:18] k8s2: drop: Policy denied (L3) ( 10.10.1.2:51256) => (istio-system/istio-pilot-6c76769f69-plclz 10.10.1.172:15011)
[2018-10-17 19:32:22] k8s2: drop: Policy denied (L3) ( 10.10.1.2:46411) => (kube-system/coredns-779ffd89bd-td94v 10.10.1.242:53)
[2018-10-17 19:32:25] k8s2: drop: Policy denied (L3) ( 10.10.1.2:51256) => (istio-system/istio-pilot-6c76769f69-plclz 10.10.1.172:15011)
[2018-10-17 19:32:26] k8s2: drop: Policy denied (L3) ( 10.10.1.2:46411) => (kube-system/coredns-779ffd89bd-td94v 10.10.1.242:53)
[2018-10-17 19:32:33] k8s2: drop: Policy denied (L3) ( 10.10.1.2:51256) => (istio-system/istio-pilot-6c76769f69-plclz 10.10.1.172:15011)
[2018-10-17 19:32:42] k8s2: drop: Policy denied (L3) ( 10.10.1.2:33946) => (istio-system/istio-statsd-prom-bridge-67bbcc746c-qjkbr 10.10.1.74:9125)
[2018-10-17 19:32:43] k8s2: drop: Policy denied (L3) ( 10.10.1.2:46411) => (kube-system/coredns-779ffd89bd-td94v 10.10.1.242:53)
[2018-10-17 19:32:43] k8s2: drop: Policy denied (L3) ( 10.10.1.2:51306) => (istio-system/istio-pilot-6c76769f69-plclz 10.10.1.172:15011)
[2018-10-17 19:32:46] k8s2: drop: Policy denied (L3) ( 10.10.1.2:46411) => (kube-system/coredns-779ffd89bd-td94v 10.10.1.242:53)
[2018-10-17 19:32:47] k8s2: drop: Policy denied (L3) ( 10.10.1.2:51306) => (istio-system/istio-pilot-6c76769f69-plclz 10.10.1.172:15011)
[2018-10-17 19:32:53] k8s2: drop: Policy denied (L3) ( 10.10.1.2:51306) => (istio-system/istio-pilot-6c76769f69-plclz 10.10.1.172:15011)
[2018-10-17 19:33:09] k8s2: drop: Policy denied (L3) ( 10.10.1.2:51306) => (istio-system/istio-pilot-6c76769f69-plclz 10.10.1.172:15011)
[2018-10-17 19:33:16] k8s2: drop: Policy denied (L3) ( 10.10.1.2:33946) => (istio-system/istio-statsd-prom-bridge-67bbcc746c-qjkbr 10.10.1.74:9125)
[2018-10-17 19:34:40] k8s2: drop: Policy denied (L3) ( 10.10.1.2:46411) => (kube-system/coredns-779ffd89bd-td94v 10.10.1.242:53)
```

We see drops, but the PolicyMap state for the endpoint shows that access to coredns is allowed!

```
Egress      k8s:io.cilium.k8s.policy.cluster=default                                        ANY          NONE         86748     896       
            k8s:io.cilium.k8s.policy.serviceaccount=coredns                                                                                    
            k8s:io.kubernetes.pod.namespace=kube-system                                                                                        
            k8s:k8s-app=kube-dns  
```

I confirmed that the coredns pod has those labels:

```
"security-relevant": [
          "k8s:io.cilium.k8s.policy.cluster=default",
          "k8s:io.cilium.k8s.policy.serviceaccount=coredns",
          "k8s:io.kubernetes.pod.namespace=kube-system",
          "k8s:k8s-app=kube-dns"
```

This is bizarre. The endpoint log for the endpoint shows no regenerations after 19:29:52, which means that the PolicyMap state that we see in the bugtool output is what was used in the test:

#### Endpoint Log 53768

```
Timestamp              Status    State                   Message
2018-10-17T19:29:52Z   Failure   ready                   Error regenerating endpoint: Error while configuring proxy redirects: proxy state changes failed: context deadline exceeded
2018-10-17T19:29:52Z   OK        ready                   Completed endpoint regeneration with no pending regeneration requests
2018-10-17T19:28:57Z   OK        regenerating            Regenerating endpoint: one or more identities created or deleted
2018-10-17T19:28:55Z   Warning   waiting-to-regenerate   Skipped invalid state transition to waiting-to-regenerate due to: Triggering endpoint regeneration due to one or more identities created or deleted
2018-10-17T19:28:54Z   Warning   waiting-to-regenerate   Skipped invalid state transition to waiting-to-regenerate due to: Triggering endpoint regeneration due to one or more identities created or deleted
2018-10-17T19:28:53Z   OK        waiting-to-regenerate   Successfully regenerated endpoint program (Reason: updated security labels)
2018-10-17T19:28:53Z   Warning   waiting-to-regenerate   Skipped invalid state transition to ready due to: Completed endpoint regeneration with no pending regeneration requests
2018-10-17T19:28:53Z   Warning   waiting-to-regenerate   Skipped invalid state transition to waiting-to-regenerate due to: Triggering endpoint regeneration due to one or more identities created or deleted
2018-10-17T19:28:51Z   Warning   waiting-to-regenerate   Skipped invalid state transition to waiting-to-regenerate due to: Triggering regeneration due to new identity
2018-10-17T19:28:51Z   OK        waiting-to-regenerate   Triggering endpoint regeneration due to one or more identities created or deleted
2018-10-17T19:28:51Z   OK        regenerating            Regenerating endpoint: updated security labels
2018-10-17T19:28:51Z   OK        waiting-to-regenerate   Triggering regeneration due to new identity
2018-10-17T19:28:51Z   OK        ready                   Set identity for this endpoint
2018-10-17T19:28:51Z   OK        waiting-for-identity    Endpoint creation
```

The `sync-policymap` controller for the endpoint never failed:
```
        {
          "configuration": {
            "error-retry": true,
            "interval": "1m0s"
          },
          "name": "sync-policymap-53768",
          "status": {
            "last-failure-timestamp": "0001-01-01T00:00:00.000Z",
            "last-success-timestamp": "2018-10-17T19:34:53.821Z",
            "success-count": 7
          },
          "uuid": "e21e6fb7-d242-11e8-9b76-080027b66966"
        },
```

I am flummoxed.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Runtime tests failed (???): https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7361/execution/node/92/log/?consoleFull

Will investigate. Trying again.


Investigation:


Test timeline:
```
22:18:17 RuntimeMemcache Testing binary memcache 
22:18:17   Tests basic memcache operation
22:18:17   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:383
22:20:02 ===================== TEST FAILED =====================
22:20:02 cmd: sudo cilium endpoint list
22:20:02 Exitcode: 1 
22:20:02 Stdout:
22:20:02  	 
22:20:02 Stderr:
22:20:02  	 Error: cannot get endpoint list: Get http:///var/run/cilium/cilium.sock/v1/endpoint: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
22:20:02 	 Is the agent running?
22:20:02 	 
22:20:02 	 
22:20:02 
22:20:02 cmd: sudo cilium policy get
22:20:02 Exitcode: 1 
22:20:02 Stdout:
22:20:02  	 
22:20:02 Stderr:
22:20:02  	 Error: Cannot get policy: Get http:///var/run/cilium/cilium.sock/v1/policy: dial unix /var/run/cilium/cilium.sock: connect: no such file or directory
22:20:02 	 Is the agent running?
22:20:02 	 
22:20:02 	 
22:20:02 
22:20:03 ===================== Existing AfterFailed =====================
22:20:04 <Checks>
22:20:04 Number of "context deadline exceeded" in logs: 0
22:20:04 Number of "level=error" in logs: 0
22:20:04 Number of "level=warning" in logs: 0
22:20:04 Number of "Cilium API handler panicked" in logs: 0
22:20:04 Number of "Goroutine took lock for more than" in logs: 0
22:20:04 
22:20:04 </Checks>
22:20:04 
22:20:04 [[ATTACHMENT|344e237c_RuntimeMemcache_Testing_binary_memcache_Tests_basic_memcache_operation.zip]]
22:20:04 
22:20:04 • Failure in Spec Setup (BeforeEach) [106.922 seconds]
22:20:04 RuntimeMemcache
22:20:04 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:351
22:20:04   Testing binary memcache [BeforeEach]
22:20:04   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:351
22:20:04     Tests basic memcache operation
22:20:04     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:383
22:20:04 
22:20:04     Cilium-agent cannot be started
22:20:04     Expected
22:20:04         <*errors.errorString | 0xc4200c4c60>: {
22:20:04             s: "Timeout reached: Cilium is not ready",
22:20:04         }
22:20:04     to be nil
22:20:04 
22:20:04     /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/runtime/memcache.go:100
22:20:04 ------------------------------
22:20:04 SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSScleaning up VMs started for runtime tests
22:20:07 
22:20:07 
22:20:07 Summarizing 1 Failure:
22:20:07 
22:20:07 [Fail] RuntimeMemcache [BeforeEach] Testing binary memcache Tests basic memcache operation 
22:20:07 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/runtime/memcache.go:100
22:20:07 
22:20:07 Ran 5 of 310 Specs in 710.032 seconds
22:20:07 FAIL! -- 4 Passed | 1 Failed | 0 Pending | 305 Skipped --- FAIL: TestTest (710.04s)
22:20:07 FAIL
```

`cilium.log` from the logs shows that cilium is stopped via systemd:
```
Oct 17 22:18:12 runtime systemd[1]: Stopped cilium.
```

The verifier test ran right before the memcached test:

```
22:18:12 RuntimeVerifier 
22:18:12   runs the kernel verifier against the tree copy of the BPF datapath
22:18:12   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:383
22:18:14 STEP: Stopping Cilium
22:18:14 STEP: Building BPF objects from the tree
22:18:14 STEP: Running the verifier test script
22:18:17 === Test Finished at 2018-10-17T22:18:17Z====
22:18:17 <Checks>
22:18:17 
22:18:17 </Checks>
22:18:17 
22:18:17 
22:18:17 • [SLOW TEST:5.489 seconds]
22:18:17 RuntimeVerifier
22:18:17 /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:351
22:18:17   runs the kernel verifier against the tree copy of the BPF datapath
22:18:17   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:383
22:18:17 ------------------------------
```

I'd expect "Restarting Cilium" to appear in the console output because the following function is called by the verifier test:
```
func (s *SSHMeta) RestartCilium() error {
	ginkgoext.By("Restarting Cilium")
```

But from the `test-output.log` of that test, I don't see that logged anywhere:

```
STEP: Running the verifier test script
time="2018-10-17T22:18:13Z" level=debug msg="running command: sudo /home/vagrant/go/src/github.com/cilium/cilium/test/bpf/verifier-test.sh"
cmd: "sudo /home/vagrant/go/src/github.com/cilium/cilium/test/bpf/verifier-test.sh" exitCode: 0 duration: 3.808953988s stdout:
=> Loading /home/vagrant/go/src/github.com/cilium/cilium/test/bpf/../../bpf/bpf_lb.c:from-netdev...
Note: 8 bytes struct bpf_elf_map fixup performed due to size mismatch!
=> Loading /home/vagrant/go/src/github.com/cilium/cilium/test/bpf/../../bpf/bpf_lxc.c:from-container...
Note: 8 bytes struct bpf_elf_map fixup performed due to size mismatch!
=> Loading /home/vagrant/go/src/github.com/cilium/cilium/test/bpf/../../bpf/bpf_netdev.c:from-netdev...
Note: 8 bytes struct bpf_elf_map fixup performed due to size mismatch!
=> Loading /home/vagrant/go/src/github.com/cilium/cilium/test/bpf/../../bpf/bpf_overlay.c:from-overlay...
Note: 8 bytes struct bpf_elf_map fixup performed due to size mismatch!
=> Skipping /home/vagrant/go/src/github.com/cilium/cilium/test/bpf/../../bpf/bpf_xdp.c.

stderr:
Ensure you have linux >= 4.12 and recent iproute2 to test XDP.

=== Test Finished at 2018-10-17T22:18:17Z====
<Checks>

</Checks>
```

However, this step runs in `AfterAll`; I don't know where `test-output.log` is gathered here.  `cmds.log` confirms this:

```
ls /tmp/
sudo cilium status
sudo docker network create --ipv6 --subnet ::1/112 --driver cilium --ipam-driver cilium cilium-net
sudo docker network inspect cilium-net
sudo cilium config -o json | jq -r '.status.realized["policy-enforcement"]'
sudo cilium config PolicyEnforcement=default
sudo systemctl stop cilium
sudo rm -f /sys/fs/bpf/tc/globals/cilium*
make -C /home/vagrant/go/src/github.com/cilium/cilium/test/../bpf V=0
sudo /home/vagrant/go/src/github.com/cilium/cilium/test/bpf/verifier-test.sh

```

@eloycoto any idea what happened here? To me it looks like the `AfterAll` got skipped for the verifier test.

EDIT: this was caused by #5944

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failure: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7364/

```
2018-10-17T22:43:10.395827144Z level=warning msg="JoinEP: Failed to load program" containerID=9d2be3fdca datapathPolicyRevision=2 desiredPolicyRevision=4 endpointID=45028 error="Failed to replace Qdisc for lxc477fc7e47926: Link not found" file-path=45028_next/bpf_lxc.o ipv4=10.10.1.57 ipv6="f00d::a0a:100:0:afe4" k8sPodName=istio-system/istio-cleanup-secrets-498qp subsys=datapath-loader veth=lxc477fc7e47926
```

I have no further information because there was no bugtool output gathered here. It looks like the test passed, but the checks found that there was a `JoinEP` failure and then failed the test.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failure: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7366/testReport/junit/(root)/runtime/RuntimeCassandra_Tests_policy_allowing_all_actions/

Cassandra tests failed. Unrelated to this PR, but I will investigate nonetheless.

EDIT: starting investigation. Looks like a prior test didn't cleanup:

```
===================== TEST FAILED =====================
cmd: sudo cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])   IPv6                 IPv4           STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                    
	 996        Disabled           Disabled          61974      container:id.app              f00d::a0f:0:0:3e4    10.15.19.55    ready   
	                                                            container:id.service1                                                
```

I'm completely flummoxed by what happened. There is no record in any `test-output.log` that was ran in this PR that shows which test created this container; I have no idea where it came from. 

The endpoint (996, with labels id.app, id.service1), was created at the following time according to Cilium logs:

```
RuntimePolicyEnforcement_Policy_Enforcement_Default_Default_values/cilium-test.log:Oct 17 23:19:15 runtime cilium-agent[10869]: level=debug msg="Endpoint creation" code=OK containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=996 endpointState=waiting-for-identity ipv4= ipv6= k8sPodName=/ policyRevision=0 subsys=endpoint type=0
```

So, I checked the console output in Jenkins to see what else happened at 23:19:15:

```
23:19:14 RuntimePolicyEnforcement Policy Enforcement Default 
23:19:14   Default values
23:19:14   /home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:383
23:19:23 STEP: Setting PolicyEnforcement=default
23:19:23 STEP: Policy Enforcement should be disabled for containers%!(EXTRA func()=0x11437e0)
23:19:23 STEP: Apply a new sample policy
23:19:23 STEP: Setting up policy: /home/vagrant/go/src/github.com/cilium/cilium/test/runtime/manifests/sample_policy.json
23:19:23 === Test Finished at 2018-10-17T23:19:23Z====
```

The RuntimePolicyEnforcement test does the following:
```
	BeforeAll(func() {
		vm = helpers.InitRuntimeHelper(helpers.Runtime, logger)
		ExpectCiliumReady(vm)

		vm.ContainerCreate(appContainerName, helpers.HttpdImage, helpers.CiliumDockerNetwork, "-l id.app")
		areEndpointsReady := vm.WaitEndpointsReady()
		Expect(areEndpointsReady).Should(BeTrue(), "Endpoints are not ready after timeout")
	})
```

The creation of the `-l id.app` container appears to be the culprit, but it does not explain where `id.service1` came from! This is bizarre.

**Comment by ianvernon** [comment]
test-me-please

EDIT: build failed: https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7398/

There was a ton of load on k8s2, the node which the details endpoint, which went into not-ready state, was running:

```
 21:11:27 up 20 min,  0 users,  load average: 17.89, 15.56, 8.53
``` 

Bugtool could not even get the output of `cilium bpf policy get --all --numeric` for the cilium pod running on that node:
```
> Error while running 'cilium bpf policy get --all --numeric':  exec timeout
```

If we cannot even run our debugging tooling in this environment, or get monitor output, that means that there is too much load on the system. In my follow-up commit, I bumped the amount of CPUs and RAM for the K8s 1.12 test to 3 CPUs, and 5120 GB of RAM per VM.  I believe that the baremetal for the CI can handle this added load for at least the K8s 1.12 tests in normal CI runs.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Another failure, but with the runtime tests and there being an improper number of endpoints:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7401/testReport/junit/(root)/runtime/RuntimePolicyEnforcement_Policy_Enforcement_Default_Default_to_Always_without_policy/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failure: 
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7404

Nothing new with respect to the Istio test failures from before. It's bizarre to see PolicyMap counters for DNS to be nonzero but to see drops in the datapath. The CPU / memory increases reduced the load a bit, but the load is still quite high:

```
 00:00:28 up 18 min,  0 users,  load average: 6.42, 6.90, 3.63
```

@joestringer and I discussed how else we can get further introspection into the datapath. I am going to make a function which will run in the background in the CI. It will do the following in the cilium pod running on k8s2:

* dump PolicyMap state 
* dump IPCache state
* dump policy state

This information will be dumped to console in Jenkins for easier debugging. 

I also tried to distill what was happening to see if a reproducer could be made with just one container. Given that the proxy configuration always fails for the details pod, I will work on locally editing the code to do the following:

* import an init policy which allows traffic to kube-dns
* create an endpoint for which that the build will *always* fail. This induced failure will occur after the program for the endpoint is loaded to ensure that we are returning an error at the same point which is occurring in the Istio test.
* see if the endpoint allows L3 connectivity.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
I ran the tests locally, and my machine was almost entirely unresponsive. The load on the K8s2 node is astronomically high:
```
$ uptime
 00:47:13 up  1:51,  1 user,  load average: 13.52, 13.41, 13.76
```


I checked `top`, and `python` processes are consuming a lot of CPU. This is likely due to the microscope pod:
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND   
 5312 root      20   0  397716 248588   4816 R  47.0  6.1  25:03.83 python                                                                                                                                                                
18305 root      20   0   96824  35428   6668 R  43.7  0.9   0:02.32 python                                                                                                                                                                
 5313 root      20   0  290452 194056   4816 R  38.4  4.8  24:58.48 python 
```

**Comment by ianvernon** [comment]
@tgraf I've kept the setup preserved locally if you want me to do any introspection. 

EDIT: I had to delete it because it was making my local setup completely unusable. I tried deleting the microscope pod to see if the load would be reduced, but the pod is stuck being deleted:

```
Events:
  Type    Reason   Age                  From           Message
  ----    ------   ----                 ----           -------
  Normal  Killing  24s (x6 over 8m37s)  kubelet, k8s2  Killing container with id docker://microscope:Need to kill Pod
```

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
Build failed due to the errors downloading the VM used for CI testing:

```
An error occurred while downloading the remote file. The error
16:12:22 message, if any, is reproduced below. Please fix this error and try
16:12:22 again.
16:12:22 
16:12:22 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
```

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/7490/

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
After all of the efforts I went to try to expose what was going on, I realized that there are several issues with my debugging:

* querying the PolicyMap periodically contributed to load on the system, which I believe helped the test *pass*in the CI, because the load it added resulted in enough delay that DNS was able to resolve within the sidecar proxy to access istio-statsd. 

and with the test itself:

* deploying Istio alongside Kubernetes, Cilium, etcd-operator, etc. puts a lot of load on the VMs. Even running locally with 3 CPUs for the test, I was seeing extremely high load numbers (load > 30, etc.). I disabled running microscope in this test, which resulted in the test running much faster and actually passing locally. I think that the scalability of microscope should be analyzed, as it basically bricked my local machine when running the Istio tests.

I added additional logs which state what the content of the PolicyMap for each endpoint is when said PolicyMaps are updated. In the prior build, I checked the logs from an endpoint which failed to have its sidecar proxy configured correctly:

From the istio-sidecar proxy for details-v1-5667f4fd65-qngh6 : 
```
2018-10-23T23:15:17.099428968Z 2018-10-23T23:15:17.099257Z	info	Attempting to lookup address: istio-statsd-prom-bridge.istio-system
```

This eventually fails 15 seconds later:

```
2018-10-23T23:15:32.361372584Z [2018-10-23 23:15:32.361][22][critical][main] external/envoy/source/server/server.cc:80] error initializing configuration '/etc/istio/proxy/envoy-rev0.json': malformed IP address: istio-statsd-prom-bridge.istio-system
```

From the cilium side: 
PolicyMap sync within cilium for this pod began at the following time:
```
2018-10-23T23:15:10.676571163Z level=debug msg="starting policymap sync" containerID=df350bb321 datapathPolicyRevision=0 desiredPolicyRevision=11 endpointID=64725 ipv4=10.10.1.239 ipv6="f00d::a0a:100:0:fcd5" k8sPodName=default/details-v1-5667f4fd65-qngh6 subsys=endpoint
```

PolicyMap entry for kube-dns (with identity 104) is synced: 
```
2018-10-23T23:15:10.676749336Z level=debug msg="dumping endpoint realizedMapState after policy sync" containerID=df350bb321 datapathPolicyRevision=0 desiredPolicyRevision=11 endpointID=64725 ipv4=10.10.1.239 ipv6="f00d::a0a:100:0:fcd5" k8sPodName=default/details-v1-5667f4fd65-qngh6 subsys=endpoint
...
2018-10-23T23:15:10.676874688Z level=debug msg="policy key in datapath" containerID=df350bb321 datapathPolicyRevision=0 desiredPolicyRevision=11 endpointID=64725 ipv4=10.10.1.239 ipv6="f00d::a0a:100:0:fcd5" k8sPodName=default/details-v1-5667f4fd65-qngh6 policyMapKey="Egress: 104" policyMapValue=0 subsys=endpoint
...
2018-10-23T23:15:10.679120998Z level=debug msg="ending policymap sync" containerID=df350bb321 datapathPolicyRevision=0 desiredPolicyRevision=11 endpointID=64725 ipv4=10.10.1.239 ipv6="f00d::a0a:100:0:fcd5" k8sPodName=default/details-v1-5667f4fd65-qngh6 subsys=endpoint
```

BPF compilation succeeded before the sidecar proxy was launched:
```
2018-10-23T23:15:10.715305009Z level=debug msg="Preparing to compile BPF" bpfHeaderfilesChanged=true containerID=df350bb321 datapathPolicyRevision=0 desiredPolicyRevision=11 endpointID=64725 ipv4=10.10.1.239 ipv6="f00d::a0a:100:0:fcd5" k8sPodName=default/details-v1-5667f4fd65-qngh6 subsys=endpoint
2018-10-23T23:15:11.653989272Z level=info msg="Recompiled endpoint BPF program" BPFCompilationTime=938.898338ms containerID=df350bb321 datapathPolicyRevision=0 desiredPolicyRevision=11 endpointID=64725 error="<nil>" ipv4=10.10.1.239 ipv6="f00d::a0a:100:0:fcd5" k8sPodName=default/details-v1-5667f4fd65-qngh6 subsys=endpoint
```

So, there is nothing wrong from the Cilium side here. This looks more like an istio problem.

**Comment by ianvernon** [comment]
https://github.com/istio/istio/issues/5379 is related. It's weird though, because we wait for `istio-statsd-prom-bridge.istio-system.svc.cluster.local` to be ready in the test initialization *before* we start the bookinfo pods whose sidecar proxies cannot be configured. I wonder if the lookup for `istio-statsd-prom-bridge.istio-system.svc.cluster.local` succeeds, but lookups for `istio-statsd-prom-bridge.istio-system` don't succeed? I don't see why that would make sense... but, who knows :)

**Comment by ianvernon** [comment]
OK, with the awesome help of @joestringer we have discovered what the cause of why `istio-statsd-prom-bridge.istio-system` cannot be resolved to an IP by the sidecar proxy. I had to reproduce this locally.

The following pod restarted on my local setup. From `kubectl get pods --all-namespaces -o wide`:

```
default        ratings-v1-5d5bc95df7-n7skt                 2/2     Running     1          5m59s   10.10.1.220     k8s2   <none>
```

Cilium pod on node k8s2:
```
kube-system    cilium-2dvwm                                1/1     Running     0          37m     192.168.36.12   k8s2   <none>
```

Previous logs from the `istio-proxy` that show when initial DNS lookup has occurred:
```
$ kubectl logs ratings-v1-5d5bc95df7-n7skt --previous istio-proxy
2018-10-24T21:16:44.362194Z	info	Version root@localhost-docker.io/istio-a29e304c6be717e0f970dabd77b27ffb3061463b-a29e304c6be717e0f970dabd77b27ffb3061463b-Clean
2018-10-24T21:16:44.363237Z	info	Proxy role: model.Proxy{ClusterID:"", Type:"sidecar", IPAddress:"10.10.1.220", ID:"ratings-v1-5d5bc95df7-n7skt.default", Domain:"default.svc.cluster.local", Metadata:map[string]string(nil)}
2018-10-24T21:16:44.363266Z	info	Attempting to lookup address: istio-statsd-prom-bridge.istio-system
```

Key takeaway: DNS request went out at  `21:16:44.363266Z`.

I had `cilium monitor | ts` installed in each Cilium pod while the test was running.

The following are drops on *ingress* to kube-dns from identity 60062 to 104 (kube-dns identity) corresponding to the lookup above:
```
Oct 24 21:16:45 xx drop (Policy denied (L3)) flow 0xabf9089d to endpoint 52931, identity 60062->104: 10.10.1.220:45304 -> 10.10.1.254:53 udp
Oct 24 21:16:45 xx drop (Policy denied (L3)) flow 0x2a037375 to endpoint 52931, identity 60062->104: 10.10.1.220:59916 -> 10.10.1.254:53 udp
Oct 24 21:16:49 xx drop (Policy denied (L3)) flow 0xe5a3a972 to endpoint 52931, identity 60062->104: 10.10.1.220:41763 -> 10.10.1.254:53 udp
Oct 24 21:16:49 xx drop (Policy denied (L3)) flow 0xec4c6771 to endpoint 52931, identity 60062->104: 10.10.1.220:46434 -> 10.10.1.254:53 udp
Oct 24 21:16:51 xx drop (Policy denied (L3)) flow 0x97d60f7f to endpoint 52931, identity 17336->104: 10.10.0.17:35501 -> 10.10.1.254:53 udp
Oct 24 21:16:51 xx drop (Policy denied (L3)) flow 0x97d60f7f to endpoint 52931, identity 17336->104: 10.10.0.17:35501 -> 10.10.1.254:53 udp
Oct 24 21:16:54 xx drop (Policy denied (L3)) flow 0x8641fcd2 to endpoint 52931, identity 60062->104: 10.10.1.220:59882 -> 10.10.1.254:53 udp
Oct 24 21:16:54 xx drop (Policy denied (L3)) flow 0x8b722ff6 to endpoint 52931, identity 60062->104: 10.10.1.220:39426 -> 10.10.1.254:53 udp
```

This means that kube-dns did not have knowledge of that identity at the time the request was initiated. This is because there is propagation delay from the syncing of the identity of the ratings endpoint (60062) to the key-value store , and to the kube-dns pod. The policy map for the kube-dns pod is only updated when a regeneration is triggered for it, which doesn't occur for some time because of the amount of load on the system. Given that we gate the number of concurrent regenerations at 2, if kube-dns doesn't get selected to regenerate quickly after the identity 60062 is synced, it won't be added to its policy map for some time:

```
$ cilium endpoint log 52931
Timestamp              Status    State                   Message
2018-10-24T21:18:18Z   OK        ready                   Successfully regenerated endpoint program (Reason: one or more identities created or deleted)
2018-10-24T21:18:18Z   OK        ready                   Completed endpoint regeneration with no pending regeneration requests
2018-10-24T21:18:18Z   OK        regenerating            Regenerating endpoint: one or more identities created or deleted
2018-10-24T21:16:27Z   Warning   waiting-to-regenerate   Skipped invalid state transition to waiting-to-regenerate due to: Triggering endpoint regeneration due to one or more identities created or deleted
2018-10-24T21:16:26Z   Warning   waiting-to-regenerate   Skipped invalid state transition to waiting-to-regenerate due to: Triggering endpoint regeneration due to one or more identities created or deleted
2018-10-24T21:16:25Z   Warning   waiting-to-regenerate   Skipped invalid state transition to waiting-to-regenerate due to: Triggering endpoint regeneration due to one or more identities created or deleted
2018-10-24T21:16:24Z   OK        waiting-to-regenerate   Triggering endpoint regeneration due to one or more identities created or deleted
...
```

The endpoint only begins to regenerate at 21:18:18 - about 1.5 minutes *after* the identity has been propagated to the node.

The ratings endpoint was added at 21:16:24
```
# cilium endpoint log 33970
Timestamp              Status    State                   Message
...
2018-10-24T21:16:24Z   OK        waiting-to-regenerate   Triggering endpoint regeneration due to one or more identities created or deleted
2018-10-24T21:16:24Z   OK        regenerating            Regenerating endpoint: updated security labels
2018-10-24T21:16:24Z   OK        waiting-to-regenerate   Triggering regeneration due to new identity
2018-10-24T21:16:24Z   OK        ready                   Set identity for this endpoint
2018-10-24T21:16:24Z   OK        waiting-for-identity    Endpoint creation
```

This occurs despite policy allowing all for kube-dns on ingress and egress, because we synthesize an allow-all for policy by inserting all identities into the policy map for a given endpoint. But, if there is a large delay in updating the policy map, that means that some traffic which should be allowed to kube-dns gets dropped because the identity isn't plumbed into the policy map for kube-dns. This is nondeterministic behavior.

**Comment by ianvernon** [comment]
Working on a simple reproducer locally to validate this.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
@tgraf I've saved the Istio test re-enabling in another PR because it is dependent on 
https://github.com/cilium/cilium/pull/6047 being merged. I think this is OK to be merged in the mean time since it helps provide more visibility into the lifecycle of an endpoint.

File: pkg/endpoint/bpf.go [hunk 5]
```diff
@@ -732,7 +732,16 @@ func (e *Endpoint) regenerateBPF(owner Owner, currentDir, nextDir string, regenC
...
```
Comment (tgraf) [inline pkg/endpoint/bpf.go:737]: Before this, the lxcmap update was done last so when the initial endpoint build failed for whatever reason, no entry would exist in the lxcmap and the endpoint couldn't be found. With this, we may leave behind a stale entry in the lxcmap for a program that does not exist. I think we should check whether this is the first build ever, and if so, undo the lxcmap entry by deleting the entry again in the error case to not leave behind an lxcmap entry if no BPF program exists.

**Review by tgraf — CHANGES_REQUESTED** [review]

File: pkg/endpoint/bpf.go [hunk 6]
```diff
@@ -20,6 +20,7 @@ import (
 	"crypto/md5"
 	"encoding/hex"
 	"fmt"
+	"github.com/cilium/cilium/pkg/maps/lxcmap"
```
Comment (aanm) [inline pkg/endpoint/bpf.go]: imports order

File: pkg/endpoint/endpoint.go [hunk 7]
```diff
@@ -471,6 +471,8 @@ type Endpoint struct {
 	// is enabled for this endpoint.
 	egressPolicyEnabled bool
 
+	hasBPFProgram chan struct{}
```
Comment (aanm) [inline pkg/endpoint/endpoint.go:474]: Replace with an int32

File: pkg/endpoint/endpoint.go [hunk 8]
```diff
@@ -482,6 +484,28 @@ type Endpoint struct {
...
+	case <-e.hasBPFProgram:
+	default:
+		close(e.hasBPFProgram)
+	}
+}
+
+// HasBPFProgram returns whether a BPF program has been generated for this
+// endpoint.
+func (e *Endpoint) HasBPFProgram() bool {
+	select {
```
Comment (aanm) [inline pkg/endpoint/endpoint.go:501]: return atomic.LoadInt32(&e.hasBPFProgram) == 1

File: pkg/endpoint/endpoint.go [hunk 9]
```diff
@@ -482,6 +484,28 @@ type Endpoint struct {
 	DeprecatedOpts deprecatedOptions `json:"Opts"`
 }
 
+// CloseBPFProgramChannel closes the channel that signals whether the endpoint
+// has had its BPF program compiled. If the channel is already closed, this is
+// a no-op.
+func (e *Endpoint) CloseBPFProgramChannel() {
+	select {
```
Comment (aanm) [inline pkg/endpoint/endpoint.go:491]: `atomic.StoreInt32(&e.hasBPFProgram2, 1)`

**Review by aanm — CHANGES_REQUESTED** [review]

File: pkg/endpoint/bpf.go (hunk 5 above)
Comment (tgraf) [reply pkg/endpoint/bpf.go:737]: Discussed offline. This is fine as the program is already kept for egress. An error will be returned to CNI and CNI will remove the endpoint altogether again.

**Review by tgraf — APPROVED** [review]

File: pkg/endpoint/bpf.go (hunk 5 above)
Comment (ianvernon) [reply pkg/endpoint/bpf.go:737]: Discussed offline.

If CNI add fails, then the endpoint will be deleted, including its lxcmap entry, so we don't have to clean up if this fails here. The program itself has been installed at this point.

File: pkg/endpoint/bpf.go (hunk 6 above)
Comment (ianvernon) [reply pkg/endpoint/bpf.go]: Fixed.

File: pkg/endpoint/endpoint.go (hunk 7 above)
Comment (ianvernon) [reply pkg/endpoint/endpoint.go:474]: This is up to developer preference, so I'm not going to change this. The nice thing about having a channel is that if we want to in the future, we can block on the endpoint not having a BPF program installed yet.

**Comment by ianvernon** [comment]
test-me-please

**Comment by ianvernon** [comment]
This needs to be backported to v1.3 and v1.2 for Istio integration to work.
