### PR TITLE
identity: remove labels on CID

### LINKED ISSUE #16579: Cannot create CiliumIdentity for ServiceAccount names longer than 63 chars
## Bug report

I found this bug while trying out EMR on EKS on a Cilium-enabled EKS1.20 cluster.

When a service account's name is longer than 63 characters, it is not possible to start a pod using this service account.

Indeed, when creating the `CiliumIdentity`, Cilium will set a label `io.cilium.k8s.policy.serviceaccount` whose value will be the name of the service account for that pod. However, label values are limited to a maximum of 63 characters. Service Account names can be up to 253 characters long.

**General Information**

- Cilium version: v1.9.7
- Kernel version: 5.5.4.117-58.216.amzn2.x86_64
- Orchestration system version in use: EKS 1.20

**How to reproduce the issue**

1. Create a service account with a name longer than 63 characters

```bash
$ kubectl create sa emr-containers-sa-spark-executor-123456789012-h94a5lkq1wmdnn0lu3ldn86aul757y413dgn7tj9zmkq4tujzz4mzp
```

2. Create a pod using this serviceAccount
```bash
$ cat <<EOT >> pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
  namespace: emr
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
  serviceAccountName: emr-containers-sa-spark-executor-123456789012-h94a5lkq1wmdnn0lu3ldn86aul757y413dgn7tj9zmkq4tujzz4mzp
EOT
$ kubectl apply -f pod.yaml
```

Then after a while the pod will fail to start:
```bash
$ kubectl describe pod static-web
Name:         static-web
Namespace:    emr
Priority:     0
Node:         ip-10-210-158-23.eu-west-1.compute.internal/10.210.158.23
Start Time:   Thu, 17 Jun 2021 14:03:05 +0200
Labels:       role=myrole
Annotations:  kubernetes.io/psp: eks.privileged
Status:       Pending
IP:           
IPs:          <none>
Containers:
  web:
    Container ID:   
    Image:          nginx
    Image ID:       
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from emr-containers-sa-spark-executor-123456789012-h94a5lkq1wmdqrkqt (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  emr-containers-sa-spark-executor-123456789012-h94a5lkq1wmdqrkqt:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  emr-containers-sa-spark-executor-123456789012-h94a5lkq1wmdqrkqt
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age                  From               Message
  ----     ------                  ----                 ----               -------
  Normal   Scheduled               5m29s                default-scheduler  Successfully assigned emr/static-web to ip-10-210-158-23.eu-west-1.compute.internal
  Warning  FailedCreatePodSandBox  3m58s                kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "e2b35de5c07d64130ebc14ee80e9c936350ad0f8973357ae1f8641bb3edf2270" network for pod "static-web": networkPlugin cni failed to set up pod "static-web_emr" network: Unable to create endpoint: Cilium API client timeout exceeded
  Warning  FailedCreatePodSandBox  2m27s                kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "8f7a714de44b928728a21066979bd0a5421d29f9215471b6980c67e817da5924" network for pod "static-web": networkPlugin cni failed to set up pod "static-web_emr" network: Unable to create endpoint: Cilium API client timeout exceeded
  Warning  FailedCreatePodSandBox  56s                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "c60b6d3993dd53224453ec36877cec1ae3bfcd6334049cb4f76d3620419495da" network for pod "static-web": networkPlugin cni failed to set up pod "static-web_emr" network: Unable to create endpoint: Cilium API client timeout exceeded
  Normal   SandboxChanged          55s (x3 over 3m57s)  kubelet            Pod sandbox changed, it will be killed and re-created.
```

And then we will see this in Cilium logs:
```
level=warning msg="Key allocation attempt failed" attempt=10 error="unable to allocate ID 2664 for key [k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=emr-containers-sa-spark-executor-123456789012-h94a5lkq1wmdnn0lu3ldn86aul757y413dgn7tj9zmkq4tujzz4mzp k8s:io.kubernetes.pod.namespace=emr k8s:role=myrole]: CiliumIdentity.cilium.io \"2664\" is invalid: metadata.labels: Invalid value: \"emr-containers-sa-spark-executor-123456789012-h94a5lkq1wmdnn0lu3ldn86aul757y413dgn7tj9zmkq4tujzz4mzp\": must be no more than 63 characters" key="[k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=emr-containers-sa-spark-executor-123456789012-h94a5lkq1wmdnn0lu3ldn86aul757y413dgn7tj9zmkq4tujzz4mzp k8s:io.kubernetes.pod.namespace=emr k8s:role=myrole]" subsys=allocator
```

### PR DESCRIPTION
**Pull request by marseel**
As we don't use labels from CiliumIdentities, let's remove them.
Labels have restriction of 63 characters and when someone created a
serviceaccount with name longer than 63, we were trying to add it to
labels of CiliumIdentity. This resulted in failure of creating CID and
failure to start pod.
We only keep namespace label as it's used when listing ciliumidentities
through kubectl, example:
```
$ k get ciliumidentities.cilium.io 
NAME    NAMESPACE            AGE
21391   kube-system          45m
22578   local-path-storage   45m
9551    default              45m
```

Fixes: https://github.com/cilium/cilium/issues/16579

```release-note
Creating pod with long (>63 characters) serviceaccount name works now 
```

### CODE REVIEW

File: pkg/k8s/identitybackend/identity.go [hunk 1]
```diff
@@ -61,50 +59,35 @@ type crdBackend struct {
 func (c *crdBackend) DeleteAllKeys(ctx context.Context) {
 }
 
-func (c *crdBackend) DeleteID(ctx context.Context, id idpool.ID) error {
-	return c.Client.CiliumV2().CiliumIdentities().Delete(ctx, id.String(), metav1.DeleteOptions{})
+// Select Labels that should be added to CRD CiliumIdentity objects
+// If we ever want to add new label, we need to ensure that it has a length
+// lower than 63 characters.
```
Comment (sypakine) [inline pkg/k8s/identitybackend/identity.go]: `no greater than 63 characters`

File: pkg/k8s/identitybackend/identity_test.go [hunk 2]
```diff
@@ -24,64 +24,43 @@ import (
...
 )
 
-func TestSanitizeK8sLabels(t *testing.T) {
+func TestSelectK8sLabels(t *testing.T) {
 	path := field.NewPath("test", "labels")
 	testCases := []struct {
 		input            map[string]string
 		selected         map[string]string
-		skipped          map[string]string
 		validationErrors field.ErrorList
```
Comment (sypakine) [inline pkg/k8s/identitybackend/identity_test.go]: Can remove this as well; all test cases have empty error list

**Review by sypakine — APPROVED** [review]
Thanks for digging into this!

**Review by bimmlerd — APPROVED** [review]
LGTM code-wise, but is this a breaking change for folks somehow consuming labels on CiliumIdentity? Does it need to be mentioned in the docs somewhere?

**Review by joamaki — APPROVED** [review]

**Comment by marseel** [comment]
> LGTM code-wise, but is this a breaking change for folks somehow consuming labels on CiliumIdentity? Does it need to be mentioned in the docs somewhere?

I don't have a strong opinion, I can add it if you have strong opinion on it. CiliumIdentity is kind of an implementation detail ;)

File: pkg/k8s/identitybackend/identity.go [hunk 3]
```diff
@@ -61,50 +59,35 @@ type crdBackend struct {
 func (c *crdBackend) DeleteAllKeys(ctx context.Context) {
 }
 
-func (c *crdBackend) DeleteID(ctx context.Context, id idpool.ID) error {
-	return c.Client.CiliumV2().CiliumIdentities().Delete(ctx, id.String(), metav1.DeleteOptions{})
+// Select Labels that should be added to CRD CiliumIdentity objects
```
Comment (squeed) [inline pkg/k8s/identitybackend/identity.go]: nit: can you make it super clear that these are the labels in the `metadata.Labels`, and are thus "advisory" and have no bearing on the actual security identity? Otherwise I foresee confusion.

**Comment by squeed** [comment]
This seems extremely reasonable! I agree that there *could* be someone relying on this, but I don't see it as published API. That said, we should probably add a release note and not backport this, on the off chance that is relied on.

(There may be some `kubectl get -l XXX` scripts out there).

**Review by qmonnet — APPROVED** [review]
OK for the docs, thanks!

**Comment by julianwiedmann** [comment]
@marseel given it's labeled as `release-note/bug`, should this be backported? Or is the impact sufficiently low severity?

**Comment by marseel** [comment]
> given it's labeled as release-note/bug, should this be backported? Or is the impact sufficiently low severity?

@julianwiedmann too low severity.
Also see Casey's comment, which I fully agree with:

> This seems extremely reasonable! I agree that there could be someone relying on this, but I don't see it as published API. That said, we should probably add a release note and not backport this, on the off chance that is relied on.
