### PR TITLE
cilium-cli: add external-other-target arg to connectivity tests

### LINKED ISSUE #35553: Add support for Cilium connectivity test on IPv6-only clusters
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

When running `cilium connectivity test` there is the assumption that the user can reach `1.1.1.1` which isn't the case in IPv6-only deployments, and as it is an IP, even with NAT64.

I did also try `cilium connectivity test --external-ip "2606:4700:4700::1111" --external-other-ip "2606:4700:4700::1001" --external-cidr "2606:4700:4700::/48"`, but it parses the last segment of IPv6 address to ports (putting them in square brackets straight up crashes it, and specifying a port like `2606:4700:4700::1111:443` after seems to work-ish but is surprising and non-obvious, and seems to still cause the tests to fail).

### How can we reproduce the issue?

- Install with IPv6 connectivity only.
- Run `cilium connectivity test`

### Cilium Version

1.16.2

### Kernel Version

6.8.0-47-generic

### Kubernetes Version

v1.30.5+k3s1

### Regression

_No response_

### Sysdump

N/a

### Relevant log output

N/a

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by wedaly**
Allow overriding the "blocked" domain in the test using `--external-other-target` instead of hard-coding cilium.io

This is a workaround for failing `to-fqdn` tests in IPv6-only cluster. These fail because "cilium.io" doesn't have an AAAA record, so `curl` tries to connect to the IPv4 address and fails with a different error code than the one expected by the test (network unreachable instead of timeout).

Fixes: #35553

```release-note
Add --external-other-target parameter to cilium CLI connectivity tests.
```

### CODE REVIEW

File: cilium-cli/connectivity/tests/world.go [hunk 1]
```diff
@@ -70,7 +70,7 @@ func (s *podToWorld) Run(ctx context.Context, t *check.Test) {
 	}
 }
 
-// PodToWorld2 sends an HTTPS request to cilium.io from from random client
+// PodToWorld2 sends an HTTPS request to ExternalOtherTarget from from random client
```
Comment (derailed) [inline cilium-cli/connectivity/tests/world.go]: nit: from from -> from

File: cilium-cli/connectivity/tests/world.go [hunk 2]
```diff
@@ -96,7 +97,7 @@ func (s *podToWorld2) Run(ctx context.Context, t *check.Test) {
 
 	for _, client := range ct.ClientPods() {
```
Comment (derailed) [inline cilium-cli/connectivity/tests/world.go:98]: Not sure why we are managing the index outside the loop? Seems we could use for i, client := range t.Context().ClientPods{}. This also eliminate the need to declare ct var since it is only used in the scope of the loop?

**Review by derailed — COMMENTED** [review]
@wedaly Thank you for this update!

File: cilium-cli/connectivity/tests/world.go (hunk 2 above)
Comment (wedaly) [reply cilium-cli/connectivity/tests/world.go:98]: Discovered from a failing lint check: `ct.ClientPods()` returns `map[string]Pod`, so the key is a string and `Sprintf()` is expecting an int.

If it's okay I'm going to keep this as-is for now. Could revisit in a follow-up PR to clean this up everywhere (there's at least one other place in the file using the same `var i int` pattern)

**Review by derailed — APPROVED** [review]

**Comment by julianwiedmann** [comment]
@sayboras :ping_pong: would be nice to see this merged, wdyt?

**Review by sayboras — APPROVED** [review]
Thanks
