### PR TITLE
redirectpolicy: Check lrp type before restoring lrp service

### LINKED ISSUE #13736: Panic when going through LRP gsg
on step "If you see an error like “request blocked by whitelist-route-regexp” while running requests to the metadata server, then you may need to whitelist the metadata requests by passing the below argument to the kiam-agent Deamonset." I misconfigured kiam and caused it to crash. this somehow triggered Cilium to crash.

logs from failing pods are here:
[panic.log](https://github.com/cilium/cilium/files/5431668/panic.log)
[panic2.log](https://github.com/cilium/cilium/files/5431669/panic2.log)

Based on cursory look at panic stack trace, this was directly caused by crash of kiam pods, which are AFAIU, a policy backend?

Panic stack trace:
```
Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 226 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x2250fa0, 0x3a62f30)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x2250fa0, 0x3a62f30)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).notifyPolicyBackendDelete(0xc000a0ec30, 0xc000acb900, 0xc000d547e0)
	/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:442 +0x316
github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).deletePolicyBackends(0xc000a0ec30, 0xc000acb900, 0xc000b74770, 0x10, 0xc000b74780, 0x7)
	/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:417 +0x1c5
github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).OnUpdatePodLocked(0xc000a0ec30, 0xc001228ea0, 0x3a90001)
	/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:266 +0x3af
github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).OnUpdatePod(0xc000a0ec30, 0xc001228ea0, 0xc001660000)
	/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:285 +0x8e
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).updateK8sPodV1(0xc000661380, 0xc000e6d200, 0xc001228ea0, 0x2739120, 0xc001bf3c00)
	/go/src/github.com/cilium/cilium/pkg/k8s/watchers/pod.go:287 +0x402
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).createPodController.func2(0x25a30e0, 0xc000e6d200, 0x25a30e0, 0xc001228ea0)
	/go/src/github.com/cilium/cilium/pkg/k8s/watchers/pod.go:88 +0x11f
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:234
github.com/cilium/cilium/pkg/k8s/informer.NewInformerWithStore.func1(0x2283f00, 0xc00025c520, 0x1, 0xc00025c520)
	/go/src/github.com/cilium/cilium/pkg/k8s/informer/informer.go:114 +0x31c
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc000acadc0, 0xc000ab7a80, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:501 +0x229
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc00018f050)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:179 +0x42
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000af8f90)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001bf3f90, 0x29436a0, 0xc0008c9140, 0xc000481d01, 0xc000c7fc80)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000af8f90, 0x3b9aca00, 0x0, 0xc000356401, 0xc000c7fc80)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*controller).Run(0xc00018f050, 0xc000c7fc80)
	/go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:150 +0x2ce
created by github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).podsInit.func1
	/go/src/github.com/cilium/cilium/pkg/k8s/watchers/pod.go:129 +0x36c
```

### PR DESCRIPTION
**Pull request by aditighag**
This fixes the regression caused by commit b553f49, whereby not checking the lrp type before restoring clusterIP service would lead to nil pointer access for `addressMatcher` lrps that don't have the `serviceID` field set in the lrp config. As there is no backing k8s service for such lrps, they don't need restore.

Here is the stack trace - 

level=info msg="Observed a panic: \"invalid memory address or nil pointer dereference\" (runtime error: invalid memory address or nil pointer dereference)" subsys=klog
level=info msg="goroutine 171 [running]:" subsys=klog
:
level=info msg="\t/usr/local/go/src/runtime/panic.go:969 +0x1b9" subsys=klog
level=info msg="github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).notifyPolicyBackendDelete(0xc000706480, 0xc0009790e0, 0xc000d8d2c0)" subsys=klog
**level=info msg="\t/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:452 +0x316" subsys=klog**
level=info msg="github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).deletePolicyBackends(0xc000706480, 0xc0009790e0, 0xc00038ec80, 0x10, 0xc00038ec65, 0x7)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:427 +0x1c5" subsys=klog
level=info msg="github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).OnUpdatePodLocked(0xc000706480, 0xc000de5d40, 0x3ad0001)" subsys=klog
level=info msg="\t/go/src/github.com/cilium/cilium/pkg/redirectpolicy/manager.go:277 +0x3af" subsys=klog
level=info msg="github.com/cilium/cilium/pkg/redirectpolicy.(*Manager).OnUpdatePod(0xc000706480, 0xc000de5d40, 0xc000cd0000)" subsys=klog

Fixes: [b553f49](https://github.com/cilium/cilium/commit/b553f492df0c7e3188fafe870973f3345700c83b)
Fixes: #13736 

[1] https://github.com/cilium/cilium/blob/master/pkg/redirectpolicy/manager.go#L452

### CODE REVIEW

**Comment by joestringer** [comment]
:facepalm: Github really doesn't like multiple people making single-label changes at once, haha. The commit which this fixes was in `1.9.0-rc2` so we can mark it as `release-note/bug`. Agree it should be backported to 1.9. Also release-blocker from the issue that this is fixing.

**Comment by aditighag** [comment]
test-me-please

**Comment by aditighag** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by aditighag** [comment]
test-runtime

**Comment by aditighag** [comment]
test-gingko

**Comment by aditighag** [comment]
test-ginkgo

**Comment by aditighag** [comment]
restart-ginkgo

**Comment by aditighag** [comment]
Ginkgo test had already passed. I meant to retest the gke test.

**Comment by aditighag** [comment]
test-gke

**Review by nebril — APPROVED** [review]

**Comment by nebril** [comment]
retest-runtime

**Review by Weil0ng — APPROVED** [review]

File: pkg/redirectpolicy/manager.go [hunk 1]
```diff
@@ -449,10 +449,12 @@ func (rpm *Manager) notifyPolicyBackendDelete(config *LRPConfig, frontendMapping
 			log.WithError(err).Errorf("Local redirect service for policy (%v)"+
 				" with frontend (%v) not deleted", config.id, frontendMapping.feAddr)
 		}
-		if restored := rpm.svcCache.EnsureService(*config.serviceID, lock.NewStoppableWaitGroup()); restored {
-			log.WithFields(logrus.Fields{
-				logfields.K8sSvcID: *config.serviceID,
-			}).Info("Restored service")
+		if config.lrpType == lrpConfigTypeSvc {
```
Comment (ti-mo) [inline pkg/redirectpolicy/manager.go:452]: This doesn't actually solve the nil deref. We could go for:

```suggestion
		if config.lrpType == lrpConfigTypeSvc && config.serviceID != nil {
```

or:

```suggestion
		if config.lrpType == lrpConfigTypeSvc {
			if config.serviceID == nil {
				// log an error
			}
```

Comment (aditighag) [reply pkg/redirectpolicy/manager.go:452]: The field will not be `nil` for a service matcher LRP by contract [1]. We also sanitize the config before it gets stored in the internal map [2]. 

[1] https://github.com/cilium/cilium/blob/master/pkg/k8s/apis/cilium.io/v2/clrp_types.go#L91
[2] https://github.com/cilium/cilium/blob/master/pkg/redirectpolicy/redirectpolicy.go#L220

Comment (ti-mo) [reply pkg/redirectpolicy/manager.go:452]: Sure thing, but do we prefer a panic+crash in case it's nil due to someone introducing a bug?

Comment (aditighag) [reply pkg/redirectpolicy/manager.go:452]: It won't be `nil`, check my previous comment. Regardless, I don't want to pepper the entire code with such redundant checks. I would rather have such code paths validated by CI/unit tests (it's in my TODO list). :)

**Review by joestringer — APPROVED** [review]
Given that the LRP manager only tracks the overwritten services in the case that the LRP has a ServiceMatcher, I think this is correct here.

I do wonder idly in the background whether it's possible to configure a service and then configure an LRP using AddressMatcher which selects the same address, and then if you configure this combination, it will break the service and not have a way to properly restore it (without deleting the LRP & restarting Cilium), but that seems like a more rare case.

**Comment by aditighag** [comment]
> I do wonder idly in the background whether it's possible to configure a service and then configure an LRP using AddressMatcher which selects the same address, and then if you configure this combination, it will break the service and not have a way to properly restore it (without deleting the LRP & restarting Cilium), but that seems like a more rare case.

That seems plausible on surface. Based on the gsg instructions, users should not create an AddressMatcher LRP for services. But I'm not sure if it's worthwhile to enforcing this in the code (e.g., look up frontend of every addressMatcher LRP in the `services` map). The redirect policy manager won't track k8s service objects for AddressMatcher LRPs so such configurations will be broken anyway.

**Comment by joestringer** [comment]
Yeah I think that case is straying fairly far off the beaten path. It seems pretty unlikely to me that a user will configure an LRP specifically with a service address but without using the servicematcher, so it's probably not necessary to put any guardrails in place (eg warning logs or logic to handle the case).
