### PR TITLE
clustermesh: correctly remove remoteCache on connection disruption

### LINKED ISSUE #13446: 'cilium-agent' memory leak, possibly due to cluster mesh
## Bug report

**General Information**

- Cilium version (run `cilium version`):
```
Client: 1.8.3 54cf3810d 2020-09-04T14:01:53+02:00 go version go1.14.7 linux/amd64
Daemon: 1.8.3 54cf3810d 2020-09-04T14:01:53+02:00 go version go1.14.7 linux/amd64
```
- Kernel version (run `uname -a`): `Linux ip-10-2-36-164.ap-northeast-1.compute.internal 4.14.193-149.317.amzn2.x86_64 #1 SMP Thu Sep 3 19:04:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**How to reproduce the issue**

I'm not exactly sure how to reproduce it. The setup is 2 k8s clusters, connected using cluster mesh on AWS. Everything seemed to be working fine, until I noticed pods kept getting evicted. It seems like the memory usage for `cilium-agent` just kept rising, while trying to connect to the remote etcd cluster.

Sorry I haven't extracted the full logs, this is a production setup that needed to be fixed ASAP (basically restarted everything to make it work again). I'll keep monitoring now again to see if it happens and will provide full logs if so.

image

The repeating logs are (from Loki):

```
2020-10-07T12:23:27+03:00 {} level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
2020-10-07T12:23:27+03:00 {} level=info msg="Connecting to etcd server..." config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" subsys=kvstore
2020-10-07T12:23:27+03:00 {} level=warning msg="Error observed on etcd connection, reconnecting etcd" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 error="not able to connect to any etcd endpoints" kvstoreErr="not able to connect to any etcd endpoints" kvstoreStatus="not able to connect to any etcd endpoints" subsys=clustermesh
2020-10-07T12:23:27+03:00 {} level=info msg="Established connection to remote etcd" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 kvstoreErr="not able to connect to any etcd endpoints" kvstoreStatus="not able to connect to any etcd endpoints" subsys=clustermesh
2020-10-07T12:23:27+03:00 {} level=info msg="Connection to remote cluster established" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 kvstoreErr="<nil>" kvstoreStatus= subsys=clustermesh
2020-10-07T12:23:27+03:00 {} level=info msg="Successfully verified version of etcd endpoint" config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" etcdEndpoint="https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271" subsys=kvstore version=3.3.12
2020-10-07T12:23:25+03:00 {} {"level":"warn","ts":"2020-10-07T09:23:25.247Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthrough:///https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
2020-10-07T12:23:16+03:00 {} level=info msg="Initial etcd session established" config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" subsys=kvstore
2020-10-07T12:23:16+03:00 {} level=info msg="Got lock lease ID f0a74d136d82b3a" subsys=kvstore
2020-10-07T12:23:16+03:00 {} level=info msg="Got lease ID f0a74d136d82b38" subsys=kvstore
2020-10-07T12:23:06+03:00 {} {"level":"warn","ts":"2020-10-07T09:23:06.482Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-2e1ac3d5-992f-47d1-b0bb-4f49625602d2/prod-k8s-ap-northeast-1.mesh.cilium.io:32271","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}
2020-10-07T12:23:05+03:00 {} level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
2020-10-07T12:23:05+03:00 {} level=info msg="Connecting to etcd server..." config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" subsys=kvstore
2020-10-07T12:23:05+03:00 {} level=warning msg="Error observed on etcd connection, reconnecting etcd" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 error="not able to connect to any etcd endpoints" kvstoreErr="not able to connect to any etcd endpoints" kvstoreStatus="not able to connect to any etcd endpoints" subsys=clustermesh
2020-10-07T12:23:05+03:00 {} level=info msg="Established connection to remote etcd" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 kvstoreErr="not able to connect to any etcd endpoints" kvstoreStatus="not able to connect to any etcd endpoints" subsys=clustermesh
2020-10-07T12:23:04+03:00 {} level=info msg="Connection to remote cluster established" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 kvstoreErr="<nil>" kvstoreStatus= subsys=clustermesh
2020-10-07T12:23:04+03:00 {} level=info msg="Successfully verified version of etcd endpoint" config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" etcdEndpoint="https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271" subsys=kvstore version=3.3.12
2020-10-07T12:23:02+03:00 {} {"level":"warn","ts":"2020-10-07T09:23:02.996Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthrough:///https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
2020-10-07T12:22:55+03:00 {} level=info msg="Reloaded endpoint BPF program" containerID= datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=809 identity=1 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2020-10-07T12:22:54+03:00 {} level=info msg="Reloaded endpoint BPF program" containerID= datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=2729 identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2020-10-07T12:22:54+03:00 {} level=info msg="Reloaded endpoint BPF program" containerID=df2377d1f2 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=102 identity=106 ipv4=10.1.47.33 ipv6= k8sPodName=kube-system/coredns-6f4dfbffb4-qn2jd subsys=endpoint
2020-10-07T12:22:54+03:00 {} level=info msg="Reloaded endpoint BPF program" containerID=f3dae2d079 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=1736 identity=106 ipv4=10.1.59.55 ipv6= k8sPodName=kube-system/coredns-6f4dfbffb4-wbtwx subsys=endpoint
2020-10-07T12:22:54+03:00 {} level=info msg="Initial etcd session established" config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" subsys=kvstore
2020-10-07T12:22:54+03:00 {} level=info msg="Got lock lease ID 1e5974d137583c3b" subsys=kvstore
2020-10-07T12:22:54+03:00 {} level=info msg="Got lease ID 1e5974d137583c39" subsys=kvstore
2020-10-07T12:22:53+03:00 {} level=info msg="regenerating all endpoints" reason="datapath ipcache" subsys=endpoint-manager
2020-10-07T12:22:53+03:00 {} level=info msg="Setting sysctl net.ipv4.conf.eth0.rp_filter=2" subsys=datapath-loader
2020-10-07T12:22:53+03:00 {} level=info msg="Setting sysctl kernel.unprivileged_bpf_disabled=1" subsys=datapath-loader
2020-10-07T12:22:53+03:00 {} level=info msg="Setting sysctl net.ipv4.conf.all.rp_filter=0" subsys=datapath-loader
2020-10-07T12:22:53+03:00 {} level=info msg="Setting sysctl net.core.bpf_jit_enable=1" subsys=datapath-loader
2020-10-07T12:22:53+03:00 {} level=info msg="Setting up base BPF datapath (BPF v2 instruction set, ktime clock source)" subsys=datapath-loader
2020-10-07T12:22:53+03:00 {} level=info msg="Reloaded endpoint BPF program" containerID= datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=2729 identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2020-10-07T12:22:53+03:00 {} level=info msg="Reloaded endpoint BPF program" containerID= datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=809 identity=1 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2020-10-07T12:22:53+03:00 {} level=info msg="Reloaded endpoint BPF program" containerID=df2377d1f2 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=102 identity=106 ipv4=10.1.47.33 ipv6= k8sPodName=kube-system/coredns-6f4dfbffb4-qn2jd subsys=endpoint
2020-10-07T12:22:53+03:00 {} level=info msg="Reloaded endpoint BPF program" containerID=f3dae2d079 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=1736 identity=106 ipv4=10.1.59.55 ipv6= k8sPodName=kube-system/coredns-6f4dfbffb4-wbtwx subsys=endpoint
2020-10-07T12:22:52+03:00 {} level=info msg="regenerating all endpoints" reason="datapath ipcache" subsys=endpoint-manager
2020-10-07T12:22:51+03:00 {} level=info msg="Setting sysctl net.ipv4.conf.eth0.rp_filter=2" subsys=datapath-loader
2020-10-07T12:22:51+03:00 {} level=info msg="Setting sysctl kernel.unprivileged_bpf_disabled=1" subsys=datapath-loader
2020-10-07T12:22:51+03:00 {} level=info msg="Setting sysctl net.ipv4.conf.all.rp_filter=0" subsys=datapath-loader
2020-10-07T12:22:51+03:00 {} level=info msg="Setting sysctl net.core.bpf_jit_enable=1" subsys=datapath-loader
2020-10-07T12:22:51+03:00 {} level=info msg="Setting up base BPF datapath (BPF v2 instruction set, ktime clock source)" subsys=datapath-loader
2020-10-07T12:22:43+03:00 {} level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
2020-10-07T12:22:42+03:00 {} level=info msg="Connecting to etcd server..." config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" subsys=kvstore
2020-10-07T12:22:42+03:00 {} level=warning msg="Error observed on etcd connection, reconnecting etcd" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 error="not able to connect to any etcd endpoints" kvstoreErr="not able to connect to any etcd endpoints" kvstoreStatus="not able to connect to any etcd endpoints" subsys=clustermesh
2020-10-07T12:22:42+03:00 {} level=info msg="Established connection to remote etcd" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 kvstoreErr="not able to connect to any etcd endpoints" kvstoreStatus="not able to connect to any etcd endpoints" subsys=clustermesh
2020-10-07T12:22:42+03:00 {} level=info msg="Connection to remote cluster established" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 kvstoreErr="<nil>" kvstoreStatus= subsys=clustermesh
2020-10-07T12:22:42+03:00 {} level=info msg="Successfully verified version of etcd endpoint" config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" etcdEndpoint="https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271" subsys=kvstore version=3.3.12
2020-10-07T12:22:40+03:00 {} {"level":"warn","ts":"2020-10-07T09:22:40.749Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthrough:///https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
2020-10-07T12:22:31+03:00 {} level=info msg="Initial etcd session established" config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" subsys=kvstore
2020-10-07T12:22:31+03:00 {} level=info msg="Got lock lease ID 513f74d136b72b7e" subsys=kvstore
2020-10-07T12:22:31+03:00 {} level=info msg="Got lease ID 513f74d136b72b7c" subsys=kvstore
2020-10-07T12:22:21+03:00 {} level=info msg="Reloaded endpoint BPF program" containerID= datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=2729 identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2020-10-07T12:22:21+03:00 {} level=info msg="Reloaded endpoint BPF program" containerID= datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=809 identity=1 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2020-10-07T12:22:21+03:00 {} level=info msg="Reloaded endpoint BPF program" containerID=df2377d1f2 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=102 identity=106 ipv4=10.1.47.33 ipv6= k8sPodName=kube-system/coredns-6f4dfbffb4-qn2jd subsys=endpoint
2020-10-07T12:22:21+03:00 {} level=info msg="Reloaded endpoint BPF program" containerID=f3dae2d079 datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=1736 identity=106 ipv4=10.1.59.55 ipv6= k8sPodName=kube-system/coredns-6f4dfbffb4-wbtwx subsys=endpoint
2020-10-07T12:22:21+03:00 {} level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
2020-10-07T12:22:20+03:00 {} level=info msg="regenerating all endpoints" reason="datapath ipcache" subsys=endpoint-manager
2020-10-07T12:22:20+03:00 {} level=info msg="Connecting to etcd server..." config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" subsys=kvstore
2020-10-07T12:22:20+03:00 {} level=warning msg="Error observed on etcd connection, reconnecting etcd" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 error="not able to connect to any etcd endpoints" kvstoreErr="not able to connect to any etcd endpoints" kvstoreStatus="not able to connect to any etcd endpoints" subsys=clustermesh
2020-10-07T12:22:20+03:00 {} level=info msg="Established connection to remote etcd" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 kvstoreErr="not able to connect to any etcd endpoints" kvstoreStatus="not able to connect to any etcd endpoints" subsys=clustermesh
2020-10-07T12:22:20+03:00 {} level=info msg="Connection to remote cluster established" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 kvstoreErr="<nil>" kvstoreStatus= subsys=clustermesh
2020-10-07T12:22:20+03:00 {} level=info msg="Successfully verified version of etcd endpoint" config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" etcdEndpoint="https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271" subsys=kvstore version=3.3.12
2020-10-07T12:22:20+03:00 {} level=info msg="Setting sysctl net.ipv4.conf.eth0.rp_filter=2" subsys=datapath-loader
2020-10-07T12:22:20+03:00 {} level=info msg="Setting sysctl kernel.unprivileged_bpf_disabled=1" subsys=datapath-loader
2020-10-07T12:22:20+03:00 {} level=info msg="Setting sysctl net.ipv4.conf.all.rp_filter=0" subsys=datapath-loader
2020-10-07T12:22:20+03:00 {} level=info msg="Setting sysctl net.core.bpf_jit_enable=1" subsys=datapath-loader
2020-10-07T12:22:20+03:00 {} level=info msg="Setting up base BPF datapath (BPF v2 instruction set, ktime clock source)" subsys=datapath-loader
2020-10-07T12:22:18+03:00 {} {"level":"warn","ts":"2020-10-07T09:22:18.501Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthrough:///https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
2020-10-07T12:22:09+03:00 {} level=info msg="Initial etcd session established" config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" subsys=kvstore
2020-10-07T12:22:09+03:00 {} level=info msg="Got lock lease ID 513f74d136b72b70" subsys=kvstore
2020-10-07T12:22:09+03:00 {} level=info msg="Got lease ID 513f74d136b72b6e" subsys=kvstore
2020-10-07T12:21:58+03:00 {} level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
2020-10-07T12:21:58+03:00 {} level=info msg="Connecting to etcd server..." config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" subsys=kvstore
2020-10-07T12:21:58+03:00 {} level=warning msg="Error observed on etcd connection, reconnecting etcd" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 error="not able to connect to any etcd endpoints" kvstoreErr="not able to connect to any etcd endpoints" kvstoreStatus="not able to connect to any etcd endpoints" subsys=clustermesh
2020-10-07T12:21:58+03:00 {} level=info msg="Established connection to remote etcd" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 kvstoreErr="not able to connect to any etcd endpoints" kvstoreStatus="not able to connect to any etcd endpoints" subsys=clustermesh
2020-10-07T12:21:58+03:00 {} level=info msg="Connection to remote cluster established" clusterName=prod-k8s-ap-northeast-1 config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 kvstoreErr="<nil>" kvstoreStatus= subsys=clustermesh
2020-10-07T12:21:58+03:00 {} level=info msg="Successfully verified version of etcd endpoint" config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" etcdEndpoint="https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271" subsys=kvstore version=3.3.12
2020-10-07T12:21:56+03:00 {} {"level":"warn","ts":"2020-10-07T09:21:56.209Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthrough:///https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
2020-10-07T12:21:47+03:00 {} level=info msg="Initial etcd session established" config=/var/lib/cilium/clustermesh/prod-k8s-ap-northeast-1 endpoints="[https://prod-k8s-ap-northeast-1.mesh.cilium.io:32271]" subsys=kvstore
2020-10-07T12:21:47+03:00 {} level=info msg="Got lock lease ID 1e5974d137583c22" subsys=kvstore
2020-10-07T12:21:47+03:00 {} level=info msg="Got lease ID 1e5974d137583c20" subsys=kvstore
```

### LINKED ISSUE #22988: clustermesh: agent leaks memory when remote cluster connection is restarted
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We started to see memory increase when remote cluster connection was restarted. And each time the remote connection was restarted the more memory it leaked. The problematic cluster had around 20k identities which was fantastic because otherwise we would not see the leak so early.   

The memory should stay the same before and after the restart. (also the memory was not released when we totally removed the cluster from clustermesh). 

I can easily reproduce this if I manually update a selected remote cluster config (to trigger fsnotify) each time I do this, some memory is leaked.

### Cilium Version

```
Client: 1.12.4 ac046c95eb 2022-11-16T14:51:11+01:00 go version go1.18.8 linux/amd64
Daemon: 1.12.4 ac046c95eb 2022-11-16T14:51:11+01:00 go version go1.18.8 linux/amd64
```

### Kernel Version

`Linux tt-os2-n1.ko.iszn.cz 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Kubernetes Version

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8", GitCommit:"7061dbbf75f9f82e8ab21f9be7e8ffcaae8e0d44", GitTreeState:"clean", BuildDate:"2022-03-16T14:10:06Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8", GitCommit:"7061dbbf75f9f82e8ab21f9be7e8ffcaae8e0d44", GitTreeState:"clean", BuildDate:"2022-03-16T14:04:34Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

but it's not related to k8s as it happens also on nodes outside of k8s 

### Sysdump

_No response_

### Relevant log output

```shell
level=info msg="etcd configuration has changed, re-creating connection" clusterName=uacl-test-labrador-test config=/www/sasanka/secrets/cilium/configs/uacl-test-labrador-test kvstoreErr="<nil>" kvstoreStatus="etcd: 1/1 connected, lease-ID=3b2a847f52738930, lock lease-ID=3b2a847f52738935, has-quorum=true: https://uacl-test-labrador-test.ko.iszn.cz:31007 - 3.5.4" subsys=clustermesh
level=info msg="Creating etcd client" ConfigPath=/www/sasanka/secrets/cilium/configs/uacl-test-labrador-test KeepAliveHeartbeat=15s KeepAliveTimeout=25s RateLimit=20 subsys=kvstore
level=info msg="Connecting to etcd server..." config=/www/sasanka/secrets/cilium/configs/uacl-test-labrador-test endpoints="[https://uacl-test-labrador-test.ko.iszn.cz:31007]" subsys=kvstore
level=info msg="Got lease ID 10df847f53140be2 and the session TTL is 15m0s" subsys=kvstore
level=info msg="Got lock lease ID 10df847f53140be7" subsys=kvstore
level=info msg="Initial etcd session established" config=/www/sasanka/secrets/cilium/configs/uacl-test-labrador-test endpoints="[https://uacl-test-labrador-test.ko.iszn.cz:31007]" subsys=kvstore
level=info msg="Successfully verified version of etcd endpoint" config=/www/sasanka/secrets/cilium/configs/uacl-test-labrador-test endpoints="[https://uacl-test-labrador-test.ko.iszn.cz:31007]" etcdEndpoint="https://uacl-test-labrador-test.ko.iszn.cz:31007" subsys=kvstore version=3.5.4
level=info msg="Connection to remote cluster established" clusterName=uacl-test-labrador-test config=/www/sasanka/secrets/cilium/configs/uacl-test-labrador-test kvstoreErr="<nil>" kvstoreStatus= subsys=clustermesh
level=info msg="Established connection to remote etcd" clusterName=uacl-test-labrador-test config=/www/sasanka/secrets/cilium/configs/uacl-test-labrador-test kvstoreErr="<nil>" kvstoreStatus="etcd: 1/1 connected, lease-ID=10df847f53140be2, lock lease-ID=10df847f53140be7, has-quorum=true: https://uacl-test-labrador-test.ko.iszn.cz:31007 - 3.5.4" subsys=clustermesh
level=info msg="regenerating all endpoints" reason="one or more identities created or deleted" subsys=endpoint-manager
```

### Anything else?

related slack thread https://cilium.slack.com/archives/C1MATJ5U5/p1672811968057149

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by squeed**
Upon reconnect, we failed to remove the old remoteCache (we were looking at the wrong Allocator on cleanup), meaning that every time we reconnected, all old remoteCaches were kept around.

This was, at best, a memory leak, and at worst meant that we continued to read stale data even after reconnecting, depending on the ordering of a map iteration.

Many thanks to @oblazek, who found the root cause.

Fixes: #22988
Fixes: #13446

Signed-off-by: Casey Callendrello <cdc@isovalent.com>

```release-note
Fixes a memory leak and (possible) source of stale data for Clustermesh whenever the connection to the remote cluster is disrupted or restarted.
```

### CODE REVIEW

**Comment by squeed** [comment]
Something seems wrong; [this failure](https://github.com/cilium/cilium/actions/runs/4074324844/jobs/7019346762) doesn't seem like it should be happening. And this test has been pretty stable.

**Review by christarazi — COMMENTED** [review]
Thanks for submitting the fix and thanks to @oblazek for finding it!

**Review by christarazi — APPROVED** [review]
Thanks for submitting the fix and thanks to @oblazek for finding it!

File: pkg/identity/cache/allocator.go [hunk 1]
```diff
@@ -440,18 +440,24 @@ func (m *CachingIdentityAllocator) ReleaseSlice(ctx context.Context, owner Ident
 
 // WatchRemoteIdentities starts watching for identities in another kvstore and
 // syncs all identities to the local identity cache.
-func (m *CachingIdentityAllocator) WatchRemoteIdentities(backend kvstore.BackendOperations) (*allocator.RemoteCache, error) {
+func (m *CachingIdentityAllocator) WatchRemoteIdentities(name string, backend kvstore.BackendOperations) (*allocator.RemoteCache, error) {
```
Comment (aditighag) [inline pkg/identity/cache/allocator.go]: Nit: Please update the function description.

**Review by aditighag — APPROVED** [review]
Good find! The refactoring/fixing typos related changes could've been separated in a separate commit. LGTM. 
Some of the functions need updated description.

**Review by tklauser — APPROVED** [review]

File: pkg/clustermesh/remote_cluster.go [hunk 2]
```diff
@@ -269,6 +269,7 @@ func (rc *remoteCluster) restartRemoteConnection(allocator RemoteIdentityWatcher
 				rc.releaseOldConnection()
 				rc.mesh.metricTotalNodes.WithLabelValues(rc.mesh.conf.Name, rc.mesh.conf.NodeName, rc.name).Set(float64(rc.remoteNodes.NumEntries()))
 				rc.mesh.metricReadinessStatus.WithLabelValues(rc.mesh.conf.Name, rc.mesh.conf.NodeName, rc.name).Set(metrics.BoolToFloat64(rc.isReadyLocked()))
+				allocator.RemoveRemoteIdentities(rc.name)
```
Comment (oblazek) [inline pkg/clustermesh/remote_cluster.go:272]: can we add this also somewhere [here](https://github.com/cilium/cilium/blob/master/pkg/clustermesh/remote_cluster.go#L165)? otherwise it does not really fix the memleak issue.. the controller itself is not stopped, so this cleanup is never run in my case...

Comment (squeed) [reply pkg/clustermesh/remote_cluster.go:272]: @oblazek There should be only one controller per remote cluster, so as soon as a new connection is made, it will replace the old cache in the allocator. I decided to preserve the old one, so that connections aren't disrupted while etcd blips. Otherwise all identities are deleted and re-created, meaning connectivity is lost.

Comment (oblazek) [reply pkg/clustermesh/remote_cluster.go:272]: ah yes, got it

**Comment by squeed** [comment]
@oblazek found another memory leak :-). Fix coming shortly.

**Comment by squeed** [comment]
Okay, added a second commit to clean up another spurious cache of etcd; PTAL.

FYI, the ipv6 tests are green now. I don't know why they were failing reliably for this PR, but they're not now. This really doesn't touch any of the affected code, so this is one big mystery. Can I blame GitHub Action slowness?

**Review by tklauser — APPROVED** [review]

**Review by tklauser — APPROVED** [review]
2nd commit LGTM as well, thanks.

**Comment by squeed** [comment]
FYI ci-multicluster passed. That's a good sign.

**Review by aditighag — APPROVED** [review]
Approving for my code review group. (I'm not sure I fully understand the new changes in `pkg/allocator/allocator.go` in the 2nd commit. Hopefully other code review areas can take a closer look. )

**Review by christarazi — APPROVED** [review]

**Comment by squeed** [comment]
Just FYI, I want to do a bit more manual testing before this merges; existing CI doesn’t cover this case at all.

**Comment by squeed** [comment]
OK, I've banged on this pretty well, couldn't get the bug to appear. This seems good to go.

**Comment by squeed** [comment]
Found the issue; we were starting the connectivity test too soon after restarting the agents. I have a test run in https://github.com/cilium/cilium/pull/23716, which I'll include here when finished. I believe this change is safe.

**Review by YutaroHayakawa — APPROVED** [review]
Sorry for the late resposse. Changes looks good to me (including the test changes) thanks!

**Comment by squeed** [comment]
Passing run for proposed CI changes here: https://github.com/cilium/cilium/actions/runs/4164795509/jobs/7206931563

**Comment by squeed** [comment]
CI is all green, including multicluster (the flake fixed by this CI run didn't hit us this time)

File: .github/workflows/conformance-multicluster.yaml [hunk 3]
```diff
@@ -322,6 +322,8 @@ jobs:
 
       - name: Wait for cluster mesh status to be ready
         run: |
+          cilium status --wait --context ${{ steps.contexts.outputs.context1 }}
+          cilium status --wait --context ${{ steps.contexts.outputs.context2 }}
```
Comment (nbusseneau) [inline .github/workflows/conformance-multicluster.yaml:326]: While this is fine for now, I suppose a more proper fix would be to have the `clustermesh status --wait` command automatically also imply a `status --wait` directly in CLI code. cc @tklauser for thoughts.

**Review by nbusseneau — APPROVED** [review]

File: .github/workflows/conformance-multicluster.yaml (hunk 3 above)
Comment (squeed) [reply .github/workflows/conformance-multicluster.yaml:326]: Well, ultimately, they do different things. Ideally there would be a `--wait` in `clustermesh join`
