### PR TITLE
gateway-api: Retrieve LB service from same namespace

### LINKED ISSUE #31270: Gateway API doesn't seem to like reusing gateway name in multiple namespaces in dedicated loadbalancer mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Testing usins multiple gateway definitions I found that if I reused the gateway name the gateway status information concerning the external ip address is inconsistent with the loadbalance service when using dedicated loadbalancer mode.

### Cilium Version

1.15.1

Due to another bug with gatway API on Kind (#31269), I can't test 1.16.0-pre.0 

### Kernel Version

Linux carbon 6.7.4-200.fc39.x86_64 cilium/cilium#1 SMP PREEMPT_DYNAMIC Mon Feb  5 22:21:14 UTC 2024 x86_64 GNU/Linux

### Kubernetes Version

Server Version: v1.29.2

### Regression

I've only tested with 1.15.1 so far.

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

Mismatch in expected address between gateway and loadbalancer service in namespace other

```
kubectl get gateway -A
NAMESPACE   NAME         CLASS    ADDRESS         PROGRAMMED   AGE
default     my-gateway   cilium   172.18.100.12   True         12m
other       my-gateway   cilium   172.18.100.12   True         5m27s
```
```
kubectl -n other get services 
NAME                        TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)        AGE
cilium-gateway-my-gateway   LoadBalancer   10.96.235.190   172.18.100.13   80:31459/TCP   6m10s
details                     ClusterIP      10.96.172.58    <none>          9080/TCP       13m
productpage                 ClusterIP      10.96.112.101   <none>          9080/TCP       13m
ratings                     ClusterIP      10.96.40.236    <none>          9080/TCP       13m
reviews                     ClusterIP      10.96.21.58     <none>          9080/TCP       13m
```
But if I change the gateway name to longer be the same as an existing gateway name...then I get what I expect.

```
kubectl get gateway -A
NAMESPACE   NAME            CLASS    ADDRESS         PROGRAMMED   AGE
default     my-gateway      cilium   172.18.100.12   True         16m
other       other-gateway   cilium   172.18.100.13   True         8s

kubectl -n other get services 
NAME                           TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)        AGE
cilium-gateway-other-gateway   LoadBalancer   10.96.160.207   172.18.100.13   80:30393/TCP   34s
details                        ClusterIP      10.96.172.58    <none>          9080/TCP       17m
productpage                    ClusterIP      10.96.112.101   <none>          9080/TCP       17m
ratings                        ClusterIP      10.96.40.236    <none>          9080/TCP       17m
reviews                        ClusterIP      10.96.21.58     <none>          9080/TCP       17m

```
### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sayboras**
### Description 

This commit is to add the same namespace while listing generated LB
service, the main reason is to avoid wrong status update for gateways
having the same name, but belonged to different namespace.

Testing was done locally as per below:

Before the fix:
```
$ kg gateway -A
NAMESPACE   NAME         CLASS    ADDRESS          PROGRAMMED   AGE
another     my-gateway   cilium   10.110.222.237   True         4s
default     my-gateway   cilium   10.110.222.237   True         56s
```

After the fix:

```
$ kg gateway -A
NAMESPACE   NAME         CLASS    ADDRESS          PROGRAMMED   AGE
another     my-gateway   cilium   10.102.170.180   True         14m
default     my-gateway   cilium   10.110.222.237   True         14m

$ kg services -A
NAMESPACE     NAME                           TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                      AGE
another       cilium-gateway-my-gateway      LoadBalancer   10.102.170.180   10.102.170.180   80:31424/TCP                 15m
default       cilium-gateway-my-gateway      LoadBalancer   10.110.222.237   10.110.222.237   80:31889/TCP                 15m
...
```

Fixes: https://github.com/cilium/cilium/issues/31270

### CODE REVIEW

File: operator/pkg/model/translation/gateway-api/translator.go [hunk 1]
```diff
@@ -105,9 +106,12 @@ func getService(resource *model.FullyQualifiedResource, allPorts []uint32, label
 
 	return &corev1.Service{
 		ObjectMeta: metav1.ObjectMeta{
-			Name:        shorten(ciliumGatewayPrefix + resource.Name),
-			Namespace:   resource.Namespace,
-			Labels:      mergeMap(map[string]string{owningGatewayLabel: resource.Name}, labels),
+			Name:      shorten(ciliumGatewayPrefix + resource.Name),
+			Namespace: resource.Namespace,
+			Labels: mergeMap(map[string]string{
+				owningGatewayLabel:          resource.Name,
```
Comment (chaunceyjiang) [inline operator/pkg/model/translation/gateway-api/translator.go]: I believe there is a bug here, we can't directly reference the name of the resource.

I have provided a reproduction step. https://github.com/cilium/cilium/issues/31285

Comment (sayboras) [reply operator/pkg/model/translation/gateway-api/translator.go]: Thanks for your message, it seems like such issue can be tackle separately (i.e. using existing hash function to shorten the name).

> When creating a gateway-api with a name exceeding 64 characters, this problem will be triggered.

**Review by chaunceyjiang — APPROVED** [review]
LGTM

File: operator/pkg/gateway-api/gateway_reconcile.go [hunk 2]
```diff
@@ -318,7 +318,8 @@ func isAttachable(_ context.Context, gw *gatewayv1.Gateway, route metav1.Object,
 func (r *gatewayReconciler) setAddressStatus(ctx context.Context, gw *gatewayv1.Gateway) error {
 	svcList := &corev1.ServiceList{}
 	if err := r.Client.List(ctx, svcList, client.MatchingLabels{
```
Comment (mhofstetter) [inline operator/pkg/gateway-api/gateway_reconcile.go:320]: wouldn't it be sufficient to just use an additional `ListOption` (`client.InNamespace(gw.GetNamespace()`) ? (the LB `Service` is always in the same namespace as the `Gateway` anyway)

Hence i don't think that it's necessary to introduce an additional label.

**Review by mhofstetter — CHANGES_REQUESTED** [review]
I think we can implement this by simply add an additional ListOption to filter for the namespace.

File: operator/pkg/gateway-api/gateway_reconcile.go (hunk 2 above)
Comment (sayboras) [reply operator/pkg/gateway-api/gateway_reconcile.go:320]: good call out, I was overthinking about cross namespace like one of Ingress cases.

File: operator/pkg/gateway-api/gateway_reconcile.go [hunk 3]
```diff
@@ -319,7 +319,7 @@ func (r *gatewayReconciler) setAddressStatus(ctx context.Context, gw *gatewayv1.
...
 		owningGatewayLabel: model.Shorten(gw.GetName()),
-	}); err != nil {
+	}, client.InNamespace(gw.GetNamespace())); err != nil {
```
Comment (mhofstetter) [inline operator/pkg/gateway-api/gateway_reconcile.go:322]: maybe covering this case in an additional unit-test?

**Review by mhofstetter — APPROVED** [review]
LGTM! Thanks for changing to the InNamespace ListOption.

Might be worth to add an additional unit-test to cover this case.

File: operator/pkg/gateway-api/gateway_reconcile.go (hunk 3 above)
Comment (sayboras) [reply operator/pkg/gateway-api/gateway_reconcile.go:322]: good point and done
