### PR TITLE
Handle `.status.conditions` on `Service`s using in accordance with KEP-1623

### LINKED ISSUE #24945: Flux cannot reconcile services anymore due to duplicate lb-ipam-request-satisfied status
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Following #24502 on https://github.com/cilium/cilium/issues/24502#issuecomment-1511630042, when deleting the `CiliumLoadBalancerIPPool` to get around the bug, flux cannot reconcile anymore services, even after applying back the pool.

```
✗ Kustomization reconciliation failed: Service/network-cluster/nginx-ingress-controller dry-run failed, error: failed to create manager for existing fields: failed to convert new object (network-cluster/nginx-ingress-controller; /v1, Kind=Service) to smd typed: .status.conditions: duplicate entries for key [type="io.cilium/lb-ipam-request-satisfied"]
```

All services have to be deleted along the pool before being able to reconcile.

 
Actually I think I saw it once even without deleting the pool

### Cilium Version

```
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
Client: 1.13.1 a6be57eb 2023-03-15T19:39:01+01:00 go version go1.19.6 linux/amd64
Daemon: 1.13.1 a6be57eb 2023-03-15T19:39:01+01:00 go version go1.19.6 linux/amd64
```

### Kernel Version

```
Linux srv1 6.2.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 30 Mar 2023 14:51:14 +0000 x86_64 GNU/Linux
```

### Kubernetes Version

```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"archive", BuildDate:"2023-03-19T19:47:22Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.4", GitCommit:"f89670c3aa4059d6999cb42e23ccb4f0b9a03979", GitTreeState:"clean", BuildDate:"2023-04-12T12:05:35Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
```

### Sysdump

[cilium-sysdump-20230418-235454.zip](https://github.com/cilium/cilium/files/11266734/cilium-sysdump-20230418-235454.zip)

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by addreas**
Currently the lbipam controller creates multiple `.status.conditions` per `type` of condition on the `Service`s it updates. This conflicts with what's expected, as the `ServiceStatus.Conditions` is [defined](https://github.com/kubernetes/api/blob/v0.26.0/core/v1/types.go#LL4416C1-L4419C21) as a `// +listType=map` and `// +listMapKey=type`.

While the Kubernetes API server seems to not notice, tooling that utilizes strategic merge patches on the in-cluster resources will encounter errors such as `error: failed to create manager for existing fields: failed to convert new object (network-cluster/nginx-ingress-controller; /v1, Kind=Service) to smd typed: .status.conditions: duplicate entries for key [type="io.cilium/lb-ipam-request-satisfied"]`.

Not quite sure if copy-pasting the required code for `github.com/cilium/cilium/pkg/k8s/slim/k8s/apimachinery/pkg/api/meta`  from the apimachinery master branch and modifying the header is the correct way of doing things. Is that supposed to follow some specific version or be tracked somehow?

Haven't dug into building an image locally for testing, but at least `go test ./operator/pkg/lbipam` passes.

Fixes: #24945

### CODE REVIEW

**Review by ghost — APPROVED** [review]
docs structure looks good

File: operator/pkg/lbipam/lbipam.go [hunk 1]
```diff
@@ -28,19 +29,20 @@ import (
...
+	ciliumSvcRequestSatisfiedCondition = "cilium.io/IPAMRequestSatisfied"
 
-	ciliumPoolIPsTotalCondition     = "io.cilium/ips-total"
-	ciliumPoolIPsAvailableCondition = "io.cilium/ips-available"
-	ciliumPoolIPsUsedCondition      = "io.cilium/ips-used"
-	ciliumPoolConflict              = "io.cilium/conflict"
+	ciliumPoolIPsTotalCondition     = "cilium.io/IPsTotal"
+	ciliumPoolIPsAvailableCondition = "cilium.io/IPsAvailable"
+	ciliumPoolIPsUsedCondition      = "cilium.io/IPsUsed"
+	ciliumPoolConflict              = "cilium.io/PoolConflict"
```
Comment (dylandreimerink) [inline operator/pkg/lbipam/lbipam.go:45]: Just our of curiosity, is there a k8s standard or guide somewhere which describes naming convention for fields such as these. I can for the live of me not remember why I chose the java package (reverse dns) style here. But doing the kebab-case for the rest seems quite normal https://kubernetes.io/docs/reference/labels-annotations-taints/

**Review by dylandreimerink — APPROVED** [review]

File: operator/pkg/lbipam/lbipam.go (hunk 1 above)
Comment (addreas) [reply operator/pkg/lbipam/lbipam.go:45]: You mentioned it in [the issue](https://github.com/cilium/cilium/issues/24945#issuecomment-1560626174), actually. It's what the [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/1623-standardize-conditions/README.md?plain=1#L81) has as an example, and condition types on regular resources like pods and deployments are camel cased as well.

This could be moved to a different PR if you want, since it's not as important as fixing the bug that breaks strategic merge patching.

Comment (dylandreimerink) [reply operator/pkg/lbipam/lbipam.go:45]: Ah! I had missed that part. Thank you for pointing that out and fixing this issue :pray: . I think these can stay, given its for conformance to the KEP and these fields are mostly for internal use anyway.

**Comment by joestringer** [comment]
Thanks for the PR! CI was passing before. Next step is getting @cilium/sig-k8s review, then once all reviewers are addressed and green we can do a rebase + re-run CI to confirm there's no breakage on tip of main branch. It'll also be worth evaluating whether we should backport this fix to v1.14 assuming it satisfies the [backport criteria](https://docs.cilium.io/en/stable/contributing/release/backports/#backport-criteria).

**Review by christarazi — CHANGES_REQUESTED** [review]
Thanks for the PR!

> Not quite sure if copy-pasting the required code for github.com/cilium/cilium/pkg/k8s/slim/k8s/apimachinery/pkg/api/meta from the apimachinery master branch and modifying the header is the correct way of doing things. Is that supposed to follow some specific version or be tracked somehow?

Please follow https://github.com/cilium/cilium/blob/main/pkg/k8s/slim/README.md and update it if the files you need in this PR aren't inside this script.

**Comment by addreas** [comment]
Updated the slim README  with another `curl` line for the meta conditions utils. Changed the package path to line up more closely with the others, though I'm not sure I can actually see the pattern there.

**Review by christarazi — APPROVED** [review]

**Comment by christarazi** [comment]
LGTM. CCing @aanm to double check the process for slim-related changes.

**Review by aanm — APPROVED** [review]
slim-related changes LGTM

**Review by joamaki — APPROVED** [review]
