### PR TITLE
bpf: Fix program size issue with host firewall in IPv4-only mode

### LINKED ISSUE #14231: Program size regression with host firewall in IPv4-only mode
Running the host firewall on a kube-proxy-free cluster with IPv4 only results in the following error:
```
level=warning msg="Prog section 'to-netdev' rejected: Argument list too long (7)!" subsys=datapath-loader
level=warning msg=" - Type:         3" subsys=datapath-loader
level=warning msg=" - Attach Type:  0" subsys=datapath-loader
level=warning msg=" - Instructions: 4179 (83 over limit)" subsys=datapath-loader
level=warning msg=" - License:      GPL" subsys=datapath-loader
```

This is easy to reproduce e.g. on GKE with the following command:
```
helm install cilium ./cilium   --namespace cilium   --set nodeinit.enabled=true   --set nodeinit.reconfigureKubelet=true   --set nodeinit.removeCbrBridge=true   --set cni.binPath=/home/kubernetes/bin   --set tunnel=disabled   --set endpointRoutes.enabled=false   --set ipam.mode=kubernetes   --set nativeRoutingCIDR=$NATIVE_CIDR   --set nodeinit.restartPods=true   --set hostFirewall=true
```

The regression doesn't affect 1.9.0. It was probably introduced by some of the recent work on IPv4 fragment tracking.

The section failing to load, `to-netdev`, performs the following actions:
1. Host policy enforcement
2. Bandwidth rate limiter enforcement (disabled on GKE; not required to reproduce)
3. NAT & service handling

The complexity issue only happens when IPv6 is disabled (maybe also when IPv4 is disabled) because the third step above is compiled into a separate tail call only when both IPv4 and IPv6 are enabled:
https://github.com/cilium/cilium/blob/89c0f08cc13125deb2a4fe409d465b48301ba34c/bpf/lib/nodeport.h#L1629-L1649

I will send a pull request to fix it by compiling the NAT & service handling into a separate program when the host firewall is enabled.

### PR DESCRIPTION
**Pull request by pchaigno**
Running Cilium in IPv4-only mode with the host firewall and our kube-proxy replacement enabled causes program `to-netdev` from `bpf_host` to have an excessive size (>4096 instructions):

    level=warning msg="Prog section 'to-netdev' rejected: Argument list too long (7)!" subsys=datapath-loader
    level=warning msg=" - Type:         3" subsys=datapath-loader
    level=warning msg=" - Attach Type:  0" subsys=datapath-loader
    level=warning msg=" - Instructions: 4179 (83 over limit)" subsys=datapath-loader
    level=warning msg=" - License:      GPL" subsys=datapath-loader

The section in question consists in particular of the host firewall enforcement and the NAT+service handling via `nodeport_nat_fwd()`. That last function is only split into several programs via tail calls when both IPv4 and IPv6 are enabled.

To reduce the program size, this pull request also splits `nodeport_nat_fwd()` into several BPF programs via tail calls when the host firewall is enabled. We also need to check for `HOST_EP_ID` to only split if we're calling `nodeport_nat_fwd()` from `bpf_host`.

Fixes: https://github.com/cilium/cilium/issues/14231

### CODE REVIEW

**Comment by pchaigno** [comment]
test-me-please

File: bpf/bpf_host.c [hunk 1]
```diff
@@ -7,6 +7,8 @@
 #include <node_config.h>
 #include <ep_config.h>
 
+#define IS_BPF_HOST 1
```
Comment (kkourt) [inline bpf/bpf_host.c]: nit: maybe just use `#define IS_BPF_HOST` here since the check is `#if defined(IS_BPF_HOST)`

**Review by kkourt — APPROVED** [review]

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
retest-gke

**Comment by pchaigno** [comment]
retest-4.9

**Comment by pchaigno** [comment]
retest-runtime

**Comment by pchaigno** [comment]
retest-gke

**Comment by pchaigno** [comment]
retest-gke

**Comment by pchaigno** [comment]
retest-gke

File: bpf/bpf_host.c (hunk 1 above)
Comment (pchaigno) [reply bpf/bpf_host.c]: That change seemed so obvious I didn't retest the patch after it. Bad idea.

Turns out the `1` is needed here because of how we define `is_defined`. I'll send a fix.

Comment (pchaigno) [reply bpf/bpf_host.c]: Fix ready at https://github.com/cilium/cilium/pull/14255, with a test this time :slightly_smiling_face:

Comment (kkourt) [reply bpf/bpf_host.c]: Sorry about that!
It might make sense to replace `#if defined(IS_BPF_HOST)` with `#if IS_BPF_HOST == 1` at some point.
