### PR TITLE
hubble: Reduce "stale identities observed" debug messages even more

### LINKED ISSUE #15283: Debug message "stale identity observed" is frequently printed in logs
Cilium latest, during v1.10 dev cycle.

Seen in a failed PR, this message is frequently printed to the log:

```
2021-03-09T21:05:11.508381379Z level=debug msg="stale identity observed" identity=6 ipAddr=10.0.0.112 oldIdentity=1 subsys=hubble
```

It's just a debug message, but given how frequently it's being logged it seems like it's trying to draw attention to something being out-of-place compared to how the code was written. Just filing this to follow up and see if it's surprising to anyone. CC @cilium/hubble 

Example CI job:
https://jenkins.cilium.io/job/Cilium-PR-K8s-1.14-kernel-4.9/113/testReport/junit/Suite-k8s-1/14/K8sConformance_Portmap_Chaining_Check_connectivity_check_compliance_with_portmap_chaining/

[71a2aa28_K8sConformance_Portmap_Chaining_Check_connectivity-check_compliance_with_portmap_chaining.zip](https://github.com/cilium/cilium/files/6111782/71a2aa28_K8sConformance_Portmap_Chaining_Check_connectivity-check_compliance_with_portmap_chaining.zip)

### PR DESCRIPTION
**Pull request by gandro**
This PR does three things. See each commit for more details:

1. It improves the log message to aid in identifying the trace event which caused the log message to be emitted
2. Ignores a newly discovered discrepancy with IPSec (see inline comment)
3. Rate-limit the log message to one occurrence every 30 seconds

Fixes: https://github.com/cilium/cilium/issues/15283

### CODE REVIEW

File: pkg/hubble/parser/common/endpoint.go [hunk 1]
```diff
@@ -109,9 +109,10 @@ func (r *EndpointResolver) ResolveEndpoint(ip netip.Addr, datapathSecurityIdenti
 				// receiving side.
 			} else {
 				r.log.WithFields(logrus.Fields{
-					logfields.Identity:    datapathID.Uint32(),
-					logfields.OldIdentity: userspaceID.Uint32(),
-					logfields.IPAddr:      ip,
+					"datapath-identity":  datapathID.Uint32(),
+					"userspace-identity": userspaceID.Uint32(),
```
Comment (pchaigno) [inline pkg/hubble/parser/common/endpoint.go:127]: Nice!

**Review by pchaigno — APPROVED** [review]

**Review by rolinh — APPROVED** [review]

**Comment by gandro** [comment]
- [ci-ipsec-upgrade](https://github.com/cilium/cilium/actions/runs/7247586447/job/19741819005) failed with 1.1.1.1 connectivity
- [https://github.com/cilium/cilium/actions/runs/7247586388/job/19741818607] failed with https://github.com/cilium/cilium/issues/24728 I believe
- [ci-eks](https://github.com/cilium/cilium/actions/runs/7247585921) failed with `timeout reached waiting for NodePort 192.168.164.101:30134` which I think is a new flake. Will create an issue

Restarting all

**Comment by gandro** [comment]
ci-ipsec-upgrade is apparently broken on main - https://github.com/cilium/cilium/issues/29666#issuecomment-1857860784

Marking ready to merge
