### PR TITLE
bpf: fix missing ipv6 ct entry for SNATed pod traffic

### LINKED ISSUE #26886: IPv6 packets falsely dropped; conntrack issue
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1. Set up cilium on a dual stack cluster
2. Enable firewall (`CiliumClusterwideNetworkPolicy`) with rules allowing http or ping access to external sources, but no explicit ingress rule
3. Watch dropped packages with the command I provided

On outgoing traffic the identity of the pod is resolved correctly. But on incoming traffic/the response to the outgoing traffic, the packets are dropped because the target identity can not be figured out.
If `::/0` is a explicitly allowed in the firewall, the traffic comes through though.
This seems like a problem with the conntrack table where the lookup of the conntrack table would be done after the traffic is let through, which it isn't because of the firewall setup. Therefore the packets are dropped, despite a conntrack entry existing.
I tried to find a hint in the code, but I am not familiar enough with this code base to give any specific information on that.

### Cilium Version

Client: 1.14.0-snapshot.4 6c8db759 2023-06-16T12:17:20-07:00 go version go1.20.5 linux/amd64
Daemon: 1.14.0-snapshot.4 6c8db759 2023-06-16T12:17:20-07:00 go version go1.20.5 linux/amd64

### Kernel Version

5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.0", GitCommit:"1b4df30b3cdfeaba6024e81e559a6cd09a089d65", GitTreeState:"clean", BuildDate:"2023-04-11T17:04:24Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

_No response_

### Relevant log output

```shell
# root@server:/home/cilium# cilium monitor --type drop | grep 2a06:98c1:3120::3
Listening for events on x CPUs with x of shared memory
Press Ctrl-C to quit
level=info msg="Initializing dissection cache..." subsys=monitor
xx drop (Policy denied) flow 0xea08f9f8 to endpoint 0, ifindex 5, file bpf_host.c:379, , identity world->unknown: [2a06:98c1:3120::3]:80 -> [xx01:xx8:0:axx1::2exx:xxxx]:51824 tcp SYN, ACK
xx drop (Policy denied) flow 0xea08f9f8 to endpoint 0, ifindex 5, file bpf_host.c:379, , identity world->unknown: [2a06:98c1:3120::3]:80 -> [xx01:xx8:0:axx1::2exx:xxxx]:51824 tcp SYN, ACK
xx drop (Policy denied) flow 0xea08f9f8 to endpoint 0, ifindex 5, file bpf_host.c:379, , identity world->unknown: [2a06:98c1:3120::3]:80 -> [xx01:xx8:0:axx1::2exx:xxxx]:51824 tcp SYN, ACK
xx drop (Policy denied) flow 0xea08f9f8 to endpoint 0, ifindex 5, file bpf_host.c:379, , identity world->unknown: [2a06:98c1:3120::3]:80 -> [xx01:xx8:0:axx1::2exx:xxxx]:51824 tcp SYN, ACK
xx drop (Policy denied) flow 0xea08f9f8 to endpoint 0, ifindex 5, file bpf_host.c:379, , identity world->unknown: [2a06:98c1:3120::3]:80 -> [xx01:xx8:0:axx1::2exx:xxxx]:51824 tcp SYN, ACK
xx drop (Policy denied) flow 0xea08f9f8 to endpoint 0, ifindex 5, file bpf_host.c:379, , identity world->unknown: [2a06:98c1:3120::3]:80 -> [xx01:xx8:0:axx1::2exx:xxxx]:51824 tcp SYN, ACK

# root@server:/home/cilium# cilium monitor --from 408 
Listening for events on x CPUs with x of shared memory
Press Ctrl-C to quit
level=info msg="Initializing dissection cache..." subsys=monitor
-> stack flow 0xb26c28d7 , identity 3625->world state new ifindex 0 orig-ip 0.0.0.0: [fdxx:ffxx:2xx1:xx::exxe]:59284 -> [2a06:98c1:3120::3]:80 tcp SYN
-> stack flow 0x31790a5b , identity 3625->world state established ifindex 0 orig-ip 0.0.0.0: [fdxx:ffxx:2xx1:xx::exxe]:59284 -> [2a06:98c1:3120::3]:80 tcp SYN
-> stack flow 0x571bc5f7 , identity 3625->world state established ifindex 0 orig-ip 0.0.0.0: [fdxx:ffxx:2xx1:xx::exxe]:59284 -> [2a06:98c1:3120::3]:80 tcp SYN
-> stack flow 0x5a1e7b5f , identity 3625->world state established ifindex 0 orig-ip 0.0.0.0: [fdxx:ffxx:2xx1:xx::exxe]:59284 -> [2a06:98c1:3120::3]:80 tcp SYN
```

### Anything else?

`bpf_host.c:379` from the logs: https://github.com/cilium/cilium/blob/v1.14.0-snapshot.4/bpf/bpf_host.c#L378 I think

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by oblazek**
When combining HostFW with kube-proxy based masquerading
host traffic will have HOST_ID for both - packet mark based
src_id and ip cache based src_id.
While SNATed pod traffic will only have HOST_ID from the
ipcache (as it doesn't pass through the iptables rules that
set the mark).
Therefore for SNATed traffic we get HOST_ID only from
ipcache and not from packet mark it means we are handling
SNATed traffic from pod that needs to have a conntrack entry
so that return traffic doesn't go through host firewall and
is skipped.

This commit fixes the issue and adds a missing ct entry for
SNATed traffic.

cc @julianwiedmann 

Fixes: https://github.com/cilium/cilium/issues/26886

related discussion: https://cilium.slack.com/archives/CDKG8NNHK/p1698155364279479

```release-note
bpf: Fix drop of IPv6 reply traffic when 1) pod-originating connection is SNATed by iptables, and 2) Host Firewall is enabled.
```

### CODE REVIEW

**Comment by julianwiedmann** [comment]
Hi @oblazek , ty for looking into this! Will have a closer look ASAP.

But just to set some context for review, as the description doesn't capture my current understanding.
With `ENABLE_HOST_FIREWALL` set, we need to handle two cases in the egress path:
- actual host traffic. Here we want to apply egress policy.
- SNATed pod traffic (when not using BPF-masquerading). Here we *don't* apply egress policy. But we still create a CT entry, so that replies can naturally bypass ingress policy.

We differentiate between the two cases by comparing the mark-derived identity with the ipcache-derived identity. Host traffic will have `HOST_ID` for both, while SNATed pod traffic will only have `HOST_ID` from the ipcache (as it doesn't pass through the iptables rule that sets the mark).

Throwing `--install-iptables-rules=false` into this picture means that legitimate host traffic will not be marked either, and thus is mis-identified as "SNATed pod traffic". And so while we create a CT entry for it (and the reply traffic flow works), we don't actually apply egress policy to it when we should.

Do you agree with that assessment, or is there still something missing from the picture?

**Comment by oblazek** [comment]
> Throwing `--install-iptables-rules=false` into this picture means that legitimate host traffic will not be marked either, and thus is **mis-identified** as "SNATed pod traffic". And so while we create a CT entry for it (and the reply traffic flow works), we don't actually apply egress policy to it when we should.
> 
> Do you agree with that assessment, or is there still something missing from the picture?

You are totally right, if iptables are not present, there is no mark and `return __ipv6_host_policy_egress(ctx, src_id == HOST_ID,...`  can't be relied on. So at least there should be an logical OR:
`src_id == HOST_ID || ipcache_srcid == HOST_ID` so that egress policy is correctly enforced.

File: bpf/bpf_host.c [hunk 1]
```diff
@@ -424,13 +435,20 @@ tail_handle_ipv6(struct __ctx_buff *ctx, const bool from_host)
...
 {
-	return tail_handle_ipv6(ctx, true);
+	__u32 ipcache_srcid = 0;
+
+#if defined(ENABLE_HOST_FIREWALL) && !defined(ENABLE_MASQUERADE_IPV6)
+	ipcache_srcid = ctx_load_meta(ctx, CB_IPCACHE_SRC_LABEL);
+	ctx_store_meta(ctx, CB_IPCACHE_SRC_LABEL, 0);
+#endif /* defined(ENABLE_HOST_FIREWALL) && !defined(ENABLE_MASQUERADE_IPV6) */
+
+	return tail_handle_ipv6(ctx, ipcache_srcid, true);
```
Comment (julianwiedmann) [inline bpf/bpf_host.c:444]: This is still missing the corresponding write to `CB_IPCACHE_SRC_LABEL` in `do_netdev()`, correct?

File: bpf/lib/host_firewall.h [hunk 2]
```diff
@@ -394,7 +437,8 @@ ipv4_host_policy_egress(struct __ctx_buff *ctx, __u32 src_id,
 	if (ct_buffer.ret < 0)
 		return ct_buffer.ret;
 
-	return __ipv4_host_policy_egress(ctx, src_id == HOST_ID, ip4, &ct_buffer, trace, ext_err);
+	return __ipv4_host_policy_egress(ctx, src_id == HOST_ID || ipcache_srcid == HOST_ID,
+					ip4, &ct_buffer, trace, ext_err);
```
Comment (julianwiedmann) [inline bpf/lib/host_firewall.h]: Let's please tackle the two problems with separate patches / PRs. Understanding the IPv6 whitelisting change is difficult enough, this subtle IPv4 change only makes things more complicated. And it introduces a severe regression for current users (they now suddenly need host-level IPv4 egress policies for their SNATed pod traffic).

So let's focus this first patch on the missing IPv6 allow-listing, when combining HostFW with kube-proxy based masquerading. Could you update the PR / patch description accordingly? Happy to help with tackling `--install-iptables-rules=false` once this is sorted.

**Comment by julianwiedmann** [comment]
> > Throwing `--install-iptables-rules=false` into this picture means that legitimate host traffic will not be marked either, and thus is **mis-identified** as "SNATed pod traffic". And so while we create a CT entry for it (and the reply traffic flow works), we don't actually apply egress policy to it when we should.
> > Do you agree with that assessment, or is there still something missing from the picture?
> 
> You are totally right, if iptables are not present, there is no mark and `return __ipv6_host_policy_egress(ctx, src_id == HOST_ID,...` can't be relied on. So at least there should be a logical OR: `src_id == HOST_ID || ipcache_srcid == HOST_ID` so that egress policy is correctly enforced.
> 
> I believe the same should be done for ipv4

agree, but this needs to be a conditional change (only when `--install-iptables-rules=false` is set).

**Review by julianwiedmann — CHANGES_REQUESTED** [review]
See comments inline.

File: bpf/bpf_host.c (hunk 1 above)
Comment (oblazek) [reply bpf/bpf_host.c:444]: agree

File: bpf/lib/host_firewall.h (hunk 2 above)
Comment (oblazek) [reply bpf/lib/host_firewall.h]: Understood, will make the changes.

**Comment by oblazek** [comment]
updated, now the PR should only contain ipv6 whitelisting related changes.. will do the rest in the followup PR

File: bpf/bpf_host.c [hunk 3]
```diff
@@ -481,7 +488,7 @@ resolve_srcid_ipv4(struct __ctx_buff *ctx, struct iphdr *ip4,
 	/* Packets from the proxy will already have a real identity. */
 	if (identity_is_reserved(srcid_from_ipcache)) {
 		info = lookup_ip4_remote_endpoint(ip4->saddr, 0);
-		if (info != NULL) {
+		if (info) {
```
Comment (julianwiedmann) [inline bpf/bpf_host.c]: In case that you need to rebase once more, please drop this cleanup :).

File: bpf/lib/host_firewall.h [hunk 4]
```diff
@@ -23,8 +52,14 @@ ipv6_host_policy_egress_lookup(struct __ctx_buff *ctx, __u32 src_sec_identity,
...
-	/* Only enforce host policies for packets from host IPs. */
-	if (src_sec_identity != HOST_ID)
+	/* Further action is needed in two cases:
+	 * 1. Packets from host IPs: need to enforce host policies.
+	 * 2. SNATed packets from pods: need to create a CT entry to skip
+	 *    applying host policies to reply packets
+	 *    (see ipv6_whitelist_snated_egress_connections).
+	 */
+	if (src_sec_identity != HOST_ID &&
+	    (is_defined(ENABLE_MASQUERADE_IPV6)))
```
Comment (julianwiedmann) [inline bpf/lib/host_firewall.h]:
```suggestion
	if (src_sec_identity != HOST_ID &&
	    (is_defined(ENABLE_MASQUERADE_IPV6)  || ipcache_srcid != HOST_ID))
```

File: bpf/bpf_host.c (hunk 1 above)
Comment (julianwiedmann) [reply bpf/bpf_host.c:444]: Hmm now the `CB_IPCACHE_SRC_LABEL` part is completely gone ... that's unexpected? Pretty sure we need it.

**Review by julianwiedmann — CHANGES_REQUESTED** [review]
Ty @oblazek ! There's one part where we need to check if the mark-based identity and ipcache-based identity match up (see below). But it's missing the ipcache-based identity ... could you have a look into passing that through, along what IPv4 does?

**Comment by oblazek** [comment]
> Hmm now the CB_IPCACHE_SRC_LABEL part is com...

yeah I must have missed that when working on different branches :(

File: bpf/lib/host_firewall.h (hunk 4 above)
Comment (oblazek) [reply bpf/lib/host_firewall.h]: done

File: bpf/bpf_host.c (hunk 3 above)
Comment (oblazek) [reply bpf/bpf_host.c]: done

File: bpf/lib/host_firewall.h [hunk 5]
```diff
@@ -15,16 +15,51 @@
...
-	/* Only enforce host policies for packets from host IPs. */
-	if (src_sec_identity != HOST_ID)
+	/* Further action is needed in two cases:
+	 * 1. Packets from host IPs: need to enforce host policies.
+	 * 2. SNATed packets from pods: need to create a CT entry to skip
+	 *    applying host policies to reply packets
+	 *    (see ipv6_whitelist_snated_egress_connections).
+	 */
+	if (src_sec_identity != HOST_ID &&
+	    (is_defined(ENABLE_MASQUERADE_IPV6) || ipcache_srcid != HOST_ID))
```
Comment (YutaroHayakawa) [inline bpf/lib/host_firewall.h:62]: I might be confused, but should this be `!is_defined(ENABLE_MASQUERADE_IPV6)`? We want to catch the case that masquerading is disabled in this case right?

File: bpf/bpf_host.c [hunk 6]
```diff
@@ -91,7 +91,8 @@ static __always_inline bool identity_from_ipcache_ok(void)
 #ifdef ENABLE_IPV6
 static __always_inline __u32
 resolve_srcid_ipv6(struct __ctx_buff *ctx, struct ipv6hdr *ip6,
-		   __u32 srcid_from_proxy, const bool from_host)
+		   __u32 srcid_from_proxy, __u32 *sec_identity,
```
Comment (YutaroHayakawa) [inline bpf/bpf_host.c]:
```suggestion
		   __u32 srcid_from_ipcache, __u32 *sec_identity,
```

and delete below assignment.

File: bpf/bpf_host.c [hunk 7]
```diff
@@ -439,7 +456,7 @@ handle_to_netdev_ipv6(struct __ctx_buff *ctx, struct trace_ctx *trace, __s8 *ext
 {
 	void *data, *data_end;
 	struct ipv6hdr *ip6;
-	__u32 src_id = 0;
+	__u32 src_id = 0, ipcache_srcid = 0;
```
Comment (YutaroHayakawa) [inline bpf/bpf_host.c]:
```suggestion
	__u32 srcid = 0, ipcache_srcid = 0;
```

for consistency.

**Review by YutaroHayakawa — CHANGES_REQUESTED** [review]
I made an initial look. The logic to set `CB_IPCACHE_SRC_LABEL` is still missing, but otherwise, the logic looks correct to me. I found some small naming inconsistency and one potential bug.

File: bpf/lib/host_firewall.h (hunk 5 above)
Comment (oblazek) [reply bpf/lib/host_firewall.h:62]: I don't think so, if we are talking about "kube-proxy based masq" (which means that pod traffic is SNATed anyway, this function gets HOST_IP in the packet, but there is no packet mark) --> `if (1 && (0 || 0))` (src_sec_identity is not HOST_ID, is_defined(ENABLE_MASQUERADE_IPV6) is false, ipcache_srcid is HOST_ID) => false, which means the code returns true which we want so that `ipv6_whitelist_snated_egress_connections` can be run afterwards

File: bpf/bpf_host.c (hunk 6 above)
Comment (oblazek) [reply bpf/bpf_host.c:94]: :+1:

File: bpf/lib/host_firewall.h (hunk 5 above)
Comment (YutaroHayakawa) [reply bpf/lib/host_firewall.h:62]: Ah, never mind. I was wrong. `is_defined(ENABLE_MASQUERADE_IPV6) == true` means "BPF-based IPv6 masquerading is enabled", so when `is_defined(ENABLE_MASQUERADE_IPV6) == true`, the packet is not masqueraded at this point.

**Review by YutaroHayakawa — APPROVED** [review]
Now LGTM 👍

**Review by julianwiedmann — APPROVED** [review]
ty!
