### PR TITLE
hubble: Fix reply state unknown being interpreted as false 

### LINKED ISSUE #13744: Hubble possibly misrepresenting replies as requests for UDP traffic
## Bug report

**General Information**

- Cilium version (run `cilium version`)

```
Client: 1.8.4 17d623853 2020-09-30T17:31:44-07:00 go version go1.14.9 linux/amd64
Daemon: 1.8.4 17d623853 2020-09-30T17:31:44-07:00 go version go1.14.9 linux/amd64
```

- Kernel version (run `uname -a`)

```
Linux ip-10-105-14-33 5.4.0-1028-aws #29-Ubuntu SMP Mon Oct 5 15:30:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.13", GitCommit:"30d651da517185653e34e7ab99a792be6a3d9495", GitTreeState:"clean", BuildDate:"2020-10-15T00:59:17Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Link to relevant artifacts (policies, deployments scripts, ...)

On these nodes, ephemeral port range is
```
$ cat /proc/sys/net/ipv4/ip_local_port_range
32768   60999
```

- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

was unable to generate the dump, sorry

**How to reproduce the issue**

1. Enable Hubble metrics
2. Make sure `port-distribution` metric is enabled
3. See `port-distribution` metric cardinality explode due to alleged UDP requests (from ephemeral port range).

On the target system, running Cilium monitor shows UDP traffic:
```
$ cilium monitor | grep ud

-> endpoint 2669 flow 0x0 identity 11980->49072 state reply ifindex lxcdaea9e2f5946 orig-ip 100.64.9.148: 100.96.0.10:53 -> 100.64.9.230:44005 udp
-> endpoint 2631 flow 0x3a6e9cf4 identity 49072->11980 state established ifindex lxc1775c9458c08 orig-ip 100.64.9.230: 100.64.9.230:44005 -> 100.64.9.148:53 udp
-> endpoint 2669 flow 0x0 identity 11980->49072 state reply ifindex lxcdaea9e2f5946 orig-ip 100.64.9.148: 100.96.0.10:53 -> 100.64.9.230:44005 udp
-> endpoint 2631 flow 0x3a6e9cf4 identity 49072->11980 state established ifindex lxc1775c9458c08 orig-ip 100.64.9.230: 100.64.9.230:44005 -> 100.64.9.148:53 udp
...
```

but adding `grep -v ':53'` produces no results. This suggests that all UDP traffic observed is DNS. There are no services that would generate UDP traffic in this cluster other than CoreDNS.

### PR DESCRIPTION
**Pull request by gandro**
This fixes a long-standing issue with Hubble not being able to
distingiush between the reply field being false and the reply field
being absent. To address the issue, the old `reply` field is replaced
with a tri-state `is_reply` field which can be either nil, true or
false. All uses of the old field are removed in the source tree, but the
field itself is preserved for backwards-compatibility.

This incidentally also fixes a bug where the `port-distribution` metric
suffered from the same confusion, which caused it to report source ports
as destination ports.

Ref: #13248
Fixes: #13744

### CODE REVIEW

File: pkg/hubble/filters/reply.go [hunk 1]
```diff
@@ -29,30 +27,11 @@ func filterByReplyField(replyParams []bool) FilterFunc {
...
-					return false
-				}
+			if f.GetIsReply() == nil {
+				return false
 			}
-			// For PolicyVerdict and Drop events, we statically assume they
-			// always have `reply=false`, as the flow is not yet established
-			// when the policy verdict is taken.
-			// For all other events (including Accesslog/L7), we assume the
-			// parser populates the Reply field reliably.
```
Comment (gandro) [inline pkg/hubble/filters/reply.go:53]: Reviewer note: This assumption is not presumed anymore with this change, so there is a slight change in behavior here: The reply filter will never report any Drop or Policy Verdict events anymore (as they have `is_reply` always nil).

If people feel strongly about this, I'm happy to add back an exception in the filter logic here to keep this previous behavior. But I'm not 100% confident that the exception is always correct (e.g. we could have dropped a spurious reply packet), which is why I removed it.

**Comment by gandro** [comment]
Unfortunately we don't have proper CI for the metrics yet. But here are some stats from my local testing.

Hubble with the connectivity-check.yaml running and the port-distribution metric enabled.

Without the bugfix, after ~15 minutes:
```console
$ curl -s localhost:9091/metrics | grep hubble_port_distribution_total | wc -l
8343
```

With the bug fix applied:
```console
$ curl -s localhost:9091/metrics | grep hubble_port_distribution_total | wc -l
11
```

**Review by rolinh — APPROVED** [review]
:100:

File: pkg/hubble/parser/threefour/parser.go [hunk 2]
```diff
@@ -183,7 +184,8 @@ func (p *Parser) Decode(data []byte, decoded *pb.Flow) error {
 	decoded.SourceNames = p.resolveNames(dstEndpoint.ID, srcIP)
 	decoded.DestinationNames = p.resolveNames(srcEndpoint.ID, dstIP)
 	decoded.L7 = nil
-	decoded.Reply = decodeIsReply(tn)
+	decoded.IsReply = decodeIsReply(tn)
+	decoded.Reply = decoded.GetIsReply().GetValue()
```
Comment (michi-covalent) [inline pkg/hubble/parser/threefour/parser.go:188]: do we need to check if `decoded.GetIsReply()` is nil? looks like `decodeIsReply` can return nil here.

**Review by michi-covalent — APPROVED** [review]
lgtm 👍 one question around nil check

File: pkg/hubble/parser/threefour/parser.go (hunk 2 above)
Comment (gandro) [reply pkg/hubble/parser/threefour/parser.go:188]: The protobuf getters take care of that :)
https://github.com/cilium/cilium/blob/8909c7f87a0c5d2b2e11e92b4c4e8ba37c60a03a/vendor/google.golang.org/protobuf/types/known/wrapperspb/wrappers.pb.go#L438-L443

Comment (rolinh) [reply pkg/hubble/parser/threefour/parser.go:188]: I think it's fine because this would only be if the flow (ie `decoded` here) is itself `nil`. But we should maybe check if `decoded` is `nil` early on.

**Comment by gandro** [comment]
test-me-please

**Review by glibsm — APPROVED** [review]

File: pkg/hubble/parser/threefour/parser.go (hunk 2 above)
Comment (gandro) [reply pkg/hubble/parser/threefour/parser.go:188]: `decoded` being `nil` is something would panic much earlier. It currently will not happen, because none of the code is invoking the three/seven parsers directly (and the top-level `parser.Decode` always initializes `decoded`).  

We could always add additional checks, but I'm marking this as resolved as it is completely unrelated to the PR.

**Comment by gandro** [comment]
Two CI flakes:
Provisioning error GKE (timeout in "selecting random cluster"): https://jenkins.cilium.io/job/Cilium-PR-K8s-GKE/2949/console
Runtime-4.9 hit: #12891 https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/2319/

**Comment by gandro** [comment]
retest-gke

**Comment by gandro** [comment]
retest-4.9

**Comment by gandro** [comment]
retest-runtime
