### PR TITLE
Fix cluster entity behavior

### LINKED ISSUE #5739: Fix behavior of cluster identity

### PR DESCRIPTION
**Pull request by tgraf**
Requires: #5771 (to solve upgrade impact)

This completely removes the cluster identity and removes almost all of the logic depending on being aware of the cluster CIDR range.

What currently remains is:
* The SNAT rule for traffic into `cilium_host` excludes the cluster range if direct routing is configured. This rule is harder to remove. A possibility is to maintain an ipset with all node prefixes and add/remove it based on node discovery.

It also fixes the behavior of the cluster entity to the following new definition:
 - All known endpoints in the local cluster, i.e. all endpoints which have a
   cluster label that equals to the cluster name associated with the
   local cilium-agent.
 - The host identity to include communication to cluster nodes and host
   networking endpoints
 - The init identity to allow communication to endpoints starting up in
   the local cluster.

Fixes: #5739

## TODO
- [x] Evaluate whether the addition of the cluster label must be hidden behind an opt-in flag
- [x] Upgrade test
- [x] Evaluate whether cluster entity should include host or whether two entities should be used to define endpoints only and endpoints+host

This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5581)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-me-please

Legit failure in runtime test:
`19:09:07 STEP: checking that reserved identity 'cluster' is in 'cilium identity list' output`

k8s tests passed

**Comment by tgraf** [comment]
test-me-please

green build

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
The latest removal of bpf code resulted in an increase of instructions.

EDIT: The issue was tracked down to the removal of `revalidate_data()`

**Comment by tgraf** [comment]
test-me-please

green build

File: pkg/labels/cidr/cidr_test.go [hunk 1]
```diff
@@ -121,7 +109,7 @@ func (s *CIDRLabelsSuite) TestGetCIDRLabelsInCluster(c *C) {
 	expected := labels.ParseLabelArray(
 		"cidr:0.0.0.0/0",
 		"cidr:10.0.0.0/16",
-		"reserved:cluster",
+		"reserved:world",
```
Comment (joestringer) [inline pkg/labels/cidr/cidr_test.go:112]: We can probably drop this entire test, there's no difference between in-cluster / out-of-cluster CIDR identities any more.

**Review by joestringer — DISMISSED** [review]
This looks worthy of a release note.

Also wondering about the upgrade considerations:

* These labels may exist in kvstore (eg in existing labels->identity mappings for CIDRs in the cluster prefix). I suppose that newer Cilium instances will generate different identities for the same CIDR and not use the ones that would previously be used. ~~During upgrade this could cause some disruption as newer Cilium instances roll out using the new identity and older instances continue to operate on the old identity for the same CIDR.~~ Given that these would only be used on egress from a given node, the inconsistency between nodes shouldn't cause problems with connectivity between nodes.

* We still have the entity cluster, but I can't quite figure out what it will do. We presumably would need this to avoid parse errors when importing existing CNPs during upgrade (otherwise we would reject the policy). Does it just map to an identity that never matches anything?

How can we make it obvious to users that they are using an entity in their policies that no longer works?

**Comment by tgraf** [comment]
@joestringer I've updated the first commit with upgrade considerations and added a 2nd commit to further reduce the dependency on the cluster range. What remains is the dependency for direct routing mode. I'm thinking about adding an explicitly required option for direct routing to specify the overall prefix.

**Comment by tgraf** [comment]
test-me-please

green build

**Comment by tgraf** [comment]
test-me-please

legit `go fmt` error

File: pkg/policy/api/entity.go [hunk 2]
```diff
@@ -44,37 +44,49 @@ const (
...
 
 // EntitySlice is a slice of entities
 type EntitySlice []Entity
 
 // Matches returns true if the entity matches the labels
 func (e Entity) Matches(ctx labels.LabelArray) bool {
-	if selector, ok := EntitySelectorMapping[e]; ok {
-		return selector.Matches(ctx)
+	if selectors, ok := EntitySelectorMapping[e]; ok {
+		for _, selector := range selectors {
```
Comment (joestringer) [inline pkg/policy/api/entity.go]: Open-coding `EndpointSelectorSlice.Matches()`?

**Review by joestringer — COMMENTED** [review]
Do you think there might be a case where someone wants to allow ingress from all endpoints in the cluster but not from nodes in the underlay? Wouldn't it be more explicit to require users to also specify host in their policies?

**Comment by rlenglet** [comment]
> The init identity to allow communication to endpoints starting up in
the local cluster.

@tgraf I don't understand why this should be a default behavior. Couldn't this be allowed explicitly by an init policy?

**Comment by rlenglet** [comment]
> > The init identity to allow communication to endpoints starting up in
> > the local cluster.
> 
> @tgraf I don't understand why this should be a default behavior. Couldn't this be allowed explicitly by an init policy?

Or I don't understand what this means...

**Comment by tgraf** [comment]
> I don't understand why this should be a default behavior. Couldn't this be allowed explicitly by an init policy?

All entities can be described with more explicit label based policies. It's really just a simplification to hide implementation details. The thinking is that an init identity is guaranteed to be an endpoint in the cluster.

**Comment by tgraf** [comment]
Added runtime tests for entities

**Comment by tgraf** [comment]
test-me-please

unit test failure due to cast problem

**Comment by tgraf** [comment]
test-me-please

**Review by jrajahalme — APPROVED** [review]
Approving changes to pkg/proxy/logger/logger.go on behalf of the "proxy" area.

**Comment by tgraf** [comment]
test-me-please

**Comment by joestringer** [comment]
Current issue:

```
00:50:44 # github.com/cilium/cilium/daemon
00:50:44 daemon/k8s_watcher_test.go:818:14: undefined: identity.ReservedIdentityCluster
00:50:44 daemon/k8s_watcher_test.go:854:14: undefined: identity.ReservedIdentityCluster
00:50:44 daemon/k8s_watcher_test.go:910:14: undefined: identity.ReservedIdentityCluster
00:50:44 daemon/k8s_watcher_test.go:950:14: undefined: identity.ReservedIdentityCluster
00:50:44 daemon/k8s_watcher_test.go:1068:14: undefined: identity.ReservedIdentityCluster
00:50:44 daemon/k8s_watcher_test.go:1109:14: undefined: identity.ReservedIdentityCluster
00:50:44 daemon/k8s_watcher_test.go:1139:14: undefined: identity.ReservedIdentityCluster
```

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
> 00:50:44 daemon/k8s_watcher_test.go:818:14: undefined: identity.ReservedIdentityCluster

Was caused by the rebase and the addition of new code depending on `ReservedIdentityCluster`. Fixed

File: bpf/lib/policy.h [hunk 3]
```diff
@@ -30,7 +30,6 @@
  * - IdentityUnknown		(0)
  * - ReservedIdentityHost	(1)
  * - ReservedIdentityWorld	(2)
- * - ReservedIdentityCluster	(3)
```
Comment (raybejjani) [inline bpf/lib/policy.h:33]: It might be better to leave this marked in some way? I would hate to re-use this identity and forget that it meant something to older cilium versions (same for the actual define in node_config.h)

**Comment by tgraf** [comment]
test-me-please

EDIT: Legit CI failures due to bugs in tests:
* toEntities world did not whitelist kube-dns so resolving google.com failed
* toEntities cluster whitelists kube-dns so resolving the DNS name for google.com will succeed but the outgoing connection will fail

**Comment by tgraf** [comment]
test-me-please

File: pkg/defaults/node.go [hunk 4]
```diff
@@ -25,9 +25,6 @@ const (
 	// IPv6NodePrefixLen is the length used to allocate container IPv6 addresses from.
 	IPv6NodePrefixLen = 96
 
-	// DefaultIPv6ClusterPrefixLen is the IPv6 prefix length of the entire cluster.
-	DefaultIPv6ClusterPrefixLen = 64
```
Comment (raybejjani) [inline pkg/defaults/node.go:29]: I haven't checked, but should `DefaultIPv4ClusterPrefixLen` also be removed?

File: daemon/daemon.go [hunk 5]
```diff
@@ -550,7 +549,7 @@ func (d *Daemon) installIptablesRules() error {
 	// cilium_host interface with a source IP in the cluster range.
 	if err := runProg("iptables", []string{
 		"-A", ciliumForwardChain,
-		"-s", node.GetIPv4ClusterRange().String(),
+		"-s", node.GetIPv4AllocRange().String(),
```
Comment (raybejjani) [inline daemon/daemon.go:557]: The comment above may need to be updated? `GetIPv4ClusterRange` is the range for this node, and that might change this behaviour? I'm not sure if it was intended to be specific to the node range, or a catch-all for any packet sent to the overlay.

File: daemon/daemon.go [hunk 6]
```diff
@@ -539,7 +539,6 @@ func (d *Daemon) installIptablesRules() error {
 	// with a destination IP in the cluster range.
 	if err := runProg("iptables", []string{
 		"-A", ciliumForwardChain,
-		"-d", node.GetIPv4ClusterRange().String(),
 		"-o", "cilium_host",
```
Comment (raybejjani) [inline daemon/daemon.go:546]: Wouldn't `GetIPv4AllocRange` go here, like the rule below?

**Review by raybejjani — DISMISSED** [review]
We seem to remove some of the IPv4 stuff in some places, and IPv6 in others. I can probably dig in more but it what's the distinction? I was expecting the same changes to IPv4 and IPv6.

File: pkg/defaults/node.go (hunk 4 above)
Comment (tgraf) [reply pkg/defaults/node.go:29]: There is one use remaining right now:
```
                ingressSnatSrcAddrExclusion := node.GetHostMasqueradeIPv4().String()
                if option.Config.Tunnel == option.TunnelDisabled {
                        ingressSnatSrcAddrExclusion = node.GetIPv4ClusterRange().String()
                }
```

File: daemon/daemon.go (hunk 6 above)
Comment (tgraf) [reply daemon/daemon.go:546]: Unfortunately, that will be too restrictive as a local process talking to a remote pod IP will go this path and will need to be masqueraded. As written in the commit message, it is safe to ignore the destination IP as the path into cilium_host can only be taken if a route is pointing to it. I've clarified this with a better comment.

**Comment by tgraf** [comment]
test-me-please

EDIT:
* k8s tests passed
* runtime tests failed in kafka tests, unrelated

**Review by raybejjani — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

EDIT: green build

**Comment by tgraf** [comment]
While testing upgrade connectivity, I've observed the expected short connectivity problem. This is not a new problem overall. Any change in security labels of an endpoint will cause a short disruption until all other nodes have adjusted right now. Addition of the cluster name as part of the label is forcing this issue for all endpoints on upgrade though.

**Comment by tgraf** [comment]
The upgrade impact will be solved by #5771. I've upgraded several times and did not observe any connectivity issues. The only potential issue is that the grace period is not long enough. We should continue testing and adjust the grace period if needed before we release.

File: bpf/bpf_lxc.c [hunk 7]
```diff
@@ -117,7 +117,6 @@ static inline int ipv6_l3_from_lxc(struct __sk_buff *skb,
 				   __u32 *dstID)
```
Comment (ianvernon) [inline bpf/bpf_lxc.c:117]: Typos in commit: 

"is not n endpoint identity or a host" --> "is not an endpoint identity or a host"
"The behavior was undefined to the most extend as cluster range detection is
   inaccurate." - not sure what this means.
"When the ipcache is first populated based on pod notifications, before the
   kvstore is available." - not a complete sentence.

File: Documentation/policy/language.rst [hunk 8]
```diff
@@ -292,12 +292,25 @@ by the selected endpoints.
 The following entities are defined:
 
 host
-    The local host serving the endpoint. On ingress, this also includes
-    the host of other Cilium cluster nodes.
+    The host entity includes all cluster nodes. This also includes all
+    containers running in host networking mode.
+cluster
+    Cluster is the logical group of all network endpoints inside of the local
+    cluster. This includes all Cilium managed endpoints of the local cluster.
```
Comment (ianvernon) [inline Documentation/policy/language.rst]: Cilium-managed

File: Documentation/concepts.rst [hunk 9]
```diff
@@ -380,11 +380,24 @@ identities are prefixed with the string ``reserved:``.
...
+|                     | that originates from or is designated to one of   |
+|                     | the IPs of any host in the cluster is assigned the|
+|                     | reserved:host identity.                           |
 +---------------------+---------------------------------------------------+
 | reserved:world      | Any network endpoint outside of the cluster       |
 +---------------------+---------------------------------------------------+
+| reserved:health     | This is health checking traffic generated by      |
+|                     | Cilium agents.                                    |
++---------------------+---------------------------------------------------+
+| reserved:init       | An endpoint for which the identity has not be     |
```
Comment (ianvernon) [inline Documentation/concepts.rst]: ... for which the identity has not yet been resolved is assigned the init identity.

File: Documentation/concepts.rst [hunk 10]
```diff
@@ -380,11 +380,24 @@ identities are prefixed with the string ``reserved:``.
...
+|                     | resolved for yet is assigned the init identity.   |
+|                     | This represents the phase of an endpoint in which |
+|                     | some of the metadata required to derive the       |
+|                     | security identity is still missing.               |
```
Comment (ianvernon) [inline Documentation/concepts.rst]: Maybe note that this is most common in the case of endpoint bootstrapping?

File: test/k8sT/Policies.go [hunk 11]
```diff
@@ -131,6 +135,72 @@ var _ = Describe("K8sPolicyTest", func() {
...
+		}
+
+		validateConnectivity := func(expectWorldSuccess, expectClusterSuccess bool) {
+			for _, pod := range []string{appPods[helpers.App2], appPods[helpers.App3]} {
+				res := kubectl.ExecPodCmd(
+					helpers.DefaultNamespace, pod,
+					helpers.CurlFail("http://www.google.com/"))
+
+				if expectWorldSuccess {
+					res.ExpectSuccess("Egress connectivity to google.com should be allowed for pod %q", pod)
```
Comment (ianvernon) [inline test/k8sT/Policies.go]: ExpectWithOffset? Similar for other `Expect*` in this function.

File: test/k8sT/Policies.go [hunk 12]
```diff
@@ -131,6 +135,72 @@ var _ = Describe("K8sPolicyTest", func() {
...
+					pod, cep.Status.Policy.Realized.PolicyEnabled, desiredState)
+			}
+		}
+
+		validateConnectivity := func(expectWorldSuccess, expectClusterSuccess bool) {
+			for _, pod := range []string{appPods[helpers.App2], appPods[helpers.App3]} {
+				res := kubectl.ExecPodCmd(
+					helpers.DefaultNamespace, pod,
+					helpers.CurlFail("http://www.google.com/"))
+
```
Comment (ianvernon) [inline test/k8sT/Policies.go:165]: Would be helpful to add calls to `By` here that contain the values of `expectWorldSuccess` and `expectClusterSuccess`. It will make the test more readable / easier to follow.

**Comment by ianvernon** [comment]
I like the change overall. The upgrade testing is being done manually, so that covers my biggest concern around this change, which is how existing environments will be affected.

**Comment by tgraf** [comment]
test-me-please

EDIT:
* k8s 1.11 passed
* k8s 1.8 failed with `    <*helpers.SSHMetaError | 0xc42186f800>: Error: Timeout reached: cannot change state of resource correctly; command timed out`

Rebasing due to merge conflict in `bpf.sha`

**Comment by tgraf** [comment]
test-me-please

**Comment by raybejjani** [comment]
@ianvernon @joestringer I'm afraid github decided that your comments are reviews. I'm going to guess that you "approve" and merge this by tomorrow EU time, assuming tgraf doesn't merge it anyway.

**Comment by tgraf** [comment]
Removing 1.2 backport request
