### PR TITLE
don't merge stderr into iptable stdout

### LINKED ISSUE #20894: "Failed to install iptables rules" causes anetd crashes
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Sometimes, we notice anetd crashes on RHEL/centos nodes due to error:

```
level=fatal msg="Error while creating daemon" error="error while initializing daemon: failed while reinitializing datapath: failed to install iptables rules: unable to run 'iptables -t filter -D OLD_CILIUM_OUTPUT -m mark ! --mark 0xe00/0xf00 -m mark ! --m# Warning: iptables-legacy tables present, use iptables-legacy to see them' iptables command: iptables v1.8.4 (nf_tables): unknown option \"--m#\"\nTry `iptables -h' or 'iptables --help' for more information.\n (exit status 2)" subsys=daemon
```

Clearly the stderr output (# Warning: iptables-legacy tables present, use iptables-legacy to see them) of iptables mixed into stdout causes the failure.

The issue has been around a while but become noticeable after commit d812b925dec2d8be09834277050050d67681fd7c

There is no clear way to reproduce. it shows up in our CIs randomly. Also golang exec.CombinedOutput should be thread-safe and stdout and stderr shouldn't be interleaved.

For now, I'm seeing a mitigation is not to merge stderr into the output but putting it into err.

### Cilium Version

1.11.7

### Kernel Version

4.18.0-305 

centos 8.4

### Kubernetes Version

v1.23.5-gke.1504

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by liuyuan10**
runProgCombinedOutput merges stdout and stderr of iptables into a single
string and parse iptables rules out from it. But stderr is never rules but warnings/errors. For example, stderr can be "# Warning: iptables-legacy
tables present, use iptables-legacy-save to see them"

This commit changes it to use exec.Output but merge stderr into err.

Fixes: #20894

Signed-off-by: Yuan Liu <liuyuan@google.com>

```release-note
put stderr of iptables command into error instead of merging into stdout
```

### CODE REVIEW

**Review by aanm — CHANGES_REQUESTED** [review]
@liuyuan10 I think you have signed the commit with the wrong name :confused:

**Comment by liuyuan10** [comment]
thanks for catching that. I was doing copy paste with my eye covered

File: pkg/command/exec/exec.go [hunk 1]
```diff
@@ -56,8 +56,14 @@ func output(ctx context.Context, cmd *exec.Cmd, filters []string, scopedLog *log
 		}
 		return nil, fmt.Errorf("Command execution failed for %s: %w", cmd.Args, ctx.Err())
 	}
-	if err != nil && verbose {
-		warnToLog(cmd, filters, out, scopedLog, err)
+	if err != nil {
+		exitErr, ok := err.(*exec.ExitError)
```
Comment (ldelossa) [inline pkg/command/exec/exec.go]: Could this use  `errors.Is()` or `errors.As()` instead ?

**Review by ldelossa — APPROVED** [review]
Looks good to me, you may want to use the errors package to discern the error type, see comment.

File: pkg/command/exec/exec.go (hunk 1 above)
Comment (liuyuan10) [reply pkg/command/exec/exec.go]: done. thanks for letting me know these useful helpers.

**Review by nathanjsweet — APPROVED** [review]

**Review by NikAleksandrov — APPROVED** [review]

**Comment by liuyuan10** [comment]
@aanm can we merge it?

**Review by aanm — APPROVED** [review]

**Comment by joestringer** [comment]
Is this a bugfix? Should we backport at least to v1.12?

**Comment by liuyuan10** [comment]
I would prefer a backport given it's a low-risk change and indeed it helped fixing #20894 for us

**Comment by julianwiedmann** [comment]
https://github.com/cilium/cilium/pull/19693 went back to `v1.10` and `v1.11`, let's unbreak those as well.
