### PR TITLE
daemon: Create IPsec and LRP maps early on startup

### LINKED ISSUE #32387: CI: Conformance E2E: check-log-errors: map cilium_xxx: pin map to /sys/fs/bpf/tc/globals/cilium_xxx: file exists
## CI failure

Example failure: https://github.com/cilium/cilium/actions/runs/8973068389/job/24642423324#step:14:218

Example logs: [logs-cilium-bzlbg-cilium-agent-20240506-174142.log](https://github.com/cilium/cilium/files/15225341/logs-cilium-bzlbg-cilium-agent-20240506-174142.log)

```
  ❌ Found 3 logs in kind-kind/kube-system/cilium-bzlbg (cilium-agent) matching list of errors that must be investigated:
time="2024-05-06T17:24:18Z" level=warning msg="JoinEP: Failed to attach program(s)" ciliumEndpointName=kube-system/coredns-76f75df574-78qsr containerID=96ff8c8492 containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=2291 error="loading eBPF collection into the kernel: map cilium_encrypt_state: pin map to /sys/fs/bpf/tc/globals/cilium_encrypt_state: file exists" file-path=2291_next/bpf_lxc.o identity=15635 ipv4=10.244.1.134 ipv6="fd00:10:244:1::d9e1" k8sPodName=kube-system/coredns-76f75df574-78qsr subsys=datapath-loader veth=lxcfcaaf011bcdc (1 occurrences)
time="2024-05-06T17:24:18Z" level=error msg="Error while rewriting endpoint BPF program" ciliumEndpointName=kube-system/coredns-76f75df574-78qsr containerID=96ff8c8492 containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=2291 error="loading eBPF collection into the kernel: map cilium_encrypt_state: pin map to /sys/fs/bpf/tc/globals/cilium_encrypt_state: file exists" identity=15635 ipv4=10.244.1.134 ipv6="fd00:10:244:1::d9e1" k8sPodName=kube-system/coredns-76f75df574-78qsr subsys=endpoint (1 occurrences)
time="2024-05-06T17:24:18Z" level=error msg="endpoint regeneration failed" ciliumEndpointName=kube-system/coredns-76f75df574-78qsr containerID=96ff8c8492 containerInterface= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=2291 error="loading eBPF collection into the kernel: map cilium_encrypt_state: pin map to /sys/fs/bpf/tc/globals/cilium_encrypt_state: file exists" identity=15635 ipv4=10.244.1.134 ipv6="fd00:10:244:1::d9e1" k8sPodName=kube-system/coredns-76f75df574-78qsr subsys=endpoint (1 occurrences)
```

### PR DESCRIPTION
**Pull request by pchaigno**
We have some sort of race popping up in CI from time to time around the loading of some BPF maps:

    loading eBPF collection into the kernel: map cilium_encrypt_state: pin map to /sys/fs/bpf/tc/globals/cilium_encrypt_state: file exists

One approach to avoid this is to ensure such maps are always created early on agent startup instead of being created during endpoint creation (where concurrent program loadings can run into this race).

This commit therefore adds the two maps concerned by this issue to the `initMaps` method.

Fixes: https://github.com/cilium/cilium/issues/32387.
```
Avoid race that could result in an error log during creation of IPsec or LRP BPF maps.
```

### CODE REVIEW

File: pkg/maps/policymap/policymap.go [hunk 1]
```diff
@@ -512,7 +512,7 @@ func InitCallMaps(haveEgressCallMap bool) error {
 	)
 	err := policyCallMap.Create()
 
-	if err == nil && haveEgressCallMap {
```
Comment (gentoo-root) [inline pkg/maps/policymap/policymap.go:515]: I guess the haveEgressCallMap parameter can be removed altogether?

**Review by gentoo-root — APPROVED** [review]
