### PR TITLE
Fix cilium configfile CLI

### LINKED ISSUE #7732: Every cilium command complains "Error reading default config ..."
```
$ cilium status
level=warning msg="Error reading default config: Config File \"ciliumd\" Not Found in \"[/home/vagrant]\"" subsys=daemon
KVStore:                Ok         Consul: 172.17.0.3:8300
ContainerRuntime:       Ok         docker daemon: OK
Kubernetes:             Disabled
Cilium:                 Ok         OK
NodeMonitor:            Disabled
Cilium health daemon:   Ok
IPv4 address pool:      3/65535 allocated from 10.11.0.0/16
IPv6 address pool:      3/65535 allocated from f00d::a0b:0:0:0/112
Controller Status:      13/13 healthy
Proxy Status:           OK, ip 10.11.0.1, port-range 10000-20000
Cluster health:          0/1 reachable   (2019-04-15T21:34:52Z)
  Name                   IP              Reachable   Endpoints reachable
  runtime1 (localhost)   10.0.2.15       true        false
```

### PR DESCRIPTION
**Pull request by joestringer**
PR https://github.com/cilium/cilium/pull/7703 introduced a regression into the CLI, where every single Cilium commandline invocation would lead to the following error message being printed:

```
level=warning msg="Error reading default config: Config File \"ciliumd\" Not Found in \"[/home/vagrant]\"" subsys=daemon
```

This PR fixes it by:
1. Skipping the init() logic for the daemon if the command being run isn't `cilium-agent` (eg, `cilium` cli which shares the same base binary).
1. Rewording the log so that it appears like an innocuous informational message, rather than a warning that the user did something wrong.
   * On the way here, it also improves logging library usage style to use `WithField()`.

Fixes: #7732

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7733)

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

File: daemon/daemon_main.go [hunk 1]
```diff
@@ -782,11 +787,13 @@ func initConfig() {
...
-		log.Infof("Using config file: %s", viper.ConfigFileUsed())
+		log.WithField(logfields.Path, viper.ConfigFileUsed()).
+			Info("Using config from file")
 	} else if option.Config.ConfigFile != "" {
-		log.Fatalf("Error reading config file %s: %s", option.Config.ConfigFile, err)
+		log.WithField(logfields.Path, option.Config.ConfigFile).
+			Fatal("Error reading config file")
 	} else {
-		log.Warnf("Error reading default config: %s", err)
+		log.WithField(logfields.Reason, err).Info("Skipped reading configuration file")
```
Comment (joestringer) [inline daemon/daemon_main.go:805]: I set this to use `logfields.Reason` just because the error isn't really something that users need to concern themselves with unless they're expecting to use this functionality. Here's how it will appear in the daemon logs:

```
level=info msg="Skipped reading configuration file" reason="Config File \"ciliumd\" Not Found in \"[/home/vagrant]\"" subsys=daemon
```

It's really searching `ciliumd.[yaml|json|...]`, but apparently the upstream library's log message doesn't reveal this very well in its error message generation.

**Comment by joestringer** [comment]
test-me-please

EDIT: CI failure looks entirely unrelated:

https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/11619/testReport/junit/(root)/Suite-runtime/RuntimeLB_With_Containers_validates_service_recovery_on_restart/
```
Stacktrace
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:410
Service list does not match
Expected
    <string>: "...0.15.171.20..."
to equal               |
    <string>: "...0.15.221.23..."
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/src/github.com/cilium/cilium/test/runtime/lb.go:318
```

**Review by ianvernon — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

**Comment by The-Loeki** [comment]
Hi @joestringer & @tgraf! I was just looking into this as well; thing that has me stumped is this message will still pop up, even if I configured a --config; that will get read in correctly though, but if I read the logic correctly, how could it pop up there again??? 

```
################ LOADED CONFIG: level=info msg="Using config file: /etc/cilium/config.yml" subsys=daemon
level=info msg="  --access-log=''" subsys=daemon
level=info msg="  --agent-labels=''" subsys=daemon
level=info msg="  --allow-localhost='auto'" subsys=daemon
level=info msg="  --auto-direct-node-routes='false'" subsys=daemon
(<SNIP>)
level=info msg="  --version='false'" subsys=daemon
level=info msg="     _ _ _" subsys=daemon
level=info msg=" ___|_| |_|_ _ _____" subsys=daemon
level=info msg="|  _| | | | | |     |" subsys=daemon
level=info msg="|___|_|_|_|___|_|_|_|" subsys=daemon
level=info msg="Cilium 1.5.0-rc4 b8566d0c9 2019-04-15T17:39:14-07:00 go version go1.12.1 linux/amd64" subsys=daemon
level=info msg="cilium-envoy  version: 68c49eeb8241867829c5eab4dff13a316c71c355/1.11.0-dev/Modified/RELEASE/BoringSSL" subsys=daemon
level=info msg="clang (7.0.0) and kernel (4.20.16) versions: OK!" subsys=daemon
level=info msg="linking environment: OK!" subsys=daemon
level=info msg="bpf_requirements check: OK!" subsys=daemon
level=info msg="Detected mounted BPF filesystem at /sys/fs/bpf" subsys=bpf
level=info msg="Valid label prefix configuration:" subsys=labels-filter
level=info msg=" - :io.kubernetes.pod.namespace" subsys=labels-filter
(<SNIP>)
level=info msg="Initializing daemon" subsys=daemon
level=info msg="Detected MTU 1500" subsys=mtu
(<SNIP>)
level=info msg="Envoy: Starting xDS gRPC server listening on /var/run/cilium/xds.sock" subsys=envoy-manager
level=info msg="Validating configured node address ranges" subsys=daemon
level=info msg="Starting connection tracking garbage collector" subsys=daemon
level=info msg="Initial scan of connection tracking completed" subsys=endpoint-manager
level=info msg="Launching node monitor daemon" subsys=daemon
level=info msg="Enabling k8s event listener" subsys=daemon
################ TRIED TO LOAD DEFAULT CONFIG???: level=warning msg="Error reading default config: Config File \"ciliumd\" Not Found in \"[/root]\"" subsys=daemon
level=info msg="Serving cilium node monitor v1.0 API at unix:///var/run/cilium/monitor.sock" subsys=cilium-node-monitor
level=info msg="Serving cilium node monitor v1.2 API at unix:///var/run/cilium/monitor1_2.sock" subsys=cilium-node-monitor
level=info msg="Beginning to read cilium agent events" subsys=cilium-node-monitor
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=CiliumNetworkPolicy/v2 subsys=k8s
level=info msg="Updating CRD (CustomResourceDefinition)..." name=v2.CiliumEndpoint subsys=k8s
level=info msg="CRD (CustomResourceDefinition) is installed and up-to-date" name=v2.CiliumEndpoint subsys=k8s
```

**Comment by joestringer** [comment]
Hi @The-Loeki , I see that those logs are running with v1.5.0-rc4, so with this PR it should no longer occur. Do you observe this or similar behaviour on master?

One guess I have would be that Cilium launches other programs (such as the node monitor), and *maybe* when those other programs launch, they invoke the same init() function and trigger this, then output the warning, which Cilium picks up and outputs to the Cilium log.

**Comment by The-Loeki** [comment]
ah that makes sense... I'll await the next RC with your PR in & see if it still happens then :) tnx
