### PR TITLE
Misc Fixes for Tunnel Map Testing

### LINKED ISSUE #31232: CI: Test/TunnelMapTestSuite/TestClusterAwareAddressing
## CI failure

```
--- FAIL: Test (0.00s)
    --- FAIL: Test/TunnelMapTestSuite (0.00s)
        --- FAIL: Test/TunnelMapTestSuite/TestClusterAwareAddressing (0.00s)
            tunnel_test.go:37: 
                ... value *fmt.wrapError = &fmt.wrapError{msg:"creating map: pin map to /sys/fs/bpf/tc/globals/test_cilium_tunnel_map: file exists", err:(*fmt.wrapError)(0xc0000563c0)} ("creating map: pin map to /sys/fs/bpf/tc/globals/test_cilium_tunnel_map: file exists")
```

Run URL: https://github.com/cilium/cilium/actions/runs/8193113970/job/22406307012
PR: https://github.com/cilium/cilium/pull/31015
Zip: Sysdump n/a.

### PR DESCRIPTION
**Pull request by learnitall**
Please ensure your pull request adheres to the following guidelines:

- [X] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [X] All code is covered by unit and/or runtime tests where feasible.
- [X] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [X] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [X] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [X] Provide a title or release-note blurb suitable for the release notes.
- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [X] Thanks for contributing!

This PR introduces a couple of potential bug fixes for tests that consume the `TunnelMap`. There were a couple of potential issues that may cause flaky tests or a lack of observability into failing tests. Please see individual commits for details.

This may potentially fix #31232 

```release-note
Improve potential issues with tests that use the tunnel eBPF map to help prevent flakes.
```

### CODE REVIEW

**Comment by tommyp1ckles** [comment]
@learnitall Was investigating this one, was going to put up this [fix](https://github.com/tommyp1ckles/cilium/blob/ac53bd7af1235b5abcae20eb93e7f7707075b706/pkg/maps/tunnel/tunnel.go), but I noticed you had a similar one as a draft, where you planning on opening that one up for review?

File: pkg/maps/tunnel/tunnel.go [hunk 1]
```diff
@@ -42,7 +42,9 @@ func SetTunnelMap(m *Map) {
 
 func TunnelMap() *Map {
 	tunnelMapInit.Do(func() {
-		tunnelMap = NewTunnelMap(MapName)
+		if tunnelMap != nil {
```
Comment (aspsk) [inline pkg/maps/tunnel/tunnel.go]: Shouldn't this be `if tunnelMap == nil`?

Comment (learnitall) [reply pkg/maps/tunnel/tunnel.go]: :facepalm: yes thank you.

**Review by aspsk — APPROVED** [review]

**Comment by julianwiedmann** [comment]
@learnitall just needs a rebase, and then we're good to go? :)

**Comment by learnitall** [comment]
Yep! This got stalled for a while because I kept running into flakes in CI. Just pushed a rebase :+1:
