### PR TITLE
k8s: delete IPs from ipcache for no running Pods

### LINKED ISSUE #12953: Conflicting endpoint when complete Job pod shares IP with an active pod
## Bug report
After launching our new EKS clusters with Cilium + AWS CNI in chaining mode we noticed that some packets are being dropped supposedly due to a "policy deny". Thing is the flows in question are actually allowed by the network policy, moreover other pods of the same (and other) workload affected by this policy are communicating just fine.

While troubleshooting we found that the destination/source pods sometimes didn't have an endpoint associated with `hubble observe` just showing the pod IP. So that's the immediate reason why traffic gets dropped. However, it wasn't clear why no endpoint is associated provided we can successfully get "allowed" conclusion when doing `cilium policy trace` using pod names as source and destination with all the labels correctly detected. Also sometimes we'd see correct behaviour on the same pods after restarting Cilium.

Sometimes Cilium restart wouldn't help though, so we started digging deeper. Accidentally we found that k8s `Job` and `CronJob` resources in the cluster leave a trail of "complete" pods (which is the default k8s behaviour to keep history of successful and failed jobs). Although the pods aren't live their specs still have IPs recorded from when they were running. Suspiciously, some of the IPs matched the IPs of the pods that had issues with erroneous network policy deny cases.

We manually deleted the inactive job pods, then restarted Cilium and all the flows started working again, endpoints correctly showing up too. Simply deleting the pods didn't work without restart. K8s removing them eventually also doesn't affect the colliding pod until Cilium is restarted.

This is quite problematic since we're running lots of jobs frequently and our workloads are fairly dynamic — getting created and restarted all the time. The more different jobs we run (and they scale along with the workloads related to this), the higher probability of having an IP collision. So this issue is basically a multiple times a day recurrence.

I believe Cilium should ignore IPs of inactive job pods when building the IP -> endpoint cache.

In the meantime, is there a workaround for this? Would running Cilium with ENI IPAM work better than chaining?

**General Information**

- Cilium version:
```
Client: 1.8.2 aa42034f0 2020-07-23T15:02:39-07:00 go version go1.14.6 linux/amd64
Daemon: 1.8.2 aa42034f0 2020-07-23T15:02:39-07:00 go version go1.14.6 linux/amd64
```
- Kernel version: `4.14.186-146.268.amzn2.x86_64`
- Orchestration system version in use:
```
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**How to reproduce the issue**

This is what I think is the way to reproduce, but obviously there's a stochastic element to which IPs get allocated:
1. Use AWS CNI chaining (not entirely sure this is required)
2. Launch 50 k8s jobs each running a couple of times until there are 100-200 inactive job pods
3. Launch 20-30 workload pods
4. Set up a `NetworkPolicy` to deny all traffic between the workloads
5. Set up a `NetworkPolicy` to allow some traffic between the workloads (e.g. a specific port ingress and egress)
6. Observe some pods having no communication issues, while others timeout (if an inactive job pod IP got allocated to a workload pod)

### PR DESCRIPTION
**Pull request by aanm**
In Kubernetes, a Job creates a pod which will complete with either
the "Succeeded" or "Failed" PodPhase. Kubernetes will leave these
Pods around until the Job is deleted by the operator. As soon the pod
enters either one of the previously described PodPhases, Kubelet will
send a CNI delete event to Cilium agent which will then release the
allocated IP addresses of that pod, making the IP address available
again.

If not disabled, Cilium will create a Cilium Endpoint for each Pod in
the cluster that has its network managed by Cilium.

Cilium agent populates the ipcache with the information retrieved from
Pods and Cilium Endpoints events, in case of duplicated information,
ipcache will be stored with the state from Cilium Endpoints.

In a unlikely case of Cilium agent not running and the Pod enters the
"Succeeded" state, it will mean the Cilium agent will not be available
to delete the Cilium Endpoint created for that Pod.

To complement this fix, Cilium agents will also prune Cilium Endpoints
of not running pods on start up.

```release-note
Delete dangling Cilium Endpoints for completed Kubernetes Jobs.
```

Fixes https://github.com/cilium/cilium/issues/12953

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

File: operator/k8s_cep_gc.go [hunk 1]
```diff
@@ -37,24 +40,37 @@ import (
...
+		gcInterval     time.Duration
+		stopCh         = make(chan struct{})
 	)
 
-	log.Info("Starting to garbage collect stale CiliumEndpoint custom resources...")
-
 	ciliumClient := ciliumK8sClient.CiliumV2()
 
+	if once {
+		log.Info("Running once the garbage collector to clean up leftover CiliumEndpoint custom resources...")
```
Comment (christarazi) [inline operator/k8s_cep_gc.go]:
```suggestion
		log.Info("Running the garbage collector only once to clean up leftover CiliumEndpoint custom resources...")
```

Comment (nathanjsweet) [inline operator/k8s_cep_gc.go]:
```suggestion
		log.Info("Running the garbage collector once to clean up leftover CiliumEndpoint custom resources...")
```

**Review by nathanjsweet — APPROVED** [review]
Small nit. Otherwise, LGTM.

File: operator/k8s_cep_gc.go [hunk 2]
```diff
@@ -64,14 +80,37 @@ func enableCiliumEndpointSyncGC() {
...
 					}
-
 					cepFullName := cep.Namespace + "/" + cep.Name
-					_, exists, err := watchers.PodStore.GetByKey(cepFullName)
-					if err != nil {
-						scopedLog.WithError(err).Warn("Unable to get pod from store")
-						continue
+
+					delCEP := once
+					if !once {
```
Comment (christarazi) [inline operator/k8s_cep_gc.go]: Instead of having different branches about whether we should run this logic once, which complicates the flow, we can use `sync.Once` to ensure that it only runs once. This keeps the deleting logic the same, without having to complicate it to account for running once / running always. Have you considered this?

**Review by christarazi — CHANGES_REQUESTED** [review]
Nice find! A minor nit and a question regarding potentially simplifying logic by using `sync.Once`.

File: operator/k8s_cep_gc.go (hunk 2 above)
Comment (aanm) [reply operator/k8s_cep_gc.go]: The meaning of the variable `once` is different from the meaning of the `sync.Once`. the intention is to run the for loop for all endpoints one time, or not, depending the the GC is not supposed to be running or it is suppose to be running

File: operator/k8s_cep_gc.go [hunk 3]
```diff
@@ -64,14 +80,37 @@ func enableCiliumEndpointSyncGC() {
...
+						// If we are running this function once it means that we
+						// will delete all CEPs in the cluster regardless of the pod
+						// state.
```
Comment (jrajahalme) [inline operator/k8s_cep_gc.go]: This comment seems a bit misplaced, if applies to what happens when this code branch is NOT executed.

**Review by jrajahalme — APPROVED** [review]
Minor nit only.

File: operator/k8s_cep_gc.go (hunk 3 above)
Comment (aanm) [reply operator/k8s_cep_gc.go]: good point, I'll re-write the comment.

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
retest-gke

File: operator/k8s_cep_gc.go [hunk 4]
```diff
@@ -64,14 +80,37 @@ func enableCiliumEndpointSyncGC() {
...
+								continue
+							}
+							// In Kubernetes Jobs, Pods can be left in Kubernetes until the Job
+							// is deleted. If the Job is never deleted, Cilium will never receive a Pod
+							// delete event, causing the IP to be left in the ipcache.
+							// For this reason we should delete the ipcache entries whenever the pod
+							// status is either PodFailed or PodSucceeded as it means the IP address
+							// is no longer in use.
+							delCEP = !k8sUtils.IsPodRunning(pod.Status)
+						}
```
Comment (pchaigno) [inline operator/k8s_cep_gc.go:114]: Similar remark to Chris, I find the code is becoming a bit more complicated with the different branches. Maybe it would be worth moving the computation of `delCEP` to its own function? That's orthogonal to the addition of branches but may help reading through.

**Review by pchaigno — APPROVED** [review]

**Review by christarazi — COMMENTED** [review]
It would be nice to simplify the flow / make it more digestible.

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by tklauser — APPROVED** [review]

File: operator/k8s_cep_gc.go [hunk 5]
```diff
@@ -64,34 +81,61 @@ func enableCiliumEndpointSyncGC() {
...
-							cep.Name,
-							meta_v1.DeleteOptions{PropagationPolicy: &PropagationPolicy})
+					scopedLog = scopedLog.WithFields(logrus.Fields{
+						logfields.K8sPodName: cepFullName,
+					})
+
+					if !once {
+						// If we are running this function "once" it means that we
+						// will delete all CEPs in the cluster regardless of the pod
+						// state therefore we won't even watch for the pod store.
```
Comment (christarazi) [inline operator/k8s_cep_gc.go]: This comment doesn't belong inside the "if" because it mentions the case where once is true. It can be confusing to read.

```suggestion
					// If we are running this function "once" it means that we
					// will delete all CEPs in the cluster regardless of the pod
					// state therefore we won't even watch for the pod store.
					if !once {
```

File: operator/k8s_cep_gc.go [hunk 6]
```diff
@@ -64,34 +81,61 @@ func enableCiliumEndpointSyncGC() {
...
+							// is no longer in use.
+							if k8sUtils.IsPodRunning(pod.Status) {
+								continue
+							}
 						}
+					}
+					// FIXME: this is fragile as we might have received the
+					// CEP notification first but not the pod notification
+					// so we need to have a similar mechanism that we have
+					// for the keep alive of security identities.
```
Comment (christarazi) [inline operator/k8s_cep_gc.go:119]: Can you clarify the "mechanism for keep alive of security identities"

**Review by christarazi — APPROVED** [review]
Nice to have nits below.

File: daemon/cmd/state.go [hunk 7]
```diff
@@ -140,7 +141,7 @@ func (d *Daemon) fetchOldEndpoints(dir string) (*endpointRestoreState, error) {
 //
 // If clean is true, endpoints which cannot be associated with a container
 // workloads are deleted.
-func (d *Daemon) restoreOldEndpoints(state *endpointRestoreState, clean bool) error {
+func (d *Daemon) restoreOldEndpoints(epMgr endpointmanager.EndpointResourceSynchronizer, state *endpointRestoreState, clean bool) error {
```
Comment (joestringer) [inline daemon/cmd/state.go]: nit: Do we need to pass this in? Surely we can just do `d.endpointManager` since the caller initializes `d` as one of the first things it does?

File: pkg/k8s/watchers/endpointsynchronizer.go [hunk 8]
```diff
@@ -280,5 +286,70 @@ func (epSync *EndpointSynchronizer) RunK8sCiliumEndpointSync(e *endpoint.Endpoin
...
+	// arbitrary errors. Disable the controller for these endpoints.
+	if isHealthEP := e.HasLabels(pkgLabels.LabelHealth); isHealthEP {
+		scopedLog.Debug("Not starting unnecessary CEP controller for cilium-health endpoint")
+		return
+	}
+
+	// NOTE: The controller functions do NOT hold the endpoint locks
+	e.UpdateController(controllerName,
+		controller.ControllerParams{
+			StopFunc: func(ctx context.Context) error {
```
Comment (joestringer) [inline pkg/k8s/watchers/endpointsynchronizer.go:322]: Same feedback from the other version of the PR, seems like this function is the same as line 289 and could be declared once & shared.

**Review by joestringer — COMMENTED** [review]
I looked at everything except `operator/k8s_cep_gc.go`, LMK if you'd like another look at that.

**Review by joestringer — APPROVED** [review]

File: daemon/cmd/state.go (hunk 7 above)
Comment (aanm) [reply daemon/cmd/state.go]: for some reason I thought `restoreOldEndpoint` didn't have a receiver :)

File: operator/k8s_cep_gc.go (hunk 6 above)
Comment (aanm) [reply operator/k8s_cep_gc.go:119]: @christarazi basically to keep a map and check if the CEP really needs to be deleted in the next call of the controller.

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
hit https://github.com/cilium/cilium/issues/13224
