### PR TITLE
alibabacloud: fix race

### LINKED ISSUE #16170: CI: potential deadlock in `pkg/alibabacloud/eni`
Travis CI race pipelines currently fail on `master`:

https://travis-ci.com/github/cilium/cilium/jobs/505412429

```
POTENTIAL DEADLOCK: Inconsistent locking. saw this ordering in one goroutine:
happened before
../../lock/lock_debug.go:62 lock.(*internalRWMutex).Lock { i.RWMutex.Lock() } <<<<<
../../ipam/node.go:360 ipam.(*Node).recalculate { n.mutex.Lock() }
../../ipam/node.go:334 ipam.(*Node).UpdatedResource { n.recalculate() }
../../ipam/node_manager.go:266 ipam.(*NodeManager).Update.func1 { nodeSynced = node.UpdatedResource(resource) }
../../ipam/node_manager.go:324 ipam.(*NodeManager).Update { return }
node_test.go:190 eni.newCiliumNode { cn := &v2.CiliumNode{ }
/usr/local/go/src/reflect/value.go:476 reflect.Value.call { call(frametype, fn, args, uint32(frametype.size), uint32(retOffset)) }
/usr/local/go/src/reflect/value.go:337 reflect.Value.Call { return v.call("Call", in) }
../../../vendor/gopkg.in/check.v1/check.go:775 check%2ev1.(*suiteRunner).forkTest.func1 { c.method.Call([]reflect.Value{reflect.ValueOf(c)}) }
../../../vendor/gopkg.in/check.v1/check.go:669 check%2ev1.(*suiteRunner).forkCall.func1 { dispatcher(c) }

happened after
../../lock/lock_debug.go:78 lock.(*internalRWMutex).RLock { i.RWMutex.RLock() } <<<<<
node.go:336 eni.(*Node).GetMaximumAllocatableIPv4 { n.mutex.RLock() }
../../ipam/node.go:219 ipam.(*Node).getMaxAllocate { instanceMax := n.ops.GetMaximumAllocatableIPv4() }
../../ipam/node.go:374 ipam.(*Node).recalculate { n.stats.NeededIPs = calculateNeededIPs(n.stats.AvailableIPs, n.stats.UsedIPs, n.getPreAllocate(), n.getMinAllocate(), n.getMaxAllocate()) }
../../ipam/node.go:334 ipam.(*Node).UpdatedResource { n.recalculate() }
../../ipam/node_manager.go:266 ipam.(*NodeManager).Update.func1 { nodeSynced = node.UpdatedResource(resource) }
../../ipam/node_manager.go:324 ipam.(*NodeManager).Update { return }
node_test.go:190 eni.newCiliumNode { cn := &v2.CiliumNode{ }
/usr/local/go/src/reflect/value.go:476 reflect.Value.call { call(frametype, fn, args, uint32(frametype.size), uint32(retOffset)) }
/usr/local/go/src/reflect/value.go:337 reflect.Value.Call { return v.call("Call", in) }
../../../vendor/gopkg.in/check.v1/check.go:775 check%2ev1.(*suiteRunner).forkTest.func1 { c.method.Call([]reflect.Value{reflect.ValueOf(c)}) }
../../../vendor/gopkg.in/check.v1/check.go:669 check%2ev1.(*suiteRunner).forkCall.func1 { dispatcher(c) }

in another goroutine: happened before
../../lock/lock_debug.go:62 lock.(*internalRWMutex).Lock { i.RWMutex.Lock() } <<<<<
node.go:145 eni.(*Node).CreateInterface { n.mutex.Lock() }
../../ipam/node.go:441 ipam.(*Node).createInterface { toAllocate, errCondition, err := n.ops.CreateInterface(ctx, a, scopedLog) }
../../ipam/node.go:634 ipam.(*Node).maintainIPPool { return n.createInterface(ctx, a.allocation) }
../../ipam/node.go:678 ipam.(*Node).MaintainIPPool { err := n.maintainIPPool(ctx) }
../../../vendor/github.com/sirupsen/logrus/entry.go:99 logrus.(*Entry).WithError { return entry.WithField(ErrorKey, err) }
../../trigger/trigger.go:209 trigger.(*Trigger).waiter { t.params.TriggerFunc(reasons) }

happened after
../../../vendor/github.com/sasha-s/go-deadlock/deadlock.go:138 go-deadlock.(*RWMutex).RLock { lock(m.mu.RLock, m) } <<<<<
../../ipam/node.go:308 ipam.(*Node).InstanceID { n.mutex.RLock() }
node.go:161 eni.(*Node).CreateInterface { err = n.manager.api.AttachNetworkInterface(ctx, n.node.InstanceID(), eniID) }
../../ipam/node.go:441 ipam.(*Node).createInterface { toAllocate, errCondition, err := n.ops.CreateInterface(ctx, a, scopedLog) }
../../ipam/node.go:634 ipam.(*Node).maintainIPPool { return n.createInterface(ctx, a.allocation) }
../../ipam/node.go:678 ipam.(*Node).MaintainIPPool { err := n.maintainIPPool(ctx) }
../../../vendor/github.com/sirupsen/logrus/entry.go:99 logrus.(*Entry).WithError { return entry.WithField(ErrorKey, err) }
../../trigger/trigger.go:209 trigger.(*Trigger).waiter { t.params.TriggerFunc(reasons) }

Other goroutines holding locks:
goroutine 73 lock 0xc0003c20c8
../../lock/lock_debug.go:62 lock.(*internalRWMutex).Lock { i.RWMutex.Lock() } <<<<<
node.go:145 eni.(*Node).CreateInterface { n.mutex.Lock() }
../../ipam/node.go:441 ipam.(*Node).createInterface { toAllocate, errCondition, err := n.ops.CreateInterface(ctx, a, scopedLog) }
../../ipam/node.go:634 ipam.(*Node).maintainIPPool { return n.createInterface(ctx, a.allocation) }
../../ipam/node.go:678 ipam.(*Node).MaintainIPPool { err := n.maintainIPPool(ctx) }
../../../vendor/github.com/sirupsen/logrus/entry.go:99 logrus.(*Entry).WithError { return entry.WithField(ErrorKey, err) }
../../trigger/trigger.go:209 trigger.(*Trigger).waiter { t.params.TriggerFunc(reasons) }

goroutine 92 lock 0xc000380000
../../lock/lock_debug.go:62 lock.(*internalRWMutex).Lock { i.RWMutex.Lock() } <<<<<
../api/mock/mock.go:180 mock.(*API).CreateNetworkInterface { a.mutex.Lock() }
node.go:152 eni.(*Node).CreateInterface { eniID, eni, err := n.manager.api.CreateNetworkInterface(ctx, toAllocate-1, bestSubnet.ID, securityGroupIDs, }
../../ipam/node.go:441 ipam.(*Node).createInterface { toAllocate, errCondition, err := n.ops.CreateInterface(ctx, a, scopedLog) }
../../ipam/node.go:634 ipam.(*Node).maintainIPPool { return n.createInterface(ctx, a.allocation) }
../../ipam/node.go:678 ipam.(*Node).MaintainIPPool { err := n.maintainIPPool(ctx) }
../../../vendor/github.com/sirupsen/logrus/entry.go:99 logrus.(*Entry).WithError { return entry.WithField(ErrorKey, err) }
../../trigger/trigger.go:209 trigger.(*Trigger).waiter { t.params.TriggerFunc(reasons) }

goroutine 92 lock 0xc0003c2488
../../lock/lock_debug.go:62 lock.(*internalRWMutex).Lock { i.RWMutex.Lock() } <<<<<
node.go:145 eni.(*Node).CreateInterface { n.mutex.Lock() }
../../ipam/node.go:441 ipam.(*Node).createInterface { toAllocate, errCondition, err := n.ops.CreateInterface(ctx, a, scopedLog) }
../../ipam/node.go:634 ipam.(*Node).maintainIPPool { return n.createInterface(ctx, a.allocation) }
../../ipam/node.go:678 ipam.(*Node).MaintainIPPool { err := n.maintainIPPool(ctx) }
../../../vendor/github.com/sirupsen/logrus/entry.go:99 logrus.(*Entry).WithError { return entry.WithField(ErrorKey, err) }
../../trigger/trigger.go:209 trigger.(*Trigger).waiter { t.params.TriggerFunc(reasons) }



FAIL	github.com/cilium/cilium/pkg/alibabacloud/eni	0.175s
```

Can be reproduced locally with `go test -race -tags lockdebug -test.v ./pkg/alibabacloud/eni`

/cc @l1b0k

### PR DESCRIPTION
**Pull request by l1b0k**
Fixes: https://github.com/cilium/cilium/issues/16170

### CODE REVIEW

File: pkg/alibabacloud/eni/node.go [hunk 1]
```diff
@@ -333,9 +333,6 @@ func (n *Node) ReleaseIPs(ctx context.Context, r *ipam.ReleaseAction) error {
 // GetMaximumAllocatableIPv4 returns the maximum amount of IPv4 addresses
 // that can be allocated to the instance
 func (n *Node) GetMaximumAllocatableIPv4() int {
-	n.mutex.RLock()
-	defer n.mutex.RUnlock()
-
```
Comment (tklauser) [inline pkg/alibabacloud/eni/node.go]: I'm not sure this is the correct fix. We call `n.getLimitsLocked` below which assumes `n.mutex` to be read-locked:

https://github.com/cilium/cilium/blob/e95a201ffa54d05d313d048d9b61f043a397c566/pkg/alibabacloud/eni/node.go#L372-L373

Can you elaborate a bit why read-locking is not needed in this case? It looks like the respective code in `pkg/aws/eni` (which this code seems to be derived from) also read-locks in `(*Node).GetMaximumAllocatableIPv4`. If taking the lock is not necessary, we should rename and adjust the godoc for `n *Node).getLimitsLocked`.

**Review by tklauser — CHANGES_REQUESTED** [review]

File: pkg/alibabacloud/eni/node.go (hunk 1 above)
Comment (l1b0k) [reply pkg/alibabacloud/eni/node.go]: yes that is not correct . I have updated.

**Comment by tklauser** [comment]
@l1b0k could you please rebase your branch and force push again? It looks like Travis CI wasn't triggered by the latest push. Thanks!

**Comment by tklauser** [comment]
@l1b0k It looks like now the old change (deleting the read-lock) is back rather than the fix you pushed before in https://github.com/cilium/cilium/commit/d0f0be8b6890147038c3f4cafbfe0610e51835d9

**Review by tklauser — APPROVED** [review]

**Comment by tklauser** [comment]
test-me-please

**Comment by tklauser** [comment]
test-runtime

**Comment by tklauser** [comment]
All remaining CI failures are known flakes:

* k8s-1.19-kernel-5.4 failure is #14959 https://jenkins.cilium.io/job/Cilium-PR-K8s-1.19-kernel-5.4/136/
* k8s-1.20-kernel-4.19 failure is #16154 https://jenkins.cilium.io/job/Cilium-PR-K8s-1.20-kernel-4.19/458/
* k8s-1.21-kernel-4.9 failure is #15103 https://jenkins.cilium.io/job/Cilium-PR-K8s-1.21-kernel-4.9/485/

The code changed by this PR doesn't affect these, so no need to re-trigger.

Travis CI still didn't trigger despite rebasing the PR and trying to close/reopen. I've ran these tests locally and verified the race is indeed solved. Marking as ready to merge.
