### PR TITLE
datapath: Fix TestNodeChurnXFRMLeaks

### LINKED ISSUE #27268: CI: linuxPrivilegedIPv4AndIPv6TestSuite/TestNodeChurnXFRMLeaks
## CI failure

Hit on https://github.com/cilium/cilium/pull/27242: https://github.com/cilium/cilium/actions/runs/5752260375/job/15592941475

```
--- FAIL: Test (227.53s)
    --- FAIL: Test/linuxPrivilegedIPv4AndIPv6TestSuite (3.51s)
        --- FAIL: Test/linuxPrivilegedIPv4AndIPv6TestSuite/TestNodeChurnXFRMLeaks (1.06s)
            node_linux_test.go:809: 
                ... value *errors.joinError = &errors.joinError{errs:[]error{(*errors.joinError)(0xc0010e0180)}} ("failed to enable ipsec with out IPv6 using local IP ::/0, rem 2001:aaaa::/64, spi 0: unable to replace remote state: file exists")
```

### PR DESCRIPTION
**Pull request by brb**
This commit fixes the following issues:

* Missed enablement of the churn tests in the non-subnet mode.
* The subnet mode being broken when v4 and v6 enabled \[1\].

\[1\]: https://github.com/cilium/cilium/issues/27280

Fixes: 9207b7898 ("datapath: Cover subnet encryption in XFRM leak test")

Fix: #27268

### CODE REVIEW

File: pkg/datapath/linux/node_linux_test.go [hunk 1]
```diff
@@ -772,6 +772,7 @@ func (s *linuxPrivilegedBaseTestSuite) TestNodeChurnXFRMLeaks(c *check.C) {
 	option.Config.EncryptInterface = []string{externalNodeDevice}
 
 	// Cover the XFRM configuration for subnet encryption: IPAM modes AKS and EKS.
+	config.EnableIPv6 = false // https://github.com/cilium/cilium/issues/27280
```
Comment (pchaigno) [inline pkg/datapath/linux/node_linux_test.go]: :scream: 

I believe instead you want:
```diff
- func (s *linuxPrivilegedBaseTestSuite) TestNodeChurnXFRMLeaks(c *check.C) {
+ // Subnet encryption fails with dual stack: https://github.com/cilium/cilium/issues/27280.
+ func (s *linuxPrivilegedIPv4OnlyTestSuite) TestNodeChurnXFRMLeaks(c *check.C) {
```

**Review by pchaigno — APPROVED** [review]
