### PR TITLE
pkg/k8s: fix hostport service created on incorrect node

### LINKED ISSUE #34342: HostPort type service is created on the wrong node when cilium-agent enable disable-endpoint-crd config
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

higher than v1.16.0 and lower than v1.17.0

### What happened?

When cilium-agent enable `disable-endpoint-crd` config，it will watch all pods in the cluster until it connects to the kvstore. pod with a hostPort container may be watched, causing the hostport type service to be created on the wrong node.

We are currently using cilium version 1.12.19, the latest cilium version seems to follow the same logic.

### How can we reproduce the issue?

1. cilium-agent enable `disable-endpoint-crd` config
2. create a PodA with a hostPort container on NodeA
3. restart cilium-agent on NodeB, and execute `cilium service list |grep PodA_IP ` commad

### Cilium Version

1.12.19

### Kernel Version

5.15.80

### Kubernetes Version

1.28.3

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by haozhangami**
When cilium-agent enable `disable-endpoint-crd` configuration, it will watch all pods in the k8s cluster until it connects to the kvstore. the pod on another node that contain a hostport container may be watched, causing the hostport type services to be created on incorrect node.

This patch checks that the pod nodeName is consistent with the local node name and skips generating the hostport services if they are inconsistent.

Fixes: #34342

```release-note
Fix issue where a hostport service would be created on an incorrect node when cilium-agent is configured with disable-endpoint-crd
```

### CODE REVIEW

File: pkg/k8s/watchers/pod.go [hunk 1]
```diff
@@ -696,6 +696,12 @@ func (k *K8sPodWatcher) genServiceMappings(pod *slim_corev1.Pod, podIPs []string
 			var nodeAddrAll []netip.Addr
 			loopbackHostport := false
 
+			hostIP := net.ParseIP(pod.Status.HostIP)
+			if hostIP == nil {
+				logger.Warningf("Skip creating HostPort service, no/invalid pod HostIP.")
```
Comment (joestringer) [inline pkg/k8s/watchers/pod.go]: Minor nits here:

```suggestion
				logger.WithFields(logfields.IPAddr, pod.Status.HostIP.Warning("Skip creating HostPort service, no/invalid pod HostIP.")
```

File: pkg/k8s/watchers/pod.go [hunk 2]
```diff
@@ -721,6 +727,10 @@ func (k *K8sPodWatcher) genServiceMappings(pod *slim_corev1.Pod, podIPs []string
 				nodeAddrAll = append(nodeAddrAll, netip.IPv4Unspecified())
 				nodeAddrAll = append(nodeAddrAll, netip.IPv6Unspecified())
 			}
+			if !loopbackHostport && ip.ListContainsAddr(nodeAddrAll, ip.MustAddrFromIP(hostIP)) {
+				logger.Warningf("Skip creating HostPort service, node IPs do not contain pod HostIP.")
```
Comment (joestringer) [inline pkg/k8s/watchers/pod.go]: Similar feedback here - Although the existing code uses `Warningf`, we should generally avoid formatting variations of the loggers, especially in cases like this where there is no formatting directives in the text. `Warning` is enough. However, given that this log message is issuing a warning to the user, it should contain enough detail for a user to cross-reference this warning with other state in the cluster. For instance, which node is this message referring to? That information can be included using `WithFields()` similar to my suggestion above.

Comment (joestringer) [reply pkg/k8s/watchers/pod.go]: Actually for that matter, is the warning actionable? We generally aim to avoid warnings in the Cilium logs if Cilium is working normally. Even info level messages should ideally not be printing on a regular basis, but be relatively rare. If this is warning is likely to show up on all nodes in the cluster because the host IP is not in the node list, then maybe this should be a `Debug` message instead.

**Review by joestringer — COMMENTED** [review]
Thanks for the fix! I posted a few inline comments about the logging output to improve UX.

File: pkg/k8s/watchers/pod.go (hunk 1 above)
Comment (squeed) [reply pkg/k8s/watchers/pod.go]: We parse `pod.HostIP` above; is there a difference between `pod.HostIP` and `pod.Status.HostIP`?

File: pkg/k8s/watchers/pod.go [hunk 3]
```diff
@@ -721,6 +727,10 @@ func (k *K8sPodWatcher) genServiceMappings(pod *slim_corev1.Pod, podIPs []string
 				nodeAddrAll = append(nodeAddrAll, netip.IPv4Unspecified())
 				nodeAddrAll = append(nodeAddrAll, netip.IPv6Unspecified())
 			}
+			if !loopbackHostport && ip.ListContainsAddr(nodeAddrAll, ip.MustAddrFromIP(hostIP)) {
```
Comment (squeed) [inline pkg/k8s/watchers/pod.go]: Is there a reason you are checking HostIP and not NodeName?

Comment (haozhangami) [reply pkg/k8s/watchers/pod.go]: It is more reasonable to use node name.

File: pkg/k8s/watchers/pod.go (hunk 1 above)
Comment (haozhangami) [reply pkg/k8s/watchers/pod.go]: I  have used debug messages with logfields instead of warning messages. `pod.Status.HostIP` is already included in the logfields.

File: pkg/k8s/watchers/pod.go (hunk 2 above)
Comment (haozhangami) [reply pkg/k8s/watchers/pod.go]: Thank you for your review, I have modified it.

**Review by squeed — CHANGES_REQUESTED** [review]
Now that I've taken a look at the broader context, I realized the needed fix is a bit different.

The problem is that `updatePodHostData()` assumes it will only be called for local pods. It does a lot of bookkeeping, including updating the ipcache.

The function needs to be refactored to do the ipcache update first, *then* return if the pod is not local to the node. Otherwise it should proceed.

Make sense? Sorry for the review "flapping".

**Comment by haozhangami** [comment]
Hi @squeed, thank you for your review.

When cilium-agent enable `disable-endpoint-crd` configuration, it watches the pod events of all nodes. The main purpose of this logic is to update ipcache. Checking whether the pod is local to the node in the `updatePodHostData` function can avoid the for loop in the `genServiceMappings` function. 

Is my understanding correct? I have modified the code and look forward to your reply.

**Review by squeed — APPROVED** [review]
Looks good, thanks!

**Comment by ldelossa** [comment]
@haozhangami looks like consistent failures in: https://github.com/cilium/cilium/actions/runs/10452314004/job/29063749091

**Comment by haozhangami** [comment]
> @haozhangami looks like consistent failures in: https://github.com/cilium/cilium/actions/runs/10452314004/job/29063749091

Hi @ldelossa It seems that the  gateway api conformance test is unstable. I notice that other PRs have similar problems.

**Comment by ldelossa** [comment]
@haozhangami can you rebase this PR against MAIN. I've seen a few error conditions clear up on other PRs so far. We may have some fixes hiding. I'll rerun tests after you do this.

**Comment by haozhangami** [comment]
Hi @ldelossa 

Conformance Gateway API failure is due to a known flake #33279 

https://github.com/cilium/cilium/actions/runs/10542055187

I have rebased, can you rerun tests again? Other failed tests were normal in the previous tests, need to be retried.

**Comment by haozhangami** [comment]
😓 Request to upload report artifact timeout, can you rerun tests again if it is necessary.

https://github.com/cilium/cilium/actions/runs/10553383986/job/29233603467
