### PR TITLE
datapath/linux: select devices only if required

### LINKED ISSUE #27276: IPsec downgrade causes XfrmInNoStates
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Job: https://github.com/cilium/cilium/actions/runs/5752376942

Xfrm errors occurred during connectivity conn-disrupt-test after downgrade:

```
[=] Test [no-ipsec-xfrm-errors]

  [-] Scenario [no-ipsec-xfrm-errors/no-ipsec-xfrm-error]
  🟥 Node  xfrm errors were changed (previous errors: , current errors: inbound_no_state:2)
```

This can be reproduced easily on local:

```shell
./contrib/scripts/kind.sh "" 3 "" "" "iptables" ipv4

# create spi
kubectl create -n kube-system secret generic cilium-ipsec-keys       --from-literal=keys="3 rfc4106(gcm(aes)) $(echo $(dd if=/dev/urandom count=20 bs=1 2> /dev/null | xxd -p -c 64)) 128"

# install
CILIUM_CLI_MODE=helm cilium install     --chart-directory=./install/kubernetes/cilium/   --helm-set=image.repository=quay.io/cilium/cilium-ci   --helm-set=image.useDigest=false   --helm-set=image.tag=v1.14   --helm-set=operator.image.repository=quay.io/cilium/operator   --helm-set=operator.image.suffix=-ci   --helm-set=operator.image.tag=v1.14   --helm-set=operator.image.useDigest=false   --helm-set=hubble.relay.image.repository=quay.io/cilium/hubble-relay-ci   --helm-set=hubble.relay.image.tag=v1.14     --wait   --helm-set=debug.enabled=true   --helm-set=cni.uninstall=false   --helm-set=cluster.name=default   --helm-set=hubble.eventBufferCapacity=65535   --helm-set=bpf.monitorAggregation=none   --nodes-without-cilium=kind-worker3   --helm-set=bpfClockProbe=false   --helm-set-string=kubeProxyReplacement=disabled --helm-set-string=routingMode=native --helm-set-string=autoDirectNodeRoutes=true --helm-set-string=ipv4NativeRoutingCIDR=10.244.0.0/16 --helm-set-string=tunnel=disabled --helm-set-string=ipv6NativeRoutingCIDR=fd00:10:244::/56      --helm-set=encryption.enabled=true --helm-set=encryption.type=ipsec --helm-set=encryption.nodeEncryption=false

# upgrade
CILIUM_CLI_MODE=helm cilium upgrade     --chart-directory=./install/kubernetes/cilium   --helm-set=image.repository=quay.io/cilium/cilium-ci   --helm-set=image.useDigest=false   --helm-set=image.tag=7f55822a724be9e5bd33c87203fc5bd1758efa68   --helm-set=operator.image.repository=quay.io/cilium/operator   --helm-set=operator.image.suffix=-ci   --helm-set=operator.image.tag=7f55822a724be9e5bd33c87203fc5bd1758efa68   --helm-set=operator.image.useDigest=false   --helm-set=hubble.relay.image.repository=quay.io/cilium/hubble-relay-ci   --helm-set=hubble.relay.image.tag=7f55822a724be9e5bd33c87203fc5bd1758efa68     --wait   --helm-set=debug.enabled=true   --helm-set=cni.uninstall=false   --helm-set=cluster.name=default   --helm-set=hubble.eventBufferCapacity=65535   --helm-set=bpf.monitorAggregation=none   --nodes-without-cilium=kind-worker3   --helm-set=bpfClockProbe=false   --helm-set-string=kubeProxyReplacement=disabled --helm-set-string=routingMode=native --helm-set-string=autoDirectNodeRoutes=true --helm-set-string=ipv4NativeRoutingCIDR=10.244.0.0/16 --helm-set-string=tunnel=disabled --helm-set-string=ipv6NativeRoutingCIDR=fd00:10:244::/56      --helm-set=encryption.enabled=true --helm-set=encryption.type=ipsec --helm-set=encryption.nodeEncryption=false

# prepare for conn-disrupt-test
cilium connectivity test --include-conn-disrupt-test --conn-disrupt-test-setup

# downgrade
CILIUM_CLI_MODE=helm cilium upgrade     --chart-directory=./install/kubernetes/cilium/   --helm-set=image.repository=quay.io/cilium/cilium-ci   --helm-set=image.useDigest=false   --helm-set=image.tag=v1.14   --helm-set=operator.image.repository=quay.io/cilium/operator   --helm-set=operator.image.suffix=-ci   --helm-set=operator.image.tag=v1.14   --helm-set=operator.image.useDigest=false   --helm-set=hubble.relay.image.repository=quay.io/cilium/hubble-relay-ci   --helm-set=hubble.relay.image.tag=v1.14     --wait   --helm-set=debug.enabled=true   --helm-set=cni.uninstall=false   --helm-set=cluster.name=default   --helm-set=hubble.eventBufferCapacity=65535   --helm-set=bpf.monitorAggregation=none   --nodes-without-cilium=kind-worker3   --helm-set=bpfClockProbe=false   --helm-set-string=kubeProxyReplacement=disabled --helm-set-string=routingMode=native --helm-set-string=autoDirectNodeRoutes=true --helm-set-string=ipv4NativeRoutingCIDR=10.244.0.0/16 --helm-set-string=tunnel=disabled --helm-set-string=ipv6NativeRoutingCIDR=fd00:10:244::/56      --helm-set=encryption.enabled=true --helm-set=encryption.type=ipsec --helm-set=encryption.nodeEncryption=false

# conn-disrupt-test is likely to fail on xfrm errors
cilium connectivity test --include-conn-disrupt-test 
```

### Cilium Version

cilium-cli: v0.15.0-93-gf7c0b606 compiled with go1.20 on linux/amd64
cilium image (default): v1.14.0
cilium image (stable): v1.14.0
cilium image (running): 1.15.0-dev

### Kernel Version

Linux gray-Latitude-5530 5.19.0-50-generic #50-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 18:24:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-15T00:36:28Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jschwinger233**
In the prevous commit (https://github.com/cilium/cilium/commit/03ad61b6b356cc47996dabfd7832053223b36ef4), "cil_from_netdev" is unconditionally attached to eth0. By design, "cil_from_netdev" should be used for eth0 only if host firewall / nodeport / wireguard is enabled, and this commit makes sure those conditions are checked.

Fixes: https://github.com/cilium/cilium/issues/27276
Fixes: https://github.com/cilium/cilium/commit/03ad61b6b356cc47996dabfd7832053223b36ef4

```release-note
Fix connection disruption for IPsec during downgrade to v1.14 by attaching correct bpf program to devices.
```

Suggested-by: Jussi Maki <jussi@isovalent.com>
Signed-off-by: Zhichuan Liang <gray.liang@isovalent.com>

### CODE REVIEW

**Comment by jschwinger233** [comment]
ci-ipsec-upgrade recovered  but other issues introduced. :crying_cat_face:

File: pkg/datapath/linux/devices_controller.go [hunk 1]
```diff
@@ -533,7 +534,7 @@ func (dc *devicesController) isSelectedDevice(d *tables.Device, routes statedb.T
 
 	log.Debug("Selected this device")
 
-	return true
+	return option.Config.AreDevicesRequired()
```
Comment (jschwinger233) [inline pkg/datapath/linux/devices_controller.go]: CI failed because `isSelectedDevice()` should have returned `true` for eth0 when KPR enabled (which auto-enables NodePort), but that didn't happen.

https://github.com/cilium/cilium/blob/f439a14d8e007705edc1fc861bfa7d362c90ada3/daemon/cmd/kube_proxy_replacement.go#L74-L83

My guess is execution order: cilium-agent calls `isSelectedDevice()` ahead of `initKubeProxyReplacementOptions()`, so by the time executing `isSelectedDevice()`, option.EnableNodePort gets no chance to be turned on by `initKubeProxyReplacementOptions()`.

@joamaki I'd appreciate it if I can get some idea from you, once you are available someday this week.

Comment (joamaki) [reply pkg/datapath/linux/devices_controller.go]: My plan is to over time remove `option.Config.Devices` and `AreDevicesRequired` completely and switch all modules to use the devices table directly. Then we would not have this central `AreDevicesRequired` check, but rather each feature (e.g. loader etc.) would itself figure out what to do with the information. Given that, I would put this `AreDevicesRequired` check into the "backwards compatible wrapper" (that wasn't): https://github.com/cilium/cilium/blob/main/pkg/datapath/linux/devices.go#L37. E.g. return early:
```
  if len(userDevices) == 0 && !option.Config.AreDevicesRequired() {
    return nil, nil
  }
```

We check for `len(userDevices) == 0` to continue to expand wildcards and check that the devices existed.

Comment (brb) [reply pkg/datapath/linux/devices_controller.go]: > I would put this AreDevicesRequired check into the "backwards compatible wrapper"

I wonder how putting the check there solves the problem that the `deviceManager.Detect()` is called before the `initKubeProxyReplacement()`. The latter might set `option.Config.EnableNodePort` which influences the former.

Comment (joamaki) [reply pkg/datapath/linux/devices_controller.go]: Detect() should be called after it in daemon.go so the options should be good to go:                 
https://github.com/cilium/cilium/blob/7f54bb398f2ceb8a2f4c8905d350eae13abe0462/daemon/cmd/daemon.go#L908

**Review by YutaroHayakawa — APPROVED** [review]
