### PR TITLE
fix(ctmap/gc): fix race conditions and flakiness in TestGCEnableRatchet

### LINKED ISSUE #41960: CI: Integration Tests - TestGCEnableRatchet
## CI failure

Link: https://github.com/cilium/cilium/actions/runs/18154090911/job/51670131670

```
--- FAIL: TestGCEnableRatchet (10.01s)

2025/10/01 07:08:46 INFO Starting GC of connection tracking first=true
2025/10/01 07:08:46 INFO Conntrack garbage collector interval recalculated expectedPrevInterval=5m0s actualPrevInterval=0s newInterval=7m30s deleteRatio=1e-17 adjustedDeleteRatio=1e-17
2025/10/01 07:08:46 INFO initial gc of ct and nat maps completed duration=485.302µs
2025/10/01 07:08:46 INFO Starting GC of connection tracking first=false
2025/10/01 07:08:47 INFO Starting GC of connection tracking first=false
2025/10/01 07:08:47 INFO Starting GC of connection tracking first=false
2025/10/01 07:08:48 INFO Starting GC of connection tracking first=false
2025/10/01 07:08:48 INFO Starting GC of connection tracking first=false
2025/10/01 07:08:49 INFO Starting GC of connection tracking first=false
2025/10/01 07:08:49 INFO Starting GC of connection tracking first=false
2025/10/01 07:08:50 INFO Starting GC of connection tracking first=false
2025/10/01 07:08:50 INFO Starting GC of connection tracking first=false
2025/10/01 07:08:51 INFO Starting GC of connection tracking first=false
    gc_test.go:183: 
        	Error Trace:	/home/runner/work/cilium/cilium/pkg/maps/ctmap/gc/gc_test.go:184
        	            				/opt/hostedtoolcache/go/1.25.1/x64/src/runtime/asm_amd64.s:1693
        	Error:      	"0" is not greater than "1"
    gc_test.go:183: 
        	Error Trace:	/home/runner/work/cilium/cilium/pkg/maps/ctmap/gc/gc_test.go:183
        	Error:      	Condition never satisfied
        	Test:       	TestGCEnableRatchet
2025/10/01 07:08:51 INFO Starting GC of connection tracking first=false
2025/10/01 07:08:52 INFO Starting GC of connection tracking first=false
2025/10/01 07:08:52 INFO Starting GC of connection tracking first=false
2025/10/01 07:08:53 INFO Starting GC of connection tracking first=false
2025/10/01 07:08:53 INFO Starting GC of connection tracking first=false
2025/10/01 07:08:54 INFO Starting GC of connection tracking first=false
2025/10/01 07:08:54 INFO Starting GC of connection tracking first=false
2025/10/01 07:08:55 INFO Starting GC of connection tracking first=false
2025/10/01 07:08:55 INFO Starting GC of connection tracking first=false
    gc_test.go:183: 
        	Error Trace:	/home/runner/work/cilium/cilium/pkg/maps/ctmap/gc/gc_test.go:184
        	            				/opt/hostedtoolcache/go/1.25.1/x64/src/runtime/asm_amd64.s:1693
        	Error:      	"0" is not greater than "0"
    gc_test.go:183: 
        	Error Trace:	/home/runner/work/cilium/cilium/pkg/maps/ctmap/gc/gc_test.go:183
        	Error:      	Condition never satisfied
        	Test:       	TestGCEnableRatchet
    gc_test.go:188: 
        	Error Trace:	/home/runner/work/cilium/cilium/pkg/maps/ctmap/gc/gc_test.go:188
        	Error:      	"5.000636943s" is not greater than "5.000687927s"
        	Test:       	TestGCEnableRatchet
2025/10/01 07:08:56 INFO Starting GC of connection tracking first=false
2025/10/01 07:08:56 INFO Conntrack garbage collector interval recalculated expectedPrevInterval=7m30s actualPrevInterval=10.001703933s newInterval=45s deleteRatio=0.9 adjustedDeleteRatio=40.49310024702168
2025/10/01 07:08:56 INFO Starting GC of connection tracking first=false
```

Easily reproduces locally as well, especially with race detection enabled (which reports a bunch of races):

```
2025/10/01 09:44:52 INFO Starting GC of connection tracking first=true
==================
WARNING: DATA RACE
Write at 0x00c0006c8c08 by goroutine 32:
  github.com/cilium/cilium/pkg/maps/ctmap/gc.TestGCEnableRatchet.func2()
      /home/marco/Documents/isovalent/cilium/pkg/maps/ctmap/gc/gc_test.go:164 +0xc4
  github.com/cilium/cilium/pkg/maps/ctmap/gc.(*GC).enable.func1()
      /home/marco/Documents/isovalent/cilium/pkg/maps/ctmap/gc/gc.go:198 +0x56e

Previous read at 0x00c0006c8c08 by goroutine 31:
  github.com/cilium/cilium/pkg/maps/ctmap/gc.TestGCEnableRatchet()
      /home/marco/Documents/isovalent/cilium/pkg/maps/ctmap/gc/gc_test.go:169 +0x5c9
  testing.tRunner()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:1934 +0x21c
  testing.(*T).Run.gowrap1()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:1997 +0x44

Goroutine 32 (running) created at:
  github.com/cilium/cilium/pkg/maps/ctmap/gc.(*GC).enable()
      /home/marco/Documents/isovalent/cilium/pkg/maps/ctmap/gc/gc.go:135 +0x17c
  github.com/cilium/cilium/pkg/maps/ctmap/gc.TestGCEnableRatchet()
      /home/marco/Documents/isovalent/cilium/pkg/maps/ctmap/gc/gc_test.go:154 +0x5bc
  testing.tRunner()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:1934 +0x21c
  testing.(*T).Run.gowrap1()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:1997 +0x44

Goroutine 31 (running) created at:
  testing.(*T).Run()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:1997 +0x9d2
  testing.runTests.func1()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:2477 +0x85
  testing.tRunner()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:1934 +0x21c
  testing.runTests()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:2475 +0x96c
  testing.(*M).Run()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:2337 +0xed4
  main.main()
      _testmain.go:47 +0x164
==================
==================
WARNING: DATA RACE
Read at 0x000007088260 by goroutine 32:
  github.com/cilium/cilium/pkg/maps/ctmap.GetInterval()
      /home/marco/Documents/isovalent/cilium/pkg/maps/ctmap/ctmap.go:741 +0x131
  github.com/cilium/cilium/pkg/maps/ctmap/gc.(*GC).enable.func1()
      /home/marco/Documents/isovalent/cilium/pkg/maps/ctmap/gc/gc.go:201 +0x5ad

Previous write at 0x000007088260 by goroutine 31:
  github.com/cilium/cilium/pkg/maps/ctmap/gc.TestGCEnableRatchet()
      /home/marco/Documents/isovalent/cilium/pkg/maps/ctmap/gc/gc_test.go:170 +0x604
  testing.tRunner()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:1934 +0x21c
  testing.(*T).Run.gowrap1()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:1997 +0x44

Goroutine 32 (running) created at:
  github.com/cilium/cilium/pkg/maps/ctmap/gc.(*GC).enable()
      /home/marco/Documents/isovalent/cilium/pkg/maps/ctmap/gc/gc.go:135 +0x17c
  github.com/cilium/cilium/pkg/maps/ctmap/gc.TestGCEnableRatchet()
      /home/marco/Documents/isovalent/cilium/pkg/maps/ctmap/gc/gc_test.go:154 +0x5bc
  testing.tRunner()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:1934 +0x21c
  testing.(*T).Run.gowrap1()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:1997 +0x44

Goroutine 31 (running) created at:
  testing.(*T).Run()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:1997 +0x9d2
  testing.runTests.func1()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:2477 +0x85
  testing.tRunner()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:1934 +0x21c
  testing.runTests()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:2475 +0x96c
  testing.(*M).Run()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:2337 +0xed4
  main.main()
      _testmain.go:47 +0x164
==================
2025/10/01 09:44:52 INFO Conntrack garbage collector interval recalculated expectedPrevInterval=5m0s actualPrevInterval=0s newInterval=7m30s deleteRatio=1e-17 adjustedDeleteRatio=1e-17
2025/10/01 09:44:52 INFO initial gc of ct and nat maps completed duration=1.480844ms
==================
WARNING: DATA RACE
Write at 0x00c00054a8ec by goroutine 31:
  github.com/cilium/cilium/pkg/maps/ctmap/gc.TestGCEnableRatchet()
      /home/marco/Documents/isovalent/cilium/pkg/maps/ctmap/gc/gc_test.go:186 +0x864
  testing.tRunner()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:1934 +0x21c
  testing.(*T).Run.gowrap1()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:1997 +0x44

Previous read at 0x00c00054a8ec by goroutine 10450:
  github.com/cilium/cilium/pkg/maps/ctmap/gc.TestGCEnableRatchet.func4()
      /home/marco/Documents/isovalent/cilium/pkg/maps/ctmap/gc/gc_test.go:184 +0x53
  github.com/stretchr/testify/assert.EventuallyWithT.func1()
      /home/marco/Documents/isovalent/cilium/vendor/github.com/stretchr/testify/assert/assertions.go:2096 +0xb3

Goroutine 31 (running) created at:
  testing.(*T).Run()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:1997 +0x9d2
  testing.runTests.func1()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:2477 +0x85
  testing.tRunner()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:1934 +0x21c
  testing.runTests()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:2475 +0x96c
  testing.(*M).Run()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:2337 +0xed4
  main.main()
      _testmain.go:47 +0x164

Goroutine 10450 (finished) created at:
  github.com/stretchr/testify/assert.EventuallyWithT()
      /home/marco/Documents/isovalent/cilium/vendor/github.com/stretchr/testify/assert/assertions.go:2119 +0x3a7
  github.com/cilium/cilium/pkg/maps/ctmap/gc.TestGCEnableRatchet()
      /home/marco/Documents/isovalent/cilium/pkg/maps/ctmap/gc/gc_test.go:183 +0x844
  testing.tRunner()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:1934 +0x21c
  testing.(*T).Run.gowrap1()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:1997 +0x44
==================
2025/10/01 09:45:12 INFO Starting GC of connection tracking first=false
==================
WARNING: DATA RACE
Read at 0x00c0004aaf90 by goroutine 32:
  github.com/cilium/cilium/pkg/maps/ctmap/gc.TestGCEnableRatchet.func2()
      /home/marco/Documents/isovalent/cilium/pkg/maps/ctmap/gc/gc_test.go:166 +0xf8
  github.com/cilium/cilium/pkg/maps/ctmap/gc.(*GC).enable.func1()
      /home/marco/Documents/isovalent/cilium/pkg/maps/ctmap/gc/gc.go:198 +0x56e

Previous write at 0x00c0004aaf90 by goroutine 31:
  github.com/cilium/cilium/pkg/maps/ctmap/gc.TestGCEnableRatchet()
      /home/marco/Documents/isovalent/cilium/pkg/maps/ctmap/gc/gc_test.go:200 +0x967
  testing.tRunner()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:1934 +0x21c
  testing.(*T).Run.gowrap1()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:1997 +0x44

Goroutine 32 (running) created at:
  github.com/cilium/cilium/pkg/maps/ctmap/gc.(*GC).enable()
      /home/marco/Documents/isovalent/cilium/pkg/maps/ctmap/gc/gc.go:135 +0x17c
  github.com/cilium/cilium/pkg/maps/ctmap/gc.TestGCEnableRatchet()
      /home/marco/Documents/isovalent/cilium/pkg/maps/ctmap/gc/gc_test.go:154 +0x5bc
  testing.tRunner()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:1934 +0x21c
  testing.(*T).Run.gowrap1()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:1997 +0x44

Goroutine 31 (running) created at:
  testing.(*T).Run()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:1997 +0x9d2
  testing.runTests.func1()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:2477 +0x85
  testing.tRunner()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:1934 +0x21c
  testing.runTests()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:2475 +0x96c
  testing.(*M).Run()
      /home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/testing/testing.go:2337 +0xed4
  main.main()
      _testmain.go:47 +0x164
==================
2025/10/01 09:45:12 INFO Conntrack garbage collector interval recalculated expectedPrevInterval=7m30s actualPrevInterval=20.005266533s newInterval=45s deleteRatio=0.9 adjustedDeleteRatio=20.24466903912157
--- FAIL: TestGCEnableRatchet (20.02s)
    gc_test.go:172: 
        	Error Trace:	/home/marco/Documents/isovalent/cilium/pkg/maps/ctmap/gc/gc_test.go:173
        	            				/home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/runtime/asm_amd64.s:1693
        	Error:      	Should not be zero, but was 0
    gc_test.go:172: 
        	Error Trace:	/home/marco/Documents/isovalent/cilium/pkg/maps/ctmap/gc/gc_test.go:172
        	Error:      	Condition never satisfied
        	Test:       	TestGCEnableRatchet
    gc_test.go:183: 
        	Error Trace:	/home/marco/Documents/isovalent/cilium/pkg/maps/ctmap/gc/gc_test.go:184
        	            				/home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/runtime/asm_amd64.s:1693
        	Error:      	"0" is not greater than "0"
    gc_test.go:183: 
        	Error Trace:	/home/marco/Documents/isovalent/cilium/pkg/maps/ctmap/gc/gc_test.go:183
        	Error:      	Condition never satisfied
        	Test:       	TestGCEnableRatchet
    gc_test.go:183: 
        	Error Trace:	/home/marco/Documents/isovalent/cilium/pkg/maps/ctmap/gc/gc_test.go:184
        	            				/home/marco/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/src/runtime/asm_amd64.s:1693
        	Error:      	"0" is not greater than "0"
    gc_test.go:183: 
        	Error Trace:	/home/marco/Documents/isovalent/cilium/pkg/maps/ctmap/gc/gc_test.go:183
        	Error:      	Condition never satisfied
        	Test:       	TestGCEnableRatchet
    gc_test.go:188: 
        	Error Trace:	/home/marco/Documents/isovalent/cilium/pkg/maps/ctmap/gc/gc_test.go:188
        	Error:      	"5.001433313s" is not greater than "5.001553401s"
        	Test:       	TestGCEnableRatchet
    testing.go:1617: race detected during execution of test
FAIL
```

/cc @tommyp1ckles

### PR DESCRIPTION
**Pull request by AritraDey-Dev**
fix race conditions and flakiness in `TestGCEnableRatchet`

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #41960

### CODE REVIEW

File: pkg/maps/ctmap/gc/gc_test.go [hunk 1]
```diff
@@ -22,13 +23,25 @@ import (
 // TestGCEnable tests the overall *flow* of ctmap GC scheduling
 // while abstracting out the underlying garbage collection logic.
 func TestGCEnableDualStack(t *testing.T) {
+	// Save original state
+	originalConntrackGCMaxInterval := option.Config.ConntrackGCMaxInterval
+	defer func() {
+		// Restore global state if not in race mode
+		if !skipGlobalStateRestoration {
+			option.Config.ConntrackGCMaxInterval = originalConntrackGCMaxInterval
```
Comment (tommyp1ckles) [inline pkg/maps/ctmap/gc/gc_test.go]: Instead of trying to change then restore the global state, I think we should just create local variables in the ctmap or gc packages and then just change those similar to what was done here: https://github.com/cilium/cilium/pull/41258/commits/c376d45f6e7292e3597b451c771c497c571288cc

File: pkg/maps/ctmap/gc/gc_test_norace.go [hunk 2]
```diff
@@ -0,0 +1,10 @@
+// SPDX-License-Identifier: Apache-2.0
+// Copyright Authors of Cilium
+
+//go:build !race
```
Comment (tommyp1ckles) [inline pkg/maps/ctmap/gc/gc_test_norace.go]: As per my comment above, maybe lets just clean up using the global directly so we don't have to deal with conditional compilations.

**Review by tommyp1ckles — CHANGES_REQUESTED** [review]
Nice work, thanks for fixing this up @AritraDey-Dev 😄 

Just had one comment regarding how we deal with mutating the global config vars.

File: pkg/maps/ctmap/gc/gc_test.go [hunk 3]
```diff
@@ -119,94 +126,137 @@ func TestGCEnableDualStack(t *testing.T) {
...
+		<-initialPassDone
+
+		// Wait for a few more passes to see interval ratcheting up
+		initialCount := passCount.Load()
 		assert.EventuallyWithT(t, func(c *assert.CollectT) {
-			assert.Greater(c, ipv4Passes.Load(), prev)
-		}, time.Second*5, time.Millisecond*10)
-		prev = ipv4Passes.Load()
-		if lastRealDuration != 0 {
-			assert.Greater(t, time.Since(lastPassTime), lastRealDuration)
```
Comment (tommyp1ckles) [inline pkg/maps/ctmap/gc/gc_test.go:188]: One thing I missed on my first pass, I think we're losing some of the intended coverage for which the test was intended; specifically with respect to the timing between Gc runs going up/down based on the results of the last pass.

To illustrate this, if I comment out the:
```go
interval = min(time.Duration(float64(interval)*1.5).Round(gcIntervalRounding), defaults.ConntrackGCMaxLRUInterval)
```
line in ctmap.go, on main this will result in TestGCEnableRatchet failing.  But if I do the same on this branch the test passes.

A similar result would probably be seen on the other one (i.e. max(...)) for ratchetting down.

**Review by tommyp1ckles — CHANGES_REQUESTED** [review]

File: pkg/maps/ctmap/gc/gc_test.go (hunk 3 above)
Comment (AritraDey-Dev) [reply pkg/maps/ctmap/gc/gc_test.go:188]: Sorry for the delay. Good point! I changed the test so it now checks the interval both decreasing and increasing.

**Review by tommyp1ckles — APPROVED** [review]

**Comment by tommyp1ckles** [comment]
@AritraDey-Dev Thanks for the changes!  I see some unrelated test failures; could you do a rebase on this branch?

File: pkg/maps/ctmap/gc/gc_test_norace.go [hunk 4]
```diff
@@ -1,10 +0,0 @@
-// SPDX-License-Identifier: Apache-2.0
```
Comment (tommyp1ckles) [inline pkg/maps/ctmap/gc/gc_test_norace.go]: Oh, missed this, can we just drop these changes from the first commit rather than committing them then removing them one commit later.

**Review by tommyp1ckles — CHANGES_REQUESTED** [review]

File: pkg/maps/ctmap/gc/gc_test_norace.go (hunk 4 above)
Comment (tommyp1ckles) [reply pkg/maps/ctmap/gc/gc_test_norace.go]: Or specifically, because the second commit likely relies on the first commit to build, I recommend doing a commit that adds the `enableWithConfig(...)` func as a prerequisite for a second commit which does all the testing changes.

**Review by tommyp1ckles — APPROVED** [review]
