### PR TITLE
agent: defend against null pointer refs in cecManager.getEndpoint()

### LINKED ISSUE #37187: agent: segfault in cecManager.getEndpoint()
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.5 and lower than v1.17.0

### What happened?

We've seen agent segfaults on versions 1.16.2 and 1.16.5 with the following approximate stack trace:

```
/go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/job/job.go:159 +0x174
created by github.com/cilium/hive/job.(*group).Start.func1 in goroutine 1
/go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/job/timer.go:131 +0x448
github.com/cilium/hive/job.(*jobTimer).start(0xc00243b6e0, {0x452ea10, 0xc002d97380}, 0xc00354a7d0?, {0x4536c60, 0xc00243b440}, {{{0xc0008793a0, 0x1, 0x1}}, 0xc000e5b850, ...})
/go/src/github.com/cilium/cilium/pkg/ciliumenvoyconfig/cec_reconciler.go:306 +0x197
github.com/cilium/cilium/pkg/ciliumenvoyconfig.(*ciliumEnvoyConfigReconciler).syncHeadlessService(0xc002464000, {0xc011f67d78?, 0x49ef6f?})
/go/src/github.com/cilium/cilium/pkg/ciliumenvoyconfig/cec_manager.go:180 +0x212
github.com/cilium/cilium/pkg/ciliumenvoyconfig.(*cecManager).syncCiliumEnvoyConfigService(0xc0002969a0, {0xc00597a510, 0xe}, {0xc00a7ab8c0, 0x1b}, 0xc0254a9f80?)
/go/src/github.com/cilium/cilium/pkg/ciliumenvoyconfig/cec_manager.go:252 +0xd3
github.com/cilium/cilium/pkg/ciliumenvoyconfig.(*cecManager).getEndpoint(0xc00a7ab8c0?, {0xc00597a600, 0xe}, {0xc00a7ab900, 0x1b})
goroutine 1555 [running]:
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x2c3fc73]
panic: runtime error: invalid memory address or nil pointer dereference
```

When this occurs, CEC reconciliation stops on the node and ClusterIP services become unreachable (though direct-dialing pods still works).

### How can we reproduce the issue?

1. Install cilium 1.16.5 via helm
1. Create at least one CEC
1. Create a large number of endpoints and churn them constantly
1. Wait for the reconciliation loop to segfault

### Cilium Version

```
Client: 1.16.5 ad688277 2024-12-12T20:18:31+00:00 go version go1.22.10 linux/amd64
Daemon: 1.16.5 ad688277 2024-12-12T20:18:31+00:00 go version go1.22.10 linux/amd64
```

### Kernel Version

`Linux 6.1.119 #1 SMP PREEMPT_DYNAMIC Fri Dec 20 22:32:32 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
(via Bottlerocket)

### Kubernetes Version

1.29 EKS

### Regression

No

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by aetimmes**
Currently, if another thread deletes an entry from the Endpoint store while getEndpoint is iterating over the keys, it can result in a segfault+panic. This change adds some light bounds-checking to eliminate that possibility.

Fixes: #37187

```release-note
agent: defend against null pointer refs in cecManager.getEndpoint()
```

### CODE REVIEW

**Review by sayboras — APPROVED** [review]
Good catch, thanks :100:

File: pkg/ciliumenvoyconfig/cec_manager.go [hunk 1]
```diff
@@ -271,8 +271,8 @@ func (r *cecManager) getEndpoint(serviceName string, serviceNamespace string) (*
 	var res *k8s.Endpoints
 	iter := store.IterKeys()
 	for iter.Next() {
-		e, _, _ := store.GetByKey(iter.Key())
-		if e.EndpointSliceID.ServiceID.Name == serviceName &&
+		e, exists, error := store.GetByKey(iter.Key())
+		if exists && error == nil && e.EndpointSliceID.ServiceID.Name == serviceName &&
```
Comment (komapa) [inline pkg/ciliumenvoyconfig/cec_manager.go]: Shouldn't `if exists && e.EndpointSliceID.ServiceID.Name == serviceName &&` be sufficient?

Comment (aetimmes) [reply pkg/ciliumenvoyconfig/cec_manager.go]: If we can assert that `exists -> !error` for all inputs, then yes, but I don't know enough about current (or future) underlying implementations to make that assertion. Happy to change this if someone smarter than me can make that assertion. 😄

**Review by komapa — APPROVED** [review]

**Comment by aetimmes** [comment]
We built an image with this fix and deployed it and are still seeing the segfaults; I'm going to hold this change back until I can investigate further - I assumed it was `e` that was the issue, but maybe it's one of `e`'s nested fields?

File: pkg/ciliumenvoyconfig/cec_manager.go [hunk 2]
```diff
@@ -272,7 +272,7 @@ func (r *cecManager) getEndpoint(serviceName string, serviceNamespace string) (*
 	iter := store.IterKeys()
 	for iter.Next() {
 		e, _, _ := store.GetByKey(iter.Key())
-		if e.EndpointSliceID.ServiceID.Name == serviceName &&
+		if e != nil && e.EndpointSliceID.ServiceID.Name == serviceName &&
```
Comment (aetimmes) [inline pkg/ciliumenvoyconfig/cec_manager.go:275]: `e` is a pointer to a struct, so current working theory is we're somehow getting back `exists = true` and `e = nil` (which I suppose `exists` indicates that the _key_ exists in the store and says nothing about the _value_).

Comment (aetimmes) [reply pkg/ciliumenvoyconfig/cec_manager.go:275]: Okay, I'm satisfied with this explanation. "Check to see if the only thing that can be nil in the comparison is nil" defends against the nil pointer dereference, and once we have a pointer, the memory won't be freed out from under us.
