### PR TITLE
 Release IPPrefixes: Support AWS ENI IP Prefix unassignment

### LINKED ISSUE #32209: Cilium operator doesn't release excess IPv4 CIDR block in AWS ENI when prefix delegation is enabled
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In cilium operator, `--aws-enable-prefix-delegation` and `--aws-release-excess-ips` are enabled.

/28 IPv4 CIDR blocks are assigned to AWS ENI, it can assign multiple IPv4 blocks based on required IPs/pod numbers in the node. However, when pod number reduces in the node, excess IPv4 CIDR blocks are not released.

From source code, https://github.com/cilium/cilium/blame/198b79470687f7e9a7786e768be0c9ec032cf5f8/pkg/aws/ec2/ec2.go#L734 function `UnassignENIPrefixes` is never used.
image

I think #18463 added support for AWS ENI prefix delegation, but it didn't consider release excess IPv4 prefix.

### Cilium Version

v1.12.3

### Kernel Version

Linux 5.15.0-1022-aws 20.04.1-Ubuntu

### Kubernetes Version

v1.23.5

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by hsalluri259**
Cilium currently do not support releasing IPPrefixes due to which IP starvation is happening in our Kubernetes clusters. We have to manually delete a node in order to free unused IPPrefixes. With this fix, operator will release those unused IPPrefixes to reassign them again in AWS ENI. Added no-op stub implementation in azure and alibabacloud to satisfy NodeOperations interface.

Fixes: #32209, #39904
### Without this fix, delegated prefixes won’t be released until their nodes are deleted, resulting in wasted IP space.
Screenshot 2025-05-02 at 12 03 43 PM
### With the fix in place, IP Prefixes are released and can be reused again.
Screenshot 2025-05-02 at 12 21 05 PM

Non goals :

- IPv6 prefix support

```release-note
Support IPPrefix unassignment in order to reuse those IPPrefixes and prevent IP starvation.
This would require cilium-operator's AWS IAM role update to add "ec2:DescribeRouteTables" permissions.  
```

### CODE REVIEW

File: pkg/ipam/node.go [hunk 1]
```diff
@@ -878,7 +881,15 @@ func (n *Node) handleIPRelease(ctx context.Context, a *maintenanceAction) (insta
 			logfields.Releasing, ipsToRelease,
 			logfields.SelectedInterface, a.release.InterfaceID,
 			logfields.SelectedPoolID, a.release.PoolID)
-		scopedLog.Info("Releasing excess IPs from node")
+		// Unassign IPPrefixes instead of IPs
+		if len(a.release.IPPrefixesToRelease) > 0 {
+			err := n.ops.ReleaseIPPrefixes(ctx, a.release)
+			if err != nil {
+				n.logger.Load().Warn("Unable to unassign IP prefixes from interface", logfields.Error, err)
```
Comment (doniacld) [inline pkg/ipam/node.go]: Why not use the `scopedLog` here?

File: pkg/ipam/node_manager_test.go [hunk 2]
```diff
@@ -162,6 +162,12 @@ func (n *nodeOperationsMock) releaseIP(ip string) error {
 	return fmt.Errorf("IP %s not found", ip)
 }
 
+func (m *nodeOperationsMock) ReleaseIPPrefixes(ctx context.Context, release *ReleaseAction) error {
+	fmt.Println("Printing release object", release)
```
Comment (doniacld) [inline pkg/ipam/node_manager_test.go]: Is it a leftover `Println`?

Comment (doniacld) [reply pkg/ipam/node_manager_test.go]: After rechecking, it might be intended...

**Review by doniacld — DISMISSED** [review]
One nit remark and a question. Otherwise LGTM. 
NB: I think that the commit description is not well formatted and will exceed chars limit per line.

I will have a look in order to reopen the [issue](https://github.com/cilium/cilium/issues/32209)

File: pkg/aws/eni/node.go [hunk 3]
```diff
@@ -153,9 +154,44 @@ func (n *Node) PrepareIPRelease(excessIPs int, scopedLog *slog.Logger) *ipam.Rel
 	// addresses available for release
 	for _, eniId := range slices.Sorted(maps.Keys(n.enis)) {
 		e := n.enis[eniId]
-
-		// IP release for prefixes is not currently supported. Will skip releasing from this ENI
-		if len(e.Prefixes) > 0 {
+		ipPrefixes := e.Prefixes
+		if len(ipPrefixes) > 0 {
```
Comment (PavelGloba) [inline pkg/aws/eni/node.go:169]: Shouldn't it be checked straight away for ```> 1``` since nothing else is done here?

Comment (hsalluri259) [reply pkg/aws/eni/node.go:169]: Good question. I thought about it. `> 0` checks if the ENI uses ipprefixes or not followed by `> 1` checks if the ENI has at least 2 ipprefixes or not before attempting to release ipprefixes. I think I can replace it with if else block rather than use two if statements. Without this check, line `#197` will be executed if there is only one ipprefix in use and continue to add individual IPs from IPPrefix to release which we want to avoid.

File: pkg/ipam/node.go (hunk 1 above)
Comment (hsalluri259) [reply pkg/ipam/node.go]: Updated to use `scopedLog`

File: pkg/ipam/node_manager_test.go (hunk 2 above)
Comment (hsalluri259) [reply pkg/ipam/node_manager_test.go]: removed the statement, it was leftover.

File: pkg/aws/eni/node.go (hunk 3 above)
Comment (PavelGloba) [reply pkg/aws/eni/node.go:169]: Thanks, I get it now

**Comment by doniacld** [comment]
I wanted to let you know that after discussing with @gandro it's not as trivial as I thought. There have been races in the past, some context here in this [PR](https://github.com/cilium/cilium/pull/17939).

**Comment by doniacld** [comment]
I just wanted to let you know that @gandro gave me some context about the history. There were data races issues that could happen. It is not as trivial as I thought.

https://github.com/cilium/cilium/pull/17939

**Comment by hsalluri259** [comment]
> I wanted to let you know that after discussing with @gandro it's not as trivial as I thought. There have been races in the past, some context here in this [PR](https://github.com/cilium/cilium/pull/17939).

@doniacld Thank you for your comment. I went through the PR. I am following exact same way to handle release of IPPrefixes. I am handling IPPrefixes release same way as IP release. Once the operator knows there are ipprefixes to release, operator marks the ipaddresses as `ready-for-release`. After that instead of releasing IPs via `ReleaseIPs` function, I am using `ReleaseIPPrefixes`. As a safety measure, I will add a condition as in `if len(ipprefixesToRelease) * 16 == len(ipaddressesToRelease)`. This will ensure the all IPaddresses of an IPPrefix are there. Please let me know if you think this is overkill. Thanks!
Screenshot 2025-05-07 at 9 46 53 AM

File: pkg/aws/eni/node.go [hunk 4]
```diff
@@ -153,9 +154,44 @@ func (n *Node) PrepareIPRelease(excessIPs int, scopedLog *slog.Logger) *ipam.Rel
...
+			// Prevents a newly added node's IPPrefix from being unassigned.
+			if len(ipPrefixes) > 1 {
```
Comment (hsalluri259) [inline pkg/aws/eni/node.go]: @doniacld Today I noticed an issue with this condition where number of prefixes are 1, usedIPs = 9, preAllocate = 8. This sums to 17. So operator will add another prefix per logs
```
- time=2025-05-13T20:25:50Z level=info msg="Resolving IP deficit of node" subsys=ipam-allocator-aws name=ip-10-196-106-143.us-west-2.compute.internal instanceID=i-0334458ecbc53b93c selectedInterface=eni-0ae692dae0c1f642f selectedPoolID=subnet-099594f12968464eb maxIPsToAllocate=1 availableForAllocation=128 emptyInterfaceSlots=1 available=16 used=9 neededIPs=1 remainingInterfaces=2
```
After that this condition checks if any of the IPs are used in the newly added prefix. Since it is added to satisfy preAllocate, this newly added ipPrefix was deleted. This happens in a loop. I added screenshots for the same. I am working on calculating number of Prefixes in a different way. So this problem won't happen. 
Screenshot 2025-05-13 at 1 32 14 PM
Screenshot 2025-05-13 at 1 32 26 PM
Screenshot 2025-05-13 at 1 41 28 PM

Comment (hsalluri259) [reply pkg/aws/eni/node.go]: Now I added the fix to calculate required number of prefixes properly. With this fix the above mentioned problem won't occur. 
Screenshot 2025-05-14 at 7 37 00 AM

File: pkg/aws/eni/node.go [hunk 5]
```diff
@@ -153,9 +154,49 @@ func (n *Node) PrepareIPRelease(excessIPs int, scopedLog *slog.Logger) *ipam.Rel
...
 	for _, eniId := range slices.Sorted(maps.Keys(n.enis)) {
 		e := n.enis[eniId]
-
-		// IP release for prefixes is not currently supported. Will skip releasing from this ENI
-		if len(e.Prefixes) > 0 {
+		ipPrefixes := e.Prefixes
+		if len(ipPrefixes) > 0 {
+			usedIPs := n.k8sObj.Status.IPAM.Used
+			usedIPsCount := len(usedIPs)
+			ipsPerPrefix := 16
```
Comment (gandro) [inline pkg/aws/eni/node.go]: Please use `ENIPDBlockSizeIPv4` here

File: pkg/aws/eni/node.go [hunk 6]
```diff
@@ -153,9 +154,49 @@ func (n *Node) PrepareIPRelease(excessIPs int, scopedLog *slog.Logger) *ipam.Rel
...
+			preAllocate := n.k8sObj.Spec.IPAM.PreAllocate
+			// Calculate number of prefixes needed
+			requiredPrefixes := (usedIPsCount + preAllocate + ipsPerPrefix - 1) / ipsPerPrefix
```
Comment (gandro) [inline pkg/aws/eni/node.go]: Why do we need to do this calculation, in particular, why do you use `n.k8sObj.Spec.IPAM.PreAllocate` here? 

When `PrepareIPRelease` is called, `excessIPs` already has contained the number of required IPs and has computed the amount of excess IPs minus preAllocate. Wouldn't it be simpler to just check `excessIPs` and see if it is larger than a prefix? And then check if there's a prefix which can be released.

File: pkg/aws/eni/node.go [hunk 7]
```diff
@@ -153,9 +154,49 @@ func (n *Node) PrepareIPRelease(excessIPs int, scopedLog *slog.Logger) *ipam.Rel
...
+
+			if len(ipPrefixes) > requiredPrefixes {
+				unusedIPPrefixes := []string{}
+				matchedIPs := []string{}
+				// Check each prefix to determine if at least one IP is used in IPAM.
+				for _, prefix := range ipPrefixes {
+					_, ipNet, err := net.ParseCIDR(prefix)
```
Comment (gandro) [inline pkg/aws/eni/node.go]: nit: Where possible please `net/netip` rather than the old types.

**Comment by doniacld** [comment]
@hsalluri259 thanks for fixing the issue you found. I asked @gandro to double-check since I am not enough familiar with this code and it is a bit tricky.

File: pkg/ipam/node.go [hunk 8]
```diff
@@ -878,7 +881,15 @@ func (n *Node) handleIPRelease(ctx context.Context, a *maintenanceAction) (insta
...
 			logfields.SelectedPoolID, a.release.PoolID)
-		scopedLog.Info("Releasing excess IPs from node")
+		// Unassign IPPrefixes instead of IPs
+		if len(a.release.IPPrefixesToRelease) > 0 {
+			err := n.ops.ReleaseIPPrefixes(ctx, a.release)
+			if err != nil {
+				scopedLog.Warn("Unable to unassign IP prefixes from interface", logfields.Error, err)
+				return false, err
+			}
+			return false, err
```
Comment (gandro) [inline pkg/ipam/node.go]: Don't we want to update the metrics below if release fails?

**Review by gandro — COMMENTED** [review]
Overall I think this looks fine to me, I have a bit of feedback however

File: pkg/ipam/node.go (hunk 8 above)
Comment (hsalluri259) [reply pkg/ipam/node.go]: Agreed. I was thinking the same I need to update metrics for success/failed. I am not sure how can I test whether the metric is submitted or not? Would you be able share any information about the same. Thanks!

File: pkg/aws/eni/node.go (hunk 6 above)
Comment (hsalluri259) [reply pkg/aws/eni/node.go]: I checked what is the value of `excessIPs` by assigning one prefix. It was 8. When I assigned two prefixes, it was 24. So like you said it was subtracting preAllocate. I might have to do `excessIPs + preAllocate >= ENIPDBlockSizeIPv4 which is 16` in order to do determine whether I can release a prefix or not.

Comment (hsalluri259) [reply pkg/aws/eni/node.go]: Since `excessIPs` is calculated per prefix, it won't work. Above formula fails when `usedIPs = 9, preAllocate = 8`. In this case, operator will add a new prefix, but the newly added prefix will be evaluated as `excessIPs = 8 , preAllocate=8`. The above condition will be true and delete the prefix. Then Operator will add a new prefix to resolve IPDeficit. It will happen in a loop. I tried with adding `excessIPs + preAllocate - 1 >= ENIPDBlockSizeIPv4` but it doesn't delete prefix since it is evaluated to at most 15 for an used prefix. So I am sticking with that formula but will update variables.

File: pkg/aws/eni/node.go (hunk 5 above)
Comment (hsalluri259) [reply pkg/aws/eni/node.go]: Thanks! updated.

File: pkg/aws/eni/node.go (hunk 7 above)
Comment (hsalluri259) [reply pkg/aws/eni/node.go]: Updated. Thanks!

File: pkg/ipam/node.go (hunk 8 above)
Comment (hsalluri259) [reply pkg/ipam/node.go]: I added metrics similar to what we do for releasing IPs. Please let me know if there are any corrections. And appreciate your help if you can share any information about how to verify these metrics.

File: pkg/aws/eni/node.go (hunk 6 above)
Comment (hsalluri259) [reply pkg/aws/eni/node.go]: I tried all those possible ways not to use this formula, but I think this is cleaner and prevents us from deleting IP prefix when an ipPrefix was added to resolve ipDeficit. I even added a check to break if we reached number of requiredPrefixes to prevent adding more prefixes to delete though they're unused.

Comment (gandro) [reply pkg/aws/eni/node.go]: Thanks for looking into this. Is there a away to unify `excessIPs` with the PD logic? I'm not a fan of having `excessIPs` passed in, but `requiredPrefixes` calculated on the fly.

Having the number of excess being calculated differently in two different places makes the code even harder to read.

File: pkg/ipam/node.go [hunk 9]
```diff
@@ -878,13 +882,29 @@ func (n *Node) handleIPRelease(ctx context.Context, a *maintenanceAction) (insta
...
 			logfields.SelectedInterface, a.release.InterfaceID,
 			logfields.SelectedPoolID, a.release.PoolID)
-		scopedLog.Info("Releasing excess IPs from node")
 		start := time.Now()
+		// Unassign IPPrefixes instead of IPs
+		if len(a.release.IPPrefixesToRelease) > 0 {
+			err := n.ops.ReleaseIPPrefixes(ctx, a.release)
+			if err == nil {
+				n.manager.metricsAPI.ReleaseAttempt(releaseIPPrefixes, success, string(a.release.PoolID), metrics.SinceInSeconds(start))
+				n.manager.metricsAPI.AddIPRelease(string(a.release.PoolID), int64(len(a.release.IPsToRelease)))
```
Comment (gandro) [inline pkg/ipam/node.go]: Looking at this more closely, isn't `a.release.IPToRelease` now double-counted? Once here and once below (which afaiu is still running when prefixes are released, since `IPsToRelease` is set)

Comment (hsalluri259) [reply pkg/ipam/node.go]: No, it doesn't count two times. It returns True As soon as metrics submitted when `n.ops.ReleaseIPPrefixes` succeeds
```
n.manager.metricsAPI.AddIPRelease(string(a.release.PoolID), int64(len(a.release.IPsToRelease)))
return true, nil
```
In case of error, it does the below
```
n.manager.metricsAPI.ReleaseAttempt(releaseIPPrefixes, failed, string(a.release.PoolID), metrics.SinceInSeconds(start))
return false, err
```
So in both the cases, it won't double count. I validated that. Thanks for checking!

File: pkg/aws/eni/node.go (hunk 6 above)
Comment (hsalluri259) [reply pkg/aws/eni/node.go]: I think the problem is, how does the operator know when to call [PrepareIPRelease](https://github.com/cilium/cilium/blob/main/pkg/ipam/node.go#L669) without calculating `excessIPs`? This is calculated earlier since all three cloud providers use `excessIPs`, but I think Prefix Delegation is used by AWS only AFAIK. Once the operator knows there are `excessIPs` to release, then we are checking if the operation has to be `ipPrefixUnassignment or ipAddressRelease`.  So I am not sure if I can put that logic in https://github.com/cilium/cilium/blob/main/pkg/ipam/node.go#L669 or calculate `excessIPs` when `PrepareIPRelease` is called. Calculating `excessIPs` can be done anywhere, but I think it is done under `pkg/ipam/node.go` to determine whether there is a need to call `PrepareIPRelease or not`.

Comment (hsalluri259) [reply pkg/aws/eni/node.go]: On a second thought, I can implement `excessIPPrefixes` in each cloud provider's [node.go](https://github.com/cilium/cilium/blob/main/pkg/ipam/node.go) with aws is being real and other providers' node.go will have dummy implementation. Then I will input the `excessIPPrefixes` to [PrepareIPRelease](https://github.com/cilium/cilium/blob/main/pkg/ipam/node.go#L669) call. This way we are providing both `excessIPs and excessIPPrefixes` rather than calculating `excessIPPrefixes` on the fly. Please let me know if that is a good approach.

Comment (gandro) [reply pkg/aws/eni/node.go]: > This way we are providing both excessIPs and excessIPPrefixes rather than calculating excessIPPrefixes on the fly.

I prefer that approach - in particular since I still hope we eventually can add IPv6 support at some point (in which case counting individual addresses no longer becomes feasible)

File: pkg/ipam/node.go (hunk 9 above)
Comment (gandro) [reply pkg/ipam/node.go]: Ah. I missed the early return, thanks for pointing that out. It's been a while since I looked at the PD logic - is it possible for a node to have both prefixes and individual IPs assigned to it? Because if so, then I don't think we can do an early return.

Comment (hsalluri259) [reply pkg/ipam/node.go]: Yes. Usually a prefix is assigned, but when the subnet runs out the prefixes then secondary IP addresses(/32) will be [assigned](https://github.com/cilium/cilium/blob/main/pkg/aws/eni/node.go#L309-L310). Currently we are not releasing both IPPrefixes and individual IP addresses if `isPrefixDelegated is true` per [this condition](https://github.com/cilium/cilium/blob/main/pkg/aws/eni/node.go#L158). But with my fix, we will be releasing ipprefixes which will prevent IP Prefix exhaustion issue. Out of 25 EKS cluster, only one cluster ran out of IPPrefixes which had ~1200prefixes. I see the value in checking but my question to you, is it worth investigating for individual IP addresses? Please let me know your preference.

Comment (hsalluri259) [reply pkg/ipam/node.go]: I just noticed this line https://github.com/cilium/cilium/blob/main/pkg/aws/eni/node.go#L780 
I think the operator do not support mixed use of prefixes and secondary IP addresses. But this line https://github.com/cilium/cilium/blob/main/pkg/aws/eni/node.go#L309-L310 says it supports when we run out of prefixes. It is confusing.

File: pkg/aws/eni/node.go (hunk 6 above)
Comment (hsalluri259) [reply pkg/aws/eni/node.go]: Please take a look at the latest commit. I implemented `excessIPPrefixes` and passed in as an input as suggested. Thanks!

File: pkg/ipam/node.go (hunk 9 above)
Comment (gandro) [reply pkg/ipam/node.go]: @hemanthmalla Since you contributed PD originally, do you know if/when we support a node having both prefixes and individual IPs assigned?

Comment (hsalluri259) [reply pkg/ipam/node.go]: The cluster we ran out of IPPrefixes had secondary IP addresses assigned and they are still there. 
```
eni-0d8b7a87a24bb5ea3:
        addresses:
        - 101.69.95.101
        -  101.69.92.69
        - 101.69.90.240
        ...
        ...
        - 101.69.90.255 
        prefixes:
        - 101.69.90.240/28
 ```

Comment (gandro) [reply pkg/ipam/node.go]: Right, thanks for confirming. 

So is there any case where we release both the excess prefixes AND the excess single IPs in one go? Because as far as I understand the code `PrepareIPRelease` can create a `maintenanceAction` action that wants to release both IPs and prefixes at once, right?

In which case, it would we wrong to do an early exit after we've released prefixes, since we still have some IPs to release? Or am I missing something?

File: pkg/aws/eni/node.go [hunk 10]
```diff
@@ -207,6 +245,35 @@ func (n *Node) PrepareIPRelease(excessIPs int, scopedLog *slog.Logger) *ipam.Rel
...
+	ipsPerPrefix := option.ENIPDBlockSizeIPv4
+	excessIPPrefixes := 0
+	if !n.IsPrefixDelegated() {
+		return 0
+	}
+	for _, e := range n.enis {
+		ipPrefixesCount := len(e.Prefixes)
+		if ipPrefixesCount > 0 {
+			usedIPsCount := len(n.k8sObj.Status.IPAM.Used)
+			excessIPPrefixes += ipPrefixesCount - (usedIPsCount+n.k8sObj.Spec.IPAM.PreAllocate+ipsPerPrefix-1)/ipsPerPrefix
```
Comment (gandro) [inline pkg/aws/eni/node.go]: The expression `(usedIPsCount+n.k8sObj.Spec.IPAM.PreAllocate+ipsPerPrefix-1)/ipsPerPrefix` in independent of the the current ENI `e`, right?

I think this makes this math harder to read than it needs to be. Could we add this subtraction outside of the loop?

**Comment by doniacld** [comment]
I am removing myself from the PR.

File: pkg/aws/eni/node.go (hunk 10 above)
Comment (hsalluri259) [reply pkg/aws/eni/node.go]: sure, that makes sense.

File: pkg/ipam/node.go (hunk 9 above)
Comment (hsalluri259) [reply pkg/ipam/node.go]: sure, I can add both prefixes and ipAddresses when `PrepareIPRelease` is called. Then `handleIPRelease` will release both. As of now I didn't add any implementation to release individual IP addresses. I will add that and update you. Thanks!

Comment (hsalluri259) [reply pkg/ipam/node.go]: I think this is going to happen only when ipPrefixes are exhausted like in my production cluster a few weeks ago. This happened because Cilium doesn't has IPPrefix release functionality. In all other cases, it is going to be an unnecessary check.

File: pkg/aws/eni/node.go (hunk 10 above)
Comment (hsalluri259) [reply pkg/aws/eni/node.go]: moved it to outside of the loop

File: pkg/ipam/node.go (hunk 9 above)
Comment (hsalluri259) [reply pkg/ipam/node.go]: Now I added support to release both IPPrefixes and secondary IP addresses in one go. So no more IP wastage. Please take a look.

File: pkg/aws/eni/node.go [hunk 11]
```diff
@@ -153,9 +153,68 @@ func (n *Node) PrepareIPRelease(excessIPs int, scopedLog *slog.Logger) *ipam.Rel
 	// addresses available for release
 	for _, eniId := range slices.Sorted(maps.Keys(n.enis)) {
```
Comment (gandro) [inline pkg/aws/eni/node.go:154]: Something I just noticed now (because it's hidden by the GitHub UI): There's a `if e.IsExcludedBySpec(n.k8sObj.Spec.ENI)` guard in this loop that I think we need to respect for prefix release as well. That function checks if the ENI is managed by Cilium or not - if it is not, then we do not want to touch it.

On a similar note, we probably also want to log the `Considering ENI for IP release` message for prefixes too.

File: pkg/aws/eni/node.go [hunk 12]
```diff
@@ -153,9 +153,68 @@ func (n *Node) PrepareIPRelease(excessIPs int, scopedLog *slog.Logger) *ipam.Rel
...
+							}
+						}
+					}
+				}
+				if len(unusedIPPrefixes) > 0 {
+					r.InterfaceID = eniId
+					r.PoolID = ipamTypes.PoolID(e.Subnet.ID)
+					r.IPsToRelease = append(matchedIPs, secondaryIPs...)
+					r.IPPrefixesToRelease = unusedIPPrefixes
+					r.StandalonePrivateIPs = secondaryIPs
```
Comment (gandro) [inline pkg/aws/eni/node.go]: Why are we using a new field for this? In other words, why can we not use `r.IPsToRelease`?

What I would have expected is the following:

- If no prefix delegation and there are excess IPs: PrepareIPRelease populates IPsToRelease
- If there are excess prefixes (but no standalone IPs): PrepareIPRelease populates IPPrefixesToRelease (with the prefixes to release) and IPsToRelease with the IPs contained by the prefixes. 
- If there are excess IPs and standalone IPs:  PrepareIPRelease populates IPPrefixesToRelease (with the prefixes to release) and IPsToRelease with the IPs contained by the prefixes, as well as the standalone excess IPs.

I also wonder if we actually should have an `excessIPPrefixes` counter. Because now I don't understand how `secondaryIPs` interacts with `excessIPPrefixes`. We do seem to release secondary IPs if we have `excessIPPrefixes > 0`, but those secondary IPs are not part of a prefix. So why would we want to release them?

Wouldn't it be simpler to just have `excessIPs` contain the IPs belonging to a prefix and then here detect if we can release a full prefix or not? If not, we just release secondary IPs using individual-IP-release logic that already exists in current Cilium.

File: pkg/aws/eni/node.go [hunk 13]
```diff
@@ -207,6 +266,35 @@ func (n *Node) PrepareIPRelease(excessIPs int, scopedLog *slog.Logger) *ipam.Rel
...
+func (n *Node) CalculateExcessIPPrefixes() int {
+	n.mutex.RLock()
+	defer n.mutex.RUnlock()
+	ipsPerPrefix := option.ENIPDBlockSizeIPv4
+	excessIPPrefixes := 0
+	if !n.IsPrefixDelegated() {
+		return 0
+	}
+	usedIPsCount := len(n.k8sObj.Status.IPAM.Used)
+	requiredIPPrefixes := (usedIPsCount + n.k8sObj.Spec.IPAM.PreAllocate + ipsPerPrefix - 1) / ipsPerPrefix
```
Comment (gandro) [inline pkg/aws/eni/node.go]: Looking at how `excessIPs` is calculated, we also take `getMaxAboveWatermark` into account when allocating prefixes:

https://github.com/cilium/cilium/blob/f497182e7b1c36d86bc3f2941130437d4feb38af/pkg/ipam/node.go#L377-L379

I think we need to do the same here, because it seems `AvailableForAllocation` does contain `getMaxAboveWatermark` and thus we might over-allocate when assigning prefixes. If we don't consider `getMaxAboveWatermark` here, then we will potentially remove prefixes that we just assigned, causing a allocate-release loop.

File: pkg/aws/eni/node.go [hunk 14]
```diff
@@ -207,6 +266,35 @@ func (n *Node) PrepareIPRelease(excessIPs int, scopedLog *slog.Logger) *ipam.Rel
...
+	for _, e := range n.enis {
+		if len(e.Prefixes) > 0 {
+			excessIPPrefixes += len(e.Prefixes) - requiredIPPrefixes
```
Comment (gandro) [inline pkg/aws/eni/node.go]: This math looks off:

Assume we have 3 ENIs, with 2 prefixes each (so 6 prefixes in total). Assume we only have 4 IPs in use (and let's assume pre-allocate 0 for simplicity).

ipsPerPrefix := 16
usedIPsCount := 4
requiredIPPrefixes := (usedIPsCount + ipsPerPrefix - 1) / ipsPerPrefix = 1

Now e loop over the ENIs:
1. First ENI: excessIPPrefixes = 0 + (2 - 1) = 1
2. Second ENI: excessIPPrefixes = 1 + (2 - 1) = 2
3. Third ENI: excessIPPrefixes = 2 + (2 - 1) = 3

However, there are potentially 5 excess prefixes in total. It doesn't make sense subtract `requiredIPPrefixes` (which is a global total) for every ENI.

---

Unrelated the the problem above:

Now that I understand the logic a bit better, I have to correct myself a bit. I think it would be better to only rely on the `excessIPs` and check if the excess IPs are contiguous within a prefix in `PrepareIPRelease`. Because the signal we're getting here doesn't actually tell us if the prefixes are actually free to be removed (i.e. are the 4 in-use IPs are all in different prefixes, are the all in the same prefix? With the above example, we could release anything from 2 to 5 prefixes, depending on what prefix the used IP belongs to).

**Review by gandro — COMMENTED** [review]
Thanks for reworking this. Unfortunately I still think the logic is off. I've left a few comments.

File: pkg/aws/eni/node.go (hunk 11 above)
Comment (hsalluri259) [reply pkg/aws/eni/node.go:154]: yes, agreed for both.

File: pkg/aws/eni/node.go (hunk 12 above)
Comment (hsalluri259) [reply pkg/aws/eni/node.go]: Right, as you mentioned in bullet `#2` and `#3`, we are adding IP addresses that belong to IPPrefixes as well. The problem with that is, we can not call `ReleaseIPs` with IP addresses that belong to IPPrefixes. So I used a second variable to store invidual IP addresses so that we don't have to figure out which IP address to release and which one to ignore. Once IPPrefixes are unassigned, I am updating my `IPsToRelease` with `StandaloneIPs` if it is not empty. From what I have seen is, secondary IPs will be assigned when operator sees there are no more IPPrefixes to assign and since I used a separate variable `StandaloneIPs` when IPPrefixes are in use, I updated `a.release.IPsToRelease = a.release.StandalonePrivateIPs`  inside `if len(a.release.IPPrefixesToRelease) > 0`. If IPPrefixes are not in use, then `StandalonePrivateIPs` will be empty and `a.release.IPPrefixesToRelease` has the Individual IP addresses that need to be released. Please let me know if I missed anything.

File: pkg/aws/eni/node.go (hunk 14 above)
Comment (hsalluri259) [reply pkg/aws/eni/node.go]: Yes, I think in the first iteration of releasing IPPrefixes, it can release at max 3 prefixes. Then operator have to do one more iteration and release 2 more prefixes. So it requires 2 operations with this math instead of 1. I think that is because I had only one ENI on my cluster, so that math came. Now I need to think about this case as well. Thanks for pointing it. I will check on that.

File: pkg/aws/eni/node.go (hunk 12 above)
Comment (gandro) [reply pkg/aws/eni/node.go]: >  The problem with that is, we can not call ReleaseIPs with IP addresses that belong to IPPrefixes.

Yes, we don't want to call `UnassignPrivateIpAddresses` on those IPs belonging to prefixes - but why can we not add the secondary IPs to that list? 

In particular I think it's important that _all_ release candidates *are* added to `ReleaseAction.IPsToRelease` - because otherwise `handleIPRelease` won't do the handshake for them (which would cause to in-use IPs being removed). To avoid calling `UnassignPrivateIpAddresses` for IPs belonging to a prefix we can just check if they are part of a prefix or not in `Node.ReleaseIPs`. No need to have a separate `StandalonePrivateIPs` field.

---

Note that `StandalonePrivateIPs` currently also is populated unconditionally if there are excess prefixes. You don't check if they are in use, and you don't check if they are excess. We always try to release them if there are excess prefixes - which I believe is wrong.

File: pkg/aws/eni/node.go (hunk 14 above)
Comment (gandro) [reply pkg/aws/eni/node.go]: I strongly recommend _not_ trying to compute the number of excess prefixes- and instead rely making sure the `calculateExcessIPs` returns the correct number _of IPs_ when using prefixes. And then in `PrepareIPRelease` actually figure out what prefixes are in use and which can be released - without computing a number for the prefixes first.

Because to compute the _correct_ number you need to check what prefix the used IPs belong to. In the above example, the number of excess prefixes could be anything from 2 to 5.

**Comment by gandro** [comment]
To put my feedback in a single post, here's my propsoed approach:

1. Let's not try to compute the number of excess prefixes. It's not possible to do so without checking what IP belongs to what prefix. Instead, let's make sure `calculateExcessIPs` returns the correct number when using prefix delegation (which I think it might already do).
2. If we detect excess IPs (_not_ prefixes), let's iterate over all used addresses in `PrepareIPRelease` and check if there are any prefixes which do not contain any used IPs. If so, let's use those free prefixes as candiatates for release.
3. Let's make sure that `ReleaseAction` can release both standalone IPs and prefixes at the same time.

File: pkg/aws/eni/node.go (hunk 14 above)
Comment (hsalluri259) [reply pkg/aws/eni/node.go]: Yes, I agree. That was my first approach until it caused resolve-release IP prefix loop. 
The reason I had to calculate excess prefixes is, for example: I have 1 ipprefix where 9 IP addresses are used. With preallocate 8, operator adds another IPprefix to resolve IP deficit of node. But `calculateExcessIPs` returns `excessIPs: 8` then checks if the newly added prefix is in use or not. If none of the IP addresses are in use then it will release causing release IPprefix and resolve IP deficit loop. 
I see we are using two different logics for resolving IP deficit.
```
// while resolving IP deficit, we calculate needed IPs on existing prefix
available=16 used=9 neededIPs=1 

// while calculating excess IPs
available=32 used=16 preallocate=8, excessIPs=8
```
while both logics are valid, the below math from [ipam/node.go](https://github.com/cilium/cilium/blob/main/pkg/ipam/node.go#L378) doesn't work for IPPrefixes at the moment which is causing release and resolve IPprefix loop. 
```
excessIPs = max(availableIPs-usedIPs-preAllocate-maxAboveWatermark, 0)
```
Because we have `calculateExcessIPs` function in [ipam/node.go](https://github.com/cilium/cilium/blob/main/pkg/ipam/node.go#L378) I am not sure if it knows ipprefixes are in use or not. I will check how can I use `calculateExcessIPs` in case IPPrefixes rather than using `calculateExcessIPPrefixes`.

File: pkg/aws/eni/node.go (hunk 11 above)
Comment (hsalluri259) [reply pkg/aws/eni/node.go:154]: Added a check to ignore an ENI that is not managed by Cilium

File: pkg/aws/eni/node.go (hunk 13 above)
Comment (hsalluri259) [reply pkg/aws/eni/node.go]: Would you be able to help me understand how `maxAboveWatermark` is used. Currently by default I think it's 0. So my logic is not using it yet.

File: pkg/aws/eni/node.go (hunk 14 above)
Comment (hsalluri259) [reply pkg/aws/eni/node.go]: I opened an issue #39904 where Cilium-operator incorrectly calculated when both IPPrefix and IPaddresses are in use, but only IP addresses need to be released. My latest commit addresses that.
1. when both IPPrefixes(1) and IPaddresses(4) need to be released. 
```
IPsToRelease:[100.66.203.58 100.66.203.59 100.66.203.60 100.66.203.48 100.66.203.49 100.66.203.55 100.66.203.51 100.66.203.62 100.66.203.63 100.66.203.54 100.66.203.57 100.66.203.61 100.66.203.50 100.66.203.52 100.66.203.53 100.66.203.56 100.66.206.144 100.66.207.250 100.66.206.193 100.66.206.41] IPPrefixesToRelease:[100.66.203.48/28]}"
```
2. When only IPPrefixes(1) need to be released
```
IPsToRelease:[100.66.202.131 100.66.202.138 100.66.202.141 100.66.202.128 100.66.202.137 100.66.202.139 100.66.202.129 100.66.202.134 100.66.202.130 100.66.202.132 100.66.202.133 100.66.202.135 100.66.202.136 100.66.202.140 100.66.202.142 100.66.202.143] IPPrefixesToRelease:[100.66.202.128/28]
```
4. when only IP addresses(4) need to be released
```
IPsToRelease:[100.66.206.144 100.66.207.250 100.66.206.193 100.66.206.41] IPPrefixesToRelease:[]}
```
This do not calculate IPPrefixes, but it still has to calculate `remainingExcessIPs` after getting `excessIPS` from below math.  `remainingExcessIPs` must be calculated each prefix in order to prevent releasing IPPrefix added to resolve IPdeficit. And `maxAboveWatermark` I didn't use it because we already used it once while calculating `excessIPs`, I think we do not want to use it twice. 
```
excessIPs = max(availableIPs-usedIPs-preAllocate-maxAboveWatermark, 0)
````
Please let me know your thoughts. Thank you!

File: pkg/aws/eni/node.go [hunk 15]
```diff
@@ -193,22 +240,71 @@ func (n *Node) PrepareIPRelease(excessIPs int, scopedLog *slog.Logger) *ipam.Rel
...
+		return err
+	}
+
+	return nil
+
+}
+
+// Get Individual IPs that do not belong to any IPPrefix
+func (n *Node) GetIndividualIPs(ipPrefixes, ipAddresses []string) (individualIPs []string) {
+	// individualIPs := []string{}
```
Comment (gandro) [inline pkg/aws/eni/node.go]: nit: stray commented out code

File: pkg/aws/eni/node.go [hunk 16]
```diff
@@ -193,22 +240,71 @@ func (n *Node) PrepareIPRelease(excessIPs int, scopedLog *slog.Logger) *ipam.Rel
...
+	if err := n.manager.api.UnassignENIPrefixes(ctx, r.InterfaceID, r.IPPrefixesToRelease); err != nil {
+		return err
+	}
+
+	return nil
+
+}
+
+// Get Individual IPs that do not belong to any IPPrefix
+func (n *Node) GetIndividualIPs(ipPrefixes, ipAddresses []string) (individualIPs []string) {
```
Comment (gandro) [inline pkg/aws/eni/node.go]: nit: This should be a free-standing function

File: pkg/aws/eni/node.go [hunk 17]
```diff
@@ -153,22 +153,69 @@ func (n *Node) PrepareIPRelease(excessIPs int, scopedLog *slog.Logger) *ipam.Rel
...
-			continue
+		matchedIPs := []string{}
+		if len(ipPrefixes) > 0 {
+			usedIPs := n.k8sObj.Status.IPAM.Used
+			unusedIPPrefixes := []string{}
+
+			// Identify unused IP prefixes to release
+			for _, prefix := range ipPrefixes {
+				// Prevent removing IPPrefix added to resolve IP deficit.
+				remainingExcessIps := excessIPs - len(unusedIPPrefixes)*option.ENIPDBlockSizeIPv4
```
Comment (gandro) [inline pkg/aws/eni/node.go]: So something I just realized now (apologies, should have looked more closely earlier) is that the `ReleaseAction` can only release things from a single ENI. It seems that the existing non-prefix aware code picks the ENI with the most unused IPs.

It seems for prefixes, we don't do that - instead we do this `remainingExcessIps` calculation here. However, I think this will lead to a situation where we only pick one ENI whenever we reach the threshold here.

How hard would it be to mirror the logic below where we pick the ENI with the most excess prefixes?

File: pkg/aws/eni/node.go (hunk 14 above)
Comment (gandro) [reply pkg/aws/eni/node.go]: I've commented on the issue itself. I didn't realize that all IPs of a prefix are considered in use if one of them is. Maybe we could change that? It only seems to be used for excess calcuation, so I think impact of changing `GetUsedIPWithPrefixes` is limitted.

File: pkg/aws/eni/node.go (hunk 17 above)
Comment (hsalluri259) [reply pkg/aws/eni/node.go]: I think it is the same case for prefixes as well per this line. We get IPPrefixes of that ENI to check if we can release any and then calculate `remainingExcessIps`. Once our `remainingExcessIps < blocksize(16)` then we stop looking for more prefixes. 
https://github.com/cilium/cilium/blob/main/pkg/aws/eni/node.go#L150
```
for _, eniId := range slices.Sorted(maps.Keys(n.enis)) {
		e := n.enis[eniId]
		ipPrefixes := e.Prefixes
		...
		...
		for _, prefix := range ipPrefixes {
		                // Prevent removing IPPrefix added to resolve IP deficit.
				remainingExcessIps := excessIPs - len(unusedIPPrefixes)*option.ENIPDBlockSizeIPv4
				if remainingExcessIps < option.ENIPDBlockSizeIPv4 {
					break
				}
				
```

File: pkg/aws/eni/node.go (hunk 16 above)
Comment (hsalluri259) [reply pkg/aws/eni/node.go]: Yes, agreed.

File: pkg/aws/eni/node.go (hunk 14 above)
Comment (hsalluri259) [reply pkg/aws/eni/node.go]: I think we shouldn't change that, I will give an example for what will happen if we do that.
Assume that we have an IPPrefix with, 
availableIPs=16, usedIPs=7, preAllocate=8, maxAboveWatermark=0
The above formula will give 
```
excessIPs = max(16-7-8-0, 0) = max(1, 0) = 1 which is correct
```
Then the operator will call `PrepareIPRelease` and realize we cannot release any prefix or individual IP address. By returning actual usedIPs instead of marking all 16IPs as used, we may increase load on operator as the operator will check each and every node continuously. With current logic of marking all 16 IPs as used, operator won't call `PrepareIPRelease` which is good.
So I am thinking to do this to respect `when IPPrefix delegation is not used`, so we won't release IPs added via PreAllocate. 
```
excessIPs = max(availableIPs-usedIPs-preAllocate-maxAboveWatermark, 0)
```
When IPPrefix delegation enabled then,
```
excessIPs = max(availableIPs-usedIPs-maxAboveWatermark, 0)
```
The reason for doing it is, we are marking entire prefix as used via `GetUsedIPWithPrefixes`. With this the above values will yield following result
```
availableIPs=16, usedIPs=16(7 IPs are used), preAllocate=8, maxAboveWatermark=0
excessIPs = max(16-16-0, 0) = 0 // Expected and correct because we cannot release individual IPs associated with prefix 
availableIPs=32, usedIPs=16(9 IPs are used actually), preAllocate=8, maxAboveWatermark=0
excessIPs = max(32-16-0, 0) = 16 // Correct but this prefix was added to resolve IP deficit via preAllocate = 8
```
At this point, operator will call `PrepareIPRelease` and see the below code and does nothing. So it won't release that extra IPPrefix added to resolve IP deficit. 
```
remainingExcessIps := excessIPs - len(unusedIPPrefixes)*option.ENIPDBlockSizeIPv4
if remainingExcessIps < option.ENIPDBlockSizeIPv4 {
	break
}
```

Comment (hsalluri259) [reply pkg/aws/eni/node.go]: My latest commit keeps `preAllocate` when IP prefix delegation is not enabled. When IP Prefix delegation is enabled, we set `preAllocate=0` to calculate ExcessIPs only since we assume the whole prefix is used even if one IP used in a prefix. I didn't change that. This way operator doesn't call `PrepareIPRelease` function unless there're IP addresses to release. If I changed `GetUsedIPWithPrefixes` to give only used IPs then operator would be calling `PrepareIPRelease` all the time from almost every node where `(availabileIps-usedIps-preAllocate) > 0`. Please check and let me know. Thank you!

File: pkg/aws/eni/node.go (hunk 17 above)
Comment (gandro) [reply pkg/aws/eni/node.go]: I'm not sure I understand - how does your logic pick the ENI with the _most_ free prefixes?

**Review by gandro — COMMENTED** [review]
Apologies for no feedback for a couple of days, I was out of office.  Thanks for addressing some of the feedback.

File: pkg/aws/eni/node.go (hunk 14 above)
Comment (gandro) [reply pkg/aws/eni/node.go]: I see. Thanks for explaining this. I understand now that `PrepareIPRelease` would be called more often than necessary if we changed `GetUsedIPWithPrefixes`. However, I also think ignoring pre-allocate is also wrong. We will have to find a different approach.

Let's assume the following example with the current implementation:

2 Prefixes (let's call them A and B). 16 IPs in-use on prefix A, 0 IPs in-use on prefix B. preAllocate=8, maxAboveWatermark=0.

```
availableIPs := 32
usedIPs := 16
preAllocate :=8
maxAboveWatermark := 0

# using new formula
excessIPs = max(availableIPs-usedIPs-maxAboveWatermark, 0) = max(16, 0) = 16
```

Now `PrepareIPRelease` is called and it decides to release the unused prefix. The prefix is released. Now `pre-allocate` is violated, because the node no longer has 8 spare IPs. `availableIPs:=16`

Next up, a maintenance action is triggered (this happens periodically), `calculateNeededIPs` uses the following formula:

```
neededIPs = preAllocate - (availableIPs - usedIPs) = 8 - (16-16) = 8
```

Because of this, the operator will now allocate a new prefix to the node again, because it wants to satisfy pre-allocate. So we will allocate again a new (unused) prefix to the node.

However, because `excessIPs` ignores pre-allocate, the new prefix will be released again. We are stuck in a release-allocate-release cycle.

Comment (hsalluri259) [reply pkg/aws/eni/node.go]: I agree with you. I thought my below code from this [line](https://github.com/cilium/cilium/blob/f4c18044577c3273a06511dad6f4766c19444db4/pkg/aws/eni/node.go#L179) had `<=` in if statement.
```
// Prevent removing IPPrefix added to resolve IP deficit.
remainingExcessIps := excessIPs - len(unusedIPPrefixes)*option.ENIPDBlockSizeIPv4
if remainingExcessIps < option.ENIPDBlockSizeIPv4 {
break
}
```
I think we have two options. 
1. Change the above if statement to `<=` so when operator sees `ExcessIPs=16`, it will not do anything.
2. Add `Preallocate` back to the `excessIPs` calculation. This will not release IPs in following scenarios with `preAllocate=8 default`.
      a. If there are `<9` Individual IPs to release, assume AvailableIps=23(including individual ips=7), PreAllocate=8, Used=16, then `excessIPs=max(23-8-16, 0) = max(-1, 0) = 0`. In this case we won't be able to call `PrepareIPRelease` unless this number exceeds PreAllocate even if we use Prefixes.
     b. If there are availableIPs=32, used=16(actual used are 8 but we mark entire prefix as used), preAllocate=8, `excessIPs=max(32-16-8,0)=max(8,0)=8` which is `8 <=ENIPDBlockSizeIPv4(16)` so operator won't release the prefix. I added that condition to prevent releasing IPPrefix which was added to resolve IP deficit when availableIPs=32, used=16(actual used are 9 but we mark entire prefix as used), preAllocate=8, `excessIPs=max(32-16-8,0)=max(8,0)=8`. In this case, we do not want to release Prefix. 
Please let me know if you think of a better way.

File: pkg/aws/eni/node.go (hunk 17 above)
Comment (hsalluri259) [reply pkg/aws/eni/node.go]: ah I see what I missed, I thought after sort the first ENI is going to be with most Prefixes to release. There is code to handle to select ENI with more IPs to release in individual IPs. I will test this by adding another ENI and get back to you. Thanks!

File: pkg/aws/eni/node.go (hunk 14 above)
Comment (hsalluri259) [reply pkg/aws/eni/node.go]: I see why I used `<` instead of `<=` in below condition
```
if remainingExcessIps < option.ENIPDBlockSizeIPv4 {
break
}
```
1. With `<` in place, operator will release IPPrefix added to resolve IP deficit when AvailableIPs=32, UsedIPs=16(actually 9 are used), PreAllocate=8. `ExcessIPs = 32 - 16 = 16`. The above condition will release Prefix which is not correct, causing release-add cycle. When usedIPs=16(actually 8 are used), AvailableIPs=32, `ExcessIPs= 32-16=16`. In this case, operator releases Prefix which is correct. 
2. With `<=` is in place, the above cases are reversed. 

I feel that we should use the previous function `calculateExcessIPPrefixes` to identify how many prefixes can be released. With that we don't have to change `ExcessIPs` existing formula.

File: pkg/aws/eni/node.go (hunk 17 above)
Comment (hsalluri259) [reply pkg/aws/eni/node.go]: I tested the current workflow. I added two ENIs to my node, first one is `eni-01a` with 2 Prefixes to release, the other is `eni-06c` has 2 prefixes but 1prefix to release. Because we are sorting the ENIs we will iterate through ENIs lexicographically. So even though I have `eni-01a` with 2 prefixes to release, operator will be releasing  1prefix from `eni-06c` first. Once that is done, then operator will be releasing 2prefixes from `eni-01a`. My logic doesn't pick the ENI with most free prefixes, but it eventually releases all free prefixes in all ENIs. In this case, operator added 2 prefixes from `eni-01a` then goes to next ENI which is `eni-06c`. Then override the prefixes with empty `eni-06c`. I am thinking to exit once I have a prefix from an ENI to release rather than override so in next iteration I will pick the other one. My question to you is, does the order really matter here since we release all prefixes eventually?

Comment (gandro) [reply pkg/aws/eni/node.go]: > My question to you is, does the order really matter here since we release all prefixes eventually?

It makes the code more consistent. As a reader of the function in two years, I will ask myself: Why are we releasing IPs on the ENI with the most IPs first, but not for prefixes. Is there a subtle reason for this? And I think there is no good reason to not pick the ENI with the most prefixes.

So my suggestion is:
- If it is easy to pick the ENI with the most prefixes, let's pick it
- If it is not easy to pick that ENI, let's add a comment to explain that we're doing a different logic for prefixes than we do for standalone IPs.

Comment (hsalluri259) [reply pkg/aws/eni/node.go]: Sounds good. I think it is possible to pick the ENI with the most prefixes. we don't need to override `r` object if new prefixes length is not greater than current `r.IPPrefixesToRelease`. Thanks!

Comment (hsalluri259) [reply pkg/aws/eni/node.go]: Although it was easy to find ENIs with most prefixes, it became complex when I had ENIs with IPPrefixes plus secondary IPs. So I tested with following test cases to see how the operator behaves. 
1. ENI 1: 1 Prefix, ENI 2: 1 prefix. Operator releases the ENI1 followed by ENI2 prefixes.
2. ENI 1: 1 Prefix + 4 secondary IPs to release, ENI2: 1prefix + 3 secondary IPs. In this case, ENI1 IPs are released first followed by ENI2 since ENI1 releases 20 IPs vs ENI2 with 19IPs.
3. ENI1: 1 prefix + 4IPs, ENI2: 1prefix + 5IPs. In this case, ENI2 IPs are released first followed by ENI1.
4. ENI1: I used prefix + 4 secondary IPs, ENI2: 5 individual IPs. In this case, ENI2 IPs are released first followed by ENI secondary IPs

Here are my observations after testing the cases outlined below:
1. Operator has to find the ENI with the max IP prefixes to release (Greedy Approach)
2. This needed extra iterations as I have to find an ENI with max IPs to release everytime. Operator has to check for all ENIs before releasing IPs/IPPrefixes from one ENI. For example: if I have n ENIs and the first ENI has the maximum IPs to release, but we check all ENIs before releasing one. This needs n iterations for each call to `PrepareIPRelease` for each node. 
3. Nested if-else branching to handle tests 2,3, and 4.

After weighing the trade-offs, I opted for the following approach:
1. Release from first ENI with IPs to release to reduce code complexity(Pragmatic Approach)
2. Releases IPs/prefixes faster in many common cases.
3. Avoids latency from scanning all ENIs when we find an ENI with IPs/IPPrefixes to release. So in this case, if we have n ENIs and the first ENI has IPs/Prefixes to release, we will be doing only one iteration. 


I’m now reconsidering whether we truly need to sort the ENIs lexicographically or select an ENI with the maximum number of IPs to release. Personally, I prefer a simpler approach that avoids sorting and doesn't rely on identifying the ENI with the most IPs, but I’m open to either direction. Thank you!
https://github.com/cilium/cilium/blob/main/pkg/aws/eni/node.go#L154

File: pkg/aws/eni/node.go (hunk 14 above)
Comment (hsalluri259) [reply pkg/aws/eni/node.go]: Following up on the Slack conversation with @gandro , I wanted to document the rationale behind the chosen approach, based on the two options I proposed below:

We evaluated two main strategies for handling excess IP release, particularly with `/28` prefixes (16 IPs per block):

**Approach 1 (Chosen):** Do not mark the entire IP prefix as "used" if only a subset of IPs are in use.
- **Continue to use Excess IP formula:** `ExcessIPs = max(AvailableIPs - UsedIPs - PreAllocate - MaxAboveWatermark, 0)`
- We avoid releasing a prefix unless `ExcessIPs >= BlockSize`, ensuring prefixes are only released when it's safe.
- **Benefits:**
  - More accurate `UsedIPs` calculation (no overestimation).
  - Simpler logic — no need for `calculateExcessIPPrefixes`.
  - Reduces waste of full prefixes and maintains enough IPs based on `PreAllocate`.

**Example Outcomes:**
- If `UsedIPs = 9`, `AvailableIPs = 32`, and `PreAllocate = 8`, `ExcessIPs = 15` → **prefix not released** ✅
- If `UsedIPs = 8`, `AvailableIPs = 32`, and `PreAllocate = 8`, `ExcessIPs = 16` → **prefix released** ✅

**Approach 2 (Not chosen):** Continue marking entire prefix as used and use adjusted logic to release based on actual usage:
```go
requiredIPs := actualUsedIPs + preAllocate + maxAboveWatermark
remainingIPs := availableIPs - (len(prefixesToRelease) * BlockSize)
if remainingIPs >= requiredIPs {
    // safe to release
}
```
we both agreed to use Approach 1 for its accuracy and simplicity. Thank you for your feedback!

File: pkg/aws/eni/node.go [hunk 18]
```diff
@@ -203,12 +263,51 @@ func (n *Node) PrepareIPRelease(excessIPs int, scopedLog *slog.Logger) *ipam.Rel
...
+	if err := n.manager.api.UnassignENIPrefixes(ctx, r.InterfaceID, r.IPPrefixesToRelease); err != nil {
+		return err
+	}
+
+	return nil
+
+}
+
+// Get Individual IPs that do not belong to any IPPrefix
+func GetIndividualIPs(ipPrefixes, ipAddresses []string) (individualIPs []string) {
```
Comment (gandro) [inline pkg/aws/eni/node.go]: nit: Consider making this a private function

File: pkg/ipam/node.go [hunk 19]
```diff
@@ -482,18 +481,11 @@ func (n *Node) recalculate(ctx context.Context) {
 		n.stats.IPv4.AssignedStaticIP = stats.AssignedStaticIP
 	}
 
-	// Get used IP count with prefixes included
-	usedIPForExcessCalc := n.stats.IPv4.UsedIPs
-	if n.ops.IsPrefixDelegated() {
-		usedIPForExcessCalc = n.ops.GetUsedIPWithPrefixes()
```
Comment (gandro) [inline pkg/ipam/node.go:488]: This function (`GetUsedIPWithPrefixes`) is otherwise unused, right? In that case, let's remove it

File: pkg/aws/eni/node.go (hunk 17 above)
Comment (gandro) [reply pkg/aws/eni/node.go]: Thanks for looking into this. I agree that it is not a big deal and that releasing the first ENI might be good enough, though I still slightly prefer being consistent for both PD and Non-PD ENIs.

A few notes:
- "This needs n iterations for each call to PrepareIPRelease for each node." - this is not a big deal I think. We already do it for Non-PD ENIs and `n` is at most 16. 
- "I’m now reconsidering whether we truly need to sort the ENIs lexicographically or select an ENI with the maximum number of IPs to release" - not sorting the ENIs means iteration order is random (because map key iteration order is random). I think this will lead to confusing behavior. Always picking the lexicographically first ENI is much more understandable. And again, sorting up to 16 values is not that expensive.

File: pkg/aws/eni/node.go [hunk 20]
```diff
@@ -153,9 +153,74 @@ func (n *Node) PrepareIPRelease(excessIPs int, scopedLog *slog.Logger) *ipam.Rel
...
+					if !found {
+						unusedIPPrefixes = append(unusedIPPrefixes, prefix)
+						for _, ipStr := range e.Addresses {
+							ip := netip.MustParseAddr(ipStr)
+							if prefixAddr.Contains(ip) {
+								matchedIPs = append(matchedIPs, ipStr)
+							}
+						}
+						// Reduce excessIPs with option.ENIPDBlockSizeIPv4 number of IPs after adding a prefix
+						excessIPs = excessIPs - option.ENIPDBlockSizeIPv4
```
Comment (gandro) [inline pkg/aws/eni/node.go:205]: nit: It is correct as is, however consider creating a copy of this variable per ENI iteration loop to keep track of how many IPs are still excess. This only works because we are guaranteed to return a release action for this ENI below (i.e. `len(unusedIPPrefixes) > 0`)

If we do not return a release action (i.e. later decide to not release anything on this ENI), then excess IPs must not be modified for the next iteration.

File: pkg/ipam/node.go [hunk 21]
```diff
@@ -662,12 +657,13 @@ func (n *Node) determineMaintenanceAction() (*maintenanceAction, error) {
 	a := &maintenanceAction{}
 
 	stats := n.Stats()
-
 	// Validate that the node still requires addresses to be released, the
 	// request may have been resolved in the meantime.
 	if n.manager.releaseExcessIPs && stats.IPv4.ExcessIPs > 0 {
 		a.release = n.ops.PrepareIPRelease(stats.IPv4.ExcessIPs, n.logger.Load())
-		return a, nil
+		if a.release != nil {
```
Comment (gandro) [inline pkg/ipam/node.go]: I think this is incomplete - as is, `PrepareIPRelease` will never return `nil` for the ENI implementation, even if there is nothing to release.

Consider either having `PrepareIPRelease` return `nil` if no prefix could be released - or better - modify this to check `a.release != nil && len(a.release.IPsToRelease) + len(a.release.IPPrefixesToRelease) > 0`. This ensures that we only emit a release action if there is actually something to release.

**Review by gandro — COMMENTED** [review]
Awesome progress. A few minor bits of feedback left

File: pkg/aws/eni/node.go (hunk 20 above)
Comment (hsalluri259) [reply pkg/aws/eni/node.go:205]: Yes, we do not modify excessIPs unless an IPPrefix added to `unusedIPPrefixes` to release. This will not modify if there is no prefix to release from current ENI before checking next ENI.  Initially I had a separate variable, but then I realized it was not needed.

```go

if !found {
	unusedIPPrefixes = append(unusedIPPrefixes, prefix)					
        excessIPs = excessIPs - option.ENIPDBlockSizeIPv4
}
```

File: pkg/ipam/node.go (hunk 19 above)
Comment (hsalluri259) [reply pkg/ipam/node.go:488]: yes, per our slack conversation you said it is used somewhere else and keep it. So I didn't remove it, but I will remove it. Thanks for checking!

File: pkg/aws/eni/node.go (hunk 18 above)
Comment (hsalluri259) [reply pkg/aws/eni/node.go]: done

File: pkg/ipam/node.go (hunk 19 above)
Comment (hsalluri259) [reply pkg/ipam/node.go:488]: removed it

File: pkg/ipam/node.go (hunk 21 above)
Comment (hsalluri259) [reply pkg/ipam/node.go]: Since we do not return `nil` I replaced the condition as below,
```go
if len(a.release.IPsToRelease) > 0 {
			return a, nil
}
```
This way anytime we have either IPPrefixes or IPaddresses to release, this will have IPaddresses.

File: pkg/ipam/node.go [hunk 22]
```diff
@@ -662,12 +657,13 @@ func (n *Node) determineMaintenanceAction() (*maintenanceAction, error) {
 	a := &maintenanceAction{}
 
 	stats := n.Stats()
-
 	// Validate that the node still requires addresses to be released, the
 	// request may have been resolved in the meantime.
 	if n.manager.releaseExcessIPs && stats.IPv4.ExcessIPs > 0 {
 		a.release = n.ops.PrepareIPRelease(stats.IPv4.ExcessIPs, n.logger.Load())
-		return a, nil
+		if len(a.release.IPsToRelease) > 0 {
```
Comment (gandro) [inline pkg/ipam/node.go]: You still need to check for `nil`, in addition to checking if `a.release` is empty. The non-ENI implementation will return `nil`, causing a nil-pointer panic.

Comment (hsalluri259) [reply pkg/ipam/node.go]: Added it back. I thought it is not needed anymore. Thank you!

**Comment by gandro** [comment]
I think this is now in a decent state, assuming it passes CI. Could you squash all your commits into one so we have a clean history once we merged?

**Comment by hsalluri259** [comment]
> I think this is now in a decent state, assuming it passes CI. Could you squash all your commits into one so we have a clean history once we merged?

I've squashed all the commits into one, and the CI checks have passed. Please let me know if there's anything else needed before merging.

**Comment by gandro** [comment]
I'll also rebase on `main` before we run CI

File: pkg/aws/eni/node.go [hunk 23]
```diff
@@ -153,9 +153,74 @@ func (n *Node) PrepareIPRelease(excessIPs int, scopedLog *slog.Logger) *ipam.Rel
...
+					}
+
+					if excessIPs < option.ENIPDBlockSizeIPv4 {
+						break
+					}
+				}
+			}
+
+			secondaryIPs := getIndividualIPs(ipPrefixes, e.Addresses)
```
Comment (gandro) [inline pkg/aws/eni/node.go:214]: Argh, sorry I missed this. But this is unconditionally releasing all secondary IPs without checking if we go under `excessIPs`. That's not correct, right?

Comment (hsalluri259) [reply pkg/aws/eni/node.go:214]: Thank you for catching it! Yes, agreed. As discussed I added a check to prevent releasing secondary IPs those are in use.

File: pkg/aws/eni/node.go [hunk 24]
```diff
@@ -154,8 +154,84 @@ func (n *Node) PrepareIPRelease(excessIPs int, scopedLog *slog.Logger) *ipam.Rel
...
+			if len(unusedIPPrefixes) > 0 || len(secondaryIPs) > 0 {
+				r.InterfaceID = eniId
+				r.PoolID = ipamTypes.PoolID(e.Subnet.ID)
+				r.IPPrefixesToRelease = unusedIPPrefixes
+				if len(secondaryIPs) > 0 {
+					secondaryIPs = getUnusedIPs(usedIPs, secondaryIPs, e.IP)
+					maxReleaseOnENI := min(excessIPs, len(secondaryIPs))
```
Comment (gandro) [inline pkg/aws/eni/node.go:221]: I think `excessIPs` can go below zero, in which case `secondaryIPs[:maxReleaseOnENI]` will panic. Please use a guard like `max(min(excessIPs, len(secondaryIPs), 0)`.

**Review by gandro — COMMENTED** [review]
Thanks for addressing the latest feedback. This looks good to me ~, only last minor issue in the most recent code.~

Btw, you can squash and rebase on main directly next time, no need to keep individual commits for such small changes.

File: pkg/aws/eni/node.go (hunk 24 above)
Comment (gandro) [reply pkg/aws/eni/node.go:221]: Actually, since we only subtract `if excessIPs >= option.ENIPDBlockSizeIPv4`, `excessIPs` cannot go below zero. So this is fine.

Comment (gandro) [reply pkg/aws/eni/node.go:221]: Actually, on closer inspection, `excessIPs` cannot go below zero since we break the above loop if `excessIPs < option.ENIPDBlockSizeIPv4`. So this is fine.

**Review by gandro — APPROVED** [review]
On closer inspection, this looks good to me, thanks! Please squash and rebase, then we can get CI running and get this merged once the feature freeze is over.

**Comment by hsalluri259** [comment]
@gandro I see a couple of CI checks are failing. I am not sure if it is related or not. Appreciate your help with them.

**Comment by gandro** [comment]
> @gandro I see a couple of CI checks are failing. I am not sure if it is related or not. Appreciate your help with them.

They are unrelated, since both of these tests are not running in ENI mode. I'll restart them.

**Comment by gandro** [comment]
This needs an ACK from alibabacloud and azure

**Review by christarazi — APPROVED** [review]

File: pkg/ipam/node.go [hunk 25]
```diff
@@ -482,18 +481,11 @@ func (n *Node) recalculate(ctx context.Context) {
...
-	// Get used IP count with prefixes included
-	usedIPForExcessCalc := n.stats.IPv4.UsedIPs
-	if n.ops.IsPrefixDelegated() {
-		usedIPForExcessCalc = n.ops.GetUsedIPWithPrefixes()
-	}
-
 	n.stats.IPv4.AvailableIPs = len(n.ipv4Alloc.available)
 	n.stats.IPv4.NeededIPs = calculateNeededIPs(n.stats.IPv4.AvailableIPs, n.stats.IPv4.UsedIPs, n.getPreAllocate(), n.getMinAllocate(), n.getMaxAllocate())
-	n.stats.IPv4.ExcessIPs = calculateExcessIPs(n.stats.IPv4.AvailableIPs, usedIPForExcessCalc, n.getPreAllocate(), n.getMinAllocate(), n.getMaxAboveWatermark())
+	n.stats.IPv4.ExcessIPs = calculateExcessIPs(n.stats.IPv4.AvailableIPs, n.stats.IPv4.UsedIPs, n.getPreAllocate(), n.getMinAllocate(), n.getMaxAboveWatermark())
```
Comment (tamilmani1989) [inline pkg/ipam/node.go:487]: i see we are changing to `n.stats.IPv4.UsedIPs`. is there any diff between `usedIPForExcessCalc` and `n.stats.IPv4.UsedIPs`

Comment (hsalluri259) [reply pkg/ipam/node.go:487]: Earlier we were doing the below for AWS ENI.
```
// Get used IP count with prefixes included
	usedIPForExcessCalc := n.stats.IPv4.UsedIPs
	if n.ops.IsPrefixDelegated() {
		usedIPForExcessCalc = n.ops.GetUsedIPWithPrefixes()
```
We no longer use `n.ops.GetUsedIPWithPrefixes()` as it was not giving accurate ExcessIPs for AWS ENI. It became simple `n.stats.IPv4.UsedIPs` for AWS ENI as well. This behavior/value same as earlier for other cloud except for not using the variable `usedIPForExcessCalc`

**Comment by hsalluri259** [comment]
@gandro I restored these single-line comments as we didn't change the ExcessIPs calculation. 
https://github.com/cilium/cilium/commit/b49935cf1b5e2d7a6aff90974f279479a2116b31

**Review by tamilmani1989 — APPROVED** [review]

**Comment by joestringer** [comment]
Please rebase your PR against the tip of the `main` branch. Some of the test failures appear to be caused by the PR being quite out-of-date vs the tests that are run (which are pulled from the latest `main` branch).

**Comment by hsalluri259** [comment]
> /test
I rebased it again as I saw couple of tests failing. Please run the tests again.
