### PR TITLE
envoy: Keep track of proxy listeners separately

### LINKED ISSUE #16375: Misbehaving L7Proxy makes Cilium API Unable to create new endpoint
## Bug report

**General Information**

- Cilium version:
Client: 1.10.0 952d9d3 2021-05-19T18:42:32+02:00 go version go1.16.4 linux/amd64
Daemon: 1.10.0 952d9d3 2021-05-19T18:42:32+02:00 go version go1.16.4 linux/amd64

- Kernel version (run `uname -a`)
Linux itsedcll-bb4070 5.10.0-1026-oem #27-Ubuntu SMP Thu May 6 07:19:13 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, ...)
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:28:42Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}

- Link to relevant artifacts (policies, deployments scripts, ...)
```
helm upgrade -i cilium cilium/cilium \
--version 1.10.0 \
--namespace kube-system \
--set kubeProxyReplacement=strict \
--set k8sServiceHost=k8s-api.dcll.cnp.ikeadt.com \
--set k8sServicePort=6443 \
--set localRedirectPolicy=true \
--set prometheus.enabled=true \
--set operator.prometheus.enabled=true \
--set hubble.enabled=true \
--set hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,http}" \
--set hubble.relay.enabled=true \
--set hubble.ui.enabled=true \
--set containerRuntime.integration=containerd \
--set tunnel=disabled \
--set ipam.mode=kubernetes \
--set nativeRoutingCIDR=10.62.128.0/19 \
--set devices=client0 \
--set endpointRoutes.enabled=true

```
- Generate and upload a system zip:
I have run it and tried to upload it to this issue but with out any luck. Maybe it is to large...

**How to reproduce the issue**

1. Install cilium with the above helm command
2. run `cilium connectivity test` && `kubectl delete ns cilium-test` a few times then after a few runs Cilium API becomes unavailable. And pods fails to be scheduled because of Cilium API timetouts
```
  Warning  FailedCreatePodSandBox  46m                 kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "2788700c30f493be1d6c729fc54d79700dbe48e7e1160a046710c9479b248a6a": Unable to create endpoint: Cilium API client timeout exceeded
```

At this point in time I am able to curl to 2 of 6 of the cilium-agent endpoints:
``` 
curl http://10.62.64.21:9095 -i
HTTP/1.1 404 Not Found
date: Mon, 31 May 2021 11:54:34 GMT
server: envoy
content-length: 0
```
On the working nodes I cannot curl the API:
```
curl http://10.62.64.23:9095 -i
curl: (7) Failed to connect to 10.62.64.23 port 9095: Connection refused
``` 
If I delete the pods on the broken nodes, they come back online for a little while and then the become healthy again.

The `cilium status` reports all healthy 
The same is if I run `cilium status` in the individual pods they also report healthy

### LINKED ISSUE #16667: Pod creating blocked with `Error regenerating endpoint: proxy state changes failed`
<!--

If you have usage questions, please try the [slack
channel](http://cilium.io/slack) and see the [FAQ](https://goo.gl/qG2YmU)
first.
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Choose either "Proposal" or "Bug report"

-->

## Bug report

Few hours after installation of cilium, one pod of cilium started to report error `regeneration recovery failed`.
On this node, it is not possible to schedule new pods until cilium is restarted.


`cilium status` is reporting error `controller endpoint-3282-regeneration-recovery is failing since 15m48s (788x): regeneration recovery failed`


Pod is stuck in state `ContainerCreating`
`kubectl -n cilium-test describe po client-8655c47fd7-s2x9r`:
```
  Warning  FailedCreatePodSandBox  39m                 kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "e5e8e6995eb73081cb01b908dca450ddedb749ce3a045ef0a3f87f9b232e9849": Unable to create endpoint: Cilium API client timeout exceeded
  Warning  FailedCreatePodSandBox  76s (x22 over 37m)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "90a4f585a4e543edf81e37f0305d9cbcb5b1f75308303c2ecf079800cc5409e2": Unable to create endpoint: Cilium API client timeout exceeded
```

<!--

Important: For security related issues: We strongly encourage you to report
security vulnerabilities to our private security mailing list:
security@cilium.io - first, before disclosing them in any public forums.

-->

**General Information**

- Cilium version (run `cilium version`)
```
Client: 1.10.0 952d9d3 2021-05-19T18:42:32+02:00 go version go1.16.4 linux/amd64
Daemon: 1.10.0 952d9d3 2021-05-19T18:42:32+02:00 go version go1.16.4 linux/amd64

```
- Kernel version (run `uname -a`)
```
Linux dc1-k8s-02 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Linux dc1-k8s-03 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Linux dc1-k8s-04 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Linux dc1-inf-15 5.4.0-74-generic #83~18.04.1-Ubuntu SMP Tue May 11 16:01:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Linux dc3-8gpu-32 5.4.0-74-generic #83~18.04.1-Ubuntu SMP Tue May 11 16:01:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
- Orchestration system version in use (e.g. `kubectl version`, ...)
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Configuration:
    
  Nodes:
  - 3 masters
  - 2 nodes

  Cilium:
  - vxlan enabled
  - etcd cluster for cilium (one instance by master)
  - 3 operators (one by master)
- Cilium Status
```
    /¯¯\
 /¯¯\__/¯¯\    Cilium:         1 errors
 \__/¯¯\__/    Operator:       OK
 /¯¯\__/¯¯\    Hubble:         OK
 \__/¯¯\__/    ClusterMesh:    disabled
    \__/
                                                                                                                                                                                                                                             
DaemonSet         cilium             Desired: 5, Ready: 5/5, Available: 5/5
Deployment        cilium-operator    Desired: 3, Ready: 3/3, Available: 3/3
Deployment        hubble-relay       Desired: 1, Ready: 1/1, Available: 1/1
Containers:       cilium             Running: 5
                  cilium-operator    Running: 3
                  hubble-relay       Running: 1
Image versions    hubble-relay       quay.io/cilium/hubble-relay:v1.10.0@sha256:e92e6778c71aa9e181618d61e9403761ad061c3960a9203aa2cf8e6cde95c9d7: 1
                  cilium             quay.io/cilium/cilium:v1.10.0@sha256:587627d909ffe0418c0bd907516496844867a21812946af82096d367760e4c1e: 5
                  cilium-operator    quay.io/cilium/operator-generic:v1.10.0@sha256:65143311a62a95dbe23c69ff2f624e0fdf030eb225e6375d889da66a955dd828: 3
Errors:           cilium             cilium-bn9k4    controller endpoint-3282-regeneration-recovery is failing since 15m48s (788x): regeneration recovery failed
```
- Link to relevant artifacts (policies, deployments scripts, ...)
No policy.
Deployment of treafik and metallb
- Generate and upload a system zip:

(Have to use `xz` to reduce size from 44MB to 16MB)
[cilium-sysdump-20210628-120117.tar.xz.zip](https://github.com/cilium/cilium/files/6726908/cilium-sysdump-20210628-120117.tar.xz.zip)


**How to reproduce the issue**

Runs connectivity tests twice:
- `kubectl delete ns cilium-test ; cilium connectivity test`
- `kubectl delete ns cilium-test ; cilium connectivity test`

When cilium pod is restarted, it temporary fixes the issue.


**Details**

Cilium pod correctly receives the request but it is failing with:
`kubectl -n kube-system logs cilium-bn9k4`
```
2021-06-28T12:01:17.357326306Z level=warning msg="Creation of endpoint failed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=73 endpointID=3757 error="timeout while waiting for initial endpoint generation to complete" identity=27434 ipv4= ipv6= k8sPodName=/ subsys=daemon
2021-06-28T12:01:17.357343126Z level=debug msg="End of create request" containerID= datapathPolicyRevision=0 desiredPolicyRevision=73 endpointID=3757 identity=27434 ipv4= ipv6= k8sPodName=/ subsys=daemon
2021-06-28T12:01:17.357349938Z level=info msg="API call has been processed" error="timeout while waiting for initial endpoint generation to complete" name=endpoint-create processingDuration=5m30.059449528s subsys=rate totalDuration=5m30.059535635s uuid=d83be27b-4db7-4c1f-8ec7-2cc5ce761214 waitDurationTotal="64.286µs"
```


Regeneration is failing with:
`kubectl -n kube-system logs cilium-bn9k4`
```
2021-06-28T12:01:17.300002355Z level=debug msg="Completed endpoint regeneration with no pending regeneration requests" code=OK containerID= datapathPolicyRevision=0 desiredPolicyRevision=73 endpointID=3757 endpointState=ready identity=27434 ipv4= ipv6= k8sPodName=/ policyRevision=0 subsys=endpoint type=0
2021-06-28T12:01:17.300037547Z level=warning msg="Regeneration of endpoint failed" bpfCompilation=0s bpfLoadProg=152.954367ms bpfWaitForELF="4.658µs" bpfWriteELF="899.396µs" containerID= datapathPolicyRevision=0 desiredPolicyRevision=73 endpointID=3757 error="Error while configuring proxy redirects: proxy state changes failed: context deadline exceeded" identity=27434 ipv4= ipv6= k8sPodName=/ mapSync="137.402µs" policyCalculation="80.937µs" prepareBuild="423.455µs" proxyConfiguration="10.854µs" proxyPolicyCalculation="51.7µs" proxyWaitForAck=5m29.792614184s reason="updated security labels" subsys=endpoint total=5m30.000731126s waitingForCTClean=51.258622ms waitingForLock=718ns
2021-06-28T12:01:17.300051594Z level=debug msg="Error regenerating endpoint: Error while configuring proxy redirects: proxy state changes failed: context deadline exceeded" code=Failure containerID= datapathPolicyRevision=0 desiredPolicyRevision=73 endpointID=3757 endpointState=ready identity=27434 ipv4= ipv6= k8sPodName=/ policyRevision=0 subsys=endpoint type=200
```

I checked for etcd connection:
```
2021-06-28T12:00:37.077455595Z level=debug msg="Distributed lock successful, etcd has quorum" config=/var/lib/etcd-config/etcd.config endpoints="[https://192.168.170.210:2279 https://192.168.170.211:2279 https://192.168.170.28:2279]" subsys=kvstore
2021-06-28T12:00:37.077507299Z level=debug msg="Checking status to etcd endpoint https://192.168.170.210:2279" config=/var/lib/etcd-config/etcd.config endpoints="[https://192.168.170.210:2279 https://192.168.170.211:2279 https://192.168.170.28:2279]" subsys=kvstore
2021-06-28T12:00:37.087813398Z level=debug msg="Checking status to etcd endpoint https://192.168.170.211:2279" config=/var/lib/etcd-config/etcd.config endpoints="[https://192.168.170.210:2279 https://192.168.170.211:2279 https://192.168.170.28:2279]" subsys=kvstore
2021-06-28T12:00:37.098259674Z level=debug msg="Checking status to etcd endpoint https://192.168.170.28:2279" config=/var/lib/etcd-config/etcd.config endpoints="[https://192.168.170.210:2279 https://192.168.170.211:2279 https://192.168.170.28:2279]" subsys=kvstore
```

`cilium` & `cilium-operator` pods receives heartbeat notification:
```
 level=debug msg="Received update notification of heartbeat" subsys=kvstore
```

### PR DESCRIPTION
**Pull request by jrajahalme**
Since the addition of Envoy prometheus listener it has been possible
to have non-proxy listeners configured with Envoy. Waiting for Envoy
N/ACKs must be disabled when no proxy listeners are configured, even
if a prometheus listener may still be configured.

Without this fix adding endpoints may fail due to not receiving N/ACKs
from Envoy after Envoy has been started due to an L7 network policy,
and this policy is removed, if the Cilium option
'--proxy-prometheus-port' is also configured.

Fixes: #12949
Fixes: #16375
Fixes: #16667

```release-note
Envoy configuration with `--proxy-prometheus-port` is fixed.
```

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

File: pkg/envoy/server.go [hunk 1]
```diff
@@ -114,6 +114,9 @@ type XDSServer struct {
 	// Value holds the number of redirects using the listener named by the key.
 	listeners map[string]*Listener
 
+	// proxyListeners is the count of redirection proxy listeners in 'listeners'
```
Comment (kkourt) [inline pkg/envoy/server.go]: Maybe some additional context for the comment. E.g.,:

```suggestion
	// proxyListeners is the count of redirection proxy listeners in 'listeners'
	// When this is zero, cilium should not wait for NACKs/ACKs from envoy.
	// This value is different from len(listeners) due to non-proxy listeners (e.g., prometheus listener)
```

File: pkg/envoy/server.go [hunk 2]
```diff
@@ -440,21 +443,24 @@ func (s *XDSServer) AddMetricsListener(port uint16, wg *completion.WaitGroup) {
...
 			log.WithField(logfields.Port, port).Info("Envoy: Listening for prometheus metrics")
 		}
-	})
+	}, false)
 }
 
 // addListener either reuses an existing listener with 'name', or creates a new one.
 // 'listenerConf()' is only called if a new listener is being created.
-func (s *XDSServer) addListener(name string, port uint16, listenerConf func() *envoy_config_listener.Listener, wg *completion.WaitGroup, cb func(err error)) {
+func (s *XDSServer) addListener(name string, port uint16, listenerConf func() *envoy_config_listener.Listener, wg *completion.WaitGroup, cb func(err error), isProxyListener bool) {
```
Comment (kkourt) [inline pkg/envoy/server.go:458]: AFAICT, the prometheus listener does not use this function. IOW, this function is only called with `isProxyListener=true`. Would it be better if we remove the `isProxyListener` parameter and rename the function to `addProxyListener`?

**Review by kkourt — APPROVED** [review]
Thanks!

LGTM, only some suggestions for your consideration.

File: pkg/envoy/server.go (hunk 1 above)
Comment (jrajahalme) [reply pkg/envoy/server.go]: applied, thanks!

File: pkg/envoy/server.go (hunk 2 above)
Comment (jrajahalme) [reply pkg/envoy/server.go:458]: This is called from `AddMetricsListener()` with `isProxyListener=false`, which is used for the Prometheus listener. It is a little cryptic due to the function parameter, though.

**Comment by jrajahalme** [comment]
test-me-please

**Review by christarazi — APPROVED** [review]

**Review by gandro — APPROVED** [review]

**Comment by jrajahalme** [comment]
Istio test on test-1.21-4.9 fails on a DNS error:
```
2021-07-09T19:53:31.715176642Z 2021-07-09T19:53:31.715056Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 14, connection error: desc = "transport: Error while dialing dial tcp: lookup istiod.istio-system.svc on 10.96.0.10:53: read udp 10.0.0.184:49256->10.96.0.10:53: i/o timeout"
```
istio-ingressgateway can't resolve istiod, so it can't be configured and the istio-ingressgateway service remains without any backends, causing istio install to fail.

Can't see anything obviously wrong with kube-dns service or coredns pods.

**Comment by jrajahalme** [comment]
CI failures are unrelated to this PR and since this is a bug fix I'm marking this as ready-to-merge without further retesting.

**Review by aditighag — APPROVED** [review]
