### PR TITLE
Deflake TestNodeManagerAbortReleaseIPReassignment

### LINKED ISSUE #42183: CI: ci-integration: ubuntu-24.04-arm64: TestNodeManagerAbortReleaseIPReassignment
## CI failure

Looking at the CI dashboard, there are some recent instances of this flake.

```
--- FAIL: TestNodeManagerAbortReleaseIPReassignment (2.02s)

    logger.go:256: time=2025-10-14T03:27:10.181Z level=INFO source=/home/runner/work/cilium/cilium/pkg/ipam/node_manager.go:390 msg="Discovered new CiliumNode custom resource" name=node4
    logger.go:256: time=2025-10-14T03:27:10.181Z level=WARN source=/home/runner/work/cilium/cilium/pkg/ipam/node.go:688 msg="Unable to compute pending pods, will not surge-allocate" name=node4 instanceID="" error="pod store uninitialized"
    logger.go:256: time=2025-10-14T03:27:10.181Z level=INFO source=/home/runner/work/cilium/cilium/pkg/ipam/node.go:718 msg="Resolving IP deficit of node" name=node4 instanceID="" selectedInterface="" selectedPoolID=global maxIPsToAllocate=3 availableForAllocation=2048 emptyInterfaceSlots=0 available=0 used=0 neededIPs=3 remainingInterfaces=0
    logger.go:256: time=2025-10-14T03:27:10.191Z level=WARN source=/home/runner/work/cilium/cilium/pkg/ipam/node.go:688 msg="Unable to compute pending pods, will not surge-allocate" name=node4 instanceID="" error="pod store uninitialized"
    logger.go:256: time=2025-10-14T03:27:10.191Z level=INFO source=/home/runner/work/cilium/cilium/pkg/ipam/node.go:718 msg="Resolving IP deficit of node" name=node4 instanceID="" selectedInterface="" selectedPoolID=global maxIPsToAllocate=1 availableForAllocation=2045 emptyInterfaceSlots=0 available=3 used=3 neededIPs=1 remainingInterfaces=0
    logger.go:256: time=2025-10-14T03:27:12.202Z level=WARN source=/home/runner/work/cilium/cilium/pkg/ipam/node.go:923 msg="Unable to unassign IPs from interface" name=node4 instanceID="" available=4 used=2 excess=1 excessIPs=[4] releasing=[4] selectedInterface="" selectedPoolID=global error="unable to release IP 4: IP 4 not found" selectedInterface="" releasingAddresses=1
    node_manager_test.go:691: 
        	Error Trace:	/home/runner/work/cilium/cilium/pkg/ipam/node_manager_test.go:691
        	Error:      	Received unexpected error:
        	            	unable to release IP 4: IP 4 not found
        	Test:       	TestNodeManagerAbortReleaseIPReassignment
```

* [Example one](https://github.com/cilium/cilium/actions/runs/18484350546/job/52665040599)
* [Example two](https://github.com/cilium/cilium/actions/runs/18401124523/job/52430400452)

@cilium/sig-ipam

### PR DESCRIPTION
**Pull request by lconnery**
This PR has a few of small changes to stabilize the node manager test `TestNodeManagerAbortReleaseIPReassignment`.

Each of the commits are self-contained fixes for individual issues which were causing flakiness.

Running locally, the failure rate using `stress` was ~4% after 2500 runs. After these four changes, the test has run for +250,000 iterations without failure.

--- 

**1. Wait for Node Stats to Be Updated**

The first fix is adding a waiting mechanism to the last check in the test. The assertion relied on a background goroutine to be triggered and update the stats used in the assertion. Occasionally that goroutine did not run in time resulting in a flaky failure.

**2. Handling Race Condition to Release IP**

This fix was similar to the first. 

There is a background goroutine that is periodically triggered to call `MaintainIPPool()` which will updated some node data depending on which IP addresses have been marked for release. I believe because of a potential exponential backoff period within the`MaintainIPPool()` trigger, the test writer manually calls this `MaintainIPPool()` from within the test itself.

Occasionally, that background `MaintainIPPool()` trigger runs first causing a flaky error due to the target IP already being released. The fix was to handle that error.

**3. Adding Locks in TestNodeManagerAbortReleaseIPReassignment**

At a couple of points in the test code, the internal data structures of the node object used in the test are either read from or written to. This was causing the occasional panic due to a concurrent read/write.

In those cases, the node mutex lock is used.

**4. Adding Locks in node.go**

In the `MaintainIPPool()` hook a function `handleIPRelease` reads and writes to a couple of data structures on the node struct without acquiring the mutex lock first.

I think this might not be an issue in production because the `MaintainIPPool()` trigger might be the only goroutine that is accessing this data. But it is an issue in  `TestNodeManagerAbortReleaseIPReassignment` because the test is reading and writing to these data structures.

Either way, I think it would be safest to make no assumptions on what might be accessing this data and simply use a mutex lock.

I didn't want to make too invasive a change here so I just removed the lock from `handleIPReleaseResponse` to avoid deadlock. This function was the only place it was being called.

Let me know if you'd like me to refactor this a bit more.

I also made sure there weren't any I/O calls being done inside the `Lock/Unlock` block.

**5. Small Final Concurrency Fix**

Added a small fix for a instance of the test accessing node data without a lock causing a rare flaky failure.

---

**Commands Used to Deflake**

Stress Command
```
cd ./pkg/ipam
go test -c -o ipam.test

stress ./ipam.test
```

Go Test with Race Condition Flag
```
go test --race ./pkg/ipam
```

Fixes: #42183

### CODE REVIEW

**Comment by joestringer** [comment]
Acknowledging that this is likely single-threaded code in cilium-operator, meaning that in production the race conditions should not trigger. However the test code paths do manipulate the target code concurrently, leading to the instability. From this I deduce the release note category would be `release-note/ci`. I'm also nominating this for backport to v1.18 under the assumption this is a general fix and would assist with making that branch's CI more reliable as well. Not nominating for further backport per [backport criteria](https://docs.cilium.io/en/stable/contributing/release/backports/#id1).

Due to the AWS => Quay outage earlier we will likely need to retrigger the workflows once write access to Quay is restored. After that CI should be able to run the testsuite.

**Comment by jrife** [comment]
@lconnery Thanks for investigating this. Good work. Overall, LGTM other than the small commit message formatting nits I mentioned offline (should be 72 chars).

File: pkg/ipam/node_manager_test.go [hunk 1]
```diff
@@ -679,30 +679,43 @@ func TestNodeManagerAbortReleaseIPReassignment(t *testing.T) {
...
 
 	// Run maintenance process again to process the acknowledgment
 	err = node.MaintainIPPool(context.Background())
-	require.NoError(t, err)
+
+	// Handle the case where the MaintainIPPool trigger runs first
+	expectedErrorStr := fmt.Sprintf("unable to release IP %s: IP %s not found", releasedIP, releasedIP)
+	if err != nil && err.Error() != expectedErrorStr {
+		require.NoError(t, err)
+	}
```
Comment (pippolo84) [inline pkg/ipam/node_manager_test.go]: Nit: we can express this in a simpler way:

```go
	require.Condition(t, func() bool {
		return err == nil || err.Error() == expectedErrorStr
	})
```

File: pkg/ipam/node_manager_test.go [hunk 2]
```diff
@@ -723,17 +739,22 @@ func TestNodeManagerAbortReleaseIPReassignment(t *testing.T) {
...
 
-	node = mngr.Get("node4")
-	require.NotNil(t, node)
-	require.Equal(t, 4, node.Stats().IPv4.AvailableIPs)
-	require.Equal(t, 2, node.Stats().IPv4.UsedIPs)
+	// Wait for the InstanceSync job to finish and update the node stats
+	require.Eventually(t, func() bool {
+		nodeStats := mngr.Get("node4").Stats()
+		return nodeStats.IPv4.AvailableIPs == 4 && nodeStats.IPv4.UsedIPs == 2
+	}, 15*time.Second, time.Second, "AvailableIPs and UsedIPs count did not update")
```
Comment (pippolo84) [inline pkg/ipam/node_manager_test.go]: Nit: we could use `EventuallyWithT` to allow assertions in the condition and to also have a more precise output to understand which specific assertion failed:

```go
	require.EventuallyWithT(t, func(c *assert.CollectT) {
		node = mngr.Get("node4")
		assert.NotNil(c, node)
		assert.Equal(c, 4, node.Stats().IPv4.AvailableIPs)
		assert.Equal(c, 2, node.Stats().IPv4.UsedIPs)
	}, 15*time.Second, time.Second, "AvailableIPs and UsedIPs count did not update")
```

Optionally, it would be nice to update the other `Eventually` in the test too.

**Review by pippolo84 — COMMENTED** [review]
Thanks!

Left a couple of comments inline about some minor improvements to the way we check some conditions.

However, running the test locally with the race detector enabled, I still see some data races:

```
=== RUN   TestNodeManagerAbortReleaseIPReassignment
    logger.go:256: time=2025-10-21T12:45:56.136+02:00 level=INFO source=github.com/cilium/cilium/pkg/ipam/node_manager.go:390 msg="Discovered new CiliumNode custom resource" name=node4
    logger.go:256: time=2025-10-21T12:45:56.136+02:00 level=WARN source=github.com/cilium/cilium/pkg/ipam/node.go:688 msg="Unable to compute pending pods, will not surge-allocate" name=node4 instanceID="" error="pod store uninitialized"
    logger.go:256: time=2025-10-21T12:45:56.136+02:00 level=INFO source=github.com/cilium/cilium/pkg/ipam/node.go:718 msg="Resolving IP deficit of node" name=node4 instanceID="" selectedInterface="" selectedPoolID=global maxIPsToAllocate=3 availableForAllocation=2048 emptyInterfaceSlots=0 available=0 used=0 neededIPs=3 remainingInterfaces=0
    logger.go:256: time=2025-10-21T12:45:56.147+02:00 level=WARN source=github.com/cilium/cilium/pkg/ipam/node.go:688 msg="Unable to compute pending pods, will not surge-allocate" name=node4 instanceID="" error="pod store uninitialized"
    logger.go:256: time=2025-10-21T12:45:56.147+02:00 level=INFO source=github.com/cilium/cilium/pkg/ipam/node.go:718 msg="Resolving IP deficit of node" name=node4 instanceID="" selectedInterface="" selectedPoolID=global maxIPsToAllocate=1 availableForAllocation=2045 emptyInterfaceSlots=0 available=3 used=3 neededIPs=1 remainingInterfaces=0
==================
WARNING: DATA RACE
Read at 0x00c000cc6210 by goroutine 242:
  github.com/cilium/cilium/pkg/ipam/types.(*IPAMStatus).DeepCopyInto()
      github.com/cilium/cilium/pkg/ipam/types/zz_generated.deepcopy.go:201 +0x971
  github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.(*NodeStatus).DeepCopyInto()
      github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2/zz_generated.deepcopy.go:2608 +0x259
  github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.(*CiliumNode).DeepCopyInto()
      github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2/zz_generated.deepcopy.go:2044 +0x184
  github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.(*CiliumNode).DeepCopy()
      github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2/zz_generated.deepcopy.go:2054 +0xd6
  github.com/cilium/cilium/pkg/ipam.(*Node).ResourceCopy()
      github.com/cilium/cilium/pkg/ipam/node.go:538 +0x8c
  github.com/cilium/cilium/pkg/ipam.(*Node).syncToAPIServer()
      github.com/cilium/cilium/pkg/ipam/node.go:1095 +0x91
  github.com/cilium/cilium/pkg/ipam.(*NodeManager).Upsert.func3()
      github.com/cilium/cilium/pkg/ipam/node_manager.go:360 +0x2e
  github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter()
      github.com/cilium/cilium/pkg/trigger/trigger.go:201 +0x748
  github.com/cilium/cilium/pkg/trigger.NewTrigger.gowrap1()
      github.com/cilium/cilium/pkg/trigger/trigger.go:121 +0x33

Previous write at 0x00c000cc6210 by goroutine 239:
  runtime.mapassign_faststr()
      internal/runtime/maps/runtime_faststr_swiss.go:263 +0x0
  github.com/cilium/cilium/pkg/testutils/ipam.FakeAcknowledgeReleaseIps()
      github.com/cilium/cilium/pkg/testutils/ipam/ipam.go:15 +0x114f
  github.com/cilium/cilium/pkg/ipam.TestNodeManagerAbortReleaseIPReassignment()
      github.com/cilium/cilium/pkg/ipam/node_manager_test.go:691 +0xfbc
  testing.tRunner()
      testing/testing.go:1934 +0x21c
  testing.(*T).Run.gowrap1()
      testing/testing.go:1997 +0x44

Goroutine 242 (running) created at:
  github.com/cilium/cilium/pkg/trigger.NewTrigger()
      github.com/cilium/cilium/pkg/trigger/trigger.go:121 +0x359
  github.com/cilium/cilium/pkg/ipam.(*NodeManager).Upsert()
      github.com/cilium/cilium/pkg/ipam/node_manager.go:355 +0x14c4
  github.com/cilium/cilium/pkg/ipam.TestNodeManagerAbortReleaseIPReassignment()
      github.com/cilium/cilium/pkg/ipam/node_manager_test.go:613 +0x66e
  testing.tRunner()
      testing/testing.go:1934 +0x21c
  testing.(*T).Run.gowrap1()
      testing/testing.go:1997 +0x44

Goroutine 239 (running) created at:
  testing.(*T).Run()
      testing/testing.go:1997 +0x9d2
  testing.runTests.func1()
      testing/testing.go:2477 +0x85
  testing.tRunner()
      testing/testing.go:1934 +0x21c
  testing.runTests()
      testing/testing.go:2475 +0x96c
  testing.(*M).Run()
      testing/testing.go:2337 +0xed4
  main.main()
      _testmain.go:117 +0x164
==================
==================
WARNING: DATA RACE
Read at 0x00c00054d0f8 by goroutine 242:
  github.com/cilium/cilium/pkg/ipam/types.(*IPAMStatus).DeepCopyInto()
      github.com/cilium/cilium/pkg/ipam/types/zz_generated.deepcopy.go:202 +0xadd
  github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.(*NodeStatus).DeepCopyInto()
      github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2/zz_generated.deepcopy.go:2608 +0x259
  github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.(*CiliumNode).DeepCopyInto()
      github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2/zz_generated.deepcopy.go:2044 +0x184
  github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2.(*CiliumNode).DeepCopy()
      github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2/zz_generated.deepcopy.go:2054 +0xd6
  github.com/cilium/cilium/pkg/ipam.(*Node).ResourceCopy()
      github.com/cilium/cilium/pkg/ipam/node.go:538 +0x8c
  github.com/cilium/cilium/pkg/ipam.(*Node).syncToAPIServer()
      github.com/cilium/cilium/pkg/ipam/node.go:1095 +0x91
  github.com/cilium/cilium/pkg/ipam.(*NodeManager).Upsert.func3()
      github.com/cilium/cilium/pkg/ipam/node_manager.go:360 +0x2e
  github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter()
      github.com/cilium/cilium/pkg/trigger/trigger.go:201 +0x748
  github.com/cilium/cilium/pkg/trigger.NewTrigger.gowrap1()
      github.com/cilium/cilium/pkg/trigger/trigger.go:121 +0x33

Previous write at 0x00c00054d0f8 by goroutine 239:
  github.com/cilium/cilium/pkg/testutils/ipam.FakeAcknowledgeReleaseIps()
      github.com/cilium/cilium/pkg/testutils/ipam/ipam.go:15 +0x115e
  github.com/cilium/cilium/pkg/ipam.TestNodeManagerAbortReleaseIPReassignment()
      github.com/cilium/cilium/pkg/ipam/node_manager_test.go:691 +0xfbc
  testing.tRunner()
      testing/testing.go:1934 +0x21c
  testing.(*T).Run.gowrap1()
      testing/testing.go:1997 +0x44

Goroutine 242 (running) created at:
  github.com/cilium/cilium/pkg/trigger.NewTrigger()
      github.com/cilium/cilium/pkg/trigger/trigger.go:121 +0x359
  github.com/cilium/cilium/pkg/ipam.(*NodeManager).Upsert()
      github.com/cilium/cilium/pkg/ipam/node_manager.go:355 +0x14c4
  github.com/cilium/cilium/pkg/ipam.TestNodeManagerAbortReleaseIPReassignment()
      github.com/cilium/cilium/pkg/ipam/node_manager_test.go:613 +0x66e
  testing.tRunner()
      testing/testing.go:1934 +0x21c
  testing.(*T).Run.gowrap1()
      testing/testing.go:1997 +0x44

Goroutine 239 (running) created at:
  testing.(*T).Run()
      testing/testing.go:1997 +0x9d2
  testing.runTests.func1()
      testing/testing.go:2477 +0x85
  testing.tRunner()
      testing/testing.go:1934 +0x21c
  testing.runTests()
      testing/testing.go:2475 +0x96c
  testing.(*M).Run()
      testing/testing.go:2337 +0xed4
  main.main()
      _testmain.go:117 +0x164
==================
    testing.go:1617: race detected during execution of test
--- FAIL: TestNodeManagerAbortReleaseIPReassignment (3.02s)
```

I don't think these are related to your changes, anyway. If so, we could also handle them in a follow-up PR. WDYT?

File: pkg/ipam/node_manager_test.go (hunk 1 above)
Comment (lconnery) [reply pkg/ipam/node_manager_test.go]: Done

**Comment by lconnery** [comment]
Hey @pippolo84, thanks for taking a look! 

I made those two adjustments from the comments you left, please take another look when you get the chance.

--- 

Looks like I missed a few of the race conditions in the test code. Let me take another look at things and try to recreate.

I'm happy to try and address these remaining race conditions in this PR if that works for you.

**Comment by pippolo84** [comment]
> I'm happy to try and address these remaining race conditions in this PR if that works for you.

Sure, that would be great, thanks! :100:

**Comment by lconnery** [comment]
@pippolo84 I believe I have fully removed the remaining race conditions with the latest commit if you wouldn't mind taking another look when you have the chance.

I was using the following command to focus on the issues in `TestNodeManagerAbortReleaseIPReassignment`
```
go test --race ./pkg/ipam -run ^TestNodeManagerAbortReleaseIPReassignment$
```

It passed 400 times locally but please let me know if you are seeing the same.

---

Separately I am seeing a few small race conditions remaining in `pkg/ipam` I'd be happy to take care up in a follow up PR if you'd like.

I figured it would be best to keep this PR focused on deflaking `TestNodeManagerAbortReleaseIPReassignment` but I think we are very closed to eliminating the flakes in the other `node_manager.go` tests.

Please let me know what you think. Thanks!

File: pkg/ipam/node.go [hunk 3]
```diff
@@ -842,7 +848,7 @@ func (n *Node) handleIPRelease(ctx context.Context, a *maintenanceAction) (insta
 			continue
 		}
 		// Check if the IP release waiting period elapsed
-		if ts.Add(time.Duration(operatorOption.Config.ExcessIPReleaseDelay) * time.Second).After(time.Now()) {
+		if ts.Add(time.Duration(n.excessIPReleaseDelay) * time.Second).After(time.Now()) {
```
Comment (pippolo84) [inline pkg/ipam/node.go]: [NON-BLOCKING] we can declare `excessIPReleaseDelay` as `time.Duration` and do the conversion:

`time.Duration(operatorOption.Config.ExcessIPReleaseDelay) * time.Second`

in `*NodeManager.Upsert`

**Review by pippolo84 — APPROVED** [review]
LGTM, thanks! 💯 

A very minor non-blocking nit left inline, feel free to ignore it if you think the current version is better.

File: pkg/ipam/node.go (hunk 3 above)
Comment (lconnery) [reply pkg/ipam/node.go]: I agree this is much better!

I've made that final change and ran the test many times locally.

**Comment by joestringer** [comment]
I suspect that the smoke tests are failing due to a new test change introduced on `main`. If you rebase against tip of `main` it should resolve the issue.

**Comment by lconnery** [comment]
> I suspect that the smoke tests are failing due to a new test change introduced on `main`. If you rebase against tip of `main` it should resolve the issue.

Thanks for the heads up, Joe!

I've rebased on top of the latest changes on main

**Comment by lconnery** [comment]
Hi all,

I think that last failing test is a failure unrelated to the changes in the PR. If someone wouldn't mind re-running that test, I'd really appreciate it.
