### PR TITLE
probes: replace ProbeManager with features API in cilium/ebpf

### LINKED ISSUE #20062: Probes: refactor `ProbeManager` to use `cilium/ebpf` features
By now the [features](https://github.com/cilium/ebpf/tree/master/features) package in https://github.com/cilium/ebpf is capable of feature probing most of the probes done with the `ProbeManager`. https://github.com/cilium/cilium/blob/eb902ce368a498b2976e018130415577c5628bb0/pkg/datapath/linux/probes/probes.go#L146-L149

Today cilium/ebpf can probe (few exceptions but on par with `bpftool` regarding ciliums use cases):
* Program Types
* Map Types
* Available Helpers
* Various Misc Probes (Instruction Limit, Bounded Loop, V2ISA, V3ISA)

It cannot:
* parse the kernel config: https://github.com/cilium/cilium/issues/20701
* probe the kernel HZ: https://github.com/cilium/cilium/issues/20737
* deliver a out of the box ready headersfile with macros (but logic to create macros could be moved into cilium which leverages the `features` package)

How could I approach replacing/refactoring `ProbeManager` for cilium to use the `features` package? 
In theory we wouldn't have to wrap those API calls with a `ProbeManager` anymore as the `features` package comes with a cache for already executed probes. I could get started with e.g. replacing calls to `GetHelpers()`. https://github.com/cilium/cilium/blob/7c86fe77439a328ea905928fb937cb17c3d4e875/pkg/datapath/linux/probes/probes.go#L327 That way we could replace usage of the `ProbeManager` step-by-step where possible and remove functionality from it?
However that approach might limit testability of code that calls the `features` APIs, or those tests would have to be privileged tests.

Would be nice to get some other opinions on how to approach this in a way that makes sense.

Referencing #11014 here, as that issue mentions a long term goal of having pure Go feature probes to not rely on shelling out to `bpftool`.

cc @ti-mo

### PR DESCRIPTION
**Pull request by rgo3**
The first commit makes sure we call `rlimit.RemoveMemlock()` only once and early enough on the startup of the agent for all probes being able to execute without `EPERM`.
 
The second commit vendors the github.com/cilium/ebpf/features package.

With the third commit we replace most of the feature probes done with the current ProbeManager system with the features API in cilium/ebpf.

Fixes: #20062

### CODE REVIEW

File: pkg/datapath/linux/devices.go [hunk 1]
```diff
@@ -497,10 +499,8 @@ func findK8SNodeIPLink() (netlink.Link, error) {
 // supportL3Dev returns true if the kernel is new enough to support BPF host routing of
 // packets coming from L3 devices using bpf_skb_redirect_peer.
 func supportL3Dev() bool {
-	probesManager := probes.NewProbeManager()
-	if h := probesManager.GetHelpers("sched_cls"); h != nil {
-		_, found := h["bpf_skb_change_head"]
-		return found
+	if err := features.HaveProgramHelper(ebpf.SchedCLS, asm.FnSkbChangeHead); err == nil {
```
Comment (ti-mo) [inline pkg/datapath/linux/devices.go]: Replace the whole function with
```suggestion
	return features.HaveProgramHelper(ebpf.SchedCLS, asm.FnSkbChangeHead) == nil
```

File: pkg/datapath/linux/requirements.go [hunk 2]
```diff
@@ -138,8 +139,7 @@ func CheckMinRequirements() {
 
 		// VTEP integration feature requires kernel 1m large instruction support
 		if option.Config.EnableVTEP {
-			supportedMisc := probeManager.GetMisc()
-			if !supportedMisc.HaveLargeInsnLimit {
+			if err := features.HaveLargeInstructions(); err != nil {
```
Comment (ti-mo) [inline pkg/datapath/linux/requirements.go]: `err` is unused outside of the nil check:
```suggestion
			if features.HaveLargeInstructions() != nil {
```

File: pkg/redirectpolicy/manager.go [hunk 3]
```diff
@@ -104,15 +106,9 @@ func (rpm *Manager) RegisterGetStores(sg StoreGetter) {
...
-		found := false
-		if h := probes.NewProbeManager().GetHelpers("cgroup_sock_addr"); h != nil {
-			if _, ok := h["bpf_sk_lookup_tcp"]; ok {
-				if _, ok = h["bpf_sk_lookup_udp"]; ok {
-					found = true
-				}
-			}
-		}
-		if !found {
+		lookupTCPErr := features.HaveProgramHelper(ebpf.CGroupSockAddr, asm.FnSkLookupTcp)
```
Comment (ti-mo) [inline pkg/redirectpolicy/manager.go]: No need to put these in a variable.

File: pkg/datapath/linux/probes/probes.go [hunk 4]
```diff
@@ -312,31 +310,11 @@ func (p *ProbeManager) GetOptionalConfig() map[KernelParam]kernelOption {
 }
 
 // GetMapTypes returns information about supported BPF map types.
+// Deprecated. Use github.com/cilium/ebpf/features instead.
```
Comment (ti-mo) [inline pkg/datapath/linux/probes/probes.go]:
```suggestion
// Deprecated. Use github.com/cilium/ebpf/features.HaveMapType() instead.
```

File: pkg/bandwidth/bandwidth.go [hunk 5]
```diff
@@ -41,14 +43,13 @@ func ProbeBandwidthManager() {
 	}
 
 	kernelGood := false
```
Comment (ti-mo) [inline pkg/bandwidth/bandwidth.go]:
```suggestion
	kernelGood := features.HaveProgramHelper(ebpf.SchedCLS, asm.FnSkbEcnSetCe) == nil
```

File: daemon/cmd/kube_proxy_replacement.go [hunk 6]
```diff
@@ -580,9 +530,12 @@ func finishKubeProxyReplacementInit(isKubeProxyReplacementStrict bool) error {
...
 	}
 
+	var haveLargeInsnLimit bool
+	if err := features.HaveLargeInstructions(); err == nil {
+		haveLargeInsnLimit = true
+	}
 	option.Config.NodePortNat46X64 = option.Config.EnableIPv4 && option.Config.EnableIPv6 &&
-		option.Config.NodePortMode == option.NodePortModeSNAT &&
-		probes.NewProbeManager().GetMisc().HaveLargeInsnLimit
+		option.Config.NodePortMode == option.NodePortModeSNAT && haveLargeInsnLimit
```
Comment (ti-mo) [inline daemon/cmd/kube_proxy_replacement.go]:
```suggestion
		option.Config.NodePortMode == option.NodePortModeSNAT && 
		features.HaveLargeInstructions() == nil
```

**Review by ti-mo — CHANGES_REQUESTED** [review]
:very-nice:

Most all `if err := features.HaveXYZ(); err ...` instances can be replaced by `if features.Have... {` if `err` is only used in the conditional.

I've highlighted a few such cases, but please apply throughout.

:rocket:

File: pkg/datapath/connector/ipvlan.go [hunk 7]
```diff
@@ -225,8 +225,13 @@ func CreateAndSetupIpvlanSlave(id string, slaveIfName string, netNs ns.NetNS, mt
...
 	}
 
-	mapID, err := m.ID()
+	mapInfo, err := m.Info()
 	if err != nil {
+		return nil, fmt.Errorf("failed to get map Info: %w", err)
+	}
+
+	mapID, ok := mapInfo.ID()
+	if !ok {
```
Comment (borkmann) [inline pkg/datapath/connector/ipvlan.go]: Needs rebase, then this commit can be dropped since we removed ipvlan support.

File: daemon/cmd/daemon_main.go [hunk 8]
```diff
@@ -1534,20 +1537,17 @@ func initEnv(cmd *cobra.Command) {
...
 		}
 	}
 
 	if option.Config.EnableBPFTProxy {
-		if h := probes.NewProbeManager().GetHelpers("sched_act"); h != nil {
-			if _, ok := h["bpf_sk_assign"]; !ok {
-				option.Config.EnableBPFTProxy = false
-				log.Info("Disabled support for BPF TProxy due to missing kernel support for socket assign (Linux 5.7 or later)")
-			}
+		if err := features.HaveProgramHelper(ebpf.SchedACT, asm.FnSkAssign); err != nil {
```
Comment (borkmann) [inline daemon/cmd/daemon_main.go]: Small nit: I would use SchedCLS as well here, since we don't use act_bpf internally, so we also don't need to add unnecessary dependency. (Both enable the same helpers.)

File: daemon/cmd/datapath.go [hunk 9]
```diff
@@ -352,10 +353,9 @@ func (d *Daemon) initMaps() error {
 		}
 	}
 
-	pm := probes.NewProbeManager()
-	supportedMapTypes := pm.GetMapTypes()
+	lruHashErr := features.HaveMapType(ebpf.LRUHash)
 	createSockRevNatMaps := option.Config.EnableSocketLB &&
-		option.Config.EnableHostServicesUDP && supportedMapTypes.HaveLruHashMapType
+		option.Config.EnableHostServicesUDP && lruHashErr == nil
```
Comment (borkmann) [inline daemon/cmd/datapath.go]: nit: Do we need extra var? maybe just fold it in: `&& features.HaveMapType(ebpf.LRUHash) == nil`?

File: daemon/cmd/kube_proxy_replacement.go [hunk 10]
```diff
@@ -216,13 +215,7 @@ func initKubeProxyReplacementOptions() (bool, error) {
...
 
 	if option.Config.EnableNodePort {
-		found := false
-		if h := probesManager.GetHelpers("sched_act"); h != nil {
-			if _, ok := h["bpf_fib_lookup"]; ok {
-				found = true
-			}
-		}
-		if !found {
+		if err := features.HaveProgramHelper(ebpf.SchedACT, asm.FnFibLookup); err != nil {
```
Comment (borkmann) [inline daemon/cmd/kube_proxy_replacement.go]: nit: independent of your PR, but same comment: SchedCLS

File: pkg/datapath/loader/compile.go [hunk 11]
```diff
@@ -157,22 +159,20 @@ var (
...
 			// We can probe the availability of BPF instructions indirectly
 			// based on what kernel helpers are available when both were
 			// added in the same release.
 			// We want to enable v3 only on kernels 5.10+ where we have
 			// tested it and need it to work around complexity issues.
-			h := manager.GetHelpers("sched_cls")
-			if manager.GetMisc().HaveV3ISAExtension && h != nil {
-				if _, ok := h["bpf_redirect_neigh"]; ok {
+			if err := features.HaveV3ISA(); err == nil {
+				if err := features.HaveProgramHelper(ebpf.SchedCLS, asm.FnRedirectNeigh); err == nil {
```
Comment (borkmann) [inline pkg/datapath/loader/compile.go]: nit: err var unused

File: pkg/datapath/loader/compile.go [hunk 12]
```diff
@@ -157,22 +159,20 @@ var (
...
 					nameBPFCPU = "v3"
 					return
 				}
 			}
 			// We want to enable v2 on all kernels that support it, that is,
 			// kernels 4.14+.
-			if manager.GetMisc().HaveV2ISAExtension {
+			if err := features.HaveV2ISA(); err == nil {
```
Comment (borkmann) [inline pkg/datapath/loader/compile.go]: nit: ditto

**Comment by tklauser** [comment]
> The first commit replaces a deprecated function in cilium/ebpf, which is needed so that updating cilium/ebpf to 9.1 won't break. We might want to cherry pick that one and split it of into a separate PR.

I think this part of the PR description no longer applies since #20584 was merged.

> The second commit updates the cilium/ebpf dependency to a newer commit, so the third commit can use some of the newer Helper built-ins which were just recently added. Commit should be removed from PR once we actually release cilium/ebpf 9.1 and do a proper dependency upgrade.

Likewise, #20453 updated cilium/ebpf.

> With the 3rd commit we replace most of the feature probes done with the current ProbeManager system with the features API in cilium/ebpf.

**Comment by ti-mo** [comment]
Converted this to draft, small update:

The 5.4 and 4.19 jobs seem to have failed with `unable to initialize Kube proxy replacement options`. Here are 2 zips for posterity:

[94fee933_K8sPolicyTestExtended_Validate_toEntities_KubeAPIServer_Allows_connection_to_KubeAPIServer.zip](https://github.com/cilium/cilium/files/9197207/94fee933_K8sPolicyTestExtended_Validate_toEntities_KubeAPIServer_Allows_connection_to_KubeAPIServer.zip)
[44b3b553_K8sDatapathConfig_Host_firewall_With_VXLAN.zip](https://github.com/cilium/cilium/files/9197209/44b3b553_K8sDatapathConfig_Host_firewall_With_VXLAN.zip)

The good news is the agent crashes early on in the startup process, and seems to occur fairly regularly, so doesn't seem so difficult to reproduce for now.

These failures highlight a shortcoming with the probing approach as proposed in this PR: we only check for `features.Have...() == nil`, which ignores any unexpected errors during probing (insufficient memory, permissions, ..). As part of this PR, we'll add a helper that logs a `Fatal()` if a probe result is not either `nil` or `ErrNotSupported`.

This way, we can start to uncover the root cause of these probe failures, as we're also seeing them on master from time to time (using bpftool).

**Comment by rgo3** [comment]
/test-1.22-5.4

**Comment by rgo3** [comment]
/test-1.22-5.4

**Comment by rgo3** [comment]
/test-1.22-5.4

**Comment by rgo3** [comment]
/test-1.22-5.4
/test-1.24-net-next

**Comment by rgo3** [comment]
/test-1.22-5.4

**Comment by rgo3** [comment]
/test-1.22-5.4

**Comment by rgo3** [comment]
/test-1.22-5.4

**Comment by rgo3** [comment]
Marking this ready for review again.

The probe failures (`EPERM`) we were seeing should be resolved by the first commit, changing when we set the `rlimit` in the agent. I have been holding off on running the full test suite again before getting another round of reviews, but the 1.22-5.4 test did pass.

Open for discussion is probably to fatal on probes with inconclusive (neither `nil` or  `ErrNotSupported`) outcomes, but I do agree with Timo that keeping the fatal here could help discovering other issues and discover their root cause as inconclusive results are not expected to happen.

File: daemon/cmd/daemon_main.go [hunk 13]
```diff
@@ -1478,20 +1480,17 @@ func initEnv(cmd *cobra.Command) {
...
 		}
 	}
 
 	if option.Config.EnableBPFTProxy {
-		if h := probes.NewProbeManager().GetHelpers("sched_act"); h != nil {
-			if _, ok := h["bpf_sk_assign"]; !ok {
-				option.Config.EnableBPFTProxy = false
-				log.Info("Disabled support for BPF TProxy due to missing kernel support for socket assign (Linux 5.7 or later)")
-			}
+		if probes.HaveProgramHelper(ebpf.SchedCLS, asm.FnSkAssign) != nil {
```
Comment (joestringer) [inline daemon/cmd/daemon_main.go:1419]: The previous code says `sched_act`, but the new code says `SchedCLS`. I don't think these are the same thing?

Comment (joestringer) [reply daemon/cmd/daemon_main.go:1419]: (ditto for the rest of this commit, I won't repeat the comment in each location)

Comment (joestringer) [reply daemon/cmd/daemon_main.go:1419]: Hmm, the more I look through the PR, the more it seems like the existing code was just inconsistently checking `sched_act` vs. `sched_cls`. From memory I think we actually use `sched_act` (direct action) for attachment rather than attaching a classifier, but I could be wrong.

File: pkg/datapath/linux/devices.go [hunk 14]
```diff
@@ -501,12 +503,7 @@ func findK8SNodeIPLink() (netlink.Link, error) {
 // supportL3Dev returns true if the kernel is new enough to support BPF host routing of
 // packets coming from L3 devices using bpf_skb_redirect_peer.
 func supportL3Dev() bool {
-	probesManager := probes.NewProbeManager()
-	if h := probesManager.GetHelpers("sched_cls"); h != nil {
-		_, found := h["bpf_skb_change_head"]
-		return found
-	}
-	return false
+	return probes.HaveProgramHelper(ebpf.SchedCLS, asm.FnSkbChangeHead) == nil
```
Comment (joestringer) [inline pkg/datapath/linux/devices.go:506]: Incidentally, it seems like a curious choice to expose the functions via the `asm` package rather than just in the ebpf package, since the asm defines the BPF_CALL instruction but the interpretation of the arguments (ie numbers here) is up to the eBPF runtime. That is to say, depending on which platform we target, the actual meaning of the number 5 which is currently mapped to some specific function in the asm package could be different. But that's probably more feedback for ensuring the ebpf library is cross-platform rather than this specific PR. (Though that said, if we change this in the upstream library then obviously this PR would also need updating).

Comment (joestringer) [reply pkg/datapath/linux/devices.go:506]: ^^ I'm not quite sure what this means in the end. Maybe creating a `github.com/cilium/ebpf/linux` package specifically to define these constants for the Linux eBPF runtime?

I'll cc @dthaler here in case he has thoughts / opinions on this, given his background on the eBPF for Windows project.

File: pkg/datapath/linux/probes/probes.go [hunk 15]
```diff
@@ -422,3 +395,101 @@ func (p *ProbeManager) KernelConfigAvailable() bool {
 
 	return true
 }
+
+// HaveMapType is a wrapper around features.HaveMapType() to check if a certain
+// BPF map type is supported by the kernel.
+// On unexpected probe results this function will terminate with log.Fatal().
+func HaveMapType(mt ebpf.MapType) error {
```
Comment (joestringer) [inline pkg/datapath/linux/probes/probes.go:396]: I think that `MustHaveMapType()` would be a more canonical way to call this if there are strict consequences for the map type being missing.

File: pkg/datapath/linux/probes/probes.go [hunk 16]
```diff
@@ -422,3 +395,101 @@ func (p *ProbeManager) KernelConfigAvailable() bool {
...
+	err := features.HaveMapType(mt)
+	if errors.Is(err, ebpf.ErrNotSupported) {
+		return err
+	}
+	if err != nil {
+		log.WithError(err).Fatalf("failed to probe MapType: %s", mt.String())
```
Comment (joestringer) [inline pkg/datapath/linux/probes/probes.go]: I don't particularly like combining the check for the map type with the forced exit here. For instance, we would know that the map type is missing. But we don't know _why_ that map type is needed. Maybe there's a workaround that involves disabling some feature flag. Only the caller has that context. If we introduce a new map type tomorrow that can be conditionally used depending on which kernel Cilium runs on, then this also prevents us from having an implementation that conditionally checks for that support and falls back to an older / more naive implementation. This is the case today for LRU and LPM map types, for what it's worth. I anticipate we'll need something like this in future too.

I would suggest creating some canonical error here, so above declare a `ErrorMapTypeUnsupported = fmt.Errorf("map type unsupported")` and then here, do:

```suggestion
        return fmt.Errorf("failed to probe MapType %s: %w", mt.String(), ErrorMapTypeUnsupported)
```

Then, the calling code could do `if errors.Is(err, probes.ErrorMapTypeUnsupported) { ... fallback / exit ... }`.

File: pkg/datapath/linux/probes/probes.go (hunk 15 above)
Comment (joestringer) [reply pkg/datapath/linux/probes/probes.go:396]: (next feedback will render this unnecessary)

File: pkg/datapath/linux/probes/probes.go [hunk 17]
```diff
@@ -422,3 +395,101 @@ func (p *ProbeManager) KernelConfigAvailable() bool {
...
+// HaveProgramType is a wrapper around features.HaveProgramType() to check
+// if a certain BPF program type is supported by the kernel.
+// On unexpected probe results this function will terminate with log.Fatal().
+func HaveProgramType(pt ebpf.ProgramType) error {
+	err := features.HaveProgramType(pt)
+	if errors.Is(err, ebpf.ErrNotSupported) {
+		return err
+	}
+	if err != nil {
+		log.WithError(err).Fatalf("failed to probe ProgramType: %s", pt.String())
```
Comment (joestringer) [inline pkg/datapath/linux/probes/probes.go]: Again, we can't just fatal out here. SkMsg is only supported in 4.19+ IIRC, but we will support older kernel versions for a while yet. This should return another declared error type.

File: pkg/datapath/linux/probes/probes.go [hunk 18]
```diff
@@ -422,3 +395,101 @@ func (p *ProbeManager) KernelConfigAvailable() bool {
...
+// HaveProgramHelper is a wrapper around features.HaveProgramHelper() to
+// check if a certain BPF program/helper copmbination is supported by the kernel.
+// On unexpected probe results this function will terminate with log.Fatal().
+func HaveProgramHelper(pt ebpf.ProgramType, helper asm.BuiltinFunc) error {
+	err := features.HaveProgramHelper(pt, helper)
+	if errors.Is(err, ebpf.ErrNotSupported) {
+		return err
+	}
+	if err != nil {
+		log.WithError(err).Fatalf("failed to probe Helper: %s/%s", pt.String(), helper.String())
```
Comment (joestringer) [inline pkg/datapath/linux/probes/probes.go]: Same here, we support a range of kernels that have different helpers and sometimes we can fall back to using older helpers when newer ones are unavailable. Needs a dedicated error return type and to let the caller decide how to handle the error.

File: pkg/datapath/linux/probes/probes.go (hunk 16 above)
Comment (joestringer) [reply pkg/datapath/linux/probes/probes.go]: (I realize now that `ebpf` library already has the unsupported error so we probably don't need to redefine it)

File: pkg/datapath/linux/probes/probes.go [hunk 19]
```diff
@@ -422,3 +395,101 @@ func (p *ProbeManager) KernelConfigAvailable() bool {
...
+// HaveLargeInstructionLimit is a wrapper around features.HaveLargeInstructions()
+// to check if the kernel supports the 1 Million instruction limit.
+// On unexpected probe results this function will terminate with log.Fatal().
+func HaveLargeInstructionLimit() error {
+	err := features.HaveLargeInstructions()
+	if errors.Is(err, ebpf.ErrNotSupported) {
+		return err
+	}
+	if err != nil {
+		log.WithError(err).Fatal("failed to probe large instruction limit")
```
Comment (joestringer) [inline pkg/datapath/linux/probes/probes.go:444]: If you see the caller checking VTEP support for instance, you'll find that it's an optional feature. The caller already calls `log.Fatal(...)` but in that case the user gets the pointer that if they disable VTEP, they may still be able to successfully run Cilium. Fataling out here deprives the user of that knowledge.

**Review by joestringer — CHANGES_REQUESTED** [review]
Thanks for working on this! The probe changes in general look good. The fataling out inside the probe library doesn't make sense to me, so I included a few comments on some of them below. I think that the probe library should just return the unsupported error to the caller (wrapped with the type) so that the caller can decide whether the kernel feature is a hard requirement and whether to either fall back to a different implementation or to fatal out itself and provide the user with instructions about how to mitigate the issue (eg, disable a feature).

File: pkg/datapath/linux/probes/probes.go (hunk 15 above)
Comment (joestringer) [reply pkg/datapath/linux/probes/probes.go:396]: Somehow I just missed the whole `ErrNotSupported` logic, sorry about that. This feedback doesn't really make sense.

File: pkg/datapath/linux/probes/probes.go (hunk 16 above)
Comment (joestringer) [reply pkg/datapath/linux/probes/probes.go]: ditto, I just missed the `ErrNotSupported` logic. More :coffee: required.

File: pkg/datapath/linux/probes/probes.go (hunk 17 above)
Comment (joestringer) [reply pkg/datapath/linux/probes/probes.go]: Ditto.

**Review by joestringer — APPROVED** [review]
You would think that after commenting on the same thing a few times, I would have noticed that I just completely overlooked the exact code I was describing that's already in the code, but evidently I just missed that. I'm not sure what I was thinking. The main feedback I gave was around that and the feedback was invalid, so I'll mark this as approved.

I've looked back over the remaining feedback and it's just this point around defining functions in the asm package which I think isn't quite right in upstream cilium/ebpf library given the lack of guarantee from eBPF runtimes about the meaning for individual BPF_CALL parameter numbers. I'd suggest looking at that a bit more closely in the library and moving them to a package that is runtime specific (ie Linux eBPF as an eBPF runtime target).

File: pkg/datapath/linux/devices.go (hunk 14 above)
Comment (ti-mo) [reply pkg/datapath/linux/devices.go:506]: > Incidentally, it seems like a curious choice to expose the functions via the asm package rather than just in the ebpf package ...

That sounds like a strawman argument to me. The `asm` package is where the ISA description lives and is used by the instruction decoder. When it was conceived, it made sense to put these constants here, since Linux had the only real eBPF implementation at the time (ignoring ubpf for a second), and why would anyone ever want to write another runtime with different helpers? :wink:

Since helpers are part of the ABI and we were only targeting Linux, they were implicitly considered part of the ISA. Until the `features` package came around, helper type constants weren't taken by any APIs outside of the `asm` package, so they were really values you'd only use when constructing bytecode from Go. It may look a bit off-color, but there's still not much use for them elsewhere in the API, so IMO they're fine where they are.

We could consider putting these behind build tags, but the existing ones will need to remain available in `asm` for compatibility. I don't see a real need to change this until someone comes along to add Windows support, though.

Comment (joestringer) [reply pkg/datapath/linux/devices.go:506]: I raise this question specifically because of the active discussions around cross-platform support going on at the moment in the context of the eBPF for Windows project. Cross-platform eBPF in general was discussed as recently as two weeks ago as part of the eBPF community call ([notes](https://lore.kernel.org/bpf/CH2PR21MB14649A069BDEACFBC440C623A3649@CH2PR21MB1464.namprd21.prod.outlook.com/T/#u)). One of the points highlighted from recent discussions is that the helper codes for that instruction are not guaranteed to be consistent between platforms. When you look at the current helpers, some of those helpers are very Linux specific, so it will not make sense for other platforms to support the same numbers for those helpers. From what I understand, the current thinking from other runtimes is that they will not ensure ABI compatibility with the Linux runtime for the `BPF_CALL` instruction.

From your explanation, I think there is a completely reasonable line of thinking that leads to the current layout of these. That said, if the question is as simple as which package these symbols live in, I think it's worth at least considering how a future of cilium/ebpf against other runtimes might work so we can minimize any library change impacts in future. Maybe the future answer to this should be as simple as setting some Go build flags when using the eBPF library in order to target specific runtimes. In that case, no further changes would be necessary. I floated the idea above that these ABI symbols could be declared in a separate package, that's also a possibility but I don't feel strongly that this should be the case.

File: pkg/datapath/linux/probes/probes.go [hunk 20]
```diff
@@ -312,31 +305,11 @@ func (p *ProbeManager) GetOptionalConfig() map[KernelParam]kernelOption {
 }
 
 // GetMapTypes returns information about supported BPF map types.
+// Deprecated. Use HaveMapType() instead.
```
Comment (tklauser) [inline pkg/datapath/linux/probes/probes.go]: The only remaining user of this method seems to be in `probes_privileged_test.go` for `TestMapTypes`. The purpose of that test seems to be testing `GetMapTypes`. I think we can thus remove the test and this method as well. While at it maybe also add a test for `HaveMapType` instead? Can both be done as a follow-up PR.

**Review by tklauser — APPROVED** [review]
One non-blocking comment regarding a deprecated method which can be addressed in a follow-up PR. Otherwise LGTM, thanks!

File: pkg/datapath/linux/probes/probes.go (hunk 16 above)
Comment (ti-mo) [inline pkg/datapath/linux/probes/probes.go]: Nit: all operands passed to string formatters like `Fatalf()` always get their `String()` methods called, if any. These may be better supplied with `WithField()`, though. I'll push a fixup.

File: pkg/datapath/linux/probes/probes.go (hunk 20 above)
Comment (ti-mo) [reply pkg/datapath/linux/probes/probes.go]: > The only remaining user of this method seems to be in probes_privileged_test.go for TestMapTypes. The purpose of that test seems to be testing GetMapTypes. I think we can thus remove the test and this method as well. 

Good point, done!

> While at it maybe also add a test for HaveMapType instead?

Package `features` already has an extensive test suite in the lib itself, so that should be covered. The specific map/prog types the Cilium agent probes for were even used to choose the initial batch of handcrafted tests that are expected to pass on specific kernel versions we need to support!

`HaveMapType` and friends are simple logging wrappers that can't really be tested.

File: daemon/cmd/daemon_main.go (hunk 13 above)
Comment (ti-mo) [reply daemon/cmd/daemon_main.go:1419]: `sched_act` and `sched_cls` were introduced in the same commit and have been in the kernel almost since the start of ebpf. `sk_assign` can be used in both cls and act, so the probe result here should be equivalent. Not sure why this was changed, but at least now we're consistently using `SchedCLS` as you pointed out! :wink:

**Comment by ti-mo** [comment]
/test-1.16-4.9

**Comment by ti-mo** [comment]
/test-1.24-net-next

**Comment by ti-mo** [comment]
/test-1.16-4.9

**Comment by ti-mo** [comment]
This hit https://github.com/cilium/cilium/issues/20288 in https://jenkins.cilium.io/job/Cilium-PR-K8s-1.16-kernel-4.9/2411/testReport/Suite-k8s-1/16/K8sHubbleTest_Hubble_Observe_Test_L3_L4_Flow/, zip attached.

[30cc83bc_K8sHubbleTest_Hubble_Observe_Test_L3-L4_Flow.zip](https://github.com/cilium/cilium/files/9423395/30cc83bc_K8sHubbleTest_Hubble_Observe_Test_L3-L4_Flow.zip)

**Comment by ti-mo** [comment]
/test-1.16-4.9

**Comment by ti-mo** [comment]
Giving this some more time until 4.9.326 CI images are built, containing a backport of the bpf accounting fix to reduce the flakiness of the 4.9 tests.

**Comment by ti-mo** [comment]
/test-1.16-4.9

**Review by ti-mo — APPROVED** [review]

**Review by joamaki — APPROVED** [review]
