### PR TITLE
Ensure completion.WaitGroup always has a timeout

### LINKED ISSUE #44543: identity updater is wedged forever when missing NPDS ack from envoy
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.18.7 and lower than v1.19.0

### What happened?

We are running cilium 1.18.6, and occasionally, we see that fqdn proxy failed to push new IPs into ipcache (via ipcache-inject-labels). This in turn causes toFQDN policies to drop legit connections.

After investigation, we found that is caused by identity_updater being stuck. Below is a capture of stackdump from one such cilium-agent pod (similar stackdumps were observed in other problematic cilium-agent pods, too):

```
goroutine 656 [select, 764 minutes]:
github.com/cilium/cilium/pkg/ipcache.(*IPCache).doInjectLabels(0x4000d0dcc0, {0x489d7d0, 0x40007288c0}, {0x4027a49bf0, 0x1, 0x1})
	/go/src/github.com/cilium/cilium/pkg/ipcache/metadata.go:579 +0x13c4
github.com/cilium/cilium/pkg/ipcache.(*IPCache).handleLabelInjection(0x4000d0dcc0, {0x489d7d0, 0x40007288c0})
	/go/src/github.com/cilium/cilium/pkg/ipcache/metadata.go:1014 +0x168
github.com/cilium/cilium/pkg/controller.(*controller).runController(0x40039fc160)
	/go/src/github.com/cilium/cilium/pkg/controller/controller.go:333 +0x1d8
created by github.com/cilium/cilium/pkg/controller.(*Manager).createControllerLocked in goroutine 1
	/go/src/github.com/cilium/cilium/pkg/controller/manager.go:131 +0x3f8
```

Basically `doInjectLabels` is stuck there forever.

https://github.com/cilium/cilium/blob/95896696119f33a0f5d21019182192fcdab3600f/pkg/ipcache/metadata.go#L578-L583

IdentityUpdater is stuck there, too:

```
goroutine 412 [sync.WaitGroup.Wait, 764 minutes]:
sync.runtime_SemacquireWaitGroup(0x400d995240?)
	/usr/local/go/src/runtime/sema.go:110 +0x2c
sync.(*WaitGroup).Wait(0x400d995240)
	/usr/local/go/src/sync/waitgroup.go:118 +0x70
github.com/cilium/cilium/pkg/policy/cell.(*identityUpdater).doUpdatePolicyMaps(0x4000d0d4a0, {0x489d798, 0x4000f1b1a0})
	/go/src/github.com/cilium/cilium/pkg/policy/cell/identity_updater.go:218 +0x234
github.com/cilium/hive/job.(*jobTimer).start(0x40011d3800, {0x489d798, 0x4000f1b1a0}, 0x0?, {0x48a7f00, 0x40011d37a0}, {{{0x0, 0x0, 0x0}}, 0x4000f191f0, ...})
	/go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/job/timer.go:191 +0x37c
created by github.com/cilium/hive/job.(*queuedJob).Start.func1 in goroutine 1
	/go/src/github.com/cilium/cilium/vendor/github.com/cilium/hive/job/job.go:126 +0x148
```

It is basically waiting endpoint manager to update policymaps for all endpoints.

https://github.com/cilium/cilium/blob/95896696119f33a0f5d21019182192fcdab3600f/pkg/policy/cell/identity_updater.go#L213-L219

This is then because of a long wait for proxyCompletions:

```
goroutine 1924249 [select, 764 minutes]:
github.com/cilium/cilium/pkg/completion.(*WaitGroup).Wait(0x4012f3a500)
	/go/src/github.com/cilium/cilium/pkg/completion/completion.go:94 +0x170
github.com/cilium/cilium/pkg/endpointmanager.(*endpointManager).waitForProxyCompletions(0x400045b0a0, 0x4012f3a500)
	/go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:186 +0xd0
github.com/cilium/cilium/pkg/endpointmanager.(*endpointManager).UpdatePolicyMaps.func1()
	/go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:214 +0x48
created by github.com/cilium/cilium/pkg/endpointmanager.(*endpointManager).UpdatePolicyMaps in goroutine 412
	/go/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:210 +0x144
```

Here it is waiting for envoy to give ACK for the policy updates:

https://github.com/cilium/cilium/blob/95896696119f33a0f5d21019182192fcdab3600f/pkg/endpointmanager/manager.go#L177-L193

~~From envoy metrics, we can also see there is a mismatch between attempts and successes:~~ (which is expected as illustrated in a later comment)

```
envoy_cilium_npds_control_plane_rate_limit_enforced{} 0
envoy_cilium_npds_init_fetch_timeout{} 0
envoy_cilium_npds_update_attempt{} 70
envoy_cilium_npds_update_failure{} 0
envoy_cilium_npds_update_rejected{} 0
envoy_cilium_npds_update_success{} 69
envoy_cilium_npds_control_plane_connected_state{} 1
envoy_cilium_npds_control_plane_pending_requests{} 0
envoy_cilium_npds_update_time{} 1772061317553
envoy_cilium_npds_version{} 15373753880136931392
```

Note there is no failures or rejects. There is just one attempt that is neither success or failure, and is stuck there forever.

### How can we reproduce the issue?

This is observed in production with a fairly high frequency. No guaranteed reproduction steps available yet.

### Cilium Version

v1.18.6

### Kernel Version

6.8.0-1025-azure-nvidia

### Kubernetes Version

v1.31.9

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jrajahalme**
Add a new CLI option `--endpoint-policy-update-timeout`, and corresponding helm value `endpointPolicyUpdateTimeoutDuration` defaulting to 10 seconds. This is used on the context passed to `completion.NewWaitGroup`, so that by default endpointmanager waits for up to 10 seconds for Envoy
policy updates to be applied and acknowledged by Envoy.

Change `UpdatePolicyMaps()` to Wait before returning and return the error from `Wait`. Remove the unused 2nd parameter. Add `endpoint-policy-update-timeout` to the context for the proxyWaitGroup. If an error is returned, make the sole caller re-trigger the policy updates with an empty WaitGroup, so that if there are no other queued events, then the policy update is done immediately again.

When the `completion.WaitGroup` context times out, return the blocking Completion's remaining resources in the returned error.

Only wait for ACKs from xDS nodes not ACKed yet.

Fixes: #44543

### CODE REVIEW

File: pkg/endpointmanager/manager.go
Comment (christarazi) [inline pkg/endpointmanager/manager.go:208]: What happens when the proxyWaitGroup times out here? We log a warning with the error but then is this update just dropped? Shouldn't there be a retry?

Comment (jrajahalme) [reply pkg/endpointmanager/manager.go:208]: Good question. We've never really seen Envoy NACKs on policy updates, so there are no reverts. It's a warn log, so we'll know if it happens in CI or production, eventually. So the most likely reason would be a context timeout, which would lead to the release of DNS response to the source pod potentially too soon, but the timeout would resolve an indefinite stall where we are waiting for an ACK in a situation where no change has been sent to Envoy.

**Review by youngnick — APPROVED** [review]
LGTM from SIG-Servicemesh.

File: pkg/endpointmanager/manager.go
Comment (squeed) [reply pkg/endpointmanager/manager.go:208]: That seems like the "done" mechanism for the WaitGroup wrapper should handle the case where no work is actually being waited on.

Is Envoy failing to mark a task as done, or are there zero tasks?

**Comment by odinuge** [comment]
Thanks for looking into this.

After working on https://github.com/cilium/cilium/pull/43953 and https://github.com/cilium/cilium/pull/44328 for quite a while to debug/fix other issues (the latter to make backports of the fix easier to do, as we agreed on), I'm not too sure this approach of passing both a timeout and a context to the WaitGroup is the most optimal and cleanest one.

Given we already pass in a context, I think its much cleaner to just do roughly the same as proposed in https://github.com/cilium/cilium/pull/43953 and have the WithTimeout outside the WaitGroup to more cleanly separate them. That way we can pass in the context from the WithTimeout into the WaitGroup - and thats exactly whats being done today in a few places eg. [this](https://github.com/cilium/cilium/pull/44731/changes#diff-1219bba868a33ebead18849319b76879a9e9126ce1020e4a469f7fb085eb5d89L160-L164) where it makes sense.

I agree some other places deserve a timeout, but that could also just as well be in the actual envoy/xds code that has the actual side-effect, in order to properly clean up those resources as well. Doesn't hurt to have it both places, but we should figure out what the exact root cause of https://github.com/cilium/cilium/issues/44543 is (I'm still not 100% sure we have that, but I might be wrong), and ensure that in case it happens, we don't leak neither goroutines, memory, or block the ipcache - no matter if its indefinitely or for 1+min.

File: pkg/endpointmanager/manager.go
Comment (jrajahalme) [reply pkg/endpointmanager/manager.go:208]: I've fixed two possible stall reasons so far:
1. (more likely) https://github.com/cilium/cilium/pull/44754
2. (less likely due to Envoy listener draining duration being 10 minutes) https://github.com/cilium/cilium/pull/44597

There still are possible stall reasons when there are multiple nodes (all releases with proxylib):
- last proxylib listeners got removed, so proxylib will not ACK any more, while we might have sent a response expecting an ACK from proxylib previously, but this is also unlikely due to the Envoy listener drain duration being 10 minutes
- ack for the current version has been received from one node, but not from another. Currently we set up completions for all the nodes, while only one of them will send an ACK. This would resolve after a further response generating a new ACK for all the nodes, though.

Comment (jrajahalme) [reply pkg/endpointmanager/manager.go:208]: @christarazi reworked the approach based on the feedback on the draft PR. Could you have a 2nd look on the sanity of the re-triggering of policy updates on a timeout?

**Comment by jrajahalme** [comment]
@odinuge scrapped the `compeltion` API change, and instead only added a timeout to where it was missing. Also added detail from the blocking completion to the returned error so that the call site facing a timeout can log it out and learn what is going on if it still happens.

File: pkg/endpointmanager/manager.go
Comment (squeed) [reply pkg/endpointmanager/manager.go:208]: gotcha. As long as we understand why this is stalling, it seems OK for me.

@jrajahalme also observed that stuck acks often get un-stuck when we issue another policy update, so stalling is not the best route to take here.

File: pkg/endpointmanager/manager.go [hunk 1]
```diff
@@ -232,16 +234,15 @@ func (mgr *endpointManager) UpdatePolicyMaps(ctx context.Context, notifyWg *sync
...
-			notifyWg.Wait()
 			if err := ep.ApplyPolicyMapChanges(proxyWaitGroup); err != nil && !errors.Is(err, endpoint.ErrNotAlive) {
 				ep.Logger("endpointmanager").Warn("Failed to apply policy map changes. These will be re-applied in future updates.", logfields.Error, err)
 			}
 			epWG.Done()
 		}(ep)
 	}
 
-	return &wg
+	wg.Wait()
```
Comment (squeed) [inline pkg/endpointmanager/manager.go:225]: Does everything that calls UpdatePolicyMaps wait for `wg`? If not, should we return a `<-chan error`?

**Review by squeed — APPROVED** [review]
One minor question about UpdatePolicyMaps usage, otherwise LGTM.

File: pkg/endpointmanager/manager.go
Comment (christarazi) [reply pkg/endpointmanager/manager.go:208]: @jrajahalme Agree with Casey. As long as we find out why it stalls then the retriggering on timeout is sane. Because it's technically possible that we get stuck in a forever-retry loop. But if we know the reason, we could then take the appropriate action.

File: pkg/endpointmanager/manager.go [hunk 2]
```diff
@@ -196,11 +196,11 @@ func (mgr *endpointManager) waitForProxyCompletions(proxyWaitGroup *completion.W
...
 
-// UpdatePolicyMaps returns a WaitGroup which is signaled upon once all endpoints
-// have had their PolicyMaps updated against the Endpoint's desired policy state.
+// UpdatePolicyMaps applies incremental policy map changes and waits for Envoy to have applied the
+// new policy. Returns the error from the wait on proxy completions.
 //
-// Endpoints will wait on the 'notifyWg' parameter before updating policy maps.
-func (mgr *endpointManager) UpdatePolicyMaps(ctx context.Context, notifyWg *sync.WaitGroup) *sync.WaitGroup {
+// The configured EndpointPolicyUpdateTimeout will be applied on the given context.
+func (mgr *endpointManager) UpdatePolicyMaps(ctx context.Context) error {
```
Comment (odinuge) [inline pkg/endpointmanager/manager.go:203]: Would it be better to to rewrite this func to remove the first goroutine? The current flow feels very unintuitive when we block on all of the goroutines before returning after all..

Something along the line of this maybe?;

```go
func (mgr *endpointManager) UpdatePolicyMaps(ctx context.Context) error {
	var epWG sync.WaitGroup

	ctx, cancel := context.WithTimeout(ctx, mgr.config.EndpointPolicyUpdateTimeout)
	defer cancel()

	proxyWaitGroup := completion.NewWaitGroup(ctx)

	eps := mgr.GetEndpoints()

	// TODO: bound by number of CPUs?
	for _, ep := range eps {
		epWG.Go(func() {
			if err := ep.ApplyPolicyMapChanges(proxyWaitGroup); err != nil && !errors.Is(err, endpoint.ErrNotAlive) {
				ep.Logger("endpointmanager").Warn("Failed to apply policy map changes. These will be re-applied in future updates.", logfields.Error, err)
			}
		})
	}

	epWG.Wait()

	waitErr := mgr.waitForProxyCompletions(proxyWaitGroup)
	if waitErr != nil {
		mgr.logger.Warn("Failed to apply L7 proxy policy changes. These will be re-applied in future updates.", logfields.Error, waitErr)
	}

	// Perform policy update call if required.
	// This should not block the main flow for Endpoint.
	mgr.policyUpdateCallback(&sync.WaitGroup{}, nil, true)

	return waitErr
}
```

It would be a bit more tricky to backport maybe, but its much easier to understand the flow that way imo.

Comment (jrajahalme) [reply pkg/endpointmanager/manager.go:203]: Right, will remove the first goroutine!

File: pkg/endpointmanager/manager.go (hunk 1 above)
Comment (jrajahalme) [reply pkg/endpointmanager/manager.go:225]: Yes, there is only one caller, in `doUpdatePolicyMaps`.

**Comment by odinuge** [comment]
I don't have too much context on the `cell` setup here, or the envoy ACK/NACK setup. But the wg/completion related stuff looks good from my pov now 👍 

But I'm curious what you are thinking about backporting here? Ideally we can get #44328 backported to all stable releases due to the leak it fixes - but this PR should also fix the same (at least the one in UpdatePolicyMaps) leak as well. But this seems pretty likely to cause a lot of conflicts on older branches.

File: pkg/policy/cell/identity_updater.go [hunk 3]
```diff
@@ -206,15 +207,24 @@ func (i *identityUpdater) doUpdatePolicyMaps(ctx context.Context) error {
 		return ctx.Err()
 	}
 
-	// UpdatePolicyMaps also waits for notifications to be complete, but we already waited :-)
-	noopWG := &sync.WaitGroup{}
-
 	// Direct all endpoints to consume the incremental changes and update policy.
 	// This returns a wg that is done when all endpoints have updated both their bpf
 	// policymaps as well as Envoy. (Or if ctx is closed).
```
Comment (vipul-21) [inline pkg/policy/cell/identity_updater.go:212]: The `UpdatePolicyMaps` no longer returns a `wg`. We should update this comment to match the new behavior of returning an error.

File: pkg/endpoint/bpf.go [hunk 4]
```diff
@@ -1170,10 +1167,6 @@ func (e *Endpoint) applyPolicyMapChangesLocked(regenContext *regenerationContext
 			if err == nil {
 				datapathRegenCtxt.revertStack.Push(rf)
 			}
-		} else if hasEnvoyRedirect {
-			// Wait for a possible ongoing update to be done if there were no current changes.
-			e.getLogger().Debug("applyPolicyMapChanges: Using current Networkpolicy")
-			e.proxy.UseCurrentNetworkPolicy(e, e.desiredPolicy, proxyWaitGroup)
```
Comment (vipul-21) [inline pkg/endpoint/bpf.go:1184]: `UseCurrentNetworkPolicy` is no longer used anywhere ? We can remove this ?

**Comment by jrajahalme** [comment]
> But I'm curious what you are thinking about backporting here? Ideally we can get #44328 backported to all stable releases due to the leak it fixes - but this PR should also fix the same (at least the one in UpdatePolicyMaps) leak as well. But this seems pretty likely to cause a lot of conflicts on older branches.

Added `needs-backport` labels both here and at #44328, thanks for the remainder!

File: pkg/policy/cell/identity_updater.go (hunk 3 above)
Comment (jrajahalme) [reply pkg/policy/cell/identity_updater.go:212]: Fixed!

File: pkg/completion/completion.go [hunk 5]
```diff
@@ -105,11 +108,16 @@ Loop:
...
+			ctxErr := wg.ctx.Err()
 			for _, comp := range wg.pendingCompletions[i:] {
 				// 'comp' may have already completed on a different error
-				compErr := comp.Complete(wg.ctx.Err())
+				compErr := comp.Complete(ctxErr)
 				err = updateError(err, compErr) // Keep the most severe error value we encounter
 			}
+			// override error with the hanging completion if deadline exceeded
+			if errors.Is(ctxErr, context.DeadlineExceeded) {
+				err = fmt.Errorf("Waiting on %s: %w", comp.Id(), ctxErr)
```
Comment (tommyp1ckles) [inline pkg/completion/completion.go:119]: Won't the comp here always refer to the last comp we processed, since we don't break out on a ctxErr.

File: pkg/endpoint/bpf.go (hunk 4 above)
Comment (jrajahalme) [reply pkg/endpoint/bpf.go:1184]: Removed dead code.

File: pkg/completion/completion.go (hunk 5 above)
Comment (jrajahalme) [reply pkg/completion/completion.go:119]: The loop above says `for _, comp := range ...`, so it is not reusing the `comp` in the outer loop, will rename to make this clear and make it less likely to get broken in future. (renamed the inner `comp` as `c`.)

**Review by sayboras — APPROVED** [review]

**Review by rgo3 — APPROVED** [review]

**Comment by Artyop** [comment]
@jrajahalme marking this PR as backport/author, stable branches are missing some commits to make this work, most likely https://github.com/cilium/cilium/commit/d04ca8f4655fab96946d704660c433deb04fa60b and maybe more
