### PR TITLE
egressgateway: fix manager logic

### LINKED ISSUE #17380: egress gw: Sync and remove obsolete policies upon startup
If cilium-agent goes down, and meanwhile DEL CiliumEgressNatPolicy `A` happens, upon the startup cilium-agent won't receive ADD CiliumEgressNatPolicy `A` and DEL CiliumEgressNatPolicy `A` events. This means that the policy `A` will continue residing in the BPF map and being effective, which is a bug.

To remove the obsolete policy we need to wait for the cache to sync and then to remove obsolete policies from the BPF map (similarly as it's done in `SyncWithK8sFinished()` in `pkg/services/`).

### LINKED ISSUE #17753: Short interruption of egress gateway functionality on `CiliumEgressNATPolicy` updates
The logic to update the BPF map and agent caches on `CiliumEgressNATPolicy` updates starts by [removing all policies matching the endpoints](https://github.com/cilium/cilium/blob/203fb2ee27a8faf5dde6cd29553d51d0bc90bb15/pkg/egressgateway/manager.go#L156-L171) before [adding the new versions back](https://github.com/cilium/cilium/blob/203fb2ee27a8faf5dde6cd29553d51d0bc90bb15/pkg/egressgateway/manager.go#L173-L186). As result, the egress gateway feature in the datapath may shortly stop working during the update.

For example, changing `destinationCIDRs` to `192.168.33.0/24` in the following policy may break connections already established for `192.168.33.13/32` because packets may shortly not be redirected and SNATed with a different IP address.
```
apiVersion: cilium.io/v2alpha1
kind: CiliumEgressNATPolicy
metadata:
  name: egress-sample
spec:
  egress:
  - podSelector:
      matchLabels:
        org: empire
        class: mediabot
  destinationCIDRs:
  - 192.168.33.13/32
  egressSourceIP: "192.168.33.100"
```

Note I have not tested this bug; this is just based on a code review.

cc @MasterZ40 @anfernee

### PR DESCRIPTION
**Pull request by jibi**
This PR refactors the egress gateway manager in order to provide a
single `reconcile()` method, responsible for adding and removing entries
to and from the egress_policy map, that will be invoked on all events
received by the manager.

In addition to this, the manager will now wait for the k8s cache to be
fully synced before running its first reconciliation, in order to always
have the egress_policy map in a consistent state with the k8s
configuration.

Fixes: #17380
Fixes: #17753

### CODE REVIEW

**Comment by jibi** [comment]
retest-4.9

**Comment by jibi** [comment]
retest-49

**Comment by jibi** [comment]
/test-4.9

File: cilium/cmd/bpf_egress_get.go [hunk 1]
```diff
@@ -43,13 +42,11 @@ var bpfEgressGetCmd = &cobra.Command{
...
 
-		key := egressmap.NewKey(sip, dip, ipv4Mask)
-
-		if value, err = egressmap.EgressMap.Lookup(&key); err != nil {
+		if value, err = egressmap.EgressPolicyMap.Lookup(sip, net.IPNet{IP: dip, Mask: ipv4Mask}); err != nil {
 			Fatalf("error lookup contents of map: %s\n", err)
 		}
 
-		fmt.Println(value.String())
+		fmt.Printf("%s %s", value.GetGatewayIP(), value.GetEgressIP())
```
Comment (pchaigno) [inline cilium/cmd/bpf_egress_get.go]: Nit: Could we put this into a `EgressPolicyVal4.String()` method as before?

File: cilium/cmd/bpf_egress_list.go [hunk 2]
```diff
@@ -15,20 +18,45 @@ import (
 )
 
 const (
-	egressListUsage = "List egress entries.\n" + lpmWarningMessage
+	egressListUsage = "List egress policy entries.\n" + lpmWarningMessage
 )
 
+type EgressPolicy struct {
```
Comment (pchaigno) [inline cilium/cmd/bpf_egress_list.go]:
```suggestion
type egressPolicy struct {
```

File: cilium/cmd/bpf_egress_list.go [hunk 3]
```diff
@@ -15,20 +18,45 @@ import (
...
+	Short:   "List egress policy entries",
 	Long:    egressListUsage,
 	Run: func(cmd *cobra.Command, args []string) {
 		common.RequireRootPrivilege("cilium bpf egress list")
 
-		bpfEgressList := make(map[string][]string)
-		if err := egressmap.EgressMap.Dump(bpfEgressList); err != nil {
-			Fatalf("error dumping contents of map: %s\n", err)
+		if err := egressmap.OpenEgressMaps(); err != nil {
+			if errors.Is(err, fs.ErrNotExist) {
```
Comment (pchaigno) [inline cilium/cmd/bpf_egress_list.go:40]: This calls into `ebpf.OpenMap` (cilium/cilium) which relies on `ebpf.LoadPinnedMap` (cilium/ebpf). But as far as I could see `ebpf.LoadPinnedMap` never returns `ErrNotExist`. Did I miss something?

**Review by errordeveloper — APPROVED** [review]

File: cilium/cmd/bpf_egress_list.go [hunk 4]
```diff
@@ -41,13 +69,23 @@ var bpfEgressListCmd = &cobra.Command{
 		if len(bpfEgressList) == 0 {
 			fmt.Fprintf(os.Stderr, "No entries found.\n%v\n", lpmWarningMessage)
 		} else {
-			TablePrinter("SRC IP & DST CIDR", "EGRESS INFO", bpfEgressList)
+			printEgressList(bpfEgressList)
```
Comment (pchaigno) [inline cilium/cmd/bpf_egress_list.go:72]: I'm guessing you're not using `TablePrinter` here because it shows map contents separated in only two columns and you'd prefer four columns? Could we extend `TablePrinter` instead to support multiple columns? (Probably best done in another PR.)

File: pkg/maps/egressmap/egress.go [hunk 5]
```diff
@@ -4,79 +4,72 @@
...
-type Key4 struct {
-	// PrefixLen is full 32 bits of SourceIP + DestCIDR's mask bits
-	PrefixLen uint32
+var log = logging.DefaultLogger.WithField(logfields.LogSubsys, "map-egress")
 
-	SourceIP types.IPv4
-	DestCIDR types.IPv4
-}
+const (
+	PolicyMapName = "cilium_egress_policy_v4"
```
Comment (pchaigno) [inline pkg/maps/egressmap/egress.go]: Won't the map name change cause a short connectivity blip on upgrade for egress gateway connections? Probably fine given it's a beta feature, but should we document it?

File: pkg/egressgateway/manager.go [hunk 6]
```diff
@@ -191,104 +152,93 @@ func (manager *Manager) OnDeleteEndpoint(endpoint *k8sTypes.CiliumEndpoint) {
...
+			egressPolicies[*key] = *val
+		})
+
+nextPolicyKey:
+	for policyKey, policyVal := range egressPolicies {
+		for _, policyConfig := range manager.policyConfigs {
+			for _, endpoint := range manager.epDataStore {
+				if !policyConfig.selectsEndpoint(endpoint) {
+					continue
+				}
```
Comment (pchaigno) [inline pkg/egressgateway/manager.go:227]: Nit: These 5 lines could be moved outside the `egressPolicies` loop, to avoid computing the same thing for each egress policy.

File: pkg/egressgateway/manager.go [hunk 7]
```diff
@@ -191,104 +152,93 @@ func (manager *Manager) OnDeleteEndpoint(endpoint *k8sTypes.CiliumEndpoint) {
...
+// Whenever it encounters an error, it will just log it and move to the next
+// item, in order to reconcile as many states as possible.
+func (manager *Manager) reconcile() {
+	if !manager.k8sCacheSyncedChecker.K8sCacheIsSynced() {
+		return
 	}
-	return nil
+
+	manager.addMissingEgressRules()
+	manager.removeUnusedEgressRules()
```
Comment (pchaigno) [inline pkg/egressgateway/manager.go:266]: The order of those two calls seems to matter for updated entries, as we would otherwise remove them before updating them. Is it worth a comment?

File: pkg/egressgateway/manager_privileged_test.go [hunk 8]
```diff
@@ -0,0 +1,262 @@
...
+	// Add a new endpoint which matches policy-2
+	ep2 := newEndpoint("ep-2", ep2IP, ep2Labels)
+	egressGatewayManager.OnUpdateEndpoint(&ep2)
+
+	assertEgressRules(c, []egressRule{
+		{ep1IP, destCIDR, egressIP1, egressIP1},
+		{ep2IP, destCIDR, egressIP2, egressIP2},
+	})
+
+	// Update the endpoint labels for polikcy-1 in order for it to not be a match
```
Comment (pchaigno) [inline pkg/egressgateway/manager_privileged_test.go]: Nit:
```suggestion
	// Update the endpoint labels for policy-1 in order for it to not be a match
```

File: bpf/lib/egress_gateway.h [hunk 9]
```diff
@@ -1,12 +1,22 @@
 /* SPDX-License-Identifier: GPL-2.0 */
 /* Copyright (C) 2021 Authors of Cilium */
 
-#ifndef __LIB_EGRESS_POLICIES_H_
-#define __LIB_EGRESS_POLICIES_H_
```
Comment (pchaigno) [inline bpf/lib/egress_gateway.h]: Can we keep this and the filename as is? It was done on purpose since this same file will inherit the SRv6 egress policies as well.

**Review by pchaigno — COMMENTED** [review]
Mostly nits.

File: cilium/cmd/bpf_egress_list.go (hunk 3 above)
Comment (jibi) [reply cilium/cmd/bpf_egress_list.go:40]: `ebpf.LoadPinnedMap` will call into `sys.ObjGet`, which in turn will call `sys.BPF`, and the BPF syscall there can return `ENOENT`:

```
vagrant@k8s1:~$ sudo cilium bpf egress list
Cannot find egress gateway bpf maps
```

File: cilium/cmd/bpf_egress_list.go (hunk 4 above)
Comment (jibi) [reply cilium/cmd/bpf_egress_list.go:72]: ~Whops, just a leftover from another branch (but in this case we can definitely use the `TablePrinter`, will switch to it :+1: )~

edit: sorry, I got confused, let's keep it like this for now, I'll look into extending the `TablePrinter` helper to support multiple columns in a separate PR

File: pkg/maps/egressmap/egress.go (hunk 5 above)
Comment (jibi) [reply pkg/maps/egressmap/egress.go]: > Won't the map name change cause a short connectivity blip on upgrade for egress gateway connections? Probably fine given it's a beta feature

yep, I remember asking for that and we said it was acceptable given the beta status

> but should we document it?

will add a note in the docs :+1:

File: pkg/egressgateway/manager.go (hunk 7 above)
Comment (jibi) [reply pkg/egressgateway/manager.go:266]: Yep, order matters here, will add a comment :+1:

File: cilium/cmd/bpf_egress_list.go (hunk 3 above)
Comment (pchaigno) [reply cilium/cmd/bpf_egress_list.go:40]: Ah, of course! :facepalm: Thanks!

File: pkg/egressgateway/manager.go (hunk 6 above)
Comment (jibi) [reply pkg/egressgateway/manager.go:227]: I don't think it's possible as for each entry in the bpf map we necessarily need to test all k8s policies. The pseudocode would be:

```
nextEntry:
for each entry in the egress_policy map {
    for each policy in k8s egressnatpolicies {
        if policy matches entry {
            // we found one k8s policy that matches the current BPF entry, move to the next one
            continue nextEntry
        }
    }

    // the current BPF entry is not backed by any k8s policy, delete it
    egressmap.RemoveEgressPolicy()
}
```

(while if we start looping from k8s policies, we would not be able to tell if a given BPF entry needs to be deleted or not)

I'll add a comment to clarify this

**Comment by jibi** [comment]
/test-5.4

**Comment by jibi** [comment]
/test-5.4

File: Documentation/cmdref/cilium_bpf_egress.md [hunk 10]
```diff
@@ -23,6 +23,6 @@ Manage the egress routing rules
 * [cilium bpf](../cilium_bpf)	 - Direct access to local BPF maps
 * [cilium bpf egress delete](../cilium_bpf_egress_delete)	 - Delete egress entries
 * [cilium bpf egress get](../cilium_bpf_egress_get)	 - Get egress entries
-* [cilium bpf egress list](../cilium_bpf_egress_list)	 - List egress entries
+* [cilium bpf egress list](../cilium_bpf_egress_list)	 - List egress policy entries
```
Comment (kkourt) [inline Documentation/cmdref/cilium_bpf_egress.md:26]: [Elsewhere](https://github.com/cilium/cilium/pull/17868#discussion_r749211292), @pchaigno mentioned that there are SRv6 egress policies coming. Will these policies be on the same map or another one? In the latter case, maybe we should refer to this map as egress gw policies?

File: cilium/cmd/bpf_egress_list.go [hunk 11]
```diff
@@ -41,13 +69,23 @@ var bpfEgressListCmd = &cobra.Command{
...
 		}
 	},
 }
 
-func init() {
+func printEgressList(egressList []egressPolicy) {
+	w := tabwriter.NewWriter(os.Stdout, 5, 0, 3, ' ', 0)
+
+	fmt.Fprintln(w, "Source IP\tDestination CIDR\tEgress IP\tGateway IP")
```
Comment (kkourt) [inline cilium/cmd/bpf_egress_list.go:80]: Thanks! a description of the various fields was definitely missing!

File: pkg/egressgateway/manager.go [hunk 12]
```diff
@@ -34,94 +20,96 @@ var (
...
+	manager.runReconciliationAfterK8sSync()
+
+	return manager
+}
+
+// runReconciliationAfterK8sSync spawns a goroutine that waits for the agent to
+// sync with k8s and then runs the first reconciliation.
+func (manager *Manager) runReconciliationAfterK8sSync() {
+	go func() {
+		for range time.NewTicker(time.Second * 1).C {
```
Comment (kkourt) [inline pkg/egressgateway/manager.go]: Do we need to grab the lock before checking if the cache is synced?

I'm not familiar with the details of the code, and I'm not clear on what the `mutex` actually protects. There are two potential reasons for needing the lock here:
1. we are using an internal field of `manager` (k8sCacheSyncedChecker). Does this needs to be protected by the mutex?
1. again, without knowing too much about the code, it seems possible that the cache will become unsynced after we break and before we take the lock. Do we care about that? If yes, can we use the lock to ensure that we always run reconcile with a synced cache?

**Review by kkourt — APPROVED** [review]
Some non-blocking comments from my side.

File: Documentation/cmdref/cilium_bpf_egress.md (hunk 10 above)
Comment (jibi) [reply Documentation/cmdref/cilium_bpf_egress.md:26]: (not sure, but this seems to me a bit out of scope for the current PR)

Comment (kkourt) [reply Documentation/cmdref/cilium_bpf_egress.md:26]: I thought that since we are chancing the name anyway, we could use "List egress gateway policy entries". Follow up is fine as well.

File: pkg/egressgateway/manager.go (hunk 12 above)
Comment (jibi) [reply pkg/egressgateway/manager.go]: A bit of context here: the `k8sCacheSyncedChecker` field is just an interface for an object that implements the `K8sCacheIsSynced` method. In this case we are passing the `Daemon` to the egress gw manager, which implements it as:

https://github.com/cilium/cilium/blob/b12ecd16302da5943379f1d7e088e07a61c2f3e4/daemon/cmd/daemon.go#L1037-L1046

This method just checks if the `k8sCachesSynced` channel is closed, which happens only after the initial k8s sync (i.e. after the agent has received all the k8s state it cares about from the apiserver during initialization). After that it will remain closed (we cannot go back to an unsycned state). 

Because of this, I don't think we need to acquire the manager's lock (which is supposed to protect the manager internal state from concurrent accesses) to run this check

Comment (joamaki) [inline pkg/egressgateway/manager.go]: You'll need to `Stop()` the ticker, otherwise (I think) this leaks resources.You could just do loop with time.Sleep instead...

Though in this case, since `K8sCacheIsSynced` is just waiting on `d.k8sCachesSynced`, 
why not just do a blocking receive on `d.k8sCachesSynced` instead?

E.g. add something like:
```
func (d *Daemon) WaitUntilK8sCacheIsSynced() {
  _, _ = <-d.k8sCachesSynced
}
```

File: pkg/maps/egressmap/egress.go [hunk 13]
```diff
@@ -4,79 +4,72 @@
...
+		logfields.DestinationCIDR: destCIDR,
+		logfields.EgressIP:        egressIP,
+		logfields.GatewayIP:       gatewayIP,
+	})
+
+	if err := EgressPolicyMap.Update(sourceIP, destCIDR, egressIP, gatewayIP); err != nil {
+		return fmt.Errorf("cannot apply egress policy: %w", err)
+	}
+
+	logger.Info("Applied egress policy")
```
Comment (joamaki) [inline pkg/maps/egressmap/egress.go]: Hm, wonder if it'd be better to log both the error and success case in the same place? When I looked at this function I immediately wondered if we log the returned error somewhere (yep, in OnAddEgressPolicy) and if we log it with enough details.

File: pkg/maps/egressmap/egress.go [hunk 14]
```diff
@@ -4,79 +4,72 @@
...
+		return err
+	}
 
-	copy(result.SourceIP[:], src.To4())
-	copy(result.DestCIDR[:], dst.To4())
-	result.PrefixLen = getStaticPrefixBits() + uint32(ones)
+	log.WithFields(logrus.Fields{
+		logfields.SourceIP:        sourceIP,
+		logfields.DestinationCIDR: destCIDR,
+	}).Info("Removed egress policy")
```
Comment (joamaki) [inline pkg/maps/egressmap/egress.go]: Same issue here with logging as in ApplyEgressPolicy.

**Review by joamaki — CHANGES_REQUESTED** [review]

**Review by qmonnet — APPROVED** [review]
I only did had a quick look at the changes, and all look in order to me. I'll look more in-depth if I can find a moment, but I trust the other people who looked in more details.

As for the few changes falling under `docs-structure`, this looks all good.

File: pkg/egressgateway/manager.go (hunk 12 above)
Comment (jibi) [reply pkg/egressgateway/manager.go]: Good shout, switched to `WaitUntilK8sCacheIsSynced`  :+1:

File: pkg/maps/egressmap/egress.go (hunk 13 above)
Comment (jibi) [reply pkg/maps/egressmap/egress.go]: Yep, makes sense. I moved all the logging into the manager and also got rid of `egressmap.{ApplyEgressPolicy, RemoveEgressPolicyMap}` since those methods where just wrapping a single function call (`egressmap.EgressPolicyMap.{Update, Delete}`)

**Review by joamaki — APPROVED** [review]

**Comment by jibi** [comment]
/test-5.4

File: bpf/lib/egress_policies.h [hunk 15]
```diff
@@ -34,25 +44,16 @@ is_cluster_destination(struct iphdr *ip4, __u32 dst_id, __u32 tunnel_endpoint)
...
-		.dip = dip,
+		.saddr = saddr,
+		.daddr = daddr,
 	};
-	return map_lookup_elem(map, &key);
+	return map_lookup_elem(&EGRESS_POLICY_MAP, &key);
 }
 
-# define lookup_ip4_egress_endpoint(sip, dip) \
-	egress_lookup4(&EGRESS_MAP, sip, dip)
```
Comment (pchaigno) [inline bpf/lib/egress_policies.h:56]: FYI, I'll have to revert all changes to this file in the SRv6 PR, except for the map/key name changes.

EDIT: Actually, I can preserve this function name change as well, doesn't make a different for SRv6 for now.
