### PR TITLE
pkg/endpoint: fix stuck state "restoring" when restoring endpoints

### LINKED ISSUE #2167: Endpoints stuck in `restoring` state after Cilium DS recreation
### General Information

- Kernel version: `Linux k8s1 4.10.0-38-generic #42-Ubuntu SMP Tue Oct 10 13:24:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- `kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.11", GitCommit:"b13f2fd682d56eab7a6a2b5a1cab1a3d2c8bdd55", GitTreeState:
"clean", BuildDate:"2017-11-25T18:34:52Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.11", GitCommit:"b13f2fd682d56eab7a6a2b5a1cab1a3d2c8bdd55", GitTreeState:
"clean", BuildDate:"2017-11-25T17:51:39Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

### How to reproduce the issue

1. checkout code from https://github.com/cilium/cilium/pull/2166
2. run `K8S_VERSION=1.7 ginkgo --race -v -focus="Nightly" test`

Expected outcome: tests pass as endpoints become ready after cilium redeployent.
Actual outcome: tests timeout on measurement of restoring endpoints.

The root cause is that all endpoints have `restoring` status in `cilium endpoint list`. It can be verified by running `vagrant ssh k8s1-1.7 -- kubectl exec -n kube-system <cilium-pod-id> cilium endpoint list `.

Example output:
```
ENDPOINT   POLICY        IDENTITY   LABELS (source:key[=value])                   IPv6                   IPv4          STATUS
           ENFORCEMENT
173        Disabled      946        k8s:io.kubernetes.pod.namespace=kube-system   f00d::a0a:100:0:ad     10.10.1.66    restoring
                                    k8s:k8s-app=kube-dns
174        Disabled      950        k8s:id=app0                                   f00d::a0a:100:0:ae     10.10.1.67    restoring
                                    k8s:io.kubernetes.pod.namespace=default
                                    k8s:zgroup=testapp
13949      Disabled      954        k8s:id=app1                                   f00d::a0a:100:0:367d   10.10.1.32    restoring
                                    k8s:io.kubernetes.pod.namespace=default
                                    k8s:zgroup=testapp
15124      Disabled      955        k8s:id=app7                                   f00d::a0a:100:0:3b14   10.10.1.37    restoring
                                    k8s:io.kubernetes.pod.namespace=default
                                    k8s:zgroup=testapp
29381      Disabled      951        k8s:id=app4                                   f00d::a0a:100:0:72c5   10.10.1.59    restoring
                                    k8s:io.kubernetes.pod.namespace=default
                                    k8s:zgroup=testapp
48896      Disabled      952        k8s:id=app6                                   f00d::a0a:100:0:bf00   10.10.1.142   restoring
                                    k8s:io.kubernetes.pod.namespace=default
                                    k8s:zgroup=testapp
60670      Disabled      953        k8s:id=app2                                   f00d::a0a:100:0:ecfe   10.10.1.193   restoring
                                    k8s:io.kubernetes.pod.namespace=default
                                    k8s:zgroup=testapp

```

### PR DESCRIPTION
**Pull request by aanm**
This commits fixes the stuck state "restore" while restoring the
endpoints by checking properly setting the waiting to regenerate state
machine before calling the endpoint.Regenerate function.

Signed-off-by: André Martins <andre@cilium.io>

Fixes: #2167

```release-note
Fix stuck "restoring" state while restoring the endpoints #2167
```

### CODE REVIEW

**Review by ianvernon — APPROVED** [review]

File: daemon/state.go [hunk 1]
```diff
@@ -75,6 +75,7 @@ func (d *Daemon) SyncState(dir string, clean bool) error {
 
 			ep.Mutex.Lock()
 			scopedLog.Debug("Restoring endpoint")
+			ep.LogStatusOKLocked(endpoint.Other, "Restoring endpoint from previous cilium instance")
```
Comment (raybejjani) [inline daemon/state.go:78]: It doesn't matter too much but maybe make the log message right above the same? so someone grepping for it in the logs can find it more easily

File: pkg/endpoint/endpoint.go [hunk 2]
```diff
@@ -1103,6 +1103,15 @@ func (e *Endpoint) LogStatusOK(typ StatusType, msg string) {
 	e.LogStatus(typ, OK, msg)
```
Comment (raybejjani) [inline pkg/endpoint/endpoint.go:1103]: Should this line use LogStatusOKLocked below to be consistent?

**Review by raybejjani — APPROVED** [review]

**Review by manalibhutiyani — APPROVED** [review]

File: daemon/state.go [hunk 3]
```diff
@@ -97,13 +98,14 @@ func (d *Daemon) SyncState(dir string, clean bool) error {
...
 
+			ep.LogStatusOKLocked(endpoint.Other, "Synchronizing endpoint labels with KVStore")
 			if err := d.syncLabels(ep); err != nil {
 				scopedLog.WithError(err).Warn("Unable to restore endpoint")
 				ep.Mutex.Unlock()
 				epRegenerated <- false
 				return
 			}
-			ready := ep.SetStateLocked(endpoint.StateRestoring, "Triggering synchronous endpoint regeneration while syncing state to host")
+			ready := ep.SetStateLocked(endpoint.StateWaitingToRegenerate, "Triggering synchronous endpoint regeneration while syncing state to host")
```
Comment (jrajahalme) [inline daemon/state.go:108]: I'm late in the game but is this change needed given that you also changed regenerateBPF() to recognize `StateRestoring`? Or the other way around, when this change is made, do we ever call regenerateBPF() while the endpoint's state is `StateRestoring`?

Comment (raybejjani) [reply daemon/state.go:108]: (I'm not aanm but we had chatted about this)
I think the idea was to more consistently enter `WaitingToRegenerate` and then `Regenerating`. While `regenerateBPF` does try to switch to `Regenerating` even if the state is `Restoring` (because we removed the `!=` check on line 425 in `regenerateBPF`) the state machine itself in `BuilderSetState` won't allow that transition. With this change the endpoint follows the same state progression it would if it was being normally created, or had a regeneration triggered for any other reason (there's a nice cycle of Ready -> WaitingToRegenerate -> Regenerating -> Ready that seems to be our normal operational state).
So, to answer your actual question: it's needed unless we change the state machine. This seemed like the simpler option.
On whether we call `regenerateBPF` while `Restoring`: I don't know. Hopefully not but it would then trigger an error. I would argue this is desirable since we can then fix it but there are many callpaths so that might be a lot of work :(

Comment (aanm) [reply daemon/state.go:108]: @jrajahalme IIRC regenerateBPF no longer recognizes `StateRestoring`
