### PR TITLE
Fix native routing cidr missing flag in daemon

### LINKED ISSUE #12130: CI: K8sServicesTest Bookinfo Demo Tests bookinfo demo
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Kernel/k8s-1.17-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:512
Unable to connect from "reviews-v1-75cfdb45f-5z5kq" to "ratings.default.svc.cluster.local:9080/health"
Expected command: kubectl exec -n default reviews-v1-75cfdb45f-5z5kq -- wget --tries=2 --connect-timeout 5 ratings.default.svc.cluster.local:9080/health 
To succeed, but it failed:
Exitcode: 4 
Stdout:
 	 
Stderr:
 	 --2020-06-16 20:47:44--  http://ratings.default.svc.cluster.local:9080/health
	 Resolving ratings.default.svc.cluster.local (ratings.default.svc.cluster.local)... 10.100.69.129
	 Connecting to ratings.default.svc.cluster.local (ratings.default.svc.cluster.local)|10.100.69.129|:9080... failed: Connection timed out.
	 Retrying.
	 
	 --2020-06-16 20:47:50--  (try: 2)  http://ratings.default.svc.cluster.local:9080/health
	 Connecting to ratings.default.svc.cluster.local (ratings.default.svc.cluster.local)|10.100.69.129|:9080... failed: Connection timed out.
	 Giving up.
	 
	 command terminated with exit code 4
	 

/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Kernel/k8s-1.17-gopath/src/github.com/cilium/cilium/test/k8sT/Services.go:1710
```

First `wget` that is allowed fails after policy import. Logs indicate that policy has been loaded and waited for. Same traffic succeeded before policy import. While the policy is an L7 policy, bpf policy map indicates no bytes/packets have been redirected to the proxy port, i.e., the packets have been dropped:
```
/sys/fs/bpf/tc/globals/cilium_policy_03066:

DIRECTION   IDENTITY   PORT/PROTO   PROXY PORT   BYTES   PACKETS   
Ingress     1          ANY          NONE         0       0         
Ingress     1665       9080/TCP     12076        0       0         
Ingress     17588      9080/TCP     12076        0       0         
Ingress     19077      9080/TCP     12076        0       0         
Egress      0          ANY          NONE         1850    16        
```

The remote identity is `19077`, and ipcache should have made the correct identity mapping:
```
10.10.1.43/32                   19077 0 192.168.36.12 
```
[9f1afa3c_K8sServicesTest_Bookinfo_Demo_Tests_bookinfo_demo.zip](https://github.com/cilium/cilium/files/4791026/9f1afa3c_K8sServicesTest_Bookinfo_Demo_Tests_bookinfo_demo.zip)

### PR DESCRIPTION
**Pull request by aanm**
Fixes: #12130

### CODE REVIEW

**Comment by aanm** [comment]
test-me-please

**Review by pchaigno — APPROVED** [review]

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-gke

**Review by tklauser — APPROVED** [review]

File: daemon/cmd/daemon_main.go [hunk 1]
```diff
@@ -542,6 +542,9 @@ func init() {
 	flags.Bool(option.EnableHostFirewall, false, "Enable host network policies")
 	option.BindEnv(option.EnableHostFirewall)
 
+	flags.String(option.IPv4NativeRoutingCIDR, "", "Allows to explicitly specify the CIDR for native routing. This value corresponds to the configured cluster-cidr.")
```
Comment (brb) [inline daemon/cmd/daemon_main.go:541]: Not related to your PR, but why we didn't call the flag `--cluster-cidr`?

**Comment by joestringer** [comment]
Ah I noticed this on v1.7 and just assumed that it was a bad backport.. we're depending on this helm option in the v1.7 GKE GSG at the moment as well, might be a backport candidate:

https://docs.cilium.io/en/v1.7/gettingstarted/k8s-install-gke/

**Comment by pchaigno** [comment]
> Ah I noticed this on v1.7 and just assumed that it was a bad backport.. we're depending on this helm option in the v1.7 GKE GSG at the moment as well, might be a backport candidate:
> https://docs.cilium.io/en/v1.7/gettingstarted/k8s-install-gke/

That guide has `global.native-routing-cidr`; shouldn't it be `global.nativeRoutingCidr`?

**Comment by aanm** [comment]
runtime failed because of missing flag in the `--help` section

**Comment by christarazi** [comment]
> > Ah I noticed this on v1.7 and just assumed that it was a bad backport.. we're depending on this helm option in the v1.7 GKE GSG at the moment as well, might be a backport candidate:
> > https://docs.cilium.io/en/v1.7/gettingstarted/k8s-install-gke/
> 
> That guide has `global.native-routing-cidr`; shouldn't it be `global.nativeRoutingCidr`?

@pchaigno I believe it's being fixed in https://github.com/cilium/cilium/pull/12087#discussion_r440507380

**Comment by aanm** [comment]
**k8s 4.19** failed with the flake that is going to be fixed in https://github.com/cilium/cilium/pull/12179
**runtime 4.9** failed because of the missing help option
**travis**  failed because of the missing help option
**k8s-1.18**: green
**k8s-1.11**: green

will re push with the flag set, we only need to retest-4.19

**Comment by aanm** [comment]
retest-4.19

**Comment by aanm** [comment]
retest-runtime

File: daemon/cmd/daemon_main.go (hunk 1 above)
Comment (tgraf) [reply daemon/cmd/daemon_main.go:541]: Because it is not the cluster CIDR. The native routing space might be much larger, spanning multiple clusters or even non-k8s space.

**Review by tgraf — APPROVED** [review]
