### PR TITLE
bpf: Track reply packets of egress gateway and SNATed host-local connections

### LINKED ISSUE #25110: snat_v{4,6}_rev_nat_handle_mapping passes a wrong tuple to conntrack
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

snat_v{4,6}_track_connection in snat_v{4,6}_nat_handle_mapping creates a conntrack entry that corresponds to the connection tuple before it's NATed.

For the reply packets, snat_v{4,6}_rev_nat_handle_mapping calls snat_v{4,6}_track_connection expecting to find the conntrack entry created at the previous step. However, the tuple before revSNAT contains the gateway IP instead of the client endpoint IP, therefore, the conntrack entry is not found, and a new one is created.

The reply packets should match the same entry instead, in order to prolong its expiration timeout.

### Cilium Version

Latest main a8e4873fc0b7ecc0e1fcfde1f2b3f03907094247.

### Kernel Version

Any.

### Kubernetes Version

Any.

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by gentoo-root**
Flag the egress gateway NAT entries as needs_ct, so that reply packets could extend the expiration timeout as well.

Fix the conntrack tuple matching for packets in the reply direction, so that the needs_ct flag could actually be useful. Currently, the tuple before revSNAT is used for conntrack and doesn't match the original CT entry. After the fix, the tuple is adjusted to contain data like after revSNAT, so that it could match the original CT entry and get the needs_ct flag from it.

Fixes: #25110

```release-note
Track reply packets in long-living egress gateway connections and SNATed host-local connections.
```

### CODE REVIEW

**Review by asauber — APPROVED** [review]
CLI related changes LGTM

**Comment by julianwiedmann** [comment]
:amaze: awesome stuff! Especially happy to see that we can use the optimized CT lookup in more places, I had been hoping for this.

On first thought, I feel this should be split into multiple PRs - the IPv4 fragmentation support is worth its own PR (if only to discuss what testing we have in place for it). Or are you strongly relying on this support for the reply-tracking work?

File: bpf/lib/nat.h [hunk 1]
```diff
@@ -1203,13 +1237,13 @@ snat_v4_rev_nat(struct __ctx_buff *ctx, const struct ipv4_nat_target *target, __
...
-	ret = snat_v4_rev_nat_handle_mapping(ctx, &tuple, &state, off, target, ext_err);
+	ret = snat_v4_rev_nat_handle_mapping(ctx, &tuple, has_l4_header, ct_action, &state,
+					     off, target, ext_err);
 	if (ret > 0)
 		return CTX_ACT_OK;
 	if (ret < 0)
 		return ret;
 
-rewrite_ingress:
 	return snat_v4_rewrite_ingress(ctx, &tuple, state, off);
```
Comment (julianwiedmann) [inline bpf/lib/nat.h]: Note that this is currently missing a `has_l4_header` parameter. So I think it would attempt to revSNAT the L4 port even for a fragment.

Comment (gentoo-root) [reply bpf/lib/nat.h]: Good point, thanks, it's a bug. As I'm splitting the pull requests, I think, it's more appropriate to fix it in the other pull request that fixes fragments.

(I'll also reuse has_l4_header for snat_v4_rewrite_egress instead of calculating it again.)

**Comment by julianwiedmann** [comment]
> I think, there is no strong dependency here, that is, if I close my eyes on the bug with fragments, the rest of the logic in that switch is good enough for the optimized CT lookup. As IPv4 fragmentation fix turned to be not straightforward, I'll follow your advice and split the pull request, so that we could get the egress gateway fix merged first.

Full-on :see_no_evil: then. It's been like that forever, a few more days likely won't hurt.

We can always add a trivial `if (fragment) return NAT_PUNT_TO_STACK` stop-gap if you hate it too much :smile:.

File: bpf/lib/nat.h [hunk 2]
```diff
@@ -338,9 +339,10 @@ static __always_inline int snat_v4_track_connection(struct __ctx_buff *ctx,
 	memcpy(&tmp, tuple, sizeof(tmp));
 
 	where = dir == NAT_DIR_INGRESS ? CT_INGRESS : CT_EGRESS;
+	ipv4_ct_tuple_swap_ports(&tmp);
```
Comment (julianwiedmann) [inline bpf/lib/nat.h:350]: Mind adding a short comment here why the swap is needed? (the callers extract the ports as-is, but CT wants tuples with swapped tuples)

File: bpf/lib/nat.h [hunk 3]
```diff
@@ -338,9 +339,10 @@ static __always_inline int snat_v4_track_connection(struct __ctx_buff *ctx,
...
 
-	ret = ct_lookup4(get_ct_map4(&tmp), &tmp, ctx, off, where,
-			 &ct_state, &monitor);
+	ret = ct_lazy_lookup4(get_ct_map4(&tmp), &tmp, ctx, off, has_l4_header,
+			      ct_action, where, &ct_state, &monitor);
```
Comment (julianwiedmann) [inline bpf/lib/nat.h:353]: Mind splitting `bpf: Reuse the NAT tuple for ct_lookup4` into two patches - one trivial refactor that only does the rename & introduces the `action` parameter, and a second that actually adapts the IPv4 NAT code to use `ct_lazy_lookup4()` ?

I think that would make it a lot easier to follow what actually changed.

File: bpf/lib/nat.h [hunk 4]
```diff
@@ -403,7 +417,14 @@ snat_v4_rev_nat_handle_mapping(struct __ctx_buff *ctx,
...
 	*state = __snat_lookup(map, tuple);
-	ret = snat_v4_track_connection(ctx, tuple, *state, has_l4_header, ct_action,
+
+	memcpy(&tuple_revsnat, tuple, sizeof(tuple_revsnat));
+	if (*state) {
+		tuple_revsnat.daddr = (*state)->to_daddr;
+		tuple_revsnat.dport = (*state)->to_dport;
+	}
+
+	ret = snat_v4_track_connection(ctx, &tuple_revsnat, *state, has_l4_header, ct_action,
```
Comment (julianwiedmann) [inline bpf/lib/nat.h]: This chunk on its own (without the change to set `ostate->common.needs_ct = 1` for EgressGW connections) already fixes CT for replies of SNATed host connections, correct?

Then I would suggest to split this part off into its own patch, and describe the CT bug there in detail (as it actually pre-dates the EgressGW aspect). Right now the impact for such host connections isn't mentioned at all from what I can tell?

**Review by julianwiedmann — CHANGES_REQUESTED** [review]
Thank you! A few smaller change requests, mostly to highlight that we're fixing the CT lookup for more than "just" EgressGW replies. Would be good if you could adjust the PR title / description accordingly as well.

I don't quite follow why the first two patches in the series are needed - these are just cleanups, correct? Then I would suggest to split them into a follow-on PR, so this PR is easier to backport.

Note that we should also fix the IPv6 path (ie. have `snat_v6_rev_nat_handle_mapping()` revSNAT the tuple before the CT lookup), but that's perfectly fine as follow-on PR.

File: bpf/lib/nat.h (hunk 2 above)
Comment (gentoo-root) [reply bpf/lib/nat.h:350]: This comment is already present inside the function body. Is it enough, or shall I add a small note also here, at the caller site?

File: bpf/lib/nat.h (hunk 3 above)
Comment (gentoo-root) [reply bpf/lib/nat.h:353]: Done.

File: bpf/lib/nat.h (hunk 4 above)
Comment (gentoo-root) [reply bpf/lib/nat.h]: >This chunk on its own (without the change to set ostate->common.needs_ct = 1 for EgressGW connections) already fixes CT for replies of SNATed host connections, correct?

Yes.

>Then I would suggest to split this part off into its own patch, and describe the CT bug there in detail (as it actually pre-dates the EgressGW aspect).

Done.

**Review by gentoo-root — COMMENTED** [review]
> Thank you! A few smaller change requests, mostly to highlight that we're fixing the CT lookup for more than "just" EgressGW replies. Would be good if you could adjust the PR title / description accordingly as well.

Done.

> I don't quite follow why the first two patches in the series are needed - these are just cleanups, correct? Then I would suggest to split them into a follow-on PR, so this PR is easier to backport.

These were first steps in my bigger effort to unify the code. As it didn't happen, and there is indeed no dependency on the first two commits, I pushed them separately:

https://github.com/cilium/cilium/pull/25356

> Note that we should also fix the IPv6 path (ie. have `snat_v6_rev_nat_handle_mapping()` revSNAT the tuple before the CT lookup), but that's perfectly fine as follow-on PR.

Done here, no reason to postpone it.

**Comment by julianwiedmann** [comment]
> > Note that we should also fix the IPv6 path (ie. have `snat_v6_rev_nat_handle_mapping()` revSNAT the tuple before the CT lookup), but that's perfectly fine as follow-on PR.
> 
> Done here, no reason to postpone it.

:+1:  But then we now also need all the corresponding `ct_lazy_lookup6()` prep work for that path, no?

File: bpf/lib/nat.h (hunk 2 above)
Comment (julianwiedmann) [reply bpf/lib/nat.h:350]: My thinking would be that it's good to have the calling path explicitly say "yes, this case applies to me". Just because all this stuff has proven to be super-tricky, and we're definitely going to get it wrong again in the future... :).

File: bpf/lib/nat.h (hunk 4 above)
Comment (julianwiedmann) [reply bpf/lib/nat.h]: > > Then I would suggest to split this part off into its own patch, and describe the CT bug there in detail (as it actually pre-dates the EgressGW aspect).
> 
> Done.

:pray: Note that it would probably help readability if you flip the patch order around (ie. have `bpf: Use the right tuple to track connections on revSNAT` first). So that the EgressGW patch doesn't need to say
>The next commit is also required for the complete fix, otherwise the
needs_ct mark won't be matched.

, but simply sets `needs_ct`, updates the unit test and gets all the correct behaviour from the preceding fix.

**Review by julianwiedmann — CHANGES_REQUESTED** [review]
Looks good! Just need to decide whether we add the full IPv6 fix here, or punt to a separate PR.

**Comment by julianwiedmann** [comment]
> Besides that, the egress gateway test is blocked on issue #25110, and the issue says nothing about egress gateway, it's about the bug in the tuples. That means, the commit that `Fixes: #25110` would go first, but it wouldn't unblock the test blocked on `#ifdef ISSUE_25110_FIXED` that doesn't make any sense, and the next commit "Track egress gateway reply packets" would unblock the test, although it has nothing to do with fixing #25110.

Ah right, that's awkward. No worries then :).

**Review by julianwiedmann — APPROVED** [review]
Looks all good, thanks a ton @gentoo-root !

**Comment by julianwiedmann** [comment]
How do you feel about backporting this into `v1.13`? Infrastructure-wise it should be doable I think, the CT changes landed with https://github.com/cilium/cilium/pull/24795.

**Comment by pchaigno** [comment]
Would MLH add the label if I comment? :thinking: :eyes:
