### PR TITLE
test: remove 'unparallel' build tag in favor of testutils helper

### LINKED ISSUE #42182: CI: TestPrivilegedAll/IPv6/TestNodePodCIDRsChurnIPSec
## CI failure

Looking at the CI dashboard, there have been some recent flakes with this and `TestPrivilegedAll/dual/TestNodePodCIDRsChurnIPSec`

```
    scripttest.go:72: # ---------------------------------------------
    logger.go:256: time=2025-10-10T09:01:28.318Z level=INFO source=/host/vendor/github.com/cilium/hive/hive.go:373 msg="Stopping hive"
    logger.go:256: time=2025-10-10T09:01:28.319Z level=INFO source=/host/vendor/github.com/cilium/hive/hive.go:377 msg="Stopped hive" duration=472.883µs
    logger.go:256: time=2025-10-10T09:01:29.622Z level=INFO source=/host/pkg/node/bootid_linux.go:27 msg="Local boot ID" bootID=ac6d9274-02af-4849-aeaa-bd4af5959397
    ipsec_linux.go:1446: Failed cleaning XFRM state: failed to delete XFRM states (1/4) failed
        no such process
--- FAIL: TestPrivilegedAll/IPv6/TestNodePodCIDRsChurnIPSec (1.12s)
--- FAIL: TestPrivilegedAll/IPv6 (4.71s)
--- FAIL: TestPrivilegedAll (14.31s)
```

* [Example one](https://github.com/cilium/cilium/actions/runs/18401124567/job/52430554980)
* [Example two](https://github.com/cilium/cilium/actions/runs/18368952191/job/52327554817)

@cilium/sig-datapath

### PR DESCRIPTION
**Pull request by ti-mo**
- Remove the 'unparallel' build tag
- Add a linter rejecting anything other than built-in linux/darwin/windows/race tags in tests
- Namespace node tests
- Namespace ipsec tests
- Remove bitrotted node benchmarks

Let's avoid regressing in the future, please.

Node and ipsec tests no longer have any side effects in the host netns.

Fixes https://github.com/cilium/cilium/issues/42182.

- [x] Try removing SerializedTest() altogether. We should be able to reason about tests' side effects. Considering adding an import side effect to package `testutils/netns` to set `net.core.fb_tunnels_only_for_init_net=2`. It's a backwards-compat measure, not sane behaviour IMO. Then namespaced tests get clean environments out of the box, and there's no risk of new modules getting loaded before netns creation.

```release-note
Remove 'unparallel' build tag to restore editor tooling functionality
```

### CODE REVIEW

File: contrib/scripts/check-go-test-tags.sh [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+        status = 1
+      }
+    }
+  }
+  !/^\/\// && !/^$/ { nextfile }
+  END { if (status) exit 1 }
+EOF
+)
+
+find . -name "*_test.go" -print0 | xargs -0 awk -v allowed="^($allowed)$" "$script"
```
Comment (bimmlerd) [inline contrib/scripts/check-go-test-tags.sh]: non-blocking nit: could use `-exec` instead of the `-print0 | xargs -0` but 🤷

**Review by bimmlerd — APPROVED** [review]
LGTM, thanks for fighting build tags Timo 🙇

**Review by tklauser — APPROVED** [review]

**Review by christarazi — APPROVED** [review]

**Review by dylandreimerink — APPROVED** [review]

File: contrib/scripts/check-go-test-tags.sh [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+# among committers.
+allowed="linux|windows|darwin|race"
+
+script=$(cat << 'EOF'
+  /^\/\/go:build / {
+    for (i = 2; i <= NF; i++) {
+      tag = $i
+      gsub(/[^a-zA-Z0-9_]/, "", tag)
+
+      if (tag != "" && tag !~ allowed) {
```
Comment (tommyp1ckles) [inline contrib/scripts/check-go-test-tags.sh:26]: There's probably some edge cases with more complex build expressions here but should be fine for the majority of cases.

**Review by tommyp1ckles — APPROVED** [review]

File: contrib/scripts/check-go-test-tags.sh (hunk 1 above)
Comment (ti-mo) [reply contrib/scripts/check-go-test-tags.sh]: Sure, thanks!

**Review by ldelossa — APPROVED** [review]
LGTM
