### PR TITLE
test: fix Infinite loop during VM provisioning

### LINKED ISSUE #16871: CI: Potential infinite loop during VM provisioning
`test/kubernetes-test.sh`, used in the k8s-upstream CI job, has an infinite loop which can lead us to only terminate the CI job after the multiple-hours timeout, if the Cilium pods fail to get ready.
https://github.com/cilium/cilium/blob/2acf25391441213966008ff50c13499de05a212d/test/kubernetes-test.sh#L32-L41

We should at least rewrite that to use a bash function and `timeout`.

[provisioning-loop-consoleText.txt](https://github.com/cilium/cilium/files/6815254/provisioning-loop-consoleText.txt)

### PR DESCRIPTION
**Pull request by h3llix**
Fixes: #16871

An environment variable in the Jenkins file has been set up to provide a timeout for polling of Cilium Pods.

Signed-off-by: Gaurav Genani <h3llix.pvt@gmail.com>

### CODE REVIEW

File: jenkinsfiles/kubernetes-upstream.Jenkinsfile [hunk 1]
```diff
@@ -86,8 +86,12 @@ pipeline {
                 timeout(time: 150, unit: 'MINUTES')
             }
 
+            environment {
+                POLL_TIMEOUT_SECONDS=150
+            }
+
             steps {
-                sh 'cd ${TESTDIR}; vagrant ssh k8s1-${K8S_VERSION} -c "cd /home/vagrant/go/${PROJ_PATH}; sudo ./test/kubernetes-test.sh ${DOCKER_TAG}"'
+                sh 'cd ${TESTDIR}; vagrant ssh k8s1-${K8S_VERSION} -c "cd /home/vagrant/go/${PROJ_PATH}; env pollTimeout=${POLL_TIMEOUT_SECONDS} sudo ./test/kubernetes-test.sh ${DOCKER_TAG}"'
```
Comment (christarazi) [inline jenkinsfiles/kubernetes-upstream.Jenkinsfile]:
```suggestion
                sh 'cd ${TESTDIR}; vagrant ssh k8s1-${K8S_VERSION} -c "cd /home/vagrant/go/${PROJ_PATH}; sudo ./test/kubernetes-test.sh ${DOCKER_TAG}"'
```

Why is it necessary to have the `env pollTimeout=${POLL_TIMEOUT_SECONDS}` part? Why can't you use the `POLL_TIMEOUT_SECONDS` directly in the script?

File: test/kubernetes-test.sh [hunk 2]
```diff
@@ -31,16 +31,21 @@ helm template --validate install/kubernetes/cilium \
...
-    sleep 1
-done
+            echo "result match, continue with kubernetes"
+            break
+        fi
+        sleep 1
+    done
+}
+
+export -f pollCiliumPods
```
Comment (christarazi) [inline test/kubernetes-test.sh:46]: Why is this line necessary?

**Review by christarazi — CHANGES_REQUESTED** [review]

File: jenkinsfiles/kubernetes-upstream.Jenkinsfile (hunk 1 above)
Comment (h3llix) [reply jenkinsfiles/kubernetes-upstream.Jenkinsfile]: Sorry for the delay in reply. This was my first time working with Jenkins. I misunderstood that those variables need to be explicitly passed to the scripts. I'll just fix this.

File: test/kubernetes-test.sh (hunk 2 above)
Comment (h3llix) [reply test/kubernetes-test.sh:46]: That's because we are trying to create a subprocess as I am using timeout which is a Linux command. So, I just exported my function so that it could be used by child process.

Comment (christarazi) [reply test/kubernetes-test.sh:46]: :+1:, then let's add an unexport of it after its use.

File: test/kubernetes-test.sh [hunk 3]
```diff
@@ -32,16 +32,20 @@ helm template --validate install/kubernetes/cilium \
...
+pollCiliumPods () {
+  while true; do
+      result=$(kubectl -n kube-system get pods -l k8s-app=cilium | grep "Running" -c)
+      echo "Running pods ${result}"
+      if [ "${result}" == "2" ]; then
+          echo "result match, continue with kubernetes"
+          break
+      fi
+      sleep 1
+  done
```
Comment (christarazi) [inline test/kubernetes-test.sh]: Actually, we can use `until` here instead of `while true`. That'll allow us to get rid of the `break`.

File: test/kubernetes-test.sh [hunk 4]
```diff
@@ -32,16 +32,21 @@ helm template --validate install/kubernetes/cilium \
...
-    echo "Running pods ${result}"
-    if [ "${result}" == "2" ]; then
+runningPods="0"
 
-        echo "result match, continue with kubernetes"
-        break
-    fi
+pollCiliumPods () {
+  until [ "${runningPods}" == "2" ]
+  do
```
Comment (christarazi) [inline test/kubernetes-test.sh]:
```suggestion
  until [ "${runningPods}" == "2" ]; do
```

**Review by christarazi — APPROVED** [review]
Thanks!

File: test/kubernetes-test.sh (hunk 4 above)
Comment (h3llix) [reply test/kubernetes-test.sh]: I'll just fix it. And what should be the default timeout?

Comment (christarazi) [reply test/kubernetes-test.sh]: 5 mins seems reasonable to me

**Comment by h3llix** [comment]
> [#17031 (comment)](https://github.com/cilium/cilium/pull/17031#discussion_r687169973) wasn't addressed :)

Hi @christarazi. I have fixed it here [Here](https://github.com/cilium/cilium/pull/17031/commits/9ab98fed2bb3bdb6b2e7a8bad8d0c668a0be4160#diff-5b7396a53a4522682b55bc3b4bd7433ac49313b38e8398547dc2c66fdf9e2a3fR38).

**Review by christarazi — APPROVED** [review]

**Comment by christarazi** [comment]
test-me-please
