### PR TITLE
loader: dump datapath config object to disk

### LINKED ISSUE #41746: Dump load-time configuration into state directory
Currently, we don't have the equivalent of `node_config.h` and `ep_config.h` written into `/var/run/cilium/state` for runtime-specified configuration values. This needs to be addressed before releasing 1.19 to make sure sysdumps include all the necessary information to reproduce.

This issue is for `spew`ing the input structs into per-endpoint, per-interface or per-object files in the state directory.

`bpf.CollectionOptions` will likely need to be extended with a path since the final input values are only known in `LoadAndAssign` and we want to avoid having to carry code to dump the input values at every L&A call site.

### PR DESCRIPTION
**Pull request by rgo3**
For better debugging information, this commit ensures that the configuration objects with load-time config values will be written out to the state directory. With this change, sysdumps should automatically include these configuration objects that define how the datapath was configured.

Fixes: #41746

### CODE REVIEW

**Comment by rgo3** [comment]
The locations for the generated files are suggestions for now. I'm also wondering how we should remove some of them, based on configuration changes.

**Comment by ti-mo** [comment]
@rgo3 I've added some notes at https://github.com/cilium/cilium/issues/41746#issuecomment-3607619465. This became a bit simpler in that we don't want to use spew but write out our own machine-readable format (json for now) that we can read back using debug tooling. The premise stays the same.

This will need to be based on https://github.com/cilium/cilium/pull/43068.

File: pkg/bpf/collection.go [hunk 1]
```diff
@@ -287,6 +296,31 @@ func renameMaps(coll *ebpf.CollectionSpec, renames map[string]string) error {
 	return nil
 }
 
+func serializeConstants(logger *slog.Logger, opts *CollectionOptions) {
```
Comment (ti-mo) [inline pkg/bpf/collection.go]: I would return errors instead of logging and quietly continuing. CI jobs fail on `level=error`, but in a user's env, this likely won't raise alarm bells. A failure to write to the statedir is an indication that something else is afoul; we shouldn't happily continue in that case.

File: pkg/datapath/loader/base.go [hunk 2]
```diff
@@ -227,7 +227,8 @@ func (l *loader) reinitializeIPSec(lnc *datapath.LocalNodeConfiguration) error {
 		CollectionOptions: ebpf.CollectionOptions{
 			Maps: ebpf.MapOptions{PinPath: bpf.TCGlobalsPath()},
 		},
-		Constants: config.NewBPFNetwork(config.NodeConfig(lnc)),
+		Constants:  config.NewBPFNetwork(config.NodeConfig(lnc)),
+		ConfigPath: filepath.Join(option.Config.StateDir, "datapath_config", "bpf_encryption_network.cfg"),
```
Comment (ti-mo) [inline pkg/datapath/loader/base.go]: I'd keep the naming of the .c/.o file and its corresponding .json aligned.

Also, see the constants at the top of `loader/compile.go`. We could add more consts for config files for individual bpf objects.

**Review by ti-mo — COMMENTED** [review]
I like the directory structure we came up with for bpffs:
`/sys/fs/bpf/cilium/devices/<dev>/`. Could we mirror this for the statedir?

For example, config would go into `/sys/fs/bpf/cilium/devices/enp2s0/bpf_host.json`. I'm not sure where verifier logs go, but they could also be written here.

**Comment by rgo3** [comment]
The output of a config dump now looks like this:
```
root@kind-control-plane:/home/cilium# cat /var/run/cilium/state/dp_config/devices/eth0/bpf_network.json
{"AllowIcmpFragNeeded":true,"DeviceMTU":1500,"EnableExtendedIPProtocols":false,"EnableIcmpRule":true,"EnableL2Announcements":false,"EnableNetkit":false,"EnableNoServiceEndpointsRoutable":true,"EnableRemoteNodeMasquerade":false,"EthHeaderLength":14,"HostEpID":2203,"InterfaceIfindex":595,"InterfaceMAC":[2,66,172,18,0,2,0,0],"L2AnnouncementsMaxLiveness":0,"NATIPv4Masquerade":[0,0,0,0],"NATIPv6Masquerade":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"SecurityLabel":1,"VtepMask":0,"WgIfindex":0,"WgPort":0,"DirectRoutingDevIfindex":0,"HybridRoutingEnabled":false,"PolicyDenyResponseEnabled":false,"RouterIPv6":[253,0,0,16,2,68,0,0,0,0,0,0,0,0,179,77],"ServiceLoopbackIPv4":[169,254,42,1],"ServiceLoopbackIPv6":[254,128,0,0,0,0,0,0,0,0,0,0,0,0,0,1],"SupportsFibLookupSkipNeigh":true,"TracePayloadLen":128,"TracePayloadLenOverlay":192,"TracingIPOptionType":0}
```

Happy to remove the second commit, or make the cleanup less eager.

**Comment by ti-mo** [comment]
> The output of a config dump now looks like this:
> 
> ```
> root@kind-control-plane:/home/cilium# cat /var/run/cilium/state/dp_config/devices/eth0/bpf_network.json
> {"AllowIcmpFragNeeded":true,"DeviceMTU":1500,"EnableExtendedIPProtocols":false,"EnableIcmpRule":true,"EnableL2Announcements":false,"EnableNetkit":false,"EnableNoServiceEndpointsRoutable":true,"EnableRemoteNodeMasquerade":false,"EthHeaderLength":14,"HostEpID":2203,"InterfaceIfindex":595,"InterfaceMAC":[2,66,172,18,0,2,0,0],"L2AnnouncementsMaxLiveness":0,"NATIPv4Masquerade":[0,0,0,0],"NATIPv6Masquerade":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"SecurityLabel":1,"VtepMask":0,"WgIfindex":0,"WgPort":0,"DirectRoutingDevIfindex":0,"HybridRoutingEnabled":false,"PolicyDenyResponseEnabled":false,"RouterIPv6":[253,0,0,16,2,68,0,0,0,0,0,0,0,0,179,77],"ServiceLoopbackIPv4":[169,254,42,1],"ServiceLoopbackIPv6":[254,128,0,0,0,0,0,0,0,0,0,0,0,0,0,1],"SupportsFibLookupSkipNeigh":true,"TracePayloadLen":128,"TracePayloadLenOverlay":192,"TracingIPOptionType":0}
> ```

Unfortunately, this will make replaying ELF loads more complicated than it should be. Along with the ELF and the config json, we'll also need the original `BPFNetwork` struct to first unmarshal the json into to then pass to bpf.LoadCollection. This makes the process less generic. This is what I had in mind: `cilium-dbg bpf load bpf_network.o bpf_network.json` should just work without necessarily specifying which config object needs to be unmarshaled into first.

What about something like this?
```json
{
  "object": {
    "DeviceMTU": 1500,
    ...
  },
  "variables": {
    "__config_device_mtu": [ ... 1500 in bytes ... ],
  }
}
```

This way:
- the key name developers interact with on the Go side pop up in grep and are recognizable and easy to read
- we can additionally inspect the raw value that was written to .rodata to rule out any endianness issues
- tooling can simply feed `.variables[]` into CollectionSpec.Variables to get an exact replay

**Comment by joestringer** [comment]
Inheriting release blocker label from https://github.com/cilium/cilium/issues/41746. Let's coordinate to confirm someone will have the time to work on this so we can avoid a regression in debuggability for 1.19 release.

**Comment by rgo3** [comment]
Hey Joe, I've been actively working on this (well before the holidays at least :face_with_peeking_eye:). I've just resolved the conflicts with the recent loader changes, but it's mainly waiting on @ti-mo's review who's out sick at the moment. 

AFAIK he wanted to test if the changes I'm proposing here are in line with some of the tooling around analyzing and replaying datapath configs that he wants to add in the future.

**Comment by joestringer** [comment]
Cool thanks for the update. We still have a few weeks before 1.19 final, and the changes are looking fairly self-contained which means the risk should be low even if we have to introduce the change relatively late. With the blocker label applied that should help us to track this and we can always backport to the 1.19 branch once that branch is created (coming soon!).

**Review by ti-mo — APPROVED** [review]

**Review by youngnick — APPROVED** [review]
