### PR TITLE
bpf: nat: Adding a new config field to enable SNAT for remote node. #35823

### LINKED ISSUE #17177: BPF masquerading does not masquerade traffic to remote node's ExternalIP
## Bug report

We have a Cilium cluster with native routing (no encapsulation). When starting a pod on any node, the node it runs on is reachable (e.g. ping). However, other nodes external IP is *not* reachable. So if pod1 runs on node1, `ping external_ip_of_node1` works, `ping external_ip_of_node2` does not.

Each node has an internal interface (dummy0) and an external interface (external). All nodes are connected internally using a WireGuard interface (wg0) at the OS level (not managed by Cilium) so that all cluster traffic is encrypted. All external interfaces are reachable from each node.

**General Information**

- Cilium version (run `cilium version`)

```
Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), wait-for-node-init (init), clean-cilium-state (init)
Client: 1.10.3 4145278 2021-07-15T16:11:03+02:00 go version go1.16.6 linux/amd64
Daemon: 1.10.3 4145278 2021-07-15T16:11:03+02:00 go version go1.16.6 linux/amd64
```

- Kernel version (run `uname -a`)

```
Linux dev-0001 5.8.0-63-generic #71-Ubuntu SMP Tue Jul 13 15:59:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

- Orchestration system version in use (e.g. `kubectl version`, ...)

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3+k3s1", GitCommit:"1d1f220fbee9cdeb5416b76b707dde8c231121f2", GitTreeState:"clean", BuildDate:"2021-07-22T20:52:14Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3+k3s1", GitCommit:"1d1f220fbee9cdeb5416b76b707dde8c231121f2", GitTreeState:"clean", BuildDate:"2021-07-22T20:52:14Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

- Generate and upload a system zip:
```
curl -sLO https://git.io/cilium-sysdump-latest.zip && python cilium-sysdump-latest.zip
```

**How to reproduce the issue**

1. Start a network multitool pod on any node (https://github.com/Praqma/Network-MultiTool)
2. Exec into a shell of the pod
3. Ping external address: `ping 1.1.1.1` works
4. Ping own node's external address: works
5. Ping other node's external address: does *not* work

**pinging external system**

tcpdump
```
17:42:40.538395 IP 10.100.2.123 > 1.1.1.1: ICMP echo request, id 51, seq 1, length 64
17:42:40.538453 IP NODE1 > 1.1.1.1: ICMP echo request, id 61439, seq 1, length 64
17:42:40.543845 IP 1.1.1.1 > NODE1: ICMP echo reply, id 61439, seq 1, length 64
17:42:40.543892 IP 1.1.1.1 > 10.100.2.123: ICMP echo reply, id 51, seq 1, length 64
```

cilium monitor
```
Policy verdict log: flow 0x0 local EP ID 333, remote ID world, proto 1, egress, action allow, match all, 10.100.2.123 -> 1.1.1.1 EchoRequest
-> stack flow 0x0 identity 237465->world state new ifindex 0 orig-ip 0.0.0.0: 10.100.2.123 -> 1.1.1.1 EchoRequest
```

Some NAT seems to be happening here

**pinging own node**

tcpdump
```
17:38:29.191152 IP 10.100.2.123 > NODE1: ICMP echo request, id 47, seq 1, length 64
17:38:29.191219 IP NODE1 > 10.100.2.123: ICMP echo reply, id 47, seq 1, length 64
```

cilium monitor
```
-> stack flow 0x0 identity 237465->host state new ifindex 0 orig-ip 0.0.0.0: 10.100.2.123 -> NODE1 EchoRequest
-> endpoint 333 flow 0x0 identity host->237465 state reply ifindex 0 orig-ip NODE1: NODE1 -> 10.100.2.123 EchoReply
```

works

**pinging other node**

tcpdump
```
17:39:02.437350 IP 10.100.2.123 > $NODE2: ICMP echo request, id 48, seq 1, length 64
```

cilium monitor
```
Policy verdict log: flow 0x0 local EP ID 333, remote ID remote-node, proto 1, egress, action allow, match all, 10.100.2.123 -> NODE2 EchoRequest
-> stack flow 0x0 identity 237465->remote-node state new ifindex 0 orig-ip 0.0.0.0: 10.100.2.123 -> NODE2 EchoRequest
```

no response (and no NAT!)

### LINKED ISSUE #35823: Difference in cilium bpf masq compared to upstream ip-masq-agent
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

Cilium ebpf based masquerading does not perform SNAT on packets destined for a remote node, even if the node CIDR is not listed in the non-masquerade list. This behavior differs from the upstream ip-masq-agent, which SNATs all packets except those with IP CIDRs specified in the non-masquerade CIDR list in the ip-masq-agent configmap. If the node CIDR is omitted from the ip-masq-agent configmap, the upstream ip-masq-agent will SNAT packets destined for remote node IPs, as expected.

I tried to look cilium bpf snat code and found this code checking for remote identity and ignoring snat. I could be wrong. https://github.com/cilium/cilium/blob/db39851d806435062fb2b1fc8d02c390aaccef21/bpf/lib/nat.h#L669 where bpf program smartly ignores snat remote node ips.

### How can we reproduce the issue?

1. enable bpf masquerading in cilium agent.
2. Deploy this config map: **_(192.168.0.0/16 is pod cidr and node cidr is 10.10.0.0/16)_**
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ip-masq-agent
  namespace: kube-system
data:
  config: |
    nonMasqueradeCIDRs:
    - 192.168.0.0/16 
    masqLinkLocal: true

```
3. ping to remote node ip from any of the pods 
traffic won't get snat which is not expected.

```
k exec -it -n kube-system         cilium-zg2mz -- cilium bpf ipmasq list
Defaulted container "cilium-agent" out of: cilium-agent, install-cni-binaries (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), systemd-networkd-overrides (init), block-wireserver (init)
IP PREFIX/ADDRESS
192.168.0.0/16
```

00:01:46.635718 00:0d:3a:fa:50:9b > 12:34:56:78:9a:bc, ethertype IPv4 (0x0800), length 98: **192.168.1.101 > 10.10.0.5**: ICMP echo request, id 37444, seq 39, length 64

In case of upstream ip-masq-agent:

```
root@aks-nodepool1-30074333-vmss000000:/# iptables -t nat -L  IP-MASQ-AGENT
Chain IP-MASQ-AGENT (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             192.168.0.0/16       /* ip-masq-agent: local traffic is not subject to MASQUERADE */
MASQUERADE  all  --  anywhere             anywhere             /* ip-masq-agent: outbound traffic is su
```

00:22:36.014827 00:0d:3a:fa:50:9b > 12:34:56:78:9a:bc, ethertype IPv4 (0x0800), length 98: **10.10.0.4 > 10.10.0.5:** ICMP echo request, id 40417, seq 9, length 64

where 10.10.0.4 is source node ip and pod traffic get snat with node ip.

### Cilium Version

1.16

### Kernel Version

5.15

### Kubernetes Version

1.28

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by behzad-mir**
- [X] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [X] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [X] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [X] Provide a title or release-note blurb suitable for the release notes.
- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [X] Thanks for contributing!

Following the issues discussed in [35823](https://github.com/cilium/cilium/issues/35823) and [17177](https://github.com/cilium/cilium/issues/17177) we are adding a new config field "enable-remote-node-snat" to enable SNAT for remote node in BPF routing mode.

Currently, Cilium ebpf based masquerading does not perform SNAT on packets destined for a remote node, even if the node CIDR is not listed in the non-masquerade list. This behavior differs from the upstream ip-masq-agent. This behavior prevents pods-remote nodes communication in a BPF-masquerade enabled cluster when pod and node network are in different subnets.

With this change if the new confimap field "enable-remote-node-snat" is set to "true"
then packets destined to remote nodes will be SNATed in bpf routing mode.

Changes are reflected in bpf/lib/nat.h :

Before:
```c
if (identity_is_remote_node(remote_ep->sec_identity))
     return NAT_PUNT_TO_STACK;
``` 
After:
```c
if (identity_is_remote_node(remote_ep->sec_identity)) {
    #ifdef ENABLE_REMOTE_NODE_SNAT
    {
	    target->addr = IPV4_MASQUERADE;
	    return NAT_NEEDED;
    }
    #endif
    return NAT_PUNT_TO_STACK;
}
``` 

In order to verify and test the expected behavior, we followed the repro in [35823](https://github.com/cilium/cilium/issues/35823#issuecomment-2607873964) in a cilium bpf routing cluster with the addition of enable-remote-node-snat = "true" in the configmap. ICMP packet from a pod to a remote node initiated.
The TCP-dump from remote node indicates that the source IPs for incoming packet SNATed to the ip of source node.

Fixes: #35823

```release-note
Add a new config field to enable remote node masquerading in BPF routing mode. This can help to establish the pods-remote nodes communication in a BPF-masquerade enabled cluster when pod and node network are in different subnets
```

### CODE REVIEW

**Comment by pchaigno** [comment]
Thanks for the contribution! Could you give a bit of context in the commit description, also describe how you tested this, and fix the CI failure? I'll mark as draft in the meantime to avoid notifying reviewers.

**Comment by behzad-mir** [comment]
> Thanks for the contribution! Could you give a bit of context in the commit description, also describe how you tested this, and fix the CI failure? I'll mark as draft in the meantime to avoid notifying reviewers.

@pchaigno 
Thank you for the comment. I addressed the issue you mentioned here. Let me know if the PR looks good or if anything is missing here.

**Review by pchaigno — DISMISSED** [review]
Could you add the additional context in the commit description and not the PR description?

> In order to verify and test ithe change. We followed the repro in https://github.com/cilium/cilium/issues/35823 and verified that the source address is getting SNATed to the source node IP.

Can you describe exactly how you did that with the current code? It does not work for me.

**Comment by behzad-mir** [comment]
> Could you add the additional context in the commit description and not the PR description?
> 
> > In order to verify and test ithe change. We followed the repro in #35823 and verified that the source address is getting SNATed to the source node IP.
> 
> Can you describe exactly how you did that with the current code? It does not work for me.

Did you follow these steps that Victor provide here:
https://github.com/cilium/cilium/issues/35823#issuecomment-2607873964

You have to make sure that when you run ` k exec -it -n kube-system         cilium-zg2mz -- cilium bpf ipmasq list ` the node subent is not included here.

**Comment by behzad-mir** [comment]
> Could you add the additional context in the commit description and not the PR description?
> 
> > In order to verify and test ithe change. We followed the repro in #35823 and verified that the source address is getting SNATed to the source node IP.
> 
> Can you describe exactly how you did that with the current code? It does not work for me.

@pchaigno I also updated the commit message with more context about the issue. Let me know if you needed to have a repro with current code.

**Comment by pchaigno** [comment]
@behzad-mir Are you sure you tested this version? If you did, could you explain how you enabled the feature?

Looking at the code and trying to image as follows, I don't think the feature can currently be enabled...
```
$ docker run -it quay.io/cilium/cilium-ci:5f46ecc72d31f20f6823ed6153c19b61ff60bacd cilium-agent --help | grep enable-remote-node-snat
$
```
Let's make sure this is properly tested and working before requesting notifications. Switching back to draft...

**Comment by behzad-mir** [comment]
> @behzad-mir Are you sure you tested this version? If you did, could you explain how you enabled the feature?
> 
> Looking at the code and trying the image as follows, I don't think the feature can currently be enabled...
> 
> ```
> $ docker run -it quay.io/cilium/cilium-ci:5f46ecc72d31f20f6823ed6153c19b61ff60bacd cilium-agent --help | grep enable-remote-node-snat
> $
> ```
> 
> Let's make sure this is properly tested and working before requesting notifications. Switching back to draft...

@pchaigno yes I have tested this multiple times and validated the SNAT via TCPDUMP. 
I did not enable feature the same way that you did I just simply added enable-remote-node-snat ="true" in the configMAP.
I'm not sure if we need additional changes in the code so it can show up as a feature in command line.

**Comment by pchaigno** [comment]
Ah, nice to know that's all that's needed for ConfigMap setups. But yeah, we'll need the agent flag fully defined for those of us who run Cilium on baremetal and for the flag to be documented. Check examples from surrounding options and how they're setup in `daemon/cmd/daemon_main.go`.

**Comment by behzad-mir** [comment]
> Ah, nice to know that's all that's needed for ConfigMap setups. But yeah, we'll need the agent flag fully defined for those of us who run Cilium on baremetal and for the flag to be documented. Check examples from surrounding options and how they're setup in `daemon/cmd/daemon_main.go`.

Thanks for clarification. I added the agent flag as well and tested it locally. It also showing up in the cmdref as well. Let me know if anything is missing.

**Comment by pchaigno** [comment]
Thanks for the update! The two failures in CI are genuine and will need to be addressed.

**Comment by behzad-mir** [comment]
> Thanks for the update! The two failures in CI are genuine and will need to be addressed.

@pchaigno addressed all.

File: daemon/cmd/daemon_main.go [hunk 1]
```diff
@@ -661,6 +661,9 @@ func InitGlobalFlags(cmd *cobra.Command, vp *viper.Viper) {
 	flags.Bool(option.EnableIPv4Masquerade, true, "Masquerade IPv4 traffic from endpoints leaving the host")
 	option.BindEnv(vp, option.EnableIPv4Masquerade)
 
+	flags.Bool(option.EnableRemoteNodeSnat, false, "SNAT IPv4 packets from endpoints leaving the host destined to a remote node")
+	option.BindEnv(vp, option.EnableRemoteNodeSnat)
```
Comment (pchaigno) [inline daemon/cmd/daemon_main.go]: Could you also document the new flag under https://docs.cilium.io/en/latest/operations/upgrade/#upgrade-notes?

File: bpf/lib/nat.h [hunk 2]
```diff
@@ -701,9 +701,15 @@ snat_v4_needs_masquerade(struct __ctx_buff *ctx __maybe_unused,
 	remote_ep = lookup_ip4_remote_endpoint(tuple->daddr, 0);
 	if (remote_ep && identity_is_remote_node(remote_ep->sec_identity)) {
 		/* Don't masquerade in native-routing mode: */
-		if (!is_defined(TUNNEL_MODE))
+		if (!is_defined(TUNNEL_MODE)) {
+			#ifdef ENABLE_REMOTE_NODE_SNAT
+			{
+				target->addr = IPV4_MASQUERADE;
+				return NAT_NEEDED;
```
Comment (pchaigno) [inline bpf/lib/nat.h]: Did you consider adding a test for this change? I'm a bit worried we regress without one. [A BPF unit test](https://github.com/cilium/cilium/tree/main/bpf/tests) would probably be good enough.

**Comment by pchaigno** [comment]
Could you also add a release note to the PR description (see the template)? It will be displayed in release notes so it needs to be understandable by users. You can find examples in the release notes of previous releases.

File: bpf/lib/nat.h (hunk 2 above)
Comment (behzad-mir) [reply bpf/lib/nat.h]: @pchaigno I understand the concern, but I could not find any test case for snat_v4_needs_masquerade() func (which includes this remote -node-snat mode). I think it's a good suggestion to have a separate PR to cover all test cases for this function including remote node snat.

Comment (pchaigno) [reply bpf/lib/nat.h]: Fair enough :slightly_smiling_face:

File: daemon/cmd/daemon_main.go (hunk 1 above)
Comment (pchaigno) [reply daemon/cmd/daemon_main.go]: For this, you'll probably want to mention that the behavior from this flag isn't exactly the optimal behavior discussed in https://github.com/cilium/cilium/issues/17177 because packets going to the nodes' InternalIP addresses will also be masqueraded (unless I missed some other check we have).

AFAIU, to implement the optimal behavior, we'd need to tell our datapath which type of IP address each node IP address is. That could probably be achieved by extending the node ID map.

Comment (behzad-mir) [reply daemon/cmd/daemon_main.go]: Understood. Will adding this

File: pkg/datapath/linux/config/config.go [hunk 3]
```diff
@@ -643,6 +643,9 @@ func (h *HeaderfileWriter) WriteNodeConfig(w io.Writer, cfg *datapath.LocalNodeC
 		cDefinesMap["SNAT_COLLISION_RETRIES"] = fmt.Sprintf("%d", nat.SnatCollisionRetries)
 
 		if option.Config.EnableBPFMasquerade {
+			if option.Config.EnableRemoteNodeSnat {
```
Comment (tamilmani1989) [inline pkg/datapath/linux/config/config.go]: should we log a warning if someone enables remote node snat without enabling bpf masquerade?

File: Documentation/cmdref/cilium-agent.md [hunk 4]
```diff
@@ -172,6 +172,7 @@ cilium-agent [flags]
       --enable-policy string                                      Enable policy enforcement (default "default")
       --enable-policy-secrets-sync                                Enables Envoy secret sync for Secrets used in CiliumNetworkPolicy and CiliumClusterwideNetworkPolicy
       --enable-recorder                                           Enable BPF datapath pcap recorder
+      --enable-remote-node-snat                                   SNAT IPv4 packets from endpoints leaving the host destined to a remote node
```
Comment (tamilmani1989) [inline Documentation/cmdref/cilium-agent.md]: can we also mention it requires bpf-masquerade to be enabled.

File: pkg/datapath/linux/config/config.go (hunk 3 above)
Comment (pchaigno) [reply pkg/datapath/linux/config/config.go]: Good point. I'd even just fatal in that case as that's not a config that makes sense. Without a signal, users might be confused as to why the flag is without effect on iptables-based masquerading.

(FYI, such an error should probably go in `daemon_main.go`; we have multiple such error cases.)

Comment (behzad-mir) [reply pkg/datapath/linux/config/config.go]: Will add a warning in that case

File: bpf/lib/nat.h [hunk 5]
```diff
@@ -723,8 +729,15 @@ snat_v4_needs_masquerade(struct __ctx_buff *ctx __maybe_unused,
...
-		if (remote_ep->flag_skip_tunnel)
+		if (remote_ep->flag_skip_tunnel) {
+			#ifdef ENABLE_REMOTE_NODE_SNAT
+			{
+				target->addr = IPV4_MASQUERADE;
+				return NAT_NEEDED;
+			}
+			#endif
 			return NAT_PUNT_TO_STACK;
+		}
```
Comment (julianwiedmann) [inline bpf/lib/nat.h]: How about adding the `ENABLE_REMOTE_NODE_SNAT` block just once, at the top of the whole section?

Are you planning to add the same handling in the IPv6 path?

Comment (behzad-mir) [reply bpf/lib/nat.h]: I did not want to make change for the Tunnel mode case that is already in place. For IPv6 We probably need to introduce a new config filed since at least for Azure we are not NAtting traffic to IPv6 in dualstack mode.

Comment (julianwiedmann) [reply bpf/lib/nat.h]: I see. I think you'll want to describe in a lot more detail what this new feature flag is doing exactly, and in which scenarios it is useful / ineffective. `Documentation/network/concepts/masquerading.rst` is probably a good resting place.

**Review by julianwiedmann — CHANGES_REQUESTED** [review]

File: bpf/lib/nat.h (hunk 5 above)
Comment (behzad-mir) [reply bpf/lib/nat.h]: Will do

Comment (pchaigno) [reply bpf/lib/nat.h]: > For IPv6 We probably need to introduce a new config filed since at least for Azure we are not NAtting traffic to IPv6 in dualstack mode.

I don't understand how that matters to the new flag. We already have `enableIPv6Masquerade`, so if you don't want to NAT traffic to IPv6, then that can be disabled. It doesn't need to be tied in any way to how remote nodes are treated, does it?

Comment (behzad-mir) [reply bpf/lib/nat.h]: @julianwiedmann 
Per @pchaigno comment, I actually made use of the same flag to SNAT traffic to IPv6 as well since we already have V6Masqurade in configmap. I also took the condition out of Tunnel mode. Since if this flag is set it wil be an explicit request for masqurading and will trump the tunneling mode condition.
I made a new commeit to address this

**Comment by behzad-mir** [comment]
@pchaigno @julianwiedmann just bumping this for review.

File: bpf/lib/nat.h (hunk 5 above)
Comment (tamilmani1989) [reply bpf/lib/nat.h]: > It doesn't need to be tied in any way to how remote nodes are treated, does it?

Agree. There shouldn't be any difference with respect to ipv4/ipv6. the new flag should be common for both.

**Review by thorn3r — APPROVED** [review]
agent changes lgtm

File: daemon/cmd/daemon_main.go [hunk 6]
```diff
@@ -663,6 +663,9 @@ func InitGlobalFlags(cmd *cobra.Command, vp *viper.Viper) {
 	flags.Bool(option.EnableIPv4Masquerade, true, "Masquerade IPv4 traffic from endpoints leaving the host")
 	option.BindEnv(vp, option.EnableIPv4Masquerade)
 
+	flags.Bool(option.EnableRemoteNodeSnat, false, "SNAT IPv4 packets from endpoints leaving the host destined to a remote node node in BPF routing mode. This option requires to set enable-bpf-masquerade to true.")
```
Comment (julianwiedmann) [inline daemon/cmd/daemon_main.go]:
```suggestion
	flags.Bool(option.EnableRemoteNodeMasquerade, false, "Masquerade packets from endpoints leaving the host destined to a remote node in BPF routing mode. This option requires to set enable-bpf-masquerade to true.")
```

Could you explain what you mean by "BPF routing mode" ? Which config option does that correspond to?

File: pkg/option/config.go [hunk 7]
```diff
@@ -340,6 +340,9 @@ const (
 	// LogOpt sets log driver options for cilium
 	LogOpt = "log-opt"
 
+	// EnableRemoteNodeSnat SNAT IPv4 packets from endpoints leaving the host destined to a remote node node in BPF routing mode. This option requires to set enable-bpf-masquerade to true.
+	EnableRemoteNodeSnat = "enable-remote-node-snat"
```
Comment (julianwiedmann) [inline pkg/option/config.go]:
```suggestion
	// EnableRemoteNodeMasquerade Masquerade packets from endpoints leaving the host destined to a remote node node in BPF routing mode. This option requires to set enable-bpf-masquerade to true.
	EnableRemoteNodeMasquerade = "enable-remote-node-masquerade"
```

Sorry for being pedantic, but I'd really like us to use "masquerading" in this context, so that it matches the other option names.

File: Documentation/network/concepts/masquerading.rst [hunk 8]
```diff
@@ -178,3 +178,15 @@ by default, use interfaces listed in the ``devices`` field as the egress masquer
...
+****************************
+
+To SNAT traffic to the remote node in BPF routing mode, a feature flag has been introduced. 
+It can be enabled via the option ``enable-remote-node-snat: "true"``. 
+This option requires ``enable-bpf-masquerade: "true"`` and also either 
+``enable-ipv4-masquerade: "true"`` or ``enable-ipv6-masquerade: "true"`` to SNAT traffic for IPv4 and IPv6, respectively.
+
+However, this flag does not provide the optimal behavior because packets directed to the nodes' InternalIP addresses will also be masqueraded. 
+To achieve the optimal behavior, we would need to inform the datapath about the type of IP address each node IP address represents. 
+This could potentially be accomplished by extending the node ID map.
```
Comment (julianwiedmann) [inline Documentation/network/concepts/masquerading.rst]:
```suggestion
Masquerade traffic to Remote Nodes
****************************

To masquerade traffic to remote nodes in BPF routing mode, use the option ``enable-remote-node-masquerade: "true"``. 
This option requires ``enable-bpf-masquerade: "true"`` and also either 
``enable-ipv4-masquerade: "true"`` or ``enable-ipv6-masquerade: "true"`` to SNAT traffic for IPv4 and IPv6, respectively.

However, this flag does not provide the optimal behavior because packets directed to the nodes' InternalIP addresses will also be masqueraded. 
To achieve the optimal behavior, we would need to inform the datapath about the type of IP address each node IP address represents. 
This could potentially be accomplished by extending the node ID map.
```

File: bpf/lib/nat.h [hunk 9]
```diff
@@ -707,10 +707,18 @@ snat_v4_needs_masquerade(struct __ctx_buff *ctx __maybe_unused,
...
+		#ifdef ENABLE_REMOTE_NODE_SNAT
+		{
+			target->addr = IPV4_MASQUERADE;
+			return NAT_NEEDED;
+		}
+		#endif
 		/* Don't masquerade in native-routing mode: */
 		if (!is_defined(TUNNEL_MODE))
 			return NAT_PUNT_TO_STACK;
-
```
Comment (julianwiedmann) [inline bpf/lib/nat.h]: accidental left over?

**Review by julianwiedmann — CHANGES_REQUESTED** [review]
Thank you! A few clarifications / suggestions inline, I'm mostly unsure what you mean by "BPF routing mode".

Have you thought of how this new feature can be tested, so that folks don't drive by and accidentally break it? Maybe a BPF test in `bpf/tests/` that sets up the needed ipcache entry, and confirms that packets are modified as expected when the feature is enabled?

File: daemon/cmd/daemon_main.go (hunk 6 above)
Comment (julianwiedmann) [reply daemon/cmd/daemon_main.go]: Note that instead of hardcoding the `enable-bpf-masquerade` name, you can do a `fmt.Sprintf()` and refer to `option.EnableBPFMasquerade`. See other examples in the file.

File: Documentation/network/concepts/masquerading.rst [hunk 10]
```diff
@@ -178,3 +178,15 @@ by default, use interfaces listed in the ``devices`` field as the egress masquer
 when ``egress-masquerade-interfaces`` is empty. When ``egress-masquerade-interfaces`` is set, 
 it takes precedence over ``devices`` to choose which network interface should perform masquerading.
 You can set ``egress-masquerade-interfaces`` to match multiple interfaces like this: ``eth+ ens+``.
+
+SNAT traffic to Remote Node
```
Comment (ghost) [inline Documentation/network/concepts/masquerading.rst]: Adding a header here, under "Implementation Modes", makes it look like "SNAT traffic to Remote Node" was a third alternative to eBPF and iptables implementations. I see there is a "Configuration" section above - it seems to be a more suitable place for a paragraph about enabling remote node SNAT.

File: bpf/lib/nat.h (hunk 2 above)
Comment (pchaigno) [reply bpf/lib/nat.h]: cc @julianwiedmann

File: Documentation/network/concepts/masquerading.rst (hunk 10 above)
Comment (behzad-mir) [reply Documentation/network/concepts/masquerading.rst]: Addressed in the new commit.

**Comment by behzad-mir** [comment]
> Thank you! A few clarifications / suggestions inline, I'm mostly unsure what you mean by "BPF routing mode".
> 
> Have you thought of how this new feature can be tested, so that folks don't drive by and accidentally break it? Maybe a BPF test in `bpf/tests/` that sets up the needed ipcache entry, and confirms that packets are modified as expected when the feature is enabled?

Thank you for the suggestions. BPF routing mode means bpf.masquerade=true in this context.
I was considering a bpf test for this but I don't think that would be easy to implement and considering a follow up PR to do it actually.

**Comment by behzad-mir** [comment]
> [julianwiedmann](/julianwiedmann)

@julianwiedmann 

> Thank you! A few clarifications / suggestions inline, I'm mostly unsure what you mean by "BPF routing mode".
> 
> Have you thought of how this new feature can be tested, so that folks don't drive by and accidentally break it? Maybe a BPF test in `bpf/tests/` that sets up the needed ipcache entry, and confirms that packets are modified as expected when the feature is enabled?

@julianwiedmann I think we need to have  follow up PR to cover all cases in nat_v4_needs_masquerade() including my change. I was not able to find a UT for the current function. If it's OK with you. We can discuss a follow up PR for it.

**Comment by julianwiedmann** [comment]
> Thank you for the suggestions. BPF routing mode means bpf.masquerade=true in this context.

I see. Let's then please consistently use `BPF masquerading`. The term `BPF routing` is already established, and it means something entirely different (whether forwarding within the node is implemented using BPF redirects or via kernel routing).

> I was considering a bpf test for this but I don't think that would be easy to implement and considering a follow up PR to do it actually.

`bpf/tests/` has plenty of examples that enable `ENABLE_MASQUERADE_IPV4`. I think you could easily take inspiration from those, insert an appropriate ipcache entry, craft a corresponding packet, and demonstrate that the packet gets masqueraded.

File: Documentation/network/concepts/masquerading.rst [hunk 11]
```diff
@@ -181,3 +192,14 @@ by default, use interfaces listed in the ``devices`` field as the egress masquer
 when ``egress-masquerade-interfaces`` is empty. When ``egress-masquerade-interfaces`` is set, 
 it takes precedence over ``devices`` to choose which network interface should perform masquerading.
 You can set ``egress-masquerade-interfaces`` to match multiple interfaces like this: ``eth+ ens+``.
+
+Masquerade traffic to Remote Nodes
```
Comment (ghost) [inline Documentation/network/concepts/masquerading.rst]: This section now duplicates the one from above - it looks like a leftover, could you remove it?

**Review by ghost — COMMENTED** [review]
@behzad-mir Could you squash the commits into one? There is no need to add more commits in this case I think, and I see there is a leftover in the docs (see my comment). Other than that docs look good :)

File: Documentation/network/concepts/masquerading.rst (hunk 11 above)
Comment (behzad-mir) [reply Documentation/network/concepts/masquerading.rst]: resolved in the new commit

**Comment by behzad-mir** [comment]
> > Thank you for the suggestions. BPF routing mode means bpf.masquerade=true in this context.
> 
> I see. Let's then please consistently use `BPF masquerading`. The term `BPF routing` is already established, and it means something entirely different (whether forwarding within the node is implemented using BPF redirects or via kernel routing).
> 
> > I was considering a bpf test for this but I don't think that would be easy to implement and considering a follow up PR to do it actually.
> 
> `bpf/tests/` has plenty of examples that enable `ENABLE_MASQUERADE_IPV4`. I think you could easily take inspiration from those, insert an appropriate ipcache entry, craft a corresponding packet, and demonstrate that the packet gets masqueraded.

@julianwiedmann A unit test has been added and also the term masqurading has been applied consistently

File: daemon/cmd/daemon_main.go [hunk 12]
```diff
@@ -1254,6 +1257,10 @@ func initEnv(vp *viper.Viper) {
 		log.Warn("IPSec encrypted overlay is enabled but IPSec is not. Ignoring option.")
 	}
 
+	if option.Config.EnableRemoteNodeMasquerade && !option.Config.EnableBPFMasquerade {
+		log.Fatal("EnableRemoteNodeMasquerade is enabled but EnableBPFMasquerade is not. Ignoring option.")
+	}
+
```
Comment (julianwiedmann) [inline daemon/cmd/daemon_main.go]:
```suggestion
	if option.Config.EnableRemoteNodeMasquerade && !option.Config.EnableBPFMasquerade {
		log.Warn("EnableRemoteNodeMasquerade is enabled but EnableBPFMasquerade is not. Ignoring option.")
	}

```


Right now we `Fatal()`. If we want to ignore the misconfig & continue, then you'd want a `Warn()` instead.

File: bpf/lib/nat.h [hunk 13]
```diff
@@ -738,10 +738,18 @@ snat_v4_needs_masquerade(struct __ctx_buff *ctx __maybe_unused,
 	 */
 	remote_ep = lookup_ip4_remote_endpoint(tuple->daddr, 0);
 	if (remote_ep && identity_is_remote_node(remote_ep->sec_identity)) {
+		/* SNAT the packet to remote node if enable-remote-node-masquerade flag is set to true.
+		 * This is a feature flag that can be enabled in BPF masquerading mode.
+		 */
+		#ifdef ENABLE_REMOTE_NODE_MASQUERADE
```
Comment (julianwiedmann) [inline bpf/lib/nat.h]: could you please also wire up some build testing (in `bpf/Makefile`) and complexity testing (in `bpf/complexity-tests/.../bpf_host/...`) for this symbol?

**Review by julianwiedmann — APPROVED** [review]
thank you, lgtm! I'm skeptical how many special-cases we can realistically maintain in the BPF masq code, but let's at least give this one a try.

A few non-blocking comments inline, please address them if this PR needs another spin. Alternatively in a follow-up PR.

**Review by thorn3r — APPROVED** [review]
agent changes LGTM :+1:

File: pkg/option/config.go [hunk 14]
```diff
@@ -331,6 +331,9 @@ const (
 	// LogOpt sets log driver options for cilium
 	LogOpt = "log-opt"
 
+	// EnableRemoteNodeMasquerade Masquerade packets from endpoints leaving the host destined to a remote node node in BPF masquerading mode. This option requires to set enable-bpf-masquerade to true.
```
Comment (asauber) [inline pkg/option/config.go]: A few typos here (i.e. "node node"). Suggested description:

"Masquerade packets from endpoints leaving the host destined for a remote node in BPF masquerading mode. This option requires that enable-bpf-masquerade is set to true."

**Review by asauber — APPROVED** [review]

**Comment by nebril** [comment]
@cilium/loader can you take a look at this change and CI failures?

**Review by joestringer — CHANGES_REQUESTED** [review]
Thanks for the PR. Please also address the comments posted by other reviewers in the PR above. (The PR will need a rebase against the tip of `main` while you're at it).

File: bpf/tests/bpf_nat_tests.c [hunk 15]
```diff
@@ -1303,4 +1308,68 @@ int test_nat4_port_allocation_udp_check(struct __ctx_buff *ctx)
...
+
+	ret = snat_v4_needs_masquerade(ctx, &tuple, &ip4, fraginfo, l4_off, &target);
+
+	/* When flag is enabled, packet to remote node should be masqueraded */
+	assert(ret == NAT_NEEDED);
+	assert(target.addr == IPV4_MASQUERADE);
+
+	/* Clean up */
+	remote_endpoint_mock = NULL;
+
```
Comment (tamilmani1989) [inline bpf/tests/bpf_nat_tests.c]: can we add one case for tunnel mode enabled and whats the expected value to be returned by `snat_v4_needs_masquerade`

File: daemon/cmd/daemon_main.go (hunk 12 above)
Comment (behzad-mir) [reply daemon/cmd/daemon_main.go]: We have discussed this in another thread and it was originally warn() @tamilmani1989 asked to make it a fatal()

File: bpf/tests/bpf_nat_tests.c (hunk 15 above)
Comment (behzad-mir) [reply bpf/tests/bpf_nat_tests.c]: Addressed in the new commit.

File: pkg/option/config.go (hunk 14 above)
Comment (behzad-mir) [reply pkg/option/config.go]: Addressed in the new commit

File: bpf/lib/nat.h (hunk 13 above)
Comment (behzad-mir) [reply bpf/lib/nat.h]: Added both requested tests in the new commit

File: Documentation/network/concepts/masquerading.rst [hunk 16]
```diff
@@ -44,6 +44,17 @@ Setting the routable CIDR
...
+**********************************
+
+To masquerade traffic to remote nodes in BPF masquerading mode, use the option ``enable-remote-node-masquerade: "true"``. 
+This option requires ``enable-bpf-masquerade: "true"`` and also either 
+``enable-ipv4-masquerade: "true"`` or ``enable-ipv6-masquerade: "true"`` to SNAT traffic for IPv4 and IPv6, respectively.
+
+However, this flag does not provide the optimal behavior because packets directed to the nodes' InternalIP addresses will also be masqueraded. 
+To achieve the optimal behavior, we would need to inform the datapath about the type of IP address each node IP address represents. 
+This could potentially be accomplished by extending the node ID map.
```
Comment (joestringer) [inline Documentation/network/concepts/masquerading.rst]: This is user documentation describing the concepts, but the text appears to be proposing future changes that may or may not be put into Cilium. I would suggest to make the text clear and specific about the current behavior and leave forward-looking statements for issue discussions.
```suggestion
This flag currently masquerades traffic to node ``InternalIP`` addresses. This may change in future. See :gh-issue:`####` for further discussion on this topic.
```

Note the suggestion above does not specify a specific github issue; you might consider filing a new one for the proposed solution, or alternatively you could reuse one of the existing ones. Depends whether we intend to close those existing issues assuming this PR is accepted.

File: Documentation/network/concepts/masquerading.rst [hunk 17]
```diff
@@ -44,6 +44,17 @@ Setting the routable CIDR
 Setting the masquerading interface
   See :ref:`masq_modes` for configuring the masquerading interfaces.
 
+Masquerade traffic to Remote Nodes
+**********************************
+
+To masquerade traffic to remote nodes in BPF masquerading mode, use the option ``enable-remote-node-masquerade: "true"``. 
+This option requires ``enable-bpf-masquerade: "true"`` and also either 
+``enable-ipv4-masquerade: "true"`` or ``enable-ipv6-masquerade: "true"`` to SNAT traffic for IPv4 and IPv6, respectively.
```
Comment (joestringer) [inline Documentation/network/concepts/masquerading.rst:52]: Suggestion to clarify which traffic is affected by the option:

```suggestion
``enable-ipv4-masquerade: "true"`` or ``enable-ipv6-masquerade: "true"`` to SNAT traffic for IPv4 and IPv6, respectively.
This option only affects traffic from an Endpoint directed towards the address of a remote node, and not traffic between Endpoints on different nodes.
```

File: Documentation/cmdref/cilium-agent.md [hunk 18]
```diff
@@ -168,6 +168,8 @@ cilium-agent [flags]
       --enable-pmtu-discovery                                     Enable path MTU discovery to send ICMP fragmentation-needed replies to the client
       --enable-policy string                                      Enable policy enforcement (default "default")
       --enable-policy-secrets-sync                                Enables Envoy secret sync for Secrets used in CiliumNetworkPolicy and CiliumClusterwideNetworkPolicy
+      --enable-recorder                                           Enable BPF datapath pcap recorder
```
Comment (joestringer) [inline Documentation/cmdref/cilium-agent.md]: Unrelated?
```suggestion
```

File: bpf/tests/bpf_nat_tests.c [hunk 19]
```diff
@@ -1302,4 +1307,107 @@ int test_nat4_port_allocation_udp_check(struct __ctx_buff *ctx)
 	test_finish();
 }
 
-BPF_LICENSE("Dual BSD/GPL");
```
Comment (joestringer) [inline bpf/tests/bpf_nat_tests.c]: Why is the license declaration being removed?

File: daemon/cmd/daemon_main.go [hunk 20]
```diff
@@ -1261,6 +1264,10 @@ func initEnv(logger *slog.Logger, vp *viper.Viper) {
 		logger.Warn("IPSec encrypted overlay is enabled but IPSec is not. Ignoring option.")
 	}
 
+	if option.Config.EnableRemoteNodeMasquerade && !option.Config.EnableBPFMasquerade {
+		logging.Fatal("EnableRemoteNodeMasquerade is enabled but EnableBPFMasquerade is not. Ignoring option.")
```
Comment (joestringer) [inline daemon/cmd/daemon_main.go]: If this is fatal, then the options are not being ignored. This is the common pattern but should be expressed more clearly to the user. Also needs to be rebased for `slog` migration in the upstream tree:
```suggestion
		logging.Fatal(logger, "Option " + option.EnableRemoteNodeMasquerade + " requires BPF masquerade to be enabled (" + option.EnableBPFMasquerade + ")")
```

File: Documentation/network/concepts/masquerading.rst [hunk 21]
```diff
@@ -44,6 +44,17 @@ Setting the routable CIDR
...
+
+However, this flag does not provide the optimal behavior because packets directed to the nodes' InternalIP addresses will also be masqueraded. 
+To achieve the optimal behavior, we would need to inform the datapath about the type of IP address each node IP address represents. 
+This could potentially be accomplished by extending the node ID map.
+
```
Comment (joestringer) [inline Documentation/network/concepts/masquerading.rst:61]: I could imagine this feature leading to confused deputy attacks in an environment, so it's probably best recommended to be disabled by default:

```suggestion

This option can limit Cilium's ability to enforce ingress host firewall policies for traffic from Pods towards Nodes.
If you use this option, consider establishing default deny policies to prevent Endpoints from communicating with Nodes,
and minimize use of policy statements that allow traffic from remote nodes (such as the ``remote-node`` Entity).
If in doubt, disable this option.

```

File: bpf/tests/bpf_nat_tests.c [hunk 22]
```diff
@@ -1302,4 +1307,107 @@ int test_nat4_port_allocation_udp_check(struct __ctx_buff *ctx)
...
+
+    ret = snat_v4_needs_masquerade(ctx, &tuple, &ip4, fraginfo, l4_off, &target);
+
+    /* When flag is enabled, packet to remote node should be masqueraded */
+    assert(ret == NAT_NEEDED);
+    assert(target.addr == IPV4_MASQUERADE);
+
+    /* Test 3: With tunnel mode enabled, without ENABLE_REMOTE_NODE_MASQUERADE */
+    #undef ENABLE_REMOTE_NODE_MASQUERADE
+    #define TUNNEL_MODE 1
```
Comment (joestringer) [inline bpf/tests/bpf_nat_tests.c]: Is there a better way to test this than modifying preprocessor macros mid-test? 

I wonder whether tests specific to this mode should just be declared in a dedicated separate test file in order to avoid tainting the test environment for the remainder of the file.

File: daemon/cmd/daemon_main.go
Comment (joestringer) [inline daemon/cmd/daemon_main.go:1]: Would you mind adding a bit more detail about the use case into the PR description? Currently it just refers to the behavior being different from upstream ip-masq-agent, but no details about a specific situation where this causes problems that might influence a user to use the new option.

File: Documentation/cmdref/cilium-agent.md (hunk 18 above)
Comment (behzad-mir) [reply Documentation/cmdref/cilium-agent.md]: I think this showed uP after a merge conflict.

File: daemon/cmd/daemon_main.go (hunk 20 above)
Comment (behzad-mir) [reply daemon/cmd/daemon_main.go]: I rebased it already and made the recommended changes

File: bpf/tests/bpf_nat_tests.c (hunk 19 above)
Comment (behzad-mir) [reply bpf/tests/bpf_nat_tests.c]: Removed by mistake.

File: Documentation/network/concepts/masquerading.rst (hunk 16 above)
Comment (behzad-mir) [reply Documentation/network/concepts/masquerading.rst]: Done in the new commit

File: bpf/tests/bpf_nat_tests.c (hunk 22 above)
Comment (behzad-mir) [reply bpf/tests/bpf_nat_tests.c]: Moved the entire test to a new file.

File: Documentation/cmdref/cilium-agent.md (hunk 18 above)
Comment (joestringer) [reply Documentation/cmdref/cilium-agent.md]: Your PR should not need to add anything from a merge conflict, could you remove it?

File: daemon/cmd/daemon_main.go
Comment (behzad-mir) [reply daemon/cmd/daemon_main.go:1]: @joestringer Some more details about the use case has been added to both PR description and release note.
@pchaigno Would appreciate it if you review the PR again.

File: Documentation/network/concepts/masquerading.rst [hunk 23]
```diff
@@ -44,6 +44,21 @@ Setting the routable CIDR
...
 
+Masquerade traffic to Remote Nodes
+**********************************
+
+To masquerade traffic to remote nodes in BPF masquerading mode, use the option ``enable-remote-node-masquerade: "true"``. 
+This option requires ``enable-bpf-masquerade: "true"`` and also either 
+``enable-ipv4-masquerade: "true"`` or ``enable-ipv6-masquerade: "true"`` to SNAT traffic for IPv4 and IPv6, respectively.
+This option only affects traffic from an Endpoint directed towards the address of a remote node, and not traffic between Endpoints on different nodes.
+
+This flag currently masquerades traffic to node ``InternalIP`` addresses. This may change in future. See : (:gh-issue:`35823`) and (:gh-issue:`17177`) for further discussion on this topic.
```
Comment (joestringer) [inline Documentation/network/concepts/masquerading.rst]: Minor nit for formatting:
```suggestion
This flag currently masquerades traffic to node ``InternalIP`` addresses. This may change in future. See :gh-issue:`35823` and :gh-issue:`17177` for further discussion on this topic.
```

File: Documentation/cmdref/cilium-agent.md (hunk 18 above)
Comment (joestringer) [reply Documentation/cmdref/cilium-agent.md]: This line should be removed.

**Review by joestringer — CHANGES_REQUESTED** [review]
Couple of minor additional nits. I'll defer to @cilium/sig-datapath on the datapath implementation / tests review.

File: Documentation/network/concepts/masquerading.rst (hunk 23 above)
Comment (behzad-mir) [reply Documentation/network/concepts/masquerading.rst]: Been addressed in the new commit

File: Documentation/cmdref/cilium-agent.md (hunk 18 above)
Comment (behzad-mir) [reply Documentation/cmdref/cilium-agent.md]: done

**Comment by joestringer** [comment]
Several of the checks are failing, most likely due to the Makefile changes in this PR. However, most prominently the datapath complexity checks are failing. What this says is that it's not possible to enable this new feature and use it with any of the kernel versions we are testing in CI. Are you able to reproduce this locally in order to iterate on the solution and explore how to resolve these issues? I don't think we can merge this feature if it is going to break as soon as a user deploys it.

**Comment by behzad-mir** [comment]
> Several of the checks are failing, most likely due to the Makefile changes in this PR. However, most prominently the datapath complexity checks are failing. What this says is that it's not possible to enable this new feature and use it with any of the kernel versions we are testing in CI. Are you able to reproduce this locally in order to iterate on the solution and explore how to resolve these issues? I don't think we can merge this feature if it is going to break as soon as a user deploys it.

The issue was related to some extra space in my MakeFIle. It has been corrected and another Commit has been made
"Makefile:100: *** target pattern contains no '%'.  Stop."

**Review by tamilmani1989 — APPROVED** [review]

**Comment by behzad-mir** [comment]
@pchaigno @joestringer Can you review the PR again?

**Comment by behzad-mir** [comment]
@joestringer Can we add a release 1.18 for this PR?
The changes are done long back, and it has been tested and near completion.

**Comment by pchaigno** [comment]
> @pchaigno @joestringer Can you review the PR again?

Could you review unresolved discussions above and mark as resolved if you think you addressed them? I believe I still have a comment from my previous review that wasn't addressed.

File: bpf/lib/nat.h (hunk 5 above)
Comment (behzad-mir) [reply bpf/lib/nat.h]: The issue has been addressed.

**Comment by behzad-mir** [comment]
> > @pchaigno @joestringer Can you review the PR again?
> 
> Could you review unresolved discussions above and mark as resolved if you think you addressed them? I believe I still have a comment from my previous review that wasn't addressed.

Thanks @pchaigno I went back through the comments, and I believe all of them have been addressed. Can you please pint me to the issue.

File: daemon/cmd/daemon_main.go (hunk 1 above)
Comment (pchaigno) [reply daemon/cmd/daemon_main.go]: This wasn't addressed :)

File: pkg/datapath/linux/config/config.go [hunk 24]
```diff
@@ -563,6 +563,9 @@ func (h *HeaderfileWriter) WriteNodeConfig(w io.Writer, cfg *datapath.LocalNodeC
 		cDefinesMap["SNAT_COLLISION_RETRIES"] = fmt.Sprintf("%d", nat.SnatCollisionRetries)
 
 		if option.Config.EnableBPFMasquerade {
+			if option.Config.EnableRemoteNodeMasquerade {
+				cDefinesMap["ENABLE_REMOTE_NODE_MASQUERADE"] = "1"
```
Comment (ti-mo) [inline pkg/datapath/linux/config/config.go]: Since you're gating a small amount of behaviour, please use the new CONFIG()-style configuration mechanism: https://docs.cilium.io/en/latest/contributing/development/datapath_config/#dpconfig.

**Review by ti-mo — DISMISSED** [review]

**Comment by joestringer** [comment]
> Thanks @pchaigno I went back through the comments, and I believe all of them have been addressed. Can you please pint me to the issue.

I understand GitHub has poor UX here, but you can click through the hidden items to find the unresolved threads:

image

I'll mark this PR as draft while you address the feedback. Once it is ready for fresh review, please use the "Ready for review" button at the bottom of the page.

File: pkg/datapath/linux/config/config.go (hunk 24 above)
Comment (behzad-mir) [reply pkg/datapath/linux/config/config.go]: @ti-mo Thank you for your review and comment. Since we have tested this option with current config style and the PR needs to be merged ASAP. I s it possible to do this as a follow up PR?

File: daemon/cmd/daemon_main.go (hunk 1 above)
Comment (behzad-mir) [reply daemon/cmd/daemon_main.go]: Thanks @pchaigno, I missed this one. I added a section as you have requested. Let me know if it covers the issue.

File: Documentation/operations/upgrade.rst [hunk 25]
```diff
@@ -330,6 +330,10 @@ communicating via the proxy must reconnect to re-establish connections.
...
   your network policies in advance for the Cilium 1.19 upgrade.
 * Creating or deleting policies via the local REST api is deprecated. This will be removed entirely in v1.19.
+* ``enable-remote-node-masquerade`` config option is introduced. To masquerade traffic to remote nodes in BPF masquerading mode, use the option ``enable-remote-node-masquerade: "true"``. This option requires ``enable-bpf-masquerade: "true"`` and also either
+  ``enable-ipv4-masquerade: "true"`` or ``enable-ipv6-masquerade: "true"`` to SNAT traffic for IPv4 and IPv6, respectively. This flag currently masquerades traffic to node ``InternalIP`` addresses. This may change in future. See :gh-issue:`35823` and :gh-issue:`17177` for further discussion on this topic.
+  This option can limit Cilium's ability to enforce ingress host firewall policies for traffic from Pods towards Nodes.
+  If you use this option, consider establishing default deny policies to prevent Endpoints from communicating with Nodes, and minimize use of policy statements that allow traffic from remote nodes (such as the ``remote-node`` Entity). If in doubt, disable this option.
```
Comment (pchaigno) [inline Documentation/operations/upgrade.rst]: Let's keep this short, like for surrounding entries. The goal here is to let users know about new flags, not describe them in details.

Comment (behzad-mir) [reply Documentation/operations/upgrade.rst]: @pchaigno I removed the second part of it. Let me know if you prefer to short it even more.

File: pkg/datapath/linux/config/config.go (hunk 24 above)
Comment (joestringer) [reply pkg/datapath/linux/config/config.go]: For what it's worth, I understand the desire to move this PR quicker given how long it's been out for and if you already tested the logic, but that's not a motivation to reject the feedback from reviewers. As a general rule in Cilium we prefer not to defer technical debt improvements to follow up PRs, as that can easily fall through the gaps and ultimately burden the maintainers with additional work to maintain the code. For full disclosure as well on the timelines, this PR has slipped the v1.18.x release window so it will now be targeted for v1.19.

File: Documentation/operations/upgrade.rst [hunk 26]
```diff
@@ -330,6 +330,8 @@ communicating via the proxy must reconnect to re-establish connections.
   recommended to check :ref:`change_policy_default_local_cluster` for details and migration recommendations to update
   your network policies in advance for the Cilium 1.19 upgrade.
 * Creating or deleting policies via the local REST api is deprecated. This will be removed entirely in v1.19.
+* ``enable-remote-node-masquerade`` config option is introduced. To masquerade traffic to remote nodes in BPF masquerading mode, use the option ``enable-remote-node-masquerade: "true"``. This option requires ``enable-bpf-masquerade: "true"`` and also either
+  ``enable-ipv4-masquerade: "true"`` or ``enable-ipv6-masquerade: "true"`` to SNAT traffic for IPv4 and IPv6, respectively. This flag currently masquerades traffic to node ``InternalIP`` addresses. This may change in future. See :gh-issue:`35823` and :gh-issue:`17177` for further discussion on this topic.
```
Comment (pchaigno) [inline Documentation/operations/upgrade.rst]: Nit: Please follow the line width of other entries.

File: Documentation/operations/upgrade.rst (hunk 25 above)
Comment (pchaigno) [reply Documentation/operations/upgrade.rst]: I think it's okay as is.

File: pkg/datapath/linux/config/config.go (hunk 24 above)
Comment (behzad-mir) [reply pkg/datapath/linux/config/config.go]: @ti-mo @joestringer I have the changes ready to transition to the new CONFIG() style but noticed if I do the transition then the complexity tests and bpf/Makefile chnages are no longer needed since I am removing the ENBALE_REMOTE_NODE_MASQURADE from the code.
Let me know if there is a way to do the complexity test or we can skip it.

Comment (ti-mo) [reply pkg/datapath/linux/config/config.go]: There is since today, see https://github.com/cilium/cilium/pull/40367. :)

**Comment by joestringer** [comment]
Heads up just to make next steps clear: The BPF checks are failing, most likely due to changes in this PR: https://github.com/cilium/cilium/actions/runs/16154872529/job/45599680186?pr=37568#step:4:182 . The PR also needs to be rebased. Also from [this thread](https://github.com/cilium/cilium/pull/37568#discussion_r2211671790) there should be a new way to do the complexity testing.

File: pkg/datapath/linux/config/config.go (hunk 24 above)
Comment (behzad-mir) [reply pkg/datapath/linux/config/config.go]: @ti-mo 
I added a new commit. Let me know if it address the issue. Also based on the above PR, do I need to make any specific changes to load my config option for the complexity test or is it going to be picked up by the verifier automatically?

File: Documentation/operations/upgrade.rst (hunk 26 above)
Comment (behzad-mir) [reply Documentation/operations/upgrade.rst]: Resolved in the new commit. Added this section to 1.19 updates and made the lines shorter.

Comment (pchaigno) [reply Documentation/operations/upgrade.rst]: There must have been a mistake because it doesn't look resolve AFAICT.

File: Documentation/operations/upgrade.rst [hunk 27]
```diff
@@ -293,6 +293,12 @@ communicating via the proxy must reconnect to re-establish connections.
 1.19 Upgrade Notes
 ------------------
 
+* ``enable-remote-node-masquerade`` config option is introduced. To masquerade traffic to remote nodes in BPF masquerading mode, 
+  use the option ``enable-remote-node-masquerade: "true"``. This option requires ``enable-bpf-masquerade: "true"`` and also either
+  ``enable-ipv4-masquerade: "true"`` or ``enable-ipv6-masquerade: "true"`` to SNAT traffic for IPv4 and IPv6, respectively. 
+  This flag currently masquerades traffic to node ``InternalIP`` addresses.
+  This may change in future. See :gh-issue:`35823` and :gh-issue:`17177` for further discussion on this topic.
```
Comment (behzad-mir) [inline Documentation/operations/upgrade.rst]: @pchaigno This is the updated version in new commit. Let me know if the line width are correct.

File: Documentation/operations/upgrade.rst (hunk 26 above)
Comment (behzad-mir) [reply Documentation/operations/upgrade.rst]: tagged you below in the updated version.

File: Documentation/operations/upgrade.rst (hunk 27 above)
Comment (joestringer) [reply Documentation/operations/upgrade.rst]: FWIW it looks like we haven't been super consistent in enforcing line lengths in this file, but for most Cilium contributors we have our editors set up for 80 character lines. Unfortunately we can't really set up a simple linter to ensure this because sometimes links cause lines to be longer, so this tends to be more of a soft limit in the docs.

We often also have linters that highlight unnecessary whitespace at EOL, and it looks like these lines also have some there too.

This incremental patch would fix up both aspects:

```
diff --git a/Documentation/operations/upgrade.rst b/Documentation/operations/upgrade.rst
index 62915fc8659c..372add2b6f8c 100644
--- a/Documentation/operations/upgrade.rst
+++ b/Documentation/operations/upgrade.rst
@@ -293,11 +293,14 @@ communicating via the proxy must reconnect to re-establish connections.
 1.19 Upgrade Notes
 ------------------
 
-* ``enable-remote-node-masquerade`` config option is introduced. To masquerade traffic to remote nodes in BPF masquerading mode, 
-  use the option ``enable-remote-node-masquerade: "true"``. This option requires ``enable-bpf-masquerade: "true"`` and also either
-  ``enable-ipv4-masquerade: "true"`` or ``enable-ipv6-masquerade: "true"`` to SNAT traffic for IPv4 and IPv6, respectively. 
-  This flag currently masquerades traffic to node ``InternalIP`` addresses.
-  This may change in future. See :gh-issue:`35823` and :gh-issue:`17177` for further discussion on this topic.
+* ``enable-remote-node-masquerade`` config option is introduced. To masquerade
+  traffic to remote nodes in BPF masquerading mode, use the option
+  ``enable-remote-node-masquerade: "true"``. This option requires
+  ``enable-bpf-masquerade: "true"`` and also either ``enable-ipv4-masquerade:
+  "true"`` or ``enable-ipv6-masquerade: "true"`` to SNAT traffic for IPv4 and
+  IPv6, respectively. This flag currently masquerades traffic to node
+  ``InternalIP`` addresses. This may change in future. See :gh-issue:`35823`
+  and :gh-issue:`17177` for further discussion on this topic.
 
 Removed Options
 ~~~~~~~~~~~~~~~
```

**Comment by joestringer** [comment]
As for the test failures, we had a regression in `main` this week which I think was resolved maybe on weds or thurs. At least one of the failures is related to that, so one more rebase might help to resolve at least some of the failures. I'm not sure if that will resolve all of the failures or not, but that would be a reasonable step forward.

File: Documentation/operations/upgrade.rst (hunk 27 above)
Comment (pchaigno) [reply Documentation/operations/upgrade.rst]: You'll also need to squash the two commits at the same time. (Or split changes in multiple commits, with ex. functional changes, docs, tests.)

Comment (behzad-mir) [reply Documentation/operations/upgrade.rst]: Yes I just did that @pchaigno .
I left them like that intentionally for review purpose since the second commit was changing the whole config process. I squashed and rebased to the master.

**Comment by behzad-mir** [comment]
> As for the test failures, we had a regression in `main` this week which I think was resolved maybe on weds or thurs. At least one of the failures is related to that, so one more rebase might help to resolve at least some of the failures. I'm not sure if that will resolve all of the failures or not, but that would be a reasonable step forward.

@joestringer @pchaigno let me know if any other change is outstanding here. Thanks

**Comment by joestringer** [comment]
@behzad-mir when the tests complete, please triage any failures according to this guidance: https://docs.cilium.io/en/stable/contributing/testing/ci/#id1 .

**Comment by behzad-mir** [comment]
@joestringer I addressed one of the issues that was related to my PR (one of the description messages for config was too long)
For the rest of the CI failures, I followed the triage link you provided and created issues.

**Comment by behzad-mir** [comment]
> @joestringer I addressed one of the issues that was related to my PR (one of the description messages for config was too long) For the rest of the CI failures, I followed the triage link you provided and created issues.

@pchaigno @ti-mo Can I please also get another review from you guys to see if the requested changes are addressed or not?

**Comment by joestringer** [comment]
> For the rest of the CI failures, I followed the triage link you provided and created issues.

Would you mind also summarizing/linking those in a comment here? Right now there are no breadcrumbs on this issue that demonstrate the triage you have performed. If you created issues, please ensure those issues reference this PR to state clearly that you have observed the issue here. 

The background to this is that if everyone observes these issues, then it will be clear the issues affect the main branch. If this is the only PR observing the issues, that's usually an indication that this PR is introducing the failures. At a glance it seems like maybe some of the tests are just odd failures in unrelated steps, so maybe we can improve on the stability of those workflows independently.

**Comment by behzad-mir** [comment]
> > For the rest of the CI failures, I followed the triage link you provided and created issues.
> 
> Would you mind also summarizing/linking those in a comment here? Right now there are no breadcrumbs on this issue that demonstrate the triage you have performed. If you created issues, please ensure those issues reference this PR to state clearly that you have observed the issue here.
> 
> The background to this is that if everyone observes these issues, then it will be clear the issues affect the main branch. If this is the only PR observing the issues, that's usually an indication that this PR is introducing the failures. At a glance it seems like maybe some of the tests are just odd failures in unrelated steps, so maybe we can improve on the stability of those workflows independently.

Thank you for clarifying that and adding extra comments to the issues. They are listed above when I linked them. The issues are not relevant to the PR since similar ones have been identified in other CI runs too.

File: bpf/Makefile [hunk 28]
```diff
@@ -93,6 +93,12 @@ HOST_OPTIONS = $(LXC_OPTIONS) \
...
 	-DENABLE_IPV4:-DENABLE_IPV6:-DENCAP_IFINDEX:-DPOLICY_VERDICT_NOTIFY:-DENABLE_NODEPORT:-DENABLE_NODEPORT_ACCELERATION:-DENABLE_DSR:-DDSR_ENCAP_MODE:-DDSR_ENCAP_GENEVE:-DENABLE_PREFILTER:-DENABLE_SESSION_AFFINITY:-DENABLE_HOST_FIREWALL:-DENABLE_ICMP_RULE:-DENABLE_SRV6:-DENABLE_SRV6_SRH_ENCAP:-DENCRYPTED_OVERLAY:-DENABLE_SCTP:-DENABLE_VTEP:-DDSR_ENCAP_IPIP=2 \
 	-DENABLE_IPV4:-DENABLE_IPV6:-DENCAP_IFINDEX:-DPOLICY_VERDICT_NOTIFY:-DENABLE_NODEPORT:-DENABLE_NODEPORT_ACCELERATION:-DENABLE_DSR:-DENABLE_DSR_HYBRID:-DENABLE_PREFILTER:-DENABLE_SESSION_AFFINITY:-DENABLE_HOST_FIREWALL:-DENABLE_ICMP_RULE:-DENABLE_SRV6:-DENABLE_SRV6_SRH_ENCAP:-DENCRYPTED_OVERLAY:-DENABLE_SCTP:-DENABLE_VTEP:-DENABLE_IPSEC: \
+    -DENABLE_IPV4:-DENABLE_IPV6:-DENCAP_IFINDEX:-DTUNNEL_MODE:-DENABLE_BPF_MASQUERADE:-DENABLE_MASQUERADE_IPV4:-DENABLE_MASQUERADE_IPV6: \
```
Comment (rgo3) [inline bpf/Makefile]: Now that you've made `enable_remote_node_masquerade` and load time config, are these makefile changes still necessary?

File: pkg/datapath/config/host_config.go [hunk 29]
```diff
@@ -14,6 +14,8 @@ type BPFHost struct {
 	DeviceMTU uint16 `config:"device_mtu"`
 	// Pass traffic with extended IP protocols.
 	EnableExtendedIPProtocols bool `config:"enable_extended_ip_protocols"`
+	// Masquerade packets from endpoints destined to a remote node.
+	EnableRemoteNodeMasquerade bool `config:"enable_remote_node_masquerade"`
```
Comment (rgo3) [inline pkg/datapath/config/host_config.go:18]: As Timo suggested in his earlier comments, you can add a permutation of this config to the complexity tests of the bpf_host progs, see https://github.com/cilium/cilium/blob/5a60ca4e9c4152cb3ce85276cb6084830200d886/pkg/datapath/loader/verifier_load_test.go#L24.

The following should achieve what you want:
```
func hostLoadPermutations() iter.Seq[*config.BPFHost] {
	return func(yield func(*config.BPFHost) bool) {
		for permutation := range permute(2) {
			cfg := config.NewBPFHost(*config.NewNode())
			cfg.SecctxFromIPCache = permutation[0]
            cfg.EnableRemoteNodeMasquerade = permutation[1]
			if !yield(cfg) {
				return
			}
		}
	}
}
```

**Review by rgo3 — CHANGES_REQUESTED** [review]
Picking up the review from Timo here, as I was assigned initially for loader anyway. Overall looks good, we should just make sure the config variable is covered in verifier tests.

File: pkg/datapath/config/host_config.go (hunk 29 above)
Comment (behzad-mir) [reply pkg/datapath/config/host_config.go:18]: Thanks for pointing this out I added cfg.EnableRemoteNodeMasquerade = permutation[1] to the exiting hostLoadPermutations() function in the file.

File: bpf/Makefile (hunk 28 above)
Comment (behzad-mir) [reply bpf/Makefile]: @rgo3  I removed the changes from the Makefile.

File: pkg/datapath/loader/verifier_load_test.go [hunk 30]
```diff
@@ -26,6 +26,7 @@ func hostLoadPermutations() iter.Seq[*config.BPFHost] {
 		for permutation := range permute(1) {
```
Comment (rgo3) [inline pkg/datapath/loader/verifier_load_test.go]:
```suggestion
		for permutation := range permute(2) {
```

I think you'll need to do this since your are now permuting two boolean values. Accessing permutation[1] without this change should also be index out of bounds if you'd run this test locally.

Comment (behzad-mir) [reply pkg/datapath/loader/verifier_load_test.go]: corrected.

File: pkg/datapath/config/host_config.go (hunk 29 above)
Comment (behzad-mir) [reply pkg/datapath/config/host_config.go:18]: @rgo3 let me know if the changes address the issue.

**Comment by behzad-mir** [comment]
> Picking up the review from Timo here, as I was assigned initially for loader anyway. Overall looks good, we should just make sure the config variable is covered in verifier tests.

@joestringer is it possible to merge the PR with outstanding request for change from @ti-mo? I think @rgo3 is reviewing in his stead.

**Comment by joestringer** [comment]
> is it possible to merge the PR with outstanding request for change from @ti-mo? I think @rgo3 is reviewing in his stead.

Yes, as long as Robin is good with it, he covers the @cilium/loader code owner. :+1:

File: pkg/datapath/config/host_config.go (hunk 29 above)
Comment (rgo3) [reply pkg/datapath/config/host_config.go:18]: Looks good!

File: pkg/datapath/loader/loader.go [hunk 31]
```diff
@@ -203,6 +203,10 @@ func netdevRewrites(ep datapath.EndpointConfiguration, lnc *datapath.LocalNodeCo
 		if option.Config.EnableIPv6Masquerade && ipv6.IsValid() {
 			cfg.NATIPv6Masquerade = ipv6.As16()
 		}
+		// Masquerading IPv4 traffic from endpoints leaving the host.
+		if option.Config.EnableRemoteNodeMasquerade {
```
Comment (rgo3) [inline pkg/datapath/loader/loader.go]: Nit
```suggestion
		cfg.EnableRemoteNodeMasquerade = option.Config.EnableRemoteNodeMasquerade
```

**Review by rgo3 — APPROVED** [review]
Loader changes LGTM!

**Comment by behzad-mir** [comment]
> > is it possible to merge the PR with outstanding request for change from @ti-mo? I think @rgo3 is reviewing in his stead.
> 
> Yes, as long as Robin is good with it, he covers the @cilium/loader code owner. 👍

Can you and @pchaigno also make sure that the requested changes are covered or not, thanks.

**Comment by behzad-mir** [comment]
@joestringer @pchaigno I addressed all of the comments and waiting for your review.

**Comment by kevinvalk** [comment]
Sorry to be a party pooper here... but this flag does not differentiate traffic for node InternalIP and ExternalIP. Both of these IPs will receive identity `reserved:remote-node` (6) and with this flag both traffic to these IPs will be masqueraded. I believe this will make this flag quite limited in its use. In my case for example, my `InternalIPs` are reachable native, but `ExternalIPs` are not....

Wouldn't it be way nicer and "easier" (in the end) to somehow allow end user to define which identities should be assigned to `InternalIP` and `ExternalIP` node addresses? That way, one could configure that all `externalIPs` should be given `reserved:world` identity which also would result in it being nicely masqueraded.

I tried to figure out where in the code node addresses are "assigned" identities, but did not fully grasp how and where this was done.

**Comment by tamilmani1989** [comment]
> Sorry to be a party pooper here... but this flag does not differentiate traffic for node InternalIP and ExternalIP. Both of these IPs will receive identity `reserved:remote-node` (6) and with this flag both traffic to these IPs will be masqueraded. I believe this will make this flag quite limited in its use. In my case for example, my `InternalIPs` are reachable native, but `ExternalIPs` are not....
> 
> Wouldn't it be way nicer and "easier" (in the end) to somehow allow end user to define which identities should be assigned to `InternalIP` and `ExternalIP` node addresses? That way, one could configure that all `externalIPs` should be given `reserved:world` identity which also would result in it being nicely masqueraded.
> 
> I tried to figure out where in the code node addresses are "assigned" identities, but did not fully grasp how and where this was done.

@kevinvalk that's correct. I believe the intention of PR is to make the behavior consistent with upstream ip-masq-agent. This PR will snat remote internal node ips if ip masq agent config excludes node cidr from non-masquerade list and new flag `enable-remote-node-snat` is enabled.  May be this work can be extended in future to address the usecase you specified.

**Comment by joestringer** [comment]
@kevinvalk I wonder if this is a use case you could capture into the masquerade discussion thread in https://github.com/cilium/cilium/discussions/36335 ? I do feel overall that we need a more cohesive configuration for all of the masquerade settings, and I think it would help for us to collect together the use cases in one place so that if someone were to try to come up with a cohesive idea about how all the cases could be configured through a single configuration interface then they would have one place to consult. 

As far as I understand the common parameters with some of this recent increase in interest is (a) running without tunneling and (b) on networks with nodes across multiple subnets. I'm not entirely sure that more NAT is going to get us into a better space here, because for instance enabling this new flag could cause surprising policy behavior where traffic from Pods towards remote nodes could be misclassified. That said, the main reason I haven't pushed back against this more is that there is an argument for consistency with how upstream ip-masq-agent works. The configuration is arguably pretty clear, even if that causes other features to work poorly.

While it'd be ideal to make this work for all the use cases, I don't think it's fair to block this PR which is useful for some people based on the goal of supporting another use case. From that perspective I agree with @tamilmani1989 that we could consider solving this problem on top.

**Comment by joestringer** [comment]
Acknowledging the CI is all green now. The test stability in the main tree has not been as green as I'd like, but getting it green again is a step by step process. Thanks for helping by filing and interacting on issues that you've found.

I had been holding back on review of this for a few reasons - one, deferring to @cilium/sig-datapath to better balance the maintenance workload; two, because CI hadn't passed and unless a PR is consistently passing CI it's hard for a third party to understand whether the failures are introduced by the PR or not, and three because I was under the impression some of the feedback had not yet been addressed. Unfortunately given how long it's dragged out, and due to summer vacations the reviewers have rotated a bit. However I think this has received plenty of scrutiny from the primary owners - @cilium/sig-datapath and @cilium/loader . On the last part I think what happened is that some feedback was provided on a couple of the documentation blurbs but not all of them, and you had applied the feedback on the ones which received comments. `Documentation/network/concepts/masquerading.rst` is not entirely consistent on that front, but that's easy enough to tidy up in a subsequent PR. For future I would suggest setting a line limit suggestion of 80 characters to conform most submissions to that line length, and that could avoid a couple of the back/forth discussion threads seen above.

**Review by joestringer — APPROVED** [review]

**Comment by tamilmani1989** [comment]
Thanks @joestringer for approval and merge!
