### PR TITLE
ipam: Update node information retrieval logic

### LINKED ISSUE #38471: ipv6 only cluster doesn't work well with multi pool ipam
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.2 and lower than v1.18.0

### What happened?

If using IPAM multi pool in ipv6 only environment with some k8s distribution(Openshift and EKS). the agent could complains
`level=fatal msg="Cannot autocomplete node addresses" error="IPv6 allocation CIDR is not configured. Please specify --ipv6-range" subsys=daemon
`

That's because their k8s nodes could have empty spec for example
```
apiVersion: v1
kind: Node
metadata:
  annotations:
    machineconfiguration.openshift.io/controlPlaneTopology: HighlyAvailable
    machineconfiguration.openshift.io/currentConfig: rendered-worker-e3216e04ae1b9e67ce70c8c1f555cce5
    machineconfiguration.openshift.io/desiredConfig: rendered-worker-e3216e04ae1b9e67ce70c8c1f555cce5
    machineconfiguration.openshift.io/desiredDrain: uncordon-rendered-worker-e3216e04ae1b9e67ce70c8c1f555cce5
    machineconfiguration.openshift.io/lastAppliedDrain: uncordon-rendered-worker-e3216e04ae1b9e67ce70c8c1f555cce5
    machineconfiguration.openshift.io/lastSyncedControllerConfigResourceVersion: "19503"
    machineconfiguration.openshift.io/reason: ""
    machineconfiguration.openshift.io/state: Done
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2025-03-23T16:21:06Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: ocp-workers-0
    kubernetes.io/os: linux
    node-role.kubernetes.io/worker: ""
    node.openshift.io/os_id: rhcos
  name: ocp-workers-0
  resourceVersion: "282168"
  uid: 7340c9f7-dc9f-4e47-8633-eac706f97239
spec: {}
```
However, our agent code doesn't consider the newer IPAM mode(like multi-pool) and only copy from `CiliumNode` when it's cluster-pool mode.

https://github.com/liyihuang/cilium/blob/4912f7a79eabc8e7bd3eec5a0364cde15fe87ec5/daemon/k8s/init.go#L38-L77

In dual stack mode, we assign the ipv6 CIDR from the ipv4.
https://github.com/cilium/cilium/blob/50a5a2e21f8dcce67f241203a99c6aba9dab4b2c/pkg/node/address.go#L138-L149

If it's ipv6 mode, we will get the error log that I posted here.

### How can we reproduce the issue?

disable ipv4, enable the ipv6  and use the IPAM multipool

### Cilium Version

any

### Kernel Version

any

### Kubernetes Version

any

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by liyihuang**
~~Change the logic now retrieves node information from Kubernetes nodes when using `IPAMKubernetes`, and from Cilium nodes when using the default configuration to cover the multi pool IPAM and other possible values for IPAM.~~

The CiliumNode is created early when the IPAM mode is cluster pool and multi pool. 

We will retrive the node info from CiliumNode when the ipam mode is cluster pool or multi pool.

Fixes: #38471

```release-note
Fix the ipv6 only cluster doesn't work with multi pool in some k8s distribution(Openshift)
```

### CODE REVIEW

File: daemon/k8s/init.go [hunk 1]
```diff
@@ -73,6 +73,7 @@ func retrieveNodeInformation(ctx context.Context, log logrus.FieldLogger, localN
 			}
 			event.Done(nil)
 		}
+
```
Comment (doniacld) [inline daemon/k8s/init.go]: You can remove the useless blank line I think

**Review by dylandreimerink — COMMENTED** [review]
This looks good to me. Looped in @gandro for a double check.

**Review by gandro — CHANGES_REQUESTED** [review]
I'm not sure what particular problem is solved here, i.e. why this change would fix any issue. 

All non-kubernetes and non-cluster-pool IPAM allocators will wait for the CiliumNode object themselves, e.g. here:


https://github.com/cilium/cilium/blob/1fb88a1572f927c4c2a77981aa9e6bff5cbc5e39/pkg/ipam/crd.go#L201-L221
https://github.com/cilium/cilium/blob/01c199a4b00a3960cc6a080ec7a207218a781fb9/pkg/ipam/multipool.go#L295

 So what do we gain from waiting for the CiliumNode object early? 

In particular, I think if we wait for the CiliumNode object for all non-kubernetes IPAM modes, then we also need to force early creation of the CiliumNode object here (otherwise I think this code will deadlock in ENI mode - I have started an EKS test to verify):

https://github.com/cilium/cilium/blob/ccc826c6a8a336cb8cbd10296ee3965224fa3d06/daemon/cmd/daemon.go#L596-L601

IPAM:ENI et all delay the creation of the CiliumNode resource until IPAM is started.

**Comment by liyihuang** [comment]
the particular issue I'm fixing is here(https://github.com/cilium/cilium/issues/38471)


I think the core problem is in non ClusterPool IPAM mode, we are trying to update the Node here(https://github.com/liyihuang/cilium/blob/0380724290f01576aa053c2c2ad35532063c695e/daemon/k8s/init.go#L114-L139). 

In this case(multi pool and ipv6), it will get the Nil from k8s `Node` and Nil will be passed to LocalNode, then it will start to fail  here(https://github.com/liyihuang/cilium/blob/0380724290f01576aa053c2c2ad35532063c695e/pkg/node/address.go#L286-L287)


I can see we dont hit this issue because ipv6 only cluster is not popular and we have https://github.com/liyihuang/cilium/blob/0380724290f01576aa053c2c2ad35532063c695e/pkg/node/address.go#L284 to set `IPv4AllocCIDR` field if that's Nil. Where I really confuse me, this is set wrong in many cases. 

For example, EKS k8s Node doesn't have `podCIDR` field where we cloud just set the default prefix to it based on my understanding. However, we didn't receive any bug from it. Based on how we LocalNode, I think we only copy the field from k8s nodes when the IPAM is kubernetes and copy from CiliumNodes for others IPAM mode. 

I think for this particular issue, we could copy from CiliumNode when IPAM mode is ClusterPool or MultiPool. But I think my PR will cover other scenarios. 

```
apiVersion: v1
kind: Node
metadata:
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: m5.2xlarge
    beta.kubernetes.io/os: linux
    eks.amazonaws.com/capacityType: ON_DEMAND
    failure-domain.beta.kubernetes.io/region: us-west-2
    failure-domain.beta.kubernetes.io/zone: us-west-2a
    k8s.io/cloud-provider-aws: 84a170f854d6410f52cad8717663db7e
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: ip-10-6-5-xxx.us-west-2.compute.internal
    kubernetes.io/os: linux
    node.kubernetes.io/instance-type: m5.2xlarge
    topology.ebs.csi.aws.com/zone: us-west-2a
    topology.kubernetes.io/region: us-west-2
    topology.kubernetes.io/zone: us-west-2a
  name: ip-10-6-5-xxx.us-west-2.compute.internal
  resourceVersion: "268957266"
  uid: def62ee3-0540-4c9e-9e29-e5e74d0668c0
spec:
  providerID: aws:///us-west-2a/i-0e39049c243xxx
```

I also dont understand why we need to set the default prefix here(https://github.com/liyihuang/cilium/blob/0380724290f01576aa053c2c2ad35532063c695e/pkg/node/address.go#L284)

**Comment by dylandreimerink** [comment]
> I'm not sure what particular problem is solved here, i.e. why this change would fix any issue.

Its slightly stupid actually. We assert in `AutoComplete` called by `Daemon.configureIPAM` that we always have a a non-nil `IPv6AllocCIDR` set on the local node. Which is only ever set by `WaitForNodeInformation`, which gets that CIDR from the k8s or Cilium node depending on which is returned by `retrieveNodeInformation`.

Since `retrieveNodeInformation` was checking for `option.Config.IPAM == ipamOption.IPAMClusterPool`, it would actually wait for the k8s node when in multi-pool IPAM mode, which doesn't have the CIDR ranges set (since these are set on the CiliumNode in multi-pool mode). Thus `IPv6AllocCIDR` on the local node remains nil when only IPv6 is enabled, thus failing the assertion in `AutoComplete`.

That is why this PR "fixes" the error.

Now, the multi-pool allocator doesn't actually depend on  `IPv6AllocCIDR`, it gets the CiliumNode object itself. However, plenty of other parts of Cilium do use `IPv6AllocCIDR` to make routes, iptables entries, and the like. 

I think we should be able to delete the whole `WaitForNodeInformation`, and we should make the IPAM allocator inform the rest of the agent about the PodCIDR ranges that are actually in use. Nowadays, its a set of ranges that can change during agent runtime. Yet a lot of the codebase assumes a single range that is static and determined on startup.

As far as I am able to tell the  `IPv{4,6}AllocCIDR` is wrong for every IPAM mode except for `kubernetes`, `cluster-pool`, and after this PR `multi-pool`. This is being masked by the defaults set in `SetDefaultPrefix`.

**Comment by gandro** [comment]
Thanks for the explanations! 

> As far as I am able to tell the IPv{4,6}AllocCIDR is wrong for every IPAM mode except for kubernetes, cluster-pool, and after this PR multi-pool. This is being masked by the defaults set in SetDefaultPrefix.
This is correct. x-ref https://github.com/cilium/cilium/issues/27018 


I think I understand now how this works around the problem. I still don't understand why we do not also have to update the if condition on the CiliumNode creation here here: https://github.com/cilium/cilium/blob/ccc826c6a8a336cb8cbd10296ee3965224fa3d06/daemon/cmd/daemon.go#L596-L601

How can in ENI IPAM `WaitForNodeInformation` observe a CiliumNode if `UpdateCiliumNodeResource` (which creates the initial CiliumNode resource) is not called?

**Comment by dylandreimerink** [comment]
> How can in ENI IPAM WaitForNodeInformation observe a CiliumNode if UpdateCiliumNodeResource (which creates the initial CiliumNode resource) is not called?

I suspect it can't. So it will wait for the 10 second timeout, then continue since we do not set the `--k8s-require-ipv4-pod-cidr` or `--k8s-require-ipv6-pod-cidr` in CI. So this likely adds 10 time to the startup for ENI and the like.

So, I think the best way to clean it up is to do the following for `retrieveNodeInformation`:

```go
switch option.Config.IPAM {
 case ipamOption.IPAMClusterPool, ipamOption.IPAMMultiPool:
    // wait for and return CiliumNode
  case ipamOption.IPAMKubernetes:
    // wait for and return k8s Node
  default:
   return errors.New("some descriptive error")
```

Then in `newDaemon` gate the calling of `WaitForNodeInformation`:

```go
if option.Config.IPAM == ipamOption.IPAMClusterPool ||
	option.Config.IPAM == ipamOption.IPAMMultiPool || 
	option.Config.IPAM == ipamOption.IPAMKubernetes {
	if err := agentK8s.WaitForNodeInformation(d.ctx, log, params.Resources.LocalNode, params.Resources.LocalCiliumNode); err != nil {
		log.WithError(err).Error("unable to connect to get node spec from apiserver")
		return nil, nil, fmt.Errorf("unable to connect to get node spec from apiserver: %w", err)
	}
}
```

That should eliminate the need to wait for anything if its not going to be useful anyway. 

Once https://github.com/cilium/cilium/issues/27018 has been sorted we can remove it.

**Comment by liyihuang** [comment]
> I suspect it can't. So it will wait for the 10 second timeout, then continue since we do not set the `--k8s-require-ipv4-pod-cidr` or `--k8s-require-ipv6-pod-cidr` in CI. So this likely adds 10 time to the startup for ENI and the like.

I doubt it because after seeing  this post https://medium.com/@amitmavgupta/cilium-ipv6-in-eks-e1fe7735feff. 

If it just times out, in the pure ipv6 EKS environment. People should have the issue that I posted it here since we can't get the podCIDR from k8s nodes in EKS environment and the default prefix can't be set.

I admit my PR isn't accurate since I didn't consider the time of CIliumNode creation. 


But changing to this will be also problematic since other IPAM mode could get panic if they are on ipv6 and can get podCIDR from k8s nodes

```go
if option.Config.IPAM == ipamOption.IPAMClusterPool ||
	option.Config.IPAM == ipamOption.IPAMMultiPool || 
	option.Config.IPAM == ipamOption.IPAMKubernetes {
	if err := agentK8s.WaitForNodeInformation(d.ctx, log, params.Resources.LocalNode, params.Resources.LocalCiliumNode); err != nil {
		log.WithError(err).Error("unable to connect to get node spec from apiserver")
		return nil, nil, fmt.Errorf("unable to connect to get node spec from apiserver: %w", err)
	}
}
   
```

Maybe the minimal impact of fixing this issue is to match how we create the CiliumNode here(https://github.com/cilium/cilium/blob/ccc826c6a8a336cb8cbd10296ee3965224fa3d06/daemon/cmd/daemon.go#L596-L601)

```go
	if option.Config.IPAM == ipamOption.IPAMClusterPool ||
		option.Config.IPAM == ipamOption.IPAMMultiPool {
		for event := range localCiliumNodeResource.Events(ctx) {
			if errors.Is(ctx.Err(), context.DeadlineExceeded) {
				log.WithField(logfields.NodeName, nodeTypes.GetName()).Error("Timeout while waiting for CiliumNode resource: API server connection issue")
				break
			}
			if event.Kind == resource.Upsert {
				no := nodeTypes.ParseCiliumNode(event.Object)
				n = &no
				log.WithField(logfields.NodeName, n.Name).Info("Retrieved node information from cilium node")
				if err := waitForCIDR(); err != nil {
					log.WithError(err).Warning("Waiting for k8s node information")
				} else {
					event.Done(nil)
					break
				}
			}
			event.Done(nil)
		}
```


I will spin up the EKS cluster with pure ipv6 to see how thing works

**Review by gandro — APPROVED** [review]
