### PR TITLE
test(config): run tests in dedicated netns

### LINKED ISSUE #22433: CI: go test ./pkg/datapath/loader fails: Link does not exist
This issue is not observed in CI, however I notice it when running the privileged tests locally in my Ubuntu 22.04 environment against the master branch:

```
$ sudo -E make tests-privileged                                                                                                                                                                                                    [182/26533]
[sudo] password for joe:                                                                                                                                                                                                                                                                   
PRIVILEGED_TESTS=true PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/joe/git/cilium/bpf CGO_ENABLED=0 go test -mod=vendor -tags=osusergo -ldflags "-X github.com/cilium/cilium/pkg/kvstore.consulDummyAddress=https://consul:8443 -X github.com/cilium/c
ilium/pkg/kvstore.etcdDummyAddress=http://etcd:4002 -X github.com/cilium/cilium/pkg/datapath.DatapathSHA256=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" \                                                                                                            
        ./... -test.v -timeout 600s -json -covermode=count -coverprofile=coverage.out | tparse                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                           
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                                                                                                                                                                                                                        
┃   FAIL  package: github.com/cilium/cilium/pkg/datapath/loader   ┃                                                                                                                                                                                                                        
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                           
--- FAIL: Test (13.48s)                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                           
level=info msg="Using autogenerated IPv4 allocation range" subsys=node v4Prefix=10.1.0.0/16                                                                                                                                                                                                
level=info msg="Using autogenerated IPv6 allocation range" subsys=node v6Prefix="f00d::a01:0:0:0/96"                                                                                                                                                                                       
level=error msg="Link does not exist" device=cilium_net error="Link not found" subsys=datapath-loader                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                           
----------------------------------------------------------------------                                                                                                                                                                                                                     
FAIL: loader_test.go:165: LoaderTestSuite.TestCompileAndLoadHostEndpoint                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                           
loader_test.go:179:                                                                                                                                                                                                                                                                        
    s.testCompileAndLoad(c, &hostEp)                                                                                                                                                                                                                                                       
loader_test.go:154:                                                                                                                                                                                                                                                                        
    c.Assert(err, IsNil)                                                                                                                                                                                                                                                                   
... value netlink.LinkNotFoundError = netlink.LinkNotFoundError{error:(*errors.errorString)(0xc0005a20d0)} ("Link not found")                                                                                                                                                              
                                                                                                                                                                                                                                                                                           
level=info msg="Compiled new BPF template" BPFCompilationTime=1.201441695s file-path=/tmp/cilium_test1977592565/templates/66e66027ec503c0d3bd84f6df8c887e45638cf0ab81cf7d82218b48841fc471d/bpf_lxc.o subsys=datapath-loader                                                                
level=info msg="Compiled new BPF template" BPFCompilationTime=1.124382949s file-path=/tmp/cilium_test1977592565/templates/049a251dd9f895fb71a76f6349fcd7b95b39232474711e5fe7aabc4fe93e6df0/bpf_lxc.o subsys=datapath-loader                                                                
level=info msg="Compiled new BPF template" BPFCompilationTime=1.201681338s file-path=/tmp/cilium_test741519073/templates/3d74155c77be515a600048efd2bfd2db3811a6019f3fa693573f34d6a929ea22/bpf_lxc.o subsys=datapath-loader                                                                 
level=info msg="Compiled new BPF template" BPFCompilationTime=1.527059091s file-path=/tmp/cilium_test741519073/templates/7938b4f4365fae566285006eb62aca0b9a0c0006909a0fb7e06c9dd0596b2c27/bpf_lxc.o subsys=datapath-loader                                                                 
level=info msg="Compiled new BPF template" BPFCompilationTime=1.687688608s file-path=/tmp/cilium_test741519073/templates/c1cc079b9189e6659deb1bd51235fdb2f8833daee728422a90349bcbc6678a81/bpf_lxc.o subsys=datapath-loader                                                                 
level=info msg="Compiled new BPF template" BPFCompilationTime=1.740012043s file-path=/tmp/cilium_test741519073/templates/312c7c9cd762c4d8942c6278c249dc0fe183c4c22fcca1b87a2d595d2361cb16/bpf_lxc.o subsys=datapath-loader                                                                 
level=info msg="Compiled new BPF template" BPFCompilationTime=1.823694022s file-path=/tmp/cilium_test741519073/templates/3d74155c77be515a600048efd2bfd2db3811a6019f3fa693573f34d6a929ea22/bpf_lxc.o subsys=datapath-loader                                                                 
level=info msg="Compiled new BPF template" BPFCompilationTime=2.284098425s file-path=/tmp/cilium_test741519073/templates/312c7c9cd762c4d8942c6278c249dc0fe183c4c22fcca1b87a2d595d2361cb16/bpf_lxc.o subsys=datapath-loader                                                                 
level=info msg="Compiled new BPF template" BPFCompilationTime=2.477713267s file-path=/tmp/cilium_test741519073/templates/3d74155c77be515a600048efd2bfd2db3811a6019f3fa693573f34d6a929ea22/bpf_lxc.o subsys=datapath-loader
level=info msg="Compiled new BPF template" BPFCompilationTime=2.486516728s file-path=/tmp/cilium_test741519073/templates/34dfc680d96948579bcf46e860aa7317c10968dcc2246fe3bed80ea1b14b1596/bpf_lxc.o subsys=datapath-loader
level=info msg="Compiled new BPF template" BPFCompilationTime=2.494995266s file-path=/tmp/cilium_test741519073/templates/c1cc079b9189e6659deb1bd51235fdb2f8833daee728422a90349bcbc6678a81/bpf_lxc.o subsys=datapath-loader
level=info msg="Compiled new BPF template" BPFCompilationTime=2.693360568s file-path=/tmp/cilium_test741519073/templates/7d904e5b0e063ace19cd292a4a7b45a7a79848adaedcbfb0bcf6ba4441515500/bpf_lxc.o subsys=datapath-loader
level=info msg="Compiled new BPF template" BPFCompilationTime=2.781194192s file-path=/tmp/cilium_test741519073/templates/7938b4f4365fae566285006eb62aca0b9a0c0006909a0fb7e06c9dd0596b2c27/bpf_lxc.o subsys=datapath-loader
level=info msg="Compiled new BPF template" BPFCompilationTime=2.849800176s file-path=/tmp/cilium_test741519073/templates/b477b8a9d9f82a8fdb1243c350c35fee79757a0fa6c0aac5577225a3cef6431f/bpf_lxc.o subsys=datapath-loader
level=info msg="Compiled new BPF template" BPFCompilationTime=3.071249398s file-path=/tmp/cilium_test741519073/templates/b0130490420ac62f0608003819a40206ad48cc027c0184986c988c2477ec379a/bpf_lxc.o subsys=datapath-loader
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.ipv6.conf.dummy9.forwarding sysParamValue=1                                  
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.ipv4.conf.dummy9.forwarding sysParamValue=1                                  
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.ipv4.conf.dummy9.rp_filter sysParamValue=0                                   
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.ipv4.conf.dummy9.accept_local sysParamValue=1                                
level=info msg="Setting sysctl" subsys=sysctl sysParamName=net.ipv4.conf.dummy9.send_redirects sysParamValue=0                              
OOPS: 9 passed, 1 FAILED
...
```

### PR DESCRIPTION
**Pull request by AritraDey-Dev**
Fixes #22433

Fix privileged test issue observed locally .
Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

Fixes: #22433

```release-note
Fixed an issue where privileged tests failed locally 
```

### CODE REVIEW

**Review by ti-mo — CHANGES_REQUESTED** [review]
Please use `pkg/testutils/netns` for this, no need for the manual netns plumbing.

Simply:

```go
ns := netns.NewNetNS(t)
ns.Do(func() {
// test code
})
```

**Comment by AritraDey-Dev** [comment]
> Please use `pkg/testutils/netns` for this, no need for the manual netns plumbing.

updated!

File: pkg/datapath/linux/config/config_test.go [hunk 1]
```diff
@@ -33,6 +33,7 @@ import (
 	"github.com/cilium/cilium/pkg/maps/nodemap/fake"
 	"github.com/cilium/cilium/pkg/option"
 	"github.com/cilium/cilium/pkg/testutils"
+	testnetns "github.com/cilium/cilium/pkg/testutils/netns"
```
Comment (ti-mo) [inline pkg/datapath/linux/config/config_test.go]: Why is this import aliased?

File: pkg/datapath/linux/config/config_test.go [hunk 2]
```diff
@@ -117,11 +118,33 @@ func writeConfig(t *testing.T, header string, write writeFn) {
...
+func setupCiliumDummyDevices(t *testing.T) func() {
+	ciliumNet := &netlink.Dummy{LinkAttrs: netlink.LinkAttrs{Name: "cilium_net"}}
+	require.NoError(t, netlink.LinkAdd(ciliumNet))
+	require.NoError(t, netlink.LinkSetUp(ciliumNet))
+
+	ciliumHost := &netlink.Dummy{LinkAttrs: netlink.LinkAttrs{Name: "cilium_host"}}
+	require.NoError(t, netlink.LinkAdd(ciliumHost))
+	require.NoError(t, netlink.LinkSetUp(ciliumHost))
+
+	return func() {
```
Comment (ti-mo) [inline pkg/datapath/linux/config/config_test.go]: Use `t.Cleanup()` instead of returning a closure. This function should take a `netns.NetNS` so you can call `ns.Do()` within the cleanup function to avoid executing netlink operations in the host netns.

Then `setupCiliumDummyDevices` doesn't need to be executed within the `ns.Do()` in the main test either.

File: pkg/datapath/linux/config/config_test.go [hunk 3]
```diff
@@ -117,11 +118,33 @@ func writeConfig(t *testing.T, header string, write writeFn) {
 	}
 }
 
+func setupCiliumDummyDevices(t *testing.T) func() {
```
Comment (ti-mo) [inline pkg/datapath/linux/config/config_test.go]: This function should call `t.Helper()` first thing.

File: pkg/datapath/linux/config/config_test.go [hunk 4]
```diff
@@ -234,81 +257,75 @@ return false;`, main1.Index, main2.Index), m)
...
-		}),
-	)
-
-	tlog := hivetest.Logger(t)
-	require.NoError(t, h.Start(tlog, context.TODO()))
-	t.Cleanup(func() { h.Stop(tlog, context.TODO()) })
-
-	var buffer bytes.Buffer
-
-	// Assert that configurations are propagated when all generated extra defines are valid
```
Comment (ti-mo) [inline pkg/datapath/linux/config/config_test.go:261]: Please don't throw away all formatting, comments and extra line breaks. Just reindent it.

**Review by ti-mo — CHANGES_REQUESTED** [review]

File: pkg/datapath/linux/config/config_test.go (hunk 4 above)
Comment (AritraDey-Dev) [reply pkg/datapath/linux/config/config_test.go:261]: Actually, if I just run `gofmt -w pkg/datapath/linux/config/config_test.go`, it automatically indents the code and removes extra spaces and gaps.

File: pkg/datapath/linux/config/config_test.go (hunk 1 above)
Comment (AritraDey-Dev) [reply pkg/datapath/linux/config/config_test.go]: As the import `"github.com/cilium/cilium/pkg/netns"` is also required.

File: pkg/datapath/linux/config/config_test.go [hunk 5]
```diff
@@ -382,32 +424,38 @@ func TestPreferredIPv6Address(t *testing.T) {
 }
 
 func TestNewHeaderfileWriter(t *testing.T) {
-	testutils.PrivilegedTest(t)
```
Comment (ti-mo) [inline pkg/datapath/linux/config/config_test.go:385]: `testutils.PrivilegedTest(t)` is still necessary here.

File: pkg/datapath/linux/config/config_test.go [hunk 6]
```diff
@@ -234,81 +271,86 @@ return false;`, main1.Index, main2.Index), m)
 }
 
 func TestWriteNodeConfigExtraDefines(t *testing.T) {
-	testutils.PrivilegedTest(t)
```
Comment (ti-mo) [inline pkg/datapath/linux/config/config_test.go:237]: `testutils.PrivilegedTest(t)` is still necessary here.

File: pkg/datapath/linux/config/config_test.go [hunk 7]
```diff
@@ -117,11 +119,46 @@ func writeConfig(t *testing.T, header string, write writeFn) {
...
+		_ = ns.Do(func() error {
+			netlink.LinkDel(&netlink.Dummy{LinkAttrs: netlink.LinkAttrs{Name: "cilium_net"}})
+			netlink.LinkDel(&netlink.Dummy{LinkAttrs: netlink.LinkAttrs{Name: "cilium_host"}})
+			return nil
+		})
+	})
+}
+
 func TestWriteNodeConfig(t *testing.T) {
-	setupConfigSuite(t)
```
Comment (ti-mo) [inline pkg/datapath/linux/config/config_test.go:121]: `testutils.PrivilegedTest(t)` is still necessary here. (setupConfigSuite calls it)

**Review by ti-mo — CHANGES_REQUESTED** [review]

File: pkg/datapath/linux/config/config_test.go (hunk 1 above)
Comment (ti-mo) [reply pkg/datapath/linux/config/config_test.go]: Ah, it's needed to import the `netns.NetNS` type. In that case, let's re-export the NetNS type from `pkg/testutils/netns/netns.go`. Please add the following in a separate commit:

At the top of netns.go:
```go
// NetNS is a type alias for netns.NetNS to avoid having to import both packages
// in tests.
type NetNS = netns.NetNS

// NewNetNS returns a new network namespace.
func NewNetNS(tb testing.TB) *NetNS
```

Then you can remove the `pkg/netns` import from the test file and import `testutils/netns` without alias. Should work without any further changes to your code.

File: pkg/datapath/linux/config/config_test.go (hunk 5 above)
Comment (AritraDey-Dev) [reply pkg/datapath/linux/config/config_test.go:385]: But this calling this inside `ns.Do` why is it necessary to call it at the top?

Comment (ti-mo) [reply pkg/datapath/linux/config/config_test.go:385]: Creating a namespace is also a privileged operation. :slightly_smiling_face: Try running the tests without sudo, it'll fail.

File: pkg/datapath/linux/config/config_test.go [hunk 8]
```diff
@@ -383,31 +425,37 @@ func TestPreferredIPv6Address(t *testing.T) {
...
-	_, err := NewHeaderfileWriter(WriterParams{
-		NodeAddressing:     fakeTypes.NewNodeAddressing(),
-		NodeExtraDefines:   []dpdef.Map{a, a},
-		NodeExtraDefineFns: nil,
-		Sysctl:             sysctl.NewDirectSysctl(afero.NewOsFs(), "/proc"),
-		NodeMap:            fake.NewFakeNodeMapV2(),
-	})
+	ns := netns.NewNetNS(t)
+	err := ns.Do(func() error {
+		setupCiliumDummyDevices(t, ns)
```
Comment (ti-mo) [inline pkg/datapath/linux/config/config_test.go]: Nit: this should be moved out of the ns.Do()

**Review by ti-mo — APPROVED** [review]

**Comment by ti-mo** [comment]
Note: names of privileged tests now need to be prefixed with TestPrivileged.

File: pkg/datapath/linux/config/config_test.go [hunk 9]
```diff
@@ -117,11 +118,47 @@ func writeConfig(t *testing.T, header string, write writeFn) {
...
+		if err := netlink.LinkSetUp(ciliumHost); err != nil {
+			return err
+		}
+		return nil
+	}))
+
+	t.Cleanup(func() {
+		_ = ns.Do(func() error {
+			netlink.LinkDel(&netlink.Dummy{LinkAttrs: netlink.LinkAttrs{Name: "cilium_net"}})
+			netlink.LinkDel(&netlink.Dummy{LinkAttrs: netlink.LinkAttrs{Name: "cilium_host"}})
```
Comment (christarazi) [inline pkg/datapath/linux/config/config_test.go]: Both of these return errors yet this function simply returns nil as an error. Shouldn't these errors be captured?

**Review by christarazi — APPROVED** [review]

File: pkg/datapath/linux/config/config_test.go (hunk 9 above)
Comment (AritraDey-Dev) [reply pkg/datapath/linux/config/config_test.go]: Since the namespace is being deleted anyway, handling these errors is not strictly necessary. However, for better debugging, I will add this.

File: pkg/datapath/linux/config/config_test.go [hunk 10]
```diff
@@ -117,11 +118,56 @@ func writeConfig(t *testing.T, header string, write writeFn) {
...
+	setupCiliumDummyDevices(t, ns)
+	err := ns.Do(func() error {
+		setupConfigSuite(t)
+		writeConfig(t, "node", func(w io.Writer, dp datapath.ConfigWriter) error {
+			return dp.WriteNodeConfig(w, &dummyNodeCfg)
+		})
+		return nil
 	})
+	require.NoError(t, err)
 }
```
Comment (joestringer) [inline pkg/datapath/linux/config/config_test.go:171]: Why does this test need to be privileged or do netns, dummy device setup, etc.? Isn't it just taking a structure and printing it to a writer?

Comment (AritraDey-Dev) [reply pkg/datapath/linux/config/config_test.go:171]: I added this because of https://github.com/cilium/cilium/pull/40150#discussion_r2189740944. However, your comment makes more sense. From what I understand, the `TestPrivilegedWriteNetdevConfig` function is already handling the same functionality. Also, even without making that test privileged, the tests are still passing.

Comment (joestringer) [reply pkg/datapath/linux/config/config_test.go:171]: I dug in a bit more to understand my question better. It turns out that `WriteNodeConfig()` does a bunch of queries of Linux networking state like links and so on. Those aspects aren't abstracted out of the config write itself, so for now the test needs extra boilerplate like this just to satisfy the way the function is written. That makes sense, sorry for the noise.

As for `WriteNetdevConfig`, no that is an entirely different facility.

I'll resolve this conversation and merge as is. Thanks!

**Comment by jingyuanliang** [comment]
Can we cherry-pick this into v1.18?

**Comment by julianwiedmann** [comment]
This is also [failing in v1.18](https://github.com/cilium/cilium/issues/45379), setting the backport label.
