### PR TITLE
fix: Add support for changing the vxlan tunnel port after initial installation

### LINKED ISSUE #38581: Cilium cannot recover from a failed VXLAN interface device
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.2 and lower than v1.18.0

### What happened?

If there is already another VXLAN device with the same destination port when you install Cilium (e.g. when you have fan-networking enabled on your host), the cilium-agent fails to setup a VXLAN interface since `ensureDevice` function returns with
```
failed to setup vxlan tunnel device: setting up vxlan device: creating vxlan device cilium_vxlan: setting up device cilium_vxlan: address already in use
```
That is expected. However, if you try to change the `tunnel-port` for VXLAN and restart the Cilium, it still fails. That's because `setupVxlanDevice` first tries to set up the previously failed `cilium_vxlan` through `ensureDevice` before checking for a destination port change and recreation of the interface. As a result, the deployment gets stuck in a deadlock until the `cilium_vxlan` deleted manually.  

### How can we reproduce the issue?

1. Install kind 
2. Setup a vxlan device inside the kind's control plane node 
```
docker exec -it kind-control-plane sh
```
```
ip link add vxlan0 type vxlan id 100 dev eth0 dstport 8472
ip link set vxlan0 up
```
3. Install Cilium on kind using Helm (Cilium fails to start which is expected)
4. Edit the `cilium-config` and add `tunnel-port:"8473"`
```
kubectl edit cm/cilium-config -n kube-system
```
6. Restart the agent's DaemonSet
```
kubectl rollout restart ds/cilium -n kube-system
```

Cilium agent still failing and the destination port change on `cilium_vxlan` is not applied. 

### Cilium Version

cilium-cli: v0.18.2 compiled with go1.24.0 on linux/amd64
cilium image (default): v1.17.0
cilium image (stable): v1.17.2
cilium image (running): 1.17.2

### Kernel Version

inux localhost 6.8.0-53-generic #55-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 17 15:37:52 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: v1.32.3
Kustomize Version: v5.5.0
Server Version: v1.32.2

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

I have added a DRAFT PR for a possible fix to better demonstrate the issue. If the issue and the general direction to fix it get accepted, I'll be more than happy to implement a complete fix. 

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rapour**
Fixes: #38581

The `setupVxlanDevice` runs `ensureDevice` before checking for any configuration change. One of the steps defined in `ensureDevice` is to set up the vxlan interface. If the vxlan interface conflicts with another interface like having the same destination port, setting a different port will not resolve the issue since the `setupVxlanDevice` still fails through `ensureDevice` before even checking the port change. This fix suggests `setupVxlanDevice` checks for destination port change and recreate the interface before trying to bring the interface up.

### CODE REVIEW

File: pkg/datapath/loader/netlink.go [hunk 1]
```diff
@@ -277,22 +277,23 @@ func setupVxlanDevice(logger *slog.Logger, sysctl sysctl.Sysctl, port, srcPortLo
 		PortHigh:  int(srcPortHigh),
 	}
 
+	if l, err := safenetlink.LinkByName(dev.Attrs().Name); err == nil {
```
Comment (ti-mo) [inline pkg/datapath/loader/netlink.go:297]: It took me a while to realize what was going wrong here. Reading the error message posted in #38581 more closely:

> failed to setup vxlan tunnel device: setting up vxlan device: creating vxlan device cilium_vxlan: **setting up** device cilium_vxlan: address already in use

The error only occurs when setting the link 'up' conflicting links, e.g.:

```
~ ip link add vxlan0 type vxlan dev eth0 dstport 8472 external
~ ip link add vxlan1 type vxlan dev eth0 dstport 8472 id 100
~ ip link set dev vxlan0 up
~ ip link set dev vxlan1 up
RTNETLINK answers: Address already in use
```

This will indeed get the agent stuck if it conflicts with an externally-managed interface listening on the same port, since `ensureDevice` will try to set the device 'up' before the follow-up code in `setupVxlanDevice` gets a change to recreate the device.

I like the change overall since we end up with a single call to `ensureDevice`, but we really need to document this for posterity:

```suggestion
	// It's possible to create multiple vxlan devices with the same dstport,
	// though only one of them can be 'up'. Delete an existing vxlan device
	// with a mismatching port before attempting to create a new one to
	// to avoid ensureDevice setting up the old interface. This avoids the
	// agent getting stuck if it conflicts with an unmanaged vxlan interface.
	if l, err := safenetlink.LinkByName(dev.Attrs().Name); err == nil {
```

It would also be nice if we had an extra test for this.

**Review by ti-mo — CHANGES_REQUESTED** [review]

File: pkg/datapath/loader/netlink.go (hunk 1 above)
Comment (rapour) [reply pkg/datapath/loader/netlink.go:297]: Nice reminder, I have added the comment and also added a test case to check for successful configuration change after a port conflict with an externally managed device. Please let me know if the test needs any modification.

**Review by rgo3 — APPROVED** [review]
Also double checked that the test is currently failing on main, thanks!

**Comment by rgo3** [comment]
Could you please remove the merge commit, squash the two commits with the actual changes and rebase onto main?

File: pkg/datapath/loader/netlink.go (hunk 1 above)
Comment (ti-mo) [reply pkg/datapath/loader/netlink.go:297]: Looks good, thanks. :+1:

File: pkg/datapath/loader/netlink.go [hunk 2]
```diff
@@ -277,22 +277,28 @@ func setupVxlanDevice(logger *slog.Logger, sysctl sysctl.Sysctl, port, srcPortLo
 		PortHigh:  int(srcPortHigh),
 	}
 
+	// It's possible to create multiple vxlan devices with the same dstport,
+	// though only one of them can be 'up'. Delete an existing vxlan device
+	// with a mismatching port before attempting to create a new one to
+	// to avoid ensureDevice setting up the old interface. This avoids the
```
Comment (ti-mo) [inline pkg/datapath/loader/netlink.go]: I made a typo in the initial comment:

```suggestion
	// avoid ensureDevice setting up the old interface. This avoids the
```

**Review by ti-mo — APPROVED** [review]
Thanks! Left one nit.

File: pkg/datapath/loader/netlink.go (hunk 2 above)
Comment (rapour) [reply pkg/datapath/loader/netlink.go]: Thanks, done

**Comment by rapour** [comment]
The nit is addresses, thanks a lot guys

**Comment by rapour** [comment]
Is there anything I can do to unblock this PR?

**Comment by ldelossa** [comment]
@rapour We seem to be getting a persistent failure in the following CI test: https://github.com/cilium/cilium/actions/runs/14726773148/job/41429620511

Can you rebase this PR off `main` and we will perform a new run of CI tests to determine if the failure continues to exist.
