### PR TITLE
test: Fix graceful termination test flake

### LINKED ISSUE #18045: CI: K8sServicesTest Checks graceful termination of service endpoints Checks client terminates gracefully on service endpoint deletion
## CI failure

K8s 1.22, kernel 4.19 - Observed on https://github.com/cilium/cilium/pull/18011

### Test Name
```test-name
K8sServicesTest Checks graceful termination of service endpoints Checks client terminates gracefully on service endpoint deletion
```

### Failure Output

Failure on graceful termination - The pod is still running after the 30s timeout, when it is expected to terminate

```failure-output
Expected
    <string>: Running
to be identical to
    <string>: Succeeded
```

### Stacktrace
<details><summary>Click to show.</summary>

```stack-trace
/home/jenkins/workspace/Cilium-PR-K8s-1.22-kernel-4.19/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:527
Timed out after 30.001s.
Unexpected pod status 

Expected
    <string>: Running
to be identical to
    <string>: Succeeded
/home/jenkins/workspace/Cilium-PR-K8s-1.22-kernel-4.19/src/github.com/cilium/cilium/test/k8sT/Services.go:1652
```
</details>

### Standard Output
<details><summary>Click to show.</summary>

```stack-output
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 0
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
No errors/warnings found in logs
Number of "context deadline exceeded" in logs: 0
Number of "level=error" in logs: 0
Number of "level=warning" in logs: 2
Number of "Cilium API handler panicked" in logs: 0
Number of "Goroutine took lock for more than" in logs: 0
Top 1 errors/warnings:
BPF masquerade requires NodePort (--enable-node-port=\
Cilium pods: [cilium-m6drn cilium-ps57j]
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
Pod                           Ingress   Egress
grafana-5747bcc8f9-99nhp                
prometheus-655fb888d7-nrxgz             
graceful-term-client                    
testclient-fhw6v                        
testclient-kpgd7                        
coredns-755cd654d4-6w9kc                
Cilium agent 'cilium-m6drn': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 33 Failed 0
Cilium agent 'cilium-ps57j': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 34 Failed 0
Cilium pods: [cilium-m6drn cilium-ps57j]
Netpols loaded: 
CiliumNetworkPolicies loaded: 
Endpoint Policy Enforcement:
Pod                           Ingress   Egress
coredns-755cd654d4-6w9kc                
grafana-5747bcc8f9-99nhp                
prometheus-655fb888d7-nrxgz             
graceful-term-client                    
testclient-fhw6v                        
testclient-kpgd7                        
Cilium agent 'cilium-m6drn': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 33 Failed 0
Cilium agent 'cilium-ps57j': Status: Ok  Health: Ok Nodes "" ContinerRuntime:  Kubernetes: Ok KVstore: Ok Controllers: Total 34 Failed 0
```
</details>

### Standard Error
<details><summary>Click to show.</summary>

```stack-error
13:47:12 STEP: Running BeforeAll block for EntireTestsuite K8sServicesTest Checks graceful termination of service endpoints
13:47:12 STEP: Installing Cilium
13:47:14 STEP: Waiting for Cilium to become ready
13:47:23 STEP: Validating if Kubernetes DNS is deployed
13:47:23 STEP: Checking if deployment is ready
13:47:23 STEP: Checking if kube-dns service is plumbed correctly
13:47:23 STEP: Checking if DNS can resolve
13:47:23 STEP: Checking if pods have identity
13:47:24 STEP: Kubernetes DNS is up and operational
13:47:24 STEP: Validating Cilium Installation
13:47:24 STEP: Performing Cilium status preflight check
13:47:24 STEP: Performing Cilium controllers preflight check
13:47:24 STEP: Performing Cilium health check
13:47:25 STEP: Performing Cilium service preflight check
13:47:25 STEP: Performing K8s service preflight check
13:47:25 STEP: Cilium is not ready yet: connectivity health is failing: Cluster connectivity is unhealthy on 'cilium-m6drn': Exitcode: 1 
Err: exit status 1
Stdout:
 	 
Stderr:
 	 Defaulted container "cilium-agent" out of: cilium-agent, mount-cgroup (init), clean-cilium-state (init)
	 Error: Cannot get status/probe: Put "http://%2Fvar%2Frun%2Fcilium%2Fhealth.sock/v1beta/status/probe": dial unix /var/run/cilium/health.sock: connect: no such file or directory
	 
	 command terminated with exit code 1
	 

13:47:25 STEP: Performing Cilium controllers preflight check
13:47:25 STEP: Performing Cilium status preflight check
13:47:25 STEP: Performing Cilium health check
13:47:26 STEP: Performing Cilium service preflight check
13:47:26 STEP: Performing K8s service preflight check
13:47:26 STEP: Performing Cilium controllers preflight check
13:47:26 STEP: Performing Cilium health check
13:47:26 STEP: Performing Cilium status preflight check
13:47:29 STEP: Performing Cilium service preflight check
13:47:29 STEP: Performing K8s service preflight check
13:47:29 STEP: Performing Cilium controllers preflight check
13:47:29 STEP: Performing Cilium status preflight check
13:47:29 STEP: Performing Cilium health check
13:47:30 STEP: Performing Cilium service preflight check
13:47:30 STEP: Performing K8s service preflight check
13:47:30 STEP: Performing Cilium controllers preflight check
13:47:30 STEP: Performing Cilium status preflight check
13:47:30 STEP: Performing Cilium health check
13:47:31 STEP: Performing Cilium service preflight check
13:47:31 STEP: Performing K8s service preflight check
13:47:33 STEP: Waiting for cilium-operator to be ready
13:47:33 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator")
13:47:33 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator") => <nil>
13:47:33 STEP: Running BeforeEach block for EntireTestsuite K8sServicesTest Checks graceful termination of service endpoints
13:47:33 STEP: WaitforPods(namespace="default", filter="-l app=graceful-term-server")
13:47:37 STEP: WaitforPods(namespace="default", filter="-l app=graceful-term-server") => <nil>
13:47:38 STEP: WaitforPods(namespace="default", filter="-l app=graceful-term-client")
13:47:38 STEP: WaitforPods(namespace="default", filter="-l app=graceful-term-client") => <nil>
13:47:43 STEP: Deleting service endpoint pod app=graceful-term-server
13:47:43 STEP: Waiting until server is terminating
13:47:44 STEP: Checking if client pod terminated successfully
FAIL: Timed out after 30.001s.
Unexpected pod status 

Expected
    <string>: Running
to be identical to
    <string>: Succeeded
=== Test Finished at 2021-11-29T13:48:14Z====
13:48:14 STEP: Running JustAfterEach block for EntireTestsuite K8sServicesTest
===================== TEST FAILED =====================
13:48:15 STEP: Running AfterFailed block for EntireTestsuite K8sServicesTest Checks graceful termination of service endpoints
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE           NAME                              READY   STATUS    RESTARTS      AGE   IP              NODE   NOMINATED NODE   READINESS GATES
	 cilium-monitoring   grafana-5747bcc8f9-99nhp          1/1     Running   0             60m   10.0.0.62       k8s1   <none>           <none>
	 cilium-monitoring   prometheus-655fb888d7-nrxgz       1/1     Running   0             60m   10.0.0.132      k8s1   <none>           <none>
	 default             graceful-term-client              1/1     Running   1 (33s ago)   44s   10.0.1.191      k8s2   <none>           <none>
	 default             testclient-fhw6v                  1/1     Running   0             44s   10.0.0.226      k8s1   <none>           <none>
	 default             testclient-kpgd7                  1/1     Running   0             44s   10.0.1.62       k8s2   <none>           <none>
	 kube-system         cilium-m6drn                      1/1     Running   0             63s   192.168.56.12   k8s2   <none>           <none>
	 kube-system         cilium-operator-59c8fdbf5-cprfs   1/1     Running   0             63s   192.168.56.12   k8s2   <none>           <none>
	 kube-system         cilium-operator-59c8fdbf5-vzg7f   1/1     Running   0             63s   192.168.56.11   k8s1   <none>           <none>
	 kube-system         cilium-ps57j                      1/1     Running   0             63s   192.168.56.11   k8s1   <none>           <none>
	 kube-system         coredns-755cd654d4-6w9kc          1/1     Running   0             31m   10.0.1.24       k8s2   <none>           <none>
	 kube-system         etcd-k8s1                         1/1     Running   0             63m   192.168.56.11   k8s1   <none>           <none>
	 kube-system         kube-apiserver-k8s1               1/1     Running   0             63m   192.168.56.11   k8s1   <none>           <none>
	 kube-system         kube-controller-manager-k8s1      1/1     Running   0             63m   192.168.56.11   k8s1   <none>           <none>
	 kube-system         kube-proxy-ms7j7                  1/1     Running   0             61m   192.168.56.12   k8s2   <none>           <none>
	 kube-system         kube-proxy-zc4nn                  1/1     Running   0             63m   192.168.56.11   k8s1   <none>           <none>
	 kube-system         kube-scheduler-k8s1               1/1     Running   0             63m   192.168.56.11   k8s1   <none>           <none>
	 kube-system         log-gatherer-cvml8                1/1     Running   0             61m   192.168.56.12   k8s2   <none>           <none>
	 kube-system         log-gatherer-hkgb8                1/1     Running   0             61m   192.168.56.11   k8s1   <none>           <none>
	 kube-system         registry-adder-fjbq4              1/1     Running   0             61m   192.168.56.11   k8s1   <none>           <none>
	 kube-system         registry-adder-gfk6w              1/1     Running   0             61m   192.168.56.12   k8s2   <none>           <none>
	 
Stderr:
 	 

Fetching command output from pods [cilium-m6drn cilium-ps57j]
cmd: kubectl exec -n kube-system cilium-m6drn -c cilium-agent -- cilium service list
Exitcode: 0 
Stdout:
 	 ID   Frontend              Service Type   Backend                   
	 1    10.96.0.1:443         ClusterIP      1 => 192.168.56.11:6443   
	 2    10.96.0.10:53         ClusterIP      1 => 10.0.1.24:53         
	 3    10.96.0.10:9153       ClusterIP      1 => 10.0.1.24:9153       
	 4    10.110.39.84:3000     ClusterIP      1 => 10.0.0.62:3000       
	 5    10.110.35.102:9090    ClusterIP      1 => 10.0.0.132:9090      
	 6    10.108.148.105:8081   ClusterIP                                
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-m6drn -c cilium-agent -- cilium bpf lb list
Exitcode: 0 
Stdout:
 	 SERVICE ADDRESS       BACKEND ADDRESS
	 10.96.0.10:9153       10.0.1.24:9153 (3)                        
	                       0.0.0.0:0 (3) [ClusterIP, non-routable]   
	 10.96.0.10:53         10.0.1.24:53 (2)                          
	                       0.0.0.0:0 (2) [ClusterIP, non-routable]   
	 10.110.39.84:3000     0.0.0.0:0 (4) [ClusterIP, non-routable]   
	                       10.0.0.62:3000 (4)                        
	 10.110.35.102:9090    10.0.0.132:9090 (5)                       
	                       0.0.0.0:0 (5) [ClusterIP, non-routable]   
	 10.108.148.105:8081   0.0.0.0:0 (6) [ClusterIP, non-routable]   
	 10.96.0.1:443         192.168.56.11:6443 (1)                    
	                       0.0.0.0:0 (1) [ClusterIP, non-routable]   
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-ps57j -c cilium-agent -- cilium service list
Exitcode: 0 
Stdout:
 	 ID   Frontend              Service Type   Backend                   
	 1    10.96.0.1:443         ClusterIP      1 => 192.168.56.11:6443   
	 2    10.96.0.10:9153       ClusterIP      1 => 10.0.1.24:9153       
	 3    10.96.0.10:53         ClusterIP      1 => 10.0.1.24:53         
	 4    10.110.39.84:3000     ClusterIP      1 => 10.0.0.62:3000       
	 5    10.110.35.102:9090    ClusterIP      1 => 10.0.0.132:9090      
	 6    10.108.148.105:8081   ClusterIP                                
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-ps57j -c cilium-agent -- cilium bpf lb list
Exitcode: 0 
Stdout:
 	 SERVICE ADDRESS       BACKEND ADDRESS
	 10.96.0.10:53         10.0.1.24:53 (3)                          
	                       0.0.0.0:0 (3) [ClusterIP, non-routable]   
	 10.110.35.102:9090    0.0.0.0:0 (5) [ClusterIP, non-routable]   
	                       10.0.0.132:9090 (5)                       
	 10.108.148.105:8081   0.0.0.0:0 (6) [ClusterIP, non-routable]   
	 10.110.39.84:3000     0.0.0.0:0 (4) [ClusterIP, non-routable]   
	                       10.0.0.62:3000 (4)                        
	 10.96.0.10:9153       0.0.0.0:0 (2) [ClusterIP, non-routable]   
	                       10.0.1.24:9153 (2)                        
	 10.96.0.1:443         192.168.56.11:6443 (1)                    
	                       0.0.0.0:0 (1) [ClusterIP, non-routable]   
	 
Stderr:
 	 

===================== Exiting AfterFailed =====================
===================== TEST FAILED =====================
13:48:28 STEP: Running AfterFailed block for EntireTestsuite K8sServicesTest
cmd: kubectl get pods -o wide --all-namespaces
Exitcode: 0 
Stdout:
 	 NAMESPACE           NAME                              READY   STATUS    RESTARTS      AGE   IP              NODE   NOMINATED NODE   READINESS GATES
	 cilium-monitoring   grafana-5747bcc8f9-99nhp          1/1     Running   0             61m   10.0.0.62       k8s1   <none>           <none>
	 cilium-monitoring   prometheus-655fb888d7-nrxgz       1/1     Running   0             61m   10.0.0.132      k8s1   <none>           <none>
	 default             graceful-term-client              1/1     Running   1 (45s ago)   56s   10.0.1.191      k8s2   <none>           <none>
	 default             testclient-fhw6v                  1/1     Running   0             56s   10.0.0.226      k8s1   <none>           <none>
	 default             testclient-kpgd7                  1/1     Running   0             56s   10.0.1.62       k8s2   <none>           <none>
	 kube-system         cilium-m6drn                      1/1     Running   0             75s   192.168.56.12   k8s2   <none>           <none>
	 kube-system         cilium-operator-59c8fdbf5-cprfs   1/1     Running   0             75s   192.168.56.12   k8s2   <none>           <none>
	 kube-system         cilium-operator-59c8fdbf5-vzg7f   1/1     Running   0             75s   192.168.56.11   k8s1   <none>           <none>
	 kube-system         cilium-ps57j                      1/1     Running   0             75s   192.168.56.11   k8s1   <none>           <none>
	 kube-system         coredns-755cd654d4-6w9kc          1/1     Running   0             31m   10.0.1.24       k8s2   <none>           <none>
	 kube-system         etcd-k8s1                         1/1     Running   0             63m   192.168.56.11   k8s1   <none>           <none>
	 kube-system         kube-apiserver-k8s1               1/1     Running   0             63m   192.168.56.11   k8s1   <none>           <none>
	 kube-system         kube-controller-manager-k8s1      1/1     Running   0             63m   192.168.56.11   k8s1   <none>           <none>
	 kube-system         kube-proxy-ms7j7                  1/1     Running   0             62m   192.168.56.12   k8s2   <none>           <none>
	 kube-system         kube-proxy-zc4nn                  1/1     Running   0             63m   192.168.56.11   k8s1   <none>           <none>
	 kube-system         kube-scheduler-k8s1               1/1     Running   0             63m   192.168.56.11   k8s1   <none>           <none>
	 kube-system         log-gatherer-cvml8                1/1     Running   0             61m   192.168.56.12   k8s2   <none>           <none>
	 kube-system         log-gatherer-hkgb8                1/1     Running   0             61m   192.168.56.11   k8s1   <none>           <none>
	 kube-system         registry-adder-fjbq4              1/1     Running   0             61m   192.168.56.11   k8s1   <none>           <none>
	 kube-system         registry-adder-gfk6w              1/1     Running   0             61m   192.168.56.12   k8s2   <none>           <none>
	 
Stderr:
 	 

Fetching command output from pods [cilium-m6drn cilium-ps57j]
cmd: kubectl exec -n kube-system cilium-m6drn -c cilium-agent -- cilium service list
Exitcode: 0 
Stdout:
 	 ID   Frontend              Service Type   Backend                   
	 1    10.96.0.1:443         ClusterIP      1 => 192.168.56.11:6443   
	 2    10.96.0.10:53         ClusterIP      1 => 10.0.1.24:53         
	 3    10.96.0.10:9153       ClusterIP      1 => 10.0.1.24:9153       
	 4    10.110.39.84:3000     ClusterIP      1 => 10.0.0.62:3000       
	 5    10.110.35.102:9090    ClusterIP      1 => 10.0.0.132:9090      
	 6    10.108.148.105:8081   ClusterIP                                
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-m6drn -c cilium-agent -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                                  IPv6        IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                                        
	 556        Disabled           Disabled          13272      k8s:app=graceful-term-client                                                 fd02::168   10.0.1.191   ready   
	                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default                                        
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                      
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                               
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                       
	 862        Disabled           Disabled          19433      k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default       fd02::1cf   10.0.1.62    ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                      
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                               
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                       
	                                                            k8s:zgroup=testDSClient                                                                                       
	 1004       Disabled           Disabled          3636       k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=kube-system   fd02::14c   10.0.1.24    ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                      
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=coredns                                                               
	                                                            k8s:io.kubernetes.pod.namespace=kube-system                                                                   
	                                                            k8s:k8s-app=kube-dns                                                                                          
	 1056       Disabled           Disabled          4          reserved:health                                                              fd02::16a   10.0.1.108   ready   
	 1944       Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s2                                                                            ready   
	                                                            reserved:host                                                                                                 
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-ps57j -c cilium-agent -- cilium service list
Exitcode: 0 
Stdout:
 	 ID   Frontend              Service Type   Backend                   
	 1    10.96.0.1:443         ClusterIP      1 => 192.168.56.11:6443   
	 2    10.96.0.10:9153       ClusterIP      1 => 10.0.1.24:9153       
	 3    10.96.0.10:53         ClusterIP      1 => 10.0.1.24:53         
	 4    10.110.39.84:3000     ClusterIP      1 => 10.0.0.62:3000       
	 5    10.110.35.102:9090    ClusterIP      1 => 10.0.0.132:9090      
	 6    10.108.148.105:8081   ClusterIP                                
	 
Stderr:
 	 

cmd: kubectl exec -n kube-system cilium-ps57j -c cilium-agent -- cilium endpoint list
Exitcode: 0 
Stdout:
 	 ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])                                                        IPv6       IPv4         STATUS   
	            ENFORCEMENT        ENFORCEMENT                                                                                                                             
	 690        Disabled           Disabled          19433      k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=default             fd02::c5   10.0.0.226   ready   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                           
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                    
	                                                            k8s:io.kubernetes.pod.namespace=default                                                                            
	                                                            k8s:zgroup=testDSClient                                                                                            
	 793        Disabled           Disabled          36874      k8s:app=prometheus                                                                 fd02::77   10.0.0.132   ready   
	                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=cilium-monitoring                                   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                           
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=prometheus-k8s                                                             
	                                                            k8s:io.kubernetes.pod.namespace=cilium-monitoring                                                                  
	 2636       Disabled           Disabled          4          reserved:health                                                                    fd02::18   10.0.0.42    ready   
	 3121       Disabled           Disabled          1          k8s:cilium.io/ci-node=k8s1                                                                                 ready   
	                                                            k8s:node-role.kubernetes.io/control-plane                                                                          
	                                                            k8s:node-role.kubernetes.io/master                                                                                 
	                                                            k8s:node.kubernetes.io/exclude-from-external-load-balancers                                                        
	                                                            reserved:host                                                                                                      
	 3498       Disabled           Disabled          2968       k8s:app=grafana                                                                    fd02::53   10.0.0.62    ready   
	                                                            k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=cilium-monitoring                                   
	                                                            k8s:io.cilium.k8s.policy.cluster=default                                                                           
	                                                            k8s:io.cilium.k8s.policy.serviceaccount=default                                                                    
	                                                            k8s:io.kubernetes.pod.namespace=cilium-monitoring                                                                  
	 
Stderr:
 	 

===================== Exiting AfterFailed =====================
13:48:41 STEP: Running AfterEach for block EntireTestsuite K8sServicesTest
13:48:41 STEP: Running AfterEach for block EntireTestsuite
```
</details>

### Resources

- [ZIP link](https://github.com/cilium/cilium/files/7619387/d4ccd0d7_K8sServicesTest_Checks_graceful_termination_of_service_endpoints_Checks_client_terminates_gracefully_on_service_endpoint_deletion.zip)
- [Jenkins URL](https://jenkins.cilium.io/job/Cilium-PR-K8s-1.22-kernel-4.19/18/testReport/junit/Suite-k8s-1/22/K8sServicesTest_Checks_graceful_termination_of_service_endpoints_Checks_client_terminates_gracefully_on_service_endpoint_deletion/)

### PR DESCRIPTION
**Pull request by aditighag**
The graceful termination test apps [1] are updated to fix a flake. Specifically, added read and write deadlines while making socket calls on the server side. This way the server doesn't block on the socket calls when `SIGTERM` event is received on termination.

While at it, also updated the test logic to validate that connectivity between client and server is intact at least for the configured `terminationGracePeriodInSeconds` duration.

Ran the test locally a few times, and it passed every time. 

[1] https://github.com/cilium/graceful-termination-test-apps

Signed-off-by: Aditi Ghag <aditi@cilium.io>

Fixes: https://github.com/cilium/cilium/issues/18045

### CODE REVIEW

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.Checks graceful termination of service endpoints" --k8s_version=1.22 --kernel_version="419"

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.Checks graceful termination of service endpoints" --k8s_version=1.22 --kernel_version="419"

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.Checks graceful termination of service endpoints" --k8s_version=1.22 --kernel_version="419"

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.Checks graceful termination of service endpoints" --k8s_version=1.22 --kernel_version="419"

**Comment by aditighag** [comment]
4/4 Jenkins runs passed.

**Comment by aditighag** [comment]
test-1.22-4.19

**Review by brb — APPROVED** [review]
:rocket:

**Comment by aditighag** [comment]
test-1.22-4.19

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.*" --k8s_version=1.22 --kernel_version="419"

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.*" --k8s_version=1.22 --kernel_version="419"

**Comment by joestringer** [comment]
FYI the failing test `K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with direct routing Tests NodePort` should now be quarantined based on #18051 due to the high incidence of recent failures in the tree. You would need to rebase to pick up the quarantining of that test.

File: test/k8sT/Services.go [hunk 1]
```diff
@@ -1642,14 +1642,27 @@ Secondary Interface %s :: IPv4: (%s, %s), IPv6: (%s, %s)`, helpers.DualStackSupp
...
 			terminateServiceEndpointPod()
 
+			By("Checking if client pod terminated gracefully")
+			ctx, cancel = context.WithCancel(context.Background())
+			res = kubectl.LogsStream(helpers.DefaultNamespace, clientPod, ctx)
+			// The log message indicates that the connectivity between client and
+			// server was intact even after the service endpoint pod was terminated,
+			// and that the client connection terminated gracefully.
+			Expect(res.WaitUntilMatch("exiting on graceful termination")).To(BeNil(),
+				"%s is not in the output after timeout", res.GetStdOut())
```
Comment (christarazi) [inline test/k8sT/Services.go]: Typically, `Eventually` should be used over `WaitUntilMatch`. I imagine the latter was added due to lack of knowledge of the former.

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.*" --k8s_version=1.22 --kernel_version="419"

File: test/k8sT/Services.go (hunk 1 above)
Comment (aditighag) [reply test/k8sT/Services.go]: >// WaitUntilMatch waits until the given substring is present in the `CmdRes.stdout`
>// If the timeout is reached it will return an error.

The helper is a special case of `Eventually` (although it uses a different function than `Eventually` underneath) as it operates on `CmdRes*` (output of the command run in the background). If we were to use eventually, we'll need to replicate the parts of `WaitUntilMatch` anyway?

**Comment by aditighag** [comment]
The latest push only contains the reverted commit that quarantined the test (this PR fixes the test).

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.*" --k8s_version=1.22 --kernel_version="419"

**Comment by pchaigno** [comment]
@cilium/ci-structure wasn't covered with an approving review. I'll review now.

File: test/k8sT/Services.go [hunk 2]
```diff
@@ -1552,7 +1552,7 @@ Secondary Interface %s :: IPv4: (%s, %s), IPv6: (%s, %s)`, helpers.DualStackSupp
 	SkipContextIf(func() bool {
 		// The graceful termination feature depends on enabling an alpha feature
 		// EndpointSliceTerminatingCondition in Kubernetes.
-		return helpers.SkipK8sVersions("<1.20.0") || helpers.RunsOnGKE() || helpers.RunsOnEKS() || helpers.SkipQuarantined()
+		return helpers.SkipK8sVersions("<1.20.0") || helpers.RunsOnGKE() || helpers.RunsOnEKS()
```
Comment (pchaigno) [inline test/k8sT/Services.go:1555]: Can we wait for 10 runs in CI before removing from quarantine as discussed in https://github.com/cilium/cilium/pull/18051#issuecomment-982429496 and https://github.com/cilium/cilium/pull/18051#issuecomment-982904054?

File: test/k8sT/Services.go (hunk 1 above)
Comment (pchaigno) [reply test/k8sT/Services.go]: AFAIU, `Eventually` could be used with just:
```go
Eventually(func() bool {
    return strings.Contains(res.OutputPrettyPrint(), "exiting on graceful termination")
}, helpers.HelperTimeout, time.Second).Should(BeTrue(), "%s is not in the output after timeout", res.GetStdOut())
```
That said, I'm not clear why `Eventually` would be preferred here. @christarazi What's the reason?

Comment (pchaigno) [inline test/k8sT/Services.go]: On a different topic, I think the error message is incorrect here. It will end up being:
```
[pod logs...] is not in the output after timeout
```
Did you mean for the error message to be something like follows?
```
'exiting on graceful termination' not found in logs after timeout: [pod logs...]
```

**Review by pchaigno — CHANGES_REQUESTED** [review]
The test improvement looks good to me with just one nit on error message. As per the previous discussions, I however think we should remove the second commit for now.

File: test/k8sT/Services.go (hunk 2 above)
Comment (aditighag) [reply test/k8sT/Services.go:1555]: We already have 9 runs on this PR. I'll trigger one more after I address your comment below.

File: test/k8sT/Services.go (hunk 1 above)
Comment (christarazi) [reply test/k8sT/Services.go]: The reason is so that we can remove cruft from our Ginkgo test suite over time. If we remove all references to `WaitUntilMatch`, then we can remove it and use the native functions, rather than maintaining our own. :slightly_smiling_face: 

To be clear, I'm not suggesting we remove all references, but at least we should avoid adding new ones.

Comment (aditighag) [reply test/k8sT/Services.go]: Fixed.

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.*" --k8s_version=1.22 --kernel_version="419"

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.*" --k8s_version=1.22 --kernel_version="419"

**Comment by aditighag** [comment]
test-only --focus="K8sServicesTest.*" --k8s_version=1.23 --kernel_version="49"

**Review by pchaigno — APPROVED** [review]
