### PR TITLE
The invocation of CiliumIdentity changes is triggered after a random delay when modifying the namespace label.

### LINKED ISSUE #38030: High-Scale: Modifying the ns label may cause the apiserver to crash.
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.1 and lower than v1.18.0

### What happened?

In a cluster of nearly 3,000 nodes, when we modified the label of a namespace(there is about 20000 pod and 5000+ ciliumidentity in this namespace), a large amount of CiliumIdentity and CIliumEndpoint traffic was generated instantly, causing the apiserver to crash.
  
1. Currently, in clusters where Cilium is deployed, changing the namespace label will instantly generate a number of ciliumidentity when the namespace have many pod who's label is different.
2. After these ciliumidentity events are pushed to the API server, they are fully distributed to each node.
3. These ciliumidentity changes will result in a large number of ciliumendpoint update events.
Therefore, when there are many pods who's lable is different in a namespace and the cluster has a large number of nodes, changing the namespace label can easily cause significant pressure on the API server and, under extreme circumstances, may lead to the API server crashing.

### How can we reproduce the issue?

1. The cluster has as many nodes as possible.
2. Place as many different label pods as possible in a namespace.
When modifying the namespace label, the impact of traffic on the apiserver is proportional to the results of the above two factors.

### Cilium Version

We use v1.13.11, but all the version have the same problem.

### Kernel Version

5.10

### Kubernetes Version

v1.30

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by orange30**
Currently, in clusters where Cilium is deployed, changing the namespace label will instantly generate a number of ciliumidentity when the namespace have many pod who's label is different.
After these ciliumidentity events are pushed to the API server, they are fully distributed to each node.
These ciliumidentity changes will result in a large number of ciliumendpoint update events.
Therefore, when there are many pods who's lable is different in a namespace and the cluster has a large number of nodes, changing the namespace label can easily cause significant pressure on the API server and, under extreme circumstances, may lead to the API server crashing.

1. In this patch, when modifying the namespace label, we delay the invocation of the CiliumIdentity change event by a random amount of time to alleviate pressure on the API server.
2. The maximum delay time can be configured via the cilium-config ConfigMap.
3. Modifying the namespace label is a relatively infrequent operation, so we believe that a delay should be acceptable in most cases.

Please ensure your pull request adheres to the following guidelines:

- [ ] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [ ] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [ ] Thanks for contributing!

Fixes: #38030

```release-note
A new option `--identity-max-jitter` adds a random delay to when Cilium reacts to namespace label updates. This jitter is intended to improve kube-apiserver resource usage at high scale.
```

### CODE REVIEW

File: pkg/k8s/watchers/namespace.go [hunk 1]
```diff
@@ -122,6 +125,13 @@ func getNamespaceLabels(ns *slim_corev1.Namespace) labels.Labels {
 	return labels.Map2Labels(labelMap, labels.LabelSourceK8s)
 }
 
+// randomDuration 在 0 到 maxDuration 之间生成一个随机的 time.Duration
```
Comment (squeed) [inline pkg/k8s/watchers/namespace.go]: nit: please comment in English :-)

File: pkg/controller/controller.go [hunk 2]
```diff
@@ -105,6 +105,8 @@ type ControllerParams struct {
 	NoErrorRetry bool
 
 	Context context.Context
+
+	DelayUpdate time.Duration
```
Comment (squeed) [inline pkg/controller/controller.go]: Suggestion: call this jitter? And do please add a docblock describing the purpose.

File: pkg/controller/manager.go [hunk 3]
```diff
@@ -108,7 +121,17 @@ func (m *Manager) createControllerLocked(name string, params ControllerParams) *
...
 
-	go ctrl.runController(ctrl.params)
+	// Notify the goroutine of the params update.
+	if params.DelayUpdate == 0 {
+		select {
+		case ctrl.update <- ctrl.params:
+		default:
+		}
+	} else {
+		go delayUpdate(ctrl, params)
```
Comment (joestringer) [inline pkg/controller/manager.go]: What happens if another update arrives during the delay? I think this could revert another change that was already applied?

File: pkg/controller/manager.go [hunk 4]
```diff
@@ -52,6 +52,15 @@ func (m *Manager) UpdateController(name string, params ControllerParams) {
 	m.updateController(name, params)
 }
 
+func delayUpdate(ctrl *managedController, params ControllerParams) {
```
Comment (joestringer) [inline pkg/controller/manager.go]: In the current code, controller updates occur while holding `m.mutex`, but the goroutine doesn't make the change under the mutex. We should probably be consistent about how the changes are applied.

File: pkg/controller/controller.go [hunk 5]
```diff
@@ -239,93 +241,100 @@ func (c *controller) GetLastErrorTimestamp() time.Time {
 	return c.lastErrorStamp
 }
 
-func (c *controller) runController(params ControllerParams) {
+func (c *controller) runController() {
+	var params ControllerParams
 	errorRetries := 1
+	runFunc := false
+	interval := 10 * time.Minute
```
Comment (joestringer) [inline pkg/controller/controller.go]: Why does this need to start at 10 minutes?

File: pkg/controller/controller.go [hunk 6]
```diff
@@ -239,93 +241,100 @@ func (c *controller) GetLastErrorTimestamp() time.Time {
...
-		c.lastDuration = duration
-		c.getLogger().Debug("Controller func execution time: ", c.lastDuration)
-
-		if err != nil {
-			if params.Context.Err() != nil {
-				// The controller's context was canceled. Let's wait for the
-				// next controller update (or stop).
-				err = NewExitReason("controller context canceled")
-			}
+		if runFunc && params.DoFunc != nil {
```
Comment (joestringer) [inline pkg/controller/controller.go]: Why would `DoFunc` be nil?

What I would be concerned about here is if the code silently stops running a controller because some code unintentionally cleared the DoFunc. If we are going to check for this condition, it should probably instead record a special error to indicate this condition. Alternatively, don't check for this.

File: pkg/controller/controller.go [hunk 7]
```diff
@@ -239,93 +241,100 @@ func (c *controller) GetLastErrorTimestamp() time.Time {
...
 
 		select {
 		case <-c.stop:
 			goto shutdown
 
 		case params = <-c.update:
 			// update channel is never closed
+			runFunc = true
 		case <-stdtime.After(interval):
 			// timer channel is not yet closed
```
Comment (joestringer) [inline pkg/controller/controller.go]: Should the `stdtime.After(...)` case also set runFunc?

File: pkg/controller/manager.go [hunk 8]
```diff
@@ -52,6 +52,15 @@ func (m *Manager) UpdateController(name string, params ControllerParams) {
...
+	select {
+	case <-time.After(params.DelayUpdate):
+		ctrl.update <- params
+	case <-ctrl.terminated:
```
Comment (joestringer) [inline pkg/controller/manager.go]: nit: The first line here could block, should there be another `select {}` statement to handle the `<-ctrl.terminated` case after the delay?

File: pkg/defaults/defaults.go [hunk 9]
```diff
@@ -166,6 +166,9 @@ const (
 	// option.IdentityChangeGracePeriod
 	IdentityChangeGracePeriod = 5 * time.Second
 
+	// Delay interval of CiliumIdentidy after Namespace lable changed..
```
Comment (joestringer) [inline pkg/defaults/defaults.go]: nit: 
```suggestion
	// Delay to change CiliumIdentity after Namespace label changed.
```

File: daemon/cmd/daemon_main.go [hunk 10]
```diff
@@ -445,6 +445,9 @@ func InitGlobalFlags(cmd *cobra.Command, vp *viper.Viper) {
 	flags.Duration(option.IdentityChangeGracePeriod, defaults.IdentityChangeGracePeriod, "Time to wait before using new identity on endpoint identity change")
 	option.BindEnv(vp, option.IdentityChangeGracePeriod)
 
+	flags.Duration(option.DelayCIdentityOfNsLabelChange, 30*time.Second, "Delay interval of CiliumIdentidy after Namespace lable changed.")
```
Comment (joestringer) [inline daemon/cmd/daemon_main.go]:
```suggestion
	flags.Duration(option.DelayCIdentityOfNsLabelChange, defaults.DelayCIdentityOfNsLabelChange, "Randomly delay CiliumIdentity updates for Endpoints by up to this time after Namespace labels change")
```

File: pkg/option/config.go [hunk 11]
```diff
@@ -1799,6 +1802,9 @@ type DaemonConfig struct {
 	// to whitelist the new upcoming identity of the endpoint.
 	IdentityChangeGracePeriod time.Duration
 
+	// Delay interval of CiliumIdentidy after Namespace lable changed..
```
Comment (joestringer) [inline pkg/option/config.go]:
```suggestion
	// Delay to change CiliumIdentity after Namespace label changed.
```

File: pkg/controller/controller.go [hunk 12]
```diff
@@ -239,93 +241,100 @@ func (c *controller) GetLastErrorTimestamp() time.Time {
 	return c.lastErrorStamp
 }
 
-func (c *controller) runController(params ControllerParams) {
+func (c *controller) runController() {
+	var params ControllerParams
 	errorRetries := 1
+	runFunc := false
+	interval := 10 * time.Minute
```
Comment (joestringer) [inline pkg/controller/controller.go]: nit: If the intent is to wait for the first trigger / params update, maybe instead of changing the loop the code should just wait for that update here?

```suggestion
	select {
		case <-c.stop:
			goto shutdown

		case params = <-c.update:
			// update channel is never closed
			runFunc = true
		case <-stdtime.After(interval):
			// timer channel is not yet closed
		case <-c.trigger:
			// trigger channel is never closed
			runFunc = true
	}
```

But wait, then the flaw is revealed: if `c.trigger()` happens first then `params` is empty, which is unacceptable. This also needs fixing.

**Review by joestringer — CHANGES_REQUESTED** [review]

File: pkg/controller/controller.go (hunk 7 above)
Comment (joestringer) [reply pkg/controller/controller.go]: See the danger here: https://github.com/cilium/cilium/pull/38031#discussion_r1989678322

If this also sets runFunc then `params` might be empty.

File: pkg/controller/controller.go (hunk 6 above)
Comment (joestringer) [reply pkg/controller/controller.go]: This seems related to the comment below: https://github.com/cilium/cilium/pull/38031#discussion_r1989678322 . That is, params.DoFunc might be nil because the controller was triggered before the params were received.

I think it should be possible to write this in a way that the controller has the parameters first before running so that this code doesn't have to check for the `params.DoFunc != nil`.

File: pkg/controller/manager.go (hunk 3 above)
Comment (orange30) [reply pkg/controller/manager.go]: For the case runIdentityResolver->func (e *Endpoint) identityLabelsChanged(ctx context.Context) :
If the second random delay is smaller then the first  random delay, then the second identityLabelsChanged will be executed earlier.  When the first identityLabelsChanged is called, it will returned for obsolete identity revision.

         myChangeRev := e.identityRevision; 
        // Since we unlocked the endpoint and re-locked, the label update may already be obsolete
	if e.identityResolutionIsObsolete(myChangeRev) {
		e.unlock()
		elog.Debug("Endpoint identity has changed, aborting resolution routine in favour of new one")
		return false, nil
	}

File: pkg/controller/manager.go (hunk 8 above)
Comment (orange30) [reply pkg/controller/manager.go]: This select is not in the loop，I think we donot need another select {} statement to handle the <-ctrl.terminated. 
What we expect is that:
time.After or ctrl.terminated: the one that returns first will be executed, otherwise it should be blocked here.

File: pkg/controller/manager.go (hunk 4 above)
Comment (orange30) [reply pkg/controller/manager.go]: I will fix it.

File: pkg/controller/controller.go (hunk 7 above)
Comment (orange30) [reply pkg/controller/controller.go]: > Should the `stdtime.After(...)` case also set runFunc?

Only update and trigger should set runFunc to be true.
"update" mean that "params" has been setted correctly, controller should execute the params.DoFunc now.

"trigger" mean it shoud exectued immediately:
(1) If "update" has been executed before, “params” should have been configured correctly, for example params.DoFunc will be setted correctly.
(2) "params" is a local variable in this function and will never be nil.
(3) If "update" has not been executed before, (here we introduced delay, this situation is possible), we need to be compatible with the situation where params is not set correctly( in this case : before "update" is called, params.DoFunc will always be nil.)

I think the introduction of "stdtime.After(interval)" is more to make the controller compatible with the situation where params.DoFunc is executed periodically.
(1) For the situation where "controller does not need to be executed periodically", params.RunInterval can be left unset or set to 0.
    // If no run interval is specified, no further updates
    // are required.
    if interval == time.Duration(0) {
        // Don't exit the goroutine, since that only happens when the
        // controller is explicitly stopped. Instead, just wait for
        // the next update. 
        c.getLogger().Debug("Controller run succeeded; waiting for next controller update or stop")
        interval = time.Duration(math.MaxInt64)
    }
(2) For the situation where "controller needs to be executed periodically", params.RunInterval needs to be set to a non-zero value. Even in this case, params.DoFunc should be called during the "update" event.

File: pkg/controller/controller.go (hunk 6 above)
Comment (orange30) [reply pkg/controller/controller.go]: > that the controller has the parameter

I will add a log to record the special error.

Comment (orange30) [reply pkg/controller/controller.go]: > This seems related to the comment below: [#38031 (comment)](https://github.com/cilium/cilium/pull/38031#discussion_r1989678322) . That is, params.DoFunc might be nil because the controller was triggered before the params were received.

yes.

> I think it should be possible to write this in a way that the controller has the parameters first before running so that this code doesn't have to check for the `params.DoFunc != nil`.

Here we introduce the delay,  i think we can not ensure the triggered is after the "update".

File: pkg/controller/controller.go (hunk 5 above)
Comment (orange30) [reply pkg/controller/controller.go]: https://github.com/cilium/cilium/pull/38031/files#r1991017071
As we analyzed in this link, interval is only meaningful after the "update" event is executed.
I think it might be more reasonable to initially set interval to time.Duration(math.MaxInt64); because before "update" is called, after "stdtime.After(interval)" return， it does nothing meaningful。 In the processing of the "update" event, the initial interval will be overwritten by params.RunInterval.

File: pkg/controller/controller.go (hunk 2 above)
Comment (orange30) [reply pkg/controller/controller.go]: I think the exact meaning of this parameter is：
“// The interval for which this update needs to be delayed”

So, for this parameter name, between "jitter" and "delay", I think maybe we shold use "delay" better.

File: pkg/controller/controller.go (hunk 12 above)
Comment (orange30) [reply pkg/controller/controller.go]: "params" is a local variable in this function and will never be nil.
https://github.com/cilium/cilium/pull/38031/files#r1991017071

File: pkg/k8s/watchers/namespace.go (hunk 1 above)
Comment (orange30) [reply pkg/k8s/watchers/namespace.go]: I will fix it.

File: pkg/controller/controller.go (hunk 12 above)
Comment (joestringer) [reply pkg/controller/controller.go]: Sorry, I misspoke. I meant the variable would be uninitialized rather than nil. My point is that we should not be using the values from an uninitialized structure.

File: pkg/controller/controller.go (hunk 6 above)
Comment (joestringer) [reply pkg/controller/controller.go]: I think we should enforce that `params.DoFunc` is never nil. Why is it nil?

File: pkg/controller/controller.go (hunk 7 above)
Comment (joestringer) [reply pkg/controller/controller.go]: > (3) If "update" has not been executed before, (here we introduced delay, this situation is possible), we need to be compatible with the situation where params is not set correctly( in this case : before "update" is called, params.DoFunc will always be nil.)

I'm suggesting that we don't allow this order of operations. The controller is declared with parameters, so those parameters should be available right from the initial declaration. It doesn't make sense to run a controller without using its parameters.

Comment (joestringer) [reply pkg/controller/controller.go]: Strictly speaking, we do not need to enable this boolean in the `stdtime.After(interval)` case. I think that if we ensure that the parameters are available right from the start, we won't need to make that change and we won't need the `runFunc` bool at all either.

File: pkg/controller/manager.go (hunk 8 above)
Comment (joestringer) [reply pkg/controller/manager.go]: Consider this case: `After()` was called and the goroutine made no progress for some undefined amount of time before proceeding to execute the `ctrl.update <- params` line. 
The `runController()` code that receives from that channel could have received `<-c.stop` immediately before the `After()` returns, then `runController()` proceeds to call into `params.StopFunc(...)` but not yet called `close(c.terminated)`. In this case, this goroutine would be stuck on `ctrl.update <- params` forever because the goroutine which normally reads from that channel will never read from it again.

File: pkg/controller/controller.go (hunk 7 above)
Comment (orange30) [reply pkg/controller/controller.go:335]: > I'm suggesting that we don't allow this order of operations. The controller is declared with parameters, so those parameters should be available right from the initial declaration. It doesn't make sense to run a controller without using its parameters.

1. For users who use controllers, they only need to call (m *Manager) UpdateController(name string, params ControllerParams) directly. After introducing delay to the controller: if delay is required, just set params.DelayUpdate to a non-zero value when calling.
2. Consider the case where the user calls UpdateController for the first time and sets params.DelayUpdate to a non-zero value. At this time, runController will be called through UpdateController->updateController->createControllerLocked. Note that the requirement for runController at this time is to run the related loop and take into account the delay processing (although parms is set, it does not need to be executed immediately)

Comment (orange30) [reply pkg/controller/controller.go:335]: > 2. Consider the case where the user calls UpdateController for the first time and sets params.DelayUpdate to a non-zero value. At this time, runController will be called through UpdateController->updateController->createControllerLocked. Note that the requirement for runController at this time is to run the related loop and take into account the delay processing (although parms is set, it does not need to be executed immediately)

In this case, when we start runController, can we give a dummyparms, whose DoFunc is guaranteed to always succeed (See (c *managedController) updateParamsLocked) . At the same time, the interval of dummyparms remains unset.
In this way, we don't need to make any changes to the runControl function.

Comment (orange30) [reply pkg/controller/controller.go]: Yes. Please help review it again.

File: pkg/controller/manager.go [hunk 13]
```diff
@@ -52,6 +52,20 @@ func (m *Manager) UpdateController(name string, params ControllerParams) {
...
 }
 
+func (m *Manager) delayUpdate(ctrl *managedController, params ControllerParams) {
+	select {
+	case <-time.After(params.DelayUpdate):
+		m.mutex.Lock()
+		select { // Refer to func (m *Manager) createControllerLocked
+		case ctrl.update <- params:
+		default:
+		}
```
Comment (joestringer) [inline pkg/controller/manager.go]: Could this lose updates if `runController()` is not ready to receive the update event?

Maybe this is more robust?
```suggestion
		// Attempt to send the parameters update unless there is a race to shut down.  
		select {
		case ctrl.update <- params:
		case <-ctrl.stop:
		}
```

File: pkg/controller/manager.go [hunk 14]
```diff
@@ -74,9 +88,13 @@ func (m *Manager) updateController(name string, params ControllerParams) *manage
...
 
 		// Notify the goroutine of the params update.
-		select {
-		case ctrl.update <- ctrl.params:
-		default:
+		if ctrl.params.DelayUpdate == 0 {
+			select {
+			case ctrl.update <- ctrl.params:
+			default:
+			}
```
Comment (joestringer) [inline pkg/controller/manager.go]: Hmm interesting, this doesn't seem right to me either. I appreciate this is how the existing code already worked, but it seems to me like if the controller is not ready to receive an update (because for instance it is actively processing its run function), then this update will just be dropped. That seems bad also. Maybe we aren't using `UpdateController()` that often after startup so we never noticed this problem before.

At the risk of causing backpressure up the callstack, this seems more robust:
```suggestion
			// Attempt to send the parameters update unless there is a race to shut down.
			select {
			case ctrl.update <- ctrl.params:
			case <-ctrl.stop
			}
```

File: pkg/controller/manager.go [hunk 15]
```diff
@@ -108,6 +126,16 @@ func (m *Manager) createControllerLocked(name string, params ControllerParams) *
...
+	if params.DelayUpdate == 0 {
+		select {
+		case ctrl.update <- ctrl.params:
+		default:
+		}
+	} else {
+		go m.delayUpdate(ctrl, ctrl.params)
+	}
+
 	go ctrl.runController(ctrl.params)
```
Comment (joestringer) [inline pkg/controller/manager.go]: Isn't the first update lost because `go ctrl.runController(...)` isn't run until after? So there's nothing to receive/handle the message on the other side, meaning the `select {...}` statement becomes a non-blocking send?

**Review by joestringer — CHANGES_REQUESTED** [review]

File: pkg/controller/manager.go (hunk 15 above)
Comment (joestringer) [reply pkg/controller/manager.go]: For the `DelayUpdate == 0` case I think we can just move the `go ctrl.runController()` above this hunk and then perform a blocking send. Then for the delay update case I think it's already doing a blocking send so it should be good to go.

File: pkg/controller/manager.go (hunk 14 above)
Comment (joestringer) [reply pkg/controller/manager.go]: Apparently there is a whole thread about this bug in the tree already :sweat_smile: https://github.com/cilium/cilium/issues/29015

Comment (orange30) [reply pkg/controller/manager.go]: > Hmm interesting, this doesn't seem right to me either. I appreciate this is how the existing code already worked, but it seems to me like if the controller is not ready to receive an update (because for instance it is actively processing its run function), then this update will just be dropped. That seems bad also. Maybe we aren't using `UpdateController()` that often after startup so we never noticed this problem before.
> 

Yes, I agress that "maybe we aren't using UpdateController() that often after startup".

> At the risk of causing backpressure up the callstack, this seems more robust:

1. "Backpressure up the callstack" seems to have some risks that need to assess.
2. In func (m *Manager) createControllerLocked, when we initialize the update channel, why not we initialize the channel size to be 32?
3. If we can set the update channel size to be 32, and then we use this change, then I think the risk of "Backpressure up the callstack" will be Insignificant。

File: pkg/controller/manager.go (hunk 15 above)
Comment (orange30) [reply pkg/controller/manager.go]: Now the size of ctrl.update channel is 1, so I think the first "ctrl.update <- ctrl.params" will success. 
"move the go ctrl.runController() above this hunk" looks fine, I will fix it.

File: daemon/cmd/daemon_main.go [hunk 16]
```diff
@@ -445,6 +445,9 @@ func InitGlobalFlags(cmd *cobra.Command, vp *viper.Viper) {
 	flags.Duration(option.IdentityChangeGracePeriod, defaults.IdentityChangeGracePeriod, "Time to wait before using new identity on endpoint identity change")
 	option.BindEnv(vp, option.IdentityChangeGracePeriod)
 
+	flags.Duration(option.DelayCIdentityOfNsLabelChange, 30*time.Second, "Randomly delay CiliumIdentity updates for Endpoints by up to this time after Namespace labels change")
```
Comment (sypakine) [inline daemon/cmd/daemon_main.go]: The more accurate and concise term is jitter:

https://en.wikipedia.org/wiki/Jitter

Comment (sypakine) [inline daemon/cmd/daemon_main.go]: nit: `DelayCIdentityOfNsLabelChange` is confusing and too narrowly specified. Something like `CiliumIdentityMaxJitter` can be extended to be used elsewhere if necessary.

**Comment by squeed** [comment]
As inspired by this PR, I filed #38319, which makes it so that identical pods should generally get the same numeric ID.

File: pkg/controller/controller.go [hunk 17]
```diff
@@ -105,6 +105,9 @@ type ControllerParams struct {
 	NoErrorRetry bool
 
 	Context context.Context
+
+	// The interval for which this update needs to be delayed
```
Comment (sypakine) [inline pkg/controller/controller.go]: nit: 

```
// UpdateJitter is the duration to delay processing the update event.
```

File: daemon/cmd/daemon_main.go [hunk 18]
```diff
@@ -445,6 +445,9 @@ func InitGlobalFlags(cmd *cobra.Command, vp *viper.Viper) {
 	flags.Duration(option.IdentityChangeGracePeriod, defaults.IdentityChangeGracePeriod, "Time to wait before using new identity on endpoint identity change")
 	option.BindEnv(vp, option.IdentityChangeGracePeriod)
 
+	flags.Duration(option.CiliumIdentityMaxJitter, 30*time.Second, "Maximum jitter time for CiliumIdentity")
```
Comment (sypakine) [inline daemon/cmd/daemon_main.go]: reference the default value:

```
flags.Duration(option.CiliumIdentityMaxJitter, defaults.CiliumIdentityMaxJitter, "Maximum jitter time for CiliumIdentity")
```

File: pkg/defaults/defaults.go [hunk 19]
```diff
@@ -166,6 +166,9 @@ const (
 	// option.IdentityChangeGracePeriod
 	IdentityChangeGracePeriod = 5 * time.Second
 
+	//Maximum jitter time for CiliumIdentity
```
Comment (sypakine) [inline pkg/defaults/defaults.go]: nit: 

```
// CiliumIdentityMaxJitter is the maximum duration to delay processing a CiliumIdentity under certain conditions.
```

File: pkg/endpoint/endpoint.go [hunk 20]
```diff
@@ -1912,6 +1912,14 @@ func (e *Endpoint) RunRestoredMetadataResolver(bwm dptypes.BandwidthManager, res
 // endpoint will receive a new identity and will be regenerated. Both of these
 // operations will happen in the background.
 func (e *Endpoint) ModifyIdentityLabels(source string, addLabels, delLabels labels.Labels) error {
+	return e.modifyIdentityLabelsWithJitter(source, addLabels, delLabels, 0)
+}
+
+func (e *Endpoint) ModifyIdentityLabelsWithJitter(source string, addLabels, delLabels labels.Labels, UpdateJitter time.Duration) error {
```
Comment (sypakine) [inline pkg/endpoint/endpoint.go]: I'll defer to Isovalent folks but I'm wary of this pattern as it may lead to proliferation of methods.

Options struct or functional options pattern can keep this in check.

File: pkg/k8s/watchers/namespace.go [hunk 21]
```diff
@@ -122,6 +125,13 @@ func getNamespaceLabels(ns *slim_corev1.Namespace) labels.Labels {
 	return labels.Map2Labels(labelMap, labels.LabelSourceK8s)
 }
 
+// randomDuration generates a random time.Duration between 0 and maxDuration
+func randomDuration(maxDuration time.Duration) time.Duration {
+	// Generate a random duration
```
Comment (sypakine) [inline pkg/k8s/watchers/namespace.go]: nit: omit comment as this is self-evident:

```
	return time.Duration(rand.Int64N(int64(maxDuration)))
```

File: pkg/option/config.go [hunk 22]
```diff
@@ -825,6 +825,9 @@ const (
 	// IdentityChangeGracePeriod option
 	IdentityChangeGracePeriod = "identity-change-grace-period"
 
+	// Maximum jitter time for CiliumIdentity (default 30s)
```
Comment (sypakine) [inline pkg/option/config.go]: nit:

```
// CiliumIdentityMaxJitter is the maximum duration to delay processing a CiliumIdentity under certain conditions (default: 30s).
```

File: pkg/k8s/watchers/namespace.go [hunk 23]
```diff
@@ -139,7 +149,8 @@ func (u *namespaceUpdater) update(newNS *slim_corev1.Namespace) error {
 	for _, ep := range eps {
 		epNS := ep.GetK8sNamespace()
 		if newNS.Name == epNS {
-			err := ep.ModifyIdentityLabels(labels.LabelSourceK8s, newIdtyLabels, oldIdtyLabels)
+			err := ep.ModifyIdentityLabelsWithJitter(labels.LabelSourceK8s, newIdtyLabels, oldIdtyLabels,
+				randomDuration(option.Config.CiliumIdentityMaxJitter))
```
Comment (sypakine) [inline pkg/k8s/watchers/namespace.go]: consider: set as a field in the namespaceUpdater rather than referencing the global config

**Review by sypakine — COMMENTED** [review]
Could you add a sentence or two to each commit message body? For the first, can use `Related #38030`

File: pkg/endpoint/endpoint.go (hunk 20 above)
Comment (joestringer) [reply pkg/endpoint/endpoint.go]: Should be OK to add the parameter and update the callsites rather than adding a wrapper?

```
$ git grep ModifyIdentityLabels
daemon/cmd/endpoint.go: if err := ep.ModifyIdentityLabels(labels.LabelSourceAny, addLabels, delLabels); err != nil {
pkg/endpoint/endpoint.go:// ModifyIdentityLabels changes the custom and orchestration identity labels of an endpoint.
pkg/endpoint/endpoint.go:func (e *Endpoint) ModifyIdentityLabels(source string, addLabels, delLabels labels.Labels) error {
pkg/endpoint/endpoint.go:       changed, err := e.OpLabels.ModifyIdentityLabels(addLabels, delLabels)
pkg/endpoint/endpoint.go:       err := e.ModifyIdentityLabels(source, newIdtyLabels, oldIdtyLabels)
pkg/k8s/watchers/namespace.go:                  err := ep.ModifyIdentityLabels(labels.LabelSourceK8s, newIdtyLabels, oldIdtyLabels)
pkg/labels/oplabels.go:func (o *OpLabels) ModifyIdentityLabels(addLabels, delLabels Labels) (changed bool, err error) {
```

File: pkg/endpoint/endpoint.go [hunk 24]
```diff
@@ -1911,7 +1911,7 @@ func (e *Endpoint) RunRestoredMetadataResolver(bwm dptypes.BandwidthManager, res
 // Labels can be added or deleted. If a label change is performed, the
 // endpoint will receive a new identity and will be regenerated. Both of these
 // operations will happen in the background.
-func (e *Endpoint) ModifyIdentityLabels(source string, addLabels, delLabels labels.Labels) error {
+func (e *Endpoint) ModifyIdentityLabels(source string, addLabels, delLabels labels.Labels, UpdateJitter time.Duration) error {
```
Comment (sypakine) [inline pkg/endpoint/endpoint.go]: `updateJitter`

File: pkg/endpoint/endpoint.go [hunk 25]
```diff
@@ -2097,7 +2097,7 @@ func (e *Endpoint) identityResolutionIsObsolete(myChangeRev int) bool {
 // are currently configured on the endpoint.
 //
 // Must be called with e.mutex NOT held.
-func (e *Endpoint) runIdentityResolver(ctx context.Context, blocking bool) (regenTriggered bool) {
+func (e *Endpoint) runIdentityResolver(ctx context.Context, blocking bool, UpdateJitter time.Duration) (regenTriggered bool) {
```
Comment (sypakine) [inline pkg/endpoint/endpoint.go]: `updateJitter`

**Review by sypakine — COMMENTED** [review]
[Point 5](https://docs.cilium.io/en/latest/contributing/development/contributing_guide/#submitting-a-pull-request) states the commit should have a "well written commit description".

Can you reference an integration/e2e test that exercises namespace label changes? Want to make sure coverage for this exists.

**Comment by orange30** [comment]
> [Point 5](https://docs.cilium.io/en/latest/contributing/development/contributing_guide/#submitting-a-pull-request) states the commit should have a "well written commit description".

I have fixed it; please review it again. Thanks.

> Can you reference an integration/e2e test that exercises namespace label changes? Want to make sure coverage for this exists.

It appears that I couldn't find it; it may not exist.

**Review by sypakine — COMMENTED** [review]
LGTM; running tests before approving.

**Comment by orange30** [comment]
Now we have modified the implementation of runController, and there is a change: the param.DoFunc in the original version of runController will be executed immediately; in the current version, runController is mainly to run the for loop in goroutine, and param is passed by the update channel, which has a delay of varying degrees. This causes the unit test https://github.com/cilium/cilium/blob/6908ee3a6f1b2b87df681b65cc89eec4d367d013/pkg/controller/controller_test.go#L46 to fail.
Personally, in runController when the param.UpdateJitter is equal to 0, I think we're better executing param.DoFunc immediately  as before; in the for loop in runController it seems we have to introduce the if runFunc {} related logic that was deliberately discarded before.
What do you think? @joestringer @sypakine 

By the way, some CI checks report errors like "unknown flag: --code-owners". What is the reason for this? Thanks!

**Comment by orange30** [comment]
Because CiliumIdentity is fully distributed to all nodes, there is a risk of overwhelming the API server in large-scale clusters, just like the case discussed in this PR.
Similar to CiliumEndpointSlice, do we have plans to introduce CiliumIdentity slices? @squeed @joestringer @sypakine

**Comment by orange30** [comment]
Please help to review, thanks @joestringer @sypakine @squeed

**Comment by joestringer** [comment]
Could you rebase against the tip of the main branch?

File: daemon/cmd/daemon_main.go [hunk 26]
```diff
@@ -445,6 +445,9 @@ func InitGlobalFlags(cmd *cobra.Command, vp *viper.Viper) {
 	flags.Duration(option.IdentityChangeGracePeriod, defaults.IdentityChangeGracePeriod, "Time to wait before using new identity on endpoint identity change")
 	option.BindEnv(vp, option.IdentityChangeGracePeriod)
 
+	flags.Duration(option.CiliumIdentityMaxJitter, defaults.CiliumIdentityMaxJitter, "Maximum jitter time for CiliumIdentity")
```
Comment (joestringer) [inline daemon/cmd/daemon_main.go]:
```suggestion
	flags.Duration(option.CiliumIdentityMaxJitter, defaults.CiliumIdentityMaxJitter, "Maximum jitter time to begin processing CiliumIdentity updates")
```

File: pkg/controller/manager.go [hunk 27]
```diff
@@ -94,7 +112,7 @@ func (m *Manager) createControllerLocked(name string, params ControllerParams) *
 			group:      params.Group,
 			uuid:       uuid.New().String(),
 			stop:       make(chan struct{}),
-			update:     make(chan ControllerParams, 1),
+			update:     make(chan ControllerParams, 32),
```
Comment (joestringer) [inline pkg/controller/manager.go]: Why does this channel capacity need to change?

The concern I have is that we *must* make this code robust to blocking sends on the channel. Channel size is primarily useful as a buffer, not to handle concurrency issues. I don't think we expect to see many controller params updates, so maybe this should just stay at capacity 1?

File: pkg/endpoint/api.go [hunk 28]
```diff
@@ -576,7 +576,7 @@ func (e *Endpoint) ProcessChangeRequest(newEp *Endpoint, validPatchTransitionSta
 	rev := e.replaceIdentityLabels(labels.LabelSourceAny, newEp.OpLabels.IdentityLabels())
 	if rev != 0 {
 		// Run as a goroutine since the runIdentityResolver needs to get the lock
-		go e.runIdentityResolver(e.aliveCtx, false)
+		go e.runIdentityResolver(e.aliveCtx, false, 0)
```
Comment (joestringer) [inline pkg/endpoint/api.go:576]: I recognize that the goal of this PR is to mitigate namespace updates, but I wonder whether these other cases that are currently passing `0` should also have the new jitter behavior?

Comment (orange30) [reply pkg/endpoint/api.go:576]: > I recognize that the goal of this PR is to mitigate namespace updates, but I wonder whether these other cases that are currently passing `0` should also have the new jitter behavior?

They should not have jitter behavior.

File: pkg/controller/manager.go (hunk 27 above)
Comment (orange30) [reply pkg/controller/manager.go]: Ok, I change it to be 1.

File: pkg/endpoint/api.go (hunk 28 above)
Comment (joestringer) [reply pkg/endpoint/api.go:576]: What is your thinking behind saying that the other cases should not have jitter behavior? Is there something fundamentally different about those other updates?

Comment (orange30) [reply pkg/endpoint/api.go:576]: 1. From the caller's perspective: UpdateController's comment says: "Updating a controller will cause the DoFunc to be run immediately regardless of any previous conditions." Before we added the UpdateJitter parameter, when callers designed the logic related to calling functions, it was estimated that most of them assumed that UpdateController would execute DoFunc immediately. (Although the previous logic could not 100% guarantee immediate execution)
2. From the controller's perspective: When UpdateController is called, it is more reasonable if UpdateJitter is an absolute value: when UpdateJitter is 0, it intuitively means that it should be executed directly without delay.
3. From the perspective of patch modifying without introducing new risks: If we try to keep consistent with the previously declared logic, the probability of introducing unexpected new problems will be smaller.

**Comment by orange30** [comment]
> Now we have modified the implementation of runController, and there is a change: the param.DoFunc in the original version of runController will be executed immediately; in the current version, runController is mainly to run the for loop in goroutine, and param is passed by the update channel, which has a delay of varying degrees. This causes the unit test
> 
> https://github.com/cilium/cilium/blob/6908ee3a6f1b2b87df681b65cc89eec4d367d013/pkg/controller/controller_test.go#L46
> 
> to fail.
> Personally, in runController when the param.UpdateJitter is equal to 0, I think we're better executing param.DoFunc immediately as before; in the for loop in runController it seems we have to introduce the if runFunc {} related logic that was deliberately discarded before.
> What do you think? @joestringer @sypakine
> By the way, some CI checks report errors like "unknown flag: --code-owners". What is the reason for this? Thanks!

Clipboard_Screenshot_1744121622
The reason why this unit test fails is the analysis above. 
When UpdateJitter is 0,  maybe we're better executing param.DoFunc immediately in runController as before. @joestringer

File: pkg/controller/controller.go
Comment (joestringer) [inline pkg/controller/controller.go:1]: Looking afresh at the first patch, I'm wondering whether the extra goroutines and channels to delay updates are more complicated than we really need to solve the core problem. Why don't we just delay the `DoFunc()` within the existing core `runController()` loop? I'm thinking something like this to replace the first patch:

```
diff --git a/pkg/controller/controller.go b/pkg/controller/controller.go
index 0283b3247bc4..0722c6f61756 100644
--- a/pkg/controller/controller.go
+++ b/pkg/controller/controller.go
@@ -8,6 +8,7 @@ import (
        "errors"
        "fmt"
        "math"
+       "math/rand/v2"
        stdtime "time"
 
        "github.com/cilium/hive/cell"
@@ -105,6 +106,9 @@ type ControllerParams struct {
        NoErrorRetry bool
 
        Context context.Context
+
+       // Jitter is the duration to delay executing DoFunc.
+       Jitter time.Duration
 }
 
 // undefinedDoFunc is used when no DoFunc is set. controller.DoFunc is set to this
@@ -248,12 +252,17 @@ func (c *controller) runController(params ControllerParams) {
                interval := params.RunInterval
 
                start := time.Now()
+               jitter := time.Duration(0)
+               if params.Jitter > 0 {
+                       jitter = time.Duration(rand.Int64N(int64(params.Jitter)))
+               }
+               time.Sleep(jitter)
                err = params.DoFunc(params.Context)
                duration := time.Since(start)
 
                c.mutex.Lock()
                c.lastDuration = duration
-               c.getLogger().Debug("Controller func execution time: ", c.lastDuration)
+               c.getLogger().Debug("Controller func executed", "duration", c.lastDuration, "jitter", jitter)
 
                if err != nil {
                        if params.Context.Err() != nil {
```

File: daemon/cmd/endpoint.go [hunk 29]
```diff
@@ -1109,7 +1109,7 @@ func (d *Daemon) modifyEndpointIdentityLabelsFromAPI(id string, add, del labels.
 		return PatchEndpointIDInvalidCode, err
 	}
 
-	if err := ep.ModifyIdentityLabels(labels.LabelSourceAny, addLabels, delLabels); err != nil {
+	if err := ep.ModifyIdentityLabels(labels.LabelSourceAny, addLabels, delLabels, 0); err != nil {
```
Comment (joestringer) [inline daemon/cmd/endpoint.go]: I think it's fair to have no jitter on local REST API requests :+1:

File: pkg/endpoint/api.go (hunk 28 above)
Comment (joestringer) [reply pkg/endpoint/api.go:576]: I understand the concern that changing these other paths might incur additional risk, but this is a proposed change for v1.18 (ETA mid 2025) so we have a few months to test and validate the change. However, I am looking for reasoning about the logically correct path, not just what minimizes risk.

This specific path mentioned on this thread handles a PATCH event for the endpoint object on the REST API. This makes it very unlikely it'll cause the sorts of problems being addressed by this PR, so I think it is fine to keep this with zero jitter.

File: pkg/endpoint/endpoint.go [hunk 30]
```diff
@@ -2063,7 +2063,7 @@ func (e *Endpoint) UpdateLabels(ctx context.Context, sourceFilter string, identi
 
 	e.unlock()
 	if rev != 0 {
-		return e.runIdentityResolver(ctx, blocking)
+		return e.runIdentityResolver(ctx, blocking, 0)
```
Comment (joestringer) [inline pkg/endpoint/endpoint.go:2092]: It's not super obvious but tracing up the incoming calls to here reaches either local reserved endpoint creation (health, host, ingress); endpoint restoration on startup; or brand new endpoint creation, none of which require jitter to mitigate the issue outlined in the PR description. So I agree `0` is the right jitter here.

```
INCOMING CALLS                                                                                                                                                   
- f UpdateLabels github.com/cilium/cilium/pkg/endpoint • endpoint.go                                                                                             
  - f LaunchAsEndpoint github.com/cilium/cilium/pkg/endpoint • endpoint.go                                                                                       
    + f initHealth github.com/cilium/cilium/cilium-health/launch • health.go                                                                                     
  - f createEndpoint github.com/cilium/cilium/pkg/endpoint • endpoint.go                                                                                         
    + f putEndpointIDHandler github.com/cilium/cilium/daemon/cmd • endpoint.go                                                                                   
  - f metadataResolver github.com/cilium/cilium/pkg/endpoint • endpoint.go                                                                                       
    - f RunMetadataResolver github.com/cilium/cilium/pkg/endpoint • endpoint.go                                                                                  
      + f createEndpoint github.com/cilium/cilium/pkg/endpoint • endpoint.go                                                                                     
      - f RunRestoredMetadataResolver github.com/cilium/cilium/pkg/endpoint • endpoint.go                                                                        
        - f validateEndpoint github.com/cilium/cilium/pkg/endpoint • state.go                                                                                    
          + f restoreOldEndpoints github.com/cilium/cilium/daemon/cmd • state.go                                                                                 
        + f RegenerateAfterRestore github.com/cilium/cilium/pkg/endpoint • restore.go                                                                                                                                                     
  - f InitWithIngressLabels github.com/cilium/cilium/pkg/endpoint • endpoint.go                                                                                  
    - f AddIngressEndpoint github.com/cilium/cilium/pkg/endpoint • manager.go                                                                                    
      + f startDaemon github.com/cilium/cilium/pkg/endpointmanager • daemon_main.go                                                                              
  - f InitWithNodeLabels github.com/cilium/cilium/pkg/endpoint • endpoint.go                                                                                     
    - f initHostEndpointLabels github.com/cilium/cilium/pkg/endpoint • manager.go                                                                                
      + f AddHostEndpoint github.com/cilium/cilium/pkg/endpointmanager • manager.go                                                                              
      + f InitHostEndpointLabels github.com/cilium/cilium/pkg/endpointmanager • manager.go
```

File: pkg/endpoint/endpoint.go [hunk 31]
```diff
@@ -2077,7 +2077,7 @@ func (e *Endpoint) UpdateLabelsFrom(oldLbls, newLbls map[string]string, source s
 	oldLabels := labels.Map2Labels(oldLbls, source)
 	oldIdtyLabels, _ := labelsfilter.Filter(oldLabels)
 
-	err := e.ModifyIdentityLabels(source, newIdtyLabels, oldIdtyLabels)
+	err := e.ModifyIdentityLabels(source, newIdtyLabels, oldIdtyLabels, 0)
```
Comment (joestringer) [inline pkg/endpoint/endpoint.go]: This case traces up to `updateK8sPodV1` which could plausibly have a similar problem to the namespaces problem you mentioned. I think that for this case it would also make sense to configure `option.Config.CiliumIdentityMaxJitter`

File: pkg/controller/controller.go
Comment (joestringer) [reply pkg/controller/controller.go:1]: If we do this then `randomDuration()` could be removed from the k8s/watchers changes since the randomness is calculated in the inner loop.

**Review by joestringer — CHANGES_REQUESTED** [review]
Apologies about the delay, I have been traveling recently and haven't dedicated the time to thoroughly review the change.

I dug back through all the paths for configuring jitter and identified (a) A potential simpler implementation to both solve the current unit test failure as well as avoiding any extra goroutines or channel coordination; and (b) Another path from k8s that I think should have this jitter applied to it. See my comments below.

With these changes and a rebase against the latest `main` I'm hoping that all the tests should pass.

**Comment by joestringer** [comment]
> Similar to CiliumEndpointSlice, do we have plans to introduce CiliumIdentity slices?

No, we don't plan to introduce such a change. CiliumIdentity objects should not change at a super high rate. Are you constantly deploying brand new workloads that were never deployed before? This is expected to occur on human timescales rather than machine timescales. Even if you are changing namespace labels, it is worth considering to ignore such labels for security purposes to avoid having to process many such updates. Most likely your policies are not also changing so frequently that they must adapt to these new labels, so the system just has more churn than necessary to correctly implement the user policy. Perhaps your environment would benefit from better [identity-relevant labels configuration](https://docs.cilium.io/en/stable/operations/performance/scalability/identity-relevant-labels/#identity-relevant-labels).

File: pkg/controller/controller.go
Comment (orange30) [reply pkg/controller/controller.go:1]: > Looking afresh at the first patch, I'm wondering whether the extra goroutines and channels to delay updates are more complicated than we really need to solve the core problem. Why don't we just delay the `DoFunc()` within the existing core `runController()` loop? I'm thinking something like this to replace the first patch:
> 

If we use this patch, some update events may be lost。
Consider the following scenarios:
1. First of all, we modify the namespace label, the call stack is : func (u *namespaceUpdater) update() -> func (e *Endpoint) ModifyIdentityLabels () -> func (e *Endpoint) runIdentityResolver() ->e.controllers.UpdateController (..., updateJitter), for example, updateJitter is 25s.
2. Then, the label of the pod changes, and the call stack is: ...-> func (e *Endpoint) ModifyIdentityLabels () -> func (e *Endpoint) runIdentityResolver() ->e.controllers.UpdateController (..., 0) .
Now because the func (c *controller) runController is hanged for time.sleep(), ctrl.update channel will saves ctrl.params.
3. If the pod’s label changes again, then ctrl.params will cannot be saved to ctrl.update because the length of ctrl.update is 1. Then this update will be lost forever.
https://github.com/cilium/cilium/blob/77552f994d596891168741e903c63a566a15cd80/pkg/controller/manager.go#L83
// Notify the goroutine of the params update.
select {
case ctrl.update <- ctrl.params:
default:
}

This scenario should not happen too often, but it is unacceptable to cause update events to be lost.
If we initialize the length of ctrl.update to 32, it seems that this problem could be solved.
Another benefit of this change is that it linearizes the processing of multiple update events received by a specific controller.

File: pkg/endpoint/endpoint.go (hunk 31 above)
Comment (orange30) [reply pkg/endpoint/endpoint.go]: ok, I will modify it in next rebase.

**Comment by orange30** [comment]
> > Similar to CiliumEndpointSlice, do we have plans to introduce CiliumIdentity slices?
> 
> No, we don't plan to introduce such a change. CiliumIdentity objects should not change at a super high rate. Are you constantly deploying brand new application workloads that were never deployed before? This is expected to occur on human timescales rather than machine timescales. Even if you are changing namespace labels, it is worth considering to ignore such labels for security purposes to avoid having to process many such updates. Most likely your policies are not also changing so frequently that they must adapt to these new labels, so the system just has more churn than necessary to correctly implement the user policy. Perhaps your environment would benefit from better [identity-relevant labels configuration](https://docs.cilium.io/en/stable/operations/performance/scalability/identity-relevant-labels/#identity-relevant-labels).

Thanks! We are currently trying to explain this [Limiting Identity-Relevant Labels] to users.
However, we are public cloud, some clusters have a large number of cluster nodes, and it is not easy to control how users configure namespace labels.
In addition, we also have another pain point: During the startup of cilium-agent, it lists so many objects. When the cluster is large and multiple cilium-agents are started or restarted at the same time, it will cause great pressure on the apiserver.

File: pkg/controller/controller.go
Comment (joestringer) [reply pkg/controller/controller.go:1]: Thanks for the analysis. I think that the controller is being a bit misused in this case. Controller is intended as an async loop that can be triggered at some point in the future, it is *not* intended to be a lossless queue. Related, I've proposed a change that would ensure that eventually the configuration which is applied to the controller will take effect: https://github.com/cilium/cilium/pull/38853 .

For (2), it should use the same configuration for the updateJitter as we discussed in [this thread](https://github.com/cilium/cilium/pull/38031#discussion_r2034019587). Technically there are other ways to trigger a similar situation using the local REST API, but it is rare to use that API and I'm not sure it's worth building a more complicated solution just to address that particular case.

With #38853 and the proposed solution above I think that we should no longer lose important configuration updates.

**Comment by joestringer** [comment]
@orange30 I would encourage you to search for issues for those particular observations or file one if you can't find one. You can also tag @cilium/sig-scalability . Several community members are encountering similar challenges as you, so I think it would be helpful to work together on the solutions.

File: pkg/controller/controller.go
Comment (orange30) [reply pkg/controller/controller.go:1]: https://github.com/cilium/cilium/issues/29015#issuecomment-1822600339
It looks #38853 is a better solution, after it is merged, I will rebase this pr again.

**Review by joestringer — APPROVED** [review]
Looks good to me. Thanks for your patience as we worked through the review process to try to simplify the implementation to make it more reliable.

**Comment by joestringer** [comment]
I trimmed back the required reviewers and just re-requested a fresh look from the reviewers who previously took a look, just in case I missed anything.

**Comment by orange30** [comment]
Clipboard_Screenshot_1744819184
I am not familiar with this test case and do not understand why our modification caused this test case to fail. I need some time to analyze it. Do you have any suggestions? @joestringer @squeed @tklauser

**Comment by joestringer** [comment]
@orange30 This PR applies a delay implementing CiliumIdentity changes. The test in question implements network policy and reached a timeout. The most likely scenario is that this test ensures that network policy is correctly calculated and applied. However because of the newly introduced delay, the test no longer reliably updates the policy. Note I didn't confirm this theory, it could be some other reason. Unfortunately this reason would also imply that it makes the test unreliable - sometimes passing, sometimes failing.

Incidentally this could also impact many other tests in the CI.

We might be able to improve this by ensuring the new logic uses the `pkg/time` wrapper (for example in the `Sleep(...)`, and in the test environment, apply a lower `MaxInternalTimerDelay` to bound the maximum variation in reaction to CiliumIdentity updates.

**Comment by orange30** [comment]
Clipboard_Screenshot_1745152158
Clipboard_Screenshot_1745152340
1. Add debugging to the key paths of our modified functions:
func (e *Endpoint) ModifyIdentityLabels
func (e *Endpoint) UpdateLabelsFrom
func (e *Endpoint) runIdentityResolver
and func (c *controller) runController().
2. Run the test: go test -v ./daemon/cmd -run ^TestIncrementalPolicyEtcd$
3. The test case is passed:
Clipboard_Screenshot_1745152735
4. During the execution, none of the debugging information I added was printed out.

It seems that this test case may be just an occasional failure that takes more than 1 second.
https://github.com/cilium/cilium/blob/1dbb3e677924e1b7ce4151bc337de0cdd5ed71fa/daemon/cmd/policy_test.go#L973

Can we run the test again? @joestringer

**Comment by joestringer** [comment]
I did a quick search for the related test in the Issues tab and I found https://github.com/cilium/cilium/issues/37678 . As such it seems that this particular test has some low background failure rate and it's not clear whether this PR makes any significant difference to that failure rate. I'll retrigger the tests.

**Comment by joestringer** [comment]
There's been five successful integration test runs in a row now, so it seems highly unlikely that this PR is introducing a failure rate there: https://github.com/cilium/cilium/actions/runs/14406813447 .

This should be good to merge assuming the other code owners approve.

**Comment by joestringer** [comment]
@sypakine / @squeed could you take a look or re-request @cilium/sig-k8s / @cilium/endpoint reviews for the other code owner areas?

**Review by sypakine — APPROVED** [review]
Apologies for the delay, I just returned for 3 weeks of OOO with no github access.

**Comment by joestringer** [comment]
I didn't realize this was still outstanding. @squeed I will mark this for auto-merge as there has been no response from you for some time.

**Comment by marseel** [comment]
nice improvement, thanks! (I've retriggered failed tests)

**Comment by joestringer** [comment]
Ah apparently the PR still needs sign-off from @cilium/endpoint .

File: pkg/controller/controller.go [hunk 32]
```diff
@@ -312,6 +316,11 @@ func (c *controller) runController() {
 		interval := params.RunInterval
 
 		start := time.Now()
+		jitter := time.Duration(0)
+		if params.Jitter > 0 {
+			jitter = time.Duration(rand.Int64N(int64(params.Jitter)))
+			time.Sleep(jitter)
```
Comment (gandro) [inline pkg/controller/controller.go]: nit: Since the sleep is potentially quite long, would it make sense to use an interruptible sleep here (i.e. a select statement that waits both on `time.After` and on `params.Context.Done()` ?

**Review by gandro — APPROVED** [review]
Seems pretty straight forward

File: pkg/controller/controller.go (hunk 32 above)
Comment (orange30) [reply pkg/controller/controller.go]: @gandro Thanks, I think this is a good idea! 
Maybe the change looks like:
Clipboard_Screenshot_1749651280
 @joestringer Do you have any suggestions?

Comment (gandro) [reply pkg/controller/controller.go]: Yeah this looks good to me!

**Comment by gandro** [comment]
Thanks for the update. Please note that there's an issue with the docs: `HINT: to fix this, run 'make -C Documentation update-cmdref'`

**Comment by gandro** [comment]
Looks like this needs a rebase to pass the gateway test. I'll do rebase.

**Comment by joestringer** [comment]
I'd like to see this in the upcoming v1.18 release and I think there are no serious concerns. I added the label to make it easier to track.

Despite the Ariane reaction on the test command above, the workflows do not appear to have been triggered. I will retrigger them now.

**Comment by joestringer** [comment]
Thanks again for the contribution @orange30!
