### PR TITLE
fix(lint): Correct the cidrs for linux routing in cni

### LINKED ISSUE #11562: Double check the usage of cidrs in plugins/cilium-cni/interface.go
Related to https://github.com/cilium/cilium/pull/11528#discussion_r425315197

### PR DESCRIPTION
**Pull request by sayboras**
Related to
https://github.com/cilium/cilium/pull/11528#discussion_r425315197

Closes #11562

Signed-off-by: Tam Mach <sayboras@yahoo.com>

```release-note
Correct cidr input in linuxRouting.NewRoutingInfo
```

### CODE REVIEW

**Review by tklauser — CHANGES_REQUESTED** [review]
It would be great if you could explain the reason behind this change (i.e. why it is safe to convert `cidrs` to a string slice and use it instead of `ipam.Cidrs` and why no CIDRs are lost in the process) in the commit message. Otherwise it will be hard to understand from the git log alone (without referring to the linked PR comments) why this change was made.

**Comment by sayboras** [comment]
> It would be great if you could explain the reason behind this change (i.e. why it is safe to convert `cidrs` to a string slice and use it instead of `ipam.Cidrs` and why no CIDRs are lost in the process) in the commit message. Otherwise it will be hard to understand from the git log alone (without referring to the linked PR comments) why this change was made.

Sorry about this, it's my mistake to mark this as ready for review (I supposed to send different one for review). I still need to figure out on how to test this change, might require a mix of ipv4 and ipv6 cidrs. I am marking this one as draft now.

**Comment by tklauser** [comment]
> > It would be great if you could explain the reason behind this change (i.e. why it is safe to convert `cidrs` to a string slice and use it instead of `ipam.Cidrs` and why no CIDRs are lost in the process) in the commit message. Otherwise it will be hard to understand from the git log alone (without referring to the linked PR comments) why this change was made.
> 
> Sorry about this, it's my mistake to mark this as ready for review (I supposed to send different one for review). I still need to figure out on how to test this change, might require a mix of ipv4 and ipv6 cidrs. I am marking this one as draft now.

Perfect, thank you @sayboras!

**Comment by christarazi** [comment]
Yeah the testing of this is not very obvious. You could refactor the code in such a way that the function to gather the inputs returns the "coalesced" or "consolidated" result of those, and create a unit test to assert against. 

I don't think that's very valuable as these pieces of functionality (the coalescing and `NewRoutingInfo`) are already tested. You could also tack on the different inputs as different cases in the [linuxrouting tests](https://github.com/cilium/cilium/blob/master/pkg/datapath/linux/routing/info_test.go).

**Comment by sayboras** [comment]
@christarazi @tklauser Thanks for your comments, I just got a time to continue with this.

After checking the code, I feel like we need to confirm if the Coalesce CIDRs (ip v4) only _should_ be used for configure routing. If yes, as both methods _ip.CoalesceCIDRs_ and _linuxrouting.NewRoutingInfo_ are already coverred by unit test, all I need to do is just to check the below block:

```go
	cidrs := make([]string, 0, len(ipv4CIDRs))
	for _, cidr := range ipv4CIDRs {
		cidrs = append(cidrs, cidr.String())
	}
```

If the original cidrs from IPAM _should be_ used, I can just remove un-related code (and confusing comment). Kindly let me know what you have in mind. Thanks

**Comment by christarazi** [comment]
https://github.com/cilium/cilium/pull/10887

> @christarazi @tklauser Thanks for your comments, I just got a time to continue with this.
> 
> After checking the code, I feel like we need to confirm if the Coalesce CIDRs (ip v4) only _should_ be used for configure routing. If yes, as both methods _ip.CoalesceCIDRs_ and _linuxrouting.NewRoutingInfo_ are already coverred by unit test, all I need to do is just to check the below block:
> 
> ```go
> 	cidrs := make([]string, 0, len(ipv4CIDRs))
> 	for _, cidr := range ipv4CIDRs {
> 		cidrs = append(cidrs, cidr.String())
> 	}
> ```
> 
> If the original cidrs from IPAM _should be_ used, I can just remove un-related code (and confusing comment). Kindly let me know what you have in mind. Thanks

We definitely want to keep the coalescing as this behavior was recently added for a certain feature: https://github.com/cilium/cilium/pull/10887

**Review by christarazi — CHANGES_REQUESTED** [review]
~~The changes look good. Thanks for following up on this! One item to address for me.~~

File: pkg/datapath/linux/routing/info.go [hunk 1]
```diff
@@ -56,7 +56,7 @@ func parse(gateway string, cidrs []string, macAddr string) (*RoutingInfo, error)
 		return nil, fmt.Errorf("invalid ip: %s", gateway)
 	}
 
-	if cidrs == nil || len(cidrs) == 0 {
```
Comment (christarazi) [inline pkg/datapath/linux/routing/info.go:59]: Why was this nil check removed? It'll make this test fail: https://github.com/cilium/cilium/blob/84db4f63a7c99c472823b84c202196897272fb4a/pkg/datapath/linux/routing/info_test.go#L79

**Review by christarazi — CHANGES_REQUESTED** [review]
The changes look good. Thanks for following up on this! One item to address for me.

File: pkg/datapath/linux/routing/info.go (hunk 1 above)
Comment (sayboras) [reply pkg/datapath/linux/routing/info.go:59]: @christarazi thanks for your input. I enabled for _gosimple_ in my IDE by default, and basically len() for nil slices is defined as zero in go, so I don't think the above test is failing. I just verify by running the test locally as well.

Feel free to let me know otherwise.

**Review by aanm — CHANGES_REQUESTED** [review]
Nice finding. Small nit can you add a 

```
Fixes: b58dd147ed44 ("Refactor enirouting pkg to use interfaces")
```
in the commit message?

**Review by tklauser — APPROVED** [review]

File: pkg/datapath/linux/routing/info.go (hunk 1 above)
Comment (christarazi) [reply pkg/datapath/linux/routing/info.go:59]: Ah, I didn't know that!  :)

**Review by christarazi — APPROVED** [review]

**Comment by christarazi** [comment]
test-me-please

**Comment by aanm** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by christarazi** [comment]
K8s 1.11 hit known flake https://github.com/cilium/cilium/issues/11698, merging
