### PR TITLE
service cache should handle duplicate endpoints addresses

### LINKED ISSUE #22446: fail to forward traffic to custom Endpoint Slices with the same Address on different Slices (it works for 1.12)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This was found by chance, long history here https://github.com/kubernetes/kubernetes/pull/114155 , the TL; DR is that Cilium is not able to forward traffic to one of the backends if  a Service has 2 EndpointSlices, and each Slice have the same address but different port.

The linked PR https://github.com/kubernetes/kubernetes/pull/114155 improves the endpointslice mirroring controller to handle better the generation of endpoint slices, and it also adds an E2E regression test to verify that implementations are able to support this "slices combinations"

The e2e test passes for kube-proxy and fails in cilium , you can checkout my PR and run the test to reproduce it

```
_output/local/bin/linux/amd64/e2e.test  --ginkgo.focus="should.mirror.a.custom.Endpoint.with.multiple.subsets.and.same.IP.address"  --kubeconfig $HOME/.kube/config
...

Summarizing 1 Failure:
  [FAIL] [sig-network] EndpointSliceMirroring [It] should mirror a custom Endpoint with multiple subsets and same IP address
  test/e2e/network/util.go:177

Ran 1 of 7070 Specs in 144.823 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 7069 Skipped
--- FAIL: TestE2E (144.89s)

```

I only have a GKE cluster with DPv2 that runs an older version if Cilium, if I have more time I will try to reproduce it with HEAD, but I'm not having much time these days :(

The endpointslice mirroring controller is not really a bug fix, so it is not likely to be backported that means that old kubernetes versions before 1.27 will generate this "weird" EndpointSlices that will fail to forward traffic in cilium

### Cilium Version

Client: 1.11.9 1be589d924 2022-10-03T21:37:49+00:00 go version go1.17.13 linux/amd64
Daemon: 1.11.9 1be589d924 2022-10-03T21:37:49+00:00 go version go1.17.13 linux/amd64

### Kernel Version

Linux ... 5.15.65+ https://github.com/cilium/cilium/pull/1 SMP Sat Oct 29 09:33:11 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

1.25.3

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

I've tried to solve it by myself, but I'm not very familiar with the code, it seems that the aggregation is done on service_cache.go, my main suspicious is that the address is used as key in some place and not handling correctly the deduplicaiton overriding one of the slices, however , I couldn't find the problem 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by aojea**
In some corner cases, a group of endpointslices may have the same address duplicate in different slices.

Since the Endpoints are cached by address, when aggregating the endpoints, we should merge the content instead of overwriting.

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

Kubernetes e2e test now passes

```
e2e.test -kubeconfig /tmp/kindkind -ginkgo.v --ginkgo.focus="should.mirror.a.custom.Endpoint.with.multiple.subsets.and.same.IP.address"
```

Fixes: #22446

```release-note
Solved an issue failing to forward traffic to Services if the Endpoint Slices had the same Address on different Slices
```

### CODE REVIEW

**Comment by aojea** [comment]
/assign @aanm @squeed 

This is much easier to review, and we'll need for 1.11 if possible 🙏 

Thanks

**Review by varunmar — APPROVED** [review]
Nicely contained change. Thanks!

File: pkg/k8s/service_cache_test.go [hunk 1]
```diff
@@ -1061,6 +1061,223 @@ func (s *K8sSuite) TestServiceCacheWith2EndpointSlice(c *check.C) {
...
+				"foo": "bar",
+			},
+			Type: slim_corev1.ServiceTypeClusterIP,
+		},
+	}
+
+	swgSvcs := lock.NewStoppableWaitGroup()
+	svcID := svcCache.UpdateService(k8sSvc, swgSvcs)
+
+	time.Sleep(100 * time.Millisecond)
```
Comment (christarazi) [inline pkg/k8s/service_cache_test.go:1137]: Why is it necessary to have a sleep here? Typically these sleeps have been a source of flakes in our tests so we try to avoid them. The alternative is to have some sort of notification mechanism for when it's OK to proceed.

Comment (christarazi) [reply pkg/k8s/service_cache_test.go:1137]: To add more context, sleeps are unreliable because it depends on the current infrastructure that the test is running on. Usually what we've seen is tests passing on a local dev's machine (where there's not much of a noisy neighbor problem), but once it starts running on the CI infrastructure, it becomes flakey.

File: pkg/k8s/service_cache_test.go [hunk 2]
```diff
@@ -1061,6 +1061,223 @@ func (s *K8sSuite) TestServiceCacheWith2EndpointSlice(c *check.C) {
...
+		defer event.SWG.Done()
+		c.Assert(event.Action, check.Equals, DeleteService)
+		c.Assert(event.ID, check.Equals, svcID)
+		return true
+	}, 2*time.Second), check.IsNil)
+
+	// Deleting the endpoints will not emit an event as the notification
+	// was sent out when the service was deleted.
+	svcCache.DeleteEndpointSlices(k8sEndpointSlice1, swgEps)
+	time.Sleep(100 * time.Millisecond)
```
Comment (christarazi) [inline pkg/k8s/service_cache_test.go:1261]: Same as above

File: pkg/k8s/service_cache_test.go (hunk 1 above)
Comment (aojea) [reply pkg/k8s/service_cache_test.go:1137]: copy pasted from the test that is just before this, only adapted it changing the values of the endpoints

File: pkg/k8s/service_cache_test.go (hunk 2 above)
Comment (aojea) [reply pkg/k8s/service_cache_test.go:1261]: https://github.com/cilium/cilium/pull/24202#discussion_r1127124458

File: pkg/k8s/service_cache_test.go (hunk 1 above)
Comment (aojea) [reply pkg/k8s/service_cache_test.go:1137]: I wonder if the updates are handled via async events and the original author added the sleeps just for that, to avoid flakes

File: pkg/k8s/endpoints.go [hunk 3]
```diff
@@ -414,7 +414,17 @@ func (es *EndpointSlices) GetEndpoints() *Endpoints {
 	allEps := newEndpoints()
 	for _, eps := range es.epSlices {
 		for backend, ep := range eps.Backends {
-			allEps.Backends[backend] = ep
+			// EndpointSlices may have duplicate addresses on different slices.
```
Comment (aditighag) [inline pkg/k8s/endpoints.go:417]: It's worthwhile to add snippets of `kubectl get endpointslices` to explain the intention. Wdyt?

File: pkg/k8s/endpoints.go [hunk 4]
```diff
@@ -414,7 +414,17 @@ func (es *EndpointSlices) GetEndpoints() *Endpoints {
...
+			b, ok := allEps.Backends[backend]
+			if !ok {
+				allEps.Backends[backend] = ep
+			} else {
+				clone := b.DeepCopy()
+				for k, v := range ep.Ports {
+					clone.Ports[k] = v
```
Comment (aditighag) [inline pkg/k8s/endpoints.go:428]: Why do you explicitly copy over ports? Looks like `DeepCopy` should do the job, no?

**Review by aditighag — COMMENTED** [review]
Changes mostly look good! Thanks!

>Kubernetes e2e test now passes

Can we add this test to the cilium k8s conformance test suite?

nit: Can you fix the release note?

>Fix a bug where Cilium didn't handle correctly

*didn't correctly handle 

Also, release notes are user facing, so they should highlight the issue from the user's perspective. I think your original issue title might be better as a release note "fail to forward traffic to custom Endpoint Slices with the same Address on different Slices".

File: pkg/k8s/endpoints.go (hunk 4 above)
Comment (aojea) [reply pkg/k8s/endpoints.go:428]: you need to merge the ports from two different backends with the same key without mutating the original object.
You clone the first backend and append the pods of the second backend ... the bug is because it overwrites the existing backends, I can't see other way of merging both maps than this

**Comment by aojea** [comment]
> Can we add this test to the cilium k8s conformance test suite?

I specifically added an e2e test in Kubernetes to verify this behavior, as this bug was reported internally to me and was only present in Cilium and I wanted to check nobody else has it.

I apologize but I don't have more time to add new conformance tests, however,  I added a commit in https://github.com/cilium/cilium/pull/24174 to run this e2e kubernetes conformance tests, so it will be tested once that merges

I spend a lot of time in Kubernetes creating, maintaining and ensuring the kubernetes SIG-network tests covers and test all the known issues and features so the ecosystem is consistent with the behaviors we define in Kubernetes, cilium should run these e2e tests, it should have caught issues like this one or https://github.com/cilium/cilium/pull/24174

File: pkg/k8s/endpoints.go (hunk 3 above)
Comment (aojea) [reply pkg/k8s/endpoints.go:417]: yeah, I like that

**Review by squeed — APPROVED** [review]

File: pkg/k8s/endpoints.go (hunk 4 above)
Comment (aditighag) [reply pkg/k8s/endpoints.go:428]: Thanks for the explanation. It's useful context to add to the code comment above (with the kubectl command output) when you push the next revision. Something along these lines: `The backend has frontend as the overlapping address, and merged ports from both the endpoint slices`.

Comment (aditighag) [reply pkg/k8s/endpoints.go:428]: While this handles the case where endpoints with overlapping addresses but different ports are duplicated in ep slices, this doesn't handle the case where an endpoint as a whole is duplicated in ep slices, does it? If I interpreted this case described here correctly - https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/#duplicate-endpoints, won't we end up duplicating ports in the cloned backend?

Comment (aojea) [reply pkg/k8s/endpoints.go:428]:
```
// PortConfiguration is the L4 port configuration of a frontend or backend. The
// map is indexed by the name of the port and the value constains the L4 port
// and protocol.
//
// +deepequal-gen=true
type PortConfiguration map[string]*loadbalancer.L4Addr
```
it is a map, it can't have duplicates
