### PR TITLE
bpf: fix in-cluster connectivity for externalTrafficPolicy=Local

### LINKED ISSUE #11724: kube-proxy replacement: LoadBalancer traffic fails from host back to same host
## Bug report

**General Information**

- Cilium version (run `cilium version`)

```
Client: 1.7.4 c7ee6d62b 2020-05-15T16:07:35+02:00 go version go1.13.10 linux/amd64
Daemon: 1.7.4 c7ee6d62b 2020-05-15T16:07:35+02:00 go version go1.13.10 linux/amd64
```

- Kernel version (run `uname -a`)

```
Linux test03.lan 5.6.2-1.el7.elrepo.x86_64 #1 SMP Thu Apr 2 10:55:54 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
```

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Link to relevant artifacts (policies, deployments scripts, ...)

```
# automatically restarts pods to ensure controlled by new CNI driver
operator:
  enabled: true

global:
  k8sServiceHost: "127.0.0.1"
  k8sServicePort: "6443"
  enableXTSocketFallback: false

  prometheus:
    enabled: true

  bpf:
    preallocateMaps: true

  # disabling not ready for primetime yet
  # https://github.com/cilium/cilium/projects/93#column-7748410
  installIptablesRules: true

  # https://docs.cilium.io/en/latest/architecture/#arch-guide
  # https://cilium.io/blog/2019/02/12/cilium-14/#sockmap-bpf-based-sidecar-acceleration-alpha
  # https://www.youtube.com/watch?v=ER9eIXL2_14
  sockops:
    enabled: true

  k8s:
    # cilium pods will not start on node until pod CIDR has been assigned
    requireIPv4PodCIDR: true

  # eliminates need for any kind of BGP stuff
  # automatically addes routes to each node
  autoDirectNodeRoutes: true

  tunnel: disabled
  kubeProxyReplacement: strict
  hostServices:
    enabled: true
  nodePort:
    enabled: true
    # dsr or snat
    #mode: dsr
    mode: snat
  externalIPs:
    enabled: true

  # dev purposes only
  cleanState: false
  cleanBpfState: true
```

- Upload a system dump (run `curl -sLO
https://github.com/cilium/cilium-sysdump/releases/latest/download/cilium-sysdump.zip &&
python cilium-sysdump.zip` and then attach the generated zip file)

**How to reproduce the issue**

I'm using cilium with metallb with the kube-proxy replacement. I've got a pretty big matrix of scenarios I'm testing and most of them work, but we've found a situation where certain traffic fails to be handled. I believe I can distill the issue down to: when traffic leaves N1 (Node 1) and comes back to N1P (Pod running on Node 1) without an snat involved it fails

I've tried this with both `dsr` mode (my intended target) and `snat` mode (less interested, but wanted to try it out). Both fail under the above circumstances. Her's a pretty crude representation of what I think the traffic flows are and what works and what fails:

GW = gateway
R = router
NX = node X
NXP = pod running on node X

## dsr mode

```
# service with Cluster externalTrafficPolicy
N1 -> GW -> R -> N2 -> N1P: fail
N1 -> GW -> R -> N1 -> N1P: fail
N2 -> GW -> R -> N1 -> N1P: success

# service with Local externalTrafficPolicy
N2 -> GW -> R -> N1 -> N1P: success
N1 -> GW -> R -> N1 -> N1P: fail
```

## snat mode

```
# service with Cluster externalTrafficPolicy
N1 -> GW -> R -> N2 -> N1P: success
N1 -> GW -> R -> N1 -> N1P: fail

# service with Local externalTrafficPolicy
N2 -> GW -> R -> N1 -> N1P: success
N1 -> GW -> R -> N1 -> N1P: fail
```

### LINKED ISSUE #11746: NodePort svc with externalTrafficPolicy=Local cannot be reached from inside cluster when there are no local backends
In kube-proxy, a remote endpoint of a externalTrafficPolicy=Local svc is allowed to be accessed from inside a cluster.

To fix this, we can reorder the endpoints in the `lb{4,6}_service` maps in a way, that first in the list are local backends, and then maintain two counters - for local and for all. This would allow to select only local backends from bpf_host, while bpf_sock can select all.

### PR DESCRIPTION
**Pull request by borkmann**
See commit messages.

Fixes: #11746
Fixes: #11724

### CODE REVIEW

File: pkg/service/service.go [hunk 1]
```diff
@@ -237,10 +235,11 @@ func (s *Service) UpsertService(
...
 	backendsCopy := []lb.Backend{}
 	for _, b := range backends {
-		// Services with trafficPolicy=Local may only use node-local backends.
-		// We implement this by filtering out all backend IPs which are not a
-		// local endpoint.
-		if onlyLocalBackends && len(b.NodeName) > 0 && b.NodeName != nodeTypes.GetName() {
+		// Services with trafficPolicy=Local may only use node-local backends
+		// for external scope. We implement this by filtering out all backend
+		// IPs which are not a local endpoint.
+		if onlyLocalBackends && frontend.Scope == lb.ScopeExternal &&
```
Comment (gandro) [inline pkg/service/service.go]: I think we should merge the `&& frontend.Scope == lb.ScopeExternal` condition into the `onlyLocalBackends` flag.

Or, alternatively, add `&& frontend.Scope == lb.ScopeExternal` check to the if-statement here:
https://github.com/cilium/cilium/blob/d34558669add991d90e2f346476b378413b9e205/pkg/service/service.go#L265-L268

Otherwise we will add the backends of the internal frontend to the `HealthCheckNodePort` server, which is only supposed to keep count of backends for the external fronted.

**Review by gandro — CHANGES_REQUESTED** [review]
Overall looks good so far! One issue with regards to `HealthCheckNodePort`

File: pkg/service/service.go (hunk 1 above)
Comment (borkmann) [reply pkg/service/service.go]: Good point, yes, thanks for catching!

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-focus K8sService*

**Review by gandro — APPROVED** [review]

**Comment by borkmann** [comment]
test-focus K8sService*

**Comment by borkmann** [comment]
test-me-please

File: cilium/cmd/service_update.go [hunk 2]
```diff
@@ -28,15 +28,16 @@ import (
...
-	deprecatedAddRev bool // TODO(v1.8+): remove it
-	k8sExternalIPs   bool
-	k8sNodePort      bool
-	k8sHostPort      bool
-	k8sLoadBalancer  bool
-	k8sTrafficPolicy string
-	idU              uint64
-	frontend         string
-	backends         []string
+	deprecatedAddRev   bool // TODO(v1.8+): remove it
```
Comment (nebril) [inline cilium/cmd/service_update.go:31]: We didn't remove it ;_;

**Review by nebril — APPROVED** [review]
CI and k8s bits look good to me

File: cilium/cmd/service_update.go (hunk 2 above)
Comment (borkmann) [reply cilium/cmd/service_update.go:31]: Yep, correct. We should remove it along with the other stuff that we deprecated.

**Comment by borkmann** [comment]
test-focus K8sService*

**Comment by borkmann** [comment]
test-focus K8sService*

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-focus K8sService*

File: pkg/loadbalancer/loadbalancer.go [hunk 3]
```diff
@@ -157,6 +157,11 @@ const (
 	UDP = L4Type("UDP")
 )
 
+const (
+	ScopeExternal = 0
+	ScopeInternal = 1
```
Comment (aanm) [inline pkg/loadbalancer/loadbalancer.go]: This requires some documentation, I have no clue what this constants refers to.

File: pkg/loadbalancer/loadbalancer.go [hunk 4]
```diff
@@ -293,19 +298,22 @@ func (l *L4Addr) DeepCopy() *L4Addr {
 type L3n4Addr struct {
 	IP net.IP
 	L4Addr
+	Scope uint8
```
Comment (aanm) [inline pkg/loadbalancer/loadbalancer.go:305]: Same, what is 'Scope'?

File: pkg/loadbalancer/loadbalancer.go [hunk 5]
```diff
@@ -397,22 +418,30 @@ func (b *Backend) GetBackendModel() *models.BackendAddress {
 	}
 }
 
-// String returns the L3n4Addr in the "IPv4:Port" format for IPv4 and
-// "[IPv6]:Port" format for IPv6.
+// String returns the L3n4Addr in the "IPv4:Port[/Scope]" format for IPv4 and
+// "[IPv6]:Port[/Scope]" format for IPv6.
 func (a *L3n4Addr) String() string {
+	scope := ""
```
Comment (aanm) [inline pkg/loadbalancer/loadbalancer.go]: nit: `s/scope := ""/var scope string/`

File: pkg/loadbalancer/loadbalancer.go [hunk 6]
```diff
@@ -397,22 +418,30 @@ func (b *Backend) GetBackendModel() *models.BackendAddress {
...
-	return fmt.Sprintf("%s:%d", a.IP.String(), a.Port)
+	return fmt.Sprintf("%s:%d%s", a.IP.String(), a.Port, scope)
 }
 
-// StringWithProtocol returns the L3n4Addr in the "IPv4:Port/Protocol" format
-// for IPv4 and "[IPv6]:Port/Protocol" format for IPv6.
+// StringWithProtocol returns the L3n4Addr in the "IPv4:Port[/Scope]/Protocol"
+// format for IPv4 and "[IPv6]:Port[/Scope]/Protocol" format for IPv6.
 func (a *L3n4Addr) StringWithProtocol() string {
+	scope := ""
```
Comment (aanm) [inline pkg/loadbalancer/loadbalancer.go]: nit: `s/scope := ""/var scope string/`

File: pkg/loadbalancer/loadbalancer.go [hunk 7]
```diff
@@ -397,22 +418,30 @@ func (b *Backend) GetBackendModel() *models.BackendAddress {
...
+		return fmt.Sprintf("[%s]:%d%s", a.IP.String(), a.Port, scope)
 	}
-	return fmt.Sprintf("%s:%d", a.IP.String(), a.Port)
+	return fmt.Sprintf("%s:%d%s", a.IP.String(), a.Port, scope)
 }
 
-// StringWithProtocol returns the L3n4Addr in the "IPv4:Port/Protocol" format
-// for IPv4 and "[IPv6]:Port/Protocol" format for IPv6.
+// StringWithProtocol returns the L3n4Addr in the "IPv4:Port[/Scope]/Protocol"
+// format for IPv4 and "[IPv6]:Port[/Scope]/Protocol" format for IPv6.
```
Comment (aanm) [inline pkg/loadbalancer/loadbalancer.go]: Perhaps would be preferably to have the scope after the `/Protocol`? Usually the protocol is next to the port so it looks weird if we have something in between the two.

File: pkg/k8s/watchers/watcher.go [hunk 8]
```diff
@@ -611,12 +619,21 @@ func (k *K8sWatcher) delK8sSVCs(svc k8s.ServiceID, svcInfo *k8s.Service, se *k8s
...
 	svcType loadbalancer.SVCType,
 	ports map[loadbalancer.FEPortName]*loadbalancer.L4Addr,
 	bes *k8s.Endpoints,
 ) []loadbalancer.SVC {
+	var svcSize int
 
-	svcs := make([]loadbalancer.SVC, 0, len(ports))
+	if svcTrafficPolicy == loadbalancer.SVCTrafficPolicyLocal &&
+		(svcType == loadbalancer.SVCTypeLoadBalancer || svcType == loadbalancer.SVCTypeNodePort) {
+		svcSize = len(ports) * 2
```
Comment (aanm) [inline pkg/k8s/watchers/watcher.go:633]: add a comment for the why `len(ports) * 2`

File: pkg/k8s/watchers/watcher.go [hunk 9]
```diff
@@ -640,12 +657,32 @@ func genCartesianProduct(
...
 						},
+						Scope: loadbalancer.ScopeExternal,
 					},
 					ID: loadbalancer.ID(0),
 				},
 				Backends: besValues,
 				Type:     svcType,
 			})
+
+		if svcSize > len(ports) {
```
Comment (aanm) [inline pkg/k8s/watchers/watcher.go:672]: please add a comment to this condition, I would even create a new variable on top to be more explicit.
e.g. `isTrafficPolicyLocal := svcSize > len(ports)`

**Review by aanm — CHANGES_REQUESTED** [review]

**Comment by borkmann** [comment]
test-focus K8sService*

File: pkg/loadbalancer/loadbalancer.go (hunk 7 above)
Comment (borkmann) [reply pkg/loadbalancer/loadbalancer.go]: Agree, changed.

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-focus K8sService*

File: pkg/k8s/service_cache.go [hunk 10]
```diff
@@ -106,6 +106,8 @@ func NewServiceCache(nodeAddressing datapath.NodeAddressing) ServiceCache {
 }
 
 // GetServiceIP returns a random L3n4Addr that is backing the given Service ID.
+// The returned IP is with external scope since it's string representation might
```
Comment (qmonnet) [inline pkg/k8s/service_cache.go]:
```suggestion
// The returned IP is with external scope since its string representation might
```
(If you find other things to address; don't respin for that.)

**Review by qmonnet — APPROVED** [review]
Looks good, nice work!

File: pkg/k8s/service_cache.go (hunk 10 above)
Comment (borkmann) [reply pkg/k8s/service_cache.go]: Ok, I'll wait for the current CI to go through, and if all green, then fix the comment and wait only for travis.

**Comment by borkmann** [comment]
(All tests green, fixing up minor details and rerunning Travis CI and K8sService.)

**Comment by borkmann** [comment]
test-focus K8sService*

**Comment by borkmann** [comment]
(don't merge yet, still debugging on sth)

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-focus K8sService*

**Comment by borkmann** [comment]
(ready to merge once CI is green)

**Comment by borkmann** [comment]
Runtime-4.9 looks unrelated:
```
	 START: proxy_test.go:306: DNSProxyTestSuite.TestRejectNonMatchingRefusedResponse
	 proxy_test.go:329:
	     c.Assert(err, IsNil, Commentf("DNS request from test client failed when it should succeed"))
	 ... value *net.OpError = &net.OpError{Op:"dial", Net:"tcp", Source:net.Addr(nil), Addr:(*net.TCPAddr)(0xc00041a1e0), Err:(*poll.TimeoutError)(0x2f8d460)} ("dial tcp [::]:36405: i/o timeout")
	 ... DNS request from test client failed when it should succeed
	 
	 START: proxy_test.go:219: DNSProxyTestSuite.TearDownTest
	 PASS: proxy_test.go:219: DNSProxyTestSuite.TearDownTest	0.000s
	 
	 FAIL: proxy_test.go:306: DNSProxyTestSuite.TestRejectNonMatchingRefusedResponse
```

**Comment by borkmann** [comment]
test-focus had vbox error:
```
23:26:58  Progress state: VBOX_E_INVALID_OBJECT_STATE
23:26:58  VBoxManage: error: Machine delete failed
23:26:58  VBoxManage: error: Medium '/root/VirtualBox VMs/ubuntu-18.04.4-amd64-60_1593638818730_5500/ubuntu-18.04.4-amd64-60-disk001.vmdk' is locked for reading by another task
23:26:58  VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MediumWrap, interface IMedium
23:26:58  VBoxManage: error: Context: "RTEXITCODE handleUnregisterVM(HandlerArg*)" at line 162 of file VBoxManageMisc.cpp
```

**Comment by borkmann** [comment]
4.19 bailed on HealthCheckNodePort ... looking into it:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Kernel/2366/

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-focus K8sService*

**Comment by joestringer** [comment]
retest-net-next

**Review by joestringer — APPROVED** [review]
docs/cli/bpf LGTM. I didn't look so closely at services side.

**Comment by travisghansen** [comment]
https://github.com/cilium/cilium/issues/11724#issuecomment-652807033
