### PR TITLE
Fix kube-apiserver policy matching feature with tunneling enabled

### LINKED ISSUE #18049: kube-apiserver policy matching does not work with tunneling mode
This is a known issue at the moment when traffic from the kube-apiserver (i.e. hostNetwork pod on kube-apiserver host, CRD webhook) reaches out to a pod (Cilium endpoint). The reason why it doesn't work is because the `cilium_host` IP (router IP) that the traffic goes out from is associated with ID 6. Since traffic from the kube-apiserver host will be expected to have ID 7, this causes policy drops.

### PR DESCRIPTION
**Pull request by christarazi**
- bpf: Fix kube-apiserver policy drop in tunneling
- test/K8sT: Add case for duplicate kube-apiserver policy
- docs: Remove kube-apiserver policy feature limitation

See commit msgs.

Fixes: https://github.com/cilium/cilium/issues/18049
Updates: https://github.com/cilium/cilium/issues/17962
Updates: https://github.com/cilium/cilium/issues/17829

### CODE REVIEW

File: bpf/bpf_overlay.c [hunk 1]
```diff
@@ -74,6 +74,21 @@ static __always_inline int handle_ipv6(struct __ctx_buff *ctx,
...
+			struct remote_endpoint_info *info;
+
+			/* Look up the ipcache for the src IP, it will give us
+			 * the real identity of that IP */
+			info = ipcache_lookup6(&IPCACHE_MAP,
+					       (union v6addr *) &ip6->saddr,
+					       V6_CACHE_KEY_LEN);
+			if (info)
+				*identity = info->sec_label;
+		}
```
Comment (christarazi) [inline bpf/bpf_overlay.c]: It would be good to get a look from the @cilium/sig-encryption team on this change.

File: bpf/bpf_overlay.c [hunk 2]
```diff
@@ -74,6 +74,21 @@ static __always_inline int handle_ipv6(struct __ctx_buff *ctx,
 		 */
 		if (*identity == HOST_ID)
 			return DROP_INVALID_IDENTITY;
+
```
Comment (joestringer) [inline bpf/bpf_overlay.c:77]: The commit message here says:

> Going forward, there are two future changes needed in order:
> * After this commit, any packet associated with the kube-apiserver IP
  must have ID 7 (rather than ID 6; without needing the logic added by
  this commit).
> * Once v1.12.y is released, we can remove this specific code as we can
  expect all of this traffic to be transmitted with "kube-apiserver"
  identity (7).

I think what you're saying is that we need to make subsequent changes to the code to achieve each of these steps. But the tense ("After this commit, any packet ... must have ID 7") makes it ambiguous whether you're talking about the code now or some future version. Note that this commit message will end up backported to 1.11.y as well, so this could confuse future readers if they're investigating this code in v1.11 during an upgrade in future.

**Review by joestringer — APPROVED** [review]
Just one nit in the commit message.

File: bpf/bpf_overlay.c (hunk 2 above)
Comment (christarazi) [reply bpf/bpf_overlay.c:77]: Updated commit msg, hopefully it's clearer now.

**Review by twpayne — APPROVED** [review]

**Review by nbusseneau — APPROVED** [review]

**Review by joestringer — COMMENTED** [review]
Oh, one small nit: Please update `Documentation/policy/language.rst` to remove the text about the known issue. (Won't need re-running the full CI, can add a small patch at the end before merging or follow up with the change in another PR after this)

**Comment by christarazi** [comment]
I've added an extra commit to address Joe's comment above. The CI failures were legitimate. They should be fixed now.

**Comment by christarazi** [comment]
* net-next hit https://github.com/cilium/cilium/issues/18520
* 4.19 hit https://github.com/cilium/cilium/issues/18318
* runtime failed to provision

**Comment by christarazi** [comment]
@joamaki ping :)

**Review by joamaki — APPROVED** [review]
