### PR TITLE
wireguard: Use dummy peer for allowed IP removal

### LINKED ISSUE #33159: CI: Network performance GKE
Network performance GKE is failing for wireguard jobs all the time

Example run:
https://github.com/cilium/cilium/actions/runs/9457833052/job/26052335517

### PR DESCRIPTION
**Pull request by jrife**
Recent flakes in the "Network performance GKE" tests, in particular those that use wireguard, uncovered an issue where updates to a peer's allowed IPs can cause connectivity issues. In the best case this may just result in dropped packets while in the worst case may lead to failed calls to `sendto`/`sendmsg` (see GH-33159 for more detail on some of the symptoms observed while running netperf).
    
This issue happens when `ReplaceAllowedIPs` is set, as it causes the wireguard driver to completely clear the set of allowed IPs for a peer before the set is rebuilt. This leaves a gap where packets sent or received at that time will appear to not have a peer associated with them. The current implementation sets `ReplaceAllowedIPs` every time `updatePeerByConfig` is called, but we can avoid ever needing to use it.

This commit uses a "dummy peer" as a way to remove allowed IPs from a peer rather than using `ReplaceAllowedIPs`. We use `peerConfig` to track any pending IP inserts and removals and split these into two different sets of updates in `updatePeerByConfig`. The first call to `ConfigureDevice()` adds any IPs that are pending insertion. Next, any IPs that are pending removal are moved to the "dummy peer" before removing the dummy peer altogether, the net effect being that the IP is removed from the original peer's list of allowed IPs.
    
This commit mostly sidesteps the issue that GH-34095 ("wireguard: restore allowedIPs upong agent restart") set out to solve since we only ever explicitly remove allowed IPs, meaning we can do away with a lot of the accounting previously done by `restoredPeers` and `restoredAllowedIPs`. However, we retain the behavior in `RestoreFinished()` that removes stale peers and allowed IPs.

## Testing
I performed the steps outlined in #33159 in a local kind cluster both before and after applying the change contained in this PR. I ran `netperf` manually while executing this script which induces failure by forcing lots of calls to `updatePeerByConfig`.

```bash
#!/bin/bash

count=100
for i in $(seq $count); do
	kubectl label --overwrite nodes kind-control-plane kill-netperf=true
	kubectl label --overwrite nodes kind-control-plane kill-netperf=false
done
```
### Before
`netperf` fails every time consistently within seconds.

```bash
jrife@jrife-kvm:~/code/cilium$ kubectl exec -it -n cilium-test-1 perf-client-other-node-749b79954c-hpgts -- bash
[root@perf-client-other-node-749b79954c-hpgts netperf]# /usr/local/bin/netperf -H 10.244.0.108 -l 5m -t UDP_STREAM -- -R 1 -m 1024
MIGRATED UDP STREAM TEST from 0.0.0.0 (0.0.0.0) port 0 AF_INET to 10.244.0.108 () port 0 AF_INET
send_data: data send error: No route to host (errno 113)
netperf: send_omni: send_data failed: No route to host
```

### After
`netperf` runs to completion.

```bash
[root@perf-client-other-node-749b79954c-hpgts netperf]# /usr/local/bin/netperf -H 10.244.0.108 -l 30s -t UDP_STREAM -- -R 1 -m 1024
MIGRATED UDP STREAM TEST from 0.0.0.0 (0.0.0.0) port 0 AF_INET to 10.244.0.108 () port 0 AF_INET
Socket  Message  Elapsed      Messages                
Size    Size     Time         Okay Errors   Throughput
bytes   bytes    secs            #      #   10^6bits/sec

212992    1024   30.00     1196041      0     326.60
212992           30.00     1072058            292.74
```

Fixes: #33159 

```release-note
wireguard: Fix issue where updates to a WireGuard device's configuration caused connectivity blips.
```

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Thank you for the PR @jrife, docs look good.

File: pkg/wireguard/agent/agent.go [hunk 1]
```diff
@@ -572,15 +580,16 @@ func (a *Agent) OnIPIdentityCacheChange(modType ipcache.CacheModification, cidrC
 	case modType == ipcache.Delete && oldHostIP != nil:
 		if nodeName, ok := a.nodeNameByNodeIP[oldHostIP.String()]; ok {
 			if peer := a.peerByNodeName[nodeName]; peer != nil {
-				if peer.removeAllowedIP(ipnet) {
+				fmt.Println("Remove", ipnet)
```
Comment (jschwinger233) [inline pkg/wireguard/agent/agent.go]: Just for debugging?

**Review by jschwinger233 — COMMENTED** [review]
Thanks! My understanding is we are maintaining a list of peer IPs that exists on wg dev. My concerns are:
1. This is pure userspace, so it could happen that a peer IP is removed from wg dev by command line, but cilium still thinks the IP is on dev.
2. We need synchronization to avoid racing of slice operations. Maybe there already is, if `UpdatePeer()` is called by `UpdateNode()` which is protected by a mutex, just saying we'd better double check.

File: pkg/wireguard/agent/agent.go (hunk 1 above)
Comment (jrife) [reply pkg/wireguard/agent/agent.go]: Oops must have missed this one.

**Comment by jrife** [comment]
> 1. This is pure userspace, so it could happen that a peer IP is removed from wg dev by command line, but cilium still thinks the IP is on dev.

That's true, but where do we draw the line? Is it true that every Cilium-managed device or system configuration is repaired if a somebody modifies it out-of-band? Ensuring this would add some additional complexity where we periodically do a full scan of the device config and compare to what we think it is. Maybe this is justified, but my initial impression is that if I as a user am modifying config at that level then I have to be aware it might be messing something up and might need to restart the Cilium agent on that node to get things back on track.

> 2. We need synchronization to avoid racing of slice operations. Maybe there already is, if `UpdatePeer()` is called by `UpdateNode()` which is protected by a mutex, just saying we'd better double check.

As far as I can see reads and writes to `allowedIPs` should be covered by the agent's `RWMutex` in all places just like the slice that it replaces. If you see something I missed please let me know. Thanks!

**Comment by jrife** [comment]
Converting this back to a draft. It looks like things require a rework due to recent commits.

**Review by nathanjsweet — APPROVED** [review]
LGTM for CLI

**Comment by giorio94** [comment]
> CC @giorio94 who authored #34095 and @asauber @doniacld who reviewed it.
> 
> This PR largely subsumes the changes made there. The goal of this PR is to avoid using `ReplaceAllowedIPs` at all to perform updates to a peer's list of allowed IPs. With this PR there should be no disruption to existing peers or allowed IPs on agent startup until we get to `RestoreFinished()` when we can just diff what's on the device with what's in our `peerConfig` and remove anything that's stale. This does away with the accounting done by `restoredPeers` and `restoredPubKeys`. Feel free to have a look.

Cool, thanks for the heads-up. I haven't yet had time to look into the exact details of the implementation, but your approach looks definitely interesting.

Additionally /cc @gandro

**Comment by brb** [comment]
> This is pure userspace, so it could happen that a peer IP is removed from wg dev by command line, but cilium still thinks the IP is on dev.

I'd be not too concerned about it, as we don't expect users to modify those peer IPs (@jspaleta please confirm, IIRC you tried to modify those peers?).

File: pkg/wireguard/agent/agent.go [hunk 2]
```diff
@@ -732,97 +740,85 @@ type peerConfig struct {
...
+			delete(p.needsInsert, pfx)
+		}
 
-	a.restoredPeers[pubKey] = restored
-	return restored
+		if _, exists := p.needsRemove[pfx]; exists {
+			delete(p.allowedIPs, pfx)
+			delete(p.needsRemove, pfx)
+		}
+	}
```
Comment (gandro) [inline pkg/wireguard/agent/agent.go:835]: I wonder if it is worth setting the maps to `nil` if they are empty after we finished the sync. It will increase the number allocation/deallocations needed, but since otherwise the maps are never shrunk and basically consume memory forever.

File: pkg/wireguard/agent/agent.go [hunk 3]
```diff
@@ -48,6 +46,7 @@ import (
 )
 
 var log = logging.DefaultLogger.WithField(logfields.LogSubsys, "wireguard")
+var wgDummyPeerKey = wgtypes.Key{}
```
Comment (gandro) [inline pkg/wireguard/agent/agent.go:50]: How does this look in `wg show`? I also wonder if we want to validate `UpsertPeer` to make sure no malicious CilumNode ever claims to be the dummy peer (which would probably break things).

**Review by gandro — COMMENTED** [review]
I did a first pass and this is pretty clever and clean. I'll like do do a more thorough second review focusing a bit on the low-level bits later

**Comment by gandro** [comment]
> > This is pure userspace, so it could happen that a peer IP is removed from wg dev by command line, but cilium still thinks the IP is on dev.
> 
> I'd be not too concerned about it, as we don't expect users to modify those peer IPs (@jspaleta please confirm, IIRC you tried to modify those peers?).

As mentioned in #34095, I actually we might eventually want to introduce a generic reconciler that ensures that at least the Cilium-managed peers (including the dummy peer) are not tampered with (whether or not we allow unmanaged peers on the interface is another question I guess)

File: pkg/wireguard/agent/agent.go (hunk 3 above)
Comment (jrife) [reply pkg/wireguard/agent/agent.go:50]: >  also wonder if we want to validate `UpsertPeer` to make sure no malicious CilumNode ever claims to be the dummy peer (which would probably break things).

Good point, I will add some validation logic around this.

File: pkg/wireguard/agent/agent.go (hunk 2 above)
Comment (jrife) [reply pkg/wireguard/agent/agent.go:835]: It probably wouldn't hurt. `UpdatePeer()` in particular has this part

```golang
peer.queueAllowedIPsInsert(a.ipCache.LookupByHostRLocked(nodeIPv4, nodeIPv6)...)
```

which would grow the capacity `needsInsert` well past what is needed later on. I do wonder about the effects of constant reallocation during periods of high pod churn.

Comment (gandro) [reply pkg/wireguard/agent/agent.go:835]: > I do wonder about the effects of constant reallocation during periods of high pod churn.

Yeah, it is a tradeoff. Ideally we'd cap the capacity of the map to a reasonable limit and reuse it as long as it's under the limit, and reset if if it's a above the limit.
Unfortunately it seems Golang has no way to inspect a map's capacity. We could track manually in a separate field which isn't pretty either. 

Not sure what to recommend here. I am worried that in particular with large-scale clustermesh setups, we might have up to 100k-300k of queued allowed IPs in total, meaning leaking about 10-30 MBs of memory.

(unrelated: we've also discussed adding pod CIDRs (where possihble) rather than individal pod IPs as allowedIPs, that would also reduce the pod churn issue. But that's not something we should tackle in this PR)

Comment (jrife) [reply pkg/wireguard/agent/agent.go:835]: > Unfortunately it seems Golang has no way to inspect a map's capacity.

You could potentially just use the map's length as a proxy for its capacity inside `finishAllowedIPSync()` to determine whether or not the capacity has reached a "high water mark". I think we should probably just start simple with setting the maps to `nil` every time here though. I think in the average case memory consumption is going to be the main thing we are concerned with.

Comment (jrife) [reply pkg/wireguard/agent/agent.go:835]: > unrelated: we've also discussed adding pod CIDRs (where possihble) rather than individal pod IPs as allowedIPs,

I was thinking about this as well. Are there any IPAM modes where there isn't a clear CIDR range per node where this approach wouldn't work? I suspect you may even get some performance benefit with WireGuard throughput this way, as it means quicker lookups in the driver's internal routing table to determine the peer associated with an IP. It would be interesting to test this out.

Comment (gandro) [reply pkg/wireguard/agent/agent.go:835]: > I was thinking about this as well. Are there any IPAM modes where there isn't a clear CIDR range per node where this approach wouldn't work? 

Yes, there are. ENI mode[^1], delegated IPAM mode, manual CRD mode, legacy Azure IPAM and AlibabaCloud all do not have the concept of a per-node pod CIDR. Instead, IPs are allocated from a global CIDR that is shared among all nodes (and pod IPs can be reassigned to other nodes). On such configurations, we will have to keep per-IP lists. 

But for IPAM modes `cluster-pool` (default), `kubernetes` (common, default on GKE) and `multi-pool`[^2] we could absolutely switch to a podCIDR based approach.

> It would be interesting to test this out.

That would be awesome. I'm more than happy to review such a PR.

[^1]: Some ENI nodes do run with prefix delegation, which means pod IPs are allocated out of /28 CIDRs on each node (with multiple CIDRs per node). That behaves a bit like pod CIDRs and would reduce the number of entries in "allowedIPs". However, those /28 CIDRs are not exposed to the agent's node manager at the moment, so there is no way for WireGuard to know them.
[^2]: `multi-pool` will have multiple CIDRs per node that are allocated dynamically, so it's a bit more involved than `cluster-pool` or `kubernetes` which have a single static pod CIDR. But still pretty much doable.

File: pkg/wireguard/agent/agent.go (hunk 3 above)
Comment (jrife) [reply pkg/wireguard/agent/agent.go:50]: > How does this look in wg show? 

It's hard to capture with the PR as-is, since I delete the dummy peer immediately after moving IPs to it. For the sake of illustration, I commented that out locally to show what `wg show` would see. This shows before and after scaling a deployment down from 20 replicas to 1 replica. You can see that all the deleted IPs go to the dummy peer (`AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=`).

```
root@kind-worker:/# wg
interface: cilium_wg0
  public key: TnEOAoy+GCY3QMYiAUny3EpTT9DZ9VkW7KBUPLC03kU=
  private key: (hidden)
  listening port: 51871
  fwmark: 0x1e00

peer: ehHIOPWnKoJJUWBGlXQrokkGHpfu72Z6gqiNOuk8xBU=
  endpoint: 172.18.0.3:51871
  allowed ips: 172.18.0.3/32, 10.244.0.245/32, 10.244.0.60/32, fd00:10:244::a4c1/128, 10.244.0.32/32, 10.244.0.53/32, 10.244.0.115/32, 10.244.0.196/32, 10.244.0.84/32, 10.244.0.86/32, 10.244.0.81/32, 10.244.0.133/32, 10.244.0.171/32, 10.244.0.44/32, 10.244.0.186/32, 10.244.0.148/32, 10.244.0.83/32, 10.244.0.101/32, 10.244.0.230/32, 10.244.0.149/32, 10.244.0.92/32, 10.244.0.232/32, 10.244.0.207/32, 10.244.0.94/32, 10.244.0.135/32
root@kind-worker:/# wg
interface: cilium_wg0
  public key: TnEOAoy+GCY3QMYiAUny3EpTT9DZ9VkW7KBUPLC03kU=
  private key: (hidden)
  listening port: 51871
  fwmark: 0x1e00

peer: ehHIOPWnKoJJUWBGlXQrokkGHpfu72Z6gqiNOuk8xBU=
  endpoint: 172.18.0.3:51871
  allowed ips: 172.18.0.3/32, 10.244.0.245/32, 10.244.0.60/32, fd00:10:244::a4c1/128, 10.244.0.32/32, 10.244.0.53/32

peer: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
  allowed ips: 10.244.0.101/32, 10.244.0.92/32, 10.244.0.196/32, 10.244.0.86/32, 10.244.0.81/32, 10.244.0.171/32, 10.244.0.44/32, 10.244.0.232/32, 10.244.0.148/32, 10.244.0.83/32, 10.244.0.186/32, 10.244.0.84/32, 10.244.0.207/32, 10.244.0.94/32, 10.244.0.149/32, 10.244.0.230/32, 10.244.0.135/32, 10.244.0.133/32, 10.244.0.115/32
```

Comment (jrife) [reply pkg/wireguard/agent/agent.go:50]: > I also wonder if we want to validate UpsertPeer to make sure no malicious CilumNode ever claims to be the dummy peer (which would probably break things).

I added a check in `UpdatePeer()` to make sure a node can't claim the dummy peer key.

File: pkg/wireguard/agent/agent.go (hunk 2 above)
Comment (jrife) [reply pkg/wireguard/agent/agent.go:835]: > I think we should probably just start simple with setting the maps to nil every time here though.

Done in the latest push.

**Review by gandro — APPROVED** [review]
Awesome work, this looks good to me now!

**Comment by jrife** [comment]
@gandro Thanks. Is there any one else who needs to review this to get it merged?

**Comment by gandro** [comment]
There is a pending review from Gray, but he is out I believe, so I don't think we need to block this PR on him.

Once CI is green I think this should be ready to be merged.

**Comment by jrife** [comment]
It seems like there was a [GitHub issue](https://github.com/orgs/community/discussions/139743) causing the CI tests to fail in "Checkout pull request branch" a while ago. Can we retrigger the tests?
Screenshot from 2024-09-25 12-06-48

**Review by jschwinger233 — APPROVED** [review]
