### PR TITLE
identity: Reduce churn, fix manager refcounts

### LINKED ISSUE #8685: CI: Suite-k8s-1.10.K8sDatapathConfig DirectRouting Check connectivity with automatic direct nodes routes
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.10-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:420
Failure while waiting for all cilium endpoints to reach ready state
Expected
    <*helpers.SSHMetaError | 0xc003bfe360>: Error: context deadline exceeded
Extended info: 	Cilium Pod: cilium-j5kbd 	Endpoint: 292 	Identity: 12034	 State: ready
	Cilium Pod: cilium-j5kbd 	Endpoint: 415 	Identity: 4	 State: ready
	Cilium Pod: cilium-j5kbd 	Endpoint: 781 	Identity: 21948	 State: ready
	Cilium Pod: cilium-j5kbd 	Endpoint: 1005 	Identity: 101	 State: not-ready
	Cilium Pod: cilium-j5kbd 	Endpoint: 2294 	Identity: 101	 State: ready
	Cilium Pod: cilium-j5kbd 	Endpoint: 2750 	Identity: 100	 State: ready
	Cilium Pod: cilium-j5kbd 	Endpoint: 3473 	Identity: 102	 State: ready
	Cilium Pod: cilium-pmqvh 	Endpoint: 372 	Identity: 4	 State: ready
	Cilium Pod: cilium-pmqvh 	Endpoint: 653 	Identity: 101	 State: ready
	Cilium Pod: cilium-pmqvh 	Endpoint: 845 	Identity: 21948	 State: ready
	Cilium Pod: cilium-pmqvh 	Endpoint: 1428 	Identity: 12034	 State: ready
```

[4894657e_K8sDatapathConfig_DirectRouting_Check_connectivity_with_automatic_direct_nodes_routes.zip](https://github.com/cilium/cilium/files/3432162/4894657e_K8sDatapathConfig_DirectRouting_Check_connectivity_with_automatic_direct_nodes_routes.zip)
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/13869/testReport/junit/Suite-k8s-1/10/K8sDatapathConfig_DirectRouting_Check_connectivity_with_automatic_direct_nodes_routes/

More context: https://cilium.slack.com/archives/C7PE7V806/p1564066768028600?thread_ts=1564066303.028500&cid=C7PE7V806

### PR DESCRIPTION
**Pull request by jrajahalme**
Use identitymanager.Add instead of identitymanager.RemoveOldAddNew
when initially adding the identity of a new endpoint into the identity
manager. This fixes a refcounting bug, where upon the restoration of
two endpoints with the same labels the first restoration adds the
identity to the manager with refcount 1, but the second restoration
first deletes the lone refcount, triggering removal of the associated
policy from the policy cache, and then adds the same ID back, with the
resulting refcount of 1, even when two endpoints are using the same
ID.

Require the old identity given to RemoveOldAddNew to have been added
to the identity manager previously, and make the case where
RemoveOldAddNew is called with two identities with the same numerical
ID a no-op to reduce churn in the observers.

Fixes: #8685
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/8691)

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

File: daemon/state.go [hunk 1]
```diff
@@ -353,7 +353,7 @@ func (d *Daemon) regenerateRestoredEndpoints(state *endpointRestoreState) (resto
 			// The identity of a freshly restored endpoint is incomplete due to some
 			// parts of the identity not being marshaled to JSON. Hence we must set
 			// the identity even if has not changed.
-			ep.SetIdentity(identity)
+			ep.SetIdentity(identity, true)
```
Comment (joestringer) [inline daemon/state.go:356]: We might have already called `SetIdentity(oldIdentity, true`) in the `ParseEndpoint()` path in `pkg/endpoint`, then set a new, different identity here (because of different `--labels` options on the daemon). In that case we should actually remove a reference to the old identity.

**Review by joestringer — CHANGES_REQUESTED** [review]

**Comment by joestringer** [comment]
This only affects v1.6, because identitymanager didn't exist before that:

```
$ find . -maxdepth 1 -name "cilium-1.*" | sort 
./cilium-1.0
./cilium-1.1
./cilium-1.2
./cilium-1.3
./cilium-1.4
./cilium-1.5
./cilium-1.6
$ grep -s -R -F "identitymanager" cilium-* | xargs dirname | sort | uniq
.
/
cilium-1.6/cilium/cmd
cilium-1.6/daemon
cilium-1.6/.git
cilium-1.6/pkg/endpoint
cilium-1.6/pkg/identity/identitymanager
cilium-1.6/pkg/policy
github.com/cilium/cilium/pkg/identity
```

File: daemon/state.go (hunk 1 above)
Comment (jrajahalme) [reply daemon/state.go:356]: Thanks, did not notice that. Planning to make `ParseEndpoint()` NOT call `SetIdentity()` at all, but ensure that `ep.SecurityIdentity` is non-nil:
```
diff --git a/pkg/endpoint/endpoint.go b/pkg/endpoint/endpoint.go
index 2dde1a4c89..c560343f28 100644
--- a/pkg/endpoint/endpoint.go
+++ b/pkg/endpoint/endpoint.go
@@ -1086,11 +1086,12 @@ func ParseEndpoint(owner regeneration.Owner, strEp string) (*Endpoint, error) {
 		ep.Status = NewEndpointStatus()
 	}
 
+	// Make sure the endpoint has an identity, using the 'init' identity if none.
 	if ep.SecurityIdentity == nil {
-		ep.SetIdentity(identityPkg.LookupReservedIdentity(identityPkg.ReservedIdentityInit), true)
-	} else {
-		ep.SecurityIdentity.Sanitize()
+		ep.SecurityIdentity = identityPkg.LookupReservedIdentity(identityPkg.ReservedIdentityInit)
 	}
+	ep.SecurityIdentity.Sanitize()
+
 	ep.UpdateLogger(nil)
 
 	ep.SetStateLocked(StateRestoring, "Endpoint restoring")
```

This way the state of the endpoint's identity is consistent after `ParseIdentity()`: not registered with the identitymanager yet.

**Comment by jrajahalme** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Review by joestringer — APPROVED** [review]
