### PR TITLE
ToFQDN Runtime test waits for DNS policy to take effect

### LINKED ISSUE #5071: CI: ToFQDNs test failure
Build link: https://jenkins.cilium.io/job/Ginkgo-CI-Tests-Pipeline/3510/testReport/junit/(root)/runtime/RuntimePolicies_Enforces_ToFQDNs_policy/

Output:
```
Stacktrace

/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:376
Cannot access %!(EXTRA string=cilium.io, string=Exitcode: 52 
Stdout:
 	 000
Stderr:
 	 
)
Expected
    <string>: 000
to contain substring
    <string>: 301
/home/jenkins/workspace/Ginkgo-CI-Tests-Pipeline/src/github.com/cilium/cilium/test/runtime/Policies.go:916
Standard Output

Standard Error

STEP: Setting PolicyEnforcement=default
STEP: Importing policy with ToFQDN rules
STEP: Setting up policy: /home/vagrant/go/src/github.com/cilium/cilium/test/policy_e4be3d5b.json
STEP: Denying egress to IPs of non-ToFQDN DNS names that are looked up
STEP: Allowing egress to IPs of specified ToFQDN DNS names
=== Test Finished at 2018-08-01T20:30:32Z====
===================== TEST FAILED =====================
cmd: sudo cilium endpoint list
ENDPOINT   POLICY (ingress)   POLICY (egress)   IDENTITY   LABELS (source:key[=value])   IPv6                 IPv4            STATUS   
           ENFORCEMENT        ENFORCEMENT                                                                                     
10804      Disabled           Enabled           8809       container:id.app1             f00d::a0f:0:0:2a34   10.15.125.26    ready   
35651      Disabled           Disabled          31247      container:id.httpd2           f00d::a0f:0:0:8b43   10.15.175.180   ready   
                                                           container:id.service1                                                      
43992      Disabled           Disabled          4          reserved:health               f00d::a0f:0:0:abd8   10.15.63.46     ready   
52059      Disabled           Disabled          52044      container:id.httpd1           f00d::a0f:0:0:cb5b   10.15.16.175    ready   
                                                           container:id.service1                                                      
52446      Disabled           Disabled          43810      container:id.app2             f00d::a0f:0:0:ccde   10.15.13.208    ready   
56762      Disabled           Disabled          17310      container:id.httpd3           f00d::a0f:0:0:ddba   10.15.40.187    ready   
                                                           container:id.service1                                                      
60056      Disabled           Disabled          52931      container:id.app3             f00d::a0f:0:0:ea98   10.15.152.73    ready   

===================== Existing AfterFailed =====================
```

Logs: 
[3161702d_RuntimePolicies_Enforces_ToFQDNs_policy.zip](https://github.com/cilium/cilium/files/2251363/3161702d_RuntimePolicies_Enforces_ToFQDNs_policy.zip)

### PR DESCRIPTION
**Pull request by raybejjani**
Fixes #5071 

The test didn't wait for the second regeneration of policy, and so it would race. This meant it failed. I've added a more correct wait that ensures the DNS lookup has added IPs to the policy and regenerated.

Note: if this misses the 1.2 merge deadline, it should be backported to avoid this flake.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/5092)

### CODE REVIEW

**Comment by raybejjani** [comment]
test-me-please

File: test/runtime/Policies.go [hunk 1]
```diff
@@ -897,23 +899,38 @@ var _ = Describe("RuntimePolicies", func() {
     ]
   }
 ]`
-		_, err := vm.PolicyRenderAndImport(fqdnPolicy)
+		startPolicyRevision, err := vm.PolicyGetRevision()
+		Expect(err).To(BeNil(), "Unable to get start policy revision before policy import: %s", err)
```
Comment (eloycoto) [inline test/runtime/Policies.go]: You don't need to have the %s, err here. The assert will print the error :-)

**Comment by raybejjani** [comment]
test-me-please

File: test/runtime/Policies.go [hunk 2]
```diff
@@ -897,9 +899,24 @@ var _ = Describe("RuntimePolicies", func() {
     ]
   }
 ]`
-		_, err := vm.PolicyRenderAndImport(fqdnPolicy)
+		startPolicyRevision, err := vm.PolicyGetRevision()
+		Expect(err).To(BeNil(), "Unable to get start policy revision before policy import", err)
```
Comment (ianvernon) [inline test/runtime/Policies.go]: What is "start policy revision"? This error message is unclear. Please rephrase.

File: test/runtime/Policies.go [hunk 3]
```diff
@@ -897,9 +899,24 @@ var _ = Describe("RuntimePolicies", func() {
...
 		Expect(err).To(BeNil(), "Unable to import policy: %s", err)
 
+		// The DNS poll will update the policy and regenerate. Since this is the
+		// first ever update, we can simply check for the presence of toCIDRSet in
+		// the policy.
+		// Once we have an API to expose DNS->IP mappings we can also use that to
+		// ensure the lookup has completed more explicitly
+		timeout_s := 3 * fqdn.DNSPollerInterval / time.Second // convert to seconds
+		dnsWaitBody := func() bool {
+			return vm.PolicyWait(startPolicyRevision + 2).WasSuccessful()
```
Comment (ianvernon) [inline test/runtime/Policies.go]: This seems really hacky to me. Why can't we query the policy repository itself to wait for toCIDRSets within the policy rules to be updated? You imply this above, but then we simply wait for the revision number to increase by 2.

**Review by ianvernon — CHANGES_REQUESTED** [review]

**Comment by ianvernon** [comment]
@raybejjani will this need backport to v1.2?

File: test/runtime/Policies.go (hunk 3 above)
Comment (raybejjani) [reply test/runtime/Policies.go]: We can. It seemed like a wash to me. If I get the policy, I would have to parse it (it's json, I think) or simply search for the presence of a `ToCIDRSet` section. In the case where I parse it, I end up doing the same thing as the substring search (I don't know the IPs beforehand, so I can't check those). In both cases I would have to assume this test is the only one manipulating the policy repository.
In the case where I look at revisions, I know that there will be two additions to the policy repository, and so the revision would increment twice. I also have to assume that only this test is manipulating the policy repository, since any other modification would be bad and increment the policy revision.

I did, in fact, try the substring search method. It worked but seemed a little random, especially the string search I was doing.

File: test/runtime/Policies.go (hunk 2 above)
Comment (raybejjani) [reply test/runtime/Policies.go]: sure, I'll come up with a better name

**Comment by raybejjani** [comment]
@ianvernon yes, it does need a backport. I guess we already forked etc. I'll mark it.

File: test/runtime/Policies.go (hunk 3 above)
Comment (raybejjani) [reply test/runtime/Policies.go]: ok, we allow for setting an "id" on the policy, so I can grab the exact same one back. This is what it would look like. What do you think?
```golang
        It("Enforces ToFQDNs policy", func() {
                By("Importing policy with ToFQDN rules")
                testPolicyID := rand.Int()
                testPolicyIDString := fmt.Sprintf("toFQDNS-test-label=%d", testPolicyID)

                // notaname.cilium.io never returns IPs, and is there to test that the
                // other name does get populated.
                fqdnPolicy := fmt.Sprintf(`
[
  {
    "labels": [{
                        "key": "toFQDNS-test-label",
                        "value": "%d"
                }],
    "endpointSelector": {
      "matchLabels": {
        "container:id.app1": ""
      }
    },
    "egress": [
      {
        "toPorts": [{
          "ports":[{"port": "53", "protocol": "ANY"}]
        }]
      },
      {
        "toFQDNs": [
          {
            "matchName": "cilium.io"
          },
          {
            "matchName": "notaname.cilium.io"
          }
        ]
      }
    ]
  }
]`, testPolicyID)

                _, err := vm.PolicyRenderAndImport(fqdnPolicy)
                Expect(err).To(BeNil(), "Unable to import policy: %s", err)
                defer vm.PolicyDel(testPolicyIDString)

                // The DNS poll will update the policy and regenerate. Since this is the
                // first ever update, we can simply check for the presence of toCIDRSet in
                // the policy, and that the policy revision has incremented twice: once for
                // the policy insert, and another for the DNS IP updates to toCIDRSet.
                // Once we have an API to expose DNS->IP mappings we can also use that to
                // ensure the lookup has completed more explicitly
                timeout_s := 3 * fqdn.DNSPollerInterval / time.Second // convert to seconds
                dnsWaitBody := func() bool {
                        policyResult := vm.PolicyGet(testPolicyIDString)
                        if !policyResult.WasSuccessful() {
                                return false
                        }
                        policy := policyResult.GetStdOut()
                        return strings.Contains(policy, "toFQDNs") && strings.Contains(policy, "toCIDRSet")
                }
                err = helpers.WithTimeout(dnsWaitBody, "DNSPoller did not update IPs",
                        &helpers.TimeoutConfig{Ticker: 1, Timeout: timeout_s})

                Expect(vm.WaitEndpointsReady()).Should(BeTrue(), "Endpoints are not ready after ToFQDNs DNS poll triggered a regenerate")

                By("Denying egress to IPs of DNS names not in ToFQDNs, and normal IPs")
                // www.cilium.io has a different IP than cilium.io (it is CNAMEd as well!),
                // and so should be blocked.
                // cilium.io.cilium.io doesn't exist.
                // 1.1.1.1, amusingly, serves HTTP.
                for _, blockedTarget := range []string{"www.cilium.io", "cilium.io.cilium.io", "1.1.1.1"} {
                        res := vm.ContainerExec(helpers.App1, helpers.CurlFail(blockedTarget))
                        res.ExpectFail("Curl succeeded against blocked DNS name %s" + blockedTarget)
                }

                By("Allowing egress to IPs of specified ToFQDN DNS names")
                allowedTarget := "cilium.io"
                res := vm.ContainerExec(helpers.App1, helpers.CurlWithHTTPCode(allowedTarget))
                res.ExpectContains("301", "Cannot access %s %s", allowedTarget, res.OutputPrettyPrint())
        })
```

**Comment by raybejjani** [comment]
test-me-please

**Review by eloycoto — APPROVED** [review]

**Review by tgraf — APPROVED** [review]
