### PR TITLE
ctmap: Introduce variable conntrack gc interval

### LINKED ISSUE #7997: Conntrack garbage collector interval regression
Commit df8582d16e51792e62ef1a512a1c13a4fd6a8057 has introduced a regression by changing the default interval for LRU map based conntrack to 12h on the basis that the tables will automatically expire the oldest entries when filling up.

Unfortunately, walking the table to clean the conntrack stale podIPs on pod removal taints all entries. This causes to random conntrack entries being evicted while the table is full.

### PR DESCRIPTION
**Pull request by tgraf**
Commit df8582d16e5 ("datapath: Optimize connection-tracking GC interval") has
introduced a regression by changing the default interval for LRU map based
conntrack to 12h on the basis that the tables will automatically expire the
oldest entries when filling up.

Unfortunately, walking the table to clean the conntrack stale podIPs on pod
removal taints all entries. This causes to random conntrack entries being
evicted while the table is full.

Resolve this by adjusting the conntrack gc interval automatically based on the
number of entries deleted in the table with the most deletions.

Fixes: #7997

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/7999)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

File: pkg/endpointmanager/conntrack.go [hunk 1]
```diff
@@ -122,9 +112,10 @@ func EnableConntrackGC(ipv4, ipv6 bool, restoredEndpoints []*endpoint.Endpoint)
 
 	go func() {
 		for {
+			var maxDeleteRatio float64
```
Comment (joestringer) [inline pkg/endpointmanager/conntrack.go:115]: Shouldn't this be outside the `for { ...`?

File: pkg/maps/ctmap/ctmap.go [hunk 2]
```diff
@@ -550,3 +554,66 @@ func Exists(e CtEndpoint, ipv4, ipv6 bool) bool {
...
+	interval = prevInterval
+
+	switch {
+	case maxDeleteRatio > 0.25:
+		if maxDeleteRatio > 0.9 {
+			maxDeleteRatio = 0.9
+		}
+		// 25%..90% => 1.3x..10x
+		interval = time.Duration(float64(interval) * (1.0 - maxDeleteRatio))
+		if interval > defaults.ConntrackGCMinInterval {
```
Comment (joestringer) [inline pkg/maps/ctmap/ctmap.go]:
```suggestion
		if interval < defaults.ConntrackGCMinInterval {
```

File: pkg/maps/ctmap/ctmap.go [hunk 3]
```diff
@@ -550,3 +554,66 @@ func Exists(e CtEndpoint, ipv4, ipv6 bool) bool {
...
+
+func calculateInterval(mapType bpf.MapType, prevInterval time.Duration, maxDeleteRatio float64) (interval time.Duration) {
+	interval = prevInterval
+
+	switch {
+	case maxDeleteRatio > 0.25:
+		if maxDeleteRatio > 0.9 {
+			maxDeleteRatio = 0.9
+		}
+		// 25%..90% => 1.3x..10x
```
Comment (joestringer) [inline pkg/maps/ctmap/ctmap.go]:
```suggestion
		// 25%..90% => 1.3x..10x shorter
```

File: pkg/maps/ctmap/ctmap.go [hunk 4]
```diff
@@ -550,3 +554,66 @@ func Exists(e CtEndpoint, ipv4, ipv6 bool) bool {
...
+			interval = defaults.ConntrackGCMinInterval
+		}
+
+	case maxDeleteRatio < 0.05:
+		// When less than 5% of entries were deleted, increase the
+		// interval. Do not assume that less than 1% were deleted.
+		if maxDeleteRatio < 0.01 {
+			maxDeleteRatio = 0.01
+		}
+		// 5%..1% => 2x..10x
```
Comment (joestringer) [inline pkg/maps/ctmap/ctmap.go]:
```suggestion
		// 5%..1% => 2x..10x longer
```

**Review by joestringer — CHANGES_REQUESTED** [review]
I posted some minor feedback below. It's hard to tell how well these particular heuristic values will work in practice without some experience with them. I've opted not to think too deeply about them just yet.

A couple of questions for if this doesn't work as intended in some environments:

* Can we turn this off?
* Can we tweak the ratio thresholds/aggressiveness (even if such configuration is typically hidden from users)?

File: pkg/maps/ctmap/ctmap.go (hunk 2 above)
Comment (tgraf) [reply pkg/maps/ctmap/ctmap.go]: Good catch, added test

File: pkg/endpointmanager/conntrack.go (hunk 1 above)
Comment (tgraf) [reply pkg/endpointmanager/conntrack.go:115]: The delete ratio is calculated for each run. It's initialized there to make sure it is 0.0 for the per endpoint CT tables. That said, there was a check missing to skip the adjustment if the delete ratio is 0.0. I've added that.

**Comment by tgraf** [comment]
> * Can we turn this off?

Good point. I've changed it so that when users define `--conntrack-gc-interval`, no adjustment is made.

> * Can we tweak the ratio thresholds/aggressiveness (even if such configuration is typically hidden from users)?

What would you like to see?

**Comment by tgraf** [comment]
test-me-please

File: pkg/maps/ctmap/ctmap.go [hunk 5]
```diff
@@ -550,3 +554,72 @@ func Exists(e CtEndpoint, ipv4, ipv6 bool) bool {
...
+				interval = defaults.ConntrackGCMaxLRUInterval
+			}
+		default:
+			if interval > defaults.ConntrackGCMaxInterval {
+				interval = defaults.ConntrackGCMaxInterval
+			}
+		}
+	}
+
+	if interval != prevInterval {
```
Comment (aanm) [inline pkg/maps/ctmap/ctmap.go:613]: To avoid this condition from being true more times than necessary, round or truncate `interval` to the second, or even, to the minute. (Or switch the `Info` to `Debug`)

**Review by aanm — CHANGES_REQUESTED** [review]

File: pkg/maps/ctmap/ctmap.go (hunk 5 above)
Comment (tgraf) [reply pkg/maps/ctmap/ctmap.go:613]: Very good point 👍

**Comment by tgraf** [comment]
@aanm @joestringer Feedback addressed. I've changed the interval growing algorithm to apply a static multiplier of 1.3x to ensure it grows slowly enough in the beginning as new nodes often have no workloads for the first couple of minutes.

The shrinking is still very aggressive with up to 10x reduction if 90% of the table has been deleted.

**Comment by tgraf** [comment]
test-me-please

**Review by aanm — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
test-docs-please

**Comment by tgraf** [comment]
test-me-please

**Comment by joestringer** [comment]
>>  Can we tweak the ratio thresholds/aggressiveness (even if such configuration is typically hidden from users)?
> What would you like to see?

I was thinking the threshold values themselves, just in case we end up in some weird oscillating pattern because of the particular patterns of connections we see. The effectiveness of these values is very environment-dependent. That said, as long as we can turn this off on demand, that should provide sufficient configurability to work around any such problems in practice.

**Review by joestringer — APPROVED** [review]

**Comment by tgraf** [comment]
test-me-please
