### PR TITLE
Pass vlan tagged packets back to the kernel stack.

### LINKED ISSUE #14579: NodePort doesn't work correctly when VLANs are involved
## Bug report

Cilium version: `1.9.1`
Kernel: `5.9.0-0.bpo.2-amd64`

If you have an interface, say `enp36s0f0`, for internal traffic and than `enp36s0f0.10` (that is tagged VLAN on the same physical interface) for external traffic than if the traffic is coming from the external side and is routed into internal, POD ips can be accessed, but NodePort (and anything that relies on them) does not work.

I have originally asked about this on slack, here is the original question 192.168.55.0/24 network is on the tagged VLAN interface (enp36s0f0.10) and 192.168.46.0/24 is on the untagged one (enp36s0f0):

i have two networks (192.168.46.0/24 and 192.168.55.0/24) - the kubernetes cluster with cilium is in the 46 network - there is a router (with 192.168.46.1 and 192.168.55.124 as ip addresses) which doubles as control plane node, one normal worker node (192.168.46.10) and i also have one computer in 46 network, that is not running kubernetes or any cilium daemons (192.168.46.200) - the default gw in the 55 knows to route 46 network as well as POD CIDR (10.92.0.0/16) through 192.168.55.124
Now i try to create NodePort service - POD is running on the worker node (.46.10). externalTrafficPolicy: Cluster. I see that cilium creates all the correct services (cilium service list) and it got port - 30698
Now from the .46.1 computer i can access this service on all addresses (192.168.46.1:30698, 192.168.55.124:30698, 192.168.46.10:30698), same on the .46.10 worker node and same for the .46.200 (which has .46.1 as default gw, but is not running any kubernetes or cilium)
But if i try to access this NodePort service from the 192.168.55.0/24 network, it doesn't work as expected. I can access the service on 192.168.46.10:30698 but i can't access the NodePort service neither on 192.168.55.124:30698 or 192.168.46.1:30698.

### PR DESCRIPTION
**Pull request by kvaster**
VLAN packets will be catched with bpf on main interface first. We
need to passs it back to the kernel stack. VLAN info/tag will be stripped and
packet will be reenqueued on proper interface or dropped.

Also we do not need to process VLAN packets on egress, cause either
we've already processed such packets in case bpf program is attached
to VLAN interface or we do not need to process such packets at all in
other way.

VLAN tagged packets will be processed in the folowing way:
* If vlan tag is zero packet will be processed as usual (cause it is targeted for main interface)
* For each device will be allowed only corresponding vlan tags.
* By default will be allowed only tags from devices controlled by cilium.
* Any other tags may be allowed via option (`--vlan-bpf-bypass`), `--vlan-bpf-bypass 0` may be used for allowing all available vlan tags.
* All other vlan tags will be always dropped for security reason.

Concerns:
* Probably ifindexes and vlan tags should be sorted to make configuration predictable.
* Probably something like `*` should be used insteadof `0` for allowing all available vlan tags.

Previous pull request and discussion: https://github.com/cilium/cilium/pull/15534

Fixes: cilium#14579

Signed-off-by: Viktor Kuzmin <kvaster@gmail.com>

```release-note
Make NodePort BPF to work on VLAN devices
```

### CODE REVIEW

File: pkg/datapath/linux/config/config.go [hunk 1]
```diff
@@ -549,6 +555,63 @@ func (h *HeaderfileWriter) WriteNodeConfig(w io.Writer, cfg *datapath.LocalNodeC
...
+		vlan, ok := l.(*netlink.Vlan)
+		// if it's vlan device and we're controlling vlan main device
+		// and either all vlans are allowed, or we're controlling vlan device or vlan is explicitly allowed
+		if ok && devices[vlan.ParentIndex] && (allowedVlans[0] || devices[vlan.Index] || allowedVlans[vlan.VlanId]) {
+			vlansByIfIndex[vlan.ParentIndex] = append(vlansByIfIndex[vlan.ParentIndex], vlan.VlanId)
+		}
+	}
+
+	if len(vlansByIfIndex) == 0 {
+		return "return CTX_ACT_DROP;", nil
```
Comment (twpayne) [inline pkg/datapath/linux/config/config.go]: The description of the `--bpf-allow-vlan` flag is "List of explicitly allowed VLAN IDs, zero will allow all VLAN IDs", but won't the `CTX_ACT_DROP` here mean that zero will allow *no* VLAN IDs? i.e. should this be a `CTX_ACT_OK` instead?

**Comment by twpayne** [comment]
Please can you add a release note to the PR description, [as documented in step 11 here](https://docs.cilium.io/en/v1.10/contributing/development/contributing_guide/#submitting-a-pull-request).

File: pkg/datapath/linux/config/config.go (hunk 1 above)
Comment (kvaster) [reply pkg/datapath/linux/config/config.go]: Bad description. I will correct - `--bpf-allow-vlan 0` means all VLAN IDs.

**Comment by kvaster** [comment]
fixed!

File: pkg/datapath/linux/config/config.go (hunk 1 above)
Comment (kvaster) [reply pkg/datapath/linux/config/config.go]: And some notices: `len(vlansByIfIndex) == 0` is true only when there is no any vlan device corresponding to main devices. By default all vlan devices are added if they are controlled by cilium. But there might be case when there will be vlan devices wich are not controlled by cilium - in this case we can pass option - `--bpf-allow-vlan 4000,4001` or allow all vlan devices - `--bpf-allow-vlan 0`

**Comment by twpayne** [comment]
test-me-please

**Comment by kvaster** [comment]
I've update PR to fix some CI problems - cmdref docs.

**Comment by kvaster** [comment]
Any updates ?

**Review by twpayne — APPROVED** [review]
Looks good from a CLI perspective, but I need the experienced datapath folk to review the datapath aspects.

File: pkg/datapath/linux/config/config.go [hunk 2]
```diff
@@ -549,6 +555,63 @@ func (h *HeaderfileWriter) WriteNodeConfig(w io.Writer, cfg *datapath.LocalNodeC
 	return fw.Flush()
 }
 
+// vlanFilterMacros generates VLAN_FILTER macros which
+// are written to node_config.h
+func vlanFilterMacros() (string, error) {
```
Comment (joestringer) [inline pkg/datapath/linux/config/config.go:560]: Is there a way to unit test this logic?

Comment (joestringer) [reply pkg/datapath/linux/config/config.go:560]: One path for this would be, do something similar to existing privileged unit tests, involving creating dummy devices and so on so that the code can actually perform queries against a configured Linux system, and then generate appropriate output. Then make sure that it picks up the appropriate devices depending on whether we're controlling the main device or not.

Separately there's also the question of whether the output of this function is valid C, ideally we could either lint or even compile a snippet as part of automated testing. Maybe at this point we're not really talking unit tests but more of an integration test.

In future maybe we could even support dynamically configured VLANs and we could test that support.

File: daemon/cmd/daemon_main.go [hunk 3]
```diff
@@ -980,6 +980,9 @@ func init() {
 	flags.Bool(option.ExternalClusterIPName, false, "Enable external access to ClusterIP services (default false)")
 	option.BindEnv(option.ExternalClusterIPName)
 
+	flags.IntSlice(option.BPFAllowVLAN, []int{}, "List of explicitly allowed VLAN IDs, '0' id will allow all VLAN IDs")
```
Comment (joestringer) [inline daemon/cmd/daemon_main.go]: Could we just treat the empty list as allow all?

So basically if you don't configure the option, the behaviour is exactly the same as today: No filtering at all. If you configure the option, you are writing an explicit list of VLANs to allow.

File: pkg/option/config.go [hunk 4]
```diff
@@ -950,6 +950,9 @@ const (
 	// ExternalClusterIPName is the name of the option to enable
 	// cluster external access to ClusterIP services.
 	ExternalClusterIPName = "bpf-lb-external-clusterip"
+
+	// BPFAllowVLAN instructs Cilium to allow vlan targeted packets
+	BPFAllowVLAN = "bpf-allow-vlan"
```
Comment (joestringer) [inline pkg/option/config.go]: I think we need a clearer name and semantics on this. Until I got to the review of the actual code being generated, I was under the impression that this functionality was a filter in the policy sense: Ie, decide when to drop things, using an inclusion list.

In practice what it's configuring is a bypass of Cilium logic. Maybe something like "vlan-bpf-bypass" or "vlan-bpf-skip"?

File: bpf/bpf_host.c [hunk 5]
```diff
@@ -997,8 +1012,18 @@ int to_netdev(struct __ctx_buff *ctx __maybe_unused)
...
 	__u32 monitor = 0;
+	__u32 __maybe_unused vlan_id;
 	int ret = CTX_ACT_OK;
 
+	/* Filter allowed vlan id's and pass them back to kernel.
+	 */
+	if (ctx->vlan_present) {
+		vlan_id = ctx->vlan_tci & 0xfff;
+		if (vlan_id) {
+			VLAN_FILTER(ctx->ifindex, vlan_id);
```
Comment (joestringer) [inline bpf/bpf_host.c]: I'd like to make sure we don't break existing behaviour here. It looks to me like by default if the user has not configured the option, we will now start dropping all vlan-tagged traffic. Maybe we need to differentiate between whether the option is enabled (which enables default drop for vlan-tagged traffic) vs. not configured (which should have no behaviour change)?

File: bpf/bpf_host.c [hunk 6]
```diff
@@ -968,6 +972,17 @@ handle_netdev(struct __ctx_buff *ctx, const bool from_host)
...
 int from_netdev(struct __ctx_buff *ctx)
 {
+	__u32 __maybe_unused vlan_id;
+
+	/* Filter allowed vlan id's and pass them back to kernel.
+	 */
+	if (ctx->vlan_present) {
+		vlan_id = ctx->vlan_tci & 0xfff;
+		if (vlan_id) {
+			VLAN_FILTER(ctx->ifindex, vlan_id);
```
Comment (joestringer) [inline bpf/bpf_host.c]: nit: As a matter of style, it's difficult to understand the implications of this `VLAN_FILTER` unless you know the details of how it works (which is autogenerated, so even harder to understand). Can we make this more explicit in the coding here?

```
ret = VLAN_FILTER(...)
if (ret < 0) {
 // .... drop path
} else if (ret > 0) {
  // ... bypass path
}
```

(Or switch case if you prefer, the point is not to hijack the execution logic via macro)

File: pkg/datapath/linux/config/config.go [hunk 7]
```diff
@@ -549,6 +555,63 @@ func (h *HeaderfileWriter) WriteNodeConfig(w io.Writer, cfg *datapath.LocalNodeC
...
+			`switch (ifindex) { \
+{{range $ifindex,$vlans := . -}} case {{$ifindex}}: { \
+switch (vlan_id) { \
+{{range $vlan := $vlans -}} case {{$vlan}}:{{end}} \
+return CTX_ACT_OK; \
+} \
+break; \
+} {{end}} \
+} \
+return CTX_ACT_DROP;`))
```
Comment (joestringer) [inline pkg/datapath/linux/config/config.go]: Naked drops like this will be hard to trace. Usually whenever we return a drop error code, we also `send_drop_notify(...)` with a dedicated drop code indicating the intent of _why_ we dropped this packet in this case. We probably need a new `DROP_VLAN_FILTERED` error code in `bpf/lib/common.h` and a good error message in `pkg/monitor/api/drop.go`, maybe something like "VLAN traffic disallowed by VLAN filter".

Could you update all of the `CTX_ACT_DROP` cases here to also send a drop notification?

Comment (joestringer) [reply pkg/datapath/linux/config/config.go]: (Note, usually this is handled by the outer code once you return an error code back up the stack... but with the current datapath implementation in this PR, this logic is invoked from the top level so there is no code which would catch the error and perform the send_drop_notify).

**Review by joestringer — CHANGES_REQUESTED** [review]
This seems much closer to striking the right balance between providing the configurability you're looking for without surprising users too much with traffic bypassing Cilium logic.

I've requested a few changes below to make the change easier to reason about, both from a user perspective (semantics/naming and traceability) but also from a developer perspective (make it super simple to follow the flow of logic, test it so we can be sure that different variations of the option produce the desired behaviour).

The only thing I didn't raise below is the complexity concern. I strongly suspect that if you configure too many VLANs in this option, bpf program load will fail and the Cilium container will crash out because it cannot configure the datapath in the way you have requested. This could happen either when you first enable the option (because you specified too many tags), or it could plausibly happen later on when you upgrade to a new release, because each release can change the datapath. When you upgrade, there could be just enough additional BPF instructions introduced by this logic that when combined with the rest of the new datapath logic, it pushes the program complexity over some limit. I don't know where that limit is, and this PR is not proposing any testing for it. For now if this is a super-advanced option, maybe you're willing to take on that risk and deal with the consequences / roll back & report issues upstream when you hit them during upgrade. But we may want to think a bit more about integration testing and how we can detect such problems earlier in the development cycle so we can start the discussions early on how to address them.

File: pkg/datapath/linux/config/config.go (hunk 2 above)
Comment (kvaster) [reply pkg/datapath/linux/config/config.go:560]: Unfortunatelly I have no good experiance with cilium yet and I think it will take much time for me to write such tests... The output of this function is valid C.

File: daemon/cmd/daemon_main.go (hunk 3 above)
Comment (kvaster) [reply daemon/cmd/daemon_main.go]: I think, no, according to talks on previous pull request. Today's behaviour doesn't mean 'allow all'. Today's behaviour is broken - cilium treats any vlan tagged packets as packets without tag and may take packet from main interface and resend to another node (for example) from vlan tagged interface and this will add one more vlan tag -> packet processing will be broken. Current behaviour does not work at all with vlan tagged packets.

File: bpf/bpf_host.c (hunk 5 above)
Comment (kvaster) [reply bpf/bpf_host.c]: As I wrote earlier, keeping existing behavious make no sense, cause current behaviour makes malformed packets with vlan tags involved.

File: bpf/bpf_host.c (hunk 6 above)
Comment (kvaster) [reply bpf/bpf_host.c]: Will make changes!

File: pkg/datapath/linux/config/config.go (hunk 2 above)
Comment (joestringer) [reply pkg/datapath/linux/config/config.go:560]: Would you be up for trying to do at least some minimal tests like configure a specific set of VLAN devices, then run this logic, then check that the output of the function is detecting the correct devices?

There's some fairly basic "create devices" type logic in `pkg/datapath/link/link_test.go`, you would need to go a bit further to create the appropriate VLAN devices. The docs have some examples about how you can run those individual privileged tests to validate the behaviour locally[0].

[0] https://docs.cilium.io/en/latest/contributing/testing/unit/#testing-individual-packages

Comment (kvaster) [reply pkg/datapath/linux/config/config.go:560]: Ok. Thanks. I will do.

File: daemon/cmd/daemon_main.go (hunk 3 above)
Comment (joestringer) [reply daemon/cmd/daemon_main.go]: OK, in that case if it's pretty broken today then it'd be better to drop early here with clear drop notifications so if someone configures this way, they at least get a more obvious failure they can investigate rather than just weird packets turning up in unexpected places. :+1:

File: pkg/datapath/linux/config/config.go [hunk 8]
```diff
@@ -549,6 +555,63 @@ func (h *HeaderfileWriter) WriteNodeConfig(w io.Writer, cfg *datapath.LocalNodeC
...
+		ifindex, err := link.GetIfIndex(device)
+		if err != nil {
+			return "", err
+		}
+		devices[int(ifindex)] = true
+	}
+
+	allowedVlans := make(map[int]bool)
+	for _, vlanId := range option.Config.BPFAllowVLAN {
+		allowedVlans[vlanId] = true
```
Comment (joestringer) [inline pkg/datapath/linux/config/config.go]: One way to make the "allow all" logic a bit nicer would be to just support "all" as one of the options for the flag. If "all" shows up in this list then rather than iterating the devices and generating a list of specific VLANs to pass through, we can generate `return CTX_ACT_OK` if any VLAN is set.

**Comment by kvaster** [comment]
From my point of view it's rather safe to just bypass any non-zero vlan tag to kernel and allow it to do it's job, bit cilium policy is to control everything on devices controlled by cilium. In 99% there will be no or 1-2 vlan tags for 1-2 devices. But maybe it's a good idea to generate just `return CTX_ACT_OK` if 'all' vlans are requested.

File: pkg/option/config.go (hunk 4 above)
Comment (kvaster) [reply pkg/option/config.go]: I was thinking about `vlan-bpf-bypass` first, but current logic will malform vlan tagged packets and we need to drop or to bypass them to kernel. Think I need help in this question :)

File: bpf/bpf_host.c [hunk 9]
```diff
@@ -37,6 +37,10 @@
  */
 #define SKIP_ICMPV6_ECHO_HANDLING
 
+#ifndef VLAN_FILTER
+# define VLAN_FILTER(ifindex, vlan_id) return CTX_ACT_DROP;
```
Comment (joestringer) [inline bpf/bpf_host.c]: You might want to consider adding a more complex default in the `bpf/node_config.h` file. That file is only used for testing, and is used in existing verifier tests. So if you define `VLAN_FILTER(...)` there with the most common configuration you would expect (could be 1-2 or maybe even 5 VLAN tags), then this would help us to catch potential verifier issues for common use cases before we release & you deploy them.

Comment (kvaster) [reply bpf/bpf_host.c]: Common configuration from my point of view is one main device and one vlan device - internal and external networks. We faced that problem with our setup on hetzner datacenter. Telling the truth, I can't imaging configuration with lot's of vlan devices for kubenetes.

**Comment by kvaster** [comment]
Thanks for comments. Will get back tomorrow with changes.

File: pkg/option/config.go (hunk 4 above)
Comment (joestringer) [reply pkg/option/config.go]: I think that technically there's two changes occurring in this PR:
a) Resolve the "malformed VLAN-tagged packets issue" by dropping packets with VLAN tags.
b) Provide a configuration option to bypass Cilium BPF logic.

(a) is basically a new default and I reason above[[link][0]] that this will just make it easier to detect when VLAN misconfiguration is causing issues in your network. (b) is then saying, if you know how the Linux stack is configured to handle VLAN traffic and you're OK with the implications, then you can teach Cilium to bypass its BPF logic for VLAN traffic.

I feel like longer term there is probably a more cohesive solution that involves teaching Cilium more about the overall VLAN configuration in your network and reasoning about the overall system + Cilium's part in it. But for now this combination of (a) / (b) should be enough to unblock what you're trying to do. And I'd argue that (b) is really what the configuration option is about.

[0]: https://github.com/cilium/cilium/pull/16772#discussion_r668158630

Comment (kvaster) [reply pkg/option/config.go]: Hm. It should be a good 'fix' for those who require vlan's. I will remove this complex logic and will make bpf drop or bypass all vlan tags depending on option with default to drop. Thanks for comments, will get back soon.

File: bpf/bpf_host.c (hunk 9 above)
Comment (joestringer) [reply bpf/bpf_host.c]: :+1: Given that VLANs have so much legacy usage, I suspect that in users own datacenters, additional use cases could come up with any number of VLAN configurations. I also note that by default this kind of configuration is configured once for the entire k8s cluster via cilium-config ConfigMap, and in the code here we configure it once for the entire node by generating the code into `node_config.h`. There's no sort of mapping between specific devices and specific VLAN tags. This means that the overall complexity is determined by the total number of VLAN tags that you expect your k8s cluster to encounter, and most likely every device on every node will have the same configuration.

If this is OK with you, then I see this as an acceptable limitation of the current proposed approach. If the community wants to drive a better solution in future we can always enhance the logic. On the other hand, if this is surprising to you and you expect to encounter issues with this as-is, then let's identify those issues and make sure this proposal is at least addressing your use case.

Comment (kvaster) [reply bpf/bpf_host.c]: Think that idea with just allow or drop all vlan tagged packets with default to drop is better for now. It will defenitely solve problems with vlan we're having. Also I think that 'vlan aware' part of community isn't too big and this approach will suite everybody with such problem.

Comment (kvaster) [reply bpf/bpf_host.c]: Also such approach will make much less changes to datapath.

**Comment by kvaster** [comment]
I've updated PR according to requests. I was going to make it drop or allow all vlans with default to drop, but it's really bad idea, cause it may break connectivity (broken connections to k8s api services at my place). I've added small tests and also some restrictions on number of vlan id's. User will see proper error in case number of vlan id's will be more then few allowed. In that case user should explicitly allow all vlan id's - in that case generated function will be very small.

**Comment by joestringer** [comment]
> I was going to make it drop or allow all vlans with default to drop, but it's really bad idea, cause it may break connectivity (broken connections to k8s api services at my place).

Can you elaborate a bit more on what occurred here? What configuration did you provide and how did that break k8s apiserver connectivity? This type of feedback from testing is often a sign that there's an upgrade impact for the PR.

**Comment by kvaster** [comment]
> > I was going to make it drop or allow all vlans with default to drop, but it's really bad idea, cause it may break connectivity (broken connections to k8s api services at my place).
> 
> Can you elaborate a bit more on what occurred here? What configuration did you provide and how did that break k8s apiserver connectivity? This type of feedback from testing is often a sign that there's an upgrade impact for the PR.

For hetzner setup we have internal network on vlan and api servers are listening on vlan devices. With default to drop all vlan tagged packets none packets can reach api server. Default behaviour will malform packets which are balanced to k8s pods, but will not touch packets not intended for k8s.

**Comment by kvaster** [comment]
That's why I decided not to change behaviour of my PR. With current code all is working as expected from user perspective.

File: bpf/bpf_host.c [hunk 10]
```diff
@@ -968,6 +976,21 @@ handle_netdev(struct __ctx_buff *ctx, const bool from_host)
...
 int from_netdev(struct __ctx_buff *ctx)
 {
+	__u32 __maybe_unused vlan_id;
+
+	/* Filter allowed vlan id's and pass them back to kernel.
+	 */
+	if (ctx->vlan_present) {
+		vlan_id = ctx->vlan_tci & 0xfff;
+		if (vlan_id) {
+			if (allow_vlan(ctx->ifindex, vlan_id))
```
Comment (joestringer) [inline bpf/bpf_host.c:986]: If I follow correctly, by default during upgrade, the new `--vlan-bpf-bypass` will be empty, which means that we will generate something like `#define VLAN_FILTER(x, y) { return false; }`. From your recent update on the main PR text, it sounds like this was the cause of your connectivity issue with your apiserver.

This sounds like the new default can break some connectivity in the network, which is not OK. That suggests that this entire new section needs to be conditionally run iff `--vlan-bpf-bypass` is configured.

Comment (joestringer) [reply bpf/bpf_host.c:986]: Basically the "drop unconfigured VLANs" logic is OK if and only if there is no way for VLAN traffic to successfully reach its destination today. If some VLAN traffic may reach its destination but other VLAN traffic may end up malformed somewhere else on the network, then changing this code to drop VLAN-tagged traffic by default could cause existing setups to break. We don't want to change this behaviour and arbitrarily break some setups with the default configuration.

Comment (kvaster) [reply bpf/bpf_host.c:986]: Sorry for my bad english...

`--vlan-bpf-bypass` will be empty by default, but empty does not mean 'block everything'. Empty allows vlan id's used by devices controlled by cilium. I've tried separately logic with just blocking everything and it's not good.

Comment (joestringer) [reply bpf/bpf_host.c:986]: I worry that we are making this more complex than necessary for the default case to support this specific use case, and I'm already having trouble understanding the implications of the default behaviour with the PR right now.

The lowest-risk option here is to make no changes at all by default. So empty means do not try any special handling for the VLANs. Don't drop, don't bypass. Then separately, if you want "bypass for assigned devices" and/or "drop VLAN-tagged traffic coming in if it's not recognized or part of a list" then you can enable this shiny new option.

Comment (kvaster) [reply bpf/bpf_host.c:986]: Just to clarify: current PR logic have no known for me issues.

Comment (joestringer) [reply bpf/bpf_host.c:986]: @kvaster Are you configuring the new option? What about if you don't configure the new option?

Comment (kvaster) [reply bpf/bpf_host.c:986]: @joestringer, my PR will always allow vlan id's used by devices controlled by cilium - by default traffic will be not blocked and will be controlled by cilium. You need to configure this option only if you have additional vlan devices which are not controlled by cilium (have bpf programs attached).

Comment (kvaster) [reply bpf/bpf_host.c:986]: That means defaults with this PR (without configuring new option) should be enough for all reported cases in issue and should not break security.

Comment (joestringer) [reply bpf/bpf_host.c:986]: > my PR will always allow vlan id's used by devices controlled by cilium - by default traffic will be not blocked and will be controlled by cilium. 

When you say "allow" here, do you mean `return CTX_ACT_OK`, ie "bypass Cilium logic"? That's the security concern I had in the previous issue that I was looking to avoid changing by default.

Comment (kvaster) [reply bpf/bpf_host.c:986]: Yes, I mean `return CTX_ACT_OK`. And it will not bypass cilium logic, cause in this case packet will be processed by cilium by bpf program attached to vlan device - only vlan id's that will be processed by cilium are allowed by default... Generally we just don't care if we have additional devices and bpf programs are not attached to them. To make it proper we will have to rewrite vlan logic in bpf, but personally I think this is too much. Without such changes cilium will malform vlan tagged packets when attached to main device (to which vlan devices attached), cause it should not process such packets. And blocking every vlan tagged packet will lead to broken connectivity without possibility to investigate problem - probably this will happen only on first setup before users will know that they should explicitly allow vlan bpf bypass, but it will be hard to understand what is happening. I think that somebody from cilium team should decide what kind of behaviour is OK. I don't understand what can be done more to fix this issue properly. Thanks.

Comment (joestringer) [reply bpf/bpf_host.c:986]: > And it will not bypass cilium logic, cause in this case packet will be processed by cilium by bpf program attached to vlan device 

I think you're basically saying, this logic is only bypassing Cilium BPF if it can identify that there is a VLAN device behind which will handle the traffic. I missed the nuance there initially, and at least in principle I agree that this mitigates the security concern we raised earlier since we have basically made a check to ensure that the traffic will be handled by Cilium after we skip processing.

My next question is, how do we know that the Cilium BPF program attached to the VLAN device is actually handling the traffic? Today the change is implemented through directly modifying `from_netdev()` / `to_netdev()` which is presumably used for both the BPF program on the main device and also on the VLAN device. Does this work because `ctx->vlan_present` is true only for VLAN packets arriving on the main device and it's false for decapsulated packets arriving on the vlan device?

File: pkg/datapath/linux/config/config_test.go [hunk 11]
```diff
@@ -245,3 +248,93 @@ func assertKeysInsideMap(c *C, m map[string]uint32, keys []string, want bool) {
...
+case 4004: \
+return true; \
+} \
+break; \
+} \
+return false;`, main1.Index, main2.Index))
+
+	option.Config.VLANBPFBypass = []int{4002, 4004, 4005}
+	m, err = vlanFilterMacros()
+	c.Logf("macros: %s", m)
```
Comment (joestringer) [inline pkg/datapath/linux/config/config_test.go]: It'd be good to turn this into a proper validation rather than a log message as well. `Logf()` doesn't do any testing and just makes the unit test output more noisy.

File: bpf/bpf_host.c (hunk 10 above)
Comment (kvaster) [reply bpf/bpf_host.c:986]: Yes, it will work cause kernel will strip vlan tag and will process packet on vlan device - and bpf will process such packet cause vlan_present will be false already.

File: pkg/datapath/linux/config/config_test.go (hunk 11 above)
Comment (kvaster) [reply pkg/datapath/linux/config/config_test.go]: Oh, this log message was added my mistake, I will update PR. We just need to test for error here.

Comment (kvaster) [reply pkg/datapath/linux/config/config_test.go]: PR updated.

File: bpf/bpf_host.c (hunk 10 above)
Comment (kvaster) [reply bpf/bpf_host.c:986]: Also please note that allow_vlan function have ifindex argument. And if, for example, we will receive packet with double vlan tags then first one will be stripped, packet will be redirected for processing on vlan device and will be dropped there by allow_vlan function, cause no vlan tag is allowed on vlan device.

**Review by joestringer — APPROVED** [review]
I think this is good at this point, though I'd welcome additional review from others.

There's a couple of rough edges - No automatic adjustment for new VLAN devices showing up on the node, so you'd have to restart the Cilium agent. And if there are many VLAN devices on the node under a main VLAN device that's Cilium-managed then the user will be forced to configure this new option upon upgrade.. but I think that's probably within the bounds of reason. We can always continue to improve on this, I don't think these are grounds to hold up the whole fix.

**Comment by joestringer** [comment]
@kvaster it looks like some of the initial linters have failed here:
* https://github.com/cilium/cilium/actions/runs/1029250653
* https://github.com/cilium/cilium/actions/runs/1029250652

The first seems to be some complaint about the proto api, while the second one failed to deploy Cilium successfully. You should be able to grep around in `.github` using the names of the tests (or part of the names) to find which commands are being run to try to reproduce locally.

**Comment by kvaster** [comment]
Oh. Thanks. I will fix all this problems right now!

**Comment by kvaster** [comment]
Updated PR with fixes for generated apis.

File: bpf/bpf_host.c [hunk 12]
```diff
@@ -968,6 +976,21 @@ handle_netdev(struct __ctx_buff *ctx, const bool from_host)
 __section("from-netdev")
 int from_netdev(struct __ctx_buff *ctx)
 {
+	__u32 __maybe_unused vlan_id;
+
+	/* Filter allowed vlan id's and pass them back to kernel.
+	 */
+	if (ctx->vlan_present) {
```
Comment (brb) [inline bpf/bpf_host.c:983]: Have you checked whether this whole if-statement gets optimized away by the compiler if no vlans are specified? If not, then we would need to wrap this into #ifdef.

**Review by brb — CHANGES_REQUESTED** [review]

File: bpf/bpf_host.c (hunk 12 above)
Comment (kvaster) [reply bpf/bpf_host.c:983]: vlan_allow function is always inline and it defenitely will be optimized, cause the code will look like:

```
if (false) {
  return CTX_ACT_OK;
} else {
  return send_drop_notifiy(...);
}
```

But don't know how to check this...

Comment (brb) [reply bpf/bpf_host.c:983]: You can use `llvm-objdump -S`. You can find the relevant object file it in `/var/run/cilium/state`. If it's not optimized, maybe the verifier will remove the branch. For this `bpftool prog dump` is useful.

Comment (kvaster) [reply bpf/bpf_host.c:983]: Thanks. I will check this and will get back to you. Meanwhile checking all other changes for 'problems' will be appreciated :)

Comment (brb) [reply bpf/bpf_host.c:983]: The rest LGTM. I'd appreciate if you would come up with a testing strategy too.

Comment (kvaster) [reply bpf/bpf_host.c:983]: I'm testing locally on VM's, but my install is specific - gentoo linux... I think only testing on VM's will help here, but to write such test will need to learn a lot about cilium's testing infastructure...

Comment (kvaster) [reply bpf/bpf_host.c:983]: I've checked - llvm-objdump is showing that this function is always optimized. If statements are removed in case they are not needed (always false or always true).

Comment (kvaster) [reply bpf/bpf_host.c:983]: Marking this conversation as resolved cause of this:

```
       4:	54 01 00 00 ff 0f 00 00	w1 &= 4095
       5:	16 01 1b 00 00 00 00 00	if w1 == 0 goto +27 <LBB6_6>
       6:	b4 01 00 00 02 00 00 00	w1 = 2
       7:	63 16 40 00 00 00 00 00	*(u32 *)(r6 + 64) = r1
       8:	b4 01 00 00 4a ff ff ff	w1 = -182
       9:	63 16 38 00 00 00 00 00	*(u32 *)(r6 + 56) = r1
      10:	b4 01 00 00 00 00 00 00	w1 = 0
```

We can see that there is no ACT_OK return here. Function is optimized.

**Comment by joestringer** [comment]
@kvaster I think you need to rebase against the latest master tree to fix up the CI failures.

**Comment by kvaster** [comment]
> @kvaster I think you need to rebase against the latest master tree to fix up the CI failures.

Thanks. Done...

**Comment by joestringer** [comment]
test-me-please

**Review by brb — APPROVED** [review]
Thanks!

**Comment by kvaster** [comment]
I've pressed 'update branch' by an accident... Sorry...

**Comment by kvaster** [comment]
What are next steps ? Is there anything more I can do to help this finalize ?

**Comment by brb** [comment]
Thanks. Marking as ready to merge.

@kvaster As a follow up, could you extend the kube-proxy-replacement guide by documenting your change?

**Comment by errordeveloper** [comment]
Unasigning myself as this PR has 3 reviews already.

**Comment by brb** [comment]
CC'ing @pchaigno and @jrfastab for visibility. This PR should fix host-fw and IPSec on vlan devices.

**Review by nathanjsweet — APPROVED** [review]
From a hubble and api perspective. LGTM. The datapath stuff makes sense to me too.

**Comment by joestringer** [comment]
The bot has marked not ready-to-merge because there are still @cilium/helm and @cilium/hubble reviews outstanding. @errordeveloper , it looks like you were pinged for those aspects (including the hubble API changes). Could you take a brief look specifically at those areas or consider raising this in the sig-hubble so that someone with the relevant expertise can take a look?

**Comment by kvaster** [comment]
> Thanks. Marking as ready to merge.
> 
> @kvaster As a follow up, could you extend the kube-proxy-replacement guide by documenting your change?

I will do this as a follow up PR!

**Review by errordeveloper — APPROVED** [review]
Protobuf and helm changes LGTM!

**Comment by kvaster** [comment]
It seems that all reviews are passed...

File: pkg/datapath/linux/config/config.go [hunk 13]
```diff
@@ -549,6 +555,74 @@ func (h *HeaderfileWriter) WriteNodeConfig(w io.Writer, cfg *datapath.LocalNodeC
...
+	if err != nil {
+		return "", err
+	}
+
+	for _, l := range links {
+		vlan, ok := l.(*netlink.Vlan)
+		// if it's vlan device and we're controlling vlan main device
+		// and either all vlans are allowed, or we're controlling vlan device or vlan is explicitly allowed
+		if ok && devices[vlan.ParentIndex] && (devices[vlan.Index] || allowedVlans[vlan.VlanId]) {
+			vlansByIfIndex[vlan.ParentIndex] = append(vlansByIfIndex[vlan.ParentIndex], vlan.VlanId)
```
Comment (jrajahalme) [inline pkg/datapath/linux/config/config.go:592]: This appending of vlanIDs that may not be ordered introduced a new unit test flake #17104.

Comment (joestringer) [reply pkg/datapath/linux/config/config.go:592]: @kvaster would you be able to look into this? Usually the solution is just to sort the slice once it's been assembled but before it is used to generate code.

Comment (joestringer) [reply pkg/datapath/linux/config/config.go:592]: Never mind, looks like @jrajahalme beat you to it :) Feel free to review though: https://github.com/cilium/cilium/pull/17105

Comment (kvaster) [reply pkg/datapath/linux/config/config.go:592]: Was away... Seems problem was already solved... I will make one more PR soon as discussed - docs update.

**Comment by jhutchins** [comment]
Is there an upcoming 1.10 release that will include this fix in the near future?

**Comment by joestringer** [comment]
Hi @jhutchins , typically more invasive features / changes are scheduled for the next upcoming release in order to minimize the risk of breakage for existing users. This will be included in the upcoming v1.11 release.
