### PR TITLE
routing: Fix route collisions in AWS ENI

### LINKED ISSUE #14336: Multi-homing route table bug in ENI mode
When allocating a new ENI device, we create a route pointing towards a ENI-specific route table. To allocate the table number, we currently use the ifindex. If the ifindex happens to be the same as the main routing table number, then instead of injecting a default route into the ENI-specific route table, we inject the route into the main routing table and mess with default routing for the entire node. This breaks connectivity for the node.

The same can occur for Azure interfaces as well (see https://github.com/cilium/cilium/issues/14705).

**General Information**

- Affects versions v1.7, v1.8, v1.9, master

### PR DESCRIPTION
**Pull request by christarazi**
See commit msgs.

This PR has been "forward-ported" from the following direct backport PR to the v1.7 branch: https://github.com/cilium/cilium/pull/14337.

Most commits have been forward-ported from the aforementioned PR, but a few commits are only meant for master (with intention to be backported to v1.9 & 1.8) because of code that didn't exist in v1.7 and because of the initial assumption that this issue impacts both ENI and Azure modes. In reality, only ENI mode has been impacted so far. While it is possible for the issue to occur on Azure, it is very unlikely and a separate PR will be made to address that (see https://github.com/cilium/cilium/issues/14705).

Fixes: https://github.com/cilium/cilium/issues/14336

### CODE REVIEW

File: pkg/datapath/linux/routing/routing.go [hunk 1]
```diff
@@ -49,17 +51,29 @@ func (info *RoutingInfo) Configure(ip net.IP, mtu int, masq bool) error {
...
+	}
+
 	ipWithMask := net.IPNet{
 		IP:   ip,
 		Mask: net.CIDRMask(32, 32),
 	}
 
-	// Route all traffic to the interface address via the main routing table
+	// Route all traffic to the interface address via the main routing table.
+	// Ingress rules are an exception to the above comment.
```
Comment (christarazi) [inline pkg/datapath/linux/routing/routing.go]: I can't find the historical context on why ingress rules need to be in the main routing table. 

Side note, if we decide to change it to be the same as the egress rule, then we'd have to change the protoype of `Delete()` which only accepts an IP. We wouldn't have enough information to find out which table the ingress rule is in because we'd need the iface name to retrieve the table ID. Just wanted to throw this out there in case we go down this route.

File: pkg/datapath/linux/routing/routing.go [hunk 2]
```diff
@@ -192,6 +208,29 @@ func deleteRule(r route.Rule) error {
...
+// we will return 4 as the table index.
+func retrieveTableIDFromIfindex(ifindex int) (int, error) {
+	iface, err := netlink.LinkByIndex(ifindex)
+	if err != nil {
+		return -1, fmt.Errorf("unable to get link by index: %w", err)
+	}
+
+	// We then use the interface name to get the integer part of the iface name
+	// (e.g. "0" from eth0, "1" from eth1).
+	idx, err := strconv.ParseInt(strings.ReplaceAll(iface.Attrs().Name, "eth", ""), 10, 64)
```
Comment (christarazi) [inline pkg/datapath/linux/routing/routing.go]: Are Azure interfaces always "eth*"? I assumed this just to get something out to get feedback. This is a minor detail that can be iterated on later.

Comment (ungureanuvladvictor) [reply pkg/datapath/linux/routing/routing.go]: I don't think the eth replace will work because the naming of the interfaces is different if the user enables or not (https://en.wikipedia.org/wiki/Consistent_Network_Device_Naming).

If this is disabled then I think the behavior is to keep `eth*` but if it's enabled it can differ (stock ubuntu AMI names interfaces `ens*`).

Comment (joestringer) [reply pkg/datapath/linux/routing/routing.go]: Yeah, here's an example Ubuntu device I have on my laptop: `enp0s31f6`. These numbers are derived from the hardware layout of the system so that they would be consistent regardless of when each device is initialized during kernel boot.

Comment (christarazi) [reply pkg/datapath/linux/routing/routing.go]: How can we reliably extract the "relevant" part from the ifname if don't know what the format is and is unpredictable? 

My initial thought was to grab the last digits of the ifname, essentially a regex of `[0-9]+$`. Would that work?

**Comment by christarazi** [comment]
This PR has been reworked completely. This PR has been forward-ported from the v1.7 PR. Please see updated PR description.

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
test-me-please

**Review by twpayne — APPROVED** [review]
LGTM. There are a couple of items from the 1.7 PR review (#14337) that it would be nice to see at some point:
* Use more specific terms than "new" and "old" schemes
* Add a sanity check that the generated interface numbers do not conflict with any reserved numbers

File: pkg/datapath/linux/routing/info.go [hunk 3]
```diff
@@ -77,9 +86,16 @@ func parse(gateway string, cidrs []string, macAddr string, masquerade bool) (*Ro
 		return nil, fmt.Errorf("invalid mac: %s", macAddr)
 	}
 
+	parsedIfaceNum, err := strconv.ParseInt(ifaceNum, 10, 64)
```
Comment (vadorovsky) [inline pkg/datapath/linux/routing/info.go]: I'd suggest to do:

```suggestion
	parsedIfaceNum, err := strconv.Atoi(ifaceNum)
```

To parse it as `int` from the beginning, instead of parsing as `int64` and then converting to `int`. I think that should fix the warning below.

File: pkg/datapath/linux/routing/info.go [hunk 4]
```diff
@@ -77,9 +86,16 @@ func parse(gateway string, cidrs []string, macAddr string, masquerade bool) (*Ro
...
+
 	return &RoutingInfo{
-		IPv4Gateway: ip,
-		IPv4CIDRs:   parsedCIDRs,
-		MasterIfMAC: parsedMAC,
+		IPv4Gateway:     ip,
+		IPv4CIDRs:       parsedCIDRs,
+		MasterIfMAC:     parsedMAC,
+		Masquerade:      masquerade,
+		InterfaceNumber: int(parsedIfaceNum),
```
Comment (vadorovsky) [inline pkg/datapath/linux/routing/info.go]: and then

```suggestion
		InterfaceNumber: parsedIfaceNum,
```

**Review by vadorovsky — COMMENTED** [review]
Just a minor nit. Everything else looks good to me.

**Comment by christarazi** [comment]
@twpayne Thanks for reviewing again :). My intention with this PR is to minimize the number of changes needed since it's a forward-port (I don't want to stray from the upstreamed commits). I'll address your comments as a followup, as it's the same feedback for the v1.7 version. This way, I can backport the followup PR and it'll change all branches, rather than addressing them one-by-one.

For fixups like @mrostecki pointed out, since we have new code scanners in master, it seems reasonable to me to fix that in this PR, otherwise we will get spammed about a code security issue. Then backport to v1.7 later since I'm doing a followup there anyway.

**Comment by christarazi** [comment]
test-me-please

**Review by vadorovsky — APPROVED** [review]
LGTM, thanks!

**Review by joestringer — APPROVED** [review]
I reviewed the original PR and was happy with it, and I've now reviewed the commits that were not in the original PR. Those LGTM.

Let me know if you think I should pay closer attention to any of the remaining commits.
