### PR TITLE
api: wait with api server start until legacy daemon init finished

### LINKED ISSUE #39430: CI: Cilium API handler panicked in `node.GetNodeAddressing()`
## CI failure

Happened in https://github.com/cilium/cilium/actions/runs/14904809330:

```
2025-05-08T11:09:12.100275961Z time=2025-05-08T11:09:12Z level=warn source=/go/src/github.com/cilium/cilium/pkg/api/apipanic.go:42 msg="Cilium API handler panicked" module=agent.infra.cilium-api-server url=/v1/config method=GET client=@ panicMessage="runtime error: invalid memory address or nil pointer dereference"
2025-05-08T11:09:12.100698439Z goroutine 561 [running]:
2025-05-08T11:09:12.100716112Z runtime/debug.Stack()
2025-05-08T11:09:12.100719278Z  /usr/local/go/src/runtime/debug/stack.go:26 +0x5e
2025-05-08T11:09:12.100722313Z github.com/cilium/cilium/pkg/api.(*APIPanicHandler).ServeHTTP.func1()
2025-05-08T11:09:12.100728856Z  /go/src/github.com/cilium/cilium/pkg/api/apipanic.go:46 +0x30e
2025-05-08T11:09:12.100737452Z panic({0x46aa800?, 0x8d4c780?})
2025-05-08T11:09:12.100740497Z  /usr/local/go/src/runtime/panic.go:792 +0x132
2025-05-08T11:09:12.100743333Z github.com/cilium/cilium/pkg/node.GetNodeAddressing()
2025-05-08T11:09:12.100745857Z  /go/src/github.com/cilium/cilium/pkg/node/address.go:350 +0x54
2025-05-08T11:09:12.100748573Z github.com/cilium/cilium/daemon/restapi.(*getConfigHandler).Handle(0xc00275e630, {0xc002c728c0?})
2025-05-08T11:09:12.100751588Z  /go/src/github.com/cilium/cilium/daemon/restapi/config.go:358 +0x5f7
2025-05-08T11:09:12.100754253Z github.com/cilium/cilium/api/v1/server/restapi/daemon.(*GetConfig).ServeHTTP(0xc001190420, {0x58dccf0, 0xc001819140}, 0xc002c728c0)
2025-05-08T11:09:12.100757169Z  /go/src/github.com/cilium/cilium/api/v1/server/restapi/daemon/get_config.go:58 +0x13d
2025-05-08T11:09:12.100759533Z github.com/go-openapi/runtime/middleware.(*Context).RoutesHandler.NewOperationExecutor.func1({0x58dccf0, 0xc001819140}, 0xc002c728c0)
2025-05-08T11:09:12.100765394Z  /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/operation.go:28 +0x50
2025-05-08T11:09:12.100770644Z net/http.HandlerFunc.ServeHTTP(0xc001709280?, {0x58dccf0?, 0xc001819140?}, 0x4776d9?)
2025-05-08T11:09:12.100776014Z  /usr/local/go/src/net/http/server.go:2294 +0x29
2025-05-08T11:09:12.100778769Z github.com/go-openapi/runtime/middleware.NewRouter.func1({0x58dccf0, 0xc001819140}, 0xc001ec5a40)
2025-05-08T11:09:12.100799417Z  /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/router.go:80 +0x257
2025-05-08T11:09:12.100802233Z net/http.HandlerFunc.ServeHTTP(0xc0016ce994?, {0x58dccf0?, 0xc001819140?}, 0xc0005e7800?)
2025-05-08T11:09:12.100804838Z  /usr/local/go/src/net/http/server.go:2294 +0x29
2025-05-08T11:09:12.100807322Z github.com/go-openapi/runtime/middleware.Redoc.serveUI.func1({0x58dccf0, 0xc001819140}, 0xc001ec5a40)
2025-05-08T11:09:12.100810107Z  /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/ui_options.go:164 +0xcc
2025-05-08T11:09:12.100812592Z net/http.HandlerFunc.ServeHTTP(0xc0016ce994?, {0x58dccf0?, 0xc001819140?}, 0xc0006f5680?)
2025-05-08T11:09:12.100815507Z  /usr/local/go/src/net/http/server.go:2294 +0x29
2025-05-08T11:09:12.100818383Z github.com/go-openapi/runtime/middleware.Spec.func1({0x58dccf0, 0xc001819140}, 0xc001ec5a40)
2025-05-08T11:09:12.100821008Z  /go/src/github.com/cilium/cilium/vendor/github.com/go-openapi/runtime/middleware/spec.go:72 +0x1a2
2025-05-08T11:09:12.100823783Z net/http.HandlerFunc.ServeHTTP(0xc0012d1340?, {0x58dccf0?, 0xc001819140?}, 0x3?)
2025-05-08T11:09:12.100826548Z  /usr/local/go/src/net/http/server.go:2294 +0x29
2025-05-08T11:09:12.100829504Z github.com/cilium/cilium/pkg/metrics.(*APIEventTSHelper).ServeHTTP(0xc000916570, {0x58dce80, 0xc00281e700}, 0xc001ec5a40)
2025-05-08T11:09:12.100832098Z  /go/src/github.com/cilium/cilium/pkg/metrics/middleware.go:63 +0x1c3
2025-05-08T11:09:12.100834823Z github.com/cilium/cilium/pkg/api.(*APIPanicHandler).ServeHTTP(0xc0023e7d40?, {0x58dce80?, 0xc00281e700?}, 0x811bf6?)
2025-05-08T11:09:12.100837348Z  /go/src/github.com/cilium/cilium/pkg/api/apipanic.go:56 +0x62
2025-05-08T11:09:12.100840063Z net/http.(*ServeMux).ServeHTTP(0x476919?, {0x58dce80, 0xc00281e700}, 0xc001ec5a40)
2025-05-08T11:09:12.100842918Z  /usr/local/go/src/net/http/server.go:2822 +0x1c4
2025-05-08T11:09:12.100845694Z net/http.serverHandler.ServeHTTP({0xc0005576e0?}, {0x58dce80?, 0xc00281e700?}, 0x1?)
2025-05-08T11:09:12.100848259Z  /usr/local/go/src/net/http/server.go:3301 +0x8e
2025-05-08T11:09:12.100850773Z net/http.(*conn).serve(0xc0018d5440, {0x58fdc78, 0xc001412960})
2025-05-08T11:09:12.100853278Z  /usr/local/go/src/net/http/server.go:2102 +0x625
2025-05-08T11:09:12.100855762Z created by net/http.(*Server).Serve in goroutine 473
2025-05-08T11:09:12.100858578Z  /usr/local/go/src/net/http/server.go:3454 +0x485
```

[cilium-sysdump-2-20250508-111942.zip](https://github.com/user-attachments/files/20101965/cilium-sysdump-2-20250508-111942.zip)

@cilium/api

### PR DESCRIPTION
**Pull request by mhofstetter**
Currently, the API server start no longer waits until the legacy
daemon initialization finished (introduced with #39357). 
This can lead to panics from api handlers
that rely on globals that are initialized by this legacy daemon logic.

(e.g. config handler that relies on node globals (`node.GetNodeAddressing`).

Therefore, this commit modifies the configmodify api handler to wait for
the Daemon promise. This way, the start of the api server gets postponed
until IPAM has been initialized.

Note: Unfortunately, due to circular dependencies it's not possible to
depend on the Daemon promise directly. Therefore, this commit also
introduces a new marker interface `legacy.DaemonInitialization` that
can be used to depend on the daemon initialization.

Note 2: IMO it's better to introduce this new (but hopefully temporary) interface than adjust the `server.Server` template to actually wait on a promise before starting the server. Because this might have other side-effects (e.g. premature unlock of endpoint deletion queue, ...)

Note 3: Let's hope that we can delete the `Daemon` struct in the near future - to prevent re-adding state to it. Then it's even more useful to have this "marker" interface for the cases that still need to be able to depend on the legacy daemon init phase.

Fixes: #39430
Fixes: #39357

### CODE REVIEW

File: daemon/cmd/legacy/daemon_init.go [hunk 1]
```diff
@@ -0,0 +1,7 @@
+// SPDX-License-Identifier: Apache-2.0
+// Copyright Authors of Cilium
+
+package legacy
+
+// marker interface to be able to depend on the legacy daemon
```
Comment (joamaki) [inline daemon/cmd/legacy/daemon_init.go]: let's expand the comment to exactly say what part is initialized, e.g. this will make sure the Start hook for Daemon runs before yours and that this means `newDaemon` has been called, but `startDaemon` is likely going to run in parallel with your start hook.

We could just use `struct{}` as the type here instead of `any`, it's perhaps a bit more honest in that there is no information here.

File: daemon/cmd/daemon_main.go [hunk 2]
```diff
@@ -1589,7 +1590,7 @@ func newDaemonPromise(params daemonParams) promise.Promise[*Daemon] {
 			return nil
 		},
 	})
-	return daemonPromise
+	return daemonPromise, struct{}{}
```
Comment (joamaki) [inline daemon/cmd/daemon_main.go]: if `DaemonInitialization` has type `struct{}` then we can do `legacy.DaemonInitialization{}` here.

**Review by joamaki — APPROVED** [review]

File: daemon/cmd/daemon_main.go (hunk 2 above)
Comment (mhofstetter) [reply daemon/cmd/daemon_main.go]: yep, changed

File: daemon/cmd/legacy/daemon_init.go (hunk 1 above)
Comment (mhofstetter) [reply daemon/cmd/legacy/daemon_init.go]: makes sense. I changed it accordingly
