### PR TITLE
Fix persisted endpoint state synchronization for FQDN operations

### LINKED ISSUE #40074: Fix persisted endpoint state synchronization for FQDN operations
Currently there are a few FQDN related operations on the Endpoint object in Cilium for which state persistence is not synchronized correctly. This can cause stale fqdn state for the endpoint to be realized on Cilium restarts. 
This doesn't seem to pose any user facing impact since the GC run for fqdn state self-corrects the state eventually.

1. Persisted endpoint state is not sync'd after `cilium fqdn cache clean -f`

Image

2. GC run on endpoint's DNS state is not persisted to the disk(for both History -> Zombie and Zombie -> dead transitions).

Image

### PR DESCRIPTION
**Pull request by fristonio**
See commit messages for details.

Fixes: #40074

```release-note
fqdn: fix persisted endpoint state synchronization for FQDN operations
```

### CODE REVIEW

File: pkg/fqdn/namemanager/gc.go [hunk 1]
```diff
@@ -125,9 +125,14 @@ func (n *manager) doGC(ctx context.Context) error {
 			namesToClean.Insert(zombie.Names...)
 		}
 
-		// Sync endpoint persisted state if DNS state changed during GC run.
-		if len(affectedNames) > 0 || len(dead) > 0 {
+		// Sync endpoint's persisted state if:
+		// 1. DNS state changed during this GC run.
+		// 2. CT GC run updated the zombies since last sync.
+		if len(affectedNames) > 0 || len(dead) > 0 || ep.DNSZombies.MaybeOutOfSync() {
```
Comment (fristonio) [inline pkg/fqdn/namemanager/gc.go]: This just seems like an additional change that doesn't reliably get rid of this noise. I will remove this change.

**Review by gandro — APPROVED** [review]
Nice, thanks!

**Review by giorio94 — APPROVED** [review]
/lgtm for the logfields change.

**Review by YutaroHayakawa — APPROVED** [review]
Looks like I've pulled-in for the change in the `maps/ctmap/gc/gc.go`. LGTM.

**Review by squeed — APPROVED** [review]
