### PR TITLE
clustermesh: Do not error out of agent when remote cluster is unreachable

### LINKED ISSUE #6376: clustermesh etcd connectivity failure leads to fatal log message
Causes cilium-agent to restart when etcd connectivity to remote cluster fails.

### PR DESCRIPTION
**Pull request by tgraf**
This PR fixes various ClusterMesh related bugs:

* The etcd client code contained a log.Fatalf() error message when the session could not be established after a certain timeout. This would error out of the agent immediately. This is desired behavior for the main etcd connection but not for connection to remote clusters. Return a channel containing the error when session establishment fails to give the caller a chance to decide how to react to connectivity problems.

* Stop leaking etcd status checker go routines

* On change of the connection information to a remote cluster, release the old connection information 

Fixes: #6376

Signed-off-by: Thomas Graf <thomas@cilium.io>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6401)

### CODE REVIEW

**Comment by tgraf** [comment]
test-me-please

**Comment by tgraf** [comment]
Noticed that this is still incomplete, the version check still emits fatal log messages.

**Comment by tgraf** [comment]
test-me-please

```
 k8s-1.13.K8sKafkaPolicyTest Kafka Policy Tests KafkaPolicies
```

**Comment by tgraf** [comment]
test-me-please

File: pkg/kvstore/etcd.go [hunk 1]
```diff
@@ -169,6 +173,21 @@ type etcdClient struct {
 	latestErrorStatus error
 }
 
+func (e *etcdClient) getLogger() *logrus.Entry {
+	endpoints, path := []string{""}, ""
```
Comment (aanm) [inline pkg/kvstore/etcd.go:186]: To avoid running this for every call of getLogger() can't you store a logrus.Entry in the etcdClient structure or use a sync.Once here? :thinking:

**Review by aanm — APPROVED** [review]

File: pkg/kvstore/etcd.go (hunk 1 above)
Comment (tgraf) [reply pkg/kvstore/etcd.go:186]: Yes possible, let's do it after 1.4.0-rc1. It's definitely not performance critical.
