### PR TITLE
ICMPv6: Fix verifier error when loading on l2-less devices

### LINKED ISSUE #41522: Verifier error: program cil_from_netdev: load program: permission denied: invalid access to packet
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than 1.19.0-pre.0

### What happened?

Upgrading Cilium to 1.19.0-pre.0 causes failure to reload endpoint BPF program.

This happens only on one node out of 8 in the Kubernetes cluster, although I couldn't figure out the difference between them yet.

```text
Verifier error: program cil_from_netdev: load program: permission denied: invalid access to packet, off=0 size=4, R4(id=0,off=0,r=0): R4 offset is outside of the packet (200 line(s) omitted)
Verifier log: load program: permission denied:
	0: R1=ctx() R10=fp0
	; int cil_from_netdev(struct __ctx_buff *ctx) @ bpf_host.c:1247
	0: (bf) r6 = r1                       ; R1=ctx() R6_w=ctx()
	; if (ctx->vlan_present) { @ bpf_host.c:1260
```

### How can we reproduce the issue?

not sure

### Cilium Version

1.19.0-pre.0

### Kernel Version

Linux srv1host 6.11.5+bpo-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.11.5-1~bpo12+1 (2024-11-11) x86_64 GNU/Linux

### Kubernetes Version

v1.31.4

### Regression

v1.18.0

### Sysdump

[cilium-sysdump-20250904-140244.zip](https://github.com/user-attachments/files/22137034/cilium-sysdump-20250904-140244.zip)

[cilium_log.txt](https://github.com/user-attachments/files/22137039/cilium_log.txt)

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dylandreimerink**
The ICMPv6 code was assuming that `ETH_HLEN` is always equal to the size of `struct ethhdr`, which is not the case on L3 devices. This leads to verifier errors when loading with l2 announcements on a L3 device.

Fixes: #41522

```release-note
Fix verifier error that occurs when enabling l2 annoucements on a l2-less device
```

### CODE REVIEW

**Comment by msune** [comment]
FWIW, ack

File: bpf/lib/icmp6.h [hunk 1]
```diff
@@ -534,6 +534,10 @@ bool icmp6_ndisc_validate(struct __ctx_buff *ctx, const struct ipv6hdr *ip6,
 	struct ethhdr *eth = ctx_data(ctx);
 	union macaddr *dmac;
 
+	/* On l2-less devices there is no MAC address, and we cannot proceed */
+	if (sizeof(struct ethhdr) != ETH_HLEN)
+		return false;
+
```
Comment (julianwiedmann) [inline bpf/lib/icmp6.h:540]: Looks good as quick fix! But I think we should be able to lift this even further up, and just skip `handle_l2_announcement()` entirely on a L3 device? Attempting to advertise `CONFIG(interface_mac)` makes no sense, even for IPv4 ...

**Review by julianwiedmann — APPROVED** [review]
Thank you! Added one comment, but feel free to defer it and get the PR in :)

File: bpf/lib/icmp6.h (hunk 1 above)
Comment (dylandreimerink) [reply bpf/lib/icmp6.h:540]: :thinking: We have the `IS_L3_DEV` macro, which is slated to be replaced by a map lookup (since it can check for a given ifindex, not just the device the current program is loaded onto). In the loader we currently do:
```
        // External devices can be L2-less, in which case it won't have a MAC address
	// and its ethernet header length is set to 0.
	em := mac.MAC(link.Attrs().HardwareAddr)
	if len(em) == 6 {
		cfg.InterfaceMAC = em.As8()
	} else {
		cfg.EthHeaderLength = 0
	}
```

Perhaps we just make `ETH_HLEN` static at 14 bytes, and make a `curDevL3` config which is a boolean. Then in BPF explicitly check `CONFIG(curDevL3)` whenever we are about to use `ETH_HLEN`?

It seems like that is more explicit about what is going on. And we can use that boolean to shortcircuit other L2 specific logic as well when needed.

Comment (julianwiedmann) [reply bpf/lib/icmp6.h:540]: As data point, here's how the redirect code deals with all the potential L{2,3}to-L{2,3} scenarios: https://github.com/cilium/cilium/blob/b02aaad70b9aba2d6158f34393bdba3803a63753/bpf/lib/fib.h#L36

Comment (dylandreimerink) [reply bpf/lib/icmp6.h:540]: I looked into a bit more, and its just a difficult and confusing situation. To summarize:
* In bpf_host.c its dynamic 0 or `__ETH_HLEN` (14), depending on the device its attached to
* In bpf_wireguard.c its static 0, because wg devices are l2-less
* In all others its static `__ETH_HLEN` (14)

For thus for library functions it depends on which .c file is the current root. And you as developer have to have knowledge of who uses the logic to know if your macro is static or dynamic.

We use `ETH_HLEN` about 150 times, so I will drop the idea of `curDevL3` I don't think it will help.

As for these changes, perhaps comparing `ETH_HLEN` to `__ETH_HLEN` or 0 is more sound than comparing to `sizeof(struct ethhdr)` even though its technically the same

Comment (julianwiedmann) [reply bpf/lib/icmp6.h:540]: > As for these changes, perhaps comparing `ETH_HLEN` to `__ETH_HLEN` or 0 is more sound than comparing to `sizeof(struct ethhdr)` even though its technically the same

ack, think I'll send a tree-wide cleanup to introduce a `is_l3_device()` helper (which checks for `ETH_HLEN == 0`). But let's merge this as-is, no need to over-complicate a fix which needs backporting.

Comment (julianwiedmann) [reply bpf/lib/icmp6.h:540]: Playing around in https://github.com/cilium/cilium/pull/41750.

**Comment by pippolo84** [comment]
@dylandreimerink  marked as _backport/author_ since I was unable to solve the conficts in https://github.com/cilium/cilium/pull/41828

**Comment by giorio94** [comment]
Hey @dylandreimerink 👋 Backporter here. Kind reminder that this PR is marked for author backport. Please check if it still makes sense to backport it, or the label should be dropped.

**Comment by dylandreimerink** [comment]
I think I mistakenly applied the backport label. The feature is its fixing was not part of the v1.18 release. Removed the label
