### PR TITLE
use CiliumEndpoint watcher to remove pod metrics across all nodes

### LINKED ISSUE #31889: hubble metrics not correctly deleted when pods are removed.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We are seeing a buildup of series for flow metrics which are not getting deleted when pods are removed. Digging into how series are cleaned up, we see they are deleted by podname and namespace, and that the deletion is driven via the pod watcher [here](https://github.com/cilium/cilium/blob/main/pkg/k8s/watchers/pod.go#L543).

By the looks of how [this watcher is configured](https://github.com/cilium/cilium/blob/main/pkg/k8s/watchers/pod.go#L179), if the CiliumEndpointCRD is enabled, it will only watch for pods on the given node. This means it will never delete series when the source or destination is a pod on a different host. 

This is particularly bad for pods like coredns where pretty much everything that ever connects to it causes it to track a series indefinitely. It is exacerbated further by short lived workloads which further explode the number of series being tracked. This can get so bad that the agent cannot be scraped and needs to be restarted.

Ideally there would be a separate reconciliation process that monitors the lifecycle of source and destinations pods from series tracked on the host and feed these through the metrics deletion handler.  

### Cilium Version

1.14.4 though it seems to be this way in the latest version too.

### Kernel Version

This is not a kernel issue

### Kubernetes Version

1.28 (not an issue with the K8s version)

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by sgargan**
Fixes #31889 by using the CiliumEndpoints watcher to drive metrics deletion instead of the Pod watcher. Metrics deletion was being handled by the pod watcher when a pod was deleted so to were all the metrics associated with it. However, if a cilium agent is configured with CiliumEndpointCRD enabled, it will only watch for pods on the current node. This leads to a leak where metrics would never be reaped up on nodes where the pod was not running.

Every node watches all the CiliumEndpoints and the endpoint resources contains contain enough information to trigger the deletion of the metrics. This change moves the deletion to the CiliumEndpoint watcher and uses the endpoint name and namespace to delete the metric when the endpoint is deleted.

Signed-off-by: Steve Gargan steve.gargan@gmail.com

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

```release-note
Fix hubble metrics leak by using CiliumEndpoint watcher to remove stale metrics.
```

### CODE REVIEW

**Comment by kaworu** [comment]
defering review to @chancez whom has more context about the Hubble metrics subsystem.

File: pkg/hubble/metrics/api/api.go [hunk 1]
```diff
@@ -126,13 +126,13 @@ func (h Handlers) ProcessFlow(ctx context.Context, flow *pb.Flow) error {
 	return errs
 }
 
-// ProcessPodDeletion queries all handlers for a list of MetricVec and removes
-// metrics directly associated to deleted pod.
-func (h Handlers) ProcessPodDeletion(pod *slim_corev1.Pod) {
+// ProcessCiliumEndpointDeletion queries all handlers for a list of MetricVec and removes
+// metrics directly associated to pod of the deleted cilium endpoint.
+func (h Handlers) ProcessCiliumEndpointDeletion(endpoint *types.CiliumEndpoint) {
```
Comment (tommyp1ckles) [inline pkg/hubble/metrics/api/api.go:131]: It's been a while since I've looked at the CEP watchers, but would this still work if CiliumEndpointSlice is enabled (i.e. in which case I believe only the operator watches CEPs and [agents watch CES resources](https://github.com/cilium/cilium/blob/ad85cd50b5216ef3ddc3a7347787d10fe5ab2a0d/pkg/k8s/watchers/cilium_endpoint.go#L79-L81)).

**Review by chancez — COMMENTED** [review]
Overall LGTM in principal, but we should determine how this interacts with EndpointSlices as @tommyp1ckles mentioned

**Comment by chancez** [comment]
Tagging @gandro for assistance on this

**Comment by chancez** [comment]
https://github.com/sgargan/cilium-metrics-leak 👀 is this how you tested @sgargan ?

File: pkg/hubble/metrics/api/api.go (hunk 1 above)
Comment (gandro) [reply pkg/hubble/metrics/api/api.go:131]: Yes, but this is called from `K8sCiliumEndpointsWatcher.endpointDeleted` which is also called from the CES watcher here:

https://github.com/cilium/cilium/blob/8190bf8ddb0f6c48a4d87064fd25da15a365ad1b/pkg/k8s/watchers/cilium_endpoint_slice_subscriber.go#L166

**Review by gandro — APPROVED** [review]
Looks good in term of correctness and is clearly an improvement over watching pods.

Long term, I think we should consider checking if it is possible to get an event from IPCache once an pod is deleted, since we also use IPCache to annotate the pod information in the metrics. Having the same source for removal events that we used for obtaining the label seems the most clean to me.

But this PR as is is already clearly more correct than the previous approach, so I don't think this is a reason to block this PR

**Comment by sgargan** [comment]
> https://github.com/sgargan/cilium-metrics-leak 👀 is this how you tested @sgargan ?

Yes, uses a kind dev cluster. It calls pods on each node and notes the hubble metrics before deleting one and seeing that the metrics get deleted on both nodes.

**Review by chancez — APPROVED** [review]

**Comment by gandro** [comment]
@sgargan A quick note: I see you are (presumably) rebasing the branch. Please note that this invalidates CI results and thus blocks the PR from being merged. 

Unless you need to do changes to the branch or rebase because of a conflict, I'd recommend to not push to the branch after we've run a `/test` command.

**Comment by sgargan** [comment]
> @sgargan A quick note: I see you are (presumably) rebasing the branch. Please note that this invalidates CI results and thus blocks the PR from being merged.
> 
> Unless you need to do changes to the branch or rebase because of a conflict, I'd recommend to not push to the branch after we've run a `/test` command.

The CI tests were hung for a long time, I thought this was due to the branch not being up to date. I'd rebased to kick the build again. I'll leave it alone now.

**Comment by sgargan** [comment]
Seems an ingress test has barfed, can you kick the tests off one more time 🙏

**Comment by sgargan** [comment]
@gandro do you think it would be possible to get this backported to 1.15?

**Comment by gandro** [comment]
Yes, considering this is a bugfix and I don't expect any conflicts, I think we can add the needs-backport label
