### PR TITLE
eni: Support Instance Metadata Service Version 2 (IMDSv2)

### LINKED ISSUE #15520: Cilium 1.9.5 + EKS & IMDSv2 seems not working
Hello,

With my team we are working on Cilium (1.9.5) integration on a freshly EKS cluster.

We follow the official [doc](https://docs.cilium.io/en/latest/gettingstarted/k8s-install-eks/) and it's working great.

For obvious [reasons](https://docs.aws.amazon.com/eks/latest/userguide/best-practices-security.html) we would like to use only Metadatav2 with our EC2 workers but it seems not working correctly.

```
kube-system   cilium-dlrhr                      0/1     Error               4          112s
kube-system   cilium-h47r4                      0/1     Running             4          112s
kube-system   cilium-node-init-d87d5            1/1     Running             0          112s
kube-system   cilium-node-init-z8hz5            1/1     Running             0          112s
kube-system   cilium-operator-f44f7c878-hk2pd   1/1     Running             0          112s
kube-system   cilium-operator-f44f7c878-rzfc8   1/1     Running             0          112s
kube-system   coredns-6987776bbd-6jn84          0/1     ContainerCreating   0          11m
kube-system   coredns-6987776bbd-dqbdq          0/1     ContainerCreating   0          11m
kube-system   hubble-relay-777ddbdccf-2j8k8     0/1     ContainerCreating   0          112s
kube-system   hubble-ui-58bbbc8b95-2dzgc        0/3     ContainerCreating   0          112s
...
``` 
When checking the logs from Cilium pods I can see it has some difficulties to recover information provided by the metadata :

```
level=warning msg="Unable to mutate nodeResource" error="InstanceID of own EC2 instance is empty" retryCount=7 subsys=nodediscovery
level=debug msg="Missing io.cilium.network.ipv4-cilium-host. Annotation required when IPSec Enabled" k8sNodeID=XXX nodeName=ip-xxx.region.compute.internal subsys=k8s
level=debug msg="Missing io.cilium.network.ipv6-cilium-host. Annotation required when IPSec Enabled" k8sNodeID=XXX nodeName=ip-xxx.region.compute.internal subsys=k8s
level=debug msg="Empty IPv4 CIDR annotation in node" k8sNodeID=XXX nodeName=ip-xxx.region.compute.internal subsys=k8s
level=debug msg="Empty IPv6 CIDR annotation in node" k8sNodeID=XXX nodeName=ip-xxx.region.compute.internal subsys=k8s
level=debug msg="Empty IPv4 health endpoint annotation in node" k8sNodeID=XXX nodeName=ip-xxx.region.compute.internal subsys=k8s
level=debug msg="Empty IPv6 health endpoint annotation in node" k8sNodeID=XXX nodeName=ip-xxx.region.compute.internal subsys=k8s
level=warning msg="Unable to mutate nodeResource" error="InstanceID of own EC2 instance is empty" retryCount=8 subsys=nodediscovery
level=debug msg="Missing io.cilium.network.ipv4-cilium-host. Annotation required when IPSec Enabled" k8sNodeID=XXX nodeName=ip-xxx.region.compute.internal subsys=k8s
level=debug msg="Missing io.cilium.network.ipv6-cilium-host. Annotation required when IPSec Enabled" k8sNodeID=XXX nodeName=ip-xxx.region.compute.internal subsys=k8s
level=debug msg="Empty IPv4 CIDR annotation in node" k8sNodeID=XXX nodeName=ip-xxx.region.compute.internal subsys=k8s
level=debug msg="Empty IPv6 CIDR annotation in node" k8sNodeID=XXX nodeName=ip-xxx.region.compute.internal subsys=k8s
level=debug msg="Empty IPv4 health endpoint annotation in node" k8sNodeID=XXX nodeName=ip-xxx.region.compute.internal subsys=k8s
level=debug msg="Empty IPv6 health endpoint annotation in node" k8sNodeID=XXX nodeName=ip-xxx.region.compute.internal subsys=k8s
level=warning msg="Unable to mutate nodeResource" error="InstanceID of own EC2 instance is empty" retryCount=9 subsys=nodediscovery
level=fatal msg="Could not create or update CiliumNode resource, despite retries" subsys=nodediscovery
```

I saw when debugging (but I'm not able to find it again) that Cilium wasn't able to connect to Metadata and get a 401/Unauthorized like it's trying to get info without having a valid token (basically requesting a token with a PUT to "http://169.254.169.254/latest/api/token" with the header "X-aws-ec2-metadata-token-ttl-seconds: 21600").

Is there any plan to support IMDSv2 ? I think it's now integrated in the AWS SDK.

Thanks,

Regards

### PR DESCRIPTION
**Pull request by Smana**
Make use of the version 2 of AWS's instance metadata API which is recommended for security purposes.
More info [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html)

Fixes: #15520

Signed-off-by: Smaine Kahlouch <smainklh@gmail.com>

```release-note
AWS eni: Support Instance Metadata Service Version 2 (IMDSv2)
```

### CODE REVIEW

File: pkg/aws/metadata/metadata.go [hunk 1]
```diff
@@ -11,53 +11,78 @@
...
+	"github.com/aws/aws-sdk-go-v2/config"
+	"github.com/aws/aws-sdk-go-v2/feature/ec2/imds"
 )
 
-func getMetadata(name string) (string, error) {
-	resp, err := http.Get("http://169.254.169.254/latest/meta-data/" + name)
+func newClient() (*imds.Client, error) {
+	cfg, err := config.LoadDefaultConfig(context.TODO())
+	if err != nil {
+		log.Printf("error: %v", err)
```
Comment (christarazi) [inline pkg/aws/metadata/metadata.go]: Let's just return the error without logging because the caller can see the error and log if they want to. This code will be retried anyway if it fails, so we don't want duplicate log msgs

File: pkg/aws/metadata/metadata.go [hunk 2]
```diff
@@ -11,53 +11,78 @@
...
+	return client, err
+}
+
+func getMetadata(client *imds.Client, path string) (string, error) {
+	res, err := client.GetMetadata(context.TODO(), &imds.GetMetadataInput{
+		Path: path,
+	})
 	if err != nil {
-		return "", fmt.Errorf("unable to retrieve instance-id from metadata server: %s", err)
+		return "", err
```
Comment (christarazi) [inline pkg/aws/metadata/metadata.go]: Why remove the error msg context?

File: pkg/aws/metadata/metadata.go [hunk 3]
```diff
@@ -11,53 +11,78 @@
...
 	}
 
-	defer resp.Body.Close()
-	instanceID, err := io.ReadAll(resp.Body)
+	defer res.Content.Close()
+	value, err := io.ReadAll(res.Content)
 	if err != nil {
-		return "", fmt.Errorf("unable to read response body: %s", err)
+		return "", err
```
Comment (christarazi) [inline pkg/aws/metadata/metadata.go]: Same here

File: pkg/aws/metadata/metadata.go [hunk 4]
```diff
@@ -11,53 +11,78 @@
...
 
-	return string(instanceID), nil
+	return string(value), err
 }
 
-// GetInstanceMetadata returns the instance ID and type
+// GetInstanceMetadata returns required AWS metadatas
 func GetInstanceMetadata() (instanceID, instanceType, availabilityZone, vpcID string, err error) {
-	instanceID, err = getMetadata("instance-id")
+	client, err := newClient()
```
Comment (christarazi) [inline pkg/aws/metadata/metadata.go:53]: Hmm, should we be creating a new client every time there's a call to `GetInstanceMetadata()`? Does it not matter?

**Review by christarazi — CHANGES_REQUESTED** [review]
Thanks for your PR! Overall look good to me, just a few comments that need to be addressed

File: pkg/aws/metadata/metadata.go (hunk 2 above)
Comment (Smana) [reply pkg/aws/metadata/metadata.go]: my bad, fixing that

File: pkg/aws/metadata/metadata.go (hunk 4 above)
Comment (Smana) [reply pkg/aws/metadata/metadata.go:53]: Thanks @christarazi for the review. regarding the client creation I don't see where else should I put it.
I checked the [nodediscovery.go](https://github.com/cilium/cilium/blob/master/pkg/nodediscovery/nodediscovery.go) which make use of this function and it seems to be called once. Please let me know if there's a better place

File: pkg/aws/metadata/metadata.go (hunk 1 above)
Comment (Smana) [reply pkg/aws/metadata/metadata.go]: done

File: pkg/aws/metadata/metadata.go (hunk 3 above)
Comment (Smana) [reply pkg/aws/metadata/metadata.go]: done

File: pkg/aws/metadata/metadata.go (hunk 4 above)
Comment (christarazi) [reply pkg/aws/metadata/metadata.go:53]: Fair enough, I think if it's called once, then the code is fine as-is

File: pkg/aws/metadata/metadata.go [hunk 5]
```diff
@@ -11,53 +11,76 @@
...
-	resp, err := http.Get("http://169.254.169.254/latest/meta-data/" + name)
+func newClient() (*imds.Client, error) {
+	cfg, err := config.LoadDefaultConfig(context.TODO())
+	if err != nil {
+		return nil, err
+	}
+
+	client := imds.NewFromConfig(cfg)
+
+	return client, err
```
Comment (christarazi) [inline pkg/aws/metadata/metadata.go]:
```suggestion
	return imds.NewFromConfig(cfg), nil
```

File: pkg/aws/metadata/metadata.go [hunk 6]
```diff
@@ -11,53 +11,76 @@
...
-	"net/http"
+
+	"github.com/aws/aws-sdk-go-v2/config"
+	"github.com/aws/aws-sdk-go-v2/feature/ec2/imds"
 )
 
-func getMetadata(name string) (string, error) {
-	resp, err := http.Get("http://169.254.169.254/latest/meta-data/" + name)
+func newClient() (*imds.Client, error) {
+	cfg, err := config.LoadDefaultConfig(context.TODO())
```
Comment (christarazi) [inline pkg/aws/metadata/metadata.go:26]: Thinking about the `context.TODO()` a bit more...I think we should probably address this in another PR. Would you mind filing an issue to tackle this? I think we would want to have some sort of reasonable timeout, as we don't want to block indefinitely trying to fetch metadata.

File: pkg/aws/metadata/metadata.go [hunk 7]
```diff
@@ -1,4 +1,4 @@
-// Copyright 2019 Authors of Cilium
+// Copyright 2021 Authors of Cilium
```
Comment (christarazi) [inline pkg/aws/metadata/metadata.go]: Typically we keep the year ranges of the copyright:

```suggestion
// Copyright 2019-2021 Authors of Cilium
```

File: pkg/aws/metadata/metadata.go [hunk 8]
```diff
@@ -11,53 +11,76 @@
...
+		return "", fmt.Errorf("unable to retrieve AWS metadata %s: %w", path, err)
 	}
 
-	defer resp.Body.Close()
-	instanceID, err := io.ReadAll(resp.Body)
+	defer res.Content.Close()
+	value, err := io.ReadAll(res.Content)
 	if err != nil {
-		return "", fmt.Errorf("unable to read response body: %s", err)
+		return "", fmt.Errorf("unable to read response content for AWS metadata %s: %w", path, err)
```
Comment (christarazi) [inline pkg/aws/metadata/metadata.go]: Let's make the `path` a bit easier to read in the error msg:

```suggestion
		return "", fmt.Errorf("unable to read response content for AWS metadata %q: %w", path, err)
```

**Review by christarazi — CHANGES_REQUESTED** [review]
A few more comments. Also please squash all your changes into one commit. No need to have separate commits mentioning that they address code review comments :)

File: pkg/aws/metadata/metadata.go (hunk 6 above)
Comment (Smana) [reply pkg/aws/metadata/metadata.go:26]: Hi @christarazi , I've created this issue. I'm not sure I've put all the elements you thought about. https://github.com/cilium/cilium/issues/15850

Comment (christarazi) [reply pkg/aws/metadata/metadata.go:26]: Looks good! :pray:

**Review by christarazi — COMMENTED** [review]
LGTM, were you able to test this?

Also one minor note on the commit msg: generally, we mention the subsystem (they are directories under `pkg/`) in the commit msg. For example, something like `eni: Support ...`. Either you the drop upper-cased `AWS` and keep `eni` or you simply use `aws:` to keep consistent with our process. I think in this case, `aws:` (lower-case) makes the most sense as this isn't specific to ENI mode.

**Comment by Smana** [comment]
>LGTM, were you able to test this?

Yes we tested it on a brand new EKS cluster with a node group composed of instances configured with instance metadata v2. With the upstream image `v1.9.5`  we had the behavior described in the issue https://github.com/cilium/cilium/issues/15520. Then it worked with an image built from the tag `v1.10.0-rc0` with the current change included.

> Also one minor note on the commit msg: generally, we mention the subsystem (they are directories under pkg/) in the commit msg. For example, something like eni: Support .... Either you the drop upper-cased AWS and keep eni or you simply use aws: to keep consistent with our process. I think in this case, aws: (lower-case) makes the most sense as this isn't specific to ENI mode.

done

**Review by christarazi — APPROVED** [review]

**Comment by christarazi** [comment]
test-me-please

**Comment by Smana** [comment]
@christarazi Hello, could you please let me know how we can get this PR included for a future release ? I saw a few errors and I don't know if I can be of any help

**Comment by christarazi** [comment]
@Smana All of the CI runs had their link expired, so I can't tell what happened. Would you mind rebasing on latest master and then pinging me? I'll start CI as soon as you rebase.

**Comment by Smana** [comment]
@christarazi ping :) thank you

**Comment by christarazi** [comment]
test-me-please

**Comment by christarazi** [comment]
@Smana Would you mind doing another rebase on master and ping me again? We've been fixing a lot of flakes recently so CI should be good the next time around :)

**Comment by Smana** [comment]
@christarazi no problem, I just rebased it. Hope the tests will be ok now :crossed_fingers:

**Comment by christarazi** [comment]
test-me-please
