### PR TITLE
fix(12664): initialize gops in RootCmd execution function

### LINKED ISSUE #12664: Unable to run cilium-agent --help
```
$ cilium-agent --help 
unable to start gops: open /home/vagrant/.config/gops/20033: permission denied
```

This happen because the user started cilium with root privileges which created the directory `/home/vagrant/.config/gops` with the user `root`:
```
$ ls -la /home/vagrant/.config/gops/
total 16
drwxr-xr-x 2 root root 4096 Jul 24 10:22 .
drwxr-xr-x 3 root root 4096 Jul 23 11:11 ..
-rwxr-xr-x 1 root root    5 Jul 24 10:22 11341
-rwxr-xr-x 1 root root    5 Jul 23 11:11 4888
```

By having this directory with `root`, we can no longer start `cilium-agent` as a regular user.

To fix this we should not initialize `gops` when the using `--help`

### PR DESCRIPTION
**Pull request by fristonio**
daemon/cmd: initialize gops in RootCmd execution function

This commit fixes a bug introduced in 299629d932d8 wherein `cilium-agent --help`
exits with an error(unable to start gops..). This happens because the user started
the cilium-agent process with root privileges which created the directory
`/home/vagrant/.config/gops` with the user root. Any further attempt to run
cilium-agent without root privileges will print out this error.
The commit fixes running commands like `cilium-agent --help`
`cilium-agent --cmdref <dir>` without root privileges by moving gops initialization
to a later stage in the agent.

Fixes: 299629d932d8 "daemon: open socket in agent for gops stack traces"

Fixes: #12664

### CODE REVIEW

**Comment by fristonio** [comment]
test-me-please

File: daemon/cmd/daemon_main.go [hunk 1]
```diff
@@ -109,6 +109,14 @@ var (
 				genMarkdown(cmd, cmdRefDir)
 				os.Exit(0)
 			}
+
+			// Open socket for using gops to get stacktraces of the agent.
+			if err := gops.Listen(gops.Options{}); err != nil {
+				errorString := fmt.Sprintf("unable to start gops: %s", err)
+				fmt.Println(errorString)
```
Comment (sayboras) [inline daemon/cmd/daemon_main.go:116]: nit: what do you think about just return one error here  (e.g. return fmt.Errorf("unable to start gops: %s", err)), and let Execute() method to print error and exit -1

Execute() method
```go
        ...
	if err := RootCmd.Execute(); err != nil {
		fmt.Println(err)
		os.Exit(-1)
	}
```

**Review by sayboras — COMMENTED** [review]
Very nice approach :100:

File: daemon/cmd/daemon_main.go (hunk 1 above)
Comment (sayboras) [reply daemon/cmd/daemon_main.go:116]: oh ignore my above comment. Just notice that this is for Run but not RunE.

**Comment by fristonio** [comment]
test-me-please

**Comment by fristonio** [comment]
retest-4.9

**Comment by fristonio** [comment]
retest-runtime

**Review by aanm — APPROVED** [review]
@tklauser the faulty commit seems to be old, do you think this was introduced when we upgrade gops dependency instead?

**Review by sayboras — APPROVED** [review]

**Comment by tklauser** [comment]
> @tklauser the faulty commit seems to be old, do you think this was introduced when we upgrade gops dependency instead?

Yes, could be related to the changes related to the user config dir in `gops` (google/gops#103). Could be that the faulty behavior only showed up due to the gops update. Might be worth adding

```
Fixes: 3384892f0329 ("vendor: update github.com/google/gops to v0.3.10")
```

to the commit message as well.

**Comment by aanm** [comment]
@tklauser thanks. The PR was merged but we can tell that vendor update was not backported to older branches so we are good.
