### PR TITLE
Neighbor subsystem rework

### LINKED ISSUE #37431: The agent erroneously removes the managed neigh entries on startup
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.0 and lower than v1.18.0

### What happened?

[enableNeighDiscovery](https://github.com/cilium/cilium/blob/c8b31a024e97fb207d756ea634b444e8444cf386/pkg/datapath/linux/node.go#L72) isn't initialized at the time [this code](https://github.com/cilium/cilium/blob/c8b31a024e97fb207d756ea634b444e8444cf386/pkg/datapath/linux/node.go#L1500) is called and `migrateOnly` is always false. As a result, the managed neigh entries are being deleted. `NodeConfigurationChanged` callback initializes `enableNeighDiscovery`  but it hasn't been called when the daemon calls `NodeCleanNeighbors`.

This causes connection disruption when the XDP acceleration is enabled.

### How can we reproduce the issue?

Restart a cilium-agent Pod.

### Cilium Version

v1.17 (main branch)

### Kernel Version

Linux 320 6.8.0-52-generic #53~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jan 15 19:18:46 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.32.1

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### LINKED ISSUE #38200: Improve neighbor subsystem resilience
## Problem

The current neighbor subsystem was made for nodes, and later extended to services. While it works in the majority of cases, there are some situations where it can fail. It was built in a time where we did not have the same reconciliation capabilities as we do now.

Here is a list of known issues:
- We currently do not detect when neighbor entries go away, which can happen when an interface goes down or when manually deleted. 
- Our neighbor table entries are based on the next hop of an address, however, if routes change we do not update these entries. 
- On pre-v5.16 kernels, the kernel does not automatically refresh stale externally managed neighbor entries. We implement a mechanism to do this, however, it lives at the node manager level. This means only entries for nodes are refreshed, but not those for services.

To fix all of the above, I propose to rework the architecture of the neighbor subsystem.

## New neighbor subsystem

Image

The overarching goal for this subsystem is to take a set of "Forwardable IP"s and ensure the kernels neighbor table always has fresh entries for them. This ensures that XDP programs will always have be able to forward traffic for a given IP using the kernels FIB.

These "Forwardable IP"s will be stored in a StateDB table. Each entry having an IP (`netip.Addr`), and a list of "owners". An owner being any other component of Cilium which wants to ensure that the IP is forwardable (For now node manager and services).

The neighbor entries are actually the next hops for the "Forwardable IP"s for every "selected device" that is also an L2 device. We can get these from the `statedb.Table[*tables.Device]` table, as well as subscribe to changes. The most reliable way to get a next hop for a given IP is to query the FIB using `netlink.RouteGetWithOptions`. However, doing netlink requests is expensive, and we have no direct way of getting notified when the result changes. Therefor we use the `statedb.Table[*tables.Route]` table as a proxy for the FIB, but only for getting a signal on change, we will still use `netlink.RouteGetWithOptions` to get the actual next hop. All of this results in a desired state which we will store in a new table `statedb.Table[DesiredNeighbor]`.

A reconciler will watch both the `statedb.Table[DesiredNeighbor]` and `statedb.Table[*tables.Neighbor]` tables to detect when the actual state and desired state deviate. When they do, the reconciler will update the kernel neighbor table to match the desired state. Table initializers at every level will ensure the first reconciliation after agent startup is done once all tables are populated to ensure we do not prune any existing entries that may actually be in use.

On kernels earlier than v5.16, the kernel does not automatically refresh stale externally managed neighbor entries. We have probes to detect this. On these older kernels, an additional task of the reconciler is to re-insert entries that have gone stale. There are three possible mechanisms for this, which the implementor will have to choose from:
- Use a separate job to periodically mark the entries such that the reconciler will re-insert them.
- Use the existing refresh logic in the generic reconciler [config.RefreshInterval](https://github.com/cilium/statedb/blob/f0c88229f440e90a671e5410ae98652aef5ee2d4/reconciler/config.go#L50)
- Use the reported state from `statedb.Table[*tables.Neighbor]` to see when the kernel marks an entry as stale, and then re-insert it.

### LINKED ISSUE #38321: CI: CPU usage regression
Since PR in https://github.com/cilium/cilium/pull/37352 we have seen regression in CPU usage in CI for scale test that generates high churn of backends of services.
With that PR, we are pushing each backend to neighbor system which invokes netlink ~3 times underneath for each backend updated. Additional testing shows around ~0.5 CPU usage increase with 200/s backends churn. 

Image
As we can see, runtime.newobject/mallocgc dominates cpu profiles.
This is most likely due to high rate of allocations that netlink perform underneath:
Image
Most likely here:
https://github.com/cilium/cilium/blob/1271223b84049edd879c952c2f75a8324f14ce66/vendor/github.com/vishvananda/netlink/nl/nl_linux.go#L886
and here: https://github.com/cilium/cilium/blob/1271223b84049edd879c952c2f75a8324f14ce66/vendor/github.com/vishvananda/netlink/nl/nl_linux.go#L921

Marking this as release-blocker for v1.18.
We have to choices:
- either revert mentioned PR
- Improve upstream netlink library

### LINKED ISSUE #39499: NodeNeighborLinkUpdater memory usage regression
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.17.3 and lower than v1.18.0

### What happened?

Memory regression is happening on main. 
Since https://github.com/cilium/cilium/pull/39001 was merged, memory usage of cilium-agent increased by 3-4% in scale-tests. Most of the memory increase is coming from health-reporting:

Image

It seems fairly excessive to report health per each node and each service backed: https://github.com/cilium/cilium/blob/07f37d3a5b0d0158c7a137690a961c18fae05a2c/pkg/node/manager/manager.go#L1393
Proposal: 
Instead of reporting health per each backend/node, let's report health one time with number of refreshed and failed entries.

### How can we reproduce the issue?

CI/scale-test

### Cilium Version

main

### Kernel Version

N/A

### Kubernetes Version

N/A

### Regression

yes

### Sysdump

Pprofs in zip file

[files.zip](https://github.com/user-attachments/files/20161914/files.zip)

### Relevant log output

```shell

```

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dylandreimerink**
This PR reworks the code we have for managing neighbor entries in the kernel. At present this logic lives in the node manager and linux node handler. 

When forwarding traffic in eBPF programs we use the FIB to find out to which L2 address we should forward that packet. The kernel uses the routing table to determine the next hop and the neighbor table to determine the L2 address of that nexthop. If no neighbor table entry exists for a given L3 address, the kernel would normally use something like ARP or ICMPv6 at that point to resolve one. This works in TC, but not XDP because in XDP context we are not allowed to delay processing of that packet to wait for the ARP/ICMPv6 resolution, and we have to drop the packet instead. So we need to ensure we always have neighbor entries for all possible next hops we would like to forward traffic to.

The existing logic had a few shortcomings:
* On older kernel the agent has to re-create neighbor entries to refresh them, in case the L2 address of an IP changed. The old system was only able to do this for neighbor entries for node IPs not for service IPs.
* The old system did not actively reconcile against the neighbor table, when neighbor entries were deleted by events such as a link carrier down, then it could take a long time before those entries were recreated
* Changes to devices and routes were not processed, resulting in possible bad entries when device failover occurred or default gateways are changed at runtime
* On agent startup, we would delete neighbor entries before desired neighbor entries were know. So we briefly removed all existing neighbor entries during restarts, causing short periods of traffic drops.

We want to address all of these by implementing the design as discussed in #38200. In short, we introduce the concept of a "Forwardable IP", each IP can have multiple owners. We query the kernel FIB for the next hop of each forwardable IP for each L2 device and de duplicate, the result are our "Desired Neighbors". We use the route and device stateDB table (also reflections of the kernel) to trigger recalculation of the desired neighbors. The desired neighbors are actively reconciled against the neighbor stateDB table which is reflection of the actual neighbor table. Refreshing of neighbor entries happens as part of the active feedback loop when needed. 

This design ensure the neighbor table reconciles as fast as possible, while doing as little work as possible when no external events occur. We incidentally also make it very easy to inspect all of this state and to write powerful integration tests that verify proper cooperation between this new logic, the device controller and kernel. 

> [!TIP]
> Reviewers are encouraged to review commit-by-commit. Commit messages contain additional details.

Fixes: #38200
Fixes: #39499
Fixes: #38321
Fixes: #37431

```release-note
Reworked the neighbor subsystem to be more resilient
```

### CODE REVIEW

File: pkg/node/manager/node_config_notifier.go [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+}
+
+func newNodeConfigNotifier() *NodeConfigNotifier {
+	return &NodeConfigNotifier{
+		handlers: make([]datapath.NodeConfigChangeHandler, 0),
+	}
+}
+
+func (n *NodeConfigNotifier) Subscribe(handler datapath.NodeConfigChangeHandler) {
+	n.handlers = append(n.handlers, handler)
```
Comment (gandro) [inline pkg/node/manager/node_config_notifier.go]: How is it guaranteed that this function is not called from multiple go routines concurrently?

If the reason is that it is intended to only be used used in Hive constructors (which are guaranteed to be sequential), why not use a Hive `group`? In any case, if this is kept either document that this is not thread-safe or add a mutex.

File: pkg/node/manager/node_config_notifier.go [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+}
+
+func (n *NodeConfigNotifier) Unsubscribe(handler datapath.NodeConfigChangeHandler) {
+	for i, h := range n.handlers {
```
Comment (gandro) [inline pkg/node/manager/node_config_notifier.go]: nit: We could use `slices.DeleteFunc` here. But overall the unsubscribe logic is not even used. Why implement it?

File: install/kubernetes/cilium/values.yaml [hunk 3]
```diff
@@ -2114,7 +2114,7 @@ readinessProbe:
 kubeProxyReplacementHealthzBindAddr: ""
 l2NeighDiscovery:
   # -- Enable L2 neighbor discovery in the agent
-  enabled: true
+  enabled: false
   # -- Override the agent's default neighbor resolution refresh period.
   refreshPeriod: "30s"
```
Comment (gandro) [inline install/kubernetes/cilium/values.yaml]: Isn't `refreshPeriod` removed also? Please also document the removal in the upgrade notes.

File: install/kubernetes/cilium/values.yaml [hunk 4]
```diff
@@ -2114,7 +2114,7 @@ readinessProbe:
 kubeProxyReplacementHealthzBindAddr: ""
 l2NeighDiscovery:
   # -- Enable L2 neighbor discovery in the agent
-  enabled: true
```
Comment (gandro) [inline install/kubernetes/cilium/values.yaml:2120]: Please document the changes in default values in the upgrade nodes.

**Review by gandro — COMMENTED** [review]
Reviewed mainly for my code owners (which have trivial changes). I didn't look at most of the `pkg/datapath` code. Minor bits of feedback on the rest.

File: pkg/node/manager/node_config_notifier.go (hunk 1 above)
Comment (dylandreimerink) [reply pkg/node/manager/node_config_notifier.go]: That is exactly the reason. Its only meant to be called from hive constructors.

>  why not use a Hive `group`?

I think consensus amongst sig-foundation is that having a observer pattern like this is desirable over using a `group`  unless you have a good reason to use groups.

Explicitly subscribing via a method makes it easier to find the dependency. With groups you have to search for functions returning the handler interface, a more difficult query. The registrar (`NodeConfigNotifier` in this case) is also explicitly added to the parameters of call constructors that so something with it. 

A group is still a good option when manual registration would add a disproportional burden. Take metrics for example, having them be collected in a single group automatically instead of manually registering tens of not hundreds of individual metrics makes it worth it.

Another good reason for groups over explicit registration is the dependency order. In this example, the `NodeConfigNotifier` has no dependencies, and both the handlers and caller depend on `NodeConfigNotifier`.

With a group, the `NodeConfigNotifier` would depend on the handlers, and the caller on the `NodeConfigNotifier`, which makes it more likely that you accidentally create a dependency cycle, which is impossible with explicit registration when done in this way.

\</rambling>

> In any case, if this is kept either document that this is not thread-safe or add a mutex.

Yes, very good idea. I will also detection for modification after construction time, since that would also be unexpected.

File: pkg/node/manager/node_config_notifier.go (hunk 2 above)
Comment (dylandreimerink) [reply pkg/node/manager/node_config_notifier.go]: I can't even recall why I added this, mostly because my brain went into "implement observer patten" mode. Will remove :+1:

File: install/kubernetes/cilium/values.yaml (hunk 3 above)
Comment (dylandreimerink) [reply install/kubernetes/cilium/values.yaml]: Yes, it was removed in an earlier commit. I forgot to remove it from the values. Will fix. Change is already noted in the upgrade nodes.

File: pkg/node/manager/node_config_notifier.go (hunk 1 above)
Comment (gandro) [reply pkg/node/manager/node_config_notifier.go]: Neat, thanks for changing it! 

>  I will also detection for modification after construction time, since that would also be unexpected.

This is clever. I do think however a log line (rather than a error return value) would be much better. The error could be ignored by callers (in fact, the current callers do also ignore it) and thus it might never be seen by a developer. Having a log line with level warning will also make sure CI fails if someone adds this.

Comment (dylandreimerink) [reply pkg/node/manager/node_config_notifier.go]: Yes, absolutely right.

File: pkg/datapath/neighbor/desired_neighbor_calculator.go [hunk 5]
```diff
@@ -0,0 +1,305 @@
...
+		tx := c.DB.WriteTxn(c.DesiredNeighborTable)
+
+		// If we are doing a full sync, first delete all entries that should not be
+		// present anymore.
+		if needFullSyn {
+			for dn := range c.DesiredNeighborTable.All(rx) {
+				// If the desired neighbor is not in the set of unique desired neighbors,
+				// delete it.
+				if _, ok := uniqueDesiredNeighbors[dn.DesiredNeighborKey]; !ok {
+					_, _, err := c.DesiredNeighborTable.Delete(tx, dn)
```
Comment (borkmann) [inline pkg/datapath/neighbor/desired_neighbor_calculator.go]: quick q: when a node in the cluster gets added and we add it to desired neighbor as well as a service backend, then that desired neighbor has two 'owners', what happens if one is going away but not the other? Do we have some implicit refcounting or detect this otherwise? (I presume agent restarts are survived as we persist the state table?)

File: pkg/datapath/neighbor/desired_neighbor_calculator.go [hunk 6]
```diff
@@ -0,0 +1,305 @@
...
+		// Select a gw for the specified link if there are multi paths to the nodeIP
+		// For example, the nextHop to the nodeIP 9.9.9.9 from eth0 is 10.0.1.2,
+		// from eth1 is 10.0.2.2 as shown bellow.
+		//
+		// 9.9.9.9 proto bird metric 32
+		//        nexthop via 10.0.1.2 dev eth0 weight 1
+		//        nexthop via 10.0.2.2 dev eth1 weight 1
+		//
+		// NOTE: We currently don't handle multiple next hops, so only one next hop
+		// per device can be used.
```
Comment (borkmann) [inline pkg/datapath/neighbor/desired_neighbor_calculator.go:276]: would probably be good to document in a GH issue what would roughly be needed in order to support this in future so we don't forget about it once we pick that up

File: pkg/datapath/neighbor/forwardable_ip.go [hunk 7]
```diff
@@ -0,0 +1,235 @@
...
+		return err
+	}
+
+	tx.Commit()
+	return nil
+}
+
+// Delete removes and IP from the table for a given owner. If an IP has multiple owners,
+// the given owner is removed from the list of owners. If the last owner is removed,
+// the IP is deleted from the table.
```
Comment (borkmann) [inline pkg/datapath/neighbor/forwardable_ip.go:188]: Ok, that answers prior question :)

File: daemon/cmd/daemon_main.go [hunk 8]
```diff
@@ -195,7 +195,7 @@ func InitGlobalFlags(logger *slog.Logger, cmd *cobra.Command, vp *viper.Viper) {
 	flags.Bool(option.AnnotateK8sNode, defaults.AnnotateK8sNode, "Annotate Kubernetes node")
 	option.BindEnv(vp, option.AnnotateK8sNode)
 
-	flags.Bool(option.EnableL2NeighDiscovery, true, "Enables L2 neighbor discovery used by kube-proxy-replacement and IPsec")
+	flags.Bool(option.EnableL2NeighDiscovery, false, "Enables L2 neighbor discovery used by kube-proxy-replacement and IPsec")
```
Comment (borkmann) [inline daemon/cmd/daemon_main.go]: Lets auto-enable it when either of the two features are enabled? XDP is definitely broken without this work, so it is critically needed. Auto-enabling means also less hassle for users.

**Review by borkmann — APPROVED** [review]
Looking forward to see this land, this is a major step forward! Thanks!

**Comment by borkmann** [comment]
Also, do we automatically dump all tables into the sysdump or should we add `db/show neighbors` specifically to make sure we have the agent view for troubleshooting?

File: Documentation/network/kubernetes/kubeproxy-free.rst [hunk 9]
```diff
@@ -1575,9 +1575,7 @@ pushes L3 addresses of new nodes into the kernel for dynamic resolution, but wit
 agent triggered periodic refresh. For introspection, iproute2 displays them only as
 "extern_learn" in this case. If there is no active traffic for a certain period of
 time, then a Cilium agent controller triggers the Linux kernel-based re-resolution for
-attempting to keep them in REACHABLE state. The refresh interval can be changed if needed
-through a ``--arping-refresh-period=30s`` flag passed to the cilium-agent. The default
-period is ``30s`` which corresponds to the kernel's base reachable time.
+attempting to keep them in REACHABLE state.
 
 The neighbor discovery supports multi-device environments where each node has multiple devices
```
Comment (borkmann) [inline Documentation/network/kubernetes/kubeproxy-free.rst:1573]: The docs section could probably also get a refresher on how the agent is handling corner cases like link-flaps etc and what current limitations we have.

File: pkg/datapath/loader/netlink_unparallel_test.go [hunk 10]
```diff
@@ -0,0 +1,93 @@
...
+	"github.com/cilium/cilium/pkg/testutils/netns"
+)
+
+func TestSetupIPIPDevices(t *testing.T) {
+	testutils.PrivilegedTest(t)
+	logger := hivetest.Logger(t)
+
+	sysctl := sysctl.NewDirectSysctl(afero.NewOsFs(), "/proc")
+
+	err := sysctl.WriteInt([]string{"net", "core", "fb_tunnels_only_for_init_net"}, 0)
```
Comment (rgo3) [inline pkg/datapath/loader/netlink_unparallel_test.go:28]: That's why the test needs to be run sequentially, correct?

**Review by rgo3 — APPROVED** [review]
Only reviewed the loader related changes around the `NodeConfigurationChanged` refactor, that LGTM.

File: pkg/datapath/neighbor/desired_neighbor_calculator.go (hunk 5 above)
Comment (dylandreimerink) [reply pkg/datapath/neighbor/desired_neighbor_calculator.go]: > when a node in the cluster gets added and we add it to desired neighbor as well as a service backend, then that desired neighbor has two 'owners', what happens if one is going away but not the other?

The forwardable IP manager handles this. It effectively has a refcount in the form of a slice of "owners", only when the last owner removes the forwardable IP does get removed from the table.

Comment (dylandreimerink) [reply pkg/datapath/neighbor/desired_neighbor_calculator.go]: > I presume agent restarts are survived as we persist the state table

We do not persist the state table, we re-construct it after restart. The initializers ensure that we only start removing neighbors when we have fully rebuilt (all nodes and services processed)

File: daemon/cmd/daemon_main.go (hunk 8 above)
Comment (dylandreimerink) [reply daemon/cmd/daemon_main.go]: Yea, can do.

**Comment by dylandreimerink** [comment]
> Also, do we automatically dump all tables into the sysdump or should we add db/show neighbors specifically to make sure we have the agent view for troubleshooting?

All tables are automatically dumped in sysdumps, no need to do it manually.

File: pkg/datapath/loader/netlink_unparallel_test.go (hunk 10 above)
Comment (dylandreimerink) [reply pkg/datapath/loader/netlink_unparallel_test.go:28]: Yes, that is correct. Some tests, namely those involving tunnel devices implicitly enable certain kernel modules. This particular test is a bit odd since it only works when this value is set to the `0` the default. Even though in the agent we always set this to `2` right before calling the same function under test here.

When set to `0` the kernel modules create fallback devices in network namespaces which makes it impossible to assert on ifindex numbers like we need for the neighbor tests.

So we make this test unparallel and set the sysctl explicitly so we don't race on the sysctl with other tests and stop relying on implicit settings.

Did the same with the neighbor tests just in reverse.

File: .github/workflows/conformance-ingress.yaml [hunk 11]
```diff
@@ -173,6 +173,7 @@ jobs:
             --helm-set=ingressController.loadbalancerMode=${{ matrix.loadbalancer-mode }} \
             --helm-set=ingressController.default=${{ matrix.default-ingress-controller }} \
             --helm-set=extraConfig.bpf-lb-acceleration=${{ matrix.bpf-lb-acceleration }} \
+            --helm-set=l2NeighDiscovery.enabled=true \
```
Comment (mhofstetter) [inline .github/workflows/conformance-ingress.yaml]: why is it necessary to set this for `conformance-ingress.yaml` but not `conformance-gateway-api.yaml`? :thinking:

File: pkg/node/manager/node_config_notifier.go [hunk 12]
```diff
@@ -0,0 +1,56 @@
...
+		return
+	}
+
+	n.handlers = append(n.handlers, handler)
+}
+
+func (n *NodeConfigNotifier) Notify(nodeConfig datapath.LocalNodeConfiguration) error {
+	var errs error
+	for _, handler := range n.handlers {
+		if err := handler.NodeConfigurationChanged(nodeConfig); err != nil {
```
Comment (mhofstetter) [inline pkg/node/manager/node_config_notifier.go]: nit: error-handling could be simplified because `errors.Join` automatically discards `nil` errors.

**Review by mhofstetter — APPROVED** [review]
Thanks, looks good for my codeowners.

File: .github/workflows/conformance-ingress.yaml (hunk 11 above)
Comment (dylandreimerink) [reply .github/workflows/conformance-ingress.yaml]: Because `conformance-ingress` has permutations where it enables XDP, and `conformance-gateway-api` does not seem to test with XDP.

**Review by gandro — APPROVED** [review]
LGTM for my codeowners

File: .github/workflows/conformance-ingress.yaml (hunk 11 above)
Comment (mhofstetter) [reply .github/workflows/conformance-ingress.yaml]: Thanks for the info! maybe it would make sense to make this more explicit by setting the helm value to `true` conditionally if `matrix.bpf-lb-acceleration==native`?

Comment (dylandreimerink) [reply .github/workflows/conformance-ingress.yaml]: I initially had it in there since it cannot hurt to have it enabled when XDP not active, even if its not strictly needed.  I am changing the logic now to automatically enable when XDP acceleration enabled. So I think I will just go ahead and remove this line, it will auto enable when needed.

File: daemon/cmd/daemon_main.go (hunk 8 above)
Comment (dylandreimerink) [reply daemon/cmd/daemon_main.go]: Made this change. We now automatically enable L2 neighbor discovery when XDP is enabled. We still have the flag so you enable it without XDP for testing or some other purpose. But the UX should be better now.

File: Documentation/network/kubernetes/kubeproxy-free.rst (hunk 9 above)
Comment (dylandreimerink) [reply Documentation/network/kubernetes/kubeproxy-free.rst:1573]: I updated the docs, they should align now with the latest changes.

**Comment by joestringer** [comment]
Hi, are you intending for this to make v1.18? Feature freeze is on Monday, which is practically speaking about one working day away. Given the size and scope of this PR, it could introduce significant risk to the release at this time. How do we feel about the ability to review such a big submission, how the test coverage is, and the likelihood that we are able to ensure this rewrite meets the quality we desire in the project over the coming month or so prior to 1.18 final?

**Review by christarazi — APPROVED** [review]

**Comment by borkmann** [comment]
imho I would love to see this land in v1.18 given this fixes several issues with neighbor entries as pointed out in the PR description, so this is definitely a big resiliency improvement over the status quo.

File: Documentation/network/kubernetes/kubeproxy-free.rst [hunk 13]
```diff
@@ -1536,30 +1536,17 @@ set ``loadBalancer.serviceTopology=true``.
 Neighbor Discovery
 ******************
 
-When kube-proxy replacement is enabled, Cilium does L2 neighbor discovery of nodes
-in the cluster. This is required for the service load-balancing to populate L2
-addresses for backends since it is not possible to dynamically resolve neighbors
+When kube-proxy replacement and XDP acceleration is enabled, Cilium does L2 neighbor discovery
```
Comment (qmonnet) [inline Documentation/network/kubernetes/kubeproxy-free.rst]:
```suggestion
When kube-proxy replacement and XDP acceleration are enabled, Cilium does L2 neighbor discovery 
```

File: Documentation/network/kubernetes/kubeproxy-free.rst [hunk 14]
```diff
@@ -1536,30 +1536,17 @@ set ``loadBalancer.serviceTopology=true``.
...
-entry in the kernel (due to the entry being garbage collected or given that the neighbor
-resolution has not been done by the kernel). This is because it is not possible to drive
-the neighbor resolution from BPF programs in the fast-path e.g. at the XDP layer.
-
-From Cilium 1.11 onwards, the neighbor discovery has been fully reworked and the Cilium
-internal ARP resolution library has been removed from the agent. The agent now fully
-relies on the Linux kernel to discover gateways or hosts on the same L2 network. Both
-IPv4 and IPv6 neighbor discovery is supported in the Cilium agent. As per our recent
+L2 neighbor discovery is automatically enabled when the agent detects that XDP is in use, but
+can also be manually setting the ``--enable-l2-neigh-discovery=true`` flag or
```
Comment (qmonnet) [inline Documentation/network/kubernetes/kubeproxy-free.rst]:
```suggestion
can also be manually turned on by setting the ``--enable-l2-neigh-discovery=true`` flag or
```

File: Documentation/network/kubernetes/kubeproxy-free.rst [hunk 15]
```diff
@@ -1571,13 +1558,17 @@ neighbor entries are dynamically resolved and periodically refreshed by the Linu
...
-agent triggered periodic refresh. For introspection, iproute2 displays them only as
-"extern_learn" in this case. If there is no active traffic for a certain period of
-time, then a Cilium agent controller triggers the Linux kernel-based re-resolution for
-attempting to keep them in REACHABLE state. The refresh interval can be changed if needed
-through a ``--arping-refresh-period=30s`` flag passed to the cilium-agent. The default
-period is ``30s`` which corresponds to the kernel's base reachable time.
+pushes L3 addresses of new nodes into the kernel for dynamic resolution. For introspection, 
+iproute2 displays them only as "extern_learn" in this case. If there is no active traffic 
+for a certain period of time and entries become state, the Cilium agent  triggers the 
+Linux kernel-based re-resolution for attempting to keep them in REACHABLE state.
```
Comment (qmonnet) [inline Documentation/network/kubernetes/kubeproxy-free.rst]:
```suggestion
iproute2 displays them only as ``extern_learn`` in this case. If there is no active traffic 
for a certain period of time and entries become state, the Cilium agent triggers the 
Linux kernel-based re-resolution for attempting to keep them in ``REACHABLE`` state.
```

**Review by qmonnet — APPROVED** [review]
I just checked doc changes and they look good, with a small non-blocking nits (please see inline below). Nice work!

**Comment by dylandreimerink** [comment]
> Hi, are you intending for this to make v1.18?

That is/was my hope. I had intended to get this PR ready for review earlier, but some CI issues and the like delayed that.
Like @borkmann mentioned, this fixes a number of issues with regards to the resilience of neighbor entries.

It also resolves some regressions which are marked as release blockers already. However, those can technically also be solved in smaller PRs and do not require all of this work.

It would be really nice to get it in so we can reap the reward, but I am fully aware its a stretch goal.

>  How do we feel about the ability to review such a big submission, how the test coverage is, and the likelihood that we are able to ensure this rewrite meets the quality we desire in the project over the coming month or so prior to 1.18 final?

I think the ability to review is an important consideration, I definitely do not want to rush anything or anyone, and I realize this is a big diff which requires time.

As to the test coverage, I am fairly confident about this change. The newly added logic is tested with the kernel in the loop, which is as close to real as I can make it. Test coverage profile show good coverage (can still be improved though). The code also implicitly run in all E2E tests involving XDP.

I would be happy to add additional tests if you feel the current set is lacking in any area so we may boost confidence.

**Review by marseel — APPROVED** [review]
lgtm for clustermesh changes - I see that others reviewed for sig-agent/sig-k8s

**Review by joamaki — APPROVED** [review]

**Review by aanm — APPROVED** [review]

**Comment by dylandreimerink** [comment]
> The identifier 'ForwarableIPCell' appears to contain a typo; consider renaming it to 'ForwardableIPCell' to match the documented concept of 'Forwardable IP'.

Its a nit, but its a valid nit. Will fix that.

**Comment by joestringer** [comment]
Given the momentum on this PR and support from multiple committers and all the reviewers, it seems worthwhile to accept this as a release blocker and grant an exception to the feature freeze date. Personally I would not review or merge a PR this big, but I am not going to be the person standing in the way. I'll defer to you as a committer for what's best for this area of the tree.
