### PR TITLE
bpf:trace: adjust TRACE_PAYLOAD_LEN for overlay packets

### LINKED ISSUE #39030: monitor:hubble: incorrectly decoded TCPv6-over-vxlan
After https://github.com/cilium/cilium/pull/37634, all types of flows will be correctly decoded from userspace Hubble/Monitor, except those exceeding the amount of bytes pushed during the trace/drop notification event. Let's ignore those when we monitor less bytes through connection tracking and aggregation, and focus when providing the TRACE_PAYLOAD_LEN (128B) value.

In the case of a TCPv6-over-vxlan packet, the amount of bytes needed to decode a SYN packet with options is at least `14B (ethernet) + 20B (ipv4) + 8B (udp) + 8B (vxlan) + 14B (ethernet) + 40B (ipv6) + >=20B (tcp+opts) = >=124`. In case this exceed 128B, the decode fails and simply displays  `[error]`, while the actual error was `TCP data offset greater than packet length` (monitor).

Given also we introduced support for IPv6 underlay, or future DSR-over-ipv6, and given that after https://github.com/cilium/cilium/pull/39650 the datapath can tell when a packet is Overlay, let's provide a new config value rather than the old TRACE_PAYLOAD_LEN to push additional bytes.

### PR DESCRIPTION
**Pull request by smagnani96**
~Blocked by https://github.com/cilium/cilium/pull/39650.~ Good to have (non-blocking) for https://github.com/cilium/cilium/pull/37634.

As described in commit messages, when tracing overlay packets the default TRACE_PAYLOAD_LEN might not be enough. An example would be an Overlay IPv4 packet carrying an IPv6 TCP packet with Options (MSS, etc., such as a SYN packet). In that case, Hubble would fail decoding such packet due to missing bytes. Same problems would arise in case of IPv6 underlay.

For this reason:
1. move `TRACE_PAYLOAD_LEN` to `CONFIG(trace_payload_len)` for coherency with the new datapath config, and use it to trace native packets
2. introduce `CONFIG(trace_payload_len_overlay)` and use it for tracing overlay packets
3. postpone the computation of capture_length when tracing to only when the trace needs to be omitted
4. add an helper to accomplish (3) based on the current classifier flags: use (2) when CLS_FLAG_{VXLAN,GENEVE} is set, (1) otherwise.

Fixes: https://github.com/cilium/cilium/issues/39030.

### CODE REVIEW

File: bpf/lib/common.h [hunk 1]
```diff
@@ -539,8 +539,12 @@ enum {
 	CAPTURE_EGRESS = 2,
 };
 
+/* Minimum bytes for decoding packet headers during trace events.
+ * - Outer: 14 (ethernet) + 40 (ipv6) + 8 (udp) + 8 (geneve) + 24 (geneve v6 opts)
+ * - Inner: 14 (ethernet) + 40 (ipv6) + 8 (udp)
+ */
 #ifndef TRACE_PAYLOAD_LEN
-#define TRACE_PAYLOAD_LEN 128ULL
+#define TRACE_PAYLOAD_LEN 156ULL
```
Comment (julianwiedmann) [inline bpf/lib/common.h]: I wonder whether we really need to bump the default size. Or can have a `TRACE_PAYLOAD_OVERLAY_LEN`, and plug it in at the right places (based on `ctx_is_overlay()` etc), given that it should only be used on a native device level (and in bpf_wireguard)

**Comment by julianwiedmann** [comment]
> Outer: 14 (ethernet) + 40 (ipv6) + 8 (udp) + 8 (geneve) + 24 (geneve v6 opts)

You might want to consider one level of VLAN header in this calculation, to be on the safe side.

File: bpf/lib/common.h (hunk 1 above)
Comment (smagnani96) [reply bpf/lib/common.h]: Thanks for the precious feedback. I tried to address it at my best, just updated the PR to achieve a similar behavior. 🙏🏼 

Closing this since outdated code, but super happy to start a new one!

**Comment by smagnani96** [comment]
Marking this as ready-for-review to start gathering feedback.
Will wait for the parent PR to get merged first: there shouldn't be substantial changes in between, and this PR is a good-to-have for the final Hubble PR.

**Comment by smagnani96** [comment]
Haven't run `ci-verifier` yet in this PR, but let me also report an interesting data.
Comparing locally kernel v6.6 N. verified instruction `THIS_BRANCH (after) - main (before)`:

bpf_host_6

Worst case increase +12k, Best case saved -350k. If found to be useful, I can also think of a partial backport of this PR. In that case, I believe most relevant commits would be:

* `bpf: move TRACE_PAYLOAD_LEN to node config variable`
* `bpf:classifiers: add ctx_capture_length for postponing computation`, the postponing part.

Here's the full zip for curious [insn-diff-66_log-wrt-main66_log-20250609_173029.zip](https://github.com/user-attachments/files/20657263/insn-diff-66_log-wrt-main66_log-20250609_173029.zip).

File: Documentation/cmdref/cilium-agent.md [hunk 2]
```diff
@@ -387,7 +387,7 @@ cilium-agent [flags]
       --tofqdns-pre-cache string                                  DNS cache data at this path is preloaded on agent startup
       --tofqdns-proxy-port int                                    Global port on which the in-agent DNS proxy should listen. Default 0 is a OS-assigned port.
       --tofqdns-proxy-response-max-delay duration                 The maximum time the DNS proxy holds an allowed DNS response before sending it along. Responses are sent as soon as the datapath is updated with the new IP information. (default 100ms)
-      --trace-payloadlen int                                      Length of payload to capture when tracing (default 128)
+      --trace-payloadlen int                                      Length of payload to capture when tracing packets. (default 128)
```
Comment (tommyp1ckles) [inline Documentation/cmdref/cilium-agent.md]: Is this auto aligned to the cache line size? should we mention that or otherwise specify that it needs to be that.

File: bpf/lib/classifiers.h [hunk 3]
```diff
@@ -36,7 +36,49 @@ enum {
 		 (TUNNEL_PROTOCOL) == TUNNEL_PROTOCOL_GENEVE ? CLS_FLAG_GENEVE : \
 		 (__throw_build_bug(), 0))                        \
 	: (__throw_build_bug(), 0))
-#endif
+
+/**
+ * supports_overlay_mark
+ * @obs_point: trace observation point (TRACE_{FROM,TO}_*)
+ *
+ * Returns true whether the provided observation point can observe Overlay traffic marked with the
```
Comment (tommyp1ckles) [inline bpf/lib/classifiers.h]: nit: observe Overlay traffic -> observe overlay traffic

**Review by tommyp1ckles — APPROVED** [review]

**Review by dylandreimerink — APPROVED** [review]
Looking good for the loader codeowner changes.

**Review by brb — APPROVED** [review]

**Review by kaworu — APPROVED** [review]

**Comment by smagnani96** [comment]
* Rebased
* Refactored `ctx_capture_len` -> `compute_capture_len`
* Refactored `supports_overlay_mark` -> `can_observe_overlay_mark`
* Refactored `supports_overlay_header` -> `can_observe_overlay_hdr`
* Added additional 2 BPF tests for `trace_payload_len / trace_payload_len_overlay`

No functional changes wrt previous reviews.

File: Documentation/cmdref/cilium-agent.md (hunk 2 above)
Comment (smagnani96) [reply Documentation/cmdref/cilium-agent.md]: Yes, those values are aligned to cache size (64B).
I introduced comments in `defaults.TracePayloadlen` and `defaults.TracePayloadlenOverlay`.
IMHO, we should not report the full explanation in these cli params, code comments should be enough as these values are mainly used by devs (or not used at all).
