### PR TITLE
endpoint: Avoid unnecessarily logging a warning during endpoint deletion

### LINKED ISSUE #40924: CI: ci-clustermesh: check-log-errors: Failed while waiting for initial global identities
## CI failure

Hit on https://github.com/cilium/cilium/pull/40863 which has a small metrics bugfix and a new linter, so the failure should be unrelated to those changes.

https://github.com/cilium/cilium/actions/runs/16729347210/job/47353347967#step:53:480

```
📋 Test Report [cilium-test-1]
❌ 1/8 tests failed (1/168 actions), 117 tests skipped, 3 scenarios skipped:
Test [check-log-errors]:
  🟥 check-log-errors/no-errors-in-logs:pkg/endpoint:kind-cluster2/kube-system/cilium-6rwbw (cilium-agent): Found 1 logs in kind-cluster2/kube-system/cilium-6rwbw (cilium-agent) matching list of errors that must be investigated:
time=2025-08-04T17:08:47.700575884Z level=warn source=/go/src/github.com/cilium/cilium/pkg/endpoint/restore.go:308 msg="Failed while waiting for initial global identities" ciliumEndpointName=kube-system/clustermesh-apiserver-5777d847d9-j4vh7 endpointID=192 containerInterface=eth0 identity=16728613 datapathPolicyRevision=0 ipv4=10.244.2.190 desiredPolicyRevision=0 containerID=d698eee51b ipv6=fd00:10:244:2::ea15 k8sPodName=kube-system/clustermesh-apiserver-5777d847d9-j4vh7 subsys=endpoint error="identity sync was cancelled: context canceled" (1 occurrences)
    ⛑️ The following owners are responsible for reliability of the testsuite: 
        - @cilium/endpoint (no-errors-in-logs:pkg/endpoint)
        - @cilium/sig-clustermesh (.github/workflows/tests-clustermesh-upgrade.yaml)
        - @cilium/ci-structure (.github/workflows/tests-clustermesh-upgrade.yaml)
[cilium-test-1] 1 tests failed
Error: Process completed with exit code 1.
```

Sysdump is too large to attach.

### PR DESCRIPTION
**Pull request by christarazi**
It is possible during endpoint restoration for the endpoint to be
deleted in the middle of the process. If the endpoint restoration
process was waiting for global identities to be synced and the deletion
occurs, then the wait for the sync will be canceled. This triggers an
unnecessary warning log. To fix, detect that the endpoint is deleted
which we can tell by checking if the context was canceled.

See https://github.com/cilium/cilium/issues/40924 for more details.

Fixes: https://github.com/cilium/cilium/issues/40924
Signed-off-by: Joe Stringer <joe@cilium.io>
Signed-off-by: Chris Tarazi <chris@isovalent.com>

### CODE REVIEW

**Review by joestringer — APPROVED** [review]
LGTM, thanks!

**Comment by joestringer** [comment]
Not sure whether v1.18 is affected by this or not to mark for v1.18 backport - I saw this failure condition for the first time today. I just don't know whether we saw it now because we changed something about startup ordering or if it's always been possible and it's just rare enough we don't often see it.

**Comment by joestringer** [comment]
I'm OK with backporting this as it's just changing the logging for this condition.

File: pkg/endpoint/restore.go [hunk 1]
```diff
@@ -304,8 +304,11 @@ func (e *Endpoint) restoreIdentity(regenerator *Regenerator) error {
 				Group: initialGlobalIdentitiesControllerGroup,
 				DoFunc: func(ctx context.Context) (err error) {
 					err = e.allocator.WaitForInitialGlobalIdentities(ctx)
-					if err != nil {
+					switch {
+					case !errors.Is(err, context.Canceled):
```
Comment (joestringer) [inline pkg/endpoint/restore.go]: I was assuming that when this context is canceled, the endpoint's context is also canceled.. but given the CI results I'm second-guessing whether that's true.

Comment (christarazi) [reply pkg/endpoint/restore.go]: I think the key thing here is the call to `e.UpdateController`: https://github.com/cilium/cilium/blob/f28330123edacbcac9d8503a33564cc41e62cacc/pkg/endpoint/endpoint.go#L534. "This" context here is the controller context which is set to the endpoint's context.

Comment (joestringer) [reply pkg/endpoint/restore.go]: I wonder why some regenerations appear to be hanging "forever" in CI then :thinking:

Comment (christarazi) [reply pkg/endpoint/restore.go]: Ah, I think this is due to a simple mistake of not tightening the `err` check: https://github.com/cilium/cilium/compare/6d4893ca5acb05d2dc3dd5a727f361d9e8e35ac8..d0f8767b5b06a2aa493610de969105f626a5e5e2

That should do it. Without this, even non-nil errors were going through the `fallthrough` and ending up at a premature `return`.

**Comment by christarazi** [comment]
/test

Edit: https://github.com/cilium/cilium/issues/39370

**Review by fristonio — APPROVED** [review]
