### PR TITLE
Fix aws-cni chaining for IPv6 EKS clusters

### LINKED ISSUE #18495: aws-cni chaining fails on IPv6 clusters
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Cilium is not able to configure any pods in aws-cni chaining mode if it is deployed on an EKS IPv6 cluster. Without Cilium the pods deploy just fine. Cilium is deployed via the Helm chart with the following options:

```yaml
cni:
  chainingMode: aws-cni
ipv6:
  enabled: true
enableIPv4Masquerade: false
enableIPv6Masquerade: false
tunnel: disabled
nodeinit:
  enabled: true
```

After deploying, whenever a new pod is scheduled it will fail with the following error message:

```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "7860a4d68a5bdf02e3bf1fe64afba09972d1bbf9aa83da20057ec5bb01719ad0" network for pod "coredns-745979c988-6pnrv": networkPlugin cni failed to set up pod "coredns-745979c988-6pnrv_kube-system" network: no address configured inside container
```

I expected the pod to deploy fine with an IPv6 address.

### Cilium Version

v1.11.0

### Kernel Version

Linux ip-172-16-48-63.eu-central-1.compute.internal 5.4.162-86.275.amzn2.x86_64 #1 SMP Tue Nov 30 20:47:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.21.5-eks-bc4871b

### Sysdump

[cilium-sysdump-20220117-110639.zip](https://github.com/cilium/cilium/files/7880932/cilium-sysdump-20220117-110639.zip)

### Relevant log output

_No response_

### Anything else?

It looks like this happens because of [this line](https://github.com/cilium/cilium/blob/62adcc5c24887af808741739491fcecfc6995a42/plugins/cilium-cni/chaining/generic-veth/generic-veth.go#L94) in the aws-cni plugin. Since the cluster is on IPv6 it will have no IPv4 addresses, just IPv6. From my first skim of the code it might be enough to make the IPv4 address optional in that code block.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mKeRix**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [ ] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Thanks for contributing!

The newly introduced [IPv6 mode for EKS](https://aws.amazon.com/de/blogs/containers/amazon-eks-launches-ipv6-support/) will create clusters in which only IPv6 addresses will be assigned to pods and services. Up until now, Cilium in chaining mode with aws-cni enforced that at least 1 IPv4 address needed to be available. This is not valid anymore, so this change will replace the logic allowing it to work given that either an IPv4 or an IPv6 address is available.

In addition to that, the IPv6 setup of EKS introduces a new plugin to the aws-cni config, which will handle IPv4 traffic through a host-local NAT. To support this the conflist setup has been reworked to simply append to a copy of the existing aws-cni conflist. This way saves us additional complexity in the script - otherwise we would have to somehow determine whether the plugin should be enabled and we'd need to call the AWS metadata service to get the host IP. Either way we go, we will need to introduce a new package into the image (jq for the former, curl or wget for the latter). Would appreciate feedback on this.

**There is an important caveat.** With this implementation the policies will only work for IPv6. The new plugin in aws-cni creates a new interface named `v4if0` on each container ([reasoning](https://github.com/aws/amazon-vpc-cni-k8s/blob/192f8472bd9524f739ef2b9d65d91a7ce3b04d09/cmd/egress-v4-cni-plugin/cni.go#L87-L104)). This interface is not tracked by Cilium in any way, i.e. IPv4 traffic is unrestricted. If you have any idea of how we could get this veth interface under Cilium control as well please let me know.

_Note:_ Unfortunately my machine does not let me install the necessary tooling to run the tests - but I did test the change in an actual EKS cluster and confirmed them to be working. When applying a policy one has to keep in mind that the `fe80::/10` CIDR range needs to be allowed for egress and ingress as per #16285.

Fixes: #18495

```release-note
Add support for aws-cni chaining in IPv6 EKS clusters
```

### CODE REVIEW

**Comment by sayboras** [comment]
:wave: thanks for your PR, there is recent change on cni-install.sh script, can you rebase with master?

**Comment by mKeRix** [comment]
Branch is rebased on the current master. I also added a caveat to the original comment, which I found after testing out this change a bit more.

File: plugins/cilium-cni/cni-install.sh [hunk 1]
```diff
@@ -174,33 +174,9 @@ EOF
 	;;
 
 "aws-cni")
-	cat > "${CNI_CONF_NAME}" <<EOF
```
Comment (aanm) [inline plugins/cilium-cni/cni-install.sh:177]: Some concerns here. If the file `10-aws.conflist.cilium_bak` does not exist on the node the Cilium CNI config will not be created on the node. Previously it was always created by Cilium. Is it possible to have a backup plan in case `10-aws.conflist.cilium_bak` does not exist and we create the file regardless?

**Review by aanm — CHANGES_REQUESTED** [review]

File: plugins/cilium-cni/cni-install.sh (hunk 1 above)
Comment (mKeRix) [reply plugins/cilium-cni/cni-install.sh:177]: Good point. I'll check if I can get the old behavior back and still give people the opportunity to customize the necessary settings. Might also be interesting for people that want to disable the IPv4 NAT when running Cilium.

Comment (mKeRix) [reply plugins/cilium-cni/cni-install.sh:177]: Hey @aanm, sorry for taking so long to address your review comment. I got side-tracked by a few other things. I just submitted a change that restores the old behavior in case that the file does not exist. This seemed to be the most straightforward solution. It should work for both IPv4 and IPv6 clusters, on IPv6 clusters pods just won't have host-local IPv4 NAT available with the backup strategy.

**Review by aanm — APPROVED** [review]

File: images/runtime/Dockerfile [hunk 2]
```diff
@@ -35,7 +35,8 @@ ENV FORCE_BUILD=1
 
 # Update ubuntu packages to the most recent versions
 RUN apt-get update && \
-    apt-get upgrade -y
+    apt-get upgrade -y && \
```
Comment (aanm) [inline images/runtime/Dockerfile:38]: This changes requires a couple of more steps as they are explained [here](https://docs.cilium.io/en/v1.11/contributing/development/images/#update-cilium-builder-and-cilium-runtime-images). Please follow them so that we have all image digests up-to-date. Thanks!

**Review by aanm — CHANGES_REQUESTED** [review]

File: images/runtime/Dockerfile (hunk 2 above)
Comment (mKeRix) [reply images/runtime/Dockerfile:38]: Apologies for missing these steps. I did the first part of it - unfortunately I can't see the members of team build, so I don't know who to ping.

**Comment by mKeRix** [comment]
While testing the latest changes (adding the default file) I noticed that I forgot about a scenario that may lead to weird states, which is why I marked the PR as draft again. When adding nodes after Cilium was installed in chaining mode the cilium pod may be launched before the aws-node one, which means that the conflist file does not exist yet. Cilium then installs the backup file without IPv4 NAT.

Other chained CNIs tend to wait for a conflist to exist and then inject themselves there (e.g. istio-cni, linkerd2-cni). This is the behavior that was in this PR before the last commits.

I would now argue in favor of reverting the defaulting commits and only have the injection into the file again, possibly with a better error message when the file does not exist. Just adding the IPv4 NAT configuration to the default would not solve the problem of inconsistent states on the nodes, plus it would break backwards compatibility with older versions of aws-cni.

Additionally, the latest version of aws-cni uses 0.4.0 of the config, so using that with the 0.3.1 default config maintained in this repo might also cause some difficult to debug failure scenarios. Simply erroring out with the "config format not supported" error, which would happen when using file injection, would be easier to understand imo. This isn't directly related to this PR, but still worthwhile to consider.

What do you think @aanm?

I'll try to provide an updated PR again early next week.

**Comment by mKeRix** [comment]
I updated the script to exit if no conflist exists when in aws-cni chaining mode. This change should be resilient to the conflist having a different name, while avoiding the issues I iterated on above. Kubernetes will simply restart the container until the main CNI is available.

I tested the change on my own EKS IPv6 cluster again and can confirm it works for adding new nodes, even if aws-node runs after cilium-agent (or nodeinit).

File: images/runtime/Dockerfile (hunk 2 above)
Comment (pchaigno) [reply images/runtime/Dockerfile:38]: You can simply post a message in #development on Slack in such cases and someone will help :slightly_smiling_face:

File: plugins/cilium-cni/cni-install.sh [hunk 3]
```diff
@@ -174,10 +174,41 @@ EOF
...
+       "name": "cilium",
+       "type": "cilium-cni",
+       "enable-debug": ${ENABLE_DEBUG},
+       "log-file": "${LOG_FILE}"
+    }
+  ]
+}
+EOF
+	  ;;
+  fi
```
Comment (pchaigno) [inline plugins/cilium-cni/cni-install.sh:226]: I think commit `cni: Provide default for aws-cni chaining config` should be merged with the previous commit to avoid the number of touched code lines (a pain when git blaming).

Comment (pchaigno) [reply plugins/cilium-cni/cni-install.sh:226]: Same for commit `cni: Fix install script format`.

**Review by pchaigno — APPROVED** [review]
Thanks for the contribution! I only have two minor comments below.

Don't hesitate to ask for help on Slack if you need it to update the images.

**Comment by pchaigno** [comment]
Ah, I also think this should be considered a "new feature" instead of a fix. IPv6-only clusters in EKS are quite new, so I think it's fair to consider this pull request is simply adding support for a new EKS config. I've updated the release label accordingly, but could you reword the release note?

**Review by aanm — APPROVED** [review]

**Review by tklauser — APPROVED** [review]
LGTM once @pchaigno's review comments https://github.com/cilium/cilium/pull/18522#discussion_r815449764 and https://github.com/cilium/cilium/pull/18522#discussion_r815449921 are addressed.

File: plugins/cilium-cni/cni-install.sh [hunk 4]
```diff
@@ -174,7 +191,12 @@ EOF
 	;;
 
 "aws-cni")
-	cat > "${CNI_CONF_NAME}" <<EOF
+  if [ -f "${CNI_CONF_DIR}/10-aws.conflist.cilium_bak" ]; then
+    jq --argjson 'ENABLE_DEBUG' "$ENABLE_DEBUG" --arg 'LOG_FILE' "$LOG_FILE" \
```
Comment (sayboras) [inline plugins/cilium-cni/cni-install.sh:195]: TIL about argjon vs arg

File: plugins/cilium-cni/chaining/generic-veth/generic-veth.go [hunk 5]
```diff
@@ -87,16 +87,13 @@ func (f *GenericVethChainer) Add(ctx context.Context, pluginCtx chainingapi.Plug
 			}
 
 			addrs, err := netlink.AddrList(link, netlink.FAMILY_V4)
-			if err != nil {
-				return fmt.Errorf("unable to list addresses for link %s: %s", link.Attrs().Name, err)
-			}
-
-			if len(addrs) < 1 {
-				return fmt.Errorf("no address configured inside container")
```
Comment (sayboras) [inline plugins/cilium-cni/chaining/generic-veth/generic-veth.go:95]: while the current behaviour didn't take care of ipv6, it actually follow idea of throwing error if no address configured inside container i.e. fail fast if possible.

We can follow the same idea here i.e. if both addrs and addrsv6 are empty, just throw same error. The changes in this PR is fine as I know that you have a check for vethIP and vethIPv6 below.

**Review by sayboras — APPROVED** [review]
LGTM :rocket:

**Comment by mKeRix** [comment]
Just wanted to check in and ask if there is anything further I can do to help get this PR merged? :)

**Comment by pchaigno** [comment]
@mKeRix Given there are merge conflicts, could you rebase and I'll then trigger the end-to-end tests?

File: .github/workflows/build-images-ci.yaml [hunk 6]
```diff
@@ -147,7 +147,7 @@ jobs:
             quay.io/${{ github.repository_owner }}/${{ matrix.name }}-ci:latest-race
             quay.io/${{ github.repository_owner }}/${{ matrix.name }}-ci:${{ steps.tag.outputs.tag }}-race
           build-args: |
-            BASE_IMAGE=quay.io/cilium/cilium-runtime:eaa047d20a1736c81bcd4cab603f6c47c5508b21@sha256:ec480391acffe3c30a05b6c3b583f28caa9d20f25f33a650416454b29dabf642
+            BASE_IMAGE=quay.io/cilium/cilium-runtime:0da282e47af1907e17a1aa8dba3d41de6879ef62
```
Comment (pchaigno) [inline .github/workflows/build-images-ci.yaml]: That seems incorrect:
```
$ docker pull quay.io/cilium/cilium-runtime:0da282e47af1907e17a1aa8dba3d41de6879ef62
Error response from daemon: manifest for quay.io/cilium/cilium-runtime:0da282e47af1907e17a1aa8dba3d41de6879ef62 not found: manifest unknown: manifest unknown
```

Comment (mKeRix) [reply .github/workflows/build-images-ci.yaml]: I think I was too eager when updating the PR. I've removed the image digest updates and force-pushed just the changes, so that the image can be built by the pipeline. It looks like I have to run through the full digest update process again, as the images changed in the mean time. Apologies for the chaos!

Comment (mKeRix) [reply .github/workflows/build-images-ci.yaml]: Looks like everything is working again. :)

**Comment by mKeRix** [comment]
Unfortunately, it looks like some of the end-to-end tests failed. ☹️ I'm not sure what caused the failures though, the test failures that are logged either seem unrelated or don't give a lot of information. Could you help me look into this?

**Comment by mKeRix** [comment]
Failed again unfortunately - looks like an issue with kube-system?

**Comment by pchaigno** [comment]
/test-1.23-net-next

**Comment by pchaigno** [comment]
All tests are passing, reviews are in. Marking ready to merge.
