### PR TITLE
daemon: conditionally disable headless service watch

### LINKED ISSUE #40763: Scalability Regression: Agent Headless Service watch changes in 1.16+
Hi,
starting from 1.16 Cilium Agent started watching for Headless Services and Headless Service Endpoint Slices. The change was initially added in the context of Cluster Mesh: https://github.com/cilium/cilium/commit/99268e7ba1c73223b1d47bfeb17d44613ee0078a, https://github.com/cilium/cilium/pull/35838/commits/894b91a55efac2734060e7d1607e96e1ecfa0918.

This behavior is different to that of kube-proxy and has a significant impact on scalability. Watching for headless service endpoint slices of large services causes a huge load on Kubernetes Control Plane - headless services are no longer safe to run on large clusters.

I have 2 questions with regard to this:
1. Is watching of headless services and headless service endpoint slices in agent only needed for cluster mesh?
2. Would the OSS community be interested in this watch being configurable via a dedicated flag / cluster mesh related flag? If 1) is true and cluster mesh is not used we could disable this watch and return to previous scalability levels.

### PR DESCRIPTION
**Pull request by moscicky**
Previously, daemon watched headless services and headless services endpoint slices uncodnitially. This meant that even if features relying on headless services watch such as Gateway API and Ingress were not used the watch was created. This caused a increased load on apisever in clusters making use of headless services.

This patch disables the headless service watch when feature relying on it (Gateway API, Ingress) are not enabled.

Tests for the change were copied from the version prior to https://github.com/cilium/cilium/pull/28440.

Fixes: https://github.com/cilium/cilium/issues/40763

Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

```release-note
Disable unnecessary headless service watching to reduce API server load in clusters not using the Gateway API or Ingress features.
```

### CODE REVIEW

**Comment by moscicky** [comment]
This PR contains one of solutions discussed in: https://github.com/cilium/cilium/issues/40763, I am happy to discuss alternative approaches

**Comment by marseel** [comment]
cc @youngnick

File: pkg/k8s/resource_ctors.go [hunk 1]
```diff
@@ -91,12 +99,29 @@ type CiliumResourceParams struct {
 	CRDSyncPromise promise.Promise[synced.CRDSync] `optional:"true"`
 }
 
+type ConfigParams struct {
+	cell.In
+
+	Config      Config
+	WatchConfig *WatchConfig `optional:"true"`
```
Comment (joamaki) [inline pkg/k8s/resource_ctors.go]: I would prefer avoiding `optional:"true"` and forcing to explicitly provide it. It can then be just `WatchConfig` and not `*WatchConfig`.

Also consider naming it `ServiceWatchConfig` to avoid any confusion.

**Review by joamaki — CHANGES_REQUESTED** [review]

File: daemon/k8s/resources.go [hunk 2]
```diff
@@ -69,6 +72,12 @@ var (
 	)
 )
 
+func provideK8sWatchConfig(envoyCfg envoy.SecretSyncConfig) *k8s.WatchConfig {
```
Comment (joamaki) [inline daemon/k8s/resources.go]: Let's add a comment here to describe why headless services are watched if these are enabled. Maybe link to https://github.com/cilium/cilium/issues/40763 too?

File: daemon/k8s/resources.go [hunk 3]
```diff
@@ -8,6 +8,8 @@ import (
 	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
 	"k8s.io/apimachinery/pkg/fields"
 
+	envoy "github.com/cilium/cilium/pkg/envoy"
```
Comment (joamaki) [inline daemon/k8s/resources.go]: This might cause issues down the line with cyclic imports. I think it is fine for now and if we have issues we can move the `envoy.SecretSyncConfig` and others into e.g. `pkg/envoy/types` etc.

Comment (joamaki) [reply daemon/k8s/resources.go]: Ah, importing `pkg/envoy` here causes `cilium-cli` to import it transitively. This causes cilium-cli darwin build to fail:
```
Building release binary for darwin/amd64...
# github.com/cilium/cilium/pkg/bpf
Error: ../pkg/bpf/collection.go:305:30: undefined: Map
Error: ../pkg/bpf/events.go:53:2: undefined: cacheEntry
Error: ../pkg/bpf/events.go:89:10: undefined: Map
Error: ../pkg/bpf/events.go:223:10: undefined: Map
```

https://github.com/cilium/cilium/actions/runs/16753437980/job/47491810951?pr=40844

Looking at `go list -deps ./cilium-cli/cmd/...`. I think what pulls these in is `cilium-cli/bgp`:
```
github.com/cilium/cilium/pkg/envoy
github.com/cilium/cilium/pkg/clustermesh/store
github.com/cilium/cilium/pkg/k8s/types
github.com/cilium/cilium/pkg/k8s
github.com/cilium/cilium/daemon/k8s
github.com/cilium/cilium/pkg/bgpv1/agent/mode
github.com/cilium/cilium/pkg/bgpv1/agent/signaler
github.com/cilium/cilium/pkg/bgpv1/manager/store
github.com/osrg/gobgp/v3/pkg/packet/bgp
github.com/cilium/cilium/pkg/bgpv1/types
github.com/cilium/cilium/pkg/bgpv1/agent
github.com/cilium/cilium/pkg/bgpv1/api
github.com/cilium/cilium/cilium-cli/bgp
```

We can either see if we can slim down `cilium-cli` dependencies to avoid pulling this much agent code in (probably quite hard) or we can move the `envoy.*Config` types into `pkg/envoy/config`, or `pkg/envoy/cell` or `pkg/envoy/types` (not sure what's best here). Maybe @jrajahalme has an opinion?

Comment (moscicky) [reply daemon/k8s/resources.go]: thanks for noticing. Indeed it seems that dependency chain is:

```
cilium-cli -> pkg/bgpv1 -> daemon/k8s -> pkg/envoy -> pkg/bpf -> ...
```

which causes import failures on non Linux platforms

File: pkg/k8s/resource_ctors.go (hunk 1 above)
Comment (moscicky) [reply pkg/k8s/resource_ctors.go]: Made it explicit: https://github.com/cilium/cilium/pull/40844/commits/b824a6ca65e426628eb78f062475184293d11b60. Wondering if making gateway api and ingress config centralized in `option/config.go` wouldn't make things simpler? It should also help with dependency issues

File: daemon/k8s/resources.go (hunk 2 above)
Comment (moscicky) [reply daemon/k8s/resources.go]: You mean: what they are actually used for inside ingress and gateway?

File: pkg/k8s/utils/utils_test.go [hunk 4]
```diff
@@ -95,9 +99,58 @@ func TestEndpointsSlices(t *testing.T) {
 	}
 
 	// Should return only test-svc-1, since test-svc-2 is managed by the endpoint slice mesh controller
-	optMod, _ := GetEndpointSliceListOptionsModifier()
+	optMod, _ := GetEndpointSliceListOptionsModifier(enableHeadlessServiceWatch)
+	options := metav1.ListOptions{}
```
Comment (bowei) [inline pkg/k8s/utils/utils_test.go]: nit: `var options metav1.ListOptions`

File: pkg/k8s/utils/utils_test.go [hunk 5]
```diff
@@ -70,6 +72,8 @@ func TestServiceProxyName(t *testing.T) {
 }
 
 func TestEndpointsSlices(t *testing.T) {
+	const enableHeadlessServiceWatch = true
```
Comment (bowei) [inline pkg/k8s/utils/utils_test.go]: nit: move close the first usage instead of at the top of the func.

Is this variable meant for documentation? You could also do:

GetEndpointSliceList...(/*enableHeadlessServiceWatch*/ true)

to document the var.

File: pkg/k8s/resource_ctors.go (hunk 1 above)
Comment (joamaki) [reply pkg/k8s/resource_ctors.go]: We're working towards completely getting rid of `pkg/option/config.go` as having one central configuration struct (in a global variable no less!) makes testing quite hard and spreads feature-specific code all over the place, so that is definitely not an option. 

EDIT: I specifically meant extending `DaemonConfig`. One might make a case that we have configuration structs that are used in wide variaty of places and thus should perhaps belong in `pkg/option` type of place. I'm just worried that if we start doing `cell.Config` calls from `pkg/option` that we end up doing it also when it really doesn't make sense. In this case I personally would prefer doing e.g. `pkg/envoy/config` or some such over putting it into `pkg/option`.

File: daemon/k8s/resources.go (hunk 2 above)
Comment (joamaki) [reply daemon/k8s/resources.go]: No just enough to say that headless services are used by these features and we are not by default watching headless services for reasons specified in #40763. E.g. why someone who comes later shouldn't remove this and revert back to always watching headless services :)

**Review by smagnani96 — APPROVED** [review]
LGTM for encryption/wireguard!

File: daemon/k8s/resources.go (hunk 3 above)
Comment (bowei) [reply daemon/k8s/resources.go]: +1 on the config specific package comment.

File: pkg/k8s/resource_ctors.go [hunk 6]
```diff
@@ -43,11 +43,23 @@ type Config struct {
 	K8sServiceProxyName string
 }
 
+type ServiceWatchConfig struct {
+	// EnableHeadlessServiceWatch controls whether watches for Headless Services and
+	// Headless Services Endpoint Slices are enabled. Disabling the watch when
+	// features depending on it are not used reduces the load on apiserver in clusters
```
Comment (bowei) [inline pkg/k8s/resource_ctors.go]: Is there a case where you want to enable the watch but there are no features that use it? The comment seems to indicate that it may be used in this way, but it seems like it isn't very useful in this combination?

File: pkg/k8s/utils/utils.go [hunk 7]
```diff
@@ -68,14 +68,15 @@ func GetObjNamespaceName(obj NamespaceNameGetter) string {
...
+// tied to how Cilium internally works with clustermesh endpoints and that this function doesn't ignore
+// headless Services when enableHeadlessServiceWatch is true.
 // Given label mirroring from the service objects to endpoint slice objects were introduced in Kubernetes PR 94443,
 // and released as part of Kubernetes v1.20; we can start using GetServiceAndEndpointListOptionsModifier for
 // endpoint slices when dropping support for Kubernetes v1.19 and older. We can do that since the
 // serviceProxyNameLabel label will then be mirrored to endpoint slices for services with that label.
 // We also ignore Kubernetes endpoints coming from other clusters in the Cilium clustermesh here as
 // Cilium does not rely on mirrored Kubernetes EndpointSlice for any of its functionalities.
-func GetEndpointSliceListOptionsModifier() (func(options *v1meta.ListOptions), error) {
+func GetEndpointSliceListOptionsModifier(enableHeadlessServiceWatch bool) (func(options *v1meta.ListOptions), error) {
```
Comment (bowei) [inline pkg/k8s/utils/utils.go]: I think the argument name is quite specific, suggest:

enableHeadlessServiceWatch => excludeHeadlessServices

which is more meaningful in the context of the function.
People might be confused why the argument is related to the watch -- which it is in the context of where it is used but this makes it so people looking at the function will need to know that context to understand why.

File: pkg/k8s/utils/utils.go [hunk 8]
```diff
@@ -68,14 +68,15 @@ func GetObjNamespaceName(obj NamespaceNameGetter) string {
 // This methods returns a ListOptions modifier which adds a label selector to
 // select all endpointSlice objects they are not from remote clusters in Cilium cluster mesh.
 // This is mostly the same behavior as kube-proxy except the cluster mesh behavior which is
-// tied to how Cilium internally works with clustermesh endpoints and that this function also doesn't ignore headless Services.
+// tied to how Cilium internally works with clustermesh endpoints and that this function doesn't ignore
+// headless Services when enableHeadlessServiceWatch is true.
```
Comment (bowei) [inline pkg/k8s/utils/utils.go]: see comment below.

File: pkg/k8s/utils/utils.go [hunk 9]
```diff
@@ -92,12 +102,12 @@ func GetEndpointSliceListOptionsModifier() (func(options *v1meta.ListOptions), e
...
 // This methods returns a ListOptions modifier which adds a label selector to only
 // select services that are in context of Cilium.
-// Unlike kube-proxy Cilium does not select services/endpoints containing k8s headless service label.
+// Unlike kube-proxy Cilium also watches headless services and their endpoint slices when enableHeadlessServiceWatch is true.
 // We honor service.kubernetes.io/service-proxy-name label in the service object and only
 // handle services that match our service proxy name. If the service proxy name for Cilium
 // is an empty string, we assume that Cilium is the default service handler in which case
 // we select all services that don't have the above mentioned label.
-func GetServiceAndEndpointListOptionsModifier(k8sServiceProxy string) (func(options *v1meta.ListOptions), error) {
+func GetServiceAndEndpointListOptionsModifier(k8sServiceProxy string, enableHeadlessServiceWatch bool) (func(options *v1meta.ListOptions), error) {
```
Comment (bowei) [inline pkg/k8s/utils/utils.go]: see comment above

File: pkg/k8s/utils/utils_test.go [hunk 10]
```diff
@@ -45,7 +47,7 @@ func TestServiceProxyName(t *testing.T) {
 	}
 
 	// Should return only test-svc-1 which has the service-proxy-name=foo
-	optMod, _ := GetServiceAndEndpointListOptionsModifier("foo")
+	optMod, _ := GetServiceAndEndpointListOptionsModifier("foo", enableHeadlessServiceWatch)
```
Comment (bowei) [inline pkg/k8s/utils/utils_test.go]: We should have a unit test for true and false?

It also feels like this test may want to be refactored to be more table driven?

File: pkg/k8s/resource_ctors.go (hunk 1 above)
Comment (moscicky) [reply pkg/k8s/resource_ctors.go]: got it, thanks for clarifying!

File: daemon/k8s/resources.go (hunk 2 above)
Comment (moscicky) [reply daemon/k8s/resources.go]: sure, added the comment

File: pkg/k8s/utils/utils_test.go (hunk 10 above)
Comment (moscicky) [reply pkg/k8s/utils/utils_test.go]: refactored these to tests to be table driven and included the missing cases, please take a look

File: pkg/k8s/utils/utils.go (hunk 7 above)
Comment (moscicky) [reply pkg/k8s/utils/utils.go]: Agree that watch is misleading in this context, changed it to `includeHeadlessServices` - imo it fits better than `excludeHeadlessServices` with how this function is invoked

File: pkg/k8s/resource_ctors.go (hunk 6 above)
Comment (moscicky) [reply pkg/k8s/resource_ctors.go]: There is no benefit to enabling the watch when features relying on it are not used. I've removed this part and added it to the comment in `deamon/k8s/resources` to explain benefits there

File: daemon/k8s/resources.go (hunk 3 above)
Comment (moscicky) [reply daemon/k8s/resources.go]: moved config struct it to `pkg/envoy/config`, now `make -C cilium-cli local-release` passes for me locally

Comment (joamaki) [reply daemon/k8s/resources.go]: 👍

**Comment by bowei** [comment]
Thanks for the updates

**Review by rastislavs — APPROVED** [review]
LGTM for bgp

File: pkg/envoy/config/config.go [hunk 11]
```diff
@@ -0,0 +1,87 @@
+package config
```
Comment (joamaki) [inline pkg/envoy/config/config.go:4]: This is missing the copyright header

Comment (moscicky) [reply pkg/envoy/config/config.go:4]: fixed

**Comment by joamaki** [comment]
The commits are now pretty messy. Could you please squash them down to maybe 1 or 2? While at it, fix the `deamon` typo in the commit messages.

**Comment by moscicky** [comment]
@joamaki sure, squashed. Was planning to squash at the end for you to be able to easier track the changes during the review

**Review by joamaki — APPROVED** [review]

**Review by youngnick — APPROVED** [review]
LGTM from sig-servicemesh. I like moving both the Envoy config structs into their own package, nice.

**Comment by pchaigno** [comment]
Shouldn't this be considered a bug fix, marked as `release-note/bug`, and backported to v1.18?

**Comment by moscicky** [comment]
@pchaigno I would be happy to backport it to 1.18 or even 1.17 if possible. As for the `release-note/bug` I am not sure, currently the watch is sometimes unnecessary but I wouldn't call it a bug.

**Comment by pchaigno** [comment]
> @pchaigno I would be happy to backport it to 1.18 or even 1.17 if possible. As for the `release-note/bug` I am not sure, currently the watch is sometimes unnecessary but I wouldn't call it a bug.

If it's causing unnecessary load on kube-apiserver then I would say this is an unexpected user-visible impact, hence a bug. See also [our backport criteria](https://docs.cilium.io/en/stable/contributing/release/backports/).

**Comment by moscicky** [comment]
one integration test was failing after rebase, pushed fix for it

**Comment by pchaigno** [comment]
I've updated the labels. Could you update the release note to clarify the user impact?

**Comment by moscicky** [comment]
> I've updated the labels. Could you update the release note to clarify the user impact?

updated to:

```
Disable unnecessary headless service watching to reduce API server load in clusters not using the Gateway API or Ingress features.
```

**Review by marseel — APPROVED** [review]

**Comment by marseel** [comment]
cc @cilium/envoy for review, I think Jarno is OOO

**Comment by youngnick** [comment]
I added @sayboras, thanks for the callout @marseel.

**Review by sayboras — APPROVED** [review]
Thanks ✅
