### PR TITLE
datapath: masquerade IPv6 traffic when using iptables masquerading mode

### LINKED ISSUE #6320: Cilium needs ip6tables rules to route IPv6 packets
### General Information ###

Cilium version: 1.3.0
Kernel version: 4.19.5
Operating System: Centos 7.5
Orchestration system: Kubernetes 1.12.2

### Summary ###

On dual IPv4/IPv6 network stack hosts, Cilium does not properly route packets to pods that initiate connections to IPv6 addresses. Recursive DNS queries that attempt to resolve AAAA addresses to nameservers, for example, get lost when Cilium hands over the request to the host OS network stack.  Running cilium monitor in this instance results in:

```bash
<- endpoint 8330 flow 0x116bfb1d identity 52799->0 state new ifindex 0: [f00d::a2a:4100:0:208a]:37470 -> [2600:9000:5303:e800::1]:53 udp
-> stack flow 0x116bfb1d identity 52799->2 state new ifindex 0: [f00d::a2a:4100:0:208a]:37470 -> [2600:9000:5303:e800::1]:53 udp
```

No packets are returned and the request times-out on the pod, while the host running the pod can reach the IPv6 address via dig, curl, and ping.

IPv6 forwarding is enabled on the host.

```bash
$ sudo sysctl -a | grep net.ipv6.conf | grep forward

net.ipv6.conf.all.forwarding = 1
net.ipv6.conf.cilium_health.forwarding = 1
net.ipv6.conf.cilium_host.forwarding = 1
net.ipv6.conf.cilium_net.forwarding = 1
net.ipv6.conf.cilium_vxlan.forwarding = 1
net.ipv6.conf.default.forwarding = 1
net.ipv6.conf.docker0.forwarding = 1
```

But cilium does not yet install ip6table rules to route traffic to pods through IPv6 interfaces.

```bash
$ sudo ip6tables-save |grep cilium

$ sudo iptables-save |grep cilium
-A POSTROUTING -m comment --comment "cilium-feeder: CILIUM_POST" -j CILIUM_POST
-A CILIUM_POST ! -s 10.42.66.1/32 ! -d 10.42.66.0/24 -o cilium_host -m comment --comment "cilium host->cluster masquerade" -j SNAT --to-source 10.42.66.1
-A CILIUM_POST -s 10.42.66.0/24 -o cilium_host -m comment --comment "cilium hostport loopback masquerade" -j SNAT --to-source 10.42.66.1
-A CILIUM_POST -s 10.42.66.0/24 ! -d 10.42.66.0/24 ! -o cilium_+ -m comment --comment "cilium masquerade non-cluster" -j MASQUERADE
-A POSTROUTING -m comment --comment "cilium-feeder: CILIUM_POST_mangle" -j CILIUM_POST_mangle
-A CILIUM_POST_mangle -o cilium_host -m comment --comment "cilium: clear masq bit for pkts to cilium_host" -j MARK --set-xmark 0x0/0x4000
-A FORWARD -m comment --comment "cilium-feeder: CILIUM_FORWARD" -j CILIUM_FORWARD
-A OUTPUT -m comment --comment "cilium-feeder: CILIUM_OUTPUT" -j CILIUM_OUTPUT
-A CILIUM_FORWARD -o cilium_host -m comment --comment "cilium: any->cluster on cilium_host forward accept" -j ACCEPT
-A CILIUM_FORWARD -s 10.42.66.0/24 -m comment --comment "cilium: cluster->any forward accept" -j ACCEPT
-A CILIUM_OUTPUT -m mark ! --mark 0xa00/0xe00 -m comment --comment "cilium: host->any mark as from host" -j MARK --set-xmark 0xc00/0xf00

```

### How to reproduce the issue ###

1. Enable IPv4 and IPv6 network on host
2. Deploy cilium on Kubernetes
3. Start interactive shell on a pod and try to get a response from the commands:

```bash
dig AAAA google.com @2606:4700:4700::1111
```
 or 
```bash
curl -v http://[2607:f8b0:400a:804::200e]
```

### PR DESCRIPTION
**Pull request by fristonio**
See commit message for more detail.

This is with respect to an ongoing effort to improve support for DualStack K8s with Cilium and CI infrastructure.
Two new flags are introduced - `--enable-ipv6-masquerade` and `--enable-ipv4-masquerade` and the output of `cilium status` reflect the masquerading behavior enabled for the cluster.

```
$ cilium status
...
Host Routing:           Legacy
Masquerading:           IPTables [IPv4: Enabled, IPv6: Enabled]
...
```

Fixes https://github.com/cilium/cilium/issues/6320.

```release-note
Add the ability to masquerade IPv6 traffic when using iptables masquerading mode. This behavior can be enabled/disabled by using `enable-ipv6-masquerade` agent option.
```

### CODE REVIEW

**Review by aanm — APPROVED** [review]

**Comment by fristonio** [comment]
test-me-please

**Comment by fristonio** [comment]
retest-gke

File: api/v1/models/masquerading.go [hunk 1]
```diff
@@ -34,8 +34,12 @@ type Masquerading struct {
 	// Enum: [BPF iptables]
 	Mode string `json:"mode,omitempty"`
 
-	// Any packet sent to IP addr belonging to CIDR will not be SNAT'd
-	SnatExclusionCidr string `json:"snat-exclusion-cidr,omitempty"`
+	// Any packet sent to IPv4 addr belonging to CIDR will not be SNAT'd
+	SnatExclusionCidrV4 string `json:"snat-exclusion-cidr-v4,omitempty"`
```
Comment (christarazi) [inline api/v1/models/masquerading.go]: Nit: `SNATExclusionCIDRv4`

```
SNATExclusionCIDRv4 exempts SNAT from being performed on any packet sent to an IPv4 address that belongs inside this CIDR.
```

File: api/v1/models/masquerading.go [hunk 2]
```diff
@@ -34,8 +34,12 @@ type Masquerading struct {
...
+
+	// Any packet sent to IPv6 address belonging to this CIDR will not be SNAT'd.
+	// For IPv6 we only do masquerading in iptables mode.
+	SnatExclusionCidrV6 string `json:"snat-exclusion-cidr-v6,omitempty"`
```
Comment (christarazi) [inline api/v1/models/masquerading.go:44]: Nit: similar naming convention and rewording as above. It's fine to leave `For IPv6 we only do masquerading in iptables mode.` as well.

**Review by christarazi — APPROVED** [review]
LGTM. I did not review the iptables rules, but have a minor nits for doc readability of the new SNAT exclusion arg.

**Comment by brb** [comment]
Added `upgrade-impact`, as for existing dual stack deployments with `--enable-masquerade=true` IPv6 traffic from local endpoints to outside will get masqueraded which previously was not the case. I think we need to add an upgrade note.

File: pkg/datapath/config.go [hunk 3]
```diff
@@ -123,14 +123,21 @@ type ConfigWriter interface {
...
 	}
 
 	return node.GetIPv4AllocRange()
 }
+
+// RemoteSNATDstAddrExclusionCIDRv6 returns a IPv6 CIDR for SNAT exclusion. Any
+// packet sent from a local endpoint to an IP address belonging to the CIDR
+// should not be SNAT'd.
+func RemoteSNATDstAddrExclusionCIDRv6() *cidr.CIDR {
+	return node.GetIPv6AllocRange()
```
Comment (brb) [inline pkg/datapath/config.go:142]: Is this pod CIDR node-local or cluster-wide?

File: pkg/datapath/iptables/iptables.go [hunk 4]
```diff
@@ -828,6 +829,160 @@ func (m *IptablesManager) installForwardChainRules(ifName, localDeliveryInterfac
 	return nil
 }
 
+func (m *IptablesManager) installMasqueradeRules(prog, ifName, localDeliveryInterface,
```
Comment (brb) [inline pkg/datapath/iptables/iptables.go:928]: Just a note that it would have been easier to review if you created the method in a separate commit.

File: pkg/datapath/iptables/iptables.go [hunk 5]
```diff
@@ -828,6 +829,160 @@ func (m *IptablesManager) installForwardChainRules(ifName, localDeliveryInterfac
...
+	snatDstExclusionCIDR, allocRange, hostMasqueradeIP string) error {
+	if option.Config.Masquerade && !option.Config.EnableBPFMasquerade {
```
Comment (brb) [inline pkg/datapath/iptables/iptables.go]: While we are here, to reduce nestedness, you could `if option.Config.Masquerade && option.Config.EnableBPFMasquerade { return nil }`.

File: pkg/datapath/iptables/iptables.go [hunk 6]
```diff
@@ -929,147 +1084,39 @@ func (m *IptablesManager) InstallRules(ifName string) error {
...
-					"-A", ciliumPostNatChain,
-					"!", "-s", node.GetHostMasqueradeIPv4().String(),
-					"!", "-d", node.GetIPv4AllocRange().String(),
-					"-o", "cilium_host",
-					"-m", "comment", "--comment", "cilium host->cluster masquerade",
-					"-j", "SNAT", "--to-source", node.GetHostMasqueradeIPv4().String()), false); err != nil {
-					return err
-				}
-			}
+		if err := m.installMasqueradeRules("iptables", ifName, localDeliveryInterface,
```
Comment (brb) [inline pkg/datapath/iptables/iptables.go]: To make both cases symmetric, maybe we should wrap the invocation into `if option.Config.EnableIPv4 { ... }`?

File: pkg/datapath/iptables/iptables.go [hunk 7]
```diff
@@ -929,147 +1084,39 @@ func (m *IptablesManager) InstallRules(ifName string) error {
...
-				"-A", ciliumPostNatChain,
-				"-s", "127.0.0.1",
-				"-o", localDeliveryInterface,
-				"-m", "comment", "--comment", "cilium host->cluster from 127.0.0.1 masquerade",
-				"-j", "SNAT", "--to-source", node.GetHostMasqueradeIPv4().String()), false); err != nil {
-				return err
-			}
+	if option.Config.EnableIPv6 {
+		// See comment above.
+		matchFromProxy := fmt.Sprintf("%#08x/%#08x", linux_defaults.MagicMarkIsProxy, linux_defaults.MagicMarkProxyMask)
```
Comment (brb) [inline pkg/datapath/iptables/iptables.go]: Maybe we could create a function to install the MARK rule, and then call with with `"ip{,6}tables"` params?

**Review by brb — CHANGES_REQUESTED** [review]
Thanks, a few nits :-)

Alternative solution to solve the asymmetric routing issue would be to force `pod -> remote node` traffic to be sent over the tunnel (https://github.com/cilium/cilium/issues/12624). However, considering that #6320 is quite requested feature, adding IPv6 masq makes sense.

In addition to the upgrade guide, we should update https://docs.cilium.io/en/v1.9/concepts/networking/masquerading/ too.

Next, is it possible in our CI to have a test for IPv6 masquerading?

Finally, do you plan to work on BPF-based masq (and ip-masq-agent) for IPv6?

File: pkg/datapath/config.go (hunk 3 above)
Comment (fristonio) [reply pkg/datapath/config.go:142]: This is the node-local IPv6 allocation range, similar to IPv4 alloc range.

File: pkg/datapath/iptables/iptables.go (hunk 6 above)
Comment (fristonio) [reply pkg/datapath/iptables/iptables.go]: This already seems to be wrapped inside if `option.Config.EnableIPv4{ ... }`
https://github.com/cilium/cilium/pull/14124/files#diff-465a6b3f4ab9e1e94fe39e5aefe81c41eaa1dc99c66500161072e564029c2f51R1052

File: pkg/datapath/iptables/iptables.go (hunk 5 above)
Comment (fristonio) [reply pkg/datapath/iptables/iptables.go]: Makes sense, will do that.

File: pkg/datapath/iptables/iptables.go (hunk 4 above)
Comment (fristonio) [reply pkg/datapath/iptables/iptables.go:928]: Sorry if I misunderstood, but are you suggesting that in the first commit I add these rules wrapped inside an `if option.Config.EnableIPv6 { ... }` inside `InstallRules` and then in separate commit merge rules for IPv4 and IPv6 using a single function?

**Comment by fristonio** [comment]
> Next, is it possible in our CI to have a test for IPv6 masquerading?

I don't think we can test the exact behavior using the NodePort service as of now, but we can test masquerading behavior using the simple pod to pod communication. I will take a look and see if tests can be added for this. 

> Finally, do you plan to work on BPF-based masq (and ip-masq-agent) for IPv6?

Yeah, that is the plan as of now. BPF based masquerading for IPv6 will require some effort so I will take it up after we merge the entire DualStack support in our CI.

File: api/v1/models/masquerading.go (hunk 1 above)
Comment (fristonio) [reply api/v1/models/masquerading.go]: This is an autogenerated field using openapi spec. I don't think it's possible for us to change the name of the variable right? :confused:

Comment (ti-mo) [reply api/v1/models/masquerading.go]: Yes, this whole file should be autogenerated and should not be modified manually. :)

**Review by qmonnet — APPROVED** [review]

**Comment by fristonio** [comment]
test-me-please

File: pkg/datapath/iptables/iptables.go (hunk 4 above)
Comment (brb) [reply pkg/datapath/iptables/iptables.go:928]: I meant in the first commit to move the existing IPv4 code into this method, and then in the second commit to add the IPv6 handling.

Comment (fristonio) [reply pkg/datapath/iptables/iptables.go:928]: Makes sense, Done!

**Comment by fristonio** [comment]
test-me-please

**Comment by fristonio** [comment]
retest-gke

**Review by brb — APPROVED** [review]
Nice!

**Comment by brb** [comment]
> Added upgrade-impact, as for existing dual stack deployments with --enable-masquerade=true IPv6 traffic from local endpoints to outside will get masqueraded which previously was not the case. I think we need to add an upgrade note.

Thinking more about this. Maybe it makes sense to introduce a `--enable-masquerade-ipv6` flag to control this? /cc @aanm @joestringer

**Comment by aanm** [comment]
> > Added upgrade-impact, as for existing dual stack deployments with --enable-masquerade=true IPv6 traffic from local endpoints to outside will get masqueraded which previously was not the case. I think we need to add an upgrade note.
> 
> Thinking more about this. Maybe it makes sense to introduce a `--enable-masquerade-ipv6` flag to control this? /cc @aanm @joestringer

Discussed offline, yes it makes sense.

**Comment by fristonio** [comment]
test-me-please

**Comment by fristonio** [comment]
retest-runtime

**Comment by fristonio** [comment]
test-me-please

**Review by gandro — APPROVED** [review]
Changes to health LGTM!

**Comment by fristonio** [comment]
retest-4.9

**Review by borkmann — APPROVED** [review]
LGTM, great work! Maybe upgrade guide optionally needs a deprecation notice and present the two new `enable-ipv{4,6}-masquerade` flags in the doc? We should also follow-up with an issue for implementing BPF-based masq for v6 as otherwise we won't be able to use the fast redirect datapath if users have v4+v6 enabled. Not blocking this one, of course, but something to resolve for 1.10 still.

**Comment by fristonio** [comment]
I have created a follow-up issue for BPF based masquerading and add upgrade notes for the changes in the Pull Request.

**Comment by fristonio** [comment]
test-me-please

File: Documentation/operations/upgrade.rst [hunk 8]
```diff
@@ -337,12 +337,6 @@ Annotations:
 
 * Cilium has bumped the minimal Kubernetes version supported to v1.13.0.
 
-Deprecated options
-~~~~~~~~~~~~~~~~~~
-
-* ``k8s-force-json-patch``: This option does not have any effect for
-  environments running Kubernetes >= 1.13. Marked for removal in Cilium v1.11.
-
```
Comment (joestringer) [inline Documentation/operations/upgrade.rst:345]: Why is this being removed? It looks like this is intended to be marked deprecated in 1.10 and removed in 1.11.

File: Documentation/operations/upgrade.rst [hunk 9]
```diff
@@ -378,6 +381,12 @@ Deprecated Options
 
 * ``bpf-compile-debug``: This option does not have any effect since 1.10
   and is planned to be removed in 1.11.
+* ``k8s-force-json-patch``: This option does not have any effect for
+  environments running Kubernetes >= 1.13. Marked for removal in Cilium v1.11.
+* ``masquerade``: With the introduction of IPv6 masquerading this option has
+  been deprecated in favor of ``enable-ipv4-masquerade`` and is planned to
+  be removed in 1.11. For 1.10 release this option will have the same effect as
+  ``enable-ipv4-masquerade`` where both options must not be used simultaneously.
```
Comment (joestringer) [inline Documentation/operations/upgrade.rst:389]: Ah, I see. I guess the question is whether we should have a separate "deprecated" vs. "removed" section. I don't know if we've had a discussion somewhere about this but it seems reasonable to me. :+1:

**Review by joestringer — CHANGES_REQUESTED** [review]
This setting changes the commandline arguments, but does not update the Helm charts (`install/kubernetes/*`). Do you intend that the helm charts would also convert to the new split ipv4/ipv6 configuration, or that we retain the helm option for general `masquerade` and auto-enable both options?

Strictly speaking I think that it will work to not change `install/kubernetes` at this time, but we will need to revisit this before we properly remove the option and it'll be easy to forget if we don't do it now.

File: cilium-health/launch/endpoint.go [hunk 10]
```diff
@@ -338,15 +341,14 @@ func LaunchAsEndpoint(baseCtx context.Context,
...
+	// Set up the endpoint routes.
 	if err = configureHealthRouting(info.ContainerName, epIfaceName, node.GetNodeAddressing(), mtuConfig); err != nil {
 		return nil, fmt.Errorf("Error while configuring routes: %s", err)
 	}
 
 	if option.Config.IPAM == ipamOption.IPAMENI {
 		if err := routingConfig.Configure(healthIP,
-			mtuConfig.GetDeviceMTU(),
-			option.Config.Masquerade); err != nil {
+			mtuConfig.GetDeviceMTU(), masq); err != nil {
```
Comment (joestringer) [inline cilium-health/launch/endpoint.go]: I don't see any IPv6 support in `routingConfig.Configure(...)` so maybe not worth making any changes here for now?

File: pkg/datapath/maps/map.go [hunk 11]
```diff
@@ -86,7 +86,8 @@ func (ms *MapSweeper) deleteMapIfStale(path string, filename string, endpointID
 
 func (ms *MapSweeper) checkStaleGlobalMap(path string, filename string) {
 	globalCTinUse := ms.HasGlobalCT() || option.Config.EnableNodePort ||
-		!option.Config.InstallIptRules && option.Config.Masquerade
+		!option.Config.InstallIptRules && option.Config.EnableIPv4Masquerade &&
+			option.Config.EnableIPv6Masquerade
```
Comment (joestringer) [inline pkg/datapath/maps/map.go]: Should this be...?

```suggestion
		!option.Config.InstallIptRules && (option.Config.EnableIPv4Masquerade ||
			option.Config.EnableIPv6Masquerade)
```

**Review by joestringer — CHANGES_REQUESTED** [review]
Couple of other nits from my codeowners (looked at all but the core iptables functionality which it looked like was already well-covered in other reviews)

File: cilium-health/launch/endpoint.go (hunk 10 above)
Comment (christarazi) [reply cilium-health/launch/endpoint.go]: Correct, ENI mode does not support IPv6.

File: pkg/datapath/maps/map.go (hunk 11 above)
Comment (fristonio) [reply pkg/datapath/maps/map.go]: Yeah, you are correct. Thanks for pointing this out.

File: Documentation/operations/upgrade.rst (hunk 9 above)
Comment (fristonio) [reply Documentation/operations/upgrade.rst:389]: Yeah, there was one item each under both sections even though they had the same behaviour(deprecated in upcoming and removed in future releases). So I removed `Deprecated Option` section.

File: Documentation/operations/upgrade.rst (hunk 8 above)
Comment (fristonio) [reply Documentation/operations/upgrade.rst:345]: I think this has been answered in the below comment.

**Comment by fristonio** [comment]
Thanks, @joestringer for pointing out the changes required in the helm chart. I think it makes sense to keep the helm chart updated with the new options introduced in the PR. I have added a commit to add the required helm option in the chart.

Also, I just realized that our helm README generation has a minor issue where the description for values in the readme is not properly populated when we have some commented out fields in the `values.yaml` file. I have created issue #14369

**Comment by fristonio** [comment]
test-me-please

**Review by joestringer — COMMENTED** [review]
Maybe also worthwhile to do a `git grep masquerade Documentation/` to check for any remaining references to the old options. At a glance I see a few in the chaining modes, we could either expand those configurations for both of the new options or consider having the existing option act as a single "override".

**Comment by fristonio** [comment]
test-me-please

**Comment by fristonio** [comment]
retest-net-next

**Comment by fristonio** [comment]
retest-runtime

**Comment by fristonio** [comment]
retest-runtime

**Review by joestringer — APPROVED** [review]
