### PR TITLE
proxy/accesslog: use new context to retrieve local node

### LINKED ISSUE #44077: CI: ci-gke: "Failed to process DNS response" during connectivity check, with error="failed create log record: failed to get local node: context deadline exceeded"
## CI failure

Observed on `main` branch:

https://github.com/cilium/cilium/actions/runs/21520614200/job/62010598819#step:24:642

📋 Test Report [cilium-test-1]
❌ 1/8 tests failed (1/43 actions), 2 tests skipped, 0 scenarios skipped:
Test [check-log-errors]:
  🟥 check-log-errors/no-errors-in-logs:pkg/fqdn/dnsproxy:gke_***_us-east1-c_cilium-cilium-21520614200-1-1/kube-system/cilium-kn5hs (cilium-agent): Found 2 logs in gke_***_us-east1-c_cilium-cilium-21520614200-1-1/kube-system/cilium-kn5hs (cilium-agent) matching list of errors that must be investigated:
time=2026-01-30T15:28:30.308483026Z level=error source=/go/src/github.com/cilium/cilium/pkg/fqdn/dnsproxy/proxy.go:1128 msg="Failed to process DNS response" module=agent.controlplane.fqdn.dns-proxy dnsName=google.com. ipAddr=10.51.161.114:39611 DNSRequestID=7590 endpointID=618 identity=16512 error="failed create log record: failed to get local node: context deadline exceeded" resp=";; opcode: QUERY, status: NOERROR, id: 7590\n;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1\n\n;; OPT PSEUDOSECTION:\n; EDNS: version 0; flags: ; udp: 1232\n\n;; QUESTION SECTION:\n;google.com.\tIN\t A\n\n;; ANSWER SECTION:\ngoogle.com.\t10\tIN\tA\t172.217.203.113\ngoogle.com.\t10\tIN\tA\t172.217.203.102\ngoogle.com.\t10\tIN\tA\t172.217.203.138\ngoogle.com.\t10\tIN\tA\t172.217.203.139\ngoogle.com.\t10\tIN\tA\t172.217.203.101\ngoogle.com.\t10\tIN\tA\t172.217.203.100\n" (1 occurrences)
[cilium-test-1] 1 tests failed
time=2026-01-30T15:27:08.886677569Z level=error source=/go/src/github.com/cilium/cilium/pkg/fqdn/dnsproxy/proxy.go:1045 msg="Failed to process DNS query" module=agent.controlplane.fqdn.dns-proxy dnsName=google.com. ipAddr=10.51.161.135:33300 DNSRequestID=957 endpointID=346 identity=4795 error="failed create log record: failed to get local node: context deadline exceeded" (1 occurrences)
    ⛑️ The following owners are responsible for reliability of the testsuite: 
        - @cilium/fqdn (no-errors-in-logs:pkg/fqdn/dnsproxy)
        - @cilium/gke (.github/workflows/conformance-gke.yaml)
        - @cilium/ipsec (.github/workflows/conformance-gke.yaml)
        - @cilium/ci-structure (.github/workflows/conformance-gke.yaml)

### PR DESCRIPTION
**Pull request by mhofstetter**
The refactorings of #43600 (using the log context to retrieve the local node from the store) can lead to errors.

```
Failed to process DNS response" during connectivity check, with error="failed create log record: failed to get local node: context deadline exceeded
```

Before #43600, the local node store was retrieved via global function that is using a new context without expiration (`context.TODO()`) (https://github.com/cilium/cilium/blob/main/pkg/node/address.go#L34-L46).

Reusing the [logcontext with its 10ms](https://github.com/cilium/cilium/blob/main/pkg/fqdn/messagehandler/message_handler.go#L233-L234) seems to be too optimistic. Therefore, this commit reverts parts of the refactoring and uses a new `context.Background` without expiration for retrieving the node again. Even though it would be better 
to eventually have a context that spans the full request that could be used for this.

Fixes: #43600
Fixes: #44077

### CODE REVIEW

File: pkg/fqdn/messagehandler/message_handler.go [hunk 1]
```diff
@@ -232,7 +232,7 @@ func (h *dnsMessageHandler) NotifyOnDNSMsg(
 	// requests because an identity isn't in the local cache yet.
 	logContext, lcncl := context.WithTimeout(context.Background(), 10*time.Millisecond)
 	defer lcncl()
-	record, err := h.proxyAccessLogger.NewLogRecord(logContext, flowType, false,
+	record, err := h.proxyAccessLogger.NewLogRecord(context.Background(), flowType, false,
```
Comment (joestringer) [inline pkg/fqdn/messagehandler/message_handler.go:235]: I'm idly wondering whether StateDB gathers sufficient metrics for us to pick out when p99 for this operation gets too high (cc @cilium/sig-foundations @joamaki). In the failing test, it appears that a one-off request to fetch the node resource took >10ms in the middle of the test run. So not correlated with startup or shutdown of the agent. Timeline:

- [Cilium ready Fri, 30 Jan 2026 15:23:32 GMT](https://github.com/cilium/cilium/actions/runs/21520614200/job/62010598819#step:22:50)
- [Tests start Fri, 30 Jan 2026 15:24:27 GMT](https://github.com/cilium/cilium/actions/runs/21520614200/job/62010598819#step:24:274)
- [Log emitted 2026-01-30T15:28:30.308483026Z](https://github.com/cilium/cilium/actions/runs/21520614200/job/62010598819#step:24:645)
- [Tests complete Fri, 30 Jan 2026 15:32:25 GMT](https://github.com/cilium/cilium/actions/runs/21520614200/job/62010598819#step:24:506)

**Review by joestringer — APPROVED** [review]
This is restoring the old behavior and should resolve the failing test, thanks :+1:

**Review by bimmlerd — APPROVED** [review]
Change LGTM. 

The root cause hasn't clicked for me yet - I was working under the assumption that, after agent startup, `Get` would essentially be infallible.

**Comment by mhofstetter** [comment]
> The root cause hasn't clicked for me yet - I was working under the assumption that, after agent startup, `Get` would essentially be infallible.

Yes that's correct - this is ensured due to the hive dependencies and their lifecycle start hooks.

The problem is the reuse of the "logContext" with a 10ms timeout which can lead to situations where this 10ms are just too optimistic and result in an error due to context timeout. (see referenced issue). These 10ms might also be too optimistic for the actual use-case for which it has been introduced (not blocking the dns request for too long while fetching endpoint related data).

see https://github.com/cilium/cilium/blob/main/pkg/fqdn/messagehandler/message_handler.go#L233-L234

As i mentioned, it would be better to use a proper context that spans the complete DNS request - incl. request timeout. But currently we don't have this.  That's why we temporarily have to fall back to use a `context.Background()` again :disappointed:

File: pkg/fqdn/messagehandler/message_handler.go (hunk 1 above)
Comment (mhofstetter) [reply pkg/fqdn/messagehandler/message_handler.go:235]: resolve -> merge -> re-open for potential follow up discussion :innocent:

**Comment by joestringer** [comment]
I floated the root cause past @joamaki as well, and it wasn't immediately apparent why this operation would take 10ms or longer. Should be a bit of pointer chasing with some atomics, so several orders of magnitude faster.

The only theory that made some sense out of the discussion was if this is running in a VM in a cloud environment, the scheduling of the programs could be arbitrarily delayed, meaning code that would otherwise take nanoseconds or microseconds to run is bumped off CPU for a while and execution continues significantly later.
