### PR TITLE
nat: Create SNAT maps only if BPF NodePort is enabled

### LINKED ISSUE #15141: Removing disabled maps causes controllers to fail
Removing disabled maps in 
https://github.com/cilium/cilium/blob/cac5218858da8cdcb2029269f3b2238f88eb33cd/pkg/datapath/maps/map.go#L210-L215

Causes the controllers to fail:
```
2021-02-26T14:24:45.460845518Z level=debug msg="Controller func execution time: 15.392µs" name=bpf-map-sync-cilium_snat_v4_external subsys=controller uuid=946f5dda-bd86-44d5-aa8d-7d5ee12daaed
2021-02-26T14:24:45.460882480Z level=debug msg="Controller run failed" consecutiveErrors=1 error="Unable to get object /sys/fs/bpf/tc/globals/cilium_snat_v4_external: no such file or directory" name=bpf-map-sync-cilium_snat_v4_external subsys=controller uuid=946f5dda-bd86-44d5-aa8d-7d5ee12daaed
```
as seen in our CI https://jenkins.cilium.io/job/Cilium-PR-K8s-1.20-kernel-4.9/799/testReport/junit/Suite-k8s-1/20/K8sServicesTest_Checks_service_across_nodes_Checks_ClusterIP_Connectivity/

This change seems to have been introduced by https://github.com/cilium/cilium/commit/cac5218858da8cdcb2029269f3b2238f88eb33cd

cc @brb @pchaigno @mazzy89

### PR DESCRIPTION
**Pull request by pchaigno**
The IPv4 and IPv6 SNAT maps are only used if BPF NodePort is enabled. https://github.com/cilium/cilium/pull/14721 removed the maps on startup if BPF NodePort is disabled.

We were however still creating them regardless of the BPF NodePort status. The creation started a controller which then fails once the actual map is removed. This commit fixes the issue by not creating the userspace object, including the controller, for the SNAT maps when BPF NodePort is disabled.

See commits for details.

Fixes: https://github.com/cilium/cilium/pull/14721
Fixes: https://github.com/cilium/cilium/issues/15141

```release-note
Fix failing `bpf-map-sync-cilium_snat_v{4,6}_external` controllers when BPF NodePort is disabled
```

### CODE REVIEW

**Comment by pchaigno** [comment]
test-me-please

**Comment by pchaigno** [comment]
test-me-please

**Review by tklauser — APPROVED** [review]
Thanks!

File: pkg/maps/ctmap/ctmap.go [hunk 1]
```diff
@@ -202,10 +202,6 @@ func InitMapInfo(tcpMaxEntries, anyMaxEntries int, v4, v6 bool) {
 		anyMaxEntries, natMaps[mapTypeIPv6AnyGlobal])
 }
 
-func init() {
-	InitMapInfo(option.CTMapEntriesGlobalTCPDefault, option.CTMapEntriesGlobalAnyDefault, true, true)
-}
-
```
Comment (aanm) [inline pkg/maps/ctmap/ctmap.go]: Why is this being removed?

File: pkg/maps/nat/nat.go [hunk 2]
```diff
@@ -299,6 +299,9 @@ func (m *Map) DeleteMapping(key tuple.TupleKey) error {
 
 // GlobalMaps returns all global NAT maps.
 func GlobalMaps(ipv4, ipv6 bool) (ipv4Map, ipv6Map *Map) {
+	if !option.Config.EnableNodePort {
+		return
+	}
```
Comment (aanm) [inline pkg/maps/nat/nat.go]: If we have this logic here, why can't we also have the logic in [1]

File: daemon/cmd/datapath.go [hunk 3]
```diff
@@ -401,12 +401,12 @@ func (d *Daemon) initMaps() error {
...
 	ipv4Nat, ipv6Nat := nat.GlobalMaps(option.Config.EnableIPv4,
 		option.Config.EnableIPv6)
-	if option.Config.EnableIPv4 {
+	if ipv4Nat != nil {
 		if _, err := ipv4Nat.Create(); err != nil {
 			return err
 		}
 	}
-	if option.Config.EnableIPv6 {
+	if ipv6Nat != nil {
```
Comment (aanm) [inline daemon/cmd/datapath.go:409]: [1]

File: pkg/maps/ctmap/ctmap.go (hunk 1 above)
Comment (pchaigno) [reply pkg/maps/ctmap/ctmap.go]: Because it ends up creating map objects with the wrong info. At `init` point, options such as `EnableNodePort` may not have their final information. We have a call early on startup to replace this.

File: daemon/cmd/datapath.go (hunk 3 above)
Comment (pchaigno) [reply daemon/cmd/datapath.go:409]: Why? `nat.GlobalMaps` checks the preconditions to create the maps. No need to duplicate all of them in the caller.

File: pkg/maps/ctmap/ctmap.go (hunk 1 above)
Comment (aanm) [reply pkg/maps/ctmap/ctmap.go]: I guess the tests that failed have given a reason why the `init()` should not be removed :wink:

File: daemon/cmd/datapath.go (hunk 3 above)
Comment (aanm) [reply daemon/cmd/datapath.go:409]: Simply to avoid removing the interface.

Comment (pchaigno) [reply daemon/cmd/datapath.go:409]: Is that something we want? My impression was that removing the interface makes sense even without this PR.

**Comment by pchaigno** [comment]
test-me-please

File: daemon/cmd/datapath.go (hunk 3 above)
Comment (joestringer) [reply daemon/cmd/datapath.go:409]: Going back to the original commit that introduced the interface, 319ccde9f19deaa435dd6d29a84ee13cfcea90fa, I don't see any explanation of what it was trying to do with the interface. In general, interfaces help to abstract but looking at the code in this PR, all of the touched packages are already directly depending on bpf so I don't see much difference there.

At some point I'd love for us to come up with a general bpf mock map abstraction, but I don't think this specific `NatMap` interface is achieving that today so unless there's some clear argument why it needs to be here, I'm OK to remove it.

**Review by joestringer — APPROVED** [review]
This seems fairly straightforward to me, just need to check & resolve the one outstanding thread

**Comment by pchaigno** [comment]
test-only --k8s_version=1.13 --kernel_version=net-next K8sServicesTest Checks service across nodes Tests NodePort BPF Tests with direct routing and DSR

File: daemon/cmd/datapath.go (hunk 3 above)
Comment (jibi) [reply daemon/cmd/datapath.go:409]: > Going back to the original commit that introduced the interface, 319ccde, I don't see any explanation of what it was trying to do with the interface. In general, interfaces help to abstract but looking at the code in this PR, all of the touched packages are already directly depending on bpf so I don't see much difference there.

It might have got copied over from the `nat` package: https://github.com/cilium/cilium/blob/e2d9cbb93f326c7017b0177ed7c5fbb1557f6970/pkg/maps/nat/nat.go#L71-L79

My understanding is that these interfaces are the used in `cilium/cmd/*`:

https://github.com/cilium/cilium/blob/e2d9cbb93f326c7017b0177ed7c5fbb1557f6970/cilium/cmd/bpf_nat_list.go#L49-L59

 so that we can replace the actual maps with the mocks in the tests:
 
 https://github.com/cilium/cilium/blob/e2d9cbb93f326c7017b0177ed7c5fbb1557f6970/cilium/cmd/bpf_nat_list_test.go#L87-L99

That said it looks like the `bpf ct` commands are using the `CtMap` interface:

https://github.com/cilium/cilium/blob/e2d9cbb93f326c7017b0177ed7c5fbb1557f6970/cilium/cmd/bpf_ct_list.go#L133-L141

So I also think it should be fine to get rid of this in the `ctmap` package

**Review by jibi — APPROVED** [review]

**Review by christarazi — APPROVED** [review]
LGTM. Since this PR moves around daemon initialization order, we'll need to be careful when backporting this.

**Comment by pchaigno** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
