### PR TITLE
Fix race while updating L7 proxy redirect in L4PolicyMap

### LINKED ISSUE #2409: agent: data race in endpoint.(*Endpoint).writeL4Map()
```
Dec 27 09:34:15 anam cilium-agent[23721]: ==================
Dec 27 09:34:15 anam cilium-agent[23721]: WARNING: DATA RACE
Dec 27 09:34:15 anam cilium-agent[23721]: Read at 0x00c420ed3650 by goroutine 42:
Dec 27 09:34:15 anam cilium-agent[23721]:   runtime.mapiterinit()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/go/src/runtime/hashmap.go:709 +0x0
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).writeL4Map()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:55 +0xab
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).writeL4Policy()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:113 +0x2b5
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).writeHeaderfile()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:256 +0x1fa8
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:433 +0x218
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/policy.go:693 +0x4ca
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate.func1()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/policy.go:759 +0x2a1
Dec 27 09:34:15 anam cilium-agent[23721]: Previous write at 0x00c420ed3650 by goroutine 109:
Dec 27 09:34:15 anam cilium-agent[23721]:   runtime.mapassign_faststr()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/go/src/runtime/hashmap_fast.go:598 +0x0
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).writeL4Map()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:71 +0x5e5
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).writeL4Policy()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:113 +0x2b5
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).writeHeaderfile()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:256 +0x1fa8
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:433 +0x218
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/policy.go:693 +0x4ca
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate.func1()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/policy.go:759 +0x2a1
Dec 27 09:34:15 anam cilium-agent[23721]: Goroutine 42 (running) created at:
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/policy.go:742 +0x1e6
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpointmanager.TriggerPolicyUpdates.func1()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:270 +0x289
Dec 27 09:34:15 anam cilium-agent[23721]: Goroutine 109 (running) created at:
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/policy.go:742 +0x1e6
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpointmanager.TriggerPolicyUpdates.func1()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:270 +0x289
Dec 27 09:34:15 anam cilium-agent[23721]: ==================
Dec 27 09:34:15 anam cilium-agent[23721]: WARNING: DATA RACE
Dec 27 09:34:15 anam cilium-agent[23721]: Read at 0x00c4202ee488 by goroutine 42:
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).writeL4Map()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:55 +0x124
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).writeL4Policy()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:113 +0x2b5
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).writeHeaderfile()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:256 +0x1fa8
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:433 +0x218
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/policy.go:693 +0x4ca
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate.func1()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/policy.go:759 +0x2a1
Dec 27 09:34:15 anam cilium-agent[23721]: Previous write at 0x00c4202ee488 by goroutine 109:
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).writeL4Map()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:71 +0x607
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).writeL4Policy()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:113 +0x2b5
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).writeHeaderfile()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:256 +0x1fa8
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:433 +0x218
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/policy.go:693 +0x4ca
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate.func1()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/policy.go:759 +0x2a1
Dec 27 09:34:15 anam cilium-agent[23721]: Goroutine 42 (running) created at:
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/policy.go:742 +0x1e6
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpointmanager.TriggerPolicyUpdates.func1()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:270 +0x289
Dec 27 09:34:15 anam cilium-agent[23721]: Goroutine 109 (running) created at:
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/policy.go:742 +0x1e6
Dec 27 09:34:15 anam cilium-agent[23721]:   github.com/cilium/cilium/pkg/endpointmanager.TriggerPolicyUpdates.func1()
Dec 27 09:34:15 anam cilium-agent[23721]:       /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpointmanager/manager.go:270 +0x289
Dec 27 09:34:15 anam cilium-agent[23721]: ==================
```

```
$ git ll
b7090303c272 (Ginkgo: redirects vagrant provision output to GinkgoWriter, 2017-12-26)
$ git diff
diff --git a/Makefile.defs b/Makefile.defs
index eb50e28d49b9..3ba7307c122f 100644
--- a/Makefile.defs
+++ b/Makefile.defs
@@ -11,10 +11,10 @@ BUILD = $(VERSION) $(shell git show -s --format='format:%h %aD') $(shell go vers
 GOBUILD = -ldflags '-X "github.com/cilium/cilium/pkg/version.Version=$(BUILD)"'
 
 # Uncomment to enable race detection
-#GOBUILD += -race
+GOBUILD += -race
 
 # Uncomment to enable deadlock detection
-#GOBUILD += -tags lockdebug
+GOBUILD += -tags lockdebug
 
 ifneq ($(LOCKDEBUG),)
     GOBUILD += -tags lockdebug
[...]
```

### PR DESCRIPTION
**Pull request by joestringer**
Previously, the L7 redirects were allocated deep in the L4 BPF code
generation; this commit shifts that functionality up to the
regenerateBPF() layer, and wraps some proper locking around its access
to Consumable, as it modifies the Consumable's L4PolicyMap.

This should fix the following data race:

```
WARNING: DATA RACE
Read at 0x00c420ed3650 by goroutine 42:
  runtime.mapiterinit()
      /home/scanf/opt/go/src/runtime/hashmap.go:709 +0x0
  github.com/cilium/cilium/pkg/endpoint.(*Endpoint).writeL4Map()
      /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:55 +0xab
  github.com/cilium/cilium/pkg/endpoint.(*Endpoint).writeL4Policy()
      /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:113 +0x2b5
  github.com/cilium/cilium/pkg/endpoint.(*Endpoint).writeHeaderfile()
      /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:256 +0x1fa8
  github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF()
      /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:433 +0x218
  github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate()
      /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/policy.go:693 +0x4ca
  github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate.func1()
      /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/policy.go:759 +0x2a1

Previous write at 0x00c420ed3650 by goroutine 109:
  runtime.mapassign_faststr()
      /home/scanf/opt/go/src/runtime/hashmap_fast.go:598 +0x0
  github.com/cilium/cilium/pkg/endpoint.(*Endpoint).writeL4Map()
      /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:71 +0x5e5
  github.com/cilium/cilium/pkg/endpoint.(*Endpoint).writeL4Policy()
      /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:113 +0x2b5
  github.com/cilium/cilium/pkg/endpoint.(*Endpoint).writeHeaderfile()
      /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:256 +0x1fa8
  github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF()
      /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:433 +0x218
  github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate()
      /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/policy.go:693 +0x4ca
  github.com/cilium/cilium/pkg/endpoint.(*Endpoint).Regenerate.func1()
      /home/scanf/opt/og/src/github.com/cilium/cilium/pkg/endpoint/policy.go:759 +0x2a1
```

Fixes: #2409

Reported-by: Alexander Alemayhu <alexander@alemayhu.com>
Signed-off-by: Joe Stringer <joe@covalent.io>

### CODE REVIEW

**Comment by joestringer** [comment]
test-me-please

**Comment by joestringer** [comment]
test-me-please

File: pkg/endpoint/bpf.go [hunk 1]
```diff
@@ -62,15 +62,6 @@ func (e *Endpoint) writeL4Map(fw *bufio.Writer, owner Owner, m policy.L4PolicyMa
 		dport := byteorder.HostToNetwork(uint16(l4.Port))
 
 		redirect := uint16(l4.L7RedirectPort)
-		if l4.IsRedirect() && redirect == 0 {
-			redirect, err = e.addRedirect(owner, &l4)
```
Comment (aanm) [inline pkg/endpoint/bpf.go:66]: You can't remove the `addRedirect` from here because this is the function that allocate the redirect port. The redirect is also used on line 66.

**Review by aanm — CHANGES_REQUESTED** [review]

File: pkg/endpoint/bpf.go (hunk 1 above)
Comment (joestringer) [reply pkg/endpoint/bpf.go:66]: What's the dependency? It's still being allocated in the code below under the same endpoint.Mutex, the call is just not so deep in the stack.

**Review by aanm — APPROVED** [review]
