### PR TITLE
datapath: Only NOTRACK proxy return traffic going to Cilium datapath

### LINKED ISSUE #8945: CI: K8sServiceTest Tests NodePort BPF
The test suite seems to be flaky. The example failure:

```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-Validated/k8s-1.10-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:420
Pod "testclient-6zb5g" can not connect to service "http://127.0.0.1:32174"
Expected command: kubectl exec -n default testclient-6zb5g -- curl --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 8 http://127.0.0.1:32174 -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
To succeed, but it failed:
Exitcode: 28 
Stdout:
 	 time-> DNS: '0.000021()', Connect: '0.000000',Transfer '0.000000', total '5.000594'
Stderr:
 	 command terminated with exit code 28 
```

The following instances of the failure were observed:

- From pod curl to ClusterIP.
- From pod curl to 127.0.0.1:NodePort
- From pod curl to PublicIP:NodePort

The tunnel / direct routing mode setting does not matter, as the test failed in both modes. In all cases `bpf_sock.c` (aka host-reachable services) was involved.

* https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/14436/testReport/junit/Suite-k8s-1/10/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan/ : 
[de1ae283_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan.zip](https://github.com/cilium/cilium/files/3516090/de1ae283_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan.zip)

* https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-Validated/14440/testReport/junit/Suite-k8s-1/10/K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan/ : 
[d2d95800_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan.zip](https://github.com/cilium/cilium/files/3515203/d2d95800_K8sServicesTest_Checks_service_across_nodes_Tests_NodePort_BPF_Tests_with_vxlan.zip)

/cc @borkmann

### LINKED ISSUE #8971: NodePort BPF service cannot be reached when L7 policy is applied / L7 visibility is enabled
A NodePort BPF service cannot be reached when:

- and L7 allow all policy is applied,
- and a request to the service is sent to a host which runs the service endpoint pod.

Sending the request to a host which SNATs the request and forwards it to the destination host works as expected.

The request (TCP SYN) enters the relevant TPROXY rule at the receiving host, and then disappears:

```
IN=cilium_net OUT= MAC=16:6a:8a:0b:7c:e0:36:d7:19:cb:ee:ec:08:00 SRC=192.168.34.11 DST=10.217.1.215 LEN=60 TOS=0x00 PREC=0x00 TTL=62 ID=15285 DF PROTO=TCP SPT
=56576 DPT=80 WINDOW=64240 RES=0x00 SYN URGP=0 MARK=0x1927020
```

### PR DESCRIPTION
**Pull request by jrajahalme**
Proxy return traffic accessed via a k8s NodePort will not be routed
back via Cilium bpf datapath, so such traffic needs to have possible
reverse NAT applied. Setting NOTRACK prevented this. Fix this by
setting NOTRACK only on packets heading back to the Cilium datapath
(`-o lxc+` and `-o cilium_host`).

Fixes: #8971
Fixes: #8945
Signed-off-by: Jarno Rajahalme <jarno@covalent.io>

### CODE REVIEW

**Comment by jrajahalme** [comment]
test-me-please

**Comment by jrajahalme** [comment]
test-gke

**Comment by jrajahalme** [comment]
This fixed nodeport with L7 on GKE on manual testing.

**Comment by jrajahalme** [comment]
1.17 flake #10231

**Comment by jrajahalme** [comment]
K8s test suite passed on GKE with this PR:
```
Ran 63 of 396 Specs in 5813.792 seconds
SUCCESS! -- 63 Passed | 0 Failed | 2 Pending | 331 Skipped
PASS
```

**Comment by jrajahalme** [comment]
retest-4.19

**Comment by jrajahalme** [comment]
retest-gke

File: pkg/datapath/iptables/iptables.go [hunk 1]
```diff
@@ -574,11 +574,23 @@ func (m *IptablesManager) installStaticProxyRules() error {
...
+			// No conntrack for proxy return traffic that is heading to lxc+
+			err = runProg("iptables", append(
+				m.waitArgs,
+				"-t", "raw",
+				"-A", ciliumOutputRawChain,
+				"-o", "lxc+",
+				"-m", "mark", "--mark", matchProxyReply,
+				"-m", "comment", "--comment", "cilium: NOTRACK for proxy return traffic",
+				"-j", "NOTRACK"), false)
+		}
```
Comment (joestringer) [inline pkg/datapath/iptables/iptables.go:586]: Interesting, OK, so overall we're basically reducing the scope of this rule to only apply to traffic going towards the endpoints. The change below to add `-o cilium_host` supports this for the regular mode, then this rule supports this for `--enable-endpoint-routes` where the packets destined for a pod are routed directly to the `lxc` device. Should we gate this particular rule insertion by `--enable-endpoint-routes` mode?

**Comment by joestringer** [comment]
Change makes sense, probably just worth considering whether to further gate one of the new rules.

I don't think it makes sense to backport to v1.6, we're not hearing reports of issues on that release with eg. EKS. This fixes a known issue with the GKE mode which is the same on v1.7 and v1.8 so those backports make sense to me.

**Review by joestringer — CHANGES_REQUESTED** [review]
We should agree on the previous comment before merging: 

https://github.com/cilium/cilium/pull/11899/files#r436051065

File: pkg/datapath/iptables/iptables.go (hunk 1 above)
Comment (tgraf) [reply pkg/datapath/iptables/iptables.go:586]: Given that we want to move towards enabling endpoint routes by default, I'm OK to add it unconditionally. `installForwardChainRules()` also adds these rules unconditionally.

**Review by tgraf — APPROVED** [review]

**Review by joestringer — APPROVED** [review]

**Comment by joestringer** [comment]
Merging despite GKE failure since the GKE job seems entirely broken but Jarno had manually validated the fix in a GKE environment.
