### PR TITLE
bpf: fib: always use bpf_redirect_neigh() when available

### LINKED ISSUE #34503: Stale neighbor entry keeps breaking nodeport return packets
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.14.13 and lower than v1.15.0

### What happened?

nodeport return packets uses bpf_fib_lookup to decide dst mac. When the entry is stale, no kernel refresh is triggered and bpf code keeps using stale mac  and broken if the mac is wrong. This can happen when the mac bound to the IP changes.

### How can we reproduce the issue?

1. create a node port service. say 10.251.23.28:30211 ( 10.251.23.28 is a node-ip)
2. run `curl 10.251.23.28:30211` from a non-cluster machine in the same L2 subnet. e.g. 10.251.23.29. confirm nodeport is working
3. run `ip neigh replace 10.251.23.29 dev eth0 lladdr aa:bb:cc:dd:ee:ff nud stale` on `10.251.23.28`
4. `curl 10.251.23.28:30211` is broken forever on `10.251.23.29`

### Cilium Version

1.14.13

### Kernel Version

5.15.0

### Kubernetes Version

v1.30.3

### Regression

_No response_

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jrife**
In some environments, neighbor entries for non-cluster hosts remain stale forever, breaking connectivity in cases where their IP is reassigned to a new host with a different MAC address. This isn't a problem for hosts within the cluster; Cilium sets the `managed` and `extern_learn` flags for those neighbor entries, so the kernel actively refreshes them.

In our particular case, we have a set of VMs forming our Kubernetes cluster running a NodePort service and another VM in the same L2 domain talking to that service. This set of VMs is upgraded as a unit by spinning up new VMs, draining the old ones, and reassigning the IP addresses, although not necessarily in that order. At some point during this process, the MAC address assigned to the IP for that external VM changes. The network switches in our setup enable ARP suppression which, as I understand it, suppresses GARPs if the ARP suppression cache on the switch already has an entry for a given MAC address. This, combined with Cilium's current behavior leads to a situation where we we need to apply some workarounds to get things talking again. What we hope would occur is that cluster nodes would send an ARP request for any STALE neighbor entries in their ARP table, but currently this never happens.

`fib_redirect()` and others call `bpf_fib_lookup()` and pass its result along to `fib_do_redirect()`. Currently, `fib_do_redirect()` only uses `bpf_redirect_neigh()` if the FIB lookup was unsuccessful, returning `BPF_FIB_LKUP_RET_NO_NEIGH`. Otherwise, it "manually" populates the L2 header of the packet and uses `bpf_redirect()` to send it out through the host interface. However, `bpf_fib_lookup()` returns `BPF_FIB_LKUP_RET_SUCCESS` regardless of the state of the neighbor entry, and `bpf_redirect()` doesn't trigger a neighbor event in the kernel. The net result is that stale entries can remain stale which is problematic in setups like the one described above.

* The first commit makes it so Cilium always uses `bpf_redirect_neigh()` when available to trigger refresh of stale entries and avoid corner cases like ours where invalid entries can can remain stale forever. 

* The last two commits use the `BPF_FIB_LOOKUP_SKIP_NEIGH` [1] flag in preceding calls to `bpf_fib_lookup()` to avoid duplicate work in cases where we want to defer to `bpf_redirect_neigh()` for the neighbor resolution. The first commit introduces a probe that ensures that `BPF_FIB_LOOKUP_SKIP_NEIGH` is supported on the current system, as some older kernels may support `bpf_fib_lookup()` but not the `BPF_FIB_LOOKUP_SKIP_NEIGH` flag. The second commit plumbs through the probe result to let the FIB code decide whether or not to set it.

[1]: [`bpf: Add BPF_FIB_LOOKUP_SKIP_NEIGH for bpf_fib_lookup`](https://github.com/torvalds/linux/commit/31de4105f00d64570139bc5494a201b0bd57349f)

### Without This Change

The neighbor entry for 192.168.4.255, a VM in the same L2 domain as my cluster nodes, remains STALE after making an HTTP request to a NodePort service hosted on that node.

```
jordan@crow:~$ ip neigh | grep 225
192.168.4.225 dev enp5s0 lladdr bc:24:11:93:7f:d4 STALE
...
jordan@crow:~$ ip neigh | grep 225
192.168.4.225 dev enp5s0 lladdr bc:24:11:93:7f:d4 STALE
```

### With This Change

The HTTP request from 192.168.4.255 triggers a neighbor event on the cluster node, so the neighbor entry transitions from STALE to REACHABLE.

```
jordan@crow:~$ ip neigh | grep 192.168.4.225
192.168.4.225 dev enp5s0 lladdr bc:24:11:93:7f:d4 STALE
...
jordan@crow:~$ ip neigh | grep 192.168.4.225
192.168.4.225 dev enp5s0 lladdr bc:24:11:93:7f:d4 DELAY
...
jordan@crow:~$ ip neigh | grep 192.168.4.225
192.168.4.225 dev enp5s0 lladdr bc:24:11:93:7f:d4 REACHABLE
```

Fixes: #34503

```release-note
bpf: fib: Fix issue where neighbor entries remain stale forever in some cases.
```

### CODE REVIEW

**Comment by ysksuzuki** [comment]
Thank you for the PR! I have two questions.

- Have you considered making this behavior, where bpf_redirect_neigh() is always used when available, opt-in instead of enabling it by default? Or have you already evaluated that the potential performance impact would be trivial?
- Does this issue occur only when the destination is a host outside the cluster? If so, would it be worth considering an optimization where bpf_redirect_neigh() is always used only when the destination is outside the cluster?

**Review by ysksuzuki — COMMENTED** [review]
Thank you for the PR! I have two questions.

- Have you considered making this behavior, where bpf_redirect_neigh() is always used when available, opt-in instead of enabling it by default? Or have you already evaluated that the potential performance impact would be trivial?
- Does this issue occur only when the destination is a host outside the cluster? If so, would it be worth considering an optimization where bpf_redirect_neigh() is always used only when the destination is outside the cluster?

**Comment by borkmann** [comment]
> In some environments, neighbor entries for non-cluster hosts remain stale forever, breaking connectivity in cases where their IP is reassigned to a new host with a different MAC address. This isn't a problem for hosts within the cluster; Cilium sets the `managed` and `extern_learn` flags for those neighbor entries, so the kernel actively refreshes them.
> 
> In our particular case, we have a set of VMs forming our Kubernetes cluster running a NodePort service and another VM in the same L2 domain talking to that service. This set of VMs is upgraded as a unit by spinning up new VMs, draining the old ones, and reassigning the IP addresses, although not necessarily in that order. At some point during this process, the MAC address assigned to the IP for that external VM changes. The network switches in our setup enable ARP suppression which, as I understand it, suppresses GARPs if the ARP suppression cache on the switch already has an entry for a given MAC address. This, combined with Cilium's current behavior leads to a situation where we we need to apply some workarounds to get things talking again. What we hope would occur is that cluster nodes would send an ARP request for any STALE neighbor entries in their ARP table, but currently this never happens.
> 
> `fib_redirect()` and others call `bpf_fib_lookup()` and pass its result along to `fib_do_redirect()`. Currently, `fib_do_redirect()` only uses `bpf_redirect_neigh()` if the FIB lookup was unsuccessful, returning `BPF_FIB_LKUP_RET_NO_NEIGH`. Otherwise, it "manually" populates the L2 header of the packet and uses `bpf_redirect()` to send it out through the host interface. However, `bpf_fib_lookup()` returns `BPF_FIB_LKUP_RET_SUCCESS` regardless of the state of the neighbor entry, and `bpf_redirect()` doesn't trigger a neighbor event in the kernel. The net result is that stale entries can remain stale which is problematic in setups like the one described above.
> 
> Always use `bpf_redirect_neigh()` if available to trigger refresh of stale entries and avoid corner cases like ours where invalid entries can can remain stale forever. Use `BPF_FIB_LOOKUP_SKIP_NEIGH` [1] in preceding calls to `bpf_fib_lookup()` to avoid duplicate work.
> 
> [1]: [`bpf: Add BPF_FIB_LOOKUP_SKIP_NEIGH for bpf_fib_lookup`](https://github.com/torvalds/linux/commit/31de4105f00d64570139bc5494a201b0bd57349f)

Hey Jordan, just a question for clarification:

In the kernel's BPF fib lookup helper, we test nud_state for NUD_VALID (https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/core/filter.c#n6180):
```
	if (!neigh || !(READ_ONCE(neigh->nud_state) & NUD_VALID))
		return BPF_FIB_LKUP_RET_NO_NEIGH;
```

The NUD_VALID is defined as (https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/net/neighbour.h#n39):
```
#define NUD_VALID	(NUD_PERMANENT|NUD_NOARP|NUD_REACHABLE|NUD_PROBE|NUD_STALE|NUD_DELAY)
```

The kernel has a `NEIGH_VAR_BASE_REACHABLE_TIME_MS` which iiuc defines the period:
```
base_reachable_time (since Linux 2.2) Once a neighbor has been found, the entry is considered to be valid for at least a random value between base_reachable_time/2 and 3*base_reachable_time/2. An entry's validity will be extended if it receives positive feedback from higher level protocols. Defaults to 30 seconds. This file is now obsolete in favor of base_reachable_time_ms. base_reachable_time_ms (since Linux 2.6.12) As for base_reachable_time, but measures time in milliseconds. Defaults to 30000 milliseconds.
```

Dumb q: Would it rather make sense to tweak base reachable time instead?

**Comment by borkmann** [comment]
> ### Without This Change
> The neighbor entry for 192.168.4.255, a VM in the same L2 domain as my cluster nodes, remains STALE after making an HTTP request to a NodePort service hosted on that node.
> 
> ```
> jordan@crow:~$ ip neigh | grep 225
> 192.168.4.225 dev enp5s0 lladdr bc:24:11:93:7f:d4 STALE
> ...
> jordan@crow:~$ ip neigh | grep 225
> 192.168.4.225 dev enp5s0 lladdr bc:24:11:93:7f:d4 STALE
> ```
> 
> ### With This Change
> The HTTP request from 192.168.4.255 triggers a neighbor event on the cluster node, so the neighbor entry transitions from STALE to REACHABLE.
> 
> ```
> jordan@crow:~$ ip neigh | grep 192.168.4.225
> 192.168.4.225 dev enp5s0 lladdr bc:24:11:93:7f:d4 STALE
> ...
> jordan@crow:~$ ip neigh | grep 192.168.4.225
> 192.168.4.225 dev enp5s0 lladdr bc:24:11:93:7f:d4 DELAY
> ...
> jordan@crow:~$ ip neigh | grep 192.168.4.225
> 192.168.4.225 dev enp5s0 lladdr bc:24:11:93:7f:d4 REACHABLE
> ```

Is it correct to assume that the above entries are the backend IPs? If yes, would this PR which is in main already have helped? https://github.com/cilium/cilium/pull/37352

**Comment by jrife** [comment]
@ysksuzuki,

> Thank you for the PR! I have two questions.
>
> * Have you considered making this behavior, where bpf_redirect_neigh() is always used when available, opt-in instead of enabling it by default? Or have you already evaluated that the potential performance impact would be trivial?

Thank you for taking a look! In my view this should simply be the default behavior if there are no ill effects, as it works for a broader set of circumstances. I've run some iperf3 benchmarks at 100 Gbps and did not experience any noticeable changes in throughput or CPU utilization between this and the old approach. I will try to find the measurements somewhere and provide them here. I'm happy to run some additional benchmarks if you are not convinced though :).

> * Does this issue occur only when the destination is a host outside the cluster? If so, would it be worth considering an optimization where bpf_redirect_neigh() is always used only when the destination is outside the cluster?

The issue I experienced does, yes. Outside the cluster but in the same L2 domain as the cluster nodes. I believe it may further complicate things in `fib.h` to need to differentiate between cluster and non-cluster IPs as we invoke `fib_do_redirect()`. If there is no performance concern I think we should aim for the simplest approach.

@borkmann,

> Dumb q: Would it rather make sense to tweak base reachable time instead? Is that mostly for NUD_REACHABLE state or does it also relate to NUD_STALE somehow?

If my read of the docs and code is correct, I'm not sure tweaking this solves the underlying issue. Seems like it just takes longer for the entry to go stale? A long enough timeout may mask the issue I described in one environment, but as with any timeout value, what works in one environment may not work for another.

> Are you saying with redirect_neigh() the NUD_STALE automatically triggers a new resolution to go back into NUD_REACHABLE?

Right, any subsequent calls to `neigh_output()` after `neigh_suspect()` happens (when an entry goes stale) triggers `neigh_resolve_output()` as opposed to the usual `neigh_connected_output()`. `neigh_resolve_output()` triggers `neigh_event_send()` before jumping into `dev_queue_xmit()`.

```
static const struct neigh_ops arp_generic_ops = {
	.family =		AF_INET,
	.solicit =		arp_solicit,
	.error_report =		arp_error_report,
	.output =		neigh_resolve_output,
	.connected_output =	neigh_connected_output,
};

static const struct neigh_ops arp_hh_ops = {
	.family =		AF_INET,
	.solicit =		arp_solicit,
	.error_report =		arp_error_report,
	.output =		neigh_resolve_output,
	.connected_output =	neigh_resolve_output,
};
```

```c
static inline int neigh_event_send(struct neighbour *neigh, struct sk_buff *skb)
{
	return neigh_event_send_probe(neigh, skb, true);
}
```

> Is it correct to assume that the above entries are the backend IPs? If yes, would this PR which is in main already have helped? https://github.com/cilium/cilium/pull/37352

To clarify, `192.168.4.225` is the IP of another VM in the same L2 domain as my cluster nodes but not part of the cluster itself. The neighbor entry exists on my cluster node (`crow`) as `192.168.4.225` talks to a node port service hosted on `crow`. I'm not sure https://github.com/cilium/cilium/pull/37352 helps here, as it seems to be targeting neighbor entries for backends managed by Cilium itself.

All in all, `bpf_redirect_neigh()` keeps neighbor entries fresh in addition to doing the neigh table lookup. By and large, Cilium keeps most relevant neighbor entries fresh (`managed extern_learn` for cluster nodes, etc.), but there are some corner cases lurking like this one. I was actually surprised to learn that Cilium doesn't already just default to `bpf_redirect_neigh()` wherever possible, as it seems like the behavior more closely matches what you'd get when using the kernel's stack. This could be my own ignorance talking though.

Are there performance reasons for the current preference for `bpf_redirect()` in most cases? I was concerned at first there might be a performance hit switching to `bpf_redirect_neigh()` in all cases due to the duplicated neighbor lookup (at least without `BPF_FIB_LOOKUP_SKIP_NEIGH`) in `bpf_fib_lookup()` and some of the extra work it has to do  compared to `bpf_redirect()`. I was unable to detect any significant differences with 100 Gbps iperf3 test which I'm happy to share here, although that doesn't mean they don't exist :). If indeed we are concerned about every ounce of performance and `bpf_redirect_neigh()` is noticeably slower or worse in some dimension, perhaps we can be a bit more intelligent about when we use `bpf_redirect_neigh()` as @ysksuzuki hinted at above; however, I wanted to explore the simple approach first.

**Comment by ysksuzuki** [comment]
> To clarify, 192.168.4.225 is the IP of another VM in the same L2 domain as my cluster nodes but not part of the cluster itself. The neighbor entry exists on my cluster node (crow) as 192.168.4.225 talks to a node port service hosted on crow

@jrife Just to confirm, the issue occurs when the datapath handles the reply traffic from the backends at `nodeport_rev_dnat_ingress_ipv[4,6]`, and it hits a stale ARP cache entry for the client `192.168.4.225`?

We can rely on the `managed` and `extern_learn` neighbor entries for the backends in the forward path. (With #37352, the Cilium agent manages these entries even if the backends are external hosts.) However,  we can't rely on them in the reply path, as the Cilium agent doesn't manage the client's neighbor entries.

**Comment by jrife** [comment]
Bumping this thread again, since I'm not sure what the verdict was here @ysksuzuki .

**Comment by jrife** [comment]
@borkmann @ysksuzuki Looks like this one went stale. I'm wondering what the resolution is here. Is there anything in particular you are concerned about or data you would like to see?

**Comment by jrife** [comment]
> My immediate reaction to this was "ugh, this feels like a workaround for something that should be improved in the kernel. And it won't help bpf_xdp when encountering the same problem".

From my point of view, it's less a kernel issue and more that the behavior of `bpf_redirect` skips a step that the kernel would normally perform on the way out, namely engaging with the neighboring subsystem and triggering side-effects like neighbor resolution on stale entires. `bpf_redirect_neigh` *does* do this stuff, so all things being equal (including performance) I'm not sure why you wouldn't just prefer `redirect_neigh` here; it seems like you'd be less likely to hit weird edge cases like this. Any insight into why `bpf_redirect` is currently preferred here?

**Comment by borkmann** [comment]
> > My immediate reaction to this was "ugh, this feels like a workaround for something that should be improved in the kernel. And it won't help bpf_xdp when encountering the same problem".
> 
> From my point of view, it's less a kernel issue and more that the behavior of `bpf_redirect` skips a step that the kernel would normally perform on the way out, namely engaging with the neighboring subsystem and triggering side-effects like neighbor resolution on stale entires. `bpf_redirect_neigh` _does_ do this stuff, so all things being equal (including performance) I'm not sure why you wouldn't just prefer `redirect_neigh` here; it seems like you'd be less likely to hit weird edge cases like this. Any insight into why `bpf_redirect` is currently preferred here?

Yes, we should just stick to `redirect_neigh` and remove the corner cases. For XDP it's unfortunately not possible to resolve anything ad-hoc, so there we need to rely on managed neigh to keep entries fresh and have this corner case wrt staleness for non-managed neighbors.

**Comment by julianwiedmann** [comment]
> At the same time, once #38308 is merged I feel it's a good moment to take a fresh look at all our FIB-driven redirect handling. And see whether we can simplify the logic more, or extend it to also cover scenarios like this.

Started [here](https://github.com/cilium/cilium/pull/39490), would be cool to rebase once this lands and see how easy the code looks overall.

File: bpf/lib/egress_gateway.h [hunk 1]
```diff
@@ -43,7 +43,9 @@ int egress_gw_fib_lookup_and_redirect(struct __ctx_buff *ctx, __be32 egress_ip,
 	if (egress_ifindex && neigh_resolver_available())
 		return redirect_neigh(egress_ifindex, NULL, 0, 0);
 
-	ret = (__s8)fib_lookup_v4(ctx, &fib_params, egress_ip, daddr, 0);
+	ret = (__s8)fib_lookup_v4(ctx, &fib_params, egress_ip, daddr,
+				  neigh_resolver_available()
+				  ? BPF_FIB_LOOKUP_SKIP_NEIGH : 0);
```
Comment (julianwiedmann) [inline bpf/lib/egress_gateway.h]: Just to reduce the churn in the patch, you could push this logic down into the `fib_lookup_v4()` and `fib_lookup_v6()` helpers.

Comment (jrife) [reply bpf/lib/egress_gateway.h]: > Just to reduce the churn in the patch, you could push this logic down into the fib_lookup_v4() and fib_lookup_v6() helpers.

IIRC there was some reason I didn't do this, but I'll take another look and see if it's possible.

**Comment by jrife** [comment]
> Started https://github.com/cilium/cilium/pull/39490, would be cool to rebase once this lands and see how easy the code looks overall.

Sure I can wait for this to merge. This PR probably needs a rebase in general, since it's a bit old.

File: bpf/lib/egress_gateway.h (hunk 1 above)
Comment (jrife) [reply bpf/lib/egress_gateway.h]: I went ahead and pushed this into `fib_lookup_v(4|6)`. My main concern before was that setting the flag inside the function doesn't make sense if there are callers that don't immediately follow up with a call to `fib_do_redirect`. However, as far as I can tell, this seems to be the usage pattern all over. Feel free to take another look.

*Note*: Unit tests are passing, but looks like some CI issue is currently blocking image builds for smoke tests, conformance tests, etc. Filed https://github.com/cilium/cilium/issues/39600

**Comment by jrife** [comment]
@julianwiedmann Can you take another look at this? Thanks!

**Comment by jrife** [comment]
[`ci-clustermesh`](https://github.com/cilium/cilium/actions/runs/16896037840/job/47866139477) looks a bit like https://github.com/cilium/cilium/issues/39855 (duplicate of https://github.com/cilium/cilium/issues/39370), or at least the part that https://github.com/cilium/cilium/pull/40690 doesn't filter out:

```
time=2025-08-12T01:15:14.598088872Z level=error source=/go/src/github.com/cilium/cilium/pkg/endpointmanager/endpointsynchronizer.go:309 msg="Cannot update CEP" containerID=952705cc68 containerInterface=eth0 identity=43610 ciliumEndpointName=kube-system/clustermesh-apiserver-8fb576fdf-glj8n ipv6=fd00:10:242:2::db00 desiredPolicyRevision=2 endpointID=754 datapathPolicyRevision=0 k8sPodName=kube-system/clustermesh-apiserver-8fb576fdf-glj8n ipv4=10.242.2.71 subsys=endpointsynchronizer controller="sync-to-k8s-ciliumendpoint (754)" error="ciliumendpoints.cilium.io \"clustermesh-apiserver-8fb576fdf-glj8n\" not found" (2 occurrences)
```

Retriggering for now.

**Comment by jrife** [comment]
@julianwiedmann @ysksuzuki @cilium/sig-datapath Can someone take another look at this?

File: bpf/lib/fib.h [hunk 2]
```diff
@@ -91,61 +91,65 @@ fib_do_redirect(struct __ctx_buff *ctx, const bool needs_l2_check,
...
+			nh_params.nh_family = fib_params->l.family;
+			__bpf_memcpy_builtin(&nh_params.ipv6_nh,
+					     &fib_params->l.ipv6_dst,
+					     sizeof(nh_params.ipv6_nh));
+
+			return (int)redirect_neigh(oif, &nh_params,
+						   sizeof(nh_params), 0);
+		}
+
+		return (int)redirect_neigh(oif, NULL, 0, 0);
```
Comment (borkmann) [inline bpf/lib/fib.h:111]: small nit here and elsewhere: do we need the explicit `(int)` casts? I'd remove them if not since the function already returns int in its signature. rest lgtm, lets get this in! thanks Jordan!

**Review by borkmann — APPROVED** [review]

File: bpf/lib/fib.h (hunk 2 above)
Comment (jrife) [reply bpf/lib/fib.h:111]: Maybe not, but this is how they were before; I just removed lines and changed indention in this PR. It might be better to open another PR for `(int)` cleanup here and other places.

**Comment by jrife** [comment]
Looks like this needs a review from @cilium/loader . @rgo3 @dylandreimerink ?

File: pkg/datapath/linux/probes/probes.go [hunk 3]
```diff
@@ -435,6 +436,41 @@ func HaveIPv6Support() error {
...
+
+	defer objs.Close()
+
+	ret, err := objs.ProbeFibLookupSkipNeigh.Run(&ebpf.RunOptions{
+		// Newer kernels require that data is at least 14 bytes:
+		// https://github.com/torvalds/linux/commit/6b3d638ca897e099fa99bd6d02189d3176f80a47
+		Data:   make([]byte, 14),
+		Repeat: 1,
+	})
+	var ve *ebpf.VerifierError
```
Comment (rgo3) [inline pkg/datapath/linux/probes/probes.go]: This doesn't look right to me. Shouldn't the check for a verifier error happen after loading the program, in this case `LoadProbesObjects`?

File: pkg/datapath/linux/probes/probes.go [hunk 4]
```diff
@@ -435,6 +436,41 @@ func HaveIPv6Support() error {
...
+	if errors.As(err, &ve) {
+		if _, err := fmt.Fprintf(os.Stderr, "Verifier error: %s\nVerifier log: %+v\n", err, ve); err != nil {
+			return fmt.Errorf("writing verifier log to stderr: %w", err)
+		}
+	}
+	if err != nil {
+		return fmt.Errorf("loading eBPF collection into the kernel: %w", err)
```
Comment (rgo3) [inline pkg/datapath/linux/probes/probes.go]: This should indicate that the error happened when trying to run the program, as loading has already succeeded previously
```suggestion
		return fmt.Errorf("running probe program: %w", err)
```

File: pkg/datapath/linux/requirements.go [hunk 5]
```diff
@@ -114,6 +114,18 @@ func CheckRequirements(log *slog.Logger) error {
...
 			return errors.New("Require support for bpf_redirect_peer() (Linux 5.10.0 or newer)")
 		}
+
+		if err := probes.HaveFibLookupSkipNeigh(); err != nil {
+			if errors.Is(err, ebpf.ErrNotSupported) {
+				log.Info("BPF_FIB_LOOKUP_SKIP_NEIGH is not supported; it will not be used",
+					logfields.Error, err,
+				)
+			} else {
+				log.Warn("Unable to determine if BPF_FIB_LOOKUP_SKIP_NEIGH is supported; it will not be used",
```
Comment (rgo3) [inline pkg/datapath/linux/requirements.go]: What is the expected outcome of this probe on kernels <6.6? Does the probe return `ErrNotSupported` or another error code?
I'm asking because for most of the other probes, unless the error is `ErrNotSupported` we return an error and not just warn users about something that isn't expected to happen.

**Review by rgo3 — CHANGES_REQUESTED** [review]

File: bpf/lib/nodeport.h [hunk 6]
```diff
@@ -195,7 +195,9 @@ nodeport_fib_lookup_and_redirect(struct __ctx_buff *ctx,
 	__u32 oif;
 	int ret;
 
-	ret = (int)fib_lookup(ctx, &fib_params->l, sizeof(fib_params->l), 0);
+	ret = (int)fib_lookup(ctx, &fib_params->l, sizeof(fib_params->l),
+			      neigh_resolver_available()
+			      ? fib_lookup_skip_neigh() : 0);
```
Comment (pchaigno) [inline bpf/lib/nodeport.h]: Nit (i.e., not going to block on this): It feels like this would be a bit more readable with a new helper function:
```c
static __always_inline __u64 fib_lookup_neigh_flags(void)
{
        return neigh_resolver_available()? fib_lookup_skip_neigh() : 0;
}
```
which you could then just use in the 4 places to mask the condition. Or you could also fold the condition in `fib_lookup_skip_neigh()` directly.

**Review by pchaigno — APPROVED** [review]
LGTM assuming Robin's comments are addressed.

File: bpf/lib/fib.h (hunk 2 above)
Comment (pchaigno) [reply bpf/lib/fib.h:111]: Yep, looks like we're already doing this in multiple other places, so not going to block on it. Though if we're touching this code and you're repushing anyway, it's probably worth fixing.

File: pkg/datapath/linux/probes/probes.go (hunk 3 above)
Comment (jrife) [reply pkg/datapath/linux/probes/probes.go]: Yes. Good catch. I moved some things around and forgot to adjust where I do the `VerifierError` check. Thanks!

File: pkg/datapath/linux/requirements.go (hunk 5 above)
Comment (jrife) [reply pkg/datapath/linux/requirements.go]: > What is the expected outcome of this probe on kernels <6.6?

It should return `ErrNotSupported` if the flag isn't available on the current kernel. I confirmed this by observing CI and seeing runs on older kernels spit out that message.

> I'm asking because for most of the other probes, unless the error is ErrNotSupported we return an error and not just warn users about something that isn't expected to happen.

I considered returning an error instead, but didn't want to block startup on this requirement, since it's not strictly necessary for correct datapath operation (it's more of an optimization).

File: bpf/lib/fib.h (hunk 2 above)
Comment (jrife) [reply bpf/lib/fib.h:111]:
```
/go/src/github.com/cilium/cilium/bpf/lib/fib.h:111:10: error: implicit conversion loses integer precision: 'long' to 'int' [-Werror,-Wshorten-64-to-32]
  111 |                 return redirect_neigh(oif, NULL, 0, 0);
      |                 ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

It looks like the casts are necessary to make the compiler happy. Probably why they were there before.

File: bpf/lib/nodeport.h (hunk 6 above)
Comment (jrife) [reply bpf/lib/nodeport.h]: Done. I just rolled this all into `fib_lookup_skip_neigh` to make things simpler.

**Comment by jrife** [comment]
`ci-gateway-api` [failure](https://github.com/cilium/cilium/actions/runs/16993917622/job/48179885406) looks like https://github.com/cilium/cilium/issues/40243. Retriggering.

**Comment by jrife** [comment]
`ci-ginkgo` is failing fairly consistently with

```
• Failure [173.568 seconds]
K8sDatapathServicesTest
/home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:461
  Checks N/S loadbalancing
  /home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:461
    With ClusterIP external access
    /home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:461
      ClusterIP can be accessed when external access is enabled [It]
      /home/runner/work/cilium/cilium/test/ginkgo-ext/scopes.go:515

      cannot curl to service IP from host: time-> DNS: '0.000022()', Connect: '0.000000',Transfer '0.000000', total '0.000000'command terminated with exit code 7
      
      Expected command: kubectl exec -n kube-system log-gatherer-52wsk -- curl -k --path-as-is -s -D /dev/stderr --fail --connect-timeout 5 --max-time 20 [http://10.96.114.208:80/](http://10.96.114.208/) -w "time-> DNS: '%{time_namelookup}(%{remote_ip})', Connect: '%{time_connect}',Transfer '%{time_starttransfer}', total '%{time_total}'" 
      To succeed, but it failed:
      Exitcode: 7 
      Err: exit status 7
      Stdout:
       	 time-> DNS: '0.000022()', Connect: '0.000000',Transfer '0.000000', total '0.000000'
      Stderr:
       	 command terminated with exit code 7
```

At a glance, this seems unrelated to this PR, as this is the first time I'm seeing this and started happening after I rebased. Inspecting [the most recent runs](https://github.com/cilium/cilium/actions/workflows/conformance-ginkgo.yaml) I see several runs with the same failure:

* https://github.com/cilium/cilium/actions/runs/16991274813
* https://github.com/cilium/cilium/actions/runs/16991468284
* https://github.com/cilium/cilium/actions/runs/16992137171
* https://github.com/cilium/cilium/actions/runs/16992791434
* https://github.com/cilium/cilium/actions/runs/16993917752
* https://github.com/cilium/cilium/actions/runs/16995052553

I'll do a bit more investigation and perhaps file a CI bug.

*Edit*: Another PR with the same [failure](https://github.com/cilium/cilium/actions/runs/16992137171/job/48174315532): https://github.com/cilium/cilium/pull/41190

**Comment by joestringer** [comment]
FWIW looking at the above links, if you browse to "Echo Workflow Dispatch Inputs" and expand the step inside, it's clear that these results are each from different PRs. The last link skipped that step, which implies the workflow was triggered directly (likely due to schedule) rather than via `workflow_dispatch`, so that likely means that it was also observed directly on a branch.

**Comment by jrife** [comment]
@joestringer Thanks. I just discovered the "Echo Workflow Dispatch Inputs" step after desperately searching for a way to correlate the run with its origin. I updated my description above to point to another example I found. Since this seems like a CI regression and not localized to this PR, I'll open an issue.

File: pkg/datapath/linux/requirements.go (hunk 5 above)
Comment (rgo3) [reply pkg/datapath/linux/requirements.go]: >I considered returning an error instead, but didn't want to block startup on this requirement, since it's not strictly necessary for correct datapath operation (it's more of an optimization).

This is a valid concern, but I'd like to maintain consistency across all probes we implement for Cilium. For Cilium, we've decided that probes should return conclusive results: `nil` or `ErrNotSupported`. Anything else is unexpected and shouldn't happen under normal operation, so it likely hints at a bigger issue and warrants a failure. See `HaveProgramHelper` as an example, only conclusive results are returned to callers, anything else fatals.

Unless this probe depends on specific kernel configuration that isn't required to run Cilium by default, I'd prefer to keep the same semantics and error handling across the package.

Comment (jrife) [reply pkg/datapath/linux/requirements.go]: > we've decided that probes should return conclusive results: nil or ErrNotSupported

Alright, I've done my best to adhere to this with the introduction of `HaveFibLookupSkipNeighNoFail` which guarantees that only `ErrNotSupported` or `nil` is returned much like some of the other probes. However, I've kept the original `HaveFibLookupSkipNeigh` as well. The relationship between `HaveFibLookupSkipNeighNoFail` and `HaveFibLookupSkipNeigh` mirrors that of, e.g., `probes.HaveProgramHelper` and `features.HaveProgramHelper` where the "outer" function guarantees only `ErrNotSupported` or `nil` are returned.

I considered just having a single `HaveFibLookupSkipNeigh` that does it all, but since it would need to accept a `logger` it didn't really make sense in the `pkg/datapath/loader/config.go` context:

```
node.SupportsFibLookupSkipNeigh = probes.HaveFibLookupSkipNeigh() == nil
```

I'd either have to pass in `nil` or plumb through a logger that isn't used. This seemed awkward, so I kept `HaveFibLookupSkipNeigh` for use inside `nodeConfig()`.

Comment (rgo3) [reply pkg/datapath/linux/requirements.go]: I probably chose the wrong wording here, I would have been fine with just doing the following in `requirements.go` which would eliminate the need for the wrapper. But consider this as a nit:

```golang
if err := probes.HaveFibLookupSkipNeigh(); err != nil {
    if !errors.Is(err, probes.ErrNotSupported) {
	    return errors.New("Unable to determine if BPF_FIB_LOOKUP_SKIP_NEIGH is supported")
    }
    log.Info("BPF_FIB_LOOKUP_SKIP_NEIGH is not supported; it will not be used", logfields.Error, err)
}
```

**Review by rgo3 — APPROVED** [review]
Only left one more nit, otherwise this LGTM for loader changes. Thanks for your patience Jordan!

**Comment by jrife** [comment]
The `ci-multi-pool` failure seems to be an existing flake looking at a series of recent runs. Created https://github.com/cilium/cilium/issues/41283 with details.

**Comment by jrife** [comment]
Retriggering ci-eks. Looks like the node groups couldn't be created (https://github.com/cilium/cilium/issues/40836). [Link](https://github.com/cilium/cilium/actions/runs/17075918069/job/48417194390)

File: bpf/include/bpf/config/node.h [hunk 7]
```diff
@@ -24,3 +24,6 @@ NODE_CONFIG(__u32, trace_payload_len, "Length of payload to capture when tracing
 NODE_CONFIG(__u32, trace_payload_len_overlay, "Length of payload to capture when tracing overlay packets.")
 
 NODE_CONFIG(__u32, direct_routing_dev_ifindex, "Index of the interface used to connect nodes in the cluster.")
+
+NODE_CONFIG(bool, supports_fib_lookup_skip_neigh,
+	    "Whether or not BPF_FIB_LOOKUP_SKIP_NEIGH is supported.")
```
Comment (julianwiedmann) [inline bpf/include/bpf/config/node.h:29]: For my own education - how would we accurately test this in `bpf/complexity-tests` ?

In the past we would simply add the relevant `HAVE_FEATURE_FOO` macro to the configs for relevant kernel versions. But for load-time configs that's no longer possible ...?

Comment (pchaigno) [reply bpf/include/bpf/config/node.h:29]: See https://github.com/cilium/cilium/pull/40367.

Comment (julianwiedmann) [reply bpf/include/bpf/config/node.h:29]: :+1: ok so on a casual look the new verifier-loader still needs to learn (for instance [here](https://github.com/cilium/cilium/blob/ce1f55100f689f6d4f24801f90c86578b8672a08/pkg/datapath/loader/verifier_load_test.go#L27)) how to set up `SupportsFibLookupSkipNeigh` according to the tested kernel version.

And that matches the fact that `ci-verifier` currently runs all its permutations with `SupportsFibLookupSkipNeigh:false`, even on `bpf-next`.

Comment (dylandreimerink) [reply bpf/include/bpf/config/node.h:29]: Yes, when we add new load time config option or convert from compile time we should add them to the ...Permutations function(s). We still have to figure out which combinations we want to run and which we don't care about as much (we are likely most interested in combinations that result in higher complexity, not all permutations possible).

Since that logic in Go, we should indeed be able to use probes instead of hard-coding settings to certain kernel versions.

**Comment by julianwiedmann** [comment]
@jrife fyi, re https://lore.kernel.org/netdev/20251003073418.291171-1-daniel@iogearbox.net/T/#u - we should have something [in-flight soon](https://github.com/cilium/cilium/pull/42000) that addresses the issue for Cilium.

**Comment by jrife** [comment]
@julianwiedmann great, thanks for the heads up.
