### PR TITLE
testing: final conversion 4.19 CI to kube-proxy free

### LINKED ISSUE #11175: Reduce BPF program complexity for kernel 4.19 (ipv4+ipv6+debug=false+vxlan+kubeProxyReplacement=strict VS. fragment support)
@brb reported that enabling a large set of features, even with `debug=false`, would have BPF `from_overlay()` fail to pass the verifier because it is bigger than the 4096-instruction limit.

From #11085:
> Also, validated on 4.19.57 with ipv4+ipv6+debug=false+vxlan+kubeProxyReplacement=strict - had to disable the ipv4 frags feature to make the verifier happy (otherwise, from-overlay is 26 insn over the limit

<details><summary><a href="https://cilium.slack.com/archives/CDKG8NNHK/p1587140038047900">Slack thread (#sig-datapath)</a></summary>

#### martynas Apr 17th
We are trying to enable all tests for test-with-kernel build which runs on 4.19.57 kernel (4k instr limit). There are problems with the BPF programs complexity though. By default, all tests run with --enable-debug=true which has been broken when running with ipv4+ipv6+nodeport+snat combo for quite some time (270 instr over the limit in from-overlay of bpf_overlay.c; I haven't found a commit which would not hit limit yet). If we disable the debug mode, we are still over the limit (14 instr) which is due to the recent ipv4 frag feature (/cc @qmo). So, I'm suggesting to run test-with-kernel with the debug mode disabled for now. The ipv4 frag issue should be fixed though. WDYT?

#### Joe
Yeah, I think getting coverage on this is better than getting debug messages although I'm sure it'll be painful to debug :confused:

#### qmo
Not sure how to remove insns for fragment support. But I can take a look.

#### Joe
does --enable-debug both enable the datapath debug config as well as control the cilium-agent logs? I'd want to make sure we at least still get the agent logs about the verifier failures

#### martynas
I believe that it enables both

#### Joe
that's my impression as well. But actually maybe it doesn't matter too much for this specific case because any verifier failure should actually print out the warning, shouldn't it?

#### martynas
yeah, it will crash the agent process anyway

#### Joe
would need to double-check that we print the verifier output if debug logs are disabled. I'm pretty sure we do if the load comes from bpf/init.sh because of the way the bash tracing works, but I'm not sure about the endpoint bpf loads where we invoke TC directly from Go

#### martynas
the failures are logged with level=warning, so it should print them before crashing

#### pchaigno
Is that 14 insns on 4096 that have to be found and removed? Or 14 on the other limit, 128k?

#### pchaigno
I'm guessing 14/4096. Then maybe we could get rid of the bit shift insns Clang generates?

    r0 <<= 32;
    r0 s>>= 32;

Almost all of those come from casting the return type of BPF helpers to int. If we keep u64 and bitmatch the MSB instead, we can probably reduce by 1 insn per helper call (for those where we actually check the return code), no?

#### martynas
it's 14/4096

#### daniel
Could we do the following: --enable-debug would be split to have the options of `--enable-debug=all|datapath|agent`so we can select if we want all as today, or only in datapath or only in agent . Then we can run bpf-next with all and 4.19 with agent so we still have debug messages there but avoid hitting the limit for BPF code where debug is not run in user's prod settings anyway.

#### daniel
And this also has the advantage that we actually test the BPF code with/without debug, so I think it would be a good idea.

#### martynas
yeah, makes sense

#### Joe

    > the failures are logged with level=warning, so it should print them before crashing

The warning itself, yes. I'm also concerned about the output from TC which IIRC is actually just printed to stdout, but might be gated by a conditional check for the log level

---
</details>

We should check if this issue can still be reproduced now that #11089 has been merged.

If it still occurs, some options to explore to save instructions could be:
- [ ] Save instructions in fragment handling somehow? (Not sure how)
- [x] Use `u64`s instead of `u32`s in code to avoid shifts by clang for zeroing upper half-registers?
- [ ] Split IPv4/IPv6 cases with tail calls.
- Other?

### PR DESCRIPTION
**Pull request by borkmann**
Re-enabling probe mode on 4.19.

Fixes: #11175

### CODE REVIEW

**Comment by borkmann** [comment]
retest-4.19

**Comment by borkmann** [comment]
test-focus K8sUpdates

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-focus K8sUpdates

**Comment by borkmann** [comment]
test-me-please

File: bpf/bpf_host.c [hunk 1]
```diff
@@ -1241,28 +1264,29 @@ int to_netdev(struct __ctx_buff *ctx __maybe_unused)
...
+		goto out_drop;
 #else
 	ret = CTX_ACT_OK;
 #endif /* ENABLE_HOST_FIREWALL */
 
-#if defined(ENABLE_NODEPORT) && \
-	(!defined(ENABLE_DSR) || \
-	 (defined(ENABLE_DSR) && defined(ENABLE_DSR_HYBRID)))
-	if ((ctx->mark & MARK_MAGIC_SNAT_DONE) != MARK_MAGIC_SNAT_DONE) {
-		ret = nodeport_nat_fwd(ctx, false);
```
Comment (pchaigno) [inline bpf/bpf_host.c:1257]: I don't think the host firewall is the main contributor to the program size here. It's only enabled where kube-proxy is disabled, which is not the case of the 4.19 pipeline yet. `nodeport_nat_fwd()` is the culprit here: the IPv4 and IPv6 paths are not in separate tail calls, which is what 26a39a8c9963325f2080ac24555067e1d17ca84b addresses.

**Comment by borkmann** [comment]
test-focus K8sUpdates

**Comment by borkmann** [comment]
test-focus K8sUpdates

**Comment by borkmann** [comment]
test-me-please

File: bpf/bpf_host.c (hunk 1 above)
Comment (borkmann) [reply bpf/bpf_host.c:1257]: > I don't think the host firewall is the main contributor to the program size here. It's only enabled where kube-proxy is disabled, which is not the case of the 4.19 pipeline yet. `nodeport_nat_fwd()` is the culprit here: the IPv4 and IPv6 paths are not in separate tail calls, which is what [26a39a8](https://github.com/cilium/cilium/commit/26a39a8c9963325f2080ac24555067e1d17ca84b) addresses.

The PR here re-enables kube-proxy-replacement probing again, which is why it gets otherwise hit on 4.19. I basically was trying to figure out if I could get away with something less complex given the 1.8 release just around the corner, and this one seemed to have resolved the issue, at least when I tried locally on 4.19.57. Will see how it goes, otherwise I can also take 26a39a8 with the earlier mentioned tweaks back in.

**Comment by borkmann** [comment]
test-focus K8sUpdates

**Comment by borkmann** [comment]
Ok, running `test-focus K8sUpdates` on net-next as stand-alone succeeds, but as part of the full net-next test suite fails. Presumably the initial cleanup might be from 1.7 image, checking..

**Comment by borkmann** [comment]
test-focus K8sUpdates

**Comment by borkmann** [comment]
retest-net-next

**Comment by borkmann** [comment]
retest-net-next

**Comment by borkmann** [comment]
test-focus K8sUpdates

**Comment by borkmann** [comment]
Still running net-next had upgrade test succeed:
```
22:03:51  K8sUpdates 
22:03:51    Tests upgrade and downgrade from a Cilium stable image to master
22:03:51    /home/jenkins/workspace/Cilium-PR-K8s-oldest-net-next/k8s-1.11-gopath/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:512
22:03:51  22:03:51 STEP: Running BeforeAll block for EntireTestsuite K8sUpdates
22:03:51  22:03:51 STEP: Ensuring the namespace kube-system exists
22:03:51  22:03:51 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs")
22:03:51  22:03:51 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-test-logs") => <nil>
22:04:14  22:04:12 STEP: Deleting Cilium and CoreDNS...
22:04:22  22:04:21 STEP: Waiting for pods to be terminated..
22:04:22  22:04:22 STEP: Cleaning Cilium state (latest)
22:04:26  22:04:25 STEP: Waiting for Cilium to become ready
22:04:26  22:04:25 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
22:04:31  22:04:30 STEP: Number of ready Cilium pods: 2
22:04:46  22:04:46 STEP: Cleaning Cilium state (v1.7)
22:04:48  22:04:48 STEP: Waiting for Cilium to become ready
22:04:48  22:04:48 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
22:04:54  22:04:53 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
22:04:58  22:04:58 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
22:05:03  22:05:03 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
22:05:08  22:05:08 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
22:05:13  22:05:13 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
22:05:19  22:05:18 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
22:05:24  22:05:23 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
22:05:28  22:05:28 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
22:05:33  22:05:33 STEP: Number of ready Cilium pods: 2
22:05:46  22:05:44 STEP: Deploying Cilium 1.7-dev
22:05:46  22:05:45 STEP: Waiting for Cilium to become ready
22:05:46  22:05:45 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
22:05:51  22:05:50 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
22:05:55  22:05:55 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
22:06:01  22:06:00 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
22:06:06  22:06:05 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
22:06:10  22:06:10 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
22:06:15  22:06:15 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
22:06:21  22:06:20 STEP: Cilium DaemonSet not ready yet: only 1 of 2 desired pods are ready
22:06:25  22:06:25 STEP: Cilium DaemonSet not ready yet: only 1 of 2 desired pods are ready
22:06:30  22:06:30 STEP: Number of ready Cilium pods: 2
22:06:30  22:06:30 STEP: Validating Cilium Installation
22:06:30  22:06:30 STEP: Performing Cilium controllers preflight check
22:06:30  22:06:30 STEP: Performing Cilium health check
22:06:30  22:06:30 STEP: Performing Cilium status preflight check
22:06:31  22:06:31 STEP: Performing Cilium service preflight check
22:06:31  22:06:31 STEP: Performing K8s service preflight check
22:06:33  22:06:33 STEP: Waiting for cilium-operator to be ready
22:06:33  22:06:33 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator")
22:06:33  22:06:33 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator") => <nil>
22:06:33  22:06:33 STEP: Cilium "1.7-dev" is installed and running
22:06:33  22:06:33 STEP: Restarting DNS Pods
22:06:41  22:06:41 STEP: Waiting for kube-dns to be ready
22:06:41  22:06:41 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=kube-dns")
22:06:41  22:06:41 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=kube-dns") => <nil>
22:06:41  22:06:41 STEP: Running kube-dns preflight check
22:06:43  22:06:42 STEP: Performing K8s service preflight check
22:06:43  22:06:42 STEP: Creating some endpoints and L7 policy
22:06:43  22:06:42 STEP: WaitforPods(namespace="default", filter="-l zgroup=testapp")
22:06:58  22:06:57 STEP: WaitforPods(namespace="default", filter="-l zgroup=testapp") => <nil>
22:07:04  22:07:04 STEP: Creating service and clients for migration
22:07:04  22:07:04 STEP: WaitforPods(namespace="default", filter="-l app=migrate-svc-server")
22:07:10  22:07:09 STEP: WaitforPods(namespace="default", filter="-l app=migrate-svc-server") => <nil>
22:07:10  22:07:09 STEP: WaitforPods(namespace="default", filter="-l app=migrate-svc-client")
22:07:15  22:07:14 STEP: WaitforPods(namespace="default", filter="-l app=migrate-svc-client") => <nil>
22:07:15  22:07:14 STEP: Validate that endpoints are ready before making any connection
22:07:16  22:07:15 STEP: Waiting for kube-dns to be ready
22:07:16  22:07:15 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=kube-dns")
22:07:16  22:07:15 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=kube-dns") => <nil>
22:07:16  22:07:15 STEP: Running kube-dns preflight check
22:07:16  22:07:16 STEP: Performing K8s service preflight check
22:07:17  22:07:17 STEP: Making L7 requests between endpoints
22:07:17  22:07:17 STEP: No interrupts in migrated svc flows
22:07:17  22:07:17 STEP: Install Cilium pre-flight check DaemonSet
22:07:21  22:07:21 STEP: Waiting for all cilium pre-flight pods to be ready
22:07:21  22:07:21 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-pre-flight-check")
22:07:37  22:07:36 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium-pre-flight-check") => <nil>
22:07:37  22:07:36 STEP: Removing Cilium pre-flight check DaemonSet
22:07:37  22:07:36 STEP: Waiting for Cilium to become ready
22:07:37  22:07:36 STEP: Number of ready Cilium pods: 2
22:07:37  22:07:36 STEP: Upgrading Cilium to 1.7.90
22:07:37  22:07:37 STEP: Validating pods have the right image version upgraded
22:07:53  22:07:52 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium")
22:08:33  22:08:32 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium") => <nil>
22:08:33  22:08:32 STEP: Checking that installed image is "latest"
22:08:33  22:08:32 STEP: Waiting for Cilium to become ready
22:08:33  22:08:32 STEP: Number of ready Cilium pods: 2
22:08:33  22:08:32 STEP: Validating Cilium Installation
22:08:33  22:08:32 STEP: Performing Cilium controllers preflight check
22:08:33  22:08:32 STEP: Performing Cilium health check
22:08:33  22:08:32 STEP: Performing Cilium status preflight check
22:08:34  22:08:34 STEP: Performing Cilium service preflight check
22:08:34  22:08:34 STEP: Performing K8s service preflight check
22:08:35  22:08:35 STEP: Waiting for cilium-operator to be ready
22:08:35  22:08:35 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator")
22:08:35  22:08:35 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator") => <nil>
22:08:35  22:08:35 STEP: Validate that endpoints are ready before making any connection
22:08:36  22:08:36 STEP: Waiting for kube-dns to be ready
22:08:36  22:08:36 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=kube-dns")
22:08:36  22:08:36 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=kube-dns") => <nil>
22:08:36  22:08:36 STEP: Running kube-dns preflight check
22:08:37  22:08:37 STEP: Performing K8s service preflight check
22:08:38  22:08:38 STEP: Making L7 requests between endpoints
22:08:38  22:08:38 STEP: No interrupts in migrated svc flows
22:08:38  22:08:38 STEP: Downgrading cilium to 1.7-dev image
22:08:54  22:08:53 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium")
22:09:42  22:09:39 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=cilium") => <nil>
22:09:42  22:09:39 STEP: Checking that installed image is "v1.7"
22:09:42  22:09:39 STEP: Waiting for cilium-operator to be ready
22:09:42  22:09:39 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator")
22:09:42  22:09:39 STEP: WaitforPods(namespace="kube-system", filter="-l name=cilium-operator") => <nil>
22:09:42  22:09:39 STEP: Validate that endpoints are ready before making any connection
22:09:42  22:09:40 STEP: Waiting for kube-dns to be ready
22:09:42  22:09:40 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=kube-dns")
22:09:42  22:09:40 STEP: WaitforPods(namespace="kube-system", filter="-l k8s-app=kube-dns") => <nil>
22:09:42  22:09:40 STEP: Running kube-dns preflight check
22:09:42  22:09:41 STEP: Performing K8s service preflight check
22:09:42  22:09:42 STEP: Making L7 requests between endpoints
22:09:42  22:09:42 STEP: No interrupts in migrated svc flows
22:09:42  === Test Finished at 2020-06-15T22:09:42Z====
22:09:42  22:09:42 STEP: Running JustAfterEach block for EntireTestsuite K8sUpdates
22:09:42  22:09:42 STEP: Running AfterEach for block EntireTestsuite K8sUpdates
22:10:01  22:10:01 STEP: Waiting for Cilium to become ready
22:10:01  22:10:01 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
22:10:06  22:10:06 STEP: Cilium DaemonSet not ready yet: only 0 of 2 desired pods are ready
22:10:11  22:10:11 STEP: Number of ready Cilium pods: 2
22:10:22  22:10:21 STEP: Running AfterEach for block EntireTestsuite
22:10:22  <Checks>
```

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
test-me-please

File: bpf/bpf_host.c (hunk 1 above)
Comment (borkmann) [reply bpf/bpf_host.c:1257]: Took 26a39a8 back in, the 4.19 tests in CI were still 9 insns over the limit in some cases. With 26a39a8 we can also bump the NAT collision retries again which is great. I left the CILIUM_CALLS_ definitions as-is. It's not ABI of some sort so we can change it anytime, but I think we need some more investigation on what we discussed wrt populating tail call map slots. I do agree that we have an issue here which needs reworking first. E.g. if we'd move both new CALL defs at the end and leave a 'gap' in the middle, then this might not be cleaned up, if we move both into the middle, then this might be disruptive wrt datapath upgrades.

File: Documentation/spelling_wordlist.txt [hunk 2]
```diff
@@ -351,6 +352,7 @@ hashtables
 herokuapp
 hexData
 hoc
+homogenous
```
Comment (pchaigno) [inline Documentation/spelling_wordlist.txt]:
```suggestion
homogeneous
```

File: Documentation/gettingstarted/kubeproxy-free.rst [hunk 3]
```diff
@@ -344,9 +344,9 @@ NodePort XDP Acceleration
 Cilium has built-in support for accelerating NodePort, LoadBalancer services and
 services with externalIPs for the case where the arriving request needs to be
 pushed back out of the node when the backend is located on a remote node. This
-ability to act as a hairpin load balancer can be handled by Cilium at the XDP
```
Comment (pchaigno) [inline Documentation/gettingstarted/kubeproxy-free.rst:347]: Could you also change the following above if you're touching this file (I wasn't fast enough to submit my review yesterday)?
```diff
- (one per eth0 and eth1 devices)
+ (one for each of devices eth0 and eth1)
```

File: daemon/cmd/daemon_main.go [hunk 4]
```diff
@@ -1803,15 +1803,16 @@ func initKubeProxyReplacementOptions() {
...
 		}
 
-		option.Config.NodePortHairpin =
-			option.Config.NodePortAcceleration != option.NodePortAccelerationDisabled ||
-				len(option.Config.Devices) == 1
+		option.Config.NodePortHairpin = len(option.Config.Devices) == 1
+		if option.Config.NodePortAcceleration != option.NodePortAccelerationDisabled &&
+			len(option.Config.Devices) != 1 {
+			log.Fatalf("Cannot set NodePort acceleration due to multi-device setup (%q). Specify --%s with a single device to enable NodePort acceleration.", option.Config.Devices, option.Devices)
+		}
```
Comment (joestringer) [inline daemon/cmd/daemon_main.go]: @brb PTAL in context of the autodetection logic and how the devices list may be pre-populated here.

File: test/helpers/kubectl.go [hunk 5]
```diff
@@ -2142,14 +2142,6 @@ func (kub *Kubectl) overwriteHelmOptions(options map[string]string) error {
 		}
 	}
 
-	// Temporary workaround until https://github.com/cilium/cilium/pull/11915
-	// has been merged. Otherwise, the BPF verifier rejects some programs on
-	// the 4.19 kernel
-	if os.Getenv("KERNEL") == "419" {
-		options = addIfNotOverwritten(options, "global.kubeProxyReplacement", "partial")
-		options = addIfNotOverwritten(options, "global.hostServices.enabled", "true")
-	}
```
Comment (pchaigno) [inline test/helpers/kubectl.go:2151]: Could you also pull in 6b14badba830a4c335d3e65fbf596deb7a1d2bab, so that kube-proxy is disabled and the code below runs? That way, `kube-proxy-replacement` would be `strict` and the host firewall would be enabled.

File: Documentation/gettingstarted/kubeproxy-free.rst [hunk 6]
```diff
@@ -370,6 +370,14 @@ modes and can be enabled as follows for ``nodePort.mode=hybrid`` in this example
         --set global.k8sServiceHost=API_SERVER_IP \\
         --set global.k8sServicePort=API_SERVER_PORT
 
+In case of a multi-device environment, where Cilium's device auto-detection selects
+more than a single device to expose NodePort, for example, the helm option
+``global.devices={eth0}`` must be additionally specified for the enablement, where
+``eth0`` is the native XDP supported networking device. In that case, the device
+name ``eth0`` must be the same on all Cilium managed nodes. Similarly, the underlying
+driver for ``eth0`` must have native XDP support on all Cilium managed nodes. This
+is typically provided in homogenous cluster environments, for example.
```
Comment (joestringer) [inline Documentation/gettingstarted/kubeproxy-free.rst]: nit:

```suggestion
driver for ``eth0`` must have native XDP support on all Cilium managed nodes.
```

I don't think the final sentence here actually clarifies anything. A homogenous environment is defined by having the same configuration in all nodes :-)

**Review by joestringer — APPROVED** [review]
Couple of minor comments, otherwise LGTM.

**Comment by borkmann** [comment]
test-focus K8sService*

**Comment by borkmann** [comment]
test-me-please

File: test/helpers/kubectl.go (hunk 5 above)
Comment (borkmann) [reply test/helpers/kubectl.go:2151]: Yes, agree. One thing we need to think about next is that we won't have any kube-proxy based coverage aside from only 4.9 kernel in CI.

File: Documentation/gettingstarted/kubeproxy-free.rst (hunk 6 above)
Comment (borkmann) [reply Documentation/gettingstarted/kubeproxy-free.rst]: Agree, I'll take it out.

File: Documentation/gettingstarted/kubeproxy-free.rst (hunk 3 above)
Comment (borkmann) [reply Documentation/gettingstarted/kubeproxy-free.rst:347]: np, done.

**Comment by borkmann** [comment]
test-focus K8sService*

**Comment by borkmann** [comment]
test-me-please

File: test/helpers/kubectl.go (hunk 5 above)
Comment (pchaigno) [reply test/helpers/kubectl.go:2151]: Yep, we will even have some tests that won't run anywhere anymore. For example, https://github.com/cilium/cilium/blob/6beb6b3d5a48e552395bd62669d3b8ebcbb0c222/test/k8sT/DatapathConfiguration.go#L208-L214
I was planning to have a look at all tests once v1.8 is out to see if any need to be reenable in some way.

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
retest-4.19

**Comment by borkmann** [comment]
retest-4.9

File: test/helpers/kubectl.go (hunk 5 above)
Comment (borkmann) [reply test/helpers/kubectl.go:2151]: Agree, somehow it would be good to perhaps run 4.19 with one job in kube-proxy free and another with kube-proxy mode to be on safe side.

**Comment by borkmann** [comment]
(all green except 4 tests on 4.19 due to missing kernel features, run them only on net-next)

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
Rebasing given https://github.com/cilium/cilium/pull/12050 was merged earlier.

**Comment by borkmann** [comment]
test-me-please

**Comment by borkmann** [comment]
retest-4.9

**Comment by borkmann** [comment]
4.19 has a single test that is flaking (K8sDatapathConfig Etcd Check connectivity). Was green on prior test run.
