### PR TITLE
cilium: fix fd leak from ObjClose being omitted on ConfigMap

### LINKED ISSUE #6803: Accept error: accept unix /var/run/cilium/cilium.sock: accept4: too many open files
```
Jan 27 21:15:12 k8s1 cilium-agent[12422]: 2019/01/27 21:15:12 http: Accept error: accept unix /var/run/cilium/cilium.sock: accept4: too many open files; retrying in 1s
```

### PR DESCRIPTION
**Pull request by jrfastab**
Watching bpftool maps via 'bpftool show map' shows the ConfigMap is
not being removed when an endpoint is deleted. This results in the
number of active fd's growing until eventually fd space is exhausted.

This fix copies the policymap approach and similarly adds the Close
hook to ConfigMap and calls it from LeaveLocked()

Fixes: #6803

Signed-off-by: John Fastabend <john.fastabend@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/6890)

### CODE REVIEW

**Comment by jrfastab** [comment]
test-me-please

**Comment by ianvernon** [comment]
@jrfastab can you put a `Fixes:` along with the commit message that is associated with this fix in the commit message? That way we can determine where this needs backporting to. I suspect v1.3 and v1.4.

File: pkg/maps/configmap/configmap.go [hunk 1]
```diff
@@ -161,6 +163,32 @@ func (m *EndpointConfigMap) Update(value *EndpointConfig) error {
 	return m.Map.Update(configKey, value)
 }
 
+// Close closes the FD of the given CofigMap. Returns an error if the close
```
Comment (joestringer) [inline pkg/maps/configmap/configmap.go]: This shouldn't be necessary; the generic Map close here should take care of this in the right way:

https://github.com/cilium/cilium/blob/0c1dbad17c2ddb13697d889787b8f0bac3f2fc0f/pkg/bpf/map_linux.go#L362-L378

Maybe it's the fact that the Map is not embedded directly into `EndpointConfigMap`? Ie, these lines:

https://github.com/cilium/cilium/blob/0c1dbad17c2ddb13697d889787b8f0bac3f2fc0f/pkg/maps/configmap/configmap.go#L137-L141

Should have the 

```
	Map  *bpf.Map
```

become 
```
	*bpf.Map
```

File: pkg/endpoint/endpoint.go [hunk 2]
```diff
@@ -272,7 +272,7 @@ type Endpoint struct {
 	realizedRedirects map[string]uint16
 
 	// BPFConfigMap provides access to the endpoint's BPF configuration.
-	bpfConfigMap *bpfconfig.EndpointConfigMap
+	ConfigMap *bpfconfig.EndpointConfigMap
```
Comment (joestringer) [inline pkg/endpoint/endpoint.go]: Renaming to have the first character as a capital letter affects how this field is exposed, including serializing to the filesystem for restore. I don't think we want to do that.

I'm fine with the shorter name, but it should start with a lower case letter (and it's a refactor/cleanup, so not really appropriate for backport to e.g. v1.3 which this bug appears to affect)

File: pkg/endpoint/endpoint.go [hunk 3]
```diff
@@ -1447,6 +1447,12 @@ func (e *Endpoint) LeaveLocked(owner Owner, proxyWaitGroup *completion.WaitGroup
 		}
 	}
 
+	if e.ConfigMap != nil {
+		if err := e.ConfigMap.Close(); err != nil {
+			errors = append(errors, fmt.Errorf("unable to close configmap %s: %s", e.BPFConfigMapPath(), err))
+		}
+	}
+
```
Comment (joestringer) [inline pkg/endpoint/endpoint.go:1455]: I think this hunk is the only part that's strictly necessary for the fix?

**Review by joestringer — CHANGES_REQUESTED** [review]
Good find, thanks. A couple of comments on code reuse and public exposure of fields. Also I think this affects v1.3.

File: pkg/endpoint/endpoint.go (hunk 2 above)
Comment (aanm) [inline pkg/endpoint/endpoint.go]: I'm ok with the rename but keep the field private or it will be stored and read on endpoint restore.

**Review by aanm — CHANGES_REQUESTED** [review]

File: pkg/endpoint/endpoint.go (hunk 2 above)
Comment (jrfastab) [reply pkg/endpoint/endpoint.go]: Lets do minimal changes seeing we have to backport this. Will revert name change and dup Close() hook.

**Comment by jrfastab** [comment]
test-me-please

**Review by joestringer — APPROVED** [review]
LGTM, thanks!

File: pkg/maps/configmap/configmap.go [hunk 4]
```diff
@@ -135,7 +135,7 @@ type endpoint interface {
 
 // EndpointConfigMap is a map type for interfacing with endpoint BPF config.
 type EndpointConfigMap struct {
-	Map  *bpf.Map
+	*bpf.Map
```
Comment (aanm) [inline pkg/maps/configmap/configmap.go:138]: Leave the `Map` because this way you will be able to know if `Map` is nil or not and don't get a nil pointer when doing the close on line 1451 from the other file.

**Review by aanm — CHANGES_REQUESTED** [review]

File: pkg/maps/configmap/configmap.go (hunk 4 above)
Comment (joestringer) [reply pkg/maps/configmap/configmap.go:138]: I think this is necessary to compose the `Map` and get the generic `bpf.Map.Close()` function access? What do you mean by "Leave the `Map`"?

The `Map` field inside `EndpointConfigMap` should always be non-nil (it's initialised in `OpenMapWithName()`, and the reference in the `Endpoint` refers to a `*EndpointConfigMap`, which may or may not be nil but the check in the other file should be fine in that regard.

Comment (aanm) [reply pkg/maps/configmap/configmap.go:138]: >What do you mean by "Leave the Map"?

Leave the `Map` attribute as it was before this change.

>The Map field inside EndpointConfigMap should always be non-nil (it's initialised in OpenMapWithName(), and the reference in the Endpoint refers to a *EndpointConfigMap, which may or may not be nil but the check in the other file should be fine in that regard.

That is true but there's also a problem if we later on add the "Close()" method to `EndpointConfigMap` which will overwrite all usages of `bpf.Map.Close()` without us knowing

**Review by aanm — CHANGES_REQUESTED** [review]

File: pkg/maps/configmap/configmap.go (hunk 4 above)
Comment (joestringer) [reply pkg/maps/configmap/configmap.go:138]: *shrug That's how Golang works. If someone introduces another implementation then they need to know this and call the composed map function. It's more boilerplate that's more explicit if we define a `Close()`, which helps non-Go programmers to contribute I guess. So long as the core implementation is shared I don't mind.

Comment (tgraf) [reply pkg/maps/configmap/configmap.go:138]: I'm fine with this as-is as well.

**Review by tgraf — APPROVED** [review]
