### PR TITLE
fix: Assign PodStore from Pod resource until cell migration is completed

### LINKED ISSUE #32713: operator: pod store is never initialized
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Each time a node needs more IP, the operator will log a warning indicating that the pod store is not initialized.
As a result the surge allocation is skipped and the operator will not allocate more than the pre-allocate value for the node (defaults to 8).

### Cilium Version

1.15.0

### Kernel Version

Linux xxx 5.10.215-203.850.amzn2.x86_64 #1 SMP Tue Apr 23 20:32:19 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

v1.28.8-eks-adc7111

### Regression

https://github.com/cilium/cilium/commit/1a9a1e7b2a7bebdf4a87200c994af91b58dba097#diff-feb41af31e6ee7149118809ccc6fe42b0603dbb5e8f9c16a72bc2fe492c0b921L56-L61

### Sysdump

_No response_

### Relevant log output

```shell
level=warning msg="Unable to compute pending pods, will not surge-allocate" error="pod store uninitialized" instanceID=i-xxx name=xxx subsys=ipam
level=info msg="Resolving IP deficit of node" available=16 availableForAllocation=208 emptyInterfaceSlots=3 instanceID=i-xxx maxIPsToAllocate=1 name=xxx neededIPs=1 remainingInterfaces=4 selectedInterface=eni-xxx selectedPoolID=subnet-xxx subsys=ipam used=9
```

### Anything else?

The pod store in `operator/watchers/pod.go` is created by the function `PodsInit` which is never called anywhere in the code.

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dlapcevic**
Fixes: https://github.com/cilium/cilium/issues/32713

Changes:
1. PodStore from Pod resource is assigned to PodStore of cilium-operator on startup.
2. `PodNodeNameIndex` is added to the Pod watcher in `operatorK8s.PodResource`.

This will be refactored once `ciliumNodeSynchronizer` is migrated to a cell.

Signed-off-by: Dorde Lapcevic <[dordel@google.com](mailto:dordel@google.com)>
```release-note
Fixed bug which prevented IP surge allocation from working
```

### CODE REVIEW

File: operator/cmd/root.go [hunk 1]
```diff
@@ -650,6 +650,15 @@ func (legacy *legacyOnLeader) onStart(_ cell.HookContext) error {
 	ciliumNodeSynchronizer := newCiliumNodeSynchronizer(legacy.clientset, nodeManager, withKVStore)
 
 	if legacy.clientset.IsEnabled() {
+		// ciliumNodeSynchronizer uses operatorWatchers.PodStore for IPAM surge
+		// allocation. Initializing PodStore from Pod resource is temporary until
+		// ciliumNodeSynchronizer is migrated to a cell.
+		podStore, err := legacy.resources.Pods.Store(legacy.ctx)
+		if err != nil {
+			log.WithError(err).Fatal("Get pod store")
```
Comment (tommyp1ckles) [inline operator/cmd/root.go]: Do we know why this might return a non nil error? If perhaps we should make the fatal log message more descriptive as to possible reasons for the termination.

**Review by tommyp1ckles — CHANGES_REQUESTED** [review]

File: operator/cmd/root.go (hunk 1 above)
Comment (dlapcevic) [reply operator/cmd/root.go]: This is the description of the .Store method:
Store retrieves the read-only store for the resource. Blocks until the store has been synchronized or the context cancelled. Returns a non-nil error if context is cancelled or the resource has been stopped before store has synchronized.

It will only fail if the context is canceled or resource are stopped.
I made the message more descriptive.

**Review by joamaki — APPROVED** [review]

**Comment by dlapcevic** [comment]
Hi @tommyp1ckles, could we please merge this?

**Comment by dlapcevic** [comment]
Hi @joamaki, could we please merge this?

File: operator/watchers/pod.go [hunk 2]
```diff
@@ -42,19 +41,13 @@ var (
...
-	if pod.Spec.NodeName != "" {
-		return []string{pod.Spec.NodeName}, nil
-	}
-	return []string{}, nil
-}
-
+// PodsInit and PodStore will be deprecated with other watchers, once all of
+// their uses move to hive/cell model that uses k8s resources instead of
+// separately initializing informers.
 func PodsInit(ctx context.Context, wg *sync.WaitGroup, clientset k8sClient.Clientset) {
```
Comment (tommyp1ckles) [inline operator/watchers/pod.go:47]: I think PodsInit is unused, we could just remove it.

**Review by tommyp1ckles — APPROVED** [review]
Sorry for the delay, changes look good to me, thanks for the fix 😄

File: operator/watchers/pod.go (hunk 2 above)
Comment (dlapcevic) [reply operator/watchers/pod.go:47]: Sounds good. I'll do it as a follow up.

**Comment by christarazi** [comment]
@dlapcevic Does this need to be backported to v1.16?

**Comment by dlapcevic** [comment]
> @dlapcevic Does this need to be backported to v1.16?

Yes. It was reported in v1.15, so it should be backported there too. https://github.com/cilium/cilium/issues/32713

**Comment by jaredledvina** [comment]
👋 Could this be included with the `needs-backport/1.15` label? 
@thorn3r I see you have https://github.com/cilium/release/issues/267 (or @christarazi) would either of you have permission to do that? 
It'd be a shame for folks upgrading to 1.15 to pick up https://github.com/cilium/cilium/issues/32713 and lose the surge allocate functionality.

**Comment by christarazi** [comment]
@jaredledvina It's not obvious to me how difficult the backport would be to v1.15 given the scope of changes to the code base since then compared to today. Going off of https://docs.cilium.io/en/v1.15/contributing/release/backports/#id1, I'm not sure if this would be considered a major bug. Otherwise, we'd recommend upgrading to the latest OSS version (v1.16).

**Comment by jaredledvina** [comment]
Ah okay, we're trying to upgrade to 1.15 currently. There's concern that we might be losing Surge Allocation because of this bug. 1.16 will be a ways off until we can finish getting to 1.15 so if a backport is doable that'd be much appreciated.

**Comment by antonipp** [comment]
I actually went ahead and did the PR for the 1.15 backport: https://github.com/cilium/cilium/pull/35419
We will be running 1.15 for a while and we'd rather not lose the surge allocation feature which is useful in our busier clusters.

**Comment by pchaigno** [comment]
I'm a bit confused because this pull request is labeled as `release-note/misc`, but is being backported. The label suggests that there is no user impact (otherwise it would be `release-note/bug`), but the backporting suggests it does fix a bug. Is the label incorrect? If so, could we fix it and add a release note in the PR description?
