### PR TITLE
enforce CT clean up from L3 to L7 policy changes on ingress

### LINKED ISSUE #1916: Ginkgo CI: Migrate tests/21-ct-clean-up.sh
Parent issue #1841

### LINKED ISSUE #2408: Ingress still allowed after deleting policy that allowed it
### Ingress still allowed after deleting policy that allowed it

When having multiple policies to allow ingress, if you delete a policy that had allowed ingress from pod A to pod B, pod A can still communicate with pod B. 

### General Information

- Cilium version: Cilium 0.13.90 56906ce Thu, 21 Dec 2017 21:51:13 +0100 go version go1.9 linux/amd64
- Kernel version: 4.11.11-coreos
- Orchestration system version:
`Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7+coreos.0", GitCommit:"c8c505ee26ac3ab4d1dff506c46bc5538bc66733", GitTreeState:"clean", BuildDate:"2017-07-06T17:38:33Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}`

### How to reproduce the issue

1. Set policy enforcement ingress to always
2. Create two pods with different app names
3. Verify that pod A can't communicate with pod B
4. Create a policy that allows ingress to pod B from pod A
5. Test communication to verify it works. 
6. Delete the policy that allows ingress. 
7. Try communication from pod A to pod B. Communication works and continues to work when it shouldn't.

If you create a new pod from either one, and attempt communication, it will not work. It is only the two pods, where communication occurred before, that will work.

### LINKED ISSUE #2569: Connection tracking is cleared when policy is deleted when endpoint ends up in default allow
When an endpoint is subject to policy and all policy of that endpoint is then cleared, the current behaviour removes all connections from the connection tracking tables. This is incorrect if the policy enforcement is set to default which will result the endpoint in turning into a "policy disabled" state and effectively all existing connections should have prevailed.

### PR DESCRIPTION
**Pull request by aanm**
**Note for reviewers**: 

There are some questions around the code with the tag REVIEWER or FIXME, I would like opinions on those 

Please read and try to understand the ginkgo tests first without looking at the code, if there are any questions about the logic behind the CT cleanup they should come first from looking at the tests logic, for example: "why this test gets this result?", by looking at the tests first I believe it will be easier to review the code.

These changes are for **ingress** policies only. **egress** needs to be addressed in the future

**Summary of changes**:

 - Clean up CT entries when removing a L3-only policy, if the policy no
   longer allows it;
 - Modify the CT entries when a L7 policy is loaded so the traffic will
   immediatlly go to the L7 proxy. By sending the traffic directly to
   the proxy instead of deleting it, like the old behavior, the proxy
   will send a RST to the client, forcing the client to restart the TCP
   connection and sending the traffic to the proxy;
 - Do the CT clean up only after the BPF program is regenerated to avoid
   loopholes in the CT. First security enforcement by BPF then cleanup.
 - Allow connections to continue to exist in the CT when running with
   policy enforcement mode "Default" and a policy that was selecting an
   endpoint be removed.
 - Add ginkgo tests 

Fixes #1916, Fixes #2569, Fixes #2408. Might also fi-x  #2053

```release-note
Enforce policy update immediately on ongoing connections #2569 #2408
```

### CODE REVIEW

**Comment by aanm** [comment]
test-all-ginkgo

File: test/runtime/ct.go [hunk 1]
```diff
@@ -128,254 +145,411 @@ var _ = Describe("RuntimeConntrackTable", func() {
...
+			dstIP := testCase.destination[testCase.kind]
+			dstPort := testCase.dstPort
+			srcIP := testCase.src[testCase.kind]
+			srcSecID := epIdentities[testCase.src[helpers.Name]]
+
+			data, err := countCTINEntriesOf(dstIP, dstPort, srcIP, srcSecID)
+			Expect(err).To(BeNil(), "Trying to count CT entries of %s and %s", dstIP, srcIP)
+
+			wantCTEntries := 0
+			if dstIP != meta[server2][testCase.kind] {
```
Comment (ianvernon) [inline test/runtime/ct.go:398]: Can you add a comment explaining why this check is made?

**Comment by joestringer** [comment]
> Do the CT clean up only after the BPF program is regenerated to avoid
loopholes in the CT. First security enforcement by BPF then cleanup.

File: test/runtime/ct.go [hunk 2]
```diff
@@ -128,254 +145,411 @@ var _ = Describe("RuntimeConntrackTable", func() {
...
 		testCombinations := []connTest{
-			{meta[client], meta[server3], helpers.IPv6, HTTPPrivate},
-			{meta[client], meta[server3], helpers.IPv4, HTTPPrivate},
-			{meta[client], meta[server3], helpers.IPv6, HTTPPublic},
-			{meta[client], meta[server3], helpers.IPv4, HTTPPublic},
-			{meta[client], meta[server3], helpers.IPv6, netcatPrivate},
-			{meta[client], meta[server3], helpers.IPv4, netcatPrivate},
-			{meta[client], meta[server3], helpers.IPv6, netcatPublic},
-			{meta[client], meta[server3], helpers.IPv4, netcatPublic},
+			{meta[client], meta[server3], "80", helpers.IPv6, HTTPPrivate},
```
Comment (ianvernon) [inline test/runtime/ct.go]: Use a variable instead of hardcoding.

File: test/runtime/ct.go [hunk 3]
```diff
@@ -385,113 +559,244 @@ var _ = Describe("RuntimeConntrackTable", func() {
...
+		netcatPort = 11112
+		testReach(client, meta[server3][helpers.IPv4], "80", netcatPrivate, BeTrue)
+		testReach(client, meta[server3][helpers.IPv6], "80", netcatPrivate, BeTrue)
+		netcatPort = 11111
+
+		epIdentities, err := vm.GetEndpointsIdentityIds()
+		Expect(err).To(BeNil(), "Getting endpoint identities")
 
-		_, err = vm.PolicyRenderAndImport(policyL7)
+		By("Checking if CT entries from server-3 to client is the number of connections make")
```
Comment (ianvernon) [inline test/runtime/ct.go]: make --> made

File: test/runtime/ct.go [hunk 4]
```diff
@@ -385,113 +559,244 @@ var _ = Describe("RuntimeConntrackTable", func() {
...
+		data, err := countCTINEntriesOf(meta[server3][helpers.IPv6], "80", meta[client][helpers.IPv6], epIdentities[client])
```
Comment (ianvernon) [inline test/runtime/ct.go]: Avoid hardcoding the port.

File: tests/21-ct-clean-up.sh [hunk 5]
```diff
@@ -41,7 +41,7 @@ function start_containers {
 }
 
 function get_container_metadata {
-  CLIENT_SEC_ID=$(cilium endpoint list | grep id.client-2 | awk '{ print $4}')
+  CLIENT_SEC_ID=$(cilium endpoint list | grep id.client | awk 'NR==1{ print $4}')
```
Comment (ianvernon) [inline tests/21-ct-clean-up.sh:47]: Does this test now have parity with the according Ginkgo test? If so, we can just deprecate this one.

File: pkg/endpoint/bpf.go [hunk 6]
```diff
@@ -602,20 +642,35 @@ func (e *Endpoint) regenerateBPF(owner Owner, epdir, reason string) (uint64, err
...
-		// The last operation hooks the endpoint into the endpoint table and exposes it
-		err = lxcmap.WriteEndpoint(epInfoCache)
-		if err != nil {
-			log.WithField(logfields.EndpointID, e.ID).WithError(err).Error("Exposing new bpf failed!")
-		}
+	if err != nil {
+		return epInfoCache.revision, err
+	}
+	// REVIEW: should the CT entry clean up also happen
+	// even if the bpf program build has failed? I think we should.
```
Comment (joestringer) [inline pkg/endpoint/bpf.go]: Defaulting to lock-down seems like the safer option. It should be logged though too, so it's easy to tell from the logs that this weird condition was hit and that's why your traffic is being dropped.

File: pkg/endpoint/bpf.go [hunk 7]
```diff
@@ -542,26 +545,63 @@ func (e *Endpoint) regenerateBPF(owner Owner, epdir, reason string) (uint64, err
...
+		// the consumersAdd be nil. If this happens it means
+		// the L4-L7 was changed so we need to update the
+		// L3L4Policy map with the new proxyport.
+		if policyChanged &&
+			consumersAdd == nil &&
+			c.L4Policy != nil &&
+			c.L4Policy.Ingress != nil &&
+			c.L3L4Policy != nil {
+
+			// Only update CT if the new a RedirectPort was changed.
```
Comment (joestringer) [inline pkg/endpoint/bpf.go]: Perhaps, "Only update CT if the RedirectPort was changed"? ("the a" doesn't make sense).

**Comment by aanm** [comment]
test-all-ginkgo

File: pkg/endpoint/policy.go [hunk 8]
```diff
@@ -176,10 +174,11 @@ func (e *Endpoint) removeOldFilter(owner Owner, labelsMap *LabelsMap,
 // it maps to whether they were added successfully (true or false).
 // It also returns the number of errors that occurred while when applying the
 // policy.
+// Applies for L4 dependent L3 not for L4-only.
```
Comment (joestringer) [inline pkg/endpoint/policy.go]: "L3 dependent L4" ?

File: pkg/endpoint/policy.go [hunk 9]
```diff
@@ -328,20 +332,26 @@ func (e *Endpoint) resolveL4Policy(owner Owner, repo *policy.Repository, c *poli
 }
 
 // Must be called with global endpoint.Mutex held
+// Returns a boolean to signalize if the policy was changed;
+// and a map matching which rules were successfully added;
+// and a map matching which rules were successfully removed.
```
Comment (joestringer) [inline pkg/endpoint/policy.go]: Minor thing, but named return values would clarify what this comment tries to convey.

File: pkg/endpointmanager/conntrack.go [hunk 10]
```diff
@@ -31,6 +31,7 @@ import (
 
 const (
 	// GcInterval is the garbage collection interval.
+	// #FIXME find a way to change this value
```
Comment (joestringer) [inline pkg/endpointmanager/conntrack.go]: What doesn't work as expected if you just change it?

File: pkg/endpoint/bpf.go (hunk 7 above)
Comment (manalibhutiyani) [inline pkg/endpoint/bpf.go]: Nit: Change `Only update CT if the new a RedirectPort was changed.` to `Only update CT if the new RedirectPort was changed.`

File: pkg/maps/ctmap/ctmap.go [hunk 11]
```diff
@@ -410,10 +336,110 @@ func doGC4(m *bpf.Map, filter *GCFilter) int {
...
+
+		action = deleteEntry
+	}
+
+	// Delete all entries of the given dstIP that are not filtered
+	if f.Type&GCFilterByIDsToKeep != 0 &&
+		dstIP.Equal(f.IP) &&
+		// only delete TUPLE_F_IN connections since the clean up is made
+		// for ingress policies
+		// #### REVIEWER: what about TUPLE_F_RELATED?
```
Comment (joestringer) [inline pkg/maps/ctmap/ctmap.go]: Seems like `TUPLE_F_RELATED` is added to the existing flags in the tuple, so it should still be covered by `flags&<DIR>`:

https://github.com/cilium/cilium/blob/b168eec23ecb5e5fb0fcdbc28ec08f7e67e85761/bpf/lib/conntrack.h#L636-L648

**Comment by eloycoto** [comment]
Hi Andre, 

Quick one, could we delete the bash test and mark ginkgo test as validated?

Regards

**Comment by manalibhutiyani** [comment]
@eloycoto @ianvernon Wasn't the plan to keep the bash scripts around for some time, before complete migration to Ginkgo?

File: pkg/maps/ctmap/ctmap.go [hunk 12]
```diff
@@ -410,10 +336,110 @@ func doGC4(m *bpf.Map, filter *GCFilter) int {
...
+			} else {
+				// If the rule is not L3-only then check if it's allowed by
+				// L3-L4 rules.
+				if l7Rule, ok := filterRuleCtx[l4RuleCtx]; ok {
+					if l7Rule.L4Installed && entry.proxy_port != l7Rule.RedirectPort {
+						action = modifyEntry
+						entry.proxy_port = l7Rule.RedirectPort
+					}
+				} else {
+					action = deleteEntry
```
Comment (joestringer) [inline pkg/maps/ctmap/ctmap.go]: What does this case represent? L4-Only?

File: pkg/endpoint/policy.go [hunk 13]
```diff
@@ -353,15 +363,71 @@ func (e *Endpoint) regenerateConsumable(owner Owner, labelsMap *LabelsMap,
...
-				e.getLogger().Fatal("L4 Policy application failed")
+				e.getLogger().WithError(err).Fatal("L4 Policy application failed")
 			}
 		}
-		e.L4Policy = c.L4Policy // Reuse the common policy
+		// Reuse the common policy, will be used in lxc_config.h (CFG_L4_INGRESS and CFG_L4_EGRESS)
+		e.L4Policy = c.L4Policy
 		e.LabelsMap = labelsMap // Remember the set of labels used
+
+		// We need to know which ones are L4-only by checking
```
Comment (joestringer) [inline pkg/endpoint/policy.go]: "ones" -> "rules" / "policies" ?

File: pkg/maps/ctmap/ctmap.go [hunk 14]
```diff
@@ -248,58 +252,20 @@ func doGC6(m *bpf.Map, filter *GCFilter) int {
...
-
-			ruleCtx := policy.RuleContext{
-				SecID:          policy.NumericIdentity(entry.src_sec_id),
-				Port:           nextKey.sport,
-				Proto:          uint8(nextKey.nexthdr),
-				L7RedirectPort: entry.proxy_port,
-				IsRedirect:     entry.proxy_port != 0,
-			}
+		// In CT's entries, `saddr` is the packet's receiver,
+		// which means, is the destination's IP.
```
Comment (joestringer) [inline pkg/maps/ctmap/ctmap.go]: (I appreciate that this comment was there before, but while we're modifying this code...)

If I do some minor rephrasing of the above comment, it seems equivalent to:

```
In CT entries, the source address of the conntrack entry is the place that the packet is received, therefore it's the destination IP
```

However, that doesn't make sense to me. Is there some way we can better explain this?

File: test/runtime/ct.go [hunk 15]
```diff
@@ -115,7 +104,35 @@ var _ = Describe("RuntimeConntrackTable", func() {
...
+		vm = helpers.CreateNewRuntimeHelper(helpers.Runtime, logger)
+		err := vm.WaitUntilReady(100)
+		Expect(err).To(BeNil())
+		vm.NetworkCreate(helpers.CiliumDockerNetwork, "")
+	}
+
+	BeforeEach(func() {
+		once.Do(initialize)
+
+		res := vm.SetPolicyEnforcement(helpers.PolicyEnforcementAlways)
```
Comment (manalibhutiyani) [inline test/runtime/ct.go:119]: Why do we set policy to `always` before each test and `default` after each test? I think we are not testing scenarios with policy `default` at all this way?

File: test/runtime/ct.go [hunk 16]
```diff
@@ -128,254 +145,411 @@ var _ = Describe("RuntimeConntrackTable", func() {
...
+			Expect(err).To(BeNil(), "Trying to count CT entries of %s and %s", dstIP, srcIP)
+
+			wantCTEntries := 0
+			if dstIP != meta[server2][testCase.kind] {
+				wantCTEntries = 1
+			}
+
+			des := fmt.Sprintf("Checking CT entries between %s and %s", dstIP, srcIP)
+			Expect(data).To(BeNumerically(comparator, wantCTEntries), des)
+		}
```
Comment (manalibhutiyani) [inline test/runtime/ct.go:296]: Should we also try to test connectivity at this point after deleting the policy? This just checks the count of CT entries. Ideally if the policy is `always` there should be no connectivity, while if the enforcement is `default` there should be connectivity.

File: pkg/endpoint/bpf.go [hunk 17]
```diff
@@ -542,26 +545,63 @@ func (e *Endpoint) regenerateBPF(owner Owner, epdir, reason string) (uint64, err
...
-		_, flushEndpointCT, consumersAdd, consumersToRm, err = e.regeneratePolicy(owner, nil)
+		policyChanged, consumersAdd, consumersRm, err = e.regeneratePolicy(owner, nil)
 		if err != nil {
 			e.Mutex.Unlock()
-			err = fmt.Errorf("Unable to regenerate policy for '%s': %s",
-				e.PolicyMap.String(), err)
-			return 0, err
+			return 0, fmt.Errorf("Unable to regenerate policy for '%s': %s", e.PolicyMap.String(), err)
+		}
+		// policyChanged can still be true and, at the same time,
```
Comment (manalibhutiyani) [inline pkg/endpoint/bpf.go:568]: Is it possible to only have L4 rules i.e no L7 rules or L3 rules, in which case, there will be no proxy redirect port to forward to. Will that scenario be handled correctly here?

File: pkg/endpoint/bpf.go [hunk 18]
```diff
@@ -542,26 +545,63 @@ func (e *Endpoint) regenerateBPF(owner Owner, epdir, reason string) (uint64, err
...
+		// the L4-L7 was changed so we need to update the
+		// L3L4Policy map with the new proxyport.
+		if policyChanged &&
+			consumersAdd == nil &&
+			c.L4Policy != nil &&
+			c.L4Policy.Ingress != nil &&
+			c.L3L4Policy != nil {
+
+			// Only update CT if the new a RedirectPort was changed.
+			policyChanged = false
```
Comment (manalibhutiyani) [inline pkg/endpoint/bpf.go]: Do we need some sort of locking for `policyChanged` writes/reads? Can there be concurrent access?

File: pkg/endpoint/bpf.go [hunk 19]
```diff
@@ -602,20 +642,35 @@ func (e *Endpoint) regenerateBPF(owner Owner, epdir, reason string) (uint64, err
...
-	if err == nil {
-		// The last operation hooks the endpoint into the endpoint table and exposes it
-		err = lxcmap.WriteEndpoint(epInfoCache)
-		if err != nil {
-			log.WithField(logfields.EndpointID, e.ID).WithError(err).Error("Exposing new bpf failed!")
-		}
+	if err != nil {
+		return epInfoCache.revision, err
+	}
+	// REVIEW: should the CT entry clean up also happen
```
Comment (manalibhutiyani) [inline pkg/endpoint/bpf.go]: Seems legit to me. Also depends on whether the policy enforcement is `default` or `always` or `never`. But I think `polciyChanged` already takes that into account?

**Review by manalibhutiyani — COMMENTED** [review]
Did a first pass. Will continue reviewing tomo. Overall awesome work @aanm !

**Comment by eloycoto** [comment]
Hi @manalibhutiyani no, from early this year we're deprecating the bash test ;-)

File: test/runtime/ct.go [hunk 20]
```diff
@@ -115,7 +104,35 @@ var _ = Describe("RuntimeConntrackTable", func() {
...
+
+		res = vm.PolicyDelAll()
+		res.ExpectSuccess("Deleting all policies")
+
+		containers(helpers.Create)
+	})
+
+	AfterEach(func() {
+		vm.PolicyDelAll()
+		netcatPort = 11111
```
Comment (raybejjani) [inline test/runtime/ct.go:130]: Maybe use a local copy in the places we change this to avoid this fixup? It might also be useful to add a check in beforeEach that panics in case we run two tests at the same time and the tests are "flaky".

File: test/runtime/ct.go [hunk 21]
```diff
@@ -29,16 +29,19 @@ import (
...
-var (
+const (
 	serverImage = "httpd"
 	ctCleanUpNC = "ct-clean-up-nc.py"
-	ctL4Policy  = "CT-l4-policy.json"
-	netcat      = "netcat"
+
+	// Change to "<=" if the pkg/endpointmanager/conntrack.go:GcInterval is 10
+	// Change to "==" if it is set to a large number
+	comparator = "<="
```
Comment (raybejjani) [inline test/runtime/ct.go:38]: More explanation why this is might help overall. We could also check GcInterval and set this value by using a little function (not pretty, though)
```golang
	func() string {
		if GcInterval == 10 {
			return "<="
		}
		return "=="
	}()
```

File: pkg/endpoint/bpf.go [hunk 22]
```diff
@@ -375,25 +375,28 @@ func (ep *epInfoCache) GetBPFValue() (*lxcmap.EndpointInfo, error) {
...
-	wg := &sync.WaitGroup{}
-
-	isLocal := e.Opts.IsEnabled(OptionConntrackLocal)
-	ip4 := e.IPv4.IP()
-	ip6 := e.IPv6.IP()
+// updateCT updates the Connection Tracking based on the endpoint's policy
+// enforcement. If the policy enforcement is true, all CT entries will be
+// removed except the ones matched by idsToKeep. If the policy enforcement
+// is not being enforced then all CT entries that match idsToMod will be
+// modified.
```
Comment (raybejjani) [inline pkg/endpoint/bpf.go]: Could you say how they're being modified? it isn't clear to me why policy-enforcement==false would only modify them (in the sense that if the enforcement is off we either skip the bpf completely or we simply create a CT entry for each connection with no policy check)

File: pkg/policy/consumer.go [hunk 23]
```diff
@@ -63,8 +63,9 @@ type Consumable struct {
 	// ReverseRules contains the consumers that are allowed to receive a reply from this Consumable
 	ReverseRules map[NumericIdentity]*Consumer `json:"-"`
 	// L4Policy contains the policy of this consumable
-	L4Policy *L4Policy `json:"l4-policy"`
-	cache    *ConsumableCache
+	L4Policy   *L4Policy           `json:"l4-policy"`
+	L3L4Policy *SecurityIDContexts `json:"l3-l4-policy"`
```
Comment (raybejjani) [inline pkg/policy/consumer.go]: Could this be a not-pointer? I'm guessing you followed the style of L4Policy, right?

**Comment by ianvernon** [comment]
Still reviewing, but had an idea - I think it would be really helpful if we had some sort of table / state-machine illustrating what types of policy changes can happen (i.e., L3-L4 dependent policy --> L7 policy) and make sure that all possible transitions are documented. It would be a useful resource for development in the future. What do you think?

File: daemon/daemon.go [hunk 24]
```diff
@@ -253,21 +253,21 @@ func (d *Daemon) DebugEnabled() bool {
 	return d.conf.Opts.IsEnabled(endpoint.OptionDebug)
 }
 
-// CleanCTEntries cleans the connection tracking of the given endpoint
+// ModifyCTEntries cleans the connection tracking of the given endpoint
 // where the given endpoint IPs' and the idsToRm match the CT entry fields.
```
Comment (ianvernon) [inline daemon/daemon.go]: remove the apostrophe here.

File: daemon/daemon.go [hunk 25]
```diff
@@ -253,21 +253,21 @@ func (d *Daemon) DebugEnabled() bool {
...
 // isCTLocal should bet set as true if the endpoint's CT table is either
```
Comment (ianvernon) [inline daemon/daemon.go]: should bet --> should be

File: daemon/daemon.go [hunk 26]
```diff
@@ -253,21 +253,21 @@ func (d *Daemon) DebugEnabled() bool {
...
 // local or not (if is not local then is assumed to be global).
```
Comment (ianvernon) [inline daemon/daemon.go]: if it is not local, then it is...

File: daemon/daemon.go [hunk 27]
```diff
@@ -253,21 +253,21 @@ func (d *Daemon) DebugEnabled() bool {
 	return d.conf.Opts.IsEnabled(endpoint.OptionDebug)
 }
 
-// CleanCTEntries cleans the connection tracking of the given endpoint
+// ModifyCTEntries cleans the connection tracking of the given endpoint
```
Comment (ianvernon) [inline daemon/daemon.go]: What defines "Modify" as opposed to "Clean" here? Should the verb 'cleans' be changed accordingly?

File: daemon/daemon.go [hunk 28]
```diff
@@ -253,21 +253,21 @@ func (d *Daemon) DebugEnabled() bool {
...
 // local or not (if is not local then is assumed to be global).
 // Implementation of pkg/endpoint.Owner interface
-func (d *Daemon) CleanCTEntries(e *endpoint.Endpoint, isCTLocal bool, ips []net.IP, idsToRm policy.RuleContexts) {
-	endpointmanager.RmCTEntriesOf(!d.conf.IPv4Disabled, e, isCTLocal, ips, idsToRm)
+func (d *Daemon) ModifyCTEntries(e *endpoint.Endpoint, isCTLocal bool, ips []net.IP, idsToMod policy.SecurityIDContexts) {
+	endpointmanager.ModifyEntriesOf(!d.conf.IPv4Disabled, e, isCTLocal, ips, idsToMod)
 }
 
 // FlushCTEntries flushes the connection tracking of the given endpoint
 // where the given endpoint IPs' match the CT entry fields.
```
Comment (ianvernon) [inline daemon/daemon.go]: IPs' --> IPs

File: daemon/daemon.go [hunk 29]
```diff
@@ -253,21 +253,21 @@ func (d *Daemon) DebugEnabled() bool {
...
 // isCTLocal should bet set as true if the endpoint's CT table is either
 // local or not (if is not local then is assumed to be global).
```
Comment (ianvernon) [inline daemon/daemon.go]: if it is not local then it is assumed to be global

File: pkg/endpoint/bpf.go (hunk 22 above)
Comment (ianvernon) [inline pkg/endpoint/bpf.go]: what constitutes "modification"? Would help to define what this is.

File: pkg/endpoint/bpf.go [hunk 30]
```diff
@@ -375,25 +375,28 @@ func (ep *epInfoCache) GetBPFValue() (*lxcmap.EndpointInfo, error) {
...
+// It returns a sync.WaitGroup that will signalize when the CT entry table
+// is updated.
+func updateCT(owner Owner, e *Endpoint, epIPs []net.IP,
```
Comment (ianvernon) [inline pkg/endpoint/bpf.go]: What is the rationale for the change to have the endpoint as a parameter rather than the receiver? I prefer having it as a receiver for consistency across the package.

File: pkg/endpoint/bpf.go (hunk 6 above)
Comment (ianvernon) [reply pkg/endpoint/bpf.go]: Agree with @manalibhutiyani here. We should defer to the mode that the daemon has enabled if building fails.

File: pkg/endpoint/owner.go [hunk 31]
```diff
@@ -76,17 +76,18 @@ type Owner interface {
 	// of BPF programs.
 	GetCompilationLock() *lock.RWMutex
 
-	// CleanCTEntries cleans the connection tracking of the given endpoint
-	// where the given endpoint IPs' and the idsToRm match the CT entry fields.
+	// ModifyCTEntries modifies the entries in the Connection Tracking table for
+	// the given endpoint where the given endpoint IPs' and the idsToMod match
```
Comment (ianvernon) [inline pkg/endpoint/owner.go]: IPs

File: pkg/endpoint/owner.go [hunk 32]
```diff
@@ -76,17 +76,18 @@ type Owner interface {
...
+	// the CT entry fields.
 	// isCTLocal should be set as true if the endpoint's CT table is either
 	// local or not (if is not local then is assumed to be global).
```
Comment (ianvernon) [inline pkg/endpoint/owner.go]: if it is not local, then it it assumed to be global

File: pkg/endpoint/policy.go [hunk 33]
```diff
@@ -130,21 +130,18 @@ func getSecurityIdentities(labelsMap *LabelsMap, selector *api.EndpointSelector)
 // It also returns the number of errors that occurred while when removing the
```
Comment (ianvernon) [inline pkg/endpoint/policy.go]: Remove this line, as the number of errors is no longer returned.

File: pkg/endpointmanager/conntrack.go (hunk 10 above)
Comment (aanm) [reply pkg/endpointmanager/conntrack.go]: The tests can become flake because they were supposed to count for the exact number of CT entries that were removed. With a garbage collector running every 10 seconds the number of CT entries that were removed need to be checked if they are less or equal than the expected number which IMO it's not very precise.

File: pkg/endpoint/bpf.go [hunk 34]
```diff
@@ -602,20 +642,35 @@ func (e *Endpoint) regenerateBPF(owner Owner, epdir, reason string) (uint64, err
 			e.L3Maps.DestroyBpfMap(IPv4Egress, e.IPv4EgressMapPathLocked())
 		}
 	}
+
+	// Since the endpoint's lock will be unlocked, we need to
+	// store the current endpoint state so we can later on
+	// update the CT without requiring to lock the endpoint again.
+	isPolicyEnforced := e.IngressOrEgressIsEnforced()
```
Comment (ianvernon) [inline pkg/endpoint/bpf.go:656]: Doesn't this mean that the conntrack entries for an endpoint can be updated with the endpoint being unlocked? Is this desirable?

File: pkg/endpoint/owner.go [hunk 35]
```diff
@@ -76,17 +76,18 @@ type Owner interface {
...
-	CleanCTEntries(e *Endpoint, isCTLocal bool, ips []net.IP, idsToRm policy.RuleContexts)
+	ModifyCTEntries(e *Endpoint, isCTLocal bool, ips []net.IP, idsToMod policy.SecurityIDContexts)
 
-	// FlushCTEntries flushes the connection tracking of the given endpoint
-	// where the given endpoint IPs' and the idsToKeep don't match any of the CT entry fields.
+	// FlushCTEntries flushes all entries in the Connection Tracking table for
+	// where the given endpoint IPs' except the entries that match the idsToKeep
 	// isCTLocal should be set as true if the endpoint's CT table is either
 	// local or not (if is not local then is assumed to be global).
```
Comment (ianvernon) [inline pkg/endpoint/owner.go]: if it is not local, then it it assumed to be global

File: pkg/endpoint/owner.go [hunk 36]
```diff
@@ -76,17 +76,18 @@ type Owner interface {
...
+	// the CT entry fields.
 	// isCTLocal should be set as true if the endpoint's CT table is either
 	// local or not (if is not local then is assumed to be global).
-	CleanCTEntries(e *Endpoint, isCTLocal bool, ips []net.IP, idsToRm policy.RuleContexts)
+	ModifyCTEntries(e *Endpoint, isCTLocal bool, ips []net.IP, idsToMod policy.SecurityIDContexts)
 
-	// FlushCTEntries flushes the connection tracking of the given endpoint
-	// where the given endpoint IPs' and the idsToKeep don't match any of the CT entry fields.
+	// FlushCTEntries flushes all entries in the Connection Tracking table for
+	// where the given endpoint IPs' except the entries that match the idsToKeep
```
Comment (ianvernon) [inline pkg/endpoint/owner.go]: IPs

File: pkg/endpoint/policy.go (hunk 9 above)
Comment (ianvernon) [reply pkg/endpoint/policy.go]: Agreed, named return values here would make the code easier to read.

File: pkg/endpoint/policy.go [hunk 37]
```diff
@@ -353,15 +363,71 @@ func (e *Endpoint) regenerateConsumable(owner Owner, labelsMap *LabelsMap,
...
+				e.getLogger().WithError(err).Fatal("L4 Policy application failed")
 			}
 		}
-		e.L4Policy = c.L4Policy // Reuse the common policy
+		// Reuse the common policy, will be used in lxc_config.h (CFG_L4_INGRESS and CFG_L4_EGRESS)
+		e.L4Policy = c.L4Policy
 		e.LabelsMap = labelsMap // Remember the set of labels used
+
+		// We need to know which ones are L4-only by checking
+		// if there's any L4-only rules that doesn't match a L3-L4 rule.
```
Comment (ianvernon) [inline pkg/endpoint/policy.go]: ... if there are any L4-only rules that do not match ...

File: pkg/endpoint/policy.go [hunk 38]
```diff
@@ -353,15 +363,71 @@ func (e *Endpoint) regenerateConsumable(owner Owner, labelsMap *LabelsMap,
...
+				}
+				for rmL4RuleCtx, rmL7RuleCtx := range ruleCtxsRm {
+					removed, ok := rulesRm[secID][rmL4RuleCtx]
+					rmL7RuleCtx.L4Installed = rmL7RuleCtx.L4Installed || (removed.L4Installed && ok)
+					rulesRm[secID][rmL4RuleCtx] = rmL7RuleCtx
+				}
+			}
+		}
+	} else {
+		// If there were no modifications to the L3L4 policy lets copy the
```
Comment (ianvernon) [inline pkg/endpoint/policy.go]: ... L3-L4, copy the existing L3-L4 policy.

File: pkg/endpoint/policy.go [hunk 39]
```diff
@@ -450,7 +527,9 @@ func (e *Endpoint) regenerateL3Policy(owner Owner, repo *policy.Repository, revi
 // IngressOrEgressIsEnforced returns true if either ingress or egress is in
```
Comment (ianvernon) [inline pkg/endpoint/policy.go:536]: Update the documentation for this function to reflect the addition of `policy.GetPolicyEnabled()` having its result checked.

File: pkg/endpoint/policy.go [hunk 40]
```diff
@@ -533,7 +612,8 @@ func (e *Endpoint) regeneratePolicy(owner Owner, opts models.ConfigurationMap) (
 			"policyRevision.repo": revision,
 		}).Debug("Skipping policy recalculation")
 		// This revision already computed, but may still need to be applied to BPF
-		return e.nextPolicyRevision > e.policyRevision, false, nil, nil, nil
+		// REVIEW: Why does this means the policy was changed?!
```
Comment (ianvernon) [inline pkg/endpoint/policy.go]: Maybe the debug message isn't as clear as it should be? This check is only concerning label-based policy. I'd have to stare at the code longer to see why if the label maps are equal whether we can return here.

File: pkg/endpointmanager/conntrack.go [hunk 41]
```diff
@@ -129,16 +130,16 @@ func EnableConntrackGC(ipv4, ipv6 bool) {
 	}()
 }
 
-// RmCTEntriesOf cleans the connection tracking table of the given endpoint `e`.
-// It removes all CT entries that of the CT table local or global, defined by isLocal,
-// that contains:
+// ModifyEntriesOf modifies the connection tracking table of the given endpoint
+// `e`. It modifies all CT entries that of the CT table local or global, defined
+// by isLocal, that contains:
```
Comment (ianvernon) [inline pkg/endpointmanager/conntrack.go]: contains --> contain

File: pkg/policy/consumer.go (hunk 23 above)
Comment (ianvernon) [inline pkg/policy/consumer.go]: Add documentation

File: pkg/policy/identity.go [hunk 42]
```diff
@@ -63,21 +65,82 @@ func (id NumericIdentity) Uint32() uint32 {
...
+
+// SecurityIDContexts returns a new L4RuleContexts created.
+func NewSecurityIDContexts() SecurityIDContexts {
+	return SecurityIDContexts(make(map[NumericIdentity]L4RuleContexts))
+}
+
+// L4RuleContexts maps a rule context to a boolean.
+type L4RuleContexts map[L4RuleContext]L7RuleContext
+
+// NewL4RuleContexts returns a new L4RuleContexts created.
```
Comment (ianvernon) [inline pkg/policy/identity.go]: remove created

File: pkg/policy/identity.go [hunk 43]
```diff
@@ -63,21 +65,82 @@ func (id NumericIdentity) Uint32() uint32 {
...
+	return cpy
+}
+
+// SecurityIDContexts returns a new L4RuleContexts created.
+func NewSecurityIDContexts() SecurityIDContexts {
+	return SecurityIDContexts(make(map[NumericIdentity]L4RuleContexts))
+}
+
+// L4RuleContexts maps a rule context to a boolean.
+type L4RuleContexts map[L4RuleContext]L7RuleContext
```
Comment (ianvernon) [inline pkg/policy/identity.go]: What does this boolean represent?

File: pkg/policy/identity.go [hunk 44]
```diff
@@ -63,21 +65,82 @@ func (id NumericIdentity) Uint32() uint32 {
...
+func (rc L4RuleContexts) DeepCopy() L4RuleContexts {
+	cpy := make(L4RuleContexts)
+	for k, v := range rc {
+		cpy[k] = v
+	}
+	return cpy
+}
+
+// IsL3Only returns false if the given L4RuleContexts contains any entry. If it
+// does not contain any entry it is considered a L3 only rule.
```
Comment (ianvernon) [inline pkg/policy/identity.go]: ... an L3-only...

File: pkg/policy/identity.go [hunk 45]
```diff
@@ -63,21 +65,82 @@ func (id NumericIdentity) Uint32() uint32 {
...
+	// L4Installed specifies if the given rule is installed in the L4 BPF map
+	L4Installed bool
+}
+
+// IsRedirect checks if the L7RuleContext is a redirect to the proxy.
+func (rc L7RuleContext) IsRedirect() bool {
+	return rc.RedirectPort != 0
+}
+
+// PortProto returns the port proto tuple in a human readable format. I.e.
```
Comment (ianvernon) [inline pkg/policy/identity.go]: human-readable format, i.e. ...

File: pkg/endpoint/bpf.go (hunk 19 above)
Comment (tgraf) [inline pkg/endpoint/bpf.go]: It absolutely must happen, the build can later succeed.

File: pkg/endpoint/bpf.go [hunk 46]
```diff
@@ -542,26 +545,63 @@ func (e *Endpoint) regenerateBPF(owner Owner, epdir, reason string) (uint64, err
...
+		}
+		// policyChanged can still be true and, at the same time,
+		// the consumersAdd be nil. If this happens it means
+		// the L4-L7 was changed so we need to update the
+		// L3L4Policy map with the new proxyport.
+		if policyChanged &&
+			consumersAdd == nil &&
+			c.L4Policy != nil &&
+			c.L4Policy.Ingress != nil &&
+			c.L3L4Policy != nil {
```
Comment (tgraf) [inline pkg/endpoint/bpf.go]: I don't understand this logic at all and comment does not clear it up fo rme.

policyChanged is return whenever policy has been changed on either L3, L4, or L7. Why does `consumersAdd` being nil mean anything.

Why try and guess what happened on the policy change side. We know *exactly* what changes while regenerated the policy. Let's just return a struct that contains the exact summary of the changes as required to draw valid consequences from it.

What information do you need? L4 or L7 change without a change in L3 underneath?

**Review by tgraf — CHANGES_REQUESTED** [review]

File: test/runtime/ct.go [hunk 47]
```diff
@@ -115,7 +104,35 @@ var _ = Describe("RuntimeConntrackTable", func() {
...
+		res.ExpectSuccess("Deleting all policies")
+
+		containers(helpers.Create)
+	})
+
+	AfterEach(func() {
+		vm.PolicyDelAll()
+		netcatPort = 11111
+		containers(helpers.Delete)
+		vm.SetPolicyEnforcement(helpers.PolicyEnforcementDefault)
```
Comment (eloycoto) [inline test/runtime/ct.go]: Could you add a `ExpectSuccess` please?

File: test/runtime/ct.go [hunk 48]
```diff
@@ -128,254 +145,411 @@ var _ = Describe("RuntimeConntrackTable", func() {
...
-	testReach := func(src, dest, mode string, assertFn func() types.GomegaMatcher) {
+	testReach := func(src, dest, destPort, mode string, assertFn func() types.GomegaMatcher) {
 		switch mode {
 		case http:
-			res := vm.ContainerExec(src, helpers.CurlFail(fmt.Sprintf(
-				"http://%s/", net.JoinHostPort(dest, "80"))))
-			ExpectWithOffset(1, res.WasSuccessful()).Should(assertFn(), "Failed to curl '%s'", res.GetCmd())
+			cmd := fmt.Sprintf("http://%s/", net.JoinHostPort(dest, destPort))
+			res := vm.ContainerExec(src, helpers.CurlFail(cmd))
+			ExpectWithOffset(0, res.WasSuccessful()).Should(assertFn(),
```
Comment (eloycoto) [inline test/runtime/ct.go]: Here should be `ExpectWithOffset(1`

File: test/runtime/ct.go [hunk 49]
```diff
@@ -128,254 +145,411 @@ var _ = Describe("RuntimeConntrackTable", func() {
...
+			Expect(data).To(BeNumerically(comparator, 1), des)
+		}
+
+		res := vm.PolicyDel("l3-only-policy-server-2")
+		res.ExpectSuccess("Deleting policy `l3-only-policy-server-2`")
+
+		areEndpointsReady := vm.WaitEndpointsReady()
+		Expect(areEndpointsReady).Should(BeTrue(), "Endpoints are not in ready state after deleting policy `l3-only-policy-server-2`")
+
+		vm.ExecCilium("endpoint list")
```
Comment (eloycoto) [inline test/runtime/ct.go]: Why this command here?

File: test/runtime/ct.go [hunk 50]
```diff
@@ -128,254 +145,411 @@ var _ = Describe("RuntimeConntrackTable", func() {
...
-	It("tests conntrack tables between client to server", func() {
-		vm.SetPolicyEnforcement(helpers.PolicyEnforcementAlways)
-		containers(helpers.Create)
-		defer containers(helpers.Delete)
-		vm.WaitEndpointsReady()
+	It("testing conntrack entries clean up with L3-L4 policy", func() {
+
+		By("Installing L3-L4 policy")
+
+		policy := `[{
```
Comment (eloycoto) [inline test/runtime/ct.go]: I would like to have some indention here. As line 509

File: test/runtime/ct.go [hunk 51]
```diff
@@ -385,113 +559,244 @@ var _ = Describe("RuntimeConntrackTable", func() {
...
+		By("Checking if CT entries from server-3 to client is the number of connections make")
+		data, err := countCTINEntriesOf(meta[server3][helpers.IPv6], "80", meta[client][helpers.IPv6], epIdentities[client])
 		Expect(err).To(BeNil())
+		Expect(data).To(BeNumerically(comparator, 4), "CT map should have exactly 4 entries or less between server-3 and client")
+
+		data, err = countCTINEntriesOf(meta[server3][helpers.IPv4], "80", meta[client][helpers.IPv4], epIdentities[client])
+		Expect(err).To(BeNil())
+		Expect(data).To(BeNumerically(comparator, 4), "CT map should have exactly 4 entries or less between server-3 and client")
+
+		policyL7 := `[{
```
Comment (eloycoto) [inline test/runtime/ct.go]: Indention here please :-)

File: test/runtime/ct.go [hunk 52]
```diff
@@ -385,113 +559,244 @@ var _ = Describe("RuntimeConntrackTable", func() {
...
 		}
 
-		// Using a different netcat source port
-		netcatPort = 11112
-		testReach(client, meta[server3][helpers.IPv4], netcatPrivate, BeTrue)
-		testReach(client, meta[server3][helpers.IPv6], netcatPrivate, BeTrue)
-		netcatPort = 11111
+		countNCwithClientCTEntries := func(kind string, nEntries int, dstPort string) {
+			data, err := countCTINEntriesOf(meta[netcat][kind], dstPort, meta[client][kind], epIdentities[client])
+			Expect(err).To(BeNil(),
```
Comment (eloycoto) [inline test/runtime/ct.go]: `ExpectWithOfset(1`

**Review by eloycoto — CHANGES_REQUESTED** [review]

File: pkg/policy/identity.go [hunk 53]
```diff
@@ -63,21 +65,82 @@ func (id NumericIdentity) Uint32() uint32 {
...
-	L7RedirectPort uint16
-	// IsRedirect is set in case the rule is a redirect
-	IsRedirect bool
+}
+
+type L7RuleContext struct {
+	// RedirectPort is the L7 redirect port in the policy in network byte order
+	RedirectPort uint16
+	// L4Installed specifies if the given rule is installed in the L4 BPF map
+	L4Installed bool
```
Comment (raybejjani) [inline pkg/policy/identity.go]: `InstalledInL4` or `L4Dependent` might have been more clear when I first saw this variable in other places. I'm not sure that my suggestions are actually better for anyone else.

File: pkg/endpoint/policy.go [hunk 54]
```diff
@@ -353,15 +363,71 @@ func (e *Endpoint) regenerateConsumable(owner Owner, labelsMap *LabelsMap,
...
+					if _, ok := rulesAdd[policy.InvalidIdentity]; !ok {
+						rulesAdd[policy.InvalidIdentity] = policy.NewL4RuleContexts()
+					}
+					l7RuleCtx.L4Installed = true
+					rulesAdd[policy.InvalidIdentity][l4RuleCtx] = l7RuleCtx
+				}
+			}
+		}
+
 		changed = true
```
Comment (raybejjani) [inline pkg/endpoint/policy.go]: Could this move above the loop above? It's a little out of place since it doesn't seem to impact the loops directly

File: pkg/endpoint/policy.go [hunk 55]
```diff
@@ -353,15 +363,71 @@ func (e *Endpoint) regenerateConsumable(owner Owner, labelsMap *LabelsMap,
...
+					rulesRm[secID] = policy.NewL4RuleContexts()
+				}
+				for rmL4RuleCtx, rmL7RuleCtx := range ruleCtxsRm {
+					removed, ok := rulesRm[secID][rmL4RuleCtx]
+					rmL7RuleCtx.L4Installed = rmL7RuleCtx.L4Installed || (removed.L4Installed && ok)
+					rulesRm[secID][rmL4RuleCtx] = rmL7RuleCtx
+				}
+			}
+		}
+	} else {
```
Comment (raybejjani) [inline pkg/endpoint/policy.go]: Could this case go first? By the time I reached the else, I forgot what the branch was on :/

File: pkg/policy/identity.go (hunk 43 above)
Comment (raybejjani) [reply pkg/policy/identity.go]: It's not even a boolean! :P

**Comment by tgraf** [comment]
I've discussed in detail with @aanm offline. I have a variety of feedback and it quickly evolved into changes way outside of this PR. This code overall needs a massive cleanup.

Overall:
 - Writing down the exact specification, in particular around L4 wildcards.
 - Verification of the datapath to implement documented behaviour
 - Separation of datapath sync with conntrack sync logic
 - Split of policy into desired state and enforced state

However, this PR as-is fixes several high profile issues so we will merge this as-is as soon as possible while compiling a list of tasks to achieve the above. @aanm will do the minimal amount of changes required to address the feedback but we will not spend any time on making it prettier as we have to touch this heavily again in a very short period of time.

File: daemon/daemon.go (hunk 27 above)
Comment (aanm) [reply daemon/daemon.go]: it's called `ResetProxyPort` now

File: daemon/daemon.go (hunk 24 above)
Comment (aanm) [reply daemon/daemon.go]: Done

File: daemon/daemon.go (hunk 25 above)
Comment (aanm) [reply daemon/daemon.go]: Done

File: daemon/daemon.go (hunk 26 above)
Comment (aanm) [reply daemon/daemon.go]: Done

File: daemon/daemon.go (hunk 28 above)
Comment (aanm) [reply daemon/daemon.go]: Done

File: daemon/daemon.go (hunk 29 above)
Comment (aanm) [reply daemon/daemon.go]: Done

File: pkg/endpoint/bpf.go (hunk 22 above)
Comment (aanm) [reply pkg/endpoint/bpf.go]:
```
// is not being enforced then all CT entries that match idsToMod will be
// modified, by resetting its proxy_port to 0 since there is no proxy running
// with policy enforcement disabled.
```

Comment (aanm) [reply pkg/endpoint/bpf.go]:
```
// is not being enforced then all CT entries that match idsToMod will be
// modified, by resetting its proxy_port to 0 since there is no proxy running
// with policy enforcement disabled.
```

File: pkg/endpoint/bpf.go (hunk 30 above)
Comment (aanm) [reply pkg/endpoint/bpf.go]: I understand that but we don't actually use the endpoint's values in this function. I'm was thinking ahead where this functions should not be called for a single endpoint but for multiple endpoints at the same time. By, later on, passing multiple endpoints, we can clean up the whole CT for all endpoints in a single pass.

File: pkg/endpoint/bpf.go (hunk 17 above)
Comment (aanm) [reply pkg/endpoint/bpf.go:568]: Yes

File: pkg/endpoint/bpf.go (hunk 46 above)
Comment (aanm) [reply pkg/endpoint/bpf.go]: Discussed offline

File: pkg/endpoint/bpf.go (hunk 7 above)
Comment (aanm) [reply pkg/endpoint/bpf.go]: Done

Comment (aanm) [reply pkg/endpoint/bpf.go]: Done

File: pkg/endpoint/bpf.go (hunk 18 above)
Comment (aanm) [reply pkg/endpoint/bpf.go]: Why? it's a local variable

File: pkg/endpoint/bpf.go (hunk 34 above)
Comment (aanm) [reply pkg/endpoint/bpf.go:656]: Yes, the conntrack change is always executed async. this will be dealt in the future

File: pkg/endpoint/bpf.go (hunk 19 above)
Comment (aanm) [reply pkg/endpoint/bpf.go]: Not the `policyChanged` but the `updateCT` function will take that into account

Comment (aanm) [reply pkg/endpoint/bpf.go]: Done

File: pkg/endpoint/bpf.go (hunk 6 above)
Comment (aanm) [reply pkg/endpoint/bpf.go]: `isPolicyEnforced := e.IngressOrEgressIsEnforced()` takes that into consideration

File: pkg/endpoint/owner.go (hunk 31 above)
Comment (aanm) [reply pkg/endpoint/owner.go]: Done

File: pkg/endpoint/owner.go (hunk 32 above)
Comment (aanm) [reply pkg/endpoint/owner.go]: Done

File: pkg/endpoint/owner.go (hunk 36 above)
Comment (aanm) [reply pkg/endpoint/owner.go]: Done

File: pkg/endpoint/owner.go (hunk 35 above)
Comment (aanm) [reply pkg/endpoint/owner.go]: Done

File: pkg/endpoint/policy.go (hunk 33 above)
Comment (aanm) [reply pkg/endpoint/policy.go]: Done

File: pkg/endpoint/policy.go (hunk 8 above)
Comment (aanm) [reply pkg/endpoint/policy.go]: Done

File: pkg/endpoint/policy.go (hunk 9 above)
Comment (aanm) [reply pkg/endpoint/policy.go]: Done

File: pkg/endpoint/policy.go (hunk 13 above)
Comment (aanm) [reply pkg/endpoint/policy.go]: "rules". Policy is a set of rules

File: pkg/endpoint/policy.go (hunk 37 above)
Comment (aanm) [reply pkg/endpoint/policy.go]: Done

File: pkg/endpoint/policy.go (hunk 54 above)
Comment (aanm) [reply pkg/endpoint/policy.go]: Moved

File: pkg/endpoint/policy.go (hunk 55 above)
Comment (aanm) [reply pkg/endpoint/policy.go]: Done

File: pkg/endpoint/policy.go (hunk 38 above)
Comment (aanm) [reply pkg/endpoint/policy.go]: Done

File: pkg/endpoint/policy.go (hunk 39 above)
Comment (aanm) [reply pkg/endpoint/policy.go:536]: Done

File: pkg/endpoint/policy.go (hunk 40 above)
Comment (aanm) [reply pkg/endpoint/policy.go]: Discussed offline with @tgraf , comments updated

File: pkg/endpointmanager/conntrack.go (hunk 10 above)
Comment (aanm) [reply pkg/endpointmanager/conntrack.go]: This is now a variable that can be changed with `cilium config` it will be easier for the tests

File: pkg/endpointmanager/conntrack.go (hunk 41 above)
Comment (aanm) [reply pkg/endpointmanager/conntrack.go]: Done

File: pkg/maps/ctmap/ctmap.go (hunk 14 above)
Comment (aanm) [reply pkg/maps/ctmap/ctmap.go]: changed to 
```
		// In CT entries, the source address of the conntrack entry (`saddr`) is
		// the destination of the packet received, therefore it's the packet's 
		// destination IP
```

File: pkg/maps/ctmap/ctmap.go (hunk 11 above)
Comment (aanm) [reply pkg/maps/ctmap/ctmap.go]: Correct, thanks for confirming!

File: pkg/maps/ctmap/ctmap.go (hunk 12 above)
Comment (aanm) [reply pkg/maps/ctmap/ctmap.go]: It means, for example, there's a L3-L4 rule installed which allows port 80, but the port in the CT entry is 82.

File: pkg/policy/consumer.go (hunk 23 above)
Comment (aanm) [reply pkg/policy/consumer.go]: It will be a structure with the introduction of egress

Comment (aanm) [reply pkg/policy/consumer.go]: Done

File: pkg/policy/identity.go (hunk 43 above)
Comment (aanm) [reply pkg/policy/identity.go]: It was just to see if you were paying attention. Fixed.

File: pkg/policy/identity.go (hunk 42 above)
Comment (aanm) [reply pkg/policy/identity.go]: Done

File: pkg/policy/identity.go (hunk 44 above)
Comment (aanm) [reply pkg/policy/identity.go]: Done

File: pkg/policy/identity.go (hunk 53 above)
Comment (aanm) [reply pkg/policy/identity.go]: Done

File: pkg/policy/identity.go (hunk 45 above)
Comment (aanm) [reply pkg/policy/identity.go]: Done

File: pkg/maps/ctmap/ctmap.go (hunk 12 above)
Comment (joestringer) [reply pkg/maps/ctmap/ctmap.go]: Ah, cool. If this code isn't otherwise reorganised it'd be useful to have a comment like that to give context. Thanks!

File: pkg/policy/consumer.go (hunk 23 above)
Comment (raybejjani) [reply pkg/policy/consumer.go]: For those following at home: We discussed this offline and there is an equivalent set of work to be done for egress, and it will make L3L4Policy a struct

File: pkg/policy/identity.go (hunk 53 above)
Comment (raybejjani) [reply pkg/policy/identity.go]: Thanks :) Maybe someone can make an AI for naming variables... instead of silly things like self-driving cars.

File: test/runtime/ct.go (hunk 15 above)
Comment (aanm) [reply test/runtime/ct.go:119]: The policy is set to `always` on all tests but it's only set to `default` on a couple tests

File: test/runtime/ct.go (hunk 47 above)
Comment (aanm) [reply test/runtime/ct.go]: Done

File: test/runtime/ct.go (hunk 48 above)
Comment (aanm) [reply test/runtime/ct.go]: Done

File: test/runtime/ct.go (hunk 49 above)
Comment (aanm) [reply test/runtime/ct.go]: Leftover

File: test/runtime/ct.go (hunk 16 above)
Comment (aanm) [reply test/runtime/ct.go:296]: Done

File: test/runtime/ct.go (hunk 50 above)
Comment (aanm) [reply test/runtime/ct.go]: Done

File: test/runtime/ct.go (hunk 1 above)
Comment (aanm) [reply test/runtime/ct.go:398]: Done

File: test/runtime/ct.go (hunk 4 above)
Comment (aanm) [reply test/runtime/ct.go]: It's tight with the policy.

File: test/runtime/ct.go (hunk 51 above)
Comment (aanm) [reply test/runtime/ct.go]: Done

File: test/runtime/ct.go (hunk 52 above)
Comment (aanm) [reply test/runtime/ct.go]: Done

File: tests/21-ct-clean-up.sh (hunk 5 above)
Comment (aanm) [reply tests/21-ct-clean-up.sh:47]: Done

**Comment by aanm** [comment]
test-all-ginkgo

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-all-ginkgo

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-all-ginkgo

**Comment by aanm** [comment]
test-me-please

File: test/runtime/ct.go [hunk 56]
```diff
@@ -49,15 +52,18 @@ func (c connTest) String() string {
 
 var _ = Describe("RuntimeConntrackTable", func() {
```
Comment (ianvernon) [inline test/runtime/ct.go]: Since the old CT test is now deprecated, this test should have its `Describe` changed from `RuntimeConntrackTable` --> `RuntimeValidatedConntrackTable` so that is run on `Cilium-Ginkgo-Tests` for PR builds as well as `Cilium-Ginkgo-Tests-All` which runs all tests.

**Review by ianvernon — CHANGES_REQUESTED** [review]

File: test/runtime/ct.go (hunk 56 above)
Comment (aanm) [reply test/runtime/ct.go]: Done

**Comment by aanm** [comment]
test-all-ginkgo

**Comment by aanm** [comment]
test-me-please

**Comment by aanm** [comment]
test-all-ginkgo

**Comment by aanm** [comment]
test-me-please

**Review by tgraf — APPROVED** [review]
