### PR TITLE
cilium-cli: Validate NodePort readiness on all node IP addresses

### LINKED ISSUE #39793: CI: no-policies-extra/pod-to-local-nodeport: command terminated with exit code 28
## CI failure

Failure observed in PR https://github.com/cilium/cilium/pull/39579.
Workflow link: https://github.com/cilium/cilium/actions/runs/15328435171/job/43128878679#step:27:648

```
[=] [cilium-test-3] Test [no-policies-extra] [1/21]
............................  [-] Scenario [no-policies-extra/pod-to-remote-nodeport]
  [.] Action [no-policies-extra/pod-to-remote-nodeport:curl-0: cilium-test-3/client-85f8686bb-sgsp7 (10.244.3.183) -> cilium-test-3/echo-other-node (echo-other-node.cilium-test-3:8080)]
  [.] Action [no-policies-extra/pod-to-remote-nodeport:curl-0: cilium-test-3/client-85f8686bb-sgsp7 (10.244.3.183) -> cilium-test-3/echo-other-node (echo-other-node.cilium-test-3:8080)]
  [.] Action [no-policies-extra/pod-to-remote-nodeport:curl-1: cilium-test-3/client-85f8686bb-sgsp7 (10.244.3.183) -> cilium-test-3/echo-other-node (echo-other-node.cilium-test-3:8080)]
  [.] Action [no-policies-extra/pod-to-remote-nodeport:curl-1: cilium-test-3/client-85f8686bb-sgsp7 (10.244.3.183) -> cilium-test-3/echo-other-node (echo-other-node.cilium-test-3:8080)]
  [.] Action [no-policies-extra/pod-to-remote-nodeport:curl-2: cilium-test-3/client-85f8686bb-sgsp7 (10.244.3.183) -> cilium-test-3/echo-same-node (echo-same-node.cilium-test-3:8080)]
  [.] Action [no-policies-extra/pod-to-remote-nodeport:curl-2: cilium-test-3/client-85f8686bb-sgsp7 (10.244.3.183) -> cilium-test-3/echo-same-node (echo-same-node.cilium-test-3:8080)]
  [.] Action [no-policies-extra/pod-to-remote-nodeport:curl-3: cilium-test-3/client-85f8686bb-sgsp7 (10.244.3.183) -> cilium-test-3/echo-same-node (echo-same-node.cilium-test-3:8080)]
  [.] Action [no-policies-extra/pod-to-remote-nodeport:curl-3: cilium-test-3/client-85f8686bb-sgsp7 (10.244.3.183) -> cilium-test-3/echo-same-node (echo-same-node.cilium-test-3:8080)]
  [.] Action [no-policies-extra/pod-to-remote-nodeport:curl-4: cilium-test-3/client2-6dd74d49c5-sphjx (10.244.3.90) -> cilium-test-3/echo-other-node (echo-other-node.cilium-test-3:8080)]
  [.] Action [no-policies-extra/pod-to-remote-nodeport:curl-4: cilium-test-3/client2-6dd74d49c5-sphjx (10.244.3.90) -> cilium-test-3/echo-other-node (echo-other-node.cilium-test-3:8080)]
  [.] Action [no-policies-extra/pod-to-remote-nodeport:curl-5: cilium-test-3/client2-6dd74d49c5-sphjx (10.244.3.90) -> cilium-test-3/echo-other-node (echo-other-node.cilium-test-3:8080)]
  [.] Action [no-policies-extra/pod-to-remote-nodeport:curl-5: cilium-test-3/client2-6dd74d49c5-sphjx (10.244.3.90) -> cilium-test-3/echo-other-node (echo-other-node.cilium-test-3:8080)]
  [.] Action [no-policies-extra/pod-to-remote-nodeport:curl-6: cilium-test-3/client2-6dd74d49c5-sphjx (10.244.3.90) -> cilium-test-3/echo-same-node (echo-same-node.cilium-test-3:8080)]
  [.] Action [no-policies-extra/pod-to-remote-nodeport:curl-6: cilium-test-3/client2-6dd74d49c5-sphjx (10.244.3.90) -> cilium-test-3/echo-same-node (echo-same-node.cilium-test-3:8080)]
  [.] Action [no-policies-extra/pod-to-remote-nodeport:curl-7: cilium-test-3/client2-6dd74d49c5-sphjx (10.244.3.90) -> cilium-test-3/echo-same-node (echo-same-node.cilium-test-3:8080)]
  [.] Action [no-policies-extra/pod-to-remote-nodeport:curl-7: cilium-test-3/client2-6dd74d49c5-sphjx (10.244.3.90) -> cilium-test-3/echo-same-node (echo-same-node.cilium-test-3:8080)]
  [.] Action [no-policies-extra/pod-to-remote-nodeport:curl-8: cilium-test-3/client3-87db7485b-2lhm5 (10.244.1.70) -> cilium-test-3/echo-same-node (echo-same-node.cilium-test-3:8080)]
  [.] Action [no-policies-extra/pod-to-remote-nodeport:curl-8: cilium-test-3/client3-87db7485b-2lhm5 (10.244.1.70) -> cilium-test-3/echo-same-node (echo-same-node.cilium-test-3:8080)]
  [.] Action [no-policies-extra/pod-to-remote-nodeport:curl-9: cilium-test-3/client3-87db7485b-2lhm5 (10.244.1.70) -> cilium-test-3/echo-same-node (echo-same-node.cilium-test-3:8080)]
  [.] Action [no-policies-extra/pod-to-remote-nodeport:curl-9: cilium-test-3/client3-87db7485b-2lhm5 (10.244.1.70) -> cilium-test-3/echo-same-node (echo-same-node.cilium-test-3:8080)]
  [.] Action [no-policies-extra/pod-to-remote-nodeport:curl-10: cilium-test-3/client3-87db7485b-2lhm5 (10.244.1.70) -> cilium-test-3/echo-other-node (echo-other-node.cilium-test-3:8080)]
  [.] Action [no-policies-extra/pod-to-remote-nodeport:curl-10: cilium-test-3/client3-87db7485b-2lhm5 (10.244.1.70) -> cilium-test-3/echo-other-node (echo-other-node.cilium-test-3:8080)]
  [.] Action [no-policies-extra/pod-to-remote-nodeport:curl-11: cilium-test-3/client3-87db7485b-2lhm5 (10.244.1.70) -> cilium-test-3/echo-other-node (echo-other-node.cilium-test-3:8080)]
  [.] Action [no-policies-extra/pod-to-remote-nodeport:curl-11: cilium-test-3/client3-87db7485b-2lhm5 (10.244.1.70) -> cilium-test-3/echo-other-node (echo-other-node.cilium-test-3:8080)]
  [-] Scenario [no-policies-extra/pod-to-local-nodeport]
  [.] Action [no-policies-extra/pod-to-local-nodeport:curl-0: cilium-test-3/client3-87db7485b-2lhm5 (10.244.1.70) -> cilium-test-3/echo-other-node (echo-other-node.cilium-test-3:8080)]
  [.] Action [no-policies-extra/pod-to-local-nodeport:curl-0: cilium-test-3/client3-87db7485b-2lhm5 (10.244.1.70) -> cilium-test-3/echo-other-node (echo-other-node.cilium-test-3:8080)]
  [.] Action [no-policies-extra/pod-to-local-nodeport:curl-1: cilium-test-3/client3-87db7485b-2lhm5 (10.244.1.70) -> cilium-test-3/echo-same-node (echo-same-node.cilium-test-3:8080)]
  [.] Action [no-policies-extra/pod-to-local-nodeport:curl-1: cilium-test-3/client3-87db7485b-2lhm5 (10.244.1.70) -> cilium-test-3/echo-same-node (echo-same-node.cilium-test-3:8080)]
  ❌ command "curl --silent --fail --show-error --connect-timeout 2 --max-time 10 -w %{local_ip}:%{local_port} -> %{remote_ip}:%{remote_port} = %{response_code}\n --output /dev/null http://[fc00:c111::2]:31[618](https://github.com/cilium/cilium/actions/runs/15328435171/job/43128878679#step:27:620)" failed: command failed (pod=cilium-test-3/client3-87db7485b-2lhm5, container=client3): command terminated with exit code 28
```
...
```
📋 Test Report [cilium-test-3]
❌ 1/15 tests failed (1/212 actions), 6 tests skipped, 0 scenarios skipped:
Test [no-policies-extra]:
  ❌ no-policies-extra/pod-to-local-nodeport:curl-1: cilium-test-3/client3-87db7485b-2lhm5 (10.244.1.70) -> cilium-test-3/echo-same-node (echo-same-node.cilium-test-3:8080)
    ⛑️ The following owners are responsible for reliability of the testsuite: 
        - @cilium/sig-lb (pod-to-local-nodeport)
        - @cilium/ci-structure (.github/workflows/tests-e2e-upgrade.yaml)
```

@cilium/sig-lb , are you aware of any issue like this?

### PR DESCRIPTION
**Pull request by pillai-ashwin**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer's Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

## Description

Fixes intermittent `pod-to-local-nodeport` connectivity test failures (exit code 28 - connection timeout) in dual-stack clusters.

### Root Cause

The upfront NodePort readiness check in `deployment.go` only validated `HostIP` (one IP per node, typically IPv4), but tests iterate through all addresses in `node.Status.Addresses[]` which includes both IPv4 and IPv6 in dual-stack clusters.

This meant IPv6 NodePorts were never validated for readiness, causing timeouts when tests tried them.

### Fix

Enhance the upfront NodePort validation to check all node IP addresses (NodeInternalIP and NodeExternalIP types) instead of just HostIP. This ensures all addresses that will be tested are validated during setup.

Fixes: #39793

```release-note
Fix intermittent NodePort connectivity test timeouts in dual-stack clusters by validating NodePort readiness on all node IP addresses during test setup.
```

### CODE REVIEW

File: cilium-cli/connectivity/tests/service.go [hunk 1]
```diff
@@ -248,7 +248,34 @@ func curlNodePort(ctx context.Context, s check.Scenario, t *check.Test,
...
-				a.ExecInPod(ctx, a.CurlCommand(ep))
+				// Wait for NodePort to be ready before testing connectivity
+				if err := check.WaitForNodePorts(ctx, a, *pod, addr.Address, svc); err != nil {
+					a.Debugf("NodePort %s:%d not ready, proceeding anyway: %v", addr.Address, np, err)
+				}
+
+				// Add detailed logging for IPv6 NodePort connections
+				if ipFam == features.IPFamilyV6 {
+					a.Debugf("Testing IPv6 NodePort connectivity: %s -> %s:%d", pod.Name(), addr.Address, np)
+				}
```
Comment (dylandreimerink) [inline cilium-cli/connectivity/tests/service.go]: Adding logs like this is fine during an investigation, in like a draft PR. But I do not thing we should commit them into the main branch to be part of the tools everyone will use.

**Review by dylandreimerink — CHANGES_REQUESTED** [review]
> 1. Insufficient timeouts: 2-second connect timeout was too aggressive for IPv6 NodePort connections
> 2. IPv6 networking delays: IPv6 connections can take longer to establish than IPv4

I am a bit skeptical about these findings. Establishing a connection should not take 2 seconds, especially when all of it is effective on the same node (no internet involved). If they do, then it seems to me that something is going wrong (packets being dropped, causing TCP level retires, or something related) and increasing the timeout may just mask that.

I also have never heard of IPv6 being slower than IPv4 to establish connections. I don't think we should accept that statement without something to back that up.

> Missing retry logic: Single-attempt connections failed on transient network issues

This is essentially saying that we expect Cilium, the thing we are testing to fail. I don't think that is right. These sorts of tests are exactly here to catch issues in Cilium. If the first connection we make always fails or frequently fails then we should investigate why and not plaster over it with retries. We want all connections to work, not just at least one out of three.

> Premature testing: Tests started before NodePorts were fully ready

This sounds more like the right direction. I think this is more likely to be the real fix.

File: cilium-cli/connectivity/tests/service.go (hunk 1 above)
Comment (pillai-ashwin) [reply cilium-cli/connectivity/tests/service.go]: @dylandreimerink Thanks a lot for your detailed feedback! 😊 I've made some changes based on that -
- Yes to your comment on timeouts and masking risk. Was just trying to reason with different hypothetical reasons (some of them far from reality haha) I removed IPv6-specific timeout multipliers and kept the default 2s connect-timeout uniformly across IP families. The fix now focuses on gating curl by explicit NodePort readiness rather than extending timeouts.

- In agreement on retries too. I removed default retries from NodePort actions so failures after readiness will hard-fail instead of being retried.

- Implemented readiness gating. The tests now wait for NodePort availability (`WaitForNodePorts`) before curl, which addresses the flake without relaxing timing. The `no-policies-extra/pod-to-local-nodeport` scenario runs consistently under this change.

**Review by dylandreimerink — APPROVED** [review]

**Review by derailed — APPROVED** [review]

**Review by viktor-kurchenko — APPROVED** [review]
Thank you!

**Comment by pillai-ashwin** [comment]
@viktor-kurchenko are we good to go ahead with merge?

**Comment by viktor-kurchenko** [comment]
> @viktor-kurchenko are we good to go ahead with merge?

Yes, it's marked as `ready-to-merge` now.
Thanks for the contribution!

File: cilium-cli/connectivity/tests/service.go [hunk 2]
```diff
@@ -251,6 +251,11 @@ func curlNodePort(ctx context.Context, s check.Scenario, t *check.Test,
 			// Create the Action with the original svc as this will influence what the
 			// flow matcher looks for in the flow logs.
 			t.NewAction(s, name, pod, svc, features.IPFamilyAny).Run(func(a *check.Action) {
+				// Wait for NodePort to be ready before testing connectivity
```
Comment (joestringer) [inline cilium-cli/connectivity/tests/service.go]: Why aren't all the nodeports checked to be ready right at the start of the full connectivity suite run? Do we need to perform this step each time we run the tests?

**Comment by pillai-ashwin** [comment]
@joestringer should I close this since the issue is closed? The logs have also expired.

**Comment by joestringer** [comment]
The issue was closed due to lack of activity, but it still affects the tree. I think a variation on this PR could still make sense, but the feedback above is blocking.

**Comment by pillai-ashwin** [comment]
@joestringer 
> Why aren't all the nodeports checked to be ready right at the start of the full connectivity suite run? Do we need to perform this step each time we run the tests?

There is an upfront check at [`deployment.go:2484-2490`](https://github.com/cilium/cilium/blob/main/cilium-cli/connectivity/check/deployment.go#L2484-L2490), but it's incomplete - it only validates `HostIP` (one IP per node), while the [tests iterate through all addresses](https://github.com/cilium/cilium/blob/main/cilium-cli/connectivity/tests/service.go#L228) in `node.Status.Addresses[]`.

**The gap:**

Upfront check validates:
```go
hostIP := ciliumPod.Pod.Status.HostIP  // Only one IP (more IPv4)
```

Tests target:
```go
for _, addr := range node.Status.Addresses {
    // All addresses: IPv4, IPv6, ExternalIP, etc.
}
```

**In dual-stack clusters:**
- Node has `10.0.0.1` (IPv4) and `fc00::1` (IPv6)
- Upfront check validates only `10.0.0.1`
- Test tries `fc00::1` --> never validated --> timeout

The current PR works around this by checking each address before testing it. But probably not ideal.

Probably better approach - Enhance the upfront check to validate all node IP addresses instead:

```go
for _, node := range ct.Nodes() {
    for _, addr := range node.Status.Addresses {
        if addr.Type != slimcorev1.NodeInternalIP && addr.Type != slimcorev1.NodeExternalIP {
            continue
        }
        
        for _, s := range ct.echoServices {
            if err := WaitForNodePorts(ctx, ct, *client, addr.Address, s); err != nil {
                return err
            }
        }
    }
}
```

This would remove the need for per-test checks entirely. Can update the PR to this approach if you prefer.

**Comment by joestringer** [comment]
Yes, I think that would be a more reliable and less wasteful way to ensure correctness at the beginning. Please do apply that change :pray:

**Comment by joestringer** [comment]
I see there's been some updates, but the PR title and description (release note) both talk about dropping IPv6-specific timeouts and I don't see that in the code change. 

Related, in the commit message: 

> This removes the need for per-test readiness checks.

If the need is removed, does that mean there should be another change to remove them? Does it make sense to track that with an issue and follow up to remove those checks or were you planning to look into that as part of this PR?

**Comment by pillai-ashwin** [comment]
@joestringer 
> I see there's been some updates, but the PR title and description (release note) both talk about dropping IPv6-specific timeouts and I don't see that in the code change.

Updated the pr title, description, commit message and release note. The current approach is simpler:

The fix enhances the existing upfront NodePort validation to check all node IP addresses (NodeInternalIP and NodeExternalIP) instead of just HostIP. This covers IPv6 addresses in dual-stack clusters that were previously unchecked and were causing the intermittent timeouts.

>If the need is removed, does that mean there should be another change to remove them? Does it make sense to track that with an issue and follow up to remove those checks or were you planning to look into that as part of this PR?

In an earlier version of this PR I added per-test `WaitForNodePorts()` calls before each curl, but I dropped that approach to favor fixing the upfront check directly. There are no per-test checks in main to remove, so no follow-up needed.

**Review by joestringer — APPROVED** [review]

**Comment by julianwiedmann** [comment]
Looks like this resulted in https://github.com/cilium/cilium/issues/43749.
