### PR TITLE
Fix issue where static pods never receive kubernetes labels

### LINKED ISSUE #8559: pod was considered a "normal" container when k8s fetch label failed

### PR DESCRIPTION
**Pull request by joestringer**
When a pod's labels are unable to be resolved in kube-apiserver, start
up a controller which will regularly attempt resolving the pod labels.
Eventually the apiserver should become aware of the pod and the labels
will be resolved, at which point this new code will update the
labels/identity and stop the controller.

We need this because apiserver is not sending notifications to Cilium
about static pods when it learns about them, so we would otherwise
never learn the labels of such pods.

Related: #9255
Fixes: #8559

I manually validated this by:
* Deploying this version of Cilium
* Configuring kubelet to support static pods (restart required)
* Disabled apiserver
* Created a static pod yaml in the configured kubelet directory
* Restarted apiserver after a couple of seconds
* Observed that the new controller was running
* After some time, observed that the new controller was no longer running, and the static pod had all of the labels from kubernetes.

The above manual test validation formed the basis for the script added in the second patch.

I also briefly considered instead supporting mounting the static pod directory into the Cilium container and having cilium-agent use these files as a potential second source of truth. This would be operationally more complex (requiring configuration of the directory at the very least), and would split the source of truth from just apiserver to two locations - files and apiserver. Furthermore the pod yaml doesn't specify the full pod name (which is derived from the hostname) and may not provide the namespace, so we would have to reproduce the logic for deriving these and the cluster in that logic (perhaps not a big deal). If it is strongly important to reduce the time period in which static pods may be represented with the "init" identity then we may still want to investigate this approach instead. That said we can also tweak the controller run period in this PR to speed things up, though it is still fundamentally dependent on the apiserver being notified about the static pod.

---
This change is [Reviewable](https://reviewable.io/reviews/cilium/cilium/9257)

### CODE REVIEW

**Comment by ianvernon** [comment]
Provisioning timed out of VMs:
```
19:20:25      k8s1-1.16: # Compile without cgo to allow use of cilium-cni on non-glibc platforms - see GH-5055
19:20:25      k8s1-1.16: CGO_ENABLED=0 go build -ldflags '-X "github.com/cilium/cilium/pkg/version.Version=1.6.90 b01800985 2019-09-24T01:08:23+00:00 go version go1.13 linux/amd64" -X "github.com/cilium/cilium/pkg/envoy.RequiredEnvoyVersionSHA=feb9a25e46898a501d1f9e49e95e7efbb725fe02" -X "github.com/cilium/cilium/pkg/datapath/loader.DatapathSHA="'  -tags lockdebug -o cilium-cni
20:07:46  Sending interrupt signal to process
20:07:52  script returned exit code 255
```

**Comment by ianvernon** [comment]
test-me-please

File: daemon/endpoint.go [hunk 1]
```diff
@@ -246,6 +249,47 @@ func (d *Daemon) createEndpoint(ctx context.Context, epTemplate *models.Endpoint
...
+			// If there are labels, but no pod namespace then it's
+			// likely that there are no k8s labels at all. Resolve.
+			_, k8sNamespaceSet := addLabels[k8sConst.PodNamespaceLabel]
+			k8sLabelsConfigured = k8sNamespaceSet
+		}
+
+		if !k8sLabelsConfigured {
+			done := make(chan struct{})
+
+			controllerName := fmt.Sprintf("resolve-labels-%d", ep.GetID())
```
Comment (ianvernon) [inline daemon/endpoint.go]: Will the endpoint ID be non-zero here? The call to `AddEndpoint` on the endpointmanager is performed immediately after this logic, and the endpointmanager is the entity which assigns an ID to an endpoint.

File: daemon/endpoint.go [hunk 2]
```diff
@@ -246,6 +249,47 @@ func (d *Daemon) createEndpoint(ctx context.Context, epTemplate *models.Endpoint
...
+	// Static pods (mirror pods) might be configured before the apiserver
+	// is available or has received the notification that includes the
+	// static pod's labels. In this case, start a controller to attempt to
+	// resolve the labels.
+	if ep.K8sNamespaceAndPodNameIsSet() && k8s.IsEnabled() {
+		k8sLabelsConfigured := len(addLabels) != 0
+		if k8sLabelsConfigured {
+			// If there are labels, but no pod namespace then it's
+			// likely that there are no k8s labels at all. Resolve.
+			_, k8sNamespaceSet := addLabels[k8sConst.PodNamespaceLabel]
```
Comment (aanm) [inline daemon/endpoint.go]: You can simply do `_, k8sLabelsConfigured := addLabels[k8sConst.PodNamespaceLabel]` in line 257

File: daemon/endpoint.go [hunk 3]
```diff
@@ -246,6 +249,47 @@ func (d *Daemon) createEndpoint(ctx context.Context, epTemplate *models.Endpoint
 		}
 	}
 
+	// Static pods (mirror pods) might be configured before the apiserver
+	// is available or has received the notification that includes the
+	// static pod's labels. In this case, start a controller to attempt to
+	// resolve the labels.
+	if ep.K8sNamespaceAndPodNameIsSet() && k8s.IsEnabled() {
+		k8sLabelsConfigured := len(addLabels) != 0
```
Comment (gandro) [inline daemon/endpoint.go]: I'm not super familiar with this code, so I might be missing something. But will `k8sLabelsConfigured` not always be true due to the assignment a few lines above?
https://github.com/cilium/cilium/blob/9450af1d2142c8c841d42aac8d73e97b869c12e2/daemon/endpoint.go#L243-L250

I believe the fallback to the `reserved:init` identity needs to be moved to after the static pod case.

**Review by gandro — CHANGES_REQUESTED** [review]

**Review by aanm — COMMENTED** [review]
I don't understand why these changes are required. I've test out cilium without this patch and the endpoint got the labels from kube-apiserver as soon it showed up there.

**Comment by joestringer** [comment]
> I don't understand why these changes are required. I've test out cilium without this patch and the endpoint got the labels from kube-apiserver as soon it showed up there.

@aanm which labels? From k8s or from containers? In my environment only the container runtime labels would show up when the apiserver restarted.

I don't understand why these changes are required. I've test out cilium without this patch and the endpoint got the labels from kube-apiserver as soon it showed up there.

File: daemon/endpoint.go (hunk 3 above)
Comment (joestringer) [reply daemon/endpoint.go]: Ah, good point, I was debating whether to place the labels inside that check or outside. I could either drop the Len 0 check here or move the init identity configuration bit later.

File: daemon/endpoint.go (hunk 1 above)
Comment (joestringer) [reply daemon/endpoint.go]: Argh, good point. I can construct it based on the pod namespace/name instead.

**Comment by joestringer** [comment]
@aanm The script I just added to the tests directory reliably fails with v1.6.1 (microk8s 1.15), but succeeds with this PR.

**Comment by joestringer** [comment]
test-me-please

**Review by ianvernon — APPROVED** [review]

**Review by aanm — APPROVED** [review]
I've test this out with container-runtime=disabled and it works pretty well :100:

**Comment by joestringer** [comment]
test-me-please

**Comment by ianvernon** [comment]
All feedback has been addressed; merging.
