### PR TITLE
Hubble: fix unknown identities for some CIDR

### LINKED ISSUE #11612: Some CIDR identities have identity `reserved:unknown`
Cilium network policies with CIDRSets assign different numerical security identities to different CIDR subnets. When performing a lookup for a CIDRs identity in the IPCache, we only perform a lookup on the IP itself, not on any subnets the IP may belong. This causes the identity in the flow the be `reserved:unknown` instead of the actual numerical security identity.

When looking up an IP in the IPCache, we should perform a search on different subnets, similar to the following code in Cilium:
https://github.com/cilium/cilium/blob/1d6fbaa966e1326ad865c4e5d9ed001edba4ee35/daemon/fqdn.go#L397-L413

### PR DESCRIPTION
**Pull request by rolinh**
Please, see individual commits for details.

Fixes: #11612

### CODE REVIEW

**Comment by Rolinh** [comment]
test-me-please

**Comment by Rolinh** [comment]
Switched to draft while I implement a CI test for this change.

File: daemon/cmd/hubble.go [hunk 1]
```diff
@@ -158,3 +165,100 @@ func (d *Daemon) launchHubble() {
...
+
+	ipv6Prefixes, ipv4Prefixes := d.GetCIDRPrefixLengths()
+	prefixes := ipv4Prefixes
+	bits := net.IPv4len * 8
+	if ip.To4() == nil {
+		prefixes = ipv6Prefixes
+		bits = net.IPv6len * 8
+	}
+	for _, prefixLen := range prefixes {
+		cidr := net.IPNet{
```
Comment (gandro) [inline daemon/cmd/hubble.go:260]: nit: You can optimize this further by check for `prefixLen == bits` and skip the lookup in that case (since that is a full IP lookup that you already did).

**Comment by Rolinh** [comment]
> Switched to draft while I implement a CI test for this change.

Writing a CI test proves to be painful. I'll do this as a follow-up PR as I don't think it should block this one.

**Review by tklauser — APPROVED** [review]
Nit: the 3rd commit is lacking a subject line. It starts directly with `This commit updates hubble parser's IPGetter interface in 2 ways:`. Probably better to have a short summary of the commit as its subject line.

Otherwise LGTM regarding the agent changes. Didn't look in detail at the changes affecting `pkg/hubble`.

File: daemon/cmd/hubble.go [hunk 2]
```diff
@@ -158,3 +165,104 @@ func (d *Daemon) launchHubble() {
...
+		prefixes = ipv6Prefixes
+		bits = net.IPv6len * 8
+	}
+	for _, prefixLen := range prefixes {
+		if prefixLen == bits {
+			// IP lookup was already done above; skip it here
+			continue
+		}
+		cidr := net.IPNet{
+			IP:   ip,
```
Comment (gandro) [inline daemon/cmd/hubble.go]: This unfortunately does not work. The old code pushed the IP through `ParseCIDR` here to translate the IP (e.g. `192.0.2.1`) into the network prefix (e.g. `192.0.2.0`). 

The resulting `cidr.String()` in your version therefore will be `192.0.2.1/24` instead of `192.0.2.0/24`, which will case the lookup to fail.

**Review by gandro — CHANGES_REQUESTED** [review]

File: daemon/cmd/hubble.go (hunk 2 above)
Comment (rolinh) [reply daemon/cmd/hubble.go]: Nice catch! I'll fix that.

**Comment by Rolinh** [comment]
> Nit: the 3rd commit is lacking a subject line. It starts directly with `This commit updates hubble parser's IPGetter interface in 2 ways:`. Probably better to have a short summary of the commit as its subject line.

Oops, subject line disappeared during a rebase. I added it back, thanks tor pointing it out.

**Review by gandro — APPROVED** [review]

**Comment by gandro** [comment]
test-me-please

**Review by michi-covalent — APPROVED** [review]
neat

**Comment by gandro** [comment]
The runtime unit test failure looks legit:
```
 	 # github.com/cilium/cilium/pkg/fqdn/dnsproxy [github.com/cilium/cilium/pkg/fqdn/dnsproxy.test]
	 pkg/fqdn/dnsproxy/proxy_test.go:186:3: cannot use func literal (type func(net.IP) (ipcache.Identity, bool, error)) as type LookupSecIDByIPFunc in argument to StartDNSProxy
```

File: pkg/fqdn/dnsproxy/proxy.go [hunk 3]
```diff
@@ -201,7 +201,7 @@ type LookupEndpointIDByIPFunc func(ip net.IP) (endpoint *endpoint.Endpoint, err
 // LookupSecIDByIPFunc Func wraps logic to lookup an IP's security ID from the
 // ipcache.
 // See DNSProxy.LookupSecIDByIP for usage.
-type LookupSecIDByIPFunc func(ip net.IP) (secID ipcache.Identity, exists bool, err error)
```
Comment (glibsm) [inline pkg/fqdn/dnsproxy/proxy.go:204]: interesting that err was never used

**Comment by Rolinh** [comment]
> The runtime4.9 unit test failure looks legit:

Right, this test is part of the privileged tests suite which I forgot to run locally and it failed due to the function signature change. Fix pushed.

**Comment by Rolinh** [comment]
test-me-please

**Comment by Rolinh** [comment]
retest-runtime
