### PR TITLE
kvstoremesh: lock destination etcd

### LINKED ISSUE #37127: CFP: HA KVstoremesh for identity-allocation-mode=kvstore
## Cilium Feature Proposal

**Is your proposed feature related to a problem?**

Yes, we are moving towards a production setup with kvstoremesh (leaving the vanila clustermesh behind) due to high scale, but we are missing the high availability feature of kvstoremesh container. (yes I know, it's possible for it to be HA in CRD mode) 

**Describe the feature you'd like**

Ability to run kvstoremesh with `identity-allocation-mode=kvstore` in HA mode (2 replicas).

**(Optional) Describe your proposed solution**

Seems like it will soon be possible to run kvstoremesh without apiserver and the sidecar etcd (https://github.com/cilium/cilium/pull/36216) which is great as that is not needed with external etcd (identity-allocation-mode=kvstore). 

There are multiple solutions I know of how the high availaiblity can be done:

1) Use a k8s leader election just like for cilium-operator where single instance of kvstoremesh is in charge, the second one is  in standby mode and will take over only when the first one fails.

2) Use e.g. client etcd lock (something like `backend.LockPath(ctx, "cilium/.lock")`) where both replicas will be trying to win the lock and will start synchronizing the remote data to the local etcd only if they get the lock. (similar technique is used here https://github.com/cilium/cilium/blob/main/pkg/kvstore/etcd.go#L420).

We would prefer the option #2 as that will allow to run the kvstoremesh app not only in k8s but also outside (as a docker container).

Few more notes:
- kvstoremesh uses lease for all keys with a default of 15min https://github.com/cilium/cilium/blob/main/pkg/defaults/defaults.go#L370 which can be tuned after which all keys are cleaned up from the target etcd
- when the standby kvstoremesh takes over, it will rewrite all the keys and replace their lease with a new one (owned by the second kvstoremesh replica)
- if some delete event is missed between one or the other takes over, it's cleaned up when the lease expires

### PR DESCRIPTION
**Pull request by balous**
Create per-cluster lock in destination etcd so that multiple instances of kvstoremesh can be used to sync data to a single etcd cluster. Every remote cluster can be synced by a single instance but each instance can sync different remote clusters.

Please ensure your pull request adheres to the following guidelines:

(https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [ ] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [ ] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [ ] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

This PR implements local backend locking in kvstoremesh so that multiple instances can be run over a single etcd cluster. Local backend is locked on per-remote-cluster bases as kvstoremesh opens a new etcd connection for each remote cluster. This, in theory, opens ways to more creative approaches like having multiple instances of kvstoremesh syncing different set of clusters (aka sharding) but also opens questions with difficult answers - whether to drain removed cluster if there could possibly be another instance still syncing it.

This PR implements locking within remote cluster's reconnections logic just before retrieving remote configuration. The lock is locked with timeout, which, upon expiration, makes reconnection to fail and go around. It is assumed that the lock can't be lost without losing etcd connection and thus having to reconnect. This way, there is no need to implement shutdown of sync watchers.

There are also unsolved problems:
- status - status can't report that some particular cluster is waiting for lock. It just states that the cluster is ready with outdated numbers of synced resources. A new field could be added to the status indicating locking status, but it would require to change status data structures and I would rather get some commentery for the basic idea before going into this.
- metrics - metrics can indicate two states - cluster is ready or not and I think neither of them is correct for the situation when the cluster is waiting for lock. The `cilium_kvstoremesh_remote_cluster_readiness_status` metrics could be made more general by adding a new label `state` whose value could contain one of [`ready`, `disconnected`, `locked`] but this must be carefuly thought of so that potential upgrade won't trigger alerts for rules like `cilium_kvstoremesh_remote_cluster_readiness_status < 1`.
- removed cluster drainage - kvstoremesh implements cluster draining upon config file removal. The drainage must be done only when the config file was removed from the last instance of kvstoremesh HA setup but the instances are not aware of each other.

Please @giorio94, check my chages and comment. I feel I can't continue with the PR without consultation with kvstoremesh maintainers.

Fixes: #37127

```release-note
KVStoreMesh: add support for leader election, to allow running multiple replicas when Cilium operates in kvstore identity allocation mode.
```

### CODE REVIEW

**Comment by giorio94** [comment]
Hmm, I'd be personally in favor of a global leader election mechanism, rather than a per remote cluster one.

A few reasons:

* It is way easier to reason about (and implement correctly), as it matches the common leader election pattern for Kubernetes operators (e.g, kube-controller-manager, Cilium operator and so on). It also simplifies status reporting, given that either a given replica is a leader or it is not, which can be easily expressed with a metric. The current approach implies that different replicas can be leader for different remote clusters, and it is harder to track the progression over time (as well as it requires more invasive changes to report the status).
* Ensures that etcd client-side rate limiting is consistently respected, as all requests are performed from a single replica. Otherwise, it is trickier to configure rate limits considering that they would effectively depend on the number of replicas active at any given time, and how remote clusters have been distributed.
* It prevents the complexity around cluster removal, given that only the leader would be responsible for all operations, including draining old entries. 
* IMO sharding does not provide much benefit in this context, given that the bottleneck is not really the kvstoremesh logic itself, but rate limiting to prevent overwhelming etcd itself. Arguably, the biggest advantage would be during startup, as it would reduce the number of entries to be re-synchronized assuming that a given replica only handles a subset of clusters. 
* Hooking leader election in the remote cluster connection path introduces unnecessary load on the remote etcd clusters, because all replicas but one would fail to acquire the lock after one minute, return an error and cause the connection to be torn down and established again, continuing forever.
* *It is assumed that the lock can't be lost without losing etcd connection and thus having to reconnect.*: this assumption does not hold, because the lock is acquired on the local etcd cluster, while the connection is established against the remote one, so they are totally independent (it wouldn't hold even if they were against the same cluster though, as the lease may fail to be renewed for multiple reasons). 

WDYT?

**Comment by balous** [comment]
OK, so I tried to implement single lock version, it seems to be way simplier. When the lock is lost, `cilium_kvstoremesh_remote_cluster_readiness_status` just goes to zero (the same way it does on cluster removal) and status reports 0/0 ready clusters. The commit is not finished but I would like some commentary before proceeding further.

File: pkg/clustermesh/kvstoremesh/kvstoremesh.go [hunk 1]
```diff
@@ -134,17 +143,56 @@ func RegisterSyncWaiter(p SyncWaiterParams) {
...
+		km.logger.Info("Locked backend lock")
+
+		km.common.Start(km.ctx)
+
+		select {
+		case <-km.ctx.Done():
+			km.common.Stop(km.ctx)
+			lock.Unlock(km.ctx)
+			return
+		// TBD: are we the only reader of the channel?
```
Comment (giorio94) [inline pkg/clustermesh/kvstoremesh/kvstoremesh.go]: Yes, you are for the local client (at least currently), but this channel does not strictly give you the signal that the lock got lost, as based on other status checks. In turn, this risks causing two instances of kvstoremesh to behave as leaders at the same time, with problematic consequences. 

The correct signal to check for expiration is whether the lease associated with that lock fails to be renewed, which is given here \[1]. This logic already allows to register a callback executed for all keys associated with that lease, but that's currently not configured for the lock leases \[2]. I would suggest looking into how to enable that for locks as well (the simplest approach is probably just mimicking what's already done for the other leases.

\[1]:  https://github.com/cilium/cilium/blob/978486df7460c5e6ab58d83f75f68baee47190cd/pkg/kvstore/etcd_lease.go#L280-L301
\[2]: https://github.com/cilium/cilium/blob/978486df7460c5e6ab58d83f75f68baee47190cd/pkg/kvstore/etcd.go#L504-L505

File: pkg/clustermesh/kvstoremesh/kvstoremesh.go [hunk 2]
```diff
@@ -134,17 +143,56 @@ func RegisterSyncWaiter(p SyncWaiterParams) {
...
+
+	for {
+		km.logger.Info("Locking backend lock")
+		lock, err := km.backend.LockPath(km.ctx, backendLockName)
+		if err != nil {
+			errTimer := time.NewTimer(1 * time.Second)
+			select {
+			case <-km.ctx.Done():
+				return
+			case <-errTimer.C:
```
Comment (giorio94) [inline pkg/clustermesh/kvstoremesh/kvstoremesh.go]: Nit. This could simply be `<-time.After()`, given that the timer is only used once.

File: pkg/clustermesh/kvstoremesh/kvstoremesh.go [hunk 3]
```diff
@@ -134,17 +143,56 @@ func RegisterSyncWaiter(p SyncWaiterParams) {
 	)
 }
 
+func (km *KVStoreMesh) run() {
```
Comment (giorio94) [inline pkg/clustermesh/kvstoremesh/kvstoremesh.go]: I would suggest moving this logic outside of the kvstoremesh cell, following a (simplified version of the) pattern similar to that of the Cilium operator if possible [1,2]. The two main reasons being easier extensibility, to possibly allow other cells to be guarded by the leader election as well (e.g., the heartbeat one), as well as keeping this cell independent of the leader election logic, for easier integration testing.

\[1]: https://github.com/cilium/cilium/blob/978486df7460c5e6ab58d83f75f68baee47190cd/operator/cmd/root.go#L217-L218
\[2]: https://github.com/cilium/cilium/blob/978486df7460c5e6ab58d83f75f68baee47190cd/operator/cmd/root.go#L89-L97

File: pkg/clustermesh/kvstoremesh/kvstoremesh.go [hunk 4]
```diff
@@ -134,17 +143,56 @@ func RegisterSyncWaiter(p SyncWaiterParams) {
...
+
+		select {
+		case <-km.ctx.Done():
+			km.common.Stop(km.ctx)
+			lock.Unlock(km.ctx)
+			return
+		// TBD: are we the only reader of the channel?
+		case e := <-km.backend.StatusCheckErrors():
+			km.logger.With(e).Info("Synchronization stopped")
+			km.common.Stop(km.ctx)
```
Comment (giorio94) [inline pkg/clustermesh/kvstoremesh/kvstoremesh.go]: A common approach is to trigger a full restart of the container when leader election is lost. I'd probably do the same here, just to make sure to restart from a clean state (you can use `hive.Shutdowner` for that).

File: pkg/clustermesh/kvstoremesh/kvstoremesh.go [hunk 5]
```diff
@@ -134,17 +143,56 @@ func RegisterSyncWaiter(p SyncWaiterParams) {
...
+		if err != nil {
+			errTimer := time.NewTimer(1 * time.Second)
+			select {
+			case <-km.ctx.Done():
+				return
+			case <-errTimer.C:
+				continue
+			}
+		}
+		km.logger.Info("Locked backend lock")
```
Comment (giorio94) [inline pkg/clustermesh/kvstoremesh/kvstoremesh.go]: I would suggest adding an `is_leader` metric, to make it easy to monitor that exactly one leader is active at any time.

File: pkg/clustermesh/kvstoremesh/kvstoremesh.go [hunk 6]
```diff
@@ -108,7 +117,7 @@ func newKVStoreMesh(lc cell.Lifecycle, params params) *KVStoreMesh {
 
 	// The "common" Start hook needs to be executed after that the kvstoremesh one
 	// terminated, to ensure that the backend promise has already been resolved.
-	lc.Append(km.common)
+	//	lc.Append(km.common)
 
 	return &km
 }
```
Comment (giorio94) [inline pkg/clustermesh/kvstoremesh/kvstoremesh.go:113]: Commenting here, as the UI doesn't allow be to select the correct line, but this refers to the `RegisterSyncWaiter` function. Basically, the goal there is have a readiness signal (i.e., kvstoremesh connected to all the remote clusters, and completed the initial synchronization), which is exposed both via a metric and as part of the `/readyz` endpoint \[1], used for the readiness probe.

The goal of the readiness probe in the normal case is to prevent Cilium agents from connecting when synchronization has not completed yet, to be able to use higher bootstrap QPS. However, this does not make sense in this context, and would need to be adapted because otherwise only the leader replica would eventually turn ready, which is problematic. 

Additionally, these changes do break the health check in the normal case, because it is based on the assumption that the initial list of clusters is retrieved synchronously during the execution of the `kc.common` start hook, hence ensuring that `ForEachRemoteCluster` in [2] loops on the populated set of target clusters when it gets invoked. However, that's no longer guaranteed to be the case given that the start hook is executed asynchronously. Migrating to the Cilium operator pattern as suggested above should help here as well.

\[1] https://github.com/cilium/cilium/blob/978486df7460c5e6ab58d83f75f68baee47190cd/clustermesh-apiserver/kvstoremesh/health.go#L32-L51
\[2] https://github.com/cilium/cilium/blob/978486df7460c5e6ab58d83f75f68baee47190cd/pkg/clustermesh/kvstoremesh/kvstoremesh.go#L194-L198

**Review by giorio94 — COMMENTED** [review]
Thanks, and sorry for the delayed review.

Yeah, I agree that this looks way more straightforward. I've left a few comments inline about high-level aspects that IMO should be improved. (A rebase is also necessary, as the etcd bootstrap logic changed a bit recently --- most notably, the client promise has been dropped in favor of a plain client object, adapting kvstoremesh as well).

File: pkg/clustermesh/kvstoremesh/kvstoremesh.go (hunk 1 above)
Comment (balous) [reply pkg/clustermesh/kvstoremesh/kvstoremesh.go]: I added a new method `RegisterLockLeaseExpiredObserver` to `BackendOperations` interface. I've copy-pasted `RegisterLeaseExpiredObserver`, may be I could create a reusable implementation. Is woth it?

File: pkg/clustermesh/kvstoremesh/kvstoremesh.go (hunk 3 above)
Comment (balous) [reply pkg/clustermesh/kvstoremesh/kvstoremesh.go]: I made similar implementation to the opeator one and it seems to work fine.

File: pkg/clustermesh/kvstoremesh/kvstoremesh.go (hunk 4 above)
Comment (balous) [reply pkg/clustermesh/kvstoremesh/kvstoremesh.go]: New implementation stops whole process.

File: pkg/clustermesh/kvstoremesh/kvstoremesh.go (hunk 6 above)
Comment (balous) [reply pkg/clustermesh/kvstoremesh/kvstoremesh.go:113]: After leader election implementation I found that things didn't improve. `synced` function is executed sooner than the files are loaded. So I implemented `common.WaitLoaded()` function that blocks until all preexisting files are loaded.

File: pkg/clustermesh/kvstoremesh/kvstoremesh.go (hunk 5 above)
Comment (balous) [reply pkg/clustermesh/kvstoremesh/kvstoremesh.go]: I am wondering how to do this. Should I mimic the same metric that is produced by kubernetes leader election with different labels? E.g:

```
leader_election_master_status{name="/kvstoremesh-lock"} 1
```

File: pkg/clustermesh/kvstoremesh/kvstoremesh.go (hunk 6 above)
Comment (balous) [reply pkg/clustermesh/kvstoremesh/kvstoremesh.go:113]: I am unsure about this solution. `synced()` function is triggered by a hive's `Invoke()` function which doesn't seem to obey the leader ifecycle I implemented. Is there some way to acheieve this with hive or do we need to implement waiting like this?

File: pkg/kvstore/memory.go [hunk 7]
```diff
@@ -205,6 +205,11 @@ func (c *inMemoryClient) LockPath(ctx context.Context, path string) (KVLocker, e
 func (c *inMemoryClient) RegisterLeaseExpiredObserver(prefix string, fn func(key string)) {
 }
 
+// RegisterLockLeaseExpiredObserver implements BackendOperations.
+func (c *inMemoryClient) RegisterLockLeaseExpiredObserver(prefix string, fn func(key string)) {
+	panic("unimplemented")
```
Comment (giorio94) [inline pkg/kvstore/memory.go]: Nit. This method should perform nothing (as the one above), rather than panic'ing.

File: clustermesh-apiserver/kvstoremesh/root.go [hunk 8]
```diff
@@ -44,3 +54,60 @@ func NewCmd(h *hive.Hive) *cobra.Command {
...
+}
+
+func runKVStoreMesh(ctx context.Context, log *slog.Logger, lc *LeaderLifecycle, client kvstore.Client, shutdowner hive.Shutdowner) {
+	client.RegisterLockLeaseExpiredObserver(backendLockName, func(string) {
+		log.Error("Lost backend lock.")
+		shutdowner.Shutdown()
+	})
+
+	for {
+		log.Info("Locking backend")
```
Comment (giorio94) [inline clustermesh-apiserver/kvstoremesh/root.go]: Nit. `log.Info("Acquiring leader election lock")`. And similarly for the other log lines, so that it is clearer to users what is happening.

File: clustermesh-apiserver/kvstoremesh/root.go [hunk 9]
```diff
@@ -44,3 +54,60 @@ func NewCmd(h *hive.Hive) *cobra.Command {
...
+		lock, err := client.LockPath(ctx, backendLockName)
+		if err != nil {
+			log.With("error", err).Warn("Failed to acquire backend lock")
```
Comment (giorio94) [inline clustermesh-apiserver/kvstoremesh/root.go]: It is expected to see an error here if another replica is already the leader, isn't it? In that case, the error should not be emitted at warning level.

File: clustermesh-apiserver/kvstoremesh/root.go [hunk 10]
```diff
@@ -44,3 +54,60 @@ func NewCmd(h *hive.Hive) *cobra.Command {
 
 	return rootCmd
 }
+
+func registerKVStoreMeshHooks(log *slog.Logger, lc cell.Lifecycle, llc *LeaderLifecycle, client kvstore.Client, shutdowner hive.Shutdowner) {
```
Comment (giorio94) [inline clustermesh-apiserver/kvstoremesh/root.go]: Nit. How about `registerLeaderElectionHooks`? That makes the purpose of this function a bit clearer IMO (and similarly for the function below).

File: clustermesh-apiserver/kvstoremesh/root.go [hunk 11]
```diff
@@ -44,3 +54,60 @@ func NewCmd(h *hive.Hive) *cobra.Command {
...
+			wg.Wait()
+			return nil
+		},
+	})
+}
+
+func runKVStoreMesh(ctx context.Context, log *slog.Logger, lc *LeaderLifecycle, client kvstore.Client, shutdowner hive.Shutdowner) {
+	client.RegisterLockLeaseExpiredObserver(backendLockName, func(string) {
+		log.Error("Lost backend lock.")
+		shutdowner.Shutdown()
```
Comment (giorio94) [inline clustermesh-apiserver/kvstoremesh/root.go]: Nit. I'd suggest passing an error as well, to make the shutdown reason clear: `hive.ShutdownWithError(errors.New("Leader election lost"))`

File: clustermesh-apiserver/kvstoremesh/root.go [hunk 12]
```diff
@@ -44,3 +54,60 @@ func NewCmd(h *hive.Hive) *cobra.Command {
...
+	lc.Append(cell.Hook{
+		OnStart: func(cell.HookContext) error {
+			wg.Add(1)
+			go func() {
+				runKVStoreMesh(ctx, log, llc, client, shutdowner)
+				wg.Done()
+			}()
+			return nil
+		},
+		OnStop: func(ctx cell.HookContext) error {
```
Comment (giorio94) [inline clustermesh-apiserver/kvstoremesh/root.go]: Nit. `s/ctx/hctx`, just for extra clarity.

File: clustermesh-apiserver/kvstoremesh/root.go [hunk 13]
```diff
@@ -44,3 +54,60 @@ func NewCmd(h *hive.Hive) *cobra.Command {
...
+		lc.Start(log, ctx)
+
+		<-ctx.Done()
+
+		log.Info("Releasing backend lock")
+		err = lock.Unlock(context.Background())
+		if err != nil {
+			log.With("error", err).Error("Failed to unlock backend lock")
+		}
+		return
```
Comment (giorio94) [inline clustermesh-apiserver/kvstoremesh/root.go:164]: Nit. This return is redundant.

File: pkg/clustermesh/kvstoremesh/kvstoremesh.go (hunk 1 above)
Comment (giorio94) [reply pkg/clustermesh/kvstoremesh/kvstoremesh.go]: As you prefer honestly, both alternatives work for me considering how trivial the implementation is.

File: pkg/clustermesh/kvstoremesh/kvstoremesh.go (hunk 5 above)
Comment (giorio94) [reply pkg/clustermesh/kvstoremesh/kvstoremesh.go]: Yeah, mimicking the Kubernetes leader election one makes sense to me. I'd probably make the label value a bit more expressive, but I'm not sure about what is used by K8s normally.

File: pkg/clustermesh/kvstoremesh/kvstoremesh.go (hunk 6 above)
Comment (giorio94) [reply pkg/clustermesh/kvstoremesh/kvstoremesh.go:113]: Hmm, that seems a quirk associated with the functioning of `WithLeaderLifecycle`. I would try with something like this:

```diff
diff --git a/clustermesh-apiserver/kvstoremesh/lifecycle.go b/clustermesh-apiserver/kvstoremesh/lifecycle.go
index ccd30e2a7a95..ca7f4831c6bd 100644
--- a/clustermesh-apiserver/kvstoremesh/lifecycle.go
+++ b/clustermesh-apiserver/kvstoremesh/lifecycle.go
@@ -4,7 +4,11 @@
 package kvstoremesh
 
 import (
+	"log/slog"
+	"runtime/pprof"
+
 	"github.com/cilium/hive/cell"
+	"github.com/cilium/hive/job"
 )
 
 // LeaderLifecycle is the inner lifecycle of the kvstoremesh that is started when this
@@ -22,8 +26,10 @@ func WithLeaderLifecycle(cells ...cell.Cell) cell.Cell {
 			func() *LeaderLifecycle { return &LeaderLifecycle{} },
 		),
 		cell.Decorate(
-			func(lc *LeaderLifecycle) cell.Lifecycle {
-				return lc
+			func(reg job.Registry, h cell.Health, l *slog.Logger, llc *LeaderLifecycle, mid cell.ModuleID) (cell.Lifecycle, job.Group) {
+				return llc, reg.NewGroup(h, llc,
+					job.WithLogger(l),
+					job.WithPprofLabels(pprof.Labels("cell", string(mid))))
 			},
 			cells...,
 		),
```

This bit would still need to be taken care of though:

> would need to be adapted because otherwise only the leader replica would eventually turn ready, which is problematic.

One possibility could be marking the replica as ready once the leader election process if attempted once and it returned an error due to another one already holding the lock. That will require a couple of adaptations to `RegisterSyncWaiter` though.

**Review by giorio94 — COMMENTED** [review]
Thanks! A few comments inline, but overall the approach makes sense to me.

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 9 above)
Comment (balous) [reply clustermesh-apiserver/kvstoremesh/root.go]: There is a problem with this. `LockPath()` has an [hardcoded timeout](https://github.com/cilium/cilium/blob/main/pkg/kvstore/etcd.go#L618) which makes it to exit after waiting a minute. Making this error would cause errors to appear in the log during normal operation.

What to do with this - distinguish between returned errors or make the timeout of the function configurable (and set it to infinite for this call)?

Comment (giorio94) [reply clustermesh-apiserver/kvstoremesh/root.go]: Moving the timeout to the callers makes sense to me, given that this function already takes a context as parameter. It should be also a fairly small change, considering that it is only called in a couple of places excluding tests.

File: pkg/clustermesh/kvstoremesh/kvstoremesh.go (hunk 5 above)
Comment (balous) [reply pkg/clustermesh/kvstoremesh/kvstoremesh.go]: `controller-manager` has this:

```
leader_election_master_status{name="kube-controller-manager"}
```

`name` label contains name of `leases.coordination.k8s.io` k8s object so I guess putting the lock path within the etcd database is appropriate.

Comment (giorio94) [reply pkg/clustermesh/kvstoremesh/kvstoremesh.go]: I'd suggest simply using `kvstoremesh` as name at that point, given that the lock path is more an implementation detail.

File: pkg/clustermesh/kvstoremesh/kvstoremesh.go (hunk 6 above)
Comment (balous) [reply pkg/clustermesh/kvstoremesh/kvstoremesh.go:113]: In [another thread](https://github.com/cilium/cilium/pull/39848#discussion_r2190920559), we've aggreed to make the timeout for `lockPath()` configurable and infinite for leader election, so making the service ready after first timeout won't work. In addition, it would be easy to errorneously configure the probe with too short timeout in the chart.

So what about making it ready after successfuly connecting to backend?

File: pkg/clustermesh/kvstoremesh/kvstoremesh.go (hunk 1 above)
Comment (balous) [reply pkg/clustermesh/kvstoremesh/kvstoremesh.go]: OK, I'll leave as it is now.

File: pkg/clustermesh/kvstoremesh/kvstoremesh.go (hunk 6 above)
Comment (giorio94) [reply pkg/clustermesh/kvstoremesh/kvstoremesh.go:113]: > In https://github.com/cilium/cilium/pull/39848#discussion_r2190920559, we've agreed to make the timeout for lockPath() configurable and infinite for leader election, so making the service ready after first timeout won't work.

That would be fairly easy to solve by performing a first attempt with a relatively short timeout (i.e., a few seconds) to verify if we can acquire the lock immediately, falling back to an infinite wait otherwise.

> In addition, it would be easy to errorneously configure the probe with too short timeout in the chart.

Not sure I'm understanding what you mean here.

> So what about making it ready after successfuly connecting to backend?

Nope, that would not work in the general case (etcd as sidecar), because it would break the assumptions that I mentioned at the beginning of this thread. But one possibility could be making the probe behavior configurable via a parameter, so that it is possible to use the correct one depending on whether kvstoremesh is run with a sidecar etcd or targeting an external etcd cluster.

File: pkg/clustermesh/kvstoremesh/kvstoremesh.go (hunk 5 above)
Comment (balous) [reply pkg/clustermesh/kvstoremesh/kvstoremesh.go]: So I implemented it:

```
$ curl -s localhost:9964/metrics | grep leader
# HELP cilium_kvstoremesh_leader_election_master_status leader election status
# TYPE cilium_kvstoremesh_leader_election_master_status gauge
cilium_kvstoremesh_leader_election_master_status{name="kvstoremesh"} 1
```

 There is one imperfection - hive prefixes all metrics with `cilium_kvstoremesh_` thus making it incompatible with similar metric created by leader election k8s library. Are there some posibilities to overcome this?

File: pkg/clustermesh/kvstoremesh/kvstoremesh.go (hunk 6 above)
Comment (balous) [reply pkg/clustermesh/kvstoremesh/kvstoremesh.go:113]: So I implemented double locking with 10s and infinite timeouts. There was one problem - `SyncState` module schedules its `Stop` function via hive. As leader election runs on background, I had to [reimplement](https://github.com/cilium/cilium/pull/39848/commits/f7600bf4e05a71c1d681d693740fdfd6e01db523) it to keep track of running routines via a counter. Stop function is called when this counter first reaches 0.

File: pkg/kvstore/memory.go (hunk 7 above)
Comment (balous) [reply pkg/kvstore/memory.go]: `panic` has been removed.

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 8 above)
Comment (balous) [reply clustermesh-apiserver/kvstoremesh/root.go]: Reworded.

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 9 above)
Comment (balous) [reply clustermesh-apiserver/kvstoremesh/root.go]: Timeout on the caller side: https://github.com/cilium/cilium/pull/39848/commits/93f46fda76743c2b271486a742132b1ac05f2628

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 10 above)
Comment (balous) [reply clustermesh-apiserver/kvstoremesh/root.go]: Renamed.

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 11 above)
Comment (balous) [reply clustermesh-apiserver/kvstoremesh/root.go]: Error added.

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 12 above)
Comment (balous) [reply clustermesh-apiserver/kvstoremesh/root.go]: Renamed.

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 13 above)
Comment (balous) [reply clustermesh-apiserver/kvstoremesh/root.go:164]: Removed.

**Comment by giorio94** [comment]
@balous Could you please fix the issues reported by CI before I take another look?

**Comment by balous** [comment]
> @balous Could you please fix the issues reported by CI before I take another look?

Yes, fixed.

File: pkg/kvstore/memory.go [hunk 14]
```diff
@@ -206,9 +206,7 @@ func (c *inMemoryClient) RegisterLeaseExpiredObserver(prefix string, fn func(key
 }
 
 // RegisterLockLeaseExpiredObserver implements BackendOperations.
-func (c *inMemoryClient) RegisterLockLeaseExpiredObserver(prefix string, fn func(key string)) {
-	panic("unimplemented")
-}
+func (c *inMemoryClient) RegisterLockLeaseExpiredObserver(prefix string, fn func(key string)) {}
```
Comment (giorio94) [inline pkg/kvstore/memory.go:209]: Nit. Should be moved to the first commit.

File: pkg/kvstore/etcd.go [hunk 15]
```diff
@@ -614,9 +614,7 @@ func (e *etcdClient) newExpBackoffRateLimiter(name string) backoff.Exponential {
 }
 
 func (e *etcdClient) LockPath(ctx context.Context, path string) (locker KVLocker, err error) {
-	// Create the context first, so that the timeout also accounts for the time
-	// possibly required to acquire a new session (if not already established).
-	ctx, cancel := context.WithTimeout(ctx, time.Minute)
+	ctx, cancel := context.WithCancel(ctx)
```
Comment (giorio94) [inline pkg/kvstore/etcd.go]: This line (and the one below) can now be simply deleted.

File: pkg/kvstore/allocator/allocator_test.go [hunk 16]
```diff
@@ -120,7 +120,9 @@ func BenchmarkRunLocksGC(b *testing.B) {
 		client, _ := kvstore.NewClient(context.Background(), hivetest.Logger(b), "etcd", map[string]string{
 			kvstore.EtcdAddrOption: kvstore.EtcdDummyAddress(),
 		}, kvstore.ExtraOptions{})
-		lock2, err = client.LockPath(context.Background(), allocatorName+"/locks/"+shortKey.GetKey())
+		ctx, cancel := context.WithTimeout(context.Background(), time.Second)
```
Comment (giorio94) [inline pkg/kvstore/allocator/allocator_test.go]: I guess this should be `time.Minute` to preserve the previous behavior (or otherwise the timeout could be just dropped).

File: pkg/kvstore/etcd_test.go [hunk 17]
```diff
@@ -84,7 +84,9 @@ func TestGetIfLocked(t *testing.T) {
 			name: "getting locked path",
 			setupArgs: func() args {
 				key := randomPath + "foo"
-				kvlocker, err := client.LockPath(context.Background(), "locks/"+key+"/.lock")
+				ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
+				defer cancel()
```
Comment (giorio94) [inline pkg/kvstore/etcd_test.go]: I'd be personally fine to revert these changes (same for all the other occurrences in this file) for simplicity, and simply let the test timeout kick in in case there's something wrong and the lock is not acquired in time.

File: clustermesh-apiserver/kvstoremesh/cells.go [hunk 18]
```diff
@@ -27,18 +27,28 @@ var Cell = cell.Module(
...
+		heartbeat.Cell,
+
+		cell.Invoke(func(*kvstoremesh.KVStoreMesh) {}),
+	),
+
+	// This needs to be the last in the list, so that the start hook responsible
+	// for leader election is guaranteed to be executed last, when
+	// all the previous ones have already completed. Otherwise, cells within
+	// the "WithLeaderLifecycle" scope may be incorrectly started too early,
+	// given that "registerKVStoreMeshHooks" does not depend on all of their
```
Comment (giorio94) [inline clustermesh-apiserver/kvstoremesh/cells.go]: Nit. `s/registerKVStoreMeshHooks/registerLeaderElectionHooks`

File: clustermesh-apiserver/kvstoremesh/lifecycle.go [hunk 19]
```diff
@@ -0,0 +1,37 @@
...
+// LeaderLifecycle is the inner lifecycle of the kvstoremesh that is started when this
+// instance is elected leader. It implements cell.Lifecycle allowing cells to use it.
+type LeaderLifecycle struct {
+	cell.DefaultLifecycle
+}
+
+func WithLeaderLifecycle(cells ...cell.Cell) cell.Cell {
+	return cell.Module(
+		"leader-lifecycle",
+		"Kvstoremesh Leader Lifecycle",
```
Comment (giorio94) [inline clustermesh-apiserver/kvstoremesh/lifecycle.go]: Nit. `s/Kvstoremesh/KVStoreMesh/`

File: pkg/clustermesh/kvstoremesh/cell.go [hunk 20]
```diff
@@ -23,4 +23,5 @@ var Cell = cell.Module(
 	cell.Config(common.DefaultConfig),
 
 	metrics.Metric(common.MetricsProvider("")),
+	metrics.Metric(MetricsProvider("")),
```
Comment (giorio94) [inline pkg/clustermesh/kvstoremesh/cell.go]: Nit. The subsystem parameter is always empty, so it can be simply dropped.

File: clustermesh-apiserver/kvstoremesh/root.go [hunk 21]
```diff
@@ -44,3 +59,85 @@ func NewCmd(h *hive.Hive) *cobra.Command {
...
+	syncedCallback := SyncState.WaitForResource()
+
+	client.RegisterLockLeaseExpiredObserver(backendLockName, func(string) {
+		shutdowner.Shutdown(hive.ShutdownWithError(errors.New("Leader election lost")))
+	})
+
+	kvMetrics.LeaderElectionStatus.With(prometheus.Labels{metrics.LabelLeaderElectionName: "kvstoremesh"}).Set(float64(0))
+
+	log.Info("Acquiring leader election lock")
+	toCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
```
Comment (giorio94) [inline clustermesh-apiserver/kvstoremesh/root.go:116]: Nit. It would be valuable to add a comment explaining the reason for this two-stage approach.

File: clustermesh-apiserver/kvstoremesh/root.go [hunk 22]
```diff
@@ -44,3 +59,85 @@ func NewCmd(h *hive.Hive) *cobra.Command {
...
+	defer cancel()
+
+	var lock kvstore.KVLocker
+	lock, err := client.LockPath(toCtx, backendLockName)
+
+	if err == nil {
+		syncedCallback(ctx)
+	} else {
+		if err.Error() == "etcd client timeout exceeded" {
```
Comment (giorio94) [inline clustermesh-apiserver/kvstoremesh/root.go]: I'd suggest defining this as an error variable, to avoid having to match on strings, which is always fragile.

File: clustermesh-apiserver/kvstoremesh/root.go [hunk 23]
```diff
@@ -44,3 +59,85 @@ func NewCmd(h *hive.Hive) *cobra.Command {
...
+				return err
+			}
+			cancel()
+			wg.Wait()
+			return nil
+		},
+	})
+}
+
+func runLeaderElection(ctx context.Context, log *slog.Logger, lc *LeaderLifecycle, client kvstore.Client, shutdowner hive.Shutdowner, kvMetrics kvstoremesh.Metrics, SyncState syncstate.SyncState) {
```
Comment (giorio94) [inline clustermesh-apiserver/kvstoremesh/root.go]: Nit. I'd suggest simply passing the params struct, to reduce the number of parameters.

File: clustermesh-apiserver/kvstoremesh/root.go [hunk 24]
```diff
@@ -44,3 +59,85 @@ func NewCmd(h *hive.Hive) *cobra.Command {
...
+		}
+		if err != nil {
+			log.Error("Failed to acquire backend lock", logfields.Error, err)
+			return
+		}
+	}
+	log.Info("Leader election lock acquired")
+	kvMetrics.LeaderElectionStatus.With(prometheus.Labels{metrics.LabelLeaderElectionName: "kvstoremesh"}).Set(float64(1))
+
+	lc.Start(log, ctx)
```
Comment (giorio94) [inline clustermesh-apiserver/kvstoremesh/root.go]: The error should not be ignored.

File: pkg/clustermesh/kvstoremesh/kvstoremesh.go [hunk 25]
```diff
@@ -122,16 +122,6 @@ type SyncWaiterParams struct {
...
-func RegisterSyncWaiter(p SyncWaiterParams) {
-	syncedCallback := p.SyncState.WaitForResource()
-
-	p.JobGroup.Add(
-		job.OneShot("kvstoremesh-sync-waiter", func(ctx context.Context, health cell.Health) error {
-			return p.KVStoreMesh.synced(ctx, syncedCallback)
-		}),
-	)
-}
-
```
Comment (giorio94) [inline pkg/clustermesh/kvstoremesh/kvstoremesh.go]: This should not be removed.

File: clustermesh-apiserver/syncstate/syncstate.go
Comment (giorio94) [inline clustermesh-apiserver/syncstate/syncstate.go:1]: The new approach is not correct, because SyncState may be marked ready too early if not all resources have registered before all the others are marked as complete. I would suggest dropping the start hook as you did, and then calling `ss.Stop()` where appropriate to preserve the existing behavior.

**Review by giorio94 — COMMENTED** [review]
Thanks for the updates. A few more comments inline.

File: pkg/clustermesh/kvstoremesh/kvstoremesh.go (hunk 5 above)
Comment (giorio94) [reply pkg/clustermesh/kvstoremesh/kvstoremesh.go]: That is because the metric is configured with the `cilium_kvstoremesh` namespace, otherwise it would not. But it looks reasonable to me, for consistency with all the other kvstoremesh metrics.

File: pkg/clustermesh/kvstoremesh/kvstoremesh.go (hunk 6 above)
Comment (giorio94) [reply pkg/clustermesh/kvstoremesh/kvstoremesh.go:113]: The new `SyncState` approach does not look correct to me, but I've commented directly there, so marking this thread as resolved.

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 22 above)
Comment (balous) [reply clustermesh-apiserver/kvstoremesh/root.go]: The problem here is that etcd client library doesn't define the error itself. Declaring the string as constant in cilium code won't improve the situation.

Comment (giorio94) [reply clustermesh-apiserver/kvstoremesh/root.go]: That error is defined in the Cilium codebase actually: https://github.com/cilium/cilium/blob/daa9fa24b9d97e9992b7676af597b07e255751d7/pkg/kvstore/etcd.go#L296-L302

Comment (balous) [reply clustermesh-apiserver/kvstoremesh/root.go]: Yes, it is, but as a mere string not as type like `context.DeadlineExceeded` is. It is not possible to use `errors.Is()` to compare the error, all I can do is to compare the message. Or is there some better possiblity I am unaware of?

File: pkg/kvstore/memory.go (hunk 14 above)
Comment (balous) [reply pkg/kvstore/memory.go:209]: Moved.

File: pkg/kvstore/etcd.go (hunk 15 above)
Comment (balous) [reply pkg/kvstore/etcd.go]: Removed.

File: pkg/kvstore/allocator/allocator_test.go (hunk 16 above)
Comment (balous) [reply pkg/kvstore/allocator/allocator_test.go]: Removed with the rest of test updates.

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 22 above)
Comment (giorio94) [reply clustermesh-apiserver/kvstoremesh/root.go]: Yes, that's why I was suggesting to extract it into a variable.

File: pkg/kvstore/etcd_test.go (hunk 17 above)
Comment (balous) [reply pkg/kvstore/etcd_test.go]: OK, removed.

File: clustermesh-apiserver/kvstoremesh/cells.go (hunk 18 above)
Comment (balous) [reply clustermesh-apiserver/kvstoremesh/cells.go]: Fixed.

File: clustermesh-apiserver/kvstoremesh/lifecycle.go (hunk 19 above)
Comment (balous) [reply clustermesh-apiserver/kvstoremesh/lifecycle.go]: Fixed.

File: pkg/clustermesh/kvstoremesh/cell.go (hunk 20 above)
Comment (balous) [reply pkg/clustermesh/kvstoremesh/cell.go]: Removed.

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 21 above)
Comment (balous) [reply clustermesh-apiserver/kvstoremesh/root.go:116]: Added.

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 23 above)
Comment (balous) [reply clustermesh-apiserver/kvstoremesh/root.go]: Reworked.

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 24 above)
Comment (balous) [reply clustermesh-apiserver/kvstoremesh/root.go]: Added handling.

File: clustermesh-apiserver/syncstate/syncstate.go
Comment (balous) [reply clustermesh-apiserver/syncstate/syncstate.go:1]: Basically, it works in kvstoremesh but I have to figure out how to call it in clustermesh-apiserver.

File: pkg/clustermesh/kvstoremesh/kvstoremesh.go (hunk 25 above)
Comment (balous) [reply pkg/clustermesh/kvstoremesh/kvstoremesh.go]: This was replaced by the call from `runLeaderElection()`.

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 22 above)
Comment (balous) [reply clustermesh-apiserver/kvstoremesh/root.go]: OK, added a string constant for the error message.

File: clustermesh-apiserver/syncstate/syncstate.go
Comment (balous) [reply clustermesh-apiserver/syncstate/syncstate.go:1]: So I added a start hook to `clustermesh-synchronization` cell that calls it.

File: clustermesh-apiserver/clustermesh/cells.go [hunk 26]
```diff
@@ -120,8 +120,20 @@ var Synchronization = cell.Module(
 		),
 		cell.Invoke(RegisterSynchronizer[*cilium_api_v2a1.CiliumEndpointSlice]),
 	),
+	cell.Invoke(registerSyncStateStop),
```
Comment (giorio94) [inline clustermesh-apiserver/clustermesh/cells.go:123]: Nit. The commit message should be updated with this new approach.

File: pkg/clustermesh/kvstoremesh/metrics.go [hunk 27]
```diff
@@ -0,0 +1,27 @@
...
+	"github.com/cilium/cilium/pkg/metrics"
+	"github.com/cilium/cilium/pkg/metrics/metric"
+)
+
+type Metrics struct {
+	// LeaderElectionStatus indicates state of leader election
+	LeaderElectionStatus metric.Vec[metric.Gauge]
+}
+
+func MetricsProvider() func() Metrics {
```
Comment (giorio94) [inline pkg/clustermesh/kvstoremesh/metrics.go]: Nit. No need for returning a function, you can directly return the `Metrics` object.

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 22 above)
Comment (giorio94) [reply clustermesh-apiserver/kvstoremesh/root.go]: Why not directly defining the error as a variable, so that you can directly match on it with `errors.Is`?

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 24 above)
Comment (giorio94) [reply clustermesh-apiserver/kvstoremesh/root.go]: Should also call `params.Shutdowner.Shutdown` to let the process terminate.

File: pkg/clustermesh/kvstoremesh/kvstoremesh.go (hunk 25 above)
Comment (giorio94) [reply pkg/clustermesh/kvstoremesh/kvstoremesh.go]: That's not correct though, as it modifies the behavior. We still want to only mark the replica that can acquire the lock immediately as ready only after that synchronization completed, as we did previously.

File: clustermesh-apiserver/kvstoremesh/root.go [hunk 28]
```diff
@@ -44,3 +63,93 @@ func NewCmd(h *hive.Hive) *cobra.Command {
...
+	syncedCallback := params.SyncState.WaitForResource()
+	params.SyncState.Stop()
+
+	params.Client.RegisterLockLeaseExpiredObserver(backendLockName, func(string) {
+		params.Shutdowner.Shutdown(hive.ShutdownWithError(errors.New("Leader election lost")))
+	})
+
+	params.Metrics.LeaderElectionStatus.With(prometheus.Labels{metrics.LabelLeaderElectionName: "kvstoremesh"}).Set(float64(0))
+
+	// try to win leader election with short timeout to test backend function
```
Comment (giorio94) [inline clustermesh-apiserver/kvstoremesh/root.go]: I'd replace `test backend function` with something like `to verify if we can be immediately promoted as leader (e.g., we are the only replica)` for increased clarity.

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 22 above)
Comment (balous) [reply clustermesh-apiserver/kvstoremesh/root.go]: I tried `errors.Is(err, fmt.Errorf(etcdTimeoutErr))` but it doesn't work. The strings are the same but they are not the same variable so the `errors.Is()` function won't regard the two errors as the same error.

Comment (giorio94) [reply clustermesh-apiserver/kvstoremesh/root.go]: Yes, the error should be extracted into a variable in `etcd.go`, rather than generating a new one every time. And then just compare with it using `errors.Is()`

File: pkg/clustermesh/kvstoremesh/kvstoremesh.go (hunk 25 above)
Comment (balous) [reply pkg/clustermesh/kvstoremesh/kvstoremesh.go]: Now I see. So I reworked the leader election to call `RegisterSyncWaiter()` directly outside of hive. It also calls `SyncState.Stop()` directly.

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 24 above)
Comment (balous) [reply clustermesh-apiserver/kvstoremesh/root.go]: Added.

File: clustermesh-apiserver/clustermesh/cells.go (hunk 26 above)
Comment (balous) [reply clustermesh-apiserver/clustermesh/cells.go:123]: Reworded.

File: pkg/clustermesh/kvstoremesh/metrics.go (hunk 27 above)
Comment (balous) [reply pkg/clustermesh/kvstoremesh/metrics.go]: Reworked.

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 28 above)
Comment (balous) [reply clustermesh-apiserver/kvstoremesh/root.go]: Reworded.

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 22 above)
Comment (balous) [reply clustermesh-apiserver/kvstoremesh/root.go]: I added `EtcdTimeoutError` which is returned by `Hint()` function instead of `fmt.Errorf('etcd timeout exceeded')`. Sorry for not figuring this quicky, I mistakenly though that the error is generated in etcd client itself, not in Cilium's `kvstore`.

File: pkg/kvstore/etcd.go [hunk 29]
```diff
@@ -94,6 +94,13 @@ var (
 	etcd3ClientLogger *zap.Logger
 )
 
+// error that is returned when etcd client times out
+type timeoutError struct{}
+
+var EtcdTimeoutError error = timeoutError{}
+
+func (e timeoutError) Error() string { return "etcd client timeout exceeded" }
```
Comment (giorio94) [inline pkg/kvstore/etcd.go]: Can be simplified with (IIRC the linter expects the name to start with `Err`):

```
var ErrEtcdClientTimeout = errors.New("etcd client timeout exceeded")
```

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 22 above)
Comment (giorio94) [reply clustermesh-apiserver/kvstoremesh/root.go]: No worries, that part of the codebase is definitely not easy to navigate at the beginning. One more simplification comment inline.

File: clustermesh-apiserver/kvstoremesh/root.go [hunk 30]
```diff
@@ -44,3 +60,106 @@ func NewCmd(h *hive.Hive) *cobra.Command {
...
+
+	params.Metrics.LeaderElectionStatus.With(prometheus.Labels{metrics.LabelLeaderElectionName: "kvstoremesh"}).Set(float64(0))
+
+	// Try to win leader election with short timeout to verify if we can
+	// be immediately promoted as leader (e.g., we are the only replica).
+	// If the timeout expires, just signal readiness and try again
+	// with infinite timeout.
+	params.Log.Info("Acquiring leader election lock")
+	toCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
+	defer cancel()
```
Comment (giorio94) [inline clustermesh-apiserver/kvstoremesh/root.go]: Nit. Cancel should be called after `params.Client.LockPath` terminates, as deferring it here means it would never be executed normally.

File: clustermesh-apiserver/kvstoremesh/root.go [hunk 31]
```diff
@@ -44,3 +60,106 @@ func NewCmd(h *hive.Hive) *cobra.Command {
...
+
+	var lock kvstore.KVLocker
+	lock, err := params.Client.LockPath(toCtx, backendLockName)
+
+	if err != nil && errors.Is(err, kvstore.EtcdTimeoutError) {
+		// signal readiness
+		syncedCallback := params.SyncState.WaitForResource()
+		params.SyncState.Stop()
+		syncedCallback(ctx)
```
Comment (giorio94) [inline clustermesh-apiserver/kvstoremesh/root.go]: Nit. Calling `Stop` alone should be enough, without the need for Wait/callback.

File: clustermesh-apiserver/kvstoremesh/root.go [hunk 32]
```diff
@@ -44,3 +60,106 @@ func NewCmd(h *hive.Hive) *cobra.Command {
...
+	if err != nil {
+		params.Log.Error("Failed to run KvStoremesh", logfields.Error, err)
+		params.Shutdowner.Shutdown(hive.ShutdownWithError(err))
+		return
+	}
+
+	<-ctx.Done()
+
+	params.Log.Info("Releasing leader election lock")
+	err = lock.Unlock(context.Background())
```
Comment (giorio94) [inline clustermesh-apiserver/kvstoremesh/root.go]: One tricky aspect is that when running with etcd as a sidecar, it is possible that, when the pod is restarted, etcd stops before kvstoremesh, which leads to this call to Unlock being blocking. It'd suggest setting a tight timeout (e.g., 1 or 2 seconds) to make sure we don't unnecessarily block for too long. I'd probably also convert the Error log into an info one, given that it is actually expected to happen in that case.

**Review by giorio94 — COMMENTED** [review]
Thanks, overall makes sense to me. Just a couple of nits inline, I'll take a final look once marked ready for review.

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 31 above)
Comment (balous) [reply clustermesh-apiserver/kvstoremesh/root.go]: When I remove `syncedCallback(ctx)` readiness probe won't never succeed.

If I understand [the code](https://github.com/cilium/cilium/blob/main/pkg/lock/stoppable_waitgroup.go#L32) correctly, calling `Stop()` causes `Add()` to do nothing, but `Wait()` still waits for all the routines that have registered.

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 32 above)
Comment (balous) [reply clustermesh-apiserver/kvstoremesh/root.go]: Added 2 seconds timeout.

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 30 above)
Comment (balous) [reply clustermesh-apiserver/kvstoremesh/root.go]: Fixed.

File: pkg/kvstore/etcd.go (hunk 29 above)
Comment (balous) [reply pkg/kvstore/etcd.go]: Renamed and reimplemented.

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 31 above)
Comment (giorio94) [reply clustermesh-apiserver/kvstoremesh/root.go]: Sure, I meant dropping the `WaitForResource` call as well (as it is currently registered and then immediately marked as done).

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 32 above)
Comment (giorio94) [reply clustermesh-apiserver/kvstoremesh/root.go]: Thanks. It would be nice to add a comment for future reference as well.

File: clustermesh-apiserver/kvstoremesh/root.go [hunk 33]
```diff
@@ -44,3 +60,109 @@ func NewCmd(h *hive.Hive) *cobra.Command {
...
+	params.Metrics.LeaderElectionStatus.With(prometheus.Labels{metrics.LabelLeaderElectionName: "kvstoremesh"}).Set(float64(0))
+
+	// Try to win leader election with short timeout to verify if we can
+	// be immediately promoted as leader (e.g., we are the only replica).
+	// If the timeout expires, just signal readiness and try again
+	// with infinite timeout.
+	params.Log.Info("Acquiring leader election lock")
+	toCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
+
+	var lock kvstore.KVLocker
```
Comment (giorio94) [inline clustermesh-apiserver/kvstoremesh/root.go]: Nit. Redundant, as you are using `:=` in the assignment below.

File: clustermesh-apiserver/kvstoremesh/root.go [hunk 34]
```diff
@@ -44,3 +60,109 @@ func NewCmd(h *hive.Hive) *cobra.Command {
...
+		SyncState:   params.SyncState,
+		Lifecycle:   lc,
+		JobGroup:    params.JobGroup,
+		Health:      params.Health,
+	})
+	params.SyncState.Stop()
+
+	err = lc.Start(params.Log, ctx)
+	if err != nil {
+		params.Log.Error("Failed to run KvStoremesh", logfields.Error, err)
```
Comment (giorio94) [inline clustermesh-apiserver/kvstoremesh/root.go]: Nit. `s/KvStoremesh/KVStoreMesh`

File: clustermesh-apiserver/kvstoremesh/root.go [hunk 35]
```diff
@@ -44,3 +60,109 @@ func NewCmd(h *hive.Hive) *cobra.Command {
...
+	params.Log.Info("Leader election lock acquired")
+	params.Metrics.LeaderElectionStatus.With(prometheus.Labels{metrics.LabelLeaderElectionName: "kvstoremesh"}).Set(float64(1))
+
+	kvstoremesh.RegisterSyncWaiter(kvstoremesh.SyncWaiterParams{
+		KVStoreMesh: params.KVStoreMesh,
+		SyncState:   params.SyncState,
+		Lifecycle:   lc,
+		JobGroup:    params.JobGroup,
+		Health:      params.Health,
+	})
```
Comment (giorio94) [inline clustermesh-apiserver/kvstoremesh/root.go:157]: The reason why this works is a bit :magic_wand:, and heavily relies on Hive internals. We could make '[KVStoreMesh.synced] explicitly block until its start hook has terminated as an extra guarantee, but I wouldn't block this PR on that, given that is has already undergone multiple iterations, and as to be fair that was already the case before.

**Review by giorio94 — APPROVED** [review]
Thanks, looks good to me on my side.

@MrFreezeex, @marseel Please also take an in-depth look, given the potential for regressions to standard kvstoremesh deployments as well (I haven't really convinced myself about the opportunity of hiding this behind a feature flag though, as it would introduce different bootstrap behaviors, and make the logic even more convoluted). On the bright side, we are just at the beginning of the 1.19 cycle, so we have plenty of time to discover and fix possible problems.

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 31 above)
Comment (balous) [reply clustermesh-apiserver/kvstoremesh/root.go]: Yes, it did the trick.

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 32 above)
Comment (balous) [reply clustermesh-apiserver/kvstoremesh/root.go]: Added.

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 33 above)
Comment (balous) [reply clustermesh-apiserver/kvstoremesh/root.go]: Removed.

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 34 above)
Comment (balous) [reply clustermesh-apiserver/kvstoremesh/root.go]: Fixed.

File: pkg/clustermesh/kvstoremesh/metrics.go [hunk 36]
```diff
@@ -0,0 +1,25 @@
...
+	// LeaderElectionStatus indicates state of leader election
+	LeaderElectionStatus metric.Vec[metric.Gauge]
+}
+
+func MetricsProvider() Metrics {
+	return Metrics{
+		LeaderElectionStatus: metric.NewGaugeVec(metric.GaugeOpts{
+			Namespace: metrics.Namespace,
+			Subsystem: "",
+			Name:      "leader_election_master_status",
```
Comment (marseel) [inline pkg/clustermesh/kvstoremesh/metrics.go:21]: nit: no need for "master" in the metric name, it's already about leader :)

**Review by marseel — APPROVED** [review]

File: pkg/clustermesh/kvstoremesh/metrics.go (hunk 36 above)
Comment (balous) [reply pkg/clustermesh/kvstoremesh/metrics.go:21]: Well, I copied the name from k8s leader election. I think it's practical to keep it the same.

**Review by derailed — APPROVED** [review]
@balous Thank you for this update!

File: clustermesh-apiserver/kvstoremesh/root.go [hunk 37]
```diff
@@ -44,3 +60,107 @@ func NewCmd(h *hive.Hive) *cobra.Command {
...
+
+	params.Log.Info("Releasing leader election lock")
+
+	// unlock with timeout for case the etcd sidecar has already terminated
+	toCtx, cancel = context.WithTimeout(context.Background(), 2*time.Second)
+	defer cancel()
+	err = lock.Unlock(toCtx)
+	if err != nil {
+		params.Log.Error("Failed to release leader election lock", logfields.Error, err)
+	}
```
Comment (MrFreezeex) [inline clustermesh-apiserver/kvstoremesh/root.go]: Shouldn't this be in in a whole defer function right after we acquire the lock? For instance the return in the current line 152 would not execute this AFAICT is that right?

**Review by MrFreezeex — COMMENTED** [review]
Thanks! I left a question inline that may require a tiny fix, otherwise lgtm

File: clustermesh-apiserver/kvstoremesh/root.go (hunk 37 above)
Comment (balous) [reply clustermesh-apiserver/kvstoremesh/root.go]: You're right, fixed.

**Review by MrFreezeex — APPROVED** [review]

**Comment by joestringer** [comment]
Observed https://github.com/cilium/cilium/issues/38464 in the previous gateway-api failure.
