### PR TITLE
BGPv1 and BGPv2 - Reject all inbound BGP advertisements

### LINKED ISSUE #32826: Cosmetic:  BGPv1 Control Plane accepts BGP Paths that have no effect
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This is a cosmetic bug report, for the most part.

Cilium's BGPv1 Control Plane accepts all BGP Paths advertised to it.  However, these paths do not program the datapath.  It is my understanding that they are simply ignored.

This leads me to ask -- why does Cilium accept them?

While troubleshooting Cilium's BGP stack using `cilium bgp routes`, I find it confusing to see any received routes/Paths:
```
$  cilium bgp routes --node bgp-cplane-dev-v4-worker
(Defaulting to `available ipv4 unicast` routes, please see help for more options)

Node                       VRouter   Prefix             NextHop    Age         Attrs
bgp-cplane-dev-v4-worker   65002     100.100.100.0/24   10.0.2.1   2m6s        [{Origin: i} {AsPath: 65000} {Nexthop: 10.0.2.1} {Med: 0}]
                           65002     100.100.110.0/24   10.0.2.1   19s         [{Origin: i} {AsPath: 65000} {Nexthop: 10.0.2.1} {Med: 0}]
                           65002     100.100.120.0/24   10.0.2.1   18s         [{Origin: i} {AsPath: 65000} {Nexthop: 10.0.2.1} {Med: 0}]
                           65002     100.100.130.0/24   10.0.2.1   16s         [{Origin: i} {AsPath: 65000} {Nexthop: 10.0.2.1} {Med: 0}]
                           65002     100.100.140.0/24   10.0.2.1   14s         [{Origin: i} {AsPath: 65000} {Nexthop: 10.0.2.1} {Med: 0}]
                           65002     100.64.12.1/32     0.0.0.0    173h9m55s   [{Origin: i} {Nexthop: 0.0.0.0}]
                           65002     200.200.200.0/24   10.0.2.1   2m0s        [{Origin: i} {AsPath: 65000} {Nexthop: 10.0.2.1} {Med: 0}]
                           65002     200.200.210.0/24   10.0.2.1   9s          [{Origin: i} {AsPath: 65000} {Nexthop: 10.0.2.1} {Med: 0}]
                           65002     200.200.220.0/24   10.0.2.1   7s          [{Origin: i} {AsPath: 65000} {Nexthop: 10.0.2.1} {Med: 0}]
                           65002     200.200.230.0/24   10.0.2.1   5s          [{Origin: i} {AsPath: 65000} {Nexthop: 10.0.2.1} {Med: 0}]
                           65002     200.200.240.0/24   10.0.2.1   4s          [{Origin: i} {AsPath: 65000} {Nexthop: 10.0.2.1} {Med: 0}]
```

For this example, I am running Cilium's BGP development setup (`make kind-bgp-v4`) with the changes below applied to the FRR container:

```
bash-5.1# ip route add 100.100.100.0/24 dev lo
bash-5.1# ip route add 100.100.110.0/24 dev lo
bash-5.1# ip route add 100.100.120.0/24 dev lo
bash-5.1# ip route add 100.100.130.0/24 dev lo
bash-5.1# ip route add 100.100.140.0/24 dev lo
bash-5.1# ip route add 200.200.200.0/24 dev lo
bash-5.1# ip route add 200.200.210.0/24 dev lo
bash-5.1# ip route add 200.200.220.0/24 dev lo
bash-5.1# ip route add 200.200.230.0/24 dev lo
bash-5.1# ip route add 200.200.240.0/24 dev lo

vtysh
router0# conf t
router0(config)# router bgp 65000
router0(config-router)# network 100.100.100.0/24
router0(config-router)# network 100.100.110.0/24
router0(config-router)# network 100.100.120.0/24
router0(config-router)# network 100.100.130.0/24
router0(config-router)# network 100.100.140.0/24
router0(config-router)# network 200.200.200.0/24
router0(config-router)# network 200.200.210.0/24
router0(config-router)# network 200.200.220.0/24
router0(config-router)# network 200.200.230.0/24
router0(config-router)# network 200.200.240.0/24
```

### Cilium Version

cilium-cli: v0.16.7-40-g9316d0ac compiled with go1.22.2 on linux/amd64
cilium image (default): v1.15.5
cilium image (stable): v1.15.5
cilium image (running): 1.16.0-dev

### Kernel Version

$  uname -a
Linux hostname 6.5.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.15-enhanced-describe-dirty", GitCommit:"ac2e2baa7d4039cc4c68f2e869e4edbe2d60b305", GitTreeState:"dirty", BuildDate:"2023-03-02T00:33:46Z", GoVersion:"go1.20.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"30", GitVersion:"v1.30.0", GitCommit:"7c48c2bd72b9bf5c44d21d7338cc7bea77d0ad2a", GitTreeState:"clean", BuildDate:"2024-05-13T22:00:36Z", GoVersion:"go1.22.2", Compiler:"gc", Platform:"linux/amd64"}

### Regression

No

### Sysdump

_No response_

### Relevant log output

_No response_

### Anything else?

_No response_

### Cilium Users Document

- [X] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dswaffordcw**
Please ensure your pull request adheres to the following guidelines:

- [x] For first time contributors, read [Submitting a pull request](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#submitting-a-pull-request)
- [x] All code is covered by unit and/or runtime tests where feasible.
- [x] All commits contain a well written commit description including a title,
      description and a `Fixes: #XXX` line if the commit addresses a particular
      GitHub issue.
- [x] If your commit description contains a `Fixes: <commit-id>` tag, then
      please add the commit author[s] as reviewer[s] to this issue.
- [x] All commits are signed off. See the section [Developer’s Certificate of Origin](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#dev-coo)
- [x] Provide a title or release-note blurb suitable for the release notes.
- [x] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)
- [x] Thanks for contributing!

# BGPv1 and BGPv2 - Reject all inbound BGP advertisements

# Overview

Cilium's BGPv1 and BGPv2 Control Planes accepts all BGP Paths advertised to it.  However, these paths do not program the datapath. This PR modifies Cilium's BGP implementation to reject all inbound BGP advertisements.

The desire for this change is:
1) To reduce confusion by administrators of a Cilium installation.  When viewing `cilium bgp routes`, the current output, which shows all received BGP paths, gives the impression that these paths/routes are being used for routing by the CNI (programmed into the dataplane).  For Cilium, this is not true and they are simply ignored.

2) To move a potential failure point in Cilium's BGP stack.  In the BGPv[1|2] implementation, a [GoBGP](https://github.com/osrg/gobgp) server is instantiated by Cilium's directly in Go.  It does not run as an external process.  If GoBGP experiences a memory leak or panic, it has the potential to disrupt Cilium as well.  One point of failure that I've seen in the past is when using GoBGP in environments containing millions of BGP paths.  While it's an unlikely use case for a CNI, the potential exists that one could try to pass full Internet tables into their CNI.  As these are unused, it would be ideal to drop them.

# Description
This PR configures a global `IMPORT` routing policy just after starting Cilium's internal [GoBGP](https://github.com/osrg/gobgp/tree/master) instance.  The policy rejects all paths.  Due to GoBGP specifics, the global import policy configured includes "permit local routes" sub-policy (see this PR's comment thread).  That was required because early testing of the change without the local route exception resulted in filtering ALL announcements, including Cilium's own outbound announcements.

* In `pkg/bgpv1/gobgp/server.go`, a top-level variable named `allowLocalPolicy` was added.  This defines a sub-policy containing the local route exception described above.
* In `pkg/bgpv1/gobgp/server.go`,  at approximately line 113, just after calling `StartBgp()`, the internal GoBGP server's `AddPolicy()` is called to configure the sub-policy containing the local route exception described above.
* In `pkg/bgpv1/gobgp/server.go`,  at approximately line 117, the internal GoBGP server's `SetPolicyAssignment()` is called to configure the global import policy.

During testing, it was observed that calling `SetPolicyAssignment()` prior to calling  `StartBgp()` resulted in a deadlock.  The call never returned.

# Testing

## Manual Testing - Setup

For testing of this change, I first referenced https://docs.cilium.io/en/latest/contributing/development/bgp_cplane/ to bring up a local Kind K8s cluster with Cilium.  The exact steps were:

```
make kind-bgp-v4

KIND_CLUSTER_NAME=bgp-cplane-dev-v4 make kind-image
cilium install --chart-directory install/kubernetes/cilium -f contrib/containerlab/bgp-cplane-dev-v4/values.yaml --set image.override="localhost:5000/cilium/cilium-dev:local" --set image.pullPolicy=Never --set operator.image.override="localhost:5000/cilium/operator-generic:local" --set operator.image.pullPolicy=Never
```

Next, I brought up a "hello world" service using:
```
kubectl create deployment hello-node --image=registry.k8s.io/e2e-test-images/agnhost:2.39 -- /agnhost netexec --http-port=8080

kubectl expose deployment hello-node --type=LoadBalancer --port=8080
```

## Manual Testing - BGPv1

The following configuration (`bgpp.yaml`) was applied to configure BGP peers using Cilium's BGPv1 Control Plane:

```
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: control-plane
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: bgp-cplane-dev-v4-control-plane
  virtualRouters:
  - localASN: 65001
    neighbors:
    - peerASN: 65000
      peerAddress: 10.0.1.1/32
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: worker
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: bgp-cplane-dev-v4-worker
  virtualRouters:
  - localASN: 65002
    #exportPodCIDR: true
    serviceSelector:
      #matchLabels:
      #  name: hello-node
      matchExpressions:
       - { key: app, operator: In, values: [hello-node, hello-node2, hello-node3] }
    serviceAdvertisements:
      - LoadBalancerIP # <-- default
      #- ClusterIP      # <-- options
      #- ExternalIP     # <-- options
    neighbors:
    - peerASN: 65000
      peerAddress: 10.0.2.1/32
      #holdTimeSeconds: 180
      #keepAliveTimeSeconds: 60
      #eBGPMultihopTTL: 1
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 60
      advertisedPathAttributes:
      - selectorType: CiliumLoadBalancerIPPool
        selector:
          matchLabels:
            environment: mgmt
        communities:
          standard:
          - 65002:100
          large:
          - 65002:100:1
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "mgmt"
  labels:
    environment: mgmt
spec:
  blocks:
    - cidr: "100.64.8.0/22"
  cidrs:
    - cidr: "100.64.12.0/22"
  #serviceSelector:
  #  matchExpressions:
  #    - {key: app, operator: In, values: [hello-node]}
---
```

Then, in the FRR container (`clab-bgp-cplane-dev-v4-router0`), I added additional routes and advertised those into BGP using:
```

docker exec -ti clab-bgp-cplane-dev-v4-router0 bash

bash-5.1# ip route add 100.100.100.0/24 dev lo
bash-5.1# ip route add 100.100.110.0/24 dev lo
bash-5.1# ip route add 100.100.120.0/24 dev lo
bash-5.1# ip route add 100.100.130.0/24 dev lo
bash-5.1# ip route add 100.100.140.0/24 dev lo

bash-5.1# vtysh

Hello, this is FRRouting (version 8.4_git).
Copyright 1996-2005 Kunihiro Ishiguro, et al.

router0# conf t
router0(config)# router bgp 65000
router0(config-router)# network 100.100.100.0/24
router0(config-router)# network 100.100.110.0/24
router0(config-router)# network 100.100.120.0/24
router0(config-router)# network 100.100.130.0/24
router0(config-router)# network 100.100.140.0/24
```

These were observed in:
```
router0# show ip bgp
...
   Network          Next Hop            Metric LocPrf Weight Path
*> 100.64.12.1/32   10.0.2.2                               0 65002 i
*> 100.100.100.0/24 0.0.0.0                  0         32768 i
*> 100.100.110.0/24 0.0.0.0                  0         32768 i
*> 100.100.120.0/24 0.0.0.0                  0         32768 i
*> 100.100.130.0/24 0.0.0.0                  0         32768 i
*> 100.100.140.0/24 0.0.0.0                  0         32768 i
```

[**BEFORE**] On Cilium's side, before this PR, these were observed in:
```
$  cilium bgp peers
Node                              Local AS   Peer AS   Peer Address   Session State   Uptime   Family         Received   Advertised
bgp-cplane-dev-v4-control-plane   65001      65000     10.0.1.1       established     7m42s    ipv4/unicast   6          0
                                                                                               ipv6/unicast   0          0
bgp-cplane-dev-v4-worker          65002      65000     10.0.2.1       established     7m40s    ipv4/unicast   6          2
                                                                                               ipv6/unicast   0          1


$  cilium bgp routes
(Defaulting to vailable ipv4 unicastroutes, please see help for more options)

Node                              VRouter   Prefix             NextHop    Age     Attrs
bgp-cplane-dev-v4-control-plane   65001     100.100.100.0/24   10.0.1.1   4m19s   [{Origin: i} {AsPath: 65000} {Nexthop: 10.0.1.1} {Med: 0}]
                                  65001     100.100.110.0/24   10.0.1.1   4m16s   [{Origin: i} {AsPath: 65000} {Nexthop: 10.0.1.1} {Med: 0}]
                                  65001     100.100.120.0/24   10.0.1.1   4m15s   [{Origin: i} {AsPath: 65000} {Nexthop: 10.0.1.1} {Med: 0}]
                                  65001     100.100.130.0/24   10.0.1.1   3m15s   [{Origin: i} {AsPath: 65000} {Nexthop: 10.0.1.1} {Med: 0}]
                                  65001     100.100.140.0/24   10.0.1.1   3m29s   [{Origin: i} {AsPath: 65000} {Nexthop: 10.0.1.1} {Med: 0}]
                                  65001     100.64.12.1/32     10.0.1.1   7m38s   [{Origin: i} {AsPath: 65000 65002} {Nexthop: 10.0.1.1} {Communities: 65002:100} {LargeCommunity: [ 65002:100:1]}]
bgp-cplane-dev-v4-worker          65002     100.100.100.0/24   10.0.2.1   4m19s   [{Origin: i} {AsPath: 65000} {Nexthop: 10.0.2.1} {Med: 0}]
                                  65002     100.100.110.0/24   10.0.2.1   4m16s   [{Origin: i} {AsPath: 65000} {Nexthop: 10.0.2.1} {Med: 0}]
                                  65002     100.100.120.0/24   10.0.2.1   4m15s   [{Origin: i} {AsPath: 65000} {Nexthop: 10.0.2.1} {Med: 0}]
                                  65002     100.100.130.0/24   10.0.2.1   3m15s   [{Origin: i} {AsPath: 65000} {Nexthop: 10.0.2.1} {Med: 0}]
                                  65002     100.100.140.0/24   10.0.2.1   3m29s   [{Origin: i} {AsPath: 65000} {Nexthop: 10.0.2.1} {Med: 0}]
                                  65002     100.64.12.1/32     0.0.0.0    7m38s   [{Origin: i} {Nexthop: 0.0.0.0}]
```

[**AFTER**] On Cilium's side with this PR, I saw:
```
$  cilium bgp routes
(Defaulting to `available ipv4 unicast` routes, please see help for more options)

Node                       VRouter   Prefix           NextHop   Age     Attrs
bgp-cplane-dev-v4-worker   65002     100.64.12.1/32   0.0.0.0   2m34s   [{Origin: i} {Nexthop: 0.0.0.0}]
```

**Inspecting Cilium using `cilium-dbg` on `bgp-cplane-dev-v4-worker`:**
```
root@bgp-cplane-dev-v4-worker:/home/cilium# cilium-dbg bgp peers
Local AS   Peer AS   Peer Address   Session       Uptime   Family         Received   Advertised
65002      65000     10.0.2.1:179   established   4m13s    ipv4/unicast   6          2
                                                           ipv6/unicast   0          1

root@bgp-cplane-dev-v4-worker:/home/cilium# cilium-dbg bgp route-policies
VRouter   Policy Name                                   Type     Match Peers   Match Prefixes (Min..Max Len)                        RIB Action   Path Actions
65002     10.0.2.1/32-CiliumLoadBalancerIPPool-cae...   export   10.0.2.1/32   {100.64.8.0/22 (32..32)} {100.64.12.0/22 (32..32)}   none         {AddCommunities: [65002:100]} {AddLargeCommunities: [65002:100:1]}
65002     10.0.2.1/32-import                            import   10.0.2.1/32                                                        reject

root@bgp-cplane-dev-v4-worker:/home/cilium# cilium-dbg bgp routes
(Defaulting to `available ipv4 unicast` routes, please see help for more options)

VRouter   Prefix           NextHop   Age     Attrs
65002     100.64.12.1/32   0.0.0.0   4m25s   [{Origin: i} {Nexthop: 0.0.0.0}]
```

**Inspecting Cilium using `cilium-dbg` on `bgp-cplane-dev-v4-control-plane`:**
```
$  k exec cilium-lrmbw -n kube-system bash -ti
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.

root@bgp-cplane-dev-v4-control-plane:/home/cilium# cilium bgp peers
Local AS   Peer AS   Peer Address   Session       Uptime   Family         Received   Advertised
65001      65000     10.0.1.1:179   established   4m56s    ipv4/unicast   6          0
                                                           ipv6/unicast   0          0

root@bgp-cplane-dev-v4-control-plane:/home/cilium# cilium bgp route-policies
VRouter   Policy Name          Type     Match Peers   Match Prefixes (Min..Max Len)   RIB Action   Path Actions
65001     10.0.1.1/32-import   import   10.0.1.1/32                                   reject
root@bgp-cplane-dev-v4-control-plane:/home/cilium# cilium bgp routes
(Defaulting to `available ipv4 unicast` routes, please see help for more options)

VRouter   Prefix   NextHop   Age   Attrs
```

[**AFTER**] Inspecting Cilium's advertised BGP route on the FRR container:
```
router0# show ip bgp
BGP table version is 6, local router ID is 10.0.0.1, vrf id 0
Default local pref 100, local AS 65000
Status codes:  s suppressed, d damped, h history, * valid, > best, = multipath,
               i internal, r RIB-failure, S Stale, R Removed
Nexthop codes: @NNN nexthop's vrf id, < announce-nh-self
Origin codes:  i - IGP, e - EGP, ? - incomplete
RPKI validation codes: V valid, I invalid, N Not found

   Network          Next Hop            Metric LocPrf Weight Path
*> 100.64.12.1/32   10.0.2.2                               0 65002 i
*> 100.100.100.0/24 0.0.0.0                  0         32768 i
*> 100.100.110.0/24 0.0.0.0                  0         32768 i
*> 100.100.120.0/24 0.0.0.0                  0         32768 i
*> 100.100.130.0/24 0.0.0.0                  0         32768 i
*> 100.100.140.0/24 0.0.0.0                  0         32768 i

Displayed  6 routes and 6 total paths
router0# show ip bgp 100.64.12.1/32
BGP routing table entry for 100.64.12.1/32, version 1
Paths: (1 available, best #1, table default)
  Advertised to non peer-group peers:
  10.0.1.2 10.0.2.2
  65002
    10.0.2.2 from 10.0.2.2 (10.0.2.2)
      Origin IGP, valid, external, best (First path received)
      Community: 65002:100
      Large Community: 65002:100:1
      Last update: Tue Jun 11 02:09:53 2024
```

## Manual Testing - BGPv2

For testing BGPv2, I nuked the test environment.  Then, I applied the following `bgpp.yaml`:

```
$  cat bgppv2.yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: bgp-cplane-dev-v4-control-plane
  bgpInstances:
  - name: "control-plane"
    localASN: 65001
    peers:
    - name: "frr"
      peerASN: 65000
      peerAddress: 10.0.1.1
      peerConfigRef:
        name: "cilium-cp-frr-peer"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: "cilium-cp-frr-peer"
spec:
  transport:
    localPort: 179
    peerPort: 179
  #timers:
  #  connectRetryTimeSeconds: 12
  #  holdTimeSeconds: 9
  #  keepAliveTimeSeconds: 3
  #authSecretRef: bgp-auth-secret
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgp"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: "bgp-advertisements"
  labels:
    advertise: "bgp"
spec:
  advertisements:
    #- advertisementType: "LoadBalancerIP"
    - advertisementType: "PodCIDR"
      #serviceSelector:
      #matchLabels:
      #  name: hello-node
      #  matchExpressions:
      #  - { key: app, operator: In, values: [hello-node, hello-node2, hello-node3] }
      attributes:
        communities:
          standard: [ "65001:100" ]
        localPreference: 99
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "mgmt"
  labels:
    environment: mgmt
spec:
  blocks:
    - cidr: "100.64.8.0/22"
  cidrs:
    - cidr: "100.64.12.0/22"
---
```

**Testing with a local build of cilium-dbg**
```
root@bgp-cplane-dev-v4-control-plane:/home/cilium# /tmp/cilium-dbg bgp peers
Local AS   Peer AS   Peer Address   Session       Uptime   Family         Received   Accepted   Advertised
65001      65000     10.0.1.1:179   established   4m48s    ipv4/unicast   11         10         2


root@bgp-cplane-dev-v4-control-plane:/home/cilium# /tmp/cilium-dbg bgp routes
(Defaulting to `available ipv4 unicast` routes, please see help for more options)

VRouter   Prefix        NextHop   Age     Attrs
65001     10.1.0.0/24   0.0.0.0   4m59s   [{Origin: i} {Nexthop: 0.0.0.0}]
```

**Testing with cilium CLI**
```
$  cilium bgp peers
Node                              Local AS   Peer AS   Peer Address   Session State   Uptime   Family         Received   Advertised
bgp-cplane-dev-v4-control-plane   65001      65000     10.0.1.1       established     11m19s   ipv4/unicast   11         2

$  cilium bgp routes
(Defaulting to `available ipv4 unicast` routes, please see help for more options)

Node                              VRouter   Prefix        NextHop   Age      Attrs
bgp-cplane-dev-v4-control-plane   65001     10.1.0.0/24   0.0.0.0   11m30s   [{Origin: i} {Nexthop: 0.0.0.0}]
```

**Inspecting the FRR container**
```
router0# show ip bgp
BGP table version is 11, local router ID is 10.0.0.1, vrf id 0
Default local pref 100, local AS 65000
Status codes:  s suppressed, d damped, h history, * valid, > best, = multipath,
               i internal, r RIB-failure, S Stale, R Removed
Nexthop codes: @NNN nexthop's vrf id, < announce-nh-self
Origin codes:  i - IGP, e - EGP, ? - incomplete
RPKI validation codes: V valid, I invalid, N Not found

   Network          Next Hop            Metric LocPrf Weight Path
*> 10.1.0.0/24      10.0.1.2                               0 65001 i
*> 100.100.100.0/24 0.0.0.0                  0         32768 i
*> 100.100.110.0/24 0.0.0.0                  0         32768 i
*> 100.100.120.0/24 0.0.0.0                  0         32768 i
*> 100.100.130.0/24 0.0.0.0                  0         32768 i
*> 100.100.140.0/24 0.0.0.0                  0         32768 i
*> 200.200.200.0/24 0.0.0.0                  0         32768 i
*> 200.200.210.0/24 0.0.0.0                  0         32768 i
*> 200.200.220.0/24 0.0.0.0                  0         32768 i
*> 200.200.230.0/24 0.0.0.0                  0         32768 i
*> 200.200.240.0/24 0.0.0.0                  0         32768 i

Displayed  11 routes and 11 total paths
router0# show ip bgp 10.1.0.0/24
BGP routing table entry for 10.1.0.0/24, version 1
Paths: (1 available, best #1, table default)
  Advertised to non peer-group peers:
  10.0.1.2
  65001
    10.0.1.2 from 10.0.1.2 (10.0.1.2)
      Origin IGP, valid, external, best (First path received)
      Community: 65001:100
      Last update: Sat Jun 15 00:10:53 2024
```

The configuration applied to the FRR container to inject 10 additional routes was:
```
ip route add 100.100.100.0/24 dev lo
ip route add 100.100.110.0/24 dev lo
ip route add 100.100.120.0/24 dev lo
ip route add 100.100.130.0/24 dev lo
ip route add 100.100.140.0/24 dev lo
ip route add 200.200.200.0/24 dev lo
ip route add 200.200.210.0/24 dev lo
ip route add 200.200.220.0/24 dev lo
ip route add 200.200.230.0/24 dev lo
ip route add 200.200.240.0/24 dev lo

vtysh
conf t
router bgp 65000
network 100.100.100.0/24
network 100.100.110.0/24
network 100.100.120.0/24
network 100.100.130.0/24
network 100.100.140.0/24
network 200.200.200.0/24
network 200.200.210.0/24
network 200.200.220.0/24
network 200.200.230.0/24
network 200.200.240.0/24
exit
exit
```

## Unit Tests

* Existing tests from `pkg/bgpv1/gobgp/server_test.go` were updated to exclude the global import policy when evaluating results.
* A new test named `TestGlobalImportPolicy()` was added to verify the global import policy.  This test calls the internal GoBGP server directly, instead of `router.GetRoutePolicies()` which returns only the sub-policy for local routes.

Fixes: #32826

```release-note
BGPv1 and BGPv2 - Reject all inbound BGP advertisements
```

### CODE REVIEW

**Comment by dswaffordcw** [comment]
@harsimran-pabla
I am seeing something that looks off in my testing.  I thought this was just about ready, aside from one test.  But, one aspect looks like it may be a regression.  I'm not sure.

With the BGP development environment (containerlab via `make kind-bgp-v4`), on `main` and recently rebased against upstream I see:
```
$  cilium bgp routes
(Defaulting to `available ipv4 unicast` routes, please see help for more options)

Node                              VRouter   Prefix           NextHop    Age   Attrs
bgp-cplane-dev-v4-control-plane   65001     100.64.12.1/32   10.0.1.1   6s    [{Origin: i} {AsPath: 65000 65002} {Nexthop: 10.0.1.1} {Communities: 65002:100} {LargeCommunity: [ 65002:100:1]}]
bgp-cplane-dev-v4-worker          65002     100.64.12.1/32   0.0.0.0    14s   [{Origin: i} {Nexthop: 0.0.0.0}]
```

This is taken before announcing any routes toward Cilium from the FRR container.  It was configured w/ the `bgpp.yaml` below.  On this PR, I see only:
```
$  cilium bgp routes
(Defaulting to vailable ipv4 unicastroutes, please see help for more options)

Node                       VRouter   Prefix           NextHop   Age     Attrs
bgp-cplane-dev-v4-worker   65002     100.64.12.1/32   0.0.0.0   21m5s   [{Origin: i} {Nexthop: 0.0.0.0}]

```

The route that was previously announced by `bgp-cplane-dev-v4-control-plane` no longer exists.

I *think* each instance of Cilium is announcing its own paths directly to it's configured peer(s).  It looks to me though that the instance of `bgp-cplane-dev-v4-worker ` is peered with `bgp-cplane-dev-v4-control-plane` internally and is also announcing the same path to it.  With my PR, that internal announcement is not being accepted.  Does it need to be?

```
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: control-plane
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: bgp-cplane-dev-v4-control-plane
  virtualRouters:
  - localASN: 65001
    neighbors:
    - peerASN: 65000
      peerAddress: 10.0.1.1/32
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: worker
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: bgp-cplane-dev-v4-worker
  virtualRouters:
  - localASN: 65002
    #exportPodCIDR: true
    serviceSelector:
      #matchLabels:
      #  name: hello-node
      matchExpressions:
       - { key: app, operator: In, values: [hello-node, hello-node2, hello-node3] }
    serviceAdvertisements:
      - LoadBalancerIP # <-- default
      #- ClusterIP      # <-- options
      #- ExternalIP     # <-- options
    neighbors:
    - peerASN: 65000
      peerAddress: 10.0.2.1/32
      #holdTimeSeconds: 180
      #keepAliveTimeSeconds: 60
      #eBGPMultihopTTL: 1
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 60
      advertisedPathAttributes:
      - selectorType: CiliumLoadBalancerIPPool
        selector:
          matchLabels:
            environment: mgmt
        communities:
          standard:
          - 65002:100
          large:
          - 65002:100:1
          #wellknown:
          #- no-export
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "mgmt"
  labels:
    environment: mgmt
spec:
  blocks:
    - cidr: "100.64.8.0/22"
  cidrs:
    - cidr: "100.64.12.0/22"
```

**Comment by dswaffordcw** [comment]
@harsimran-pabla Replying to my last comment, I think the missing route is actually the original from `bgp-cplane-dev-v4-worker` being re-advertised by the FRR container back toward Cilium's `bgp-cplane-dev-v4-control-plane` instance.   I'll do more testing tomorrow to confirm.

**Comment by rastislavs** [comment]
Hi @dswaffordcw , thanks a lot for this PR, I think it makes a lot of sense to filter inbound advertisements while we don't need them. 

However, instead of doing that per neighbor, I think it would be better to just change the default import policy to reject the routes - see [GoBGP Policy docs - 4.1 Attach policy to global rib](https://github.com/osrg/gobgp/blob/master/docs/sources/policy.md#4-attaching-policy) - the equivalent of:
```
default-import-policy = "reject-route"
```

This way we can save some processing on the number of policies in case of many neighbors, and future-wise, we can still enable import per-neighbor if we need to implement such a feature.

You will probably need to add a Policy Assignment in the import direction like here: https://github.com/cilium/cilium/blob/main/pkg/bgpv1/gobgp/server.go#L186

**Comment by dswaffordcw** [comment]
> Hi @dswaffordcw , thanks a lot for this PR, I think it makes a lot of sense to filter inbound advertisements while we don't need them.
> 
> However, instead of doing that per neighbor, I think it would be better to just change the default import policy to reject the routes - see [GoBGP Policy docs - 4.1 Attach policy to global rib](https://github.com/osrg/gobgp/blob/master/docs/sources/policy.md#4-attaching-policy) - the equivalent of:
> 
> ```
> default-import-policy = "reject-route"
> ```
> 
> This way we can save some processing on the number of policies in case of many neighbors, and future-wise, we can still enable import per-neighbor if we need to implement such a feature.
> 
> You will probably need to add a Policy Assignment in the import direction like here: https://github.com/cilium/cilium/blob/main/pkg/bgpv1/gobgp/server.go#L186

Thanks @rastislavs!  That's a good suggestion.  I'll update the PR and let you know when it's ready to look over again.

**Comment by dswaffordcw** [comment]
@rastislavs I fought through this all day and am at a wall.  I've figured out how to configure the global policy but GoBGP is not handling it as expected.

Could you look through this and let me know your thoughts?

In https://github.com/cilium/cilium/pull/33035/commits/8714116f8d16df121cacfb8ac85704618ad3c15c, I believe that is the correct way to configure the global policies.  However, it is silently ignored.  I found another report last December of the same in https://github.com/osrg/gobgp/issues/1768#issuecomment-1839399167.  I logged a new issue under https://github.com/osrg/gobgp/issues/2814.

Then, I walked through GoBGP's configuration file parsing code.  It configures the default in a different way (see https://github.com/osrg/gobgp/blob/master/pkg/config/config.go#L45).  I did that in https://github.com/cilium/cilium/pull/33035/commits/f028b2bf5e63e0227fb748ce2c491d2497e84200 using `SetPolicyAssignment()` but that too is not working correctly.  With that commit in place, I see the following:

```
$  cilium bgp peers
Node                              Local AS   Peer AS   Peer Address   Session State   Uptime   Family         Received   Advertised
bgp-cplane-dev-v4-control-plane   65001      65000     10.0.1.1       established     9m12s    ipv4/unicast   0          0
                                                                                               ipv6/unicast   0          0
bgp-cplane-dev-v4-worker          65002      65000     10.0.2.1       established     9m14s    ipv4/unicast   0          1
                                                                                               ipv6/unicast   0          1

00x0 dswafford@dswafford-2 2024/06/11 17:00:49
☸︎ kind-bgp-cplane-dev-v4:
> cilium-fork on  GH32826-import-none [$]
$  cilium bgp routes
(Defaulting to `available ipv4 unicast` routes, please see help for more options)

Node   VRouter   Prefix   NextHop   Age   Attrs

```

And on the FRR instance, no paths/routes:

```
router0# show ip bgp sum

IPv4 Unicast Summary (VRF default):
BGP router identifier 10.0.0.1, local AS number 65000 vrf-id 0
BGP table version 0
RIB entries 0, using 0 bytes of memory
Peers 2, using 1434 KiB of memory
Peer groups 1, using 64 bytes of memory

Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt Desc
10.0.1.2        4      65001        21        21        0    0    0 00:09:35            0        0 N/A
10.0.2.2        4      65002        23        22        0    0    0 00:09:37            0        0 N/A

Total number of neighbors 2
router0# show ip bgp
No BGP prefixes displayed, 0 exist
```

**Comment by rastislavs** [comment]
Hi @dswaffordcw,

> I fought through this all day

Sorry to hear that, but I can understand it - GoBGP can be a bit tricky, you almost always need to look into source code to understand the details.

> I did that in https://github.com/cilium/cilium/commit/f028b2bf5e63e0227fb748ce2c491d2497e84200 using SetPolicyAssignment()

Yeah, that is what I suggested in my first comment. That is the correct way to do it.

> but that too is not working correctly

So I looked into the source code :) and it seems that GoBGP applies policies also on locally installed routes, see:

`AddPath` calls `addPathList`: https://github.com/osrg/gobgp/blob/master/pkg/server/server.go#L2269
`addPathList` calls `propagateUpdate`: https://github.com/osrg/gobgp/blob/master/pkg/server/server.go#L2242
`propagateUpdate` calls `ApplyPolicy`: https://github.com/osrg/gobgp/blob/master/pkg/server/server.go#L1224

The solution is to add an import policy that allows local routes. Something like this seems to be working for me:

```diff
diff --git a/pkg/bgpv1/gobgp/server.go b/pkg/bgpv1/gobgp/server.go
index ab8a2ba52b..45088080da 100644
--- a/pkg/bgpv1/gobgp/server.go
+++ b/pkg/bgpv1/gobgp/server.go
@@ -74,7 +74,7 @@ func NewGoBGPServer(ctx context.Context, log *logrus.Entry, params types.ServerP
 		SubSys:    "bgp-control-plane",
 	})

-	s := server.NewBgpServer(server.LoggerOption(logger))
+	s := server.NewBgpServer(server.LoggerOption(logger), server.GrpcListenAddress("0.0.0.0:50051"))
 	go s.Serve()

 	startReq := &gobgp.StartBgpRequest{
@@ -95,11 +95,40 @@ func NewGoBGPServer(ctx context.Context, log *logrus.Entry, params types.ServerP
 		return nil, fmt.Errorf("failed starting BGP server: %w", err)
 	}

+	allowLocalPolicy := &gobgp.Policy{
+		Name: "allow-local",
+		Statements: []*gobgp.Statement{
+			{
+				Conditions: &gobgp.Conditions{
+					RouteType: gobgp.Conditions_ROUTE_TYPE_LOCAL,
+				},
+				Actions: &gobgp.Actions{
+					RouteAction: gobgp.RouteAction_ACCEPT,
+				},
+			},
+		},
+	}
+	err := s.AddPolicy(ctx, &gobgp.AddPolicyRequest{Policy: allowLocalPolicy})
+	if err != nil {
+		return nil, fmt.Errorf("failed to add %s policy: %w", allowLocalPolicy.Name, err)
+	}
+	err = s.SetPolicyAssignment(ctx, &gobgp.SetPolicyAssignmentRequest{
+		Assignment: &gobgp.PolicyAssignment{
+			Name:          globalPolicyAssignmentName,
+			Direction:     gobgp.PolicyDirection_IMPORT,
+			DefaultAction: gobgp.RouteAction_REJECT,
+			Policies:      []*gobgp.Policy{allowLocalPolicy},
+		},
+	})
+	if err != nil {
+		return nil, fmt.Errorf("failed configuring BGP server's global import policy: %w", err)
+	}
+
 	// will log out any peer changes.
 	watchRequest := &gobgp.WatchEventRequest{
 		Peer: &gobgp.WatchEventRequest_Peer{},
 	}
-	err := s.WatchEvent(ctx, watchRequest, func(r *gobgp.WatchEventResponse) {
+	err = s.WatchEvent(ctx, watchRequest, func(r *gobgp.WatchEventResponse) {
 		if p := r.GetPeer(); p != nil && p.Type == gobgp.WatchEventResponse_PeerEvent_STATE {
 			logger.l.Debug(p)
 		}
```

Note that I temporarily configured `GrpcListenAddress` on the server so that I can debug this with `gobgp` CLI, it might be helpful for you as well - e.g. this is the result of running the above code:

```
$ gobgp --host 172.18.0.2 global policy
Import policy:
    Default: REJECT
    Name allow-local:
        StatementName allow-local_stmt0:
          Conditions:
            Route Type: local
          Actions:
             accept
```

**Comment by dswaffordcw** [comment]
Thanks @rastislavs!  That worked!

One follow-up Q, I'd like to include an update the `cilium-dbg` and `cilium` CLIs to distinguish between "Received" and "Accepted" route counts when looking at `cilium bgp peers`.  I thought this change would do it, but it too didn't work :-D!  Thoughts on where I should look next?

```
$  git diff
diff --git a/cilium-dbg/cmd/bgp_peer_get.go b/cilium-dbg/cmd/bgp_peer_get.go
index b40978ee3f..5168d06326 100644
--- a/cilium-dbg/cmd/bgp_peer_get.go
+++ b/cilium-dbg/cmd/bgp_peer_get.go
@@ -54,7 +54,7 @@ func printSummary(peers []*models.BgpPeer) {
                return peers[i].LocalAsn < peers[j].LocalAsn || peers[i].PeerAddress < peers[j].PeerAddress
        })

-       fmt.Fprintln(w, "Local AS\tPeer AS\tPeer Address\tSession\tUptime\tFamily\tReceived\tAdvertised")
+       fmt.Fprintln(w, "Local AS\tPeer AS\tPeer Address\tSession\tUptime\tFamily\tReceived\tAccepted\tAdvertised")
        for _, peer := range peers {
                fmt.Fprintf(w, "%d\t", peer.LocalAsn)
                fmt.Fprintf(w, "%d\t", peer.PeerAsn)
@@ -72,6 +72,7 @@ func printSummary(peers []*models.BgpPeer) {
                        // AFI and SAFI are concatenated for brevity
                        fmt.Fprintf(w, "%s/%s\t", afisafi.Afi, afisafi.Safi)
                        fmt.Fprintf(w, "%d\t", afisafi.Received)
+                       fmt.Fprintf(w, "%d\t", afisafi.Accepted)
                        fmt.Fprintf(w, "%d\t", afisafi.Advertised)
                        fmt.Fprintf(w, "\n")
                }
```

After building and copying that into one of the cilium containers, I saw:
```
root@bgp-cplane-dev-v4-control-plane:/home/cilium# /tmp/cilium-dbg-david bgp peers
Local AS   Peer AS   Peer Address   Session       Uptime     Family         Received   Accepted   Advertised
65001      65000     10.0.1.1:179   established   1h51m22s   ipv4/unicast   10         10         0
                                                             ipv6/unicast   0          0          0
root@bgp-cplane-dev-v4-control-plane:/home/cilium# /tmp/cilium-dbg-david bgp routes
(Defaulting to `available ipv4 unicast` routes, please see help for more options)

VRouter   Prefix   NextHop   Age   Attrs
root@bgp-cplane-dev-v4-control-plane:/home/cilium# /tmp/cilium-dbg-david bgp route-policies
VRouter   Policy Name   Type     Match Peers   Match Prefixes (Min..Max Len)   RIB Action   Path Actions
65001     allow-local   import                                                 accept
```

I was expecting to see 0 for "Accepted".  It looks like the response that comes back through the API's `client.Bgp.GetBgpPeers()` is unaware of the global policies and their effect.

**Comment by rastislavs** [comment]
@dswaffordcw 
> I'd like to include an update the cilium-dbg and cilium CLIs to distinguish between "Received" and "Accepted" route counts when looking at cilium bgp peers. I thought this change would do it, but it too didn't work 

Interesting, in my setup your proposed CLI change seems to be working fine - it matches the output of `gobgp neighbor`:

```
gobgp --host 172.18.0.2 neighbor
Peer         AS  Up/Down State       |#Received  Accepted
172.0.0.1 65000 00:02:05 Establ      |        2         1
```

```
cilium-dbg bgp peers
Local AS   Peer AS   Peer Address    Session       Uptime   Family         Received   Accepted   Advertised
65001      65000     172.0.0.1:179   established   2m32s    ipv4/unicast   2          1          1
                                                            ipv6/unicast   0          0          0
```

Could you check what `gobgp neighbor` returns in your case?

**Comment by dswaffordcw** [comment]
Hey @rastislavs

They match for me as well.   With adding the global policy to reject all routes, I was expected to see "Accepted: 0".  Though, technically this is correct.  The per-neighbor policies accepted the routes and they are being rejected later on.

I am not seeing a way to extract the fact that "Neighbor X's routes were later rejected by the global import policy".  Do you think this is worth pursuing further?  One idea for now, is that we add the "Accepted" column but statically set the value to 0.  My desire is to eliminate confusion -- by making it clear that Cilium does nothing with received routes.


```
root@bgp-cplane-dev-v4-control-plane:/home/cilium# /tmp/gobgp neigh
Peer        AS  Up/Down State       |#Received  Accepted
10.0.1.1 65000 00:20:25 Establ      |        6         6

root@bgp-cplane-dev-v4-control-plane:/home/cilium# /tmp/gobgp global rib
Network not in table
root@bgp-cplane-dev-v4-control-plane:/home/cilium#

root@bgp-cplane-dev-v4-control-plane:/home/cilium# /tmp/gobgp global rib summary
Table afi:AFI_IP  safi:SAFI_UNICAST
Destination: 0, Path: 0
root@bgp-cplane-dev-v4-control-plane:/home/cilium#
```

```
root@bgp-cplane-dev-v4-control-plane:/home/cilium# cilium-dbg bgp peers
Local AS   Peer AS   Peer Address   Session       Uptime   Family         Received   Accepted   Advertised
65001      65000     10.0.1.1:179   established   21m16s   ipv4/unicast   6          6          0
                                                           ipv6/unicast   0          0          0

root@bgp-cplane-dev-v4-control-plane:/home/cilium# cilium-dbg bgp routes
(Defaulting to `available ipv4 unicast` routes, please see help for more options)

VRouter   Prefix   NextHop   Age   Attrs
```

**Comment by rastislavs** [comment]
Hi @dswaffordcw 

> They match for me as well. With adding the global policy to reject all routes, I was expected to see "Accepted: 0". Though, technically this is correct. The per-neighbor policies accepted the routes and they are being rejected later on.

Right, it seems the "Accepted" stats for a peer are sourced from adj-rib-in state: https://github.com/osrg/gobgp/blob/master/pkg/server/server.go#L3092
which is before the import policies are applied. 

I checked how FRR displays "accepted" stats for BGP peers, if you filter-out incoming routes via a route-map, and it also shows the routes that do not get into route table in the "accepted" counter in the "sh bgp neighbors" output - so at least it is consistent.

>  Do you think this is worth pursuing further? One idea for now, is that we add the "Accepted" column but statically set the value to 0.

I would not do this - I think we should be consistent with gobgp stats, but more importantly, it will become an issue once we actually start importing routes. I think for now the best option probably is to keep just the Received and Advertised columns.

File: pkg/bgpv1/gobgp/server.go [hunk 1]
```diff
@@ -95,11 +110,27 @@ func NewGoBGPServer(ctx context.Context, log *logrus.Entry, params types.ServerP
 		return nil, fmt.Errorf("failed starting BGP server: %w", err)
 	}
 
+	if err := s.AddPolicy(ctx, &gobgp.AddPolicyRequest{Policy: allowLocalPolicy}); err != nil {
```
Comment (rastislavs) [inline pkg/bgpv1/gobgp/server.go:118]: Could you add a comment on why this policy & policy assignment are needed ad what they do?

File: pkg/bgpv1/gobgp/server.go [hunk 2]
```diff
@@ -22,6 +22,7 @@ const (
 	// idleHoldTimeAfterResetSeconds defines time BGP session will stay idle after neighbor reset.
 	idleHoldTimeAfterResetSeconds = 5
 
+	globalAllowLocalPolicyName = "allow-local"
```
Comment (rastislavs) [inline pkg/bgpv1/gobgp/server.go:27]: could you add a comment here?

**Comment by rastislavs** [comment]
@dswaffordcw please note that this change now affects BGPv2 as well, could you please test with BGPv2 enabled, and update the title & release note accordingly?

**Comment by dswaffordcw** [comment]
@rastislavs Testing for BGPv2 --

Using only a BGPv2 configuration, I see the same result as with BGPv1.  I advertised 10 BGP paths from an FRR instance toward Cilium and all were rejected.  Cilium continued to announce a path toward FRR and FRR accepted it.

I'll update the PR's description to include this as well.

Here's  the `bgpp.yaml` I used:
```
$  cat bgppv2.yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: bgp-cplane-dev-v4-control-plane
  bgpInstances:
  - name: "control-plane"
    localASN: 65001
    peers:
    - name: "frr"
      peerASN: 65000
      peerAddress: 10.0.1.1
      peerConfigRef:
        name: "cilium-cp-frr-peer"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: "cilium-cp-frr-peer"
spec:
  transport:
    localPort: 179
    peerPort: 179
  #timers:
  #  connectRetryTimeSeconds: 12
  #  holdTimeSeconds: 9
  #  keepAliveTimeSeconds: 3
  #authSecretRef: bgp-auth-secret
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgp"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: "bgp-advertisements"
  labels:
    advertise: "bgp"
spec:
  advertisements:
    #- advertisementType: "LoadBalancerIP"
    - advertisementType: "PodCIDR"
      #serviceSelector:
      #matchLabels:
      #  name: hello-node
      #  matchExpressions:
      #  - { key: app, operator: In, values: [hello-node, hello-node2, hello-node3] }
      attributes:
        communities:
          standard: [ "65001:100" ]
        localPreference: 99
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "mgmt"
  labels:
    environment: mgmt
spec:
  blocks:
    - cidr: "100.64.8.0/22"
  cidrs:
    - cidr: "100.64.12.0/22"
  #serviceSelector:
  #  matchExpressions:
  #    - {key: app, operator: In, values: [hello-node]}
---
```

```

**Comment by dswaffordcw** [comment]
@rastislavs This is ready for review.

Thanks for all of your help!

File: cilium-dbg/cmd/bgp_peer_get.go [hunk 3]
```diff
@@ -54,7 +54,7 @@ func printSummary(peers []*models.BgpPeer) {
 		return peers[i].LocalAsn < peers[j].LocalAsn || peers[i].PeerAddress < peers[j].PeerAddress
 	})
 
-	fmt.Fprintln(w, "Local AS\tPeer AS\tPeer Address\tSession\tUptime\tFamily\tReceived\tAdvertised")
+	fmt.Fprintln(w, "Local AS\tPeer AS\tPeer Address\tSession\tUptime\tFamily\tReceived\tAccepted\tAdvertised")
```
Comment (rastislavs) [inline cilium-dbg/cmd/bgp_peer_get.go]: I would propose to rather not expose `Accepted` counter at this point. It has very minor information benefit - and may actually confuse users.

**Review by rastislavs — CHANGES_REQUESTED** [review]
I would propose to not change the CLI output at his point, otherwise LGTM!

**Comment by dswaffordcw** [comment]
> I would propose to not change the CLI output at his point, otherwise LGTM!

@rastislavs ACK.  I reverted those changes.  Thanks for the thorough review!

**Review by asauber — APPROVED** [review]
dropping an approval since the files owned by my team no longer appear here

**Review by rastislavs — APPROVED** [review]
LGTM now, thanks a lot for your work!
