### PR TITLE
datapath/linux: enable neighbor discovery in unit tests

### LINKED ISSUE #17020: CI: RuntimePrivilegedUnitTests TestArpPingHandling failed, timeout reached while waiting for condition
```
	 START: node_linux_test.go:956: linuxPrivilegedIPv4OnlyTestSuite.TestArpPingHandling
	 START: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest
	 PASS: node_linux_test.go:117: linuxPrivilegedIPv4OnlyTestSuite.SetUpTest	0.002s
	 
	 node_linux_test.go:1071:
	     // insertNeighbor is invoked async, so thus this wait based on last ping
	     wait(nodev1.Identity(), &now, false)
	 node_linux_test.go:1054:
	     c.Assert(err, check.IsNil)
	 ... value *errors.errorString = &errors.errorString{s:"timeout reached while waiting for condition"} ("timeout reached while waiting for condition")
```
Seen in https://jenkins.cilium.io/job/Cilium-PR-Runtime-4.9/5434/testReport/junit/(root)/Suite-runtime/RuntimePrivilegedUnitTests_Run_Tests/

[f25b1682_RuntimePrivilegedUnitTests_Run_Tests.zip](https://github.com/cilium/cilium/files/6907360/f25b1682_RuntimePrivilegedUnitTests_Run_Tests.zip)

Similar to #16221, but this timeout happens after `NodeAdd()`.

### PR DESCRIPTION
**Pull request by aanm**
This option should be enabled in unit tests since it is also enabled as
a flag in the agent.

Fixes: cee08cd2b299 ("daemon: Make L2 neighbor discovery configurable.")
Signed-off-by: André Martins <andre@cilium.io>

Fixes https://github.com/cilium/cilium/issues/17020

### CODE REVIEW

**Comment by aanm** [comment]
test-runtime

File: pkg/datapath/linux/node_linux_test.go [hunk 1]
```diff
@@ -946,6 +946,11 @@ func (s *linuxPrivilegedIPv4OnlyTestSuite) TestArpPingHandling(c *check.C) {
 	runtime.LockOSThread()
 	defer runtime.UnlockOSThread()
 
+	prevEnableL2NeighDiscovery := option.Config.EnableL2NeighDiscovery
+	defer func() { option.Config.EnableL2NeighDiscovery = prevEnableL2NeighDiscovery }()
+
+	option.Config.EnableL2NeighDiscovery = true
```
Comment (aditighag) [inline pkg/datapath/linux/node_linux_test.go:952]: Enabling node port @ L1014 below should've enabled neighbor discovery - https://github.com/cilium/cilium/blob/0a4a393d6554da91d34236bcd2cd0f7b6046f3a4/pkg/datapath/linux/node.go#L1378-L1378?

Comment (aanm) [reply pkg/datapath/linux/node_linux_test.go:952]: If `option.Config.EnableL2NeighDiscovery` is `false` the following will happen:
```golang
		switch {
		case !option.Config.EnableL2NeighDiscovery:
			n.enableNeighDiscovery = false
		case option.Config.EnableNodePort:
```
```golang
		switch {
		case !false:
			n.enableNeighDiscovery = false
		case option.Config.EnableNodePort:
```
```golang
		switch {
		case true:
			n.enableNeighDiscovery = false <---
		case option.Config.EnableNodePort:
```

**Review by aditighag — APPROVED** [review]

File: pkg/datapath/linux/node_linux_test.go (hunk 1 above)
Comment (aditighag) [reply pkg/datapath/linux/node_linux_test.go:952]: Yeah, makes sense. I missed the ordering of switch cases.
